### ISSUE TITLE
canu fails due to #!perl

### ISSUE THREAD

**Issue by tseemann** [marbl/canu#1]
On RHEL the canu master script fails:

```
$ ./Linux-amd64/bin/canu
-bash: ./Linux-amd64/bin/canu: perl: bad interpreter: No such file or directory

$ head -n 1 ./Linux-amd64/bin/canu
#!perl

$ perl -v
This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
```

I've never seen a hash-bang line with a bare exe name.  Perhaps ```#!/usr/bin/env perl``` would be more compatible?

PS.  canu compiled cleanly in 20 seconds on my new server ```make -j 72``` (2 x 18 h/t cores) !!!

**Comment by brianwalenz** [comment]
Yup, that's the solution.  I had committed, but didn't push it out for some reason.

My compiles are down in the 6 second range...but I have the cccache installed.

**Comment by tseemann** [comment]
Thanks @brianwalenz !
