### ISSUE TITLE
Resource errors on large local machine

### ISSUE THREAD

**Issue by ghannum** [marbl/canu#100]
Canu assembly failed repeatably on the error correction step, with the message:
"failed to overlapStoreBucketize"

Logs showed problems with hitting limits on available processes and/or file handles (Ex. 'cannot fork'). Increasing these limits did not resolve the issue. A workaround was found by limiting the number of threads using 'maxThreads=30'.

Machine specs:
120 virtual cores
2TB ram

**Comment by skoren** [comment]
This could be the same issue as #85 where it is over-subscribing the memory. That would cause errors opening files and forking processes. Popen is also considered a fork and the number of sort jobs determines how many files/processes are opened/created. The file handle limit is per user not per job so if you have 100 jobs running in parallel * 100 sort partitions, you'd need 10k file handles so you could still exceed a file handle limit. How high did you increase it?

**Comment by ghannum** [comment]
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 16544511
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 102400
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by brianwalenz** [comment]
Idle, acceptable work around noted (thanks).  The general problem is on our list of things to figure out.
