### ISSUE TITLE
run triocanu erro

### ISSUE THREAD

**Issue by fanyucai1** [marbl/canu#1002]
hi, doctor, when I run triocanu the erro as follows:
-- Starting command on Thu Jul 12 15:26:53 2018 with 46351.146 GB free disk space

    cd .
    /public1/home/pg2001/canu-1.7.1/Linux-amd64/bin/gatekeeperCreate \
      -minlength 50 \
      -o ./haplotypeP2.gkpStore.BUILDING \
      ./haplotypeP2.gkpStore.gkp \
    > ./haplotypeP2.gkpStore.BUILDING.err 2>&1

-- Finished on Thu Jul 12 19:57:59 2018 (16266 seconds) with 45027.006 GB free disk space
----------------------------------------
--
-- WARNING: gnuplot failed.
--
----------------------------------------
--
-- In gatekeeper store './haplotypeP2.gkpStore':
--   Found 649055184 reads.
--   Found 97346405458 bases (29.4 times coverage).
--
--   Read length histogram (one '*' equals 8744289.62 reads):
--        0     99  96813
--      100    199 612100274 **********************************************************************
--
-- Running jobs.  First attempt out of 2.
--

CRASH:
CRASH: Canu 1.7.1
CRASH: Please panic, this is abnormal.
ABORT:
CRASH:   Failed to submit batch jobs.
CRASH:
CRASH: Failed at /public1/home/pg2001/canu-1.7.1/Linux-amd64/bin/../lib/site_perl/canu/Execution.pm line 1101.
CRASH:  canu::Execution::submitOrRunParallelJob('haplotypeP2', 'meryl', 'haplotype/0-mercounts-haplotypeP2', 'meryl', 1) called at /public1/home/pg2001/canu-1.7.1/Linux-amd64/bin/../lib/site_perl/canu/Meryl.pm line 538
CRASH:  canu::Meryl::merylCheck('haplotypeP2', 'hap') called at /public1/home/pg2001/canu-1.7.1/Linux-amd64/bin/trioCanu line 414
CRASH:
CRASH: No log file supplied.

**Comment by brianwalenz** [comment]
Based on your other issue, this isn't a problem any more.
