### ISSUE TITLE
SLURM submission issue

### ISSUE THREAD

**Issue by tatianaliu** [marbl/canu#1004]
Hello, I tried to run the test data of canu on a SLRUM grid. It was failed, and I got the error message as follows.

CRASH: Canu snapshot v1.7 +290 changes (r8982 7e6d8f842c48d8342956e85eb8f267a5415b219a)
CRASH: Please panic, this is abnormal.
ABORT:
CRASH:   Failed to submit batch jobs.
CRASH:
CRASH: Failed at /gpfs/fs0/scratch/a/asher/tatiana/apps/canu/Linux-amd64/bin/../lib/site_perl/canu/Execution.pm line 1222.
CRASH:  canu::Execution::submitOrRunParallelJob("ecoli", "meryl", "correction/0-mercounts", "meryl", 1) called at /gpfs/fs0/scratch/a/asher/tatiana/apps/canu/Linux-amd64/bin/../lib/site_perl/canu/Meryl.pm line 518
CRASH:  canu::Meryl::merylCheck("ecoli", "cor") called at /gpfs/fs0/scratch/a/asher/tatiana/apps/canu/Linux-amd64/bin/canu line 604
CRASH: 
CRASH: Last 50 lines of the relevant log file (correction/0-mercounts/meryl.jobSubmit-01.out):
CRASH:
CRASH: SBATCH WARNING: Cannot find configuration file 'sbatchfilter.conf'
CRASH: Traceback (most recent call last):
CRASH:   File "/opt/slurm/bin/sbatch", line 838, in <module>
CRASH:     main()
CRASH:   File "/opt/slurm/bin/sbatch", line 274, in main
CRASH:     sbatchchecking(sbatchcheck)
CRASH:   File "/opt/slurm/bin/sbatch", line 824, in sbatchchecking
CRASH:     if request[ALLOC] in configsections:
CRASH: NameError: global name 'configsections' is not defined

Here is the command I used, basically, I changed nothing. BTW, It runs fine in "useGrid=false" mode, but that's not the job supposed to be..

canu  -p ecoli -d ecoli-pacbio useGrid=true genomeSize=4.8m gnuplotTested=true -pacbio-raw pacbio.fastq

Thanks!!

**Comment by skoren** [comment]
The error is coming from your SLURM's sbatch command. It sounds like your compute nodes may not be able to submit jobs. If that's the case you won't be able to run Canu on your grid without using useGrid=remote and manually submitting scripts (http://canu.readthedocs.io/en/latest/faq.html#my-run-stopped-with-the-error-failed-to-submit-batch-jobs).

You can see the exact submit command in ```correction/0-mercounts/meryl.jobSubmit-01.sh```, try running it by hand both on the head and a compute node to see if it works or contact your grid support.

**Comment by tatianaliu** [comment]
Indeed, the meryl.jobSubmit-01.sh script shows that the command has not been submit to the nodes correctly. I will contact the sysadm to see if anything we could do on slurm configuration first. If not, then try to submit manually. Thanks!!

**Comment by skoren** [comment]
Any updates on this?

**Comment by tatianaliu** [comment]
Yep. We moved this job to another server, and it works....thank you!
