### ISSUE TITLE
Poor assembly result. How can I improve as much as possible my assembly?

### ISSUE THREAD

**Issue by icruz1989** [marbl/canu#1006]
Dear Dr. Sergey,

I have been assembling two genomes of a plant species. However, one assembly did not work at all. The estimated genome size is about 1.5 Gb and when I run Quast to see the statistics the assembly with Canu was around 400 Mb. The starting coverage was 19.32. I leave my report of the assembly, and I am wondering if can I improve the assembly despite my low coverage PacBio reads? 

Command: 
```
canu -d ensamble_teo1_pacbio -p datura_teo1 genomeSize=1.5g gridOptionscormhap="--mem=40g" merylMemory=62 batMemory=62 gridOptions="--time=168:00:00 --partition=FAST" gnuplotTested=true -pacbio-raw /home/icruz/data/secuencias_pacbio/bamfiles_teo_g/teo1.subreads.fastq 1>run2.log & 
```
CANU ASSEMBLY REPORT:

[datura_teo1.txt](https://github.com/marbl/canu/files/2195459/datura_teo1.txt)

```
Indeed my assembly did not show NG50 statistics in the Canu reports

[UNITIGGING/CONTIGS]
-- Found, in version 1, after unitig construction:
--   contigs:      43123 sequences, total length 314552254 bp (including 192 repeats of total length 2014024 bp).
--   bubbles:      0 sequences, total length 0 bp.
--   unassembled:  1030136 sequences, total length 2941938397 bp.
--
-- Contig sizes based on genome size 1.5gbp:
--
--            NG (bp)  LG (contigs)    sum (bp)
--         ----------  ------------  ----------
--     10       10357          9014   150002626
--     20        2566         35521   300002338
--

[UNITIGGING/CONSENSUS]
-- Found, in version 2, after consensus generation:
--   contigs:      43123 sequences, total length 313699644 bp (including 192 repeats of total length 2011088 bp).
--   bubbles:      0 sequences, total length 0 bp.
--   unassembled:  1030136 sequences, total length 2941661469 bp.
--
-- Contig sizes based on genome size 1.5gbp:
--
--            NG (bp)  LG (contigs)    sum (bp)
--         ----------  ------------  ----------
--     10       10308          9044   150009011
--     20        2499         35834   300001172
```

**Comment by skoren** [comment]
At 19x you're at the low end of supported coverage. The biggest thing you can do to improve your assembly is probably get higher depth. From your report, almost no coverage was left after trimming. I don't see any distinguishable peaks in the kmer histogram either which indicates the corrected reads still have errors. 

See the FAQ for suggestions: http://canu.readthedocs.io/en/latest/faq.html#my-assembly-continuity-is-not-good-how-can-i-improve-it. In particular you want to increase correctErrorRate. You may also want to run 2-3 rounds of round of correction (again see the FAQ for instructions).

**Comment by icruz1989** [comment]
Thank you for the response, I am going to try with this parameters and see what will happen..
