### ISSUE TITLE
Comparing SNVs from SAMtools to assemblies

### ISSUE THREAD

**Issue by Omer-K** [marbl/canu#1007]
I've called SNVs using SAMtools and have compared it to the data from assemblies produced by canu (a gene of several kb). Some SNVs are also noticeable in the contigs, some aren't.

How much sense does that actually makes in corroborating the SNVs which SAMtools called?
Is this a good 'extra way' for affirmation?

Hope the question was clear.
Thanks.

**Comment by skoren** [comment]
I'm not sure what you're comparing? SNV calls using nanopore data against a reference and an assembly against a reference?

**Comment by skoren** [comment]
That seems like a reasonable approach though I expect what filtering you do for your mapping/regions of the assembly where you call SNVs will make a big difference in how many are detected/matching.
