### ISSUE TITLE
--mem-per-cpu parameter for modifying SLURM Grid

### ISSUE THREAD

**Issue by devonorourke** [marbl/canu#1008]
Hi Sergey,

This questions follows a similar problem posted in [issue 998](https://github.com/marbl/canu/issues/998). 

I'm trying to set a `--mem-per-cpu` parameter for a job running on a Linux grid that uses SLURM. My job is currently failing, I believe, because the `_canu.ovlStore.jobSubmit-01.sh` script is asking for a bit more memory than is available per cpu. Here's the full shell script for that job:

```
#!/bin/sh

sbatch \
  --mem-per-cpu=263145g --cpus-per-task=1 -p LM -t 14-00:00:00 -N 1 --mem 1200g -o myluLM_canu.ovlStore.%A_%a.out \
  -D `pwd` -J "ovS_myluLM_canu" \
  -a 1-1 \
  ./myluLM_canu.ovlStore.sh 0 \
> ./myluLM_canu.ovlStore.jobSubmit-01.out 2>&1
```

As you might imagine, each cpu on this cluster, large as it is, does not have 263 Tb of memory...

I thought that perhaps I could modify the `Grid_Slurm.pm` directly, and specify on line 90 to change the amount of memory allocated. Yet even after that update, I get the same issue in the shell created for that job - namely, all the memory on the entire cluster is requested - that change to the `.pm` didn't seem to have an effect.

I suspected perhaps I needed to specify the amount of memory per cpu as a `Grid Option` parameter directly also. So I modified my SLURM script to ensure that the parameters included the following:
```
$CANU \
-s /path/to/my.spec \
-p myjob \
-d /path/to/canu/job \
genomeSize=2.1g -nanopore-raw /path/to/files.gz \
correctedErrorRate=0.105 \
gridOptions="-p LM -t 14-00:00:00 -N 1 --mem 1200g --mem-per-cpu=48"
```

This half worked. The resulting `.sh` file for the newly created job indeed recognizes that we are now specifying 48 Gb of memory per CPU, but unfortunately, it also won't forget what it was doing by default :(

```
#!/bin/sh

sbatch \
  --mem-per-cpu=263145g --cpus-per-task=1 -p LM -t 14-00:00:00 -N 1 --mem 1200g --mem-per-cpu=48 -o myluLM_canu.ovlStore.%A_%a.out \
  -D `pwd` -J "ovS_myluLM_canu" \
  -a 1-1 \
  ./myluLM_canu.ovlStore.sh 0 \
> ./myluLM_canu.ovlStore.jobSubmit-01.out 2>&1
```

Notice the subtle difference on the very first line: there are two `--mem-per-cpu` parameters - the old (unwanted) one first, and the new (wanted) one last.

I'm wondering how exactly I can get rid of the first of the two, while keeping the second. Perhaps there is something in the `.spec` file I can specify?

Thank you very much for your help

**Comment by brianwalenz** [comment]
What version of canu is this?  What stage (correction, trimming, or unitigging)?

What's in the *.ovlStore.config.txt?  If there is a corresponding .err, paste that in too.

If no *.err, rerun the ovStoreConfig command, something like:
```
ovStoreConfig -S ../*seqStore -M 8 -create TEST.config 1-overlapper/ovljob.files
```
Run it from within the same directory that has the current *ovlStore.config file.  The output I'm looking for will be printed to the screen.

**Comment by devonorourke** [comment]
Thanks very much for the quick reply Brian. Sorry for the lack of detail.

**version**
```
Canu snapshot v1.7 +271 changes (r8963 683fa2fe6ec668c8c2c7a6913014154e9414922c)
```
**stage**
Correction  

**details in** `*.ovlStore.config.txt`
```
Configured for:
  numBuckets        1
  numSlices         1
  sortMemory   263145 GB (263144.037 GB)
```

**details in** `*_canu.ovlStore.err`
```
-- SCANNING INPUTS --

      Molaps
------------ ----------------------------------------
    7672.476          1-overlapper/results/000001.ovb
    7860.107          1-overlapper/results/000002.ovb
    6472.748          1-overlapper/results/000003.ovb
    8880.977          1-overlapper/results/000004.ovb
    5001.224          1-overlapper/results/000005.ovb
    1739.190          1-overlapper/results/000006.ovb
   11385.226          1-overlapper/results/000007.ovb
    6587.450          1-overlapper/results/000008.ovb
    6659.313          1-overlapper/results/000009.ovb
    2050.426          1-overlapper/results/000010.ovb
    8604.427          1-overlapper/results/000011.ovb
    5200.720          1-overlapper/results/000012.ovb
     320.412          1-overlapper/results/000013.ovb
------------ ----------------------------------------
   78434.696 overlaps in inputs
  156869.393 overlaps to sort


Allocating space for 156869392626 overlaps.

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Failed with 'Aborted'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::97 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
stores/ovOverlap.H::201 in _ZN9ovOverlap16allocateOverlapsEP7sqStorem()
stores/ovStoreBuild.C::198 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
```

Because there was an `.err` file, I will await further instructions for how to proceed before rerunning.

Thanks again.

**Comment by brianwalenz** [comment]
Give your source an update and try the config step again.  The easiest way to do this (without running ovStoreConfig by hand, that is) is to remove the all the `*ovlStore*` files and directories and restart Canu.

**Comment by devonorourke** [comment]
Thanks Brian,
Apologies for my limited computer literacy. I can certainly remove and restart, but I'm still unclear how I should go about properly specifying the `--mem-per-cpu=` parameter. Perhaps that was never the issue?

**Comment by brianwalenz** [comment]
I don't think that was the problem here.  You were unlucky enough to grab a Canu version in the middle of a bug fix, and the ovStoreConfig command was returning totally bogus values, namely 'sortMemory   263145 GB (263144.037 GB)'.

**Comment by devonorourke** [comment]
After deleting the `*ovlStore*` files and restarting, the new `.sh` file created shows a similar but unique problem: it's now specifying `--mem-per-cpu` with a new (higher!) value in the first of the two redundant parameters...

```
#!/bin/sh

sbatch \
  --mem-per-cpu=701756g --cpus-per-task=1 -p LM -t 14-00:00:00 -N 1 --mem 1200g --mem-per-cpu=48 -o myluLM_canu.ovlStore.%A_%a.out \
  -D `pwd` -J "ovS_myluLM_canu" \
  -a 1-1 \
  ./myluLM_canu.ovlStore.sh 0 \
> ./myluLM_canu.ovlStore.jobSubmit-01.out 2>&1
```

This generates a new SLURM error in the `.out` file for this job:
```
Running job 1 based on SLURM_ARRAY_TASK_ID=1 and offset=0.

Attempting to increase maximum allowed processes and open files.
  Max processes per user limited to 12383940, no increase possible.
  Max open files limited to 51200, no increase possible.

/var/slurmd/job3584911/slurm_script: line 82: 24351 Aborted                 /pylon5/mc3bg6p/devono/software/canu/Linux-amd64/bin/ovStoreBuild -O ./myluLM_canu.ovlStore.BUILDING -S ../myluLM_canu.seqStore -C ./myluLM_canu.ovlStore.config > ./myluLM_canu.ovlStore.err 2>&1
```

**Comment by devonorourke** [comment]
I have a way of being unlucky with these things...

**Comment by brianwalenz** [comment]
You did do a 'git pull' and 'make' to rebuild Canu, right?  `canu -version` should report it's at snapshot +292 r8984.

Look in canu-scripts/*out for the ovStoreConfig command, and run that by hand.

**Comment by devonorourke** [comment]
I did not. Sorry. There goes my computer literacy. 
Will redo now.
Thanks for your patience

**Comment by devonorourke** [comment]
Updated newest version:

```
```

Deleted all previous `*ovlStore*` files/directories. 

Restarted. Current `*OvlStore.config.txt` file is reporting:
```
Configured for:
  numBuckets        4
  numSlices         4
  sortMemory     1170 GB (1168.952 GB)
```

In addition, a `*.ovlStore.BUILDING` directory was created this time, which has not previously been the case. Within `*ovlStore.BUILDING/scripts` there is a `1-bucketize-jobSubmit-01.sh` shell script which reports:

```
#!/bin/sh

sbatch \
  --mem-per-cpu=1200g --cpus-per-task=1 -p LM -t 14-00:00:00 -N 1 --mem 1200g --mem-per-cpu=48 -o logs/1-bucketize.%A_%a.out \
  -D `pwd` -J "ovB_myluLM_canu" \
  -a 1-4 \
  ./scripts/1-bucketize.sh 0 \
> ./scripts/1-bucketize.jobSubmit-01.out 2>&1
```

So while it's no longer reporting the gigantic memory per CPU value, there again appears to be the non-redundant `--mem-per-cpu` parameters. 

The SLURM script I'm passing to run the program looks like this:
```
#!/bin/bash

#SBATCH -D /pylon5/mc3bg6p/devono/assembly/canu/mylu
#SBATCH -J LUcanuLM
#SBATCH -p LM
#SBATCH --mail-type=ALL
#SBATCH --mail-user=devon.orourke@gmail.com
#SBATCH --mem 1300Gb
#SBATCH --mem-per-cpu=48
#SBATCH -N 1
#SBATCH -t 14-00:00:00
#SBATCH --export=ALL
set -x

CANU=/pylon5/mc3bg6p/devono/software/canu/Linux-amd64/bin/canu

$CANU \
-s /home/devono/scripts/canu/myluLM.spec \
-p myluLM_canu \
-d /pylon5/mc3bg6p/devono/assembly/canu/mylu \
genomeSize=2.1g -nanopore-raw \
/pylon5/mc3bg6p/devono/reads/nanopore/mylu/fqtrim/chop_mylu.fastq.gz \
correctedErrorRate=0.105 \
gridOptions="-p LM -t 14-00:00:00 -N 1 --mem 1200g --mem-per-cpu=48"
```
I was passing `--mem 1200g` and `--mem-per-cpu=48` thinking these were distinct parameters, but perhaps both are interpreted as the same `--mem-per-cpu` by canu?

**Comment by brianwalenz** [comment]
That looks a lot better!

In general, you shouldn't be setting the slurm memory explicitly; canu will do it for you.  The preferred way to run with a grid is to run canu directly on the head node, let it figure out what nodes are available, and let it do all job submission (including itself the first time).

For your grid, I think you'd need to include the -J and mail options in gridOptions, and remove both mem settings and -N.

**Comment by devonorourke** [comment]
Thanks Brian,
I'm fortunate to have access to a cluster that has a lot of resources, but there are multiple partitions with different hardware resources, and each partition has to be accessed with an independent SLURM submission. Because all are under SLURM control, so I don't think I'll ever be able to run directly via a head node (though that would be awesome). `canu` recognizes a number of these resources in the array:
```
-- Found   2 hosts with 288 cores and 1209 GB memory under Slurm control.
-- Found 768 hosts with  28 cores and  125 GB memory under Slurm control.
-- Found  42 hosts with  32 cores and  125 GB memory under Slurm control.
-- Found   8 hosts with  64 cores and 3023 GB memory under Slurm control.
-- Found  34 hosts with  80 cores and 3023 GB memory under Slurm control.
-- Found   1 host  with 704 cores and 1209 GB memory under Slurm control.
-- Found   1 host  with 352 cores and 1209 GB memory under Slurm control.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl   1200 GB   32 CPUs  (k-mer counting)
-- Grid:  cormhap 1200 GB   16 CPUs  (overlap detection with mhap)
-- Grid:  obtovl  1200 GB   16 CPUs  (overlap detection)
-- Grid:  utgovl  1200 GB   16 CPUs  (overlap detection)
-- Grid:  cor     1200 GB    4 CPUs  (read correction)
-- Grid:  ovb     1200 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs     1200 GB    1 CPU   (overlap store sorting)
-- Grid:  red     1200 GB    8 CPUs  (read error detection)
-- Grid:  oea     1200 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat     1200 GB   32 CPUs  (contig construction with bogart)
-- Grid:  cns     1200 GB    8 CPUs  (consensus)
-- Grid:  gfa       32 GB   32 CPUs  (GFA alignment and processing)
```

I think there is still a fundamental problem in that the first ` --mem-per-cpu` parameter which canu seems to automatically add to the `sbatch` script is still not correct. As you can see below, there are still two `--mem-per-cpu` arguments, the first of which is not correct:

```
#!/bin/sh

sbatch \
  --mem-per-cpu=1200g --cpus-per-task=1 -p LM -t 14-00:00:00 -N 1 --mem 1200g --mem-per-cpu=48 -o logs/1-bucketize.%A_%a.out \
  -D `pwd` -J "ovB_myluLM_canu" \
  -a 1-4 \
  ./scripts/1-bucketize.sh 0 \
> ./scripts/1-bucketize.jobSubmit-01.out 2>&1
```

It's my understanding that the `#SBATCH` commands specifying `--mem` is essential for this particular grid set up because the partition I'm specifying to run the job shares memory with other jobs. 

So I'm stuck trying to figure out exactly what to do. As I'm not in a position to change the grid parameters, or run anything form the head node, I'm curious what you would advise?

Thanks for your help throughout this process.

Devon

**Comment by skoren** [comment]
The first request for memory is correct, you can request memory on slurm using either mem or mem-per-cpu. Both are equally valid and in this case equivalent since only one cpu is requested. The next two requests which you provided will overwrite the first so only the last (```--mem-per-cpu=48```) will be active which is wrong and will make the job fail. As @brianwalenz said, you shouldn't specify memory in gridOptions, let canu manage the request.

You can certainly run on a slurm grid with multiple partitions, we do this all the time. You could just provide the required flags to reserve a specific partition with gridOptions. Alternatively, set maxMemory to a smaller size (e.g. 120 in your case) and it will restrict Canu to the smaller memory partition on  your grid.

**Comment by devonorourke** [comment]
I think I'm starting to follow. Sorry, I understand this must be painfully obvious to you.

The job I restarted crashed almost immediately. I submitted this script, which as removed the `--mem` and `--mem-per-cpu` flags used earlier:

```
#!/bin/bash

#SBATCH -D /pylon5/mc3bg6p/devono/assembly/canu/mylu
#SBATCH -J LUcanuLM
#SBATCH -p LM
#SBATCH --mail-type=ALL
#SBATCH --mail-user=devon.orourke@gmail.com
#SBATCH --mem 1300Gb
#SBATCH --mem-per-cpu=48
#SBATCH -N 1
#SBATCH -t 14-00:00:00
#SBATCH --export=ALL
set -x

CANU=/pylon5/mc3bg6p/devono/software/canu/Linux-amd64/bin/canu

$CANU \
-s /home/devono/scripts/canu/myluLM.spec \
-p myluLM_canu \
-d /pylon5/mc3bg6p/devono/assembly/canu/mylu \
genomeSize=2.1g -nanopore-raw \
/pylon5/mc3bg6p/devono/reads/nanopore/mylu/fqtrim/chop_mylu.fastq.gz \
correctedErrorRate=0.105 \
gridOptions="-p LM -t 14-00:00:00"
```

The SLURM message suggests that I'm trying to acquire more processors than I'm permitted:
```
-- BEGIN CORRECTION
--
--
-- Creating overlap store correction/myluLM_canu.ovlStore using:
--      4 buckets
--      4 slices
--        using at most 1170 GB memory each
-- Overlap store bucketizer finished.
--
-- Running jobs.  First attempt out of 2.
--

CRASH:
CRASH: Canu snapshot v1.7 +292 changes (r8984 187d7b05fea762ea2a31a2d741946b3ba50a78cd)
CRASH: Please panic, this is abnormal.
ABORT:
CRASH:   Failed to submit batch jobs.
CRASH:
CRASH: Failed at /pylon5/mc3bg6p/devono/software/canu/Linux-amd64/bin/../lib/site_perl/canu/Execution.pm line 1222.
CRASH: 	canu::Execution::submitOrRunParallelJob('myluLM_canu', 'ovS', 'correction/myluLM_canu.ovlStore.BUILDING', 'scripts/2-sort', 1, 2, 3, 4) called at /pylon5/mc3bg6p/devono/software/c
anu/Linux-amd64/bin/../lib/site_perl/canu/OverlapStore.pm line 582
CRASH: 	canu::OverlapStore::overlapStoreSorterCheck('correction', 'myluLM_canu', 'cor', 4, 4) called at /pylon5/mc3bg6p/devono/software/canu/Linux-amd64/bin/../lib/site_perl/canu/OverlapS
tore.pm line 807
CRASH: 	canu::OverlapStore::createOverlapStore('myluLM_canu', 'cor') called at /pylon5/mc3bg6p/devono/software/canu/Linux-amd64/bin/canu line 583
CRASH: 	main::overlap('myluLM_canu', 'cor') called at /pylon5/mc3bg6p/devono/software/canu/Linux-amd64/bin/canu line 607
CRASH: 
CRASH: Last 50 lines of the relevant log file (correction/myluLM_canu.ovlStore.BUILDING/scripts/2-sort.jobSubmit-01.out):
CRASH:
CRASH: sbatch: error: Batch job submission failed: More processors requested than permitted
CRASH:
```

I have a `.spec` file that's attached to this SLURM script that only specifies memory usage; perhaps I should be amending how many threads to allocate for these tasks also? I wonder if that is why jobs are stopping?
 
```
## mylu.spec 
cnsMemory=1200
corMemory=1200
redMemory=1200
oeaMemory=1200
ovlMemory=1200
corovlMemory=1200
obtovlMemory=1200
utgovlMemory=1200
mhapMemory=1200
cormhapMemory=1200
obtmhapMemory=1200
utgmhapMemory=1200
mmapMemory=1200
cormmapMemory=1200
obtmmapMemory=1200
utgmmapMemory=1200
ovbMemory=1200
ovsMemory=1200
batMemory=1200
merylMemory=1200
```

**Comment by devonorourke** [comment]
It appears that the grid administrators here have a few examples on their partitions that do exactly that - their `.spec` files all include specified Thread values for every process, but it's very redundant:

```
gridOptions="-p LM -t 7-00:00:00 --mem=1000G --cpus-per-task=21"
batMemory=950
batThreads=21
merylMemory=950
merylThreads=21
ovbMemory=950
ovbThreads=21
ovsMemory=950
ovsThreads=21
cnsMemory=950
cnsThreads=21
corMemory=950
corThreads=21
cormhapMemory=950
cormhapThreads=21
obtmhapMemory=950
obtmhapThreads=21
utgmhapMemory=950
utgmhapThreads=21
corovlMemory=950
corovlThreads=21
obtovlMemory=950
obtovlThreads=21
utgovlMemory=950
utgovlThreads=21
cormmapMemory=950
cormmapThreads=21
obtmmapMemory=950
obtmmapThreads=21
utgmmapMemory=950
utgmmapThreads=21
redMemory=950
redThreads=21
oeaMemory=950
oeaThreads=21
```

Isn't there a way to specify something like `master` so that you only have to write this once for every task?

Thanks again

**Comment by skoren** [comment]
I again wouldn't specify the memory or threads, 1.2tb quite a lot more than most of these jobs would need, so just don't use any spec file.

Your grid is complaining about the job requesting more than allowed CPUs but it's only asking for one (the exact command is in ```correction/myluLM_canu.ovlStore.BUILDING/scripts/2-sort.jobSubmit-01.sh```). This job is an array of 4 jobs each sorting a different part and I'd guess you have a limit on your cluster which limits how many jobs using 1.2tb you can launch at the same time. Either way, you'd have to figure out with your cluster admin why that command was not accepted and how to make it acceptable (and then provide the required options to canu).

**Comment by macmanes** [comment]
I think the main issue here is that on the specific system @devonorourke is using, (XSEDE PSC Bridges), the Large Memory partition requires you specify memory, which in turn determines the number of cores you are allocated. 

```

**Comment by macmanes** [comment]
Jobs submitted to the LM partition must request the amount of memory they need rather than the number of cores. Each core on the 3TB and 12TB nodes is associated with a fixed amount of memory, so the amount of memory you request determines the number of cores assigned to your job. The environment variable SLURM_NTASKS tells you the number of cores assigned to your job. Since there is no default memory value you must always include the --mem option for the LM partition.

**Comment by skoren** [comment]
I don't know why random clusters disable features the grid engine naturally supports? The canu submission is standard by SLURM specification, the cluster isn't implementing SLURM commands correctly. 

You can probably just use the RM-shared partition with lets you specify cores but not memory, 128gb should be enough for most steps. Then, look at the canu preamble where it describes the resources it wants to use (do not specify any of the memory/threads parameters or spec file when you run it):
```
-- Grid:  meryl    100 GB   28 CPUs  (k-mer counting)
-- Grid:  cormhap   17 GB    8 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    24 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl    24 GB    8 CPUs  (overlap detection)
-- Grid:  ovb        2 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       32 GB    1 CPU   (overlap store sorting)
-- Grid:  red       32 GB    4 CPUs  (read error detection)
-- Grid:  oea       32 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      100 GB   28 CPUs  (contig construction)
-- Grid:  gfa       32 GB   28 CPUs  (GFA alignment and processing)
```
Compute the amount of cores you need to request to get the right memory request. That is, if you have a 128gb machine with 28 cores then the per core memory is 4.5g. So for the above example you'd need to request:
```
ovsThreads=8
redReads=8
```
The rest are already using < 4.5g/core. You can then also hard-code the rest of the request that Canu selected similar to your current spec just to make sure you always select the same resources for any genome.  I assume it will just ignore the memory request canu provides but if not reset ```gridEngineThreadsOption="-p RM-shared --time=48:00:00```. You can put all these parameters in either ```~/.canu``` or the canu bin path under canu.defaults.
