### ISSUE TITLE
Meryl failed lickety-split 

### ISSUE THREAD

**Issue by indapa** [marbl/canu#1010]
Hi Canu team,

I'm trying to error correct my raw pacbio reads and meryl is failing. Here is my command line:

```
~/canu-1.7.1/Linux-amd64/bin/canu  -correct -p canu_ -d canu_run1 genomeSize=195100 \\
  -pacbio-raw subreads.fastq
```

Meryl fails:

```
- Running jobs.  Second attempt out of 2.                                              
----------------------------------------                                                
-- Starting 'meryl' concurrent execution on Tue Jul 17 16:30:31 2018 with 9837.844 GB free disk space (1 processes; 1 concurrently)

    cd correction/0-mercounts
    ./meryl.sh 1 > ./meryl.000001.out 2>&1

-- Finished on Tue Jul 17 16:30:31 2018 (lickety-split) with 9837.844 GB free disk space

```

The meryl.000001.out file contents is:

```
sh: ./meryl.sh: Permission denied
```

This makes me think meryl isn't installed properly or the bash script is looking in the wrong place. But when I compiled the latest source  code release, it worked fine.  

I'm working on  Linux x86_64 system.

**Comment by skoren** [comment]
Right before running meryl.sh it gets chmoded (0755), this seems to have not happened. Can you run ```sh ./meryl.sh``` from within the ```correction/0-mercounts``` folder? That would confirm meryl is correctly installed and the script is fine, just chmod failed. What if you manually chmod the file? What does ```umask``` report?

**Comment by indapa** [comment]
Thanks for your reply @skoren. When I excute meryl.sh within the ```correction/0-mercounts``` folder I get a segmentation fault:

```
sh ./meryl.sh
seqFactory::openFile()--  Cannot determine type of file '../canu_sample.gkpStore'.  Tried:
seqFactory::openFile()--         'FastA'
seqFactory::openFile()--         'FastAstream'
seqFactory::openFile()--         'Fastq'
seqFactory::openFile()--         'FastQstream'
seqFactory::openFile()--         'seqStore'
seqFactory::openFile()--         'GKSTORE'
./meryl.sh: line 58:  4136 Segmentation fault      (core dumped) $bin/estimate-mer-threshold -h ./canu_sample.ms16.histogram -c 15987 > ./canu_sample.ms16.estMerThresh.out.WORKING 2> ./canu_sample.ms16.estMerThresh.err

```



Looking at the *.histogram.info file it reads:

```
merylStreamReader()-- ERROR: Didn't find data files for reading mer data.
merylStreamReader()-- ERROR: Expecting to find './canu_sample.ms16.mcidx' and
merylStreamReader()-- ERROR:                   './canu_sample.ms16.mcdat'


```

``` uname ``` returns ``` 0022```

**Comment by skoren** [comment]
Those are very different errors. More importantly, you can't get to 0-meryl without having a valid gkpStore but the error is saying you don't have one. Can you confirm the folder ```canu_sample.gkpStore``` exists and what files it contains, in particular post the contents of ```info.txt```. What OS/filesystem are you running this on?
