### ISSUE TITLE
How does canu perform error correction for sequel data?

### ISSUE THREAD

**Issue by lakhujanivijay** [marbl/canu#1011]
Hi 

I have Pacbio sequel data for bacterial samples. I am trying to assemble it using canu

```
[mypc]$ canu -version
Canu v0.0 (+0 commits) r0 unknown-hash-tag-no-repository-available.
```
> I am not sure why the version command is not working but I can assure you that the assembly works without any issue. 

The command was
`[mypc]$  canu -p sample -d sample genomeSize=4.1m -pacbio-raw sample.fq`

I initially had the `bam` files which were converted into `fastq` files using `samtools`. The command used was

`[mypc]$ samtools fastq -0 sample.fq -@ 55 sample.bam`

My question is that since pacbio sequel [data have arbitrary phred score values](https://github.com/marbl/canu/issues/745) (!) marks, how will canu perform error correction. Are quality values indeed used for error correction?

**Comment by skoren** [comment]
See issue #1009, quality isn't used. As for the version, I think you have an older Canu version (versions before 1.5 reported 0.0), downloading the latest should fix it.
