### ISSUE TITLE
Different results with fastq and fastq converted fasta files

### ISSUE THREAD

**Issue by lakhujanivijay** [marbl/canu#1013]
May be I am working with an older version of canu as explained in [this](https://github.com/marbl/canu/issues/1011) earlier post. I tried running the assembly with both fastq file (from pacbio sequel data) and fasta file (converted from the same fastq file). I am getting _slightly_ different results with same canu command.

**with fastq file**

```
[mypc]$ canu -p sample -d sample genomeSize=4.1m -pacbio-raw sample.fq

num_contigs = 53
total genome length = 4859398
Max contig size = 297503
Min contig size = 6158
```

**with fasta file**

```
[mypc]$ canu -p sample -d sample genomeSize=4.1m -pacbio-raw sample.fa

num_contigs = 53
total genome length = 4859397
Max contig size = 297504
Min contig size = 6158
```
As you can see that one of the contigs in the assembly generated by fasta file larger by 1 bp than the assembly generated by fastq file. Is this expected?

**Comment by brianwalenz** [comment]
Expected.  The contig consensus algorithm is slightly non-deterministic in that it can apply the evidence read alignments in a different order on each run.  I've only seen this at the ends of contigs, and suspect it happens in regions of 2x coverage, where the tie is broken by whatever evidence is seen first.

I don't think read correction is susceptible to the same problem, but I'm not 100% positive.

**Comment by lakhujanivijay** [comment]
I want to understand how read correction actually works. If read quality is not important in this case, how the correction works? Can you please provide some thoughts on this; may be some external links?

**Comment by skoren** [comment]
The canu paper has the overview of the correction algorithm for the reads and the final consensus.

As @brianwalenz  said, I don't think correction is going to be different between your fastq and fasta inputs. The corrected reads (```*.correctedReads.fasta.gz```), trimmed reads (```*.trimmedReads.fasta.gz```), unitigs (```unitigging/4-unitigger/*.sizes```) should all match between the two runs. The non deterministic bit is calling the final consensus which is using the corrected reads and the order the reads are added in slightly alters results (e.g. your 1bp out of 4.85 Mbp).
