### ISSUE TITLE
canu job very long in correction step

### ISSUE THREAD

**Issue by splaisan** [marbl/canu#1017]
Hi

I submitted a full run and find that the current correction step (below) is going rather slow and using only few threads and RAM (I have much more avail on the server)

```
canu -d canuOUT genomeSize=400m -nanopore-raw ./ont.fq.gz -p canutry1 overlapper=mhap utgReAlign=true
```

Could you please tell me if I could tune the command to use more and get to results faster

```
...
-- Finished on Fri Jul 20 23:32:08 2018 (1 second) with 258.962 GB free disk space
----------------------------------------
--
-- Set corMemory to 2 GB based on read 696150 of length 207312 with 767 overlaps of average size 19295.
--
-- Using overlaps no worse than 0.5 fraction error for correcting reads (from corErrorRate parameter).
-- Finished stage 'cor-buildCorrectionLayouts', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'cor' concurrent execution on Fri Jul 20 23:32:10 2018 with 258.962 GB free disk space (152 processes; 1 concurrently)
```

This is now using only 4 thread from htop and a tot of 16G RAM while I have 88:500, all the rest being idle.

REM: I am still running 1.6

Thanks

**Comment by skoren** [comment]
Based on the fact that it's got 152 jobs to run but only running one concurrently, it doesn't seem that Canu detected your full node resources. What's the full Canu log, including the preamble that describes resources to use for each step.

**Comment by skoren** [comment]
Ah, you originally said it was 1.6 not an intermediate checkout. There was a bug (issue #613) around that time which ran only one correction job at a time. You can either use the workaround there (set corConcurrency) or update to version 1.7.1.

**Comment by splaisan** [comment]
my mistake indeed, I noticed afterwards I had softlinked the intermediate github version while I thought I was using a release.
I restarted the job now with 1.7.1 and will soon pass this stage.
Thanks for your feedback and help.
Best
Stephane
