### ISSUE TITLE
Canu read correction  fails

### ISSUE THREAD

**Issue by amitvas** [marbl/canu#1024]
Canu keeps failing on the precompute step.  I'm trying to correct RNA-seq reads and have a minoverlap of 200 and minreadlength of 200.

the precompute files have the error below

![image](https://user-images.githubusercontent.com/30876937/43530092-57b652da-9572-11e8-8931-aa0fdb261600.png)

**Comment by amitvas** [comment]
Thanks!  I did that, and limited the memory usage.  

I now have another problem with the corrected reads.

If I open a correctReads.out file I get this:

Running job 159 based on command line options.
./correctReads.sh: line 766: 18003 Done(141)               ( $bin/generateCorrectionLayouts -b $bgn -e $end -rl ./C102.readsToCorrect -G $gkpStore -O ../C102.ovlStore -S ./C102.globalScores -C 80 -F && touch ./correction_outputs/$jobid.dump.success )
     18004 Killed                  | $bin/falcon_sense --min_idt 0.5 --min_len 1000 --max_read_len 915378 --min_ovl_len 500 --min_cov 4 --n_core 2 > ./correction_outputs/$jobid.fasta.WORKING 2> ./correction_outputs/$jobid.err
Read layout generation failed.
mv: cannot stat â€˜./correction_outputs/0159.fastaâ€™: No such file or directory

**Comment by skoren** [comment]
This looks like the same error, not enough memory getting the job killed. 

I think you're on an older version of Canu (1.6?) and memory usage/tracking has been improved in this step in particular so I'd suggest updating to 1.7.1 and re-running with that. You'd have to restart from scratch. Alternatively, increase the memory request for your job to be higher.

**Comment by amitvas** [comment]
no, This is the latest version of canu.  I installed it right before the run

**Comment by skoren** [comment]
The latest version does not call generateCorrectionLayouts and falcon_sense separately, it should just call falconsense. You can see this if you look at the code for the 1.7.1 branch:
https://github.com/marbl/canu/blob/v1.7.1/src/pipelines/canu/CorrectReads.pm

So whatever version generated that shell script is not the latest. It's possible you have multiple versions installed and launched an older one. The shell script should also report the path to the canu version it is using and you can run ```canu -version``` to confirm.

**Comment by amitvas** [comment]
Thanks!  will work on getting the latest version.  Everytime I have tried to install it with bioconda it apparently gets the v1.5 or earlier
