### ISSUE TITLE
Read correction jobs failed

### ISSUE THREAD

**Issue by YuyaKiguchi** [marbl/canu#1026]
Dear canu Developers,

System and command info
OS: Linux-3.10.0-514.10.2.el7.x86_64-x86_64-with-Ubuntu-18.04-bionic
Command: 
`canu -correct -p KG-V_deb_S1_filter6_ref_canu -d KG-V_deb_S1_filter6_ref_canu_correct genomeSize=10m maxThreads=50 -pacbio-raw KG-V_deb_S1_m54244_180705_095417.subreads.rm_ctrl_hg.rm_dup.filter6.split.rm_chimera.fasta > log_canu_correct 2>&1 &`

I run canu for pacbio metagenomic read correction and getting following error.

`-- Read correction jobs failed, retry.
--   job 2-correction/results/0058.cns FAILED.`

Please check canu log attached.

[
[log_canu_correct.txt](https://github.com/marbl/canu/files/2253354/log_canu_correct.txt)
](url)

Thank you.

Yuya

**Comment by skoren** [comment]
I would guess this is the same as issue #881 and #880 and your code is from before that fix. I suggest updating to the latest in the repo and re-running from scratch to see if the error is fixed.

**Comment by brianwalenz** [comment]
Assuming resolved.

**Comment by YuyaKiguchi** [comment]
Thank you skoren and brianwalenz.
This problem has been resolved to update.
