### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by laurafisch9** [marbl/canu#1029]
I am trying to install canu on my local MacOS and a Linux server using the make file.

Every time I try to install the program I get this error

In file included from AS_UTL/AS_UTL_alloc.H:37:
/Users/Laura/Documents/programs/canu-1.7.1/src/AS_global.H:94:/Users/Laura/Documents/programs/canu-1.7.1/src/AS_global.H10::94 :10: fatal error: fatal error
:       'omp.h' 
file       'omp.h'not  filefound not
 found
#include <omp.h>
#include <omp.h>         ^ 

         ^ 
1 error generated.
make: *** [/Users/Laura/Documents/programs/canu-1.7.1/Darwin-amd64/obj/lib/libcanu.a/AS_UTL/AS_UTL_stackTrace.o] Error 1
In file included from AS_UTL/bitPackedFile.C:46In file included from :
AS_UTL/bitEncodings.C:26:
In file included from /Users/Laura/Documents/programs/canu-1.7.1/src/AS_global.HAS_UTL/bitEncodings.H::9426::
10: /Users/Laura/Documents/programs/canu-1.7.1/src/AS_global.H:94fatal error:: 10: 
      'omp.h' filefatal error : not found

**Comment by skoren** [comment]
You need a compiler which supports openmp. The default clang on OS X does not and has other quirks so we do not support building with it. Installing a recent (4.8.5 or newer) gcc should let you build. I've also added binaries to the latest release so you can just use those without building yourself.
