### ISSUE TITLE
unassembled file

### ISSUE THREAD

**Issue by woodoo46** [marbl/canu#103]
What kind of data is put in to *unassembled.fasta? It seems that there are not only single reads? Thanks.

**Comment by skoren** [comment]
It is singletons and pseudo-singletons where the contig has more than one read but is essentially unassembled. Currently, this means contigs with the majority of their bases in a single read (so most of the other reads are contained) or contigs with <2X coverage over a large fraction of their length.

**Comment by woodoo46** [comment]
So, is this normal? 
> tig00179397 len=30911 reads=1652 covStat=-1104.42

**Comment by woodoo46** [comment]
Can we reuse these kinds of "contig"?

**Comment by skoren** [comment]
Yes, that is normal, though it shouldn't be the majority of the unassembled file. Here is an example from a mammalian asm we have locally:
```
>tig01024191 len=35827 reads=1419 covStat=-927.97 gappedBases=no class=unassm suggestRepeat=yes suggestCircular=no
```

You can see it has >1K reads and a very negative a-stat. It is likely an unassembled and collapsed repeat. The asm.layout.readToTig file will give you the location of the reads in this unitig. In my case, there is a single read:

```
5207899	1024191	ungapped	176	35762
```
which covers all but about 300 bases so essentially this is one very long read from a repeat region with all other reads it contains collapsed into it.
