### ISSUE TITLE
No share dir in release

### ISSUE THREAD

**Issue by Danos2000** [marbl/canu#1031]
Hopefully this is not just me being dense. I downloaded the latest Darwin release on my personal Mac (10.12.6) and installed as per the release directions. When I run canu, however, it fails:

```
Starting mhap precompute.

Error: Unable to access jarfile [MYPATH]/canu-1.7.1/Darwin-amd64/bin/../share/java/classes/mhap-2.1.3.jar
Mhap failed.
```

I went back and looked in the directory it's trying to access, and in the `/canu-1.7.1/Darwin-amd64/` directory there are only two directories, `bin` and `lib`. No `share` directory there.

I have an older version of canu elsewhere that I compiled myself, and in the `/Darwin-amd64/` dir for that one, there are four directories: `bin`, `lib`, `obj`, and `share`.

I repeated the download and unzip just to be sure, but still no `share` dir. Any idea how I'm not getting that one?

**Comment by skoren** [comment]
Nope, not you. The release package missed those directories, try downloading again.

**Comment by Danos2000** [comment]
Excellent, thanks. I see the `share` dir now. Will try running it soon.
