### ISSUE TITLE
Getting the canu test to work.

### ISSUE THREAD

**Issue by laurafisch9** [marbl/canu#1036]
I am trying to work with canu on my local macOS machine and on a linux server.
At both locations I tried to run the following command on the ecoli fasta test file

```~/assemblers/canu-1.7.1/Darwin-amd64/bin/canu -p ecoli -d ecoli-oxford  genomeSize=4.8m  -nanopore-raw oxford.fasta```

For the linux server here is the issue

```
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Thu Aug  9 10:28:19 2018 with 13395.891 GB free disk space

    cd .
    /slipstream/home/LauraF/assemblers/canu-1.7.1/gatekeeperCreate \
      -minlength 1000 \
      -o ./ecoli.gkpStore.BUILDING \
      ./ecoli.gkpStore.gkp \
    > ./ecoli.gkpStore.BUILDING.err 2>&1

-- Finished on Thu Aug  9 10:28:19 2018 (lickety-split) with 13395.891 GB free disk space
----------------------------------------

ERROR:
ERROR:  Failed with exit code 127.  (rc=32512)
ERROR:

ABORT:
ABORT: 
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   gatekeeper failed.
ABORT:
ABORT: Disk space available:  13395.891 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (./ecoli.gkpStore.BUILDING.err):
ABORT:
ABORT:
```

For my macbook here is the error that was returns

```
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'cormhap' concurrent execution on Thu Aug  9 10:13:39 2018 with 46.56 GB free disk space (3 processes; 1 concurrently)

    cd correction/1-overlapper
    ./precompute.sh 1 > ./precompute.000001.out 2>&1
    ./precompute.sh 2 > ./precompute.000002.out 2>&1
    ./precompute.sh 3 > ./precompute.000003.out 2>&1

-- Finished on Thu Aug  9 10:13:40 2018 (1 second) with 46.429 GB free disk space
----------------------------------------
--
-- Mhap precompute jobs failed, retry.
--   job correction/1-overlapper/blocks/000001.dat FAILED.
--   job correction/1-overlapper/blocks/000002.dat FAILED.
--   job correction/1-overlapper/blocks/000003.dat FAILED.
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'cormhap' concurrent execution on Thu Aug  9 10:13:40 2018 with 46.429 GB free disk space (3 processes; 1 concurrently)

    cd correction/1-overlapper
    ./precompute.sh 1 > ./precompute.000001.out 2>&1
    ./precompute.sh 2 > ./precompute.000002.out 2>&1
    ./precompute.sh 3 > ./precompute.000003.out 2>&1

-- Finished on Thu Aug  9 10:13:41 2018 (1 second) with 46.429 GB free disk space
----------------------------------------
--
-- Mhap precompute jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/blocks/000001.dat FAILED.
--   job correction/1-overlapper/blocks/000002.dat FAILED.
--   job correction/1-overlapper/blocks/000003.dat FAILED.
--

ABORT:
ABORT: Canu 1.7.1
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```

**Comment by skoren** [comment]
For the linux run, what happens if you run:
```
    /slipstream/home/LauraF/assemblers/canu-1.7.1/gatekeeperCreate
```

For OSX, it is failing due to the the JVM, the ```correction/1-overlapper/precompute.*.out``` files will have more info.

**Comment by laurafisch9** [comment]
How exactly am I supposed to run this new path with ```gatekeeperCreate``` 
Is this a full restart from the beginning? Or do I run this command on the files that have already been created?

Here is the output from the *.out files

```
Running job 1 based on command line options.
Dumping reads from 1 to 9000 (inclusive).

Starting mhap precompute.

Unrecognized option: -d64
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Mhap failed.

```

**Comment by skoren** [comment]
Just run the standalone command, I want to see if there was an issue with the compilation of the linux code.

For OS X it looks like you have JVM 10 which removed a previous option. It's fixed in tip (issue #901) but not the 1.7.1 release. To fix it you'd have to either downgrade to JVM8 or 9 on your mac or edit the code in ```Darwin-amd64/lib/site_perl/canu/OverlapMhap.pm``` to remove the -d64 parameter. There should be two places.

**Comment by laurafisch9** [comment]
I ran the standalone command just like this in my terminal window on the server

```/slipstream/home/LauraF/assemblers/canu-1.7.1/Darwin-amd64/bin/gatekeeperCreate ```

Here is the resul
```/slipstream/home/LauraF/assemblers/canu-1.7.1/Darwin-amd64/bin/gatekeeperCreate: cannot execute binary file: Exec format error```

**Comment by skoren** [comment]
Let's look at one machine at a time. The OS X issue is the JDK, the binaries work fine. You need to either install an older JVM and point canu to it using the ```java=``` parameter or update the code as I described.

For the linux system, your command which was failing gave the path: ```/slipstream/home/LauraF/assemblers/canu-1.7.1/gatekeeperCreate```  which is what I wanted too see run. The darwin binaries are definitely not going to work on a linux system.

**Comment by laurafisch9** [comment]
I successfully ran the ecoli test using canu on the linux server using the correct binaries.
I am going to try and assemble genomes on the server and wait to use my local mac.

Thanks very much for all your help. This issue can be considered close

**Comment by skoren** [comment]
OK good to know. The JDK issue will be fixed in the next release as well so you'll definitely be able to run on the mac then.
