### ISSUE TITLE
Failed to output trimmed reads

### ISSUE THREAD

**Issue by laurafisch9** [marbl/canu#1037]
Since my data is lower quality, I wanted to just some parameters 
It looks like the end result was all of the reads were deleted during trimming.
Why would this happen when I adjust the parameters. A default canu run worked on the same data set.

**command:**
```
~/assemblers/canu-1.7.1/Linux-amd64/bin/canu -p p_temperatura -d lenient_p_temperatura genomeSize=3.2m correctedErrorRate=0.108 minOverlapLength=300 -nanopore-corrected ~/FN58_diamond_blast_runs/planktomarina/long_reads/plankto_reads.fastq
```

**Issue:**

```
ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:

ABORT:
ABORT: Canu 1.7.1
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to output trimmed reads.
ABORT:
ABORT: Disk space available:  13383.513 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (./p_temperatura.trimmedReads.fasta.err):
ABORT:
ABORT:
```

from the .err file

```No trimmed reads in store.```

**the .report file**

```
In gatekeeper store './p_temperatura.gkpStore':
--   Found 546 reads.
--   Found 8091026 bases (2.52 times coverage). 
```

Then in trimming it looks like the reads all got deleted. 

```
lauraf@unc:~/FN58_diamond_blast_runs/planktomarina/long_reads/assembled_genome/canu_assembled/lenient_p_temperatura$ less p_temperatura.report

--  ----------
--     1000    (reads trimmed below this many bases are deleted)
--   0.1080    (use overlaps at or below this fraction error)
--        1    (break region if overlap is less than this long, for 'largest covered' algorithm)
--        1    (break region if overlap coverage is less than this many read, for 'largest covered' algorithm)
--  
--  INPUT READS:
--  -----------
--     546 reads      8091026 bases (reads processed)
--       0 reads            0 bases (reads not processed, previously deleted)
--       0 reads            0 bases (reads not processed, in a library where trimming isn't allowed)
--  
--  OUTPUT READS:
--  ------------
--       0 reads            0 bases (trimmed reads output)
--       0 reads            0 bases (reads with no change, kept as is)
--     362 reads      5200526 bases (reads with no overlaps, deleted)
--     184 reads      2890500 bases (reads with short trimmed length, deleted)
```

**Comment by skoren** [comment]
You specified the input reads as corrected so no correction would have been done. Are these reads already corrected somehow or raw off the sequencer? If they're raw then all of them would have no overlaps and thus get deleted.

The adjusted error rate of 0.108 is also lower than the current default for nanopore of 0.14 so that would remove some overlaps.

**Comment by laurafisch9** [comment]
These reads have been quality trimmed and filtered based on average read quality score
They are not raw off the sequencer.

**Comment by skoren** [comment]
That's still raw off the sequencer since the base call accuracy within each read is whatever was generated by the base caller. Corrected reads would have new bases called through consensus. In the default run which worked did you input the reads as raw or corrected?

**Comment by laurafisch9** [comment]
I see. What you just wrote makes sense.
using the raw option fixed the issue and canu ran the assembly.
I had to delete the previous directory and re run the command. Then it worked

**Comment by skoren** [comment]
OK, that said, your parameter adjustment isn't likely to help the assembly. It would decrease the tolerance for error in the reads. See the FAQ for some suggestions, including running multiple rounds of correction.
