### ISSUE TITLE
extreme amounf of hard drive space

### ISSUE THREAD

**Issue by macmanes** [marbl/canu#1039]
Hello, 

I am trying to assemble a mammalian genome using approximately 25x nanopore reads. The assembly folder currently is 23Tb (!!!) in size, which is not making the sys-admin very happy. The largest part of this (17Tb) is in `correction/name.ovlStore.BUILDING`. Can you help me understand why so much space is needed, and how to reduce the HD footprint?

This is `Canu snapshot v1.7 +318 changes (r9010 e6d1892055e4599f31eaf774366aebe8dfc995f2)`

Thanks, Matt

**Comment by skoren** [comment]
In short, it's the low coverage. When you have low coverage the overlap sensitivity has to be increased which in turns adds noise overlaps as well. You can clean up some intermediate outputs early (see issue #937). You can also adjust the overlapping parameters, we had some suggested ones  in the human nanopore paper:
```
"corMhapOptions=--threshold 0.8 --num-hashes 768 --num-min-matches 3 --ordered-sketch-size 1000 -ordered-kmer-size 14 --min-olap-length 2000"
```
if your genome is very repetitive you could also add (see #942):
```
corMhapFilterThreshold=0.0000000002 corMhapOptions="--threshold 0.80 --num-hashes 768 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50" mhapMemory=60g mhapBlockSize=500
```

However, if you have the space, you can just let it complete. The current store building is the peak of disk space usage. Both the large store and the intermediate files are deleted shortly after construction.

**Comment by devonorourke** [comment]
Hi guys,
Following Sergey's referencing to issue [937](https://github.com/marbl/canu/issues/937), I was wondering if you could clarify something:
If my script has advanced from the `corrections` phase and now entered the `trimming` phase, when and where is there a reasonable time to delete data no longer being used by Canu (or move to another disk)?
For example, when `trimming` is just starting and has only created a `0-mercounts` directory, is there anything in the `corrections` directory that can safely be removed? Is it just the `blocks` folder within `corrections` that can be removed, or can everything in the `1-overlapper` directory within `corrections` be deleted?
Thanks!
