### ISSUE TITLE
Bad UID for job execution MSG

### ISSUE THREAD

**Issue by prince26121991** [marbl/canu#104]
Anyone can help me with this message?

-- Meryl attempt 1 begins.
----------------------------------------
-- Starting command on Tue Apr 19 15:25:07 2016 with 20856 GB free disk space

      qsub \
        -l mem=126g -l nodes=1:ppn=32 \
        -d `pwd` -N "meryl_1st_try" \
        -t 1-1 \
        -j oe -o /home/scbbcluster/nitesh_mpi/pacbio_assembly/canu-1.2/Linux-amd64/bin/1st_trial/unitigging/0-mercounts/meryl.\$PBS_ARRAYID.out \
        /home/scbbcluster/nitesh_mpi/pacbio_assembly/canu-1.2/Linux-amd64/bin/1st_trial/unitigging/0-mercounts/meryl.sh
    
qsub: submit error (Bad UID for job execution MSG=ruserok failed validating scbbcluster/scbbcluster from r3node4)

-- Finished on Tue Apr 19 15:25:10 2016 (3 seconds) with 20856 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 177.
ERROR:
================================================================================
Please panic.  canu failed, and it shouldn't have.

Stack trace:

 at /home/scbbcluster/nitesh_mpi/pacbio_assembly/canu-1.2/Linux-amd64/bin/lib/canu/Defaults.pm line 234
	canu::Defaults::caFailure('Failed to submit batch jobs', undef) called at /home/scbbcluster/nitesh_mpi/pacbio_assembly/canu-1.2/Linux-amd64/bin/lib/canu/Execution.pm line 1139
	canu::Execution::submitOrRunParallelJob('/home/scbbcluster/nitesh_mpi/pacbio_assembly/canu-1.2/Linux-a...', '1st_try', 'meryl', '/home/scbbcluster/nitesh_mpi/pacbio_assembly/canu-1.2/Linux-a...', 'meryl', 1) called at /home/scbbcluster/nitesh_mpi/pacbio_assembly/canu-1.2/Linux-amd64/bin/lib/canu/Meryl.pm line 370
	canu::Meryl::merylCheck('/home/scbbcluster/nitesh_mpi/pacbio_assembly/canu-1.2/Linux-a...', '1st_try', 'utg') called at /home/scbbcluster/nitesh_mpi/pacbio_assembly/canu-1.2/Linux-amd64/bin/canu line 512

canu failed with 'Failed to submit batch jobs'.

However when I tried to run this command manually
qsub \
    -l mem=126g -l nodes=1:ppn=32 \
    -d `pwd` -N "meryl_1st_try" \
    -t 1-1 \
    -j oe -o /home/scbbcluster/nitesh_mpi/pacbio_assembly/canu-1.2/Linux-amd64/bin/1st_trial/unitigging/0-mercounts/meryl.\$PBS_ARRAYID.out \
    /home/scbbcluster/nitesh_mpi/pacbio_assembly/canu-1.2/Linux-amd64/bin/1st_trial/unitigging/0-mercounts/meryl.sh

It run successfully, But if I have to run manually all command than how its going to be distribute on all node and how would I know everytime which command I have to run ?

**Comment by prince26121991** [comment]
By googling on this error 
"submit error (Bad UID for job execution MSG=ruserok failed validating scbbcluster/scbbcluster from r3node4)"
 I got some result and after trying those result I was able to overcome this error so posting here solution:


Step 1: Do check that your Torque Server Configuration has the followings. You can check by doing 
# qmgr -c "p s".
.....
.....
set server submit_hosts = submission_node
set server allow_node_submit = True 
.....
.....

If not you can add it in very quickly
# qmgr -c 'set server submit_hosts = submission_node'

# qmgr -c 'set server allow_node_submit = True'

Step 2: Start the PBS services in sequence. 
From my observation, we do not need to start the pbs_sched just the pbs_server only
# service pbs_server start


Hope this will help other users.
Thank you

Source: http://linuxtoolkit.blogspot.in/2014/06/bad-uid-for-job-execution-msgruserok.html

**Comment by caot** [comment]
@prince26121991 

The dot at the end of `qmgr -c "p s". ` should be removed
