### ISSUE TITLE
canu : ABORT:   invalid useGrid (1) and gridEngine (PBS); found no execution hosts - is grid available from this host?.

### ISSUE THREAD

**Issue by nishaag** [marbl/canu#1040]
Hi I would like to use canu on PBS based cluster. For which I installed the canu and using following canu command 

canu -p 'ecoli' 'genomeSize=4.8m'  -pacbio-raw 'pacbio.fastq' canuIteration=0 gridOptions="-l nodes=2:ppn=16,walltime=10:00 -q GPUq"

canu -version
Canu 1.7.1

The error which I am getting in output file is

```
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_181' (from 'java').
-- Detected gnuplot version '4.2 patchlevel 6 ' (from 'gnuplot') and image format 'png'.
-- Detected 16 CPUs and 63 gigabytes of memory.
-- Detected PBS/Torque '' with 'pbsnodes' binary in /usr/local/PBS/bin/pbsnodes.
pbs_iff command not found.
qmgr: cannot connect to server  (errno=15008) pbs_iff command not found, unable to authenticate
-- Detecting PBS/Torque resources.
pbs_iff command not found.
pbsnodes: cannot connect to server yc9.en.yuva.param, error=15008 (pbs_iff command not found, unable to authenticate)
-- 

ABORT:
ABORT: Canu 1.7.1
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   invalid useGrid (1) and gridEngine (PBS); found no execution hosts - is grid available from this host?.
ABORT:
```
Please help to fix this issue.

**Comment by skoren** [comment]
Canu uses the PBS command pbsnodes to poll your available resources. On your compute nodes this is not working. See the FAQ: http://canu.readthedocs.io/en/latest/faq.html#my-run-stopped-with-the-error-failed-to-submit-batch-jobs. If your nodes cannot access/submit to the grid then Canu won't work with your grid system. These are grid configuration issues so you'll have to check with your sysadmin if it can be changed. If not, you'll have to run Canu on a single node or use ```useGrid=remote``` from the head node which will print the commands for you to manually run (see issue #822).

Also, don't specify the memory/cpu resources in the command, Canu will request the appropriate ones for each step (e.g. use ```gridOptions="walltime=10:00 -q GPUq"```).

**Comment by nishaag** [comment]
Hi,

Thanks for your prompt reply. As suggested by you I used useGrid=remote as I want to submit canu job  from head node using qsub for N no. of nodes. I got the following command after using useGrid=remote 
option
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
qsub -j oe -d `pwd` \
  -l  nodes=1:ppn=4 -l walltime=10:00 -q GPUq -o meryl.\$PBS_ARRAYID.out \
  -N "meryl_ecoli" \
  -t 1-1 \
  ./meryl.sh -F "0" \
> ./meryl.jobSubmit-01.out 2>&1
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Now I want to run this for nodes=64 , but when I changed and executed it was running on single node. Please suggest how to move forward.

**Comment by skoren** [comment]
I got an email for a comment but don't see it here now, not sure what happened.

Not all steps will submit array jobs. Some, like meryl, run a single shared-memory process on one node. Others will submit arrays of shared-memory jobs. You don't need to tell it to use a specific set of nodes (you'd never use nodes=64) because the request describes what each job in the array not the entire array needs. So you can run the commands Canu prints as is without modification and once the submitted job completes run Canu again to get the next command to submit and so on.

**Comment by nishaag** [comment]
Hi Sergey Koren

*I would like to thank you for your prompt reply and support. As per
your suggestion I am able *
*to run canu **successfully with useGrid=remote option on my cluster :-) .
However  it would be *
*great instead of manually **doing the steps canu would have done
it automatically for useGrid=remote.  *

"Apologizing does not mean that you are wrong and the other one is right...
It simply means that you value the relationship much more than your ego.."

**Comment by skoren** [comment]
Canu can't do it automatically for useGrid=remote, it has no way to know when the submitted job is done unless it keeps running in a busy-wait polling your grid engine. The remote option is a workaround for grids that don't allow submission from compute nodes.

Instead, Canu relies on the grid itself to submit jobs waiting for the completion of the arrays. This is what was broken on your grid so if you can fix the config so you are able to run pbsnodes/bsub on compute nodes then you can run Canu automatically on the grid.

**Comment by nishaag** [comment]
Hi,

Thanks. Will this array jobs in grid runs on multiple nodes or only on one
node with multiple threads?

N if I will run canu locally will it also create array jobs or just execute
with multiple threads?

**Comment by brianwalenz** [comment]
There's no difference in what gets run between grid and non-grid; they both do the same work.  Canu will set up (for example) 100 overlapper jobs, each wanting to use 4 threads.  If on a grid, the grid scheduler will be asked to run the jobs for us.  Otherwise, Canu will run the jobs, running as many as possible at the same time (e.g., if you have 20 processors, it would run 5 of those 4-thread overlapper jobs at the same time).

**Comment by nishaag** [comment]
Hi Brian,


One last query, array jobs of canu in grid environment will run on a single
system with multiple processor or across the systems each with multiple
processor.

Say suppose I have 4 systems and each with 4 processors and canu is running
with 4 overlapper (array) jobs.  Will these 4 array jobs run on 1 system
with 4 processor or it can run across 4 systems each with 4 processor?

"Apologizing does not mean that you are wrong and the other one is right...
It simply means that you value the relationship much more than your ego.."

**Comment by skoren** [comment]
The array jobs will run multiple systems with multiple processes in use by each. So it will run on 4 systems, or as many as the scheduler gives the array.

**Comment by nishaag** [comment]
Hi,

Is there any way to put a limit on Maximum no. of array jobs to be created?
