### ISSUE TITLE
Error at cor step and general question

### ISSUE THREAD

**Issue by aberaslop** [marbl/canu#1042]
Hi Canu team,
 
I am trying to assemble a genome with Canu v 1.7. in a virtual machine.

I first found some trouble running the program, but I realized that I was running if from a shared folder and that was preventing it from working properly. I wrote the output to the Desktop and that seems to have solved it. 

However, I've found a second problem. I have run the following command:

canu -p Genome -d Genome_canu genomeSize=30m -pacbio-raw reads/*.fastq gnuplotTested=true

It run for 5 hours with a number of successful intermediate steps. However, I have found the following error:
```
-- ERROR
-- ERROR
-- ERROR  Found 1 machine configuration:
-- ERROR    class0 - 1 machines with 3 cores with 43 GB memory each.
-- ERROR
-- ERROR  Task cor can't run on any available machines.
-- ERROR  It is requesting:
-- ERROR    corMemory=3 memory (gigabytes)
-- ERROR    corThreads=4 threads
-- ERROR
-- ERROR  No available machine configuration can run this task.
-- ERROR
-- ERROR  Possible solutions:
-- ERROR    Change corMemory and/or corThreads
-- ERROR

ABORT:
ABORT: Canu 1.7
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   task cor failed to find a configuration to run on.
ABORT:
```

My question is two-fold: first, what would be appropriate values for corThreads and corMemory given my memory parameters?

And two: I know that Canu can be run separately for the correcting, trimming and assembling stages. Is there any way to run the intermediate scripts of each step one by one? I would like to do that to avoid running canu again for 5 hours, just to have it fail again after correcting this step. I have read the manual, but haven't found an answer to this.

Thank you so much for your help!

**Comment by skoren** [comment]
The issue is the default configuration for a 30mb genome tries to use more than 3 cores which is what you have for your VM. Set ```corThreads=3``` and it should be fine.

As for two, see the FAQ: http://canu.readthedocs.io/en/latest/faq.html#my-run-of-canu-was-killed-by-the-sysadmin-the-power-going-out-my-cat-stepping-on-the-power-button-et-cetera-is-it-safe-to-restart-how-do-i-restart. You don't need to do anything special to restart, it will automatically see what is completed and resume.

**Comment by aberaslop** [comment]
Hi @skoren,

Thank you so much for your help!
It's running!
