### ISSUE TITLE
Mhap overlap step fails due to segmentation fault, Canu 1.7

### ISSUE THREAD

**Issue by hornhd** [marbl/canu#1043]
Hello, 

We are running Canu (-version 1.7) on PacBio Sequel reads using a cluster with slurm as workflow manager. 

Canu was started as follows:
``canu gridOptions="-p htseq-guest" merylMemory="450" merylThreads="72"  genomeSize="3300m" -correct -p initial_assembly -d /canu_default/ -pacbio-raw /raw_data_fastq/*.fastq.gz``

- The first step (0-mercounts) ended successfully and without any errors/warnings. 
- For the second step (1-overlapping), 480 precompute jobs were generated and finished successfully.
- For the following mhap overlap step, 1197 jobs were configured, which all failed in the first iteration, but were restarted.
-  In the second interation of mhap, again 24 jobs failed:

```
-- BEGIN CORRECTION
--
--
-- Mhap overlap jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/results/000029.ovb FAILED.
--   job correction/1-overlapper/results/000033.ovb FAILED.
--   job correction/1-overlapper/results/000037.ovb FAILED.
--   job correction/1-overlapper/results/000041.ovb FAILED.
--   job correction/1-overlapper/results/000045.ovb FAILED.
--   job correction/1-overlapper/results/000047.ovb FAILED.
--   job correction/1-overlapper/results/000048.ovb FAILED.
--   job correction/1-overlapper/results/000049.ovb FAILED.
--   job correction/1-overlapper/results/000051.ovb FAILED.
--   job correction/1-overlapper/results/000052.ovb FAILED.
--   job correction/1-overlapper/results/000053.ovb FAILED.
--   job correction/1-overlapper/results/000054.ovb FAILED.
--   job correction/1-overlapper/results/000055.ovb FAILED.
--   job correction/1-overlapper/results/000056.ovb FAILED.
--   job correction/1-overlapper/results/000057.ovb FAILED.
--   job correction/1-overlapper/results/000058.ovb FAILED.
--   job correction/1-overlapper/results/000059.ovb FAILED.
--   job correction/1-overlapper/results/000060.ovb FAILED.
--   job correction/1-overlapper/results/000061.ovb FAILED.
--   job correction/1-overlapper/results/000062.ovb FAILED.
--   job correction/1-overlapper/results/000065.ovb FAILED.
--   job correction/1-overlapper/results/000067.ovb FAILED.
--   job correction/1-overlapper/results/000069.ovb FAILED.
--   job correction/1-overlapper/results/000071.ovb FAILED.
--

ABORT:
ABORT: Canu 1.7
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```
I restarted them manually using the script _mhap.jobSubmit-01.sh_, but still did not work.
The error messages from the 24 mhap.out files are all the same:

```
/var/spool/slurmd/job4962322/slurm_script: line 7288: 48808 Segmentation fault      (core dumped) $bin/mhapConvert -G ../initial_assembly.gkpStore -o ./results/$qry.mhap.ovb.WORKING ./results/$qry.mhap
```

All previous files seem to be ok and the error messages do not show any problems. 
We would appreciate any help or suggestions to solve this issue. 
If you need more information/logs, please let us know.

**Comment by skoren** [comment]
It looks like a subset of jobs' output is likely truncated or corrupt. Does one of the failed log jobs report anything before the segmentation fault? Try removing all files named ```correction/1-overlapper/results/*mhap*``` and re-running one of the failing jobs by hand to see if it completes.

**Comment by hornhd** [comment]
We removed the files as you suggested and restarted the failing ones again -
but with the same result: "Segmentation fault" 

The job logs did not show any obvious errors. 
But, at that may have caused the overall problem: the jobs weren't able to write on
disk for a couple of hours, as they reached the quota of our storage. 

Running Canu from scratch with extended storage solved the described problem.
