### ISSUE TITLE
ovlStore.BUILDING Failed

### ISSUE THREAD

**Issue by Phylloxera** [marbl/canu#1044]
canu1.7.1 on grid
```
canu -correct -p gaur_c -d /project/gaur_genome_assembly/ad_ceres -gnuplotTested=true \
corMhapSensitivity=normal corOutCoverage=100 saveOverlaps=true \
gridOptionsExecutive="--partition=short" gridOptionsMeryl="--partition=mem" \
gridOptionsCORMHAP="--partition=short" gridOptionsOVS="--partition=mem" \
gridOptionsCOR="--partition=short" stageDirectory=/scratch/$SLURM_JOBID gridEngineStageOption="--gres=lscratch:80" genomesize=2.8g \
-pacbio-raw /project/gaur_genome_assembly/gaur.fasta.gz

output of canu.out:
-- Overlap store sorting jobs failed, tried 2 times, giving up.
--   job correction/gaur_c.ovlStore.BUILDING/2133 FAILED.
--   job correction/gaur_c.ovlStore.BUILDING/2134 FAILED.
--   job correction/gaur_c.ovlStore.BUILDING/2135 FAILED.
--   job correction/gaur_c.ovlStore.BUILDING/2136 FAILED.
--   job correction/gaur_c.ovlStore.BUILDING/2137 FAILED.
--   job correction/gaur_c.ovlStore.BUILDING/2138 FAILED.
--   job correction/gaur_c.ovlStore.BUILDING/2139 FAILED.
--   job correction/gaur_c.ovlStore.BUILDING/2140 FAILED.
--   job correction/gaur_c.ovlStore.BUILDING/2141 FAILED.
--   job correction/gaur_c.ovlStore.BUILDING/2142 FAILED.
--   job correction/gaur_c.ovlStore.BUILDING/2143 FAILED.
--   job correction/gaur_c.ovlStore.BUILDING/2144 FAILED.
--   job correction/gaur_c.ovlStore.BUILDING/2145 FAILED.
--   job correction/gaur_c.ovlStore.BUILDING/2146 FAILED.
--   job correction/gaur_c.ovlStore.BUILDING/2147 FAILED.
--   job correction/gaur_c.ovlStore.BUILDING/2148 FAILED.
--   job correction/gaur_c.ovlStore.BUILDING/2149 FAILED.
--   job correction/gaur_c.ovlStore.BUILDING/2150 FAILED.
--   job correction/gaur_c.ovlStore.BUILDING/2151 FAILED.
--   job correction/gaur_c.ovlStore.BUILDING/2152 FAILED.

ABORT:
ABORT: Canu 1.7
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```
I restarted but the same steps failed again... what to do/check next?

**Comment by skoren** [comment]
What is the error reported in the bucketizing output (e.g. ```correction/gaur_c.ovlStore.BUILDING/logs/1-*.2152.out```)? When we've seen this before it's been due to FS corruption of intermediate outputs which means you may need to re-run part of the previous step.

**Comment by Phylloxera** [comment]
The labeling of the log files in gaur_c.ovlStore.BUILDING/logs is not what I expected from the 1-*.2152.out template... I've got 1-bucketize.20732_<1-413>.out then 1-bucketize.207447_367.out, 1-bucketize.207448_369.out, 1-bucketize.207449<371-375>.out, 1-bucketize.207450_379.out.

The output of 1-bucketize.20732_152.out is:

Running job 152 based on SLURM_ARRAY_TASK_ID=152 and offset=0.

Attempting to increase maximum allowed processes and open files.
  Max processes per user limited to 515530, no increase possible.
  Max open files limited to 51200, no increase possible.

maxError fraction: 1.000 percent: 100.000 encoded: 4095
Bucketizing ../1-overlapper/results/000152.ovb
Success!

**Comment by skoren** [comment]
My mistake, it should be ```logs/2-sort*2152.out```.

**Comment by Phylloxera** [comment]
The 2-sort step seems to have been divided up into 4 sets of MAX 1000 jobs. Guessing this is due to the MAXARRAYJOB (or something like that) SLURM parameter.
My sets are:
2-sort.207510_<1-1000>.out
2-sort.207511_<1-1000>.out
2-sort.207512_<1-1000>.out
2-sort.207513_<1-16>.out
Then I have the reruns
210983_1
210984_<1-20>
212654_<1-20>
212690_<1-20>
So guessing the 2152nd log outfile should be
2-sort.207512_152.out... does look like a culprit!

head -n 9:
Running job 2152 based on SLURM_ARRAY_TASK_ID=152 and offset=2000.
  Attempting to increase maximum allowed processes and open files.  
  Max processes per user limited to 6192169, no increase possible.
  Max open files limited to 51200, no increase possible.          
 Finding overlaps.                                                 
  found     737368 overlaps in './bucket0003/sliceSizes'.         
       
tail -n 17:
  loading   25568499 overlaps from './bucket0367/slice2152'.
ERROR: expected 25568499 overlaps, found 786240 overlaps.
ovStoreSorter: stores/ovStoreWriter.C:332: void ovStoreWriter::loadOverlapsFromSlice(uint32, uint64, ovOverlap*, uint64&): Assertion `num == expectedLen' failed.
Failed with 'Aborted'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::97 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
stores/ovStoreWriter.C::332 in _ZN13ovStoreWriter21loadOverlapsFromSliceEjmP9ovOverlapRm()
stores/ovStoreSorter.C::228 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
/var/spool/slurmd/job210120/slurm_script: line 72: 78047 Aborted                 (core dumped) $bin/ovStoreSorter -deletelate -M 4 -O . -G ../gaur_c.gkpStore -F 3016 -job $jobid 413

sorry so verbose... I'm trying to be thorough for the sake of my own learning curve :)

**Comment by skoren** [comment]
So that definitely looks like disk corruption. There's a short read on one of the bucket output files. Look for similar errors in all the 2-sort files, and get the lines which indicate the bucket it was reading (bucket0367 in the example above) and make a list of all buckets which caused the errors. What you'll want to do is remove those bucket folders and re-run ```scripts/1-bucketize.sh <failed job>``` for each of them. Then, try one of the failing sort jobs by hand (e.g. ```scripts/2-sort.sh 2152```).

**Comment by Phylloxera** [comment]
All of the failed jobs relate back to the single bucket 0367.
Tried to run scripts/1-bucketize.sh 2152 via sbatch from a login node and requested the job be run on a 'mem' node (high memory).
is this good or should i request a lower memory node? 
my stdout says: 
Running job 2152 based on command line options.
Job out of range.

**Comment by skoren** [comment]
The bucket job is not 2152 but 367 so you want ```sh scripts/1-bucketize.sh 367```. The way the store build works is a distributed sort. It takes each set of overlaps and distributes them into their appropriate range. So you have 2152 ranges (sort jobs) and each bucket can have files named slice000001 to slice 002152. The sort then takes all slices it needs (e.g. job 2152 takes all files named slice002152 from all buckets) and sorts them.

The bucketizing job should be low memory, maybe 4gb. Same applies to the sort jobs. Then run the failed sorting jobs:
```
sh scripts/2-sort.sh 2133
sh scripts/2-sort.sh 2134
sh scripts/2-sort.sh 2135
sh scripts/2-sort.sh 2136
sh scripts/2-sort.sh 2137
sh scripts/2-sort.sh 2138
sh scripts/2-sort.sh 2139
sh scripts/2-sort.sh 2140
sh scripts/2-sort.sh 2141
sh scripts/2-sort.sh 2142
sh scripts/2-sort.sh 2143
sh scripts/2-sort.sh 2144
sh scripts/2-sort.sh 2145
sh scripts/2-sort.sh 2146
sh scripts/2-sort.sh 2147
sh scripts/2-sort.sh 2148
sh scripts/2-sort.sh 2149
sh scripts/2-sort.sh 2150
sh scripts/2-sort.sh 2151
sh scripts/2-sort.sh 2152
```

one at a time to see if they work now. You probably also need to remove any ```*.ovs``` files before running the sort.

**Comment by Phylloxera** [comment]
21 'Success!' signals. now should I try to resubmit the canu command?
did not see any .ovs files, would they have been in .ovlStore.BUILDING or elsewhere?

**Comment by skoren** [comment]
The ovs files would have been in the ovlStore.BUILDING folder. Have you run one of the sorting jobs to make sure they now complete? I'd run them all by hand to make sure there are no other bucket issues and then re-run the same Canu command. It should pick up at the next step.

**Comment by Phylloxera** [comment]
I ran the 1-bucketize.sh job and got 'Success!' Likewise for each of the 20 2-sort.sh jobs... but that was without removing *.ovs files. should I go find and delete those and then rerun? or am i good to go with the Canu command?

**Comment by skoren** [comment]
No that's fine, the ovs files would have prevented your jobs from running again so if they ran to completion then everything is OK and you can go ahead and re-launch Canu.
