### ISSUE TITLE
canu is slowly and spent too much time

### ISSUE THREAD

**Issue by wangxinbio** [marbl/canu#1046]
Hi 
I used canu to assemble a tomato genome. The command is as below:
canu -p tomato -d tomato-pacbio genomeSize=1.2g -pacbio-raw Pacbio.subreads.fastq. The raw pacbio data is 77.8G. canu version is 1.7. It spent more than one month and still running.  What is the problem for it? Thanks.

**Comment by skoren** [comment]
Not enough information here to answer the question. What are your compute resources? Are you running on a single node or a grid? What step is it on?

Read some existing issues for suggestions to improve runtime like #942, #994, #1014.

**Comment by wangxinbio** [comment]
My compute resources is 512Gb RAM. 
![qq 20180816131554](https://user-images.githubusercontent.com/12146966/44223771-90005380-a156-11e8-840d-8513b14ac492.jpg)

**Comment by skoren** [comment]
It is on the last expensive overlapping step (utgcns). It is likely setting the ovlMerThreshold parameter as in issue #1014 would help. You would have to kill the current run and restart from the assembly step (```canu -assemble -p tomato -d tomato-new genomeSize=1.2g -pacbio-corrected tomato-pacbio/asm.trimmedReads.fasta.gz ovlMerThreshold=500```). You're about 15% through the current run so you could also let it keep running.

How many cores does your machine have available? It looks like it's only running 4 processes concurrently and these typically default to 8 cores or less so I'll guess 16-32 cores on your system?

**Comment by wangxinbio** [comment]
@skoren  yes. 32 cores in my server. I have read the issue #1014. Do I add two more setting overlapper=mhap utgReAlign=true, or just add the ovlMerThreshold=500. Thanks.

**Comment by skoren** [comment]
Just ovlMerThreshold=500. 

For context, the FAQ lists a mammalian genome as taking about 25k cpu hours. On 32 cores that translates to about a month. Your genome is smaller but also more repetitive so a month is not too surprising.

**Comment by wangxinbio** [comment]
@skoren  Thank you very much. I will try.
