### ISSUE TITLE
meryl fails, no error message

### ISSUE THREAD

**Issue by asrivathsan** [marbl/canu#1048]
Hi,

I have been trying to run canu for assembly and while for test ecoli dataset meryl works fine, for the dataset we are trying to assemble, canu returns Meryl failed, tried 2 times, giving up. We are assembling a genome sizing ~1Gb.

The output of meryl.1.out is not telling me much...

Thanks for looking into this

> 

Computing 32 segments using 32 threads and 209696MB memory (22444MB if in one batch).
  numMersActual      = 56316585665
  mersPerBatch       = 12240639317
  basesPerBatch      = 1762643543
  numBuckets         = 67108864 (26 bits)
  bucketPointerWidth = 31
  merDataWidth       = 6
Computing segment 20 of 32.
Computing segment 2 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
Computing segment 13 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 22 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
Computing segment 32 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
Computing segment 23 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
Computing segment 7 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
Computing segment 1 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 28 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
Computing segment 30 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 19 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
Computing segment 6 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
Computing segment 3 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
Computing segment 11 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
Computing segment 26 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 15 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
Computing segment 14 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
Computing segment 17 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
Computing segment 4 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 24 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
Computing segment 5 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 25 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
Computing segment 21 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 18 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 31 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 27 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
Computing segment 8 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 16 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
Computing segment 9 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 12 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 29 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 10 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Counting mers in buckets:    2.10 Mmers --  1.02 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.98 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  1.88 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.71 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  1.82 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.82 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  1.34 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.63 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.84 Mmers/second
 Counting mers in buckets:    6.29 Mmers --  2.40 Mmers/second
 Counting mers in buckets:    6.29 Mmers --  2.42 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  1.47 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.78 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.69 Mmers/second
 Counting mers in buckets:    6.29 Mmers --  1.80 Mmers/second
 Counting mers in buckets:    8.39 Mmers --  3.03 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.74 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  1.49 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.64 Mmers/second
 Counting mers in buckets:    8.39 Mmers --  2.86 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  1.13 Mmers/second
 Counting mers in buckets:    8.39 Mmers --  2.28 Mmers/second
 Counting mers in buckets:   10.49 Mmers --  3.58 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  1.40 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  1.21 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  1.26 Mmers/second
 Counting mers in buckets:    6.29 Mmers --  1.93 Mmers/second
 Counting mers in buckets:   12.58 Mmers --  4.06 Mmers/second
 Counting mers in buckets:   10.49 Mmers --  2.72 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  1.32 Mmers/second
 Counting mers in buckets:   10.49 Mmers --  3.25 Mmers/second
 Counting mers in buckets:    8.39 Mmers --  2.40 Mmers/second
 Counting mers in buckets:   12.58 Mmers --  3.11 Mmers/second
 Counting mers in buckets:   12.58 Mmers --  3.69 Mmers/second
 Counting mers in buckets:   14.68 Mmers --  4.37 Mmers/second
 Counting mers in buckets:    6.29 Mmers --  1.49 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.61 Mmers/second
 Counting mers in buckets:    6.29 Mmers --  1.85 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.60 Mmers/second
 Counting mers in buckets:   10.49 Mmers --  2.82 Mmers/second
 Counting mers in buckets:   16.78 Mmers --  4.76 Mmers/second
 Counting mers in buckets:   14.68 Mmers --  3.41 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  1.15 Mmers/second
 Counting mers in buckets:   14.68 Mmers --  3.99 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.47 Mmers/second
 Counting mers in buckets:    6.29 Mmers --  1.68 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  1.11 Mmers/second
 Counting mers in buckets:    8.39 Mmers --  2.26 Mmers/second
 Counting mers in buckets:   18.87 Mmers --  5.06 Mmers/second
 Counting mers in buckets:    6.29 Mmers --  1.54 Mmers/second
 Counting mers in buckets:   12.58 Mmers --  3.14 Mmers/second
 Counting mers in buckets:    8.39 Mmers --  1.81 Mmers/second
 Counting mers in buckets:    6.29 Mmers --  1.62 Mmers/second
 Counting mers in buckets:   16.78 Mmers --  3.64 Mmers/second
 Counting mers in buckets:    6.29 Mmers --  1.45 Mmers/second
 Counting mers in buckets:   16.78 Mmers --  4.20 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.44 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  0.88 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.45 Mmers/second
 Counting mers in buckets:   20.97 Mmers --  5.19 Mmers/second
 Counting mers in buckets:   10.49 Mmers --  2.60 Mmers/second
 Counting mers in buckets:    8.39 Mmers --  2.06 Mmers/second
 Counting mers in buckets:    8.39 Mmers --  1.91 Mmers/second
 Counting mers in buckets:   14.68 Mmers --  3.40 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.43 Mmers/second
 Counting mers in buckets:   18.87 Mmers --  3.83 Mmers/second
 Counting mers in buckets:    8.39 Mmers --  1.99 Mmers/second
 Counting mers in buckets:    8.39 Mmers --  1.81 Mmers/second
 Counting mers in buckets:   10.49 Mmers --  2.08 Mmers/second
 Counting mers in buckets:   18.87 Mmers --  4.37 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  0.83 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.48 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  0.84 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.54 Mmers/second
 Counting mers in buckets:   12.58 Mmers --  2.89 Mmers/second
 Counting mers in buckets:   10.49 Mmers --  2.39 Mmers/second
 Counting mers in buckets:   10.49 Mmers --  2.23 Mmers/second
 Counting mers in buckets:   16.78 Mmers --  3.64 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  0.80 Mmers/second
 Counting mers in buckets:   10.49 Mmers --  2.14 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.52 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.52 Mmers/second
 Counting mers in buckets:   20.97 Mmers --  4.00 Mmers/second
 Counting mers in buckets:   10.49 Mmers --  2.30 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  0.91 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  1.03 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.51 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.51 Mmers/second
 Counting mers in buckets:   20.97 Mmers --  4.52 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.38 Mmers/second
 Counting mers in buckets:   12.58 Mmers --  2.50 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.39 Mmers/second
 Counting mers in buckets:   12.58 Mmers --  2.31 Mmers/second
 Counting mers in buckets:   18.87 Mmers --  3.85 Mmers/second
 Counting mers in buckets:   12.58 Mmers --  2.52 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.48 Mmers/second
 Counting mers in buckets:   14.68 Mmers --  3.14 Mmers/second
 Counting mers in buckets:   12.58 Mmers --  2.67 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  0.98 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  0.99 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  0.75 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  0.74 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  0.97 Mmers/second
 Counting mers in buckets:   14.68 Mmers --  2.83 Mmers/second
Computing 32 segments using 32 threads and 209696MB memory (22444MB if in one batch).
  numMersActual      = 56316585665
  mersPerBatch       = 12240639317
  basesPerBatch      = 1762643543
  numBuckets         = 67108864 (26 bits)
  bucketPointerWidth = 31
  merDataWidth       = 6
Computing segment 1 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
Computing segment 28 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 11 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
Computing segment 23 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 21 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 31 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 25 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 13 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 32 of 32.
Computing segment 3 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 26 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 22 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 5 of 32.
Computing segment 9 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 16 of 32.
 Allocating 256MB for counting the size of each bucket.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 20 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 6 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
Computing segment 7 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 24 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 2 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
Computing segment 12 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 14 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 8 of 32.
Computing segment 30 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 19 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
Computing segment 29 of 32.
Computing segment 27 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 17 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
Computing segment 4 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 18 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 15 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
Computing segment 10 of 32.
 Allocating 248MB for bucket pointer table (31 bits wide).
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Allocating 256MB for counting the size of each bucket.
 Counting mers in buckets:    2.10 Mmers --  1.08 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  1.08 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  1.19 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  1.01 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  1.10 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.95 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.87 Mmers/second
 Counting mers in buckets:    2.10 Mmers --  0.95 Mmers/second
 Counting mers in buckets:    4.19 Mmers --  2.15 Mmers/second
>

**Comment by brianwalenz** [comment]
I'm going to guess it's running out of memory.  Try decreasing merylMemory to 128g.

Is this grid-based or on one machine?  What Canu version?

**Comment by asrivathsan** [comment]
Sorry about the silence, have been travelling, changing meryl Memory worked! Thanks for this
