### ISSUE TITLE
Canu stopped by the errors

### ISSUE THREAD

**Issue by Ikedakei** [marbl/canu#1049]
After Canu was downloaded from https://github.com/marbl/canu.git and installed on Ubuntu-based desktop computer as instructed, I tried to check Canu program with test data from http://nanopore.s3.climb.ac.uk/MAP006-PCR-1_2D_pass.fasta.   But Canu stopped by the errors with messages, 'ls: Cannnot access to '*seqStore'; no such file or directory ', 'Can't exec "gnuplot": no such files or directory at ---../lib/site_perl/canu/Defaults.pm line 1106.', and 'readline() on closed filehandle F at -------../lib/site_perl/canu/Defaults.pm line 1107.'  Error message at last line says, "ERROR:  Failed to run gnuplot from 'gnuplot'.ERROR:  Set option gnuplot=<path-to-gnuplot> or gnuplotTested=true to skip this test and not generate plots," although I tried to reinstall Canu.
I would very much appreciate to know what is happen and how to resolve this problem.

**Comment by brianwalenz** [comment]
Please read https://help.github.com/articles/basic-writing-and-formatting-syntax/ and format the message.  Click 'Preview' to see what we'd see before submitting.

What is you canu command line?  Did you specify both the '-d' and '-p' options?  Did you set 'gnuplotTested=true' as it said to?

**Comment by Ikedakei** [comment]
Thank you for your replay, brianwalenz.
I write as below in command line and reaction to input command;

xxxxxxx:~$ ./canu/Linux-amd64/bin/canu -d ecoli-oxford -p ecoli genomeSize=4.8m -nanopore-raw oxford.fasta
(Cited from “https://canu.readthedocs.io/en/latest/quick-start.html”)
-- Canu snapshot v1.7 +363 changes (r9055 adfe0c503b62e2127a300209d50a07ebed6e5fcc)
--
-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
-- 
-- Read and contig alignments during correction, consensus and GFA building use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_181' (from 'java') with -d64 support.
Can't exec "gnuplot": そのようなファイルやディレクトリはありません[No files or directory]  at /home/kibanken/canu/Linux-amd64/bin/../lib/site_perl/canu/Defaults.pm line 1106.
readline() on closed filehandle F at /home/kibanken/canu/Linux-amd64/bin/../lib/site_perl/canu/Defaults.pm line 1107.

usage:   canu [-version] [-citation] \
              [-correct | -trim | -assemble | -trim-assemble] \
              [-s <assembly-specifications-file>] \
               -p <assembly-prefix> \
               -d <assembly-directory> \
               genomeSize=<number>[g|m|k] \
              [other-options] \
              [-pacbio-raw |
               -pacbio-corrected |
               -nanopore-raw |
               -nanopore-corrected] file1 file2 ...

example: canu -d run1 -p godzilla genomeSize=1g -nanopore-raw reads/*.fasta.gz 


  To restrict canu to only a specific stage, use:
    -correct       - generate corrected reads
    -trim          - generate trimmed reads
    -assemble      - generate an assembly
    -trim-assemble - generate trimmed reads and then assemble them

  The assembly is computed in the -d <assembly-directory>, with output files named
  using the -p <assembly-prefix>.  This directory is created if needed.  It is not
  possible to run multiple assemblies in the same directory.

  The genome size should be your best guess of the haploid genome size of what is being
  assembled.  It is used primarily to estimate coverage in reads, NOT as the desired
  assembly size.  Fractional values are allowed: '4.7m' equals '4700k' equals '4700000'

  Some common options:
    useGrid=string
      - Run under grid control (true), locally (false), or set up for grid control
        but don't submit any jobs (remote)
    rawErrorRate=fraction-error
      - The allowed difference in an overlap between two raw uncorrected reads.  For lower
        quality reads, use a higher number.  The defaults are 0.300 for PacBio reads and
        0.500 for Nanopore reads.
    correctedErrorRate=fraction-error
      - The allowed difference in an overlap between two corrected reads.  Assemblies of
        low coverage or data with biological differences will benefit from a slight increase
        in this.  Defaults are 0.045 for PacBio reads and 0.144 for Nanopore reads.
    gridOptions=string
      - Pass string to the command used to submit jobs to the grid.  Can be used to set
        maximum run time limits.  Should NOT be used to set memory limits; Canu will do
        that for you.
    minReadLength=number
      - Ignore reads shorter than 'number' bases long.  Default: 1000.
    minOverlapLength=number
      - Ignore read-to-read overlaps shorter than 'number' bases long.  Default: 500.
  A full list of options can be printed with '-options'.  All options can be supplied in
  an optional sepc file with the -s option.

  Reads can be either FASTA or FASTQ format, uncompressed, or compressed with gz, bz2 or xz.
  Reads are specified by the technology they were generated with, and any processing performed:
    -pacbio-raw         <files>      Reads are straight off the machine.
    -pacbio-corrected   <files>      Reads have been corrected.
    -nanopore-raw       <files>
    -nanopore-corrected <files>

Complete documentation at http://canu.readthedocs.org/en/latest/

ERROR:  Failed to run gnuplot from 'gnuplot'.ERROR:  Set option gnuplot=<path-to-gnuplot> or gnuplotTested=true to skip this test and not generate plots.

**Comment by skoren** [comment]
Looks like you have no gnuplot executable or it is broken. Have you tried adding gnuplotTested=true to the command line?

**Comment by Ikedakei** [comment]
Thank you for your reply, skoren.  After gnulot was installed, I can execute Canu.
