### ISSUE TITLE
Statistics of  corrected and assembly Reads

### ISSUE THREAD

**Issue by shameem356** [marbl/canu#105]
Hello,

I have finished  correction and trimming of pacbio reads by using -correct and -assemble option. Now I am looking some information like "distribution of the lengths of the corrected reads".I would like to know that how get these information ..?

**Comment by skoren** [comment]
There are logs of the read length distribution before and after correction to stdout/stderr. If you ran the assembler on the grid it would be in the canu-scripts/canu.*.out files so you can do
```
less <canu folder>/canu-scripts/canu.*.out
```
You can also view the correction.html output for more information on the corrected reads.

One other thing, you don't need to run correct and assemble separately, if you specify nothing, Canu will automatically correct, trim, and assemble your data.

**Comment by shameem356** [comment]
canu-scripts folder of  correction process is empty and correction.html page is showing empty Correction & Corrected Reads fields .However *correctedReads.fastq file is  generated after correction process.

**Comment by JohnUrban** [comment]
Try looking at:
asm/correction/asm.gkpStore/readlengthhistogram.txt -- input reads
asm/trimming/asm.gkpStore/readlengthhistogram.txt  -- reads after correction
asm/unitigging/asm.gkpStore/readlengthhistogram.txt  -- reads after trimming, input to assembly

Those folders also each have a readlengths.txt file you can use to compute any of your own stats on.

**Comment by skoren** [comment]
Closing since this has been answered, please re-open if you have further questions about the read length outputs.
