### ISSUE TITLE
restart from XXX.correctedReads.fasta.gz

### ISSUE THREAD

**Issue by jayceejiao** [marbl/canu#1050]
Hi,

I am using canu to assemble a highly repetitive plant genome (1G). The trimming step configured 574 overlapInCore jobs and it takes me more than 20 days to finish 60 jobs. I checked the previously reported issues  #1014. I want to restart the pipeline with ovlMerThreshold=500 from correctedReads and redo all the overlapInCore jobs. Now I am not sure which outputs should I delete and do I need to manually do something you mentioned in #1014 from step 2 to step 4 before I restart?

```
1. Kill any current canu jobs
2. Re-run meryl in trimming/0-mercounts using meryl.sh
3. Generate a new trimming/0-mercounts/*.ms22.frequentMers.fasta with a lower threshold than the default (meryl -Dt -n 500 -s ./asm.ms22 > ./asm.ms22.frequentMers.fasta should do it).
4. Re-launch using the overlap.jobSubmit-*.sh files and all the unfinished jobs will continue but with the modified repeat kmer threshold.
```

_CMD: canu -p XXX corOutCoverage=100 -d XXX-pacbio_all genomeSize=1009m  -pacbio-raw XXX_Pacbio.fastq.gz >canu.log   ## version canu-1.7.1
linux single server 1TB 72 cpus_

Thanks!

**Comment by jayceejiao** [comment]
output files I have: 

**_0-mercounts/**
-rw-rw-r-- 1 jiaochen jiaochen 871K Jul 26 08:22 plant.ms22.frequentMers.fasta
-rw-rw-r-- 1 jiaochen jiaochen 3.3K Jul 26 08:20 plant.ms22.histogram.sm.png
-rw-rw-r-- 1 jiaochen jiaochen  838 Jul 26 08:20 plant.ms22.histogram.sm.gp
-rw-rw-r-- 1 jiaochen jiaochen  14K Jul 26 08:20 plant.ms22.histogram.lg.png
-rw-rw-r-- 1 jiaochen jiaochen  840 Jul 26 08:20 plant.ms22.histogram.lg.gp
-rw-rw-r-- 1 jiaochen jiaochen    0 Jul 26 08:20 meryl.success
-rw-rw-r-- 1 jiaochen jiaochen    7 Jul 26 08:20 plant.ms22.estMerThresh.out
-rw-rw-r-- 1 jiaochen jiaochen  459 Jul 26 08:20 plant.ms22.estMerThresh.err
-rw-rw-r-- 1 jiaochen jiaochen 2.2M Jul 26 08:20 plant.ms22.histogram
-rw-rw-r-- 1 jiaochen jiaochen  115 Jul 26 08:20 plant.ms22.histogram.info
-rw-rw-r-- 1 jiaochen jiaochen 6.1M Jul 26 08:20 meryl.000001.out
-rwxr-xr-x 1 jiaochen jiaochen 1.4K Jul 26 07:13 meryl.sh*_

**1-overlapper/**
_-rw-rw-r-- 1 jiaochen jiaochen  16K Aug 17 14:14 overlap.000058.out
-rw-rw-r-- 1 jiaochen jiaochen  15K Aug 17 14:04 overlap.000056.out
-rw-rw-r-- 1 jiaochen jiaochen  25K Aug 17 13:48 overlap.000052.out
-rw-rw-r-- 1 jiaochen jiaochen 8.8K Aug 17 13:32 overlap.000060.out
-rw-rw-r-- 1 jiaochen jiaochen 5.2K Aug 17 13:22 overlap.000062.out
-rw-rw-r-- 1 jiaochen jiaochen  18K Aug 17 12:48 overlap.000054.out
drwxrwxr-x 2 jiaochen jiaochen 8.0K Aug 17 00:52 001/
-rw-rw-r-- 1 jiaochen jiaochen  32K Aug 17 00:51 overlap.000061.out
-rw-rw-r-- 1 jiaochen jiaochen  32K Aug 16 07:07 overlap.000059.out
-rw-rw-r-- 1 jiaochen jiaochen  32K Aug 15 13:55 overlap.000057.out
-rw-rw-r-- 1 jiaochen jiaochen  32K Aug 15 10:20 overlap.000046.out
-rw-rw-r-- 1 jiaochen jiaochen  32K Aug 14 23:17 overlap.000055.out
-rw-rw-r-- 1 jiaochen jiaochen  32K Aug 14 19:40 overlap.000050.out
-rw-rw-r-- 1 jiaochen jiaochen  32K Aug 14 17:26 overlap.000048.out
-rw-rw-r-- 1 jiaochen jiaochen  31K Aug 13 23:11 overlap.000044.out
.....
-rw-rw-r-- 1 jiaochen jiaochen  30K Jul 26 18:23 overlap.000004.out
-rw-rw-r-- 1 jiaochen jiaochen  30K Jul 26 15:39 overlap.000003.out
-rw-rw-r-- 1 jiaochen jiaochen  30K Jul 26 15:14 overlap.000005.out
-rw-rw-r-- 1 jiaochen jiaochen  30K Jul 26 13:16 overlap.000002.out
-rw-rw-r-- 1 jiaochen jiaochen  29K Jul 26 10:50 overlap.000001.out
-rwxr-xr-x 1 jiaochen jiaochen  87K Jul 26 08:22 overlap.sh*
-rw-rw-r-- 1 jiaochen jiaochen  58K Jul 26 08:22 plant.partition.err
-rw-rw-r-- 1 jiaochen jiaochen 2.3K Jul 26 08:22 plant.partition.ovlbat
-rw-rw-r-- 1 jiaochen jiaochen 4.0K Jul 26 08:22 plant.partition.ovljob
-rw-rw-r-- 1 jiaochen jiaochen  45K Jul 26 08:22 plant.partition.ovlopt_

**Comment by skoren** [comment]
The easiest to re-run all jobs is to completely erase the trimming folder and re-run the same Canu command. It will re-run the 60 jobs you already completed that way. The directions in #1014 are only needed if you wanted to save the output of the 60 jobs that already completed.

**Comment by jayceejiao** [comment]
Thanks!
