### ISSUE TITLE
Setting time limit for slurm job

### ISSUE THREAD

**Issue by Lcornet** [marbl/canu#1052]
Hello,

I'm trying to run CANU on a slurm cluster. I have a problem with the time limitation of the cluster. This the error message : 

Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
slurmstepd: error: *** JOB 3884617 ON node023 CANCELLED AT 2018-08-19T16:30:21 DUE TO TIME LIMIT ***

The time limit of the cluster is 14 days for a job and here it crash after one hour (default). This is because the jobs created by CANU (correction/1-overlapper/precompute.jobSubmit-01.sh) don't have the time limit specification. The job didn't include the line #SBATCH --time=13-24:00:00 # days-hh:mm:ss.
This line was present in the CANU submitted job (see below) but not in the sub jobs created by CANU.
Can you help me to include a specific time limitation in these sub jobs ?

#canu.job
#!/bin/bash
#SBATCH --time=13-24:00:00 # days-hh:mm:ss
#
#SBATCH --ntasks=60
#SBATCH --mem-per-cpu=2629 # megabytes
#SBATCH --partition=defq

/home/ulg/plgen/lcornet/work/CANU/canu-1.7/Linux-amd64/bin/canu -pacbio-raw all_proof-untrim-tme3.fastq genomeSize=1.4g \
corMhapFilterThreshold=0.0000000002 corMhapOptions="--threshold 0.78 --num-hashes 768 --num-min-matches 2 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50" \
maxMemory=64g maxThreads=60 gnuplotTested=true ovsMethod=parallel -p untrim -d untrim java=/home/ulg/plgen/lcornet/work/java/jre1.8.0_181/bin/java

Thanks,
Luc

**Comment by skoren** [comment]
See the FAQ: https://canu.readthedocs.io/en/latest/faq.html#how-do-i-run-canu-on-my-slurm-sge-pbs-lsf-torque-system. You can use gridOptions to request time which will be requested for all canu jobs.
