### ISSUE TITLE
Problem with Data Staging

### ISSUE THREAD

**Issue by Phylloxera** [marbl/canu#1053]
canu 1.7 on grid
~/canu-1.7/Linux-amd64/bin/canu -correct -p gaur_c -d <full path> -gnuplotTested=true -merylMemory=62 -batMemory=62 corMhapSensitivity=normal corOutCoverage=100 saveOverlaps=true stageDirectory=/local/$SLURM_JOBID gridEngineStageOption="--gres=lscratch:250" genomesize=2.8g -pacbio-raw<full path>

CRASH: Last 50 lines of the relevant log file (correction/2-correction/correctReads.jobSubmit-01.out):
sbatch: error: Batch job submission failed: Invalid generic resource (gres) specification

I'm trying to test data staging (i think for falconsense?) and received errors above. Is this a failure in how SLURM was set up? I followed the syntax from the parameter reference.

**Comment by skoren** [comment]
It is up to your grid to specify a way to request scratch space. The syntax in the reference is just an example for our grid. You should check with your IT if there is a way to request scratch space. 

If not, you'll have to request other resources to make sure the jobs won't fill up the available space, each job will need about the size of the gaur_c.gkpStore directory. For example, if you have 16-core 120GB ram nodes with 200GB of space. Assuming also the store is 50GB, you want to configure correction so at most 4 jobs fit on a node by setting corThreads=4 (16/4) or corMemory=30 (120/4).

**Comment by Phylloxera** [comment]
Talked to our sysadmin and he suggested removing the optional gridEngineStageOption specification. The job submitted when I did this. I did set corThreads=8 to keep the number of jobs submitted per node to no-more-than two. But on this grid, canu only runs 1-job-per-node... even when I think it could handle more based on threads available. Always assumed this had to do with the settings on our local grid because canu submits multiple jobs per node on a remote grid I use. There is a lot to try and figure out :)

**Comment by Phylloxera** [comment]
Speaking of the remote grid. I expected it to submit multiple falconsense jobs like on the local one but instead it is running a single very long (3days+) job on a single node. I'm not really sure how to check in and see what stage is actually running. This is my command on the remote grid:

canu -correct -p gaur_c -d <full path> -gnuplotTested=true corMhapSensitivity=normal \
corOutCoverage=100 saveOverlaps=true gridOptionsExecutive="--partition=short" \
gridOptionsMeryl="--partition=mem" gridOptionsCORMHAP="--partition=short" \
gridOptionsOVS="--partition=mem" gridOptionsCOR="--partition=short --time=7-00:00:00" \
stageDirectory=/scratch/$SLURM_JOBID gridEngineStageOption="--gres=lscratch:80" \
genomesize=2.8g -pacbio-raw <full path>

**Comment by skoren** [comment]
Removing the option would certainly work but I would also ask your IT dept to add a way to reserve scratch space on compute nodes. If they provide nodes with scratch space, there should be a way for jobs to request them too.

As for your second question, yes multiple correction jobs would be submitted to the grid. I expect the job you see is not the correction but a previous or subsequent step. You can check status by looking at the canu.out file in the top-level assembly directory, it will have the information on the command running or the last run command that completed.

**Comment by Phylloxera** [comment]
OK, I passed along the request to IT. It doesn't look like I'm getting any time savings over not staging just based on appearance of average runtimes for jobs. That being said, when I ssh into a compute node and ls /local, the gkpStore folder is there so staging must have done what I wanted. I guess I'll see at the end if my total falconsense runtime was less than 4 days, which was about what it was without staging.

The remote grid is closing in on 4 days (disjointed so maybe when I restarted it did not pick up where it left off?) running a job on a single node:
[aaron.dickey@sn-cn-8-1 ~]$ squeue -u aaron.dickey
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
            220819     short canu_gau aaron.di  R 1-23:15:03      1 sn-cn-11-1
[aaron.dickey@sn-cn-8-1 ~]$ tail /project/gaur_genome_assembly/ad_ceres/canu.out
    cd correction
    /software/7/apps/canu/1.7.1/bin/generateCorrectionLayouts \
      -G ./gaur_c.gkpStore \
      -O ./gaur_c.ovlStore \
      -C ./gaur_c.corStore.WORKING \
      -ec 4 \
      -eC 200 \
    > ./gaur_c.corStore.err 2>&1
I don't ever remember a task running this long on a single node on our local server for this canu correct job.

**Comment by skoren** [comment]
That steps always runs before falcon sense to make layouts for corrected reads. It is completely I/O bound so I expect it ran faster on your local system because it had better disk access than on your cluster.

**Comment by Phylloxera** [comment]
OK, so I guess that was tangential to the staging question, sorry. I'm ultimately building up to testing these jobs on an amazon web services hpc. At that point either myself or someone with BioTeam will be in charge of adding a way to reserve scratch space on the compute nodes. Presumably we will want to do this if the time savings is substantial. The hpc is running slurm, but I can tell that not all slurm settings are set (e.g. I can't run sacct commands). I know we might be venturing out of the software and into the hardware space but am curious your thoughts... might the 'way of reserving scratch space' be a slurm configuration setting after the hpc is built or something in the hpc or centos build specifications. Any direction (including educated guesses) are appreciated :)

**Comment by skoren** [comment]
Reserving scratch space is a generic resource request (GRES). As far as I know they can be configured after the cluster is built, just requires configuration changes.

If your goal is to run on amazon, running on your local cluster isn't going to be very informative. Canu already runs on AWS albeit through the DNA nexus interfaces. What you'd really want to do is adapt those to use the direct S3 interface (rather than DNA nexus) and AWS node requests. That will let you spin instance up/down on demand. Running as if you have a shared filesystem and SLURM cluster will likely be more expensive.

**Comment by BradleyRan** [comment]
Hi Sergey,  Makes sense.  The slurm docs are a little fuzzy to me.  Can you give us an example of how to set up gres scratch space using slurm?  It looks tome line we need 

1.  an entry in "slurm.conf" like "GresTypes=scratch"
