### ISSUE TITLE
cant' open 'correction/

### ISSUE THREAD

**Issue by Adelaam** [marbl/canu#1055]
Hello,
I am getting this error from canu 1.6:

cant' open 'correction//home/mwiks/untitled folder.gkpStore.gkp' for writing: /usr/bin/canu.

Thank you!

**Comment by Adelaam** [comment]
after running:
canu \
> -d '/home/mwiks/untitled folder'  -p '/home/mwiks/untitled folder' genomeSize=4m -nanopore-raw '/home/mwiks/m.absc.fasta' 
-- Canu 1.6
CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '10.0.1' (from 'java').
-- Detected gnuplot version '5.2 patchlevel 2' (from 'gnuplot') and image format 'png'.
-- Detected 4 CPUs and 16 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |  algorithm
--        -------  ------  --------   --------  -----------------------------
-- Local: meryl      8 GB    4 CPUs x   1 job   (k-mer counting)
-- Local: cormhap    6 GB    4 CPUs x   1 job   (overlap detection with mhap)
-- Local: obtovl     8 GB    4 CPUs x   1 job   (overlap detection)
-- Local: utgovl     8 GB    4 CPUs x   1 job   (overlap detection)
-- Local: cor        8 GB    2 CPUs x   2 jobs  (read correction)
-- Local: ovb        4 GB    1 CPU  x   4 jobs  (overlap store bucketizer)
-- Local: ovs        8 GB    1 CPU  x   4 jobs  (overlap store sorting)
-- Local: red        2 GB    4 CPUs x   1 job   (read error detection)
-- Local: oea        1 GB    1 CPU  x   4 jobs  (overlap error adjustment)
-- Local: bat       16 GB    4 CPUs x   1 job   (contig construction)
-- Local: cns       16 GB    4 CPUs x   1 job   (consensus)
-- Local: gfa        8 GB    4 CPUs x   1 job   (GFA alignment and processing)
--
-- Found Nanopore uncorrected reads in the input files.
--
-- Generating assembly '/home/mwiks/untitled folder' in '/home/mwiks/untitled folder'
--
-- Parameters:
--
--  genomeSize        4000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1440 ( 14.40%)
--    utgOvlErrorRate 0.1440 ( 14.40%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1440 ( 14.40%)
--    utgErrorRate    0.1440 ( 14.40%)
--    cnsErrorRate    0.1920 ( 19.20%)
--
--
-- BEGIN CORRECTION
--

ABORT:
ABORT: Canu 1.6
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   cant' open 'correction//home/mwiks/untitled folder.gkpStore.gkp' for writing: /usr/bin/canu.
ABORT:

**Comment by skoren** [comment]
I expect your error is because the prefix option (-p) is the prefix for assembly output, it should not be a path. Instead of your current value use something like ```-p asm```, see the quick start (https://canu.readthedocs.io/en/latest/quick-start.html) for examples.

**Comment by Adelaam** [comment]
Hello,

Thank you very much for your answer, it worked. But now I have got this error:


Finished on Wed Aug 22 10:00:55 2018 (lickety-split) with 858.693 GB free disk space
----------------------------------------
--
-- Mhap precompute jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/blocks/000001.dat FAILED.
--

ABORT:
ABORT: Canu 1.6
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
Does it mean I have not enough space or something with JAVA?

**Comment by skoren** [comment]
Probably a java issue, check the log in ```correction/1-overlapper/precompute.1.out``` or similar.

**Comment by Adelaam** [comment]
Starting 'cormhap' concurrent execution on Wed Aug 22 10:00:55 2018 with 858.693 GB free disk space (1 processes; 1 concurrently)
This was beforet he one I have already posted:

    cd correction/1-overlapper
    ./precompute.sh 1 > ./precompute.000001.out 2>&1

**Comment by Adelaam** [comment]
I have tried it, but it doesn't work:

bash: correction/1-overlapper/precompute.1.out: No such file or directory

**Comment by Adelaam** [comment]
ok, I have opened this one /home/mwiks/trial_oxford/correction/1-overlapper/precompute.0001.out:

Running job 1 based on command line options.
Dumping reads from 1 to 263 (inclusive).

Starting mhap precompute.

Error: Unable to access jarfile /usr/lib/canu/mhap.jar
Mhap failed. 

bash: /home/mwiks/trial_oxford/correction/1-overlapper/precompute.000001.out: Permission denied

**Comment by skoren** [comment]
How was canu installed on your system? That's not the default path we package it in and it appears to be missing part of the code. Try downloading the latest release from the GitHub page for your system (OSX?), removing any intermediate outputs (like the trial_oxford folder), and re-running.

**Comment by Adelaam** [comment]
ok, done but now I get this:
ERROR:  mhap overlapper requires java version at least 1.8.0; you have unknown (from 'java').
ERROR:  'java -showversion' reports:
ERROR:    'Error occurred during initialization of VM'
ERROR:    'java.lang.Error: Properties init: Could not determine current working directory.'
ERROR:    '	at java.lang.System.initProperties(Native Method)'
ERROR:    '	at java.lang.System.initializeSystemClass(System.java:1166)'
ERROR:    ''
I have tried to see java version:
java -version
Error occurred during initialization of VM
java.lang.Error: Properties init: Could not determine current working directory.
	at java.lang.System.initProperties(Native Method)
Should I have install a java version 8 or 10? How can I uninstall the version I have currently got installed?
Thank you!

**Comment by skoren** [comment]
Doesn't matter if you have 8 or 10, but it seems your java is not working. You should be able to run java -version outside of Canu. If that doesn't work, Canu won't either. If you're in a directory that has spaces in the name, try running in a folder without spaces, java might not be interpreting the spaces right.

**Comment by Adelaam** [comment]
I have installed Java 8 on linux mint and still the same:

CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_181' (from '/usr/lib/jvm/java-8-oracle/bin/java').
-- Detected gnuplot version '5.2 patchlevel 2' (from 'gnuplot') and image format 'png'.
-- Detected 4 CPUs and 16 gigabytes of memory.
-- No grid engine detected, grid disabled.



Mhap precompute jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/blocks/000001.dat FAILED.
--

ABORT:
ABORT: Canu 1.6
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.

Thank you anyway

**Comment by skoren** [comment]
And did you look at the same output file as on the OS X system?

**Comment by Adelaam** [comment]
I don't know if I understand you, do you mean for java when I download?

**Comment by skoren** [comment]
No, for Canu. When you install canu, don't use any package managers and download the latest release for your system from our release page. However you installed it originally on OS X (which installed Canu 1.6) didn't install it correctly and since you had version 1.6 again on Linux I presume you used the same installation method which I expect is again broken on linux.

You want to look at the same output file on linux as OS X, ```correction/1-overlapper/precompute.*.out```

**Comment by Adelaam** [comment]
There is something I am doing wrong obviously, I have download canu 1.7.1.Linux-amd64.tar.xz and unpacked it, I have got now a folder canu-1.7.1
Trying with:   xz -dc canu-1.7.1.Linux-amd64.tar.xz |tar -xf -
xz: canu-1.7.1.Linux-amd64.tar.xz: No such file or directory
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

**Comment by Adelaam** [comment]
I installed version 1.6 with python

**Comment by skoren** [comment]
You're missing the xz tool, try ```tar xvJf canu-1.7.1.Linux-amd64.tar.xz```.

**Comment by Adelaam** [comment]
$ tar xvJf canu-1.7.1.Linux-amd64.tar.xz
tar (child): canu-1.7.1.Linux-amd64.tar.xz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by skoren** [comment]
Wait I just went back and read your earlier comment, you said you already extracted it and have a canu-1.7.1 folder? If you have that folder, you don't need to extract anything else or run tar. Just run the canu command as you did before from the canu-1.7.1/*/bin/canu path.

**Comment by Adelaam** [comment]
Done!!
Thank you very much for your help!
BW
