### ISSUE TITLE
gatekeeperCreate: error while loading shared libraries

### ISSUE THREAD

**Issue by Hongchang-Gu** [marbl/canu#1063]
HELLO:
I'm running canu-1.7.1 on PacBio Sequel data
the command is:
`~/canu-1.7.1/Linux-amd64/bin/canu -correct \-p peking -d peking-auto \corThreads=30 gnuplotTested=true \genomeSize=1200m minReadLength=2000 minOverlapLength=500 \corOutCoverage=60 corMinCoverage=2 \maxMemory=500g maxThreads=48 ovsMemory=8-500g ovsThreads=4 oeaThreads=4 gridOptions=--partition=TH_BM \-pacbio-raw /vol6/home/quluj/gu/SMRT_DUCK_merge/data_sort/peking.fasta.gz/`

and then i got this error

```
ABORT:
ABORT: /vol6/home/quluj/gu/software/canu-1.7.1/Linux-amd64/bin/gatekeeperCreate: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   reads '/vol6/home/quluj/gu/SMRT_DUCK_merge/data_sort/peking.fasta.gz/' not found..
ABORT:
```

I am not quite sure where the problem is.

**Comment by skoren** [comment]
I am guessing you're running on the grid by your command line? Can you run the gatekeeper command from your head node? 

If you can run the command on the head node but not on the compute nodes, your nodes have a different environment than the head node. You need to make sure your compute nodes are inheriting the same environment as the head node (the option can be supplied in gridOptions and varies by grid type (e.g. -V on SGE).

**Comment by Hongchang-Gu** [comment]
Sorry, I am an entry-level student of code knowledge. Can you explain it specifically?
thanks a lot！

**Comment by skoren** [comment]
Your system is missing a common library which will break many tools, not just Canu. What is your exact Canu command and the output from it?

Try running the command ```/vol6/home/quluj/gu/software/canu-1.7.1/Linux-amd64/bin/gatekeeperCreate``` from wherever you launched Canu and post what it reports.

**Comment by Hongchang-Gu** [comment]
This is my exact Canu command：
`gu/software/canu-1.7.1/Linux-amd64/bin/canu -correct \-p peking -d peking-auto \corThreads=30 gnuplotTested=true \genomeSize=1200m minReadLength=2000 minOverlapLength=500 \corOutCoverage=60 corMinCoverage=2 \maxMemory=500g maxThreads=48 ovsMemory=8-500g ovsThreads=4 oeaThreads=4 gridOptions=--partition=TH_BM \-pacbio-raw /vol6/home/quluj/gu/SMRT_DUCK_merge/data_sort/peking.fasta.gz/`

and I didn't find the reason for the error in the command line. But I found the error from a file “peking-auto”:
```
-- /vol6/home/quluj/gu/software/canu-1.7.1/Linux-amd64/bin/gatekeeperCreate: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
--
-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
-- 
-- Read and contig alignments during correction, consensus and GFA building use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
--   Li H.
--   Minimap and miniasm: fast mapping and de novo assembly for noisy long sequences.
--   Bioinformatics. 2016 Jul 15;32(14):2103-10.
--   http://doi.org/10.1093/bioinformatics/btw152
-- 
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_111' (from '/vol6/home/quluj/Software/jre1.8.0_111/bin/java').
-- Detected 0 CPUs and 47 gigabytes of memory.
-- Limited to 500g gigabytes from maxMemory option.
-- Limited to 48 CPUs from maxThreads option.
-- Detected Slurm with 'sinfo' binary in /usr/bin/sinfo.
-- Detected Slurm with 'MaxArraySize' limited to 1000 jobs.
-- 
-- Found 2393 hosts with  12 cores and   22 GB memory under Slurm control.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl    256 GB   32 CPUs  (k-mer counting)
-- Grid:  cormhap   22 GB   12 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    16 GB   12 CPUs  (overlap detection)
-- Grid:  utgovl    16 GB   12 CPUs  (overlap detection)
-- Grid:  ovb        2 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs      500 GB    4 CPUs  (overlap store sorting)
-- Grid:  red        7 GB    4 CPUs  (read error detection)
-- Grid:  oea        4 GB    4 CPUs  (overlap error adjustment)
-- Grid:  bat      256 GB   16 CPUs  (contig construction)
-- Grid:  gfa       16 GB   16 CPUs  (GFA alignment and processing)
--
-- Found PacBio uncorrected reads in the input files.
--
-- Generating assembly 'peking' in '/vol6/home/quluj/peking-auto'
--
-- Parameters:
--
--  genomeSize        1200000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0750 (  7.50%)
--
--
-- BEGIN CORRECTION
--

ABORT:
ABORT: /vol6/home/quluj/gu/software/canu-1.7.1/Linux-amd64/bin/gatekeeperCreate: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   reads '/vol6/home/quluj/gu/SMRT_DUCK_merge/data_sort/peking.fasta.gz/' not found..
ABORT:
```

and after  running the command
 `/vol6/home/quluj/gu/software/canu-1.7.1/Linux-amd64/bin/gatekeeperCreate`

we can see the following report：
```
usage: /vol6/home/quluj/gu/software/canu-1.7.1/Linux-amd64/bin/gatekeeperCreate [-minlength L] -o gkpStore input.gkp
  -o gkpStore            load raw reads into new gkpStore
  -minlength L           discard reads shorter than L
  
ERROR: no gkpStore (-o) supplied.
```

thank you！

**Comment by Hongchang-Gu** [comment]
In fact, I found **libgomp.so.1** in **/usr/lib64** in the root directory, so which path should I need to add libgomp.so.1 to?

**Comment by skoren** [comment]
Right this is what I was saying. Your head node (where you launch canu) works fine and the same command runs. However, on a compute node in the cluster, libgomp.so.1 is missing, causing the crash. Essentially the issue is your head node and your compute node environments don't match. 

This is a grid configuration issue not a Canu issue, you'll have to work with your cluster IT to see if there are parameters they want you to pass or modules to load to add the missing library.

**Comment by Hongchang-Gu** [comment]
yeah. I tried to add that missing library last week. 
And the next error appeared.
```
Failed at /vol6/home/quluj/gu/software/canu-1.7.1/Linux-amd64/bin/../lib/site_perl/canu/Execution.pm line 1101
CRASH: 	canu::Execution::submitOrRunParallelJob('peking', 'meryl', 'correction/0-mercounts', 'meryl', 1) called at /vol6/home/quluj/gu/software/canu-1.7.1/Linux-amd64/bin/../lib/site_perl/canu/Meryl.pm line 538
CRASH: 	canu::Meryl::merylCheck('peking', 'cor') called at /vol6/home/quluj/gu/software/canu-1.7.1/Linux-amd64/bin/canu line 622
CRASH: Last 50 lines of the relevant log file (correction/0-mercounts/meryl.jobSubmit-01.out):
```
Specifically，we see the following




![_20180912120223](https://user-images.githubusercontent.com/42732926/45401632-1b043900-b684-11e8-9bd6-61d466490d40.png)

What caused this error?

thanks！

**Comment by skoren** [comment]
See the FAQ: https://canu.readthedocs.io/en/latest/faq.html#my-run-stopped-with-the-error-failed-to-submit-batch-jobs

The ```correction/0-mercounts/meryl.jobSubmit-01.out``` will have the exact error message. If your compute nodes cannot submit jobs you won't be able to run Canu on the grid unless you use the remote option. If there are some parameters required for all your jobs, you can add them using the ```gridOptions``` parameter.

**Comment by Hongchang-Gu** [comment]
thanks a lot!
