### ISSUE TITLE
Struggling to compile on OSZ

### ISSUE THREAD

**Issue by TullyIJ** [marbl/canu#1066]
Hi - I'm struggling with installation of canu on OSX.  First, I received the error message that my compiler was unsupported, requiring a non-clang compiler.  I've downloaded the brew version of gcc which seems to have cleared this hurdle.  I'm now receiving a make *** error1 message and do not know how to proceed further.  Command used:

    CC=/usr/local/Cellar/gcc CXX=/usr/local/bin/g++-8 make

...and the output:

    Building for 'Darwin' '17.5.0' as 'amd64' into '/usr/local/bin/canu/Darwin-amd64/{bin,obj}'.
    Using '/usr/local/bin/g++-8' version '8.2.0'.

     Building snapshot v1.7 +364 changes (r9056 2327563f151721fb9a803df769e998a5908baaa4) (sync'd with guthub)

    /usr/local/bin/g++-8 -o /usr/local/bin/canu/Darwin-amd64/obj/lib/libcanu.a/stores/ovStoreFile.o -c -MD -D_GLIBCXX_PARALLEL -fopenmp -pthread -fPIC -m64 -Wall -Wextra -Wno-write-strings -Wno-unused -Wno-char-subscripts -Wno-sign-compare -Wformat -g3 -O4 -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer -DNOBACKTRACE -I/usr/local/bin/canu/src -Iutility -Istores -Istores/libsnappy -Ialignment -Iutgcns/libNDalign -Iutgcns/libcns -Iutgcns/libpbutgcns -Iutgcns/libNDFalcon -Iutgcns/libboost -IoverlapInCore -IoverlapInCore/libedlib -IoverlapInCore/liboverlap stores/ovStoreFile.C
    stores/ovStoreFile.C: In member function 'void ovFile::writeBuffer(bool)':
    stores/ovStoreFile.C:241:92: error: invalid conversion from 'uint64*' {aka 'long long unsigned int*'} to 'size_t*' {aka 'long unsigned int*'} [-fpermissive]
     snappy::RawCompress((const char *)_buffer, _bufferLen * sizeof(uint32), _snappyBuffer, &bl);
                                                                                            ^~~
    In file included from stores/ovStoreFile.C:48:
    stores/libsnappy/snappy.h:122:28: note:   initializing argument 4 of 'void snappy::RawCompress(const char*, size_t, char*, size_t*)'
                        size_t* compressed_length);
                        ~~~~~~~~^~~~~~~~~~~~~~~~~
    stores/ovStoreFile.C: In member function 'void ovFile::readBuffer()':
    stores/ovStoreFile.C:368:52: error: invalid conversion from 'uint64*' {aka 'long long unsigned int*'} to 'size_t*' {aka 'long unsigned int*'} [-fpermissive]
       snappy::GetUncompressedLength(_snappyBuffer, cl, &ol);
                                                    ^~~
    In file included from stores/ovStoreFile.C:48:
    stores/libsnappy/snappy.h:170:38: note:   initializing argument 3 of 'bool snappy::GetUncompressedLength(const char*, size_t, size_t*)'
                                  size_t* result);
                                  ~~~~~~~~^~~~~~
    make: *** [/usr/local/bin/canu/Darwin-amd64/obj/lib/libcanu.a/stores/ovStoreFile.o] Error 1


I've had a look online as best I can, but I can't find a route to fix the problem - I wonder if you could help.

Thank you in advance.

**Comment by skoren** [comment]
Unless there's a specific reason you want the unreleased tip, the easiest way to install on OS X would be to use the pre-compiled binaries from the release page.

**Comment by TullyIJ** [comment]
Ah, yes, that would be simpler.  I think I misread the instructions in the readme… sorry to waste your time!

**Comment by skoren** [comment]
It seems to be an issue with gcc 7 or 8 on OS X (as @brianwalenz found) so using an older gcc version should also work.

**Comment by brianwalenz** [comment]
No worries, it needed to be fixed sooner or later.  It should work now.
