### ISSUE TITLE
Job cancelled due to time limit

### ISSUE THREAD

**Issue by JingXia730** [marbl/canu#1067]
Hi!
I was running canu/1.7 on Linux. This is the command I used:
```
#!/bin/bash
#SBATCH -N 1
#SBATCH --cpus-per-task=12
#SBATCH --mem=24G
#SBATCH --qos long
#SBATCH -t 6-00:00:00

module load canu/1.7
module load compiler/java/1.8.0_65-oracle

canu obtovlMemory=24 utgovlMemory=24 -p RH88_gDNA_command -d RH88_gDNA_command correctedErrorRate=0.154 gnuplotTested=TRUE minReadLength=10000 genomeSize=65m java=/ihome/sam/apps/compiler/java/jdk1.8.0_65/bin/java -nanopore-raw RHgDNA071718_command.fastq
```
It ran smoothly until it came to the last step, unitigging, with the error "slurmstepd: *** JOB 830329 CANCELLED AT 2018-08-06T17:21:44 DUE TO TIME LIMIT on n447 ***". I set the Quality of Service as “--qos=long” (max walltime is 6 days) when I submitted the job, but once it started to run, it would be divided into several “sub-jobs” on different nodes automatically, e.g. “835121_12”, “835121_13”, “835121_14” on three different nodes respectively. The Quality of Service of each “sub-job” was normal (max walltime is 3 days), and I found each "sub-job" stopped at the third day.

I tried running another software which would not separate job with the long QOS, it worked very well.

So could you please let me know what I should do to force canu not to generate those "sub-jobs"? or what I should do to solve this problem?

Thank you!

Best,
Jing

**Comment by skoren** [comment]
See the FAQ: https://canu.readthedocs.io/en/latest/faq.html#how-do-i-run-canu-on-my-slurm-sge-pbs-lsf-torque-system

You can tell canu to pass the QOS parameter to the sub jobs. You can disable the subjobs by specifying ```useGrid=false``` but I don't think you want that as it will take longer to run.

**Comment by JingXia730** [comment]
It works by adding `gridOptions="--qos=long --time=6-00:00:00"`!!

Thanks so much!!
