### ISSUE TITLE
Cluster renting

### ISSUE THREAD

**Issue by mictadlo** [marbl/canu#1069]
Hi,
Where could I rent a cluster in order to run CANU?

Thank you in advance,

Best wishes,

Michal

**Comment by skoren** [comment]
Your best best is to use AWS. You'd want to use their emulation of a SLURM/SGE cluster. Canu should become available through DNAnexus as well in the near future so you could also wait for that and have it run through DNAnexus' interface to AWS.

**Comment by mictadlo** [comment]
I just checked DNAnexus and it seems Canu is available https://platform.dnanexus.com/app/canu . Are there any Canu instructions how to do use AWS emulation of a SLURM/SGE cluster?
