### ISSUE TITLE
unitigging step produces contigs or unitigs in asm.contigs.fasta ?

### ISSUE THREAD

**Issue by albodrug** [marbl/canu#107]
Hello,

The tigInfo and readToTig files write about contigs. My understanding is that bogart is a unitigger and not a contigger. Is the utgcns consensus algorithm turning unitigs to contigs or the contig.fasta still contains only unitigs? If not, is there a way to keep unitigs from turning into contigs?

**Comment by skoren** [comment]
Unitigs and contigs are essentially equal when you don't have paired-end data, which no long-read sequencer currently produces. A unitig is a high confidence contig that ideally agrees with all the data (e.g. no branching). In practice it agrees with most of the data, ignoring some noise. 

The layouts for the outputs in asm.contigs.fasta and after the bogart step are identical. Those placed in asm.contigs.fasta are just designated as the primary assembly, versus those which were not well assembled (unassembled.fasta) and those which come from alternate variants (bubbles.fasta). All are unitigs and should either be fully contained in a repeat (e.g. a collapsed repeat) or be unique regions of the genome (where spanned repeats are considered unique) extending by at most one read into a repeat.

**Comment by albodrug** [comment]
Well thanks for clearing that up for me!
