### ISSUE TITLE
Discovering new transcript variants.

### ISSUE THREAD

**Issue by Omer-K** [marbl/canu#1071]
Broadly, I have reverse transcribed a transcript with gene-specific primer. 
The resulting ss-cDNA molecules served as template for PCR, and the ds-cDNAs were then sequenced with MinION.
I've inputted the data to canu, only indicating the `genomeSize` corresponding to the size of the PCR amplicon. Canu yielded very nice results, producing contigs which spanned 99% of the subject. But some contigs also had a rather long "missing" sequence (unfortunately for me these are not missing exactly an exon/s). These structures have not been reported before.

My question, knowingly a general one, is what would it take to validate that indeed these contigs are in fact transcript variants?

**Comment by skoren** [comment]
The first step is to check how many reads support this structure in the raw data. Canu outputs layout files which associate reads to the contigs so you can see how much of your data matches the deletion contigs (see docs on outputs). However, even if the read data supports the variants, it's possible that this is a PCR or sequencing artifact so I think at some point you'd have to go back to the lab for validation but the read support is a good start.

**Comment by skoren** [comment]
The layout files will give you reads and coordinates of those reads. You want to find reads which span the deletion not just reads in the contig (maybe they're all at the start of the product and don't span the area you are interested in), see:
https://canu.readthedocs.io/en/latest/tutorial.html#outputs

The file looks like this:
```
% head *.contigs.layout.readToTig 
#readID	tigID	coordType	bgn	end
3605930	5	ungapped	0	10322
7385820	5	ungapped	10988	1195
4780250	5	ungapped	1991	12165
5413056	5	ungapped	2925	12599
6630478	5	ungapped	5285	8244
```

You can look in ```*Store/readNames.txt``` which will give you the raw read ID:
```
grep 3605930 *Store/readNames.txt
3605930	m54315_180712_105314/34013651
```

I'm not an expert on lab experiments but yes, I guess PCR product sizes and short read sequencing.

**Comment by Omer-K** [comment]
Ok, got you.
I'll search for the layout files.

**Comment by Omer-K** [comment]
Is there an effective way for retrieving reads which were used specifically for the assembly of a contig?
For example, a contigs which interests me utilized over 2000 reads. I can see the readIds but tracking the raw reads manually will take me too long.

**Comment by skoren** [comment]
You can use grep with a file to get all the raw read ids and awk to extract the reads from the contig which span your region of interest.

**Comment by Omer-K** [comment]
> You can use grep with a file to get all the raw read ids 
I don't follow you.
The read IDs I can easily obtain from file contigs.layout.readToTig
How would I use the read IDs to extract the fast5 file names from readNames.txt, and then use this list of fast5 files to extract the files themselves from their libraries?

**Comment by skoren** [comment]
That's what I meant by using grep. If you have a list of the read IDs in a file named <x> then you can run ```grep -f x readNames.txt``` which will print all the fast5 file names. You can use any fasta/q utility to get a subset of your full dataset by read name (seqtk can do this).

**Comment by Omer-K** [comment]
I see now what you mean. But the `grep` command you've recommended is not functional (bare in mind I'm also fresh to linux commands)
Also, I'm not quite sure how to save to readsIDs from contigs.layout.readToTig.
I naively saved just the reads from a contig (1151) which was of interest to me to a new file which I've called `readNames.contig1151.txt`. I.e., I saved just one column containing the read names which are of interest to me. Is this okay? It looks like this

```
2586
4901
5889
4607
4538
7399
770
7421
1878
3444
```
Then I run `grep -f -x readNames.contig1151.txt readNames.txt`, but nothing outputs.

**Comment by skoren** [comment]
Man pages will help here (```man grep```). You have an extra - in your grep command that I didn't in the example. You probably also want to add a ^ before the read names too so you only match the beginning of the line (so your file would be
```
^2586
^4901
etc...
```

Then run:
``` grep -wf readNames.contig1151.txt *Store/readNames.txt``` and keep the second column (the raw read name) for input to seqtk or whatever tool you want to use to subset fasta/q files.

**Comment by Omer-K** [comment]
So the problem was with the format, it was windows (which was the OS I used to edit `readNames.contig1151.txt`, using excel).
I opened `readNames.contig1151.txt` in Mobaxterm (which I'm using as my Unix terminal) and saved it as Unix format. This time `grep -f -x readNames.contig1151.txt readNames.txt
` for some reason didn't work, but `grep -f readNames.contig1151.txt readNames.txt` did.

**Comment by Omer-K** [comment]
Thanks @skoren I'll give it a go.

**Comment by skoren** [comment]
Like I said it's the extra dash before the x which turns it into a flag not a file which is making it look for a full line match, from the man page:
```
       -x, --line-regexp
              Select only those matches that exactly match the whole line.  (-x is specified by POSIX.)
```

**Comment by Omer-K** [comment]
> You have an extra - in your grep command that I didn't in the example

True, because the `grep -f x` outputs an error `grep: x: No such file or directory`.
Therefor I though you meant a dash was intended (just mis-typed it) and then re-arranged as `grep -x -f`. Nevermind..

I edited, and added ^ before each filename.
But running `grep -wf readNames.contig1151.txt *Store/readNames.txt` just prints out ALL of the entries in file readNames.txt, with no discretion.

**Comment by skoren** [comment]
Then there must be a mistake or typo in your read names file. You'll have to debug it by trying to look for just one read with a file/etc. I've tested the following for example:
```
% cat tmp
^6
^2189
% grep -wf tmp *Store/readNames.txt
6	ddc04528-5ba0-423b-813e-2f2645bb8764 
2189	1c74dc7e-352e-45ec-b1f6-e8af1628a05d 
```

**Comment by Omer-K** [comment]
I tried thinning the file `readNames.contig1151.txt` and kept just two entries
```
^982
^2140
```

Then I run ` grep -wf readNames.contig1151.txt readNames.txt`. What I got was:
`982     dea6b629-2191-438f-ad60-9f27d0ef783a runid=d20680f0495125cc465d6a96efb49b194cb0777b read=1618 ch=481 start_time=2018-03-27T11:33:04Z
2140    0a8136cc-f1d9-4163-8358-42fdd3e8dfad runid=d20680f0495125cc465d6a96efb49b194cb0777b read=4082 ch=188 start_time=2018-03-27T11:58:18Z`

Which are two reads that I didn't mean to find.. It obviously matched the beginning of the file readNames..

So re-edited `readNames.contig1151.txt` and did 
```
read=982
read=2140
```

And run  `grep -wf readNames.contig1151.txt readNames.txt`. This time around the output was good:
`1555    53dc4007-357d-4378-a347-2b63b68d03a9 runid=d20680f0495125cc465d6a96efb49b194cb0777b read=2140 ch=412 start_time=2018-03-27T11:46:29Z`

The only thing that worries me now is that read 982 which` contigs.layout.readToTig` file indicated is not present in the `readNames` file (I've ctrl+f for it).

**Comment by skoren** [comment]
No your first output was correct, the IDs given by the layout file correspond to the first column of the readNames.txt file (the Canu numbering). The readid=XX line is just from the sequencer itself, completely unrelated to the Canu numbering. So you do want to be matching the beginning.

**Comment by Omer-K** [comment]
Oh.. Thanks for noting that!

**Comment by Omer-K** [comment]
What would be a quick way of adding the `^` char before each entry?

**Comment by skoren** [comment]
Sed or awk are good options for this task, ```cat readNames.contig1151.txt |sed s/^/^/``` should work. Again, man sed or man awk will give more info.

This issue has drifted quite a bit into linux support and not canu from the original question which should be answered so I'm going to close it. Please do update the issue with anything you are able to confirm in terms of whether these deletions are real or not.
