### ISSUE TITLE
Bogart Fails

### ISSUE THREAD

**Issue by sarah872** [marbl/canu#1076]
Based on the assembly graph & coverage generated by SPAdes, a ~8 kb plasmid assembled from genome sequencing a 2.4 Mb bacterial genome. Since it is incomplete/unclosed, I wanted to use canu for the assembly of this plasmid.
This is my command:

    canu -p plasmid -d plasmid -genomeSize=8k -maxThreads=8 -nanopore-raw all-nanopore-reads.fq.gz

However, the step `bogart` failed - I tried restarting multiple times.

Could it be that I am using reads that are longer than the plasmid are used? Should I filter out >10kb reads from the total reads?

[canu.out.txt](https://github.com/marbl/canu/files/2354570/canu.out.txt)

**Comment by brianwalenz** [comment]
The 1.7.1 release fixed several problems in bogart; you're running a version somewhere between 1.6 and 1.7.  Given the size of you assembly, I'd first suggest restarting with 1.7.1.

In your current assembly, check the *.report and/or canu screen output for a histogram of the trimmed read lengths.  If those are all below 8Kbp, there's no need to filter.  Even if a few are bigger than that, it might assemble correctly to a single 8Kbp copy.

**Comment by sarah872** [comment]
Thanks for the answer. I will try assembling with a new version.
Canu seems not to trim the reads:
[plasmid.report.txt](https://github.com/marbl/canu/files/2356410/plasmid.report.txt)
