### ISSUE TITLE
canu 1.7 unitigging ovlStore.BUILDING failed on a single linux computer with 2T memory.

### ISSUE THREAD

**Issue by JifengTang** [marbl/canu#1077]
canu 1.7 is used to assemble a plant genome size of about 450Mbp with input 50x nanopore data on a single linux computer with 2T memory and 64 cores.
The process went through correction and trimming step.
But it stopped at unitigging step --- ovlStore.BUILDING. 
The errors are:
```Found 791954858 (791.95 million) overlaps.
Configuring for 1800.00 GB to 1800.00 GB memory.
ERROR:  Cannot sort 791.95 million overlaps using 1800.00 GB memory; too few file handles available.
ERROR:    olapsPerBucket 48311671193
ERROR:    buckets        1
ERROR:  Increase memory size (in canu, ovsMemory; in ovStoreBuild, -M)
Command exited with non-zero status 1
```

The command used for the assembly was
```
canu  -p assembly -d assemblynanopore  genomeSize=450m ovsMemory=1800 -nanopore-raw 50x.filtered.fastq 
```
The actual running step is 
```
ovStoreBuild \
  -G assemblynanopore/unitigging/assembly.gkpStore \
  -O assemblynanopore/unitigging/assembly.ovlStore \
  -M 1800-1800 \
  -config assemblynanopore/unitigging/assembly.ovlStore.BUILDING/config \
  -L assemblynanopore/unitigging/1-overlapper/ovljob.files
```
More information about our system
```
$ ulimit -n
64000
$ cat /proc/sys/fs/file-max
1517562
$ grep -c assemblynanopore/unitigging/1-overlapper/ovljob.files
153
```

Does anyone have some ideas and suggestions to solve the problem?
I appreciate any suggestions.

**Comment by skoren** [comment]
I think you're hitting an overflow bug (48311671193 per bucket seems suspicious), first thing to try is to switch to 1.7.1 since that has several fixes to 1.7 and should be ok to restart from where you are. Just remove the ovlStore.BUILDING folder. Next would be to try decreasing memory to 1tb or lower to see if it will avoid the overflow if the new version doesn't fix it.

**Comment by JifengTang** [comment]
Thank you for the reply.
Decreasing memory to 1000g, 800g and 500g, it still generated the same errors.

I compiled 1.7.1 and restarted the pipeline. The errors  are 
ABORT:
ABORT: Canu 1.7.1
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   overlapper output '/.../unitigging/1-overlapper/001/000001.ovb.gz' not found.
ABORT:
Command exited with non-zero status 1

However, I did see /.../unitigging/1-overlapper/001/000001.ovb.gz exists with 456k size.

Do you have some clues what happened?
Thank you in advance.

**Comment by brianwalenz** [comment]
I'm confused by a couple of things.  Can you confirm which version of canu was initially used?  This doesn't look like 1.7.

Did Canu gzip compress the ovb files?  It hasn't done that for a long time.

Are the `/.../` your editing of a long path, or is that verbatim?  What's in assemblynanopore/unitigging/1-overlapper/ovljob.files?  This should be a list of relative paths to the ovb files.  Recreate this file using full paths (something like `ls $PWD/*/*ovb* > ovljob.files` run from inside the 1-overlapper directory should work).

The paths used in the ovStoreBuild command look odd.  Using 1.7, I see commands like:
```
    cd unitigging
    {path_to_canu_binaries}/ovStoreBuild \
     -O ./test.ovlStore.BUILDING \
     -G ./test.gkpStore \
     -M 2-8 \
     -L ./1-overlapper/ovljob.files \
     > ./test.ovlStore.err 2>&1
```
and I don't remember Canu ever running commands with paths like you've show.

Finally, if you use the original version of Canu (not 1.7.1) with small values for ovsMemory (e.g., 4, 8, 12) does it work?  Again, remove the ovlStore.WORKING before restarting.

**Comment by brianwalenz** [comment]
Idle.
