### ISSUE TITLE
changing number of threads in obtovl

### ISSUE THREAD

**Issue by pjm43** [marbl/canu#1078]
Hi,

I'm running in to a wall time issue with our grid (max wall time is 7 days).  I running nanopore data for the first time in canu 1.7.1 (50X coverage).  The automagic sets the obtovl to 16 GB and 8 CPUs.  When I look at my jobs they aren't using nearly the 16GB, so I figured one way to speed up the analysis would be increase the number of CPUs while reducing the GB.  To do this I added obtovlThreads=24 obtovlMemory=5g to the canu command line (below).  This gets parsed by canu and changes the slurm to report 5 GB and 24 CPUs:

```
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl    500 GB   24 CPUs  (k-mer counting)
-- Grid:  cormhap   16 GB    8 CPUs  (overlap detection with mhap)
-- Grid:  obtovl     5 GB   24 CPUs  (overlap detection)
-- Grid:  utgovl    16 GB    8 CPUs  (overlap detection)
-- Grid:  ovb        2 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       32 GB    1 CPU   (overlap store sorting)
-- Grid:  red        8 GB    4 CPUs  (read error detection)
-- Grid:  oea        4 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      256 GB   16 CPUs  (contig construction)
-- Grid:  gfa       16 GB   16 CPUs  (GFA alignment and processing)
```

but when a obtovl job gets launched the log still has -t 8 and hence limits the job to just 8 CPUs:

```
cat 1536244854_m8pws-1-1_164297_overlapInCore:
Command:
/panfs/pan.fsl.byu.edu/home/grp/fslg_pws_module/software/.conda/envs/canu_1.7.1/libexec/bin/overlapInCore \
  -G \
  -t 8 \
  -k 22 \
  -k ../0-mercounts/canu1_7_atriplex_60.ms22.frequentMers.fasta \
  --hashbits 24 \
  --hashload 0.75 \
  --maxerate 0.144 \
  --minlength 500 \
  -h 1273858-1320577 \
  -r 1-1271249 \
  --hashstrings 20111 \
  --hashdatalen 341248895 \
  -o ./001/000046.ovb.WORKING \
  -s ./001/000046.stats ../canu1_7_atriplex_60.gkpStore
```
Any idea why t is not being set to 24 for these jobs?

Thanks,

Jeff

```
#!/bin/bash
#SBATCH -c 24 --qos=pws --mem=128gb -t 3-00:00:00

module purge
module load conda-pws
module load conda/canu_1.7.1

canu -d canu1_7_atriplex_60 -p canu1_7_atriplex_60 genomeSize=1100m maxMemory=500g maxThreads=24 corMhapSensitivity=normal corOutCoverage=40 \
merylMemory=500g merylThreads=24 ovsMethod=parallel obtovlThreads=24 obtovlMemory=5g \
gridOptions="--qos=pws" \
gridOptionsOVS="--mem-per-cpu=64g --time=72:00:00" \
gridOptionsExecutive="--mem-per-cpu=24g --time=72:00:00" \
gridOptionsCORMHAP="--mem-per-cpu=10g --time=72:00:00" \
gridOptionsOBTMHAP="--mem-per-cpu=10g --time=72:00:00" \
gridOptionsUTGMHAP="--mem-per-cpu=10g --time=72:00:00" \
gridOptionsCOROVL="--mem-per-cpu=10g --time=72:00:00" \
gridOptionsOBTOVL="--mem-per-cpu=5g --cpus-per-task=24 --time=168:00:00" \
gridOptionsUTGOVL="--mem-per-cpu=6g --time=72:00:00" \
gridOptionsRED="--mem-per-cpu=12g --time=72:00:00" \
gridOptionsOEA="--mem-per-cpu=12g --time=72:00:00" \
gridOptionsOVB="--mem-per-cpu=12g --time=71:00:00" \
gridOptionsCNS="--mem-per-cpu=12g --time=70:00:00" \
-nanopore-raw trimmed.q8_l2000.porechop.fastq.gz
```

**Comment by skoren** [comment]
You have to remove the old overlapper.sh file when changing the parameters, I don't think it will get re-generated automatically.

While you're changing parameters, I'd suggest using ovlThreads rather than obtovlThreads since that will set it for the subsequent steps too, adding ovlMerThreshold=500, and restarting from the trimmed reads. This should also significantly speed up the overlapping step.

**Comment by pjm43** [comment]
Thanks for the quick reply!  You were correct - after removing the overlap.sh file, it was regenerated correctly (reflecting the new parameter).  Thanks for the suggestions regarding the ovlThreads and ovlMerThreshold.  Anything else you'd have me change:

#!/bin/bash
#SBATCH -c 24 --qos=pws --mem=128gb -t 3-00:00:00

module purge
module load conda-pws
module load conda/canu_1.7.1

canu -d canu1_7_atriplex_60 -p canu1_7_atriplex_60 genomeSize=1100m maxMemory=500g maxThreads=24 corMhapSensitivity=normal corOutCoverage=40 \
merylMemory=500g merylThreads=24 ovsMethod=parallel ovlThreads=24 obtovlMemory=5g ovlMerThreshold=500 \
gridOptions="--qos=pws" \
gridOptionsOVS="--mem-per-cpu=64g --time=72:00:00" \
gridOptionsExecutive="--mem-per-cpu=24g --time=72:00:00" \
gridOptionsCORMHAP="--mem-per-cpu=10g --time=72:00:00" \
gridOptionsOBTMHAP="--mem-per-cpu=10g --time=72:00:00" \
gridOptionsUTGMHAP="--mem-per-cpu=10g --time=72:00:00" \
gridOptionsCOROVL="--mem-per-cpu=10g --time=72:00:00" \
gridOptionsOBTOVL="--mem-per-cpu=5g --cpus-per-task=24 --time=168:00:00" \
gridOptionsUTGOVL="--mem-per-cpu=6g --time=72:00:00" \
gridOptionsRED="--mem-per-cpu=12g --time=72:00:00" \
gridOptionsOEA="--mem-per-cpu=12g --time=72:00:00" \
gridOptionsOVB="--mem-per-cpu=12g --time=71:00:00" \
gridOptionsCNS="--mem-per-cpu=12g --time=70:00:00" \
-nanopore-raw trimmed.q8_l2000.porechop.fastq.gz

Thanks,

Jeff

**Comment by skoren** [comment]
The rest look OK, any reason you're setting all those mem-per-cpu options? In many cases they don't match what Canu is configuring itself for but is larger so you'll end up over-reserving memory for your jobs.
