### ISSUE TITLE
Severe trimming

### ISSUE THREAD

**Issue by francicco** [marbl/canu#1079]
Hi,

I'm assembly 3 genomes the putative coverage vary (37x, 76x, 90x). For the first two assembly I just finished the trimming and it looks a bit harsh: 

```
--  OUTPUT READS:
--  ------------
--  723170 reads   4957249792 bases (trimmed reads output)
--  112965 reads    246390436 bases (reads with no change, kept as is)
--  1074436 reads     67554614 bases (reads with no overlaps, deleted)
--   63612 reads    142034966 bases (reads with short trimmed length, deleted)
--  
--  TRIMMING DETAILS:
--  ----------------
--  658405 reads    805839562 bases (bases trimmed from the 5' end of a read)
--  638758 reads    627223203 bases (bases trimmed from the 3' end of a read)
```

```
--  OUTPUT READS:
--  ------------
--  845511 reads   7533701111 bases (trimmed reads output)
--   67366 reads    213091435 bases (reads with no change, kept as is)
--  1673448 reads     41045529 bases (reads with no overlaps, deleted)
--   50489 reads    115564850 bases (reads with short trimmed length, deleted)
--  
--  TRIMMING DETAILS:
--  ----------------
--  762573 reads    999385064 bases (bases trimmed from the 5' end of a read)
--  745450 reads    797816567 bases (bases trimmed from the 3' end of a read)
```

The problem with this is that my coverage drops dramatically to 13 and 17 for the first two samples respectively.

Is this normal?
Thanks
F

**Comment by skoren** [comment]
Are you running all the genomes with default parameters? How much coverage did you have before trimming and after correction?

**Comment by skoren** [comment]
In that case the trimming isn't surprising, you're losing most of the data in correction. What data type is this, PacBio? Sequel?

**Comment by francicco** [comment]
PacBio of a quite heterozygosity species. This is the first assembly outputs.

Dryadula phaetusa
____________________________
N50: 154577 bp
Number of contigs: 6003
Longest contig: 1647849 bp
Genome length: 447963036 bp
____________________________

Dione juno
____________________________
N50: 53924 bp
Number of contigs: 9926
Longest contig: 2178371 bp
Genome length: 331293273 bp
____________________________

Eueides isabella
____________________________
N50: 56363 bp
Number of contigs: 13362
Longest contig: 1036744 bp
Genome length: 531564872 bp
____________________________

**Comment by skoren** [comment]
I'll guess Sequel data too? See the FAQ for parameter guidance for both Sequel and heterozygous genomes, the defaults are not going to be optimal in those cases. As a start I'd suggest:

```
37x: corMhapSensitivity=high corOutCoverage=100 corMinCoverage=0 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" correctedErrorRate=0.105 ovlMerThreshold=500
76x: corMhapSensitivity=normal corOutCoverage=100 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" correctedErrorRate=0.105 ovlMerThreshold=500
90x:corMhapSensitivity=normal corOutCoverage=100 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" correctedErrorRate=0.105 ovlMerThreshold=500
```

**Comment by francicco** [comment]
Thank you so much!!! What's Sequel data?
F

**Comment by skoren** [comment]
Which pacbio instrument was your data generated on, an RSII or a Sequel? If it's recent it's probably Sequel.

**Comment by francicco** [comment]
Oh yes! Sequel 2.0 chemistry
F

**Comment by francicco** [comment]
One quick question. After the assembly I'd like to run Arrow to try to polish farther the assembly. When should I remove haplotypes in the assembly? Before or after?
Thanks a lot

**Comment by skoren** [comment]
You should polish the full assembly to avoid mis-mapping reads from both haplotypes onto one locus as much as possible. You can remove haplotypes after this step.

**Comment by francicco** [comment]
Great!
F
