### ISSUE TITLE
Any comment or resource would be appreciated

### ISSUE THREAD

**Issue by prince26121991** [marbl/canu#108]
Read length distribution is:
```
0	999	0
1000	1999	4365880
2000	2999	2516795
3000	3999	1577202
4000	4999	1232543
5000	5999	810815
6000	6999	525348
7000	7999	331432
8000	8999	202718
9000	9999	119893
10000	10999	68977
11000	11999	38223
12000	12999	21045
13000	13999	11618
14000	14999	6285
15000	15999	3508
16000	16999	2091
17000	17999	1277
18000	18999	706
19000	19999	467
20000	20999	275
21000	21999	164
22000	22999	89
23000	23999	62
24000	24999	38
25000	25999	17
26000	26999	15
27000	27999	10
28000	28999	3
29000	29999	1
```

Overlapper having this output:

```
Category	Reads	Read Length	Feature Size or Coverage	Analysis
middle-missing 	71880	3998.88	±	2336.05	300.99	±	433.85	bad trimming
middle-hump 	10469	4379.90	±	2991.49	2046.65	±	2176.72	bad trimming
no-5-prime 	208809	2539.06	±	1969.58	570.80	±	902.68	bad trimming
no-3-prime 	172134	2553.38	±	2038.50	577.13	±	929.37	bad trimming
low-coverage 	281199	1859.38	±	1100.55	4.23	±	2.09	easy to assemble, potential for lower quality consensus
unique 	2514238	2481.55	±	1526.84	20.51	±	7.52	easy to assemble, perfect, yay
repeat-cont 	3365527	2889.77	±	1774.31	679.88	±	479.61	potential for consensus errors, no impact on assembly
repeat-dove 	39171	7966.94	±	2423.99	523.73	±	406.47	hard to assemble, likely won't assemble correctly or even at all
span-repeat 	664342	3971.12	±	2441.65	1586.08	±	1737.23	read spans a large repeat, usually easy to assemble
uniq-repeat-cont 	2775406	3134.00	±	1751.46				should be uniquely placed, low potential for consensus errors, no impact on assembly
uniq-repeat-dove 	859147	5903.65	±	2735.99				will end contigs, potential to misassemble
uniq-anchor 	449446	5592.11	±	2565.56	1397.89	±	1591.20	repeat read, with unique section, probable bad read
```

Any comment or resource to understand overlapper output, will be appreciated.

Thanks

**Comment by skoren** [comment]
What is your specific question? The categories are a summary of the overlap distribution across reads. Based on this information, reads are classified into different categories which are summarized in the last column. The length columns gives the average read length and feature length in each category. So in the middle-missing column, the average read length missing part of it's sequence is 4000bp while the missing region is on average 300bp long.

Is this output from the correction step? In that case the most useful categories would be the bad trimming ones. The no 5-prime and no-3-prime indicate reads which have no support on one or both ends while middle-missing are reads which will be split because they lack support across their full length. These could be chimeric sequences or, in the case of pacbio, could be reads with the SMRTbell adapter left in.

The other categories aren't particularly useful for correction statistics, there is always high number of low-coverage reads.

**Comment by prince26121991** [comment]
This is the output of overlapper step. Just before Overlap Error Adjustment. I corrected rads using prooveread and submitted them for assembly in canu. Gatekeeper,meryl and overlapper step is done, overlap error adjustment is currently running, My specific question is what this output stat indicating, coz in 6th line it says "easy to assemble, perfect, yay", so is it going to use only "unique  2514238" reads for assembly. or am I missing something here?
And one more question is arising now that how much approximate time it is going to take for overlap correction becuase in overlapping it was hardly taking 2 minute for for each job (total was 1334 job there). But for correction step it made 175 job and it is running on 8 node (32 processor/node = 256 processor ) so it assigned 8 processor for each job and it's running since 6 hour but not single job completed yet so just curious if u have any rough estimate. Genome size is 1.7G total corrected reads data is 43GB, after meryl step it was showing these stats
readsLoaded	11837497 reads (38440193508 bp)
readsSkipped	4398836 reads (3152979744 bp) (read was too short)
warnings	0 warnings (invalid base or quality value)

so if you can give any rough estimate for single job, coz till now it is looking most time consuming step.

Thanks

**Comment by skoren** [comment]
Ah, OK now I understand you question better. It will try to use all reads for the assembly, the stats are only an estimate so you have some idea of what your data looks like. It looks like you only ran the assemble step and the reads are not very well trimmed (almost 4% in the bad-trim category), which will definitely hamper assembly.  The reads with no 5-prime or 3-prime essentially are dead ends and won't get used. The single biggest category of your reads (29%) is repeat-contained reads which won't help assembly since they are non-unique. Unique easy to assemble reads make up only 22% of the data. For comparison here is a table from a recent run of a haploid human cell line:
```
category            reads       read length        feature size or coverage  analysis	precent	cumulative percent
----------------  -------  ----------------------  ------------------------  --------------------		
middle-missing        342    19379.27 +- 10696.71      1811.96 +- 2011.39    (bad trimming)	0.00643843	0.00643843
middle-hump            88     5628.74 +- 4172.56        377.59 +- 589.45     (bad trimming)	0.00165667	0.00809511
no-5-prime            434    12628.34 +- 7799.97        237.74 +- 608.34     (bad trimming)	0.00817041	0.0162655
no-3-prime            599    14157.40 +- 8031.70        244.05 +- 733.55     (bad trimming)	0.0112767	0.0275422
	0	0.0275422
low-coverage         5707     4630.49 +- 3892.86          4.67 +- 1.94       (easy to assemble, potential for lower quality consensus)	0.107439	0.134981
unique            4123625    16572.90 +- 8507.55         31.63 +- 7.34       (easy to assemble, perfect, yay)	77.6307	77.7656
repeat-cont        293154    12595.09 +- 8987.05       1712.69 +- 4503.96    (potential for consensus errors, no impact on assembly)	5.51887	83.2845
repeat-dove          6121    34380.07 +- 7657.63        527.99 +- 921.67     (hard to assemble, likely won't assemble correctly or even at all)	0.115233	83.3997
	0	83.3997
span-repeat        521231    21951.09 +- 8629.11       4512.57 +- 4682.63    (read spans a large repeat, usually easy to assemble)	9.81261	93.2123
uniq-repeat-cont   293738    16646.20 +- 6948.92                             (should be uniquely placed, low potential for consensus errors, no impact on assembly)	5.52986	98.7422
uniq-repeat-dove    38747    30665.36 +- 7924.53                             (will end contigs, potential to misassemble)	0.729444	99.4717
uniq-anchor         28065    21220.10 +- 8483.42       7669.39 +- 7130.39    (repeat read, with unique section, probable bad read)	0.528347	100
```

You can see most of the reads are in the easy to assemble category and less than 0.5% are badly trimmed. So overall, I'd expect your assembly to not be very contiguous. I'd suggest running both assembly and trimming (run canu with -pacbio-corrected rather than specifying canu -assemble) which should help to fix the 4% of badly trimmed reads. You can also just run canu end-to-end if you have at least 20X of coverage with the raw data using the latest release and the parameters I suggested to another user recently:
```
corMhapSensitivity=high corMinCoverage=0 errorRate=0.035  minOverlapLength=499
```

Lastly, 3-overlapErrorAdjustment should be faster in CPU time than 1-overlapper (about 3x faster typically) but it is not parallelized as well so can be slower in wall-clock time. It's possible you can benefit from partitioning into more jobs to run more jobs concurrently and reduce the wall-clock time.

**Comment by prince26121991** [comment]
Well thanks for your kind suggestions and parameters. I am having shortage of time that is why I was running only -assemble step with canu, because I am working on this project since may,2015 it is almost one year is going to complete and I have only some basic stats regarding reads I started it with smrtanalysis using MHAP2 algorithm at that time I had 20X coverage but after read correction only 8X coverage left which was not sufficient for celera therefor after 3 month I got nothing in result except to increase coverage of genome, as MHAP needs atleast 60-70X coverage for eukaryotic genome which was very cost effective in our case so we found alternative which was hybrid assembly we generated approximately 42X (72GB) coverage data for PB reads only and 70X coverage illumina and corrected it using several tool like ECtool, spades and many more but all were extremely time consuming, finally we found prooveread and started correcting PB reads, in initial stage of prooveread we also get to know that prooveread is giving almost half size of input file so were sure that we will get atleast 20X coverage at the end, after 6 month correction time we have now 43 GB (25X) of corrected reads. In the mean time I found canu assembler for PB reads specialist. so just three days ago when we get our last corrected file we started assembly using canu, and I used only -assemble option because trimming step aslo performed by prooveread for chimeric reads.

So this is the whole story now I can go with your suggestion as you are saying if I have 20X coverage for raw reads ( I have 42x coverage of raw reads) thn I can run it with your provided parameters.
or
I can run with -pacbio-corrected using trimming and assemble option.

So you suggest me which one is better becuase I didn't use MHAP so I dont have idea about time it is going to take if it also going to take same time as HGAP (almost 3 months) thn I will prefer 2nd option.
That's it sir
Thanks

**Comment by skoren** [comment]
HGAP is very slow and has some issues on repetitive genomes so I wouldn't expect it to work well on a large genome like this. The Canu correction step should be faster then the assemble step. As for proovread trimming, I think it is not aggressive enough for assembly judging by the overlap statistics so the assembler's trimming is likely to shorten your reads but make the usable for the assembly.

**Comment by prince26121991** [comment]
One more point I want to take in your consideration that its a plant genome so this much repeat content is valid in our case, And it's a diploid genome

**Comment by prince26121991** [comment]
Sir,
The table you are showing for human haploid cell line, is at how much raw reads coverage?

**Comment by skoren** [comment]
It's about 65X but here is a vertebrate 2.6G genome at 18X:
```
category            reads       read length        feature size or coverage  analysis   precent cumulative percent
----------------  -------  ----------------------  ------------------------  --------------------       
middle-missing       1458     9963.99 +- 4979.86        734.33 +- 771.67     (bad trimming)	0.04	0.04
middle-hump           238     5048.75 +- 3524.76        440.30 +- 670.83     (bad trimming)	0.01	0.04
no-5-prime           5246     8871.13 +- 4786.62        216.89 +- 498.37     (bad trimming)	0.13	0.17
no-3-prime           5170     8832.22 +- 4671.67        218.14 +- 488.45     (bad trimming)	0.13	0.30
	0.00	0.30
low-coverage       105414     3273.24 +- 2344.77          5.31 +- 1.81       (easy to assemble, potential for lower quality consensus)	2.61	2.91
unique            2515979     7102.23 +- 4472.61         17.63 +- 4.80       (easy to assemble, perfect, yay)	62.39	65.30
repeat-cont         56244     5165.44 +- 3827.26        715.35 +- 955.69     (potential for consensus errors, no impact on assembly)	1.39	66.70
repeat-dove           637    15491.83 +- 4943.53        314.14 +- 310.55     (hard to assemble, likely won't assemble correctly or even at all)	0.02	66.72
	0.00	66.72
span-repeat        428962    10787.93 +- 4840.76       2985.39 +- 3198.49    (read spans a large repeat, usually easy to assemble)	10.64	77.35
uniq-repeat-cont   653200     7264.53 +- 3572.59                             (should be uniquely placed, low potential for consensus errors, no impact on assembly)	16.20	93.55
uniq-repeat-dove   249142    13595.63 +- 3753.87                             (will end contigs, potential to misassemble)	6.18	99.73
uniq-anchor         10960    11134.72 +- 4121.20       4914.18 +- 3846.49    (repeat read, with unique section, probable bad read)	0.27	100.00
```

You can see a similar read distribution despite the lower coverage.

**Comment by prince26121991** [comment]
perl canu -d 3rd_trial    -p 3rd_try   -assemble    genomeSize=1.7g   corMhapSensitivity=high corMinCoverage=0 errorRate=0.035  minOverlapLength=499   useGrid=1  -pacbio-corrected /home/scbbcluster/nitesh_mpi/pacbio_assembly/2nd_try.trimmedReads.fastq

Reads corrected by prooveread and trimmed by canu, Here I used and submitted them for assembly as you suggested with these parameter, but stopped just before stats generation.






-- Finished on Thu Apr 28 17:31:04 2016 (19 seconds) with 20151.2 GB free disk space
----------------------------------------
--
-- Overlap store '/home/scbbcluster/nitesh_mpi/pacbio_assembly/canu-1.2/Linux-amd64/bin/3rd_trial/unitigging/3rd_try.ovlStore' successfully constructed.
--
-- Purged 48.541 GB in 1224 overlap output files and 2 directories.
----------------------------------------
-- Starting command on Thu Apr 28 17:31:11 2016 with 20216.6 GB free disk space

    /home/scbbcluster/nitesh_mpi/pacbio_assembly/canu-1.2/Linux-amd64/bin/ovStoreStats \
     -G /home/scbbcluster/nitesh_mpi/pacbio_assembly/canu-1.2/Linux-amd64/bin/3rd_trial/unitigging/3rd_try.gkpStore \
     -O /home/scbbcluster/nitesh_mpi/pacbio_assembly/canu-1.2/Linux-amd64/bin/3rd_trial/unitigging/3rd_try.ovlStore \
     -o /home/scbbcluster/nitesh_mpi/pacbio_assembly/canu-1.2/Linux-amd64/bin/3rd_trial/unitigging/3rd_try.ovlStore \
     > /home/scbbcluster/nitesh_mpi/pacbio_assembly/canu-1.2/Linux-amd64/bin/3rd_trial/unitigging/3rd_try.ovlStore.summary.err 2>&1

-- Finished on Thu Apr 28 17:55:36 2016 (1465 seconds) with 20216.1 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 1.
ERROR:
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

Disk space available:  20216.1 GB

Last 50 lines of the relevant log file (/home/scbbcluster/nitesh_mpi/pacbio_assembly/canu-1.2/Linux-amd64/bin/3rd_trial/unitigging/3rd_try.ovlStore.summary.err):

Failed to open '/home/scbbcluster/nitesh_mpi/pacbio_assembly/canu-1.2/Linux-amd64/bin/3rd_trial/unitigging/3rd_try.ovlStore.summary' for writing: Cannot allocate memory

canu failed with 'failed to generate statistics for the overlap store'.

**Comment by prince26121991** [comment]
category            reads       read length        feature size or coverage  analysis
----------------  -------  ----------------------  ------------------------  --------------------
middle-missing      20175     3898.89 +- 2210.98        265.28 +- 338.52     (bad trimming)
middle-hump          4335     3599.60 +- 2292.74        669.66 +- 1123.74    (bad trimming)
no-5-prime          40506     3376.86 +- 2264.07        282.71 +- 562.13     (bad trimming)
no-3-prime          39727     3408.93 +- 2283.20        284.83 +- 576.41     (bad trimming)

low-coverage       223434     1964.81 +- 1218.91          3.74 +- 2.18       (easy to assemble, potential for lower quality consensus)
unique            2161130     2432.94 +- 1479.09         20.97 +- 7.67       (easy to assemble, perfect, yay)
repeat-cont       4269802     2905.71 +- 1803.18        810.85 +- 610.00     (potential for consensus errors, no impact on assembly)
repeat-dove         88263     7319.33 +- 2595.16        551.71 +- 478.53     (hard to assemble, likely won't assemble correctly or even at all)

span-repeat        554845     3911.52 +- 2404.15       1537.13 +- 1685.36    (read spans a large repeat, usually easy to assemble)
uniq-repeat-cont  2639844     3093.20 +- 1756.88                             (should be uniquely placed, low potential for consensus errors, no impact on assembly)
uniq-repeat-dove   734678     5878.64 +- 2761.82                             (will end contigs, potential to misassemble)
uniq-anchor        496513     5453.00 +- 2634.42       1388.23 +- 1532.72    (repeat read, with unique section, probable bad read)


Well Here is the new stats, But what I have to do to resume this job from here?

**Comment by prince26121991** [comment]
I sorted it out using previous run trial, I made new canu.04.sh by using previous file, just parameter changed this time, it is running now for error correction module on all node.
Thank you.

**Comment by skoren** [comment]
Your stats look much better, less than 1% of the reads are now badly trimmed. I would still suggest just running canu from the raw reads for comparison.

**Comment by prince26121991** [comment]
Sir, I am already on it, at one of our server am working on completely aw read also, but there is problem arising of space, that system has 23TB memory itself, but oeverlap file made by mhap is taking 50-60 GB /file, there are approxmately 873 job divided on RAW read and yet only 220 job completed and they had taken almost 20TB memory in mhap overlap file, I can shift them on other storage but thn question is how would I take them as input for next step, coz we can take input from a single place and I dont have 50-60TB memory at a single place.

**Comment by skoren** [comment]
What was the command you used to run Canu? If you're doing low coverage options it will generate more data, given 40x you may be able to run with default parameters.

You can remove the *.mhap output files as long as there are corresponding *.ovb.gz files. That is if you do an ls: 
```
000001.counts  
000001.mhap    
000001.ovb.gz  
000002.counts
000002.mhap 
000002.ovb.gz
000003.mhap 
```

In this case, you could remove 000001.mhap  and 000002.mhap.

**Comment by prince26121991** [comment]
```
                                                   (prooveread+Canu assembler)  (Prooveread+ Canu trim and assembly
Total Sequences	                                                   104917	         128672
Maximum Length of a sequence is	                           133646	         136594
Sequence having More than 1000 Nucleotide	   100	         99.995
N50 value is	                                                           18479	         16380
NG50 value is	                                                           19057	         16907
Total BP value is	                                                   1783775585	 1781279813
Total average is	                                                   17001.7784 	 13843.56979
Minimum Length of a sequence is	                           1996	          998

```

Ok so here are the stats from starting two assembly.
However PB reads only assembly using MHAP is going on.

**Comment by brianwalenz** [comment]
Idle.  Open new issue if needed.
