### ISSUE TITLE
Assembly hangs in gnuplot during trimming

### ISSUE THREAD

**Issue by mchaisso** [marbl/canu#1084]
I'm running a small assembly.  The command options are:

 -pacbio-raw reads.fasta genomeSize=60000 -d assembly -p asm useGrid=false gnuplotTested=true corMhapSensitivity=high corMinCoverage=1 cnsThreads=4 ovlThreads=4 mhapThreads=4 contigFilter="2 1000 1.0 1.0 2"

During the trimming phase (command below), it stalls on the gnuplot command.  Checking for running jobs shows:

`sh -c gnuplot ./asm.1.trimReads.inputReads.gp > /dev/null 2>&1`

When I go to the assembly directory and run the command without redirection:
`sh -c gnuplot ./asm.1.trimReads.inputReads.gp`, it enters the gnuplot shell.

If I instead run:
`sh -c gnuplot <  ./asm.1.trimReads.inputReads.gp` it ends without problems.  

I'm trying to track down the source of this since I've been able to run canu commands before, so it's possibly something changed on our cluster.  However, if it is possible to add an option to skip plotting, this will reduce some file IO and this issue.

The trimming step:

    cd trimming/3-overlapbasedtrimming
    /auto/cmb-16/mjc/shared/software_packages/canu/Linux-amd64/bin/trimReads \
      -G  ../asm.gkpStore \
      -O  ../asm.ovlStore \
      -Co ./asm.1.trimReads.clear \
      -e  0.045 \
      -minlength 1000 \
      -ol 1 \
      -oc 1 \
      -o  ./asm.1.trimReads \
    >     ./asm.1.trimReads.err 2>&1

**Comment by brianwalenz** [comment]
Very bizarre.  From the gnuplot manpage:
```
If file names are given on the command line, gnuplot loads and executes each file
in the order specified, and exits after the last file is processed.  If no files are
given, gnuplot prompts for  interactive commands.
```
leading me to think it's not seeing the file.  Since all you changed in your test was adding a redirect, gnuplot is being run in the correct directory and the file exists.

Was your gnuplot just upgraded to a different version?  Which version is it?

You can try setting Canu option `gnuplot="gnuplot <"` to trick it into using the redirect instead of opening the file directly.  I need to do some minor maintenance on the plots and will add a way to disable them.

**Comment by mchaisso** [comment]
gnuplot --version
gnuplot 5.2 patchlevel 4

I had actually tried that and there were some issues. Currently the system command is just commented out in my code. I'll get back to this in a couple of days and re-test .

**Comment by brianwalenz** [comment]
I changed the way gnuplot is setup and run.  You can now do `gnuplot=` or `gnuplot=undef` to disable gnuplot.

I'm running it as `gnuplot < /dev/null file.gp`.  Does that work as expected for you?  I suppose I could make it read stdin...that just seems impure for some reason.

**Comment by mchaisso** [comment]
Awesome!

**Comment by mchaisso** [comment]
Oh, I replied too early. I'll let you know if it works in a bit.

**Comment by brianwalenz** [comment]
> Oh, I replied too early. I'll let you know if it works in a bit.

Fortunately, I can edit and delete comments.  ;-)

**Comment by brianwalenz** [comment]
Assuming fixed.

**Comment by mchaisso** [comment]
Yes, sorry, I haven't gotten back to running any canu jobs lately.  Will
open again if there are issues.
