### ISSUE TITLE
meryl configuration failing on small input

### ISSUE THREAD

**Issue by mchaisso** [marbl/canu#1085]
I'm not sure what the function is doing, but the meryl configuration fails on small input

Changing:
```
    foreach my $ss (qw(01 02 04 06 08 12 16 20 24 32 40 48 56 64 96)) {
        my $mem = undef;
        my $bat = undef;
```

to:
```
foreach my $ss (qw(01 02 04 06 08 12 16 20 )) {
...
  
resolves the issue.   The command that is ran is:

canu -pacbio-raw reads.fasta genomeSize=30000 -d assembly -p asm useGrid=false gnuplotTested=true corMhapSensitivity=high corMinCoverage=1 cnsThreads=4 ovlThreads=4 mhapThreads=4 contigFilter="2 1000 1.0 1.0 2"

**Comment by brianwalenz** [comment]
Thanks for reporting.  This is in a large bit of new code.

Can you supply one of the errors reported?

What reads do you have?  I'm looking for the canu report that looks like:
```
-- In sequence store './test.seqStore':
--   Found 1444 reads.
--   Found 2071770 bases (41.43 times coverage).
--
--   Read length histogram (one '*' equals 3.85 reads):
--     1000   1099    270 **********************************************************************
--     1100   1199    238 *************************************************************
--     1200   1299    163 ******************************************
--     1300   1399    160 *****************************************
--     1400   1499    121 *******************************
--     1500   1599    122 *******************************
--     1600   1699     87 **********************
--     1700   1799     53 *************
--     1800   1899     50 ************
--     1900   1999     38 *********
--     2000   2099     34 ********
--     2100   2199     30 *******
--     2200   2299     19 ****
--     2300   2399     16 ****
--     2400   2499     13 ***
--     2500   2599     11 **
--     2600   2699      6 *
--     2700   2799      3 
--     2800   2899      2 
--     2900   2999      2 
--     3000   3099      3 
--     3100   3199      1 
--     3200   3299      0 
--     3300   3399      1 
--     3400   3499      1 
```

**Comment by mchaisso** [comment]
The error from meryl is:

merylInput-- segment 1/96 picked reads 0-1 out of 158
ERROR: Estimate of number of kmers (-n) not supplied.

This case happened for asm.ms22.config.{56,64,96}.err.  



-- In sequence store './asm.seqStore':
--   Found 158 reads.
--   Found 1952657 bases (65.08 times coverage).
--
--   Read length histogram (one '*' equals 0.15 reads):
--     1000   1999      7 ********************************************
--     2000   2999      8 **************************************************
--     3000   3999      6 **************************************
--     4000   4999      7 ********************************************
--     5000   5999      9 *********************************************************
--     6000   6999      9 *********************************************************
--     7000   7999      6 **************************************
--     8000   8999      7 ********************************************
--     9000   9999      6 **************************************
--    10000  10999      4 *************************
--    11000  11999     11 **********************************************************************
--    12000  12999      7 ********************************************
--    13000  13999      5 *******************************
--    14000  14999      8 **************************************************
--    15000  15999      7 ********************************************
--    16000  16999      8 **************************************************
--    17000  17999     11 **********************************************************************
--    18000  18999      4 *************************
--    19000  19999      2 ************
--    20000  20999      2 ************
--    21000  21999      7 ********************************************
--    22000  22999      4 *************************
--    23000  23999      4 *************************
--    24000  24999      2 ************
--    25000  25999      2 ************
--    26000  26999      1 ******
--    27000  27999      1 ******
--    28000  28999      0 
--    29000  29999      2 ************
--    30000  30999      1 ******

**Comment by brianwalenz** [comment]
Should be fixed, tested with an assembly of just 4 reads.
