### ISSUE TITLE
nanopore error rate

### ISSUE THREAD

**Issue by igordot** [marbl/canu#109]
By default, using `-nanopore-raw` sets the error rate to 0.05. I recently saw a presentation where they used an error rate of 0.15, which is much higher. How did you decide on 0.05 as the default? Is there anything is the output to help determine this parameter, especially since it will vary for every cell?

**Comment by skoren** [comment]
The error rate is an estimate of residual error after correction and is empirically estimated from recent datasets. This is sufficient to assemble both MAP005 and MAP006 2D data we've tried but if you want to assemble 1D data or have a bad run, it is possible you would need to increase the error rate. You could run with a high error rate (0.1) and look at the distribution of overlap error rates in the unitig step to look for a peak in the distribution. If you have a near neighbor you could also map the corrected reads to it and estimate the residual error that way.

**Comment by igordot** [comment]
Sorry. Where would I find the distribution of overlap error rates in the unitig step? Is that one of the output files or do I need calculate it myself?

**Comment by skoren** [comment]
You'd need to dump the overlap store yourself and compute the distribution using a command like on the unitigging or trimming stores:

```
ovStoreDump -d -b 1 -e 1000 --coords -d5 -d3 -G asm.gkpStore -O asm.ovlStore
```

This will dump overlaps for the first 1000 reads which should be a big enough sample to estimate the distribution. You'd then want to plot a histogram of the last column of the output.

**Comment by igordot** [comment]
I ran it on the E. coli example and the peak was around 0.005, which is somewhat lower than your estimate of 1-2% for MAP006. Should I be concerned or are those just really good reads?

**Comment by skoren** [comment]
Those are better than average reads, you're about 2x better than my estimate (0.5%) but even the four MAP006 samples vary between each other as well.
