### ISSUE TITLE
ovs --memory-per-cpu configuration and canu auto configuration conflict on canu1.6

### ISSUE THREAD

**Issue by imneuro** [marbl/canu#1091]
Hi canu team,

I am using canu-1.6 on AWS cfncluster, with ubuntu16.04 and slurm 16.05.3. I have 13 jobs aborted and 130 jobs killed on Trimming/2-sort steps. The ganglia monitor shows a memory usage spike in a few minutes during this period and then few node with big memory spikes went off line.

In the initial canu configuration as following ovs step requested 32 GB mem and 1 cpu.

> -- Found  10 hosts with  72 cores and  137 GB memory under Slurm control. 
> -- 
> --                     (tag)Threads 
> --            (tag)Memory         | 
> --        (tag)         |         |  algorithm 
> --        -------  ------  --------  ----------------------------- 
> -- Grid:  meryl     68 GB   32 CPUs  (k-mer counting) 
> -- Grid:  cormhap   22 GB   12 CPUs  (overlap detection with mhap) 
> -- Grid:  obtovl    15 GB    8 CPUs  (overlap detection) 
> -- Grid:  utgovl    15 GB    8 CPUs  (overlap detection) 
> -- Grid:  cor       10 GB    4 CPUs  (read correction) 
> -- Grid:  ovb        2 GB    1 CPU   (overlap store bucketizer) 
> -- Grid:  ovs       32 GB    1 CPU   (overlap store sorting) 
> -- Grid:  red       15 GB    8 CPUs  (read error detection) 
> -- Grid:  oea        4 GB    1 CPU   (overlap error adjustment) 
> -- Grid:  bat      137 GB   32 CPUs  (contig construction) 
> -- Grid:  cns       68 GB    8 CPUs  (consensus) 
> -- Grid:  gfa       32 GB   24 CPUs  (GFA alignment and processing) 

Yet, the ovStoreSorter only request 4G of memory 
```
$bin/ovStoreSorter \
  -deletelate \
  -M 4 \
  -O . \
  -G ../LT.gkpStore \
  -F 285 \
  -job $jobid 758
```
and 2-sort.jobSubmit-01.sh requested --memory-per-cput=5g as following:
```
#!/bin/sh
sbatch \
  --mem-per-cpu=5g --cpus-per-task=1 -o logs/2-sort.%A_%a.out \
  -D `pwd` -J "ovS_LT_LT_default" \
  -a 1-285 \
  ./scripts/2-sort.sh 0 \
> ./scripts/2-sort.jobSubmit-01.out 2>&1
```

And config.err shows 4GB per bucket.
```
ubuntu@ip-10-30-2-139:/shared/lettuce/LT/trimming/LT.ovlStore.BUILDING/scripts$ tail /shared/lettuce/LT/trimming/LT.oStore.BUILDING/config.err
  bucket  279 has 125785699 olaps.
  bucket  280 has 125803539 olaps.
  bucket  281 has 125785915 olaps.
  bucket  282 has 125781792 olaps.
  bucket  283 has 125798888 olaps.
  bucket  284 has 125818852 olaps.
  bucket  285 has 119965322 olaps.
Will sort 125.781 million overlaps per bucket, using 285 buckets 4.00 GB per bucket.

-  Saved configuration to './LT.ovlStore.BUILDING/config'.
```

There are 72 cpus and 137G memory on each compute node. According to initial configuration, each ovs jobs should has 1 cpu and 32G memory. Somehow, the config change is to 1 cpu with 4GB memory. Even when sbatch request --mem-per-cpu=5GB, this will bring total memory per node to 360GB.  It seem like the potential reason of memory usage spike.

I don't know what make the configuration changed in the middle, any suggestion to avoid this unexpected configuration change is appreciated. I want to know how to know if the configuration is correctly done. At the same time, is there a way to enforce the initial configuration of memory?

Best,
Xin

**Comment by brianwalenz** [comment]
You've got two issues here.

First, slurm should not be overloading the machine.  Canu told it each job needs one CPU and 5GB memory.  If it ran more than 27 jobs per node (27*5 = 135GB) then the slurm configuration is broken.  There's nothing that Canu can do to resolve this.

Second, the unexpected configuration of overlap jobs.  The initial report from Canu is only the maximum job sizes; each algorithm is free to make smaller jobs.  What's the ovStoreConfig command run - there should be a memory size selection on the command line, something like '-M 8-16'?  What's at the start of config.err (everything up to the 'bucket X has Y overlaps' lines)?

**Comment by imneuro** [comment]
I think of slurm configuration too. I will check with the IT support on slurm configuration.

Hmm, I don't see the ovStoreConfig in the precomiled canu1.6 /opt/canu/bin folder. Here is what I have in the folder:

```
ubuntu@ip-10-30-2-139:/opt/canu/bin$ ls
alignGFA                 fastqSimulate-sort         meryl                   positionDB
bogart                   filterCorrectionOverlaps   mhap-2.1.2.jar          prefixEditDistance-matchLimitGenerate
bogus                    findErrors                 mhapConvert             readConsensus
canu                     findErrors-Dump            mmapConvert             simple
canu.defaults            gatekeeperCreate           overlapConvert          splitReads
correctOverlaps          gatekeeperDumpFASTQ        overlapImport           tgStoreCompress
createFalconSenseInputs  gatekeeperDumpMetaData     overlapInCore           tgStoreCoverageStat
erateEstimate            gatekeeperPartition        overlapInCorePartition  tgStoreDump
errorEstimate            generateCorrectionLayouts  overlapPair             tgStoreFilter
estimate-mer-threshold   leaff                      ovStoreBucketizer       tgStoreLoad
existDB                  lib                        ovStoreBuild            tgTigDisplay
falcon_sense             libcanu.a                  ovStoreDump             trimReads
fastqAnalyze             libleaff.a                 ovStoreIndexer          utgcns
fastqSample              maskMers                   ovStoreSorter
fastqSimulate            merTrim                    ovStoreStats
```
Do you mean the same Canu1.6 version?

In addition, I forgot to mention that the command I used is
```
/opt/canu/bin/canu -p LT -d LT genomeSize=2.5G -pacbio-raw /shared/lettuce/fasta/lettuce.merged.filt2k.fasta gridOptionsJo
bName=LT_default shell='/bin/bash' useGrid=1
```

Here are the start of config.err

> root@ip-10-30-3-147:/var/log# head /shared/lettuce/LT/trimming/LT.ovlStore.BUILDING/config.err
> Attempting to increase maximum allowed processes and open files.
>   Max processes per user limited to 563048, no increase possible.
>   Changed max open files from 1024 to 51200 (max 51200).
> 
> Found 35847678040 (35847.68 million) overlaps.
> Configuring for 4.00 GB to 32.00 GB memory and 51184 open files.
> Will sort using 285 files; 125829120 (125.83 million) overlaps per bucket; 4.00 GB memory per bucket
>   bucket    1 has 125791868 olaps.
>   bucket    2 has 125821867 olaps.

**Comment by skoren** [comment]
The configuration looks correct @brianwalenz said, it has a range from 4-32 and it picked 4 because you still end up with only about 300 buckets that way. No reason to commit more memory. 

SLURM should've reserved 5gb memory/per job so you wouldn't end up with >300GB on a node. If it isn't properly reserving memory, you can use threads to force it to limit the jobs per machine. Since you have 72 cores and 137gb of memory per machine, you can fit at most 27 jobs. If you reserve 3 cores that will enforce the limit. Add the option ```gridOptionsovs="----mem=5g --cpus-per-task=3"``` to your Canu command and re-launch. That should limit it to 24 jobs (72/3).

**Comment by brianwalenz** [comment]
Canu option ovsThreads=3 should work too.  I'd choose 4 for a bit of safety.

**Comment by imneuro** [comment]
@skoren @brianwalenz  Your suggestion are really helpful! Shall I remove all the failed 2-sort.*.out in the log folder and then add the option to rerun the command? 

In addition, for some reason on cfncluster, each compute node the S:C:T is setup as 72:1:1 even through the real situation is 2:18:2. Before IT found a solution for that, would `gridOptionsovs="--mem=5g --ovsThreads=3"`  works better than `gridOptionsovs="--mem=5g --cpus-per-task=3"` ? 

For the other genome I need to assemble, shall I just add the option into command line according to the initial configuration before we find good solutions for both cfncluster and slurm configuration? Any suggestion on that?

**Comment by skoren** [comment]
1. Shall I remove all the failed 2-sort.*.out in the log folder and then add the option to rerun the command?

Doesn't matter, safer to clean up so you know which error logs are new and which are old 

2. Before IT found a solution for that, would gridOptionsovs="--mem=5g --ovsThreads=3" works better than gridOptionsovs="--mem=5g --cpus-per-task=3" ?

The two are separate options. Use either ovsThreads=3 or gridOptionsovs="--mem=5g --cpus-per-task=3", the two should be interchangeable. 

3. For the other genome I need to assemble, shall I just add the option into command line according to the initial configuration before we find good solutions for both cfncluster and slurm configuration?

Yes, you can also add it to the canu.defaults file in the canu Linux-amd64/bin folder. That will add the options to all canu jobs run on the grid.

**Comment by imneuro** [comment]
@skoren @brianwalenz  With your suggestion, I  safely get through most of the buckets, except that 5 jobs failed with 2 attempts.

```
-- Overlap store sorting jobs failed, tried 2 times, giving up.
--   job trimming/LT.ovlStore.BUILDING/0011 FAILED.
--   job trimming/LT.ovlStore.BUILDING/0063 FAILED.
--   job trimming/LT.ovlStore.BUILDING/0076 FAILED.
--   job trimming/LT.ovlStore.BUILDING/0179 FAILED.
--   job trimming/LT.ovlStore.BUILDING/0199 FAILED.


::::::::::::::
2-sort.4350_199.out
::::::::::::::
Running job 199 based on SLURM_ARRAY_TASK_ID=199 and offset=0.

Attempting to increase maximum allowed processes and open files.
  Max processes per user limited to 563048, no increase possible.
  Changed max open files from 1024 to 51200 (max 51200).

Job 199 is finished (remove './0199' or -force to try again).
```

Without more details why these 5 jobs failed, do you have any suggestion on how to give them another try? 

I am also curious what are the possible reasons for sorting to fail. If there are anything on sequence input or computational environment that we can improve on our end, I would like to know.

**Comment by skoren** [comment]
When the sorting jobs fail, it is usually due to file system corruption. That would imply your FS can't handle the concurrent writes from the multiple sort jobs. The corruption could be in the bucket jobs up-front of the sort step. 

The error message is indicating there is already partial output from the failed jobs. Check if there are files named ```slice*199``` in the ```bucket*``` folders (```ls bucket*/slice*199```). If so, you can remove the files named ./0199 and re-run the sort job by hand to see what it reports.

**Comment by imneuro** [comment]
Four of them are good where I run

 ` sbatch --mem=5g --cpus-per-task=4 -o logs/2-sort.%A_%a.out  -D `pwd` -J "ovS_LT_LT_default"  -a 199-199  ./scripts/2-sort.sh 0 > ./scripts/2-sort.jobSubmit-01.out 2>&1
`

One of them is generate 0 output where I used the command in 2-sort.jobSubmit-01.sh
```
sbatch \
  --mem-per-cpu=5g --cpus-per-task=1 --mem=5g --cpus-per-task=4 -o logs/2-sort.%A_%a.out \
  -D `pwd` -J "ovS_LT_LT_default" \
  -a 11-11 \
  ./scripts/2-sort.sh 0 \
> ./scripts/2-sort.jobSubmit-01.out 2>&1
```

Are both `--mem-per-cpu=5g --cpus-per-task=1` and `--mem=5g --cpus-per-task=4` exists in the 2-sort.jobSubmit-01.sh are what I should expected after I put `--mem=5g --cpus-per-task=4` on the initial command line?

I am ok to let this one job go for this case. As you mention the file system corruption, if it is ok for you, I would like to know limits of your file system or to the file system assemble a human genome, such as maximum name length, max size of a single file, max directory depth,  limit on file locks, limit of  number of file system operations per second....

**Comment by skoren** [comment]
What do you mean 0 output? The corresponding file is empty from the sort? That implies it had previously run and had already removed the input slice files. Do you have the corresponding slice files (```ls bucket*/slice*011```)? You can continue on but you'll lose a bunch of overlaps supporting reads so some data may be over-trimmed due to this. It may be better to remove the BUILDING folder and re-start canu with the added memory option and a limit on concurrent jobs (see below) to let it load all the overlaps for the store.

We use NFS mounted Isilon x410s as well as a GPFS and both handle multiple concurrent human runs without issue. You can always limit the maximum number of jobs running concurrently which will mean less load on the filesystem by adding ```gridEngineArrayOption="-a ARRAY_JOBS%50"``` which will limit arrays to 50 jobs at a time.

**Comment by imneuro** [comment]
You are right about the butcket*/slice*011. I end up remove the BUILDING folde and re-start canu with limit on memory and cpu request to decrease the job number. 

The output assembled vegetable contigs are very fragmented with nearly 27000 contigs for 2.2GB genome (targeted 2.5GB genome). I wonder if I had other steps have data losted due to the concurrent jobs. As canu1.6 removes all the scripts, logs and temporary data. I want to look into more about our system and I heard Canu1.5 kept all the scripts. I would like to get your suggestion on pro and cons to use Canu1.5 vs. Canu1.6.

**Comment by skoren** [comment]
You can keep all the logs and output in any version if you want but I wouldn't expect you'd easily be able to figure out if data was lost from them anyway. If you're going to change versions update to 1.7.1. 

Your assembly report should have more info on what may have impacted the assembly. It could also be that your genome is very repetitive and there aren't enough long reads to resolve most of them. You can also look at the FAQ for suggested parameters for improving assembly continuity.

**Comment by imneuro** [comment]
Thank you for your help. May be this how it is. This genome has very high repeat percentage. This is the best we can do so far.
