### ISSUE TITLE
Restart from unitigging/1-overlapper/

### ISSUE THREAD

**Issue by peritob** [marbl/canu#1095]
I have am running the last steps of assembly using canu v1.6. within PBS-pro grid environment.

I ran into a problem (identified previously) in unitigging/3-overlapErrorAdjustment with the script submitting two batches of jobs: 1-1000 and 1-209.

I killed the jobs and rewrote the scripts to correct as 1-1000 and 1001-1209. Here is where I really made an error. I deleted the completed 'red' jobs within the folder and restarted canu but I am not able to proceed.

I have kept the ovb files within unitigging/1-overlapper/001/
I would like to start from this step again. These files and folders are present within unitigging/
0-mercounts   3-overlapErrorAdjustment  MR.gkpStore.err  MR.ovlStore               MR.ovlStore.summary
1-overlapper  MR.gkpStore         M.gkpStore.gkp  M.ovlStore.per-read.log

Can you please advise - feeling very foolish...

**Comment by skoren** [comment]
There are two steps that run in the 3-overlapErrorAdjustment folder, red.sh and oea.sh. Which did you run by hand and which files did you remove? If it was red.sh and you removed filed name ```*.red``` then essentially it's as if the step didn't run.

The easiest way to restart is to remove the 3-overlapErrorAdjustment folder completely and re-launch canu with the option ```gridEngineArrayMaxJobs=9999```, this should prevent it from having jobs 1-1000 and 1-209 (which as far as I know works correctly in the latest release on PBS) and make a single large array job of 1209 jobs (assuming your grid will let you do this).
