### ISSUE TITLE
What are the meanings of bogart's parameters

### ISSUE THREAD

**Issue by luyang93** [marbl/canu#1096]
What are the meanings of these parameters batoptions
Unitigger-bogart
batOptions <unset> Advanced options to bogart

corOutCoverage=200 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50"

**Comment by skoren** [comment]
These are documented if you run the bogart command itself. The first two (dg/db) decrease the deviation of error rate for the automatic threshold so it means a lower error rate limit will be used to better separate haplotypes. The last three parameters affect mis-assembly breaking. If there is ambiguity in a contig, the selected overlap has to be at least 500 bases or 5 times longer  than the next best option. You can see these parameters described in issue #190
