### ISSUE TITLE
running Canu on AWS Batch || ECS

### ISSUE THREAD

**Issue by edxxgardo** [marbl/canu#1099]
Hello,
Is there any chance to run Canu on AWS Batch or AWS ECS services? Instead of selecting a specific Amazon EC2 type, it would be awesome to run Canu, i.e. on AWS Batch, so it assign jobs like in a grid-like architecture and in doing so we can save some money ;). Any feedback would be appreciated. Thanks in advance.

**Comment by brianwalenz** [comment]
More than happy to help you (or anyone else) understand what Canu needs to run and how it runs jobs and checks that the result are complete.  We lack resources (developer time) and any experience with AWS Batch to do much more than give occasional advice.

**Comment by skoren** [comment]
I'll add that Canu is capable of running on non-shared file systems and has an interface to fetch data as needed. This is how it runs on DNANexus. Take a look at ```src/pipelines/canu/Grid_DNANexus.pm``` and ```src/pipelines/canu/Grid_Cloud.pm```. You'd want to modify those to add another cloud environment (AWS). 

You need to find ways to query available nodes, copy data to/from the node, request a compute node given a shell script to run, and a way to wait for a job to complete. As @brianwalenz said, we don't have access to AWS for testing and don't have much experience but if you want to add the support we can incorporate it into the assembler.
