### ISSUE TITLE
Abort error on large overlap store

### ISSUE THREAD

**Issue by skoren** [marbl/canu#11]
With very large overlap stores (>20TB), overlap store stats and generateCorrectionLayouts crashes with an assertion of:

```
generateCorrectionLayouts: stores/ovStore.C:379: uint32 ovStore::readOverlaps(ovOverlap*, uint32, bool): Assertion `_offt._numOlaps <= maxOverlaps' failed.
```

**Comment by brianwalenz** [comment]
Fixed in 16bd85e438572daf717c28a9098bd0d20728801d.
