### ISSUE TITLE
Issue installing canu 1.7.1 to Ubuntu ver 18

### ISSUE THREAD

**Issue by newcanu** [marbl/canu#1107]
I would like to preface by saying that I am new to linux so it's entirely possible I made a mistake during the installation process. 

I am trying to install canu onto a machine running ubuntu ver18, and I think it installed correctly but when I type the command to launch canu I am told that it cannot be found.

This was my process for installing canu:

1. Download "Source code (tar.gz)"
2. Use gunzip -dc canu-v1.7.1.tar.gz | tar -xf - to unzip the file
3. I moved canu-1.7.1 out of downloads to another directory
4. I used cd canu-1.7.1/src
5. I then typed make -j 8

Below is the beginning and end of the script which was generated after I executed the command:

First few lines:

WARNING:
WARNING: GCC 7 detected, disabling stack trace support.  Please upgrade to GCC 4.7 or higher.
WARNING:
Building for 'Linux' '4.15.0-36-generic' as 'amd64' into '/minion/software/canu-1.7.1/Linux-amd64/{bin,obj}'
CC  cc 7
CXX g++ 7

Last few lines:

/tmp/ccfd36Pp.s: Assembler messages:
/tmp/ccfd36Pp.s:75749: Internal error (Segmentation fault).
Please report this bug.
Makefile:659: recipe for target '/minion/software/canu-1.7.1/Linux-amd64/obj/bin/bogart/bogart/AS_BAT_MarkRepeatReads.o' failed
make: *** [/minion/software/canu-1.7.1/Linux-amd64/obj/bin/bogart/bogart/AS_BAT_MarkRepeatReads.o] Error 1

Is this a successful install? I moved into the canu-1.7.1 directory and typed:

canu-1.7.1/*/bin/canu

However I just get a message saying that no such file or directory exists.

**Comment by skoren** [comment]
That looks like your GCC compiler crashed while compiling, your gcc installation may be broken.

You don't really need to compile though, try downloading and running the pre-compiled Linux binary and see if it works on your system.
