### ISSUE TITLE
canu Failed to submit batch jobs

### ISSUE THREAD

**Issue by mawad89** [marbl/canu#1109]
I work in lsf platform to assemble bacterial genome using like this command
**canu -p aw -d ddff  genomeSize=6m gnuplotTested=true -pacbio-raw /bath/ to/fastq**

but the following error appear   
 ` 

BEGIN CORRECTION
--
--
-- Running jobs.  First attempt out of 2.
--

CRASH:
CRASH: Canu 1.6
CRASH: Please panic, this is abnormal.
ABORT:
CRASH:   Failed to submit batch jobs.
CRASH:
CRASH: Failed at /opt/share/software/packages/canu-1.6/bin/lib/canu/Execution.pm line 1119.
CRASH:         canu::Execution::submitOrRunParallelJob("awad", "cormhap", "correction/1-overlapper", "precompute", 1, 2) called at /opt/share/software/packages/canu-1.6/bin/lib/canu/OverlapMhap.pm line 661
CRASH:         canu::OverlapMhap::mhapPrecomputeCheck("awad", "cor", "partial") called at /opt/share/software/packages/canu-1.6/bin/canu line 621
CRASH:         main::overlap("awad", "cor") called at /opt/share/software/packages/canu-1.6/bin/canu line 666
CRASH:
CRASH: Last 50 lines of the relevant log file (correction/1-overlapper/precompute.jobSubmit-01.out):
CRASH:
CRASH:`

I trying to use 
gridEngineThreadsOption="-pe make THREADS"
 gridEngineThreadsOption="-pe make-dedicated THREADS"
gridEngineThreadsOption="-pe mpich-rr THREADS"
gridEngineMemoryOption="-l h_vmem=MEMORY -l mem_free=MEMORY"
But no way the problem still appear

**Comment by skoren** [comment]
Your grid engine options look like SGE options not LSF. What is the Canu preamble (what grid it detected, resources)? What is the error reported in ```correction/1-overlapper/precompute.jobSubmit-01.out```?

**Comment by mawad89** [comment]
Dear Skoren 
Thanks very much for your replay 
**precompute.jobSubmit-01.out** containing the following error

> 

bsub: illigal option --l
usage:bsub [-X] etc.... 

bsub [-h] [-V]

>

**Comment by mawad89** [comment]
I don't know exactly where is the error I resubmit it today many times and precompute.jobSubmit-01.out containing the following error

> Too many processors requested, JOB  NOT SUBMITTED  

>

**Comment by brianwalenz** [comment]
The Canu `gridOptions` simply pass those values to the command used to submit jobs to the grid, `bsub` in your case.  The options you've listed are compatible with SGE, not LSF, and so `bsub` fails.  I don't know what appropriate LSF options are.

What does Canu report when you run without any of gridOptions specified -- why are you specifying gridOptions at all?

On SGE, the report looks like:
```
-- Detected Java(TM) Runtime Environment '1.8.0_162' (from 'java') with -d64 support.
-- Detected gnuplot version '5.2 patchlevel 2   ' (from 'gnuplot') and image format 'png'.
-- Detected 24 CPUs and 128 gigabytes of memory.
-- Detected Sun Grid Engine in '/usr/local/sge/bpwi'.
-- Detected Grid Engine environment 'thread'.
-- Detected Grid Engine consumable 'memory'.
-- 
-- Found   1 host  with   6 cores and   15 GB memory under Sun Grid Engine control.
-- Found   1 host  with  12 cores and   62 GB memory under Sun Grid Engine control.
-- Found  48 hosts with  24 cores and  124 GB memory under Sun Grid Engine control.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl     31 GB    6 CPUs  (k-mer counting)
-- Grid:  cormhap   48 GB   12 CPUs  (overlap detection with mhap)
-- Grid:  obtovl     8 GB    6 CPUs  (overlap detection)
-- Grid:  utgovl     8 GB    6 CPUs  (overlap detection)
-- Grid:  ovb        4 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs        8 GB    1 CPU   (overlap store sorting)
-- Grid:  red       10 GB    6 CPUs  (read error detection)
-- Grid:  oea        4 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat       64 GB    8 CPUs  (contig construction with bogart)
-- Grid:  gfa        8 GB    8 CPUs  (GFA alignment and processing)
```

**Comment by mawad89** [comment]
In my first run I don't use any grid options but the error appeared so I trying with different grid options

**This is the canu configuration without any grid options**
<pre><code> 
-- Detected Java(TM) Runtime Environment '1.8.0_181' (from 'java').
-- Detected 128 CPUs and 1008 gigabytes of memory.
-- Detected LSF with 'bsub' binary in /opt/lsf/8.3/linux2.6-glibc2.3-x86_64/bin/bsub.
-- Warning: unknown memory units for grid engine LSF assuming KB
-- 
-- Found   6 hosts with 128 cores and 1008 GB memory under LSF control.
-- Found   1 host  with   8 cores and   16 GB memory under LSF control.
-- 
-- On LSF detected memory is requested in KB
-- 
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl      8 GB    4 CPUs  (k-mer counting)
-- Grid:  cormhap    6 GB    8 CPUs  (overlap detection with mhap)
-- Grid:  obtovl     8 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl     8 GB    8 CPUs  (overlap detection)
-- Grid:  cor        8 GB    2 CPUs  (read correction)
-- Grid:  ovb        2 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs        8 GB    1 CPU   (overlap store sorting)
-- Grid:  red        2 GB    4 CPUs  (read error detection)
-- Grid:  oea        1 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat        8 GB    4 CPUs  (contig construction)
-- Grid:  cns        8 GB    4 CPUs  (consensus)
-- Grid:  gfa        8 GB    4 CPUs  (GFA alignment and processing)
</code></pre>

 **and this is also the precompute.jobSubmit-01.out error**
<pre><code>
 Too many processors requested, JOB NOT SUBMITTED
</code></pre>

**Comment by brianwalenz** [comment]
That's saying that the mhap 'precompute' jobs (cormhap in the table) are going to request 8 CPUs and 6GB memory for the jobs.  But LSF is refusing to run those claiming the 'too many processors' error.  Unfortunately, there is some site-specific magic you need to supply to bsub to make the request work -- so you're correct is using the gridOptions, we just need to figure out what bsub options to list there.  For that you'll have to ask around at your site (help desk, other users) to learn how to get jobs that want to use multiple processors on the same node.

If possible, upgrade to Canu release 1.7.1.  There's nothing in there that should fix your current problem, but lots that will fix problems you might encounter later.  It's safest if you start the assembly over when upgrading Canu.

**Comment by skoren** [comment]
Idle, site specific grid options required, no code to fix.
