### ISSUE TITLE
Keep quality score when correcting with Canu assembler? 

### ISSUE THREAD

**Issue by lguzmanz** [marbl/canu#111]
I am using Canu assembler to do a de novo assembly of PacBio data. I noticed that when I corrected my reads it produced a .fasta not a .fastq file, therefore loosing the quality score data of my original raw PacBio reads. Is there any parameter or option I can add so that the quality score is not lost when issuing the "canu -correct" command? Thank you! 

P.S. I am trying to pipe the corrected reads to MIRA and MIRA requires quality scores when I run it on Geneious.

**Comment by brianwalenz** [comment]
Nope, no option to do this.

The correction process generates a consensus sequence for the reads, and the QV isn't informative after that.  Besides, the algorithm doesn't generate a QV.

I'd suggest making up fastq with a qv between 20 and 30 for all bases.

**Comment by zhuzhuo** [comment]
A follow-up question, since there is not quality score for the consensus sequence, how do I evaluate the "quality" of the consensus sequence for de novo sequencing? 
Thanks!
