### ISSUE TITLE
executiveMemory option not recognised?

### ISSUE THREAD

**Issue by mcshane** [marbl/canu#1110]
Using canu 1.7.1, and trying to set `executiveMemory=10`, but run into the following error:
```
ERROR:  Parameter 'executiveMemory' is not known.
```
Maybe not part of the 1.7.1 release? Although looking back at the commit the option was added to the documentation, it looks like it should be there...

**Comment by skoren** [comment]
This option was added as part of DNA nexus support post the 1.7 release so it will be in the next release. In the meantime, you can change what Canu requests from the grid with the gridOptionsExecutive parameter.
