### ISSUE TITLE
Unknown Error causing canu to stop

### ISSUE THREAD

**Issue by bruce-boles** [marbl/canu#1114]
Hello,
I have tried to correct my data, but canu seems to be stopping prematurely. My system is Ubuntu 18. I am working on canu 1.7.1. The program seems to initiate and gets to the following point:
```
-- Finished on Tue Oct 16 11:50:35 2018 (lickety-split) with 1656.78 GB free disk space
----------------------------------------
--
-- Mhap precompute jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/blocks/000001.dat FAILED.
--   job correction/1-overlapper/blocks/000002.dat FAILED.
--   job correction/1-overlapper/blocks/000003.dat FAILED.
--   job correction/1-overlapper/blocks/000004.dat FAILED.
```

but then it says:

```
ABORT:
ABORT: Canu 1.7.1
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```

My input to the program is the folllowing:

```
*/bin/canu -correct -d /home/bruceboles/Projects/canuoutput -p canu_correction genomeSize=5.2m -nanopore-raw /home/bruceboles/Projects/RawData/Nanopore/Shew_albacore_processing3/workspace/pass/*.fastq
```
Thanks for the help,

Bruce Boles

**Comment by skoren** [comment]
Most likely related to #1108 or #1064. Check the log from the precompute job to see the exact error.

**Comment by bruce-boles** [comment]
Here is the error in that file: ```Error: Unable to access jarfile /usr/lib/canu/mhap.jar
Mhap failed.```

**Comment by skoren** [comment]
That's the same error as #1064 and #1055, you've got a partial canu installation, whatever package manager installed Canu is broken. Install Canu by downloading it from the releases page, there is a pre-compiled linux binary.

**Comment by skoren** [comment]
Incomplete installation, nothing to fix within canu.
