### ISSUE TITLE
Canu install problems

### ISSUE THREAD

**Issue by newcanu** [marbl/canu#1115]
Hi I have tried installing canu on Ubuntu 16.04 using both the binary and source code. Using both methods I get the same result (below):

sudo xz -dc home/armeganalysis/Downloads/canu-1.7.1.Linux-amd64.tar.xz |tar -xf - 
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin: Cannot mkdir: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/alignGFA: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/bogart: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/bogus: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/canu: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/canu.defaults: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/correctOverlaps: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/createFalconSenseInputs: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/dumpBlob: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/edalign: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/erateEstimate: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/errorEstimate: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/estimate-mer-threshold: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/existDB: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/falcon_sense: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/falconsense: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/fastqAnalyze: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/fastqSample: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/fastqSimulate: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/fastqSimulate-sort: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/filterCorrectionLayouts: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/filterCorrectionOverlaps: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/findErrors: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/findErrors-Dump: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/gatekeeperCreate: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/gatekeeperDumpFASTQ: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/gatekeeperDumpMetaData: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/gatekeeperPartition: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/generateCorrectionLayouts: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/leaff: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/loadCorrectedReads: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/loadTrimmedReads: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/maskMers: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/merTrim: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/meryl: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/mhapConvert: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/mmapConvert: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/overlapConvert: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/overlapImport: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/overlapInCore: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/overlapInCorePartition: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/overlapPair: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/ovStoreBucketizer: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/ovStoreBuild: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/ovStoreDump: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/ovStoreIndexer: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/ovStoreSorter: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/ovStoreStats: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/positionDB: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: canu-1.7.1/Linux-amd64/bin/prefixEditDistance-matchLimitGenerate: Cannot open: No such file or directory
tar: canu-1.7.1: Cannot mkdir: Permission denied
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
 
Any advice to complete the install?

**Comment by brianwalenz** [comment]
It appears you're installing in the root directory, and its not letting you make files or directories there.  Good!  That's entirely the wrong place to install it.

Try installing in your home directory.  No need to use sudo.

The "Unexpected EOF in archive" might be indicating your download is incomplete.

**Comment by newcanu** [comment]
Thanks Brain Canu installed immediately within home.
