### ISSUE TITLE
documentation/source/tutorial.rst: comment on <prefix>.contigs.gfa is unclear

### ISSUE THREAD

**Issue by kortschak** [marbl/canu#1116]
In the GRAPHS section of the [tutorial](https://github.com/marbl/canu/blob/master/documentation/source/tutorial.rst#outputs) the caveat on \<prefix\>.contigs.gfa regarding bubble edges is unclear. Nowhere is the notion of a bubble edge defined to contrast it with any other kind of edge/path. The GFA spec does not define this concept either. So it would be useful to elaborate on this.

>\<prefix\>.contigs.gfa
>    Unused or ambiguous edges between contig sequences. **Bubble edges cannot be represented in this format.**

**Comment by skoren** [comment]
See the discussion of edges on the GFA2 page: https://github.com/GFA-spec/GFA-spec/blob/master/GFA2.md

The GFA format can capture dovetail or contain overlaps but not general edges in the figure on that page where part of each contig overlaps. This is what the readme is referring to. We output unitigs and unitig edges instead which break at these types of intersections to be compatible with gfa.

**Comment by kortschak** [comment]
Maybe elaborate in the comment at the page I link to then. I'm not asking a question here but raising a defect in the documentation.

**Comment by skoren** [comment]
Added more info to docs
