### ISSUE TITLE
Mhap precompute jobs failed, tried 2 times, giving up.

### ISSUE THREAD

**Issue by impreza-92** [marbl/canu#1117]
Hey, 

I am having issues with running canu on the lambda phage control genome form Nanopore. For some reason it seems to fail everytime.
System: Xubuntu, 16 cores, 64gb RAM

The command I use:

canu -d test -p test genomeSize=49k -nanopore-raw ./GA40000/merged_GA40000.fastq  merylMemory=32 merylThreads=16 cnsMemory=32 cnsThreads=16

Error (Canu v1.6):

Mhap precompute jobs failed, tried 2 times, giving up.

Could you elaborate on how to get Canu working? I have not yet been able to complete a run.

**Comment by skoren** [comment]
Idle, nothing to fix in Canu, likely an issue with invalid package installation.
