### ISSUE TITLE
Can I assemble a very large genome using Canu?

### ISSUE THREAD

**Issue by okokookk** [marbl/canu#1120]
The genome size is estimated at about 20G.
Can I assemble this genome with Canu using long reads (PacBio or nanopore)?
The depth to be used is about 30 to 60X.
Is there any possibility of problems with memory etc.?
Is there a limit to the size of the genome or the amount of reads used to assemble the genome using canu?

**Comment by skoren** [comment]
Memory is not so much an issue as disk space. There is no practical limit on the number of reads or genome size. I'd recommend having 50-100tb if possible. Definitely look at the FAQ page to reduce runtime and disk usage and get a trio if you can to simplify the assembly.

**Comment by skoren** [comment]
Idle.
