### ISSUE TITLE
-fast option is undocumented

### ISSUE THREAD

**Issue by johnomics** [marbl/canu#1122]
The -fast option mentioned in the [version 1.8 release notes](https://github.com/marbl/canu/releases/tag/v1.8) does not appear to be documented in the QuickStart, FAQ or Tutorial, and does not appear in the 'canu -options' output or the usage message. Please could you add this?

Also, it looks from the [code](
https://github.com/marbl/canu/commit/5defa9e261ee49aa7f22d3e21c8a5e0d3d025e81) like canu will use wtdbg-1.2.8 for unitigging if it is installed - is there a way to get canu to add this at compile time, or do we need to manually copy this to the bin directory? (I see wtdbgConvert in the bin directory, but not wtdbg-1.2.8 itself).

Thanks,
John

**Comment by johnomics** [comment]
Another question about this, sorry. Fast mode is recommended for nanopore assemblies under 1 GB in size. What drives the limitation? Number of unique kmers, or repeat content, or...? We're wondering about using it for metagenomes, whether the genomes won't be repetitive, but the total genome size might be large.

**Comment by skoren** [comment]
I added a description of fast to the options page. It can be used on any size genome, it just may generate a less continuous assembly than the defaults. Metagenomes would probably be OK.

I don't recommend the wtdbg option as it hasn't been tested on anything but small bacteria.

**Comment by johnomics** [comment]
Thank you very much! (Very minor note on wtdbg - the fast [code](https://github.com/marbl/canu/blob/5defa9e261ee49aa7f22d3e21c8a5e0d3d025e81/src/pipelines/canu.pl#L136) will only check for the wtdbg-1.2.8 binary, but the wtdbg binary is now wtdbg2, and wtdbg-1.2.8 appears to be unavailable. So copying the wtdbg2 binary to the bin directory as suggested by https://github.com/marbl/canu/commit/c72909a529f4966603b53571e7fc67fef5a39464 will not work.)
