### ISSUE TITLE
Canu analysis error

### ISSUE THREAD

**Issue by yl010** [marbl/canu#1124]
Hi, 

I have a nanopore fastq data.
I filtered out the short reads using 
awk 'NR%4==1{a=$0} NR%4==2{b=$0} NR%4==3{c=$0} NR%4==0&&length(b)>5000{print a"\n"b"\n"c"\n"$0;}' 15407_0.fastq > 15407_0_5k.fastq

Then ran canu
sudo /Everythings/tools/canu/Linux-amd64/bin/canu -p 15407 -d ./ genomeSize=16.5k -nanopore-raw 15407_0_5k.fastq

Came back with error
-- ERROR:  Read coverage (1.36) is too low to be useful.
-- ERROR:
-- ERROR:  This could be caused by an incorrect genomeSize or poor quality reads that could not
-- ERROR:  be sufficiently corrected.
-- ERROR:
-- ERROR:  You can force Canu to continue by decreasing parameter stopOnLowCoverage=10,
-- ERROR:  however, the quality of corrected reads and/or contiguity of contigs will be poor.

I tried to follow the suggestion 
sudo /Everythings/tools/canu/Linux-amd64/bin/canu -p 15407 -d ./ genomeSize=16.5k stopOnLowCcoverage=10 -nanopore-raw 15407_0_5k.fastq

Came back with
ERROR:  Parameter 'stopOnLowCcoverage' is not known.

Is there another way that could bypass the coverage problem?

Thank you for your help

**Comment by skoren** [comment]
This isn't an error but a warning that you have insufficient coverage to do anything useful. Double-check your fastq file, how many reads do you have in it and how much coverage is that for a 16kb sequence?

You mis-spelled the option (stopOnLowCcoverage should be stopOnLowCoverage) and you need to set it below your limit to continue (e.g. 1 in your case) but this isn't going to do anything useful if you really have 1-fold coverage of your sequence.

**Comment by yl010** [comment]
Hi

Thanks for the response
I thought it was the low coverage causing the abortion of Canu

ABORT:
ABORT: Canu snapshot (snapshot)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:

Does that mean something else is wrong?
Thanks

**Comment by brianwalenz** [comment]
There should be something immediately before that text.  Don't be shy about posting too much logging!

As small as this is, remove the old run and restart from scratch.  Use the original unfiltered reads, since you don't seem to have enough coverage in reads > 5 Kbp -- option minReadLength=5000 would do the same filtering you did (but don't do that).  Canu ignores reads below 1000 by default.

**Comment by skoren** [comment]
Any updates on this?

**Comment by skoren** [comment]
Idle, closing.
