### ISSUE TITLE
Parameter issue/question

### ISSUE THREAD

**Issue by kfriesen2** [marbl/canu#1126]
I tried out version 1.8.0_121 on slurm today, with 44x of sequel data. I used the following command:

canu \
gridOptionsExecutive="--partition=mem --mem-per-cpu=24g --time=7-00:00:00" \
correctedErrorRate=0.085 ovlMerThreshold=500 \
gridOptionsmeryl="--partition=mem" \
'stageDirectory=$TMPDIR' \
gridOptionsCOR="--partition=mem --time=7-00:00:00" gridOptions="--time=48:00:00" \
-p sp1_ceres_canu18 -d sp1_ceres_canu18 genomesize=2150m \
-pacbio-raw /project/insect_gen/species1/reads/*.fastq

But it gave me these errors:

ERROR:  Invalid 'obtOvlErrorRate' specified (0.085 ovlMerThreshold=500); must be numeric
ERROR:  Invalid 'utgOvlErrorRate' specified (0.085 ovlMerThreshold=500); must be numeric
ERROR:  Invalid 'obtErrorRate' specified (0.085 ovlMerThreshold=500); must be numeric
ERROR:  Invalid 'utgErrorRate' specified (0.085 ovlMerThreshold=500); must be numeric
ERROR:  Invalid 'cnsErrorRate' specified (0.085 ovlMerThreshold=500); must be numeric

It did run after I removed ovlMerThreshold=500. I though maybe it was a case issue, since it varied from the options list. But then others had different case, and were processed.

Can you help me undertand what the issue was? (I hope it's not too obvious.) Thanks.

**Comment by skoren** [comment]
Idle, cannot reproduce locally.
