### ISSUE TITLE
Canu Paramter version

### ISSUE THREAD

**Issue by zachcp** [marbl/canu#1129]
Team Canu,

Than you for this  new release.  

A small issue: it seems that canu1.8 no longer has the `gnuplotTested` option.  I noticed it after upgrading to 1.8.  Previously I had added this to all of my scripts as a defense against gnuplot failure. So I am glad you no longer need it but you may want to mention that options have changed.

Kind Regards,
zach cp

**Comment by brianwalenz** [comment]
Thanks!  I've updated the release notes.
