### ISSUE TITLE
How to submit  a PBS msub job?

### ISSUE THREAD

**Issue by wisekh6** [marbl/canu#113]
Hello,

According to the tutorial, canu may also support PBS "msub".
But, I don't know how to set up gridOptions.
Would you please advice?

FYI: Our PBS header includes:
#PBS -N anystring
#PBS -l nodes=1:ppn=24,walltime=24:00:00
#PBS -l mem=128gb
#PBS -M email@gmail.com
#PBS -m abe
#PBS -d anydirectory
#PBS -o anydirectory/logs
#PBS -e anydirectory/logs
#PBS -V
canu -options

Thank you so much,

Hoon

**Comment by skoren** [comment]
Canu supports PBS/Torque through qsub. It will auto-detect you're on PBS and switch to PBS-style submit commands. There is no support for msub. Does your system support using qsub, it should on PBS. 

You don't need most of your PBS header. Canu submits other jobs and will specify job names,  name/memory/nodes, and inputs/outputs based on what it needs. If you want it to maintain the other options you can add them through gridOptions:
```
gridOptionsJobName="canuRun1" gridOptions="-M email@gmail.com -m abe -V"
```

**Comment by wisekh6** [comment]
Thank you very much for your quick response.
Unfortunately, our system only supports msub; qsub was depreciated.
And, we don't use, for example, '-q long' option any more, and our system requires me to strictly follow the following header format:
-------
#PBS -N anystring
#PBS -l nodes=1:ppn=24,walltime=24:00:00
#PBS -l mem=128gb
#PBS -M email@gmail.com
#PBS -m abe
#PBS -d anydirectory
#PBS -o anydirectory/logs
#PBS -e anydirectory/logs
#PBS -V
-----

Is there any workaround?

Thank you in advance,

Hoon

**Comment by skoren** [comment]
Canu submits jobs as it runs using dynamically generated shell scripts and is designed to request resources on the command line. Unless you edit the code to write the header there is no other workaround since the resources vary from job to job. You'd also have to change qsub to msub, assuming it supports the same syntax in pipelines/canu/Grid_PBSTorque.pm.

Your other option would be to submit the canu job to the grid and have it run on a single node using the useGrid=0 option.

**Comment by wisekh6** [comment]
Appreciating for your direction. I will talk with my bioinformatics team about your suggestion.

May I ask one more?
I have been working on PacBio sequencing from human.
If I assume I run the job on a single node (with, for example, 100Gb), how long do you expect it will take? I am afraid it won't be finished in a week. Is it correct?

Thank you very much,

Hoon

**Comment by skoren** [comment]
No it won't. It takes about 5k cpu hours to generate corrected reads and about 20k to finish the assembly. So assuming 64 cores that would be >2 weeks. So you're probably looking at 3-6 weeks or longer, depending on your compute hardware.

I would suggest asking for an exception to the header option since the jobs would still specify the resources they need, just not in a header block. It should really not matter to the scheduler how they're specified.

**Comment by wisekh6** [comment]
Thank you very much for your advice.
Very helpful!!!

HK

**Comment by wisekh6** [comment]
Dear Sergey, 

I tried to test in a different cluster computer which supports PBS qsub.
I run the following script:
canu -p ecoli -d ecoli-auto genomeSize=4.8m -pacbio-raw p6.25x.fastq

However, as shown below, my command looks like not recognizing PBS system in my cluster.
I wonder if you know how to solve out this issue.

Thank you in advance,

HK.

### Script ####
canu -p ecoli -d ecoli-auto genomeSize=4.8m -pacbio-raw p6.25x.fastq

### Output ###
-- Detected Java(TM) Runtime Environment '1.8.0_25' (from 'java').
-- Detected 24 CPUs and 252 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
-- Allowed to run   6 jobs concurrently, and use up to   4 compute threads and   16 GB memory for stage 'bogart (unitigger)'.
-- Allowed to run   2 jobs concurrently, and use up to  12 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   2 jobs concurrently, and use up to  12 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   2 jobs concurrently, and use up to  12 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   6 jobs concurrently, and use up to   4 compute threads and    8 GB memory for stage 'read error detection (overlap error adjustment)'.
-- Allowed to run  24 jobs concurrently, and use up to   1 compute thread  and    2 GB memory for stage 'overlap error adjustment'.
-- Allowed to run   6 jobs concurrently, and use up to   4 compute threads and   32 GB memory for stage 'utgcns (consensus'.
-- Allowed to run  24 jobs concurrently, and use up to   1 compute thread  and    4 GB memory for stage 'overlap store parallel bucketizer'.
-- Allowed to run  24 jobs concurrently, and use up to   1 compute thread  and    6 GB memory for stage 'overlapper'.
-- Allowed to run   3 jobs concurrently, and use up to   8 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run   3 jobs concurrently, and use up to   8 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run   6 jobs concurrently, and use up to   4 compute threads and    8 GB memory for stage 'meryl (k-mer counting)'.
-- Allowed to run   6 jobs concurrently, and use up to   4 compute threads and   16 GB memory for stage 'falcon_sense (read correction)'.
-- Allowed to run   2 jobs concurrently, and use up to  12 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   2 jobs concurrently, and use up to  12 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   2 jobs concurrently, and use up to  12 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
--
-- This is canu parallel iteration #1, out of a maximum of 2 attempts.
--
-- Final error rates before starting pipeline:
...
...
#######################################################

**Comment by wisekh6** [comment]
Dear Sergey,

I have been testing canu in a different cluster which has 5 nodes and supports PBS qsub, by running the following command:
`canu -p ecoli -d ecoli-auto genomeSize=4.8m -pacbio-raw p6.25x.fastq gridOptionsJobName="canuRun3" gridOptions="-l nodes=5:ppn=23,walltime=2:00:00"`

But, I am not sure if canu really uses all of my cluster resources (all 5 nodes).
Is there any way to examine if this works in PBS mode using all the nodes?
My goal is to use all compute resources available in my cluster.
If you think this question is too trivial, please forgive me.

Thank you in advance,

HK.

**Comment by skoren** [comment]
You can run qstat to see the jobs currently running (you might need -a and -f to see all instances of an array job). There will be parts of canu where it runs a single job and parts where it will submit an array of jobs.

**Comment by wisekh6** [comment]
Thanks a lot for the tips.

**Comment by skoren** [comment]
I got an email about your comment that on another grid, it gave the message that no grid was detected but I don't see the comment in the thread here. Canu looks for key executables to determine what grid it's on, for PBS it is pbsnodes. It looks like your system is missing this which is why no grid is detected. pbsnodes is also how Canu determines available resources so without it you won't be able to run.

**Comment by wisekh6** [comment]
Thanks. Now, it works, but only by explicitly adding gridOptions="-l nodes=3:ppn=10,walltime=2:00:00".
I think my system has some problem that may block canu from automatically detecting grid system.

Best regards,

HK
