### ISSUE TITLE
trimming.html and unitigging.html

### ISSUE THREAD

**Issue by woodoo46** [marbl/canu#1133]
Hi there,

In Canu 1.6, after Canu finishes correctly, there will be correction.html, trimming.html and unitigging.html.  In 1.7.1, are these files removed? Or my run did not finish correctly (although I got the contig file **sample.contigs.fasta**)?

Thanks.

George

**Comment by brianwalenz** [comment]
They were removed - see #951 and #637 -- summary: read the *.report ASCII file for the same information.

If you've got *.contigs.fasta, you're done!
