### ISSUE TITLE
Installation fail

### ISSUE THREAD

**Issue by jeffapderek** [marbl/canu#1136]
I was trying to run the assembly in the quick start having installed it with sudo apt and getting the Mhap precompute failed. So I uninstalled it, downloaded your package to 'Downloads' and unpacked it with
tar -xJf canu-1.8.*.tar.xz

Saved the unzipped folder canu-1.8/* into my home directory and ran 
canu-1.8/*/bin/canu, which results in a list of instructions, but no installation. 
I presume I'm missing something pretty basic here. Grateful for any suggestions. Thanks

**Comment by skoren** [comment]
That's correct, there is nothing to install with the pre-compiled packages. Running canu without options gives usage instructions. Just run canu with whatever parameters you want, or the quickstart example.

**Comment by jeffapderek** [comment]
Thanks. I thought so. But it won't run, comes back with command not found. Do I need to paste the extracted folders into a particular directory?

**Comment by skoren** [comment]
What command are you running?

**Comment by jeffapderek** [comment]
trying to run the quick start code 

canu \
 -p ecoli -d ecoli-oxford \
 genomeSize=4.8m \
 -nanopore-raw oxford.fasta

**Comment by skoren** [comment]
You need to provide a full path to Canu (e.g. wherever_you_extracted/canu-1.8/*/bin/canu), your system doesn't know where to find it or add it to your system path.

**Comment by jeffapderek** [comment]
OK, that's working now I've put the canu files in the same directory as the reads that I'm assembling:
canu-1.8/*/bin/canu -p Ecoli -d Ecoli.Oxford genomeSize=4.8m -nanopore-raw oxford.fasta
 and it seems to be happily running cornhap.

but is there not a way of iconfiguring it so that I can simply type canu + parameters? 

Excuse my ignorance - this is the very first program I've ever installed on Linux!

**Comment by skoren** [comment]
Yeah, you have to modify your PATH variable, I suggest a linux quick start guide to get yourself familiar, for example:ftp://ftp.wayne.edu/ldp/en/Intro-Linux/Intro-Linux.pdf. See page 35 for information on paths.

**Comment by jeffapderek** [comment]
great stuff. I'll take a look at that. Thanks!
