### ISSUE TITLE
ULR with Pacbio

### ISSUE THREAD

**Issue by Lcornet** [marbl/canu#1137]
Hello,

I have a question about Ultra Long Read and CANU.
We produce ULR ONT on a plant genome, for a very low coverage. We would like to try an assembly with this low ULR coverage and our Pacbio data.
How can we do that with CANU, is it correct to mix to two type of data (ONT and Pacbio) and just change the deflines in the fasta file  ?

Thanks,
Luc

**Comment by brianwalenz** [comment]
No need to edit sequence names.  Just give both datasets to canu: `canu .... -pacbio-raw pacbio.fasta -nanopore-raw nanopore.fasta` (or fastq).

**Comment by skoren** [comment]
I'll add that if you don't have too much UL coverage and the majority of the data is PacBio, you can specify both sets of reads as pacbio and include the sequel options (```corMhapSensitivity=normal correctedErrorRate=0.105```) instead of letting the assembler default to nanopore parameters.
