### ISSUE TITLE
Possible to stop canu after trio binning, but before execution of haplotype assemblies

### ISSUE THREAD

**Issue by smg283** [marbl/canu#1140]
In canu v1.8, it is possible to run trio binning as part of the canu command using the -haplotype flags.  Is it possible to stop the pipeline after the trio binning is complete, but before execution of each of the haplotype assemblies (is there a flag similar to the "-correct" -"assemble", etc to restrict execution to only the trio binning step?)

**Comment by skoren** [comment]
You should be able to use the option ```stopAfter=haplotype```.

**Comment by brianwalenz** [comment]
I added a -haplotype option, mostly for consistency with the existing -correct et cetera options.  The stopAfter method will work too, it just omits a trivial report on the number of reads/bases in each haplotype read set, and doesn't generate scripts for running the assemblies.
