### ISSUE TITLE
CRASH: Please panic, this is abnormal.Failed to submit batch jobs.

### ISSUE THREAD

**Issue by fantasticair** [marbl/canu#1145]
```
canu.lsf
#BSUB -J WL
#BSUB -n 1
#BSUB -e WL.err
#BSUB -o WL.out
#BSUB -q queue
#BSUB -R "rusage[res=1]span[hosts=1]"
/home/software/canu-1.7/Linux-amd64/bin/canu -assemble -s pacbio.spec -p WL.assembly -d WL.assembly genomeSize=1100m gnuplotTested=true -pacbio-corrected /home/new/WL/WL.trimmedReads.fasta.gz

pacbio.spec
useGrid = true
maxThreads=24
maxMemory=125G
gridOptions = -q queue
minOverlapLength = 700
minReadLength  = 1000
corMhapSensitivity=normal

WL.err
-- Canu 1.7
--
-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
-- 
-- Read and contig alignments during correction, consensus and GFA building use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
--   Li H.
--   Minimap and miniasm: fast mapping and de novo assembly for noisy long sequences.
--   Bioinformatics. 2016 Jul 15;32(14):2103-10.
--   http://doi.org/10.1093/bioinformatics/btw152
-- 
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_72' (from 'java').
-- Detected 24 CPUs and 126 gigabytes of memory.
-- Limited to 125G gigabytes from maxMemory option.
-- Limited to 24 CPUs from maxThreads option.
-- Detected LSF with 'bsub' binary in /stor9000/apps/jhinno/unischeduler/jhlava/bin/linux-x86_64/bsub.
Invalid command <showconf> 

Usage: lsadmin [-h] [-V] [command] [command_options] [command_args]

    where 'command' is:

    reconfig    Reconfigure jhscheduler
    ckconfig    Check configuration files
    limrestart  Restart LIM (Load Information Manager)
    limstartup  Startup LIM (Load Information Manager)
    limshutdown Shut down LIM (Load Information Manager)
    limlock     Lock LIM on local host
    limunlock   Unlock LIM on local host
    resrestart  Restart RES (Remote Execution Server)
    resstartup  Startup RES (Remote Execution Server)
    resshutdown Shut down RES (Remote Execution Server)
    reslogon    Log tasks executed by RES
    reslogoff   RES log off
    limdebug    Debug LIM
    limtime     Debug LIM timing message
    resdebug    Debug RES
    restime     Debug RES timing message
    help        Get help on commands
    ?           Get help on commands
    quit        Quit
-- Warning: unknown memory units for grid engine LSF assuming KB
-- 
-- Found   8 hosts with  32 cores and  125 GB memory under LSF control.
-- Found  16 hosts with  28 cores and  251 GB memory under LSF control.
-- Found  44 hosts with  24 cores and  125 GB memory under LSF control.
-- Found   1 host  with  16 cores and   62 GB memory under LSF control.
-- Found   2 hosts with  56 cores and 2019 GB memory under LSF control.
-- Found  71 hosts with  24 cores and   62 GB memory under LSF control.
-- 
-- On LSF detected memory is requested in KB
-- 
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl    125 GB   24 CPUs  (k-mer counting)
-- Grid:  cormhap   20 GB    8 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    16 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl    16 GB    8 CPUs  (overlap detection)
-- Grid:  ovb        2 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       32 GB    1 CPU   (overlap store sorting)
-- Grid:  red        8 GB    4 CPUs  (read error detection)
-- Grid:  oea        4 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      125 GB   16 CPUs  (contig construction)
-- Grid:  gfa       16 GB   16 CPUs  (GFA alignment and processing)
--
-- Found PacBio corrected reads in the input files.
--
-- Generating assembly 'WL.assembly.chicken' in '/home/2.assembly/WL/new/WL/assembly/WL.assembly'
--
-- Parameters:
--
--  genomeSize        1100000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0750 (  7.50%)
--
--
-- BEGIN ASSEMBLY
--
----------------------------------------
-- Starting command on Thu Nov  8 20:41:21 2018 with 38580.014 GB free disk space

    cd .
    /home/software/canu-1.7/Linux-amd64/bin/gatekeeperCreate \
      -minlength 1000 \
      -o ./WL.assembly..gkpStore.BUILDING \
      ./WL.assembly..gkpStore.gkp \
    > ./WL.assembly.gkpStore.BUILDING.err 2>&1

-- Finished on Thu Nov  8 21:06:36 2018 (1515 seconds) with 38573.234 GB free disk space
----------------------------------------
--
-- WARNING:  No trimmed reads found for assembly, but untrimmed reads exist.
-- WARNING:  Upgrading untrimmed reads to trimmed reads for assembly.
--
-- WARNING: gnuplot failed.
--
----------------------------------------
--
-- In gatekeeper store './WL.assembly.chicken.gkpStore':
--   Found 2585228 reads.
--   Found 48977553094 bases (44.52 times coverage).
--
--   Read length histogram (one '*' equals 3491.11 reads):
--        0    999      0 
--     1000   1999      0 
--     2000   2999      0 
--     3000   3999      0 
--     4000   4999      0 
--     5000   5999      0 
--     6000   6999      0 
--     7000   7999      0 
--     8000   8999      0 
--     9000   9999      0 
--    10000  10999      0 
--    11000  11999      0 
--    12000  12999 227099 *****************************************************************
--    13000  13999 216934 **************************************************************
--    14000  14999 209287 ***********************************************************
--    15000  15999 217620 **************************************************************
--    16000  16999 242749 *********************************************************************
--    17000  17999 244378 **********************************************************************
--    18000  18999 207861 ***********************************************************
--    19000  19999 172648 *************************************************
--    20000  20999 143608 *****************************************
--    21000  21999 120170 **********************************
--    22000  22999  99677 ****************************
--    23000  23999  82862 ***********************
--    24000  24999  69070 *******************
--    25000  25999  57059 ****************
--    26000  26999  47591 *************
--    27000  27999  40010 ***********
--    28000  28999  33871 *********
--    29000  29999  27751 *******
--    30000  30999  23286 ******
--    31000  31999  19433 *****
--    32000  32999  15903 ****
--    33000  33999  13019 ***
--    34000  34999  10702 ***
--    35000  35999   8641 **
--    36000  36999   6915 *
--    37000  37999   5521 *
--    38000  38999   4516 *
--    39000  39999   3559 *
--    40000  40999   2952 
--    41000  41999   2268 
--    42000  42999   1847 
--    43000  43999   1391 
--    44000  44999   1144 
--    45000  45999    846 
--    46000  46999    702 
--    47000  47999    554 
--    48000  48999    404 
--    49000  49999    360 
--    50000  50999    251 
--    51000  51999    196 
--    52000  52999    158 
--    53000  53999    113 
--    54000  54999     64 
--    55000  55999     63 
--    56000  56999     51 
--    57000  57999     35 
--    58000  58999     25 
--    59000  59999     14 
--    60000  60999     12 
--    61000  61999     16 
--    62000  62999      7 
--    63000  63999      2 
--    64000  64999      5 
--    65000  65999      3 
--    66000  66999      0 
--    67000  67999      0 
--    68000  68999      1 
--    69000  69999      2 
--    70000  70999      2 
--
-- Running jobs.  First attempt out of 2.
--

CRASH:
CRASH: Canu 1.7
CRASH: Please panic, this is abnormal.
ABORT:
CRASH:   Failed to submit batch jobs.
CRASH:
CRASH: Failed at /home/software/canu-1.7/Linux-amd64/bin/../lib/site_perl/canu/Execution.pm line 1101
CRASH:  canu::Execution::submitOrRunParallelJob('WL.assembly.chicken', 'meryl', 'unitigging/0-mercounts', 'meryl', 1) called at /home/software/canu-1.7/Linux-amd
CRASH:  canu::Meryl::merylCheck('WL.assembly.chicken', 'utg') called at /home/software/canu-1.7/Linux-amd64/bin/canu line 677
CRASH: 
CRASH: Last 50 lines of the relevant log file (unitigging/0-mercounts/meryl.jobSubmit-01.out):
CRASH:
CRASH:
```
I guess it is caused by a large amount of data (more than 40X), then I continue to reduce the amount of data to remove the shorter reads, or the same error.

**Comment by fantasticair** [comment]
Thanks!
I chose the 1.8 version of canu to run, no error above, but no result.
The informtion of error as follows：
Use of implicit split to @_ is deprecated at /home/anaconda2/libexec/bin/../lib/site_perl/canu/Grid_Cloud.pm line 73.
-- Canu snapshot (snapshot)
--
-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
-- 
-- Koren S, Rhie A, Walenz BP, Dilthey AT, Bickhart DM, Kingan SB, Hiendleder S, Williams JL, Smith TPL, Phillippy AM.
-- De novo assembly of haplotype-resolved genomes with trio binning.
-- Nat Biotechnol. 2018
-- https//doi.org/10.1038/nbt.4277
-- 
-- Read and contig alignments during correction, consensus and GFA building use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_72' (from 'java') with -d64 support.
-- Detected gnuplot version '4.2 patchlevel 6 ' (from 'gnuplot') and image format 'png'.
-- Detected 24 CPUs and 126 gigabytes of memory.
-- Limited to 125G gigabytes from maxMemory option.
-- Limited to 24 CPUs from maxThreads option.
-- Detected LSF with 'bsub' binary in /home/apps/jhinno/unischeduler/jhlava/bin/linux-x86_64/bsub.
Invalid command <showconf> 

Usage: lsadmin [-h] [-V] [command] [command_options] [command_args]

    where 'command' is:

    reconfig    Reconfigure jhscheduler
    ckconfig    Check configuration files
    limrestart  Restart LIM (Load Information Manager)
    limstartup  Startup LIM (Load Information Manager)
    limshutdown Shut down LIM (Load Information Manager)
    limlock     Lock LIM on local host
    limunlock   Unlock LIM on local host
    resrestart  Restart RES (Remote Execution Server)
    resstartup  Startup RES (Remote Execution Server)
    resshutdown Shut down RES (Remote Execution Server)
    reslogon    Log tasks executed by RES
    reslogoff   RES log off
    limdebug    Debug LIM
    limtime     Debug LIM timing message
    resdebug    Debug RES
    restime     Debug RES timing message
    help        Get help on commands
    ?           Get help on commands
    quit        Quit
-- Warning: unknown memory units for grid engine LSF assuming KB
Argument "-" isn't numeric in int at /home/apps/users/anaconda2/libexec/bin/../lib/site_perl/canu/Grid_LSF.pm line 152, <F> line 113.
Argument "-" isn't numeric in int at /home/apps/users/anaconda2/libexec/bin/../lib/site_perl/canu/Grid_LSF.pm line 152, <F> line 121.
-- 
-- Found   8 hosts with  32 cores and  125 GB memory under LSF control.
-- Found  16 hosts with  28 cores and  251 GB memory under LSF control.
-- Found  44 hosts with  24 cores and  125 GB memory under LSF control.
-- Found   1 host  with  16 cores and   62 GB memory under LSF control.
-- Found   2 hosts with  56 cores and 2019 GB memory under LSF control.
-- Found  71 hosts with  24 cores and   62 GB memory under LSF control.
-- 
-- On LSF detected memory is requested in KB
-- 
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl     31 GB    8 CPUs  (k-mer counting)
-- Grid:  hap       16 GB   24 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   20 GB    8 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    16 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl    16 GB    8 CPUs  (overlap detection)
-- Grid:  ovb        4 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       32 GB    1 CPU   (overlap store sorting)
-- Grid:  red       10 GB    4 CPUs  (read error detection)
-- Grid:  oea        4 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      125 GB   16 CPUs  (contig construction with bogart)
-- Grid:  gfa       16 GB   16 CPUs  (GFA alignment and processing)
--
-- Found PacBio corrected reads in the input files.
--
-- Generating assembly 'WL.assembly' in '/home/apps/users/2.assembly/WL/new/WL/assembly/WL.assembly'
--
-- Parameters:
--
--  genomeSize        1100000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0750 (  7.50%)
--
--
-- BEGIN ASSEMBLY
--
----------------------------------------
-- Starting command on Thu Nov  8 23:08:27 2018 with 38585.041 GB free disk space

    cd .
    /home/apps/users/anaconda2/libexec/bin/sqStoreCreate \
      -o ./WL.assembly.seqStore.BUILDING \
      -minlength 1000 \
      ./WL.assembly.seqStore.ssi \
    > ./WL.assembly.seqStore.BUILDING.err 2>&1

-- Finished on Thu Nov  8 23:31:38 2018 (1391 seconds) with 38567.371 GB free disk space
----------------------------------------
--
-- WARNING:  No trimmed reads found for assembly, but untrimmed reads exist.
-- WARNING:  Upgrading untrimmed reads to trimmed reads for assembly.
--
-- In sequence store './WL.assembly.seqStore':
--   Found 5740581 reads.
--   Found 68245350354 bases (62.04 times coverage).
--
--   Read length histogram (one '*' equals 5543.34 reads):
--     1000   1999 388034 **********************************************************************
--     2000   2999 325949 **********************************************************
--     3000   3999 303902 ******************************************************
--     4000   4999 289519 ****************************************************
--     5000   5999 282118 **************************************************
--     6000   6999 278438 **************************************************
--     7000   7999 271520 ************************************************
--     8000   8999 267426 ************************************************
--     9000   9999 259553 **********************************************
--    10000  10999 250355 *********************************************
--    11000  11999 238539 *******************************************
--    12000  12999 227099 ****************************************
--    13000  13999 216934 ***************************************
--    14000  14999 209287 *************************************
--    15000  15999 217620 ***************************************
--    16000  16999 242749 *******************************************
--    17000  17999 244378 ********************************************
--    18000  18999 207861 *************************************
--    19000  19999 172648 *******************************
--    20000  20999 143608 *************************
--    21000  21999 120170 *********************
--    22000  22999  99677 *****************
--    23000  23999  82862 **************
--    24000  24999  69070 ************
--    25000  25999  57059 **********
--    26000  26999  47591 ********
--    27000  27999  40010 *******
--    28000  28999  33871 ******
--    29000  29999  27751 *****
--    30000  30999  23286 ****
--    31000  31999  19433 ***
--    32000  32999  15903 **
--    33000  33999  13019 **
--    34000  34999  10702 *
--    35000  35999   8641 *
--    36000  36999   6915 *
--    37000  37999   5521 
--    38000  38999   4516 
--    39000  39999   3559 
--    40000  40999   2952 
--    41000  41999   2268 
--    42000  42999   1847 
--    43000  43999   1391 
--    44000  44999   1144 
--    45000  45999    846 
--    46000  46999    702 
--    47000  47999    554 
--    48000  48999    404 
--    49000  49999    360 
--    50000  50999    251 
--    51000  51999    196 
--    52000  52999    158 
--    53000  53999    113 
--    54000  54999     64 
--    55000  55999     63 
--    56000  56999     51 
--    57000  57999     35 
--    58000  58999     25 
--    59000  59999     14 
--    60000  60999     12 
--    61000  61999     16 
--    62000  62999      7 
--    63000  63999      2 
--    64000  64999      5 
--    65000  65999      3 
--    66000  66999      0 
--    67000  67999      0 
--    68000  68999      1 
--    69000  69999      2 
--    70000  70999      2 
----------------------------------------
-- Starting command on Thu Nov  8 23:32:49 2018 with 38567.233 GB free disk space

    cd unitigging/0-mercounts
    ./meryl-configure.sh \
    > ./meryl-configure.err 2>&1

-- Finished on Thu Nov  8 23:33:05 2018 (16 seconds) with 38566.549 GB free disk space
----------------------------------------
--  segments   memory batches
--  -------- -------- -------
--        01 31.00 GB       7
--        02 31.00 GB       4
--        04 31.00 GB       3
--        06 31.00 GB       2
--        08 28.00 GB       2
--        12 19.99 GB       1
--        16 15.00 GB       1
--        20 12.00 GB       1
--        24 10.00 GB       1
--        32  8.00 GB       1
--        40  6.00 GB       1
--        48  5.00 GB       1
--        56  4.00 GB       1
--        64  4.00 GB       1
--        96  2.87 GB       1
--
--  For 5740581 reads with 68245350354 bases, limit to 682 batches.
--  Will count kmers using 12 jobs, each using 21 GB and 8 threads.
--
-- Finished stage 'merylConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
--
-- 'meryl-count.jobSubmit-01.sh' -> job ended(6179788) tasks 1-12.
--
----------------------------------------
-- Starting command on Thu Nov  8 23:33:07 2018 with 38566.549 GB free disk space

    cd /home/apps/users/2.assembly/WL/new/WL/assembly/WL.assembly
    bsub \
      -w "ended(6179788)"  \
      -q nodequeue \
      -M 4194304 \
      -R span[hosts=1] \
      -n 1 \
      -J 'canu_WL.assembly' \
      -o canu-scripts/canu.01.out  canu-scripts/canu.01.sh

-- Finished on Thu Nov  8 23:33:07 2018 (one second) with 38566.549 GB free disk space
----------------------------------------
Use of implicit split to @_ is deprecated at /home/apps/users/anaconda2/libexec/bin/../lib/site_perl/canu/Grid_Cloud.pm line 73.
-- Canu snapshot (snapshot)
--
-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
-- 
-- Koren S, Rhie A, Walenz BP, Dilthey AT, Bickhart DM, Kingan SB, Hiendleder S, Williams JL, Smith TPL, Phillippy AM.
-- De novo assembly of haplotype-resolved genomes with trio binning.
-- Nat Biotechnol. 2018
-- https//doi.org/10.1038/nbt.4277
-- 
-- Read and contig alignments during correction, consensus and GFA building use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_72' (from 'java') with -d64 support.
-- Detected gnuplot version '4.2 patchlevel 6 ' (from 'gnuplot') and image format 'png'.
-- Detected 24 CPUs and 126 gigabytes of memory.
-- Limited to 100G gigabytes from maxMemory option.
-- Limited to 24 CPUs from maxThreads option.
-- Detected LSF with 'bsub' binary in /stor9000/apps/jhinno/unischeduler/jhlava/bin/linux-x86_64/bsub.
Invalid command <showconf> 

Usage: lsadmin [-h] [-V] [command] [command_options] [command_args]

    where 'command' is:

    reconfig    Reconfigure jhscheduler
    ckconfig    Check configuration files
    limrestart  Restart LIM (Load Information Manager)
    limstartup  Startup LIM (Load Information Manager)
    limshutdown Shut down LIM (Load Information Manager)
    limlock     Lock LIM on local host
    limunlock   Unlock LIM on local host
    resrestart  Restart RES (Remote Execution Server)
    resstartup  Startup RES (Remote Execution Server)
    resshutdown Shut down RES (Remote Execution Server)
    reslogon    Log tasks executed by RES
    reslogoff   RES log off
    limdebug    Debug LIM
    limtime     Debug LIM timing message
    resdebug    Debug RES
    restime     Debug RES timing message
    help        Get help on commands
    ?           Get help on commands
    quit        Quit
-- Warning: unknown memory units for grid engine LSF assuming KB
Argument "-" isn't numeric in int at /home/apps/users/anaconda2/libexec/bin/../lib/site_perl/canu/Grid_LSF.pm line 152, <F> line 113.
Argument "-" isn't numeric in int at /home/apps/users//anaconda2/libexec/bin/../lib/site_perl/canu/Grid_LSF.pm line 152, <F> line 121.
-- 
-- Found   8 hosts with  32 cores and  125 GB memory under LSF control.
-- Found  16 hosts with  28 cores and  251 GB memory under LSF control.
-- Found  44 hosts with  24 cores and  125 GB memory under LSF control.
-- Found   1 host  with  16 cores and   62 GB memory under LSF control.
-- Found   2 hosts with  56 cores and 2019 GB memory under LSF control.
-- Found  71 hosts with  24 cores and   62 GB memory under LSF control.
-- 
-- On LSF detected memory is requested in KB
-- 
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl     31 GB    8 CPUs  (k-mer counting)
-- Grid:  hap       16 GB   24 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   20 GB    8 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    16 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl    16 GB    8 CPUs  (overlap detection)
-- Grid:  ovb        4 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       32 GB    1 CPU   (overlap store sorting)
-- Grid:  red       10 GB    4 CPUs  (read error detection)
-- Grid:  oea        4 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      100 GB   16 CPUs  (contig construction with bogart)
-- Grid:  gfa       16 GB   16 CPUs  (GFA alignment and processing)
--
-- In 'WL.assembly.seqStore', found PacBio reads:
--   Raw:        0
--   Corrected:  5740581
--   Trimmed:    5740581
--
-- Generating assembly 'WL.assembly' in '/home/apps/users/2.assembly/WL/new/assembly/WL.assembly'
--
-- Parameters:
--
--  genomeSize        1100000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0750 (  7.50%)
--
--
-- BEGIN ASSEMBLY
--
--
-- Running jobs.  First attempt out of 2.
--
-- 'unitigger.jobSubmit-01.sh' -> job ended(6180325) task 1.
--
----------------------------------------
-- Starting command on Fri Nov  9 15:32:25 2018 with 38536.845 GB free disk space

    cd /home/apps/users/2.assembly/WL/new/WL/assembly/WL.assembly
    bsub \
      -w "ended(6180325)"  \
      -q nodequeue \
      -M 4194304 \
      -R span[hosts=1] \
      -n 1 \
      -J 'canu_WL.assembly' \
      -o canu-scripts/canu.05.out  canu-scripts/canu.05.sh

-- Finished on Fri Nov  9 15:32:26 2018 (one second) with 38536.845 GB free disk space
----------------------------------------

**Comment by brianwalenz** [comment]
Please format your replies!  Read "Styling with Markdown is supported" below the reply box on the left side.  Click on "Preview" to see what it will look like.

Where's the error?  I see the unitigger job being submitted, and the next iteration of canu being submitted.  Did they run?

**Comment by fantasticair** [comment]
It is ok,the result is run out.

**Comment by fantasticair** [comment]
Hello,
I used all the corrected reads to assemble, and the results showed that the contig N50 was shortened from the original 9M to 6M compared to the longest corrected 40X reads. We have about 80X of data, all the parameters are assembled above, can you give me some advice?

**Comment by skoren** [comment]
The assembly is best around 25-35x coverage, more than can start to make errors appear real and to introduce other artifacts. This is why we select the longest 40x to maximize the assembly. The only times when it can be useful to correct all data is when you have a highly heterozygous genome and you need more coverage of each haplotype (since you want 25-35x of each).

**Comment by skoren** [comment]
Closing, original issue of submission is fixed. Open a new issue if you encounter other run errors.
