### ISSUE TITLE
Assembly data selection

### ISSUE THREAD

**Issue by Xuelei-Dai** [marbl/canu#1150]
Hello,
I have the pacbio data about 80X ,and the  heterozygosity is low. 
I used `canu-1.8` to correct all reads and they are used for assembly，compare with using the longest 40X is better,@https://github.com/marbl/canu/issues/1145#issuecomment-437373440.If I choose the longest 40X data in all the corrected reads to assemble, will the result be better?

Thanks

**Comment by fantasticair** [comment]
Thank you very much for your quick reply！
