### ISSUE TITLE
Difference between smashed and default assembly?

### ISSUE THREAD

**Issue by psur9757** [marbl/canu#1151]
Can you please explain the difference between the contigs.fasta and unitigs.fasta in the smashed vs default assembly? I did read https://canu.readthedocs.io/en/latest/tutorial.html#outputs, but it didn't answer my question.

I ran my PacBio data both ways. I was expecting both contigs and unitigs while running default but only contigs when running smashed. Actually, I get more unitig data with the smashed version that without. It truly does not make sense to me.

Which fasta file should I proceed with for haplotyping? Below are the scripts and outputs.

canu_default.pbs
```
#!/bin/bash
#PBS -P RDS-FAE-OSR-RW
#PBS -N canu
#PBS -l select=1:ncpus=8:mem=64GB
#PBS -l walltime=36:00:00
#PBS -e ./OSR_512_canu_error.txt
#PBS -o ./OSR_512_canu_output.txt
#PBS -M priyanka.surana@sydney.edu.au
#PBS -m abe

module load canu/1.7

canu -p OSR_512_canu -d /scratch/RDS-FAE-OSR-RW/OSR_512_canu gnuplot="/usr/local/gnuplot/5.0.0/bin/gnuplot" genomeSize=86m corOutCoverage=999 gridOptions="-P RDS-FAE-OSR-RW" gridOptionsJobName=OSR512 corConcurrency=4 gridOptionsCOR="-l walltime=36:00:00" gridOptionsCORMHAP="-l walltime=36:00:00" gridOptionsCOROVL="-l walltime=36:00:00" gridOptionsOBTOVL="-l walltime=56:00:00 -l mem=16g -l nodes=1:ppn=8" gridOptionsUTGOVL="-l walltime=56:00:00 -l mem=16g -l nodes=1:ppn=8" -pacbio-raw /home/psur9757/osr/raw_data/m54078_170626_*.subreads.fasta

module unload canu/1.7
```

This ouputs `OSR_512_canu3.contigs.fasta - 158M` and `OSR_512_canu.unitigs.fasta - 187M`.

canu_smashed.pbs
```
#!/bin/bash
#PBS -P RDS-FAE-OSR-RW
#PBS -N canu3
#PBS -l select=1:ncpus=8:mem=64GB
#PBS -l walltime=36:00:00
#PBS -e ./OSR_512_canu3_error.txt
#PBS -o ./OSR_512_canu3_output.txt
#PBS -M priyanka.surana@sydney.edu.au
#PBS -m abe

module load canu/1.7

canu -p OSR_512_canu3 -d /scratch/RDS-FAE-OSR-RW/OSR_512_canu3 gnuplot="/usr/local/gnuplot/5.0.0/bin/gnuplot" genomeSize=86m corOutCoverage=200 correctedErrorRate=0.15 gridOptions="-P RDS-FAE-OSR-RW" gridOptionsJobName=OSR512 corConcurrency=4 gridOptionsCOR="-l walltime=36:00:00" gridOptionsCORMHAP="-l walltime=36:00:00" gridOptionsCOROVL="-l walltime=36:00:00" gridOptionsOBTOVL="-l walltime=156:00:00 -l nodes=1:ppn=8" gridOptionsUTGOVL="-l walltime=156:00:00 -l nodes=1:ppn=8" gridOptionsOEA="-l walltime=16:00:00 -l nodes=1:ppn=8" oeaMemory=64 -pacbio-raw /scratch/RDS-FAE-OSR-RW/raw_data/m54078_170626_*.subreads.fasta

module unload canu/1.7
``` 

This outputs `OSR_512_canu3.contigs.fasta – 158M` and `OSR_512_canu3.unitigs.fasta - 196M`.

**Comment by skoren** [comment]
There is no difference in output between a smashed assembly and a regular one, you're just changing error tolerance. The output is always the same no matter what parameters you change. Unitigs are just contigs split at intersections, like haplotype switches. So in a smashed assembly you probably have more of these intersections and more unitigs since you have more haplotype switching/smashing in the contigs. 

You probably want the contigs for downstream analysis, though I'm not sure what you mean by "haplotyping". The contigs will definitely contain haplotype switches and will be a mixed consensus of both haplotypes. The unitigs will split at many haplotype switches but may still have mixed consensus from both haplotypes. So if you're running a tool like whatshap or similar, you can let it try to fix consensus. Generally, this is why we recommend the non-smashed assembly since it ends up with less of a mixed consensus.

**Comment by skoren** [comment]
Looking at the issue you posted on HapCut2 I am not sure you're going to get what you want from the smashed assembly. You're never going to get a fully phased haplotype across the genome (without a trio) and at best could get phased chromosomes but that would require more data than just PacBio sequencing. There also aren't really good tools at taking a partially phased assembly.

The main benefit of a smashed assembly is a reduced assembly size at the cost of a less accurate consensus. The general recommendation on the FAQ is to use the heterozygous parameters and remove the redundancy using a different program, like purge_haplotigs. I would say this is a better option for you as well. As long as your diversity is relatively high (over 2%), you'd get a genome twice the expected size that purge_haplotigs would reduce down to close to the expected. You can then use the filtered contig set as a "haplotype" and improve phasing on it using hapcut2/whatshap/etc but you'd still likely end up with pseudohaplotypes where each contig could switch phase. You'd have to break contigs at every phase block if you really wanted to get haplotigs but those would likely be much shorter than the contigs (see the korean human paper for an example of this strategy: https://www.nature.com/articles/nature20098).
