### ISSUE TITLE
Overlap store sorting jobs failed

### ISSUE THREAD

**Issue by vidhyajagannathan** [marbl/canu#1152]
Hi 
I was running Canu 1.6 on a 2.7Gb genome with ~100x coverage of PacBio reads. 
In the correction step I have the following error. 
```
-- Overlap store sorting jobs failed, tried 2 times, giving up.
--   job correction/canu_PacBio.ovlStore.BUILDING/2603 FAILED.
--   job correction/canu_PacBio.ovlStore.BUILDING/2649 FAILED. 
```

I tried to restart Canu, but it gave the same error. and then I increased the OvsMemory to 100g as suggested in one the reported issues earlier, but still have the same issue. 
Also during the runs Canu reported "No disk space left" error. and then I had restart after making more disk space available. 

Here is the command I have used for the correction step. 
canu -correct -p canu_PacBio -d canu_PacBio genomeSize=2.7g -pacbio-raw  *.subreads.fastq.gz java=/software/Development/java/1.8.0_121/bin/java gridOptions="-q highmem.q" gridEngineThreadsOption="-pe smp THREADS" gridEngineMemoryOption="-l h_rss=MEMORY" ovsMemory=100g corMhapSensitivity=high corMinCoverage=0 correctedErrorRate=0.105

Thank you very much for your answer. 

regards
Vidhya

**Comment by skoren** [comment]
I'm going to guess you've got file corruption due to the earlier out of disk error. What is the output from one of the failed jobs (```correction/canu_PacBio.ovlStore.BUILDING/logs/2-sort*2603*out```)?. 1.6 is also quite old and this step has had several major fixes since then. Once you complete the correction step, I'd recommend re-launching with Canu 1.8 with the corrected reads.

**Comment by vidhyajagannathan** [comment]
Dear skoren 
Thank you very much for fast response and for your suggestions. Here is last few lines from both the failed processes. 
-----------------------------------------------------------------------
correction/canu_PacBio.ovlStore.BUILDING/logs/2-sort*2603*out
  loading    1581142 overlaps from './bucket0834/slice2603'.
  loading    1462810 overlaps from './bucket0836/slice2603'.
  loading  143453009 overlaps from './bucket0838/slice2603'.
ERROR: short read on file './bucket0838/slice2603': read 820949 bytes, expected 823339.
--------------------------------------------------------------------------------
correction/canu_PacBio.ovlStore.BUILDING/logs/2-sort*2649*out 
 loading    1332275 overlaps from './bucket0842/slice2649'.
 loading    1324318 overlaps from './bucket0844/slice2649'.
 loading  146061247 overlaps from './bucket0846/slice2649'.
ERROR: short read on file './bucket0846/slice2649': read 817680 bytes, expected 822701.
-------------------------------------------------------------------------------
Thank you very much once again for your answer. 

regards
Vidhya

**Comment by skoren** [comment]
Yep, you've got truncated files. At least bucket0846 and bucket0838 are affected and maybe others. You can remove those bucket folders completely and any files named *.ovs, then run the following from inside the canu_PacBio.ovlStore.BUILDING folder:
```
sh scripts/1-bucketize.sh 838
sh scripts/1-bucketize.sh 846
sh scripts/2-sort.sh 2603
sh scripts/2-sort.sh 2649
```
The sort jobs may fail again if you have more file corruption. If that's the case, look for the bucket with the error in the output, remove those, and repeat the above steps.

**Comment by vidhyajagannathan** [comment]
Hi  Sergey Koren
I did the steps you suggested above and then reran by canu_correction step to make sure it goes through. It has been running since 14th of Nov. and I see that this file is getting updated correction/2-correction/canu_PacBio.estimate.WORKING.log. 
Is it normal to run this long ?  

Thank you very much for your answer and your time. 
Vidhya

**Comment by skoren** [comment]
Yes, that step is single-core and can be slow, depending on the size of your overlap store (which I'll guess is large since you had space issues). This step is also gone in newer Canu versions. The good news is it seems your store building seems to have completed.
