### ISSUE TITLE
canu stuck at ovS

### ISSUE THREAD

**Issue by harmeet1990** [marbl/canu#1153]
I am trying to correct nanopore reads for a polyploid plant genome of approximately 1gbp with almost 40x coverage.
Here is the command I am using 
/homes/hchawla/canu/Linux-amd64/bin/canu -correct -p express617_ONT -d /nfs/agipz/harmeet/nanopore_analysis/express617/02_canu_correction/no_backup -genomeSize=1.2g -nanopore-raw /nfs/agipz/harmeet/nanopore_analysis/express617/01_raw_ONT_data/express617_ONT.fastq -maxThreads=32 maxMemory=256g
canu version is 1.7 running on  Ubuntu 16.04.5 LTS on an interactive node on a cluster.

Every time I try to run canu it is failing at ovS stage. All the jobs fail in the second attempt and not a part of them.Below is the output of log file in 
/nfs/agipz/harmeet/nanopore_analysis/express617/02_canu_correction/no_backup/correction/express617_ONT.ovlStore.BUILDING/logs/2-sort.000001.out

```
Found perl:
   /usr/bin/perl
   This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi

   java version "1.8.0_171"

Found canu:
   /homes/hchawla/canu/Linux-amd64/bin/canu
   Canu snapshot v1.7 +479 changes (r9171 8cb8c1a26356b8e562cf59221ed85285770a22f1)

Running job 1 based on command line options.

Attempting to increase maximum allowed processes and open files.
./scripts/2-sort.sh: 1: ulimit: Illegal option -u
./scripts/2-sort.sh: 1: ulimit: Illegal option -u
./scripts/2-sort.sh: 70: ulimit: Illegal option -u
./scripts/2-sort.sh: 1: ulimit: Illegal option -u
  Changed max processes per user from  to  (max ).
  Changed max open files from 1024 to 1048576 (max 1048576).


Finding overlaps.
  found  471479733 overlaps in './express617_ONT.ovlStore.BUILDING/bucket0001/sliceSizes'.
  found  219559298 overlaps in './express617_ONT.ovlStore.BUILDING/bucket0002/sliceSizes'.
  found  212780400 overlaps in './express617_ONT.ovlStore.BUILDING/bucket0003/sliceSizes'.
  found  336810547 overlaps in './express617_ONT.ovlStore.BUILDING/bucket0004/sliceSizes'.

Loading 1240629978 overlaps using 27.73 GB of allowed (-M) 29 GB memory.
  loading  471479733 overlaps from './express617_ONT.ovlStore.BUILDING/bucket0001/slice0001'.
  loading  219559298 overlaps from './express617_ONT.ovlStore.BUILDING/bucket0002/slice0001'.
  loading  212780400 overlaps from './express617_ONT.ovlStore.BUILDING/bucket0003/slice0001'.
  loading  336810547 overlaps from './express617_ONT.ovlStore.BUILDING/bucket0004/slice0001'.

Sorting.

Writing sorted overlaps.
Failed to open './express617_ONT.ovlStore.BUILDING/0001<001>' for writing: Invalid argument

```
Can you please suggest a solution to this? I have already tried restarting Canu (with and without deleting the express617_ONT.ovlStore.BUILDING folder). I have also tried specifying shell='bin/bash', but didn't help.

Thanks
Harmeet

**Comment by brianwalenz** [comment]
Interesting (in a bad way).

Do you know what file system the cluster is using?  Can you create files with '>' or '<' in them (e.g., `touch "test<"`)?

I'll work on a fix, but I suspect it will end up being a compile time option.

**Comment by harmeet1990** [comment]
I think the cluster is using an nfs filesystem as far as I can check and yes I can create files with >' or '<' in them.

**Comment by brianwalenz** [comment]
I've (finally, hopefully) resolved this, but you'll need to compile a custom version of Canu.  Follow the install directions for the 'unreleased version', but compile with `gmake POSIX_FILE_NAMES=1`.

With that, you can resume the current assembly (no need to start over from scratch), possibly deleting `express617_ONT.ovlStore.BUILDING` first.

**Comment by harmeet1990** [comment]
Can I use make instead of gmake? I get an error while trying to use gmake .

**Comment by harmeet1990** [comment]
it worked...thanks a ton
