### ISSUE TITLE
Robustness to SLURM timeouts

### ISSUE THREAD

**Issue by charles-plessy** [marbl/canu#1154]
Our Slurm workload manager sometimes becomes unavailable for a while; typically when some users or bogus scripts start an unreasonable amount of jobs, etc.  A typical error message is `slurm_load_jobs error: Socket timed out on send/recv operation`. If this happen when our canu job needs to start new jobs, then it fails.

Would it be possible to make canu more robust to transient Slurm unavailabilities ?

**Comment by skoren** [comment]
You can always restart the canu job and it will resume from where it left off.

It is possible to make canu retry the submission multiple times but that can still fail if the error lasts too long. I don't want to put in grid-specific logic to figure out what a transient slurm error is vs a true submission error.

If you want to change the code and submit a pull request, go ahead. That will probably be faster than us changing it plus you can test it and we can't (our slurm is pretty reliable at submitting jobs). In src/pipelines/canu/Execution.pm in the functions submitOrRunParallelJob:
```
1233             runCommandSilently($path, "./$cmd.sh", 0) and caFailure("Failed to submit batch jobs", "$path/$cmd.out");
```
and submitScript:
```
 780     runCommand(getcwd(), $qcmd) and caFailure("Failed to submit script", undef);
```
You'd have to make these retry loops that check for success, wait/sleep, and retry some number of times (say 2)

**Comment by brianwalenz** [comment]
I added a single retry attempt.  It doesn't distinguish between 'errors' and 'timeouts', which will make the error logging from actual errors a bit messier that it should be.
