### ISSUE TITLE
Installing 1.8 but showing 1.6

### ISSUE THREAD

**Issue by piiboo** [marbl/canu#1155]
Hello,
I managed to install Canu by following the instructions in release. I downloaded the binary 'canu-1.8.Linux-amd64.tar.xz', then installed with command 'tar -xJf canu-1.8.*.tar.xz'. In terminal it showed success. However when I check the version using canu -version, it shows canu 1.6. And it does not run correctly. 

```
-- Canu 1.6
--
-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
-- 
-- Read and contig alignments during correction, consensus and GFA building use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
--   Li H.
--   Minimap and miniasm: fast mapping and de novo assembly for noisy long sequences.
--   Bioinformatics. 2016 Jul 15;32(14):2103-10.
--   http://doi.org/10.1093/bioinformatics/btw152
-- 
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '10.0.2' (from 'java').
-- Detected gnuplot version '5.2 patchlevel 2' (from 'gnuplot') and image format 'png'.
-- Detected 40 CPUs and 126 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |  algorithm
--        -------  ------  --------   --------  -----------------------------
-- Local: meryl      8 GB    4 CPUs x  10 jobs  (k-mer counting)
-- Local: cormhap    6 GB   10 CPUs x   4 jobs  (overlap detection with mhap)
-- Local: obtovl     8 GB    8 CPUs x   5 jobs  (overlap detection)
-- Local: utgovl     8 GB    8 CPUs x   5 jobs  (overlap detection)
-- Local: cor        6 GB    2 CPUs x  20 jobs  (read correction)
-- Local: ovb        3 GB    1 CPU  x  40 jobs  (overlap store bucketizer)
-- Local: ovs        8 GB    1 CPU  x  40 jobs  (overlap store sorting)
-- Local: red        2 GB    4 CPUs x  10 jobs  (read error detection)
-- Local: oea        1 GB    1 CPU  x  40 jobs  (overlap error adjustment)
-- Local: bat       12 GB    4 CPUs x  10 jobs  (contig construction)
-- Local: cns       12 GB    4 CPUs x  10 jobs  (consensus)
-- Local: gfa        8 GB    4 CPUs x  10 jobs  (GFA alignment and processing)
--
-- Found Nanopore uncorrected reads in the input files.
--
-- Generating assembly 'lambdaDevono' in '/home/geneious/lambdarun'
--
-- Parameters:
--
--  genomeSize        48500
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1440 ( 14.40%)
--    utgOvlErrorRate 0.1440 ( 14.40%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1440 ( 14.40%)
--    utgErrorRate    0.1440 ( 14.40%)
--    cnsErrorRate    0.1920 ( 19.20%)
--
--
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Tue Nov 13 21:05:24 2018 with 62.856 GB free disk space

    cd correction
    /usr/lib/canu/gatekeeperCreate \
      -minlength 1000 \
      -o ./lambdaDevono.gkpStore.BUILDING \
      ./lambdaDevono.gkpStore.gkp \
    > ./lambdaDevono.gkpStore.BUILDING.err 2>&1

-- Finished on Tue Nov 13 21:05:47 2018 (23 seconds) with 62.561 GB free disk space
----------------------------------------
--
-- In gatekeeper store 'correction/lambdaDevono.gkpStore':
--   Found 141265 reads.
--   Found 1053670231 bases (21725.15 times coverage).
--
--   Read length histogram (one '*' equals 270.92 reads):
--        0    999      0 
--     1000   1999  18965 **********************************************************************
--     2000   2999  17182 ***************************************************************
--     3000   3999  15155 *******************************************************
--     4000   4999  13015 ************************************************
--     5000   5999  11302 *****************************************
--     6000   6999   9630 ***********************************
--     7000   7999   8212 ******************************
--     8000   8999   7076 **************************
--     9000   9999   5875 *********************
--    10000  10999   5155 *******************
--    11000  11999   4371 ****************
--    12000  12999   3728 *************
--    13000  13999   3204 ***********
--    14000  14999   2772 **********
--    15000  15999   2317 ********
--    16000  16999   2018 *******
--    17000  17999   1690 ******
--    18000  18999   1484 *****
--    19000  19999   1123 ****
--    20000  20999   1026 ***
--    21000  21999    803 **
--    22000  22999    679 **
--    23000  23999    575 **
--    24000  24999    492 *
--    25000  25999    351 *
--    26000  26999    314 *
--    27000  27999    323 *
--    28000  28999    328 *
--    29000  29999    289 *
--    30000  30999    235 
--    31000  31999    214 
--    32000  32999    193 
--    33000  33999    174 
--    34000  34999    150 
--    35000  35999    144 
--    36000  36999    110 
--    37000  37999     99 
--    38000  38999     91 
--    39000  39999     71 
--    40000  40999     77 
--    41000  41999     36 
--    42000  42999     57 
--    43000  43999     38 
--    44000  44999     38 
--    45000  45999     36 
--    46000  46999     22 
--    47000  47999     23 
--    48000  48999      3 
-- Finished stage 'cor-gatekeeper', reset canuIteration.
-- Finished stage 'merylConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'meryl' concurrent execution on Tue Nov 13 21:05:48 2018 with 62.557 GB free disk space (1 processes; 10 concurrently)

    cd correction/0-mercounts
    ./meryl.sh 1 > ./meryl.000001.out 2>&1

-- Finished on Tue Nov 13 21:07:17 2018 (89 seconds) with 62.099 GB free disk space
----------------------------------------
-- Meryl finished successfully.
-- Finished stage 'merylCheck', reset canuIteration.
--
--  16-mers                                                                                           Fraction
--    Occurrences   NumMers                                                                         Unique Total
--       1-     1  77962580 *******************************************************************--> 0.6898 0.0741
--       2-     2  13915978 ********************************************************************** 0.8130 0.1006
--       3-     4   8689914 *******************************************                            0.8625 0.1166
--       5-     7   4412050 **********************                                                 0.9074 0.1377
--       8-    11   2429480 ************                                                           0.9360 0.1588
--      12-    16   1467642 *******                                                                0.9538 0.1783
--      17-    22    948809 ****                                                                   0.9651 0.1964
--      23-    29    653220 ***                                                                    0.9728 0.2130
--      30-    37    470207 **                                                                     0.9782 0.2285
--      38-    46    350924 *                                                                      0.9821 0.2430
--      47-    56    268934 *                                                                      0.9851 0.2567
--      57-    67    211673 *                                                                      0.9874 0.2696
--      68-    79    168982                                                                        0.9892 0.2818
--      80-    92    137902                                                                        0.9907 0.2935
--      93-   106    112994                                                                        0.9919 0.3046
--     107-   121     92549                                                                        0.9929 0.3151
--     122-   137     76900                                                                        0.9937 0.3251
--     138-   154     64532                                                                        0.9943 0.3345
--     155-   172     55861                                                                        0.9949 0.3433
--     173-   191     48301                                                                        0.9954 0.3520
--     192-   211     42765                                                                        0.9958 0.3603
--     212-   232     36360                                                                        0.9962 0.3684
--     233-   254     32568                                                                        0.9965 0.3761
--     255-   277     28628                                                                        0.9968 0.3836
--     278-   301     25305                                                                        0.9970 0.3908
--     302-   326     22661                                                                        0.9973 0.3977
--     327-   352     20425                                                                        0.9975 0.4044
--     353-   379     18355                                                                        0.9976 0.4110
--     380-   407     16045                                                                        0.9978 0.4174
--     408-   436     14556                                                                        0.9979 0.4234
--     437-   466     13189                                                                        0.9981 0.4292
--     467-   497     12227                                                                        0.9982 0.4348
--     498-   529     11102                                                                        0.9983 0.4404
--     530-   562     10130                                                                        0.9984 0.4458
--     563-   596      9328                                                                        0.9985 0.4511
--     597-   631      8373                                                                        0.9986 0.4562
--     632-   667      7893                                                                        0.9986 0.4611
--     668-   704      7132                                                                        0.9987 0.4660
--     705-   742      6518                                                                        0.9988 0.4706
--     743-   781      6132                                                                        0.9988 0.4751
--     782-   821      5615                                                                        0.9989 0.4795
--
--       58824 (max occurrences)
--   973588676 (total mers, non-unique)
--    35053579 (distinct mers, non-unique)
--    77962580 (unique mers)
-- For mhap overlapping, set repeat k-mer threshold to 10515.
--
-- Found 1051551256 16-mers; 113016159 distinct and 77962580 unique.  Largest count 58824.
-- Finished stage 'cor-meryl', reset canuIteration.
--
-- OVERLAPPER (mhap) (correction)
--
-- Set corMhapSensitivity=low based on read coverage of 21725.
--
-- PARAMETERS: hashes=256, minMatches=3, threshold=0.85
--
-- Given 6 GB, can fit 18000 reads per block.
-- For 9 blocks, set stride to 2 blocks.
-- Logging partitioning to 'correction/1-overlapper/partitioning.log'.
-- Configured 8 mhap precompute jobs.
-- Configured 17 mhap overlap jobs.
-- Finished stage 'cor-mhapConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'cormhap' concurrent execution on Tue Nov 13 21:07:20 2018 with 62.556 GB free disk space (8 processes; 4 concurrently)

    cd correction/1-overlapper
    ./precompute.sh 1 > ./precompute.000001.out 2>&1
    ./precompute.sh 2 > ./precompute.000002.out 2>&1
    ./precompute.sh 3 > ./precompute.000003.out 2>&1
    ./precompute.sh 4 > ./precompute.000004.out 2>&1
    ./precompute.sh 5 > ./precompute.000005.out 2>&1
    ./precompute.sh 6 > ./precompute.000006.out 2>&1
    ./precompute.sh 7 > ./precompute.000007.out 2>&1
    ./precompute.sh 8 > ./precompute.000008.out 2>&1

-- Finished on Tue Nov 13 21:07:22 2018 (2 seconds) with 61.545 GB free disk space
----------------------------------------
--
-- Mhap precompute jobs failed, retry.
--   job correction/1-overlapper/blocks/000001.dat FAILED.
--   job correction/1-overlapper/blocks/000002.dat FAILED.
--   job correction/1-overlapper/blocks/000003.dat FAILED.
--   job correction/1-overlapper/blocks/000004.dat FAILED.
--   job correction/1-overlapper/blocks/000005.dat FAILED.
--   job correction/1-overlapper/blocks/000006.dat FAILED.
--   job correction/1-overlapper/blocks/000007.dat FAILED.
--   job correction/1-overlapper/blocks/000008.dat FAILED.
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'cormhap' concurrent execution on Tue Nov 13 21:07:22 2018 with 61.545 GB free disk space (8 processes; 4 concurrently)

    cd correction/1-overlapper
    ./precompute.sh 1 > ./precompute.000001.out 2>&1
    ./precompute.sh 2 > ./precompute.000002.out 2>&1
    ./precompute.sh 3 > ./precompute.000003.out 2>&1
    ./precompute.sh 4 > ./precompute.000004.out 2>&1
    ./precompute.sh 5 > ./precompute.000005.out 2>&1
    ./precompute.sh 6 > ./precompute.000006.out 2>&1
    ./precompute.sh 7 > ./precompute.000007.out 2>&1
    ./precompute.sh 8 > ./precompute.000008.out 2>&1

-- Finished on Tue Nov 13 21:07:25 2018 (3 seconds) with 61.545 GB free disk space
----------------------------------------
--
-- Mhap precompute jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/blocks/000001.dat FAILED.
--   job correction/1-overlapper/blocks/000002.dat FAILED.
--   job correction/1-overlapper/blocks/000003.dat FAILED.
--   job correction/1-overlapper/blocks/000004.dat FAILED.
--   job correction/1-overlapper/blocks/000005.dat FAILED.
--   job correction/1-overlapper/blocks/000006.dat FAILED.
--   job correction/1-overlapper/blocks/000007.dat FAILED.
--   job correction/1-overlapper/blocks/000008.dat FAILED.
--

ABORT:
ABORT: Canu 1.6
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```
I am new to Linux, could anyone help me about this error? Thank you.

**Comment by skoren** [comment]
You probably already have a canu installation in your path while your new install is not in the path. Provide the full path to your downloaded Canu location (e.g. ```/full/path/to/where/you/extracted/canu-1.8/*/bin/canu```).

**Comment by piiboo** [comment]
Thank you skoren, I managed to find the canu 1.6 and uninstalled it, then I install canu 1.8 at the location I know. Then I run it again but still without success, is it related to the java version mentioned in previous issues? Here is the log when I run canu agian:

canu-1.8/*/bin/canu -d lambdarun -p lambdaDevono genomeSize=48.5k -nanopore-raw *.fastq.gz
-- Canu 1.8
--
-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
-- 
-- Koren S, Rhie A, Walenz BP, Dilthey AT, Bickhart DM, Kingan SB, Hiendleder S, Williams JL, Smith TPL, Phillippy AM.
-- De novo assembly of haplotype-resolved genomes with trio binning.
-- Nat Biotechnol. 2018
-- https//doi.org/10.1038/nbt.4277
-- 
-- Read and contig alignments during correction, consensus and GFA building use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_192' (from 'java') with -d64 support.
-- Detected gnuplot version '5.2 patchlevel 2   ' (from 'gnuplot') and image format 'png'.
-- Detected 40 CPUs and 126 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |     total usage     algorithm
--        -------  ------  --------   --------  -----------------  -----------------------------
-- Local: meryl     12 GB    4 CPUs x  10 jobs   120 GB   40 CPUs  (k-mer counting)
-- Local: hap        8 GB    4 CPUs x  10 jobs    80 GB   40 CPUs  (read-to-haplotype assignment)
-- Local: cormhap    6 GB   10 CPUs x   4 jobs    24 GB   40 CPUs  (overlap detection with mhap)
-- Local: obtovl     4 GB    8 CPUs x   5 jobs    20 GB   40 CPUs  (overlap detection)
-- Local: utgovl     4 GB    8 CPUs x   5 jobs    20 GB   40 CPUs  (overlap detection)
-- Local: ovb        4 GB    1 CPU  x  31 jobs   124 GB   31 CPUs  (overlap store bucketizer)
-- Local: ovs        8 GB    1 CPU  x  15 jobs   120 GB   15 CPUs  (overlap store sorting)
-- Local: red        8 GB    4 CPUs x  10 jobs    80 GB   40 CPUs  (read error detection)
-- Local: oea        4 GB    1 CPU  x  31 jobs   124 GB   31 CPUs  (overlap error adjustment)
-- Local: bat       16 GB    4 CPUs x   1 job     16 GB    4 CPUs  (contig construction with bogart)
-- Local: gfa        8 GB    4 CPUs x   1 job      8 GB    4 CPUs  (GFA alignment and processing)
--
-- Found Nanopore uncorrected reads in the input files.
--
-- Generating assembly 'lambdaDevono' in '/home/geneious/lambdarun'
--
-- Parameters:
--
--  genomeSize        48500
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1200 ( 12.00%)
--    utgOvlErrorRate 0.1200 ( 12.00%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1200 ( 12.00%)
--    utgErrorRate    0.1200 ( 12.00%)
--    cnsErrorRate    0.2000 ( 20.00%)
--
--
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Wed Nov 14 10:53:12 2018 with 61.963 GB free disk space

    cd .
    /home/geneious/canu-1.8/Linux-amd64/bin/sqStoreCreate \
      -o ./lambdaDevono.seqStore.BUILDING \
      -minlength 1000 \
      ./lambdaDevono.seqStore.ssi \
    > ./lambdaDevono.seqStore.BUILDING.err 2>&1

-- Finished on Wed Nov 14 10:53:34 2018 (22 seconds) with 61.667 GB free disk space
----------------------------------------
--
-- In sequence store './lambdaDevono.seqStore':
--   Found 141265 reads.
--   Found 1053670231 bases (21725.15 times coverage).
--
--   Read length histogram (one '*' equals 270.92 reads):
--     1000   1999  18965 **********************************************************************
--     2000   2999  17182 ***************************************************************
--     3000   3999  15155 *******************************************************
--     4000   4999  13015 ************************************************
--     5000   5999  11302 *****************************************
--     6000   6999   9630 ***********************************
--     7000   7999   8212 ******************************
--     8000   8999   7076 **************************
--     9000   9999   5875 *********************
--    10000  10999   5155 *******************
--    11000  11999   4371 ****************
--    12000  12999   3728 *************
--    13000  13999   3204 ***********
--    14000  14999   2772 **********
--    15000  15999   2317 ********
--    16000  16999   2018 *******
--    17000  17999   1690 ******
--    18000  18999   1484 *****
--    19000  19999   1123 ****
--    20000  20999   1026 ***
--    21000  21999    803 **
--    22000  22999    679 **
--    23000  23999    575 **
--    24000  24999    492 *
--    25000  25999    351 *
--    26000  26999    314 *
--    27000  27999    323 *
--    28000  28999    328 *
--    29000  29999    289 *
--    30000  30999    235 
--    31000  31999    214 
--    32000  32999    193 
--    33000  33999    174 
--    34000  34999    150 
--    35000  35999    144 
--    36000  36999    110 
--    37000  37999     99 
--    38000  38999     91 
--    39000  39999     71 
--    40000  40999     77 
--    41000  41999     36 
--    42000  42999     57 
--    43000  43999     38 
--    44000  44999     38 
--    45000  45999     36 
--    46000  46999     22 
--    47000  47999     23 
--    48000  48999      3 
----------------------------------------
-- Starting command on Wed Nov 14 10:53:36 2018 with 61.666 GB free disk space

    cd correction/0-mercounts
    ./meryl-configure.sh \
    > ./meryl-configure.err 2>&1

-- Finished on Wed Nov 14 10:53:36 2018 (lickety-split) with 61.666 GB free disk space
----------------------------------------
--  segments   memory batches
--  -------- -------- -------
--        01  2.50 GB       1
--        02  1.38 GB       1
--        04  0.69 GB       1
--        06  0.50 GB       1
--        08  0.38 GB       1
--
--  For 141265 reads with 1053670231 bases, limit to 10 batches.
--  Will count kmers using 01 jobs, each using 4 GB and 4 threads.
--
-- Finished stage 'merylConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'meryl' concurrent execution on Wed Nov 14 10:53:36 2018 with 61.666 GB free disk space (1 processes; 10 concurrently)

    cd correction/0-mercounts
    ./meryl-count.sh 1 > ./meryl-count.000001.out 2>&1

-- Finished on Wed Nov 14 10:54:55 2018 (79 seconds) with 61.154 GB free disk space
----------------------------------------
-- Found 1 Kmer counting (meryl) outputs.
-- Finished stage 'cor-merylCountCheck', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'meryl' concurrent execution on Wed Nov 14 10:54:55 2018 with 61.154 GB free disk space (1 processes; 10 concurrently)

    cd correction/0-mercounts
    ./meryl-process.sh 1 > ./meryl-process.000001.out 2>&1

-- Finished on Wed Nov 14 10:55:14 2018 (19 seconds) with 61.5 GB free disk space
----------------------------------------
--
--  16-mers                                                                                           Fraction
--    Occurrences   NumMers                                                                         Unique Total
--       1-     1  77962580 *******************************************************************--> 0.6898 0.0741
--       2-     2  13915978 ********************************************************************** 0.8130 0.1006
--       3-     4   8689914 *******************************************                            0.8625 0.1166
--       5-     7   4412050 **********************                                                 0.9074 0.1377
--       8-    11   2429480 ************                                                           0.9360 0.1588
--      12-    16   1467642 *******                                                                0.9538 0.1783
--      17-    22    948809 ****                                                                   0.9651 0.1964
--      23-    29    653220 ***                                                                    0.9728 0.2130
--      30-    37    470207 **                                                                     0.9782 0.2285
--      38-    46    350924 *                                                                      0.9821 0.2430
--      47-    56    268934 *                                                                      0.9851 0.2567
--      57-    67    211673 *                                                                      0.9874 0.2696
--      68-    79    168982                                                                        0.9892 0.2818
--      80-    92    137902                                                                        0.9907 0.2935
--      93-   106    112994                                                                        0.9919 0.3046
--     107-   121     92549                                                                        0.9929 0.3151
--     122-   137     76900                                                                        0.9937 0.3251
--     138-   154     64532                                                                        0.9943 0.3345
--     155-   172     55861                                                                        0.9949 0.3433
--     173-   191     48301                                                                        0.9954 0.3520
--     192-   211     42765                                                                        0.9958 0.3603
--     212-   232     36360                                                                        0.9962 0.3684
--     233-   254     32568                                                                        0.9965 0.3761
--     255-   277     28628                                                                        0.9968 0.3836
--     278-   301     25305                                                                        0.9970 0.3908
--     302-   326     22661                                                                        0.9973 0.3977
--     327-   352     20425                                                                        0.9975 0.4044
--     353-   379     18355                                                                        0.9976 0.4110
--     380-   407     16045                                                                        0.9978 0.4174
--     408-   436     14556                                                                        0.9979 0.4234
--     437-   466     13189                                                                        0.9981 0.4292
--     467-   497     12227                                                                        0.9982 0.4348
--     498-   529     11102                                                                        0.9983 0.4404
--     530-   562     10130                                                                        0.9984 0.4458
--     563-   596      9328                                                                        0.9985 0.4511
--     597-   631      8373                                                                        0.9986 0.4562
--     632-   667      7893                                                                        0.9986 0.4611
--     668-   704      7132                                                                        0.9987 0.4660
--     705-   742      6518                                                                        0.9988 0.4706
--     743-   781      6132                                                                        0.9988 0.4751
--     782-   821      5615                                                                        0.9989 0.4795
--
--           0 (max occurrences)
--           0 (total mers, non-unique)
--           0 (distinct mers, non-unique)
--           0 (unique mers)
-- Finished stage 'meryl-process', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'cormhap' concurrent execution on Wed Nov 14 10:55:15 2018 with 61.5 GB free disk space (8 processes; 4 concurrently)

    cd correction/1-overlapper
    ./precompute.sh 1 > ./precompute.000001.out 2>&1
    ./precompute.sh 2 > ./precompute.000002.out 2>&1
    ./precompute.sh 3 > ./precompute.000003.out 2>&1
    ./precompute.sh 4 > ./precompute.000004.out 2>&1
    ./precompute.sh 5 > ./precompute.000005.out 2>&1
    ./precompute.sh 6 > ./precompute.000006.out 2>&1
    ./precompute.sh 7 > ./precompute.000007.out 2>&1
    ./precompute.sh 8 > ./precompute.000008.out 2>&1

-- Finished on Wed Nov 14 10:55:15 2018 (furiously fast) with 61.5 GB free disk space
----------------------------------------
--
-- Mhap precompute jobs failed, retry.
--   job correction/1-overlapper/blocks/000001.dat FAILED.
--   job correction/1-overlapper/blocks/000002.dat FAILED.
--   job correction/1-overlapper/blocks/000003.dat FAILED.
--   job correction/1-overlapper/blocks/000004.dat FAILED.
--   job correction/1-overlapper/blocks/000005.dat FAILED.
--   job correction/1-overlapper/blocks/000006.dat FAILED.
--   job correction/1-overlapper/blocks/000007.dat FAILED.
--   job correction/1-overlapper/blocks/000008.dat FAILED.
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'cormhap' concurrent execution on Wed Nov 14 10:55:15 2018 with 61.5 GB free disk space (8 processes; 4 concurrently)

    cd correction/1-overlapper
    ./precompute.sh 1 > ./precompute.000001.out 2>&1
    ./precompute.sh 2 > ./precompute.000002.out 2>&1
    ./precompute.sh 3 > ./precompute.000003.out 2>&1
    ./precompute.sh 4 > ./precompute.000004.out 2>&1
    ./precompute.sh 5 > ./precompute.000005.out 2>&1
    ./precompute.sh 6 > ./precompute.000006.out 2>&1
    ./precompute.sh 7 > ./precompute.000007.out 2>&1
    ./precompute.sh 8 > ./precompute.000008.out 2>&1

-- Finished on Wed Nov 14 10:55:15 2018 (in the blink of an eye) with 61.5 GB free disk space
----------------------------------------
--
-- Mhap precompute jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/blocks/000001.dat FAILED.
--   job correction/1-overlapper/blocks/000002.dat FAILED.
--   job correction/1-overlapper/blocks/000003.dat FAILED.
--   job correction/1-overlapper/blocks/000004.dat FAILED.
--   job correction/1-overlapper/blocks/000005.dat FAILED.
--   job correction/1-overlapper/blocks/000006.dat FAILED.
--   job correction/1-overlapper/blocks/000007.dat FAILED.
--   job correction/1-overlapper/blocks/000008.dat FAILED.
--

ABORT:
ABORT: Canu 1.8
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:

**Comment by piiboo** [comment]
Sorry I didn't realize your suggestion. I provided full path to canu and now it works well. Thank you.
