### ISSUE TITLE
unitigging/3-overlapErrorAdjustment RED job fails repeatedly

### ISSUE THREAD

**Issue by kfriesen2** [marbl/canu#1156]
CANU 1.8.0_121 on slurm grid @ SciNet
I've had this 'job 62' fail 5+ times, and apparently my adjustments aren't working. I'm not sure what to try next. Here is my latest command, followed by typical outputs.

canu \
gridOptionsExecutive="--partition=mem --mem-per-cpu=24g --time=7-00:00:00 --mem=10g" \
correctedErrorRate=0.085 \
gridOptionsmeryl="--partition=mem" \
'stageDirectory=$TMPDIR' \
gridOptionsCOR="--partition=mem --time=7-00:00:00" gridOptions="--time=48:00:00" \
gridOptionsRED="--partition=mem --time=7-00:00:00 --mem=10g" gridOptions="--time=48:00:00" \
-p ado_ceres_canu18 -d ado_ceres_canu18 genomesize=2150m \
-pacbio-raw /project/cricket_gen/ado_house/reads/*.fastq

unitigging/3-overlapErrorAdjustment/red.jobSubmit-01.sh
```#!/bin/sh

sbatch \
  --mem-per-cpu=2g --cpus-per-task=8 --time=48:00:00 --partition=mem --time=7-00:00:00 --mem=10g -o red.%A_%a.out \
  -D `pwd` -J "red_ado_ceres_canu18" \
  -a 62-62 \
  ./red.sh 0 \
> ./red.jobSubmit-01.out 2>&1
```
canu-scripts/canu.46.out
```Found perl:
   /usr/bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /software/7/apps/java/1.8.0_121/bin/java
   java version "1.8.0_121"

Found canu:
   /software/7/apps/canu/1.8/bin/canu
   Canu 1.8

-- Canu 1.8
--
-- CITATIONS
[                   ]
--
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_121' (from 'java') with -d64 support.
-- Detected gnuplot version '4.6 patchlevel 2   ' (from 'gnuplot') and image format 'png'.
-- Detected 120 CPUs and 1512 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /usr/bin/sinfo.
-- Detected Slurm with 'MaxArraySize' limited to 1000 jobs.
--
-- Found   5 hosts with 120 cores and 1494 GB memory under Slurm control.
-- Found   1 host  with  40 cores and   94 GB memory under Slurm control.
-- Found  64 hosts with  40 cores and  125 GB memory under Slurm control.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl     25 GB    8 CPUs  (k-mer counting)
-- Grid:  hap       16 GB   40 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   23 GB   10 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    24 GB   10 CPUs  (overlap detection)
-- Grid:  utgovl    24 GB   10 CPUs  (overlap detection)
-- Grid:  ovb        4 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       32 GB    1 CPU   (overlap store sorting)
-- Grid:  red       16 GB    8 CPUs  (read error detection)
-- Grid:  oea        8 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      512 GB   32 CPUs  (contig construction with bogart)
-- Grid:  gfa       32 GB   32 CPUs  (GFA alignment and processing)
--
-- In 'ado_ceres_canu18.seqStore', found PacBio reads:
--   Raw:        17509240
--   Corrected:  10690904
--   Trimmed:    10072881
--
-- Generating assembly 'ado_ceres_canu18' in '/project/cricket_gen/ado_house/asmb/ado_ceres_canu18'
--
-- Parameters:
--
--  genomeSize        2150000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0850 (  8.50%)
--    utgOvlErrorRate 0.0850 (  8.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0850 (  8.50%)
--    utgErrorRate    0.0850 (  8.50%)
--    cnsErrorRate    0.0850 (  8.50%)
--
--
-- BEGIN ASSEMBLY
--
--
-- Read error detection jobs failed, tried 2 times, giving up.
--   job 00062.red FAILED.
--

ABORT:
ABORT: Canu 1.8
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```
unitigging/3-overlapErrorAdjustment/red.425032_62.out
```Found perl:
   /usr/bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /software/7/apps/java/1.8.0_121/bin/java
   java version "1.8.0_121"

Found canu:
   /software/7/apps/canu/1.8/bin/canu
   Canu 1.8

Running job 62 based on SLURM_ARRAY_TASK_ID=62 and offset=0.
Read_Frags()-- Loading target reads 10420980 through 10645946 with 500225109 bases.
Read_Frags()-- 6.054 GB for bases, votes and info.

Read_Olaps()-- Loading 570361243 overlaps.
/var/spool/slurmd/job425032/slurm_script: line 473: 41558 Killed                  $bin/findErrors -S ../../ado_ceres_canu18.seqStore -O ../ado_ceres_canu18.ovlStore -R $minid $maxid -e 0.085 -l 500 -o ./$jobid.red.WORKING -t 8
slurmstepd: error: Detected 1 oom-kill event(s) in step 425032.batch cgroup.
```

**Comment by skoren** [comment]
Your job is getting killed by the grid. Based on the Canu config, it wants to use 16gb but you've set the request to be 10gb. Setting gridOptions doesn't change the resources a job will use, you need to set redMemory at the same time. Either don't set gridOptionsRED or increase the memory request to 20gb and I expect the job will run.

**Comment by kfriesen2** [comment]
Sergey, thanks for the response. 
Yeah that 10gb was the last thing I tried, based on something I read somewhere. Here is my original command, which I just restarted. I didn't delete anything this time, just ran it, and it ran overnight.

canu \
gridOptionsExecutive="--partition=mem --mem-per-cpu=24g --time=7-00:00:00" \
correctedErrorRate=0.085 \
gridOptionsmeryl="--partition=mem" \
'stageDirectory=$TMPDIR' \
gridOptionsCOR="--partition=mem --time=7-00:00:00" gridOptions="--time=48:00:00" \
-p ado_ceres_canu18 -d ado_ceres_canu18 genomesize=2150m \
-pacbio-raw /project/cricket_gen/ado_house/reads/*.fastq

Before, I had bucketizing issues, and Ben Rosen gave me good advice, about what to delete before restarting, and holding the executive job to avoid duplicate job issues. This last hangup with job 62, I would delete the failed outputs and restart, with subsequent short/failed jobs. Did I not need to clean up for this process? It's not clear to me why it worked now, but not before.

**Comment by skoren** [comment]
Your bucketizing issue is due to the broken SLURM dependencies on your cluster, I'm not sure how that happens, I've never seen it before but manually holding the job works. It submits jobs with a dependency before the dependency finishes running.

Cleaning up doesn't matter. When you ran before how much memory were you giving the job? I'd guess it didn't run before because it had insufficient memory and now it ran since it properly requesting the needed memory.

**Comment by kfriesen2** [comment]
Thanks, Sergey. To clarify, you dont need to remove failed *.out files, or maybe *.sh files that didn't finish?

The command above that I restarted yesterday, that ran overnight, is the original command. I also deleted files and successfully restarted several 1-overlapper/001/ jobs with this command. But the same command wouldn't work when deleting files and restarting /unitigging/3-overlapErrorAdjustment RED jobs.

**Comment by skoren** [comment]
You generally don't need to remove anything to re-run a failed job. If you change parameters you would need to remove the shell script or the whole folder (e.g. if you changed redMemory you would have a different number of partitions).

I am confused about your comment that your previous command ran overnight and worked now but also that it didn't work when restarting 3-overlapErrorAdjustment? Did your assembly run the failed red job successfully on the restart? If it failed before, it might have been a different error than out of memory on your grid, the log would give the information on it.

**Comment by kfriesen2** [comment]
I was surprised it took off and ran yesterday, because I tried rerun that job multiple times. with that command, without success. (And then started monkeying with the command.) In my mind the logged errors were the same. But you are probably right, that it was a different error. 
Thanks for the help. This can be closed now
