### ISSUE TITLE
trimming step: why is the output of a fastq?

### ISSUE THREAD

**Issue by albodrug** [marbl/canu#116]
I have troubles understanding what the trimming step does. I understand that it will detect suspicious regions thanks to overlapping regions that either have too low coverage or too high coverage and keep the largest portion of the read after splitting the read. 
Apart from remaining adaptors, in what other cases would trimming split reads? Could a tandem large repeat contained in a read cause its splitting?
Why is the output a fastq even when inputting a fasta into correction step?

Thanks

**Comment by skoren** [comment]
The best description is the OBT algorithm in this paper: http://bioinformatics.oxfordjournals.org/content/24/24/2818.full though quite a bit has changed for long reads vs what is described.

The trimming step does two functions. First it trims all reads to the largest good region to ensure that any overlaps found in subsequent steps go to the end of a read. For example, if correction added spurious bases to the end of a read, those would be trimmed off. A read can also be trimmed if regions of it have no support from other data as that is likely to be a chimera or bad read. The second step breaks reads at missed SMRTbell adapters. It looks for a palindromic signature to break. A repeat should not cause splitting. All the read fates are logged in asm.1.trimReads.log and asm.2.splitReads.log, you can look at how much and at what positions a read was trimmed/split.

**Comment by brianwalenz** [comment]
The SMRTbell adapter detection requires a specific signature that, IIRC, has tripped up one assembly in the past (we never validated what the issue was; the assembly had other issues).  Check trimming.html for 'subread' numbers.  If abnormally high, feel free to reopen or make a new issue.

As for FASTQ vs FASTA, thanks for noticing.  I've changed it to output FASTA.gz.
