### ISSUE TITLE
SLURM resource allocation problem

### ISSUE THREAD

**Issue by kalbflei** [marbl/canu#1164]
Hello,

      I am trying to run canu on the XSEDE Comet cluster.  I have a limit of 35000 cpu hours for my allocation.  

When I run 

canu -p a3Rat -d a3Rat-pacbio genomeSize=2.8g -pacbio-raw A3pacbio.subreads.fa.gz gridOptions="-t 01:00:00"

Ultimately, I fail and get this at the tail of the canu.out log

CRASH:
CRASH: Canu snapshot v1.8 +44 changes (r9254 a50e26a75ffccc529bd944b7adb291e2b6e1c24b)
CRASH: Please panic, this is abnormal.
ABORT:
CRASH:   Failed to submit batch jobs.
CRASH:
CRASH: Failed at /home/kalbflei/canu/Linux-amd64/bin/../lib/site_perl/canu/Execution.pm line 1235
CRASH: 	canu::Execution::submitOrRunParallelJob('a3Rat', 'cormhap', 'correction/1-overlapper', 'mhap', 1, 2, 3, 4, 5, ...) called at /home/kalbflei/canu/Linux-amd64/bin/../lib/site_perl/canu/OverlapMhap.pm line 774
CRASH: 	canu::OverlapMhap::mhapCheck('a3Rat', 'cor', 'partial') called at /home/kalbflei/canu/Linux-amd64/bin/canu line 600
CRASH: 	main::overlap('a3Rat', 'cor') called at /home/kalbflei/canu/Linux-amd64/bin/canu line 808
CRASH: 
CRASH: Last 50 lines of the relevant log file (correction/1-overlapper/mhap.jobSubmit-01.out):
CRASH:
CRASH: sbatch: error: bank_limit plugin: The requested time can not exceed the available balance.
CRASH: Requested SUs: 51022
CRASH: Allocation limit group SUs: 35000
CRASH: Allocation limit user SUs: 35000
CRASH: Allocation used group SUs: 3550
CRASH: Allocation used user SUs: 3550
CRASH: Allocation available group SUs: 31450
CRASH: Allocation available user SUs: 31450
CRASH: Allocation running/queued group SUs: 0
CRASH: Allocation running/queued user SUs: 0
CRASH: Allocation completed today group SUs: 11
CRASH: Allocation completed today user SUs: 11
CRASH: sbatch: error: Batch job submission failed: Requested time limit is invalid (missing or exceeds some limit)

When alter the time to get in under my resource limit, and run 

canu -p a3Rat -d a3Rat-pacbio genomeSize=2.8g -pacbio-raw A3pacbio.subreads.fa.gz gridOptions="-t 00:30:00"

I get 

CRASH:
CRASH: Canu snapshot v1.8 +44 changes (r9254 a50e26a75ffccc529bd944b7adb291e2b6e1c24b)
CRASH: Please panic, this is abnormal.
ABORT:
CRASH:   Failed to submit batch jobs.
CRASH:
CRASH: Failed at /home/kalbflei/canu/Linux-amd64/bin/../lib/site_perl/canu/Execution.pm line 1235
CRASH: 	canu::Execution::submitOrRunParallelJob('a3Rat', 'cormhap', 'correction/1-overlapper', 'mhap', 1, 2, 3, 4, 5, ...) called at /home/kalbflei/canu/Linux-amd64/bin/../lib/site_perl/canu/OverlapMhap.pm line 774
CRASH: 	canu::OverlapMhap::mhapCheck('a3Rat', 'cor', 'partial') called at /home/kalbflei/canu/Linux-amd64/bin/canu line 600
CRASH: 	main::overlap('a3Rat', 'cor') called at /home/kalbflei/canu/Linux-amd64/bin/canu line 808
CRASH: 
CRASH: Last 50 lines of the relevant log file (correction/1-overlapper/mhap.jobSubmit-01.out):
CRASH:
CRASH: sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)
CRASH:

Any suggestions your could provide would be greatly appreciated.

Best regards,

Ted

**Comment by brianwalenz** [comment]
For the record, adding `-p shared` to the gridOptions resolved the problem.  It seems XSEDE Comet, by default, allocates entire nodes to jobs.  Not sure which limit was exceeded though.  https://portal.xsede.org/sdsc-comet

**Comment by kalbflei** [comment]
Brian,

     Looks like your suggestion of adding the gridOption of -p shared did the trick.  The full command like looks like

canu -p a3Rat -d a3Rat-pacbio genomeSize=2.8g -pacbio-raw A3pacbio.subreads.fa.gz gridOptions="-t 48:00:00 -p shared" 

and seems to work!
