### ISSUE TITLE
Canu on local assembly

### ISSUE THREAD

**Issue by woodoo46** [marbl/canu#1169]
Hi Canu developers,

I am wondering if I can use Canu doing local assembly. For example, we extracted a few reads on certain regions, and would like to assemble these reads. If we can, which parameters we should pay more attention to? 

Thanks.

George

**Comment by skoren** [comment]
You can assemble local regions, are you co-assembling them or running each region individually? I'd suggest running them individually and setting the genomeSize to what your expect the region to be and otherwise use whatever parameters the FAQ recommends for your sequencing data type.
