### ISSUE TITLE
assembly command

### ISSUE THREAD

**Issue by wisekh6** [marbl/canu#117]
Hello,

I wonder if I can ask you how I could use canu with PacBio data in order to perform assembly.
If it was answered somewhere, I would be very sorry, and please direct me to the site.

Regarding my question, 
The PacBio files I downloaded include 
1.  "human.bax.h5"
2.  "human.ccs.fastq"
2. "human.filtered_subreads.fastq", 
3. "human.filtered_subreads.longest.fastq".

My goal is to assemble with all information available in the above files.
I thought that I would be able to run canu by using:
canu -assemble -p human -d human-auto genomeSize=3.1g -pacbio-raw human.filtered_subreads.fastq -pacbio-corrected human.ccs.fastq
But, I am not sure if this command would be appropriate, of if there would be a better way to assemble.

Your advice will be highly appreciated!!!

Best regards,

**Comment by skoren** [comment]
You cannot mix correct and raw read in the input. The ccs reads are also likely to be much shorter and are unlikely to help assembly, I would leave them out. 

You can follow the tutorial on the quick start page:
http://canu.readthedocs.org/en/stable/quick-start.html#correct-trim-and-assemble

You don't need to specify -assemble, it will run all three steps for you (correct, trim, assemble). If you do want to include the ccs, you'd have to follow the tutorial of running each step individually:
http://canu.readthedocs.org/en/stable/quick-start.html#correct-trim-and-assemble-manually
to correct the raw reads and then specify the corrected reads and ccs reads as pacbio-corrected data.

**Comment by wisekh6** [comment]
Dear Sergey,

Thank you so much for your quick response.

----------------------------
to correct the raw reads and then specify the corrected reads and ccs reads as pacbio-corrected data.
----------------------------
So, does it mean that I would be able to use multiple '-pacbio-corrected' parameters (i.e. -pacbio-corrected ccs.fastq -pacbio-corrected corrected.fastq) in order to specify both corrected reads and ccs reads as pacbio-corrected data when assembling? 

Thank you in advance,

HK

**Comment by skoren** [comment]
Yes
