### ISSUE TITLE
Local assembly error

### ISSUE THREAD

**Issue by woodoo46** [marbl/canu#1170]
Hi,

I tried to do local assembly on a about 100k region, and got this error message:

sh: line 6: 187389 Floating point exception/largeprojects/mytools/canu/canu-1.7.1/Linux-amd64/bin/overlapInCorePartition -G ../Sample.gkpStore -hl 85312000 -rl 1000000000 -ol 500 -o ./Sample.partition > ./Sample.partition.err 2>&1

The region is supposed to be around 60k.

Thanks.

**Comment by skoren** [comment]
You've probably got no overlaps. post the full output from the Canu run up to that point and upgrade to 1.8 while you're at it.

**Comment by woodoo46** [comment]
Yes you are right, the estimate of the size was wrong, and after upgrade to 1.8; the program went through smoothly.

Thanks!
