### ISSUE TITLE
meryl fails to configure

### ISSUE THREAD

**Issue by GeoMicroSoares** [marbl/canu#1172]
Hi there,

I'm getting the following error from running canu -correct:
```
ERROR:
ERROR:  Failed with exit code 126.  (rc=32256)
ERROR:

CRASH:
CRASH: Canu snapshot v1.8 +44 changes (r9254 a50e26a75ffccc529bd944b7adb291e2b6e1c24b)
CRASH: Please panic, this is abnormal.
ABORT:
CRASH:   meryl failed to configure.
CRASH:
CRASH: Failed at /home/andre/canu/Linux-amd64/bin/../lib/site_perl/canu/Meryl.pm line 393.
CRASH: 	canu::Meryl::merylConfigure('ERR2264279', 'cor') called at /home/andre/canu/Linux-amd64/bin/canu line 804
CRASH: 
CRASH: No log file supplied.
CRASH:
```
My full command was:
```        
/home/andre/canu/Linux-amd64/bin/canu -correct \
                -p spl \
                -d out_folder \
                genomeSize=1.5k \
                -nanopore-raw  \
                $out_folder_spl__barcoded.fa
```
My canu version is the latest:
```
/home/andre/canu/Linux-amd64/bin/canu --version
Canu snapshot v1.8 +44 changes (r9254 a50e26a75ffccc529bd944b7adb291e2b6e1c24b)
```
Couldn't get any relevant log files as ```correction/0-mercounts``` only contains ```meryl-configure.sh``` and ```spl.seqStore``` only had an empty errorLog file.

Let me know if you need any other information.

Thanks in advance,
Andr]e

**Comment by brianwalenz** [comment]
Inside correction/0-mercounts/ run meryl-configure.sh by hand - it's small and quick.  Stupidly, Canu deletes the log file just before trying to report the error contained in it.

I'm suspecting problems running the meryl command itself, which could be caused by a faulty installation.  How did you install Canu?

**Comment by brianwalenz** [comment]
Any update?  Success?  Reopen if needed.

**Comment by Freemacl** [comment]
Hi there, I am also experiencing this problem. My installation was from the 1.8 binary distribution. 

When I manually execute the meryl-configure.sh, it prints:
```
Found perl:
   /usr/bin/perl
   This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi

Found java:
   /usr/bin/java
   openjdk version "1.8.0_212"

Found canu:
   /home/claire/bin/canu
   Canu 1.8
```
and then creates an output file in that directory. Re running canu after manually executing that script throws the same error.

**Comment by brianwalenz** [comment]
Are you by chance on PBS or PBSpro?

What file is created and what is in it?

meryl-configure.sh is quite simple, just running a handful of (small) commands.  Can you run any of those by hand?  How about just the 'meryl' command itself (it will just print command line usage).

**Comment by Freemacl** [comment]
This is just being run on a local computer (although I very much appreciate all the support you have added for grid usage).

When I execute the canu command, I don't think meryl-configure.sh is being run as it generates no output file in the 0-mercounts directory. When I run meryl-configure.sh by hand it outputs ecoli.ms16.config.01.out:

```
Counting 133  million canonical 16-mers from 1 input file:
    canu-seqStore: ../../ecoli.seqStore

SIMPLE MODE
-----------
  16-mers
    -> 4294967296 entries for counts up to 65535.
    -> 64 Gbits memory used

  140042151 input bases
    -> expected max count of 560168, needing 5 extra bits.
    -> 20 Gbits memory used
  10 GB memory needed

COMPLEX MODE
------------

prefix     # of   struct   kmers/    segs/     data    total
  bits   prefix   memory   prefix   prefix   memory   memory
------  -------  -------  -------  -------  -------  -------
     1     2  P    64 kB    66 MM  4143  S   517 MB   517 MB
     2     4  P    63 kB    33 MM  2005  S   501 MB   501 MB
     3     8  P    61 kB    16 MM   969  S   484 MB   484 MB
     4    16  P    60 kB  8547 kM   468  S   467 MB   467 MB
     5    32  P    59 kB  4273 kM   226  S   451 MB   451 MB
     6    64  P    60 kB  2136 kM   109  S   435 MB   435 MB
     7   128  P    65 kB  1068 kM    53  S   423 MB   423 MB
     8   256  P    76 kB   534 kM    26  S   415 MB   415 MB
     9   512  P   100 kB   267 kM    13  S   415 MB   415 MB
    10  1024  P   144 kB   133 kM     6  S   383 MB   383 MB  Best Value!
    11  2048  P   240 kB    66 kM     3  S   383 MB   384 MB
    12  4096  P   448 kB    33 kM     2  S   511 MB   512 MB
    13  8192  P   832 kB    16 kM     1  S   511 MB   512 MB
    14    16 kP  1664 kB  8548  M     1  S  1023 MB  1025 MB
    15    32 kP  3328 kB  4274  M     1  S  2047 MB  2050 MB
FINAL CONFIGURATION
-------------------
Configured complex mode for 0.375 GB memory per batch, and up to 1 batch.
Bye.
```

For reference, this is the oxford ecoli data linked to in the quick start section.

**Comment by Freemacl** [comment]
Oh and yes, if I call `meryl` it prints the program usage

**Comment by brianwalenz** [comment]
Very puzzling.

Can you make a new issue for this, and include the canu output from a full restart (that is, delete the current assembly directory).

The `ecoli.ms16.config.01.out` output looks correct.
