### ISSUE TITLE
Next stage beginning before task array is complete

### ISSUE THREAD

**Issue by johnomics** [marbl/canu#1175]
I'm trying to run canu 1.8 on a new cluster running Slurm 17.11.2, using several different nanopore data sets including some we have assembled successfully elsewhere, using vanilla settings:
```
canu -p asm -d asm genomeSize=500000000 -nanopore-raw *fastq.gz
```

At several different stages, canu begins the next stage of the assembly before the previous task array has completed. This has happened for MHAP, correction and trimming overlaps - haven't gone any further. The behaviour is consistent across several assemblies.

It's likely to be a configuration issue with our new cluster, but we can't figure it out, and we are unable to replicate the problem with non-canu test jobs.

Have you ever seen anything like this on your Slurm cluster?

For example, the first pass of correction started a task array and a dependent job:
```
-- 'correctReads.jobSubmit-01.sh' -> job 12639 tasks 1-512.
--
----------------------------------------
-- Starting command on Thu Nov 22 17:33:55 2018 with 2507297.653 GB free disk space

    cd /mnt/lustre/john/asm/canu1.8
    sbatch \
      --depend=afterany:12639 \
      --mem-per-cpu=4g \
      --cpus-per-task=1   \
      -D `pwd` \
      -J 'asm' \
      -o canu-scripts/canu.11.out  canu-scripts/canu.11.sh
Submitted batch job 12640
```

Job 12640 started at 19:08:59:
```
$ sacct -o 'jobid,start,end,exit' -j 12640
       JobID               Start                 End ExitCode
------------ ------------------- ------------------- --------
12640        2018-11-22T19:08:59 2018-11-22T19:09:03      0:0
12640.batch  2018-11-22T19:08:59 2018-11-22T19:09:03      0:0
```

But  array 12639 was not finished at this point. 12640 started exactly when 12639_510 completed, but several other jobs continued to run after that:
```
$ sacct -o 'jobid,start,end,exit' -j 12639 | sort -k3
...
12639_511    2018-11-22T17:47:36 2018-11-22T19:08:39      0:0
12639_511.b+ 2018-11-22T17:47:36 2018-11-22T19:08:39      0:0
12639_367    2018-11-22T17:41:13 2018-11-22T19:08:50      0:0
12639_367.b+ 2018-11-22T17:41:13 2018-11-22T19:08:50      0:0
12639_510    2018-11-22T17:47:35 2018-11-22T19:08:59      0:0
12639_510.b+ 2018-11-22T17:47:35 2018-11-22T19:08:59      0:0
12639_428    2018-11-22T17:43:40 2018-11-22T19:09:09      0:0
12639_428.b+ 2018-11-22T17:43:40 2018-11-22T19:09:09      0:0
12639_270    2018-11-22T17:35:25 2018-11-22T19:09:18      0:0
12639_270.b+ 2018-11-22T17:35:25 2018-11-22T19:09:18      0:0
12639_326    2018-11-22T17:38:53 2018-11-22T19:09:32      0:0
12639_326.b+ 2018-11-22T17:38:53 2018-11-22T19:09:32      0:0
12639_320    2018-11-22T17:38:01 2018-11-22T19:09:45      0:0
12639_320.b+ 2018-11-22T17:38:01 2018-11-22T19:09:45      0:0
12639_292    2018-11-22T17:36:30 2018-11-22T19:10:14      0:0
12639_292.b+ 2018-11-22T17:36:30 2018-11-22T19:10:14      0:0
12639_277    2018-11-22T17:35:46 2018-11-22T19:10:23      0:0
12639_277.b+ 2018-11-22T17:35:46 2018-11-22T19:10:23      0:0
12639_316    2018-11-22T17:37:51 2018-11-22T19:11:56      0:0
12639_316.b+ 2018-11-22T17:37:51 2018-11-22T19:11:56      0:0
12639_279    2018-11-22T17:35:47 2018-11-22T19:13:17      0:0
12639_279.b+ 2018-11-22T17:35:47 2018-11-22T19:13:17      0:0
12639_272    2018-11-22T17:35:30 2018-11-22T19:13:28      0:0
12639_272.b+ 2018-11-22T17:35:30 2018-11-22T19:13:28      0:0
12639_507    2018-11-22T17:47:29 2018-11-22T19:13:30      0:0
12639_507.b+ 2018-11-22T17:47:29 2018-11-22T19:13:30      0:0
12639_273    2018-11-22T17:35:36 2018-11-22T19:13:57      0:0
12639_273.b+ 2018-11-22T17:35:36 2018-11-22T19:13:57      0:0
12639_276    2018-11-22T17:35:39 2018-11-22T19:14:14      0:0
12639_276.b+ 2018-11-22T17:35:39 2018-11-22T19:14:14      0:0
12639_271    2018-11-22T17:35:30 2018-11-22T19:14:53      0:0
12639_271.b+ 2018-11-22T17:35:30 2018-11-22T19:14:53      0:0
12639_278    2018-11-22T17:35:46 2018-11-22T19:15:30      0:0
12639_278.b+ 2018-11-22T17:35:46 2018-11-22T19:15:30      0:0
```

When canu restarted via job 12640, it assumed the still-running jobs failed and tried to rerun them:
```
-- Read correction jobs failed, retry.
--   job 2-correction/results/0270.cns FAILED.
--   job 2-correction/results/0271.cns FAILED.
--   job 2-correction/results/0272.cns FAILED.
--   job 2-correction/results/0273.cns FAILED.
--   job 2-correction/results/0276.cns FAILED.
--   job 2-correction/results/0277.cns FAILED.
--   job 2-correction/results/0278.cns FAILED.
--   job 2-correction/results/0279.cns FAILED.
--   job 2-correction/results/0292.cns FAILED.
--   job 2-correction/results/0316.cns FAILED.
--   job 2-correction/results/0320.cns FAILED.
--   job 2-correction/results/0326.cns FAILED.
--   job 2-correction/results/0428.cns FAILED.
--   job 2-correction/results/0507.cns FAILED.
```

I have similar logs for MHAP and trimming overlap stages, same behaviour. But I can't replicate the behaviour outside of canu; simple test scripts with dependent jobs do complete their task arrays properly before continuing.

Any thoughts you have on this would be greatly appreciated.

Many thanks
John

**Comment by skoren** [comment]
We have seen it on one other Slurm cluster, not restricted to Canu though. The ArrowGrid pipeline was failing in the same way. I wouldn't think it is a config issue as I can't imagine why you'd want to configure job dependencies in this way. I expect it is a bug with some Slurm versions. 

As a workaround, you can always make the main Canu job hold for the user to trigger it. This means you'll have to manually look to see if the array jobs have completed before you release the job but you won't have the failure anymore. Add ```gridOptionsExecutive="--hold"```. No better suggestions than that, post back if you figure out a fix.

**Comment by johnomics** [comment]
Thanks - we haven't solved it yet, but will let you know if we do.

**Comment by skoren** [comment]
FWIW, the working slurm version is 17.02.9 and the failing one is 17.11.3-2. Both are quite old though in terms of releases.

**Comment by johnomics** [comment]
Ah, thank you - which version are you running now?

**Comment by skoren** [comment]
We're still on 17.02.9 which is the one that hasn't had any issues with jobs starting early. Both of the failing ones are ```17.11.*```, maybe that had a bug?

**Comment by johnomics** [comment]
This seems like a plausible bug, although it's going to be a while before we can upgrade and test this:
https://bugs.schedmd.com/show_bug.cgi?id=4802
https://github.com/SchedMD/slurm/commit/f381e4e6abca6ce45709b86989112442487f856a

The remove_job_hash function looked like this in 17.02 and up to 17.11.0.0rc1:
https://github.com/SchedMD/slurm/blob/693fb6b9b41a5ed8e24ce144173a2dbb9e89e5f8/src/slurmctld/job_mgr.c#L2786
https://github.com/SchedMD/slurm/commit/317d633754d7b2b03bc91c5a062c45313f876a43

Then it was rewritten to handle job array and task ids - the rewrite is in 17.11.0:
https://github.com/SchedMD/slurm/blob/5f7c70f51271ec2c26f6751294013b608fddf254/src/slurmctld/job_mgr.c#L2794

But the rewrite missed the last few lines. This was fixed in the bug above, and included in 17.11.4.

When we can get the cluster upgraded, I'll test this and report back.

**Comment by skoren** [comment]
The 17.11.3-2 cluster was recently upgraded to 18.08.3 so will let you know once we have a chance to test dependencies if the issue is fixed.

**Comment by johnomics** [comment]
Our cluster was just upgraded to Slurm 18.08.4 and this problem has now gone away. Thanks for your help tracking this down, and for all your great advice and support this year. Happy holidays!
