### ISSUE TITLE
utgcns failed with abort error

### ISSUE THREAD

**Issue by zhuqian4** [marbl/canu#1176]
i am trying run canu1.7 on a server with 96 core and 512G mem,the system is  centOS 7.4,used cmd is : 

`canu -pacbio-raw /ssd/canu32G/passed.fq.gz -p Ant.all -d Ant-canu corMemory=4 corPartitions=192 corPartitionMin=1000 corThreads=4 useGrid=false genomeSize=350m obtOverlapper=mhap corMhapThreads=4 obtMhapThreads=4 utgOverlapper=mhap utgMhapThreads=4 redThreads=1 oeaThreads=1 batThreads=48 cnsThreads=4 gridEngineMemoryOption="-l vf=MEMORY"`

when i change src/correction/falconsense.C line 370
for (uint32 ii=idMin; `ii<idMax`; ii++)   to for (uint32 ii=idMin;` ii<= idMax`; ii++)

there is an error in utgcns : 
```
----------------------------------------
-- Using slow alignment for consensus (iteration '1').
-- Configured 13 contig and 11 unitig consensus jobs.
--
-- Consensus jobs failed, retry.
--   job utgcns/0008.cns FAILED.
-- Running jobs.  Second attempt out of 2.
----------------------------------------

-- Using slow alignment for consensus (iteration '2').
-- Configured 13 contig and 11 unitig consensus jobs.
--
-- Consensus jobs failed, tried 2 times, giving up.
--   job utgcns/0008.cns FAILED.
--

ABORT:
ABORT: Canu 1.7
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```

![image](https://user-images.githubusercontent.com/36786499/49622870-4342d000-fa06-11e8-8a78-8c387f452555.png)

i change corPartitions=192 to corPartitions=96, restart the job ,it is run success,
and use  `for (uint32 ii=idMin;ii< idMax; ii++)` also run success.
why not used <=? in my mind use < will lost the idMax read ,

 greatly appreciated.

qin z

**Comment by skoren** [comment]
It should be <=, you can see that is corrected in the 1.8 release and the current code. 

You're hitting an unrelated issue due to the addition of more reads into the assembly. It looks like the contig ends up significantly longer than expected causing the consensus error. There have been enough changes between 1.7 and 1.8 that I would say just re-run with 1.8 and see if it succeeds.

**Comment by zhuqian4** [comment]
thanks for your answer
i also run with 1.8 in last weekend ,the job is also failed , 

 `Failed with 'Aborted'; backtrace (libbacktrace):
utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
 (null)::0 in (null)()
 (null)::0 in (null)()
 (null)::0 in (null)()
 (null)::0 in (null)()
 (null)::0 in (null)()
utgcns/libcns/unitigConsensus.C::557 in _Z22generateTemplateStitchP8abAbacusP10tgPositionjdb()
 utgcns/libcns/unitigConsensus.C::786 in _ZN15unitigConsensus13generatePBDAGEP5tgTigcPSt3mapIjP6sqReadSt4lessIjESaISt4pairIKjS4_EEEPS2_IjP10sqReadDataS6_SaIS7_IS8_SE_EEE()
 utgcns/utgcns.C::522 in main()
   (null)::0 in (null)()
 (null)::0 in (null)()
  (null)::0 in (null)()
     ./consensus.sh: line 100: 148345 Aborted                 $bin/utgcns -S ../Ant.all.${tag}Store/partitionedReads.seqStore -T ../Ant.all.${tag}Store 1 $jobid -O ./${tag}cns/$jobid.cns.WORKING         -maxcoverage 40 -e 0.075 -pbdagcon -edlib -threads 8`

Is there a problem with the genome data?

TKS
qin z

**Comment by brianwalenz** [comment]
Idle.
