### ISSUE TITLE
can i increase the correctedErrorRate 

### ISSUE THREAD

**Issue by nagendranipgr** [marbl/canu#1179]
Actually we have very low coverage raw data from nanopore. we did the correction step with default parameters and then ran trim-assemble
 /canu -correct -d canu_correct -p canuAssembly genomeSize=430m useGrid=false -nanopore-raw nanopore_combined.fastq

canu -trim-assemble -d canu_assembly/ -p canuAssembly genomeSize=430M useGrid=false -nanopore-corrected canuAssembly.correctedReads.fasta.gz

But resulted a very bad assembly so we changed the parameters a little bit for the trim-assemble step as follows

canu  -trim-assemble -d canu_assembly/ -p canuAssembly genomeSize=430m useGrid=false  rawErrorRate=0.900  minReadLength=500  correctedErrorRate=0.288  minOverlapLength=500 -nanopore-corrected ../canuAssembly.correctedReads.fasta.gz
this gave a good quality assembly but is it a good idea to increase correctedErrorRate to this extend?

**Comment by skoren** [comment]
Generally, it is OK to increase the error rate but you might introduce some more mis-assemblies than the default. Canu won't necessarily use that high an error rate as it auto-sets the threshold based on the observed distribution of errors. You can see the estimate in the ```unitigging/4-unitigger/*001.filterOverlaps.thr000.num000.log``` file.  That will give you an idea of what error rate you actually used.

The rawError rate also controls the alignment that is accepted for correcting reads but using it on the corrected reads won't matter.
