### ISSUE TITLE
unitigging 3-overlapErrorAdjustment very slow and sluggish

### ISSUE THREAD

**Issue by ghannum** [marbl/canu#118]
The findErrors processes appear to be exceptionally slow and make the machine very slow to respond.

In Canu1.0 w. 2.1mil reads (13.1GB) the step took 15hrs.
Using Canu1.2 w. 2.5mil reads (18.6 GB) the ETA is ~2wks.

Run on single server w. 120 cores and 2TB ram. 
CPU usage is 75%, ram usage is <5%. All data stored on local SSD array.

**Comment by brianwalenz** [comment]
I don't have any good suggestions, yet, so all I can do is ask for more info and suggest places to look.

What's the genome size?  Any special settings on the canu command line?  What did canu report for limits of the various stages (reported at the start of the canu run)?  Your machine is double what we've tested with.

How are you estimating two weeks for completion time?

How many 'red.sh' jobs need to be run in each case?  You can find this by reading 3-overlapErrorAdjustment/red.sh.  While there, how large is each job (number of reads, maxid-minin)?  How much memory is being used by each job?  How many threads?

Can you view disk performance?  Is it saturated?

Are the statistics in correction.html and trimming.html and unitigging.html comparabale?  Compare the read length histograms, kmer histograms and overlap counts.

How long has this been running?  Is a restart (of findErrors) feasible?

**Comment by ghannum** [comment]
Here are some answers to your questions:

Genome size: ~866MB (we think 216x4)
Canu run cmd:
canu -p myorganism -d /localdir genomeSize=866000000 minReadLength=3000 -pacbio-raw /data/filtered_subreads.fastq > canu.out 2> canu.err
Also note that this is being run in a docker container.

Canu detection report:
-- Detected Java(TM) Runtime Environment '1.8.0_66-internal' (from 'java').
-- Detected 120 CPUs and 2020 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
-- Allowed to run   8 jobs concurrently, and use up to  15 compute threads and  252 GB memory for stage 'bogart (unitigger)'.
-- Allowed to run   8 jobs concurrently, and use up to  15 compute threads and   32 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   8 jobs concurrently, and use up to  15 compute threads and   32 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   8 jobs concurrently, and use up to  15 compute threads and   32 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run  15 jobs concurrently, and use up to   8 compute threads and   16 GB memory for stage 'read error detection (overlap error adjustment)'.
-- Allowed to run 120 jobs concurrently, and use up to   1 compute thread  and    2 GB memory for stage 'overlap error adjustment'.
-- Allowed to run  15 jobs concurrently, and use up to   8 compute threads and   48 GB memory for stage 'utgcns (consensus'.
-- Allowed to run 120 jobs concurrently, and use up to   1 compute thread  and    4 GB memory for stage 'overlap store parallel bucketizer'.
-- Allowed to run 120 jobs concurrently, and use up to   1 compute thread  and    8 GB memory for stage 'overlapper'.
-- Allowed to run  15 jobs concurrently, and use up to   8 compute threads and   12 GB memory for stage 'overlapper'.
-- Allowed to run  15 jobs concurrently, and use up to   8 compute threads and   12 GB memory for stage 'overlapper'.
-- Allowed to run   8 jobs concurrently, and use up to  15 compute threads and   64 GB memory for stage 'meryl (k-mer counting)'.
-- Allowed to run  30 jobs concurrently, and use up to   4 compute threads and   20 GB memory for stage 'falcon_sense (read correction)'.
-- Allowed to run   8 jobs concurrently, and use up to  15 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   8 jobs concurrently, and use up to  15 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   8 jobs concurrently, and use up to  15 compute threads and    6 GB memory for stage 'minimap (overlapper)'.

I estimate the 2wks completion time by looking at the time for a single red.sh job (~3days) and figure there are 81 jobs, 15 at a time. 81/15*3/7 = 2.3 wks

maxid - minid = 33000

Each job uses 8GB (18 GB virtual) and 8 threads.

iostat:
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
                67.82    0.00    0.85          0.35       0.00      30.98

top:
All findErrors jobs reported as 'S'
Cpu(s): 60.9%us,  0.4%sy,  0.0%ni, 38.7%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
ex. 473997 ghannum   20   0 17.9g 7.9g 3.5g S 656.5  0.4  14975:20 findErrors

I have restarted this step several times with no difference. The job has been running continuously for ~5days between my attempts to restart it. A few of the jobs are completed each time.

Stats from:  #Reads   Hist                                                           #kmers   #distinct   #single
correction    7.9e6      median ~8k, high peak at low end (3k)     60.4e9    2.1e9       2.7e6
trimming      2.5e6      median ~8k, no peak at low end               18.7e9    1.1e9       672e6
unitigging    2.5e6      median ~8k, no peak at low end               18.6e9     1.1e9      661e6

**Comment by brianwalenz** [comment]
It's possible you're being flooded with short overlaps.  The default minimum overlap length is 500.  Unfortunately, we don't compute a direct histogram of the overlap lengths, so figuring out if this is so will be convoluted.

This is a bit of a fishing expedition.  unitigging.html has a table of read classifications.  I'm interested in the uniq-repeat-dove category.  The classification of each read is in *ovlStore.per-read.log.  You can dump a picture of the overlaps for one of those reads, and filter by length, with:

ovStoreDump -G *gkpStore -O *ovlStore -p <readID> -L <minLength>

I wanted to then try running findErrors with the short overlaps ignored, but the code doesn't support it (yet).

**Comment by StefanoLonardi** [comment]
I have also experienced a similar problem. I have run canu v1.0 and canu v1.2 on exactly the same set of data, and in one run the findErrors processes would take forever and I had to kill them. I thought there was something wrong with the hw because I could not explain why they would take so much longer than before.  I will try what Brian is suggesting. My genome is 620Mb and we have about 52x worth of data.

**Comment by brianwalenz** [comment]
Thanks for reporting.  I can confirm there is a problem.  My test is showing about 3.5 times slower.

Changing the value of AS_MAX_READLEN_BITS from 21 to 17 significantly improves run time performance, but I don't know why.  Note that this will limit reads to 128 kbp long, and any assembly must be restarted from scratch.

**Comment by brianwalenz** [comment]
Fixed, and then some.  It should be even faster than v1.0 now.
