### ISSUE TITLE
generateTemplateStitch()-- FAILED to align

### ISSUE THREAD

**Issue by edotau** [marbl/canu#1180]
I am using canu version 1.8 with the following command:
```canu -p canu -d stickleback_canu corThreads=2 corConcurrency=10 correctedErrorRate=0.085 corMhapSensitivity=normal useGrid=1 gridOptionsExecutive=--mem=64g genomeSize=500m overlapper=mhap utgReAlign=true gridEngineThreadsOption=--cpus-per-task=8 -pacbio-raw *.fastq*```

I am at the unitigging/5-consensus stage of the assembly pipeline and here are the log files, do you have any ideas to how I should fix this? thanks!

Running job 1 based on SLURM_ARRAY_TASK_ID=1 and offset=0.
 16 -- Opening seqStore '../canu.ctgStore/partitionedReads.seqStore' partition 1.
 17 -- Opening tigStore '../canu.ctgStore' version 1.
 18 -- Opening output results file './ctgcns/0001.cns.WORKING'.
 19 --
 20 -- Computing consensus for b=0 to e=96229 with errorRate 0.0850 (max 0.4000) and minimum overlap 40
 21 --
 22 generateTemplateStitch()-- FAILED to align - no more template to remove!  Fail!
 23 generateTemplateStitch()-- FAILED to align - no more template to remove!  Fail!
 24 generateTemplateStitch()-- FAILED to align - no more template to remove!  Fail!
 25 generateTemplateStitch()-- FAILED to align - no more template to remove!  Fail!
 26 generateTemplateStitch()-- FAILED to align - no more template to remove!  Fail!
 27 generateTemplateStitch()-- FAILED to align - no more template to remove!  Fail!
 28 generateTemplateStitch()-- FAILED to align - no more template to remove!  Fail!
 29 generateTemplateStitch()-- FAILED to align - no more template to remove!  Fail!

**Comment by brianwalenz** [comment]
Can you rerun with the latest unreleased code from github?  Before restarting, add options "-V -V" to the utgcns command at the end of 'unitigging/5-consensus/consensus.sh' (for example, make the first line of the command `$bin/utgcns -V -V \` instead of `$bin/utgcns \`).

Also, if possible, check for any N's in your reads.

**Comment by brianwalenz** [comment]
Idle.  Success?
