### ISSUE TITLE
Small virus assembly aborts at meryl stage before correction

### ISSUE THREAD

**Issue by Niicii** [marbl/canu#1183]
Hey :) I tried to assemble an ssRNA virus genome from Nanopore ~20.000 cDNA reads (710x cov) using the following command:  
`canu -p amv -d test_amv_only_l500 genomeSize=30k minReadLength=500 corOutCoverage=1000 -nanopore-raw ./12271_Arabis_mosaic_virus.fastq`

I already assumed there migth be some challenges coming up because of the small sizes of the Virus genome fragments (7.3 and 3.8 kb). I scanned through a few open and closed Issues about small genomes, plasmid and meryl problems but could not find my solution. 

Would be happy to hear any suggestions :) 

Last few lines of stdout:
```
-- Starting 'meryl' concurrent execution on Mon Dec 10 14:50:14 2018 with 1226.343 GB free disk space (1 processes; 4 concurrently)

    cd correction/0-mercounts
    ./meryl-count.sh 1 > ./meryl-count.000001.out 2>&1

-- Finished on Mon Dec 10 14:50:17 2018 (3 seconds) with 1226.302 GB free disk space
----------------------------------------
-- Found 1 Kmer counting (meryl) outputs.
-- Finished stage 'cor-merylCountCheck', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'meryl' concurrent execution on Mon Dec 10 14:50:17 2018 with 1226.302 GB free disk space (1 processes; 4 concurrently)

    cd correction/0-mercounts
    ./meryl-process.sh 1 > ./meryl-process.000001.out 2>&1

-- Finished on Mon Dec 10 14:50:18 2018 (one second) with 1226.302 GB free disk space
----------------------------------------
--
-- meryl-process failed, retry.
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'meryl' concurrent execution on Mon Dec 10 14:50:18 2018 with 1226.302 GB free disk space (1 processes; 4 concurrently)

    cd correction/0-mercounts
    ./meryl-process.sh 1 > ./meryl-process.000001.out 2>&1

-- Finished on Mon Dec 10 14:50:18 2018 (furiously fast) with 1226.302 GB free disk space
----------------------------------------
--
-- meryl-process failed, tried 2 times, giving up.
--
ABORT:
ABORT: Canu snapshot v1.8 +58 changes (r9268 7db596703c7d8ffe2a62a20c3365800d304234f8)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```

The `correction/0-mercounts/meryl-process.000001.out` file showed the following error message:
```
Found perl:
   /usr/bin/perl
   This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi

Found java:
   /usr/bin/java
   openjdk version "1.8.0_191"

Found canu:
   /opt/canu/Linux-amd64/bin/canu
   Canu snapshot v1.8 +58 changes (r9268 7db596703c7d8ffe2a62a20c3365800d304234f8)

Running job 1 based on command line options.
kmerCountFileWriter()-- Creating 'amv.ms16.WORKING' for 16-mers, with prefixSize 12 suffixSize 20 numFiles 64
Segmentation fault (core dumped)
meryl merge failed.
./test_amv_only_l500/correction/0-mercounts/meryl-process.000001.out (END)
```

Also, I was wondering whether it is correct that the file meryl-count.success is emty, while ./correction/0-mercounts/meryl-count.000001.out says counting was finished as below. 
```
Running job 1 based on command line options.

Counting 20  million canonical 16-mers from 1 input file:
    canu-seqStore: ../../amv.seqStore


SIMPLE MODE
-----------

  16-mers
    -> 4294967296 entries for counts up to 65535.
    -> 64 Gbits memory used

  21314615 input bases
    -> expected max count of 85258, needing 2 extra bits.
    -> 8192 Mbits memory used
  9216 MB memory needed

COMPLEX MODE
------------
prefix     # of   struct   kmers/    segs/     data    total
  bits   prefix   memory   prefix   prefix   memory   memory
------  -------  -------  -------  -------  -------  -------
     1     2  P    10 kB    10 MM   631  S    78 MB    78 MB
     2     4  P     9 kB  5203 kM   305  S    76 MB    76 MB
     3     8  P    10 kB  2601 kM   148  S    74 MB    74 MB
     4    16  P    10 kB  1300 kM    72  S    72 MB    72 MB
     5    32  P    12 kB   650 kM    35  S    70 MB    70 MB
     6    64  P    15 kB   325 kM    17  S    68 MB    68 MB
     7   128  P    22 kB   162 kM     8  S    64 MB    64 MB
     8   256  P    36 kB    81 kM     4  S    64 MB    64 MB
     9   512  P    64 kB    40 kM     2  S    64 MB    64 MB
    10  1024  P   120 kB    20 kM     1  S    64 MB    64 MB  Best Value!
    11  2048  P   240 kB    10 kM     1  S   128 MB   128 MB
    12  4096  P   480 kB  5204  M     1  S   256 MB   256 MB
    13  8192  P   960 kB  2602  M     1  S   512 MB   512 MB
    14    16 kP  1920 kB  1301  M     1  S  1024 MB  1025 MB
    15    32 kP  3840 kB   651  M     1  S  2048 MB  2051 MB

FINAL CONFIGURATION
-------------------
Configured complex mode for 0.063 GB memory per batch, and up to 1 batch.

kmerCountFileWriter()-- Creating './amv.01.meryl.WORKING' for 16-mers, with prefixSize 10 suffixSize 22 numFiles 64
Loading kmers from '../../amv.seqStore' into buckets.
Used 0.281 GB out of 2.000 GB to store         1042 kmers.

Writing results to './amv.01.meryl.WORKING', using 4 threads.
finishIteration()--

Finished counting.
Bye.
```

**Comment by brianwalenz** [comment]
Is amv.01.meryl small enough to upload, and are you willing to share the kmers in your reads?  There's no useful logging, not even on the crash, and I'd rather not debug through email.  If it's too big to attach here, the [Canu FAQ](https://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you) has directions to upload to FTP.

There's a chance it might be a corrupted file.  Save the bad results by renaming '0-mercounts' to '0-mercounts-bad'.  The restart Canu and let it recompute.

All the 'success' files will be empty.  They're just Post-It notes telling Canu the process finished successfully, and to not bother checking the results.

**Comment by Niicii** [comment]
Hi Brian,  

Thanks for the quick reply.
   
Renaming and restarting did not work, neither did deleting the complete run-output and recomputing.   

I zipped the 01.meryl folders of the canu run attempts from a prefiltered metagenomic sample containing all found virus reads ([virus.01.meryl.zip](https://github.com/marbl/canu/files/2668327/virus.01.meryl.zip)) and from the run only taking the reads classified as Arabis mosaic virus ([amv.01.meryl.zip](https://github.com/marbl/canu/files/2668326/amv.01.meryl.zip)).

Thanks for having a look at it.

**Comment by brianwalenz** [comment]
Unfortunately, it took me a while to look at this, and worse, it isn't failing for me.  So we'll have to do this the hard way.

Have you gotten any runs to finish?  If not this could indicate something in your environment.  Lets start with various process limits from `ulimit -a`.

What compiler was used to install?  Assuming you've still got it around, `make` in the src/ directory will report all sorts of good stuff.

Now for some experiments.  It's failing trying to run:
```
meryl threads=4 memory=2 greater-than 1 output junk.meryl union-sum virus.01.meryl
```
so lets try to run some slight variants of that.  I'm not interested in the output if they run, but if they crash, paste in the last few lines.  That will hopefully give some indication of where its failing.
```
meryl histogram virus.01.meryl
meryl -VVV threads=1 union-sum virus.01.meryl
meryl -VVV threads=1 greater-than 1 virus.01.meryl
meryl -VVV threads=1 output junk.meryl union-sum virus.01.meryl
meryl -VVV threads=1 output junk.meryl greater-than 1 virus.01.meryl
```
The -VVV option (very very verbose) will generate A LOT of output to the screen.  Try running without that option first.

And if you're feeling adventurous, running in the debugger will definitely help.  Prefix the command with `gdb -silent --args` (so: `gdb -silent --args meryl .....`) and enter the command `where` when it fails.  You'll be rewarded with a listing of the functions it's called and line numbers in the source code.

**Comment by brianwalenz** [comment]
Idle.
