### ISSUE TITLE
Question about using High Quality Short reads

### ISSUE THREAD

**Issue by bmlett** [marbl/canu#1187]
Hi, 

I just finished reading the initial papers for the Celera and Canu. My interest in Celera was that it did the long read correction using high-identity short-reads. Seeing that is was no longer supported I was looking into Canu, however in my searches I haven't seen an option of using the high-identity short-reads. Is that no an option with Canu? If not is there a way to combine the two to utilizes high quality short-reads along with assembling and correcting the long reads?

Thanks, 
Beth

**Comment by brianwalenz** [comment]
There is no way to use them in Canu, on purpose.  Short reads aren't terribly useful in long-read assembly.  When used for correction, they homogenize repeats and mix up haplotypes, resulting in _worse_ assemblies.

**Comment by bmlett** [comment]
Hi, 

Thank you for your reply. You've raised interesting point that I will need to read deeper into. So far in my literature search I have not seen any reports of the short reads making the assembly worse, however there has seemed to be more non-hybrid approaches to long-read assembly, which was a curiosity for me. I may not be searching for the correct terminology to find articles discussing the quality difference of the non-hybrid approaches versus a hybrid one. Is there a specific article or articles that has shown that correction of long reads via high-quality short reads results in a worse assembly? 

Thank you for your time and suggestions,
Beth

**Comment by skoren** [comment]
Generally, the non-hybrid assembly also outperforms hybrid methods at higher coverages (over 30x or so as a rule). You can see some of these comparisons here: https://www.ncbi.nlm.nih.gov/pubmed/24034426 and in the Canu paper: https://www.ncbi.nlm.nih.gov/pubmed/28298431

**Comment by bmlett** [comment]
Thank you.

**Comment by brianwalenz** [comment]
Added to FAQ, cheers!
