### ISSUE TITLE
Possible Pacbio+10xC approaches

### ISSUE THREAD

**Issue by francicco** [marbl/canu#1188]
Dear @skoren,

Due to a poor Pacbio sequencing we and up having a slightly incomplete genome (the full genome should be ~400Mb). Because we decided to improve it we opted to do some 10x Chromium sequencing. This would help to error correction and scaffold the CANU assembly. But I guess this might not be enough since the original assembly is partially incomplete. So my question is how can I use both data more wisely. I was thinking at two strategies.

A) I assemble the 10xG with Supernova, than reduce the contings in ~30,000 pseudo reads and with the original Pacbio reads assemble with CANU. (Maybe someone already tried this?)

B) Assemble the two separate data and somehow merge Supernova and CANU assemblies. Maybe using quickmerge? This is less elegant I think. I would also need to make a consensus out the the two Supernova assembly alleles.

Any advice?
Best
F

**Comment by skoren** [comment]
We have tried to use quick merge but it has the issue that it will replace a gapless PacBio contig with a gapped 10x scaffold which you don't want. I don't know if there are updated options to avoid this but for this reason I wouldn't recommend it.

I think your two options would be to gap fill the 10x assembly with PacBio reads or to scaffold the PacBio assembly with 10x data and then gap fill. Depending on how close to complete the assembly is (have you checked busco stats?) the gap filling may help get it to the full size. You could also try including 10x scaffolds that are not in the PacBio-only assembly but I'd first confirm the assembly is really not complete.

**Comment by francicco** [comment]
Thanks Sergey,

Filling the gap with the Pacbio was one of the idea, but then we need to polish those regions, and I should test if those are somehow covered by the illumina reads. Definitely something to think about

BUSCO insecta_odb9
```
C:94.9%[S:93.5%,D:1.4%],F:2.0%,M:3.1%,n:1658

	1574	Complete BUSCOs (C)
	1551	Complete and single-copy BUSCOs (S)
	23	Complete and duplicated BUSCOs (D)
	33	Fragmented BUSCOs (F)
	51	Missing BUSCOs (M)
	1658	Total BUSCO groups searched
```

arthropoda_odb9
```
C:96.0%[S:94.9%,D:1.1%],F:1.5%,M:2.5%,n:1066

	1024	Complete BUSCOs (C)
	1012	Complete and single-copy BUSCOs (S)
	12	Complete and duplicated BUSCOs (D)
	16	Fragmented BUSCOs (F)
	26	Missing BUSCOs (M)
	1066	Total BUSCO groups searched
```

It doen't look extremely bad, but there's room for improvement I think.
F

**Comment by skoren** [comment]
That's pretty good, and will likely improve after you run signal polishing with Arrow (the fragmented are likely frame shifted genes). I would probably just scaffold that assembly and gap fill/polish.

For polishing, Illumina will definitely have issues polishing repetitive regions and I expect those will be what you're gap-filling so I'd guess the best strategy would be polishing with both long reads and short reads (long to polish the repeat, short to polish the rest).

**Comment by francicco** [comment]
I already run Arrow on top. I did some test and apparently there's still stuff to be fixed. 10xG reads will come handy for that.
