### ISSUE TITLE
What algorithm is used to calculate the prefix edit distance in file findErrors-Prefix_Edit_Distance.C

### ISSUE THREAD

**Issue by shengyang007** [marbl/canu#1190]
Hi
I can‘t understand the calculation process well. How can I get the introduction or URL of this algorithm?

**Comment by brianwalenz** [comment]
It is related to Myers' et al. O(ND) difference and O(NP) sequence comparison algorithms.  Based on dates, it's probably closer to the O(NP) variant.

https://link.springer.com/article/10.1007/BF01840446
https://www.sciencedirect.com/science/article/pii/002001909090035V
