### ISSUE TITLE
mhap overlap jobs failed

### ISSUE THREAD

**Issue by dtzhu337** [marbl/canu#1191]
I ran canu in a grid for several time but failed. This time the problem come back to mhap overlap.

```
Mhap overlap jobs failed, retry.
--   job correction/1-overlapper/results/000146.ovb FAILED.
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'cormhap' concurrent execution on Fri Dec 21 02:20:54 2018 with 1578501.205 GB free disk space (1 processes; 4 concurrently)

    cd correction/1-overlapper
    ./mhap.sh 146 > ./mhap.000146.out 2>&1

-- Finished on Fri Dec 21 02:20:54 2018 (in the blink of an eye) with 1578501.205 GB free disk space
----------------------------------------
--
-- Mhap overlap jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/results/000146.ovb FAILED.

I tried to remove 000146.mhap.WORKING (this file only), but it still didn't work. I checked mhap.000146.out file, and it showed that 'Running job 146 based on command line options.
ls: cannot access ./queries/000146: No such file or directory
\ Running block 000058 in query 000146'
```
What can I do to fix this?

Thank you

**Comment by skoren** [comment]
It looks like you're missing files from the previous step. What is in the queries folder and the blocks folder in 1-overlapper.

**Comment by dtzhu337** [comment]
<img width="1256" alt="screen shot 2018-12-21 at 9 48 11 am" src="https://user-images.githubusercontent.com/45495876/50348008-95571b80-0505-11e9-8f3f-24c381c3eb91.png">

Here it is. The queries fold lacks 000146. But the blocks folder contains 000058.dat for 000146. What's more, I checked 000145, and it also use 000058.dat. What does that mean?

**Comment by skoren** [comment]
That's fine it's supposed to split the same index into two runs. One dat file is loaded as the index and the rest are streamed against it. It seems your file system somehow lost a folder, did you run out of space any some point?

Check the partitioning.log file, see if it has an entry for job 146 (or any jobs over 145 for that matter), it should tell you what the query folder should have contained.

**Comment by dtzhu337** [comment]
> You should be able to create an empty folder in queries named 000146 and the job should run. I am not sure how it would disappear or not get created.

Hi Skoren,

It's working. Thank you.

Merry Christmas.
