### ISSUE TITLE
canu 1.8 "ERROR:  Paramter 'correctedErrorRate' is not known."

### ISSUE THREAD

**Issue by foala** [marbl/canu#1194]
Hi,
I have installed canu 1.8 via bioconda.
When I tried to run this option:
correctedErrorRate=0.105 as mentioned in the documentation, I get this error:

ERROR:  Paramter 'correctedErrorRate' is not known.

Please assist.  @brianwalenz  @skoren 
Thank you

**Comment by brianwalenz** [comment]
The bioconda upgrade method is broken.

See https://github.com/bioconda/bioconda-recipes/issues/11509 and https://github.com/bioconda/bioconda-recipes/issues/11132 for details and a fix - or just install without using bioconda using our release packages.

**Comment by skoren** [comment]
Same issue as #1196
