### ISSUE TITLE
Report is not generated 

### ISSUE THREAD

**Issue by foala** [marbl/canu#1196]
Hi,
I cannot find *.report after the assembly is concluded.
Please assist,
Version: Canu 1.8

**Comment by foala** [comment]
> What files do you have?
Thank you for your reply.

I think I have all the folders. There was no issue with the assembly process.
Here is a list of all the files and folders I have in the main assembly directory.

canu-logs
correction.html
SP11.contigs.fasta
SP11.contigs.layout.readToTig
SP11.correctedReads.length
SP11.unitigs.fasta
SP11.unitigs.layout.readToTig
trimming.html
unitigging.html
canu-scripts
correction.html.files
SP11.contigs.gfa
SP11.contigs.layout.tigInfo
SP11.trimmedReads.fasta.gz
SP11.unitigs.gfa
SP11.unitigs.layout.tigInfo
trimming.html.files
unitigging.html.files
correction
SP11.bubbles.fasta
SP11.contigs.layout
SP11.correctedReads.fasta.gz
SP11.unassembled.fasta
SP11.unitigs.layout
trimming
unitigging


Thank you once again,

**Comment by brianwalenz** [comment]
The good news: you have an assembly.

The bad news: that is, at best, Canu 1.6.  Most of the same *.report information is in the various *.html files.

How was canu installed?  What does `canu --version` report?  If it was installed with bioconda, reinstall directly using our release packages.  Bioconda isn't installing Canu correctly; see https://github.com/bioconda/bioconda-recipes/issues/11509 and https://github.com/bioconda/bioconda-recipes/issues/11132 for details.
