### ISSUE TITLE
Canu 1.8: task meryl failed to find a configuration to run on.

### ISSUE THREAD

**Issue by paul-sheridan** [marbl/canu#1198]
Hi All,

I ran the following command on the MacOS High Sierra Version 10.13.6 operating system:
 
```canu -p myorganism -d myorganism-oxford genomeSize=1g -nanopore-raw reads/*.fastq```

But it gives this error:

```
-- Canu 1.8
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_191' (from 'java') with -d64 support.
-- Detected gnuplot version '5.2 patchlevel 5   ' (from 'gnuplot') and image format 'png'.
-- Detected 4 CPUs and 16 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
-- ERROR
-- ERROR
-- ERROR  Found 1 machine configuration:
-- ERROR    class0 - 1 machines with 4 cores with 16 GB memory each.
-- ERROR
-- ERROR  Task meryl can't run on any available machines.
-- ERROR  It is requesting:
-- ERROR    merylMemory=24-64 memory (gigabytes)
-- ERROR    merylThreads=1-8 threads
-- ERROR
-- ERROR  No available machine configuration can run this task.
-- ERROR
-- ERROR  Possible solutions:
-- ERROR    Change merylMemory and/or merylThreads
-- ERROR
ABORT:
ABORT: Canu 1.8
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   task meryl failed to find a configuration to run on.
ABORT:
```

I gather from reading [https://github.com/marbl/canu/issues/547] that I ought to change the 'merylMemory' setting, but I don't understand where to find it and what to change it to.

Any suggestions?

Many Thanks,

Paul

**Comment by brianwalenz** [comment]
`canu merylMemory=8 merylThreads=4 ....`

However, you'll struggle to get this to complete on that hardware.  Memory isn't so much of an issue (I'd prefer to have twice that, but it should be ok).  CPU is a problem.  A drosophila takes me about a day with 24 cores.  Your genome is 6 times larger, likely more repeat rich, and has longer reads.  The repeats result in more intermediate data being generated, stored and processed.  The longer reads - great for assembly - are more expensive to process.

**Comment by paul-sheridan** [comment]
Thanks a lot. For the record, I was able to get the process started by running this command:

`canu -p myorganism -d myorganism-oxford genomeSize=1g merylMemory=8 merylThreads=4 hapThreads=4 batMemory=8 -nanopore-raw reads/*.fastq`

However, I think I'll heed your advice and run it on a more suitable system.

**Comment by brianwalenz** [comment]
If you've got 6-8 weeks to burn, I wouldn't mind seeing how it runs on that hardware.  :-)
