### ISSUE TITLE
Installation errors introduced after pbdagcon made default consensus module.

### ISSUE THREAD

**Issue by JohnUrban** [marbl/canu#12]
Congrats on Canu V1.0.

Last I downloaded Canu was a little over a week ago - just before pbdagcon was made the default consensus module. I never had problems with Canu installation prior to today, which was a major benefit of using Canu in my opinion.

Today I tried to install the latest commit and got the following error message:

$ git clone https://github.com/marbl/canu.git
$ cd canu/src
$ make

In file included from utgcns/libpbutgcns/Alignment.C:8:
utgcns/libpbutgcns/Alignment.H:17: error: ‘uint32_t’ does not name a type
utgcns/libpbutgcns/Alignment.H:19: error: ‘uint32_t’ does not name a type
utgcns/libpbutgcns/Alignment.H:33: error: ‘uint32_t’ does not name a type
utgcns/libpbutgcns/Alignment.C: In constructor ‘dagcon::Alignment::Alignment()’:
utgcns/libpbutgcns/Alignment.C:13: error: class ‘dagcon::Alignment’ does not have any field named ‘start’
utgcns/libpbutgcns/Alignment.C:14: error: class ‘dagcon::Alignment’ does not have any field named ‘end’
utgcns/libpbutgcns/Alignment.C: In function ‘dagcon::Alignment normalizeGaps(dagcon::Alignment&)’:
utgcns/libpbutgcns/Alignment.C:79: error: ‘class dagcon::Alignment’ has no member named ‘start’
utgcns/libpbutgcns/Alignment.C:79: error: ‘class dagcon::Alignment’ has no member named ‘start’
make: *** [../Linux-amd64/obj/libcanu.a/utgcns/libpbutgcns/Alignment.o] Error 1

Any ideas on how to successfully install Canu?

**Comment by skoren** [comment]
This looks a difference in default includes. Can you try the attached patch file to patch your code and see if it fixes the issue

```
mv utgcns/libpbutgcns/Alignment.H utgcns/libpbutgcns/Alignment.old
patch utgcns/libpbutgcns/Alignment.old -i patchfile.patch -o utgcns/libpbutgcns/Alignment.H
make
```
[patchfile.patch.gz](https://github.com/marbl/canu/files/77776/patchfile.patch.gz)

**Comment by JohnUrban** [comment]
Your instructions and patch worked. Thank you.
