### ISSUE TITLE
canu failed with 'gatekeeper store exists, but contains no reads'.

### ISSUE THREAD

**Issue by ml12220** [marbl/canu#120]
Hi,
I've been running canu on a series of simulated bacterial reads with different error rates. canu works fine with error rates of 10% or lower and changing the errorRate value seems to makes no difference to its success. However, when I input reads with an error rate of approximately 16% it fails, with all other parameters the same:

canu -p pmarinus -d Pmarinus_p8_c35 genomeSize=1.8m errorRate=0.16 -nanopore-raw Pmarinus.fasta.minion.phred_8.cov_35.fa

I get this error:

=============================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'gatekeeper store exists, but contains no reads'.

Is there are a reason why this happens on low accuracy data and are there some parameters I should tinker with for it to work?

Many thanks,
Mike

**Comment by brianwalenz** [comment]
You are correct - the errorRate parameter does nothing.  It was an early design idea that we could never make work as intended, but didn't quite remove completely.  Whatever you set is overridden by -nanopore-raw (et al.).

16% error is 1 base wrong in every 6 or 7.  Assuming this is from the 'trimming' gatekeeper store, I think what you're seeing is a failure to find kmers for correcting the reads, resulting in no corrected reads being generated (correctedReads.fasta should be empty).  Look in correction.html for details on the correction.

You can try dropping mhapMerSize.  The default is 16.

How are you generating reads?  What prompted this experiment?

**Comment by skoren** [comment]
I second Brian's suggestion, the likeliest bottleneck is the seed size and maybe the corrected read consensus. You can try setting
```
corMhapMerSize=<12 or lower, default is 16> corMhapSensitivity=high
```
to find more overlaps. You may also need to set
```
corMinCoverage=0
```
to get as much data output from correction as possible. The bad bases will then be trimmed by the subsequent steps before assembly.

Generally, I've not found any simulated data that reflects the characteristics of real data. For example, the nanopore data is high error but is clumpy so you can find seeds longer than you would expect if the error was perfectly randomly distributed.

**Comment by ml12220** [comment]
Thanks

I tried it again with the suggested settings:

> corMhapMerSize=12 corMhapSensitivity=high corMinCoverage=0

The process is completed, but the contigs.fasta file is empty.

I'm a masters student and for part of my thesis I'm exploring the use of simulated MinION reads in improving assemblies (hybrid and scaffolding) and as a standalone assembly solution. As for the simulated data, I cannot give a good explanation for how they are generated as I did not write the script. Although, I believe it does assume a random error distribution. Do you know of any sources that describe the the error distribution of real nanopore data?

Many thanks,
Mike

**Comment by skoren** [comment]
That sounds strange, what was the output of the full run, specifically how much coverage did you have after correction and after trimming? I'd also suggest mapping the corrected reads to your reference to estimate their quality.

As for real nanopore data, there is at least one preprint online for a simulator but there is a large variation between runs and it is rapidly changing so I'm not sure any simulator would keep up with the real data.

**Comment by hd4git** [comment]
Hi,

Could you get a solution for contigs.fasta being empty?
I am trying to assemble mitochondrial genome with pacbio reads using the following command:
`./canu -d CH_mito_lowcvg -p Mitochondria genomesize=16000 utgMhapVersion=2.0 corMhapMerSize=12 corMhapSensitivity=high corMinCoverage=2 errorRate=0.035 minOverlapLength=499 corMaxEvidenceErate=0.3 -pacbio-raw ../../../../CH_mito/pacbio.fastq`

The process runs completely but contigs.fasta is empty. I used the options for low coverage data to rule out any problem due to coverage. I have also tried number of different values for these options to make it more lenient, trying to know where the problem can be, but contigs.fasta is always empty.

However, when I checked  the layout file I can find the entire length of expected sequence in the topmost tig reported there amongst other 57 tigs ranging in size from 1118-16355.

Does anyone has any idea why couldn't that tig be reported in the contigs.fasta file? 
I would like to know if I am missing some important option to get the assembly.

Thanks.

**Comment by skoren** [comment]
I assume you have relatively high coverage of the mitochondrial genome? The sensitive parameters aren't going to help if you have over 30X.

There are flags which determine if something is assembled or not based on what percentage is spanned by a single read. On these small organelles, it is possible you have a single read covering the majority of it, leading it to be classified as unassembled. You can find the 16k tig from the layout file in asm.unassembled.fasta which will give other stats (such as # reads, coverage stat, etc), as long as it is not composed of a single read, you can treat it as a normal contig from this assembly.

If you want to avoid filtering for this case, you can adjust the filtering criteria
```
contigFilter="2 1000 0.95 0.95 2"
```
This means filter out those tigs where 95% of it is covered by a single read or has 1x coverage. The default is 75%, you could also increase it to 99% or any other value if you want.

or try correcting more reads
```
corOutCoverage=100
```

**Comment by hd4git** [comment]
Thanks a lot for such a nice explanation.
We do have reads covering the entire genome, so definitely contigFilter option was required.
I tried setting it to "1 1000 1.00 1.00 1" and I could get the contigs reported in contigs.fasta and the assembled sequence is as expected.
