### ISSUE TITLE
canu correctReads phase

### ISSUE THREAD

**Issue by dtzhu337** [marbl/canu#1200]
I run canu in grid, but with useGrid=false option. The estimated size of genome is 280M.

Canu is running well now for almost 2 weeks, and in correctReads phase, which create a directory '2-correction'. Showed as below.

```
antPacbio.readsToCorrect        correctReads.000094.out
antPacbio.readsToCorrect.err    correctReads.000095.out
antPacbio.readsToCorrect.log    correctReads.000096.out
antPacbio.readsToCorrect.stats  correctReads.000097.out
correctReads.000001.out         correctReads.000098.out
correctReads.000002.out         correctReads.000099.out
correctReads.000003.out         correctReads.000100.out
correctReads.000004.out         correctReads.000101.out
correctReads.000005.out         correctReads.000102.out
correctReads.000006.out         correctReads.000103.out
correctReads.000007.out         correctReads.000104.out
```

But this step has been carried out for more than 10 days now, ~10 reads out every 48 hours. I have two questions. 

1. Is this normal to take such a long time?

2. If it is, how many reads would be correct further?
I checked the stats files
```
                         original      original
                         raw reads     raw reads
category                w/overlaps  w/o/overlaps
-------------------- ------------- -------------
Number of Reads            1832113        193478
Number of Bases        17435476973     836018890
Coverage                    62.270         2.986
Median                        7946          2476
Mean                          9516          4321
N50                          13283          9839
Minimum                       1000             0
Maximum                     131059         63645

                                     --------corrected---------  ----------rescued----------
                          evidence                     expected                     expected
category                     reads            raw     corrected            raw     corrected
-------------------- -------------  ------------- -------------  ------------- -------------
Number of Reads            1854044         755591        755591           8112          8112
Number of Bases        17940919425    11736751086   11200003802       25051830      23270542
Coverage                    64.075         41.917        40.000          0.089         0.083
Median                        8155          13729         13179           2946          2737
Mean                          9676          15533         14822           3088          2868
N50                          13255          15336         14694           3485          3349
Minimum                       1000           8096          8094           1005          1002
Maximum                     131059         113961        104803          16348          8092

                     --------uncorrected--------
                                        expected
category                       raw     corrected
-------------------- ------------- -------------
Number of Reads            1261888       1261888
Number of Bases         6509692947    3066360715
Coverage                    23.249        10.951
Median                        4450          1546
Mean                          5158          2429
N50                           6884          5525
Minimum                          0             0
Maximum                     131059        125217

Maximum Memory          1889407814
```
I am just wondering if it means there would be another more than 8000 reads to be corrected?

Thank you

**Comment by skoren** [comment]
The time will depend on the resources you have given Canu on the single node you're running on. What is the preamble say when you started Canu (available cores/etc)? It should also say how many total partitions it will run and how many concurrently which will let you know how much is left.

There should be about 755K corrected reads. I'm not sure what you mean 10 reads every 48 hours, do you mean 10 ```correctReads.*.out``` files every 48 hours?

**Comment by dtzhu337** [comment]
Hi skoren,

I required 1,000GB in 1 core for Canu. I tried to ask for more cores but the job in PBS pending for a longtime and not succeed. I've no idea about what you said about the partitions.

The PBS system has a walltime for each job, which is 48 hours. So i need to resubmit the job every 48 hours. Each time when I resubmit, I checked the progress of the job. In the directory of './correction/2-correction', the number of files (correctReads.*.out) would increase gradually. For example, from correctReads.000150.out to correctReads.000165.out.  So if more than 700K to be corrected, it's definitely not the right way. How can I improve this? Thank you.

**Comment by dtzhu337** [comment]
Hi Skoren,

This is an output file of a previous job.
--------------------------------
-- Finished on Fri Dec 21 15:16:03 2018 (16 seconds) with 1571258.036 GB
free disk space
----------------------------------------
--                             original      original
--                            raw reads     raw reads
--   category                w/overlaps  w/o/overlaps
--   -------------------- ------------- -------------
--   Number of Reads            1832113        193478
--   Number of Bases        17435476973     836018890
--   Coverage                    62.270         2.986
--   Median                        7946          2476
--   Mean                          9516          4321
--   N50                          13283          9839
--   Minimum                       1000             0
--   Maximum                     131059         63645
--
--                                        --------corrected---------
----------rescued----------
--                             evidence                     expected
             expected
--   category                     reads            raw     corrected
    raw     corrected
--   -------------------- -------------  ------------- -------------
------------- -------------
--   Number of Reads            1854044         755591        755591
   8112          8112
--   Number of Bases        17940919425    11736751086   11200003802
 25051830      23270542
--   Coverage                    64.075         41.917        40.000
  0.089         0.083
--   Median                        8155          13729         13179
   2946          2737
--   Mean                          9676          15533         14822
   3088          2868
--   N50                          13255          15336         14694
   3485          3349
--   Minimum                       1000           8096          8094
   1005          1002
--   Maximum                     131059         113961        104803
  16348          8092
--
--                        --------uncorrected--------
--                                           expected
--   category                       raw     corrected
--   -------------------- ------------- -------------
--   Number of Reads            1261888       1261888
--   Number of Bases         6509692947    3066360715
--   Coverage                    23.249        10.951
--   Median                        4450          1546
--   Mean                          5158          2429
--   N50                           6884          5525
--   Minimum                          0             0
--   Maximum                     131059        125217
--
--   Maximum Memory          1889407814
-- Finished stage 'cor-filterCorrectionLayouts', reset canuIteration.
--
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |     total usage     algorithm
--        -------  ------  --------   --------  -----------------
-----------------------------
-- Local: cor        7 GB    4 CPUs x  10 jobs    70 GB   40 CPUs  (read
correction)
--
-- Using overlaps no worse than 0.3 fraction error for correcting reads
(from corErrorRate parameter).
-- Finished stage 'cor-generateCorrectedReadsConfigure', reset
canuIteration.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'cor' concurrent execution on Fri Dec 21 15:16:03 2018 with
1571258.032 GB free disk space *(203 processes; 10 concurrently)*

    cd correction/2-correction
    ./correctReads.sh 1 > ./correctReads.000001.out 2>&1
    ./correctReads.sh 2 > ./correctReads.000002.out 2>&1
    ./correctReads.sh 3 > ./correctReads.000003.out 2>&1
    ./correctReads.sh 4 > ./correctReads.000004.out 2>&1
    ./correctReads.sh 5 > ./correctReads.000005.out 2>&1
    ./correctReads.sh 6 > ./correctReads.000006.out 2>&1
    ./correctReads.sh 7 > ./correctReads.000007.out 2>&1
    ./correctReads.sh 8 > ./correctReads.000008.out 2>&1
    ./correctReads.sh 9 > ./correctReads.000009.out 2>&1
    ./correctReads.sh 10 > ./correctReads.000010.out 2>&1
    ./correctReads.sh 11 > ./correctReads.000011.out 2>&1
    ./correctReads.sh 12 > ./correctReads.000012.out 2>&1
    ./correctReads.sh 13 > ./correctReads.000013.out 2>&1
    ./correctReads.sh 14 > ./correctReads.000014.out 2>&1
    ./correctReads.sh 15 > ./correctReads.000015.out 2>&1
    ./correctReads.sh 16 > ./correctReads.000016.out 2>&1
    ./correctReads.sh 17 > ./correctReads.000017.out 2>&1
    ./correctReads.sh 18 > ./correctReads.000018.out 2>&1
    ./correctReads.sh 19 > ./correctReads.000019.out 2>&1
    ./correctReads.sh 20 > ./correctReads.000020.out 2>&1
    ./correctReads.sh 21 > ./correctReads.000021.out 2>&1
    ./correctReads.sh 22 > ./correctReads.000022.out 2>&1
    ./correctReads.sh 23 > ./correctReads.000023.out 2>&1
    ./correctReads.sh 24 > ./correctReads.000024.out 2>&1
    ./correctReads.sh 25 > ./correctReads.000025.out 2>&1
    ./correctReads.sh 26 > ./correctReads.000026.out 2>&1
    ./correctReads.sh 27 > ./correctReads.000027.out 2>&1
    ./correctReads.sh 28 > ./correctReads.000028.out 2>&1
    ./correctReads.sh 29 > ./correctReads.000029.out 2>&1
    ./correctReads.sh 30 > ./correctReads.000030.out 2>&1

--------------------------------------

Does it mean there would be 203 correctReads.*.out files? (it has come to
187 now)

And this also showed the usage of memory?

Thank you

**Comment by skoren** [comment]
Yes, it means there will be 203 partitions and 203 output files. If you're at 187 then you would be done in about 3 days (assuming same runtime as you had before). You're actually using 40 cores on the node, which is more than the reservation but I assume by asking for 1000g you reserved a large node so that is OK. You're also only using 70gb which is far far less than your request.

What kind of nodes do you have available in your cluster? It's also possible you can increase the wall time beyond 48 hours so you don't have to re-start the jobs. If the job gets terminated in the middle of a partition, that partition will be recomputed from scratch so you're wasting compute there.

**Comment by dtzhu337** [comment]
Thank you very much for the explanation. It really helps and gives me
confidence. In terms of the walltime, I don't think I can do anything due
to that we didn't purchase private nodes. I will let it run like this.
