### ISSUE TITLE
Canu Wont Run "Failed to run gnuplot"

### ISSUE THREAD

**Issue by peflanag** [marbl/canu#1208]
Hi,

I recently installed Canu 1.8 and now the command wont run for me. It says gnuplot error. I have attached a screenshot below. Also, I had to remove the -fast command because that wouldn't work also. Once I removed the -fast command the gnuplot error came up.

Any help would be great, cheers!

P
<img width="963" alt="screen shot 2019-01-09 at 09 27 55" src="https://user-images.githubusercontent.com/32863969/50889862-e8c7d580-13f0-11e9-994f-fbee84d43349.png">
<img width="947" alt="screen shot 2019-01-09 at 09 24 24" src="https://user-images.githubusercontent.com/32863969/50889869-ebc2c600-13f0-11e9-9324-413084b9deb9.png">

**Comment by peflanag** [comment]
Hey it seems to be working when I put in the gnplotTested=true but the -fast command doesn't work. Is this an issue with v1.8?

Cheers,

P

**Comment by peflanag** [comment]
Just to update more, the script failed with exit code 139 and I have attached a screenshot below!

Cheers,

P

<img width="817" alt="screen shot 2019-01-09 at 11 16 47" src="https://user-images.githubusercontent.com/32863969/50896150-1405f100-1400-11e9-8974-71a1f3494239.png">

**Comment by skoren** [comment]
This is not version 1.8, neither gkpStore nor gnplotTested exists in 1.8. I expect this is 1.6 at best which would also not have a -fast option. I would guess you installed via Conda? That package is broken and can't properly upgrade Canu if you had a previous install. Instead, download the pre-compiled binaries from the GitHub page and run those directly.

**Comment by peflanag** [comment]
Ah ok cheers! Yea it was conda. I must have miss read it. I was thinking it be easier for me to install it that way!

**Comment by skoren** [comment]
Conda doesn't check for a pre-existing install and doesn't run a make clean beforehand so when you install a new version it gets a partial compilation. The version will report as 1.8 but most of the code will not be upgraded.
