### ISSUE TITLE
Canu problem with repetition of nucleotides in assembly

### ISSUE THREAD

**Issue by gktahon** [marbl/canu#1209]
Dear all,

I have recently started using Nanopore sequencing for bacterial genomes. We are currently in the testing phase and are trying to assemble genomes of pure bacterial strains of which we already have a closed reference genome available for comparison. Currently I'm working with Arcobacter butzleri with a G+C% of ~27%.

I run canu (version 1.8) on our high performance computer using the basic commands:
canu -correct -p arcobacter -d output_directory genomeSize=2.341m -nanopore-raw basecalls.fq
Afterwards I run the trim and the assemble commands.

The raw data gives me coverage of ~500x. After correction and trimming, I am left with a quarter of this coverage. Using less (trimmed) data for the assembly does not change the final output. 30x, 60x or 100x coverage gives me nearly the exact same assembly result, which is always a single contig that is circular. Sometimes I have a second or even third very small contig, but these do not matter.

After checking the large contig and removing the overlapping area, however, the remaining contig is always ~20-25 kb too short compared to the closed reference genome.
I have aligned this contig with the reference genome and noticed that the problem occurs when there are long repetitions of a certain nucleotide (in the case of this genome A of T). When there is a repetition of 4 or more A's for example, the canu assembly often misses one or 2 compared to the reference genome. So instead of having for example 6 A's, the canu assembly only has 4 or 5.

I have checked the raw data (i.e. output of the flappie and albacore basecallers) and noticed that there the repeats look different. For example where the final assembly only gives 4 A's, the raw data gives 5, 6 or even more. Sadly, these missing nucleotides influence the genome annotation as genes are split into several pieces.
Additionally, I have checked the trimmed data. Here I searched all the remaining reads for parts of my final contig where I suddenly am missing one nucleotide. I noticed that the reads already look different, i.e. the longer repeats (e.g. originally aaaaaaaa) have been shortened (to for example aaaaaa). Here I always find more sequences with a nucleotide too little instead of sequences with the correct number of A's for example.

Is there a way to reduce this problem during the data correction, trimming or assembly? I've already tried different things, but neither one worked. For example, I've tried to include also shorter reads (starting from 125 bp), lowering the error allowed in overlaps, changing minimum overlap size, ... but nothing changed this problem.

Would there be any suggestions on how to solve this?

Many thanks!!
Guillaume

**Comment by skoren** [comment]
The drop in coverage from correction is expected, by default Canu only keeps the best 40x so if you give it 500x and end up with a quarter that's expected. 

As for consensus, yes, there are primarily homopolymer-associated indels remaining after consensus. Canu is designed to have a subsequent polisher run on the output, something like Nanopolish should fix many of these errors. However, with a nanopore-only assembly, you'll probably still end up with a large number of indels and frameshifts due to limitations in the base caller (see issue #1201).

**Comment by gktahon** [comment]
Thank you for the quick reply!

If these are normal, I will not play with the parameters to try and improve it. Apart from the missing 1% of data, the rest of the genome is 99.99% correct compared to the reference. I already started trying out Nanopolish. Hopefully I will see a (major) improvement. Also planned on trying Medaka.

Thanks for the great assembler!
