### ISSUE TITLE
Lost 1M reads

### ISSUE THREAD

**Issue by woodoo46** [marbl/canu#121]
We have 5.5M PacBio raw reads. After correction and trimming, we lost about 1M reads. Is this normal?

**Comment by skoren** [comment]
The default parameters only correct the longest 40X of data so yes, losing some reads is normal. Some reads will also be removed for being too short or getting trimmed after correction to be too short. As long as your coverage is in the 25-30X range you're fine.

**Comment by woodoo46** [comment]
Our raw reads have coverage about 27X (counting bases). But after correction/trimming, we have 4.5M reads, and the coverage is about 16X.

**Comment by skoren** [comment]
That is with the low coverage settings I suggested in issue #86? With those parameters the corrected reads should be approximately the same coverage as input data and trimming will lose some coverage.

**Comment by woodoo46** [comment]
Yes. We used the same settings in #86. You are right. During the correction procedure, we did not lose very much; but the trimming was very effective. All the lost reads happened in that part.

**Comment by JohnUrban** [comment]
I am curious as to whether or not you are using the most recent Canu code…? The major loss in coverage seems similar to what was happening to me a while ago when using low coverage (high sensitivity) settings. See #63 and #80.

If you are unsure what commit you are using, you can find the commit ID by going into the canu main folder and doing:
$ git log --format="%H" -n 1

**Comment by woodoo46** [comment]
Is this right?

commit 1f08690b0c7a6048d1ba67df6c5526517b639631
Merge: 1f0352d b0d1c02
Author: Sergey Koren <sergek@umd.edu>
Date:   Thu Mar 31 14:29:57 2016 -0400

    Merge pull request #83 from jxtx/clang-unused

    Supress unused variable warnings for clang.

**Comment by JohnUrban** [comment]
The error may have been fixed in that commit seeing that it is a pretty old commit. Sergey might have a more definitive answer. 
A fair amount has changed since March 31st, so it might be worthwhile re-installing the latest code before making another assembly attempt.

**Comment by skoren** [comment]
That's right around version 1.2 so you're running 1.2 which fixed the issue @JohnUrban mentioned. Typically on the low coverage data, I've seen 60-66% retained bases (e.g. 12x from 17x input) so you're within that range though a bit on the low end.
