### ISSUE TITLE
error-correction of 160 Gb nanopore-reads

### ISSUE THREAD

**Issue by MichelMoser** [marbl/canu#1210]
Hi, 

I try to self-error correct a lot of nanopore reads but running out of disk space. 

Could you tell me which are the crucial files to store so i can process them in batches. 

I figured *.ovb and *.oc in the result directory are the results of MHAP, but missing the next step. 

If you could tell me the next step and which scripts are used to process *ovb , *oc to corrected fastq-files? (And if this is even possible or if i miss some crucial intermediates in between)

That would be much appreciated!  

Thank you very much, 
Michel

**Comment by skoren** [comment]
You can see the FAQ for suggestions to save space and what can be removed: https://canu.readthedocs.io/en/latest/faq.html#my-assembly-is-running-out-of-space-is-too-slow.

Generally if you removing the wrong thing Canu will re-run a previous step so you'll waste CPU time but not lose the other results but those should be a start.
