### ISSUE TITLE
Meryl-process failed: 'dataBlockLenMax' error

### ISSUE THREAD

**Issue by KrisChristensen** [marbl/canu#1211]
Hello Canu team,

I am running canu on a cluster (slurm) and I encountered an error that I am unable to figure out.  To begin with, here is the submission script (with the account info and personal info removed).

[RunCanu.txt](https://github.com/marbl/canu/files/2742341/RunCanu.txt)

Here is the output stating that there was an error in meryl-process:

[canu.txt](https://github.com/marbl/canu/files/2742350/canu.txt)

This was the job that was then submitted (account info removed):

[meryl-process.jobSubmit-01.txt](https://github.com/marbl/canu/files/2742375/meryl-process.jobSubmit-01.txt)

And the error from that job: 

[meryl-process.10690511_1.txt](https://github.com/marbl/canu/files/2742377/meryl-process.10690511_1.txt)

I tried increasing the meryl memory with the job submission, the meryl-process.sh file, and the specific job with no luck.  Any thoughts would be greatly appreciated.  Thank you for your time.

Kind regards,

Kris Christensen

**Comment by KrisChristensen** [comment]
Thanks for the timely reply.

Here are the answers to your questions:
I think I have enough space:
Disk Space (quota -vs)
                             Description                Space           # of files
                    Home (user ########)             230M/53G            7868/500k
                 Scratch (user ########)            421G/100T             6397/10M
                Project (group ########)              0/2048k               0/2048
               Project (group #########)           788G/1000G             545/500k

Contents of Otsh.canu.v.1.ms22.WORKING directory:
[#####@######## Otsh.canu.v.1.ms22.WORKING]$ ls -sh
total 19G
1.2G 0x000000.merylData   4.0K 0x001101.merylIndex  382M 0x011011.merylData   4.0K 0x101000.merylIndex
4.0K 0x000000.merylIndex  444M 0x001110.merylData   4.0K 0x011011.merylIndex  236M 0x101001.merylData
656M 0x000001.merylData   4.0K 0x001110.merylIndex  101M 0x011100.merylData   4.0K 0x101001.merylIndex
4.0K 0x000001.merylIndex  498M 0x001111.merylData   4.0K 0x011100.merylIndex  378M 0x101010.merylData
730M 0x000010.merylData   4.0K 0x001111.merylIndex  102M 0x011101.merylData   4.0K 0x101010.merylIndex
4.0K 0x000010.merylIndex  551M 0x010000.merylData   4.0K 0x011101.merylIndex  205M 0x101011.merylData
561M 0x000011.merylData   4.0K 0x010000.merylIndex  113M 0x011110.merylData   4.0K 0x101011.merylIndex
4.0K 0x000011.merylIndex  506M 0x010001.merylData   4.0K 0x011110.merylIndex  189M 0x101100.merylData
912M 0x000100.merylData   4.0K 0x010001.merylIndex  100M 0x011111.merylData   4.0K 0x101100.merylIndex
4.0K 0x000100.merylIndex  470M 0x010010.merylData   4.0K 0x011111.merylIndex  138M 0x101101.merylData
491M 0x000101.merylData   4.0K 0x010010.merylIndex  360M 0x100000.merylData   4.0K 0x101101.merylIndex
4.0K 0x000101.merylIndex  492M 0x010011.merylData   4.0K 0x100000.merylIndex  231M 0x101110.merylData
522M 0x000110.merylData   4.0K 0x010011.merylIndex  255M 0x100001.merylData   4.0K 0x101110.merylIndex
4.0K 0x000110.merylIndex  451M 0x010100.merylData   4.0K 0x100001.merylIndex  145M 0x101111.merylData
192M 0x000111.merylData   4.0K 0x010100.merylIndex  321M 0x100010.merylData   4.0K 0x101111.merylIndex
4.0K 0x000111.merylIndex  441M 0x010101.merylData   4.0K 0x100010.merylIndex  123M 0x110000.merylData
612M 0x001000.merylData   4.0K 0x010101.merylIndex  217M 0x100011.merylData    98M 0x110001.merylData
4.0K 0x001000.merylIndex  391M 0x010110.merylData   4.0K 0x100011.merylIndex  4.0K 0x110001.merylIndex
402M 0x001001.merylData   4.0K 0x010110.merylIndex  308M 0x100100.merylData    84M 0x110010.merylData
4.0K 0x001001.merylIndex  125M 0x010111.merylData   4.0K 0x100100.merylIndex  4.0K 0x110010.merylIndex
623M 0x001010.merylData   4.0K 0x010111.merylIndex  269M 0x100101.merylData    95M 0x110011.merylData
4.0K 0x001010.merylIndex  306M 0x011000.merylData   4.0K 0x100101.merylIndex   75M 0x110100.merylData
545M 0x001011.merylData   4.0K 0x011000.merylIndex  325M 0x100110.merylData    63M 0x110101.merylData
4.0K 0x001011.merylIndex  389M 0x011001.merylData   4.0K 0x100110.merylIndex   44M 0x110110.merylData
650M 0x001100.merylData   4.0K 0x011001.merylIndex   72M 0x100111.merylData    15M 0x110111.merylData
4.0K 0x001100.merylIndex  334M 0x011010.merylData   4.0K 0x100111.merylIndex  2.1M 0x111000.merylData
363M 0x001101.merylData   4.0K 0x011010.merylIndex  247M 0x101000.merylData   4.0K 0x111001.merylData

How many .meryl directories:
Otsh.canu.v.1.01.meryl
..
Otsh.canu.v.1.20.meryl

File (meryl-count.10689179):
[meryl-count.10689179_1.txt](https://github.com/marbl/canu/files/2746549/meryl-count.10689179_1.txt)

Coverage: ~34x

Running commands:
[######@#### 0-mercounts]$ meryl statistics Otsh.canu.v.1.01.meryl | head -20
Number of 22-mers that are:
  unique             1923575928  (exactly one instance of the kmer is in the input)
  distinct           2330205888  (non-redundant kmer sequences in the input)
  present            4035130474  (...)
  missing        17589855838528  (non-redundant kmer sequences not in the input)

             number of   cumulative   cumulative     presence
              distinct     fraction     fraction   in dataset
frequency        kmers     distinct        total       (1e-6)
--------- ------------ ------------ ------------ ------------
        1   1923575928       0.8255       0.4767     0.000248
        2    208227785       0.9149       0.5799     0.000496
        3     92445706       0.9545       0.6486     0.000743
        4     43410900       0.9732       0.6917     0.000991
        5     20817489       0.9821       0.7175     0.001239
        6     10808493       0.9867       0.7335     0.001487
        7      6093913       0.9893       0.7441     0.001735
        8      3927344       0.9910       0.7519     0.001983
        9      2739215       0.9922       0.7580     0.002230
       10      2059439       0.9931       0.7631     0.002478

[######@#### 0-mercounts]$ meryl print Otsh.canu.v.1.01.meryl | head -20
AAAAAAAAAAAAAAAAAAAAAA	379192
AAAAAAAAAAAAAAAAAAAAAC	11249
AAAAAAAAAAAAAAAAAAAAAT	10548
AAAAAAAAAAAAAAAAAAAAAG	7622
AAAAAAAAAAAAAAAAAAAACA	9189
AAAAAAAAAAAAAAAAAAAACC	1721
AAAAAAAAAAAAAAAAAAAACT	1296
AAAAAAAAAAAAAAAAAAAACG	747
AAAAAAAAAAAAAAAAAAAATA	6974
AAAAAAAAAAAAAAAAAAAATC	1116
AAAAAAAAAAAAAAAAAAAATT	2678
AAAAAAAAAAAAAAAAAAAATG	1269
AAAAAAAAAAAAAAAAAAAAGA	5946
AAAAAAAAAAAAAAAAAAAAGC	686
AAAAAAAAAAAAAAAAAAAAGT	846
AAAAAAAAAAAAAAAAAAAAGG	1322
AAAAAAAAAAAAAAAAAAACAA	8250
AAAAAAAAAAAAAAAAAAACAC	909
AAAAAAAAAAAAAAAAAAACAT	709
AAAAAAAAAAAAAAAAAAACAG	589

[######@#### 0-mercounts]$ meryl print greater-than-1 Otsh.canu.v.1.01.meryl | head -20
[######@#### 0-mercounts]$ 

Running meryl-process.sh 1 from interactive job:

[######@#### 0-mercounts]$ ./meryl-process.sh 1

Found perl:
   /cvmfs/soft.########.ca/easybuild/software/2017/Core/perl/5.22.4/bin/perl
   This is perl 5, version 22, subversion 4 (v5.22.4) built for x86_64-linux-thread-multi

Found java:
   /cvmfs/soft.#######.ca/easybuild/software/2017/Core/java/1.8.0_121/bin/java
   java version "1.8.0_121"

Found canu:
   /cvmfs/soft.#######.ca/easybuild/software/2017/avx2/Compiler/gcc5.4/canu/1.8/bin/canu
   Canu 1.8

Running job 1 based on command line options.
kmerCountFileWriter()-- Creating 'Otsh.canu.v.1.ms22.WORKING' for 22-mers, with prefixSize 12 suffixSize 32 numFiles 64
./meryl-process.sh: line 164: 17659 Killed                  /cvmfs/soft.#######.ca/easybuild/software/2017/avx2/Compiler/gcc5.4/canu/1.8/bin/meryl threads=1 memory=15 greater-than 1 output Otsh.canu.v.1.ms22.WORKING union-sum ./Otsh.canu.v.1.01.meryl ./Otsh.canu.v.1.02.meryl ./Otsh.canu.v.1.03.meryl ./Otsh.canu.v.1.04.meryl ./Otsh.canu.v.1.05.meryl ./Otsh.canu.v.1.06.meryl ./Otsh.canu.v.1.07.meryl ./Otsh.canu.v.1.08.meryl ./Otsh.canu.v.1.09.meryl ./Otsh.canu.v.1.10.meryl ./Otsh.canu.v.1.11.meryl ./Otsh.canu.v.1.12.meryl ./Otsh.canu.v.1.13.meryl ./Otsh.canu.v.1.14.meryl ./Otsh.canu.v.1.15.meryl ./Otsh.canu.v.1.16.meryl ./Otsh.canu.v.1.17.meryl ./Otsh.canu.v.1.18.meryl ./Otsh.canu.v.1.19.meryl ./Otsh.canu.v.1.20.meryl
meryl merge failed.

It looks like there might be an issue since greater-than-1 didn't print anything?

Thanks again for the help.

Kind regards,

Kris Christensen

**Comment by brianwalenz** [comment]
The 'killed' is _usually_ Slurm killing the job for exceeding memory limits.

My fault on the `greater-than-1` -- I should have written `greater-than 1`.  No matter, it seems to be finding and reading valid data.

What I think happened is: meryl choose poor parameters, resulting in large blocks of data.  With 20 inputs and 8 threads, it will try to allocate 20*8 = 160 buffers PLUS space to unpack each buffer PLUS space to process them.  I think some combination of reducing meryl threads and increasing the slurm job size request should make it work.

We can peek at those blocks with `meryl dumpFile 0x000000.merylData | head`.  For an ecoli, I get:
```
> meryl dumpFile 0x000000.merylData | head
            prefix   nKmers kCode uBits bBits                 k1 cCode                 c1                 c2
------------------ -------- ----- ----- ----- ------------------ ----- ------------------ ------------------
0x0000000000000000    14905     1    14    18 0x0000000000000000     1 0x0000000000000000 0x0000000000000000
0x0000000000000001     8727     1    14    18 0x0000000000000000     1 0x0000000000000000 0x0000000000000000
0x0000000000000002     8499     1    14    18 0x0000000000000000     1 0x0000000000000000 0x0000000000000000
0x0000000000000003     6440     1    13    19 0x0000000000000000     1 0x0000000000000000 0x0000000000000000
0x0000000000000004     5373     1    13    19 0x0000000000000000     1 0x0000000000000000 0x0000000000000000
0x0000000000000005     5932     1    13    19 0x0000000000000000     1 0x0000000000000000 0x0000000000000000
0x0000000000000006     4104     1    13    19 0x0000000000000000     1 0x0000000000000000 0x0000000000000000
0x0000000000000007     6053     1    13    19 0x0000000000000000     1 0x0000000000000000 0x0000000000000000
```
I'm curious what you have.

**Comment by KrisChristensen** [comment]
Thanks, I will try to reduce the threads and increase the slurm job size request.

Here is the information about from the 0x000000.merylData file:

[####@## 0-mercounts]$ meryl dumpFile Otsh.canu.v.1.01.meryl/0x000000.merylData | head -20
            prefix   nKmers kCode uBits bBits                 k1 cCode                 c1                 c2
------------------ -------- ----- ----- ----- ------------------ ----- ------------------ ------------------
0x0000000000000000  2488450     1    22     7 0x0000000000000000     1 0x0000000000000000 0x0000000000000000
0x0000000000000001  1216386     1    21     8 0x0000000000000000     1 0x0000000000000000 0x0000000000000000
0x0000000000000002   878258     1    20     9 0x0000000000000000     1 0x0000000000000000 0x0000000000000000
0x0000000000000003   409499     1    19    10 0x0000000000000000     1 0x0000000000000000 0x0000000000000000
0x0000000000000004   849179     1    20     9 0x0000000000000000     1 0x0000000000000000 0x0000000000000000
0x0000000000000005   696384     1    20     9 0x0000000000000000     1 0x0000000000000000 0x0000000000000000
0x0000000000000006   548282     1    20     9 0x0000000000000000     1 0x0000000000000000 0x0000000000000000

The file 0x000000.merylData in Otsh.canu.v.1.ms22.WORKING output (so the headers and nothing else):

            prefix   nKmers kCode uBits bBits                 k1 cCode                 c1                 c2
------------------ -------- ----- ----- ----- ------------------ ----- ------------------ ------------------

Thanks for the help.

Kind regards,

Kris

**Comment by brianwalenz** [comment]
I've been trying to reproduce this on a data set slightly larger than yours - 37x of human.  I'm seeing about 6GB memory usage for the `meryl union-sum` step.  As far as I can see, parameters are comparable.  The `dumpFile` you ran showed the parameter I was worried about isn't an issue.

A couple of options:

**Retry the whole 0-mercounts step** - rename 0-mercounts to something else and restart Canu.  This would fix a corrupt file that is reporting an incorrect data size, e.g., 'this data block is 1546 TB in size', and meryl tries to allocate that much memory.  You're running out of memory on a write though, so this isn't likely to fix the problem.

**Run manually with an alternate strategy** - There are many alternate ways of generating this result.  The goal of this step is to take your 20 intermediate kmer counts, add them all together, and discard all the unique kmers.  We can get approximately the same result by filtering the unique kmers from each intermediate file, then summing: (I'm using X for the name of your assembly):
```
meryl output X.gt1.01.meryl greater-than 1 X.01.meryl
...
meryl output X.gt1.20.meryl greater-than 1 X.20.meryl
meryl output X.meryl union-sum X.gt1.??.meryl
```
Or, instead of doing 'union-sum' on all 20 at once, you can do a two-stage union: pieces 1-5 -> A, 6-10 -> B, etc, then a second union-sum of A, B, C, D to get the full result.  Once X.meryl exists, you can run meryl-process.sh, and it will finish up this step.

**Share the data** - If you can share the data, I can debug and see why it's failing.  I need the 20 *.??.meryl directories.  These contain all the 22-mers in your genome.  However, given where/how it is failing, I don't think this will find the problem.

**Comment by KrisChristensen** [comment]
Running manually with an alternative strategy did work.  Thanks for the help!
