### ISSUE TITLE
Tweaking canu settings for new Nanopore basecaller? 

### ISSUE THREAD

**Issue by apredeus** [marbl/canu#1212]
There has been a public release of a new basecalling algorithm ("flip-flop") from Nanopore, that significantly improves read identity (different tests show increase of median identity by 3-5 percent). Read identities now are often in 93-95% range. Homopolymer issues are also expected to be significantly improved. 

What settings do you thing would be best to use for such reads? Is it worth trying to assemble with pacbio presets? I'm also interested in assembling 20x longer Nanopore reads + 60x Pacbio mixed dataset, so any suggestions on settings there would also be very welcome. 

Thank you in advance!

**Comment by skoren** [comment]
I'm not sure I believe those 93-95% identity are accurate across the whole dataset or between datasets. There may be some higher quality reads but for assembly/correction you want to capture the full distribution. At least in one analysis (http://omicsomics.blogspot.com/2018/12/flappie-vs-albacore-via-counterr.html), it seemed like the new base caller made no difference on a GC-skewed genome. So I'd start with defaults and see how those work.

That said, you could try to study what the error rates look like if you have a close reference. Map all the raw reads in chunks to the reference and report the % identity of each chunk (global identity so any unmapped chunks == 0%, unmapped bases should also hurt identity). Repeat the same for corrected reads with default parameters. That should give you an idea of the distribution of error rates. You can then set the appropriate error rates to about double suggested by that distribution (e.g. if most chunks in corrected reads are more than 95% identity set error to 10% aka ```correctedErrrorRate=0.10``` with ```rawErrorRate``` being the analog for raw data).

**Comment by apredeus** [comment]
Thank you for such detailed answer, this is very helpful.
