### ISSUE TITLE
Giant ovlStore.BUILDING despite tweaks for repetitive genome

### ISSUE THREAD

**Issue by zrlewis** [marbl/canu#1213]
Hi - 

I'm trying a second assembly with `Canu` using 50x Sequel coverage after the first one completed but ended up fairly fragmented (2.85 Gbp, 60146 contigs, 66kb N50) and with poor BUSCO scores (about 50% complete after polishing). I've found that the genome is highly repetitive (66% by repeat modeler/masker and 77% by Repeat Detector), so that may be the source of the problems. However, I wanted to try out some of the parameters you've suggested for repetitive genomes since last time the correction didn't work very well. 

```
[TRIMMING/READS]
--
-- In gatekeeper store './species1.gkpStore':
--   Found 7137954 reads.
--   Found 63659925378 bases (19.29 times coverage).
```

I'm running `1.8` on a SLURM cluster with the following submission script. 

```
canu-1.8/*/bin/canu \
    -p species1 -d species1_assembly_11 \
    genomeSize=3.3g \
    -pacbio-raw $READS/species1_concatenated_reads.fasta \
    correctedErrorRate=0.105  \
    gridOptions="--partition general,scavenge,bigmem -t 168:00:00" \
    corMhapFilterThreshold=0.0000000002 corMhapOptions="--threshold 0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50" \
    mhapMemory=60g mhapBlockSize=500 ovlMerDistinct=0.975 \
    batMemory=180 batThreads=20 merylMemory=90 merylThreads=20 gfaThreads=20 corMemory=20 cormhapMemory=40 \
    cormhapThreads=8 ovsMemory=40 ovlMerThreshold=500 cnsMemory=16 \
    gridOptionsmeryl="-t 03:00:00"  \
    gridOptionsovb="--mem-per-cpu=5G --cpus-per-task 4 -N 1" \
    gridOptionsobtovl="--mem-per-cpu=5G -n 2 -N 1"
```

My assembly failed during ovlStore sorting because I exceeded my disk quota. The `ovlStore.BUILDING` directory is 85 TB and it looks like 855 of 1779 buckets failed. The parent `correction` directory is 119 TB. With my previous assembly I think my scratch storage usage maxed out at about 90 TB total. Many of the `ovlStore.BUILDING` buckets are about 40 GB, with some reaching about 70 GB.

![bucketsizes](https://user-images.githubusercontent.com/24272721/50995946-a08edd00-14ee-11e9-98a3-ec159f780050.png)
Here are the bucket sizes in GB

Is there something I should be doing to reign in the size of these buckets? Should I reduce `ovsMemory`? Can I drop that value down, delete the `ovlStore.BUILDING` directory and run again? Perhaps some of my existing parameters are overriding the new `corMhapOptions=` that I've inserted based on the recommendation for repetitive genomes.

Log below. 

```
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_161' (from 'java') with -d64 support.
-- Detected gnuplot version '4.6 patchlevel 2   ' (from 'gnuplot') and image format 'png'.
-- Detected 20 CPUs and 125 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /usr/bin/sinfo.
-- Detected Slurm with 'MaxArraySize' limited to 10000 jobs.
--
-- Found   2 hosts with  32 cores and 1507 GB memory under Slurm control.
-- Found  12 hosts with  32 cores and  499 GB memory under Slurm control.
-- Found 154 hosts with  20 cores and  121 GB memory under Slurm control.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl     90 GB   20 CPUs  (k-mer counting)
-- Grid:  hap       16 GB   20 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   80 GB    8 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    24 GB    4 CPUs  (overlap detection)
-- Grid:  utgovl    24 GB    4 CPUs  (overlap detection)
-- Grid:  cor       20 GB    4 CPUs  (read correction)
-- Grid:  ovb        4 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       40 GB    1 CPU   (overlap store sorting)
-- Grid:  red       16 GB    4 CPUs  (read error detection)
-- Grid:  oea        8 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      180 GB   20 CPUs  (contig construction with bogart)
-- Grid:  cns       16 GB    4 CPUs  (consensus)
-- Grid:  gfa       32 GB   20 CPUs  (GFA alignment and processing)
--
-- In 'species1.seqStore', found PacBio reads:
--   Raw:        15006194
--   Corrected:  0
--   Trimmed:    0
--
-- Generating assembly 'species1' in '/gpfs/ycga/scratch60/fas/dunn/zrl3/canu/species1_assembly_11'
--
-- Parameters:
--
--  genomeSize        3300000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.1050 ( 10.50%)
--    utgOvlErrorRate 0.1050 ( 10.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.1050 ( 10.50%)
--    utgErrorRate    0.1050 ( 10.50%)
--    cnsErrorRate    0.1050 ( 10.50%)
--
--
-- BEGIN CORRECTION
--
--
-- Creating overlap store correction/species1.ovlStore using:
--   1779 buckets
--   1779 slices
--        using at most 41 GB memory each
--
-- Overlap store sorting jobs failed, tried 2 times, giving up.
--   job correction/species1.ovlStore.BUILDING/0237 FAILED.
--   job correction/species1.ovlStore.BUILDING/0238 FAILED.
--   job correction/species1.ovlStore.BUILDING/0254 FAILED.

[...]

```
Thanks in advance!
Zack

**Comment by skoren** [comment]
Which step of the assembly are you on? The initial log seems to indicate you are done with correction or is that the first assembly you tried? The parameters for repetitive genomes aren't going to help keep more corrected reads in most cases, instead you probably want to include ```corMinCoverage=0 corOutCoverage=100``` which should be OK to add now without re-running.

As for space, the store building should take about double the size of the results folder in 1-overlapper. There are files you can clean up, see the FAQ but in summary, you can remove the blocks folder in 1-overlapper and for any bucks which did not fail (they should have sliceSizes file and no errors to stdout/stderr), you can remove the corresponding results file (e.g. bucket000001 means you can remove results/000001.ovb).

**Comment by zrlewis** [comment]
Sorry to not make that more clear: The gatekeeper store stats at the top refer to the first Canu assembly that I tried. For this one, I'm still on correction.

Thanks for the clean up suggestions. I'll see how much space I can free up then re-run with the new parameters above. 

Zack
