### ISSUE TITLE
PBS: job killed: walltime 86415 exceeded limit 86400

### ISSUE THREAD

**Issue by maolingfengZJU** [marbl/canu#1214]
I tried to run the command "canu -trim -p 0106-trim -d 0106-trim genomeSize=0.5g -pacbio-corrected 1130_correct.correctedReads.fasta.gz corOutCoverage=200 correctedErrorRate=0.15" in the head node,
and the overlap jobs were always killed, like that below
```
[mlf@node21 1-overlapper]$ tail  overlap.30.out-30
Thread 07 processes reads 976326-996250
Thread 02 writes    reads 816926-836850 (1916 overlaps 886652/3614789/0 kmer hits with/without overlap/skipped)
Thread 02 processes reads 996251-1016175
Thread 03 writes    reads 876701-896625 (28080 overlaps 880048/3609796/0 kmer hits with/without overlap/skipped)
Thread 03 processes reads 1016176-1036100
Thread 01 writes    reads 836851-856775 (21167 overlaps 873135/3655543/0 kmer hits with/without overlap/skipped)
Thread 01 processes reads 1036101-1056025
Thread 04 writes    reads 896626-916550 (32685 overlaps 917421/3656297/0 kmer hits with/without overlap/skipped)
Thread 04 processes reads 1056026-1075950
=>> PBS: job killed: walltime 86415 exceeded limit 86400

```
Following the suggestion from  https://canu.readthedocs.io/en/latest/faq.html#my-assembly-continuity-is-not-good-how-can-i-improve-it
"Smash haplotypes together parameters corOutCoverage=200 correctedErrorRate=0.15"
may be the correctedErrorRate is too high to make the calculation time too much,
so any suggestion for that, some parameters to unlimit the walltime or something else?

**Comment by skoren** [comment]
Just what it sounds like, you hit the default wall time limit on your grid. You can pass through a request for more time (see #1207 and FAQ). Something like ```gridOptions="-l walltime=96:00:00"``` for example.
