### ISSUE TITLE
Genome size

### ISSUE THREAD

**Issue by Lcornet** [marbl/canu#1215]
Dear Canu team, 

Concerning genome size parameter, does is take haplotype variation ?
I mean with a high difference between haplotypes, do i have to double the genome size ?

Thanks for help

**Comment by brianwalenz** [comment]
Nope.  The supplied genome size is used only for estimating coverage in reads (which, in turn, controls how many corrected reads to generate) and reporting of statistics.

If you haven't read it yet, read https://canu.readthedocs.io/en/latest/faq.html#what-parameters-can-i-tweak (and skim the rest).
