### ISSUE TITLE
Pacbio read length

### ISSUE THREAD

**Issue by woodoo46** [marbl/canu#1217]
A general question, does the pacbio read length affect the program's running time significantly? For example, if the average raw read length is about 15k; the pipeline could take very long time to finish? I have seen a cormhap job (assemble stage), with 8 cores, a job could take 2 days finish. 

Thanks!

George

**Comment by skoren** [comment]
I saw you mentioned it is in the assembly stage, I assume this is using the ```-fast``` option?

Read length doesn't really have much of a runtime impact, each read is sketched to a fixed size. System I/O and repetitiveness usually explains these variations in runtime in my experience. You could kill the job and let canu re-launch it on another node to see if it completes faster.
