### ISSUE TITLE
About the recommended option for assembling heterozygous genomes

### ISSUE THREAD

**Issue by yjx1217** [marbl/canu#1221]
Hello,

According to Canu's FAQ, the option combination `corOutCoverage=200 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50"` is recommended to be used for assembling heterozygous genomes.  Having noticed the placement of the double quotes, I was wondering how to interpret this option combination from Canu's perspective when executing the assembly process. For example, does the suggested option be equivalent to `corOutCoverage=200 batOptions="-dg 3 -db 3 -dr 1 -ca 500 -cp 50"` as `corOytCoverage` and `batOptions`  are two independent options?  Thanks in advance!

Best,
Jia-Xing

**Comment by brianwalenz** [comment]
Backing up a bit, when you run a command, the shell splits the command line into words, using spaces as the delimiter, then passes those words to the program for it to do something with.  A command like `command a b cd` would see three words as inputs, "a", "b" and "cd".  In unix convention, commands expect parameters with a single or double dash prefix, "-a", "-b", "--cd".  In particular, something like '-n 3' would be passed to the program as two words, "-n" and "3".  It's up to the program to associate the value 3 with parameter n.

Canu is different in that it wants things as `parameter=value` -- as one word.  This usually works painlessly; corOutCoverage=200, useGrid=true, etc, all behave as they should.  The shell, they're a single word, and passes it to Canu.  But the batOptions value (setting low level parameters to be passed to the bogart module) isn't one word according to the shell, and the quotes are needed to keep everything as one string.  (The shell then removes the quote marks.)

So, the weird quoting of `"batOptions=a b c"` makes perfect sense to the shell - it treats this as one 'word' and passes the whole thing to Canu.  Canu scans the 'word' for the equals sign and sets the parameter `batOptions` to the string `a b c`.

I've noticed that your two batOptions variants actually do behave the same, but this is probably shell specific.

**Comment by yjx1217** [comment]
Dear Brian,

Thank you very much for the prompt and detailed explanation. How shell would treat this scenario is indeed why I asked my original question. I implemented a bash wrapper for canu in a pipeline software that I developed.  The wrapper goes like this:

customized_canu_parameters='option1=XXX;option2=YYY' 

OLDIFS=$IFS;
IFS=";"
customized_canu_parameters_array=($customized_canu_parameters)
IFS=$OLDIFS;
$canu_dir/canu -p $prefix -d $out_dir \
        useGrid=false \
        maxThreads=$threads \
        genomeSize=$genome_size \
        gnuplot=$gnuplot_dir/gnuplot \
        "${customized_canu_parameters_array[@]}" \
        -${long_reads_type} $long_reads 

So I noticed that when I set `customized_canu_parameters='corOutCoverage=200;"batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50"'` and `customized_canu_parameters='corOutCoverage=200;batOptions="-dg 3 -db 3 -dr 1 -ca 500 -cp 50"'`, canu can be executed in both scenarios. However, the `customized_canu_parameters='corOutCoverage=200;"batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50"'` setting will lead to an error at the unitigging stage, likely related with how batOption was parsed.  I am waiting for the run with `customized_canu_parameters='corOutCoverage=200;batOptions="-dg 3 -db 3 -dr 1 -ca 500 -cp 50"'` setting to finish now.  Hopefully it can work this way.  

So if you have additional comments for my specific use case, please let me know. Thanks again!

Best,
Jia-Xing

**Comment by brianwalenz** [comment]
Ah yes, this brings back unpleasant memories.  You (probably) need to quote the quote marks.  And I'm not sure how `"${array[@]}"` is expanded.  I hope it will be `"option1=XXX" "option2=XXX"` (two words) and not `"option1=XXX option2=XXX"` (one word).

An alternate way to pass parameters to Canu, that gets around quoting issues, is to put all the parameter=value settings in a file, one per line.
```
> cat sample.spec
#Comments allowed too.
option1=XXX
batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50
```
Then run `canu -s sample.spec otherOptions=true -pacbio-raw files ...`.  Options on the command line supersede options in the spec file.  Of note, there are no quote marks here.  Canu treats each line as a single `parameter=value`.

You can also include input data files, in which case, the spec file becomes a nice record of what parameters and inputs were run:
```
> cat sample.spec
#Comments allowed too.
option1=XXX
batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50
-pacbio-raw input1.fasta
-pacbio-raw input2.fasta
```
In this case, your canu command would be just `canu -p prefix -d directory -s sample.spec`.

**Comment by yjx1217** [comment]
Great! Many thanks for the additional tips, Brian! 
I will let you know if my current setting `customized_canu_parameters='corOutCoverage=200;batOptions="-dg 3 -db 3 -dr 1 -ca 500 -cp 50"'` works in the end when it finishes. 

Best,
Jia-Xing

**Comment by yjx1217** [comment]
Hi Brian,
My second attempt also failed but your suggestion of using a spec file works well. So I've adopted this way. Many thanks for the help. I will close this ticket. 

Best,
Jia-Xing
