### ISSUE TITLE
Canu resume problem

### ISSUE THREAD

**Issue by cjchen5** [marbl/canu#1228]
Hi, 
I use canu 1.7.1 on PBS, I notice that canu could resume the incomplete assemblies. But it seem that it only resumes jobs it already finished rather than where it ended. 
For example, after my Canu trimmming jobs was kill because it exceeded the walltime. It ends at running overlaop out 003-006. When I resume it today the overlaop out 003-006 restart from 0 rather than from where them ended. In this case, if overlaop out 003-006 always can't finished in my  walltime. I guess restart the canu job will only rerun overlaop out 003-006 again and again.
Is there any way to solve this?
Thanks.

**Comment by skoren** [comment]
I think that is the expected behavior. Canu processes are atomic, they don't restart in the middle of a single job. Rather, the pipeline can recognize when some jobs have completed and not re-run them. In other words if job 003 is running and gets killed due to wall time, it didn't complete so it has to run again. However, any jobs that finished in less than the wall time won't be re-run.

**Comment by cjchen5** [comment]
Okay, but is there any other way to solve this problem? For example, make overlap.000003.out smaller so it will finish faster? Or rather run 003 to 006 one by one than let them running at same time?
Thanks.

**Comment by skoren** [comment]
Can you increase the wall time or is it already at the maximum allowed by the system? To change the size of the partitions you'd have to re-run all of them. 

If you have a grid, Canu should already be submitting the jobs one at a time to the grid (unless you're running with useGrid=false). You can certainly run each job of 003 etc one at a time in parallel jobs, they are independent. You can also remove the overlap.sh and increase the CPUs allocated per job using ```ovlThreads=32``` or whatever you have available.

**Comment by cjchen5** [comment]
Thank you! The wall time is already at the maximum allowed by the system. 
BTW, if I want to make the size of the partitions of canu trimming smaller, I just need to increase corPartitions <integer=128>? Is that correct?

**Comment by skoren** [comment]
No, that will not affect the overlaps. You don't directly set the number of partitions but instead specify how many bases to either load into memory or stream against it. That is set by ```OvlRefBlockLength``` parameter. The default for genomes < 40mb is 1gb and 5gb (5000000000) for genomes < 500mb. If you set it to 10-fold less you'll get more jobs.
