### ISSUE TITLE
Start from special step

### ISSUE THREAD

**Issue by mawad89** [marbl/canu#1229]
Hi 
Canu Run from one month and after month the job killed and give me this error 
`ERROR: Failed to detect a suitable output format for gnuplot.`
`ERROR:  Looked for png, svg and gif, found none of them.`
`Set option gnuplotImageFormat=<type>, or gnuplotTested=true to skip this test and not generate plots.`
I will resubmit it with gnuplotTested=true but I want to start from last successful stage 
`(Finished stage 'overlapErrorAdjustmentConfigure', reset canuIteration.)`
`'oea.jobSubmit-01.sh' -> job ended(853489) tasks 1-13.`

**Comment by skoren** [comment]
See the FAQ: https://canu.readthedocs.io/en/latest/faq.html#my-run-of-canu-was-killed-by-the-sysadmin-the-power-going-out-my-cat-stepping-on-the-power-button-et-cetera-is-it-safe-to-restart-how-do-i-restart, you can re-run the same Canu command you originally used and it will resume where you left off.

**Comment by mawad89** [comment]
Thank but when I trying to restart it and adding (**gnuplotTested=true**) to the  command, It give me this error
` ERROR:  Parameter 'gnuplotTested' is not known.`
is this normal??

**Comment by skoren** [comment]
I don't think that's related to the restart. 

What exact command did you use originally and what command did you run now? What folder are you running the command from? What is in the canu assembly folder?

**Comment by mawad89** [comment]
Thanks very much for your response
**The origenal command** 

> Canu -p awad_g -d awad_g stopOnReadQuality=false -nanopore-raw $workdir/fastq/awad_g.fastq

**then I try with the following** 

> Canu -p awad_g -d awad_g gnuplotTested=true stopOnReadQuality=false -nanopore-raw $workdir/fastq/awad_g.fastq

`Error Parameter 'gnuplotTested' is not known`

> Canu -p awad_g -d awad_g gnuplotImageFormat='png' stopOnReadQuality=false -nanopore-raw $workdir/fastq/awad_g.fastq

`Unable to assemble uncorrected reads`

> Canu -p awad_g -d awad_g gnuplotImageFormat='png' -nanopore-raw $workdir/fastq/awad_g.fastq

`Unable to assemble uncorrected reads`

**I copy the trimmed reads to working dir and run the the below commands**

> Canu -p awad_g -d awad_g gnuplotImageFormat='png' stopOnReadQuality=false -nanopore-corrected awad_g.trimmedReads.fasta.gz

`Unable to assemble uncorrected reads`

> Canu  -p awad_g -d awad_g gnuplotImageFormat='png' -nanopore-corrected awad_g.trimmedReads.fasta.gz

`Unable to assemble uncorrected reads`

**Comment by skoren** [comment]
That would seem to indicate the sequence store you have is invalid. When you specify the -d folder with a seqStore, the option for reads isn't used which is why your nanopore-corrected option is not working either. What files do you have in ```awad_g/*Store```? What is the contents of ```awad_g/*Store/info.txt```?

As a workaround you could run ```canu -assemble -p awad_g -d awad_g_restart genomeSize=200m gnuplotImageFormat='png' -nanopore-corrected awad_g.trimmedReads.fasta.gz``` which should resume the assembly though it will re-compute parts of the assembly.

**Comment by mawad89** [comment]
this is info.txt

>sqMagic            = 0x504b473a756e6162
sqVersion          = 0x0000000000000006
sqLibrarySize      = 168
sqReadSize         = 40
sqMaxLibrariesBits = 6
sqLibraryNameSize  = 128
sqMaxReadBits      = 37
sqMaxReadLenBits   = 21
numLibraries       = 1
numReads           = 1258856
numBlobs           = 5
numRawReads        = 1258856
numCorrectedReads  = 0
numTrimmedReads    = 0
numRawBases        = 17146912512
numCorrectedBases  = 0
numTrimmedBases    = 0

Store contents

> blobs.[0000-0004], errorLog, info, info.txt, libraries,libraries.txt,load.dat, readNames.txt, and reads

Your proposed command working now but started from the first assembly step. however, this may need another 10-15 days to back to the same killed point but better than start from scratch.
Thanks

**Comment by skoren** [comment]
That store indeed has no corrected data which explains the error. However, I'm not sure how the store lost the corrected read information if you already have corrected and trimmed data. We've never seen that before. Do you have the full log from the Canu run that got killed, I want to see if anything looks amiss there.

What do you mean the first assembly step? If you use the command I gave it should start from the unitigging folder and computing meryl (0-mercounts) and overlaps (1-overlapper), it won't run anything from correction nor trimming.

**Comment by mawad89** [comment]
I am sorry the log file changed after restart processes I can't find the original one 

> What do you mean the first assembly step? If you use the command I gave it should start from the unitigging folder and computing meryl (0-mercounts) and overlaps (1-overlapper), it won't run anything from correction nor trimming.

I mean what you exactly explain here it started from meryl (0-mercounts), but the killed run already finished the first 3 steps.

However it is run now and I hope it is will continue to the end

**Comment by skoren** [comment]
The info file you posted seems to correspond to 1.7 but the txt log indicates that was generated by version 1.6 which would have had multiple stores for each step rather than one common one. 

Did you switch canu versions somewhere along the way?  It seems like you had a 1.6 run then switched to 1.7 which tried to build its single store but did not have the corrected reads where they were expected and couldn't resume.

**Comment by mawad89** [comment]
I don't do any change, however, It is still run now with assemble option
Thanks very much

**Comment by skoren** [comment]
Since it is running, I'm going to close the issue. The restart failed because there was a 1.6 and 1.7 gkpStore somehow in the working folder.
