### ISSUE TITLE
filterCorrectionOverlaps exceeds requested memory

### ISSUE THREAD

**Issue by mschatz** [marbl/canu#123]
My sysadmin informed me that filterCorrectionOverlaps (during correction/2-correction from the current github HEAD repo) is using over 30 GB of RAM for a task that requested 4GB. The genome size is about 440Mbp and we have about 80X coverage. Can you make this step self tuning? Let me know if you need any other details.

Mike

**Comment by brianwalenz** [comment]
I don't see any memory usage in the code - just a list of overlaps for a single read and a histogram of the same.  The gatekeeper store 'blobs' file (with sequence data) is mmap()d into the process, but it shouldn't be used here - so virtual size will be large but resident should be small.  That file should be about 30gb.

**Comment by mschatz** [comment]
Okay, I'll try to keep a closer eye on it for next time. Maybe it was in
one of the previous tasks

Thanks,

Mike
