### ISSUE TITLE
option for automated trimming of circular contigs?

### ISSUE THREAD

**Issue by Kirk3gaard** [marbl/canu#1230]
Hi

It would be super helpful if circular contigs were automatically trimmed (https://canu.readthedocs.io/en/stable/faq.html#my-circular-element-is-duplicated-has-overlap) as most users will use default settings and expect this behaviour.

Best regards
Rasmus

**Comment by skoren** [comment]
Yes, this is a feature for the next release, see the projects tab. In the meantime the cigar string for these alignments is provided in the GFA file so you could use that to compute the trim points yourself as well.

**Comment by brianwalenz** [comment]
Noted in project entry https://github.com/marbl/canu/projects/2#card-4243356.  Will update this issue when something happens.
