### ISSUE TITLE
Illegal division by zero at line 188 Linux-amd64/lib/site_perl/canu/Meryl.pm

### ISSUE THREAD

**Issue by rozaimirazali** [marbl/canu#1231]
Hello.

I am encountering an illegal division by zero at line 188 in the Meryl.pm file.

The command that I used was : 

`canu -correct -d dir.m54107_181009_075636 -p m54107_181009_075636 corMemory=12g genomeSize=3g stopOnReadQuality=false gnuplotTested=true useGrid=true gridEngine=lsf gridOptions='-e error.txt -o out -q memnode -P correction -n 4' -pacbio-raw m54107_181009_075636.subreads.bam`

I am using Canu version 1.7.1 (June 2018) and running on LSF. When I run the correction on a smaller genome (e.coli) it works fine, so I don't think it is the problem with the program.

Is it something with my reads? 

I tried to look at the perl file but it is not very clear what the code is doing. I appreciate it if someone help me to figure out this issue.

Thanks!

**Comment by skoren** [comment]
That code is mostly just printing a histogram to screen, so if it is failing the previous compute step likely failed to generate output. What's in ```dir.m54107_181009_075636/correction/0-mercounts/```? Post the contents of any err/out files that are there to get more info on what went wrong.

**Comment by brianwalenz** [comment]
I suspect all your kmers are unique.  If they are, you won't get any correction or assembly anyway.  Decreasing mhapMerSize from 16 (the default) to 15 _might_ work, but that value (with a 3 Gbp genome) will increase computation time and disk requirements significantly.

What's in `dir.m54107_181009_075636/correction/0-mercounts/*histogram`?

How much coverage do you have?  Canu logs this to the screen and also to `*.report` in the root assembly directory.

**Comment by rozaimirazali** [comment]
> That code is mostly just printing a histogram to screen, so if it is failing the previous compute step likely failed to generate output. What's in `dir.m54107_181009_075636/correction/0-mercounts/`? Post the contents of any err/out files that are there to get more info on what went wrong.

Sorry for the late reply, I re-ran canu -correct again but this time with version 1.8 (previously it was ver 1.7). However, I still have the same issue. The following is the stderr file

[stderr.txt](https://github.com/marbl/canu/files/2865090/stderr.txt)

**Comment by rozaimirazali** [comment]
This is my comment:

canu -correct -d MNDY0202_ver1.8 -p MNDY0202_ver1.8 corMemory=12g genomeSize=3g stopOnReadQuality=false useGrid=true gridEngine=lsf gridOptions='-e stderr -o stdout -q fatnode -P assembly -n 3' -pacbio-raw ../../MNDY0202.bam

**Comment by rozaimirazali** [comment]
> I suspect all your kmers are unique. If they are, you won't get any correction or assembly anyway. Decreasing mhapMerSize from 16 (the default) to 15 _might_ work, but that value (with a 3 Gbp genome) will increase computation time and disk requirements significantly.
> 
> What's in `dir.m54107_181009_075636/correction/0-mercounts/*histogram`?

The kmers are all shown as missing:

[MNDY0202_ver1.8.ms16.histogram.txt](https://github.com/marbl/canu/files/2865118/MNDY0202_ver1.8.ms16.histogram.txt)


> 
> How much coverage do you have? Canu logs this to the screen and also to `*.report` in the root assembly directory.

--   Found 2021910 reads.
--   Found 77698657955 bases (25.89 times coverage).

**Comment by skoren** [comment]
Are you providing Canu with a bam file input? Canu only support fastq/fasta (or gzip/bzip version of those). Extract the fasta from the bam and try running it again. I'm not sure why Canu didn't crash on the input since it seems like you end up with no valid bases.

**Comment by rozaimirazali** [comment]
My mistake. I am running another assembler at the same time and it uses the BAM files instead.

Do you recommend to provide merged fastq of all the subreads or can Canu support multiple fastq input e.g.

--pacbio-raw subread1.fastq, subread2.fastq,subread3.fastq etc

**Comment by brianwalenz** [comment]
Easy peasy, but not in the format you suggested.  Use `-pacbio-raw file1.fastq file2.fastq` (no comma) or just `-pacbio-raw *fastq` (gzip, bzip2 and xz supported too).

Scan through the Quick Start and, more importantly, the FAQ, at https://canu.readthedocs.io/.  Lots of great advice there.

**Comment by brianwalenz** [comment]
Canu will now reject input files that end in 'bam'.
