### ISSUE TITLE
slow assembly with low ONT coverage

### ISSUE THREAD

**Issue by Lcornet** [marbl/canu#1232]
Dear CANU team,

I have a Pacbio 70 x and ONT 10x to assemble Cassava genome.
The ONT contain very long reads.

I run this command (on 60 cpus node with 512 Gb of RAM): 
#canu
/media/vol2/scratch/lcornet/cassava/CANU-1.8/canu/Linux-amd64/bin/canu -pacbio-raw /media/vol2/scratch/lcornet/cassava/Dataset/raw-pacbio/60444/subreads_47smrt_raw.fq -nanopore-raw ONT-4FC.fastq genomeSize=1.4g \
maxMemory=450 maxThreads=60 -p PbONT -d PbONT \
useGrid=false

In the trimming part, the assembly is very slow (167 processes; 4 concurrently). 25 process done in 2 weeks. I have the same problem while running only ONT 10 fold.
Is this linked to the low coverage in ONT ? 
Do i have to increase this coverage or run ONT as pacbio (with corMhapSensitivity=normal correctedErrorRate=0.105) to speed up ?

Thanks ,

**Comment by skoren** [comment]
There are a couple of issues, first a 1.5G genome on 60 cores is going to always take some time. You're only running 4 jobs at a time. The best way to speed it up is to allow Canu to use your grid to submit these jobs in parallel so they'd all run simultaneously.

That said, you probably don't want the default given that the majority of your data is PacBio and thus overall quality will look more like PacBio than Nanopore. You can add the options you listed above (```corMhapSensitivity=normal correctedErrorRate=0.105``` along with ```ovlMerDistinct=0.975```) (see FAQ). No need to re-run correction, just restart in a new folder with the corrected reads specified as pacbio-corrected (e.g. ```canu -d PbONT_restart -pacbio-corrected PbONT/PbONT.correctedReads.fasta.gz```)

**Comment by Lcornet** [comment]
Thanks,
Unfortunately, impossible to run with GRID for a series of reasons.
I will try restart as pacbio-corrected.

Best,
Luc
