### ISSUE TITLE
Optimising canu for promethion and gridion data

### ISSUE THREAD

**Issue by atracey99** [marbl/canu#1234]
Hi

I have around 60x of Promethion data and around 6x of Gridion data (both ONT) for a 400Mb worm genome.  I corrected these reads using canu-1.8 (giving around 38x coverage) and then attempted to assemble this:

```canu-1.8/Linux-amd64/bin/canu -p scurr -d scurr-canu genomeSize=400m -nanopore-corrected scurr.correctedReads.fasta.gz -maxMemory=250g -maxThreads=32 java=/software/jre1.8.0_74/bin/java -batMemory=100 -batThreads=32 useGrid=remote rawErrorRate=0.500 correctedErrorRate=0.155```

I ran this on a 64-bit Linux cluster.  The job ran for a couple of months and it looked like it would possibly complete in 3 months total.  Is there a way to tweak my Canu settings so that performance is improved?  It doesn't seem that 3 months is a reasonable time to generate an assembly.

**Comment by skoren** [comment]
It's hard to say how much compute time was actually used without more info. For example, how long did the jobs wait in the queue, how many CPUs/jobs were getting simultaneously scheduled, etc?

That said, there are a couple of options you can change. First, you're setting a high corrected error rate which increases runtime. You can try 0.12 (the default) or even 0.105 potentially if you're using the new flip-flop base caller along with ```ovlMerDistinct=0.975``` (https://canu.readthedocs.io/en/latest/faq.html#my-assembly-is-running-out-of-space-is-too-slow). Alternatively, you can use the ```-fast``` option which may reduce the continuity but will significantly speed up the run.
