### ISSUE TITLE
Running canu on a laptop ?

### ISSUE THREAD

**Issue by FlorianBrnrd** [marbl/canu#1235]
More of a question than a real issue but I tried to run canu on my macbook pro (MacOS X 13.6) and based on the output I assume this is just too much for a laptop ?

I was looking to do error correction on RNA-seq data generated with nanopore and I used this command:

`canu-1.8/*/bin/canu -correct -d CanuCorrected -p run14 genomeSize=100m -nanopore-raw /Users/florian/run14.fastq`

I also tried to change MerylMemory and MerylThread but it didn't appear to do anything.
Here's the output I get:

```
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_171' (from 'java') with -d64 support.
--
-- WARNING:
-- WARNING:  Failed to run gnuplot using command 'gnuplot'.
-- WARNING:  Plots will be disabled.
-- WARNING:
--
-- Detected 4 CPUs and 8 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
-- ERROR
-- ERROR
-- ERROR  Found 1 machine configuration:
-- ERROR    class0 - 1 machines with 4 cores with 8 GB memory each.
-- ERROR
-- ERROR  Task meryl can't run on any available machines.
-- ERROR  It is requesting:
-- ERROR    merylMemory=12-24 memory (gigabytes)
-- ERROR    merylThreads=1-8 threads
-- ERROR
-- ERROR  No available machine configuration can run this task.
-- ERROR
-- ERROR  Possible solutions:
-- ERROR    Change merylMemory and/or merylThreads
-- ERROR

ABORT:
ABORT: Canu 1.8
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   task meryl failed to find a configuration to run on.
ABORT:
```

**Comment by skoren** [comment]
It's complaining that it would like to use more memory than you have available given the genome size. You can probably run with less but it will be slow. Set the memory limits explicitly (maxMemory=8 merylMemory=8 and may be others if it gives you an error again).
