### ISSUE TITLE
How to get coverage-per-contig report?

### ISSUE THREAD

**Issue by cjchen5** [marbl/canu#1236]
Hi,
I use canu 1.7.1 on PBS. I only find the coverage for global coverage for input reads. Could you please tell me how to get coverage-per-contig report from canu assembly?
Thanks!

**Comment by skoren** [comment]
See the documentation on outputs: https://canu.readthedocs.io/en/latest/tutorial.html#outputs. The layout.tigInfo file will give you the average coverage per contig. This is also reported in the fasta header. If you want more detailed coverage (like per base), see the ```tgStoreDump``` command :https://canu.readthedocs.io/en/latest/commands/tgStoreDump.html

**Comment by cjchen5** [comment]
That's very useful! Thank you so much for your help!

**Comment by cjchen5** [comment]
Could you please tell me what's the coverage mean in <prefix>.contigs.layout.tigInfo?  Is that fraction of the genome sequenced by at least one read **or** average number of reads that cover any given region? And is 'numChildren' number of reads in that contig?
Thanks.

**Comment by skoren** [comment]
It's the mean base coverage in each of the contigs since different parts of the contig may have different coverage. The numChildren is the number of reads yes.

**Comment by cjchen5** [comment]
How do you calculate this coverage? ctg_coverage = sum(reads_in_contig_len) / contig_len?
Thank you!

**Comment by skoren** [comment]
See the code in https://github.com/marbl/canu/blob/master/src/stores/tgTig.C, line 253. It computes the coverage at each base and averages that. I think that's essentially the same as the sum of reads in contig / length.

**Comment by cjchen5** [comment]
Awesome! Thank you so much!

**Comment by davidherndon23** [comment]
Receiving an error from tgStoreDump (canu v2.0), looking to generate per base contig coverage plots. Error reads:
sqStore_loadInfo()-- Error: Unsupported historical version 6 detected.

**Comment by skoren** [comment]
That error indicates you've got an older version of store that you're running a recent canu version on. Generally, canu isn't backwards compatible with older assemblies so you need to get the version corresponding to whatever version you used for assembly.
