### ISSUE TITLE
Keep the first canu executive running when using grid

### ISSUE THREAD

**Issue by ilyavs** [marbl/canu#1239]
Hello,
I am using canu in a snakemake (python variation of make) workflow. When running canu on the grid (SGE), snakemake seems to monitor the first executive job to identify shell command completion. Once the first executive job completes, it begins to look for the final output files (defined by me). Obviously, the final output does not exist yet.

A workaround that comes to mind is to keep the first executive job running until all the canu jobs finish. Is that possible somehow?

Alternatively, is there a shell command that can detect the completion of the last job generated by canu on the grid?

Just updated canu. The output of canu -version is: Canu snapshot (snapshot).
Thanks,
Ilya.

**Comment by skoren** [comment]
Canu relies on the grid to handle its dependencies so the first executive no longer exists as soon as the next step is submitted. Keeping the executive around doesn't make sense as it would have to busy-wait looking for a file, you could implement that logic in your snakemake pipeline potentially (I don't know details of snakemake) but busy waits in general aren't ideal.

You have two other options. The first is to run Canu off grid (useGrid=false) in which case there is only a single canu executive which will not exit until the assembly is completed. Alternatively, Canu defines a hook to let you run another command when it completes the assembly or fails (```onSuccess``` and ```onFailure```). See issue #471 for details.
