### ISSUE TITLE
Canu Error

### ISSUE THREAD

**Issue by Lau16** [marbl/canu#1248]
Hi, I try to perform a bacterial genome assembly with Canu ( v1.8) in two steps.: error correction and then generate and assemble trimmed reads with  fastq data coming from 1D  and for 1^D2 after basecalling with **guppy**.
I encountered a problem with error correction step with the data of 1D^2: "ERROR:  Read coverage (2.84) is too low to be useful".
I'm aware that  the input data of fastq 1D^2 is quite low (31 M) but the genome size is correct and 1D^2 reads, I suppose that they have a better quality than 1D once. 
What is the reason and which option can I use to fix the canu correction step.
Waiting for you response.

**Comment by skoren** [comment]
How are you running Canu, just on the 1d or 1d^2 reads? 2-fold coverage really isn't enough to do anything with, the correction isn't going to improve the reads. You can either mix the 1d and 1d^2 together at the same time or provide the 1d^2 reads as already corrected (assuming they are at least 95% identity or so) and combined them with the 1d reads run through Canu's correction.

**Comment by skoren** [comment]
Idle
