### ISSUE TITLE
The number of Ovb files is different with that of bucke

### ISSUE THREAD

**Issue by Jolvii85** [marbl/canu#1249]
Hi 
I am using canu to correct my Nanopore reads, since I have a lot sequencing reads, I want to reduce the disk usage as much as possible.
I am now reach the ovs step, I have 1-bucketize.success file created by canu. I found sth weird that I only have 1375 bucket, but 3311 ovb files.  Following this question (https://github.com/marbl/canu/issues/735), you said the number of ovb files should be the same with bucket files.  
Can you tell me, is it looks normal? If yes, can I remove all the ovb files to save some space?  

Thank you!

**Comment by skoren** [comment]
The algorithm in version 1.8 changed so the number of buckets will be <= ovb files now. If your overlap store building is already running sorting and you have a ```1-bucketize.success``` file in the ovlStore folder, you can remove the ovb files yes. 

However, if you had any file system corruption in the bucket generation and you remove the ovb files now, you would have to re-run some overlap computation. Unless you're running out of space, Canu will automatically remove them once the store build completes.

**Comment by Jolvii85** [comment]
Yes, I am running out of space, so I have to remove the ovb files, hope everything goes well.
Thanks for your help.

**Comment by Jolvii85** [comment]
After removing the ovb files, canu finished the sorting step without error, you can close the ticket now. Thanks.
