### ISSUE TITLE
Correction ovStoreSort for ovlStore.building "Cannot allocate memory Failure"

### ISSUE THREAD

**Issue by esolares** [marbl/canu#125]
I am getting an memory allocation error, but I checked available memory and I do indeed have more than the 104.31Gb the script is requesting. I have 128G available of ram.  I have tried resubmtting the job, removing the ovlStore.BUILDING folder, and also manually running the script and changing the -M parameter value manually incrementally from 104G all the way to 128G. I am running CANU 1.2.

Here is the script:
`ovStoreSorter -deletelate -M 120 -O /home/solares/pylon1/willi/canu8/dwilli-auto/correction/dwilli.ovlStore.BUILDING -G /home/solares/pylon1/willi/canu8/dwilli-auto/correction/dwilli.gkpStore -F 1 -job 1 13`

Here is the error:
```
Overlaps need 104.31 GB memory, allowed to use up to (via -M) 120 GB.
Loading 332126930 overlaps from '/home/solares/pylon1/willi/canu8/dwilli-auto/correction/dwilli.ovlStore.BUILDING/bucket0001/slice001.gz'.
ERROR:  Failed to open input file '/home/solares/pylon1/willi/canu8/dwilli-auto/correction/dwilli.ovlStore.BUILDING/bucket0001/slice001.gz': Cannot allocate memory
Failure.
```

I'm showing 128G of available memory
Here is the cat /proc/meminfo:

```
MemTotal:       131909136 kB
MemFree:        129286124 kB
MemAvailable:   129721448 kB
Buffers:          156844 kB
Cached:           451728 kB
SwapCached:            0 kB
Active:           494764 kB
Inactive:         361208 kB
Active(anon):     247852 kB
Inactive(anon):    17180 kB
Active(file):     246912 kB
Inactive(file):   344028 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:      17591292 kB
SwapFree:       17591292 kB
Dirty:                40 kB
Writeback:             0 kB
AnonPages:        249512 kB
Mapped:            35448 kB
Shmem:             17628 kB
Slab:             296080 kB
SReclaimable:     139228 kB
SUnreclaim:       156852 kB
KernelStack:       12496 kB
PageTables:         6216 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    83545860 kB
Committed_AS:    2053820 kB
VmallocTotal:   34359738367 kB
VmallocUsed:     1150472 kB
VmallocChunk:   34290429852 kB
HardwareCorrupted:     0 kB
AnonHugePages:    114688 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      188672 kB
DirectMap2M:     5976064 kB
DirectMap1G:    130023424 kB
```

**Comment by skoren** [comment]
This is likely an issue with memory being unavailable for a system process (like popen). If your machine has 128gb of ram and is using 120 for the process, you'd have 8gb for system-level tasks which is a bit low. The swap should take care of it but I see you have about 15GB of swap. In my experience, Linux needs about 30gb free of physical + virtual so you're right on the border. Do all your jobs fail or just a few? Canu will retry and if only a subset of jobs is failing it will likely complete. However, you can explicitly limit the memory used for this step by setting
```
ovsMemory=70
```
That should fit on your machines comfortably.

**Comment by esolares** [comment]
Thank you. Your suggestion solved the problem by decreasing the ovsMemory. I was able to successfully complete this part by setting it to 70 and also 100.

**Comment by skoren** [comment]
OK, we will consider allowing more slack for users who are running without swap space.

**Comment by brianwalenz** [comment]
Question - are you explicitly requesting a memory size, e.g., ovsMemory?  I'm confused how canu could have picked such a high value.  This step doesn't benefit from additional memory, it's almost entirely I/O bound.
