### ISSUE TITLE
ovStoreDump was not finished but canu goes on generateCorrectionLayouts

### ISSUE THREAD

**Issue by Jolvii85** [marbl/canu#1251]
Hi there,

I did not give canu enough time for the last few steps(after Ovs), the index sorting was finished but when the ovStoreDump was runing, the job was stop by the cluster, I got the following output. Can you help me to check whether the ovStoreDump was finished or not? What does ovStoreDump do?
I do not have output like "**-- Purged xx GB in xx overlap output files and x directories**."  and  **I did not find the counts.dat and counts.err in Po.ovlStore folder.** When I resubmit the main script, canu just run the next script "generateCorrectionLayouts".  Is it ok to continue? 

Thank you very much.

```
-- Creating overlap store correction/Po.ovlStore using:
--   1375 buckets
--   1375 slices
--        using at most 29 GB memory each

-- Starting command on Mon Feb 18 16:26:08 2019 with 195835.452 GB free disk space

    cd correction
    /pfs/nobackup/home/j/jolvii/Software/canu/Linux-amd64/bin/ovStoreIndexer \
      -O  ./Po.ovlStore.BUILDING \
      -S ../Po.seqStore \
      -C  ./Po.ovlStore.config \
      -delete \
    > ./Po.ovlStore.BUILDING.index.err 2>&1

-- Finished on Mon Feb 18 22:52:13 2019 (23165 seconds, like watching paint dry) with 228629.371 GB free disk space

-- Checking store.

-- Starting command on Mon Feb 18 22:52:13 2019 with 228629.371 GB free disk space

    cd correction
    /pfs/nobackup/home/j/jolvii/Software/canu/Linux-amd64/bin/ovStoreDump \
     -S ../Po.seqStore \
     -O  ./Po.ovlStore \
     -counts \
     > ./Po.ovlStore/counts.dat 2> ./Po.ovlStore/counts.err

-- Finished on Mon Feb 18 22:52:29 2019 (16 seconds) with 228653.658 GB free disk space


-- Overlap store 'correction/Po.ovlStore' successfully constructed.
-- Found 1694847078872 overlaps for 35746784 reads; 15963 reads have no overlaps.
--
slurmstepd: error: *** JOB 6247139 ON b-cn0126 CANCELLED AT 2019-02-18T23:12:51 ***

```

**Comment by brianwalenz** [comment]
You should be OK to continue.

It looks like you got incredibly lucky and Canu was killed while it was cleaning up intermediate files.  This will waste a little disk space, but won't hurt otherwise.

The ovlStoreDump is simply checking that the overlap store can be accessed.  If it can, the output in counts.dat and counts.err is summarized ("Found ...") and those two files are removed.  If it can't, the ovlStoreDump command fails and Canu stops.

Cheers!
