### ISSUE TITLE
canu-1.8: unitigging/4-unitigger/unitigger.sh should be recreated upon re-execution

### ISSUE THREAD

**Issue by mmokrejs** [marbl/canu#1255]
If a job fails during this step and is later re-run, say for clarity with a canu placed in a different `$PATH`, one would expect the whole pipeline use the "new" installation. Unfortunately, the `bin` variable defined in the script still points to the original location, which is wrong.

I think https://github.com/marbl/canu/issues/1253#issuecomment-465491843 faced same issue with old settings stored somewhere mysteriously. Probably `-threads 16` value in the same `unitigging/4-unitigger/unitigger.sh` script caused that issue.

In an ideal world maybe there should be a new `unitigger.sh.$$` script written and if having same checksum as the old-one, it could be immediately deleted, otherwise moved over the `unitigger.sh` original.

**Comment by skoren** [comment]
More generally, all shell scripts for steps which are not completed should be re-written. Even if they exist, the newest parameters need to take precedence.

**Comment by mmokrejs** [comment]
I wonder whether `$NCPUS` or` $THREADS` or `$OMP_NUM_THREADS` variables could be used in this and other shellscripts throughout canu to work properly. Some universally defined variable already set by SGE/LSF/PBS, etc.?

I see different values assigned to "threads" in these scripts (like `threads=8`, `threads=1`, `threads=16`), which is weird:

```
trimming/0-mercounts/meryl-count.sh
trimming/0-mercounts/meryl-configure.sh
trimming/0-mercounts/meryl-process.sh
unitigging/4-unitigger/unitigger.sh
unitigging/0-mercounts/meryl-count.sh
unitigging/0-mercounts/meryl-configure.sh
unitigging/0-mercounts/meryl-process.sh
```

**Comment by skoren** [comment]
The scripts are all dynamically generated based on the available resources and different programs may or may not be multithreaded, thus the different values. We wouldn't want to use the variables you suggest because those are all machine-wide and multiple shell scripts can share a machine in which case they'd overload it. We could use grid-specific ones (like SLURM_CPUS_PER_TASK) but since the shell scripts are dynamic anyway, it should be easy enough to re-generate them when the threads value is changed.

**Comment by brianwalenz** [comment]
`unitigger.sh` is now rewritten every time, until it completes successfully.

I like the idea of setting threads based on the number requested from the grid.  It's arguably the correct way to get resource limits.  I'm hesitant to commit to it for two reasons:  what we have works; we don't have access to test on LSF, PBS or PBSpro, and the last two have been a continuous source of problems for us.  A third complication is that with hard coded resource requests, it is possible to run the scripts manually, outside grid control.

I have, however, added this to our list of features for the next release (https://github.com/marbl/canu/projects/2) but no guarantees it'll get implemented.
