### ISSUE TITLE
sanity check on SGE grid

### ISSUE THREAD

**Issue by mahulchak** [marbl/canu#1258]
Hello,
I am running Canu snapshot v1.8 +122 changes (r9332 a29bb50a07434d00da2345aad5b0f53165c4e0f8) on our SGE. I encountered an issue and solved it but I wanted to let you know in case anyone else faces it. 

The issue concerns the sanity check code block (Line 226-265) in canu/src/pipelines/canu/Grid_SGE.pm. For our grid, openmp is the parallel environment name. Running qconf -spl returns a list of 200 openmp queue names. However, qconf -sp openmp would not return anything because you'll have to provide one of the names from the list that qconf -spl returned (in our case, these are openmp-queue_name, where queue_name is replaced by the name of an actual queue). The system works because our sysadmin has written a script that takes openmp and a queue name to create a name that works with qconf- sp command. I was getting error because that sanity check was failing with our SGE system. After I commented it out, it is working fine now.

**Comment by skoren** [comment]
The code should use the names returned from spl to query each individual one:
```
    my @env = `qconf -spl`;  chomp @env;

    foreach my $env (@env) {
        qconf -sp $env
```

So i'm not sure why it was failing on your system. What does your ```qconf -spl``` return look like?

**Comment by mahulchak** [comment]
That’s interesting. I was under the impression that it was using the openmp parallel environment name I supplied with 
gridEngineResourceOption="-pe openmp THREADS -l mem_size=MEMORY"

Alright, here is an example of 5 openmp entries from the list qconf -spl returns

qconf -spl|grep 'openmp'|head -n 5
openmp-FDCP
openmp-abio
openmp-abio128
openmp-adl
openmp-adriana

the top entries are not openmp but in case you need to know –

qconf -spl|head -n 5
gpu-node-cores
make
mpi-FDCP
mpi-abio
mpi-abio128

**Comment by skoren** [comment]
I am not sure why any of those would fail. Is it possible your grid was not returning -spl for one of those listed environments? If you're changing the code, can you add a print before the -spl command runs to report which it is hanging on?

**Comment by skoren** [comment]
Ah, I see from reading your earlier comment: ```The system works because our sysadmin has written a script that takes openmp and a queue name to create a name that works with qconf- sp command.```. 

That is non-standard for sure, why not record the proper sp name in the list? You could modify Canu to use the same logic the script uses. Specifying the ```gridEngineResourceOption``` should completely skip this code, can you post your full canu command line?
