### ISSUE TITLE
Trimming stage - memory configuration 

### ISSUE THREAD

**Issue by erikenbody** [marbl/canu#1259]
Hi there, 

I'm running canu 1.8 with the trio option on a linux cluster and using SLURM grid configuration. Array jobs in the OvS trimming stage draw more memory than is available per core and I am hoping you can help track down how to configure correctly. 

```
canu -version
Canu 1.8
```
The configuration looks like:

```
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_191' (from 'java') with -d64 support.
-- Detected gnuplot version '4.6 patchlevel 2   ' (from 'gnuplot') and image format 'png'.
-- Detected 16 CPUs and 126 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /usr/bin/sinfo.
-- Detected Slurm with 'MaxArraySize' limited to 1000 jobs.
-- 
-- Found  17 hosts with  16 cores and  500 GB memory under Slurm control.
-- Found 198 hosts with  16 cores and  125 GB memory under Slurm control.
-- Found  13 hosts with  16 cores and  250 GB memory under Slurm control.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl     62 GB    8 CPUs  (k-mer counting)
-- Grid:  hap       16 GB   16 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   48 GB   16 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    24 GB   16 CPUs  (overlap detection)
-- Grid:  utgovl    24 GB   16 CPUs  (overlap detection)
-- Grid:  ovb        4 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       32 GB    1 CPU   (overlap store sorting)
-- Grid:  red       16 GB    8 CPUs  (read error detection)
-- Grid:  oea        8 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      500 GB   16 CPUs  (contig construction with bogart)
-- Grid:  gfa       32 GB   16 CPUs  (GFA alignment and processing)
--
```

The job script below is the source of the issue, where it asks for 17g / cpu, when only 8g / cpu is available on the default node (128gb with 16 cores). The scheduler cancels the job once it exceeds 8gb.

```
cat trimming/asm-haplotypeA157.ovlStore.BUILDING/scripts/2-sort.jobSubmit-01.sh
>
sbatch \
  --mem-per-cpu=17g --cpus-per-task=1 -M snowy -p core -t 2-23:59:00 -A snic2018-8-65 --mail-type=all --mail-user=erik.enbody@gmail.com -o logs/2-sort.%A_%a.out \
  -D `pwd` -J "ovS_asm-haplotypeA157" \
  -a 1-2 \
  ./scripts/2-sort.sh 0 \
> ./scripts/2-sort.jobSubmit-01.out 2>&1
```

My job script looks like:

```
GRID_OPTIONS="-M snowy -p core -t 2-23:59:00 -A snic2018-8-65 -C mem128GB"

canu \
 -p asm -d rabbitTrio_corr_2 \
 genomeSize=2737490501 \
 useGrid=TRUE \
 gridOptions="$GRID_OPTIONS" \
 -haplotype6134 $FASTQ_D/6134*fastq.gz \
 -haplotypeA157 $FASTQ_D/A946*fastq.gz \
 -pacbio-raw $REF \
 corMhapFilterThreshold=0.0000000002 \
 corMhapOptions="--threshold 0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000  --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50"
 mhapMemory=60g \
 mhapBlockSize=500 \
 ovlMerDistinct=0.975
```

When I look through issue #1008 I believe I can force Ovs to use 5 threads (thus have 40gb available) using:

```
 ovsThreads=5 
```

However, when I restart canu after deleting the `trimming/asm-haplotypeA157.ovlStore.BUILDING/` directory, the above job array script still requests 1 cpu with 17gb of memory and is cancelled by the scheduler. 

I believe that the original source of the issue is that sinfo returns two fat nodes available (other than the default 128g), but these require specific slurm configuration to request (using -C 216GB etc). I attempted to fix this by adding -C 128GB, but the top level configuration stays the same. 

Are there more folders I should delete when restarting canu to force ovsThreads to apply to the array commands? Is there another way to force canu to meet the 8gb / cpu threshold in this case and avoid this issue downstream? For example, it looks like the same issue will apply to the bat stage.

Thank you for your help!
Erik

**Comment by skoren** [comment]
Canu expects to be able to request an arbitrary amount of memory per core, this is how slurm works by default. Your slurm cluster is implicitly allocating memory instead which is different from issue #1008 (where it was implicitly allocating cores by memory). Essentially the ```--mem-per-cpu``` option is being ignored on your cluster.

The easiest fix for you would be to explicitly overwrite the memory used for each step, either to match the available per-core (which would be ```ovsMemory=8 batMemory=128``` in this case) or to explicitly over-write the slurm request (```gridOptionsovs="--mem-per-cpu=8g --cpus-per-task=4"```). You can set ```maxMemory=128``` to avoid scheduling to the larger nodes too.

**Comment by erikenbody** [comment]
Thank you so much for the helpful response! That makes a lot of sense to me.

I deleted the trimming/*.ovlStore.BUILDING/ directories and ran it once with ```ovsMemory=8 batMemory=128``` and it generated the same problematic array script as above (i.e. --mem-per-cpu 17g --cpus-per-task=4, so I tried again with ```gridOptionsovs="--mem-per-cpu=8g --cpus-per-task=4"``` with the same result. So I suspect that there must be an earlier configuration that I haven't been able to rewrite. Should I delete the entire trimming directory, or perhaps some files up one level from the individual haplotype assemblies?

I realize this is very specific to my cluster and configuration and very much appreciate your help.

**Comment by brianwalenz** [comment]
I suspect Canu is picking up the old configuration saved in `trimming/asm-haplotypeA157.ovlStore.config` and `trimming/asm-haplotypeA157.ovlStore.config.txt`.

You're on the right track with ovsMemory=8.  I'd drop that slightly to 7, just to give a small margin of error.

Running with useGrid=remote will tell Canu to set up jobs for the grid, but make you do the actual job submission.  This will let you change any grid options -- in particular, increasing mem-per-cpu from 7 to 8.  In other words, you've told the program to use 7gb memory (it's usually pretty good at not exceeding that) but will request 8gb from slurm.

**Comment by erikenbody** [comment]
Thank you both very much for the response! With your suggestions these steps got me through trimming: 
1)  ``rm -r trimming/*.ovlStore*`` 
2) `ovsMemory=7` 
3) Manually edit and run `trimming/asm-*ovlStore.BUILDING/scripts/2-sort.jobSubmit-01.sh` when it failed to have `--mem-per-cpu=8g --cpus-per-task=4`. `useGrid = remote` would have also worked to do this. Then once completed (a few minutes), submitting the original canu submission. 
4) A missing backslash in my job script that may have negated ovsMemory when I resubmitted. 

The last user error may have been the source of my failed resubmissions, apologies! I was very pleased to wake up to find canu had completed successfully. ``batMemory=124`` and `maxMemory=124` was necessary to get through the bat stage. 

Thank you for the support and for implementing this impressively efficient grid engine! In case it will help anyone (especially those on the UPPMAX cluster), I pasted my canu command below and the resulting configuration it produces. 

```
GRID_OPTIONS="-M snowy -p core -t 2-23:59:00 -A snic2018-8-65 -C mem128GB"

canu \
 -p asm -d rabbitTrio_corr_2 \
 genomeSize=2737490501 \
 useGrid=TRUE \
 gridOptions="$GRID_OPTIONS" \
 -haplotype6134 $FASTQ_D/6134*fastq.gz \
 -haplotypeA157 $FASTQ_D/A946*fastq.gz \
 -pacbio-raw $REF \
 corMhapFilterThreshold=0.0000000002 \
 corMhapOptions="--threshold 0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000  --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50" \
 ovsMemory=7 \
 mhapMemory=60g \
 mhapBlockSize=500 \
 ovlMerDistinct=0.975 \
 batMemory=124 \
 maxMemory=124
```

```
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl     62 GB    8 CPUs  (k-mer counting)
-- Grid:  hap       16 GB   16 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   60 GB   16 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    24 GB   16 CPUs  (overlap detection)
-- Grid:  utgovl    24 GB   16 CPUs  (overlap detection)
-- Grid:  ovb        4 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs        8 GB    1 CPU   (overlap store sorting)
-- Grid:  red       16 GB    8 CPUs  (read error detection)
-- Grid:  oea        8 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      124 GB   16 CPUs  (contig construction with bogart)
-- Grid:  gfa       32 GB   16 CPUs  (GFA alignment and processing)
```
