### ISSUE TITLE
Correct nanopore reads with -pacbio-raw

### ISSUE THREAD

**Issue by Jolvii85** [marbl/canu#1267]
Hi there,

Can I feed -pacbio-raw parameter to nanopore reads to accelerate  the correction step? Is there any drawback?

Thank you.

**Comment by skoren** [comment]
Changing nanopore to pacbio won't change the speed of the correction much. It will speed up trimming and overlapping but will likely end up with a worse assembly. See the FAQ for ways to speed up/save space instead.

**Comment by Jolvii85** [comment]
Hi,
I have used -pacbio-raw parameter to nanopore reads and got 60× reads, can I run canu with  -nanopore-raw on this  60× reads to improve the correction quality?
Thank you.

**Comment by skoren** [comment]
I don't think the correction will change much from pacbio to nanopore settings..

**Comment by Jolvii85** [comment]
> I don't think the correction will change much from pacbio to nanopore settings..

So, do I need redo the correction from the very beginning, or run another correction with 
-pacbio-raw? Or is it ok to use the results from my previous run"correct nanopore reads with -pacbio-raw parameter"? I plan to assemble the canu correction reads with wtdbg2 (the genome size is ~20G), do you have any other suggestion?  
Thank you very much?

**Comment by skoren** [comment]
It's fine to use the corrected reads from the pacbio-raw run. I'd suggest running the Canu assembly too on the corrected reads providing them as -nanopore-corrected.
