### ISSUE TITLE
consensus jobs failed

### ISSUE THREAD

**Issue by YuyaKiguchi** [marbl/canu#1268]
Hi,
I assembled metagenomic data using canu version 1.8 but I got the error.

This is the command.
`canu -p KG-V_deb_S1_600000.correctedReads.split.30th -d KG-V_deb_S1_600000.correctedReads.split.30th.trimassemble -pacbio-corrected KG-V_deb_S1_600000.correctedReads.split.30th.500bp.fasta genomeSize=10m maxThreads=60 minReadLength=500 minOverlapLength=250 corOutCoverage=10000 corMinCoverage=0 corMhapSensitivity=high redMemory=32 oeaMemory=32 batMemory=200`

Please check canu log attached.
[KG-V_deb_S1_600000.correctedReads.split.30th.trimassemble.log](https://github.com/marbl/canu/files/2914154/KG-V_deb_S1_600000.correctedReads.split.30th.trimassemble.log)

Thank you.

Yuya

**Comment by gabyrech** [comment]
Same error here. I am running Canu 1.8 in a SLURM cluster. It works fine for some assemblies, but for others it gives this error:

`$HOME/$ tail  canu.out 
--
-- Consensus jobs failed, tried 2 times, giving up.
--   job ctgcns/0007.cns FAILED.
--

ABORT:
ABORT: Canu 1.8
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
`
And this is the out:

`$HOME/unitigging/5-consensus$ cat consensus.5844957_7.out 

Found perl:
   /bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /homes/aplic/noarch/software/Java/1.8.0_92/bin/java
   java version "1.8.0_92"

Found canu:
   /gpfs42/robbyfs/homes/aplic/noarch/software/canu/1.8/bin/canu
   Canu 1.8

Running job 7 based on SLURM_ARRAY_TASK_ID=7 and offset=0.
-- Opening seqStore '../mun1158_oneRun_minLen2Kb_20190225.ctgStore/partitionedReads.seqStore' partition 7.
-- Opening tigStore '../mun1158_oneRun_minLen2Kb_20190225.ctgStore' version 1.
-- Opening output results file './ctgcns/0007.cns.WORKING'.
--
-- Computing consensus for b=0 to e=55850 with errorRate 0.2000 (max 0.4000) and minimum overlap 40
--
/var/spool/slurmd/job5844965/slurm_script: line 100: 112492 Bus error               (core dumped) $bin/utgcns -S ../mun1158_oneRun_minLen2Kb_20190225.${tag}Store/partitionedReads.seqStore -T ../mun1158_oneRun_minLen2Kb_20190225.${tag}Store 1 $jobid -O ./${tag}cns/$jobid.cns.WORKING -maxcoverage 40 -e 0.2 -pbdagcon -edlib -threads 2-8
`
Thanks for your help!
Gabriel

**Comment by skoren** [comment]
@YuyaKiguchi, try the suggestions in issue #1225 to increase the error rate.

@gabyrech, the bus error would likely imply this is out of memory. You can confirm my checking the job history on slurm. Try increasing the memory for this step using ```gridOptionscns="--mem=double whatever it was requesting now"```.

**Comment by YuyaKiguchi** [comment]
Dear skoren,

Thank you for you suggestion.
The problem is solved.

Thank you for your help.
Yuya.

**Comment by gabyrech** [comment]
Thanks @skoren ! I'll give a try and let you know.
best,
Gabriel

**Comment by gabyrech** [comment]
Hi @skoren, indeed, by increasing the `gridOptionscns="--mem="` to the double it was the consensus step finished.
Thanks!
Gabriel
