### ISSUE TITLE
Crash during sqStoreCreate

### ISSUE THREAD

**Issue by fbemm** [marbl/canu#1269]
1. What you were trying to do

I am trying to assemble a ONT data set that looks like this:

```
Total n:        8501779
Total seq:      255698433134 bp
Avg. seq:       30075.87 bp
Median seq:     25251.00 bp
N 50:           34384 bp
Min seq:        13056 bp
Max seq:        778386 bp
```

2. What you wanted to happen

I wanted Canu to create me the perfect assembly ;)

3. What actually happened

```
Starting file './test.seqStore.ssi'.

  Loading reads from 'test.fasta.gz'

Failed with 'Interrupt'; backtrace (libbacktrace):
utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
stores/sqStoreCreate.C::134 in _Z9loadFASTAPcS_S_RiPhP20compressedFileReaderP8_IO_FILERj()
stores/sqStoreCreate.C::424 in _Z9loadReadsP7sqStoreP9sqLibraryjjP8_IO_FILES4_S4_PcRjS6_RmS6_S7_()
stores/sqStoreCreate.C::686 in _Z11createStorePKcjPPcjj()
stores/sqStoreCreate.C::924 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
```

4. What data and command line to use to make the problem recur, if applicable

```
canu useGrid=true -nanopore-raw $SEQ -p $PFX -d $PFX genomeSize=2500m corMemory=128 corPartitions=256 corPartitionMin=256 oeaMemory=128 redMemory=128
```

Looks like a read length issue again. I adjusted memory limits already but that did not help.

Any idea?

**Comment by skoren** [comment]
The reads you have are not that long so I don't think this is a read issue. This seems like a file system issue, the read is being interrupted in the middle of loading your input file. Is it possible the file is corrupted? Is it a valid fasta file, does it extract OK with gunzip or zcat? Does it have non-ACGTN characters?

**Comment by brianwalenz** [comment]
Hmmm.  `Failed with 'Interrupt'` (SIGINT) is implying that the program received "CTRL-C" from the keyboard.

I don't think it's a code problem or file corruption.  It looks like something is killing the job.

Does it fail with exactly the same stack trace every time?

test.seqStore.BUILDING/readNames.txt will indicate approximately how far it got in loading reads.  Does that change (wildly) on different runs?

**Comment by skoren** [comment]
Idle, SIGINT implies job was killed not crashed so nothing to fix w/o more information.
