### ISSUE TITLE
Canu error while doing assembly,  hapMemory and hapThreads error.

### ISSUE THREAD

**Issue by shashibioinfo** [marbl/canu#1275]
Hi everyone,

I'm trying to do metagenomics de novo assembly for MinION nanopore data using Canu tool.

The data set has 22000 reads 

im doing analysis in AWS ubuntu server with 32 Gb RAM and 1Tb storage.

when i have tried this command 

./canu -d /home/ubuntu/Leucine_rawdata/canu_results/barcode3_5_canu_results/ -p barcode3_5_leucine genomeSize=1g -correct -assemble -nanopore-raw /home/ubuntu/Leucine_rawdata/trimmed/barcode3_5_trimmed.fastq

it shows error of **hapMemory** and **hapThreads** to change the RAM the system has enough ram to do analysis.

Again i have changed the command

./canu -d /home/ubuntu/Leucine_rawdata/canu_results/barcode3_5_canu_results/ -p barcode3_5_leucine genomeSize=1g -correct -assemble -nanopore-raw /home/ubuntu/Leucine_rawdata/trimmed/barcode3_5_trimmed.fastq hapMemory=16 hapThreads=64

and tried but still it shows the same error

can you please help me to resolve this hapMemory and hapThreads issue.

Thank you
![canu_memory_error](https://user-images.githubusercontent.com/47294807/53881269-436c5f00-4039-11e9-80dd-aadb034343a4.png)

**Comment by skoren** [comment]
Canu selects default memory/threads based on your genome size. For a 1gb genome it is trying to use 16gb/64 cores by default. Your machine only has 8 cores/31gb of memory. You can make canu run by adjusting the memory it is allowed to use from the defaults. ```hapMemory=31 hapThreads=8 maxMemory=30 maxThreads=8``` should be a good start, you might need to adjust other limits if it complains about them. Adjust them the same way to match your machine not what it reported it defaulted to (see also #1235 and the FAQ page).

**Comment by shashibioinfo** [comment]
Thank you so much for your valuable information
