### ISSUE TITLE
Any tips for running canu on short MinION reads?

### ISSUE THREAD

**Issue by francoiskroll** [marbl/canu#1277]
I am computing a consensus sequence from short MinION reads (~1000bp at ~800X coverage).

My current command is:

```
canu \
  -p test -d consensus \
  -nanopore-raw 11_06_pooled.fastq \
  genomeSize=1.5k \
```

Not any issue here, as it is working well and I am getting very good identity to my reference.

However, I was wondering: as canu is primarily designed for long reads; are there any parameters I should tweak to further maximise performance on short reads?

Apologies if that's a bit of a broad question, I am hoping it's useful for other people doing short read sequencing on MinION.

**Comment by brianwalenz** [comment]
Canu really only uses the longest ~40x of the reads, though the shorter reads are used during read correction.  There are some histograms of read length in the *.report showing read length before correction, after correction, and after trimming.

A couple of parameters to play with:
- corOutCoverage (default 40) - coverage in corrected reads to generate
- minReadLength (default 1000) - minimum length of a read
- minOverlapLength (default 500) - minimum length of an overlap
- readSamplingCoverage and readSamplingBias - down-sample reads before processing

With 800x coverage, you'll probably just see compute performance improvements (i.e., faster) from changing parameters.  The two readSampling parameters are useful here.

With lower coverage, dropping minReadLength could make a significant improvement as reads shorter than this are discarded before any processing starts.  minOverlapLength is harder: too large and you won't find short but true overlaps; too small and you'll find an incredible amount of false overlaps.  Read coverage and genome structure factor in here: smaller overlaps are needed for lower coverage; longer overlaps are needed for more repetitive genomes ('lower coverage', however, is on the order of 5x, not usually a problem).

corOutCoverage isn't generally tweaked, except to "output everything".  This is useful if you want to use the corrected reads for something other than assembly, or if you're looking for some rare variant.  Be warned that too much coverage makes assembly _harder_.  Canu does, however, try to use every read as either evidence for correcting some other read, or as a target for correction - so even though corOutCoverage=40, you could end up with more corrected reads if there are 'novel' reads left over.

**Comment by francoiskroll** [comment]
Such an in-depth answer! Thank you so much for your time.
