### ISSUE TITLE
CANU failed at ovlStore.BUILDING step in trimming.

### ISSUE THREAD

**Issue by githubrookie1** [marbl/canu#1278]
/tmp/slurmd/job00541/slurm_script: line 111: 37260 Killed                  $bin/
ovStoreSorter -O ./PA3003.ovlStore.BUILDING -S ../PA3003.seqStore -C ./PA3003.ov
lStore.config -f -s $jobid -M 29

**Comment by githubrookie1** [comment]
more 200 of the sorting jobs failed

**Comment by githubrookie1** [comment]
my command: /opt/canu/bin/canu -p PA3003 -d PA3003 genomeSize=2500m -pacbio-corrected /shared/fasta/PA3003.correctedReads.fasta  shell='/bin/bash' java='/usr/lib/jvm/j
re-1.8.0-openjdk.x86_64/bin/java' useGrid=1 gridOptionsmeryl="--mem=70g --cpus-per-task=32"

**Comment by brianwalenz** [comment]
Try increasing the memory requested from slurm.  Each job is wanting to use 29 GB, so `gridOptionsOVS="--mem=35g"` is a good first try.

**Comment by skoren** [comment]
Any updates on this?

**Comment by githubrookie1** [comment]
With --mem=35g, it ran without any problems
