### ISSUE TITLE
Setting batOptions minimum overlap lenght overwritten by default length

### ISSUE THREAD

**Issue by albodrug** [marbl/canu#128]
Testing the effect of batOptions="-el N" on the ecoli sample I noticed no effect even when setting -el 50000. I looked into the 4-unitigger/unitigging.sh and noticed that the -el option appears twice when specifying batOptions="-el N". The first time my chosen length, the second time what canu decides is best for the dataset (for ecoli, 500bp). 

Command: 
`>for el in 500 1000 2000 3000 4000 5000 10000 12000 14000 16000 18000 20000 50000 ; do canu -assemble -d ecoli_bogart-el${el} -p ecol-bogel-${el} -pacbio-corrected ecoli_correct_trimm/ecol.trimmedReads.fastq useGrid=1 genomeSize=4.8m gridOptions=" -N 1 --qos=p70625_0128 --partition=mem_0128 --account=p70625 " batOptions=" -el ${el} " 2> ecol_assemble_settings.out-${el} ; done`

All these assemblies have the same single contig result in contigs.fa.

Here is the unitigger.sh of  -el 50000 : 

```
>cat ecoli_bogart-el50000/unitigging/4-unitigger/unitigger.sh 
#!/bin/sh

if [ -e /global/lv70694/abodrug/canu_test/canu_ecoli/ecoli_bogart-el50000/unitigging/ecol-bogel-50000.tigStore/seqDB.v001.tig ] ; then
  exit 0
fi

syst=`uname -s`
arch=`uname -m`
name=`uname -n`

if [ "$arch" = "x86_64" ] ; then
  arch="amd64"
fi
if [ "$arch" = "Power Macintosh" ] ; then
  arch="ppc"
fi

bin="/home/lv70694/abodrug/progs/canu-1.1/$syst-$arch/bin"

if [ ! -d "$bin" ] ; then
  bin="/home/lv70694/abodrug/progs/canu-1.1"
fi


$bin/bogart \
 -G /global/lv70694/abodrug/canu_test/canu_ecoli/ecoli_bogart-el50000/unitigging/ecol-bogel-50000.gkpStore \
 -O /global/lv70694/abodrug/canu_test/canu_ecoli/ecoli_bogart-el50000/unitigging/ecol-bogel-50000.ovlStore \
 -T /global/lv70694/abodrug/canu_test/canu_ecoli/ecoli_bogart-el50000/unitigging/ecol-bogel-50000.tigStore.WORKING \
 -o /global/lv70694/abodrug/canu_test/canu_ecoli/ecoli_bogart-el50000/unitigging/4-unitigger/ecol-bogel-50000 \
 -B 1362 \
 -gs 4800000 \
 -eg 0.05 \
 -eb 0.0625 \
 -em 0.0375 \
 -er 0.05 \
 -threads 4 \
 -M 16 \
 -el 50000 \
 -unassembled 2 1000 0.75 0.75 2 \
 -repeatdetect 6 22 15 \
 -el 500 \
 > /global/lv70694/abodrug/canu_test/canu_ecoli/ecoli_bogart-el50000/unitigging/4-unitigger/unitigger.err 2>&1 \
&& \
mv /global/lv70694/abodrug/canu_test/canu_ecoli/ecoli_bogart-el50000/unitigging/ecol-bogel-50000.tigStore.WORKING /global/lv70694/abodrug/canu_test/canu_ecoli/ecoli_bogart-el50000/unitigging/ecol-bogel-50000.tigStore.FINISHED

exit 0
```
My questions is if the -el I am setting is overwritten by the default -el 500 or if the ecoli sample is too simple to try to test bogart options. Am I using batOptions correctly?
canu version 1.2

Thanks!

**Comment by brianwalenz** [comment]
e.coli is too simple to do any useful testing.  It gives just a binary result - assembled to one contig, or not.  Yeast is slightly more interesting, drosophila and arabidopsis are useful tests.

src/pipelines/canu/Unitig.pm can be trivially modified to move the batOptions line to the end of the parameter list.  I'll make that change, thanks.  This length is also set by canu parameter minOverlapLength (at least in the git latest; 1.2 might be different).
