### ISSUE TITLE
overlapping contigs after assembly

### ISSUE THREAD

**Issue by dtzhu337** [marbl/canu#1285]
Hi,

I used Canu to assemble the reads from Pacbio to generate a genome for an insect.  The script I used was:
./canu -p Pacbio -d /pathway/ genomeSize=280m -pacbio-raw /pathway/to/reads/fq/file.

After assembly, I compared the contigs.fasta file to other insects from the same Order, and realized the assembly was far larger than published genomes. Meanwhile, the number of predicted genes based on the assembly reached twice that in other genomes. My guess was there were overlappings within the contigs. So I blasted the contigs against themselves, and the results indicated several alignments, where a small contig could almost fully fit into a large one.

For example, tig00000005 (30,972bp) was divided into two parts. 18,141bp of it was assigned to 821,153-803,036 bp region of tig00012502, and another 15789bp of it went to 801,991-786,242bp region of tig00012502, with both similarities over 98%.  

I know quite well that there should be reasons that Canu separated small contigs from large ones, and did not combine them. However, it is evidenced by the size and number of genes, that this assembly contains more fragments than it is supposed to be. Do you happen to have any ideas about how to improve this situation? Like some software to eliminate the overlappings or to add more parameters in Canu to tolerate a higher mismatch rate so that it can combine contigs? Thank you in advance for your time and consideration.

**Comment by brianwalenz** [comment]
Lots of suggestions at https://canu.readthedocs.io/en/latest/faq.html, specifically "smash haplotypes together" in the section "What parameters can I tweak?".

**Comment by skoren** [comment]
Most likely you are getting separation of haplotypes in the genome, leading to larger assembly size and overlapping contigs. In addition to the section @brianwalenz mentioned, I'd also suggest reading: https://canu.readthedocs.io/en/latest/faq.html#my-genome-size-and-assembly-size-are-different-help. I'm not a fan of the smashing parameters and would recommend the heterozygous assembly followed by removing duplicates using something like purge_haplotigs.
