### ISSUE TITLE
Issue with canu for metagenomics

### ISSUE THREAD

**Issue by Raymi1** [marbl/canu#1289]
Hello,

I tried to run canu in order to assemble bacterial metagenome with the following options (as suggest here : https://canu.readthedocs.io/en/latest/faq.html) : 

`canu -p prefix -d canu/  genomeSize=5m corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0 redMemory=32 oeaMemory=32 batMemory=200 gridEngineThreadsOption='--cpus-per-task THREADS' maxMemory=230G maxThreads=8 -nanopore-raw file.fastq`

However the job fails with the following error message : 

 Using slow alignment for consensus (iteration '2').
 Configured 9 contig and 6 unitig consensus jobs.

 Consensus jobs failed, tried 2 times, giving up.
   job ctgcns/001.cns FAILED.
   job ctgcns/0002.cns FAILED.
   job ctgcns/0003.cns FAILED.
   job ctgcns/0004.cns FAILED.
   job ctgcns/0005.cns FAILED.
   job ctgcns/0008.cns FAILED.
   job ctgcns/0009.cns FAILED.
   job utgcns/0001.cns FAILED.
   job utgcns/0002.cns FAILED.
   job utgcns/0003.cns FAILED.
   job utgcns/0004.cns FAILED.
   job utgcns/0005.cns FAILED.
   job utgcns/0006.cns FAILED.

ABORT:
ABORT: Canu snapshot v1.8 +151 changes (r9361 db9bfcc26004b26f21686f0c324ab69d37c5a885)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.

I use Ubuntu 14.04.5 LTS with 64G RAM. I checked in the system log file and the issue doesn't seem to occur because of a lack of memory. I also tried to rerun the program but it still didn't work.

Thank you for any advice about how to run Canu for metagenomic assembly.

**Comment by skoren** [comment]
This is most likely the same as #1288, you're running in the middle of some consensus code changes. Try switching to the 1.8 release rather than a direct checkout of the latest code and see if consensus runs.

**Comment by Raymi1** [comment]
I already have the 1.8 version. 
When I do `canu --version`, I get : `Canu snapshot v1.8 +151 changes`

**Comment by skoren** [comment]
You do not have version 1.8, it is reporting 1.8 + 151 changes, that means it is 151 commits ahead of the release. Download the 1.8 version from the release page.

**Comment by skoren** [comment]
Confirmed, this bug is fixed in tip so either update to latest from repo or use the release source.

**Comment by Raymi1** [comment]
Thanks very much. It seems to work now.
