### ISSUE TITLE
Log file shows unexpected error rates

### ISSUE THREAD

**Issue by annalenaVdW** [marbl/canu#129]
Hi,
I recently tested a few different values for the errorRate parameter (from 0.01 to 0.000001) on my reads, to see how this influences other errors. I checked the files in the `canu-logs` folders and realized that for extremely low errorRate (0.00001 and 0.000001), the errors in trimReads and splitReads are set to 3. If I understand correctly, trimReads and splitReads use a percent error. For errorRate=0.01, 0.001, and 0.0001, those values are set to 0.03, so I would expect the value to be smaller than that, not larger. Can you explain this please?

Best,
Anna-Lena

Below I pasted the content of the trimReads log files with errorRate=0.01 and errorRate=0.00001. 

> 
> Canu v1.1 (+18 commits) r7396 91906b6ce56217d765cf1938696ced0e738ca8a3.
> 
> Current Working Directory:
> /ebio/abt6_projects8/Ath_Rgenes_pipeline/data/testcase/assembly/canu/ccs-reads_subsetting/0.99999/trimming/3-overlapbasedtrimming
> 
> Command:
> /ebio/abt6_projects9/abt6_software/bin/canu/Linux-amd64/bin/trimReads \
>   -G /ebio/abt6_projects8/Ath_Rgenes_pipeline/data/testcase/assembly/canu/ccs-reads_subsetting/0.99999/trimming/PRE.gkpStore \
>   -O /ebio/abt6_projects8/Ath_Rgenes_pipeline/data/testcase/assembly/canu/ccs-reads_subsetting/0.99999/trimming/PRE.ovlStore \
>   -Co /ebio/abt6_projects8/Ath_Rgenes_pipeline/data/testcase/assembly/canu/ccs-reads_subsetting/0.99999/trimming/3-overlapbasedtrimming/PRE.1.trimReads.clear \
>   -e 0.03 \
>   -minlength 1000 \
>   -ol 1 \
>   -oc 1 \
>   -o /ebio/abt6_projects8/Ath_Rgenes_pipeline/data/testcase/assembly/canu/ccs-reads_subsetting/0.99999/trimming/3-overlapbasedtrimming/PRE.1.trimReads
> 
> Canu v1.1 (+18 commits) r7396 91906b6ce56217d765cf1938696ced0e738ca8a3.
> 
> Current Working Directory:
> /ebio/abt6_projects8/Ath_Rgenes_pipeline/data/testcase/assembly/canu/ccs-reads_subsetting/0.99999_adj_evalue/trimming/3-overlapbasedtrimming
> 
> Command:
> /ebio/abt6_projects9/abt6_software/bin/canu/Linux-amd64/bin/trimReads \
>   -G /ebio/abt6_projects8/Ath_Rgenes_pipeline/data/testcase/assembly/canu/ccs-reads_subsetting/0.99999_adj_evalue/trimming/PRE.gkpStore \
>   -O /ebio/abt6_projects8/Ath_Rgenes_pipeline/data/testcase/assembly/canu/ccs-reads_subsetting/0.99999_adj_evalue/trimming/PRE.ovlStore \
>   -Co /ebio/abt6_projects8/Ath_Rgenes_pipeline/data/testcase/assembly/canu/ccs-reads_subsetting/0.99999_adj_evalue/trimming/3-overlapbasedtrimming/PRE.1.trimReads.clear \
>   -e 3 \
>   -minlength 1000 \
>   -ol 1 \
>   -oc 1 \
>   -o /ebio/abt6_projects8/Ath_Rgenes_pipeline/data/testcase/assembly/canu/ccs-reads_subsetting/0.99999_adj_evalue/trimming/3-overlapbasedtrimming/PRE.1.trimReads

**Comment by brianwalenz** [comment]
For trimReads, the -e parameter is just 3*errorRate.  We've never imagined having more than 4 digits precision (0.0001 = 0.01%) and many of the output formats will truncate to that.  No explanation for how 3 * 0.00001 = 3.  I'll blame perl.

Everything should be using fraction error, which makes 3 even more nonsensical.

The errorRate parameter never lived up to expectations, and will probably be removed in the near future.  Hopefully, this will accelerate its demise.

You should update your copy of canu, at least to the 1.2 release, and preferably the git latest (which seems stable at the moment).

**Comment by annalenakeller** [comment]
I'll update and won't not use anything smaller than 0.01% to be on the save side then. Thanks :)
Best,
Anna-Lena
