### ISSUE TITLE
slurm 2.6.9-3 is not compatible with canu 1.8 ?

### ISSUE THREAD

**Issue by xiaoyezao** [marbl/canu#1290]
I am running canu (v1.8) on a 1.3G plant genome. The command is:
`srun -p paratera canu -p rheum_run1 -correct -d ./run1 genomeSize=1.3g -pacbio-raw *.gz useGrid=TRUE gridOptions="-p paratera"`

The job stops at **1-overlapper** . I check **precompute.jobSubmit-01.out** at that folder, and it says: **sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)**

Then, I try to manully submit the job by: `yhbatch -p paratera precompute.jobSubmit-01.sh` . The submittion seems work, but the job stops again. I check **precompute.jobSubmit-01.out** and it says:  **yhrun: invalid option -- 'a'** . Then I go back to **precompute.jobSubmit-01.sh** and find there is an option: **-a 1-161** . The complete script is:

#!/bin/sh

sbatch \
  --mem-per-cpu=2645m --cpus-per-task=12 -p paratera -o precompute.%A_%a.out \
  -D `pwd` -J "cormhap_rheum_run1" \
  -a 1-161 \
  ./precompute.sh 0 > ./precompute.jobSubmit-01.out 2>&1

Then I do `srun -h` , there is no `-a` option in the help message.

So the problem is: the slurm (v2.6.9-3) does not support the option `-a`. Is the **slurm 2.6.9-3** not compatible with **canu 1.8** ?  How can fix the issue?

Thanks

**Comment by brianwalenz** [comment]
As the first error says, the job is exceeding a limit on the number of jobs you can submit, or the amount of memory you can request.

This job is split into 161 tasks (the -a option, short for --array), each of which are requesting 31740 MB memory and 12 processors.  `sacctmgr list associations` and `sacctmgr show qos` might be helpful to see what the limits are.

Assuming it's the number of jobs, it is possible (but tedious) to run them manually (by running multiple `sbatch` commands, changing the -a ranges for each job: one with `-a 1-50`, then `-a 51-100`, then `-a 101-150`, etc, until all 161 tasks are complete) then restarting canu.  You'll need to do this for around ten stages in the canu pipeline.  I'd advise trying to get your limit increased to at least 1000 jobs, 2000 would be better.

If it's memory, canu option `maxMemory` can limit all jobs to some maximum memory.  However, it will be hard to get an assembly with significantly less than 32 GB.

I'm not familiar with yhrun or yhbatch, so can't help there.

**Comment by xiaoyezao** [comment]
I checked with our cluster admin that my maxmium nodes and jobs are both 16. So that's the problem.

The 161 tasks need 161*12 cpus. Our cluster has 24cores-65G per node, so I need 161*12/24 nodes simultaneously to run the job. Am I right?  I will try to ask for more nodes, but not sure for more than 80.

The yhrun or yhbatch I am using are same with srun and sbatch. Are there any solutions to reduce the nomber of nodes being used simultaneously?

**Comment by skoren** [comment]
Nope, it doesn't matter how many nodes you get to run on concurrently. You can run using one, the limit is how many jobs you can submit to be in the queue to run. You can get half the jobs by increasing memory for mhap to 64 and 24 cores but that will still end up with >16 jobs for you to run. If you can't get the limit increased as 16 scheduled (not running) jobs is quite low, the workaround @brianwalenz to manually run various job intervals is your only option.

**Comment by xiaoyezao** [comment]
I understand. Thank you very much!

> You can get half the jobs by increasing memory for mhap to 64 and 24 cores

How can I do this ? 

There are few lines in **mhap.sh** in the 1-overlapper folder:

**if[ ! -e ./results/$qry.mhap ] ; then
  /WORK/app/java/jdk1.8.0_11/bin/java -d64 -XX:ParallelGCThreads=12 -server -Xms28570m -Xmx28570m \
    -jar  $bin/../share/java/classes/mhap-2.1.3.jar  \
    --repeat-weight 0.9 --repeat-idf-scale 10 -k 16 \
    --store-full-id \
    --num-hashes 256 \
    --num-min-matches 3 \
    --threshold 0.8 \
    --filter-threshold 0.0000001 \
    --ordered-sketch-size 1000 \
    --ordered-kmer-size 14 \
    --min-olap-length 500 \
    **--num-threads 12** \
    -s  ./blocks/$blk.dat $slf  \
    -q  queries/$qry  \
    > ./results/$qry.mhap.WORKING \**

Should I change **--num-threads** 12 to 24 ?

**Comment by skoren** [comment]
You're not at the mhap.sh yet, you would want to remove the 1-overlapper folder completely and re-launch Canu with corMhapThreads=24 corMhapMemory=60

**Comment by skoren** [comment]
Idle, workaround provided. Batch limit of 16 jobs in queue would be quite low and atypical so we're not going to try to special case it.
