### ISSUE TITLE
Query on unassigned reads and assembly

### ISSUE THREAD

**Issue by TGeneralovic** [marbl/canu#1293]
Hi,

I have a query on the assembly method.

1) I am trying out different methods of assembly with a trio so using trio assembly approach `canu v1.8`. When the reads are assigned to haplotypes and the left over reads are left unassigned do they get used in assembly at all?

If they are not used in assembly what is the location they are dumped into? Are they all dumped at the haplotype stage into `haplotype-unknown.fasta.gz`?

Or are they dumped into the `*haplotype*.unassembled.fasta` for each haplotype?

2) Also I have looked through the scripts but cannot see the threshold value that canu uses to distinguish kmers from the reads? 

Any pointers in the right direction would be great,
Tom

**Comment by skoren** [comment]
1. The unassigned files are dumped to haplotype-unknown and not used in the assembly unless they make up a large fraction of the bases (2% by default). 

2. What do you mean distinguish kmers from the reads? If you mean how it filters noise kmers for classification, this is computed in splitHaplotype.C from the parental histograms. All parental kmers are counted, 1-copy kmers removed, and k-mers specific to each parent are identified. The threshold is then set by looking at the distribution of k-mers for each parent, it should report the value used in the splitHaplotype*.out logs, something like: "use kmers with frequency at least ...".
