### ISSUE TITLE
Small sequences missing in a bacterial assembly

### ISSUE THREAD

**Issue by touala** [marbl/canu#1295]
Hello,

I'm trying to assemble a small bacterial genome (1.6 Mbases) with nanopore reads only. While the genome can be assembled into one contig, some sequences (~20 to 50+ bp in reads but not in the assembly) are missing. There are at least 10 of those insertion issues in the assembly which seems to be supported by most reads. See exemples below.
![igv_insertion2](https://user-images.githubusercontent.com/12401381/54871974-2c48a380-4d93-11e9-8fbc-3ab41ce3c5c0.png)
![igv_insertion3](https://user-images.githubusercontent.com/12401381/54872269-c27ec880-4d97-11e9-912e-55fd350a1335.png)

I tried Canu 1.7 and 1.8 with default parameters `-nanopore-raw` using nanopore fasta file with approximately 200x coverage. I also tested with the set of parameters you recommended for metagenome assembly in case using all data would help (`corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0 redMemory=32 oeaMemory=32 batMemory=200`). I tried to correct them with Nanopolish but I think they are too long to be fixed this way. 

Are there parameters I could tweak to include those regions in the final assembly?

Regards,

Alan

**Comment by skoren** [comment]
I assume you mean the insertions indicated by IGV. Those seem to vary in location and size.  Without a multi-alignment of those reads you can't tell if they all agree or not. I would guess they're just poor quality in the reads so are left out of the consensus. You're not going to recover them with assembly settings and the Canu consensus is not meant to be the final product. You could run something like medaka or nanopolish to improve the consensus. You can also improve the consensus by using a more recent basecaller like the flip-flop option in guppy.

**Comment by touala** [comment]
Thank you for your rapid response.

I don't know how to generate a useful multi-alignment of long reads mapping on those kind of insertions (Clustal didn't gave easy to read results). Instead I tried to assembled reads from one of those events using `wtdbg2 -x ont` and obtained a contig with resolved insertion. I aligned this wtdbg2 assembly and original reads onto the canu assembly and we can see similar insertion events in reads and wtdbg2 assembly (see below). I tried canu with the same reads, and the insertion was resolved too (not shown).
![igv_insertion4](https://user-images.githubusercontent.com/12401381/54951711-b5d6ad80-4f1a-11e9-80b0-4bc36e443a59.png)

I also aligned the original reads onto the wtdbg2 assembly (not polished) to see if they all agree or not. It seems that, while they agree overall, there are multiple positions with higher error rate than usual (see below; note that I used IGV Quick Consensus mode). I color coded anchor points on both sides to match the figure above.
![igv_insertion5](https://user-images.githubusercontent.com/12401381/54951935-2e3d6e80-4f1b-11e9-98dd-07919254fe74.png)

Regarding the read quality, I'm not sure it matters but I'm using fasta, not fastq. Also, I already tried to use Nanopolish but it didn't fixed the insertions (reference in 2nd figure of my 1st post and 1st figure of this post are polished). I think the missing regions are too large to be added back in the assembly this way.

**Comment by skoren** [comment]
Nanopolish can definitely fix 50bp errors, in the scale of 10kb + reads 50bp is not large. It sounds like when you assemble a subset of reads either with canu or wtdbg2 you get the expected consensus, but using the full dataset you don't. That would make me think there is support for both versions of the consensus in the data, which would also be why nanopolish didn't change it. These sound like nanopore low quality regions so I would try seeing what you get if you re-call all your data with the latest basecaller (like flip-flop) and see how that impacts the assembly.

**Comment by touala** [comment]
I finally got some time to allocate to this projet. I end up doing one round of Racon right after Canu 1.8 assembly which resolve the insertion we observed in reads. I then run Nanopolish to improve the consensus sequence. I didn't track all regions with issue but for the one I looked at in my previous post you can see that there is a good consensus once polished (see below; IGV is in Quick Consensus mode and hidden soft-clipped reads). I don't see any reads supporting the deletion in this specific case but there is too many unchecked variables to come to any kind of conclusion. Let me know if you to want me to dig deeper.

![igv_resolved](https://user-images.githubusercontent.com/12401381/57021304-c9e88b80-6bf9-11e9-9283-2a9adc9524cc.png)

Thank you very much for your help.

**Comment by skoren** [comment]
I did find out recently that nanopolish will not fix these type of errors so that is why they remained after polishing. I'm not sure if medaka does or not. Racon will fix anything it can align a read across so it's not a bad idea to run it before nanopolish. However, I'd expect many of these to also be resolved/improved with updated base calling as well.
