### ISSUE TITLE
how to interpret suggestCircular=yes?

### ISSUE THREAD

**Issue by liu3zhenlab** [marbl/canu#1303]
The Canu (1.8) assembly was finished. Some contigs show "suggestCircular=yes" but no obvious overlapping sequences were found at both ends of a contig. The document (https://canu.readthedocs.io/en/latest/tutorial.html) says that "If yes, sequence is likely circular.  Not implemented.". Do you have any suggestion how to interpret "suggestCircular=yes" from Canu1.8? Thank you.

**Comment by skoren** [comment]
The docs shouldn't say unimplemented, I just fixed that.

The circular tag is assigned based on identified overlaps between the ends of the contig so there should be similarity on the ends. The GFA file will give the CIGAR string for this overlap which will let you compute the position. How are you looking for overlapping sequence?

**Comment by liu3zhenlab** [comment]
Thanks. Nucmer was used to perform self-alignment. Here are parameters used:
nucmer -l 30 -t 8

**Comment by skoren** [comment]
By default nucmer is going to ignore repeat seeds which will ignore the overlap regions since they aren't unique. The match might also be quite short. I'd suggest:
```nucmer --maxmatch --nosimplify``` 

as a start, you might also need to lower the -l option.

**Comment by liu3zhenlab** [comment]
Thanks Dr. Koren. I tested new parameters. I can see end overlaps in some contigs now.
