### ISSUE TITLE
No space left on device with staging

### ISSUE THREAD

**Issue by coreywischmeyer** [marbl/canu#1305]
Hi,

I'm running on SLURM and I decided to use the `stagingDirectory` argument thinking that I would have enough space, and now I'm getting "No space left on device" errors in the correctReads.<JOB_ARRAY>_<ARRAY_ID>.out files.

The issue I have is two-fold. 

At the end of one of the "out" files, I get a "Finished" timestamp, as though the program did not realize it ran out of space on the device (see below).

Knowing the store is too large to have copied to the scratch drives I would like to run things locally, what would I have to do backtrack so the program does not stage the data? 

Version `Canu 1.8`

Command:

`canu -s spec.conf -p genome -d genome_pacbio -pacbio-raw subreads.fasta`

spec.conf:

```
gnuplot=/usr/bin/gnuplot
stageDirectory=/scratch/canu_tmp/$SLURM_JOB_ID
```

Outfile snippet
```
cp: error writing '/scratch/canu_tmp/14198/genome.seqStore/blobs.0005': No space left on device
Finished at Wed Mar 27 20:46:06 CDT 2019
```

**Comment by skoren** [comment]
The "finished" message is just saying the copy returned, I expect the job quickly failed after that. What's the contents in correction/2-correction/results and one of the err files there? I expect those will recognize the copy failed.

The easiest way to restart is to remove the full correction/2-correction folder and re-launch Canu without the staging option. If you want to make staging work, there is also the ```gridEngineStageOption``` which lets you specify whatever flags you need to reserve the necessary local space on your grid nodes (assuming your grid lets you request local space and some have enough to fit the seqStore folder).

**Comment by coreywischmeyer** [comment]
Thanks Sergey,

You are right, the results directory is full of error files! Here's a look at a job that failed to copy the blobs this morning:

0074.err
```
-- Opening seqStore '/scratch/canu_tmp/14225/genome.seqStore'.
-- Opening corStore '../genome.corStore' version 1.
loadFromFile()-- After loading 0 out of 4 'sqStore::sqStore_loadDataFromFile::blob' objects (1 bytes each): End of file
    read    read evidence     corrected
      ID  length    reads       regions
-------- ------- -------- ------------- ...
 1095001   36156      139
```

I'm assuming the `loadFromFile()` bit is an error, because the job is finished and all I see left over is a 0074.WORKING.cns and no final 0074.cns file.

Nothing was written in 0074.cns, so it looks like I wouldn't have to hunt down unfinished files later. 

Does canu want to copy the whole of the ovlStore to each of the /scratch disks? My ovlStore is 650GB and I think only 1 of my 4 "nodes" has a hard drive large enough in the first place. 

If that's the case it seems the best move is to restart the correction without staging for this particular genome.

**Comment by skoren** [comment]
Nope, the ovlStore doesn't need to be copied, in fact at this point it's not needed by canu anymore. Only the seqStore (a subset of files you can see in 2-correction/correctReads.sh) need to be staged.

**Comment by coreywischmeyer** [comment]
Got it, I see that the seqStore is much smaller (54G). The issue then is not the amount of data but the amount of jobs trying to run simultaneously. 

I might go a round or two configuring a `gres.conf` and get that working on the cluster before blasting all of the 2-correction directory.

I'm also a bit fuzzy on what causes the need of a delete/re-run instead versus a rerun. Is the general rule if any configuration changes I'm probably going to have to delete some progress? For example, would artificially cutting down the number of concurrent jobs like adding `gridOptionsCOR --cpus-per-task=24` instead of it's current default setting`--cpus-per-task=4` to the specfile work without having to delete progress? I only ask because I never expect configuring SLURM to go smoothly for me.

Thanks for your help and your continued work on the canu project!

**Comment by skoren** [comment]
In general, changing threads mid-compute is OK but changing memory is more difficult because it changes the size of partitions usually. In both cases, you want to remove the sh file (so correctReads.sh and correctReads.jobSubmit*.sh in your case). 

In terms of config, canu will read a canu.defaults file from the bin folder so once you figure out settings that work well on your grid you can save them there and canu will always use them by default.

**Comment by coreywischmeyer** [comment]
Great! This cleared up a lot for me. I'll setup my general resources once the queue is cleared and if that doesn't work I'll just fiddle with the CPUs to cut down on the concurrent jobs copying data to scratch.

Thanks!
