### ISSUE TITLE
CANU assembly modes

### ISSUE THREAD

**Issue by Kirk3gaard** [marbl/canu#1306]
Hi 

CANU has a ton of cool options that allows the user to play with a number of parameters. However, most users (including myself) will probably start running with default settings and when we find new parameters from old issues or the FAQ we are likely to copy paste them for reuse even when there is a new release with better options for a given task. I know it is a bad habit but with the rapid iterations it is difficult to keep up. 

Therefore it would be super helpful if CANU had a limited set of "modes" that can be triggered and would make CANU use the recommended settings for a given version for a given task. 
e.g. --mode metagenome would activate "corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0 redMemory=32 oeaMemory=32 batMemory=200" (from the FAQ)
--mode polyploid would activate "corOutCoverage=200 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50"" (from the FAQ)
etc.

Best regards
Rasmus

**Comment by brianwalenz** [comment]
I like!  Added it to the list.  https://github.com/marbl/canu/projects/2

**Comment by harish0201** [comment]
Can I add a suggestion as well?

Please make -fast use minimap(2) as an aligner by default. Mhap is relatively still slow compared with minimap which screams around either Mhap and ovl :)

**Comment by skoren** [comment]
Might be worth benchmarking minimap2 again but last we tested it, the assemblies were noticeably worse. Speed isn't the only consideration. Part of why minimap is fast because it filters a lot of hits which can easily completely lose any overlaps to plasmids and would harm metagenomic assembly.

**Comment by harish0201** [comment]
Well, I truly agree with you on that, but when you want to evaluate a test run on a large data, it doesn't really help if your going to wait ages. To put into context, I'm assembling a 2.6Gb genome, with fairly extensive repeats (>85%), I have for correction ~450 jobs of which only 36 have finished (granted its not running on a scheduler, but its a fairly bulky compute node) in over a week. 

Maybe a switch like fast (which uses mhap) and faster which would use minimap would help?

But, pardon for being a bit off-topic, we can assemble plasmids with Canu? Damn!

**Comment by skoren** [comment]
You should take a look at the FAQ for parameters to help with speed/disk space used on repetitive genomes. That will likely help. Canu is designed to run on a grid when you have large genomes so yes, a single node will take quite a bit of time for a 3gb genome.
