### ISSUE TITLE
I also get very fragmented assemblies

### ISSUE THREAD

**Issue by splaisan** [marbl/canu#1307]
[canu_sequel.report.txt](https://github.com/marbl/canu/files/3030035/canu_sequel.report.txt)

Dear Sergey,

I did canu 1.8 assemblies (and flye) for several closely related read sets obtained from imbred bug strains with a 80-100Mb genome. The raw coverage is above 30x for all samples.

The first sample gave a very nice assembly with N50 > 130k while all other samples give a 6x narrower N50 of 13kb or so.

It seems that something (repeats! heterozygosity in the inbred population) leads to small contigs just the size of the read N50 (sequel 15kb).

Do you have any parameter I could change to try get better contiguity?

rem: Fly gives better N50 for both sample types but does not bring the bad cases to the level of the good sample.

Thanks for any advice

PS: my default options include:
```
# added to speed up small genome assembly
# ref: https://github.com/marbl/canu/issues/607
overlapper=mhap
utgReAlign=true
```

Here is the content of the unitiger file as used in https://github.com/marbl/canu/issues/892

```
less unitigging/4-unitigger/*.001.filterOverlaps.thr0*.log

INITIAL EDGES
-------- ----------------------------------------
  157125 reads are contained
  353668 reads have no best edges (singleton)
    9067 reads have only one best edge (spur) 
             7164 are mutual best
   21524 reads have two best edges 
             1952 have one mutual best edge
            18799 have two mutual best edges


ERROR RATES (257691 samples)
-----------
mean   0.03528880 stddev 0.00678549 -> 0.07600171 fraction error =   7.600171% error
median 0.03670000 mad    0.00450000 -> 0.07673020 fraction error =   7.673020% error


EDGE FILTERING
-------- ------------------------------------------
  353746 reads have a suspicious overlap pattern
       0 reads had edges filtered
                0 had one
                0 had two
    2335 reads have length incompatible edges
             1782 have one
              553 have two

FINAL EDGES
-------- ----------------------------------------
  157125 reads are contained
  356491 reads have no best edges (singleton)
   12624 reads have only one best edge (spur) 
             4577 are mutual best
   15144 reads have two best edges 
              179 have one mutual best edge
            13428 have two mutual best edges
```

**Comment by skoren** [comment]
You didn't post your full Canu command, I assume it is the defaults and you're not using the Sequel parameters from the FAQ? Start with those and don't include ```overlapper=mhap utgReAlign=true```. From your unitigging logs, the default error rate is too low and most of your reads have no overlaps due to this.

What does the corrected read distribution (which is included in the report file) to make sure your data are good and the genome really is homozygous. We've seen some random genomes have low quality PacBio data for an unknown reason, in those cases multiple rounds of correction often help (again see FAQ).

**Comment by splaisan** [comment]
Thanks Sergey,
From your answer I understand that I should remove the two defaults (_overlapper=mhap utgReAlign=true_) and add the arguments list from [#892](https://github.com/marbl/canu/issues/892), keeping 0.105 which is higher than my 7.7% error above.

canu -p canu_cust_sequel -d canu-asm_cust **corMhapSensitivity=normal corOutCoverage=100 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" OvlMerThreshold=500 correctedErrorRate=0.105** genomeSize=90m -pacbio-raw reads/m54094_190318_114306.fasta.gz

Could you please confirm this is what you advised
Thanks

**Comment by brianwalenz** [comment]
Did you compare the read length distributions in canu_sequel.report?  If the corrected reads (the second distribution) look similar to the raw reads (the first distribution), I'd leave out corMhapSensitivity and corOutCoverage -- and, in fact, you can just start the assembly from the previously corrected reads (-trim-assemble -pacbio-corrected *.correctedReads.fasta.gz).  If the corrected reads are dramatically shorter or lower coverage, we need to redo correction.

For now, I'd also leave out batOptions.  It's easy to rerun this step if needed.

**Comment by splaisan** [comment]
Thanks Brian,
So in short, the only non-default parameter I needed was **correctedErrorRate=0.105** set highher than the observed 7% right?

**Comment by brianwalenz** [comment]
Yup.

To be clear, the default is to compute overlaps to 4.5% error; the observed was 3.5% +- 0.6%, but that's obviously incorrect.  The new option will compute overlaps out to 10.5% error.  It will also be vastly slower.  Finally, this doesn't impact read corrections at all, which is why we can use the previously corrected reads again.

**Comment by skoren** [comment]
Just to clarify, ```overlapper=mhap utgReAlign=true``` are not default, those are the -fast option which speed up the assembly but may make it less continuous.

I agree with @brianwalenz, if you have good corrected reads and your genomes are really low heterozygosity (the assembly report gives a histogram of k-mer counts) you can skip re-running correction. You don't need ```corOutCoverage=100 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" OvlMerThreshold=500```, those are heterozygous genome parameters. The only one you really need is ```corMhapSensitivity=normal correctedErrorRate=0.105``` (see the FAQ for sequel v2: https://canu.readthedocs.io/en/latest/faq.html#what-parameters-should-i-use-for-my-reads).

**Comment by splaisan** [comment]
Thanks to both for your kind help,
I did not mean the two were official default but more that I added them as my own defaults (good of you to mention this for other readers).
I am now re-assembling without the fast parameters and with the full bold from my previous post and will rerun after that with only correctedErrorRate=0.105 to see the difference (I do not have 50x coverage).
Thanks for pointing me to the FAQ, I had not read this recently an dit indeed contains a lot of info (as a good FAQ should ;-)
I will post here any success with either parameter set (takes indeed much longer now)

**Comment by brianwalenz** [comment]
Idle.  Feel free to add updated results or reopen if you need more help.
