### ISSUE TITLE
Wishlist: use forward/reverse consistency to improve nanopore error correction

### ISSUE THREAD

**Issue by gringer** [marbl/canu#1308]
Would it be possible to avoid correcting any nanopore reads when the forward and reverse mapping suggest different variants?

I'm not sure how feasible it will be to do this, but figured I might as well mention it just in case it's possible.

It's well-known that nanopore reads have systematic errors, but I realised at a nanopore symposium I attended a week ago that this is not the complete story. In doing some fishing for recent research for my talk, I came across Melissa Leija-Salazar's [paper](https://doi.org/10.1002/mgg3.564) on variant detection. This bit stuck out at me:

> To investigate false‐positive SNVs further, we reviewed k‐mer motifs which were prone to error according to NanoOK for the commonest false positive (chr1: 155,211,111A>G, found in four samples; no. 7 in Supporting Information Figure S6). We noted that CAGC, where the third base corresponds to the base prone to error, was within the three commonest 4‐mer errors for substitutions in all cases. Another G>A change found as a false positive in one sample (S1) was also affecting the third base in this 4‐mer. We did not notice any relation to common error in 5‐mers. We also reviewed strand bias and found an excess in false positives (p = 0.04; supplementary note 2).

I realised / remembered that mapping direction matters for nanopore sequencing, and will produce completely different raw signals. As such, it's less likely that systematic errors will be an issue at the same location in both forward and reverse strands of the DNA. I was clued into this when thinking again about [impressively consistent variant proportions](https://twitter.com/gringene_bio/status/1026993384798339075) in systematic errors I'd seen. Looking again at the results, I noticed that these systematic errors almost looked like heterozygous variants. Further digging into the mapping data demonstrated a strand-bias in the errors. I'm now looking to see if strand consistency can be used as an indication that a variant is correct. My [preliminary investigations](https://twitter.com/gringene_bio/status/1112519488530898944) suggest that this is the case: where variant proportions are similar in forward/reverse orientation, the variant is more likely to be valid.

My rough idea about how this would work is as follows:

1. Map reads to reference sequence(s)
1. Identify forward-mapping reads; determine counts
1. Identify reverse-mapping reads; determine counts
1. Calculate chi^2 statistic to work out if foward/reverse variant counts are similar
1. Where counts are *not* similar, do not change the reference sequence

**Comment by skoren** [comment]
I wonder how true this is with the latest updates and base caller? It may also be sufficient to not rely on correction at all with the recent data as well.

**Comment by skoren** [comment]
I'm going to close this as I think it's probably not relevant for the new base callers.
