### ISSUE TITLE
Retaining all bubbles in the assembly

### ISSUE THREAD

**Issue by suvi93** [marbl/canu#1309]
Hello, I'm using canu version 1.8 to assemble a yeast genome of about 33Mb.
I want to know what are the options to be given so that I retain all the bubbles in the assembly as the genome seems to be heterozygous, and I want to do phasing after this.
I did look into issue #221 but those options did not work for me. Any idea how to go about this?

**Comment by skoren** [comment]
The FAQ lists the "split haplotype" recommended parameters. However, that won't split every bubble necessarily, it depends on the identity between the haplotypes. Canu requires about 1.5-2% divergence to separate haplotypes (assuming pacbio data).  In regions where they were more similar, you'll still get a collapsed assembly.

**Comment by suvi93** [comment]
sorry for the late response but this is the error I'm getting after running the command:

canu -d 243_canu_run2 -p yeast_243 genomeSize=33m -s ../options.txt corOutCoverage=200 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" -pacbio-raw m54151_190317_115243.fasta.gz

-- Starting command on Thu Apr 11 19:10:28 2019 with 9796.577 GB free disk space

    cd unitigging
    /home/ssubha/software/canu/Linux-amd64/bin/tgStoreCoverageStat \
      -S ../yeast_243.seqStore \
      -T  ./yeast_243.ctgStore 2 \
      -s 33000000 \
      -o ./yeast_243.ctgStore.coverageStat \
    > ./yeast_243.ctgStore.coverageStat.err 2>&1

-- Finished on Thu Apr 11 19:10:29 2019 (one second) with 9796.571 GB free disk space
----------------------------------------

ERROR:
ERROR:  Failed with exit code 134.  (rc=34304)
ERROR:

ABORT:
ABORT: Canu snapshot v1.8 +177 changes (r9387 f103a6d399bf602cdda8e7b79f8331d7d845b4e8)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to compute coverage statistics.
ABORT:
ABORT: Disk space available:  9796.568 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (unitigging/yeast_243.ctgStore.coverageStat.err):
ABORT:
ABORT:   read      324860 anchor         0 hang       0       0 position    953077    945156
ABORT:   read      437684 anchor         0 hang       0       0 position    953521    945166
ABORT:   read      384963 anchor         0 hang       0       0 position    953081    945178
ABORT:   read       73842 anchor         0 hang       0       0 position    953282    945514
ABORT:   read      266201 anchor         0 hang       0       0 position    953248    945514
ABORT:   read      288768 anchor         0 hang       0       0 position    953220    945514
ABORT:   read      389772 anchor         0 hang       0       0 position    952884    945515
ABORT:   read      132384 anchor         0 hang       0       0 position    953639    945537
ABORT:   read      321449 anchor         0 hang       0       0 position    953750    945541
ABORT:   read      307533 anchor         0 hang       0       0 position    953909    945636
ABORT:   read      305705 anchor         0 hang       0       0 position    953198    945693
ABORT:   read      333923 anchor         0 hang       0       0 position    953750    945943
ABORT:   read      450349 anchor         0 hang       0       0 position    953874    946054
ABORT:   read      429414 anchor         0 hang       0       0 position    953078    946201
ABORT:   read      119818 anchor         0 hang       0       0 position    953716    946222
ABORT:   read       40198 anchor         0 hang       0       0 position    953874    946285
ABORT:   read      285480 anchor         0 hang       0       0 position    953762    946306
ABORT:   read      404376 anchor         0 hang       0       0 position    953814    946383
ABORT:   read      201043 anchor         0 hang       0       0 position    953465    946565
ABORT:   read       44374 anchor         0 hang       0       0 position    953236    946735
ABORT:   read      149567 anchor         0 hang       0       0 position    953530    946826
ABORT:   read      232056 anchor         0 hang       0       0 position    953212    947053
ABORT:   read       27968 anchor         0 hang       0       0 position    953937    947129
ABORT:   read       10266 anchor         0 hang       0       0 position    953446    947354
ABORT:   read       24455 anchor         0 hang       0       0 position    953961    947876
ABORT:   read      240608 anchor         0 hang       0       0 position    953902    947955
ABORT:   read       72475 anchor         0 hang       0       0 position    953072    947988
ABORT:   read       86323 anchor         0 hang       0       0 position    952904    948151
ABORT:   read      385900 anchor         0 hang       0       0 position    953517    948224
ABORT:   read      252935 anchor         0 hang       0       0 position    953229    948289
ABORT:   read      149639 anchor         0 hang       0       0 position    953846    950755
ABORT:   read      293619 anchor         0 hang       0       0 position    953603    951178
ABORT:   read      227700 anchor         0 hang       0       0 position    953115    951756
ABORT:   tigend
ABORT:   tgStoreCoverageStat: stores/tgStoreCoverageStat.C:130: double computeRho(tgTig*): Assertion `minBgn == 0' failed.
ABORT:   
ABORT:   Failed with 'Aborted'; backtrace (libbacktrace):
ABORT:   utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   stores/tgStoreCoverageStat.C::130 in _Z10computeRhoP5tgTig()
ABORT:   stores/tgStoreCoverageStat.C::188 in _Z20getGlobalArrivalRateP7tgStoreP8_IO_FILEmb()
ABORT:   stores/tgStoreCoverageStat.C::523 in main()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   Aborted (core dumped)
ABORT:

How do I go about this error?
Thanks

**Comment by brianwalenz** [comment]
See issue #1319 for a solution.

**Comment by suvi93** [comment]
Thank you Brian, I've got my assembly after referring to #1319 
So, now at the end of this, I've got the diploid assembly right?

**Comment by brianwalenz** [comment]
If you have contigs.fasta, you've got an assembly.  View contigs.gfa with Bandage to see how well it separated.

**Comment by suvi93** [comment]
I will check this out, meanwhile, do you have any suggestions to get the diploid assembly?

**Comment by skoren** [comment]
As I said in my earlier comment, there is no way to guarantee you'll get a separated diploid genome short of using a trio. Canu will avoid collapsing where it can but if your haplotypes are too similar, they will be merged. You can see how much could be separated by comparing the genome size to the assembly size, the assembly should be larger if most of the genome is split or looking for duplicated core genes. Even if a large fraction is separated out, there will be phase switches within the contigs between the two haplotypes.

**Comment by suvi93** [comment]
I see, one last doubt - using the default canu options, what assembly do we get back, the haploid or diploid?

**Comment by skoren** [comment]
Not that simple, it will collapse more of the haplotypes by default but very diverged regions will still be separated (see #1326 for example). The problem for high heterozygosity genomes with default parameters is you end up with too little coverage to do a good assembly since your genome size is really double what you expected (e.g. the diploid size not the haploid size).
