### ISSUE TITLE
two overlapping contigs

### ISSUE THREAD

**Issue by wisekh6** [marbl/canu#131]
Hello,
I could run canu successfully, and canu generated '.contigs.fasta' which consists of many contigs.
I found that some contigs are (not fully but highly) overlapping each other.
Originally, I expected that any pair of two contigs would not overlap, but I might be wrong.
I wonder if you could explain me a bit about how to interpret two contigs that overlap (partially).
Can we consider them to originate from a single bigger contig? If this is the case, can I create those bigger contigs by merging the original canu contigs?

thank you,

**Comment by brianwalenz** [comment]
They weren't put together for some reason - repeats and low identity alignments come to mind - and I'd want more evidence than just an alignment to put them together.  After all, canu had those alignments (at the read level) and it decided to not put them together.

**Comment by skoren** [comment]
Canu will not split a read when generating tigs so if you a tig is split due to a repeat, you will be extending into the repeat by as much as the length of a single read. Since these are PacBio reads, they can be very long overlaps but are repeat-induced and thus can't be trusted. As Brian said, you'd want some other evidence that these unitigs should be put together.

**Comment by wisekh6** [comment]
Thank you very much, both, for your responses.

HK

**Comment by wisekh6** [comment]
I am sorry for re-opening this issue.
In my canu result, I found that a small contig (~8k bp) can be fully aligned to a different larger contig (~20k bps) with 99.8% identity. So, I wonder if I should assume that such '99.8%' identity may not be sufficient for merging the two contigs into one (Actually, the smaller contig would be discarded because of it is included in the larger one). Your comments will be highly appreciated.

thank you,

HK.
