### ISSUE TITLE
Assemblies resulting in non-zero and zero contigs.fasta files

### ISSUE THREAD

**Issue by chytrids** [marbl/canu#1314]
Hello, I am using Canu v1.3 on the Flux Linux-based operating environment at the University of Michigan to assemble contigs of demultiplexed amplicons generated from fungal genomic DNA using a Nanopore MinION. Depending on the species of fungus, the amplicon can range from 4.5 kbp to 6kbp. After filtering and demultiplexing, I have been using the following command (which I inherited from another labmate):

```
canu \
-p $myprefix -d $myoutputdirectory \
genomeSize=5000 -nanopore-raw $myfastafile \
useGrid=false "canuIteration=1" canuIteration=1 contigFilter="2 0 1.0 0.5 0"
```

Of the 204 attempted contigs, 46 have resulted in contigs.fasta files with a zero value, though all others seem to have worked well. To my untrained eye, the zeroed contigs.fasta samples do not appear drastically different from those that work, and I have not detected a trend. Assembly input is averaging around 30 reads.

Would you suggest some parameters that might need further manipulation to obtain results? If helpful, I am happy to provide further information.

Thank you for your attention,
Rabern Simmons.

**Comment by skoren** [comment]
Version 1.3 is extremely old, over 2.5 years at this point. The usage of the filter parameter changes between the current version and 1.3 so  the parameter you want is ```contigFilter="2 1000 1.0 1.0 2"``` based on looking at the old version of the documentation.

You can also just use the unassembled.fasta file which will probably have your contig.

**Comment by chytrids** [comment]
Thank you for the quick response. Now using 1.8, output is good, but perhaps too good. Using my initial command, but without ```contigFilter="2 0 1.0 0.5 0"```, works for most samples. For those with few reads, the recommended ```corMhapSensitivity=normal``` has been useful. However, in both cases, I am often seeing contigs.fasta files with one or more tigs of 1 read, in addition to the dominant 40+ read tig. Is there a way that I should be filtering out these 1 read tigs?

Thank you once again,
Rabern.

**Comment by skoren** [comment]
The 1 read tigs will get left in if they have any edges to them in the output assembly graph. Similar to issue #1313, with high depth amplicon assemblies, there isn't really anything to assemble so there are lots of reads which tend to be left behind in shorter contigs with small variations. You could try the suggested parameters in that issue or use the general rule of filtering all by the best coverage contig.

**Comment by brianwalenz** [comment]
You can automate this.  Somewhere in the canu logs (the screen output) will be a couple of `tgStoreDump` commands.  Adding option `-nreads min max` will output only configs with the specified number of reads in them.   Or change the dump type from `-consensus` to `-tigs` to get a list of the configs in the store plus (I hope) the number of reads in them.
