### ISSUE TITLE
Use of unassembled data to further improve assembly

### ISSUE THREAD

**Issue by ggargAUS** [marbl/canu#1315]
Hi,

I have assembled a plant genome of estimated size of 921 Mb using Canu v 1.8 using Sequel Pacbio reads. Current assembly size is 653Mb in 2486 contigs. The assembly generated lot of unassembled data (1322402 sequences, 11740.430 MB). 

Many of these unassembled reads have covStat is positive and reads > 10 (for example one has reads=10 covStat=66.81)

Can this data be used to further improve the assembly ?

**Comment by skoren** [comment]
It is typical to have a larger set of unassembled data than assembled data. These are filtered based on some common thresholds like fraction of contig below some threshold coverage (see FAQ for details). So even if it has 10 reads total, most of it is only composed of a couple of reads. I am not sure how you could use that data to improve the assembly, the reads didn't fit into the rest of the assembly graph so they aren't going to help. If you're going to scaffold/gapfill, you may as well use the original raw read for gap filling.

If you're not already, make sure you're using the recommended Sequel parameters from the FAQ. Also add the heterozygosity parameters if your plant is heterozygous.

**Comment by ggargAUS** [comment]
Thanks for your suggestions
