### ISSUE TITLE
Plasmid assembly

### ISSUE THREAD

**Issue by hgbrian** [marbl/canu#132]
Hi canu team,
thanks for your work on this impressive pipeline. I hope this is the right forum for this question.

Our team is trying to some simple de novo assembly of a plasmid (and several plasmids multiplexed).
In preparation for that, I wanted to get some general ideas of how easy it is to de novo assemble with different error rates and read-lengths. 

Because we are using nanopore data, most of the highest-quality reads are essentially complete plasmids. As a simple experiment, I give canu a set of simulated plasmid sequences. The easiest test case is 20 error-free exact copies of a 16kb plasmid. (I have also tried variations: 0-30% error rate, 10-40 copies, 1-10 different plasmids etc.) I get no contigs returned for any of these test cases (*.contigs.fasta is empty, and each read is assigned to its own contig in the logs).

I run canu as follows, following the tutorial:

    name="plasmids_m1"
    canu -p $name -d d_$name \
    genomeSize=16k corMhapSensitivity=high corMinCoverage=2 \
    errorRate=0.055 minOverlapLength=499 corMaxEvidenceErate=0.3 \
    -nanopore-raw $name.fasta

The clues I have from canu's output about what is going wrong:

    removeHighErrorBestEdges()-- 80 ends have no best edge; 0 ends are suspiciously high error; 0 ends are acceptable.
    BestOverlapGraph()--  suspicious 0  contained 0  spur 40  mutual-best 0  accepted 0  rejected 0

So there are no best edges and all reads are being classified as spurs? Is this perhaps a property of having so many "complete" reads as opposed to shorter, overlapping reads? (Note, miniasm also fails on this dataset, after "containment removal".)

I have also tried canu with real nanopore data generated from a plasmid, where the highest quality passing reads are essentially full-length plasmids (even more so in *.trimmedReads.fasta), and had the same result of no contigs generated, so this is not only a theoretical problem. In this case there are spurs and contained reads though.

    BestOverlapGraph()--  suspicious 0  contained 31  spur 4  mutual-best 1  accepted 0  rejected 0

I'd really like to understand how the simple simulation fails to get comfortable with the pipeline. Thanks for any advice on this!

**Comment by skoren** [comment]
Yes, Canu expects there's something to assemble so flags regions which are spanned by a single read as unassembled. We're adding info on this to our next release's documentation, see the first question here:
http://canu.readthedocs.io/en/latest/faq.html

You can either look directly in asm.unassembled.fasta or run with the suggested parameters which should promote the plasmid to asm.contigs.fasta.

**Comment by hgbrian** [comment]
Thanks! The new faq answered my question.

**Comment by open3dgenome** [comment]
Hello ... I am a bit late to the party but two years later I have the same issue and I can't figure out how to solve this problem (assembly of a simple plasmid using nanopore's MinION). 

I am afraid that I can't find the relevant information you refer to on the faq (latest and on [old commits](https://github.com/marbl/canu/commit/b56b3b48d38c674caa1b03f9ac759a0cf6418c85#diff-10baba340c992ab1555e1f4b2b3cd410))

@hgbrian Could you please show me how you solved this task of assembly of plasmids using canu? or how you solved this particular issue of impossible-to-assemble-full-covering-reads?

@skoren Could you point me to the "suggested parameters that should promote the plasmid to asm.contigs.fasta"?

My current unitigs are all around. Some match the size of the plasmid, some are at suspicious lengths for a circular template (2x or 0.5x). I have the feeling that this task should be trivial for a suite like canu but I am finding it hard to find examples out there.

Thanks in advance

**Comment by skoren** [comment]
The latest code will recover plasmids even if they are only in shorter reads/low coverage. In general, a circular plasmid will be larger than the expected size because it is circular and it will have self-similarity on the ends. 

The FAQ for settings is here: https://canu.readthedocs.io/en/latest/faq.html#my-asm-contigs-fasta-is-empty-why so anything over 3x is saved, you can change it to promote some.
