### ISSUE TITLE
Overlap store bucketizer jobs failed, tried 2 times, giving up.

### ISSUE THREAD

**Issue by coreywischmeyer** [marbl/canu#1321]
I'm on Canu 1.8 and I need some guidance on how backtrack to fix this issue. 

-- Overlap store bucketizer jobs failed, tried 2 times, giving up.
--   job trimming/genome.ovlStore.BUILDING/bucket0016 FAILED.
--   job trimming/genome.ovlStore.BUILDING/bucket0025 FAILED.

Both have the same std::bad_alloc error in the logs. 

bucketizing input   18 out of   18 - '1-overlapper/001/000518.ovb'
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Failed with 'Aborted'; backtrace (libbacktrace):
utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP7siginfoPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
../../gcc-4.8.2/libstdc++-v3/libsupc++/vterminate.cc::95 in _ZN9__gnu_cxx27__verbose_terminate_handlerEv()
../../gcc-4.8.2/libstdc++-v3/libsupc++/eh_terminate.cc::38 in _ZN10__cxxabiv111__terminateEPFvvE()
../../gcc-4.8.2/libstdc++-v3/libsupc++/eh_terminate.cc::48 in _ZSt9terminatev()
../../gcc-4.8.2/libstdc++-v3/libsupc++/eh_throw.cc::84 in __cxa_throw()
../../gcc-4.8.2/libstdc++-v3/libsupc++/new_op.cc::56 in _Znwm()
../../gcc-4.8.2/libstdc++-v3/libsupc++/new_opv.cc::32 in _Znam()
utility/arrays.H::106 in setArraySize<char, long unsigned int>()
utility/arrays.H::145 in resizeArray<char, long unsigned int>()
stores/ovStoreFile.C::365 in _ZN6ovFile10readBufferEv()
stores/ovStoreFile.C::391 in _ZN6ovFile11readOverlapEP9ovOverlap()
stores/ovStoreBucketizer.C::238 in main()
(null)::0 in (null)()
(null)::0 in (null)()
Aborted (core dumped)

**Comment by brianwalenz** [comment]
It's failing trying to read data compressed with snappy (https://google.github.io/snappy/).  I've only seen this when the file is somehow corrupted.  To fix, you'll need to rerun the overlap jobs listed in the logs just before the error:
```
bucketizing input 18 out of 18 - '1-overlapper/001/000518.ovb'
```
To rerun, rename `1-overlapper/001/000518.ovb` (and any `oc` file if it exists) to e.g.   `000518.ovb.bad` then run `overlap.sh 518` manually.  Once both jobs have been rerun, you can restart canu and it should resume with those two bucketizer jobs.

**Comment by coreywischmeyer** [comment]
Thanks Brian, 

This suggestion works perfectly.

I want to say I tried doing something like this but I think I must have missed the oc file or something.

Much appreciated,

-Corey
