### ISSUE TITLE
Nucleotides missing in the beggining and the end of the reconstructed sequence

### ISSUE THREAD

**Issue by evgisa** [marbl/canu#1327]
Hi, I’m using canu to reconstruct a 36k-length sequence. For that, I’m using the simulated reads from DeepSimulator (https://github.com/lykaust15/DeepSimulator). I have a very high coverage (>400X)  and before assembling I'm doing 6 rounds of error correction as suggested in canu documentation. 
The reconstructed sequence is perfect, however, its size is smaller than the original one. I tried with two different sequences with same size. For the first one I had 30000 reads and I have around 620 nt missing in the reconstructed one (almost 590 in the beginning and the rest in the end). For the second one I got 15000 reads and 320 nt were missing (again most of them in the beginning and the rest in the end). I’d like to know if it this is a common case, if I could solve it changing any parameter of canu or if maybe it is due to the way nanopore simulator is generating the reads.
Please, let me know if you need any further information. Thank you in advance!

**Comment by skoren** [comment]
You shouldn't need to run more then one round of correction, that's only recommended for low quality data so if the simulator matches what current sequencing looks like one round would be enough. 

Have you looked at the raw as well as the the corrected read coverage at the ends? I'd guess since the simulator is generating reads from a linear sequence, it is under-sampling the ends and you end up with much lower coverage there than everywhere else.

**Comment by evgisa** [comment]
First of all, thank you so much for the answer. Could you provide me some information about how to check the coverage in both ends? I am not aware about how to do it.

**Comment by evgisa** [comment]
First of all, thank you so much for the answer. Could you provide me some information about how to check the coverage in both ends? I am not aware about how to do it.

**Comment by skoren** [comment]
I'd start by aligning with something like minimap2 and visualizing in IGV.

**Comment by evgisa** [comment]
Thank you for your suggestion. I checked it and you were right, it's under-sampling the ends. Do you know if this is also the case with the real nanopore sequencer and how to overcome this issue?

**Comment by skoren** [comment]
No idea how to address it in the simulator but I expect this would happen in real datasets too on linear sequences. 

You can try low-coverage parameters, downsample your data randomly to 50x or 100x and run with ```corMinCoverage=0 corMhapSensitivity=high correctedErrorRate=0.20```, this should hopefully keep more of the bases from the ends. You can check if your corrected/trimmed ends have coverage on the ends with these parameters. However, Canu will never use just a single read to assemble so if you have a region on the end with only 1x coverage, you'll not be able to assemble it.

**Comment by skoren** [comment]
Low coverage in simulator explains canu behavior, sensitive parameters probably the best option to get as much assembled as possible.

**Comment by evgisa** [comment]
Sorry, I forgot to reply. I checked the coverage in both ends and it is much lower than in the rest of the genome positions. So it is an issue of the reads simulation and not canu indeed.
