### ISSUE TITLE
Meryl failed for Oxford and PacBio merged data

### ISSUE THREAD

**Issue by HTaekOppa** [marbl/canu#1328]
Hi Canu users,

I am trying to run CANU for a merged data from Oxford and PacBio reads.

FYI,

System: PBSpro
Canu version: Bioconda  CANU   1.8 pl526h470a237_0  bioconda
Canu_run.sh: See below

module load gnuplot/5.0.6-foss-2017a
module load java/1.8.0_112

cd $PBS_O_WORKDIR

source activate canu

canu -correct \
  -p QLDC -d /scratch/waterhouse_team/Taek_Test/QLD_Assemblies/CANU_QLD \
  genomeSize=3.1g \
  -pacbio-raw /work/waterhouse_team/All_RawData/Benth/PacBio_gDNA/QLD_PacBio_April_2019/NbQLD_All6.fastq \
  -nanopore-raw /work/waterhouse_team/All_RawData/Benth/AGRF_ONT_QLD/files/LSK109_L1_PAC22573/2-A7-D7/Unzip_FastA_Q/ONT_QLD_All.fastq \
  maxMemory=140 \
  minMemory=4 \
  useGrid=true \
  gridOptionsJobName=QLC \
  gridOptions="-V -l walltime=159:00:00 -W umask=0007" \
  minReadLength=1000 \
minOverlapLength=1000

It ran only for 30 minutes and caused an issue in “meryl” stage. See below. 

-- Finished stage 'merylConfigure', reset canuIteration.

ABORT:
ABORT: Canu snapshot (snapshot)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to find the number of jobs in 'correction/0-mercounts/meryl-count.sh'.
ABORT:

I have also attached a zip file (canu.01.out and QLDC.ms16.config.01.out). 
Re config.01.out, it is a total of 15 (see the attached file, too).

Any suggestion for this incident?

Looking forward to your reply!

Cheers,

Taek
[Canu_Error_Taek.zip](https://github.com/marbl/canu/files/3084823/Canu_Error_Taek.zip)

**Comment by brianwalenz** [comment]
This looks similar to other issues we've seen with bioconda installations where it incompletely installs a new version of canu on top of an older version.  Issue #1194 has details.

Or, preferably, install canu outside of bioconda.  Directions are at https://github.com/marbl/canu.  As incentive, PBS support was improved in the past week.

**Comment by HTaekOppa** [comment]
Hi Brian,

I have tried again after installing directly in HPCPro.

Two attempts were made.

1. Treated each raw data (PacBio and Nanopore) differently. 

2 Treated as a single file after merging them (PacBio and Nanopore). 


Both attempts show same error.


cd correction/0-mercounts
    ./meryl-configure.sh \
    > ./meryl-configure.err 2>&1

-- Finished on Mon Apr 29 15:14:11 2019 (3 seconds) with 345869.506 GB free disk space
----------------------------------------
--  segments   memory batches
--  -------- -------- -------
--
--  For 9426065 reads with 151127942162 bases, limit to 1511 batches.
--  Will count kmers using  jobs, each using  GB and 6 threads.
--
-- Finished stage 'merylConfigure', reset canuIteration.

ABORT:
ABORT: Canu 1.8
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to find the number of jobs in 'correction/0-mercounts/meryl-count.sh'.
ABORT:


I have attached some error files.

Any idea about this? 

Looking forward to your reply!

cheers,

Taek
[1556510525_cl4n024_25137_meryl.txt](https://github.com/marbl/canu/files/3126063/1556510525_cl4n024_25137_meryl.txt)
[canu.01.txt](https://github.com/marbl/canu/files/3126064/canu.01.txt)
[QLDC.seqStore.txt](https://github.com/marbl/canu/files/3126065/QLDC.seqStore.txt)

**Comment by skoren** [comment]
First, don't use conda to install canu, that often fails silently and ends up with incomplete/corrupted installs. Instead, use the release pages from Canu which has pre-compiled binaries available. 

You're most likely hitting the same issue as #1138. Try running the latest from the repo rather than the release, follow the instructions to build the latest unreleased from GitHub here: https://canu.readthedocs.io/en/latest/index.html#install. That should fix the bug.
