### ISSUE TITLE
After run assembly statistics check fail

### ISSUE THREAD

**Issue by abayega** [marbl/canu#133]
Hi,

I have failed to get the assembly stats after the assembly. I run the command;
canu tgStoreDump -sizes -s 4700000 -T assembly_results/unitigging/ecoliDenovo.tigStore 2 -G assembly_results/unitigging/ecoliDenovo.gkpStore

but I get the following in return;
specFile '/gs/project/wst-164-ab/anthony/Nanopore_data/C002_05_4/alignment2/assembly/4700000' not found.

Any help?
Anthony

**Comment by skoren** [comment]
The command to dump is just
```
<path to canu>/Linux-amd64/tgStoreDump -sizes -s 4700000 -T assembly_results/unitigging/ecoliDenovo.tigStore 2 -G assembly_results/unitigging/ecoliDenovo.gkpStore
```

Do not prefix canu in front of it, that is why you're getting an error.

**Comment by abayega** [comment]
Many thanks skoren, done. If there's anywhere there is more tutorials on canu apart form the documentation kindly let me know.

**Comment by skoren** [comment]
The documentation is the best reference for canu commands, the quick start page shows an example of using the tgStoreDump command:
http://canu.readthedocs.io/en/stable/quick-start.html#assembling-low-coverage-datasets

There is also a list of all commands:
http://canu.readthedocs.io/en/stable/command-reference.html
and their usages though that is probably not very useful unless you know what command you're looking for.

**Comment by abayega** [comment]
Many thanks, I will have a look
