### ISSUE TITLE
alignGFA: Canu 1.8 memory exceeded

### ISSUE THREAD

**Issue by scotthotaling** [marbl/canu#1334]
Hey all,

Canu (v1.8 +184 changes) is failing on my current assembly. Following other reports I looked in the unitigging report. I have tried increasing the memory but it doesn't seem to be altering the amount request / amount allocated ration (17021500 > 16777216) so I'm not sure if I'm doing it correctly. 

Most of the needed details should be below, happy to add others! Thank you.

- Scott

**Command**
```
#!/bin/bash
#SBATCH --partition=kamiak
#SBATCH --output=/data/kelley/projects/ice_worm_genomes/canu_ice_worm.out
#SBATCH --error=/data/kelley/projects/ice_worm_genomes/canu_ice_worm.err
#SBATCH --mail-type=END,FAIL

/data/kelley/projects/programs/canu/Linux-amd64/bin/canu \
-p ice_worm -d /scratch/scott.hotaling_82835 genomeSize=1500m \
-pacbio-raw /data/kelley/projects/ice_worm_genomes/Raw_Data/Ice_Worm_PacBio/Ice_Worm_Pacbio.fastq \
useGrid=true -gridOptionscns="--mem=150g"
```

**Version**
```
   Canu snapshot v1.8 +184 changes (r9394 033bee3d1e6d518a6c2b4828fadf9833c4e33765)
```

**Output file**
```
[scott.hotaling@login-p1n01 4-unitigger]$ cat alignGFA.8701292_1.out

Found perl:
   /usr/bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /home/scott.hotaling/jdk-11.0.1/bin/java
   openjdk version "11.0.1" 2018-10-16

Found canu:
   /data/kelley/projects/programs/canu/Linux-amd64/bin/canu
   Canu snapshot v1.8 +184 changes (r9394 033bee3d1e6d518a6c2b4828fadf9833c4e33765)

slurmstepd: error: Job 8701292 exceeded memory limit (17021500 > 16777216), being killed
slurmstepd: error: Exceeded job memory limit
slurmstepd: error: *** JOB 8701292 ON cn106 CANCELLED AT 2019-04-18T15:42:15 ***
```

**Comment by skoren** [comment]
The failing job is alignGFA not CNS so the extra memory requested there isn't helping this job. Instead of gridOptionscns set ```gridOptionsgfa="--mem=50g"``` (see also #656).

**Comment by scotthotaling** [comment]
Thank you! That was the issue I was trying to find a solution from but wasn't sure how to properly set the memory. I'll try this and report back.

**Comment by skoren** [comment]
For future users, you can always run ```canu -options``` which will list all available options, gripping for ```-i grid``` or ```-i gfa``` will find the option I mentioned.  We plan to increase the memory request for this step by default as well since it's caused several issues.

**Comment by skoren** [comment]
Any updates, did the assembly finish?

**Comment by scotthotaling** [comment]
Yes! I thought I followed up on this but clearly did not. The change worked perfectly and the assembly completed with no other issues. Thanks, @skoren.
