### ISSUE TITLE
What resources does Canu require?

### ISSUE THREAD

**Issue by crkmary** [marbl/canu#1338]
In the issue #1300 [https://github.com/marbl/canu/issues/1300], I was told that my CPU is much older than the intel CPUs and if I look up benchmarks, score at best half as fast. So I did a test using the test data downloaded from [https://github.com/marbl/canu/blob/master/documentation/source/quick-start.rst] . Download from the command line with:`curl -L -o pacbio.fastq http://gembox.cbcb.umd.edu/mhap/raw/ecoli_p6_25x.filtered.fastq`. Run the command: `canu -p ecoli -d ecoli-pacbio  genomeSize=4.8m  -pacbio-raw pacbio.fastq batThreads=48 batMemory=100`. 
In my machine which has 64-thread AMD Opteron 6380 @2.5GHz CPUs with 512Gbp of memory, canu runs for 22 minutes.

```
> Starting command on Tue Apr 23 17:10:11 2019 with 1656.906 GB free disk space
> -- Finished on Tue Apr 23 17:32:28 2019 (fast as lightning) with 1656.517 GB free disk space
```
_
In the other machine which has 2*Intel Xeon Platinum 8168 Processor （2.5GHz ，48cores per node）156GB Memory,canu runs for 27 minutes.

```
> Running jobs.  First attempt out of 2.
> -- Starting 'cormhap' concurrent execution on Tue Apr 23 18:25:21 2019 with 113.541 GB free disk space (2 processes; 6 concurrently)
> -- Finished on Tue Apr 23 18:52:46 2019 (fast as lightning) with 113.306 GB free disk space
```

**The intel CPUs does not improve the speed. Why? Do I need to set some parameters to achieve parallelism when submitting jobs with slurm?**

**Comment by skoren** [comment]
You're comparing very different systems, I expect Canu is running more jobs in parallel because of the large difference in memory and cores. 

You should't use wall clock time to compare these machines but instead using something like usr/bin/time. You should also force Canu to use the same resources (e.g. ```maxThreads=48 maxMemory=156```). I don't see any Slurm info in your logs, canu would have detected/submitted itself to the grid so I assume you're running on standalone nodes you've reserved?

**Comment by crkmary** [comment]
Now,I will run canu in the frid. The canu's logs record "Found 302 hosts with  28 cores and  256 GB memory under LSF control." Do I need to set additional parameters, for example, "gridOptions=–time 72:00:00–partitionnorm"? 
Can I copy the results running on standalone nodes and make it continue ?
I see the canu Documentation(Release 1.8). The title "2.9 My assembly is running out of space, is too slow?" mentioned that some parameters you can tweak to both reduce disk space and speed up the run. Now, Canu has taken up 2.8T disk space. Can I set parameters ` corMhapFilterThreshold=0.0000000002 corMhapOptions="--threshold
0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000
--ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50"
mhapMemory=60g mhapBlockSize=500 ovlMerDistinct=0.975` ？Will they affect continued operation?

**Comment by skoren** [comment]
Canu won't request time by itself or partitions so if you want it to run on specific partitions or allow more than the default time, then yes you need to set gridOptions to request those.

You can use those parameters but you have to set them before the run starts. If you've already started the run you can't change the parameters, even if you set them they won't affect your run. As it says on the FAQ, canu will use a few TBfor a human genome at 60x and more at lower coverage or more repetitive genomes. See issue #1039 for suggestions on some intermediate files you can clean up without changing parameters.

**Comment by crkmary** [comment]
Does the  data compression format（.fastq or fq.gz） affect the speed of software operation?

**Comment by crkmary** [comment]
I restart canu on the grid to test. The command line is` nohup canu -p asm -d asm genomeSize=3.1g -nanopore-raw ./Human.filt.fq corMaxEvidenceErate=0.22 correctedErrorRate=0.105 "corMhapOptions=–threshold 0.8–num-hashes 512–ordered-sketchsize 1000–ordered-kmer-size 14" gridOptions='-q Sharedqueue' &`
But Canu had output the following:

> -- BEGIN CORRECTION
--
--
-- Mhap precompute jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/blocks/000001.dat FAILED.
--   job correction/1-overlapper/blocks/000002.dat FAILED.
--   job correction/1-overlapper/blocks/000003.dat FAILED.
......
--   job correction/1-overlapper/blocks/000180.dat FAILED.
--   job correction/1-overlapper/blocks/000181.dat FAILED.
--   job correction/1-overlapper/blocks/000182.dat FAILED.
--   job correction/1-overlapper/blocks/000183.dat FAILED.
--

> ABORT:
> ABORT: Canu 1.8
> ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
> ABORT: Try restarting.  If that doesn't work, ask for help.
> ABORT:

And within the correction/1-overlapper folder I have the following:

> blocks
precompute.1.out  
....
precompute.183.out
mhap.sh		       
partitioning.log       
precompute.files
precompute.jobSubmit-01.out
precompute.jobSubmit-01.sh
precompute.sh
queries
queries.tar

precompute.183.out report an error:

> mv: cannot stat ‘./000183.input.dat’: No such file or directory
Mhap failed.

Why didn't my job run? These files(./*.input.dat) were not in the previous results running on standalone nodes.

**Comment by skoren** [comment]
What do you mean you restarted on grid? You cannot mix on-grid and off-grid runs, once you start off grid that job needs to run off grid. You have to start a new run on grid if you want to do that. 

There should be more information in the log error than the move message.

**Comment by crkmary** [comment]
yes,I start a new run on grid

> Sender: LSF System <lsfadmin@njblade02-28-15-hs>
Subject: Job 4507[183]: <cormhap_asm[1-183]> in cluster <YZ-parallel-2> Exited

Job <cormhap_asm[1-183]> was submitted from host <njblade02-31-07-hs> by user <sc11134> in cluster <YZ-parallel-2> at Mon May  6 15:30:52 2019
Job was executed on host(s) <14*njblade02-28-15-hs>, in queue <Sharedqueue>, as user <sc11134> in cluster <YZ-parallel-2> at Mon May  6 15:30:53 2019
</YZGROUP4/home/sc11134> was used as the home directory.
</YZGROUP4/home/sc11134/20190430/rawdata/asm/correction/1-overlapper> was used as the working directory.
Started at Mon May  6 15:30:53 2019
Terminated at Mon May  6 15:31:10 2019
Results reported at Mon May  6 15:31:10 2019

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
./precompute.sh 0
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   2.95 sec.
    Max Memory :                                 1 GB
    Average Memory :                             0.50 GB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   -
    Max Processes :                              4
    Max Threads :                                5
    Run time :                                   16 sec.
    Turnaround time :                            18 sec.

The output (if any) follows:


Found perl:
   /usr/bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /usr/bin/java
   openjdk version "1.8.0_65"

Found canu:
   /YZGROUP4/home/sc11134/canu-1.8/Linux-amd64/bin/canu
   Canu 1.8

Running job 183 based on LSB_JOBINDEX=183 and offset=0.
Dumping reads from 23587201 to 23703590 (inclusive).

Starting mhap precompute.

Unknown parameter in command line: –threshold
MHAP: MinHash Alignment Protocol. A tool for finding overlaps of long-read sequences (such as PacBio or Nanopore) in bioinformatics.
	Version: 2.1.3
	Usage 1 (direct execution): java -server -Xmx<memory> -jar <MHAP jar> -s<fasta/dat from/self file> [-q<fasta/dat to file>] [-f<kmer filter list, must be sorted>]
	Usage 2 (generate precomputed binaries): java -server -Xmx<memory> -jar <MHAP jar> -p<directory of fasta files> -q <output directory> [-f<kmer filter list, must be sorted>]
		--filter-threshold, default = 1.0E-7
			[double], The cutoff at which the k-mer in the k-mer filter file is considered repetitive. This value for a specific k-mer is specified in the second column in the filter file. If no filter file is provided, this option is ignored.
		--help, default = false
			Displays the help menu.
		--max-shift, default = 0.2
			[double], Region size to the left and right of the estimated overlap, as derived from the median shift and sequence length, where a k-mer matches are still considered valid. Second stage filter only.
		--min-olap-length, default = 500
			[int], The minimum length of the read that used for overlapping. Used to filter out short reads from FASTA file.
		--min-store-length, default = 0
			[int], The minimum length of the read that is stored in the box. Used to filter out short reads from FASTA file.
		--no-rc, default = false
			Do not store or do comparison of the reverse compliment strings.
		--no-self, default = false
			Do not compute the overlaps between sequences inside a box. Should be used when the to and from sequences are coming from different files.
		--no-tf, default = false
			Do not perform the tf weighing, in the tf-idf weighing.
		--num-hashes, default = 512
			[int], Number of min-mers to be used in MinHashing.
		--num-min-matches, default = 3
			[int], Minimum # min-mer that must be shared before computing second stage filter. Any sequences below that value are considered non-overlapping.
		--num-threads, default = 14
			[int], nNumber of threads to use for computation. Typically set to #cores.
		--ordered-kmer-size, default = 12
			[int] The size of k-mers used in the ordered second stage filter.
		--ordered-sketch-size, default = 1536
			[int] The sketch size for second stage filter.
		--repeat-idf-scale, default = 10.0
			[double] The upper range of the idf (from tf-idf) scale. The full scale will be [1,X], where X is the parameter.
		--repeat-weight, default = 0.9
			[double] Repeat suppression strength for tf-idf weighing. <0.0 do unweighted MinHash (version 1.0), >=1.0 do only the tf weighing. To perform no idf weighting, do no supply -f option. 
		--settings, default = 0
			Set all unset parameters for the default settings. Same defaults are applied to Nanopore and Pacbio reads. 0) None, 1) Default, 2) Fast, 3) Sensitive.
		--store-full-id, default = true
			Store full IDs as seen in FASTA files, rather than storing just the sequence position in the file. Some FASTA files have long IDS, slowing output of results. This options is ignored when using compressed file format. Indexed file (-s) is indexed first, followed by -q files in alphabetical order.
		--supress-noise, default = 0
			[int] 0) Does nothing, 1) completely removes any k-mers not specified in the filter file, 2) supresses k-mers not specified in the filter file, similar to repeats. 
		--threshold, default = 0.83
			[double], The threshold cutoff for the second stage sort-merge filter. This is based on the identity score computed from the Jaccard distance of k-mers (size given by ordered-kmer-size) in the overlapping regions.
		--version, default = false
			Displays the version and build time.
		-f, default = ""
			k-mer filter file used for filtering out highly repetative k-mers. Must be sorted in descending order of frequency (second column).
		-h, default = false
			Displays the help menu.
		-k, default = 16
			[int], k-mer size used for MinHashing. The k-mer size for second stage filter is seperate, and can also be modified.
		-p, default = ""
			Usage 2 only. The directory containing FASTA files that should be converted to binary format for storage.
		-q, default = ""
			Usage 1: The FASTA file of reads, or a directory of files, that will be compared to the set of reads in the box (see -s). Usage 2: The output directory for the binary formatted dat files.
		-s, default = ""
			Usage 1 only. The FASTA or binary dat file (see Usage 2) of reads that will be stored in a box, and that all subsequent reads will be compared to.

mv: cannot stat ‘./000183.input.dat’: No such file or directory
Mhap failed.

**Comment by skoren** [comment]
Ah right, your corMhapOptions are wrong: "corMhapOptions=–threshold 0.8–num-hashes 512–ordered-sketchsize 1000–ordered-kmer-size 14". There are no spaces and it should be using -- not -.

**Comment by crkmary** [comment]
I am running Canu version 1.8 not master, do I need to update this parameter(corMhapPptions）? However, when I tried to update this parameter, I still got the same error.

**Comment by brianwalenz** [comment]
There's a chance we're not rewriting the `precompute.sh` script with the new options.  Remove the whole `correction/1-overlapper` directory and retry.

If it still fails, paste in the *exact* canu command being run, and the full java command at the end of `precompute.sh`.

Example java command:
```
java -d64 -XX:ParallelGCThreads=12 -server -Xms44237m -Xmx44237m \
  -jar  $bin/../share/java/classes/mhap-2.1.3.jar  \
  --repeat-weight 0.9 --repeat-idf-scale 10 -k 16 \
  --store-full-id \
  --num-hashes 256 \
  --num-min-matches 3 \
  --ordered-sketch-size 1000 \
  --ordered-kmer-size 14 \
  --threshold 0.85 \
  --filter-threshold 0.0000001 \
  --min-olap-length 500 \
  --num-threads 12 \
  -f  ../../0-mercounts/test.ms16.ignore.gz  \
  -p  ./$job.input.fasta  \
  -q  .  \
```

**Comment by crkmary** [comment]
I start a new run on grid with canu 1.8 . 
Last time, canu had output the following:

> -- Starting 'cormhap' concurrent execution on Fri Mar 29 13:36:57 2019 with 2155.198 GB free disk space (331 processes; 4 concurrently)

    cd correction/1-overlapper
    ./mhap.sh 122 > ./mhap.000122.out 2>&1
    ./mhap.sh 123 > ./mhap.000123.out 2>&1
    ./mhap.sh 125 > ./mhap.000125.out 2>&1
    ./mhap.sh 126 > ./mhap.000126.out 2>&1
    ./mhap.sh 127 > ./mhap.000127.out 2>&1
    ./mhap.sh 128 > ./mhap.000128.out 2>&1

But now, why not canu has such output again? How do I know where the software is going?

**Comment by crkmary** [comment]
oh, I'm also worried about a problem. When I set the parameters, I was careless that these parameters(`mhapMemory=60g mhapBlockSize=500 ovlMerDistinct=0.975`) were omitted and other parameters(`corMhapFilterThreshold=0.0000000002 corMhapOptions="--threshold 0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50"`) are set. 
Does this lead to errors? Can some parameters  reduce disk space? What should I do?

**Comment by skoren** [comment]
It doesn't lead to errors but you might encounter out of memory issues with the mhap step. If it runs and fits into memory, then you're fine and don't need to change anything. The ovlMerDistinct parameter only affects the run after correction so you can always stop canu after you have corrected reads and add it.
