### ISSUE TITLE
Trying to understand gfa file

### ISSUE THREAD

**Issue by gwaldbieser** [marbl/canu#134]
Canu corrected and assembled pacbio reads from a 4Mb bacterial genome into 6 contigs (0, 1, 2, 3, 16, and 17 below). I've included the .gfa file below. The Segment lines show the length and read count of the six contigs that would be trusted, a couple of lower coverage contigs that might or might not be something, and single read contigs that I would ignore. However, is the last field in each Linkage line a cigar string - thus tig0 and tig2 have an overlap of 19,868 matching bases? Or are there a total of 19,868 overlaps between these two contigs? Thanks.

$ cat assembly.gfa
H       VN:Z:bogart
S       tig00000000     *       LN:i:1790014    RC:i:9792
S       tig00000001     *       LN:i:851255     RC:i:5443
S       tig00000002     *       LN:i:535568     RC:i:2756
S       tig00000003     *       LN:i:58558      RC:i:369
S       tig00000004     *       LN:i:7220       RC:i:1
S       tig00000005     *       LN:i:5904       RC:i:1
S       tig00000006     *       LN:i:5858       RC:i:1
S       tig00000007     *       LN:i:2958       RC:i:1
S       tig00000008     *       LN:i:1198       RC:i:1
S       tig00000009     *       LN:i:5581       RC:i:1
S       tig00000010     *       LN:i:5852       RC:i:1
S       tig00000011     *       LN:i:2967       RC:i:1
S       tig00000012     *       LN:i:6980       RC:i:1
S       tig00000013     *       LN:i:6960       RC:i:1
S       tig00000014     *       LN:i:9337       RC:i:21
S       tig00000015     *       LN:i:4943       RC:i:5
S       tig00000016     *       LN:i:196437     RC:i:1385
S       tig00000017     *       LN:i:515249     RC:i:3858
L       tig00000000     +       tig00000002     -       19868m
L       tig00000001     -       tig00000016     -       9775m
L       tig00000001     -       tig00000002     +       536035m
L       tig00000002     +       tig00000001     -       536035m
L       tig00000002     -       tig00000000     +       19868m
L       tig00000003     -       tig00000016     -       7760m
L       tig00000003     -       tig00000017     +       59825m
L       tig00000016     +       tig00000000     -       7412m
L       tig00000016     -       tig00000017     +       196450m
L       tig00000016     -       tig00000017     -       9765m

**Comment by brianwalenz** [comment]
Hi, Geoff-  Quite excellent timing you have.  I've been working on the GFA output this week, and just committed an improvement.  The output above is trying to show intersections, where the end of one unitig intersects the middle of another.  tig1 and tig2 are probably this - it is unlikely that there is a 536k overlap between them.  But, GFA doesn't really support this, and Bandage certainly can't show it.

The new version will show just end-to-end overlaps between contigs, and (eventually) circular contigs.  The cigar string isn't being computed.  It's just showing the average length of the aligned pieces.  Good enough to draw a graph, not nearly good enough to extract sequences.

To rerun, remove 4-unitigger, 5-consensus and the canu outputs in the root assembly directory.
