### ISSUE TITLE
Optimizing parameters to mitigate parallel I/O issues

### ISSUE THREAD

**Issue by JackyHess** [marbl/canu#1340]
Hi there,
 
I am running CANU on a SLURM cluster running off NAS storage which is proving problematic for the read correction step. 

It is possible to restrict the number of concurrent high I/O jobs on our cluster using a license system and I would like to pass this option to the grid. I would only like to do this for jobs that require throttling to that end though to avoid unnecessarily slowing down the assembly.

Based on reading other posts here, corMhap seems to be the main culprit overloading the file system so I will specifically place these jobs under highIO license using gridOptionsCORMHAP.

My question is: are there any other jobs with high I/O demands that should be placed under such a license as well? I would like to be on the safe side to avoid bringing the whole file system down again.

This is the command I have been using so far:

`canu -correct -p Tlei -d Tlei genomeSize=1.2g -pacbio-raw DTG-DNA-499.subreads.bam.fasta maxMemory=320G maxThreads=20 gridEngine=slurm gridEngineMemoryOption='--mem=MEMORY' gridEngineThreadsOption='--cpus-per-task=THREADS' gridOptionsJobName=Tle stageDirectory=\$TMPDIR`

Canu version is 1.8

Thanks very much for your help,

Jacky

**Comment by skoren** [comment]
You should be able restrict all array on slurm by adding ```gridEngineArrayOption="-a ARRAY_JOBS%50"```. Change 50 to whatever you want the limit to be. 

The corMhap step is essentially just writing text to disk, it isn't doing any random seek so I would think you'd hit issues on other steps that do seek as well. I'd also suggest looking into using the ```gridEngineStageOption``` and ```stageDirectory``` options. It is only used in one step but can cut down on random I/O significantly.

**Comment by JackyHess** [comment]
OK, great. Thank you very much for your suggestions! 

I had tried the stageDirectory option but the run didn't even get to the consensus step before crashing the file system. It seems like limiting the amount of concurrent jobs is the way to go for our set up.
