### ISSUE TITLE
Underscores versus spaces in fasta headers output

### ISSUE THREAD

**Issue by thierryjanssens** [marbl/canu#1341]
In two consecutive analyses I have encountered spaces versus underscores as separators for the respective fields in the generated fasta headers. I do not understand this unexpected behaviour...
Is there a setting that I overlooked?

**Comment by brianwalenz** [comment]
I assume you're referring to our contigs/unitigs.fasta output?
```
>tig00000001 len=4862011 reads=35387 covStat=10342.22 gappedBases=no class=contig suggestRepeat=no suggestCircular=yes
```
There's no real specification for the fasta headers, except that the first word (white space separated) is the 'name' of the sequence.  The rest of the words in the line are just free-text annotation.  We've always output in this format, no options to change it.

**Comment by thierryjanssens** [comment]
#
