### ISSUE TITLE
controlling overlapInCore  stringency.

### ISSUE THREAD

**Issue by bernardo1963** [marbl/canu#1342]
Hi,
I am using canu1.7 and I am trying to obain better assemblies in repetitive regions. For this purpose  I would like to play with  the stringency of overlapInCore in the k-mer seeding step. Other overlappers  have parameters that directly control stringency at the seeding step  (eg, MHAP has --num-min-matches  , daligner has -h ), but I could not find the equivalent parameter in overlapInCore. When I issued canu -options I found 
utgOvlMerDistinct	( K-mer frequency threshold; the least frequent fraction of distinct mers can seed overlaps)
but looking into canu code (Defaults.pm) its default value seems to be undef , and it is not mentioned in any other piece of the code. Is utgOvlMerDistinct  effectivelly used in canu?   Are there parameters in Canu which control how many shared k-mers two reads must have in order to "promote" them  to the next step (fine alignment)? 
Bernardo

**Comment by skoren** [comment]
Yes, it is used but is auto-set to include a fraction of k-mers. You can explicitly set it to a threshold or you can set ovlMerDistinct to a fraction (values between 0 and 1, higher keeps more repeat k-mers). A single seed in overlapInCore is sufficient to seed an overlap and compute alignments.
