### ISSUE TITLE
Canu -assemble step stucked 

### ISSUE THREAD

**Issue by fsq9451** [marbl/canu#1345]
Hi!

I had propose the isuue > #1326 , but tried to redo the assemble process using hetero- parameters:

canu -assemble -p new1 -d newAsm correctedErrorRate=0.105 maxThreads=30 genomeSize=560m -pacbio-corrected ./trim/trim.trimmedReads.fasta.gz "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50"

I stucked on the step here and need your help! Thanks

```
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_121' (from '/home/caupql/miniconda2/bin/java') with -d64 support.
--
-- WARNING:
-- WARNING:  Failed to run gnuplot using command 'gnuplot'.
-- WARNING:  Plots will be disabled.
-- WARNING:
--
-- Detected 40 CPUs and 504 gigabytes of memory.
-- Limited to 30 CPUs from maxThreads option.
-- No grid engine detected, grid disabled.
--
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |     total usage     algorithm
--        -------  ------  --------   --------  -----------------  -----------------------------
-- Local: meryl     24 GB    6 CPUs x   5 jobs   120 GB   30 CPUs  (k-mer counting)
-- Local: hap       12 GB   15 CPUs x   2 jobs    24 GB   30 CPUs  (read-to-haplotype assignment)
-- Local: cormhap   32 GB   15 CPUs x   2 jobs    64 GB   30 CPUs  (overlap detection with mhap)
-- Local: obtovl    16 GB   15 CPUs x   2 jobs    32 GB   30 CPUs  (overlap detection)
-- Local: utgovl    16 GB   15 CPUs x   2 jobs    32 GB   30 CPUs  (overlap detection)
-- Local: cor       16 GB    4 CPUs x   7 jobs   112 GB   28 CPUs  (read correction)
-- Local: ovb        4 GB    1 CPU  x  30 jobs   120 GB   30 CPUs  (overlap store bucketizer)
-- Local: ovs       16 GB    1 CPU  x  30 jobs   480 GB   30 CPUs  (overlap store sorting)
-- Local: red       12 GB    6 CPUs x   5 jobs    60 GB   30 CPUs  (read error detection)
-- Local: oea        4 GB    1 CPU  x  30 jobs   120 GB   30 CPUs  (overlap error adjustment)
-- Local: bat      256 GB   16 CPUs x   1 job    256 GB   16 CPUs  (contig construction with bogart)
-- Local: cns      --- GB    8 CPUs x --- jobs   --- GB  --- CPUs  (consensus)
-- Local: gfa       16 GB   16 CPUs x   1 job     16 GB   16 CPUs  (GFA alignment and processing)
--
-- In 'new1.seqStore', found PacBio reads:
--   Raw:        0
--   Corrected:  1925218
--   Trimmed:    1925218
--
-- Generating assembly 'new1' in '/home/caupql/Softwares/Aca/canu/lbg1_pac/newAsm'
--
-- Parameters:
--
--  genomeSize        560000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.1050 ( 10.50%)
--    utgOvlErrorRate 0.1050 ( 10.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.1050 ( 10.50%)
--    utgErrorRate    0.1050 ( 10.50%)
--    cnsErrorRate    0.1050 ( 10.50%)
--
--
-- BEGIN ASSEMBLY
--
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'utgovl' concurrent execution on Fri Apr 19 13:38:53 2019 with 1370.589 GB free disk space (69 processes; 2 concurrently)

    cd unitigging/1-overlapper
    ./overlap.sh 72 > ./overlap.000072.out 2>&1
    ./overlap.sh 73 > ./overlap.000073.out 2>&1
    ./overlap.sh 74 > ./overlap.000074.out 2>&1
    ./overlap.sh 75 > ./overlap.000075.out 2>&1
    ./overlap.sh 76 > ./overlap.000076.out 2>&1
    ./overlap.sh 77 > ./overlap.000077.out 2>&1
    ./overlap.sh 78 > ./overlap.000078.out 2>&1
    ./overlap.sh 79 > ./overlap.000079.out 2>&1
    ./overlap.sh 80 > ./overlap.000080.out 2>&1
    ./overlap.sh 81 > ./overlap.000081.out 2>&1
    ./overlap.sh 82 > ./overlap.000082.out 2>&1
    ./overlap.sh 83 > ./overlap.000083.out 2>&1
    ./overlap.sh 84 > ./overlap.000084.out 2>&1
    ./overlap.sh 85 > ./overlap.000085.out 2>&1
    ./overlap.sh 86 > ./overlap.000086.out 2>&1
    ./overlap.sh 87 > ./overlap.000087.out 2>&1
    ./overlap.sh 88 > ./overlap.000088.out 2>&1
    ./overlap.sh 89 > ./overlap.000089.out 2>&1
    ./overlap.sh 90 > ./overlap.000090.out 2>&1
    ./overlap.sh 91 > ./overlap.000091.out 2>&1
    ./overlap.sh 92 > ./overlap.000092.out 2>&1
    ./overlap.sh 93 > ./overlap.000093.out 2>&1
    ./overlap.sh 94 > ./overlap.000094.out 2>&1
    ./overlap.sh 95 > ./overlap.000095.out 2>&1
    ./overlap.sh 96 > ./overlap.000096.out 2>&1
    ./overlap.sh 97 > ./overlap.000097.out 2>&1
    ./overlap.sh 98 > ./overlap.000098.out 2>&1
    ./overlap.sh 99 > ./overlap.000099.out 2>&1
    ./overlap.sh 100 > ./overlap.000100.out 2>&1
    ./overlap.sh 101 > ./overlap.000101.out 2>&1
    ./overlap.sh 102 > ./overlap.000102.out 2>&1
    ./overlap.sh 103 > ./overlap.000103.out 2>&1
    ./overlap.sh 104 > ./overlap.000104.out 2>&1
    ./overlap.sh 105 > ./overlap.000105.out 2>&1
    ./overlap.sh 106 > ./overlap.000106.out 2>&1
    ./overlap.sh 107 > ./overlap.000107.out 2>&1
    ./overlap.sh 108 > ./overlap.000108.out 2>&1
    ./overlap.sh 109 > ./overlap.000109.out 2>&1
    ./overlap.sh 110 > ./overlap.000110.out 2>&1
    ./overlap.sh 111 > ./overlap.000111.out 2>&1
    ./overlap.sh 112 > ./overlap.000112.out 2>&1
    ./overlap.sh 113 > ./overlap.000113.out 2>&1
    ./overlap.sh 114 > ./overlap.000114.out 2>&1
    ./overlap.sh 115 > ./overlap.000115.out 2>&1
    ./overlap.sh 116 > ./overlap.000116.out 2>&1
    ./overlap.sh 117 > ./overlap.000117.out 2>&1
    ./overlap.sh 118 > ./overlap.000118.out 2>&1
    ./overlap.sh 119 > ./overlap.000119.out 2>&1
    ./overlap.sh 120 > ./overlap.000120.out 2>&1
    ./overlap.sh 121 > ./overlap.000121.out 2>&1
    ./overlap.sh 122 > ./overlap.000122.out 2>&1
    ./overlap.sh 123 > ./overlap.000123.out 2>&1
    ./overlap.sh 124 > ./overlap.000124.out 2>&1
    ./overlap.sh 125 > ./overlap.000125.out 2>&1
    ./overlap.sh 126 > ./overlap.000126.out 2>&1
    ./overlap.sh 127 > ./overlap.000127.out 2>&1
    ./overlap.sh 128 > ./overlap.000128.out 2>&1
    ./overlap.sh 129 > ./overlap.000129.out 2>&1
    ./overlap.sh 130 > ./overlap.000130.out 2>&1
    ./overlap.sh 131 > ./overlap.000131.out 2>&1
    ./overlap.sh 132 > ./overlap.000132.out 2>&1
    ./overlap.sh 133 > ./overlap.000133.out 2>&1
    ./overlap.sh 134 > ./overlap.000134.out 2>&1
    ./overlap.sh 135 > ./overlap.000135.out 2>&1
    ./overlap.sh 136 > ./overlap.000136.out 2>&1
    ./overlap.sh 137 > ./overlap.000137.out 2>&1
    ./overlap.sh 138 > ./overlap.000138.out 2>&1
    ./overlap.sh 139 > ./overlap.000139.out 2>&1
    ./overlap.sh 140 > ./overlap.000140.out 2>&1

-- Finished on Wed May  1 19:30:34 2019 (1057901 seconds, fashionably late) with 1533.654 GB free disk space
----------------------------------------
-- Found 140 overlapInCore output files.
--
-- overlapInCore compute 'unitigging/1-overlapper':
--   kmer hits
--     with no overlap      67713346830  763.071429 +- 248439208.134
--     with an overlap        155645641  4.57857143 +- 568785.605
--
--   overlaps                 155645641  4.57857143 +- 568785.605
--     contained               52927247  .764285714 +- 192204.778
--     dovetail               102718394  .814285714 +- 376655.393
--
--   overlaps rejected
--     multiple per pair              0           0 +- 0
--     bad short window               0           0 +- 0
--     bad long window                0           0 +- 0
-- Finished stage 'utg-overlapCheck', reset canuIteration.
----------------------------------------
-- Starting command on Wed May  1 19:30:36 2019 with 1533.654 GB free disk space

    cd unitigging
    /home/caupql/Softwares/Aca/canu/Linux-amd64/bin/ovStoreConfig \
     -S ../new1.seqStore \
     -M 8-16 \
     -L ./1-overlapper/ovljob.files \
     -create ./new1.ovlStore.config \
     > ./new1.ovlStore.config.txt \
    2> ./new1.ovlStore.config.err

-- Finished on Wed May  1 19:30:43 2019 (7 seconds) with 1533.65 GB free disk space
----------------------------------------
--
-- Creating overlap store unitigging/new1.ovlStore using:
--      2 buckets
--      2 slices
--        using at most 7 GB memory each
-- Finished stage 'utg-overlapStoreConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'ovB' concurrent execution on Wed May  1 19:30:43 2019 with 1533.65 GB free disk space (2 processes; 30 concurrently)

    cd unitigging/new1.ovlStore.BUILDING
    ./scripts/1-bucketize.sh 1 > ./logs/1-bucketize.000001.out 2>&1
    ./scripts/1-bucketize.sh 2 > ./logs/1-bucketize.000002.out 2>&1

-- Finished on Wed May  1 19:31:20 2019 (37 seconds) with 1531.305 GB free disk space
----------------------------------------
--
-- Overlap store bucketizer jobs failed, retry.
--   job unitigging/new1.ovlStore.BUILDING/bucket0001 FAILED.
--   job unitigging/new1.ovlStore.BUILDING/bucket0002 FAILED.
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'ovB' concurrent execution on Wed May  1 19:31:20 2019 with 1531.305 GB free disk space (2 processes; 30 concurrently)

    cd unitigging/new1.ovlStore.BUILDING
    ./scripts/1-bucketize.sh 1 > ./logs/1-bucketize.000001.out 2>&1
    ./scripts/1-bucketize.sh 2 > ./logs/1-bucketize.000002.out 2>&1

-- Finished on Wed May  1 19:31:48 2019 (28 seconds) with 1531.304 GB free disk space
----------------------------------------
--
-- Overlap store bucketizer jobs failed, tried 2 times, giving up.
--   job unitigging/new1.ovlStore.BUILDING/bucket0001 FAILED.
--   job unitigging/new1.ovlStore.BUILDING/bucket0002 FAILED.
--

ABORT:
ABORT: Canu snapshot v1.8 +177 changes (r9387 f103a6d399bf602cdda8e7b79f8331d7d845b4e8)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
Command exited with non-zero status 1
14549928.42user 33766.29system 293:52:58elapsed 1378%CPU (0avgtext+0avgdata 8564572maxresident)k
35318368inputs+14397160outputs (70726major+19707248219minor)pagefaults 0swaps
```

**Comment by skoren** [comment]
This is typically due to filesystem corruption, can you post both the logs of the failed files (```unitigging/new1.ovlStore.BUILDING/logs/*.out```).

**Comment by fsq9451** [comment]
Hi @skoren ,
This is the files.

cat unitigging/new1.ovlStore.BUILDING/logs/*.out

Found perl:
   /home/caupql/miniconda2/bin/perl
   This is perl 5, version 22, subversion 0 (v5.22.0) built for x86_64-linux-thread-multi

Found java:
   /home/caupql/miniconda2/bin/java
   openjdk version "1.8.0_121"

Found canu:
   /home/caupql/Softwares/Aca/canu/Linux-amd64/bin/canu
   Canu snapshot v1.8 +177 changes (r9387 f103a6d399bf602cdda8e7b79f8331d7d845b4e8)

Running job 1 based on command line options.

Attempting to increase maximum allowed processes and open files.
./scripts/1-bucketize.sh: 1: ulimit: Illegal option -u
./scripts/1-bucketize.sh: 1: ulimit: Illegal option -u
./scripts/1-bucketize.sh: 72: ulimit: Illegal option -u
./scripts/1-bucketize.sh: 1: ulimit: Illegal option -u
  Changed max processes per user from  to  (max ).
  Changed max open files from 1024 to 1048576 (max 1048576).

Overwriting incomplete result from presumed crashed job in directory './new1.ovlStore.BUILDING/create0001'.

Opened '../new1.seqStore' with 1925218 reads.

Constructing slice 1 for store './new1.ovlStore.BUILDING'.
 - Filtering overlaps over 1.0000 fraction error.

Bucketizing input    1 out of   70 - '1-overlapper/001/000001.ovb'
Bucketizing input    2 out of   70 - '1-overlapper/001/000003.ovb'
Bucketizing input    3 out of   70 - '1-overlapper/001/000005.ovb'
Bucketizing input    4 out of   70 - '1-overlapper/001/000007.ovb'
Bucketizing input    5 out of   70 - '1-overlapper/001/000009.ovb'
Bucketizing input    6 out of   70 - '1-overlapper/001/000011.ovb'
Bucketizing input    7 out of   70 - '1-overlapper/001/000013.ovb'
Bucketizing input    8 out of   70 - '1-overlapper/001/000015.ovb'
Bucketizing input    9 out of   70 - '1-overlapper/001/000017.ovb'
Bucketizing input   10 out of   70 - '1-overlapper/001/000019.ovb'
Bucketizing input   11 out of   70 - '1-overlapper/001/000021.ovb'
Bucketizing input   12 out of   70 - '1-overlapper/001/000023.ovb'
Bucketizing input   13 out of   70 - '1-overlapper/001/000025.ovb'
Bucketizing input   14 out of   70 - '1-overlapper/001/000027.ovb'
Bucketizing input   15 out of   70 - '1-overlapper/001/000029.ovb'
Bucketizing input   16 out of   70 - '1-overlapper/001/000031.ovb'
Bucketizing input   17 out of   70 - '1-overlapper/001/000033.ovb'
Bucketizing input   18 out of   70 - '1-overlapper/001/000035.ovb'
Bucketizing input   19 out of   70 - '1-overlapper/001/000037.ovb'
Bucketizing input   20 out of   70 - '1-overlapper/001/000039.ovb'
Bucketizing input   21 out of   70 - '1-overlapper/001/000041.ovb'
Bucketizing input   22 out of   70 - '1-overlapper/001/000043.ovb'
Bucketizing input   23 out of   70 - '1-overlapper/001/000045.ovb'
Bucketizing input   24 out of   70 - '1-overlapper/001/000047.ovb'
Bucketizing input   25 out of   70 - '1-overlapper/001/000050.ovb'
Bucketizing input   26 out of   70 - '1-overlapper/001/000051.ovb'
Bucketizing input   27 out of   70 - '1-overlapper/001/000054.ovb'
Bucketizing input   28 out of   70 - '1-overlapper/001/000055.ovb'
Bucketizing input   29 out of   70 - '1-overlapper/001/000058.ovb'
Bucketizing input   30 out of   70 - '1-overlapper/001/000059.ovb'
Bucketizing input   31 out of   70 - '1-overlapper/001/000062.ovb'
Bucketizing input   32 out of   70 - '1-overlapper/001/000063.ovb'
Bucketizing input   33 out of   70 - '1-overlapper/001/000066.ovb'
Bucketizing input   34 out of   70 - '1-overlapper/001/000067.ovb'
Bucketizing input   35 out of   70 - '1-overlapper/001/000070.ovb'
Bucketizing input   36 out of   70 - '1-overlapper/001/000071.ovb'
Bucketizing input   37 out of   70 - '1-overlapper/001/000074.ovb'
Bucketizing input   38 out of   70 - '1-overlapper/001/000075.ovb'
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Failed with 'Aborted'; backtrace (libbacktrace):
utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
utility/arrays.H::106 in _Z12setArraySizeIcmEvRPT_mRT0_mj()
utility/arrays.H::145 in _Z11resizeArrayIcmEvRPT_mRT0_mj()
stores/ovStoreFile.C::376 in _ZN6ovFile10readBufferEv()
stores/ovStoreFile.C::402 in _ZN6ovFile11readOverlapEP9ovOverlap()
stores/ovStoreBucketizer.C::238 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
Aborted (core dumped)

Found perl:
   /home/caupql/miniconda2/bin/perl
   This is perl 5, version 22, subversion 0 (v5.22.0) built for x86_64-linux-thread-multi

Found java:
   /home/caupql/miniconda2/bin/java
   openjdk version "1.8.0_121"

Found canu:
   /home/caupql/Softwares/Aca/canu/Linux-amd64/bin/canu
   Canu snapshot v1.8 +177 changes (r9387 f103a6d399bf602cdda8e7b79f8331d7d845b4e8)

Running job 2 based on command line options.

Attempting to increase maximum allowed processes and open files.
./scripts/1-bucketize.sh: 1: ulimit: Illegal option -u
./scripts/1-bucketize.sh: 1: ulimit: Illegal option -u
./scripts/1-bucketize.sh: 72: ulimit: Illegal option -u
./scripts/1-bucketize.sh: 1: ulimit: Illegal option -u
  Changed max processes per user from  to  (max ).
  Changed max open files from 1024 to 1048576 (max 1048576).

Overwriting incomplete result from presumed crashed job in directory './new1.ovlStore.BUILDING/create0002'.

Opened '../new1.seqStore' with 1925218 reads.

Constructing slice 2 for store './new1.ovlStore.BUILDING'.
 - Filtering overlaps over 1.0000 fraction error.

Bucketizing input    1 out of   70 - '1-overlapper/001/000002.ovb'
Bucketizing input    2 out of   70 - '1-overlapper/001/000004.ovb'
Bucketizing input    3 out of   70 - '1-overlapper/001/000006.ovb'
Bucketizing input    4 out of   70 - '1-overlapper/001/000008.ovb'
Bucketizing input    5 out of   70 - '1-overlapper/001/000010.ovb'
Bucketizing input    6 out of   70 - '1-overlapper/001/000012.ovb'
Bucketizing input    7 out of   70 - '1-overlapper/001/000014.ovb'
Bucketizing input    8 out of   70 - '1-overlapper/001/000016.ovb'
Bucketizing input    9 out of   70 - '1-overlapper/001/000018.ovb'
Bucketizing input   10 out of   70 - '1-overlapper/001/000020.ovb'
Bucketizing input   11 out of   70 - '1-overlapper/001/000022.ovb'
Bucketizing input   12 out of   70 - '1-overlapper/001/000024.ovb'
Bucketizing input   13 out of   70 - '1-overlapper/001/000026.ovb'
Bucketizing input   14 out of   70 - '1-overlapper/001/000028.ovb'
Bucketizing input   15 out of   70 - '1-overlapper/001/000030.ovb'
Bucketizing input   16 out of   70 - '1-overlapper/001/000032.ovb'
Bucketizing input   17 out of   70 - '1-overlapper/001/000034.ovb'
Bucketizing input   18 out of   70 - '1-overlapper/001/000036.ovb'
Bucketizing input   19 out of   70 - '1-overlapper/001/000038.ovb'
Bucketizing input   20 out of   70 - '1-overlapper/001/000040.ovb'
Bucketizing input   21 out of   70 - '1-overlapper/001/000042.ovb'
Bucketizing input   22 out of   70 - '1-overlapper/001/000044.ovb'
Bucketizing input   23 out of   70 - '1-overlapper/001/000046.ovb'
Bucketizing input   24 out of   70 - '1-overlapper/001/000048.ovb'
Bucketizing input   25 out of   70 - '1-overlapper/001/000049.ovb'
Bucketizing input   26 out of   70 - '1-overlapper/001/000052.ovb'
Bucketizing input   27 out of   70 - '1-overlapper/001/000053.ovb'
Bucketizing input   28 out of   70 - '1-overlapper/001/000056.ovb'
Bucketizing input   29 out of   70 - '1-overlapper/001/000057.ovb'
Bucketizing input   30 out of   70 - '1-overlapper/001/000060.ovb'
Bucketizing input   31 out of   70 - '1-overlapper/001/000061.ovb'
Bucketizing input   32 out of   70 - '1-overlapper/001/000064.ovb'
Bucketizing input   33 out of   70 - '1-overlapper/001/000065.ovb'
Bucketizing input   34 out of   70 - '1-overlapper/001/000068.ovb'
Bucketizing input   35 out of   70 - '1-overlapper/001/000069.ovb'
Bucketizing input   36 out of   70 - '1-overlapper/001/000072.ovb'
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Failed with 'Aborted'; backtrace (libbacktrace):
utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
utility/arrays.H::106 in _Z12setArraySizeIcmEvRPT_mRT0_mj()
utility/arrays.H::145 in _Z11resizeArrayIcmEvRPT_mRT0_mj()
stores/ovStoreFile.C::376 in _ZN6ovFile10readBufferEv()
stores/ovStoreFile.C::402 in _ZN6ovFile11readOverlapEP9ovOverlap()
stores/ovStoreBucketizer.C::238 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
Aborted (core dumped)

**Comment by skoren** [comment]
Yes, this looks like some of your overlap files are corrupt. Did you run out of space during this run at any point?

The best way to proceed is to remove/rerun the corrupt files and try to see if bucketizing fails. In the above log, the bad files are 000072.ovb and 000075.ovb. The steps you want to follow are:
```
cd 1-overlapper/
rm 001/000072.*
rm 001/000075.*
sh overlap.sh 72
sh overlap.sh 75
cd ../asm.ovlStore.BUILDING
sh scripts/1-bucketize.sh 1
sh scripts/1-bucketize.sh 2
```

This may work or fail again if more than 2 files are bad. You want to repeat the above steps until you find all the bad files and are able to build the buckets.

**Comment by fsq9451** [comment]
Thanks @skoren !

I will do what you suggested :D

**Comment by fsq9451** [comment]
Hi @skoren ,

Sorry to bother again... I run a sh script as your suggestion. But I met a problem with:

tail -50 nohup.out

Bucketizing input    2 out of   70 - '1-overlapper/001/000004.ovb'
Bucketizing input    3 out of   70 - '1-overlapper/001/000006.ovb'
Bucketizing input    4 out of   70 - '1-overlapper/001/000008.ovb'
Bucketizing input    5 out of   70 - '1-overlapper/001/000010.ovb'
Bucketizing input    6 out of   70 - '1-overlapper/001/000012.ovb'
Bucketizing input    7 out of   70 - '1-overlapper/001/000014.ovb'
Bucketizing input    8 out of   70 - '1-overlapper/001/000016.ovb'
Bucketizing input    9 out of   70 - '1-overlapper/001/000018.ovb'
Bucketizing input   10 out of   70 - '1-overlapper/001/000020.ovb'
Bucketizing input   11 out of   70 - '1-overlapper/001/000022.ovb'
Bucketizing input   12 out of   70 - '1-overlapper/001/000024.ovb'
Bucketizing input   13 out of   70 - '1-overlapper/001/000026.ovb'
Bucketizing input   14 out of   70 - '1-overlapper/001/000028.ovb'
Bucketizing input   15 out of   70 - '1-overlapper/001/000030.ovb'
Bucketizing input   16 out of   70 - '1-overlapper/001/000032.ovb'
Bucketizing input   17 out of   70 - '1-overlapper/001/000034.ovb'
Bucketizing input   18 out of   70 - '1-overlapper/001/000036.ovb'
Bucketizing input   19 out of   70 - '1-overlapper/001/000038.ovb'
Bucketizing input   20 out of   70 - '1-overlapper/001/000040.ovb'
Bucketizing input   21 out of   70 - '1-overlapper/001/000042.ovb'
Bucketizing input   22 out of   70 - '1-overlapper/001/000044.ovb'
Bucketizing input   23 out of   70 - '1-overlapper/001/000046.ovb'
Bucketizing input   24 out of   70 - '1-overlapper/001/000048.ovb'
Bucketizing input   25 out of   70 - '1-overlapper/001/000049.ovb'
Bucketizing input   26 out of   70 - '1-overlapper/001/000052.ovb'
Bucketizing input   27 out of   70 - '1-overlapper/001/000053.ovb'
Bucketizing input   28 out of   70 - '1-overlapper/001/000056.ovb'
Bucketizing input   29 out of   70 - '1-overlapper/001/000057.ovb'
Bucketizing input   30 out of   70 - '1-overlapper/001/000060.ovb'
Bucketizing input   31 out of   70 - '1-overlapper/001/000061.ovb'
Bucketizing input   32 out of   70 - '1-overlapper/001/000064.ovb'
Bucketizing input   33 out of   70 - '1-overlapper/001/000065.ovb'
Bucketizing input   34 out of   70 - '1-overlapper/001/000068.ovb'
Bucketizing input   35 out of   70 - '1-overlapper/001/000069.ovb'
Bucketizing input   36 out of   70 - '1-overlapper/001/000072.ovb'
Bucketizing input   37 out of   70 - '1-overlapper/001/000073.ovb'
Overlap has IDs out of range (maxID 1925218), possibly corrupt input data.

Failed with 'Segmentation fault'; backtrace (libbacktrace):
utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
stores/sqStore.C::99 in _ZN7sqStore15sqStore_getReadEj()
stores/ovOverlap.H::245 in _ZNK9ovOverlap5a_endE14sqRead_version()
stores/ovOverlap.C::60 in _ZN9ovOverlap8toStringEPc20ovOverlapDisplayTypeb()
stores/ovStoreFilter.C::178 in _ZN13ovStoreFilter13filterOverlapER9ovOverlapS1_()
stores/ovStoreBucketizer.C::239 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
Segmentation fault (core dumped)


It seems wired compared to the previous time...

Thanks!

**Comment by skoren** [comment]
It's the same error as last time, the input file has invalid data. You need to repeat the process for overlap job 73 and potentially others as I said in my pervious comment until the bucketizing job is able to process all its input files.

**Comment by skoren** [comment]
Any updates on this?

**Comment by skoren** [comment]
Idle.
