### ISSUE TITLE
LSF settings error/warning

### ISSUE THREAD

**Issue by thierryjanssens** [marbl/canu#1346]
Hi,

in the output of canu the following message is appearing. We 
make use of an LSF grid engine with the following options gridOptions="-q bio -n 13 -o log.txt -e error.txt".

-- Detected LSF with 'bsub' binary in /opt/ibm/lsfsuite/lsf/10.1/linux2.6-glibc2.3-x86_64/bin/bsub.
Argument "-" isn't numeric in int at /data/BioGrid/Anaconda3-5.1.0/envs/nanopore_tools_env/libexec/bin/../lib/site_perl/canu/Grid_LSF.pm line 152, <F> line 16.
Argument "-" isn't numeric in int at /data/BioGrid/Anaconda3-5.1.0/envs/nanopore_tools_env/libexec/bin/../lib/site_perl/canu/Grid_LSF.pm line 152, <F> line 17.
Argument "-" isn't numeric in int at /data/BioGrid/Anaconda3-5.1.0/envs/nanopore_tools_env/libexec/bin/../lib/site_perl/canu/Grid_LSF.pm line 152, <F> line 18.
Argument "-" isn't numeric in int at /data/BioGrid/Anaconda3-5.1.0/envs/nanopore_tools_env/libexec/bin/../lib/site_perl/canu/Grid_LSF.pm line 152, <F> line 19.
Argument "-" isn't numeric in int at /data/BioGrid/Anaconda3-5.1.0/envs/nanopore_tools_env/libexec/bin/../lib/site_perl/canu/Grid_LSF.pm line 152, <F> line 20.

Can I ignore this?

kind regards,

Thierry

**Comment by brianwalenz** [comment]
This is attempting to figure out what resources are available on your grid.  Can you paste in the output of `lshosts`?  This command is, I suspect, reporting five hosts with "-" for memory.

**Comment by thierryjanssens** [comment]
HOST_NAME      type    model  cpuf ncpus maxmem maxswp server RESOURCES
hosta  X86_64 Intel_EM  60.0     2  11.9G   3.8G    Yes (mg)
hostv   NTX64 Intel_EM  60.0    26 292.9G     4G    Yes ()
hostv   NTX64 Intel_EM  60.0    26 292.9G     4G    Yes ()
hostv    NTX64 Intel_EM  60.0    26 292.9G     4G    Yes ()
hostv    NTX64 Intel_EM  60.0    26 292.9G     4G    Yes ()
hostv   X86_64 Intel_EM  60.0    13 159.9G   3.8G    Yes ()
hostv  X86_64 Intel_EM  60.0    13 159.9G   3.8G    Yes ()
hostv   X86_64 Intel_EM  60.0    13 159.9G   3.8G    Yes ()
hostv   X86_64 Intel_EM  60.0    13 159.9G   3.8G    Yes ()
hostv   X86_64 Intel_EM  60.0    13 159.9G   3.8G    Yes ()
hostv   X86_64 Intel_EM  60.0    13 159.9G   3.8G    Yes ()
hostv   X86_64 Intel_EM  60.0    13 159.9G   3.8G    Yes ()
hostv   X86_64 Intel_EM  60.0    13 159.9G   3.8G    Yes ()
hostv   X86_64 Intel_EM  60.0    13 159.9G   3.8G    Yes ()
hostl   NTX64 Intel_EM  60.0     -      -      -     No (windows)
hostn  X86_64 Intel_EM  60.0     -      -      -     No (linux)
hostn  X86_64 Intel_EM  60.0     -      -      -     No (linux)
hostn  X86_64 Intel_EM  60.0     -      -      -     No (linux)
hostn  X86_64 Intel_EM  60.0     -      -      -     No (linux)

**Comment by thierryjanssens** [comment]
Should I just ignore it?

**Comment by brianwalenz** [comment]
I'm reasonably sure it can be ignored.  I'll get a patch in to prevent it.  Thanks for the output.
