### ISSUE TITLE
Problem with 'make' canu

### ISSUE THREAD

**Issue by limnoperna** [marbl/canu#1347]
Hello,
I try to install canu on the Bio-Linux 8.0.7 using virtual box in Windows 10.
The problem occurred when 'make -j 4'.
There were many warning and error messages.
How to fix these problems?

For example,
g++ -o /home/manager/canu/Linux-amd64/obj/bin/meryl/meryl/meryl.o -c -MD -g3 -O4 -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer -Wall -Wextra -Wformat -Wno-write-strings -Wno-char-subscripts -Wno-sign-compare -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-deprecated-declarations -D_GLIBCXX_PARALLEL -pthread -fopenmp -fPIC -DLIBBACKTRACE -DCANU -Imeryl -I/home/manager/canu/src -Iutility -Istores meryl/meryl.C
meryl/meryl.C:261:2: warning: #warning HARD CODED NUMBER OF FILES! [-Wcpp]
 #warning HARD CODED NUMBER OF FILES!

g++ -o /home/manager/canu/Linux-amd64/obj/bin/meryl/meryl/merylOp-nextMer.o -c -MD -g3 -O4 -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer -Wall -Wextra -Wformat -Wno-write-strings -Wno-char-subscripts -Wno-sign-compare -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-deprecated-declarations -D_GLIBCXX_PARALLEL -pthread -fopenmp -fPIC -DLIBBACKTRACE -DCANU -Imeryl -I/home/manager/canu/src -Iutility -Istores meryl/merylOp-nextMer.C
meryl/merylOp-nextMer.C:98:2: warning: #warning "need to decide whic direction we're going?" [-Wcpp]
 #warning "need to decide whic direction we're going?"
  ^
meryl/merylOp-nextMer.C:116:2: warning: #warning "rounding issues in word-frequency!" [-Wcpp]
 #warning "rounding issues in word-frequency!"

g++ -o /home/manager/canu/Linux-amd64/obj/bin/overlapConvert/overlapInCore/overlapConvert.o -c -MD -g3 -O4 -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer -Wall -Wextra -Wformat -Wno-write-strings -Wno-char-subscripts -Wno-sign-compare -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-deprecated-declarations -D_GLIBCXX_PARALLEL -pthread -fopenmp -fPIC -DLIBBACKTRACE -I/home/manager/canu/src -Iutility -Istores -IoverlapInCore/liboverlap overlapInCore/overlapConvert.C
g++ -o /home/manager/canu/Linux-amd64/obj/bin/overlapImport/overlapInCore/overlapImport.o -c -MD -g3 -O4 -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer -Wall -Wextra -Wformat -Wno-write-strings -Wno-char-subscripts -Wno-sign-compare -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-deprecated-declarations -D_GLIBCXX_PARALLEL -pthread -fopenmp -fPIC -DLIBBACKTRACE -I/home/manager/canu/src -Iutility -Istores -IoverlapInCore/liboverlap overlapInCore/overlapImport.C
overlapInCore/overlapImport.C: In function ‘int main(int, char**)’:
overlapInCore/overlapImport.C:274:31: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fgets(S, 1024, in->file());
                               ^
overlapInCore/overlapImport.C:304:33: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
       fgets(S, 1024, in->file());
                                 ^

g++ -o /home/manager/canu/Linux-amd64/obj/bin/splitReads/overlapBasedTrimming/splitReads.o -c -MD -g3 -O4 -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer -Wall -Wextra -Wformat -Wno-write-strings -Wno-char-subscripts -Wno-sign-compare -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-deprecated-declarations -D_GLIBCXX_PARALLEL -pthread -fopenmp -fPIC -DLIBBACKTRACE -I/home/manager/canu/src -Iutility -Istores overlapBasedTrimming/splitReads.C
overlapBasedTrimming/trimReads-quality.C: In function ‘void findGoodQuality(double*, uint32, char, uint32&, uint32&)’:
overlapBasedTrimming/trimReads-quality.C:156:12: warning: variable ‘winningFPos’ set but not used [-Wunused-but-set-variable]
   uint32   winningFPos  = 0;
            ^
overlapBasedTrimming/trimReads-quality.C:157:12: warning: variable ‘winningRPos’ set but not used [-Wunused-but-set-variable]
   uint32   winningRPos  = 0;
            ^
overlapBasedTrimming/trimReads-quality.C:158:12: warning: variable ‘winningStyle’ set but not used [-Wunused-but-set-variable]
   uint32   winningStyle = 0;

g++ -o /home/manager/canu/Linux-amd64/obj/bin/overlapAlign/overlapAlign/overlapAlign.o -c -MD -g3 -O4 -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer -Wall -Wextra -Wformat -Wno-write-strings -Wno-char-subscripts -Wno-sign-compare -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-deprecated-declarations -D_GLIBCXX_PARALLEL -pthread -fopenmp -fPIC -DLIBBACKTRACE -I/home/manager/canu/src -Iutility -Istores -IoverlapInCore/libedlib overlapAlign/overlapAlign.C
In file included from /usr/include/c++/4.8/tuple:35:0,
                 from overlapAlign/overlapAlign-computation.H:32,
                 from overlapAlign/overlapAlign.C:41:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from overlapAlign/overlapAlign.C:41:0:
overlapAlign/overlapAlign-computation.H:94:3: error: ‘tuple’ does not name a type
   tuple<int32, int32>  findMinThickestEdge(double coverage);
   ^
make: *** [/home/manager/canu/Linux-amd64/obj/bin/overlapAlign/overlapAlign/overlapAlign.o] Error 1
make: *** Waiting for unfinished jobs....

Thanks for your help.

Best regards,
Chihwei

**Comment by brianwalenz** [comment]
Two options:
1) Install a newer gcc.
2) Install Canu release v1.8.

What does `g++ --version` report?

**Comment by dbtara** [comment]
Thanks for this wonderful software that is the product of the whole teams hard work and I really appreciate your responsiveness to all the issues that we come across.

I have similar issues with compilation of this particular file. I can use the release 1.8 but the changes made since are numerous and I was hoping to build it. 
Two questions:
1. What version of gcc do you recommend to compile at source for this version. For other releases a min 4.8 with 6.x as recommended was indicated
2. Is there a timeline for release on 1.8.1

Thanks
Dhwani

**Comment by brianwalenz** [comment]
Looking at https://www.gnu.org/software/gcc, they're listing versions 7.4, 8.3 and 9.1 as supported (as of May 2019).  Personally, I'm using gcc7, occasionally gcc8.

We've not thought about a 1.8.1 release yet.  It'd be just bug fixes though, no new features.

The code that is failing is under heavy development at the moment, and not part of the Canu pipeline.  Editing `src/main.mk` to remove the line:
```
overlapAlign/overlapAlign.mk \
```
(currently line 202) will skip compilation of this module.

**Comment by dbtara** [comment]
Thank you.

This helps.

Dhwani

**Comment by dbtara** [comment]
that worked. Thank you.

Dhwani
