### ISSUE TITLE
assembly size is much smaller than expected

### ISSUE THREAD

**Issue by baoxingsong** [marbl/canu#1348]
Dear Canu developer,

I am using Canu to assembly a heterogeneities plant genome with an estimated genome size 2758M using 50Gb nanopore sequencing data. The assembled size is only 200MB, which is much smaller than estimated. I am also tried WTDBG2.2 and flye to assemble it, the assembly size is about 3Gb.

Here are the command and the Canu version I am using.

```
/home/bs674/software/src/canu/Linux-amd64/bin/canu -p r1 -d r1 -correct genomeSize=2758m overlapper=minimap -nanopore-raw ../reads.fastq usegrid=false
/home/bs674/software/src/canu/Linux-amd64/bin/canu -trim -p trim -d trim genomeSize=2758m overlapper=minimap stopOnLowCoverage=5 -nanopore-corrected r1/r1.correctedReads.fasta.gz usegrid=false
/home/bs674/software/src/canu/Linux-amd64/bin/canu -assemble -p assemble -d assemble genomeSize=2758m overlapper=minimap stopOnLowCoverage=5 -nanopore-corrected trim/trim.trimmedReads.fasta.gz usegrid=false
```

```
Canu snapshot v1.8 +208 changes (r9418 fc616eb8a1047b9561de058ccd398f550f3244ff)
```
I am using linux

I checked something in the trimming step and found those message. Not sure this is a reason.

```
ERROR: same orient duplicate overlaps for pair 852842 2351514
ERROR: same orient duplicate overlaps for pair 852842 2351657
ERROR: more overlaps than expected for pair 852842 2352133.
ERROR: more overlaps than expected for pair 852842 2352133.
ERROR: more overlaps than expected for pair 852842 2352133.
ERROR: same orient duplicate overlaps for pair 852842 2352162
ERROR: same orient duplicate overlaps for pair 852842 2352604
ERROR: same orient duplicate overlaps for pair 852842 2353370
ERROR: same orient duplicate overlaps for pair 852842 2354067
ERROR: same orient duplicate overlaps for pair 852842 2356701
```
Thank you,
Baoxing

**Comment by skoren** [comment]
If you have 50gb of data for a 2.7g genome you only have about 18x coverage which is below Canu's recommendation for 20x. You're also switching the overlapper for both correction and trimming to minimap, that is not the default nor at all recommended. I would guess you ended up with no reads to assemble. 

As a start, run with default parameters, the sensitivity for the default overlapper will automatically adjust to your lower coverage. You probably also want to increase the default error rate (```corMinCoverage=0 correctedErrorRate=0.14```).
