### ISSUE TITLE
Failed with exit code 1. (rc=256)

### ISSUE THREAD

**Issue by drs357** [marbl/canu#1351]
```
-- Finished on Mon May  6 16:18:17 2019 (lickety-split) with 12620.164 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

Disk space available:  12620.164 GB

Last 50 lines of the relevant log file (/athena/masonlab/scratch/projects/metagenomics/vartanian_lab_ms_study/analysis/c5012/trimming/c50.ovlStore.err):

Found no overlaps to sort.

canu failed with 'failed to create the overlap store'.
```

My input data was nanopore raw data, with no other paramaters than gnuplotTested=true useGrid=false as I am running it on a server that uses slurm and not a grid. When I look in the ovlStore.err file, it just says 'Found no overlaps to sort.' 

I am not sure where it went wrong.

**Comment by brianwalenz** [comment]
A good place to start figuring out what went wrong is to look in `c50.report`.  This will show read lengths and coverage and a kmer histogram.  Paste that in for suggestions.

**Comment by drs357** [comment]
Sorry I don't see that file, what folder would it be located in?

**Comment by skoren** [comment]
Idle, I would guess a mixed-version installation from Conda.
