### ISSUE TITLE
Memory usage configuration on LSF

### ISSUE THREAD

**Issue by RomainFeron** [marbl/canu#1353]
Hi,

I am trying to run Canu on a cluster with an LSF scheduler (IBM Platform LSF Standard 9.1.1.1, Jul 17 2013). I've ran into memory issues for the jobs, and I noticed that memory is specified only with "-M MEMORY" ([here](https://github.com/marbl/canu/blob/0a8f026e0a15b54fb3b2ce8b9c76e3cccf3142da/src/pipelines/canu/Grid_LSF.pm#L71)). However, to my understanding, this parameter only specifies a memory limit, while the syntax to reserve memory would be :
> -R "rusage[mem=XXX]"
where XXX is the memory to reserve (in MB on my cluster).

I think this is the reason why Canu is not running properly on my setup, did I miss something ?

Thanks !

**Comment by skoren** [comment]
I have not tried this but perhaps something like ```gridEngineMemoryOption="-M `expr MEMORY * 1000` -R 'rusage[mem=MEMORY]'"``` would work? Canu will replace all instances of MEMORY with the Mb value and then expr will hopefully evaluate right when the job is submitted?

**Comment by skoren** [comment]
I have not tried this but perhaps something like ```gridEngineMemoryOption="-M `expr MEMORY * 1000` -R 'rusage[mem=MEMORY]'"``` would work? Canu will replace all instances of MEMORY with the Mb value and then expr will hopefully evaluate right when the job is submitted?

**Comment by RomainFeron** [comment]
> I have not tried this but perhaps something like `` gridEngineMemoryOption="-M `expr MEMORY * 1000` -R 'rusage[mem=MEMORY]'" `` would work? Canu will replace all instances of MEMORY with the Mb value and then expr will hopefully evaluate right when the job is submitted?

This seems to be working ! I had to modify your command a bit, here is what did the trick in case someone runs into the same issue:

gridEngineMemoryOption="-M \\\`expr MEMORY \\* 1000 \\\` -R 'rusage[mem=MEMORY]'"

Thanks a lot for your help @skoren !!

**Comment by brianwalenz** [comment]
Four random comments:

(1)

Can you just set -M to something uselessly large (512 GB or so)?  If so, just hardcode that part, and let Canu fill in the -R value:
```
gridEngineMemoryUnits=m
gridEngineMemoryOption="-M 512gb -R 'rusage[mem=MEMORY]'"
```
(where `512gb` is whatever the correct uselessly large value should be)

(2)

I've seen some pages claim that -R sets both the reservation and limit.  (https://qa.rc.hms.harvard.edu/questions/66/how-do-i-specify-the-amount-of-memory-my-job-will-need)

(3)

Are you *sure* they're different units?  The two docs I'm looking at ([bsub -R](https://www.ibm.com/support/knowledgecenter/en/SSETD4_9.1.3/lsf_command_ref/bsub.__r.1.html) and [bsub](https://www.ibm.com/support/knowledgecenter/en/SSETD4_9.1.2/lsf_command_ref/bsub.1.html)) say they're both controlled by LSF_UNIT_FOR_LIMITS in lsf.conf.  I wouldn't be surprised if they are, given what silly configurations I've seen on other grids.

(4)

Another option, though somewhat ugly, is to make a simple wrapper script for bsub that would parse the `rusage[mem=N]` line and add `-M N*1000`.  Place the wrapper in the same directory as 'canu', and set `gridEngineSubmitCommand` to that.

Actually, no need to even parse `rusage`, just make your own option to the wrapper to take the memory in whatever unit you want, and run `bsub` with a properly formed `-M (MEMORY * 1000) -R 'rusage[mem=MEMORY]`.

**Comment by brianwalenz** [comment]
It appears timestamps are all screwed up in this issue and the comments aren't in order.

**Comment by RomainFeron** [comment]
I agree, it's rather inconvenient for us users, but it seems to be the default setup for LSF. I think both -M and -R are needed, -M specifies the memory limit to kill the job and -R reserves the memory. If either is not setup, the jobs die with some form of "out of memory" error.

As "LSF_UNIT_FOR_LIMITS" was not setup in lsf.conf, the memory unit should be inferred from `lshosts`, which is in Mb instead of Kb. I think the only way to make it work would be to somehow be able to specify `gridEngineMemoryOption="-M (MEMORY * 1000) -R 'rusage[mem=MEMORY]'"`, but it's likely not possible. I don't see another way around it.

**Comment by RomainFeron** [comment]
Yes the timestamps were messed up yesterday. Thank you for the suggestions anyway ! I'll still answer your points in case someone stumble on this issue in the future.

1) I think this would work, it's less elegant than the previous solution but it's easier to implement

2) For me this did not work, the jobs got killed if I did not set -M, it might be config-dependent.

3) LSF_UNITS_FOR_LIMITS was not set on the cluster I'm working on, sadly, so default units are used (kb for -M and Mb for -R)
 
4) This is a similar idea to the previous solution, maybe a bit harder to implement, but it would work too.
