### ISSUE TITLE
correction/1-overlapper/results/000115.ovb FAILED in a CANU assembly 

### ISSUE THREAD

**Issue by biowackysci** [marbl/canu#1357]
**Remove this text before submitting your issue!**
The CANU command I used for assembly is 
canu -p canu -d /group/home/vici86y/canu-1.8 genomeSize=2.8g -fast maxThreads=16 useGrid=false stopOnReadQuality=false corOutCoverage=1000 minOverlapLength=1000 -nanopore-raw /group/pasture/Saila/all_oxford_reads.fastq -pacbio-raw /group/pasture/Saila/all_Pacbio.fastq

 the output of `canu -1.8` is 

Found perl:
   /usr/bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /usr/local/EasyBuild/software/Java/1.8.0_172/bin/java
   java version "1.8.0_172"

Found canu:
   /usr/local/EasyBuild/software/canu/1.8-intel-2018a/bin/canu
   Canu 1.8

Running job 115 based on command line options.
Fetch blocks/000035.dat
Fetch blocks/000036.dat
Fetch blocks/000037.dat
Fetch blocks/000038.dat
Fetch blocks/000039.dat
Fetch blocks/000040.dat
Fetch blocks/000041.dat
Fetch blocks/000042.dat
Fetch blocks/000043.dat
Fetch blocks/000044.dat
Fetch blocks/000045.dat
Fetch blocks/000046.dat
Fetch blocks/000047.dat
Fetch blocks/000048.dat
Fetch blocks/000049.dat

Running block 000034 in query 000115

mhapConvert: mhap/mhapConvert.C:116: int main(int, char **): Assertion `W[4][0] == '0'' failed.
./mhap.sh: line 1061: 384019 Aborted                 (core dumped) $bin/mhapConvert -S ../../canu.seqStore -o ./results/$qry.mhap.ovb.WORKING ./results/$qry.mhap

I run this on a cluster.

Also, another question is, if I want to include the haplotyping what do I need to include in my command?

Thanks for your help 
SV

**Comment by skoren** [comment]
Is this a different assembly than your previous issue (#1291). It looks like the same file system corruption error and the same solution as there applies. Did you try the solution there?

I'm not sure what you mean by "haplotyping". The FAQ includes suggested parameters for heterozygous genomes. However, there will still be haplotype switches in the assembly. PacBio data is not long enough to generate chromosome-scale phase blocks.

**Comment by biowackysci** [comment]
Thanks for the reply, last time i removed the  *.mhap and *.WORKING files and re started the run and this is what happened now. Do I go ahead and remove those files again and run them?

**Comment by skoren** [comment]
Yes but if it keeps happening after removing files then something else may be going on. Are you running out of disk space or disk quota? Run the failing jobs by hand and see what message they give.

**Comment by biowackysci** [comment]
I have alloted 500g of memory. So, i guess that should not be an issue. When i ran the job, this is what i found
[vici86y@dev1 1-overlapper]$ sh mhap.sh 000115

Found perl:
   /usr/bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /usr/local/EasyBuild/software/Java/1.8.0_172/bin/java
   java version "1.8.0_172"

Found canu:
   /usr/local/EasyBuild/software/canu/1.8-intel-2018a/bin/canu
   Canu 1.8

Running job 115 based on command line options.
Fetch blocks/000035.dat
Fetch blocks/000036.dat
Fetch blocks/000037.dat
Fetch blocks/000038.dat
Fetch blocks/000039.dat
Fetch blocks/000040.dat
Fetch blocks/000041.dat
Fetch blocks/000042.dat
Fetch blocks/000043.dat
Fetch blocks/000044.dat
Fetch blocks/000045.dat
Fetch blocks/000046.dat
Fetch blocks/000047.dat
Fetch blocks/000048.dat
Fetch blocks/000049.dat

Running block 000034 in query 000115

mhapConvert: mhap/mhapConvert.C:116: int main(int, char **): Assertion `W[4][0] == '0'' failed.
mhap.sh: line 1061: 126729 Aborted                 (core dumped) $bin/mhapConvert -S ../../canu.seqStore -o ./results/$qry.mhap.ovb.WORKING ./results/$qry.mhap


Thanks 
Saila

**Comment by skoren** [comment]
You still need to remove the existing mhap and WORKING files before re-running the job.

**Comment by biowackysci** [comment]
Alright I will do it and upload the output. Thanks SV

**Comment by biowackysci** [comment]
Hello,
This is what i got when i ran the job 
[vici86y@dev1 1-overlapper]$ sh mhap.sh 000115

Found perl:
   /usr/bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /usr/local/EasyBuild/software/Java/1.8.0_172/bin/java
   java version "1.8.0_172"

Found canu:
   /usr/local/EasyBuild/software/canu/1.8-intel-2018a/bin/canu
   Canu 1.8

Running job 115 based on command line options.
Fetch blocks/000035.dat
Fetch blocks/000036.dat
Fetch blocks/000037.dat
Fetch blocks/000038.dat
Fetch blocks/000039.dat
Fetch blocks/000040.dat
Fetch blocks/000041.dat
Fetch blocks/000042.dat
Fetch blocks/000043.dat
Fetch blocks/000044.dat
Fetch blocks/000045.dat
Fetch blocks/000046.dat
Fetch blocks/000047.dat
Fetch blocks/000048.dat
Fetch blocks/000049.dat

Running block 000034 in query 000115

Running with these settings:
--filter-threshold = 1.0E-7
--help = false
--max-shift = 0.2
--min-olap-length = 1000
--min-store-length = 0
--no-rc = false
--no-self = false
--no-tf = false
--num-hashes = 768
--num-min-matches = 2
--num-threads = 16
--ordered-kmer-size = 12
--ordered-sketch-size = 1536
--repeat-idf-scale = 10.0
--repeat-weight = 0.9
--settings = 0
--store-full-id = true
--supress-noise = 0
--threshold = 0.78
--version = false
-f =
-h = false
-k = 16
-p =
-q = queries/000115
-s = ./blocks/000034.dat

Processing files for storage in reverse index...
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
Current # sequences loaded and processed from file: 40000...
Current # sequences loaded and processed from file: 45000...
Current # sequences loaded and processed from file: 50000...
Current # sequences loaded and processed from file: 55000...
Current # sequences loaded and processed from file: 60000...
Current # sequences loaded and processed from file: 65000...
Current # sequences loaded and processed from file: 70000...
Current # sequences loaded and processed from file: 75000...
Current # sequences loaded and processed from file: 80000...
Current # sequences loaded and processed from file: 85000...
Current # sequences loaded and processed from file: 90000...
Current # sequences loaded and processed from file: 95000...
Current # sequences loaded and processed from file: 100000...
Current # sequences loaded and processed from file: 105000...
Current # sequences loaded and processed from file: 110000...
Current # sequences loaded and processed from file: 115000...
Current # sequences loaded and processed from file: 120000...
Current # sequences loaded and processed from file: 125000...
Current # sequences stored: 5000...
Current # sequences stored: 10000...
Current # sequences stored: 15000...
Current # sequences stored: 20000...
Current # sequences stored: 25000...
Current # sequences stored: 30000...
Current # sequences stored: 35000...
Current # sequences stored: 40000...
Current # sequences stored: 45000...
Current # sequences stored: 50000...
Current # sequences stored: 55000...
Current # sequences stored: 60000...
Current # sequences stored: 65000...
Current # sequences stored: 70000...
Current # sequences stored: 75000...
Current # sequences stored: 80000...
Current # sequences stored: 85000...
Current # sequences stored: 90000...
Current # sequences stored: 95000...
Current # sequences stored: 100000...
Current # sequences stored: 105000...
Current # sequences stored: 110000...
Current # sequences stored: 115000...
Current # sequences stored: 120000...
Current # sequences stored: 125000...
Stored 129600 sequences in the index.
Processed 129600 unique sequences (fwd and rev).
Time (s) to read and hash from file: 28.030238720000003
Time (s) to score and output to self: 893.7975773400001
Opened fasta file /group/home/vici86y/canu-1.8/correction/1-overlapper/blocks/000035.dat.
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
Current # sequences loaded and processed from file: 40000...
Current # sequences loaded and processed from file: 45000...
Current # sequences loaded and processed from file: 50000...
Current # sequences loaded and processed from file: 55000...
Current # sequences loaded and processed from file: 60000...
Processed 64800 to sequences.
Time (s) to score, hash to-file, and output: 1735.8254697480002
Opened fasta file /group/home/vici86y/canu-1.8/correction/1-overlapper/blocks/000036.dat.
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
Current # sequences loaded and processed from file: 40000...
Current # sequences loaded and processed from file: 45000...
Current # sequences loaded and processed from file: 50000...
Current # sequences loaded and processed from file: 55000...
Current # sequences loaded and processed from file: 60000...
Processed 64800 to sequences.
Time (s) to score, hash to-file, and output: 1895.287075871
Opened fasta file /group/home/vici86y/canu-1.8/correction/1-overlapper/blocks/000037.dat.
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
Current # sequences loaded and processed from file: 40000...
Current # sequences loaded and processed from file: 45000...
Current # sequences loaded and processed from file: 50000...
Current # sequences loaded and processed from file: 55000...
Current # sequences loaded and processed from file: 60000...
Processed 64800 to sequences.
Time (s) to score, hash to-file, and output: 1903.4711485470002
Opened fasta file /group/home/vici86y/canu-1.8/correction/1-overlapper/blocks/000038.dat.
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
Current # sequences loaded and processed from file: 40000...
Current # sequences loaded and processed from file: 45000...
Current # sequences loaded and processed from file: 50000...
Current # sequences loaded and processed from file: 55000...
Current # sequences loaded and processed from file: 60000...
Processed 64800 to sequences.
Time (s) to score, hash to-file, and output: 1706.6867814640002
Opened fasta file /group/home/vici86y/canu-1.8/correction/1-overlapper/blocks/000039.dat.
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
Current # sequences loaded and processed from file: 40000...
Current # sequences loaded and processed from file: 45000...
Current # sequences loaded and processed from file: 50000...
Current # sequences loaded and processed from file: 55000...
Current # sequences loaded and processed from file: 60000...
Processed 64800 to sequences.
Time (s) to score, hash to-file, and output: 1659.524077063
Opened fasta file /group/home/vici86y/canu-1.8/correction/1-overlapper/blocks/000040.dat.
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
Current # sequences loaded and processed from file: 40000...
Current # sequences loaded and processed from file: 45000...
Current # sequences loaded and processed from file: 50000...
Current # sequences loaded and processed from file: 55000...
Current # sequences loaded and processed from file: 60000...
Processed 64800 to sequences.
Time (s) to score, hash to-file, and output: 1768.6790699980002
Opened fasta file /group/home/vici86y/canu-1.8/correction/1-overlapper/blocks/000041.dat.
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
Current # sequences loaded and processed from file: 40000...
Current # sequences loaded and processed from file: 45000...
Current # sequences loaded and processed from file: 50000...
Current # sequences loaded and processed from file: 55000...
Current # sequences loaded and processed from file: 60000...
Processed 64800 to sequences.
Time (s) to score, hash to-file, and output: 1532.295143044
Opened fasta file /group/home/vici86y/canu-1.8/correction/1-overlapper/blocks/000042.dat.
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
Current # sequences loaded and processed from file: 40000...
Current # sequences loaded and processed from file: 45000...
Current # sequences loaded and processed from file: 50000...
Current # sequences loaded and processed from file: 55000...
Current # sequences loaded and processed from file: 60000...
Processed 64800 to sequences.
Time (s) to score, hash to-file, and output: 1533.697253862
Opened fasta file /group/home/vici86y/canu-1.8/correction/1-overlapper/blocks/000043.dat.
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
Current # sequences loaded and processed from file: 40000...
Current # sequences loaded and processed from file: 45000...
Current # sequences loaded and processed from file: 50000...
Current # sequences loaded and processed from file: 55000...
Current # sequences loaded and processed from file: 60000...
Processed 64800 to sequences.
Time (s) to score, hash to-file, and output: 1448.814127628
Opened fasta file /group/home/vici86y/canu-1.8/correction/1-overlapper/blocks/000044.dat.
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
Current # sequences loaded and processed from file: 40000...
Current # sequences loaded and processed from file: 45000...
Current # sequences loaded and processed from file: 50000...
Current # sequences loaded and processed from file: 55000...
Current # sequences loaded and processed from file: 60000...
Processed 64800 to sequences.
Time (s) to score, hash to-file, and output: 1490.6134936560002
Opened fasta file /group/home/vici86y/canu-1.8/correction/1-overlapper/blocks/000045.dat.
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
Current # sequences loaded and processed from file: 40000...
Current # sequences loaded and processed from file: 45000...
Current # sequences loaded and processed from file: 50000...
Current # sequences loaded and processed from file: 55000...
Current # sequences loaded and processed from file: 60000...
Processed 64800 to sequences.
Time (s) to score, hash to-file, and output: 1372.9283165870002
Opened fasta file /group/home/vici86y/canu-1.8/correction/1-overlapper/blocks/000046.dat.
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
Current # sequences loaded and processed from file: 40000...
Current # sequences loaded and processed from file: 45000...
Current # sequences loaded and processed from file: 50000...
Current # sequences loaded and processed from file: 55000...
Current # sequences loaded and processed from file: 60000...
Processed 64800 to sequences.
Time (s) to score, hash to-file, and output: 1380.1963467320002
Opened fasta file /group/home/vici86y/canu-1.8/correction/1-overlapper/blocks/000047.dat.
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
Current # sequences loaded and processed from file: 40000...
Current # sequences loaded and processed from file: 45000...
Current # sequences loaded and processed from file: 50000...
Current # sequences loaded and processed from file: 55000...
Current # sequences loaded and processed from file: 60000...
Processed 64800 to sequences.
Time (s) to score, hash to-file, and output: 1395.585960394
Opened fasta file /group/home/vici86y/canu-1.8/correction/1-overlapper/blocks/000048.dat.
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
Current # sequences loaded and processed from file: 40000...
Current # sequences loaded and processed from file: 45000...
Current # sequences loaded and processed from file: 50000...
Current # sequences loaded and processed from file: 55000...
Current # sequences loaded and processed from file: 60000...
Processed 64800 to sequences.
Time (s) to score, hash to-file, and output: 1430.91678862
Opened fasta file /group/home/vici86y/canu-1.8/correction/1-overlapper/blocks/000049.dat.
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
Current # sequences loaded and processed from file: 40000...
Current # sequences loaded and processed from file: 45000...
Current # sequences loaded and processed from file: 50000...
Current # sequences loaded and processed from file: 55000...
Current # sequences loaded and processed from file: 60000...
Processed 64800 to sequences.
Time (s) to score, hash to-file, and output: 1335.824445342
Total scoring time (s): 24484.195397409003
Total time (s): 24512.225752102
MinHash search time (s): 3908.1800298810003
Total matches found: 1447844865
Average number of matches per lookup: 1396.4553096064815
Average number of table elements processed per lookup: 17672.379774305555
Average number of table elements processed per match: 12.655170310667227
Average % of hashed sequences hit per lookup: 4.813672166733348
Average % of hashed sequences hit that are matches: 22.384403749272867
Average % of hashed sequences fully compared that are matches: 54.83509337318048

Thanks
SV

**Comment by skoren** [comment]
That means the job finished successfully, do you have files  named ```*115*``` in the correction/1-overlapper/results folder? You can try manually running the jobs that failed and see if they all succeed. Did you check that you are not running out of disk quota during your run?

**Comment by biowackysci** [comment]
Yes, I checked for space. I have allocated 500g for this job. Also, in the results folder I have 000115.ovb and 000115.oc. Do I run both of them?

**Comment by biowackysci** [comment]
I have restarted the jobs again. Let me see what happens

**Comment by skoren** [comment]
I would not restart the jobs (unless 115 was the only failing jobs). Instead, run each failed job one at a time after removing the intermediate files like you did for 115. That way you'll hopefully get the real error rather than the error after the failed re-try.

I assume when you say 500g you mean memory, I mean disk space. 500g of disk space is going to likely be an issue for a human-sized genome

**Comment by biowackysci** [comment]
Hello, I checked for disk space and looks like there was an issue with that too. So i have restarted the jobs after sorting out the space. Will update as it goes. Thanks so much. Hope CANU works for me this time.

**Comment by biowackysci** [comment]
Hello Again, 
We have a question with setting the mem per cpu to 300g when running on a Slurm grid
I used 
canu -p canu -d /group/pasture/Saila/CANU_CARL/CANU_Grid-options2/Assembly genomeSize=2.8g useGrid=true  stopOnReadQuality=false  minOverlapLength=1000 -nanopore-raw /group/pasture/Saila/all_oxford_reads.fastq -pacbio-raw /group/pasture/Saila/all_Pacbio.fastq gridEngine=slurm gridOptions="--account=dbiopast1 --partition=batch --time=1000:00:00 --mem-per-cpu=300g"

but for some reason when it kickstarts it shows 4g to be the default memory like below 
sbatch \
      --mem-per-cpu=4g \
      --cpus-per-task=1 \
      --account=dbiopast1 \
      --partition=batch \
      --time=1000:00:00 \
      --mem-per-cpu=300g  \
      -D `pwd` \
      -J 'canu_canu_correction' \
      -o canu-scripts/canu.01.out  canu-scripts/canu.01.sh

is there a way i could control the memory as my job failed due memory again.

Thanks heaps for your input 
Saila

**Comment by skoren** [comment]
If you look at your command you can see it is including the full request (```--account=dbiopast1  --partition=batch  --time=1000:00:00  --mem-per-cpu=300g```) so it is requesting 300g per core.

**Comment by biowackysci** [comment]
Thanks for that i have decreased the mem-per-cpu to 100g.. Its running at the moment and not crashed yet. So fingers crossed.
Thanks for your thoughts 
Saila

**Comment by biowackysci** [comment]
Thanks for this.I stopped running the assembly job and started just a correction job alone and its done. So now I have issues with the trimming and assembly. I will start a new thread with those queries.
Thanks for your help though
