### ISSUE TITLE
Error during running ovStoreBucketizer

### ISSUE THREAD

**Issue by rozaimirazali** [marbl/canu#1359]
canu-logs shows:

> Command:
> /gpfs/software/pathology/canu/canu-1.7.1/Linux-amd64/bin/ovStoreBucketizer \
>   -O . \
>   -G ../MNDY0206.gkpStore \
>   -C ./config \
>   -job 250 \
>   -i ../1-overlapper/results/000250.ovb

in the correction/MNDY0206.ovlStore.BUILDING/MNDY0206.e file,the last few lines show:

> ../MNDY0206.gkpStore -C ./config -job $jobid -i $jn
> ./scripts/1-bucketize.sh: line 346: 31507 Killed                  $bin/ovStoreBucketizer -O . -G ../MNDY0206.gkpStore -C ./config -job $jobid -i $jn
> ./scripts/1-bucketize.sh: line 346: 12316 Killed                  $bin/ovStoreBucketizer -O . -G ../MNDY0206.gkpStore -C ./config -job $jobid -i $jn
> ./scripts/1-bucketize.sh: line 346: 23769 Killed                  $bin/ovStoreBucketizer -O . -G ../MNDY0206.gkpStore -C ./config -job $jobid -i $jn
> ./scripts/1-bucketize.sh: line 346:  4952 Killed                  $bin/ovStoreBucketizer -O . -G ../MNDY0206.gkpStore -C ./config -job $jobid -i $jn

I tried to investigate this error and found a pattern. For jobs where .ovb is small (<11GB), it will use memory below 3 GB but for larger file (>11GB) it seems to need more than 3GB. The file size for the .ovb files ranges from 400MB to 200GB

The problem is CANU seems to limit the LSF MEMLIMIT for each job to 3GB. So when a job requires higher memory than 3GB, it will get killed by LSF.

When I look at the 1-bucketsize.sh inside correction/MNDY0206.ovlStore.BUILDING/scripts/ he $max is referring to maximum allowed processes. 

1. How can i change this 3GB max memory limit?
2. What number should I set it to? Ideally, CANU should set it automatically and I assume this is what it is doing

**Comment by rozaimirazali** [comment]
Just saw something in correction/MNDY0206.ovlStore.BUILDING/config.err

> Attempting to increase maximum allowed processes and open files.
> ./MNDY0206.ovlStore.BUILDING/scripts/0-config.sh: line 20: [: unlimited: integer expression expected
>   Max processes per user limited to unlimited, no increase possible.
>   Max open files limited to 1000000, no increase possible.
> 
> Found 1093840474230 (1093840.47 million) overlaps.
> Configuring for 4.00 GB to 32.00 GB memory and 999984 open files.
> Will sort using 8694 files; 125829120 (125.83 million) overlaps per bucket; 4.00 GB memory per bucket

The last couple of lines:

> Will sort 126.164 million overlaps per bucket, using 8648 buckets 4.01 GB per bucket.
> 
> -  Saved configuration to './MNDY0206.ovlStore.BUILDING/config'.

I know that in CANU, i can set the ‘maxMemory’ but I doubt changing this would solve the issue because in the previous few steps before this, there were jobs using huge amount of memory without any problem

**Comment by rozaimirazali** [comment]
So the ovb stage is pre-defined to use use 3GB and 1 core.

> -- Grid:  meryl    256 GB   32 CPUs  (k-mer counting)
> -- Grid:  cormhap   48 GB   16 CPUs  (overlap detection with mhap)
> -- Grid:  obtovl    24 GB   16 CPUs  (overlap detection)
> -- Grid:  utgovl    24 GB   16 CPUs  (overlap detection)
> -- Grid:  cor       12 GB    4 CPUs  (read correction)
> -- Grid:  ovb        3 GB    1 CPU   (overlap store bucketizer)
> -- Grid:  ovs       32 GB    1 CPU   (overlap store sorting)
> -- Grid:  red       15 GB    4 CPUs  (read error detection)
> -- Grid:  oea        8 GB    1 CPU   (overlap error adjustment)
> -- Grid:  bat      512 GB   32 CPUs  (contig construction)
> -- Grid:  gfa       32 GB   32 CPUs  (GFA alignment and processing)

Defining ovlMemory to anything bigger than 3GB should fix the issue, right? Do I have to do trial and error until all the ovl jobs completed successfully? Any good rule of thumb?

**Comment by brianwalenz** [comment]
I suspect it's the small sort memory size it picked.  Try restarting with `ovsMemory=16g`, or even `32g`.  Remove all the `ovlStore` files and directories before restarting.

You can test this manually by changing the memory size in `scripts/0-config.sh`, running that script, then looking in the same `config.err`.  Note that it needs to be run from within `MNDY0206.ovlStore.BUILDING`:
```
% cd MNDY0206.ovlStore.BUILDING
% sh scripts/0-config.sh
```
The critical line is
```
Will sort 126.164 million overlaps per bucket, using 8648 buckets 4.01 GB per bucket
```
8648 is just way too many buckets.

You've also got a **LOT** of overlaps.  Are you using all default parameters for Canu?

**Comment by rozaimirazali** [comment]
> I suspect it's the small sort memory size it picked. Try restarting with `ovsMemory=16g`, or even `32g`. Remove all the `ovlStore` files and directories before restarting.
> 
> You can test this manually by changing the memory size in `scripts/0-config.sh`, running that script, then looking in the same `config.err`. Note that it needs to be run from within `MNDY0206.ovlStore.BUILDING`:
> 
> ```
> % cd MNDY0206.ovlStore.BUILDING
> % sh scripts/0-config.sh
> ```
> 
> The critical line is
> 
> ```
> Will sort 126.164 million overlaps per bucket, using 8648 buckets 4.01 GB per bucket
> ```
> 
> 8648 is just way too many buckets.
> 
> You've also got a **LOT** of overlaps. Are you using all default parameters for Canu?

Yes. except for corMemory and ovbMemory. This is my command:

> bsub -e bsuberr_ver2c -o bsubout_ver2c -q normal -P CANU -J correction_ver2c "canu -correct gnuplotTested=true -d dir.MNDY0206_ver2 -p MNDY0206 ovbMemory=32g corMemory=12g genomeSize=3g stopOnReadQuality=false useGrid=true gridEngine=lsf gridOptions='-e MNDY0206.e -o MNDY0206.o -q normal -P assembly -J denovo_ref_assembly' -pacbio-raw .....

**Comment by rozaimirazali** [comment]
putting ovbMemory=32g solved the issue
