### ISSUE TITLE
sh: fork: retry: Resource temporarily unavailable

### ISSUE THREAD

**Issue by tramaraj** [marbl/canu#136]
Hello - 

I am trying to assemble a 2.8 Gbps tetraploid legume genome that has 25X PacBio data.

Looks like it crashed when finishing the following command,

/sw/compbio/canu/canu/Linux-amd64/bin/ovStoreBuild

Here is a little section from the log file,

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    /home/projects/canu/denovo_pacbio_out/correction/1-overlapper/mhap.sh 166 > /home/projects/canu/denovo_pacbio_out/correction/1-overlapper/mhap.000166.out 2>&1

    -- Finished on Fri May 13 11:13:33 2016 (1141363 seconds) with 31301.7 GB free disk space
    ----------------------------------------
    -- Found 166 mhap overlap output files.
    ----------------------------------------
    -- Starting command on Fri May 13 11:13:48 2016 with 31300.7 GB free disk space

        /sw/compbio/canu/canu/Linux-amd64/bin/ovStoreBuild \
         -G /home/projects/canu/denovo_pacbio_out/correction/denovo_pacbio.gkpStore \
         -O /home/projects/canu/denovo_pacbio_out/correction/denovo_pacbio.ovlStore \
         -M 4-32 \
         -config /home/projects/canu/pacbio_out/correction/denovo_pacbio.ovlStore.BUILDING/config \
         -L /home/projects/canu/denovo_pacbio_out/correction/1-overlapper/ovljob.files \
        > /home/projects/canu/denovo_pacbio_out/correction/denovo_pacbio.ovlStore.BUILDING/config.err 2>&1

    -- Finished on Fri May 13 11:16:08 2016 (140 seconds) with 31295.9 GB free disk space
    ----------------------------------------
    -- overlap store bucketizer attempt 0 begins with 0 finished, and 166 to compute.
    ----------------------------------------
    -- Starting concurrent execution on Fri May 13 11:16:10 2016 with 31295.8 GB free disk space (166 processes; 64 concurrently)

        /home/projects/canu/denovo_pacbio_out/correction/denovo_pacbio.ovlStore.BUILDING/scripts/1-bucketize.sh 1 > /home/projects/canu/denovo_pacbio_out/correction/denovo_pacbio.ovlStore.BUILDING/logs/1-bucketize.000001.out 2>&1
    ........
    ........
    ........
        /home/projects/canu/denovo_pacbio_out/correction/denovo_pacbio.ovlStore.BUILDING/scripts/1-bucketize.sh 86 > /home/projects/canu/denovo_pacbio_out/correction/denovo_pacbio.ovlStore.BUILDING/logs/1-bucketize.000086.out 2>&1
    Can't fork: Resource temporarily unavailable
    sh: fork: retry: Resource temporarily unavailable
    sh: fork: retry: Resource temporarily unavailable

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 
Any suggestions on getting this problem resolved and continue from where it crashed would be greatly appreciated!

Thanks in advance for your time and help.

Thiru.

**Comment by skoren** [comment]
I think this is an issue with process limitations on the system (ulimit -Su). If you can increase the limit before Canu runs (in your login script), you should be able to re-run Canu and it will try again on the partitions which failed. This is the easiest.

Otherwise, you can remove the store (denovo_pacbio.ovlStore.BUILDING) and try increasing ovsMemory (```ovsMemory=4-128```) (decreasing 128 if you don't have that available on your systems, I wouldn't go over 128). Re-running Canu should make it use fewer partitions which should bypass the error as well.

**Comment by tramaraj** [comment]
Thanks, Sergey!

I will give it a try and let you know how it goes.

Thanks again very much.

Thiru.

**Comment by tramaraj** [comment]
Hi 

Here is the command I have right now,

canu \
 -p denovo_pacbio \
 -d denovo_pacbio_out \
 genomeSize=2.9g \
 ovsMemory=128 \
 maxThreads=64 \
 -pacbio-raw \
 /home/projects/raw_subreads.fastq

and I have deleted the denovo_pacbio.ovlStore.BUILDING/ folder.

If run the above command will it pick it up from where it left of or is it going to start from the beginning.

Just want to make sure before I resubmit it. Please let me know when you get a moment.

Thanks,
Thiru.

**Comment by brianwalenz** [comment]
It will pick up where it left off.

You can check that all the files mentioned in /home/projects/canu/denovo_pacbio_out/correction/1-overlapper/ovljob.files exist.  The first part of the store construction will fail if any of these don't exist, and it'll be easier to recreate them before starting.  They should all exist.

**Comment by tramaraj** [comment]
Great! Thanks Brian.

Seems to pickup where it left. It is running now. Will let you know  how it goes!

Thanks again very much for your help and support. Much appreciated.

Thiru.

**Comment by tramaraj** [comment]
Hello Again!

After using ovsMemory=128 parameter and deleting denovo_pacbio.ovlStore.BUILDING/ folder, it seemed to pick up from where it left of and was running fine. But this morning I did notice the following error messages,
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-- 54 overlap store bucketizer jobs failed:
--   job /home/projects/canu/denovo_pacbio_out/correction/denovo_pacbio.ovlStore.BUILDING/bucket0006 FAILED.
...
...
...
--   job /home/projects/canu/denovo_pacbio_out/correction/denovo_pacbio.ovlStore.BUILDING/bucket0159 FAILED.
--
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'failed to overlapStoreBucketize.  Made 2 attempts, jobs still failed'.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Should I still reduce the ovsMemory=128 parameter to maybe ovsMemory=100 and give it a try again.

Any suggestions on how to overcome this error will be gretaly appreciated!

Thank you.
Thiru.

**Comment by brianwalenz** [comment]
There should be a bunch of logging files in denovo_pacbio.ovlStore.BUILDING/logs/.  Pick one that failed and post it.  It'd be nice if you can compare a few to see if they look like similar problems.

Also post denovo_pacbio.ovlStore.BUILDING/config.err - this is the output of the ovStoreBuild command in your first comment above.

How big is the 1-overlapper/results directory?  This will be captured in the config.err (I think).

Finally, what version (canu -version) are you using?

**Comment by tramaraj** [comment]
Hi Brian -

Please find attached config.err file.

[config.err.txt](https://github.com/marbl/canu/files/269460/config.err.txt)

Looking through the .out files in denovo_pacbio.ovlStore.BUILDING/logs/ folder there are two types of error messages, please see below

===============================================================================
ERROR:  Failed to open output file '/home/projects/canu/denovo_pacbio_out/correction/denovo_pacbio.ovlStore.BUILDING/create0108/slice032.gz': Resource temporarily unavailable

ERROR:  Failed to open input file '/home/projects/canu/denovo_pacbio_out/correction/1-overlapper/results/000109.ovb.gz': Resource temporarily unavailable
===============================================================================

I am unable to look for the size of the 1-overlapper/results folder. It doesn't look huge when I do a ls -lh command on the folder.

Finally I am using version 1.0.

Any suggestions on resolving this will be greatly appreciated!

Thanks again,
Thiru.

**Comment by brianwalenz** [comment]
You're definitely running out of processes - an OS imposed limit.  This is a large store, but not enormous, so it can be built.

Version 1.0 is _very_ old, definitely update to the latest code from github.  Not just the latest release, actually do the 'clone' as there are changes to store building since the last release.  I think you'll be fine restarting with the newer code, however, if possible, make a copy of the current results before restarting.

You can check the limit on processes with 'ulimit -a'.  Then try to increase the limit with 'ulimit -Su' (the new code will do this for you).  If the limit is still low, less than a few thousand, consider asking sysadmins to increase the limit.

**Comment by tramaraj** [comment]
Hi Brian - 

Thanks for the note!

Here is what I get when I type ulimit -a

core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 8271405
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1024
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

I am currently in the process of getting upgraded to version 1.2 (https://github.com/marbl/canu/releases)

Will resubmit it with the newer version and let you know how it goes.

Thanks again very much for your time and help!

Thiru.

**Comment by brianwalenz** [comment]
I think we're going to have the 1.3 release out in a week.  It's running through our tests now.

**Comment by tramaraj** [comment]
Thanks, Brian!

Thiru.

**Comment by brianwalenz** [comment]
1.3 is finally out.

If you're still having trouble, the latest code has a slightly different algorithm for setting job sizes, and much more logging to help diagnose any problems.  I couldn't get this ready in time for the release.  You'll have to pull the latest code using git or the zip download.

**Comment by tramaraj** [comment]
Hi Brian - 

We have the most recent version (1.3) installed and ready to give it a try.

As per your suggestion I have made a copy of the current results we have before restarting with the newer version.

One question I had was regarding increasing the limit on the processors, you mentioned that the new code should do this for me. So I don't have to manually change anything upfront. Just restart with the new version. Am I right? I am unsure and if you could please clarify this that would be great.

Thank you.
Thiru.

**Comment by brianwalenz** [comment]
Yup, canu is nearly always safe to restart.  If you've upgraded from very old versions, it might try to recompute things, but shouldn't break later.

**Comment by achurcher** [comment]
Hi
I am having what appears to be the same problem as in the original post. We are trying to assemble a 1.2 GB genome with ~66x PacBio coverage and are using Canu version 1.3. We are running on a 512GB machine with 16 cores.

I have tried increasing the ovsMemory from 5-500 (ovsMemory=5-500) but the run still fails at the same place. I have pasted the tail end of the log file below and would be very happy to hear if you have any suggestions.

Thank you,
Allison

```
----------------------------------------
-- Found 243 mhap overlap output files.
----------------------------------------
-- Starting command on Mon Nov  7 18:49:13 2016 with 2864.2 GB free disk space

    /pica/sw/apps/bioinfo/canu/1.3/milou/Linux-amd64/bin/ovStoreBuild \
     -G /scratch/8987161/run1/canu_assm3/correction/warb_assm.gkpStore \
     -O /scratch/8987161/run1/canu_assm3/correction/warb_assm.ovlStore \
     -M 5-500 \
     -config /scratch/8987161/run1/canu_assm3/correction/warb_assm.ovlStore.BUILDING/config \
     -L /scratch/8987161/run1/canu_assm3/correction/1-overlapper/ovljob.files \
    > /scratch/8987161/run1/canu_assm3/correction/warb_assm.ovlStore.BUILDING/config.err 2>&1

----------------------------------------
-- overlap store bucketizer attempt 0 begins with 0 finished, and 243 to compute.
----------------------------------------
-- Starting concurrent execution on Mon Nov  7 18:49:24 2016 with 2864.2 GB free disk space (243 processes; 16 concurrently)

    /scratch/8987161/run1/canu_assm3/correction/warb_assm.ovlStore.BUILDING/scripts/1-bucketize.sh 1 > /scratch/8987161/run1/canu_assm3/correction/warb_assm.ovlStore.BUILDING/logs/1-bucketize.000001.out 2>&1
. . . . . . 
bucketize.000015.out 2>&1
    /scratch/8987161/run1/canu_assm3/correction/warb_assm.ovlStore.BUILDING/scripts/1-bucketize.sh 16 > /scratch/8987161/run1/canu_assm3/correction/warb_assm.ovlStore.BUILDING/logs/1-bucketize.000016.out 2>&1
    /scratch/8987161/run1/canu_assm3/correction/warb_assm.ovlStore.BUILDING/scripts/1-bucketize.sh 17 > /scratch/8987161/run1/canu_assm3/correction/warb_assm.ovlStore.BUILDING/logs/1-bucketize.000017.out 2>&1
Can't fork: Resource temporarily unavailable
/var/spool/slurmd/job8987161/slurm_script: fork: retry: Resource temporarily unavailable
/var/spool/slurmd/job8987161/slurm_script: fork: retry: Resource temporarily unavailable
/var/spool/slurmd/job8987161/slurm_script: fork: retry: Resource temporarily unavailable
/var/spool/slurmd/job8987161/slurm_script: fork: retry: Resource temporarily unavailable
/var/spool/slurmd/job8987161/slurm_script: fork: Resource temporarily unavailable

```
