### ISSUE TITLE
Missing contig file in canu/1.6

### ISSUE THREAD

**Issue by ArnieBerg** [marbl/canu#1366]
I can successfully run Canu 1.8 on a Ubuntu 18 platform and it generates contigs in files with the extension .contigs.fasta.  However, when I run the same command in a HPC Grid (Linux) environment running Canu 1.6, the contig file is not generated, even though all three Canu steps run successfully.  What am I missing?  Does Canu 1.6 behave differently in this instance?  If so, where do I find the equivalent of the contig file?

The Canu command that I run is:
canu -p BRD2017_0001 -d data/BRD2017/BRD2017_GridION/BRD2017_0001/uploaded/ useGrid=true genomeSize=4m -nanopore-raw data/BRD2017/BRD2017_GridION/BRD2017_0001/uploaded/BRD2017_0001.fastq

**Comment by skoren** [comment]
I believe 1.6 still has the contigs.fasta file though I wouldn't suggest a version that's >2 years old. On a grid environment, canu will submit itself to the scheduler and exit. So your initial command will quit before anything runs. As long as you have jobs scheduled, Canu is still running. The current state is captured in canu.out in the top-level folder.
