### ISSUE TITLE
Illegal division by zero at /home/hpc/crlee/miniconda/envs/nanopore/libexec/lib/canu/CorrectReads.pm line 427.

### ISSUE THREAD

**Issue by JesChen** [marbl/canu#1369]
Hi, 
I've read #627 and #638, but I'm still confused.
I'm using Canu 1.8 on CentOS release 6.5 (HPC, it has 2TB memory), and I'm using Canu only for correction
Here's the command: 
`canu -correct -p SAD4_corrected -d ./SAD4_correctedreads gnuplotTested=true genomeSize=216m minReadLength=1000 stopOnReadQuality=false -nanopore-raw ./SAD4_porechop.fastq corMemory=1800 ovsMemory=1800`
However, Canu stopped with the error message below, could someone suggest me how should I overcome this problem, please?
Thank you!

```Starting command on Wed May 22 14:39:57 2019 with 1910.01 GB free disk space
/home/hpc/crlee/miniconda/envs/nanopore/libexec/generateCorrectionLayouts \
      -G /home/hpc/crlee/boechera_nanopore/SAD12/./SAD4_correctedreads/correction/SAD4_corrected.gkpStore \
      -O /home/hpc/crlee/boechera_nanopore/SAD12/./SAD4_correctedreads/correction/SAD4_corrected.ovlStore \
      -S /home/hpc/crlee/boechera_nanopore/SAD12/./SAD4_correctedreads/correction/2-correction/SAD4_corrected.globalScores \
      -C 80 \
      -p /home/hpc/crlee/boechera_nanopore/SAD12/./SAD4_correctedreads/correction/2-correction/SAD4_corrected.estimate.WORKING
Finished on Wed May 22 14:40:34 2019 (37 seconds) with 1910.008 GB free disk space
Illegal division by zero at /home/hpc/crlee/miniconda/envs/nanopore/libexec/lib/canu/CorrectReads.pm line 427

**Comment by skoren** [comment]
I don't think you're actually using 1.8, the conda installs are broken and not recommended. The command you listed isn't run anymore in 1.8, I think it's 1.6 or earlier. I'd suggest installing Canu from our repo using the pre-compiled binaries for your system and starting the assembly from scratch in a new folder to see if it resolves the issue.

**Comment by JesChen** [comment]
Alright, thank you very much!
