### ISSUE TITLE
assembling cancer genomes with canu

### ISSUE THREAD

**Issue by sjin09** [marbl/canu#1372]
To whom it may concern,

We have generated 30X HiFi data for a cancer genome with chromothripsis and other small and large structural rearrangements and we are attempting to assemble this monstrous genome. I would also like to highlight a peculiar characteristic of this genome. Chromothripsis, for example, has occurred on one chromosome 6, but the other chromosome is normal (there is no chromothripsis). Here are the questions.

1. I am hoping that increasing the length of exact kmer match might allow for some partial haplotype phasing during the assembly. Richard has informed me that your group has experimented with this approach in the VGP and I was wondering if you could illuminate me on this process.

2. Maybe I missed the documentation, but I just wanted to confirm that read trimming through -trim option is not required for the HiFi reads  and that only the assembly step would be performed through -assemble option.

Many thanks,
Sangjin Lee

session
canu --version: Canu 1.8
uname -a: Linux flye 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by skoren** [comment]
1. The length of the kmer isn't going to affect the haplotype separation, the lower error rate does help. I'd suggest using the parameters listed in the CCS manuscript (Wenger et al) for Canu. You can see from that manuscript that Canu already separated some diverged regions of the human genome and so would likely separate diverged regions in your sample too. We are working on some strategies to separate the haplotype blocks more but that code isn't ready for general use yet.

2. You definitely want trim, the CCS reads are not perfect and benefit from the same trimming that Canu would do for corrected reads.

**Comment by sjin09** [comment]
Thank you @skoren
