### ISSUE TITLE
Correction issue-Overlap store sorting jobs failed: Protocol error

### ISSUE THREAD

**Issue by nkuyfq** [marbl/canu#1374]
I am using Canu 1.8 for the first time in Ubuntu 16 installed in VirtualBox.

When I run the canu command, the error message occured as below:

```
> 
_-- Overlap store sorting jobs failed, tried 2 times, giving up.
--   job correction/test.ovlStore.BUILDING/0001 FAILED.
--   job correction/test.ovlStore.BUILDING/0002 FAILED._
```
The two log files in the directory "correction\test.ovlStore.BUILDING\logs" had similar contents like:

```
Attempting to increase maximum allowed processes and open files.
./scripts/2-sort.sh: 1: ulimit: Illegal option -u
./scripts/2-sort.sh: 1: ulimit: Illegal option -u
./scripts/2-sort.sh: 70: ulimit: Illegal option -u
./scripts/2-sort.sh: 1: ulimit: Illegal option -u
  Changed max processes per user from  to  (max ).
  Changed max open files from 1024 to 1048576 (max 1048576).

Finding overlaps.
  found     807271 overlaps in './test.ovlStore.BUILDING/bucket0001/sliceSizes'.
Loading     807271 overlaps using 0.02 GB of allowed (-M) 1 GB memory.
  loading     807271 overlaps from './test.ovlStore.BUILDING/bucket0001/slice0001'.

Sorting.
Writing sorted overlaps.
Failed to open './test.ovlStore.BUILDING/0001<001>' for writing: Protocol error
```

When I re-ran the command, the similar error message re-appeared. I am not sure what does the "Protocol error" mean.

**Comment by skoren** [comment]
This is most likely a VM issue not a canu issue, essentially your file system is refusing to write to disk. Some people who've experienced similar issues (https://forums.virtualbox.org/viewtopic.php?f=6&t=33378) said it is due to permissions on the folder. You may also be running out of space in the location you're running Canu.

**Comment by nkuyfq** [comment]
Thank you so much. I have solved this issue by using the method as #811 described. It was a VM issue as you mentioned.

**Comment by brianwalenz** [comment]
Can you do two tests for me, using the latest non-release version of canu?

1) Compiling this version should report `Using user-supplied CXXFLAGS '-DPOSIX_FILE_NAMES'.` at the very start of the compilation:
```
% make | more
Building for 'Darwin' '17.7.0' as 'amd64' into '/Users/walenzbp/canu/Darwin-amd64/{bin,obj}'.
Using '/opt/local/bin/c++' version '8.3.0'.
Using user-supplied CXXFLAGS '-DPOSIX_FILE_NAMES'.

Building snapshot v1.8 +244 changes (r9454 c8152a705b5b946fadb53ff85cb4ec3faf65c0fd) (ahead of github)
```

2) If so, can you run another assembly in the shared folder (where your original assembly was failing)?

The issue is that NTFS cannot create files with `<>` in them, and canu (foolishly) wants to do that.  I changed the Makefile to attempt to detect this condition.

**Comment by nkuyfq** [comment]
@brianwalenz  Would you please give more information about the test? I am now using the binary version of Canu 1.8. Should I install Canu v1.8 from the source codes? What's the command line like?

**Comment by brianwalenz** [comment]
Stick with 1.8 for your production assemblies.

The test amounts to downloading the latest version from https://github.com/marbl/canu/archive/master.zip, extracting the files, and then:
```
cd canu-master/src
make -j 4
make
```
The first `make` will compile the assembler (hopefully) and will take a minute or three.  The second make will report just the header as I show in my previous message.  Paste that header in.

If it reports the POSIX_FILE_NAMES line, start another assembly in your shared directory (the same place where you originally ran, the place where it failed) using this version.  If it doesn't, then I've got some more work to do.

Thanks for the help.  No worries if you want to bail on this.

**Comment by nkuyfq** [comment]
@brianwalenz 
I have got an error message just after the command "make -j 4" by using root permission:

> 
In file included from /usr/include/c++/5/tuple:35:0,
                 from overlapAlign/overlapAlign-computation.H:32,
                 from overlapAlign/overlapAlign.C:41:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^

....

Makefile:707: recipe for target '/opt/canu-master/canu-master/Linux-amd64/obj/bin/overlapAlign/overlapAlign/overlapAlign.o' failed
make: *** [/opt/canu-master/canu-master/Linux-amd64/obj/bin/overlapAlign/overlapAlign/overlapAlign.o] Error 1
make: *** Waiting for unfinished jobs....
Makefile:707: recipe for target '/opt/canu-master/canu-master/Linux-amd64/obj/bin/overlapAlign/overlapAlign/computeOverlapAlignment.o' failed
make: *** [/opt/canu-master/canu-master/Linux-amd64/obj/bin/overlapAlign/overlapAlign/computeOverlapAlignment.o] Error 1

It seems that some library would be needed.

**Comment by skoren** [comment]
What version of gcc do you have? I'd guess 5 or older. I'd recommend compiling with 7 or at least 6 to fix the error message.

**Comment by nkuyfq** [comment]
@brianwalenz @skoren 
Sorry for the delayed response.

I have upgraded gcc and g++ from 5.4.0 to 7.4.0.
'sudo make -j 4' was successfully complied after using gcc -7.4.
However, after running 'sudo make' or 'sudo make | more', the messages were displayed as below:

> 
WARNING:
WARNING: g++ 7 detected, disabling stack trace support.  Please upgrade to GCC 4.7 or higher.
WARNING:
Building for 'Linux' '4.15.0-50-generic' as 'amd64' into '/opt/canu-master/Linux-amd64/{bin,obj}'.
Using '/usr/bin/g++' version '7'.

Building master-snapshot v1.8

Success!
canu installed in /opt/canu-master/Linux-amd64/bin/canu


Regrettably, it seemed that 'Using user-supplied CXXFLAGS '-DPOSIX_FILE_NAMES'' didn't appear in the shell terminal.

**Comment by brianwalenz** [comment]
I guess it's Plan B then.

Thanks for the help.
