### ISSUE TITLE
Are there any known issues running canu with Java 12 on a mac?

### ISSUE THREAD

**Issue by mradz19** [marbl/canu#1378]
I am trying to run canu on a mac but I don't think it is working, it seems to stall. I noticed the recommended java is version 8, my mac runs version 12, is that compatible with canu?

**Comment by skoren** [comment]
Older versions of Canu didn't work with JVM 10+ but 1.8 should be compatible. If it launches java and is using CPU then it is OK.

**Comment by skoren** [comment]
Idle, no response
