### ISSUE TITLE
canu error correct for PCR amplicons

### ISSUE THREAD

**Issue by xusijia1211** [marbl/canu#1379]
Hi developer, I saw several questions here about PCR amplicon but still confused with my results so need your help badly.
My data is generated by ONT nanopore sequencing. I sequenced 5 different amplicons (~ 10kbp each, short overlaps between each other) that totally cover a whole target gene. All reads are after trimming with Nanofilt. Since there is a reference genome, I decided only to use canu's correct function and do an alignment with the corrected file. However, it keeps giving me an error message as "Overlap store bucketizer jobs failed, tried 2 times, giving up".
I restarted it but nothing changed.
I saw your suggestions in [https://github.com/marbl/canu/issues/583](url) , but I don't understand what "increase corOutCoverage" and "randomly subsample the corrected reads" mean. 
I put the screenshot here. Any help would be greatly appreciated. Thank you.
 
![image](https://user-images.githubusercontent.com/49852351/58887529-c0829f80-8720-11e9-8de7-01c39a443940.png)
![image](https://user-images.githubusercontent.com/49852351/58887586-d7c18d00-8720-11e9-870c-0f24db40c640.png)
![image](https://user-images.githubusercontent.com/49852351/58887624-e60fa900-8720-11e9-8638-c6628d9f09ea.png)
![image](https://user-images.githubusercontent.com/49852351/58887670-ffb0f080-8720-11e9-9c7d-c168e7e1b3a9.png)
![image](https://user-images.githubusercontent.com/49852351/58887725-19523800-8721-11e9-8011-843c424c1eb4.png)
![image](https://user-images.githubusercontent.com/49852351/58887771-2cfd9e80-8721-11e9-968d-a8da92bf8a1f.png)
![image](https://user-images.githubusercontent.com/49852351/58887795-3edf4180-8721-11e9-844b-6c337e379534.png)
![image](https://user-images.githubusercontent.com/49852351/58887820-4bfc3080-8721-11e9-9d6e-f780c9c3950b.png)

**Comment by skoren** [comment]
I wouldn't worry about corOutCoverage (it's a parameter to Canu, see the metagenomic assembly FAQ) for now. The error isn't likely to be related. Post the contents of one or more of the failing bucket jobs (e.g. `correction/*.ovlStore.BUILDING/logs/1-bucketize.*.out`).

**Comment by xusijia1211** [comment]
Hi skoren, thank you for the quick reply.
Here are the contents. Please let me anything else need to provide.
Thank you for the help.
![image](https://user-images.githubusercontent.com/49852351/58941504-ea86a100-87b6-11e9-9406-3e4c23a6d809.png)
![image](https://user-images.githubusercontent.com/49852351/58941632-228de400-87b7-11e9-9987-03a30cf4f920.png)
![image](https://user-images.githubusercontent.com/49852351/58942045-f161e380-87b7-11e9-8d46-f641dbffbf46.png)
![image](https://user-images.githubusercontent.com/49852351/58941989-d98a5f80-87b7-11e9-8258-a5bafa97f687.png)

**Comment by brianwalenz** [comment]
It would seem you've hit your disk quota limit.  The earlier logging is showing the disk has 3 TB free space, but the error messages are "Disk quota exceeded".

**Comment by xusijia1211** [comment]
Thank you Brian, the fastq file I used here is about 770M, is it normal that canu uses so many spaces when correct a file like this? Anything I could do to fix this?

**Comment by skoren** [comment]
The canu run is only using a few GB, at the start of the run you had 3136 G free and when it failed you had 3095G free. That's about 40gb. Yes, given 10,000 fold coverage that isn't unexpected. You can randomly downsample to 100x coverage or so (making sure to keep even coverage of all the amplicons). That is, select a random subset of the data, given 10,000x coverage to get down to 200x you want to keep every 50th read or so.

**Comment by xusijia1211** [comment]
Thank you Skoren for such detailed suggestion!  I'll give it a try and let you know the results.

**Comment by xusijia1211** [comment]
Hi, Skoren and Brian. Thanks for the suggestion. I tried the downsampling method by adding readSamplingCoverage=200. It finished in seconds and generated a fasta.gz of 1.8M.
Also, I tried increasing the space and ran the whole dataset using the earlier command.  It also works. Canu used 22G during the process. I got a fasta.gz file of 44M by this. 
![image](https://user-images.githubusercontent.com/49852351/59095784-489cbb00-8954-11e9-94c5-2a61c39b5af4.png)
![image](https://user-images.githubusercontent.com/49852351/59095858-7da90d80-8954-11e9-88ab-49b2d2da7f63.png)
Here I have other questions. If I use downsampling method, does the size of raw data matters?  ( say, any difference between given 770M or 5G data here?)  Also, for downstream variant detection, is coverage number here the larger the better? (readSamplingCoverage=xxx) .
Thank you for being so patient.

**Comment by skoren** [comment]
I'd expect the amplicons are present in both the downsampled and the full dataset, just at difference coverages. You could check this though to confirm.

For variant detection, do you mean variants within your PCR products? In that case I'd rely on the raw data themselves because the corrected reads won't keep variants in phase. There are a few SNP/variant callers available for nanopore data.

**Comment by xusijia1211** [comment]
OK, I understand. Thank you very much for all the information. I think it's ok to close the issue.
