### ISSUE TITLE
an error when running in PBS

### ISSUE THREAD

**Issue by wisekh6** [marbl/canu#138]
Hello,

When I ran canu in a PBS mode, it failed at "5-consensus" step. But, when I RE-RAN canu (without removing the outputs from the previous run) in a shell mode, canu successfully ran with success. It looks like canu automatically re-started at the 5-concensus step. I would like to assume that this job is complete with success. Have you ever seen this before? and Do you also agree that this can be considered to be a completion?

Thank you in advance,

HK

**Comment by brianwalenz** [comment]
Yup, it's complete.

This can happen if your job is starved of memory by other processes.  The consensus job is attempted three times, but all three fail because of the other large job.  On the (much) later restart, the large job isn't present, and consensus ran to completion.

**Comment by wisekh6** [comment]
Thank you very much for confirming it.
