### ISSUE TITLE
canu stopped in cormhap

### ISSUE THREAD

**Issue by umdChenwaiting** [marbl/canu#1380]
Hi, I tried to ran canu on Atmosphere, Cyverse, and it stopped in the process of cormhap.
I used df command to see the usage of the output folder( as you can see in the last picture, the folder is vol_c, of which only 10% was used), and it seemed that it was not a issue about disk space. I also checked the r1 output folder, and I didn't find any unnormal file. Could you please figure out what problem it was or what file should I check to find the problem? Thank you in advance.
![1](https://user-images.githubusercontent.com/42663082/58901142-943e3300-86ce-11e9-8027-460eed17a608.png)
![2](https://user-images.githubusercontent.com/42663082/58901143-943e3300-86ce-11e9-998d-6e53cc870f1d.png)
![3](https://user-images.githubusercontent.com/42663082/58901144-94d6c980-86ce-11e9-9598-7697e7063669.png)
![4](https://user-images.githubusercontent.com/42663082/58901145-94d6c980-86ce-11e9-9009-a5f302e2ad7c.png)
![5](https://user-images.githubusercontent.com/42663082/58901146-94d6c980-86ce-11e9-9ec2-34216da02004.png)
![6](https://user-images.githubusercontent.com/42663082/58901147-94d6c980-86ce-11e9-918f-d339bde06e72.png)
![7](https://user-images.githubusercontent.com/42663082/58901148-94d6c980-86ce-11e9-8ceb-d32c8956e163.png)
![8](https://user-images.githubusercontent.com/42663082/58901149-94d6c980-86ce-11e9-8831-aa304c3f2b73.png)

**Comment by skoren** [comment]
I see you still have issue #1367 open, is this the same assembly? If so I'll close that issue to avoid duplication.

As before (e.g. #1337) post the output of the failing job, like ```mhap.*1.out```.

**Comment by skoren** [comment]
Idle, no response.
