### ISSUE TITLE
Failed with exit code 139.  (rc=35584)

### ISSUE THREAD

**Issue by limin321** [marbl/canu#1381]
I run canu on my agrobacterium nanopose data, and failed. Could anyone have any good advice on how to solve the problem?
Here is my command line:
```
dklabuser$ canu -p 91156 -d outdir_canu genomeSize=6m -gnuplotTested=true -nanopore-raw BC05.fastq 
```
and here is the failed information:
<img width="1259" alt="Screen Shot 2019-06-04 at 5 05 09 PM" src="https://user-images.githubusercontent.com/42760669/58921453-a9758a80-86eb-11e9-9005-3c21a20e24eb.png">
```
-- Finished on Tue Jun  4 16:51:09 2019 (lickety-split) with 1140.412 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 139.  (rc=35584)
ERROR:
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

Disk space available:  1140.412 GB

Last 50 lines of the relevant log file (/Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/91156.ovlStore.err):

Found 51134466 (51.13 million) overlaps.
Configuring for 2.00 GB to 8.00 GB memory and 2544 open files.
Will sort using 1 files; 58720256 (58.72 million) overlaps per bucket; 2.00 GB memory per bucket
  bucket   1 has 51134466 olaps.
  bucket   2 has 0 olaps.
Will sort 51.134 million overlaps per bucket, using 1 buckets 1.77 GB per bucket.


-- BUCKETIZING --

-  Bucketizing '/Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/results/000001.ovb'

canu failed with 'failed to create the overlap store'.
```

Thank you so much whoever can help.

**Comment by limin321** [comment]
Here is the full running information:

-- Canu v0.0 (+0 commits) r0 unknown-hash-tag-no-repository-available.
-- Detected Java(TM) Runtime Environment '1.8.0_112' (from '/Users/dklabuser/miniconda2/bin/java').
-- Detected 12 CPUs and 32 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
-- Allowed to run   3 jobs concurrently, and use up to   4 compute threads and   10 GB memory for stage 'bogart (unitigger)'.
-- Allowed to run   1 job  concurrently, and use up to  12 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   1 job  concurrently, and use up to  12 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   1 job  concurrently, and use up to  12 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   3 jobs concurrently, and use up to   4 compute threads and    2 GB memory for stage 'read error detection (overlap error adjustment)'.
-- Allowed to run  12 jobs concurrently, and use up to   1 compute thread  and    1 GB memory for stage 'overlap error adjustment'.
-- Allowed to run   3 jobs concurrently, and use up to   4 compute threads and   10 GB memory for stage 'utgcns (consensus)'.
-- Allowed to run  12 jobs concurrently, and use up to   1 compute thread  and    2 GB memory for stage 'overlap store parallel bucketizer'.
-- Allowed to run  12 jobs concurrently, and use up to   1 compute thread  and    8 GB memory for stage 'overlap store parallel sorting'.
-- Allowed to run  12 jobs concurrently, and use up to   1 compute thread  and    2 GB memory for stage 'overlapper'.
-- Allowed to run   2 jobs concurrently, and use up to   6 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run   2 jobs concurrently, and use up to   6 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run   3 jobs concurrently, and use up to   4 compute threads and    8 GB memory for stage 'meryl (k-mer counting)'.
-- Allowed to run   6 jobs concurrently, and use up to   2 compute threads and    6 GB memory for stage 'falcon_sense (read correction)'.
-- Allowed to run   1 job  concurrently, and use up to  12 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   1 job  concurrently, and use up to  12 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   1 job  concurrently, and use up to  12 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
--
-- This is canu parallel iteration #1, out of a maximum of 2 attempts.
--
-- Final error rates before starting pipeline:
--   
--   genomeSize          -- 6000000
--   errorRate           -- 0.048
--   
--   corOvlErrorRate     -- 0.144
--   obtOvlErrorRate     -- 0.144
--   utgOvlErrorRate     -- 0.144
--   
--   obtErrorRate        -- 0.144
--   
--   cnsErrorRate        -- 0.144
--
--
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Tue Jun  4 16:12:14 2019 with 1143.308 GB free disk space

    /Users/dklabuser/miniconda2/libexec/gatekeeperCreate \
      -minlength 1000 \
      -o /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/91156.gkpStore.BUILDING \
      /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/91156.gkpStore.gkp \
    > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/91156.gkpStore.BUILDING.err 2>&1

-- Finished on Tue Jun  4 16:12:27 2019 (13 seconds) with 1142.866 GB free disk space
----------------------------------------
sh: line 1: 97113 Abort trap: 6           gnuplot /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/91156.gkpStore/readlengths.gp > /dev/null 2>&1
--
-- WARNING: gnuplot failed; no plots will appear in HTML output.
--
----------------------------------------
--
-- In gatekeeper store '/Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/91156.gkpStore':
--   Found 113172 reads.
--   Found 1589607138 bases (264.93 times coverage).
--
--   Read length histogram (one '*' equals 195.9 reads):
--        0    999      0 
--     1000   1999  13713 **********************************************************************
--     2000   2999  10166 ***************************************************
--     3000   3999   7812 ***************************************
--     4000   4999   6398 ********************************
--     5000   5999   5815 *****************************
--     6000   6999   5078 *************************
--     7000   7999   4697 ***********************
--     8000   8999   4181 *********************
--     9000   9999   3841 *******************
--    10000  10999   3572 ******************
--    11000  11999   3202 ****************
--    12000  12999   3131 ***************
--    13000  13999   2735 *************
--    14000  14999   2491 ************
--    15000  15999   2354 ************
--    16000  16999   2112 **********
--    17000  17999   2035 **********
--    18000  18999   1863 *********
--    19000  19999   1731 ********
--    20000  20999   1619 ********
--    21000  21999   1502 *******
--    22000  22999   1420 *******
--    23000  23999   1377 *******
--    24000  24999   1271 ******
--    25000  25999   1171 *****
--    26000  26999   1042 *****
--    27000  27999   1027 *****
--    28000  28999    914 ****
--    29000  29999    858 ****
--    30000  30999    821 ****
--    31000  31999    764 ***
--    32000  32999    739 ***
--    33000  33999    690 ***
--    34000  34999    624 ***
--    35000  35999    633 ***
--    36000  36999    584 **
--    37000  37999    538 **
--    38000  38999    529 **
--    39000  39999    485 **
--    40000  40999    465 **
--    41000  41999    425 **
--    42000  42999    392 **
--    43000  43999    392 **
--    44000  44999    388 *
--    45000  45999    303 *
--    46000  46999    286 *
--    47000  47999    290 *
--    48000  48999    286 *
--    49000  49999    254 *
--    50000  50999    244 *
--    51000  51999    211 *
--    52000  52999    228 *
--    53000  53999    211 *
--    54000  54999    188 
--    55000  55999    190 
--    56000  56999    153 
--    57000  57999    139 
--    58000  58999    143 
--    59000  59999    115 
--    60000  60999    126 
--    61000  61999    120 
--    62000  62999    110 
--    63000  63999    108 
--    64000  64999    100 
--    65000  65999     89 
--    66000  66999    100 
--    67000  67999     90 
--    68000  68999     92 
--    69000  69999     75 
--    70000  70999     76 
--    71000  71999     68 
--    72000  72999     53 
--    73000  73999     61 
--    74000  74999     49 
--    75000  75999     50 
--    76000  76999     48 
--    77000  77999     50 
--    78000  78999     65 
--    79000  79999     46 
--    80000  80999     43 
--    81000  81999     39 
--    82000  82999     38 
--    83000  83999     25 
--    84000  84999     29 
--    85000  85999     33 
--    86000  86999     32 
--    87000  87999     34 
--    88000  88999     28 
--    89000  89999     20 
--    90000  90999     20 
--    91000  91999     21 
--    92000  92999     26 
--    93000  93999     16 
--    94000  94999     28 
--    95000  95999     25 
--    96000  96999     11 
--    97000  97999     18 
--    98000  98999     17 
--    99000  99999     15 
--   100000 100999      7 
--   101000 101999     14 
--   102000 102999      8 
--   103000 103999     15 
--   104000 104999      8 
--   105000 105999     12 
--   106000 106999      2 
--   107000 107999     10 
--   108000 108999     11 
--   109000 109999     11 
--   110000 110999      7 
--   111000 111999      4 
--   112000 112999      4 
--   113000 113999     10 
--   114000 114999      4 
--   115000 115999      5 
--   116000 116999      5 
--   117000 117999      6 
--   118000 118999      3 
--   119000 119999      2 
--   120000 120999      8 
--   121000 121999      6 
--   122000 122999      5 
--   123000 123999      1 
--   124000 124999      5 
--   125000 125999      2 
--   126000 126999      2 
--   127000 127999      3 
--   128000 128999      5 
--   129000 129999      3 
--   130000 130999      1 
--   131000 131999      2 
--   132000 132999      3 
--   133000 133999      1 
--   134000 134999      4 
--   135000 135999      8 
--   136000 136999      0 
--   137000 137999      4 
--   138000 138999      0 
--   139000 139999      1 
--   140000 140999      0 
--   141000 141999      1 
--   142000 142999      1 
--   143000 143999      2 
--   144000 144999      3 
--   145000 145999      0 
--   146000 146999      2 
--   147000 147999      1 
--   148000 148999      2 
--   149000 149999      1 
--   150000 150999      1 
--   151000 151999      1 
--   152000 152999      0 
--   153000 153999      3 
--   154000 154999      0 
--   155000 155999      0 
--   156000 156999      1 
--   157000 157999      0 
--   158000 158999      0 
--   159000 159999      0 
--   160000 160999      0 
--   161000 161999      1 
--   162000 162999      0 
--   163000 163999      1 
--   164000 164999      0 
--   165000 165999      0 
--   166000 166999      1 
--   167000 167999      0 
--   168000 168999      1 
--   169000 169999      0 
--   170000 170999      0 
--   171000 171999      0 
--   172000 172999      0 
--   173000 173999      0 
--   174000 174999      0 
--   175000 175999      1 
--   176000 176999      1 
--   177000 177999      0 
--   178000 178999      0 
--   179000 179999      0 
--   180000 180999      0 
--   181000 181999      0 
--   182000 182999      0 
--   183000 183999      1 
--   184000 184999      0 
--   185000 185999      0 
--   186000 186999      1 
--   187000 187999      0 
--   188000 188999      0 
--   189000 189999      0 
--   190000 190999      1 
-- Meryl attempt 1 begins.
----------------------------------------
-- Starting concurrent execution on Tue Jun  4 16:12:28 2019 with 1142.863 GB free disk space (1 processes; 3 concurrently)

    /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/0-mercounts/meryl.sh 1 > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/0-mercounts/meryl.000001.out 2>&1

-- Finished on Tue Jun  4 16:19:50 2019 (442 seconds) with 1141.216 GB free disk space
----------------------------------------
-- Meryl finished successfully.
----------------------------------------
-- Starting command on Tue Jun  4 16:19:50 2019 with 1141.216 GB free disk space

    /Users/dklabuser/miniconda2/libexec/meryl \
      -Dh \
      -s /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/0-mercounts/91156.ms16 \
    > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/0-mercounts/91156.ms16.histogram \
    2> /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/0-mercounts/91156.ms16.histogram.info

-- Finished on Tue Jun  4 16:19:50 2019 (lickety-split) with 1141.216 GB free disk space
----------------------------------------
sh: line 1: 97214 Abort trap: 6           gnuplot /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/0-mercounts/91156.ms16.histogram.lg.gp > /dev/null 2>&1
--
-- WARNING: gnuplot failed; no plots will appear in HTML output.
--
----------------------------------------
sh: line 1: 97216 Abort trap: 6           gnuplot /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/0-mercounts/91156.ms16.histogram.sm.gp > /dev/null 2>&1
--
-- WARNING: gnuplot failed; no plots will appear in HTML output.
--
----------------------------------------
-- For mhap overlapping, set repeat k-mer threshold to 15879.
--
-- Found 1587909558 16-mers; 399099596 distinct and 243066901 unique.  Largest count 453376.
--
-- OVERLAPPER (mhap) (correction)
--
-- Set corMhapSensitivity=low based on read coverage of 264.
--
-- PARAMETERS: hashes=256, minMatches=3, threshold=0.8
--
-- Given 6 GB, can fit 18000 reads per block.
-- For 8 blocks, set stride to 2 blocks.
-- Logging partitioning to '/Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/partitioning.log'.
-- Configured 7 mhap precompute jobs.
-- Configured 13 mhap overlap jobs.
-- mhap precompute attempt 1 begins with 0 finished, and 7 to compute.
----------------------------------------
-- Starting concurrent execution on Tue Jun  4 16:19:58 2019 with 1142.838 GB free disk space (7 processes; 1 concurrently)

    /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/precompute.sh 1 > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/precompute.000001.out 2>&1
    /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/precompute.sh 2 > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/precompute.000002.out 2>&1
    /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/precompute.sh 3 > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/precompute.000003.out 2>&1
    /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/precompute.sh 4 > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/precompute.000004.out 2>&1
    /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/precompute.sh 5 > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/precompute.000005.out 2>&1
    /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/precompute.sh 6 > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/precompute.000006.out 2>&1
    /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/precompute.sh 7 > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/precompute.000007.out 2>&1

-- Finished on Tue Jun  4 16:46:11 2019 (1573 seconds) with 1140.894 GB free disk space
----------------------------------------
-- All 7 mhap precompute jobs finished successfully.
-- mhap attempt 1 begins with 0 finished, and 13 to compute.
----------------------------------------
-- Starting concurrent execution on Tue Jun  4 16:46:11 2019 with 1140.894 GB free disk space (13 processes; 1 concurrently)

    /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.sh 1 > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.000001.out 2>&1
    /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.sh 2 > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.000002.out 2>&1
    /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.sh 3 > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.000003.out 2>&1
    /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.sh 4 > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.000004.out 2>&1
    /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.sh 5 > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.000005.out 2>&1
    /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.sh 6 > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.000006.out 2>&1
    /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.sh 7 > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.000007.out 2>&1
    /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.sh 8 > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.000008.out 2>&1
    /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.sh 9 > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.000009.out 2>&1
    /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.sh 10 > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.000010.out 2>&1
    /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.sh 11 > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.000011.out 2>&1
    /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.sh 12 > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.000012.out 2>&1
    /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.sh 13 > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/mhap.000013.out 2>&1

-- Finished on Tue Jun  4 16:51:09 2019 (298 seconds) with 1140.412 GB free disk space
----------------------------------------
-- Found 13 mhap overlap output files.
----------------------------------------
-- Starting command on Tue Jun  4 16:51:09 2019 with 1140.412 GB free disk space

    /Users/dklabuser/miniconda2/libexec/ovStoreBuild \
     -O /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/91156.ovlStore.BUILDING \
     -G /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/91156.gkpStore \
     -M 2-8 \
     -L /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/ovljob.files \
     > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/91156.ovlStore.err 2>&1
sh: line 5: 97678 Segmentation fault: 11  /Users/dklabuser/miniconda2/libexec/ovStoreBuild -O /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/91156.ovlStore.BUILDING -G /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/91156.gkpStore -M 2-8 -L /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/ovljob.files > /Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/91156.ovlStore.err 2>&1

-- Finished on Tue Jun  4 16:51:09 2019 (lickety-split) with 1140.412 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 139.  (rc=35584)
ERROR:
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

Disk space available:  1140.412 GB

Last 50 lines of the relevant log file (/Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/91156.ovlStore.err):

Found 51134466 (51.13 million) overlaps.
Configuring for 2.00 GB to 8.00 GB memory and 2544 open files.
Will sort using 1 files; 58720256 (58.72 million) overlaps per bucket; 2.00 GB memory per bucket
  bucket   1 has 51134466 olaps.
  bucket   2 has 0 olaps.
Will sort 51.134 million overlaps per bucket, using 1 buckets 1.77 GB per bucket.


-- BUCKETIZING --

-  Bucketizing '/Users/dklabuser/limin/nanopolish/BC05-BWG1E3/outdir_canu/correction/1-overlapper/results/000001.ovb'

canu failed with 'failed to create the overlap store'.

**Comment by brianwalenz** [comment]
This looks like a fairly old version of Canu.  Can you upgrade to v1.8 and restart from scratch?  Installing canu directly, outside of conda or any package manager, is strongly suggested.

**Comment by limin321** [comment]
> This looks like a fairly old version of Canu. Can you upgrade to v1.8 and restart from scratch? Installing canu directly, outside of conda or any package manager, is strongly suggested.

Thank you so much. 😊  I am trying to install canu1.8 and I have problem install this, here is information:
(base) KluepfelLabMBP01:~ dklabuser$ gunzip -dc canu-1.8.tar.gz | tar -xf -
(base) KluepfelLabMBP01:~ dklabuser$ ls
1			Documents		Library			PhD			Sites			canu-1.8.tar.gz		miniconda2
Applications		Downloads		Movies			Pictures		VirtualBox VMs		limin			standard-RAxML-master
Desktop			Filtlong		Music			Public			canu-1.8		master.zip
(base) KluepfelLabMBP01:~ dklabuser$ cd canu-1.8/src/
(base) KluepfelLabMBP01:src dklabuser$ ls
AS_global.C		bogart-analysis		dx-canu			main.mk			overlapBasedTrimming	pipelines		utility
AS_global.H		bogus			fastq-utilities		meryl			overlapErrorAdjustment	sequence		wtdbg
Makefile		canu_version_update.pl	gfa			mhap			overlapInCore		stores
bogart			correction		haplotyping		minimap			overlapInCore-analysis	utgcns
(base) KluepfelLabMBP01:src dklabuser$ make -j 8
Makefile:451: 
Makefile:455: Compiler 'c++' at '/usr/bin/c++' reports version 'Apple LLVM version 10.0.1 (clang-1001.0.46.4)'.
Makefile:457: 
Makefile:458: Canu cannot be compiled with this compiler.  Please install GCC and/or
Makefile:459: specify a non-Clang compiler on the command line, e.g.,
Makefile:460:     make CC=/path/to/gcc CXX=/path/to/g++
Makefile:461: 
Makefile:462: *** unsupported compiler.  Stop.
(base) KluepfelLabMBP01:src dklabuser$ 

How should specifically solve this problem?  
I have no idea about how to get a complier to fit for canu.

Your help is greatly appreciated.

**Comment by brianwalenz** [comment]
The easiest will be to use the pre-compiled version: https://github.com/marbl/canu/releases/download/v1.8/canu-1.8.Darwin-amd64.tar.xz

If you want to compile yourself, you'll need to install gcc7 through MacPorts or homebrew or some such.

**Comment by limin321** [comment]
> The easiest will be to use the pre-compiled version: https://github.com/marbl/canu/releases/download/v1.8/canu-1.8.Darwin-amd64.tar.xz
> 
> If you want to compile yourself, you'll need to install gcc7 through MacPorts or homebrew or some such.

Thank you so much! I downloaded the version you just recommended and ran the tar command to uncompress, however, I still don't know how to install it. I am really new to bioinformatics, would you mind give me the detail steps of how to install them with command line. 
I follow these commands: gunzip -dc canu-v1.8.tar.gz | tar -xf -
cd canu-1.8/src
make -j 8
cd ..
but I don't have a src folder. I am really lost how to install them with command line. Thank you so much. Really appreciate it.  Here is the info inside the folder where I downloaded.

<img width="630" alt="Screen Shot 2019-06-05 at 8 46 43 AM" src="https://user-images.githubusercontent.com/42760669/58970721-cbfcb780-876e-11e9-9c47-31aceb5896ea.png">

**Comment by skoren** [comment]
It's installed once you extract it, you don't need to run make as the release notes say, all you need to do is run the canu command from /full/path/to/yourinstall/canu-1.8/*/bin/canu instead of just canu as you were doing before.

**Comment by limin321** [comment]
> It's installed once you extract it, you don't need to run make as the release notes say, all you need to do is run the canu command from /full/path/to/yourinstall/canu-1.8/*/bin/canu instead of just canu as you were doing before. Run with a new folder (-d) option and remove the previous run since the new version won't be compatible with the old started run.

#################################
It is running now and will keep the results updated. Thank you so so so much.  Hope it won't fail this time. You guys are great. I really appreciate it.  Have a good day.

**Comment by limin321** [comment]
> It's installed once you extract it, you don't need to run make as the release notes say, all you need to do is run the canu command from /full/path/to/yourinstall/canu-1.8/*/bin/canu instead of just canu as you were doing before. Run with a new folder (-d) option and remove the previous run since the new version won't be compatible with the old started run.

After 10 hrs of running, my canu run successfully. Thank you so much. 😊
