### ISSUE TITLE
onSuccess= triggered on read correction/trimming

### ISSUE THREAD

**Issue by mjpdejong** [marbl/canu#1382]
I have a question concerning the onSuccess option to execute a command after completion of a genome assembly. It would be very useful if this option is also triggered when the -correction or -trim option is used and no assembly is being generated. At the moment I am happily using Canu for correction of raw nanopore reads, feeding the result in to other assemblers. Therefore it would be an efficient way to trigger downstream applications.

Greets, Marco

**Comment by skoren** [comment]
Yes, I see onSuccess is only checked when canu is generating output, which only gets run if you're assembling. Should be straightforward to add onSuccess to the end of canu in general instead. You should be able to modify your code to add:
```
    if (defined(getGlobal("onSuccess"))) {
        print STDERR "-- Running user-supplied termination command.\n";
        runCommand(getGlobal("onExitDir"), getGlobal("onSuccess") . " $asm");
    }
```
to the end of src/pipelines/canu.pl right before
```
print STDERR "--\n";
print STDERR "-- Bye.\n";
```

**Comment by brianwalenz** [comment]
Thanks for the suggestion.  It's been implemented.

**Comment by mjpdejong** [comment]
That is really nice! Many thanks for the effort.
