### ISSUE TITLE
can‘t install ...what should I do？

### ISSUE THREAD

**Issue by bestweicheng** [marbl/canu#1383]
canu/src$ make -j 6
Building for 'Linux' '4.15.0-50-generic' as 'amd64' into '/media/dell/Elements/canu/Linux-amd64/{bin,obj}'.
Using '/usr/bin/g++' version '5.4.0'.

Building snapshot v1.8 +258 changes (r9468 aa8c2ec4dc430d1cffbf844c3806058a358537b0) (sync'd with github)

g++ -o /media/dell/Elements/canu/Linux-amd64/obj/bin/overlapAlign/overlapAlign/overlapAlign.o -c -MD -g3 -O4 -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer -Wall -Wextra -Wformat -Wno-write-strings -Wno-char-subscripts -Wno-sign-compare -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-deprecated-declarations -D_GLIBCXX_PARALLEL -pthread -fopenmp -fPIC -DLIBBACKTRACE -I/media/dell/Elements/canu/src -Iutility -Istores -IoverlapInCore/libedlib overlapAlign/overlapAlign.C
g++ -o /media/dell/Elements/canu/Linux-amd64/obj/bin/overlapAlign/overlapAlign/computeOverlapAlignment.o -c -MD -g3 -O4 -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer -Wall -Wextra -Wformat -Wno-write-strings -Wno-char-subscripts -Wno-sign-compare -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-deprecated-declarations -D_GLIBCXX_PARALLEL -pthread -fopenmp -fPIC -DLIBBACKTRACE -I/media/dell/Elements/canu/src -Iutility -Istores -IoverlapInCore/libedlib overlapAlign/computeOverlapAlignment.C
g++ -o /media/dell/Elements/canu/Linux-amd64/obj/bin/overlapAlign/overlapAlign/trimRead.o -c -MD -g3 -O4 -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer -Wall -Wextra -Wformat -Wno-write-strings -Wno-char-subscripts -Wno-sign-compare -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-deprecated-declarations -D_GLIBCXX_PARALLEL -pthread -fopenmp -fPIC -DLIBBACKTRACE -I/media/dell/Elements/canu/src -Iutility -Istores -IoverlapInCore/libedlib overlapAlign/trimRead.C
g++ -o /media/dell/Elements/canu/Linux-amd64/obj/bin/overlapAlign/overlapAlign/computeAlignments.o -c -MD -g3 -O4 -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer -Wall -Wextra -Wformat -Wno-write-strings -Wno-char-subscripts -Wno-sign-compare -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-deprecated-declarations -D_GLIBCXX_PARALLEL -pthread -fopenmp -fPIC -DLIBBACKTRACE -I/media/dell/Elements/canu/src -Iutility -Istores -IoverlapInCore/libedlib overlapAlign/computeAlignments.C
g++ -o /media/dell/Elements/canu/Linux-amd64/obj/bin/alignGFA/gfa/alignGFA.o -c -MD -g3 -O4 -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer -Wall -Wextra -Wformat -Wno-write-strings -Wno-char-subscripts -Wno-sign-compare -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-deprecated-declarations -D_GLIBCXX_PARALLEL -pthread -fopenmp -fPIC -DLIBBACKTRACE -I/media/dell/Elements/canu/src -Iutility -Istores -IoverlapInCore/libedlib gfa/alignGFA.C
g++ -o /media/dell/Elements/canu/Linux-amd64/obj/bin/fastqAnalyze/fastq-utilities/fastqAnalyze.o -c -MD -g3 -O4 -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer -Wall -Wextra -Wformat -Wno-write-strings -Wno-char-subscripts -Wno-sign-compare -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-deprecated-declarations -D_GLIBCXX_PARALLEL -pthread -fopenmp -fPIC -DLIBBACKTRACE -I/media/dell/Elements/canu/src -Iutility fastq-utilities/fastqAnalyze.C
In file included from /usr/include/c++/5/tuple:35:0,
                 from overlapAlign/overlapAlign-computation.H:32,
                 from overlapAlign/trimRead.C:39:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
In file included from /usr/include/c++/5/tuple:35:0,
                 from overlapAlign/overlapAlign-computation.H:32,
                 from overlapAlign/computeOverlapAlignment.C:40:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
In file included from /usr/include/c++/5/tuple:35:0,
                 from overlapAlign/overlapAlign-computation.H:32,
                 from overlapAlign/overlapAlign.C:41:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
In file included from /usr/include/c++/5/tuple:35:0,
                 from overlapAlign/overlapAlign-computation.H:32,
                 from overlapAlign/computeAlignments.C:37:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
fastq-utilities/fastqAnalyze.C: In function ‘void doStats(char*, char*)’:
fastq-utilities/fastqAnalyze.C:185:25: warning: large integer implicitly truncated to unsigned type [-Woverflow]
   uint32   minLen     = UINT64_MAX;
                         ^
gfa/alignGFA.C: In function ‘void dotplot(uint32, bool, char*, uint32, bool, char*)’:
gfa/alignGFA.C:151:16: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
   system(Pfile);
                ^
Makefile:707: recipe for target '/media/dell/Elements/canu/Linux-amd64/obj/bin/overlapAlign/overlapAlign/overlapAlign.o' failed
make: *** [/media/dell/Elements/canu/Linux-amd64/obj/bin/overlapAlign/overlapAlign/overlapAlign.o] Error 1
make: *** 正在等待未完成的任务....
Makefile:707: recipe for target '/media/dell/Elements/canu/Linux-amd64/obj/bin/overlapAlign/overlapAlign/trimRead.o' failed
make: *** [/media/dell/Elements/canu/Linux-amd64/obj/bin/overlapAlign/overlapAlign/trimRead.o] Error 1
Makefile:707: recipe for target '/media/dell/Elements/canu/Linux-amd64/obj/bin/overlapAlign/overlapAlign/computeOverlapAlignment.o' failed
make: *** [/media/dell/Elements/canu/Linux-amd64/obj/bin/overlapAlign/overlapAlign/computeOverlapAlignment.o] Error 1
fastq-utilities/fastqAnalyze.C:128:30: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fgets(A, MAX_READ_LEN, F);
                              ^
fastq-utilities/fastqAnalyze.C:129:30: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fgets(B, MAX_READ_LEN, F);  chomp(B);
                              ^
fastq-utilities/fastqAnalyze.C:130:30: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fgets(C, MAX_READ_LEN, F);
                              ^
fastq-utilities/fastqAnalyze.C:131:30: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fgets(D, MAX_READ_LEN, F);  chomp(D);
                              ^
Makefile:707: recipe for target '/media/dell/Elements/canu/Linux-amd64/obj/bin/overlapAlign/overlapAlign/computeAlignments.o' failed
make: *** [/media/dell/Elements/canu/Linux-amd64/obj/bin/overlapAlign/overlapAlign/computeAlignments.o] Error 1
fastq-utilities/fastqAnalyze.C: In function ‘void doAnalyzeQV(char*, bool&, bool&, bool&)’:
fastq-utilities/fastqAnalyze.C:295:30: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fgets(A, MAX_READ_LEN, F);
                              ^
fastq-utilities/fastqAnalyze.C:296:30: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fgets(B, MAX_READ_LEN, F);
                              ^
fastq-utilities/fastqAnalyze.C:297:30: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fgets(C, MAX_READ_LEN, F);
                              ^
fastq-utilities/fastqAnalyze.C:298:30: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fgets(D, MAX_READ_LEN, F);  chomp(D);
                              ^
fastq-utilities/fastqAnalyze.C: In function ‘void doTransformQV(char*, char*, bool, bool, bool)’:
fastq-utilities/fastqAnalyze.C:407:30: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fgets(A, MAX_READ_LEN, F);
                              ^
fastq-utilities/fastqAnalyze.C:408:30: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fgets(B, MAX_READ_LEN, F);
                              ^
fastq-utilities/fastqAnalyze.C:409:30: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fgets(C, MAX_READ_LEN, F);
                              ^
fastq-utilities/fastqAnalyze.C:410:30: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fgets(D, MAX_READ_LEN, F);  chomp(D);

**Comment by brianwalenz** [comment]
Upgrade to gcc 6, 7 or 8, or remove the overlapAlign.mk line from `src/main.mk` (line 202).
```
		\
                overlapAlign/overlapAlign.mk \
		\
```
this isn't used for normal assemblies.

Leaving open until I fix for real.

**Comment by bestweicheng** [comment]
remove the line. Success!  thank you！

**Comment by brianwalenz** [comment]
Fixed in 093a51f41fcb7029a81dfd7663ee5aa4e44e2110.
