### ISSUE TITLE
Need helps on triobinning scripts run

### ISSUE THREAD

**Issue by ligang1978** [marbl/canu#1384]
I read you paper ‘De novo assembly of haplotype-resolved genomes with trio binning’, which is a great work and will give a lot help to our current project. I am try to apply your software and method to make some test on our data. 
         I got some problem to use triobinning scripts and send this mail to ask whether I can have your kind help on it. 
        My illumine data of one parent is about 70 Gb, the other is about 90Gb. After I tried command 'meryl -threads 16 -B -C -m 32 -s **.fas  -o **' , I always got the error massage 'Segmentation fault (core dumped)'. But if I just cut about 5Gb from the original data, this run can be done.
     Need helps to fix this. Thanks a lot.

**Comment by skoren** [comment]
That looks like you're running by hand rather than letting Canu split the data. Update to Canu 1.8 and run trio binning as on the quick start example.

**Comment by ligang1978** [comment]
Hi, thanks for the response.  I used the Canu1.8 version  , meryl looks like can not deal with the big input data, but small size works.  Also, in the compiled binary executable package (Linux-amd64 folder, release with 1.8 download),  program meryl does not accept the Sample.sh parameters. 

To follow the Sample.sh, I recompiled code (see below) using the same command. But problem is given by the first meryl line, big illumine data report error  'Segmentation fault (core dumped)

To run one line by one line, or bash/shall file run, the first meryl command flied.

# build code used for assembly
# cd ../canu/src
# make -j8
# cd -

# build code used to count kmers and to subtract kmer sets
# cd ../meryl/src
# make -j8
# cd -

# count kmers for both parent strains
../meryl/bin/meryl -threads 16 -B -C -m 16 -s Mydata-p1.fasta -o Mydata-p1   

../meryl/*/bin/meryl -threads 16 -B -C -m 16 -s Mydata-p2.fasta -o Mydata-p2

**Comment by skoren** [comment]
Meryl in canu 1.8 is completely different so does not have the same parameters and can deal with large input sizes. There is no sample.sh in Canu, you're looking at the trioBinning repo which is deprecated in favor of Canu 1.8. You no longer have to run meryl manually. Follow the example on the Canu quick start guide as I said before: https://canu.readthedocs.io/en/latest/quick-start.html#trio-binning-assembly which will run meryl and binning for you as part of the canu pipeline.

**Comment by skoren** [comment]
Idle.
