### ISSUE TITLE
Canu 1.8 jobs fail in HPC environment

### ISSUE THREAD

**Issue by ArnieBerg** [marbl/canu#1385]
I am using Canu 1.8 running nanopore samples on a (Red Hat) High-Performance Cluster managed by slurm.  Inexplicably some jobs with large samples run successfully, others with smaller samples run with various errors.  Additionally, all these samples run successfully in a non-slurm, desktop environment under Ubuntu.

I need help to know how to set the slurm environment to avoid these errors.  One example to illustrate show the error reported in the job submitted through sbatch:

[canu.15.txt](https://github.com/marbl/canu/files/3278788/canu.15.txt)

The failing job that reports the slurm error is:

[overlap.292541_2.txt](https://github.com/marbl/canu/files/3278769/overlap.292541_2.txt)

Checking internal slurm stats indicates that this job was allocated only 512M of memory which likely caused the failure.  The slurm submission script is:

[canu.txt](https://github.com/marbl/canu/files/3278779/canu.txt)

**Comment by skoren** [comment]
Canu reports it should be using 4gb for these jobs:
```
-- Grid:  obtovl     4 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl     4 GB    8 CPUs  (overlap detection)
```
so it's requesting 512 * 8 or 4gb. If somehow this is not being scaled by cores, that would explain the error. What is the submit script for the overlap job look like (```overlap.jobSubmit*.sh```).

**Comment by ArnieBerg** [comment]
Hi Sergey,

Thanks for your response.  I have attached the script file where the error occurred.  I hope you can indicate what I need to do differently to run in this environment.  

Arnie

**Comment by skoren** [comment]
The email attachments don't come through GitHub issues, can you upload the file like you did before instead.

**Comment by ArnieBerg** [comment]
Here is the script reporting the error:

[overlap.txt](https://github.com/marbl/canu/files/3281488/overlap.txt)

**Comment by skoren** [comment]
That's the actual overlap job script, there should also be a submit script which submits this overlap job to the grid, it has jobSubmit in the name. That's the one I wanted to see.

**Comment by ArnieBerg** [comment]
Here is the content of overlap.jobSubmit-01.sh:

#!/bin/sh

sbatch \
  --mem-per-cpu=512m --cpus-per-task=8 --time=240:00:00 -o overlap.%A_%a.out \
  -D `pwd` -J "obtovl_Ecoli_iso_808" \
  -a 1-2 \
  ./overlap.sh 0 \
> ./overlap.jobSubmit-01.out 2>&1

**Comment by skoren** [comment]
That looks like it is correctly requesting 512m per cpu, are you sure the job was only allocated 512m total? If that's the case, your slurm system is not behaving correctly and you'll likely have issues in other steps too where the memory will be under-requested.

I think what probably happened is Canu used more than 4gb for this job causing it to get killed. Increasing the default memory (```utgovlMemory=8 obtovlMemory=8```) should work around it.

**Comment by ArnieBerg** [comment]
This is discouraging.  I bumped the memory request to 8Gb and verified that it was actually in the job submission, 

-- Grid:  obtovl     8 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl     8 GB    8 CPUs  (overlap detection)

but the same sample failed again.  Then I re-ran a difference sample (733) that ran successfully the first time I ran it, but it failed too.  

-- BEGIN TRIMMING
--
--
-- Creating overlap store trimming/E.coli_iso_733.ovlStore using:
--      2 buckets
--      2 slices
--        using at most 2 GB memory each
--
-- Overlap store sorting jobs failed, tried 2 times, giving up.
--   job trimming/E.coli_iso_733.ovlStore.BUILDING/0001 FAILED.
--   job trimming/E.coli_iso_733.ovlStore.BUILDING/0002 FAILED.

I ran it a second time and it failed with a different error in a different place.

-- BEGIN ASSEMBLY
--
--
-- Creating overlap store unitigging/Ecoli_iso_733.ovlStore using:
--      2 buckets
--      2 slices
--        using at most 2 GB memory each
--
-- Overlap store sorting jobs failed, tried 2 times, giving up.
--   job unitigging/Ecoli_iso_733.ovlStore.BUILDING/0001 FAILED.
--   job unitigging/Ecoli_iso_733.ovlStore.BUILDING/0002 FAILED.

What is going on?  I'd like to get to the bottom of this.  What information do you need to diagnose this further?

**Comment by skoren** [comment]
I think it's a combination of Canu being overly parsimonious with its grid request and your grid being overzealous at killing memory exceeding jobs. The proper solution is for Canu to request more memory for these jobs, I think the memory tolerance is improved post 1.8.

Your previous run had chosen 4gb for everything, now it restricted itself to 2gb which is quite low. You've got plenty of high-memory nodes, so I'd increase these small jobs in your script (```ovsMemory=8 ovbMemory=8 oeaMemory=8```). If that works more consistently you can make a canu.defaults file in the canu bin directory with these options so they're always set by default for all runs.

**Comment by ArnieBerg** [comment]
I threw the 808 sample back in the oven with your suggestions and got much farther, ending with the error below.  Please explain what this means:

-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_181' (from 'java') with -d64 support.
-- Detected gnuplot version '5.0 patchlevel 3   ' (from 'gnuplot') and image format 'png'.
-- Detected 16 CPUs and 31 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /opt/software/slurm/bin/sinfo.
-- Detected Slurm with 'MaxArraySize' limited to 1000 jobs.
-- 
-- Found   2 hosts with  32 cores and  244 GB memory under Slurm control.
-- Found  91 hosts with  16 cores and   30 GB memory under Slurm control.
-- Found  32 hosts with  40 cores and  185 GB memory under Slurm control.
-- Found   1 host  with  48 cores and 2000 GB memory under Slurm control.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl      7 GB    4 CPUs  (k-mer counting)
-- Grid:  hap        7 GB    4 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap    6 GB    8 CPUs  (overlap detection with mhap)
-- Grid:  obtovl     8 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl     8 GB    8 CPUs  (overlap detection)
-- Grid:  ovb        8 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs        8 GB    1 CPU   (overlap store sorting)
-- Grid:  red        7 GB    4 CPUs  (read error detection)
-- Grid:  oea        8 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat       16 GB    4 CPUs  (contig construction with bogart)
-- Grid:  gfa        8 GB    4 CPUs  (GFA alignment and processing)
--
-- In 'Ecoli_iso_808.seqStore', found Nanopore reads:
--   Raw:        39514
--   Corrected:  2743
--   Trimmed:    2731
--
-- Generating assembly 'Ecoli_iso_808' in '/home/agb465/data/staging/Ecoli_iso_808'
--
-- Parameters:
--
--  genomeSize        4000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1200 ( 12.00%)
--    utgOvlErrorRate 0.1200 ( 12.00%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1200 ( 12.00%)
--    utgErrorRate    0.1200 ( 12.00%)
--    cnsErrorRate    0.2000 ( 20.00%)
--
--
-- BEGIN ASSEMBLY
--
--
-- Bogart failed, tried 2 times, giving up.
--

ABORT:
ABORT: Canu 1.8
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT: Disk space available:  7358.953 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (unitigging/4-unitigger/unitigger.err):
ABORT:
ABORT:   
ABORT:   ==> BREAK REPEATS.
ABORT:   
ABORT:   computeErrorProfiles()-- Computing error profiles for 98 tigs, with 4 threads.
ABORT:   computeErrorProfiles()-- Finished.
ABORT:   markRepeatReads()-- Found 0 confused edges.
ABORT:   
ABORT:   ==> CLEANUP MISTAKES.
ABORT:   
ABORT:   splitDiscontinuous()-- Tested 22 tigs, split none.
ABORT:   promoteToSingleton()-- Moved 207 unplaced reads to singleton tigs.
ABORT:   dropDead()-- Modified 1 tigs.  Dropped 0 first and 1 last reads, 0 tigs had both reads dropped.
ABORT:   splitDiscontinuous()-- Tested 22 tigs, split none.
ABORT:   promoteToSingleton()-- Moved 0 unplaced reads to singleton tigs.
ABORT:   
ABORT:   ==> CLEANUP GRAPH.
ABORT:   
ABORT:   AssemblyGraph()-- rebuilding
ABORT:   AssemblyGraph()-- building reverse edges.
ABORT:   AssemblyGraph()-- rebuild complete.
ABORT:   AssemblyGraph()-- filtering edges
ABORT:   AssemblyGraph()-- 2636 contig edges and 0 unitig edges.
ABORT:   AssemblyGraph()-- 0 bubble edges and 0 repeat edges.
ABORT:   AssemblyGraph()-- 143 middle contig edges filtered from 127 reads.
ABORT:   AssemblyGraph()-- 0 repeat end edges filtered from 0 reads.
ABORT:   AssemblyGraph()-- 143 repeat edges (not output).
ABORT:   AssemblyGraph()-- 5 bubble edges.
ABORT:   AssemblyGraph()-- 5 intersecting edges (from the end of a tig to somewhere else).
ABORT:   
ABORT:   ==> GENERATE OUTPUTS.
ABORT:   
ABORT:   AssemblyGraph()-- generating './Ecoli_iso_808.final.assembly.gfa'.
ABORT:   AssemblyGraph()-- Found 0 edges to unassembled contigs.
ABORT:   AssemblyGraph()--        0 bubble placements
ABORT:   AssemblyGraph()--        0 repeat placements
ABORT:   
ABORT:   AssemblyGraph()-- Intratig edges:            0 contained         0 5'         0 3' (in both contig and unitig)
ABORT:   AssemblyGraph()-- Contig only edges:       280 contained      2344 5'      2333 3'
ABORT:   AssemblyGraph()-- Unitig only edges:         0 contained         0 5'         0 3'
ABORT:   AssemblyGraph()-- Intercontig edges:         0 contained         1 5'         4 3' (in neither contig nor unitig)
ABORT:   AssemblyGraph()-- generating './Ecoli_iso_808.contigs.gfa'.
ABORT:   
ABORT:   ==> GENERATE UNITIGS.
ABORT:   
ABORT:   computeErrorProfiles()-- Computing error profiles for 307 tigs, with 4 threads.
ABORT:   computeErrorProfiles()-- Finished.
ABORT:   splitDiscontinuous()-- Tested 20 tigs, split none.
ABORT:   AssemblyGraph()-- generating './Ecoli_iso_808.unitigs.gfa'.
ABORT:   
ABORT:   Bye.
ABORT:

**Comment by skoren** [comment]
I don't see an error in that log, what do you have in the unitigging/4-unitigger folder? What happens if you resume Canu?

**Comment by ArnieBerg** [comment]
I didn't see any output files that indicated an error in the 4-unitigger folder, so when I restarted the Canu job, it ran to completion.
