### ISSUE TITLE
didn't find any reads in store 'haplotype/XXXX.gkpStore'

### ISSUE THREAD

**Issue by rozaimirazali** [marbl/canu#1386]
Hello.

The Meryl jobs for the parental reads have been completed finished. Now I am getting an error about not finding any reads in the gkpStore of the child.

```
-- Meryl finished successfully with threshold 19 to 104 for haplotypeMat.
-- Meryl finished successfully with threshold 17 to 97 for haplotypePat.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  cor       88 GB  140 CPUs  (read correction)
--

ABORT:
ABORT: Canu 1.7.1
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   didn't find any reads in store 'haplotype/MNDY0206.gkpStore'?.
ABORT:
```

This is the content of the MNDY0206.gkpStore folder. If there are issues then I assume they will show up in the errorLog file, right?

```
[rmohamadrazali@hpclogin1 TrioCANU_2Jun2019]$ ls -ltrh MNDY0206.gkpStore
total 29G
-rw-rw-r-- 1 rmohamadrazali sysbio    0 Jun  2 11:58 errorLog
-rw-rw-r-- 1 rmohamadrazali sysbio  336 Jun  2 12:25 libraries
-rw-rw-r-- 1 rmohamadrazali sysbio 350M Jun  2 12:25 reads
-rw-rw-r-- 1 rmohamadrazali sysbio   88 Jun  2 12:25 info
-rw-rw-r-- 1 rmohamadrazali sysbio  436 Jun  2 12:25 info.txt
-rw-rw-r-- 1 rmohamadrazali sysbio  28G Jun  2 12:25 blobs
-rw-rw-r-- 1 rmohamadrazali sysbio 616M Jun  2 12:25 readNames.txt
-rw-rw-r-- 1 rmohamadrazali sysbio  368 Jun  2 12:25 load.dat
-rw-rw-r-- 1 rmohamadrazali sysbio  188 Jun  2 12:25 libraries.txt
-rw-rw-r-- 1 rmohamadrazali sysbio  49M Jun  2 12:26 readlengths-hap.dat
-rw-rw-r-- 1 rmohamadrazali sysbio  572 Jun  2 12:26 readlengths-hap.gp

```

Any idea why it is saying there are no reads?

Thank you.

**Comment by skoren** [comment]
Canu 1.7.1 had some early support for trio binning, I'd first suggest upgrading to 1.8 and running that to see if you have an error. There have been several bug fixes.

**Comment by rozaimirazali** [comment]
So ver 1.8 is backward compatible? I don't need to re-run all the previous steps, right ?

**Comment by skoren** [comment]
Not at all backwards compatible so you have to run from the beginning.

**Comment by skoren** [comment]
Looking at the 1.7.1 code, the store it is complaining about is your input reads that you want to bin. Do these happen to be corrected reads? What's the Canu command you ran and what is the contents of info.txt?

**Comment by rozaimirazali** [comment]
> Do these happen to be corrected reads?

Yes, they are corrected and trimmed reads.

> What's the Canu command you ran...

bsub -e triocanu_9jun2019.err -o triocanu_9jun2019.out -q normal -P CANU -J assembly_TrioCANU "trioCanu \
-assemble \
-p MNDY0206 \
-d TrioCANU_2Jun2019 \
minThreads=140 \
minMemory=32g \
genomeSize=3g \
stopOnReadQuality=false \
useGrid=true \
gridEngine=lsf \
'gridOptionsExecutive=-M 600000' 'gridOptionsMeryl=-M 600000' gridOptions='-R rusage[mem=400GB] -e MNDY0206.assembly.e -o MNDY0206.assembly.o -q fatnode -P assembly -J denovo_ref_assembly' \
gnuplotTested=true \
-haplotypeMat maternal/0200304480_R1.fastq.gz maternal/0200304480_R2.fastq.gz \
-haplotypePat paternal/0200304560_R1.fastq.gz paternal/0200304560_R2.fastq.gz \
-pacbio-corrected correction_trimming_MNDY0206/MNDY0206.trimmedReads.fasta.gz"

> ...what is the contents of info.txt?

gkMagic            = 0x504b473a756e6163
gkVersion          = 0x0000000000000002

gkLibrarySize      = 168
gkReadSize         = 40
gkMaxLibrariesBits = 6
gkLibraryNameSize  = 128
gkMaxReadBits      = 37
gkMaxReadLenBits   = 21

numLibraries       = 1
numReads           = 9165466

numRawReads        = 0
numCorrectedReads  = 9165466
numTrimmedReads    = 0

numRawBases        = 0
numCorrectedBases  = 112048361930
numTrimmedBases    = 0

> Not at all backwards compatible so you have to run from the beginning

Do you mean all the way from Correction stage or just the Triocanu assembly? 

Thanks!

**Comment by skoren** [comment]
Are these PacBIo HiFI reads? If not you should not be trio-binning corrected reads, that is not what you want. How did you get corrected reads, running both haplotypes together to be corrected by Canu? That is not correct as corrected reads are not phased so you can't properly haplotype them. The trio binning will run first in the pipeline and bin the raw data and then correct it using only the reads from the correct haplotype. So you'll need to start from scratch anyway if you corrected before binning.

I will keep this issue open since right now the same error will happen if you provide HiFi reads as pacbio-corrected and we should allow binning those reads. As a workaround, they can be provided as raw reads, haplotyped with stopAfter=haplotype, and then assembled as pacbio-corrected for each bin.

**Comment by rozaimirazali** [comment]
> Are these PacBIo HiFI reads? If not you should not be trio-binning corrected reads, that is not what you want.

No, they are Pacbio Sequel reads.

> How did you get corrected reads, running both haplotypes together to be corrected by Canu? 

I ran the 3 steps (correction, trim and assemble) in consequent order on the Child Pacbio raw reads. I combined the corrected + trimmed child reads together with the Hiseq reads from maternal and paternal during the -assemble as i showed in my previous reply.

Is this wrong? Should I just run triocanu using the raw Pacbio reads of the child with the hiseq from the parents?

**Comment by skoren** [comment]
Yes this is wrong, trio binning is meant to run first to avoid mis-correcting or mis-assembling the two haplotypes together. The corrected and trimmed reads are also the same thing so combining them just duplicates all your data.

**Comment by rozaimirazali** [comment]
I see. Thanks for the explanation.

Initially, I thought of assembling using normal Canu as per the Canu Quick Start.

Then I received the parental short reads in the last couple of months so I thought I can combine my corrected and trimmed reads with the short reads of the parents.

Thanks again!

**Comment by skoren** [comment]
Documented in quickstart for trio, will close and store as feature request
