### ISSUE TITLE
Unitigger failed - bogart() [0x404609]

### ISSUE THREAD

**Issue by fbemm** [marbl/canu#139]
I got the following error message:

canu failed with 'failed to generate unitigs.  Made 2 attempts, jobs still failed'.

Unitigger.err says:

Graph  error threshold  = 0.150 (15.000%)
Max    error threshold  = 0.150 (15.000%)

Minimum overlap length = 500 bases

number of threads     = 8 (command line)

FragmentInfo()-- Loading fragment information for 1172683 fragments and 1 libraries from cache 'canu/.//unitigging/4-unitigger/HD1.00.fragmentInfo'

OverlapCache()-- limited to 40960MB memory (user supplied).
PHYS_PAGES = 24749587
PAGE_SIZE  = 4096
MEMORY     = 101374308352
OverlapCache()--      13MB for fragment data.
OverlapCache()--      17MB for best edges.
OverlapCache()--      31MB for unitig layouts.
OverlapCache()--       0MB for unitigs.
OverlapCache()--       8MB for id maps.
OverlapCache()--      13MB for overlap cache pointers.
OverlapCache()--      56MB for overlap cache initial bucket.
OverlapCache()--     256MB for overlap cache thread data.
OverlapCache()--       4MB for number of overlaps per read.
OverlapCache()--       0MB for other processes.
OverlapCache()-- ---------
OverlapCache()--     401MB for data structures (sum of above).
OverlapCache()--   40558MB available for overlaps.

OverlapCache()-- Loading number of overlaps per fragment.
OverlapCache()--  Initial guess at _maxPer=2266 (max of 5124) from (memLimit=42528409398 - memUsed=0) / (numFrags=1172683 * sizeof(OVL)=16)
OverlapCache()-- _maxPer=   2266 (numBelow=1170571 numEqual=2 numAbove=2110 totalLoad=166029272 -- 0 + 166029272 = 2656468352 <? 42528409398
OverlapCache()--                 (38024 MB free, adjust by 1181040)
OverlapCache()-- _maxPer=   5124 (numBelow=1172682 numEqual=1 numAbove=0 totalLoad=167291912 -- 0 + 167291912 = 2676670592 <? 42528409398

OverlapCache()-- blockSize        = 41531649 (633MB)

OverlapCache()-- _maxPer          = 5124 overlaps/reads
OverlapCache()-- numBelow         = 1172682 reads (all overlaps loaded)
OverlapCache()-- numEqual         = 1 reads (all overlaps loaded)
OverlapCache()-- numAbove         = 0 reads (some overlaps loaded)
OverlapCache()-- totalLoad        = 167291912 overlaps (100.00%)

OverlapCache()-- availForOverlaps = 40558MB
OverlapCache()-- totalMemory      = 0MB for organization
OverlapCache()-- totalMemory      = 2552MB for overlaps
OverlapCache()-- totalMemory      = 2552MB used

OverlapCache()-- Loading overlap information
OverlapCache()-- Loading overlap information: overlaps processed          148 (000.00%) loaded          145 (000.00%) (at read iid 1)
OverlapCache()-- Loading overlap information: overlaps processed    142599375 (085.24%) loaded    141231731 (084.42%) (at read iid 1000246)
OverlapCache()-- Loading overlap information: overlaps processed    167291912 (100.00%) loaded    165684416 (099.04%)
setLogFile()-- Now logging to 'canu/.//unitigging/4-unitigger/HD1.00.002.bestOverlapGraph'
setLogFile()-- Now logging to 'canu/.//unitigging/4-unitigger/HD1.00.004.ChunkGraph'
setLogFile()-- Now logging to 'canu/.//unitigging/4-unitigger/HD1.00.005.buildUnitigs'
setLogFile()-- Now logging to 'canu/.//unitigging/4-unitigger/HD1.00.006.placeContains'
Computing arrival rates for 29862 unitigs using 8 threads.
Computing error profiles for 29862 unitigs using 8 threads.
Computing error profiles - FINISHED.
setLogFile()-- Now logging to 'canu/.//unitigging/4-unitigger/HD1.00.007.popBubbles'
Computing error profiles for 29862 unitigs using 8 threads.
Computing error profiles - FINISHED.
setLogFile()-- Now logging to 'canu/.//unitigging/4-unitigger/HD1.00.008.markRepeatReads'
Computing error profiles for 29862 unitigs using 8 threads.
Computing error profiles - FINISHED.
bogart: bogart/AS_BAT_Unitig_AddFrag.C:87: void Unitig::addFrag(ufNode, int, bool): Assertion `node.position.end >= 0' failed.

Failed with 'Aborted'

Backtrace (mangled):

canu/code/canu/Linux-amd64/bin/bogart[0x5129ad]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10340)[0x7f3d51d54340]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x39)[0x7f3d519b5cc9]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7f3d519b90d8]
/lib/x86_64-linux-gnu/libc.so.6(+0x2fb86)[0x7f3d519aeb86]
/lib/x86_64-linux-gnu/libc.so.6(+0x2fc32)[0x7f3d519aec32]
canu/code/canu/Linux-amd64/bin/bogart[0x5105e5]
canu/code/canu/Linux-amd64/bin/bogart[0x450b5e]
canu/code/canu/Linux-amd64/bin/bogart[0x457a35]
canu/code/canu/Linux-amd64/bin/bogart[0x40399f]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f3d519a0ec5]
canu/code/canu/Linux-amd64/bin/bogart[0x404609]

Backtrace (demangled):

[0] canu/code/canu/Linux-amd64/bin/bogart() [0x5129ad]
[1] /lib/x86_64-linux-gnu/libpthread.so.0::(null) + 0x10340  [0x7f3d51d54340]
[2] /lib/x86_64-linux-gnu/libc.so.6::(null) + 0x39  [0x7f3d519b5cc9]
[3] /lib/x86_64-linux-gnu/libc.so.6::(null) + 0x148  [0x7f3d519b90d8]
[4] /lib/x86_64-linux-gnu/libc.so.6::(null) + 0x2fb86  [0x7f3d519aeb86]
[5] /lib/x86_64-linux-gnu/libc.so.6::(null) + 0x2fc32  [0x7f3d519aec32]
[6] canu/code/canu/Linux-amd64/bin/bogart() [0x5105e5]
[7] canu/code/canu/Linux-amd64/bin/bogart() [0x450b5e]
[8] canu/code/canu/Linux-amd64/bin/bogart() [0x457a35]
[9] canu/code/canu/Linux-amd64/bin/bogart() [0x40399f]
[10] /lib/x86_64-linux-gnu/libc.so.6::(null) + 0xf5  [0x7f3d519a0ec5]
[11] canu/code/canu/Linux-amd64/bin/bogart() [0x404609]

GDB:

Aborted (core dumped)

Running the job on a big memory machine does not solve the problem. I also pulled and compiled canu's most recent version. 

Any help would be great!

Thx,
F

**Comment by brianwalenz** [comment]
Should be fixed now.  Close the issue if it works for you.

Commit d2e9696a7f3eae109f85da174027263ecb144566.

**Comment by fbemm** [comment]
Worked like charm! Thx a lot, F
