### ISSUE TITLE
We are going to sequence 60 genome assembly and we want to finish one genome assembly within 10 days. plz suggest me best server configuration.

### ISSUE THREAD

**Issue by nagendranipgr** [marbl/canu#1393]
We are going to sequence 60 genome assembly and we want to finish one genome assembly within 10 days. plz suggest me best server configuration.

**Comment by skoren** [comment]
Insufficient information, coverage, genome size, repetitiveness, sequencing type will all affect runtime. The FAQ lists some common runtimes for various genomes.

**Comment by nagendranipgr** [comment]
Coverage 60x
Genome size : 300mb to 3 gb.
All are Eukaryote Mostly  plants.
Sequencing type:  Nanopore or pacbio

**Comment by skoren** [comment]
That's still an extremely large range and type of technology. Figure a 40x human takes about 30k cpu hours from pacbio and 100k from nanopore. Plants tend to be more repetitive so will likely take longer. You can back-compute from those numbers to get the cores you'd need to have to finish in 10 days, assuming you're doing one genome at a time.  Canu is also available from cloud providers so you could run on their systems too.
