### ISSUE TITLE
Not getting good assembly

### ISSUE THREAD

**Issue by nagendranipgr** [marbl/canu#1394]
I'm doing genome assembly for rice it's genome size is 430mb. 
Sequencing type is Nanopore .
Raw Reads 28.06 Gb in bp
Coverage 60x

Raw read stat

 total no of seq :     5716181        
total length  :           28.06Gb
Min length  :            73bp 
Max length :           108kb  
Average length:.   4.9kb 
                                                 

1.We  run the correction step with default parameters but data decrease 3 fold  (16.94gb ) does it's good data?

2. After correction I ran the trim-assembly  in 3 differents way
1st 
default parameters

2nd 
genomeSize=430m 
useGrid=false 
correctedErrorRate=0.14544 minReadLength=1000 
 minOverlapLength=1000

And 3rd
correctedErrorRate=0.14544 minReadLength=500 
 minOverlapLength=500

 we complete 2nd step minReadLength=1000 
 minOverlapLength=1000 but we didn't get good assembly stat 

canu parameters: 

min read length - 1Kb
min overlap length - 1Kb 
                                                                               
Total no of contigs : 2348                                                        
Total length           : 390Mb                                                        
Largest contig       : 3.21Mb                                                         
avg                      : 166.20kb                                                          
N50                      : 432.87kb

We want n50 around 1mb and contigs around 500 . Should I have to wait complete  default parameter assembly or change parameters for improve our assembly.
Thank you in advance

**Comment by nagendranipgr** [comment]
Does it good way to ran canu in default parameters.

**Comment by skoren** [comment]
We almost always run with default parameters. There are other suggestions depending on data on the FAQ. The canu report provides lots of information on your sequencing data and the assembly, you should post that.

That said, you shouldn't set an expectation for NG50/contig count before having an assembly. It's going to depend on your genome complexity (heterozygosity, repeat content), sequencing (read length, quality) and other factors. I bet you can reach your target contig count by just filtering contigs <50kb but that will filter some, likely repetitive, parts of your genome.

**Comment by nagendranipgr** [comment]
canu report  as you ask plz suggest what to do ?

[canuAssembly_1k_1k_barcode11_report.txt](https://github.com/marbl/canu/files/3305346/canuAssembly_1k_1k_barcode11_report.txt)

**Comment by nagendranipgr** [comment]
I'm attaching the nohup.out file for default parameters 
[nohup_default parameters.txt](https://github.com/marbl/canu/files/3305377/nohup_default.parameters.txt)

**Comment by skoren** [comment]
Neither one of these reports shows the original input data and correction output, how did you generate corrected reads?

In general, the correction seems to be OK with about 40x data left after trimming and a good k-mer peak at the expected coverage. I think the main issue is the relatively short read length, most of the reads are <7kb (and I expect before correction even shorter) so that's going to limit your ability to resolve large repeats.

**Comment by nagendranipgr** [comment]
actually i attached the nohup command output not original reports now I'm attaching the original reports with defaults parameters.   

**this is my command for correction reads.**  


canu/Linux-amd64/bin/canu -correct -d canu_correct_barcode11 -p canuAssembly genomeSize=430m useGrid=false -nanopore-raw demultiplex/barcode11.fastq
[canu_correctReads_report.txt](https://github.com/marbl/canu/files/3320580/canu_correctReads_report.txt)


**this is for trim and assembly**
canu/Linux-amd64/bin/canu -trim-assemble -d canu_assembly/ -p canuAssembly genomeSize=430M useGrid=false -nanopore-corrected canuAssembly.correctedReads.fasta.gz
[canu_trim_assembly_report.txt](https://github.com/marbl/canu/files/3320581/canu_trim_assembly_report.txt)

**Comment by skoren** [comment]
Yeah as I expected, your reads are quite short, with an average of only 5kb and most of them <5kb in the histogram. The correction runs fine with the default, you end up with 40x coverage which is what Canu targets by default and your average read length increases, essentially Canu threw out the short reads you had and corrected the best long reads available. 

The main issue is the short read length which is limiting your assembly. You could try the low coverage parameters (```corMhapSensitivity=normal corMinCoverage=0 correctedErrorRate=0.15```) but I doubt it will help much.
