### ISSUE TITLE
Don't panic, but a mostly harmless error occurred and Canu stopped

### ISSUE THREAD

**Issue by ZelalemH** [marbl/canu#1395]
Hello there, I was assembling a bacterial genome with estimated 1.2 m GS, and I have got the following error. for this work I am using a Mac with 16GB memory, I am not sure how to increase the available memory size for Canu to compute. I thought Canu automatically calculate and optimize the required memory for individual jobs?,   is there any way to do that by including in the Canu command 

```
___
-- Finished on Wed Jun 19 18:03:50 2019 (fast as lightning) with 171.978 GB free disk space
----------------------------------------
--                             original      original
--                            raw reads     raw reads
--   category                w/overlaps  w/o/overlaps
--   -------------------- ------------- -------------
--   Number of Reads              60428          9553
--   Number of Bases         2750579932      16367667
--   Coverage                  2292.150        13.640
--   Median                        7842          1248
--   Mean                         45518          1713
--   N50                         139884          1534
--   Minimum                       1000             0
--   Maximum                     936485        138527
--   
--                                        --------corrected---------  ----------rescued----------
--                             evidence                     expected                     expected
--   category                     reads            raw     corrected            raw     corrected
--   -------------------- -------------  ------------- -------------  ------------- -------------
--   Number of Reads               4158             79            79          39978         39978
--   Number of Bases          405348820       48278113      48277086     2177407568    1167230411
--   Coverage                   337.791         40.232        40.231       1814.506       972.692
--   Median                       46533         586189        586176          21060          3435
--   Mean                         97486         611115        611102          54465         29196
--   N50                         300519         603397        603384         141112        203178
--   Minimum                       1402         521216        521203           1014          1001
--   Maximum                     936485         906149        906136         458970        458957
--   
--                        --------uncorrected--------
--                                           expected
--   category                       raw     corrected
--   -------------------- ------------- -------------
--   Number of Reads              29924         29924
--   Number of Bases          541261918     226240073
--   Coverage                   451.052       188.533
--   Median                        1575             0
--   Mean                         18087          7560
--   N50                         119414        350614
--   Minimum                          0             0
--   Maximum                     936485        936472
--   
--   Maximum Memory          9383407730
-- Finished stage 'cor-filterCorrectionLayouts', reset canuIteration.
-- Using overlaps no worse than 0.5 fraction error for correcting reads (from corErrorRate parameter).
--
-- Configuring correction jobs:
--   Jobs limited to 8 GB per job (via option corMemory).
--   Reads estimated to need at most 8.738 GB for computation.
--   Leaving -0.737 GB memory for read data.

ABORT:
ABORT: Canu snapshot v1.8 +261 changes (r9471 093a51f41fcb7029a81dfd7663ee5aa4e44e2110)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   not enough memory for correction; increase corMemory.
ABORT:
```

**Comment by skoren** [comment]
You can set either minMemory or corMemory to 16 when you run canu (```corMemory=16```), that should let it run this step. Canu tries to limit memory for small genomes in addition to checking your resources which is why it picked 8 here (otherwise it can only run 1 job at a time).

**Comment by ZelalemH** [comment]
thanks, that seems to resolve the earlier issue but I am encountering another one. look below 
____
-- Using overlaps no worse than 0.5 fraction error for correcting reads (from corErrorRate parameter).
-- Finished stage 'cor-generateCorrectedReadsConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'cor' concurrent execution on Thu Jun 20 11:33:24 2019 with 148.908 GB free disk space (5 processes; 1 concurrently)

    cd correction/2-correction
    ./correctReads.sh 1 > ./correctReads.000001.out 2>&1
    ./correctReads.sh 2 > ./correctReads.000002.out 2>&1
    ./correctReads.sh 3 > ./correctReads.000003.out 2>&1
    ./correctReads.sh 4 > ./correctReads.000004.out 2>&1
    ./correctReads.sh 5 > ./correctReads.000005.out 2>&1

-- Finished on Thu Jun 20 11:33:37 2019 (13 seconds) with 148.908 GB free disk space
----------------------------------------
--
-- Read correction jobs failed, retry.
--   job 2-correction/results/0001.cns FAILED.
--   job 2-correction/results/0002.cns FAILED.
--   job 2-correction/results/0003.cns FAILED.
--   job 2-correction/results/0004.cns FAILED.
--   job 2-correction/results/0005.cns FAILED.
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'cor' concurrent execution on Thu Jun 20 11:33:37 2019 with 148.908 GB free disk space (5 processes; 1 concurrently)

    cd correction/2-correction
    ./correctReads.sh 1 > ./correctReads.000001.out 2>&1
    ./correctReads.sh 2 > ./correctReads.000002.out 2>&1
    ./correctReads.sh 3 > ./correctReads.000003.out 2>&1
    ./correctReads.sh 4 > ./correctReads.000004.out 2>&1
    ./correctReads.sh 5 > ./correctReads.000005.out 2>&1

-- Finished on Thu Jun 20 11:33:47 2019 (10 seconds) with 148.907 GB free disk space
----------------------------------------
--
-- Read correction jobs failed, tried 2 times, giving up.
--   job 2-correction/results/0001.cns FAILED.
--   job 2-correction/results/0002.cns FAILED.
--   job 2-correction/results/0003.cns FAILED.
--   job 2-correction/results/0004.cns FAILED.
--   job 2-correction/results/0005.cns FAILED.
--

ABORT:
ABORT: Canu snapshot v1.8 +261 changes (r9471 093a51f41fcb7029a81dfd7663ee5aa4e44e2110)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:

**Comment by skoren** [comment]
What is in the failing logs of one of the jobs (e.g. ````correctReads.000001.out```)?

**Comment by skoren** [comment]
Any update on this?

**Comment by skoren** [comment]
Idle, likely due to non-ACGT characters (see #1370).
