### ISSUE TITLE
Read coverage (0) is too low to be useful.

### ISSUE THREAD

**Issue by evgisa** [marbl/canu#1399]
Hi, I'm trying to assemble the simulated Nanopore reads from DeepSimulator (https://github.com/lykaust15/DeepSimulator).
The reference sequence is 1000pb length and the coverage is around 50X 
(around 43 reads) with a mapping identity of 0.9.
However, when I run canu I get the following error:

```
-- ERROR:  Read coverage (0) is too low to be useful.
-- ERROR:
-- ERROR:  This could be caused by an incorrect genomeSize or poor quality reads that could not
-- ERROR:  be sufficiently corrected.
```

The command I'm using is the following:

`./bin/canu -p asm -d asm genomeSize=1k minReadLength=500  -nanopore-raw <path of nanopore reads fasta file>`

I've tried to perform a round of just error correction and it works with the same input data, giving as result 21 corrected reads:

`./bin/canu -p r_1 -d r_1 -correct genomeSize=1k correctedErrorRate=0.2 corOutCoverage=500 corMinCoverage=0 corMhapSensitivity=high -nanopore-raw <path of nanopore reads fasta file>`

Could it be a problem of the reads length? Do you have any suggestion?

Thank you!

**Comment by skoren** [comment]
It doesn't make sense to try to assemble 1 kb sequence with nanopore reads, the reads will be longer than the target and Canu will ignore most of their overlaps at the default of 500. How many of your reads are actually over 500 and how many have overlaps over 500 based on your mapping identity? The canu report file will give more information on how many reads are left/have overlaps but I would suggest simulating something at least 10s or 100s of kb to get a realistic example.

**Comment by evgisa** [comment]
First of all thank you for you quick response.
I have 43 reads with length between 1000 and 1099pb but you were right, there are no reads with overlaps over 500. I'll follow your advice and try with longer sequences.

Thank you for your time!
