### ISSUE TITLE
No contig Fasta file

### ISSUE THREAD

**Issue by calvincicha** [marbl/canu#1403]
I recently ran Canu on a algae genome sample sequenced with nanopore technology.
After removing reads less than 1000 bp with canu I still had roughly 50X coverage of my genome. However these reads were relatively small with an N50 of 7kb.

This is the command I used

```
canu -d SLA-04_q100_Canu_assembly -p SLA-04 genomeSize=55m -nanopore-raw /home/calvinc/SLA-04_fast5_original/fastq_skipped+passed/*.fastq
```

I am using 
```
Canu snapshot v1.8 +261 changes (r9471 093a51f41fcb7029a81dfd7663ee5aa4e44e2110)
```

I have been using a linux based computer with 48 cores, and 1tb RAM. no virtual machine or grid.

The program ran well at the beginning. but resulted in error later in the run. 

```
-- Finished stage 'consensusLoad', reset canuIteration.
----------------------------------------
-- Starting command on Tue Jun 25 23:32:17 2019 with 2068.763 GB free disk space

    cd unitigging
    /software/canu/canu/Linux-amd64/bin/tgStoreCoverageStat \
      -S ../SLA-04.seqStore \
      -T  ./SLA-04.ctgStore 2 \
      -s 55000000 \
      -o ./SLA-04.ctgStore.coverageStat \
    > ./SLA-04.ctgStore.coverageStat.err 2>&1

-- Finished on Tue Jun 25 23:32:17 2019 (lickety-split) with 2068.763 GB free disk space
----------------------------------------

ERROR:
ERROR:  Failed with exit code 134.  (rc=34304)
ERROR:

ABORT:
ABORT: Canu snapshot v1.8 +261 changes (r9471 093a51f41fcb7029a81dfd7663ee5aa4e44e2110)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to compute coverage statistics.
ABORT:
ABORT: Disk space available:  2068.763 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (unitigging/SLA-04.ctgStore.coverageStat.err):
ABORT:
ABORT:   read      428368 anchor         0 hang       0       0 position    698729    700788
ABORT:   read      238894 anchor         0 hang       0       0 position    704900    700054 delta    27 at 1891213
ABORT:   read      326711 anchor         0 hang       0       0 position    700449    704718 delta    30 at 1891480
ABORT:   read       16897 anchor         0 hang       0       0 position    701195    703524
ABORT:   read      524212 anchor         0 hang       0       0 position    726964    705583 delta    93 at 1891766
ABORT:   read      600489 anchor         0 hang       0       0 position    726708    706023 delta    95 at 1892688
ABORT:   read      112427 anchor         0 hang       0       0 position    708865    716254 delta    39 at 1893655
ABORT:   read      110599 anchor         0 hang       0       0 position    716482    709770 delta    38 at 1894043
ABORT:   read      258608 anchor         0 hang       0       0 position    717287    710473 delta    28 at 1894419
ABORT:   read       62496 anchor         0 hang       0       0 position    710608    714490 delta    32 at 1894647
ABORT:   read      239460 anchor         0 hang       0       0 position    710647    714286 delta    22 at 1894911
ABORT:   read      370124 anchor         0 hang       0       0 position    720401    710757 delta    29 at 1895123
ABORT:   read      301943 anchor         0 hang       0       0 position    718492    711077 delta    44 at 1895482
ABORT:   read      131370 anchor         0 hang       0       0 position    711097    714504 delta    26 at 1895814
ABORT:   read      144112 anchor         0 hang       0       0 position    711679    718201 delta    26 at 1896044
ABORT:   read      156681 anchor         0 hang       0       0 position    716482    711789 delta    22 at 1896275
ABORT:   read      532105 anchor         0 hang       0       0 position    716445    711863 delta    35 at 1896500
ABORT:   read      203867 anchor         0 hang       0       0 position    718344    711892 delta    28 at 1896803
ABORT:   read      444829 anchor    286813 hang       0       0 position    762474    712231 delta   127 at 1897042
ABORT:   read      184635 anchor         0 hang       0       0 position    717553    712277 delta    18 at 1898262
ABORT:   read      554300 anchor         0 hang       0       0 position    712397    717659 delta    18 at 1898459
ABORT:   read       46407 anchor         0 hang       0       0 position    718304    713052 delta    46 at 1898665
ABORT:   read      258473 anchor         0 hang       0       0 position    713182    714656
ABORT:   read      410946 anchor         0 hang       0       0 position    716709    713785 delta    18 at 1899062
ABORT:   read       69916 anchor         0 hang       0       0 position    714010    718047 delta    28 at 1899236
ABORT:   read      534177 anchor         0 hang       0       0 position    717721    714233 delta    30 at 1899482
ABORT:   read      525815 anchor         0 hang       0       0 position    731148    720903 delta    31 at 1899767
ABORT:   read      364419 anchor         0 hang       0       0 position    730344    721144 delta    43 at 1900138
ABORT:   read      129963 anchor         0 hang       0       0 position    722722    727483 delta    20 at 1900600
ABORT:   read      462213 anchor         0 hang       0       0 position    722813    727767 delta    23 at 1900826
ABORT:   read      246559 anchor         0 hang       0       0 position    727461    723536 delta    12 at 1901079
ABORT:   read      580251 anchor         0 hang       0       0 position    733553    724035 delta    23 at 1901225
ABORT:   read      425281 anchor         0 hang       0       0 position    730348    734742 delta     7 at 1901471
ABORT:   tigend
ABORT:   tgStoreCoverageStat: stores/tgStoreCoverageStat.C:130: double computeRho(tgTig*): Assertion `minBgn == 0' failed.
ABORT:   
ABORT:   Failed with 'Aborted'; backtrace (libbacktrace):
ABORT:   utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   stores/tgStoreCoverageStat.C::130 in _Z10computeRhoP5tgTig()
ABORT:   stores/tgStoreCoverageStat.C::188 in _Z20getGlobalArrivalRateP7tgStoreP8_IO_FILEmb()
ABORT:   stores/tgStoreCoverageStat.C::523 in main()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   Aborted
ABORT:
```
The output in terminal said the program generated 45 contigs spanning 39Mb of genome, but I can not find any contig fasta files in my output folder. I have the `.report` `.seqStore.err` and `seqStore.ssi` files and fasta files of corrected and trimmed reads, but no fasta files for` contigs`, `unitigs`, or  `unassembled`. Could you help explain what this error means and how to generate contig files. I can provide more details or error files if requested/needed.

**Comment by skoren** [comment]
It seems like you have a bad contig in the result that's causing the crash. You could try seeing if you can dump the contigs with the command:
```
/software/canu/canu/Linux-amd64/bin/tgStoreDump -S ../SLA-04.seqStore -T  ./SLA-04.ctgStore 2  -contigs -consensus -fasta  > ../SLA-04.contigs.fasta
```
(from inside the unitigging folder) and see if that runs without errors. You won't have some of the other accessory outputs (like the gfa or the read to contig placement) but you'd have an assembly.

**Comment by calvincicha** [comment]
Ok, when starting the run I did start a command, but accidentally close it, then restart the same command. Perhaps this is the error as you stated that re-running could be an issue. I will try running the program again in a completely new output folder.

**Comment by skoren** [comment]
Don't restart all the way from scratch, at most you need to re-run consensus/unitigging. Try the dump command first. If that does not work you can try removing 4-unitigging, 5-consensus, *.ctgStore, and *.utgStore folders and re-running Canu in the same folder.

**Comment by calvincicha** [comment]
Ok, Thank you for this helpful information. I will try your suggestions.

**Comment by calvincicha** [comment]
Your command worked perfectly and output a contig.fasta file. Thank you. I did also try rerunning this program in a different and new output directory and the same error occurred. So this error doesn't seem to be caused by re-running the program in the same folder more than once. 

With this modified output is there a way to measure the coverage of my different contigs?

Thanks again

**Comment by skoren** [comment]
The error is happening during the computation of the coverage so you likely won't be able to get the coverage from the contigs. Try the ```tgStoreDump``` command but instead ask for statistics not sequence (-tigs), run it without options to see usage.

Since you're on the latest code it's possible this is a new bug, are you able to share your data (either the ctgStore and seqStores or the raw reads)? See the FAQ for instructions to upload it to our FTP.

**Comment by skoren** [comment]
This is a bug in post-1.8 Canu, the release works as expected and wouldn't crash here. 

In short, when Canu re-aligns the reads to the final consensus it can leave a few bases at the ends uncovered. As a workaround, you can re-run the command that failed but add -L: ```/software/canu/canu/Linux-amd64/bin/tgStoreCoverageStat \
      -L -S ../SLA-04.seqStore \
      -T  ./SLA-04.ctgStore 2 \
      -s 55000000 \
      -o ./SLA-04.ctgStore.coverageStat \
    > ./SLA-04.ctgStore.coverageStat.err 2>&1
```
then resume Canu, it should continue onto the next step.

**Comment by calvincicha** [comment]
Is there a way to output tig fasta files from this pipeline?  I have already output contig files using the above command you recommended, but I am interested in looking at the tig files as well.

Also, I am a little confused when looking at the consensus data under 
unitigging/ 5-consensus/consensus.00000#.out 
I have files from consensus.000001.out- consensus.000035.out

These files give length and coverage of certain Tigs that were generated, and also gives the tigID.

My confusion comes from the tigIDs. I would think that the tigIDs represent distinct sequences, however, the tigIDs seem to repeat for some of these output files. 

For example, in consensus.000001.out it shows data for tigID 1 saying that it is 6.2 mb in length 33X coverage.

However, consensus.000022.out also shows data for tigID 1 saying that it is 1.9 mb in length and 36X coverage. 

It looks like the tigIDs starting at file consensus.000022.out and onwards have repeading tigIDs as the previous output files (consensus.000001-21.out). 

Can you explain why this is happening?

When outputting the contig sequences it only outputs sequences from consensus.000001.out-consensus.000021.out. I am worried that it is leaving out some important data from the later files (consensus.000022.out-consensus.000035.out).

**Comment by skoren** [comment]
That's correct, there are contigs and unitigs, the latter consensus jobs are generating unitigs. They are more conservative than contigs but will be redundant sequence with the contigs so you don't typically need them. You can dump the unitigs by replacing ctgStore with utgStore in the  command.

**Comment by calvincicha** [comment]
Is there a way to pull all of the tigs, even those that were not significant enough to be contigs or unitigs. 

Busco analysis (a program that looks for single copy conserved genes) of my assembly showed that my assembly is only 65% complete. I am trying to determine if this is because I did not sequence the full genome, or my assembly parameters are incorrect.

My thought is that I can run Busco on all of the tig files instead of just the contigs and this will tell me if the missing portions of the genome just didn't get assembled into the contigs, or if I did not sequence the whole genome to begin with.

**Comment by skoren** [comment]
You can dump everything, don't include -contigs on the dump command. Do that on only one store though (ctgStore), the unitigs aren't going to improve completeness and will just duplicate everything in your genome.

If you assembly size is close to the expected size then your assembly parameters are OK. The raw output from the assembly should have low completeness due to errors remaining in the consensus. BUSCO is sensitive to indel errors in the assembly. You need to run polishing (racon + nano polish or racon+medaka) and probably illumina polishing to get a higher accuracy and improve the completeness.

**Comment by brianwalenz** [comment]
The `tgStoreCoverageStat` command and computation of coverage stat has been removed from v1.9 and master.  The coverage stat was of dubious value with long reads; it was designed assuming that unitigs stopped at repeat boundaries, which is only true for short reads.

**Comment by calvincicha** [comment]
Hi Sergey,

You mentioned that my Canu error in #1403 was likely due to a bad contig. Is there a way to figure out which contig, original fasta file is causing this crash so I can remove it and continue the program with the remaining files?

Best,
Calvin

**Comment by skoren** [comment]
The error log (```SLA-04.ctgStore.coverageStat.err```) would have the bad contig ID in the error message. You can't remove a fasta file though because the contigs are stored in a binary tigStore, you'd have to remove it from the store which isn't easy to do. You also couldn't fix it by removing a read since the issue is an alignment bug in the version of the code you were using, if you are re-running you can just use the 1.9 brach which doesn't have this issue.
