### ISSUE TITLE
Canu v1.8 +268 - Consensus job failed with no error messages in consensus*out

### ISSUE THREAD

**Issue by shenjean** [marbl/canu#1408]
Hi there,

With canu v1.8 +268, the default assembly options worked fine, but when I changed to the high sensitivity option (corMhapSensitivity=high) it keeps failing at the consensus job. I have tried increasing cnsErrorRate, cnsConcurrency and the memory but it didn't work. There isn't any obvious error message in consensus.xxx.out either. Attached is the log and consensus.xxx.out.

[canu.log](https://github.com/marbl/canu/files/3373934/canu.log)

[consensus.out.txt](https://github.com/marbl/canu/files/3373937/consensus.out.txt)

**Comment by skoren** [comment]
From the error, it looks like there is a truncated file in one of the previous outputs. Post the contents and file sizes for ```unitigging/3313highsen.utgStore/partitionedReads.seqStore```. You can also try removing that folder completely and re-launching Canu.

**Comment by shenjean** [comment]
Here are the contents and file sizes. I'll try removing that folder and re-running too. Thank you!

ls -al partitionedReads.seqStore/partitions/
total 42151
drwxr-xr-x 2 jslim cuuser        5 Jul  8 17:43 .
drwxr-xr-x 3 jslim cuuser        1 Jul  8 17:43 ..
-rw-r--r-- 1 jslim cuuser 42467328 Jul  8 18:34 blobs.0001
-rw-r--r-- 1 jslim cuuser   396720 Jul  8 18:12 blobs.0002
-rw-r--r-- 1 jslim cuuser        0 Jul  8 17:43 map
-rw-r--r-- 1 jslim cuuser   293720 Jul  8 18:12 reads.0001
-rw-r--r-- 1 jslim cuuser     3080 Jul  8 18:12 reads.0002

**Comment by skoren** [comment]
Any update on this?

**Comment by shenjean** [comment]
Hi Sergey,

Sorry, no. I just decided to stop using the high sensitivity function and
stick with the default parameters instead. You can go ahead close this
issue. Thank you!

Jean
