### ISSUE TITLE
Correcting raw reads with illumina data

### ISSUE THREAD

**Issue by ViriatoII** [marbl/canu#1411]
Hey,

I've seen your FAQ about the reason for not using illumina reads
> 
***Can I use Illumina data too?***

    No. We’ve seen that using short reads for correction will homogenize repeats and mix up haplotypes.  Even though the short reads are very high quality, their length isn’t sufficient for the true alignment to be identified, and so reads from other repeat instances are used for correction, resulting in incorrect corrections.

But I have found a program (and corresponding paper) that states exactly the opposite:
http://www.atgc-montpellier.fr/lordec/
https://academic.oup.com/bioinformatics/article/30/24/3506/2422175

I have a highly heterozygous genome, and suspect correcting with illumina reads prior to canu might help to later deal with undercollapsed heterozygosity.

Can I ask you for your opinion on this?

Kind regards,
Ricardo

**Comment by gringer** [comment]
I suggest you re-read that answer. It talks about repeat homogenization (i.e. making all repeats of near-identical sequence identical) and haplotype mixing, neither of which are discussed in the LoRDEC paper (which was *published* in 2014).

**Comment by skoren** [comment]
Yes, what @gringer said, we don't recommend illumina correction. See the FAQ for heterozygous genomes, we generally recommend splitting the haplotypes out as much as possible. Collapsing them would just lead to false sequence that doesn't really exist in either haplotype. You can then remove the duplication using something like purge_dups or purge_haplotigs.

**Comment by ViriatoII** [comment]
Thank you, I'm doing exactly that!
