### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by REDitter** [marbl/canu#1412]
I am getting to following errors:
```
'-p: command not found'
'-nanopore-corrected: command not found'
```
running the following script on SLURM
```
#!/bin/bash
	#  this file is called 3393canu.sh

#SBATCH --qos normal

# Number of nodes
#SBATCH -N 1

# Number of tasks
#SBATCH -n 8

#SBATCH --job-name canu

#---Error file
#SBATCH -e /canu/err     

#---Output file 
#SBATCH -o /canu/out     

#SBATCH -p centos7

export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE
. /home/share/Modules/4.1.3/init/profile.sh
#export PATH=${PATH}:/canu

module load canu-1.7.1-gcc-8.2.0-xnezptc

echo "Running program on $SLURM_CPUS_ON_NODE CPU cores"

canu
-p 3393canu -d /canu
genomeSize=1.9g
-nanopore-corrected nanopore.fastq
```
I have also tried adding -assemble after the canu command
and I getting the additional following error:
ls: cannot access */*gkpStore: No such file or directory

Any help would be greatly appreciated

**Comment by skoren** [comment]
Your command is invalid, you're in effect calling four different programs:
````
1. canu
2. -p 3393canu -d /canu
3. genomeSize=1.9g
4. -nanopore-corrected nanopore.fastq
```
so the shell is complaining that -p and genomeSize and -nanopore-corrected are unknown executables, which they are. If you split a shell command on more than one line you need a ```\``` at the end like this:
```
canu \
-p 3393canu -d canu \
genomeSize=1.9g \
-nanopore-corrected nanopore.fastq
```

You should also add useGrid=false to your command if you don't want Canu to use your grid resources, just the node you allocate it to run on.

**Comment by REDitter** [comment]
Hey Sergey

I tried you advise of adding \ at the end

I also tried running it as:
canu -assemble -p HBG3393 -d /canu genomeSize=1.9g -nanopore-corrected
/mergedALL.fastq -useGrid=false

&

canu -p HBG3393 -d /canu genomeSize=1.9g -nanopore-corrected
/mergedALL.fastq -useGrid=false

All three runned an error and out file that you would expect if I only
submitted the command "canu" with no arguments


Thanks for the Quick Responce

Cheers,
Robert Ditter
*Ph.D. Candidate*


*Bracken-Grissom Lab (MSB-330) Florida International UniversityBiscayne Bay
Campus*
*Crustomics: Crustacean Genomics and Systematics Lab*
*brackengrissomlab.com
<https://urldefense.proofpoint.com/v2/url?u=http-3A__heatherbracken.wix.com_brackengrissomlab&d=AwMFaQ&c=1QsCMERiq7JOmEnKpsSyjg&r=rWAH25-c2Us3UVBK4CF-kw&m=s2M-Th-DF1xlXhMmvH18O_6AlDFIEeuJkwljCvhYRN0&s=kvqKaPnXopv0j4Gn_8cNIiHvUz6Q6M80MKkvdXSon9w&e=>*

**Comment by skoren** [comment]
I'm confused it worked or didn't? You didn't post any output. Also, you're asking it to read/write to the top-level dir (/canu), is that really where it should write output not the current folder?

**Comment by REDitter** [comment]
Hi Sergey,

None of the attempts worked.

Do you mean specify an output?

the /canu directory is just an abbreviation to shorten it for the post.  I
will attached the last version I tried to run.

Cheers,
Robb
*Ph.D. Candidate*


*Bracken-Grissom Lab (MSB-330) Florida International UniversityBiscayne Bay
Campus*
*Crustomics: Crustacean Genomics and Systematics Lab*
*brackengrissomlab.com
<https://urldefense.proofpoint.com/v2/url?u=http-3A__heatherbracken.wix.com_brackengrissomlab&d=AwMFaQ&c=1QsCMERiq7JOmEnKpsSyjg&r=rWAH25-c2Us3UVBK4CF-kw&m=s2M-Th-DF1xlXhMmvH18O_6AlDFIEeuJkwljCvhYRN0&s=kvqKaPnXopv0j4Gn_8cNIiHvUz6Q6M80MKkvdXSon9w&e=>*

**Comment by skoren** [comment]
Attachments don't come through on GitHub, you have to post through the web page or inline. I mean the full output that you get when you run the command.

**Comment by REDitter** [comment]
Hi Sergey,

Good to know attachments do come through github, and thanks for helping.  I
fount the culprit, and extra '.' in one of the paths.  I have it up and
running now.

Cheers,
Robb
*Ph.D. Candidate*


*Bracken-Grissom Lab (MSB-330) Florida International UniversityBiscayne Bay
Campus*
*Crustomics: Crustacean Genomics and Systematics Lab*
*brackengrissomlab.com
<https://urldefense.proofpoint.com/v2/url?u=http-3A__heatherbracken.wix.com_brackengrissomlab&d=AwMFaQ&c=1QsCMERiq7JOmEnKpsSyjg&r=rWAH25-c2Us3UVBK4CF-kw&m=s2M-Th-DF1xlXhMmvH18O_6AlDFIEeuJkwljCvhYRN0&s=kvqKaPnXopv0j4Gn_8cNIiHvUz6Q6M80MKkvdXSon9w&e=>*
