### ISSUE TITLE
Meryl merylOperation::reportStatistics() failed.

### ISSUE THREAD

**Issue by rozaimirazali** [marbl/canu#1413]
I am getting core dump files during 0-mercounts stage but instead of exiting the assembly continues to 1-overlapper . Is this something that I need to be worry of?

> Configured simple mode for 15.000 GB memory per batch, and up to 1 batch.
> 
> Loading kmers from '../../MNDY0206-haplotypePat.seqStore' into buckets.
> Increasing to 17-bit storage (for kmer 0x0000000000000000).
> Increasing to 18-bit storage (for kmer 0x0000000000000000).
> Increasing to 19-bit storage (for kmer 0x0000000000000000).
> Increasing to 20-bit storage (for kmer 0x0000000000000000).
> Increasing to 21-bit storage (for kmer 0x0000000000000000).
> Increasing to 22-bit storage (for kmer 0x0000000000000000).
> Increasing to 23-bit storage (for kmer 0x0000000000000000).
> Increasing to 24-bit storage (for kmer 0x0000000000000000).
> Increasing to 25-bit storage (for kmer 0x0000000000000000).
> Increasing to 26-bit storage (for kmer 0x0000000000000000).
> kmerCountFileWriter()-- Creating './MNDY0206-haplotypePat.01.meryl.WORKING' for 16-mers, with prefixSize 10 suffixSize 22 numFiles 64
> 
> Writing results to './MNDY0206-haplotypePat.01.meryl.WORKING', using 8 threads.
>   wPrefix  10
>   wSuffix  22
>   nPrefix  1024
>   nSuffix  4194304
>   sMask    0x00000000003fffff
> 
> finishIteration()--
> Bye.
> kmerCountFileWriter()-- Creating 'MNDY0206-haplotypePat.ms16.WORKING' for 16-mers, with prefixSize 12 suffixSize 20 numFiles 64
> Bye.
> **meryl: meryl/merylOp-histogram.C:107: void merylOperation::reportStatistics(): Assertion `sDistinct == stats->numDistinct()' failed.**
> 
> **Failed with 'Aborted'; backtrace (libbacktrace):
> utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
> (null)::0 in (null)()
> (null)::0 in (null)()
> (null)::0 in (null)()
> (null)::0 in (null)()
> (null)::0 in (null)()
> meryl/merylOp-histogram.C::107 in _ZN14merylOperation16reportStatisticsEv()
> meryl/meryl.C::773 in main()
> (null)::0 in (null)()
> (null)::0 in (null)()
> (null)::0 in (null)()
> ./meryl-process.sh: line 136: 22868 Aborted                 (core dumped)** /gpfs/software/pathology/canu/v1.8/canu/Linux-amd64/bin/meryl threads=1 memory=1 statistics ./MNDY0206-haplotypePat.ms16 > ./MNDY0206-hapl
> otypePat.ms16.histogram
> For word-frequency 0.000000, found threshold 8336
> For word-frequency 0.000000, found threshold 8336
> For word-frequency 0.000000, found threshold 8336

**Comment by brianwalenz** [comment]
Nope, no worries needed!  Even though it's crashing, it is generating the correct outputs.

See issue #1182 for discussion.
