### ISSUE TITLE
Bogart failed at "Place contained reads" stage (Canu v1.8)

### ISSUE THREAD

**Issue by svsaenko** [marbl/canu#1414]
I am running Canu v1.8 on SGE to assemble a large (3.5 Gbp) repetitive genome. It failed at bogart stage several times, every time at "Place contained reads". 

My Canu command is:
`/usr/local/canu/canu-v1.8/bin/canu -assemble -p snail -d snail-6 genomeSize=3.5g correctedErrorRate=0.105 -pacbio-corrected /exports/lgtc/projects/Suzanne/snail-6/snail.trimmedReads.fasta.gz gridOptions="-l h_vmem=20g -l h_stack=32m" minReadLength=3000 minOverlapLength=3000 canuIteration=0`

First, I got the error:
Failed to optimize read 4762940 in tig 103052
bogart: bogart/AS_BAT_OptimizePositions.C:279: void Unitig::optimize_recompute(uint32, optPos*, optPos*, bool): Assertion `cnt > 0' failed.

Following instructions in issues #1271 and #1252 I increased minOverlapLength to 1000 and 2000, it failed with the same error. Then I increased minOverlapLength to 3000, it failed again but this time **without** "Failed to optimize read 4762940 in tig 103052". Instead, the error looks like this: 

```
==> PLACE CONTAINED READS.

computeErrorProfiles()-- Computing error profiles for 387221 tigs, with 32 threads.
computeErrorProfiles()-- Finished.

placeContains()-- placing 2908897 contained and 1387500 unplaced reads, with 32 threads.
placeContains()-- Placed 1864604 contained reads and 17297 unplaced reads.
placeContains()-- Failed to place 1044293 contained reads (too high error suspected) and 1370203 unplaced reads (lack of overlaps suspected).
optimizePositions()-- Optimizing read positions for 4812526 reads in 387221 tigs, with 32 threads.
optimizePositions()--   Allocating scratch space for 4812526 reads (300782 KB).
optimizePositions()--   Initializing positions with 32 threads.
bogart: bogart/AS_BAT_OptimizePositions.C:202: void Unitig::optimize_initPlace(uint32, optPos*, optPos*, bool, std::set<unsigned int>&, bool): Assertion `cnt > 0' failed.

Failed with 'Aborted'; backtrace (libbacktrace):
utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
bogart/AS_BAT_OptimizePositions.C::202 in _ZN6Unitig18optimize_initPlaceEjP6optPosS1_bRSt3setIjSt4lessIjESaIjEEb()
bogart/AS_BAT_OptimizePositions.C::461 in _ZN9TigVector17optimizePositionsEPKcS1_._omp_fn.0()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
```
I attach the error and output files.
[snail.report.txt](https://github.com/marbl/canu/files/3391551/snail.report.txt)
[canu.out.txt](https://github.com/marbl/canu/files/3391552/canu.out.txt)
[unitigger.err.txt](https://github.com/marbl/canu/files/3391550/unitigger.err.txt)

Please, help, I don't know what else to do!
Kind regards, 
Suzanne

**Comment by brianwalenz** [comment]
A for effort!  Thanks for searching issues!

Can you fetch and compile a new version of canu?
```
> git clone https://github.com/marbl/canu.git
> cd canu
> git checkout 9f15c0d1e6e2ca40d718c70f8da1c716189757e5
(it will report a scary looking message about being in a 'detached HEAD' state)
> cd src
> make -j 8
```
(this is similar to the solution in issue #1377, but a few commits after the one used there).

Then remove the old failed bogart results and restart the assembly using the new version.
```
> rm -r snail-6/unitigging/4-unitigger
> {path-to-new-canu}/Linux-amd64/bin/canu <options as used before>
```

**Comment by svsaenko** [comment]
Dear Brian,

Thanks a lot for your superfast response! I compiled the new version and restarted the assembly. Now it's in a server queue for a day. The problem with our server is that there is only one instance that has the requested resources (32 threads and 512 Gb mem) and it's always full (waiting time can be up to a week). Is it OK to submit with less threads (e.g. batThreads=16 and h_vmem=32G) or better to let it as it is? 

Kind regards,
Suzanne

**Comment by skoren** [comment]
It'll probably be OK with much less memory. What's the next smallest node you have? You could try batMemory=256 or batMemory=128, make sure to remove the 4-unitigging folder before re-launching canu. I think 32 is a bit low for this size genome.

**Comment by svsaenko** [comment]
I just re-run with batMemory=256 and batThreads=12. Sadly, bogart stopped with exactly the same error. What next? 
My command this time was 
`/exports/lgtc/projects/Suzanne/canu/Linux-amd64/bin/canu -assemble -p snail -d snail-6 genomeSize=3.5g correctedErrorRate=0.105 -pacbio-corrected /exports/lgtc/projects/Suzanne/snail-6/snail.trimmedReads.fasta.gz gridOptions="-l h_vmem=24g -l h_stack=32m" batMemory=256g batThreads=12 minReadLength=3000 minOverlapLength=3000 canuIteration=0`
[unitigger.err.txt](https://github.com/marbl/canu/files/3404003/unitigger.err.txt)
[unitigger.1.out.txt](https://github.com/marbl/canu/files/3404004/unitigger.1.out.txt)

**Comment by svsaenko** [comment]
Dear Brian and Sergey,
sorry to bother you again, but do you have an idea how to fix my problem with bogart? I am stuck and don't know what to do. Please help!

**Comment by brianwalenz** [comment]
Whoop, sorry, I missed your reply.

Would it be possible to share this data so I can properly debug it?  I'd need snail.seqStore and unitigging/snail.ovlStore.  Directions for uploading are in the [FAQ](https://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you).

If not, increasing or decreasing the allowed error rate might get around the problem.

Bogart computes statistics on the overlaps then uses any that are within N standard deviations of the loaded overlaps.  This is controlled through options `-dg` and `-db`: higher values will use noisier overlaps (and possibly collapse repeats) while smaller values will possibly shatter the assembly, or make smaller contigs.  The default values are `batOptions="-dg 6 -db 6 -dr 3"`, so try `batOptions="-dg 4 -db 4 -dr 3"` or `batOptions="-dg 8 -db 8 -dr 3"`.  (Don't leave out the quotes!)

If you hang on to the contents of the current 4-unitigger/ directory (rename it to, say, 4-unitigger-crashed), you can compare the *sizes files to see what impact these changes had on contig sizes.

**Comment by svsaenko** [comment]
Dear Brian,
I tried those batOptions but it didn't help, still the same error.
I am now uploading the data (snail.seqStore.new.tar.gz and snail.ovlStore.tar.gz) to ftp.cbcb.umd.edu/incoming/sergek. I started uploading snail.seqStore.tar.gz earlier today but then the connection got broken, so I started again with the "new" file as I wasn't sure if everything has been transferred.
Thanks a lot for your help!!

**Comment by brianwalenz** [comment]
Fixed!  Thanks for the data, this would have been hard to find without an example.

From your previous clone of canu, do:
```
> cd canu
> git fetch
> git merge
> git checkout v1.9
Previous HEAD position was 9f15c0d1e Fix crash caused by placing orphan in an orphan that was already placed.  Issue #1284.
Branch 'v1.9' set up to track remote branch 'v1.9' from 'origin'.
Switched to a new branch 'v1.9'
> rm -r Linux-amd64
> cd src
> make -j 12
```
This updates your copy to the latest stable version of canu.  This will eventually become the 1.9 release.

Are you planning on getting more data?  If not, the assembly might benefit from multiple rounds of correction, as described at  https://canu.readthedocs.io/en/latest/faq.html#id8, in the "Nanopore R7 1D and Low Identity Reads" section.

**Comment by svsaenko** [comment]
Hi Brian,
It worked!!! Thanks a lot for fixing this problem!!
