### ISSUE TITLE
Issue with Canu

### ISSUE THREAD

**Issue by stanislasmorand** [marbl/canu#1418]
Hi, I'm a new user of the famous CANU. I wanted to assemble de novo a set of Nanopore gDNA reads (~800Mb) to get closer to a bacterial genome, which size is expected to be close to 4.5Mb.
I ran the following command line 
canu -p sxenoph -d sxenoph-minion genomeSize=4.5m -nanopore-raw FAF09678_57146reads.fastq.gz java=/home/stanislas.morand/bin/jdk-12.0.1/bin/java
And obtain few seconds after this message :

-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
--
-- Koren S, Rhie A, Walenz BP, Dilthey AT, Bickhart DM, Kingan SB, Hiendleder S, Williams JL, Smith TPL, Phillippy AM.
-- De novo assembly of haplotype-resolved genomes with trio binning.
-- Nat Biotechnol. 2018
-- https//doi.org/10.1038/nbt.4277
--
-- Read and contig alignments during correction, consensus and GFA building use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
--
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
--
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
--
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
--
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
--
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '12.0.1' (from '/home/stanislas.morand/bin/jdk-12.0.1/bin/java') without -d64 support.
-- Detected gnuplot version '4.6 patchlevel 2   ' (from 'gnuplot') and image format 'png'.
-- Detected 48 CPUs and 126 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |     total usage     algorithm
--        -------  ------  --------   --------  -----------------  -----------------------------
-- Local: meryl     10 GB    4 CPUs x  12 jobs   120 GB   48 CPUs  (k-mer counting)
-- Local: hap        8 GB    4 CPUs x  12 jobs    96 GB   48 CPUs  (read-to-haplotype assignment)
-- Local: cormhap    6 GB   16 CPUs x   3 jobs    18 GB   48 CPUs  (overlap detection with mhap)
-- Local: obtovl     4 GB    8 CPUs x   6 jobs    24 GB   48 CPUs  (overlap detection)
-- Local: utgovl     4 GB    8 CPUs x   6 jobs    24 GB   48 CPUs  (overlap detection)
-- Local: ovb        4 GB    1 CPU  x  31 jobs   124 GB   31 CPUs  (overlap store bucketizer)
-- Local: ovs        8 GB    1 CPU  x  15 jobs   120 GB   15 CPUs  (overlap store sorting)
-- Local: red        8 GB    4 CPUs x  12 jobs    96 GB   48 CPUs  (read error detection)
-- Local: oea        4 GB    1 CPU  x  31 jobs   124 GB   31 CPUs  (overlap error adjustment)
-- Local: bat       16 GB    4 CPUs x   1 job     16 GB    4 CPUs  (contig construction with bogart)
-- Local: gfa        8 GB    4 CPUs x   1 job      8 GB    4 CPUs  (GFA alignment and processing)
--
-- Found Nanopore uncorrected reads in the input files.
--
-- Generating assembly 'sxenoph' in '/home/stanislas.morand/sxenoph-minion'
--
-- Parameters:
--
--  genomeSize        4500000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1200 ( 12.00%)
--    utgOvlErrorRate 0.1200 ( 12.00%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1200 ( 12.00%)
--    utgErrorRate    0.1200 ( 12.00%)
--    cnsErrorRate    0.2000 ( 20.00%)
--
--
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Wed Jul 17 16:50:46 2019 with 2.735 GB free disk space

    cd .
    /home/stanislas.morand/canu-1.8/Linux-amd64/bin/sqStoreCreate \
      -o ./sxenoph.seqStore.BUILDING \
      -minlength 1000 \
      ./sxenoph.seqStore.ssi \
    > ./sxenoph.seqStore.BUILDING.err 2>&1
^C
-- Finished on Wed Jul 17 16:51:00 2019 (14 seconds) with 2.544 GB free disk space  !!! WARNING !!!
----------------------------------------

ERROR:
ERROR:  Failed with signal INT.  (rc=2)
ERROR:

ABORT:
ABORT: Canu 1.8
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   sqStoreCreate failed.
ABORT:
ABORT: Disk space available:  2.544 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (./sxenoph.seqStore.BUILDING.err):
ABORT:
ABORT:
ABORT:   Starting file './sxenoph.seqStore.ssi'.
ABORT:
ABORT:     Loading reads from '/home/stanislas.morand/FAF09678_57146reads.fastq.gz'
ABORT:
ABORT:   Failed with 'Interrupt'; backtrace (libbacktrace):
ABORT:   utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   utility/files.C::85 in _Z11writeToFilePvPKcmmP8_IO_FILE()
ABORT:   utility/files-buffered.C::403 in _ZN11writeBuffer5flushEv()
ABORT:   utility/files-buffered.C::353 in _ZN11writeBuffer5writeEPvm()
ABORT:   stores/sqStoreBlobWriter.H::89 in _ZN17sqStoreBlobWriter9writeDataEPhm()
ABORT:   stores/sqStore.C::148 in _ZN7sqStore21sqStore_stashReadDataEP10sqReadData()
ABORT:   stores/sqStoreCreate.C::462 in _Z9loadReadsP7sqStoreP9sqLibraryjjP8_IO_FILES4_S4_PcRjS6_RmS6_S7_()
ABORT:   stores/sqStoreCreate.C::641 in _Z11createStorePKcjPPcjj()
ABORT:   stores/sqStoreCreate.C::879 in main()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:

Could you please tell me what is the error origin and how to avoid it? Thanks in advance.
Cheers,
Stan

**Comment by brianwalenz** [comment]
Based on where it failed, and the logging "2.544 GB free disk", I'm going to guess you're just out of disk space.

**Comment by stanislasmorand** [comment]
Thanks Brian for your fast reply and analysis. I'll swith on another server where Canu is also installed. Cheers, Stan (and sorry for the poor quality of the initial editing).
