### ISSUE TITLE
overlap store methhod

### ISSUE THREAD

**Issue by pickettbd** [marbl/canu#1419]
I'm using Canu 1.8 running on Linux (RHEL 6) using SLURM. I have used v1.6 in the past with success. I am getting stuck on the creation of the overlap store. the ovb steps appear to have completed, but the ovs steps end up failing. I see in the documentation for 1.8 that two methods (sequential and parallel) exist for creating the store. I had issues with this in 1.6 as well. My solution (when running 1.6) was to use ovsMethod=sequential. That option appears to be deprecated in 1.8 (as made apparent by an error message), yet the possibility of both options is still referenced in the documentation. I've read through the documentation several times, but cannot seem to find how to use the sequential method. However, I may be missing it. Would you kindly point me in the right direction? Thank you.

**Comment by skoren** [comment]
The sequential method is indeed deprecated, the parallel should be used instead. The ovs step is likely failing due to memory limits, you can try increasing its request (see #1278 or #1356 for more information).

**Comment by pickettbd** [comment]
Thank you for your quick reply and help. I was already giving the ovs jobs 128 GB of memory. I'll try again with more and see what happens. Thank you!
