### ISSUE TITLE
calculating some quality score

### ISSUE THREAD

**Issue by wisekh6** [marbl/canu#142]
Hello,
I could successfully run canu with low coverage (~10X) pacbio data.
I wonder what quality scores I can use in order to evaluate my assembly.
For example, how can I calculate N50 and how should I interpret it to evaluate my result? canu created several html files representing some summary information, but they don't have N50. Probably, I could use .layout.tigInfo file for calculating N50.
I will be sorry if this question was addressed somewhere else.

Thank you in advance,

**Comment by brianwalenz** [comment]
This is a weak spot in the assembler.  Most of the stats are capture in various log files, and I've yet to collect them for the html report.

The result of the assembly is stored in the 'tigStore'.  The tigStore holds the contigs after various phases, 'versions' in tigStore terms.  In Celera Assembler, there were many many versions of contigs.  In canu, there are only two: version=1 is the contigs as output by the contigger.  Version=2 is the contigs after consensus sequences are generated.  The 'tgStoreDump' command is used to query this structure.

N50 (and all the other N values) is reported by:
  tgStoreDump -G *gkpStore -t *tigStore 2 -sizes -s <your-genome-size>

You can get sequence in fasta/fastq with -consensus, and the layouts with '-layout'.  Both of these are generated by canu.

**Comment by wisekh6** [comment]
thank you very much for your quick response.

**Comment by noushing** [comment]
Hello Brian,

I'm using Canu 1.5 and trying above commands won't work. It give me the "ERROR: invalid range '*tigStore'" message. I used the recommandation by Sergey in #450 and replaced the *tigStore with ctgStore, but still no success. Is there any changes needed for above command to get the stats? 

Thanks!

**Comment by skoren** [comment]
In general you can always get a usage by just running the executable without any parameters. You should also include your full command that is not working. There are multiple commands explained above so I am not sure which you're trying to run. 

Your error is only triggered when you're specifying a range with a dash, none of the commands above should be doing that unless you're trying to specify specific tigs. The syntax hasn't changed very much, I can run 
```tgStoreDump -G asm.gkpStore -T asm.ctgStore 2 -sizes -s 3100000000``` for example inside the unitigging directory.

**Comment by noushing** [comment]
Thanks Sergey. I had provided the path to the directories before, but this time I moved there and reran the command, Worked perfectly.
