### ISSUE TITLE
Four mhap jobs were aborted by the PBS Server

### ISSUE THREAD

**Issue by Malabady** [marbl/canu#1421]
Hello, 

Three of the mhap jobs were aborted by PBS server. Other jobs are running fine. 
Here is the tail of the cormhap out file of the aborted jobs:
```
$ cormhap_run.o1374474-31
Current # sequences loaded and processed from file: 80000...
Current # sequences loaded and processed from file: 85000...
Current # sequences loaded and processed from file: 90000...
Processed 91800 sequences (fwd and rev).
Read, hashed, and stored file ./000031.input.fasta to ./000031.input.dat.
Time (s): 1358.155031404
Total time (s): 1358.1552511900002

$ tail cormhap_run.o1374474-32
Current # sequences loaded and processed from file: 65000...
Current # sequences loaded and processed from file: 70000...
Current # sequences loaded and processed from file: 75000...
Current # sequences loaded and processed from file: 80000...
Current # sequences loaded and processed from file: 85000...
Current # sequences loaded and processed from file: 90000...
Processed 91800 sequences (fwd and rev).
Read, hashed, and stored file ./000032.input.fasta to ./000032.input.dat.
Time (s): 1425.736445078
Total time (s): 1425.736695664

$ tail cormhap_run.o1374474-33
Current # sequences loaded and processed from file: 65000...
Current # sequences loaded and processed from file: 70000...
Current # sequences loaded and processed from file: 75000...
Current # sequences loaded and processed from file: 80000...
Current # sequences loaded and processed from file: 85000...
Current # sequences loaded and processed from file: 90000...
Processed 91800 sequences (fwd and rev).
Read, hashed, and stored file ./000033.input.fasta to ./000033.input.dat.
Time (s): 1361.2385056940002
Total time (s): 1361.238724898

$ tail cormhap_run.o1374474-34
Current # sequences loaded and processed from file: 65000...
Current # sequences loaded and processed from file: 70000...
Current # sequences loaded and processed from file: 75000...
Current # sequences loaded and processed from file: 80000...
Current # sequences loaded and processed from file: 85000...
Current # sequences loaded and processed from file: 90000...
Processed 91800 sequences (fwd and rev).
Read, hashed, and stored file ./000034.input.fasta to ./000034.input.dat.
Time (s): 1361.470281502
Total time (s): 1361.470518503
```
There are no *.oc and *.ovb files for these jobs in the results folder. 

Reading through similar issues here, I found a solution like the following:
```
# If I run the following commands, they will regenerate and submit the jobs to the queue:
mhap_failed_jobs=(31 32 33 34) 
for i in "$mhap_failed_ids[@]"; do
  ./mhap.sh $i
done
```
Is this a viable solution? If not, what could be the solution to this issue? 

Many thanks for your outstanding support. 

Magdy

**Comment by skoren** [comment]
I don't see any error in the output, this looks like the precompute step which won't generate oc or ovb files but instead dat files in the blocks folder. What is the contents of your block folder? Canu will automatically retry any failed jobs so if the rest of the jobs are still running, just let Canu re-try if these jobs are indeed missing output.

**Comment by Malabady** [comment]
The block folders have 481 dat files (000001.dat to 000481.dat). I think the precomute step is compete already because when I look in the results folder, I see files like this: 000060.mhap.WORKING.

**Comment by Malabady** [comment]
And yes, you are right, the file "cormhap_run.o1374474-31/2/3/4 are from the precompute step. The next set of job array have a different job id, something like :cormhap_run.o1379635-39. But there is files for 31,32,33,34 under the 1-overlapper directory.

**Comment by skoren** [comment]
Do the files include WORKING in the name? Can you post the tail of jobs 31-34 from cormhap_run.o1379635?

**Comment by Malabady** [comment]
There is no files for jobs 31-34 in cormhap_run01379635 array of jobs.  Here is the whole list:

-rw-------.    1 malabady msalab  96K Jul 19 10:09 cormhap_run.o1379635-1
-rw-------.    1 malabady msalab  96K Jul 19 10:54 cormhap_run.o1379635-10
-rw-------.    1 malabady msalab  96K Jul 19 10:55 cormhap_run.o1379635-11
-rw-------.    1 malabady msalab  94K Jul 19 10:57 cormhap_run.o1379635-12
-rw-------.    1 malabady msalab  96K Jul 19 11:24 cormhap_run.o1379635-13
-rw-------.    1 malabady msalab  96K Jul 19 11:26 cormhap_run.o1379635-14
-rw-------.    1 malabady msalab  96K Jul 19 11:26 cormhap_run.o1379635-15
-rw-------.    1 malabady msalab  93K Jul 19 11:34 cormhap_run.o1379635-16
-rw-------.    1 malabady msalab  96K Jul 19 11:35 cormhap_run.o1379635-17
-rw-------.    1 malabady msalab  96K Jul 19 11:38 cormhap_run.o1379635-18
-rw-------.    1 malabady msalab  96K Jul 19 12:01 cormhap_run.o1379635-19
-rw-------.    1 malabady msalab  96K Jul 19 10:17 cormhap_run.o1379635-2
-rw-------.    1 malabady msalab  93K Jul 19 12:05 cormhap_run.o1379635-20
-rw-------.    1 malabady msalab  96K Jul 19 12:04 cormhap_run.o1379635-21
-rw-------.    1 malabady msalab  96K Jul 19 12:13 cormhap_run.o1379635-22
-rw-------.    1 malabady msalab  96K Jul 19 12:14 cormhap_run.o1379635-23
-rw-------.    1 malabady msalab  92K Jul 19 12:19 cormhap_run.o1379635-24
-rw-------.    1 malabady msalab  96K Jul 19 12:40 cormhap_run.o1379635-25
-rw-------.    1 malabady msalab  96K Jul 19 12:41 cormhap_run.o1379635-26
-rw-------.    1 malabady msalab  96K Jul 19 12:40 cormhap_run.o1379635-27
-rw-------.    1 malabady msalab  91K Jul 19 12:52 cormhap_run.o1379635-28
-rw-------.    1 malabady msalab  96K Jul 19 12:55 cormhap_run.o1379635-29
-rw-------.    1 malabady msalab  96K Jul 19 10:11 cormhap_run.o1379635-3
-rw-------.    1 malabady msalab  96K Jul 19 13:00 cormhap_run.o1379635-30
-rw-------.    1 malabady msalab  96K Jul 19 13:33 cormhap_run.o1379635-35
-rw-------.    1 malabady msalab  90K Jul 19 13:35 cormhap_run.o1379635-36
-rw-------.    1 malabady msalab  96K Jul 19 13:36 cormhap_run.o1379635-37
-rw-------.    1 malabady msalab  96K Jul 19 13:33 cormhap_run.o1379635-38
-rw-------.    1 malabady msalab  96K Jul 19 13:34 cormhap_run.o1379635-39
-rw-------.    1 malabady msalab  96K Jul 19 10:15 cormhap_run.o1379635-4
-rw-------.    1 malabady msalab  89K Jul 19 13:40 cormhap_run.o1379635-40
-rw-------.    1 malabady msalab  96K Jul 19 14:11 cormhap_run.o1379635-41
-rw-------.    1 malabady msalab  96K Jul 19 14:11 cormhap_run.o1379635-42
-rw-------.    1 malabady msalab  96K Jul 19 14:13 cormhap_run.o1379635-43
-rw-------.    1 malabady msalab  88K Jul 19 14:14 cormhap_run.o1379635-44
-rw-------.    1 malabady msalab  96K Jul 19 14:14 cormhap_run.o1379635-45
-rw-------.    1 malabady msalab  96K Jul 19 14:21 cormhap_run.o1379635-46
-rw-------.    1 malabady msalab  96K Jul 19 14:48 cormhap_run.o1379635-47
-rw-------.    1 malabady msalab  87K Jul 19 14:51 cormhap_run.o1379635-48
-rw-------.    1 malabady msalab  96K Jul 19 14:55 cormhap_run.o1379635-49
-rw-------.    1 malabady msalab  96K Jul 19 10:17 cormhap_run.o1379635-5
-rw-------.    1 malabady msalab  96K Jul 19 14:53 cormhap_run.o1379635-50
-rw-------.    1 malabady msalab  96K Jul 19 14:51 cormhap_run.o1379635-51
-rw-------.    1 malabady msalab  86K Jul 19 15:01 cormhap_run.o1379635-52
-rw-------.    1 malabady msalab  96K Jul 19 15:28 cormhap_run.o1379635-53
-rw-------.    1 malabady msalab  96K Jul 19 15:33 cormhap_run.o1379635-54
-rw-------.    1 malabady msalab  96K Jul 19 15:31 cormhap_run.o1379635-55
-rw-------.    1 malabady msalab  86K Jul 19 15:32 cormhap_run.o1379635-56
-rw-------.    1 malabady msalab  96K Jul 19 15:37 cormhap_run.o1379635-57
-rw-------.    1 malabady msalab  96K Jul 19 15:44 cormhap_run.o1379635-58
-rw-------.    1 malabady msalab  96K Jul 19 16:08 cormhap_run.o1379635-59
-rw-------.    1 malabady msalab  96K Jul 19 10:17 cormhap_run.o1379635-6
-rw-------.    1 malabady msalab  85K Jul 19 16:07 cormhap_run.o1379635-60
-rw-------.    1 malabady msalab  96K Jul 19 16:12 cormhap_run.o1379635-61
-rw-------.    1 malabady msalab  96K Jul 19 16:14 cormhap_run.o1379635-62
-rw-------.    1 malabady msalab  96K Jul 19 16:19 cormhap_run.o1379635-63
-rw-------.    1 malabady msalab  84K Jul 19 16:26 cormhap_run.o1379635-64
-rw-------.    1 malabady msalab  96K Jul 19 16:45 cormhap_run.o1379635-65
-rw-------.    1 malabady msalab  96K Jul 19 16:48 cormhap_run.o1379635-66
-rw-------.    1 malabady msalab  96K Jul 19 16:51 cormhap_run.o1379635-67
-rw-------.    1 malabady msalab  83K Jul 19 16:53 cormhap_run.o1379635-68
-rw-------.    1 malabady msalab  96K Jul 19 17:01 cormhap_run.o1379635-69
-rw-------.    1 malabady msalab  96K Jul 19 10:46 cormhap_run.o1379635-7
-rw-------.    1 malabady msalab  96K Jul 19 17:09 cormhap_run.o1379635-70
-rw-------.    1 malabady msalab  79K Jul 19 17:17 cormhap_run.o1379635-71
-rw-------.    1 malabady msalab  63K Jul 19 17:17 cormhap_run.o1379635-72
-rw-------.    1 malabady msalab  65K Jul 19 17:17 cormhap_run.o1379635-73
-rw-------.    1 malabady msalab  53K Jul 19 17:17 cormhap_run.o1379635-74
-rw-------.    1 malabady msalab  35K Jul 19 17:17 cormhap_run.o1379635-75
-rw-------.    1 malabady msalab  14K Jul 19 17:17 cormhap_run.o1379635-76
-rw-------.    1 malabady msalab  95K Jul 19 10:49 cormhap_run.o1379635-8
-rw-------.    1 malabady msalab  96K Jul 19 10:52 cormhap_run.o1379635-9

**Comment by skoren** [comment]
What about an cormhap_run.e1379635?

**Comment by Malabady** [comment]
There are no cormhap_run.e1379635 files. Also there is no cormhap_run.e1374474 files

**Comment by skoren** [comment]
So if your grid did kill these jobs, they had no output. This seems like it might be a node issue. Are there any files for 31-34 in the results folder? Is there any status from your PBS for why the jobs were killed?

**Comment by Malabady** [comment]
No, there are no files for 31-34 in the results folder. Our cluster system admin  had to restart the queuing system server daemon at 12:59 today, because qstat was hanging. when it started back again, it didn't have all the state information it needed for all of the array jobs. And these four jobs were aborted consequently.  

# If I run the following commands, will regenerate and submit the jobs to the queue?
mhap_failed_jobs=(31 32 33 34) 
for i in "$mhap_failed_ids[@]"; do
  ./mhap.sh $i
done

**Comment by skoren** [comment]
In that case, don't run any commands, you may conflict with the automated re-try.

Canu has a re-try mechanism as I mentioned which is meant to handle these kind of intermittent grid failures or node failures. It will see those jobs never ran and launch just them by itself. If this re-try fails several times, it will abort the run and then you'd have to manually run them.
