### ISSUE TITLE
Interesting structure with canu and nanopolish

### ISSUE THREAD

**Issue by limin321** [marbl/canu#1423]
I only have nanopore sequence data for agrobacterium tumefaciens whole genome, then I noticed different basecaller guppy version (2.1.3 vs. 3.0.3) combine with different assembly tool (unicycler vs. canu_nanopolish). 
<img width="789" alt="Screen Shot 2019-07-23 at 5 42 14 PM" src="https://user-images.githubusercontent.com/42760669/61756647-bf114300-ad71-11e9-95cc-9b93ec716057.png">
The first and the third are canu assembly, both have those unresolved structure.
canu with Guppy 3.0.3 HAC basecaller seems to produce extra origins of replication.  

Does any one have similar issue? and have any better explanation for this?  Really appreciate for that?

Your help are  greatly appreciated.
Limin

**Comment by skoren** [comment]
I'm not sure how to interpret your plot, the bottom two both have a large circular contig and several smaller ones (presumably plasmids). Are you talking about the double-loop structure in the bottom? The best way to check that is to look at raw read support, canu will tell you where all reads ended up in the assembly (see the layout files under output: https://canu.readthedocs.io/en/latest/tutorial.html#outputs) so you can see how much support there is for the structure. You can also re-map the raw reads to the assembly and check support.

**Comment by skoren** [comment]
Idle, no response
