### ISSUE TITLE
Bucketizing stage death

### ISSUE THREAD

**Issue by claumer** [marbl/canu#1424]
Hello there,

I'm trying to assemble a genome with millions (about 7.5m) of relatively short PCR amplified nanopore reads (1-5 kbp), using a novel protocol that minimizes coverage bias and maximizes library diversity. With this approach that I've gotten great results with from other samples, including single C. elegans worms as input. So I know this is possible, and so far canu has been the best assembler.

The launch command I'm using is:
```
canu -nanopore-raw [read fastq] -p MeioA_canu -d MeioA_canu genomeSize=300m minMemory=8g
```

My job dies at the bucketizing stage of overlap correction, and I'm really not sure why. Lots of the jobs succeed but 23 die. Below is the bucketize out log for one of the failed jobs:

```
Found perl:
   /usr/local/bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /usr/bin/java
   openjdk version "1.8.0_161"

Found canu:
   /nfs/research1/marioni/claumer/canu/Linux-amd64/bin/canu
   Canu snapshot v1.8 +261 changes (r9471 093a51f41fcb7029a81dfd7663ee5aa4e44e2110)

Running job 529 based on LSB_JOBINDEX=529 and offset=0.

Attempting to increase maximum allowed processes and open files.
  Max processes per user limited to 514833, no increase possible.
  Max open files limited to 4096, no increase possible.

Overwriting incomplete result from presumed crashed job in directory './MeioA_canu.ovlStore.BUILDING/create0529'.

Opened '../MeioA_canu.seqStore' with 7445339 reads.

Constructing slice 529 for store './MeioA_canu.ovlStore.BUILDING'.
 - Filtering overlaps over 1.0000 fraction error.

Bucketizing input    1 out of    1 - '1-overlapper/results/000529.ovb'
writeToFile()-- After writing 5624 out of 683881 'ovFile::writeBuffer::sb' objects (1 bytes each): No space left on device

------------------------------------------------------------
Sender: LSF System <lsf@hx-noah-63-09>
Subject: Job 120597[529]: <ovB_MeioA_canu[529-530]> in cluster <EBI> Exited

Job <ovB_MeioA_canu[529-530]> was submitted from host <hx-noah-64-06> by user <claumer> in cluster <EBI> at Thu Jul 25 11:32:06 2019
Job was executed on host(s) <hx-noah-63-09>, in queue <research-rh74>, as user <claumer> in cluster <EBI> at Thu Jul 25 11:32:07 2019
</homes/claumer> was used as the home directory.
</nfs/research1/marioni/claumer/CEL_MeioA_160719/MeioA_canu/correction/MeioA_canu.ovlStore.BUILDING> was used as the working directory.
Started at Thu Jul 25 11:32:07 2019
Terminated at Thu Jul 25 11:34:22 2019
Results reported at Thu Jul 25 11:34:22 2019
Cannot open your job file: /homes/claumer/.lsbatch/1564050726.120597.529
Exited with exit code 1.

Resource usage summary:

    CPU time :                                   57.62 sec.
    Max Memory :                                 430 MB
    Average Memory :                             275.20 MB
    Total Requested Memory :                     8192.00 MB
    Delta Memory :                               7762.00 MB
    Max Swap :                                   713 MB
    Max Processes :                              4
    Max Threads :                                5
    Run time :                                   135 sec.
    Turnaround time :                            136 sec.

The output (if any) is above this job summary.

```
It says that there's no space left on the device but this is not true. However, there might be a system-wide limit on the number of files that we could be running into...

Is there a way to relaunch that will overcome these errors? Ideally without having to re-run a lot of expensive compute? I have tried using ovbConcurrency=8 and ovsConcurrency=8 and this does not seem to solve the problem...

Thanks for reading (and sorry if this is an issue that has come up before - couldn't find a clear solution on the issues pages).

Regards,
Chris L

**Comment by skoren** [comment]
Are you sure that there is not another quota you're hitting? I don't think this is a file limit as it reports it was able to write part of the output before hitting an out of space error. 

You can try a couple of things, remove the ```MeioA_canu.ovlStore.BUILDING``` folder along with the ```1-overlapper/blocks``` folder. That will free up some space. Increase the memory used for sorting jobs as well to make fewer of them which will decrease the number of files using ```ovsMemory=32``` (assuming you have nodes with 32g memory).

**Comment by claumer** [comment]
Hi Sergey,

I've just been in contact with my sysadmins about other quotas in place on this filesystem. Your intuition was quite correct. They write: 

"/nfs/research1 is mounted from vnas-research:/fg_research which is a Flexgroup. Flexgroup consists of number flexvolumes which one of them is unfortunately full."

Which is not at all visible when doing df . which says that the drive is only 74% full. So not a canu problem at all - I'm closing this issue, and thanks for your input.
