### ISSUE TITLE
different performance using the git canu and the binary canu

### ISSUE THREAD

**Issue by jhernandez1409** [marbl/canu#1426]
Hi,

I installed Canu as source code and assembled a Pacbio run using default parameters and also installed Canu as pre-compiled binaries in another docker and assembled the same Pacbio run using also the default parameters. However, the performance or output of the two different installations is different. We ran Quast on the two against a reference too for comparison (attached file). Do you have any idea of why the differences?

Thanks!

JoJo
[quast.log](https://github.com/marbl/canu/files/3436234/quast.log)

**Comment by skoren** [comment]
You didn't provide info on how Canu was installed from source/vs pre-compiled binary. What were the commands and the canu output.

**Comment by jhernandez1409** [comment]
From source, I used :
git clone https://github.com/marbl/canu.git && cd canu/src && make 

For binary, I used:
wget https://github.com/marbl/canu/releases/download/v1.8/canu-1.8.Linux-amd64.tar.xz && tar -xJf canu-1.8.Linux-amd64.tar.xz && rm canu-1.8.Linux-amd64.tar.xz 

command:
canu -p canu - d canu_output genomeSize=101.2m -pacbio-raw SRR7595427_subreads.fastq.gz

**Comment by skoren** [comment]
Those are different versions and the tip has some pretty large-scale changes that aren't tested. The most stable option from source would be to get the 1.9 branch using:
```
git checkout v1.9
rm -r Linux-amd64
make
```
it might still be slightly different from the 1.8 version, to match that from source you should get the 1.8 tag:
```
git checkout v1.8
rm -r Linux-amd64
make
```

**Comment by skoren** [comment]
Idle, different versions were used leading to different results.
