### ISSUE TITLE
Unitiging failed canu 1.8

### ISSUE THREAD

**Issue by splaisan** [marbl/canu#1427]
Dear Sergey,

I think I have too much Ecoli data to assemble from as happened before or too many tigs.
The failed job advises to increase -M but I do not find reference to that -M for the correct syntax. I reran several times increasing 'ovsMemory' up to 256G but no better and no change in the user-supplied cache value (16G). I have 512G in total and 88 threads.

my original command:

`canu  -d asm_full -p Coli_and_BAC genomeSize=5m -nanopore-raw /data2/gridion_data/3201/merged_hac.fq.gz`

Can you please advise?

> cat asm_full/unitigging/4-unitigger/unitigger.err
> 
> ==> PARAMETERS.
> 
> Resources:
>   Memory                16 GB
>   Compute Threads       4 (command line)
> 
> Lengths:
>   Minimum read          0 bases
>   Minimum overlap       500 bases
> 
> Overlap Error Rates:
>   Graph                 0.120 (12.000%)
>   Max                   0.120 (12.000%)
> 
> Deviations:
>   Graph                 6.000
>   Bubble                6.000
>   Repeat                3.000
> 
> Edge Confusion:
>   Absolute              2100
>   Percent               200.0000
> 
> Unitig Construction:
>   Minimum intersection  500 bases
>   Maxiumum placements   2 positions
> 
> Debugging Enabled:
>   (none)
> 
> ==> LOADING AND FILTERING OVERLAPS.
> 
> ReadInfo()-- Using 1550731 reads, no minimum read length used.
> 
> OverlapCache()-- limited to 16384MB memory (user supplied).
> 
> OverlapCache()--      11MB for read data.
> OverlapCache()--      59MB for best edges.
> OverlapCache()--     153MB for tigs.
> OverlapCache()--      41MB for tigs - read layouts.
> OverlapCache()--      59MB for tigs - error profiles.
> OverlapCache()--    4096MB for tigs - error profile overlaps.
> OverlapCache()--       0MB for other processes.
> OverlapCache()-- ---------
> OverlapCache()--    4450MB for data structures (sum of above).
> OverlapCache()-- ---------
> OverlapCache()--      29MB for overlap store structure.
> OverlapCache()--   11903MB for overlap data.
> OverlapCache()-- ---------
> OverlapCache()--   16384MB allowed.
> OverlapCache()--
> OverlapCache()-- Retain at least 968 overlaps/read, based on 484.17x coverage.
> OverlapCache()-- Initial guess at 503 overlaps/read.
> OverlapCache()--
> OverlapCache()-- Not enough memory to load the minimum number of overlaps; increase -M.

**Comment by splaisan** [comment]
I found something! do I need to manually edit asm_full/unitigging/4-unitigger/unitigger.sh at the level of '''-M 16''' or can I have it changed from the main command?

**Comment by skoren** [comment]
In canu 1.8 it won't re-write the unitigger.sh script so you'd either need to manually edit it to increase the -M option or remove the full unitigging/4-unitigger folder and then re-start canu adding batMemory=512 or whatever you want.

Generally, assembling from 500x data isn't really useful, canu has options to downsample the data on load to a desired coverage, see ```readSamplingCoverage```.
