### ISSUE TITLE
how to select input data

### ISSUE THREAD

**Issue by dcopetti** [marbl/canu#1428]
Hello,

I wonder if you have any suggestion on how to run Canu with PromethION data. We are assembling a highly-heterozygous 2.5 Gb plant genome (we consider it to be as a 5 Gb genome), our data looks like the following:
-batch 1: ~64x coverage (of the 2.5 Gb genome), N50 ~10 kb, mean read quality 10;
-batch 2: ~38x coverage (of the 2.5 Gb genome), N50 ~55 kb, mean read quality 10.

We run batch 1 and it took more than a month to get the error corrected reads (on a large cluster, I don't have the details here), with a footprint of 60 TB. The report of the error correction is attached, and in the Canu docs I read that anyway just the largest ~40x of reads gets corrected.

So we are wondering if there is anything we could do to reduce the duration of the EC step. 
- Would it be possible just to select the (40, 50, 60x of) long reads only for the whole assembly run? Would we lose accuracy in the EC by not computing overlaps with all reads?
- Is it possible to direct the EC step to align only shorter reads to longer reads (like FALCON does)?
- Can we use the EC reads from the first batch to correct the second batch? Would that help?

What else could we do to error correct with high accuracy (we want to keep allelic phasing information in the reads) and with reasonable computing time and resources?
Thanks,

Dario

```
[CORRECTION/LAYOUT]
--                             original      original
--                            raw reads     raw reads
--   category                w/overlaps  w/o/overlaps
--   -------------------- ------------- -------------
--   Number of Reads           13536972       5049782
--   Number of Bases       100165151106     222065026
--   Coverage                    40.066         0.089
--   Median                        5147             0
--   Mean                          7399            43
--   N50                          10007          2854
--   Minimum                       2000             0
--   Maximum                     572656         59408
--   
--                                        --------corrected---------  ----------rescued----------
--                             evidence                     expected                     expected
--   category                     reads            raw     corrected            raw     corrected
--   -------------------- -------------  ------------- -------------  ------------- -------------
--   Number of Reads           13609520       13104392      13104392              0             0
--   Number of Bases       100366168305    98799787970   92560106367              0             0
--   Coverage                    40.146         39.520        37.024          0.000         0.000
--   Median                        5120           5300          4896              0             0
--   Mean                          7374           7539          7063              0             0
--   N50                           9985          10137         10237              0             0
--   Minimum                       2000           2000             1              0             0
--   Maximum                     572656         572656        228887              0             0
--   
--                        --------uncorrected--------
--                                           expected
--   category                       raw     corrected
--   -------------------- ------------- -------------
--   Number of Reads            5482362       5482362
--   Number of Bases         1587428162        256787
--   Coverage                     0.635         0.000
--   Median                           0             0
--   Mean                           289             0
--   N50                           3022             0
--   Minimum                          0             0
--   Maximum                     258416        256787
--   
--   Maximum Memory          4255018316
```

**Comment by skoren** [comment]
You could probably use just batch 2, the read length is much better and 40x is relatively high, you could supplement it it up to 50 or 60x with the longest reads from batch 1. The quality of the reads would be similar with those read sets.

You can speed up computation and by using the repetitive suggestions on the FAQ page. That will also reduce space requirements. If you use the 1.9 branch, which I would recommend, it has an option to clean up data as it runs via ```purgeOverlaps=aggressive```, this should significantly reduce your disk usage. Finally, the 1.9 branch also allows the staging parameters (```gridEngineStageOption``` and ```stageDirectory```) to apply to these overlap jobs which will store most of the data on a local disk (assuming your cluster has local storage) which is both faster and will again reduce disk usage.
