### ISSUE TITLE
The reads between 20,000 and 50,000 in length are lost after corrected step

### ISSUE THREAD

**Issue by yplee614** [marbl/canu#1429]
We used canu v1.8 to correct the reads, but we found that The reads between 20,000 and 50,000 in length are lost after corrected. The command : canu -correct -p raspberry_nanopore -d raspberry_nanopore genomeSize=293m maxThreads=32 minReadLength=3000 -nanopore-raw ./*.fastq.gz

-- Proceeding with assembly because stopOnReadQuality=false.
--
-- In sequence store './raspberry_nanopore.seqStore':
--   Found 2620081 reads.
--   Found 47049878628 bases (160.57 times coverage).
--
--   Read length histogram (one '*' equals 10220.88 reads):
--        0   4999 592395 *********************************************************
--     5000   9999 715462 **********************************************************************
--    10000  14999 341434 *********************************
--    15000  19999 213850 ********************
--    20000  24999 151336 **************
--    25000  29999 115502 ***********
--    30000  34999  91493 ********
--    35000  39999  75683 *******
--    40000  44999  62913 ******
--    45000  49999  52204 *****
--    50000  54999  43522 ****
--    55000  59999  35803 ***
--    60000  64999  29014 **
--    65000  69999  23343 **
--    70000  74999  18721 *
--    75000  79999  14740 *
--    80000  84999  11453 *
--    85000  89999   8781
--    90000  94999   6583
--    95000  99999   4723
--   100000 104999   3435
--   105000 109999   2437
--   110000 114999   1780
--   115000 119999   1164
--   120000 124999    825
--   125000 129999    508
--   130000 134999    320
--   135000 139999    234
--   140000 144999    135
--   145000 149999     99
--   150000 154999     52
--   155000 159999     40
--   160000 164999     31
--   165000 169999     18
--   170000 174999     14
--   175000 179999      6
--   180000 184999      7
--   185000 189999      4
--   190000 194999      1
--   195000 199999      2
--   200000 204999      4
--   205000 209999      1

-- Finished on Tue Jul 23 04:07:36 2019 (304 seconds) with 1059.77 GB free disk space
----------------------------------------
--
-- In sequence store './raspberry_nanopore.seqStore':
--   Found 267114 reads.
--   Found 12374807850 bases (42.23 times coverage).
--
--   Read length histogram (one '*' equals 525.78 reads):
--        0   4999  27790 ****************************************************
--     5000   9999  36805 **********************************************************************
--    10000  14999  21480 ****************************************
--    15000  19999  11782 **********************
--    20000  24999   5550 **********
--    25000  29999   2157 ****
--    30000  34999    768 *
--    35000  39999    303
--    40000  44999    315
--    45000  49999    529 *
--    50000  54999  14493 ***************************
--    55000  59999  32116 *************************************************************
--    60000  64999  26298 **************************************************
--    65000  69999  21079 ****************************************
--    70000  74999  16704 *******************************
--    75000  79999  13063 ************************
--    80000  84999   9956 ******************
--    85000  89999   7525 **************
--    90000  94999   5634 **********
--    95000  99999   3912 *******
--   100000 104999   2887 *****
--   105000 109999   1951 ***
--   110000 114999   1396 **
--   115000 119999    942 *
--   120000 124999    604 *
--   125000 129999    365
--   130000 134999    243
--   135000 139999    174
--   140000 144999    100
--   145000 149999     58
--   150000 154999     40
--   155000 159999     33
--   160000 164999     17
--   165000 169999     13
--   170000 174999      9
--   175000 179999      5
--   180000 184999      4
--   185000 189999      2
--   190000 194999      1
--   195000 199999      1
--   200000 204999      2
--   205000 209999      0
--   210000 214999      1
--   215000 219999      2
--   220000 224999      2

**Comment by skoren** [comment]
See the canu quick-start and FAQ. By default the longest supported 40x of data is corrected. In your case that means removing reads below about 50kb. This is expected and not a concern.

**Comment by yplee614** [comment]
But why the corrected reads histogram in 5000 and 20000 in length?

**Comment by skoren** [comment]
Canu has a read rescue feature, if there are short reads which contain sequences nor represented by the longest 40x it will select them for correction too. This is probably the chloroplast or mitochondria reads which are shorter than the genomic reads.

**Comment by yplee614** [comment]
Thanks. I have a more question, I have a 200X nanopore data, to reduce canu running time, can I pick the longest 100X raw reads (the reads length > 25000) as the input of canu?

**Comment by skoren** [comment]
I wouldn't select just the longest read, if you have a 500kb read but it's noise that's not really useful for assembly. I'd recommend a random downsampling to 100x instead, canu can do this for you using ```readSamplingCoverage```
