### ISSUE TITLE
cormhap_run have been on "H" for many days

### ISSUE THREAD

**Issue by Malabady** [marbl/canu#1430]
Hi.

out of over 1300 cormhap_run jobs, 176 jobs have been on hold "H" for many days although alll the required resources are available to them. Neither our HPC team nor I are able to diagnose and resolve the issue. there are no other canu jobs from this run are being executed, everythign is on hold.

Here are the arry jobs that are being on hold:
cormhap_run-125
...
...
cormhap_run-300

There are no *.ovb and *.oc files corresponding to those jobs in the results folder. Nor there are *.o* files. 

My questions are:
1. Do you know what is the causing this issue and how to fix the problem? 
2. If I kill all those on-hold jobs and restart the canu script, will it pick from where it stopped? I know it will in normal cases, but not sure if that true when jobs were purposely killed. 

Thank you for your help. 
Magdy

**Comment by skoren** [comment]
No idea why the jobs would hold, that's usually either the scheduler or the user requesting a hold. If you kill the jobs, canu will re-launch the killed ones, it doesn't care why they failed just that they failed.

**Comment by Malabady** [comment]
Thank you! that exactly what I hope to hear 👍
