### ISSUE TITLE
No raw reads detected. Cannot proceed; empty outputs generated.

### ISSUE THREAD

**Issue by cmaggior** [marbl/canu#1433]
Using the following canu command: canu-1.8/*/bin/canu -correct -p FullCryoCorrect -d FullCryoCorrect genomeSize=4.7m corOutCoverage=10000 corMhapSensitivity=high maxMemory=6 stopOnLowCoverage=0 saveReadCorrections=true -nanopore-raw All_seqs_FullCryo.fastq

Gives the error: No raw reads detected. Cannot proceed; empty outputs generated.

In the error log, it says that the reads are either too short have invalid headers. Example: read '' of length 0 in file '/home/whyte/Catherine/FullCryo_Jul15-18/All_seqs_FullCryo.fastq' at line 1 is too short, skipping.
invalid read header '' in file '/home/whyte/Catherine/FullCryo_Jul15-18/All_seqs_FullCryo.fastq' at line 2, skipping.

The reads don't appear too short and the headers should be valid. Can you please advise?

**Comment by skoren** [comment]
Too short is defined by default to be 1000. Canu isn't designed for reads shorter than that though you can lower it manually. Your fastq seems to be malformed based on these errors though. Send your fastq file to the FTP again, I don't think it properly got transferred last time.

**Comment by cmaggior** [comment]
Re-sent.

**Comment by skoren** [comment]
I don't see anything on the FTP site, are you using the instructions here:
https://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you

**Comment by cmaggior** [comment]
Yes, the remote server is closing the connection when I try now. Is there something else I can do to send you the file?

**Comment by skoren** [comment]
How big is the read set? You could try gzipping it and emailing it to me (sergek@umd.edu)

**Comment by skoren** [comment]
Your reads file is definitely invalid, it has lots of unprintable characters at the beginning of the lines, for example:
```
??@fa4c032c-ebd0-49c4-b1de-548c15090aab runid=0963a1934ab1f29b4d9bb1cde17e93f050579507 read=3 ch=10 start_time=2018-07-15T20:09:51Z
```
that's not a valid fastq format. Canu is rightly complaining your input is invalid and throwing out malformed reads. This ends up with no data left. Your sequence lines are similarly corrupted with extra characters:
```
^@T^@T^@G^@G
```

This seems like not an ASCII file, UTF-16 unicode according to @brianwalenz. How did you get this file? Running ```iconv -f UTF-16 -t ASCII All_seqs_FullCryo.fastq > tmp.fq``` should fix it or you should generate it again and not use unicode.
