### ISSUE TITLE
gridEngineMemoryOption: Use a specific machine on SGE cluster

### ISSUE THREAD

**Issue by etvedte** [marbl/canu#1434]
Version: canu-1.8

System: SGE

I'm using canu to generate assemblies of long read data generated using different sequencing technologies. For this project, I'd like to restrict canu to using specific machines on the SGE grid so I can directly compare assembly time/compute time/memory usage of various assemblies.

The following command works on my SGE system:

/usr/local/packages/canu-1.8/bin/canu -p dir.prefix -d output/dir/ genomeSize=4.6m  gridEngineThreadsOption="-pe thread THREADS" gridEngineMemoryOption="-l mem_free=MEMORY" gridOptions="-q threaded.q" -nanopore-raw reads.fastq.gz

On our grid, specification of certain machines and exclusive use of machines falls under the -l parameter, e.g. 

echo -e "some/sample/command -i input -o output" | qsub -l mem_free=2G  hostname=sample.node.name excl=true 

However, when I try adding that to gridEngineMemoryOption, canu cannot interpret multiple -l arguments:

/usr/local/packages/canu-1.8/bin/canu -p dir.prefix -d output/dir/ genomeSize=4.6m  gridEngineThreadsOption="-pe thread THREADS" gridEngineMemoryOption="-l mem_free=MEMORY excl=true" gridOptions="-q threaded.q" -nanopore-raw reads.fastq.gz

RESULT: Couldn't parse gridEngineMemoryOption='-l mem_free=MEMORY excl=true'.

Do you have any suggestions for specifying machines on SGE? Apologies if this has been addressed before. I looked on Canu FAQ and github issues and could not find similar questions. Thanks in advance.

Eric

**Comment by skoren** [comment]
The memory option shouldn't be overloaded to add other options. If you want to pass a parameter to all jobs, there is the gridOptions parameter, see the FAQ on using a grid (https://canu.readthedocs.io/en/latest/faq.html#how-do-i-run-canu-on-my-slurm-sge-pbs-lsf-torque-system). SGE can support multiple -l parameters so there's no reason you can't use:
```
gridEngineThreadsOption="-pe thread THREADS" gridEngineMemoryOption="-l mem_free=MEMORY" gridOptions="-q threaded.q -l hostname=sample.node.name excl=true"
```

The canu 1.9 branch doesn't have this check so you could also switch to that but adding multiple -l options should suffice.

**Comment by etvedte** [comment]
Thanks for the prompt response. I'll try this now and re-open the issue if I need additional assistance.
