### ISSUE TITLE
Canu - reads longer then 2097151 bp

### ISSUE THREAD

**Issue by mjpdejong** [marbl/canu#1436]
I am running into something that seems like a bug with ONT reads that are over 2097151 bp. With the latest basecalling improvements some of these reads are starting to pass my Q filters.

It seems that after the encoutering of the very long read the import of data is truncated/parsing is broken and all reads thereafter no longer correctly imported. The seqStore report shows fasta imported reads, which are definately not in my bundled fastq. This causes Canu to crash later on.

I am ofcourse able to detect and remove reads that are too long, but this doesn't seem to be correct behaviour.

This is the 2nd time I have encountered this problem though. Removing the long read with for example sed solves the problem for me.

Greets,
Marco

```
canu --version
Canu snapshot v1.8 +261 changes (r9471 093a51f41fcb7029a81dfd7663ee5aa4e44e2110)
```

```
head ~/Path/2_DataAssembly/Samplename/1_canu_8K8BE/Samplename_8K8BE.seqStore/errorLog
read '2c7405d0-54e2-411d-a28c-707b6eb5afaa runid=79a002baddbf66f10975776b0bded9a86246f3bc sampleid=180703_PAC20173 read=142180 ch=1448 start_time=2018-07-05T08:19:49Z' is too long; contains 2099815 bases, but we can only handle 2097151.
invalid read header 'TGCTTATTCATCCTTTCTAGATTTTCCAAATGCGGGGCAT...' in file '~/Path/1_DataImport/nanopore_OP4YZ/Bundle/Bundle_prtr_adtr_potr.fastq' at line 3310756, skipping.
invalid read header '+' in file '~/Path/1_DataImport/nanopore_OP4YZ/Bundle/Bundle_prtr_adtr_potr.fastq' at line 3310757, skipping.
invalid read header '%%%&&9-/4;<6;8=29'%%%18874747840$$&.;9:<...' in file '~/Path/1_DataImport/nanopore_OP4YZ/Bundle/Bundle_prtr_adtr_potr.fastq' at line 3310758, skipping.
invalid read header 'GCTGAAAAGAAAAGAAAATCCAGTTAGGCGGAAGGATAAA...' in file '~/Path/1_DataImport/nanopore_OP4YZ/Bundle/Bundle_prtr_adtr_potr.fastq' at line 3310764, skipping.
invalid read header '+' in file '~/Path/1_DataImport/nanopore_OP4YZ/Bundle/Bundle_prtr_adtr_potr.fastq' at line 3310765, skipping.
invalid read header '&%%%(((('0032&&,2:((3+&10(/1'.2',6630-0/...' in file '~/Path/1_DataImport/nanopore_OP4YZ/Bundle/Bundle_prtr_adtr_potr.fastq' at line 3310766, skipping.
invalid read header 'CAATCAAGAAAATAAAGGGATTACCCACACGATGGGTGAG...' in file '~/Path/1_DataImport/nanopore_OP4YZ/Bundle/Bundle_prtr_adtr_potr.fastq' at line 3310772, skipping.
invalid read header '+' in file '~/Path/1_DataImport/nanopore_OP4YZ/Bundle/Bundle_prtr_adtr_potr.fastq' at line 3310773, skipping.
invalid read header '((().%'&(+88.263('&&$%)')*$&%./0'',3''(*...' in file '~/Path/1_DataImport/nanopore_OP4YZ/Bundle/Bundle_prtr_adtr_potr.fastq' at line 3310774, skipping.
```

```
Starting file './Samplename_8K8BE.seqStore.ssi'.

  Loading reads from '~/Path/1_DataImport/nanopore_OP4YZ/Bundle/Bundle_prtr_adtr_potr.fastq'
    Processed 28077035 lines.
    Loaded 179772373228 bp from:
      84385 FASTA format reads (150152748156 bp).
      662173 FASTQ format reads (29619625072 bp).
    WARNING: 144786 reads issued a warning.

Finished with:
  144786 warnings (bad base or qv, too short, too long)

Loaded into store:
  179772373228 bp.
  746558 reads.

Skipped (too short):
  0 bp (0.0000%).
  0 reads (0.0000%).


sqStoreCreate finished successfully.
```

**Comment by skoren** [comment]
There is a 2mb max read limit, that is correct. We've seen 6mb reads with recent base callers as well but they all seem like noise so I don't expect your 2mb read is real either. There  was a bug in 1.8 which didn't trim off the rest of the too long read so that read ended up duplicated in the store but no other reads are affected. The crash is unrelated, you're not using a release but a tip version with some large scale untested changes. I would suggest updating to the 1.9 branch
```
git checkout v1.9
rm -r Linux-amd64
make
```
which will both fix the 2mb parsing bug and your other crash and will be more stable than what you're using now.

If you want to increase the limit from 2mb you can, edit sqStore.H to increase the bits from 21:
```
#define AS_MAX_READLEN_BITS        21
```
22 will give you 4mb and 23 will give you 8mb maximums.

**Comment by mjpdejong** [comment]
Thanks for the reply.

I agree that most of these reads are likely not real, and one or two of these long reads are not going to make a significant difference anyway. The behavior seemed a bug, so therefore I raised this issue. I was using this tip due to a feature you recently added some time ago. I'll try again after updating to the latest stable version.

Greets,
Marco

**Comment by skoren** [comment]
Confirmed, 1.9 branch correctly handles very long reads (warns and truncates), reopen if you encounter errors with that branch.
