### ISSUE TITLE
java version issue

### ISSUE THREAD

**Issue by igsbma** [marbl/canu#144]
Hi there, when I submitted my jobs

>canu -p ecoli -d ecoli-auto  genomeSize=4.8m  -pacbio-raw p6.25x.fastq 
it says:
-- Detected Java(TM) Runtime Environment '1.8.0_45' (from 'java').

but in "canu.01.out", it says:

ERROR:  mhap overlapper requires java version at least 1.8.0; you have unknown

please advice! thank you!

**Comment by brianwalenz** [comment]
This is likely a difference between the head node and the compute node.  Set canu option java=/path/to/java, to wherever the default java lives.

Possibly, java=`which java` will work.

**Comment by igsbma** [comment]
Thanks Brian for your speedy response. I am very new to canu. Can you advice where to set the canu option?

**Comment by brianwalenz** [comment]
One the command line:

canu -p <prefix> -d <directory> java=/path/to/java <other options> -pacbio-raw ...

**Comment by igsbma** [comment]
Thanks Brian, I did, but still got  this error

-- Detected Java(TM) Runtime Environment 'unknown' (from '/XX/XX/software/jre1.8.0_45/bin/java')
XXX
ERROR:  mhap overlapper requires java version at least 1.8.0; you have unknown

**Comment by igsbma** [comment]
$ java -version
Picked up _JAVA_OPTIONS: -Xms512m -Xmx12288m
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**Comment by brianwalenz** [comment]
Same -version string if run with the full path?

**Comment by igsbma** [comment]
yes, same -version.

**Comment by igsbma** [comment]
it is weird to me that when I submit the jobs it shows 
"-- Detected Java(TM) Runtime Environment '1.8.0_40' (from '/usr/local/packages/java-jre-1.8.0/bin/java')." 
but in the canu.01.out, it shows
"-- Detected Java(TM) Runtime Environment 'unknown' (from '/usr/local/packages/java-jre-1.8.0/bin/java')."

**Comment by brianwalenz** [comment]
Yup, it's a difference between -version and -showversion.  I don't know which is correct.

src/pipelines/canu/Defaults.pm at around line 1167 has the test.  I'd suggest just commenting this out for now.

**Comment by igsbma** [comment]
I have specify that I have a jre1.8.0_45 installed in my own directory, and jre-1.8.0 globally on server. 

I comment out 
#addCommandLineError("ERROR:  mhap overlapper requires java version at least 1.8.0; you have $versionStr\n")   if ($version < 1.8);

But, it gives the same error message even I commented it out!

**Comment by brianwalenz** [comment]
Or maybe not (-version vs -showversion).  I have no idea.

Can you paste in the output of java -showversion on your head node and a compute node?

You need to 'make' in the src/ directory again.

**Comment by igsbma** [comment]
java -showversion
Picked up _JAVA_OPTIONS: -Xms512m -Xmx12288m
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

do you mean "computer node"?

**Comment by brianwalenz** [comment]
Wherever the job is running - SGE, Slurm, etc.  The error isn't when you run locally, it is when it is running on your grid.

**Comment by igsbma** [comment]
I "make" it and remove the specific java path, and the java error is gone.

when run on SGE cluster, I don't know which node it runs on, but I thought it should use my local settings?

**Comment by igsbma** [comment]
it runs but the problem persists. at step 05 it failed again. 

$ head -1 *.out
==> canu.01.out <==
-- Detected Java(TM) Runtime Environment 'unknown' (from 'java').

==> canu.02.out <==
-- Detected Java(TM) Runtime Environment 'unknown' (from 'java').

==> canu.03.out <==
-- Detected Java(TM) Runtime Environment 'unknown' (from 'java').

==> canu.04.out <==
-- Detected Java(TM) Runtime Environment 'unknown' (from 'java').

**Comment by brianwalenz** [comment]
It is.  I think the error is that the java found on the head node isn't found (or isn't installed) on the compute nodes.  Not much I can fix here - ask around to see how to run java programs on your cluster.

**Comment by igsbma** [comment]
thanks Brian.

**Comment by igsbma** [comment]
Hi Brian, is there anyway not to run canu on grid? thanks!

**Comment by brianwalenz** [comment]
Yeah, that's easy:  useGrid=false

**Comment by igsbma** [comment]
thanks Brian, works since!

**Comment by kk86bioinfo** [comment]
Same error using latest build. I try to print the line before the following:

```
        open(F, "$java -showversion 2>&1 |");
        while (<F>) {
            #  First word is either "java" or "openjdk" or ...
            if (m/^.*\s+version\s+\"(\d+.\d+)(.*)\".*$/) {
                $versionStr = "$1$2";
                $version    =  $1;
            }
            print STDERR "[INFO] capture java '$java' '$version' \n";
        }
        close(F);
```

It is always print default values of 'java' and '0'.

And the following log files is always generated for every run.

```
---------- 1 ubuntu ubuntu    0 Jan 10  1972 hs_err_pid19441.log
---------- 1 ubuntu ubuntu    0 Jan 10  1972 hs_err_pid19476.log
---------- 1 ubuntu ubuntu    0 Jan  6  1972 hs_err_pid55503.log
---------- 1 ubuntu ubuntu    0 Jan 14  1972 hs_err_pid58451.log
---------- 1 ubuntu ubuntu    0 Jan 14  1972 hs_err_pid58486.log
---------- 1 ubuntu ubuntu    0 Jan 15  1972 hs_err_pid58921.log
---------- 1 ubuntu ubuntu    0 Jan 15  1972 hs_err_pid58965.log
---------- 1 ubuntu ubuntu    0 Jan 16  1972 hs_err_pid59505.log
---------- 1 ubuntu ubuntu    0 Jan 16  1972 hs_err_pid59506.log
---------- 1 ubuntu ubuntu    0 Jan 16  1972 hs_err_pid59575.log
---------- 1 ubuntu ubuntu    0 Jan 16  1972 hs_err_pid59578.log
---------- 1 ubuntu ubuntu    0 Jan  6  1972 hs_err_pid72818.log
---------- 1 ubuntu ubuntu    0 Jan 17  1972 hs_err_pid73477.log
---------- 1 ubuntu ubuntu    0 Jan 17  1972 hs_err_pid73512.log
```

With lost permission to access those log files.

I think the function to check Java is not right for this version of canu. I remember a few months back running will not have such case. Would need to check back this.

canu.09.out
```
ERROR:  mhap overlapper requires java version at least 1.8.0; you have unknown (from 'java').
ERROR:  'java -showversion' reports:
ERROR:    '[thread 47026599409408 also had an error][thread 47026263160576 also had an error][thread 47026264213248 also had an error][thread 47026260002560 also had an error][thread 47026600462080 also had an error][thread 47026258949888 also had an error][thread 47026603620096 also had an error]#'
ERROR:    ''
ERROR:    ''
ERROR:    ''
ERROR:    ''
ERROR:    ''
ERROR:    ''
ERROR:    '[thread 47026596251392 also had an error]Error occurred during initialization of VM'
ERROR:    ''
ERROR:    '# There is insufficient memory for the Java Runtime Environment to continue.'
ERROR:    '[thread 47026597304064 also had an error]Unable to allocate 61056KB bitmaps for parallel garbage collection for the requested 1953792KB heap.# '
ERROR:    'pthread_getattr_np'
ERROR:    ''
ERROR:    ''
ERROR:    'Error: Could not create the Java Virtual Machine.'
ERROR:    'Error: A fatal exception has occurred. Program will exit.'
```

**Comment by kk86bioinfo** [comment]
I have no choice to hard code all the default value to proper java settings in my clusters. Now all are running. I think "JAVA_HOME" may cause the error if a server has set that variable with empty value.

**Comment by skoren** [comment]
The error you pasted above is not a version issue but the JVM not being able to start up properly. Having an empty JAVA_HOME is OK, however, if you have JAVA_HOME set on your head node to a version that doesn't work on the compute nodes. In that case, setting java=java or java=<full path to java that works on compute nodes> should work.

**Comment by kk86bioinfo** [comment]
But everything work fine when I bypass the Java version test, I have completed two cycle of canu with different parameters with the following hard cored bypass.

```
$global{"java"}                        = "/usr/bin/java";
```

```
    if ((getGlobal("corOverlapper") eq "mhap") ||
        (getGlobal("obtOverlapper") eq "mhap") ||
        (getGlobal("utgOverlapper") eq "mhap")) {
        my $java       = getGlobal("java");
        my $versionStr = "1.8.0_91";
        my $version    = 1.8;

        #  Argh, we can't use runCommand() here, because we're included in Execution.pm.  Try to check it with -x.
        #  Nope.  Fails if $java == "java".

        #if (! -x $java) {
        #    addCommandLineError("ERROR:  java executable '$java' not found or not executable\n");
        #}
```

at `src/pipelines/canu/Defaults.pm` and recompile with `make -j 48`

Java on all of my nodes are working properly, have test with running commands `java -version`, 'java -showversion` and `canu` in all of the nodes respectively.

**Comment by skoren** [comment]
The environment Canu is running in must be different from the environment where you were testing. You can see in the log you posted Canu is reporting the full output from java -showversion which reports an exception.

Have you checked in the Canu logs (correction/1-overlapper/precompute.*.out) which java binary is being used, is it the default in your path and the same you were doing the testing with?

**Comment by kk86bioinfo** [comment]
@skoren , sorry, the files have been removed. I have completed 3 times of canu assemblies with my workaround. I have actually tested all of my cluster nodes with ```java -showversion 2>&1``` as per what the script does in every of my cluster nodes. All of them return correct version of my java installed (version 1.8.0_91) path at java. I do not set env parameter JAVA_HOME, when ```print $JAVA_HOME``` it would be empty and my java is installed at ```/usr/bin/java``` by Ubuntu Java 8 repository through ```apt-get```. Hope it helps to clarify the condition. I suspect some of the jar files (possible mhap) is actually failed to recognize java path, but that is beyond my scope to validate.

**Comment by skoren** [comment]
Nope, the jar doesn't matter, the check happens way before any java program is executed and if your patch to not check version works it means the mhap jar runs fine. It is an environment/jvm issue on your system since you can see showversion is crashing:
```
ERROR:  'java -showversion' reports:
ERROR:    '[thread 47026599409408 also had an error][thread 47026263160576 also had an error][thread 47026264213248 also had an error][thread 47026260002560 also had an error][thread 47026600462080 also had an error][thread 47026258949888 also had an error][thread 47026603620096 also had an error]#'
ERROR:    ''
ERROR:    ''
ERROR:    ''
ERROR:    ''
ERROR:    ''
ERROR:    ''
ERROR:    '[thread 47026596251392 also had an error]Error occurred during initialization of VM'
ERROR:    ''
ERROR:    '# There is insufficient memory for the Java Runtime Environment to continue.'
ERROR:    '[thread 47026597304064 also had an error]Unable to allocate 61056KB bitmaps for parallel garbage collection for the requested 1953792KB heap.# '
ERROR:    'pthread_getattr_np'
ERROR:    ''
ERROR:    ''
ERROR:    'Error: Could not create the Java Virtual Machine.'
ERROR:    'Error: A fatal exception has occurred. Program will exit.'
```

Your JVM might be set up to use more memory than Canu requests by default (4gb). You can see the defaults (in bytes) using
```
% java -XX:+PrintFlagsFinal -version | grep HeapSize
    uintx InitialHeapSize                          := 1983905792      {product}
    uintx MaxHeapSize                              := 31715229696     {product}
```
In my case the default initial heap size is 2g and the default max is 32g. If yours is >4g that could be causing a problem since Canu only requests 4g to run. You can try updating the -showversion command to add -Xmx1g and see if it is fixed.

**Comment by lamz138138** [comment]
Hi,

**Comment by lamz138138** [comment]
Hi!

Did you find the reason at last@kk86bioinfo@skoren? I agree with kk86bioinfo that some module may failed to deal with the -showversion in new java version, considering there are more output of "-showversion" than "-version". 

I had tried with different methods, for example, export the PATH of java, and give "-V" to gridOptions, "java=/path/to/java" was also added. But none worked. At last, I set "JAVA_HOME" it the ~/.bashrc file that solve my problem. 

So, I just leave my solution here for someone who may encounter the same problem. Besides, I am interesting in the reason of this problem, and hope someone would give me an answer.

Best wishes!

**Comment by unalibun** [comment]
Hi, I have the same error. I am trying to run Canu for a Fungus genome, This is my config.sh file 

#$ -q all.q
#$ -V
#$ -cwd

module load CANU/1.8

canu -d /Storage/data2/sandra.gonzalez/PacBio/assembly/Canu -p p_ulei_canu genomeSize=85m -correctedErrorRate=0.045 java=/Storage/progs/jdk1.8.0_191/bin/java  -pacbio-raw /Storage/data2/sandra.gonzalez/PacBio/rawdata/20190118/release/Result/00.RawData/SPseuL/PseuL*.fasta gridEngineMemoryOption="-l h_vmem=MEMORY"
#gridEngineThreadsOption="-pe make THREADS" 

I work in a server managed by SGE 

This is what said my canu.out 

ERROR:  mhap overlapper requires java version at least 1.8.0; you have unknown (from '/Storage/progs/jdk1.8.0_191/bin/java').
ERROR:  '/Storage/progs/jdk1.8.0_191/bin/java -Xmx1g -showversion' reports:
ERROR:    'Error occurred during initialization of VM'
ERROR:    'java.lang.OutOfMemoryError: unable to create new native thread' " 

This is the output of my qsub error report 

CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_191' (from '/Storage/progs/jdk1.8.0_191/bin/java') with -d64 support.
--
-- WARNING:
-- WARNING:  Failed to run gnuplot using command 'gnuplot'.
-- WARNING:  Plots will be disabled.
-- WARNING:
--
-- Detected 56 CPUs and 567 gigabytes of memory.
-- Detected Sun Grid Engine in '/Storage/progs/sge/default'.
-- Detected Grid Engine environment 'smp'.
-- User supplied Grid Engine consumable '-l h_vmem=MEMORY'.
-- 
-- Found   1 host  with  24 cores and  141 GB memory under Sun Grid Engine control.
-- Found   1 host  with  56 cores and  566 GB memory under Sun Grid Engine control.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl     12 GB    4 CPUs  (k-mer counting)
-- Grid:  hap        8 GB    4 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   13 GB    8 CPUs  (overlap detection with mhap)
-- Grid:  obtovl     8 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl     8 GB    8 CPUs  (overlap detection)
-- Grid:  ovb        4 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs        8 GB    1 CPU   (overlap store sorting)
-- Grid:  red       10 GB    4 CPUs  (read error detection)
-- Grid:  oea        4 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat       64 GB    8 CPUs  (contig construction with bogart)
-- Grid:  gfa        8 GB    8 CPUs  (GFA alignment and processing)
--
-- Found PacBio uncorrected reads in the input files.
--
-- Generating assembly 'p_ulei_canu' in '/Storage/data2/sandra.gonzalez/PacBio/assembly/Canu'
--
-- Parameters:
genomeSize        85000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0450 (  4.50%)
--
--
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Thu May 30 16:48:40 2019 with 12209.138 GB free disk space

    cd .
    /Storage/progs/canu-1.8/Linux-amd64/bin/sqStoreCreate \
      -o ./p_ulei_canu.seqStore.BUILDING \
      -minlength 1000 \
      ./p_ulei_canu.seqStore.ssi \
    > ./p_ulei_canu.seqStore.BUILDING.err 2>&1

-- Finished on Thu May 30 16:52:46 2019 (246 seconds) with 12206.397 GB free disk space
----------------------------------------
--
-- WARNING: gnuplot failed.
--
----------------------------------------
--
-- In sequence store './p_ulei_canu.seqStore':
--   Found 1686151 reads.
--   Found 10335634849 bases (121.59 times coverage).
--
--   Read length histogram (one '*' equals 12182.4 reads):
--        0   4999 852768 **********************************************************************
--     5000   9999 603203 *************************************************
--    10000  14999 155178 ************
--     15000  19999  41240 ***
--    20000  24999  13722 *
--    25000  29999   6077 
--    30000  34999   3686 
--    35000  39999   2604 
--    40000  44999   1912 
--    45000  49999   1358 
--    50000  54999    996 
--    55000  59999    690 
--    60000  64999    563 
--    65000  69999    445 
--    70000  74999    330 
--    75000  79999    280 
--    80000  84999    245 
--    85000  89999    193 
--    90000  94999    151 
--    95000  99999    103 
--   100000 104999     84 
--   105000 109999     63 
--   110000 114999     60 
--   115000 119999     51 
--   120000 124999     31 
--   125000 129999     28 
--   130000 134999     24 
--   135000 139999     17 
--   140000 144999     14 
--   145000 149999     10 
--   150000 154999      2 
--   155000 159999      5 
--   160000 164999      3 
--   165000 169999      2 
--   170000 174999      5 
--   175000 179999      1 
--   180000 184999      4 
--   185000 189999      1 

-- Starting command on Thu May 30 16:53:00 2019 with 12206.389 GB free disk space

    cd correction/0-mercounts
    ./meryl-configure.sh \
    > ./meryl-configure.err 2>&1

-- Finished on Thu May 30 16:53:02 2019 (2 seconds) with 12206.388 GB free disk space
----------------------------------------
--  segments   memory batches
--  -------- -------- -------
--        01 12.00 GB       2
--        02 11.00 GB       2
--        04  6.00 GB       1
--        06  4.00 GB       1
--        08  3.00 GB       1
--        12  2.00 GB       1
--        16  1.69 GB       1
--        20  1.38 GB       1
--        24  1.12 GB       1
--        32  0.88 GB       1
--        40  0.69 GB       1
--        48  0.56 GB       1
--        56  0.50 GB       1
--        64  0.44 GB       1
--        96  0.31 GB       1
--
--  For 1686151 reads with 10335634849 bases, limit to 103 batches.
--  Will count kmers using 04 jobs, each using 7 GB and 4 threads.
--
-- Finished stage 'merylConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
--
-- 'meryl-count.jobSubmit-01.sh' -> job 5550 tasks 1-4.
----------------------------------------
-- Starting command on Thu May 30 16:53:03 2019 with 12206.388 GB free disk space

    cd /Storage/data2/sandra.gonzalez/PacBio/assembly/Canu
    qsub \
      -hold_jid 5550 \
      -l h_vmem=4g \
      -pe smp 1   \
      -cwd \
      -N 'canu_p_ulei_canu' \
      -j y \
      -o canu-scripts/canu.01.out  canu-scripts/canu.01.sh

-- Finished on Thu May 30 16:53:03 2019 (like a bat out of hell) with 12206.388 GB free disk space

My java version 

openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

Finally, I try to put the java executable PATH 

But it is imposible to run 

Some advice? 

Thanks

**Comment by skoren** [comment]
Your JVM appears to be broken on the instance where canu is running. The error is coming from just trying to get the JVM version:
```
/Storage/progs/jdk1.8.0_191/bin/java -Xmx1g -showversion' reports:
ERROR:    'Error occurred during initialization of VM'
ERROR:    'java.lang.OutOfMemoryError: unable to create new native thread'
```

So the JVM is failing to run even to report a version. It may be due to how you're requesting memory, h_vmem is usually not consumable and you want a consumable resource of memory to ensure you have enough memory available. In this case canu asked for 4gb, tried to use 1gb for the JVM, and failed.

**Comment by unalibun** [comment]
Hi Skoren, 

Thanks for your answer. Should I set up the memory again? or just running with the useGrid=FALSE option and set up the memory and threads options?

Best, and thank you once again

**Comment by skoren** [comment]
You could run with useGrid=false, assuming whatever instance you reserve for that run has memory reserved and a working JVM. I'd try to track down how to reserve memory on the node, see other issues (for example #40) for the commands to find a consumable memory resource.

**Comment by bifxcore** [comment]
I am having the same issue. I am running on PBSpro and I have explicitly set the Java version to 1.8 with:

`module load Java/1.8.0_171
`

I logged in to one of our compute nodes to check the java version and I get:
```
~$ java -Xmx1g -showversion
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```

Still CANU crashes with:

`ERROR:  mhap overlapper requires java version at least 1.8.0; you have 1.7.0_191 (from 'java').
`

**Comment by skoren** [comment]
This is likely the same issue as the original comment, even though you load the right version of java on the node you start canu on, when it runs on other nodes on the cluster you end up with the older default version instead (your module load is never run). You should explicitly set the java path by giving it to canu (```java=path to java 1.8```).

**Comment by bifxcore** [comment]
Thanks Sergey, I ended up running it on one node with useGrid=false.
