### ISSUE TITLE
Mhap overlap jobs failed during correction

### ISSUE THREAD

**Issue by hungweichen0327** [marbl/canu#1444]
Hello,

I am a beginner of bioinformatics. I use Canu (version 1.8) for correction on serverbut it failed. The input coverage is about 41X. The command I use is below:

The content below is the script I used in the q file:
```
/home/hpc/crlee/softwares/canu-1.8/Linux-amd64/bin/canu -correct -p Crystal_chunk1_1kb -d ./Crystal_chunk1_canu_v1.8 genomeSize=580m minReadLength=1000 corOutCoverage=60 stopOnReadQuality=false -nanopore-raw ./Crystal_all_porechop_c1.fastq
````

And the output file showed:
```
 Mhap overlap jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/results/000001.ovb FAILED.
--   job correction/1-overlapper/results/000003.ovb FAILED.
--   job correction/1-overlapper/results/000006.ovb FAILED.
--   job correction/1-overlapper/results/000009.ovb FAILED.
--   job correction/1-overlapper/results/000010.ovb FAILED.
--   job correction/1-overlapper/results/000012.ovb FAILED.
--   job correction/1-overlapper/results/000013.ovb FAILED.
--   job correction/1-overlapper/results/000017.ovb FAILED.
--   job correction/1-overlapper/results/000026.ovb FAILED.
--   job correction/1-overlapper/results/000028.ovb FAILED.
--   job correction/1-overlapper/results/000030.ovb FAILED.
--

ABORT:
ABORT: Canu 1.8
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
```

Thank you for reading my question and any suggestions are welcome.

**Comment by skoren** [comment]
This is usually an issue with the JVM or memory, I assume you're running on a grid? Post the canu preamble (where it reports resources it plans to use) and the output of one of the failing jobs (```correction/1-overlapper/mhap.*30.out``` or similar).

**Comment by hungweichen0327** [comment]
Dear Sergey Koren,

Thank you for the fast reply. To be honest, I am not sure whether I am running on a grid (What does grid mean? Sorry I am a bioinformatics beginner). I ran it on server computer. 

I don't know where the canu preamble showed? Is the information below?
```
CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0' (from 'java') with -d64 support.
-- Detected gnuplot version '4.2 patchlevel 6 ' (from 'gnuplot') and image format 'png'.
-- Detected 80 CPUs and 2018 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |     total usage     algorithm
--        -------  ------  --------   --------  -----------------  -----------------------------
-- Local: meryl     24 GB    8 CPUs x  10 jobs   240 GB   80 CPUs  (k-mer counting)
-- Local: hap       12 GB   20 CPUs x   4 jobs    48 GB   80 CPUs  (read-to-haplotype assignment)
-- Local: cormhap   32 GB   16 CPUs x   5 jobs   160 GB   80 CPUs  (overlap detection with mhap)
-- Local: obtovl    16 GB   16 CPUs x   5 jobs    80 GB   80 CPUs  (overlap detection)
-- Local: utgovl    16 GB   16 CPUs x   5 jobs    80 GB   80 CPUs  (overlap detection)
-- Local: ovb        4 GB    1 CPU  x  80 jobs   320 GB   80 CPUs  (overlap store bucketizer)
-- Local: ovs       16 GB    1 CPU  x  80 jobs  1280 GB   80 CPUs  (overlap store sorting)
-- Local: red       12 GB    8 CPUs x  10 jobs   120 GB   80 CPUs  (read error detection)
-- Local: oea        4 GB    1 CPU  x  80 jobs   320 GB   80 CPUs  (overlap error adjustment)
-- Local: bat      256 GB   16 CPUs x   1 job    256 GB   16 CPUs  (contig construction with bogart)
-- Local: gfa       16 GB   16 CPUs x   1 job     16 GB   16 CPUs  (GFA alignment and processing)
```

The file below is the mhap.000063.out (I change the filename extension from .out to .txt for uploading)
[mhap.000063.txt](https://github.com/marbl/canu/files/3507978/mhap.000063.txt)

The hardware of the server computer is below:

large queue:
CPU: Intel E7-8870 2.40GHz 
core: 80 CPU cores
RAM: 2TB memory

My setting:
```
#!/bin/bash
#PBS -q large
#PBS -l nodes=1:ppn=20

/home/hpc/crlee/softwares/canu-1.8/Linux-amd64/bin/canu -correct -p Crystal_chunk1_1kb -d ./Crystal_chunk1_canu_v1.8 genomeSize=580m minReadLength=1000 corOutCoverage=60 stopOnReadQuality=false -nanopore-raw ./Crystal_all_porechop_c1.fastq
```

If you need any more information for debug, I am willing to provide. Thank you!


Best wishes,
Hung-Wei

**Comment by skoren** [comment]
The logs indicate you have bad intermediate outputs. Is it possible you're running out of disk space? How much free space does canu report you have and do you have any quotas? If you have space, remove the files in ```correction/1-overlapper/results/*mhap*```. Then you can re-start with the same Canu command you were using before.

Another issue, from your script it looks like you're on a PBS cluster. You're reserving 20 cores on the node but Canu will detect the full instance and assume it can use all of it. Case in point, it intends to use 160gb and 80 cores on your system for this step.
```
-- Local: cormhap   32 GB   16 CPUs x   5 jobs   160 GB   80 CPUs  (overlap detection with mhap)
```
Your jobs may be getting killed by the PBS scheduler because you are using more resources than you asked for. I suggest reserving the full node for the run to avoid this.

**Comment by hungweichen0327** [comment]
Dear Sergey Koren,

Thank you for the suggestions and help. I removed the files in correction/1-overlapper/results/*mhap* and the correction process is still running. I will give you feedback if the correction succeed in the end.

**Comment by hungweichen0327** [comment]
Dear Sergey Koren,

I obtained the final corrected reads after following your suggestions. Thanks!
One more thing I found is that the largest read is removed after Canu correction. Is that becasue the largest read is categorized in w/ overlaps for Canu? Therefore, this read will not included in the final fasta file.

**Comment by skoren** [comment]
The largest read may not be a real read, correction will trim/remove reads that don't have support from other data. It may also be a read that has both forward and reverse strand in one sequence. In these cases, Canu will keep the longest supported region of a read, unless that ends up too short to be worth outputting. The output sequence uses the same readIDs as the input so you can see if that longest read ended up being trimmed to a subset of its input length.
