### ISSUE TITLE
gatekeeperDumpFASTQ error

### ISSUE THREAD

**Issue by tangerzhang** [marbl/canu#1447]
**Command line**
```
canu -s spec.txt -p dipJH -d asm genomeSize=3g -pacbio-raw *.fasta.gz gnuplotTested=true
```
**Version:**
```
Canu 1.7
```
Grid: PBS

Error message when running the following command line:
```
    /public/home/fzmju_edu_denovo/biotools/canu-1.7/Linux-amd64/bin/gatekeeperDumpFASTQ \
      -corrected \
      -G ./dipJH.gkpStore \
      -o ./dipJH.correctedReads.gz \
      -fasta \
      -nolibname \
    > dipJH.correctedReads.fasta.err 2>&1
```

```
Dumping reads from 1 to 20432331 (inclusive).
Index error in read 1 mPtr 319136261192 pID 0 expected BLOB, got 10 14 14 0a '^P^T^T
'
gatekeeperDumpFASTQ: stores/gkStore.C:422: void gkReadData::gkReadData_loadFromBlob(uint8*): Assertion `blob[0] == 'B'' fa

Failed with 'Aborted'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::97 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
stores/gkStore.C::422 in _ZN10gkReadData23gkReadData_loadFromBlobEPh()
stores/gkStore.C::62 in _ZN6gkRead25gkRead_loadDataFromStreamEP10gkReadDataP8_IO_FILE()
stores/gatekeeperDumpFASTQ.C::422 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
```

**Comment by skoren** [comment]
This looks like you've got disk corruption or other filesystem issue, it tried to read a block of sequence and got unexpected results. I think you've had issues with your FS before based on previous issues. Version 1.7 is quite old so I would recommend updating to at least 1.8 or better the 1.9 branch and re-starting. 

You did finish correction with this step so you could see if you can dump any reads, modify the above command to try add ```-r 2``` or other values and see if that works. If it does, you could try ```-r 2-20432331``` which will dump all but the first read but if it doesn't it's likely your only option is to restart from scratch with the new version. What's the full contents of the store (```ls -lha *.gkpStore/```)?

**Comment by tangerzhang** [comment]
Thanks for your response. Adding -r does not help.
ls -lha *.gkpStore/ return the following message:
```
drwxr-xr-x. 2 fzmju_edu_denovo users 8.0K 8m  17 21:02 .
drwxr-xr-x. 6 fzmju_edu_denovo users 8.0K 8m  18 16:22 ..
-rw-r--r--. 1 fzmju_edu_denovo users 971G 8m  17 21:00 blobs
-rw-r--r--. 1 fzmju_edu_denovo users    0 8m  8 10:00 errorLog
-rw-r--r--. 1 fzmju_edu_denovo users   88 8m  17 21:00 info
-rw-r--r--. 1 fzmju_edu_denovo users  456 8m  17 21:00 info.txt
-rw-r--r--. 1 fzmju_edu_denovo users  672 8m  17 21:00 libraries
-rw-r--r--. 1 fzmju_edu_denovo users  432 8m   8 11:30 libraries.txt
-rw-r--r--. 1 fzmju_edu_denovo users  962 8m   8 11:30 load.dat
-rw-r--r--. 1 fzmju_edu_denovo users 110M 8m   8 11:31 readlengths-cor.dat
-rw-r--r--. 1 fzmju_edu_denovo users  560 8m   8 11:31 readlengths-cor.gp
-rw-r--r--. 1 fzmju_edu_denovo users  79M 8m  17 21:02 readlengths-obt.dat
-rw-r--r--. 1 fzmju_edu_denovo users  560 8m  17 21:02 readlengths-obt.gp
-rw-r--r--. 1 fzmju_edu_denovo users 954M 8m   8 11:30 readNames.txt
-rw-r--r--. 1 fzmju_edu_denovo users 780M 8m  17 21:00 reads
```

**Comment by skoren** [comment]
In that case, the easiest option is to use 1.8 or 1.9, the code you're getting an error from is completely different in 1.8 and 1.9 from this so it isn't worth trying to track down the error here as it's likely changed anyway.

If you want to rescue your correction so you don't have to re-run it and are comfortable editing code you can edit ```src/correction/falconsense.C``` from:
```
361   FILE *seqFile = AS_UTL_openOutputFile(outputPrefix, '.', "fasta", false);   //  Not useful.
```
to
```
361   FILE *seqFile = AS_UTL_openOutputFile(outputPrefix, '.', "fasta", true);   //  Not useful.
```
recompile, and then re-run the correction/2-correction/correctReads.jobSubmit-01.sh, that should generate fasta files in the correction/2-correction/results/ folder that you can concatenate together and input into 1.8 or 1.9 as ```-pacbio-corrected```.

**Comment by tangerzhang** [comment]
Thanks for your response! I have modified the script and recompiled. It seams that I still get the same error. I will re-run it with CANU 1.9.

**Comment by skoren** [comment]
The error is the same but you can take the fasta files directly rather than letting canu run/dump the reads, just cat them together into a single fasta file as input for 1.9
