### ISSUE TITLE
genome size for human sample

### ISSUE THREAD

**Issue by wisekh6** [marbl/canu#145]
Hello,
Previously, I addressed a similar (awkward) question. 
Do you think it would be ok to assign chr1's size (250m) (instead of the whole genome size ~3.1Gb) to 'genomeSize' when running canu for a human sample? Use of 3.1Gb caused a memory issue, and I assumed that chromosomes could be considered to be physically independent.
Probably, I might be wrong, but I can recall (from a previous reply to my issue) that 'genome size' would not affect much. 

thank you in advance,

**Comment by skoren** [comment]
The genome size affects how much data is corrected. You need enough reads to assemble the full genome so if you set the genome size to chr1's size but give WGS data from all chromosomes you'll end up with only 2X for assembly (30*250m / 3.1g) which won't work. 

By memory error, do you mean it complained that your maximum memory node was insufficient? We've run Canu on human genomes in <64g but recommend 128g so you can set maxMemory=64 which will force Canu to run. Given that you have a low-coverage sample, that will probably be sufficient.

**Comment by wisekh6** [comment]
Thank very much for your explanation.
