### ISSUE TITLE
Missing stats

### ISSUE THREAD

**Issue by juliofdiaz** [marbl/canu#1450]
Hi,
I am running Canu snapshot v1.8 +313 changes (r9523 68fecc9b7ee845d2fdd43f977dfa34229661f462) to assemble a bacterial genome. This is the command I use 
`canu -p PB1 -d PB1 genomeSize=6.26m -pacbio-raw PACBIO_1.fastq.gz`
And it runs smoothly except of the `WARNING: gnuplot failed`.
When I check the contains, the headers look like this:
`>tig00000242 len=1837889 reads=4164 class=contig suggestRepeat=no suggestCircular=no`
Looking at the documentation it seems as there should be two more stats in the headers (i.e `covStat` and `gappedBases`)

Am I running Canu incorrectly?
Thanks for your help

**Comment by skoren** [comment]
You're running the latest in tip not the 1.8 release and those options were removed post 1.8. It doesn't hurt anything not to have them but the documentation describes the release not the tip. You'd likely have a more stable version of the code if you ran 1.8 or the 1.9 branch.

**Comment by juliofdiaz** [comment]
Thanks for your help. I ran Canu 1.8 and now the `covStat` and `gappedBases` stats. The output contigs are different. Just wanted to let you know that with the latest tip I get these contigs:
```
>tig00000012 len=15359 reads=9 class=contig suggestRepeat=no suggestCircular=no
>tig00000041 len=665273 reads=1535 class=contig suggestRepeat=no suggestCircular=no
>tig00000077 len=17101 reads=3 class=contig suggestRepeat=no suggestCircular=no
>tig00000149 len=45516 reads=28 class=contig suggestRepeat=no suggestCircular=yes
>tig00000226 len=2900570 reads=6747 class=contig suggestRepeat=no suggestCircular=no
>tig00000227 len=18352 reads=17 class=contig suggestRepeat=yes suggestCircular=no
>tig00000228 len=83501 reads=158 class=contig suggestRepeat=no suggestCircular=no
>tig00000229 len=15691 reads=5 class=contig suggestRepeat=yes suggestCircular=no
>tig00000230 len=926476 reads=2147 class=contig suggestRepeat=no suggestCircular=no
>tig00000231 len=1837868 reads=4355 class=contig suggestRepeat=no suggestCircular=no
>tig00000232 len=26857 reads=43 class=contig suggestRepeat=yes suggestCircular=no
>tig00000233 len=622325 reads=1408 class=contig suggestRepeat=no suggestCircular=no
```
and with 1.8 I only get these.
```
>tig00000025 len=47941 reads=32 covStat=79.87 gappedBases=no class=contig suggestRepeat=no suggestCircular=yes
>tig00000136 len=4031168 reads=9518 covStat=4347.56 gappedBases=no class=contig suggestRepeat=no suggestCircular=no
>tig00000137 len=18352 reads=17 covStat=12.24 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00000138 len=2279365 reads=5349 covStat=2455.64 gappedBases=no class=contig suggestRepeat=no suggestCircular=no
>tig00000139 len=23123 reads=32 covStat=7.28 gappedBases=no class=contig suggestRepeat=yes suggestCircular=no
>tig00000140 len=734179 reads=1766 covStat=732.28 gappedBases=no class=contig suggestRepeat=no suggestCircular=no
```
