### ISSUE TITLE
Options for CCS data

### ISSUE THREAD

**Issue by mschatz** [marbl/canu#1451]
I was wondering if you have any recommended settings for HiFi data? I have about 25x coverage of 12kbp HiFi reads from a plant genome that assemble pretty well (contig N50 of 1.8Mb, basically the whole genome assembles) but would love to improve if possible. For this I used the parameters that you listed in the HiFi NBT paper:

```
canu -assemble -p asm -d asm genomeSize=2135m \
  correctedErrorRate=0.015 ovlMerThreshold=75 batOptions="-eg 0.01 -eM 0.01 -dg 6 -db 6 -dr 1 -ca 50 -cp 5" \
  -pacbio-corrected *.fasta
```

Are these still your recommendation? I think you said compressing homopolymers before assembly can help. Is that worth trying? Any other tips for optimizing the batOptions?

Thanks in advance!

Mike

**Comment by brianwalenz** [comment]
There's support in the v1.9 branch for hifi, including homopolymer compression.  Parameters are set to find perfect overlaps, a bit more aggressive than the batOptions you have (1% difference allowed).  Supply reads with -pacbio-hifi to enable.

**Comment by skoren** [comment]
I'd still recommend using the parameters from the HiFi paper, the compression Brian mentioned is experimental and typically not as continuous as the default options. Unless you're after haplotype separation or better repeat resolution, the HiFI paper parameters will give a more continuous assembly.

**Comment by mschatz** [comment]
Thanks!
