### ISSUE TITLE
utrovl too long

### ISSUE THREAD

**Issue by fmarletaz** [marbl/canu#1453]
Hi - Thanks for developing such a great tool! 
I am running a canu assembly on a 500MB quite heterozygous genome (expected almost twice the genome size). I am using newly generated sequel II dataset representing ~90Gb of data total that yields ~40Gb of corrected reads with a rather high read N50 (40kb). I ran canu with standard options but  `correctedErrorRate=0.065` for sequel and `batOptions="-dg 3 -db 3 -dr 1 -ca 500 -cp 50"`. 
The utgovl steps seems to take a very long time though and some of the jobs crashed as running out of time, I could of course try to relaunch with more time allocated but I am wondering whether this could be related to another issue, like k-mer filtration. This is a genome that proved difficult to deal with in the past. Meryl seems to have run properly, the .dump file with the excluded k-mers is 17MB. 
Thanks!

**Comment by skoren** [comment]
Check what the smallest value in the dmp file is (in the second column). If it's much higher than 500 then you could speed up the run by adding the option ````ovlMerDistinct=0.975``` (https://canu.readthedocs.io/en/latest/faq.html#my-assembly-is-running-out-of-space-is-too-slow). Of course this would require you to remove both the 0-mercounts and the 1-overlapper folder and re-run all the jobs that finished.

You could also try increasing the number of cores for each job or increase their wall time assuming they're not at your grid maximum to see if they will finish.

**Comment by fmarletaz** [comment]
Thanks a lot for your continued support, I did both and that fixed it! I am encountering another issue at the consens stage, 
I have several errors in the logs and some jobs appear not to have completed properly. For instance in a `consensus.000072.out` file, I have the following statements: 

```
utgcns: overlapInCore/libedlib/edlib.C:163: EdlibAlignResult edlibAlign(const char*, int, const char*, int, EdlibAlignConfig): Assertion `queryLength > 0' failed.
Failed with 'Aborted'; backtrace (libbacktrace):
utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
overlapInCore/libedlib/edlib.C::163 in _Z10edlibAlignPKciS0_i16EdlibAlignConfig()
utgcns/libcns/unitigConsensus.C::446 in _Z22generateTemplateStitchP8abAbacusP10tgPositionjdb()
utgcns/libcns/unitigConsensus.C::786 in _ZN15unitigConsensus13generatePBDAGEP5tgTigcPSt3mapIjP6sqReadSt4lessIjESaISt4pairIKjS4_EEEPS2_IjP10sqReadDataS6_SaIS7_IS8_SE_EEE()
utgcns/utgcns.C::522 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
./consensus.sh: line 100: 18729 Aborted                 (core dumped) $bin/utgcns -S ../Priap.${tag}Store/partitionedReads.seqStore -T ../Priap.${tag}Store 1 $jobid -O ./${tag}cns/$jobid.cns.WORKING -maxcoverage 40 -e 0.065 -pbdagcon -edlib -threads 2-8
```
Any suggestions?

**Comment by skoren** [comment]
Idle
