### ISSUE TITLE
How to estimate required disk space during correction

### ISSUE THREAD

**Issue by hungweichen0327** [marbl/canu#1454]
Dear community,

I would like to estimate how much disk space required during correction. Because the available space on PBS cluster is probably 4 TB. 

The version of Canu is ``1.8``.

The script I use is below:
```
/canu-1.8/Linux-amd64/bin/canu -correct -p Crystal_all_1kb -d ./Crystal_all_canu1.8 genomeSize=580m minReadLength=1000 stopOnReadQuality=false -nanopore-raw ./Crystal_all_porechop.fastq
```

The summary of raw nanopore read is below:
(120X coverage sequence for the self-pollinating plant species)
```
# contigs (>= 0 bp)         8913471             
# contigs (>= 1000 bp)      6923179             
# contigs (>= 5000 bp)      3697224             
# contigs (>= 10000 bp)     2325311             
# contigs (>= 25000 bp)     711816              
# contigs (>= 50000 bp)     118431              
Total length (>= 0 bp)      72711798733         
Total length (>= 1000 bp)   71611153733         
Total length (>= 5000 bp)   63414016273         
Total length (>= 10000 bp)  53508770421         
Total length (>= 25000 bp)  27802480179         
Total length (>= 50000 bp)  7776099977          
# contigs                   8013521             
Largest contig              315423              
Total length                72411139971         
GC (%)                      34.03               
N50                         19403               
N75                         9596                
L50                         1094014             
L75                         2406933    
```

In previous post #587 , they also discussed related issue before. But the date of issue is 2 year ago. I am not sure whether suggested parameter also reliable and useful for Canu version 1.8. Of course if 3-4 TB space is enough for correction in my case, I prefer to get better corrected reads.

Thank you.

**Comment by skoren** [comment]
No great way to estimate disk usage, it tends to vary with repetitive genomes. I would suggest using the repetitive genome parameters from the FAQ. I'd also suggest using the 1.9 branch which has the option ```purgeOverlaps=aggressive``` to clean up space more aggressively during the run.

**Comment by hungweichen0327** [comment]
Thank you for the answer. But I am sorry I can't find the branch version of Canu (1.9) from the release. (https://github.com/marbl/canu/releases)

PS: If I update the Canu to 1.9 branch, can I continue correction with resume option? (So far I used 1.8)

**Comment by skoren** [comment]
Version 1.9 is not yet released, you have to build it from source:
```
> git clone https://github.com/marbl/canu.git
> cd canu/src
> git checkout v1.9
> make -j 8
```

However, you can't switch between 1.8 and 1.9 in the middle of a run but if you end up changing parameters you'd likely need to restart anyway. I guess you can let this run with 1.8 keep going and if you encounter space issues switch to 1.9 with my suggestions.

**Comment by hungweichen0327** [comment]
Thank you for the suggestions!
