### ISSUE TITLE
About assembly process after correction finished

### ISSUE THREAD

**Issue by hungweichen0327** [marbl/canu#1459]
Dear community,

I would like to ask some questions related to run assemble function by canu after I obtained corrected reads. (I will get fasta file of corrected reads recently)

Q1. The definition of repetitive genome?
I am working on self-pollinating plant species. The heterozygosity of this species is 0.027% and estimated repetitive region using Illumina reads by k-mer analysis is 44% (Any other good method to estimate?). I don't know whether 44% repetitive region in genome is defined as a highly repetitive genome?
If it is the highly repetitive genome case, do I need to restart a new run for correction? Because I didn't adjust ```corMaxEvidenceErate``` to 0.15 suggested in manual during correction.

The script I use for correction before is below:
```
/home/hpc/crlee/softwares/canu-1.8/Linux-amd64/bin/canu -correct -p Crystal_all_1kb -d ./Crystal_all_canu1.8 genomeSize=580m minReadLength=1000 stopOnReadQuality=false -nanopore-raw ./Crystal_all_porechop.fastq
```

Q2. GC bias definition
Similar issue related to highly repetitive genome. The GC % of raw nanopore reads before correction is 34%. Is that categorized as skewed AT/GC ratio in this plant genome? Do you suggest me to restart correction with ```corMaxEvidenceErate = 0.15``` parameter if I didn't add this before?

Q3. If the genome size I set for correction is 580m, can I change the value to 508m for assembly 508m by canu? Sorry, why I set genome size 580m during correction is I refered the previous literature. But estimated genome size by k-mer analysis is 508m after the correction is running. Since the accession is different to that in the previous literature. I think 508m is more reliable to the actual genome size.

Q4. The requirement of disk space for assembly process is lower or higher of that for correction process? The pick of disk space for correction process in my previous run is 3 TB. I want to know whether is available disk space is enough for assembly process? How about the spending time? is that shorter or longer than that of correction? (In general)

Q5. The script I probably use is:
```
canu -assemble -p Crystal -d Crystal-ErRate0.144 genomeSize=508m correctedErrorRate=0.144 -nanopore-corrected Crystal_1kb.correctedReads.fasta.gz
```
The set pf correctedErrorRate=0.144 is because I basecall nanopore raw read by Guppy with fast mode rather HAC mode. So I think I shouldn't adjust it to 0.105. 

But I read one description from Canu 1.8 manual:

```
For more than 60X coverage, decrease the allowed difference in overlaps (from 14.4% to 12% with correctedErrorRate=0.12 for Nanopore), so that only the better corrected reads are used. This is primarily an optimization for speed and generally does not change assembly continuity. 
```

Is it better to adjust correctedErrorRate from 0.144 to 0.12 because I put 120X coverage raw nanopore read to obtain 40X longest read?

PS:  ```For more than 60X coverage, decrease the allowed....```  in canu manual, the 60X coverage here means 60X coverage raw reads or 60X corrected read in fasta file after correction by canu?

 
Thank you for the patience.

**Comment by hungweichen0327** [comment]
Thank you. One more thing about Q5 question:
you said: ```it makes a big different and higher quality reads will also help separate repeats and improve the assembly```

In your opinion, do you still suggest to use HAC mode for basecalling even though we have Illumina data to do polish after assembly has finished? Since the graphic card in our local computer is not compatible with Guppy and we would not use cloud computing GPU instance. 

Is there any paper or report discussed about the difference between HAC and fast mode for basecalling? I am curious that you said "it makes a big different". What I knew is read accuracy improved from 92.1% to 95% when use HAC.

**Comment by skoren** [comment]
The benefit of HAC is that your corrected reads will also be higher accuracy and will allow you to separate more repeats and improve your assembly quality. The illumina polishing isn't going to resolve the repeat from polishing. However, you'll probably get a decent assembly from the normal data.
