### ISSUE TITLE
can I run canu using 2 smrt cells sequences? 

### ISSUE THREAD

**Issue by igsbma** [marbl/canu#146]
with the option -pacbio-raw $pacbio,$pacbio2? I tried it, it seems running then failed "canu failed with 'failed to compute mhap overlaps.  Made 2 attempts, jobs still failed'." I am not sure it is because it does not allow two smrt cells or other reason. thanks!

**Comment by brianwalenz** [comment]
Most definitely it'll run with more than one file.  Did it really work with the comma between the file names?  It definitely works as "-pacbio-raw *fastq".  It expects any number of files after the pacbio/nanopore options.

Mhap failure is usually a failure to run java programs.  Check the logs in the 1-overlapper directory (they might be in subdirectories).

**Comment by tseemann** [comment]
Just to confirm - when we use the `*.subreads.fastq.gz` files we should be used `-pacbio-raw` ?

**Comment by skoren** [comment]
Yep, those are still raw uncorrected reads versus pacbio-corrected which would be CCS or reads generated by Canu's correction step.

**Comment by tseemann** [comment]
Thanks!
