### ISSUE TITLE
Multiple questions

### ISSUE THREAD

**Issue by Malabady** [marbl/canu#1461]
Hello Sergey:

- Kmers:
I am looking for the kmer files of the uncorrected and corrected data. I am thinking that they are as following:
 -- Uncorrected data: correction/0-mercounts/run.ms16.histogram --> k=16
 -- Corrected data:trimming/0-mercounts/run.ms22.histogram  --> k=22

Is this correct? 
In both cases there is a dump file. Was there any upper and lower thresholds applied on them? 
It is normal to have different k size? Was the k=22 used based on some optimizations? 

- Long time:
I am running the assembly pipeline and it is still in the triming stage after more than three weeks of running on 48 cores. I am using all corrected reads (~ 96X) in the assembly.  is it normal to run for that long when using this high coverage (comparing to the default 40X)? 
Here is my command: 

$canu -p run -d rosea4 genomeSize=3.6g  -pacbio-raw ../raw_data/*.subreads.fastq.gz \
corOutCoverage=200 correctedErrorRate=0.05 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" \
useGrid=true \
gridEngine=pbs \
gridEngineThreadsOption="-l nodes=1:ppn=THREADS" \
gridEngineMemoryOption="-l mem=MEMORY" gridOptions="-q ggbc_q -l walltime=12:00:00:00" \
gridOptionsovs="-l mem=80g" \
java=/usr/local/apps/eb/Java/1.8.0_144/bin/java

-Corrected reads
I need the corrected reads, but since I ran the assembly pipeline, it did't write out corrected reads fastq file. 
If I run the same command using "-correct" and giving it the run directory of the ongoing run, would write out the corrected reads fastq file? 

-Another assembly
The corrected out reads makes about 96X coverage. If I want to make another assembly using the default 40X coverage, can I use the correct reads from the above run? 

As always, thank you very much for your help. 
magdy

**Comment by skoren** [comment]
Yes, k=16 is the default for raw and 22 for corrected. You want a large k-mer to make it more unique in the genome but the initial raw reads are too high error to find overlaps with a large k-mer. Thus it increases when the reads are corrected. The dump file lists the k-mers that were filtered for being too repetitive, the minimum value there is your repeat threshold. If it is very high (say over 1000), you could use the parameters suggested on the FAQ for repetitive genomes (```ovlMerDistinct=0.975```) but this would mean you'd have to restart the trimming from scratch giving the corrected reads as -pacbio-corrected. 

Given that you've more than doubled the coverage you will increase the runtime as well, close to 4-fold. So if a 3gb human genome takes 20k CPU h at your coverage it would take closer to 80k CPU h. On 48 cores 80k = 70 days. You've already run through part of this time obviously with correction but still 3 weeks is not unexpected given the large genome size and the high coverage you have.

Running the full pipeline will still output corrected reads, there are both correctedReads.fasta.gz and trimmedReads.fasta.gz, either way you can use the sqStoreDumpFASTQ command (run without options or see the docs to see usage) to dump corrected reads (assuming you're on 1.8).

Sure, you can run another assembly with the corrected reads, You can either subset to keep the longest 40x of use canu's built-in options of readSamplingBias and readSamplingCoverage. Input the corrected reads as -pacbio-corrected which will only run the assembly steps.

**Comment by Malabady** [comment]
Thank you. 

For the built in options, will the following values be correct? 
readSamplingCoverage=40 readSamplingBias=-1

Thanks.

**Comment by Malabady** [comment]
Is there command (similar to sqStoreDumpFASTQ) to write out the good Kmers and their occurrences? I couldn't find anything in the documentations about it (probably missed it). 

The thing is: when I use the run.ms16.histogram produced by Canu in genomescope, the results, especially genome size, are very very close to expectation. When I generate k22 mers db and histogram using KMC from the Canu corrected reads, I get completely different results from genomescope. the predicted genome size is way below expectations.

**Comment by skoren** [comment]
You want the sampling bias to be >0, not negative that would bias to keep shorter reads. You want to make it use larger positive numbers.

Typically the full kmer counts aren't stored, you may have a ```*.meryl``` folder in which case you can use the meryl command to dump all k-mers but there are a lot of them. Overlapping uses kmers >1 and < the minimum value in the dump file. There's no way you're going to get an accurate estimate of genome size from 16-mers on the raw reads for your size genome (since there are only 4^16 k-mers or about the size of your genome) and the reads are too noisy. The assembly report file will have a picture of the k-mer histogram after correction, you should look for a peak besides the error k-mers to see if it matches what you expect. Genomescope tends to underestimate genome size especially with very repetitive genomes.

**Comment by Malabady** [comment]
Thanks! is there any rule or heuristic for choosing the suitable "large positive number"? Does the read length distribution of corrected reads have any effect on choosing this value? 

Which of the following two methods is better for the assembly?
- extracting the longest reads constituting  ~40X coverage and pass them to Canu (-trim-assemble).
- Utilizing Canu built-in functions  readSamplingBias and readSamplingCoverage.

In second method, all reads will be viable to Canu, which is not the case in the first method. Does Canu use the extra reads (above the ~40X) later in the process? If yes, then I think the 2nd method might be preferred.

**Comment by skoren** [comment]
The length of reads doesn't matter, the repetitiveness of the genome and the k-mer counts are used to select the value. Typically it is a few hundred. If it is very large, like over 1000 then the parameters I suggested for repetitive genomes might help.

I think the two options would be essentially the same.
