### ISSUE TITLE
"Bye" after meryl finishes

### ISSUE THREAD

**Issue by claumer** [marbl/canu#1464]
Hi there,

I'm trying to use canu to assemble a funny marine worm, which I know is a.) pretty heterozygous and b.) contains within the library some interesting bacterial reads (possibly its microbiome, possibly lab contamination) and a minor fraction of human reads as well. I'd slightly prefer to see how the assembler handles all this at once, rather than trying to a priori bin to remove non-target genome reads. It's a large (88 Gbp) nanopore run of flip-flop data, mean read size ~2.5 kbp with a tail out to 10 kbp (long-range PCR amplified library, but the distribution of coverage should be pretty even).

The command I've used (taking on board your advice in the FAQs for flip-flop and also metagenome data) is:

```
canu 'corMhapOptions=--threshold 0.8 --ordered-sketch-size 1000 --ordered-kmer-size 14' correctedErrorRate=0.105 corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0 redMemory=32 oeaMemory=32 batMemory=200 merylMemory=16g genomeSize=700m -p MeioA_canu -d ./ -nanopore-raw MeioA_total_chopped.fastq
```

And this was run on an LSF cluster, with canu built from today's git: Canu snapshot v1.8 +334 changes (r9544 54df6e99dafe9a57e179f874271b0770c4bd7221)

At first all seems well, one big meryl job finishes and writes its output in correction/0-mercounts... but, there's no further pending jobs, canu has just stopped. When I re-run it using the same command, I get:

```
-- Canu snapshot v1.8 +334 changes (r9544 54df6e99dafe9a57e179f874271b0770c4bd7221)
--
-- Detected Java(TM) Runtime Environment '1.8.0_121' (from 'java') with -d64 support.
-- Detected gnuplot version '4.6 patchlevel 2   ' (from 'gnuplot') and image format 'png'.
-- Detected 40 CPUs and 126 gigabytes of memory.
-- Detected LSF with 'bsub' binary in /ebi/lsf/yoda/10.1/linux3.10-glibc2.17-x86_64/bin/bsub.
-- Discovered LSF_UNIT_FOR_LIMITS of 'MB' from '/ebi/lsf/yoda/conf/lsf.conf'.
--
-- Found   1 host  with 112 cores and 1945 GB memory under LSF control.
-- Found 168 hosts with  40 cores and  127 GB memory under LSF control.
--
-- On LSF detected memory is requested in MBB
--
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl     16 GB    8 CPUs  (k-mer counting)
-- Grid:  hap       12 GB    8 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   25 GB    8 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    16 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl    16 GB    8 CPUs  (overlap detection)
-- Grid:  cor       16 GB    4 CPUs  (read correction)
-- Grid:  ovb        4 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       16 GB    1 CPU   (overlap store sorting)
-- Grid:  red       32 GB    8 CPUs  (read error detection)
-- Grid:  oea       32 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      200 GB   16 CPUs  (contig construction with bogart)
-- Grid:  cns      --- GB    8 CPUs  (consensus)
-- Grid:  gfa       32 GB   16 CPUs  (GFA alignment and processing)
--
-- In 'MeioA_canu.seqStore', found Nanopore reads:
--   Nanopore:                 1
--
--
-- Generating assembly 'MeioA_canu' in '/nfs/leia/research/marioni/claumer/MeioA_canu'
--
-- Parameters:
--
--  genomeSize        700000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1050 ( 10.50%)
--    utgOvlErrorRate 0.1050 ( 10.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1050 ( 10.50%)
--    utgErrorRate    0.1050 ( 10.50%)
--    cnsErrorRate    0.1050 ( 10.50%)
--
-- Bye.
```
And this is also the output of canu-scripts/canu.01.out, the last job that was submitted.

What gives? Is this expected behavior? Is there something wrong with my data that stops canu from even attempting to overlap, or is this just a bug? (In any case, the error message is, you will agree... not very informative.)

Anyway, thanks for reading, keen to see what you make of this.

Regards,
Chris L

**Comment by skoren** [comment]
You're running tip which is not recommended, you should switch either to the 1.8 release or the 1.9 branch and run again in a new folder (or make sure you remove all of ```MeioA_canu``` folder and report what that outputs.

**Comment by claumer** [comment]
Quite so - installing the release version of 1.8 fixes this problem and lets me advance to overlapping. I guess you recommend them first for a reason. :-) Now to sit back and twiddle my thumbs.

One thing - the binary for me had trouble interacting with LSF on our cluster, tried to submit a job with way too much memory. Changing the grid engine memory units flag to G did not help. So I deleted the binary, build this release from source... and voila, that fixed it. Thought you developers might like to know about that.
