### ISSUE TITLE
canu error in PacBio raw FASTQ file correction

### ISSUE THREAD

**Issue by hidvegin** [marbl/canu#1466]
I have got an 40 threads CPU and 126 GB ram in my computer with Ubuntu 18.04. I installed the canu 1.8 with brew from homebrew/bio. I generated the FASTQ file from BAM files with bam2fastx 1.3. I used this parameters for canu correct reads:

`canu -d pacbio -p LC001 genomeSize=4g batMemory=120 batThreads=40 -pacbio-raw LC001.fastq.gz`

I get this error message from the canu:

```
-- Canu 1.8
--
-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
-- 
-- Koren S, Rhie A, Walenz BP, Dilthey AT, Bickhart DM, Kingan SB, Hiendleder S, Williams JL, Smith TPL, Phillippy AM.
-- De novo assembly of haplotype-resolved genomes with trio binning.
-- Nat Biotechnol. 2018
-- https//doi.org/10.1038/nbt.4277
-- 
-- Read and contig alignments during correction, consensus and GFA building use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '11.0.4' (from 'java') without -d64 support.
-- Detected gnuplot version '5.2 patchlevel 2   ' (from 'gnuplot') and image format 'png'.
-- Detected 40 CPUs and 126 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |     total usage     algorithm
--        -------  ------  --------   --------  -----------------  -----------------------------
-- Local: meryl     25 GB    8 CPUs x   5 jobs   125 GB   40 CPUs  (k-mer counting)
-- Local: hap       16 GB   40 CPUs x   1 job     16 GB   40 CPUs  (read-to-haplotype assignment)
-- Local: cormhap   31 GB   10 CPUs x   4 jobs   124 GB   40 CPUs  (overlap detection with mhap)
-- Local: obtovl    24 GB   10 CPUs x   4 jobs    96 GB   40 CPUs  (overlap detection)
-- Local: utgovl    24 GB   10 CPUs x   4 jobs    96 GB   40 CPUs  (overlap detection)
-- Local: ovb        4 GB    1 CPU  x  31 jobs   124 GB   31 CPUs  (overlap store bucketizer)
-- Local: ovs       32 GB    1 CPU  x   3 jobs    96 GB    3 CPUs  (overlap store sorting)
-- Local: red       16 GB    8 CPUs x   5 jobs    80 GB   40 CPUs  (read error detection)
-- Local: oea        8 GB    1 CPU  x  15 jobs   120 GB   15 CPUs  (overlap error adjustment)
-- Local: bat      120 GB   40 CPUs x   1 job    120 GB   40 CPUs  (contig construction with bogart)
-- Local: gfa       32 GB   32 CPUs x   1 job     32 GB   32 CPUs  (GFA alignment and processing)
--
-- Found PacBio uncorrected reads in the input files.
--
-- Generating assembly 'LC001' in '/NVMe2/PacBio_lencse_DNA_corrected/pacbio'
--
-- Parameters:
--
--  genomeSize        4000000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0750 (  7.50%)
--
--
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Sun Sep  1 13:58:32 2019 with 860.375 GB free disk space

    cd .
    /home/linuxbrew/.linuxbrew/Cellar/canu/1.8/Linux-amd64/bin/sqStoreCreate \
      -o ./LC001.seqStore.BUILDING \
      -minlength 1000 \
      ./LC001.seqStore.ssi \
    > ./LC001.seqStore.BUILDING.err 2>&1

-- Finished on Sun Sep  1 13:59:27 2019 (55 seconds) with 859.345 GB free disk space
----------------------------------------

ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:

ABORT:
ABORT: Canu 1.8
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   sqStoreCreate failed.
ABORT:
ABORT: Disk space available:  859.345 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (./LC001.seqStore.BUILDING.err):
ABORT:
ABORT:   
ABORT:   Starting file './LC001.seqStore.ssi'.
ABORT:   
ABORT:     Loading reads from '/NVMe1/lencse_de_novo_dna/PacBio_lencse_DNA_raw_fastq/LC001pacbio.fastq.gz'
ABORT:   Failed to close file './LC001.seqStore.BUILDING/blobs.0000': Operation not permitted
ABORT:
```

How can I resolve the issue?

**Comment by skoren** [comment]
Is this a VM? The error is coming from your filesystem not wanting to create a file. We've seen VMs filesystems often don't behave properly and cause errors. It's also possible you're out of quota space.

**Comment by hidvegin** [comment]
No, this is not a VM. This is a Dell Precision 7920 workstation with native Ubuntu 18.04 LTS. I am the only user on this PC and there is not any quota for space. The available space is 859 GB, as the canu also mention in the log. The user has got permission for read/write this space so I do not know what happened because canu can create the folders and files for the correction but can not create the blobs.0000 file. So this is very strange. Could you suggest to me a solution for this issue? Is it possible that linuxbrew cause this issue and if I build from source the canu the issue will be stop?

**Comment by hidvegin** [comment]
I installed canu v1.9 from github as discribed here:
`> git clone https://github.com/marbl/canu.git
> cd canu/src
> git checkout v1.9
> make -j 8`

I used this code for run canu:

`canu -correct -d pacbio -p LC001 genomeSize=4g batMemory=120 batThreads=40 -pacbio-raw LC001.fastq.gz`

I get the same error message as I described below. I do not know what I did wrong because every bioinformatic analysis which I usually do I do on this NVMe SSD and nothing problem. But canu somehow make the folders and files but this blobs.0000 can not close but can make it and after 1.1 GB size canu can not handle it. It is very starnge.

**Comment by brianwalenz** [comment]
This is something outside Canu.

The error message translates as `EPERM  The operation was prevented by a file seal; see fcntl(2)` (from http://man7.org/linux/man-pages/man2/write.2.html).  The relevant bit of fcntl() (http://man7.org/linux/man-pages/man2/fcntl.2.html) is
```
       File seals limit the set of allowed operations on a given file.  For
       each seal that is set on a file, a specific set of operations will
       fail with EPERM on this file from now on.  The file is said to be
       sealed.  The default set of seals depends on the type of the underly‐
       ing file and filesystem.  For an overview of file sealing, a discus‐
       sion of its purpose, and some code examples, see memfd_create(2).

       Currently, file seals can be applied only to a file descriptor
       returned by memfd_create(2) (if the MFD_ALLOW_SEALING was employed).
       On other filesystems, all fcntl() operations that operate on seals
       will return EINVAL.
```
We're definitely not calling memfd_create().  Is something is intercepting our (very vanilla) file operations and trying to cache them in memory?

**Comment by hidvegin** [comment]
Thank you for your reply. I do not know. I use Ubuntu 18.04 OS with EXT4 filesystem. How can I check that something is intercepting with the file operations and trying cache them in memory?

**Comment by skoren** [comment]
Is it possible your NVMe is not configured correctly, have you tried running on another FS volume to see if that works. Also, it looks like you're running with a 4gb genome on 4 cores, that will take a very long time and I wouldn't recommend it, that size genome needs a cluster to run.

**Comment by hidvegin** [comment]
Thank you for your answer. I would like to use 20 cores (40 threads) and 128 GB ram for 4Gb de novo assembly. Is it not enough? If not I can use a cluster for this. I used this NVMe for other bioinformtic analysis for assembly without any problem but I tried canu on 4 TB hard disk drive and get the same error message, I do not know what I did wrong, but I will try also use a cluster for run canu. What is the recommended computer resources (cpu core, memory and free disk space size) for 4 Gb highly repetitive plant genome de novo assembly? Based on you suggestions I can ask a cluster from my University.

**Comment by skoren** [comment]
A human genome takes about 20-25k cpu hours. Your genome is larger and presumably more repetitive. I'd start with an estimate of 100-150k cpu hours, on 40 cores that's months. The more CPU the faster it will run, a slurm cluster would be best. No need for large memory nodes, 128gb/node is OK. Disk space can also vary by species, I'd suggest including the repetitive genome options (on the FAQ here: https://canu.readthedocs.io/en/latest/faq.html#my-assembly-is-running-out-of-space-is-too-slow).
