### ISSUE TITLE
Bogart failed

### ISSUE THREAD

**Issue by apoosakkannu** [marbl/canu#1467]
Hello,
I have an new error assembling a genome in canu software. I hereby attached log file for your reference. I hope to get a solution for this problem. 

[canu.sh.e3108503.txt](https://github.com/marbl/canu/files/3564962/canu.sh.e3108503.txt)

**Comment by brianwalenz** [comment]
You've got lots of coverage, Canu is trying to assemble it all and finds it needs more memory than it is allowed to use.

Three options:
1)  Increase batMemory from the default 16 GB to 64 GB with `batMemory=64` (or more, as needed).  Delete the old result of this step in the `unitigging/4-unitigger` folder before restarting.
2)  Start again, telling it to down sample the reads with `readSamplingCoverage=80` (anywhere from 60 to 200 is useful).  This is a random sampling.  Generate two or three assemblies and compare them.  This will redo rad correction, but will be immensely faster.
3)  Start again using your existing corrected and trimmed reads, with random sampling enabled as above.  Use `-assemble -nanopore-corrected <assembly>/assembly_RF_1_1_25_1_filt_canu.trimmedReads.fasta.gz`.

Be sure to use a different run directory (-d option) for options 2 and 3.

**Comment by skoren** [comment]
Idle, closing.
