### ISSUE TITLE
heterozygosity for corOutCoverage 

### ISSUE THREAD

**Issue by hungweichen0327** [marbl/canu#1468]
Dear community:

I am curious about the heterozygosity issue to adjust corOutCoverage value. According to the previous post from the # 908 (https://github.com/marbl/canu/issues/908) and discuss with Dr. Sergey. I understand that Increase corOutCoverage value (default = 40) will not improve the assembly continuity and quality. And the heterozygosity over 0.5% is suggested to use heterozygous parameter described in FAQs.
The parameters showed in FAQs are:
```
corMhapSensitivity=normal if you have >50X
corMhapSensitivity=high 
corMinCoverage=0 
corOutCoverage=100 (or >40)
```

The result of the heterozygosity based on Illumina data and genome reference:

Accession | Homozygous site |  total SNP site  | Heterozygosity
Crystal      |     25329705         |    26020046     |   2.7 %

I am not sure whether the heterozygosity I measured is correct. 
Heterozygosity = (no. of SNP site - Homozygous site) / no. of SNP site * 100 (%)

So far I have 120X raw Illumina data and obtain 40X longest corrected reads after correction of self-pollinating plant species. Do I need to re-run correction with those suggested parameters below?
```
corMhapSensitivity=normal 
corMhapSensitivity=high 
corMinCoverage=0 
corOutCoverage=100 
```

Hung-Wei
PhD student

**Comment by skoren** [comment]
Heterozygosity should be measured against the full genome not just the differences vs reference. If your genome was over 2% diverged I'd expect you would get double the genome size in the assembly (assuming it's diploid). You can use GenomeScope and your illumina data to compute some statistics and confirm the heterozygosity. If it is not high, then you don't need to change the parameters, defaults will be OK.

If the heterozygosity is high, the parameters you listed are not what you want. They are for generally improving assembly if correction did not work well (e.g. you did not end up with 40x coverage) but you said you have 40x. There is a specific section on polyploid genomes where the parameters listed are: ```corOutCoverage=200 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50"```. Essentially, very heterozygous genomes should just be thought of as double the genome size so outputting more coverage helps have enough data to assemble both haplotypes separately.
