### ISSUE TITLE
canu -trim

### ISSUE THREAD

**Issue by zjwang6** [marbl/canu#1469]
** canu -trim **
Hello, I need your help.

```
 nohup canu -trim -p dl \
-d /public/home/zjwang/de_novo_seq/3_parent/canu/trim \
maxThreads=40 genomeSize=400m \
minReadLength=20000 minOverlapLength=500 \
ovsMemory=16G ovbConcurrency=15 ovsConcurrency=15 \
-pacbio-corrected /public/home/zjwang/de_novo_seq/3_parent/canu/correct/dl.correctedReads.fasta.gz &
```
linux    canu/v1.8

> 
Finished with:
  0 warnings (bad base or qv, too short, too long)

Loaded into store:
  72227462463 bp.
  2131578 reads.

Skipped (too short):
  2526075848 bp (3.3792%).
  158358 reads (6.9154%).

sqStoreCreate finished successfully.

No error occurred, but no result file “trimmedReads.fasta.gz” output. How can I resolve this problem？ 
Thanks a lot

**Comment by skoren** [comment]
That output is only from the binary store creation that input your corrected fastq files. The run should not be done yet, that's why you have no output. Canu should be counting k-mers and identifying overlaps now in this step.

**Comment by zjwang6** [comment]
> That output is only from the binary store creation that input your corrected fastq files. The run should not be done yet, that's why you have no output. Canu should be counting k-mers and identifying overlaps now in this step.

Thank you for your apply. My input file is corrected fastq files by "canu correct". And the run is termination. How can I get result file? should I change or add some parameter.

**Comment by skoren** [comment]
Are you sure it is not still running, it was launched in the background with your command. What is the full output of the actual canu run (which would be redirected to nohup.out in your case)?

**Comment by zjwang6** [comment]
> Are you sure it is not still running, it was launched in the background with your command. What is the full output of the actual canu run (which would be redirected to nohup.out in your case)?

`drwxr-xr-x 2 zjwang YDOYang 8.0K Sep  2 15:02 canu-logs
lrwxrwxrwx 1 zjwang YDOYang   24 Sep  2 15:02 canu.out -> canu-scripts/canu.01.out
drwxr-xr-x 2 zjwang YDOYang 4.0K Sep  3 08:56 canu-scripts
-rw-r--r-- 1 zjwang YDOYang 6.0K Sep  3 15:08 dl.report
drwxr-xr-x 2 zjwang YDOYang 4.0K Sep  3 08:54 dl.seqStore
-rw-r--r-- 1 zjwang YDOYang  599 Sep  3 16:28 dl.seqStore.err
-rw-r--r-- 1 zjwang YDOYang  276 Sep  2 14:12 dl.seqStore.ssi
-rw------- 1 zjwang YDOYang 7.9K Sep  3 10:23 nohup.out
drwxr-xr-x 4 zjwang YDOYang 4.0K Sep  2 15:02 trimming
`
Thank you for your apply. I am sure it is not still running.Is it too many intermediate files generated by my run, exceeding the threshold set by the server administrator?or other reason?

**Comment by skoren** [comment]
It looks like it is running on your cluster, the most recent step would be in canu.out. Post the contents of that along with the contents of nohup.out.

**Comment by zjwang6** [comment]
> It looks like it is being launched on your cluster in which case the initial job you launched would exit as soon as the run is submitted to the cluster. The most recent output would be in `canu-scripts/*.out`. Post the contents of those files along with the contents of `nohup.out`.

`-- Finished on Mon Sep  2 14:31:35 2019 (one second) with 2167222.343 GB free disk space
----------------------------------------
--  segments   memory batches
--  -------- -------- -------
--        01 12.00 GB      19
--        02 12.00 GB      10
--        04 12.00 GB       6
--        06 12.00 GB       4
--        08 12.00 GB       3
--        12 12.00 GB       2
--        16 12.00 GB       2
--        20 12.00 GB       2
--        24 11.00 GB       2
--        32  8.00 GB       1
--        40  6.75 GB       1
--        48  5.50 GB       1
--        56  5.13 GB       1
--        64  4.00 GB       1
--        96  3.00 GB       1
--
--  For 2131578 reads with 72227462463 bases, limit to 722 batches.
--  Will count kmers using 32 jobs, each using 10 GB and 4 threads.
--
-- Finished stage 'merylConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
--
-- 'meryl-count.jobSubmit-01.sh' -> job ended(473955) tasks 1-32.
--
----------------------------------------
-- Starting command on Mon Sep  2 14:31:36 2019 with 2167222.343 GB free disk space

    cd /public/home/zjwang/de_novo_seq/3_parent/canu/trim
    bsub \
      -w "ended(473955)"   \
      -R span[hosts=1] \
      -n 1  \
      -J 'canu_dl' \
      -o canu-scripts/canu.01.out  canu-scripts/canu.01.sh
Job <473956> is submitted to default queue <normal>.

-- Finished on Mon Sep  2 14:31:36 2019 (lickety-split) with 2167222.343 GB free disk space`

**Comment by skoren** [comment]
That looks like it is running without issue. Do you have either of the jobs still in the queue (either 473955 or 473956).

**Comment by zjwang6** [comment]
> That looks like it is running without issue. Do you have either of the jobs still in the queue (either 473955 or 473956).

I am sorry, I forget post canu-scripts/*.out to you .There is a problem.

`-- Configured 3507 overlapInCore jobs.
-- Finished stage 'obt-overlapConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
--
-- Failed to submit compute jobs.  Delay 10 seconds and try again.

CRASH:
CRASH: Canu snapshot v1.8 +167 changes (r9377 06f1d32beef8f6d3d38d6de8dc2086268b9b7c8b)
CRASH: Please panic, this is abnormal.
ABORT:
CRASH:   Failed to submit compute jobs.
CRASH:
`
How can I resolve this problem. should I change or add some parameter.

**Comment by skoren** [comment]
Ah OK, that shows the error, Canu tried to submit too many jobs. Canu 1.8 did not detect the job limit on LSF. You can set it manually using the ```gridEngineArrayMaxJobs``` parameter, check the value of the environment variable MAX_JOB_ARRAY_SIZE and set ```gridEngineArrayMaxJobs``` to that.

You could also change the resources being used for this step to decrease the number of jobs. What are the nodes in the cluster and what did Canu try to use, these should be listed at the start of your same output file you posted.

**Comment by zjwang6** [comment]
> Ah OK, that shows the error, Canu tried to submit too many jobs. Canu 1.8 did not detect the job limit on LSF. You can set it manually using the `gridEngineArrayMaxJobs` parameter, check the value of the environment variable MAX_JOB_ARRAY_SIZE and set `gridEngineArrayMaxJobs` to that.
> 
> You could also change the resources being used for this step to decrease the number of jobs. What are the nodes in the cluster and what did Canu try to use, these should be listed at the start of your same output file you posted.

Thank you for your reply, I have resubmitted the task. And I add the parameter"gridEngineArrayMaxJobs=50"
my queues 
`QUEUE_NAME      PRIO STATUS          MAX JL/U JL/P JL/H NJOBS  PEND   RUN  SUSP
smp              30  Open:Active       -  200    -    -   657     1   656     0`
And the nodes:
`HOST_NAME          STATUS       JL/U    MAX  NJOBS    RUN  SSUSP  USUSP    RSV 
s006               closed          -     96     96     96      0      0      0`
I am sorry, due to my poor ability in analysis. Disturbing you so much.

**Comment by zjwang6** [comment]
> Ah OK, that shows the error, Canu tried to submit too many jobs. Canu 1.8 did not detect the job limit on LSF. You can set it manually using the `gridEngineArrayMaxJobs` parameter, check the value of the environment variable MAX_JOB_ARRAY_SIZE and set `gridEngineArrayMaxJobs` to that.
> 
> You could also change the resources being used for this step to decrease the number of jobs. What are the nodes in the cluster and what did Canu try to use, these should be listed at the start of your same output file you posted.

Thank you so much. The problem has been resolved，by properly configuring computer resources
