### ISSUE TITLE
memory allocation problem during trimming

### ISSUE THREAD

**Issue by cdb3ny** [marbl/canu#147]
Hi Brian, thanks again for your help so far (following issue 141).  The new version of canu has run nicely on a largish genome.  It's made it through correction and all the *.sh scripts that start off trimming.  But now I am getting an error just after that.  The screen output finishes with the error: 

_Don't panic, but a mostly harmless error occurred and canu failed.
Disk space available:  649.4 GB
Last 50 lines of the relevant log file (/data/baileyd/L_tri_assemb5-26-16/LTRI052616/trimming/Ltri052616.ovlStore.BUILDING/config.err):
Found 4264375588 (4264.38 million) overlaps.
Configuring for 5.00 GB to 5.00 GB memory.
ERROR:  Cannot sort 4264.38 million overlaps using 5.00 GB memory; too few file handles available.
ERROR:    olapsPerBucket 127506841
ERROR:    buckets        34
ERROR:  Increase memory size (in canu, ovsMemory; in ovStoreBuild, -M)
canu failed with 'failed to generate configuration for building overlap store'._

The Ltri052616.ovlStore.BUILDING/config.err file is here:

_Found 4264375588 (4264.38 million) overlaps.
Configuring for 5.00 GB to 5.00 GB memory.
ERROR:  Cannot sort 4264.38 million overlaps using 5.00 GB memory; too few file handles available.
ERROR:    olapsPerBucket 127506841
ERROR:    buckets        34
ERROR:  Increase memory size (in canu, ovsMemory; in ovStoreBuild, -M)_

I can probably solve this one manually, but I thought you might like to know about it in case it is a general problem for others.  Thanks, Donovan

**Comment by cdb3ny** [comment]
I tried manually increasing the -M option to 400GB of memory and still get the same error.  There seems to be something going on here I may not understand. Thanks for any advice. Donovan

**Comment by brianwalenz** [comment]
I suspect you need to set ovsMemory on the canu command line, instead of changing -M in the script.  Setting it to ovsMemory=5g-400g will let it pick the smallest value that will work.

You also could be hitting a short-lived bug in this step.  That it picked 5GB is hinting you are.  Updating the code is suggested.

Removing the *.ovlStore.BUILDING directory is suggested to remove any trace of the previous configuration.

**Comment by cdb3ny** [comment]
Thanks Brian!  I'll Give it a try tonight or tomorrow.  Donovan

**Comment by brianwalenz** [comment]
Can you give the latest code on github a try?  I added a bunch of debugging, and changed the way it picks a memory size slightly.  You need only run the ovStoreBuild command, not the entire canu pipeline.  Usage will be something like:

ovStoreBuild \
  -G *gkpStore -O junk.ovlStore -M 8-256 \
  -config junk.ovlStore/config \
  -L 1-overlapper/ovljob.files

Regardless of success, I'd like to see what it reports to the screen.

You can delete junk.ovlStore when done testing.

**Comment by cdb3ny** [comment]
Sure Brian.  Because of server drive space I've had to delete the old runs, but I'll give the new code a try from the beginning and let you know how it goes.

Donovan


________________________________

**Comment by brianwalenz** [comment]
It's not super critical.  If you can do it, great.  If not, wait for the next assembly.

**Comment by cdb3ny** [comment]
Hi Brian, I started the new assembly yesterday, but it ran into troubles in the correction step.  I've attached the bottom portion of the screen output.  Any thoughts would be appreciated.  Donovan
[canu_correction_problem.docx](https://github.com/marbl/canu/files/306868/canu_correction_problem.docx)

**Comment by brianwalenz** [comment]
I've never seen this before.  Is there anything suspicious in LTRI060716/correction/Ltri060716.ovlStore/logs/3-index.err?  It's complaining that the 'info' file in the ovlStore directory is missing.  What files are present there?

**Comment by cdb3ny** [comment]
If you haven't seen it before, it can't be good :) 

Looks like lots of errors in the LTRI060716/correction/Ltri060716.ovlStore/logs/3-index.err file -
[canu_correction_problem2.docx](https://github.com/marbl/canu/files/306944/canu_correction_problem2.docx)

There do appear to be 35 "*.info" files in the /correction/ovlStore directory.  Each has a numerical prefix.  (e.g. 0012.info)

Sorry this is such a pain.  The assemblies are still running fine on my slower AMD machine, but I'm admittedly still using an older version of canu.  Not sure why this machine is causing so much trouble.

**Comment by brianwalenz** [comment]
Nah, don't worry about it.  I've spent half my life debugging.

It's reporting segments 1, 2, 3 and 5 (etc) failed, but that 4 succeeded.  In the same log directory, compare the log for sort 4 against 1, 2, 3, etc.  Paste in one of the failing logs.

**Comment by cdb3ny** [comment]
Thanks. Ok, I get it.  The output for sort4 log succeeded but 1,2,3,5 etc failed - that makes sense when I look at the outputs as well.  Here is the failed sort log for #1.  The sort log for #4 ends with "success". 
[canu_correction_problem3.docx](https://github.com/marbl/canu/files/307907/canu_correction_problem3.docx)

**Comment by brianwalenz** [comment]
Hopefully you saw this already:
`Write failure on ovFile::writeOverlap: No space left on device`

**Comment by cdb3ny** [comment]
hmm - that would explain a lot.  Sorry I missed that line :)
