### ISSUE TITLE
Bogart fails, no .ctgStore or utgStore found

### ISSUE THREAD

**Issue by bbarbazuk** [marbl/canu#1471]
Hi,
I am running an assembly with parameters suggested to collapse haplotypes.  I have done the assembly using parameters that will not collapse haplotypes, and I am trying to re-run to produce a collapsed version for comparison.  I have a larger than expected genome assembly with ~30% duplicates based on BUSCO, but I'm trying to determine if this is a hetrozygosity issue.  I am using CANU 1.8, and running on a cluster using SLURM as a scheduler.

Anyway, my command is:

```
canu -assemble \
-p CLAM-V3-ASSEMBLE_SMASH-HAPLO-082319 -d CLAM-V3-ASSEMBLE_SMASH-HAPLO-082319 \
genomeSize=1g \
rawErrorRate=0.300 \
correctedErrorRate=0.15 \
corMhapSensitivity=normal \
corMinCoverage=4 \
corOutCoverage=40 \
minOverlapLength=200 \
minReadLength=1000 \
merylMemory=70 \
merylThreads=32 \
shell="/bin/bash" \
java="/apps/java/11.0.1/bin/java" \
-pacbio-corrected $PROJ_ROOT/CLAM-V3-TRIM_SMASH-HAPLO-071419.trimmedReads.fasta.gz \
usegrid=true \
gridOptionsJobName=CANU-default \
gridOptions="--time=14-00:00:00 --qos=icbrbi --account=icbrbi"
```

This ran until the 4-unitiger step at which time if failed due to a requested node configuration that was unavailable.
I edited the unitigger.jobSubmit-01.sh script and ran it by hand.

The edited script is:
```
#!/bin/sh

sbatch \
  --mem=128g --cpus-per-task=16 --partition=bigmem --time=14-00:00:00 --qos=icbrbi --account=icbrbi -o unitigger.%A_%a.out \
  -D `pwd` -J "bat_CLAM-V3-ASSEMBLE_SMASH-HAPLO-082319_CANU-default" \
  -a 1-1 \
  ./unitigger.sh 0 \
> ./unitigger.jobSubmit-01.out 2>&1

Unfortunately this results in a core dump and I get two .out files 'unitigger.41137906_1.out' and unitigger.41138607_1.out with similar contents.

unitigger.41137906_1.out reads:

```
Found perl:
   /usr/bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /apps/java/11.0.1/bin/java
   java version "11.0.1" 2018-10-16 LTS

Found canu:
   /apps/canu/1.8/libexec/bin/canu
   Canu snapshot (snapshot)

Running job 1 based on SLURM_ARRAY_TASK_ID=1 and offset=0.
/tmp/slurmd/job41137906/slurm_script: line 99: 26105 Aborted                 (core dumped) $bin/bogart -S ../../CLAM-V3-ASSEMBLE_SMASH-HAPLO-082319.seqStore -O ../CLAM-V3-ASSEMBLE_SMA
SH-HAPLO-082319.ovlStore -o ./CLAM-V3-ASSEMBLE_SMASH-HAPLO-082319 -gs 1000000000 -eg 0.15 -eM 0.15 -mo 200 -dg 6 -db 6 -dr 3 -ca 2100 -cp 200 -threads 16 -M 256 -unassembled 2 0 1.0 0
.5 3 > ./unitigger.err 2>&1
bogart appears to have failed. No CLAM-V3-ASSEMBLE_SMASH-HAPLO-082319.ctgStore or CLAM-V3-ASSEMBLE_SMASH-HAPLO-082319.utgStore found.
```
The contents of unitigger.41138607_1.out
are:
```
Found perl:
   /usr/bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /apps/java/11.0.1/bin/java
   java version "11.0.1" 2018-10-16 LTS

Found canu:
   /apps/canu/1.8/libexec/bin/canu
   Canu snapshot (snapshot)

Running job 1 based on SLURM_ARRAY_TASK_ID=1 and offset=0.
/tmp/slurmd/job41138607/slurm_script: line 99: 32091 Aborted                 (core dumped) $bin/bogart -S ../../CLAM-V3-ASSEMBLE_SMASH-HAPLO-082319.seqStore -O ../CLAM-V3-ASSEMBLE_SMA
SH-HAPLO-082319.ovlStore -o ./CLAM-V3-ASSEMBLE_SMASH-HAPLO-082319 -gs 1000000000 -eg 0.15 -eM 0.15 -mo 200 -dg 6 -db 6 -dr 3 -ca 2100 -cp 200 -threads 16 -M 256 -unassembled 2 0 1.0 0
.5 3 > ./unitigger.err 2>&1
bogart appears to have failed. No CLAM-V3-ASSEMBLE_SMASH-HAPLO-082319.ctgStore or CLAM-V3-ASSEMBLE_SMASH-HAPLO-082319.utgStore found.
```

The contents of the unitigger.err file are:

```
==> PARAMETERS.

Resources:
  Memory                256 GB
  Compute Threads       16 (command line)

Lengths:
  Minimum read          0 bases
  Minimum overlap       200 bases

Overlap Error Rates:
  Graph                 0.150 (15.000%)
  Max                   0.150 (15.000%)

Deviations:
  Graph                 6.000
  Bubble                6.000
  Repeat                3.000

Edge Confusion:
  Absolute              2100
  Percent               200.0000

Unitig Construction:
  Minimum intersection  500 bases
  Maxiumum placements   2 positions

Debugging Enabled:
  (none)

==> LOADING AND FILTERING OVERLAPS.

ReadInfo()-- Using 4743496 reads, no minimum read length used.

OverlapCache()-- limited to 262144MB memory (user supplied).

OverlapCache()--      36MB for read data.
OverlapCache()--     180MB for best edges.
OverlapCache()--     470MB for tigs.
OverlapCache()--     126MB for tigs - read layouts.
OverlapCache()--     180MB for tigs - error profiles.
OverlapCache()--   65536MB for tigs - error profile overlaps.
OverlapCache()--       0MB for other processes.
OverlapCache()-- ---------
OverlapCache()--   66621MB for data structures (sum of above).
OverlapCache()-- ---------
OverlapCache()--      90MB for overlap store structure.
OverlapCache()--  195431MB for overlap data.
OverlapCache()-- ---------
OverlapCache()--  262144MB allowed.
OverlapCache()--
OverlapCache()-- Retain at least 82 overlaps/read, based on 41.05x coverage.
OverlapCache()-- Initial guess at 2700 overlaps/read.
OverlapCache()--
OverlapCache()-- Adjusting for sparse overlaps.
OverlapCache()--
OverlapCache()--               reads loading olaps          olaps               memory
OverlapCache()--   olaps/read       all      some          loaded                 free
OverlapCache()--   ----------   -------   -------     ----------- -------     --------
OverlapCache()--         2700   4683365     60131       939749891  56.99%     181092 MB
OverlapCache()--       200070   4743496         0      1649042312 100.00%     170269 MB
OverlapCache()--
OverlapCache()-- Loading overlaps.
OverlapCache()--
OverlapCache()--          read from store           saved in cache
OverlapCache()--   ------------ ---------   ------------ ---------
OverlapCache()--       40330608 (002.45%)       37271879 (002.26%)
OverlapCache()--       85277536 (005.17%)       79484634 (004.82%)
OverlapCache()--      131656906 (007.98%)      123159141 (007.47%)
OverlapCache()--      179284373 (010.87%)      168087816 (010.19%)
OverlapCache()--      226288608 (013.72%)      212459591 (012.88%)
OverlapCache()--      271501984 (016.46%)      254998495 (015.46%)
OverlapCache()--      315494958 (019.13%)      296166445 (017.96%)
OverlapCache()--      349914481 (021.22%)      327977282 (019.89%)
OverlapCache()--      374614222 (022.72%)      350758864 (021.27%)
OverlapCache()--      400769601 (024.30%)      374926005 (022.74%)
OverlapCache()--      427453713 (025.92%)      399651075 (024.24%)
OverlapCache()--      454048570 (027.53%)      424155843 (025.72%)
OverlapCache()--      480310276 (029.13%)      448455982 (027.19%)
OverlapCache()--      507026718 (030.75%)      473247465 (028.70%)
OverlapCache()--      532960123 (032.32%)      497122780 (030.15%)
OverlapCache()--      559349702 (033.92%)      521602346 (031.63%)
OverlapCache()--      586908092 (035.59%)      547213111 (033.18%)
OverlapCache()--      612885454 (037.17%)      571174439 (034.64%)
OverlapCache()--      638549969 (038.72%)      594905908 (036.08%)
OverlapCache()--      666638563 (040.43%)      620630428 (037.64%)
OverlapCache()--      703334675 (042.65%)      654295556 (039.68%)
OverlapCache()--      740500953 (044.90%)      688557070 (041.75%)
OverlapCache()--      780476854 (047.33%)      725562567 (044.00%)
OverlapCache()--      821100765 (049.79%)      763354541 (046.29%)
OverlapCache()--      861733323 (052.26%)      801173436 (048.58%)
OverlapCache()--      900537497 (054.61%)      837108543 (050.76%)
OverlapCache()--      937916804 (056.88%)      871588974 (052.85%)
OverlapCache()--      973318874 (059.02%)      903964157 (054.82%)
OverlapCache()--     1004658662 (060.92%)      932565770 (056.55%)
OverlapCache()--     1033211058 (062.66%)      959101788 (058.16%)
OverlapCache()--     1060396660 (064.30%)      984438172 (059.70%)
OverlapCache()--     1089170439 (066.05%)     1011271809 (061.32%)
OverlapCache()--     1118039731 (067.80%)     1038310957 (062.96%)
OverlapCache()--     1146460025 (069.52%)     1064859695 (064.57%)
OverlapCache()--     1175392550 (071.28%)     1091946631 (066.22%)
OverlapCache()--     1203822937 (073.00%)     1118522609 (067.83%)
OverlapCache()--     1233492688 (074.80%)     1146241118 (069.51%)
OverlapCache()--     1262001294 (076.53%)     1172833119 (071.12%)
OverlapCache()--     1290913878 (078.28%)     1199631761 (072.75%)
OverlapCache()--     1319301705 (080.00%)     1225940272 (074.34%)
OverlapCache()--     1359121217 (082.42%)     1262848915 (076.58%)
OverlapCache()--     1402884498 (085.07%)     1303802542 (079.06%)
OverlapCache()--     1447649434 (087.79%)     1345885683 (081.62%)
OverlapCache()--     1494331398 (090.62%)     1389814890 (084.28%)
OverlapCache()--     1541704058 (093.49%)     1434471360 (086.99%)
OverlapCache()--     1587197721 (096.25%)     1477200999 (089.58%)
OverlapCache()--     1630468713 (098.87%)     1517592417 (092.03%)
OverlapCache()--   ------------ ---------   ------------ ---------
OverlapCache()--     1649042312 (100.00%)     1534900540 (093.08%)
OverlapCache()--
OverlapCache()-- Ignored 108076938 duplicate overlaps.
OverlapCache()--
OverlapCache()-- Symmetrizing overlaps.
OverlapCache()--   Finding missing twins.
OverlapCache()--   Found 2262360 missing twins in 1534900540 overlaps, 424271 are strong.
OverlapCache()--   Dropping weak non-twin overlaps; allocated 0 MB scratch space.
OverlapCache()--   Dropped 669623 overlaps; scratch space released.
OverlapCache()--   Adding 1592737 missing twin overlaps.
OverlapCache()--   Finished.

BestOverlapGraph()-- allocating best edges (144MB)

BestOverlapGraph()-- finding initial best edges.

BestOverlapGraph()-- filtering suspicious reads.
BestOverlapGraph()-- marked 951 reads as suspicious.

BestOverlapGraph()-- filtering high error edges.

BestOverlapGraph()-- filtering reads with lopsided best edges.

BestOverlapGraph()-- filtering spur reads.
BestOverlapGraph()-- detected 128699 spur reads and 3859 singleton reads.
BestOverlapGraph()-- detected 139 zombie reads.

BestOverlapGraph()-- removing best edges for contained reads.

==> BUILDING GREEDY TIGS.

breakSingletonTigs()-- Removed 115888 singleton tigs; reads are now unplaced.
optimizePositions()-- Optimizing read positions for 4743497 reads in 152516 tigs, with 16 threads.
optimizePositions()--   Allocating scratch space for 4743497 reads (296468 KB).
optimizePositions()--   Initializing positions with 16 threads.
optimizePositions()--   Recomputing positions, iteration 1, with 16 threads.
optimizePositions()--     Reset zero.
optimizePositions()--     Checking convergence.
optimizePositions()--     converged: 4606890 reads
optimizePositions()--     changed:   136607 reads
optimizePositions()--   Recomputing positions, iteration 2, with 16 threads.
optimizePositions()--     Reset zero.
optimizePositions()--     Checking convergence.
optimizePositions()--     converged: 4673777 reads
optimizePositions()--     changed:    69720 reads
optimizePositions()--   Recomputing positions, iteration 3, with 16 threads.
optimizePositions()--     Reset zero.
optimizePositions()--     Checking convergence.
optimizePositions()--     converged: 4711794 reads
optimizePositions()--     changed:    31703 reads
optimizePositions()--   Recomputing positions, iteration 4, with 16 threads.
optimizePositions()--     Reset zero.
optimizePositions()--     Checking convergence.
optimizePositions()--     converged: 4723858 reads
optimizePositions()--     changed:    19639 reads
optimizePositions()--   Recomputing positions, iteration 5, with 16 threads.
optimizePositions()--     Reset zero.
optimizePositions()--     Checking convergence.
optimizePositions()--     converged: 4728598 reads
optimizePositions()--     changed:    14899 reads
optimizePositions()--   Expanding short reads with 16 threads.
optimizePositions()--   Updating positions.
optimizePositions()--   Finished.

==> PLACE CONTAINED READS.

computeErrorProfiles()-- Computing error profiles for 152516 tigs, with 16 threads.
computeErrorProfiles()-- Finished.

placeContains()-- placing 4054573 contained and 344461 unplaced reads, with 16 threads.
placeContains()-- Placed 2840605 contained reads and 45764 unplaced reads.
placeContains()-- Failed to place 1213968 contained reads (too high error suspected) and 298697 unplaced reads (lack of overlaps suspected).
optimizePositions()-- Optimizing read positions for 4743497 reads in 152516 tigs, with 16 threads.
optimizePositions()--   Allocating scratch space for 4743497 reads (296468 KB).
optimizePositions()--   Initializing positions with 16 threads.
bogart: bogart/AS_BAT_OptimizePositions.C:202: void Unitig::optimize_initPlace(uint32, optPos*, optPos*, bool, std::set<unsigned int>&, bool): Assertion `cnt > 0' failed.

Failed with 'Aborted'; backtrace (libbacktrace):
utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP7siginfoPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
bogart/AS_BAT_OptimizePositions.C::202 in _ZN6Unitig18optimize_initPlaceEjP6optPosS1_bRSt3setIjSt4lessIjESaIjEEb()
bogart/AS_BAT_OptimizePositions.C::461 in (null)()
/home/nwani/m3/conda-bld/compilers_linux-64_1560109574129/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libgomp/team.c::123 in gomp_thread_start()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()

```
Any suggestions/comments you have that can explain what is happening and an y work around would be most helpful.

Thanks!

**Comment by skoren** [comment]
See #1414, this is a bug in the 1.8 release. You can follow the suggestions there to update to the 1.9 release branch and resume your assembly. It should be OK to resume the 1.8 assembly after you remove the unitigger/4-unitigging folder.

**Comment by skoren** [comment]
Any update on this?

**Comment by bbarbazuk** [comment]
Yes - sorry! Your suggestion worked perfectly. Installation of the newest version of CANU (1.9) solved the issue and the the run completed. Thanks!
