### ISSUE TITLE
Read Filtering Prior to Canu

### ISSUE THREAD

**Issue by stopalopa** [marbl/canu#1477]
Hello, 
I would like to use Canu to do error correction for nanopore reads without doing a full assembly. I was wondering if I need to do any kind of read filtering/trimming before running the error correction step or if I should run Canu on the raw reads as they are.  Are there benefits to using Canu's trimming over the trimming in NanoFilt?https://github.com/wdecoster/nanofilt 

Thanks.

**Comment by skoren** [comment]
We typically don't do any filtering and let the assembler pick the reads to correct. It may help speed to remove some low quality reads, especially if they are very long and repetitive (e.g. ATATATA or the like) but I'd suggest a conservative trimming.

**Comment by stopalopa** [comment]
Ok thanks!
