### ISSUE TITLE
Trying to find the root cause for a job failure

### ISSUE THREAD

**Issue by guibar** [marbl/canu#1480]
Hello,

I am using version 1.8 and I am trying an assembly with some nanopore and pacbio reads.

`canu -p doublon-mix -d doublon-mix genomeSize=380m gridOptionsOVL="--mem=12G" \
-pacbio-raw /home/gbarreau/work/melon/doublon/raw/pacbio.1.fasta \
-pacbio-raw /home/gbarreau/work/melon/doublon/raw/pacbio.2.fasta \
-pacbio-raw /home/gbarreau/work/melon/doublon/raw/pacbio.3.fasta \
-pacbio-raw /home/gbarreau/work/melon/doublon/raw/pacbio.4.fasta \
-nanopore-raw /home/gbarreau/work/melon/doublon/raw/minion.fastq.gz`

This job had failed previously and I was able to find the following message in file 
doublon-mix/unitigging/3-overlapErrorAdjustment/red.7637144_40.out

`slurmstepd: error: Job 7637160 exceeded memory limit (7340956 > 7340032), being killed
slurmstepd: error: Exceeded job memory limit
slurmstepd: error: *** JOB 7637160 ON node024 CANCELLED AT 2019-09-05T14:14:56 ***`

which is why I tried running again with the gridOptionsOVL="--mem=12G"

This time the job fails with the following message in the canu.out file

```
-- Read error detection jobs failed, tried 2 times, giving up.
--   job 00039.red FAILED.
--   job 00040.red FAILED.
--   job 00041.red FAILED.
--   job 00042.red FAILED.
--   job 00043.red FAILED.
```
However, when I look at the files:

unitigging/3-overlapErrorAdjustment/red.7792387_39.out
unitigging/3-overlapErrorAdjustment/red.7792387_40.out
unitigging/3-overlapErrorAdjustment/red.7792387_41.out
unitigging/3-overlapErrorAdjustment/red.7792387_42.out
unitigging/3-overlapErrorAdjustment/red.7792387_43.out

```
/var/spool/slurm/d/job7792387/slurm_script: line 257: 153369 Killed                  $bin/findErrors -S ../../doublon-mix.seqStore -O ../doublon-mix.ovlStore -R $minid $maxid -e 0.12 -l 500 -o ./$jobid.red.WORKING -t 4
slurmstepd: error: Detected 1 oom-kill event(s) in step 7792387.batch cgroup.
```
Any idea where I could try to find the root cause of the problem?

Thanks a lot,

**Comment by skoren** [comment]
The step exceeding memory isn't ovl so your option had no effect. Add ```gridOptionsRed="--mem=16G"``` instead. That should double the memory requested for this step. Remove unitigging/3-overlapErrorAdjustment/red.jobSubmit*``` before re-launching the Canu command.

**Comment by guibar** [comment]
Thanks a lot! Indeed, I should have guessed it was red from the file name.
I will close this issue if all goes well.

**Comment by guibar** [comment]
It worked with the memory adjustment.
Thanks!
