### ISSUE TITLE
Meryl error 

### ISSUE THREAD

**Issue by francicco** [marbl/canu#1481]
Hi,

I'm having this error while running `Meryl`:

```ABORT:   /mnt/storage/software/apps/canu/Linux-amd64/bin/meryl: /mnt/storage/easybuild/software/GCCcore/5.4.0/lib64/libgomp.so.1: version `GOMP_4.5' not found (required by /mnt/storage/software/apps/canu/Linux-amd64/bin/meryl)```

How can I fix this.

Thanks a lot
F

**Comment by skoren** [comment]
That is actually a compilation error, the system you're running on is missing OpenMP. How did you install Canu, download and build yourself? If so, download a pre-compiled release binary instead, it should avoid this error.

**Comment by skoren** [comment]
Idle, compilation issue.
