### ISSUE TITLE
Canu useGrid=true in Singularity container - can't find Slurm

### ISSUE THREAD

**Issue by chrisjackson-pellicle** [marbl/canu#1482]
Hi. I've installed Canu in a Singularity container, running on an Ubuntu host that has Slurm as the job scheduler. Ideally I'd like to use Canu's automatic grid job submission feature (useGrid=true), but as it's running inside a container it can't see the host Slurm as the grid manager, and so runs in local mode (i.e. the log file states 'No grid engine detected, grid disabled). 

Is there a way to run Canu inside a container, with useGrid=true, detecting the host Slurm and submitting jobs accordingly to multiple nodes?

Thanks very much for any info! 

**Canu command:**

canu -d canu_run \
  -p assembly \
  genomeSize=0.03m \
  gnuplot='/usr/bin/gnuplot' \
  useGrid=true \
  gridOptions="--time=0-1:0:00" \
  -nanopore-raw ${nano_reads}/*.fastq.gz

**Canu version:**
1.8

**System details**
Ubuntu 18.10
singularity version 3.2.0-rc1.318.gf496fe9ee
slurm 18.08.5-2

**Comment by skoren** [comment]
The singularity container is blocking Canu from seeing the grid. I am not aware of a way to make singularity let Canu see or interact with the grid outside it. That would seem to be against the point of a container. 

You can see a similar discussion in #1415, essentially running like this is akin to splitting Canu apart and putting the pipeline back together yourself. I'd suggest running Canu outside a singularity container if you want to use the grid engine.
