### ISSUE TITLE
Error during Unitig Consensus - " Assertion `bgn < end' failed "

### ISSUE THREAD

**Issue by rozaimirazali** [marbl/canu#1483]
Hello.

I am getting a core dump during unitig consensus stage. I looked at all closed cases related to error during unitig consesus generation but majority of them are about unable to align. The closest I found was by @Lcornet in https://github.com/marbl/canu/issues/1325#issuecomment-482741088 but I am using a newer version of Canu than him, and his solution was to upgrade.

But in my case, I am able to align.

> -rw-rw-r-- 1 rmohamadrazali sysbio  26K Sep 15 18:32 consensus.220.out
-rw-rw-r-- 1 rmohamadrazali sysbio  17K Sep 15 18:33 consensus.217.out
-rw-rw-r-- 1 rmohamadrazali sysbio  19K Sep 15 18:35 consensus.219.out
-rw-rw-r-- 1 rmohamadrazali sysbio  14K Sep 15 18:35 consensus.224.out
-rw-rw-r-- 1 rmohamadrazali sysbio  16K Sep 15 18:35 consensus.218.out
-rw-rw-r-- 1 rmohamadrazali sysbio  34K Sep 15 18:36 consensus.225.out
drwxrwxr-x 2 rmohamadrazali sysbio 4.0K Sep 15 18:36 utgcns
-rw-rw-r-- 1 rmohamadrazali sysbio 7.1K Sep 15 18:36 consensus.223.out
-rwxr-xr-x 1 rmohamadrazali sysbio  291 Sep 15 18:36 consensus.jobSubmit-01.sh
-rw-rw-r-- 1 rmohamadrazali sysbio   44 Sep 15 18:36 consensus.jobSubmit-01.out
-rw------- 1 rmohamadrazali sysbio 1.2G Sep 16 09:58 core.12723
-rw-rw-r-- 1 rmohamadrazali sysbio 418M Sep 16 09:58 MNDY0206.assembly.e
-rw-rw-r-- 1 rmohamadrazali sysbio  24K Sep 16 09:58 consensus.145.out
-rwxr-xr-x 1 rmohamadrazali sysbio 2.0K Sep 16 09:58 consensus.sh

The log (MNDY0206.assembly.e) file shows the following (I'm bolding what I think is the cause of the problem).

> ...
> Align of length 4351 with 126 gaps stored in 45855 bits.
> Align of length 2417 with 71 gaps stored in 46503 bits.
> Align of length 1250 with 37 gaps stored in 46856 bits.
> utgcns: utgcns/unitigConsensus.C:1095: void unitigConsensus::findCoordinates(): **Assertion `bgn < end' failed**.
> 
> Failed with 'Aborted'; backtrace (libbacktrace):
> utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
> (null)::0 in (null)()
> (null)::0 in (null)()
> (null)::0 in (null)()
> (null)::0 in (null)()
> (null)::0 in (null)()
> 
> utgcns/unitigConsensus.C::1095 in _ZN15unitigConsensus15findCoordinatesEv()
> utgcns/unitigConsensus.C::1237 in _ZN15unitigConsensus8generateEP5tgTigccPSt3mapIjP6sqReadSt4lessIjESaISt4pairIKjS4_EEEPS2_IjP10sqReadDataS6_SaIS7_IS8_SE_EEE()
> utgcns/utgcns.C::529 in main()
> (null)::0 in (null)()
> (null)::0 in (null)()
> (null)::0 in (null)()
> 
> ./consensus.sh: line 100: 12723 Aborted                 (core dumped) $bin/utgcns -S ../MNDY0206-haplotypePat.${tag}Store/partitionedReads.seqStore -T ../MNDY0206-haplotypePat.${tag}Store 1 $jobid -O ./${tag}cns/$jobid.cns.WORKING -maxcoverage 40 -e 0.075 -pbdagcon -edlib -threads 4

Is it saying that I have a unitig/read where the START is bigger than the END?

My Canu version:

```
[rmohamadrazali@hpclogin1 5-consensus]$ canu --version
Canu snapshot v1.8 +106 changes (r9316 490b517a05233e031c60260d709a2442bc7995a2)
```

**Comment by skoren** [comment]
Your version still had the bug, you can see from issue #1364 which is newer than your version.

In general you should not be using a checkout from tip to run assemblies, the releases are tested and stable while the tip is not. Your best option is to update to the 1.9 branch and re-run.

**Comment by rozaimirazali** [comment]
The weird thing is that it works fine for _haplotypeMat_ (as seen below). The problem occurs only in my _haplotypePat_

![Screen Shot 2019-09-17 at 1 56 54 PM](https://user-images.githubusercontent.com/37179568/65035964-0b809580-d953-11e9-983f-203d4b4b5e64.png)

I just installed v1.9 and will try to re-run this but will it re-run from the last stop point in _haplotypePat_  and leave the _haplotypeMat_ alone ? 

FYI, the _haplotypeMat_ is still running in the server. Should I wait until the _haplotypeMat_ finishes or should I kill the _haplotypeMat_ jobs?

**JOBID   USER    STAT  QUEUE      FROM_HOST   EXEC_HOST   JOB_NAME   SUBMIT_TIME**

72183[1] rmo RUN   normal     nsnode29    32*JRNAS1   **gfa_MNDY0206-haplotypeMat[1]** Sep 17 08:30
72184   rmo PEND  normal     nsnode29       -        **canu_MNDY0206-haplotypeMat** Sep 17 08:30

**Comment by skoren** [comment]
The two assemblies (mat and pat) are completely independent and have different contigs/reads so it's not suprising they have different results. You can leave the mat running and just launch pat alone using the shell script canu left behind (```asm-haplotypePaternal.sh``` or similar).

**Comment by skoren** [comment]
Any update on this?

**Comment by skoren** [comment]
Idle
