### ISSUE TITLE
Canu cannot successfully run in parallel on my cluster

### ISSUE THREAD

**Issue by Gostwander** [marbl/canu#1484]
Hello,
I have searched similar issues I ran into, but it did not solve my problem.
I use the cluster to run my jobs, and if I use 'useGrid=False', the job ran successfully but very slow which is not ideal, when I try to run in parallel, Canu failed.
This is my slurm submission script:
```
#!/bin/sh
#SBATCH --account=##
#SBATCH --qos=##
#SBATCH --job-name=correct
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=##
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=50
#SBATCH --mem=200gb
#SBATCH --time=48:00:00
#SBATCH --output=canu_correct%j.out
pwd; hostname; date

cd /goodrun
module load canu
canu -correct -p similis -d canu genomeSize=65.5m maxMemory=180 maxThreads=50 -nanopore-raw Rsimilis.goodrun.fq
```

And this is the Canu.out file:
```
Found perl:
   /apps/canu/1.8/bin/perl
   This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-l
inux-thread-multi

Found java:
   /apps/canu/1.8/bin/java
   openjdk version "11.0.1" 2018-10-16 LTS

Found canu:
   /apps/canu/1.8/libexec/bin/canu
   Canu snapshot (snapshot)

-- Canu snapshot (snapshot)
--
-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer wei
ghting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
-- 
-- Koren S, Rhie A, Walenz BP, Dilthey AT, Bickhart DM, Kingan SB, Hiend
leder S, Williams JL, Smith TPL, Phillippy AM.
-- De novo assembly of haplotype-resolved genomes with trio binning.
-- Nat Biotechnol. 2018
-- https//doi.org/10.1038/nbt.4277
-- 
-- Read and contig alignments during correction, consensus and GFA build
ing use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using ed
it distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locali
ty-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- Corrected read consensus sequences are generated using an algorithm d
erived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '11.0.1' (from 'java') without -d64 support.
-- Detected gnuplot version '5.2 patchlevel 7   ' (from 'gnuplot') and image format 'png'.
-- Detected 32 CPUs and 125 gigabytes of memory.
-- Limited to 180 gigabytes from maxMemory option.
-- Limited to 50 CPUs from maxThreads option.
-- Detected Slurm with 'sinfo' binary in /opt/slurm/bin/sinfo.
-- Detected Slurm with 'MaxArraySize' limited to 10000 jobs.
-- 
-- Found  32 hosts with  32 cores and  186 GB memory under Slurm control.
-- Found   8 hosts with   8 cores and   62 GB memory under Slurm control.
-- Found  10 hosts with  32 cores and  186 GB memory under Slurm control.
-- Found   6 hosts with  32 cores and  125 GB memory under Slurm control.
-- Found  25 hosts with  28 cores and  125 GB memory under Slurm control.
-- Found   2 hosts with  16 cores and   31 GB memory under Slurm control.
-- Found  24 hosts with  12 cores and   93 GB memory under Slurm control.
-- Found  64 hosts with  16 cores and   62 GB memory under Slurm control.
-- Found   1 host  with 192 cores and 1509 GB memory under Slurm control.
-- Found   1 host  with  24 cores and  750 GB memory under Slurm control
.
-- Found   1 host  with  48 cores and  500 GB memory under Slurm control.
-- Found  22 hosts with  32 cores and  182 GB memory under Slurm control.
-- Found 897 hosts with  32 cores and  125 GB memory under Slurm control.
-- Found 222 hosts with  64 cores and  250 GB memory under Slurm control.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl      7 GB    4 CPUs  (k-mer counting)
-- Grid:  hap        7 GB    4 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   10 GB    4 CPUs  (overlap detection with mhap)
-- Grid:  obtovl     8 GB    4 CPUs  (overlap detection)
-- Grid:  utgovl     8 GB    4 CPUs  (overlap detection)
-- Grid:  ovb        4 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs        8 GB    1 CPU   (overlap store sorting)
-- Grid:  red        7 GB    4 CPUs  (read error detection)
-- Grid:  oea        4 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat       64 GB    8 CPUs  (contig construction with bogart)
-- Grid:  gfa        8 GB    8 CPUs  (GFA alignment and processing)
--
-- In 'similis.seqStore', found Nanopore reads:
--   Raw:        480801
--   Corrected:  0
--   Trimmed:    0
--
-- Generating assembly 'similis' in '/goodrun/canu'
--
-- Parameters:
--
--  genomeSize        65500000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1200 ( 12.00%)
--    utgOvlErrorRate 0.1200 ( 12.00%)
--
--  Overlap Processing Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1200 ( 12.00%)
--    utgOvlErrorRate 0.1200 ( 12.00%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1200 ( 12.00%)
--    utgErrorRate    0.1200 ( 12.00%)
--    cnsErrorRate    0.2000 ( 20.00%)
--
--
-- BEGIN CORRECTION
--
--
-- Mhap precompute jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/blocks/000001.dat FAILED.
--   job correction/1-overlapper/blocks/000002.dat FAILED.
--   job correction/1-overlapper/blocks/000003.dat FAILED.
--   job correction/1-overlapper/blocks/000004.dat FAILED.
--   job correction/1-overlapper/blocks/000005.dat FAILED.
--   job correction/1-overlapper/blocks/000006.dat FAILED.
--   job correction/1-overlapper/blocks/000007.dat FAILED.
--   job correction/1-overlapper/blocks/000008.dat FAILED.
--   job correction/1-overlapper/blocks/000009.dat FAILED.
--   job correction/1-overlapper/blocks/000010.dat FAILED.
--   job correction/1-overlapper/blocks/000011.dat FAILED.
--   job correction/1-overlapper/blocks/000012.dat FAILED.
--   job correction/1-overlapper/blocks/000013.dat FAILED.
--   job correction/1-overlapper/blocks/000014.dat FAILED.
--   job correction/1-overlapper/blocks/000015.dat FAILED.
--   job correction/1-overlapper/blocks/000016.dat FAILED.
--   job correction/1-overlapper/blocks/000017.dat FAILED.
--   job correction/1-overlapper/blocks/000018.dat FAILED.
--

ABORT:
ABORT: Canu snapshot (snapshot)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```

**Comment by skoren** [comment]
As in other similar issues, the cause is likely a mis-configured JVM or a cluster submission issue. Post the output of one of the failing jobs (```correction/1-overlapper/precompute.*.out```).

**Comment by Gostwander** [comment]
Thanks for the quick reply. This is from one of the 'precompute.41398941_10.out'
Found perl:
   /apps/perl/perls/perl-5.16.0/bin/perl
   This is perl 5, version 16, subversion 0 (v5.16.0) built for x86_64-linux-thr
ead-multi

Found java:
   /apps/java/jdk1.8.0_31/bin/java
   java version "1.8.0_31"

Found canu:
   /apps/canu/1.9/bin/canu
   Canu branch v1.9 +314 changes (r9524 b6c7bd2afc76b69e88cf781294e5d82246c68959
)

Running job 10 based on SLURM_ARRAY_TASK_ID=10 and offset=0.
Dumping reads from 243001 to 270000 (inclusive).

Starting mhap precompute.

Running with these settings:
--filter-threshold = 1.0E-7
--help = false
--max-shift = 0.2
--min-olap-length = 500
--min-store-length = 0
--no-rc = false
--no-self = false
--no-tf = false
--num-hashes = 512
--num-min-matches = 3
--num-threads = 4
--ordered-kmer-size = 12
--ordered-sketch-size = 1536
--repeat-idf-scale = 10.0
--repeat-weight = 0.9
--settings = 0
--store-full-id = true
--supress-noise = 0
--threshold = 0.83
--version = false
-f = ../../0-mercounts/similis.ms16.ignore.gz
-h = false
-k = 16
-p = ./000010.input.fasta
-q = .
-s = 
Reading in filter file ../../0-mercounts/similis.ms16.ignore.gz.
Read in values for repeat 1197200 and 0
Warning, k-mer filter file has zero elements.
Initializing
Trying size 1197200 and it was successfull
Initialized
Time (s) to read filter file: 5.741421982
Read in k-mer filter for sizes: [16]
Processing FASTA files for binary compression...
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
slurmstepd: error: *** JOB 41398951 ON c2a-s19 CANCELLED AT 2019-09-16T11:10:20 DUE TO TIME LIMIT ***

**Comment by skoren** [comment]
The jobs are being killed due to a time limit on your system, not sure what the default is but you should supply your own grid parameters for Canu to use (e.g. ```gridOptions="--time=48:00:00" --account=## --qos=## --mail-type=END,FAIL --mail-user=##"``` to match your initial run) as documented in the FAQ (https://canu.readthedocs.io/en/latest/faq.html#how-do-i-run-canu-on-my-slurm-sge-pbs-lsf-torque-system).

**Comment by Gostwander** [comment]
I added gridOption="--time=48:00:00", the precompute job finished successfully, however the mhap overlap jobs failed, this is from Canu.out:
-- Mhap overlap jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/results/000001.ovb FAILED.
--   job correction/1-overlapper/results/000002.ovb FAILED.
--   job correction/1-overlapper/results/000003.ovb FAILED.
--   job correction/1-overlapper/results/000004.ovb FAILED.
--   job correction/1-overlapper/results/000006.ovb FAILED.
--   job correction/1-overlapper/results/000007.ovb FAILED.
--   job correction/1-overlapper/results/000008.ovb FAILED.
--   job correction/1-overlapper/results/000009.ovb FAILED.
--   job correction/1-overlapper/results/000010.ovb FAILED.
--   job correction/1-overlapper/results/000011.ovb FAILED.
--   job correction/1-overlapper/results/000012.ovb FAILED.
--   job correction/1-overlapper/results/000013.ovb FAILED.
--   job correction/1-overlapper/results/000014.ovb FAILED.
--   job correction/1-overlapper/results/000015.ovb FAILED.
--   job correction/1-overlapper/results/000016.ovb FAILED.
--   job correction/1-overlapper/results/000017.ovb FAILED.
--   job correction/1-overlapper/results/000018.ovb FAILED.
--   job correction/1-overlapper/results/000019.ovb FAILED.
--   job correction/1-overlapper/results/000020.ovb FAILED.
--   job correction/1-overlapper/results/000022.ovb FAILED.
--   job correction/1-overlapper/results/000023.ovb FAILED.
--   job correction/1-overlapper/results/000024.ovb FAILED.
--   job correction/1-overlapper/results/000025.ovb FAILED.
--   job correction/1-overlapper/results/000026.ovb FAILED.
--   job correction/1-overlapper/results/000027.ovb FAILED.
--   job correction/1-overlapper/results/000028.ovb FAILED.
--   job correction/1-overlapper/results/000029.ovb FAILED.
--   job correction/1-overlapper/results/000030.ovb FAILED.
--   job correction/1-overlapper/results/000031.ovb FAILED.
--   job correction/1-overlapper/results/000032.ovb FAILED.
--   job correction/1-overlapper/results/000033.ovb FAILED.
--   job correction/1-overlapper/results/000034.ovb FAILED.
--   job correction/1-overlapper/results/000035.ovb FAILED.
--   job correction/1-overlapper/results/000036.ovb FAILED.
--   job correction/1-overlapper/results/000037.ovb FAILED.
--   job correction/1-overlapper/results/000038.ovb FAILED.
--   job correction/1-overlapper/results/000039.ovb FAILED.
--   job correction/1-overlapper/results/000040.ovb FAILED.
--   job correction/1-overlapper/results/000041.ovb FAILED.
--   job correction/1-overlapper/results/000042.ovb FAILED.
--   job correction/1-overlapper/results/000043.ovb FAILED.
--   job correction/1-overlapper/results/000044.ovb FAILED.
--   job correction/1-overlapper/results/000045.ovb FAILED.
--   job correction/1-overlapper/results/000046.ovb FAILED.
--

ABORT:
ABORT: Canu branch v1.9 +314 changes (r9524 b6c7bd2afc76b69e88cf781294e5d82246c68959)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.

**Comment by skoren** [comment]
Same as before, post the output of one of the failing jobs (correction/1-overlapper/mhap.*.out).

**Comment by Gostwander** [comment]
And this is the end of mhap.41403168_10.out, does this mean I need to request more memory?
Average number of matches per lookup: 7665.776755555556
Average number of table elements processed per lookup: 136339.41846666666
Average number of table elements processed per match: 17.78546686320581
Average % of hashed sequences hit per lookup: 25.787538710562412
Average % of hashed sequences hit that are matches: 55.04939048271362
Average % of hashed sequences fully compared that are matches: 91.81338075816362
writeToFile()-- After writing 7852 out of 831954 'ovFile::writeBuffer::sb' objects (1 bytes each): Disk quota exceeded

**Comment by skoren** [comment]
Not memory, you're out of disk space. You'll need to run in a FS with more space or request more quota from your cluster admin. When you get more space, remove all files under correction/1-overlapper/results/ and re-start.

**Comment by Gostwander** [comment]
Hello
I ran out of disk space again at this step:
Creating overlap store correction/similis.ovlStore using:
--     46 buckets
--    219 slices
--        using at most 8 GB memory each
--
-- Overlap store bucketizer jobs failed, retry.
--   job correction/similis.ovlStore.BUILDING/bucket0001 FAILED.

 I had 1.5 TB space before I ran mhap jobs, with my original 2918049805 bases fastq input, my target genome is about 65mb, how much disk space does Canu need to finish the correction and assembly?

**Comment by skoren** [comment]
I would not expect a 65mb genome to take that much space, typically a human run takes a couple of tb. It can be higher on very repetitive genomes but again I wouldn't expect a 65mb genome to be that bad. 

There are intermediate files you can remove manually to clean up space (if you upgrade to the 1.9 branch you can also add ```purgeOverlaps=aggressive``` to do this automatically). First check how much space is being used by the full canu correction folder (```du --max-depth 2 -h``` in correction).

**Comment by Gostwander** [comment]
584G	./1-overlapper/results
13G	./1-overlapper/blocks
188K	./1-overlapper/queries
597G	./1-overlapper
11G	./similis.ovlStore.BUILDING/create0020
20G	./similis.ovlStore.BUILDING/create0040
25G	./similis.ovlStore.BUILDING/create0025
24G	./similis.ovlStore.BUILDING/create0010
1.9G	./similis.ovlStore.BUILDING/bucket0046
8.9G	./similis.ovlStore.BUILDING/create0028
25G	./similis.ovlStore.BUILDING/create0031
26G	./similis.ovlStore.BUILDING/create0004
24G	./similis.ovlStore.BUILDING/create0014
23G	./similis.ovlStore.BUILDING/create0015
6.8G	./similis.ovlStore.BUILDING/bucket0045
5.4G	./similis.ovlStore.BUILDING/bucket0033
17G	./similis.ovlStore.BUILDING/bucket0027
24G	./similis.ovlStore.BUILDING/create0029
24G	./similis.ovlStore.BUILDING/create0009
24G	./similis.ovlStore.BUILDING/create0035
27G	./similis.ovlStore.BUILDING/create0022
21G	./similis.ovlStore.BUILDING/create0007
5.3G	./similis.ovlStore.BUILDING/bucket0021
10G	./similis.ovlStore.BUILDING/create0011
5.4G	./similis.ovlStore.BUILDING/bucket0041
12G	./similis.ovlStore.BUILDING/bucket0030
19G	./similis.ovlStore.BUILDING/bucket0037
21G	./similis.ovlStore.BUILDING/create0042
26G	./similis.ovlStore.BUILDING/create0034
312K	./similis.ovlStore.BUILDING/logs
80K	./similis.ovlStore.BUILDING/scripts
23G	./similis.ovlStore.BUILDING/create0016
14G	./similis.ovlStore.BUILDING/bucket0044
21G	./similis.ovlStore.BUILDING/create0012
21G	./similis.ovlStore.BUILDING/create0043
22G	./similis.ovlStore.BUILDING/create0008
4.8G	./similis.ovlStore.BUILDING/bucket0005
12G	./similis.ovlStore.BUILDING/bucket0017
23G	./similis.ovlStore.BUILDING/create0038
21G	./similis.ovlStore.BUILDING/create0023
28G	./similis.ovlStore.BUILDING/create0006
23G	./similis.ovlStore.BUILDING/create0019
25G	./similis.ovlStore.BUILDING/create0024
24G	./similis.ovlStore.BUILDING/create0032
12G	./similis.ovlStore.BUILDING/bucket0039
23G	./similis.ovlStore.BUILDING/create0036
21G	./similis.ovlStore.BUILDING/create0026
11G	./similis.ovlStore.BUILDING/create0003
27G	./similis.ovlStore.BUILDING/create0002
29G	./similis.ovlStore.BUILDING/create0001
18G	./similis.ovlStore.BUILDING/bucket0013
25G	./similis.ovlStore.BUILDING/create0018
847G	./similis.ovlStore.BUILDING
25M	./0-mercounts
1.5T	.

**Comment by skoren** [comment]
Interesting, it does seem you have some large overlap outputs, are all the files in ```correction/1-overlapper/results``` named something like ```*.ovb``` or ```*.oc```? 

If it's easy for you to get more space, you can request a larger quota, 5tb should be enough I expect, less if you update to the 1.9 release and add the ```purgeOverlaps=aggressive``` option I suggested above (you should be able to remove the ```similis.ovlStore.BUILDING``` folder and re-start 1.9 and it will continue. Without that you could manually clean up as you run to keep the space down (at the current step you can remove the 1-overlapper/blocks folder, once you have a ```similis.ovlStore.BUILDING/1-bucketizing.success```) file you can remove the 1-overlapper/results folder.

If you can't easily get more space, then the best option is to try the parameters from the FAQ (```orMhapFilterThreshold=0.0000000002 corMhapOptions="--repeat-idf-scale 50" mhapMemory=60g mhapBlockSize=500 ovlMerDistinct=0.975```). You'd have to restart from scratch with these parameters.

**Comment by Gostwander** [comment]
Thanks a lot for all the suggestions. Yes, the files in results are *.oc and *.ovb for each unique number (000001 to 000046). I am going to request 10Tb. Will the assemble step need this much disk space as well?

**Comment by skoren** [comment]
No, that is typically much smaller, you're at the largest usage of space in the process right now.

**Comment by Gostwander** [comment]
I know this kind of question is hard to answer, but just want to get a general idea. Is the trimming step time consuming? It was run for 48 hour and have not finished yet. If it is taking so long, does it mean there is something wrong with my sequences?

**Comment by skoren** [comment]
Trimming and unitig overlapping are relatively slow, especially if you have very long reads. You can use the ```-fast``` option which will be much faster but may give a less continuous assembly. The wall-clock will vary based on how many nodes you're able to reserve at a time for the run. 

One thing to check is the threshold in ```trimming/0-*/*.dump```, check the minimum value of the second column. If it is much higher than about 500, you can speed up your run by adding some of the parameters I mentioned above (if you're not already) like ```ovlMerDistinct=0.975```. You'd have to re-start the trimming step to do this though.

**Comment by skoren** [comment]
Idle, original issue of submissions resolved.
