### ISSUE TITLE
Failure in Triming during creating overlap store

### ISSUE THREAD

**Issue by Malabady** [marbl/canu#1485]
Hello: 

I am running stage-by-stage and having trouble finishing the trimming stage. A subset of the overlap store jobs keeps on failing after restarting the canu (v1.8) multiple times. Here is part of the error file:
```
-- BEGIN TRIMMING
--
--
-- Creating overlap store trimming/Spu.ovlStore using:
--    126 buckets
--    126 slices
--        using at most 29 GB memory each
--
-- Running jobs.  First attempt out of 2.
--
-- 'scripts/1-bucketize.jobSubmit-01.sh' -> job 1574360.sapelo2 task 12.
-- 'scripts/1-bucketize.jobSubmit-02.sh' -> job 1574361.sapelo2 task 47.
-- 'scripts/1-bucketize.jobSubmit-03.sh' -> job 1574362.sapelo2 task 49.
-- 'scripts/1-bucketize.jobSubmit-04.sh' -> job 1574363.sapelo2 task 51.
-- 'scripts/1-bucketize.jobSubmit-05.sh' -> job 1574364.sapelo2 task 53.
-- 'scripts/1-bucketize.jobSubmit-06.sh' -> job 1574365.sapelo2 task 65.
-- 'scripts/1-bucketize.jobSubmit-07.sh' -> job 1574366.sapelo2 task 88.
-- 'scripts/1-bucketize.jobSubmit-08.sh' -> job 1574367.sapelo2 task 105.
-- 'scripts/1-bucketize.jobSubmit-09.sh' -> job 1574368.sapelo2 task 116.
-- 'scripts/1-bucketize.jobSubmit-10.sh' -> job 1574369.sapelo2 task 120.
-- 'scripts/1-bucketize.jobSubmit-11.sh' -> job 1574370.sapelo2 task 123.
-- 'scripts/1-bucketize.jobSubmit-12.sh' -> job 1574371.sapelo2 task 126.
--
----------------------------------------
-- Starting command on Wed Sep 18 09:02:25 2019 with 511067.333 GB free disk space

    cd /scratch/malabady/PitcherGenome/PitchPacBio/canu_assembly/40x_assembly/rosea8-trim
    qsub \
      -j oe \
      -d `pwd` \
      -W depend=afterany:1574360.sapelo2:1574361.sapelo2:1574362.sapelo2:1574363.sapelo2:1574364.sapelo2:1574365.sapelo2:1574366.sapelo2:1574367.sapelo2:1574368.sapelo2:1574369.sapelo2:1574370.sapelo2:1574371.sapelo2 \
      -l mem=4g \
      -l nodes=1:ppn=1 \
      -q batch \
      -l walltime=30:00:00:00  \
      -N 'canu_Spu' \
      -o canu-scripts/canu.26.out  canu-scripts/canu.26.sh

-- Finished on Wed Sep 18 09:02:25 2019 (in the blink of an eye) with 511067.333 GB free disk space
----------------------------------------
```
- I added the following flag to the original canu command to increase the memory per dependent job to 24gb, but still failed: 
gridOptionsOVS="-l mem=24g" gridOptionsOVB="-l mem=24g"

- I tried to run the the script "1-bucketize.sh" on each individual job but for some reasons didn't work. I tired to run it from the "trimming" directory, but it complained that it can't read the "./Spu.ovlStore.config" file although the file is present in the directory. Here is what is in the "trimming" dir:
0-mercounts  
1-overlapper  
Spu.ovlStore.BUILDING  
Spu.ovlStore.config  
Spu.ovlStore.config.txt

- I removed the "Spu.ovlStore.*" data and started the canu again but it failed at the exact same files. 

Any idea what's going on? 

Many thanks.

**Comment by skoren** [comment]
This is often caused by filesystem corruption (upstream of the store building which is why your removing the store didn't help). Each of these jobs also wants 29gb of memory so requesting 24gb for them is too low and will also not work, you'd want to request 30gb+, so say 40gb to give a buffer.

What is the actual error from the failing jobs, correction/Spu.ovlStore.BUILDING/logs/1-bucketize*12*out```?

**Comment by Malabady** [comment]
The logs folder has no files in it. It is totally empty. The increased the memory to 50gb and run it but it failed again. Is there a way to run these jobs manually?


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by skoren** [comment]
There should be logs from the runs, unless your grid is not saving output from failed jobs it terminated, which doesn't make sense from a usability standpoint.

You can run the jobs manually, you should run them from inside the Spu.ovlStore.BUILDING folder, run sh scripts/1-bucketize.sh 12 on a node with at least 50gb reserved and see what it outputs.

**Comment by Malabady** [comment]
Is there any files that I need to delete before trying to rerun manually? For the failing jobs, there are folders named “creat00**” where is “**” is he job number as 12, 47, etc.. Do I keep or remove those folders?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by skoren** [comment]
It should be fine to leave them, the default bucketizing scripts will force overwrite the partial outputs.

**Comment by Malabady** [comment]
Hey Sergy,

I tried to manually run those jobs on a node with 120gb free memory, but it failed. Here is the verbose:


-------------------
Constructing slice 12 for store './Spu.ovlStore.BUILDING'.
- Filtering overlaps over 1.0000 fraction error.

Bucketizing input    1 out of   15 - '1-overlapper/001/000012.ovb'
Bucketizing input    2 out of   15 - '1-overlapper/001/000161.ovb'
Bucketizing input    3 out of   15 - '1-overlapper/001/000304.ovb'
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Failed with 'Aborted'; backtrace (libbacktrace):
utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP7siginfoPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
../../gcc-4.8.2/libstdc++-v3/libsupc++/vterminate.cc::95 in _ZN9__gnu_cxx27__verbose_terminate_handlerEv()
../../gcc-4.8.2/libstdc++-v3/libsupc++/eh_terminate.cc::38 in _ZN10__cxxabiv111__terminateEPFvvE()
../../gcc-4.8.2/libstdc++-v3/libsupc++/eh_terminate.cc::48 in _ZSt9terminatev()
../../gcc-4.8.2/libstdc++-v3/libsupc++/eh_throw.cc::84 in __cxa_throw()
../../gcc-4.8.2/libstdc++-v3/libsupc++/new_op.cc::56 in _Znwm()
../../gcc-4.8.2/libstdc++-v3/libsupc++/new_opv.cc::32 in _Znam()
utility/arrays.H::106 in setArraySize<char, long unsigned int>()
utility/arrays.H::145 in resizeArray<char, long unsigned int>()
stores/ovStoreFile.C::365 in _ZN6ovFile10readBufferEv()
stores/ovStoreFile.C::391 in _ZN6ovFile11readOverlapEP9ovOverlap()
stores/ovStoreBucketizer.C::238 in main()
(null)::0 in (null)()
(null)::0 in (null)()
scripts/1-bucketize.sh: line 116: 69179 Aborted                 (core dumped) $bin/ovStoreBucketizer -O ./Spu.ovlStore.BUILDING -S ../Spu.seqStore -C ./Spu.ovlStore.config -f -b $jobid

-----------

It does seem to be a memory problem but I am not sure how much memory is needed! Here is my question:

Why these jobs require a lot more memory than other similar jobs? Are not buckets similar in size?


Many thanks.

**Comment by skoren** [comment]
This is actually a disk corruption issue not a memory problem, the allocation is based on the size specified in the file which is bogus causing a huge allocation that can't be satisfied.

Look for the bad outputs by running all failing jobs as you did above. When they report something like:
```
Bucketizing input    3 out of   15 - '1-overlapper/001/000304.ovb'
terminate called after throwing an instance of 'std::bad_alloc'
```
That means file ```1-overlapper/001/000304.ovb`` is bad. Remove any files in the 1-overlapper/results matching those names (e.g. ```1-overlapper/001/000304.*``` in this case). Then, manually run ```sh mhap.sh 304``` (and whatever else you need) in 1-overlapper. Once all those have completed, you can re-try one of the failing bucketizing jobs.

**Comment by Malabady** [comment]
Thank you, Sergey! This resolved the problem. Best regards! Magdy
