### ISSUE TITLE
Limit canu at a certain node and partition using gripOptions

### ISSUE THREAD

**Issue by Tdanis** [marbl/canu#1486]
Hi, I have a quick question. So, I want to implement canu for a genome assembly and my question is how to 'restrict' canu at a certain partition and of course at a certain node.
canu -assembly -p canu_assembly gridOptions="--partition <name> --nodes(integer)" genomeSize=(number)g ...
Are there any options to limit canu, in order to do not occupy all the partition?
For example I want so set partition batch and I want 2 nodes for canu, not all the possible resources. Could you show me the options, please?
thank you

**Comment by skoren** [comment]
You've got the right canu option in gridOptions, the rest is dependent on your cluster. On slurm you can specify ```gridOptions="--partition=batch"``` which will be passed through to every Canu grid request. You could limit to nodes as well (though isn't this redundant given you're already limited to a partition which restricts your nodes)? 

As for the number of nodes, you can't easily limit the number of nodes but you can limit the number of jobs Canu runs at a time. See the FAQ: https://canu.readthedocs.io/en/latest/faq.html#how-do-i-run-canu-on-my-slurm-sge-pbs-lsf-torque-system which has an example for slurm, adding ``` gridEngineArrayOption="-a ARRAY_JOBS%2"``` (assuming you're using canu 1.8 release) will have at most two jobs running at a time.
