### ISSUE TITLE
CANU-correct subreads individually VS batch

### ISSUE THREAD

**Issue by lguzmanz** [marbl/canu#149]
This is a question rather than an issue: 

When my Pacbio sequencing was done I ended up with 18 subreads that each contained xxxx number of sequences (6,431,149 sequences in total for all 18 subreads). Due to particular reasons of having an allocation at a super computer I was having troubles running the Canu command that encompasses all three stages: correct, trim, assemble. So what I decided to do was individually execute the Canu-correct command on each of the 18 subreads. So now I have a list of 18 subreads that have been corrected. My questions is would there be a difference if I would have executed the Canu-correct command on one single file that was a concatenation of all 18 subreads? I ask because I am going to do some downstream analysis with the corrected reads and want to make sure that I am doing this right. Thank you!

**Comment by brianwalenz** [comment]
Yes, huge differences.  The way you've run it used only 5.56% (1/18) of the available evidence to correct reads.  I'd be surprised if you got any decent corrected reads back.

You have 18 runs, not 18 subreads.  A subread is just a portion of a read.

http://files.pacb.com/software/smrtanalysis/2.2.0/doc/smrtportal/help/!SSL!/Webhelp/Portal_PacBio_Glossary.htm

**Comment by lguzmanz** [comment]
Thank you for your help! I will go back and re-correct all of the 18 runs together.

**Comment by brianwalenz** [comment]
Yay!  Good answer!

Use the 1.3 release (expected Monday), or update to the github latest before you start.
