### ISSUE TITLE
massive amount of data lost after correction

### ISSUE THREAD

**Issue by dcastaneda5** [marbl/canu#1490]
Hi! 

I am new to Canu and so far I like it! I am currently running some sequencing nanopore data on it by first aligning my filtered/trimmed/demultiplexed reads to a reference by using Minimap2. Then, I run canu to correct my DNA reads using the following command:

`canu -correct -p sample01 -d sample01 genomeSize=1k nanopore-raw /home/dcmogollon/output/sample01.out.fasta`

After that I realign the fasta corrected output using the same procedure as before (Minimap2) and the same references, I can notice that a lot of my data is missing, for instance:

msp2 alignment raw file:                               msp2 alignment canu corrected file:
number of reads: 41,802                               number of reads: 335
mismatch average: 10%                                 mismatch: 8.1%

I was wondering what could be the reason behind this? In both cases I trimmed the adapters of my data, I demultiplexed it, and I ran a filter to get rid of data with a quality less than 9. Also, in this case the size of my genes is 800 bp (I couldn't run 0.8kb, canu wouldn't let me). Is there anything I am doing wrong in here? 

Thanks for the help!

**Comment by skoren** [comment]
By default, only the longest 40x of data is going to be corrected (see the FAQ). This is probably why you end up with so few reads. If you want more, set corOutCoverage to something high, like 10000 or all.

**Comment by dcastaneda5** [comment]
Hi ! Thanks for your fast reply! I just noticed that you replied a while ago and for some reason I did not get the notification. I just ran it with the recommendation you gave me, setting corOutCoverage=100000 , however I am still getting the same number of low reads... Do you know what approach could I get in here to avoid losing so many reads?

Thanks !

**Comment by skoren** [comment]
Are you looking at all reads before correction or only those >1kb? Canu discards all reads shorter than this by default. Post the full output of the canu run (or the report file it generates), that should have more details on where the reads went.

**Comment by skoren** [comment]
Any updates?

**Comment by skoren** [comment]
Idle, no response. Using sensitive parameters/output coverage (```corOutCoverage=10000 corMhapSensitivity=normal```) would likely get more reads (although none <1kb).
