### ISSUE TITLE
Creating overlap store correction

### ISSUE THREAD

**Issue by MartinLaforest** [marbl/canu#1491]
Hello,

Sorry for the newbie question. I love CANU but I'm running into problems. The plant genome I'm assembling is approximately 1.4 gb large. I am running CANU on a SGE cluster with several nodes with 80 cores and 1tb ram. 

The problem is at this step: 

```
-- Creating overlap store correction/Ass4.ovlStore using:
--   1811 buckets
--   67718 slices
--        using at most 2 GB memory each
```
The software will launch many instances that eventually fills one nodes ram and then this node freezes (swapping heavily I suppose... the server is in a remote location). 

So my question is : is there a way to limit the number of ovB_*** tasks per node?

Here is the command used:
```
#!/bin/bash
#$ -S /bin/bash
#$ -N CANU
#$ -cwd
#$ -pe orte 8
JAVA=/path/to/java
canu-1.8/Linux-amd64/bin/canu \
-java=$JAVA \
-p Ass4 \
-d CANU/ \
genomesize=1400m \
correctedErrorRate=0.144 \
minReadLength=500 \
gridEngineMemoryOption="-l mem_free=MEMORY" \
corMhapSensitivity=high \
gridOptions="-S /bin/bash" \
ovsMemory=1 \
ovsThreads=4 \
maxThreads=16 \
maxMemory=32G \
-nanopore-raw nanoporedata
```
Thank you

**Comment by skoren** [comment]
I don't think the memory on the nodes is the issue, by limiting ovsMemory you've created a lot of slices (68k is way too many) so the machines are probably completely I/O bound trying to open so many files in parallel. Instead, remove your ```Ass4.ovlStore.BUILDING``` folder and any ```Ass4.ovlStore.config*``` files, set ovsMemory=32 and ovbMemory=32 in your script and try again and report back how it runs.

**Comment by MartinLaforest** [comment]
Great! 
Thank you so much.
Will try and report back.

**Comment by MartinLaforest** [comment]
This attempt has failed and I have 3 unresponsive servers this morning... 

I am in contact with the people managing the cluster to see what happened.

**Comment by MartinLaforest** [comment]
There are much fewer buckets now: 

-- Creating overlap store correction/AMBEL_Ass4.ovlStore using:
--   1591 buckets
--   1591 slices
--        using at most 33 GB memory each
-- Finished stage 'cor-overlapStoreConfigure', reset canuIteration.

Here is my command:

#!/bin/bash
#$ -S /bin/bash
#$ -N CANU
#$ -cwd
#$ -pe smp 8
JAVA=/path/to/java
/home/AAFC-AAC/martinsa/Tools/canu-1.8/Linux-amd64/bin/canu \
-java=$JAVA \
-p Ass4 \
-d CANU/ \
genomesize=1400m \
correctedErrorRate=0.144 \
minReadLength=500 \
gridEngineThreadsOption="-pe smp THREADS" \
gridEngineMemoryOption="-l mem_free=MEMORY" \
corMhapSensitivity=high \
gridOptions="-S /bin/bash -q all.q" \
ovsMemory=32 \
ovbMemory=32 \
maxThreads=16 \
-nanopore-raw ...

CANU sends jobs to the cluster (single core) even though memory seems to be full...

Am I doing something wrong?

**Comment by MartinLaforest** [comment]
Added : 

ovsThreads=4 
ovbThreads=4 

So far so good....

**Comment by skoren** [comment]
I'm not sure what you mean by "CANU sends jobs to the cluster (single core) even though memory seems to be full...". Canu doesn't schedule any jobs, it submits them all to your scheduler with the request of -l mem_free=32g. Even though all of them are submitted at once, they don't all run until the scheduler decides to dispatch them. If it's running more on a node than the node has memory available, then the mem_free option is not working properly. Do you see more jobs that node memory being launched (e.g. 5 32g jobs in a machine with 128g of memory?)

**Comment by skoren** [comment]
Idle
