### ISSUE TITLE
Getting Around Walltime Restrictions

### ISSUE THREAD

**Issue by jasongallant** [marbl/canu#1493]
Hello,

Our cluster is set up with a buy-in structure such that our shortest wait times are for jobs less than 4 hours.  It is unclear to me from the code whether MHAP jobs that time out have to completely start over, or if progress during that 4-hour window is saved?  Hopefully this is easy to answer!

**Comment by skoren** [comment]
Jobs are atomic, so if they fail no progress will get saved. 

The best option would be to make more small jobs in this case to try to fit into the time limit (reduce the memory for mhap jobs). If your nodes have local scratch disk you can request also see the stageDirectory option (https://canu.readthedocs.io/en/latest/parameter-reference.html?highlight=stageDirectory#file-staging) which will also speed up this run as the most I/O intensive part will avoid network writes.
