### ISSUE TITLE
Failed with exit code 136. (rc=34816) ERROR CODE

### ISSUE THREAD

**Issue by ioer0417** [marbl/canu#1494]
I tried this command.

$ ~/util/canu-1.7.1/Linux-amd64/bin/canu -trim -p Ftest -d Fcanutest java=~util/jre1.8.0_161/bin/java ovsMethod=sequential useGrid=false stopOnReadQuality=false genomeSize=40m -pacbio-corrected ~/Fcanutest/Ftest.correctedReads.fasta.gz

And, This ERROR CODE.  What problem?

Failed with exit code 136. (rc=34816) 

canu 1.7.1
Don'y panic, but a  mostly harmless error occurred and Canu stopped.
Try restarting. If that doesn't work,. ask for help

failed partition for overlapper.

I tried 6 times.

**Comment by skoren** [comment]
This code has changed significantly since 1.7.1 and so I'd rather not try to debug the old version. Can you update to 1.8 (or the 1.9 branch if you're comfortable compiling code yourself) and re-launch this assembly from scratch? Post any errors it hits with the updated version.

**Comment by skoren** [comment]
Any update on this?

**Comment by ioer0417** [comment]
> This code has changed significantly since 1.7.1 and so I'd rather not try to debug the old version. Can you update to 1.8 (or the 1.9 branch if you're comfortable compiling code yourself) and re-launch this assembly from scratch? Post any errors it hits with the updated version.



Thanks to your answer!

It was fixed after the update to canu ver.1.8.

BUT, I keep getting a prompt to enter the stopOnLowCoverage = 10 command.

If you add it, it will run, but if you do not, it will not run. So I added it and the result was not good. What should I do?

**Comment by skoren** [comment]
stopOnLowCoverage is essentially the replacement for stopOnReadQuality so since you had to set that to false you have to disable the stop on low coverage as well. This means you don't have enough coverage to assemble the data, either from the raw data or after correction. You can read the FAQ for some parameter suggestions you can tweak (I'd start with ```corMinCoverage=0 corMhapSensitivity=high correctedErrorRate=0.105```) and run the full assembly from scratch from raw reads.
