### ISSUE TITLE
Cpu time statistics

### ISSUE THREAD

**Issue by SixPlusSeven** [marbl/canu#1495]
Now I want to count the cpu time used by canu, but sge can't do this. Is there any convenient way?

Thanks！
Alex

**Comment by skoren** [comment]
SGE can report usage of jobs, see the qacct command. Canu logs contain the IDs of all the jobs it submitted to the grid during the run so you'd just have to add up the total wall time or cpu time used by them to get what you're after.

**Comment by brianwalenz** [comment]
See https://github.com/marbl/canu/blob/master/src/pipelines/canu-time.pl for a perl program that might work.  It parses the outputs in canu-scripts/ to find job IDs, the queries SGE to get the time.  It might not work; I don't remember if I needed to change canu to make parsing easier.
