### ISSUE TITLE
ERROR: Failed to determine the sequencing technology of the reads.

### ISSUE THREAD

**Issue by shiwani21** [marbl/canu#1496]
Hi, I am a new canu user, trying to run assembly for nanopore data (bacterial genome)
my canu version is: 
`Canu snapshot v1.8 +358 changes (r9568 c478f9e441e76326ea1435adedf7f01997bbd32f)    
`Ran this command:  
canu -trim-assemble -p canuassmble -d ./test_canu/ genomeSize=8.5m -corrected -nanopore ./data_again/ssgG1/20190819_1825_MN30506_FAK92592_810fd581/fastq_pass/*.fastq
It gives me error:

```
-- In 'canuassmble.seqStore', found NO READS AT ALL reads:
--

ABORT:
ABORT: Canu snapshot v1.8 +358 changes (r9568 c478f9e441e76326ea1435adedf7f01997bbd32f)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   ERROR: Failed to determine the sequencing technology of the reads.
ABORT:
```

**Comment by skoren** [comment]
You are not using Canu 1.8 but the unstable tip, download the 1.8 release for your system from the releases page instead and run that from scratch.

**Comment by brianwalenz** [comment]
Can you provide more context (logging) for this error?  What was used to correct the reads?

**Comment by shiwani21** [comment]
Thank you @skoren, I installed 1.8 version from releases and it worked. 
@brianwalenz I wasn't doing correction, instead directly running -assembly option earlier, also was trying with -correct but nothing was working (program was not detecting my input files), so asked for help. Now it's working. Thank you all.
