### ISSUE TITLE
I am getting extra contigs than the required!!!

### ISSUE THREAD

**Issue by sneupane01** [marbl/canu#1498]
Hi,
I am using canu for the bacterial genome assembly.
Expected genome size is 1.5m. I got this result using following parameters:
genomeSize=1.5m correctedErrorRate=0.015 ovlMerThreshold=500 corOutCoverage=100 batOptions="-eg 0.01 -eM 0.01 -dg 6 -db 6 -dr 1 -ca 50 -cp 5"​

```
Found, in version 2, after consensus generation:
--   contigs:      8 sequences, total length 1683575 bp (including 0 repeats of total length 0 bp).
--   bubbles:      0 sequences, total length 0 bp.
--   unassembled:  6953 sequences, total length 38219821 bp.
--
-- Contig sizes based on genome size 1.5mbp:
--
--            NG (bp)  LG (contigs)    sum (bp)
--         ----------  ------------  ----------
--     10     1452149             1     1452149
--     20     1452149             1     1452149
--     30     1452149             1     1452149
--     40     1452149             1     1452149
--     50     1452149             1     1452149
--     60     1452149             1     1452149
--     70     1452149             1     1452149
--     80     1452149             1     1452149
--     90     1452149             1     1452149
--    100       84182             2     1536331
--    110       19669             6     1658319
```
I got expected size of 1.45Mb but I am not why I am getting other contigs. I tried changing many parameters and it is not helping. I would appreciate suggesting the various parameters to be changed.
Thank You

**Comment by brianwalenz** [comment]
This is quite normal and nothing to be too worried about.  It could be a small bit of contamination, adapter, plasmids or even unexpected variation in the sample.  Time for analysis!

**Comment by sneupane01** [comment]
Thank you for the quick response. Actually I did blastn and found one contig (24kb) as a contamination (host contig). So what do you suggest? Proceed with just the largest contig or include other contigs after removing the contamination.

**Comment by skoren** [comment]
The contigs represent other sequence present in your reads. Some may be plasmids and some may be control sequence if you included any during library preparation. Once you remove the obvious contamination (control, host, etc) then the rest should be included in any analysis.
