### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by drose13** [marbl/canu#150]
Hi,

I am trying to compile canu on a CentOS 5.5. and get a compilation error, see attachment. Do you have any advise for me? Thanks in advance.

"overlapInCore/liboverlap/prefixEditDistance-matchLimitGenerate.C:103: internal compiler error: in rewrite_stmt, at tree-into-ssa.c:1041"

[canu_err.txt](https://github.com/marbl/canu/files/297729/canu_err.txt)

**Comment by skoren** [comment]
This looks like an internal compiler error, not a syntax error in Canu. Mostly likely you need to update your compiler. What goes g++ --version report? Canu requires at least 4.5 and we typically use 4.8 to build releases. You can also try the pre-compiled binaries for Linux.

**Comment by drose13** [comment]
You saved my day, thanks! I just followed the README.md at the github landing page and missed the release section. The pre-compiled version works fine. Thanks again.
