### ISSUE TITLE
Overlapper fails in two unitig sub-jobs

### ISSUE THREAD

**Issue by wgallin** [marbl/canu#1502]
I am running an assembly that has made it to the unitigging/overlapping step but at this stage two (the same two and only two) of the overlapping jobs have failed several times with the following tail from the overlapper .out file:
```
Initializing 8 work areas.
Build_Hash_Index from 5449247 to 5465517

Found 9500 reads with length 160009927 to load; 6771 skipped by being too short; 0 skipped per library restriction
HASH LOADING STOPPED: curID         5465517 out of      5465517
HASH LOADING STOPPED: length      160009927 out of    160009927 max.
HASH LOADING STOPPED: entries      99999078 out of    140928614 max (load 56.77).

Read 418549 kmers to mark to skip


Range: 1-4628228.  Store has 5608638 reads.
Chunk: 72317 reads/thread -- (G.endRefID=4628228 - G.bgnRefID=1) / G.Num_PThreads=8 / 8

Starting 1-4628228 with 72317 per thread

Thread 00 processes reads 1-72317
Thread 03 processes reads 216952-289268
Thread 01 processes reads 72318-144634
Thread 07 processes reads 506220-578536
Thread 02 processes reads 144635-216951
Thread 05 processes reads 361586-433902
Thread 04 processes reads 289269-361585
Thread 06 processes reads 433903-506219
Thread 00 writes    reads 1-72317 (17544 overlaps 17544/418361/0 kmer hits with/without overlap/skipped)
Thread 00 processes reads 578537-650853
Thread 01 writes    reads 72318-144634 (19956 overlaps 19956/538630/0 kmer hits with/without overlap/skipped)
Thread 01 processes reads 650854-723170
Thread 04 writes    reads 289269-361585 (22761 overlaps 22761/595930/0 kmer hits with/without overlap/skipped)
writeToFile()-- After writing 1 out of 1 'ovFile::writeBuffer::bl' objects (8 bytes each): Cannot allocate memory

```

This is running as a grid job using SLURM on a Linux system and the original invoking SLURM script is:

```
........
# Load modules: 

module load nixpkgs/16.09 gcc/5.4.0 canu/1.8

# Run the code:

echo "Starting run at: `date`"

cd $SLURM_SUBMIT_DIR

canu -p 190708_PpenNano_All useGrid=true gridOptions="--time=5:00:00" gridOptionsutgovl="--time=35:00:00" gridOptionsobtovl="--time=20:00:00" gridOptionsovs="--mem=8G"  genomeSize=380m -d /scratch/wgallin/190902_CANU_Nanopore_Only -nanopore-raw /scratch/wgallin/190902_CANU_Nanopore_Only/190902_Combined_Nanopore_Data.fastq

echo "Program finished with exit code $? at: `date`"

```
I have rerun the job two times, with increasing memory for the overlapper, but the failure is the same.
The overlapping in the correction step ran without failing, so I am at a loss as to why the overlapping in the unitigging step would fail.

Any pointers at what may be wrong are appreciated.

**Comment by skoren** [comment]
The job is reporting it couldn't allocate memory so memory seems like the likeliest issue. How much memory did the job originally request and how much did you increase it to? Try doubling or tripling it (assuming you have that much memory) and see if it completes.

**Comment by wgallin** [comment]
The default memory allocation to each job was 1Gb, I increased it to 10Gb and it failed at the same point, on only those two jobs.
Since the correction and consensus parts of the job went through without faiing on any of the overlapping processes, but two of 173 overlapping jobs are failing on the unitigging part of the job, same two overlapping jobs in the same way even when memory allocation is increased 10-fold I am wondering what possibilities I can investigate.
Could there be an intermediate pice of data that is just too large? That seems unlikely to me.

**Comment by wgallin** [comment]
Sorry, reset gridOptionsovs="--mem=8G", so an 8-fold increase in allocated memory.

**Comment by skoren** [comment]
Typically the memory in this step from canu is requested per core, was it really only 1gb or per core? What was the original Canu submit command it used (you can post the contents of ```overlap.jobSubmit*sh```, it still has the canu parameters).

I'd suggest running one of the failing jobs in an interactive session reserving 16 or 32gb of memory and monitor memory usage to see how much it uses and if it runs all the way to the end.

**Comment by wgallin** [comment]
Sergey,

	I checked and it looks to me that the memory request in this step was treated as a per-task, not a per-core request.

The overlap.jobSubmit-02.sh  is:

#!/bin/sh

sbatch \
  --mem-per-cpu=1g --cpus-per-task=8 --time=5:00:00 --time=35:00:00 -o overlap.%A_%a.out \
  -D `pwd` -J "utgovl_190708_PpenNano_All" \
  -a 148-148 \
  ./overlap.sh 0 \
> ./overlap.jobSubmit-02.out 2>&1


and the initiating script to the grid job was:



canu -p 190708_PpenNano_All useGrid=true gridOptions="--time=5:00:00" gridOptionsutgovl="--time=35:00:00" gridOptionsobtovl="--time=20:00:00" gridOptionsovs="—mem=8G"  genomeSize=380m -d /scratch/wgallin/190902_CANU_Nanopore_Only -nanopore-raw /scratch/wgallin/190902_CANU_Nanopore_Only/190902_Combined_Nanopore_Data.fastq


I am rerunning the grid job request with gridOptionsovs="—mem=32G”

So I guess I’ll see if that was the issue.

Warren

**Comment by skoren** [comment]
Right, so the initial request was for
```
--mem-per-cpu=1g --cpus-per-task=8
```
or 8gb, when you added ```gridOptionsovs="--mem=8G"``` you essentially requested the same memory as before in total not 8-fold higher since --mem is not multiplied by cores (while --mem-per-cpu is). I expect ```gridOptionsovs="—mem=32G”``` will work as would ```gridOptionsovs="—mem-per-cpu=4G”```

**Comment by wgallin** [comment]
Grid Submission command is now:
```
canu -p 190708_PpenNano_All useGrid=true gridOptions="--time=5:00:00" gridOptionsutgovl="--time=35:00:00 --mem-per-cpu=4g" gridOptionsobtovl="--time=20:00:00"  genomeSize=380m -d /scratch/wgallin/190902_CANU_Nanopore_Only -nanopore-raw /scratch/wgallin/190902_CANU_Nanopore_Only/190902_Combined_Nanopore_Data.fastq

```



Contents of the job submission file for this task is now:

```
#!/bin/sh

sbatch \
  --mem-per-cpu=1g --cpus-per-task=8 --time=5:00:00 --time=35:00:00 --mem-per-cpu=4g -o overlap.%A_%a.out \
  -D `pwd` -J "utgovl_190708_PpenNano_All" \
  -a 148-148 \
  ./overlap.sh 0 \
> ./overlap.jobSubmit-01.out 2>&1
```

And the job still fails, in essentially the same way at the same point:

```
Running job 148 based on SLURM_ARRAY_TASK_ID=148 and offset=0.

STRING_NUM_BITS          31
OFFSET_BITS              31
STRING_NUM_MASK          2147483647
OFFSET_MASK              2147483647
MAX_STRING_NUM           2147483647

Hash_Mask_Bits           23
bgnHashID                5449247
bgnHashID                5465517
Max_Hash_Data_Len        160009927
Max_Hash_Load            0.800000
Kmer Length              22
Min Overlap Length       500
Max Error Rate           0.120000
Min Kmer Matches         0

Num_PThreads             8

sizeof(Hash_Bucket_t)    216
sizeof(Check_Vector_t)   4
sizeof(Hash_Frag_Info_t) 4

HASH_TABLE_SIZE          8388608

hash table size:         1728 MB
hash check array         32 MB
string info              0 MB
string start             0 MB

Initializing 8 work areas.
Build_Hash_Index from 5449247 to 5465517

Found 9500 reads with length 160009927 to load; 6771 skipped by being too short; 0 skipped per library restriction
HASH LOADING STOPPED: curID         5465517 out of      5465517
HASH LOADING STOPPED: length      160009927 out of    160009927 max.
HASH LOADING STOPPED: entries      99999078 out of    140928614 max (load 56.77).

Read 418549 kmers to mark to skip


Range: 1-4628228.  Store has 5608638 reads.
Chunk: 72317 reads/thread -- (G.endRefID=4628228 - G.bgnRefID=1) / G.Num_PThreads=8 / 8

Starting 1-4628228 with 72317 per thread

Thread 00 processes reads 1-72317
Thread 01 processes reads 72318-144634
Thread 03 processes reads 216952-289268
Thread 06 processes reads 433903-506219
Thread 04 processes reads 289269-361585
Thread 05 processes reads 361586-433902
Thread 02 processes reads 144635-216951
Thread 07 processes reads 506220-578536
Thread 00 writes    reads 1-72317 (17544 overlaps 17544/418361/0 kmer hits with/without overlap/skipped)
Thread 00 processes reads 578537-650853
Thread 01 writes    reads 72318-144634 (19956 overlaps 19956/538630/0 kmer hits with/without overlap/skipped)
Thread 01 processes reads 650854-723170
Thread 04 writes    reads 289269-361585 (22761 overlaps 22761/595930/0 kmer hits with/without overlap/skipped)
writeToFile()-- After writing 1 out of 1 'ovFile::writeBuffer::bl' objects (8 bytes each): Cannot allocate memory

```

**Comment by skoren** [comment]
It's possible it's not actually memory but something else like running out of file descriptors. Can you get an interactive session with 64gb of memory and monitor the process for memory to see what it is using when it fails?

**Comment by skoren** [comment]
Any updates?

**Comment by skoren** [comment]
Idle.
