### ISSUE TITLE
Segmentation Fault on 1.7.1

### ISSUE THREAD

**Issue by woodoo46** [marbl/canu#1505]
Hi Canu Developers,

I am using Canu 1.71., and during bat stage (unitigging phase), I had the following error message:

Failed with 'Segmentation fault'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::97 in _Z17AS_UTL_catchCrashiP7siginfoPv()
(null)::0 in (null)()
bogart/AS_BAT_MergeOrphans.C::758 in _Z12mergeOrphansR9TigVectord()
bogart/bogart.C::474 in main()
(null)::0 in (null)()
(null)::0 in (null)()

Let me know if you need any further information.

Thanks.

**Comment by skoren** [comment]
There's a lot of changes since 1.7.1 including bugfixes in unitigging so you should try updating to 1.8 or the 1.9 branch and re-running. You'll have to restart from the trimmed reads using the ```canu -assemble``` option.

**Comment by woodoo46** [comment]
If there is any change between 1.7.1 and 1.9 in the first two stages, correction and trimming?

**Comment by skoren** [comment]
Yes there have been but you can still run the trimmed reads from the older version, the assembly should end up pretty similar to what you'd get running from scratch.
