### ISSUE TITLE
Failed with exit code 1.  (rc=256)

### ISSUE THREAD

**Issue by gauravarai** [marbl/canu#1507]
```
-- Finished on Wed Oct  9 13:21:16 2019 (lickety-split) with 225.025 GB free disk space
----------------------------------------

ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:

ABORT:
ABORT: Canu snapshot v1.8 +296 changes (r9506 56d8be4dd6c05d2b50822a920c582c2eb7f6edd3)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to load unitig consensus into utgStore.
ABORT:
ABORT: Disk space available:  225.025 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (unitigging/5-consensus/utgcns.files.utgStoreLoad.err):
ABORT:
ABORT:   usage: /home/ubuntu1/canu/Linux-amd64/bin/tgStoreLoad -S <seqStore> -T <tigStore> <v> [input.cns]
ABORT:   
ABORT:     -S <seqStore>         Path to the sequence store
ABORT:     -T <tigStore> <v>     Path to the tigStore and version to add tigs to
ABORT:   
ABORT:     -L <file-of-files>    Load the tig(s) from files listed in 'file-of-files'
ABORT:                           (WARNING: program will succeed if this file is empty)
ABORT:   
ABORT:     -n                    Don't load into store, just report what would have happened
ABORT:   
ABORT:     -dump                 Dump the cns files as ASCII, don't load into store
ABORT:     -test                 Test the cns files for various errors, don't load into store
ABORT:   
ABORT:     The primary operation is to replace tigs in the store with ones in a set of input files.
ABORT:     The input files can be either supplied directly on the command line or listed in
ABORT:     a text file (-L).
ABORT:   
ABORT:     A new store is created if one doesn't exist, otherwise, whatever tigs are there are
ABORT:     replaced with those in the -R file.  If version 'v' doesn't exist, it is created.
ABORT:   
ABORT:     Even if -n is supplied, a new store is created if one doesn't exist.
ABORT:   
ABORT:     To add a new tig, give it a tig id of -1.  New tigs must be added to the latest version.
ABORT:     To delete a tig, remove all children, and set the number of them to zero.
ABORT:   
ABORT:   ERROR:  no input tig files supplied on command line or via -L option.
```
Further I went into unitigging/5-consensus/utgcns.files.utgStoreLoad.err and got this

```
usage: /home/ubuntu1/canu/Linux-amd64/bin/tgStoreLoad -S <seqStore> -T <tigStore> <v> [input.cns]

  -S <seqStore>         Path to the sequence store
  -T <tigStore> <v>     Path to the tigStore and version to add tigs to

  -L <file-of-files>    Load the tig(s) from files listed in 'file-of-files'
                        (WARNING: program will succeed if this file is empty)

  -n                    Don't load into store, just report what would have happened

  -dump                 Dump the cns files as ASCII, don't load into store
  -test                 Test the cns files for various errors, don't load into store

  The primary operation is to replace tigs in the store with ones in a set of input files.
  The input files can be either supplied directly on the command line or listed in
  a text file (-L).

  A new store is created if one doesn't exist, otherwise, whatever tigs are there are
  replaced with those in the -R file.  If version 'v' doesn't exist, it is created.

  Even if -n is supplied, a new store is created if one doesn't exist.

  To add a new tig, give it a tig id of -1.  New tigs must be added to the latest version.
  To delete a tig, remove all children, and set the number of them to zero.

ERROR:  no input tig files supplied on command line or via -L option.
```

canu parameter used was as follows-
```canu -p canu -d ./gom_graphmap_analysis/canu_gom_graphmap/AF027657_Choristoneura_fumiferana_entomopoxvirus_canu genomeSize=0.1m -nanopore-raw ./gom_graphmap_analysis/gom_reads_complete_genome_seq/AF027657_Choristoneura_fumiferana_entomopoxvirus.fasta useGrid=false minReadLength=200 minOverlapLength=100 stopOnLowCoverage=0```

I'm kind of noob in coding and bioinformatics. please help

**Comment by skoren** [comment]
The error sounds like there are no unitigs and most likely no assembled contigs either, I would guess you have very low coverage and very short reads (given the parameters you're using). Can you post the full report file produced by the assembly? 

See issue #1396 for a similar error. You can dump the "assembly" using the same command listed there but I expect it's not very good. You can also re-run the assembly following the FAQ and turning down the contig filter (```contigFilter="2 0 1.0 0.5 0"```).

**Comment by gauravarai** [comment]
Sir, unfortunately I couldn't figure out more from the issue #1396 because of my less understanding about command line tho I tried contig filter as stated by you but outcome is the same Failed with exit code 1.  (rc=256).
I would like to put more insight into the issue..
Hardly a month before I ran canu with [this](https://drive.google.com/open?id=1HfiXqWBBfiZCLW-CoFq8PKu347C8kMr9) read data using [this](https://drive.google.com/open?id=16v7ZhmsIimsCWtVSBmj73QNqvIfEn95i) canu parameter, which successfully ran and produced [this](https://drive.google.com/open?id=1QBmaPqvTyIhhnwFiNp7JjAAxsBqmSW4s) assembly result. now when i trying re-assembly with same read data I have to add redMemory=12 oeaMemory=6 into parameter to run but it too results into "Failed with exit code 1.  (rc=256)" error. The complete data of failed assembly is [here
](https://drive.google.com/open?id=1QBmaPqvTyIhhnwFiNp7JjAAxsBqmSW4s). 
I hope this will help you to understand the problem.
thanks

**Comment by skoren** [comment]
I ran the following command:
```
anu -p asm -d bug18 useGrid=false genomeSize=1m -nanopore-raw gom_Cyanobacteria_phage_AS-1_335924_seq.fasta useGrid=false minReadLength=200 minOverlapLength=100 stopOnLowCoverage=0
```

using both the latest on the 1.9 branch and the 1.8 release. In both cases, there is no error and I get an assembly at the end. Here are the stats for those assemblies:
1.8:
```
>tig00000001 len=1404 reads=25 covStat=-16.60 gappedBases=no class=contig suggestRepeat=no suggestCircular=no
```

1.9:
```
tig00000017 len=1112 reads=29 class=contig suggestRepeat=no suggestCircular=no
tig00000018 len=1161 reads=1 class=contig suggestRepeat=no suggestCircular=no
```

I think you must be using an intermediate version between the two not a release. I'd recommend sticking with 1.8 unless you have encountered specific errors with it in which case you can use the 1.9 branch.

**Comment by gauravarai** [comment]
Yes sir, 
I agree, I have messed up with versions somewhere in the middle.  yesterday I removed all versions and tried with 1.8. It worked well. Issue solved.
Thank you very much for your patient.
