### ISSUE TITLE
Overlap error adjustment jobs failed

### ISSUE THREAD

**Issue by Gostwander** [marbl/canu#1509]
The assembly job has been running for like 5 days for a 65Mb genome, now the can.out shows that overlap error adjustment jobs failed:
```
-- BEGIN ASSEMBLY
--
--
-- Overlap error adjustment jobs failed, tried 2 times, giving up.
--   job 00013.oea FAILED.
--   job 00020.oea FAILED.
--   job 00022.oea FAILED.
--   job 00030.oea FAILED.
--   job 00031.oea FAILED.
--   job 00032.oea FAILED.
--   job 00034.oea FAILED.
--   job 00041.oea FAILED.
--   job 00044.oea FAILED.
--   job 00053.oea FAILED.
--   job 00072.oea FAILED.
--   job 00075.oea FAILED.
--   job 00102.oea FAILED.
--   job 00103.oea FAILED.
--   job 00114.oea FAILED.
--   job 00117.oea FAILED.
--   job 00119.oea FAILED.
--   job 00129.oea FAILED.
--   job 00134.oea FAILED.
--   job 00135.oea FAILED.
--   job 00141.oea FAILED.
--   job 00142.oea FAILED.
--   job 00152.oea FAILED.
--   job 00153.oea FAILED.
--   job 00155.oea FAILED.
--   job 00181.oea FAILED.
--   job 00192.oea FAILED.
--   job 00200.oea FAILED.
--   job 00202.oea FAILED.
--   job 00203.oea FAILED.
--   job 00206.oea FAILED.
--   job 00207.oea FAILED.
--   job 00211.oea FAILED.
--   job 00213.oea FAILED.
--   job 00215.oea FAILED.
--   job 00219.oea FAILED.
--   job 00222.oea FAILED.
ABORT:
ABORT: Canu branch v1.9 +314 changes (r9524 b6c7bd2afc76b69e88cf781294e5d82246c68959)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.

AND this is the output from file unitizing/3-overlapErrorAdjustment/oea.42291544_148.out
Found perl:
   /apps/perl/perls/perl-5.16.0/bin/perl
   This is perl 5, version 16, subversion 0 (v5.16.0) built for x86_64-linux-thread-multi

Found java:
   /apps/java/jdk1.8.0_31/bin/java
   java version "1.8.0_31"

Found canu:
   /apps/canu/1.9/bin/canu
   Canu branch v1.9 +314 changes (r9524 b6c7bd2afc76b69e88cf781294e5d82246c68959)

Running job 148 based on SLURM_ARRAY_TASK_ID=148 and offset=0.
Initializing.
Opening seqStore '../../similis.seqStore'.
Correcting reads 269047 to 270907.
Reading 1531821 corrections from './red.red'.
Correcting 9445912 bases with 701088 indel adjustments.
--Allocate 9 + 5 + 0 MB for bases, adjusts and reads.
Corrected 9446506 bases with 1562 substitutions, 1031 deletions and 1625 insertions.
Loading overlaps.
Read_Olaps()--  Loading 55055433 overlaps from '../similis.ovlStore' for reads 269047 to 270907
--Allocate 1680 MB for overlaps.
Read_Olaps()--  Loaded 55055433 overlaps -- 40746709 normal and 14308724 innie.
Sorting overlaps.
Recomputing overlaps.
--Allocate 8 MB for fseq and rseq.
--Allocate 32 MB for fadj and radj.
--Allocate 16 MB for pedWorkArea_t.
-- Allocate 1 MB for Edit_Array pointers
Recomputing overlaps -         1 -         1 -    413121^M--Allocate 16 MB for edit array work space 0 (positions 0-4092)
Recomputing overlaps -         1 -      1025 -    413121^MRecomputing overlaps -         1 -      2049 -    413121^MRecomputing overlaps -         1 -      3073 -    413121^MRecomputing overlaps -         1 -      4097 -    413121^MRecomputing overlaps -         1 -      5121 -    413121^MRecomputing overlaps -         1 -      6145 -    413121^MRecomputing overlaps -         1 -      7169 -    413121^MRecomputing overlaps -         1 -      8193 -    413121^MRecomputing overlaps -         1 -      9217 -    413121^MRecomputing overlaps -         1 -     10241 -    413121^MRecomputing overlaps -         1 -     11265 -    413121^MRecomputing overlaps -         1 -     12289 -    413121^MRecomputing overlaps -         1 -     13313 -    413121^MRecomputing overlaps -         1 -     14337 -    413121^MRecomputing overlaps -         1 -     15361 -    413121^MRecomputing overlaps -         1 -     16385 -    413121^MRecomputing overlaps -         1 -     17409 -    413121^MRecomputing overlaps -         1 -     18433 -    413121^MRecomputing overlaps -         1 -     19457 -    413121^MRecomputing overlaps -         1 -     20481 -    413121^MRecomputing overlaps -         1 -     21505 -    413121^MRecomputing overlaps -         1 -     22529 -    413121^MRecomputing o
...
--  Release bases, adjusts and reads.
Olaps Fwd 40746709
Olaps Rev 14308724
Total:  55055433
Failed: 3211913 (both)
Failed: 3678662 (either)
Failed: 3678662 (match to end)
Failed: 3211913 (negative length)
rhaFail 2162894 rhaPass 24503094
Sorting overlaps.
Saving corrected error rates to file ./00148.oea.WORKING
--Allocate 105 MB for output error rates.

Bye.
```
I could not figure out the issue from the .out file, thanks

**Comment by skoren** [comment]
What's your canu command, what is the report log from the assembly so far? 

There is no error in that log, 148 is not one of the jobs that failed in your list. Check the output for one of the failed jobs in the list like 152.

**Comment by Gostwander** [comment]
This is my canu command:
canu -assemble -p similis -d assemble-fast gridOptions="--time=168:00:00" genomeSize=65.5m maxMemory=100 maxThreads=50 -nanopore-corrected ./trim-fast/similis.trimmedReads.fasta.gz

This is from oea.42291544_152.out
Failed with 'Aborted'; backtrace (libbacktrace):
utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
overlapErrorAdjustment/correctOverlaps-Redo_Olaps.C::554 in _Z10Redo_OlapsP12coParametersP7sqStore()
overlapErrorAdjustment/correctOverlaps.C::171 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
/tmp/slurmd/job42298831/slurm_script: line 980: 29419 Aborted                 (core dumped) $bin/correctOverlaps -S ../../similis.seqStore -O ../similis.ovlStore -R $minid $maxid -e 0.12 -l 500 -c ./red.red -o ./$jobid.oea.WORKING

**Comment by skoren** [comment]
Can you try updating to the latest code on that branch (git pull should do it), re-compile, and re-run one of the failing jobs to see if they work? If that doesn't work, are you able to share the data for this run?

**Comment by Gostwander** [comment]
I do not think I have permission to update that, but I could share the data, should I just attached the fasta file here?

**Comment by skoren** [comment]
You shouldn't need special permission to update canu, you could get the 1.9 branch and build it yourself from GitHub. 

The FAQ has instructions to send us data. We'd need the seqStore, ovlStore, and the 3-overlapErrorAdjustment folders.

**Comment by Gostwander** [comment]
Done, uploaded all three folders. By the way, I only see canu v1.8, could not find v1.9, sorry to bother you with such simple questions.

**Comment by skoren** [comment]
I don't see any new data on the FTP site, are you sure it was sent? You probably need to tar the folders up before transferring folders.

The latest official release is 1.8, 1.9 is a branch in the repo but not officially released yet. Whoever installed your version of canu pulled that which is not backwards compatible with 1.8 so you can't switch to it in the middle of the assembly. Pull the code from GitHub then run:
```
git clone https://github.com/marbl/canu.git
cd canu
git checkout v1.9
rm -r Linux-amd64
make
```
or you can get the 1.8 release and re-launch the assembly step (```<path to canu1.8>/*/bin/canu -assemble -p similis -d assemble-v18 gridOptions="--time=168:00:00" genomeSize=65.5m maxMemory=100 maxThreads=50 -nanopore-corrected ./trim-fast/similis.trimmedReads.fasta.gz```

**Comment by Gostwander** [comment]
I uploaded 3-overlaperroradjustment and skeqstore, in the process of uploading ovlstre, it might finish this evening, thanks

**Comment by Gostwander** [comment]
Have you received all the files? They should be there now, thanks.

**Comment by skoren** [comment]
Yes, will update once I run locally

**Comment by skoren** [comment]
I was able to run without error using the latest 1.9 from the repo so if you update your code, remove the 3-overlaperroradjustment folder and re-launch Canu, it should run.

However, the read and assemblies don't look very good. The reads don't have a peak in the k-mer histogram and the assembly is not close to the expected genome size. There is also a lot of high-error overlaps. This data may benefit from re-basecalling with a recent nanopore Guppy release if you haven't already or multiple rounds of correction (see FAQ for how to run that).

**Comment by Gostwander** [comment]
Thank you very much. I ran using v1.8, and it worked too. But it only assembled 10% of the genome, is this normal for nanopore data?

**Comment by skoren** [comment]
No, as I said above the data did not seem like the corrected reads were really corrected. You can try my suggestions above to see if it helps.

**Comment by Gostwander** [comment]
Thank you very much, I will try it.

**Comment by skoren** [comment]
Since the original issue is resolved, I'm going to close this. Open a new issue if you hit errors trying to run multiple rounds of correction or still have no assembly w/newer basecallers.
