### ISSUE TITLE
canu failed with 'failed to generate configuration for building overlap store'

### ISSUE THREAD

**Issue by mahulchak** [marbl/canu#151]
Hello,
I am running canu for a Drosophila size genome on a SGE cluster. For some reason that I am unable to figure out, the overlap store building is failing (please see below). I tried setting ovsMemory=512 but still it fails with the same error. Is the store building command somehow failing to partition the jobs? Let me know if you need more information.

Found 3380556174 (3380.56 million) overlaps.
Configuring for 2.00 GB to 8.00 GB memory.
ERROR:  Cannot sort 3380.56 million overlaps using 8.00 GB memory; too few file handles available.
ERROR:    olapsPerBucket 208037454
ERROR:    buckets        17
ERROR:  Increase memory size (in canu, ovsMemory; in ovStoreBuild, -M)

Mahul

**Comment by skoren** [comment]
Have you tried the recommendations from Brian is issue #147?

**Comment by mahulchak** [comment]
Thanks Sergey for the quick response.
I did as Brian had suggested in the other post.
I am using the latest version of canu. I have set ovsMemory=8-256. I
deleted the dmau.ovlStore.BUILDING before restarting the pipeline but it is
still failing. Do I need to start from the beginning after I set
ovsMemory=8-256 ?

**Comment by brianwalenz** [comment]
Can you give the latest code on github a try?  I added a bunch of debugging, and changed the way it picks a memory size slightly.  You need only run the ovStoreBuild command, not the entire canu pipeline.  Usage will be something like:

ovStoreBuild \
  -G *gkpStore -O junk.ovlStore -M 8-256 \
  -config junk.ovlStore/config \
  -L 1-overlapper/ovljob.files

Regardless of success, I'd like to see what it reports to the screen.

You can delete junk.ovlStore when done testing.

**Comment by mahulchak** [comment]
Interestingly it is working now. Thanks a lot Brian. I will run your command and send you the output.

By the way, I noticed a few of things that might interest you . 
1. Canu master script adds a 'g' or a 'm' with the appropriate size to replace 'MEMORY' in "gridEngineMemoryOption=-l mem_size=MEMORY". In our SGE cluster, only numbers are allowed so canu jobs do not run when mem_size=5g is requested (mem_size=5 is fine). I have edited the script in my case so I am not facing any problem but I thought I would bring this to your notice.

2.  Somehow the options "gridOptionscns","gridOptionscormhap", "gridOptionscor" in the spec file are not being used by the script.  Only "gridOptionsExecutive" works.

3. Jobs are often being submitted to the interactive nodes. I tried to specify the ques using the gridOptions* but as I have mentioned in 2. they are not being used by canu.
Mahul

**Comment by colindaven** [comment]
I had a similar issue with building the overlap store (codebase canu 1.3 release). Following recommendations in these two threads (this, and the one mentioned above), I set the ovsMemory to that listed below in the original canu command. The pipeline restarted and is now building or "bucketizing" fine. Server: 512g RAM

ovsMemory=5g-500g
