### ISSUE TITLE
Read count drop at correction / trimming step

### ISSUE THREAD

**Issue by etvedte** [marbl/canu#1511]
I'm running canu v1.8 to assemble some E. coli genomes. The reads were sequenced on PacBio RS II.

Initially, I ran canu with default parameters, i.e. 

canu -p ecoli -d /assembly/output/dir/ genomeSize=4.6m gridEngineThreadsOption="-pe thread THREADS" gridEngineMemoryOption="-l mem_free=MEMORY" -pacbio-raw pacbio.reads.fq.gz

The .report file is attached as initial.report.txt

Next I subsampled the reads to ~60X depth from the initial ~295, because for my experiment I'm comparing assembly performance using datasets from different read libraries but roughly equivalent sequencing depth (=60X). The canu pipeline stopped after the correction step, reporting that the sequencing depth was too low to continue.

I was digging around the issues and came across this previous post:
https://github.com/marbl/canu/issues/584

Given this, I tried another canu pipeline with the parameters:

canu -p ecoli -d /assembly/output/dir/ genomeSize=4.6m corOutCoverage=999 corMinCoverage=0 gridEngineThreadsOption="-pe thread THREADS" gridEngineMemoryOption="-l mem_free=MEMORY" -pacbio-raw pacbio.reads.fq.gz

I assumed corOutCoverage and corMinCoverage would result in readsets being non-lossy from one step to the next, however apparently this is not the case. The read set at the beginning of the trimming step is smaller than the correction step, for instance. See the canu report as subset.report.txt

As a more general question. with so many reads dropping out due to no overlaps, does this indicate poor sequence data quality?

[inital.report.txt](https://github.com/marbl/canu/files/3714045/inital.report.txt)

[subset.report.txt](https://github.com/marbl/canu/files/3714046/subset.report.txt)

**Comment by skoren** [comment]
The  corMinCoverage step will keep raw reads that have at least one overlaps but if they have completely no support they will get removed, the trimming step will remove reads that again have no support or overlaps. Given that the subset report indicates a lot of reads have no overlaps and this seems like quite old data, I expect the quality is lower than current data yes. 

I would suggest increasing error rate/sensitivity. Try ```corMinCoverage=0 corMhapSensitivity=normal correctedErrorRate=0.085``` or ```corMhapSensitivity=high``` instead of normal.

**Comment by etvedte** [comment]
The first suggestion seemed to work in terms of producing an assembly. I can inspect the output and adjust as needed. Thanks!
