### ISSUE TITLE
Canu nanopore-raw split single reads into different contigs

### ISSUE THREAD

**Issue by hrpelg** [marbl/canu#1514]
I run Canu with base called  by Albacore2 raw nanopore data and I got teh contig I was after for my targeted region..plus other off targets as expected. 

However when I performed the basecalling with Guppy and run Canu with the same parameter (Nanopore-raw) than for the Albacore2 basecalled data I get every read from my target locus into single different contigs. What can I do to force the reads to be assembled in a single contig?
 I am using Canu v1.7. My data is a enrichment of a target small locus not whole genome

Many thanks

**Comment by skoren** [comment]
I'm not sure I understand the question. The same input data base called by albacore assembled correctly and as expected but after calling it with guppy there is essentially no assembly? That sounds like an issue with the guppy base calling you have. 

The first step would be to compare the reads to the assembly you have already or the targeted region and see what the identity looks like for albacore and guppy. You can also compare the canu report files as they will indicate where the issue is, in correction, trimming, or assembly. I'd also recommend updating to a more recent release, at least 1.8 or the 1.9 branch from the repo since 1.7.1 is quite old.

**Comment by hrpelg** [comment]
Hi! Thank you for your early response. Yes, that is the issue.

I mapped already Albacore2_canu_corrected reads and Guppy_canu_corrected reads to the against the whole ref genome (using minimap2) and got for both cases a (100 reads) covered targeted region. The mapping coming from Guppy + Canu correction looks better (less errors) than the albacore2 + Canu. 

But when I tried to get the contig of our target region assembled  using as input the Guppy-Canu-corrected  or Guppy raw using either oxford-nanopore or nano-corrected, the assembly doesn't have a contig with the target corrected reads. The reads end up as single contigs in unasemmbled file. Could be an issue of setting up the right Genomesize (I set up 200K), my target region is 8Kb plus I thought some off targets. I tried different size but still don't get a single contig. Could be also a problem of coverage?

Cheers, 

E

**Comment by skoren** [comment]
Post both report files from the two assemblies, you could also share the guppy reads to our FTP site (see FAQ for sending data to us) if you're willing.

**Comment by hrpelg** [comment]
Hi! Please find attached both Canu reports. They are using same input reads: raw Guppy basecalled reads and raw Albacore2.
[Albacore2_raw_canu_report.txt](https://github.com/marbl/canu/files/3731874/Albacore2_raw_canu_report.txt)
[Guppy_raw_report.txt](https://github.com/marbl/canu/files/3731901/Guppy_raw_report.txt)

Cheers, 

Elena

**Comment by skoren** [comment]
The reports look pretty similar, have you checked that the target isn't in unassigned with more than a single read in the contig? The unassigned file doesn't have to have only single-read contigs.

Try disabling the contig filtering (```contigFilter="2 0 1.0 0.5 0"```) and you can also try randomly downsampling your data.

**Comment by skoren** [comment]
Idle, no response, reports look very similar so I expect some contigs were demoted to unassembled.
