### ISSUE TITLE
Self-Correction of CCS Reads?

### ISSUE THREAD

**Issue by laurenfitch** [marbl/canu#1517]
More of a question than an issue: can Canu be used to self-correct PacBio CCS reads? The `correct` module seems to expect raw reads.

Thank you!

**Comment by skoren** [comment]
It doesn't really make sense to self-correct CCS reads, they're already self-corrected as part of the CCS process. You could force them to be self-corrected if you supplied them as raw reads but I don't expect that to improve their quality.

**Comment by laurenfitch** [comment]
That was what I expected but wanted to confirm - thanks for the quick reply!

**Comment by skoren** [comment]
You can try our experimental CCS read support if you get the 1.9 branch (which should be released by the end of the month). Specify the reads via ```-pacbio-hifi```, compare it to using the default assembly via ```-pacbio-corrected```.
