### ISSUE TITLE
Preprocessing of Nanopore data before canu assembly

### ISSUE THREAD

**Issue by SixPlusSeven** [marbl/canu#1518]
I saw in some papers that they did data filtering before nanopore data assembly, such as quality and length filtering. Is these preprocessing necessary? 
In addition, does canu consider the quality of reads when assembling nanopore data? Should I process the nanopore data before canu assembly?

Thanks，
Alex

**Comment by brianwalenz** [comment]
No need to preprocess.

Canu discards reads below 1000bp and does what could be called a quality filter through the process of finding overlaps and correcting reads.  It doesn't use QVs at all.

**Comment by SixPlusSeven** [comment]
Thank you for your answer! And I have the following two questions：
So low quality data does not affect the assembly of canu?
Will removing low-quality reads first speed up the canu calculation without affecting the assembly?

**Comment by brianwalenz** [comment]
Sure, garbage in, garbage out, as the saying goes.  A little bit of bad data will probably do little to the quality of the assembly.  It's unknown exactly how much and how bad the data needs to be to significantly degrade the assembly.

The problem I have with pre-screening reads is that it's hard to distinguish useful from junk, or biological sequence from artifacts.  Consider a long but low quality read.  This could be spanning hard-to-assemble regions, and will act as glue for the rest of the high-quality (but shorter) data.

Can you point to these papers that filtered ahead of assembly?

**Comment by SixPlusSeven** [comment]
ok！I list three articles here, which preprocessed the data before assembly.
1.  Shin S C , Kim H , Lee J H , et al. Nanopore sequencing reads improve assembly and gene annotation of the Parochlus steinenii genome[J]. Scientific Reports, 2019, 9(1).
The FASTQ files obtained by base-calling were merged into single files and used for trimming using Porechop
2. Liu Y, Tang Q, Cheng P, et al. Whole-genome sequencing and analysis of the Chinese herbal plant Gelsemium elegans[J]. Acta Pharmaceutica Sinica B, 2019.
 A  total  of  56.11 Gb  of  genomic  data  (6.23  Gb  per  cell)  with  an  average  read  length  of  14.59  kb  was generated   after   quality   filtering,   from   which   the   longest   reading   is   153.6   kb
3. Ge H, Lin K, Shen M, et al. De novo assembly of a chromosome‐level reference genome of red‐spotted grouper (Epinephelus akaara) using nanopore sequencing and Hi‐C[J]. Molecular Ecology Resources, 2019.
Nineteen Flow Cells yielded 111.05 Gb of data in total, of which 106.29 Gb was collected after filtering.

**Comment by skoren** [comment]
Did those papers compare not filtering and filtering though, I skimmed the first two and didn't see an assembly w/o filtering. The issue with nanopore data is that it becomes very quickly outdated as basecallers change and improve. I'll say that for all the nanopore assemblies we've generated, we've used all data, usually even including "failed" reads.

Low quality reads shouldn't affect the assembly but they might affect speed if they're very long. Chimeric reads would be a bigger issue, especially if they are a high proportion of your data which can happen with some library preps, but I don't think trimming would catch those anyway. If your genome isn't too big, you could try running two assemblies, w/trimming and w/o. If you do, post your experience here.
