### ISSUE TITLE
Mhap precompute jobs failed

### ISSUE THREAD

**Issue by ahrimiseq** [marbl/canu#1519]
Hello,

I install canu on ubuntu in VirtualBox.
The tar.gz file was downloaded from github. 
I followed the install instructions of canu github.  

I tried to run the assembly of nanopore data that accessed from 
http://nanopore.s3.climb.ac.uk/MAP006-PCR-1_2D_pass.fasta
After these command line,
```canu \
 -p ecoli -d ecoli-oxford \
 genomeSize=4.8m \
 -nanopore-raw oxford.fasta
```
it showed 
```
Command 'canu' not found, but can be installed with: sudo apt install canu
```

I followed the command lines and run again.
```-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '11.0.4' (from 'java').
-- Detected gnuplot version '5.2 patchlevel 2' (from 'gnuplot') and image format 'png'.
-- Detected 1 CPUs and 21 gigabytes of memory.
-- No grid engine detected, grid disabled.
```

These messages showed up:
```
-- For mhap overlapping, set repeat k-mer threshold to 1397.
--
-- Found 139736676 16-mers; 81516113 distinct and 70555151 unique.  Largest count 13740.
-- Finished stage 'cor-meryl', reset canuIteration.
--
-- OVERLAPPER (mhap) (correction)
--
-- Set corMhapSensitivity=high based on read coverage of 29.
--
-- PARAMETERS: hashes=768, minMatches=2, threshold=0.78
--
-- Given 6 GB, can fit 9000 reads per block.
-- For 4 blocks, set stride to 2 blocks.
-- Logging partitioning to 'correction/1-overlapper/partitioning.log'.
-- Configured 3 mhap precompute jobs.
-- Configured 3 mhap overlap jobs.
-- Finished stage 'cor-mhapConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'cormhap' concurrent execution on Thu Oct 17 13:31:02 2019 with 19.957 GB free disk space (3 processes; 1 concurrently)

    cd correction/1-overlapper
    ./precompute.sh 1 > ./precompute.000001.out 2>&1
    ./precompute.sh 2 > ./precompute.000002.out 2>&1
    ./precompute.sh 3 > ./precompute.000003.out 2>&1

-- Finished on Thu Oct 17 13:31:03 2019 (1 second) with 19.82 GB free disk space
----------------------------------------
--
-- Mhap precompute jobs failed, retry.
--   job correction/1-overlapper/blocks/000001.dat FAILED.
--   job correction/1-overlapper/blocks/000002.dat FAILED.
--   job correction/1-overlapper/blocks/000003.dat FAILED.
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'cormhap' concurrent execution on Thu Oct 17 13:31:03 2019 with 19.82 GB free disk space (3 processes; 1 concurrently)

    cd correction/1-overlapper
    ./precompute.sh 1 > ./precompute.000001.out 2>&1
    ./precompute.sh 2 > ./precompute.000002.out 2>&1
    ./precompute.sh 3 > ./precompute.000003.out 2>&1

-- Finished on Thu Oct 17 13:31:03 2019 (lickety-split) with 19.82 GB free disk space
----------------------------------------
--
-- Mhap precompute jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/blocks/000001.dat FAILED.
--   job correction/1-overlapper/blocks/000002.dat FAILED.
--   job correction/1-overlapper/blocks/000003.dat FAILED.
--

ABORT:
ABORT: Canu 1.6
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```
How to fix this problem?
Thanks!

**Comment by ahrimiseq** [comment]
Thanks for your response.
Do you suggest install canu on ubuntu in windows 10?
Thanks.

**Comment by skoren** [comment]
"Do you suggest install canu on ubuntu in windows 10?"

I don't understand this question. You said you downloaded the pre-compiled linux binary, I expect it should work on the ubuntu packaged with windows 10 (though I don't have a windows machine to test on). You just have to make sure you run the canu you downloaded by giving the full path to it rather than depending on your PATH variable to find it.

**Comment by ahrimiseq** [comment]
I input the command ‘/home/ahri/canu/Linux-amd64/bin/canu –version’

The following message showed up:
Global symbol "$retries" requires explicit package name (did you forget to declare "my $retries"?) at /home/ahri/canu/Linux-amd64/bin/../lib/site_perl/canu/Grid_Cloud.pm line 457.
Global symbol "$delay" requires explicit package name (did you forget to declare "my $delay"?) at /home/ahri/canu/Linux-amd64/bin/../lib/site_perl/canu/Grid_Cloud.pm line 461.
Global symbol "$retries" requires explicit package name (did you forget to declare "my $retries"?) at /home/ahri/canu/Linux-amd64/bin/../lib/site_perl/canu/Grid_Cloud.pm line 461.
Global symbol "$delay" requires explicit package name (did you forget to declare "my $delay"?) at /home/ahri/canu/Linux-amd64/bin/../lib/site_perl/canu/Grid_Cloud.pm line 462.
Global symbol "$retryCount" requires explicit package name (did you forget to declare "my $retryCount"?) at /home/ahri/canu/Linux-amd64/bin/../lib/site_perl/canu/Grid_Cloud.pm line 503.
Global symbol "$retryDelay" requires explicit package name (did you forget to declare "my $retryDelay"?) at /home/ahri/canu/Linux-amd64/bin/../lib/site_perl/canu/Grid_Cloud.pm line 507.
Global symbol "$retryDelay" requires explicit package name (did you forget to declare "my $retryDelay"?) at /home/ahri/canu/Linux-amd64/bin/../lib/site_perl/canu/Grid_Cloud.pm line 508.
Compilation failed in require at /home/ahri/canu/Linux-amd64/bin/../lib/site_perl/canu/Report.pm line 41.
BEGIN failed--compilation aborted at /home/ahri/canu/Linux-amd64/bin/../lib/site_perl/canu/Report.pm line 41.
Compilation failed in require at /home/ahri/canu/Linux-amd64/bin/../lib/site_perl/canu/SequenceStore.pm line 48.
BEGIN failed--compilation aborted at /home/ahri/canu/Linux-amd64/bin/../lib/site_perl/canu/SequenceStore.pm line 48.
Compilation failed in require at /home/ahri/canu/Linux-amd64/bin/../lib/site_perl/canu/HaplotypeReads.pm line 62.
BEGIN failed--compilation aborted at /home/ahri/canu/Linux-amd64/bin/../lib/site_perl/canu/HaplotypeReads.pm line 62.
Compilation failed in require at /home/ahri/canu/Linux-amd64/bin/canu line 59.
BEGIN failed--compilation aborted at /home/ahri/canu/Linux-amd64/bin/canu line 59.

**Comment by skoren** [comment]
It looks like you've installed another version of Canu, and not a release but master. That isn't recommended since it changes rapidly. For example that error was fixed by commits today. Stick with a release version downloaded from the releases page.

Run the following commands in the folder with the reads:
```
curl -L https://github.com/marbl/canu/releases/download/v1.8/canu-1.8.Linux-amd64.tar.xz -o canu.tar.xz
tar -xJf canu.tar.xz 
./canu-1.8/*/bin/canu -version
./canu-1.8/*/bin/canu -p ecoli -d ecoli-oxford \
 genomeSize=4.8m \
 -nanopore-raw oxford.fasta
```

**Comment by skoren** [comment]
Idle, issue was an old canu version incompatibility with latest JVM, resolved in more recent releases.
