### ISSUE TITLE
parameter recommendations for noisy high coverage dataset

### ISSUE THREAD

**Issue by aswathyseb** [marbl/canu#152]
Hi,

I have high-coverage(150X) minIon data that I want to assemble. The data is noisy with around 0.2-0.25 % error rate. Do you have any recommendations on what parameters to use for this data set to assemble with Canu. So far I have tried 'corOutCoverage' and 'errorRate' with no success. Could you please help?

Thanks,

**Comment by skoren** [comment]
Do you mean 20-25% error rate? That's fine and quite typical for nanopore, you should just be able to run it with default parameters. What do you mean no success? Did the assembly finish or did it give an error along the way?

**Comment by aswathyseb** [comment]
Canu produces 4 contigs and 69 sequences in unassembled.fasta file. But there are regions which are well-covered and seemingly easy-to-assemble but completely missing from the assembly.How can I fine tune canu to include these regions and produce a better assembly? The command that I am using is
```canu -p genome -d genome-canu genomeSize=150k -errorRate=0.2 -maxMemory=20 -maxThreads=4 -nanopore-raw all_2d.fq ```

**Comment by brianwalenz** [comment]
Well, this question seems to have fallen on the floor, sorry.

You possibly need to correct more reads, or change the setting for the unassembled contig filter.

Check the FAQ http://canu.readthedocs.io/en/latest/faq.html for details.  Reopen or make a new issue as needed.
