### ISSUE TITLE
Q: How to reduce IO time and correctly set thread/memory for stages upto meryl?

### ISSUE THREAD

**Issue by SHuang-Broad** [marbl/canu#1522]
Hi,

I have a few questions about runtime performance when using canu for splitting long reads on a human child when short reads from both parents are available, with the **ultimate** aim of adapting at least the trio-binning stage into a cloud-friendly pipeline.

I've noticed that the process is IO bound up to the kmer counting stage.

------------

## Experiment setup

I am using canu branch 1.9 on a VM with 24 CPUs and 190 G memory available.

My experiment using the Ashkenazim trio has the following setup structure

```
$ tree -d trioCanu/
trioCanu/
├── father
├── hg002
│   ├── 10kb
│   └── 15kb
├── mother
```
where `father` and `mother` contains short read FASTQs, and I'm using two public PcBio HiFi data sets on the son (two different read sizes to check their effect on assembly).

And my script for running canu is
```bash
$ cat triobin.sh
#!/bin/bash

set -eu

canu \
  -haplotype \
  -p giab \
  -d /home/shuang/paper/trioCanu/testrun \
  genomeSize=3.1G \
  merylMemory=180 \
  merylThreads=22 \
  minThreads=16 \
  -haplotypeFather /home/shuang/paper/trioCanu/father/*.fastq.gz \
  -haplotypeMother /home/shuang/paper/trioCanu/mother/*.fastq.gz \
  -pacbio-hifi /home/shuang/paper/trioCanu/hg002/15kb/*.fastq.gz
```

## Re-partitioning parental reads
At first the parents' short read fastqs seem to be re-partitioned. I guess that is done so that the partition is more friendly to canu's workflow controller? This took about 2 hours on my Google VM instance, where it seems that 4 threads are used.

The optimization I am thinking about for this stage is to
  * provision a VM with lower CPU & memory resources in this IO bound step before meryl kicks in
  * save the result to some intermediate location, then
  * provision a VM with high memory for meryl, first copying the saved result to this VM.

This optimization is
  * trying to take advantage of canu's capability in resuming jobs after interruptions, if I understand correctly
  * based on the fact that storage is much cheaper compared to CPU and memory on cloud VMs.

## meryl count
Then `meryl-count.sh` under my `test/haplotype/0-kmers` kept being invoked in serial for the (53) batches, with most of the time spent loading the FASTQs (from the previous stage) assigned to that batch into memory. Effectively 1 thread is used for the loading that lasts ~ 30 minutes and the actual counting takes ~ 5 minutes using the 22 threads as specified but making use of only ~ 26 G memory (which is what's specified in `meryl-count.sh`)

So apparently I've set my memory and thread in a very bad way, or at least not interacting correctly with canu's workflow controller.

The optimization I am thinking about for this counting stage is more of a question:
  * it seems that the kmer counting step is a perfect candidate for a scatter-gather scheme, and canu's workflow controller is doing that with some assumptions baked in for grid computing. I am wondering what those assumptions are. Particularly how are the arguments `merylMemory` and `merylThreads` interacting with themselves and with the actual CPU and memory available? Should I specify some parameters [here](https://canu.readthedocs.io/en/latest/tutorial.html#execution-configuration) considering I am essentially running canu locally?

Below are the lines from `meryl-count.sh`  sans the batch-defining blocks

```bash
#!/bin/sh


#  Path to Canu.

syst=`uname -s`
arch=`uname -m | sed s/x86_64/amd64/`

bin="/home/shuang/bin/canu/$syst-$arch/bin"

if [ ! -d "$bin" ] ; then
  bin="/home/shuang/bin/canu"
fi

#  Report paths.

echo ""
echo "Found perl:"
echo "  " `which perl`
echo "  " `perl --version | grep version`
echo ""
echo "Found java:"
echo "  " `which /usr/lib/jvm/java-8-oracle/bin/java`
echo "  " `/usr/lib/jvm/java-8-oracle/bin/java -showversion 2>&1 | head -n 1`
echo ""
echo "Found canu:"
echo "  " $bin/canu
echo "  " `$bin/canu -version`
echo ""


#  Environment for any object storage.

export CANU_OBJECT_STORE_CLIENT=
export CANU_OBJECT_STORE_CLIENT_UA=
export CANU_OBJECT_STORE_CLIENT_DA=
export CANU_OBJECT_STORE_NAMESPACE=
export CANU_OBJECT_STORE_PROJECT=




#  Discover the job ID to run, from either a grid environment variable and a
#  command line offset, or directly from the command line.
#
if [ x$CANU_LOCAL_JOB_ID = x -o x$CANU_LOCAL_JOB_ID = xundefined -o x$CANU_LOCAL_JOB_ID = x0 ]; then
  baseid=$1
  offset=0
else
  baseid=$CANU_LOCAL_JOB_ID
  offset=$1
fi
if [ x$offset = x ]; then
  offset=0
fi
if [ x$baseid = x ]; then
  echo Error: I need CANU_LOCAL_JOB_ID set, or a job index on the command line.
  exit
fi
jobid=`expr -- $baseid + $offset`
if [ x$CANU_LOCAL_JOB_ID = x ]; then
  echo Running job $jobid based on command line options.
else
  echo Running job $jobid based on CANU_LOCAL_JOB_ID=$CANU_LOCAL_JOB_ID and offset=$offset.
fi

###############################
# omitting the batch-defining codes here (53 batches)
# ...
###############################

#  If the meryl database exists, we're done.

if [ -e ./reads-$output.meryl/merylIndex ] ; then
  echo Kmers for batch $output exist.
  exit 0
fi

#  And compute.

/home/shuang/bin/canu/Linux-amd64/bin/meryl k=21 threads=22 memory=27.64 \
  count \
    output ./reads-$output.meryl.WORKING \
    $batch \
&& \
mv -f ./reads-$output.meryl.WORKING ./reads-$output.meryl

exit 0
```

## meryl merge and subtract

Finished relatively quickly. Cannot think of any optimization (maybe premature optimization if any).

## `hap` failed

No idea why that is the case yet.

------------

I've attached the log file running my `triobin.sh` here, if that helps.

Thank you!
Steve

[triobin.log.zip](https://github.com/marbl/canu/files/3748028/triobin.log.zip)

**Comment by brianwalenz** [comment]
Phew, there's a lot to answer here.

1)

There *is* support for cloud-based computes and storing intermediate files in an object store.  We only have 'drivers' for the DNAnexus platform.  To support a new platform, four basic functions are needed: upload a file, download a file, query if a file exists, and submit a new job for execution.

File actions are implemented in src/pipelines/canu/Grid_Cloud.pm.  Function fetchFile() in there is representative.  Two versions of each exist, one that runs directly from perl, and one that runs as a series of shell-script commands.

Job execution needs to support a mechanism where a job will run only after all of a set of other jobs has completed.  For example, Canu will submit 20 meryl jobs, and one more that should run only after all the meryl jobs have completed.

There's also some configuration tasks, like querying what compute resources are available, that are needed.  This is just a mapping from job parameters (number of CPUs, memory needed) to instance name.

2)

Meryl count jobs are configured such that both the number of jobs and the job size increases with the size of the input short-read data.  This looks to be functioning correctly, if perhaps creating jobs that are slightly too large.

As you've noticed, there is not much gain from more merylThreads.  The threads are used only during output; the 'hard part' can only use a single thread.  For this step, 4 threads is sufficient (the default is to pick between 1 and 8 threads, based on what nodes are available).  The benefit of this backwards-ness (single thread compute, multi-thread output) is that later processing of the kmer data (merge and subtract) is quite fast.  These steps will benefit from more threads, up to 64.

I'll have to think a bit on how to support a single large machine here.  With the current strategy, it could run 7 jobs at 26 GB each concurrently (182 GB total), which would let this step finish in 8 batches of 30 minutes each (~4 hours).  But that's still only 30% CPU utilization.

If you want to hack the code a bit to see what smaller jobs would perform like, explicitly setting `$nFilesPerJob` at line 316 in src/pipelines/canu/HaplotypeReads.pm will change the job size.  Canu picked 80 files per job, resulting in 52 jobs.  Setting nFilesPerJob to 40 should result in 102 jobs, each around 13 GB in size, which would let around 14 jobs run concurrently.

**Comment by SHuang-Broad** [comment]
Thanks, Brian!
You answers helped me getting started in `src/pipelines`.

I'll close this ticket for now, as I need to do a deep dive into the Perl scripts.

I am sure I'll have more questions as I adapt the Perl scripts (and possibly Perl modules) to fit our Google Could computing infrastructure together with workflow managed by WDL.
If something useful grows out of this effort and is appropriate to be contributed back into canu (that is, IMHO), I'll generate an PR.

Steve
