### ISSUE TITLE
running out of memory in overlapper

### ISSUE THREAD

**Issue by nsmackler** [marbl/canu#1523]
Hi,

I ran the canu pipeline, using the following script. 
```
#!/bin/bash
module load canu/1.8

canu -p dix_pb -d tgel \
    genomeSize=3.0g \
    correctedErrorRate=0.105 \
    gridOptions="-A nsnyderm --time=5-0" \
    -pacbio-raw /scratch/nsnyderm/m54329U_190915_100748.subreads.fasta 
```

It's a 3 gb primate genome, and the error is during the overlap score correction: 
```
-- BEGIN CORRECTION
--
--
-- Creating overlap store correction/dix_pb.ovlStore using:
--    201 buckets
--    201 slices
--        using at most 29 GB memory each
--
-- Overlap store sorting jobs failed, tried 2 times, giving up.
--   job correction/dix_pb.ovlStore.BUILDING/0001 FAILED.
--   job correction/dix_pb.ovlStore.BUILDING/0002 FAILED
```

I'm running into another error (sorry I'm just getting back to this since i have time). It's running out of memory late in the pipeline, which is an automated pipeline.

I went into the detailed logs
```tail /dix_pb.ovlStore.BUILDING/logs/2-sort.1955545_96.out```
and here is the error at the end:
```Loading 1236786334 overlaps using 27.64 GB of allowed (-M) 29 GB memory./var/spool/slurmd/job1955793/slurm_script: line 114:  8982 Killed                  $bin/ovStoreSorter -deletelate -O ./dix_pb.ovlStore.BUILDING -S ../dix_pb.seqStore -C ./dix_pb.ovlStore.config -f -s $jobid -M 29slurmstepd: error: Detected 1 oom-kill event(s) in step 1955793.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.```

Any idea how I can get this sorted out or can tell it to use less memory? I've reached out to my IT team to see if they can help. I only have to assemble this genome once, so any help would be much appreciated.

```canu --version
Canu snapshot v1.8 +358 changes (r9568 c478f9e441e76326ea1435adedf7f01997bbd32f)```

Thank you

**Comment by skoren** [comment]
You should be able to increase this memory request slightly, either edit the  ```/dix_pb.ovlStore.BUILDING/scripts/2-sort.jobSubmit*.sh``` script to increase the memory from the current 29g to 64g and re-run it (from inside the ```/dix_pb.ovlStore.BUILDING/``` folder) or add ```gridOptionsovs="--mem-per-cpu=64g"``` to the canu command and re-launch.

By the way, what you have is not 1.8, it's an intermediate checkout from the repo so it isn't validated as much as a release. We generally don't recommend using those versions for production assembly.

**Comment by nsmackler** [comment]
Thanks for the quick and helpful response!

I had my sysadmins install the package cluster-wide, so maybe they picked the wrong version. I will ask them replace it with the stable release. 

Is there a way to pickup a job where it left off as some sort of checkpointing? I guess that is the option you mentioned where I can modify all of the 2-sort*sh jobs, but was wondering if you had that option in the main script as I don't quite know how many more steps there are after the overlapping.

**Comment by skoren** [comment]
Don't replace the package in the middle of a run, it will likely break your assembly.

The checkpointing is automatic, you don't need to specify anything additional. I suggested modifying the scripts to make sure the updated memory is sufficient to complete the jobs, it's not required. If you re-run Canu with the added option I suggested, it will resume where it failed and try requesting more memory itself. So the simplest option for you is to try adding the gridOptionsovs parameter and seeing if the jobs complete now.

**Comment by nsmackler** [comment]
Thanks! That worked. Now a few days later I'm running into another issue during untigging.

The 4-untigger script is requesting 
`--cpus-per-task=32 --mem-per-cpu=16g`

but that configuration isn't available to me. And when I try and override it by adding
`gridOptions="--cpus-per-task=16 --mem-per-cpu=16g" `
it doesn't work. I just adds it to the end of the slurm submit job script.

Any chance we can override this and request a slightly lower number of CPUs?  

Thanks,
Noah

**Comment by brianwalenz** [comment]
Use options batMemory=100 (or more, but it probably won't matter) and batThreads=16; no need to set gridOptions.  For safety, remove the unitigging.4-unitigging directory before restarting.

**Comment by nsmackler** [comment]
Thanks! Will update you at the next roadblock :)

**Comment by nsmackler** [comment]
For some reason that is only working for the first untigging bit, but not the for the alignGFA script:
``` cat unitigging/4-unitigger/alignGFA.jobSubmit-01.sh 
#!/bin/sh

sbatch \
  --cpus-per-task=32 --mem-per-cpu=2g -A nsnyderm --time=5-0 -o alignGFA.%A_%a.out \
  -D `pwd` -J "gfa_dix_pb" \
  -a 1-1 \
  `pwd`/alignGFA.sh 0 \
> ./alignGFA.jobSubmit-01.out 2>&1```

It's now trying to submit with 32 threads even though I am using the batThreads=16 option.

Thanks in advance for your help!

**Comment by brianwalenz** [comment]
Each stage has its own configuration options.  This one is 'gfaMemory' and 'gfaThreads'.

At the start of canu logging, it will show a table of the resources each stage wants to use, similar to:
```
--                         (tag)Threads
--                (tag)Memory         |
--        (tag)             |         |  algorithm
--        -------  ----------  --------  -----------------------------
-- Grid:  meryl     24.000 GB    8 CPUs  (k-mer counting)
-- Grid:  hap       12.000 GB    8 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   16.000 GB    4 CPUs  (overlap detection with mhap)
-- Grid:  obtovl     8.000 GB    6 CPUs  (overlap detection)
-- Grid:  utgovl     8.000 GB    6 CPUs  (overlap detection)
-- Grid:  cor       16.000 GB    4 CPUs  (read correction)
-- Grid:  ovb        4.000 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       12.000 GB    1 CPU   (overlap store sorting)
-- Grid:  red       15.000 GB    4 CPUs  (read error detection)
-- Grid:  oea        8.000 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat       64.000 GB    8 CPUs  (contig construction with bogart)
-- Grid:  cns        -.--- GB    8 CPUs  (consensus)
-- Grid:  gfa       16.000 GB    8 CPUs  (GFA alignment and processing)
```
the word in the 'tag' column can be used to set options for that stage.  See https://canu.readthedocs.io/en/latest/parameter-reference.html#algorithm-execution-method and maybe the previous sections.

(Entries with no value shown compute how much memory they'll need.)

**Comment by nsmackler** [comment]
Ah - got it. Thanks!

**Comment by skoren** [comment]
You can also limit all steps to a maximum number of cores via ```maxThreads=16```.

**Comment by nsmackler** [comment]
Thanks! I got it to complete and am now working on the next steps.

**Comment by skoren** [comment]
For future runs, if you add maxThreads=16 to a file named ```~/.canu```, along with any other options you ended up customizing (like ```gridOptions="-A nsnyderm --time=5-0"```), they will automatically be added to your command. That way you don't have to remember to add them all the time.
