### ISSUE TITLE
ONT reads correction ERROR

### ISSUE THREAD

**Issue by Axolotl233** [marbl/canu#1524]
thank you for reading my question

I m try to correct ONT data using Canu, but there someting wrong

canu version : Canu snapshot v1.8 +476 changes

system : liunx

my command :
```
./canu/Linux-amd64/bin/canu -correct -p RL -d rl maxThreads=50 genomeSize=350m minReadLength=3000 minOverlapLength=500 corOutCoverage=120 corMinCoverage=2 -nanopore-raw RL_clean_ont_fastq.gz
```

```
> ERROR :-- Starting command on Tue Oct 22 02:51:35 2019 with 1987.769 GB free disk space
> 
>     cd .
>     ./RL.seqStore.sh \
>     > ./RL.seqStore.err 2>&1
> 
> Finished on Tue Oct 22 02:54:59 2019 (204 seconds) with 0 GB free disk space  !!! WARNING !!!
> 
> ERROR:
> ERROR:  Failed with exit code 1.  (rc=256)
> ERROR:
> 
> ABORT:
> ABORT: Canu snapshot v1.8 +476 changes (r9686 19560b269db9bf87419fdc40af0974376da2712e)
> ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
> ABORT: Try restarting.  If that doesn't work, ask for help.
> ABORT:
> ABORT:   sqStoreCreate failed; boom!.
> ABORT:
> ABORT: Disk space available:  1981.005 GB
```

no more useful information i found in output folder and i have not found how to solve this question, but i can use this command successfully in another serve with same data.

thank you

**Comment by skoren** [comment]
From your version you're on slightly out of date master which is not guaranteed to be stable. I'd suggest sticking with either the 1.8 or 1.9 (to come shortly) release.

If it still is failing with those versions, check the full log in ```rl/RL.seqStore.err``` and post it here.

**Comment by skoren** [comment]
Any update?

**Comment by skoren** [comment]
Idle, likely an error due to unstable master version.

**Comment by Axolotl233** [comment]
i have run canus correction in another machine and it worked, so i don't have to solve this ERROR, thank you
