### ISSUE TITLE
Questions-Suggestions of separate steps

### ISSUE THREAD

**Issue by Tdanis** [marbl/canu#1527]
Hi everyone, due my poor experience on de novo genome assemblies, could you suggest me any improvement for my assembly. My assembly is pure nanopore data with ~20x coverage. 
My commands are ,
**For correction-->**
canu -correct 
-d /my-dir/canu-1.8-corrected 
gridOptions="--partition batch" gridEngineArrayOption="-a ARRAY_JOBS%12" corMinCoverage=0
 corMhapSensitivity=high genomeSize=0.5g
-nanopore-raw my-file.fastq

**For trim -->**
canu -trim -p trim 
-d /my-dir/-1.8-trimmed 
gridOptions="--partition batch" gridEngineArrayOption="-a ARRAY_JOBS%16" 
corMinCoverage=0 corMhapSensitivity=high 
genomeSize=0.5g -nanopore-corrected 
/canu_correction.correctedReads.fasta

**For assembly -->**

canu -assemble 
-d /my-dir/Canu-1.8-assembly-new gridOptions="--partition batch" 
gridEngineArrayOption="-a ARRAY_JOBS%16" stopOnLowCoverage=0 
correctedErrorRate=0.105 genomeSize=0.5g -nanopore-corrected 
/my-dir/trim-reads.fasta

**Comment by skoren** [comment]
The FAQ has suggestions for parameters you can improve. 20x is the bare minimum for assembly we recommend so more coverage would be another thing to consider along with re-calling with the most recent base callers if you haven't already. You could try increasing the trimming/unitigging error rate to 0.15 (0.105 is quite low given your coverage and nanopore data) and/or multiple rounds of correction.

Can't give more concrete advice based on just commands, at least post the report files generated from all the steps you ran.

**Comment by Tdanis** [comment]
[correction.txt](https://github.com/marbl/canu/files/3756291/correction.txt)
[assemble.txt](https://github.com/marbl/canu/files/3756297/assemble.txt)
[trim.txt](https://github.com/marbl/canu/files/3756299/trim.txt)

Thank you very much

**Comment by Tdanis** [comment]
[assemble.txt](https://github.com/marbl/canu/files/3756309/assemble.txt)
[correction.txt](https://github.com/marbl/canu/files/3756310/correction.txt)
[trim.txt](https://github.com/marbl/canu/files/3756311/trim.txt)

**Comment by skoren** [comment]
Those reports look ok, I don't see issues with the correction or trimming, you have a nice peak around 23-29x coverage from the k-mers. That to me implies the genome is slightly smaller than you estimated. The assembly report looks OK too. The reads are pretty short which will mean you won't be able to span many repeats but it should still assemble OK. The report didn't show your assembly though, do you have contigs?

So I guess the question is what exactly do you mean by "poor experience".

**Comment by Tdanis** [comment]
No I dont because crashed , in this morning.
I mean , poor experience in terms of the use of canu assembler .

**Comment by skoren** [comment]
Can't comment on "poor experience" without specifics, you can always open an issue for a specific error.

No parameters as the reports look fine, the error rate 0.105 might be a bit low but can't know that w/o looking at the output from the 4-unitigging step.

**Comment by skoren** [comment]
This typically happens when you have multiple partitions on the cluster with different resources and Canu sees all the nodes and tries to use one but that partition that requires special parameters to submit jobs (see #963). 

I'd guess the configuration set it up to use a large-memory node that is not available in the partition you requested (batch). Limit canu or bogart to the maximum memory on your partition (batMemory=```<whatever is max on batch partition>``` or ```maxMemory=<whatever is max on batch partition>```) to your canu command and re-start. Once you get it to work you can also add this to canu's default (```~/.canu``` or ```/mnt/big/Assembly/canu-1.8/Linux-amd64/bin/canu.defaults)``` so it will always get included.

**Comment by Tdanis** [comment]
So, in order to re-submit my canu job and continue after the last correct step what have I do? I do not want to re-run it from scratch.

Thank you very much

**Comment by skoren** [comment]
Canu automatically tracks where it is and resumes the pipeline, so re-run the same canu command you used before after adding the batMemory option.

**Comment by skoren** [comment]
Idle, original question answered.
