### ISSUE TITLE
Is this statement still valid?

### ISSUE THREAD

**Issue by SHuang-Broad** [marbl/canu#1528]
> Trio binning does not yet support inputting PacBio HiFi reads for binning as they get flagged as "corrected" and the same error as above is given. As a workaround, run canu -haplotype specifying the HiFi reads as -pacbio-raw. This will bin the data and create shell scripts to start the assembly. Edit the shell scripts to replace -pacbio-raw with -pacbio-corrected or -pacbio-hifi and run the assemblies manually.

Excerpt from the paragraph immediately above [this](https://github.com/marbl/canu/blob/master/documentation/source/quick-start.rst#consensus-accuracy), in the `Trio Binning Assembly` section of `documentation/source/quick-start.rst`

Thanks!
Steve

**Comment by skoren** [comment]
Yep that is correct.
