### ISSUE TITLE
mhap v Ovl

### ISSUE THREAD

**Issue by fergsc** [marbl/canu#1529]
Hi, my assemblies are taking a very long time to complete due to overlap detection. If I were to change the overlap algorithm from Ovl to mhap for trimming and/or unitiging whould you expect a large reduction in the quality of the output genome?

thanks.

**Comment by skoren** [comment]
Depends what you mean by quality, base quality or mis-assemblies, no. Continuity and NG50, in some cases yes. We've seen on human the NG50 can drop to 12mb from 25mb for a dataset with the change but other genomes (like c. elegans, tomato) are not affected. It will certainly be much faster on nanopore data though.

**Comment by fergsc** [comment]
Thanks, a reduction in run time seems like a good trade by using mhap.

**Comment by fergsc** [comment]
Posting an update for this, incase anyone is interested.

I am assembling a number of plant genomes with high heterozygosity and repeats. Estimated genome size ~600m. My coverage is low ~20-22x.
During correction the mhap (default) overlapper took less than 10 hours * 8cpu per job. During trimming the ovl overlapper did not finish, the max job time I can use is 168 hours and many jobs didn't finish. Thats 168*8cpu=1344 total hours.
Changing to mhap for trimming and unitigging all jobs finished in less than 2 hours with 8cpu.
