### ISSUE TITLE
setting error rate for unitigging step

### ISSUE THREAD

**Issue by albodrug** [marbl/canu#153]
Hello!
I'd like to set up a personally estimated error rate in corrected reads for the canu unitigging step. Seems like the options reported in the canu readthedocs do not exist anymore.
```
ERROR:  Paramter 'utgGraphErrorRate' is not known.
ERROR:  Paramter 'utgMergeErrorRate' is not known.
ERROR:  Paramter 'utgRepeatErrorRate' is not known.
```
The parameters left for error rate in unitigging that I found so far are utgMhapFilterUnique and utgRepeatDeviation. Could you advise me on a way to set canu so that it does not use corrected reads which align with more that 0.01 (1%) error rate for the assembly? I would also like to turn on utgMhapFilterUnique to minimize noise overlaps. Could you explain this feature a bit more?

Thanks!
Alex

**Comment by skoren** [comment]
I'm guessing you're running the latest from git, not a release? Those options are gone in the latest code and shouldn't appear in the updated docs: http://canu.readthedocs.io/en/latest/index.html

You can limit the error rate with the ```errorRate`` parameter, by default overlaps are computed at 3-fold higher coverage than your setting. So, if you set ```errorRate=0.003``` it should give you only overlaps below 1% error.

utgMhapFilterUnique is experimental so we aren't supporting it, you can run it but it may not work. It will throw out k-mers below the expected number of times a correct k-mer should appear in your sequences given the error rate and coverage.
