### ISSUE TITLE
Q: where can we read more about sequenceStore

### ISSUE THREAD

**Issue by SHuang-Broad** [marbl/canu#1531]
It seems that this is used for storing the reads.
We are interested in making efficient use of that.

Forgive me if the answer lies in this repo, but I cannot seem to find any documentation.

**Comment by brianwalenz** [comment]
Most of the functionality is at the C++ API level.

From the command line, two utilities exist to access data in it: sqStoreDumpFASTQ and sqStoreDumpMetaData.  The only documentation is the command line usage.

Note that the seqStore changed significantly recently.  The v1.9 branch has an older version, while the master branch has a newer version.  Some of the command line options are different or not present, and the output of sqStoreDumpMetaData will be different.
