### ISSUE TITLE
Canu vaporized my reads? also Canu takes too much days

### ISSUE THREAD

**Issue by khyojoo01** [marbl/canu#1533]
I tried to run correction jobs on ONT nanopore generated human genomes by using Canu commands like : 
```
$canu-directory/canu/Linux-amd64/bin/canu -correct -d mydata \
 -p output-name genomeSize=97m useGrid=true stopOnLowCoverage=3 \
 gridEngineResourceOption="-l nodes=1:ppn=THREADS,mem=MEMORY" gridEngineMemoryPerJob=1 \
 -nanopore-raw nanopore-read-adptrim.sorted.chr21-22.bam.fastq
```
```
$canu/Linux-amd64/bin/canu -correct corOutCoverage=1000 -d output-directory \
 -p output genomeSize=97m useGrid=false stopOnLowCoverage=0 'ovsMemory = 100g-250g' \
 gridEngineResourceOption="-l nodes=1:ppn=THREADS,mem=40g" gridEngineMemoryPerJob=1 gridOptionsovs="-l mem=130g" \
 -nanopore-raw nanopore-read_adptrim.sorted.chr21-22.bam.fastq
```
```
$canu/Linux-amd64/bin/canu -correct corOutCoverage=1000 -d output-dir \
 -p output genomeSize=97m useGrid=false stopOnLowCoverage=0 'ovsMemory = 100g-250g' overlapper=mhap utgReAlign=true \
 gridEngineResourceOption="-l nodes=1:ppn=THREADS,mem=40g" gridEngineMemoryPerJob=1 gridOptionsovs="-l mem=130g" \
 -nanopore-raw nanopore-read_adptrim.sorted.chr21-22.bam.fastq
```
and yes Sir, I used memory options on grid while using useGrid=false option because I was having trouble with using grid on whole genome sequence. Anyway, I had 3 following results 
```
Number of reads = 205470
Total bases = 1496696294
```
```
Number of reads = 139576
Total bases = 997692479
```
```
Number of reads = 211287
Total bases = 1495564815
```
data before canu-correction had these results
```
Number of reads = 137672
Total bases = 1659031153
```
I don't understand the results and Please help me.

also I can't see the end of my jobs on these commands:
```
$canu/Linux-amd64/bin/canu -correct corOutCoverage=1000 -d output-dir \
 -p outtput genomeSize=3g useGrid=false stopOnLowCoverage=0 'ovsMemory = 100g-250g' overlapper=mhap utgReAlign=true \
 gridEngineResourceOption="-l nodes=1:ppn=THREADS,mem=130g batMemory=100 batThreads=20 merylMemory=100 merylThreads=20" gridEngineMemoryPerJob=1 gridOptionsovs="-l mem=130g" \
 -nanopore-raw nanopore-input-nanofilt_adptrim.fastq
```
```
$canu/Linux-amd64/bin/canu -correct corOutCoverage=1000 -d output-dir \
 -p output genomeSize=3g useGrid=true stopOnLowCoverage=0 'ovsMemory = 100g-250g' batMemory=100 batThreads=20 merylMemory=100 merylThreads=20 overlapper=mhap utgReAlign=true \
 gridEngineResourceOption="-l nodes=1:ppn=THREADS,mem=130g" gridEngineMemoryPerJob=1 gridOptionsovs="-l mem=130g" \
 -nanopore-raw nanopore-input-nanofilt_adptrim.fastq
```
Please help me sir, I beg you
Environment : OS: CentOS release 6.10 (Final)

**Comment by skoren** [comment]
I am not sure I understand your question. The input data you have is only about 16x coverage, that's pretty low, do you really have only 16x? don't think there's any difference between all three of your commands, ```overlapper=mhap utgReAlign=true``` has no effect on the correction step and ```corOutCoverage=1000``` will have no effect if you have less than the default 40x of coverage anyway so I'd expect them to output about the same corrected reads, which I see 2/3 do. Either way the output you posted ranges between 10-14x, not surprising given how little coverage you had in the input and not unexpected so I don't see anything to fix there.

For your second question, is that the full human genome? Running on a single node for a human genome will take weeks and isn't recommended (even with overlapper=mhap it will take about 20k cpu hours).

**Comment by khyojoo01** [comment]
Well, shouldn't results be same if I used the same input with different options that will have no effect, unless there are 1/3 of more than x1000 coverage reads in average x16 coverage reads data which is generated by PromethION machine? I'm asking you why did  
```
Number of reads = 205470
Total bases = 1496696294
```
result went down to 
```
Number of reads = 139576
Total bases = 997692479
```
just because I added corOutCoverage=1000 option?
And why did my  
```
Number of reads = 137672
Total bases = 1659031153
```
input has small portion of missing base pairs to 
```
Number of reads = 205470
Total bases = 1496696294
```
after running canu?
Is there any read filtering or end trimming steps in your canu code?

and thanks for your answer on my second question. I really appreciate it.

**Comment by skoren** [comment]
I agree it shouldn't drop 1/3 but your third run had the corOutCoverage=1000 and almost the same output as the first run so I don't think the difference is due to corOutCoverage. Are you sure there were no other differences in the inputs for the second run? Post the canu version you are using and the report files from the runs.

As for trimming, yes canu will trim reads at multiple times. The correction only keeps reads which have support from other reads. Thus reads which have no support will be removed.

**Comment by khyojoo01** [comment]
Canu version is : Canu snapshot v1.8 +194 changes (r9404 e13467a0ada171b9f70dd9ea615452cd707ea0ac)
yes, I used the exact same input file on those 3 runs. 
and here are the reports
[canu-logs_report_seqStore_error.zip](https://github.com/marbl/canu/files/3776660/canu-logs_report_seqStore_error.zip)

Thanks for your fast answers. 

Oh, by the way ... I'm not sure this is the right moment to add another information here but, 
actually I have another canu run result on whole human genome with no corOutCoverage = 1000 option which had almost x22 coverage and dropped to x5 coverage. would you like to see that case too? I'm so sorry keep bothering you TT <- this means I'm crying in Korea.

**Comment by skoren** [comment]
First, the version you're using is in between two releases, I'd suggest sticking with the 1.8 or 1.9 (soon to come or you can build from the branch) not this intermediate.

For the log you attached, which run is this? From the logs it looks like it has corOutCoverage=1000 set. It reports you had:
```
--   Found 137672 reads.
--   Found 1659031153 bases (17.1 times coverage).
```
before correction and
```
--   Found 136838 reads.
--   Found 1628797952 bases (16.79 times coverage).
```
after. 

That doesn't match any of your three runs though so I am not sure how you're counting the reads after correction.

**Comment by khyojoo01** [comment]
OK, I'll try to use Canu 1.8 version. Is it 'Latest commit 22a2453 on 23 Oct 2018'? 
Can you give me git clone https://*/canu.git address for '22a2453' release? I need it to install. 
And the canu-log report I posted earlier was the case of 'with corOutCoverage=1000' and ***Aligned and Mapped with LAST to Human genome referenece hg38.*** and all other 2 Nanoplot results I posted at first were also ***Aligned and Mapped with LAST to Human genome referenece hg38.***

**Comment by skoren** [comment]
To install the release, download the pre-compiled binary from the releases page: https://github.com/marbl/canu/releases/tag/v1.8, you don't need to clone/build it.

So based on the Canu logs, adding corOutCoverage didn't change the reads output, I see the bases stayed a high fraction of the input. I don't see an issue in the Canu run. 

I am also not sure about the alignments, the results look suspicious. First, I don't think you're counting reads but alignments (since you're reporting more "reads" than canu output). I also don't believe all your raw reads would map full-length and 100% of the bases which is what the pre Canu stats you posted imply.

**Comment by khyojoo01** [comment]
OK thanks for your attention and kind answers. I'll try them on v1.8 and report another issue if there's anything to ask. Thanks again.
