### ISSUE TITLE
Q: undocumented `saveReadHaplotypes`

### ISSUE THREAD

**Issue by SHuang-Broad** [marbl/canu#1535]
This "global" parameter defined in `src/canu/Default.pm` is not documented.
So I am curious about what type of intermediate files it is referring to, and why its synopsis reads
> Save intermediate read haplotype files, almost never a good idea

**Comment by skoren** [comment]
That option is not documented because it's currently not used, it's a placeholder so for now, changing it won't matter. In general the save options increase disk usage, often significantly, and unless you're after very specific debugging of steps aren't useful.
