### ISSUE TITLE
Bug report: canu should check `stopAfter` before throwing errors on not-enough resources

### ISSUE THREAD

**Issue by SHuang-Broad** [marbl/canu#1536]
My command running canu (requesting to stop after haplotyping) on my local machine:

```bash
canu \
  -haplotype \
  -p ${assembly_name} \
  -d ${output_prefix} \
  genomeSize=${genome_size_gbases_estimate}G \
  -haplotypeFather father/*.fastq.gz \
  -haplotypeMother mother/*.fastq.gz \
  -pacbio-raw child/*.fastq.gz
```

But I got the following complaint from canu about not enough memory for "read error detection", even though I requested the workflow to stop before that step.
(Of course, the assumption is that the order defined [here](https://github.com/marbl/canu/blob/19560b269db9bf87419fdc40af0974376da2712e/src/pipelines/canu/Defaults.pm#L940) is the order in which jobs are to be executed.)
```
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_232' (from '/usr/local/openjdk-8/bin/java') with -d64 support.
--
-- WARNING:
-- WARNING:  Failed to run gnuplot using command 'gnuplot'.
-- WARNING:  Plots will be disabled.
-- WARNING:
--
-- Detected 16 CPUs and 31 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
-- ERROR
-- ERROR
-- ERROR  Found 1 machine configuration:
-- ERROR    class0 - 1 machines with 16 cores with 31 GB memory each.
-- ERROR
-- ERROR  Task red can't run on any available machines.
-- ERROR  It is requesting:
-- ERROR    redMemory=32-48 memory (gigabytes)
-- ERROR    redThreads=4-8 threads
-- ERROR
-- ERROR  No available machine configuration can run this task.
-- ERROR
-- ERROR  Possible solutions:
-- ERROR    Change redMemory and/or redThreads
-- ERROR

ABORT:
ABORT: Canu branch v1.9 +386 changes (r9596 53267dcc72639b3d0dabb0d8ca4a9acf7c2f47e1)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   task red failed to find a configuration to run on.
ABORT:
```

Most likely relevant code is in
`src/pipelines/canu/Configure::getAllowedResources($$$$$@)`,
line [371](https://github.com/marbl/canu/blob/19560b269db9bf87419fdc40af0974376da2712e/src/pipelines/canu/Configure.pm#L371) and the looping block above it.

**Comment by brianwalenz** [comment]
Thanks!  I'm moving this to the minor bug tracker (https://github.com/marbl/canu/projects/3) so the more critical issues aren't hidden in the issue tracker.

Send me an email, please.  brian.walenz@nih.gov.

**Comment by SHuang-Broad** [comment]
Thanks Brian!
I've copied down your email address now, email to follow later.
And may I suggest removing your email address in the comment (to avoid potential spammers)?
