### ISSUE TITLE
More robust criteria for `haplotypeReadsExist` in src/pipelines/canu/HaplotypeReads.pm

### ISSUE THREAD

**Issue by SHuang-Broad** [marbl/canu#1538]
My workflow failed in a previous run, in which I requested it to stopAfter haplotyping the reads, due to an out-of-memory error (see below if that is useful)
I then allocated more memory to my machine and run the same command again (i.e. stopAfter haplotyping the reads), but received the error 
```
ABORT:
ABORT: Canu branch v1.9 +383 changes (r9593 5c68cb93ef0cd11fd1802f4c1a9f90d2f87a2ff6)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   can't open 'haplotype/haplotype.log' for reading: No such file or directory.
ABORT:
```

This error was triggered [here](https://github.com/marbl/canu/blob/975e476610fae7ad15793d80dbf831f284830709/src/pipelines/canu.pl#L809), while the pipeline should resume [here](https://github.com/marbl/canu/blob/975e476610fae7ad15793d80dbf831f284830709/src/pipelines/canu.pl#L784).

There are two aspects that I think can be improved:
  * in `src/pipelines/canu/HaplotypeReads.haplotypeReadsExist`, which only checks that haplotyped reads "fasta.gz" exists. I think it should check something like `haplotype.success` too, to make sure that whatever is in those `fasta.gz` files are not corrupted
  * that the block below `#  If haplotype reads exist, bootstrap the assemblies.` in `canu.pl` should not execute if the user has requested to stopAfter haplotyping the reads, i.e. the user at the moment is not interested in performing later stages yet (correction, trimming, and/or assembly).

Please feel free to migrate this ticket to a minor-issue tracking system, as this is non-critical.

------------------

#### out-of-memory error message from 1st run
```
cat splitHaplotype.000001.out

Found perl:
   /usr/bin/perl
   This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-gnu-thread-multi

Found java:
   /usr/lib/jvm/java-8-oracle/bin/java
   java version "1.8.0_201"

Found canu:
   /home/shuang/bin/canu/Linux-amd64/bin/canu
   Canu branch v1.9 +383 changes (r9593 5c68cb93ef0cd11fd1802f4c1a9f90d2f87a2ff6)

Running job 1 based on command line options.
--
-- Loading haplotype data, using up to 8 GB memory for each.
--
--  Haplotype './0-kmers/haplotype-Father.meryl':
--   use kmers with frequency at least 13.

 p       prefixes             bits gigabytes (allowed: 8 GB)
-- -------------- ---------------- ---------
16          65536       2243487478     0.261
17         131072       2209073279     0.257
18         262144       2178853384     0.254
19         524288       2157022097     0.251
20        1048576       2151968026     0.251 (smallest)
21        2097152       2180468387     0.254
22        4194304       2276077612     0.265
23        8388608       2505904565     0.292
24       16777216       3004166974     0.350
25       33554432       4039300295     0.470
26       67108864       6148175440     0.716
27      134217728      10404534233     1.211
28      268435456      18955860322     2.207
29      536870912      36097121003     4.202 (used)
30     1073741824      70418250868     8.198
31     2147483648     139099119101    16.193
32     4294967296     276499464070    32.189
33     8589934592     551338762511    64.184
-- -------------- ---------------- ---------

For 38608503 distinct 21-mers (with 29 bits used for indexing and 13 bits for tags):
    4.202 GB memory
    4.000 GB memory for index (536870912 elements 64 bits wide)
    0.058 GB memory for tags  (38608503 elements 13 bits wide)
    0.144 GB memory for data  (38608503 elements 32 bits wide)

Will load 38608503 kmers.  Skipping 8171640299 (too low) and 0 (too high) kmers.
Allocating space for 38608503 suffixes of 13 bits each -> 501910539 bits (0.058 GB) in blocks of 32.000 MB
                     38608503 values   of 32 bits each -> 1235472096 bits (0.144 GB) in blocks of 32.000 MB
Loaded 38608503 kmers.  Skipped 8171640299 (too low) and 0 (too high) kmers.
--   loaded 38608503 kmers.
--  Haplotype './0-kmers/haplotype-Mother.meryl':
--   use kmers with frequency at least 1.

 p       prefixes             bits gigabytes (allowed: 8 GB)
-- -------------- ---------------- ---------
23        8388608     427734112004    49.795
24       16777216     419894566424    48.882
25       33554432     412591891756    48.032
26       67108864     406362958912    47.307
27      134217728     402281509716    46.832 (smallest)
28      268435456     402495027816    46.857
29      536870912     411298480508    47.881
30     1073741824     437281802384    50.906
31     2147483648     497624862628    57.931
32     4294967296     626687399608    72.956
-- -------------- ---------------- ---------

Not enough memory to load 8376416492 distinct 21-kmers.
Need at least 46.832 GB memory.
```

**Comment by skoren** [comment]
I think it would make sense to move the success file in the checks, that is have it be:

```
    if (! -e "./haplotype/haplotyping.success") {
```

and

```
    if ((-e "./haplotype/haplotyping.success") &&
        (haplotypeReadsExist($asm, @haplotypes) eq "yes")) {
```

The block below will stop prior to running the assembly, but it makes sense to output the report from that block (the fraction of unclassified reads/etc) even if a user isn't running the assembly yet.

**Comment by brianwalenz** [comment]
Three issues here.


Canu will now check that 'haplotyping.success' exists before claiming haplotypeReadsExist() is "yes".


The various stopAfter all all have the feature that they will only stop if the stage is actually started.  They were mode for debugging than production use.  To run only the haplotype stage, use option '-haplotype' -- other similar options exist: -correct, -trim, -assemble and -trim-assemble.


The out of memory is troubling.  Father kmers look normal:
```
--  Haplotype './0-kmers/haplotype-Father.meryl':
--   use kmers with frequency at least 13.
```
but Mother kmers do not:
```
--  Haplotype './0-kmers/haplotype-Mother.meryl':
--   use kmers with frequency at least 1.
```
Can you send the two `haplotype/0-kmers/*statistics` files for analysis?  Either attach here or email.

**Comment by SHuang-Broad** [comment]
Thanks Brian and Sergey.

The stats are attached below.
[father.mother.stats.tar.gz](https://github.com/marbl/canu/files/3810995/father.mother.stats.tar.gz)

**Comment by brianwalenz** [comment]
...and I missed seeing the data until now.  Thanks, there was a bit of a bug in processing the mother histogram.
