### ISSUE TITLE
Seeking help in understanding two functions in `src/pipelines/canu`

### ISSUE THREAD

**Issue by SHuang-Broad** [marbl/canu#1542]
I have two questions regarding canu's `Configure` module and `Execution` module.

I'd appreciate it if you can help me understand the logic there.

----------

### `canu::Configure::getAllowedResources`
The first question is about the reason for allowing recursive calls to `src/pipelines/canu/Configure getAllowedResources`. I see that the condition for triggering the recursion is when a local variable `$bestCoresM` is undefined. I don't quite understand under which scenario could this happen. And when the recursion gets triggered, essentially it is trying to go through the process again with debugging information printed out.Is that correct?

----------

### `canu::Execution::schedulerFinish`

The second question is about [this block](https://github.com/marbl/canu/blob/7cb717cd145d0cb3ac7bf33a6d201c433fd60b9b/src/pipelines/canu/Execution.pm#L246) in `Execution.pm`. My understanding is that the tasks are submitted in batches, where the batch size is the number of concurrent tasks allowed `$numberOfProcesses`. What I don't quite understand is the following (questions in the comment):

```perl
if ($remain > 0) {
    $child = waitpid -1, 0;

    undef @newProcesses;
    foreach my $i (@processesRunning) {
        # when is the following condition true?
        push @newProcesses, $i if ($child != $i);
    }
    # why is @processesRunning cleared?
    undef @processesRunning;
    @processesRunning = @newProcesses;
}
```

Thank you very much!

**Comment by brianwalenz** [comment]
Hi-

getAllowedResources:

The recursion is purely for diagnostic outputs.  It's triggered when some module requests resources that aren't available with the machines Canu can use.  An example where I request 256 GB memory for bogart, but the machine only has 128 GB:
```
> canu -p a -d a useGrid=false genomeSize=5m -pacbio READS/p6/*xz batMemory=256g
-- Canu snapshot v1.8 +494 changes (r9704 ff82c6586203bd2626df2e249d6db775a4f4e360)
--
[...]
-- Detected 24 CPUs and 128 gigabytes of memory.
--
-- ERROR
-- ERROR
-- ERROR  Found 1 machine configuration:
-- ERROR    class0 - 1 machines with 24 cores with 128 GB memory each.
-- ERROR
-- ERROR  Task bat can't run on any available machines.
-- ERROR  It is requesting:
-- ERROR    batMemory=256g memory (gigabytes)
-- ERROR    batThreads=2-4 threads
-- ERROR
-- ERROR  No available machine configuration can run this task.
-- ERROR
-- ERROR  Possible solutions:
-- ERROR    Change batMemory and/or batThreads
-- ERROR

ABORT:
ABORT: Canu snapshot v1.8 +494 changes (r9704 ff82c6586203bd2626df2e249d6db775a4f4e360)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   task bat failed to find a configuration to run on.
ABORT:
```

I'm disappointed that it fails so soon.  It would have been nice to generate the normal output, and then fail.

schedulerFinish:


The waitpid call waits for any child process to complete, then returns the pid of that process into $child.  We then loop through all processes in our list of running processes and save all but the just-completed process to a new list.  Then this new list is replaces the list of running processes.

Aside: this particular block of code is almost 17 years old!  The implementation is definitely a little odd -- why didn't I use a hash -- but it is at least well tested.  The very first version is still around.  https://sourceforge.net/p/kmer/code/5/tree//trunk/scripts/libBri.pm.
