### ISSUE TITLE
undefined reference to `GOMP_loop_nonmonotonic_dynamic_start'

### ISSUE THREAD

**Issue by tseemann** [marbl/canu#1547]
Trying to build brew package for v1.9.
I think maybe the issue is link order, the order of libs in the command line?

```
# COMMAND CAUSING ERROR 

g++-9
-o
/tmp/canu-20191106-13449-v8msc/canu-1.9/Linux-amd64/bin/sequence
-D_GLIBCXX_PARALLEL
-pthread
-fopenmp
-lm
-L/tmp/canu-20191106-13449-v8msc/canu-1.9/Linux-amd64/lib
/tmp/canu-20191106-13449
-v8msc/canu-1.9/Linux-amd64/obj/bin/sequence/sequence/sequence.o
/tmp/canu-20191106-13449-v8msc/can
u-1.9/Linux-amd64/obj/bin/sequence/sequence/sequence-extract.o
/tmp/canu-20191106-13449-v8msc/canu-1.9/Linux-amd64/obj/bin/sequence/sequence/sequence-generate.o
/tmp/canu-20191106-13449-v8msc/canu-1
.9/Linux-amd64/obj/bin/sequence/sequence/sequence-mutate.o
/tmp/canu-20191106-13449-v8msc/canu-1.9/
Linux-amd64/obj/bin/sequence/sequence/sequence-sample.o
/tmp/canu-20191106-13449-v8msc/canu-1.9/Linux-amd64/obj/bin/sequence/sequence/sequence-shiftregister.o
/tmp/canu-20191106-13449-v8msc/canu-1.9
/Linux-amd64/obj/bin/sequence/sequence/sequence-simulate.o
/tmp/canu-20191106-13449-v8msc/canu-1.9/Linux-amd64/obj/bin/sequence/sequence/sequence-summarize.o
-lcanu

# ERROR

/home/linuxbrew/.linuxbrew/bin/ld: /tmp/canu-20191106-13449-v8msc/canu-1.9/Linux-amd64/lib/libcanu.
a(kmers-exact.o): in function `kmerCountExactLookup::count() [clone ._omp_fn.0]':
kmers-exact.C:(.text+0x1975): undefined reference to `GOMP_loop_nonmonotonic_dynamic_start'
/home/linuxbrew/.linuxbrew/bin/ld: kmers-exact.C:(.text+0x1d27): undefined reference to `GOMP_loop_
nonmonotonic_dynamic_next'
/home/linuxbrew/.linuxbrew/bin/ld: /tmp/canu-20191106-13449-v8msc/canu-1.9/Linux-amd64/lib/libcanu.
a(kmers-exact.o): in function `kmerCountExactLookup::load() [clone ._omp_fn.0]':
kmers-exact.C:(.text+0x1f88): undefined reference to `GOMP_loop_nonmonotonic_dynamic_start'
/home/linuxbrew/.linuxbrew/bin/ld: kmers-exact.C:(.text+0x2623): undefined reference to `GOMP_loop_
nonmonotonic_dynamic_next'
collect2: error: ld returned 1 exit status
make: *** [Makefile:707: /tmp/canu-20191106-13449-v8msc/canu-1.9/Linux-amd64/bin/meryl-lookup] Error 1
```

```

**Comment by skoren** [comment]
Seems more like a compiler not including openmp by default, what compiler is this? What if you add -lgomp? Also, why not just use the pre-compiled binary rather than re-compiling on a user's system, that's kind of the point of the binary release.

**Comment by tseemann** [comment]
Brew and Conda do not package existing binaries. as they will not link against the correct libraries. A large number of bioinformatics users in the world use conda or brew, and most pipelines use conda now. I will look into the `libgomp` issue. We had no problem with v1.8.

**Comment by skoren** [comment]
The whole point of a binary is that it avoids users having to have correct libraries, there's nothing to link against, it's included in the distribution. I've not yet found a system where the binaries don't work. The reason for g++-7 is because 5 has spotty support for some g+11 features. I've built locally with either 9.2.0 or 7.4.1 with no errors so there is something different about your gcc.

This is my problem with brew and conda, they add unnecessary complexity for a package with no dependencies. Building like this causes issues when people build on one system and run on another than then lacks the right OS libraries or the compilations silently fail and the user isn't alerted (as conda was doing).

**Comment by tseemann** [comment]
Most HPC centres will refuse to install binaries. 
We can't trust you haven't embedded malware :)

**Comment by skoren** [comment]
1.9 had lots of changes that made it incompatible with older compilers, but nothing particular openmp related. I meant I've built on linux with those gcc versions, on multiple linux nodes. 

As for binaries vs compilation, are the HPC folks who forbid binaries reviewing the brew and canu source code? If I can embed malware in my binary I can embed it in my code and obfuscate or in brew/conda. The home-brew for gcc is only a suggestion if you want to compile and develop, if you want to run and download the binary even on OS X, you again don't need anything, no gcc, no home-brew, just extract and run.

**Comment by tseemann** [comment]
The bioinformatics community depends on packaging systems like brew and conda. I'm just trying to help spread your good work to a wide audience, and ensure they are using the latest version with less bugs. I don't work for a HPC centre, and I don't think their policies are necessarily rational, but they do affect people's ability to use some software.

 I have nothing to gain personally from this exercise. You have citations and potentially less support question to gain. If "just use the binaries" is the only assistance you can provide, then I will seek help elsewhere, or just give up and wait for someone else to solve it for the community. It may indeed be a quirk of the Brew system, but I was hoping your expertise with complex Makefiles could provide some insight into the command line above.

**Comment by snurk** [comment]
Dear @tseemann,
Do you see the same problem on an older version of GCC and/or different machine?

**Comment by snurk** [comment]
Also Thank you for your great work. Please don't get angry about conda/brew. @skoren just really hates them (we are still not sure why) :)

**Comment by tseemann** [comment]
@snurk it works with GCC-5 on brew. @sjackman is helping me. We think it is potentially trying to link against gcc5 libgomp instead of gcc9 libgomp.  Probably a brewed gcc quirk. I'll just use gcc5 given that @skoren said it was mainly for c++11 compat and not better optimization.

**Comment by snurk** [comment]
Got you! gcc5 should be OK, since we've only used the most basic c++11 features so far. I believe at some point we even compiled on GCC4.5 and it was ok.
See you in DC!

**Comment by tseemann** [comment]
I will leave it at gcc5. Thank you both :)
You can add `brew install brewsci/bio/canu` to your instructions if you like.

**Comment by tseemann** [comment]
@snurk I think @skoren is just grumpy/grouchy because you found so many important bugs :-P

**Comment by snurk** [comment]
@tseemann believe me, his grudge against conda/brew long predates my involvement! :)

**Comment by skoren** [comment]
@tseemann I appreciate your work packaging canu. I'm glad you were able to figure it out. While I could guess it was an OpenMP issue, it would never have occurred to me that it would link to the old version of openmp lib, and I obviously don't have much brew experience. Wouldn't this break every tool depending on gcc >5?

As @snurk said, I've just been burned by package managers a lot (like conda not running make clean and not checking for failed builds or conda installing a super old canu and super new JVM on OS X). I'd encourage you and others to not dismiss binaries when they're available for a tool just because some HPC admins do not want binary packages. I expect that this requirement is relatively rare, I've personally not encountered such a cluster and it would make everyone's job easier, both for you to package and for users to install.

**Comment by tseemann** [comment]
I didn't figure it out, I just went back to gcc 5 :-)
Conda was horrible in the past, but they have fixed most of the issues you describe.
The auto-bump of canufrom 1.8 to 1.9 went flawlessly a couple of days ago in bioconda.

**Comment by sjackman** [comment]
> Wouldn't this break every tool depending on gcc >5?

My unconfirmed guess is that it breaks building from source on machines that have both brewed GCC 5 and GCC 9 installed when OpenMP is required. Surprisingly few packages require GCC > 5. The CI machines that build the precompiled binary packages would not usually have both versions of GCC installed.
