### ISSUE TITLE
canu --help returns 1 not 0

### ISSUE THREAD

**Issue by tseemann** [marbl/canu#1548]
```
% canu --help
<snip>

% echo $?
1
```

It should return 0 because I asked for help, and I got it. It was a success.

But +1 for printing to stdout - thank you!

**Comment by skoren** [comment]
Cute, it even checks for error but then always returns 1, fixed in tip. Canu -version, -option and -help all return 0 now (unless help got printed for invalid arguments):
```
% canu > /dev/null
% echo $?
0
% canu -badargument > /dev/null
% echo $?
1
% canu -help > /dev/null
% echo $?
0
% canu -options > /dev/null
% echo $?
0
% canu -defaults > /dev/null
% echo $?
0
```

**Comment by tseemann** [comment]
@skoren great!
