### ISSUE TITLE
Merging vs separating haplotypes

### ISSUE THREAD

**Issue by Malabady** [marbl/canu#1553]
Hello,

I have an assembly produced using the recommended parameters for assembling polyploidy genomes in the Q&A section of the readthedoc pages.  As expected, the size of the assembly is 2X of the genome size. Here is the relevant part of the command:

$ canu -assemble genomeSize=3.6g  -pacbio-corrected Spu.trimmedReads.fasta.gz  \
readSamplingCoverage=55 correctedErrorRate=0.045 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" \
Note: error correction and trimming steps were performed independently using the following parameters: " readSamplingCoverage=55 correctedErrorRate=0.045"

I want to produce another assembly in which the haplotypes are merged. Also, as recommended in the Q&A page, I am using the following command:

$  canu -assemble genomeSize=3.65g  -pacbio-corrected Spu.trimmedReads.fasta.gz  \
readSamplingCoverage=55  correctedErrorRate=0.15 \

My questions are:
-  Can I use the error corrected and trimmed reads that I used in diploid assembly?
-  Do I need to redo the error correction and trimming with less stringent correctedErrorRate? 

I am using Canu-1.8

Thank you.

**Comment by skoren** [comment]
You can definitely use the same corrected reads, you can probably use the same trimmed reads too. We typically don't recommend the collapse version, your consensus will suffer and you won't be able to collapse complex variants like inversions/etc anyway (just simple bubbles). Instead, we typically run purge_dups to remove the duplication from the assembly to get a set of "primary" and alts.
