### ISSUE TITLE
Canu v1.8 Index error

### ISSUE THREAD

**Issue by cssanchez23** [marbl/canu#1554]
Hello, 
Below is the command that I used to run canu 
**canu -p art24 -d art24 genomeSize=4.5M -pacbio XBCOM_20191025_S54024R1_PL100142225-1_B01.subreads.fastq**

My  `canu -version` = Canu snapshot v1.8 +516 changes (r9726 0375de8a1da13f23cf583a5fd30811e21ed72b81)

I ran Canu on an AWS instance using Linux. I have rerun this script multiple times however I receive the same error. 

Below is a screenshot of the error that I am receiving. 

<img width="1230" alt="Screen Shot 2019-11-06 at 1 42 11 PM" src="https://user-images.githubusercontent.com/18295083/68488873-9a9b8280-020b-11ea-97ca-f295e363c59a.png">

Please let me know if anything else is needed,
THank you

**Comment by skoren** [comment]
This looks like you've got disk corruption in your run. However, rather than fixing this run, I would suggest switching to the 1.9 release rather than a checked out version that you're using now. Run the assembly from scratch with the 1.9 release and post if it runs into the same error.

**Comment by skoren** [comment]
Idle, fixed in the release version.
