### ISSUE TITLE
Canu 1.9 Linux error

### ISSUE THREAD

**Issue by GenerGener** [marbl/canu#1555]
```
ERROR:  Failed with exit code 127.  (rc=32512)
ERROR:

ABORT:
ABORT: 
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   sqStoreCreate failed.
ABORT:
ABORT: Disk space available:  443.902 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (./canu.seqStore.BUILDING.err):
ABORT:
ABORT:   sh: line 1: /Users/alejandrogener/Downloads/canu-1.9/sqStoreCreate: No such file or directory
```

**Comment by skoren** [comment]
Your installation looks broken, the sqStoreCreate file should not exist in the top-level canu directory but in something like Linux-amd64/bin. The only way I can see that happening is if the canu script was moved from its original location. How did you download/get canu on your system? What's the command you're using?

**Comment by GenerGener** [comment]
Thanks for quick reply!

/Users/alejandrogener/Downloads/canu-1.9/Linux-amd64/bin/canu -p canu -d 89.6_HIV_native_RNA_for_AIDS genomeSize=9k -nanopore-raw /Users/alejandrogener/Downloads/Galaxy804-896.fastq

I just downloaded. Didn't move.

(base) Alejandros-MacBook-Pro-3:src alejandrogener$ cd /Users/alejandrogener/Downloads/canu-1.9 
(base) Alejandros-MacBook-Pro-3:canu-1.9 alejandrogener$ ls -l
total 72
drwxr-xr-x@ 5 alejandrogener  staff    160 Nov  4 01:40 Linux-amd64
-rw-r--r--@ 1 alejandrogener  staff    219 Nov  4 00:18 README.citation
-rw-r--r--@ 1 alejandrogener  staff  18009 Nov  4 00:18 README.license.GPL
-rw-r--r--@ 1 alejandrogener  staff   6506 Nov  4 00:18 README.licenses
-rw-r--r--@ 1 alejandrogener  staff   1968 Nov  4 00:18 README.md

**Comment by GenerGener** [comment]
I have access to Canu 1.8 on a couple clusters. Would like to try out 1.9 though.

**Comment by skoren** [comment]
Are you on OSX and not linux? Your download is the linux binary which won't work on a mac. Download the Darwin release instead and see if that runs.

**Comment by skoren** [comment]
Idle, no response, appears to be Linux distro on OSX.
