### ISSUE TITLE
Re: cnsMaxCoverage

### ISSUE THREAD

**Issue by Malabady** [marbl/canu#1557]
Hi,

I am a bit confused about the option "cnsMaxCoverage". which one of the following cases describes it (if any)? 

1. Canu will pick longest reads that constitute an "X" coverage as defined by this option and will use them for unitgging. 
**OR**
2. Canu will use all trimmed reads (say, 80X of the genome) in the untigging, But when doing the overlap to read the consensus, it will stop at "X" coverage (as defined by this option). 

ALthough the manul says that this option is defaulted to "0" which means using all reads, the actual command is using 40

- From canu -options:

cnsMaxCoverage: Limit unitig consensus to at most this coverage; default '0' = unlimited

- From Canu readthedocs:

cnsMaxCoverage: Limit unitig consensus to at most this coverage.

- From the consensus command:
 maxcoverage 40

Thanks

**Comment by brianwalenz** [comment]
Your first case is the `corOutCoverage` option.  Canu will generate X coverage in corrected reads, by discarding the short reads.

Your second case is close.  We'll use all corrected and trimmed reads to generate contigs.  'cnsMaxCoverage' tells the consensus module to ignore short reads when computing the consensus sequence.  The shorter reads are still present in the contig layout, they just don't contribute to the consensus sequence.  It is, for the most part, a speed optimization, useful for contigs that are entirely repeats or high-coverage contamination.

I fixed the incorrect 'canu -options' output.  The default is 40.

**Comment by Malabady** [comment]
Thanks, Brian. This means that if I used "corOutCoverage=200" in the read correction parameters, all corrected and trimmed reads (about 90X in my case) will be used to generate contigs.  correct?

**Comment by skoren** [comment]
Yes, that's right all reads will be used for building the contigs.
