### ISSUE TITLE
gfa to contig

### ISSUE THREAD

**Issue by fergsc** [marbl/canu#1567]
Hi, 

Is there anyway to work out which knote in the genome graph (unitigging/4-unitigger/blah.contigs.gfa) creates which contig in the final fasta. 

Thanks.

**Comment by skoren** [comment]
I am not sure I understand what you're asking. The gfa you mention, unitigging/4-unitigger/ is an intermediate output, you should use the one produced in the top-level of the folder. However, both of those files have the same IDs as the records in the contigs fasta file. 

For unitigs, you have the bed file which tells you the unitigs making up each contig.
