### ISSUE TITLE
What is the normal range of child reads unassigned (fraction) to parent haplotypes?

### ISSUE THREAD

**Issue by SHuang-Broad** [marbl/canu#1568]
I cannot seem to get an "expected" number from [this](https://github.com/marbl/canu/blob/3a35672d72dcb86c9df854a98d800c24ad7283a3/src/pipelines/canu.pl#L822) code block.

Below is the `haplotype.log`

```
--  2302687 reads  31113662866 bases written to haplotype file ./haplotype-Father.fasta.gz.
--  2385237 reads  32232132834 bases written to haplotype file ./haplotype-Mother.fasta.gz.
--  1922168 reads  25749216015 bases written to haplotype file ./haplotype-unknown.fasta.gz.
--
--      148 reads        65011 bases filtered for being too short.
--
```

**Comment by skoren** [comment]
That depends on the genome heterozygosity and read length, the higher the zygosity or the longer the reads, the more of them will be assigned. 

You've got about an equal split between maternal/paternal/unknown and relatively short reads (at 13kb) so I'd guess this isn't a very heterozygous individual. We see this rate in older/shorter human datasets (like HG002 CCS/CLR data).

**Comment by SHuang-Broad** [comment]
HG002 CCS is exactly the data that generated this log (except that 15kb is the library that I chose for doing this analysis&mdash;public data from the CCS Nat. Biotech. paper).

So it sounds like this should not be (serious) concern.

Thanks Sergey!
