### ISSUE TITLE
rescued vs uncorrected reads

### ISSUE THREAD

**Issue by lmolokin** [marbl/canu#1570]
Hi,
What determines canu's decision to "rescue" certain reads during correction and leave others uncorrected? The documentation says rescued reads are those that are shorter than the longest 40X but it doesn't say how they differ from uncorrected reads.

The reason I ask is because I get two very different amount of reads rescued when I run two subsets of the same nanopore amplicon reads through correction that differ in the read lengths they contain. In other words:

set 1: 1000 - 2100 bp (89,141 reads)
after correction: 48,724 reads

set 2: 1600 - 2100 bp (72,360 reads)
after correction: 70,112 reads

The target amplicon length is 1700bp but I wanted to leave some wiggle room in terms of length to potentially capture novel length variants that may be in low abundance.  

I'm trying to understand why the second set with the more narrow size distribution ends up with more reads rescued versus set 1.

correction reports:
[1000-2100bp.txt](https://github.com/marbl/canu/files/3881735/1000-2100bp.txt)
[1600-2100bp.txt](https://github.com/marbl/canu/files/3881737/1600-2100bp.txt)

Thanks!

**Comment by skoren** [comment]
Canu tries to correct only the longest 40x of reads (accounting for loss in correction to reads that have no support). Reads shorter than this selected threshold can be eescued if they are not well-represented by the selected 40x of data (e.g. they have different sequence and don't share overlaps). The remainder of the shorter reads become uncorrected.

In very high coverage, the rescue tends to over-recruit reads so it ends up correcting almost everything in both your cases. I think the different isn't too important but instead I'd suggest downsampling your input randomly (canu has built-in parameters for this, see the readSamplingCoverage and readSamplingBias options).

**Comment by lmolokin** [comment]
But if I downsample, wouldn't that reduce my sensitivity for being able to detect low abundance sequences of interest?

**Comment by skoren** [comment]
Ah I missed that you were looking for low-frequency variants, in that case don't rely on rescue and explicitly ask canu to correct all the data (```corOutCoverage=all```). You probably don't need assembly, just correction and you can then cluster/compare the resulting reads.

**Comment by lmolokin** [comment]
Got it, good to know I was on the right track. 

In addition to `corOutCoverage=all`, I believe I also need to set `corMinCoverage=0` in order have all the reads corrected?

Thanks.

**Comment by lmolokin** [comment]
For reference, `corOutCoverage=all` does not seem to work. Only by explicitly giving a number that's greater than your input coverage yields the desired effect and only when combined with the parameter `corMinCoverage=0`.

**Comment by skoren** [comment]
I think you're looking at total output bases to define "works"? 

I confirmed all does work, it is equivalent to setting corOutCoverage=10000. If you have more than 10k coverage, it would end up not correcting everything. corMinCoverage=0 is unrelated to how many reads will be corrected, by setting it you will keep all bases you input. You'll keep bases even if no other read supports them, so unless you're interested in low-copy variants that exist in only a single read that's probably not what you want. The default, 4, keeps bases supported by at least 4 other reads, you could lower this to 2 or 3.
