### ISSUE TITLE
Canu 1.9: Overly long duration of the obtovl/overlap.sh step with 2 short amplicons

### ISSUE THREAD

**Issue by scogi** [marbl/canu#1573]
Hi,

I am trying to assemble two short, partially overlapping PCR fragments (6.8 kb + 2.2 kb). The fragments have been mixed equimolarly and sequenced on a Nanopore MinION system (LSK109 ligation library). Both fragments are covered by about 10,000-15,000, more or less full length reads. We need an as error free as possible (assembled) consensus sequence of these two fragments, that is why we are assembling with canu. 

Setup: 
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.7.1908 (Core)
Release:	7.7.1908
Canu 1.9
20 CPU cores, 80 GB of RAM , 4.6 TB of free disk space

Canu command:

```
canu \
 -d canu/barcode02/ \
 -p 2_6.b01_filter.canu \
 genomeSize=10k \
 executiveMemory=32 \
 executiveThreads=12 \
 -nanopore-raw `barcode02/barcode02_filtered.fastq
```

The fastq already contains only reads that have been filtered at +/- 200 bp the correct length of each amplicon (length filtering using reformat.sh of the BBmap package)

While the first steps of canu have run though quite fast (3 hours), the step "Starting 'obtovl'" (overlap.sh) is taking extremely long (16 hours since start and still running at this moment). Indeed, there are still 4 cores fully working and the 4 processes "overlapInCore -partial -t 5 -k 22 -k ../0-mercounts/2_6.b01_filter.canu.ms"  been now been running since 20 hours each. 
After 20 hours the  overlap.000001.out  file contains:

```
$ tail -f overlap.000001.out 
Thread 00 writes    reads 26176-27222 (40601 overlaps 1569751/38863/0 kmer hits with/without overlap/skipped)
Thread 00 processes reads 31411-32457
Thread 02 writes    reads 30364-31410 (4058 overlaps 1183688/4876/0 kmer hits with/without overlap/skipped)
Thread 02 processes reads 32458-33504
Thread 01 writes    reads 29317-30363 (22675 overlaps 1377065/3924/0 kmer hits with/without overlap/skipped)
Thread 01 processes reads 33505-34551
Thread 04 writes    reads 28270-29316 (9437 overlaps 1276447/3594/0 kmer hits with/without overlap/skipped)
Thread 04 processes reads 34552-35598
Thread 03 writes    reads 27223-28269 (27160 overlaps 1337860/4047/0 kmer hits with/without overlap/skipped)
Thread 03 processes reads 35599-36645
```
(the input fastq contains 41865 sequences)

and seems to receive one line every 4-6 hours or so. This seems very long to me, but I have no previous experience with such a setup and data structure, though. Is this expected with such data or is something wrong going on here? Thank you for any help!

Stefan

**Comment by skoren** [comment]
I'd guess you still have extremely high coverage of the data, the report output from canu would give more details on that. Canu has built-in parameters for this, see the readSamplingCoverage and readSamplingBias options. You don't need more than 100x or so input data for this.

**Comment by scogi** [comment]
Thank you. I was suspecting so. I re-ran the command with only 100 randomly extracted reads per amplicon. Canu runs now very fast, but ends with error code 1 "no input tig files supplied on command line or via -L option."

Command is
`canu  -d canu/barcode02/  -p 2_6.b01_filter.canu  genomeSize=10k  executiveMemory=32  executiveThreads=12  -nanopore-raw fastq/barcode02_both_100.fastq`

consensus.000001.out reads:
```
Found perl:
   /usr/bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /usr/bin/java
   openjdk version "1.8.0_232"

Found canu:
   /opt/tools/genetics/canu/canu-1.9/Linux-amd64/bin/canu
   Canu 1.9

Running job 1 based on command line options.
-- Opening seqStore '../pig2_6.b01_filter.canu.ctgStore/partitionedReads.seqStore' partition 1.
-- Opening tigStore '../pig2_6.b01_filter.canu.ctgStore' version 1.
-- Opening output results file './ctgcns/0001.cns.WORKING'.
--
-- Computing consensus for b=0 to e=148 with errorRate 0.2000 (max 0.4000) and minimum overlap 40
--
Consensus finished successfully.

Bye.
                           ----------CONTAINED READS----------  -DOVETAIL  READS-
  tigID    length   reads      used coverage  ignored coverage      used coverage
------- --------- -------  -------- -------- -------- --------  -------- --------

Processed 0 tigs and 146 singletons.
```

The screen output is

`-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'cns' concurrent execution on Thu Nov 28 11:33:46 2019 with 4487.318 GB free disk space (1 processes; 5 concurrently)

    cd unitigging/5-consensus
    ./consensus.sh 1 > ./consensus.000001.out 2>&1

-- Finished on Thu Nov 28 11:33:48 2019 (2 seconds) with 4487.285 GB free disk space
----------------------------------------
-- Using slow alignment for consensus (iteration '1').
-- Configured 1 contig and 0 unitig consensus jobs.
-- No change in report.
-- All 1 consensus jobs finished successfully.
-- No change in report.
-- Finished stage 'consensusCheck', reset canuIteration.
-- Using slow alignment for consensus (iteration '0').
-- Configured 1 contig and 0 unitig consensus jobs.
-- No change in report.
----------------------------------------
-- Starting command on Thu Nov 28 11:33:48 2019 with 4487.285 GB free disk space

    cd unitigging
    /opt/tools/genetics/canu/canu-1.9/Linux-amd64/bin/tgStoreLoad \
      -S ../pig2_6.b01_filter.canu.seqStore \
      -T  ./pig2_6.b01_filter.canu.ctgStore 2 \
      -L ./5-consensus/ctgcns.files \
    > ./5-consensus/ctgcns.files.ctgStoreLoad.err 2>&1

-- Finished on Thu Nov 28 11:33:49 2019 (one second) with 4487.284 GB free disk space
----------------------------------------
----------------------------------------
-- Starting command on Thu Nov 28 11:33:49 2019 with 4487.284 GB free disk space

    cd unitigging
    /opt/tools/genetics/canu/canu-1.9/Linux-amd64/bin/tgStoreLoad \
      -S ../pig2_6.b01_filter.canu.seqStore \
      -T  ./pig2_6.b01_filter.canu.utgStore 2 \
      -L ./5-consensus/utgcns.files \
    > ./5-consensus/utgcns.files.utgStoreLoad.err 2>&1

-- Finished on Thu Nov 28 11:33:49 2019 (lickety-split) with 4487.284 GB free disk space
----------------------------------------

ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:

ABORT:
ABORT: Canu 1.9
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to load unitig consensus into utgStore.
ABORT:
(...)
`
As far as i understand there es no unitig created, but unfortunately I could not  figure out what the precise problem is (I am new to assmbling). The two amplicons overlap by several 100 bp, as far as we now. So assembly should be possible. Coudl it be a problem that only two overlapping fragments are provided? Thank you

**Comment by gringer** [comment]
I think Canu used to have a setting enabled where a new contig wouldn't be assembled if it were only a little bit larger than a single read. It might be that your reads are already so well assembled that Canu has nothing to do.

**Comment by skoren** [comment]
I'd guess there is nothing to assemble, if all your reads contain both amplicons. Your description of the amplicon isn't clear, are they expected to be in a single read or are you looking for Canu to assemble them together? It looks like in your case there is no end-to-end overlap between any reads which would be the case if all the corrected reads are the amplicons full-length. 

In that case, you can just take a single corrected read, that'll be the best consensus you'll get anyway for the amplicon. You can also look at the filtering parameters on the FAQ: https://canu.readthedocs.io/en/latest/faq.html#my-asm-contigs-fasta-is-empty-why, setting contigFilter="1 0 1.0 0.5 0" will  promote the reads to contigs but won't change their consensus.

**Comment by scogi** [comment]
I see. Thank you all.
