### ISSUE TITLE
Error: Read coverage(6.18) is too low to be useful

### ISSUE THREAD

**Issue by huizhen2014** [marbl/canu#1574]
Hello, When I used canu to assemble my Acinetobacter baumannii genome, I encountered an error, which said "the read coverage(6.18) is too low to be useful". I tried again with the same error output, and I could not figure out why, So I want to get some solutions or tips. This is my code:
canu -p icu43_100x -d icu43_100x \
-pacbio-raw ICU43_subreads.fastq \
genomeSize=4m \
minReadLength=2000 \
corOutCoverage=100 \
correctedErrorRate=0.040

Since my fastq file is big enough, I selected a little stringent value for correctedErrorRate, and here is my fastq volume(I will write the codes and results instead of the pic):

sed -n '2~4p' ICU43_subreads.fastq | gawk '{len+=length($0)}END{print len/((1024)^2)}' 
which prints: 699.949 

Thanks !

**Comment by huizhen2014** [comment]
Oh, I forgot that the version of my canu is 1.9.

**Comment by skoren** [comment]
I'd guess your reads are either too short or too low quality to be reducing the error rate. Post the full report file generated from the run.

**Comment by huizhen2014** [comment]
I am afraid it is too long and this window will be overwhelmed. 
-- Canu 1.9
--
-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
--
-- Koren S, Rhie A, Walenz BP, Dilthey AT, Bickhart DM, Kingan SB, Hiendleder S, Williams JL, Smith TPL, Phillippy AM.
-- De novo assembly of haplotype-resolved genomes with trio binning.
-- Nat Biotechnol. 2018
-- https//doi.org/10.1038/nbt.4277
--
-- Read and contig alignments during correction, consensus and GFA building use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
--
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
--
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
--
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
--
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
--
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_221' (from '/Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home/bin/java') with -d64 support.
-- Detected gnuplot version '5.2 patchlevel 6   ' (from 'gnuplot') and image format 'png'.
-- Detected 4 CPUs and 8 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |     total usage     algorithm
--        -------  ------  --------   --------  -----------------  -----------------------------
-- Local: meryl      8 GB    4 CPUs x   1 job      8 GB    4 CPUs  (k-mer counting)
-- Local: hap        8 GB    4 CPUs x   1 job      8 GB    4 CPUs  (read-to-haplotype assignment)
-- Local: cormhap    6 GB    4 CPUs x   1 job      6 GB    4 CPUs  (overlap detection with mhap)
-- Local: obtovl     4 GB    4 CPUs x   1 job      4 GB    4 CPUs  (overlap detection)
-- Local: utgovl     4 GB    4 CPUs x   1 job      4 GB    4 CPUs  (overlap detection)
-- Local: cor        8 GB    4 CPUs x   1 job      8 GB    4 CPUs  (read correction)
-- Local: ovb        4 GB    1 CPU  x   2 jobs     8 GB    2 CPUs  (overlap store bucketizer)
-- Local: ovs        8 GB    1 CPU  x   1 job      8 GB    1 CPU   (overlap store sorting)
-- Local: red        8 GB    4 CPUs x   1 job      8 GB    4 CPUs  (read error detection)
-- Local: oea        8 GB    1 CPU  x   1 job      8 GB    1 CPU   (overlap error adjustment)
-- Local: bat        8 GB    4 CPUs x   1 job      8 GB    4 CPUs  (contig construction with bogart)
-- Local: cns      --- GB    4 CPUs x --- jobs   --- GB  --- CPUs  (consensus)
-- Local: gfa        8 GB    4 CPUs x   1 job      8 GB    4 CPUs  (GFA alignment and processing)
--
-- Found PacBio uncorrected reads in the input files.
--
-- Generating assembly 'icu43_100x' in '/Data_analysis/PacBio_analysis/icu43_100x'
--
-- Parameters:
--
--  genomeSize        4000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0400 (  4.00%)
--    utgOvlErrorRate 0.0400 (  4.00%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0400 (  4.00%)
--    utgErrorRate    0.0400 (  4.00%)
--    cnsErrorRate    0.0400 (  4.00%)
--
--
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Sun Dec  1 21:39:54 2019 with 61.741 GB free disk space

    cd .
    /Users/carlos/Bin/canu-1.9/Darwin-amd64/bin/sqStoreCreate \
      -o ./icu43_100x.seqStore.BUILDING \
      -minlength 2000 \
      ./icu43_100x.seqStore.ssi \
    > ./icu43_100x.seqStore.BUILDING.err 2>&1

-- Finished on Sun Dec  1 21:40:01 2019 (7 seconds) with 61.545 GB free disk space
----------------------------------------
--
-- In sequence store './icu43_100x.seqStore':
--   Found 79742 reads.
--   Found 725325000 bases (181.33 times coverage).
--
--   Read length histogram (one '*' equals 136.21 reads):
--     2000   2999   5024 ************************************
--     3000   3999   5714 *****************************************
--     4000   4999   5618 *****************************************
--     5000   5999   5677 *****************************************
--     6000   6999   5604 *****************************************
--     7000   7999   5925 *******************************************
--     8000   8999   8476 **************************************************************
--     9000   9999   9535 **********************************************************************
--    10000  10999   7155 ****************************************************
--    11000  11999   5300 **************************************
--    12000  12999   3730 ***************************
--    13000  13999   2800 ********************
--    14000  14999   2099 ***************
--    15000  15999   1491 **********
--    16000  16999   1052 *******
--    17000  17999    842 ******
--    18000  18999    615 ****
--    19000  19999    489 ***
--    20000  20999    416 ***
--    21000  21999    343 **
--    22000  22999    267 *
--    23000  23999    246 *
--    24000  24999    206 *
--    25000  25999    185 *
--    26000  26999    177 *
--    27000  27999    110
--    28000  28999    129
--    29000  29999     93
--    30000  30999     81
--    31000  31999     66
--    32000  32999     48
--    33000  33999     54
--    34000  34999     33
--    35000  35999     30
--    36000  36999     24
--    37000  37999     21
--    38000  38999     16
--    39000  39999     14
--    40000  40999     10
--    41000  41999      3
--    42000  42999      7
--    43000  43999      3
--    44000  44999      3
--    45000  45999      3
--    46000  46999      1
--    47000  47999      0
--    48000  48999      1
--    49000  49999      4
--    50000  50999      1
--    51000  51999      0
--    52000  52999      0
--    53000  53999      1
-- New report created.
----------------------------------------
-- Starting command on Sun Dec  1 21:40:02 2019 with 61.544 GB free disk space

    cd correction/0-mercounts
    ./meryl-configure.sh \
    > ./meryl-configure.err 2>&1

-- Finished on Sun Dec  1 21:40:02 2019 (fast as lightning) with 61.544 GB free disk space
----------------------------------------
--  segments   memory batches
--  -------- -------- -------
--        01  1.88 GB       1
--        02  0.94 GB       1
--        04  0.50 GB       1
--        06  0.31 GB       1
--
--  For 79742 reads with 725325000 bases, limit to 7 batches.
--  Will count kmers using 01 jobs, each using 3 GB and 4 threads.
--
-- Report changed.
-- Finished stage 'merylConfigure', reset canuIteration.
-- No change in report.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'meryl' concurrent execution on Sun Dec  1 21:40:02 2019 with 61.544 GB free disk space (1 processes; 1 concurrently)

    cd correction/0-mercounts
    ./meryl-count.sh 1 > ./meryl-count.000001.out 2>&1

-- Finished on Sun Dec  1 21:41:09 2019 (67 seconds) with 59.583 GB free disk space
----------------------------------------
-- Found 1 Kmer counting (meryl) outputs.
-- No change in report.
-- Finished stage 'cor-merylCountCheck', reset canuIteration.
-- No change in report.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'meryl' concurrent execution on Sun Dec  1 21:41:09 2019 with 59.583 GB free disk space (1 processes; 1 concurrently)

    cd correction/0-mercounts
    ./meryl-process.sh 1 > ./meryl-process.000001.out 2>&1

-- Finished on Sun Dec  1 21:42:00 2019 (51 seconds) with 60.502 GB free disk space
----------------------------------------
-- Meryl finished successfully.  Kmer frequency histogram:
--
--  16-mers                                                                                           Fraction
--    Occurrences   NumMers                                                                         Unique Total
--       1-     1         0                                                                        0.0000 0.0000
--       2-     2  74623769 ********************************************************************** 0.6004 0.3735
--       3-     4  33884069 *******************************                                        0.7930 0.5533
--       5-     7   9547510 ********                                                               0.9128 0.7147
--       8-    11   3524825 ***                                                                    0.9599 0.8134
--      12-    16   1680613 *                                                                      0.9821 0.8840
--      17-    22    630654                                                                        0.9931 0.9338
--      23-    29    207289                                                                        0.9972 0.9591
--      30-    37     83739                                                                        0.9986 0.9707
--      38-    46     41496                                                                        0.9992 0.9770
--      47-    56     23392                                                                        0.9995 0.9811
--      57-    67     14220                                                                        0.9997 0.9840
--      68-    79      8881                                                                        0.9998 0.9861
--      80-    92      5603                                                                        0.9998 0.9876
--      93-   106      3507                                                                        0.9999 0.9888
--     107-   121      2371                                                                        0.9999 0.9897
--     122-   137      1688                                                                        0.9999 0.9903
--     138-   154      1353                                                                        0.9999 0.9908
--     155-   172      1056                                                                        0.9999 0.9913
--     173-   191       797                                                                        1.0000 0.9918
--     192-   211       615                                                                        1.0000 0.9921
--     212-   232       596                                                                        1.0000 0.9924
--     233-   254       572                                                                        1.0000 0.9928
--     255-   277       487                                                                        1.0000 0.9931
--     278-   301       383                                                                        1.0000 0.9934
--     302-   326       301                                                                        1.0000 0.9937
--     327-   352       203                                                                        1.0000 0.9939
--     353-   379       182                                                                        1.0000 0.9941
--     380-   407       124                                                                        1.0000 0.9943
--     408-   436       127                                                                        1.0000 0.9944
--     437-   466       107                                                                        1.0000 0.9945
--     467-   497        70                                                                        1.0000 0.9946
--     498-   529        62                                                                        1.0000 0.9947
--     530-   562        68                                                                        1.0000 0.9948
--     563-   596        62                                                                        1.0000 0.9949
--     597-   631        79                                                                        1.0000 0.9950
--     632-   667        63                                                                        1.0000 0.9951
--     668-   704        56                                                                        1.0000 0.9952
--     705-   742        50                                                                        1.0000 0.9953
--     743-   781        40                                                                        1.0000 0.9954
--     782-   821        28                                                                        1.0000 0.9955
--
--           0 (max occurrences)
--   399560933 (total mers, non-unique)
--   124291519 (distinct mers, non-unique)
--           0 (unique mers)
-- Report changed.
-- Finished stage 'meryl-process', reset canuIteration.
--
-- Removing meryl database 'correction/0-mercounts/icu43_100x.ms16'.
--
-- OVERLAPPER (mhap) (correction)
--
-- Set corMhapSensitivity=low based on read coverage of 181.
--
-- PARAMETERS: hashes=256, minMatches=3, threshold=0.8
--
-- Given 5.4 GB, can fit 16200 reads per block.
-- For 6 blocks, set stride to 2 blocks.
-- Logging partitioning to 'correction/1-overlapper/partitioning.log'.
-- Configured 5 mhap precompute jobs.
-- Configured 7 mhap overlap jobs.
-- No change in report.
-- Finished stage 'cor-mhapConfigure', reset canuIteration.
-- No change in report.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'cormhap' concurrent execution on Sun Dec  1 21:42:01 2019 with 61.543 GB free disk space (5 processes; 1 concurrently)

    cd correction/1-overlapper
    ./precompute.sh 1 > ./precompute.000001.out 2>&1
    ./precompute.sh 2 > ./precompute.000002.out 2>&1
    ./precompute.sh 3 > ./precompute.000003.out 2>&1
    ./precompute.sh 4 > ./precompute.000004.out 2>&1
    ./precompute.sh 5 > ./precompute.000005.out 2>&1

-- Finished on Sun Dec  1 22:34:33 2019 (3152 seconds) with 58.168 GB free disk space
----------------------------------------
-- All 5 mhap precompute jobs finished successfully.
-- No change in report.
-- Finished stage 'cor-mhapPrecomputeCheck', reset canuIteration.
-- No change in report.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'cormhap' concurrent execution on Sun Dec  1 22:34:33 2019 with 58.168 GB free disk space (7 processes; 1 concurrently)

    cd correction/1-overlapper
    ./mhap.sh 1 > ./mhap.000001.out 2>&1
    ./mhap.sh 2 > ./mhap.000002.out 2>&1
    ./mhap.sh 3 > ./mhap.000003.out 2>&1
    ./mhap.sh 4 > ./mhap.000004.out 2>&1
    ./mhap.sh 5 > ./mhap.000005.out 2>&1
    ./mhap.sh 6 > ./mhap.000006.out 2>&1
    ./mhap.sh 7 > ./mhap.000007.out 2>&1

-- Finished on Sun Dec  1 22:36:24 2019 (111 seconds) with 58.16 GB free disk space
----------------------------------------
-- Found 7 mhap overlap output files.
-- No change in report.
-- Finished stage 'cor-mhapCheck', reset canuIteration.
----------------------------------------
-- Starting command on Sun Dec  1 22:36:24 2019 with 58.16 GB free disk space

    cd correction
    /Users/carlos/Bin/canu-1.9/Darwin-amd64/bin/ovStoreConfig \
     -S ../icu43_100x.seqStore \
     -M 4-8 \
     -L ./1-overlapper/ovljob.files \
     -create ./icu43_100x.ovlStore.config \
     > ./icu43_100x.ovlStore.config.txt \
    2> ./icu43_100x.ovlStore.config.err

-- Finished on Sun Dec  1 22:36:24 2019 (in the blink of an eye) with 58.16 GB free disk space
----------------------------------------
--
-- Creating overlap store correction/icu43_100x.ovlStore using:
--      2 buckets
--      2 slices
--        using at most 1 GB memory each
-- No change in report.
-- Finished stage 'cor-overlapStoreConfigure', reset canuIteration.
-- No change in report.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'ovB' concurrent execution on Sun Dec  1 22:36:24 2019 with 58.16 GB free disk space (2 processes; 2 concurrently)

    cd correction/icu43_100x.ovlStore.BUILDING
    ./scripts/1-bucketize.sh 1 > ./logs/1-bucketize.000001.out 2>&1
    ./scripts/1-bucketize.sh 2 > ./logs/1-bucketize.000002.out 2>&1

-- Finished on Sun Dec  1 22:36:25 2019 (one second) with 58.157 GB free disk space
----------------------------------------
-- Overlap store bucketizer finished.
-- No change in report.
-- Finished stage 'cor-overlapStoreBucketizerCheck', reset canuIteration.
-- No change in report.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'ovS' concurrent execution on Sun Dec  1 22:36:25 2019 with 58.157 GB free disk space (2 processes; 1 concurrently)

    cd correction/icu43_100x.ovlStore.BUILDING
    ./scripts/2-sort.sh 1 > ./logs/2-sort.000001.out 2>&1
    ./scripts/2-sort.sh 2 > ./logs/2-sort.000002.out 2>&1

-- Finished on Sun Dec  1 22:36:26 2019 (one second) with 58.146 GB free disk space
----------------------------------------
-- Overlap store sorter finished.
-- No change in report.
-- Finished stage 'cor-overlapStoreSorterCheck', reset canuIteration.
----------------------------------------
-- Starting command on Sun Dec  1 22:36:26 2019 with 58.146 GB free disk space

    cd correction
    /Users/carlos/Bin/canu-1.9/Darwin-amd64/bin/ovStoreIndexer \
      -O  ./icu43_100x.ovlStore.BUILDING \
      -S ../icu43_100x.seqStore \
      -C  ./icu43_100x.ovlStore.config \
      -delete \
    > ./icu43_100x.ovlStore.BUILDING.index.err 2>&1

-- Finished on Sun Dec  1 22:36:26 2019 (lickety-split) with 58.149 GB free disk space
----------------------------------------
-- Checking store.
----------------------------------------
-- Starting command on Sun Dec  1 22:36:26 2019 with 58.149 GB free disk space

    cd correction
    /Users/carlos/Bin/canu-1.9/Darwin-amd64/bin/ovStoreDump \
     -S ../icu43_100x.seqStore \
     -O  ./icu43_100x.ovlStore \
     -counts \
     > ./icu43_100x.ovlStore/counts.dat 2> ./icu43_100x.ovlStore/counts.err

-- Finished on Sun Dec  1 22:36:26 2019 (in the blink of an eye) with 58.148 GB free disk space
----------------------------------------
--
-- Overlap store 'correction/icu43_100x.ovlStore' successfully constructed.
-- Found 145598 overlaps for 34930 reads; 44812 reads have no overlaps.
--
--
-- Purged 1.35 GB in 19 overlap output files.
-- No change in report.
-- Finished stage 'cor-createOverlapStore', reset canuIteration.
-- Set corMinCoverage=4 based on read coverage of 181.
-- Global filter scores will be estimated.
-- Computing correction layouts.
----------------------------------------
-- Starting command on Sun Dec  1 22:36:26 2019 with 59.513 GB free disk space

    cd correction
    /Users/carlos/Bin/canu-1.9/Darwin-amd64/bin/generateCorrectionLayouts \
      -S ../icu43_100x.seqStore \
      -O  ./icu43_100x.ovlStore \
      -C  ./icu43_100x.corStore.WORKING \
      -eC 200 \
    > ./icu43_100x.corStore.err 2>&1

-- Finished on Sun Dec  1 22:36:26 2019 (fast as lightning) with 59.502 GB free disk space
----------------------------------------
-- No change in report.
-- Finished stage 'cor-buildCorrectionLayoutsConfigure', reset canuIteration.
-- Computing correction layouts.
----------------------------------------
-- Starting command on Sun Dec  1 22:36:26 2019 with 59.502 GB free disk space

    cd correction/2-correction
    /Users/carlos/Bin/canu-1.9/Darwin-amd64/bin/filterCorrectionLayouts \
      -S  ../../icu43_100x.seqStore \
      -C     ../icu43_100x.corStore \
      -R      ./icu43_100x.readsToCorrect.WORKING \
      -cc 4 \
      -cl 2000 \
      -g  4000000 \
      -c  100 \
    > ./icu43_100x.readsToCorrect.err 2>&1

-- Finished on Sun Dec  1 22:36:27 2019 (one second) with 59.497 GB free disk space
----------------------------------------
--                             original      original
--                            raw reads     raw reads
--   category                w/overlaps  w/o/overlaps
--   -------------------- ------------- -------------
--   Number of Reads              34655         45087
--   Number of Bases          295389624       3080764
--   Coverage                    73.847         0.770
--   Median                        8657             0
--   Mean                          8523            68
--   N50                           9694         14000
--   Minimum                       2000             0
--   Maximum                      53583         37764
--
--                                        --------corrected---------  ----------rescued----------
--                             evidence                     expected                     expected
--   category                     reads            raw     corrected            raw     corrected
--   -------------------- -------------  ------------- -------------  ------------- -------------
--   Number of Reads              24881           8841          8841              0             0
--   Number of Bases          217458159       76172019      33490754              0             0
--   Coverage                    54.365         19.043         8.373          0.000         0.000
--   Median                        8813           8706          2969              0             0
--   Mean                          8739           8615          3788              0             0
--   N50                           9785           9629          5725              0             0
--   Minimum                       2000           2000             1              0             0
--   Maximum                      53583          50520         49195              0             0
--
--                        --------uncorrected--------
--                                           expected
--   category                       raw     corrected
--   -------------------- ------------- -------------
--   Number of Reads              70901         70901
--   Number of Bases          222298369         53570
--   Coverage                    55.575         0.013
--   Median                           0             0
--   Mean                          3135             0
--   N50                           9740             0
--   Minimum                          0             0
--   Maximum                      53583         53570
--
--   Maximum Memory          1031127338
-- Report changed.
-- Finished stage 'cor-filterCorrectionLayouts', reset canuIteration.
-- Using overlaps no worse than 0.3 fraction error for correcting reads (from corErrorRate parameter).
--
-- Configuring correction jobs:
--   Jobs limited to 8 GB per job (via option corMemory).
--   Reads estimated to need at most 1 GB for computation.
--   Leaving 7 GB memory for read data.
----------------------------------------
-- Starting command on Sun Dec  1 22:36:27 2019 with 59.497 GB free disk space

    cd correction/2-correction
    ./correctReadsPartition.sh \
    > ./correctReadsPartition.err 2>&1

-- Finished on Sun Dec  1 22:36:27 2019 (like a bat out of hell) with 59.497 GB free disk space
----------------------------------------
-- Using overlaps no worse than 0.3 fraction error for correcting reads (from corErrorRate parameter).
-- No change in report.
-- Finished stage 'cor-generateCorrectedReadsConfigure', reset canuIteration.
-- No change in report.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'cor' concurrent execution on Sun Dec  1 22:36:27 2019 with 59.497 GB free disk space (1 processes; 1 concurrently)

    cd correction/2-correction
    ./correctReads.sh 1 > ./correctReads.000001.out 2>&1

-- Finished on Sun Dec  1 22:44:30 2019 (483 seconds) with 94.715 GB free disk space
----------------------------------------
-- Found 1 read correction output files.
-- No change in report.
-- Finished stage 'cor-generateCorrectedReadsCheck', reset canuIteration.
-- Found 1 read correction output files.
-- No change in report.
-- Finished stage 'cor-generateCorrectedReadsCheck', reset canuIteration.
--
-- Loading corrected reads into corStore and seqStore.
----------------------------------------
-- Starting command on Sun Dec  1 22:44:31 2019 with 94.715 GB free disk space

    cd correction
    /Users/carlos/Bin/canu-1.9/Darwin-amd64/bin/loadCorrectedReads \
      -S ../icu43_100x.seqStore \
      -C ./icu43_100x.corStore \
      -L ./2-correction/corjob.files \
    >  ./icu43_100x.loadCorrectedReads.log \
    2> ./icu43_100x.loadCorrectedReads.err

-- Finished on Sun Dec  1 22:44:32 2019 (one second) with 94.688 GB free disk space
----------------------------------------
--
-- ERROR:  Read coverage (6.18) is too low to be useful.
-- ERROR:
-- ERROR:  This could be caused by an incorrect genomeSize or poor quality reads that could not
-- ERROR:  be sufficiently corrected.
-- ERROR:
-- ERROR:  You can force Canu to continue by decreasing parameter stopOnLowCoverage=10,
-- ERROR:  however, the quality of corrected reads and/or contiguity of contigs will be poor.
--

ABORT:
ABORT: Canu 1.9
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:

**Comment by skoren** [comment]
It looks like many of your reads don't have overlaps in the initial run, try adding ```corMhapSensitivity=normal``` and re-starting from scratch.

**Comment by huizhen2014** [comment]
Thanks, It works by adding the parameter. So, I conjecture the difference between the corMhapsensitivity and corOutCoverage from the literal meaning. The former seems to extract the better reads from all the corrected reads, and if I used less coverage value, I would get the more better reads cohort to assemble the genome, and the quality of genome also would be better from this point; While, the latter will adapt the coverage to the corrected reads' quality and quantity when assembles the genome. 
Have you tried the mecat2 ?  It will output more integrated scaffolds than canu, which means the output from canu includes more contigs than mecat2.  And would you give me some advices about how to use the short reads from Illumina paired-end sequencing to fill the gap from the canu outputs?  Thank you.

**Comment by skoren** [comment]
The sensitivity parameter means what the default error limit is for the data, your data seems lower quality than average, perhaps it is older. The correction out coverage is how many reads are targeted for correction, which defaults to 40. However, if you don't have any overlaps to some reads then they can't be corrected anyway. You don't really need to adjust this unless you're working with a metagenome or a heterozygous genome. 

The number of contigs doesn't really matter, Canu is meant to be conservative and faithfully represent what's in your data. This will include plasmids, control sequences (if you included them), and variants present in the sample. Many assemblers just ignore these differences and reduce the number of contigs. The proper thing to look at is the length of the contigs and whether you have circular ones. Given that your data is lower quality, you may not want to be adjusting the error rate down either, instead see the FAQ for sequel I parameters which increases the error rate.

Lastly, short-read data isn't going to fill any gaps. It's too short to be useful for that. The only thing you can use it for is to improve consensus accuracy using something like freebayes but only after running a long-read polishing tool like arrow.

**Comment by huizhen2014** [comment]
Thanks, I got it! I have read some blogs about the assembly of PacBio sequence and understood some criteria about a better assembly outcome.
