### ISSUE TITLE
Metagenome assembly running out of memory on 3Tb node

### ISSUE THREAD

**Issue by btemperton** [marbl/canu#1575]
I'm trying to assemble a viral metagenome from MinION reads (metaFlye is estimating the total size as ~350Mb) using canu 1.9 on our linux HPC:

```
canu -d tmp.2018_11_viral_fraction.guppy_v330.canu         -p 2018_11_viral_fraction.guppy_v330.canu         genomeSize=350m         stopOnLowCoverage=5         maxMemory=2000         corOutCoverage=10000         corMhapSensitivity=high         correctedErrorRate=0.16         corMinCoverage=0         redMemory=32         oeaMemory=32         batMemory=200         useGrid=false         -nanopore-raw samples/processed/2018_11_viral_fraction.guppy_v330/no.dtr.fa
```

The output would suggest that it's running out of memory (!) during correction:

```
ABORT:      loaded   skipped                          input file
ABORT:   --------- --------- -----------------------------------
ABORT:   Failed to open '../2018_11_viral_fraction.guppy_v330.canu.seqStore/blobs.0000' for reading: Cannot allocate memory
```

Can you recommend what I can tweak to try to get it to run successfully? I have attached the whole log file for reference 
[snakejob.canu_assemble.163.sh.txt](https://github.com/marbl/canu/files/3906958/snakejob.canu_assemble.163.sh.txt)

**Comment by skoren** [comment]
The correction actually finished, it had issues loading the data into your store, which seems like a disk corruption issue not a memory issue. 

What's the contents in 2018_11_viral_fraction.guppy_v330.canu.seqStore? (ls -la). How did you install Canu? It's reporting that it is a snapshot, so not necessarily a tested released version but rather an intermediate which may have bugs/issues.

**Comment by skoren** [comment]
Idle, no response.
