### ISSUE TITLE
Support/Suggested parameters for R10 Nanopore flowcells

### ISSUE THREAD

**Issue by zmunro** [marbl/canu#1577]
Under the FAQs in the Canu docks, there is helpful information about how to tweak parameters when using R7 and R9 flowcells. I just started to use the new R10 flowcells and I am wondering if there is any suggestions of how to tweak parameters for it, or if the FAQs will be updated with this information.

**Comment by skoren** [comment]
We haven't seen much data from R10 so can't say how to best assemble it until there are more public datasets. I'd expect that the same suggestions as R9 (which is defaults for nanopore) should be a good start.
