### ISSUE TITLE
low coverage HiFi reads producing large assembly

### ISSUE THREAD

**Issue by pbfrandsen** [marbl/canu#1580]
Dear Canu developers,

First, thanks for such a great program. It's wonderfully user-friendly and the documentation is excellent.

I recently sequenced my first set of HiFi reads and ran them through the latest release of Canu 1.9 in HiFi mode, e.g.:

```
canu -p hespero -d hespero_hifi genomeSize=1.2g -pacbio-hifi hespero_pacbio_q20_hifi.fastq useGrid=false
```

Interestingly, I get an assembly that is approximately twice the size of a Canu assembly on the same species (though a different individual) with Nanopore data. I don't have flow cytometry data, but the genome size estimate from Illumina kmers more closely resembles the Nanopore assembly size. One additional point of data is that there is an unusually high amount of duplicated BUSCOs, perhaps suggesting uncollapsed haplotypes?:

```
INFO	Results:
INFO	C:91.1%[S:42.5%,D:48.6%],F:3.6%,M:5.3%,n:2442
INFO	2223 Complete BUSCOs (C)
INFO	1037 Complete and single-copy BUSCOs (S)
INFO	1186 Complete and duplicated BUSCOs (D)
INFO	89 Fragmented BUSCOs (F)
INFO	130 Missing BUSCOs (M)
INFO	2442 Total BUSCO groups searched
```

Any idea on what might be going on here or where there is a parameter that I might fiddle with to fix it?

Many thanks,

Paul

**Comment by skoren** [comment]
This is correct and expected, hifi data error rates are below most genome's heterozygosity rates so you end up separating your haplotypes. The nanopore data in contrast is too high error to do that for most genomes. You should run purge_dups on the HiFi assembly (and on the nanopore one for that matter too) and I expect the resulting sizes will be similar.

**Comment by pbfrandsen** [comment]
Thanks for the quick reply, Sergey! That makes sense and is a nice feature.
