### ISSUE TITLE
Conda install of Canu seems to be broken.

### ISSUE THREAD

**Issue by Lamm-a** [marbl/canu#1584]
Canu command used:
```
canu \
  -p $tag -d /home/lamma/faststorage/K_bird/canu-outputs \
  genomeSize=8m \
  -pacbio-raw $file
```
Canu version:
`canu                      1.9                  he1b5a44_0    bioconda
`
canu -version returns:
`readline() on closed filehandle F at /home/lamma/miniconda3/envs/hybrid-assembly/bin/../lib/site_perl/canu/Defaults.pm line 1068.`
Not sure why?

The error:
```
ERROR:
ERROR:  Failed with exit code 127.  (rc=32512)
ERROR:

ABORT:
ABORT:
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   sqStoreCreate failed.
ABORT:
ABORT: Disk space available:  4037885.868 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (./F19FTSEUHT1027.PSU4_ISF1A.subreads.seqStore.BUILDING.err):
ABORT:
ABORT:   sh: line 1: /home/lamma/miniconda3/envs/sqStoreCreate: No such file or directory
```
From looking around it is an issue with the conda install but how can this be solved whilst maininging the install in a conda environment?

**Comment by skoren** [comment]
We don't manage the conda install and don't really support it, it is not the recommended way to install Canu. There's no reason to manage Canu in a conda install since it has no outside dependencies to install. 

It looks like Conda isn't properly linking all the binaries which it is moving around from their default locations. You could manually link all the canu binaries to be visible from `/home/lamma/miniconda3/envs/`

**Comment by Lamm-a** [comment]
Fair enough, saves having to add canu to $PATH though does it not, as I assume cloning the git repository still requiers you to be whereever it was cloned to in order to clone canu or? How do I manually link all the canu binaries to be visible from `/home/lamma/miniconda3/envs/`

Thank you for the help and fast reponse :)

**Comment by skoren** [comment]
It does mean you don't have to add canu to path, you don't need to close just download one of the pre-compiled binaries on the release page.

I'm not sure where conda actually put the canu binaries. Can you run `which canu` or `which sqStoreCreate` and see what they return? For every file in the same path as those you want to symlink them to `/home/lamma/miniconda3/envs/` with `ln -s`.

**Comment by Lamm-a** [comment]
Ah okay that is good :)

`which canu` returns:
/miniconda3/envs/hybrid-assembly/bin/canu

`which sqStoreCreate` returns:
/miniconda3/envs/hybrid-assembly/bin/sqStoreCreate

File in the same path as what sorry?

I seems sqStoreCreate is not getting put into the highest canu directory. Will moving it over solve this issue?

**Comment by skoren** [comment]
Ah interesting, where does the hybrid-assembly path come from? Did you specify that or is that part of the conda environment? Canu's path code is a bit overcomplicated and it expects if it sees something like Linux-amd64 it strips this out but in your case it's stripping out hybrid-assembly. Renaming this to be hybrid_assembly or hybrid assembly should fix the issue.

**Comment by Lamm-a** [comment]
Ah okay thank you :) hybrid-assembly path is just the name of the conda environment. I will try this and see if it fixes it.

**Comment by Lamm-a** [comment]
This does no appear to have fixed the issue. `which canu` and `which sqStoreCreate` return the same as above just with hybrid_assembly in the path instead.

**Comment by skoren** [comment]
That's fine, but what happens if you run the assembly again.

**Comment by Lamm-a** [comment]
Seems to have worked, will update when the run ends :) Thank you!

**Comment by skoren** [comment]
I'm going to close this and track through our feature request (to remove the Linux-amd64) or at least not strip out other random text like in your case from the binary path. Open a new issue if your run has an error to keep different errors in separate issues.
