### ISSUE TITLE
Follow up to #1051

### ISSUE THREAD

**Issue by ranitori** [marbl/canu#1585]
Hi,
In #1051 with respect to interpreting the <>.report file, you explain as follows:

tells you most of your reads had at least one overlap, that's good and expected. Next,

```
--                                        --------corrected---------  
--                             evidence                     expected      
--   category                     reads            raw     corrected
--   -------------------- -------------  ------------- -------------
--   Number of Reads             229397          48006         48006      
--   Number of Bases         2134291652      993586222     920001699     
--   Coverage                    92.795         43.199        40.000          
--   Median                        6842          15330         14106           
--   Mean                          9303          20697         19164           
--   N50                          11512          28066         26840           
--   Minimum                       1045          10184         10183         
--   Maximum                      60664          60664         59063     
--   
```
tells you that you could end up with 92.8x coverage if you corrected all the reads. However, Canu only wants to get the longest 40x so it selects 43.2x of your raw read data which it estimates will result in 40x correction (it actually results in 40.77x from your logs). This just means some reads which are long in raw form are not as long in corrected form because they have errors/chimera/etc.
```
--                            ----------rescued----------
--                                        expected
--   category                     raw     corrected
--   --------------------   ------------- -------------
--   Number of Reads               20030         20030
--   Number of Bases            90137165      61903752
--   Coverage                      3.919         2.691
--   Median                         3324          2682
--   Mean                           4500          3090
--   N50                            5529          3659
--   Minimum                        1012           501
--   Maximum                       41475         10179
```
The rescued reads are ones that wouldn't have contributed at all to the longest 40x. These could be short plasmids, mitochondria, etc. Canu includes them even though they're too short by the 40x cutoff to avoid losing sequence in the assembly.

My questions are:
1) For the first table above, does this mean that the expected final genome coverage in this particular example will be about 92x, or will canu always default back down to 40x coverage for any genome I try to assemble?
2) For the second table above, if there IS a plasmid in the organism I am using (and it is a high copy number plasmid), then I would expect all of the numbers to be substantially higher, correct?

Thank you in advance.

**Comment by skoren** [comment]
1. The final coverage will be 40x in corrected reads and in the contigs assembled from those reads but the full 92x will be used to make the corrected reads. It usually doesn't help improve the assembly or consensus to include more than 40x (unless you have a very heterozygous genome) and so using the longest 40x is the default.

2. Not necessarily, the plasmids are typically short so having 3x coverage of the nuclear genome translates to a high coverage of the plasmid.
