### ISSUE TITLE
polyploid 

### ISSUE THREAD

**Issue by pjm43** [marbl/canu#1587]
Sergey

I'm assembling an allotetraploid plant species.  The plant naturally inbreeds so the genome should be homozygous, but is the result of ancient polyploidization event where an A diploid and C diploid genome formed this allotetraploid (AACC genomes).  When I assembly with default parameters I get good assembly statistics (N50=5.2 Mb), but the size of the genome is slightly smaller than I expected (7.2Gb vs. 9.0Gb anticipated from flow cytometry).  I realize that some collapse of repetitive regions is expected and probably unavoidable - indeed most of my assemblies (for other inbred plant species) are slightly smaller than the flow cytometry estimates but all indications (from BUSCO) is that the genomes are complete (at least for the genic regions).  

I did read in the Canu documents that you suggest some polyploid parameters.  While I'm pretty happy with my default parameters results (including some parameters you previously suggested for Sequel II data), I did want to see if I could increase the genome assembly size (to better match the flow cytometry estimates).   In the canu documents you suggest adding these parameters: `corOutCoverage=200 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50"`.  Would you suggest these same parameters for the assembly I described above?  If so, do you simply add them into the command line like so:

`canu -d canu_v1.9_polyploid_insularis -p canu1.9_polyploid_insularis genomeSize=9090m maxThreads=16 corMhapSensitivity=normal correctedErrorRate=0.035 utgOvlErrorRate=0.065 trimReadsCoverage=2 trimReadsOverlap=500
corOutCoverage=200 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" \`
 
I was worried about the positioning of the quotation marks in the command before the batOptions (in my mind I thought it would come after the "=" sign.

Lastly, can you comment of assemblies sizes - for a homozygous and highly repetitive (78% based on RepeatModuler) plant species should I expect that some collapse is inevitable and that assembly sizes will be smaller than the flow cytometry estimates.

Thanks,

Jeff

**Comment by skoren** [comment]
The command should work with the quotes either after the equals or around the whole expression.

I wouldn't expect the heterozygous parameters to make much difference here, I expect the collapse is due to repeats and/or the genome size is over-estimated originally. You can compare the assembly size to the estimate size from something like genome scope. You can also try to quantify collapse either using a tool like SDA or by looking at coverages for contigs canu output (see the tigInfo file, take contigs with higher than mean coverage + some sd and count bases in those, use coverage in those contigs over mean coverage to estimate how many bases they should have been).

**Comment by pjm43** [comment]
Sergey,

Let me make sure I got this right.  When I look in the .contig.tigInfo file I see a column for "coverage" - you're suggesting that I take the mean and standard deviation of that column and come up with a cutoff value (say mean + 2sd??).  Any contigs that are above that, I could could the bases in those contigs multiple by the coverage/mean coverage to estimate how many bases they should have been -- this will help me understand how much of the genome has collapsed.  Did I get this right?

The contig.tigInfo file has 694480 lines in it - I'm assuming I should remove the "unassem" - leaving me just the contigs from the assembly (6325 contigs).  These contigs have an average coverage of 36.87 with a SD of 240. If I use 2 SD then my cut off would be 518 for the coverage (is that a reasonable cutoff (2 X SD)?).  That leaves 39 contigs with greater than 518 coverage:


`

  |   |   | mean + 2XSD | 518.297293 |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
  |   |   | SD | 240.711977 |   |   |   |  
  |   |   | mean | 36.8733391 |   |   |   |  
#tigID | tigLen | coordType | covStat | coverage | tigClass | sugRept | sugCirc | numChildren
7279 | 103985 | ungapped | -18310.81 | 13176.37 | contig | no | no | 26531
6647 | 178021 | ungapped | -16039.5 | 7264.26 | contig | no | no | 23346
314 | 286475 | ungapped | -24352.04 | 6802.67 | contig | no | no | 35472
67146 | 115872 | ungapped | -9188.52 | 4556.12 | contig | yes | no | 13368
7191 | 115875 | ungapped | -6352.24 | 3474.13 | contig | no | no | 9291
6963 | 114877 | ungapped | -6640.27 | 3129.86 | contig | no | no | 9692
11424 | 132454 | ungapped | -7022.85 | 2957.04 | contig | no | no | 10232
6846 | 245751 | ungapped | -10708.45 | 2799.96 | contig | no | no | 15727
67720 | 448390 | ungapped | -14422.92 | 2060.95 | contig | yes | no | 21350
67116 | 116802 | ungapped | -5460.29 | 1944.75 | contig | yes | no | 7974
7142 | 151418 | ungapped | -4474.57 | 1874.41 | contig | no | no | 6627
7385 | 129786 | ungapped | -3668.6 | 1692.34 | contig | no | no | 5431
8009 | 110519 | ungapped | -3269.98 | 1617.53 | contig | no | no | 4844
7345 | 99139 | ungapped | -2602.33 | 1355.24 | contig | no | no | 3870
755742 | 97714 | ungapped | -3756.94 | 1318.68 | contig | no | no | 5516
67198 | 196681 | ungapped | -5454.79 | 1144.68 | contig | yes | no | 8090
7580 | 128428 | ungapped | -2793.1 | 1143.77 | contig | no | no | 4175
7553 | 112502 | ungapped | -2442.73 | 1119.38 | contig | no | no | 3648
12076 | 328203 | ungapped | -10700.02 | 1069.07 | contig | no | no | 15783
12553 | 57882 | ungapped | -1601.1 | 1059.51 | contig | no | no | 2350
1183 | 176345 | ungapped | -4545.97 | 990.63 | contig | no | no | 6737
6458 | 173844 | ungapped | -3124.23 | 980.7 | contig | no | no | 4705
5753 | 102059 | ungapped | -1861.74 | 968.99 | contig | no | no | 2795
67228 | 110142 | ungapped | -2198.02 | 871.18 | contig | yes | no | 3274
12111 | 141709 | ungapped | -6205.92 | 817.2 | contig | no | no | 9114
9089 | 116184 | ungapped | -2380.28 | 770.78 | contig | no | no | 3564
830 | 99605 | ungapped | -1409.84 | 754.98 | contig | no | no | 2132
7157 | 158730 | ungapped | -1743.53 | 677.91 | contig | no | no | 2694
12617 | 119816 | ungapped | -4366.35 | 666.81 | contig | no | no | 6408
7492 | 145574 | ungapped | -1773.01 | 635.33 | contig | no | no | 2717
5911 | 154805 | ungapped | -2101.99 | 598.56 | contig | no | no | 3204
67241 | 97554 | ungapped | -958.92 | 571.38 | contig | yes | no | 1465

`
What would be my next step?

Thanks in advance,

Jeff

**Comment by skoren** [comment]
Yes that is a good start though the coverage will be a mean across the entire contig. If there is a smaller collapse within a large contig it may be missed. Canu's tgStoreDump command (run without parameters to see options) can also provide per-base coverage information for each contig. There are also tools designed for detecting these assembly collapses like SDA.
