### ISSUE TITLE
Canu 1.8 Overlap buckets taking up too much space

### ISSUE THREAD

**Issue by Mpersicae** [marbl/canu#1588]
Hello, 

I am using Canu 1.8 to assemble an insect genome. Reads are from a PacBio Sequel II platform, genome size is estimated at 350 Mbp, I have an estimated x280 coverage. I am working on a Linux-based grid using a Slurm scheduler. 

Previously, I ran into problems at the `1-overlapper` step. My mhap files were very large and they quickly took up all the grid memory alloted to me (20 TB). After this, I added the parameters recommended in the Canu FAQ for highly repetitive genomes, and the total size of the `1-overlapper` directory was reduced to 3 TB.

My Canu command is:
```
canu -p M-persicae -d M-persicae-canu \
-pacbio-raw $HOME/scratch/M-persicae-fastq/M-persicae-bamtools.fasta \
genomeSize=350m \
correctedErrorRate=0.085 \
corMhapSensitivity=high \
corMinCoverage=0 \
gridOptions="--time=08:00:00" \
gridEngineArrayOption="-a ARRAY_JOBS%20" \
corMhapFilterThreshold=0.0000000002 \
corMhapOptions="--threshold 0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50"
mhapMemory=60g \
mhapBlockSize=500 \
ovlMerDistinct=0.975
```

After re-running Canu with the new parameters, the mhap jobs are completing just fine, but the buckets created by `ovlStore` jobs are once again taking up all remaining space in my scratch directory. Canu wants to create 993 buckets. This fails after 933 buckets due to memory constraints. Each bucket directory in `correction/M-persicae.ovlStore.BUILDING` is around 15 GB. 

Here is output from one of the failed buckets, `correction/M-persicae.ovlStore.BUILDING/logs/1-bucketize_..._934.out`:
```
Found perl:
   /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/perl/5.22.4/bin/perl
   This is perl 5, version 22, subversion 4 (v5.22.4) built for x86_64-linux-thread-multi

Found java:
   /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/java/13.0.1/bin/java
   openjdk version "13.0.1" 2019-10-15

Found canu:
   /cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc7.3/canu/1.8/bin/canu
   Canu 1.8

Running job 934 based on SLURM_ARRAY_TASK_ID=934 and offset=0.

Attempting to increase maximum allowed processes and open files.
  Max processes per user limited to 514105, no increase possible.
  Max open files limited to 51200, no increase possible.


Opened '../M-persicae.seqStore' with 6993466 reads.

Constructing slice 934 for store './M-persicae.ovlStore.BUILDING'.
 - Filtering overlaps over 1.0000 fraction error.

Bucketizing input    1 out of    1 - '1-overlapper/results/000934.ovb'
writeToFile()-- After writing 69908 out of 828336 'ovFile::writeBuffer::sb' objects (1 bytes each): Disk quota exceeded
```

I am not sure how to proceed, or which parameters I can safely tweak to help with this issue. 

Many thanks for your patience, this is my first genome assembly and I still have lots to learn!

**Comment by skoren** [comment]
I think your original issue is you set corMhapSensitivity=high and had 300x, that is going to produce too many overlaps and fill up your space. The setting for repetitive genomes somewhat undid that but you'd probably be better off just setting corMhapSensitivity=low (or leaving it off) which would be the default given your 300x of coverage. You also don't need corMinCoverage=0 at 300x of input coverage, you'll just force keeping low-quality data. I expect that will take less space than the current run. I believe 1.8 was the version that was not cleaning up most of the store building as it went. There are improved options in 1.9 (```purgeOverlaps=aggressive``` for example) but 1.9 isn't backwards compatible with your current run. If it's not too expensive to re-run the mhap step, I'd suggest trying 1.9, removing all your mhap options, and adding the purge option:
```
correctedErrorRate=0.085 \
gridOptions="--time=08:00:00" \
gridEngineArrayOption="-a ARRAY_JOBS%20" \
ovlMerDistinct=0.975
purgeOverlaps=aggressive
```
This will likely fit in the space.

If you don't want to re-run you can try to manually clean up as the store is built. This is a bit error-prone as if you remove the wrong file you would have to re-run some computation. First, you can remove the 1-overlapper/blocks folder. Second, as long as a bucketizing step completed (it has a bucket<JOBID> folder and there is no error about being out of space like above in the file, you can remove the corresponding ovb file (for example if the above had not failed you'd remove ```1-overlapper/results/000934.*```). You can run the bucketizing steps in batches of 100 or so and clean up the ovb files as each batch completes to save space.

**Comment by Mpersicae** [comment]
Hi Sergey, thank you so much for your comments.
I will try to get Canu 1.9 installed and give that a go with the improved parameters. Re-running the mhap step shouldn't be too much of an issue, but I very much appreciate your explanation of a workaround.

**Comment by Mpersicae** [comment]
Running the command with the recommended parameters in Canu 1.9 solved my issue, the mhap and mhap bucketizing steps ran smoothly and only took up ~8Tb of memory. 

Thanks again!! Your attentiveness to this issues page and your comprehensive answers are highly appreciated.
