### ISSUE TITLE
canu 1.3 gives quite different, worse results than 1.2 

### ISSUE THREAD

**Issue by tseemann** [marbl/canu#159]
I have a 1.8 Mb bacterial genomes and I run 
`canu -p canu -d canu-X.XX genomeSize=1.8m -pacbio-raw pacbio.subreads.fastq.gz`

The reads are 60x coverage:
`Reads   11255
Yield   115739815
GeeCee  40.9
MinLen  38
AvgLen  10283
MaxLen  39514`

With HGAP we get 1 contig of 1825004 bp.
With Canu 1.2 I get 10 contigs with about the right genome size.
With Canu 1.3 I get 15 contigs and 1/5th of the genome only.

With other pacbio data i have been getting excellent results (1 contig etc).

See table below.

Any ideas?

```
canu-1.2/canu.contigs.fasta         no=10 bp=1716676 ok=1716676 Ns=0 gaps=0 min=27297 avg=171667 max=1046698 N50=1046698
canu-1.2/canu.unassembled.fasta     no=91 bp=478853 ok=478853 Ns=0 gaps=0 min=1067 avg=5262 max=15756 N50=7842

canu-1.3/canu.contigs.fasta         no=15 bp=357930 ok=357930 Ns=0 gaps=0 min=9278 avg=23862 max=57798 N50=24803
canu-1.3/canu.unassembled.fasta     no=648 bp=2943773 ok=2943773 Ns=0 gaps=0 min=1017 avg=4542 max=17746 N50=6150
```

**Comment by skoren** [comment]
Strange, have you compared the corrected reads? Canu 1.3 auto-sets some parameters for higher coverage (which 60x is) but perhaps your data is lower quality than expected on this genome. I'd say try 1.3 with
corMhapSensitivity=normal or corMhapSensitivity=high. You could also that parameter in combination with corMinCoverage=0 (essentially corMhapSensitivity=high and corMinCoverage=0 are the defaults for 30X or less so you're enabling low-coverage setting for this genome).

If you're able to share the data I can also take a look at it locally, you can upload it to our ftp here:
ftp://ftp.cbcb.umd.edu/incoming/sergek

**Comment by tseemann** [comment]
@skoren I've uploaded `canu-issue_159-subreads.fastq.gz` to your FTP. The md5 is `cf910af471c84166e3f490e78374fc6d`.

**Comment by tseemann** [comment]
Ok, with `corMhapSensitivity=high corMinCoverage=0 genomeSize=1.8m` I get 1 contig: `tig00000000     dna     1840014`

Checking the consensus with Illumina data I get 3500 1 base insertions (mostly A/T), which is expected.

I hope the example above can help with improving the automatic settings.  This was the worst sample of the batch, the others were >100x.

Thank you for the advice.  Canu is a wonderful tool.

**Comment by skoren** [comment]
I think in future versions we should detect loss of too many reads and suggest the sensitive parameters.
