### ISSUE TITLE
CANU 1.9 ovStore::loadOverlapsForRead()-- Failed to load overlap

### ISSUE THREAD

**Issue by ReiGao** [marbl/canu#1591]
Hellow,
I am trying to assemble a genome, At the correction step,when begin to build Pmm.corStore.WORKING dir ,I got the following erro .
   
How can I locate which input file is the problem point. Can I rerun previous step to solve this problem?  

The previous steps took me about two week.
 Thank you for any help!
```
-- Starting command on Wed Jan  1 17:06:04 2020 with 290027.953 GB free disk space

    cd correction
    /public/Software/canu-1.9/Linux-amd64/bin/generateCorrectionLayouts \
      -S ../Pmm.seqStore \
      -O  ./Pmm.ovlStore \
      -C  ./Pmm.corStore.WORKING \
      -eC 100 \
    > ./Pmm.corStore.err 2>&1

 Finished on Wed Jan  1 22:56:10 2020 (21006 seconds) with 289425.382 GB free disk space
----------------------------------------

ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:

ABORT:
ABORT: Canu 1.9
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to generate correction layouts.
ABORT:
ABORT: Disk space available:  289425.382 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (correction/Pmm.corStore.err):
ABORT:
ABORT:   ovStore::loadOverlapsForRead()-- Failed to load overlap 22572 out of 112825 for read 4590061.
ABORT:
```

**Comment by skoren** [comment]
Sorry for the late reply, somehow missed this issue. This seems like it would be a corruption of the overlap store on a prior step (it has an invalid overlap). The store is verified after it is created so it seems like this would have happened after that. 

What is the size of files in your ```correction/*ovlStore``` (```ls -la```) folder?

**Comment by skoren** [comment]
Any update?

**Comment by skoren** [comment]
Idle, appears to be disk corruption.
