### ISSUE TITLE
Is polishing necessary after Canu?

### ISSUE THREAD

**Issue by Ateesha** [marbl/canu#1592]
Hello,

Thanks to your earlier issue resolve, I have a successfully running Canu(1.9) on a Linux cluster (PBS).

I assembled a Drosophila genome using PacBio sequel data from 3 SMRTcell in the `fastq` format. As a result, I obtained the following output from Canu:
```
[UNITIGGING/CONSENSUS]
-- Found, in version 2, after consensus generation:
--   contigs:      4153 sequences, total length 185225337 bp (including 210 repeats of total length 4456732 bp). 
```
I ran QUAST on the Canu outputted contigs.fasta and got `N50` value of `116282`

However, the same PacBio sequel data after running through the HGAP-4 assembler after two rounds of polishing had outputted the `number of contigs` to be `790` and `N50` value of `1275303 bp`.

Can you kindly give your input as to why I could have got the above discrepancies? Will polishing the Canu output help? If so, what polishing software is recommended?

Thank you!

**Comment by skoren** [comment]
Assuming this is a CLR dataset, yes you should run Arrow at the end of the process to improve the accuracy but that won't significantly change the contig sizes. 

The N50 values aren't comparable between assemblies if they are different sizes, you should use a common denominator (like the current reference size) to compute NG50 values.
