### ISSUE TITLE
Any suggestions on `k` for trio-binning CCS reads

### ISSUE THREAD

**Issue by SHuang-Broad** [marbl/canu#1593]
Hi,

As I go back and read the TrioCanu paper again, one particular paragraph made me as the above question

> Read classification accuracy depends not only on the zygosity of the offspring, but also on sequencing read length and error rate (Fig. 2). Given the high error rates in current long-read technologies, the k-mer size is also important. It must be long enough to be unique in the genome but short enough that it will not be corrupted by sequencing errors (for example, k ≈ 21 for a 3-Gb genome).

Apparently, PacBio CCS reads are no longer of that high error rates, hence `k` can be increased. A similar argument can possibly be made for ONT reads with improved pore and base caller. 
So I'm wondering if the canu team has done any experiments on this issue.

Thanks!

Steve

**Comment by skoren** [comment]
Yes, see the wenger et al. paper for HG002, we tried binning with 21-mers, 51-mers, and 91-mers. We ended up using 51-mers in the paper. Unfortunately the current version of meryl doesn't support mers >31 so you'd have to use that as the max. We may increase that limit to 64 in the next meryl update.

**Comment by SHuang-Broad** [comment]
Good to know. Thanks Sergey!

Unsure if you want to leave this open (for knowledge sharing purpose) or close it. So I'll leave to your decision.

Thanks!

**Comment by SHuang-Broad** [comment]
@skoren 
Following your reply, I went back and dug up the code that computed this `$k$` value, which I believe is [here](https://github.com/marbl/canu/blob/163a7f07de97d6035cbab76335d2e4b5ec60ed3d/src/pipelines/canu/HaplotypeReads.pm#L236).

You mentioned that in the Nature Biotech paper in 2019, `$k$` ended up set as 51, which means 
that formula is changed (the error rate needs to be unrealistically low if the same formula is used, even for `k=31`). So I'm wondering if you can elaborate a bit on this model change.

Thanks again!

**Comment by skoren** [comment]
That formula ignores error rate of the reads though, it's just telling you a 21-mer should be relatively unique in the human genome, it's the minimum threshold for a k-mer size not the maximum.

The reason you want to use 51-mer is because you get more specificity with the matches so it can help classify more reads accurately.
