### ISSUE TITLE
Time Chart for CANU & Different Genomes

### ISSUE THREAD

**Issue by cement-head** [marbl/canu#1596]
Are there any handy-dandy charts of genome size X coverage X time (man hours; not CPU hours) for/to completion?

CANU's been running for several days (without issues) but I'm wondering expected time to completion?

128 threads, 2 TB ECC RAM; 6.2 Gbp amphibian genome; about 30x coverage PacBioSII + 2x coverage ONT minION (ultra-long reads); no reference

**Comment by skoren** [comment]
Not easily since genome repeat content can have a large effect. Given your genome is 6.2Gbp and likely revery repetitive, a single node will take a very long time to run, months. We recommend a cluster for this sized genome instead.

**Comment by cement-head** [comment]
Ha! okay...months is not good.
