### ISSUE TITLE
FastQsimulate vanished

### ISSUE THREAD

**Issue by ugadal** [marbl/canu#1598]
Not a real issue..
building canu from src does not produce fastqsimulate
it was included in binary release 18 but not from src
totally vanished in 19

**Comment by brianwalenz** [comment]
Yup, it's gone.  It was leftover code from our Illumina days, never used in Canu and never used by us for more than 5 years, so I removed it.

On the bright side, the one included in v1.8 will forever more be the latest version.

**Comment by ugadal** [comment]
ok, It was tho a great teaching instrument...

**Comment by skoren** [comment]
I think there are more robust Illumina simulation tools than what fastqSimulate had built in. I'd recommend using those instead since we haven't maintained or updated fastqSimulate in many years and it's unlikely to accurately represent current Illumina datasets.
