### ISSUE TITLE
Recommendations for low coverage extremely large genome

### ISSUE THREAD

**Issue by rhallPB** [marbl/canu#160]
Hi, 
Can you make any recommendations for parameter I may what to consider changing in order to assemble ~25x of data for a 15Gb repetitive genome. The cluster environment is comprised of 16, 48 core 512Gb machines. I would be grateful of any pointers, I don't have a lot of experience with canu.
Thanks,
Richard.

**Comment by colindaven** [comment]
Sounds tough. From the FAQ for <30X coverage. (http://canu.readthedocs.io/en/stable/faq.html)

corMinCoverage=0 errorRate=0.035

**Comment by skoren** [comment]
Yep, those parameters are a good start.

You can also try some of the experimental parameters to speed up the assembly (```obtOvlFilter=1 utgOvlFilter=1```) will speed up the overlapping in the post-correction steps.

**Comment by brianwalenz** [comment]
Before you get too far here, what do you get from:

% ulimit -a
% ulimit -Hu
% ulimit -Hn

And how much free disk space do you have access to?

Depending on the repeat content, you could end up with a LOT of overlaps, requiring a LOT of disk space, open files and processes to process.  We've hit OS limits on the last two before.  A friendly sysadmin will go a long way to completing this assembly.

**Comment by colindaven** [comment]
I couldn't set these experimental parameters successfully, how should they be specified ?

ERROR:  Paramter 'obtOvlFilter' is not known.
ERROR:  Paramter 'utgOvlFilter' is not known.

Command:

$ ~/programs/canu/canu-1.3/Linux-amd64/bin/canu -p ass_canu4 -d ass_canu4  -pacbio-raw all.fastq genomeSize=750m ovsMemory=30g-500g corMinCoverage=0 errorRate=0.035 corMaxEvidenceErate=0.15 obtOvlFilter=1 utgOvlFilter=1

**Comment by skoren** [comment]
The options aren't part of the 1.3 release, you have to be running the latest from tip to try them.

**Comment by rhallPB** [comment]
@brianwalenz 
ulimit -a
`core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 773213
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 300000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 300000
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited`

ulimit -Hu
`300000`

ulimit -Hn
`300000`

10's of Tb of disk space isn't a problem.

Currently trying to optimize the ovB and ovS jobs, even running very few jobs is heavily I/O limited.

**Comment by brianwalenz** [comment]
Those jobs are essentially 100% I/O.  It's all sequential though.  ovB jobs expand the *ovb.gz into multiple files, the ovS jobs read those files, sort, and write one output.
