### ISSUE TITLE
Using different/higher $k$ in `splitHaplotype`

### ISSUE THREAD

**Issue by SHuang-Broad** [marbl/canu#1606]
Hi,

I'm wondering if it is possible to specify a different (mostly higher) $k$ for 

https://github.com/marbl/canu/blob/master/src/haplotyping/splitHaplotype.C

Or is the answer "it doesn't matter", i.e. it depends on the $k$ used in constructing the meryl database?

Thanks!

**Comment by skoren** [comment]
At that point it doesn't matter, the k-mer used is the same as the k-mer used in the meryl DBs, @brianwalenz can correct me if I'm wrong.

**Comment by SHuang-Broad** [comment]
Thanks Sergey!

**Comment by SHuang-Broad** [comment]
closing as this is resolved, unless Brian has more comments.
