### ISSUE TITLE
k-mer information question

### ISSUE THREAD

**Issue by mcatto** [marbl/canu#1608]
16-mers |   |   | Fraction |  
-- | -- | -- | -- | --
Occurrences |   | NumMers | Unique | Total
1- | 1 | 0 | 0 | 0
2- | 2 | 3650802 | 0.0017 | 0.0001
3- | 4 | 25875518 | 0.0058 | 0.0003
5- | 7 | 119204509 | 0.0267 | 0.0021
8- | 11 | 292786498 | 0.0985 | 0.0118
12- | 16 | 395842593 | 0.2442 | 0.0408
17- | 22 | 354251102 | 0.4225 | 0.0909
23- | 29 | 261336103 | 0.5765 | 0.1498
30- | 37 | 185524602 | 0.6901 | 0.2071
38- | 46 | 130382665 | 0.7717 | 0.2597
47- | 56 | 89998591 | 0.8293 | 0.306
57- | 67 | 63350113 | 0.8693 | 0.3454
68- | 79 | 46017486 | 0.8977 | 0.3789
80- | 92 | 34486105 | 0.9185 | 0.4079
93- | 106 | 26614980 | 0.9341 | 0.4335
107- | 121 | 20321946 | 0.9462 | 0.4563
122- | 137 | 15488293 | 0.9555 | 0.4763
138- | 154 | 12418693 | 0.9626 | 0.4937
155- | 172 | 10180727 | 0.9683 | 0.5094
173- | 191 | 8111839 | 0.9729 | 0.5239
192- | 211 | 6522018 | 0.9767 | 0.5367
212- | 232 | 5378021 | 0.9797 | 0.5481
233- | 254 | 4380539 | 0.9821 | 0.5585
255- | 277 | 3533938 | 0.9842 | 0.5678
278- | 301 | 2930285 | 0.9858 | 0.576
302- | 326 | 2550306 | 0.9871 | 0.5834
327- | 352 | 2340956 | 0.9883 | 0.5904
353- | 379 | 2170067 | 0.9894 | 0.5974
380- | 407 | 1972375 | 0.9904 | 0.6043
408- | 436 | 1776274 | 0.9913 | 0.6111
437- | 466 | 1579987 | 0.9922 | 0.6177
467- | 497 | 1373148 | 0.9929 | 0.6239
498- | 529 | 1190419 | 0.9935 | 0.6297
530- | 562 | 1031678 | 0.9941 | 0.635
563- | 596 | 892373 | 0.9946 | 0.64
597- | 631 | 788692 | 0.995 | 0.6445
632- | 667 | 702038 | 0.9953 | 0.6487
668- | 704 | 605417 | 0.9957 | 0.6527
705- | 742 | 512600 | 0.9959 | 0.6564
743- | 781 | 454804 | 0.9962 | 0.6596
782- | 821 | 417675 | 0.9964 | 0.6626

--           0 (max occurrences)
-- 113844777341 (total mers, non-unique)
--  2146298799 (distinct mers, non-unique)
--           0 (unique mers)

Hi,

I have a simple question about the meaning of some of the terms. The information I posted was from me trying to figure out where the "fraction" comes from and what it means. I saw another post that had the same issues of "0 (unique mers)", but I don't understand how I can have 0 as well. The fraction says the unique percentage is increasing, so it can't be 0 right? Also, where is the "total" count coming from? I have been reading about the terms from Canu's documentation, but am still not completely understanding.

Thanks!

**Comment by skoren** [comment]
So the histogram doesn't report the 1-copy kmers in the table which is why it has 0. In the raw data these are actually the dominant k-mers. 

The other values are differentiating between total k-mers, which is just the total k-mers in the data, and distinct k-mers, which only count a repeating kmer once. So if you had a sequence like AAAA and counted 3-mers you'd have 2 total 3mers but only 1 distinct mer. 

In general though the 16-mer histograms on raw pacbio or nanopore data are not super useful as they are dominated by noise but post correction/trimming it can be used with tools like genomescope to estimate genome properties.

**Comment by mcatto** [comment]
Appreciate the fast response! That makes sense for the report and the terms. I am still waiting for my run to finish and will check on the distribution post correction/ trimming. Thanks for directing me towards a tool I haven't read about yet (have used jellyfish in the past though).
