### ISSUE TITLE
Need help to identify the corrected reads file

### ISSUE THREAD

**Issue by pomidorku** [marbl/canu#1610]
canu command used:
canu useGrid=false -p genome -d /genome_canu_out genomeSize=4.3m -pacbio-raw /subreads.fastq

 `canu -version` :
 Canu/1.8-intel-2017A-Python-3.5.2

Running on a grid

Hi,

I need you advise on how to obtain the corrected reads to perform a test for a hybrid assembly (pacbio+illumina short pe reads) with SPAdes. I read that Spades can take CCS reads. The recommended software to obtain the CCS reads (https://github.com/PacificBiosciences/ccs) is not installed in our cluster; furthermore, I may have some limitations on the use of the CCS sofware due to the chemistry of my raw data: S/P2-C2/5.0 (SEQUEL)

I want to test the hybryd assembly by using the corrected reads generated by a canu assembled genome (unless there is a better way to do it, I am still searching for advise on this issue). I run canu to assemble a genome but I am kind of confused about the output.

To assemble the genome I used the following command (options were the default ones):
canu useGrid=false -p genome -d /genome_canu_out genomeSize=4.3m -pacbio-raw /subreads.fastq

The assembly completes succesfully, according to the stdout file

stderr file shows some lines with information about the corrected reads:
genome.correctedReads.fasta.err 2>&1
Corrected reads saved in 'genome.correctedReads.fasta.gz'

The /genome_canu_out folder shows, among others,  the files named:

genome.contigs.fasta
genome.correctedReads.fasta.gz   ######## I think these are the reads I want.
genome.trimmedReads.fasta.gz
genome.unassembled.fasta
genome.unitigs.fasta

My question is: are the "genome.correctedReads.fasta.gz" identified above the output I need?

******************************************************************************
I ask this becuase when searching for the corrected reads I navigated to the correction/2-correction directory and it contains the following:

a "/results" directory that is empty.
and the following files:

corjob.files   (all lines look like this: "2-correction/results/xxxx.cns")

correctReads.sh  (This file contins two error messages:
echo Error: I need CANU_LOCAL_JOB_ID set, or a job index on the command line.
exit
echo Error: Only 188 partitions, you asked for $jobid.
exit 1
##the end of the file reads:
exit 0)

Sphing1.readsToCorrect       (it contains a list of numbers)
Sphing1.readsToCorrect.err   (it contains a single line that reads "Bye.")
Sphing1.readsToCorrect.log   (a table with descriptive data of some reads)
Sphing1.readsToCorrect.stats (stats about corrections)

##(nothing else I can read, i.e, no corjob.files.load.err exists in directory):
********************************************************************************

Also, the "/genome_canu_out/canu-scripts/" directory is empty
I cannot fnd the "genome.corStore" directory, which I have seen in assembleis I run in the past.

FORGOT TO MENTION that in the "genome_canu_out" folder there are three "core" files:
core.57660
core.70675
core.76602

Thank you for your help and your time.

Regards,

Pomidorku

**Comment by skoren** [comment]
See the outputs section of the documentation: https://canu.readthedocs.io/en/latest/tutorial.html#outputs. The correctedReads.fasta.gz are what you want. The results folder is for intermediate outputs as it runs. The core files are likely from gnuplot and can be ignored if the run completed.

The hybrid assembly should work with raw reads, you don't need to use corrected reads for SPAdes. You can likely just assemble the PacBio reads alone with Canu, no need for a hybrid assembly since both the consensus (after arrow polishing) and assembly continuity would be good.
