### ISSUE TITLE
Suggestions for high repetitive, high heterozygous polyploid

### ISSUE THREAD

**Issue by baozg** [marbl/canu#1612]
Hi, skoren

We recently want to assembly a high repetitive(>60%), high heterozygous(>1%) hexaploid plant. We already have 242 Gb raw Nanopore R9 1D data (N50 33kb).Based the flow cytometry, the genome should be 1.5Gb(subgenome should be 500M),so we had 160x raw data.The genome scope 2.0(for polyploidy) showed the haploid genome size should be 480M. We think the `canu` is the only choice to assemble such challenging genome. We want to recover all the subgenomes, then use the HiC data to get subgenomes separately and scaffolding.

But after reading all the FAQS, we want to confirmed the options we used. Would you mind give some advice for this genome?

1. ONT R9 1D
`overlapper=mhap utgReAlign=true`

2. high heterozygous
`corMhapSensitivity=normal`

3. polyploid genome
`corOutCoverage=200 errorRate=0.013 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50"`
But the option is for the PacBio raw data, the ONT data can use this parameter?

4. high repetitive
`OvlMerThreshold=300` 

So all the parameters is below:
```bash
canu \
-p genome -d genome \
genomeSize=1500m \
-nanopore-raw ./*.fastq.gz \
overlapper=mhap \
utgReAlign=true \
OvlMerThreshold=300 \
corMhapSensitivity=normal \
corOutCoverage=200 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" \
minReadLength=10000 \
minOverlapLength=2000 \
```

Did the parameter all right?
Thank you in advance.

Best Wishes
Zhigui

**Comment by skoren** [comment]
The parameters look OK, the corrected error rate defaults to 0.12 on nanopore so 13 % would be higher but the default is likely to work. 

The min read length is quite high, how much coverage do you have over 10kb? You may be better off providing a shorter length (like 2-3kb) and letting Canu choose the best set of coverage because a long read doesn't necessarily mean a correct read (it can be base caller noise, chimera, etc).

Lastly, you may get a better assembly without the overlapped,utgReAlign options but it will be much slower.

**Comment by baozg** [comment]
Hi, skoren

Thanks for your promptly response. 

We have total 242 Gb raw data, 230 Gb of them are >10k，N90 is 15kb.

So according to your expenrice, the parameters should change as below:

```bash
canu \
-p genome -d genome \
genomeSize=1500m \
-nanopore-raw ./*.fastq.gz \
OvlMerThreshold=300 \
corMhapSensivity=normal \
corOutCoverage=200 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" \
minReadLength=2000 \
minOverlapLength=2000 \
```

**Comment by skoren** [comment]
Yes those seem like a good start

**Comment by baozg** [comment]
Thanks for replying. The canu have already run in our HPC  server. I will close the issue.
If have any updates, I will post result in this issue.
