### ISSUE TITLE
installation help- Windows subsystem for Linux

### ISSUE THREAD

**Issue by emmaeisemann** [marbl/canu#1613]
I have canu downloaded with bioconda- which doesn't identify a version that can be used when trying to use circlator so I am trying to install canu separately. However, I am very new to command line and am very confused. I have downloaded the release files and use the command:

tar -xJf canu-1.9.Linux-amd64.tar.xz 

which does nothing and it just prompts me again and says my version is still canu snapshot ()

**Comment by skoren** [comment]
I expect you're still running the bioconda version but there isn't enough information in your original post. 

Can you post more details when you say does nothing. List the full contents of the folder where you downloaded the file (```ls -lha```) before and after you run the tar command. What is the full canu command you're running. Try also running ```canu-1.9/*/bin/canu``` if you're not already as described in the release notes.

**Comment by skoren** [comment]
Idle, no response and no access to a windows machine to test but conda isn't the recommended installer.
