### ISSUE TITLE
Creating .gfa file

### ISSUE THREAD

**Issue by ViriatoII** [marbl/canu#1614]
Hi, 

I was wondering if it's possible to use your [scripts](https://github.com/marbl/canu/tree/master/src/gfa) to create a .gfa file from a fasta file. 

It's awesome that canu automatically creates a .gfa in the end of the assembly, but I would like creating a new .gfa after scaffolding, and I can't find a way to do that.. 

Cheers,
Ricardo

**Comment by skoren** [comment]
These scripts wouldn't work from a fasta, they are designed to compute alignments when you have approximate positions of where contigs should intersect/connect. In Canu we have approximate guesses before we generate consensus for the assembly and then these scripts refine the positions. The scripts also assume your GFA nodes (contigs in our case) overlap.
