### ISSUE TITLE
How does Canu correct snp reads data?

### ISSUE THREAD

**Issue by Shen-Jing** [marbl/canu#1616]
Excuse me, my question is: After reads correction stage, does Canu reserve SNP reads?

If reads data have some SNPs (from parent),
for example:

```
AATCGG (from father)
AATCGG (from father)
AATCGG (from father)
AACCGG (from mother)
```

Does Canu correct these 4 reads to AATCGG (version of father), and doesn't reserve read from mother (AACCGG)?

In other words, after read correction, Canu only reserve 1 read: AATCGG (from father)?

### [my experiment]

reference genome: Chr21.fasta

1. 
use pbsim from Chr21.fasta to generate simulated reads => from_father_reads.fasta
(fasta read ID: `>chr21`)

2.
modify original genome file, each 500 bp have 1 snp => Chr21_mother.fasta
(A→T, T→C, C→G, G→A; at position 500 / 1000 / 1500 bp, etc.)

3.
use pbsim from Chr21_mother.fasta to generate simulated reads => from_mother_reads.fasta

4.
merge 2 reads files (concat from one to the other): 
from_father_reads.fasta + from_mother_reads.fasta => snp_reads.fasta
(snp_reads.fasta read ID: `>snp`)

5.
use Canu correct snp_reads.fasta => corrected_snp.fasta
```
canu -correct -p SNP genomeSize=46709983 -pacbio-raw snp_reads.fasta
```

6.
use minimap2 (aligner) align these reads to genome (Chr21.fasta):
from_father_reads.fasta => uncorrected.bam
snp_reads.fasta         => corrected_snp.bam

7. 
use samtools view specific snp position (randomly sample):
SNP reads (reads ID prefix: `>snp`) account for **higher** proportion of the corrected reads.

For example:
At position: 5,076,000 bp
- uncorrected reads (1544 reads)
  - 1164 normal reads (from_father_reads)
  - 380 snp reads (**24.6%**)
- corrected reads (117 reads, Canu's output data)
  - 58 normal reads
  - 59 snp reads (**50.4%**)

My experiment show that Canu doesn't correct all snp reads, it can reserve snp reads.
Are my experiment and conclusion correct?

(Sorry, my English is pretty limited.)

**Comment by skoren** [comment]
I'm not sure I understand what you're measuring (what's a SNP read?). Why would a second haplotype be only 25% of the reads, shouldn't it be closer to 50%.

There is no consideration in Canu for phase of SNPs during correction. That is, it can switch phase within reads so you end up with a read which is a mixture of mom + dad. However, Canu will only use the best buddies of a read to correct it so if there are enough mom (or dad) reads then their SNPs will be maintained.

**Comment by Shen-Jing** [comment]
> I'm not sure I understand what you're measuring (what's a SNP read?). Why would a second haplotype be only 25% of the reads, shouldn't it be closer to 50%.

Yes, You're right! Thank you! It should be closer to 50%.
Sorry, this position is valueless.

> There is no consideration in Canu for phase of SNPs during correction. That is, it can switch phase within reads so you end up with a read which is a mixture of mom + dad. However, Canu will only use the best buddies of a read to correct it so if there are enough mom (or dad) reads then their SNPs will be maintained.

(Sorry, maybe I didn't fully understand your response.)

If part of reference is: AA**T**CGG
and reads at which are:
<sup>Read 1</sup> AA**T**CGG (from father, reference allele)
<sup>Read 2</sup> AA**T**CGG (from father, reference allele)
<sup>Read 3</sup> AA**C**CGG (from mother, alternative allele)
<sup>Read 4</sup> AA**C**CGG (from mother, alternative allele)

According to falcon_sense, it only output **1** consensus read, either reference allele or alternative allele. (Q1) Are my conclusion correct?

(Q2) In falcon_sense: If Read 1 is seed sequence (template read), and Read 2~N are supporting reads.
After reads correction, does these N reads only be reserved **1** read (consensus read)?

(Q3) After Canu correction, the `prefix.correctedReads.fasta` file only account for 25% reads.
Are my result acceptable?

**Comment by skoren** [comment]
1. No, all reads are subject to correction and output. The default is to only output the longest 40x of data input but it won't keep 1/4 reads. There is no guarantee though that the read that had the father allele will maintain only father alleles.

2. No, as I said above, multiple reads will be output and reads that correct other reads can also be output as consensus reads, assuming they're long enough.

3. I'd guess it's a combination of coverage depth (only longest 40x) and the fact that the simulated reads don't accurately reflect real error rates. You don't say how much coverage you have, you could manually add corOutCoverage=all to increase how many reads are corrected over 40x and/or corMhapSensitivity=high (which is likely only needed for the simulated data) to be more premissive with overlaps.
