### ISSUE TITLE
Failed to show the version of canu

### ISSUE THREAD

**Issue by liaochenlanruo** [marbl/canu#1618]
Hi sir,
        There is a problem with running "canu -version" on the Linux system. I have installed canu 1.9 with bioconda, but the result of the command "canu -version" only shows "Canu snapshot ()". Can you tell me how to solve the problem? That is important because the software "circlator" needs the canu version to run.
       Thank you!

**Comment by skoren** [comment]
Not sure what conda is doing, it's build system for canu has been broken in the past and it isn't the recommended way to install Canu. Download the pre-compiled binaries from this page instead and add Canu to your path and the version should be reported correctly.

**Comment by skoren** [comment]
This should be fixed in the next release so conda's built won't be able to mess up canu's version but in the meantime installing canu from the releases page will report the version properly.
