### ISSUE TITLE
Reads coverage too low & disk quota 

### ISSUE THREAD

**Issue by HanKMU** [marbl/canu#1622]
Hi, this this is the follow up of issue #1497.
In last 3 months we're still stuck with the correction step...
**version** Canu 1.9
**system** Linux 

Actually we got 4 ONT FASTQ files and each of them is about 10G. The genome we are going to assemble is about 1G.
**command:** 
```
/opt/canu/Linux-amd64/bin/canu -correct -p ONT_ligase -d EEG388_389 genomeSize=1G maxMemory=500 maxThreads=40 purgeOverlaps=aggressive -nanopore-raw /home/std/hyli/nanopore/EEG388_100fmol_LNB30_mix /home/std/hyli/nanopore/EEG389_100fmol_LNB15_mix /home/std/hyli/nanopore/EEG389_100fmol_LNB60_mix /home/std/hyli/nanopore/EEG389_200fmol_LNB30_mix 1>canu_stdout 2>canu_errout
``` 
This command took approximately 2 months to run and used 5.1T of our disk then stopped since `disk quota exceeded`.
It stopped at: 
```
 ./mhap.sh 96 > ./mhap.000096.out 2>&1
sh: ./mhap.000096.out: Disk quota exceeded
```
.
.
.
```
    ./mhap.sh 203 > ./mhap.000203.out 2>&1
sh: ./mhap.000203.out: Disk quota exceeded
```
it seems there are total 203 should finished, but I can't get more disk quota.

Q1. Is there any way that can calculate how much disk quota it totally need in **correction** stage? Will it release disk quota after finish whole correction stage? (I've read Canu FAQ **My assembly is running out of space, is too slow?** but it's talk about assembly stage already, not the previous correction stage.)

Q2. Will the full log shows how much coverage do I input? Is the `Given 28.8 GB` means it in the picture below? Since I cannot found any information about how many reads does Canu analysis, and I want to make sure my command is right and I input actually 38.8GB of reads within 4 FASTQ files. 

![image](https://user-images.githubusercontent.com/55967210/74710707-43229f00-525d-11ea-9ff2-2245d63ae276.png)

Q3. I've tried to correct only two FASTQ files (about 19G) instead of 4 files at once, will the running speed get faster in this way? 
**command:** 
```
/opt/canu/Linux-amd64/bin/canu -correct -p ONT_ligase -d EEG388_389 genomeSize=1G maxMemory=500 maxThreads=40 purgeOverlaps=aggressive -nanopore-raw /home/std/hyli/nanopore/EEG388_100fmol_LNB30_mix /home/std/hyli/nanopore/EEG389_100fmol_LNB60_mix 1>canu_stdout 2>canu_errout
```
However it showed that 
```
-- ERROR:  Read coverage (9.16) is too low to be useful.
```
but 9.16GB is only one of my input FASTQ file (EEG388_100fmol_LNB30_mix), why the other file (EEG389_100fmol_LNB60_mix) with 10GB being ignored?

Really sorry about this amount of questions but we do really need the help form Canu experts. Thank you very much for your time.

**Comment by skoren** [comment]
It looks from the logs like you are only getting 18x coverage input:
```
Set corMhapSensitivity=high based on read coverage of 18.
```

Which is below our recommendation and requires very sensitive overlapping which, in turn, increases the space usage due to false positive or repeat overlaps. That is likely the source of your space issues. The FAQ lists suggested parameters to decrease space usage on repetitive genomes but it will likely sacrifice continuity. The parameters are applicable to both assembly and correction. I wouldn't recommend downsampling as you'll again sacrifice continuity.

The question to figure out is why you have half the coverage you expect. How did you measure the bases in the fastq file? Canu by default ignores reads shorter than 1kb, have you checked what fraction of the fastq files is in short reads? Can you post the log from the canu loading of your reads (```ONT_ligase.seqStore.err```).

**Comment by HanKMU** [comment]
I see! I think I totally misunderstand the way to evaluate the bases I got in FASTQ file (so sorry about this).

Here is the `ONT_ligase.seqStore.err`:
```
Starting file './ONT_ligase.seqStore.ssi'.

  Loading reads from '/home/std/hyli/nanopore/EEG388_100fmol_LNB30_mix'
    Processed 4348475 lines.
    Loaded 4489443854 bp from:
      869695 FASTQ format reads (4489443854 bp).
    WARNING: 192182 reads (22.0976%) with 106069794 bp (2.3081%) were too short (< 1000bp) and were ignored.

  Loading reads from '/home/std/hyli/nanopore/EEG389_100fmol_LNB15_mix'
    Processed 4232610 lines.
    Loaded 2883999455 bp from:
      846522 FASTQ format reads (2883999455 bp).
    WARNING: 237203 reads (28.0209%) with 134510679 bp (4.4562%) were too short (< 1000bp) and were ignored.

  Loading reads from '/home/std/hyli/nanopore/EEG389_100fmol_LNB60_mix'
    Processed 7860000 lines.
    Loaded 4673802333 bp from:
      1572000 FASTQ format reads (4673802333 bp).
    WARNING: 562464 reads (35.7802%) with 288472107 bp (5.8133%) were too short (< 1000bp) and were ignored.

  Loading reads from '/home/std/hyli/nanopore/EEG389_200fmol_LNB30_mix'
    Processed 10480000 lines.
    Loaded 5985949331 bp from:
      2096000 FASTQ format reads (5985949331 bp).
    WARNING: 838651 reads (40.0120%) with 449115687 bp (6.9792%) were too short (< 1000bp) and were ignored.

Finished with:
  0 warnings (bad base or qv, too short, too long)

Loaded into store:
  18033194973 bp.
  3553717 reads.

Skipped (too short):
  978168267 bp (5.1452%).
  1830500 reads (33.9975%).


sqStoreCreate finished successfully.
```
So does it mean that if we can make sure to increase the base pairs that loaded into store  over 20x coverage then the problem of correction taking time and disk space will solved ?

**Comment by skoren** [comment]
Canu tunes parameters based on coverage, below 30x requires higher sensitivity which makes it use more space/is slower. However, adding reads shorter than 1kb to boost from 20 to 30x isn't going to do much good. You'd likely also still want to use the repetitive genome parameters from the FAQ.

**Comment by skoren** [comment]
Idle
