### ISSUE TITLE
Question Hifi reads

### ISSUE THREAD

**Issue by fmarletaz** [marbl/canu#1623]
I have a question, I have been started to use Hifi reads (and obtained moderately good results, but that might be related to the genome). If I combine normal pacbio reads, are the hifi reads used for error correction, I assumed, they could maybe help phase the regular longer reads, combining the strength of both technologies. Thanks!

**Comment by brianwalenz** [comment]
Nope, sorry, no way to use both types in Canu.  There's some discussion over in issue #1578.
