### ISSUE TITLE
Does `correctedErrorRate` affect correction stage?

### ISSUE THREAD

**Issue by Raina-M** [marbl/canu#1628]
Hi there,

Sorry to ask a very stupid question: I wrongly used parameter `correctedErrorRate=0.03` in **correction stage**, which is supposed to confining corrected reads rather than raw reads. Would this affect the output in correction stage? In another word, does the program ignore this parameter or use it for correction? The correction has ran around one week so it would save lots of time if I could know whether the parameter could mess up my results.

And it looks like correction stage drops a great number of reads because the read coverage decreases from ~68x to ~35x after correction. According to the description of parameter `rawErrorRate`, the default allowed difference in an overlap between two uncorrected reads is **0.300** for PacBio reads, which differs greatly from the value I gave. So I am wondering if the drop of reads is due to the stringent error rate I specify.

FYI, I use canu-1.8, and here is the command:
```
canu -correct  -p hedgehog \
 -d $OUTDIR correctedErrorRate=0.03 \
 genomeSize=2.4g  maxThreads=64  maxMemory=500g \
 -pacbio-raw $PBREADS
```

**Comment by brianwalenz** [comment]
You're safe!  Correction doesn't use correctedErrorRate.

The drop from 68x to 35x is because we only want to generate about 40x in corrected reads; the other reads aren't corrected at all.  The missing 5x is because some reads that we thought would make good corrected reads were not good corrected reads.

**Comment by Raina-M** [comment]
Great. Thank you for the interpretation, which helps a lot!
I will close the issue then.
