### ISSUE TITLE
GFA output

### ISSUE THREAD

**Issue by kevlim83** [marbl/canu#163]
Hi,

I was trying out Canu and wanted to use the gfa output mentioned in the documentation for assembly graph visualization. However, it turns out that although the assembly process completed, no gfa file was produced in the output directory.

I traced back the log files and found that the graph output file was not generated because the unused best edges file was missing. Why is this so? I tried to search but couldnt find any answers online.

Any explanation would be greatly appreciated.

Thanks!

**Comment by brianwalenz** [comment]
I'll guess you have an older version of canu.  There was a period where this output was disabled (IIRC).

**Comment by kevlim83** [comment]
I checked that the version of canu I was using was 1.2.

Perhaps, I'll check out the latest version.
