### ISSUE TITLE
PBSpro mem allocation workaround

### ISSUE THREAD

**Issue by EarlyEvol** [marbl/canu#1631]
Thanks to everyone for working so hard to get PBSpro grid submission working.  I had a small issue and just thought I would put this workaround up incase someone else is having problems with a stupid PBSpro submission requirement.

My grid would not accept the MEMORY allocation because it needed "gb" instead of "g".  I think PBSpro = Perpetually Broken Submission PROblems.  

Anyway, easy work around so far.
In Linux-amd64/lib/site_perl/canu/Execution.pm edit line 915 to:
```
   my $u = "gb";
```
and 945 to:
```
      $u = "mb";
```

It's running ```sqStoreCreate``` now, so first PBSpro hurtle cleared! Now to thrash the server I/O!

General info:
prebuilt canu-1.9 for linux (2/27/2020)
submission command
```~/apps/canu-1.9/Linux-amd64/bin/canu -p Best_species_ever.min20k -d Best_species_ever_canu genomeSize=270m useGrid=true gridOptions="-W group_list=best_lab_ever -q standard  -l walltime=01:00:00" -pacbio-raw ~/WorkingDir/data/PacBio/Best_species_ever.fa.gz```

Original error:
```ERROR:  Failed with exit code 32.  (rc=8192)```

**Comment by skoren** [comment]
I am confused by your fix, since changing 915 to gb would mean line 945 will never get executed at all. Did you also edit the if (line 942) condition to use gb in the check as well? Perhaps we need to expose this as a parameter but I've not seen any other PBSPro or other system that didn't understand "g".

I'd actually suggest the following:
```
 948     # pbs wants units as gb and mb not g and m
 949     if (uc(getGlobal("gridEngine")) eq "PBSPRO")
 950        $u = $u . "b";
```

**Comment by EarlyEvol** [comment]
Oh, I'm a dumby. I missed the eq "g" on line 942...oops.
I guess canu hasn't asked for a non integer of mem, and/or PBS hasn't complained.  The canu.out file makes it look like canu will never ask for a non-integer amount of ram anyway.

As for why PBSpro is getting mad abt "g" vs "gb", I have no idea.  Its pretty clear though. i can reproduce it with any job submission.  
```

$ qsub \
>       -j oe \
>       -l select=1:ncpus=1:mem=4gb \
>       -W group_list=lab \
>       -q standard \
>       -l walltime=01:00:00  \
>       -N 'canu_mem_test' \
>       -o tmp.out  tmp.sh
3034045.head1.cm.cluster
$ qsub \
>       -j oe \
>       -l select=1:ncpus=1:mem=4g \
>       -W group_list=lab \
>       -q standard \
>       -l walltime=01:00:00  \
>       -N 'canu_mem_test' \
>       -o tmp.out  tmp.sh
qsub: adjust_job hook failed with (<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'group'",)). Please contact Admin
```
I have heard that my hpc is trying to switch away from PBS, so maybe this is some artifact of a wrapper layer.  Haven't looked into it.  Doubt it is worth the effort to add a mem units argument though.

If canu crashes with a submission issue I will make the change you suggest. 

Thanks again for all the grid compatibility work. I know it's a huge pain in the butt and I really appreciate it.

Earl
