### ISSUE TITLE
Meryl ERROR：out of perl array limit

### ISSUE THREAD

**Issue by SixPlusSeven** [marbl/canu#1632]
Hi，

I encountered the following problems when using meryl：
```
-- Meryl finished successfully.  Kmer frequency histogram:
Modification of non-creatable array value attempted, subscript -1629355247 at /ehpcdata/genome_analysis/GA_ASM/software/01.canu/01.20190715/Linux-amd64/bin/../lib/site_perl/canu/Meryl.pm line 142, <F> line 171399.
```
The last few lines of the “out.ms16.histogram” file look like this：
```
120768260            1       1.0000       0.9909   308.825693
121210221            1       1.0000       0.9912   309.955865
778740067            1       1.0000       0.9932  1991.375387
2665612049            1       1.0000       1.0000  6816.439079
```
“2665612049” is out of the perl array's max size. How can I solve this?

Thanks!
Alex

**Comment by SixPlusSeven** [comment]
I have changed the Meryl.pm，array to hash，the problem has been solved！

**Comment by skoren** [comment]
Can you make a pull request for your change?

**Comment by SixPlusSeven** [comment]
Here is the changed Meryl.pm:
https://github.com/SixPlusSeven/canu/blob/master/src/pipelines/canu/Meryl.pm

**Comment by SixPlusSeven** [comment]
Another question, how can I read these files generated by minimap: “000001.mmap”、“000001.oc”、“000001.ovb”

**Comment by skoren** [comment]
The mmap file should be the paf output from minimap2, ovb is canu's internal binary format, but it has the same information as the mmap file. See the overlapConvert command: https://canu.readthedocs.io/en/latest/commands/overlapConvert.html

**Comment by SixPlusSeven** [comment]
Thanks for your help！

**Comment by brianwalenz** [comment]
You aren't getting away that easily!  Reopening until we fix the array problem.

**Comment by KaiqiangLiu** [comment]
Hi, 
I encountered exactly the same  problem showed above (canu-1.9),  
My error message is below 
Modification of non-creatable array value attempted, subscript -1010426677 at /home/software/canu-1.9/Linux-amd64/bin/../lib/site_perl/canu/Meryl.pm line 142, <F> line 185218.
Then I replaced the Meryl.pm with  https://github.com/SixPlusSeven/canu/blob/master/src/pipelines/canu/Meryl.pm
but it does not work, either. 
Anyone have suggestions to deal with the error?

Thanks in advance.
