### ISSUE TITLE
Assessing memory usage

### ISSUE THREAD

**Issue by egoltsman** [marbl/canu#1638]
Hi Sergey,
I just completed an assembly of the Rice genome with CCS/HiFi reads, running v.2.0a, and I used a single high-memory (1.5TB) node to do it.  Now I'm trying to gauge what the *absolute* minimum memory requirements would be to do the same on a cluster of commodity nodes with, say, 128 GB available on each one (I can go with as many as I like).   Looking at stdout, it seems like the  overlap store sorting step used the most memory overall, but that was over 36 jobs, which suggests that if these were distributed over multiple nodes the memory footprint would be much lower for that step.
```
Local: ovs       16.000 GB    1 CPU  x  36 jobs   576.000 GB  36 CPUs  (overlap store sorting)
```

On the other hand,  contig construction ran as one job, so I suspect that the 64GB that it needed cannot be partitioned further as it needs the entire graph loaded in memory. 
```
Local: bat       64.000 GB    8 CPUs x   1 job     64.000 GB   8 CPUs  (contig construction with bogart)
```
If my understanding is correct, then contig construction is the overall memory limiting step, and I should request my resources based on that, and not the total memory footprint.   

Also, is there a way to check the total cpu time for all/any of the steps executed?  My appologies if this has been answered in other threads.

Thank you!

Gene

**Comment by skoren** [comment]
What is the exact commit of version v2.0a? I'd recommend using the v2.0-maintenance branch which is the current release candidate for production or wait for the release.

The bat memory often can be lowered without too much impact on assembly, you can force it to be lower by setting maxMemory=32 or batMemory=32. I don't think it actually filled all 64gb of memory. Typically the consensus is the memory limiting steps as its memory is proportional to max contig length so a 150mb contig will take lots of memory (80-ish gb). Luckily rice doesn't have huge chromosomes or a huge genome. Based on my run of the 24kb rice library PacBio released, bat actually only used 5gb of memory. The largest memory usage was consensus at 20gb, as I expected. So I think you can fit this run on 32gb nodes.

As for checking time/cpu, the easiest is to run on a  grid as then each job will have logging from the grid engine and an individual ID. You could also modify Canu's code to call the commands with `/usr/bin/time` but that's more involved.

**Comment by egoltsman** [comment]
Yes, sorry I got impatient to get the latest-greatest. 
Canu branch hicanu_rc +325 changes (r9818 86bb2e221546c76437887d3a0ff5ab9546f85317)

In the staging section, the consensus step doesn't show anything wrt memory. I'm guessing that's because the contig sizes are not yet known and so memory usage is unpredictable (?)

-- Local: cns        -.--- GB    8 CPUs x   - jobs     -.--- GB   - CPUs  (consensus)

But my main point was about how to best distribute the run on the cluster.  Assuming contig sizes will not be large enough to push the memory over 100G, you can still potentially blow out the memory if the graph size is large or the read coverage is excessive, can't you?     
I'm trying to predict what type of assemblies we'd be limited to with commodity nodes (we're considering metagenomes too).

**Comment by skoren** [comment]
It isn't possible to blow out memory, Canu will always load as many overlaps as can fit. It is possible to trigger an error if you set memory so low that too few overlaps get loaded given the genome coverage. Canu tends to be over-aggressive reserving memory for that step. If you have a large memory node it will try to use it but you can force it to be lower.

We pretty never use nodes than 128gb nodes for our assemblies. I expect that should be fine for human sized genomes, metagenomes, etc.

**Comment by egoltsman** [comment]
Don't you need all (best) overlaps loaded for the entire genome in order to build contigs?  Or does the sparse nature of the graph mean you don't ever get that large of a data structure  (unlinke, say a DBG graph)?

**Comment by skoren** [comment]
You do but that isn't much space. There are at most 2 best overlaps per read and each overlap takes about 12 bytes so for a human genome at 50x with 15kb reads you'd fit into a quarter gb of memoryt. Really we load more than just the best, about C per read end (where C = coverage). Even that will be about 15gb for the above example. The sparseness will drop this down further.

**Comment by egoltsman** [comment]
Makes sense, thanks!
