### ISSUE TITLE
output file size is very low

### ISSUE THREAD

**Issue by bioramg** [marbl/canu#1640]
Hi, 
Thank you for your suggestion.
I have submitted full raw read data (8.8 GB) for correction and trimming. 

I don't know my mitochondrial genome size. So, I used pair-end Illumina data and submitted to bbmap tools and suggested that the expected genome size is ~1.24mb. 

If I do not know genome size, can I run this program?

Please suggest to me. 
Thank you.

_Originally posted by @bioramg in https://github.com/marbl/canu/issues/1637#issuecomment-597401572_

**Comment by skoren** [comment]
You don't need to know an exact genome size, it just has to be approximately right (e.g. 3g vs 3.3g is ok but 3g vs 30g is not). 

You haven't clarified what your input is. If you have 10gb of raw data and this is only mitochondrial DNA then you have >1000 fold coverage and 200mb would provide more than enough data for assembly. If your 10gb of raw data is a mixture of nuclear DNA and mitochondrial DNA, then you should be providing the full genome size not the mitochondrial genome size for the run.

**Comment by skoren** [comment]
Idle, continued in #1650
