### ISSUE TITLE
Can't get statistics

### ISSUE THREAD

**Issue by asumann** [marbl/canu#1641]
Hi,

I run Canu v1.5 after all multi step assembly process(I run correction and trim-assemble separately), it doesn't give me stats report. In the given report only see correction& trimming results, unitigging outcome and contig size related information. I searched other directories already, but couldn't find any report which shows N50 and other related statistics. 

Thanks!

**Comment by skoren** [comment]
The 1.5 version is almost 3 years old, it likely predates the report file being added. It may still have an HTML report to report these statistics instead. There are internal files in each step that have some of the statistics you're looking for but you shouldn't be using a 3-yr old version anyway.
