### ISSUE TITLE
memory / thread management question

### ISSUE THREAD

**Issue by egoltsman** [marbl/canu#1649]
Hi,
I'm trying to set up a cluster (slurm) run that would use our resources optimally or close to that.  The run kicks off and finishes ok but takes much longer than I'd expect.   We have many 120G nodes at our disposal, each with at least 64 cores, but  many of the steps in the pipeline utilize only a fraction of that.  I figure that for some operations the parallelization model doesn't scale linearly, but could you confirm that the partitioning below makes sense?  For instance, meryl was set up to run on only 8 threads and the total of 12G of memory (see below).  Canu ended up preparing job arrays of 6 meryl tasks each, with each task ending up (per scheduler's decision) running on a separate node utilizing only 12G and 8 threads - a big waste of nodes' resources.     It seems that it would make more sense to pack everything into a single job here.  Instead, much of the time is spent waiting in queue for all these tasks to schedule.   Is canu leaving the job packing up to the scheduler or is there a way to force tighter packing and fewer jobs?
Thanks!
```
-- Canu 2.0
--
-- Detected Java(TM) Runtime Environment '11.0.5' (from '/usr/lib64/jvm/java/bin/java') without -d64 support.
-- Detected gnuplot version '5.2 patchlevel 2   ' (from 'gnuplot') and image format 'png'.
-- Detected 64 CPUs and 503 gigabytes of memory.
-- Limited to 600g gigabytes from maxMemory option.
-- Detected Slurm with task IDs up to 64999 allowed.
-- 
-- Found 2388 hosts with  64 cores and  117 GB memory under Slurm control.
-- Found 9688 hosts with 272 cores and   86 GB memory under Slurm control.
--
--                         (tag)Threads
--                (tag)Memory         |
--        (tag)             |         |  algorithm
--        -------  ----------  --------  -----------------------------
-- Grid:  meryl     12.000 GB    8 CPUs  (k-mer counting)
-- Grid:  hap        6.000 GB   19 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap    8.000 GB   16 CPUs  (overlap detection with mhap)
-- Grid:  obtovl     8.000 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl     8.000 GB    8 CPUs  (overlap detection)
-- Grid:  cor       16.000 GB    4 CPUs  (read correction)
-- Grid:  ovb        4.000 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       16.000 GB    1 CPU   (overlap store sorting)
-- Grid:  red        8.000 GB    6 CPUs  (read error detection)
-- Grid:  oea        8.000 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat       64.000 GB    8 CPUs  (contig construction with bogart)
-- Grid:  cns        -.--- GB    8 CPUs  (consensus)
-- Grid:  gfa       16.000 GB    8 CPUs  (GFA alignment and processing
```

**Comment by skoren** [comment]
The cores and memory are chosen based on both available resources and the genome size to maximize the number of jobs it can fit in. This assumes more than one job will run on a node. The actual scheduling is up to the cluster. Not sure why it wouldn't put all jobs on a single node since your nodes have 64 cores and 120 GB of ram, then all should've fit on a single node. I don't see an issue with Canu's job selection here though, it seems like the scheduler is reserving complete nodes for jobs instead of sharing them.

**Comment by egoltsman** [comment]
Yes, I suspect that too (pending confirmation from sysadmins).  But why create multi-task arrays if a single job could handle all the data, like in this case?

**Comment by skoren** [comment]
It's often easier to parallelize by process than by thread by dividing the data (or a combination of both). There are often also overheads with trying to get large jobs scheduled and allocating the memory (it's easier to fit a few 10gb jobs than one 80 gb job). Canu usually uses a combination of both to parallelize.

**Comment by egoltsman** [comment]
Will try to get the scheduler to cooperate. Thank you for clarification.
