### ISSUE TITLE
SegFault during unitigging/3-overlapErrorAdjustment/red.sh

### ISSUE THREAD

**Issue by fbemm** [marbl/canu#165]
I ran into a segmentation fault during unitigging/3-overlapErrorAdjustment. Dataset is a bit noisy with lots of smaller reads.

Any idea? Thx!

Read_Frags()-- from 4575001 through 4575838
Read_Frags()-- allocate 2 MB for bases, votes and info, for 838 reads of total length 181594 (13.0000 bytes/base)
Read_Frags()-- from 4575001 through 4575837 -- loaded 181594 bases in 838 reads.
Read_Olaps()-- loading 13209 overlaps.
Extract_Needed_Frags()--  Loading used reads between 89984 and 189983.
Extract_Needed_Frags()--  At overlap 0
Extract_Needed_Frags()--  Loading reads for overlaps 0 to 3
Extract_Needed_Frags()--  reads 3 bases 1325
realloc reads from 0 to 3
realloc bases from 0 to 1590
Extract_Needed_Frags()--  Loaded 3 reads (0.0030%).  Loaded IDs 89984 through 177591.
Extract_Needed_Frags()--  Loading used reads between 296210 and 289983.
Extract_Needed_Frags()--  At overlap 3
Extract_Needed_Frags()--  Loading reads for overlaps 3 to 3
Extract_Needed_Frags()--  reads 0 bases 0

Failed with 'Segmentation fault'

Backtrace (mangled):

/ebio/abt6_projects9/abt6_software/bin/canu/Linux-amd64/bin/findErrors[0x421a8d]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10330)[0x7ff186818330]
/ebio/abt6_projects9/abt6_software/bin/canu/Linux-amd64/bin/findErrors[0x403fbe]
/ebio/abt6_projects9/abt6_software/bin/canu/Linux-amd64/bin/findErrors[0x402c06]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7ff186461f45]
/ebio/abt6_projects9/abt6_software/bin/canu/Linux-amd64/bin/findErrors[0x4033ce]

Backtrace (demangled):

[0] /ebio/abt6_projects9/abt6_software/bin/canu/Linux-amd64/bin/findErrors() [0x421a8d]
[1] /lib/x86_64-linux-gnu/libpthread.so.0::(null) + 0x10330  [0x7ff186818330]
[2] /ebio/abt6_projects9/abt6_software/bin/canu/Linux-amd64/bin/findErrors() [0x403fbe]
[3] /ebio/abt6_projects9/abt6_software/bin/canu/Linux-amd64/bin/findErrors() [0x402c06]
[4] /lib/x86_64-linux-gnu/libc.so.6::(null) + 0xf5  [0x7ff186461f45]
[5] /ebio/abt6_projects9/abt6_software/bin/canu/Linux-amd64/bin/findErrors() [0x4033ce]

GDB:

Segmentation fault

**Comment by skoren** [comment]
What version of Canu are you using, this mostly likely is an out of bounds access so if you could share the data, we can try to reproduce locally.

**Comment by fbemm** [comment]
canu v1.3 (+14 commits) r7630 e25669486e13090410bbade6e91a562bc43ccabb

Data is coming.

**Comment by brianwalenz** [comment]
Thanks for sharing, and being up to date.

We can reproduce with only three directories:
- unitigging/\*gkpStore
- unitigging/\*ovlStore
- unitigging/3-overlapErrorAdjustment (and here, none of the output *.red files)

which should cut down on the transfer considerably.  The \*ovlStore files gzip -1 well.

**Comment by fbemm** [comment]
I uploaded 3 cases (case-[1-3].tar.gz). First two are Pacbio CCS reads. Case 3 has very short reads (better don't ask where they are from).

**Comment by fbemm** [comment]
We just tested release 1.2 and case 1 and 2 run through. So changes in RED from 1.2 to 1.3 are likely to cause the problem.

**Comment by fbemm** [comment]
Any news on the isssue? Did you get the dataset?

**Comment by brianwalenz** [comment]
Got the data, but was unable to do anything with it until today.

Should be fixed.  Remove the 3-\* directories before restarting canu.

You can save a little bit of compute by saving the 0\*.red files from the larger run.  There is a script change that will affect the last job.

**Comment by fbemm** [comment]
Works! Thanks a lot!
