### ISSUE TITLE
mhapConvert failed

### ISSUE THREAD

**Issue by SixPlusSeven** [marbl/canu#1652]
Hi，

I recently encountered the following error when running canu(v1.9)'s mhap:
```
Current # sequences loaded and processed from file: 170000...
Processed 172800 to sequences.
Time (s) to score, hash to-file, and output: 21938.909302665
Total scoring time (s): 442964.015790981
Total time (s): 443574.50363241805
MinHash search time (s): 171865.24058672102
Total matches found: 80717415289
Average number of matches per lookup: 14597.333494104456
Average number of table elements processed per lookup: 136938.33705204717
Average number of table elements processed per match: 9.381051485009475
Average % of hashed sequences hit per lookup: 16.131433111120153
Average % of hashed sequences hit that are matches: 26.183448485469945
Average % of hashed sequences fully compared that are matches: 94.34772718163588
mhapConvert: mhap/mhapConvert.C:118: int main(int, char**): Assertion `W.toint32(5) < W.toint32(6)' failed.
./mhap.sh: line 1968: 13857 Aborted                 (core dumped) $bin/mhapConvert -S ../../out.seqStore -o ./results/$qry.mhap.ovb.WORKING $outPath/$qry.mhap
```
It looks like mhap has finished running, mhapconvert seems to report an error because of out of the memory. 
The *.mhap file's size is about 5T, and the memory of the compute node I can use is 128G. 
How can I solve this problem?

Thanks,
Alex

**Comment by skoren** [comment]
This error is usually a file corruption issue (see #957 for example). The single file is 5TB, that may be an issue with the filesystem not being able to handle a file that big. What does the end of the file look like? You could try the suggestions from #957 (remove the ```001/*WORKING*``` files and ```*.mhap```) and re-run the failing job to see if it succeeds.

**Comment by SixPlusSeven** [comment]
It looks like mhap did not generate the complete result file:
```
$ tail ../000008.mhap
read21079579 read340306 0.103720 70.000000 0 0 19922 19935 0 0 19813 19826
read21079579 read217489 0.120902 28.000000 0 9750 16408 19935 0 8502 12003 12016
read21079579 read293211 0.109769 47.000000 0 5812 18456 19935 0 0 9574 9587
read21079579 read232396 0.192636 5.000000 0 11208 14395 19935 1 438 3582 3756
read21079579 read195984 0.095336 62.000000 0 0 19922 19935 0 2933 26118 26226
read21079579 read247303 0.122112 13.000000 0 11528 14487 19935 0 415 3715 3728
read21079579 read184114 0.109081 59.000000 0 3473 19903 19935 0 0 14238 14251
read21079579 read325463 0.107839 52.000000 0 5723 18967 19935 0 0 11079 11092
read21079579 read305081 0.108833 37.000000 0 6952 16652 19935 0 12 7080 7162
read21079579 read321378 0.129766 63.0000
```
Can I delete the last line of this file and run mhapconvert?

**Comment by skoren** [comment]
I wouldn't just delete the last line since I don't know when it got truncated. I'd remove the whole file and re-run the mhap.sh failed job and see if the error occurs again.

**Comment by SixPlusSeven** [comment]
I rerun the Job, but mhapConvert failed again.
tail mhap.124.out:
```
Total time (s): 1908687.755875637
MinHash search time (s): 158797.756082406
Total matches found: 80717415289
Average number of matches per lookup: 14597.333494104456
Average number of table elements processed per lookup: 136938.33705204717
Average number of table elements processed per match: 9.381051485009475
Average % of hashed sequences hit per lookup: 16.131433111120153
Average % of hashed sequences hit that are matches: 26.183448485469945
Average % of hashed sequences fully compared that are matches: 94.34772718163588
./mhap.sh: line 1968: 11539 Segmentation fault      (core dumped) $bin/mhapConvert -S ../../Shrimp.seqStore -o ./results/$qry.mhap.ovb.WORKING $outPath/$qry.mhap
```
tail results/000124.mhap:
```
read10886396 read5495208 0.077635 8.000000 0 1724 1867 6535 0 152 290 2982
read10886396 read5522424 0.178430 5.000000 0 2321 4792 6535 1 23844 26247 32166
read10886396 read5448563 0.174773 12.000000 0 2579 4623 6535 1 2071 3972 7508
read10886396 read5418856 0.196461 5.000000 0 2248 3979 6535 0 3645 5006 8143
read10886396 read5448562 0.198975 6.000000 0 2236 4737 6535 0 13812 16157 18166
read10886396 read5451460 0.210794 11.000000 0 0 2583 6535 0 3039 5681 9680
read10886396 read5520330 0.123523 6.000000 0 4697 5320 6535 0 14335 14964 17776
read10886396 read5400584 0.175874 7.000000 0 0 2653 6535 1 12988 15619 17134
read10886396 read5520031 0.188128 5.000000 0 4529 5754 6535 0 18116 19156 19169
read10886396 read5366135 0.189291 8.000000 0 3087 4638 6535 0 2046 3537 9932
```
It seems that there is no problem with the file. The reason for the failure of mhapconvert may be out of the memory, but now my available node memory is only so large, how can I solve this problem? Is there a way to reduce the memory consumption of mhapconvert?

Thanks,
Alex

**Comment by skoren** [comment]
Mhapconvert uses no memory (especially compared to the initial java command) so no, it's not a memory issue. The file is likely still corrupted. Out of space issues don't have to only cause corruption at the end of the file. You should make sure you're not out of space or close to the limit. You can also check the file for corruption by making sure all lines have the same word count.

**Comment by SixPlusSeven** [comment]
Okay, thanks for your answers! 
There is another question, my disk space is not enough, can I delete the oc and ovb files immediately after the bucketize program is completed? for example, rm 000302.ovb and 000302.oc when bucket0302 folder is generated.

**Comment by skoren** [comment]
Yes that is safe to do as long as the bucket0302/sliceSizes file is created successfully.

**Comment by SixPlusSeven** [comment]
I am using canu v1.9.
Is the id of the bucket the same as the prefix of the oc and ovb files? I'm worried that I will delete files that should not be deleted.
For example: 000001.oc and 000001.ovb files correspond to the command "./scripts/1-bucketize.sh 1", 000002.oc and 000002.ovb files correspond to the command "./scripts/1-bucketize.sh 2", 000003. oc and 000003.ovb files correspond to the command "./scripts/1-bucketize.sh 3" and so on.

**Comment by skoren** [comment]
Do you have an ovlStore.config file? You can confirm it's one-to-one of ovb/bucket by checking the logs of one of the successful jobs. It will say which ovb file it is using. If they're all loading one then you're safe. You can also use the list of ovb files in the successful bucketizing log files to get the list that is safe to delete.

**Comment by SixPlusSeven** [comment]
My bucketize job failed because of "Too many open files", file "logs/1-bucketize.000001.out":
```
Found perl:
   /usr/bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /usr/bin/java
   openjdk version "1.8.0_65"

Found canu:
   /home/liyl/hanwentao/biosoftware/canu-software/canu-1.9/Linux-amd64/bin/canu
   Canu 1.9

Running job 1 based on command line options.

Attempting to increase maximum allowed processes and open files.
  Max processes per user limited to 514448, no increase possible.
  Changed max open files from 1024 to 4096 (max 4096).


Opened '../Shrimp.seqStore' with 21421196 reads.

Constructing slice 1 for store './out.ovlStore.BUILDING'.
 - Filtering overlaps over 1.0000 fraction error.

Bucketizing input    1 out of    1 - '1-overlapper/results/000001.ovb'
Failed to open './out.ovlStore.BUILDING/create0001/slice4090' for writing: Too many open files
```
Can the number of files opened simultaneously by ovStoreBucketizer be reduced?

**Comment by skoren** [comment]
I'm confused, weren't you already on bucket0302, this is running bucket0001? Is this a new run or a restart? You can lower the number of slices by increasing the ovsMemory to make larger sorting jobs, try 32 or 64. You'd have to remove the BUILDING folder and re-start Canu to make it re-compute the partitioning again with the large sorting jobs.

**Comment by SixPlusSeven** [comment]
Bucket0302 is an example I gave, I am currently running the 1-bucketize.sh program like this:
```
./scripts/1-bucketize.sh 1 > ./logs/1-bucketize.000001.out 2>&1
```
ovsMemory seems to be a parameter of scripts / 2-sort.sh, Will it affect ovStoreBucketizer?

**Comment by SixPlusSeven** [comment]
Oh, I get it. I increase the ovsMemory and rerun the ovStoreConfig. Thanks!

**Comment by skoren** [comment]
Yep that is correct, you want to-reun the configuration to scale for new memory. It should let you know how many sorting jobs are created, this is how many slices each bucket will have to make sure it is below your max open file limit.
