### ISSUE TITLE
Error: Finished stage 'obt-splitReads', reset canuIteration.

### ISSUE THREAD

**Issue by bioramg** [marbl/canu#1653]
Hi,
I used the following commands:
./../bin/bin/canu-1.9/Linux-amd64/bin/canu -p ONT -d ONT genomeSize=100m batMemory=188 -nanopore-raw ONT.fastq.gz

```
-- Finished stage 'obt-splitReads', reset canuIteration.
----------------------------------------
-- Starting command on Mon Mar 23 13:34:06 2020 with 503.86 GB free disk space

    cd trimming/3-overlapbasedtrimming
    /home/pmslab/Desktop/Raman/bin/bin/canu-1.9/Linux-amd64/bin/loadTrimmedReads \
      -S ../../ONT.seqStore \
      -c ./ONT.2.splitReads.clear \
    > ./ONT.loadtrimmedReads.err 2>&1

-- Finished on Mon Mar 23 13:34:06 2020 (lickety-split) with 503.83 GB free disk space
----------------------------------------
--
-- ERROR:  Read coverage (8.9) is too low to be useful.
-- ERROR:
-- ERROR:  This could be caused by an incorrect genomeSize or poor quality reads that could not
-- ERROR:  be sufficiently corrected.
-- ERROR:
-- ERROR:  You can force Canu to continue by decreasing parameter stopOnLowCoverage=10,
-- ERROR:  however, the quality of corrected reads and/or contiguity of contigs will be poor.
--

ABORT:
ABORT: Canu 1.9
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```

**Comment by skoren** [comment]
I'm not sure what your question is, the error message explains why Canu stopped. You ended up with too little coverage to be useful for assembly (<10x). How much coverage did you start with? If you have <30x coverage, you can use the parameters recommended on the FAQ: https://canu.readthedocs.io/en/latest/faq.html#what-parameters-can-i-tweak

**Comment by bioramg** [comment]
My average genome coverage is 87.7x based on ONT bases and calculated using coverage and bases and the expected genome size is ~89 MB.
When I assembled both Illumina and ONT hybrid assembly using SPADES, most of the mitochondrial contigs having ~25x coverage.
Should I delete any files in that folder? or shall I include this command with previous and re-run the same analysis? or a new one?

**Comment by skoren** [comment]
You don't need to remove any files, add the stop option to the command and re-launch. Given almost 90x coverage of the genome, I'm surprised you ended up with so little corrected data but hopefully it's enough for the mitochondria. If not, you could take a look at the FAQ for other parameters to tweak to improve the assembly.

**Comment by bioramg** [comment]
Thank you. But unfortunately I deleted all file and started re-run will all parameters with modification of genomeSize60m stopOnLowCoverage=0.

I will let you know after getting results. Thank you for your valuable suggestions.
