### ISSUE TITLE
ovS std::bad_alloc

### ISSUE THREAD

**Issue by hung-th** [marbl/canu#1654]
I am running the following on a slurm grid.

Command:
`/home/univ4423/bin/canu-1.9/Linux-amd64/bin/canu -p DBCO -d DBCO_canu-correct genomeSize=1.5g corOutCoverage=60 corMhapSensitivity=normal -pacbio-raw DBCO_pacbio.fasta -nanopore-raw DBCO_npfilter.fastq -gridOptionsCORMHAP="--time=120:00:00 --cpus-per-task=16" -gridOptionsOVS="--mem-per-cpu=64g"`

Canu version:
`Canu 1.9`

```
Running job 37 based on SLURM_ARRAY_TASK_ID=37 and offset=0.

Attempting to increase maximum allowed processes and open files.
  Changed max processes per user from 4096 to 514842 (max 514842).
  Changed max open files from 1024 to 51200 (max 51200).


Finding overlaps.
  found   10334359 overlaps in './DBCO.ovlStore.BUILDING/bucket0001/sliceSizes'.
  found    9961692 overlaps in './DBCO.ovlStore.BUILDING/bucket0005/sliceSizes'.
  found    9738384 overlaps in './DBCO.ovlStore.BUILDING/bucket0009/sliceSizes'.
  found    9729733 overlaps in './DBCO.ovlStore.BUILDING/bucket0013/sliceSizes'.
  found    9677911 overlaps in './DBCO.ovlStore.BUILDING/bucket0017/sliceSizes'.
  found    9797527 overlaps in './DBCO.ovlStore.BUILDING/bucket0021/sliceSizes'.
  found    9859773 overlaps in './DBCO.ovlStore.BUILDING/bucket0025/sliceSizes'.
  found    9766189 overlaps in './DBCO.ovlStore.BUILDING/bucket0029/sliceSizes'.
  found    9649750 overlaps in './DBCO.ovlStore.BUILDING/bucket0033/sliceSizes'.
  found    9776723 overlaps in './DBCO.ovlStore.BUILDING/bucket0037/sliceSizes'.
  found    9974397 overlaps in './DBCO.ovlStore.BUILDING/bucket0041/sliceSizes'.
  found   10078624 overlaps in './DBCO.ovlStore.BUILDING/bucket0045/sliceSizes'.
  found    9920468 overlaps in './DBCO.ovlStore.BUILDING/bucket0049/sliceSizes'.
  found    9898727 overlaps in './DBCO.ovlStore.BUILDING/bucket0053/sliceSizes'.
  found    9787705 overlaps in './DBCO.ovlStore.BUILDING/bucket0057/sliceSizes'.
  found   10111467 overlaps in './DBCO.ovlStore.BUILDING/bucket0061/sliceSizes'.
  found    9719937 overlaps in './DBCO.ovlStore.BUILDING/bucket0065/sliceSizes'.
  found    9737440 overlaps in './DBCO.ovlStore.BUILDING/bucket0069/sliceSizes'.
  found    9703368 overlaps in './DBCO.ovlStore.BUILDING/bucket0073/sliceSizes'.
  found    9904540 overlaps in './DBCO.ovlStore.BUILDING/bucket0077/sliceSizes'.
  found    9774365 overlaps in './DBCO.ovlStore.BUILDING/bucket0081/sliceSizes'.
  found    9673771 overlaps in './DBCO.ovlStore.BUILDING/bucket0085/sliceSizes'.
  found    9928412 overlaps in './DBCO.ovlStore.BUILDING/bucket0089/sliceSizes'.
  found    9978751 overlaps in './DBCO.ovlStore.BUILDING/bucket0093/sliceSizes'.
  found    9865981 overlaps in './DBCO.ovlStore.BUILDING/bucket0097/sliceSizes'.
  found    9737239 overlaps in './DBCO.ovlStore.BUILDING/bucket0101/sliceSizes'.
  found  404961799 overlaps in './DBCO.ovlStore.BUILDING/bucket0105/sliceSizes'.
  found  361569518 overlaps in './DBCO.ovlStore.BUILDING/bucket0106/sliceSizes'.
  found   96819721 overlaps in './DBCO.ovlStore.BUILDING/bucket0107/sliceSizes'.
  found   38071157 overlaps in './DBCO.ovlStore.BUILDING/bucket0108/sliceSizes'.
  found   37229242 overlaps in './DBCO.ovlStore.BUILDING/bucket0109/sliceSizes'.
  found   32592930 overlaps in './DBCO.ovlStore.BUILDING/bucket0110/sliceSizes'.
  found    9636486 overlaps in './DBCO.ovlStore.BUILDING/bucket0111/sliceSizes'.
  found    3596765 overlaps in './DBCO.ovlStore.BUILDING/bucket0112/sliceSizes'.

Loading 1240564851 overlaps using 27.73 GB of allowed (-M) 64 GB memory.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Failed with 'Aborted'; backtrace (libbacktrace):
utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP7siginfoPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
../../gcc-7.3.0/libstdc++-v3/libsupc++/vterminate.cc::95 in _ZN9__gnu_cxx27__verbose_terminate_handlerEv()
../../gcc-7.3.0/libstdc++-v3/libsupc++/eh_terminate.cc::47 in _ZN10__cxxabiv111__terminateEPFvvE()
../../gcc-7.3.0/libstdc++-v3/libsupc++/eh_terminate.cc::57 in _ZSt9terminatev()
../../gcc-7.3.0/libstdc++-v3/libsupc++/eh_throw.cc::93 in __cxa_throw()
../../gcc-7.3.0/libstdc++-v3/libsupc++/new_op.cc::54 in _Znwm()
stores/ovStoreSorter.C::224 in main()
(null)::0 in (null)()
(null)::0 in (null)()
/var/spool/slurmd/job805896/slurm_script: line 114:  9469 Aborted                 (core dumped) $bin/ovStoreSorter -deletelate -O ./DBCO.ovlStore.BUILDING -S ../DBCO.seqStore -C ./DBCO.ovlStore.config -f -s $jobid -M 64
```

Similar instances happened on multiple jobs.

Your advice would be much appreciated.

**Comment by skoren** [comment]
This usually happens from disk corruption, not actually a memory error (for example #1485). I'd guess all the jobs failing have issues with the same bucket input in common. Try to see if you can find a bucket ID in common between all the failing jobs that also isn't in any successful jobs(I assume some succeeded?). 

If you find one (or more), say bucket0112, try removing that bucket folder and from inside the DBCO.ovlStore.BUILDING folder run ```sh scripts/1-bucketize.sh 112``` (or whatever bucket failed). Then try re-running the failed sorting job (```sh scripts/2-sort.sh 37```). You may need to re-generate more than one bucket depending on where the disk corruption is.

**Comment by hung-th** [comment]
Thank you for your comments.

How should I determine which bucket is failing? From the above example, it seems the job has founded all the buckets properly and failed immediately after trying to load any overlaps. Similar errors are widespread in the jobs.

**Comment by hung-th** [comment]
Thank you very much for your comments.

I got what you meant, but it seems the failures are too widespread in the jobs and is quite hard to find the common buckets. Also, because I tried running and killing several times, there are lots of mixing output files in the directory. Probably it would be faster for me just to re-run canu from bucketizing?

**Comment by skoren** [comment]
Yes, you can remove the full BUILDING folder and re-launch Canu and it will re-bucketize and re-sort. In case your filesystem had issues because there were too many jobs, you can try limiting them. Since you're on slurm, add ```gridEngineArrayOption="-a ARRAY_JOBS%20"```, this will limit Canu to 20 jobs (probably over-conservative).

**Comment by hung-th** [comment]
I cleaned the entire 1-overlapper, but it hit another error at the same ovS stage.

`
found   20219117 overlaps in './DBCO.ovlStore.BUILDING/bucket0426/sliceSizes'.
  found   20929912 overlaps in './DBCO.ovlStore.BUILDING/bucket0427/sliceSizes'.
  found   21386163 overlaps in './DBCO.ovlStore.BUILDING/bucket0428/sliceSizes'.
  found   21664221 overlaps in './DBCO.ovlStore.BUILDING/bucket0429/sliceSizes'.
  found   21988250 overlaps in './DBCO.ovlStore.BUILDING/bucket0430/sliceSizes'.
  found   22406476 overlaps in './DBCO.ovlStore.BUILDING/bucket0431/sliceSizes'.
  found  196492115 overlaps in './DBCO.ovlStore.BUILDING/bucket0432/sliceSizes'.

Loading 1240418064 overlaps using 27.73 GB of allowed (-M) 29 GB memory.
/var/spool/slurmd/job816100/slurm_script: line 114: 76434 Killed                  $bin/ovStoreSorter -deletelate -O ./DBCO.ovlStore.BUILDING -S ../DBCO.seqStore -C ./DBCO.ovlStore.config -f -s $jobid -M 29

`

**Comment by skoren** [comment]
Increasing memory for the sorting jobs should avoid this. To confirm, you can running one of the failing jobs by hand on a node with more memory reserved (currently you're using 32, try reserving 40 or 45g) and running the sort job by hand inside the BUILDING folder (```sh scripts/2-sort.sh <jobid>```). If that works, you should be able to increase the ovsMemory (either by adding ```ovsMemory=45``` to canu or by editing the ```scripts/2-sort.jobSubmit*sh``` files to change their request to the grid).

**Comment by hung-th** [comment]
45g failed, it worked for some at 60g but still many are failing. I wonder if I need to use even more. I would try to increase to 128g using some high-memory nodes.

**Comment by hung-th** [comment]
I tried 380g then about 30 still failed. Finally I had to use the 1.5TB nodes. But fortunately it is all done now and proceeded to next stage.

I wonder why such high memory is needed?

**Comment by skoren** [comment]
I can't imagine it ever actually using 1.5 TB. I'd guess there is something strange with the memory tracking/request. You can check the completed job IDs for how much memory the jobs actually used with slurs.

**Comment by hung-th** [comment]
You were that most jobs were capped at 29 Gb - it is really strange though, could it be intra-node jobs competing?

**Comment by skoren** [comment]
That shouldn't be an issue with jobs competing on a node since the were requesting the right amount of memory. It must be an issue with how your slurm configuration is tracking memory usage. I'd suggest asking your IT group why the jobs were being killed and show them the memory usage of the job that needed >64gb but actually report being limited to 29gb or much lower than the request you had to use. 

I'm going to close the issue since you've gotten past this step but do post a followup if you hear back or find out why the jobs were being terminated.
