### ISSUE TITLE
Didn't find canu in path. Looked for:canu

### ISSUE THREAD

**Issue by jellila** [marbl/canu#1656]
Hi,

I am using circlator in conda on Mac. When I run progcheck I get:

```
Circlator version: 1.5.5

External dependencies:
bwa 0.7.17 /Users/laura/miniconda3/envs/sanger/bin/bwa
WARNING: Didn't find canu in path. Looked for:canu
nucmer 3.1 /Users/laura/miniconda3/envs/sanger/bin/nucmer
prodigal 2.6.3 /Users/laura/miniconda3/envs/sanger/bin/prodigal
samtools 1.9 /Users/laura/miniconda3/envs/sanger/bin/samtools
WARNING: SPAdes version 3.14.0 is being used. It will work, but better results are usually obtained from Circlator using SPAdes version 3.7.1. Although 3.7.1 is not the latest version, we recommend it for Circlator.
spades 3.14.0 /Users/laura/miniconda3/envs/sanger/bin/spades.py

Python version:
3.6.10 | packaged by conda-forge | (default, Mar 5 2020, 09:56:10)
[GCC Clang 9.0.1 ]

Python dependencies:
openpyxl 2.4.0-b1 /Users/laura/miniconda3/envs/sanger/lib/python3.6/site-packages/openpyxl/init.py
pyfastaq 3.17.0 /Users/laura/miniconda3/envs/sanger/lib/python3.6/site-packages/pyfastaq/init.py
pymummer 0.11.0 /Users/laura/miniconda3/envs/sanger/lib/python3.6/site-packages/pymummer/init.py
pysam 0.15.3 /Users/laura/miniconda3/envs/sanger/lib/python3.6/site-packages/pysam/init.py
```
but canu is already in my path:

```
(base) 192-168-1-106:~ laura$ echo $PATH /Users/laura/miniconda3/bin:/Users/laura/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/laura/canu-2.0/Darwin-amd64/bin/canu
```

Can anyone help me, please? :)

**Comment by skoren** [comment]
Have you tried running ```which canu```? 

I'm pretty sure your path is incorrect. The path you have is ```/Users/laura/canu-2.0/Darwin-amd64/bin/canu``` so it's going to look for a file named ````/Users/laura/canu-2.0/Darwin-amd64/bin/canu/canu```, you want your path to use ````/Users/laura/canu-2.0/Darwin-amd64/bin```

**Comment by jellila** [comment]
Oh, right I got it! Thank you. However, I have noticed that the path keeps disappearing from $PATH, now I get only 
`(base) 192-168-1-106:~ laura$ echo $PATH
/Users/laura/miniconda3/bin:/Users/laura/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin`
I am sorry, maybe it's a really silly situation, but I am not really experienced.

**Comment by skoren** [comment]
The path doesn't persist between sessions unless you modify your environment (something like .profile or .bashrc depending on shell/OS).

**Comment by jellila** [comment]
Oh, I didn't know that, thank you! It took me a while but I managed to solved the problem. Part of the reason why it was not working though (even when using the correct path) is that the terminal could not open the files downloaded from github, so I had to manually force the opening and then everything worked. So, my next and last question is, is there a way to save time and avoid opening every single file I download? :) thank you again for your help!

**Comment by skoren** [comment]
I'm not sure what you mean "opening"? Does it say they don't have execute permissions?

**Comment by jellila** [comment]
I get this message "macOS cannot verify the developer of “.........”. Are you sure you want to open it? By opening this app, you will be overriding system security which can expose your computer and personal information to malware that may harm your Mac or compromise your privacy."

**Comment by skoren** [comment]
Are you running canu in the terminal or by double-clicking the files? I've not seen that error if I just run canu or the related commands in terminal directly.

**Comment by jellila** [comment]
I am running it in the terminal. When I got that message I thought that was why it was giving me problems and I had to open the single files.

**Comment by skoren** [comment]
I've not seen that before but some quick googling says this may work:
```
xattr -r -d com.apple.quarantine <wherever canu/other apps you want to run is>
```

**Comment by jellila** [comment]
Great! Thank you very much :)
