### ISSUE TITLE
bubble contigs

### ISSUE THREAD

**Issue by pjm43** [marbl/canu#1657]
Sergey,

I'm running a HiFi assembly (-pacbio-hifi) using your newly released Canu 2.0 using default parameters.  I'm working with an allotetraploid inbred plant species that shows normal diploid inheritance.  GenomeScope reflects a low level of heterozygosity (0.25%). 

The assembly came together quickly and nicely, but I'm trying to wrap my head around the report (see below).  What I'm struggling the most with is understand the difference between contigs and bubbles.  The contigs seem pretty straight forward, but the bubbles are throwing me for a loop.  I read in your Nurk et al. 2020 paper that they represent "alternative alleles within the set of greedy contigs".  That suggests to me that they should not be considered in the total genome length.  Do I have that right?  But why then are they reported in the .contig.fasta file?  I'm trying to get to a haploid genome for the species.  should I just consider the contigs, recognizing that  bubble contigs are reported simply represent the opposing alleles?  I know I've probably way oversimplified things here and would appreciate any insight on how to handle the "bubble contigs".

I also read in your manuscript that you recommend "because placements are not always found, especially for longer, more heterozygous alleles, we recommend using a post-processing tool such as Purge_dups (Guan et al. 2020) to classify alternate alleles and remove any false duplications".  Does running Purge_dups remove the alternative alleles (bubble contigs) and produce a better haploid genome.

Again, thanks before hand for answering my question,

Jeff

 

```
[UNITIGGING/OVERLAPS]
--   category            reads     %          read length        feature size or coverage  analysis
--   ----------------  -------  -------  ----------------------  ------------------------  --------------------
--   middle-missing      16952    0.32    14049.06 +- 3668.21       1067.37 +- 1742.82    (bad trimming)
--   middle-hump           289    0.01    14189.66 +- 2557.47       4178.14 +- 2717.74    (bad trimming)
--   no-5-prime          10155    0.19    12400.20 +- 2359.86       3016.69 +- 3230.23    (bad trimming)
--   no-3-prime          10583    0.20    12321.01 +- 2379.44       3067.24 +- 3263.88    (bad trimming)
--
--   low-coverage        14744    0.28    11425.14 +- 1979.86          4.42 +- 2.60       (easy to assemble, potential for lower quality consensus)
--   unique            2221510   41.69    12251.13 +- 2121.23         42.94 +- 8.55       (easy to assemble, perfect, yay)
--   repeat-cont        241762    4.54    11752.60 +- 2013.39        647.27 +- 1263.62    (potential for consensus errors, no impact on assembly)
--   repeat-dove          9286    0.17    16331.57 +- 2022.91        191.40 +- 418.23     (hard to assemble, likely won't assemble correctly or even at all)
--
--   span-repeat       1121543   21.04    12720.36 +- 2208.55       4637.19 +- 3883.62    (read spans a large repeat, usually easy to assemble)
--   uniq-repeat-cont  1268878   23.81    12024.70 +- 1624.91                             (should be uniquely placed, low potential for consensus errors, no impact on assembly)
--   uniq-repeat-dove   205144    3.85    15568.72 +- 2226.25                             (will end contigs, potential to misassemble)
--   uniq-anchor        152050    2.85    12634.07 +- 2204.26       5139.05 +- 3682.62    (repeat read, with unique section, probable bad read)

[UNITIGGING/ADJUSTMENT]
-- No report available.

[UNITIGGING/CONTIGS]
-- Found, in version 1, after unitig construction:
--   contigs:      3269 sequences, total length 1401268543 bp (including 70 repeats of total length 1106880 bp).
--   bubbles:      17347 sequences, total length 414794100 bp.
--   unassembled:  125874 sequences, total length 1557421186 bp.
--
-- Contig sizes based on genome size 2.6gbp:
--
--            NG (bp)  LG (contigs)    sum (bp)
--         ----------  ------------  ----------
--     10    41721566             5   281201342
--     20    25503799            13   537968047
--     30    12624405            28   788456990
--     40     5615652            59  1040634510
--     50      292921           246  1300074646
--

[UNITIGGING/CONSENSUS]
-- Found, in version 2, after consensus generation:
--   contigs:      3269 sequences, total length 1939798503 bp (including 70 repeats of total length 1565209 bp).
--   bubbles:      17347 sequences, total length 576120036 bp.
--   unassembled:  125874 sequences, total length 2232475284 bp.
--
-- Contig sizes based on genome size 2.6gbp:
--
--            NG (bp)  LG (contigs)    sum (bp)
--         ----------  ------------  ----------
--     10    77269270             4   332047212
--     20    51176359             8   549341247
--     30    28760754            15   807036139
--     40    19084922            26  1055973286
--     50    10844651            43  1303397010
--     60     4343351            80  1563511033
--     70      262469           321  1820191154
```

**Comment by skoren** [comment]
For HiFi data, 0.25% is extremely heterozygous. 

The bubbles are exactly that, they are alternate alleles. They are in the contigs file since that represents the full output of the assembly. Since we only try to identify the bubbles that would affect assembly continuity, not necessarily all alleles present. You need to run purge_dups to identify all alternate alleles in the assembly and produce a haploid assembly. It won't give you a "better" assembly, in the sense that the contigs will largely be the same, but it will partition your contigs into a set of primary and alternate contigs.

**Comment by pjm43** [comment]
Thanks for the quick response.  Just to clarify, once I run purge_dup, I can calculate the assembly statistics for the haploid genome based on just the primary contigs.  Correct?   

I'm puzzled by your comment that 0.25% is extremely high heterozygosity for HiFi data.  I made the estimate using Genomescope.  When I look at the heterozygosity values for their example species (bird, oyster, arabidopsis F1, etc.), they all have much higher heterozygosity values - hence my confusion as to why you said my estimate is extremely high - am I missing something here?

Thanks again,

Jeff

**Comment by snurk** [comment]
Dear @pjm43, @skoren meant that 0.25% should be enough to reconstruct long stretches individual

**Comment by snurk** [comment]
Dear @pjm43, @skoren meant 0.25% is high enough for us to separate most of the alternative alleles based on HiFi data. Also 'yes' to the primary contigs representing our best guess about the 'haploid' genome.

**Comment by pjm43** [comment]
Thanks the quick response.  Much appreciated!
