### ISSUE TITLE
Translocation on Dmel HiFi

### ISSUE THREAD

**Issue by snurk** [marbl/canu#1660]
Reproduced in particular by c68b5e711ef0fa394e87fdd4233c3b64e1903cac commit in the confusion_fixes_rebased branch. Somehow the 'confusion' that should be clearly present around reads 189473 and 156610 is not detected.

**Comment by snurk** [comment]
I don’t think that we should be focusing on orphan contigs right now
In particular, I don’t think that the read that @brianwalenz  was reporting as ‘critical’ to the whole situation (read 134141) should be our focus.
I see the following: 189473 is lopsided and not used; we know that 156610 is bad, but bogart has no simple way of knowing that right now, so it is used; it’s best (relatively weak) overlap leads us to read 203272.
In turn the ACTUAL best overlap of 203272 on that side is read 67704.
Read 134141 is not present in their overlaps, so I don’t think it is relevant.
Thus the question is: *why read 203272 wasn’t confused by read 67704 which gives a much better overlap to it than the one we used (156610)*
What is the next step to figure it out?

**Comment by skoren** [comment]
The confused read is pushed out of the tig by a placed spur (164048) which probably shouldn't have been inserted here in the first place.

**Comment by skoren** [comment]
Another issues is that the mean/stdev computation here is corrupted, ending up with invalid thresholds.

**Comment by skoren** [comment]
Fixed contained read placement to use correct thresholds (936917ff4759b610738963370b8dc7b8fb60ab37) and fixed mean/stdev (#1665) so this should be addressed
