### ISSUE TITLE
0.0 erate considered 'high error' in orphan merging procedure

### ISSUE THREAD

**Issue by snurk** [marbl/canu#1665]

**Comment by skoren** [comment]
There should never be floats comparing to absolute 0, overlapConsistentWithTig needs to have a minimum value like 1e-10. Print should not round to 2 significant digits.

**Comment by brianwalenz** [comment]
Should be fixed with marbl/meryl-utility@fab095151393ff3f6f1fa4f35666ca06b99ffb9b.  HT to @skoren for the debugging that led to the simple example there.

**Comment by brianwalenz** [comment]
You jerk.
```
==> PLACE CONTAINED READS.

computeErrorProfiles()-- Computing error profiles for 8334 tigs, with 1 thread.
ERROR: stdDev has negative variance; mismatch in values supplied to insert() and remove()?
```

**Comment by skoren** [comment]
Fixed by utility changes to stdev/mean calculation and increased precision (6104ec8d7ad01e32ae49c3a15e2b33b43cdc45e8) to improve logging.
