### ISSUE TITLE
Amplicon Sequencing Help

### ISSUE THREAD

**Issue by jiangweiyao** [marbl/canu#1671]
Hi. I have been trying to use Canu to do some amplicon error correction and get my amplicon sequences. I looked through the FAQs and previous issues, and still get inconsistent results. I am very confused by the results and wondering if I could get some help.

The amplicons are generated by a multiplex PCR, and between 1-3 amplicons (1.3kb, 1.5kb, and 2kb) can appear. The full length amplicons are sequenced via Nanopore Minion. I would like to get the error corrected or consensus sequence of these amplicons. I have tried a number of options detailed below, and I notice that the reads of the larger amplicons keep going into unassembled.fasta (with many lines of them with read=1), while the smaller amplicons go into contigs.fasta with read=many. How do I ensure my larger amplicons behave like my smaller amplicons (get a consensus of reads in contigs.fasta)? I am happy to send the sequencing data (or whatever else you need) if you would like to take a look at it. 

I am running this on Linux (Ubuntu 18.04) with Canu version 1.9 or 2.0 installed via Conda. The command I have used is below. I have tried changing contigFilter="2 0 1.0 0.5 0". Increased and decreased the minReadLength, and increased and decreased the correctedErrorRate. 
```
canu -p asm useGrid=0 -nanopore-raw BC01_1kb_5k.fastq -d canu_BC01_1kb_5k genomeSize=2000 minReadLength=1200 minOverlapLength=100 contigFilter="1 0 1.0 0.5 0" readSamplingCoverage=5000 correctedErrorRate=0.25
```

Many thanks for your help.

**Comment by skoren** [comment]
I am not sure what your goal is, if you want to just get a high-accuracy version of the amplicon, all you want to run is correction. Each corrected read is a consensus of multiple raw reads so it will have good consensus accuracy. The subsequent assembly steps will try to join reads that overlap into a single contig but this probably isn' what you want anyway. I'd guess the larger amplicons don't have enough overlaps to be assembled.

**Comment by jiangweiyao** [comment]
Thanks for your answer. Your overlap comment makes sense. I guess the correction step is what I am having trouble with then.

I looked in asm.correctedReads.fasta.gz for one of my runs, and I get 1637 corrected reads. I did a quick analysis, and 3 of the first 4 reads for example are >95% identical to each other through BLASTN (although slightly different in length at the ends). Is this the expected behavior or did I use an incorrect option? If it is, how do I select my 3 amplicons from the all selected reads?

Thank you again for your help.

**Comment by skoren** [comment]
Yes the corrected reads will be redundant with each other, you also were forcing the output of a lot of reads using the ```readSamplingCoverage``` option. If you remove that and run you'd get less redundancy. 

You can select reads arbitrarily, each one is error-corrected, so you could just take the first representative or do some sort of clustering on the reads and select a representative that way. Just treat the corrected reads as high-accuracy amplicon sequencing results.

**Comment by jiangweiyao** [comment]
Got it. Any particular recommendations? I am thinking CD-hit or swarm, but appreciate any suggestions. Thank you very much.
