### ISSUE TITLE
canu restart using a different queue

### ISSUE THREAD

**Issue by davidaray** [marbl/canu#1675]
Thanks for this useful tool.

My question regards restarting the assembly. I see on the read the docs page that it's possible to restart by re-running the exact command but I'm not sure if what I'm proposing will work.

We have two queues on our system. One only allows a 2 day walltime. The other allows 5 days. 

Trying to be safe, I chose to run canu using the longer walltime. Unfortunately, there are fewer slots in the queue and I've now reached the "obtovl_" stage and there are 725 jobs. Each job is taking a day and after 1 week, I'm only on job 12. At this rate it will be well over a month before this part of the assembly is done. And I'm not even sure where we are in the process. It's already been over a month since I started it.

So, my question is this; Would it be possible to restart the assembly and pick up where it left off but still change the queue I'm using. 

My original command line usage was via the submission script below:
```
#$ -V
#$ -cwd
#$ -S /bin/bash
#$ -N canu_geomys
#$ -o $JOB_NAME.o$JOB_ID
#$ -e $JOB_NAME.e$JOB_ID
#$ -q omni
#$ -pe sm 36
#$ -l h_rt=120:00:00
#$ -P xlquanah

#Add canu to system path
CANU_PATH=/lustre/work/daray/software/canu-1.8/Linux-amd64/bin

#Export path
export PATH=$PATH:$CANU_PATH

#Load gnuplot module 

module load gnu gnuplot

#Configure Canu for properly use Grid Engin, here I modified quanah for xlquanah 

export CANU_UGE_OPTIONS=( "useGrid=true" "gridEngineThreadsOption=-pe sm THREADS" "gridEngineMemoryOption=-l h_vmem=MEMORY" "gridOptions=-P xlquanah" ) 

#Run Canu, genome size was set up to 3.3GB
canu -d . -p geomys genomeSize=3.3g -nanopore-raw raw_pacbio/*.fastq "${CANU_UGE_OPTIONS[@]}" 
```
As you can see in the commands, I'm using "xlquanah" as the queue. I'd like to switch to the normal queue, "guanah". 

Is it possible to kill the current assembly, switch out the queue name and then restart, picking up where I left off?

Thanks.

David

**Comment by skoren** [comment]
Yes, can update the command to use the other queue. Just change the command and the restart will launch jobs for the new name. You have to make sure you kill all canu jobs (the obtovl and the job waiting on them) and make sure no Canu jobs are running before you restart.

Another option is to use qalter to just change the runtime and project of the obtovl jobs without killing them. I see you're using the -P option, that is normally a project name not a queue but I guess on your system different projects have different nodes assigned to them. I am not sure if qalter lets you modify projects, it should let you modify walltime and queues. If qalter doesn't let you change project on a running job then you'd have to restart following the above.

**Comment by davidaray** [comment]
Thanks very much. I made the change and the analyses appears too have picked right back up and is humming along. Already to obtovl jog number 76 and I only started it earlier this morning.

**Comment by skoren** [comment]
OK, will close the issue then. Open a new one if you hit errors in the run.
