### ISSUE TITLE
Question: qcat trimmed nanopore reads, use '-trimmed'?

### ISSUE THREAD

**Issue by JWDebler** [marbl/canu#1676]
Hi,

I have demultiplexed nanopore reads where adapters and barcodes were trimmed using qcat. Should I therefore run canu with the -trimmed option?

Cheers

**Comment by brianwalenz** [comment]
Nope.  qcat is just demultiplexing and trimming off barcodes.  Canu will still need to trim off the low quality and garbage sequence to get a good assembly.

**Comment by JWDebler** [comment]
Thanks for the clarification.
