### ISSUE TITLE
Job failed after unitig

### ISSUE THREAD

**Issue by yuanyuan12543** [marbl/canu#1678]
Hi, my job got failed after the stage of unitig. 

```
The output file shows the error like this: 
-- Finished on Fri Apr 10 05:30:05 2020 (108 seconds) with 365821.287 GB free disk space
----------------------------------------
-- No report available.
-- Report changed.
-- Finished stage 'updateOverlapStore', reset canuIteration.
-- Finished stage 'unitig', reset canuIteration.
-- No change in report.
-- No change in report.
--
-- Running jobs.  First attempt out of 2.
--
-- Failed to submit compute jobs.  Delay 10 seconds and try again.

CRASH:
CRASH: Canu 1.9
CRASH: Please panic, this is abnormal.
CRASH:
CRASH:   Failed to submit compute jobs.
CRASH:
CRASH: Failed at /apps/canu/1.9_20191104/bin/../lib/site_perl/canu/Execution.pm line 1274.
CRASH: 	canu::Execution::submitOrRunParallelJob("Mercenaria.assemble", "bat", "unitigging/4-unitigger", "unitigger", 1) called at /apps/canu/1.9_20191104/bin/../lib/site_perl/canu/Unitig.pm line 393
CRASH: 	canu::Unitig::unitigCheck("Mercenaria.assemble") called at /apps/canu/1.9_20191104/bin/canu line 943
CRASH: 
CRASH: Last 50 lines of the relevant log file (unitigging/4-unitigger/unitigger.jobSubmit-01.out):
CRASH:
CRASH: sbatch: error: Batch job submission failed: Requested node configuration is not available
CRASH:
```
And my script is as below:
```
#!/bin/sh
#SBATCH --account=austin
#SBATCH --qos=austin-b
#SBATCH --job-name=junli_canu_assem
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=zjl1983@ufl.edu
#SBATCH --mem=30gb
#SBATCH --time=96:00:00
#SBATCH --output=junli_cau_assem_%j.out
#SBATCH --error=errCanu_assem_%j.err
pwd; hostname; date

module load ufrc
module load gcc/5.2.0 
module load gnuplot/5.2.3
module load canu/1.9
module load java/1.8.0_31


canu -assemble -p Mercenaria.assemble -d Mercenaria.assemble genomeSize=2.1g rawErrorRate=0.300 correctedErrorRate=0.085 corMhapSensitivity=normal corMinCoverage=4 minOverlapLength=500 minReadLength=5000 corOutCoverage=200 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" -pacbio-corrected /ufrc/austin/zjl1983/Clam_pacbio_2019/Mercenaria.trim/Mercenaria.trim.trimmedReads.fasta.gz shell="/bin/bash" java="/apps/java/1.8.0_31/bin/java" usegrid=1 gridOptionsJobName=CANU-assemble gridOptions="--time=96:00:00 --ntasks=1 --qos=austin-b" 1>correct.Mercenaria.assemble.log 2>>correct.Mercenaria.assemble.log
```

And I have tried to increase the memory quest to 100g, it did not work either.

Could you please help me to solve this problem? 

Thanks!

**Comment by skoren** [comment]
The error is saying your grid doesn't like the request Canu submitted to run the bogart step. Canu scans your full grid for available resources and picks a node. Unfortunately, sometimes this node is not in the default queue which makes sbatch reject the request. I suspect if you checked the preamble from Canu (where it says what resources it will use), the bat step will be using more memory than available on your standard nodes.

The fix is easy, force Canu to use a node in the default queue by adding ```batMemory=100``` to your command (where I'm assuming 100gb nodes are available in the default queue your jobs are running in). Re-run the command and it should resume the assembly.

**Comment by yuanyuan12543** [comment]
Thank you, skoren! I added the option and ran it again. But it failed again. I am attaching the error files, the script file and the order error files here. 

Maybe I should use batMemory=550. 

Please let me know your opinion.

Thank you!

[Canu_assemble.docx](https://github.com/marbl/canu/files/4471613/Canu_assemble.docx)
[correct.Mercenaria.assemble.log.docx](https://github.com/marbl/canu/files/4471615/correct.Mercenaria.assemble.log.docx)
[canu.12.out.docx](https://github.com/marbl/canu/files/4471617/canu.12.out.docx)

**Comment by skoren** [comment]
Did you switch Canu versions? Your initial issue was using 1.9 and in your new script you are loading canu/2.0. You can't switch versions in the middle of a run, since you started with 1.9 keep using 1.9.

**Comment by yuanyuan12543** [comment]
Yes, I thought newer version would be better. Actually it is not, I just tried the memory increase to 550, still failed with the same problem, cannot read the sequence. I am gonna to switch to the order version

**Comment by skoren** [comment]
The memory increase to 550 cannot fix your error. I'm not sure why you are trying 550? The issue is that the job is trying to use more memory than allowed for the default queue, increasing the memory further isn't going to fix that.

**Comment by yuanyuan12543** [comment]
That is because in the error file it shows" -- Grid:  bat      512 GB   32 CPUs  (contig construction with bogart)". So it doesn't matter how much memory is request, 100 will work, right?

**Comment by skoren** [comment]
Yes, 512 is the default and that's what it already tried to request but your grid rejected the job. I'm guessing it's because of these machines:
```
-- Found   1 host  with  24 cores and  749 GB memory under Slurm control.
-- Found   1 host  with 192 cores and 1509 GB memory under Slurm control.
-- Found 104 hosts with  32 cores and  186 GB memory under Slurm control.
-- Found  25 hosts with  28 cores and  124 GB memory under Slurm control.
-- Found 905 hosts with  32 cores and  124 GB memory under Slurm control.
-- Found  64 hosts with  16 cores and   62 GB memory under Slurm control.
-- Found 221 hosts with  64 cores and  249 GB memory under Slurm control.
```
The two large memory nodes with >250gb of ram require special queue/access. Specifying batMemory=100 will change that to 100 instead of 512 and will ensure it can run on most of the nodes in the cluster.

**Comment by yuanyuan12543** [comment]
Thank you very much, it is running now.
