### ISSUE TITLE
sqStoreCreate failed. Failed with exit code 1.  (rc=256)

### ISSUE THREAD

**Issue by ChloeDG** [marbl/canu#1680]
I am trying to assemble Nanopore direct RNA sequencing data for an RNA virus and I am having an error. I read that canu will likely fail to assemble RNA but I wanted to make sure I am having an error because of this and not something preventable.
When I use the following command: 
`/home/hh/miniconda3/bin/canu -p RNA-1 -d RNA-1 genomeSize=30000 useGrid=false -nanopore-raw '/home/hh/Documents/Basecalled/update.fastq' useGrid=false minReadLength=200 minOverlapLength=100 stopOnLowCoverage=0 contigFilter="2 0 1.0 0.5 0" `

I get the following error 
```
ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:

ABORT:
ABORT: Canu 2.0
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   sqStoreCreate failed; boom!.
ABORT:
ABORT: Disk space available:  548.832 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (./update.seqStore.err):
ABORT:
ABORT:   
ABORT:   Found perl:
ABORT:      /home/hh/miniconda3/bin/perl
ABORT:      This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-thread-multi
ABORT:   
ABORT:   Found java:
ABORT:      /home/hh/miniconda3/bin/java
ABORT:      openjdk version "11.0.1-internal" 2018-10-16
ABORT:   
ABORT:   Found canu:
ABORT:      /home/hh/miniconda3/bin/canu
ABORT:      Canu 2.0
ABORT:   
ABORT:   
ABORT:   Creating library 'covid_update' for Nanopore raw reads.
ABORT:   
ABORT:                  reads               bases
ABORT:   ---------- --------- ------ ------------ ------
ABORT:   Loaded             0   0.0%            0   0.0%  /home/hh/Documents/Basecalled/update/update.fastq
ABORT:   Short            318   0.0%         1190   0.0%
ABORT:   Invalid       778890 100.0%    910278331 100.0%
ABORT:   
ABORT:   
ABORT:   All reads processed.
ABORT:   
ABORT:                  reads               bases
ABORT:   ---------- --------- ------ ------------ ------
ABORT:   Loaded             0   0.0%            0   0.0%
ABORT:   Short            318   0.0%         1190   0.0%
ABORT:   Invalid       778890 100.0%    910278331 100.0%
ABORT:   
ABORT:   sqStoreCreate: stores/sqStoreConstructor.C:94: void sqStore::sqStore_loadMetadata(): Assertion `sqRead_defaultVersion != sqRead_unset' failed.
ABORT:   
ABORT:   Failed with 'Aborted'; backtrace (libbacktrace):
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   ../sysdeps/x86_64/elf/start.S::103 in (null)()
ABORT:   Aborted (core dumped)
ABORT:
```

When I look in the directory:
```
Last 50 lines of the relevant log file (./RNA.seqStore.err):
```

It just says the same as the error in the terminal, 
```
sqStoreCreate: stores/sqStoreConstructor.C:94: void sqStore::sqStore_loadMetadata(): Assertion `sqRead_defaultVersion != sqRead_unset' failed.
```
Canu Version 2.0
Ubuntu 16.04
16GB memory
Intel® Core™ i5-8250U CPU @ 1.60GHz × 8 
Intel® Kabylake GT1.5 

Any help would be really appreciated.

**Comment by skoren** [comment]
Since all the reads aren't being loaded because they are "invalid", I would guess it is due to them being RNA and having non-ACGT bases. There should be an log file in the failed seqStore folder (```*BUILDING/*error*``` or similar). Post a snippet of that file as it should give the exact error for why each read was marked invalid.

**Comment by ChloeDG** [comment]
This is the snippet: 
```

read 'a22f5a69-54c1-47dd-b58c-d6f739d2be2a runid=dda1537ffc4910b351360f5c24d80ad08ffe7950 read=5 ch=84 start_time=2020-02-11T11:48:25Z flow_cell_id=FAL90649 protocol_group_id=George_Cell_Direct sample_id=George_Cell_Direct' of length 44 in file '/home/hh/Documents/Basecalled/update/update.fastq' - contains 9 invalid letters, skipping.
read '68706a6b-7ad6-4762-b02a-51d0ac732592 runid=dda1537ffc4910b351360f5c24d80ad08ffe7950 read=5 ch=53 start_time=2020-02-11T11:48:25Z flow_cell_id=FAL90649 protocol_group_id=George_Cell_Direct sample_id=George_Cell_Direct' of length 104 in file '/home/hh/Documents/Basecalled/update/update.fastq' - contains 26 invalid letters, skipping.

```
"Invalid letters, skipping" is said a lot so I guess you are right. Bummer. Do you know of any packages that can convert RNA fastqs to its DNA counterparts so I can still use canu? Or reduce the threshold of invalid letters canu will let me load?

**Comment by skoren** [comment]
You should check what the non-ACGT characters are. Canu used to have support to recognize Us and convert them to Ts but that functionality has certainly not been tested for a while so it may have broken. It's also possible there are other characters besides Us. If it is just Us, you can replace them all with Ts and run Canu.

**Comment by ChloeDG** [comment]
They are U's
Here is a snippet from the fastq: 

> @a22f5a69-54c1-47dd-b58c-d6f739d2be2a runid=dda1537ffc4910b351360f5c24d80ad08ffe7950 read=5 ch=84 start_time=2020-02-11T11:48:25Z flow_cell_id=FAL90649 protocol_group_id=George_Cell_Direct sample_id=George_Cell_Direct
> CGACGCCCUCUCUGUCCCUAUCAUCUGCGACGCAGCGCCCUAAC
> +
> %%##""#$""##"###$###$#####$#""$###$""#$$$"""
> @68706a6b-7ad6-4762-b02a-51d0ac732592 runid=dda1537ffc4910b351360f5c24d80ad08ffe7950 read=5 ch=53 start_time=2020-02-11T11:48:25Z flow_cell_id=FAL90649 protocol_group_id=George_Cell_Direct sample_id=George_Cell_Direct
> CACCUGAACGCGCCUGAUUUCGUCGCUGAUUUGGAAGCUAAGCAGGUGGCAAAAAAGGUUAGUACUCAGAUGAGGAGUCUGCUGGAAUCAAGUGUGGCUUCUGC
> +
> $#)'&1/%,2-/*&#%#%'*$/+%##&16-#%,-+%*($%*+&&'&(''*#$$$$#99'#$*/+,%##+&$&$'&#)"$#%$#(((&%#%$//%#+*1%'##%"
> @d231efeb-588b-4bf7-af95-e47382dcfc22 runid=dda1537ffc4910b351360f5c24d80ad08ffe7950 read=14 ch=299 start_time=2020-02-11T11:48:28Z flow_cell_id=FAL90649 protocol_group_id=George_Cell_Direct sample_id=George_Cell_Direct
> AAACGCCCCCGUCCGCUCA
> +
> -'&&$%).&$%$$%"$#()
> @56424f0c-01fe-4006-b2d2-3cf6dbb13556 runid=dda1537ffc4910b351360f5c24d80ad08ffe7950 read=11 ch=91 start_time=2020-02-11T11:48:28Z flow_cell_id=FAL90649 protocol_group_id=George_Cell_Direct sample_id=George_Cell_Direct
> AAACCAUUACCACAUAAAGUAUAGGUGAUAGAAAUUCAACUCGGCGCUAUGGACACAGGAAAUCCCUACUCCCCAUCUACAGCUCCCCUGUUACUUGGUACCUGUGCUUUCAAACUGCUCAAUUUCCAUUACAUUUUUUUCCUU
> +
> .6:96032)%*&)')2173.<B674%-361686357%)*,)*4*4:/345$..$+),.:/-&&+&$#"%#%-')'($&$*%%""(+++,&$$"##)**0#%$%'&#$$&&$#$""#"#$$%#$$$')%$$$$%')-*-'((.$%
> @05a2ca8f-c0d7-47f6-9e5e-a96c3fb63953 runid=dda1537ffc4910b351360f5c24d80ad08ffe7950 read=15 ch=81 start_time=2020-02-11T11:48:33Z flow_cell_id=FAL90649 protocol_group_id=George_Cell_Direct sample_id=George_Cell_Direct
> CCCAUCGAAGCGUCGCGCGCAAAACGCACGCGGUAUAUCAAACGGUACCUGUUUCCGGAGCAGCCCAAACAU
> +
> $%#$"#%##%###$"##$##'('&%"#"#$#$&%"#""""#"###$"$""####$#%%$"$"$#$#"#"""#
> @c9ac106d-e39e-4358-b7fb-dbe57f136b26 runid=dda1537ffc4910b351360f5c24d80ad08ffe7950 read=11 ch=274 start_time=2020-02-11T11:48:33Z flow_cell_id=FAL90649 protocol_group_id=George_Cell_Direct sample_id=George_Cell_Direct
> UCUAAUCCUGAUACCACUACUAACCUCCCUGAUCGAAAAUAACCUACUCAAAUGAACUUAAAGUUCCCUUCCAUCUACACCAACCCACCAUAUUUUCAUCAUCCAUUUAUUUAUGCCCUCCGCCCUGCUGCCCUAU

**Comment by skoren** [comment]
The U/T translation was definitely lost, I committed a fix to restore that functionality. I expect you'll get results now. I would suggest you only want to run the correction step and use the corrected reads. I'm not sure what assembling the RNA reads would mean since I expect most are full-length transcripts already. I'm closing this issue since the original problem (Us causing reads to be ignored) is fixed. If you encounter other errors during your run, open a new issue.

**Comment by LandiMi2** [comment]
Hi @skoren , I have a similar error

``` ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:

ABORT:
ABORT: canu 2.1.1
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   sqStoreCreate failed; boom!.
ABORT:
ABORT: Disk space available:  4990.503 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (./ecoli-pacbio.seqStore.err):
ABORT:
ABORT:      /usr/bin/perl
ABORT:   perl: warning: Setting locale failed.
ABORT:   perl: warning: Please check that your locale settings:
ABORT:   	LANGUAGE = "en_GB:en",
ABORT:   	LC_ALL = (unset),
ABORT:   	LC_CTYPE = "UTF-8",
ABORT:   	LANG = "en_GB.UTF-8"
ABORT:       are supported and installed on your system.
ABORT:   perl: warning: Falling back to the standard locale ("C").
ABORT:      This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-gnu-thread-multi
ABORT:   
ABORT:   Found java:
ABORT:      /usr/bin/java
ABORT:      java version "1.8.0_20"
ABORT:   
ABORT:   Found canu:
ABORT:      /opt/canu-2.1.1/bin/canu
ABORT:   perl: warning: Setting locale failed.
ABORT:   perl: warning: Please check that your locale settings:
ABORT:   	LANGUAGE = "en_GB:en",
ABORT:   	LC_ALL = (unset),
ABORT:   	LC_CTYPE = "UTF-8",
ABORT:   	LANG = "en_GB.UTF-8"
ABORT:       are supported and installed on your system.
ABORT:   perl: warning: Falling back to the standard locale ("C").
ABORT:      canu 2.1.1
ABORT:   
ABORT:   
ABORT:   Creating library 'pacbio' for PacBio raw reads.
ABORT:   
ABORT:                  reads               bases
ABORT:   ---------- --------- ------ ------------ ------
ABORT:   sqStoreCreate: utility/src/utility/sequence.C:743: uint64 dnaSeqFile::loadFASTQ(char*&, uint32&, char*&, uint8*&, uint64&): Assertion `seqLen == qltLen' failed.
ABORT:   
ABORT:   Failed with 'Aborted'; backtrace (libbacktrace):
ABORT:   utility/src/utility/system-stackTrace.C::83 in _Z17AS_UTL_catchCrashiP7siginfoPv()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   utility/src/utility/sequence.C::743 in _ZN10dnaSeqFile9loadFASTQERPcRjS1_RPhRm()
ABORT:   utility/src/utility/sequence.C::773 in _ZN10dnaSeqFile12loadSequenceERPcRjS1_RPhRmS5_()
ABORT:   utility/src/utility/sequence.H::213 in _ZN10dnaSeqFile12loadSequenceER6dnaSeq()
ABORT:   stores/sqStoreCreate.C::196 in _Z9loadReadsP7sqStoreP9sqLibraryjjP8_IO_FILES4_PcR9loadStats()
ABORT:   stores/sqStoreCreate.C::345 in _Z11createStorePKcRSt6vectorI6seqLibSaIS2_EEj()
ABORT:   stores/sqStoreCreate.C::662 in main()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   ./ecoli-pacbio.seqStore.sh: line 47:  3716 Aborted                 /opt/canu-2.1.1/bin/sqStoreCreate -o ./ecoli-pacbio.seqStore.BUILDING -minlength 1000 -genomesize 4800000 -coverage 200 -bias 0 -raw -pacbio pacbio /syn06/mlandi/PacBio-TrialData/pacbio.fastq 
```

Kindly please assist. Running cunu v1.8 was successful in running my assembly unfortunately with canu v2.1.1 I get that error 

Here is the command 

```/opt/canu-2.1.1/bin/canu -d ./Results/PacBio-Trial/ecoli-test -p ecoli-pacbio genomeSize=4.8m -pacbio ./PacBio-TrialData/pacbio.fastq -useGrid=false -executiveMemory=8 -executiveThreads=4 -corOverlapper=ovl```

**Comment by Guanguan8** [comment]
@skoren I come across this issue, could you give me a help.
![image](https://github.com/marbl/canu/assets/41434736/97c62382-611c-4874-ab9b-f645d519b823)

**Comment by skoren** [comment]
@Guanguan8 doesn't look like it's the same issue since you're not assembling RNA data but also your reads look like they are contigs. Canu isn't designed to assemble contig sequences.
