### ISSUE TITLE
Any intermediate products can be deleted for more disk quota

### ISSUE THREAD

**Issue by HanKMU** [marbl/canu#1681]
Hi, sorry for bothering again with the similar question.
This this is the follow up of issue #1622 

We increased the coverage to 25X (after ignored reads <1KB, which is shown in `.seqStore.err` ) and also applied the suggested parameters from Canu FAQ **My assembly is running out of space, is too slow?** 

**command:** 
```
cd /home/std/hyli/canu/20200226/
/opt/canu/Linux-amd64/bin/canu -correct -p 25Xcoverage -d EEG357_376_388_389 genomeSize=1G maxMemory=500 maxThreads=40 corMhapFilterThreshold=0.0000000002 corMhapOptions="--threshold 0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50" mhapMemory=60g mhapBlockSize=500 ovlMerThreshold=500 purgeOverlaps=aggressive -nanopore-raw /home/std/hyli/nanopore/EEG357mix.fastq /home/std/hyli/nanopore/EEG376mix.fastq /home/std/hyli/nanopore/EEG388_100fmol_KAPA60_mix /home/std/hyli/nanopore/EEG388_100fmol_LNB30_mix /home/std/hyli/nanopore/EEG389_100fmol_LNB15_mix /home/std/hyli/nanopore/EEG389_100fmol_LNB60_mix /home/std/hyli/nanopore/EEG389_200fmol_LNB30_mix 1>canu_stdout 2>canu_errout
```
We finally finished stage 'cor-overlapStoreConfigure', but we got the same disk quota problem in the following 'ovB' concurrent execution stage.

![image](https://user-images.githubusercontent.com/55967210/79318390-82a5f880-7f39-11ea-93ec-dda80be9d0f1.png)
![image](https://user-images.githubusercontent.com/55967210/79318450-96515f00-7f39-11ea-8729-03e13a21e1f3.png)

We are wondering that are there any intermediate files can be deleted for more disk quota?
Or what can we do for solving this problem...

Thank you!

**Comment by HanKMU** [comment]
I've saw issue #1465 discussed the same problem as mine. But we already add **purgeOverlaps=aggressive**, and there are no `*WORKING*` files anymore. According to the reply about **Remove all files named *mhap* from the results folder.** I found lots mhap files for instance named `mhap.000001.out`, in **1-overlapper folder**, not in the results folder. The files in results folder are `*.oc* or *.ovb*`. So in my case, should I remove the *mhap* from the 1-overlapper folder? 

Thanks for your time..

**Comment by skoren** [comment]
If you're running with purgeOverlaps=agressive, it should already be removing the oc and ovb files for any bucket job that completed. You can check if you have ovb files corresponding to the finished bucketizing job (those before 331) vs those that failed (331 and later). You CANNOT remove the ovb files for those jobs where you have not finished bucketizing as those results would be lost. If you still have a blocks folder in 1-overlapper, you can remove it to save some space.

**Comment by HanKMU** [comment]
Thanks for your response!
I have checked it and there's no blocks folder anymore. The left `.ovb and .oc` files in results folder are those after 290. Can I delete the ovb and oc files of 290~330 which are already finished bucketizing job?
How about those `.oc` files? Are they as essential as .ovb files in bucket job or any following steps? Since the last number is 923 which means the remained .oc files are about 11G and the ovb files from 290~330 are about 240G. I'm just trying to save some more space for finishing the whole correction step....

**Comment by skoren** [comment]
The oc files are needed to use the ovb files, so you shouldn't remove them. You can delete the ovb/oc files from the finished bucketizing jobs, I'm not sure why they weren't removed by Canu. Confirm in the logs that the bucket job finished OK and that there is a sliceSizes file in the buckets too. 

From the logs it looks like you have more disk space, you're hitting a quota, I think the easiest approach is to ask for a larger quota from your admin. That way you don't have to keep trying to clean up files. You're right about the remaining steps but you're at peak space usage now so once the correction store is built (you can estimate space needed as double the size of the remaining ovb files) you will not be using as much space.

**Comment by HanKMU** [comment]
Thank you so much for the explanation and recommendation!

**Comment by skoren** [comment]
Any update, were you able to get more space to complete the run?

**Comment by HanKMU** [comment]
After estimating the needed space through double the size of the remaining ovb files, I found that we still need about 11T more disk space...
We decide to re-basecall those sequence by GUPPY v6 (we got them from pretty old version minKNOW) and try to decrease the error rate first, then using Canu again
Hope it works.

**Comment by skoren** [comment]
The corrected error rate won't help correction space usage but you can decrease the sketch size to 256 from 512 in your command line (or increase the matches from 3 to 5) and likely still find enough overlaps after re-calling. This would probably not work since you have such low coverage (25x) w/o recalling.

I'll close this issue for now, feel free to open a new one if you encounter issues with the re-called data.
