### ISSUE TITLE
Longer read exclusion positively impacts the assembly

### ISSUE THREAD

**Issue by snurk** [marbl/canu#1686]
Part of the reason was that long reads with bad 'ends' were not considered cov-gap.
Instead they ended up being spurs, sucking up shorter correct reads as contained.

But it seems that just making such reads cov-gap did not resolve quite a few issues.
It is important to understand what is going on, in particular to see if we are facing some unknown type of recurrent errors.

**Comment by skoren** [comment]
Updated deadend filtering and seeding criteria lead to expected results, with the same long contigs built if long read are included or excluded.
