### ISSUE TITLE
Long bubbles are not detected at Dmel

### ISSUE THREAD

**Issue by snurk** [marbl/canu#1688]
It seems that fragmentation observed on Dmel (and potentially diploid humnans) is related to the fact that we are not recognizing long 'alternative' contigs (up to Mb long) as bubbles, leading to fragmentation of primary contigs.

**Comment by snurk** [comment]
Maybe we indeed don't want to recognize some of the ultra-long bubble contigs, but it would be nice to have slightly more control over the classification.

**Comment by skoren** [comment]
Allowing placements of bubbles into bubbles and adjusting bubble criteria resolves the majority of the issues. Remaining issue correspond to true confusion in the graph.
