### ISSUE TITLE
ERROR:  Failed with exit code 1.  (rc=256)

### ISSUE THREAD

**Issue by yanz711** [marbl/canu#169]
I try to use Canu as following:

```
canu \
 -p sinb -d sinb \
 genomeSize=500m \
ovsMemory=128 \
 -pacbio-raw 6qctCUJF.1th-to-20th_smrt.fastq.gz -useGrid=0  -maxMemory=250 -maxThreads=24
```

But I got error at: 

```
    /scratch/beegfs/monthly/zyan/software/canu/canu/Linux-amd64/bin/filterCorrectionOverlaps \
      -G /scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/sinb.gkpStore \
      -O /scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/sinb.ovlStore \
      -S /scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/2-correction/sinb.globalScores \
      -c 40 \
      -l 0 \
    > /scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/2-correction/sinb.globalScores.err 2>&1

-- Finished on Fri Jun 17 14:08:00 2016 (157 seconds) with 91614.3 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:
=============================================================================
```

Any suggestion to solve it?

**Comment by brianwalenz** [comment]
What's reported in sinb/correction/2-correction/sinb.globalScores.err?

**Comment by yanz711** [comment]
ERROR: directory '/scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/sinb.ovlStore' is not an overlapStore; failed to open info file '/scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/sinb.ovlStore/info': No such file or directory

**Comment by brianwalenz** [comment]
...and it gets harder.  :-(

What's the 'ls -l' of sinb.ovlStore/?  Depending on genome size, there will either be a sinb.ovlStore.err or a simb.ovlStore/logs/ directory with logs for many processes.  Look through those for any errors.

If the logs/ directory exists, give priority to the 3\*, then the 2\* and finally the 1\* files.

**Comment by yanz711** [comment]
Thank you so much for answer my question.

I looked at simb.ovlStore/logs/ fold, there is one "3-index.err" exist and contains 578 lines of error message; head 3-index.err:

ERROR: Segment 1 data not present  (/scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/sinb.ovlStore.BUILDING/0001)
ERROR: Segment 1 info not present (/scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/sinb.ovlStore.BUILDING/0001.info)
ERROR: Segment 1 index not present (/scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/sinb.ovlStore.BUILDING/0001.index)
ERROR: Segment 2 data not present  (/scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/sinb.ovlStore.BUILDING/0002)
ERROR: Segment 2 info not present (/scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/sinb.ovlStore.BUILDING/0002.info)
ERROR: Segment 2 index not present (/scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/sinb.ovlStore.BUILDING/0002.index)
ERROR: Segment 11 data not present  (/scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/sinb.ovlStore.BUILDING/0011)
ERROR: Segment 11 info not present (/scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/sinb.ovlStore.BUILDING/0011.info)
ERROR: Segment 11 index not present (/scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/sinb.ovlStore.BUILDING/0011.index)
ERROR: Segment 23 data not present  (/scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/sinb.ovlStore.BUILDING/0023)

**Comment by brianwalenz** [comment]
Segments 3 through 10 seem to have succeeded, where 1, 2, 11, ... failed.  Check those 2\* files for errors.  I'm going to guess out of disk (check your quota, too), or other lack of system resources.

Also, what version are you using (canu -version)?

**Comment by yanz711** [comment]
I got two Failure message in file: 2-sort.000001.out and 2-sort.000002.out

For example:

Found 112056370 overlaps from '/scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/sinb.ovlStore.BUILDING/bucket0001/sliceSizes'.
Found 107993686 overlaps from '/scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/sinb.ovlStore.BUILDING/bucket0002/sliceSizes'.
Found 102370192 overlaps from '/scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/sinb.ovlStore.BUILDING/bucket0003/sliceSizes'.
Found 95555481 overlaps from '/scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/sinb.ovlStore.BUILDING/bucket0004/sliceSizes'.
Found 3548365 overlaps from '/scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/sinb.ovlStore.BUILDING/bucket0005/sliceSizes'.
Overlaps need 15.70 GB memory, allowed to use up to (via -M) 16 GB.
/scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/sinb.ovlStore.BUILDING/scripts/2-sort.sh: line 36: 19684 Killed                  $bin/ovStoreSorter -deletelate -M 16 -O /scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/sinb.ovlStore.BUILDING -G /scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/sinb.gkpStore -F 246 -job $jobid 136
Failure.

Canu v1.3 (+27 commits) r7643 4c5f6fef6ae021251b348f8ce7fd47ce294151fd.

**Comment by brianwalenz** [comment]
Killed is suggesting the job exceeded some site policy - memory, CPU or disk bandwidth.

I see you've limited it to 250GB and 24 threads.  I can't tell how many of the 2-sort jobs it is trying to run at once.  I'm assuming it's trying to run too many and exhausting memory.  At best, it can run 15 at the same time, though 12 is more comfortable.  These limits are reported every time canu is run.

Can you run this job by hand: "sh 2-sort.sh 1" will run the 1st job.  If not, something is limiting your jobs to less than 16gb.

Setting ovsConcurrency=12 will limit it to running 12 2-sort jobs at the same time.

I'd like to see the full output of the canu command if you restart with the same command -- canu will either resume running the 2-sort jobs, or fail with the same error you're seeing here.

**Comment by yanz711** [comment]
[zyan@dee-serv03 scripts]$ sh 2-sort.sh 1
ERROR: Failed to open '/scratch/beegfs/monthly/zyan/annotation/Pacbio/sinb/correction/sinb.ovlStore.BUILDING/0001.ovs' for writing: No such file or directory
Failure.

I set ovsConcurrency=12 and restart the Canu command, but it fail with the same error.

Really thank you so much to respond my question.

**Comment by brianwalenz** [comment]
No idea, it looks like sinb.ovlStore.BUILDING doesn't exist?  Remove sinb.ovlStore\* and restart canu.

But based on issue #178, I'm guessing you're past this.
