### ISSUE TITLE
What is the behavior of trimming/unitigging when you change genomeSize?

### ISSUE THREAD

**Issue by EarlyEvol** [marbl/canu#1694]
Sorry, this is a pretty dumb question, but hopefully it is a quick answer.
I have a bunch of assemblies running on different species, some of which I don't know the genome size.  For one I overshot by about 2x (these wasps are really variable) based on corrected kmers.  so now canu corrected and started trimming ~80x reads.  What is the behavior of canu if I start the unitigging with a different expected genome size?  Will it just take the longest 40X trimmed reads for unitig construction?

**Comment by brianwalenz** [comment]
The primary use of genomeSize is during correction, to generate about 40x of corrected reads.  After that, it's used for computing NGx statistics.  If you restart an assembly that already finished correction, it'll still use all the corrected reads generated (so 80x in this case).

You can restart from the trimmed reads with something like `canu ... -assemble -corrected -pacbio asm.trimmedReads.fasta.gz maxInputCoverage=40 readSamplingBias=10` to use the longest 40x.  Do check the read length histogram in asm.report to be sure it's doing what you expect.

**Comment by EarlyEvol** [comment]
Ah, glad I asked.  Thanks for the info.
