### ISSUE TITLE
Is generateCorrectionLayouts single threaded?

### ISSUE THREAD

**Issue by SHuang-Broad** [marbl/canu#1696]
Hi ,

I have two simple questions:
is `generateCorrectionLayouts` single-threaded?
And how long would it take, approximately, for it to scan through an ovlStore of ~4TB, on a single thread with HDD (not SSD, so IO will be slow)?

Thank you!
Steve

**Comment by skoren** [comment]
Yes it is single threaded, it would probably take 1-2 days for that size store to scan through it.

**Comment by SHuang-Broad** [comment]
Thanks Sergey
