### ISSUE TITLE
version `GOMP_4.0' not found 

### ISSUE THREAD

**Issue by rmenafra** [marbl/canu#1699]
I'm using Canu2.0 on a CLR human asm (PacBio CLR) on a linux cluster Ubuntu 14.04.6 
At the correction step I've an error log in the folder output/correction/2-correction :
```bash
 path/canu-2.0/Linux-amd64/bin/filterCorrectionLayouts: /usr/lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found (required by path/canu-2.0/Linux-amd64/bin/filterCorrectionLayouts)
```
The command I used it was: 
```
path/canu-2.0/Linux-amd64/bin/canu -p asm -d output_Canu genomeSize=3.3g  -pacbio-raw input.fasta.gz gridOptions="-V -q all.q" gridEngineThreadsOption="-pe BWA THREADS" gridOptionsExecutive="-l h_vmem=320g" correctedErrorRate=0.035 utgOvlErrorRate=0.065 trimReadsCoverage=2 trimReadsOverlap=500
```
Any idea how to fix this? It has been running for weeks so far and I really would like it to complete.
Starting coverage is ~92X.
Thanks in advance

**Comment by skoren** [comment]
This is likely an issue with your nodes not Canu. It looks like you're running on a cluster and some nodes have environments that don't match each other. Pretty much all canu binaries require GOMP so if it made it this far most of your nodes have it but some apparently don't. You'll have to contact your IT group to check why the node you landed on that time was different from the rest. 

If you re-run the canu command, it will retry the failed step and may land on a node that is OK and continue running.

**Comment by rmenafra** [comment]
Could you indicate me where exactly in the logs can I find the node on which that job failed?
I'm having a hard time figuring that out and we only have 7 nodes with that memory capacity.
I also tried using a different version of gcc (gcc-7) downloaded via conda, making sure that option -V was used in the main command, because I thought that our gcc version (4.8) could have been the problem.
Thanks in advance

**Comment by skoren** [comment]
It's going to be cluster specific, you don't say what cluster type you're running on. The canu-scripts folder will have a log of all the job IDs on your cluster Canu used, the next to last one will tell you what the job ID was of the one which failed. The GCC version has to match however you built Canu so if you built with 7 then 7 has to be available (the pre-compiled binaries will work with 4.8).

**Comment by rmenafra** [comment]
Sorry the cluster is SGE, and I'm using the pre-compiled binaries.

**Comment by skoren** [comment]
Then the GCC version isn't an issue, I expect the file system is not the same on the node which failed the run. Use qacct on the job IDs reported in ```canu-scripts/*.out``` to see where the jobs landed. Then, try logging into an interactive session to them and see if you can run the command w/o errors. BTW, there's no reason to request 320gb of memory for the process, you're just slowing down your run so it sits around doing nothing waiting to get scheduled.

**Comment by rmenafra** [comment]
The only reason for that is that it was failing at some point due to insufficient memory. I know Canu should assess resources by itself, but that was not the case...this was the only way to get it run again...

**Comment by skoren** [comment]
You're only setting the memory for the executive script though and we have never used 320gb for it even when assembling genomes much larger than human. Maybe 16gb or 32 but not 320, did you try lower values than 320?

**Comment by skoren** [comment]
"I didn't think that was only setting the memory for the executive job, I'll definitely try lowering that."
This also means all the other jobs are using canu's memory requests and succeeding on the cluster w/o issue.

If previous jobs succeeded on the node then there must be a recent change to your cluster. You can see pretty much every canu binary needs GOMP (run ldd on any binary like sqStoreCreate) which also runs in the executive. So if GOMP was always an issue it would have failed to build the initial sequence DB. Can you still run any of those binaries on your head node?

**Comment by rmenafra** [comment]
Hi,
I tried to run separately one of the binaries and had no problems.
Since we are transitioning to a new (different) cluster I also tried to restart the asm from there and had no problems, so now I'm continuing from there. 
I'm not sure what have generated the first error but I couldn't run it on the old cluster without getting the above mentioned error back.
I guess you can close the issue.
Thanks
