### ISSUE TITLE
overlapper problem

### ISSUE THREAD

**Issue by DiegoSantos-Garcia** [marbl/canu#170]
Dear Skoren,
I was trying to run the E. coli example for your canu assembler but I always have a problem during the overlapper step, independently if I run it with mhap or overlapper. Exploring the outputs/folders, it seem to me that the problem comes during the job assignment or the generation of the blocks .dat files. I append you the log files. Maybe be I made a silly mistake, but I was trying to fix it all the day and I didn’t find any solution. 
All the best,

Diego

[mhpa_log.txt](https://github.com/marbl/canu/files/322338/mhpa_log.txt)
[overlapper_log.txt](https://github.com/marbl/canu/files/322337/overlapper_log.txt)

**Comment by brianwalenz** [comment]
'overlapper' hasn't been tested much, if even at all, at this stage, so lets ignore it for the moment.  It did seem to run only the even jobs, which is a little odd!

Can you post the 'precompute.\*.out' files (or just a representative one)?  The second job seems to have finished, but the first one seems like it fails immediately.

**Comment by DiegoSantos-Garcia** [comment]
Yes, that’s the point.  Is only stopping in the odd numbers. Actually, I think the problem is that the 000001.dat file is not produced but I can not figure out where it fails. I was running another project but then I switched to the example reads, both of them gave me the same problem during the overlapper process (running the full pipeline or only correction step).


[partitioning.log.txt](https://github.com/marbl/canu/files/322736/partitioning.log.txt)
[precompute.000001.out.txt](https://github.com/marbl/canu/files/322738/precompute.000001.out.txt)
[precompute.000002.out.txt](https://github.com/marbl/canu/files/322737/precompute.000002.out.txt)

**Comment by skoren** [comment]
It looks like the partitioning is failing, are you running a release or the latest from tip? If you're not on a release, the code could be unstable and I would suggest running the 1.3 release instead.

**Comment by DiegoSantos-Garcia** [comment]
You are right. I was running the last unstable release from GitHub. Release 1.3 assembled the e.coli trial without problems.  Now, is time to deal with real data. Thanks  a lot!
