### ISSUE TITLE
evaluate using reads in repeats for splitting

### ISSUE THREAD

**Issue by brianwalenz** [marbl/canu#1700]
AS_BAT_MarkRepeatReads.C 921 has this disabled, but we're not sure if it's a good idea or not.
```
/*
      if ((rMin  <= rdAlo) &&   //  If the read is contained in the repeat region,
          (rdAhi <= rMax)) {    //  it's useless for deciding if this is a
        continue;               //  confused repeat.
      }
*/
```

**Comment by skoren** [comment]
This isn't leading to false breaks and I don't see a reason why we shouldn't break based on reads based within the repeat. In the worst case the assembly will be more conservative which is OK.
