### ISSUE TITLE
Loss of coverage after trimming

### ISSUE THREAD

**Issue by gaudinc** [marbl/canu#1708]
I am running Canu 2.0 on a virtual machine to assemble a small ~4.4Mb bacterial genome using raw pacbio data with ~111x coverage. In a first attempt, I tried to run Canu with the default parameters but the run stopped after the trimming step with 19 reads and '0 times coverage'. I tried different correction rounds with the following parameters corMhapSensitivity=high corMinCoverage=0 corOutCoverage=100 and then tried trimming with correctedErrorRate=0.15 and ovlMerThreshold=500 as previously suggested. I ended up with an unsatifactory ~7x times coverage of trimmed data.
The report of the 2 last steps are the following:
[TB1_12.report.txt.txt](https://github.com/marbl/canu/files/4606730/TB1_12.report.txt.txt)
[TB1_13.report.txt.txt](https://github.com/marbl/canu/files/4606731/TB1_13.report.txt.txt)

I have no additional clue about the quality of the data used. Any help or advice would be very much appreciated. Please let me know if additional information would be helpful.

**Comment by skoren** [comment]
Given your results, I would question the quality of the data. In particular, even after correction there are a lot of error k-mers and the peak is around 20-30x not anywhere near 80x as you'd expect:
```
--
--  22-mers                                                                                           Fraction
--    Occurrences   NumMers                                                                         Unique Total
--       1-     1         0                                                                        0.0000 0.0000
--       2-     2    826052 ********************************************************************** 0.3616 0.0573
--       3-     4    371153 *******************************                                        0.4654 0.0820
--       5-     7    214004 ******************                                                     0.5641 0.1165
--       8-    11    147472 ************                                                           0.6377 0.1565
--      12-    16    116317 *********                                                              0.6940 0.2028
--      17-    22    112805 *********                                                              0.7415 0.2587
--      23-    29    130665 ***********                                                            0.7907 0.3387
--      30-    37    154778 *************                                                          0.8483 0.4629
--      38-    46    136107 ***********                                                            0.9155 0.6460
--      47-    56     54284 ****                                                                   0.9707 0.8309
```

You could try putting the k-mer histogram output to genomescope to see what it predicts for genome size and sequence error rate. Where did this data come from? Is it possible it has contamination from a larger genome?

**Comment by gaudinc** [comment]
Thanks, Serguey, for your feedback (even with potential bad news concerning the data quality). Following your first suggestion, I ran Jellyfish 2.3.0 with standard parameters as suggested on the Genomescope website to generate the histo file and submitted it to Genomescope. Here are the results:
![image](https://user-images.githubusercontent.com/65133606/81586270-8e100680-93b5-11ea-8714-41dadeb18ae3.png)
For what I can see the estimated size seems ok. But what about the sequence error rate???
FYI, the data used are recent data but generated on a PacBio RSII sequencer.
Concerning the data source and possible contamination, I will investigate. 
Thanks again for your help and time.

**Comment by skoren** [comment]
You can try the FAQ suggestion for high-error data and run multiple rounds of trimming. How did you get this data, NCBI download? Direct from sequencing center?

**Comment by gaudinc** [comment]
From a sequencing service provider I'm afraid. I will follow your suggestion and have a look to the FAQ for high-error data.

**Comment by gaudinc** [comment]
After double-checking, we have no evidence for obvious contamination of the sample used for PacBio sequencing (the DNA was extracted from bacterial culture). I suppose the problematic step was the sequencing itself. Would you please kindly suggest the parameters I should use for the multiple rounds of trimming in order not to loose two many reads? In the previous attempt, I lost 90% of the reads during trimming with the following parameteres correctedErrorRate=0.15 and ovlMerThreshold=500. 
In addition, I also have Illumina data (same strain but different bacterial culture). Would you suggest to include these data in Canu as well? Would this help in obtaining a first assembly?
Thanks again for your help.

**Comment by skoren** [comment]
The Illumina data can't be used in Canu so it won't help. How was the data processed to obtain fastq files? Was it filtered for quality/etc as is typically done? Do you have a near-neighbor reference to map to to check the error rate? Are you able to share this data?

For parameters, follow the FAQ:
```
-correct corOutCoverage=500 corMinCoverage=0 corMhapSensitivity=high
```
for 2-3 rounds with the input to each round being the output of the previous correction, then run assembly as you did initially.

**Comment by gaudinc** [comment]
The fastq files were provided by the sequencing center and I have no access to any SMRTanalysis report for now. On the other hand, I have a near-neighbor genome assembly I could probably used as reference. Would you have any suggestion for the more appropriate tool to use to evaluate error rate by mapping?
Concerning your second point, I already performed a couple of correction rounds with the following command line -correct corOutCoverage=100 corMinCoverage=0 corMhapSensitivity=high. Does your suggestion is to run additional 2-3 rounds modifying the corOutCoverage value from 100 to 500 before trimming or to restart from scratch with the mentioned parameters and to run assembly (-assemble) directly after correction with no trimming step if this is an option ? 
To note, until now, I did not try to assemble my genome because coverage was always too low after trimming (~7 times coverage at best, below targeted ~20x corrected/trimmed data). Does this make sense to you ?

**Comment by skoren** [comment]
For mapping, I'd just use minimap2 to generate sam files and use those to evaluate read mapping statistics like fraction of reads mapping and their identity.

How many rounds of correction have you run (with the ```-correct corOutCoverage=100 corMinCoverage=0 ``` parameters) and what were the exact commands you used? You'll want to run trimming before assembly but not until the last round when the data is hopefully improved enough to not get so trimmed.

**Comment by gaudinc** [comment]
The TB1_12.report above was obtained after 10 correction rounds with the following command:
nohup canu -p TB1_12 -d /media/data/PacBio/TB1/Assembly_8_11/ genomeSize=4.4m -correct corMhapSensitivity=high corMinCoverage=0 corOutCoverage=100 -pacbio /media/data/PacBio/TB1/Assembly_8_10/TB1_11.correctedReads.fasta.gz &
Then, TB1_13.report after trimming with 
nohup canu -p TB1_13 -d /media/data/PacBio/TB1/Assembly_8_12/ genomeSize=4.4m -trim correctedErrorRate=0.15 ovlMerThreshold=500 -corrected -pacbio /media/data/PacBio/TB1/Assembly_8_11/TB1_12.correctedReads.fasta.gz &
Does that sound correct to you?

**Comment by skoren** [comment]
That looks correct, though the reports don't make sense since I'd expect the reads after 10 rounds of correction would have some non-error k-mers in the histogram but they do not. If you already did 10 rounds of correction, more correction won't help. Let's wait to see what the mapping looks like. Can you share the reads?

**Comment by gaudinc** [comment]
I finaly found an old near-neighbor reference to map on using minimap2 as suggested, with the following command "minimap2 -ax map-pb", generating the corresponding SAM file. 
Below are the stats obtained with samtools flagstat :
104039 + 0 in total (QC-passed reads + QC-failed reads)
6484 + 0 secondary
6117 + 0 supplementary
0 + 0 duplicates
69231 + 0 mapped (66.54% : N/A)

and samtools stats:
SN raw total sequences: 91438
SN filtered sequences:  0
SN sequences:   91438
SN is sorted:   0
SN 1st fragments:       91438
SN last fragments:      0
SN reads mapped:        56630
SN reads mapped and paired:     0       # paired-end technology bit set + both mates mapped
SN reads unmapped:      34808
SN reads properly paired:       0       # proper-pair bit set
SN reads paired:        0       # paired-end technology bit set
SN reads duplicated:    0       # PCR or optical duplicate bit set
SN reads MQ0:   128     # mapped and MQ=0
SN reads QC failed:     0
SN non-primary alignments:      6484
SN total length:        501711186       # ignores clipping
SN bases mapped:        316390504       # ignores clipping
SN bases mapped (cigar): 216999792      # more accurate
SN bases trimmed:       0
SN bases duplicated:    0
SN mismatches:  64285681 # from NM fields
SN error rate:  2.962477e-01    # mismatches / bases mapped (cigar)
SN average length:      5486
SN maximum length:      37183
SN average quality:     8.8
SN insert size average: 0.0
SN insert size standard deviation:      0.0
SN inward oriented pairs:       0
SN outward oriented pairs:      0
SN pairs with other orientation:        0
SN pairs on different chromosomes:      0

Would you have any feedback on the error rate?

**Comment by skoren** [comment]
How distant in ANI is this near neighbor? It doesn't look like the mapping stats report an identity (e.g. matches / total gapped alignment length) but it does report mismatches / bases mapped which is 30% and quite high. I checked a human pacbio library and it reports a mapping error rate of <13%. Also, only about 50% of the reads map at all.  That's consistent with low-quality data but I would have expected the correction rounds to help mitigate some of this. I'd like to try assembling the data locally, can you send the fastq to us using the instruction on the FAQ?

**Comment by skoren** [comment]
Idle. No data to reproduce locally but seems like a low-quality/library issue.
