### ISSUE TITLE
failed to precompute mhap indices

### ISSUE THREAD

**Issue by miguelpmachado** [marbl/canu#171]
Hi,
I'm trying run CANU v1.3 (installed from source) in a MinION uncorrected fasta file using the command
`canu -p 1999v0493s_MinION_pass_all -d ./1999v0493s_MinION_pass_all genomeSize=2.2m maxMemory=15 maxThreads=4 -nanopore-raw /scratch/1999v0493s_MinION_pass.all.fasta`
But it ends with

> canu failed with 'failed to precompute mhap indices.  Made 2 attempts, jobs still failed'.

Because this error happend to me before and it was a java problem [issue#68](https://github.com/marbl/canu/issues/68), I tried run it with java jdk1.8.0_77 and jre1.8.0_91, but it was the same.
I tried to find any specific log, but the only specific one that I found was in precompute.000001.out

> Running job 2 based on 1=1 and offset=1.
> Job partitioning error. jobid 2 is invalid.

I attached the [CANU prints to stderr](https://github.com/marbl/canu/files/325056/1999v0493s_MinION_pass_all.stderr.txt) (stdout was empty).

Do you know what can I do to make it run?

Thank you in advance.
Best regards,
Miguel

**Comment by brianwalenz** [comment]
That's not v1.3, but a snapshot of the current (unstable) version.  The bug should be fixed in the latest code - 'git pull' or grab the latest .zip.  Recompile, remove the correction/1-overlapper directory, and rerun the canu command.

**Comment by miguelpmachado** [comment]
Thanks @brianwalenz, removing the directory worked for me, both for "v1.3" or git clone.
I thought it was v1.3 because I got it using
```
wget https://github.com/marbl/canu/archive/v1.3.tar.gz
tar xf v1.3.tar.gz
cd canu-1.3/src
make -j 8
```
Any way, I might made some confusing when trying to make it run at all cost.
Thank you again
Miguel
