### ISSUE TITLE
Restart assembly after moving the assembly working directory

### ISSUE THREAD

**Issue by sebastiangornik** [marbl/canu#1711]
Hi,

for reasons of available space on a cluster device I had to move my assembly to a different directory midway through read correction. I was assuming that as long as within the working directory all files remain unchanged canu should easily pick up where it stopped. However, I now get this error:
```
readline() on closed filehandle NEW at /sw/csi/canu/1.9/el7.6_gnu6.4.0/canu-1.9/Linux-amd64/bin/../lib/site_perl/canu/Report.pm line 156.
```
and
```
Undefined subroutine &canu::Report::caExit called at /sw/csi/canu/1.9/el7.6_gnu6.4.0/canu-1.9/Linux-amd64/bin/../lib/site_perl/canu/Report.pm line 67.
```
Any advice? I hope it is just a matter of erasing some script or config file. Otherwise I lost 4 weeks of computation :-(.

Thanks!

**Comment by skoren** [comment]
Restarting in another folder should work fine, this doesn't look like a canu error but an issue with your new filesystem. All this bit of code is doing is opening the report file for writing, the fact that it reports this as a closed file handle means the open failed. Most likely, the permissions are not correct after the move. Do you have permissions to write to the files you moved (try editing the report file yourself)?

**Comment by skoren** [comment]
Idle, seems to be a permissions issue.
