### ISSUE TITLE
Contig size is bigger than before because of bubble sequences

### ISSUE THREAD

**Issue by xuzhougeng** [marbl/canu#1717]
Recently, I use the canu(v2.0) to assemble a diploid plant genome,  I find the v2.0's report is a different than v1.9.

This report is from canu(v1.8)

```
-- Found, in version 2, after consensus generation:
--   contigs:      163 sequences, total length 167437903 bp (including 21 repeats of total length 2797200 bp).
--   bubbles:      0 sequences, total length 0 bp.
--   unassembled:  118241 sequences, total length 1274842904 bp.
```

And this report is from canu v2.0

```
-- Found, in version 2, after consensus generation:
--   contigs:      179 sequences, total length 166110249 bp (including 2 repeats of total length 190835 bp).
--   bubbles:      136 sequences, total length 6145969 bp.
--   unassembled:  2985 sequences, total length 59476754 bp.
```

The two contig are almose same, but the bubbles increase to 136 (about 6M). I check other reports produced by old version canu,  and I find the bubbles all are zero.

Should I **remove the bubbles** when I use hic/bionano to scaffold the contig?

Is it caused by the improvements of contig construction of "Detect bubbles during contig construction and prevent them from shattering heterozygous genomes." ?

**Comment by skoren** [comment]
The older versions didn't really remove/detect bubbles properly. You should remove the bubbles, in fact we usually recommend running something like purge_dups (see FAQ) on the full contig set (including bubbles) to make sure you remove any additional contigs that Canu should have flagged as bubbles but didn't.

**Comment by xuzhougeng** [comment]
Thanks for your suggession, I will test purge_dups on my full contig set.
