### ISSUE TITLE
Canu --assemble for merging overlapping contigs

### ISSUE THREAD

**Issue by dcopetti** [marbl/canu#1718]
Hello,

I wonder if the --assemble option will work in my case: I have sets (100s) of 2-5 WGS long read contigs that overlap (I know this from their alignment to the optical map and they share some bands) and I would like to merge them into one longer sequence.
My doubt is that there is no redundancy in the sequences, like when instead corrected/trimmed reads are used.
Do you think that it would work? contigs are 50 - 100s kb, >99% accurate.

Or, what other tool would you suggest to use? I thought of minimus2, but I wonder if there is something newer around.
Thanks,

Dario

**Comment by skoren** [comment]
There would be a couple of issues with just using assembly, one is that there is a max read limit of 2mb so you'd want to take just the ends of the contigs you want to merge. You also want to keep the overlapping constrained so don't put in all 1000s of sets at the same time but run each 2-5 or even just the pairs you want to merge. I think assemble would work but it will likely flag your result as "unassembled" (see FAQ on how to adjust the parameters to avoid that). 

I think you may be able to get by with something much simpler like an alignment and stitching. You could just use minimap2 to find the matching sequence in the contigs then stitch them together using those coordinates. I'm not sure there is much benefit in trying to get a consensus of the region from just 2 contigs anyway.

**Comment by dcopetti** [comment]
Thank you for your feedback,
I was going to do individual assemblies for each region, as you suggest.
I tried a few examples, but canu does not find overlaps. The command is:
`canu minInputCoverage=1 stopOnLowCoverage=1 contigFilter="2 0 1.0 0.5 0" useGrid=false minReadLength=2000 minOverlapLength=2000 maxMemory=80 maxThreads=18 -p ctg_4075-ctg_8153 -d ctg_4075-ctg_8153 genomeSize=326k -assemble -corrected -pacbio-hifi ../concatenated_inputs/ctg_4075-ctg_8153.fa &>log_ctg_4075-ctg_8153`
and the log is attached
[log_ctg_4075-ctg_8153.txt](https://github.com/marbl/canu/files/4671911/log_ctg_4075-ctg_8153.txt)
The genome size is the total size of the input file (2-7 fastas), since the overlaps span 10-20% of contig lenght. Sometimes I had to decrease the genome size by 10-20% to have a k-mer frequency above 1 at some step - but that's minor. I assumed that the -pacbio-hifi would be the format that fits best my conitgs (from ONT assembled with Flye, polished 2x with long reads, 1x with short reads).

In the attached pdf there are two exemplar regions, with the evidence I had from the optical map and the overlap I see at the dotplot
[partial_overlap_assemblies.pdf](https://github.com/marbl/canu/files/4671926/partial_overlap_assemblies.pdf)
So the overlaps are there, but are not enough for Canu maybe. Do you think there is something else I can tweak in the command to make it work?
Thanks,

Dario

**Comment by skoren** [comment]
I'm not sure the overlap is high enough quality for hifi, that only looks out to 1% error. I'd run it with nanopore-corrected instead with the same option. Can you share one of the fasta files?

**Comment by dcopetti** [comment]
I think we did some progress: with `nanopore-corrected` there is one overlap:
```
-- Found 1 overlapInCore output files.
-- overlapInCore compute 'unitigging/1-overlapper':
--   kmer hits
--     with no overlap                1           1 +- 0
--     with an overlap                1           1 +- 0
--   overlaps                         1           1 +- 0
--     contained                      0           0 +- 0
--     dovetail                       1           1 +- 0
--   overlaps rejected
--     multiple per pair              0           0 +- 0
--     bad short window               0           0 +- 0
--     bad long window                0           0 +- 0
-- No change in report.
-- Finished stage 'utg-overlapCheck', reset canuIteration.
```
but still no contig in output, nor I can find useful information in the log files.
[log_ctg_4075-ctg_8153.txt](https://github.com/marbl/canu/files/4671963/log_ctg_4075-ctg_8153.txt)

**Comment by skoren** [comment]
Thanks for emailing the data, as I suspected the error rate is much higher than what hifi assumes. I mapped the two contigs with mashmap:
```
OF1p3c_ctg_8153 78415 60000 78414 + OF1p3c_ctg_4075 249869 0 17559 96.9554
```

So yes, you need to use nanopore-corrected or -pacbio-corrected. 

The other issue is just the fact that canu is designed assuming depeer than 1x coverage and some quirks of how it builds contigs. You want to disable all the filtering it has for bad reads (```batOptions="-nofilter covgap,spur,lopsided"```) and you need to reverse-complement the input contigs you want to join. The reason is canu builds the config from the 3' end of a read which when you have normal coverage of a genome doesn't really matter (since you have reads in both orientations present) but in your case there is nothing to build. My final command was:
```
canu -p asm -d test genomeSize=300k -assemble -nanopore-corrected rc.fa  batOptions="-nofilter covgap,spur,lopsided" contigFilter="2 0 1.0 0.5 0" stopOnLowCoverage=0 minInputCoverage=0
```

**Comment by dcopetti** [comment]
thanks for the tips, I'll give it a try
