### ISSUE TITLE
assembly both pacbio and short illumina reads

### ISSUE THREAD

**Issue by wisekh6** [marbl/canu#172]
Hello,
I successfully assembled pacbio long reads with canu. Thank you for your helps.
I just wonder if your have a plan to implement a "hybrid-mode" canu that can work using both long read pacbio and short illumina reads.
Thank you,

**Comment by skoren** [comment]
Nope, no plans/interest. We've found the hierarchical approach performs better than a hybrid one over some minimum coverage like 20-30X so our recommendation is to use short-read data after you have your contigs from a PacBio-only assembly.

You can use the short reads to improve your assembly consensus using a tool like Pilon, you can also use short-reads for scaffolding if you have large >10kbp insert sizes using standalone scaffolders like SSPACE or Opera-LG

**Comment by wisekh6** [comment]
thank you very much for your suggestions. It helps a lot.
