### ISSUE TITLE
Generate the genome fasta

### ISSUE THREAD

**Issue by KaiqiangLiu** [marbl/canu#1721]
Hi, 
I got a similar issue as #936 when generate the final genome, and following is my case. 
```
software/canu-1.9/Linux-amd64/bin/tgStoreDump \
      -S ./lx02.seqStore \
      -T ./unitigging/lx02.ctgStore 2 \
      -consensus -fasta \
      -contigs \
    > ./lx02.contigs.v2.fasta
    2> ./lx02.contigs.v2.err
```
I run the same command twice, unfortunately, the same error occurred.

cat lx02.contigs.v2.err
tgTig::loadFromStream()-- not at a tigRecord, got bytes 'CTGA' (0x43544741).
Failed to load tig 49679903. 
The contig.fasta stoped to generate at tig 49679903, any ideas to ignore this tig and continue to create the rest of the genome? 

Thanks in advance.
Best.

**Comment by skoren** [comment]
I'm guessing you're hitting some file limit on the system? What does ```ls -lha ./unitigging/lx02.ctgStore``` report? Do you really have 50 million tigs? That seems like something likely went wrong earlier in the assembly to generate so many.

**Comment by KaiqiangLiu** [comment]
I guess I do have 50 million tigs since the genome is large.
ls -lha ./unitigging/lx02.ctgStore showed below.

drwxr-xr-x 1 username blctmp  300 May 19 03:59 .
drwxr-xr-x 1 username blctmp  812 May 18 09:25 ..
-rw-r--r-- 1 username blctmp 7.2G May 13 15:42 seqDB.v001.dat
-rw-r--r-- 1 username blctmp  16K May 13 16:04 seqDB.v001.sizes.txt
-rw-r--r-- 1 username blctmp 4.2G May 13 15:42 seqDB.v001.tig
-rw-r--r-- 1 username blctmp 2.7T May 19 03:58 seqDB.v002.dat
-rw-r--r-- 1 username blctmp    0 May 19 03:59 seqDB.v002.sizes.txt
-rw-r--r-- 1 username blctmp 4.2G May 19 03:58 seqDB.v002.tig

Besides, the seqDB.v002.sizes.txt is also empty, I guess it also caused by the tig above.

**Comment by skoren** [comment]
Yes, I expect the log for the run will report an error for that step as well (in one of the ```canu-scripts/canu.*.out``` files if you're running on a grid). I'm actually surprised other steps didn't fail as well, do you have any errors in files like ```unitigging/5-consensus/*.err``` or unitigging/4-unitigger/alignGFA.*.out```? 

The fasta dump does support contig IDs so you could try to run something like:
```
software/canu-1.9/Linux-amd64/bin/tgStoreDump 
-S ./lx02.seqStore 
-T ./unitigging/lx02.ctgStore 2 
-tig 1-49679902
-consensus -fasta 
-contigs 
> ./lx02.contigs.part1.fasta
software/canu-1.9/Linux-amd64/bin/tgStoreDump 
-S ./lx02.seqStore 
-T ./unitigging/lx02.ctgStore 2 
-consensus -fasta 
-tig 49679904-<whatever your max tig id is>
-contigs 
> ./lx02.contigs.part2.fasta
```
However, I suspect this will not work as I am suspecting an overflow of some indexing variable rather than that one tig being bad.

**Comment by KaiqiangLiu** [comment]
There are some warnings in unitigging/5-consensus/*.err, like 
tgStore::insertTig()-- WARNING: tig 1096 read 3001397 at (4766,18731) exceeded multialign length 17599
tgStore::insertTig()-- WARNING: tig 5714 read 172770 at (1746,15224) exceeded multialign length 14890
tgStore::insertTig()-- WARNING: tig 6933 read 6782784 at (7129,18567) exceeded multialign length 17988

alignGFA.*.out showed failed as well.  

when I run the command, 
software/canu-1.9/Linux-amd64/bin/tgStoreDump \
      -S ./lx02.seqStore \
      -T ./unitigging/lx02.ctgStore 2 \
      -consensus -fasta \
      -tig 49679910-143304945 \
      -contigs \
    > ./lx02.contigs.part2.fasta
    2> ./lx02.contigs.part2.err 

it turned out the same error message, it seems that '-tig 49679910-143304945' does not help to ignore the tig 49679903.

WARNING: adjusting tig ID range from 49679904-143304945 to 49679904-93625040 as there are only 93625041 tigs in the store.
tgTig::loadFromStream()-- not at a tigRecord, got bytes 'CTGA' (0x43544741).
Failed to load tig 49679903.

**Comment by skoren** [comment]
I'm surprised Canu got to the contig dump given that GFA failed. That should have aborted the pipeline. Is the dump a manual command you're running?

One possible workaround (assuming you don't care about the gfa outputs or read assignment to contigs) is to re-generate the consensus but output it directly to fasta instead of binary. You'd have to edit ```unitigging/5-consensus/consensus.sh``` and change the ```-O``` option to a ```-onlycontig -A```. Then, re-run all the consensus jobs (```unitigging/5-consensus/consensus.jobSubmit*sh``` should have the commands). Your ctgcns folder will now have fasta files that you can concatenate together to get your genome.

**Comment by KaiqiangLiu** [comment]
Thanks for your quick reply. 
I checked the other Canu run, found that one may directly output the contig.fasta after consensus.sh since the files needed for the genome generation exist, so I manually command my run after finishing the job consensus.sh with the following two commands parallelly, 

software/canu-1.9/Linux-amd64/bin/tgStoreDump \
		-S ./lx02.seqStore \
		-T ./unitigging/lx02.ctgStore 2 \
		-o ./lx02.contigs \
		-layout \
		> ./lx02.contigs.layout.err 2>&1

software/canu-1.9/Linux-amd64/bin/tgStoreDump \
      -S ./lx02.seqStore \
      -T ./unitigging/lx02.ctgStore 2 \
      -consensus -fasta \
      -contigs \
    > ./lx02.contigs.fasta
    2> ./lx02.contigs.err
Btw, what is the difference with or  without the gfa outputs or read assignment to contigs  for the final genome? 
I will try your suggestion and give you feedback soon.

Many Thanks.

**Comment by KaiqiangLiu** [comment]
Follow your advice, I changed the  -O option to a -onlycontig -A to  run the consensus.sh, but there is one problem that needs more than 2T memory, any ideas to reduce memory consumption? 
one of my command is,
software/canu-1.9/Linux-amd64/bin/utgcns  \
-S ../lx02.ctgStore/partitionedReads.seqStore  \  
-T ../lx02.ctgStore 2 0002  \
 -onlycontig -A ./ctgcns/0002.cns.fasta  \ 
 -maxcoverage 40    \
-e 0.05   \
-pbdagcon \   
-edlib  \
-threads 64 

Thanks.

**Comment by skoren** [comment]
The memory usage shouldn't be different from the A to the O option but the command doesn't look like what Canu is using in consensus.sh. There are several issues:
 - You didn't provide the partitions that load a subset of reads. You likely need to recreate them first since they got cleaned up after the initial run.
 - You should also be using the v1 of the store not version 2
 - The -e option looks low unless you have hifi data

Re-generate the partitions (from inside the unitizing folder) run:
```
utgcns \
      -S ../lx02.seqStore \
      -T  ./lx02.ctgStore 1 \
      -partition 0.8 1.5 0.1 \
    > ./lx02.ctgStore/partitioning.log 2>&1
```
and make sure there are files named ```lx02.ctgStore/partition.*```.

Use the consensus.sh command as a template (run for all partitions you have from 0001 to however many you have.
```
$bin/utgcns \
  -R ../lx02.ctgStore/partition.0001 \
  -T ../asm.${tag}Store 1 \
  -P 0002 \
  -onlycontig -A ctgcns/0001.cns.fasta \
  -maxcoverage 40 \
  -e 0.075 \
  -pbdagcon \
  -edlib    \
  -threads 8
```

**Comment by KaiqiangLiu** [comment]
1)My data is hifi one.
2)The program to re-generate the partitions (from inside the unitizing folder) run is utgcns or sqStoreCreatePartition, I am afraid there is no -partition option in utgcns, my canu version is 1.9.
3)I actually re-generated the partition file by sqStoreCreatePartition before running the command line

sqStoreCreatePartition \
                -S ../lx02.seqStore \
		-T  ./lx02.ctgStore 1 \
		-b 100000 \
		-p 63 \
		> ./lx02.ctgStore/partitionedReads.log 2>&1

Btw, using the version 1 is mandatory?

Thanks.

**Comment by skoren** [comment]
Ah yes you need sqStoreCreateParitition since you're on 1.9, you also should use 
```
-S ../lx02.ctgStore/partitionedReads.seqStore
```
instead of 
```
-R ../lx02.ctgStore/partition.0001 \
```
Yes, using version 1 is mandatory. Your version 2 is corrupt so it doesn't make sense to use it.

Since you do have HiFi data, I'd strongly recommend running a new assembly with 2.0 once you finish getting the consensus. The HiFi support in 1.9 is very preliminary.

**Comment by KaiqiangLiu** [comment]
Finally, it works with version 1. 
Thanks.

**Comment by skoren** [comment]
I'd still strongly suggest running version 2.0 if you can, the HiFi support in 1.9 was quite preliminary. I'm also curious if it still causes a crash in 2.0 or if it is fixed.
