### ISSUE TITLE
Canu trio binning question

### ISSUE THREAD

**Issue by LQHHHHH** [marbl/canu#1722]
Hi,

I'am using Canu 2.0 to try trio binning assembly following the description in [canu docs](https://canu.readthedocs.io/en/latest/quick-start.html#trio-binning-assembly). You noted that we should use raw sequences. Does the raw sequences specifically refer to the PacBio/ONT sequences or also include the NGS sequences. **Should I filter the NGS data (e.g. remove low quality reads, remove adaptor) before using trio binning or just using raw NGS data to find unique k-mer.**

thanks

**Comment by skoren** [comment]
You can pre-process the illumina data, it won't hurt anything but it likely won't make much difference. 

The histogram is used to estimate an automatic cutoff for k-mers to use for haplotype assignment so error k-mers from low quality regions will be filtered. The adaptor k-mers are unlikely to occur in real data too.
