### ISSUE TITLE
version `GOMP_4.0' not found

### ISSUE THREAD

**Issue by nahanoo** [marbl/canu#1725]
Hi,

I'm running in a very similar issue as issue #1699 .
I tried both building from release and the compiled binaries both resulting in the same error. For building from release I used `GCC 7.3.0`. 
Somehow in the correction step `meryl` keeps falling back to `GCC 4.8.4` causing an error. I can't manage to prevent canu form falling back to use `GCC 4.8.4`.

Error log:
```
canu-2.0/Linux-amd64/bin/meryl: /apps/GCC/4.8.4/lib64/libgomp.so.1: version `GOMP_4.0' not found (required by canu-2.0/Linux-amd64/bin/meryl)
```

I'm running canu on a grid and the canu version of debate is 2.0

Kind regards

**Comment by skoren** [comment]
As in #1699, the issue isn't with Canu, it's with your cluster nodes. Canu isn't picking 4.8.4, it's the GCC defined on the system where it is running. 

The usual issue is that your head node where you're launching/compiling has some modules load which change the GCC version but this environment isn't being carried over to the submitted jobs. You'll need to figure out on your grid how to maintain the environment for the submitted job (on SGE for example this means adding -V to the submission command).

**Comment by nahanoo** [comment]
Thank you very much for your time. 

As far as I understand the issue was that by default the `GCC 4.8.4` path was in the `LD_LIBRARY_PATH` environment variable. That's also why it failed with the compiled binary. 

Executing `ml purge` before executing canu cleared the `LD_LIBRARY_PATH` variable and the canu binary worked.

Another hurdle was also that I had to remove the output folder of the canu test run.

Have a nice day
