### ISSUE TITLE
Make canu only see half of available cores

### ISSUE THREAD

**Issue by bistace** [marbl/canu#1727]
Hi,

I work on a Linux server that is shared between my lab and another lab. The server has 96 cores and 2TB of RAM, but to make the sharing of this server fair, we can only use 48 out of the 96 available cores.

When I launch Canu locally, it tries to use all available cores, would it be possible for me to make it see only 48 cores instead of 96?

**Comment by brianwalenz** [comment]
Yup.  `maxThreads=48`.  It'll probably never get close to using all the memory, but you can also set `maxMemory=1t`, or even 512g; you'll be CPU limited before using that much memory.

**Comment by bistace** [comment]
Fantastic, thank you!
