### ISSUE TITLE
large genome size changed in sqStoreCreate

### ISSUE THREAD

**Issue by pickettbd** [marbl/canu#1728]
I recently downloaded the version 2.0 binary from the releases page. The result of `canu --version` is "Canu 2.0". Long story short: my error is now fixed due to further development, but it naturally persists in the official release of version 2.0. I was unable to find an explanation of what was happening in the other issues, so I thought it might be useful to document this if someone else experiences the same issue. I fully expect the issue to be closed once it is read by the team at MarBL. The [commit](https://github.com/marbl/canu/commit/c1e4ac2f1cd44aac373ac2d17f96de39f131e078) that fixes this issue is c1e4ac2 from 11 May 2020. It has the message: "Parse genome size as float to avoid overflowing with genomes >4gb".

The genome I am assembling has a genome size of 9.455 Gb. 189.1 Gb of PacBio HiFi reads were generated, which amounts to 20x coverage. `sqStoreCreate` decided to downsample to about 43.3 Gb, which was only 4.57x coverage. The result was the following error at the end of the log file `canu.out`. 

```
-- ERROR:  Read coverage (4.57) lower than allowed.
-- ERROR:    minInputCoverage  = 10
-- ERROR:    stopOnLowCoverage = 10
-- ERROR:
-- ERROR:  This could be caused by an incorrect genomeSize or poor quality
-- ERROR:  reads that cound not be sufficiently corrected.
-- ERROR:
-- ERROR:  You can force Canu to continue by decreasing parameters
-- ERROR:  minInputCoverage and/or stopOnLowCoverage.  Be warned that the
-- ERROR:  quality of corrected reads and/or contiguity of contigs will be poor.
--
```

For reference, this was the `sqStoreCreate` command as found in `assembly-name.seqStore.sh`:

```
/path/to/sqStoreCreate \
  -o ./assembly-name.seqStore.BUILDING \
  -minlength 1000 \
  -genomesize 9455000000 \
  -coverage   50 \
  -bias       0 \
  -raw -trimmed -pacbio-hifi libraryName /path/to/libraryName.fq
```

The program was correctly able to load 189.1 Gb into the sequence store, the failure came when it had to decide if any reads should be dropped due to excess coverage (in this case, above 50x). You can see the result in `assembly-name.seqStore.err`:

```
Creating library 'libraryName' for PacBioHiFi corrected-trimmed reads.

               reads               bases
---------- --------- ------ ------------ ------
Loaded      12054493 100.0% 189075214549 100.0%  /path/to/libraryName.fq
Short           2154   0.0%       372057   0.0%


All reads processed.

               reads               bases
---------- --------- ------ ------------ ------
Loaded      12054493 100.0% 189075214549 100.0%
Short           2154   0.0%       372057   0.0%

sqStore_loadMetadata()-- Using 'corrected-trimmed' 0x10 reads.

EXCESSIVE COVERAGE DETECTED.  Sampling reads.

For genome size of    865065408 bases,
            retain  43253270400 bases (50.00X coverage).

Found     12054493 reads with 189075214549 bases (218.57X coverage).
Dropped    9297012 reads with 145821938904 bases (168.57X coverage).
Retained   2757481 reads with  43253275645 bases (50.00X coverage).

Bye.
```

As you can see, canu was able to load the 189.1 Gb of sequence into the seqstore, but calculated the coverage as being too high. The parameters provided were 50x coverage and 9.455 Gb genome size, yet somehow sqStoreCreate used a genome size of 865 Mb instead. Given this genome size, the coverage would certainly be considered excessive. The issue, obviously, is that the genome size is 9.455 Gb, not 865 Mb. Once the downsampling occurred, canu correctly determined that 43 Gb of sequence is insufficient coverage (4.57x). So, why did canu use a genome size of 865 Mb in this instance? The issue is an overflow when converting a large genome size to an integer (`atoi`). If you are using v2.0 and have a genome size larger than about 4 Gb, you should use a more recent commit or version 2.1 (or later) after the release.

**Comment by skoren** [comment]
There are a lot of other changes between the release and that commit that you may not want just to fix this. I just pushed it to the 2.0 branch. Please try to pull the 2.0 branch version and build locally:
```
git clone https://github.com/marbl/canu.git
cd canu
git checkout v2.0-maintenance
rm -r Linux-amd64
make
```

We hope to have a 2.1 release in the next few weeks.

**Comment by pickettbd** [comment]
That is a good suggestion; I'll do that! Thank you for pushing those changes to the 2.0 branch.
