### ISSUE TITLE
Hicanu input reads format

### ISSUE THREAD

**Issue by guosongjia** [marbl/canu#1733]
Hi\
Thanks for your novel software which now suitable for Pacbio Hifi reads! \
I'm a beginner of genome assembly and it's my first time dealing with Hifi reads. I downloaded the example data about the sequencing of E.coli from [SRA](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR10971019). After transforming `fastq` file to `fasta` file, I found that the name of each reads contains the word "ccs" like below.
```
$ cat ecoli.fasta |grep ">" |head
>m54316_180808_005743/5636304/ccs rq:f:0.995286 np:i:5
>m54316_180808_005743/5636332/ccs rq:f:0.992906 np:i:4
>m54316_180808_005743/5636435/ccs rq:f:0.993936 np:i:4
>m54316_180808_005743/5701907/ccs rq:f:0.999643 np:i:10
>m54316_180808_005743/5702212/ccs rq:f:0.999539 np:i:8
>m54316_180808_005743/5702226/ccs rq:f:0.999563 np:i:9
>m54316_180808_005743/5702378/ccs rq:f:0.999363 np:i:9
>m54316_180808_005743/5767403/ccs rq:f:0.998918 np:i:6
>m54316_180808_005743/5832827/ccs rq:f:0.996384 np:i:5
>m54316_180808_005743/5832938/ccs rq:f:0.999376 np:i:8
```
Does it mean that these are already Hifi-reads after the processing of pacbio's `ccs` [software](https://github.com/PacificBiosciences/ccs#changelog) using subreads as input? If so, do you have any recommendations about the parameters of `ccs`  software?\
Thanks~\
Guo-Song

**Comment by skoren** [comment]
Yes typically PacBio has been submitting the fastq after calling CCS reads not the raw bam output from the sequencer (which are typically much larger). You can input either the fastq or the fasta to Canu, doesn't matter, use the -pacbio-hifi option to specify the reads.
