### ISSUE TITLE
out of space

### ISSUE THREAD

**Issue by fengyuanli304** [marbl/canu#1734]
Hi,
I am using Canu 1.9 to correct my data. I have 10T disk space, but my assembly is running out of space. Could you please advise on how we could improve this? 
The data was generated from Pacbio sequel II library, representing approximately 84-fold coverage of the genome. The genome feature high levels of repetitive sequences (60.05%) and heterozygosity(1.3%).
I am running on Linux with slurm.
Data was corrected with the following parameters:
```
/lfy/software/canu-1.9/Linux-amd64/bin/canu -correct \
    -p toxeus -d /lfy/canucorrection \
    genomeSize=2.91g \
    correctedErrorRate=0.045 \
    corOutCoverage=90 \
    useGrid=false \
    maxMemory=500G maxThreads=20 \
    corMhapFilterThreshold=0.0000000002 corMhapOptions="--threshold 0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50" mhapMemory=60g mhapBlockSize=500 ovlMerDistinct=0.975\
    ovsMemory=16G ovbConcurrency=15 ovsConcurrency=15 \
    -pacbio-raw /lfy/merge.fastq.gz
```
Beast wishes,
Fengyuan

**Comment by skoren** [comment]
I think this may be due to a couple of factors, first given your high coverage you can probably get away with:
```
corMhapOptions="--threshold 0.80 --num-hashes 256 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50" 
```
this would mean you need to restart overlapping. Second, adding the ```purgeOverlaps=agressive``` option will clean up more as you're running. 

You may be able to manually apply the extra cleanup and continue this assembly, the FAQ lists some. Essentially, if you have all your ovb files and have the asm.ovlStore.BUILDING folder, you can likely remove 1-overlapper/blocks, if you have an asm.ovlStore.BUILDING/1-bucketizing.success file, you can remove 1-overlapper/results.

**Comment by fengyuanli304** [comment]
Thank you for your reply.  
I have got the toxeus.ovlStore.BULDING, 1-overlapper and 0-mercounts folders. Should I delete  toxeus.ovlStore.BULDING and 1-overlapper folders before I restart this pipeline using the following parameters?
/lfy/software/canu-1.9/Linux-amd64/bin/canu -correct \
    -p toxeus -d /lfy/canucorrection \
    genomeSize=2.91g \
    correctedErrorRate=0.045 \
    corOutCoverage=90 \
    useGrid=false \
    maxMemory=500G maxThreads=20 \
    corMhapFilterThreshold=0.0000000002 corMhapOptions="--threshold 0.80 --num-hashes 256 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50" mhapMemory=60g mhapBlockSize=500 ovlMerDistinct=0.975\
    ovsMemory=16G ovbConcurrency=15 ovsConcurrency=15 \
    purgeOverlaps=agressive \
    -pacbio-raw /lfy/merge.fastq.gz

Waiting for your reply. 
Best wishes,
Fengyuan

**Comment by skoren** [comment]
You want to remove the 1-overlapper and the ovlStore.BUILDING folders, you can leave the 0-mercounts folder.

**Comment by skoren** [comment]
Any update?

**Comment by skoren** [comment]
Idle, documented suggestions on FAQ to reduce space
