### ISSUE TITLE
Request for help with parameterization suggestions for a bacterial genome with large repeats

### ISSUE THREAD

**Issue by dbayles** [marbl/canu#174]
I've got a 3.6 MB bacterial genome that has several large repeats of at least two or more copies of repeats that are approximately 25, 35, and 55 Kb.  As input, I have three PacBio runs that are 7.7 KB mean read length 75x coverage, 8.3 KB mean read length 58x coverage, and 12.5 KB mean read length and 76x coverage.  Using CANU v. 1.3 I've tried varying the error rate specification and have tried changing the overlapper algorithm used in the unitigging, but none of these parameterizations has resulted in any substantive improvement in the assembly compared to the assembly made using the default parameters.  Given the large number of tunable settings in CANU, I'm wondering if you have any suggestions for tuning additional parameters to potentially assemble across at least some of these large repeats.

Regards,

Darrell

**Comment by skoren** [comment]
What are the longest corrected reads you have in your assembly? Your best option would be to try the sensitive parameters I recommended in issue #159:
```
corMhapSensitivity=high corMinCoverage=0
```

That will give you the most corrected data. However, given the size of your PacBio reads and the size of the repeats, it's likely you won't have sufficiently long reads to resolve all the repeats.

**Comment by dbayles** [comment]
The longest corrected reads (not necessarily assembled, but output from running canu -correct) are approximately 130 reads > 25 KB in length.  In KB, the top 10 in length are:
42320
41326
34593
34373
34318
33794
32812
32806
31659
31643

I'll give the sensitive parameters a try and let you know if there is an improvement.
