### ISSUE TITLE
Error corMaxEvidenceErate=0.15

### ISSUE THREAD

**Issue by josruirod** [marbl/canu#1742]
Hi,
So I'm using canu v2.0 on Linux and getting an error when providing corMaxEvidenceErate=0.15 in the spec file.

I'm getting:
ERROR:  File not found or unknown specFile option line '﻿corMaxEvidenceErate=0.15'.
ERROR:  File not found in spec file option '﻿corMaxEvidenceErate=0.15'

Full command: 
canu -p XX -s pacbio.spec -pacbio fastq

Any tips? Is this option no longer supported?

Thanks for the support

**Comment by skoren** [comment]
The option is supported, I would guess your spec file has special characters causing the issue. Can you post your spec file here?

**Comment by josruirod** [comment]
Hi, 
Thanks very much for the suggestion. That seems to be the case and now it seems o be working fine.

Thanks again and sorry for the silly error!
