### ISSUE TITLE
duo approach

### ISSUE THREAD

**Issue by chklopp** [marbl/canu#1744]
Hi,

I'm assembling a tree genome for which we only have DNA from the mother and will not be able to find DNA from the father (long distance fecundation, too many potential fathers). Is it possible to reduce the trio approach to a duo approach? If yes, where could I find the scripts or procedure to run this?

**Comment by skoren** [comment]
We've done limited testing of duos but no official support no and certainly nothing scripted. You could try to decide which k-mers are the heterozygous ones in the F1 and then use those to make bins for the two parents.
