### ISSUE TITLE
Overlap error adjustment jobs failed, tried 2 times, giving up.

### ISSUE THREAD

**Issue by gitalvaro** [marbl/canu#1746]
After running the following command, I got the error on the title:

../canu-2.0/Linux-amd64/bin/canu  -assemble -useGrid=false  genomeSize=33m -p rexxania_Canu_2.0  correctedErrorRate=0.05 -pacbio-corrected r54094_20200401_173718-1_A01_m54094_200401_175727.subreads.fastq maxThreads=20

```
-- Canu 2.0
--
-- Detected Java(TM) Runtime Environment '1.8.0_252' (from 'java') with -d64 support.
-- Detected gnuplot version '5.2 patchlevel 2   ' (from 'gnuplot') and image format 'png'.
-- Detected 20 CPUs and 74 gigabytes of memory.
-- Limited to 20 CPUs from maxThreads option.
-- No grid engine detected, grid and staging disabled.
--
--                                (tag)Concurrency
--                         (tag)Threads          |
--                (tag)Memory         |          |
--        (tag)             |         |          |       total usage      algorithm
--        -------  ----------  --------   --------  --------------------  -----------------------------
-- Local: meryl     12.000 GB    4 CPUs x   5 jobs    60.000 GB  20 CPUs  (k-mer counting)
-- Local: hap        8.000 GB    4 CPUs x   5 jobs    40.000 GB  20 CPUs  (read-to-haplotype assignment)
-- Local: cormhap    6.000 GB   10 CPUs x   2 jobs    12.000 GB  20 CPUs  (overlap detection with mhap)
-- Local: obtovl     4.000 GB    5 CPUs x   4 jobs    16.000 GB  20 CPUs  (overlap detection)
-- Local: utgovl     4.000 GB    5 CPUs x   4 jobs    16.000 GB  20 CPUs  (overlap detection)
-- Local: cor        8.000 GB    4 CPUs x   5 jobs    40.000 GB  20 CPUs  (read correction)
-- Local: ovb        4.000 GB    1 CPU  x  18 jobs    72.000 GB  18 CPUs  (overlap store bucketizer)
-- Local: ovs        8.000 GB    1 CPU  x   9 jobs    72.000 GB   9 CPUs  (overlap store sorting)
-- Local: red       14.000 GB    4 CPUs x   5 jobs    70.000 GB  20 CPUs  (read error detection)
-- Local: oea        8.000 GB    1 CPU  x   9 jobs    72.000 GB   9 CPUs  (overlap error adjustment)
-- Local: bat       16.000 GB    4 CPUs x   1 job     16.000 GB   4 CPUs  (contig construction with bogart)
-- Local: cns        -.--- GB    4 CPUs x   - jobs     -.--- GB   - CPUs  (consensus)
-- Local: gfa       16.000 GB    4 CPUs x   1 job     16.000 GB   4 CPUs  (GFA alignment and processing)
--
-- In 'rexxania_Canu_2.0.seqStore', found PacBio CLR reads:
--   PacBio CLR:               1
--
--   Corrected:                1
--   Corrected and Trimmed:    1
--
-- Generating assembly 'rexxaniania_Canu_2.0' in '/home/a0/pacbiodata':
--    - assemble corrected and trimmed reads.
--
-- Parameters:
--
--  genomeSize        33000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0500 (  5.00%)
--    utgOvlErrorRate 0.0500 (  5.00%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0500 (  5.00%)
--    utgErrorRate    0.0500 (  5.00%)
--    cnsErrorRate    0.0500 (  5.00%)
--
--
-- BEGIN ASSEMBLY
--
-- No change in report.
-- No change in report.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'oea' concurrent execution on Tue Jun 23 08:56:12 2020 with 67.011 GB free disk space (2 processes; 9 concurrently)

    cd unitigging/3-overlapErrorAdjustment
    ./oea.sh 15 > ./oea.000015.out 2>&1
    ./oea.sh 17 > ./oea.000017.out 2>&1

-- Finished on Tue Jun 23 08:56:17 2020 (5 seconds) with 67.011 GB free disk space
----------------------------------------
--
-- Overlap error adjustment jobs failed, retry.
--   job 00015.oea FAILED.
--   job 00017.oea FAILED.
--
-- No change in report.
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'oea' concurrent execution on Tue Jun 23 08:56:17 2020 with 67.011 GB free disk space (2 processes; 9 concurrently)

    cd unitigging/3-overlapErrorAdjustment
    ./oea.sh 15 > ./oea.000015.out 2>&1
    ./oea.sh 17 > ./oea.000017.out 2>&1

-- Finished on Tue Jun 23 08:56:22 2020 (5 seconds) with 67.011 GB free disk space
----------------------------------------
--
-- Overlap error adjustment jobs failed, tried 2 times, giving up.
--   job 00015.oea FAILED.
--   job 00017.oea FAILED.
--

ABORT:
ABORT: Canu 2.0
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```
Any idea how to solve this? Thanks in advance!

**Comment by skoren** [comment]
Post the output of one of the failed jobs (either ```unitigging/3-*/*15*out or *17*out```)

**Comment by gitalvaro** [comment]
Thanks for the answer. 

Below is the content of oea.000015.out. 

(File blobs.0000 does not seem to have been generated; others did:  blobs.0001, blobs.0002, blobs.0003).

---------------------------
more oea.000015.out

Found perl:
   /usr/bin/perl
   This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi

Found java:
   /usr/bin/java
   openjdk version "1.8.0_252"

Found canu:
   /home/axxxxx/canu-2.0/Linux-amd64/bin/canu
   Canu 2.0

Running job 15 based on command line options.
Initializing.
Opening seqStore '../../rexxania_Canu_2.0.seqStore'.
sqStore_loadMetadata()-- Using 'corrected-trimmed' 0x10 reads.
Correcting reads 2050010 to 2197143.
Reading 3236438 corrections from './red.red'.
Correcting 300147936 bases with 230 indel adjustments.
--Allocate 286 + 0 + 4 MB for bases, adjusts and reads.
Corrected 300147936 bases with 0 substitutions, 0 deletions and 0 insertions.
Loading overlaps.
Read_Olaps()--  Loading 0 overlaps from '../rexxania_Canu_2.0.ovlStore' for reads 2050010 to 2197143
--Allocate 0 MB for overlaps.
Read_Olaps()--  Loaded 0 overlaps -- 0 normal and 0 innie.
Sorting overlaps.
Recomputing overlaps.
--Allocate 8 MB for fseq and rseq.
--Allocate 32 MB for fadj and radj.
--Allocate 16 MB for pedWorkArea_t.
-- Allocate 0 MB for Edit_Array pointers.
Recomputing overlaps -         0 -         0 - 2348690937
fetchFromObjectStore()-- fetching file '../../rexxania_Canu_2.0.seqStore/blobs.0000'
fetchFromObjectStore()--   from object ':/rexxania_Canu_2.0.seqStore/blobs.0000'
fetchFromObjectStore()-- execve() failed with error 'No such file or directory'.
fetchFromObjectStore()-- execve() failed to run the command.

**Comment by skoren** [comment]
There shouldn't be a blobs.0000 file, I think either the red file has an issue or there is an issue reading your overlaps. The lines:
```
Read_Olaps()--  Loading 0 overlaps from '../rexxania_Canu_2.0.ovlStore' for reads 2050010 to 2197143
--Allocate 0 MB for overlaps.
Read_Olaps()--  Loaded 0 overlaps -- 0 normal and 0 innie.
Sorting overlaps.
Recomputing overlaps.
...
Recomputing overlaps -         0 -         0 - 2348690937
```
look suspicious as those values are most likely wrong. I expect you're hitting a bug where one of the partitions has no overlaps to load leading to an error. 

I noticed in your command you're providing Pacbio subreads but telling Canu not to run correction or trimming and using only 5% error rate? What kind of data is in the subreads, they are likely to be much too high error for this to work.

**Comment by gitalvaro** [comment]
Thanks again for the input. I am now testing with correction and trimming and waiting for the results...

**Comment by skoren** [comment]
Any updates?

**Comment by gitalvaro** [comment]
Correction and trimming both finished without error and produced output. The assembly is still running.

**Comment by skoren** [comment]
Idle, uncorrected assembly of raw reads isn't supported.
