### ISSUE TITLE
make: *** No rule to make target `meryl/src/meryl/meryl.mk'.  Stop.

### ISSUE THREAD

**Issue by pezhmansafdari** [marbl/canu#1747]
Hi,
I am trying to install canu form git repository and I get the following error:
make -j 56
You need to run this command from the toplevel of the working tree.

You need to run this command from the toplevel of the working tree.

You need to run this command from the toplevel of the working tree.

Makefile:677: meryl/src/meryl/meryl.mk: No such file or directory
You need to run this command from the toplevel of the working tree.
Failed to open 'utility/src/utility/version.H.new' for writing: No such file or directory
Building snapshot v2.0-development +533 changes (r10026 1b104d26d6b278118f6cf1c90608ad85dc29cb38) (sync'd with github)
For 'Linux' '3.10.0-1127.10.1.el7.x86_64' as 'amd64' into '/home/safdari/canu/Linux-amd64/{bin,obj}'.
Using '/usr/bin/g++' version '4.9.2'.

make: *** No rule to make target `meryl/src/meryl/meryl.mk'.  Stop.
[safdari@cyrus src]$ make -j 8
You need to run this command from the toplevel of the working tree.

You need to run this command from the toplevel of the working tree.

You need to run this command from the toplevel of the working tree.

Makefile:677: meryl/src/meryl/meryl.mk: No such file or directory
You need to run this command from the toplevel of the working tree.
Failed to open 'utility/src/utility/version.H.new' for writing: No such file or directory
Building snapshot v2.0-development +533 changes (r10026 1b104d26d6b278118f6cf1c90608ad85dc29cb38) (sync'd with github)
For 'Linux' '3.10.0-1127.10.1.el7.x86_64' as 'amd64' into '/home/safdari/canu/Linux-amd64/{bin,obj}'.
Using '/usr/bin/g++' version '4.9.2'.

make: *** No rule to make target `meryl/src/meryl/meryl.mk'.  Stop.

Would you please tell what the problem is?
BR,
Pezhman

**Comment by skoren** [comment]
This can happen with very old versions of git which don't have good support for submodules. What does ```git --version``` report on your system? We recommend git 2.2 or newer. In general, unless you're planning to do development, we recommend the release version for installation instead as it is tested and stable unlike the master branch.
