### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by sekhwal** [marbl/canu#1748]
I am getting following error while processing the data:

scontrol: error: s_p_parse_file: unable to status file /etc/slurm-llnl/slurm.conf: No such file or directory, retrying in 1sec up to 60sec

Command:
canu -p ecoli -d canu-ecoli genomeSize=4.6m -nanopore-raw ERR908493_1.fastq

**Comment by skoren** [comment]
Your grid is not configured correctly, slurm isn't letting Canu get the information on the nodes. You can run off grid with useGrid=false but if you want to use more than a single node you'll have to get in contact with your IT group to help fix slurm.

**Comment by sekhwal** [comment]
Thanks. It worked.
