### ISSUE TITLE
Where are the Hicanu results??

### ISSUE THREAD

**Issue by luferise30** [marbl/canu#1751]
Hello,  

I just run HiCanu the process finished without any error but I can't see the results of the assembly on any generated directory. Here the command :

##software
module load hicanu/1.9/gnu6.4.0

##run the application:
canu -d Hw2 -p Hassawi2 genomeSize=400m -pacbio-hifi m64041_200619_190612.Q20.fasta usegrid=1 gridOptions="--time=5-00:00:00 --partition=batch --mem-per-cpu=16g" gridOptionsJobName=Hassawi2.grid

Here the output directories:
Hw2]$ ls
canu-logs  canu-scripts     Hassawi2.seqStore      Hassawi2.seqStore.sh
canu.out   Hassawi2.report  Hassawi2.seqStore.err  trimming

Here the latest part of canu.out file:

-- Starting command on Sun Jun 28 21:20:37 2020 with 2548141.226 GB free disk space

    cd /ibex/scratch/projects/c2067/Hifi_Hassawi/HiCanu/test2/Hw2
    sbatch \
      --depend=afterany:11061588 \
      --cpus-per-task=1 \
      --mem-per-cpu=4g \
      --time=5-00:00:00 \
      --partition=batch \
      --mem-per-cpu=16g  \
      -D `pwd` \
      -J 'canu_Hassawi2_Hassawi2.grid' \
      -o canu-scripts/canu.05.out  canu-scripts/canu.05.sh
Submitted batch job 11061589

-- Finished on Sun Jun 28 21:20:37 2020 (in the blink of an eye) with 2548141.226 GB free disk space

Thank you in advance ,

Luis.

**Comment by skoren** [comment]
A good idea to check the FAQ and other issues before asking: https://canu.readthedocs.io/en/latest/tutorial.html#execution-configuration or #1642.

It's running as expected on the grid. However, given the output file names I believe you've run the same Canu command multiple times on the same folder which means there are now multiple runs competing for that folder. I would kill all your grid jobs, remove the current run folder, and start Canu again (after upgrading to 2.0 as I already said in response to your previous comment). Once it submits to the grid it is running and you don't need to do anything. The canu.out file will tell you the latest progress and will report any errors if they happen. Also, do not specify ```--mem-per-cpu=16g```.
