### ISSUE TITLE
1-overlapper over 2 TB

### ISSUE THREAD

**Issue by AlexdeMendoza** [marbl/canu#1756]
Hi, I am running Canu 2.0 (distributed as binaries) in a Grid using this command:

```
canu \
-p MyGenome -d /data/scratch/btx717/MyGenome/canu2.v1 \
-pacbio-raw Mygenome.fastq.gz \
genomeSize=170m \
useGrid=true \
correctedErrorRate=0.085 corMhapSensitivity=normal \
gridEngineResourceOption="-l h_vmem=MEMORY -pe smp THREADS" \
gridOptions="-l h_rt=72:0:0 -j y -l highmem" \
"batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" \
"gridOptionsGFA=-l h_vmem=300G" \
"gridOptionsovb=-l h_vmem=120G" \
"gridOptionsovs=-l h_vmem=120G" \
"gridOptionscorovl=-l h_vmem=30G" \
"gridOptionscor=-l h_vmem=30G" \
"gridOptionscns=l h_vmem=40G" \
gnuplot=$(which gnuplot) \
java=$(which java)
> /data/scratch/btx717/MyGenome/canu2.v1LOG/LOG 2>&1
```

The software seemed to be running well, but the 1-overlapper folder has bloated to 1.7TB, and the `*.ovlStore.BUILDING` folder is about 771Gb. This caused the job to fail, since my server has a limitation of 2TB on scratch drive. 

The input file is a combination of RSII and Sequel fastq (generated from bam), which combined are 16Gb (gzipped by default by `bam2fastq` software).

I assume this might be related to the repetitiveness of the genome, but I am not sure. Is there a way to check this?
Any tip on trying to reduce the output of the files?

Thanks in advance for your help.

Alex

**Comment by skoren** [comment]
There are suggestions on the FAQ for adjusted parameters to reduce space. Depending on your coverage (if over 70x) you may also be able to use corMhapSensitivity=low. You also want purgeOverlaps=aggressive which will clean up intermediate files sooner. Both of these would require you to restart from scratch. 

You may be able to manually apply the extra cleanup and continue this assembly, the FAQ lists some. Essentially, if you have all your ovb files and have the asm.ovlStore.BUILDING folder, you can likely remove 1-overlapper/blocks, if you have an asm.ovlStore.BUILDING/1-bucketizing.success file, you can remove 1-overlapper/results.

**Comment by woodoo46** [comment]
Following up this question, we had 70X human Sequel II data (mean read length is about 20k). We had seen excessive space usage (10T) with default parameters (Canu 1.9);
1) is this normal? (From FAQ answer, it seems this is not normal)
2) if we set up corMhapSensitivity=low as well as the suggestion in the FAQ; how would this affect the final assembly?
3) in general, what is the main factor affecting the space usage, for example, number of reads, or read length?

Thanks!

George

**Comment by skoren** [comment]
@woodoo46 as I recall you were using an old version of Canu which didn't clean up all intermediate files as it should. That created part of the space. The main determinant of size is repeat content, coverage, and sensitivity settings. For a 70x human genome, the default should be corMhapSensitivity=low unless you explicitly change it. Sequel II data works fine with default parameters as the FAQ states so I'd definitely use corMhapSensitivity=low.

**Comment by woodoo46** [comment]
We have switched to 1.9.  You are right, I had set up corMhapSensitivity=normal; I will give it a try.
