### ISSUE TITLE
canu and slurm in dynamic cluster on aws

### ISSUE THREAD

**Issue by hidrargyro** [marbl/canu#1758]
Hello, I will describe my environment first. I have a cluster in aws with slurm, but in this case, slurm manage how many nodes I have based on the jobs scheduled, so, if no jobs are running, only the master node is alive. The problem is that if I run the canu ecoli example, it will not detect any node as you can see below:

```
ubuntu@ip-10-0-0-84:/shared/canu$ canu -p ecoli -d ecoli-pacbio genomeSize=4.8m gridOptions=""  -pacbio-raw input/pacbio.fastq
-- Canu 2.0
--
-- Detected Java(TM) Runtime Environment '1.8.0_252' (from 'java') with -d64 support.
-- Detected gnuplot version '5.2 patchlevel 2   ' (from 'gnuplot') and image format 'png'.
-- Detected 2 CPUs and 8 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /opt/slurm/bin/sinfo.
-- Detected Slurm with task IDs up to 1000 allowed.
-- 

ABORT:
ABORT: Canu 2.0
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   invalid useGrid (1) and gridEngine (SLURM); found no execution hosts - is grid available from this host?.
ABORT:

```
Next try was to spin up some nodes manually (really tiny ones 2 cpu and 8GB of ram, just to see if I have a different error message)  and then canu is saying that in fact he can see nodes, but it states that slurm has no control on the ram  of the nodes, which i do not what means, but i can send jobs to these nodes using sbatch without problem. The output is the following:

```
ubuntu@ip-10-0-0-84:/shared/canu$ sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
compute*     up   infinite      2   idle ip-10-0-13-152,ip-10-0-14-206
ubuntu@ip-10-0-0-84:/shared/canu$ canu -p ecoli -d ecoli-pacbio genomeSize=4.8m gridOptions=""  -pacbio-raw input/pacbio.fastq
-- Canu 2.0
--
-- Detected Java(TM) Runtime Environment '1.8.0_252' (from 'java') with -d64 support.
-- Detected gnuplot version '5.2 patchlevel 2   ' (from 'gnuplot') and image format 'png'.
-- Detected 2 CPUs and 8 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /opt/slurm/bin/sinfo.
-- Detected Slurm with task IDs up to 1000 allowed.
-- 
-- Found   2 hosts with   2 cores and    0 GB memory under Slurm control.
--
-- ERROR
-- ERROR
-- ERROR  Found 0 machine configurations:
-- ERROR
-- ERROR  Task meryl can't run on any available machines.
-- ERROR  It is requesting:
-- ERROR    merylMemory=4-12 memory (gigabytes)
-- ERROR    merylThreads=1-4 threads
-- ERROR
-- ERROR  No available machine configuration can run this task.
-- ERROR
-- ERROR  Possible solutions:
-- ERROR    Change merylMemory and/or merylThreads
-- ERROR

ABORT:
ABORT: Canu 2.0
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   task meryl failed to find a configuration to run on.
ABORT:

``` 

The thing is, I do not know how canu interacts with slurm, but any script run with sbatch in the cluster spins up the nodes automatically. There is any special configuration for this kind of clusters?

**Comment by brianwalenz** [comment]
The easiest will be to make up a 'fake' sinfo command that returns a list of your preferred node sizes.  The only tricky part is getting the fake version to be used instead of the real one.

The relevant code in canu is in src/pipelines/canu/Grid_Slurm.pm, the last roughly 40 lines.  It's calling `sinfo --exact -o '%N %D %c %m' | grep -v drained | grep -v interactive` to build a list how many nodes have X CPUs and Y memory.  Canu doesn't use the number of nodes when a grid is involved, so your fake 'sinfo' can just report 1 node at each desired CPU and memory size.

Alternatively, you can hard code the node sizes you want to use.  Replace all the stuff between the `open(F, ...)` and `close(F)` lines with, e.g.:
```
$hosts{"24-128"} = 4;
```
This would tell canu the grid has 4 nodes available, each with 24 CPUs and 128 GB memory.

The second error was canu complaining your nodes are too small.  For some reason, it didn't detect any memory on those nodes.

**Comment by skoren** [comment]
Idle

**Comment by hidrargyro** [comment]
Hi, I has been doing some tests in the last couple of weeks, it finally worked!
SO, if anyone wants to have it working with pcluster and slurm in aws, the steps are:

- Fake nodes in the canu perl script (`src/pipelines/canu/Grid_Slurm.pm`) you must replace the last while loop with the size of the computes nodes you'll be using, in my case each node have 24 cores and 128GB of RAM, I'll say to canu that I have 4 of them, but it is not important, canu will use as much as needed when running: `$hosts{"24-128"} = 4;`
- Determine the RealMemory available in the compute instance. We can get this by logging into the compute and running `/opt/slurm/sbin/slurmd -C`, we should see something like `RealMemory=121543`.
- Edit `/opt/slurm/etc/slurm.conf` and add `NodeName=DEFAULT RealMemory=[RealMemory for compute nodes] `**BEFORE** `include slurm_parallelcluster_nodes.conf`. Note that ideally we should just use the _RealMemory_ we got from `/opt/slurm/sbin/slurmd -C`, but _RealMemory_ might be different even for different instances of the same instance type. I would round down _RealMemory_ slightly just to avoid any potential error when the cluster is scaling and launching new instances.
- Restart `slurmctld` on master node, and we should see that memory is configured in `scontrol show nodes`, if you have compute nodes up before this configuration, and you want to use them, restart `slurmd` on the compute nodes as well.
The last part of the configuration was taken from [here](https://github.com/aws/aws-parallelcluster/issues/1517)

**Comment by skoren** [comment]
Thanks
