### ISSUE TITLE
Inadvertant fork bomb?

### ISSUE THREAD

**Issue by plattsa** [marbl/canu#176]
Hi

I ran the Canu pipeline once and all seemed to go ok although at one point I noted an awful lot of gzip processes running in paeallel.  I just ran it again with slightly increased sensitivity and the same maxThreads (28)

./canu -p Oenothera -d Oen_all_sensitive genomeSize=400m maxMemory=120 maxThreads=28 -pacbio-raw Long_Oen.fastq useGrid=false  corMhapSensitivity=high corMinCoverage=0

however this failed with the error "Can't fork: Resource temporarily unavailable".  This suggests that more than 4,096 user processes were running.  I restarted Canu from the last checkpoint and it does indeed seem to be running way more than 28 threads/processes ... any suggestions?

$ ps -u $UID | wc -l
1404

This number of processes is growing quickly and seems to be mostly hundreds of gzip processes coming from Canu (9 processes come from non-Canu sources).

$ ps -u $UID
   PID TTY          TIME CMD
 27866 ?        00:06:30 sshd
 27867 ?        00:02:08 sftp-server
 29038 ?        00:00:00 screen
 29039 pts/2    00:00:00 bash
104661 ?        00:00:00 sshd
104662 pts/0    00:00:00 bash
121763 pts/2    00:00:00 perl
121869 pts/2    00:00:00 sh
121870 pts/2    00:00:00 sh
121871 pts/2    00:00:00 sh
121872 pts/2    00:00:00 sh
121873 pts/2    00:00:00 sh
121874 pts/2    00:00:00 sh
121875 pts/2    00:00:00 1-bucketize.sh
121876 pts/2    00:00:00 sh
121877 pts/2    00:00:00 1-bucketize.sh
121878 pts/2    00:00:00 sh
121879 pts/2    00:00:00 1-bucketize.sh
121880 pts/2    00:00:00 sh
121881 pts/2    00:00:00 1-bucketize.sh
121882 pts/2    00:00:00 sh
121883 pts/2    00:00:00 1-bucketize.sh
121884 pts/2    00:00:00 sh
121885 pts/2    00:00:00 sh
121887 pts/2    00:00:00 1-bucketize.sh
121888 pts/2    00:00:00 1-bucketize.sh
121889 pts/2    00:00:00 sh
121890 pts/2    00:00:00 1-bucketize.sh
121893 pts/2    00:00:00 sh
121895 pts/2    00:00:00 1-bucketize.sh
121896 pts/2    00:00:00 sh
121897 pts/2    00:00:00 1-bucketize.sh
121899 pts/2    00:00:00 sh
121900 pts/2    00:00:00 sh
121901 pts/2    00:00:00 sh
121902 pts/2    00:00:00 1-bucketize.sh
121903 pts/2    00:00:00 1-bucketize.sh
121906 pts/2    00:00:00 sh
121907 pts/2    00:00:00 1-bucketize.sh
121909 pts/2    00:00:00 1-bucketize.sh
121910 pts/2    00:00:00 sh
121913 pts/2    00:00:00 sh
121914 pts/2    00:00:00 1-bucketize.sh
121916 pts/2    00:00:00 1-bucketize.sh
121917 pts/2    00:00:00 sh
121918 pts/2    00:00:00 1-bucketize.sh
121919 pts/2    00:00:00 sh
121920 pts/2    00:00:00 1-bucketize.sh
121921 pts/2    00:00:00 sh
121924 pts/2    00:00:00 1-bucketize.sh
121925 pts/2    00:00:00 sh
121927 pts/2    00:00:00 1-bucketize.sh
121929 pts/2    00:00:00 sh
121934 pts/2    00:00:00 sh
121936 pts/2    00:00:00 1-bucketize.sh
121937 pts/2    00:00:00 1-bucketize.sh
121941 pts/2    00:00:00 sh
121944 pts/2    00:00:00 1-bucketize.sh
121949 pts/2    00:00:00 1-bucketize.sh
121955 pts/2    00:00:00 1-bucketize.sh
121956 pts/2    00:00:00 1-bucketize.sh
121961 pts/2    00:00:00 1-bucketize.sh
121967 pts/2    00:00:00 1-bucketize.sh
122065 pts/2    00:00:05 ovStoreBucketiz
122071 pts/2    00:00:05 ovStoreBucketiz
122077 pts/2    00:00:06 ovStoreBucketiz
122100 pts/2    00:00:05 ovStoreBucketiz
122117 pts/2    00:00:04 ovStoreBucketiz
122129 pts/2    00:00:06 ovStoreBucketiz
122136 pts/2    00:00:06 ovStoreBucketiz
122152 pts/2    00:00:06 ovStoreBucketiz
122171 pts/2    00:00:05 ovStoreBucketiz
122179 pts/2    00:00:05 ovStoreBucketiz
122185 pts/2    00:00:05 ovStoreBucketiz
122190 pts/2    00:00:06 ovStoreBucketiz
122199 pts/2    00:00:06 ovStoreBucketiz
122200 pts/2    00:00:05 ovStoreBucketiz
122203 pts/2    00:00:05 ovStoreBucketiz
122205 pts/2    00:00:06 ovStoreBucketiz
122206 pts/2    00:00:06 ovStoreBucketiz
122212 pts/2    00:00:06 ovStoreBucketiz
122222 pts/2    00:00:06 ovStoreBucketiz
122223 pts/2    00:00:05 ovStoreBucketiz
122226 pts/2    00:00:06 ovStoreBucketiz
122227 pts/2    00:00:06 ovStoreBucketiz
122228 pts/2    00:00:05 ovStoreBucketiz
122229 pts/2    00:00:06 ovStoreBucketiz
122230 pts/2    00:00:05 ovStoreBucketiz
122231 pts/2    00:00:05 ovStoreBucketiz
122232 pts/2    00:00:05 ovStoreBucketiz
122233 pts/2    00:00:06 ovStoreBucketiz
122234 pts/2    00:00:01 gzip
122235 pts/2    00:00:01 gzip
122236 pts/2    00:00:00 sh
122237 pts/2    00:00:00 sh
122238 pts/2    00:00:00 sh
122239 pts/2    00:00:00 sh
122240 pts/2    00:00:00 sh
122241 pts/2    00:00:00 sh
122242 pts/2    00:00:00 sh
122243 pts/2    00:00:00 sh
122244 pts/2    00:00:00 sh
122245 pts/2    00:00:00 sh
122246 pts/2    00:00:00 gzip
122247 pts/2    00:00:00 sh
122248 pts/2    00:00:00 gzip
122249 pts/2    00:00:00 gzip
122250 pts/2    00:00:00 sh
122251 pts/2    00:00:00 sh
122252 pts/2    00:00:00 sh
122253 pts/2    00:00:00 sh
122254 pts/2    00:00:00 gzip
122255 pts/2    00:00:01 gzip
122256 pts/2    00:00:00 sh
122257 pts/2    00:00:00 sh
122258 pts/2    00:00:00 gzip
122259 pts/2    00:00:00 sh
122260 pts/2    00:00:00 gzip
122261 pts/2    00:00:00 sh
122262 pts/2    00:00:01 gzip
122263 pts/2    00:00:00 gzip
122264 pts/2    00:00:00 gzip
122265 pts/2    00:00:00 gzip
122266 pts/2    00:00:00 gzip
122267 pts/2    00:00:00 gzip
122268 pts/2    00:00:00 gzip
122269 pts/2    00:00:00 gzip
122270 pts/2    00:00:00 gzip
122271 pts/2    00:00:00 gzip
122272 pts/2    00:00:00 gzip
122273 pts/2    00:00:00 gzip
122274 pts/2    00:00:01 gzip
122275 pts/2    00:00:00 sh
122276 pts/2    00:00:00 sh
122277 pts/2    00:00:00 sh
122278 pts/2    00:00:00 sh
122279 pts/2    00:00:00 sh
122280 pts/2    00:00:00 sh
122281 pts/2    00:00:00 sh
122282 pts/2    00:00:00 sh
122283 pts/2    00:00:00 sh
122284 pts/2    00:00:00 gzip
122285 pts/2    00:00:00 gzip
122286 pts/2    00:00:01 gzip
122287 pts/2    00:00:00 gzip
122288 pts/2    00:00:00 gzip
122289 pts/2    00:00:00 gzip
122290 pts/2    00:00:00 gzip
122291 pts/2    00:00:00 gzip
122292 pts/2    00:00:00 gzip
122293 pts/2    00:00:01 gzip
122294 pts/2    00:00:00 sh
122295 pts/2    00:00:00 sh
122296 pts/2    00:00:00 sh
122297 pts/2    00:00:00 sh
122298 pts/2    00:00:00 sh
122299 pts/2    00:00:00 sh
122300 pts/2    00:00:00 gzip
122301 pts/2    00:00:00 sh
122302 pts/2    00:00:00 gzip
122303 pts/2    00:00:00 sh
122304 pts/2    00:00:00 sh
122305 pts/2    00:00:00 gzip
122306 pts/2    00:00:00 gzip
122307 pts/2    00:00:00 gzip
122308 pts/2    00:00:00 gzip
122309 pts/2    00:00:00 gzip
122310 pts/2    00:00:01 gzip
122311 pts/2    00:00:00 gzip
122312 pts/2    00:00:01 gzip
122313 pts/2    00:00:01 gzip
122314 pts/2    00:00:00 sh
122315 pts/2    00:00:00 sh
122316 pts/2    00:00:00 sh
122317 pts/2    00:00:00 sh
122318 pts/2    00:00:00 sh
122319 pts/2    00:00:00 sh
122320 pts/2    00:00:00 sh
122321 pts/2    00:00:00 sh
122322 pts/2    00:00:00 sh
122323 pts/2    00:00:00 gzip
122324 pts/2    00:00:00 gzip
122325 pts/2    00:00:00 sh
122326 pts/2    00:00:00 gzip
122327 pts/2    00:00:00 gzip
122328 pts/2    00:00:00 gzip
122329 pts/2    00:00:00 gzip
122330 pts/2    00:00:01 gzip
122331 pts/2    00:00:00 gzip
122332 pts/2    00:00:00 gzip
122333 pts/2    00:00:00 gzip
122334 pts/2    00:00:01 gzip
122335 pts/2    00:00:01 gzip
122336 pts/2    00:00:00 sh
122337 pts/2    00:00:00 sh
122338 pts/2    00:00:00 sh
122339 pts/2    00:00:00 sh
122340 pts/2    00:00:00 sh
122341 pts/2    00:00:00 sh
122342 pts/2    00:00:00 sh
122343 pts/2    00:00:00 gzip
122344 pts/2    00:00:00 sh
122345 pts/2    00:00:00 sh
122346 pts/2    00:00:00 gzip
122347 pts/2    00:00:00 gzip
122348 pts/2    00:00:00 gzip
122349 pts/2    00:00:00 gzip
122350 pts/2    00:00:00 gzip
122351 pts/2    00:00:00 gzip
122352 pts/2    00:00:00 sh
122353 pts/2    00:00:00 sh
122354 pts/2    00:00:00 gzip
122355 pts/2    00:00:00 gzip
122356 pts/2    00:00:00 sh
122357 pts/2    00:00:00 gzip
122358 pts/2    00:00:00 sh
122359 pts/2    00:00:00 gzip
122360 pts/2    00:00:00 gzip
122361 pts/2    00:00:00 sh
122362 pts/2    00:00:00 gzip
122363 pts/2    00:00:00 gzip
122364 pts/2    00:00:00 sh
122365 pts/2    00:00:00 gzip
122366 pts/2    00:00:00 sh
122367 pts/2    00:00:00 gzip
122368 pts/2    00:00:00 sh
122369 pts/2    00:00:00 gzip
122370 pts/2    00:00:00 sh
122371 pts/2    00:00:00 gzip
122372 pts/2    00:00:00 sh
122373 pts/2    00:00:00 sh
122374 pts/2    00:00:00 sh
122375 pts/2    00:00:00 sh
122376 pts/2    00:00:00 sh
122377 pts/2    00:00:00 sh
122378 pts/2    00:00:00 sh
122379 pts/2    00:00:00 sh
122380 pts/2    00:00:00 gzip
122381 pts/2    00:00:01 gzip
122382 pts/2    00:00:00 gzip
122383 pts/2    00:00:00 sh
122384 pts/2    00:00:00 sh
122385 pts/2    00:00:00 gzip
122386 pts/2    00:00:00 gzip
122387 pts/2    00:00:00 gzip
122388 pts/2    00:00:00 gzip
122389 pts/2    00:00:00 gzip
122390 pts/2    00:00:00 gzip
122391 pts/2    00:00:00 gzip
122392 pts/2    00:00:01 gzip
122393 pts/2    00:00:00 sh
122394 pts/2    00:00:00 sh
122395 pts/2    00:00:00 sh
122396 pts/2    00:00:00 sh
122397 pts/2    00:00:00 sh
122398 pts/2    00:00:00 sh
122399 pts/2    00:00:00 sh
122400 pts/2    00:00:00 sh
122401 pts/2    00:00:01 gzip
122402 pts/2    00:00:00 gzip
122403 pts/2    00:00:00 sh
122404 pts/2    00:00:00 gzip
122405 pts/2    00:00:00 gzip
122406 pts/2    00:00:00 gzip
122407 pts/2    00:00:00 gzip
122408 pts/2    00:00:00 gzip
122409 pts/2    00:00:00 gzip
122410 pts/2    00:00:00 gzip
122411 pts/2    00:00:01 gzip
122412 pts/2    00:00:00 sh
122413 pts/2    00:00:00 sh
122414 pts/2    00:00:00 gzip
122415 pts/2    00:00:00 sh
122416 pts/2    00:00:00 gzip
122417 pts/2    00:00:01 gzip
122418 pts/2    00:00:00 sh
122419 pts/2    00:00:00 sh
122420 pts/2    00:00:00 sh
122421 pts/2    00:00:00 gzip
122422 pts/2    00:00:00 gzip
122423 pts/2    00:00:00 sh
122424 pts/2    00:00:00 gzip
122425 pts/2    00:00:00 gzip
122426 pts/2    00:00:00 sh
122427 pts/2    00:00:00 gzip
122428 pts/2    00:00:00 sh
122429 pts/2    00:00:00 gzip
122430 pts/2    00:00:00 sh
122431 pts/2    00:00:00 gzip
122432 pts/2    00:00:01 gzip
122433 pts/2    00:00:01 gzip
122434 pts/2    00:00:01 gzip
122435 pts/2    00:00:01 gzip
122436 pts/2    00:00:00 sh
122437 pts/2    00:00:00 sh
122438 pts/2    00:00:00 sh
122439 pts/2    00:00:00 sh
122440 pts/2    00:00:00 sh
122441 pts/2    00:00:00 sh
122442 pts/2    00:00:00 sh
122443 pts/2    00:00:00 sh
122444 pts/2    00:00:00 gzip
122445 pts/2    00:00:00 gzip
122446 pts/2    00:00:00 gzip
122447 pts/2    00:00:00 gzip
122448 pts/2    00:00:00 gzip
122449 pts/2    00:00:00 gzip
122450 pts/2    00:00:00 gzip
122451 pts/2    00:00:00 gzip
122452 pts/2    00:00:00 sh
122453 pts/2    00:00:00 sh
122454 pts/2    00:00:00 sh
122455 pts/2    00:00:00 sh
122456 pts/2    00:00:00 sh
122457 pts/2    00:00:00 sh
122458 pts/2    00:00:01 gzip
122459 pts/2    00:00:00 gzip
122460 pts/2    00:00:00 sh
122461 pts/2    00:00:00 gzip
122462 pts/2    00:00:00 gzip
122463 pts/2    00:00:00 sh
122464 pts/2    00:00:00 sh
122465 pts/2    00:00:00 sh
122466 pts/2    00:00:00 gzip
122467 pts/2    00:00:00 gzip
122468 pts/2    00:00:00 gzip
122469 pts/2    00:00:00 gzip
122470 pts/2    00:00:00 gzip
122471 pts/2    00:00:00 gzip
122472 pts/2    00:00:00 sh
122473 pts/2    00:00:00 sh
122474 pts/2    00:00:00 sh
122475 pts/2    00:00:00 sh
122476 pts/2    00:00:00 sh
122477 pts/2    00:00:00 sh
122478 pts/2    00:00:00 sh
122479 pts/2    00:00:00 gzip
122480 pts/2    00:00:00 gzip
122481 pts/2    00:00:00 gzip
122482 pts/2    00:00:01 gzip
122483 pts/2    00:00:00 gzip
122484 pts/2    00:00:00 gzip
122485 pts/2    00:00:00 gzip
122486 pts/2    00:00:00 sh
122487 pts/2    00:00:00 sh
122488 pts/2    00:00:00 sh
122489 pts/2    00:00:00 sh
122490 pts/2    00:00:00 sh
122491 pts/2    00:00:00 sh
122492 pts/2    00:00:00 gzip
122493 pts/2    00:00:00 gzip
122494 pts/2    00:00:00 sh
122495 pts/2    00:00:00 gzip
122496 pts/2    00:00:00 sh
122497 pts/2    00:00:00 gzip
122498 pts/2    00:00:00 gzip
122499 pts/2    00:00:00 gzip
122500 pts/2    00:00:00 gzip
122501 pts/2    00:00:00 gzip
122502 pts/2    00:00:00 sh
122503 pts/2    00:00:00 gzip
122504 pts/2    00:00:01 gzip
122505 pts/2    00:00:00 gzip
122506 pts/2    00:00:01 gzip
122507 pts/2    00:00:00 gzip
122508 pts/2    00:00:00 gzip
122509 pts/2    00:00:01 gzip
122510 pts/2    00:00:01 gzip
122511 pts/2    00:00:00 gzip
122512 pts/2    00:00:00 gzip
122513 pts/2    00:00:01 gzip
122514 pts/2    00:00:00 gzip
122515 pts/2    00:00:01 gzip
122516 pts/2    00:00:01 gzip
122517 pts/2    00:00:01 gzip
122518 pts/2    00:00:00 sh
122519 pts/2    00:00:00 sh
122520 pts/2    00:00:00 sh
122521 pts/2    00:00:00 sh
122522 pts/2    00:00:00 sh
122523 pts/2    00:00:00 sh
122524 pts/2    00:00:00 sh
122525 pts/2    00:00:01 gzip
122526 pts/2    00:00:00 sh
122527 pts/2    00:00:00 gzip
122528 pts/2    00:00:00 sh
122529 pts/2    00:00:00 gzip
122530 pts/2    00:00:00 sh
122531 pts/2    00:00:00 gzip
122532 pts/2    00:00:00 gzip
122533 pts/2    00:00:00 gzip
122534 pts/2    00:00:00 gzip
122535 pts/2    00:00:00 gzip
122536 pts/2    00:00:00 gzip
122537 pts/2    00:00:00 gzip
122538 pts/2    00:00:00 sh
122539 pts/2    00:00:00 sh
122540 pts/2    00:00:00 sh
122541 pts/2    00:00:00 sh
122542 pts/2    00:00:00 sh
122543 pts/2    00:00:00 sh
122544 pts/2    00:00:00 sh
122545 pts/2    00:00:01 gzip
122546 pts/2    00:00:00 sh
122547 pts/2    00:00:00 sh
122548 pts/2    00:00:00 gzip
122549 pts/2    00:00:00 gzip
122550 pts/2    00:00:00 gzip
122551 pts/2    00:00:00 gzip
122552 pts/2    00:00:00 gzip
122553 pts/2    00:00:00 gzip
122554 pts/2    00:00:00 gzip
122555 pts/2    00:00:00 gzip
122556 pts/2    00:00:00 sh
122557 pts/2    00:00:00 sh
122558 pts/2    00:00:00 sh
122559 pts/2    00:00:00 sh
122560 pts/2    00:00:00 sh
122561 pts/2    00:00:00 sh
122562 pts/2    00:00:00 gzip
122563 pts/2    00:00:01 gzip
122564 pts/2    00:00:00 sh
122565 pts/2    00:00:00 sh
122566 pts/2    00:00:00 gzip
122567 pts/2    00:00:00 gzip
122568 pts/2    00:00:00 sh
122569 pts/2    00:00:00 sh
122570 pts/2    00:00:00 gzip
122571 pts/2    00:00:00 sh
122572 pts/2    00:00:00 gzip
122573 pts/2    00:00:00 gzip
122574 pts/2    00:00:00 sh
122575 pts/2    00:00:00 gzip
122576 pts/2    00:00:00 gzip
122577 pts/2    00:00:00 sh
122578 pts/2    00:00:00 sh
122579 pts/2    00:00:00 gzip
122580 pts/2    00:00:00 sh
122581 pts/2    00:00:00 gzip
122582 pts/2    00:00:00 gzip
122583 pts/2    00:00:00 sh
122584 pts/2    00:00:00 sh
122585 pts/2    00:00:00 gzip
122586 pts/2    00:00:00 gzip
122587 pts/2    00:00:00 gzip
122588 pts/2    00:00:00 gzip
122589 pts/2    00:00:00 gzip
122590 pts/2    00:00:00 sh
122591 pts/2    00:00:00 sh
122592 pts/2    00:00:00 sh
122593 pts/2    00:00:00 sh
122594 pts/2    00:00:00 sh
122595 pts/2    00:00:00 sh
122596 pts/2    00:00:00 gzip
122597 pts/2    00:00:00 sh
122598 pts/2    00:00:00 sh
122599 pts/2    00:00:01 gzip
122600 pts/2    00:00:00 sh
122601 pts/2    00:00:00 gzip
122602 pts/2    00:00:00 gzip
122603 pts/2    00:00:00 gzip
122604 pts/2    00:00:00 gzip
122605 pts/2    00:00:00 gzip
122606 pts/2    00:00:00 gzip
122607 pts/2    00:00:00 gzip
122608 pts/2    00:00:00 sh
122609 pts/2    00:00:00 sh
122610 pts/2    00:00:00 sh
122611 pts/2    00:00:00 sh
122612 pts/2    00:00:00 sh
122613 pts/2    00:00:00 sh
122614 pts/2    00:00:00 sh
122615 pts/2    00:00:01 gzip
122616 pts/2    00:00:00 sh
122617 pts/2    00:00:00 gzip
122618 pts/2    00:00:00 gzip
122619 pts/2    00:00:00 sh
122620 pts/2    00:00:00 gzip
122621 pts/2    00:00:00 sh
122622 pts/2    00:00:00 gzip
122623 pts/2    00:00:00 gzip
122624 pts/2    00:00:00 gzip
122625 pts/2    00:00:00 gzip
122626 pts/2    00:00:00 gzip
122627 pts/2    00:00:00 gzip
122628 pts/2    00:00:00 sh
122629 pts/2    00:00:00 sh
122630 pts/2    00:00:00 sh
122631 pts/2    00:00:00 sh
122632 pts/2    00:00:00 sh
122633 pts/2    00:00:00 sh
122634 pts/2    00:00:00 sh
122635 pts/2    00:00:00 sh
122636 pts/2    00:00:00 gzip
122637 pts/2    00:00:00 gzip
122638 pts/2    00:00:00 sh
122639 pts/2    00:00:00 gzip
122640 pts/2    00:00:00 gzip
122641 pts/2    00:00:00 gzip
122642 pts/2    00:00:00 gzip
122643 pts/2    00:00:00 gzip
122644 pts/2    00:00:00 gzip
122645 pts/2    00:00:00 gzip
122646 pts/2    00:00:00 sh
122647 pts/2    00:00:00 sh
122648 pts/2    00:00:00 sh
122649 pts/2    00:00:00 sh
122650 pts/2    00:00:00 sh
122651 pts/2    00:00:00 gzip
122652 pts/2    00:00:00 gzip
122653 pts/2    00:00:00 gzip
122654 pts/2    00:00:00 sh
122655 pts/2    00:00:00 gzip
122656 pts/2    00:00:01 gzip
122657 pts/2    00:00:00 gzip
122658 pts/2    00:00:00 sh
122659 pts/2    00:00:00 sh
122660 pts/2    00:00:00 sh
122661 pts/2    00:00:00 sh
122662 pts/2    00:00:00 sh
122663 pts/2    00:00:00 sh
122664 pts/2    00:00:00 sh
122665 pts/2    00:00:00 gzip
122666 pts/2    00:00:00 gzip
122667 pts/2    00:00:00 gzip
122668 pts/2    00:00:00 sh
122669 pts/2    00:00:00 gzip
122670 pts/2    00:00:00 gzip
122671 pts/2    00:00:00 gzip
122672 pts/2    00:00:00 gzip
122673 pts/2    00:00:00 gzip
122674 pts/2    00:00:00 sh
122675 pts/2    00:00:00 sh
122676 pts/2    00:00:00 sh
122677 pts/2    00:00:00 sh
122678 pts/2    00:00:00 sh
122679 pts/2    00:00:01 gzip
122680 pts/2    00:00:00 sh
122681 pts/2    00:00:00 sh
122682 pts/2    00:00:00 sh
122683 pts/2    00:00:00 sh
122684 pts/2    00:00:00 gzip
122685 pts/2    00:00:00 gzip
122686 pts/2    00:00:00 sh
122687 pts/2    00:00:00 sh
122688 pts/2    00:00:00 sh
122689 pts/2    00:00:00 gzip
122690 pts/2    00:00:00 sh
122691 pts/2    00:00:00 gzip
122692 pts/2    00:00:00 gzip
122693 pts/2    00:00:01 gzip
122694 pts/2    00:00:00 sh
122695 pts/2    00:00:00 gzip
122696 pts/2    00:00:00 sh
122697 pts/2    00:00:00 gzip
122698 pts/2    00:00:00 gzip
122699 pts/2    00:00:00 sh
122700 pts/2    00:00:00 sh
122701 pts/2    00:00:00 gzip
122702 pts/2    00:00:00 gzip
122703 pts/2    00:00:00 sh
122704 pts/2    00:00:00 gzip
122705 pts/2    00:00:00 gzip
122706 pts/2    00:00:00 sh
122707 pts/2    00:00:00 gzip
122708 pts/2    00:00:00 gzip
122709 pts/2    00:00:00 gzip
122710 pts/2    00:00:00 gzip
122711 pts/2    00:00:00 gzip
122712 pts/2    00:00:00 sh
122713 pts/2    00:00:00 sh
122714 pts/2    00:00:00 sh
122715 pts/2    00:00:00 sh
122716 pts/2    00:00:00 sh
122717 pts/2    00:00:00 sh
122718 pts/2    00:00:00 sh
122719 pts/2    00:00:00 gzip
122720 pts/2    00:00:00 sh
122721 pts/2    00:00:00 gzip
122722 pts/2    00:00:00 gzip
122723 pts/2    00:00:00 sh
122724 pts/2    00:00:00 gzip
122725 pts/2    00:00:00 sh
122726 pts/2    00:00:00 gzip
122727 pts/2    00:00:00 gzip
122728 pts/2    00:00:00 gzip
122729 pts/2    00:00:00 gzip
122730 pts/2    00:00:00 gzip
122731 pts/2    00:00:00 gzip
122732 pts/2    00:00:00 sh
122733 pts/2    00:00:01 gzip
122734 pts/2    00:00:00 sh
122735 pts/2    00:00:00 sh
122736 pts/2    00:00:00 sh
122737 pts/2    00:00:00 sh
122738 pts/2    00:00:00 sh
122739 pts/2    00:00:00 gzip
122740 pts/2    00:00:00 sh
122741 pts/2    00:00:00 sh
122742 pts/2    00:00:00 gzip
122743 pts/2    00:00:00 gzip
122744 pts/2    00:00:00 gzip
122745 pts/2    00:00:00 gzip
122746 pts/2    00:00:00 gzip
122747 pts/2    00:00:00 gzip
122748 pts/2    00:00:00 sh
122749 pts/2    00:00:00 sh
122750 pts/2    00:00:00 sh
122751 pts/2    00:00:00 sh
122752 pts/2    00:00:00 sh
122753 pts/2    00:00:00 sh
122754 pts/2    00:00:00 sh
122755 pts/2    00:00:00 sh
122756 pts/2    00:00:01 gzip
122757 pts/2    00:00:00 gzip
122758 pts/2    00:00:00 gzip
122759 pts/2    00:00:00 sh
122760 pts/2    00:00:00 sh
122761 pts/2    00:00:00 gzip
122762 pts/2    00:00:00 gzip
122763 pts/2    00:00:00 gzip
122764 pts/2    00:00:00 gzip
122765 pts/2    00:00:00 gzip
122766 pts/2    00:00:00 gzip
122767 pts/2    00:00:00 gzip
122769 pts/2    00:00:00 sh
122770 pts/2    00:00:01 gzip
122771 pts/2    00:00:00 sh
122772 pts/2    00:00:01 gzip
122773 pts/2    00:00:00 sh
122774 pts/2    00:00:01 gzip
122775 pts/2    00:00:00 sh
122776 pts/2    00:00:01 gzip
122777 pts/2    00:00:00 sh
122778 pts/2    00:00:01 gzip
122780 pts/2    00:00:00 sh
122781 pts/2    00:00:01 gzip
122782 pts/2    00:00:00 sh
122783 pts/2    00:00:01 gzip
122784 pts/2    00:00:00 sh
122785 pts/2    00:00:01 gzip
122786 pts/2    00:00:00 sh
122787 pts/2    00:00:01 gzip
122788 pts/2    00:00:00 sh
122789 pts/2    00:00:01 gzip
122790 pts/2    00:00:00 sh
122791 pts/2    00:00:01 gzip
122792 pts/2    00:00:00 sh
122793 pts/2    00:00:01 gzip
122794 pts/2    00:00:00 sh
122795 pts/2    00:00:01 gzip
122796 pts/2    00:00:00 sh
122797 pts/2    00:00:01 gzip
122798 pts/2    00:00:00 sh
122799 pts/2    00:00:01 gzip
122800 pts/2    00:00:00 sh
122801 pts/2    00:00:01 gzip
122802 pts/2    00:00:00 sh
122803 pts/2    00:00:01 gzip
122804 pts/2    00:00:00 sh
122805 pts/2    00:00:01 gzip
122806 pts/2    00:00:00 sh
122807 pts/2    00:00:00 gzip
122808 pts/2    00:00:00 sh
122809 pts/2    00:00:00 gzip
122811 pts/2    00:00:00 sh
122812 pts/2    00:00:00 gzip
122813 pts/0    00:00:00 ps

$ ./canu/Linux-amd64/bin/canu --version
Canu v1.3 (+27 commits) r7643 4c5f6fef6ae021251b348f8ce7fd47ce294151fd.

Adrian

**Comment by skoren** [comment]
What does Canu report in the preamble where it describes available resources and what it will use?

The code should be using the minimum of maxThreads but you could try manually setting 
```
ovbConcurrency=28 ovsConcurrency=28
```
to see if that fixes your issue.

**Comment by plattsa** [comment]
Thanks skoren,

The preamble goes as follows ...

$ ./canu -p Oenothera -d Oen_all_sensitive genomeSize=400m maxMemory=120 maxThreads=28 -pacbio-raw Long_Oen.fastq useGrid=false corMhapSen
sitivity=high corMinCoverage=0
-- Detected Java(TM) Runtime Environment '1.8.0_91' (from 'java').
-- Detected 56 CPUs and 126 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
-- Allowed to run   4 jobs concurrently, and use up to   7 compute threads and   30 GB memory for stage 'bogart (unitigger)'.
-- Allowed to run   2 jobs concurrently, and use up to  14 compute threads and   13 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   2 jobs concurrently, and use up to  14 compute threads and   13 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   2 jobs concurrently, and use up to  14 compute threads and   13 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   7 jobs concurrently, and use up to   4 compute threads and    6 GB memory for stage 'read error detection (overlap error adjustment)'.
-- Allowed to run  28 jobs concurrently, and use up to   1 compute thread  and    2 GB memory for stage 'overlap error adjustment'.
-- Allowed to run   4 jobs concurrently, and use up to   7 compute threads and   30 GB memory for stage 'utgcns (consensus'.
-- Allowed to run  28 jobs concurrently, and use up to   1 compute thread  and    4 GB memory for stage 'overlap store parallel bucketizer'.
-- Allowed to run  28 jobs concurrently, and use up to   1 compute thread  and   16 GB memory for stage 'overlap store parallel sorting'.
-- Allowed to run  28 jobs concurrently, and use up to   1 compute thread  and    4 GB memory for stage 'overlapper'.
-- Allowed to run   4 jobs concurrently, and use up to   7 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run   4 jobs concurrently, and use up to   7 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run   2 jobs concurrently, and use up to  14 compute threads and   60 GB memory for stage 'meryl (k-mer counting)'.
-- Allowed to run   7 jobs concurrently, and use up to   4 compute threads and   17 GB memory for stage 'falcon_sense (read correction)'.
-- Allowed to run   2 jobs concurrently, and use up to  14 compute threads and   13 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   2 jobs concurrently, and use up to  14 compute threads and   13 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   2 jobs concurrently, and use up to  14 compute threads and   13 GB memory for stage 'minimap (overlapper)'.
--

I just restarted with the below but am already up to 1052 threads.  It looks like 

./canu -p Oenothera -d Oen_all_sensitive genomeSize=400m maxMemory=120 maxThreads=28 -pacbio-raw Long_Oen.fastq useGrid=false corMhapSen
sitivity=high corMinCoverage=0 ovbConcurrency=28 ovsConcurrency=28

It almost seems like whatever is launching these gzip tasks is checking the logical core count and running N x Gzip + N x sh tasks, so with 28 of these running, I'm seeing 28 x 2 x N parallel tasks where N is my logical core count (56).  I think for now I'll run this section with maxThreads=2 and when we move past the next checkpoint, maybe then relaunch with maxThreads=28.

Adrian

**Comment by brianwalenz** [comment]
We're now using https://github.com/google/snappy to compress these files, so no more process explosions.  Support appeared in commit 3208c21070f9ca5d1242eb87e219f1e9bbf00b6d (with a small tweak in 71dcf22e1e315f6f7f1cde22d165fed20c464465).  You'll be better off using the latest version though, or waiting a few weeks for a new release to appear.

Do NOT update code for a currently running assembly, it will fail horribly.
