### ISSUE TITLE
Minimum coverage accepted

### ISSUE THREAD

**Issue by ddEmoryU** [marbl/canu#1760]
Hey guys,
I know that the minimum coverage recommended is 10X, but is it possible to relax this requirement to run datasets for which we might not have gotten enough data to reach the 10X?
Thanks,
Dario

**Comment by skoren** [comment]
We actually recommend 20x, the default to stop assembly is set lower to 10x but it's unlikely you'll get a very good assembly (if any) from such low coverage, especially if you're using raw data and not something like HiFi. The error message Canu reports when you input too little coverage tells you how to ignore this if you want to keep going:
```
-- ERROR:  Read coverage (1.82) lower than allowed.
-- ERROR:    minInputCoverage  = 10
-- ERROR:    stopOnLowCoverage = 10
-- ERROR:
-- ERROR:  This could be caused by an incorrect genomeSize or poor quality
-- ERROR:  reads that cound not be sufficiently corrected.
-- ERROR:
-- ERROR:  You can force Canu to continue by decreasing parameters
-- ERROR:  minInputCoverage and/or stopOnLowCoverage.  Be warned that the
-- ERROR:  quality of corrected reads and/or contiguity of contigs will be poor.
```

So you can add stopOnLowCoverage=0 or similar to continue.

**Comment by skoren** [comment]
Idle, should be resolved by lowering minimum coverage
