### ISSUE TITLE
How to move an abruptly closed run from one server to locally running to complete assembly

### ISSUE THREAD

**Issue by amit4mchiba** [marbl/canu#1761]
Hi Canu Developers,

I am writing here to seek your help to learn if this is possible to move a non-complete run Canu assembly from a server to run it again on a local computer.

I was running my assembly at a server, and after reaching at alignGFA 4-unitigger stage, the program stuck and remained that way for several days. I stopped the program and again tried running, or running alignGFA.sh manually, but either cases, the program is not woking.

I searched in Canu issues, and learnt that such issues could be due to servers sometimes. So, I was wondering if there are ways that I could run this partially completed assembly run locally at my own computer. 

thank you so much,

with best regards
Amit

**Comment by amit4mchiba** [comment]
Hi,

Just adding up from my previous question. I think I simply modified the alignGFA.sh script and add info related to my local server Canu, and I was able to run it. While program seems running but I am not sure as I can not see any output of this run while when I checked using top command, I can see that alignGFA is running. Normally, this step is relatively faster, but for this assembly, it looks taking too long time, and I can not see any output being generated from it. So, I am not sure if I should wait for longer or if there is some issue but still Canu is running.

This is report for my assembly-
[UNITIGGING/READS]
--
-- In sequence store './Gg_15thJune2020_0.085_l10000.seqStore':
--   Found 1590924 reads.
--   Found 32537534777 bases (79.35 times coverage).
--    
--    G=32537534777                      sum of  ||               length     num
--    NG         length     index       lengths  ||                range    seqs
--    ----- ------------ --------- ------------  ||  ------------------- -------
--    00010        42551     67226   3253772757  ||      10000-11311      194341|---------------------------------------------------------------
--    00020        35964    150758   6507540572  ||      11312-12623      178490|----------------------------------------------------------
--    00030        30786    248626   9761269765  ||      12624-13935      147334|------------------------------------------------
--    00040        26280    363176  13015035450  ||      13936-15247      122223|----------------------------------------
--    00050        22537    497019  16268785366  ||      15248-16559      107411|-----------------------------------
--    00060        19384    652868  19522530388  ||      16560-17871       94211|-------------------------------
--    00070        16652    834087  22776274572  ||      17872-19183       82419|---------------------------
--    00080        14187   1045780  26030040296  ||      19184-20495       72095|------------------------
--    00090        12031   1295136  29283788452  ||      20496-21807       63624|---------------------
--    00100        10000   1590923  32537534777  ||      21808-23119       55448|------------------
--    001.000x             1590924  32537534777  ||      23120-24431       49347|----------------
--                                               ||      24432-25743       44169|---------------
--                                               ||      25744-27055       39261|-------------
--                                               ||      27056-28367       35437|------------
--                                               ||      28368-29679       31753|-----------
--                                               ||      29680-30991       29230|----------
--                                               ||      30992-32303       27295|---------
--                                               ||      32304-33615       25101|---------
--                                               ||      33616-34927       23864|--------
--                                               ||      34928-36239       21565|-------
--                                               ||      36240-37551       19899|-------
--                                               ||      37552-38863       18241|------
--                                               ||      38864-40175       16172|------
--                                               ||      40176-41487       14383|-----
--                                               ||      41488-42799       12650|-----
--                                               ||      42800-44111       11087|----
--                                               ||      44112-45423        9464|----
--                                               ||      45424-46735        8195|---
--                                               ||      46736-48047        7235|---
--                                               ||      48048-49359        5969|--
--                                               ||      49360-50671        4880|--
--                                               ||      50672-51983        4133|--
--                                               ||      51984-53295        3300|--
--                                               ||      53296-54607        2653|-
--                                               ||      54608-55919        2067|-
--                                               ||      55920-57231        1720|-
--                                               ||      57232-58543        1298|-
--                                               ||      58544-59855         964|-
--                                               ||      59856-61167         700|-
--                                               ||      61168-62479         492|-
--                                               ||      62480-63791         332|-
--                                               ||      63792-65103         198|-
--                                               ||      65104-66415         109|-
--                                               ||      66416-67727          78|-
--                                               ||      67728-69039          44|-
--                                               ||      69040-70351          25|-
--                                               ||      70352-71663           8|-
--                                               ||      71664-72975           7|-
--                                               ||      72976-74287           1|-
--                                               ||      74288-75599           2|-
--

[UNITIGGING/MERS]
--
--  22-mers                                                                                           Fraction
--    Occurrences   NumMers                                                                         Unique Total
--       1-     1         0                                                                        0.0000 0.0000
--       2-     2 172974389 ********************************************************************** 0.2635 0.0111
--       3-     4 101089052 ****************************************                               0.3651 0.0174
--       5-     7  44088314 *****************                                                      0.4492 0.0252
--       8-    11  20455611 ********                                                               0.4956 0.0318
--      12-    16  11720341 ****                                                                   0.5204 0.0371
--      17-    22  11356692 ****                                                                   0.5366 0.0421
--      23-    29  17819030 *******                                                                0.5544 0.0498
--      30-    37  23446726 *********                                                              0.5827 0.0660
--      38-    46  18641511 *******                                                                0.6178 0.0913
--      47-    56  23290195 *********                                                              0.6450 0.1156
--      57-    67  59957481 ************************                                               0.6834 0.1584
--      68-    79  82257759 *********************************                                      0.7802 0.2876
--      80-    92  37892872 ***************                                                        0.9023 0.4772
--      93-   106   6935668 **                                                                     0.9538 0.5694
--     107-   121   3193020 *                                                                      0.9632 0.5889
--     122-   137   3264980 *                                                                      0.9680 0.6004
--     138-   154   3562591 *                                                                      0.9730 0.6141
--     155-   172   2337266                                                                        0.9783 0.6306
--     173-   191   1461230                                                                        0.9818 0.6424
--     192-   211   1233278                                                                        0.9839 0.6507
--     212-   232   1108483                                                                        0.9858 0.6587
--     233-   254    867600                                                                        0.9875 0.6665
--     255-   277    711752                                                                        0.9888 0.6731
--     278-   301    620613                                                                        0.9899 0.6791
--     302-   326    528267                                                                        0.9908 0.6848
--     327-   352    448643                                                                        0.9916 0.6901
--     353-   379    397258                                                                        0.9923 0.6950
--     380-   407    345443                                                                        0.9929 0.6996
--     408-   436    297758                                                                        0.9934 0.7039
--     437-   466    263370                                                                        0.9939 0.7079
--     467-   497    231944                                                                        0.9943 0.7117
--     498-   529    208797                                                                        0.9946 0.7152
--     530-   562    186875                                                                        0.9949 0.7187
--     563-   596    170050                                                                        0.9952 0.7219
--     597-   631    153513                                                                        0.9955 0.7250
--     632-   667    144377                                                                        0.9957 0.7281
--     668-   704    137946                                                                        0.9959 0.7310
--     705-   742    134212                                                                        0.9961 0.7341
--     743-   781    129538                                                                        0.9963 0.7372
--     782-   821    139111                                                                        0.9965 0.7403
--
--           0 (max occurrences)
-- 31298682049 (total mers, non-unique)
--   656348464 (distinct mers, non-unique)
--           0 (unique mers)

[UNITIGGING/OVERLAPS]
--   category            reads     %          read length        feature size or coverage  analysis
--   ----------------  -------  -------  ----------------------  ------------------------  --------------------
--   middle-missing        162    0.01    18632.91 +- 7866.09       3640.88 +- 5169.85    (bad trimming)
--   middle-hump             1    0.00    18083.00 +- 0.00          3287.00 +- 0.00       (bad trimming)
--   no-5-prime             75    0.00    17724.51 +- 7223.61       1698.24 +- 2545.78    (bad trimming)
--   no-3-prime             90    0.01    18171.54 +- 8252.55       1352.64 +- 2442.56    (bad trimming)
--   
--   low-coverage         1988    0.12    15633.22 +- 5523.87         12.83 +- 6.27       (easy to assemble, potential for lower quality consensus)
--   unique            1115455   70.11    20310.13 +- 9814.75         68.77 +- 17.51      (easy to assemble, perfect, yay)
--   repeat-cont        145077    9.12    19106.10 +- 9299.07       6900.97 +- 5394.00    (potential for consensus errors, no impact on assembly)
--   repeat-dove           875    0.05    43800.68 +- 11859.09      4057.73 +- 3812.10    (hard to assemble, likely won't assemble correctly or even at all)
--   
--   span-repeat         56716    3.56    25405.06 +- 11626.79      4651.20 +- 5567.62    (read spans a large repeat, usually easy to assemble)
--   uniq-repeat-cont   229893   14.45    19274.58 +- 8093.98                             (should be uniquely placed, low potential for consensus errors, no impact on assembly)
--   uniq-repeat-dove    16579    1.04    40212.68 +- 10692.02                            (will end contigs, potential to misassemble)
--   uniq-anchor         24010    1.51    20681.00 +- 9644.49      13074.21 +- 9797.53    (repeat read, with unique section, probable bad read)

[UNITIGGING/ADJUSTMENT]
-- No report available.

[UNITIGGING/CONTIGS]
-- Found, in version 1, after unitig construction:
--   contigs:      1140 sequences, total length 554287102 bp (including 224 repeats of total length 14977493 bp).
--   bubbles:      1343 sequences, total length 115148363 bp.
--   unassembled:  2545 sequences, total length 48070974 bp.
--
-- Contig sizes based on genome size 410mbp:
--
--            NG (bp)  LG (contigs)    sum (bp)
--         ----------  ------------  ----------
--     10    22076994             2    46380283
--     20    14228327             5    90755541
--     30    11037488             8   125429998
--     40     7110586            13   167079172
--     50     5762101            20   209622724
--     60     4173568            28   247001922
--     70     2842259            40   288391600
--     80     2020561            57   329374007
--     90     1071222            85   369063036
--    100      692214           131   410133577
--    110      404187           211   451068866
--    120      221733           343   492169410
--    130       76969           666   533045442
--

[UNITIGGING/CONSENSUS]
-- Found, in version 2, after consensus generation:
--   contigs:      1140 sequences, total length 552534323 bp (including 224 repeats of total length 14953294 bp).
--   bubbles:      1343 sequences, total length 114918750 bp.
--   unassembled:  2545 sequences, total length 48072527 bp.
--
-- Contig sizes based on genome size 410mbp:
--
--            NG (bp)  LG (contigs)    sum (bp)
--         ----------  ------------  ----------
--     10    21999502             2    46215565
--     20    14168423             5    90428452
--     30    10992861             8   124966787
--     40     7079894            13   166478084
--     50     5750197            20   208911440
--     60     4161602            28   246174898
--     70     2834091            40   287442468
--     80     2013031            57   328284699
--     90     1059793            87   369991270
--    100      663752           133   410186030
--    110      397312           215   451287727
--    120      211524           349   492007758
--    130       72827           687   533032591
--

So, in principle, it means I am almost done. Isn't it. But while running on server, this program stuck at this-
Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'gfa' concurrent execution on Wed Jul 15 00:17:26 2020 with 9561.067 GB free disk space (1 processes; 1 concurrently)

    cd unitigging/4-unitigger
    ./alignGFA.sh 1 > ./alignGFA.000001.out 2>&1

I waited for 3 days, but I could not see any output, but server was not killing this program as well or no error could be seen. So, I decided to run it locally, and hence I asked the above question for your help.

In the unitig folder, I could see these outputs-
-- Reading GFA './Gg_15thJune2020_0.085_l10000.unitigs.gfa'.
gfa:  Loaded 6484 sequences and 157712 links.
-- Loading sequences from tigStore '../Gg_15thJune2020_0.085_l10000.utgStore' version 1.
-- Loading sequences from tigStore '../Gg_15thJune2020_0.085_l10000.utgStore' version 2.
-- Resetting sequence lengths.
-- Aligning 157712 links using 8 threads and 8.50 error rate.
WARNING: tig00002700 - tig00002700 + -- circular to the same end!?


But after this, no output or new files can be seen. So, I am not sure if I am being too impatient or indeed Canu keeps running without generating any output as it does not know what to do.

I am so sorry for such a stupid question, but I will really appreciate your help.

thanks and regards
Amit

**Comment by skoren** [comment]
As long as it's using CPU (which you can check via top) it is running. It doesn't have much logging from this step apart from what you already saw. You have relatively high coverage and I see a relatively large number of GFA links which is likely why this is taking a while. You can always just skip this step if you don't want plan to use the unitigs (see #1745).

**Comment by amit4mchiba** [comment]
Thank you so much.

All worked perfect. Indeed, it took too long as large number of GFA links. I was able to run it locally as well as able to skip this step.

I have got two more question, and would really appreciate your help.

Post assembly, these are my assembly stats-
-- Found, in version 1, after unitig construction:
--   contigs:      906 sequences, total length 554486141 bp (including 166 repeats of total length 9603463 bp).
--   bubbles:      1020 sequences, total length 99194181 bp.
--   unassembled:  1577 sequences, total length 44271363 bp.
--
-- Contig sizes based on genome size 410mbp:
--
--            NG (bp)  LG (contigs)    sum (bp)
--         ----------  ------------  ----------
--     10    22188756             2    46032461
--     20    15764183             5    96065482
--     30    13717518             7   125429859
--     40     9892059            11   169523983
--     50     7104341            16   206675932
--     60     4945885            23   248038480
--     70     3884796            32   287417823
--     80     2962993            44   328152828
--     90     1555311            63   369860926
--    100      863529            99   410157108
--    110      501502           163   451470579
--    120      303569           269   492097456
--    130       88488           518   533054215

The expected genome size was 410Mb, Clearly, my species has lots of heterozygosity, and the increased size of assembly was because Canu could not resolved them and hence kept them separate (Thats my understanding based on Canu2 doc). In the manual, the recommendation is to run a purge_dups or purge_haplotigs. 

While I understand this, but wanted to ask about the difference between bubble and contigs. When I checked my assembly, I had in total 1926 sequences (which is the sum of contigs and bubbles). So, these bubbles are important or can I just selected contigs for next stage of genome assembly. Also, as you can see, I have 1577 sequences, wich are unassembled sequences. What about them? I mean is it normal to discard them from scaffolding or what is the recommendation for them. Clearly these could be super repeats or unique sequences that could not get a partner, hence unassembled, but that also means that these could be some contaminants or non-plant sequences, isn't? Ideally we simply take our assembled assembly for scaffolding, but what should be done with unassembled sequences. 

And while we define a nice parameter based on how fewer contigs we get and higher N50, but if I get fewer unassembled sequences, will not that be a good assembly?

thank you so much in advance,

with best regards
Amit

**Comment by skoren** [comment]
The bubbles are pretty conservative and only identified when they could impact the assembly. They should be included in downstream analysis, you can let purge_dups re-classify which part of the assembly it wants to call bubble and contig. The unassembled can typically be discarded. It is possible they are some very repetitive segments but there is also always noise in the data that doesn't get incorporated in the assembly. Since they are also short, scaffolders won't be able to use them either.
