### ISSUE TITLE
Canu "Unable to assemble uncorrected reads"

### ISSUE THREAD

**Issue by dcopetti** [marbl/canu#1762]
Hello,

I am running Canu as
`sudo /home/stlinus/bin/canu/Linux-amd64/bin/canu -assemble useGrid=false corOutCoverage=200 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" maxMemory=100 maxThreads=15 -p canu_150x_ass -d canu_150x_assembly genomeSize=500m -nanopore ONT_reads_in_150xregions.fq.gz &>canu_150x_log`
(notice: I am running it from the installation of a colleague - I am lazy I know)
and soon after I get this error:
```
[...]
-- Finished on Wed Jul 15 13:09:42 2020 (2504 seconds) with 8368.681 GB free disk space
----------------------------------------
-- Unable to assemble uncorrected reads.

ABORT:
ABORT: Canu snapshot v2.0-development +369 changes (r9862 6cfdadd772614d22446e9c113b8405b489dfe3e5)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   unable to assemble uncorrected reads.
ABORT:
```
restarting with the same command will give me the same error instantaneously.
the output folder has:
```
$ tree .
.
├── canu_150x_ass.seqStore
│   ├── blobs.0001
│   ├── blobs.0002
│   ├── blobs.0003
│   ├── blobs.0004
│   ├── blobs.0005
│   ├── blobs.0006
│   ├── blobs.0007
│   ├── errorLog
│   ├── info
│   ├── info.txt
│   ├── libraries
│   ├── libraries.txt
│   ├── readNames.txt
│   ├── reads
│   ├── reads-corc
│   ├── reads-coru
│   ├── reads-rawc
│   ├── reads-rawu
│   └── version.001
│       ├── info
│       ├── info.txt
│       ├── libraries
│       ├── reads
│       ├── reads-corc
│       ├── reads-coru
│       ├── reads-rawc
│       └── reads-rawu
├── canu_150x_ass.seqStore.err
├── canu_150x_ass.seqStore.sh
├── canu-logs
│   ├── 1594808878_kp141-242_8463_canu
│   ├── 1594808879_kp141-242_8587_sqStoreCreate
│   ├── 1594811382_kp141-242_8888_sqStoreDumpMetaData
│   └── 1594812897_kp141-242_9124_canu
├── canu-scripts
└── unitigging
```
the .sh and .err files don't have anything (that I think is) informative. 
Any idea on why it is crashing? I have 120 GB RAM and 16 CPUs on a single machine.
thanks,
Dario

**Comment by skoren** [comment]
You've specified both ```-assemble``` and Nanopore reads which are assumed to be raw. Those require correction to assemble so you would either need to tell Canu to treat these reads as corrected (```-corrected```) or remove the ```-assemble``` option to let canu run correction/assembly/trimming. I'd also suggest using the 2.0 release rather than the master like you are now, that's likely to be unstable.

I've had some luck assembling Nanopore reads without correction from the recent base caller (3.6.0) by specifying them as hifi data:
```
'batOptions=-eg 0.12 -sb 0.01 -dg 3 -db 3 -dr 1 -ca 500 -cp 50' 'correctedErrorRate=0.12' 'maxInputCoverage=100' -pacbio-hifi ONT_reads_in_150xregions.fq.gz
```

**Comment by dcopetti** [comment]
OK, thanks for the clarification - I assumed that assemble was to run the whole pipeline, not just the last part.
I restarted the assembly without `-assemble` and it is not complaining now.

Good to know about the settings for the data called with 3.6 - I will get them soon.
