### ISSUE TITLE
run canu on HPC

### ISSUE THREAD

**Issue by UronicAcid** [marbl/canu#1765]
I am running canu 2.0 with ``canu -p G6 -d G6 genomeSize=18m -nanopore-raw <nanopore.fastq.gz>`` on HPC(High Performance Computing), which is centos6. 
However, it seems that canu needs to submit jobs automatically though I have no access permission.

Here are the errors:
```
CRASH:
CRASH: Canu 2.0
CRASH: Please panic, this is abnormal.
CRASH:
CRASH:   Failed to submit compute jobs.
CRASH:
CRASH: Failed at /public/home/tangwei1/miniconda3/envs/assemble/bin/../lib/site_perl/canu/Execution.pm line 1275.
CRASH: 	canu::Execution::submitOrRunParallelJob("G6", "meryl", "correction/0-mercounts", "meryl-count", 1, 2) called at /public/home/tangwei1/miniconda3/envs/assemble/bin/../lib/site_perl/canu/Meryl.pm line 834
CRASH: 	canu::Meryl::merylCountCheck("G6", "cor") called at /public/home/tangwei1/miniconda3/envs/assemble/bin/canu line 989
CRASH: 
CRASH: Last 50 lines of the relevant log file (correction/0-mercounts/meryl-count.jobSubmit-01.out):
CRASH:
CRASH: qsub: submit error (Bad UID for job execution MSG=ruserok failed validating tangwei1/tangwei1 from node50)
CRASH:
```

Thanks!

**Comment by skoren** [comment]
It sounds like your compute nodes aren't allowed to submit jobs, this is a requirement to run Canu (see: https://canu.readthedocs.io/en/latest/faq.html#my-run-stopped-with-the-error-failed-to-submit-batch-jobs). If you cannot make your compute nodes submit nodes as well, you'll have to run the jobs by hand (using correction/0-mercounts/meryl-count.jobSubmit-01.sh, wait for them to finish, re-start canu, and repeat on all the steps).

**Comment by UronicAcid** [comment]
``useGrid=false`` works. Thanks!
