### ISSUE TITLE
PacBio CLR subreads question

### ISSUE THREAD

**Issue by cjfields** [marbl/canu#1768]
I have a more general question regarding sequence data from PacBio Sequel BAM files converted to FASTQ, and whether it's the best input for assembly.  This is related somewhat to #644, which does briefly mention the issue below but it isn't addressed directly.

A little explanation: we are using the PacBio `bam2fastq` tool (SMRTLink 8.0) as follows to generate FASTQ for later assembly:

```
bam2fastq -o $SAMPLE $XML
```

Where the `$XML` is the XML file generated from the run.  The PacBio BAM file and index file are in the same directory. 

With one CLR library from a PacBio SequelII SMRT cell, the PacBio SMRTLink report indicates there are 8,038,637 'reports' (subreads) in the BAM file, with 6,288,262 polymerase reads which should correspond (unless I am mistaken) to unique molecules; here it's obvious there are more subreads than polymerase reads, so a reasonable number of subreads are duplicate reads from the same molecules.  

However, the FASTQ data generated above yields 8,038,637 sequences, which are **all** of the subreads, including duplicated runs across molecules (probably with a bias towards shorter inserts having more subreads, though I haven't confirmed this yet).  

**My question:** would it be best to generate a single 'best/first/longest/shortest' subread per polymerase read for assembly?  Or does it make a difference?  I know that Canu selects the longest reads by default, which might partly alleviate this issue for Canu, but I wasn't sure whether this has been tested before.  

I can see it being more of a concern with other assemblers (wtdbg2, etc) where there may not be a pre-selection step available.

**EDIT**: Should also re-emphasize this is for CLR, HiFi isn't an issue.

**Comment by skoren** [comment]
We haven't tested this extensively. Typically we keep all the reads and let Canu pick the reads with good support. This can pick two reads from the same ZMW. I don't think it would hurt the assembly to to keep only the best read per ZMW though. If you test both, you can let us know how the assemblies turned out.

**Comment by cjfields** [comment]
Thx @skoren for the quick reply!  This question came up when prepping reads for test runs. We initially ran assemblies using wtdbg2 which we thought required some read prepping prior to assembly (size filtering and preference for longer reads), but we found that it does have a `-L` option set by default to both filter reads less than 5000bp *and* (if PacBio) pick the longest subread.  We may be testing Canu soon and can let you know if this does make a difference, though my expectation is removal of shorter reads likely mitigates the issue.
