### ISSUE TITLE
about  canu 

### ISSUE THREAD

**Issue by snow111222333333** [marbl/canu#1771]
I am using canu to correct the error before assembly, and the output canu.out: 
```
ERROR: mhap overlapper requires java version at least 1.8.0; you have unknown (from'/usr/bin/java').
ERROR:'/usr/bin/java -Xmx1g -showversion' reports:
```

**Comment by skoren** [comment]
As the error indicates, your JVM isn't functioning properly and not reporting a version (assuming you posted the full log of the error). If you're running on a cluster, it's likely the JVM on the compute node doesn't match what you have on the login node. If you have a working JVM you want to use, pass it using the ```java=<full path to java>``` parameter to Canu.

**Comment by snow111222333333** [comment]
I used an absolute path, but canu.out reported an error ：
ERROR:  mhap overlapper requires java version at least 1.8.0; you have unknown (from '/datalus/chenx/software/jdk1.8.0_191/bin/java').
ERROR:  '/datalus/chenx/software/jdk1.8.0_191/bin/java -Xmx1g -showversion' reports:
ERROR:    'Error occurred during initialization of VM'
ERROR:    'java.lang.OutOfMemoryError: unable to create new native thread'

**Comment by skoren** [comment]
That still looks like a JVM or a grid issue (assuming you're running on grid). The JVM can't start up and create a 1gb instance (which is pretty small). That usually means the machine you're running on isn't reserving memory for jobs. Canu requests at least 4gb of memory by default. 

What's the grid you're running on (if any)? What is the canu submission command (should be in the ```canu-scripts/canu.*.out``` files).

**Comment by snow111222333333** [comment]
thank you very much , I set useGrid=0, and it run successful

**Comment by skoren** [comment]
If you do want to run on the grid, you can work with your IT group to find the right way to request memory to the system and then use gridEngineResourceOption to pass it to canu.
