### ISSUE TITLE
Overlap store sorting jobs failed, tried 2 times, giving up.

### ISSUE THREAD

**Issue by phrh** [marbl/canu#1772]
Hello,
I am a new canu user. I was just trying to follow the canu quick start. I downloaded canu two days ago. 

However, I get the following error with the example data

canu -p ecoli -d ecoli-mix genomeSize=4.8m -pacbio-raw pacbio.part1.fastq -nanopore-raw oxford.fasta

looking forward to an answer. 

```
-- Finished on Wed Aug  5 07:47:19 2020 (lickety-split) with 1659.515 GB free disk space
----------------------------------------
--
-- Overlap store sorting jobs failed, tried 2 times, giving up.
--   job correction/ecoli.ovlStore.BUILDING/0001 FAILED.
--   job correction/ecoli.ovlStore.BUILDING/0002 FAILED.
--

ABORT:
ABORT: Canu 2.0
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```

**Comment by skoren** [comment]
Are you running on the grid or on a local node? Post the logs from the failing jobs (they should be in ```correction/ecoli.ovlStore.BUILDING/logs/*.out```).

**Comment by phrh** [comment]
I am running in a local node.

Here are the log files

(1) *1-bucketize.000001.out*
Found canu:

 /media/paula/DATA/paula/Corpoica/Nanopore/Ubuntu/canu-2.0.Linux-amd64/canu-2.0/Linux-amd64/bin/canu
   Canu 2.0

Running job 1 based on command line options.

Attempting to increase maximum allowed processes and open files.
./scripts/1-bucketize.sh: 1: ulimit: Illegal option -u
./scripts/1-bucketize.sh: 1: ulimit: Illegal option -u
./scripts/1-bucketize.sh: 72: ulimit: Illegal option -u
./scripts/1-bucketize.sh: 1: ulimit: Illegal option -u
  Changed max processes per user from  to  (max ).
  Changed max open files from 1024 to 1048576 (max 1048576).

sqStore_loadMetadata()-- Using 'raw' 0x01 reads.

Opened '../ecoli.seqStore' with 6050 reads.

Constructing slice 1 for store './ecoli.ovlStore.BUILDING'.
 - Filtering overlaps over 1.0000 fraction error.

Bucketizing input    1 out of    1 - '1-overlapper/results/000001.ovb'
Success!

(2) *less 2-sort.000001.out*


Found perl:
   /usr/bin/perl
   This is perl 5, version 30, subversion 0 (v5.30.0) built for
x86_64-linux-gnu-thread-multi

Found java:
   /usr/bin/java
   openjdk version "1.8.0_252"

Found canu:

 /media/paula/DATA/paula/Corpoica/Nanopore/Ubuntu/canu-2.0.Linux-amd64/canu-2.0/Linux-amd64/bin/canu
   Canu 2.0

Running job 1 based on command line options.

Attempting to increase maximum allowed processes and open files.
./scripts/2-sort.sh: 1: ulimit: Illegal option -u
./scripts/2-sort.sh: 1: ulimit: Illegal option -u
./scripts/2-sort.sh: 72: ulimit: Illegal option -u
./scripts/2-sort.sh: 1: ulimit: Illegal option -u
  Changed max processes per user from  to  (max ).
  Changed max open files from 1024 to 1048576 (max 1048576).

sqStore_loadMetadata()-- Using 'raw' 0x01 reads.

Finding overlaps.
  found     112542 overlaps in
'./ecoli.ovlStore.BUILDING/bucket0001/sliceSizes'.

Loading     112542 overlaps using 0.00 GB of allowed (-M) 1 GB memory.
  loading     112542 overlaps from
'./ecoli.ovlStore.BUILDING/bucket0001/slice0001'.

Sorting.

Writing sorted overlaps.
Failed to open './ecoli.ovlStore.BUILDING/0001<001>' for writing: Invalid
argument

(3) *less 2-sort.000002.out*
Found perl:
   /usr/bin/perl
   This is perl 5, version 30, subversion 0 (v5.30.0) built for
x86_64-linux-gnu-thread-multi

Found java:
   /usr/bin/java
   openjdk version "1.8.0_252"

Found canu:

 /media/paula/DATA/paula/Corpoica/Nanopore/Ubuntu/canu-2.0.Linux-amd64/canu-2.0/Linux-amd64/bin/canu
   Canu 2.0

Running job 2 based on command line options.

Attempting to increase maximum allowed processes and open files.
./scripts/2-sort.sh: 1: ulimit: Illegal option -u
./scripts/2-sort.sh: 1: ulimit: Illegal option -u
./scripts/2-sort.sh: 72: ulimit: Illegal option -u
./scripts/2-sort.sh: 1: ulimit: Illegal option -u
  Changed max processes per user from  to  (max ).
  Changed max open files from 1024 to 1048576 (max 1048576).

sqStore_loadMetadata()-- Using 'raw' 0x01 reads.

Finding overlaps.
  found       3002 overlaps in
'./ecoli.ovlStore.BUILDING/bucket0001/sliceSizes'.

Loading       3002 overlaps using 0.00 GB of allowed (-M) 1 GB memory.
  loading       3002 overlaps from
'./ecoli.ovlStore.BUILDING/bucket0001/slice0002'.

Sorting.

Writing sorted overlaps.
Failed to open './ecoli.ovlStore.BUILDING/0002<001>' for writing: Invalid
argument

**Comment by skoren** [comment]
It looks like your file system doesn't support the names Canu is trying to use for the files. There is a build option to avoid these path names but unfortunately that had a bug in it in the last release (see issue #1732 ). Your best option would be to try the latest code from tip which is close to the next release. You can check it out directly from GitHub and build locally.

**Comment by phrh** [comment]
Thank you very much. It was the file system. I have a shared partition for
Ubuntu and Mac. Once I installed canu outside the partition It worked fine.
Thanks again for your help

**Comment by hafizmtalha** [comment]
Hi, I am facing the same issues. but my log looks a bit different.

all logs of bucketsize.out saying success. pasting one of it

Found perl:
   /usr/bin/perl
   This is perl 5, version 30, subversion 0 (v5.30.0) built for x86_64-linux-gnu-thread-multi

Found java:
   /usr/bin/java
   openjdk version "13.0.7" 2021-04-20

Found canu:
   /media/navi/ssd/magnaporthe-KI215/genome-assembly/canu/build/bin/canu
   canu snapshot v2.3-development +88 changes (r10359 4b563b58ee6c0053e035ba0360ecc82cb7c4499a)

Running job 19 based on command line options.

Attempting to increase maximum allowed processes and open files.
./scripts/1-bucketize.sh: 1: ulimit: Illegal option -u
./scripts/1-bucketize.sh: 1: ulimit: Illegal option -u
./scripts/1-bucketize.sh: 69: ulimit: Illegal option -u
./scripts/1-bucketize.sh: 1: ulimit: Illegal option -u
  Changed max processes per user from  to  (max ).
  Changed max open files from 1024 to 1048576 (max 1048576).


Opened '../oryza.seqStore' with 702090 reads.

Constructing slice 19 for store './oryza.ovlStore.BUILDING'.
 - Filtering overlaps over 1.0000 fraction error.

Bucketizing input    1 out of    2 - '1-overlapper/results/000019.ovb'
Bucketizing input    2 out of    2 - '1-overlapper/results/000034.ovb'
Success!

logs od sort files shows the following error..
2-sort.000002.out 


Found perl:
   /usr/bin/perl
   This is perl 5, version 30, subversion 0 (v5.30.0) built for x86_64-linux-gnu-thread-multi

Found java:
   /usr/bin/java
   openjdk version "13.0.7" 2021-04-20

Found canu:
   /media/navi/ssd/magnaporthe-KI215/genome-assembly/canu/build/bin/canu
   canu snapshot v2.3-development +88 changes (r10359 4b563b58ee6c0053e035ba0360ecc82cb7c4499a)

Running job 2 based on command line options.

Attempting to increase maximum allowed processes and open files.
./scripts/2-sort.sh: 1: ulimit: Illegal option -u
./scripts/2-sort.sh: 1: ulimit: Illegal option -u
./scripts/2-sort.sh: 69: ulimit: Illegal option -u
./scripts/2-sort.sh: 1: ulimit: Illegal option -u
  Changed max processes per user from  to  (max ).
  Changed max open files from 1024 to 1048576 (max 1048576).


Finding overlaps.
  found   17492867 overlaps in './oryza.ovlStore.BUILDING/bucket0001/sliceSizes'.
  found     711225 overlaps in './oryza.ovlStore.BUILDING/bucket0002/sliceSizes'.
  found     703683 overlaps in './oryza.ovlStore.BUILDING/bucket0003/sliceSizes'.
  found     564135 overlaps in './oryza.ovlStore.BUILDING/bucket0004/sliceSizes'.
  found   99291393 overlaps in './oryza.ovlStore.BUILDING/bucket0005/sliceSizes'.
  found   82392831 overlaps in './oryza.ovlStore.BUILDING/bucket0006/sliceSizes'.
  found   82065883 overlaps in './oryza.ovlStore.BUILDING/bucket0007/sliceSizes'.
  found   48844937 overlaps in './oryza.ovlStore.BUILDING/bucket0008/sliceSizes'.

Loading  332066954 overlaps using 7.42 GB of allowed (-M) 9 GB memory.
  loading   17492867 overlaps from './oryza.ovlStore.BUILDING/bucket0001/slice0002'.
Killed
looking forward for some help

**Comment by skoren** [comment]
This looks the same as previous issues where the memory was under-requested. Add ovsMemory=32 or 64 and re-try. It should resume from where you left off.
