### ISSUE TITLE
weird gfa graph and smaller assembly

### ISSUE THREAD

**Issue by dabitz** [marbl/canu#1773]
Hi Sergey,

I am trying to assemble a homozygous plant genome (2.4gb) with 30x HiFi reads, which seems to have experienced a recent accumulation of large segmental duplications and I got the following strange graph for the unitig.gfa file, also the assembly size (2.07gb unitgs and 1.83gb contigs) does not match well the expected genome size.

![Rpubera12Hicanu unitigs](https://user-images.githubusercontent.com/25509795/89646138-7b757280-d8bb-11ea-9362-46085bf979f3.png)

here are the infos
canu -version 2.0
Linux
command: bsub -q ioheavy -n 40 -R "rusage[mem=180000] span[hosts=1]" -M 200000 canu -assemble -p Rp12Hicanu -d Rp12Hicanu genomeSize=2.4g maxThreads=40 useGrid=false -pacbio-hifi Rp12CCS.fastq

assembly metrics:
Contigs:
sum = 1835491805, n = 14482, ave = 126742.98, largest = 58954314
N50 = 3064599, n = 99
N60 = 1964189, n = 175
N70 = 1022688, n = 306
N80 = 99603, n = 752
N90 = 26920, n = 6042
N100 = 1869, n = 14482
N_count = 0
Gaps = 0

Unitigs:
sum = 2070363298, n = 31551, ave = 65619.58, largest = 3149448
N50 = 204986, n = 2102
N60 = 115748, n = 3448
N70 = 55605, n = 6059
N80 = 30308, n = 11414
N90 = 21979, n = 19441
N100 = 1243, n = 31551
N_count = 0
Gaps = 0

Thanks for your support!
André

**Comment by skoren** [comment]
We're planning to deprecate the unitig Agfa in future release as it can not include all edges we want to see and over-fragment the graph. However, I am not sure your graph is particularly weird, it looks there are some common repeats connecting the full genome. This is quite common to see for CLR data, less common for HiFi data. 

As for genome size, it's possible your 2.4 estimate is an over-estimate of the genome size. It's also possible that some repeats are collapsed since they are identical and so take up less bases than they should. Have you checked the assembly for gene completeness? You can also see issue #1755 for some ways to compute the estimated size of the collapsed repetitive contigs.

**Comment by dabitz** [comment]
The assembly looks complete 94.5% with Busco. It is weird though that even unitig file shows two peaks for coverage: 

![Rp12Hicanu unitigs coverage_covplot](https://user-images.githubusercontent.com/25509795/89773029-6be86a80-db03-11ea-86c4-1b8872d58ccb.png)
 also seen from the contig file:

![Rp12Hicanu contigs coverage_covplot](https://user-images.githubusercontent.com/25509795/89773065-802c6780-db03-11ea-96ad-f4a2102daf41.png)

You are right that there is a specific class of repeat that is present regularly across the genome, which could contribute to the smaller assembly size. We will do flow cytometry to be sure about genome size. But the two peak coverage distribution also for the unitig file is strange. We think that this plant is accumulating duplications. If such duplications are very recent perhaps we do not have much SNPs to differentiate them, right? Would it be possible to increase even more assembly stringency for this particular case?
It is worth mentioning that HiCanu managed to assemble another individual from another population fine. In this case an assembly size matching the expected haploid genome was achieved with uniform coverage distribution.

**Comment by skoren** [comment]
Typically HiFi assembly runs at 0% error rate already (well after compressing homopolymers correcting whatever errors we can) so I doubt you'd be able to be more stringent. You can check the actual thresholds used in `unitigging/4-unitigger/*001.filterOverlaps.thr000.num000.log`.

That looks almost like a diploid genome, with the haploid peak at 35x and a second peak at 70x. Have you run genomescope on the HiFi k-mers? It'd be interesting what it reports for genome size/etc. Perhaps the genome is not as homozygous as you'd expect or perhaps there was a recent genome duplication so part of the genome can't be separated, even at HiFi stringency. From the plots, about 30% of the assembly is in the elevated coverage peak, so if all those contigs were present twice in the assembly, you'd get very close to your expected 2.4gb size. So I think these collapsed regions at higher coverage explain the assembly size difference from your estimate as I suspected.

**Comment by dabitz** [comment]
Yes, indeed threshold looks like very stringent 0.001% 
ERROR RATES
-----------

                                            --------threshold-------
5981559                  fraction error     fraction         percent
samples                          (1e-5)        error           error
                 ----------------------       ------        --------
command line                             ->    30.00         0.0300%
mean + std.dev     1.25 +-   0 *   4.70  ->     1.25         0.0012%
median + mad       0.00 +-   0 *   0.00  ->     0.00         0.0000%
90th percentile                          ->     1.00         0.0010%  (enabled)


BEST EDGE FILTERING
-------------------

Reads with both best edges below threshold:    731934
Reads with one  best edge  above threshold:    117407
Reads with both best edges above threshold:     44712


INITIAL EDGES
-------- ----------------------------------------
 4046262 reads are contained
  205308 reads have no best edges (singleton)
  151173 reads have only one best edge (spur) 
            38204 are mutual best
  967015 reads have two best edges 
            79416 have one mutual best edge
           768022 have two mutual best edges


EDGE FILTERING
-------- ------------------------------------------
       0 reads are ignored
  140221 reads have a gap in overlap coverage
  177081 reads have lopsided best edges

FINAL EDGES
-------- ----------------------------------------
 4037288 reads are contained
  472414 reads have no best edges (singleton)
   37724 reads have only one best edge (spur) 
            28428 are mutual best
  822332 reads have two best edges 
            42592 have one mutual best edge
           768854 have two mutual best edges
We have also checked the genome size based on kmer counts from Illumina data with both genomescope and findGSE. Genomescope failed to determine a reasonable genome size (320Mb), while findGSE reported either 1.2 for a heterozygous or 2.4 for a homozygous genome. The funny thing is that despite the two peaks, we observed several additional peaks, representing most likely duplicated regions in the genome. Although HiCanu was able to assemble these duplications fine in the standard genotype, it seems to not resolve the additional duplications found in this individual from another population that seems to actively accumulate more duplications. It might be some very recent process...
FindGSE kmer plot
[Rp_genome_size_est_if74x_case2.pdf](https://github.com/marbl/canu/files/5052834/Rp_genome_size_est_if74x_case2.pdf)

Although this is the coverage plot for the 1.3gb collapsed assembly:

![Coverage_igv_snapshot_contigs2](https://user-images.githubusercontent.com/25509795/89819809-4af83780-db4c-11ea-87c2-7f47749b2cd6.png)

**Comment by skoren** [comment]
It seems like this genome has more recent duplication, perhaps too similar even for the HiFi accuracy of reads. You can collect the reads in the collapsed tig and investigate how many SNPs/variants there are and perhaps try to manually bin them by some additional information (HiC/ONT/etc) but I expect that will not work either. 

I don't think there is anything you can do in the settings to resolve these regions, as you said, they resolve OK with defaults in another dataset so I'm going to close the issue.
