### ISSUE TITLE
Trying to understand batOptions for metagenome assembly

### ISSUE THREAD

**Issue by VManning** [marbl/canu#1777]
Hello, and before I go any further, Thank you for the help!

I am performing a metagenome assembly (should be primarily prokaryotes) from HiFi reads using Canu V2. I came across an earlier topic that recommended changing batOptions.

('batOptions=-eg 0.0 -sb 0.001 -dg 0 -db 3 -dr 0 -ca 2000 -cp 200')

Can you explain what this does?

Best, V

**Comment by skoren** [comment]
The parameters force Canu to use a low error rate (to avoid merging similar strains) and increase bubble stringency and default repeat splitting. You should keep using those parameters for the 2.0 release. If you use the tip (which is close to the next release) the default parameters should be sufficient for metagenomes too.

**Comment by VManning** [comment]
Hi,

I ran, with and without the batOptions:

SGE_Batch -c “~/scripts/canu-2.0/*/bin/canu -p Bioreactor -d Bioreactor_hifi2 genomeSize=0.2m useGrid=FALSE 'batOptions=-eg 0.0 -sb 0.001 -dg 0 -db 3 -dr 0 -ca 2000 -cp 200' -pacbio-hifi Bioreactor.ccs.fa.gz” -P 8 -m 16G -r Bioreactor_canu 

**With batOptions from <>.report**
[UNITIGGING/READS]
--
-- In sequence store './Bioreactor.seqStore':
--   Found 1332 reads.
--   Found 10005386 bases (50.02 times coverage).

**Without batOptions from <>.report**
[UNITIGGING/READS]
--
-- In sequence store './Bioreactor.seqStore':
--   Found 1314647 reads.
--   Found 10000002126 bases (50 times coverage).


Yikes! Lost lots of data early in the process. Too stringent?

**Comment by skoren** [comment]
The bat options wouldn't change the reads kept, by default HiCanu only keeps a random 50x subset of the data. You can do that by setting ```maxInputCoverage=900```. Given the difference in I think you set the genome size differently between the two runs (the second command has the genome size as 0.2m, I assume it should be 0.2g).

**Comment by VManning** [comment]
You are so right! Ugh! 

Thanks for the recommendation on the maxInputCoverage. Will try to run it right next time!
