### ISSUE TITLE
Canu corrected reads using similar label as raw reads

### ISSUE THREAD

**Issue by dikshyantg** [marbl/canu#1778]
I used canu  assembler on my Nanopore reads and after blasting those raw reads with one of the contigs I found that the reads doesn't cover the starting region of the contigs from 1-3000 bp . I looked at the tig.info and readnames .txt file to see whether reads were used to map that region and found a read that has been used by the assembler to make that region of the contig. My surprise was that particular read named 2255448d-b1ef-4a82-ab25-2ae522773881 is in corrected reads but not in the original raw reads of Nanopore. Looking at the runid in the label of that read from canu corrected reads shows me that it is the same run id of the Nanopore run  which is runid=ca57a8f71dd30a4834dc41652f07e38ae391df1b but I can't get hold of the read id in the nanopore read. Is it possible that while correcting the reads canu might have made a new read with similar name to the parent reads from raw nanopore data ?

**Comment by skoren** [comment]
It's not possible to get a new read name from correction, if the read name is in the readNames.txt file then it was in the original input data. New names are never created by Canu.

**Comment by skoren** [comment]
Any update, did you check the readNames.txt file for the read in question?

**Comment by dikshyantg** [comment]
I did and it was error on my end. The tool I used to make fasta file out of
fastq.gz file didn’t gave me all the reads.
Thanks!
Dikshyant
