### ISSUE TITLE
./unitigging/3-overlapErrorAdjustment/0001.oea FAILED

### ISSUE THREAD

**Issue by yanz711** [marbl/canu#178]
Dear Canu,

After very long running, the Canu stop with the message:

-- 39 overlap error adjustment jobs failed:

canu failed with 'failed to adjust overlap error rates.  Made 2 attempts, jobs still failed'.

Anyone has a suggestion?

**Comment by skoren** [comment]
Are you running the latest (1.3) release? What is the output of one of the failed jobs, it should be in unitigging/3-*/oea.*.out.

**Comment by yanz711** [comment]
I rerun it, and finished successfully. Thank you.

**Comment by skoren** [comment]
If you're able to post one of the original error logs it would still be useful to see why it failed the first time.
