### ISSUE TITLE
Failed to unstash the contained reads. Still have 9 reads unplaced.

### ISSUE THREAD

**Issue by tbenavi1** [marbl/canu#1780]
I used canu with the --pacbio-hifi command and I am on Linux on a grid (but using useGrid=false).

The output of 'canu -version' is canu snapshot v2.2-development +11 changes (r10120 6d274143e05952e1543169071436f6ad2c59b72e).

The issue I get is that the consensus step fails, here is the output:

 ```BEGIN ASSEMBLY
-- Using slow alignment for consensus (iteration '0').
-- Configured 13 consensus jobs.
--
--                                (tag)Concurrency
--                         (tag)Threads          |
--                (tag)Memory         |          |
--        (tag)             |         |          |       total usage      algorithm
--        -------  ----------  --------   --------  --------------------  -----------------------------
-- Local: cns        0.500 GB    4 CPUs x   3 jobs     1.500 GB  12 CPUs  (consensus)
--
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'cns' concurrent execution on Thu Aug 27 16:17:20 2020 with 369.951 GB free disk space (2 processes; 3 concurrently) 
 
    cd unitigging/5-consensus
    ./consensus.sh 3 > ./consensus.000003.out 2>&1
    ./consensus.sh 5 > ./consensus.000005.out 2>&1 
 
-- Finished on Thu Aug 27 16:17:23 2020 (3 seconds) with 369.949 GB free disk space
----------------------------------------
-- Using slow alignment for consensus (iteration '1').
-- Configured 13 consensus jobs.
--
-- Consensus jobs failed, retry.
--   job ctgcns/0005.cns FAILED.
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'cns' concurrent execution on Thu Aug 27 16:17:23 2020 with 369.949 GB free disk space (1 processes; 3 concurrently) 
 
    cd unitigging/5-consensus
    ./consensus.sh 5 > ./consensus.000005.out 2>&1 
 
-- Finished on Thu Aug 27 16:17:26 2020 (3 seconds) with 369.949 GB free disk space
----------------------------------------
-- Using slow alignment for consensus (iteration '2').
-- Configured 13 consensus jobs.
--
-- Consensus jobs failed, tried 2 times, giving up.
--   job ctgcns/0005.cns FAILED.
-- 
```

The contents of consensus.000005.out are:

```
Found perl:
   /usr/bin/perl
   This is perl 5, version 26, subversion 3 (v5.26.3) built for x86_64-linux-thread-multi 
 
Found java:
   /grid/it/data/elzar/easybuild/software/Java/11.0.2/bin/java
   openjdk version "11.0.2" 2019-01-15 
 
Found canu:
   /grid/schatz/home/ranallo/software/canu/build/bin/canu
   canu snapshot v2.2-development +11 changes (r10120 6d274143e05952e1543169071436f6ad2c59b72e) 
 
Running job 5 based on command line options.
-- Using seqFile '../het0.3_err0.5.ctgStore/partition.0005'.
-- Opening tigStore '../het0.3_err0.5.ctgStore' version 1.
-- Opening output results file './ctgcns/0005.cns.WORKING'.
--
-- Computing consensus for b=0 to e=4533 with errorRate 0.0500 (max 0.4000) and minimum overlap 500
--
Loading corrected-trimmed reads from seqFile '../het0.3_err0.5.ctgStore/partition.0005'
Failed to unstash the contained reads.  Still have 9 reads unplaced.
utgcns: utgcns/stashContains.C:206: void tgTig::unstashContains(): Assertion `idmap.empty() == true' failed. 
 
Failed with 'Aborted'; backtrace (libbacktrace):
utility/src/utility/system-stackTrace.C::83 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
utgcns/stashContains.C::206 in _ZN5tgTig15unstashContainsEv()
utgcns/utgcns.C::623 in _Z11processTigsR13cnsParameters()
utgcns/utgcns.C::990 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
./consensus.sh: line 89: 1591913 Aborted                 (core dumped) $bin/utgcns -R ../het0.3_err0.5.ctgStore/partition.$jobid -T ../het0.3_err0.5.ctgStore 1 -P $jobid -O ./ctgcns/$jobid.cns.WORKING -maxcoverage 40 -e 0.05 -pbdagcon -edlib -threads 4
```

I see that the error is "Failed to unstash the contained reads.  Still have 9 reads unplaced." Any ideas? I am using reads that I simulated so perhaps they are malformed somehow? (Though this seems to be a rare issue on data I've generated). Thanks.

**Comment by brianwalenz** [comment]
The easy fix:

Set canu option cnsMaxCoverage=0, remove 5-consensus/consensus.sh and restart.  By default, we're only using 40x of the data for consensus.  Setting the max to zero will use all the data, bypassing the stash/unstash steps.

The longer fix:

I'd like to get the data so I can properly debug.  Unfortunately, the logging isn't telling us which contig is failing and a bit of work is needed on your part to figure this out.  I'll use a generic `asm` for the assembly name `het0.3_err0.5`.

Scan file unitigging/asm.ctgStore/partitioning to find the first tig in partition 5.  The file will look like:
```
      Tig     Reads    Length         Area  Memory GB  Partition    Data GB
--------- --------- --------- ------------  ---------  ---------  ---------
        1     17173   4646877  79800818721      4.432          1      0.095
        2         1      7660         7660      0.007          2      0.000
        3         1     18336        18336      0.017          2      0.000
        4         1      9995         9995      0.010          2      0.000
```
When you find that tig ID, run a test consensus to make sure it's the one that is failing:
```
utgcns -V -V \
  -R ../asm.ctgStore/partition.0005 \
  -T ../asm.ctgStore 1 \
  -P 5 \
  -O test.cns \
  -maxcoverage 40 \
  -e 0.2 \
  -tig <TIG_ID>
```
A couple of comments:
1) If you now remove the -maxcoverage option, it should work.
2) This looks to be failing quite quickly.  You could also run the above command without the -tig option.  The tig it crashes on should be logged to the screen.
3) If too much debug info is reported, remove one of the -V options.

Now that we know the bad tig, just 'export' the data and post here or email to me:
```
utgcns \
  -R ../asm.ctgStore/partition.0005 \
  -T ../asm.ctgStore 1 \
  -P 5 \
  -tig <TIG_ID> \
  -export bad_tig.tig
```
WARNING!  This file will contain all the sequence data for this tig.

**Comment by tbenavi1** [comment]
I am wondering if the problem is the number of threads that Canu is requesting. When I used the cnsMaxCoverage=0 option you suggested (and after deleting consensus.sh and restarting), I still received the same error. However, whenever I used the cnsConcurrency=1 option, Canu was able to successfully run cns.

I am running this on a cluster where I allocate a certain number of threads and a certain amount of memory per thread. If I only allocate X threads, is it sufficient to set maxThreads=X for Canu? Or do I also need to set the Concurrency to 1? Perhaps there is something else I am missing, but let me know your thoughts and I will continue to investigate as you said.

**Comment by skoren** [comment]
The concurrency should not have changed how many threads are being used. You only have one failed job and all corConcurrency would do would say to run at most one job at a time but that's all you have left. The job should have still used the same number of threads (which you can check from the consensus.sh script). I don't see that maxCoverage=0 would have not stashed anything, I think you need to set it very high like maxCoverage=200 to turn off stashing (again the log would have info). 

That said, it is still strange it ran the next time since nothing should have changed. So it would still be good to find the failing tig and share the data per @brianwalenz suggestions and share it so we can try to reproduce locally.

**Comment by tbenavi1** [comment]
I went through all the tig IDs for the failing partition, as Brian mentioned, and ran the utgcns command he suggested. The command succeeded for every tig, and output
```
Processed 1 tig and 0 singletons.

Consensus finished successfully.

Bye.
```

for every tig. I also edited the utgcns command to match what was in my consensus.sh file (e.g. -e 0.05, -pbdagcon, -edlib, and -threads 4). Again, running the command individually for every tig in the failing partition, it still succeeded every time. Adding cnsMaxCoverage=200 and even cnsMaxCoverage=500 still resulted in the failed to unstash reads error. 

However, whenever I change "-threads 4" to "-threads 1" in my consensus.sh file and restart Canu, the assembly succeeds. I'm not sure why this would cause only a certain partition to fail (since -threads 4 is being run in all cases). I assume that my computing grid is cancelling Canu? Any further ideas? Sorry for the trouble. At least I can help my assemblies succeed by changing the -threads option for consensus.sh.

**Comment by tbenavi1** [comment]
Ok, I'm not sure what's happening yet, but I was able to find an example of a bad tig with a different dataset. Here is the output of the utgcns command:

```
-- Using seqFile '../het0.2_err0.5.ctgStore/partition.0044'.
-- Opening tigStore '../het0.2_err0.5.ctgStore' version 1.
-- Opening output results file 'test.cns'.
--
-- Computing consensus for b=1137 to e=1137 with errorRate 0.2000 (max 0.4000) and minimum overlap 500
--
                           ----------CONTAINED READS----------  -DOVETAIL  READS-
  tigID    length   reads      used coverage  ignored coverage      used coverage
------- --------- -------  -------- -------- -------- --------  -------- --------
Loading corrected-trimmed reads from seqFile '../het0.2_err0.5.ctgStore/partition.0044'
switchToUncompressedCoordinates()-- I'm trying to find start of child 1186 compressed 0 (dist from guide read is 0 and in uncompressed in becomes 0)
switchToUncompressedCoordinates() --Updated read 1186 which has length 4178 to be from 0 - 4178
switchToUncompressedCoordinates()-- Updating guide read to be 1186 which ends at 3171. Best before ended at 3171. Now my guide is at 0 (0 uncompressed)
Failed to unstash the contained reads.  Still have 1 reads unplaced.
utgcns: utgcns/stashContains.C:206: void tgTig::unstashContains(): Assertion `idmap.empty() == true' failed.

Failed with 'Aborted'; backtrace (libbacktrace):
utility/src/utility/system-stackTrace.C::83 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
utgcns/stashContains.C::206 in _ZN5tgTig15unstashContainsEv()
utgcns/utgcns.C::623 in _Z11processTigsR13cnsParameters()
utgcns/utgcns.C::990 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
Aborted (core dumped)
```
Removing the maxcoverage parameter has no effect, there is still the same error. Whenever I try to use the export command as suggested, I got the following error:

```
-- Using seqFile '../het0.2_err0.5.ctgStore/partition.0044'.
-- Opening tigStore '../het0.2_err0.5.ctgStore' version 1.
-- Opening output package 'bad_tig.tig'.

Failed with 'Segmentation fault'; backtrace (libbacktrace):
utility/src/utility/system-stackTrace.C::83 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
stores/sqStore.C::136 in _ZN7sqStore24sqStore_saveReadToBufferEP11writeBufferjP6sqReadP16sqReadDataWriter()
stores/tgTig.C::690 in _ZN5tgTig10exportDataEP11writeBufferP7sqStoreb()
utgcns/utgcns.C::445 in _Z10exportTigsR13cnsParameters()
utgcns/utgcns.C::984 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
Segmentation fault (core dumped)

```
So, unfortunately at this moment I am not able to give you the sequence of the bad contig. Any ideas?

**Comment by johnomics** [comment]
I am having exactly the same problem as @tbenavi1 with canu 2.1, except I have 7 of 8 consensus jobs failing:
```
consensus.000001.out:Failed to unstash the contained reads.  Still have 1351 reads unplaced.
consensus.000002.out:Failed to unstash the contained reads.  Still have 1142 reads unplaced.
consensus.000003.out:Failed to unstash the contained reads.  Still have 50 reads unplaced.
consensus.000004.out:Failed to unstash the contained reads.  Still have 1008 reads unplaced.
consensus.000006.out:Failed to unstash the contained reads.  Still have 810 reads unplaced.
consensus.000007.out:Failed to unstash the contained reads.  Still have 388 reads unplaced.
consensus.000008.out:Failed to unstash the contained reads.  Still have 330 reads unplaced.
```

Partition 5 succeeds.

These all appear to be due to the first tig in each partition - here they are, from the partitioning file, with numbers of reads matching the unplaced reads above:
```
      Tig     Reads    Length         Area  Memory GB  Partition    Data GB
--------- --------- --------- ------------  ---------  ---------  ---------
        1      1351   2779814   3755528714      2.651          1      0.046
        2        50    207734     10386700      0.198          3      0.083
        3      1008   1922376   1937755008      1.833          4      0.062
        4      1142   2188330   2499072860      2.087          2      0.059
        5       810   1542672   1249564320      1.471          6      0.082
        7      1197   1561961   1869667317      1.490          5      0.073
       15       388    755889    293284932      0.721          7      0.130
       20       330    723188    238652040      0.690          8      0.094
```

I can get the assembly to complete using cnsMaxCoverage=0, however I deleted the entire 5-consensus folder, rather than just the consensus.sh script.

I tried to replicate the error with utgcns and maxcoverage=40 after the assembly was completed, but the job ran successfully, as @tbenavi1 saw. So I tried deleting the cnsStore, 4-unitigging and 5-consensus, and ended up with the same utgcns errors. The same tigs are failing, but I can't export them, getting the same segmentation fault as @tbenavi1.

John

**Comment by skoren** [comment]
How big are your ctgStore and seqStore folders? If you can tar both of those (make sure to tar including symlinks) and upload them to the FTP (see the direction on the FAQ), we should be able to test it locally.

**Comment by johnomics** [comment]
Thanks - OK, file issue1780_johnomics_2020-09-01.tar.gz now on the FTP server, contains the seqStore, ctgStore and 5-consensus folders, with a README including the command I ran and a summary of the data. tarred with h option so should include symlinks. Please let me know if you need anything else. Thanks for looking into this.

**Comment by jbh-cas** [comment]
Thanks for looking into this issue. I have a similar situation. 

Four out of 32 failed. I reran one failed set with maxcoverage 0 and that did complete. I reran with maxcoverage set back to 40 and the -V -V args hoping to see the problem tig, but though it failed with the same output as the first failure, the logging does not shed much light -- shown below.

I ran Canu 2.1 on the recent Asian Giant Hornet, Vespa mandarinia, assembly, downloading the HiFi reads from SRR12366675 in preparation for trying version 2.1 on a much larger genome (which did assemble with Canu 2.0). They used IPA for the published assembly, so I was also curious to compare the results. So, possibly, the same issue might arise if you try that dataset. Also, threads set to 1 with maxcoverage 40 failed, whereas threads 8 and maxcoverage 0 completed.


The completed file was 22M bytes the, incomplete 18M. I've renamed the successful output with .OK appended in what's shown below.

```
~/ncbi-genomes-2020-08-25/unitigging/5-consensus$ ls -l ctgcns/0020*
-rw-rw-r-- 1 jhenderson ccg 22449494 Sep  1 16:59 ctgcns/0020.cns.OK
-rw-rw-r-- 1 jhenderson ccg 18210816 Sep  1 17:11 ctgcns/0020.cns.WORKING
```

Here's the bottom of the output from the -V -V run:
```
~/ncbi-genomes-2020-08-25/unitigging/5-consensus$ tail -50  consensus.000020.out
alignEdLib()-- align read  422878 eRate 0.0250 at   2189104-2211648   - ALIGNED 0.0130 at   2182179-2201212  
alignEdLib()-- align read  464266 eRate 0.0250 at   2190224-2205068   - ALIGNED 0.0160 at   2183404-2201864  
alignEdLib()-- align read 1435683 eRate 0.0250 at   2189937-2210925   - ALIGNED 0.0132 at   2185489-2201273  
alignEdLib()-- align read 1815681 eRate 0.0250 at   2194472-2211546   - ALIGNED 0.0133 at   2185364-2201817  
alignEdLib()-- align read 1033287 eRate 0.0250 at   2194844-2217286   - ALIGNED 0.0153 at   2185658-2203004  
alignEdLib()-- align read  983005 eRate 0.0250 at   2195245-2214442   - ALIGNED 0.0165 at   2188512-2205036  
alignEdLib()-- align read  465130 eRate 0.0250 at   2198577-2214042   - ALIGNED 0.0094 at   2188891-2205047  
alignEdLib()-- align read 1423414 eRate 0.0250 at   2201103-2222531   - ALIGNED 0.0091 at   2192004-2203399  
alignEdLib()-- align read  797709 eRate 0.0250 at   2201212-2223255   - ALIGNED 0.0007 at   2191752-2209128  
 - ALIGNED 0.0148 at   2196502-2209520  
alignEdLib()-- align read  504529 eRate 0.0250 at   2201552-2226520  alignEdLib()-- align read 1617395 eRate 0.0250 at   2201894-2225863   - ALIGNED 0.0108 at   2200370-2212316  
alignEdLib()-- align read 1894277 eRate 0.0250 at   2202700-2221756   - ALIGNED 0.0148 at   2192411-2208543  
alignEdLib()-- align read  907304 eRate 0.0250 at   2203144-2224958   - ALIGNED 0.0073 at   2197506-2212275  
alignEdLib()-- align read  795963 eRate 0.0250 at   2204703-2226846   - ALIGNED 0.0090 at   2197477-2214722  
alignEdLib()-- align read  508055 eRate 0.0250 at   2205671-2222970   - ALIGNED 0.0132 at   2203606-2220016  
alignEdLib()-- align read  997566 eRate 0.0250 at   2205937-2227185   - ALIGNED 0.0134 at   2203774-2220706  
alignEdLib()-- align read  896210 eRate 0.0250 at   2206419-2225998   - ALIGNED 0.0125 at   2204927-2219564  
alignEdLib()-- align read 1896583 eRate 0.0250 at   2206577-2228549   - ALIGNED 0.0081 at   2207664-2221035  
alignEdLib()-- align read  314135 eRate 0.0250 at   2209398-2229674   - ALIGNED 0.0117 at   2204674-2223120  
alignEdLib()-- align read  952819 eRate 0.0250 at   2211239-2229674   - ALIGNED 0.0059 at   2205675-2222473  
alignEdLib()-- align read 1039806 eRate 0.0250 at   2211534-2229674   - ALIGNED 0.0091 at   2204446-2223676  
alignEdLib()-- align read 1356148 eRate 0.0250 at   2212749-2227275   - ALIGNED 0.0057 at   2207262-2224292  
alignEdLib()-- align read  458277 eRate 0.0250 at   2215994-2229674   - ALIGNED 0.0036 at   2208678-2223764  
 - ALIGNED 0.0003 at   2208387-2224754  
 - ALIGNED 0.0067 at   2214407-2225605  
 - ALIGNED 0.0069 at   2217581-2228290  
 - ALIGNED 0.0126 at   2209110-2225978  
 - ALIGNED 0.0079 at   2211868-2228334  
 - ALIGNED 0.0051 at   2213617-2229622  
 - ALIGNED 0.0055 at   2213889-2229674  
generatePBDAG()--    read alignment: 0 failed, 3182 passed.
Constructing graph
Merging graph
Calling consensus
Failed to unstash the contained reads.  Still have 3182 reads unplaced.
utgcns: utgcns/stashContains.C:206: void tgTig::unstashContains(): Assertion `idmap.empty() == true' failed.

Failed with 'Aborted'; backtrace (libbacktrace):
utility/src/utility/system-stackTrace.C::83 in _Z17AS_UTL_catchCrashiP7siginfoPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
utgcns/stashContains.C::206 in _ZN5tgTig15unstashContainsEv()
utgcns/utgcns.C::623 in _Z11processTigsR13cnsParameters()
utgcns/utgcns.C::990 in main()
(null)::0 in (null)()
(null)::0 in (null)()
Aborted (core dumped)
```

thanks for all that you do in this arena,
Jim Henderson

**Comment by brianwalenz** [comment]
Sorry folks.  This was a pretty big fluck up from me.  The flaw won't lead to incorrect results; it'll either crash or generate the correct result.  Why it didn't crash for us on three quite different systems is a mystery.

If you're compiling from source, the quick fix is to change src/utgcns/stashedContains.C at line 46 from:
```
  //  Initialize.
  //    Declare that we have no stashed reads.
  //    Clear the return statistics.

  _stashedLen = 0;
```
to
```
  //  Initialize.
  //    Declare that we have no stashed reads.
  //    Clear the return statistics.

  _stashed    = nullptr;
  _stashedLen = 0;
  _stashedMax = 0;
```

This has been committed to the 'v2.1-maintenance' branch.  Attached is a fixed (Linux amd64) binary, [utgcns.gz](https://github.com/marbl/canu/files/5162616/utgcns.gz)

**Comment by johnomics** [comment]
Hi Brian,

Thank you very much for fixing this so quickly. Dropping in the new utgcns binary fixes the problem for me. Thanks for all your hard work on canu, which continues to produce better assemblies for us than any other assembler.

Best wishes
John

**Comment by tbenavi1** [comment]
Thanks, your changes for stashedContains.C worked for me.

**Comment by jbh-cas** [comment]
Brian, Thank you very, very much.
This looks like it is working on my set. Although I was surprised that the maxcoverage 40 output for 0020.cns is a bit bigger than when we used all (maxcoverage 0), but I guess that is the nature of consensus:
$ ls -l 0020.cns.OK 0020.cns
-rw-rw-r-- 1 jhenderson ccg 23121228 Sep  2 10:30 0020.cns

-rw-rw-r-- 1 jhenderson ccg 22449494 Sep  1 16:59 0020.cns.OK
A question on the maxcoverage setting. If you know your coverage is in the 50X range is it best to leave the 40X cutoff or set to 0 or 55 or the like?
That is, if coverage 40 gets you most but not all of the reads
is it any better to use those last remaining HiFi reads.
btw, this class of problem is why some use that four-letter word Rust ;)
best and thanks again,
Jim Henderson
---------------------------- Original Message ----------------------------
Subject: Re: [marbl/canu] Failed to unstash the contained reads. Still have 9 reads unplaced. (#1780)

From: "Brian Walenz" 

Date: Wed, September 2, 2020 6:41 am

To: "marbl/canu" 

Cc: "jbh-cas" 

"Comment" 

--------------------------------------------------------------------------




 
Sorry folks. This was a pretty big fluck up from me. The flaw won't lead to incorrect results; it'll either crash or generate the correct result. Why
it didn't crash for us on three quite different systems is a mystery.
If you're compiling from source, the quick fix is to change src/utgcns/stashedContains.C at line 46 from:
  //  Initialize.   //    Declare that we have no stashed reads.   //    Clear the return statistics.    _stashedLen = 0; 

to

  //  Initialize.   //    Declare that we have no stashed reads.   //    Clear the return statistics.    _stashed    = nullptr;   _stashedLen = 0;   _stashedMax = 0; 

This has been committed to the 'v2.1-maintenance' branch. Attached is a fixed (Linux amd64) binary, utgcns.gz—

**Comment by skoren** [comment]
I'm don't think that maxCoverage=0 was actually using all the data, I don't see anything in the code that would treat 0 as "all". It would use less coverage which is why the file is smaller. It's more likely you just got lucky and the uninitialized variables were OK on one run vs another. Generally, 40x is when you don't see much return on higher coverage, you can use 50 but the consensus wouldn't really improve and you'd have a higher cost to compute the consensus.

**Comment by brianwalenz** [comment]
If anyone is tracking the `v2.1-maintenance` branch, please update again.  The fix above exposed a memory leak in the read correction (for non-HiFi data) and was causing a crash.

If you just manually changed stashContains.C or are using attached utgcns binary, you're immune.
