### ISSUE TITLE
The results of canu assembly are quite different

### ISSUE THREAD

**Issue by Boston1212** [marbl/canu#1782]
Hi,recently, I have been using canu to assemble my Nanopore reads. I have assembled three times with the same data,but the assembly results are quite different. I don't know where the problem is.            

Here is my script :
`canu -p Kp914 -d /Users/usrname/Kp914 genomeSize=5m rawErrorRate=0.300 correctedErrorRate=0.100 useGrid=false -nanopore /Users/usrname/samples/Kp914/Kp914.porechopQC.filtered_reads.fq.gz`     

This is my assembly result. The number is the assembly size:

1 | chromosome | 5420878 | 5409063 | 5414401
-- | -- | -- | -- | --
2 | Plasmid | 88793 | 83728 | 272497
3 | Plasmid | 284737 | 281264 | 83393
  |   |   | 46069 | 44353
  |   |   |   | 46629
  |   |   |   | 56164
  |   |   |   | 43031

Any help or advice will be much appreciated!

**Comment by brianwalenz** [comment]
How much coverage in input reads do you have?  Canu will automatically downsample to 200x by removing random shorter reads.  You can change this with `maxInputCoverage=<number>`.

Post Kp914.report for more help.

**Comment by Boston1212** [comment]
> How much coverage in input reads do you have? Canu will automatically downsample to 200x by removing random shorter reads. You can change this with `maxInputCoverage=<number>`.
> 
> Post Kp914.report for more help.

**The coverage of our data is between 380x and 720x, so when using canu, do we need to change `maxinputcoverage= < number >` according to different data? Is there any way to deal with this kind of data with different coverage ?Any advice or help will be much appreciated!**

**And here is my Kp914.report.**

> [CORRECTION/READS]
--
-- In sequence store './Kp914.seqStore':
--   Found 89542 reads.
--   Found 1000037515 bases (200 times coverage).
--    
--    G=1000037515                       sum of  ||               length     num
--    NG         length     index       lengths  ||                range    seqs
--    ----- ------------ --------- ------------  ||  ------------------- -------
--    00010        38803      2154    100017808  ||       2000-3822        19193|---------------------------------------------------------------
--    00020        30526      5082    200015318  ||       3823-5645        13978|----------------------------------------------
--    00030        24943      8717    300018153  ||       5646-7468        10312|----------------------------------
--    00040        20527     13148    400032093  ||       7469-9291         7926|---------------------------
--    00050        16883     18519    500021440  ||       9292-11114        6386|---------------------
--    00060        13550     25128    600033164  ||      11115-12937        5174|-----------------
--    00070        10580     33480    700032620  ||      12938-14760        4044|--------------
--    00080         7806     44449    800032038  ||      14761-16583        3503|------------
--    00090         5091     60209    900038564  ||      16584-18406        2951|----------
--    00100         2000     89541   1000037515  ||      18407-20229        2561|---------
--    001.000x               89542   1000037515  ||      20230-22052        2143|--------
--                                               ||      22053-23875        1739|------
--                                               ||      23876-25698        1540|------
--                                               ||      25699-27521        1260|-----
--                                               ||      27522-29344        1116|----
--                                               ||      29345-31167         946|----
--                                               ||      31168-32990         810|---
--                                               ||      32991-34813         681|---
--                                               ||      34814-36636         548|--
--                                               ||      36637-38459         500|--
--                                               ||      38460-40282         380|--
--                                               ||      40283-42105         393|--
--                                               ||      42106-43928         333|--
--                                               ||      43929-45751         227|-
--                                               ||      45752-47574         177|-
--                                               ||      47575-49397         153|-
--                                               ||      49398-51220         120|-
--                                               ||      51221-53043         116|-
--                                               ||      53044-54866          75|-
--                                               ||      54867-56689          68|-
--                                               ||      56690-58512          46|-
--                                               ||      58513-60335          43|-
--                                               ||      60336-62158          27|-
--                                               ||      62159-63981          29|-
--                                               ||      63982-65804          15|-
--                                               ||      65805-67627           7|-
--                                               ||      67628-69450           5|-
--                                               ||      69451-71273           2|-
--                                               ||      71274-73096           6|-
--                                               ||      73097-74919           4|-
--                                               ||      74920-76742           0|
--                                               ||      76743-78565           1|-
--                                               ||      78566-80388           1|-
--                                               ||      80389-82211           1|-
--                                               ||      82212-84034           0|
--                                               ||      84035-85857           0|
--                                               ||      85858-87680           0|
--                                               ||      87681-89503           0|
--                                               ||      89504-91326           0|
--                                               ||      91327-93149           2|-
--

>[CORRECTION/MERS]
--
--  16-mers                                                                                           Fraction
--    Occurrences   NumMers                                                                         Unique Total
--       1-     1         0                                                                        0.0000 0.0000
--       2-     2  35624387 ********************************************************************** 0.4553 0.0853
--       3-     4  20984183 *****************************************                              0.6325 0.1351
--       5-     7   8950869 *****************                                                      0.7778 0.1947
--       8-    11   3861987 *******                                                                0.8556 0.2440
--      12-    16   1745494 ***                                                                    0.8936 0.2803
--      17-    22    833541 *                                                                      0.9120 0.3056
--      23-    29    432700                                                                        0.9213 0.3230
--      30-    37    262849                                                                        0.9262 0.3354
--      38-    46    209799                                                                        0.9294 0.3455
--      47-    56    241980                                                                        0.9320 0.3561
--      57-    67    364970                                                                        0.9352 0.3717
--      68-    79    602089 *                                                                      0.9400 0.4004
--      80-    92    952387 *                                                                      0.9480 0.4563
--      93-   106   1246662 **                                                                     0.9605 0.5582
--     107-   121   1104939 **                                                                     0.9764 0.7086
--     122-   137    547173 *                                                                      0.9901 0.8553
--     138-   154    132372                                                                        0.9966 0.9340
--     155-   172     23967                                                                        0.9982 0.9545
--     173-   191     16063                                                                        0.9984 0.9589
--     192-   211     19916                                                                        0.9986 0.9624
--     212-   232     19956                                                                        0.9989 0.9673
--     233-   254     15465                                                                        0.9992 0.9726
--     255-   277     10582                                                                        0.9993 0.9770
--     278-   301      8975                                                                        0.9995 0.9803
--     302-   326      8636                                                                        0.9996 0.9834
--     327-   352      7220                                                                        0.9997 0.9867
--     353-   379      4625                                                                        0.9998 0.9896
--     380-   407      2236                                                                        0.9999 0.9915
--     408-   436      1122                                                                        0.9999 0.9926
--     437-   466       855                                                                        0.9999 0.9931
--     467-   497       713                                                                        0.9999 0.9936
--     498-   529       480                                                                        0.9999 0.9940
--     530-   562       460                                                                        0.9999 0.9943
--     563-   596       458                                                                        0.9999 0.9946
--     597-   631       454                                                                        0.9999 0.9949
--     632-   667       543                                                                        0.9999 0.9952
--     668-   704       609                                                                        0.9999 0.9957
--     705-   742       620                                                                        1.0000 0.9962
--     743-   781       594                                                                        1.0000 0.9967
--     782-   821       583                                                                        1.0000 0.9972
--
--           0 (max occurrences)
--   835204480 (total mers, non-unique)
--    78245479 (distinct mers, non-unique)
--           0 (unique mers)

>[CORRECTION/LAYOUT]
--                             original      original
--                            raw reads     raw reads
--   category                w/overlaps  w/o/overlaps
--   Number of Reads              72054        231248
--   Number of Bases          941616479      58363340
--   Coverage                   188.323        11.673
--   Median                        9796             0
--   Mean                         13068           252
--   N50                          17904          3292
--   Minimum                       2021             0
--   Maximum                      93148         23410
--   
--                                        --------corrected---------  ----------rescued----------
--                             evidence                     expected                     expected
--   category                     reads            raw     corrected            raw     corrected
--   Number of Reads              77208           5100          5100           2061          2061
--   Number of Bases          953937673      200348403     200018685       11440798       6833439
--   Coverage                   190.788         40.070        40.004          2.288         1.367
--   Median                        9166          37190         37147           5415          3093
--   Mean                         12355          39284         39219           5551          3315
--   N50                          17712          38766         38669           5688          3765
--   Minimum                       2000          30413         30400           2872          1009
--   Maximum                      93148          92086         91964          13549          9433
--   
--                        --------uncorrected--------
--                                           expected
--   category                       raw     corrected
--   Number of Reads             296141        296141
--   Number of Bases          788190618     562477381
--   Coverage                   157.638       112.495
--   Median                           0             0
--   Mean                          2661          1899
--   N50                          13729         16908
--   Minimum                          0             0
--   Maximum                      93148         93135
--   
--   Maximum Memory          1494716054

>[TRIMMING/READS]
--
-- In sequence store './Kp914.seqStore':
--   Found 7161 reads.
--   Found 208139974 bases (41.62 times coverage).
--    
--    G=208139974                        sum of  ||               length     num
--    NG         length     index       lengths  ||                range    seqs
--    00010        52959       355     20858504  ||        983-2616          777|--------------------------------------------------------------
--    00020        47145       773     41658978  ||       2617-4250          790|---------------------------------------------------------------
--    00030        43481      1234     62460873  ||       4251-5884          373|------------------------------
--    00040        41121      1727     83291475  ||       5885-7518          100|--------
--    00050        38562      2250    104101302  ||       7519-9152           18|--
--    00060        36515      2804    124888362  ||       9153-10786           3|-
--    00070        34696      3389    145715520  ||      10787-12420           0|
--    00080        33058      4004    166531189  ||      12421-14054           0|
--    00090        31538      4648    187341654  ||      14055-15688           0|
--    00100          983      7160    208139974  ||      15689-17322           0|
--    001.000x                7161    208139974  ||      17323-18956           0|
--                                               ||      18957-20590           0|
--                                               ||      20591-22224           0|
--                                               ||      22225-23858           3|-
--                                               ||      23859-25492           0|
--                                               ||      25493-27126           1|-
--                                               ||      27127-28760           0|
--                                               ||      28761-30394           0|
--                                               ||      30395-32028         637|---------------------------------------------------
--                                               ||      32029-33662         699|--------------------------------------------------------
--                                               ||      33663-35296         572|----------------------------------------------
--                                               ||      35297-36930         502|-----------------------------------------
--                                               ||      36931-38564         440|------------------------------------
--                                               ||      38565-40198         326|--------------------------
--                                               ||      40199-41832         353|-----------------------------
--                                               ||      41833-43466         327|---------------------------
--                                               ||      43467-45100         244|--------------------
--                                               ||      45101-46734         188|---------------
--                                               ||      46735-48368         150|------------
--                                               ||      48369-50002         116|----------
--                                               ||      50003-51636         108|---------
--                                               ||      51637-53270          99|--------
--                                               ||      53271-54904          74|------
--                                               ||      54905-56538          65|------
--                                               ||      56539-58172          44|----
--                                               ||      58173-59806          34|---
--                                               ||      59807-61440          32|---
--                                               ||      61441-63074          27|---
--                                               ||      63075-64708          21|--
--                                               ||      64709-66342          15|--
--                                               ||      66343-67976           4|-
--                                               ||      67977-69610           5|-
--                                               ||      69611-71244           2|-
--                                               ||      71245-72878           4|-
--                                               ||      72879-74512           4|-
--                                               ||      74513-76146           1|-
--                                               ||      76147-77780           1|-
--                                               ||      77781-79414           0|
--                                               ||      79415-81048           1|-
--                                               ||      81049-82682           1|-
--

>[TRIMMING/MERS]
--
--  22-mers                                                                                           Fraction
--    Occurrences   NumMers                                                                         Unique Total
--       1-     1         0                                                                        0.0000 0.0000
--       2-     2    308879 *********                                                              0.0484 0.0030
--       3-     4    219647 ******                                                                 0.0695 0.0050
--       5-     7    143013 ****                                                                   0.0920 0.0080
--       8-    11    110528 ***                                                                    0.1103 0.0120
--      12-    16    102510 ***                                                                    0.1260 0.0170
--      17-    22    155421 ****                                                                   0.1417 0.0243
--      23-    29    893201 ***************************                                            0.1714 0.0437
--      30-    37   2315346 ********************************************************************** 0.3424 0.1909
--      38-    46   1844392 *******************************************************                0.7102 0.5856
--      47-    56    220023 ******                                                                 0.9659 0.9191
--      57-    67      4479                                                                        0.9886 0.9540
--      68-    79     12425                                                                        0.9894 0.9555
--      80-    92      4540                                                                        0.9913 0.9599
--      93-   106      1651                                                                        0.9920 0.9617
--     107-   121      1946                                                                        0.9922 0.9625
--     122-   137     18449                                                                        0.9925 0.9637
--     138-   154     21320                                                                        0.9957 0.9768
--     155-   172       889                                                                        0.9988 0.9906
--     173-   191       847                                                                        0.9989 0.9913
--     192-   211       553                                                                        0.9990 0.9918
--     212-   232       330                                                                        0.9991 0.9923
--     233-   254      1337                                                                        0.9991 0.9927
--     255-   277      1882                                                                        0.9994 0.9943
--     278-   301      2097                                                                        0.9997 0.9972
--     302-   326        37                                                                        1.0000 0.9996
--     327-   352        30                                                                        1.0000 0.9997
--     353-   379        15                                                                        1.0000 0.9997
--     380-   407        35                                                                        1.0000 0.9998
--     408-   436        20                                                                        1.0000 0.9998
--     437-   466        10                                                                        1.0000 0.9999
--     467-   497         1                                                                        1.0000 0.9999
--     498-   529         6                                                                        1.0000 0.9999
--     530-   562         6                                                                        1.0000 0.9999
--     563-   596         3                                                                        1.0000 0.9999
--     597-   631         8                                                                        1.0000 0.9999
--     632-   667         0                                                                        0.0000 0.0000
--     668-   704         2                                                                        1.0000 1.0000
--     705-   742         2                                                                        1.0000 1.0000
--     743-   781         3                                                                        1.0000 1.0000
--     782-   821         2                                                                        1.0000 1.0000
--
--           0 (max occurrences)
--   206020236 (total mers, non-unique)
--     6385885 (distinct mers, non-unique)
--           0 (unique mers)

>[TRIMMING/TRIMMING]
--  PARAMETERS:
--     1000    (reads trimmed below this many bases are deleted)
--   0.1000    (use overlaps at or below this fraction error)
--      500    (break region if overlap is less than this long, for 'largest covered' algorithm)
--        2    (break region if overlap coverage is less than this many reads, for 'largest covered' algorithm)
--  INPUT READS:
--  303302 reads    208139974 bases (reads processed)
--       0 reads            0 bases (reads not processed, previously deleted)
--       0 reads            0 bases (reads not processed, in a library where trimming isn't allowed)
--  OUTPUT READS:
--    4383 reads    159853201 bases (trimmed reads output)
--    2776 reads     47935421 bases (reads with no change, kept as is)
--  296141 reads            0 bases (reads with no overlaps, deleted)
--       2 reads         1968 bases (reads with short trimmed length, deleted)
--  
--  TRIMMING DETAILS:
--    1810 reads       115118 bases (bases trimmed from the 5' end of a read)
--    3729 reads       234266 bases (bases trimmed from the 3' end of a read)

>[TRIMMING/SPLITTING]
--  PARAMETERS:
--     1000    (reads trimmed below this many bases are deleted)
--   0.1000    (use overlaps at or below this fraction error)
--  INPUT READS:
--    7159 reads    208138006 bases (reads processed)
--  296143 reads         1968 bases (reads not processed, previously deleted)
--       0 reads            0 bases (reads not processed, in a library where trimming isn't allowed)
--  PROCESSED:
--       0 reads            0 bases (no overlaps)
--       0 reads            0 bases (no coverage after adjusting for trimming done already)
--       0 reads            0 bases (processed for chimera)
--       0 reads            0 bases (processed for spur)
--    7159 reads    208138006 bases (processed for subreads)
--  READS WITH SIGNALS:
--       0 reads            0 signals (number of 5' spur signal)
--       0 reads            0 signals (number of 3' spur signal)
--       0 reads            0 signals (number of chimera signal)
--       0 reads            0 signals (number of subread signal)
--  SIGNALS:
--       0 reads            0 bases (size of 5' spur signal)
--       0 reads            0 bases (size of 3' spur signal)
--       0 reads            0 bases (size of chimera signal)
--       0 reads            0 bases (size of subread signal)
--  TRIMMING:
--       0 reads            0 bases (trimmed from the 5' end of the read)
--       0 reads            0 bases (trimmed from the 3' end of the read)

>[UNITIGGING/READS]
-- In sequence store './Kp914.seqStore':
--   Found 7159 reads.
--   Found 207788622 bases (41.55 times coverage).
--    G=207788622                        sum of  ||               length     num
--    NG         length     index       lengths  ||                range    seqs
--    00010        52886       354     20785586  ||       1027-2660          798|--------------------------------------------------------------
--    00020        47085       772     41563422  ||       2661-4294          779|--------------------------------------------------------------
--    00030        43439      1233     62343353  ||       4295-5928          366|-----------------------------
--    00040        41076      1726     83154218  ||       5929-7562           96|--------
--    00050        38522      2248    103899407  ||       7563-9196           18|--
--    00060        36494      2803    124700506  ||       9197-10830           2|-
--    00070        34640      3387    145464108  ||      10831-12464           0|
--    00080        33026      4002    166255742  ||      12465-14098           0|
--    00090        31515      4645    187012838  ||      14099-15732           0|
--    00100         1027      7158    207788622  ||      15733-17366           1|-
--    001.000x                7159    207788622  ||      17367-19000           2|-
--                                               ||      19001-20634           1|-
--                                               ||      20635-22268           4|-
--                                               ||      22269-23902           3|-
--                                               ||      23903-25536           1|-
--                                               ||      25537-27170           1|-
--                                               ||      27171-28804           1|-
--                                               ||      28805-30438           4|-
--                                               ||      30439-32072         661|-----------------------------------------------------
--                                               ||      32073-33706         694|-------------------------------------------------------
--                                               ||      33707-35340         571|----------------------------------------------
--                                               ||      35341-36974         491|---------------------------------------
--                                               ||      36975-38608         446|------------------------------------
--                                               ||      38609-40242         321|--------------------------
--                                               ||      40243-41876         351|----------------------------
--                                               ||      41877-43510         331|---------------------------
--                                               ||      43511-45144         230|-------------------
--                                               ||      45145-46778         187|---------------
--                                               ||      46779-48412         153|-------------
--                                               ||      48413-50046         112|---------
--                                               ||      50047-51680         107|---------
--                                               ||      51681-53314          96|--------
--                                               ||      53315-54948          74|------
--                                               ||      54949-56582          62|-----
--                                               ||      56583-58216          45|----
--                                               ||      58217-59850          35|---
--                                               ||      59851-61484          31|---
--                                               ||      61485-63118          27|---
--                                               ||      63119-64752          19|--
--                                               ||      64753-66386          15|--
--                                               ||      66387-68020           4|-
--                                               ||      68021-69654           5|-
--                                               ||      69655-71288           2|-
--                                               ||      71289-72922           4|-
--                                               ||      72923-74556           4|-
--                                               ||      74557-76190           1|-
--                                               ||      76191-77824           1|-
--                                               ||      77825-79458           0|
--                                               ||      79459-81092           1|-
--                                               ||      81093-82726           1|-
--
>[UNITIGGING/MERS]
--  22-mers                                                                                           Fraction
--    Occurrences   NumMers                                                                         Unique Total
--       1-     1         0                                                                        0.0000 0.0000
--       2-     2    307383 *********                                                              0.0482 0.0030
--       3-     4    219116 ******                                                                 0.0692 0.0049
--       5-     7    142693 ****                                                                   0.0917 0.0080
--       8-    11    110569 ***                                                                    0.1100 0.0119
--      12-    16    102552 ***                                                                    0.1256 0.0170
--      17-    22    158186 ****                                                                   0.1414 0.0243
--      23-    29    899623 ***************************                                            0.1715 0.0440
--      30-    37   2322358 ********************************************************************** 0.3441 0.1926
--      38-    46   1830577 *******************************************************                0.7127 0.5885
--      47-    56    217154 ******                                                                 0.9659 0.9190
--      57-    67      4472                                                                        0.9886 0.9539
--      68-    79     12511                                                                        0.9894 0.9555
--      80-    92      4449                                                                        0.9913 0.9599
--      93-   106      1651                                                                        0.9920 0.9617
--     107-   121      1947                                                                        0.9922 0.9625
--     122-   137     18495                                                                        0.9925 0.9636
--     138-   154     21274                                                                        0.9957 0.9768
--     155-   172      1167                                                                        0.9988 0.9906
--     173-   191       568                                                                        0.9990 0.9916
--     192-   211       553                                                                        0.9990 0.9918
--     212-   232       331                                                                        0.9991 0.9923
--     233-   254      1336                                                                        0.9991 0.9927
--     255-   277      1882                                                                        0.9994 0.9943
--     278-   301      2097                                                                        0.9997 0.9972
--     302-   326        37                                                                        1.0000 0.9996
--     327-   352        30                                                                        1.0000 0.9997
--     353-   379        15                                                                        1.0000 0.9997
--     380-   407        35                                                                        1.0000 0.9998
--     408-   436        20                                                                        1.0000 0.9998
--     437-   466        10                                                                        1.0000 0.9999
--     467-   497         1                                                                        1.0000 0.9999
--     498-   529         6                                                                        1.0000 0.9999
--     530-   562         6                                                                        1.0000 0.9999
--     563-   596         3                                                                        1.0000 0.9999
--     597-   631         8                                                                        1.0000 0.9999
--     632-   667         0                                                                        0.0000 0.0000
--     668-   704         2                                                                        1.0000 1.0000
--     705-   742         2                                                                        1.0000 1.0000
--     743-   781         3                                                                        1.0000 1.0000
--     782-   821         2                                                                        1.0000 1.0000
--
--           0 (max occurrences)
--   205740171 (total mers, non-unique)
--     6383124 (distinct mers, non-unique)
--           0 (unique mers)

>[UNITIGGING/OVERLAPS]
--   category            reads     %          read length        feature size or coverage  analysis
--   middle-missing          0    0.00        0.00 +- 0.00             0.00 +- 0.00       (bad trimming)
--   middle-hump             0    0.00        0.00 +- 0.00             0.00 +- 0.00       (bad trimming)
--   no-5-prime              0    0.00        0.00 +- 0.00             0.00 +- 0.00       (bad trimming)
--   no-3-prime              0    0.00        0.00 +- 0.00             0.00 +- 0.00       (bad trimming)
--   low-coverage            0    0.00        0.00 +- 0.00             0.00 +- 0.00       (easy to assemble, potential for lower quality consensus)
--   unique               6919   96.65    29074.18 +- 17619.30        36.43 +- 6.11       (easy to assemble, perfect, yay)
--   repeat-cont            88    1.23     7033.07 +- 9285.69        122.09 +- 30.78      (potential for consensus errors, no impact on assembly)
--   repeat-dove             2    0.03    44086.50 +- 2696.20        104.10 +- 20.56      (hard to assemble, likely won't assemble correctly or even at all)
--   span-repeat             4    0.06    44804.75 +- 3284.78      27118.50 +- 17859.34   (read spans a large repeat, usually easy to assemble)
--   uniq-repeat-cont       94    1.31    37069.97 +- 5229.32                             (should be uniquely placed, low potential for consensus errors, no impact on assembly)
--   uniq-repeat-dove       51    0.71    43410.61 +- 2678.50                             (will end contigs, potential to misassemble)
--   uniq-anchor             1    0.01    39580.00 +- 0.00          2519.00 +- 0.00       (repeat read, with unique section, probable bad read)

>[UNITIGGING/ADJUSTMENT]
-- No report available.

>[UNITIGGING/CONTIGS]
-- Found, in version 1, after unitig construction:
--   contigs:      3 sequences, total length 5788868 bp (including 0 repeats of total length 0 bp).
--   bubbles:      0 sequences, total length 0 bp.
--   unassembled:  1 sequences, total length 41731 bp.
-- Contig sizes based on genome size 5mbp:
--            NG (bp)  LG (contigs)    sum (bp)
--     10     5415555             1     5415555
--     20     5415555             1     5415555
--     30     5415555             1     5415555
--     40     5415555             1     5415555
--     50     5415555             1     5415555
--     60     5415555             1     5415555
--     70     5415555             1     5415555
--     80     5415555             1     5415555
--     90     5415555             1     5415555
--    100     5415555             1     5415555
--    110      284545             2     5700100
--

>[UNITIGGING/CONSENSUS]
-- Found, in version 2, after consensus generation:
--   contigs:      3 sequences, total length 5794408 bp (including 0 repeats of total length 0 bp).
--   bubbles:      0 sequences, total length 0 bp.
--   unassembled:  1 sequences, total length 41731 bp.
-- Contig sizes based on genome size 5mbp:
--            NG (bp)  LG (contigs)    sum (bp)
--     10     5420878             1     5420878
--     20     5420878             1     5420878
--     30     5420878             1     5420878
--     40     5420878             1     5420878
--     50     5420878             1     5420878
--     60     5420878             1     5420878
--     70     5420878             1     5420878
--     80     5420878             1     5420878
--     90     5420878             1     5420878
--    100     5420878             1     5420878
--    110      284737             2     5705615
--

**Comment by skoren** [comment]
You don't really need 700x to get an assembly so you don't need to change maxInputCoverage, it would just slow down the assembly. 

I wouldn't actually say your assemblies are very different. You're getting lightly different subsets when you so it changes the end of the contig but they're all circular I expect and if you trimmed them back to their unique region, I expect they'd be the same length. The main three contigs are always the same things. The shorter things (<50kb) based on the report I'd guess are low-frequency variants in the data or errors that are confirming each other, I bet they align to the larger rigs and it's just a matter of if you get enough reads sampled from them by the random set.

**Comment by Boston1212** [comment]
> You don't really need 700x to get an assembly so you don't need to change maxInputCoverage, it would just slow down the assembly.
> 
> I wouldn't actually say your assemblies are very different. You're getting lightly different subsets when you so it changes the end of the contig but they're all circular I expect and if you trimmed them back to their unique region, I expect they'd be the same length. The main three contigs are always the same things. The shorter things (<50kb) based on the report I'd guess are low-frequency variants in the data or errors that are confirming each other, I bet they align to the larger rigs and it's just a matter of if you get enough reads sampled from them by the random set.

Thanks for your advice!!!
