### ISSUE TITLE
Read coverage (0) is too low to be useful.-CANU

### ISSUE THREAD

**Issue by JiaZhibo123** [marbl/canu#1783]
```
-- Canu 1.9
--
-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
-- 
-- Koren S, Rhie A, Walenz BP, Dilthey AT, Bickhart DM, Kingan SB, Hiendleder S, Williams JL, Smith TPL, Phillippy AM.
-- De novo assembly of haplotype-resolved genomes with trio binning.
-- Nat Biotechnol. 2018
-- https//doi.org/10.1038/nbt.4277
-- 
-- Read and contig alignments during correction, consensus and GFA building use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '10.0.2' (from '/public/home/zbjia/miniconda3/bin/java') without -d64 support.
--
-- WARNING:
-- WARNING:  Failed to run gnuplot using command 'gnuplot'.
-- WARNING:  Plots will be disabled.
-- WARNING:
--
-- Detected 36 CPUs and 377 gigabytes of memory.
-- Detected LSF with 'bsub' binary in /opt/ibm/lsf/10.1/linux3.10-glibc2.17-x86_64/bin/bsub.
-- Discovered LSF_UNIT_FOR_LIMITS of 'MB' from '/opt/ibm/lsf/conf/lsf.conf'.
-- 
-- Found   1 host  with  96 cores and 3993 GB memory under LSF control.
-- Found   1 host  with  36 cores and  511 GB memory under LSF control.
-- Found   3 hosts with  12 cores and   63 GB memory under LSF control.
-- Found   4 hosts with 192 cores and 1945 GB memory under LSF control.
-- Found  29 hosts with  20 cores and  255 GB memory under LSF control.
-- Found   1 host  with  96 cores and 1945 GB memory under LSF control.
-- Found   1 host  with  20 cores and   63 GB memory under LSF control.
-- Found   2 hosts with  20 cores and   95 GB memory under LSF control.
-- Found  29 hosts with  20 cores and  127 GB memory under LSF control.
-- Found  44 hosts with  36 cores and  383 GB memory under LSF control.
-- Found   1 host  with  36 cores and  351 GB memory under LSF control.
-- Found  49 hosts with  36 cores and  191 GB memory under LSF control.
-- 
-- On LSF detected memory is requested in MBB
-- 
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl     31 GB    6 CPUs  (k-mer counting)
-- Grid:  hap       16 GB   18 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   19 GB    4 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    16 GB    4 CPUs  (overlap detection)
-- Grid:  utgovl    16 GB    4 CPUs  (overlap detection)
-- Grid:  cor       24 GB    4 CPUs  (read correction)
-- Grid:  ovb        4 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       32 GB    1 CPU   (overlap store sorting)
-- Grid:  red       19 GB    4 CPUs  (read error detection)
-- Grid:  oea        8 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      150 GB   16 CPUs  (contig construction with bogart)
-- Grid:  cns      --- GB    8 CPUs  (consensus)
-- Grid:  gfa      150 GB   16 CPUs  (GFA alignment and processing)
--
-- Found PacBio corrected reads in the input files.
--
-- Generating assembly '3045_r_correct' in '/public/home/zbjia/3045/correct'
--
-- Parameters:
--
--  genomeSize        1200000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0850 (  8.50%)
--    utgOvlErrorRate 0.0850 (  8.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0850 (  8.50%)
--    utgErrorRate    0.0850 (  8.50%)
--    cnsErrorRate    0.0850 (  8.50%)
--
--
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Mon Aug 31 20:06:32 2020 with 2211311.14 GB free disk space

    cd .
    /public/home/zbjia/soft/canu-1.9/Linux-amd64/bin/sqStoreCreate \
      -o ./3045_r_correct.seqStore.BUILDING \
      -minlength 2000 \
      ./3045_r_correct.seqStore.ssi \
    > ./3045_r_correct.seqStore.BUILDING.err 2>&1

-- Finished on Mon Aug 31 20:38:29 2020 (1917 seconds) with 2210868.359 GB free disk space
----------------------------------------
--
-- ERROR:  Read coverage (0) is too low to be useful.
-- ERROR:
-- ERROR:  This could be caused by an incorrect genomeSize or poor quality reads that could not
-- ERROR:  be sufficiently corrected.
-- ERROR:
-- ERROR:  You can force Canu to continue by decreasing parameter stopOnLowCoverage=10,
-- ERROR:  however, the quality of corrected reads and/or contiguity of contigs will be poor.
-- 

ABORT:
ABORT: Canu 1.9
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```

Hi I am run canu on a lsf system, it goes out an error like this . how do I fix it ? Please help me !
My script is like this :
```
#BSUB -J 3045_r_correct
#BSUB -n 20
#BSUB -R span[hosts=1]
#BSUB -o %J.out
#BSUB -e %J.err
#BSUB -q high
canu -correct \
-p 3045_r_correct -d /public/home/zbjia/3045/correct \
genomeSize=1.2g \
minReadLength=2000 minOverlapLength=1000 \
correctedErrorRate=0.085 corMhapSensitivity=normal \
corOutCoverage=150 \
-pacbio-corrected /public/home/zbjia/r_3045_subreads.fasta \
batMemory=150  gridOptionsBAT="-q high" \
gfaMemory=150  gridOptionsBAT="-q high" \
gridEngineResourceOption="-R 'span[hosts=1] rusage[mem=MEMORY]' -n THREADS -M MEMORY "
 ```

**Comment by skoren** [comment]
One issue I see is you're supplying the reads as `pacbio-corrected` but then also asking for correction so there is nothing to do, essentially it's saying there are no uncorrected reads to correct. If you want to run correction supply the reads as ```-pacbio-raw```.

**Comment by JiaZhibo123** [comment]
thank you I will run it later.
Now ,I have an another question,
I run canu to assemble ,the report is as blow
-- Canu 1.9
--
-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
-- 
-- Koren S, Rhie A, Walenz BP, Dilthey AT, Bickhart DM, Kingan SB, Hiendleder S, Williams JL, Smith TPL, Phillippy AM.
-- De novo assembly of haplotype-resolved genomes with trio binning.
-- Nat Biotechnol. 2018
-- https//doi.org/10.1038/nbt.4277
-- 
-- Read and contig alignments during correction, consensus and GFA building use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '10.0.2' (from '/public/home/zbjia/miniconda3/bin/java') without -d64 support.
--
-- WARNING:
-- WARNING:  Failed to run gnuplot using command 'gnuplot'.
-- WARNING:  Plots will be disabled.
-- WARNING:
--
-- Detected 36 CPUs and 377 gigabytes of memory.
-- Detected LSF with 'bsub' binary in /opt/ibm/lsf/10.1/linux3.10-glibc2.17-x86_64/bin/bsub.
-- Discovered LSF_UNIT_FOR_LIMITS of 'MB' from '/opt/ibm/lsf/conf/lsf.conf'.
-- 
-- Found  29 hosts with  20 cores and  127 GB memory under LSF control.
-- Found   1 host  with  96 cores and 1945 GB memory under LSF control.
-- Found   3 hosts with  12 cores and   63 GB memory under LSF control.
-- Found  29 hosts with  20 cores and  255 GB memory under LSF control.
-- Found  44 hosts with  36 cores and  383 GB memory under LSF control.
-- Found   1 host  with  36 cores and  511 GB memory under LSF control.
-- Found   2 hosts with  20 cores and   95 GB memory under LSF control.
-- Found  50 hosts with  36 cores and  191 GB memory under LSF control.
-- Found   1 host  with  96 cores and 3993 GB memory under LSF control.
-- Found   1 host  with  20 cores and   63 GB memory under LSF control.
-- Found   4 hosts with 192 cores and 1945 GB memory under LSF control.
-- Found   1 host  with  36 cores and  351 GB memory under LSF control.
-- 
-- On LSF detected memory is requested in MBB
-- 
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl     31 GB    6 CPUs  (k-mer counting)
-- Grid:  hap       16 GB   18 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   19 GB    4 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    16 GB    4 CPUs  (overlap detection)
-- Grid:  utgovl    16 GB    4 CPUs  (overlap detection)
-- Grid:  cor       24 GB    4 CPUs  (read correction)
-- Grid:  ovb        4 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       32 GB    1 CPU   (overlap store sorting)
-- Grid:  red       19 GB    4 CPUs  (read error detection)
-- Grid:  oea        8 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      256 GB   16 CPUs  (contig construction with bogart)
-- Grid:  cns      --- GB    8 CPUs  (consensus)
-- Grid:  gfa       32 GB   16 CPUs  (GFA alignment and processing)
--
-- Found PacBio corrected reads in the input files.
--
-- Generating assembly '3008_sk_ass' in '/public/home/zbjia/3008/assemble'
--
-- Parameters:
--
--  genomeSize        1200000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0750 (  7.50%)
--
--
-- BEGIN ASSEMBLY
--
-- WARNING:
-- WARNING:  Previously failed seqStore detected.
-- WARNING:
    /public/home/zbjia/soft/canu-1.9/Linux-amd64/bin/sqStoreDumpMetaData \
      -S ./3008_sk_ass.seqStore \
      -libs \
    > ./3008_sk_ass.seqStore/libraries.txt \
    2> /dev/null

ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:

ABORT:
ABORT: Canu 1.9
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to generate list of libraries in store.
ABORT:


And my scripts is 
#BSUB -J 3008-ass
#BSUB -n 20
#BSUB -R span[hosts=1]
#BSUB -o %J.out
#BSUB -e %J.err
#BSUB -q high
canu -assemble \
-p 3008_sk_ass -d /public/home/zbjia/3008/assemble \
genomeSize=1.2g \
-pacbio-corrected /public/home/zbjia/3008/trim/3008_sk_trim.trimmedReads.fasta.gz \
batMemory=150  gridOptionsBAT="-q high" \
gfaMemory=150  gridOptionsBAT="-q high"

can you help me to run it ?

**Comment by skoren** [comment]
Follow what the reported error says: "Previously failed seqStore detected." You already tried and have a failed assembly in your folder, clean up any existing folders and re-start from scratch. If that gives an error post that.

**Comment by JiaZhibo123** [comment]
OK，I will try .thank you

**Comment by JiaZhibo123** [comment]
hello，I still have an question ,when I assemble genome use canu after trim , my data have 70X, can I assemble just use 50X？

**Comment by skoren** [comment]
The FAQ address this question, the default is to assemble the longest 40x plus any reads not represented by the longest 40x which Canu auto-selects. You increased the default of 40x to 150x in one of your earlier commands so it likely tried to correct all your data. You can select the longest 40x of the correct reads but this risks losing things like plasmids/mitochondria. On very heterozygous genomes we recommend increasing the default coverage over 40x.

**Comment by JiaZhibo123** [comment]
OK,thanks for your advice

**Comment by JiaZhibo123** [comment]
> The FAQ address this question, the default is to assemble the longest 40x plus any reads not represented by the longest 40x which Canu auto-selects. You increased the default of 40x to 150x in one of your earlier commands so it likely tried to correct all your data. You can select the longest 40x of the correct reads but this risks losing things like plasmids/mitochondria. On very heterozygous genomes we recommend increasing the default coverage over 40x.
