### ISSUE TITLE
no unitigs output file using canu2.1

### ISSUE THREAD

**Issue by biobai** [marbl/canu#1786]
canu 2.1 was tested with my pacbio data. 
```
/data/programs/canu-2.1/bin/canu \
 -p SD1 -d ../results/canu_2.1_result \
 genomeSize=34m \
 -pacbio ../raw_data/my.subreads.fq.fastq.gz
```
I had the same problem with the issue #1780. I changed maxCoverage=0 and canu finished completely. 

My problem is that no *unitigs.* file at all in the output directory.
report file attached. Thanks
[SD1.zip](https://github.com/marbl/canu/files/5162898/SD1.zip)

**Comment by skoren** [comment]
Yes, the unitigs and their GFA have been removed in 2.1. They were just too fragmented (more fragmented than they needed to be) and unreliable (missing some edges) to be of useful. We expect in the future to add more reliable assembly graphs once we have finalized an improved contig strategy.

**Comment by skoren** [comment]
Unitigs + their gfa intentionally removed.
