### ISSUE TITLE
One OEA job per read

### ISSUE THREAD

**Issue by Tierhon** [marbl/canu#179]
Hi, 
for some reason, canu wants to run one OEA job per read. With 2085502 reads, it wants to run 2085502 jobs. This is not efficient I suspect. 

I run this with:
canu \
 useGrid=0 \
 -p species -d canu \
 genomeSize=700m \
 cnsThreads=4 \
 ovsConcurrency=16 \
 ovsMemory=5g-500g \
 corMhapSensitivity=high corMinCoverage=0 errorRate=0.12 \
 -pacbio-raw reads.fastq

I have around 25x coverage. See below for a snapshot of the log. Could it be the 4928.2 adjustments per read that leads to each job wanting 5256.3 MB, and then being too large for the 2 GB limit set? 

The code is from a snapshot from 26th of May. Tried to see of you had fixed any bugs related to this since then, but couldn't find anything.

Thank you.

Ole

```
    /work/users/olekto/haddock/assembly/canu/canu/unitigging/3-overlapErrorAdjustment/red.sh 414 > /work/users/olekto/haddock/assembly/canu/canu/unitigging/3-overlapErrorAdjustment/red.000414.out 2>&1
    /work/users/olekto/haddock/assembly/canu/canu/unitigging/3-overlapErrorAdjustment/red.sh 415 > /work/users/olekto/haddock/assembly/canu/canu/unitigging/3-overlapErrorAdjustment/red.000415.out 2>&1
    /work/users/olekto/haddock/assembly/canu/canu/unitigging/3-overlapErrorAdjustment/red.sh 416 > /work/users/olekto/haddock/assembly/canu/canu/unitigging/3-overlapErrorAdjustment/red.000416.out 2>&1
    /work/users/olekto/haddock/assembly/canu/canu/unitigging/3-overlapErrorAdjustment/red.sh 417 > /work/users/olekto/haddock/assembly/canu/canu/unitigging/3-overlapErrorAdjustment/red.000417.out 2>&1
    /work/users/olekto/haddock/assembly/canu/canu/unitigging/3-overlapErrorAdjustment/red.sh 418 > /work/users/olekto/haddock/assembly/canu/canu/unitigging/3-overlapErrorAdjustment/red.000418.out 2>&1

-- Finished on Sun Jun 26 08:40:00 2016 (90401 seconds) with 60676.9 GB free disk space
----------------------------------------
-- Found 418 read error detection output files.

Configure OEA for 2gb memory with batches of at most 25000 reads and (unlimited) bases.

OEA job   1 from read         1 to read         1 -  0.0 bases + 4928.2 adjusts +  0.0 reads +  0.1 olaps +  8.0 fseq/rseq + 32.0 fadj/radj + 32.0 work + 256.0 misc = 5256.3 MB
OEA job   2 from read         2 to read         2 -  0.0 bases + 4928.2 adjusts +  0.0 reads +  0.1 olaps +  8.0 fseq/rseq + 32.0 fadj/radj + 32.0 work + 256.0 misc = 5256.2 MB
OEA job   3 from read         3 to read         3 -  0.0 bases + 4928.2 adjusts +  0.0 reads +  0.1 olaps +  8.0 fseq/rseq + 32.0 fadj/radj + 32.0 work + 256.0 misc = 5256.2 MB
OEA job   4 from read         4 to read         4 -  0.0 bases + 4928.2 adjusts +  0.0 reads +  0.0 olaps +  8.0 fseq/rseq + 32.0 fadj/radj + 32.0 work + 256.0 misc = 5256.2 MB
OEA job   5 from read         5 to read         5 -  0.0 bases + 4928.2 adjusts +  0.0 reads +  0.0 olaps +  8.0 fseq/rseq + 32.0 fadj/radj + 32.0 work + 256.0 misc = 5256.2 MB
OEA job   6 from read         6 to read         6 -  0.0 bases + 4928.2 adjusts +  0.0 reads +  0.0 olaps +  8.0 fseq/rseq + 32.0 fadj/radj + 32.0 work + 256.0 misc = 5256.2 MB
OEA job   7 from read         7 to read         7 -  0.0 bases + 4928.2 adjusts +  0.0 reads +  0.1 olaps +  8.0 fseq/rseq + 32.0 fadj/radj + 32.0 work + 256.0 misc = 5256.2 MB
OEA job   8 from read         8 to read         8 -  0.0 bases + 4928.2 adjusts +  0.0 reads +  0.0 olaps +  8.0 fseq/rseq + 32.0 fadj/radj + 32.0 work + 256.0 misc = 5256.2 MB
OEA job   9 from read         9 to read         9 -  0.0 bases + 4928.2 adjusts +  0.0 reads +  0.1 olaps +  8.0 fseq/rseq + 32.0 fadj/radj + 32.0 work + 256.0 misc = 5256.2 MB
```

**Comment by skoren** [comment]
I assume you're running version 1.3? What does the Canu preamble say about resources it has available to use? Also, how big is the red.red file in unitigging/3-*/red.red? As a workaround you can set oeaMemory=32 or some largish value which will cause Canu to start less jobs.

**Comment by Tierhon** [comment]
The snapshot is more or less identical with 1.3 I guess.

red.red is 1.9 GB. Changing to oeaMemory=32 leads to just 84 jobs created:
Configure OEA for 32gb memory with batches of at most 25000 reads and (unlimited) bases.

OEA job   1 from read         1 to read     25000 - 93.4 bases + 4928.2 adjusts +  0.8 reads + 362.2 olaps +  8.0 fseq/rseq + 32.0 fadj/radj + 32.0 work + 256.0 misc = 5712.5 MB
OEA job   2 from read     25001 to read     50000 - 103.1 bases + 4928.2 adjusts +  0.8 reads + 239.5 olaps +  8.0 fseq/rseq + 32.0 fadj/radj + 32.0 work + 256.0 misc = 5599.6 MB
OEA job   3 from read     50001 to read     75000 - 93.6 bases + 4928.2 adjusts +  0.8 reads + 213.1 olaps +  8.0 fseq/rseq + 32.0 fadj/radj + 32.0 work + 256.0 misc = 5563.5 MB
OEA job   4 from read     75001 to read    100000 - 90.8 bases + 4928.2 adjusts +  0.8 reads + 192.3 olaps +  8.0 fseq/rseq + 32.0 fadj/radj + 32.0 work + 256.0 misc = 5540.0 MB

This is the preamble:
-- Detected Java(TM) Runtime Environment '1.8.0_77' (from 'java').
-- Detected 64 CPUs and 1010 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /usr/bin/sinfo.
-- Grid engine disabled per useGrid=false option.
--
-- Allowed to run   4 jobs concurrently, and use up to  16 compute threads and  252 GB memory for stage 'bogart (unitigger)'.
-- Allowed to run   4 jobs concurrently, and use up to  16 compute threads and   32 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   4 jobs concurrently, and use up to  16 compute threads and   32 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   4 jobs concurrently, and use up to  16 compute threads and   32 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   8 jobs concurrently, and use up to   8 compute threads and    8 GB memory for stage 'read error detection (overlap error adjustment)'.
-- Allowed to run  64 jobs concurrently, and use up to   1 compute thread  and   32 GB memory for stage 'overlap error adjustment'.
-- Allowed to run  16 jobs concurrently, and use up to   4 compute threads and   48 GB memory for stage 'utgcns (consensus'.
-- Allowed to run  64 jobs concurrently, and use up to   1 compute thread  and    4 GB memory for stage 'overlap store parallel bucketizer'.
-- Allowed to run  16 jobs concurrently, and use up to   1 compute thread  and  500 GB memory for stage 'overlap store parallel sorting'.
-- Allowed to run  64 jobs concurrently, and use up to   1 compute thread  and    8 GB memory for stage 'overlapper'.
-- Allowed to run   8 jobs concurrently, and use up to   8 compute threads and   12 GB memory for stage 'overlapper'.
-- Allowed to run   8 jobs concurrently, and use up to   8 compute threads and   12 GB memory for stage 'overlapper'.
-- Allowed to run   4 jobs concurrently, and use up to  16 compute threads and   64 GB memory for stage 'meryl (k-mer counting)'.
-- Allowed to run  16 jobs concurrently, and use up to   4 compute threads and   20 GB memory for stage 'falcon_sense (read correction)'.
-- Allowed to run   4 jobs concurrently, and use up to  16 compute threads and   32 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   4 jobs concurrently, and use up to  16 compute threads and   32 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   4 jobs concurrently, and use up to  16 compute threads and   32 GB memory for stage 'minimap (overlapper)'.

So the workaround seems to have worked fine.

Thank you.

Ole

**Comment by skoren** [comment]
Ah, so the issue is the red file is taking up all the memory (1.9 / 2gb) not letting any sequences fit. We should check its size and increase OEA memory if needed, we should also probably increase the minimum used for larger genomes.

**Comment by brianwalenz** [comment]
Canu will now automagically (and without permission from the user) increase the memory request for OEA jobs if the jobs are tiny.  Tiny is defined as fewer than 1024 reads per job, and more than 8 jobs.

**Comment by JohnUrban** [comment]
So Canu does use magic… I thought so!
