### ISSUE TITLE
Install from source instructions don't work

### ISSUE THREAD

**Issue by outpaddling** [marbl/canu#1790]
FYI, the install from source instructions at [https://github.com/marbl/canu/releases/tag/v2.1](https://github.com/marbl/canu/releases/tag/v2.1) do not work because the submodules are missing from the release tarballs.

```
tar zxf canu-2.1.tar.gz
cd canu-2.1/src
gmake

```
[snip]

```
Using '/usr/local/bin/g++9' version '9.3.0'.

Makefile:707: meryl/src/meryl/meryl.mk: No such file or directory
gmake: *** No rule to make target 'meryl/src/meryl/meryl.mk'.  Stop.

```

**Comment by skoren** [comment]
The instructions look correct, the refer to the 2.1 tar that is available for download and not the auto-created ones. GitHub doesn't support submodules and so their packaging is broken, this is a known issue. I added a note to the instructions to clarify that you should use the tar we provide not the source made by GitHub.

**Comment by outpaddling** [comment]
That'll work, thanks.
