### ISSUE TITLE
How do I react here?

### ISSUE THREAD

**Issue by jahneldardavik** [marbl/canu#1798]

**Comment by jahneldardavik** [comment]
![image](https://user-images.githubusercontent.com/25763942/93374109-8c1fed80-f856-11ea-8c3c-02b833d12e27.png)

**Comment by jahneldardavik** [comment]
this is the message I got after 24 hs running of Canu

**Comment by skoren** [comment]
It's a good idea to search for a similar error in other issues. I think this is likely the same as #1791 and #1780. You can confirm by checking the logs of the failing jobs. Those issues have updated version of the utgcns binary (both for Linux and OSX depending on which machine type you're running on). Once you replace the utgcns in your canu installation with the fixed version, you can re-start Canu and it should resume from the current step and re-generate consensus.

**Comment by jahneldardavik** [comment]
OK, thank you.
I need to Get some Linux litterate to sort me out here.
Otherwise, Flye seem to run .

Sendt fra min iPad

16. sep. 2020 kl. 20:19 skrev Sergey Koren <notifications@github.com>:

﻿

It's a good idea to search for a similar error in other issues. I think this is likely the same as #1791<https://github.com/marbl/canu/issues/1791> and #1780<https://github.com/marbl/canu/issues/1780>. You can confirm by checking the logs of the failing jobs. Those issues have updated version of the utgcns binary (both for Linux and OSX depending on which machine type you're running on). Once you replace the utgcns in your canu installation with the fixed version, you can re-start Canu and it should resume from the current step and re-generate consensus.

**Comment by skoren** [comment]
Not very hard, follow the instructions in the  issue I pointed you to, assuming canu is installed in /usr/canu-2.1/ (or wherever you put it):
```
cd /usr/canu-2.1/bin
rm ./utgcns
wget https://github.com/marbl/canu/files/5162616/utgcns.gz
gunzip utgcns.gz
chmod u+x utgcns
./utgcns
```

As long as the new binary words you're done.

**Comment by jahneldardavik** [comment]
OK. Thank you.
So, I follow your instructions, and restart my canu.sh?



Fra: Sergey Koren <notifications@github.com>
Sendt: onsdag 16. september 2020 20:51
Til: marbl/canu <canu@noreply.github.com>
Kopi: Jahn Davik <jahn.davik@nibio.no>; Author <author@noreply.github.com>
Emne: Re: [marbl/canu] How do I react here? (#1798)


Not very hard, follow the instructions in the issue I pointed you to, assuming canu is installed in /usr/canu-2.1/ (or wherever you put it):

cd /usr/canu-2.1/bin

rm ./utgcns

wget https://github.com/marbl/canu/files/5162616/utgcns.gz

gunzip utgcns.gz

chmod u+x utgcns

./utgcns

As long as the new binary words you're done.

**Comment by brianwalenz** [comment]
Yes, replace the utgcns file in bin/ with the commands Sergey posted, then restart canu.  It will resume the assembly starting with the ctgcns jobs.

**Comment by jahneldardavik** [comment]
Did as you said. Got the attached error message. Don’t know if it matters?



Fra: Sergey Koren <notifications@github.com>
Sendt: onsdag 16. september 2020 20:51
Til: marbl/canu <canu@noreply.github.com>
Kopi: Jahn Davik <jahn.davik@nibio.no>; Author <author@noreply.github.com>
Emne: Re: [marbl/canu] How do I react here? (#1798)


Not very hard, follow the instructions in the issue I pointed you to, assuming canu is installed in /usr/canu-2.1/ (or wherever you put it):

cd /usr/canu-2.1/bin

rm ./utgcns

wget https://github.com/marbl/canu/files/5162616/utgcns.gz

gunzip utgcns.gz

chmod u+x utgcns

./utgcns

As long as the new binary words you're done.

**Comment by jahneldardavik** [comment]
Believe it worked. Thanks.


Fra: Brian Walenz <notifications@github.com>
Sendt: torsdag 17. september 2020 08:56
Til: marbl/canu <canu@noreply.github.com>
Kopi: Jahn Davik <jahn.davik@nibio.no>; Author <author@noreply.github.com>
Emne: Re: [marbl/canu] How do I react here? (#1798)


Yes, replace the utgcns file in bin/ with the commands Sergey posted, then restart canu. It will resume the assembly starting with the ctgcns jobs.
