### ISSUE TITLE
utgcn file not work

### ISSUE THREAD

**Issue by zhanwen-cheng** [marbl/canu#1799]
Hi brain, I met some problem with my canu processing.
My canu version:
![image](https://user-images.githubusercontent.com/26667865/93428104-76abd180-f8f1-11ea-9f2d-4cd92d2cf3d3.png)
My linux version:
![image](https://user-images.githubusercontent.com/26667865/93428246-b07cd800-f8f1-11ea-819c-5e5180dbfe83.png)
My canu command:
`nohup canu -p yca30 -d . genomeSize=1m minReadLength=200 minOverlapLength=150 corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0 -nanopore-raw ~/CZW_disk/groundwater_nanopore/raw_data/yca_30/fastq_pass.fq > yca30.log`
After my running, canu show the same as #1791 and #1780， two consensous jobs failed.
Thus I update the utgcn file as you post in 1791 like this:
`cd /Users/victorpylro/tools/canu-2.1/bin/
rm ./utgcns
wget https://github.com/marbl/canu/files/5196664/utgcns.gz
gunzip utgcns.gz
chmod u+x utgcns
./utgcns`
However, canu still failed to work with following report:
```
-- Starting command on Thu Sep 17 13:57:07 2020 with 2333.952 GB free disk space

    cd unitigging
    /home/chengzw/software/canu/build/bin/utgcns \
      -S ../yca30.seqStore \
      -T  ./yca30.ctgStore 1 \
      -partition 0.8 1 0.1 \
    > ./yca30.ctgStore/partitioning.log 2>&1

-- Finished on Thu Sep 17 13:57:07 2020 (in the blink of an eye) with 2333.952 GB free disk space
----------------------------------------

ERROR:
ERROR:  Failed with exit code 2.  (rc=512)
ERROR:

ABORT:
ABORT: canu snapshot v2.2-development +34 changes (r10143 2c12c357c17fabc55132c3c045950f6ba1b5f4d9)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to partition the reads.
ABORT:
ABORT: Disk space available:  2333.952 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (unitigging/yca30.ctgStore/partitioning.log):
ABORT:
ABORT:   /home/chengzw/software/canu/build/bin/utgcns: 1: /home/chengzw/software/canu/build/bin/utgcns: Syntax error: "(" unexpected
ABORT:`
Here is my log file.
[yca30.log](https://github.com/marbl/canu/files/5236769/yca30.log)
```
It seem ths utgcns file is binary file and we couldn't see it.

Can you help me to check that?
Thanks!

![canu_version](https://user-images.githubusercontent.com/26667865/93429036-11f17680-f8f3-11ea-921a-ce88a3de7234.PNG)
![ubuntu_version](https://user-images.githubusercontent.com/26667865/93429042-128a0d00-f8f3-11ea-9286-e2bfc29df0e4.PNG)

**Comment by brianwalenz** [comment]
It looks like you're downloading to and running different copies of canu.  The download went to `/Users/victorpylro/tools/canu-2.1/bin/` while the running version is reporting '/home/chengzw/software/canu/build/bin/utgcns'.

Are you on MacOS or Linux?  The patched binary in the issue will only work on Linux.

If you're compiling from source - as the last `canu --version` seems to be reporting) you don't need to download the fixed version.  The fix is included in the source.

**Comment by zhanwen-cheng** [comment]
Hi brain, I just paste the command from #1791 to github below, and actually I download and replace utgcns to my own file, that's '/home/chengzw/software/canu/build/bin/'.
Whatever, did you mean the latest version(my version) not need to replace the utgcns file?

**Comment by zhanwen-cheng** [comment]
Hi brain, I re-installed canu from github now without changing anything, and ran the same command  
"canu -p yca30 -d . genomeSize=1m minReadLength=200 minOverlapLength=150 corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0 -nanopore-raw ~/CZW_disk/groundwater_nanopore/raw_data/yca_30/fastq_pass.fq" without deleting previous intermediate file, it reports the same mitake the same to my first runing canu like #1791 and #1780 

(base) chengzw@profxia-SUSTC-309:~/CZW_disk/groundwater_nanopore/assemble/canu/yca30_1m$ canu -p yca30 -d . genomeSize=1m minReadLength=200 minOverlapLength=150 corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0 -nanopore-raw ~/CZW_disk/groundwater_nanopore/raw_data/yca_30/fastq_pass.fq
-- canu snapshot v2.2-development +34 changes (r10143 2c12c357c17fabc55132c3c045950f6ba1b5f4d9)
--
-- CITATIONS
--
-- For 'standard' assemblies of PacBio or Nanopore reads:
--   Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
--   Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
--   Genome Res. 2017 May;27(5):722-736.
--   http://doi.org/10.1101/gr.215087.116
--
-- Read and contig alignments during correction and consensus use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
--
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
--
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
--
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
--
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
--
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '11.0.4' (from 'java') without -d64 support.
-- Detected gnuplot version '5.0 patchlevel 3   ' (from 'gnuplot') and image format 'png'.
-- Detected 80 CPUs and 504 gigabytes of memory.
-- No grid engine detected, grid and staging disabled.
--
--                                (tag)Concurrency
--                         (tag)Threads          |
--                (tag)Memory         |          |
--        (tag)             |         |          |       total usage      algorithm
--        -------  ----------  --------   --------  --------------------  -----------------------------
-- Local: meryl     12.000 GB    4 CPUs x  20 jobs   240.000 GB  80 CPUs  (k-mer counting)
-- Local: hap        8.000 GB    4 CPUs x  20 jobs   160.000 GB  80 CPUs  (read-to-haplotype assignment)
-- Local: cormhap    6.000 GB   16 CPUs x   5 jobs    30.000 GB  80 CPUs  (overlap detection with mhap)
-- Local: obtovl     4.000 GB    8 CPUs x  10 jobs    40.000 GB  80 CPUs  (overlap detection)
-- Local: utgovl     4.000 GB    8 CPUs x  10 jobs    40.000 GB  80 CPUs  (overlap detection)
-- Local: cor        8.000 GB    4 CPUs x  20 jobs   160.000 GB  80 CPUs  (read correction)
-- Local: ovb        4.000 GB    1 CPU  x  80 jobs   320.000 GB  80 CPUs  (overlap store bucketizer)
-- Local: ovs        8.000 GB    1 CPU  x  63 jobs   504.000 GB  63 CPUs  (overlap store sorting)
-- Local: red       16.000 GB    4 CPUs x  20 jobs   320.000 GB  80 CPUs  (read error detection)
-- Local: oea        8.000 GB    1 CPU  x  63 jobs   504.000 GB  63 CPUs  (overlap error adjustment)
-- Local: bat       16.000 GB    4 CPUs x   1 job     16.000 GB   4 CPUs  (contig construction with bogart)
-- Local: cns        -.--- GB    4 CPUs x   - jobs     -.--- GB   - CPUs  (consensus)
--
-- Found Nanopore reads in 'yca30.seqStore':
--   Libraries:
--     Nanopore:              1
--   Reads:
--     Raw:                   200000429
--     Corrected:             198770632
--     Corrected and Trimmed: 127181697
--
--
-- Generating assembly 'yca30' in '/home/chengzw/CZW_disk/groundwater_nanopore/assemble/canu/yca30_1m':
--   genomeSize:
--     1000000
--
--   Overlap Generation Limits:
--     corOvlErrorRate 0.3200 ( 32.00%)
--     obtOvlErrorRate 0.1200 ( 12.00%)
--     utgOvlErrorRate 0.1200 ( 12.00%)
--
--   Overlap Processing Limits:
--     corErrorRate    0.5000 ( 50.00%)
--     obtErrorRate    0.1200 ( 12.00%)
--     utgErrorRate    0.1200 ( 12.00%)
--     cnsErrorRate    0.2000 ( 20.00%)
--
--   Stages to run:
--     assemble corrected and trimmed reads.
--
--
-- Corrected reads exist in yca30.seqStore.
--
-- Trimmed reads exist in yca30.seqStore.
--
-- BEGIN ASSEMBLY
----------------------------------------
-- Starting command on Thu Sep 17 14:57:27 2020 with 2333.952 GB free disk space

    cd unitigging
    /home/chengzw/software/canu/build/bin/utgcns \
      -S ../yca30.seqStore \
      -T  ./yca30.ctgStore 1 \
      -partition 0.8 1 0.1 \
    > ./yca30.ctgStore/partitioning.log 2>&1

-- Finished on Thu Sep 17 14:57:34 2020 (7 seconds) with 2333.825 GB free disk space
----------------------------------------
-- Using slow alignment for consensus (iteration '0').
-- Configured 23 consensus jobs.
-- Finished stage 'consensusConfigure', reset canuIteration.
--
--                                (tag)Concurrency
--                         (tag)Threads          |
--                (tag)Memory         |          |
--        (tag)             |         |          |       total usage      algorithm
--        -------  ----------  --------   --------  --------------------  -----------------------------
-- Local: cns        0.500 GB    4 CPUs x  20 jobs    10.000 GB  80 CPUs  (consensus)
--
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'cns' concurrent execution on Thu Sep 17 14:57:34 2020 with 2333.825 GB free disk space (23 processes; 20 concurrently)

    cd unitigging/5-consensus
    ./consensus.sh 1 > ./consensus.000001.out 2>&1
    ./consensus.sh 2 > ./consensus.000002.out 2>&1
    ./consensus.sh 3 > ./consensus.000003.out 2>&1
    ./consensus.sh 4 > ./consensus.000004.out 2>&1
    ./consensus.sh 5 > ./consensus.000005.out 2>&1
    ./consensus.sh 6 > ./consensus.000006.out 2>&1
    ./consensus.sh 7 > ./consensus.000007.out 2>&1
    ./consensus.sh 8 > ./consensus.000008.out 2>&1
    ./consensus.sh 9 > ./consensus.000009.out 2>&1
    ./consensus.sh 10 > ./consensus.000010.out 2>&1
    ./consensus.sh 11 > ./consensus.000011.out 2>&1
    ./consensus.sh 12 > ./consensus.000012.out 2>&1
    ./consensus.sh 13 > ./consensus.000013.out 2>&1
    ./consensus.sh 14 > ./consensus.000014.out 2>&1
    ./consensus.sh 15 > ./consensus.000015.out 2>&1
    ./consensus.sh 16 > ./consensus.000016.out 2>&1
    ./consensus.sh 17 > ./consensus.000017.out 2>&1
    ./consensus.sh 18 > ./consensus.000018.out 2>&1
    ./consensus.sh 19 > ./consensus.000019.out 2>&1
    ./consensus.sh 20 > ./consensus.000020.out 2>&1
    ./consensus.sh 21 > ./consensus.000021.out 2>&1
    ./consensus.sh 22 > ./consensus.000022.out 2>&1
    ./consensus.sh 23 > ./consensus.000023.out 2>&1

-- Finished on Thu Sep 17 14:57:39 2020 (5 seconds) with 2333.819 GB free disk space
----------------------------------------
-- Using slow alignment for consensus (iteration '1').
-- Configured 23 consensus jobs.
--
-- Consensus jobs failed, retry.
--   job ctgcns/0001.cns FAILED.
--   job ctgcns/0003.cns FAILED.
--   job ctgcns/0005.cns FAILED.
--   job ctgcns/0007.cns FAILED.
--   job ctgcns/0008.cns FAILED.
--   job ctgcns/0009.cns FAILED.
--   job ctgcns/0010.cns FAILED.
--   job ctgcns/0011.cns FAILED.
--   job ctgcns/0012.cns FAILED.
--   job ctgcns/0014.cns FAILED.
--   job ctgcns/0015.cns FAILED.
--   job ctgcns/0017.cns FAILED.
--   job ctgcns/0018.cns FAILED.
--   job ctgcns/0019.cns FAILED.
--   job ctgcns/0020.cns FAILED.
--   job ctgcns/0021.cns FAILED.
--   job ctgcns/0022.cns FAILED.
--   job ctgcns/0023.cns FAILED.
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'cns' concurrent execution on Thu Sep 17 14:57:39 2020 with 2333.819 GB free disk space (18 processes; 20 concurrently)

    cd unitigging/5-consensus
    ./consensus.sh 1 > ./consensus.000001.out 2>&1
    ./consensus.sh 3 > ./consensus.000003.out 2>&1
    ./consensus.sh 5 > ./consensus.000005.out 2>&1
    ./consensus.sh 7 > ./consensus.000007.out 2>&1
    ./consensus.sh 8 > ./consensus.000008.out 2>&1
    ./consensus.sh 9 > ./consensus.000009.out 2>&1
    ./consensus.sh 10 > ./consensus.000010.out 2>&1
    ./consensus.sh 11 > ./consensus.000011.out 2>&1
    ./consensus.sh 12 > ./consensus.000012.out 2>&1
    ./consensus.sh 14 > ./consensus.000014.out 2>&1
    ./consensus.sh 15 > ./consensus.000015.out 2>&1
    ./consensus.sh 17 > ./consensus.000017.out 2>&1
    ./consensus.sh 18 > ./consensus.000018.out 2>&1
    ./consensus.sh 19 > ./consensus.000019.out 2>&1
    ./consensus.sh 20 > ./consensus.000020.out 2>&1
    ./consensus.sh 21 > ./consensus.000021.out 2>&1
    ./consensus.sh 22 > ./consensus.000022.out 2>&1
    ./consensus.sh 23 > ./consensus.000023.out 2>&1

-- Finished on Thu Sep 17 14:57:44 2020 (5 seconds) with 2333.819 GB free disk space
----------------------------------------
-- Using slow alignment for consensus (iteration '2').
-- Configured 23 consensus jobs.
--
-- Consensus jobs failed, tried 2 times, giving up.
--   job ctgcns/0001.cns FAILED.
--   job ctgcns/0003.cns FAILED.
--   job ctgcns/0005.cns FAILED.
--   job ctgcns/0007.cns FAILED.
--   job ctgcns/0008.cns FAILED.
--   job ctgcns/0009.cns FAILED.
--   job ctgcns/0010.cns FAILED.
--   job ctgcns/0011.cns FAILED.
--   job ctgcns/0012.cns FAILED.
--   job ctgcns/0014.cns FAILED.
--   job ctgcns/0015.cns FAILED.
--   job ctgcns/0017.cns FAILED.
--   job ctgcns/0018.cns FAILED.
--   job ctgcns/0019.cns FAILED.
--   job ctgcns/0020.cns FAILED.
--   job ctgcns/0021.cns FAILED.
--   job ctgcns/0022.cns FAILED.
--   job ctgcns/0023.cns FAILED.
--

ABORT:
ABORT: canu snapshot v2.2-development +34 changes (r10143 2c12c357c17fabc55132c3c045950f6ba1b5f4d9)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:

What should I do at this stage?

**Comment by skoren** [comment]
You are still not running a release version, it would report version as 2.1 not `canu snapshot v2.2-development +34 changes (r10143 2c12c357c17fabc55132c3c045950f6ba1b5f4d9)`. As long as it reports a snapshot version it is incorrect. You seem to have two canu installs, one in :
```
 /home/chengzw/software/canu/build/bin/
```
and one in
```
/Users/victorpylro/tools/canu-2.1/bin/
```
I am pretty sure the second location is invalid since you're just copying and pasting the instructions instead of actually updating your installation. You should completely remove the canu folder from `/home/cengzw/software/canu` then run
```
cd  /home/chengzw/software/
wget https://github.com/marbl/canu/releases/download/v2.1/canu-2.1.Linux-amd64.tar.xz
tar -xJf canu-2.1.*.tar.xz
cd canu-2.1/bin/
rm ./utgcns
wget https://github.com/marbl/canu/files/5162616/utgcns.gz
gunzip utgcns.gz
chmod u+x utgcns
./utgcns
```
Remove any assembly outputs you have (`/home/chengzw/CZW_disk/groundwater_nanopore/assemble/canu/yca30_1m`) and start the run from scratch by giving a full path to Canu (/home/chengzw/software/canu-2.1/bin/canu`)`.

**Comment by zhanwen-cheng** [comment]
Ok, thanks! I have redownloaded canu 2.1 and updated utgcns file as you recommended, it works!
Thanks!
