### ISSUE TITLE
Contig circularisation

### ISSUE THREAD

**Issue by gringer** [marbl/canu#180]
I'm trying to assemble a circular mitochondria at the moment and getting a little frustrated that Canu isn't picking up on the circular aspect of it. I note that the Geneious assembler implements circularisation at an intermediate step, rather than annotating the end:

"""
The second more complex approach is to allow contigs to circularize during the assembly process and still allow similar sequences and contigs to merge into the circular contigs later. This approach is more robust and more likely to produce correct results. For example if we have two related species present in a data set, the ends of the temporary linear contigs may be sufficiently similar to merge into a large incorrect linear contig. But if we circularize during the assembly process, instead of merging they’ll correctly circularize first.
"""

http://blog.geneious.com/post/84370864944/building-a-circular-de-novo-assembler

At the moment, I suppose I could map to the middle of the assembled mitochondria, exclude all those reads, then reassemble something that hopefully includes an overlap with the linear assembly.

**Comment by skoren** [comment]
What assembly output are you looking for to indicate circularization? Pretty much all assemblers do what the quote from Geneious assembler says. If there is a circular structure in the assembly graph, Canu will walk it until the path loops back on itself causing it to stop. The point at which you start and stop in the circle is arbitrary but you should have overlaps on the ends of your linear contig that indicates a circle. 

The fasta file can't show a circular structure but you can look at the read-level GFA file (in unitigging/4-unitigger/asm.gfa) that you can visualize in something like Bandage to look for a circular structure in the graph. You can also look at the final GFA if you are trying to circularize multiple contigs into a single structure.

**Comment by gringer** [comment]
Okay, thank you. I had previously looked for a GFA I could use but didn't know about the unitigging one. My target (mitochondria) is either too small to be visible, or not obviously circular on the bandage plot:

![marjun_lowcoverage](https://cloud.githubusercontent.com/assets/856314/16403903/fb72039e-3d4d-11e6-8aef-c3a35cfc9680.png)

Ideally I'd like a list of all reads that map to the circular sequence. It would be nice if at least the assembly output gave an estimate of the circularised length, and/or a particular subset of the sequence that comprised a circular subset with no duplicated sequence.

That would save a couple of hours of work manually identifying a circular portion (which may have a few errors), duplicating and rotating the contig, then remapping my original sequences to the result.

**Comment by brianwalenz** [comment]
There were a bunch of flaws in the GFA output, but we now have one that looks reasonable, in files:
- asm.unitigs.fasta
- asm.unitigs.gfa
- asm.unitigs.layout

![screen shot 2016-10-20 at 10 47 17 am](https://cloud.githubusercontent.com/assets/8249720/19564576/00eb70ea-96b2-11e6-8576-e1cff1b42031.png)

That little circular guy is:
```
L       tig00000004     +       tig00000004     -       12405M
```
indicating a 12.4k overlap.

The 'layout' file will give the read to tig mapping.

I think we'd like to generate a cleaned up consensus for the circular contigs, but I'm closing this issue because I'd rather not clutter up the 'issues' with feature requests.
