### ISSUE TITLE
tagged 2.1 release archive no longer self sufficient.

### ISSUE THREAD

**Issue by EricDeveaud** [marbl/canu#1801]
Hello, 

while trying to install canu-2.1 I noticed that the tagged 2.1 source code archive is no longer sefl sufficient.
previous version are as easy to build than 

```
wget https://github.com/marbl/canu/archive/v$VERSION.tar.gz
tar xz v$VERSION.tar.gz
cd canu-$VERSION/src 
make 
```

vesion 2.1 archive lacks content of the following git submodules 

1. meryl code
2. seqrequester
3. utility 

you may want to consider providing a fully self sufficient archive again.

regards

Eric

**Comment by brianwalenz** [comment]
Unfortunately, there's nothing straightforward or easy we can do to fix this.  it's a limitation in git itself.  I'm open to suggestions.

https://github.com/dear-github/dear-github/issues/214 describes the problem.

**Comment by skoren** [comment]
We also provide a source tar.gz with the release which is self-sufficient, but as @brianwalenz git flaws make the automated source package not self sufficient.

**Comment by skoren** [comment]
Idle, no known fix possible due to git limitations but provided source tar is self-sufficient.
