### ISSUE TITLE
meryl histogram shows no kmers

### ISSUE THREAD

**Issue by drs357** [marbl/canu#1803]
```
-- Starting 'meryl' concurrent execution on Thu Sep 24 06:37:11 2020 with 36253.066 GB free disk space (1 processes; 20 concurrently)

    cd correction/0-mercounts
    ./meryl-process.sh 1 > ./meryl-process.000001.out 2>&1

-- Finished on Thu Sep 24 06:37:44 2020 (33 seconds) with 36242.105 GB free disk space
----------------------------------------
-- Meryl finished successfully.  Kmer frequency histogram:
ABORT:
ABORT: Canu 2.0
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   meryl histogram 'correction/0-mercounts/ATCC3626.ms16.histogram' shows no kmers.
```
I used Canu, version 2.0 

command was canu -d directory -p prefix genomesize=x.xm nanopore-raw xxxx.fastq 
I also tried running it with useGrid=false

I am running it on a linux, not exactly sure if it is a grid.

Thanks

**Comment by skoren** [comment]
Something is likely wrong with either the data or upstream in the run. Post all the files in ```correction/0-mercounts/*.out``` along with the full Canu run log.

**Comment by drs357** [comment]
this is in the 0-mercounts folder
3626.ms16.frequentMers.ignore.gz  3626.ms16.histogram.sm.gp    ATCC3626.ms16.dump                    ATCC3626.ms16.histogram.info   ATCC3626.ms16.ignore.gz  meryl-count.sh            meryl-process.sh
3626.ms16.histogram               ATCC3626.ms16                ATCC3626.ms16.frequentMers.ignore.gz  ATCC3626.ms16.histogram.lg.gp  meryl.000001.out         meryl-count.success       meryl.sh
3626.ms16.histogram.info          ATCC3626.ms16.config.01.out  ATCC3626.ms16.histogram               ATCC3626.ms16.histogram.png    meryl-configure.sh       meryl-make-ignore.pl
3626.ms16.histogram.lg.gp         ATCC3626.ms16.config.02.out  ATCC3626.ms16.histogram.gp            ATCC3626.ms16.histogram.sm.gp  meryl-count.000001.out   meryl-process.000001.out

**Comment by skoren** [comment]
I mean post the contents of those files.

**Comment by drs357** [comment]
these are all the files in the log folder:
``1600250547_hippocampus.pbtech_55381_canu                    1600252066_hippocampus.pbtech_67300_gatekeeperDumpFASTQ     1600941190_hippocampus.pbtech_11235_gatekeeperDumpFASTQ
1600250547_hippocampus.pbtech_55439_gatekeeperCreate        1600252067_hippocampus.pbtech_67335_gatekeeperDumpFASTQ     1600943786_hippocampus.pbtech_33998_canu
1600250554_hippocampus.pbtech_55591_gatekeeperDumpMetaData  1600252067_hippocampus.pbtech_67336_gatekeeperDumpFASTQ     1600943786_hippocampus.pbtech_34103_sqStoreCreate
1600250554_hippocampus.pbtech_55597_gatekeeperDumpMetaData  1600252067_hippocampus.pbtech_67337_gatekeeperDumpFASTQ     1600943793_hippocampus.pbtech_34302_sqStoreDumpMetaData
1600250667_hippocampus.pbtech_56464_gatekeeperDumpFASTQ     1600941113_hippocampus.pbtech_10456_canu                    1600943793_hippocampus.pbtech_34309_sqStoreDumpMetaData
1600250667_hippocampus.pbtech_56465_gatekeeperDumpFASTQ     1600941113_hippocampus.pbtech_10519_gatekeeperCreate        1600943793_hippocampus.pbtech_34315_sqStoreDumpMetaData
1600250667_hippocampus.pbtech_56466_gatekeeperDumpFASTQ     1600941118_hippocampus.pbtech_10533_gatekeeperDumpMetaData  1600943793_hippocampus.pbtech_34361_meryl
1600250669_hippocampus.pbtech_56501_gatekeeperDumpFASTQ     1600941118_hippocampus.pbtech_10538_gatekeeperDumpMetaData  1600943794_hippocampus.pbtech_34365_meryl
1600250669_hippocampus.pbtech_56502_gatekeeperDumpFASTQ     1600941188_hippocampus.pbtech_11195_gatekeeperDumpFASTQ     1600943794_hippocampus.pbtech_34414_meryl
1600250669_hippocampus.pbtech_56503_gatekeeperDumpFASTQ     1600941188_hippocampus.pbtech_11196_gatekeeperDumpFASTQ     1600943832_hippocampus.pbtech_34665_meryl
1600252066_hippocampus.pbtech_67203_canu                    1600941188_hippocampus.pbtech_11197_gatekeeperDumpFASTQ     1600943848_hippocampus.pbtech_34710_meryl
1600252066_hippocampus.pbtech_67298_gatekeeperDumpFASTQ     1600941190_hippocampus.pbtech_11233_gatekeeperDumpFASTQ     1600943864_hippocampus.pbtech_34899_meryl
1600252066_hippocampus.pbtech_67299_gatekeeperDumpFASTQ     1600941190_hippocampus.pbtech_11234_gatekeeperDumpFASTQ     1600944075_hippocampus.pbtech_36366_canu``

**Comment by brianwalenz** [comment]
Specifically,  `ATCC3626.report` in the main directory, `meryl-count.000001.out` and `meryl-process.000001.out`.

**Comment by drs357** [comment]
Haha sorry about that. This is meryl-count.000001.out:
``Found perl:
   /home/drs4001/miniconda3/envs/canu/bin/perl
   This is perl 5, version 30, subversion 3 (v5.30.3) built for x86_64-linux-thread-multi

Found java:
   /home/drs4001/miniconda3/envs/canu/bin/java
   openjdk version "11.0.8-internal" 2020-07-14

Found canu:
   /pbtech_mounts/homes054/drs4001/miniconda3/envs/canu/bin/canu
   Canu 2.0

Running job 1 based on command line options.
sqStore_loadMetadata()-- Using 'raw' 0x01 reads.
Enabling 4 threads.

Counting 227 (estimated) million canonical 16-mers from 1 input file:
    canu-seqStore: ../../ATCC3626.seqStore


SIMPLE MODE
-----------

  16-mers
    -> 4294967296 entries for counts up to 65535.
    -> 64 Gbits memory used

  238340066 input bases
    -> expected max count of 953360, needing 5 extra bits.
    -> 20 Gbits memory used

  10 GB memory needed


COMPLEX MODE
------------

prefix     # of   struct   kmers/    segs/      min     data    total
  bits   prefix   memory   prefix   prefix   memory   memory   memory
------  -------  -------  -------  -------  -------  -------  -------
     1     2  P   110 kB   113 MM  7047  S   128 kB   880 MB   880 MB
     2     4  P   107 kB    56 MM  3410  S   256 kB   852 MB   852 MB
     3     8  P   103 kB    28 MM  1648  S   512 kB   824 MB   824 MB
     4    16  P   101 kB    14 MM   796  S  1024 kB   796 MB   796 MB
     5    32  P    99 kB  7273 kM   384  S  2048 kB   768 MB   768 MB
     6    64  P    99 kB  3636 kM   185  S  4096 kB   740 MB   740 MB
     7   128  P   103 kB  1818 kM    89  S  8192 kB   712 MB   712 MB
     8   256  P   114 kB   909 kM    43  S    16 MB   688 MB   688 MB
     9   512  P   140 kB   454 kM    21  S    32 MB   672 MB   672 MB
    10  1024  P   192 kB   227 kM    10  S    64 MB   640 MB   640 MB  Best Value!
    11  2048  P   304 kB   113 kM     5  S   128 MB   640 MB   640 MB
    12  4096  P   544 kB    56 kM     3  S   256 MB   768 MB   768 MB
    13  8192  P  1024 kB    28 kM     2  S   512 MB  1024 MB  1025 MB
    14    16 kP  1920 kB    14 kM     1  S  1024 MB  1024 MB  1025 MB
    15    32 kP  3840 kB  7274  M     1  S  2048 MB  2048 MB  2051 MB
    16    64 kP  7680 kB  3637  M     1  S  4096 MB  4096 MB  4103 MB
    17   128 kP    15 MB  1819  M     1  S  8192 MB  8192 MB  8207 MB
    18   256 kP    30 MB   910  M     1  S    16 GB    16 GB    16 GB


FINAL CONFIGURATION
-------------------

Configured complex mode for 0.625 GB memory per batch, and up to 1 batch.

kmerCountFileWriter()-- Creating './ATCC3626.01.meryl.WORKING' for 16-mers, with prefixSize 10 suffixSize 22 numFiles 64
Loading kmers from '../../ATCC3626.seqStore' into buckets.
Used 0.280 GB out of 2.000 GB to store         2268 kmers.
Used 0.405 GB out of 2.000 GB to store     48755324 kmers.
Used 0.530 GB out of 2.000 GB to store     97558636 kmers.
Used 0.655 GB out of 2.000 GB to store    146300237 kmers.
Used 0.780 GB out of 2.000 GB to store    195062226 kmers.

Writing results to './ATCC3626.01.meryl.WORKING', using 4 threads.
finishIteration()--

Finished counting.
Bye.``

**Comment by drs357** [comment]
meryl process:

Found perl:
   /home/drs4001/miniconda3/envs/canu/bin/perl
   This is perl 5, version 30, subversion 3 (v5.30.3) built for x86_64-linux-thread-multi

Found java:
   /home/drs4001/miniconda3/envs/canu/bin/java
   openjdk version "11.0.8-internal" 2020-07-14

Found canu:
   /pbtech_mounts/homes054/drs4001/miniconda3/envs/canu/bin/canu
   Canu 2.0

Running job 1 based on command line options.
Enabling 4 threads.
kmerCountFileWriter()-- Creating 'ATCC3626.ms16.WORKING' for 16-mers, with prefixSize 12 suffixSize 20 numFiles 64
Bye.
Enabling 4 threads.
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
For word-frequency 0.000000, found threshold 15
Bye.
Enabling 80 threads.

**Comment by drs357** [comment]
report:
[CORRECTION/READS]
--
-- In sequence store './ATCC3626.seqStore':
--   Found 20822 reads.
--   Found 238340066 bases (62.72 times coverage).
--    
--    G=238340066                        sum of  ||               length     num
--    NG         length     index       lengths  ||                range    seqs
--    ----- ------------ --------- ------------  ||  ------------------- -------
--    00010        37987       515     23869907  ||       1000-3253         4506|---------------------------------------------------------------
--    00020        31012      1214     47695131  ||       3254-5507         3209|---------------------------------------------
--    00030        26146      2054     71526437  ||       5508-7761         2406|----------------------------------
--    00040        22119      3046     95342448  ||       7762-10015        1853|--------------------------
--    00050        18586      4222    119175873  ||      10016-12269        1553|----------------------
--    00060        15340      5635    143008821  ||      12270-14523        1235|------------------
--    00070        12126      7375    166843165  ||      14524-16777        1097|----------------
--    00080         8972      9648    190680387  ||      16778-19031         898|-------------
--    00090         5613     12969    214510236  ||      19032-21285         763|-----------
--    00100         1000     20821    238340066  ||      21286-23539         637|---------
--    001.000x               20822    238340066  ||      23540-25793         535|--------
--                                               ||      25794-28047         471|-------
--                                               ||      28048-30301         336|-----
--                                               ||      30302-32555         314|-----
--                                               ||      32556-34809         231|----
--                                               ||      34810-37063         196|---
--                                               ||      37064-39317         135|--
--                                               ||      39318-41571         120|--
--                                               ||      41572-43825          76|--
--                                               ||      43826-46079          68|-
--                                               ||      46080-48333          41|-
--                                               ||      48334-50587          37|-
--                                               ||      50588-52841          31|-
--                                               ||      52842-55095          18|-
--                                               ||      55096-57349          10|-
--                                               ||      57350-59603           7|-
--                                               ||      59604-61857           9|-
--                                               ||      61858-64111           8|-
--                                               ||      64112-66365           4|-
--                                               ||      66366-68619           1|-
--                                               ||      68620-70873           2|-
--                                               ||      70874-73127           2|-
--                                               ||      73128-75381           5|-
--                                               ||      75382-77635           1|-
--                                               ||      77636-79889           0|
--                                               ||      79890-82143           0|
--                                               ||      82144-84397           1|-
--                                               ||      84398-86651           1|-
--                                               ||      86652-88905           2|-
--                                               ||      88906-91159           0|
--                                               ||      91160-93413           0|
--                                               ||      93414-95667           0|
--                                               ||      95668-97921           1|-
--                                               ||      97922-100175          1|-
--                                               ||     100176-102429          0|
--                                               ||     102430-104683          0|
--                                               ||     104684-106937          0|
--                                               ||     106938-109191          0|
--                                               ||     109192-111445          0|
--                                               ||     111446-113699          1|-
--

**Comment by drs357** [comment]
precompute outs:
Running job 1 based on command line options.
Dumping reads from 1 to 18000 (inclusive).
Starting mhap precompute.
Unrecognized option: -d64
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
mv: cannot stat `/athena/masonlab/scratch/projects/metagenomics/vartanian_lab_ms_study/analysis/canuATCC3626/correction/1-overlapper/blocks/000001.dat': No such file or directory
Mhap failed.

**Comment by drs357** [comment]
Running job 2 based on command line options.
Dumping reads from 18001 to 36000 (inclusive).
Starting mhap precompute.
Unrecognized option: -d64
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
mv: cannot stat `/athena/masonlab/scratch/projects/metagenomics/vartanian_lab_ms_study/analysis/canuATCC3626/correction/1-overlapper/blocks/000002.dat': No such file or directory
Mhap failed.

**Comment by drs357** [comment]
Running job 3 based on command line options.
Dumping reads from 36001 to 49119 (inclusive).
Starting mhap precompute.
Unrecognized option: -d64
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
mv: cannot stat `/athena/masonlab/scratch/projects/metagenomics/vartanian_lab_ms_study/analysis/canuATCC3626/correction/1-overlapper/blocks/000003.dat': No such file or directory
Mhap failed.

**Comment by skoren** [comment]
A couple of issues in the output you posted:
  - We don't recommend using conda for installation, download the Linux package directly from the releases page instead. The error being reported in your precompute logs shows me you're not actually running Canu 2.0 but likely 1.6 or similar.
  - You have output from the next step (precompute) but your report/logs show that Canu stopped before that. Are you running multiple times with the same prefix/folder? Clean up any folders you have completely (e.g. canuATCC3626), and launch once you install as I said above with useGrid=false.

**Comment by skoren** [comment]
Invalid canu install from Conda, re-installation using release binary should fix.
