### ISSUE TITLE
Can I remove repeat and bubble sequence in contigs.fasta?

### ISSUE THREAD

**Issue by xuzhougeng** [marbl/canu#1805]
I use the canu-2.1 to assemble my genome, and I find that in the output sequence, each contig will have the following information,for example

```
>tig00000002 len=3577253 reads=5272 class=contig suggestRepeat=no suggestBubble=no suggestCircular=no trim=0-3577253
```

After I read some related issues, I know that the `suggestBubble=yes` means the contig is a potential alternative allele, and `suggestRepeat` means t hat the contig is  a potential repeat sequences.  

My genome estimated size is about 220Mb, and the size of canu assembly is about 240 Mb which is 10% larger than the estimated one . If I remove  bubble and repeat sequences (about  10 Mb), the remain contig will be almost same to estimated size.

Could I remove these repeat and bubble sequence in downstream analysis ?

Will these sequence affect the Hi-C scaffolding step?

**Comment by skoren** [comment]
You should not remove the repeats, they are legitimate parts of the genome, just repetitive, removing them will mess up downstream steps like polishing/etc. It's probably OK to remove the bubbles or you could use something like purge_dups (see FAQ) to identify/remove bubbles.

**Comment by xuzhougeng** [comment]
@skoren Thanks your quick reply for my question.  When I use the following command to just select the bubbles 

```
seqkit grep -nrp "suggestBubble=yes" contigs.fasta > bubbles.fasta
``` 

I find the bubble sequence include some repeat sequences, e.g. `suggestRepeat=yes suggestBubble=yes`, is this means the contig is a alternate allele to a repeat sequence?  

Do you think it is right for me to remove theses repeat bubble contigs

**Comment by brianwalenz** [comment]
Good question!

It's the other way around.  The `suggestRepeat=yes suggestBubble=yes` contigs are repeats found in bubble (alternate) contigs.  This could either be a true repeat, or a false-positive repeat formed from the two haplotypes.  But in any case, it's still part of the original bubble sequence and can be removed.
