### ISSUE TITLE
trioCanu large data output

### ISSUE THREAD

**Issue by tbrown91** [marbl/canu#1807]
Hi,

I am running canu 2.1 in trio mode for pacbio CLR and illumina reads. When I run with "useGrid=true" the mhap files in correction/1-overlapper for both Maternal and paternal get really big. The first time I ran it it created 70Tb before we reached the limit of our cluster quota and it crashed. It seems the mhap.WORKING and mhap.ovb.WORKING files are getting very large (~250G) before reaching the .ovb and .oc files. Even now running using "useGrid=false" I still have 18Tb accumulated and it is taking a very long time. I have included the parameters used below that I got from vgp assembly pipeline: https://github.com/VGP/vgp-assembly/tree/master/pipeline/triocanu

Any help would be greatly appreciated, as I don't think I am going to be able to run triocanu on our cluster at this rate.

Many thanks,

Tom

```$CANU -p asm -d ../../assembly/triocanu genomeSize=3g -haplotypePaternal ../../data/illumina/dad/*.fastq.gz -haplotypeMaternal ../../data/illumina/mum/*.fastq.gz -pacbio-raw ../../processed-data/pacbio/lofi/L*fasta.gz correctedErrorRate=0.035 utgOvlErrorRate=0.065 trimreadsCoverage=2 trimReadsOverlap=500 hapUnknownFraction=0.01 corMhapSensitivity=normal corMinCoverage=0```

**Comment by skoren** [comment]
It seems like either your genome is very repetitive or you have higher coverage than the VGP parameters are set for. How much coverage do you have per haplotype? If it's over 50x remove ```corMhapSensitivity=normal corMinCoverage=0```. There are also some suggestions for parameters on the FAQ to reduce space usage you can try as well.

**Comment by tbrown91** [comment]
I have around 60X CLR coverage - so 30X per haplotype and around 60X illumina coverage for the parents. I will try the arguments in the FAQ now, do you think I should remove the corMhapSensitivity and corMinCoverage arguments?

**Comment by skoren** [comment]
No 30x is quite low so I'd leave those parameters in.

**Comment by tbrown91** [comment]
sorry, each mhap working file was getting up to 250Gb in size and there were around 250 jobs for maternal and 150 for paternal. I had to remove quite a lot of data just to create some space on the cluster.

**Comment by skoren** [comment]
Ah that makes more sense, OK, then the FAQ parameters should be what you want. The other parameter that can help here (depending on your cluster) are the staging options (https://canu.readthedocs.io/en/latest/parameter-reference.html?highlight=staging#file-staging). If the mhap.WORKING files are much larger than the mhap.ovl files (and they usually are), the staging options will write them to local scratch on each node when your nodes have local disk, then only copy back the final smaller ovl file. This can save space and time since the shared disk doesn't have to deal with the intermediate outputs.

**Comment by tbrown91** [comment]
Thank you, I will give this a go and see how it performs over the weekend.

**Comment by skoren** [comment]
Idle
