### ISSUE TITLE
Will running canu-correct on a bacterial genome be any quicker in a Grid than a large VM?

### ISSUE THREAD

**Issue by zmunro** [marbl/canu#1809]
I am trying to get canu-correct to run as quickly as possible on ONT MinION data. So far I am downsampling the input file so that it has less spikey coverage, and also tweaked canu's parameters to the following:
```
canu -correct -p reads -d /mnt/large-disk genomeSize=${genomeSize}m useGrid=false \
      correctedErrorRate=0.105 corMaxEvidenceErate=0.15 maxThreads=60 maxMemory=100 stopOnLowCoverage=0 \
      corMhapFilterThreshold=0.0000000002 corMhapOptions="--threshold 0.80 --num-hashes 512 \
      --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 \
      --repeat-idf-scale 50" mhapBlockSize=500 ovlMerDistinct=0.975 \
      -nanopore-raw raw_reads.fastq 1>&2
```
I have been running this on VMs with 240Gb memory, and 60cpu.
It has been taking anywhere between 30 minutes and 4 hours. I am hoping to get this down so that it is routinely under 20 minutes. Will running this on a compute grid with Slurm make it go any faster?

**Comment by skoren** [comment]
Certainly a grid would be faster than a single node, assuming the grid lets you get access to >60cores at a time consistently. You can also speed it up by using corMhapSensitivity=low rather than you custom set (or drop hashes from 512 to 256). Lastly, on a single node, you could run in a ram disk which may also speed it up.

**Comment by zmunro** [comment]
I've tested it in a ramdisk and there is a small speedup, but it is hard to have access to a VM that has a large enough memory that you can devote 1TB to a ramdisk as that is how much space is sometimes needed.
