### ISSUE TITLE
How does Canu runtime scale?

### ISSUE THREAD

**Issue by ktingey** [marbl/canu#181]
Hello there,

I see in the FAQ you have some estimated run times, but I don't see a specified coverage.  I'm wondering how Canu runtime scales based on coverage and genome size?  Of course RAM and number of cores play a role in the overall calculation, but I assume there is some formula... In the end I need to submit an accurate proposal for a 1.4Gb genome with 60x coverage on a machine with unto 12TB of RAM.  For every 48GB I'll be issued 1 core.  Any additional information would be greatly appreciated.

Best,

Kyle

**Comment by brianwalenz** [comment]
Is this PSC 'Bridges'?  You'll be better off using the normal 'RSM' nodes.  The 'overlapping' phases will appreciate the extra cores, and the large memory phases (probably) won't benefit from more than 128gb memory.

No formula.  Run time (and disk usage) can be very dependent on genome structure.  More repeats mean more overlaps, and so more processing to weed out false from true overlaps.  Polymorphism and bad data can result in multiple attempts at assembly.

Our human test data is ~50x and ~100x.  Budgeting for 30k seems conservative.  Keep in mind that human is a _very_ well behaved assembly.  It's nearly the easiest assembly to do.

**Comment by ktingey** [comment]
Thanks for the quick response.  I am on bridges, so I appreciate the node recommendation.  The additional information on the test data will go a long way in submitting my proposal.

Thanks Again,

Kyle
