### ISSUE TITLE
HiCanu assembly

### ISSUE THREAD

**Issue by wyim-pgl** [marbl/canu#1815]
Hi Sergey,
Do we
For HiCanu, do we need to use CCS from HiFi sequencing or subreads?
Thanks.

Won

**Comment by skoren** [comment]
You need to convert subreads to the ccs version (which outputs a ccs.bam file) using pacbio's tools first. The subreads file are just regular PacBio CLR reads before consensus.

**Comment by wyim-pgl** [comment]
Thanks. Just confused with this message "-- Found trimmed raw PacBio HiFi reads in the input files."

**Comment by skoren** [comment]
Yes, HiFi reads are considered "raw" in that their form within the assembly is in homopolymer-compressed space. By default they aren't trimmed though or corrected in the traditional Canu sense.

**Comment by wyim-pgl** [comment]
Makes sense.
Thanks.

**Comment by wyim-pgl** [comment]
Do you have any recommendations option for the autotetraploidy genome ?

**Comment by skoren** [comment]
No, defaults should be reasonable, assuming there is enough divergence between haplotypes/copies you will get 4x the original genome size in the assembly. It does mean you probably want higher coverage to get enough data for each haplotype and may want to increase maxInputCoverage over the default of 50 (maxInputCoverage=100 for example) assuming you're setting the genome size to the haploid (1/4) size.

**Comment by skoren** [comment]
Genome size isn't used for much so you can use either. It depends what you want canu to use to report your NG50 statistics with. If you do use the haploid genome size, set the maxInputCoverage as I suggested.

**Comment by wyim-pgl** [comment]
Thanks.
