### ISSUE TITLE
No .gfa output file when running HiCanu 2.1?

### ISSUE THREAD

**Issue by VManning** [marbl/canu#1819]
Hi,

I had a successful HiCanu run using v2.1. Yah! I noticed that there are fewer output files than with v2.0, including no .gfa file (or other unitigs. files.) Are they located elsewhere or are they no longer generated? Can I generate a .gfa from some of the other output data?

Thanks,

Viola

**Comment by skoren** [comment]
Yes, these were deprecated (see #1786). You can use the best edges gfa (found in unitigging/4-unitigger) which will be a more accurate representation of how the assembly is built. Circular contigs are identified in the fasta def lines along with their trim points.

**Comment by VManning** [comment]
Thank you. Sorry, I should have looked.
