### ISSUE TITLE
Canu genome assembly size double than expected size

### ISSUE THREAD

**Issue by farhan-phd** [marbl/canu#1820]
Dear Canu developer,

I just finished my first genome draft of the canu assembly but the genome assembled is the almost double size (1.7 Gb) (evaluated by quast) than that expected/calculated using GenomeScope (0.9 Gb). Could you please have a look at my commands and parameters what could be the major problem? Please see the details below:

Assembly commads and parametres:
canu-2.1/bin/canu -p Asta-latifasciata -d canu-01-assembly genomeSize=1g -pacbio-raw /00-raw-data_pacbio/ala-1b-Ge-Mus-M_PacBio.fastq correctedErrorRate=0.035 utgOvlErrorRate=0.065 trimReadsCoverage=2 trimReadsOverlap=500 > std.error 2> std.out &

Assembly corrected and trimmed reads (report) and genomeScope output attached below

[Asta.report.txt](https://github.com/marbl/canu/files/5391876/Asta.report.txt)
[GenomeScope_statistic.docx](https://github.com/marbl/canu/files/5391882/GenomeScope_statistic.docx)

Note: This assembled genome is of a cichlid fish with an extra (B) chromosome, which sequences are mainly duplicated from Autosomes. Is there any possibility that this extra chromosome might have caused this issue of genome size?
Many thanks in advance,
Best regards,
Farhan

**Comment by skoren** [comment]
It's likely you're getting haplotypes separated in your assembly. I'd suggest using purge_dups as listed on the FAQ to remove the redundancy in the assembly. You can then use tools like KAT or Merqury to check if the assembly is indeed capturing both haplotypes and/or if purge_dups is working correctly.

**Comment by jenny315** [comment]
Dear HICanu developer,

I use HICANU to assemble D. melanogaster HiFi data [available from NCBI at PRJNA573706 (SRR10238607,
median: 24.4 kbp mean: 24.4 kbp)]( genome is 150m), the genome assembled is the almost double size (326m). It's likely i'm  getting haplotypes separated in my assembly. Could I also use the above method to solve this problem (purge_dups, then KAT or Merqury)?

Assembly commads and parametres:
canu  -d  ./  -p  dmela_asm  genomeSize=150m  -pacbio-hifi  dmela_hifi.fastq.gz

Assemble report:
[dmela_asm_1.report.txt](https://github.com/marbl/canu/files/5463036/dmela_asm_1.report.txt)

BUSCO result below:
[short_summary.specific.diptera_odb10.BUSCO.txt](https://github.com/marbl/canu/files/5463059/short_summary.specific.diptera_odb10.BUSCO.txt)

2. If I want to get two haplotypes separated in my assembly, what should I do?


Many thanks in advance,
Best regards,
Jenny
