### ISSUE TITLE
Canu with HiFi correction Failed

### ISSUE THREAD

**Issue by francicco** [marbl/canu#1821]
Hi,

I'm running CANU using the hifi flag:

`canu -correct useGrid=false -p $ASSPREFIX -d $GENOMEDIR -pacbio-hifi`

I got this error.

```
-- Finished on Sat Oct 17 17:21:19 2020 (one second) with 1608401.046 GB free disk space
----------------------------------------
--  segments   memory batches
--  -------- -------- -------
--
--  For 0 reads with 0 bases, limit to 0 batches.
--  Will count kmers using  jobs, each using  GB and 7 threads.
--
-- Finished stage 'merylConfigure', reset canuIteration.

ABORT:
ABORT: canu snapshot v2.2-development +64 changes (r10173 d51c25a5f47721a51f16e7ae2e585427507c519f)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to find the number of jobs in 'correction/0-mercounts/meryl-count.sh'.
ABORT:
```

What's going on?

Cheers
F

**Comment by skoren** [comment]
You're not supposed to run correction on HiFi data, don't specify -correct.

**Comment by francicco** [comment]
Hi @skoren,

so just trimming or directly assemble?

Thanks
F

**Comment by skoren** [comment]
The default doesn't do trimming as it's not necessary unless there was some issue with your library or you have barcoded the sequencing run that you didn't remove. You can try both, run just canu not specifying anything or run -untrimmed to turn on trimming.
