### ISSUE TITLE
Modification of non-creatable array value attempted

### ISSUE THREAD

**Issue by jainy** [marbl/canu#1824]
Hi,

I am trying to run assemble PacBio CLR data (~60X). 

I got this error: Modification of non-creatable array value attempted, subscript -1837480591 at ./lib/site_perl/canu/Meryl.pm line 142, <F> line 113543.

This is the command that I have used:
nohup /home/jainy/software/canu-2.0/Linux-amd64/bin/canu -p PT-6198canuasmb -d /ybod2/jainy/Project4/PanTail-6198/CanuAsmb genomeSize=3.1g corOutCoverage=200 batOptions="-dg 3 -db 3 -dr 1.0 -ca 500 -cp 50" corMinCoverage=0 -pacbio /ybod2/jainy/Project4/files.rc.byu.edu/fslg_dnasc/data_transfer/PanTail-6198/PanTail-6198_Pbreads.fastq.gz > /ybod2/jainy/Project4/PanTail-6198/CanuAsmb/PT-6198_asmb_status_1.txt &

Please let me know if you need any other info.

Thank you so much for your help!
Jainy

**Comment by skoren** [comment]
This seems similar to issue #1632 which was fixed in the 2.1 release (there is also an updated Meryl.pm in that issue). I'd suggest trying the 2.1.1 release on your data to see if it fixes the problem.

**Comment by jainy** [comment]
The new version seems to fix the issue, no more error message. Thank you!
