### ISSUE TITLE
errorRate defaults clarification

### ISSUE THREAD

**Issue by kfriesen2** [marbl/canu#183]
Hello,
Can you give some clarification about the default errorRate for PacBio reads? What is the recommended default value, and will it be set in the code if no value is specified? I am having trouble reconciling the documentation.

http://canu.readthedocs.io/en/stable/parameter-reference.html#parameter-reference
 errorRate <**float=0.01**>
 * The expected error rate, as fraction error, in the corrected reads, set by default based on data type, typically **not changed by the user**.

https://media.readthedocs.org/pdf/canu/latest/canu.pdf (p12)
 * This is the parameter errorRate. Currently, the defaults are **0.025** for PacBio sequences and 0.05
 for Oxford Nanpore sequences.

**Comment by skoren** [comment]
The defaults are set by datatype so 0.025 (2.5%) is accurate for PacBio sequences.

**Comment by kfriesen2** [comment]
So, will CANU auto select this value if no value is submitted with the command?

________________________________

**Comment by skoren** [comment]
Yes, you don't need to set the value.
