### ISSUE TITLE
Combine CLR and HiFi reads

### ISSUE THREAD

**Issue by libby-natola** [marbl/canu#1833]
Hello,

My sequencer returned both CLR and HiFi reads for one of my samples. I'd hate to lose any data, is there a way to run canu on both kinds of reads at once? Could I correct the CLR, run the CLR and HiFi trimming separately, and input both of the resulting fastq files in the assembly step, in which case what option would I use a similar structure to using nanopore and pacbio data only use the  -pacbio-raw pacbio.fastq.gz \ -pacbio-hifi pacbiohifi.fasta.gz options?

Thanks for any advice on this topic!

Best,

Libby

**Comment by skoren** [comment]
No way to combine the data types, they are too different in terms of quality. The corrected CLR data won't be phase/haplotype preserving either so it will just confuse assembly. I'd suggest assembling only HiFi and then using CLR after scaffolding to gap fill instead.
