### ISSUE TITLE
haplotypes separated

### ISSUE THREAD

**Issue by jenny315** [marbl/canu#1836]
Dear HICANU developer,

I am learning to use HiCANU for later genomic assembly.  I started with D. melanogaster HiFi data [available from NCBI at PRJNA573706 (SRR10238607,median: 24.4 kbp mean: 24.4 kbp), same as the HIFI data in "HiCANU: accurate assembly of segmental duplications, satellites, and allelic variants from high-fidelity long reads" ]

1.  I use HICANU to assemble D. melanogaster HiFi data( genome is 150m), the genome assembled is the almost double size (326m). It's likely i'm getting haplotypes separated in my assembly. Could I also use the above method [https://github.com/marbl/canu/issues/1820  :(purge_dups, then KAT or Merqury) ]to solve this problem when use HICANU?

  Assembly commads and parametres:
```
canu -d ./ -p dmela_asm genomeSize=150m -pacbio-hifi dmela_hifi.fastq.gz
```
  Assemble report below:
    [dmela_asm_1.report.txt](https://github.com/marbl/canu/files/5464374/dmela_asm_1.report.txt)

  BUSCO result below:
    [short_summary.specific.diptera_odb10.BUSCO.txt](https://github.com/marbl/canu/files/5464378/short_summary.specific.diptera_odb10.BUSCO.txt)

2. If I want to get two haplotypes separated in my assembly later, and genome heterozygosity is about 0.8%, what should I do when use HICANU? While CANU recommends using the `batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50` parameter to separate two haplotypes as much as possible, and then remove duplication. Does this method apply to HICANU?

Many thanks in advance,
Best regards,
Jenny

**Comment by skoren** [comment]
1. Yes, you can run purge_dups on the assembly, that will address the duplicated genes in your BUSCO report. You could also separate the bubbles from the contigs and evaluate those independently using BUSCO as the contigs are only 180mb from the report (the def line in the fasta file tells you which is a bubble and which is a contig) but I expect purge_dups will do a more complete job than the bubble detection does.

2. No need to modify the parameters for HiFi haplotype separation, 0.8% is very high as far as HiFi data is concerned so you'll get the haplotypes separated with defaults.
