### ISSUE TITLE
output fasta file empty 

### ISSUE THREAD

**Issue by maysonlin** [marbl/canu#1837]
Hi, by following up from my last post a week ago  [#1822 ]("https://github.com/marbl/canu/issues/1822), I added "useGrid=false" on my script, so the job will run on the machine. However, the output fasta file is [empty](https://ibb.co/ZMZKNMS). Here is my [asm.report](https://ibb.co/RSBzNtP), my log file

```
--Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '11.0.1' (from '/home/applications/spack/applications/gcc-8.2.0/jdk-11.0.1-ref6fpqme4viq7dehz4b3lk3mow2mba4/bin/java') without -d64 support.
-- Detected gnuplot version '5.2 patchlevel 5   ' (from 'gnuplot') and image format 'png'.
-- Detected 16 CPUs and 126 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /home/share/slurm/19.05.3/bin/sinfo.
-- Grid engine and staging disabled per useGrid=false option.
--
--                                (tag)Concurrency
--                         (tag)Threads          |
--                (tag)Memory         |          |
--        (tag)             |         |          |       total usage      algorithm
--        -------  ----------  --------   --------  --------------------  -----------------------------
-- Local: meryl     24.000 GB    8 CPUs x   2 jobs    48.000 GB  16 CPUs  (k-mer counting)
-- Local: hap       12.000 GB   16 CPUs x   1 job     12.000 GB  16 CPUs  (read-to-haplotype assignment)
-- Local: cormhap   32.000 GB   16 CPUs x   1 job     32.000 GB  16 CPUs  (overlap detection with mhap)
-- Local: obtovl    16.000 GB   16 CPUs x   1 job     16.000 GB  16 CPUs  (overlap detection)
-- Local: utgovl    16.000 GB   16 CPUs x   1 job     16.000 GB  16 CPUs  (overlap detection)
-- Local: cor       16.000 GB    4 CPUs x   4 jobs    64.000 GB  16 CPUs  (read correction)
-- Local: ovb        4.000 GB    1 CPU  x  16 jobs    64.000 GB  16 CPUs  (overlap store bucketizer)
-- Local: ovs       16.000 GB    1 CPU  x   7 jobs   112.000 GB   7 CPUs  (overlap store sorting)
-- Local: red       32.000 GB    8 CPUs x   2 jobs    64.000 GB  16 CPUs  (read error detection)
-- Local: oea        8.000 GB    1 CPU  x  15 jobs   120.000 GB  15 CPUs  (overlap error adjustment)
-- Local: bat      126.000 GB   16 CPUs x   1 job    126.000 GB  16 CPUs  (contig construction with bogart)
-- Local: cns        -.--- GB    8 CPUs x   - jobs     -.--- GB   - CPUs  (consensus)
--
-- Found trimmed raw PacBio HiFi reads in the input files.
--
-- Generating assembly 'asm' in '/scratch/slin023/PhormiaPacBio':
--    - assemble HiFi reads.
--
-- Parameters:
--
--  genomeSize        650000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.0000 (  0.00%)
--    obtOvlErrorRate 0.0250 (  2.50%)
--    utgOvlErrorRate 0.0100 (  1.00%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.0000 (  0.00%)
--    obtErrorRate    0.0250 (  2.50%)
--    utgErrorRate    0.0100 (  1.00%)
--    cnsErrorRate    0.0500 (  5.00%)
--
-- Bye.
```

My [script](https://ibb.co/pvPMtFK), can you help me figure what is going on, please? Thank you.

**Comment by skoren** [comment]
Looks like none of your posted links work. 

When you launched with useGrid=false, did you do so in a new empty folder or did you re-use the previous one? If it was reused you may have collided two runs (since the original run you had was working just running on the grid).

**Comment by maysonlin** [comment]
my apology let me give you the link
My output file:https://i.ibb.co/CHrvWH6/Screen-Shot-2020-10-30-at-2-05-00-PM.png
My asm.report:https://i.ibb.co/sP6yCcQ/Screen-Shot-2020-10-30-at-2-08-55-PM.png
My script: https://i.ibb.co/bg3CS9v/Screen-Shot-2020-10-30-at-2-13-31-PM.png
This is the folder I have every data in there just FYI, "m64140_200721_055642.Q20.fastq" is input file, "hicanu.sh" is my canu script
So you suggest I open up different folder to run it?

**Comment by maysonlin** [comment]
this is canu.log folder:"https://i.ibb.co/ZJm7wTP/Screen-Shot-2020-10-30-at-3-16-16-PM.png"
"untigging folder" is empty
"asmseqStore" folder:"https://i.ibb.co/zrSwfP9/Screen-Shot-2020-10-30-at-3-18-04-PM.png"

**Comment by maysonlin** [comment]
> Looks like none of your posted links work.
> 
> When you launched with useGrid=false, did you do so in a new empty folder or did you re-use the previous one? If it was reused you may have collided two runs (since the original run you had was working just running on the grid). Post the full contents of the run folder and any subfolders it has.


this is canu.log folder:"https://i.ibb.co/ZJm7wTP/Screen-Shot-2020-10-30-at-3-16-16-PM.png"
"untigging folder" is empty
"asmseqStore" folder:"https://i.ibb.co/zrSwfP9/Screen-Shot-2020-10-30-at-3-18-04-PM.png"
My output file:https://i.ibb.co/CHrvWH6/Screen-Shot-2020-10-30-at-2-05-00-PM.png
My asm.report:https://i.ibb.co/sP6yCcQ/Screen-Shot-2020-10-30-at-2-08-55-PM.png
My script: https://i.ibb.co/bg3CS9v/Screen-Shot-2020-10-30-at-2-13-31-PM.png
This is the folder I have every data in there just FYI, "m64140_200721_055642.Q20.fastq" is input file, "hicanu.sh" is my canu script

**Comment by skoren** [comment]
I'm still blocked from accessing your png files, you should be able to attach them directly to the issue instead. It sounds like this may be a collision of two runs. Post the full canu command you're using (the hicanu.sh script).

**Comment by maysonlin** [comment]
> I'm still blocked from accessing your png files, you should be able to attach them directly to the issue instead. It sounds like this may be a collision of two runs. Post the full canu command you're using (the hicanu.sh script).

`#!/bin/bash
#SBATCH --qos pq_mdegenna 
#SBATCH --account iacc_mdegenna   
#SBATCH --partition centos7_16C_128G 
#SBATCH -n 11
#SBATCH -N 1
#SBATCH --output=log

. $MODULESHOME/../global/profile.modules
module load jdk-11.0.1-gcc-8.2.0-ref6fpq
module load gnuplot-5.2.5-gcc-8.2.0-ftntrbx 
module load canu-2.1-gcc-8.2.0 

## Run canu to assemble HiFi sequencing
canu -p asm -d /scratch/slin023/PhormiaPacBio genomeSize=650.0m useGrid=false -pacbio-hifi /scratch/slin023/PhormiaPacBio/m64140_200721_055642.Q20.fastq`

**Comment by maysonlin** [comment]
> I'm still blocked from accessing your png files, you should be able to attach them directly to the issue instead. It sounds like this may be a collision of two runs. Post the full canu command you're using (the hicanu.sh script).

Hi, I tried to work on different folder now, it works fine, and the output looks fine. Thank you for your help
