### ISSUE TITLE
meryl taking a long time

### ISSUE THREAD

**Issue by tom-brekke** [marbl/canu#1839]
Hello,
I've been running HiCanu2.1.1 on a SLURM cluster for a murid rodent genome with ~35x coverage. 
Raw data: 4.8M reads, N50 of 18kb, 88B bases.

The meryl step was submitted as 4 separate tasks which were all killed by SLURM when they hit my time limit of 7 days. I can easily request to increase my limit, but I was under the impression that the entire Canu run should take about a week and so was surprised that one step would take over 7 days. 

Here is my call:

canu \\
-p take03 \\
-d "~/Assemblies/take03" \\
genomeSize=2.5G \\
merylThreads=40 \\
gridOptions="--partition=highmem" \\
gridOptionsmeryl="--partition=htc" \\
gridOptionscormhap="--partition=highmem" \\
gridOptionsobtovl="--partition=highmem" \\
gridOptionsutgovl="--partition=highmem" \\
gridOptionscor="--partition=highmem" \\
gridOptionsovb="--partition=htc" \\
gridOptionsovs="--partition=highmem" \\
gridOptionsred="--partition=highmem" \\
gridOptionsoea="--partition=htc" \\
gridOptionsbat="--partition=highmem" \\
gridOptionscns="--partition=htc" \\
-pacbio-hifi $READS

Where $READS contains the path to my reads.

Is 7+ days expected for meryl? If so, any estimate on how long I should let it run for?
This is the second time that meryl has hit my time limit, and for this run I increased merylThreads from default to 40. Was that maybe the wrong thing to do?

Thanks in advance, and attached is the canu.out file contents.
Best, 
Tom

[canu.01.out.txt](https://github.com/marbl/canu/files/5500336/canu.01.out.txt)

**Comment by skoren** [comment]
Typically meryl takes less than a couple of hours on a 30x human on our cluster so 7 days is way too long. It is possible it's getting I/O bound, in that case it may be better to make more small jobs on different nodes using fewer cores. Set merylThreads to 8 and merylMemory=20. If you can, also track the CPU/IO usage of the jobs while they run.

**Comment by tom-brekke** [comment]
That seems to have done it. 16 meryl jobs were submitted, each took about 3 minutes and it was done. 
Thank you!
-Tom
