### ISSUE TITLE
Can Canu assemble multiple contigs ?

### ISSUE THREAD

**Issue by Johnsonzcode** [marbl/canu#1848]
Thank you for your excellent work first !

I got different contigs generated by several assemblier from Pacbio CLR, Pacbio HiFi, and nanopore, and I am wondering Can Canu assemble these contigs and get best part of each contig even correct each other, if Canu do, How I set the command?

**Comment by skoren** [comment]
Canu by default has a max read limit of 2mb. Reads longer than this will be broken. You can recompile to use larger reads but we don't recommend merging assemblies in general. The contigs are missing context of the original reads and can easily lead to mis-assemblies. I would instead recommend using the HiFi assembly as the base and then using CLR/nanopore data to gap fill/scaffold/correct that assembly.
