### ISSUE TITLE
SGE cluster with no consumable memory  => can't configure for SGE

### ISSUE THREAD

**Issue by bwlang** [marbl/canu#185]
Our cluster is pretty simple... 4G and 1Cpu per slot.

I'm thinking of modifying 
https://github.com/marbl/canu/blob/88c4a43e11aa953621c12a7dfda36425082900b3/src/pipelines/canu/Grid_SGE.pm#L168

to add an option to extract the slot consumable resource and multiply by a command line option (in my case 4G) to handle this situation?
PR welcome?

-- WARNING:  Couldn't determine the SGE resource to request memory.
-- WARNING:  No valid choices found!  Find an appropriate complex name (qconf -sc) and set:
-- WARNING:    gridEngineMemoryOption="-l \<name\>=MEMORY"
<pre>
qconf -sc
#name               shortcut   type        relop requestable consumable default  urgency
#----------------------------------------------------------------------------------------
arch                a          RESTRING    ==    YES         NO         NONE     0
calendar            c          RESTRING    ==    YES         NO         NONE     0
cpu                 cpu        DOUBLE      >=    YES         NO         0        0
display_win_gui     dwg        BOOL        ==    YES         NO         0        0
h_core              h_core     MEMORY      <=    YES         NO         0        0
h_cpu               h_cpu      TIME        <=    YES         NO         0:0:0    0
h_data              h_data     MEMORY      <=    YES         NO         0        0
h_fsize             h_fsize    MEMORY      <=    YES         NO         0        0
h_rss               h_rss      MEMORY      <=    YES         NO         0        0
h_rt                h_rt       TIME        <=    YES         NO         0:0:0    0
h_stack             h_stack    MEMORY      <=    YES         NO         0        0
h_vmem              h_vmem     MEMORY      <=    YES         NO         0        0
hostname            h          HOST        ==    YES         NO         NONE     0
load_avg            la         DOUBLE      >=    NO          NO         0        0
load_long           ll         DOUBLE      >=    NO          NO         0        0
load_medium         lm         DOUBLE      >=    NO          NO         0        0
load_short          ls         DOUBLE      >=    NO          NO         0        0
m_core              core       INT         <=    YES         NO         0        0
m_socket            socket     INT         <=    YES         NO         0        0
m_topology          topo       RESTRING    ==    YES         NO         NONE     0
m_topology_inuse    utopo      RESTRING    ==    YES         NO         NONE     0
mem_free            mf         MEMORY      <=    YES         NO         0        0
mem_total           mt         MEMORY      <=    YES         NO         0        0
mem_used            mu         MEMORY      >=    YES         NO         0        0
min_cpu_interval    mci        TIME        <=    NO          NO         0:0:0    0
np_load_avg         nla        DOUBLE      >=    NO          NO         0        0
np_load_long        nll        DOUBLE      >=    NO          NO         0        0
np_load_medium      nlm        DOUBLE      >=    NO          NO         0        0
np_load_short       nls        DOUBLE      >=    NO          NO         0        0
num_proc            p          INT         ==    YES         NO         0        0
qname               q          RESTRING    ==    YES         NO         NONE     0
rerun               re         BOOL        ==    NO          NO         0        0
s_core              s_core     MEMORY      <=    YES         NO         0        0
s_cpu               s_cpu      TIME        <=    YES         NO         0:0:0    0
s_data              s_data     MEMORY      <=    YES         NO         0        0
s_fsize             s_fsize    MEMORY      <=    YES         NO         0        0
s_rss               s_rss      MEMORY      <=    YES         NO         0        0
s_rt                s_rt       TIME        <=    YES         NO         0:0:0    0
s_stack             s_stack    MEMORY      <=    YES         NO         0        0
s_vmem              s_vmem     MEMORY      <=    YES         NO         0        0
seq_no              seq        INT         ==    NO          NO         0        0
slots               s          INT         <=    YES         YES        1        1000
swap_free           sf         MEMORY      <=    YES         NO         0        0
swap_rate           sr         MEMORY      >=    YES         NO         0        0
swap_rsvd           srsv       MEMORY      >=    YES         NO         0        0
swap_total          st         MEMORY      <=    YES         NO         0        0
swap_used           su         MEMORY      >=    YES         NO         0        0
tmpdir              tmp        RESTRING    ==    NO          NO         NONE     0
virtual_free        vf         MEMORY      <=    YES         NO         0        0
virtual_total       vt         MEMORY      <=    YES         NO         0        0
virtual_used        vu         MEMORY      >=    YES         NO         0        0
</pre>

**Comment by brianwalenz** [comment]
canu is currently configuring itself correctly (based on the qhost report).  The consumable is only used to reserve memory on nodes.

See if:
  gridEngineMemoryOption="-l mem_free=MEMORY"
works.  This will tell SGE to not run a job unless the host has whatever memory the job is requesting currently free.  You also might be able to set it to nothing (literally just "gridEngineMemoryOption="), but I don't remember if we're checking for the string MEMORY anywhere.  If we are, it's easy to fix.

I'd rather make the last suggestion (set to nothing) work instead.  It's a simple way of specifying that canu shouldn't really care about memory usage for grid jobs.

**Comment by bwlang** [comment]
Hi Brian:
gridEngineMemoryOption="-l mem_free=MEMORY" seems to work - and still seems to care about memory
<pre>
-- Found   1 host  with   8 cores and   27 GB memory under Sun Grid Engine control.
-- Found   8 hosts with   8 cores and   63 GB memory under Sun Grid Engine control.
-- Found  13 hosts with  16 cores and   63 GB memory under Sun Grid Engine control.
-- Found   6 hosts with   8 cores and   62 GB memory under Sun Grid Engine control.
-- Found   3 hosts with   8 cores and   31 GB memory under Sun Grid Engine control.
-- Found   4 hosts with  32 cores and  126 GB memory under Sun Grid Engine control.
-- Found   1 host  with   8 cores and   39 GB memory under Sun Grid Engine control.
-- Found   1 host  with  32 cores and  252 GB memory under Sun Grid Engine control.
--
-- Allowed to run under grid control, and use up to   4 compute threads and   13 GB memory for stage 'bogart (unitigger)'.
-- Allowed to run under grid control, and use up to   4 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run under grid control, and use up to   4 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run under grid control, and use up to   4 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run under grid control, and use up to   4 compute threads and    2 GB memory for stage 'read error detection (overlap error adjustment)'.
-- Allowed to run under grid control, and use up to   1 compute thread  and    1 GB memory for stage 'overlap error adjustment'.
-- Allowed to run under grid control, and use up to   4 compute threads and   13 GB memory for stage 'utgcns (consensus'.
-- Allowed to run under grid control, and use up to   1 compute thread  and    3 GB memory for stage 'overlap store parallel bucketizer'.
-- Allowed to run under grid control, and use up to   1 compute thread  and    8 GB memory for stage 'overlap store parallel sorting'.
-- Allowed to run under grid control, and use up to   1 compute thread  and    3 GB memory for stage 'overlapper'.
-- Allowed to run under grid control, and use up to   4 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run under grid control, and use up to   4 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run under grid control, and use up to   4 compute threads and    8 GB memory for stage 'meryl (k-mer counting)'.
-- Allowed to run under grid control, and use up to   2 compute threads and    6 GB memory for stage 'falcon_sense (read correction)'.
-- Allowed to run under grid control, and use up to   4 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run under grid control, and use up to   4 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run under grid control, and use up to   4 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
</pre>

**Comment by brianwalenz** [comment]
There's two places where it uses memory.

The first, shown in your comment, queries the hosts in your grid for their memory/CPU and configures algorithms to fit nicely.  That didn't change.

The second is when jobs are submitted to the grid.  The usual job submission will ask only for CPUs.  Canu also requests that memory be reserved.  That's what you disabled.  The 'overlap store parallel sorting' jobs (in the middle of the list) are going to use 1 CPU and 8gb memory each - so it's possible that your 16 core host will try to run 16 jobs that will need 16 * 8gb = 128gb total memory.

You can force these jobs to request more CPUs (they'll still only use one) but this is just a surrogate for a memory request.  And that was essentially your original idea.  I don't know how easy that will be to include in canu.

**Comment by bwlang** [comment]
I see... I think I may need to discuss turning on the memory as a consumable resource with our cluster admin
