### ISSUE TITLE
Increasing CANU Memory usage. 

### ISSUE THREAD

**Issue by Paula27222** [marbl/canu#1850]
Hello, 

I am running Canu to assemble HiFi reads. My genome is 250 MG long, and it will take a while into being assembled. 
My RAM memory is 50 GB, but when I run HiCanu the software only uses 2.5 GB. 

How could I increase the usage of RAM in order to produce my results faster?

Thanks

**Comment by brianwalenz** [comment]
You can't.  More memory won't necessarily make it faster.  Which stage is being slow?  Paste in both `asm.report` and `canu.out` for more help.

**Comment by Paula27222** [comment]
Hello brian, 

Thanks for your answer. 
Find attached the asm.report. I could not find the file canu.out among the results. Where should it be placed?
[asm.report.pdf](https://github.com/marbl/canu/files/5616037/asm.report.pdf)

**Comment by skoren** [comment]
Idle, input data looks suspect, no high-quality overlaps so doesn't appear to be HiFi.
