### ISSUE TITLE
canu job correction failed

### ISSUE THREAD

**Issue by signor-molevol** [marbl/canu#1852]
This is the canu command I am using:
```
./canu -correct -d /home -p sample_correct genomeSize=140000000 -nanopore-raw sample.fastq useGrid=false gridOptionsmeryl="--mem-per-cpu=6000mb" gridOptionsmeryl="--cpu-per-task=1"  batMemory=100 batthreads=20 redMemory=100 redthreads=20  ovbthreads=20 ovbMemory=100 corthreads=20 corMemory=100 utgovlthreads=20 utgovlMemory=100 obtovlthreads=20 obtovlMemory=100 cormhapthreads=20 cormhapMemory=100
```
In the output file, it reflects these limits on memory, though perhaps I need to reduce them further. 

```
                                (tag)Concurrency
--                         (tag)Threads          |
--                (tag)Memory         |          |
--        (tag)             |         |          |       total usage      algorithm
--        -------  ----------  --------   --------  --------------------  -----------------------------
-- Local: meryl     24.000 GB    8 CPUs x  10 jobs   240.000 GB  80 CPUs  (k-mer counting)
-- Local: hap       12.000 GB   20 CPUs x   4 jobs    48.000 GB  80 CPUs  (read-to-haplotype assignment)
-- Local: cormhap  100.000 GB   20 CPUs x   3 jobs   300.000 GB  60 CPUs  (overlap detection with mhap)
-- Local: obtovl   100.000 GB   20 CPUs x   3 jobs   300.000 GB  60 CPUs  (overlap detection)
-- Local: utgovl   100.000 GB   20 CPUs x   3 jobs   300.000 GB  60 CPUs  (overlap detection)
-- Local: cor      100.000 GB   20 CPUs x   3 jobs   300.000 GB  60 CPUs  (read correction)
-- Local: ovb      100.000 GB   20 CPUs x   3 jobs   300.000 GB  60 CPUs  (overlap store bucketizer)
-- Local: ovs        8.000 GB    1 CPU  x  47 jobs   376.000 GB  47 CPUs  (overlap store sorting)
-- Local: red      100.000 GB   20 CPUs x   3 jobs   300.000 GB  60 CPUs  (read error detection)
-- Local: oea        8.000 GB    1 CPU  x  47 jobs   376.000 GB  47 CPUs  (overlap error adjustment)
-- Local: bat      100.000 GB   20 CPUs x   1 job    100.000 GB  20 CPUs  (contig construction with bogart)
-- Local: cns        -.--- GB    8 CPUs x   - jobs     -.--- GB   - CPUs  (consensus)
```

Every time the job is killed like so:
```
ABORT:
ABORT: canu 2.1.1
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
job correction/sample.ovlStore.BUILDING/0395 FAILED.ABORT:
slurmstepd: error: Detected 1318 oom-kill event(s) in step 14895.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
```
This is not in itself a canu error, but I just can't for the life of me figure out how to limit the memory so that thing runs. The memory it lists above is available.

**Comment by skoren** [comment]
One, you're mixing grid parameters and non grid parameters, since you've specified useGrid=false, nothing with `gridOptions*` has any effect. You should also avoid explicitly setting memory for each step as you're doing, you're telling Canu to use 100gb for the store building step, the one that's failing and 20 cores. That's excessive and the ovb process is single-threaded anyway. I would honestly run without setting any of the memory/cores explicitly.

Since you've limited canu to a single node, it's not making any memory requests. It's all down to whatever you requested when you submitted your canu command. Make sure you restrict Canu to that memory/cores using maxThreads/maxMemory or a bit lower to give some buffer or it will try to use the entire node and potentially get killed by the scheduler.

**Comment by signor-molevol** [comment]
Hi, Ok, I will say that I had the exact same failure when I did not specify these parameters. This is the result of many attempts to improve memory. With absolutely no calls about memory I get the same error.

**Comment by skoren** [comment]
Yes, see my second paragraph. Canu has no idea what resources to use so it tries to fill the node. If that isn't what you're requesting it will cause issues. Run without setting memory for each step but do use maxThreads/maxMemory to limit canu to make sure it doesn't exceed the request you made for this job.

**Comment by signor-molevol** [comment]
Ok, thank you. I will try this. My apologies if I did not read the documentation closely enough.

**Comment by signor-molevol** [comment]
You are absolutely right (as to be expected), that worked. Thank you.
