### ISSUE TITLE
No untigs.fasta 

### ISSUE THREAD

**Issue by lenhoe** [marbl/canu#1853]
Hi, I'm new to canu and using it to process nanopore datas.
I ran the program with the default options (except that I specified the corMaxEvidenceErate at 0.15, since my target genome is GC reach and highly ripetitive). 
Anyway, in the "Output" section of canu tutorial is stated I should have as one of the output the file containing contigs split at alternate paths in the graph (untigs.fasta), but the only thing I can find with a slightly similar name is a folder (untigging).
Is that normal?
How can I fix it?

**Comment by skoren** [comment]
Ah, looks like the documentation didn't get re-built with that change, I've fixed it. The unitigs output has been deprecated as of canu 2.1 (see also #1786, #1826).
