### ISSUE TITLE
trio binning doesn't separate haplotypes

### ISSUE THREAD

**Issue by TrentPrall** [marbl/canu#1854]
Hello there. I am attempting to use trio binning. I have ont long reads for the F1 sample and illumina novaseq paired end fastqs for the F0 parental datasets. However, when I run canu it doesn't separate reads into haplotypes. Any thoughts or advice would be greatly appreciated. 
```
canu --version
Canu 1.9
```

command:
```
canu -p 24866 -d /slipstream/home/tprall/24866/out/correct genomeSize=5m corMaxEvidenceErate=0.15 -haplotyperh1990 rh1990.merged.fastq.gz -haplotyper97070 r97070.merged.fastq.gz -nanopore-raw r02072.hg38.MHC.fastq.gz corMemory=50 
```

```
-- Found 1 haplotyping outputs.
-- No change in report.
-- Finished stage 'haplotype-reads', reset canuIteration.
--
-- Found         22 reads and      1520933 bases for haplotype r97070.
-- Found          0 reads and            0 bases for haplotype rh1990.
-- Found      32626 reads and    413483179 bases assigned to no haplotype.
-- Ignored    11117 reads and      6377554 bases because they were short.
--
-- More than 5 % of bases in unassigned reads; including them in assemblies.
--
-- Haplotype assembly commands:
--   /slipstream/home/tprall/24866/out/correct/24866-haplotyper97070.sh
--   /slipstream/home/tprall/24866/out/correct/24866-haplotyperh1990.sh
--
-- ERROR:
-- ERROR:  Too many bases in unassigned reads.  Assemblies not started.
-- ERROR:
-- ERROR:  If you run them manually, note that the unassigned reads
-- ERROR:  are included in ALL assemblies.
-- ERROR:
```

**Comment by skoren** [comment]
It doesn't seem like your haplotypes have enough k-mers to bin the data, this looks like an input issue. Are you sure these are the correct parents? The `haplotype.log` and `splitHaplotype.*.out` will have more info like the thresholds chosen for the binning and the k-mer stats. I'd also suggest using merqury to check what fraction of your parental k-mers are inherited in the reads you're providing.

**Comment by skoren** [comment]
Idle, seems like parental data lacks k-mers to bin the reads.
