### ISSUE TITLE
Searching subreads used to assemble contig of interest (canu)

### ISSUE THREAD

**Issue by wcc-new** [marbl/canu#1856]
I use canu to assemble pacbio data. From the contigs.layout.readToTig file, I can find the reads that are used to assemble a particular contig. However, the read ID does not match the original subreads ID. Is there any way to relate the read ID to the original subread ID so that I can get those subreads  sequences and map back to the assembled contig of interest?

On the other hand, I would like to know more detail on the consensus.000002.out file. By referring to the description below, my understanding is for contig ID: tigID2, 108 reads were used to assemble it. However, there is CONTAINED READS and DOVETAIL READS with different number of reads used. May I know what is that mean? 

                         ----------CONTAINED READS----------  -DOVETAIL  READS-
  tigID    length   reads      used coverage  ignored coverage      used coverage
------- --------- -------  -------- -------- -------- --------  -------- --------
      2     23295     108       103   35.33x        0    0.00x         5    3.38x

**Comment by skoren** [comment]
The read ID translation is available in `*.seqStore/readNames.txt`, see https://canu.readthedocs.io/en/latest/tutorial.html#outputs
