### ISSUE TITLE
Version not properly reported when installed with conda

### ISSUE THREAD

**Issue by akiledal** [marbl/canu#1861]
I installed canu version 2.1.1 with conda to use with [circlator.](https://sanger-pathogens.github.io/circlator/) Though it installed correctly, the version reported by `canu --version` appears to be incorrect: 

> canu branch HEAD +0 changes (r10117 5638f7d9a5379373310ab62c28aa0cdbd864722d)

This improper version output additionally breaks compatibility with circlator. I'm not sure if this is specific to conda installations, as I haven't tested installation via any other methods.

**Comment by skoren** [comment]
We don't officially support or recommend conda as an installation method, we don't control the recipe and it has had issues in the past. You could try downloading the binary instead for your system which will properly report the version. I submitted a pull request to conda to change the recipe to make sure the built version appears as ```canu 2.1.1```, not sure when/if it'd be accepted.
