### ISSUE TITLE
avoiding low-coverage/erroneous overlaps? 

### ISSUE THREAD

**Issue by TC-Hewitt** [marbl/canu#1862]
Hi, using Canu 2.0 with default settings and -pacbio-hifi, I noted sites of misjoins in chimeric contigs were associated with low overlap coverage (we have a reliable reference). The image shows one such site where I have aligned the source reads back to their contig. Is there a way to minimize these such as setting a min coverage cutoff? Is it better to adjust correctedErrorRate? (url
![lowcovex1_19ACT06run2_ctg93](https://user-images.githubusercontent.com/33470968/102303761-096f1180-3fb0-11eb-886c-ba984b8e348f.PNG)
)
thanks

**Comment by skoren** [comment]
You should definitely update to canu 2.1.1 from 2.0 as it has significant changes in contig construction. You can also turn on trimming (add `-untrimmed` to the command line.

**Comment by TC-Hewitt** [comment]
Hi, I upgraded to v2.1.1 using default params with -untrimmed. Seems to work well as the 2 largest chimeric contigs are no longer generated compared to the same using v2.0. Was just generally wondering if any situations recommend adjusting overlap params or if Canu handles that pretty well based on the input data.
cheers

**Comment by skoren** [comment]
Generally, canu auto-sets many of the parameters for you so you shouldn't need to adjust them. You can also try canu 2.1.1 w/o the untrimmed option to see if the chimeric contigs are generated.
