### ISSUE TITLE
HIcanu performance and ultra low protocol for HiFi ?

### ISSUE THREAD

**Issue by ptranvan** [marbl/canu#1869]
Thanks for your amazing software,

I have HiFi data and working on insects. DNA were not sufficient, so we did the ultra low protocol as described here:

https://www.pacb.com/wp-content/uploads/Application-Note-Considerations-for-Using-the-Low-and-Ultra-Low-DNA-Input-Workflows-for-Whole-Genome-Sequencing.pdf

I used `canu 2.1.1`

`canu -p asm -d x genomeSize=500m maxThreads=24 maxMemory=500 useGrid=false -pacbio-hifi ../x.fastq.gz
`
However I had a poor result:

```
G size: 350Mb 
# Contigs: 11021
BUSCO: C:80.6%[S:66.9%,D:13.7%],F:3.3%,M:16.1%,n:1367
```

As you can see, the genome is highly incomplete (I expect around 500Mb and we can see the BUSCO score ...).

1) My assumption is that the ultra low protocol cause too much coverage bias. Do you have some recommended parameters to look at ?

2) How HiCanu deals with coverage bias ? the regions with very low coverage: are they discarded ?

**Comment by skoren** [comment]
We've assembled metagenomes from the ultra-low protocol as well as mosquito samples from low-input libraries released by PacBio (e.g. https://www.ncbi.nlm.nih.gov/sra/?term=SRR12121585) without issue with default parameters. HiCanu doesn't really care about coverage variations, except to downsample the full dataset to 50x of the genome size and discard single-coverage regions (but those aren't useful for assembly anyway). 

More likely is overall low coverage, how much total coverage did you have? Have you confirmed the BUSCO run didn't have any issues, it can sometimes silently fail and report inaccurate results.

**Comment by ptranvan** [comment]
Hi @skoren, I have 46X of coverage. I thought I needed at least 30X, it's not enough ?

The BUSCO didn't had any issue

**Comment by skoren** [comment]
Based on the mapping stats, it seems like the assembly faithfully represents the reads, perhaps the BUSCO set is inaccurate for your species? 

Normally, 46x is enough but if you have lots of PCR bias it's possible some regions ended up with no coverage. There are also biases in the HiFi sequencing data, namely it drops long simple repeats of GA/TC. This would show up in your k-mer histogram but may be hard to see separate from the PCR bias and this doesn't normally affect the genes. 

Reads with 2x coverage should be assembled by default, only reads with no other support are discarded. Canu reports statistics on reads used/error rates/etc if you post the full report file generated. You can also see the list of reads used (in the contigs.layout.readToTig file) for the actual assembly.
