### ISSUE TITLE
misassembly in Canu2.0

### ISSUE THREAD

**Issue by MeiyuanJi** [marbl/canu#1870]
Hi,

I am using Canu2.0 for a plant genome assembly. The genome is very repetitive (>90%). The command I used for this assembly (total PacBio reads for this assembly is more 100 coverage):

canu -p B96 -d /scratch/general/lustre/u1268149/B96_canu/ genomeSize=2.5g correctedErrorRate=0.035 -pacbio-raw /uufs/chpc.utah.edu/common/home/clarkr-group1/B96_pacbio.fasta saveReads=true

I am running it on a Linux machine. After I got the assembled contigs, two rounds of polishing were performed using pbmm2. I used the reference genome to assess the performance of the Canu assembly. Reference genome genes were mapped against contigs so that gene orders on reference and the query contigs are known. I attached the dotplot here:

![Screen Shot 2020-12-26 at 10 32 15 PM](https://user-images.githubusercontent.com/33933620/103180326-04cd1780-4852-11eb-8132-1ad53a46a628.png)

As you can find, there are at least 3 misassemblies across different chromosomes, separated by dashed line, and chromosome names are label on the upper side. 

Although the assembled contigs are supper large, the mis-assembly make things hard to explain. At this point, I only can break the contigs that show misassemblies based on the genes source. However, it is arbitrary. Is there any idea to fix this problem in a more reasonable and pervasive way?

Many thanks for your help!

Best,
Meiyuan

**Comment by skoren** [comment]
First step would be to switch to canu 2.1.1, it has significant updates to the unitigging algorithm which may address this. However, there are always likely to be a handful of errors in any assembly from any assembler. We typically rely on other data types (like bionano, HiC, etc) to identify and fix these errors in scaffolding.

**Comment by sotuamax** [comment]
Hi,

Thanks for your reply. 

Because run the whole process again can cost a very long time. I want to ask if the corrected reads from the Canu2.0 output can be used as input for Canu 2.1. So that only use Canu 2.1 for the re-assembly step. Many thanks!

Best,
Meiyuan

**Comment by skoren** [comment]
You only need to re-run the unitigging step with 2.1.1 so run canu something like:
```canu <your other options> -d newrun -p asm -corrected -trimmed -pacbio <old run folder>/*.trimmedReads.fasta.gz```

**Comment by sotuamax** [comment]
Thanks for your quick reply.

I will run this then. Update more when I have new results.

Meiyuan

**Comment by skoren** [comment]
Any update?

**Comment by sotuamax** [comment]
The assembly takes more time than I expected. I have to give up it and stick on the mis-assembly correction I used now. But, you are right. Every assembler has some minor errors that need to be further checked and corrected using additional data.

Best,
Meiyuan

On Jan 22, 2021, at 8:22 AM, Sergey Koren <notifications@github.com<mailto:notifications@github.com>> wrote:



Any update?

**Comment by paulamool** [comment]
Just to let you know in my case for a smaller genome (40Mb) switching from Canu2.0  to Canu2.1.1 fixed the mis-assemblies.

**Comment by brianwalenz** [comment]
Great!  Always like to get comments like that!  The 2.1 release was almost entirely focused on fixing misassemblies, definitely worth the effort to redo the 'unitigging' step with that release.

**Comment by MeiyuanJi** [comment]
Thanks for letting me know.

Meiyuan
