### ISSUE TITLE
Tasks  have been queued at this step "bat" always

### ISSUE THREAD

**Issue by jenny315** [marbl/canu#1873]
Hi,

I'm running CANU 2.1 using the hifi flag on Linux.
```
canu  -d  ./  -p Aa_asm  genomeSize=820m  -pacbio-hifi  ../01bam_convert_fa/result_A-2_G02.ccs.fasta.gz
```
When the task enters the "bat" step, it  queuing at this step, and many of the tasks behind it are already running, but it is still queuing. I checked and found the number of free CPUs>16. So I don't know why it has been queuing, and there is no error message or "out" file in this step.
```
17990.schpc.m     jenny  default  bat_Aa_asm          --      1     16  256gb   --  Q   --
    --
17991.schpc.m     jenny  default  canu_Aa_asm         --      1      1    4gb   --  H   --
```
use checkjob and to view task information
```
$ checkjob 17990


checking job 17990

State: Idle
Creds:  user:jenny  group:FBI  class:default  qos:DEFAULT
WallTime: 00:00:00 of 99:23:59:59
SubmitTime: Sat Jan  9 23:36:38
  (Time Queued  Total: 2:16:35:33  Eligible: 2:16:35:33)

Total Tasks: 16

Req[0]  TaskCount: 16  Partition: ALL
Network: [NONE]  Memory >= 0  Disk >= 0  Swap >= 0
Opsys: [NONE]  Arch: [NONE]  Features: [NONE]
Dedicated Resources Per Task: PROCS: 1  MEM: 16G


IWD: [NONE]  Executable:  [NONE]
Bypass: 20  StartCount: 0
PartitionMask: [ALL]
Flags:       RESTARTABLE

PE:  136.23  StartPriority:  3875
job cannot run in partition DEFAULT (idle procs do not meet requirements : 0 of 16 procs found)
idle procs:  64  feasible procs:   0

Rejection Reasons: [Class        : 1466][CPU          :    6][State        :    2]

```
I'm not sure if there's a problem with the task.

Thanks for any advice,
Best regards,
Jenny

**Comment by skoren** [comment]
I expect the issue is the memory request for the job, Canu tends to request too much memory for hifi data (see #1788). There are likely a limited number of machines in your default queue with 256G. You can likely use much less memory in practice, delete both those jobs from your queue and re-launch canu adding `batMemory=50`. This should resume the run where it left off and request less memory to avoid waiting in the queue.

**Comment by jenny315** [comment]
Thank you very much.  I have set it. Now there are empty nodes, and the memory of empty nodes is enough, but the tasks are still queuing. I wonder if I could specify the node to make it run and I don't know how to specify the node for it .

Thanks for any advice,
Best regards,
Jenny

**Comment by jenny315** [comment]
hi，
Thanks for your suggestion.

I resubmitted the task after adding ``` batMemory=50```. Even though there are enough empty nodes, it is still queuing, so I wonder if I can use ```useGrid=false``` in this step. Then I want to use a script that only contains the ```sleep``` command to hold the empty nodes, at the same time use ```nohup```  to re-launch the canu script. If I do this, will the task resumed where it left off?
or  I wonder if I could specify the node to make it run, and I  I don't know how to specify the node for it.

Thanks for any advice,
Best regards,
Jenny

**Comment by jenny315** [comment]
If I reboot the servers, then re-launch canu script (hicanu)，will the task resumed where it left off?

**Comment by skoren** [comment]
If it's still holding even though there are available nodes, that's a grid issue but not a Canu issue. You can check why the job is not being scheduled, perhaps your priority has dropped? 

Any restart with the same command and folder will resume where it left off, yes. Canu is not really designed to jump between on grid and off grid in one run. You can switch to be off grid if you remove the current 4-unitigger folder and re-start but then you should stay on the single node until the run finishes.

**Comment by jenny315** [comment]
hi，
Thank you very much!  sorry for the late reply, you are right, it is the problem of grid. I added ```useGrid=false```  in "canu.defaults" file to make it continue to run on a single node [In fact, managing nodes ( previous attempts at subnode failed)], and it succeeded!

Best regards,
Jenny
