### ISSUE TITLE
Assembly for tandem repeats

### ISSUE THREAD

**Issue by tay45** [marbl/canu#1874]
Hello,

I've been trying to assemble viral genomes (~ 200 kb) which has the inverted terminal repeat (ITR) including tandem repeat region at the very ends. The assembled sequence between ITRs is usually good with the expected contig size. However, the assembled tandem repeats at the ITRs are not always perfect when comparing the references even though the raw read length was enough to cover the entire the repeated regions. I wonder if you could give me some tips to improve the quality of the repeated sequence during the assembly. I attached my command line here for your reference. Thank you.

Tay

canu -p virus -d virus genomeSize=0.2m -pacbio-raw subreads.fasta minReadLength=5000 batMemory=200

**Comment by skoren** [comment]
When you say it's not always perfect, do you mean it's truncated or just lower accuracy. I presume this is a linear genome so the coverage drops at the end of the molecule which always leads to some shortening and lower QV, there is not much you can do about that. The other issue is the ITR looks a lot like the pattern of a missed PacBio SMRTbell adapter which Canu tries to detect/trim. In these cases, polishing with Arrow afterwards can help extend the assembly. You could also try running the corrected reads without trimming (supply the `virus.correctedReads.fasta.gz` with the `-pacbio -corrected -trimmed`) parameters.

**Comment by tay45** [comment]
Thank you for your comment!  I will try to assemble it with the suggestions.

Tay


2021년 1월 13일 (수) 오후 12:03, Sergey Koren <notifications@github.com>님이 작성:
