### ISSUE TITLE
Why the contig file also includes bubbles inside?

### ISSUE THREAD

**Issue by bostanict** [marbl/canu#188]
Hi,
I am assembling a plant genome with high heterozygosity. I did the correction, trimming and assembly by CANu and got the results. Strangely I have only 18 sequences in the bubble files (which seems to be very few to my understanding) and also when I run the contigs vs contigs blast, there are many of the contigs that go inside the other one with high similarity and coverage and also in some cases even 100% with some gaps. So my question is that:

1) why these contigs are in the same file as primary and not in the bubbles file?
2) how can we distinguish the primary wrote and other routes to be able to see how much of the genome is assembled aside from the stats CANU provides?

Thanks a lot

**Comment by brianwalenz** [comment]
I recently discovered a flaw in the bubble detection that would leave many - if not most - bubbles undetected.  I've yet to implement a solution.  There was a commit this morning that will catch more of the nearly identical bubbles and resolve them into their proper location.

Will the GFA help for your second question?

**Comment by bostanict** [comment]
Thanks for the info. eagerly waiting for the solution to this issue. Moreover, is the information inside the gfa file coherent since you mentioned the bubbles are not cough correctly? if yes, do you have any suggestion on the way we can use the gfa file simply to get all the primary contigs?

**Comment by brianwalenz** [comment]
Moving from active issue to feature request.  https://github.com/marbl/canu/projects/1
