### ISSUE TITLE
Only one PacBio read found after starting canu with gridEngine options

### ISSUE THREAD

**Issue by christinahedderich** [marbl/canu#1880]
Hi, 

I am trying to run canu for read correction on a 2,1g PacBio genome. I am using our institute's cluster, which uses slurm. My slurm-file looks like the following:

```
#!/bin/bash
#
#SBATCH --job-name=dimp_corr
#SBATCH --cpus-per-task=20
#SBATCH --mem=320000
#SBATCH --partition=himem
#SBATCH --license=scratch-highio
#SBATCH --mail-type=ALL

module load canu
canu -correct -p Dimp -d /scratch/hedderich/canu -pacbio-raw /scratch/hedderich/canu/Dimpolita.fastq genomeSize=2.1g maxMemory=320G maxThreads=20 gridEngine=slurm gridOptions='--license=scratch-highio --constraint=array-4core' gridEngineMemoryOption='--mem=MEMORY' gridEngineThreadsOption='--cpus-per-task=THREADS' gridOptionsJobName=dimp_corr stageDirectory=\$TMPDIR_
```
the job starts, but finishes after 10 secs without any error message. This is what I get as my output:
```
Canu 2.0
--
-- Detected Java(TM) Runtime Environment '14.0.2' (from '/apps/java/14.0.2/bin/java') without -d64 support.
-- Detected gnuplot version '4.6 patchlevel 2   ' (from 'gnuplot') and image format 'png'.
-- Detected 128 CPUs and 504 gigabytes of memory.
-- Limited to 320G gigabytes from maxMemory option.
-- Limited to 20 CPUs from maxThreads option.
-- Detected Slurm with task IDs up to 999999 allowed.
--
-- Found   2 hosts with  24 cores and  487 GB memory under Slurm control.
-- Found   1 host  with  40 cores and  976 GB memory under Slurm control.
-- Found   1 host  with  40 cores and 1073 GB memory under Slurm control.
-- Found  16 hosts with  20 cores and  306 GB memory under Slurm control.
-- Found   1 host  with  32 cores and  976 GB memory under Slurm control.
-- Found   2 hosts with  48 cores and  976 GB memory under Slurm control.
-- Found  16 hosts with  64 cores and  487 GB memory under Slurm control.
-- Found  30 hosts with  16 cores and  124 GB memory under Slurm control.
-- Found   1 host  with  48 cores and  487 GB memory under Slurm control.
-- Found   4 hosts with 128 cores and 1952 GB memory under Slurm control.
--
--                         (tag)Threads
--                (tag)Memory         |
--        (tag)             |         |  algorithm
--        -------  ----------  --------  -----------------------------
-- Grid:  meryl     30.000 GB    4 CPUs  (k-mer counting)
-- Grid:  hap       16.000 GB   16 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   30.000 GB    4 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    24.000 GB    4 CPUs  (overlap detection)
-- Grid:  utgovl    24.000 GB    4 CPUs  (overlap detection)
-- Grid:  cor       24.000 GB    4 CPUs  (read correction)
-- Grid:  ovb        4.000 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       32.000 GB    1 CPU   (overlap store sorting)
-- Grid:  red       48.000 GB    8 CPUs  (read error detection)
-- Grid:  oea        8.000 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      320.000 GB   20 CPUs  (contig construction with bogart)
-- Grid:  cns        -.--- GB    8 CPUs  (consensus)
-- Grid:  gfa       64.000 GB   20 CPUs  (GFA alignment and processing)
--
-- In 'Dimp.seqStore', found PacBio CLR reads: 
--   PacBio CLR:               1
--
--   Raw:                      1
--
-- Generating assembly 'Dimp' in '/scratch/hedderich/canu':
--    - only correct raw reads.
--
-- Parameters:
--  
--  genomeSize        2100000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%) 
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0750 (  7.50%)
--
--
-- BEGIN CORRECTION
--
-- No change in report.
--
-- OVERLAPPER (mhap) (correction) complete, not rewriting scripts.
--
-- No change in report.
--
-- Running jobs.  First attempt out of 2.
--
-- 'mhap.jobSubmit-01.sh' -> job 377001 tasks 68-143.
--
----------------------------------------
-- Starting command on Wed Jan 20 10:17:17 2021 with 96018.607 GB free disk space

    cd /scratch/hedderich/canu
    sbatch \
      --depend=afterany:377001 \
      --cpus-per-task=1 \
      --mem-per-cpu=4g \
      --license=scratch-highio \
      --constraint=array-4core  \
      -D `pwd` \
      -J 'canu_Dimp_dimp_corr' \
      -o canu-scripts/canu.07.out  canu-scripts/canu.07.sh
Submitted batch job 377002

-- Finished on Wed Jan 20 10:17:17 2021 (like a bat out of hell) with 96018.607 GB free disk space
```
It seems that it only finds one raw read. I don't know what is causing this issue and would be very thankful for any help! 

Best,
Christina

**Comment by brianwalenz** [comment]
There's a small chance it's reporting the number of PacBio _libraries_ found.  Have a look in `Dimp.report`, `Dimp.seqStore.err`, `Dimp.seqStore/errorLog` and `Dimp.seqStore/info.txt` for better logging.

Also check the first `canu-scripts/*out` to see what it reported immediately after loading reads into the seqStore.

This particular quirk was fixed in Canu 2.1.  Upgrading to Canu 2.1.1 is suggested!

**Comment by christinahedderich** [comment]
The Dimp.seqStore/errorLog gives, in general, the following message for probably all of the reads: 

read 'm64046_201204_153309/722923/26782_27250' of length 468 in file '/scratch/hedderich/canu/Dimpolita.fastq' - too short, skipping.
read 'm64046_201204_153309/722967/0_205' of length 205 in file '/scratch/hedderich/canu/Dimpolita.fastq' - too short, skipping.

The info file:
    Reads        Bases Read Type
---------- ------------ ----------------------------------------
   7538501            - total-reads
   7538501 163397516717 raw
         0            0 raw-trimmed
   7538501 110674169661 raw-compressed
         0            0 raw-compressed-trimmed
         0            0 corrected
         0            0 corrected-trimmed
         0            0 corrected-compressed
         0            0 corrected-compressed-trimmed

I cannot explain to myself what is causing it.

**Comment by brianwalenz** [comment]
The `info` is reporting that there are 7,538,501 with 163,397,516,717 bases for around 77x coverage.  I think this is just a logging failure.

As for the 10 second run time - Sorry! I just noticed that this is what your real concern was - this is normal.  Canu checked the progress of the compute, noticed that two 'mhap' jobs needed to be run still, it submitted those two jobs to slurm, and then re-submitted itself to run when those jobs finish.

**Comment by christinahedderich** [comment]
Thank you! 
Still, I am not gaining any corrected reads. I checked the mhap files and they are giving the following error:
 job correction/1-overlapper/results/000143.ovb FAILED.

Is there something wrong with my slurm-job, then?

**Comment by skoren** [comment]
Canu runs on the grid so when the job exists, it doesn't mean correction is done. The jobs will continue to run in the background on your cluster and will retry failed jobs automatically. If you have jobs in the queue, then the run is OK.

If you see no jobs are running and the last `canu.out` file has an error message, then it could be something within Canu or something on the cluster causing the error. Post the full log of the failing job in that case (e.g. `correction/1-overlapper/*143*out` if job 143 failed in the overlapper step) which will have more details on what happened.

**Comment by christinahedderich** [comment]
I already checked yesterday if there were any jobs running in the background, but that wasn't the case. The last mhap*out gives the following message: 

Found perl:
   /apps/perl/5.32.0/bin/perl
   This is perl 5, version 32, subversion 0 (v5.32.0) built for x86_64-linux-thread-multi

 Found java:
   /apps/java/14.0.2/bin/java
   java version "14.0.2" 2020-07-14

Found canu:
   /apps/canu/2.0/Linux-amd64/bin/canu
   Canu 2.0

Running job 0 based on command line options.
Error: Job index out of range.

-- for the canu.out: 

BEGIN CORRECTION
 No change in report.
OVERLAPPER (mhap) (correction) complete, not rewriting scripts.
Mhap overlap jobs failed, tried 2 times, giving up.
 job correction/1-overlapper/results/000068.ovb FAILED. (...) 
ABORT:
ABORT: Canu 2.0
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:

**Comment by skoren** [comment]
That looks like something is going wrong with your slurm job, it's not properly passing a job id to the canu jobs. What does the `mhap.jobSubmit*out` and `mhap.jobSubmit*.sh` say? What happens if you run `sh mhap.sh 68` in the 1-overlapper folder directly?

Have you launched this run more than once? If so it's possible the jobs collided if one was still running (e.g. jobs queued) and caused the errors. I'd first remove the full run folder, update to 2.1.1, and re-launch. Only launch the job once and use the canu.out to monitor progress. If it reports an error again, post the error from `canu.out`

**Comment by skoren** [comment]
Idle
