### ISSUE TITLE
Unexplained memory errors in the Computing correction layouts step.

### ISSUE THREAD

**Issue by DustinSokolowski** [marbl/canu#1882]
Hello! 

Thank you for your tool and package. I am trying to generate a de novo_ gneome with canu before moving to complete Trio-binning with paired 10X linked reads. I have been working with canu to try and assemble the "proband" genome for a while (just to make sure that it is working properly on our HPC) and I have consistently been running into strange memory errors. The genome should be roughly the size of the mouse (including # repeats). We used oxford nanopore sequencing.

The command I have used is below:
```
#!/bin/bash

#PBS -l nodes=1:ppn=4,mem=500g,walltime=100:00:00

cd $dir

module purge ; module load canu/2.1 ; module load gnuplot/5.2.2 ; module load li
bpng/1.2.59 ; module load java/1.8.0_161

# 20201120 - added corMhapFilterThreshold.... to ovlMerDistinc=0.975 as per canu
 faq
# 20201120 -
# 20201214 - set maxMemory=110, batMemory=64-110

canu batMemory=64-110 \
    saveOverlaps=true \
    stageDirectory='/localhd/$PBS_JOBID' \
    corMhapFilterThreshold=0.0000000002 \
    corMhapOptions="--threshold 0.80 --num-hashes 512 --num-min-matches 3 --orde
red-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-
scale 50" \
    corMhapSensitivity=low \
    corMinCoverage=0 \
    purgeOverlaps="aggressive" \
    maxMemory=110 \
    mhapMemory=60 \
    mhapBlockSize=500 \
    ovlMerDistinct=0.975 \
    gridOptions="-l mem=110g,walltime=300:00:00" \
    preExec="module load canu/2.1 gnuplot/5.2.2 libpng/1.2.59 java/1.8.0_161" \
    -d test8 -p NMR_boy genomeSize=2.7g -nanopore-raw NMR_male/*.fastq.gz gnuplo
t=/hpf/tools/centos6/gnuplot/5.2.2/bin/gnuplot
```

We consistently fail at trying to generate correction layouts with: ` Failed with exit code 134.  (rc=34304)`

It stops at `canu.06.sh` with the final successful steps being:

```
-- Overlap store 'correction/NMR_boy.ovlStore' successfully constructed.
-- Found 4327397029522 overlaps for 11264713 reads; 605876 reads have no overlap
```

It seemed to report a memory error: ` terminate called after throwing an instance of 'std::bad_alloc'`. What we are finding particularly odd is that the jobs seem to peak around 87Gb of memory despite us allowing much more than that. 

If you need us to upload our reads (~95.5Gb) or the most recently generated cor file (~400 Gb ?!) to the ftp then we would be happy to. 

We have been able to assemble this genome with flye 2.8 but since we do want to complete a diploid genome with your trio-binning method we were hoping to complete this analysis with canu. If you think it is not possible then do you have a pipeline for using your Trio-binning scripts with the eventual assembly of flye 2.8?

I also noticed that issue #1875 may have some overlap however I am fairly convinced that the "*.readsToCorrect.log" has not yet been generated yet. If it has an I just missed it then I will try the same correction from there.

Thank you so much for your help
Dustin

**Comment by brianwalenz** [comment]
Out of memory error have _usually_ been from slight corruption in the overlap store where it claims some read has billions and billions of overlaps.  When we go to read in the overlaps for this read, we try to allocate memory for all of those, and consequently explode.

Logging in that module is non-existent, unless it is turned on (with -V), then it's ginormous.  But it can be run by hand:
```
cd correction/
> generateCorrectionLayouts -S ../asm.seqStore -O ./asm.ovlStore -C ./tmp.corStore -eC 80 -V
```
tmp.corStore.log will be filled with lots of
```
...
Generate layout for read 7 length 17089 using up to 95 overlaps.
  filter read      8200 at position      0, 16682 length 16949 erate 0.1459 - filtered by global filter (6212 < 6409)
  allow  read     18253 at position    658, 17088 length 16279 erate 0.1357 - allowed  by global filter (9851 > 9410)
  allow  read     30372 at position  13340, 14746 length  1355 erate 0.1399 - allowed  by global filter (13957 > 0)
  allow  read     41159 at position     12, 12859 length 12877 erate 0.1455 - allowed  by global filter (10475 > 9444)
...
  allow  read    663999 at position     12,  5668 length  6146 erate 0.1561 - allowed  by global filter (12378 > 6450)
  allow  read    664636 at position      0, 17076 length 17594 erate 0.1516 - allowed  by global filter (8719 > 8053)
Generate layout for read 8 length 1909 using up to 3 overlaps.
  filter read    321540 at position   1061,  1908 length  1026 erate 0.1865 - filtered by global filter (515 < 9877)
  filter read    638057 at position     12,  1908 length  2225 erate 0.1871 - filtered by global filter (3105 < 13544)
  allow  read    640402 at position     12,  1420 length  1757 erate 0.1994 - allowed  by global filter (2260 > 0)
Generate layout for read 9 length 20097 using up to 103 overlaps.
  filter read      6923 at position    136, 20073 length 19726 erate 0.1252 - filtered by global filter (4553 < 6333)
  allow  read      7843 at position    811, 17323 length 16360 erate 0.1380 - allowed  by global filter (13986 > 10691)
  allow  read     19354 at position     12, 11579 length 11724 erate 0.1510 - allowed  by global filter (12472 > 11619)
...
```
we only care what the last 'Generate' line says - this is the read (or just before the read) causing problems.  If you're comfortable hacking C code, comment out the 'extra' printf()s in src/correction/generateCorrectionLayouts.C.

A different attack would be to ask the overlap store for some information:
```
> ovStoreDump -S ../asm.seqStore -O ./asm.ovlStore -counts
1       117
2       67     <- read 2 has 67 overlaps
3       93
4       40
...
```
hopefully that will show something useful.  If it does, the next step will be to either fix the overlap store (painful) or to modify generateCorrectionLayouts.C to skip the problematic read(s).

Or I could be totally wrong here and something else is wrong.

**Comment by DustinSokolowski** [comment]
Thanks so much! 

I'll get the output and get back to you as soon as possible.

**Comment by DustinSokolowski** [comment]
Hello!

Thank you very much for your help and patience with the results. 

I took your advice and generated a file containing all of the lines you need with `grep "Generate" tmp.corStore.log > corstoreGen`

This pulled our ~95260 reads with a reasonable distribution in length.

![Read length](https://user-images.githubusercontent.com/56414662/106224233-f192cc00-61b0-11eb-9d4f-444e3fc4d972.png)

None of the reads reached a billion overlaps but >14,326 reads contain over a million overlaps (max ~4.1 million).

![dist_ovl_reads](https://user-images.githubusercontent.com/56414662/106224403-4df5eb80-61b1-11eb-88b2-4994d1004601.png)


Please let me know if this gives you any more insight!

Best,
Dustin

**Comment by brianwalenz** [comment]
It'll probably be easiest to upload the data and let me poke around.  I need just the seqStore and ovlStore directories.  Both of those compress nicely with `gzip -1`.

I don't need any of the 'blobs' files in seqStore for this (nor do I need the `readlengths*` files).  The `blobs` files have the sequence in them.

Even better, I don't need all the overlap data files.
```
ovStoreDump -S ../asm.seqStore -O asm.ovlStore -metadata 95260
```
will report something like
```
   readID slice piece    offset  numOlaps overlapID
--------- ----- ----- --------- --------- ---------
    95250     1     1  48635898        19  48635898
--------- ----- ----- --------- --------- ---------
```
telling us that these overlaps are stored in overlap store file `0001-001` (slice-piece), so I need just `index`, `info` and `0001-001`.  To be safe, include the data files before and just after that one too.

--

You probably don't need to do this.  I had it written before I remembered the `-metadata` dump above.  It was an attempt to figure out exactly what read is failing.  Since the corStore.log stopped after ~95260 lets try to narrow down the bad read by running generateCoorectionLayouts on small ranges until it doesn't fail:
```
generateCorrectionLayouts -S ../asm.seqStore -O ./asm.ovlStore -C ./tmp.corStore -eC 80 -b 95260 -e 96000 -V
generateCorrectionLayouts -S ../asm.seqStore -O ./asm.ovlStore -C ./tmp.corStore -eC 80 -b 95300 -e 96000 -V
generateCorrectionLayouts -S ../asm.seqStore -O ./asm.ovlStore -C ./tmp.corStore -eC 80 -b 95400 -e 96000 -V
```
Adjusting the -b value until you find the one that fails, but the next one doesn't.  I'm not sure what to do with that info, except maybe hardcode it into generateCoorectionLayouts to be skipped, which would be ugly to say the least.
