### ISSUE TITLE
sbatch: error: AssocMaxSubmitJobLimit

### ISSUE THREAD

**Issue by Huangtianyu-caas** [marbl/canu#1883]
Hi Oliga,

It's me again. Based on your suggestion that single node is so unefficient for my project, so this time I tried to run `trim` in a grid option.
        `canu -trim -p Ttri -d ~/canu/result_file maxThreads=64 genomeSize=580m minReadLength=2000 minOverlapLength=500 ovbConcurrency=10 ovsConcurrency=10  useGrid=true -pacbio-corrected /public3/home/sc55294/canu/Ttri.correctedReads.fasta.gz`
        
        I got a new error, which is not presented in any before issues, so here, I opened a new issue for this error:
        `-- Canu 2.0
        --
        -- Detected Java(TM) Runtime Environment '1.8.0_262' (from 'java') with -d64 support.
        --
        -- WARNING:
        -- WARNING:  Failed to run gnuplot using command 'gnuplot'.
        -- WARNING:  Plots will be disabled.
        -- WARNING:
        --
        -- Detected 64 CPUs and 252 gigabytes of memory.
        -- Limited to 256g gigabytes from maxMemory option.
        -- Limited to 64 CPUs from maxThreads option.
        -- Detected Slurm with 'sinfo' binary in /usr/bin/sinfo.
        -- Detected Slurm with task IDs up to 1000 allowed.
        -- 
        -- Found  83 hosts with  64 cores and  499 GB memory under Slurm control.
        -- Found 2056 hosts with  64 cores and  249 GB memory under Slurm control.
        -- Found  13 hosts with  64 cores and  999 GB memory under Slurm control.
        --
        --                         (tag)Threads
        --                (tag)Memory         |
        --        (tag)             |         |  algorithm
        --        -------  ----------  --------  -----------------------------
        -- Grid:  meryl     24.000 GB    8 CPUs  (k-mer counting)
        -- Grid:  hap       12.000 GB   16 CPUs  (read-to-haplotype assignment)
        -- Grid:  cormhap   32.000 GB   16 CPUs  (overlap detection with mhap)
        -- Grid:  obtovl    16.000 GB   16 CPUs  (overlap detection)
        -- Grid:  utgovl    16.000 GB   16 CPUs  (overlap detection)
        -- Grid:  cor       16.000 GB    4 CPUs  (read correction)
        -- Grid:  ovb        4.000 GB    1 CPU   (overlap store bucketizer)
        -- Grid:  ovs       16.000 GB    1 CPU   (overlap store sorting)
        -- Grid:  red       31.000 GB    8 CPUs  (read error detection)
        -- Grid:  oea        8.000 GB    1 CPU   (overlap error adjustment)
        -- Grid:  bat      256.000 GB   16 CPUs  (contig construction with bogart)
        -- Grid:  cns        -.--- GB    8 CPUs  (consensus)
        -- Grid:  gfa       32.000 GB   16 CPUs  (GFA alignment and processing)
        --
        -- In 'Ttri.seqStore', found PacBio CLR reads:
        --   PacBio CLR:               1
        --
        --   Corrected:                1
        --
        -- Generating assembly 'Ttri' in '/public3/home/sc55294/canu/result_file_max':
        --    - only trim corrected reads.
        --
        -- Parameters:
        --
        --  genomeSize        580000000
        --
        --  Overlap Generation Limits:
        --    corOvlErrorRate 0.2400 ( 24.00%)
        --    obtOvlErrorRate 0.0450 (  4.50%)
        --    utgOvlErrorRate 0.0450 (  4.50%)
        --
        --  Overlap Processing Limits:
        --    corErrorRate    0.3000 ( 30.00%)
        --    obtErrorRate    0.0450 (  4.50%)
        --    utgErrorRate    0.0450 (  4.50%)
        --    cnsErrorRate    0.0750 (  7.50%)
        --
        --
        -- BEGIN TRIMMING
        --
        -- No change in report.
        -- No change in report.
        --
        -- Running jobs.  First attempt out of 2.
        --
        -- Failed to submit compute jobs.  Delay 10 seconds and try again.
        
        CRASH:
        CRASH: Canu 2.0
        CRASH: Please panic, this is abnormal.
        CRASH:
        CRASH:   Failed to submit compute jobs.
        CRASH:
        CRASH: Failed at /public3/soft/canu/2.0/Linux-amd64/bin/../lib/site_perl/canu/Execution.pm line 1275.
        CRASH:  canu::Execution::submitOrRunParallelJob('Ttri', 'meryl', 'trimming/0-mercounts', 'meryl-count', 1, 2, 3, 4, 5, ...) called at /public3/soft/canu/2.0/Linux-amd64/bin/../lib/site_perl/canu/Meryl.pm line 834
        CRASH:  canu::Meryl::merylCountCheck('Ttri', 'obt') called at /public3/soft/canu/2.0/Linux-amd64/bin/canu line 1025
        CRASH: 
        CRASH: Last 50 lines of the relevant log file (trimming/0-mercounts/meryl-count.jobSubmit-01.out):
        CRASH:
        CRASH: sbatch: error: AssocMaxSubmitJobLimit
        CRASH: sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)
        CRASH: s`

I have to mention that this cluster only allow me to use 10 nodes, is it the point?

My best,
Tianyu

**Comment by brianwalenz** [comment]
Oh, bother.  I do enjoy when sysadmins make life difficult.  Are you limited to 10 _nodes_ or 10 _jobs_?

Error AssocMaxSubmitJobLimit is, I think, the maximum number of jobs (or tasks in an array) that you can have running *or submitted* at a single time.

Before getting to the nitty-gritty, it'd definitely be worth trying to get your limit increased.

Instead of `useGrid=true` you can specify `useGrid=remote`.  This will set up jobs for execution on the grid, but not submit them.  It will prompt you to do that manually:
```
-- Running jobs.  First attempt out of 2.

Please run the following command to submit tasks to the grid for execution.
Each task will use 2 gigabytes memory and 4 threads.

  cd /assembly/lambda/test/correction/0-mercounts
  ./meryl-count.jobSubmit-01.sh

When all tasks are finished, restart canu as before.  The output of the grid
submit command will be in *jobSubmit*out.
```
`jobSubmit*sh` is just a qsub/sbatch command to run a task array on the grid.  You can then do whatever is needed to run those jobs.

Further setting option gridEngineArrayMaxJobs=10 should result in each jobSubmit-XX.sh script submitting only 10 jobs at a time.  Even so, it'll be a pain to manually submit them one after another.

With some minor code modifications and `gridEngineArrayMaxJobs=9 canuIterationsMax=20` you can get canu to submit 9 compute jobs to the grid and then resubmit itself to run when those 9 have finished -- so you will end up with at most 10 jobs submitted to the grid at a time.  Thus, to get 30 tasks to run, canu would submit the first 9 and then itself.  When those 9 tasks finish, the canu job starts, notices the first 9 tasks are complete and submits the next 9 and itself again.  Repeating until all jobs are run, then moving on to the next stage.

A slight danger here is that if a compute job fails for any reason, canu will try to rerun it up to canuIterationsMax times.   You want to make this big enough so that all compute tasks get run (9 * 20 = 180 tasks) but small enough so that if something bad does happen canu doesn't keep trying over and over and over and over to make it run.

The modification needed is to either (a) make canu submit exactly one batch of compute jobs (instead of all batches), or to (b) make it submit all batches and not fail on errors.

The (a) modification is to add 'last' at line 317:
```
            if (defined($jobName)) {
                push @jobsSubmitted, $jobName;
            }
            last;    #  ADD THIS!
        }
```

The (b) modification is to change line 1242 in src/pipelines/canu/Execution.pm from
```
            if (runCommandSilently($path, "./$cmd.sh", 0)) {
                print STDERR "-- Failed to submit compute jobs.  Delay 10 seconds and try again.\n";
                sleep(10);

                runCommandSilently($path, "./$cmd.sh", 0) and caFailure("Failed to submit compute jobs", "$path/$cmd.out");
            }
```
to just
```
            runCommandSilently($path, "./$cmd.sh", 0);
```

**Comment by Huangtianyu-caas** [comment]
Hi brain,

Thank you for your detailed guidance. I have modified my command into `canu -trim -p Ttri -d ~/canu/result_file_max maxThreads=64 maxMemory=256g genomeSize=580m minReadLength=2000 minOverlapLength=500 ovbConcurrency=10 ovsConcurrency=10 gridEngineArrayMaxJobs=9 useGrid=remote -pacbio-corrected~/Ttri.correctedReads.fasta.gz`, where I added `gridEngineArrayMaxJobs=9` and used `useGrid=remote `. However, my canu seems like still working on a one node model, only 4 tasks were concurrently worked at `obtovl` step:

      `-- Canu 2.0
      --
      -- Detected Java(TM) Runtime Environment '1.8.0_262' (from 'java') with -d64 support.
      --
      -- WARNING:
      -- WARNING:  Failed to run gnuplot using command 'gnuplot'.
      -- WARNING:  Plots will be disabled.
      -- WARNING:
      --
      -- Detected 64 CPUs and 252 gigabytes of memory.
      -- Limited to 256g gigabytes from maxMemory option.
      -- Limited to 64 CPUs from maxThreads option.
      -- Detected Slurm with 'sinfo' binary in /usr/bin/sinfo.
      -- Detected Slurm with task IDs up to 1000 allowed.
      -- 
      -- Found  83 hosts with  64 cores and  499 GB memory under Slurm control.
      -- Found 2056 hosts with  64 cores and  249 GB memory under Slurm control.
      -- Found  13 hosts with  64 cores and  999 GB memory under Slurm control.
      --
      --                         (tag)Threads
      --                (tag)Memory         |
      --        (tag)             |         |  algorithm
      --        -------  ----------  --------  -----------------------------
      -- Grid:  meryl     24.000 GB    8 CPUs  (k-mer counting)
      -- Grid:  hap       12.000 GB   16 CPUs  (read-to-haplotype assignment)
      -- Grid:  cormhap   32.000 GB   16 CPUs  (overlap detection with mhap)
      -- Grid:  obtovl    16.000 GB   16 CPUs  (overlap detection)
      -- Grid:  utgovl    16.000 GB   16 CPUs  (overlap detection)
      -- Grid:  cor       16.000 GB    4 CPUs  (read correction)
      -- Grid:  ovb        4.000 GB    1 CPU   (overlap store bucketizer)
      -- Grid:  ovs       16.000 GB    1 CPU   (overlap store sorting)
      -- Grid:  red       31.000 GB    8 CPUs  (read error detection)
      -- Grid:  oea        8.000 GB    1 CPU   (overlap error adjustment)
      -- Grid:  bat      256.000 GB   16 CPUs  (contig construction with bogart)
      -- Grid:  cns        -.--- GB    8 CPUs  (consensus)
      -- Grid:  gfa       32.000 GB   16 CPUs  (GFA alignment and processing)
      --
      -- In 'Ttri.seqStore', found PacBio CLR reads:
      --   PacBio CLR:               1
      --
      --   Corrected:                1
      --
      -- Generating assembly 'Ttri' in '/public3/home/sc55294/canu/result_file_max':
      --    - only trim corrected reads.
      --
      -- Parameters:
      --
      --  genomeSize        580000000
      --
      --  Overlap Generation Limits:
      --    corOvlErrorRate 0.2400 ( 24.00%)
      --    obtOvlErrorRate 0.0450 (  4.50%)
      --    utgOvlErrorRate 0.0450 (  4.50%)
      --
      --  Overlap Processing Limits:
      --    corErrorRate    0.3000 ( 30.00%)
      --    obtErrorRate    0.0450 (  4.50%)
      --    utgErrorRate    0.0450 (  4.50%)
      --    cnsErrorRate    0.0750 (  7.50%)
      --
      --
      -- BEGIN TRIMMING
      --
      -- No change in report.
      -- Meryl finished successfully.  Kmer frequency histogram:
      --
      -- WARNING: gnuplot failed.
      --
      ----------------------------------------
      --
      --  22-mers                                                                                           Fraction
      --    Occurrences   NumMers                                                                         Unique Total
      --       1-     1         0                                                                        0.0000 0.0000
      --       2-     2 843672654 ********************************************************************** 0.4282 0.0292
      --       3-     4 390451110 ********************************                                       0.5630 0.0430
      --       5-     7 153073316 ************                                                           0.6632 0.0580
      --       8-    11  70249346 *****                                                                  0.7166 0.0703
      --      12-    16  37575866 ***                                                                    0.7448 0.0802
      --      17-    22  24731457 **                                                                     0.7614 0.0886
      --      23-    29  19465742 *                                                                      0.7730 0.0966
      --      30-    37  18701986 *                                                                      0.7825 0.1053
      --      38-    46  20242496 *                                                                      0.7919 0.1164
      --      47-    56  21832395 *                                                                      0.8022 0.1314
      --      57-    67  27598455 **                                                                     0.8133 0.1512
      --      68-    79  52532119 ****                                                                   0.8278 0.1826
      --      80-    92 100220800 ********                                                               0.8560 0.2549
      --      93-   106 104209751 ********                                                               0.9081 0.4103
      --     107-   121  45653062 ***                                                                    0.9593 0.5848
      --     122-   137   9660484                                                                        0.9804 0.6665
      --     138-   154   3676918                                                                        0.9848 0.6859
      --     155-   172   3587367                                                                        0.9866 0.6950
      --     173-   191   3611123                                                                        0.9885 0.7053
      --     192-   211   2888914                                                                        0.9903 0.7166
      --     212-   232   1926034                                                                        0.9917 0.7265
      --     233-   254   1521736                                                                        0.9927 0.7338
      --     255-   277   1369475                                                                        0.9934 0.7402
      --     278-   301   1196586                                                                        0.9941 0.7465
      --     302-   326    988297                                                                        0.9947 0.7524
      --     327-   352    847318                                                                        0.9952 0.7578
      --     353-   379    770302                                                                        0.9956 0.7627
      --     380-   407    650833                                                                        0.9960 0.7676
      --     408-   436    554244                                                                        0.9964 0.7720
      --     437-   466    499202                                                                        0.9966 0.7760
      --     467-   497    446421                                                                        0.9969 0.7799
      --     498-   529    407374                                                                        0.9971 0.7837
      --     530-   562    360965                                                                        0.9973 0.7873
      --     563-   596    332232                                                                        0.9975 0.7907
      --     597-   631    303700                                                                        0.9977 0.7940
      --     632-   667    275757                                                                        0.9978 0.7972
      --     668-   704    243467                                                                        0.9980 0.8003
      --     705-   742    216956                                                                        0.9981 0.8032
      --     743-   781    200520                                                                        0.9982 0.8059
      --     782-   821    194909                                                                        0.9983 0.8086
      --
      --           0 (max occurrences)
      -- 57716252054 (total mers, non-unique)
      --  1970086378 (distinct mers, non-unique)
      --           0 (unique mers)
      -- Report changed.
      -- Finished stage 'meryl-process', reset canuIteration.
      --
      -- Removing meryl database 'trimming/0-mercounts/Ttri.ms22'.
      --
      -- OVERLAPPER (normal) (trimming) erate=0.045
      --
      ----------------------------------------
      -- Starting command on Wed Jan 27 10:06:54 2021 with 795516.506 GB free disk space
      
          cd trimming/1-overlapper
          /public3/soft/canu/2.0/Linux-amd64/bin/overlapInCorePartition \
           -S  ../../Ttri.seqStore \
           -hl 320000000 \
           -rl 15000000000 \
           -ol 500 \
           -o  ./Ttri.partition \
          > ./Ttri.partition.err 2>&1
      
      -- Finished on Wed Jan 27 10:06:55 2021 (one second) with 795516.506 GB free disk space
      ----------------------------------------
      --
      -- Configured 619 overlapInCore jobs.
      -- No change in report.
      -- Finished stage 'obt-overlapConfigure', reset canuIteration.
      -- No change in report.
      --
      -- Running jobs.  First attempt out of 2.
      ----------------------------------------
      -- Starting 'obtovl' concurrent execution on Wed Jan 27 10:06:56 2021 with 795516.331 GB free disk space (619 processes; 4 concurrently)
      
          cd trimming/1-overlapper
          ./overlap.sh 1 > ./overlap.000001.out 2>&1
          ./overlap.sh 2 > ./overlap.000002.out 2>&1
          ./overlap.sh 3 > ./overlap.000003.out 2>&1
          ./overlap.sh 4 > ./overlap.000004.out 2>&1`

When I check how many node I was using, the squeue command showed that only one node was working, which is not looks like a multi-node running model.

My best

**Comment by brianwalenz** [comment]
I'm guessing you ran this on a compute node or interactive login instead of the head node.  Canu gets confused when run that way and thinks it is running as "part of the pipeline" instead of running "to start the pipeline".

Try running, on the head node:
```
canu -trim -p Ttri -d ~/canu/result_file_max \
  maxThreads=64 maxMemory=256g \
  genomeSize=580m \
  minReadLength=2000 \
  minOverlapLength=500 \
  gridEngineArrayMaxJobs=9 \
  useGrid=true \
  -pacbio-corrected~/Ttri.correctedReads.fasta.gz
```
`useGrid=true` needs to be set so that canu will manage the grid jobs directly.  With 'remote', canu simply configures jobs but doesn't run anything.  

This will be good enough for testing.  Without increasing `canuIterationsMax` it will stop after a few iterations, but you should see some progress.

I removed the two `concurrency` options since they'll do nothing in this mode.

**Comment by skoren** [comment]
Idle
