### ISSUE TITLE
Running CANU on a SLURM cluster

### ISSUE THREAD

**Issue by aureliendejode** [marbl/canu#1886]
I try to run canu on a slurm cluster and I cannot find a solution that works with the grid option.
Is it possible that it is related to way the cluster is built ?
At the moment canu is running on one node but the ./mhap.sh 366 jobs are taking a very long time.

Here is the command line I used
```
canu useGrid=true gridOptions="-A snic2020-15-289" -p new_pacbio_all_third_library -d /proj/snic2020-6-155/canu_new_pacbio_all_third_lib-6-155 genomeSize=1.3g  -pacbio-raw /proj/snic2020-16-222
/PacBio/new_pacbio_all_third_library/Raw_reads/littorina_pacbio_new_pacbio_all_third_lib.fastq.gz
```
Here is the output I get, SLURM output file:

canu/2.0 has the useGrid option default set to useGrid=false. This can be overriden by another configuration file or a command-line option.
```
-- Canu 2.0
--
-- Detected Java(TM) Runtime Environment '1.8.0_151' (from '/sw/comp/java/x86_64/sun_jdk1.8.0_151/bin/java') with -d64 support.
-- Detected gnuplot version '4.6 patchlevel 2   ' (from 'gnuplot') and image format 'png'.
-- Detected 16 CPUs and 126 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /usr/bin/sinfo.
-- Detected Slurm with task IDs up to 1000 allowed.
-- 
-- Found 174 hosts with  16 cores and  124 GB memory under Slurm control.
-- Found   1 host  with  80 cores and 3997 GB memory under Slurm control.
-- Found  13 hosts with  16 cores and  249 GB memory under Slurm control.
-- Found  17 hosts with  16 cores and  499 GB memory under Slurm control.
--
--                         (tag)Threads
--                (tag)Memory         |
--        (tag)             |         |  algorithm
--        -------  ----------  --------  -----------------------------
-- Grid:  meryl     62.000 GB    8 CPUs  (k-mer counting)
-- Grid:  hap       16.000 GB   16 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   32.000 GB   16 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    16.000 GB   16 CPUs  (overlap detection)
-- Grid:  utgovl    16.000 GB   16 CPUs  (overlap detection)
-- Grid:  cor       24.000 GB    4 CPUs  (read correction)
-- Grid:  ovb        4.000 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       32.000 GB    1 CPU   (overlap store sorting)
-- Grid:  red       32.000 GB    8 CPUs  (read error detection)
-- Grid:  oea        8.000 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      256.000 GB   16 CPUs  (contig construction with bogart)
-- Grid:  cns        -.--- GB    8 CPUs  (consensus)
-- Grid:  gfa       32.000 GB   16 CPUs  (GFA alignment and processing)
--
-- In 'new_pacbio_all_third_library.seqStore', found PacBio CLR reads:
--   PacBio CLR:               1
--
--   Raw:                      1
--
-- Generating assembly 'new_pacbio_all_third_library' in '/crex/proj/snic2020-6-155/canu_new_pacbio_all_third_lib-6-155':
--    - correct raw reads.
--    - trim corrected reads.
--    - assemble corrected and trimmed reads.
--
-- Parameters:
--
--  genomeSize        1300000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0750 (  7.50%)
--
--
-- BEGIN CORRECTION
--
-- No change in report.
--
-- OVERLAPPER (mhap) (correction) complete, not rewriting scripts.
--
-- No change in report.
--
-- Running jobs.  First attempt out of 2.
--
-- 'mhap.jobSubmit-01.sh' -> job 3393293 tasks 206-721.
--
----------------------------------------
-- Starting command on Mon Dec 21 13:37:28 2020 with 533530.684 GB free disk space

    cd /crex/proj/snic2020-6-155/canu_new_pacbio_all_third_lib-6-155
    sbatch \
      --depend=afterany:3393293 \
      --cpus-per-task=1 \
      --mem-per-cpu=4g \
      -A snic2020-15-289  \
      -D `pwd` \
      -J 'canu_new_pacbio_all_third_library' \
      -o canu-scripts/canu.01.out  canu-scripts/canu.01.sh
Submitted batch job 3393294

-- Finished on Mon Dec 21 13:37:28 2020 (like a bat out of hell) with 533530.684 GB free disk space
```
I looked in the canu.01.out file but could not find an explanation why this has failed.
```
Found perl:
   /usr/bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /sw/comp/java/x86_64/sun_jdk1.8.0_151/bin/java
   java version "1.8.0_151"

Found canu:
   /sw/bioinfo/canu/2.0/rackham/Linux-amd64/bin/canu
   Canu 2.0

-- Canu 2.0
--
-- Detected Java(TM) Runtime Environment '1.8.0_151' (from '/sw/comp/java/x86_64/sun_jdk1.8.0_151/bin/java') with -d64 support.
-- Detected gnuplot version '4.6 patchlevel 2   ' (from 'gnuplot') and image format 'png'.
-- Detected 16 CPUs and 126 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /usr/bin/sinfo.
-- Detected Slurm with task IDs up to 1000 allowed.
-- 
-- Found 174 hosts with  16 cores and  124 GB memory under Slurm control.
-- Found   1 host  with  80 cores and 3997 GB memory under Slurm control.
-- Found  13 hosts with  16 cores and  249 GB memory under Slurm control.
-- Found  17 hosts with  16 cores and  499 GB memory under Slurm control.
--
--                         (tag)Threads
--                (tag)Memory         |
--        (tag)             |         |  algorithm
--        -------  ----------  --------  -----------------------------
-- Grid:  meryl     62.000 GB    8 CPUs  (k-mer counting)
-- Grid:  hap       16.000 GB   16 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   32.000 GB   16 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    16.000 GB   16 CPUs  (overlap detection)
-- Grid:  utgovl    16.000 GB   16 CPUs  (overlap detection)
-- Grid:  cor       24.000 GB    4 CPUs  (read correction)
-- Grid:  ovb        4.000 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       32.000 GB    1 CPU   (overlap store sorting)
-- Grid:  red       32.000 GB    8 CPUs  (read error detection)
-- Grid:  oea        8.000 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      256.000 GB   16 CPUs  (contig construction with bogart)
-- Grid:  cns        -.--- GB    8 CPUs  (consensus)
-- Grid:  gfa       32.000 GB   16 CPUs  (GFA alignment and processing)
--
-- In 'new_pacbio_all_third_library.seqStore', found PacBio CLR reads:
--   PacBio CLR:               1
--
--   Raw:                      1
--
-- Generating assembly 'new_pacbio_all_third_library' in '/crex/proj/snic2020-6-155/canu_new_pacbio_all_third_lib-6-155':
--    - correct raw reads.
--    - trim corrected reads.
--    - assemble corrected and trimmed reads.
--
-- Parameters:
--
--  genomeSize        1300000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0750 (  7.50%)
--
--
-- BEGIN CORRECTION
--
-- No change in report.
--
-- OVERLAPPER (mhap) (correction) complete, not rewriting scripts.
--
--
-- Mhap overlap jobs failed, retry.
--   job correction/1-overlapper/results/000206.ovb FAILED.
--   job correction/1-overlapper/results/000207.ovb FAILED.
[...]
--   job correction/1-overlapper/results/000720.ovb FAILED.
--   job correction/1-overlapper/results/000721.ovb FAILED.
--
-- No change in report.
--
-- Running jobs.  Second attempt out of 2.
--
-- 'mhap.jobSubmit-01.sh' -> job 3409349 tasks 206-721.
--
----------------------------------------
-- Starting command on Tue Dec 22 03:17:23 2020 with 536998.321 GB free disk space

    cd /crex/proj/snic2020-6-155/canu_new_pacbio_all_third_lib-6-155
    sbatch \
      --depend=afterany:3409349 \
      --cpus-per-task=1 \
      --mem-per-cpu=5g \
      -A snic2020-15-289  \
      -D `pwd` \
      -J 'canu_new_pacbio_all_third_library' \
      -o canu-scripts/canu.02.out  canu-scripts/canu.02.sh
Submitted batch job 3409350

-- Finished on Tue Dec 22 03:17:23 2020 (furiously fast) with 536998.321 GB free disk space
```

**Comment by brianwalenz** [comment]
It looks like the first 205 tasks completed successfully.  Which is a good sign.

Have a look at the various logging in correction/1-overlapper/mhap*out.  I'm going to guess you've exceeded some kind of quota.

**Comment by aureliendejode** [comment]
Thanks for your answer.
I just tried grep "quota"correction/1-overlapper/mhap*out but did not find anything.
I am having a closer look at those file at the moment. 

I started to run canu without the grid option and I think those 205 tasks completed successfully like that. The problem comes when I try to use the grid option.

**Comment by skoren** [comment]
Canu isn't designed to switch between on grid and off-grid in the middle of a run. Try removing all the shell scripts in 1-overlapper and re-try the run. If it still fails post one of the logs from the failed jobs as @brianwalenz said: `correction/1-overlapper/mhap*out`.

**Comment by aureliendejode** [comment]
Hey,

I just tried that and now I have this error:
ABORT:
ABORT: Canu 2.0
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to open 'correction/1-overlapper/mhap.sh'.

**Comment by skoren** [comment]
Yeah, as I was afraid, it's non-trivial to force it to re-generate scripts which are made for the grid in the middle of a run. Try removing the `queries.tar` file and the `ovljob.files` (both in 1-overlapper) outputs too. If that doesn't work, you'll have to remove the full 1-overlapper folder and re-start on grid.

**Comment by aureliendejode** [comment]
Hello,

I got many errors so I decided to start from scratch running canu on the grid.
I just received a new error because of a lack of memory.
What I don't understand is that with in grid mode canu choose how much memory to request for each job right ? I guess sometimes it makes mistake ?

To restart from where I am now should I just increase memory and rerun canu or is there files I need to remove ?

Thanks


more canu.02.out

Found perl:
   /usr/bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /sw/comp/java/x86_64/sun_jdk1.8.0_151/bin/java
   java version "1.8.0_151"

Found canu:
   /sw/bioinfo/canu/2.0/rackham/Linux-amd64/bin/canu
   Canu 2.0

-- Canu 2.0
--
-- Detected Java(TM) Runtime Environment '1.8.0_151' (from '/sw/comp/java/x86_64/sun_jdk1.8.0_151/bin/java') with -d64 support.
-- Detected gnuplot version '4.6 patchlevel 2   ' (from 'gnuplot') and image format 'png'.
-- Detected 16 CPUs and 126 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /usr/bin/sinfo.
-- Detected Slurm with task IDs up to 1000 allowed.
-- 
-- Found 174 hosts with  16 cores and  124 GB memory under Slurm control.
-- Found   1 host  with  80 cores and 3997 GB memory under Slurm control.
-- Found  13 hosts with  16 cores and  249 GB memory under Slurm control.
-- Found  17 hosts with  16 cores and  499 GB memory under Slurm control.
--
--                         (tag)Threads
--                (tag)Memory         |
--        (tag)             |         |  algorithm
--        -------  ----------  --------  -----------------------------
-- Grid:  meryl     62.000 GB    8 CPUs  (k-mer counting)
-- Grid:  hap       16.000 GB   16 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   32.000 GB   16 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    16.000 GB   16 CPUs  (overlap detection)
-- Grid:  utgovl    16.000 GB   16 CPUs  (overlap detection)
-- Grid:  cor       24.000 GB    4 CPUs  (read correction)
-- Grid:  ovb        4.000 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       64.000 GB    1 CPU   (overlap store sorting)
-- Grid:  red       32.000 GB    8 CPUs  (read error detection)
-- Grid:  oea        8.000 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      256.000 GB   16 CPUs  (contig construction with bogart)
-- Grid:  cns        -.--- GB    8 CPUs  (consensus)
-- Grid:  gfa       32.000 GB   16 CPUs  (GFA alignment and processing)
--
-- In 'new_pacbio_all_third_library.seqStore', found PacBio CLR reads:
--   PacBio CLR:               1
--
--   Raw:                      1
--
-- Generating assembly 'new_pacbio_all_third_library' in '/crex/proj/snic2020-6-155/canu_new_pacbio_all_third_lib-6-155':
--    - correct raw reads.
--    - trim corrected reads.
--    - assemble corrected and trimmed reads.
--
-- Parameters:
--
--  genomeSize        1300000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0750 (  7.50%)
--
--
-- BEGIN CORRECTION
--
-- No change in report.
-- Meryl finished successfully.  Kmer frequency histogram:
/var/spool/slurmd/job3724948/slurm_script : ligne 48 : 54224 Processus arrêté      /usr/bin/env perl $bin/canu 'useGrid=true' 'gridOptions=-A snic2020-15-289 -t 48:00:00' 
'ovsMemory=64g' -p 'new_pacbio_all_third_library' 'genomeSize=1.3g' -pacbio-raw '/crex/proj/snic2019-30-27/PacBio/new_pacbio_all_third_library/Raw_reads/littorina_pacbio_n
ew_pacbio_all_third_lib.fastq.gz' canuIteration=1
slurmstepd: error: Detected 1 oom-kill event(s) in step 3724948.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.

**Comment by skoren** [comment]
This particular step is handled within the Canu executive so it's controlled by the `executiveMemory` parameter. Canu always requests 4gb, in some cases this seems to not be enough, depending on how different grids implement memory tracking. I believe this was fixed post v2.0. Adding `executiveMemory=64` and restart and it should continue on.

**Comment by aureliendejode** [comment]
Hi,

Thanks your previous answer helped and everything went smoothly until the cns steps.
I get a lot of jobs with memory overflow. 



Found perl:
   /usr/bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /sw/comp/java/x86_64/sun_jdk1.8.0_151/bin/java
   java version "1.8.0_151"

Found canu:
   /sw/bioinfo/canu/2.0/rackham/Linux-amd64/bin/canu
   Canu 2.0

-- Canu 2.0
--
-- Detected Java(TM) Runtime Environment '1.8.0_151' (from '/sw/comp/java/x86_64/sun_jdk1.8.0_151/bin/java') with -d64 support.
-- Detected gnuplot version '4.6 patchlevel 2   ' (from 'gnuplot') and image format 'png'.
-- Detected 16 CPUs and 126 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /usr/bin/sinfo.
-- Detected Slurm with task IDs up to 1000 allowed.
-- 
-- Found 174 hosts with  16 cores and  124 GB memory under Slurm control.
-- Found   1 host  with  80 cores and 3997 GB memory under Slurm control.
-- Found  13 hosts with  16 cores and  249 GB memory under Slurm control.
-- Found  17 hosts with  16 cores and  499 GB memory under Slurm control.
--
--                         (tag)Threads
--                (tag)Memory         |
--        (tag)             |         |  algorithm
--        -------  ----------  --------  -----------------------------
-- Grid:  meryl     62.000 GB    8 CPUs  (k-mer counting)
-- Grid:  hap       16.000 GB   16 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   32.000 GB   16 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    16.000 GB   16 CPUs  (overlap detection)
-- Grid:  utgovl    16.000 GB   16 CPUs  (overlap detection)
-- Grid:  cor       24.000 GB    4 CPUs  (read correction)
-- Grid:  ovb        4.000 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       64.000 GB    1 CPU   (overlap store sorting)
-- Grid:  red       32.000 GB    8 CPUs  (read error detection)
-- Grid:  oea        8.000 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      256.000 GB   16 CPUs  (contig construction with bogart)
-- Grid:  cns        -.--- GB    8 CPUs  (consensus)
-- Grid:  gfa       32.000 GB   16 CPUs  (GFA alignment and processing)
--
-- In 'new_pacbio_all_third_library.seqStore', found PacBio CLR reads:
--   PacBio CLR:               1
--
--   Raw:                      1
--   Corrected:                1
--   Corrected and Trimmed:    1
--
-- Generating assembly 'new_pacbio_all_third_library' in '/crex/proj/snic2020-6-155/canu_new_pacbio_all_third_lib-6-155':
--    - assemble corrected and trimmed reads.
--
-- Parameters:
--
--  genomeSize        1300000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0750 (  7.50%)
--
--
-- BEGIN ASSEMBLY
--
-- No change in report.
-- Using slow alignment for consensus (iteration '2').
-- Configured 98 contig and 106 unitig consensus jobs.
-- No change in report.
--
--                         (tag)Threads
--                (tag)Memory         |
--        (tag)             |         |  algorithm
--        -------  ----------  --------  -----------------------------
-- Grid:  cns        2.139 GB    8 CPUs  (consensus)
--
--
-- Consensus jobs failed, tried 2 times, giving up.
--   job ctgcns/0086.cns FAILED.
--   job ctgcns/0087.cns FAILED.
--   job ctgcns/0088.cns FAILED.
--   job ctgcns/0089.cns FAILED.
--   job ctgcns/0090.cns FAILED.
--   job ctgcns/0091.cns FAILED.
--   job ctgcns/0092.cns FAILED.
--   job ctgcns/0093.cns FAILED.
--   job ctgcns/0094.cns FAILED.
--   job ctgcns/0095.cns FAILED.
--   job ctgcns/0096.cns FAILED.
--   job ctgcns/0097.cns FAILED.
--   job ctgcns/0098.cns FAILED.
--   job utgcns/0097.cns FAILED.
--   job utgcns/0098.cns FAILED.
--   job utgcns/0099.cns FAILED.
--   job utgcns/0100.cns FAILED.
--   job utgcns/0101.cns FAILED.
--   job utgcns/0102.cns FAILED.
--   job utgcns/0103.cns FAILED.
--   job utgcns/0104.cns FAILED.
--   job utgcns/0105.cns FAILED.
--   job utgcns/0106.cns FAILED.
--

ABORT:
ABORT: Canu 2.0
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:

I tried to restart but I got the same errors again. Is there a way to correct this ? Maybe some option to add more Memory for that step ?

**Comment by skoren** [comment]
It is trying to use only 2gb for that step. You can specify `cnsMemory=64` since you have plenty of memory and it will request more which should let these jobs complete.

**Comment by aureliendejode** [comment]
Hi,

Thanks for you help and fast answers, the assembly completed fine.
I plan to do some polishing with long and short reads now do you have any advice about the polishing step ?
Also I will use the purge_dup tool because I have a highly heterozygote genome and the assembly size I obtain is bigger than the expected genome size. Any thoughts about this ?

Thank you very much

**Comment by skoren** [comment]
I'd suggest following the VGP best practice (scaffold the purged assembly if you have the data), polish both the scaffolded assembly and the alts with arrow which also fills gaps, and finally run freebayes with short reads to polish (https://github.com/VGP/vgp-assembly).
