### ISSUE TITLE
Visual Assembly

### ISSUE THREAD

**Issue by zhoudreames** [marbl/canu#1888]
in your hificanu article,the picture is so nice showed in blow,I tried many ways to draw it ,but those are not good. can you provide me the code or method？thank you very much！
![image](https://user-images.githubusercontent.com/54714639/106358698-bc20e680-6348-11eb-8499-305268ad2b0b.png)

**Comment by zhoudreames** [comment]
@hyphaltip @jxtx @hartzell @jts could you help me ? thanks!

**Comment by hartzell** [comment]
Sorry, but not me.  My entire contribution to canu was correcting a typo of _architecture_.

**Comment by skoren** [comment]
It is very rude to open an issue on the weekend, wait less than a couple of hours then proceed to randomly tag people to force them to pay attention to you. Many of the people you tagged aren't even on the HiCanu paper. Further, you not only opened the issue, you then tweeted the same question again, tagging tons of people, again on a weekend. When you submit an issue wait at least 24-48 hours (or until the work week) for an answer before bothering everyone. You need to respect other people's time.

The article explains exactly how the image was made. The caption for the figure you posted says:
"Assemblies were aligned to GRCh38 using MashMap (Jain et al. 2018a) and plots were generated using coloredChromosomes (Böhringer et al. 2002) as previously described (Berlin et al. 2015; Jain et al. 2018b)." Those liked articles give all the details in their methods sections:
"Assemblies were aligned using MUMmer v3.23 with parameters “-l 20 -c 500 -maxmatch” for the raw assemblies and “-l 100 -c 500 -maxmatch” for the polished assemblies. Output was processed with dnadiff to report average 1-to-1 alignment identity. The MUMmer coords file was converted to a tiling using the scripts from Berlin et al.55 with the command:python convertToTiling.py 10000 90 100000 and drawn using the coloredChromosomes package", "The software and data used for this manuscript are available at http://www.cbcb.umd.edu/software/PBcR/. " When you go to that listed page, there is a package for drawing human ideograms like the above. So at least read carefully and try to solve the issue yourself before asking a question and then immediately start harassing people for answers. There are also newer tools besides coloredChromosomes to draw ideograms, for example take a look at karyotypeR. A google search for plot ideogram human genome" gives you this and several other options.
