### ISSUE TITLE
gatekeeperPartition failed

### ISSUE THREAD

**Issue by tangerzhang** [marbl/canu#189]
Hi,
I am running canu to assemble a big plant genome. In the gatekeeperPartion step, I got such error:
Any idea to fix it?
Thanks!

```
##########################################################################
#-- Finished on Thu Jul  7 08:35:45 2016 (48 seconds) with 144939.1 GB free disk space
#----------------------------------------
ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:
#============================================================================#====
Don't panic, but a mostly harmless error occurred and canu failed.

Disk space available:  144939.1 GB

Last 50 lines of the relevant log file (/share/bioinfo/zhangxt/project/2_AP85/3_canuAsm/asm/unitigging/5-consensus/AP85.partitioned.err):

Found 0 unpartitioned reads and maximum partition of 732
gkStore::gkStore_buildPartitions()-- ERROR: failed to open partition 511 file '/share/bioinfo/zhangxt/project/2_AP85/3_canuAsm/asm/unitigging/AP85.gkpStore/partitions/reads.0511' for write: Too many open files

canu failed with 'failed to partition the reads'.
```

**Comment by skoren** [comment]
This looks like a max open file limit, what does
```
ulimit -a
```
show? You can try running 
```
ulimit -Sn 4096
```
and re-run the failed command.

**Comment by tangerzhang** [comment]
I tried ulimit -Sn 4096 then type ulimit -a, it showed:
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 128194
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 4096
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1024
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

After I re-run the failed command, I still got the same error.
Any suggestion?
Thanks a lot!

**Comment by skoren** [comment]
According to the original logs there should be 732 partitions and there are two files per partition so a total of 732*2 or 1,464 should be enough. My guess is the default on your system was 1024 so 4096 should be enough. What was the output of the re-run command?

**Comment by tangerzhang** [comment]
Thanks for your response!
I attached the log file in unitigging/5-consensus/ folder.
I did not get more information except the open files problem.

**Comment by brianwalenz** [comment]
Attachments made through email unfortunately don't make it to the tracker on github.

Are you running interactively or through a grid?  If interactively, do the ulimit as above, then restart canu.  It should start with the gatekeeperPartition command that failed and, with the increased file limit, complete.

If through the grid, the easiest solution would be to run the gatekeeperPartition command, by hand, after ulimit is updated.  When that finishes, restart canu as before.

**Comment by brianwalenz** [comment]
No response.
