### ISSUE TITLE
install canu on system 76 with Pop OS

### ISSUE THREAD

**Issue by jjfid** [marbl/canu#1890]
jjf@system76-pc:~$ sudo apt install canu --fix-missing
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  aglfn binfmt-support ca-certificates-java default-jre-headless fastjar
  gnuplot gnuplot-data gnuplot-qt jaligner jarwrapper java-common
  libapache-pom-java libatinject-jsr330-api-java libcommons-compress-java
  libcommons-parent-java libfastutil-java libfilesys-df-perl libguava-java
  libjsr305-java libqt5printsupport5 libqt5svg5 libqt5widgets5 libssw-java
  libwxbase3.0-0v5 libwxgtk3.0-0v5 mhap openjdk-11-jre-headless
Suggested packages:
  pbgenomicconsensus nanopolish default-jre gnuplot-doc
  libatinject-jsr330-api-java-doc libxz-java libjsr305-java-doc
  fonts-dejavu-extra fonts-ipafont-gothic fonts-ipafont-mincho
  fonts-wqy-microhei | fonts-wqy-zenhei fonts-indic
The following NEW packages will be installed:
  aglfn binfmt-support ca-certificates-java canu default-jre-headless fastjar
  gnuplot gnuplot-data gnuplot-qt jaligner jarwrapper java-common
  libapache-pom-java libatinject-jsr330-api-java libcommons-compress-java
  libcommons-parent-java libfastutil-java libfilesys-df-perl libguava-java
  libjsr305-java libqt5printsupport5 libqt5svg5 libqt5widgets5 libssw-java
  libwxbase3.0-0v5 libwxgtk3.0-0v5 mhap openjdk-11-jre-headless
0 upgraded, 28 newly installed, 0 to remove and 338 not upgraded.
Need to get 49.1 MB/67.0 MB of archives.
After this operation, 240 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Ign:1 http://us.archive.ubuntu.com/ubuntu eoan-security/universe amd64 libqt5widgets5 amd64 5.12.4+dfsg-4ubuntu1.1
Err:2 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 libqt5svg5 amd64 5.12.4-1
  404  Not Found [IP: 91.189.91.39 80]
Ign:3 http://us.archive.ubuntu.com/ubuntu eoan-security/main amd64 openjdk-11-jre-headless amd64 11.0.7+10-2ubuntu2~19.10
Err:4 http://us.archive.ubuntu.com/ubuntu eoan/main amd64 libfilesys-df-perl amd64 0.92-6build3
  404  Not Found [IP: 91.189.91.39 80]
Ign:5 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 jarwrapper all 0.72.9
Ign:6 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 libcommons-compress-java all 1.18-3
Err:7 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 libssw-java amd64 1.1-2
  404  Not Found [IP: 91.189.91.39 80]
Ign:8 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 gnuplot-data all 5.2.6+dfsg1-2
Ign:9 http://us.archive.ubuntu.com/ubuntu eoan-security/universe amd64 libqt5printsupport5 amd64 5.12.4+dfsg-4ubuntu1.1
Err:10 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 libwxbase3.0-0v5 amd64 3.0.4+dfsg-12
  404  Not Found [IP: 91.189.91.39 80]
Err:11 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 libwxgtk3.0-0v5 amd64 3.0.4+dfsg-12
  404  Not Found [IP: 91.189.91.39 80]
Err:12 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 gnuplot-qt amd64 5.2.6+dfsg1-2
  404  Not Found [IP: 91.189.91.39 80]
Ign:13 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 gnuplot all 5.2.6+dfsg1-2
Err:14 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 canu amd64 1.8+dfsg-2
  404  Not Found [IP: 91.189.91.39 80]
Err:1 http://us.archive.ubuntu.com/ubuntu eoan-security/universe amd64 libqt5widgets5 amd64 5.12.4+dfsg-4ubuntu1.1
  404  Not Found [IP: 91.189.91.39 80]
Err:3 http://us.archive.ubuntu.com/ubuntu eoan-security/main amd64 openjdk-11-jre-headless amd64 11.0.7+10-2ubuntu2~19.10
  404  Not Found [IP: 91.189.91.39 80]
Err:5 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 jarwrapper all 0.72.9
  404  Not Found [IP: 91.189.91.39 80]
Err:6 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 libcommons-compress-java all 1.18-3
  404  Not Found [IP: 91.189.91.39 80]
Err:8 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 gnuplot-data all 5.2.6+dfsg1-2
  404  Not Found [IP: 91.189.91.39 80]
Err:9 http://us.archive.ubuntu.com/ubuntu eoan-security/universe amd64 libqt5printsupport5 amd64 5.12.4+dfsg-4ubuntu1.1
  404  Not Found [IP: 91.189.91.39 80]
Err:13 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 gnuplot all 5.2.6+dfsg1-2
  404  Not Found [IP: 91.189.91.39 80]
Unable to correct missing packages.
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/q/qtbase-opensource-src/libqt5widgets5_5.12.4+dfsg-4ubuntu1.1_amd64.deb  404  Not Found [IP: 91.189.91.39 80]
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/q/qtsvg-opensource-src/libqt5svg5_5.12.4-1_amd64.deb  404  Not Found [IP: 91.189.91.39 80]
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/o/openjdk-lts/openjdk-11-jre-headless_11.0.7+10-2ubuntu2~19.10_amd64.deb  404  Not Found [IP: 91.189.91.39 80]
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/libf/libfilesys-df-perl/libfilesys-df-perl_0.92-6build3_amd64.deb  404  Not Found [IP: 91.189.91.39 80]
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/j/javatools/jarwrapper_0.72.9_all.deb  404  Not Found [IP: 91.189.91.39 80]
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/libc/libcommons-compress-java/libcommons-compress-java_1.18-3_all.deb  404  Not Found [IP: 91.189.91.39 80]
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/libs/libssw/libssw-java_1.1-2_amd64.deb  404  Not Found [IP: 91.189.91.39 80]
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/g/gnuplot/gnuplot-data_5.2.6+dfsg1-2_all.deb  404  Not Found [IP: 91.189.91.39 80]
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/q/qtbase-opensource-src/libqt5printsupport5_5.12.4+dfsg-4ubuntu1.1_amd64.deb  404  Not Found [IP: 91.189.91.39 80]
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/w/wxwidgets3.0/libwxbase3.0-0v5_3.0.4+dfsg-12_amd64.deb  404  Not Found [IP: 91.189.91.39 80]
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/w/wxwidgets3.0/libwxgtk3.0-0v5_3.0.4+dfsg-12_amd64.deb  404  Not Found [IP: 91.189.91.39 80]
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/g/gnuplot/gnuplot-qt_5.2.6+dfsg1-2_amd64.deb  404  Not Found [IP: 91.189.91.39 80]
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/g/gnuplot/gnuplot_5.2.6+dfsg1-2_all.deb  404  Not Found [IP: 91.189.91.39 80]
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/c/canu/canu_1.8+dfsg-2_amd64.deb  404  Not Found [IP: 91.189.91.39 80]
E: Aborting install.
jjf@system76-pc:~$ 

When I follow the links to the 404 fetch not found http addresses I get URL not found error:

Not Found

The requested URL was not found on this server.

**Comment by brianwalenz** [comment]
Nothing we control or can fix.  That looks like an Ubuntu problem.  For what it's worth, I get 404's when I click on the link too.

Canu 1.8 is over two years old.  Are your packages up to date?

**Comment by jjfid** [comment]
Thank you for the quick reply

I downloaded 2.1.1 .tar.gz

then I ran the tar command which created a canu 2.1.1 directory in my home directory

then ran the sudo apt install command


________________________________

**Comment by skoren** [comment]
There's no reason to run sudo apt install if you're downloading the binary from the release page. Follow the instructions there.
Once the folder is extracted you can run Canu by giving the path to the extracted folder (e.g. `canu-2.1.1/bin/canu` or add it to your PATH so you only have to type `canu`). Running sudo apt install is going to install a completely new and different version of canu.

**Comment by jjfid** [comment]
Wow! Do I feel dumb?
That works. 
Thank you!
