### ISSUE TITLE
unitigs.gfa output suitable for bandage graph?

### ISSUE THREAD

**Issue by TC-Hewitt** [marbl/canu#1894]
Hi. This was an old issue (https://github.com/marbl/canu/issues/72) and back then, the unitigs.gfa output was not suitable for visualisation using bandage.  Was just wondering if there has been any update on this as I can't find any? I was able to create some bandage graphs from the latest Canu versions but not sure if what I'm looking at is a suitable representation. Thanks.

**Comment by skoren** [comment]
It can be displayed in Bandage yes. However, the graph may be incomplete (missing edges) and in some cases over-split which is why we deprecated it.
