### ISSUE TITLE
Canu stalled at the utgovl step 

### ISSUE THREAD

**Issue by Brent-Saylor-Canopy** [marbl/canu#1895]
Hi I am running canu 2.1 on a AWS instance with 64CPUs and  498 GB of RAM using the following command:

canu  -p CANU.asm -d denovo_genome_03_hifi  genomeSize=850m  -pacbio-hifi Raw_reads/subreads_HiFi_ccs.fastq.gz &> Canu.test_run2.txt

The process seems to die off without any error I can see at the utgovl step.
the following is the end of my log file. 

```-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'utgovl' concurrent execution on Mon Feb  8 19:17:56 2021 with 1138.755 GB free disk space (90 processes; 4 concurrently)

    cd unitigging/1-overlapper
    ./overlap.sh 1 > ./overlap.000001.out 2>&1
    ./overlap.sh 2 > ./overlap.000002.out 2>&1
    ./overlap.sh 3 > ./overlap.000003.out 2>&1
    ./overlap.sh 4 > ./overlap.000004.out 2>&1
    ./overlap.sh 5 > ./overlap.000005.out 2>&1
    ./overlap.sh 6 > ./overlap.000006.out 2>&1
    ./overlap.sh 7 > ./overlap.000007.out 2>&1
```

Digging into the files the contents of unitigging/1-overlapper/001 indicate that files 1-4 seem to have finished, and some of the others start and others don't. 

Again it seems weird that I'm not getting an execution error or anything the program just seems to stop.

Any help you may be able to provide would be much appreciated. I'm new to canu and AWS both.

**Comment by skoren** [comment]
What do you mean stop? Unless it reports a specific error message it will just keep launching jobs (it's running 4 at a time) until it finishes all of them. It's likely it's just waiting here for some jobs to complete.

**Comment by Brent-Saylor-Canopy** [comment]
That's that I would have guessed. But there is almost no CPU usage/ memory usage / disc change that I am seeing. The top command only shows unrelated processes running.

**Comment by Brent-Saylor-Canopy** [comment]
I left it to running for days and checked on the file sizes marked working. Here are the results.

`Fri Feb 12 16:22 UTC 2021
total 28140
-rw-r--r-- 1 root root 7860572 Feb 11 20:27 000001.oc
-rw-r--r-- 1 root root  371537 Feb 11 20:27 000001.ovb
-rw-r--r-- 1 root root     253 Feb 11 20:27 000001.stats
-rw-r--r-- 1 root root 7860572 Feb 11 20:28 000002.oc
-rw-r--r-- 1 root root 1161421 Feb 11 20:28 000002.ovb
-rw-r--r-- 1 root root     255 Feb 11 20:28 000002.stats
-rw-r--r-- 1 root root 7860572 Feb 11 20:29 000003.oc
-rw-r--r-- 1 root root 1872407 Feb 11 20:29 000003.ovb
-rw-r--r-- 1 root root     255 Feb 11 20:29 000003.stats
-rw-r--r-- 1 root root 1798144 Feb 11 20:29 000004.ovb.WORKING
-rw-r--r-- 1 root root       0 Feb 11 20:27 000005.ovb.WORKING
-rw-r--r-- 1 root root       0 Feb 11 20:28 000006.ovb.WORKING
-rw-r--r-- 1 root root       0 Feb 11 20:29 000007.ovb.WORKING
Fri Feb 12 19:06:51 UTC 2021
total 28140
-rw-r--r-- 1 root root 7860572 Feb 11 20:27 000001.oc
-rw-r--r-- 1 root root  371537 Feb 11 20:27 000001.ovb
-rw-r--r-- 1 root root     253 Feb 11 20:27 000001.stats
-rw-r--r-- 1 root root 7860572 Feb 11 20:28 000002.oc
-rw-r--r-- 1 root root 1161421 Feb 11 20:28 000002.ovb
-rw-r--r-- 1 root root     255 Feb 11 20:28 000002.stats
-rw-r--r-- 1 root root 7860572 Feb 11 20:29 000003.oc
-rw-r--r-- 1 root root 1872407 Feb 11 20:29 000003.ovb
-rw-r--r-- 1 root root     255 Feb 11 20:29 000003.stats
-rw-r--r-- 1 root root 1798144 Feb 11 20:29 000004.ovb.WORKING
-rw-r--r-- 1 root root       0 Feb 11 20:27 000005.ovb.WORKING
-rw-r--r-- 1 root root       0 Feb 11 20:28 000006.ovb.WORKING
-rw-r--r-- 1 root root       0 Feb 11 20:29 000007.ovb.WORKING
Tue Feb 16 14:17:36 UTC 2021
total 28140
-rw-r--r-- 1 root root 7860572 Feb 11 20:27 000001.oc
-rw-r--r-- 1 root root  371537 Feb 11 20:27 000001.ovb
-rw-r--r-- 1 root root     253 Feb 11 20:27 000001.stats
-rw-r--r-- 1 root root 7860572 Feb 11 20:28 000002.oc
-rw-r--r-- 1 root root 1161421 Feb 11 20:28 000002.ovb
-rw-r--r-- 1 root root     255 Feb 11 20:28 000002.stats
-rw-r--r-- 1 root root 7860572 Feb 11 20:29 000003.oc
-rw-r--r-- 1 root root 1872407 Feb 11 20:29 000003.ovb
-rw-r--r-- 1 root root     255 Feb 11 20:29 000003.stats
-rw-r--r-- 1 root root 1798144 Feb 11 20:29 000004.ovb.WORKING
-rw-r--r-- 1 root root       0 Feb 11 20:27 000005.ovb.WORKING
-rw-r--r-- 1 root root       0 Feb 11 20:28 000006.ovb.WORKING
-rw-r--r-- 1 root root       0 Feb 11 20:29 000007.ovb.WORKING`

**Comment by Brent-Saylor-Canopy** [comment]
This ended up being an issue specific to AWS. Thanks for the help.
