### ISSUE TITLE
Restart support in version 1.7

### ISSUE THREAD

**Issue by andrew-niaid** [marbl/canu#1897]
I have a user doing a large assembly with version 1.7 (for their own reasons) and would like to know if the [restart feature mentioned in the FAQ](https://canu.readthedocs.io/en/latest/faq.html#my-run-of-canu-was-killed-by-the-sysadmin-the-power-going-out-my-cat-stepping-on-the-power-button-et-cetera-is-it-safe-to-restart-how-do-i-restart) applied to 1.7. I see this question addressed in the the FAQ source for the v1.9-maintenance branch, but not in the v1.7.1 branch FAQ source.

**Comment by brianwalenz** [comment]
The restarts have been there since day zero.  They're actually essential to how the pipeline itself works.

Kudos for actually checking the old FAQs!

**Comment by andrew-niaid** [comment]
Perfect, thanks.
