### ISSUE TITLE
Non-deterministic behavior v 2.1.1 different # threads

### ISSUE THREAD

**Issue by ekopylova** [marbl/canu#1899]
Hello,

The same Canu command ran on three different AWS instances (4 threads, 8 threads, 16 threads) gave me 3 different assembly results. The input data were HiFI PacBio reads for a microbial genome at 500x coverage. It seems that with fewer number of threads, I obtained a shorter primary assembly, fewer # contigs and with 4 threads ```suggestCircular=yes```. Is this behavior expected? Do you suggest to use fewer threads? Thanks!

```Canu command used:```

/canu-2.1.1/bin/canu -d asm -p bc genomeSize=2.6m -pacbio-hifi bc.fastq.gz

```Machine 1: Linux 16 threads```
-- Detected Java(TM) Runtime Environment '12.0.2' (from 'java') without -d64 support.
-- Detected gnuplot version '5.2 patchlevel 8   ' (from 'gnuplot') and image format 'png'.
-- Detected 16 CPUs and 29 gigabytes of memory.
-- No grid engine detected, grid and staging disabled.

canu result: 9 contigs, primary contig:

>tig00000001 len=2545269 reads=11995 class=contig suggestRepeat=no suggestBubble=no suggestCircular=no trim=0-2545269

```Machine 2: Linux 8 threads```
-- Detected Java(TM) Runtime Environment '12.0.2' (from 'java') without -d64 support.
-- Detected gnuplot version '5.2 patchlevel 8   ' (from 'gnuplot') and image format 'png'.
-- Detected 8 CPUs and 15 gigabytes of memory.
-- No grid engine detected, grid and staging disabled.

canu result: 6 contigs, primary contig:

>tig00000001 len=2537288 reads=12051 class=contig suggestRepeat=no suggestBubble=no suggestCircular=no trim=0-2537288

```Machine 3: Linux 4 threads```
-- Detected Java(TM) Runtime Environment '12.0.2' (from 'java') without -d64 support.
-- Detected gnuplot version '5.2 patchlevel 8   ' (from 'gnuplot') and image format 'png'.
-- Detected 4 CPUs and 15 gigabytes of memory.
-- No grid engine detected, grid and staging disabled.

canu result: 5 contigs, primary contig:

>tig00000007 len=2534820 reads=12069 class=contig suggestRepeat=no suggestBubble=no suggestCircular=yes trim=5235-2528695

**Comment by skoren** [comment]
I don't think it's the threads, so there is no recommendation to use fewer threads. With HiFi data, the default is to downsample to a random 50x subset and since you have much more than that, you're assembling different reads every time you run it. I expect if you check the self-alignment of the top contig, you'd find it is circular as well. Canu can sometimes miss the circularization overlap. I also expect if you compared the two assemblies I expect they'll be near-identical.

**Comment by ekopylova** [comment]
Thanks @skoren ! The downsampling to random 50x makes sense and explains the different assemblies. I do see the primary contigs to be almost identical regardless of number of threads (based on 4 microbial genome assemblies), however it appears that overall more contigs are assembled with 16 threads rather than 4, is that anything to worry about? Thanks!!

***Genome 1***
*threads = 16*
9 contigs, primary contig:
>tig00000009 len=2571575 reads=12143 class=contig suggestRepeat=no suggestBubble=no suggestCircular=yes trim=6488-2565809

*threads = 4*
4 contigs, primary contig:
>tig00000005 len=2572844 reads=12238 class=contig suggestRepeat=no suggestBubble=no suggestCircular=yes trim=6433-2565752

***Genome 2***
*threads = 16*
9 contigs, primary contig:
>tig00000001 len=2545269 reads=11995 class=contig suggestRepeat=no suggestBubble=no suggestCircular=no trim=0-2545269

*threads = 4*
5 contigs, primary contig:
>tig00000007 len=2534820 reads=12069 class=contig suggestRepeat=no suggestBubble=no suggestCircular=yes trim=5235-2528695

***Genome 3***
*threads = 16*
9 contigs, primary contig:
>tig00000010 len=2508047 reads=12207 class=contig suggestRepeat=no suggestBubble=no suggestCircular=yes trim=5648-2500180

*threads = 4*
4 contigs, primary contig:
>tig00000005 len=2508516 reads=12296 class=contig suggestRepeat=no suggestBubble=no suggestCircular=yes trim=6965-2501495

***Genome 4***
*threads = 16*
8 contigs, primary contig:
>tig00000010 len=2561712 reads=12013 class=contig suggestRepeat=no suggestBubble=no suggestCircular=yes trim=6165-2553893

*threads = 4*
6 contigs, primary contig:
>tig00000001 len=2560580 reads=12055 class=contig suggestRepeat=no suggestBubble=no suggestCircular=yes trim=8459-2556185

**Comment by skoren** [comment]
No the number of contigs will vary with the input reads because you might capture some rare variants or read errors in one case and not in another due to the differential sampling of the data.
