### ISSUE TITLE
quick question(s) on heterozygosity

### ISSUE THREAD

**Issue by JohnUrban** [marbl/canu#190]
Hi @skoren 

Recently we had an email exchange where I asked about how to mess around with parameters for heterozygous genomes in 1.3 as compared to 1.2:

 >I have always found that your advice on re-running bogart with the second number in the -repeatdetect parameter being 3X the guessed X coverage gave a significant boost to NG50 and the max contig size. Will that still be possible in Canu 1.3? 

Your response was helpful, but I have some questions:
>In Canu 1.3 there are a couple of flags you can tune for heterozygosity, first is the number of deviations to use when auto-computing the error rate for your dataset (-dg, -db, -dr). The default is 6, I would say in your case use 2 or 1 as this will help avoid merging haplotypes so you get parallel assemblies for both. The other is the stringency of the repeat splitting, this is two values, the first is number of bases, the second is percent for how much better an overlap is than the alternate before it is breaking. The default is 5000 and 500 which means the overlap must be 5000 bases or 5 times longer than the next best in an ambiguous region (-ca and -cp). You can drop it to as low as 500 50 without introducing too much error. So, I’d suggest sweeping these parameters for your genome.

(i) Are these flags (-dg, -db, -dr, -ca, -cp) just added to the Canu command? Or are these bogart parameters?
(ii) When you say I will get parallel assemblies for both, will Canu recognize them as parallel and let me know? e.g. will one be in bubbles and the other in the contigs.fasta file?

I ran a Canu assembly with the latest code, default settings. There was only 1 sequence in bubbles.fasta, which was somewhat surprising to me. I guess I'd expect more. Any thoughts?

**Comment by skoren** [comment]
1. Some of the flags are exposed as Canu parameters but it is easiest to pass them directly to bogart through the batOptions flag.
2. Yes it should flag the parallel assembly into bubbles, however, @brianwalenz recently found a bug in the implementation (see issue #188) so until it's fixed it's going to under-call the bubbles in the assembly which is probably why there is only 1 bubble in the asm.bubbles.fasta file while the rest are output into asm.contigs.fasta

**Comment by JohnUrban** [comment]
Thanks again. I hope the bubble problem is an easy fix.

**Comment by JohnUrban** [comment]
Anyone reading this thread/interested in heterozygosity, also see:
#201
