### ISSUE TITLE
Canu 2.1.1 Storage issue at correction/1-overlapper 

### ISSUE THREAD

**Issue by fallean15** [marbl/canu#1900]
Hello,

I am running canu 2.1.1 to assemble pacbio sequel II reads for an insect with an estimated genome size of 1.9 Gbps. I am running all of this over SLURM. I initially ran the default parameters of canu but ran out of storage space (20T), so I looked at your FAQ page and found options that were recommended to add under "My assembly is running out of space, is too slow?".

The command I ran was:

`canu -p veletis -d output corMhapFilterThreshold=0.0000000002 corMhapOptions="--threshold 0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50" mhapMemory=60g mhapBlockSize=500 ovlMerDistinct=0.975 gridOptions="--time=15:00:00" genomeSize=1.96g -pacbio ~/projects/def-bsincla7/arteen/veletis/raw_reads/pacbio/fastq/longread_c1.fastq ~/projects/def-bsincla7/arteen/veletis/raw_reads/pacbio/fastq/longread_c2.fastq`

 I let this run but it is about halfway through the jobs for correction/1-overlapper and is at 15T out of 20T that I have available. Most of the size is in correction/1-overlapper/results in the *.ovb files.

Are there any other options/tweaks that I can potentially use to reduce the storage size that you know of? I hope that made sense, I can clarify anything if necessary.

Thanks for the help!

**Comment by skoren** [comment]
The genome appears to be very repetitive. If you have high coverage (more than 50x), you can further adjust the stringency to use ```--min-overlap-length 5000 --num-hashes 256 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 16 -k 18```. This will require you to restart the assembly from scratch. You could avoid changing the -k option from the default of 16 if you don't want to do that. Aim to keep the output of 1-overlapper under 10TB to fit into the 20TB constraint and increase the min overlap length to fit.

**Comment by fallean15** [comment]
Okay thanks, I'll restart and try with those options. Do you know if it's possible to reduce the number of CPUs that the script requests per job because it's currently at 16 and I'm suspecting that it is lower my job priority on SLURM and causing my jobs to take a very long time to start running. Thanks anyways!

**Comment by skoren** [comment]
You can set maxThreads which will limit any submitted job to that limit.

**Comment by fallean15** [comment]
Okay cool, do you know if there’s a minimum number that canu needs in order to complete its jobs or would I be safe to leave it at 1 or 2?
