### ISSUE TITLE
canu-2.2.1+: utgcns crash in transformSequences()

### ISSUE THREAD

**Issue by mmokrejs** [marbl/canu#1901]
Hi,
  I have repeatedly crashing canu-2.1.1 here but the stacktrace I was seeing in `mygenome_canu_2.1.1_correctedErrorRate_0.30_v9/unitigging/5-consensus/consensus.000023.out` was without details. I went to fetch current `git master` code and to compile with `make -j 2 CXXFLAGS=-ggdb CFLAGS=-ggdb` and resolved the stacktrace manually.

  Here is the full log: 
[canu.crash.txt](https://github.com/marbl/canu/files/6025988/canu.crash.txt)

**Comment by skoren** [comment]
Are you able to share the data as following the instructions on the FAQ/#1864?

**Comment by mmokrejs** [comment]
```
35G     my_genome_canu_2.1.1_correctedErrorRate_0.30_v9/unitigging/my_genome_genome.ctgStore
54G     my_genome_canu_2.1.1_correctedErrorRate_0.30_v9/my_genome_genome.seqStore
```
```
-rw------- 1 mmokrejs meta 2,8G Feb 23 00:48 my_genome_canu_2.1.1_correctedErrorRate_0.30_v9/unitigging/5-consensus/core
```

I could run some `gdb` commands for you would that help. It would be easier for me I guess. If you really want those 35+54GB of data, I will ask the PI. But it is from another lab, so two might be involved in the decision.

**Comment by skoren** [comment]
OK got it and will take a look this week, thanks.

**Comment by skoren** [comment]
I ran both the 2.1.1 release and the latest tip (snapshot v2.2-development +96 changes (r10205 f1eadb317cc2731fc4a2a10c222c684d830919cc) without any errors on all 73 partitions. I'll track down where we're doing an invalid access w/o error on our system. In the meantime, I can also share the consensus job output so you could finish your run. Just to confirm, what is the consensus command in consensus.sh? This is what I used: 
```
$bin/utgcns \
  -R ../Eresinifera_genome.ctgStore/partition.$jobid \
  -T ../Eresinifera_genome.ctgStore 1 \
  -P $jobid \
  -O ./ctgcns/$jobid.cns.WORKING \
  -maxcoverage 40 \
  -V -V -V -e 0.3 \
  -pbdagcon \
  -edlib    \
  -threads 4 \
```

**Comment by mmokrejs** [comment]
```
$bin/utgcns \
  -R ../Eresinifera_genome.ctgStore/partition.$jobid \
  -T ../Eresinifera_genome.ctgStore 1 \
  -P $jobid \
  -O ./ctgcns/$jobid.cns.WORKING \
  -maxcoverage 40 \
  -e 0.30 \
  -pbdagcon \
  -edlib    \
  -threads 8 \
```

**Comment by mmokrejs** [comment]
Weird, I hit the same errors several times so I felt it is reproducible. At that time. Isn't the stacktrace from `core` dump helpful? I still have it along with the debug binary on the system. Well, having a chance to continue with this would be nice. I have a few more assembly assembly attempts running with same input data but who knows when they will finsih. So, yes please. ;-) And thank you for your efforts.

**Comment by mmokrejs** [comment]
BTW: I asked PBSpro to give me 64 CUs so he difference between `4` and `8` is maybe attributed to the number of CPUs per partition, dynamically caclulatd on the fly. Provided the values are stored in the config files generated by `canu` maybe that is the culprit? Although, I think I ran them on same machines during the moments when it was crashing reproducibly. Do you want me to run the `utgcns` command iwth the extra verbose args here? Or shall I even pass them to the top-most `canu` command?

**Comment by skoren** [comment]
You can download the files here: https://obj.umiacs.umd.edu/sergek/seqdata/cns.tar.bz2?AWSAccessKeyId=ND7WFDFYKH6OWJD76YW3&Signature=phc%2B9WfoIIIm6fPONm0d5p7Inn8%3D&Expires=1616040103 (md5: `1a581f7a6044bbad6a50de308edf0c2e`). This link will expire in 48 hrs. I wouldn't expect the number of threads to matter, but yes the 8 was auto-set based on your available nodes and I defaulted to 4. I have my suspicion on what's going wrong but if you could run an offending partition with the `-V -V -V` option and single-threaded, that will help track it down to the read and contig in question which will help confirm.

**Comment by mmokrejs** [comment]
Per the stack traces it happened with partiton0030 but I could reproduce with others, like 32 and 24 now. Here is when I re-run with `-V -V -V -`threads 1`:

```
-- Using seqFile '../my_genome.ctgStore/partition.0024'.
-- Opening tigStore '../my_genome.ctgStore' version 1.
-- Opening output results file './ctgcns/0024.cns.WORKING'.
--
-- Computing consensus for b=0 to e=4451966 with errorRate 0.3000 (max 0.4000) and minimum overlap 500
--
                           ----------CONTAINED READS----------  -DOVETAIL  READS-
  tigID    length   reads      used coverage  ignored coverage      used coverage
------- --------- -------  -------- -------- -------- --------  -------- --------
Loading corrected-trimmed reads from seqFile '../my_genome.ctgStore/partition.0024'
   3470      9978       5         2    0.46x        0    0.00x         3    1.07x

generateTemplateStitch()-- COPY READ read #0 3577900 (len=548 to 0-548)

generateTemplateStitch()-- read #1/5 ident 368240 position 164-8067 SAVE THIN FIRST
generateTemplateStitch()-- WARNING, increasing min overlap from 384 to 7897 for read 1 (164 - 8067

generateTemplateStitch()-- ALIGN template -6560-548 (len=7108) to read #1 368240 0-7897 (len=7897 actual=7897 at 164-8067)  expecting olap of 7897

Failed with 'Segmentation fault'
```

**Comment by skoren** [comment]
Please see if the above commit fixes your crash

**Comment by mmokrejs** [comment]
Works! My terminal is now flooded by lots of nucleotides in the output .... Thank you.
