### ISSUE TITLE
Generating contigs with smashed haplotypes

### ISSUE THREAD

**Issue by A-J-F-Mackintosh** [marbl/canu#1904]
Hi,

I have used canu (2.0) to assemble an insect genome with high (>1%) heterozygosity from Pacbio CLR data. I used the recommended batOptions for assembling both haplotypes separately.

`canu -assemble -p my_species -d /scratch/amackintosh/my_species.canu genomeSize=501m -pacbio-corrected /scratch/amackintosh/my_species.canu/my_species.trimmedReads.fasta.gz useGrid=false "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50"`

The assembly is 1.1Gb, which is very close to 2x the expected size. However, I do also want a haploid representation of the genome. One way to do this would be to use purge_dups, but I think there is information is the assembly graph that is not being used by purge_dups. In the example below, purge_dups would return contig_A, contig_B, and a small portion of contig_D (D'), all as separate contigs. But there could be an unambiguous path in the assembly graph that connects these contigs into one, which I have represented as a 'smashed haplotypes' contig.

```
Maternal haplotype assembly :    [      contig_A      ]    [   contig_B      ]
Paternal haplotype assembly :    [  contig_C  ] [   contig_D   ] [ contig_E  ]

Purge_dups:    [      contig_A      ][ c_D' ][   contig_B      ]

Smashed haplotypes:    [                contig_A_D'_B                ]
```

So, my question is whether there is a good way to infer a set of 'smashed haplotype' contigs. The wiki suggests increasing the error rate, but maybe a better (and quicker) way would be to generate contigs from  `my_species.unitigs.gfa` using more aggressive batOptions?

Any suggestions would be much appreciated.

Best,

Alex

**Comment by skoren** [comment]
I don't think you're likely to get a much more continuous assembly from the smashed strategy. Insects usually have large SVs between haplotypes like inversions so there's really no way to reasonably smash them, no matter the higher error rate. If you do want to try, definitely do not use the unitigs.gfa but instead start from the trimmed reads you already have and run only the assembly step. I'd personally follow the VGP strategy of purging followed by scaffolding and polishing/gap-filling with arrow which will solve the issue you're concerned about above (assuming the contigs have spanning reads that can be mapped during polishing to gap fill)

**Comment by A-J-F-Mackintosh** [comment]
Hi,

Many thanks for your advice. I think I will try both approaches - rerunning the assembly stage and purge_dups + gap filling.

Best,

Alex
