### ISSUE TITLE
Some consensus jobs fail at cns step

### ISSUE THREAD

**Issue by calvincicha** [marbl/canu#1905]
Hello,

I have been running an assembly of a metagenomic sample for the last week.

version:
```
canu snapshot v2.2-development +75 changes (r10184 4dd74b57b79f25aa2aa845f0cac6f87c346fd584)
```

here is the command:
```
canu -p mag_bac -d /home/calvinc/Roland_mag_bacteria_2_3_21/CANU_assembly/ genomeSize=10m corOutCoverage=all maxInputCoverage=all corMhapSensitivity=high corMinCoverage=0 redMemory=128 oeaMemory=128 batMemory=500 maxThreads=128 maxMemory=1000G -nanopore /home/calvinc/Roland_mag_bacteria_2_3_21/mag_bac/mag_bac/20210203_2017_MN33966_FAO06901_13e1aad4/fastq_pass/*.fastq
```

I am running it on a Linux server with 128 threads and 1tb RAM

A subset of the threads failed at the `cns` step. 3 jobs failed, but all of the other jobs passed.

 ```
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'cns' concurrent execution on Thu Feb 25 10:10:46 2021 with 8002.889 GB free disk space (3 processes; 32 concurrently)

    cd unitigging/5-consensus
    ./consensus.sh 13 > ./consensus.000013.out 2>&1
    ./consensus.sh 17 > ./consensus.000017.out 2>&1
    ./consensus.sh 19 > ./consensus.000019.out 2>&1

-- Finished on Thu Feb 25 10:32:59 2021 (1333 seconds) with 8002.887 GB free disk space
----------------------------------------
-- Using slow alignment for consensus (iteration '2').
-- Configured 20 consensus jobs.
--
-- Consensus jobs failed, tried 2 times, giving up.
--   job ctgcns/0013.cns FAILED.
--   job ctgcns/0017.cns FAILED.
--   job ctgcns/0019.cns FAILED.
```
Due to this failure the program stops and does not generate an assembly.

Thanks for your time.

**Comment by skoren** [comment]
It looks like you're on an intermediate commit after the 2.1.1 release but there have been some fixes to CNS crashes since then (see #1878). I suggest updating to at least #e90f476574c423dfba0b02252e58a2cb035169ff and re-launching the same Canu command. It should resume and try the failed jobs again. If it still crashes, post the log from one of the jobs (`unitigging/5-consensus/consensus.000013.out` for example) here.

**Comment by skoren** [comment]
Any update?

**Comment by calvincicha** [comment]
I updated the program and the run completed successfully.

Thanks for your time.

From: Sergey Koren ***@***.***>
Date: Monday, March 15, 2021 at 10:35 AM
To: marbl/canu ***@***.***>
Cc: Cicha, Calvin ***@***.***>, Author ***@***.***>
Subject: Re: [marbl/canu] Some consensus jobs fail at cns step (#1905)

Any update?

**Comment by skoren** [comment]
Thanks for the update, glad it worked.
