### ISSUE TITLE
GRID requires a minimum of 4 GB of virtual memory for using JDK version 1.8.0

### ISSUE THREAD

**Issue by carolhsb** [marbl/canu#1908]
Hello, 

I am using canu - version 2.1.1, installed via anaconda, in an SGE GRID. My grid requires a minimum of 4 GB of virtual memory for using JDK version 1.8.0.  If I don't put this requirement JDK doesn't initialize.

This is how I am running my job:

```
#!/bin/sh
# Grid Engine options (lines prefixed with #$)
#$ -N canu
#$ -l h_vmem=4G

# Initialise the environment modules
. /etc/profile.d/modules.sh

# Load anaconda
module load anaconda
source activate canu

# Run the program
canu -correct -p canu -d canu genomeSize=1.036g -pacbio /pacbio/raw_reads.fa -correctedErrorRate=0.035 
-gridEngineResourceOption="-pe mpi THREADS -l h_vmem=MEMORY"

```
I am getting the following error:

```
CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '11.0.8-internal' (from '/conda/envs/canu/bin/java') without -d64 support.
-- Detected gnuplot version '5.4 patchlevel 1   ' (from 'gnuplot') and image format 'png'.
-- Detected 20 CPUs and 63 gigabytes of memory.
-- Detected Sun Grid Engine in '/exports/applications/gridengine/ge-8.6.5/eddieUGE'.
-- User supplied Parallel Environment 'mpi'.
-- User supplied Memory Resource      'h_vmem'.
Can't exec "qhost": No such file or directory at /conda/envs/canu/bin/../lib/site_perl/canu/Grid_SGE.pm line 349.
readline() on closed filehandle F at /conda/envs/canu/bin/../lib/site_perl/canu/Grid_SGE.pm line 351.
readline() on closed filehandle F at /conda/envs/canu/bin/../lib/site_perl/canu/Grid_SGE.pm line 352.
readline() on closed filehandle F at /conda/envs/canu/bin/../lib/site_perl/canu/Grid_SGE.pm line 364.
--
-- WARNING:  No hosts found in 'qhost' report.
-- WARNING:  Will use maxMemory= and maxThreads= instead.
-- ERROR:    maxMemory not defined!
-- ERROR:    maxThreads not defined!

ABORT:
ABORT: canu branch HEAD +0 changes (r10117 5638f7d9a5379373310ab62c28aa0cdbd864722d)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   maxMemory or maxThreads not defined.

```

How can I work it out?

Thanks in advance,

Carol

**Comment by skoren** [comment]
The error doesn't really have anything to do with JDK. Your grid seems like it's not supported by Canu. We've not tested on UGE and it seems to be missing common SGE modules like qhost which is causing the error (qhost is what canu uses to determine what nodes are available on your cluster to process jobs). You can see at some older issues like #392 for possible workarounds. In particular set maxMemory and maxThreads to be about half of your available nodes on the cluster. Canu will then not rely on qhost to figure out resources.

There may be other incompatibilities between UGE and SGE. In that case, your only option will be to run w/o using the grid with `useGrid=false maxMemory=<whatever you requested from your grid> maxThreads=<whatever you requested from your grid>` which will run on the single node you've launched on and will likely take a while for a 1gb genome.

**Comment by carolhsb** [comment]
Hi Koren,

Thank you for your answer. I will try to run on a SLURM grid.

Cheers,

Carol
