### ISSUE TITLE
Assembly statistics query

### ISSUE THREAD

**Issue by devenderarora** [marbl/canu#1914]
Dear Canu Team,
I have assembled PacBio sequenced data using canu assembler and I have received great support for that. After the assembly our aim was to polish the contigs and used gcpp.
During statistics comparison we have observed same number of contigs in both canu assembled and polished genome. Only marginal change in contig size has been reported. 
My understanding to polishing and earlier work suggest that there should be decrease in total number of contig. What possible mistake we would have done during the process. Please share your experience and suggestion to improve our assembled genome.

Regards
Devender Arora

**Comment by skoren** [comment]
Polishing only makes minor base corrections, it won't erase contigs or remove them so the number of bases and number of contigs shouldn't change. If you scaffold your assembly before polishing, arrow will fill some of these gaps which can reduce your contig count, depending on how many gaps are filled.

**Comment by devenderarora** [comment]
Respected Sir,
Thankyou so much. I was totally messed up with scaffold and polishing.
