### ISSUE TITLE
Canu 2.1.1 Issue with creating *.corStore.WORKING

### ISSUE THREAD

**Issue by fallean15** [marbl/canu#1915]
Hello hope all is well, I previously had issue  #1900 but I think I'm stuck at another point now. 

My command is:

`canu -p veletis -d out corMhapFilterThreshold=0.0000000002 corMhapOptions="--threshold 0.80 --min-olap-length 10000 --num-hashes 256 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 16  --repeat-idf-scale 50" mhapMemory=60g mhapBlockSize=500 ovlMerDistinct=0.975 gridOptions="--time=12:00:00" gridEngineArrayOption="-a ARRAY_JOBS%175" maxThreads=16 genomeSize=1.96g -pacbio ~/projects/def-bsincla7/arteen/veletis/raw_reads/pacbio/longread_c1.fastq ~/projects/def-bsincla7/arteen/veletis/raw_reads/pacbio/longread_c2.fastq`

Canu has finished bucketizing the overlaps and is creating *.corStore.WORKING. This initially ran but timed out because of the time limit I previously set and created 1.1 G of seqDB.v001.dat. After it timed out I re-ran my assembly and it picked back up at this stage, but instead of working with what was already there, it started to remake the file and timed out again.

Is there a way to work around this? I looked at canu.out and it seems like the script it sends is:

`cd correction
    /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/canu/2.1.1/bin/generateCorrectionLayouts \
      -S ../veletis.seqStore \
      -O  ./veletis.ovlStore \
      -C  ./veletis.corStore.WORKING \
      -eC 80 \
    > ./veletis.corStore.err 2>&1`

Could I just create a script with a longer run time with this command and then once it completes re-run my assembly?

Any help is appreciated!

**Comment by skoren** [comment]
This particular step is atomic so it has to complete and if it gets killed in the middle, Canu will re-start it from scratch. You're specifying a time of 12 hrs in the grid options in your command. You can increase that to a longer time like 96 (or whatever your grid is OK with) which will increase the time for all jobs including this one. You could also increase the time for only this step using `gridOptionsExecutive="--time=96:00:00"`

**Comment by fallean15** [comment]
Okay and so the executive option is just for the main canu script that submits jobs and creates this *.corStore.WORKING correct? Also if I were to adjust this parameter (add `gridOptionsExecutive="--time=96:00:00"`) would resubmitting the job resume canu at that last step or restart entirely?

**Comment by brianwalenz** [comment]
You are definitely safe restarting, it will resume where it left off.

> Could I just create a script with a longer run time with this command and then once it completes re-run my assembly?

Some commands will work with this trick, but some will not.  If it doesn't work, canu will just rerun the command again.  generateCorrectionLayouts looks like one that will work.  Unless you're familiar with the internals of Canu, I'd suggest against trying it in general.

**Comment by fallean15** [comment]
I added the parameter executive grid option that you recommended so my code is:

`canu -p veletis -d out corMhapFilterThreshold=0.0000000002 corMhapOptions="--threshold 0.80 --min-olap-length 10000 --num-hashes 256 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 16  --repeat-idf-scale 50" mhapMemory=60g mhapBlockSize=500 ovlMerDistinct=0.975 gridOptionsExecutive="--time=96:00:00" gridOptions="--time=12:00:00" gridEngineArrayOption="-a ARRAY_JOBS%175" maxThreads=16 genomeSize=1.96g -pacbio ~/projects/def-bsincla7/arteen/veletis/raw_reads/pacbio/longread_c1.fastq ~/projects/def-bsincla7/arteen/veletis/raw_reads/pacbio/longread_c2.fastq`


but it still only ran the job that creates *.corStore.WORKING for 12 hours instead of 96, I'm not sure if I did something wrong?

**Comment by skoren** [comment]
I confirmed your parameters should be OK, the job submitted requesting the gridExecutiveMemory options. Are you launching Canu on a head node or on a compute node you reserved yourself first?

**Comment by skoren** [comment]
Any update?

**Comment by skoren** [comment]
Idle, no reply. Likeliest explanation is canu starting on a interactive node with lower time limit as in #1838
