### ISSUE TITLE
canu errors on correction, step is building

### ISSUE THREAD

**Issue by signor-molevol** [marbl/canu#1916]
Canu version 2.1

```
Command:  ./canu -correct -d org_correct/ -p org_correct -nanopore-raw org_2_3_2021.fastq org_409.fastq org_411.fastq org_415.fastq org_428.fastq org_456.fastqorg_457.fastq useGrid=false genomeSize=200000000
```
Error in the output is:
```
--   job correction/org_correct.ovlStore.BUILDING/0706 FAILED.
--   job correction/org_correct.ovlStore.BUILDING/0707 FAILED.
--   job correction/org_correct.ovlStore.BUILDING/0708 FAILED.
```
Or that is a sample, and it is present for some but not all of the #'s for example 225 seems to have worked, anything after 908 worked, etc. 

Errors in org_correct/correction/org_correct.ovlStore.BUILDING/logs/  are about 50/50 split between the two following, with the first error showing up in earlier numbers and the second in later numbers:

Error in one file: 
```
ERROR: short read on file './org_correct.ovlStore.BUILDING/bucket0097/slice0125': read 567194 bytes, expected 679819.
```

Error in another log file:

```
AS_UTL_loadFile()-- File './org_correct.ovlStore.BUILDING/bucket0107/sliceSizes' contains 0 objects, but asked to load 1043.
````

Others seem to have worked just fine:

```
Sorting.

Writing sorted overlaps.
  created './org_correct.ovlStore.BUILDING/1042' with 82072571 overlaps for reads 6727008 to 6728552.

Removing bucketized overlaps.

Success!
```
This is what an example of the sliceSizes are, some of them do appear to be missing:
```


-rw-rw-r-- 1 sarahs sarahs  24M Mar  7 01:40 slice0896
-rw-rw-r-- 1 sarahs sarahs  20M Mar  7 01:40 slice0897
-rw-rw-r-- 1 sarahs sarahs  20M Mar  7 01:40 slice0898
-rw-rw-r-- 1 sarahs sarahs  24M Mar  7 01:40 slice0899
-rw-rw-r-- 1 sarahs sarahs  24M Mar  7 01:40 slice0900
-rw-rw-r-- 1 sarahs sarahs    0 Mar  7 01:40 slice0901
-rw-rw-r-- 1 sarahs sarahs    0 Mar  7 01:40 slice0902
-rw-rw-r-- 1 sarahs sarahs    0 Mar  7 01:40 slice0903
-rw-rw-r-- 1 sarahs sarahs    0 Mar  7 01:40 slice0904

```

**Comment by skoren** [comment]
This is usually a disk issue, are you out of quota space or disk space? Often the FS fails to report these errors back to the process so Canu doesn't realize than the writes did not complete. It's also possible the FS got overloaded and lost data during the write as well. Once you confirm you have space/quota available, you'll need to re-create the bad buckets (see #1044 for another example). Look for all failed sorting jobs and what buckets they have and common. Make a list of all buckets which caused the errors. What you'll want to do is remove those bucket folders and re-run scripts/1-bucketize.sh <failed job> for each of them. Hopefully there are only a couple of buckets causing issues. Then, try one of the failing sort jobs by hand (e.g. scripts/2-sort.sh 706).

**Comment by skoren** [comment]
Idle, looks like I/O or space issues.
