### ISSUE TITLE
use canu -haplotype to bin short-reads like RNAseq data

### ISSUE THREAD

**Issue by zhen0506** [marbl/canu#1923]
Hi, 
I tested using canu -haplotype to bin RNAseq(150PE) data. There was no phased reads due to a read length filtering. Is there an option to turn the filtering step off?
If not, is there any software available which uses parental kmer to phase short reads?
Thank you very much.

**Comment by zhen0506** [comment]
I used this script, it is running now.
$bin/splitHaplotype \
  -cl 100 \
  -threads 8 \
  -memory  12 \

**Comment by skoren** [comment]
Canu has an option of minReadLength which would let you drop the length: https://canu.readthedocs.io/en/latest/tutorial.html#minimum-lengths. Running the binning directly is also OK. I'll note that the binning is designed to work on long reads and with 150bp data, you're unlikely to have a haplotype k-mer unless your genome has a very high heterozygosity. I expect most of your reads are going to end up as unclassified.
