### ISSUE TITLE
Using hicanu 2.1.1 in a mock metagenomic dataset

### ISSUE THREAD

**Issue by xfengnefx** [marbl/canu#1927]
Hi, I used hicanu 2.1.1 to assemble two Hifi mock metagenomic datasets, the Zymo D6331 standard input (SRR13128014) and the ATCC MSA-1003 (SRR11606871) on a linux server. I referred to the settings mentioned in #1796 and used the following parameters: `maxInputCoverage=1000 genomeSize=4m batMemory=200` with the `-pacbio-hifi` switch. There was no additional settings.

The zymo assembled very well, judging from dotter plots generated with reference assemblies. The ATCC mock however, struggled with most of the less prevalent species in the mix, specifically the 1.80% and 0.18% ones; the 0.02% species were not recoverable in other assemblers. 

The ATCC mock dataset has very high coverage for the prevalent species (18.0%) which goes up to more than 300x iirc, and the second prevalent species only share a 1.80% of all contents each. It is highly redundant. The zymo mock community also displayed coverage differences and redundancy, but milder. I'm not sure how would this affect hicanu, but other than the coverage issues, the ATCC mock communitiy seems to be not more complex than the zymo's. The `genomeSize=4m` was a rough guess; the actually genome sizes lay between 2M~6M for both datasets.

Would you recommend a different hicanu setting, or some read selection pipeline before assembling for the ATCC mock? Thank you!

**Comment by skoren** [comment]
Are you sure there's enough coverage of the low-abundance species to assemble them more continuously? Are you still filtering coverage at maxInputCoverage=1000? If so, you can increase it further.

**Comment by xfengnefx** [comment]
@skoren  Thanks for the previous suggestion! I tried `maxThreads=48 maxInputCoverage=600 genomeSize=50m batMemory=200 -pacbio-hifi` with canu 2.1.1 on a linux machine, the assembly did not finish, but i can't quite find the error message. 

`dmesg` did not mention killing because of memory (is there a keyword that i should grep?). Here what was written to the end of canu log files:

##### STDERR 
```
----------------------------------------
--
-- Configured 379 overlapInCore jobs.
-- Finished stage 'utg-overlapConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'utgovl' concurrent execution on Fri Apr  2 16:12:59 2021 with 3147.485 GB free disk space (379 processes; 6 concurrently)
    cd unitigging/1-overlapper
    ./overlap.sh 1 > ./overlap.000001.out 2>&1
    ./overlap.sh 2 > ./overlap.000002.out 2>&1
// omitting a few lines here for brevity
    ./overlap.sh 29 > ./overlap.000029.out 2>&1
    ./overlap.sh 30 > ./overlap.000030.out 2>&1
// end of file
```
##### dummy.report
// omiiting kmer histogram and stats here
--           0 (max occurrences)
-- 21818664493 (total mers, non-unique)
--    49470529 (distinct mers, non-unique)
--           0 (unique mers)
// end of file
```

Previously if a run crashes i usually see something in STDERR, but this time there's none. I wonder which part went wrong and how could i fix it?

**Comment by xfengnefx** [comment]
Increasing the two parameteres resolved the problem. Thank you!
