### ISSUE TITLE
How to get the raw sequence used for assembly?

### ISSUE THREAD

**Issue by baishengjun** [marbl/canu#1929]
Hello,

Thank you very much for this awesome software.
Each contig should be assembled by many raw sequences, so how to get the raw sequence information used for assembly?  For example, I have one contig, and I want to know which raw sequences were assembled to this contig.

Thanks a lot
Bai.

**Comment by brianwalenz** [comment]
See `<prefix>.contigs.layout.readToTig` at the bottom of https://canu.readthedocs.io/en/latest/tutorial.html#outputs.

Not mentioned on the page is that the coordinates are from the corrected and trimmed version of the read, not the original raw input read.
