### ISSUE TITLE
Canu fails: unable to submit jobs

### ISSUE THREAD

**Issue by meganlsmith** [marbl/canu#1931]
Hello, I am using canu to assemble two lanes of PacBio sequencing data for a terrestrial slug. The command that I ran was: 

canu -p prophysaon -d prophysaon  gridOptions="-l vmem=400gb,walltime=10:00:00" useGrid=true genomeSize=1.54g -pacbio-raw ./fastq/*.fq

I am running this on an HPC, and things seemed to have been doing well, until it crashed saying that a job could not be submitted. I understand that this may be on the HPC's side of things, rather than on canu's, but I'm having trouble figuring out which job didn't submit, so that I can look more closely at the job file and see if there is an issue. I am attaching my .out file here, which includes the error message at the bottom. Thanks for any insight you're able to share.

Sincerely,
Megan Smith
[canu.out.txt](https://github.com/marbl/canu/files/6286688/canu.out.txt)

**Comment by skoren** [comment]
This looks like some of the initial jobs failed and the re-try failed. I expect it didn't like the list of dependencies rather than a single dependency. PBS is often causing issues as we don't have access to one for testing and there are large changes between versions. You've also got a pretty old version of Canu so I would suggest updating to 2.1.1 as some PBS issues have been fixed. 

The real question is why are most of your initial jobs failing. One of the failed job logs (`correction/1-*/mhap.*.out`) should have more details. Often it is an issue with JVM configuration on the grid or an incorrect resource request.

**Comment by meganlsmith** [comment]
Hi Sergey,
Thanks for the quick response. The reason I am using the older version of
Canu is because it's what was preinstalled and set up to work on the HPC
I'm using. Many of the initial jobs did run, it seems. Canu has been
running for a long time (> 2 months) and has produced ~24 TB of files.
Ideally, I don't want to have to start over from scratch at this point. Is
it possible that these jobs that failed could be rerun without rerunning
all of the other jobs which didn't fail? If I update to the newest version,
will I need to start from scratch?
Best,
Megan
Megan L. Smith, PhD
NSF Postdoctoral Research Fellow
Department of Biology
Indiana University

**Comment by meganlsmith** [comment]
Hello,
I have tried restarting the assembly using the newest version of Canu. I am now seeing another error (shown in the log file attached in this email.

**Comment by skoren** [comment]
GitHub doesn't post email attachments so we can't see the error. Can you copy/paste it into the email or upload on GitHub directly.

**Comment by meganlsmith** [comment]
[canu.txt](https://github.com/marbl/canu/files/6353365/canu.txt)

Apologies, uploading the file on GitHub now.

**Comment by skoren** [comment]
That looks like meryl is failing, can you upload the output files from that step (`correction/0-*/*.out`)?

**Comment by meganlsmith** [comment]
[meryl-out.zip](https://github.com/marbl/canu/files/6353388/meryl-out.zip)
Okay, those files are in the .zip I just uploaded. Thanks!

**Comment by brianwalenz** [comment]
They're getting killed for exceeding the slurm time limit.

Add `gridOptions="-t 2-0"` to get a time limit of 2 days for all pieces.  You can tune this for specific components...but that's usually tedious and not useful.  https://canu.readthedocs.io/en/latest/parameter-reference.html#grid-options

**Comment by meganlsmith** [comment]
Thanks; that seems to be working. 

I also wanted to check one other thing about the output. The log file says:
In 'porphysaon.seqStore' found Pacbio CLR reads:
PacBio CLR: 2
Raw: 1
I had two lanes that I am trying to assemble (there are two .fq files in the directory I provide for my raw reads). I am wondering Raw: 1 means that canu is only detecting one of these for some reason?

Thanks again.
Best,
Megan

**Comment by brianwalenz** [comment]
It's a little misleading: the 'units' aren't displayed.  The message is saying canu found two input files and that the "raw" flag is true.  Newer versions report simply `Found untrimmed raw Nanopore reads in the input files.`

**Comment by meganlsmith** [comment]
Hi Brian, Okay, that makes sense. Thanks for the help!
