### ISSUE TITLE
Failed with exit code 1.  (rc=256)  AS_UTL_renane()--  Failed to rename file

### ISSUE THREAD

**Issue by ericgonzalezs** [marbl/canu#1932]
Hi, I am using the next canu command line:
#!/bin/bash
#run canu assembly on ccs.bam
#runs as: bash hicanu.sh *ccs.fastq prefix directory
#prefix for the results
#directory for saving result
module load StdEnv/2020 canu/2.1.1
FASTQ=$1
PREFIX=$2
DIRECTORY=$3
#Canu
canu \
 -p $PREFIX \
 -d $DIRECTORY \
 genomeSize=3.5g \
 useGrid=true \
 gridOptions="-A  -gropupA -t 4-1" \
 gridEngineArrayOption="-a ARRAY_JOBS%99" \
 -pacbio-hifi $FASTQ

I am running canu/2.1.1 on a SLURM cluster

I am having the next error:

ERROR:  Failed with exit code 1.  (rc=256)
ERROR:

ABORT:
ABORT: canu 2.1.1
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   sqStoreCreate failed; boom!.
ABORT:
ABORT: Disk space available:  970901.253 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (./ANN1372_hicanu_def.seqStore.err):
ABORT:
ABORT:
ABORT:   Found perl:
ABORT:      /cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/perl/5.30.2/bin/perl
ABORT:      This is perl 5, version 30, subversion 2 (v5.30.2) built for x86_64-linux-thread-multi
ABORT:
ABORT:   Found java:
ABORT:      /cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/java/13.0.2/bin/java
ABORT:      openjdk version "13.0.2" 2020-01-14
ABORT:
ABORT:   Found canu:
ABORT:      /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/canu/2.1.1/bin/canu
ABORT:      canu 2.1.1
ABORT:
ABORT:
ABORT:   Creating library 'Sequel.RunS142_S2.002.ANN1372-3.ccs' for PacBioHiFi corrected-trimmed reads.
ABORT:
ABORT:                  reads               bases
ABORT:   ---------- --------- ------ ------------ ------
ABORT:   Loaded       1229869 100.0%  26899654172 100.0%  /project/6019339/egonza02/PacBio_HiFi_8x/ALIGNMENTS/NGMLR/Sequel.RunS142_S2.002.ANN1372-3.ccs.fasta
ABORT:
ABORT:
ABORT:   All reads processed.
ABORT:
ABORT:                  reads               bases
ABORT:   ---------- --------- ------ ------------ ------
ABORT:   Loaded       1229869 100.0%  26899654172 100.0%
ABORT:
ABORT:   AS_UTL_renane()--  Failed to rename file './ANN1372_hicanu_def.seqStore.BUILDING/libraries' to './ANN1372_hicanu_def.seqStore.BUILDING/version.001/libraries': Remote address
changed
ABORT:
Coudl you please tell what is happening?

**Comment by skoren** [comment]
The error isn't coming from Canu but from the filesystem saying a file was already removed. It looks like you may have had two runs using the same folder. Did you launch Canu with the same parameters more than once? I suggest removing the working directory, making sure you have no jobs in the SLURM queue, and launching the assembly again. It will submit itself to the grid and exit. You'll be able to monitor it using the grid scheduler and the canu output files.

**Comment by ericgonzalezs** [comment]
Sorry for my late response, I solved this by running it in a different cluster. However I came back to this cluster and I followed your instructions, however, the error is the same. Any suggestions?

**Comment by skoren** [comment]
If it's working on one cluster and not the other, there must be some file system difference between the two. You could try running in a different volume (if you have more than one). No other suggestions besides that.
