### ISSUE TITLE
hicanu: geneme size greater than expext

### ISSUE THREAD

**Issue by LILIHAN-001** [marbl/canu#1933]
Hi,

I use the hicanu both `-untrimmed` and `default` parameter to assembly my genome, but both the genome size is greater than I expect. (expected: 1.67G, obsevered: 3.35G )
I know the reason caused it is high heterozygosity, But I need use the depth method to identify the sex chromosome, `purge_dups` not only remove the uncolllapsed allel but also sex-linked regions. Do you have any ideas about the problem?

Thanks!

**Comment by skoren** [comment]
The "normal" sex chromosomes don't usually get removed by purge_dups because they are not that similar to each other so don't have alignments to suggest removal. It's likely you need to tune purge_dups's cutoffs for HiFi datasets as the defaults it picks are often incorrect. Purge_dups also provides details on why a certain contig was removed in the output file so if you know the ones being incorrectly removed you can look up why and adjust the run accordingly.

**Comment by StevenBai97** [comment]
> The "normal" sex chromosomes don't usually get removed by purge_dups because they are not that similar to each other so don't have alignments to suggest removal. It's likely you need to tune purge_dups's cutoffs for HiFi datasets as the defaults it picks are often incorrect. Purge_dups also provides details on why a certain contig was removed in the output file so if you know the ones being incorrectly removed you can look up why and adjust the run accordingly.

Hi, I have some confusion about purge_dups. When running "pbcstat read-aln.paf", I didn't achieve “PB.base.cov”, and only got “PB.stat” (only 4.7 KB). Errors are “Error in `pbcstat': double free or corruption (out): 0x000055a1ef6dc6c0” and “Aborted (core dumped)”. I don't know the reason.

Command:
minimap2 -I 16G -t 40 -x map-pb assembly.contigs.fa raw.HiFi.fasta > read-aln.paf
pbcstat read-aln.paf

Here is "PB.stat": 
[PB.zip](https://github.com/marbl/canu/files/6310930/PB.zip)

I’ll really appreciate your suggestions.
Thanks a lot.

**Comment by skoren** [comment]
@StevenBai97 I suggest asking this on the purge_dups GitHub page since we don't develop or maintain it.

**Comment by wyim-pgl** [comment]
Hi Sergey, @skoren 
Just curiosity, if we sequence XX type human genome, is it possible to get two haploid type X chromosomes after purge_dups?
I know this is not purge_dups Github but you are the one who know this answer.
> The "normal" sex chromosomes don't usually get removed by purge_dups because they are not that similar to each other so 
don't have alignments to suggest removal.

**Comment by LILIHAN-001** [comment]
Hi, 
I use the 'purge_dups' to deal with my genome obtained from hicanu, but the genome size only dropped to **3.22G** (Gneome size before purge_dups: **3.35G**). At the same time, the second peaks in PB.stat is not obvious, but the kmer graph have a obvious second peaks. 

Here is  K-mer graph, PB.stat before tune the cutoffs and after tune the cutoffs of purge_dups:
[cc_kmer.pdf](https://github.com/marbl/canu/files/6333061/cc_kmer.pdf)
[PB.stat.pdf](https://github.com/marbl/canu/files/6333018/PB.stat.pdf)
[PB.stat.v1.pdf](https://github.com/marbl/canu/files/6333019/PB.stat.v1.pdf)

Is the genome have a higher heterozygosity so that could't meet the criterion of purge_dups: 0.5x depth and 70% alignrate? I can't get a good explanation.  

Appreciate your suggestions.
Thanks!

**Comment by skoren** [comment]
@wyim-pgl yes, I expect you would get most of the X as two copies though the contigs would have lots of switches between the haplotypes. You can check this in the HiCanu assemblies from the publication. Specifically HG0733 from here: https://obj.umiacs.umd.edu/marbl_publications/hicanu/index.html is a female human sample so you can evaluate how much of the X chromosome was separated.

@LILIHAN-001 This is normal with HiFi data. The k-mer distribution is showing that your genome is relatively diverse. Not too high as the first peak is not larger than the second. Certainly something that purge_dups can handle. The reason you have no second peak in the PB.stat.pdf is that the entire genome has been separated into two haplotypes by HiCanu. There are almost no regions which are collapsed diploid representations. purge_dups does a bad job selecting thresholds in these cases. See a long discussion of how to set thresholds for purge_dups in #1814 and on the purge_dups GitHub as well: https://github.com/dfguan/purge_dups/issues/38.

**Comment by skoren** [comment]
Idle
