### ISSUE TITLE
Consensus jobs failed, tried 2 times, giving up

### ISSUE THREAD

**Issue by guangtugao** [marbl/canu#1934]
Hello,

I/m running canu with about 29x coverage of ccs reads for a genome about 2.4Gb in size. I got the error message at the CNS stage:
-- Consensus jobs failed, tried 2 times, giving up.
--   job ctgcns/0058.cns FAILED.
--   job ctgcns/0059.cns FAILED.
--

ABORT:
ABORT: canu 2.1.1
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:_

 I then checked the file consensus.5752873_58.out and here is the error message:

Killed $bin/utgcns -R ../swanson.ctgStore/partition.$jobid -T ../swanson.ctgStore 1 -P $jobid -O ./ctgcns/$jobid.cns.WORKING -maxcoverage 40 -e 0.05 -pbdagcon -edlib -threads 8
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=5752891.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.

Here is the canu command I ran:
canu -p swanson -d hicanu_untrimmed genomeSize=2.4g gridOptionsBAT="-p mem" -untrimmed \
     -pacbio-hifi /home/guangtu.gao/rainbow_trout/Swanson/ccs_fastq/*.ccs.fastq.gz

I also tried this command in the second run:
canu -p swanson -d hicanu_untrimmed genomeSize=2.4g gridOptions="-p mem" -untrimmed \
     -pacbio-hifi /home/guangtu.gao/rainbow_trout/Swanson/ccs_fastq/*.ccs.fastq.gz
and still have the issue.

Please advise me how to deal with this issue.

Thanks,
Guangtu

**Comment by guangtugao** [comment]
The error message should be:
Killed                  $bin/utgcns -R ../swanson.ctgStore/partition.$jobid -T ../swanson.ctgStore 1 -P $jobid -O ./ctgcns/$jobid.cns.WORKING -maxcoverage 40 -e 0.05 -pbdagcon -edlib -threads 8
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=5752891.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.

**Comment by guangtugao** [comment]
I think I found the solution for this problem. I increased the size of memory per cpu with the option of:
gridOptions="-p mem --mem-per-cpu=10G".

Thanks,
Guangtu

**Comment by skoren** [comment]
Increasing memory is the right solution (see for example #1930). However, increasing it via gridOptions is not ideal as that would affect every job submitted by Canu. It is better to set cnsMemory=80 which will accomplish the same thing (8 core consensus jobs and 10gb/cpu).

**Comment by guangtugao** [comment]
Ah, that's the best way to do it. Thank you Sergey!
Guangtu
