### ISSUE TITLE
grid parameter

### ISSUE THREAD

**Issue by jenny315** [marbl/canu#1938]
Hi, (CANU 2.1.1) If I want to run on a grid, but one node is dedicated for another thing and so cannot be occupied, is there a way to set it up so that canu can run on all nodes except this one?

Thanks for any advice,
Best regards,
Jenny

**Comment by brianwalenz** [comment]
That will be grid and site specific.  There is no mechanism in canu to do such a thing, but you can set grid-specific options for canu to use when submitting jobs with the gridOptions parameter.

Here's our docs on grid engine support:
https://canu.readthedocs.io/en/latest/parameter-reference.html#grid-engine-support

**Comment by jenny315** [comment]
Thanks  for your advice.

Best regards,
Jenny

**Comment by brianwalenz** [comment]
It should work out of the box with PBS (and Slurm and SGE).  The string you quoted is the default (I think) one that canu uses for PBS.  It's requesting one node, with a certain number of CPUs and memory.  Canu will replace THREADS and MEMORY with values it thinks are appropriate for the job it wants to run.

`gridOptions` (I'll point out here, this is a completely different thing than the `gridEngine*` options) allows you to supply other options, for example, an option that tells PBS to use only a certain class of nodes, or to use a certain charge account, or to set a maximum time limit.

The `gridEngine*` options are mostly internal settings for canu and, in most cases, should not be changed.  I can't think of them ever being set by a user - and *definitely* don't go changing defaults in the code (yet).  I applaud the effort, and it's a great way to figure out what canu is doing though!

If you can figure out the PBS option to restrict canu from using a specific node, that option can be supplied to canu with `gridOptions` -- an example to tell SGE to use only nodes in the queueu 'general.q' would be `gridOptions="-q general.q"`.

**Comment by jenny315** [comment]
Thanks for your reply and sorry for my late reply.

Is it mean that the general.q file is generated by myself, if I can figure out the PBS option to restrict using a specific node?

Thanks for any advice,
Best regards,
Jenny

**Comment by jenny315** [comment]
Thank you very much, the setup is successful!

Best regards,
Jenny
