### ISSUE TITLE
How to interpret the "trim" in fasta def line of assembly output

### ISSUE THREAD

**Issue by koolape** [marbl/canu#1939]
I used Canu to assemble PacBio raw reads and when I checked the fasta def line in the output assembly file, I found the last part is "trim":
```
>tig00000001 len=4552969 reads=13249 class=contig suggestRepeat=no suggestBubble=no suggestCircular=yes trim=5823-4546292
```
I'm wondering what does it mean since I did not see explanation in  Canu docs.

**Comment by skoren** [comment]
This is the non-redundant sequence for the circular molecule. So if you trimmed the contig to those coordinates, it should not have any self-similarity due to circularization on the ends.

**Comment by koolape** [comment]
Thanks for your explanation!

**Comment by koolape** [comment]
Can I just use `samtool faidx` command to trim the contig to those coordinates? In this example, trim from 5823 to 4546292 to get non-redundant sequence for the circular molecule

**Comment by skoren** [comment]
I've not used faidx but I expect yes, check if it's 1 or 0 base or your trim might be 1bp off.
