### ISSUE TITLE
canu trim for ONT data in a block state（PBS show “H”）

### ISSUE THREAD

**Issue by jenny315** [marbl/canu#1942]
Hi, 
I submitted trim command of ONT data on PBS, as follows.After he finished all the previous tasks, the last step always remained in the "H" which means be block state (this was the second time). When it first encounter "H" state, I killed the task and resubmitted the command. It could continue to run from several small previous tasks until it went to last step , but when he ran to the last step, he was still in a block state "H". There are available nodes on the grid, I'm not sure is it normal.

canu2.1.1
```
canu -trim \
    -p JT_ONT_trim \
    -d ./trim \
    merylThreads=20 \
    genomeSize=850m \
    minReadLength=2000 \
    minOverlapLength=500\
    corOutCoverage=40 \
    corMinCoverage=2 \
    -corrected -nanopore ~/02result/01ont/04canu/correct/ont.correctedReads.fasta

```
now PBS state is
```
8095.admin              jenny             low              canu_JT_ONT_trim    --      1      1    4gb     24:00:00        H       --
```

Thanks for any advice
Jenny

**Comment by skoren** [comment]
Nothing in Canu would place a job on hold, this is likely something on your grid engine. You can see the job is only requesting 4gb of memory and 1 core. Are there any non-default options you need to include (time/account/partition), Canu will only request memory/CPUs, everything else should be included in `gridOptions`. 

Can you run qrls <jobid>? If not, you'll have to check with your sysadmins as to why these jobs are in H state. Perhaps you have exceeded some usage quota?

**Comment by jenny315** [comment]
Thank you very much
I run ```qrls 8095``` , and nothing happen, the task always remained in "H", I think you are right. Perhaps other task of me have exceeded some usage quota.
```
-bash-4.2$ qrls 8095
-bash-4.2$
```

Thanks 
Jenny
