### ISSUE TITLE
Running out of room: Options to ameliorate high disk space usage in correction 

### ISSUE THREAD

**Issue by fishercera** [marbl/canu#1947]
Hi folks, 

Assembling a repetitive, eukaryote, diploid genome that is 1.3Gbp. Let me preface this by saying I've read the issues here regarding Canu running away with disk space. 

**My overall question is**: what do the recommended options actually mean, and which direction should I tweak them to improve? 
Subquestions:
- What's the difference between `num-hashes 512` and `728`? Is a larger num-hashes value better or worse for disk space? Is it better or worse for speed?
- Is `--num-min-matches 3` better or worse for disk space than "--num-min-matches 2", and what is the default? Is it better or worse for speed?\
- How much of a difference does `threshold 0.80` make versus `threshold 0.78`, or are these substantially similar? What is the default? 
- Will dropping reads shorter than the minimum overlap help with disk space, if I have the coverage to support it? 

Special snowflake details -- I have access to a cluster with a SLURM grid engine but it's legacy access from my previous institution; I don't want to run the risk of Angering The Sysadmins there. At my new institution, I do not have access to a grid -- I must use single machines which are Big Bois, but are not quite as powerful as having a vast array of nodes.  Max disk space on the SLURM cluster is probably ~ 20TB. Max disk space on the single-server is about 11TB. I just had a run error out on the single-server during correction at the bucketize step due to lack of disk space (the Big Bad Run). Meanwhile, I have a another Canu job that is at the Unitigging stage, running quietly along with 103G of disk space currently used (the Good Run). 

Canu command used (on the Big Bad Run):

```
/programs/canu-2.1.1/bin/canu \
    -useGrid=False \
    -p CKR_A1_canu.v1 \
    -genomeSize=1.3g \
    -raw \
    -correct \  ## Just correcting reads! 
    -nanopore CKR_A1_1kbplus.fastq.gz
```

For the Good Run, I used this command to perform Correction Only on the SLURM cluster 

```
canu \
    -useGrid=TRUE \
    -gridOptions="--partition=general --qos=general" \
    -p OSP_C1_canu.v1 \
    -genomeSize=1.3g \
    -maxMemory=$(( SLURM_MEM_PER_NODE -1 )) \
    -maxThreads=$SLURM_CPUS_PER_TASK \
    -raw \
    -corMhapFilterThreshold=0.0000000002 \
    -corMhapOptions="--threshold 0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50" \
    -mhapMemory=60g -mhapBlockSize=500 -ovlMerDistinct=0.975 \
    -correct \
    -nanopore OSP_C1_1kbplus.fastq.gz
```
Then moved all the files from the SLURM cluster to the single-server machine and used this command: 

```
/programs/canu-2.1.1/bin/canu \
    -useGrid=FALSE \
    -p OSP_C1_canu.v1 \
    -genomeSize=1.3g \
#    -showNext=TRUE \
    -raw \
    -corMhapFilterThreshold=0.0000000002 \
    -corMhapOptions="--threshold 0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50" \
    -mhapMemory=60g -mhapBlockSize=500 -ovlMerDistinct=0.975 \
    -nanopore OSP_C1_1kbplus.fastq.gz
```

Those extra options were taken from the FAQ, but I've also seen slightly different options suggested here -- such as `num-hashes 728`; `num-min-matches 2`. I left them in for the post-correction run on the single-server machine, but since they have the prefix "cor", it does seem like they only affect correction. Unfortunately, I didn't make note of how much disk-space ended up getting used during correction in the Good Run. It may still have gone over the disk space limit I would have on the single-server machine. 

What's the difference between `num-hashes 512` and `728`? Is a larger num-hashes value better or worse for disk space? Is it better or worse for speed? Is `--num-min-matches 3` better or worse for disk space? Is it better or worse for speed? How much of a difference does `threshold 0.80` make versus `threshold 0.78`?  (More simply: In which direction do I tweak to slim down my disk space footprint?)

My coverage for these genomes is right around 35-40x, with Nanopore reads of N50=15kbp.  Can I afford to ditch shorter reads and will it improve matters (e.g., if the min olap length is 2000, is it better to drop any reads shorter than 2500bp)? Filtering down to reads that are 10kbplus for this library doesn't drop my coverage too badly, but reduces the byte-size of the fastq by 7 gigabytes. Will that make a difference for canu? 

Edited: Summarized my questions at the top in bulleted list form to make them more intelligible.

**Comment by skoren** [comment]
More hashes in itself doesn't make that much difference in disk space (the index is larger) but coupled with a smaller min matches it will generate more hits and, thus, take more space. So min matches 3 uses less space than 2 and threshold 0.78 uses more space than 0.80. I think you'd be ok dropping reads <2kb or even <5kb given what you said about your read distribution. Keep the parameters you have from the good run, those are recommendation from the FAQ to decrease space usage.
