### ISSUE TITLE
Bacterial genome sequenced with PacBio resulted in a smaller genome size than expected with canu

### ISSUE THREAD

**Issue by Selucote82** [marbl/canu#1948]
Hi all,

I'm trying to assemble a bacterial genome with an expected size of 10.7Mbp (from previous assembly done with illumina reads) with PacBio smrt reads, but the resulted assembly is below 7Mbp. This is the command and parameters I launched with canu 1.9:

canu -p canu_bact -d output corMhapSensitivity=high corMinCoverage=0 genomeSize=10.7m -pacbio-raw PB_raw_merged.fastq.gz

The compressed data PB_raw_merged.fastq.gz is about 1.2Gb. Would you be so kind as to help me with this issue?

Thank you!

**Comment by Selucote82** [comment]
The log:

[CORRECTION/READS]
--
-- In sequence store './canu_crossiellaRAW.seqStore':
--   Found 114544 reads.
--   Found 1486461452 bases (138.92 times coverage).
--
--   Read length histogram (one '*' equals 128.07 reads):
--     1000   1999   8785 ********************************************************************
--     2000   2999   8965 **********************************************************************
--     3000   3999   4239 *********************************
--     4000   4999   4048 *******************************
--     5000   5999   4337 *********************************
--     6000   6999   4419 **********************************
--     7000   7999   4476 **********************************
--     8000   8999   4617 ************************************
--     9000   9999   4461 **********************************
--    10000  10999   4582 ***********************************
--    11000  11999   4539 ***********************************
--    12000  12999   4417 **********************************
--    13000  13999   4210 ********************************
--    14000  14999   4130 ********************************
--    15000  15999   3901 ******************************
--    16000  16999   3878 ******************************
--    17000  17999   3624 ****************************
--    18000  18999   3590 ****************************
--    19000  19999   3400 **************************
--    20000  20999   3228 *************************
--    21000  21999   3000 ***********************
--    22000  22999   2763 *********************
--    23000  23999   2511 *******************
--    24000  24999   2337 ******************
--    25000  25999   2103 ****************
--    26000  26999   1891 **************
--    27000  27999   1757 *************
--    28000  28999   1490 ***********
--    29000  29999   1302 **********
--    30000  30999    986 *******
--    31000  31999    767 *****
--    32000  32999    589 ****
--    33000  33999    409 ***
--    34000  34999    264 **
--    35000  35999    182 *
--    36000  36999    127 
--    37000  37999     75 
--    38000  38999     53 
--    39000  39999     27 
--    40000  40999     27 
--    41000  41999     14 
--    42000  42999      8 
--    43000  43999      5 
--    44000  44999      2 
--    45000  45999      5 
--    46000  46999      3 
--    47000  47999      1

[CORRECTION/MERS]
--
--  16-mers                                                                                           Fraction
--    Occurrences   NumMers                                                                         Unique Total
--       1-     1         0                                                                        0.0000 0.0000
--       2-     2 125944071 ********************************************************************** 0.4737 0.2288
--       3-     4  82650436 *********************************************                          0.6785 0.3772
--       5-     7  33124631 ******************                                                     0.8459 0.5537
--       8-    11  11816159 ******                                                                 0.9262 0.6844
--      12-    16   4732991 **                                                                     0.9586 0.7637
--      17-    22   3260319 *                                                                      0.9737 0.8174
--      23-    29   2385118 *                                                                      0.9853 0.8744
--      30-    37   1075088                                                                        0.9933 0.9262
--      38-    46    428483                                                                        0.9969 0.9549
--      47-    56    213837                                                                        0.9983 0.9699
--      57-    67    112067                                                                        0.9991 0.9792
--      68-    79     62078                                                                        0.9995 0.9852
--      80-    92     34856                                                                        0.9997 0.9891
--      93-   106     19552                                                                        0.9998 0.9917
--     107-   121     11470                                                                        0.9999 0.9934
--     122-   137      6572                                                                        0.9999 0.9946
--     138-   154      4260                                                                        0.9999 0.9953
--     155-   172      2604                                                                        1.0000 0.9958
--     173-   191      1790                                                                        1.0000 0.9962
--     192-   211      1234                                                                        1.0000 0.9965
--     212-   232       930                                                                        1.0000 0.9967
--     233-   254       566                                                                        1.0000 0.9969
--     255-   277       453                                                                        1.0000 0.9970
--     278-   301       290                                                                        1.0000 0.9972
--     302-   326       201                                                                        1.0000 0.9972
--     327-   352       175                                                                        1.0000 0.9973
--     353-   379       120                                                                        1.0000 0.9973
--     380-   407        93                                                                        1.0000 0.9974
--     408-   436        90                                                                        1.0000 0.9974
--     437-   466        58                                                                        1.0000 0.9974
--     467-   497        51                                                                        1.0000 0.9975
--     498-   529        32                                                                        1.0000 0.9975
--     530-   562        26                                                                        1.0000 0.9975
--     563-   596        21                                                                        1.0000 0.9975
--     597-   631        10                                                                        1.0000 0.9975
--     632-   667         6                                                                        1.0000 0.9975
--     668-   704         3                                                                        1.0000 0.9975
--     705-   742         4                                                                        1.0000 0.9975
--     743-   781         3                                                                        1.0000 0.9975
--     782-   821         6                                                                        1.0000 0.9975
--
--           0 (max occurrences)
--  1100963967 (total mers, non-unique)
--   265892829 (distinct mers, non-unique)
--           0 (unique mers)

[CORRECTION/LAYOUT]
--                             original      original
--                            raw reads     raw reads
--   category                w/overlaps  w/o/overlaps
--   -------------------- ------------- -------------
--   Number of Reads              98873         15671
--   Number of Bases         1273525397     172097170
--   Coverage                   119.021        16.084
--   Median                       11837          9905
--   Mean                         12880         10981
--   N50                          18743         17674
--   Minimum                       1000             0
--   Maximum                      47717         46924
--   
--                                        --------corrected---------  ----------rescued----------
--                             evidence                     expected                     expected
--   category                     reads            raw     corrected            raw     corrected
--   -------------------- -------------  ------------- -------------  ------------- -------------
--   Number of Reads              90573          16469         16469           9915          9915
--   Number of Bases         1301108314      433392421     428001428       38913169      24418239
--   Coverage                   121.599         40.504        40.000          3.637         2.282
--   Median                       13486          25693         25361           2030          2000
--   Mean                         14365          26315         25988           3924          2462
--   N50                          18929          26278         25900           6894          2046
--   Minimum                       1000          21358         21357           1014          1001
--   Maximum                      47717          47717         42409          41208         21264
--   
--                        --------uncorrected--------
--                                           expected
--   category                       raw     corrected
--   -------------------- ------------- -------------
--   Number of Reads              88160         88160
--   Number of Bases          973316977     682646093
--   Coverage                    90.964        63.799
--   Median                       10647          6660
--   Mean                         11040          7743
--   N50                          15215         14532
--   Minimum                          0             0
--   Maximum                      46924         45516
--   
--   Maximum Memory           955560446

[TRIMMING/READS]
--
-- In sequence store './canu_crossiellaRAW.seqStore':
--   Found 26384 reads.
--   Found 459126791 bases (42.9 times coverage).
--
--   Read length histogram (one '*' equals 87.92 reads):
--     1000   1999   6155 **********************************************************************
--     2000   2999   1834 ********************
--     3000   3999    298 ***
--     4000   4999    185 **
--     5000   5999    178 **
--     6000   6999    110 *
--     7000   7999    109 *
--     8000   8999     79 
--     9000   9999     78 
--    10000  10999     65 
--    11000  11999     65 
--    12000  12999     68 
--    13000  13999     62 
--    14000  14999     73 
--    15000  15999     86 
--    16000  16999     85 
--    17000  17999    112 *
--    18000  18999    165 *
--    19000  19999    314 ***
--    20000  20999    778 ********
--    21000  21999   1591 ******************
--    22000  22999   1843 ********************
--    23000  23999   1794 ********************
--    24000  24999   1700 *******************
--    25000  25999   1571 *****************
--    26000  26999   1459 ****************
--    27000  27999   1300 **************
--    28000  28999   1140 ************
--    29000  29999    965 **********
--    30000  30999    697 *******
--    31000  31999    474 *****
--    32000  32999    349 ***
--    33000  33999    206 **
--    34000  34999    138 *
--    35000  35999     85 
--    36000  36999     51 
--    37000  37999     45 
--    38000  38999     26 
--    39000  39999     18 
--    40000  40999     14 
--    41000  41999      9 
--    42000  42999      4 
--    43000  43999      0 
--    44000  44999      3 
--    45000  45999      1 
--    46000  46999      1 
--    47000  47999      1

[TRIMMING/MERS]
--
--  22-mers                                                                                           Fraction
--    Occurrences   NumMers                                                                         Unique Total
--       1-     1         0                                                                        0.0000 0.0000
--       2-     2   2439311 ******************************************************************     0.2341 0.0164
--       3-     4   1073132 *****************************                                          0.3050 0.0238
--       5-     7    376698 **********                                                             0.3548 0.0315
--       8-    11    148576 ****                                                                   0.3785 0.0371
--      12-    16     69364 *                                                                      0.3895 0.0410
--      17-    22     50911 *                                                                      0.3951 0.0439
--      23-    29    182099 ****                                                                   0.4002 0.0475
--      30-    37   1163875 *******************************                                        0.4232 0.0702
--      38-    46   2552637 ********************************************************************** 0.5511 0.2278
--      47-    56   1951822 *****************************************************                  0.8001 0.6036
--      57-    67    351433 *********                                                              0.9688 0.9083
--      68-    79     12276                                                                        0.9947 0.9632
--      80-    92     16484                                                                        0.9957 0.9658
--      93-   106     10207                                                                        0.9973 0.9706
--     107-   121      3554                                                                        0.9982 0.9738
--     122-   137      1898                                                                        0.9985 0.9750
--     138-   154      2905                                                                        0.9987 0.9759
--     155-   172      4391                                                                        0.9990 0.9773
--     173-   191      1680                                                                        0.9994 0.9798
--     192-   211       473                                                                        0.9996 0.9807
--     212-   232       374                                                                        0.9996 0.9810
--     233-   254       341                                                                        0.9996 0.9813
--     255-   277       201                                                                        0.9997 0.9816
--     278-   301       153                                                                        0.9997 0.9818
--     302-   326       125                                                                        0.9997 0.9819
--     327-   352        97                                                                        0.9997 0.9820
--     353-   379        82                                                                        0.9997 0.9821
--     380-   407        60                                                                        0.9997 0.9822
--     408-   436        60                                                                        0.9997 0.9823
--     437-   466        93                                                                        0.9998 0.9824
--     467-   497        90                                                                        0.9998 0.9825
--     498-   529        94                                                                        0.9998 0.9827
--     530-   562        56                                                                        0.9998 0.9829
--     563-   596        36                                                                        0.9998 0.9830
--     597-   631        21                                                                        0.9998 0.9830
--     632-   667        13                                                                        0.9998 0.9831
--     668-   704        10                                                                        0.9998 0.9831
--     705-   742        26                                                                        0.9998 0.9831
--     743-   781        43                                                                        0.9998 0.9832
--     782-   821        28                                                                        0.9998 0.9833
--
--           0 (max occurrences)
--   297370870 (total mers, non-unique)
--    10417812 (distinct mers, non-unique)
--           0 (unique mers)

[TRIMMING/TRIMMING]
--  PARAMETERS:
--  ----------
--     1000    (reads trimmed below this many bases are deleted)
--   0.0450    (use overlaps at or below this fraction error)
--      500    (break region if overlap is less than this long, for 'largest covered' algorithm)
--        2    (break region if overlap coverage is less than this many reads, for 'largest covered' algorithm)
--  
--  INPUT READS:
--  -----------
--  114544 reads    459126791 bases (reads processed)
--       0 reads            0 bases (reads not processed, previously deleted)
--       0 reads            0 bases (reads not processed, in a library where trimming isn't allowed)
--  
--  OUTPUT READS:
--  ------------
--   14972 reads    290479838 bases (trimmed reads output)
--    1530 reads     10708796 bases (reads with no change, kept as is)
--   97550 reads    105863036 bases (reads with no overlaps, deleted)
--     492 reads      5927194 bases (reads with short trimmed length, deleted)
--  
--  TRIMMING DETAILS:
--  ----------------
--   11712 reads     34133745 bases (bases trimmed from the 5' end of a read)
--   14022 reads     12014182 bases (bases trimmed from the 3' end of a read)

[TRIMMING/SPLITTING]
--  PARAMETERS:
--  ----------
--     1000    (reads trimmed below this many bases are deleted)
--   0.0450    (use overlaps at or below this fraction error)
--  INPUT READS:
--  -----------
--   16502 reads    347336561 bases (reads processed)
--   98042 reads    111790230 bases (reads not processed, previously deleted)
--       0 reads            0 bases (reads not processed, in a library where trimming isn't allowed)
--  
--  PROCESSED:
--  --------
--       0 reads            0 bases (no overlaps)
--       0 reads            0 bases (no coverage after adjusting for trimming done already)
--       0 reads            0 bases (processed for chimera)
--       0 reads            0 bases (processed for spur)
--   16502 reads    347336561 bases (processed for subreads)
--  
--  READS WITH SIGNALS:
--  ------------------
--       0 reads            0 signals (number of 5' spur signal)
--       0 reads            0 signals (number of 3' spur signal)
--       0 reads            0 signals (number of chimera signal)
--       6 reads            6 signals (number of subread signal)
--  
--  SIGNALS:
--  -------
--       0 reads            0 bases (size of 5' spur signal)
--       0 reads            0 bases (size of 3' spur signal)
--       0 reads            0 bases (size of chimera signal)
--       6 reads         4479 bases (size of subread signal)
--  
--  TRIMMING:
--  --------
--       3 reads         6777 bases (trimmed from the 5' end of the read)
--       3 reads         6859 bases (trimmed from the 3' end of the read)

[UNITIGGING/READS]
--
-- In sequence store './canu_crossiellaRAW.seqStore':
--   Found 16502 reads.
--   Found 301174998 bases (28.14 times coverage).
--
--   Read length histogram (one '*' equals 44.31 reads):
--     1000   1999   3102 **********************************************************************
--     2000   2999    106 **
--     3000   3999     92 **
--     4000   4999     85 *
--     5000   5999    108 **
--     6000   6999    126 **
--     7000   7999    137 ***
--     8000   8999    128 **
--     9000   9999    170 ***
--    10000  10999    159 ***
--    11000  11999    195 ****
--    12000  12999    184 ****
--    13000  13999    187 ****
--    14000  14999    245 *****
--    15000  15999    213 ****
--    16000  16999    254 *****
--    17000  17999    271 ******
--    18000  18999    291 ******
--    19000  19999    421 *********
--    20000  20999    871 *******************
--    21000  21999   1214 ***************************
--    22000  22999   1216 ***************************
--    23000  23999   1102 ************************
--    24000  24999    998 **********************
--    25000  25999    939 *********************
--    26000  26999    889 ********************
--    27000  27999    731 ****************
--    28000  28999    684 ***************
--    29000  29999    569 ************
--    30000  30999    369 ********
--    31000  31999    220 ****
--    32000  32999    129 **
--    33000  33999     59 *
--    34000  34999     30 
--    35000  35999      6 
--    36000  36999      1 
--    37000  37999      0 
--    38000  38999      0 
--    39000  39999      1

[UNITIGGING/MERS]
--
--  22-mers                                                                                           Fraction
--    Occurrences   NumMers                                                                         Unique Total
--       1-     1         0                                                                        0.0000 0.0000
--       2-     2   1551110 *****************************************                              0.1711 0.0109
--       3-     4    771841 ********************                                                   0.2286 0.0163
--       5-     7    294721 *******                                                                0.2719 0.0223
--       8-    11    116079 ***                                                                    0.2934 0.0270
--      12-    16     51090 *                                                                      0.3032 0.0301
--      17-    22     43227 *                                                                      0.3079 0.0323
--      23-    29    219018 *****                                                                  0.3132 0.0358
--      30-    37   1318727 ***********************************                                    0.3455 0.0646
--      38-    46   2610471 ********************************************************************** 0.5093 0.2472
--      47-    56   1780092 ***********************************************                        0.7986 0.6419
--      57-    67    259645 ******                                                                 0.9731 0.9270
--      68-    79      9266                                                                        0.9946 0.9681
--      80-    92     16101                                                                        0.9956 0.9705
--      93-   106      9168                                                                        0.9974 0.9753
--     107-   121      2642                                                                        0.9983 0.9783
--     122-   137      1584                                                                        0.9986 0.9792
--     138-   154      3113                                                                        0.9988 0.9799
--     155-   172      4125                                                                        0.9991 0.9816
--     173-   191       729                                                                        0.9996 0.9839
--     192-   211       267                                                                        0.9996 0.9843
--     212-   232       118                                                                        0.9997 0.9845
--     233-   254       196                                                                        0.9997 0.9846
--     255-   277        73                                                                        0.9997 0.9847
--     278-   301       122                                                                        0.9997 0.9848
--     302-   326        63                                                                        0.9997 0.9849
--     327-   352        97                                                                        0.9997 0.9850
--     353-   379       111                                                                        0.9997 0.9851
--     380-   407        64                                                                        0.9997 0.9852
--     408-   436        40                                                                        0.9997 0.9853
--     437-   466        28                                                                        0.9998 0.9854
--     467-   497        23                                                                        0.9998 0.9854
--     498-   529        19                                                                        0.9998 0.9855
--     530-   562        32                                                                        0.9998 0.9855
--     563-   596        34                                                                        0.9998 0.9856
--     597-   631        36                                                                        0.9998 0.9856
--     632-   667        42                                                                        0.9998 0.9857
--     668-   704        11                                                                        0.9998 0.9858
--     705-   742        16                                                                        0.9998 0.9858
--     743-   781        27                                                                        0.9998 0.9859
--     782-   821        17                                                                        0.9998 0.9859
--
--           0 (max occurrences)
--   285543046 (total mers, non-unique)
--     9066151 (distinct mers, non-unique)
--           0 (unique mers)

[UNITIGGING/OVERLAPS]
--   category            reads     %          read length        feature size or coverage  analysis
--   ----------------  -------  -------  ----------------------  ------------------------  --------------------
--   middle-missing          0    0.00        0.00 +- 0.00             0.00 +- 0.00       (bad trimming)
--   middle-hump             1    0.01     1978.00 +- 0.00             0.00 +- 0.00       (bad trimming)
--   no-5-prime              3    0.02     1683.00 +- 469.41          55.00 +- 95.26      (bad trimming)
--   no-3-prime              3    0.02     1630.33 +- 278.78         366.33 +- 199.77     (bad trimming)
--   
--   low-coverage           22    0.13     1637.18 +- 246.43           4.15 +- 2.22       (easy to assemble, potential for lower quality consensus)
--   unique               2889   17.51    17057.84 +- 9003.72         37.32 +- 4.17       (easy to assemble, perfect, yay)
--   repeat-cont          4118   24.95     8786.02 +- 9614.83        125.02 +- 199.82     (potential for consensus errors, no impact on assembly)
--   repeat-dove           194    1.18    29306.94 +- 2158.38         56.77 +- 4.38       (hard to assemble, likely won't assemble correctly or even at all)
--   
--   span-repeat          2483   15.05    22332.37 +- 6244.07      10014.18 +- 8022.69    (read spans a large repeat, usually easy to assemble)
--   uniq-repeat-cont     4438   26.89    20869.68 +- 6416.27                             (should be uniquely placed, low potential for consensus errors, no impact on assembly)
--   uniq-repeat-dove     1081    6.55    28846.06 +- 2513.88                             (will end contigs, potential to misassemble)
--   uniq-anchor          1263    7.65    24320.87 +- 4650.00       8527.05 +- 6667.34    (repeat read, with unique section, probable bad read)

[UNITIGGING/ADJUSTMENT]
-- No report available.

[UNITIGGING/CONTIGS]
-- Found, in version 1, after unitig construction:
--   contigs:      4 sequences, total length 6347857 bp (including 0 repeats of total length 0 bp).
--   bubbles:      0 sequences, total length 0 bp.
--   unassembled:  2752 sequences, total length 5578431 bp.
--
-- Contig sizes based on genome size 10.7mbp:
--
--            NG (bp)  LG (contigs)    sum (bp)
--         ----------  ------------  ----------
--     10     6341922             1     6341922
--     20     6341922             1     6341922
--     30     6341922             1     6341922
--     40     6341922             1     6341922
--     50     6341922             1     6341922
--

[UNITIGGING/CONSENSUS]
-- Found, in version 2, after consensus generation:
--   contigs:      4 sequences, total length 6346332 bp (including 0 repeats of total length 0 bp).
--   bubbles:      0 sequences, total length 0 bp.
--   unassembled:  2752 sequences, total length 5578431 bp.
--
-- Contig sizes based on genome size 10.7mbp:
--
--            NG (bp)  LG (contigs)    sum (bp)
--         ----------  ------------  ----------
--     10     6340406             1     6340406
--     20     6340406             1     6340406
--     30     6340406             1     6340406
--     40     6340406             1     6340406
--     50     6340406             1     6340406
--

**Comment by Selucote82** [comment]
Attached the log:

[canu_out.txt](https://github.com/marbl/canu/files/6510930/canu_out.txt)

**Comment by skoren** [comment]
Looking at the log, I don't see any issue. I expect the 10.7 Mbp genome size is inaccurate. There is a clear k-mer peak around 40x in the corrected reads and the overlaps have a mean of close to that. Given your input data, that'd be close to a 7mb genome size. Have you used gennomescope to estimate the genome size from the corrected reads histogram or from the Illumina data?

You could try increasing the corrected reads output via `corOutCoverage=200`, you can also probably dump the `corMhapSensitivity=high corMinCoverage=0` options. I don't think either of these will change your genome size though.

**Comment by Selucote82** [comment]
Yes, canu was right assembling the genome. Thank you for responding so quickly.

All the best.
