### ISSUE TITLE
Segmentation fault of mhap in reads correction

### ISSUE THREAD

**Issue by zhanglu295** [marbl/canu#1949]
Hi there,

Canu reported an error when I assembled the nanopore reads from a metagenome sample. I used canu 1.1.2 and the command line is shown as below:

```canu -p ont_med -d ont_med genomeSize=571m -nanopore nanopore_medium_1.fq.renamed.gz useGrid=remote minThreads=20 maxThreads=60```

Three subtasks had failed:

```-- Running jobs.  Second attempt out of 2.

-- Starting 'cormhap' concurrent execution on Wed May 19 23:35:52 2021 with 1402245.56 GB free disk space (3 processes; 1 concurrently)

    cd correction/1-overlapper
    ./mhap.sh 139 > ./mhap.000139.out 2>&1
    ./mhap.sh 190 > ./mhap.000190.out 2>&1
    ./mhap.sh 191 > ./mhap.000191.out 2>&1

-- Finished on Thu May 20 04:07:34 2021 (16302 seconds, better late than never) with 1387748.872 GB free disk space

--
-- Mhap overlap jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/results/000139.ovb FAILED.
--   job correction/1-overlapper/results/000190.ovb FAILED.
--   job correction/1-overlapper/results/000191.ovb FAILED.
```

In correction/1-overlapper/mhap.000190.out, the detailed error report is

```./mhap.sh: line 1301: 33486 Segmentation fault      $bin/mhapConvert -S ../../ont_med.seqStore -o ./results/$qry.mhap.ovb.WORKING $outPath/$qry.mhap```

I tried to delete all the '*.WORKING' files and restarted canu, but the errors were still there.

Could you give me any comments or suggestions to deal with this issue?

Many thanks,
Eric

**Comment by skoren** [comment]
This implies there is a truncated file somewhere. First, make sure you're not out of space or quota before restarting. If you're not, remove all the `*WORKING` and `*mhap` files and re-launch.

**Comment by zhanglu295** [comment]
Many thanks. I will try to remove all the relevant files.
