### ISSUE TITLE
Assemble Failed

### ISSUE THREAD

**Issue by lzyskyline** [marbl/canu#195]
Hi，
I am running canu to assemble genome, In the Assemble step, I got two errors:
any idea solve it? Thank you

First,  
```
-- read error detection attempt 0 begins with 0 finished, and 3591 to compute.
----------------------------------------
-- Starting concurrent execution on Wed Jul 13 21:08:03 2016 with 2461.4 GB free disk space (3591 processes; 16 concurrently)
#################
#################
#############

Can't fork: Resource temporarily unavailable
```

Second, 
```
-- 72 overlap error adjustment jobs failed:
####################
####################

================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'failed to adjust overlap error rates.  Made 2 attempts, jobs still failed'.
```

**Comment by brianwalenz** [comment]
What hardware resources are available (output to the screen when canu starts)?
Details on genome size and amount of reads would be nice to know.

What I can see here is that it is trying to run 16 of the read error detection jobs ("findErrors") at the same time.  Each will be using some number of compute threads (not shown).  'Can't fork' is suggesting that you hit some kind of limit on the number of processes or threads.

redConcurrency can be set to reduce the number of jobs run at once.

However, there are 3591 total jobs to run, which is a VERY large number of jobs.

**Comment by brianwalenz** [comment]
No response.
