### ISSUE TITLE
unitigger.sh ran for a long time

### ISSUE THREAD

**Issue by zhanglu295** [marbl/canu#1951]
Hi there,

I was analyzing the nanopore reads from a metagenome sample. I used canu 2.1.1 and the command line is as:

canu -p high_ont -d high_ont genomeSize=2805m -nanopore nanopore_high.fq.renamed.gz useGrid=remote minThreads=10 maxThreads=60

Here is the content of log file 

```-- Running jobs.  First attempt out of 2.
-- Starting 'bat' concurrent execution on Sun May 23 18:25:34 2021 with 1469409.007 GB free disk space (1 processes; 1 concurrently)

    cd unitigging/4-unitigger
    ./unitigger.sh 1 > ./unitigger.000001.out 2>&1
```

I also checked `/unitigging/4-unitigger/high_ont.010.mergeOrphans.thr000.num000.log`

And it reported a potential size issue

```
read 8205385 at     52597-45058
read 15091905 at     49736-45004
read 11651374 at     57298-52753
read 11651826 at     63038-56752
logFile()--  size 536870947 exceeds limit of 536870912; rotate to new file.
```
I also attached [unitigger.err](https://github.com/marbl/canu/files/6535968/unitigger.err.txt) for your reference.

Could you share any thoughts on this issue? Should I increase the thread number or just wait for a longer time?

Thank you,
Eric

**Comment by brianwalenz** [comment]
I'd let it run.

You're a day into it with 32 threads, right?  Bumping up to 64 threads would still take ~18 hours to get back to where you are now (loading data is slow and isn't multi-threaded).

No estimate on how much longer it'll run for...but "over half done" is plausible.  However, the last major step to perform is repeat detection and I don't have a feel for if this will be expensive or 'nothing' on a metagenomic sample.

The log files are limited to 512 MB, so they can be more easily examined.  Once the size is exceeded, it continues writing to a new file.
