### ISSUE TITLE
Can canu 2.1.1 use both -pacbio-hifi and  -haplotype{NAME} at same command

### ISSUE THREAD

**Issue by PengJia6** [marbl/canu#1953]
Hi, 
I have pacbio hifi sequencing data from a trio (a gril and her parents), can I use both **hicanu** (-pacbio-hifi) and **triocanu** (-haplotype{NAME})? 
Thx!

**Comment by skoren** [comment]
Follow the instructions on the quick start: https://canu.readthedocs.io/en/latest/quick-start.html#quickstart to run the haplotype step separately and then run the binned assemblies with the HiFi data.
