### ISSUE TITLE
No result in the end

### ISSUE THREAD

**Issue by Kai-Maker1** [marbl/canu#1955]
Hello Canu community，I installed Canu 2.1 version on my linux with submitting through LSF job scheduling system.
Bachground：
        We wanna assemble a homozygous diploid that its haploid genome size is 600m. And its heterozygosity rate is 0.03% and repetitive sequence content is 64.77% with sequencing method ----pacbio CLR, 37.89g data was abtained by sequenced and it is around 60x, there is no result in the end, and a very large core file is produced.
        The following attachments are my submitted script, runtime error ,runtime log and report. Besides the picture is about the core file.
[files.zip](https://github.com/marbl/canu/files/6595512/files.zip)

         Hope to receive your reply soon and many thanks in advance.

**Comment by Kai-Maker1** [comment]
Hi, thanks to your prompt response. Here are my canu.out file.[canu_out.zip](https://github.com/marbl/canu/files/6596897/canu_out.zip)
      Is there a memory overflow problem？ How can I avoid the similar situation？What’s more,do I need to start from the beginning or right where I failed ? Should I change the canu version?
       I have been stuck in this for a long time. Sincerely looking forward to your reply.

**Comment by brianwalenz** [comment]
Bus errors are _typically_ caused by the grid scheduler killing the job which are _typically_ from using too much memory.  Try increasing `executiveMemory` from the default of 4 to 8 or 12 or even 16.

I suspect this is caused by the high repeat content resulting in lots and lots of overlaps for some reads...but this step isn't known to be a memory hog.

**Comment by Kai-Maker1** [comment]
Thanks for your prompt response. Do I just should rewrite the script like ‘ canu -p xxx -d xxx genomeSize=xxx executiveMemory=16’ ,the parameter without an unit?What if there is no result again?Is there a bigger parameter like 32 or 64?
