### ISSUE TITLE
Canu best options 

### ISSUE THREAD

**Issue by Dongho1234** [marbl/canu#1956]
Hi there,
I am trying to assemble one of the Bacillus subtilis organisms. And i used the basic method described in quick start 

canu  -p my_subtilis \
-d mysubtilis-pacbio \
 genomeSize=4.1m \
 -pacbio my_subtilis.fastq

and I got the results. When i compare my result to the assembled result from another( i paid), it does not seem accurate.
is there any best options or parameters to improve the accuracy rate of the reulst??

**Comment by skoren** [comment]
Hard to say anything because I'm not sure what you mean by "it doesn't seem accurate". How are you measuring accuracy? Do you mean base-level or structural differences?

**Comment by Dongho1234** [comment]
Sorry for the poor description. 
I requested and paid money to a company for assembling so I have the assembled result (fasta). Now i am trying to do it on my own. 

![image](https://user-images.githubusercontent.com/79836778/120819839-ebfa2800-c58e-11eb-8e58-3b5cd0835db8.png)

so the result of the first two should look like the third one but it does not. 
The first sequence is done with correctedErrorRate =0.039
The second sequence is done with correctedErrorRate =0.075
The third sequence is the result that I already have.

**Comment by skoren** [comment]
How are you comparing the genomes, are they aligned so they have the same start positions? In a circular genome, the start position is completely arbitrary and so your genome will likely be rotated with respect to each other. Try comparing them with MUMmer or QUAST or similar. There will also likely be overlapping sequence at the ends (indicated on the fasta defline by canu).

**Comment by Dongho1234** [comment]
Thank you. I will try to compare it with QUAST.

**Comment by Dongho1234** [comment]
I have compared them with QUAST, so i can conclude they are the same. But another issue pops up. 

![image](https://user-images.githubusercontent.com/79836778/121838218-4c693200-cd12-11eb-85b8-4e0a4e1e05ad.png)

![image](https://user-images.githubusercontent.com/79836778/121838386-abc74200-cd12-11eb-8763-3727dc4ab1f2.png)

Here, as you can see, assembled by canu, gives you reverse strand. 
Since it is a reverse strand i am wondering if it affects when i do further analysis such as gene annotation.

**Comment by skoren** [comment]
I doubt that reverse complement would matter for any downstream analysis like gene calling. You can always test it by reverse-complementing the assembly and comparing results. To get the best quality of consensus, you probably do want to trim the redundant sequence and run a polishing tool (like Arrow) on the canu results.
