### ISSUE TITLE
Can I use the p_ctg & a_ctg assembly generated by Hicanu to falcon_phase?

### ISSUE THREAD

**Issue by Yujiaxin419** [marbl/canu#1957]
Deer developer:

Thanks for developing Hicanu assembler for hifi reads.  

The Hicanu's article represented  that the pseudo-haplotype generated by Hicanu can be truly phase in falcon_phase. How can I convert the format of HiCanu assembly to falcon_unzip assembly, and phase the pseudo-haplotype further?

Looking forward your kindly reply.

Yours sincerely，
Jiaxin Yu

**Comment by skoren** [comment]
In theory, this is possible to do but not trivial. You'd have to run purge_dups to identify the primary and alternates and then convert it's format to one expected by FALCON-Phase. There would be a few other changes required in FALCON-Phase to make it work.  I've run this locally as an experiment so it can work. However, the phasing results weren't great with the HiFi+HiC combination. I think you' be better off binning the reads before the assembly if you wanted longer-range binning.
