### ISSUE TITLE
GFA layout links

### ISSUE THREAD

**Issue by knightjimr** [marbl/canu#196]
I'm trying to analyze a problematic assembly, and I noticed these following lines in the GFA file:

L       tig00000229     +       tig00000013     -       2147474165M
L       tig00000275     +       tig00000013     -       2147474192M
L       tig00000340     -       tig00000013     -       2147480175M
L       tig00000514     +       tig00000071     -       2147479119M
L       tig00000091     -       tig00000120     -       2147476235M

L       tig00000003     -       tig00000000     -       181587m
L       tig00000003     -       tig00000001     -       178847m
L       tig00000011     -       tig00000001     -       118463m
L       tig00000011     +       tig00000001     -       121892m

L       tig00000113     +       tig00000578     +       16052M
L       tig00000113     +       tig00000578     +       10470M
L       tig00000393     -       tig00000391     -       1529M
L       tig00000393     -       tig00000391     -       1378M

There were many lines with a 2GB overlap, but the lines that more concern me are the ones where the overlap appears to be a real overlap length, but longer than any read in the dataset (the longest read was only 55kb), as well as when there are multiple distances for the same link between contigs.  The lines above are just examples of the many lines that are occurring in the files.

The genome is a parasite that is supposed to be ~8-10MB, but the assemblies keep coming out at 25-45MB, with hints that this could be an even larger genome, but with other hints that it could just be highly variable (using a large number of parasites to generate enough DNA was a possibility, or it is possible host contamination).  The first assembly was done with one SMRT cell, they did three SMRT cells for 1.5GB of data before I got the dataset (canu reports 149x if you give a genome size of 10MB, the kmer analysis is reporting more along the lines of a 60x coverage, and the last assembly I just did with corHighSensitivity=true, but no other options, generated a 25MB assembly).

I am just trying to get a better sense of why the assembly is turning out the way it is, and looking for files and/or tools that can help analyze the results, when I noticed this issue with the file.  If you know of which files, or tools, that are useful for pointing to explanations of the assembly results, any help would be appreciated.

**Comment by brianwalenz** [comment]
Unsigned strikes again.  Which canu -version are you running?  The GFA is post-processed using unused best edges reported from the unitigger.  These edges could be to the interior of a unitig, and we're not checking of the ends would indeed align.  Early versions of canu had more than a few issues in generating the GFA.

There is a read-level GFA in unitigging/4-unitigger/$asm.best.edges.gfa.  It is generated using all best edges that would be used to assemble.  We're doing a fair bit of filtering on the overlaps and it's certainly possible we've managed to separate the variation -- canu parameter utgGraphDeviation is (roughly) how many stddev's of overlap error rate we'll use (default 6).  The error rate used is reported in the 001.filterOverlaps log.

The tgStoreDump command has a bunch of different way to view the tigs.  The coverage and/or depth reports might be interesting.  They should certainly show a contaminant.  "Version" 1 is the layout out of the unitigger, version 2 has consensus sequences.  Version 1 will work for this.

If you run 'bogart' by hand, you can turn on more debugging ("-D most").  The 'chunkGraph' report will tell why it stopped extending a unitig.  Warning: it's not a friendly file (long lines).

Happy to give it a detailed look if you want to share the data.  I'll only need unitigging/gkpStore and unitigging/ovlStore, not the whole run directory.

**Comment by knightjimr** [comment]
The path to the executable I'm using says canu-1.3, but canu -version reports this:

Canu v0.0 (+0 commits) r0 unknown-hash-tag-no-repository-available.

I tried to do a vanilla install of the canu-1.3 executable from github, but I can't get it to compile right now.  I have perl 5.16.3 and 5.22.3 on the system, and when I use 5.16.3, I get this error for the canu command:

Perl API version v5.20.0 of Filesys::Df does not match v5.16.0 at /ycga-gpfs/apps/hpc/Langs/Perl/5.16.3/lib/perl5/5.16.3/x86_64-linux/DynaLoader.pm line 213.

When I try perl 5.22.1, I get this error (which a Google search says occurs when you need to recompile your libraries for a new perl version):

perl: symbol lookup error: /ycga-ba/home/jk2269/soft.ruddle/canu-1.3/Linux-amd64/bin/lib/canu/lib/perl5/x86_64-linux/auto/Filesys/Df/Df.so: undefined symbol: Perl_xs_apiversion_bootcheck

I have no idea how the other folks who installed the canu that is working did it.

And, thanks for the tips on the files, the contig depth reports might help (I'm really looking for average depth numbers for each contig and zero.vs.many overlaps as the cause for each tig's ends).

**Comment by brianwalenz** [comment]
The Df module has been a bit of a pain.  It's referenced once, in src/canu/pipeline/Defaults.pm, and is used only to report disk space available after each command (because I got tired of 'debugging' people running out of disk).  Should be trivial to hack it out for now.

1.3 certainly should have the graph fixes.  I'll dig into it next week.

**Comment by knightjimr** [comment]
Well, you always just do something like this:

sub FreeSpace {
    $out = `df -k . | tail -1 | cut -f4 -d' '`;
    return $out / 1000;
}

**Comment by knightjimr** [comment]
P.S. The markdown removed the backticks around the command string...

**Comment by brianwalenz** [comment]
Yeah, I just don't like the backtick pipelines.  Not really sure why, probably stung by middle components failing silently.  We'll see if your seed takes hold.

**Comment by brianwalenz** [comment]
I think I left this open for fixes to the GFA output, which seems to at long last be working correctly.
