### ISSUE TITLE
TrioCanu reported "Too many bases in unassigned reads"

### ISSUE THREAD

**Issue by chhylp123** [marbl/canu#1961]
Hello there, I recently ran triocanu by using:
> canu -haplotype -p asm -d Meles_trio genomeSize=2.8g useGrid=false maxThreads=48 -haplotypePat pat.reads.fq -haplotypeMat mat.read.fq -pacbio-raw HiFi_reads.fq

And then canu reported:
>-- ERROR:  Too many bases in unassigned reads.  Assemblies not started.
-- ERROR:
-- ERROR:  If you run them manually, note that the unassigned reads
-- ERROR:  are included in ALL assemblies.
-- ERROR:

The sizes of partitioned reads are:
>6.7G Jun  5 19:32 ./haplotype/haplotype-Mat.fasta.gz
8.0G Jun  5 19:32 ./haplotype/haplotype-Pat.fasta.gz
19G Jun  5 19:32 ./haplotype/haplotype-unknown.fasta.gz

Is it OK if I manually run the 'asm-haplotypeMat.sh' and 'asm-haplotypeMat.sh'? Can I tune some parameters to make more reads partitionable? Thanks in advance.

**Comment by skoren** [comment]
You can manually run the assemblies but the majority of the data couldn't be binned so it won't be too different from an unbinned assembly. If you do that, I'd suggest manually randomly assigning the unassigned reads 50/50 to each parental bin. I'd also run a regular unbinned HiFi assembly for comparison. 

There aren't really parameters you can change to affect how the reads are binned, if they had even 1 marker they'd have been assigned by default. I'd suggest checking that there are no issues with the input data. You can use Merqury to build child and parental databases and compare the parental k-mers against the child k-mers to make sure both are inherited approximately equally and there wasn't any mis-tracking of the parents. It may be also be that your HiFi reads are too short to bin. For human, you typically need 15-20kb reads to bin them successfully, shorter reads are often ambiguous.

**Comment by chhylp123** [comment]
I see. Thanks a lot. The heterozygosity rate of this sample is quite low, which is about half of the heterozygosity rate of human. So I wonder if longer k-mers can provider more markers for trio-binning assembly.

**Comment by skoren** [comment]
In my experience, longer k-mers don't make too much difference. The main issue is the read sequences are really from homozygous stretches. Trio-binning was primarily designed for high heterozygosity samples in mind, even though it works on human, so this isn't the type of data it was designed for.

I'd suggest doing two assemblies, one with binned data, splitting the unknown reads randomly equally between the two bins and a standard hicanu assembly of all data followed by purge_dups. You can then use merqury to evaluate the phase blocks and quality of the two assemblies and select the best one.

**Comment by chhylp123** [comment]
Sure. I will have a try. Thanks so much.
