### ISSUE TITLE
ABORT: failed to generate correction layouts.

### ISSUE THREAD

**Issue by Kai-Maker1** [marbl/canu#1967]
Hello Canu community. Sorry to bother you again. This question is the continuation of #1962 and #1955 .
I just tried executiveMemory = 8, submitted to these specific fat nodes, but there  still existed this bus error.
Should I need a bigger executiveMemory parameter or I should pay attention to other parameters?
Thanks a lot for helping me so much. 
[canu.zip](https://github.com/marbl/canu/files/6693012/canu.zip)

**Comment by skoren** [comment]
Bus errors are typically out of memory or the executable changing while running. Your zip file doesn't include the error file from the generateCorrectionLayouts scripts and I don't see the bus error reported anywhere in the logs. However, the report for resource usage for the run does indicate it used 8gb of memory. It is not actually currently using executiveMemory for this step but instead if based on whatever you request in your canu launch script (similar to #1838) so it seems to be getting whatever is the default on the system. You have lots of large-memory nodes so follow the suggestions I had in #1962. Namely, leave the canu command with executiveMemory=4. Then, update your canu launch script to be something like (I haven't used LSF for a long time so the syntax may not be 100% correct):
```
#BSUB -J tlmx_canu
#BSUB -q lobs
#BSUB -o log
#BSUB -e error
#BSUB -R span[hosts=1] rusage[mem=32000]

/public-supool/software/canu-2.1/bin/canu -correct -p dlmx -d tlmx_8g useGrid=true minThreads=4 gridOptions="-q lowb" genomeSize=600m minReadLength=1000 minOverlapLength=700 executiveMemory=4 -pacbio /public-supool/home/yangkx/tlmx/tlmx.fasta.gz
```

**Comment by Kai-Maker1** [comment]
Thanks for your timely response. I will find the  instruction of LSF and try this script at once.

**Comment by skoren** [comment]
Idle
