### ISSUE TITLE
Read correction doesn't work

### ISSUE THREAD

**Issue by fjruizruano** [marbl/canu#1968]
Dear Canu authors,

I am trying to only compress homopolymers and correct reads with Canu using this command:
```
./canu-2.1.1/bin/canu -correct -p asm_correct2 -d asm_correct2 useGrid=false genomeSize=200m saveReads=true -pacbio-hifi hifi_sel.fastq
```
However, it finishes without any apparent error, but I don't get the expected *correctedReads.fasta.gz file. Please, see below the messages I got. I also tried the -trim option with the same library and I got the trimmedReads.fasta.gz. But, as far as I understood, the read correction should be done before trimming.

Any clue? 

Thanks in advance,
Francisco.

```
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Sat Jun 26 01:54:30 2021 with 497305.322 GB free disk space

    cd .
    ./asm_correct2.seqStore.sh \
    > ./asm_correct2.seqStore.err 2>&1
                      

-- Finished on Sat Jun 26 01:55:42 2021 (72 seconds) with 497259.313 GB free disk space
----------------------------------------
----------------------------------------
-- Starting command on Sat Jun 26 01:55:42 2021 with 497259.313 GB free disk space

    cd .
    /crex/proj/sllstore2017073/private/GRC/Paco/sumk/canu/canu-2.1.1/bin/sqStoreDumpMetaData \
      -S ./asm_correct2.seqStore \
      -raw \
      -histogram \
      -lengths \
    > ./asm_correct2.seqStore/readlengths-cor.dat \
    2> ./asm_correct2.seqStore/readlengths-cor.err 
    

-- Finished on Sat Jun 26 01:55:42 2021 (lickety-split) with 497259.313 GB free disk space
----------------------------------------
--
-- WARNING: gnuplot failed.
--
----------------------------------------
----------------------------------------
-- Starting command on Sat Jun 26 01:55:42 2021 with 497259.313 GB free disk space

    cd .
    /crex/proj/sllstore2017073/private/GRC/Paco/sumk/canu/canu-2.1.1/bin/sqStoreDumpMetaData \
      -S ./asm_correct2.seqStore \
      -raw \
      -histogram \
    > ./asm_correct2.seqStore/readlengths-cor.txt \
    2> ./asm_correct2.seqStore/readlengths-cor.err 
    

-- Finished on Sat Jun 26 01:55:42 2021 (in the blink of an eye) with 497259.313 GB free disk space
----------------------------------------
--
-- In sequence store './asm_correct2.seqStore':
--   Found 0 reads.
--   Found 0 bases (0 times coverage).
--
-- WARNING:
-- WARNING:  No raw reads detected.  Cannot proceed; empty outputs generated.
-- WARNING:
--

```

**Comment by skoren** [comment]
The correction step is not supported or recommended for HiFi reads due to their high accuracy. It would not preserve phase within the reads which would corrupt their usefulness for repeat and phasing resolution. Trimming is also not used by default, poor quality reads are discarded during assembly instead. There is a different more conservative correction step within the unitigging stage for this type of data instead so if you ran a standard HiFi assembly (without adding the -correct option), you could generate compressed conservatively corrected reads from the intermediate outputs (see the `fixErrors` binary in Canu tip).

**Comment by fjruizruano** [comment]
It makes sense now. I will try to do as you recommend.
Thanks a lot for your fast response.

**Comment by fjruizruano** [comment]
Hi again,

I have run HiCanu with the following options:

`
/home/fruano/bin/canu-2.1.1/bin/canu \
 -p asm_si_grid \
 -d asm_si_grid \
 useGrid=true \
 gridOptions="$GRID_OPTIONS" \
 genomeSize=1500m \
 saveReadCorrections=true \
 saveReadHaplotypes=true \
 saveReads=true \
 -pacbio-hifi tgut_testis_hifi.fastq
 utgOvlMerThreshold=300
 utgovlThreads=5
`
And I didn't get the corrected or trimmed reads ("<prefix>.correctedReads.fasta.gz" or "<prefix>.trimmedReads.fasta.gz") after HiCanu finished without any apparent error.

Do you have any clue about what can be failing?

Thanks in advance,
Francisco.

**Comment by skoren** [comment]
HiCanu doesn't trim or correct the HiFi reads in the traditional sense, it's not necessary given their high quality. So it's fine that you don't have those files, there isn't an error. You can output compressed and corrected HiFi reads if you wanted to using the `fixErrors` (run it w/o options to see the parameters`)
