### ISSUE TITLE
walltime and queue limits in batch jobs #gridOptions

### ISSUE THREAD

**Issue by lifan18** [marbl/canu#1969]
Dear canu

I manage to qsub my canu work.sh to my university HPC system. However, the system requires a fixed walltime and queue settings. For the jobs which require less than 96 gb memory and only require 1 node (up to 24 cores) I could request the walltime up to 120 hours in a normal queue. Once the batch jobs require more memory, cores or walltime, the batch jobs will be terminated. The 120 hours is the maximum walltime. If I require larger memory or cores, the walltime will be requested less than 24 hours.

Could you give me some suggestion for the job submission? For your reference, I attached the details at the end of this text.

Thank you very much!

Regards

Fan

java version "1.8.0_291"
canu 2.1.1
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 6.10 (Santiago)
Release:	6.10
Codename:	Santiago

<img width="633" alt="image" src="https://user-images.githubusercontent.com/44634495/123574487-85210500-d802-11eb-90fd-cd2d1d4ef1f6.png">
<img width="658" alt="image" src="https://user-images.githubusercontent.com/44634495/123574550-9ec24c80-d802-11eb-927b-954dbfa58993.png">

```
###work.sh
#!/bin/bash
#PBS -q normal
#PBS -P 11000267
#PBS -l walltime=24:00:00

export PATH=/home/users/00.bin/jre1.8.0_291/bin/:$PATH

/home/users/00.bin/canu-2.1.1/bin/canu -p LiphistSX -d /home/users/01.canu-assembly-Liphistiidae/ genomeSize=4.04g -minReadLength=3000 -pacbio /home/users/sx_genome_wtdbg2/m64061_191215_062620.subreads.fasta.gz gridOptions="-V -P 11000267 -l walltime=24:00:00 -q normal"
```

```
##less cor_LiphistSX.o4923787.59
Running job 59 based on PBS_ARRAY_INDEX=59 and offset=0.
=>> PBS: job killed: walltime 86498 exceeded limit 86400
======================================================================================

                        Resource Usage on 2021-06-28 08:32:19.709562:

        JobId: 4923787[59].wlm01
        Project: 11000226
        Exit Status: 271
        NCPUs Requested: 4                              NCPUs Used: 4
                                                        CPU Time Used: 39:29:32
        Memory Requested: 24gb                          Memory Used: 16222272kb
                                                        Vmem Used: 16341444kb
        Walltime requested: 24:00:00                    Walltime Used: 24:01:38

        Execution Nodes Used: (std1622:ncpus=4:mem=25165824kb)
```

**Comment by skoren** [comment]
None of the Canu steps usually require more than 96gb of memory so you can use the smaller nodes. There is a summary of resources to be used listed when you start Canu so you can check that to confirm. 

It looks like a correction job ran out of time. If it's only one job having issues, not many of them, you can just adjust your walltime from 24 to 120 hours and let the failing job re-run. This step is very I/O heavy and can be much faster if you have access to and use local scratch space on your nodes. See the https://canu.readthedocs.io/en/latest/parameter-reference.html?highlight=stage#file-staging info. You could also make more faster jobs (see #1965) but I'd only recommend that if many of the correction jobs are failing and you're unable to use scratch space.

**Comment by skoren** [comment]
The unitigging step can over-estimate memory. Your genome is relatively large but we've definitely run that size in under 200gb. You can try 90 and if it isn't enough it will complain and exit and you can restart with larger memory. So add batMemory=90

**Comment by lifan18** [comment]
Hi Dr. Skoren

As the resource or walltime always exceeded limit when batch jobs submitted by canu automatically , I would like to submit these jobs manually. I found running Canu with `useGrid=remote` which will stop at every submit command, list what should be submitted. Although I tried this command as the following, it still automatically submit jobs. Is there anything wrong with my command?

Thank you for your time!

With kindest regards,

Fan


```
###work.sh
#!/bin/bash
#PBS -q normal
#PBS -P 11000267
#PBS -l walltime=24:00:00

export PATH=/home/users/00.bin/jre1.8.0_291/bin/:$PATH

/home/users/00.bin/canu-2.1.1/bin/canu -p LiphistSX -d /home/users/01.canu-assembly-Liphi/ genomeSize=4.04g -minReadLength=3000 -pacbio /home/users/sx_genome_wtdbg2/m64061_191215_062620.subreads.fasta.gz useGrid=remote gridOptions="-V -P 11000226 -l walltime=24:00:00 -q normal"

```


```

-- Starting 'cormhap' concurrent execution on Mon Jun 28 17:33:31 2021 with 920748.443 GB free disk space (138 process
es; 1 concurrently)

    cd correction/1-overlapper
    ./precompute.sh 1 > ./precompute.000001.out 2>&1
    ./precompute.sh 2 > ./precompute.000002.out 2>&1
    ./precompute.sh 3 > ./precompute.000003.out 2>&1
    ./precompute.sh 4 > ./precompute.000004.out 2>&1
    ./precompute.sh 5 > ./precompute.000005.out 2>&1
    ./precompute.sh 6 > ./precompute.000006.out 2>&1
    ./precompute.sh 7 > ./precompute.000007.out 2>&1
    ./precompute.sh 8 > ./precompute.000008.out 2>&1
    ./precompute.sh 9 > ./precompute.000009.out 2>&1
    ./precompute.sh 10 > ./precompute.000010.out 2>&1
    ./precompute.sh 11 > ./precompute.000011.out 2>&1
    ./precompute.sh 12 > ./precompute.000012.out 2>&1
    ./precompute.sh 13 > ./precompute.000013.out 2>&1
    ./precompute.sh 14 > ./precompute.000014.out 2>&1
    ./precompute.sh 15 > ./precompute.000015.out 2>&1
    ./precompute.sh 16 > ./precompute.000016.out 2>&1
    ./precompute.sh 17 > ./precompute.000017.out 2>&1
    ./precompute.sh 18 > ./precompute.000018.out 2>&1
    ./precompute.sh 19 > ./precompute.000019.out 2>&1
    ./precompute.sh 20 > ./precompute.000020.out 2>&1
    ./precompute.sh 21 > ./precompute.000021.out 2>&1
    ./precompute.sh 22 > ./precompute.000022.out 2>&1
    ./precompute.sh 23 > ./precompute.000023.out 2>&1
    ./precompute.sh 24 > ./precompute.000024.out 2>&1
=>> PBS: job killed: walltime 86515 exceeded limit 86400

```

**Comment by skoren** [comment]
If all you need is longer wall time, you don't need to use remote. You can edit your canu command to change your gridOptions parameter: `gridOptions="-V -P 11000226 -l walltime=24:00:00 -q normal"` from 24 to whatever you want/is allowed by the grid.

If you do use remote, it expects to be launched on a head node not within a job. So don't  submit the work.sh script as you are now, run the Canu command directly on the head node instead. It won't run computation, just output the job to run.

**Comment by skoren** [comment]
Idle
