### ISSUE TITLE
question: re-running CANU with different cor parameters

### ISSUE THREAD

**Issue by StefanoLonardi** [marbl/canu#197]
First, thanks for a wonderful assembler. 

I have 91x pacbio coverage for a 620Mb genome.  I have run successfully
`canu corMhapSensitivity=low -p cowpea -d cowpea genomeSize=620m -pacbio-raw ./pacbio/*.fasta` (took 4 days on our Torque server).

I understand that if I want to try `corMhapSensitivity=high` I will have to start from scratch, but how about if what to test `corMhapSensitivity=low` with a different value of `corOutCoverage` or `corMinCoverage`. Can I reuse the initial overlap step? What directories need to deleted to force CANU to restart at the correct stage?

**Comment by brianwalenz** [comment]
Thanks to you for the excellent question.

You need to remove just the 2-correction directory, and the output files in cowpea/ itself.  However, I'd make a new work directory and symlink in the previous data.  For further paranoia, remove the write bit from those two stores.

mkdir cowpea2
cd cowpea2
ln -s ../cowpea/correction/cowpea.gkpStore .
ln -s ../cowpea/correction/cowpea.ovlStore .
ln -s ../cowpea/[01]* .

It _might_ work with just the two stores, but I don't think it's been tested.  Worst case, canu will launch a 'meryl' job.

**Comment by StefanoLonardi** [comment]
Thanks. What is `ln -s ../cowpea/[01]* .` supposed to do? It did not create a valid link in my case.

**Comment by brianwalenz** [comment]
That was supposed to link the 0-mercounts and 1-overlapper directory into the current directory.  Looks like I left out 'correction/' from the path, oops!  (I edited the comment to fix this)

**Comment by StefanoLonardi** [comment]
thank you, it is working (CANU restarted and did not touch gkpStore or  ovlStore). Cheers.
