### ISSUE TITLE
Correct not generating correctedReads

### ISSUE THREAD

**Issue by Ptero64** [marbl/canu#1971]
Hello,
I trying to use on a hpc Canu -correct to correct Nanopore raw reads. I ahve installed Canu via Conda (with gnuplot). The submitted job end without error message but generate no fasta.gz corrected outputs.

Here is the command used:
```
canu -correct minReadLength=500 corOutCoverage=1000 corMhapSensitivity=high \
corMinCoverage=0 redMemory=32 oeaMemory=32 batMemory=200 genomeSize=200m -p test.fastq -d test \
-nanopore-raw /data/scratch/btx246/RawReads_DeNovo/test.fastq gridEngineMemoryOption="-l m_mem_free=MEMORY"
```
I am running on a hpc working under CentOS 7.9
canu -version is supposed to be the 2.1 but this is the info from the output file:
```
Variable OMP_NUM_THREADS has been set to 12
-- Canu v0.0 (+0 commits) r0 unknown-hash-tag-no-repository-available.
-- Detected Java(TM) Runtime Environment '1.8.0_92' (from 'java').
-- Detected gnuplot version '4.6 patchlevel 0' (from 'gnuplot') and image format 'svg'.
-- Detected 24 CPUs and 756 gigabytes of memory.
-- Detected Sun Grid Engine in '/data/ITSR-Scheduler/8.6.12/default'.
-- Detected Grid Engine environment 'smp'.
-- User supplied Grid Engine consumable '-l m_mem_free=MEMORY'.
```

I alos tried loading canu 1.6 and gnuplot installed as modules on the cluster. The run also failed unfortunately. Same adding the command gnuplotTested=true

Thanks for the help,

Regards

**Comment by brianwalenz** [comment]
First, make sure that canu is not still running.  It submits and resubmits itself to the grid multiple times.

Check the logging of the last iteration.  This is in file `canu.out`.  Errors for specific compute jobs will be in `*.out` or `*.err` files with names similar to the name of the FAILED file, for example:
```
-- Read correction jobs failed, tried 2 times, giving up.
--   job 2-correction/results/0001.cns FAILED.
```
would have errors in files `0001.err` in the same directory.

**Comment by Ptero64** [comment]
Hi, 
Thanks for your answer. 
Yes I checked on the cluster that all jobs were finished (e.g. ```meryl.jobSubmit-01.sh canu.01.sh to canu.04.sh```).
I havent found in my output folder  any ``` *.err``` files  (but I have large errorLog file)
In -d ```folder/canu.out``` I have this error message
``` ERROR:  Failed to run gnuplot from 'gnuplot'.ERROR:  Set option gnuplot=<path-to-gnuplot> or gnuplotTested=true to skip this test and not generate plots.
```
A correction.html is genetrad and the fours folders: ``` canu-logs/ canu-scripts/ correction/ correction.html.files/ ```
Within ``` correction/0-mercounts/meryl.1.out``` I found lines with this error message:
```
/opt/sge_spool/8.5.4/sdv45/job_scripts/1583088: line 48: 127637 Segmentation fault      $bin/meryl -Dh -s ./DynamicH_124_13DN16_HRV.fastq.ms16 > ./DynamicH_124_13DN16_HRV.fastq.ms16.histogram.WORKING 2> ./DynamicH_124_13DN16_HRV.fastq.ms16.histogram.info
/opt/sge_spool/8.5.4/sdv45/job_scripts/1583088: line 63: 127639 Segmentation fault      $bin/estimate-mer-threshold -h ./DynamicH_124_13DN16_HRV.fastq.ms16.histogram -c 12 > ./DynamicH_124_13DN16_HRV.fastq.ms16.estMerThresh.out.WORKING 2> ./DynamicH_124_13DN16_HRV.fastq.ms16.estMerThresh.err

mv: cannot stat ‘./DynamicH_124_13DN16_HRV.fastq.ms16.WORKING.mcdat’: No such file or directory
```
Thanks

**Comment by brianwalenz** [comment]
For gnuplot, you probably need to give a path to the binary using the canu `gnuplot` option.  This isn't critical, it's only used for some diagnostic plots.

The meryl step(s) aren't known to segfault, and I will guess conda failed to install some compiler library.  You can try running meryl by hand, with no options, to see if it runs.  If it doesn't even do that, I'd suggest installing canu yourself either from source or precompiled binaries.  https://github.com/marbl/canu/releases/tag/v2.1.1

Are there any other messages in meryl.1.out?

**Comment by Ptero64** [comment]
Hi,
No there was not other errors message in meryl.1.out

I have made a clean install of canu 2.1.1 I tested on one sample (not array jobs with SGE) on the cluster. command
```
/data/scratch/btx246/PipelineMetagenomic/canu-2.1.1/build/bin/canu  -correct minReadLength=500 corOutCoverage=1000 corMhapSensitivity=high \
corMinCoverage=0 redMemory=32 oeaMemory=32 batMemory=200 genomeSize=200m -p DynamicH_124_13DN16_HRV.fastq -d test \
-nanopore-raw /data/scratch/btx246/RawReads_DeNovo/20210617_DynamicH_124-156/DynamicH_124_13DN16_HRV.fastq gridEngineResourceOption="-pe smp 12 THREADS -l highmem=MEMORY"
```
I still ended with an error message with meryl step I think. 
A ```meryl-count.jobSubmit-01.sh``` is submitted:
```
#!/bin/sh

qsub \
  -pe smp 12 4 -l highmem=2g -j y -o meryl-count.\$TASK_ID.out \
  -cwd -N "meryl_DynamicH_124_13DN16_HRV.fastq" \
  -t 1-1 \
  `pwd`/meryl-count.sh 0 \
> ./meryl-count.jobSubmit-01.out 2>&1
```
but failed with this error message:
```
Unable to read script file because of error: error opening 4: No such file or directory
```
After reading an other issue post, is it possible to use canu as an array job with SGE on a cluster?

**Comment by skoren** [comment]
Your gridEngineResourceOption is wrong which is causing SGE to not realize what script to read (it thinks the script is named `4`). You shouldn't specify both a thread value (12) and THREADS (which gets dynamically updated by Canu). It should be something like: `gridEngineResourceOption="-pe smp THREADS -l highmem=MEMORY`

**Comment by skoren** [comment]
Idle
