### ISSUE TITLE
which one should l use?

### ISSUE THREAD

**Issue by ld9866** [marbl/canu#1972]
I assembled a genome using HICANU software, now which FASTA file should I use for the next HIC mount?
ccs_asm.contigs.fasta
ccs_asm.unassembled.fasta
ccs_asm.unitigs.fasta

**Comment by brianwalenz** [comment]
Contigs.  More details on the outputs of Canu are at https://canu.readthedocs.io/en/latest/tutorial.html#outputs.

Please check which version of Canu you used.  I think you might be using version 2.0.  Version 2.1.1 is the latest and contains numerous improvements for HiFi data.

**Comment by skoren** [comment]
You also probably want to run purge_dups as recommended here: https://canu.readthedocs.io/en/latest/faq.html#my-genome-size-and-assembly-size-are-different-help

**Comment by ld9866** [comment]
thank you! l will change the version and try to handle it.
