### ISSUE TITLE
ERROR:  Required parameter 'genomeSize' not set.

### ISSUE THREAD

**Issue by ld9866** [marbl/canu#1973]
Hello!
How can I evaluate this genome size when using Hicanu to assemble HIFI data?

**Comment by skoren** [comment]
You can provide an estimate of your genome size, it doesn't have to be exact. It's only used to report NG50 values and set job sizes. If you have no idea of a size, you can run genomescope (http://qb.cshl.edu/genomescope/genomescope2.0/) on your HiFi data to get an estimate.
