### ISSUE TITLE
sqStoreCreate cannot be opened, not notarized, developer cannot be verified

### ISSUE THREAD

**Issue by jim1884** [marbl/canu#1974]
downloaded canu-2.1.1.Darwin-amd64.tar.xz 30 June 2021 because I had the mhap precompute jobs failed issue with Anaconda installed canu 1.5 from bioconda.

program stops with system warning:
`
"sqStoreCreate" cannot be opened because the developer cannot be verified. It means that the app was not notarized, and Apple could not scan the app for known malicious software. macOS cannot verify that this app is free from malware.
move to trash or cancel
`

`
ABORT:   sqStoreCreate failed; boom!.
`

command line used:
Canu-2.1.1/bin/canu useGrid=False -p bacillus.clr -d 04-CLR-asbld4 genomeSize=5.5m -pacbio 03-CLR/isi_run_01.clr.fq

System:
MacBook Pro, Big Sur, 11.4,3.1 GHz Dual-Core Intel Core i5
8 GB 2133 MHz memory, 
Using Anaconda Navigator 2.03 to set up python 2.7 and python 3.9 environments.

I haven't seen this red flag previously on other software.
Please advise, can you notarize sqStoreCreate?

**Comment by skoren** [comment]
We have no apple developer account so there's no way to notarize. You should still be able to run unsigned apps, see https://support.apple.com/en-us/HT202491

**Comment by jim1884** [comment]
Thanks for the reply. Could a checksum be supplied to insure the files are legitimate?

**Comment by skoren** [comment]
The md5sum for the tar download is a58fb625fc364904245f655f7debb92d and the file size is 4384156. For the sqStoreCreate specifically, it's e649dfb0fc5bf360a13b75d32c6ab542.

**Comment by skoren** [comment]
We cannot sign the binaries w/o an apple developer license but the MD5 should be sufficient to verify the binaries.

**Comment by skoren** [comment]
I confirmed this issue after upgrading to OS X 10.15. The fix is to run:
```
xattr -d com.apple.quarantine ./canu-2.1.1/bin/*
xattr -d com.apple.quarantine ./canu-2.1.1/lib/*
```
Verify the MD5 matches to make sure the binaries are legitimate first.
