### ISSUE TITLE
Launch canu on SGE

### ISSUE THREAD

**Issue by HadrienRegue** [marbl/canu#1975]
Hello,

First thanks for your tool! We are using CANU for ont read correction. After few test, we want to apply correction on all of our reads, for all of our samples. The computing time is strongly increased, so we want to try to do it on grid.

I'm far from being an expert in grid systems and job submission, so I cant clearly identify the problem.
Here is my command:
```
./canu/build/bin/canu -correct \
    -nanopore DATASET_HBV/barcode02_02PARIS/*.fastq \
    -p barcode02_02PARIS \
    -d test/ \
    genomeSize=3200 \
    correctedErrorRate=0.105 \
    maxInputCoverage=1000 \
    useGrid=True \
    gridEngine=sge \
    gridOptionsJobName=barcode02_02PARIS \
    gridOptions='-q E5_test -pe test_debian 16' 
```
And here is the output error:

```
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_272' (from 'java') with -d64 support.
-- Detected gnuplot version '5.0 patchlevel 5   ' (from 'gnuplot') and image format 'png'.
--
-- Detected 16 CPUs and 126 gigabytes of memory on the local machine.
--
--
--
-- ERROR:  No Sun Grid Engine Parallel Environment is using allocation rule '$pe_threads'.
-- ERROR:  Multi-thread execution not supported on this grid.
--
```

I dont realy get the error. It seems the grid is not detected? Tell me if you need more informations.

EDIT: maxInputCoverage=1000 is not the desired coverage, its only for testing purposes. 

Thanks,

Hadrien

**Comment by skoren** [comment]
Canu can't find an appropriate way to reserve threads on your grid. You need something that will allocate all the requested cores on a single node, typically denoted as pe_threads. See http://gridscheduler.sourceforge.net/htmlman/htmlman5/sge_pe.html for details on the allocation rules. You don't want any that distributes cores among more than one node, that won't work. You want to run `qconf -spl` to see what parallel environments are available on your grid and then run `qconf -sp <name>` for each one to check their allocation rules to find a suitable one. For memory, you want to run `qconf -sc` and find a consumable memory resource that isn't VM or swap. You can post the output of both of the above if you want help picking the right ones.

You can force Canu to use specific thread/memory allocation by specifying the gridEngineResource parameter (https://canu.readthedocs.io/en/latest/parameter-reference.html#grid-engine-configuration), e.g. `gridEngineResourceOption="-pe test_debian THREADS -l mem_free MEMORY"`. However, if test_debian will allocate threads across more than one node that will cause issues.

**Comment by HadrienRegue** [comment]
Thank you for the help.

I think some features are locked on our grid due to admin restriction.
I tried the following command:`qconf -spl`, however I get this message:
`denied: host "e5-2670comp2" is not an admin host`

When logged to our cluster, we have to submit job from "frontal servers", such as e5-2670comp2 it that case. Canu can still adress submissions from there, or it should be submitted from a script?

**Comment by skoren** [comment]
Canu expects to be launched on the head node but it does require the nodes where the jobs land to be able to submit subsequent jobs (see the FAQ: https://canu.readthedocs.io/en/latest/faq.html#my-run-stopped-with-the-error-failed-to-submit-batch-jobs). If your compute nodes are not allowed to submit jobs, Canu will not run out of the box on the system. You have the options described on the FAQ to either use a single node or manually submit jobs at each step.

**Comment by HadrienRegue** [comment]
Thanks for your time.
I will check these options for my analysis, .

Best,

Hadrien

**Comment by HadrienRegue** [comment]
Hello again,

We reworked our Canu command:
```
/home/hregue/canu/build/bin/canu -correct \
    -nanopore /home/hregue/DATASET_HBV/barcode02_02PARIS/*.fastq \
    -p barcode02_02PARIS \
    -d /home/hregue/test/ \
    genomeSize=3200 \
    correctedErrorRate=0.105 \
    maxInputCoverage=1000 \
    useGrid=remote \
    gridEngine=sge \
    gridOptionsJobName=barcode02_02PARIS \
    gridEngineResourceOption="-q E5_test -pe test_debian 16" \
    maxMemory=16 \
    maxThreads=16
```

We've tried to use Canu with useGrid=remote .
```
cd /home/hregue/test/correction/0-mercounts
./meryl-process.jobSubmit-01.sh
```

I used this given command then Canu told me to relaunch the main Canu command, however, It's adress me the same submission script (./meryl-process.jobSubmit-01.sh).

I haven't any current job with `qstat -u hregue` and I dont realy get what shloud I do next, or check in the output files if everything worked fine:
```
hregue@e5-2670comp1:~/test/correction/0-mercounts$ ls
barcode02_02PARIS.ms16                barcode02_02PARIS.ms16.ignore.gz  meryl-count.jobSubmit-01.sh  meryl-process.1.out
barcode02_02PARIS.ms16.config.01.out  meryl-configure.sh                meryl-count.sh               meryl-process.jobSubmit-01.out
barcode02_02PARIS.ms16.dump           meryl-count.1.out                 meryl-count.success          meryl-process.jobSubmit-01.sh
barcode02_02PARIS.ms16.histogram      meryl-count.jobSubmit-01.out      meryl-make-ignore.pl         meryl-process.sh
```

Thanks

**Comment by skoren** [comment]
What's the output in all files of the form `meryl-process.*.out`?

**Comment by HadrienRegue** [comment]
I think I was a bit tired yesterday. The given command was different on each canu execution after finished job.

Every think worked fine, I have completed my analysis using the remote option.

Huge thanks for the provided help:)
Best,

Hadrien

**Comment by skoren** [comment]
Glad you figured it out.
