### ISSUE TITLE
Error when using trim

### ISSUE THREAD

**Issue by TT1972** [marbl/canu#1976]
Hi, 

Not sure if this is an issue, or the problem is sitting in front of the computer.

We finished sequencing our first genome using the nanopore MinION and I am currently trying to assemble it. I am using Canu (canu snapshot v2.2-development) and have finished the correction using the following command:

canu -correct -p fastq_runid -d /home/torsten/d-drive/MinION/basecalled/ genomeSize=38m -nanopore-raw /home/torsten/d-drive/MinION/basecalled/*.fastq.gz

Now I want to start the trimming process but I ran into a problem. I am using the following command:

canu -trim -p fastq_trim -d /home/torsten/d-drive/MinION/basecalled/trim/ genomeSize=38m -corrected -nanopore /home/torsten/d-drive/MinION/basecalled/fastq_runid.correctedReads.fastq.gz

This produces the following error:

ERROR:  Invalid command line option '/home/torsten/d-drive/MinION/basecalled/fastq_runid.correctedReads.fastq.gz'.  Did you forget quotes around options with spaces?

Can anybody tell me, what I am doing wrong?

Cheers,

Torsten

**Comment by TT1972** [comment]
Found the error. I unzipped the fastq_runid.correctedReads.fastq.gz file using gunzip. Now it works.

**Comment by skoren** [comment]
I was going to suggest checking the input file, Canu can read gzipped and bzipped files but if it works with the unzipped file, then that is also fine.
