### ISSUE TITLE
About Hicanu reads correction

### ISSUE THREAD

**Issue by zhoudreames** [marbl/canu#1977]
I only gain compressed reads and the reads IDs lost raw hifi reads name by running hicanu,but i want to gain decompressed reads and  saved the hifi raw IDs after reads corrected.could you help me?  thanks~

**Comment by zhoudreames** [comment]
@hyphaltip @jxtx @hartzell @jts I am a little anxious and very sorry to disturb you，thanks~

**Comment by skoren** [comment]
I've asked you multiple times to stop tagging people in issues without at least waiting for a response. Many times these are issues you've already emailed about (and gotten responses) or they can be easily solved by basic searches/reading the documentation. Further, you tag a random selection of people, many of whom are not at all associated with the issue at hand. You're getting free support for open source tools, it is rude to disturb people and demand immediate response. I am not going to ask again, this is your last warning and you will be banned from our repos if you do it again.

There are no decompressed corrected reads in HiCanu, as I already explained. There are corrected and compressed reads which are output using the internal IDs. You can translate these IDs to raw IDs using the seqStore information as documented on the FAQ: https://canu.readthedocs.io/en/latest/tutorial.html#outputs under Metadata.
