### ISSUE TITLE
Can't locate Filesys/Df.pm

### ISSUE THREAD

**Issue by powellhd** [marbl/canu#198]
Hi,

After downloading the source and compiling it, as suggested under "Getting Started:", I tried to run canu as suggested under "Run:" and received the following error (I am using perl v5.10.1):

Can't locate Filesys/Df.pm in @INC (@INC contains: /hits/fast/cbi/prog/canu/Linux-amd64/bin/lib/canu/lib64/perl5 /hits/fast/cbi/prog/canu/Linux-amd64/bin/lib/canu/lib/perl5 /hits/fast/cbi/prog/canu/Linux-amd64/bin/lib /hits/fast/cbi/prog/canu/Linux-amd64/bin/lib/canu /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /hits/fast/cbi/prog/canu/Linux-amd64/bin/lib/canu/Defaults.pm line 50.
BEGIN failed--compilation aborted at /hits/fast/cbi/prog/canu/Linux-amd64/bin/lib/canu/Defaults.pm line 50.
Compilation failed in require at ./canu line 52.
BEGIN failed--compilation aborted at ./canu line 52.

**Comment by brianwalenz** [comment]
For now, modify src/pipelines/canu/Defaults.pm to:

1) comment out (add '#' to the start of the line) line 50.
2) replace all of the diskSpace function at line 321-331 with:

sub diskSpace ($) {
  return(10);
}

I'll get a real fix in the near future.

This just disables

**Comment by brianwalenz** [comment]
All fixed.
