### ISSUE TITLE
Issues passing grid options

### ISSUE THREAD

**Issue by bbarbazuk** [marbl/canu#1981]
HI,
I am currently running correction on canu 2.1 on a SLURM grid.

My command is:
```
#!/bin/bash
#SBATCH --job-name=canu_Td1
#SBATCH --mail-user=bbarbazuk@ufl.edu
#SBATCH --mem=8gb
#SBATCH -t 96:00:00 
#SBATCH --output=outCanu_Td1%j.out
#SBATCH --error=errCanu_Td1%j.err
#SBATCH --qos=barbazuk
export PROJ_ROOT="/barbazuk/bb01/Td_genome/SEQ"

module load ufrc
module load gcc/5.2.0
module load gnuplot/4.6.0
module load canu/2.1
module load java/1.8.0_31
export _JAVA_OPTIONS="-Xmx16g"


canu -correct \
-p Td_2.1_07112021 -d Td_2.1_correct_07112021 \
genomeSize=2.5g \
rawErrorRate=0.300 \
correctedErrorRate=0.045 \
corMhapSensitivity=normal \
corMinCoverage=4 \
corOutCoverage=40 \
minOverlapLength=500 \
minReadLength=1000 \
shell="/bin/bash" \
java="/apps/java/1.8.0_31/bin/java" \
gnuplot="/apps/gcc/5.2.0/gnuplot/5.0.3/bin/gnuplot" \
gnuplotImageFormat=svg \
-pacbio $PROJ_ROOT//XDOVE_20210308_S64018_PL100167692-1_B01.subreads.fastq.gz \
$PROJ_ROOT/XDOVE_20210329_S64018_PL100167692-2_B01.subreads.fastq.gz \
$PROJ_ROOT/XDOVE_20210329_S64018_PL100167692-2_C01.subreads.fastq.gz \

usegrid=true \
gridOptionsJobName=CANU2.1-default \
gridOptions="-t=96:00:00 --qos=barbazuk-b --ntasks=1"
```
The issues I have is that the script canu generates and submits seem to ignore the gridOptions I have passed: they run on the wrong queue (my investment queue although I have specified my bust queue) and have the incorrect time limit applied.

Any suggestions as to what I've done to make the command blind to my passed options?

Thanks for your help!

Brad

**Comment by skoren** [comment]
Canu reports all the options that it was provided and includes them in the `canu-scripts/canu.*.sh` file. If grid options aren't there, then the shell didn't pass them to Canu. Most likely the issue is the empty line without a continuation `\` between your options and useGrid=true. I suspect the job name isn't being set either if that's the case.
