### ISSUE TITLE
Which is more suitable for combination with canu

### ISSUE THREAD

**Issue by ld9866** [marbl/canu#1986]
Hello, I'm assembling a simple genome of a diploid mammal. Canu has a very good effect, but I also have HIC data results. I want to ask you which HIC software should I use to combine canu to get better assembly results?

**Comment by skoren** [comment]
We typically use Salsa (make sure you run purge_dups on the assembly just to make sure you don't have uncollapsed haplotypes first) but we've also had good result with 3D-DNA.

**Comment by ld9866** [comment]
Thank you for your reply. I will try to use these two software for follow-up analysis.
