### ISSUE TITLE
What is my version of Canu?

### ISSUE THREAD

**Issue by aaronphillips7493** [marbl/canu#1988]
Hey,

I'm trying to get the version of Canu I used for the assembly of a genome in March 2020. I installed it using conda on a old version of our HPC, which was upgraded at the end of last year. During the upgrade we had to migrate data over from the old system to the new. I managed to copy the conda environment for Canu over. 

I used the command:
`canu -version `

and I get the following output:
`canu branch HEAD +0 changes (r10117 5638f7d9a5379373310ab62c28aa0cdbd864722d)`

Just wondering, what does this mean? And how do I report this in a paper?

Thanks,
Aaron :)

**Comment by brianwalenz** [comment]
That corresponds exactly to version 2.1.1.  I don't know why installs through conda don't report the version correctly.

However, version 2.1.1 came out in October 2020 (https://github.com/marbl/canu/releases) which makes it unlikely you used this in March 2020.  If you still have the canu output directory, look in some of the `*.log`, `*.out` and `*.err` files in there.  Many of them will also report the version of the code used.

The big string of hexadecimal is the 'git hash' that points to exactly the code that is used.  I don't know of a way to nicely 'search' github for this, but the link is easy to create: https://github.com/marbl/canu/commit/5638f7d9a5379373310ab62c28aa0cdbd864722d

**Comment by aaronphillips7493** [comment]
Ah ok, I must have updated Canu after the fact, which means the original version must be lost. 

I just investigated a *.out file in canu-scripts and it says:
```
Found canu:
   /fast/users/a1779884/rice_genomics/.snakemake/conda/b07b1fd5/bin/canu
   Canu snapshot ()
```

Does this mean the version is called snapshot?

Thank you very much for your help,
Aaron :)

**Comment by skoren** [comment]
Snapshot isn't a version, it's what gets reported when Canu can't figure out what version it is. Unfortunately, that isn't really a reportable version. This is an artifact of the conda installation. I'm not sure how it pulls the Canu repo and we don't control the install recipe which has had numerous issues in the past. My best guess is you used the 2.0 release which was released in March 2020 but without the conda installation logs it'll be hard to know exactly.
