### ISSUE TITLE
How to check if Canu 2.1.1 job is still running or completed

### ISSUE THREAD

**Issue by ardy20** [marbl/canu#1989]
Hi 

After submission of job via PBSpro batch system (qsub), It is difficult to see the status of job and its progress. 

Does Canu 2.1.1 send notification upon completion?

Could you please indicate to which folder the output.fasta get stored?

Regards

**Comment by skoren** [comment]
You can check the status of the job using standard grid commands (like qstat). The output (documented here: https://canu.readthedocs.io/en/latest/tutorial.html#outputs) goes into whatever you specified as the -d parameter. There is also a canu.out file in that folder which lists the last jobs run and submitted to the grid.
