### ISSUE TITLE
Interaction of corOutCoverage & correctedErrorRate

### ISSUE THREAD

**Issue by fergsc** [marbl/canu#1990]
Hi,
I have a large amount of ONT data and want to reduce how much is used for trimming and assembly. The parametes that impact the most on coverage retained after correction appear to be `corOutCoverage` and `correctedErrorRate`. I hope this is true.

My question is, which of these filters is applied first? Are reads filtered by error rate and then the longest X coverage of those that pass error filtering, corrected and keeped. Or are the longest X coverage of reads aligned and error rate filtered?

I am trying to find all reads that are above X quality (correctedErrorRate) and then downsample to X coverage.

Thanks.

**Comment by brianwalenz** [comment]
There isn't an explicit filter on read quality.  `correctedErrorRate` is used akin to a volume knob when finding overlaps, and overlaps below this cutoff are used for trimming and assembly.  Most of the overlaps are well below this cutoff.

`corOutCoverage` is the parameter you want to fiddle with.  This is applied before the corrected read sequences are generated.  The correction algorithm will estimate the length (but not quality) of each corrected read, then generate only the longest corrected reads up to `corOutCoverage`.
