### ISSUE TITLE
Assembling microbial genome from ONT data

### ISSUE THREAD

**Issue by ramnageena11** [marbl/canu#1992]
```
--Detected Java(TM) Runtime Environment '11.0.11' (from 'java') without -d64 support.
-- Detected gnuplot version '5.2 patchlevel 8   ' (from 'gnuplot') and image format 'png'.
-- Detected 12 CPUs and 31 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |     total usage     algorithm
--        -------  ------  --------   --------  -----------------  -----------------------------
-- Local: meryl     10 GB    4 CPUs x   3 jobs    30 GB   12 CPUs  (k-mer counting)
-- Local: hap        8 GB    4 CPUs x   3 jobs    24 GB   12 CPUs  (read-to-haplotype assignment)
-- Local: cormhap    6 GB   12 CPUs x   1 job      6 GB   12 CPUs  (overlap detection with mhap)
-- Local: obtovl     4 GB    6 CPUs x   2 jobs     8 GB   12 CPUs  (overlap detection)
-- Local: utgovl     4 GB    6 CPUs x   2 jobs     8 GB   12 CPUs  (overlap detection)
-- Local: cor        8 GB    4 CPUs x   3 jobs    24 GB   12 CPUs  (read correction)
-- Local: ovb        4 GB    1 CPU  x   7 jobs    28 GB    7 CPUs  (overlap store bucketizer)
-- Local: ovs        8 GB    1 CPU  x   3 jobs    24 GB    3 CPUs  (overlap store sorting)
-- Local: red       10 GB    4 CPUs x   3 jobs    30 GB   12 CPUs  (read error detection)
-- Local: oea        8 GB    1 CPU  x   3 jobs    24 GB    3 CPUs  (overlap error adjustment)
-- Local: bat       16 GB    4 CPUs x   1 job     16 GB    4 CPUs  (contig construction with bogart)
-- Local: cns      --- GB    4 CPUs x --- jobs   --- GB  --- CPUs  (consensus)
-- Local: gfa       16 GB    4 CPUs x   1 job     16 GB    4 CPUs  (GFA alignment and processing)

After executing the command:
Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'meryl' concurrent execution on Thu Jul 29 19:33:42 2021 with 73.637 GB free disk space (1 processes; 3 concurrently)

    cd trimming/0-mercounts
    ./meryl-process.sh 1 > ./meryl-process.000001.out 2>&1

-- Finished on Thu Jul 29 19:33:42 2021 (like a bat out of hell) with 73.637 GB free disk space
----------------------------------------
--
-- meryl-process failed, retry.
--
-- No change in report.
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'meryl' concurrent execution on Thu Jul 29 19:33:42 2021 with 73.637 GB free disk space (1 processes; 3 concurrently)

    cd trimming/0-mercounts
    ./meryl-process.sh 1 > ./meryl-process.000001.out 2>&1

-- Finished on Thu Jul 29 19:33:42 2021 (in the blink of an eye) with 73.637 GB free disk space
----------------------------------------
--
-- meryl-process failed, tried 2 times, giving up.
--

ABORT:
ABORT: Canu 1.9
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
```
I have tried couple of times but same error is coming.

Thanks

**Comment by skoren** [comment]
First, v1.9 is quite old so I would suggest upgrading to v2.1.1. If it still fails, post the error from the last command it ran (in the above case from `trimming/0-mercounts/meryl-process.000001.out`

**Comment by ramnageena11** [comment]
Hi skoren,

thanks for suggestions.
could you help me how to upgrade? do i need to reinstall?
Thanks

**Comment by skoren** [comment]
Yes, you need to install a new version. Follow the instructions on the release page: https://github.com/marbl/canu/releasesto download and unzip the binary for your system. Make sure to give the full path to the Canu folder where you downloaded/extracted the file (e.g. if you are launching it in the folder where you downloaded/extracted the you'd run `./canu-2.1.1/bin/canu`).

**Comment by ramnageena11** [comment]
Thanks Skoren.
Appreciated.

rgds
RNS

**Comment by ramnageena11** [comment]
is these commands:
tar -xJf canu-2.1.1.tar.xz
cd canu-2.1.1/src
make -j 8
cd ..

**Comment by ramnageena11** [comment]
When I run the script as you suggested:
inghram@CH-CB-RS-T15GL:~/Downloads$ ./canu-2.1.1/bin/canu
bash: ./canu-2.1.1/bin/canu: No such file or directory
singhram@CH-CB-RS-T15GL:~/Downloads$

**Comment by skoren** [comment]
My command only applied if you were in the same folder where you downloaded/extracted the Canu binaries. I am guessing you're on an OS X machine. In that case the commands are:
```
curl -L https://github.com/marbl/canu/releases/download/v2.1/canu-2.1.Darwin-amd64.tar.xz --output canu-2.1.Darwin-amd64.tar.xz 
tar -xJf canu-2.1.*.tar.xz
./canu-2.1/bin/canu
```

**Comment by ramnageena11** [comment]
it worked and installed. i'm using ubuntu 21.
Thanks for helping.

rgds
RNS

**Comment by ramnageena11** [comment]
Still it is using old version
singhram@CH-CB-RS-T15GL:~$ canu -version 2.1.1 -d /home/singhram/Documents/g20_assembly -p DA_G20_assembly6 -genomesize=4m -nanopore-corrected /home/singhram/Documents/g20_assembly/Raw_files/Rreads.zip
Canu 1.9
singhram@CH-CB-RS-T15GL:~$

**Comment by skoren** [comment]
As I said, you have to give the full path to the download, like in my example above, not just `canu`. That will run whatever is in your path which is likely the old version.

**Comment by ramnageena11** [comment]
okay

**Comment by ramnageena11** [comment]
Pls look into
BEGIN TRIMMING
--
----------------------------------------
-- Starting command on Fri Jul 30 18:13:16 2021 with 72.789 GB free disk space

    cd .
    ./DA_G20_assembly10.seqStore.sh \
    > ./DA_G20_assembly10.seqStore.err 2>&1

-- Finished on Fri Jul 30 18:13:16 2021 (in the blink of an eye) with 72.789 GB free disk space
----------------------------------------

ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:

ABORT:
ABORT: canu 2.1.1
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   sqStoreCreate failed; boom!.
ABORT:
ABORT: Disk space available:  72.789 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (./DA_G20_assembly10.seqStore.err):

**Comment by ramnageena11** [comment]
It failed many times

**Comment by skoren** [comment]
Did you clean up any previous runs? Make sure the full folder (`/home/singhram/Documents/g20_assembly`) is removed. What happens if you run the binary by hand (`./canu-2.1.1/bin/sqStoreDumpFASTQ`). Also, given this is raw Nanopore data, you should use `-nanopore` not `-nanopore-corrected`.

**Comment by brianwalenz** [comment]
I think you might have the MacOS ("Darwin") package installed, instead of the Linux one.  There was some confusion as to which OS you are using.  Download the Linux one from https://github.com/marbl/canu/releases.

**Comment by ramnageena11** [comment]
okay thanks

**Comment by ramnageena11** [comment]
Hi
again same error rc256
Found perl:
   /usr/bin/perl
   This is perl 5, version 30, subversion 0 (v5.30.0) built for x86_64-linux-gnu-thread-multi

Found java:
   /usr/bin/java
   openjdk version "11.0.11" 2021-04-20

Found canu:
   /home/singhram/canu-2.1.1/build/bin/canu
   canu 2.1.1


Creating library 'Rreads.zip' for Nanopore raw reads.

               reads               bases
---------- --------- ------ ------------ ------
Loaded             0   0.0%            0   0.0%  /home/singhram/Documents/g20_assembly/Raw_files/Rreads.zip


All reads processed.

               reads               bases
---------- --------- ------ ------------ ------
Loaded             0   0.0%            0   0.0%

sqStoreCreate: stores/sqStoreConstructor.C:73: void sqStore::sqStore_loadMetadata(): Assertion `sqRead_defaultVersion != sqRead_unset' failed.

Failed with 'Aborted'; backtrace (libbacktrace):
utility/src/utility/system-stackTrace.C::83 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
stores/sqStoreConstructor.C::73 in _ZN7sqStore20sqStore_loadMetadataEv()
stores/sqStoreConstructor.C::171 in _ZN7sqStoreC2EPKc12sqStore_mode()
stores/sqStoreCreate.C::398 in _Z16deleteShortReadsPKcmdd()
stores/sqStoreCreate.C::664 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
Aborted (core dumped)

here it is saying no reads while when executed on canu v1.9 there were 6626 reads.

**Comment by skoren** [comment]
I didn't notice you're providing a Rreads.zip as input. Zip files are not supported, the input has to be either fasta or fastq (they can be gzipped/bzipped).

**Comment by ramnageena11** [comment]
Hi
i did with single file but it failed
cd trimming
    /home/singhram/canu-2.1.1/build/bin/ovStoreConfig \
     -S ../DA_G20_assembly11.seqStore \
     -M 4-8 \
     -L ./1-overlapper/ovljob.files \
     -create ./DA_G20_assembly11.ovlStore.config \
     > ./DA_G20_assembly11.ovlStore.config.txt \
    2> ./DA_G20_assembly11.ovlStore.config.err

-- Finished on Mon Aug  2 16:15:21 2021 (fast as lightning) with 72.701 GB free disk space
----------------------------------------

ERROR:
ERROR:  Failed with exit code 139.  (rc=35584)
ERROR:

ABORT:
ABORT: canu 2.1.1
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to configure the overlap store.
ABORT:
ABORT: Disk space available:  72.701 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (trimming/DA_G20_assembly11.ovlStore.config.err):
ABORT:
ABORT:   
ABORT:   Finding number of overlaps per read and per file.
ABORT:   
ABORT:      Moverlaps
ABORT:   ------------ ----------------------------------------
ABORT:   
ABORT:   Failed with 'Segmentation fault'; backtrace (libbacktrace):
ABORT:   utility/src/utility/system-stackTrace.C::83 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
ABORT:   (null)::0 in (null)()
ABORT:   stores/ovStoreConfig.C::64 in _ZN13ovStoreConfig19assignReadsToSlicesEP7sqStoremm()
ABORT:   stores/ovStoreConfig.C::433 in main()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   Segmentation fault (core dumped)

How could i use multiple .fastq files for assembly? I have 11 files.

Thanks'

**Comment by ramnageena11** [comment]
can canu be executed from the folder where files are?

**Comment by ramnageena11** [comment]
Segmentation Fault???

Failed with 'Segmentation fault'; backtrace (libbacktrace):
ABORT:   utility/src/utility/system-stackTrace.C::83 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
ABORT:   (null)::0 in (null)()
ABORT:   stores/ovStoreConfig.C::65 in _ZN13ovStoreConfig19assignReadsToSlicesEP7sqStoremm()
ABORT:   stores/ovStoreConfig.C::433 in main()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   Segmentation fault (core dumped)
This time i have included all files with 117 x coverage.

**Comment by skoren** [comment]
I still suspect your input files are causing an issue. The failing step just divides reads into partitions and we've never seen it fail before. Make sure you are removing any intermediate outputs between retries (e.g. the full folder you provide to -d). Post the full output of the Canu run and your command, make sure you're also using -nanopore-raw for Nanopore reads not -nanopore-corrected.

**Comment by ramnageena11** [comment]
This is the assembly report:
[CORRECTION/READS]
--
-- In sequence store './DA_G20_assembly18.seqStore':
--   Found 31147 reads.
--   Found 380701249 bases (95.17 times coverage).
--    
--    G=380701249                        sum of  ||               length     num
--    NG         length     index       lengths  ||                range    seqs
--    ----- ------------ --------- ------------  ||  ------------------- -------
--    00010        38768       795     38085222  ||       1000-2923         4291|---------------------------------------------------------------
--    00020        30789      1908     76147897  ||       2924-4847         4025|------------------------------------------------------------
--    00030        25790      3262    114233094  ||       4848-6771         3404|--------------------------------------------------
--    00040        21726      4872    152293035  ||       6772-8695         3021|---------------------------------------------
--    00050        18233      6786    190361641  ||       8696-10619        2596|---------------------------------------
--    00060        15223      9073    228424565  ||      10620-12543        2235|---------------------------------
--    00070        12270     11850    266498661  ||      12544-14467        1830|---------------------------
--    00080         9380     15381    304561487  ||      14468-16391        1632|------------------------
--    00090         6259     20272    342631485  ||      16392-18315        1372|---------------------
--    00100         1000     31146    380701249  ||      18316-20239        1105|-----------------
--    001.000x               31147    380701249  ||      20240-22163         986|---------------
--                                               ||      22164-24087         781|------------
--                                               ||      24088-26011         674|----------
--                                               ||      26012-27935         588|---------
--                                               ||      27936-29859         475|-------
--                                               ||      29860-31783         412|-------
--                                               ||      31784-33707         338|-----
--                                               ||      33708-35631         262|----
--                                               ||      35632-37555         218|----
--                                               ||      37556-39479         169|---
--                                               ||      39480-41403         125|--
--                                               ||      41404-43327         118|--
--                                               ||      43328-45251         105|--
--                                               ||      45252-47175          79|--
--                                               ||      47176-49099          68|-
--                                               ||      49100-51023          52|-
--                                               ||      51024-52947          36|-
--                                               ||      52948-54871          28|-
--                                               ||      54872-56795          24|-
--                                               ||      56796-58719          15|-
--                                               ||      58720-60643          12|-
--                                               ||      60644-62567           7|-
--                                               ||      62568-64491           6|-
--                                               ||      64492-66415           7|-
--                                               ||      66416-68339           9|-
--                                               ||      68340-70263           6|-
--                                               ||      70264-72187           6|-
--                                               ||      72188-74111           3|-
--                                               ||      74112-76035           8|-
--                                               ||      76036-77959           3|-
--                                               ||      77960-79883           4|-
--                                               ||      79884-81807           4|-
--                                               ||      81808-83731           2|-
--                                               ||      83732-85655           0|
--                                               ||      85656-87579           1|-
--                                               ||      87580-89503           0|
--                                               ||      89504-91427           2|-
--                                               ||      91428-93351           0|
--                                               ||      93352-95275           1|-
--                                               ||      95276-97199           2|-
--

[CORRECTION/MERS]
--
--  16-mers                                                                                           Fraction
--    Occurrences   NumMers                                                                         Unique Total
--       1-     1         0                                                                        0.0000 0.0000
--       2-     2  13320346 ********************************************************************** 0.5036 0.0914
--       3-     4   6305670 *********************************                                      0.6674 0.1360
--       5-     7   2102168 ***********                                                            0.7823 0.1814
--       8-    11    703462 ***                                                                    0.8318 0.2116
--      12-    16    267719 *                                                                      0.8511 0.2294
--      17-    22    125553                                                                        0.8593 0.2402
--      23-    29     94696                                                                        0.8635 0.2479
--      30-    37    162153                                                                        0.8671 0.2568
--      38-    46    391413 **                                                                     0.8738 0.2780
--      47-    56    849307 ****                                                                   0.8899 0.3416
--      57-    67   1169878 ******                                                                 0.9237 0.5036
--      68-    79    716992 ***                                                                    0.9672 0.7521
--      80-    92    151815                                                                        0.9920 0.9165
--      93-   106     17300                                                                        0.9968 0.9536
--     107-   121     16999                                                                        0.9974 0.9590
--     122-   137     20846                                                                        0.9980 0.9658
--     138-   154     13777                                                                        0.9988 0.9751
--     155-   172      5152                                                                        0.9993 0.9817
--     173-   191      1862                                                                        0.9995 0.9844
--     192-   211      1723                                                                        0.9996 0.9855
--     212-   232      1297                                                                        0.9996 0.9867
--     233-   254      1271                                                                        0.9997 0.9877
--     255-   277      1506                                                                        0.9997 0.9887
--     278-   301      1130                                                                        0.9998 0.9901
--     302-   326       524                                                                        0.9998 0.9912
--     327-   352       306                                                                        0.9998 0.9917
--     353-   379       210                                                                        0.9999 0.9921
--     380-   407       164                                                                        0.9999 0.9924
--     408-   436       168                                                                        0.9999 0.9926
--     437-   466       178                                                                        0.9999 0.9928
--     467-   497       243                                                                        0.9999 0.9931
--     498-   529       291                                                                        0.9999 0.9935
--     530-   562       412                                                                        0.9999 0.9940
--     563-   596       402                                                                        0.9999 0.9948
--     597-   631       464                                                                        0.9999 0.9956
--     632-   667       511                                                                        1.0000 0.9966
--     668-   704       319                                                                        1.0000 0.9977
--     705-   742       189                                                                        1.0000 0.9985
--     743-   781        94                                                                        1.0000 0.9989
--     782-   821        38                                                                        1.0000 0.9992
--
--           0 (max occurrences)
--   291441733 (total mers, non-unique)
--    26448664 (distinct mers, non-unique)
--           0 (unique mers)

[CORRECTION/LAYOUT]
--                             original      original
--                            raw reads     raw reads
--   category                w/overlaps  w/o/overlaps
--   -------------------- ------------- -------------
--   Number of Reads              26597          4550
--   Number of Bases          366986202      13065138
--   Coverage                    91.747         3.266
--   Median                       10963          2230
--   Mean                         13798          2871
--   N50                          18813          3423
--   Minimum                       1000             0
--   Maximum                      97163         46330
--   
--                                        --------corrected---------  ----------rescued----------
--                             evidence                     expected                     expected
--   category                     reads            raw     corrected            raw     corrected
--   -------------------- -------------  ------------- -------------  ------------- -------------
--   Number of Reads              30998           5661          5661              0             0
--   Number of Bases          379632385      166029401     160004579              0             0
--   Coverage                    94.908         41.507        40.001          0.000         0.000
--   Median                        9277          26676         26037              0             0
--   Mean                         12246          29328         28264              0             0
--   N50                          18241          29405         28203              0             0
--   Minimum                       1000          19265         19258              0             0
--   Maximum                      97163          97163         94491              0             0
--   
--                        --------uncorrected--------
--                                           expected
--   category                       raw     corrected
--   -------------------- ------------- -------------
--   Number of Reads              25486         25486
--   Number of Bases          214021939     140049805
--   Coverage                    53.505        35.012
--   Median                        7391          2440
--   Mean                          8397          5495
--   N50                          11736         13410
--   Minimum                          0             0
--   Maximum                      95846         95833
--   
--   Maximum Memory          1469879324

[TRIMMING/READS]
--
-- In sequence store './DA_G20_assembly18.seqStore':
--   Found 5661 reads.
--   Found 161485475 bases (40.37 times coverage).
--    
--    G=161485475                        sum of  ||               length     num
--    NG         length     index       lengths  ||                range    seqs
--    ----- ------------ --------- ------------  ||  ------------------- -------
--    00010        44349       312     16155151  ||      11176-12869           2|-
--    00020        37779       709     32325209  ||      12870-14563           2|-
--    00030        33777      1161     48458206  ||      14564-16257           5|-
--    00040        30879      1662     64617515  ||      16258-17951           3|-
--    00050        28442      2207     80769076  ||      17952-19645         129|----------
--    00060        26365      2796     96896279  ||      19646-21339         837|---------------------------------------------------------------
--    00070        24505      3432    113053080  ||      21340-23033         701|-----------------------------------------------------
--    00080        22648      4117    129196948  ||      23034-24727         631|------------------------------------------------
--    00090        21003      4858    145353283  ||      24728-26421         572|--------------------------------------------
--    00100        11176      5660    161485475  ||      26422-28115         484|-------------------------------------
--    001.000x                5661    161485475  ||      28116-29809         394|------------------------------
--                                               ||      29810-31503         372|----------------------------
--                                               ||      31504-33197         282|----------------------
--                                               ||      33198-34891         223|-----------------
--                                               ||      34892-36585         186|--------------
--                                               ||      36586-38279         163|-------------
--                                               ||      38280-39973         131|----------
--                                               ||      39974-41667          96|--------
--                                               ||      41668-43361          93|-------
--                                               ||      43362-45055          68|------
--                                               ||      45056-46749          62|-----
--                                               ||      46750-48443          52|----
--                                               ||      48444-50137          37|---
--                                               ||      50138-51831          34|---
--                                               ||      51832-53525          26|--
--                                               ||      53526-55219          21|--
--                                               ||      55220-56913          11|-
--                                               ||      56914-58607          10|-
--                                               ||      58608-60301           6|-
--                                               ||      60302-61995           7|-
--                                               ||      61996-63689           0|
--                                               ||      63690-65383           1|-
--                                               ||      65384-67077           1|-
--                                               ||      67078-68771           3|-
--                                               ||      68772-70465           0|
--                                               ||      70466-72159           2|-
--                                               ||      72160-73853           1|-
--                                               ||      73854-75547           1|-
--                                               ||      75548-77241           2|-
--                                               ||      77242-78935           1|-
--                                               ||      78936-80629           2|-
--                                               ||      80630-82323           3|-
--                                               ||      82324-84017           0|
--                                               ||      84018-85711           1|-
--                                               ||      85712-87405           0|
--                                               ||      87406-89099           1|-
--                                               ||      89100-90793           0|
--                                               ||      90794-92487           0|
--                                               ||      92488-94181           1|-
--                                               ||      94182-95875           1|-
--

**Comment by ramnageena11** [comment]
Does it show no corrected reads??

**Comment by ramnageena11** [comment]
The error file .err


Found perl:
   /usr/bin/perl
   This is perl 5, version 30, subversion 0 (v5.30.0) built for x86_64-linux-gnu-thread-multi

Found java:
   /usr/bin/java
   openjdk version "11.0.11" 2021-04-20

Found canu:
   /home/singhram/canu-2.1.1/build/bin/canu
   canu 2.1.1


Creating library 'fastq_runid_f44fa89f467efbddefc70ddbe6b9461f37b2d053_0' for Nanopore raw reads.

               reads               bases
---------- --------- ------ ------------ ------
Loaded          3758  94.0%     45955900  99.7%  /home/singhram/canu-2.1.1/build/bin/fastq_runid_f44fa89f467efbddefc70ddbe6b9461f37b2d053_0.fastq
Short            242   6.0%       147457   0.3%


Creating library 'fastq_runid_f44fa89f467efbddefc70ddbe6b9461f37b2d053_1' for Nanopore raw reads.

               reads               bases
---------- --------- ------ ------------ ------
Loaded          3754  93.8%     45240967  99.7%  /home/singhram/canu-2.1.1/build/bin/fastq_runid_f44fa89f467efbddefc70ddbe6b9461f37b2d053_1.fastq
Short            246   6.2%       146868   0.3%


Creating library 'fastq_runid_f44fa89f467efbddefc70ddbe6b9461f37b2d053_2' for Nanopore raw reads.

               reads               bases
---------- --------- ------ ------------ ------
Loaded          3717  92.9%     46677684  99.6%  /home/singhram/canu-2.1.1/build/bin/fastq_runid_f44fa89f467efbddefc70ddbe6b9461f37b2d053_2.fastq
Short            283   7.1%       163980   0.4%


Creating library 'fastq_runid_f44fa89f467efbddefc70ddbe6b9461f37b2d053_4' for Nanopore raw reads.

               reads               bases
---------- --------- ------ ------------ ------
Loaded          3766  94.2%     47080033  99.7%  /home/singhram/canu-2.1.1/build/bin/fastq_runid_f44fa89f467efbddefc70ddbe6b9461f37b2d053_4.fastq
Short            234   5.8%       133071   0.3%


Creating library 'fastq_runid_f44fa89f467efbddefc70ddbe6b9461f37b2d053_5' for Nanopore raw reads.

               reads               bases
---------- --------- ------ ------------ ------
Loaded          3753  93.8%     44202993  99.7%  /home/singhram/canu-2.1.1/build/bin/fastq_runid_f44fa89f467efbddefc70ddbe6b9461f37b2d053_5.fastq
Short            247   6.2%       145649   0.3%


Creating library 'fastq_runid_f44fa89f467efbddefc70ddbe6b9461f37b2d053_6' for Nanopore raw reads.

               reads               bases
---------- --------- ------ ------------ ------
Loaded          3738  93.5%     46224818  99.7%  /home/singhram/canu-2.1.1/build/bin/fastq_runid_f44fa89f467efbddefc70ddbe6b9461f37b2d053_6.fastq
Short            262   6.5%       151559   0.3%


Creating library 'fastq_runid_f44fa89f467efbddefc70ddbe6b9461f37b2d053_3' for Nanopore raw reads.

               reads               bases
---------- --------- ------ ------------ ------
Loaded          3763  94.1%     45049064  99.7%  /home/singhram/canu-2.1.1/build/bin/fastq_runid_f44fa89f467efbddefc70ddbe6b9461f37b2d053_3.fastq
Short            237   5.9%       139367   0.3%


Creating library 'fastq_runid_f44fa89f467efbddefc70ddbe6b9461f37b2d053_7' for Nanopore raw reads.

               reads               bases
---------- --------- ------ ------------ ------
Loaded            85  96.6%      1017099  99.8%  /home/singhram/canu-2.1.1/build/bin/fastq_runid_f44fa89f467efbddefc70ddbe6b9461f37b2d053_7.fastq
Short              3   3.4%         2455   0.2%


Creating library 'FAP06472_pass_barcode04_f44fa89f_0' for Nanopore raw reads.

               reads               bases
---------- --------- ------ ------------ ------
Loaded          3814  95.3%     46882560  99.7%  /home/singhram/canu-2.1.1/build/bin/FAP06472_pass_barcode04_f44fa89f_0.fastq
Short            186   4.7%       118583   0.3%


Creating library 'FAP06472_pass_barcode04_f44fa89f_1' for Nanopore raw reads.

               reads               bases
---------- --------- ------ ------------ ------
Loaded           999  96.8%     12370131  99.8%  /home/singhram/canu-2.1.1/build/bin/FAP06472_pass_barcode04_f44fa89f_1.fastq
Short             33   3.2%        19533   0.2%


All reads processed.

               reads               bases
---------- --------- ------ ------------ ------
Loaded         31147  94.0%    380701249  99.7%
Short           1973   6.0%      1168522   0.3%


Bye.

**Comment by skoren** [comment]
All those logs look OK. Is this a new run? It doesn't look like it's gotten to the step that failed previously from the report.

**Comment by ramnageena11** [comment]
this is a new run
ERROR:
ERROR:  Failed with exit code 139.  (rc=35584)
ERROR:

ABORT:
ABORT: canu 2.1.1
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to configure the overlap store.
ABORT:
ABORT: Disk space available:  70.241 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (trimming/DA_G20_assembly18.ovlStore.config.err):
ABORT:
ABORT:   
ABORT:   Finding number of overlaps per read and per file.
ABORT:   
ABORT:      Moverlaps
ABORT:   ------------ ----------------------------------------
ABORT:   
ABORT:   Failed with 'Segmentation fault'; backtrace (libbacktrace):
ABORT:   utility/src/utility/system-stackTrace.C::83 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
ABORT:   (null)::0 in (null)()
ABORT:   stores/ovStoreConfig.C::64 in _ZN13ovStoreConfig19assignReadsToSlicesEP7sqStoremm()
ABORT:   stores/ovStoreConfig.C::433 in main()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   Segmentation fault (core dumped)

**Comment by skoren** [comment]
Strange, there should be more report/logging before it gets to that step (the equivalent of CORRECTION/MERS is missing). What is the contents of the trimming folder and it's subfolders (you could just run `find .  -exec ls -lh {} \;` in trimming).

**Comment by ramnageena11** [comment]
Dont find this file

I have .seqsSore.err, .seqStore.sh, assembly.report, ovlStore.config.txt, ovlStore.config.err,

**Comment by ramnageena11** [comment]
trimming folder has only two files: ovlStore.config.txt and ovlStore.config.err

**Comment by skoren** [comment]
That is definitely very strange, I don't see any way in the code where it would try to create a trimming store (the failing step) when nothing has run in trimming. Are you sure the previous run was completely removed before you started a new run? 

Start a completely new run (use a new -p and -d option you have never tried before) and post your fully Canu command and the full output of everything Canu writes to screen (that's what I meant by stderr/stdout) from start to crash.

**Comment by ramnageena11** [comment]
okay, i will.

Thanks

**Comment by ramnageena11** [comment]
its working now. Thanks for support and suggestions.
rgds
Ram
