### ISSUE TITLE
Error Message: No grid engine detected, grid disabled | Task obtovl can't run on any available machines.

### ISSUE THREAD

**Issue by Jawen-D** [marbl/canu#1995]
This is my first attempt to do De Novo Assembly of Nanopore reads from a parasite sample. I managed to install CANU in the virtualbox installed UBUNTU. 
After running this command:
canu -p TtAssembly -d Assembly genomeSize=15m -nanopore-raw raw1.fastq

![image](https://user-images.githubusercontent.com/86952822/128136864-80d5439a-caf3-4641-a0e0-ac0f2934dc59.png)

I got this error message:
No grid engine detected, grid disabled
Task obtovl can't run on any available machines.
No available machine configuration can run this task.
![image](https://user-images.githubusercontent.com/86952822/128136982-1400d044-7e8b-4a09-9a81-73b808bf0bc4.png)

It also mentioned a possible solution: Change obtovlMemory and/or obtovlThreads
But I dont know what do with it.

May I ask if anyone encountered this issue before and can you suggest some steps to resolve this issue.
Thank you in advance.

**Comment by skoren** [comment]
See #1235. It looks like Canu detected your machine as having only 1 CPU, is that accurate? The issue is Canu doesn't expect to run on a single-core machine. We typically recommend at least 4 cpus and 16gb of memory to run assemblies and the more cores the better. 

If you can make your VM bigger, I'd suggest doing that. Otherwise, you can restrict Canu to use 1 thread via `obtovlThreads=1 maxThreads=1`. If it reports that No available machine configurations can run this task again, update the thread option to 1 (e.g. based on the above you add `obtovlThreads=1`).

**Comment by Jawen-D** [comment]
Thank you for addressing this. We appreciate your efforts.

**Comment by comery** [comment]
hi Sergey, 

I got the same problem with CPU issues. I can specify the compute node to run a job with 128 CPU and 3T memory available, but Canu can only detect "class0 - 1 machines with 1 cores with 3022 GB memory each.". so I am curious how canu detect CPU number, and how to solve this problem?

**Comment by brianwalenz** [comment]
It checks environment variables NSLOTS, PBS_NUM_PPN, PBS_NCPUS, SLURM_JOB_CPUS_PER_NODE, OMP_NUM_THREADS and uses the _first_ one that has a value set.  If none have a value, it calls `getconf _NPROCESSORS_ONLN`.

**Comment by comery** [comment]
Hi Sergey,

for your information, I use this command to check node info:

lscpu | grep -E '^Thread|^Core|^Socket|^CPU\('
CPU(s):                160
Thread(s) per core:    2
Core(s) per socket:    20
Socket(s):             4

I am not sure this could be a problem when someone did not set these values, especially when set "useGrid=false". I am wondering if you use the command of "lscpu | grep" to get the hardware information would be a universal solution.

**Comment by comery** [comment]
I have solved this problem by masking several lines in https://github.com/marbl/canu/blob/master/src/pipelines/canu/Grid_Local.pm#L79-#L81

if you install a compiled version, you can modify the file of  “path_you_install/canu-2.2/lib/site_perl/canu/Grid_Local.pm”, or you can modify the source in "canu/src/pipelines/canu/Grid_Local.pm" before you compile it.

Maybe you can have a try.

**Comment by asan-emirsaleh** [comment]
Hello!
In 2026, I faced exactly the same error when tryed to launch Canu via Snakemake rule with `useGrid=false` defined. Setting local variable might fix the issue. Trying to do...

Update: it really did fix the job.
