### ISSUE TITLE
PBS grib job error

### ISSUE THREAD

**Issue by wbrewer5** [marbl/canu#1996]
I am running into issues with the grid not liking being told how much memory to use. Is there a way I can fix this in my submission file? I do not have access to the source file on the compute cluster.

[pandora_1_correct.txt](https://github.com/marbl/canu/files/6941184/pandora_1_correct.txt)

[pandora_canu_1_correction_e5028483.txt](https://github.com/marbl/canu/files/6941188/pandora_canu_1_correction_e5028483.txt)

**Comment by skoren** [comment]
That looks like an error specific to your grid, I'm not sure what it means that memory is managed by the system, how does the system know how much memory I want to use? Does it mean there is a fixed memory/core allocated?

You can force Canu not to request memory via `gridEngineResourceOption="-l nodes=1:ppn=THREADS` (see #133). However, I expect if Canu then uses more memory than whatever the system assumes, it will cause errors. Once you know how much memory/core is allocated, make sure no jobs will exceed this (based on the config printed at the top):
```
-- Grid:  meryl     15.000 GB    8 CPUs  (k-mer counting)
-- Grid:  hap        7.000 GB    8 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   13.000 GB   16 CPUs  (overlap detection with mhap)
-- Grid:  obtovl     8.000 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl     8.000 GB    8 CPUs  (overlap detection)
-- Grid:  cor       16.000 GB    4 CPUs  (read correction)
-- Grid:  ovb        4.000 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       16.000 GB    1 CPU   (overlap store sorting)
-- Grid:  red        8.000 GB    4 CPUs  (read error detection)
-- Grid:  oea        8.000 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat       64.000 GB    8 CPUs  (contig construction with bogart)
-- Grid:  cns        -.--- GB    8 CPUs  (consensus)
-- Grid:  gfa       16.000 GB    8 CPUs  (GFA alignment and processing)
```
If it will increase the appropriate step's cpu request as needed.

**Comment by brianwalenz** [comment]
Some relevant links:

https://oit.utk.edu/hpsc/isaac-open/open-enclave-system-overview/
https://oit.utk.edu/hpsc/isaac-open/running-jobs/ (Table 2.1)

Pick one of 'rho' or 'beacon' for each task, then specify this in the grid options for each task (e.g., `gridOptionsMHAP="-l partition=rho,...."`, `gridOptionsOVL="..."`, `gridOptionsBAT="-l partition=beacon,nodes=1,ppn=16,..."`).

Use 'beacon' for consensus.

You'll also probably want to explicitly set memory and cpus for each step - `ovlMemory=14g ovlThreads=8`, etc.  Note that I set memory here below 8 * 2 GB just to make sure we don't exceed the 16 GB limit PBS will enforce.

**Comment by wbrewer5** [comment]
Thank you for the prompt reply. Every job requires flags that state how many nodes and cores you need for the amount of time, with memory being determined by total memory/number of requested cores. I added the first string you mentioned to my submission. 

canu -correct \
-d /lustre/haven/user/wbrewer5/pandora/assembly/canu/1_corrected_reads \
-p pandora \
genomeSize=300m \
-nanopore /lustre/haven/user/wbrewer5/pandora/assembly/fastq/*fastq.gz \
gridEngineResourceOption="-l nodes=1:ppn=24"

The job ran for 5 minutes before sending the completion status. It created 2 new jobs, one that is queued and another that is being held. Does the held job depend upon the queued job to complete?

Job ID                  Username    Queue    Jobname          SessID  NDS   TSK   Memory      Time    S   Time
----------------------- ----------- -------- ---------------- ------ ----- ------ --------- --------- - ---------
5029021.apollo-acf      wbrewer5    batch    pandora_canu_1_c 311711     1     48       --   24:00:00 C       --
5029024.apollo-acf      wbrewer5    batch    meryl_pandora       --      1     24   98304mb  01:00:00 Q       --
5029025.apollo-acf      wbrewer5    batch    canu_pandora        --      1     24   98304mb  01:00:00 H       --

**Comment by skoren** [comment]
Yes, Canu submits itself to hold for the array jobs and then continues on. This will happen several times during the run. You can monitor progress using the `canu.out` and `*.report` files.
