### ISSUE TITLE
TrioCanu with other contig assembler

### ISSUE THREAD

**Issue by mentorlg** [marbl/canu#1997]
Hi, 

I have some questions about TrioCanu output files...

1. What is the exact output files of TrioCanu..?
- Can TrioCanu assemble binned reads to contig-level for each haplotype respectively, or do I need to assemble the binned reads with other contig assemblers (Canu, Falcon, and so on) ..?

2. If TrioCanu release the assembled binned reads for each haplotype, can I use the other contig assembler before trio-binned reads are assembled in TrioCanu..?

Thank you,
Amelia

**Comment by brianwalenz** [comment]
Yes and yes.

By default, trio mode will write the binned reads into the `haplotype/` directory and then assemble each set of binned reads.

For this command:
```
canu -p test -d f1-75x-trio genomeSize=135m useGrid=true \
  -haplotypeA4  /data/reads/drosophila/A4-illumina/*fastq.gz \
  -haplotypeISO /data/reads/drosophila/ISO1-illumina/*fastq.gz \
  -pacbio       /data/reads/drosophila/F1-sequel/075x/*fasta.xz
```

The output directory will have:
```
> ls -l f1-75x-trio/
total 34
drwxr-xr-x  2 bri  bri      8 Aug  4 04:46 canu-logs
drwxr-xr-x  2 bri  bri     12 Aug  4 04:46 canu-scripts
lrwxr-xr-x  1 bri  bri     24 Aug  4 04:46 canu.out -> canu-scripts/canu.05.out
drwxr-xr-x  3 bri  bri     12 Aug  4 04:46 haplotype
drwxr-xr-x  8 bri  bri     18 Aug  4 16:48 test-haplotypeA4
-rw-r--r--  1 bri  bri  11165 Aug  4 04:47 test-haplotypeA4.out
-rwxr-xr-x  1 bri  bri    222 Aug  4 04:46 test-haplotypeA4.sh
drwxr-xr-x  8 bri  bri     18 Aug  4 21:14 test-haplotypeISO
-rw-r--r--  1 bri  bri  11100 Aug  4 04:49 test-haplotypeISO.out
-rwxr-xr-x  1 bri  bri    226 Aug  4 04:46 test-haplotypeISO.sh
-rw-r--r--  1 bri  bri      0 Aug  4 04:06 test.report
```

`test-haplotypeISO` and `test-haplotypeA4` are 'normal' canu output directories of each binned-read assembly.  The commands to run these are saved in the respective `.sh` file.

The `haplotype` directory has the binned reads.  The 'unknown' reads were not binned and are used in both assemblies.

```
> ls -l f1-75x-trio/haplotype/
total 3243415
drwxr-xr-x  6 bri  bri          35 Aug  4 04:14 0-kmers
-rw-r--r--  1 bri  bri  1431558384 Aug  4 04:46 haplotype-A4.fasta.gz
-rw-r--r--  1 bri  bri  1883877101 Aug  4 04:46 haplotype-ISO.fasta.gz
-rw-r--r--  1 bri  bri     3467561 Aug  4 04:46 haplotype-unknown.fasta.gz
-rw-r--r--  1 bri  bri       18747 Aug  4 04:46 haplotype.log
-rw-r--r--  1 bri  bri           0 Aug  4 04:46 haplotyping.success
-rw-r--r--  1 bri  bri        1917 Aug  4 04:46 splitHaplotype.1.out
-rw-r--r--  1 bri  bri          60 Aug  4 04:14 splitHaplotype.jobSubmit-01.out
-rwxr-xr-x  1 bri  bri         193 Aug  4 04:14 splitHaplotype.jobSubmit-01.sh
-rwxr-xr-x  1 bri  bri        8810 Aug  4 04:14 splitHaplotype.sh
```

**Comment by mentorlg** [comment]
Thank you for your fast reply..!

then... you mean,
Can I get automatically "assembled contigs for each haplotype" at once when I run TrioCanu..?
or, do I need to run Canu additionally?

and... TrioCanu can also output the binned reads data, so I can assemble them with other contig assemblers such as Falcon... is it right..?

**Comment by brianwalenz** [comment]
Yup.  Trio mode will do both the read binning and launch the two assemblies, automatically.  After it writes the binned read fasta files it will launch Canu on each of those files.

**Comment by mentorlg** [comment]
I really appreciate your answer..!! It is very helpful to understand the TrioCanu.
Thank you :)
