### ISSUE TITLE
The result is not exactly!

### ISSUE THREAD

**Issue by ld9866** [marbl/canu#1998]
Hello, I measured the mammalian diploid genomes of 5 cells and finally obtained 5 BAM files.
I used the samtools fasta -@ 5 ${I} > ${I}. fasta command for batch format conversion.
Then I used the cat command to merge multiple FASTA files.
canu -assemble -p test -d test_hifi genomeSize=2500m maxThreads=50 -pacbio-hifi test.fasta useGrid=false
However, when I use the above command to merge, the final size of the conting genome is 4 g. what is the reason for this problem? Because there was a reference genome size before, I'm sure it's about 2.5G.
Thank you!

**Comment by skoren** [comment]
See https://canu.readthedocs.io/en/latest/faq.html#my-genome-size-and-assembly-size-are-different-help. Most likely with HiFI data you have most of the genome haplotypes separated out so you're getting the diploid genome not a collapsed version. You can run BUSCO to confirm and purge_dups to remove the duplication.

**Comment by ld9866** [comment]
Thank you!
l will try it and glad to receive your reply.

**Comment by ld9866** [comment]
Hello!
l have used busco to confirm that the result showed:
        --------------------------------------------------
        |Results from dataset vertebrata_odb10            |
        --------------------------------------------------
        |C:98.0%[S:42.2%,D:55.8%],F:1.0%,M:1.0%,n:3354    |
        |3287   Complete BUSCOs (C)                       |
        |1414   Complete and single-copy BUSCOs (S)       |
        |1873   Complete and duplicated BUSCOs (D)        |
        |34     Fragmented BUSCOs (F)                     |
        |33     Missing BUSCOs (M)                        |
        |3354   Total BUSCO groups searched               |
        --------------------------------------------------

The l want to use purge_dups to remove the duplication, but l find it has some problem using this software and there has been a long time nobody answers the question. Hence, I have to disturb you again.
When l did this step it showed that:
calcuts PB.stat > cutoffs 2>calcults.log
[M::calcuts] Find 0 peaks
How can l solve this problem  and is there any to do the same step like purge_dups?
Thank you!
