### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by ebioman** [marbl/canu#2]
Hello I was eager to try this fork
Unfortunately the dependencies are less clear. For the java version the message was pretty clear, but now I seem to lack a falcon program.
I have currently the Falcon assembler from Jason here but it seems not to be sufficient. What is this
dependency exactly?
Thanks

**Comment by brianwalenz** [comment]
If you're on 64-bit linux, one is included in the repo, but I see the code
to find it is hardcoded to our development environment, and that the
Makefile doesn't actually install the binary.

Try setting:

falconSense={path}/canu/src/falcon_sense/falcon_sense.Linux-amd64.bin

**Comment by ebioman** [comment]
Hi
It did not do the trick, I still get 

    canu failed with 'didn't find falcon program with option falconSense='''.

The variable seems to be set correctly:

     $falconSense -h
    usage: falcon_sense.Linux-amd64.bin [-h] [--n_core N_CORE]
                                    [--local_match_count_window LOCAL_MATCH_COUNT_WINDOW]
                                    [--local_match_count_threshold LOCAL_MATCH_COUNT_THRESHOLD]
                                    [--min_cov MIN_COV]
                                    [--max_n_read MAX_N_READ] [--trim]
                                    [--output_full] [--output_multi]
.....

Could you tell me where to find the according section in the makefile ? I couldn't track it down.
Thanks

**Comment by skoren** [comment]
Can you try passing the falconSense= argument when you run canu (i.e. canu ... falconSense=) instead of setting it as an environment variable.

**Comment by ebioman** [comment]
Thanks skoren, that worked!

**Comment by brianwalenz** [comment]
falconSense should be installed and used now.  Fixed in 1008c61e8069c4f4f39bc1609b5f81a39cdfc99a.

**Comment by duspriya** [comment]
I install canu-1.7 ubuntu 16.04. I check ./canu to found the error commant cant not found swap-swm package univers
