### ISSUE TITLE
Multialignment files of Unitigs

### ISSUE THREAD

**Issue by saanasum** [marbl/canu#200]
Dear Canu developers,

many thanks for providing this assembler. The assembler works and unitigs were generated. 

To have a closer look at the unitigs and the aligned PacBio reads at the unitig I was wondering where to find these files? Are these files already present somewhere or do I need to generate these file afterwards using e.g. the utgcns command? I am not sure how to proceed. Do I need to run this command as described here: [http://canu.readthedocs.io/en/stable/commands/utgcns.html]? 

Thank you for your help
Falk

**Comment by skoren** [comment]
Hi,

There is no multi-alignment generated for consensus. All the reads are aligned to a template and added to a DAG which generates the final contig consensus. This is what utgcns does by default. You can get the read positions in each unitig from the asm.layout file in your assembly directory, albeit the positions will be slightly off since the consensus can insert/delete bases moving the read positions.

**Comment by saanasum** [comment]
Thanks for your quick reply. I think that I can use this information to get the reads out of the raw data (which I used as input in Canu) to realign them (e.g. https://github.com/HIT-Bioinformatics/rHAT) against the unitig. 

Why I am doing this?

I would like to check if repetitive regions (e.g. satellite DNAs) are covered equally by many reads and if unique regions in between these repeat blocks are covered by fewer reads to be sure that a repetitive genome region has been correctly assembled and to avoid that a large unitig is generated only due to overlapping repetitive regions. I am not sure if that works. 

What does DAG means?

**Comment by brianwalenz** [comment]
DAG - directed acyclic graph.  It the data structure used in this form of consensus.

Your experiment will be a good sanity check on our result, but no where near easy to do.  You will detect regions where the assembler decided alternate paths through the repeat had weak evidence - that the reconstruction of the repeat was sufficiently unique compared to any other path through the repeat.
