### ISSUE TITLE
canu support MPI ?

### ISSUE THREAD

**Issue by 123123456abc** [marbl/canu#2010]
hello！
I want to ask canu support MPI？

Thank you.

**Comment by brianwalenz** [comment]
No.  Canu does not use MPI.

**Comment by 123123456abc** [comment]
That means that canu can only run the same program with a single node and not multiple nodes, right?

**Comment by skoren** [comment]
No it doesn't. MPI is only required for inter-node communication which Canu doesn't need. For the largest compute steps, it runs array jobs which run across multiple nodes (each using multiple threads) on subsets of the data and so don't need to communicate. Steps that can't easily partition the data do run on a single node. All this is automatically handled by Canu when it submits jobs to your grid.
