### ISSUE TITLE
Very heavy trimming using Nanopore reads

### ISSUE THREAD

**Issue by mvolar** [marbl/canu#2012]
Hello everyone,

I was performing the assembly based on 30 GB of N50 approximately 25kB reads, putting the "readLength=30000" since I expected a lot of coverage and my genome is pretty small (and repetitive). However once trimming finished the coverage fell to about 30X pass the filter meaning approx 45x coverage of the reads got shortened and fell through the filter.

In the beggining we also had many reads >100kb in size with a couple of reads >300kb in size, but after trimming our largest read was only 125k in size and the rest of them were in the range 30kb-95kb and we feel like there is a lot of useful information (for us, at least since we are studying organization of repetitive elements) being lost.

My question is are there any parameters to tweak (I went through the documentation but non directly impact the "force of the trimm", but rather many other parameters which I am perhaps reluctant to change) in order to get longer contigs, since the pure per-base accuracy is not very important to us, and we can also perform polishing if necessary.

Thanks for the help,
M

**Comment by mvolar** [comment]
Very sorry the command was run as following (almost the defalut, with a couple of tweaks, and on an SGE cluster)

`canu-2.1.1/bin/canu -p out1 -d out1 genomeSize=200m minReadLength=35000 corMaxEvidenceErate=0.15 ovlMerThreshold=500 -nanopore reads.fasta gridEngineResourceOption="-pe a16-mpisingle THREADS -l mem=MEMORY"`

since the genome is heavily repetitive and without the "ovlMerTHreshold" it takes weeks to run. 

As for the reads, the trimmed reads (ones that go into the assembly process itself) do indeed get mapped, however the corrected and raw reads don't go anywhere near (the longest read itself , 400kb, gets divided into 300 parts when using minimap2, no matter the k-mer length or other options). 

As I understand there is little to no point into trying to change the parameters, since given our result, the program had its reasons to do what it did to our longest reads, so changing the parameters can only present an unrealistic picture and force errors.

Thank you for the prompt response.

**Comment by skoren** [comment]
The error rate limit (`corMaxEvidenceErate=0.15`) is a bit lower than the default of 0.3 or 30%. On recent guppy R9.4.1 runs of human, most overlaps are below 15%. It will depend on your Nanopore quality, you may be losing some valid but higher error overlaps at 15% so you could try removing that option.

**Comment by mvolar** [comment]
I have started the run without the parameter, however I have selected that parameter based on the notes from the [documentation](https://canu.readthedocs.io/en/latest/faq.html#my-genome-is-at-or-gc-rich-do-i-need-to-adjust-parameters-what-about-highly-repetitive-genomes) for highly repetitive AT rich genomes, since our genome id very repetitive (30% main satellite based on per-read data and GC% is around 34%), do You have any insight on how will that effect the performance/quality? All our Nanopore reads are of the 10.3.1. chemistry and basecalled with guppy 5.0.x.

**Comment by skoren** [comment]
I think you should be OK w/o the option but you may also want to try the uncorrected ONT assembly (see quick start: https://canu.readthedocs.io/en/latest/quick-start.html#correct-trim-and-assemble-manually) which should not be affected by an AT-rich genome.

**Comment by mvolar** [comment]
Just to update the new run is SIGNIFICANTLY slower, previous runs were completed in 2 days, now I'm only on the trimming step. Will rerun with the 95% ONT accuracy mode after it finishes.

**Comment by skoren** [comment]
That is expected if you ended up with a lot more or longer reads from changing the correction parameters. Have you compared the assembly reports so far side by side?

**Comment by mvolar** [comment]
The assembly had finished on Sunday around 5 am. Both assemblies are largely the same (the first one and one with new options). difference is in around 2000 reads between original and trimmed and the resulting coverage is approximately the same. The problem is that our longest reads (100kb+) are heavily interspersed with repeat elements, and it looks like there is insufficient evidence for their existence because of their around 50% repeat element content, like in the picture below, where the black/grey elements represent the main satellite:

![repeats_in_reads](https://user-images.githubusercontent.com/89461052/132204438-e47966a3-deef-4035-bf19-82208b911811.png)


From BLAST results in reads approximately 30% of bases are contained within the repeats, in the contigs however that number is more than halved, down to 10% out of total bases (and most of those are in the smaller contigs which are start-to-finish long repeat elements). It looks like we should be striving to increase our N50 and max read length in order to get a better assembly. Thanks a lot for the prompt response and the help.
