### ISSUE TITLE
Error trimming out.ovlStore.BUILDING fails last 4 jobs

### ISSUE THREAD

**Issue by Sharpens** [marbl/canu#2014]
Hi, I am having trouble completing the last 4 jobs on the trimming/out.ovlStore.BUILDING step. I have 16 jobs in total but 11, 12, 13, and 15 fail when i run the command. 

The command i'm using is: canu -p out genomeSize=5m maxThreads=20 minReadLength=1000 gridOptionsovs=--mem-per-cpu=40g  -nanopore-raw *.fastq 

The output i get is 
```
CONFIGURE CANU

Detected Java(TM) Runtime Environment '11.0.12' (from 'java') without -d64 support.
 Detected gnuplot version '5.2 patchlevel 6   ' (from 'gnuplot') and image format 'png'.
 Detected 64 CPUs and 996 gigabytes of memory.
 Limited to 20 CPUs from maxThreads option.
 No grid engine detected, grid disabled.
--
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |     total usage     algorithm
--        -------  ------  --------   --------  -----------------  -----------------------------
-- Local: meryl     12 GB    4 CPUs x   5 jobs    60 GB   20 CPUs  (k-mer counting)
-- Local: hap        8 GB    4 CPUs x   5 jobs    40 GB   20 CPUs  (read-to-haplotype assignment)
-- Local: cormhap    6 GB   10 CPUs x   2 jobs    12 GB   20 CPUs  (overlap detection with mhap)
-- Local: obtovl     4 GB    5 CPUs x   4 jobs    16 GB   20 CPUs  (overlap detection)
-- Local: utgovl     4 GB    5 CPUs x   4 jobs    16 GB   20 CPUs  (overlap detection)
-- Local: ovb        4 GB    1 CPU  x  20 jobs    80 GB   20 CPUs  (overlap store bucketizer)
-- Local: ovs        8 GB    1 CPU  x  20 jobs   160 GB   20 CPUs  (overlap store sorting)
-- Local: red        8 GB    4 CPUs x   5 jobs    40 GB   20 CPUs  (read error detection)
-- Local: oea        4 GB    1 CPU  x  20 jobs    80 GB   20 CPUs  (overlap error adjustment)
-- Local: bat       16 GB    4 CPUs x   1 job     16 GB    4 CPUs  (contig construction with bogart)
-- Local: gfa        8 GB    4 CPUs x   1 job      8 GB    4 CPUs  (GFA alignment and processing)
--
-- In 'out.seqStore', found Nanopore reads:
--   Raw:        1018781
--   Corrected:  330649
--   Trimmed:    0
--
-- Generating assembly 'out' in '/mibi/users/wjg795/fastq_output'
--
-- Parameters:
--
--  genomeSize        5000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1200 ( 12.00%)
--    utgOvlErrorRate 0.1200 ( 12.00%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1200 ( 12.00%)
--    utgErrorRate    0.1200 ( 12.00%)
--    cnsErrorRate    0.2000 ( 20.00%)
--
--
-- BEGIN TRIMMING
--
--
-- Creating overlap store trimming/out.ovlStore using:
--     16 buckets
--    320 slices
--        using at most 8 GB memory each
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'ovB' concurrent execution on Fri Aug 27 10:31:25 2021 with 14701.933 GB free disk space (4 processes; 20 concurrently)

    cd trimming/out.ovlStore.BUILDING
    ./scripts/1-bucketize.sh 11 > ./logs/1-bucketize.000011.out 2>&1
    ./scripts/1-bucketize.sh 12 > ./logs/1-bucketize.000012.out 2>&1
    ./scripts/1-bucketize.sh 13 > ./logs/1-bucketize.000013.out 2>&1
    ./scripts/1-bucketize.sh 15 > ./logs/1-bucketize.000015.out 2>&1

-- Finished on Fri Aug 27 11:00:41 2021 (1756 seconds) with 14599.539 GB free disk space
----------------------------------------
--
-- Overlap store bucketizer jobs failed, retry.
--   job trimming/out.ovlStore.BUILDING/bucket0011 FAILED.
--   job trimming/out.ovlStore.BUILDING/bucket0012 FAILED.
--   job trimming/out.ovlStore.BUILDING/bucket0013 FAILED.
--   job trimming/out.ovlStore.BUILDING/bucket0015 FAILED.
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'ovB' concurrent execution on Fri Aug 27 11:00:41 2021 with 14599.539 GB free disk space (4 processes; 20 concurrently)

    cd trimming/out.ovlStore.BUILDING
    ./scripts/1-bucketize.sh 11 > ./logs/1-bucketize.000011.out 2>&1
    ./scripts/1-bucketize.sh 12 > ./logs/1-bucketize.000012.out 2>&1
    ./scripts/1-bucketize.sh 13 > ./logs/1-bucketize.000013.out 2>&1
    ./scripts/1-bucketize.sh 15 > ./logs/1-bucketize.000015.out 2>&1

-- Finished on Fri Aug 27 11:29:25 2021 (1724 seconds) with 14599.539 GB free disk space
----------------------------------------
--
-- Overlap store bucketizer jobs failed, tried 2 times, giving up.
--   job trimming/out.ovlStore.BUILDING/bucket0011 FAILED.
--   job trimming/out.ovlStore.BUILDING/bucket0012 FAILED.
--   job trimming/out.ovlStore.BUILDING/bucket0013 FAILED.
--   job trimming/out.ovlStore.BUILDING/bucket0015 FAILED.
--

ABORT:
ABORT: Canu 1.8
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
```
When i look in my folder i can see the that bucket1 to bucket16 excluding bucket11, 12, 13, 15 have been succesfull. The failed jobs folders are called create11, 12, 13, 15. I'm not sure why it won't finish but i suspect it's a possible curruption.

The logs from one of the failed jobs looks like this:
```
Found perl:
   /usr/bin/perl
   This is perl 5, version 28, subversion 1 (v5.28.1) built for x86_64-linux-gnu-thread-multi

Found java:
   /usr/bin/java
   openjdk version "11.0.12" 2021-07-20

Found canu:
   /usr/lib/canu/bin/canu
   Canu 1.8

Running job 15 based on command line options.

Attempting to increase maximum allowed processes and open files.
./scripts/1-bucketize.sh: 1: ulimit: Illegal option -u
./scripts/1-bucketize.sh: 1: ulimit: Illegal option -u
./scripts/1-bucketize.sh: 70: ulimit: Illegal option -u
./scripts/1-bucketize.sh: 1: ulimit: Illegal option -u
  Changed max processes per user from  to  (max ).
  Changed max open files from 1024 to 1048576 (max 1048576).

Overwriting incomplete result from presumed crashed job in directory './out.ovlStore.BUILDING/create0015'.

Opened '../out.seqStore' with 1018781 reads.

Constructing slice 15 for store './out.ovlStore.BUILDING'.
 - Filtering overlaps over 1.0000 fraction error.

Bucketizing input    1 out of    1 - '1-overlapper/001/000015.ovb'
Overlap has IDs out of range (maxID 1018781), possibly corrupt input data.
Segmentation fault
```
In the create folders there are many slices already done but some slices are 0kb. I have seen other posts and looks like i need to redo the currupted files. i'm not sure how to do this so any help would be greatly appreciated.

**Comment by Sharpens** [comment]
Thanks! I should remove the 1-overlapper/0001/000013.ovb, 1-overlapper/0001/000012.ovb and 1-overlapper/0001/000011.ovb, since they were corrupted aswell right?

1-overlapper/0001/000012.ovb had a different log report: 

Found perl:
   /usr/bin/perl
   This is perl 5, version 28, subversion 1 (v5.28.1) built for x86_64-linux-gnu-thread-multi

Found java:
   /usr/bin/java
   openjdk version "11.0.12" 2021-07-20

Found canu:
   /usr/lib/canu/bin/canu
   Canu 1.8

Running job 12 based on command line options.

Attempting to increase maximum allowed processes and open files.
./scripts/1-bucketize.sh: 1: ulimit: Illegal option -u
./scripts/1-bucketize.sh: 1: ulimit: Illegal option -u
./scripts/1-bucketize.sh: 70: ulimit: Illegal option -u
./scripts/1-bucketize.sh: 1: ulimit: Illegal option -u
  Changed max processes per user from  to  (max ).
  Changed max open files from 1024 to 1048576 (max 1048576).

Overwriting incomplete result from presumed crashed job in directory './out.ovlStore.BUILDING/create0012'.

Opened '../out.seqStore' with 1018781 reads.

Constructing slice 12 for store './out.ovlStore.BUILDING'.
 - Filtering overlaps over 1.0000 fraction error.

Bucketizing input    1 out of    1 - '1-overlapper/001/000012.ovb'
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

Is this also a possible corruption?

Thanks alot!

**Comment by skoren** [comment]
Yes, this is most likely also corruption. You may have some trial and error to find and remove all the corrupted files.

**Comment by Sharpens** [comment]
Alright, i have done as you have said but now i get a new error code:

 BEGIN TRIMMING
--
----------------------------------------
-- Starting command on Tue Aug 31 13:14:08 2021 with 15440.59 GB free disk space

    cd trimming
    /usr/lib/canu/bin/ovStoreConfig \
     -S ../out.seqStore \
     -M 4-8 \
     -L ./1-overlapper/ovljob.files \
     -create ./out.ovlStore.config \
     > ./out.ovlStore.config.txt \
    2> ./out.ovlStore.config.err

-- Finished on Tue Aug 31 13:14:09 2021 (one second) with 15440.59 GB free disk space
----------------------------------------

ERROR:
ERROR:  Failed with exit code 139.  (rc=35584)
ERROR:

ABORT:
ABORT: Canu 1.8
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to configure the overlap store.
ABORT:
ABORT: Disk space available:  15440.59 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (trimming/out.ovlStore.config.err):
ABORT:
ABORT:
ABORT:   Finding number of overlaps per read and per file.
ABORT:
ABORT:         Molaps
ABORT:   ------------ ----------------------------------------
ABORT:        249.660              1-overlapper/001/000001.ovb
ABORT:        748.990              1-overlapper/001/000002.ovb
ABORT:       1249.960              1-overlapper/001/000003.ovb
ABORT:       1748.159              1-overlapper/001/000004.ovb
ABORT:       2244.978              1-overlapper/001/000005.ovb
ABORT:       2747.335              1-overlapper/001/000006.ovb
ABORT:       3251.476              1-overlapper/001/000007.ovb
ABORT:       3744.065              1-overlapper/001/000008.ovb
ABORT:       4247.087              1-overlapper/001/000009.ovb
ABORT:       4749.572              1-overlapper/001/000010.ovb
ABORT:   Segmentation fault
ABORT:


Should i just the entire "trimming" folder at this time a start from there?

**Comment by skoren** [comment]
I'd update to the 2.2 release instead and then launch trimming and assembly on the corrected reads (`canu -p out genomeSize=5m maxThreads=20 minReadLength=1000 gridOptionsovs=--mem-per-cpu=40g -corrected -nanopore out.correctedReads.fasta.gz`)

**Comment by skoren** [comment]
Idle
