### ISSUE TITLE
Including ONT fastq_fail reads

### ISSUE THREAD

**Issue by tbrown91** [marbl/canu#2017]
Hi,

We are currently sequencing a ~2Gb genome with nanopore data and it looks like we will get around 100Gb data out from two flowcells. We are currently using the in-built "high-accuracy" basecaller and a read-quality cutoff of QV7. We have seen from test runs that these "fastq_pass" reads look to have a modal overlap error rate of around 10% (i.e. 5% per read) and those in the "fastq_fail" bin much higher, but likely still within the error profile that we see for pacbio.

Do you have any experience of including these failed reads into canu? I am hoping that the read correction and trimming would help already and that we would be potentially adding coverage in valuable regions. I am however worried that this would violate some underlying assumptions in canu about the error profiles of the reads.

Any advice would be much appreciated.

Thanks,

Tom

**Comment by skoren** [comment]
We've included the failed reads as part of correction before. If they're too low quality, they won't get corrected so won't hurt anything anyway. Given the lower error rate in your data, you could also try the uncorrected ONT assembly (see quick start: https://canu.readthedocs.io/en/latest/quick-start.html#correct-trim-and-assemble-manually) including the fail reads as well.

**Comment by tbrown91** [comment]
Hi Sergey,

Thank you. I will try out a few approaches to see what the results are like. 

I was also wondering about polishing after the assembly. With pacbio CLR reads we were generally seeing around Q40 coming out of triocanu, which was either not really changing or if anything getting worse afterwards polishing with arrow. Do you have any idea if polishing is necessary or better with nanopolish or whether you'd recommend another tool?

**Comment by skoren** [comment]
Are you using trio-binned reads for polishing, without that it is likely the arrow polishing won't make any improvements. ONT quality out of the assembler is likely to be lower so I would definitely polish it, again with trio-binned reads. We've used Nanopolish or Medaka. Also take a look at Merfin (https://github.com/arangrhie/merfin) which filters the polishing tool corrections to improve consensus.

**Comment by tbrown91** [comment]
We were able to get the trio-binned subreads before. Here we don't have a trio, so are a bit worried about the haplotypes causing issues.
