### ISSUE TITLE
Need help in setting a slurm job for running canu in a cluster 

### ISSUE THREAD

**Issue by gunjanpandey** [marbl/canu#2018]
I am just starting with eukaryotic genome assemblies in slurm. Could you please help me in setting a slurm job through a batch script for canu/2.1.1 (or if anything would change in the script when we upgrade to  canu 2.2)? We have around 30X coverage of nanopore (untrimmed, uncorrected; PromethION and MinION concatenated in a single file; 60X combined coverage) reads and our genome size is around 2.25g.

We have nodes in the following configuration 
1. 20 cpu with 125 gb memory each
2. 20 cpu with 512 gb memory each
3. 48 cpu with 3tb memory

I am pretty sure this is not how the batch script should should look like. 

#!/bin/bash
#SBATCH --nodes=1               			
#SBATCH --ntasks-per-node=1			
#SBATCH --cpus-per-task=20           		
#SBATCH --mem=500gb                   		
#SBATCH --time=30-00:00              		
#SBATCH --partition=ext 				

mkdir Result

module purge
module load canu/2.1.1 
#do we need any other modules?

#Define in and out paths 
in=data_file_path
out=Result

canu -p prefix genomeSize=2.25g -nanopore-raw  ${in}/nano-pre.fastq

**Comment by skoren** [comment]
You don't need to submit the canu job as a script, it will take care of that for you. You can request specific partitions and time: `gridOptions="--time=10-00:00 --partition=ext"` and you may need to also load the JVM module if you don't have java available by default.

**Comment by gunjanpandey** [comment]
Thank you for your prompt reply. But as an absolute beginner to HPC/slurm system, I dont understand what exact command I need to run to submit the script to HPC cluster 

could you confirm if below would be the script ? and if so, how can it be submitted to slurm? All I know the sbash way of submitting a job. I understand your time is precious but a little help would go  a long way for us. Thank you again.

`canu -p prefix genomeSize=2.25g -nanopore-raw path/nano-pre.fastq gridOptions="--time=10-00:00 --partition=ext"  `

**Comment by skoren** [comment]
None, you don't need to run any sbatch command. Just run the Canu command by itself:
```module load canu/2.1.1 jdk/10.0.2_013 && canu -d assembly -p prefix genomeSize=2.25g -nanopore-raw path/nano-pre.fastq  gridOptions="--time=10-00:00 --partition=ext```
which will submit itself to the grid. As for partition, most Canu jobs should fit in 125gb so use the one with the most available CPUs. You may want to add `maxMemory=120` to make sure Canu does not try to use more than available in that partition.

**Comment by gunjanpandey** [comment]
THANK YOU VERY MUCH. I now have it up and running.

**Comment by skoren** [comment]
Feel free to open an issue if you encounter an error during the run.

**Comment by gunjanpandey** [comment]
Will do that. Thank yo very much.

**Comment by gunjanpandey** [comment]
Sorry, I silly question. Do you think a job as above would finish in 14 day?

**Comment by skoren** [comment]
It will depend on how much CPU it's able to get on your cluster and the speed of the CPU, I/O, how repetitive your genome is, and how much coverage you have. The FAQ has some suggestions on how you can change parameters to speed the assembly up: https://canu.readthedocs.io/en/latest/faq.html, especially if you have recent ONT data.

**Comment by gunjanpandey** [comment]
Yes I was asking about the full assembly - approx time that canu takes?

I am getting an error

command
`module load canu/2.1.1 jdk/10.0.2_013 && srun canu -d assembly -p prefix genomeSize=2.25g -nanopore-raw path/nano-pre.fastq 01_RawData/Minion/nano-pre.fastq gridOptions="--time=10-00:00 --partition=ext --maxMemory=120g"


-- Starting command on Sat Sep  4 10:47:52 2021 with 14991.486 GB free disk space

    cd /assembly
    sbatch \
      --cpus-per-task=1 \
      --mem-per-cpu=4g \
      --time=10-00:00 \
      --partition=ext \
      --maxMemory=120  \
      -D `pwd` \
      -J 'canu_prefix' \
      -o canu-scripts/canu.01.out  canu-scripts/canu.01.sh
sbatch: unrecognized option '--maxMemory=120'
Try "sbatch --help" for more information



`srun -help | grep memory` gives me this. So there seems to be no --maxMemory option

--mem=MB                      minimum amount of real memory
--mem-per-cpu=MB        maximum amount of real memory per allocated
--mem-per-gpu=n           real memory required per allocated GPU

**Comment by skoren** [comment]
`maxMemory` is a Canu option not a slurm option: ```module load canu/2.1.1 jdk/10.0.2_013 && srun canu -d assembly -p prefix genomeSize=2.25g maxMemory=120 -nanopore-raw path/nano-pre.fastq 01_RawData/Minion/nano-pre.fastq gridOptions="--time=10-00:00 --partition=ext"```

**Comment by gunjanpandey** [comment]
got it. Thanks again

**Comment by gunjanpandey** [comment]
Could you please tell what is wrong here. Command and output both are below. I think the given time 14 days. 
` module load canu/2.1.1 jdk/10.0.2_013  && srun canu -d assembly -p prefix genomeSize=2.25g maxMemory=512 -nanopore-raw ../../../../01_RawData/Minion/nano-pre.fastq gridOptions="--time=14-00:00:00 --partition=m512gb"`


-- Starting command on Sat Sep  4 18:01:45 2021 with 15418.614 GB free disk space
 cd .
 ./prefix.seqStore.sh \
> ./prefix.seqStore.err 2>&1
srun: Force Terminated job 54592293
srun: Job step aborted: Waiting up to 122 seconds for job step to finish.
slurmstepd: error: *** STEP 54592293.0 ON c376 CANCELLED AT 2021-09-04T18:12:08 DUE TO TIME LIMIT ***
srun: error: c376: task 0: Terminated

**Comment by skoren** [comment]
You shouldn't use srun to submit the canu command, as I said previously. That's assigning the job the default time limit of 10 minutes which is insufficient. Let canu submit it's own job, remove srun from the command.

**Comment by gunjanpandey** [comment]
The job is running now. Thank you.

the program is at cormhap_ level and have utilized around 62TB space. Is there a way we can work out how much space it might need? Our genome is around 2.25g and nanopore coverage is ~65x. Canu was run with default settings as below 

`module load canu/2.1.1 jdk/10.0.2_013 && canu -d assembly -p prefix genomeSize=2.25g maxMemory=120 -nanopore-raw path/nano-pre.fastq 01_RawData/Minion/nano-pre.fastq gridOptions="--time=10-00:00 --partition=ext"`

**Comment by skoren** [comment]
It's hard to predict the size exactly because it depends on genome repeat content not just coverage and size. Most of your space is in temporary files which will be removed (and are not present in v2.2). The FAQ also has some suggestions to reduce space usage: https://canu.readthedocs.io/en/latest/faq.html#my-assembly-is-running-out-of-space-is-too-slow.

I'd recommend upgrading to v2.2 and starting an assembly from scratch using the recommended parameters from the FAQ. I'm going to close the issue since the original problem (setting slurm parameters) is resolved. If you encounter new errors with your restart you can open a new issue.
