### ISSUE TITLE
contigFilter not working?

### ISSUE THREAD

**Issue by alimayy** [marbl/canu#2024]
If I'm not missing something, the filtering thresholds I use in contigFilter aren't working:

System: linux
Canu version: canu 2.2

Canu command:

```
/canu-2.2/bin/canu \
  -p samplename \
  -d canu_assembly \
  useGrid=false \
  stopOnLowCoverage=0 \
  genomeSize=36.0m \
  minReadLength=1000 \
  contigFilter="20 1000 1.0 0.5 2" \
  -nanopore-raw reads.fastq.gz

```

I still get contigs with reads<20. Any clue what might be going on?

```
>tig00000067 len=13472 reads=1 class=contig suggestRepeat=yes suggestBubble=yes suggestCircular=no trim=0-13472
>tig00000068 len=13327 reads=1 class=contig suggestRepeat=yes suggestBubble=yes suggestCircular=no trim=0-13327
>tig00000070 len=20045 reads=11 class=contig suggestRepeat=yes suggestBubble=no suggestCircular=no trim=0-20045
>tig00000071 len=1356 reads=4 class=contig suggestRepeat=yes suggestBubble=no suggestCircular=no trim=0-1356
>tig00000073 len=1696 reads=2 class=contig suggestRepeat=yes suggestBubble=no suggestCircular=no trim=0-1696
>tig00000074 len=1381 reads=2 class=contig suggestRepeat=yes suggestBubble=no suggestCircular=no trim=0-1381

```
```
Output Filtering
contigFilter <minReads, integer=2> <minLength, integer=0> <singleReadSpan, float=1.0> <lowCovSpan, float=0.5> <lowCovDepth, integer=5>
A contig that needs any of the following conditions is flagged as ‘unassembled’ and removed from further consideration:

fewer than minReads reads (default 2)
shorter than minLength bases (default 0)
a single read covers more than singleReadSpan fraction of the contig (default 1.0)
more than lowCovSpan fraction of the contig is at coverage below lowCovDepth (defaults 0.5, 5)
This filtering is done immediately after initial contigs are formed, before potentially incorrectly spanned repeats are detected. Initial contigs that incorrectly span a repeat can be split into multiple contigs; none of these new contigs will be flagged as ‘unassembled’, even if they are a single read.
```
https://canu.readthedocs.io/en/latest/parameter-reference.html

**Comment by skoren** [comment]
I think it is working and the reason they are kept is that last line:
"Initial contigs that incorrectly span a repeat can be split into multiple contigs; none of these new contigs will be flagged as ‘unassembled’, even if they are a single read."

These are all marked as repeat so these came from the splitting step and so none of them are flagged as unassembled.

**Comment by alimayy** [comment]
Thanks for your quick response! 

So if I understand it right, these are parts of contigs that (before the contig was split) incorrectly spanned repeats. Then, is it correct to think of this (unsplit) contig structure as:

`nonrepeatseq1REPEATSEQnonrepeatseq2
`

and Canu identified nonrepeatseqs1 and/or nonrepeatseq2 to be incorrectly spanning REPEATSEQ, so it split the contig into >1 sequence, e.g. nonrepeatseq1, REPEATSEQ, nonrepeatseq2

Do the contigs in my example above with `suggestRepeat=yes` correspond to REPEATSEQ, then? If so, wouldn't one expect them to be formed by more-than-average number of reads instead of low amount of reads like above? 

Thanks again!

**Comment by skoren** [comment]
That's the general idea but it's not quite so straightforward since reads are never split. That means the reads that have repeat sequence will be present in the contigs comprising nonrepeatseq1, REPEATSEQ, and nonrepeatseq2. That is, the unique contigs will reach into the repeat sequence which will steal some of its reads. The REPEATSEQ is also often split into more than a single contig as well so that lowers the number of reads per single tig. Lastly, there are also some in your output which are both bubble and repeat which means this was a bubble which later got split so those have fewer reads from the start to lower even more.

**Comment by alimayy** [comment]
Thanks! I'm closing this
