### ISSUE TITLE
how to operate canu/

### ISSUE THREAD

**Issue by leggylas** [marbl/canu#2026]
Hi, I am new to assembly, I have installed the newest version of Canu using gitclone, however I don't understand what steps should I do next, after I paste this command, I use a MacOS by the way: 

cd canu/src

I'm supposed to 

 make -j <number of threads>   , what does number of threads mean? 

After that, how am I supposed to assemble my FASTQ file? 

The quickstart recommend you to do this if you have a nanopore data: 

canu \
 -p ecoli -d ecoli-oxford \
 genomeSize=4.8m maxInputCoverage=100 \
 -nanopore ecolk12mg1655_R10_3_guppy_345_HAC.fastq

However, how am I supposed to enter my data? https://www.ebi.ac.uk/ena/browser/view/DRX123937?show=reads

Any help is much appreciated, thank you

**Comment by brianwalenz** [comment]
A 'thread' is slang for how many CPUs to use.  https://en.wikipedia.org/wiki/Thread_(computing).  Here we're just compiling the source code into executable code.  This step isn't particularly time consuming; with one thread I can compile canu in about 100 seconds, with 16 threads it takes 15 seconds.

On MacOS, you might be better off using the pre-compiled release images.  The default compiler supplied with MacOS cannot properly compile Canu.

Scroll to the right in the "Read Files" table on that ENA page and you'll find a link to download the reads as a '.fastq.gz' file.  Change the genomeSize parameter from 4.8m to 3m (found by clicking on the Organism link) and supply the name of the downloaded reads.

**Comment by skoren** [comment]
Yep, what @brianwalenz said, no need to compile your own. The release page has instructions to download pre-compiled Darwin (OS X) binaries):
```
curl -L https://github.com/marbl/canu/releases/download/v2.2/canu-2.2.Darwin-amd64.tar.xz --output canu-2.2.Darwin.tar.xz 
tar -xJf canu-2.2.*.tar.xz
xattr -d com.apple.quarantine ./canu-2.2/bin/*
xattr -d com.apple.quarantine ./canu-2.2/lib/*
```

You also need to download the files from your ENA link:
```
curl -L ftp://ftp.sra.ebi.ac.uk/vol1/fastq/DRR131/DRR131199/DRR131199_1.fastq.gz -o reads.fastq.gz
```
then run Canu
```
./canu-2.2/bin/canu 
-p asm -d asm-oxford
genomeSize=3m maxInputCoverage=100 
-nanopore reads.fastq.gz
```

**Comment by leggylas** [comment]
> A 'thread' is slang for how many CPUs to use. https://en.wikipedia.org/wiki/Thread_(computing). Here we're just compiling the source code into executable code. This step isn't particularly time consuming; with one thread I can compile canu in about 100 seconds, with 16 threads it takes 15 seconds.
> 
> On MacOS, you might be better off using the pre-compiled release images. The default compiler supplied with MacOS cannot properly compile Canu.
> 
> Scroll to the right in the "Read Files" table on that ENA page and you'll find a link to download the reads as a '.fastq.gz' file. Change the genomeSize parameter from 4.8m to 3m (found by clicking on the Organism link) and supply the name of the downloaded reads.

I was told by the terminal to install GCC as a compiler, I types "brew install gcc" 

however, there seems to be a problem 
`Updating Homebrew...
==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 15 formulae.

==> Downloading https://ghcr.io/v2/homebrew/core/gmp/manifests/6.2.1_1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/gmp/blobs/sha256:491220f1ff2c66
Warning: Transient problem: timeout Will retry in 1 seconds. 3 retries left.  
-=O=-           #     #    #     #                                            
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to pkg-containers.githubusercontent.com:443 
Error: gcc: Failed to download resource "gmp"
Download failed: https://ghcr.io/v2/homebrew/core/gmp/blobs/sha256:491220f1ff2c662b96295d931a80702523eeaee681d7305fb02b561e527dcbb8
 

`

**Comment by leggylas** [comment]
> Yep, what @brianwalenz said, no need to compile your own. The release page: https://github.com/marbl/canu/releases has instructions to download pre-compiled Darwin (OS X) binaries):
> 
> ```
> curl -L https://github.com/marbl/canu/releases/download/v2.2/canu-2.2.Darwin-amd64.tar.xz --output canu-2.2.Darwin.tar.xz 
> tar -xJf canu-2.2.*.tar.xz
> xattr -d com.apple.quarantine ./canu-2.2/bin/*
> xattr -d com.apple.quarantine ./canu-2.2/lib/*
> ```
> 
> You also need to download the files from your ENA link:
> 
> ```
> curl -L ftp://ftp.sra.ebi.ac.uk/vol1/fastq/DRR131/DRR131199/DRR131199_1.fastq.gz -o reads.fastq.gz
> ```
> 
> then run Canu
> 
> ```
> ./canu-2.2/bin/canu 
> -p asm -d asm-oxford
> genomeSize=3m maxInputCoverage=100 
> -nanopore reads.fastq.gz
> ```

thank you so much, I'll try this out once I got my compiler running :)

**Comment by skoren** [comment]
You don't need a compiler to run the above

**Comment by leggylas** [comment]
> Seems like you had an issue with homebrew's server connection. However, as @brianwalenz and I said, you shouldn't need to compile canu. You can run my commands above without having a compiler installed.

so I just need to copy the code into the terminal?

**Comment by skoren** [comment]
Yes, you need to copy the commands to the terminal

**Comment by leggylas** [comment]
> Yes, you need to copy the commands to the terminal

Thank you so much, works like a charm, then after this I can begin the assembly process or has the sequence has already been assembled? How do you convert it to a FASTA format?

**Comment by skoren** [comment]
I included the commands to download the data and launch the assembly. The data is downloaded as gzipped fastq (https://en.wikipedia.org/wiki/FASTQ_format) which canu can read. The last command launches canu

**Comment by leggylas** [comment]
> I included the commands to download the data and launch the assembly. The data is downloaded as gzipped fastq (https://en.wikipedia.org/wiki/FASTQ_format) which canu can read. The last command launches canu

Oh yeah, I actually have downloaded the fastq data from ENA, and I have already inserted the command to download the files, I just need to launch Canu later. 

What I'm meaning to say is what am I supposed to do after I launched canu? 

Thank you so much for helping me btw, I have zero experience in this field :))

**Comment by skoren** [comment]
It will run for some time and generate an assembly, you can see the outputs to expect here: https://canu.readthedocs.io/en/latest/tutorial.html#outputs.

**Comment by leggylas** [comment]
> It will run for some time and generate an assembly, you can see the outputs to expect here: https://canu.readthedocs.io/en/latest/tutorial.html#outputs.

Ah okay, I see, I tried to run the Canu, however there seems to be a trouble shoot,
`  Reads are specified by the technology they were generated with, and any processing performed.

  [processing]
    -corrected
    -trimmed

  [technology]
    -pacbio      <files>
    -nanopore    <files>
    -pacbio-hifi <files>

Complete documentation at http://canu.readthedocs.org/en/latest/

zsh: command not found: -p
zsh: command not found: -nanopore`

**Comment by skoren** [comment]
I think that's because the command was split onto multiple lines, run it all on one line:
```
./canu-2.2/bin/canu -p asm -d asm-oxford genomeSize=3m maxInputCoverage=100 -nanopore reads.fastq.gz
```

**Comment by leggylas** [comment]
> I think that's because the command was split onto multiple lines, run it all on one line:
> 
> ```
> ./canu-2.2/bin/canu -p asm -d asm-oxford genomeSize=3m maxInputCoverage=100 -nanopore reads.fastq.gz
> ```

Splendid, it works perfectly, I'll update you asap when everything runs smoothly, thank you 👍

**Comment by skoren** [comment]
I'm going to close the issue since the initial question (installation) is resolved. If you do have an error, open a new issue with information on the error.
