### ISSUE TITLE
Canu not responding

### ISSUE THREAD

**Issue by leggylas** [marbl/canu#2027]
I have reached the trimming process but there seems to be no progress, I tried to suspend and resuspend it but it doesn't seem to work, is there any way I could check the progress, I know that the program is running earlier because my laptop is heating up but now it has cooled down but there's no progress...

`-- Starting 'obtovl' concurrent execution on Sat Sep 25 06:39:47 2021 with 92.424 GB free disk space (2 processes; 1 concurrently)

    cd trimming/1-overlapper
    ./overlap.sh 1 > ./overlap.000001.out 2>&1

^Z
zsh: suspended  ./canu-2.2/bin/canu -p asm -d asm-oxford genomeSize=3m maxInputCoverage=100  
(base) kristintalia@Kristins-MacBook-Air ~ % fg
[1]  + continued  ./canu-2.2/bin/canu -p asm -d asm-oxford genomeSize=3m maxInputCoverage=100  

^Z
zsh: suspended  ./canu-2.2/bin/canu -p asm -d asm-oxford genomeSize=3m maxInputCoverage=100  
(base) kristintalia@Kristins-MacBook-Air ~ % fg
[1]  + continued  ./canu-2.2/bin/canu -p asm -d asm-oxford genomeSize=3m maxInputCoverage=100  

 any help will be much appreciated :)`

**Comment by skoren** [comment]
It looks like it's running fine, as long as there isn't an error message. You can use top to monitor the job rather than the screen output.

**Comment by leggylas** [comment]
ah okay, how long does it usually take to assemble the sequence, just so I have a picture on how long I should wait?

**Comment by brianwalenz** [comment]
The overlapper stage is slow in this data for some reason.  On my somewhat slow machine, this stage took about 10 hours using 10 CPUs.  This stage runs twice -- once for 'trimming' and once for 'unitigging'.  All other steps combined took a little over two hours.

Canu option `-fast` should decrease run time.  The downside is that the assembly can be lower quality.

I've attached the output contigs.
[DRR131199_1.contigs.fasta.gz](https://github.com/marbl/canu/files/7229859/DRR131199_1.contigs.fasta.gz)

**Comment by leggylas** [comment]
> The overlapper stage is slow in this data for some reason. On my somewhat slow machine, this stage took about 10 hours using 10 CPUs. This stage runs twice -- once for 'trimming' and once for 'unitigging'. All other steps combined took a little over two hours.
> 
> Canu option `-fast` should decrease run time. The downside is that the assembly can be lower quality.
> 
> I've attached the output contigs.
> [DRR131199_1.contigs.fasta.gz](https://github.com/marbl/canu/files/7229859/DRR131199_1.contigs.fasta.gz)

Oh my gosh, thank you very much, so this is the final output of the assembly then, assuming that it is in fasta format? If it is no trouble to you, may I also see the copy of the session from the terminal? Because I think there may be a difference in my later final result and your result, because some of the run failed in mine (like the "gnuplot" for example)

**Comment by leggylas** [comment]
> > The overlapper stage is slow in this data for some reason. On my somewhat slow machine, this stage took about 10 hours using 10 CPUs. This stage runs twice -- once for 'trimming' and once for 'unitigging'. All other steps combined took a little over two hours.
> > Canu option `-fast` should decrease run time. The downside is that the assembly can be lower quality.
> > I've attached the output contigs.
> > [DRR131199_1.contigs.fasta.gz](https://github.com/marbl/canu/files/7229859/DRR131199_1.contigs.fasta.gz)
> 
> Oh my gosh, thank you very much, so this is the final output of the assembly then, assuming that it is in fasta format? If it is no trouble to you, may I also see the copy of the session from the terminal? Because I think there may be a difference in my later final result and your result, because some of the run failed in mine (like the "gnuplot" for example)

If it is too long to put it in here, you can also email it to me at kristintalia117@gmail.com

**Comment by brianwalenz** [comment]
Sorry, I didn't save the canu chatter output.

gnuplot is used only for information/diagnostic outputs, errors there don't affect the process.

**Comment by skoren** [comment]
If you have the output contigs (`DRR131199_1.contigs.fasta.gz`), yes you can use them for polishing with short-reads. We typically use the VGP recommendation for polishing with short-reads: https://github.com/VGP/vgp-assembly/tree/master/pipeline/freebayes-polish rather than Pilon for diploid organisms but I'm guessing this is a bacteria so Pilon should be OK.
