### ISSUE TITLE
Too much disk space

### ISSUE THREAD

**Issue by mpalmada** [marbl/canu#2028]
I am having issues with the huge amount of disk space canu needs to create a genome of 3.2 Gb estimated genome size. I don't know how much disk space I am supposed to need to run it smoothly but its using more than 40 Tb...

**Comment by skoren** [comment]
Hard to say much without more info, the disk space will vary based on coverage, genome repetitiveness, and read type. I'm going to guess you're using Nanopore reads and are in the correction step. If you're not using Canu 2.2, I suggest updating as that reduces disk usage (see #2022) by skipping some intermediate outputs. The FAQ also has some suggestions to reduce disk usage: https://canu.readthedocs.io/en/latest/faq.html#my-assembly-is-running-out-of-space-is-too-slow. Lastly, if you have recent Nanopore data (e.g. Guppy 5+ with HAC model) you can try the uncorrected assembly option: https://canu.readthedocs.io/en/latest/quick-start.html#assembling-with-multiple-technologies-and-multiple-files

**Comment by mpalmada** [comment]
I am using Canu 1.9, I am in the correction step with a genome of 3.2 Gb. I am using old PacBio data (no HiFi). Now it's using around 30 Tb in the results directory in the 1-overlapping step and started to create 3 Tb in the next one. How much disk space will updating reduce? It will start from scratch, I guess? It's been running during several weeks I don't know if I can take profit of what's been already done? Thanks @skoren!

**Comment by skoren** [comment]
By next step, I assume you mean it's building the ovlStore? In that case, it would probably take about double the current space at the peak. There isn't a good way to re-use the output of your current run because v1.9 is quite old, about 2 years old at this point and so isn't compatible with any newer versions. You can try to finish the run by following the info at the FAQ I linked to which tells you how to remove intermediate outputs to save space while building the store. Updating the command based on the FAQ and updating to the newer version should reduce space quite a bit. What is your exact command?

**Comment by mpalmada** [comment]
canu -p species_try -d /homes/users/mpalmada/projects/species_try/s01.1_Canu_PacBio/canu_assembly genomeSize=3.2g -pacbio /homes/users/mpalmada/projects/species_try/data/PacBio/fastqs/*fastq.gz 

(I have gzipped the fastqs now due to the disk space, should I uncompress them again?)

**Comment by skoren** [comment]
No reason to uncompress, Canu can read the compressed files. Are these fastqs from your sequencing core or were they downloaded from somewhere like NCBI. Sometimes, NCBI fastq files are properly filtered so they have lots of noise reads.

I'd suggest you can try to follow the FAQ to remove intermediate files manually assuming you still have space to keep going. If not, then I suggest updating to v2.2 and adding the parameters from the FAQ to reduce space usage.

**Comment by mpalmada** [comment]
I'll try updating to 2.2 and use those parameters! I'll keep you posted!

**Comment by mpalmada** [comment]
Updating to version 2.2 and using those parameters worked! Thanks @skoren!!

**Comment by gushiro** [comment]
@skoren would ovlStore takes double the space at its peak in Canu 2.2? I am just planning ahead my experiment as it is in still in the overlapping step and already consuming 4.8 Tb.
