### ISSUE TITLE
Old 2.1.1 release still on bioconda?

### ISSUE THREAD

**Issue by russellsmithies** [marbl/canu#2029]
Can someone update the version of canu available via bioconda please? It appears the newest available is 2.1.1.
https://anaconda.org/bioconda/canu

thanx

**Comment by skoren** [comment]
We don't officially support the conda package and don't have control over it. I see the OS X version is still 1.5. I suggest opening an issue on the conda GitHub page: https://github.com/bioconda/bioconda-recipes/blob/25ee21573c577aa1ae899e0f7fbbc848d8a63865/recipes/canu/meta.yaml. It should be as easy as changing the SHA to af9c6e709ff2d6473cf966702c420b9eb42d9078

**Comment by skoren** [comment]
I made a pull request to overhauled the canu recipe (https://github.com/bioconda/bioconda-recipes/pull/30832/files#diff-1f67a67164e90f2ac3b0fe4054914e1869fad6367926b8148dd74ea52bbb4bc8). Not sure how long it will take to get it tested/integrated.

**Comment by skoren** [comment]
The recipe should be updated now.
