### ISSUE TITLE
Kmer counting (meryl-count) jobs failed, tried 2 times, giving up

### ISSUE THREAD

**Issue by Songeun-ewha** [marbl/canu#2031]
Hi, I am running Canu 2.1 and bumped into Kmer counting errors.
Would you let me know if this is memory error or the other kinds? and how to solve it?
(I assigned 30 cores, and 900G memory)

**The commands I used are:**
```
module load canu/2.1

canu \
 -p obsoleta -d [folder_name] \
 genomeSize=3200m merylThreads=1 \
 -pacbio [input_file_name]
```

### The out file I got is: 
```
slurmstepd: error: Unable to create TMPDIR [/local_scratch/6824631]: Permission denied
slurmstepd: error: Setting TMPDIR to /tmp

Found perl:
   /usr/bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /software/jdk/1.8.0_111/bin/java
   Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/local_scratch/6824008

Found canu:
   /gpfs/fs1/sfw2/canu/2.1/bin/canu
   canu 2.1

-- canu 2.1
--
-- CITATIONS
--
-- For 'standard' assemblies of PacBio or Nanopore reads:
--   Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
--   Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
--   Genome Res. 2017 May;27(5):722-736.
--   http://doi.org/10.1101/gr.215087.116
-- 
-- Read and contig alignments during correction and consensus use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_111' (from '/software/jdk/1.8.0_111/bin/java') with -d64 support.
--
-- WARNING:
-- WARNING:  Failed to run gnuplot using command 'gnuplot'.
-- WARNING:  Plots will be disabled.
-- WARNING:
--
-- Detected 24 CPUs and 63 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /software/slurm/current/bin/sinfo.
-- Detected Slurm with task IDs up to 1000 allowed.
-- 
-- Found   4 hosts with  48 cores and  370 GB memory under Slurm control.
-- Found   9 hosts with  12 cores and   46 GB memory under Slurm control.
-- Found  11 hosts with  24 cores and  184 GB memory under Slurm control.
-- Found   1 host  with  52 cores and  175 GB memory under Slurm control.
-- Found   1 host  with  24 cores and  745 GB memory under Slurm control.
-- Found   5 hosts with  36 cores and  124 GB memory under Slurm control.
-- Found   1 host  with  24 cores and   54 GB memory under Slurm control.
-- Found   3 hosts with  24 cores and  502 GB memory under Slurm control.
-- Found  11 hosts with  16 cores and   61 GB memory under Slurm control.
-- Found  28 hosts with  12 cores and   21 GB memory under Slurm control.
-- Found   4 hosts with  12 cores and   38 GB memory under Slurm control.
-- Found   1 host  with  44 cores and  999 GB memory under Slurm control.
-- Found   1 host  with  36 cores and  175 GB memory under Slurm control.
-- Found   2 hosts with  12 cores and   62 GB memory under Slurm control.
-- Found   6 hosts with  48 cores and  123 GB memory under Slurm control.
-- Found   4 hosts with  36 cores and  370 GB memory under Slurm control.
-- Found   1 host  with  36 cores and  502 GB memory under Slurm control.
-- Found   1 host  with  64 cores and  497 GB memory under Slurm control.
-- Found   1 host  with  40 cores and  370 GB memory under Slurm control.
-- Found  32 hosts with  24 cores and  123 GB memory under Slurm control.
-- Found  16 hosts with  24 cores and   62 GB memory under Slurm control.
-- Found   3 hosts with  24 cores and  175 GB memory under Slurm control.
-- Found   3 hosts with  16 cores and  250 GB memory under Slurm control.
-- Found  13 hosts with  24 cores and  249 GB memory under Slurm control.
-- Found   1 host  with  16 cores and   53 GB memory under Slurm control.
-- Found   1 host  with  36 cores and  249 GB memory under Slurm control.
-- Found  89 hosts with  24 cores and   61 GB memory under Slurm control.
-- Found   1 host  with  24 cores and  277 GB memory under Slurm control.
-- Found   1 host  with  32 cores and  370 GB memory under Slurm control.
-- Found   2 hosts with  48 cores and  180 GB memory under Slurm control.
-- Found  20 hosts with  40 cores and  184 GB memory under Slurm control.
-- Found  49 hosts with  20 cores and  123 GB memory under Slurm control.
-- Found   1 host  with  12 cores and   28 GB memory under Slurm control.
-- Found   1 host  with  32 cores and 2929 GB memory under Slurm control.
-- Found   1 host  with  48 cores and  495 GB memory under Slurm control.
-- Found  16 hosts with  56 cores and  487 GB memory under Slurm control.
-- Found   4 hosts with  16 cores and  124 GB memory under Slurm control.
-- Found   1 host  with  32 cores and  175 GB memory under Slurm control.
-- Found   1 host  with  12 cores and   15 GB memory under Slurm control.
-- Found   1 host  with  40 cores and  185 GB memory under Slurm control.
-- Found   1 host  with  64 cores and  976 GB memory under Slurm control.
-- Found  65 hosts with  36 cores and  123 GB memory under Slurm control.
-- Found   1 host  with  28 cores and  123 GB memory under Slurm control.
-- Found   1 host  with  36 cores and  122 GB memory under Slurm control.
-- Found   1 host  with  64 cores and  187 GB memory under Slurm control.
-- Found   1 host  with  20 cores and  183 GB memory under Slurm control.
-- Found   7 hosts with  56 cores and  495 GB memory under Slurm control.
--
--                         (tag)Threads
--                (tag)Memory         |
--        (tag)             |         |  algorithm
--        -------  ----------  --------  -----------------------------
-- Grid:  meryl     24.000 GB    1 CPU   (k-mer counting)
-- Grid:  hap       16.000 GB   18 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   18.000 GB    8 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    24.000 GB   12 CPUs  (overlap detection)
-- Grid:  utgovl    24.000 GB   12 CPUs  (overlap detection)
-- Grid:  cor       24.000 GB    4 CPUs  (read correction)
-- Grid:  ovb        4.000 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       32.000 GB    1 CPU   (overlap store sorting)
-- Grid:  red       35.000 GB    8 CPUs  (read error detection)
-- Grid:  oea        8.000 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      512.000 GB   32 CPUs  (contig construction with bogart)
-- Grid:  cns        -.--- GB    8 CPUs  (consensus)
--
-- In 'obsoleta.seqStore', found PacBio CLR reads:
--   PacBio CLR:               1
--
--   Raw:                      1
--
-- Generating assembly 'obsoleta' in '/gpfs/fs2/scratch/slee239/PacBio/Tobsoleta_092821':
--    - correct raw reads.
--    - trim corrected reads.
--    - assemble corrected and trimmed reads.
--
-- Parameters:
--
--  genomeSize        3200000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0750 (  7.50%)
--
--
-- BEGIN CORRECTION
--
--
-- Kmer counting (meryl-count) jobs failed, tried 2 times, giving up.
--   job obsoleta.01.meryl FAILED.
--

ABORT:
ABORT: canu 2.1
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```

**Comment by skoren** [comment]
See my comments on #2030, post the log files from the `correction/0-*/meryl-count*.out`

**Comment by Songeun-ewha** [comment]
Hi Skoren, thank you very much for the comments - I am checking #2030 now.
These are the log files I got below. It says the job was cancelled due to the time limit
but it actually done before the assigned time is over...


### meryl-count.6824810_1.out

slurmstepd: error: Unable to create TMPDIR [/local_scratch/6824631]: Permission denied
slurmstepd: error: Setting TMPDIR to /tmp

Found perl:
   /usr/bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /software/jdk/1.8.0_111/bin/java
   Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/local_scratch/6824008

Found canu:
   /gpfs/fs1/sfw2/canu/2.1/bin/canu
   canu 2.1

Running job 1 based on SLURM_ARRAY_TASK_ID=1 and offset=0.

Found 1 command tree.

Counting 127 (estimated) billion canonical 16-mers from 1 input file:
    canu-seqStore: ../../obsoleta.seqStore


SIMPLE MODE
-----------

  16-mers
    -> 4294967296 entries for counts up to 65535.
    -> 64 Gbits memory used

  137267560105 input bases
    -> expected max count of 549070240, needing 15 extra bits.
    -> 60 Gbits memory used

  15 GB memory needed


COMPLEX MODE
------------

prefix     # of   struct   kmers/    segs/      min     data    total
  bits   prefix   memory   prefix   prefix   memory   memory   memory
------  -------  -------  -------  -------  -------  -------  -------
     1     2  P    61 MB    63 GM  3963 kS   128 kB   495 GB   495 GB
     2     4  P    59 MB    31 GM  1917 kS   256 kB   479 GB   479 GB
     3     8  P    57 MB    15 GM   926 kS   512 kB   463 GB   463 GB
     4    16  P    55 MB  8181 MM   447 kS  1024 kB   447 GB   447 GB
     5    32  P    54 MB  4090 MM   215 kS  2048 kB   431 GB   431 GB
     6    64  P    52 MB  2045 MM   103 kS  4096 kB   415 GB   415 GB
     7   128  P    50 MB  1022 MM    49 kS  8192 kB   399 GB   399 GB
     8   256  P    48 MB   511 MM    23 kS    16 MB   383 GB   383 GB
     9   512  P    47 MB   255 MM    11 kS    32 MB   367 GB   367 GB
    10  1024  P    47 MB   127 MM  5626  S    64 MB   351 GB   351 GB
    11  2048  P    48 MB    63 MM  2685  S   128 MB   335 GB   335 GB
    12  4096  P    52 MB    31 MM  1279  S   256 MB   319 GB   319 GB
    13  8192  P    63 MB    15 MM   608  S   512 MB   304 GB   304 GB
    14    16 kP    86 MB  8181 kM   288  S  1024 MB   288 GB   288 GB
    15    32 kP   135 MB  4090 kM   136  S  2048 MB   272 GB   272 GB
    16    64 kP   234 MB  2045 kM    64  S  4096 MB   256 GB   256 GB
    17   128 kP   434 MB  1022 kM    30  S  8192 MB   240 GB   240 GB
    18   256 kP   836 MB   511 kM    14  S    16 GB   224 GB   224 GB  Best Value!
    19   512 kP  1644 MB   255 kM     7  S    32 GB   224 GB   225 GB
    20  1024 kP  3256 MB   127 kM     3  S    64 GB   192 GB   195 GB
    21  2048 kP  6496 MB    63 kM     2  S   128 GB   256 GB   262 GB
    22  4096 kP    12 GB    31 kM     1  S   256 GB   256 GB   268 GB
    23  8192 kP    25 GB    15 kM     1  S   512 GB   512 GB   537 GB
    24    16 MP    50 GB  8182  M     1  S  1024 GB  1024 GB  1074 GB
    25    32 MP   101 GB  4091  M     1  S  2048 GB  2048 GB  2149 GB
    26    64 MP   202 GB  2046  M     1  S  4096 GB  4096 GB  4298 GB


FINAL CONFIGURATION
-------------------

Configured simple mode for 15.500 GB memory per batch, and up to 1 batch.

Start counting with SIMPLE method.
Loading kmers from '../../obsoleta.seqStore' into buckets.
Increasing to 17-bit storage (for kmer 0x00000000000000000000000055555555).
Increasing to 18-bit storage (for kmer 0x00000000000000000000000055555555).
Increasing to 19-bit storage (for kmer 0x00000000000000000000000055555555).
Increasing to 20-bit storage (for kmer 0x00000000000000000000000055555555).
Increasing to 21-bit storage (for kmer 0x00000000000000000000000055555555).
Increasing to 22-bit storage (for kmer 0x00000000000000000000000055555555).
Increasing to 23-bit storage (for kmer 0x00000000000000000000000055555555).
Increasing to 24-bit storage (for kmer 0x00000000000000000000000055555555).
Increasing to 25-bit storage (for kmer 0x00000000000000000000000055555555).
slurmstepd: error: *** JOB 6824810 ON bhc0173 CANCELLED AT 2021-09-28T13:52:17 DUE TO TIME LIMIT ***
### 

meryl-count.6824630_1.out

slurmstepd: error: Unable to create TMPDIR [/local_scratch/6824008]: Permission denied
slurmstepd: error: Setting TMPDIR to /tmp

Found perl:
   /usr/bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /software/jdk/1.8.0_111/bin/java
   Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/local_scratch/6824008

Found canu:
   /gpfs/fs1/sfw2/canu/2.1/bin/canu
   canu 2.1

Running job 1 based on SLURM_ARRAY_TASK_ID=1 and offset=0.

Found 1 command tree.

Counting 127 (estimated) billion canonical 16-mers from 1 input file:
    canu-seqStore: ../../obsoleta.seqStore


SIMPLE MODE
-----------

  16-mers
    -> 4294967296 entries for counts up to 65535.
    -> 64 Gbits memory used

  137267560105 input bases
    -> expected max count of 549070240, needing 15 extra bits.
    -> 60 Gbits memory used

  15 GB memory needed


COMPLEX MODE
------------

prefix     # of   struct   kmers/    segs/      min     data    total
  bits   prefix   memory   prefix   prefix   memory   memory   memory
------  -------  -------  -------  -------  -------  -------  -------
     1     2  P    61 MB    63 GM  3963 kS   128 kB   495 GB   495 GB
     2     4  P    59 MB    31 GM  1917 kS   256 kB   479 GB   479 GB
     3     8  P    57 MB    15 GM   926 kS   512 kB   463 GB   463 GB
     4    16  P    55 MB  8181 MM   447 kS  1024 kB   447 GB   447 GB
     5    32  P    54 MB  4090 MM   215 kS  2048 kB   431 GB   431 GB
     6    64  P    52 MB  2045 MM   103 kS  4096 kB   415 GB   415 GB
     7   128  P    50 MB  1022 MM    49 kS  8192 kB   399 GB   399 GB
     8   256  P    48 MB   511 MM    23 kS    16 MB   383 GB   383 GB
     9   512  P    47 MB   255 MM    11 kS    32 MB   367 GB   367 GB
    10  1024  P    47 MB   127 MM  5626  S    64 MB   351 GB   351 GB
    11  2048  P    48 MB    63 MM  2685  S   128 MB   335 GB   335 GB
    12  4096  P    52 MB    31 MM  1279  S   256 MB   319 GB   319 GB
    13  8192  P    63 MB    15 MM   608  S   512 MB   304 GB   304 GB
    14    16 kP    86 MB  8181 kM   288  S  1024 MB   288 GB   288 GB
    15    32 kP   135 MB  4090 kM   136  S  2048 MB   272 GB   272 GB
    16    64 kP   234 MB  2045 kM    64  S  4096 MB   256 GB   256 GB
    17   128 kP   434 MB  1022 kM    30  S  8192 MB   240 GB   240 GB
    18   256 kP   836 MB   511 kM    14  S    16 GB   224 GB   224 GB  Best Value!
    19   512 kP  1644 MB   255 kM     7  S    32 GB   224 GB   225 GB
    20  1024 kP  3256 MB   127 kM     3  S    64 GB   192 GB   195 GB
    21  2048 kP  6496 MB    63 kM     2  S   128 GB   256 GB   262 GB
    22  4096 kP    12 GB    31 kM     1  S   256 GB   256 GB   268 GB
    23  8192 kP    25 GB    15 kM     1  S   512 GB   512 GB   537 GB
    24    16 MP    50 GB  8182  M     1  S  1024 GB  1024 GB  1074 GB
    25    32 MP   101 GB  4091  M     1  S  2048 GB  2048 GB  2149 GB
    26    64 MP   202 GB  2046  M     1  S  4096 GB  4096 GB  4298 GB


FINAL CONFIGURATION
-------------------

Configured simple mode for 15.500 GB memory per batch, and up to 1 batch.

Start counting with SIMPLE method.
Loading kmers from '../../obsoleta.seqStore' into buckets.
Increasing to 17-bit storage (for kmer 0x00000000000000000000000055555555).
Increasing to 18-bit storage (for kmer 0x00000000000000000000000055555555).
Increasing to 19-bit storage (for kmer 0x00000000000000000000000055555555).
Increasing to 20-bit storage (for kmer 0x00000000000000000000000055555555).
Increasing to 21-bit storage (for kmer 0x00000000000000000000000055555555).
Increasing to 22-bit storage (for kmer 0x00000000000000000000000055555555).
Increasing to 23-bit storage (for kmer 0x00000000000000000000000055555555).
slurmstepd: error: *** JOB 6824630 ON bhc0178 CANCELLED AT 2021-09-28T13:48:48 DUE TO TIME LIMIT ***

**Comment by skoren** [comment]
Looks like a simple fix, you need to add gridOptions to your canu command to specify a time limit. The way canu runs is it submits jobs to the grid on its own: https://canu.readthedocs.io/en/latest/faq.html#how-do-i-run-canu-on-my-slurm-sge-pbs-lsf-torque-system. That means the resources you requested only apply to the first step which just reads the input data and submits the next step (k-mer counting). Add ```gridOptions="--time 96:00:00``` to your command. Alternatively, you could restrict Canu to a single node (```useGrid=false```) but that will be much slower than letting it use your grid resources.

**Comment by Songeun-ewha** [comment]
Thank you for the comment - that worked! now the K-mer counting step is finished and I have two folders, '0-mercounts' and '1-overlapper' folders in correction folder but the process is over with empty *.report file. I cannot find error messages for that and posted the .out and log files below..
 

### The last out file I got in canu-scripts is canu.04.out (below):

slurmstepd: error: Unable to create TMPDIR [/local_scratch/6844857]: Permission denied
slurmstepd: error: Setting TMPDIR to /tmp

Found perl:
   /usr/bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /software/jdk/1.8.0_111/bin/java
   Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/local_scratch/6831927

Found canu:
   /gpfs/fs1/sfw2/canu/2.1/bin/canu
   canu 2.1

-- canu 2.1
--
-- CITATIONS
--
-- For 'standard' assemblies of PacBio or Nanopore reads:
--   Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
--   Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
--   Genome Res. 2017 May;27(5):722-736.
--   http://doi.org/10.1101/gr.215087.116
-- 
-- Read and contig alignments during correction and consensus use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_111' (from '/software/jdk/1.8.0_111/bin/java') with -d64 support.
--
-- WARNING:
-- WARNING:  Failed to run gnuplot using command 'gnuplot'.
-- WARNING:  Plots will be disabled.
-- WARNING:
--
-- Detected 24 CPUs and 63 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /software/slurm/current/bin/sinfo.
-- Detected Slurm with task IDs up to 1000 allowed.
-- 
-- Found   4 hosts with  48 cores and  370 GB memory under Slurm control.
-- Found   9 hosts with  12 cores and   46 GB memory under Slurm control.
-- Found  11 hosts with  24 cores and  184 GB memory under Slurm control.
-- Found   1 host  with  52 cores and  175 GB memory under Slurm control.
-- Found   1 host  with  24 cores and  745 GB memory under Slurm control.
-- Found   5 hosts with  36 cores and  124 GB memory under Slurm control.
-- Found   1 host  with  24 cores and   54 GB memory under Slurm control.
-- Found   3 hosts with  24 cores and  502 GB memory under Slurm control.
-- Found  11 hosts with  16 cores and   61 GB memory under Slurm control.
-- Found  28 hosts with  12 cores and   21 GB memory under Slurm control.
-- Found   4 hosts with  12 cores and   38 GB memory under Slurm control.
-- Found   1 host  with  44 cores and  999 GB memory under Slurm control.
-- Found   1 host  with  36 cores and  175 GB memory under Slurm control.
-- Found   2 hosts with  12 cores and   62 GB memory under Slurm control.
-- Found   6 hosts with  48 cores and  123 GB memory under Slurm control.
-- Found   1 host  with  64 cores and  497 GB memory under Slurm control.
-- Found   1 host  with  36 cores and  502 GB memory under Slurm control.
-- Found   4 hosts with  36 cores and  370 GB memory under Slurm control.
-- Found   1 host  with  40 cores and  370 GB memory under Slurm control.
-- Found  32 hosts with  24 cores and  123 GB memory under Slurm control.
--
--
--
--
--
-- Parameters:




### The last file I got in the canu-logs folder (1632929867_bhc0014_15455_canu) is:


###
###  Reading options from '/gpfs/fs1/sfw2/canu/2.1/bin/canu.defaults'
###

# Add site specific options (for setting up Grid or limiting memory/threads) here.

###
###  Reading options from the command line.
###

genomeSize=3200m
gridOptions=--time 48:00:00
canuIteration=2

**Comment by skoren** [comment]
That file is definitely truncated which makes me thing the job is still running but the SLURM stdout/stderr logging to the file is not flushed. What jobs do you have in your cluster queue? What is the contents of the 1-overlapper file.

**Comment by Songeun-ewha** [comment]
The queue does not show any jobs running (I submitted one job and it sometimes disappeared the new jobs showed up continuing the Canu process.. I don't know what is happening with the server but maybe there are some jobs waiting to run..?). The contents of the '1-overlapper' folder are:

two folders: 
queries (files from '000001' to '000711')
blocks (files: *.dat, *.input.fasta, *.input.dat, *.input.fasta.FAILED)

files: 
precompute.*.out     
precompute.jobSubmit-01.sh
partitioning.log
precompute.sh
mhap.sh
queries.tar

**Comment by skoren** [comment]
It looks like the next steps were running but some may have failed (due to the presence of the FAILED files). In these cases, Canu auto-retries once. That still doesn't explain why the canu.04.out file is truncated, `squeue` should report both running and queued jobs. Post the `precompute.jobSubmit-01.sh` file and check if any `precompute.*.out` files report an error.

**Comment by Songeun-ewha** [comment]
I will check if there are some error messages in precompute.*_*.out files. 
The contents of precompute.jobSumit-01.sh and .out are:

 
### precompute.jobSubmit-01.sh:

#!/bin/sh

sbatch \
  --cpus-per-task=8 --mem-per-cpu=2880m --time 48:00:00 -o precompute.%A_%a.out \
  -D `pwd` -J "cormhap_obsoleta" \
  -a 108-285 \
  `pwd`/precompute.sh 0 \
> ./precompute.jobSubmit-01.out 2>&1


### precompute.jobSubmit-01.sh is:

Submitted batch job 6861087

**Comment by Songeun-ewha** [comment]
### One of the precompute.*_*.out file which failed is below.

precompute.6861087_279.out:

slurmstepd: error: Unable to create TMPDIR [/local_scratch/6844857]: Permission denied
slurmstepd: error: Setting TMPDIR to /tmp

Found perl:
   /usr/bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /software/jdk/1.8.0_111/bin/java
   Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/local_scratch/6831927

Found canu:
   /gpfs/fs1/sfw2/canu/2.1/bin/canu
   canu 2.1

Running job 279 based on SLURM_ARRAY_TASK_ID=279 and offset=0.
/gpfs/fs2/scratch/slee239/PacBio/Tobsoleta_092821-1/correction/1-overlapper
Opened seqStore '../../obsoleta.seqStore' for 'raw' reads.
Dumping raw reads from 13510801 to 13559400 (inclusive).
writeToFile()-- After writing 529 out of 15479 'AS_UTL_writeFastA::seq' objects (1 bytes each): Disk quota exceeded
Failed to extract fasta.

**Comment by skoren** [comment]
Those both look fine and it does look like the jobs were re-tried at least once because the latter half all failed (0-107 worked but 108-285 didn't). Check the history of job 6861087 as well (`sacct -j 6861087`).

**Comment by Songeun-ewha** [comment]
![status](https://user-images.githubusercontent.com/27803915/135354750-0a957396-f4b9-45ce-9039-7cacf8391437.png)

**Comment by skoren** [comment]
Ah that explains both why the file is truncated and why the jobs failed: "Disk quota exceeded
Failed to extract fasta." You're out of disk/quota space. We recommend 3tb free for a 3gb well-behaved genome (https://canu.readthedocs.io/en/latest/faq.html#what-resources-does-canu-require-for-a-bacterial-genome-assembly-a-mammalian-assembly).

**Comment by skoren** [comment]
Closing since the original issue resolved (adding time request to gridOptions) and the last failure was out of disk space. If you do have more space available to run and encounter other errors, feel free to open a new issue. The FAQ has some suggestions to save space during assembly as well.

**Comment by brianwalenz** [comment]
Canu 2.2 has lower disk usage in this step and is worth upgrading to.  It should be possible to upgrade and restart; delete `correction/1-overlapper/results` before restarting - this holds the results of this step and should be a large directory with lots of `*.ovb`, `*.mhap` and `*WORKING*` files.

If read length and coverage are high, you can also throw out short reads (minReadLength) and short overlaps (minOverlapLength).  The defaults are 1000 and 500 respectively, and are quite conservative.  I think minOverlapLength can be increased without a full restart
