### ISSUE TITLE
MD5 checksum value

### ISSUE THREAD

**Issue by kokevin** [marbl/canu#2032]
Hi, I followed the instructions from https://github.com/marbl/canu/releases to download canu:

```
curl -L https://github.com/marbl/canu/releases/download/v2.2/canu-2.2.Linux-amd64.tar.xz --output canu-2.2.Linux.tar.xz
tar -xJf canu-2.2.*.tar.xz
```
Then ran `md5sum canu-2.2.Linux.tar.xz` and got this value:
```
63219165fc45b3dbbeb73ed920a23db5  canu-2.2.Linux.tar.xz
```

which is different than the listed value from https://github.com/marbl/canu/releases:
```
46bcd769e0726bd1df8b59af13505ba5	canu-2.2.Darwin-amd64.tar.xz
f417833c7846c5784523515c7dae9704	canu-2.2.Linux-amd64.tar.xz
```

**Comment by skoren** [comment]
Yes, you're right, the MD5sum on the release page is incorrect. Yours is correct, I updated the release notes.
