### ISSUE TITLE
Why do I get different assembly results on my laptop and on Slurm cluster?

### ISSUE THREAD

**Issue by Andromeda96** [marbl/canu#2037]
Include the canu command used, or at least tell us what options you've set.
I am using a canu for assembly on corrected fasta file on both my laptop and a slurm cluster but I got different results with the same command. My command is:
./canu-2.1.1/bin/canu -p nano.13cor -d ./assembly/cor13 genomeSize=4m -corrected -trimmed -nanopore ./data/nano.cor13.fasta
Include the output of `canu -version` if it isn't in any outputs.  It's reported at the start of the logging, and just before any crash report.
2.1.1
Include what system you're running on.  MacOS, Linux, or other?  In a virtual machine?  On a grid?
Macos, Linux.
On my laptop, it takes longer time and have complete report and output contigs. However on the Slurm, it is done in several seconds but miss a lot things in the report and outputs like the contigs. Do I need to make any change to the command when I use it on the slurm server?

**Comment by brianwalenz** [comment]
When you run Canu on the head node of your cluster, it detects that Slurm is available and submits itself to Slurm for execution, then exits.  On the laptop, there is no cluster available, and Canu will run all the steps before exiting.

Use Slurm command `squeue` to see what jobs are running.

Supply canu option `useGrid=false` to disable cluster support.

Some documentation:
 - https://canu.readthedocs.io/en/latest/tutorial.html
- https://canu.readthedocs.io/en/latest/tutorial.html#execution-configuration
- https://canu.readthedocs.io/en/latest/parameter-reference.html#grid-engine-support

and

 - https://canu.readthedocs.io/en/latest/faq.html

**Comment by valery-shap** [comment]
Hello,

I have the same problem. I run canu for 3 times (twice with slurm, once using special node ) and have different assembly results:
1. w/o Slurm, using 96 cpus

```
/home/canu-2.2/bin/canu -p ecoli -d id_canu_96_cpus useGrid=false genomeSize=5.5m maxInputCoverage=100 -nanopore barcode02.fastq.gz
>tig00000001 len=4804575 reads=9554 class=contig suggestRepeat=no suggestBubble=no suggestCircular=yes trim=3312-4788130
>tig00000002 len=138669 reads=97 class=contig suggestRepeat=no suggestBubble=no suggestCircular=yes trim=10312-124744
>tig00000004 len=136900 reads=170 class=contig suggestRepeat=no suggestBubble=no suggestCircular=yes trim=17821-133236
>tig00000005 len=77785 reads=28 class=contig suggestRepeat=no suggestBubble=no suggestCircular=yes trim=9544-70259
>tig00000006 len=116647 reads=101 class=contig suggestRepeat=no suggestBubble=no suggestCircular=yes trim=6141-107632
>tig00000007 len=15981 reads=1 class=contig suggestRepeat=yes suggestBubble=no suggestCircular=no trim=0-15981
>tig00000008 len=21428 reads=2 class=contig suggestRepeat=yes suggestBubble=no suggestCircular=no trim=0-21428
>tig00000009 len=48711 reads=18 class=contig suggestRepeat=yes suggestBubble=no suggestCircular=no trim=0-48711

```
2. from terminal, using grid true
```
/home/canu-2.2/bin/canu -p ecoli -d id_canu genomeSize=5.5m maxInputCoverage=100 -nanopore barcode02.fastq.gz

>tig00000001 len=4814457 reads=9512 class=contig suggestRepeat=no suggestBubble=no suggestCircular=yes trim=13364-4798238
>tig00000002 len=162128 reads=162 class=contig suggestRepeat=no suggestBubble=no suggestCircular=no trim=0-162128
>tig00000004 len=141044 reads=95 class=contig suggestRepeat=no suggestBubble=no suggestCircular=yes trim=22285-136726
>tig00000005 len=92860 reads=39 class=contig suggestRepeat=no suggestBubble=no suggestCircular=no trim=0-92860
>tig00000006 len=127698 reads=85 class=contig suggestRepeat=no suggestBubble=no suggestCircular=yes trim=17521-119000
>tig00000007 len=36918 reads=13 class=contig suggestRepeat=no suggestBubble=no suggestCircular=no trim=0-36918
```

3. from slurm bash script, but w/o setting cpus or node, grid True
```
/home/canu-2.2/bin/canu -p ecoli -d id_canu2 genomeSize=5.5m maxInputCoverage=100 -nanopore barcode02.fastq.gz
>tig00000001 len=4809766 reads=9586 class=contig suggestRepeat=no suggestBubble=no suggestCircular=yes trim=18041-4802966
>tig00000002 len=133387 reads=178 class=contig suggestRepeat=no suggestBubble=no suggestCircular=yes trim=12980-128391
>tig00000004 len=80969 reads=39 class=contig suggestRepeat=no suggestBubble=no suggestCircular=yes trim=8693-69430
>tig00000005 len=125703 reads=101 class=contig suggestRepeat=no suggestBubble=no suggestCircular=yes trim=5014-106502
>tig00000006 len=133052 reads=86 class=contig suggestRepeat=no suggestBubble=no suggestCircular=yes trim=7227-121662
>tig00000007 len=21217 reads=1 class=contig suggestRepeat=yes suggestBubble=no suggestCircular=no trim=0-21217
```

canu 2.2
CentOS

Valery

**Comment by skoren** [comment]
@valery-shap do you have more than 100x input coverage for your genome? If so, you've got non-deterministic read sampling down to 100x which would explain minor assembly differences like you're seeing. Once you account for trimming, you're always getting a 4.84mb contig and 115, 114, 100, and 60kb smaller contigs which are likely plasmids.

**Comment by skoren** [comment]
The duplication will appear and disappear with different downsampling of the reads. It depends where the circularization/end of the contig is. If the contig ends near your gene you get a duplication. If it falls somewhere else in the genome, another gene is duplicated but not the one you're checking so it's not visible. You can use the trim points listed in the contig header of your assembly or the FAQ has suggestions to align/remove overlaps via nucmer: https://canu.readthedocs.io/en/latest/faq.html#my-circular-element-is-duplicated-has-overlap

One other possibility is you have a non-clonal sample and there is a variant that is showing up in a secondary smaller contig  (that should have suggestRepeat=yes or suggestCircular=yes). You could try running purge_dups on the assembly (again on the FAQ: https://canu.readthedocs.io/en/latest/faq.html#my-genome-size-and-assembly-size-are-different-help. However, if you've got two large contigs and both are suggestCircular=yes and a gene is duplicated between them, I'd tend to trust that. Especially if it's happening across multiple assemblers.

**Comment by skoren** [comment]
Idle, original issue was due to random read subsampling.
