### ISSUE TITLE
canu command not found

### ISSUE THREAD

**Issue by ShaoyuanTan** [marbl/canu#204]
I installed canu from source code and it gave a "install success" information. Then I tried to run the assembler with: canu-1.3/*/bin/canu , it gave me some usage information and three error messages. Then I want to assemble sequence from nanopore using the code: 
canu \
 -p ecoli -d ecoli-oxford \
 genomeSize=4.8m \
 -nanopore-raw oxford.fasta
But I get canu command not found.
Can anybody help me with that?

![canu command not found](https://cloud.githubusercontent.com/assets/20542710/17039104/71fd41dc-4f5e-11e6-9d5f-1572db644286.PNG)

**Comment by brianwalenz** [comment]
You need to either add canu-1.3/*/bin to your path, or run the canu command using the full path every time.  Read up on 'bash path', e.g., https://kb.iu.edu/d/acar
