### ISSUE TITLE
canu on two clusters

### ISSUE THREAD

**Issue by gunjanpandey** [marbl/canu#2042]
Is it possible to run a single canu assembly on two different HPC clusters? 
For example, if there is a mid way run in one HPC cluster, is it ok to start the exactly same script again on a different cluster - in the same working and output directory.

**Comment by skoren** [comment]
I'm not sure what you mean by run a single assembly simultaneously on two clusters. I assume you mean running part of the assembly on one cluster, stopping it, then resuming it on another cluster. Yes, that is OK. It isn't OK to launch more than one assembly command using the same folder (-d option), no matter if it's on one cluster or not.
