### ISSUE TITLE
Contigs with few reads supported

### ISSUE THREAD

**Issue by csxie-666** [marbl/canu#2044]
Hi,
I used canu 2.1.1 to assembly my genome with HiFi data. 
The result contains so many contigs with few reads (reads < 20)
Among 2185 contigs , 1292 contigs have reads < 20 , and 316 contigs have only 1 reads.

Can I remove those contig ?

**Comment by skoren** [comment]
I expect many of those contigs are flagged as either suggestRepeat=yes or suggestBubble=yes or both. We typically recommend running purge_dups after HiFi assembly which will remove these but you can also remove the suggestBubble=yes contigs beforehand. Just note that depending on your genome's heterozygosity, the bubble list identified by the assembler may be incomplete.

**Comment by csxie-666** [comment]
Thanks! So if i want to assembly a haplotype-resolved genome, those contigs can be retained and used for subsequent construction of scaffolds？

**Comment by skoren** [comment]
You can't make a haplotype resolved genome from just hifi data, it's too short. The output is primary contigs and alts/bubbles so each of the large primary contigs will be switching between haplotypes arbitrarily. Running purge_dups just removes alts/bubbles not marked during assembly. Scaffolding won't break/fix the haplotype switches in the primary contigs.

**Comment by csxie-666** [comment]
Thank you for your suggestion. The species I assembled are extremely heterozygous, and the final assembly size is in line with the content estimated by flow cytometry. So should i still run the purge_dups to remove those contig?

**Comment by skoren** [comment]
Do you mean inline with the diploid size (e.g. human is 6gb not 3gb)? Either way, we've found it useful to run purge_dups and run it in all cases for the the VGP assemblies.
