### ISSUE TITLE
If it is possible to make CANU take more resources

### ISSUE THREAD

**Issue by amit4mchiba** [marbl/canu#2046]
Hi,

I am so sorry for asking this stupid question. I am working with a server, which has follwing specifications-
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              64
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7702P 64-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         2623.761
CPU max MHz:                     3353.5149
CPU min MHz:                     1500.0000
BogoMIPS:                        4000.14
Virtualization:                  AMD-V
L1d cache:                       2 MiB
L1i cache:                       2 MiB
L2 cache:                        32 MiB
L3 cache:                        256 MiB
NUMA node0 CPU(s):               0-127

I started a genome assembly using Canu, and using 90x genome coverage for a plant genome which has a size of 2Gb, and is highly hetrozygous. At the overlap stage of unitiging, it created over 800 jobs, and started running 8 jobs concurrently. I checked my computer resources, and it seems my server can take more jobs. 
(base) amit8riken@amit8riken:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:        1019519      127315       93811          38      798392      885169
Swap:          2047          52        1995

I wonder if it is possible to run more jobs or if I can run some of the jobs outside the script (meaning running indivisual jobs, and when Canu reaches to that stage, it will find the files and will not be required to do anything).

I am not sure if this make sense at all, so, please let me know and I will try to make my question more clear.

Thank you so much in advance,

with best regards
Amit

**Comment by hbadrane** [comment]
I run into the same problem as some folks: when CANU is run with default it gets stuck and terminates at the trimming phase (I didn't use correction). I had to use "useGrid=false" to be able to complete a run, but it took about 35 hours for a 12.5 Mb Genome, running as a Slurm on a cluster node. A few questions:
1- is the above runtime what normally it should take?
2- will using Grid (manually) make it faster?
3- Brian, could you please elaborate a little bit more on how to use "useGrid=remote"? Will CANU stop once it creates the array of scripts to be run manually? Should we restart CANU with "useGrid=remote" or else? Does this work for correction, trimming, and assembly?

**Comment by skoren** [comment]
1. Hard to say what's normal given we don't know input coverage, read type, or cores available on the node.
2. Using the grid is not much faster on small genomes because the jobs spend time just waiting to get scheduled. On larger genomes it's definitely faster.
3. Yes, canu stops and tells you what commands to submit. You can then edit the commands if you want and submit them and after they all finish, restart canu again as before. The useGrid=remote option is only really needed when you have a grid that doesn't support some feature (like array jobs) and typically you're better off letting Canu manage the jobs itself. I bet your initial run terminated due to time limits or similar and you could just add a longer time request using gridOptions rather than using remote.

**Comment by skoren** [comment]
Idle

**Comment by hbadrane** [comment]
Thanks
