### ISSUE TITLE
canu failed with 'failed to generate consensus.  Made 2 attempts, jobs still failed'.

### ISSUE THREAD

**Issue by bioramg** [marbl/canu#2048]
Hi,
I am assembling the plant mitochondrial genome using ONT sequences. I assembled the mitochondrial genome successfully with the following parameters:
canu -assemble -p xyz -d xyz-erate-0.039 genomeSize=1.16g errorRate=0.039 -nanopore-corrected ./canu_trim/ONT_trim.trimmedReads.fasta.gz

Again, I changed the error-rate parameter and re-run. But, I am getting an error. 
canu -assemble -p xyz -d xyz-erate-0.075 genomeSize=1.16g errorRate=0.075 -nanopore-corrected ./canu_trim/ONT_trim.trimmedReads.fasta.gz

```
-- BEGIN ASSEMBLY
--
-- Configured 100 contig and 40 unitig consensus jobs.
-- Consensus attempt 1 begins with 139 finished, and 1 to compute.
----------------------------------------
-- Starting concurrent execution on Mon Nov  1 12:04:37 2021 with 4765.351 GB free disk space (1 processes; 6 concurrently)

    /home/canu/canu-erate-0.075/unitigging/5-consensus/consensus.sh 36 > 
  /home/canu/canu-erate-0.075/unitigging/5-consensus/consensus.000036.out 2>&1

-- Finished on Mon Nov  1 12:05:43 2021 (66 seconds) with 4765.351 GB free disk space
----------------------------------------
--
-- 1 consensus jobs failed:
--   job  /home/canu/canu-erate-0.075/unitigging/5-consensus/ctgcns/0036.cns FAILED.
--
-- Consensus attempt 2 begins with 139 finished, and 1 to compute.
----------------------------------------
-- Starting concurrent execution on Mon Nov  1 12:05:43 2021 with 4765.351 GB free disk space (1 processes; 6 concurrently)

    /home/canu/canu-erate-0.075/unitigging/5-consensus/consensus.sh 36 >  /home/canu/canu-erate-0.075/unitigging/5-consensus/consensus.000036.out 2>&1

-- Finished on Mon Nov  1 12:06:48 2021 (65 seconds) with 4765.351 GB free disk space
----------------------------------------
--
-- 1 consensus jobs failed:
--   job  /home/canu/canu-erate-0.075/unitigging/5-consensus/ctgcns/0036.cns FAILED.
--
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'failed to generate consensus.  Made 2 attempts, jobs still failed'.
```
Could you please suggest solving this issue?

Thank you.

**Comment by brianwalenz** [comment]
If this isn't version 2.2, upgrade to that version.

Otherwise, post the contents of `/home/canu/canu-erate-0.075/unitigging/5-consensus/consensus.000036.out`.

**Comment by bioramg** [comment]
Please find the consensus.000036.out txt file.

[consensus.000036.out.txt](https://github.com/marbl/canu/files/7457107/consensus.000036.out.txt)

**Comment by skoren** [comment]
I'm not sure what version of Canu this is but it looks super old, it's still using gkpStore. My best guess is pre 1.7 which is years old. I'd dump this whole assembly and download the pre-build binaries for 2.2 from the releases page and run that from scratch. If you hit errors with that version, open a new issue.

**Comment by skoren** [comment]
Idle, outdated release.

**Comment by AndyLy2Zy** [comment]
Hi all,

I also encountered this issue. Is there anyone know how to fix it ? Thanks.

Best,
Yi

**Comment by skoren** [comment]
This issue was specific to a very old release of Canu. Your best option is to upgrade to the latest from the repo or wait for the next release and try that to see if it resolves your issue.
