### ISSUE TITLE
Canu hanging on mhap within 1-overlapper of correction step

### ISSUE THREAD

**Issue by halfwayBraindead** [marbl/canu#205]
While attempting to assemble the test ecoli dataset from the readthedocs page, I noticed that the 32-core, 64 GB test machine I'd been using had hung on the first major step of Canu, read correction, after 650+ CPU hours and roughly 24 hours of wall time.

Following further investigation, the main Canu logs did not seem to indicate any major errors, but within "ecoli-auto/correction/1-overlapper/", I found that the "mhap.000001.out" appeared incomplete:

 ```
% cat mhap.000001.out
Running block 000001 in query 000001
Running with these settings:
--filter-threshold = 5.0E-6
--help = false
--max-shift = 0.2
--min-olap-length = 116
--min-store-length = 0
--no-self = false
--no-tf = false
--num-hashes = 768
--num-min-matches = 2
--num-threads = 16
--ordered-kmer-size = 12
--ordered-sketch-size = 1536
--repeat-weight = 0.9
--settings = 0
--store-full-id = false
--supress-noise = 0
--threshold = 0.73
--version = false
-f = /home/aurash/canu/ecoli-auto/correction/0-mercounts/ecoli.ms16.frequentMers.ignore.gz
-h = false
-k = 16
-p =
-q = /home/aurash/canu/ecoli-auto/correction/1-overlapper/queries/000001
-s = /home/aurash/canu/ecoli-auto/correction/1-overlapper/blocks/000001.dat

Reading in filter file /home/aurash/canu/ecoli-auto/correction/0-mercounts/ecoli.ms16.frequentMers.ignore.gz.
Time (s) to read filter file: 0.27358649
Read in k-mer filter for sizes: [16]
Processing files for storage in reverse index...
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
```

Was wondering if anyone has had any experience with this type of issue? What might cause mhap to freeze up during the read correction process?

Thanks!

**Comment by brianwalenz** [comment]
What was the canu command line, and what did canu report (to the screen) for process sizes?

I'm going to guess there are too many mhap processes, and each process isn't getting enough memory - and that is known to make mhap run slow.  I run 12 threads and 6gb memory for ecoli mhap.

**Comment by halfwayBraindead** [comment]
The Canu command was practically identical to [that specified in the documentation](http://canu.readthedocs.io/en/stable/quick-start.html#correct-trim-and-assemble), with the addition of "useGrid=0". For the mhap process(es), Canu reported the following to stdout:

```
----------------------------------------
-- For mhap overlapping, set repeat k-mer threshold to 1157.
--
-- Found 115711421 16-mers; 89186744 distinct and 77230204 unique.  Largest count 37954.
--
-- OVERLAPPER (mhap) (correction)
--
-- Set corMhapSensitivity=high based on read coverage of 24.
--
-- PARAMETERS: hashes=768, minMatches=2, threshold=0.73
--
-- Given 6 GB, can fit 9000 reads per block.
-- For 3 blocks, set stride to 2 blocks.
-- Logging partitioning to '/home/aurash/canu/ecoli-auto2/correction/1-overlapper/partitioning.log'.
-- Configured 2 mhap precompute jobs.
-- Configured 2 mhap overlap jobs.
-- mhap precompute attempt 0 begins with 0 finished, and 2 to compute.
----------------------------------------
```

**Comment by skoren** [comment]
From the logs it looks like it is using 6GB/16 cores per each partition and there are only 2 partitions so very similar to what Brian had suggested and wouldn't have used more than 12GB of memory. 

What did the CPU usage/load on your system look like while the job was running, both precompute and mhap.sh should be CPU-bound so they should be using 1600 CPU. If they aren't there is an issue either with other jobs competing for resources on the node or I/O issues given that this full assembly should take under 2 cpu hours (0.5 of that for mhap).

**Comment by halfwayBraindead** [comment]
Hi skoren,

System CPU throughout the mhap job held around 70% of total system CPU, so I believe that would be around 2240 CPU. Seems strange that mhap didn't complete with 650+ CPU hours when it should only take 0.5!

**Comment by skoren** [comment]
As a sanity check, I'd run on another machine. The E. coli genome doesn't need many resources, I've run it on my laptop, 8gb and 4 cores should be sufficient to eliminate potential variables causing it to not finish.

**Comment by halfwayBraindead** [comment]
Definitely. My sysadmin will be reviewing his installation of the package in the coming days. Thanks for the feedback!

**Comment by brianwalenz** [comment]
No python dependencies.

**Comment by outpaddling** [comment]
Hi guys,

I'm the sysadmin who did the installation.

Looks like there was some sort of typo with the command or something amiss in the environment.  When I tried to reproduce the problem, everything worked fine for me, both from my account and from halfwayBraindead's.

Sorry for the distraction.

    Jason

**Comment by brianwalenz** [comment]
No worries.  This isn't the first time we've had bugs correct themselves.  Thanks for the update.
