### ISSUE TITLE
CANU Producing empty contigs.fasta file

### ISSUE THREAD

**Issue by sagnikbanerjee15** [marbl/canu#2050]
Hello,

I am working on a project where we sequenced a target region of the genome. The length of the target region is ~8.5Kb. The sample was sequenced on a Sequel II platform and CCS reads were reported by the vendor. I used those for assembly. The execution finishes without any error but generates an empty contigs.fasta file. Here is the command I used.

Canu command (version 2.2)
-----------------------------
`nohup canu -d 580421_canu -p 580421 genomeSize=9k -pacbio-hifi 580421.fastq cnsThreads=8 > 580421_canu.output 2> 580421_canu.error &`

I have attached the log files. 

Could you please look into this?

Thank you.
[canu_github_issue.zip](https://github.com/marbl/canu/files/7514537/canu_github_issue.zip)

**Comment by skoren** [comment]
You've probably got a single read containing the entire sequence so it's being demoted to unassembled. See the faq: https://canu.readthedocs.io/en/latest/faq.html#my-asm-contigs-fasta-is-empty-why. You can check the unassembled sequences or change the parameters as listed in the faq.

**Comment by sagnikbanerjee15** [comment]
Hi @skoren,

Thank you for your reply. I tried with the relaxed filter but it still produces no assembly.

Thank you.

**Comment by skoren** [comment]
Based on the logs, you've got no overlaps that aren't contained so there's nothing to assemble:
```
--  INITIAL EDGES
--  -------- ----------------------------------------
--       291 reads are contained
--    115735 reads have no best edges (singleton)
--         0 reads have only one best edge (spur) 
--                  0 are mutual best
--         0 reads have two best edges 
--                  0 have one mutual best edge
--                  0 have two mutual best edges
```

So really you don't need assembly just consensus. Canu isn't really designed for this type of use case where there's nothing for it to do. I'd just suggest using a standalone consensus tool, like racon, instead.

**Comment by sagnikbanerjee15** [comment]
HI @skoren,

Thank you for your reply. I was in fact hoping to do a consensus but I thought the assembly might yield similar results. Thank you for referring racon. I will give it a try.

Thank you.
