### ISSUE TITLE
empty and stuck *.mhap.ovb.WORKING

### ISSUE THREAD

**Issue by gushiro** [marbl/canu#2053]
While running my assembly, I noticed I have non-empty` *.mhap.ovb.WORKING` in `/run1/correction/1-overlapper/results/` . However, after I hit the space limit in the cluster, I noticed that new `*.mhap.ovb.WORKING` files are empty. I increase the space in the cluster and noticed that many non-empty `*.mhap.ovb.WORKING` files are "stuck" (not converted to *.ovb and *.oc files).
      Also, new *`.mhap.ovb.WORKING` files launched automatically in the cluster are non-empty, and one are already converted into *.ovb and *.oc files.

My question is: what should I do with those empty and stuck `*.mhap.ovb.WORKING ` files? The stuck files seem to be still running in the cluster.  In `/run1/correction/1-overlapper/ `  I can  also see `mhap.1960640_XX.out` (which correspond to a stuck `*.mhap.ovb.WORKING` file) still running (this file and others were created right after I  increased the space in the cluster).

PD: in `/run1/correction/1-overlapper/ ` I can see empty `*-pipe` files too

Thanks in advance.

**Comment by skoren** [comment]
It's possible the out of space FS error caused the jobs to stall writing. You can kill all your canu jobs and run, remove the intermediate files (anything with the WORKING suffix) and then re-start canu with the same command. It will continue and only re-run the jobs that failed originally.

**Comment by gushiro** [comment]
@skoren thanks. Should I also delete the empty `*.mhap.success` files in `/run1/correction/1-overlapper/results`?

**Comment by skoren** [comment]
No need to remove the success files if those have matching ovb outputs. Those completed.

**Comment by gushiro** [comment]
@skoren the empty `*.mhap.success` match the stalled `*WORKING` files. So I should delete them too I guess?

**Comment by skoren** [comment]
Yes, in that case you can delete them as well.

**Comment by skoren** [comment]
Idle
