### ISSUE TITLE
Can HiCanu perform "trim"?

### ISSUE THREAD

**Issue by 123long123** [marbl/canu#2055]
Hi, 

We all know Canu can perform correct, trim and assembly phase when we used pacbio CLR data. In the trim phase, canu may trim some suspicious regions such as remaining SMRTbell adapter as you described in Canu documents. Will HiCanu performed "trim" phase when I used HiFi data (--pacbio-hifi parameter) ? 

I found my some HiFi data have some adapters. How can I remove these ? Can you recommond some softwares for me ?

Thanks in advance. 

long

**Comment by skoren** [comment]
See the FAQ: https://canu.readthedocs.io/en/latest/faq.html#what-parameters-should-i-use-for-my-reads. You can specify `-untrimmed` which will run the trimming step before assembly on the HiFi reads.
