### ISSUE TITLE
tgTig::loadFromStream()-- not at a tigRecord

### ISSUE THREAD

**Issue by claumer** [marbl/canu#2056]
Hello,

I'm trying assemble a genome from which we got a bit lower-than-hoped-for counts of PacBio Hifi reads - genomescope tells me perhaps ~9x haploid coverage. I thought there might be some hope in trying to use all reads that were output from the flow cells we collected and assembling in PB CLR mode. I ran an assembly with the following command:

../../../canu-2.2/bin/canu maxInputCoverage=10000 corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0 redMemory=32 oeaMemory=32 batMemory=200 gridOptions="-q long" genomeSize=1g -p Pkin_canu_all -d Pkin_canu_all -pacbio ../Pkin_all.fastq.gz

(So here using the guidelines in the FAQs to use all reads and enforce stringent overlaps)

But unfortunately it seems that the assembly stops in the correction phase. After a couple of restarts (the original job submission had some overlap jobs die because the default submission queue kills after 8 hours running) the assembly 1-overlapping step in correction *seems* to finish, and it moves onto 2-correction, but then the job dies with the following error:

-- Finished on Mon Nov 22 14:24:08 2021 (3492 seconds) with 183484.057 GB free disk space
----------------------------------------

ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:

ABORT:
ABORT: canu 2.2
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to generate list of reads to correct.
ABORT:
ABORT: Disk space available:  183484.057 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (correction/2-correction/Pkin_canu_all.readsToCorrect.err):
ABORT:
ABORT:   tgTig::loadFromStream()-- not at a tigRecord, got bytes '<85>b^@^@' (0xffffff85620000).
ABORT:   Failed to load tig 1724320.
ABORT:

------------------------------------------------------------

I've tried deleting 2-correction and re-running but it just leads to the same failure as before. Is it clear what's happened here, and how to recover?

Thank you for your advice,

Regards,
Chris L

**Comment by skoren** [comment]
Idle
