### ISSUE TITLE
missing trimming and assemble file when using canu command

### ISSUE THREAD

**Issue by ShaoyuanTan** [marbl/canu#206]
When I ran the "canu  -p ecoli -d ecoli-oxford...." code according to canu quick start, I get a ecoli-oxford only containing some correction files. Also, I didn't find any fasta.gz in the correction file. 
![correction](https://cloud.githubusercontent.com/assets/20542710/17072100/5b13200e-502b-11e6-8ab3-8c5f61d78954.PNG)
I think I have installed canu successfully. But why it didn't run as expected? Do I need to install some other softwares? Can anybody help me with that? Thanks!

**Comment by brianwalenz** [comment]
What was the screen output from running canu?  This looks like it failed somewhere early.

Are there files/logging in canu-scripts?

If there is a grid involved, it might still be running there.

**Comment by ShaoyuanTan** [comment]
Hi,
Thank you so much!
The screen output is [image: Inline image 2][image: Inline image 3][image:
Inline image 4][image: Inline image 1]
Also I noticed that there are some requirements to run canu:

   - Java SE 8 +
   - GCC 4.5+ (for compilation only)
   - Filesys::Df Perl module (for binaries only, depending on perl version)
   - OS X 10.10 or newer (for binaries only)
   - Gnuplot (optional for generating HTML graphs)

Do I need to install all software above using module load... command?

Thanks,
Shaoyuan

**Comment by brianwalenz** [comment]
Unfortunately, attachments in email don't make it to the issue tracker.  You need to go to the issue web page and drag-and-drop any images to it.  Or send it as plain text.

Only Java is required to run.  Filesys::Df isn't needed anymore.  Gnuplot is nice, but optional.

Look for any errors in *.err or *.out files in the correction directory.
