### ISSUE TITLE
Haplotype assembly with HiFi data

### ISSUE THREAD

**Issue by taskent** [marbl/canu#2061]
We are trying to run a haplotype-aware assembly with HiFi data but we weren't sure whether we should run the correction and trimming steps first. Particularly, we were worried whether correction would somehow remove haplotypes and collapse reads to one haploid genome.
 
We are using canu v1.8 and working in a Linux environment.

Any input would be appreciated.

Thanks!

**Comment by skoren** [comment]
First, don't use Canu 1.8, that predates any HiFi development so you should update to v2.2. Run with -pacbio-hifi as documented: https://canu.readthedocs.io/en/latest/faq.html#what-parameters-should-i-use-for-my-reads. The correction and trimming steps aren't on for HiFi data as they aren't needed. You can manually enable trimming (again see the docs) but we don't recommend this unless your initial assembly is very fragmented or you know you have adapters (e.g. barcodes) added to your reads.

**Comment by taskent** [comment]
thanks!
