### ISSUE TITLE
Taking big space 

### ISSUE THREAD

**Issue by S-111** [marbl/canu#2063]
Hello!
I'm assembling a genome that predicted size is 1Gb.
Disk space is 23TB, but it was over the space during assembly.
It is difficult increasing the space...
Are there any files which I can delete?

**Comment by skoren** [comment]
See the suggestions in previous similar issues (e.g. #2028)

**Comment by S-111** [comment]
Thank you for your reply.
I confirmed # 2028.

I use canu 2.2. 
If I add the option to reduce space and I perform canu again, do all of analyses become to start over?

**Comment by skoren** [comment]
Yes, you have to restart from the beginning, assuming you haven't already generated corrected reads.

**Comment by S-111** [comment]
OK.
Thank you very much for your comment!

**Comment by skoren** [comment]
Idle
