### ISSUE TITLE
No output for a long time

### ISSUE THREAD

**Issue by wynhhh** [marbl/canu#2067]
Hello，
I am an absolute beginner.I am planning to try canu(v.2.2) using the B.taurus dataset to do trio binning assembly.

There are Illumina short-read sequencing pair-end files for parents (Angus_1.fasta, Angus_2.fasta and Brahman_1.fasta, Brahman_2.fasta). I merger these two fasta file into a single Angus (Brahman) fasta file, i use Angus.fasta(~52X Illumina coverage) and Brahman.fasta(~56X Illumina coverage), and F1_Sequel.fasta(~68× PacBio coverage for their male F1 offspring) as input files of TrioCanu.

For this command:
canu \
-p BOS -d bosTrio \
genomeSize=3g \
-haplotypeBrahman Brahman.fasta \
-haplotypeAngus Angus.fasta \
-pacbio F1_Sequel.fasta

My output directory looks like this:

![0](https://user-images.githubusercontent.com/28442418/146660020-df55a8c2-6320-4ab0-95d6-8e89b8ab9f95.png)

At present, the program is stuck in the place 'meryl' (meryl-count) and has not output any files for a long time. I would like to ask you whether my input parameters are missing or what other problems may exist.

![1](https://user-images.githubusercontent.com/28442418/146660034-7893b4bb-e5a2-4648-9525-68a36221871d.png)

![微信图片_20211211212146](https://user-images.githubusercontent.com/28442418/146660040-c93d0db8-5e9b-47e0-8884-89d64e81a530.png)
Any input would be appreciated.
Thanks!

**Comment by skoren** [comment]
If there's no error reported, then the jobs are running and there's nothing to do. You can look at their individual output files and/or the load on your system to see how much CPU they are using.

**Comment by skoren** [comment]
Idle
