### ISSUE TITLE
Option not to check for submit node when using `useGrid=remote`?

### ISSUE THREAD

**Issue by xgrau** [marbl/canu#2068]
Hi,

I am using the `useGrid=remote` option in Canu v2.2 so that it prepares `qsub` submission scripts, which I then execute manually on my local cluster. However, the intermediate steps between the parallelised parts of the pipeline  are sometimes a bit computationally intensive (e.g. the seqStore building step), which, due to the configuration of my cluster (which I'm not managing myself), often results in halted jobs due to excess resource usage. In a normal scenario, I would use the `useGrid=true` option, but this is not possible because my `qsub` configuration prevents me from launching nested qsub jobs.

A possible workaround to this issue would be running these intermediate steps as independent `qsub` jobs and keep launching the generated submission scripts manually, but this is apparently only not possible, as the following error appears when launching `canu` from a compute node:

`error: denied: host "XXXX" is neither submit nor admin host`

Given that I'm using `useGrid=remote` and are therefore not interested in using the current node as a submit node, this check seems unnecessary. Is there any way of disasbling it, or any other workaround to this issue? Thanks a lot in advance.

Find my log attached below.

Any tips will be appreciated.

Cheers

Xavi

```
###
###  Reading options from '/nfs/users2/asebe/xgraubove/Programes/canu-2.2/bin/canu.defaults'
###

# Add site specific options (for setting up Grid or limiting memory/threads) here.

###
###  Reading options from the command line.
###

genomeSize=300m
useGrid=remote
gridEngineResourceOption=-pe smp 16 -l virtual_free=90G,h_rt=720:00:00 -q long-sl7
minReadLength=1000
corOutCoverage=200
batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50
correctedErrorRate=0.105
```

**Comment by skoren** [comment]
Sorry for not replying earlier. The check is coming from the grid engine itself not Canu, and is coming from resource polling (to figure out what nodes are available/etc). The useGrid=remote is designed to run on a head node and doesn't actually do any compute. You can then run the submit commands it provides as independent jobs to proceed through the run.
