### ISSUE TITLE
overlapInCore

### ISSUE THREAD

**Issue by dagi34** [marbl/canu#2074]
[CANU_ONT_arabidopsisAll.pdf](https://github.com/marbl/canu/files/7804157/CANU_ONT_arabidopsisAll.pdf)
Dear All,

I am trying to assemble ONT reads from Arabidopsis using nodes controlled by Slurm. The assembly got stuck with overlapInCore for several days. I attach the .sh code, the .out file and the output of the top command in a pdf document. If you please how can I modify the .sh code so that this problem is overcome. I am rather new to bioinformatics. Thank you.

**Comment by skoren** [comment]
Not sure this version this is but looks super old, we haven't had the errorRate parameter for a long time, my guess is this is v1.6. Setting the error rate to 0.144 as you did makes the actual error computation much higher than this which is likely why the assembly is taking so long. The equivalent in this old version to correctedErrorRate of 0.144 would be something like 0.05 

I wouldn't use such an old version though. Instead, download the latest release binary for your system from here: https://github.com/marbl/canu/releases/tag/v2.2, provide the full path to wherever you extracted it, and use the default parameters for ONT data. You may also be able to run an uncorrected assembly as listed in the quick start: https://canu.readthedocs.io/en/latest/quick-start.html#assembling-with-multiple-technologies-and-multiple-files.

**Comment by dagi34** [comment]
Dear Dr Koren,

Thanks a lot for your prompt reply. I will try your suggestions.
The actual version I have is 1.4. May I draw your attention to the fact
that I did the installations on the nodes recently via Conda. So it seems
the version available there is very old.

Yours truly

**Comment by skoren** [comment]
We don't officially support or recommend conda for installations. However, bioconda definitely has v2.2 available for Linux + OS X, I've installed it from there recently. Not sure why/how it's pulling 1.4 since I don't use conda much.

**Comment by dagi34** [comment]
Dear Sergey,

Thanks a lot for your help.

Regards
