### ISSUE TITLE
Overlap jobs failed with both canu v1.9 and v2.2

### ISSUE THREAD

**Issue by Xuerlock** [marbl/canu#2077]
Hi, I used the following command in the Linux system to assemble the yeast genome with 'genome size = 12m' and 'data coverage ～ 60X':
_xxx_/tools/canu-2.2/bin/canu -d canu_60x -p canu_60x genomeSize=12m -nanopore-raw _xxx_/s288c_3g_60x.fa useGrid=false rawErrorRate=0.500 corErrorRate=0.144 maxThreads=40

However, the canu stopped mainly due to:
'''
Overlap jobs failed, tried 2 times, giving up.
--   job unitigging/1-overlapper/001/000004.ovb FAILED.
--   job unitigging/1-overlapper/001/000005.ovb FAILED.
'''
I tried canu v1.9 and canu v2.2, both of them failed for the same reason. The error file of the canu v2.2 was attached below.
[9277081_err.txt](https://github.com/marbl/canu/files/7880251/9277081_err.txt)

**Comment by skoren** [comment]
Post the logs from the failing jobs, `canu_60x /unitigging/1-overlapper/overlap.000004.out` and/or `overlap.000005.out`

**Comment by Xuerlock** [comment]
> 发布失败作业的日志，`canu_60x /unitigging/1-overlapper/overlap.000004.out`和/或`overlap.000005.out`
[overlap.000004_5.zip](https://github.com/marbl/canu/files/7887244/overlap.000004_5.zip)
It seems that the error is due to the file **000005.ovb.WORKING** in the canu_60x /unitigging/1-overlapper/001/, which has the **WORKING** suffix ( **000004.ovb.WORKING and 000005.ovb.WORKING** ) while others haven't ( 000001.ovb, 000002.ovb, and 000003.ovb ).  So I also uploaded the  _canu_60x /unitigging/1-overlapper/001/000004.ovb.WORKING_. Thank you very much for your kindly help!

**Comment by skoren** [comment]
Hmm, it looks like the jobs finished but crashed after being done:
```
Thread 01 writes    reads 36109-36720 (1258 overlaps 1258/20846/0 kmer hits with/without overlap/skipped)
Bye.

Failed with 'Segmentation fault'; backtrace (libbacktrace):
utility/src/utility/system-stackTrace.C::82 in _Z17AS_UTL_catchCrashiP7siginfoPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
util/transmit.c::73 in __XALT_transmit_xalt_1_5()
libxalt/run_submission.c::194 in __XALT_run_submission_xalt_1_5()
libxalt/xalt_initialize.c::1061 in __XALT_myfini_LD_PRELOAD_xalt_1_5()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
./overlap.sh: 行 137: 360323 段错误               $bin/overlapInCore -t 8 -k 22 -k ../0-mercounts/canu_60x.ms22.dump --hashbits 22 --hashload 0.8 --maxerate 0.12 --minlength 500 $opt -o ./$job.ovb.WORKING -s ./$job.stats ../../canu_60x.seqStore
```

It's possible you may be able to rename the WORKING file to ovb and continue the run. I'd try that first and then restart Canu.

**Comment by brianwalenz** [comment]
You might want to alert your cluster admins to this.  The crash is in cluster monitoring software (https://github.com/xalt/xalt; https://xalt.readthedocs.io/en/latest/) outside of Canu.

**Comment by Xuerlock** [comment]
> You might want to alert your cluster admins to this. The crash is in cluster monitoring software (https://github.com/xalt/xalt; https://xalt.readthedocs.io/en/latest/) outside of Canu.

Sorry I still don't know how to fix this problem, I tried to load the **xalt** by **_module load xalt/2.9.8_**, however, the same error happened again. Do I need to update xalt to the latest version?

**Comment by Xuerlock** [comment]
I tried not loading the XALT by the code **_module purge_** before the canu run, and the assembly was completed in one step!  Thanks very much for your help, although this error is out of canu :)
