### ISSUE TITLE
Trio bin F1 ONT reads using parental Pacbio HIFI data?

### ISSUE THREAD

**Issue by TrentPrall** [marbl/canu#2081]
Hello,

I have a trio dataset with 30x coverage of ONT long reads and 30x coverage of pacbio HIFI data for all three samples in the trio. 
Is it possible to bin the F1 ONT reads and/or F1 HIFI reads by substituting parental HIFI reads in place of parental Illumina reads? If so, how would you go about running this?

Forgive me if this has already been addressed but I haven't seen an answer in the issues/documentation.

Thank you.

**Comment by TrentPrall** [comment]
Thank you for the info. I have tried following the work around instructions for running canu-trio with pb hifi data but when I run the following command there are no scripts created and the data isn't binned. Any thoughts to what may be occurring?

```
docker run -it -u 0 -v $(pwd):/scratch -w /scratch staphb/canu:latest \
canu -haplotype \
-p cy0695.pacbio \
-genomeSize=1m \
-haplotypecy0355 cy0355.pacbio.kir.fastq.gz \
-haplotypecy0161 cy0161.pacbio.kir.fastq.gz \
-pacbio-raw cy0695.pacbio.kir.fastq.gz
```

Here's the error:
```
-- BEGIN HAPLOTYPING
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'hap' concurrent execution on Wed Feb 16 05:10:43 2022 with 4666.686 GB free disk space (1 processes; 10 concurrently)

    cd haplotype
    ./splitHaplotype.sh 1 > ./splitHaplotype.000001.out 2>&1

-- Finished on Wed Feb 16 05:10:44 2022 (one second) with 4666.686 GB free disk space
----------------------------------------
--
-- Haplotyping jobs failed, retry.
--   job 1 FAILED.
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'hap' concurrent execution on Wed Feb 16 05:10:44 2022 with 4666.686 GB free disk space (1 processes; 10 concurrently)

    cd haplotype
    ./splitHaplotype.sh 1 > ./splitHaplotype.000001.out 2>&1

-- Finished on Wed Feb 16 05:10:44 2022 (in the blink of an eye) with 4666.686 GB free disk space
----------------------------------------
--
-- Haplotyping jobs failed, tried 2 times, giving up.
--   job 1 FAILED.
--

ABORT:
ABORT: canu 2.2
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT: Disk space available:  4666.686 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (haplotype/haplotype.log.WORKING):
ABORT:
ABORT:
```

Thanks again.

**Comment by skoren** [comment]
What's in the splitHaplotype.000001.out log?

**Comment by TrentPrall** [comment]
Here is the log:

```
cat splitHaplotype.000001.out 

Found perl:
   /usr/bin/perl
   This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi

Found java:
   /usr/bin/java
   openjdk version "1.8.0_292"

Found canu:
   /canu-2.2/bin/canu
   canu 2.2

Running job 1 based on command line options.
--
-- Loading haplotype data, using up to 4 GB memory for each.
--

For 69656 distinct 15-mers (with 11 bits used for indexing and 19 bits for tags):
    0.000 GB memory for kmer indices -         2048 elements 64 bits wide)
    0.000 GB memory for kmer tags    -        69656 elements 19 bits wide)
    0.000 GB memory for kmer values  -        69656 elements  7 bits wide)
    0.000 GB memory

Will load 69656 kmers.  Skipping 291816 (too low) and 0 (too high) kmers.
Allocating space for 85784 suffixes of 19 bits each -> 1629896 bits (0.000 GB) in blocks of 32.000 MB
                     85784 values   of 7 bits each -> 600488 bits (0.000 GB) in blocks of 32.000 MB
Loaded 69656 kmers.  Skipped 291816 (too low) and 0 (too high) kmers.
--   loaded 69656 kmers.

For 0 distinct 15-mers (with 0 bits used for indexing and 30 bits for tags):
    0.000 GB memory for kmer indices -            1 elements 64 bits wide)
    0.000 GB memory for kmer tags    -            0 elements 30 bits wide)
    0.000 GB memory for kmer values  -            0 elements  0 bits wide)
  2147483648.000 GB memory

--   loaded 0 kmers.
-- Data loaded.
--
-- Processing reads in batches of 100 reads each.
--

Failed with 'Segmentation fault'; backtrace (libbacktrace):

Failed with 'Segmentation fault'; backtrace (libbacktrace):
utility/src/utility/system-stackTrace.C::82 in _Z17AS_UTL_catchCrashiP7siginfoPv()
Segmentation fault (core dumped)
```

**Comment by skoren** [comment]
It looks like one of your haplotypes is empty (or at least had no kmers). That might be an issue with the input data. Post the `splitHaplotype.*.sh`script and the contents of your `0-kmers`, specifically the starts of the `*statistics` files.

**Comment by brianwalenz** [comment]
I think what happened is that the second haplotype has no mers unique to it.  These are in `0-kmers/haplotype-cy0161.meryl` and `0-kmers/haplotype-cy0161.meryl`.  You can confirm this by generating statistics for each with `{path_to_canu}/bin/meryl statistics {hap}.meryl | head -n 20`.  The stats shown before were for the reads themselves, before filtering for unique-to-haplotype kmers (and they look fine).

What to do next, I don't know.

**Comment by skoren** [comment]
I'd suggest running Merqury (https://github.com/marbl/merqury) and getting statistics on the resulting k-mer databases just as a sanity check on Canu's run. It will also give more intermediate databases than Canu to check counts. The resulting databases are compatible with Canu so you could still run splitHaplotype but give it the DBs from merqury.

If indeed there are no k-mers unique to one parent, that implies an issue with the parental sequencing or incorrect parentage. If the parental data is very low coverage (<15x) it may help to get more sequencing. Otherwise, it's likely you can't use these parents to trio-bin the data.

**Comment by skoren** [comment]
Idle
