### ISSUE TITLE
massive .part file = failed consensus

### ISSUE THREAD

**Issue by shaferab** [marbl/canu#2083]
Hi, I have ~45x HiFi data (2.7 GB genome). I use the grid option but often run individual sbatch scrips due to some incompatibilities with slurm (i.e. submitting 4000 jobs or oom events). It's worked well and I'm on the consensus phase; however, one of my partition files is 38G, more than double the next closes. This variation has led me to run indivdiual consensus jobs for 57 arrays.  This particular file is getting ooms but now running at 32 CPUs @8G per. 

I guess my question is does this seem out of the ordinary? And it's not clear to me if I can pick up from XXX.cns.WORKING if this times out? And if so, is that from the general canu script or the one specific to the module (below). Much appreciated.

```
  sbatch \
  --cpus-per-task=32 --mem-per-cpu=8G --account=rrg-shaferab --time=1-23:59:00 -o consensus.%A_%a.out \
  -D `pwd` -J "cns_Sc" \
  -a 52 \
  `pwd`/consensus.sh 0 \
> ./consensus.jobSubmit-01.out 2>&1
```

**Comment by skoren** [comment]
It's strange to have 4000 jobs for such a small genome and low coverage. Can you post the report file to see what the data/assembly look like?

Consensus typically does have a larger partition because one gets all the small contigs which run faster individually. The steps are all atomic so if it fails, you'd have to restart the consensus from scratch for that job. You can modify the portioning parameters to create more jobs but then you'd have to re-run all the partitions. I'd let the job run and see what progress it is making.

**Comment by skoren** [comment]
The report says 195x not 45x that you had mentioned originally. That doesn't look like HiFi data though, it's way too long and there's almost no peak in the histogram. The assembly is also quite fragmented. It also looks like you're running with higher error rate and coverage than the defaults for HiFi data, what's your full command?

**Comment by shaferab** [comment]
Okay. Here is the data output from the sequencing facilty

Name	HiFi_Reads	HIFi_BP	HiFi_mean_len
SC7_HTpool_42PM_CELL2	1,316,217	19,255,575,399	14,629
SC7_HTpool_50PM_CELL1	1,339,709	19,554,913,662	14,596
SC7_HTpool_33PM_CELL3	1,780,469	26,160,968,655	14,693
SC7_HTpool_33PM_CELL4	1,810,309	26,597,809,556	14,692
SC7_HTpool_33PM_CELL5	1,654,212	24,236,775,031	14,651

Command below. But I think it seems like we might have read in the CLR or additioanl data somehow. Sounds like I should restart from the beginning? Before that - command below:

module load gcc/9.3.0 
module load canu/2.2

canu \
  -p Sc -d Sc-pacbio_2nodes \
  genomeSize=2.7g \
  -pacbio-hifi  HiFi_reads/trim-cell[1-5]* \
  correctedErrorRate=0.035 \
  utgOvlErrorRate=0.065 \
  trimReadsCoverage=2 \
  trimReadsOverlap=500 \
  -maxMemory=128G \
  -maxThreads=64 \
  -executiveMemory=16 \
  gridOptions="--account=rrg-shaferab --cpus-per-task=32 --time=05:59:00"

**Comment by skoren** [comment]
Yeah, I'd restart from the beginning. I think what you have is the SequelIe output which outputs 1 read per ZMW, even if it's a CLR read. Filter the files for Q20 reads first. You also shouldn't need the `correctedErrorRate=0.035 utgOvlErrorRate=0.065 trimReadsCoverage=2 trimReadsOverlap=500` parameters then.

**Comment by shaferab** [comment]
for q20 reads - that extracts reads that have an average Q>20, so I can use any QC program?

Much appreciated your quick and detailed feedback, I imagine this will run much smoother once I get rid of the garbage.

**Comment by skoren** [comment]
I've used the PacBio dataset command before: `https://www.pacb.com/wp-content/uploads/SMRT_Tools_Reference_Guide_v10.1.pdf`, see page 15. I assume other tools would work. If you have the BAMs for the cells, there should be a tag indicating QV for each read as well that you can use to filter.

**Comment by skoren** [comment]
Idle, input was not HiFi data and likely needed filtering.
