### ISSUE TITLE
Cannot create job info file. Job not submitted.

### ISSUE THREAD

**Issue by xhzy940301** [marbl/canu#2086]
Hi!
I run a canu job on computer cluster, when the job runs to unitigging, it broken and report "Cannot create job info file. Job not submitted." Where might the problem lie?

Your best

**Comment by skoren** [comment]
That doesn't seem like a canu error but a cluster error: https://www.ibm.com/support/pages/error-message-cannot-create-job-info-file-job-not-submitted (assuming you're using LSF).

Post the canu.out log that will have more information including the command it tried to submit. You can also try manually submitting the command again to see if it was a transient grid issue.
