### ISSUE TITLE
location of corrected HiFi reads

### ISSUE THREAD

**Issue by justdx** [marbl/canu#2088]
Hi, there. Thank you for developing such nice tool :).
I'm assembling a plant genome with PacBio HiFi reads using canu-2.2. I am wondering under which path can I find the corrected reads or how can I extract them? Thanks ahead for the reply.

**Comment by skoren** [comment]
The corrected reads are never instantiated, their corrections are only used to update overlap identities. You can manually run a command to dump the reads (see https://github.com/snurk/sg_sandbox/blob/master/src/canu_launch/fix_errors.sh) as long as you still have your seqStore and your intermediate outputs but the reads will be in homoopolymer-compressed space.
