### ISSUE TITLE
The understanding of the parameters "corMaxEvidenceCoverageGlobal", "corMaxEvidenceCoverageLocal"

### ISSUE THREAD

**Issue by SarahIsme** [marbl/canu#2093]
Sorry for this easy question, but I am confused by these two parameters.

The explainations of thses two parameters are `Limit reads used for correction to supporting at most this coverage` and `Limit reads being corrected to at most this much evidence coverage` in [parameter-reference](https://canu.readthedocs.io/en/latest/parameter-reference.html). In #634, these two parameters were suggested to be set as 10 in metagenomics.  I am confused by the explainations.

Suppose we set `corMaxEvidenceCoverageGlobal` and `corMaxEvidenceCoverageLocal` as 5 and 10, respectively. If the reads A, B, C, D, E and F can overlap with each other, and the estimated genome size is 5M. The coverage is the sum length of A-F divided by 5M. In my understanding, if the coverage is less than 5, read correction is performed, and if the coverage is greater than 5, no read correction is performed. Furthermore, if read correction is performed, the correction will only be stop when the coverage after correction (that is the sum length of corrected A-F divided by 5M) is no longer improved or higher than 10. Is my understanding right?

For another question, the [parameter-reference](https://canu.readthedocs.io/en/latest/parameter-reference.html) shows `By default, only the longest 40X of data (based on the specified genome size) is used for correction`. The 40X should be the coverage,  which is easily understanding. But how to understand the longest, a single read?

Thanks in advance!

Sarah

**Comment by skoren** [comment]
I think you're confusing those parameters with `corOutCoverage` which controls how much corrected data is output. Read correction is always performed, it's just a question of which reads get selected to be corrected. This is what `corOutCoverage` controls. So in your example above, if it's set to 5 and you have 5x all reads would be selected for correction. If it's set to 2 and you have 5x, only the longest 2x of reads would be corrected while the rest are dropped. To select longest, a read's corrected length is estimated based on its overlaps and all reads are sorted in reverse order by length (greatest to smallest). Reads are selected for correction until the total length exceeds the requested coverage.

The above two parameters control how each individual read is corrected. The first, `corMaxEvidenceCoverageGlobal` specifies how many best-buddies each read is allowed to correct. In your example,  if the coverage is 5, each read would be allowed to pick it's 5 best overlaps (based on identity*length). Only these buddies can be used for correction. This helps prevent over-correction of repeats. The second, `corMaxEvidenceCoverageLocal` is mostly a performance optimization and just avoids having a large pileup of reads in one location. So in your example, say read A picked BCDE as it's best buddies. Read F would then not be allowed to use A for correction.

**Comment by SarahIsme** [comment]
Thanks for your clear reply!

I have other questions. For metagenomics, there will be some sequences that do not overlap. For example, A-F can overlap each other, and G-L can overlap each. Therefore, the calculation of coverage uses the sum length of A-F or A-L? 

Other question is about the parameters in metagenomic analysis. In [FAQ](https://canu.readthedocs.io/en/latest/faq.html), the suggested parameters are `maxInputCoverage=10000 corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0 redMemory=32 oeaMemory=32 batMemory=200`. However, in #634 , the suggested parameters are `corMinCoverage=0' corOutCoverage=all corMhapSensitivity=high 'correctedErrorRate=0.105' 'genomeSize=5m' 'corMaxEvidenceCoverageLocal=10 corMaxEvidenceCoverageGlobal=10 oeaMemory=32' 'redMemory=32' batMemory=200`. Therefore, if I set `maxInputCoverage=10000` and `corOutCoverage=all ` as 10000 and all, respectively, can all reads be corrected and assembled?

The final quesition is how to use parameter `fast`, canu v2.2 may not recognize this parameter.

Thanks in advance!

Sarah

**Comment by skoren** [comment]
The coverage is global so if it's set to 10, every read is allowed to pick 10 other reads. That's why it was set low for metagenomics but I think in practice we didn't find it made much difference so it's not on the FAQ. The other differences between the parameters is that maxInputCoverage didn't exist when #634 was opened. corOutCoverage=all or corOutCoverage=10000 should be equivalent.

As for fast, you just add it as an option, it's recognized in v2.2:
```
% canu -fast -p asm -d test -nanopore pass.2d.fasta useGrid=false genomeSize=50k
-- canu 2.2
--
-- CITATIONS
--
-- For 'standard' assemblies of PacBio or Nanopore reads:
--   Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
--   Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
--   Genome Res. 2017 May;27(5):722-736.
--   http://doi.org/10.1101/gr.215087.116
--
-- Read and contig alignments during correction and consensus use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
--
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
--
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
--
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
--
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_11' (from '/usr/local/Java/jdk1.8.0_11/bin/java') with -d64 support.
-- Detected gnuplot version '5.4 patchlevel 0   ' (from 'gnuplot') and image format 'png'.
--
-- Detected 8 CPUs and 61440 gigabytes of memory on the local machine.
--
-- Detected Slurm with 'sinfo' binary in /usr/local/slurm/bin/sinfo.
--          Slurm disabled by useGrid=false
--
-- Local machine mode enabled; grid support not detected or not allowed.
--
--                                (tag)Concurrency
--                         (tag)Threads          |
--                (tag)Memory         |          |
--        (tag)             |         |          |       total usage      algorithm
--        -------  ----------  --------   --------  --------------------  -----------------------------
-- Local: meryl     12.000 GB    4 CPUs x   2 jobs    24.000 GB   8 CPUs  (k-mer counting)
-- Local: hap        8.000 GB    4 CPUs x   2 jobs    16.000 GB   8 CPUs  (read-to-haplotype assignment)
-- Local: cormhap    6.000 GB    8 CPUs x   1 job      6.000 GB   8 CPUs  (overlap detection with mhap)
-- Local: obtmhap    6.000 GB    8 CPUs x   1 job      6.000 GB   8 CPUs  (overlap detection with mhap)
-- Local: utgmhap    6.000 GB    8 CPUs x   1 job      6.000 GB   8 CPUs  (overlap detection with mhap)
-- Local: cor        -.--- GB    4 CPUs x   - jobs     -.--- GB   - CPUs  (read correction)
-- Local: ovb        4.000 GB    1 CPU  x   8 jobs    32.000 GB   8 CPUs  (overlap store bucketizer)
-- Local: ovs        8.000 GB    1 CPU  x   8 jobs    64.000 GB   8 CPUs  (overlap store sorting)
-- Local: red       16.000 GB    4 CPUs x   2 jobs    32.000 GB   8 CPUs  (read error detection)
-- Local: oea        8.000 GB    1 CPU  x   8 jobs    64.000 GB   8 CPUs  (overlap error adjustment)
-- Local: bat       16.000 GB    4 CPUs x   1 job     16.000 GB   4 CPUs  (contig construction with bogart)
-- Local: cns        -.--- GB    4 CPUs x   - jobs     -.--- GB   - CPUs  (consensus)
--
-- Found untrimmed raw Nanopore reads in the input files.
```
but keep in mind fast will likely give a less continuous assembly.

**Comment by SarahIsme** [comment]
I forget to add `-` before `fast`.

In FAQ, `maxInputCoverage` was set as 10000 for metagenomes, but the default value is 200.  Does this parameter significantly affect the number of the reads being corrected and assembled?

**Comment by skoren** [comment]
Yes, you definitely need to set maxInputCoverage since you want to keep all data in metagenomes. By default, only a random 200x subset of data would be kept. Unless you have a very low coverage metagenome,  you'd lose a lot of data without it.

**Comment by SarahIsme** [comment]
Thank you very much for your patient answer!

I think `maxInputCoverage` is enough, when the reads are 12G and the estimated genome size is 3M.
