### ISSUE TITLE
co-assembly of nanopore reads

### ISSUE THREAD

**Issue by Duannai** [marbl/canu#2095]
Thanks for developing this tool!

I have two nanopore read files from sequential sampling, and I want to perform a co-assembly.

So should I set `-nanopore-raw A.fastq -nanopore-raw B.fastq` or first `cat A.fastq B.fastq > C.fastq` and then `-nanopore-raw C.fastq`?

Thanks in advance!

Mort

**Comment by skoren** [comment]
You can provide wildcards to canu (see https://canu.readthedocs.io/en/latest/quick-start.html#assembling-with-multiple-technologies-and-multiple-files). So `-nanopore-raw [AB].fastq` or `-nanopore-raw *.fastq` would work.
