### ISSUE TITLE
RE: Interpretation

### ISSUE THREAD

**Issue by Malabady** [marbl/canu#2096]
Hi,

- In my assembly of large plant genome I used the following option, as recommended in the readthedocs of Canu, to avoid collapsing the haplotypic sequences:
''bat0ptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50''

I am happy with the results. Now I am writing the manuscript and need to explain in words the meaning of these options. Could you explain them to me, please? 

- the unassembled reads: are they reads with error, low coverage, low overlap with other reads, etc.. or are they good reads but not needed because of the coverage threshold. in other words, what are canu's criteria of the unassembled reads? 

FYI, this assembly was done using Canu 1.8. 

Many thanks,
Magdy

**Comment by skoren** [comment]
As far as bat options see #2090. For unassembled reads, see this FAQ: https://canu.readthedocs.io/en/latest/faq.html#my-asm-contigs-fasta-is-empty-why along with the description here: https://canu.readthedocs.io/en/latest/parameter-reference.html#output-filtering. So they're suspect reads/contigs that have low coverage or few reads.
