### ISSUE TITLE
Node Oversubscription?

### ISSUE THREAD

**Issue by Botantisty** [marbl/canu#2097]
Hello CANU team,

First, thank you for your continuing work on CANU. It has been a great program to work with. 

I am having issues with CANU oversubscribing to the nodes of our HPC and I need some guidance on how to set the restrictions to prevent this. 

I have tried limiting CANU's memory (e.g. maxMemory=60G) and threads (e.g. maxThreads=16), however, CANU submits 137 - 1 slot/core jobs at the start of the cormhap stage and these jobs seem to require more processing power than requested as the nodes running these jobs rapidly rise to 300-500X load and go into alarm. Then I am contacted to kill the run. Or alternatively, if they don't notice/ask me to kill CANU, it seems like the node can become unresponsive and the build stalls because the jobs on the node are lost on reset.

The cluster is running an SGE system (Rocks 7.0 (Manzanita)). I am trying to use CANU 2.2. on Linux to assemble a 630m genome using PacBio and ONT data. 

The latest version of the command I am using is:  
```
../canu-2.2/bin/canu -java=$JAVA -p Sar_CANU22_Feb072022 -d "../Assembly/New/" genomesize=630m gridEngineResourceOption="-l mem_free=MEMORY" minReadLength=15000 maxMemory=60G maxThreads=16  corMhapFilterThreshold=0.0000000002 corMhapOptions="--threshold 0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50" mhapMemory=60g mhapBlockSize=500 ovlMerDistinct=0.975 gridOptions="-S /bin/bash" -nanopore "../ONT/S_arvensis_pass_2021.fastq.gz" -pacbio "../PacBio/PB_Sarvensis_longest_bedtools_Feb2022.fq.gz"
```

CANU seems to be detecting the parameters of the cluster correctly:

```
	-- Detected 16 CPUs and 1008 gigabytes of memory on the local machine.
	--
	-- Detected Sun Grid Engine in '/opt/gridengine/default'.
	-- No Sun Grid Engine parallel environment detected in gridEngineResourceOption.
	-- User supplied Memory Resource      'mem_free'.
	-- 
	-- Sun Grid Engine support detected.  Resources available:
	--     13 hosts with  80 cores and 1007 GB memory.
	--      6 hosts with 128 cores and 3072 GB memory.
	--
	-- Job limits:
	--     60 gigabytes memory  (maxMemory option).
	--     16 CPUs              (maxThreads option).
	--
	--                         (tag)Threads
	--                (tag)Memory         |
	--        (tag)             |         |  algorithm
	--        -------  ----------  --------  -----------------------------
	-- Grid:  meryl     24.000 GB    8 CPUs  (k-mer counting)
	-- Grid:  hap       12.000 GB   16 CPUs  (read-to-haplotype assignment)
	-- Grid:  cormhap   60.000 GB   16 CPUs  (overlap detection with mhap)
	-- Grid:  obtovl    16.000 GB   16 CPUs  (overlap detection)
	-- Grid:  utgovl    16.000 GB   16 CPUs  (overlap detection)
	-- Grid:  cor        -.--- GB    4 CPUs  (read correction)
	-- Grid:  ovb        4.000 GB    1 CPU   (overlap store bucketizer)
	-- Grid:  ovs       16.000 GB    1 CPU   (overlap store sorting)
	-- Grid:  red       32.000 GB    8 CPUs  (read error detection)
	-- Grid:  oea        8.000 GB    1 CPU   (overlap error adjustment)
	-- Grid:  bat       60.000 GB   16 CPUs  (contig construction with bogart)
	-- Grid:  cns        -.--- GB    8 CPUs  (consensus)
	--
	-- Found untrimmed raw PacBio CLR and Nanopore reads in the input files.
	--
	-- I appear to be task  in a job array, unsetting SGE_TASK_ID.
```

I am also a little puzzled over why this issue is arising now as I have been using CANU to build genomes since 2015. I have even run 2.2 on this genome, though it failed at a later step from a lack of disk space and 2.1.1 successfully, but with less data. Is this a function of the amount of data or the genome size?  (Or did they just not notice the machines had high load?)

Thanks - I appreciate any guidance you can offer,
Sara

**Comment by skoren** [comment]
The maxMemory/maxThreads limits applies on a per-job basis on the array so each of your jobs will be limited to this but it can still submit arrays of those jobs.

 I'd guess the oversubscription is due to missing resource reservation. Your command specifies ` gridEngineResourceOption="-l mem_free=MEMORY"` but that will only reserve memory, not threads. So a node with 80 cores will end up with 80 16-core jobs not 5 as it should. You should add whatever parallel environment your grid uses (look for one using qconf -spl to find that has  allocation_rule=pe_slots, which means put all cores on one node) and update the option to be something like `gridEngineResourceOption="-pe <your pe env> THREADS -l mem_free=MEMORY"`

**Comment by Botantisty** [comment]
Thank you very much! That has solved the issue and the assembly is now running without overloading the nodes. 

All the best, Sara


For those landing here after a similar problem, first use `qconf -spl`  to get a list of parallel environments - for me this looked like:
```
$> qconf -spl
make
mpi
orte
smp
```
Then use the command `qconf -sp <env name>` to get details on the environment to check if it is using the allocation_rule=pe_slots that skoren indicated. For me:
```
$> qconf -sp smp
pe_name            smp
slots              999
user_lists         NONE
xuser_lists        NONE
start_proc_args    NONE
stop_proc_args     NONE
allocation_rule    $pe_slots
control_slaves     TRUE
job_is_first_task  TRUE
urgency_slots      min
accounting_summary TRUE
qsort_args         NONE
```
As a result, in my case `gridEngineResourceOption="-pe <your pe env> THREADS -l mem_free=MEMORY"` needed to be `gridEngineResourceOption="-pe smp THREADS -l mem_free=MEMORY"` to fix the issue. 

Looking around in the file `../canu-2.2/lib/site_perl/canu/Grid_SGE.pm` may have also given me an idea of what the problem was and maybe helpful for similar SGE grid issues.
