### ISSUE TITLE
Running the trio-binning module on corrected ONT

### ISSUE THREAD

**Issue by GuillaumeHolley** [marbl/canu#2098]
Hi, 

I currently have 70x of Illumina-corrected ONT reads (N50=22kb) with an estimated error rate of 1.6% across the genome. I also have Illumina reads (151bp PE) for the parents. As reported in this [recent paper](https://www.biorxiv.org/content/10.1101/2022.03.06.483034v1.full.pdf) about the haplotype-resolved assembly of HG002, I would like to use the trio-binning module of Trio-Canu to separate my reads into both haplotypes. After browsing the [documentation](https://canu.readthedocs.io/en/latest/quick-start.html#trio-binning-assembly), I only found how to do the trio-binned assembly (which I assume performs the binning as one of the steps). I currently use the following command:
```
canu -p asm -d Sample genomeSize=3g useGrid=false -haplotype1 parent1.illumina.fastq  -haplotype2 parent2.illumina.fastq -nanopore-corrected offspring.ont_corr.fastq
```
I am running Canu 2.2.

- Is it possible to run the trio-binning module without actually doing the assembly?
- Would you recommend any change in the parameters I am using or any additional parameters?

Thank you for your help and time,
Guillaume

**Comment by skoren** [comment]
Yes, you can run just trio-binning with the -haplotype option: https://canu.readthedocs.io/en/latest/tutorial.html?highlight=haplotype#canu-the-command
