### ISSUE TITLE
Merging overlapping contigs with --assemble in canu

### ISSUE THREAD

**Issue by aswathyseb** [marbl/canu#2099]
I want to merge some of the overlapping contigs. These contigs were created using HiCanu.

Attached is the IGV snapshot of the alignment.

<img width="2516" alt="overlap_contigs" src="https://user-images.githubusercontent.com/5373487/157316368-8d47a238-b2a6-4268-859c-97d6aa80a59f.png">

I see the same problem in  #1718 and I tried the command given there. My command is 

`time canu -p asm -d scaf_test genomeSize=980000 -assemble -pacbio-corrected chr2.fa batOptions="-nofilter covgap,spur,lopsided" contigFilter="2 0 1.0 0.5 0" stopOnLowCoverage=0 minInputCoverage=0  `

However I get the error 
`ABORT:   partitioning failed; increase redMemory.`

I tried changing redMemory parameter but of no use.

I am using a Linux machine with 23 CPUs and about 528Gb of ram. 

I could HiCanu with no issues of memory or disk space.

Could you please help?

Thank you very much!

**Comment by skoren** [comment]
In general, it's a bad idea to merge contigs. They will have overlaps by definition of the string graph/overlap graph but that doesn't mean it's a safe operation. Practically, there's a limit on read length in Canu of 2mb so any contig longer than this would have been truncated.

**Comment by aswathyseb** [comment]
Okay, thank you.
Is there any parameters that I can tweak in Canu so that it produces only the longest overlapping contigs? 

I have CCS reads with 70x coverage which produce contigs like the image below with the command

`canu -p canu_asm genomeSize=23m -pacbio-hifi ccs.fq -d canu_assembly`


![igv](https://user-images.githubusercontent.com/5373487/157331873-be8ab562-4468-47eb-b100-cc6f6ce57d06.png)

Thank you

**Comment by skoren** [comment]
No, the contig output is the output. If there's more than one contig covering a loci, it's probably due to haplotype variation or other sequence differences. You can filter bubbles (annotated on the def line in the assembly fasta) or run a tool like purge_dups.

**Comment by aswathyseb** [comment]
Thank you for the suggestions. I will try it out.

**Comment by skoren** [comment]
Any updates, did you manage to do what you were trying?

**Comment by aswathyseb** [comment]
Thank you for checking in.
 Based on your suggestion and the general idea that I am getting from the community about merging contigs in assembly, I decided not to merge but keep them as separate contigs.
