### ISSUE TITLE
Clarification on one of the FAQs

### ISSUE THREAD

**Issue by JohnUrban** [marbl/canu#210]
I hope all is well in Canu land.

I have a question concerning one of the FAQs:
http://canu.readthedocs.io/en/stable/faq.html

Particularly the one about parameters for sequence type. It discusses 1D data from R7 and doing 5-10 rounds of correction. Is this the case when you are strictly/only using 1D data? What if you have 1D data in addition to higher quality data? Should one still iterate over correcting the 1D data before including it with the rest of the data? Or should one iterate over correcting it including the higher quality data in the correction cycles?

It then says:
>Assemble with:
> -nanopore-corrected <your data> errorRate=0.1 utgGraphDeviation=50

Does utgGraphDeviation having anything to do with -dg (or another option) in bogart? Is this the same approach as smashing heterozygosity (e.g., smashing mentioned in #201 )?

Also in the case of correcting low-quality 1D data in the presence of higher quality data (or including it with higher quality data), how would that affect setting errorRate and utgGraphDeviation above?

Thanks for any thoughts you have on this. I am trying to make sure I get the most out of Canu with my dataset, and for me there is a big question mark over how to handle a dataset with a big range over the quality of the input data.

**Comment by skoren** [comment]
utgGraphDeviation sets the -dg and -db parameters. It's similar to smashing heterozygosity in that it will merge higher-error sequences. This is needed for R7 1D data because after correction it's still only average 85-90% identity.  If you have both low-quality data and high-quality data, I would not set these parameters because you want to use the high quality data when you can. If some of your lower quality data gets corrected well it will be used but the worse low-quality data will not.

**Comment by JohnUrban** [comment]
Is there any merit in iterating over correction a couple times in the scenario of having both high and low quality data?

**Comment by skoren** [comment]
Sure it shouldn't hurt the high-quality data and might improve more low-quality data.

**Comment by JohnUrban** [comment]
Thanks. I will give a try and see what happens. As far as smashing heterozygosity goes, could you suggest a reasonable value to feed utgGraphDeviation?

**Comment by skoren** [comment]
You can make it relatively high, 10 or more. The overlaps are still limited by the error rate the overlaps were computed out to which is 13% for nanopore data by default and 7.5% for PacBio. The 4-unitigger/asm.001*log file will give you a summary of what the median and deviations were and what limit was actually selected based on your threshold.

**Comment by JohnUrban** [comment]
I see. Correct me if I am wrong. It sounds like you are saying that on some level it doesn't matter what I set utgGraphDeviation to since the overlaps are limited by the error rate anyway. Does that mean I would have to increase the errorRate (or some other) parameter along with utgGraphDeviation to help smash heterozygosity?

**Comment by skoren** [comment]
You can increase the error rate but the default is pretty permissive. In practice bogart is typically using a much lower threshold than originally computed. For example on your dataset we include in the regression testing, it used a bound of 3.5% even though overlaps were computed out to 7.5%.

**Comment by JohnUrban** [comment]
Ultimately my goal/what I am trying to do is get the Canu performance back up to what it was when I was able to modify "-repeatdetect" for diploidy settings. 
Back then, I did a for-loop over various parameters for bogart. I found that using 3X guessed coverage for the middle parameter of -repeatdetect did quite well -- at least for size stats (did not evaluate other ways). For example:
Assuming G=210m, I was able to get NG50 of ~6.98 Mb and expect size of at least 6.4 Mb.
Assuming G=350m, I was able to get an NG50 of ~1.5 Mb and expected size of at least 3.8 Mb.

This beat out falcon in most parameters above, which had corresponding values of:
G=210m, NG50 = 3.7 Mb, E_G = 5.2 Mb
G=350m, NG50 = 2.1 Mb, E_G = 3.1 Mb

Currently, with default settings for the latest Canu code, I get more like:
G=210m, NG50 = 2.8 Mb, E_G = 3.7 Mb
G=350m, NG50 = 1.1 Mb, E_G = 2.3 Mb
These current size-stats are also lower than earlier Canu versions with defaults (i.e. when not messing around with -repeatdetect). For example, 4 Mb vs 2.8 Mb -- or 5.5 Mb vs 3.7 Mb. So at least in terms of size-stats, previously Canu was doing as good or better than Falcon. Now Falcon is doing better. 

I am hoping to find a way to get the latest Canu code back up to the previous levels. I imagine this involves smashing the heterozygosity or something similar. Is that wrong to assume?

Previously I was able to do this:
```
for ovl in 500 1000 1500 2000 2500 3000 3500 4000 4500 5000; do
   for ee in 0.025 0.030 0.035 0.040 0.045 0.050 0.055 0.060 0.065 0.070 0.080 0.090 0.100 ; do
      for B in $B1 $B2 $B3; do 
        echo "ASM, OVL $ovl, EE $ee, B $B"
        mkdir 4-unitigger-RS-NS-CS-${ovl}-${ee}-${B} && cd 4-unitigger-RS-NS-CS-${ovl}-${ee}-${B} && echo `pwd` && $bin/bogart -G $GKP -O $OVL -T asm.tigStore -o asm -B 19824 -el ${ovl}  -eg ${ee} -eb 0.0625 -em 0.0375 -er ${ee} -threads 4 -M 16 -RS -NS -CS -unassembled 2 1000 0.75 0.75 2 -repeatdetect $A $B $C && cd ..
        echo $G1
        $bin/tgStoreDump -contigs -bubbles -sizes -s $G1 -G $GKP -T 4-unitigger-RS-NS-CS-${ovl}-${ee}-${B}/asm.tigStore 1 | awk -v "var=parameters::: G: $G1 ovl: $ovl ee: $ee B: $B" '{print $0 "\t" var}' #> 4-unitigger-RS-NS-CS-${ovl}-${ee}-${B}/${G1}.g1.out
        echo
        echo $G2
        $bin/tgStoreDump -contigs -bubbles -sizes -s $G2 -G $GKP -T 4-unitigger-RS-NS-CS-${ovl}-${ee}-${B}/asm.tigStore 1 | awk -v "var=parameters::: G: $G2 ovl: $ovl ee: $ee B: $B" '{print $0 "\t" var}' #> 4-unitigger-RS-NS-CS-${ovl}-${ee}-${B}/${G2}.g2.out
        echo; echo
      done
   done
done
```
Ultimately, ee of 0.055 or 0.06 worked best with ovl of 1000-2500 and B=3*guessedXcov

Is there a similar loop to run with the latest code?
