### ISSUE TITLE
Canu 2.2/failed

### ISSUE THREAD

**Issue by Mariagio6** [marbl/canu#2105]
Hi!
I am a beginner in bioinformatics, I work on PacBio sequences, that I wanted to assemble with Canu/2.2
I ran it manually step by step and I had trouble in the assemble step.
This is my script: 
[prova.txt](https://github.com/marbl/canu/files/8340345/prova.txt)

 When I submitt the work I don't receive error message but the run failed everytime in 16 sec 

[prova1.txt](https://github.com/marbl/canu/files/8340396/prova1.txt)

Which could be the reason?

**Comment by Mariagio6** [comment]
Thank you for the help! I cleaned up the folder and launched it again as single command

**Comment by skoren** [comment]
Any update, is it running now?

**Comment by Mariagio6** [comment]
Actually not. I got the same problem.
The run stop after the trimming

Il giorno gio 31 mar 2022 alle ore 19:16 Sergey Koren <
***@***.***> ha scritto:

**Comment by skoren** [comment]
Do you have the full logs of the run, including anything in canu.out?

**Comment by Mariagio6** [comment]
I have the logs of the run and also the canu.out.. this is the error I got 


-- BEGIN ASSEMBLY
-- Found 35 overlap error adjustment output files.
-- Finished stage 'overlapErrorAdjustmentCheck', reset canuIteration.
----------------------------------------
-- Starting command on Sat Mar 26 06:10:22 2022 with 17215.683 GB free disk space

    cd unitigging/3-overlapErrorAdjustment
    /apps/haswell/software/canu/2.2-GCCcore-10.3.0/bin/loadErates \
      -S ../../wasp.seqStore \
      -O ../wasp.ovlStore \
      -L ./oea.files \
    > ./oea.apply.err 2>&1

-- Finished on Sat Mar 26 06:10:22 2022 (fast as lightning) with 17215.683 GB free disk space
----------------------------------------
-- No report available.
-- Finished stage 'updateOverlapStore', reset canuIteration.
-- Finished stage 'unitig', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
--
-- Failed to submit compute jobs.  Delay 10 seconds and try again.

CRASH:
CRASH: canu 2.2
CRASH: Please panic, this is abnormal.
CRASH:
CRASH:   Failed to submit compute jobs.
CRASH:
CRASH: Failed at /apps/haswell/software/canu/2.2-GCCcore-10.3.0/bin/../lib/site_perl/canu/Execution.pm line 1259.
CRASH:  canu::Execution::submitOrRunParallelJob("wasp", "bat", "unitigging/4-unitigger", "unitigger", 1) called at /apps/haswell/software/canu/2.2-GCCcore-10
.3.0/bin/../lib/site_perl/canu/Unitig.pm line 334
CRASH:  canu::Unitig::unitigCheck("wasp") called at /apps/haswell/software/canu/2.2-GCCcore-10.3.0/bin/canu line 1131
CRASH:
CRASH: Last 50 lines of the relevant log file (unitigging/4-unitigger/unitigger.jobSubmit-01.out):
CRASH:
CRASH: sbatch: error: Batch job submission failed: Requested node configuration is not available
CRASH:
###############################################################################
Peregrine Cluster
Job 23443582 for user 's5307430'
Finished at: Sat Mar 26 06:10:33 CET 2022

Job details:
============

Job ID              : 23443582
Name                : canu_wasp
User                : s5307430
Partition           : regular
Nodes               : pg-node209
Number of Nodes     : 1
Cores               : 1
Number of Tasks     : 1
State               : FAILED
Submit              : 2022-03-26T06:04:42
Start               : 2022-03-26T06:10:20
End                 : 2022-03-26T06:10:33
Reserved walltime   : 4-23:00:00
Used walltime       :   00:00:13
Used CPU time       :   00:00:01 (efficiency:  9.92%)
% User (Computation): 51.16%
% System (I/O)      : 48.76%
Mem reserved        : 16G
Max Mem (Node/step) : 0.00  (Node unknown, N/A)
Full Max Mem usage  : 0.00
Total Disk Read     : 0.00
Total Disk Write    : 0.00

**Comment by skoren** [comment]
That's the unitigging step, not trimming. It is trying to use a higher memory node which must require special sbatch parameters on your cluster. Add batMemory=100 to fit on your smaller nodes and re-launch and it should work.

**Comment by skoren** [comment]
Idle, initial issue was proper behavior. Bogart memory usage can be addressed either via batMemory or by adding required slurm options to `gridOptionsBat`
