### ISSUE TITLE
Stage 'cor' concurrent execution (Read correction) not finishing

### ISSUE THREAD

**Issue by carlosparq** [marbl/canu#2108]
Hi,

I'm having some trouble trying to correct some nanopore reads to start an assembly. Initially, I tried these more time-consuming parameters to use most of my reads:

```
canu -correct -p assembly -d rnd1 corOutCoverage=500 corMinCoverage=0 corMhapSensitivity=high genomeSize=36.7m -nanopore $reads
```
It went through the kmercounts and overlapping processes fine but got stuck in the correction stage, at the last process of the 'cor' concurrent execution. That time, I had up to 6 partitions and it ran fairly fast through the first 5 (less than 1 hour), but got stuck for days in the last 6th partition. I thought about running it in default with the same data and the same happened, though this time it only created 2 data partitions for that step. Please, see below:

```
-- Local: cor        6.000 GB    4 CPUs x   8 jobs    48.000 GB  32 CPUs  (read correction)
--
--
-- Configuring correction jobs:
--   Reads estimated to need at most 3.268 GB for computation.
--   Jobs will request 6 GB each.
----------------------------------------
-- Starting command on Sun Apr  3 19:31:24 2022 with 715.967 GB free disk space

    cd correction/2-correction
    ./correctReadsPartition.sh \
    > ./correctReadsPartition.err 2>&1

-- Finished on Sun Apr  3 19:31:26 2022 (2 seconds) with 715.967 GB free disk space
----------------------------------------
-- Finished stage 'cor-generateCorrectedReadsConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'cor' concurrent execution on Sun Apr  3 19:31:26 2022 with 715.967 GB free disk space (2 processes; 8 concurrently)

    cd correction/2-correction
    ./correctReads.sh 1 > ./correctReads.000001.out 2>&1
    ./correctReads.sh 2 > ./correctReads.000002.out 2>&1
```
Doesn't look like a high resource-consuming step, but it won't go further that stage and it's been there for almost a day now.
Maybe I am a little impatient, but I'm seeing that it's not really occupying any resources right now and seems like a pretty long time to be idle. I would really appreciate some help on to what I am doing wrong.
Thanks in advance,
Carlos

**Comment by skoren** [comment]
This step can take a while on reads that are very long which is likely what you're seeing. You can control how many partitions are created to reduce some of that using `corPartitions` and `corPartitionMin` (see #1965). To do that, you would have to stop the current run, remove or rename the `2-correction` folder, and re-launch. I'd suggest something like `corPartitions=8 corPartitionMin=1` based on the fact that canu said it could run 8 partitions on your node simultaneously.

**Comment by carlosparq** [comment]
Thank you, I'll try that and report here! I was using the conda package but now I have downloaded the binaries, so maybe that'll improve things. So just to be clear, it is perfectly normal that it completed the first 'cor' processes in a matter of minutes, but after finishing the last one it's still processing and this will take a while (maybe days?), right?

**Comment by skoren** [comment]
I presume this finished with an increased number of partitions. Feel free to open a new issue if you encounter other issues with the asm.
