### ISSUE TITLE
Parts of pipeline where SLURM is killing Canu for exceeding memory 

### ISSUE THREAD

**Issue by JohnUrban** [marbl/canu#211]
Hi,

I recently began running a lot of Canu jobs again. In case it is of interest, I am sharing here parts of the pipeline that are being killed due to exceeding memory. Recall, I'm on SLURM (if that matters).
1. Meryl in correction phase
   In at least 1 run with a set of reads filtered some various way, it reproducibly fails to ask for enough memory.

```
##   Mem/CPU : 2432 MB
##  Mem/Node : 16384 MB
.
.
.
slurmstepd: Job 13015929 exceeded memory limit (19924520 > 19922944), being killed
slurmstepd: Exceeded job memory limiters --  6.66 Mmers/second
slurmstepd: *** JOB 13015929 ON node413 CANCELLED AT 2016-07-28T22:55:01 ***
slurmstepd: Exceeded step memory limit at some point.
```

I had to add `corMemory=18` to the canu command to pass through this meryl step. This changes --mem-per-cpu=2432 to  --mem-per-cpu=3840 in meryl.jobSubmit.sh. Here is top of slurm.out file

```
##   Mem/CPU : 3840 MB
##  Mem/Node : 16384 MB
```
1. 2-correction in correction phase
   This has failed on several different attempts (with different read mixtures).
   Example: part of header in correctRead._1.out:

```
##   Mem/CPU : 2304 MB
##  Mem/Node : 16384 MB
```

I added corMemory=18 to the canu command.
It still failed - so I need more.
Example slurm.out - piece of header:

```
##  Nodelist : node403
##      CPUs : 
##   Mem/CPU : 4608 MB
##  Mem/Node : 16384 MB
.
.
Running job 1 based on SLURM_ARRAY_TASK_ID=1 and offset=0.
slurmstepd: Job 13020988 exceeded memory limit (18879048 > 18874368), being killed
slurmstepd: Exceeded job memory limit
slurmstepd: *** JOB 13020988 ON node403 CANCELLED AT 2016-07-29T05:49:25 ***
slurmstepd: Exceeded step memory limit at some point.
```

Increasing corMemory=24 worked for some, not others.
Its now running at corMemory=30.

I will let you know any other problematic areas of the pipeline as the runs progress.

best,

  John

**Comment by JohnUrban** [comment]
I just saw some mistakes.... to fix the meryl thing I needed ```merylMemory=30```, not ```corMemory=18```.

**Comment by brianwalenz** [comment]
Is this failing when running meryl (the binary) or gnuplot?  I.e., what is in the 0-mercounts directory?  Serge has seem a few cases where gnuplot was the problem.

**Comment by JohnUrban** [comment]
This is what the end of one of the failing meryl.out files looks like:
```
 Counting mers in buckets: 2265.18 Mmers -- 11.85 Mmers/second
 Creating bucket pointers.
 Releasing 512MB from counting the size of each bucket./second
 Allocating 1353MB for mer storage (5 bits wide).
 Counting mers in buckets: 2266.18 Mmers -- 11.34 Mmers/second
 Creating bucket pointers.
 Releasing 512MB from counting the size of each bucket./second
 Allocating 1353MB for mer storage (5 bits wide).
 Counting mers in buckets: 2266.30 Mmers -- 11.02 Mmers/second
 Creating bucket pointers.
 Releasing 512MB from counting the size of each bucket./second
 Allocating 1353MB for mer storage (5 bits wide).
 Counting mers in buckets: 2265.07 Mmers -- 10.49 Mmers/second
 Creating bucket pointers.
 Releasing 512MB from counting the size of each bucket./second
 Allocating 1353MB for mer storage (5 bits wide).
slurmstepd: Job 13041182 exceeded memory limit (19925168 > 19922944), being killed
slurmstepd: Exceeded job memory limit
slurmstepd: *** JOB 13041182 ON node405 CANCELLED AT 2016-08-02T05:04:18 ***
slurmstepd: Exceeded step memory limit at some point.
```

Does that help?

**Comment by brianwalenz** [comment]
Shucks.  Yup, that's pretty clearly meryl.  Again.

There are three large allocations per thread.  Two are shown here, one temporary at 512mb, and one for the data at 1353mb.  Assuming the third (the 'bucket pointers') is also 512mb, that's 1865mb per thread.  I don't know how many threads you're running.

I'm puzzled why your initial logs are showing different mem/cpu but constant mem/node at 16gb.  Even after increasing merylMemory.  Is slurm somehow scheduling jobs incorrectly?

Is something else running (like the canu perl script) that is eating up our memory?

**Comment by JohnUrban** [comment]
I am not sure I have good answers to your questions.

Here is meryl.jobSumbit.sh before meryl=30:
```
  sbatch \
    --time 24:00:00  --mem-per-cpu=3840m --cpus-per-task=8 \
    -D `pwd` -J "meryl_pbont-correct-i2" \
    -a 1-1 \
    -o /canu/multicorrect/i2/correction/0-mercounts/meryl.%A_%a.out \
    /canu/multicorrect/i2/correction/0-mercounts/meryl.sh 0
```

Here it is after:
```
  sbatch \
    --time 24:00:00  --mem-per-cpu=2432m --cpus-per-task=8 \
    -D `pwd` -J "meryl_pbont-correct-i2" \
    -a 1-1 \
    -o /canu/multicorrect/i2/correction/0-mercounts/meryl.%A_%a.out \
    /canu/multicorrect/i2/correction/0-mercounts/meryl.sh 0
```

I was puzzled by the different mem/cpu but constant mem/node too....

**Comment by JohnUrban** [comment]
For everything I do with SLURM, I use --mem rather than --mem-per-cpu -- but I know we have had this discussion already. It seems like it makes a difference for me -- but that is anecdotal. Maybe this comes down to slurm version.

```
sbatch -V
slurm 15.08.9
```

**Comment by brianwalenz** [comment]
Backwards?

Before merylMemory=30, it wanted 3840m and 8 threads (30720m total).
After merylMemory=30, it wanted 2432m and 8 threads (19456m total).

Do you still have the meryl.sh for each of those?  If possible, meryl.out too (or check that what it allocated agrees with what it's requesting).

**Comment by JohnUrban** [comment]
It was backwards -- I believe I edited it correctly for future reference.

Here is meryl.sh for merylMemory=30 -- the other one was overwritten. I can re-run to get it though.
```
#!/bin/sh

if [ -e /canu/multicorrect/i2/correction/correct-i2.tigStore/seqDB.v001.tig ] ; then
  exit 0
fi

syst=`uname -s`
arch=`uname -m`
name=`uname -n`

if [ "$arch" = "x86_64" ] ; then
  arch="amd64"
fi
if [ "$arch" = "Power Macintosh" ] ; then
  arch="ppc"
fi

bin="/gpfs_home/jurban/software/canu/canu/$syst-$arch/bin"

if [ ! -d "$bin" ] ; then
  bin="/gpfs_home/jurban/software/canu/canu"
fi


#  Purge any previous intermediate result.  Possibly not needed, but safer.

rm -f /canu/multicorrect/i2/correction/0-mercounts/correct-i2.ms16.WORKING*

$bin/meryl \
  -B -C -L 2 -v -m 16 -threads 8 -memory 24576 \
  -s /canu/multicorrect/i2/correction/correct-i2.gkpStore \
  -o /canu/multicorrect/i2/correction/0-mercounts/correct-i2.ms16.WORKING \
&& \
mv /canu/multicorrect/i2/correction/0-mercounts/correct-i2.ms16.WORKING.mcdat /canu/multicorrect/i2/correction/0-mercounts/correct-i2.ms16.FINISHED.mcdat \
&& \
mv /canu/multicorrect/i2/correction/0-mercounts/correct-i2.ms16.WORKING.mcidx /canu/multicorrect/i2/correction/0-mercounts/correct-i2.ms16.FINISHED.mcidx

exit 0
```

**Comment by JohnUrban** [comment]
Perhaps some of this info will help from sacct.

For the job that failed:
```

       JobID    JobName  Partition  MaxVMSize  MaxVMSizeNode 
------------ ---------- ---------- ---------- -------------- 
13041182_1   meryl_pbo+ default-b+                           
13041182_1.+      batch             25289980K        node405 


 MaxVMSizeTask  AveVMSize     MaxRSS MaxRSSNode 
-------------- ---------- ---------- ---------- 
                                                
             0  25289980K  19925168K    node405 


MaxRSSTask     AveRSS MaxPages MaxPagesNode 
---------- ---------- -------- ------------ 
                                            
         0  19925168K        0      node405 


  MaxPagesTask   AvePages     MinCPU MinCPUNode 
-------------- ---------- ---------- ---------- 
                                                
             0          0   00:29:29    node405 


MinCPUTask     AveCPU   NTasks  AllocCPUS    Elapsed 
---------- ---------- -------- ---------- ---------- 
                                        8   00:04:01 
         0   00:29:29        1          8   00:04:02 


     State ExitCode AveCPUFreq ReqCPUFreqMin 
---------- -------- ---------- ------------- 
CANCELLED+      0:0                  Unknown 
 CANCELLED     0:15      2.60M             0 


ReqCPUFreqMax ReqCPUFreqGov ConsumedEnergy 
------------- ------------- -------------- 
      Unknown       Unknown                
            0             0              0 


 MaxDiskRead MaxDiskReadNode MaxDiskReadTask 
------------ --------------- --------------- 
                                             
       0.10M         node405               0 


   AveDiskRead MaxDiskWrite MaxDiskWriteNode 
-------------- ------------ ---------------- 
                                             
         0.10M        0.59M          node405 


MaxDiskWriteTask    AveDiskRead    AllocGRES      ReqGRES 
---------------- -------------- ------------ ------------ 
                                                          
               0          0.10M                           


```


For the job that succeeded (merylMemory=30):
```

       JobID    JobName  Partition  MaxVMSize  MaxVMSizeNode 
------------ ---------- ---------- ---------- -------------- 
13041197_1   meryl_pbo+ default-b+                           
13041197_1.+      batch             25291340K        node410 


 MaxVMSizeTask  AveVMSize     MaxRSS MaxRSSNode 
-------------- ---------- ---------- ---------- 
                                                
             0   1267404K  20630816K    node410 


MaxRSSTask     AveRSS MaxPages MaxPagesNode 
---------- ---------- -------- ------------ 
                                            
         0    127052K        0      node410 


  MaxPagesTask   AvePages     MinCPU MinCPUNode 
-------------- ---------- ---------- ---------- 
                                                
             0          0   01:42:34    node410 


MinCPUTask     AveCPU   NTasks  AllocCPUS    Elapsed 
---------- ---------- -------- ---------- ---------- 
                                        8   00:24:59 
         0   01:42:34        1          8   00:24:59 


     State ExitCode AveCPUFreq ReqCPUFreqMin 
---------- -------- ---------- ------------- 
 COMPLETED      0:0                  Unknown 
 COMPLETED      0:0      2.59M             0 


ReqCPUFreqMax ReqCPUFreqGov ConsumedEnergy 
------------- ------------- -------------- 
      Unknown       Unknown                
            0             0              0 


 MaxDiskRead MaxDiskReadNode MaxDiskReadTask 
------------ --------------- --------------- 
                                             
      23055M         node410               0 


   AveDiskRead MaxDiskWrite MaxDiskWriteNode 
-------------- ------------ ---------------- 
                                             
        23055M       32002M          node410 


MaxDiskWriteTask    AveDiskRead    AllocGRES      ReqGRES 
---------------- -------------- ------------ ------------ 
                                                          
               0         23055M   

```

**Comment by JohnUrban** [comment]
So, this part of Canu pipeline just failed due to memory:
```
    /gpfs_home/jurban/software/canu/canu/Linux-amd64/bin/ovStoreBuild \
     -O /asm/correction/asm.ovlStore.BUILDING \
     -G /asm/correction/asm.gkpStore \
     -M 2-8 \
     -L /asm/correction/1-overlapper/ovljob.files \
     > /asm/correction/asm.ovlStore.err 2>&1
slurmstepd: Job 13041453 exceeded memory limit (8431484 > 8388608), being killed
slurmstepd: Exceeded job memory limit
slurmstepd: *** JOB 13041453 ON node405 CANCELLED AT 2016-08-02T21:37:10 ***
slurmstepd: Exceeded step memory limit at some point.
```

**Comment by brianwalenz** [comment]
For meryl, I wondering if your grid is including the pages used for the memory mapped gkpStore/blobs file.  I've not seen any other grid do that.  The 'fix' would be to increase the grid memory request by the size of this file - it'd need to be done in code, but shouldn't be too hard to do.

The ovStoreBuild shouldn't have the same problem.  It should be using only the metadata file, which is vastly smaller.  What's in /asm/correction/asm.ovlStore.err?

**Comment by JohnUrban** [comment]
Apologies -- I somewhat began focusing on the ovlStore in a new issue #216 

It is re-running right now, so the previous file is over-written.

In general, that step for what I am currently doing takes more than 64GB. I am trying 100GB right now.

**Comment by JohnUrban** [comment]
In order to keep these memory issues in one thread, I am going to close #216 , which was more about estimating how big the overlap store would get -- though it also brought up memory issues.

I found a work around for now:
I was able to get the ovs step to finish by setting ovsMemory=80 and --mem=100g (for sbatch).
I am on the 3rd iteration of read correction and defaults for that step failed again. I am trying the solution above (that worked for iter 2) now, which I imagine will work again.

**Comment by brianwalenz** [comment]
I don't know if this will be fixing anything for you.

Previously, the gkpStore 'blobs' file was mapped into the process, which let us treat the file as if it were a normal array and pushed all the file accesses to the OS.  Super simple for us, supposedly speedy, but it came with the price of bloating the apparent process size.  For large assemblies, this could be adding tens of GB's to the process size.  It should have been treated as 'free' - the data was never written to, so the OS could have thrown it out of memory at any time.

I switched this to use direct file access.  In limited testing, there wasn't a noticeable performance impact.

**Comment by brianwalenz** [comment]
Thanks for the help on these.  Closing since there seem to be few problems any more.
