### ISSUE TITLE
Canu 2.2: utgovl failed

### ISSUE THREAD

**Issue by yzhang-github-pub** [marbl/canu#2110]
Dear author,

I logged into a node in HPC, and my command is like:
canu -d ./assemble_dir -p test genomeSize=60k useGrid=false -nanopore-raw ./reads/*.fastq.gz

I got errors:
```
-- Local machine mode enabled; grid support not detected or not allowed.
-- ERROR
-- ERROR  Found 1 machine configuration:
-- ERROR    class0 - 1 machines with 1 cores with 376 GB memory each.
-- ERROR
-- ERROR  Task utgovl can't run on any available machines.
-- ERROR  It is requesting:
-- ERROR    utgovlMemory=4 gigabytes
-- ERROR    utgovlThreads=2-8 threads
-- ERROR
-- ERROR  No available machine configuration can run this task.
-- ERROR
-- ERROR  Possible solutions:
-- ERROR    Change maxMemory or maxThreads
-- ERROR    Change utgovlMemory and/or utgovlThreads
-- ERROR

ABORT:
ABORT: canu 2.2
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   task utgovl failed to find a configuration to run on.
```

I'd appreciate your help. Thanks!

**Comment by yzhang-github-pub** [comment]
Thanks. 

With "maxThreads=1 obtovlThreads=1", I still got the same error.

**Comment by skoren** [comment]
You may need to add more than one option to set threads to 1 (e.g. your original message mentioned utgovlThreads but your command only specified obtovlThreads. You want to add both and others if it complains about them. You can also try defining the appropriate environment variable as in #1995.

**Comment by yzhang-github-pub** [comment]
I added "utgovlThreads=1 corThreads=1 redThreads=1 batThreads=1" and the cmd worked.

Thanks @skoren & @brianwalenz for your help!
