### ISSUE TITLE
Unable to install Canu 2.2 on MacOS Monterey

### ISSUE THREAD

**Issue by LCFortier** [marbl/canu#2116]
Hi,

I am trying to install Canu 2.2 on my Macbookpro (M1 chipset) running on Monterey (OSX 12.3.1), but the binary files seem to be of unknown format.

I used this command:

curl -L https://github.com/marbl/canu/releases/download/v2.2/canu-2.2.Darwin.tar.xz --output canu-2.2.Darwin.tar.xz 
tar -xJf canu-2.2.Darwin.tar.xz

But this is what I get:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     14      0 --:--:-- --:--:-- --:--:--    14
tar: Error opening archive: Unrecognized archive format

Am I doing something wrong? 

I also tried to install it with conda, but it looks like it is the Canu v1.5 that gets installed and not the v2.2, and I also get error messages that I don't understand.

Can someone help me out with that? I can't find the answers in the Canu documentation. I would like to assemble phage and bacterial genomes sequenced with nanopore.

Thanks!

**Comment by skoren** [comment]
Your curl command is invalid, it should be:
```
curl -L https://github.com/marbl/canu/releases/download/v2.2/canu-2.2.Darwin-amd64.tar.xz --output canu-2.2.Darwin.tar.xz 
```
as in the release notes: https://github.com/marbl/canu/releases. As for Conda, I'm not an expert but I expect you're getting it from the wrong repo, bioconda should have the right versions for v2.2: https://bioconda.github.io/recipes/canu/README.html?highlight=canu#package-package%20&#x27;canu&#x27
```
conda install -c conda-forge -c bioconda -c defaults canu
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/korens/miniconda3

  added / updated specs:
    - canu


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cairo-1.16.0               |    h0ab9d94_1001         1.3 MB  conda-forge
    canu-2.2                   |       hbe63672_0         9.8 MB  bioconda
    certifi-2021.10.8          |   py39h6e9494a_2         144 KB  conda-forge
    expat-2.4.4                |       he49afe7_0         145 KB  conda-forge
    fontconfig-2.13.94         |       h10f422b_0         285 KB  conda-forge
    freetype-2.10.4            |       h4cff582_1         890 KB  conda-forge
    fribidi-1.0.10             |       hbcb3906_0          64 KB  conda-forge
    gettext-0.19.8.1           |    h7937167_1005         3.3 MB  conda-forge
    giflib-5.1.7               |       h01d97ff_1         140 KB  conda-forge
    glib-2.68.4                |       he49afe7_0         429 KB  conda-forge
    glib-tools-2.68.4          |       he49afe7_0          81 KB  conda-forge
    gnuplot-5.2.7              |       hd866d03_2         1.0 MB  conda-forge
    graphite2-1.3.13           |    h2e338ed_1001          85 KB  conda-forge
    harfbuzz-2.4.0             |       h92b87b8_1         1.2 MB  conda-forge
    jpeg-9e                    |       h0d85af4_0         252 KB  conda-forge
    k8-0.2.5                   |       h87af4ef_1         1.4 MB  bioconda
    libgd-2.2.5                |    h8cbe2a3_1005         234 KB  conda-forge
    libglib-2.68.4             |       hd556434_0         2.8 MB  conda-forge
    libpng-1.6.37              |       h7cec526_2         313 KB  conda-forge
    libtiff-4.0.9              |    h79f4b77_1002         542 KB  conda-forge
    libwebp-1.0.2              |       h14d73da_2         852 KB  conda-forge
    minimap2-2.22              |       h188c3c3_0         147 KB  bioconda
    openjdk-11.0.9.1           |       hcf210ce_1       168.8 MB  conda-forge
    pango-1.42.4               |       haa940fe_4         509 KB  conda-forge
    pcre-8.45                  |       he49afe7_0         220 KB  conda-forge
    perl-filesys-df-0.92       | pl5321ha5712d3_5          14 KB  bioconda
    pixman-0.38.0              |    h01d97ff_1003         611 KB  conda-forge
    qt-5.9.7                   |       h93ee506_2        76.8 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       272.3 MB
```

**Comment by LCFortier** [comment]
OK thanks for the quick reply skoren,
I finally was able to install it. But when I run the following command I get an error message:
 canu \
-p ecoli -d ecoli-pacbio \
genomeSize=4.8m \
-pacbio pacbio.fastq

INVALID -pacbio

usage: canu [-version] \
            [-correct | -trim | -assemble | -trim-assemble] \
            [-s <assembly-specifications-file>] \
             -p <assembly-prefix> \
             -d <assembly-directory> \
             genomeSize=<number>[g|m|k] \
            [other-options] \
            [-pacbio-raw | -pacbio-corrected | -nanopore-raw | -nanopore-corrected] *fastq

  By default, all three stages (correct, trim, assemble) are computed.
  To compute only a single stage, use:
    -correct       - generate corrected reads
    -trim          - generate trimmed reads
    -assemble      - generate an assembly
    -trim-assemble - generate trimmed reads and then assemble them

  The assembly is computed in the (created) -d <assembly-directory>, with most
  files named using the -p <assembly-prefix>.

  The genome size is your best guess of the genome size of what is being assembled.
  It is used mostly to compute coverage in reads.  Fractional values are allowed: '4.7m'
  is the same as '4700k' and '4700000'

  A full list of options can be printed with '-options'.  All options
  can be supplied in an optional sepc file.

  Reads can be either FASTA or FASTQ format, uncompressed, or compressed
  with gz, bz2 or xz.  Reads are specified by the technology they were
  generated with:
    -pacbio-raw         <files>
    -pacbio-corrected   <files>
    -nanopore-raw       <files>
    -nanopore-corrected <files>

Complete documentation at http://canu.readthedocs.org/en/latest/

ERROR:  Invalid command line option '-pacbio'.  Did you forget quotes around options with spaces?
ERROR:  File supplied on command line; use -s, -pacbio-raw, -pacbio-corrected, -nanopore-raw, or -nanopore-corrected.

**Comment by skoren** [comment]
Are you sure you're actually running the canu version you downloaded and not the one you installed via conda? The help text looks old. What does `canu --version` report? If it's not 2.2, uninstall the conda version and give the full path to the location where you downloaded the 2.2 release or add that one to your path.

**Comment by LCFortier** [comment]
Indeed, it was running the v1.5 installed by conda... so I did what you suggested and removed it, then added Canu to the PATH and now it seems to work! I started a run and it is processing so it's already good news!! Let's see if it completes the job as expected.
Thanks!!

**Comment by LCFortier** [comment]
It worked! Thanks a lot skoren for your help!
