### ISSUE TITLE
Low coverage, Ultra-long, "Super Accurate" Nanopore.

### ISSUE THREAD

**Issue by JohnUrban** [marbl/canu#2121]
Hello fellas!

It's been a long time. I hope all is well. Congrats on all your productivity and recognition!

I'm working with a 10X nanopore dataset (Read N50 = 120 kb) that I basecalled with Guppy 6.1.2 super-accurate mode. FWIW -- the mean Q scores suggest an expected accuracy average of 95% for passing reads and 90% for all reads (including "fail" folder).  I am hoping to convince my colleague to at least double this data, but it is all I have for now.

I was wondering if you have any recommendations on how to run Canu under these limiting conditions. On one hand, the coverage is low. On the other, the read N50 is huge, so it seems like it still could generate a decent assembly. I've already run other assemblers (flye, shasta, wtdbg2, miniasm) and have had decent results. I'm hoping to use parameters that give Canu its best shot. 

That is the gist of this "issue". So I will cut it off here, but I will add info in the "p.s." section in anticipation to questions you might have.

Best,

John

________________________

#########################
The P.S. Section:
_______________

So far `minInputCoverage=5` and `stopOnLowCoverage=2-5` is preventing Canu from quitting under various conditions. 

Also, I see the docs say"
```
For low coverage datasets (less than 30X), we recommend increasing correctedErrorRate slightly, by 1% or so.
```
It says the default for nanopore is `0.144`, so I assume this means increase it by 0.01 with `correctedErrorRate=0.154`. I'm yet to add this though, as I wanted to try defaults first. Should I do anything with `rawErrorRate`?

I assume Canu is automatically `{prefix}MhapSensitivity=high` given the expected genome size and data equates to ~10X coverage.

Should I lower `corMinCoverage` to 3? 
Should I toggle `corFilter` at all?

Should I adjust anything in Output Filtering such as `lowCovDepth` ? -- e.g. the docs say defaults are:
```
contigFilter <minReads, integer=2> <minLength, integer=0> <singleReadSpan, float=1.0> <lowCovSpan, float=0.5> <lowCovDepth, integer=5>
```

On a related note, this data is expected to be diploid and is from a single relatively wild animal (few generations in a lab environment) -- i.e. not inbred for 100 years or something. With the other assemblers, I'm seeing assembly sizes from slightly below the expected genome size to double the expected genome size. I am currently assuming this may indicate high enough heterozygosity such that large portions of the maternal and paternal genomes present in this individual are being assembled in parallel under some settings. I will check the duplication rates with BUSCO and try purge_dups at some point. I just thought this might be pertinent to parameter recommendations, and to any interpretations of Canu assembly results that I may report back with.

**Comment by skoren** [comment]
Running correction with only 10x coverage is tricky, as you've found. I would instead try the uncorrected ONT assembly:
https://canu.readthedocs.io/en/latest/quick-start.html#assembling-with-multiple-technologies-and-multiple-files. Something like:
`-untrimmed correctedErrorRate=0.12 minInputCoverage=5 'batOptions=-eg 0.10 -sb 0.01 -dg 2 -db 1 -dr 3' -pacbio-hifi ont.fastq`

**Comment by skoren** [comment]
Idle
