### ISSUE TITLE
Question about starting and polyploid.

### ISSUE THREAD

**Issue by YuChrming** [marbl/canu#2124]
Dear writer,
I used Canu-2.2 to assemble but it dosen't work. Logging file showing `Cannot connect to specified server host 'alice'`, seems it cannot connect to the server, but other tasks work fine.
```
canu \
        -p genome -d ./genome genomeSize=1960m \
        -pacbio-hifi *.fastq.gz
```
One more question, I am assembling a plant triploid genome using 25× Hi-Fi data, I would like to know your suggestions on parameter setting.
Thanks very much!

**Comment by skoren** [comment]
First, the easy part, we don't have any specific parameters for HiFi, the defaults work quite well in most cases. There's some more advice on the FAQ here: https://canu.readthedocs.io/en/latest/faq.html#what-parameters-should-i-use-for-my-reads. 

As for the error, there's nothing in Canu that contacts a server so this is likely coming from your system. Post the full output of the command you launched.

**Comment by skoren** [comment]
Idle, not a canu error.
