### ISSUE TITLE
error rate estimate dynamically

### ISSUE THREAD

**Issue by igordot** [marbl/canu#213]
This wasn't covered in the online documentation, but checking options in the binary, I noticed the description for `errorRate`:
```
The expected error rate in the corrected reads, typically set based on sequencing type.
Set to 0 to try to estimate dynamically. (EXPERIMENTAL)
```
It sounds like setting errorRate to 0 is a good idea. Since it can potentially vary a lot between experiments, may as well determine it dynamically every time. How experimental is it? What can go wrong? Is that process analogous to running `ovStoreDump` manually which shows the observed error rate?

**Comment by skoren** [comment]
I wouldn't recommend using this option yet. Experimental means the algorithm isn't finalized and it didn't work on all our regression tests. It computes the error rate from a subset of the data. It can over or under-estimate the error rate currently. Over-estimating would make the computation much slower while under-estimating would fracture your assembly. The defaults are pretty good generally, especially if you follow the guidelines on the FAQ page.
