### ISSUE TITLE
Just a question how do you filter the kmers before proceeding with the haplotyping?

### ISSUE THREAD

**Issue by plnspineda** [marbl/canu#2134]
`haplotype.log` report shows this...

```
--  Haplotype './0-kmers/haplotype-father.meryl':
--   use kmers with frequency at least 5.
--  Haplotype './0-kmers/haplotype-mother.meryl':
--   use kmers with frequency at least 5.
```

and I'd like to ask how was the "5" computed in this instance? The reason I'd like to know is because my run with merqury for hapmer and canu gave me different number for filtering kmers.

canu filter at least 5 while merqury hapmer filter at least 46. I got how merqury-hapmer filtered at 46, however, I can't find it in canu how it computed for 5.

Both the `father_not_mother.meryl` from merqury hapmer and `haplotype-father.meryl` in the 0-kmers folder from canu has the same count of meryls using `meryl statistics <file> | head`.

version used is canu/2.0 while merqury version is v1.3 with meryl v1.3

Thank you.

**Comment by brianwalenz** [comment]
Canu is filtering out erroneous kmers by discarding any kmer with frequency less than the first minimum in the kmer histogram (https://github.com/marbl/canu/blob/master/src/haplotyping/splitHaplotype.C#L326).  It then assigns reads to haplotypes by using kmers that occur in exactly one haplotype.

Merqury seems to be looking for the depth of coverage - so the peak in the kmer histogram - and discarding kmers below that frequency.  I'm not entirely sure what it does after that though.

**Comment by plnspineda** [comment]
Hi Brian,

Thank you very much. Merqury does the same (first minimum in the kmer histogram), but I see that the difference is that canu filter erroneous kmers in the raw reads, while merqury does its first filtering after getting the hapmers.

Thanks again!
