### ISSUE TITLE
failed to generate corrected reads

### ISSUE THREAD

**Issue by bioramg** [marbl/canu#2135]
Hello sir,
I am assembling the plant mitochondrial genome using the whole genome ONT reads. I am doing the first step (correction with the following parameters: 

canu -correct -p pnt -d pnt genomeSize=1.36g -nanopore-raw /home/PNT.ONT.fastq.gz

I am getting an error and how to solve it?
```
-- 2 read correction jobs failed:
--   job /home/canu/pnt/correction/2-correction/correction_outputs/0045.fasta FAILED.
--   job /home/canu/pnt/correction/2-correction/correction_outputs/0111.fasta FAILED.
-- generate corrected reads attempt 2 begins with 148 finished, and 2 to compute.
----------------------------------------
-- Starting concurrent execution on Wed Jun 15 17:08:08 2022 with 8923.605 GB free disk space (2 processes; 12 concurrently)

    /home/canu/pnt/correction/2-correction/correctReads.sh 45 > /home/canu/pnt/correction/2-correction/correctReads.000045.out 2>&1
    /home/canu/pnt/correction/2-correction/correctReads.sh 111 > /home/canu/pnt/correction/2-correction/correctReads.000111.out 2>&1

-- Finished on Wed Jun 15 18:49:59 2022 (6111 seconds) with 8923.605 GB free disk space
----------------------------------------
--
-- 2 read correction jobs failed:
--   job /home/canu/pnt/correction/2-correction/correction_outputs/0045.fasta FAILED.
--   job /home/canu/pnt/correction/2-correction/correction_outputs/0111.fasta FAILED.
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'failed to generate corrected reads.  Made 2 attempts, jobs still failed'.
```

**Comment by skoren** [comment]
See similar errors in #2089. What do the failed jobs report at the end (e.g. post `/home/canu/pnt/correction/2-correction/correctReads.000045.out`)

**Comment by skoren** [comment]
Ah in that case #1784 and #1959 might be relevant. As it says there, we haven't seen a segmentation fault in that part of the code for a very long time and when we did, it was due to non-ACGT characters in the input data. What version of Canu are you running and how was it installed? Do you have non-ACGT characters in the input?

**Comment by skoren** [comment]
There's an example command in. #1959: `perl -i.bak -pe 's/[^[:ascii:]]//g' At.longest.4.fa`). You could start with that and try the assembly from scratch (assuming the above changes your file). We've also had issues in the past with conda installs being outdated (they perform a partial update) so I'd also suggest downloading the 2.2.1 release on this github page for your system and trying with that (you can re-start the existing assembly).

If neither of those work, are you able to share your input sequences? See the FAQ https://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you for instructions.

**Comment by bioramg** [comment]
Thank you.
Sir, I have used the same ONT reads for other assemblers such as spades assembler, Masurca, and Unicycler. There is no issue with that. If you wish, I can share my input sequences. How to share it? Please suggest me.

**Comment by 1372189477** [comment]
I also encountered the same problem when I assembled mitochondria, I reported an error at correct, and the generated file was empty at last. My input file was the result of Canu assembly before, I used minimap2 again mapping it, and wanted to assemble it again. Running memory is also sufficient
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'ovS' concurrent execution on Wed Jun 29 09:09:41 2022 with 6550.307 GB free disk space (2 processes; 62 concurrently)

    cd correction/suriana2.ovlStore.BUILDING
    ./scripts/2-sort.sh 1 > ./logs/2-sort.000001.out 2>&1
    ./scripts/2-sort.sh 2 > ./logs/2-sort.000002.out 2>&1

-- Finished on Wed Jun 29 09:09:43 2022 (2 seconds) with 6550.307 GB free disk space
----------------------------------------
--
-- Overlap store sorting jobs failed, retry.
--   job correction/suriana2.ovlStore.BUILDING/0001 FAILED.
--   job correction/suriana2.ovlStore.BUILDING/0002 FAILED.
--
-- No change in report.
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'ovS' concurrent execution on Wed Jun 29 09:09:43 2022 with 6550.307 GB free disk space (2 processes; 62 concurrently)

    cd correction/suriana2.ovlStore.BUILDING
    ./scripts/2-sort.sh 1 > ./logs/2-sort.000001.out 2>&1
    ./scripts/2-sort.sh 2 > ./logs/2-sort.000002.out 2>&1

-- Finished on Wed Jun 29 09:09:44 2022 (one second) with 6550.307 GB free disk space
----------------------------------------
--
-- Overlap store sorting jobs failed, tried 2 times, giving up.
--   job correction/suriana2.ovlStore.BUILDING/0001 FAILED.
--   job correction/suriana2.ovlStore.BUILDING/0002 FAILED.
--

ABORT:
ABORT: Canu branch hicanu_rc +325 changes (r9818 86bb2e221546c76437887d3a0ff5ab9546f85317)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
dell@dell-Precision-7920-Tower:/media/dell/OS/bic/program/hicanu/Linux-amd64/bin$ df -h
udev            248G     0  248G    0% /dev
tmpfs            50G  3.6M   50G    1% /run
/dev/sda6       338G   14G  307G    5% /
tmpfs           248G     0  248G    0% /dev/shm
tmpfs           5.0M  4.0K  5.0M    1% /run/lock
tmpfs           248G     0  248G    0% /sys/fs/cgroup
/dev/loop0      128K  128K     0  100% /snap/bare/5
/dev/loop1       56M   56M     0  100% /snap/core18/2128
/dev/loop2       56M   56M     0  100% /snap/core18/2409
/dev/loop3       51M   51M     0  100% /snap/snap-store/547
/dev/loop5       55M   55M     0  100% /snap/snap-store/558
/dev/loop4       82M   82M     0  100% /snap/gtk-common-themes/1534
/dev/loop6       62M   62M     0  100% /snap/core20/1518
/dev/loop8      219M  219M     0  100% /snap/gnome-3-34-1804/77
/dev/loop9      255M  255M     0  100% /snap/gnome-3-38-2004/106
/dev/loop7      219M  219M     0  100% /snap/gnome-3-34-1804/72
/dev/loop10      66M   66M     0  100% /snap/gtk-common-themes/1515
/dev/loop12      47M   47M     0  100% /snap/snapd/16010
/dev/loop11      45M   45M     0  100% /snap/snapd/15904
/dev/sda1       246M   45M  202M   19% /boot/efi
tmpfs            50G   20K   50G    1% /run/user/125
tmpfs            50G  104K   50G    1% /run/user/1000
/dev/sda3       7.0T  554G  6.4T    8% /media/dell/OS

**Comment by skoren** [comment]
@bioramg did you sent the data using the instructions on the FTP? The other assemblers you referenced are all hybrid based ones so I expect any invalid characters would have been ignored in the input.

**Comment by skoren** [comment]
See: https://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you:
```
Here is a quick walk-through using a command-line ftp client (should be available on most Linux and OSX installations). Say we want to transfer a file named reads.fastq. First, run ftp ftp.cbcb.umd.edu, specify anonymous as the user name and hit return for password (blank). Then cd incoming/sergek, put reads.fastq, and quit.

That’s it, you won’t be able to see the file but we can download it.
```

**Comment by bioramg** [comment]
Thank you.
I tried to reassemble with your suggestions using the command (perl -i.bak -pe 's/[^[:ascii:]]//g' At.longest.4.fa). But I am getting the same error.
Also, I tried to upload the sequence file. There is one issue. Please check it.

Connected to ftp.cbcb.umd.edu.
220-
220-Welcome to the CBCB FTP Server
220-
220-Please visit, http://www.cbcb.umd.edu
220-for more information.
220-
220
Name (ftp.cbcb.umd.edu:raman): anonymous
331 Please specify the password.
Password:
230 Login successful.
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> cd incoming/sergek
250 Directory successfully changed.
ftp> put reads.fastq
local: reads.fastq remote: reads.fastq
200 PORT command successful. Consider using PASV.
425 Failed to establish connection.

Thank you.

**Comment by skoren** [comment]
There was a truncated reads.fastq file that may have caused the issue. You can try again. If it still doesn't work, there is something on your end blocking the ftp connection, try using `ftp -p ftp.cbcb.umd.edu` instead as suggested here: https://superuser.com/questions/153888/ftp-error-425-failed-to-establish-connection

**Comment by bioramg** [comment]
Yes, I transferred my file (C320HAN.fastq.gz). Please check it. 
For your kind information, I used the command in the file (perl -i.bak -pe 's/[^[:ascii:]]//g' At.longest.4.fa) for Canu assembly
Thank you.

**Comment by skoren** [comment]
Unfortunately, the file you uploaded is corrupted. It is named fastq.gz but gzip says it is not properly formatted and the other common zip tools (e.g. bgzip, unzip) don't work either. It doesn't say it's a truncated file, just that it is not properly formatted. It also doesn't look like an uncompressed fastq. Could you try again, post the md5 here as well to make sure the transfer was OK.

As for your command with perl, that is an example assuming your input is At.longest.4.fa. If your input is named something else (should to be uncompressed fasta or fastq) like `C320HAN.fastq`, you'd have to run `perl -i.bak -pe 's/[^[:ascii:]]//g' C320HAN.fastq`, it will write a file named C320HAN.fastq.bak that will be the updated file with non-ascii matches removed. You'd then use the bak file as the input to the assembler.

**Comment by bioramg** [comment]
Thank you.
I am using the original read sequence. I shall update you after assembling the sequence.

**Comment by skoren** [comment]
Any update, were you able to re-upload the reads or run through the filtered set?

**Comment by bioramg** [comment]
Thank you for your kind response.
I tried with both fastq and fastq.bak format. I am getting the same issue. So, I could do it further. However, I uploaded reads.fastq.bak file in the server. Please check and do the needful.
Thank you, and looking forward to hearing from you.

**Comment by skoren** [comment]
I was able to download the data and launched a run. I will let you know if it finishes or crashes.

Do you really only have about 8x coverage? Did canu complain about this low level of coverage when you launched it? That check was added in v1.8 so if it didn't report an error and you didn't have to set the minInputCoverage parameter, I don't think you're using v2.2 and something must have gone wrong with the conda install.

**Comment by bioramg** [comment]
Is it possible to get a result from you after the assembly process?

Yes, I am having this ONT reads for the genome.

No. I assembled other plant mitochondrial genomes using Canu. I am getting an error with this genome sequence only. There is no issue with conda installation.

**Comment by skoren** [comment]
If you are able to run `canu -p pnt -d test genomeSize=1.36g -nanopore-raw reads.fastq.bak.gz` and don't get a message like:
```
-- ERROR:  Read coverage (8.87) lower than allowed.
-- ERROR:    minInputCoverage  = 10
-- ERROR:    stopOnLowCoverage = 10
-- ERROR:
-- ERROR:  This could be caused by an incorrect genomeSize or poor quality
-- ERROR:  reads that cound not be sufficiently corrected.
-- ERROR:
-- ERROR:  You can force Canu to continue by decreasing parameters
-- ERROR:  minInputCoverage and/or stopOnLowCoverage.  Be warned that the
-- ERROR:  quality of corrected reads and/or contiguity of contigs will be poor.
-- 
```
then it can't be v2.2 . You can see older issues where conda was reporting it installed canu 2.2 (or some up to date version) but actually the installation failed because the conda recipe was broken. I would suggest downloading the appropriate binary for your system from the release page instead to be sure which version you have.

My run on your data had no issues and completed. I don't see anything to fix so I'm going to close the issue. As I said above, I suspect an issue with the install. You can download the corrected reads here: https://obj.umiacs.umd.edu/sergek/shared/pnt.correctedReads.fasta.gz

**Comment by bioramg** [comment]
Thank you.
