### ISSUE TITLE
Resume killed run with grid from cor (correction) step

### ISSUE THREAD

**Issue by weilu1998** [marbl/canu#2138]
Hi,

I am using Canu 2.2 to generate assembly from nanopore reads (R9.4.1) with sup accuracy mode (roughly 1.7% error rates). The estimated genome size is around 300 Mb (heterozygosity around 2.2%, raw Flye assembly is around 500 Mb) and the total bases is 12.8Gb. Previously, when I started the run, I submit it to the PBS job system with one node (14 CPUs). After several days, the job is still at the cor step. I killed the job and trying to restart the job with more cores (28 CPUs). However, I cannot resume the job after resubmitting the job. Any advice on how to resume previous run? I tried to delete the bash scripts in the folder 2-correction and it didn't work. Do I need to submit the job to the same node with the same number of requested processor? Will appreciate any suggestion.

Job submission
```
canu \
 -p ${S} -d ${S}_canu \
 genomeSize=266m \
 -nanopore ${S}.passReads.${M}.fastq.gz
```

Previous local run information
```
-- Detected gnuplot version '4.2 patchlevel 6 ' (from 'gnuplot') and image format 'png'.
--
-- Detected 14 CPUs and 505 gigabytes of memory on the local machine.
--
-- Local machine mode enabled; grid support not detected or not allowed.
--
--                                (tag)Concurrency
--                         (tag)Threads          |
--                (tag)Memory         |          |
--        (tag)             |         |          |       total usage      algorithm
--        -------  ----------  --------   --------  --------------------  -----------------------------
-- Local: meryl     24.000 GB    7 CPUs x   2 jobs    48.000 GB  14 CPUs  (k-mer counting)
-- Local: hap       12.000 GB   14 CPUs x   1 job     12.000 GB  14 CPUs  (read-to-haplotype assignment)
-- Local: cormhap   13.000 GB   14 CPUs x   1 job     13.000 GB  14 CPUs  (overlap detection with mhap)
-- Local: obtovl     8.000 GB    7 CPUs x   2 jobs    16.000 GB  14 CPUs  (overlap detection)
-- Local: utgovl     8.000 GB    7 CPUs x   2 jobs    16.000 GB  14 CPUs  (overlap detection)
-- Local: cor        -.--- GB    4 CPUs x   - jobs     -.--- GB   - CPUs  (read correction)
-- Local: ovb        4.000 GB    1 CPU  x  14 jobs    56.000 GB  14 CPUs  (overlap store bucketizer)
-- Local: ovs        8.000 GB    1 CPU  x  14 jobs   112.000 GB  14 CPUs  (overlap store sorting)
-- Local: red       16.000 GB    6 CPUs x   2 jobs    32.000 GB  12 CPUs  (read error detection)
-- Local: oea        8.000 GB    1 CPU  x  14 jobs   112.000 GB  14 CPUs  (overlap error adjustment)
-- Local: bat       64.000 GB    8 CPUs x   1 job     64.000 GB   8 CPUs  (contig construction with bogart)
-- Local: cns        -.--- GB    8 CPUs x   - jobs     -.--- GB   - CPUs  (consensus)
--
-- Found untrimmed raw Nanopore reads in the input files.

```

**Comment by skoren** [comment]
What's the output when you try to run it on the grid?

**Comment by weilu1998** [comment]
@skoren Sorry for the late response. After checking more closely on the output, I just realize it was killed because of out of memory. I was able to resume the previous run today. Since it takes a long time to run, will you recommend do some raw reads filtering using nanofilt (higher q-score threshold like 10 and remove reads shorter than 10k)? Or maybe the real time limiting step is not at the correction step. Thanks.

**Comment by skoren** [comment]
No we typically don't filter the data and let the correction figure out which to keep. You could try the parameters for uncorrected ONT assembly (https://canu.readthedocs.io/en/latest/quick-start.html#assembling-with-multiple-technologies-and-multiple-files) as that might be faster.

Since you've resolved the original issue, I'll close this one. Please open a new one if you encounter an error with whatever message it reports.
