### ISSUE TITLE
canu MaxMemPerLimit issue

### ISSUE THREAD

**Issue by LennWhy** [marbl/canu#2140]
Hi,

I am new to Canu and trying to assemble a genome following the tutorial (three top level task approach). I've managed to correct and trim the reads, however when I try to assemble the output on my institute cluster, my job keeps pending and the reason is 'MaxMemPerLimit'. 

I am unsure of the limitations of my institute HPC, but I reckon vertebrate genomes have been assembled on it before. My estimated genome size is about 500MB. Can you please provide some guidance on how I could potentially bypass this memory or thread issue? 

Thanks and sorry if this problem has been asked before or if it's an easy problem to solve.

**Comment by brianwalenz** [comment]
Can you post the logs?  Two pieces, one where it reports how much memory/threads each stage is allowed to use (it's a table) and one with the sbatch/qsub command that fails.

Each stage in the pipeline has a configuration to set memory and threads.  once you figure out which stage is the problem, you can try to reduce requirements and the algorithms will adjust.  Threads can generally be reduced at will; it will just run for a longer time.  However, some stages, like consensus, just need memory and so will fail when the memory limit is reduced.

See https://canu.readthedocs.io/en/latest/tutorial.html#module-tags and the following section https://canu.readthedocs.io/en/latest/tutorial.html#execution-configuration.

**Comment by LennWhy** [comment]
Thank you for your quick reply. Please see the log below.

#####
Wed 29 Jun 21:25:17 BST 2022
Running a program on 8 CPU cores
Wed 29 Jun 21:25:18 BST 2022
-- canu 2.2
--
-- CITATIONS
--
-- For 'standard' assemblies of PacBio or Nanopore reads:
--   Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
--   Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
--   Genome Res. 2017 May;27(5):722-736.
--   http://doi.org/10.1101/gr.215087.116
-- 
-- Read and contig alignments during correction and consensus use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_201' (from 'java') with -d64 support.
--
-- WARNING:
-- WARNING:  Failed to run gnuplot using command 'gnuplot'.
-- WARNING:  Plots will be disabled.
-- WARNING:
--
--
-- Detected 8 CPUs and 37600 gigabytes of memory on the local machine.
--
-- Detected Slurm with 'sinfo' binary in /cm/shared/apps/slurm/18.08.4/bin/sinfo.
-- Detected Slurm with task IDs up to 100 allowed.
-- 
-- Slurm support detected.  Resources available:
--     10 hosts with  80 cores and  187 GB memory.
--      1 host  with 128 cores and 2014 GB memory.
--      6 hosts with  72 cores and  754 GB memory.
--      2 hosts with  96 cores and  251 GB memory.
--      1 host  with 128 cores and 2015 GB memory.
--      1 host  with  40 cores and  375 GB memory.
--      2 hosts with  64 cores and  251 GB memory.
--      1 host  with 128 cores and 1003 GB memory.
--      1 host  with  48 cores and  251 GB memory.
--      2 hosts with  64 cores and  187 GB memory.
--
-- Job limits:
--      8 CPUs              (maxThreads option).
--
--                         (tag)Threads
--                (tag)Memory         |
--        (tag)             |         |  algorithm
--        -------  ----------  --------  -----------------------------
-- Grid:  meryl     18.000 GB    8 CPUs  (k-mer counting)
-- Grid:  hap       12.000 GB    8 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   18.000 GB    8 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    16.000 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl    16.000 GB    8 CPUs  (overlap detection)
-- Grid:  cor        -.--- GB    4 CPUs  (read correction)
-- Grid:  ovb        4.000 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       16.000 GB    1 CPU   (overlap store sorting)
-- Grid:  red       18.000 GB    8 CPUs  (read error detection)
-- Grid:  oea        8.000 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      256.000 GB    8 CPUs  (contig construction with bogart)
-- Grid:  cns        -.--- GB    8 CPUs  (consensus)
--
-- Found PacBio CLR reads in 'canu_RcaF.seqStore':
--   Libraries:
--     PacBio CLR:            1
--   Reads:
--     Corrected:             11102908429
--     Corrected and Trimmed: 11102908429
--
--
-- Generating assembly 'canu_RcaF' in '/nobackup/beegfs/workspace/lly201/projects/cobia_long/canu_RcaF-erate-0.039':
--   genomeSize:
--     500000000
--
--   Overlap Generation Limits:
--     corOvlErrorRate 0.2400 ( 24.00%)
--     obtOvlErrorRate 0.0390 (  3.90%)
--     utgOvlErrorRate 0.0390 (  3.90%)
--
--   Overlap Processing Limits:
--     corErrorRate    0.2500 ( 25.00%)
--     obtErrorRate    0.0390 (  3.90%)
--     utgErrorRate    0.0390 (  3.90%)
--     cnsErrorRate    0.0390 (  3.90%)
--
--   Stages to run:
--     assemble corrected and trimmed reads.
--
--
-- Correction skipped; not enabled.
--
-- Trimming skipped; not enabled.
--
-- BEGIN ASSEMBLY
--
-- Running jobs.  First attempt out of 2.
--
-- 'unitigger.jobSubmit-01.sh' -> job 3361554 task 1.
--
----------------------------------------
-- Starting command on Wed Jun 29 21:25:19 2022 with 66953.995 GB free disk space

    cd /nobackup/beegfs/workspace/lly201/projects/cobia_long/canu_RcaF-erate-0.039
    sbatch \
      --depend=afterany:3361554 \
      --cpus-per-task=1 \
      --mem-per-cpu=4g   \
      -D `pwd` \
      -J 'canu_canu_RcaF' \
      -o canu-scripts/canu.11.out  canu-scripts/canu.11.sh
Submitted batch job 3361555

-- Finished on Wed Jun 29 21:25:19 2022 (like a bat out of hell) with 66953.995 GB free disk space

####

Let me know if you need anything else.

**Comment by brianwalenz** [comment]
Yup, those were the bits I was after.  `batMemory` is what you want to change.  It's currently requesting 256GB.  Try halving it until it runs - `batMemory=128`, then `batMemory=64`, etc.

You can, with effort, see your Slurm job limits with the following:
```
sacctmgr -np show qos format=Name,MaxTRESPerUser,MaxTresPerJob
```
which, on my cluster, reports:
```
norm_part|cpu=10000,mem=60T|node=1|
```
Each item in the format list is separated by a '|'.  This will report the name of the partition, the limits for all jobs I run, and the limits for a single job: in the `norm` partition, I'm limited to 10,000 CPUs and 60 TB (for the sum of all my jobs) and each job can run on a single node (`node=1`).  There might be a better way to find this for your cluster.

**Comment by LennWhy** [comment]
Many thanks for this Brian! It worked.
