### ISSUE TITLE
Questions about correction step from user 1372189477 

### ISSUE THREAD

**Issue by skoren** [marbl/canu#2141]
I want to know why it took me a day to finish using Canu before, but now it takes me 5 days or more, and there is no error. But triming and Unitigging need a long time, and the parameters I use have not changed. This is the process of running data.

```
-- Removing meryl database 'unitigging/0-mercounts/suriana.ms22'.

-- OVERLAPPER (normal) (assembly) erate=0.12

-- Starting command on Mon Jun 27 07:15:12 2022 with 6650.158 GB free disk space

cd unitigging/1-overlapper
/media/dell/OS/bic/program/canu-2.2.Linux-amd64/canu-2.2/bin/overlapInCorePartition \
 -S  ../../suriana.seqStore \
 -hl 80000000 \
 -rl 1000000000 \
 -ol 500 \
 -o  ./suriana.partition \
> ./suriana.partition.err 2>&1
-- Finished on Mon Jun 27 07:15:12 2022 (in the blink of an eye) with 6650.158 GB free disk space

--
-- Configured 2 overlapInCore jobs.
-- Finished stage 'utg-overlapConfigure', reset canuIteration.

-- Running jobs. First attempt out of 2.

-- Starting 'utgovl' concurrent execution on Mon Jun 27 07:15:12 2022 with 6650.158 GB free disk space (2 processes; 14 concurrently)

cd unitigging/1-overlapper
./overlap.sh 1 > ./overlap.000001.out 2>&1
./overlap.sh 2 > ./overlap.000002.out 2>&1
```

**Comment by skoren** [comment]
I also encountered the same problem when I assembled mitochondria, I reported an error at correct, and the generated file was empty at last. My input file was the result of Canu assembly before, I used minimap2 again mapping it, and wanted to assemble it again. Running memory is also sufficient
```
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'ovS' concurrent execution on Wed Jun 29 09:09:41 2022 with 6550.307 GB free disk space (2 processes; 62 concurrently)

    cd correction/suriana2.ovlStore.BUILDING
    ./scripts/2-sort.sh 1 > ./logs/2-sort.000001.out 2>&1
    ./scripts/2-sort.sh 2 > ./logs/2-sort.000002.out 2>&1

-- Finished on Wed Jun 29 09:09:43 2022 (2 seconds) with 6550.307 GB free disk space
----------------------------------------
--
-- Overlap store sorting jobs failed, retry.
--   job correction/suriana2.ovlStore.BUILDING/0001 FAILED.
--   job correction/suriana2.ovlStore.BUILDING/0002 FAILED.
--
-- No change in report.
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'ovS' concurrent execution on Wed Jun 29 09:09:43 2022 with 6550.307 GB free disk space (2 processes; 62 concurrently)

    cd correction/suriana2.ovlStore.BUILDING
    ./scripts/2-sort.sh 1 > ./logs/2-sort.000001.out 2>&1
    ./scripts/2-sort.sh 2 > ./logs/2-sort.000002.out 2>&1

-- Finished on Wed Jun 29 09:09:44 2022 (one second) with 6550.307 GB free disk space
----------------------------------------
--
-- Overlap store sorting jobs failed, tried 2 times, giving up.
--   job correction/suriana2.ovlStore.BUILDING/0001 FAILED.
--   job correction/suriana2.ovlStore.BUILDING/0002 FAILED.
--

ABORT:
ABORT: Canu branch hicanu_rc +325 changes (r9818 86bb2e221546c76437887d3a0ff5ab9546f85317)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
dell@dell-Precision-7920-Tower:/media/dell/OS/bic/program/hicanu/Linux-amd64/bin$ df -h
udev            248G     0  248G    0% /dev
tmpfs            50G  3.6M   50G    1% /run
/dev/sda6       338G   14G  307G    5% /
tmpfs           248G     0  248G    0% /dev/shm
tmpfs           5.0M  4.0K  5.0M    1% /run/lock
tmpfs           248G     0  248G    0% /sys/fs/cgroup
/dev/loop0      128K  128K     0  100% /snap/bare/5
/dev/loop1       56M   56M     0  100% /snap/core18/2128
/dev/loop2       56M   56M     0  100% /snap/core18/2409
/dev/loop3       51M   51M     0  100% /snap/snap-store/547
/dev/loop5       55M   55M     0  100% /snap/snap-store/558
/dev/loop4       82M   82M     0  100% /snap/gtk-common-themes/1534
/dev/loop6       62M   62M     0  100% /snap/core20/1518
/dev/loop8      219M  219M     0  100% /snap/gnome-3-34-1804/77
/dev/loop9      255M  255M     0  100% /snap/gnome-3-38-2004/106
/dev/loop7      219M  219M     0  100% /snap/gnome-3-34-1804/72
/dev/loop10      66M   66M     0  100% /snap/gtk-common-themes/1515
/dev/loop12      47M   47M     0  100% /snap/snapd/16010
/dev/loop11      45M   45M     0  100% /snap/snapd/15904
/dev/sda1       246M   45M  202M   19% /boot/efi
tmpfs            50G   20K   50G    1% /run/user/125
tmpfs            50G  104K   50G    1% /run/user/1000
/dev/sda3       7.0T  554G  6.4T    8% /media/dell/OS
```

**Comment by skoren** [comment]
@1372189477 please don't hijack other issues, especially with completely unrelated questions or errors. I removed your original comments and opened a new issue.

Canu hasn't changed how it constructs the store so to answer your question, if it's the same version and data, it would likely be a change on your system. If you've changed versions, you should see the FAQ which addresses how you can speed up overlapping. 

Your second error likely indicates a disk problem but it looks like it's a different version of Canu than your first run. It's also out of date. I suggest using the released version for your all your experiments. If you update to v2.2.1 and still have an error, post the log from the failing step (e.g. `correction/suriana2.ovlStore.BUILDING/logs/2-sort.000001.out`).

**Comment by 1372189477** [comment]
Dear sir ,
Can I use Hicanu if my data is not HIFI data? My previous data is also not HiFI data, but it can run successfully, so I still don't know why it is running so long, but It's not wrong, Trimming only uses 8 threads, it is still running.

For the second question, I used Hicanu to report the same error, but I used Canu2.2, it can run successfully, the problem has been solved, but I want to know why, thank you for your help

**Comment by skoren** [comment]
You can use HiFi mode with any data but that doesn't mean it will work, you may get no assembly or a much smaller assembly than you expect. HiFi mode works with defaults on duplex data (see: https://www.keygene.com/news-events/maize-b73-oxford-nanopore-duplex-sequence-data-release/) and it works with modified parameters on some newer ONT data (see https://canu.readthedocs.io/en/latest/quick-start.html#assembling-with-multiple-technologies-and-multiple-files).

As for why 2.2 worked and the older branch you were using didn't, that's easy, there were many fixes since then. The version you were using before was a very outdated version of hicanu, hicanu can be used in 2.2 as well, assuming your data is compatible.

**Comment by skoren** [comment]
Idle
