### ISSUE TITLE
Failed to find number of jobs

### ISSUE THREAD

**Issue by paracontias** [marbl/canu#2143]
Hello,

I would like to trio-bin ONT reads. I use an AWS EC2 instance with 96 CPU and 256 GB RAM. I use this command:

canu-2.2/bin/canu -haplotype -p asm -d /s3/ont/trio-1 genomeSize=857m -haplotypeA /s3/pe150/bbduk/A-r1-adapt-trim.fq /s3/pe150/bbduk/A-r2-adapt-trim.fq -haplotypeB /s3/pe150/bbduk/B-r1-adapt-trim.fq /s3/pe150/bbduk/B-r2-adapt-trim.fq -nanopore /s3/ont/q7pc/*.fastq.gz

The short reads separate in ~130 files and then I receive an error. When I repeat the command I get this result:
```
-- Detected 96 CPUs and 185 gigabytes of memory on the local machine.
--
-- Local machine mode enabled; grid support not detected or not allowed.
--
--                (tag)Concurrency
--             (tag)Threads     |
--        (tag)Memory     |     |
--    (tag)       |     |     |    total usage   algorithm
--    ------- ---------- --------  -------- -------------------- -----------------------------
-- Local: meryl   15.000 GB  8 CPUs x 12 jobs  180.000 GB 96 CPUs (k-mer counting)
-- Local: hap    12.000 GB  24 CPUs x  4 jobs  48.000 GB 96 CPUs (read-to-haplotype assignment)
-- Local: cormhap  30.000 GB  16 CPUs x  6 jobs  180.000 GB 96 CPUs (overlap detection with mhap)
-- Local: obtovl  16.000 GB  16 CPUs x  6 jobs  96.000 GB 96 CPUs (overlap detection)
-- Local: utgovl  16.000 GB  16 CPUs x  6 jobs  96.000 GB 96 CPUs (overlap detection)
-- Local: cor    -.--- GB  4 CPUs x  - jobs   -.--- GB  - CPUs (read correction)
-- Local: ovb    4.000 GB  1 CPU x 46 jobs  184.000 GB 46 CPUs (overlap store bucketizer)
-- Local: ovs    16.000 GB  1 CPU x 11 jobs  176.000 GB 11 CPUs (overlap store sorting)
-- Local: red    16.000 GB  8 CPUs x 11 jobs  176.000 GB 88 CPUs (read error detection)
-- Local: oea    8.000 GB  1 CPU x 23 jobs  184.000 GB 23 CPUs (overlap error adjustment)
-- Local: bat   185.000 GB  16 CPUs x  1 job  185.000 GB 16 CPUs (contig construction with bogart)
-- Local: cns    -.--- GB  8 CPUs x  - jobs   -.--- GB  - CPUs (consensus)
--
-- Found untrimmed raw Nanopore reads in the input files.
--
-- Generating assembly ‘asm’ in ‘/s3/ont/trio-2’:
--  genomeSize:
--   857000000
--
--  Overlap Generation Limits:
--   corOvlErrorRate 0.3200 ( 32.00%)
--   obtOvlErrorRate 0.1200 ( 12.00%)
--   utgOvlErrorRate 0.1200 ( 12.00%)
--
--  Overlap Processing Limits:
--   corErrorRate  0.3000 ( 30.00%)
--   obtErrorRate  0.1200 ( 12.00%)
--   utgErrorRate  0.1200 ( 12.00%)
--   cnsErrorRate  0.2000 ( 20.00%)
--
--  Stages to run:
--   only separate reads into haplotypes.
--
--
-- BEGIN HAPLOTYPING
--
-- Running jobs. First attempt out of 2.
----------------------------------------
-- Starting ‘meryl’ concurrent execution on Fri Jul 8 17:05:22 2022 with 17179869183.984 GB free disk space (4 processes; 12 concurrently)
  cd haplotype/0-kmers
  ./meryl-count.sh 1 > ./meryl-count.000001.out 2>&1
  ./meryl-count.sh 2 > ./meryl-count.000002.out 2>&1
  ./meryl-count.sh 4 > ./meryl-count.000004.out 2>&1
  ./meryl-count.sh 11 > ./meryl-count.000011.out 2>&1
sh: 1: cannot create ./meryl-count.000001.out: Bad file descriptor
sh: 1: cannot create ./meryl-count.000002.out: Bad file descriptor
sh: 1: cannot create ./meryl-count.000004.out: Bad file descriptor
sh: 1: cannot create ./meryl-count.000011.out: Bad file descriptor
-- Finished on Fri Jul 8 17:05:22 2022 (furiously fast) with 17179869183.984 GB free disk space
----------------------------------------
ABORT:
ABORT: canu 2.2
ABORT: Don’t panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting. If that doesn’t work, ask for help.
ABORT:
ABORT:  failed to find the number of jobs in ‘haplotype/0-kmers/meryl-count.sh’.
ABORT:
```
It is not clear to me if 'bad file descriptor' or ´failed to find the number of jobs' is the actual problem. 

Thank you for your help.

**Comment by paracontias** [comment]
I try again with 'useGrid=false' and get another error, 

'ob haplotype/0-kmers/meryl-merge.sh 2 creating haplotype/0-kmers/reads-A.meryl FAILED'

'-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '11.0.15' (from 'java') without -d64 support.
--
-- WARNING:
-- WARNING:  Failed to run gnuplot using command 'gnuplot'.
-- WARNING:  Plots will be disabled.
-- WARNING:
--
--
-- Detected 96 CPUs and 185 gigabytes of memory on the local machine.
--
-- Local machine mode enabled; grid support not detected or not allowed.
--
--                                (tag)Concurrency
--                         (tag)Threads          |
--                (tag)Memory         |          |
--        (tag)             |         |          |       total usage      algorithm
--        -------  ----------  --------   --------  --------------------  -----------------------------
-- Local: meryl     15.000 GB    8 CPUs x  12 jobs   180.000 GB  96 CPUs  (k-mer counting)
-- Local: hap       12.000 GB   24 CPUs x   4 jobs    48.000 GB  96 CPUs  (read-to-haplotype assignment)
-- Local: cormhap   30.000 GB   16 CPUs x   6 jobs   180.000 GB  96 CPUs  (overlap detection with mhap)
-- Local: obtovl    16.000 GB   16 CPUs x   6 jobs    96.000 GB  96 CPUs  (overlap detection)
-- Local: utgovl    16.000 GB   16 CPUs x   6 jobs    96.000 GB  96 CPUs  (overlap detection)
-- Local: cor        -.--- GB    4 CPUs x   - jobs     -.--- GB   - CPUs  (read correction)
-- Local: ovb        4.000 GB    1 CPU  x  46 jobs   184.000 GB  46 CPUs  (overlap store bucketizer)
-- Local: ovs       16.000 GB    1 CPU  x  11 jobs   176.000 GB  11 CPUs  (overlap store sorting)
-- Local: red       16.000 GB    8 CPUs x  11 jobs   176.000 GB  88 CPUs  (read error detection)
-- Local: oea        8.000 GB    1 CPU  x  23 jobs   184.000 GB  23 CPUs  (overlap error adjustment)
-- Local: bat      185.000 GB   16 CPUs x   1 job    185.000 GB  16 CPUs  (contig construction with bogart)
-- Local: cns        -.--- GB    8 CPUs x   - jobs     -.--- GB   - CPUs  (consensus)
--
-- Found untrimmed raw Nanopore reads in the input files.
--
-- Generating assembly 'asm' in '/s3/ont/trio-3':
--   genomeSize:
--     857000000
--
--   Overlap Generation Limits:
--     corOvlErrorRate 0.3200 ( 32.00%)
--     obtOvlErrorRate 0.1200 ( 12.00%)
--     utgOvlErrorRate 0.1200 ( 12.00%)
--
--   Overlap Processing Limits:
--     corErrorRate    0.3000 ( 30.00%)
--     obtErrorRate    0.1200 ( 12.00%)
--     utgErrorRate    0.1200 ( 12.00%)
--     cnsErrorRate    0.2000 ( 20.00%)
--
--   Stages to run:
--     only separate reads into haplotypes.
--
--
-- BEGIN HAPLOTYPING
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'meryl' concurrent execution on Fri Jul  8 18:23:29 2022 with 17179869183.984 GB free disk space (4 processes; 12 concurrently)

    cd haplotype/0-kmers
    ./meryl-count.sh 3 > ./meryl-count.000003.out 2>&1
    ./meryl-count.sh 4 > ./meryl-count.000004.out 2>&1
    ./meryl-count.sh 5 > ./meryl-count.000005.out 2>&1
    ./meryl-count.sh 9 > ./meryl-count.000009.out 2>&1

-- Finished on Fri Jul  8 18:30:34 2022 (425 seconds) with 17179869183.984 GB free disk space
----------------------------------------
-- Found 12 Kmer counting (meryl-count) outputs.
-- Finished stage 'haplotype-merylCountCheck', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'meryl' concurrent execution on Fri Jul  8 18:30:34 2022 with 17179869183.984 GB free disk space (2 processes; 12 concurrently)

    cd haplotype/0-kmers
    ./meryl-merge.sh 1 > ./meryl-merge.000001.out 2>&1
    ./meryl-merge.sh 2 > ./meryl-merge.000002.out 2>&1

-- Finished on Fri Jul  8 18:33:49 2022 (195 seconds) with 17179869183.984 GB free disk space
----------------------------------------
--
-- Kmer counting (meryl-merge) jobs failed, retry.
--   job haplotype/0-kmers/meryl-merge.sh 2 creating haplotype/0-kmers/reads-A.meryl FAILED.
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'meryl' concurrent execution on Fri Jul  8 18:33:49 2022 with 17179869183.984 GB free disk space (1 processes; 12 concurrently)

    cd haplotype/0-kmers
    ./meryl-merge.sh 2 > ./meryl-merge.000002.out 2>&1

-- Finished on Fri Jul  8 18:33:51 2022 (2 seconds) with 17179869183.984 GB free disk space
----------------------------------------
--
-- Kmer counting (meryl-merge) jobs failed, tried 2 times, giving up.
--   job haplotype/0-kmers/meryl-merge.sh 2 creating haplotype/0-kmers/reads-A.meryl FAILED.
--

ABORT:
ABORT: canu 2.2
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:'

**Comment by skoren** [comment]
useGrid=false isn't going to make any difference, you had no grid available anyway. It seems your node has some file system issues or isn't configured properly. The bad file descriptor error is the real issue but might be secondary to the initial failure which you didn't post the details of. T

he folders have different names so are you re-running the command from scratch each time? Post the log from one of the failed jobs (e.g. `meryl-merge.000002.out` from your last run).

**Comment by paracontias** [comment]
In this attempt (trio-3) I repeated the initial command with useGrid=false, in order to re-use the parental read splitting. This seems to get past meryl-count and then fails on meryl-merge. 

Here is meryl-merge.000002.out:

'
Found perl:
   /usr/bin/perl
   This is perl 5, version 30, subversion 0 (v5.30.0) built for x86_64-linux-gnu-thread-multi

Found java:
   /usr/bin/java
   openjdk version "11.0.15" 2022-04-19

Found canu:
   /root/canu-2.2/bin/canu
   canu 2.2

Running job 2 based on command line options.
usage: /root/canu-2.2/bin/meryl ...

  A meryl command line is formed as a series of commands and files, possibly
  grouped using square brackets.  Each command operates on the file(s) that
  are listed after it.

  COMMANDS:

    statistics           display total, unique, distnict, present number of the kmers on the screen.  accepts exactly one input.
    histogram            display kmer frequency on the screen as 'frequency<tab>count'.  accepts exactly one input.
    print                display kmers on the screen as 'kmer<tab>count'.  accepts exactly one input.

    count                Count the occurrences of canonical kmers in the input.  must have 'output' specified.
    count-forward        Count the occurrences of forward kmers in the input.  must have 'output' specified.
    count-reverse        Count the occurrences of reverse kmers in the input.  must have 'output' specified.
      k=<K>              create mers of size K bases (mandatory).
      n=<N>              expect N mers in the input (optional; for precise memory sizing).
      memory=M           use no more than (about) M GB memory.
      threads=T          use no more than T threads.
      compress           compress homopolymer runs to a single letter.

    less-than N          return kmers that occur fewer than N times in the input.  accepts exactly one input.
    greater-than N       return kmers that occur more than N times in the input.  accepts exactly one input.
    equal-to N           return kmers that occur exactly N times in the input.  accepts exactly one input.
    not-equal-to N       return kmers that do not occur exactly N times in the input.  accepts exactly one input.

    increase X           add X to the count of each kmer.
    decrease X           subtract X from the count of each kmer.
    multiply X           multiply the count of each kmer by X.
    divide X             divide the count of each kmer by X.
    divide-round X       divide the count of each kmer by X and round results. count < X will become 1.
    modulo X             set the count of each kmer to the remainder of the count divided by X.

    union                return kmers that occur in any input, set the count to the number of inputs with this kmer.
    union-min            return kmers that occur in any input, set the count to the minimum count
    union-max            return kmers that occur in any input, set the count to the maximum count
    union-sum            return kmers that occur in any input, set the count to the sum of the counts

    intersect            return kmers that occur in all inputs, set the count to the count in the first input.
    intersect-min        return kmers that occur in all inputs, set the count to the minimum count.
    intersect-max        return kmers that occur in all inputs, set the count to the maximum count.
    intersect-sum        return kmers that occur in all inputs, set the count to the sum of the counts.

    subtract             return kmers that occur in the first input, subtracting counts from the other inputs

    difference           return kmers that occur in the first input, but none of the other inputs
    symmetric-difference return kmers that occur in exactly one input

  MODIFIERS:

    output O             write kmers generated by the present command to an output  meryl database O
                         mandatory for count operations.

  EXAMPLES:

  Example:  Report 22-mers present in at least one of input1.fasta and input2.fasta.
            Kmers from each input are saved in meryl databases 'input1' and 'input2',
            but the kmers in the union are only reported to the screen.

            meryl print \
                    union \
                      [count k=22 input1.fasta output input1] \
                      [count k=22 input2.fasta output input2]

  Example:  Find the highest count of each kmer present in both files, save the kmers to
            database 'maxCount'.

            meryl intersect-max input1 input2 output maxCount

  Example:  Find unique kmers common to both files.  Brackets are necessary
            on the first 'equal-to' command to prevent the second 'equal-to' from
            being used as an input to the first 'equal-to'.

            meryl intersect [equal-to 1 input1] equal-to 1 input2

Can't interpret './reads-PR-011.meryl': not a meryl command, option, or recognized input file.
usage: /root/canu-2.2/bin/meryl ...

  A meryl command line is formed as a series of commands and files, possibly
  grouped using square brackets.  Each command operates on the file(s) that
  are listed after it.

  COMMANDS:

    statistics           display total, unique, distnict, present number of the kmers on the screen.  accepts exactly one input.
    histogram            display kmer frequency on the screen as 'frequency<tab>count'.  accepts exactly one input.
    print                display kmers on the screen as 'kmer<tab>count'.  accepts exactly one input.

    count                Count the occurrences of canonical kmers in the input.  must have 'output' specified.
    count-forward        Count the occurrences of forward kmers in the input.  must have 'output' specified.
    count-reverse        Count the occurrences of reverse kmers in the input.  must have 'output' specified.
      k=<K>              create mers of size K bases (mandatory).
      n=<N>              expect N mers in the input (optional; for precise memory sizing).
      memory=M           use no more than (about) M GB memory.
      threads=T          use no more than T threads.
      compress           compress homopolymer runs to a single letter.

    less-than N          return kmers that occur fewer than N times in the input.  accepts exactly one input.
    greater-than N       return kmers that occur more than N times in the input.  accepts exactly one input.
    equal-to N           return kmers that occur exactly N times in the input.  accepts exactly one input.
    not-equal-to N       return kmers that do not occur exactly N times in the input.  accepts exactly one input.

    increase X           add X to the count of each kmer.
    decrease X           subtract X from the count of each kmer.
    multiply X           multiply the count of each kmer by X.
    divide X             divide the count of each kmer by X.
    divide-round X       divide the count of each kmer by X and round results. count < X will become 1.
    modulo X             set the count of each kmer to the remainder of the count divided by X.

    union                return kmers that occur in any input, set the count to the number of inputs with this kmer.
    union-min            return kmers that occur in any input, set the count to the minimum count
    union-max            return kmers that occur in any input, set the count to the maximum count
    union-sum            return kmers that occur in any input, set the count to the sum of the counts

    intersect            return kmers that occur in all inputs, set the count to the count in the first input.
    intersect-min        return kmers that occur in all inputs, set the count to the minimum count.
    intersect-max        return kmers that occur in all inputs, set the count to the maximum count.
    intersect-sum        return kmers that occur in all inputs, set the count to the sum of the counts.

    subtract             return kmers that occur in the first input, subtracting counts from the other inputs

    difference           return kmers that occur in the first input, but none of the other inputs
    symmetric-difference return kmers that occur in exactly one input

  MODIFIERS:

    output O             write kmers generated by the present command to an output  meryl database O
                         mandatory for count operations.

  EXAMPLES:

  Example:  Report 22-mers present in at least one of input1.fasta and input2.fasta.
            Kmers from each input are saved in meryl databases 'input1' and 'input2',
            but the kmers in the union are only reported to the screen.

            meryl print \
                    union \
                      [count k=22 input1.fasta output input1] \
                      [count k=22 input2.fasta output input2]

  Example:  Find the highest count of each kmer present in both files, save the kmers to
            database 'maxCount'.

            meryl intersect-max input1 input2 output maxCount

  Example:  Find unique kmers common to both files.  Brackets are necessary
            on the first 'equal-to' command to prevent the second 'equal-to' from
            being used as an input to the first 'equal-to'.

            meryl intersect [equal-to 1 input1] equal-to 1 input2

Can't interpret './reads-A.meryl': not a meryl command, option, or recognized input file.'

**Comment by paracontias** [comment]
Dear Sergey:

The command finishes when I output to an attached ephemeral NVMe drive and
not to the S3 bucket.

So yes, filesystem related.

Also now I use an instance with 64 ARM cores and 256 Gb RAM.

Thank you!
