### ISSUE TITLE
mhapConvert failed for some files

### ISSUE THREAD

**Issue by tangerzhang** [marbl/canu#215]
Hi,
I am running mhap step right now. However, I got errors for some files.
Please see below for the error information.
Is there any way to fix it? Thanks!

Opened fasta file /public4/zhangxt/project/1_canu/run2/correction/1-overlapper/blocks/000022.dat.
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
Current # sequences loaded and processed from file: 40000...
Current # sequences loaded and processed from file: 45000...
Current # sequences loaded and processed from file: 50000...
Current # sequences loaded and processed from file: 55000...
Current # sequences loaded and processed from file: 60000...
Current # sequences loaded and processed from file: 65000...
Current # sequences loaded and processed from file: 70000...
Current # sequences loaded and processed from file: 75000...
Current # sequences loaded and processed from file: 80000...
Current # sequences loaded and processed from file: 85000...
Current # sequences loaded and processed from file: 90000...
Processed 93000 to sequences.
Time (s) to score, hash to-file, and output: 32.894866686
Total scoring time (s): 393.02564713000004
Total time (s): 394.058691278
MinHash search time (s): 88.86131710800001
Total matches found: 22382992
Average number of matches per lookup: 18.091271926066863
Average number of table elements processed per lookup: 200.33475048212696
Average number of table elements processed per match: 11.073558083745015
Average % of hashed sequences hit per lookup: 2.080827946643766
Average % of hashed sequences hit that are matches: 18.502375236966966
Average % of hashed sequences fully compared that are matches: 80.69260328714594
mhapConvert: mhap/mhapConvert.C:116: int main(int, char**): Assertion `W[4][0] == '0'' failed.
/public1/software/sge-8.1.7/default/spool/node1/job_scripts/111900: line 1538:  1297 Aborted                 (core dumped) $bin/mhapConvert $cvt -o /public4/zhangxt/project/1_canu/run2/correction/1-overlapper/results/$qry.mhap.ovb.WORKING.gz /public4/zhangxt/project/1_canu/run2/correction/1-overlapper/results/$qry.mhap

**Comment by skoren** [comment]
This looks like the output file from MHAP is corrupt, there are no other errors in this step so I would guess either that your FS ran out of space or there was another disk issue. You can check the output files for the failed runs to make sure each line has 12 columns and the 5th column is always 0. You can also look for lines where the 5th column isn't 0.

You can try re-running the failed step, though Canu should re-run it for you, after confirming you're not out of space.

**Comment by tangerzhang** [comment]
Thanks, Skoren!
I should have enough storage either in nodes and local computer. But not sure whether it is a disk issue.
I did detect several lines with the 5th != 0, tough have no idea why that happens.
I remove those lines and re-run canu. That rescue me!

**Comment by skoren** [comment]
What was column 5, 1 instead of 0? Can you post some of those lines here.

**Comment by tangerzhang** [comment]
Sure! Please see below:

11167 1615 0.168841 26.000000 1 1611 2946 3141 0 5401 6618 6647
11167 2167 0.192516 83.000000 1 878 2777 3141 1 118 2028 2090
11167 921 0.183320 87.000000 1 16 2471 3141 1 807 3255 3475
11167 2324 0.210197 31.000000 1 1480 2793 3141 1 508 1820 2637
11167 1264 0.184888 43.000000 1 287 2958 3141 1 4656 7372 11620
11167 2166 0.181011 46.000000 1 801 2943 3141 0 3596 5695 5706

**Comment by brianwalenz** [comment]
This is very puzzling.  Can you share the data?

Has it happened again?  If you rerun this, or encounter it again, set 'saveOverlaps=true' to save intermediate outputs.  These will help us figure out what is going wrong.

**Comment by tangerzhang** [comment]
Hi Brian,
Thanks for your email.
I thought it might be the problem of interrupt files due to disk issue. I
re-run the whole progress and the problem disappears.


2016-08-11 3:26 GMT+08:00 brianwalenz <notifications@github.com>:

**Comment by brianwalenz** [comment]
Hopefully we won't ever see this happen again.  Thanks for rerunning.
