### ISSUE TITLE
Parameter setting in Configure.pm file

### ISSUE THREAD

**Issue by wuyangChin** [marbl/canu#2152]
Hi,
I'm confused about the underlying logic behind some parameter settings in Configure.pm file. 
for example, the 'corPartitions' parameter used in falconsense module. If I have a cluster of more than 1,000 nodes, can I set ‘corPartitions’ value higher? (In my understanding, the larger the 'corPartitions' value, the more parallel works. Not sure if my understanding is correct)

And may I ask whether other parameter settings are the best experience values taken by your team under specific hardware configurations? (for example, the range of 'corMhapMemory', 'corPartitionMin', etc.)

Thank you very much in advance!

**Comment by skoren** [comment]
You're correct that setting corPartitions higher will create more jobs but there is also a minimum number of reads per partition. There's some non-zero startup cost and overhead so you don't want partitions to just run with a couple of reads and shut down. There's also the overhead of waiting to be scheduled on the cluster. 

Generally, we don't change the parameters from the auto-selected ones, those do a pretty good job of adjusting to your cluster nodes. You may be able to get some additional speed from tweaking them but I don't think it's worth the effort.

**Comment by wuyangChin** [comment]
Thank you very much for your prompt reply.

In our test example, it seems that the falconsense algorithm consumes most of the time in the first correction phase, so we are trying to find possible and simple acceleration methods. 

It seems that falconsense corrects the reads one by one in a chunk of data (a partition), rather than parallel processing. 
I wonder if it's worth trying to distribute more tasks to reduce the time consumption in this stage (or the data division strategy in this step is almost optimal. If we want to improve the speed, we need to consider the design of the algorithm itself).

Thanks!

**Comment by skoren** [comment]
falconsense is parallel, it aligns multiple reads to the template being corrected at the same time but this is relatively fasta and the final consensus is called on a single thread per read which can be slower, especially if you have very long reads. 

It won't hurt anything to specify more tasks for this step but you'd have to start this step from scratch since the partitioning of any jobs which already finished would be incorrect.

**Comment by wuyangChin** [comment]
Got it. Thanks again!
