### ISSUE TITLE
Settings for preserving haplotypes for ONT data?

### ISSUE THREAD

**Issue by marija-kra** [marbl/canu#2155]
A question, rather than issue.

We're hoping to use Nanopore to create two genome assemblies from the same dataset - one 'ordinary' and one attempting to preserve haplotypes. In the FAQ, I've found this:

> We’ve used the following parameters for polyploid populations (PacBio data):

> corOutCoverage=200 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50"

I'm wondering if you have any recommendations for the settings to use with Nanopore data for preserving haplotypes?

Nanopore data: MinION R9.4, basecalled using guppy 6.2.1 (Linux CPU)
Expected haploid genome size: 32 Mb
Approximate expected average coverage: 120x
Canu version: 2.2

Thanks!

**Comment by skoren** [comment]
If it's good enough quality ONT data, you could try uncorrected assembly (https://canu.readthedocs.io/en/latest/quick-start.html#assembling-with-multiple-technologies-and-multiple-files). The defaults there should do a reasonable job. If that doesn't work, the same parameters as PacBio above should work.
