### ISSUE TITLE
canu correction issue

### ISSUE THREAD

**Issue by nie31618** [marbl/canu#2158]
Hello,
When using the canu to correct the hifi reads, we meet a problem that our output reads seem to be compressed. The partial alignment of a raw read and its corrected output is demonstrated below:
![Screenshot from 2022-08-26 03-22-31](https://user-images.githubusercontent.com/30558179/186846689-665294e2-75ef-4cd6-af0b-cf527835deaf.png)

Could you provide some suggestion to resolve the problem?
Thank you

**Comment by skoren** [comment]
We don't recommend the consensus-based correction for HiFi data. Do you mean the overlap correction within the unitigging step for HiFi data? If so, yes those reads are only corrected in homopolymer-compressed space. Hicanu operates completely in homopolymer-compressed space until the final consensus step so there's no way to uncompress these reads.
