### ISSUE TITLE
Canu read correction failed due to the time

### ISSUE THREAD

**Issue by qinghong2019** [marbl/canu#2159]
Hi, I am new to Canu, and does not have very much experience in bioinformtics. I am running canu to assemble a genome (~6M, estimation), and it kept to failed due to the limited time. How to change the time for correction? Here are my scripts and files
my script: 
#!/bin/bash -l
#SBATCH --job-name=canu_YR343
#SBATCH --partition=batch.q,ksu-gen-highmem.q
#SBATCH --mem=30G             # Memory per core/cpu
#SBATCH --cpus-per-task=10
#SBATCH --time=04-23:00:00           # DD-HH:MM:SS
#SBATCH --mail-type=ALL
cd /bulk/xxxx/xxxxxxx/00_Nanopore/run_04052022YR343/03_Canu
/homes/xxxx/canu-2.2/bin/canu -p Y_YR343 -d ./YR343 genomeSize=6m -nanopore /bulk/xxxxx/Share_LeeLab/00_Nanopore/run_04052022YR343/02_QC/Y_YR343_filtered.fastq

Here is the correctReads.xxx.out

Found perl:
   /usr/bin/perl
   This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

Found java:
   /homes/qinghong/miniconda3/bin/java
   openjdk version "1.8.0_152-release"

Found canu:
   /homes/qinghong/canu-2.2/bin/canu
   canu 2.2

Running job 1 based on SLURM_ARRAY_TASK_ID=1 and offset=0.
slurmstepd: error: *** JOB 6747610 ON hero02 CANCELLED AT 2022-08-26T17:10:25 DUE TO TIME LIMIT ***

Here is the correctReads.jobSumnit--1.sh
#!/bin/sh

sbatch \
  --cpus-per-task=4 --mem-per-cpu=1920m -o correctReads.%A_%a.out \
  -D `pwd` -J "cor_Y_YR343" \
  -a 1-1 \
  `pwd`/correctReads.sh 0 \
> ./correctReads.jobSubmit-01.out 2>&1

Here is the correctdReadsPartition.batches
batch     bgnID     endID  nReads  memory (base memory 0.010 GB)
----- --------- --------- ------- -------
    1         1     61809    9228   0.188

here is the correctReadspartition.sh 
#!/bin/sh

#  Path to Canu.

bin="/homes/qinghong/canu-2.2/bin"

#  Report paths.

echo ""
echo "Found perl:"
echo "  " `which perl`
echo "  " `perl --version | grep version`
echo ""
echo "Found java:"
echo "  " `which /homes/qinghong/miniconda3/bin/java`
echo "  " `/homes/qinghong/miniconda3/bin/java -showversion 2>&1 | head -n 1`
echo ""
echo "Found canu:"
echo "  " $bin/canu
echo "  " `$bin/canu -version`
echo ""

#  Environment for any object storage.

export CANU_OBJECT_STORE_CLIENT=
export CANU_OBJECT_STORE_CLIENT_UA=
export CANU_OBJECT_STORE_CLIENT_DA=
export CANU_OBJECT_STORE_NAMESPACE=
export CANU_OBJECT_STORE_PROJECT=

$bin/falconsense \
  -partition 6 1.431 64 10000 \
  -S ../../Y_YR343.seqStore \
  -C ../Y_YR343.corStore \
  -R ./Y_YR343.readsToCorrect \
  -t  4 \
  -cc 4 \
  -cl 1000 \
  -oi 0.7 \
  -ol 500 \
  -p ./correctReadsPartition.WORKING \
&& \
mv ./correctReadsPartition.WORKING.batches ./correctReadsPartition.batches \
&& \
exit 0

exit 1

HELP****which parameter should I change? after I change, Could I just submit my sbatch script again to restart the job? Thank you so much!

**Comment by brianwalenz** [comment]
By default, Canu will do its own job scheduling to the grid, running each computational piece as a separate job.  This makes sense for large genomes, where it can have hundreds/thousands of jobs to run, but makes little sense for small genomes where there are only a few jobs and they're quick.  You can disable this behavior with `useGrid=false`; Canu will then run as one job, in your case, using one node with 10 CPUs and 30 GB max memory.

Here's some documentation: https://canu.readthedocs.io/en/latest/quick-start.html?highlight=usegrid#canu-quick-start

**Comment by skoren** [comment]
Idle
