### ISSUE TITLE
Estimating ovlStore size in correction phase

### ISSUE THREAD

**Issue by JohnUrban** [marbl/canu#216]
I have been trying to iterate over the correction phase as suggested in the FAQs on the read-the-docs.

I am on the second iteration -- i.e. the first time using the previous set of corrected reads.

The 1-overlapper directory holds 658GB of data. Building the ovlStore has failed several times. Some of those times it failed for exceeding allotted memory. I have had to set ```ovsMemory=64```, which still failed. I am now trying ```ovsMemory=100```. However, building the ovlStore also has failed a few times for exceeding my Disk Quota limits. I have ~1 TB of space, but am somewhat allowed to overflow at least a few more TB -- technically up to 12TB, but I often start having Disk Quota issues much sooner eveb though this excess disk space is usually given a grace period of 7 days before needing to be deleted. I should note that I have also seen the ovStoreBuild report to be finished, but for Canu to fail anyway saying building the ovlStore failed.

Anyway the ovlStore has got up to at least 1 TB in some of those attempts. I deleted everything and started over from the beginning. The 1-overlapper directory is the same size, and the ovlStore is up to ~820GB at the moment. There are 29 tmp.sort files already. I am curious if there is a way to predict how many of those files there might be and/or the size of the ovlStore when it is done.

Thanks for any thoughts.

**Comment by JohnUrban** [comment]
Update: the current ovlStore is ~1.5 TB at the moment... still building.

**Comment by JohnUrban** [comment]
```tail``` of ovlStore.err says it is on 
```bucketizing /path/to/correction/1-overlapper/results/000247.ovb.gz```

It looks like there are 436 .ovb.gz files in ```/path/to/correction/1-overlapper/results/```.

So I guess that implies it is ~56-57% done with bucketizing those files...
If the ovlStore is at 1.6 TB now, does that mean it will reach approximately 2.8-2.9 TB (i.e. 1.6/0.56 or so)?

**Comment by brianwalenz** [comment]
Assuming the reads are random - that you haven't biased the read order to put all the repeats at the end of the read list - then your 3tb estimate is decent.

This size is certainly computable before the store build process even starts.  In fact, it's essentially already computed, just not reported, when we figure out how big to make each job.  If the estimate is decent, canu can check for available disk space before even starting to construct the store.

**Comment by JohnUrban** [comment]
Yeah I guess this information in ovlStore.err might be useful enough for predicting how much space it will need:
```
Found 77198911902 (77198.91 million) overlaps.
Configuring for 100.00 GB to 100.00 GB memory and 512 open files.
At memory 100.000GB, 2677643673 olaps per bucket, 29 buckets (pass 1).
Will sort using 29 files; 2677643673 (2677.64 million) overlaps per bucket; 100.00 GB memory per bucket
```
If it is doing 29 buckets of ~100 GB, then it comes to ~2.9 TB.... or is that just coincidence?

The reads should be random with respect to size.

Regarding your comment on Canu checking for available disk space (e.g. in canu.out files), I've often wondered about this. When Canu reports available disk space, it is detecting all possible space rather than what my quota on the system is.... so I can imagine scenarios where that would interfere with Canu's expectations.
e.g. Canu detects ```56196.151 GB```, but really I have 1-2 TB that will not trigger a Disk Quota kill -- and a hard limit of up to 12 TB that may or may not trigger a kill at any given time.

**Comment by brianwalenz** [comment]
No coincidence.  The final size should be 7/8 that size (plus a little bit of overhead).

Aye, I'd forgotten about quotas.  I looked briefly into supporting them, but every system seems to have their own method.  A workable solution would be to let the user supply a command that returns the current free disk space in gigabytes.  Right now, the 'user supplied command' is just df.

**Comment by JohnUrban** [comment]
Alright so, in ovlStore.err, it got up to:
```
bucketizing DONE!
```

On the other hand, this is the stdout/stderr file (e.g. like canu.out, but not in canu-scripts since it is the output of the sbatch command that restarted canu):
```
    /gpfs_home/jurban/software/canu/canu/Linux-amd64/bin/ovStoreBuild \
     -O /jurban/scratch/canu/asm-i2/correction/asm-i2.ovlStore.BUILDING \
     -G /jurban/scratch/canu/asm-i2/correction/asm-i2.gkpStore \
     -M 100-100 \
     -L /jurban/scratch/canu/asm-i2/correction/1-overlapper/ovljob.files \
     > /jurban/scratch/canu/asm-i2/correction/asm-i2.ovlStore.err 2>&1
slurmstepd: Job 13054296 exceeded memory limit (104861996 > 104857600), being killed
slurmstepd: *** JOB 13054296 ON node950 CANCELLED AT 2016-08-04T19:22:45 ***
slurmstepd: Exceeded step memory limit at some point.
slurmstepd: Exceeded job memory limit
```

I had --mem=100g as well as ovsMemory=100....
...so I am trying --mem=110g with ovsMemory=100 to allow some extra memory...

**Comment by JohnUrban** [comment]
Perhaps a conclusion to this issue…. at least on my side.
I was able to get it to finish by setting ```ovsMemory=80``` and ```--mem=100g``` (for sbatch).
I am on the 3rd iteration of read correction and defaults for that step failed again. I am trying the solution above (that worked for iter 2) now.
