### ISSUE TITLE
EXCESSIVE COVERAGE DETECTED

### ISSUE THREAD

**Issue by Edomfra** [marbl/canu#2163]
**I have to reduce of number of reads for the coverage is in a range between 30-60X?**

command used:`canu -p SRR9090003 -d SRR9090003 -genomeSize=60m -pacbio-raw SRR9090003.fastq`

`canu -version canu snapshot v2.3-development +79 changes (r10350 48786ab3beecb04269a29934de96d06cd931a802)` 
 system: Linux, resources: 32gb, 16cores, Ubuntu

When execute `SRR9090003.seqStore.sh` returns.
```
Found perl:
   /opt/bin/anaconda3/bin/perl
   This is perl 5, version 22, subversion 0 (v5.22.0) built for x86_64-linux-thread-multi

Found java:
   /opt/bin/anaconda3/bin/java
   openjdk version "11.0.1" 2018-10-16 LTS

Found canu:
   /opt/bin/canu/build/bin/canu
   canu snapshot v2.3-development +79 changes (r10350 48786ab3beecb04269a29934de96d06cd931a802)


Creating library 'SRR9090003' for PacBio raw reads.

               reads               bases
---------- --------- ------ ------------ ------
Loaded        724978  92.3%  14320712838  99.8%  /media/FILES_FQ_INPUT_RAW/SRA/SRR9090003.fastq
Short          60404   7.7%     25647301   0.2%


All reads processed.

               reads               bases
---------- --------- ------ ------------ ------
Loaded        724978  92.3%  14320712838  99.8%
Short          60404   7.7%     25647301   0.2%


EXCESSIVE COVERAGE DETECTED.  Sampling reads.

For genome size of     60000000 bases,
            retain  12000000000 bases (200.00X coverage).

Found       724978 reads with  14320712838 bases (238.68X coverage).
Dropped     117480 reads with   2320712579 bases (38.68X coverage).
Retained    607498 reads with  12000000259 bases (200.00X coverage).

Bye.
```
I have to build small files *.fastq for process it with canu?

**Comment by brianwalenz** [comment]
Nope, Canu is autmagically reducing coverage for you, from input 238.68x to 200.00x.  Canu will then attempt to correct errors in this set of reads, then assemble the 'best' 40x of the corrected reads.

Since I don't know what you're after, I'll point to the parameter tweaking section in the FAQ: https://canu.readthedocs.io/en/latest/faq.html?what-parameters-can-i-tweak#what-parameters-can-i-tweak

**Comment by Edomfra** [comment]
great!!!

 I used 

`canu -p SRR9090003 -d SRR9090003 -genomeSize=59m correctedErrorRate=0.040  -pacbio SRR9090003.fastq`

finished correctly with Sequel reads.
thanks
