### ISSUE TITLE
Error in stoponLowCoverage/Read coverage lower than allowed.

### ISSUE THREAD

**Issue by yi-tingho** [marbl/canu#2164]
Hello.

I am running to an error with 'read coverage (0.05) lower than allowed.' 
[error_readcoverage.txt](https://github.com/marbl/canu/files/9632504/error_readcoverage.txt) I have changed my genomeSize and what has been suggested on these forums but it doesn't seem to work. 

I am using the culebrONT pipeline that incorporates Canu, here is my configuration file: [configuration_seac.txt](https://github.com/marbl/canu/files/9632511/configuration_seac.txt). I am trying to assemble an echinoderm genome using ONT data- there are a lot of tandem repeats. 

Please advise. Thanks in advance!

**Comment by brianwalenz** [comment]
Hi.

From the logging:
- you've set genomeSize=1g
- there are 54.8 million reads in the input
- Canu claims there are only 1g * 0.05 = 50m bases in the input

I'll guess there are a lot of short reads being rejected.  Look in `/scratch/hxxyit001/hins/Output/RB01HI009/ASSEMBLERS/CANU/ASSEMBLER` (or a subdir) for a file `out_canu.report` - this will have a histogram of the read lengths that canu found in the input.  Then look in `out_canu.seqStore` for `errorLog` - this will have a list of reads canu rejected.

You can decrease `minReadLength` but I doubt you'll get any kind of useful assembly ... especially given there are lots of repeats.

Side note 1: the input to canu is a single file, is this correct?
Side note2 : canu is seeing only the last of the OPTIONS lines in the config.txt.

**Comment by yi-tingho** [comment]
Thank you for the feedback. I corrected everything to be in the same OPTIONS line in my config.txt file, decreased minReadLength=300 but it still gives me an error.

For side note 1: yes, it was a single file.

**Comment by brianwalenz** [comment]
Nothing I can add without seeing a histogram of the read lengths and the error file, or the reads themselves.

**Comment by yi-tingho** [comment]
Apologies. Forgot to add those.
Here is the  `out_canu.seqStore` [out_canu report.txt](https://github.com/marbl/canu/files/9634049/out_canu.report.txt) and the `error Log` 
[errorLog.txt](https://github.com/marbl/canu/files/9634058/errorLog.txt)

**Comment by skoren** [comment]
How much coverage do you expect to have of your genome? The report shows only 50mb and all the short reads only add up to 16mb more. Is that accurate? If the genome size is 1gb, that's not even 1x of coverage so there's nothing to assemble.

**Comment by Nkosinathi15** [comment]
Hi skoren, 
I have kind of same issue.
I am assembling sheep genome with long nanopore reads.

Canu runs few minutes and stop.
below are the details.

![image](https://user-images.githubusercontent.com/108574026/195545178-c9ecb537-0947-444d-ad4e-455c104c1364.png)

![image](https://user-images.githubusercontent.com/108574026/195549383-9485afeb-f7a8-48a2-a8c6-b81862b46103.png)

![image](https://user-images.githubusercontent.com/108574026/195545902-0288427c-f239-4587-a8a1-36d1cb3c897c.png)

![image](https://user-images.githubusercontent.com/108574026/195549887-07c7e325-4282-424c-b1ee-eab663adf3f5.png)

[errorLog.txt](https://github.com/marbl/canu/files/9773563/errorLog.txt)

![image](https://user-images.githubusercontent.com/108574026/195548753-db93718f-4c83-41bf-9395-23d84a858f5d.png)


Thank you

**Comment by Nkosinathi15** [comment]
https://github.com/marbl/canu/files/9773563/errorLog.txt

errorLog here.

**Comment by brianwalenz** [comment]
There appears to be an error in the gzip file: pigz is complaining about 'trailing junk' in the third screen cap.

**Comment by Nkosinathi15** [comment]
Thank you for your response 

what could be the most possible way to correct this?

**Comment by skoren** [comment]
Your input file is corrupt, no way to fix that within Canu. If you downloaded it from somewhere, you can confirm the md5 and try downloading again. If it's a locally generated file, you may need to restore a backup. How much coverage did you expect to have of the 2.5g genome? Less than 20x is definitely not going to work and less than 50x will probably not get a very good assembly.

**Comment by skoren** [comment]
Idle
