### ISSUE TITLE
Canu restart failed ovlStore.BUILDING' is a valid ovStore; cannot create a new one.

### ISSUE THREAD

**Issue by broganmcgreal** [marbl/canu#2171]
Hi there, 

I'm trying to restart a canu job and I keep getting the error "ovlStore.BUILDING' is a valid ovStore; cannot create a new one."
I see this issue in a previous thread (https://github.com/marbl/canu/issues/896), however, I'm not sure how to resolve the issue and get the job working. 

**report from ovlStore.err**
```
  bucket  237 has 58575397 olaps.
  bucket  238 has 58597834 olaps.
  bucket  239 has 45937714 olaps.
Will sort 58.570 million overlaps per bucket, using 239 buckets 2.00 GB per bucket.

-- BUCKETIZING --

ERROR:  './RS324p_v1.ovlStore.BUILDING' is a valid ovStore; cannot create a new one.
```
**canu-log for ovStoreBuild**
```
Canu v1.7 (+0 commits) r0 .

Current Working Directory:
/powerplant/workspace/hrabxm/bioinf_Neonectria_Genome/ONT/02.canu_v2/correction

Command:
/software/bioinformatics/canu-1.7/bin/ovStoreBuild \
  -O ./RS324p_v1.ovlStore.BUILDING \
  -G ./RS324p_v1.gkpStore \
  -M 2-8 \
  -L ./1-overlapper/ovljob.files
```
**script to submit job**
```
canu -p RS324p_v1 -d $OUT genomeSize=45m \
-nanopore-raw $INPUT/*fastq \
useGrid=false
```

Thanks

**Comment by brianwalenz** [comment]
You are aware that v1.7 is 4.5 years old, right?

Assuming the store is valid (errors would be in earlier logs which are probably lost) you can simply rename it to RS324p_v1.ovlStore and restart.

I strongly suggest upgrading to v2.2 and starting again from scratch though.  https://github.com/marbl/canu/releases

**Comment by skoren** [comment]
Idle
