### ISSUE TITLE
md5sum

### ISSUE THREAD

**Issue by skr3178** [marbl/canu#2172]
![image](https://user-images.githubusercontent.com/79299617/196814322-c6bf6ed5-44c0-4b89-9181-4478368a0944.png)
![image](https://user-images.githubusercontent.com/79299617/196814384-c31b24b1-355f-4ff8-99cd-fcc49ec407c8.png)

**Comment by skoren** [comment]
The documentation lists the MD5 sum of the file decompressed rather than compressed, it should match if you extract first but since canu supports running without extraction I updated the docs to list the compressed MD5.
