### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by skr3178** [marbl/canu#2173]
![image](https://user-images.githubusercontent.com/79299617/196820473-395f5063-7d15-4e77-9dd6-fddf5082f342.png)

**Gives** 

![image](https://user-images.githubusercontent.com/79299617/196820500-27cc1972-3616-490f-af19-b8685542dc38.png)

**Pip list doesn't show canu installed** 
![image](https://user-images.githubusercontent.com/79299617/196820561-97198a53-9939-4ac9-ac2a-73fb728ed8da.png)

But canu version is 

![image](https://user-images.githubusercontent.com/79299617/196820623-389fb8b1-92f4-4401-ad56-f335418901c2.png)

**Comment by skoren** [comment]
Your gcc is quite old, have you tried downloading the pre-compiled binaries instead. Canu is also available through bioconda, pip isn't relevant as canu doesn't use any python code.

**Comment by skr3178** [comment]
Running this code gives error although  file is present in the directory and in the pwd
![image](https://user-images.githubusercontent.com/79299617/196820889-72dc6fd4-264d-4256-b491-330baf2bf882.png)


![image](https://user-images.githubusercontent.com/79299617/196820839-ffb84451-c643-4699-8e3d-b5a81b2d5150.png)

**Comment by skr3178** [comment]
I will use text from henceforth. 

Running this code
canu \
 -p ecoli -d ecoli-pacbio \
 genomeSize=4.8m \
 -pacbio pacbio.fastq

gives an error even though the file is present in the working directory

Invalid command line option '-pacbio'. Did you forget quotes around options with spaces?

**Comment by skoren** [comment]
Please don't mix topics, solve the compilation issue first.

I would guess whatever you're running when you specify canu is a super old globally installed version (check `canu --version`). You would instead need to specify `./canu-2.2/build/bin/canu` but I presume that doesn't exist because of the build error.

**Comment by skr3178** [comment]
It works now with the correct build. Closing now. Thanks!
