### ISSUE TITLE
Read coverage lower than allowed

### ISSUE THREAD

**Issue by tamsinlh** [marbl/canu#2174]
Hello.

I am trying to trim my PacBio CLR canu corrected reads. Prior to correction, it says I have ~33x coverage, but it will not trim as it is giving me a 5.48x coverage after correction. Reports after correction and prior to trimming attached. Please advise.

I am using canu 2.2 and submitting to a cluster.

```
canu -trim \
 -p Canu_trimmed -d canu-GSpacbiocorrection \
 genomeSize=1200000000 \
 -corrected - pacbio canu-GSpacbiocorrection/ GS_canu.correctedReads.fasta.gz
```

[Canu_trimmed.txt](https://github.com/marbl/canu/files/9855512/Canu_trimmed.txt)
[Canu_correction.txt](https://github.com/marbl/canu/files/9855513/Canu_correction.txt)

**Comment by skoren** [comment]
It's likely your data is lower quality and isn't getting corrected as well. You can try the FAQ suggestions of running multiple rounds of correction:
```
https://canu.readthedocs.io/en/latest/faq.html#what-parameters-should-i-use-for-my-reads
```

Namely, run with `corMinCoverage=0 corMhapSensitivity=high`. You can take these reads and proceed to trimming with an increased correctedErrorRate (probably 0.105 or 0.12) and see if you have enough data. You could also take the reads from the first correction and run them through correction again (as in the FAQ) for a couple of rounds and see if that helps.

**Comment by tamsinlh** [comment]
Thank you. I will give it a try.

**Comment by skoren** [comment]
Idle
