### ISSUE TITLE
Trimming and Unitigging skipped

### ISSUE THREAD

**Issue by usmart31** [marbl/canu#2176]
Hi, 

We have been trying to assemble a frog mitochondrial genome sequenced on nanopore using the latest version of canu but the software never completes the trimming and contiging (pls see attached output below). Thinking that this had something to do with our data, we decided to do test runs with the sample e.coli data as shown in the quick start tutorial (https://canu.readthedocs.io/en/latest/quick-start.html). However, that results in the same outcome and the software does not produce any results after the correction step. We have tried running it with both the nanopore and pacbio sample data but to no avail. Any help would be much appreciated! 

Thank you

![20221110_174538](https://user-images.githubusercontent.com/47125677/201230413-3250e446-b357-4b32-9352-e76650797b43.jpg)

**Comment by skoren** [comment]
How are you running canu, it looks from the log like you didn't request trimming or unitigging.

**Comment by usmart31** [comment]
We are running canu exactly as prescribed by the tutorial e.g.:
canu \
 -p ecoli -d ecoli-oxford \
 genomeSize=4.8m maxInputCoverage=100 \
 -nanopore ecolk12mg1655_R10_3_guppy_345_HAC.fastq

My understanding is that this will run all three steps (Correction, Trimming and Unitigging). Am I missing something?

**Comment by brianwalenz** [comment]
Look for options specified in ~/.canu or $bin/canu.defaults (where $bin is the location of the canu executable).

If that doesn't help, paste in the actual command and logging similar to this (it appears just before the first command is run by canu):
```
-- Found untrimmed raw PacBio CLR reads in the input files.
--
-- Generating assembly 'et' in '/devel/ecoli-trio/mix':
--   genomeSize:
--     4800000
--
--   Overlap Generation Limits:
--     corOvlErrorRate 0.2400 ( 24.00%)
--     obtOvlErrorRate 0.0450 (  4.50%)
--     utgOvlErrorRate 0.0450 (  4.50%)
--
--   Overlap Processing Limits:
--     corErrorRate    0.2500 ( 25.00%)
--     obtErrorRate    0.0450 (  4.50%)
--     utgErrorRate    0.0450 (  4.50%)
--     cnsErrorRate    0.0750 (  7.50%)
--
--   Stages to run:
--     correct raw reads.
--     trim corrected reads.
--     assemble corrected and trimmed reads.
```

**Comment by usmart31** [comment]
I apologize for the radio silence, I had to put this on the backburner for a bit. I looked at the $bin/canu.defaults file and it had no specifications listed on it. What command should I paste in it? The last three lines mentioned in the terminal in your last screenshot? The same question for pasting the actual and command and logging - what command needs to be pasted in while executing the three stages? 

Thanks.

**Comment by skoren** [comment]
The logging should be everything at the start of the canu run, so everything it outputs after you launch it through the "Stages to run:" part. Also post the exact canu command as entered, yours can't be identical to the quickstart, at least the -p is different.

**Comment by usmart31** [comment]
We were following the tutorial as closely as we could so we named the -p prefix the same as the tutorial too. However, it was the -d argument that was creating the issue since we just provided ". /" instead of a directory name, which was an avoidable oversight on our end. The analysis worked after we fixed this. Thank you for the help!
