### ISSUE TITLE
gnuplot failed

### ISSUE THREAD

**Issue by lamz138138** [marbl/canu#218]
Hi!

I have installed canu and test it with demo data. Although it's statue was "done",  I found some "gnuplot failed" output from stderr. From the information, I couldn't figure out why it failed, because canue failed to find gnuplot (I had added the path to PATH), or it failed in running command (and what command)?

I had tried to found the script taking charge of running gnuplot, and gave up for to many script, could you tell me which module should I reference to?

Any suggestion would be grateful!

Following is a part of information output from stderr:

```
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Fri Aug  5 17:40:42 2016 with 459.6 GB free disk space

    /tools/canu-1.3/Linux-amd64/bin/gatekeeperCreate \
      -minlength 1000 \
      -o /myPath/canu/demo/ecoli-auto/correction/ecoli.gkpStore.BUILDING \
      /myPath/canu/demo/ecoli-auto/correction/ecoli.gkpStore.gkp \
    > /myPath/canu/demo/ecoli-auto/correction/ecoli.gkpStore.BUILDING.err 2>&1

-- Finished on Fri Aug  5 17:40:44 2016 (2 seconds) with 459.6 GB free disk space
----------------------------------------
--
-- WARNING: gnuplot failed; no plots will appear in HTML output.
--
----------------------------------------
--
-- In gatekeeper store '/myPath/canu/demo/ecoli-auto/correction/ecoli.gkpStore':
--   Found 12528 reads.
--   Found 115899341 bases (24.14 times coverage).

```

**Comment by skoren** [comment]
Gnuplot is optional and you can run fine without it. The gnuplot is just run without parameters on the gp files canu creates. For example, the gkpStore folder (correction/ecoli.gkpStore/) has a file named readlengths.gp. The command would just be ```gnuplot correction/ecoli.gkpStore/readlengths.gp```

**Comment by lamz138138** [comment]
Hi,

Thank you for reply this issue too.

According to your suggestion, I know the gnuplot failed because my SGE doesn't support png, so I need to change "set terminal png" to "set teminal svg", but I can't find which module should I change, could you help me figure out?

Best wishes!

**Comment by brianwalenz** [comment]
It's called from three different files:

src/pipelines/canu/CorrectReads.pm
src/pipelines/canu/Gatekeeper.pm
src/pipelines/canu/Meryl.pm

**Comment by lamz138138** [comment]
Hi, brianwalenz! 

Thanks very much!

**Comment by lexnederbragt** [comment]
Sorry to reopen, but I really was happy to discover canu makes html reports, and was very sorry that it didn't work. From a (not too advanced) user's perspective, it is rather suboptimal the way the gnuplot problem is reported to the user, especially as users may think the program simply can't find gnuplot even though they tehmselves see it in the path. Had it not been for this issue, I would not have been able to troubleshoot it. And yes, the program finishes nicely without gnuplot, but I still would really like to use it *with* the html reports (not least for teaching).

So, can I put in the request that the checking of gnuplot is split into testing availability, and whether it runs but fails for other reasons, both with a potential solution suggested to the user?

**Comment by lamz138138** [comment]
Hi!

I also think test gnuplot would be grateful and the html report is useful! Hope they could add this in the new version. Otherwise, one could run with the command "gnuplot correction/ecoli.gkpStore/readlengths.gp" to find the reason by themselves.

**Comment by brianwalenz** [comment]
Hi, Lex-

Was your problem also png vs svg?  I should be able to support canu parameters 'gnuplot' (= path to gnuplot) and 'gnuplotFormat' (= 'png' or 'svg' or ...) without too much trouble.  For testing, I'll add (hidden) option 'gnuplotTested'.  If not set, canu will try to make a plot at about the same time it checks for java.  If the pot fails, canu will fail.  If set, the check will be skipped.

Also, I have a fix, not pushed out yet, for about half of the correction plots not showing up in the html reports.

Lastly, the reports are pretty basic, incomplete, include some esoteric numbers, and lack anything equivalent to CA's 'qc' report.  I heartily encourage improvements!  Or even just suggestions for improvements.

**Comment by brianwalenz** [comment]
Give the latest a try.  It should be reporting failure to run gnuplot, and auto-detecting which image format to use (as long as it is png, svg, or gif, in that order).  You can, of course, point to any gnuplot executable you want, and set the image type to whatever you want.

http://canu.readthedocs.io/en/latest/parameter-reference.html#general-options

**Comment by lexnederbragt** [comment]
Thanks. My IT has fixed our gnuplot, so I can't really test it :-(. Also, I lack time right now ... But maybe later. Keep up the good work with canu!
