### ISSUE TITLE
Overwrite existing output files from previews run

### ISSUE THREAD

**Issue by AlesBucek** [marbl/canu#2181]
Hi,
on canu 2.1.1 I would like to run multiple times canu in the same folder, each time ignoring the previous run results (and overwriting them if such files exist in the folder). Is there an argument to specify such behavior?
Thanks!

**Comment by brianwalenz** [comment]
No option for this.  It is counter to the pipeline methodology used and raises the (difficult) question of which pieces to rewrite and which to reuse.  If you're rewriting everything, it's simpler to just `rm -rf <directory>` before starting canu.

**Comment by AlesBucek** [comment]
@brianwalenz Thanks for the info and suggestions. Ales
