### ISSUE TITLE
Encountered deprecated error  (increase `-M`)

### ISSUE THREAD

**Issue by JulianneDavid** [marbl/canu#2185]
Hello! I encountered an error while running `canu` (v 1.8) with the following command:
```
canu -p <label> -d <output_directory> gridEngine=slurm batMemory=100 genomeSize=150000 correctedErrorRate=0.05 stopOnLowCoverage=2 -pacbio-corrected <input_reads.fasta>
```
The end of the `canu.out` file, written perhaps by [this script](https://github.com/marbl/canu/blob/b626dbed153439c76f291c747002121852474d2b/src/bogart/AS_BAT_OverlapCache.C), shows:
```
ABORT:   OverlapCache()-- limited to 102400MB memory (user supplied).
ABORT:   
ABORT:   OverlapCache()--       2MB for read data.
ABORT:   OverlapCache()--      11MB for best edges.
ABORT:   OverlapCache()--      29MB for tigs.
ABORT:   OverlapCache()--       8MB for tigs - read layouts.
ABORT:   OverlapCache()--      11MB for tigs - error profiles.
ABORT:   OverlapCache()--   25600MB for tigs - error profile overlaps.
ABORT:   OverlapCache()--       0MB for other processes.
ABORT:   OverlapCache()-- ---------
ABORT:   OverlapCache()--   25669MB for data structures (sum of above).
ABORT:   OverlapCache()-- ---------
ABORT:   OverlapCache()--       5MB for overlap store structure.
ABORT:   OverlapCache()--   76725MB for overlap data.
ABORT:   OverlapCache()-- ---------
ABORT:   OverlapCache()--  102400MB allowed.
ABORT:   OverlapCache()--
ABORT:   OverlapCache()-- Retain at least 66006 overlaps/read, based on 33003.03x coverage.
ABORT:   OverlapCache()-- Initial guess at 16662 overlaps/read.
ABORT:   OverlapCache()--
ABORT:   OverlapCache()-- Not enough memory to load the minimum number of overlaps; increase -M.
```
However, `-M` doesn't seem to be a valid input argument, either in canu 1.8 or 2.2:
```
ERROR:  Invalid command line option '-M'.  Did you forget quotes around options with spaces?
```

Should I increase the `batMemory` further? Or, could you advise me on what parameter should be bumped up for this run to succeed?
Thanks!
Julianne

**Comment by skoren** [comment]
The -M is an option to bogart directly, but batMemory sets it for you (see #1645 and others). The estimate for coverage is over 33,000x which means it will be load a lot of overlaps for every read. The better solution would be to update to a more recent release which will randomly downsample the 33,000x to a more reasonable 200x by default to avoid this.

**Comment by JulianneDavid** [comment]
Thank you! I really appreciate the quick response. Both options (`batMemory` + v2.2) did work here.
