### ISSUE TITLE
Issue opening input file in Canu

### ISSUE THREAD

**Issue by jakehhill** [marbl/canu#2186]
I'm running Canu on a Mac and I'm encountering the following error message when I try to run the programme:

'Starting file './RC128.gkpStore.gkp'.

Loading reads from '/Users/j.hill/Desktop/Nanopore/barcode_01/barcode01/RC128.fasta'
ERROR:  Failed to open input file '/Users/j.hill/Desktop/Nanopore/barcode_01/barcode01/RC128.fasta': Operation not permitted'

Looks like the .fasta can't be opened but I can open it in my text editor with no issues. I'm also not sure what's meant by 'Operation not permitted'. Any idea how to fix this?

**Comment by skoren** [comment]
Can you open the file within terminal (say with vi) or does it also have permission issues. It seems on recent OSX versions you may need to grant terminal permissions to the file system: https://osxdaily.com/2018/10/09/fix-operation-not-permitted-terminal-error-macos/

**Comment by skoren** [comment]
Idle, likely a OSX permissions issue.
