### ISSUE TITLE
How to check and update version of canu?

### ISSUE THREAD

**Issue by self-Shubham** [marbl/canu#2187]
When using command "canu -version", I am getting output as  
"canu branch HEAD +0 changes (r10117 5638f7d9a5379373310ab62c28aa0cdbd864722d)".
How to update to latest version of canu?

**Comment by skoren** [comment]
That looks like the 2.1.1 release if you click on the tag link. Not sure how you installed canu which would dictate how you can update. If you're using a package manager like conda, it should have v2.2 available. If you downloaded it yourself, the latest is available on the releases page and you can download and replace your version (or keep both, just make sure to point your path to the most recent one).

**Comment by self-Shubham** [comment]
When using command "canu -version", I am getting output as
canu branch HEAD +0 changes (r10117 5638f7d9a5379373310ab62c28aa0cdbd864722d) 
This seems lika an error. How to update to latest version of canu?
