### ISSUE TITLE
Read coverage (9.32) lower than allowed.

### ISSUE THREAD

**Issue by self-Shubham** [marbl/canu#2190]
Using canu version 2.1.1
Command-
```canu -p BG -d BG_b1_gsize100 genomeSize=100m -nanopore-raw ./NanoFilt_b1_hc75_l200_q8.fastq.gz corMhapSensitivity=high corMinCoverage=0```

Error- 
```
ERROR:  Read coverage (9.32) lower than allowed.
-- ERROR:    minInputCoverage  = 10
-- ERROR:    stopOnLowCoverage = 10
-- ERROR:
-- ERROR:  This could be caused by an incorrect genomeSize or poor quality
-- ERROR:  reads that cound not be sufficiently corrected.
```
As mentioned in the code "corMhapSensitivity=high" "corMinCoverage=0", facing this issue.
I have a shotgun meta genome data of multiple soil samples. Data is generated using ONT sequencing platform.

**Comment by skoren** [comment]
You are likely setting the genome size too large. Keep the genome at a normal bacterial genome (5m) but then also use the metagenomic parameters from the FAQ: `maxInputCoverage=10000 corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0 redMemory=32 oeaMemory=32 batMemory=200`.

**Comment by self-Shubham** [comment]
Thanks for the reply Sergey
This is a soil sample data and it contains bacteria as well as fungi also. I want to target both of them so keeping genome size =100m. Should I change genome size?

**Comment by skoren** [comment]
The coverage only matters for setting some default thread/memory limits and subsetting sequences (if you have very deep coverage) so it doesn't matter if you set it to 5m. If you do keep it at 100m then you need to set the minInputCoverage to lower than the default of 10, probably 0 to just ignore coverage and run anyway.
