### ISSUE TITLE
CANU stops at Consensus step without giving any error message or finishing the job

### ISSUE THREAD

**Issue by alitahir0** [marbl/canu#2191]
I am trying to assemble Brassicaceae plant species genome (estimated genome size 254 Mb) using PacBio HiFi reads. Canu runs fine through all the steps until it reaches consensus step. There it just stops without producing any error message or a contig.fasta file

**Canu command **
nohup canu -p asref69 -d /canu2 genomeSize=254m -pacbio-hifi /hifi_raw/asref69.hifireads.fastq.gz &
 
**canu version**
canu 2.2

I have attached the "nohup.out" file, could you please have a look into this. I would really appreciate you for your support. Thank you!
[nohup.txt](https://github.com/marbl/canu/files/10331812/nohup.txt)

**Comment by skoren** [comment]
Nothing in the log indicates the run stopped, it's computing consensus. Looks like it started 1 job and is running it 1 at a time.

**Comment by alitahir0** [comment]
Thank you for replying to my query. Do you think it can run for a long time before it produces an output file, in this case, it is now more than two weeks that it is still on 1 job of the consensus step.

**Comment by skoren** [comment]
The runtime will depend on the coverage of the contig and the contig length. Typically they take no more than a few hours, weeks definitely seems suspicious.

**Comment by alitahir0** [comment]
Yes, it did not finish in two weeks. Then, I edited "consensus.sh" file and replaced the current error rate (the -e flag) with 0.25 and then run "consensus.sh 1" from the 5-consensus folder as mentioned here https://github.com/marbl/canu/issues/932. Then it completed the process in about 30 min, and run all the individual consensus processes from 1-11 like this and then run the original canu command, which produced the assembly successfully. I am not sure if this is the correct way to do this. I would highly appreciate your input on this. 
[nohup.out.txt](https://github.com/marbl/canu/files/10399825/nohup.out.txt)

**Comment by alitahir0** [comment]
Thank you for guiding me in setting the error rate for the consensus step. Do I have to run the analysis from scratch or I can just repeat consensus step with an error rate of 0.10/0.15?

**Comment by skoren** [comment]
You can repeat just the consensus step, make a copy of the assembly folder and remove the 4-unitigger, 5-consensus, and ctgStore folders along with the final assembly outputs and run canu again with the `cnsErrorRate` set to what you want (0.10 or 0.15).

**Comment by alitahir0** [comment]
thank you. I will follow your suggestions and let you know if I have any further questions. Thank you again.
