### ISSUE TITLE
Optimising assembly of segmental duplication 

### ISSUE THREAD

**Issue by smf96** [marbl/canu#2195]
Hello,

I am trying to assemble a human 200kb region that contains a large segmental duplication with two ~85kb repeats. I have generated nanopore data from the region with a mixture of WGS and cas9 targeting. I have aligned to hg38, called SNVs with nanopolish and then phased with whatshap to obtain reads from each haplotype. When I run the assembly with canu v2.2 on each set of reads, it successfully generates a single contig across the region for haplotype 1 but not for haplotype 2. 

I'm just using the very basic command at the moment. Are you able to suggest which parameters I could adjust to make the assembly for haplotype 2 more contiguous? I'd like to relax some of the thresholds but am wary it will result in the collapse of the two paralogous repeats from the segmental duplication. 

I'm using the simple command of:
```
${canu_tool}/bin/canu \
 -p ${sampleID}_hap1 -d ${sampleID}/Canu_assembly_${sampleID}_hap1 \
 genomeSize=200k \
 gridOptions="--nodes=1 --time 8:00:00" \
 gnuplot=/local/software/biobuilds/2017.05/bin/gnuplot\
 java=/local/software/jdk/jdk-13.0.1/bin/java\
 -nanopore ${hap1FQ}

${canu_tool}/bin/canu \
 -p ${sampleID}_hap2 -d ${sampleID}/Canu_assembly_${sampleID}_hap2 \
 genomeSize=200k \
 gridOptions="--nodes=1 --time 8:00:00"\
 gnuplot=/local/software/biobuilds/2017.05/bin/gnuplot\
 java=/local/software/jdk/jdk-13.0.1/bin/java\
 -nanopore ${hap2FQ}
```

I have attached the reports for each assembly.

[CRA125_8rap3lig3cas9_hap1.report.txt](https://github.com/marbl/canu/files/10405878/CRA125_8rap3lig3cas9_hap1.report.txt)

[CRA125_8rap3lig3cas9_hap2.report.txt](https://github.com/marbl/canu/files/10405879/CRA125_8rap3lig3cas9_hap2.report.txt)

Other than the hap2 reads having a slightly shorter N50 of 30kb rather than hap 1s 34kb, I don't really understand the difference in ability to assembly a single continuous contig across the region? 

Any advice or guidance you're able to give would be much appreciated! Thank you

**Comment by skoren** [comment]
The surprising thing is these two datasets are selecting very different unitigging thresholds. The number of reads is pretty low so this could be making the setting more random than on a full dataset with thousands of reads.
```
--  ERROR RATES
--  -----------
--                                                   --------threshold------
--  304                          fraction error      fraction        percent
--  samples                              (1e-5)         error          error
--                   --------------------------      --------       --------
--  command line (-eg)                           ->  12000.00       12.0000%
--  command line (-ef)                           ->  -----.--      ---.----%
--  command line (-eM)                           ->  12000.00       12.0000%
--  mean + std.dev     139.76 +-  12 *   817.78  ->   9953.18        9.9532%
--  median + mad        40.00 +-  12 *    40.00  ->    751.65        0.7516%  (enabled)
--  90th percentile                              ->    171.00        0.1710%
```
vs
```
--  ERROR RATES
--  -----------
--                                                   --------threshold------
--  395                          fraction error      fraction        percent
--  samples                              (1e-5)         error          error
--                   --------------------------      --------       --------
--  command line (-eg)                           ->  12000.00       12.0000%
--  command line (-ef)                           ->  -----.--      ---.----%
--  command line (-eM)                           ->  12000.00       12.0000%
--  mean + std.dev     165.98 +-  12 *   743.97  ->   9093.66        9.0937%  (enabled)
--  median + mad        48.00 +-  12 *    48.00  ->    901.98        0.9020%
--  90th percentile                              ->    253.00        0.2530%
```

I'd suggest dropping the max rate used for unitigging in the second run and see what it does. You can edit the unitigger.sh script to change it to `-eg 0.01`, remove the `*ctgStore` and `5-consensus` folders and run the script manually (inside the `4-unitigger` folder run `sh unitigger.sh`. See if that makes a difference in the assembly of the second haplotype. If it does you could try re-running with a lower correctedErrorRate (maybe 0.045 or even 0.025).

**Comment by smf96** [comment]
Thank you for such a rapid response,

What exactly am I editing in the 'unitigger.sh' file? Is it the -eg and -eM from 0.12? Also when I run the script in the folder I get this error:
![image](https://user-images.githubusercontent.com/52749489/212349746-9e267e87-1dbb-43dd-b59e-a5796765e652.png)

From my initial assembly, canu produced:
```
contigs:      3 sequences, total length 305478 bp (including 0 repeats of total length 0 bp).
bubbles:      1 sequences, total length 90999 bp.
unassembled:  3 sequences, total length 175490 bp.
```
With these fasta headers:
![image](https://user-images.githubusercontent.com/52749489/212350330-daa9aed9-5e3b-4026-9ef2-91d2e2e70a3c.png)

Sorry I've skipped ahead a bit as I couldn't quite work out the first bit you had said. When I run with `correctedErrorRate` = 0.045 I get: 
```
contigs:      4 sequences, total length 377864 bp (including 0 repeats of total length 0 bp).
bubbles:      0 sequences, total length 0 bp.
unassembled:  132 sequences, total length 2859533 bp.
```
With:
![image](https://user-images.githubusercontent.com/52749489/212351315-d8793e1b-8533-4314-a57e-cf6423906dae.png)

Then when I run with `correctedErrorRate` = 0.025 I get:
```
contigs:      3 sequences, total length 302392 bp (including 0 repeats of total length 0 bp).
bubbles:      2 sequences, total length 94869 bp.
unassembled:  131 sequences, total length 3693867 bp.
```
With
![image](https://user-images.githubusercontent.com/52749489/212352176-bad9f0f9-a7d7-4020-b02d-0295d842b211.png)

I'm not sure if any of that helps? It just seems quite strange to me as this is the coverage over the locus split into haplotype and there doesn't seem to be any obvious reason (in terms of coverage/read lengths) why haplotype 1 would work but haplotype 2 wouldn't.
![image](https://user-images.githubusercontent.com/52749489/212352874-77811212-c7c5-46f6-93e8-2b3a75a1a2b2.png)

The funny distribution is because both WGS and cas9-targeting was performed. 

What I'm also confused about is why I end up with the pretty low number of reads. Start with >1.4k
 reads with overlap but significantly reduces to ~300 at the trimming stage. Is that normal?

**Comment by skoren** [comment]
I wonder if there is more noise (or mis-binned reads) in haplotype 2 vs haplotype 1, leading to the higher error rate being selected and potentially splitting the contigs. Still try the unitigger.sh experiment, you have to run `sh unitigger.sh 1` which should fix the error. You only need to change eg, but it doesn't hurt to change eM too.

The default settings drop the overall input coverage to 100x and the corrected coverage to 40x. It looks like you have about 100x data input anyway so the first part shouldn't make a difference. You could increase this (corOutCoverage=100) and keep a lower correctedErrorRate (0.025) and see if that makes a difference. Other than that, not sure I have other suggestions.

**Comment by smf96** [comment]
I ran `sh unitigger.sh 1` and this was printed:
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/52749489/212531125-8ed9d62c-cd34-4b0e-a2bd-030d814f8bcf.png">

And these were generated in `4-unitigger`
<img width="520" alt="image" src="https://user-images.githubusercontent.com/52749489/212531237-6e23c0d6-659c-4a0f-ab30-efa1e091cbd2.png">

And this is what's in `unitigging`:
<img width="460" alt="image" src="https://user-images.githubusercontent.com/52749489/212531260-403d5575-4410-4671-a1cc-77610df01047.png">

So the `.ctgStore` was remade but not `5-consensus`, was that what was supposed to happen?

**Comment by skoren** [comment]
Yes that step only re-runs the 4-unitigger step, it should give a report in the sizes files of what contigs were generated so you can check if the assembly improved.

**Comment by skoren** [comment]
Idle

**Comment by smf96** [comment]
Thank you for your help!

Just for completion of this thread, rerunning the 4-unitigger step reduced the number of contigs in the sizes file to 2.

I also went back and applied a more stringent filter on the SNVs used to phase before running canu again. 

Decreasing correctedErrorRate = 0.025 produced 2 contigs and 1 bubble

Increasing corOutCoverage=100 produced 1 contig of 195kb (yay)

Changing both produced 3 contigs and 2 bubbles

Out of interest, are there any more reasons other than keeping runtime low to why the default is 40x?

**Comment by skoren** [comment]
Overlap-based assemblers, like canu, can suffer from too much coverage which is part of why we subset to 40x by default. It is also a speed optimization. 100x is not so outrageously high so I think you're fine using that coverage.
