### ISSUE TITLE
Read only file system error during CANU Pacbio assembly run

### ISSUE THREAD

**Issue by sangeet2019** [marbl/canu#2196]
Hello,

I am trying to run CANU on my Pacbio CLR data. using the code below,

/Tools/canu-2.2/bin/canu useGrid=False -p Test -d Test_assembly genomeSize=1000m -pacbio /clr_data/m64168e_201230_174743.subreads.fq,

It's running on Linux in a virtual machine.

It gets killed in the first correction step during 

/mhap.sh 1 > ./mhap.000001.out 2>&1

Once it is killed, it also makes the entire file system read only. 

I am not sure what is going wrong here. Any suggestion would be great.

**Comment by skoren** [comment]
Canu can't make the filesystem read only so this is likely some issue w/in the virtual machine itself. We've seen issues with VM filesystems which have incomplete implementations before (missing symlinking for example). The out file should have more information on what error, if any, canu reported.

**Comment by skoren** [comment]
Idle
