### ISSUE TITLE
canu failed with 'failed to compute mhap overlaps" issue

### ISSUE THREAD

**Issue by LennWhy** [marbl/canu#2198]
Hi -

I am attempting to run canu on Pacbio raw reads. I am using the version that is available on conda and is now installed a Linux HPC. Below is the basic command that I attempted to run.

canu -correct -p canu_RcaF -d canu_RcaF genomeSize=500m -pacbio-raw female.subreads.fastq.gz

The HPC has up to 1TB (more or less) and up to 56 threads.

Can you please advise as to why it might fail? I've tried to do a couple of times now.

Thanks

**Comment by skoren** [comment]
Most likely an issue with your JVM configuration, see similar issues (e.g. #2167). Check the output logs in the `correction/1-overlapper/*.out` files for error messages.

**Comment by skoren** [comment]
Idle
