### ISSUE TITLE
Mhap overlap jobs failed, tried 2 times, giving up

### ISSUE THREAD

**Issue by JWDebler** [marbl/canu#2200]
`canu genomeSize=42m -trimmed -corrected -nanopore Af24715.trimmedReads.fasta.gz -fast`

I performed trimming and correction earlier, the full command then was:

`canu genomeSize=42m -nanopore Af24715.guppy627_sup.fastq.gz -fast`

Canu 2.2 on Ubuntu 18.04

I am trying to assemble nanopore data, it usually works, but this time it just keeps failing. 
I suspect is has something to do with the read lenght of this particular sample as the distribution in the uncorrected reads is 1,686 bp (average) and 3,819 bp (N50). The respective values for the corrected and trimmed reads are 2,822 bp (avg) and 4,926 bp (N50).

The log file under `unitigging/1-overlapper/mhap.000025.out` finishes with this:

```
Tested  19740032 olaps -- Skipped   0.0051% -- Passed  92.2303% -- 16455.97 olaps/sec
Tested  19750016 olaps -- Skipped   0.0050% -- Passed  92.2286% -- 16453.68 olaps/sec
Tested  19760000 olaps -- Skipped   0.0050% -- Passed  92.2293% -- 16452.98 olaps/sec
ERROR:  edlibAlign()  queryLength  = -5
ERROR:                targetLength = 102
overlapPair: utility/src/utility/edlib.C:191: EdlibAlignResult edlibAlign(const char*, int, const char*, int, EdlibAlignConfig): Assertion `queryLength > 0' failed.

Failed with 'Aborted'; backtrace (libbacktrace):
utility/src/utility/system-stackTrace.C::82 in _Z17AS_UTL_catchCrashiP7siginfoPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
utility/src/utility/edlib.C::191 in _Z10edlibAlignPKciS0_i16EdlibAlignConfig()
overlapInCore/overlapPair.C::310 in _Z14finalAlignmentPciS_iP9ovOverlapdRiS2_()
overlapInCore/overlapPair.C::605 in _Z17recomputeOverlapsPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
Aborted (core dumped)
```

Not sure if the negative `queryLength` has anything to do with it.

Any help will be appreciated.

Cheers

**Comment by skoren** [comment]
This seems like a bad overlap generated by mhap is causing the crash. Try removing all the `*WORKING*` files and re-running just this step `sh mhap.sh 25` in 1-overlapper folder to see if it is due to file corruption/truncated output. Other than that, you could try increasing the minimum overlap length to see if it will get around the issue.

**Comment by JWDebler** [comment]
Yep, that fixed it, thanks :-)
