### ISSUE TITLE
Mategenome assembly of assemblies

### ISSUE THREAD

**Issue by fergsc** [marbl/canu#2201]
Hi,

I have a short read set of many samples that I am trying to do a global metagenome assembly. The usual assemblers (megahit, spades) I can get to complete an assembly, to much data. My next idea is try do invididual metagenome assemblies for all samples, pool the resulting contigs and assemble. Would Canu be suitable for an assembly of meta genome assemblies, if so are there any recomemded parameters that I should use? The coverage for each contig will be very low, but the confidence will be high.

Thanks.

**Comment by skoren** [comment]
It's been asked before, see #1848 but is not really something canu is designed for or tested with. It *should* mostly work, the maximum read limit is 2mb so as long as your contigs are shorter than this it would be OK. I'd recommend using only the --assemble option (no trimming/correction) and a lower than default correctedErrorRate, maybe 0.01 or 0.02. However, te generally don't recommend merging assemblies.

**Comment by fergsc** [comment]
Thought that may be the case, all the assumptions for assembling reads are different.

Thanks for the help.
