### ISSUE TITLE
Question about minOverlapLength

### ISSUE THREAD

**Issue by yzhang-github-pub** [marbl/canu#2202]
I used canu 2.2 to assembly amplicon nanopore reads. Parameters specified include 
genomeSize=15k, 
minOverlapLength=(300, 400, and 500), and 
minReadLength=minOverlapLength + 100, i.e., (400, 500, 600) respectively. 

I got expected, similar contigs for minOverlapLength=(300, 500), but no result for minOverlapLength=400.

**Comment by gringer** [comment]
What is the amplicon length, i.e. what length sequence are you trying to assemble?

**Comment by yzhang-github-pub** [comment]
5.5kb

**Comment by skoren** [comment]
There is random downsampling that I expect is happening here which may affect your results. I would suggest downsampling the dataset deterministically before passing the reads to canu which would ensure the same reads are being compared across the different overlap lengths.
