### ISSUE TITLE
Undefined subroutine &canu::Report::caExit called at  canu-2.2/build/bin/../lib/site_perl/canu/Report.pm line 116.

### ISSUE THREAD

**Issue by chenzhaozhu** [marbl/canu#2207]
I run under the LIUNX system and appear when the error correction
 canu -p dyy.fq -d ~/dyy/hifi/D01/clean.canu.fq/ genomeSize=0.6g useGrid=false -pacbio ~/dyy/hifi/D01/DYY.ccs.fq.fastq

Print () on Closed Filehandle F AT /HOME/Zhuchenzhao/software/canu-2.2/build/bin/../lib/site_perl/canu/defaults.pm Line 321.
-
-Begin Correcation
-
- Creating Overlap Store Correction/DYY.FQ.ovlstore USING:
- 46 Buckets
- 85 slices
- Use most 15 GB Memory Each
Undefined Subroutine & Canu :: Report :: CAEXIT CALLED at/Home/zhuchenzhao/software/canu-2.2/build/bin/site_perl/canu/report.pm line 116.

sub saveReport ($) {
    my $asm = shift @_;
    my $tag;

    open(F, "> $asm.report.new") or caExit("can't open '$asm.report.new' for writing: $!", undef);

    saveReportItem("CORRECTION/READS",       $report{"corSeqStore"});
    saveReportItem("CORRECTION/MERS",        $report{"corMeryl"});
    saveReportItem("CORRECTION/FILTERING",   $report{"corFilter"});
    saveReportItem("CORRECTION/LAYOUT",      $report{"corLayout"});
    saveReportItem("CORRECTION/CORRECTIONS", $report{"corrections"});

    saveReportItem("TRIMMING/READS",         $report{"obtSeqStore"});
    saveReportItem("TRIMMING/MERS",          $report{"obtMeryl"});
    saveReportItem("TRIMMING/TRIMMING",      $report{"trimming"});
    saveReportItem("TRIMMING/SPLITTING",     $report{"splitting"});

    saveReportItem("UNITIGGING/READS",       $report{"utgSeqStore"});
    saveReportItem("UNITIGGING/MERS",        $report{"utgMeryl"});
    saveReportItem("UNITIGGING/OVERLAPS",    $report{"overlaps"});
    saveReportItem("UNITIGGING/ADJUSTMENT",  $report{"adjustments"});
    saveReportItem("UNITIGGING/ERROR RATES", $report{"error rates"});
    saveReportItem("UNITIGGING/UNITIGS",     $report{"unitigs"});
    saveReportItem("UNITIGGING/CONTIGS",     $report{"contigs"});
    saveReportItem("UNITIGGING/CONSENSUS",   $report{"consensus"});

    close(F);

    my $diff = -1;
  if (-e "$asm.report") {
        open(OLD, "< $asm.report");
        open(NEW, "< $asm.report.new");

        $diff = 0;

        while (!eof(OLD) || !eof(NEW)) {
            my $old = <OLD>;
            my $new = <NEW>;

            if ($old ne $new) {
                $diff++;
            }
        }

        close(OLD);
        close(NEW);
    }

    if ($diff < 0) {
        #print STDERR "-- New report created.\n";

        rename "$asm.report.new", "$asm.report";
        stashFile("$asm.report");
    }

    elsif ($diff == 0) {
        #print STDERR "-- No change in report.\n";

        unlink "$asm.report.new";
    }

**Comment by chenzhaozhu** [comment]
thank you , my Disk quota exceeded

**Comment by skoren** [comment]
See the faq for potential parameters to reduce space usage: https://canu.readthedocs.io/en/latest/faq.html#my-assembly-is-running-out-of-space-is-too-slow or you can get a larger quota and re-try.
