### ISSUE TITLE
canu failed with 'failed to create the overlap store' during Bucketizing

### ISSUE THREAD

**Issue by avvypaks** [marbl/canu#2208]
-- Canu v0.0 (+0 commits) r0 unknown-hash-tag-no-repository-available.
-- Detected Java(TM) Runtime Environment '1.8.0_92' (from 'java').
-- Detected 8 CPUs and 8 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
-- Allowed to run   2 jobs concurrently, and use up to   4 compute threads and    4 GB memory for stage 'bogart (unitigger)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   2 jobs concurrently, and use up to   4 compute threads and    2 GB memory for stage 'read error detection (overlap error adjustment)'.
-- Allowed to run   8 jobs concurrently, and use up to   1 compute thread  and    1 GB memory for stage 'overlap error adjustment'.
-- Allowed to run   2 jobs concurrently, and use up to   4 compute threads and    8 GB memory for stage 'utgcns (consensus)'.
-- Allowed to run   8 jobs concurrently, and use up to   1 compute thread  and    2 GB memory for stage 'overlap store parallel bucketizer'.
-- Allowed to run   8 jobs concurrently, and use up to   1 compute thread  and    8 GB memory for stage 'overlap store parallel sorting'.
-- Allowed to run   8 jobs concurrently, and use up to   1 compute thread  and    2 GB memory for stage 'overlapper'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run   2 jobs concurrently, and use up to   4 compute threads and    4 GB memory for stage 'meryl (k-mer counting)'.
-- Allowed to run   4 jobs concurrently, and use up to   2 compute threads and    8 GB memory for stage 'falcon_sense (read correction)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
--
-- This is canu parallel iteration #1, out of a maximum of 2 attempts.
--
-- Final error rates before starting pipeline:
--   
--   genomeSize          -- 4800000
--   errorRate           -- 0.015
--   
--   corOvlErrorRate     -- 0.045
--   obtOvlErrorRate     -- 0.045
--   utgOvlErrorRate     -- 0.045
--   
--   obtErrorRate        -- 0.045
--   
--   cnsErrorRate        -- 0.045
--
--
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Sat Mar 11 20:43:46 2023 with 140.991 GB free disk space

    /Users/paulhebert/opt/anaconda3/libexec/gatekeeperCreate \
      -minlength 1000 \
      -o /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/ecoli.gkpStore.BUILDING \
      /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/ecoli.gkpStore.gkp \
    > /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/ecoli.gkpStore.BUILDING.err 2>&1

-- Finished on Sat Mar 11 20:43:47 2023 (1 second) with 140.96 GB free disk space
----------------------------------------
sh: line 1: 25402 Abort trap: 6           gnuplot /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/ecoli.gkpStore/readlengths.gp > /dev/null 2>&1
--
-- WARNING: gnuplot failed; no plots will appear in HTML output.
--
----------------------------------------
--
-- In gatekeeper store '/Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/ecoli.gkpStore':
--   Found 12528 reads.
--   Found 115899341 bases (24.14 times coverage).
--
--   Read length histogram (one '*' equals 20.62 reads):
--        0    999      0 
--     1000   1999   1444 **********************************************************************
--     2000   2999   1328 ****************************************************************
--     3000   3999   1065 ***************************************************
--     4000   4999    774 *************************************
--     5000   5999    668 ********************************
--     6000   6999    619 ******************************
--     7000   7999    618 *****************************
--     8000   8999    607 *****************************
--     9000   9999    560 ***************************
--    10000  10999    523 *************************
--    11000  11999    478 ***********************
--    12000  12999    429 ********************
--    13000  13999    379 ******************
--    14000  14999    366 *****************
--    15000  15999    353 *****************
--    16000  16999    329 ***************
--    17000  17999    297 **************
--    18000  18999    294 **************
--    19000  19999    283 *************
--    20000  20999    251 ************
--    21000  21999    195 *********
--    22000  22999    152 *******
--    23000  23999    132 ******
--    24000  24999     75 ***
--    25000  25999     66 ***
--    26000  26999     56 **
--    27000  27999     44 **
--    28000  28999     35 *
--    29000  29999     16 
--    30000  30999     21 *
--    31000  31999     18 
--    32000  32999     11 
--    33000  33999      8 
--    34000  34999      6 
--    35000  35999      6 
--    36000  36999     10 
--    37000  37999      2 
--    38000  38999      3 
--    39000  39999      2 
--    40000  40999      2 
--    41000  41999      2 
--    42000  42999      1 
-- Meryl attempt 1 begins.
----------------------------------------
-- Starting concurrent execution on Sat Mar 11 20:43:47 2023 with 140.959 GB free disk space (1 processes; 2 concurrently)

    /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/0-mercounts/meryl.sh 1 > /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/0-mercounts/meryl.000001.out 2>&1

-- Finished on Sat Mar 11 20:44:10 2023 (23 seconds) with 140.594 GB free disk space
----------------------------------------
-- Meryl finished successfully.
----------------------------------------
-- Starting command on Sat Mar 11 20:44:10 2023 with 140.594 GB free disk space

    /Users/paulhebert/opt/anaconda3/libexec/meryl \
      -Dh \
      -s /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/0-mercounts/ecoli.ms16 \
    > /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/0-mercounts/ecoli.ms16.histogram \
    2> /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/0-mercounts/ecoli.ms16.histogram.info

-- Finished on Sat Mar 11 20:44:10 2023 (lickety-split) with 140.594 GB free disk space
----------------------------------------
sh: line 1: 25454 Abort trap: 6           gnuplot /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/0-mercounts/ecoli.ms16.histogram.lg.gp > /dev/null 2>&1
--
-- WARNING: gnuplot failed; no plots will appear in HTML output.
--
----------------------------------------
sh: line 1: 25456 Abort trap: 6           gnuplot /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/0-mercounts/ecoli.ms16.histogram.sm.gp > /dev/null 2>&1
--
-- WARNING: gnuplot failed; no plots will appear in HTML output.
--
----------------------------------------
-- For mhap overlapping, set repeat k-mer threshold to 1157.
--
-- Found 115711421 16-mers; 89186744 distinct and 77230204 unique.  Largest count 37954.
--
-- OVERLAPPER (mhap) (correction)
--
-- Set corMhapSensitivity=high based on read coverage of 24.
--
-- PARAMETERS: hashes=768, minMatches=2, threshold=0.73
--
-- Given 6 GB, can fit 9000 reads per block.
-- For 3 blocks, set stride to 2 blocks.
-- Logging partitioning to '/Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/1-overlapper/partitioning.log'.
-- Configured 2 mhap precompute jobs.
-- Configured 2 mhap overlap jobs.
-- mhap precompute attempt 1 begins with 0 finished, and 2 to compute.
----------------------------------------
-- Starting concurrent execution on Sat Mar 11 20:44:11 2023 with 140.956 GB free disk space (2 processes; 1 concurrently)

    /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/1-overlapper/precompute.sh 1 > /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/1-overlapper/precompute.000001.out 2>&1
    /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/1-overlapper/precompute.sh 2 > /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/1-overlapper/precompute.000002.out 2>&1

-- Finished on Sat Mar 11 20:56:07 2023 (716 seconds) with 140.489 GB free disk space
----------------------------------------
-- All 2 mhap precompute jobs finished successfully.
-- mhap attempt 1 begins with 0 finished, and 2 to compute.
----------------------------------------
-- Starting concurrent execution on Sat Mar 11 20:56:07 2023 with 140.489 GB free disk space (2 processes; 1 concurrently)

    /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/1-overlapper/mhap.sh 1 > /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/1-overlapper/mhap.000001.out 2>&1
    /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/1-overlapper/mhap.sh 2 > /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/1-overlapper/mhap.000002.out 2>&1

-- Finished on Sat Mar 11 20:56:31 2023 (24 seconds) with 140.483 GB free disk space
----------------------------------------
-- Found 2 mhap overlap output files.
----------------------------------------
-- Starting command on Sat Mar 11 20:56:31 2023 with 140.483 GB free disk space

    /Users/paulhebert/opt/anaconda3/libexec/ovStoreBuild \
     -O /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/ecoli.ovlStore.BUILDING \
     -G /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/ecoli.gkpStore \
     -M 2-8 \
     -L /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/1-overlapper/ovljob.files \
     > /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/ecoli.ovlStore.err 2>&1
sh: line 5: 25605 Segmentation fault: 11  /Users/paulhebert/opt/anaconda3/libexec/ovStoreBuild -O /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/ecoli.ovlStore.BUILDING -G /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/ecoli.gkpStore -M 2-8 -L /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/1-overlapper/ovljob.files > /Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/ecoli.ovlStore.err 2>&1

-- Finished on Sat Mar 11 20:56:31 2023 (lickety-split) with 140.483 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 139.  (rc=35584)
ERROR:
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

Disk space available:  140.483 GB

Last 50 lines of the relevant log file (/Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/ecoli.ovlStore.err):

Found 497374 (0.50 million) overlaps.
Configuring for 2.00 GB to 8.00 GB memory and 240 open files.
Will sort using 1 files; 58720256 (58.72 million) overlaps per bucket; 2.00 GB memory per bucket
  bucket   1 has 497374 olaps.
  bucket   2 has 0 olaps.
Will sort 0.497 million overlaps per bucket, using 1 buckets 0.26 GB per bucket.

-- BUCKETIZING --

-  Bucketizing '/Users/paulhebert/opt/anaconda3/ecoli-pacbio/correction/1-overlapper/results/000001.ovb'

canu failed with 'failed to create the overlap store'.

**I am running the demo Pacific Biosciences released P6-C4 chemistry reads for Escherichia coli K12 data to check the functionalities of canu. Can you kindly tell me what might be the issue ?**

**Comment by brianwalenz** [comment]
I'm guessing the small memory limit (8 CPUs and 8 GB) led it to make a bad choice of parameters resulting in an intermediate file with no results (`bucket 2 has 0 olaps.`).  Can you increase the memory limit to 12 GB or 16 GB and try again after removing `correction/ecoli.ovlStore*`?

This also appears to be a very old version of Canu, from sometime around/before 2017.  You can get the latest released version from https://github.com/marbl/canu/releases/tag/v2.2.

**Comment by avvypaks** [comment]
Thank you for the response. I will definitely use a 16GB system and let you know. 

I have some issues while compiling canu from the updated source code from your link: "https://github.com/marbl/canu/releases/tag/v2.2"

I have already gcc installed in my path but it is still showing:



 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2343k  100 2343k    0     0  3228k      0 --:--:-- --:--:-- --:--:-- 3228k
Makefile:505: 
Makefile:509: Compiler 'c++' at '/usr/bin/c++' reports version 'Apple clang version 14.0.0 (clang-1400.0.29.202)'.
Makefile:511: 
Makefile:512: Canu cannot be compiled with this compiler.  Please install GCC and/or
Makefile:513: specify a non-Clang compiler on the command line, e.g.,
Makefile:514:     make CC=/path/to/gcc CXX=/path/to/g++
Makefile:515: 
Makefile:516: *** unsupported compiler.  Stop.

**Comment by skoren** [comment]
Your gcc installation must not be configured to be the default compiler, at least when you run c++ it reports the Apple clang version. What goes `g++ --version` and `which g++` report? You can try the option listed (CC=/path/to/your/gcc CXX=/path/to/your/g++)

**Comment by skoren** [comment]
Idle, older version of canu and compilation indicates incorrect gcc is the system default.
