### ISSUE TITLE
Can't successfully install on Ubuntu 18 using binaries or source: Can't locate canu/Defaults.pm in @INC (you may need to install the canu::Defaults module)

### ISSUE THREAD

**Issue by jmunshisouth** [marbl/canu#2209]
Hello,

I have tried to install canu 2.2 using both the binaries and source, but I always receive this error when trying to run:

Can't locate canu/Defaults.pm in @INC (you may need to install the canu::Defaults module) (@INC contains: /usr/local/bin/../lib/site_perl /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/local/bin/canu line 32.
BEGIN failed--compilation aborted at /usr/local/bin/canu line 32.

I assumed it was a perl issue, so I created a conda environment with perl 5.12.5 but that didn't solve the issue. 

Installing using conda creates a useable canu, but it crashes after reading in the sequences with this error:

'Mhap precompute jobs failed'

Any advice? How do I install the canu::Defaults module?

**Comment by skoren** [comment]
I think you copied part of the canu binaries to a central location but not the libraries when you did the installation. The Defaults.pm is in canu's build/lib/site_perl folder which it looks to be relative to the canu binary. You have to copy either both binary and library or just add canu's build folder to your path.

As for the mhap precompute error, likely a JVM issue but would need the full log to know exact error.

**Comment by jmunshisouth** [comment]
Thank you @skoren . I was able to get an install of v2.2 working by fixing the locations of the files. There was also a rogue entry in the PATH for v1.9 that I installed using the conda package installer that I still haven't located, but I can call v2.2 from its folder. The mhap precompute error turned out to be due to a rogue character in my script.
