### ISSUE TITLE
canu 2.2 failed with nanopores reads during overlap (with or without grid)

### ISSUE THREAD

**Issue by frangeul** [marbl/canu#2212]
My run consist of 4.3 million of nanopores reads (R9) in 10 fastq.gz files.
My command line on x86_64 GNU/Linux : 
```
canu -d testcanu2.2 -p Oregon_BX2 genomeSize=180m useGrid=false minReadLength=1000 minOverlapLength=500 -nanopore-raw fastq_cat_pass/*.fastq.gz
```

(I try with and without grid for the same result)

Tail of the log file after several hours : 
```
.../...
    ./scripts/2-sort.sh 91 > ./logs/2-sort.000091.out 2>&1
    ./scripts/2-sort.sh 93 > ./logs/2-sort.000093.out 2>&1
    ./scripts/2-sort.sh 96 > ./logs/2-sort.000096.out 2>&1
    ./scripts/2-sort.sh 97 > ./logs/2-sort.000097.out 2>&1
    ./scripts/2-sort.sh 99 > ./logs/2-sort.000099.out 2>&1
    ./scripts/2-sort.sh 100 > ./logs/2-sort.000100.out 2>&1
    ./scripts/2-sort.sh 108 > ./logs/2-sort.000108.out 2>&1
    ./scripts/2-sort.sh 111 > ./logs/2-sort.000111.out 2>&1
    ./scripts/2-sort.sh 113 > ./logs/2-sort.000113.out 2>&1

-- Finished on Fri Mar 17 02:10:35 2023 (971 seconds) with 17940.322 GB free disk space
----------------------------------------
--
-- Overlap store sorting jobs failed, tried 2 times, giving up.
--   job correction/Oregon_BX2.ovlStore.BUILDING/0006 FAILED.
--   job correction/Oregon_BX2.ovlStore.BUILDING/0013 FAILED.
--   job correction/Oregon_BX2.ovlStore.BUILDING/0020 FAILED.
--   job correction/Oregon_BX2.ovlStore.BUILDING/0034 FAILED.
--   job correction/Oregon_BX2.ovlStore.BUILDING/0036 FAILED.
--   job correction/Oregon_BX2.ovlStore.BUILDING/0050 FAILED.
--   job correction/Oregon_BX2.ovlStore.BUILDING/0069 FAILED.
--   job correction/Oregon_BX2.ovlStore.BUILDING/0086 FAILED.
--   job correction/Oregon_BX2.ovlStore.BUILDING/0088 FAILED.
--

ABORT:
ABORT: canu 2.2
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:

```

**Comment by frangeul** [comment]
the 1-bucketsize finish by a succes! but the 2-sort finish by a Killed :


$ more 2-sort.000006.out


Found perl:
   /usr/bin/perl
   This is perl 5, version 26, subversion 3 (v5.26.3) built for x86_64-linux-thread-multi

Found java:
   /opt/gensoft/exe/graalvm/ce-java8-20.0.0/bin/java
   openjdk version "1.8.0_242"

Found canu:
   /opt/gensoft/exe/canu/2.2/bin/canu
   canu 2.2

Running job 6 based on command line options.

Attempting to increase maximum allowed processes and open files.
  Changed max processes per user from 4096 to 2061910 (max 2061910).
  Changed max open files from 65536 to 131072 (max 131072).


Finding overlaps.
  found    2943494 overlaps in './Oregon_BX2.ovlStore.BUILDING/bucket0001/sliceSizes'.
  found    3059592 overlaps in './Oregon_BX2.ovlStore.BUILDING/bucket0006/sliceSizes'.
  found    3134425 overlaps in './Oregon_BX2.ovlStore.BUILDING/bucket0010/sliceSizes'.
  found    3398380 overlaps in './Oregon_BX2.ovlStore.BUILDING/bucket0014/sliceSizes'.
  found   80058954 overlaps in './Oregon_BX2.ovlStore.BUILDING/bucket0018/sliceSizes'.
  found   76603969 overlaps in './Oregon_BX2.ovlStore.BUILDING/bucket0019/sliceSizes'.
  found   74193508 overlaps in './Oregon_BX2.ovlStore.BUILDING/bucket0020/sliceSizes'.
  found   55961079 overlaps in './Oregon_BX2.ovlStore.BUILDING/bucket0021/sliceSizes'.

Loading  299353401 overlaps using 6.69 GB of allowed (-M) 8 GB memory.
./scripts/2-sort.sh: line 111: 1213062 Killed                  $bin/ovStoreSorter -deletelate -O ./Oregon_BX2.ovlStore.BUILDING -S ../Oregon_BX2.seqStore -C ./Oregon_BX2.ovlStore.config -f -s $jobid -M 8







$ more 1-bucketize.000006.out

Found perl:
   /usr/bin/perl
   This is perl 5, version 26, subversion 3 (v5.26.3) built for x86_64-linux-thread-multi

Found java:
   /opt/gensoft/exe/graalvm/ce-java8-20.0.0/bin/java
   openjdk version "1.8.0_242"

Found canu:
   /opt/gensoft/exe/canu/2.2/bin/canu
   canu 2.2

Running job 6 based on command line options.

Attempting to increase maximum allowed processes and open files.
  Changed max processes per user from 4096 to 2061910 (max 2061910).
  Changed max open files from 65536 to 131072 (max 131072).


Opened '../Oregon_BX2.seqStore' with 3125084 reads.

Constructing slice 6 for store './Oregon_BX2.ovlStore.BUILDING'.
 - Filtering overlaps over 1.0000 fraction error.

Bucketizing input    1 out of    2 - '1-overlapper/results/000006.ovb'
Bucketizing input    2 out of    2 - '1-overlapper/results/000173.ovb'
Success!



--
Lionel Frangeul
Viruses and RNAi 
Institut Pasteur,
Université Paris Cité, CNRS UMR3569
25 rue du Dr ROUX,
F-75015 Paris, France.

________________________________
De : Sergey Koren ***@***.***>
Envoyé : vendredi 17 mars 2023 15:50:39
À : marbl/canu
Cc : Lionel FRANGEUL; Author
Objet : Re: [marbl/canu] canu 2.2 failed with nanopores reads during overlap (with or without grid) (Issue #2212)


What's the contents of one of the log files for a job that failed (e.g. 006 or 013 in correction/Oregon_BX2.ovlStore.BUILDING/logs/)?

**Comment by skoren** [comment]
Looks like the grid is killing it for using too much memory. You can request more memory for this step either on grid or on the single node you're running on, adding `ovsMemory=16` to the command should let it run and resume from where you are.

**Comment by frangeul** [comment]
OK I will test that next week. 16 Go it's a lot, my machine have 500 Go of RAM.

what is the default value ?



--
Lionel Frangeul
Viruses and RNAi 
Institut Pasteur,
Université Paris Cité, CNRS UMR3569
25 rue du Dr ROUX,
F-75015 Paris, France.

________________________________
De : Sergey Koren ***@***.***>
Envoyé : vendredi 17 mars 2023 19:28:00
À : marbl/canu
Cc : Lionel FRANGEUL; Author
Objet : Re: [marbl/canu] canu 2.2 failed with nanopores reads during overlap (with or without grid) (Issue #2212)


Looks like the grid is killing it for using too much memory. You can request more memory for this step either on grid or on the single node you're running on, adding ovsMemory=16 to the command should let it run and resume from where you are.

**Comment by skoren** [comment]
The default value it is using is 8gb/jo but it can run more than one job in parallel. It is possible it's trying to use more memory than you've allocated for its job. It will print a preamble that says how many jobs it plans to run and how much memory it will use in total. You can restrict the memory it is allowed to use with maxMemory and so you could lower or set ovsMemory, both would accomplish the effect of running fewer sorting jobs at a time.

**Comment by frangeul** [comment]
I try ovsMemory=16 then 24 then 32 then 64 for the same problem.


End of the log :

'''

-- Finished on Thu Mar 23 06:56:58 2023 (1548 seconds) with 18347.363 GB free disk space
----------------------------------------
--
-- Overlap store sorting jobs failed, tried 2 times, giving up.
--   job correction/Oregon_BX2.ovlStore.BUILDING/0002 FAILED.
--

ABORT:
ABORT: canu 2.2
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:

'''


End of the file 2-sort.000002.out :

'''

Running job 2 based on command line options.

Attempting to increase maximum allowed processes and open files.
  Changed max processes per user from 4096 to 2061910 (max 2061910).
  Changed max open files from 65536 to 131072 (max 131072).


Finding overlaps.
  found  229879267 overlaps in './Oregon_BX2.ovlStore.BUILDING/bucket0001/sliceSizes'.
  found  210260818 overlaps in './Oregon_BX2.ovlStore.BUILDING/bucket0002/sliceSizes'.
  found  177443199 overlaps in './Oregon_BX2.ovlStore.BUILDING/bucket0003/sliceSizes'.
  found  239552707 overlaps in './Oregon_BX2.ovlStore.BUILDING/bucket0004/sliceSizes'.
  found  130739442 overlaps in './Oregon_BX2.ovlStore.BUILDING/bucket0005/sliceSizes'.
  found  175762191 overlaps in './Oregon_BX2.ovlStore.BUILDING/bucket0006/sliceSizes'.
  found  199619087 overlaps in './Oregon_BX2.ovlStore.BUILDING/bucket0007/sliceSizes'.
  found  171948836 overlaps in './Oregon_BX2.ovlStore.BUILDING/bucket0008/sliceSizes'.
  found  233563054 overlaps in './Oregon_BX2.ovlStore.BUILDING/bucket0009/sliceSizes'.
  found  201524033 overlaps in './Oregon_BX2.ovlStore.BUILDING/bucket0010/sliceSizes'.
  found  153970997 overlaps in './Oregon_BX2.ovlStore.BUILDING/bucket0011/sliceSizes'.
  found  174052495 overlaps in './Oregon_BX2.ovlStore.BUILDING/bucket0012/sliceSizes'.
  found  250989988 overlaps in './Oregon_BX2.ovlStore.BUILDING/bucket0013/sliceSizes'.
  found  191434794 overlaps in './Oregon_BX2.ovlStore.BUILDING/bucket0014/sliceSizes'.

Loading 2740740908 overlaps using 61.26 GB of allowed (-M) 63 GB memory.
./scripts/2-sort.sh: line 111: 2479040 Killed                  $bin/ovStoreSorter -deletelate -O ./Oregon_BX2.ovlStore.BUILDING -S ../Oregon_
BX2.seqStore -C ./Oregon_BX2.ovlStore.config -f -s $jobid -M 63

'''



--
Lionel Frangeul
Viruses and RNAi 
Institut Pasteur,
Université Paris Cité, CNRS UMR3569
25 rue du Dr ROUX,
F-75015 Paris, France.

________________________________
De : Sergey Koren ***@***.***>
Envoyé : mercredi 22 mars 2023 03:00:03
À : marbl/canu
Cc : Lionel FRANGEUL; Author
Objet : Re: [marbl/canu] canu 2.2 failed with nanopores reads during overlap (with or without grid) (Issue #2212)


The default value it is using is 8gb/job but it can run more than one job in parallel. It is possible it's trying to use more memory than you've allocated for its job. It will print a preamble that says how many jobs it plans to run and how much memory it will use in total. You can restrict the memory it is allowed to use with maxMemory and so you could lower or set ovsMemory, both would accomplish the effect of running fewer sorting jobs at a time.

**Comment by skoren** [comment]
What was the log in the actual job that was running, the same killed message? How much memory did it request on the cluster and how much did it actually use before being killed? Did you also limit Canu to the memory/cpu you requested for this job.

**Comment by skoren** [comment]
How much memory did you reserve for the cluster node when running that canu command? What did the canu preamble say that I asked about originally?

**Comment by frangeul** [comment]
Sorry but I don't understand your question.

I'm using useGrid=false in my command line, so I'm not using a cluster.

I only use one machine with its cpu and its RAM and therefore I reserve nothing...?

what is the canu preamble ? is it in a log file ?


--
Lionel Frangeul
Viruses and RNAi 
Institut Pasteur,
Université Paris Cité, CNRS UMR3569
25 rue du Dr ROUX,
F-75015 Paris, France.

________________________________
De : Sergey Koren ***@***.***>
Envoyé : mercredi 5 avril 2023 17:50:46
À : marbl/canu
Cc : Lionel FRANGEUL; Author
Objet : Re: [marbl/canu] canu 2.2 failed with nanopores reads during overlap (with or without grid) (Issue #2212)


How much memory did you reserve for the cluster node when running that canu command? What did the canu preamble say that I asked about originally?

**Comment by skoren** [comment]
You're using one machine but you reserved that machine through the cluster, correct? Otherwise, nothing should be killing the canu run for memory usage. I was asking how you reserved that machine where you launched canu. The preamble is the first print out to stderr when you launch canu, it lists job names and how much resource each will use.

**Comment by frangeul** [comment]
I reserved my machine with a salloc and the --exclusive option.

I thought that with this option my limits were those of the machine, but apparently not, there remained certain thresholds because I added --mem=0 at the last test and it worked, with the option ovsMemory=64 I was able to get an assembly.



--
Lionel Frangeul
Viruses and RNAi 
Institut Pasteur,
Université Paris Cité, CNRS UMR3569
25 rue du Dr ROUX,
F-75015 Paris, France.

________________________________
De : Sergey Koren ***@***.***>
Envoyé : jeudi 6 avril 2023 17:52:15
À : marbl/canu
Cc : Lionel FRANGEUL; Author
Objet : Re: [marbl/canu] canu 2.2 failed with nanopores reads during overlap (with or without grid) (Issue #2212)


You're using one machine but you reserved that machine through the cluster, correct? Otherwise, nothing should be killing the canu run for memory usage. I was asking how you reserved that machine where you launched canu. The preamble is the first print out to stderr when you launch canu, it lists job names and how much resource each will use.
