### ISSUE TITLE
No corrected reads after assembling a short amplicon

### ISSUE THREAD

**Issue by Koen-vdl** [marbl/canu#2214]
I have been experiencing an issue while assembling a short amplicon. `canu` finishes successfully (no crashes / errors) but I don't end up with any corrected reads. I have used a similar approach to assemble other short amplicons of similar size. I tried breaking the assembly down in more manageable steps (`-correct` only) to identify the issue but can't work it out. 

I use `canu` v2.2 on a Ubuntu 20.04.6 LTS server

I run `canu` in the following way:

`canu -correct -d canu_barcode01_ITS2 -p canu_barcode01_ITS2 useGrid=false maxThreads=60 genomeSize=1000 minReadLength=300 minOverlapLength=200 corOutCoverage=100 maxInputCoverage=100  -nanopore-raw barcode01_ITS2.fastq.gz`

Below you can find the canu report.

Could you guys shed some light on this?

Thanks for any support!

KV

```
[CORRECTION/READS]
--
-- In sequence store './canu_barcode01_ITS2.seqStore':
--   Found 223 reads.
--   Found 100164 bases (100.16 times coverage).
--    Histogram of raw reads:
--    
--    G=100164                           sum of  ||               length     num
--    NG         length     index       lengths  ||                range    seqs
--    ----- ------------ --------- ------------  ||  ------------------- -------
--    00010          479        17        10475  ||        391-401             1|-
--    00020          473        38        20471  ||        402-412             1|-
--    00030          438        60        30449  ||        413-423            11|-------
--    00040          437        82        40080  ||        424-434           113|---------------------------------------------------------------
--    00050          434       105        50084  ||        435-445            47|---------------------------
--    00060          432       129        60469  ||        446-456             1|-
--    00070          430       152        70380  ||        457-467             3|--
--    00080          428       175        80240  ||        468-478            26|---------------
--    00090          426       199        90488  ||        479-489            12|-------
--    00100          391       222       100164  ||        490-500             0|
--    001.000x                 223       100164  ||        501-511             0|
--                                               ||        512-522             2|--
--                                               ||        523-533             1|-
--                                               ||        534-544             0|
--                                               ||        545-555             1|-
--                                               ||        556-566             0|
--                                               ||        567-577             0|
--                                               ||        578-588             0|
--                                               ||        589-599             0|
--                                               ||        600-610             0|
--                                               ||        611-621             0|
--                                               ||        622-632             0|
--                                               ||        633-643             0|
--                                               ||        644-654             0|
--                                               ||        655-665             0|
--                                               ||        666-676             0|
--                                               ||        677-687             0|
--                                               ||        688-698             0|
--                                               ||        699-709             0|
--                                               ||        710-720             0|
--                                               ||        721-731             0|
--                                               ||        732-742             0|
--                                               ||        743-753             0|
--                                               ||        754-764             0|
--                                               ||        765-775             0|
--                                               ||        776-786             0|
--                                               ||        787-797             0|
--                                               ||        798-808             0|
--                                               ||        809-819             0|
--                                               ||        820-830             0|
--                                               ||        831-841             0|
--                                               ||        842-852             0|
--                                               ||        853-863             2|--
--                                               ||        864-874             0|
--                                               ||        875-885             0|
--                                               ||        886-896             0|
--                                               ||        897-907             1|-
--                                               ||        908-918             0|
--                                               ||        919-929             1|-
--

[CORRECTION/MERS]
--
--  16-mers                                                                                           Fraction
--    Occurrences   NumMers                                                                         Unique Total
--       1-     1         0                                                                        0.0000 0.0000
--       2-     2       707 ********************************************************************** 0.3263 0.0160
--       3-     4       688 ********************************************************************   0.4735 0.0267
--       5-     7       112 ***********                                                            0.6641 0.0459
--       8-    11        43 ****                                                                   0.6996 0.0516
--      12-    16        41 ****                                                                   0.7171 0.0559
--      17-    22        52 *****                                                                  0.7360 0.0627
--      23-    29        29 **                                                                     0.7637 0.0769
--      30-    37        10                                                                        0.7734 0.0830
--      38-    46         8                                                                        0.7780 0.0873
--      47-    56         8                                                                        0.7803 0.0898
--      57-    67         9                                                                        0.7845 0.0951
--      68-    79         2                                                                        0.7882 0.1010
--      80-    92         0                                                                        0.0000 0.0000
--      93-   106        73 *******                                                                0.7900 0.1050
--     107-   121        30 **                                                                     0.8256 0.1905
--     122-   137         4                                                                        0.8371 0.2221
--     138-   154         0                                                                        0.0000 0.0000
--     155-   172        27 **                                                                     0.8389 0.2285
--     173-   191        63 ******                                                                 0.8514 0.2789
--     192-   211       234 ***********************                                                0.8879 0.4448
--     212-   232        27 **                                                                     0.9889 0.9408
--
--           0 (max occurrences)
--       88649 (total mers, non-unique)
--        2167 (distinct mers, non-unique)
--           0 (unique mers)

[CORRECTION/LAYOUT]
--                             original      original
--                            raw reads     raw reads
--   category                w/overlaps  w/o/overlaps
--   -------------------- ------------- -------------
--   Number of Reads                207         22035
--   Number of Bases              93344          6820
--   Coverage                    93.344         6.820
--   Median                         434             0
--   Mean                           450             0
--   N50                            434           432
--   Minimum                        412             0
--   Maximum                        925           440
--   
--                                        --------corrected---------  ----------rescued----------
--                             evidence                     expected                     expected
--   category                     reads            raw     corrected            raw     corrected
--   -------------------- -------------  ------------- -------------  ------------- -------------
--   Number of Reads                223            197           197              0             0
--   Number of Bases             100164          88039         85608              0             0
--   Coverage                   100.164         88.039        85.608          0.000         0.000
--   Median                         434            434           431              0             0
--   Mean                           449            446           434              0             0
--   N50                            434            434           432              0             0
--   Minimum                        391            412           371              0             0
--   Maximum                        925            925           474              0             0
--   
--                        --------uncorrected--------
--                                           expected
--   category                       raw     corrected
--   -------------------- ------------- -------------
--   Number of Reads              22045         22045
--   Number of Bases              12125           499
--   Coverage                    12.125         0.499
--   Median                           0             0
--   Mean                             0             0
--   N50                            432             0
--   Minimum                          0             0
--   Maximum                        900           499
--   
--   Maximum Memory           532656500


```

**Comment by skoren** [comment]
How big is the amplicon, I see you're using a very small minimum overlap which may be related to #2182. You can build the latest code to get the fix that uses minOverlapLength not a fixed 500bp threshold.

**Comment by Koen-vdl** [comment]
The amplicon is tiny (429bp) which is why I landed on `minReadLength=300` `minOverlapLength=200`. 
`minReadLength=300` `minOverlapLength=200` did work on two slightly larger amplicons of approx. 500 and 600bp.
I will try to build the latest code from source next week. 
Thanks for the quick reply! Much appreciated!

**Comment by Koen-vdl** [comment]
Hi @skoren, 

As instructed I built the latest version of `canu` from source (canu snapshot v2.3-development ) and, as you predicted, I indeed ended up with my corrected short reads!

I did notice though non of the corrected reads make it through trimming.  Again, `canu -trim` finishes successfully (no crashes / errors) but I don't end up with any corrected reads.

```canu -correct -d $output_dir/barcode$id/barcode${id}_${assay}_canu_correct -p barcode${id}_${assay} useGrid=false maxThreads=60 genomeSize=1000 minReadLength=300 minOverlapLength=200 corOutCoverage=100 maxInputCoverage=100 corMinCoverage=50 -nanopore-raw $output_dir/barcode$id/barcode${id}_${assay}.fastq.gz

canu -trim -d $output_dir/barcode$id/barcode${id}_${assay}_canu_trim -p barcode${id}_${assay} useGrid=false maxThreads=60 genomeSize=1000 minReadLength=300 minOverlapLength=200 corOutCoverage=100 maxInputCoverage=100 corMinCoverage=50 -corrected -nanopore $output_dir/barcode$id/barcode${id}_${assay}_canu_correct/barcode${id}_${assay}.correctedReads.fasta.gz```

Below you can find the `canu -trim` report. 

```
[TRIMMING/READS]
--
-- In sequence store './barcode04_ITS2.seqStore':
--   Found 130 reads.
--   Found 54751 bases (54.75 times coverage).
--    Histogram of corrected reads:
--    
--    G=54751                            sum of  ||               length     num
--    NG         length     index       lengths  ||                range    seqs
--    ----- ------------ --------- ------------  ||  ------------------- -------
--    00010          430        12         5590  ||        389                 1|--
--    00020          430        25        11180  ||        390                 0|
--    00030          430        38        16770  ||        391                 0|
--    00040          422        51        22277  ||        392                 0|
--    00050          418        64        27734  ||        393                 0|
--    00060          418        77        33168  ||        394                 0|
--    00070          418        90        38602  ||        395                 0|
--    00080          418       103        44036  ||        396                 0|
--    00090          416       116        49463  ||        397                 0|
--    00100          389       129        54751  ||        398                 0|
--    001.000x                 130        54751  ||        399                 0|
--                                               ||        400                 0|
--                                               ||        401                 0|
--                                               ||        402                 2|---
--                                               ||        403                 0|
--                                               ||        404                 1|--
--                                               ||        405                 1|--
--                                               ||        406                 0|
--                                               ||        407                 1|--
--                                               ||        408                 0|
--                                               ||        409                 0|
--                                               ||        410                 4|-----
--                                               ||        411                 0|
--                                               ||        412                 2|---
--                                               ||        413                 0|
--                                               ||        414                 0|
--                                               ||        415                 1|--
--                                               ||        416                 2|---
--                                               ||        417                 3|----
--                                               ||        418                52|---------------------------------------------------------------
--                                               ||        419                 0|
--                                               ||        420                 4|-----
--                                               ||        421                 1|--
--                                               ||        422                 5|-------
--                                               ||        423                 7|---------
--                                               ||        424                 3|----
--                                               ||        425                 0|
--                                               ||        426                 0|
--                                               ||        427                 0|
--                                               ||        428                 0|
--                                               ||        429                 0|
--                                               ||        430                40|-------------------------------------------------
--

[TRIMMING/MERS]
--
--  22-mers                                                                                           Fraction
--    Occurrences   NumMers                                                                         Unique Total
--       1-     1         0                                                                        0.0000 0.0000
--       2-     2         0                                                                        0.0000 0.0000
--       3-     4        30 *****                                                                  0.0274 0.0008
--       5-     7         0                                                                        0.0000 0.0000
--       8-    11         0                                                                        0.0000 0.0000
--      12-    16         1                                                                        0.0654 0.0024
--      17-    22        25 ****                                                                   0.1055 0.0090
--      23-    29         9 *                                                                      0.1371 0.0152
--      30-    37         0                                                                        0.0000 0.0000
--      38-    46         0                                                                        0.0000 0.0000
--      47-    56         1                                                                        0.1392 0.0161
--      57-    67         1                                                                        0.1414 0.0173
--      68-    79        11 **                                                                     0.1498 0.0228
--      80-    92        11 **                                                                     0.1878 0.0513
--      93-   106         0                                                                        0.0000 0.0000
--     107-   121        29 *****                                                                  0.2300 0.0925
--     122-   137       356 ********************************************************************** 0.2785 0.1451
--
--           0 (max occurrences)
--       51943 (total mers, non-unique)
--         474 (distinct mers, non-unique)
--           0 (unique mers)

[TRIMMING/TRIMMING]
--  PARAMETERS:
--  ----------
--      300    (reads trimmed below this many bases are deleted)
--   0.1200    (use overlaps at or below this fraction error)
--      500    (break region if overlap is less than this long, for 'largest covered' algorithm)
--        2    (break region if overlap coverage is less than this many reads, for 'largest covered' algorithm)
--  
--  INPUT READS:
--  -----------
--     130 reads        54751 bases (reads processed)
--       0 reads            0 bases (reads not processed, previously deleted)
--       0 reads            0 bases (reads not processed, in a library where trimming isn't allowed)
--  
--  OUTPUT READS:
--  ------------
--       0 reads            0 bases (trimmed reads output)
--       0 reads            0 bases (reads with no change, kept as is)
--       0 reads            0 bases (reads with no overlaps, deleted)
--     130 reads        54751 bases (reads with short trimmed length, deleted)
--  
--  TRIMMING DETAILS:
--  ----------------
--       0 reads            0 bases (bases trimmed from the 5' end of a read)
--       0 reads            0 bases (bases trimmed from the 3' end of a read)

[TRIMMING/SPLITTING]
--  PARAMETERS:
--  ----------
--      300    (reads trimmed below this many bases are deleted)
--   0.1200    (use overlaps at or below this fraction error)
--  INPUT READS:
--  -----------
--       0 reads            0 bases (reads processed)
--     130 reads        54751 bases (reads not processed, previously deleted)
--       0 reads            0 bases (reads not processed, in a library where trimming isn't allowed)
--  
--  PROCESSED:
--  --------
--       0 reads            0 bases (no overlaps)
--       0 reads            0 bases (no coverage after adjusting for trimming done already)
--       0 reads            0 bases (processed for chimera)
--       0 reads            0 bases (processed for spur)
--       0 reads            0 bases (processed for subreads)
--  
--  READS WITH SIGNALS:
--  ------------------
--       0 reads            0 signals (number of 5' spur signal)
--       0 reads            0 signals (number of 3' spur signal)
--       0 reads            0 signals (number of chimera signal)
--       0 reads            0 signals (number of subread signal)
--  
--  SIGNALS:
--  -------
--       0 reads            0 bases (size of 5' spur signal)
--       0 reads            0 bases (size of 3' spur signal)
--       0 reads            0 bases (size of chimera signal)
--       0 reads            0 bases (size of subread signal)
--  
--  TRIMMING:
--  --------
--       0 reads            0 bases (trimmed from the 5' end of the read)
--       0 reads            0 bases (trimmed from the 3' end of the read)

```

**Comment by skoren** [comment]
Canu has two values, first is the overlap length which controls what size overlaps are computed but then there is also the overlap length use. The two don't have to be equal and I think the default for trimming is 500bp and so is throwing away everything it computed. Try adding `trimReadsOverlap=300`
