### ISSUE TITLE
how to use just 4 nodes in my cluster machine

### ISSUE THREAD

**Issue by frsepulveda** [marbl/canu#2216]
Hi! i' am running canu v2.2 on a cluster machine. I'am allowed to use just 4 of our 24 available nodes via slurm. 
For the moment, i running locally with useGrid=false:

canu -p mazzalam -d mazzalam-pacbio genomeSize=100m -pacbio-raw ../limpieza/1A1_CLEAN.fa useGrid=false 

but id like to use 4 nodes for the job. 

how can i set up my canu run?

**Comment by brianwalenz** [comment]
I don't know how to limit array jobs to using at most four _nodes_.

However, you can use Canu option `gridEngineArrayOption="-a ARRAY_JOBS%4"` to tell Slurm to run only four _jobs_ at a time.  This uses the `%` modifier of Slurm's sbatch option `-a` as described at https://slurm.schedmd.com/sbatch.html#OPT_array for details.  Canu will replace `ARRAY_JOBS` with the total number of jobs it needs to run before calling sbatch.

**Comment by skoren** [comment]
Idle
