### ISSUE TITLE
Error:  canu iteration count too high, stopping pipeline

### ISSUE THREAD

**Issue by PrishaTiwari05** [marbl/canu#2217]
Hello, I'm a novice at using command line pipelines. I'm running canu version 1.5 to correct a pacbio genome and it stopped running after a few hours saying:

"Don't panic, but a mostly harmless error occurred and Canu stopped.

Canu release v1.5 failed with:
 canu iteration count too high, stopping pipeline (most likely a problem in the grid-based computes)"

I looked up the interactions on github and read that my version might have a bug so I reinstalled it but the same thing happened again.

This was my code:
canu -correct \
  -p PTER -d /DATA2/prisha/canu-2.2/build/bin \
  genomeSize=1.2g \
  -pacbio-raw  PTER.fasta

Please help me resolve this, thank you so much!

**Comment by skoren** [comment]
That release is very old, over 5 years. I suggest trying the assembly with a recent release like v2.2. If it still fails post the full log of the run.

**Comment by PrishaTiwari05** [comment]
Thank you so much for your reply. As I mentioned, I installed a new version and ran the command again but I'm just noticing that the new version I installed said it's 2.2 but it's running as v1.5 only. 

I used the source code to download: 
curl -L https://github.com/marbl/canu/releases/download/v2.2/canu-2.2.tar.xz --output canu-2.2.tar.xz

Please let me know what to do, thanks!

**Comment by PrishaTiwari05** [comment]
<img width="649" alt="Screenshot 2023-03-22 at 12 15 47 PM" src="https://user-images.githubusercontent.com/128525779/226823417-7fc0e97d-0f94-453d-8b93-a779770f70d3.png">

Here's a screenshot of the command and the input I get right after running it.

**Comment by skoren** [comment]
You have multiple versions installed it seems, the 1.5 version is in your path so when you say `canu` it runs the older version. Try providing the full path to the canu from v2.2. You probably also want to uninstall the v1.5 version to avoid confusion in the future. The -d is also incorrect, it should be where you want your assembly to go not the location of canu itself.

**Comment by PrishaTiwari05** [comment]
Thank you so much for your suggestions! I will try this and let you know if it works.

**Comment by skoren** [comment]
Yes, that would be my comment about providing the full path above. Run it as `/DATA2/prisha/canu-2.2/build/bin/canu` or add that to your path. If the canu file is not in that folder it likely means the compilation wasn't successful.

**Comment by PrishaTiwari05** [comment]
I've tried running it with the full path but it says "there's no such file or directory". I downloaded this version of canu using the source code:
curl -L https://github.com/marbl/canu/releases/download/v2.2/canu-2.2.tar.xz --output canu-2.2.tar.xz
tar -xJf canu-2.2.tar.xz
cd canu-2.2/src
make -j 8

Do you suggest I install it using another method?

**Comment by skoren** [comment]
Did the make report any errors or did it complete successfully? What's the contents of canu-2.2/build/bin after you ran make?

There are the pre-complied binaries for common platforms you could use instead or you could use conda with the specific version (e.g. canu=2.2) to install.

**Comment by skoren** [comment]
No reason to as that looks complete, what if you run ./canu from inside the bin folder?
