### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mdelmans** [marbl/canu#2218]
Hi ! 

Are you planning to release Canu open-source ? At the moment it has no license, which prevents other people to use in their products, modify and re-distribute.

**Comment by skoren** [comment]
Not sure what you mean, there's a README.licenses and README.license.gpl. There are multiple licenses that cover Canu's work, depending on how old the code is and where the person working on it was at the time.

**Comment by mdelmans** [comment]
Sorry, it's too late for my brain. Was looking for LICENSE.md, totally missed README.licenses
