### ISSUE TITLE
canu again out of space on a bucket step(

### ISSUE THREAD

**Issue by vmukhina** [marbl/canu#2219]
Hi, I am trying to run canu assembly on ~55x coverage nanopore human cancer data with following parameters (based on FAQ and some issues here):
genomeSize=3.2g \
 minReadLength=3000 \
 minOverlapLength=2000 \
 purgeOverlaps=aggressive \
 corMhapFilterThreshold=0.0000000002 \
 corMhapOptions="--threshold 0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50" \
 mhapMemory=60g mhapBlockSize=500 ovlMerDistinct=0.975 

After some trials, I finished the .obv file construction stage with around 1000 obv files, each around 40 GB. At the next step, processing each obv file results in a 95 GB bucket directory (so it'd be 95 TB in total?). I am really impressed by this enormous space usage, and actually, I don't have that much. What else can I do to reduce space usage, and what actually triggers such behavior? I expect my region of interest to be highly repetitive, but it's relatively small.

Thank you!

**Comment by skoren** [comment]
The number of overlap buckets isn't necessarily 1-to-1 to the number of ovb files. The configuration file for the overlap store will have more information on how many sort jobs/buckets there will be (config.txt).  Check the number of buckets there to estimate how much space it's going to use. It will also erase the inputs as the buckets are made. 

If the space estimated from above is too large, yes you can reduce usage. There are probably a lot of shorter overlaps and ONT reads have also gotten much higher quality so the thresholds are probably too permissive. You could increase the minimum identity/overlap length and/or the minimum read length further but that would require filtering your current output (take a look at the overlapConvert/overlapImport binaries). The first will convert the ovb files to ascii and the second will filter it by read length/overlap length/identity.

I would suggest trying to run an uncorrected ONT assembly instead, as listed on the quick start here: 
https://canu.readthedocs.io/en/latest/quick-start.html#correct-trim-and-assemble-manually assuming your data is > than about 95% accuracy.

**Comment by vmukhina** [comment]
Thank you for the prompt feedback! We use 9.4 flowcells and HAC model so the data accuracy is not ideal, but I'll try both options (uncorrected + very long reads only).
I wonder if there is '-corrected' option missing in command from manual:
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/18194781/230735831-2ee4ad54-2923-489e-8cab-bd2657da0c23.png">
Without this my data enter correction step as usually.

**Comment by skoren** [comment]
No, the command is correct, `-pacbio-hifi` option disables correction. If that option doesn't exist then you probably are using an old version of canu rather than a recent release.

**Comment by skoren** [comment]
Idle
