### ISSUE TITLE
MhapRuntimeException:　K-mer filter file first line must contain estimated number of k-mers in the file (long)

### ISSUE THREAD

**Issue by bioprojects** [marbl/canu#222]
Dear developers, 

Thank you for developing and maintaining this great software!

I'm try to assemble R9 1D data
http://s3.climb.ac.uk/nanopore/E_coli_K12_1D_R9.2_SpotON_2.pass.fasta

but canu causes the following error:
Reading in filter file ~/nanopore/ecoli_R9/correction/0-mercounts/ecoli.ms16.frequentMers.ignore.gz.
Exception in thread "main" Starting mhap precompute.
edu.umd.marbl.mhap.impl.MhapRuntimeException: Could not parse k-mer filter file.
MhapRuntimeException: K-mer filter file first line must contain estimated number of k-mers in the file (long)

When I look at the "igonore.gz" file, the first line is "-1" although the file has 145 rows.
Is it perhaps the cause?

Could you help how to fix this problem?

Thank you very much in advance.

Koji Yahara
Senior Research Fellow
Department of Bacteriology II
National Institute of Infectious Diseases
4-7-1 Gakuen, Musashimurayama, Tokyo
2080011 Japan
Tel: +81-42-561-0771 (Ex. 3539)

**Comment by brianwalenz** [comment]
Hi-  Can you attach (to the issue in github, not the email) the 'histogram' file in the same directory?

And you might as well paste in the first ten or so lines of 'ecoli.ms16.frequentMers.ignore'.

**Comment by bioprojects** [comment]
Thank you very much for your reply.  Attached are the "histogram" files, one of which is produced in another environment that did not caused the error.  They are indeed different.  

[ecoli.ms16.histogram.NG.txt](https://github.com/marbl/canu/files/411659/ecoli.ms16.histogram.NG.txt)
[ecoli.ms16.histogram.OK.txt](https://github.com/marbl/canu/files/411660/ecoli.ms16.histogram.OK.txt)

Below are the the first ten or so lines of 'ecoli.ms16.frequentMers.ignore' that caused the error:

-1
AAAACAGCAATACGTA        9.544251e-06
TACGTATTGCTGTTTT        9.544251e-06
AAAACGCGAAAGCGTT        1.252861e-05
AACGCTTTCGCGTTTT        1.252861e-05
AAACAGCAATACGTAA        2.005148e-05
TTACGTATTGCTGTTT        2.005148e-05
AAACGCGAAAGCGTTT        1.598801e-05
AAACGCTTTCGCGTTT        1.598801e-05
AAAGCGTTTCACGATA        1.201045e-05


Below are the the first ten or so lines of 'ecoli.ms16.frequentMers.ignore' that did not causethe error:

142
AAAACAGCAATACGTA        9.544251e-06
TACGTATTGCTGTTTT        9.544251e-06
AAAACGCGAAAGCGTT        1.252861e-05
AACGCTTTCGCGTTTT        1.252861e-05
AAACAGCAATACGTAA        2.005148e-05
TTACGTATTGCTGTTT        2.005148e-05
AAACGCGAAAGCGTTT        1.598801e-05
AAACGCTTTCGCGTTT        1.598801e-05
AAAGCGTTTCACGATA        1.201045e-05



Thank you very much in advance.
Best wishes,

**Comment by brianwalenz** [comment]
This was fixed in:
  https://github.com/marbl/canu/commit/4d07faca1d54852966e8ca9f4bbd4bf607b521d3#diff-748ccd8ce778cb244accd7e340740ed4

It is a one line change to one file.  You can make the change by hand by adding the two 'resizeArray' flags to line 483 of file src/meryl/libmeryl.C as shown, then recompiling.  This choice has the benefit of fixing only the bug, and not introducing other problems.

Alternatively, you can download the latest snapshot of the entire project.  This choice will update all the code to our development version, which has not been rigorously tested yet.

**Comment by bioprojects** [comment]
Thank you very much!  But the compilation failed in my environment.
Could you paste the recompiled meryl here?

**Comment by bioprojects** [comment]
Thank you very much! But the compilation failed in my environment.
Could you attach the recompiled meryl here?

**Comment by brianwalenz** [comment]
I'm assuming you're on Linux.

[meryl.gz](https://github.com/marbl/canu/files/411755/meryl.gz)

**Comment by bioprojects** [comment]
Thank you so much!  I've confirmed that the recompiled meryl did not caused the error.  

Thanks a lot again.

Best wishes,
