### ISSUE TITLE
Limiting the number of parallelized Canu jobs on SGE grid

### ISSUE THREAD

**Issue by alvizain786** [marbl/canu#2222]
Hi Everyone, 

I am running Canu v2.2 on the grid, but it ends up using the whole grid with its parallelized jobs. This is great if I am the only one using it. But I would like to submit other jobs onto grid, but Canu ends up using all threads. 

So I was wondering if there is a command in the manual that I should use to limit the number of parallelized jobs from Canu. I have tried setting the `task concurrency` option to 5. Unfortunately that fails with following error: 

`Unable to run job: invalid "task concurrency" value in job request.
Exiting.`

My basic command: 

`/path/to/Canu_v2/bin/canu useGrid=true GridEngineResourceOption="-pe grid 6 -tc 5 -l mem_free=12G" -p assemble -d /path/to/assemble/analysis/ genomeSize=2G -pacbio-hifi /path/to/assemble/analysis/assemble.hifireads.fastq.gz `

Thank you for the help in advance.

**Comment by skoren** [comment]
You do want task concurrency, the option is `-tc` but I don't think SGE likes it if you specify it outside of array jobs. Don't modify the resource but the array jobs instead (like in this issue for slurm #2216), something like `gridEngineArrayOption="-t ARRAY_JOBS -tc 5"`.

**Comment by alvizain786** [comment]
Thank you! That worked like a charm! :)
