### ISSUE TITLE
Canu output files

### ISSUE THREAD

**Issue by ARW-UBT** [marbl/canu#2223]
Hello, 
I have used canu to correct the outcome of a MinION run of a cDNA library (transcriptome). 
canu -correct -p Pscaber -d Pscaber-corr genomeSize=30m -nanopore-raw guppy_reads.fastq.gz 

Is it true that the corrected reads were replaced in the original input file? Although the timestamp of the fastq.gz file has not changed, a subsequent canu job indicated that this file seems to have corrected reads ("Found untrimmed corrected Nanopore reads in the input files."). I had exected that corrected reads would be found somewhere in the -p output directory. 

I would appreciate your comments, and sorry if I missed some details in readthedocs
Best regards

**Comment by ARW-UBT** [comment]
I was expecting an output fasta file in the -d folder, but no such file has been created (I searched the entire subfolders). Has the parameter [processing] -corrected to be set?

**Comment by skoren** [comment]
What's the contents of the folder? Can you start a clean run with a new -d folder and post the full log from the canu command?

**Comment by ARW-UBT** [comment]
Yes, it was a temporary problem with our grid/file system... A new sbatch completed sucessfully and I got the fasta.gz output. 
Thank you for your assistance, and sorry that I overlooked the grid issue.
Best,
