### ISSUE TITLE
Combining HiFi reads with other technologies 

### ISSUE THREAD

**Issue by BaxW** [marbl/canu#2224]
I've had great success with Canu over the years (thank you!). A quick question:

I have PacBio HiFi data for some genomes I originally assembled with ONT reads, and it would be cool to try to assemble with both technologies together. Am I remembering correctly that this isn't a good idea with Canu, or has that changed?

**Comment by skoren** [comment]
No canu isn't designed to mix HiFi and ONT. If you want to do that, you can use verkko (https://github.com/marbl/verkko) which will build a HiFi graph and use ONT to simplify that.

**Comment by BaxW** [comment]
Awesome thanks!
