### ISSUE TITLE
Reproducibility between identical runs

### ISSUE THREAD

**Issue by dweemx** [marbl/canu#2226]
Hi, 

The contig generated in `test.contigs.fasta` between 2 runs of Canu is not the same i.e. not the same `md5` checksum. Why is that? How can I make sure the results are reproducible between mutliple runs of Canu given the same data and parameters are used?

Here is the command I'm using,

```
canu    \
   -assemble \
   -corrected  \
   -d canu \
   -p assembled  \
   genomeSize=4702  \
   maxThreads=8 \
   useGrid=false \
   -nanopore test.subsample.fasta
```

Version: `Canu 2.0`

I'm running the command on `Ubuntu 20.04.6 LTS`

**Comment by skoren** [comment]
The biggest source of changes we've observed is when the coverage is higher than the default allowed and reads are randomly downsampled. I assume here your coverage is below this threshold so it wouldn't matter? Other than that, Canu's consensus has some variability based on the order the reads are aligned so results may change but these should be very small differences. You can align the two assemblies to each other or a reference to confirm.

**Comment by dweemx** [comment]
I'm using 500 reads as input to Canu. All most all of the reads cover the entire reference sequence. So I'm not sure whether it's doing a downsampling?

Is there no way to set a seed so that results are reproducible?

**Comment by brianwalenz** [comment]
The program that downsamples the reads does support setting the seed, but the parameter isn't exposed in canu.  You can overload one of the canu options to also pass in a seed:
```
readSamplingBias="0 -seed 8"
```
This will pass the `-seed` parameter to the sqStoreCreate command; the command is executed via `canu/assembled.seqStore.sh` .

The other option is to set `maxInputCoverage=all` to disable downsampling (at some risk of an inferior assembly, and increased compute time).

The consensus variability can be controlled by disabling threads for that module: `cnsThreads=1`.

**Comment by dweemx** [comment]
I'll test that and report the results, thanks!

**Comment by dweemx** [comment]
@brianwalenz 

I tried to set the seed using:

```
readSamplingBias="0 -seed 8"
```

But it failed with:

```
 ABORT:   Found java:
  ABORT:      /usr/lib/jvm/java-11-openjdk-amd64/bin/java
  ABORT:      openjdk version "11.0.18" 2023-01-17
  ABORT:   
  ABORT:   Found canu:
  ABORT:      /app/canu/bin/canu
  ABORT:      Canu 2.0
  ABORT:   
  ABORT:   usage: /app/canu/bin/sqStoreCreate -o seqStore [-minlength L] [-genomesize G -coverage C] [-pacbio-raw NAME file1 ...]
  ABORT:     -o seqStore            load raw reads into new seqStore
  ABORT:     
  ABORT:     -minlength L           discard reads shorter than L
  ABORT:     
  ABORT:     -genomesize G          expected genome size, for keeping only the longest reads
  ABORT:     -coverage C            desired coverage in long reads
  ABORT:     
  ABORT:     Reads are supplied as a collection of libraries.  Each library should
  ABORT:     contain all the reads from one sequencing experiment (e.g., sample collection,
  ABORT:     sample preperation, sequencing run).
  ABORT:     
  ABORT:     The library is specified as a sequencing technology, a read processing status,
  ABORT:     and a unique library name.
  ABORT:       -technology-status LIBRARY_NAME seqFile1 [seqFile2] [...] 
  ABORT:     
  ABORT:     Valid combinations of technology and status are:
  ABORT:       -pacbio-raw
  ABORT:       -pacbio-corrected
  ABORT:       -pacbio-trimmed
  ABORT:       -pacbio-raw
  ABORT:       -nanopore-raw
  ABORT:       -nanopore-corrected
  ABORT:       -nanopore-trimmed
  ABORT:   
  ABORT:   Unknown option '-seed'.
  ABORT:   Unknown option '8'.
```

Then I tried: 

```
maxInputCoverage=all
```

together with:

```
cnsThreads=1
```
as suggested and this seems to do the job.
