### ISSUE TITLE
Total number of contigs from report different that the number in .contigs.fasta

### ISSUE THREAD

**Issue by ericgonzalezs** [marbl/canu#2227]
Hi,
           
I ran canu like this:

FASTQ1=$1
PREFIX=$2
DIRECTORY=$3
#Canu
canu \
 -p $PREFIX \
 -d $DIRECTORY \
 genomeSize=588m \
 useGrid=true \
 gridOptions="-A def -t 2-6" \
 gridEngineArrayOption="-a ARRAY_JOBS%999" \
 cnsMemory=80 \
 -pacbio-hifi $FASTQ1

On the report, I have this:

         [UNITIGGING/CONSENSUS]
         -- Found, in version 2, after consensus generation:
         --   contigs:      3717 sequences, total length 680273866 bp (including 548 repeats of total length 47132943 bp).
         --   bubbles:      2275 sequences, total length 124478653 bp.
         --   unassembled:  319005 sequences, total length 3195731570 bp. 
         --
         -- Contig sizes based on genome size 588mbp:  
         --
         --            NG (bp)  LG (contigs)    sum (bp)
         --         ----------  ------------  ----------
         --     10     1743298            23    60313949
         --     20     1178908            63   118095437
         --     30      947755           120   177280344
         --     40      724524           191   235322029
         --     50      558535           283   294030600
         --     60      418342           404   352849690
         --     70      317403           567   411770747
         --     80      241768           780   470631034
         --     90      160235          1074   529291370
         --    100      102037          1531   588016867
         --    110       45557          2379   646815200
         --

It says I have 3717 sequences and  a total length 680273866 bp, when I count the number of sequences on my contigs file like this: 

       grep ">" Genome_def.contigs.fasta | wc -l

I have 5992 sequences. Also when I count the total number of bases like this:

       grep -v ">" Genome_def.contigs.fasta | tr -d '\n' | wc -c

I have  804,752,519. Do you know why my numbers are different from the report?

In addition, I have hifi sequences, but the contigs are very small, also it is supposed to be an inbreed genome,  but the Kmer plot on genomescope looks like this:

![imagen](https://github.com/marbl/canu/assets/13828526/d3e90dbb-2961-4300-9f5a-056b8aa515d1)

And my busco score looks like this:
|Results from dataset stramenopiles_odb10         |
        --------------------------------------------------
        |C:77.0%[S:26.0%,D:51.0%],F:14.0%,M:9.0%,n:100    |
        |77     Complete BUSCOs (C)                       |
        |26     Complete and single-copy BUSCOs (S)       |
        |51     Complete and duplicated BUSCOs (D)        |
        |14     Fragmented BUSCOs (F)                     |
        |9      Missing BUSCOs (M)                        |
        |100    Total BUSCO groups searched   

I think that from the kmer plot and the busco score, the sample looks heterozygous and is not inbred. The short contigs make me think it could be contaminated. I am wondering if you could please give me your opinion about this.

Many thanks,

Eric

**Comment by skoren** [comment]
The contig reports lists bubbles and contigs separately. There are 3717 contigs and 2275 bubbles. Together that's the 5992 sequences you see. Based on the duplication, it looks like you probably have both haplotypes. You can use purge_dups or a similar tool to remove the redundant nodes from your assembly (https://canu.readthedocs.io/en/latest/faq.html#my-genome-size-and-assembly-size-are-different-help). 

The genome size from genome scope is even smaller, at 300 mbp, which would mean the assembly is almost 3x larger. Are you sure the genome is not closer to 400 mbp, if you're not already, I'd use genome scope 2.0 which is more accurate at estimating the genome size.

**Comment by ericgonzalezs** [comment]
Many thanks. Could you please tell me your thoughts about the contig size of a few hundred kb. I was expecting Mb contigs. Is it normal to have a few hundred kb contigs with more than 40X hifi data?

**Comment by skoren** [comment]
Well if the genome is actually 300mb then using the genome size of 600mb is not going to give an accurate picture of continuity. The alt haplotype will always be shorter than the primary since the primary steals homozygous nodes from it. It's also hard to say what the stats should be given no information on how long the HiFi reads are, if there are any issues with data quality, or how many chromosomes there are here which necessarily limits continuity.

**Comment by ericgonzalezs** [comment]
The HiFi reads have a median Q35 and it is supposed that we have 43X (if the genome is really 588 MB). The reads are relatively small, there are between 5kb and 10 kb. We were expecting reads with a mean of around 15kb. The individual has many chromosomes ~30.

**Comment by ericgonzalezs** [comment]
Many thanks, I'll try the other parameters.
