### ISSUE TITLE
Don't panic, but a mostly harmless error occurred and Canu stopped.

### ISSUE THREAD

**Issue by ali-qaafi** [marbl/canu#2228]
Hi, I am using canu for genome assembly, and I am receiving the following error in the canu.out file:

```
 'BEGIN ASSEMBLY'
--
-- Overlap jobs failed, tried 2 times, giving up.
--   job unitigging/1-overlapper/001/000011.ovb FAILED.
--   job unitigging/1-overlapper/001/000014.ovb FAILED.
--   job unitigging/1-overlapper/001/000015.ovb FAILED.
--   job unitigging/1-overlapper/001/000016.ovb FAILED.
--   job unitigging/1-overlapper/001/000017.ovb FAILED.
--   job unitigging/1-overlapper/001/000018.ovb FAILED.
--   job unitigging/1-overlapper/001/000019.ovb FAILED.
--   job unitigging/1-overlapper/001/000020.ovb FAILED.
--   job unitigging/1-overlapper/001/000021.ovb FAILED.
--   job unitigging/1-overlapper/001/000022.ovb FAILED.
--   job unitigging/1-overlapper/001/000023.ovb FAILED.
--   job unitigging/1-overlapper/001/000024.ovb FAILED.
--   job unitigging/1-overlapper/001/000025.ovb FAILED.
--   job unitigging/1-overlapper/001/000026.ovb FAILED.

and it continues until /000376, followed by this message:
ABORT:
ABORT: canu 2.2
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:

I am using the following command in the Linux:

#!/bin/bash
#SBATCH -N 1
#SBATCH --job-name=canu_assembly
#SBATCH --partition=general
#SBATCH -o assembly_canu_out.txt
#SBATCH -e assembly_canu_error.txt
#SBATCH --ntasks=6
#SBATCH --cpus-per-task=24
#SBATCH --mem=650gb
#SBATCH --time=165:00:00
#SBATCH --account=a_tabor

# Add the conda binary directory to the system path
source ~/.bashrc
export PATH="/home/uqaraza/Softwares/Anaconda3/bin:$PATH"

# Activate the conda environment
conda activate canu  # Replace my_env with the name of your Canu environment
# Move to the working directory
cd /scratch/project_mnt/S0099/Ali/Filtered_BF_data/

# Run Canu
canu \
  -p BF_assembly_canu \
  -d assembly_dir_canu \
  genomeSize=1.9g \
  -maxThreads=24 \
  -maxMemory=650g \
  -trimmed -nanopore Sample_AB_Merged_NanoFilt_5kb.fastq
```

Previously, I tried the same command with 450gb memory, and ntasks=1, and the same error happened.

Thanks in advance for any help.

**Comment by ali-qaafi** [comment]
Thanks, Skoren, I have already corrected and trimmed the ONT data. Yes, there are some files int he canu-log dir.

total 4
drwxr-sr-x. 2 uqaraza S_TABOR 4096 Jun  9 01:40 ./
drwxr-sr-x. 6 uqaraza S_TABOR 4096 Jun  9 01:40 ../
-rw-r--r--. 1 uqaraza S_TABOR  285 Jun  8 12:37 1686191872_bun030_4155902_canu
-rw-r--r--. 1 uqaraza S_TABOR  301 Jun  8 13:05 1686193557_bun049_3881649_canu
-rw-r--r--. 1 uqaraza S_TABOR  301 Jun  8 13:11 1686193861_bun049_3888730_canu
-rw-r--r--. 1 uqaraza S_TABOR  301 Jun  8 19:25 1686216350_bun053_2537333_canu
-rw-r--r--. 1 uqaraza S_TABOR  301 Jun  9 01:40 1686238807_bun049_125325_canu

**Comment by skoren** [comment]
How were the reads corrected/trimmed? By the logs I meant the full output from the canu runs you have done so far.

**Comment by ali-qaafi** [comment]
Hi Skoren, the following files/dir were generated. WHich one you want to see?
16K -rw-r--r--. 1 uqaraza S_TABOR  14K Jun  8 13:11 BF_assembly_canu.report
512 drwxr-sr-x. 3 uqaraza S_TABOR 4.0K Jun  8 12:49 BF_assembly_canu.seqStore
512 -rw-r--r--. 1 uqaraza S_TABOR  845 Jun  8 12:49 BF_assembly_canu.seqStore.err
512 -rwxr-xr-x. 1 uqaraza S_TABOR 1.2K Jun  8 12:37 BF_assembly_canu.seqStore.sh
512 drwxr-sr-x. 2 uqaraza S_TABOR 4.0K Jun  9 01:40 canu-logs
512 lrwxrwxrwx. 1 uqaraza S_TABOR   24 Jun  9 01:40 canu.out -> canu-scripts/canu.04.out
512 drwxr-sr-x. 2 uqaraza S_TABOR 4.0K Jun  9 01:40 canu-scripts
512 drwxr-sr-x. 4 uqaraza S_TABOR 4.0K Jun  8 13:11 unitigging

**Comment by skoren** [comment]
The report would be good but I also meant the output to stdout/stderr from the canu run. If you have the report files from the correction/trim runs those would be good as well.

**Comment by ali-qaafi** [comment]
Hi Skoren, previously, I used Guppy for base calling, which I believe also does the read correction and adaptor removal. Then I used NanoPack for filtration. Here is the report file from the Canu run.
Please let me know if you need some more information.

Cheers,
Ali

**Comment by ali-qaafi** [comment]
Hi Skoren, previously, I used Guppy for base calling, which I believe also does the read correction and adaptor removal. Then I used NanoPack for filtration. Here is the Canu report 
[TRIMMING/READS]
--
-- In sequence store './BF_assembly_canu.seqStore':
--   Found 5065443 reads.
--   Found 52272889450 bases (27.51 times coverage).
--    Histogram of corrected reads:
--
--    G=52272889450                      sum of  ||               length     num
--    NG         length     index       lengths  ||                range    seqs
--    ----- ------------ --------- ------------  ||  ------------------- -------
--    00010        26922    147652   5227307622  ||       5000-16803     4474904|---------------------------------------------------------------
--    00020        19905    376700  10454582508  ||      16804-28607      471148|-------
--    00030        15957    671785  15681870048  ||      28608-40411       89898|--
--    00040        13216   1032960  20909167809  ||      40412-52215       21414|-
--    00050        11126   1465063  26136447899  ||      52216-64019        5685|-
--    00060         9453   1975634  31363741201  ||      64020-75823        1593|-
--    00070         8064   2575081  36591024015  ||      75824-87627         491|-
--    00080         6885   3277296  41818314009  ||      87628-99431         182|-
--    00090         5873   4100071  47045605475  ||      99432-111235         56|-
--    00100         5000   5065442  52272889450  ||     111236-123039         32|-
--    001.000x             5065443  52272889450  ||     123040-134843         10|-
--                                               ||     134844-146647         10|-
--                                               ||     146648-158451          5|-
--                                               ||     158452-170255          1|-
--                                               ||     170256-182059          2|-
--                                               ||     182060-193863          2|-
--                                               ||     193864-205667          1|-
--                                               ||     205668-217471          1|-
--                                               ||     217472-229275          0|
--                                               ||     229276-241079          1|-
--                                               ||     241080-252883          1|-
--                                               ||     252884-264687          1|-
--                                               ||     264688-276491          0|
--                                               ||     276492-288295          0|
--                                               ||     288296-300099          1|-
--                                               ||     300100-311903          1|-
--                                               ||     311904-323707          0|
--                                               ||     323708-335511          0|
--                                               ||     335512-347315          0|
--                                               ||     347316-359119          0|
--                                               ||     359120-370923          0|
--                                               ||     370924-382727          0|
--                                               ||     382728-394531          0|
--                                               ||     394532-406335          0|
--                                               ||     406336-418139          0|
--                                               ||     418140-429943          0|
--                                               ||     429944-441747          1|-
--                                               ||     441748-453551          0|
--                                               ||     453552-465355          0|
--                                               ||     465356-477159          0|
--                                               ||     477160-488963          0|
--                                               ||     488964-500767          0|
--                                               ||     500768-512571          0|
--                                               ||     512572-524375          0|
--                                               ||     524376-536179          0|
--                                               ||     536180-547983          0|
--                                               ||     547984-559787          0|
--                                               ||     559788-571591          0|
--                                               ||     571592-583395          1|-
--                                               ||     583396-595199          1|-
--

[UNITIGGING/READS]
--
-- In sequence store './BF_assembly_canu.seqStore':
--   Found 5065443 reads.
--   Found 52272889450 bases (27.51 times coverage).
--    Histogram of corrected-trimmed reads:
--
--    G=52272889450                      sum of  ||               length     num
--    NG         length     index       lengths  ||                range    seqs
--    ----- ------------ --------- ------------  ||  ------------------- -------
--    00010        26922    147652   5227307622  ||       5000-16803     4474904|---------------------------------------------------------------
--    00020        19905    376700  10454582508  ||      16804-28607      471148|-------
--    00030        15957    671785  15681870048  ||      28608-40411       89898|--
--    00040        13216   1032960  20909167809  ||      40412-52215       21414|-
--    00050        11126   1465063  26136447899  ||      52216-64019        5685|-
--    00060         9453   1975634  31363741201  ||      64020-75823        1593|-
--    00070         8064   2575081  36591024015  ||      75824-87627         491|-
--    00080         6885   3277296  41818314009  ||      87628-99431         182|-
--    00090         5873   4100071  47045605475  ||      99432-111235         56|-
--    00100         5000   5065442  52272889450  ||     111236-123039         32|-
--    001.000x             5065443  52272889450  ||     123040-134843         10|-
--                                               ||     134844-146647         10|-
--                                               ||     146648-158451          5|-
--                                               ||     158452-170255          1|-
--                                               ||     170256-182059          2|-
--                                               ||     182060-193863          2|-
--                                               ||     193864-205667          1|-
--                                               ||     205668-217471          1|-
--                                               ||     217472-229275          0|
--                                               ||     229276-241079          1|-
--                                               ||     241080-252883          1|-
--                                               ||     252884-264687          1|-
--                                               ||     264688-276491          0|
--                                               ||     276492-288295          0|
--                                               ||     288296-300099          1|-
--                                               ||     300100-311903          1|-
--                                               ||     311904-323707          0|
--                                               ||     323708-335511          0|
--                                               ||     335512-347315          0|
--                                               ||     347316-359119          0|
--                                               ||     359120-370923          0|
--                                               ||     370924-382727          0|
--                                               ||     382728-394531          0|
--                                               ||     394532-406335          0|
--                                               ||     406336-418139          0|
--                                               ||     418140-429943          0|
--                                               ||     429944-441747          1|-
--                                               ||     441748-453551          0|
--                                               ||     453552-465355          0|
--                                               ||     465356-477159          0|
--                                               ||     477160-488963          0|
--                                               ||     488964-500767          0|
--                                               ||     500768-512571          0|
--                                               ||     512572-524375          0|
--                                               ||     524376-536179          0|
--                                               ||     536180-547983          0|
--                                               ||     547984-559787          0|
--                                               ||     559788-571591          0|
--                                               ||     571592-583395          1|-
--                                               ||     583396-595199          1|-
--

[UNITIGGING/MERS]
--
--  22-mers                                                                                           Fraction
--    Occurrences   NumMers                                                                         Unique Total
--       1-     1         0                                                                        0.0000 0.0000
--       2-     2 806048328 ********************************************************************** 0.3742 0.0372
--       3-     4 419582529 ************************************                                   0.5033 0.0564
--       5-     7 197094045 *****************                                                      0.6099 0.0796
--       8-    11 124719684 **********                                                             0.6784 0.1029
--      12-    16 101948196 ********                                                               0.7292 0.1290
--      17-    22 108932465 *********                                                              0.7742 0.1624
--      23-    29 127404056 ***********                                                            0.8250 0.2141
--      30-    37 114682968 *********                                                              0.8834 0.2922
--      38-    46  67967771 *****                                                                  0.9337 0.3778
--      47-    56  25775530 **                                                                     0.9623 0.4377
--      57-    67  11611270 *                                                                      0.9729 0.4650
--      68-    79   8274507                                                                        0.9781 0.4810
--      80-    92   6274105                                                                        0.9818 0.4947
--      93-   106   4870566                                                                        0.9846 0.5069
--     107-   121   3915600                                                                        0.9868 0.5179
--     122-   137   3186763                                                                        0.9886 0.5281
--     138-   154   2626101                                                                        0.9901 0.5375
--     155-   172   2203670                                                                        0.9913 0.5462
--     173-   191   1861932                                                                        0.9923 0.5545
--     192-   211   1578476                                                                        0.9932 0.5622
--     212-   232   1348321                                                                        0.9939 0.5695
--     233-   254   1152166                                                                        0.9945 0.5764
--     255-   277    995503                                                                        0.9950 0.5828
--     278-   301    860779                                                                        0.9955 0.5889
--     302-   326    750932                                                                        0.9959 0.5946
--     327-   352    657191                                                                        0.9962 0.6000
--     353-   379    581193                                                                        0.9965 0.6051
--     380-   407    517873                                                                        0.9968 0.6100
--     408-   436    463305                                                                        0.9970 0.6147
--     437-   466    413398                                                                        0.9973 0.6192
--     467-   497    369194                                                                        0.9974 0.6235
--     498-   529    332626                                                                        0.9976 0.6275
--     530-   562    301525                                                                        0.9978 0.6315
--     563-   596    273473                                                                        0.9979 0.6353
--     597-   631    249912                                                                        0.9980 0.6389
--     632-   667    228034                                                                        0.9982 0.6424
--     668-   704    210296                                                                        0.9983 0.6458
--     705-   742    192874                                                                        0.9984 0.6492
--     743-   781    177406                                                                        0.9984 0.6524
--     782-   821    163635                                                                        0.9985 0.6555
--
--           0 (max occurrences)
-- 43367067137 (total mers, non-unique)
--  2153811987 (distinct mers, non-unique)
--           0 (unique mers)

**Comment by skoren** [comment]
Guppy is just a base caller and does not perform any correction. The reads seem relatively high accuracy but likely not accurate enough to assemble without any correction. I suspect this is what happened. Could you post the logs from some of the failed jobs (e.g. `assembly_dir_canu/unitigging/1-overlapper/* 000011*err`)?

Given the accuracy of the reads, you could try the parameters for highly-accurate ONT reads using the --pacbio-hifi option (https://canu.readthedocs.io/en/latest/quick-start.html#correct-trim-and-assemble-manually).

**Comment by skoren** [comment]
Idle, initial issue was due to trying to assemble raw ONT data w/o correction or trimming.
