### ISSUE TITLE
Canu error

### ISSUE THREAD

**Issue by RacheliHadjez** [marbl/canu#2229]
Hello,
I am trying to run canu on linux and it ends very quickly ("lickety-split"). I want to assemble a 60m sized genome.
This is my command:
#!/bin/bash
#PBS -q huchond
#PBS -o out_canu_HSA2_DNA
#PBS -e err_canu_HSA2_DNA
#PBS -l select=1:ncpus=50
#PBS -m ae
#PBS -r y

module load canu/canu-2.2

canu -p 'HSA_DNA_1' -d '/dorotheeh/hadjez/Canu_HSA2_DNA' genomeSize=100M gridOptions="-q huchond" merylThreads=50 -pacbio-hifi /dorotheeh/hadjez/FilteredResults_Q20.fastq

This is the error that I'm getting:

-- Starting command on Mon Jun 12 12:31:56 2023 with 4181.468 GB free disk space

    cd /dorotheeh/hadjez/Canu_HSA2_DNA
    qsub \
      -j oe \
      -W depend=afterany:8660219[].power9.tau.ac.il \
      -l select=1:ncpus=1:mem=4g \
      -q huchond  \
      -N 'canu_HSA_DNA_1' \
      -o canu-scripts/canu.01.out  canu-scripts/canu.01.sh

-- Finished on Mon Jun 12 12:31:56 2023 (lickety-split) with 4181.468 GB free disk space

[Canuerror2.txt](https://github.com/marbl/canu/files/11721024/Canuerror2.txt)

I'm very new to linux so I don't understand why it stops so quickly.

Thank you!!

**Comment by skoren** [comment]
Idle, no error reported.
