### ISSUE TITLE
Error in compiling canu version 2.2 under archlinux

### ISSUE THREAD

**Issue by kbipinkumar** [marbl/canu#2231]
i am attempting to compile latest release canu from source tarball as per instruction given in README. however i am encountering following error
```bash 
$ cd canu/src
$ make
fatal: not a git repository (or any of the parent directories): .git

fatal: not a git repository (or any of the parent directories): .git

fatal: not a git repository (or any of the parent directories): .git

Failed to open 'utility/src/utility/version.H.new' for writing: No such file or directory
Building release v2.2
For 'Linux' '6.3.8-arch1-1' as 'amd64' into '/build/canu/src/canu-2.2/build/{bin,obj}'.
Using '/usr/bin/g++' version '13.1.1'.
Using user-supplied CXXFLAGS '-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS'.

Makefile:668: meryl/src/meryl/meryl.mk: No such file or directory
make: *** No rule to make target 'meryl/src/meryl/meryl.mk'.  Stop.
```

i am assuming this is probably due to folders corresponding to `meryl`, `utility`, `seqrequester` being empty. any idea why these are not included in release tarball?

**Comment by brianwalenz** [comment]
If this is the `Source code (tar.gz)` download listed on the releases page, that is known not to work.  Use [canu-2.2.tar.xz](https://github.com/marbl/canu/releases/download/v2.2/canu-2.2.tar.xz) instead.

**Comment by kbipinkumar** [comment]
> If this is the `Source code (tar.gz)` download listed on the releases page, that is known not to work.  Use [canu-2.2.tar.xz](https://github.com/marbl/canu/releases/download/v2.2/canu-2.2.tar.xz) instead.

This worked. Thanks for the suggestion.
