### ISSUE TITLE
Using Singleton Reads from Unassembled.fasta

### ISSUE THREAD

**Issue by iek** [marbl/canu#2235]
Hi Sergey,

Thank you so much for this tool. I have used PCR primers that tile across the whole genome of a virus. Unfortunately, one of the primers hitting a key gene spanning 1400 base pairs is not working very well and has much lower coverage compared to the rest of the genome. As a result, I mapped all of the reads to the viral genome and only extracted those mapping to the key 1400bp gene and then used Canu to assemble. I have altered the Canu parameters to start assembling some of the key gene even with relatively lower coverage, but there is a good chunk of it still missing in the contigs.fasta file. 

The unassembled.fasta file, however, has a good number of reads spanning across the whole gene that are all composed to single reads (numChildren=1). Is there any way that I can use the reads from this unassembled.fasta file as contigs? After all, many of my original raw reads were filtered out by Canu, so theoretically only the good-quality reads are remaining in the unassembled.fasta file. 

Here is the IGV plot with the first set of reads showing "Unassembled.fasta" and the second set of reads showing "Contigs.fasta". Note that Unassembled.fasta has plenty of reads at the end of the gene where Contigs.fasta does not. All reads in Unassembled.fasta are supported by single reads (numChildren=1), while the one contig in Contigs.fasta has 35 children/reads supporting it.

<img width="1027" alt="Screen Shot 2023-06-27 at 9 21 17 PM" src="https://github.com/marbl/canu/assets/12649783/ed3845d7-f6a9-4538-a288-591fe06a7937">

Digging into it a little further, I wasn't sure if the lack of assembly was because the vast majority of the corrected reads might be contained within a larger corrected read? This is what the report said (I have sent you the full report as well on ftp as 
promethion_barcode02_v7.report):

<img width="600" alt="Screen Shot 2023-06-27 at 9 32 58 PM" src="https://github.com/marbl/canu/assets/12649783/4f1a069d-2687-45bf-8a84-5f5fe48827a8">

I am running Canu with the following parameters:

`maxInputCoverage=1000000000000 corMhapSensitivity=high corMinCoverage=0 redMemory=100 oeaMemory=32 batMemory=200 genomeSize=1472 corOutCoverage=1000000000000  minReadLength=10 minOverlapLength=5 trimReadsOverlap=5 correctedErrorRate=1 minInputCoverage=0 stopOnLowCoverage=0 trimReadsCoverage=1 obtOvlErrorRate=1 obtErrorRate=1 -nanopore`

Thank you so much for your time and help.

**Comment by skoren** [comment]
Those parameters are a bit odd, the error rates are a fraction so setting it to 1 means 100% error (which is impossible anyway). Most of your reads have no overlaps and/or have coverage gaps and no support which implies they are incorrect. Allowing trimming to remove and/or fix these rather than setting a super-high error rate would be better. 

I would suggest removing all parameters after `minOverlapLength=5` (so remove `trimReadsOverlap=5 correctedErrorRate=1 minInputCoverage=0 stopOnLowCoverage=0 trimReadsCoverage=1 obtOvlErrorRate=1 obtErrorRate=1`) and only use `correctedErrorRate=0.10`.

**Comment by iek** [comment]
Thank you so much, Sergey! I really appreciate your quick response. I tried that, and while it worked better, there was still part of the gene that didn't get assembled in contigs.fasta but was found in unassembled.fasta . Would you recommend using any contigs from unassembled.fasta?

**Comment by skoren** [comment]
The unassembled are essentially corrected reads in your case. So they would have a slightly lower identity but still usable.  There seems to be 1 very large but bad read (first line in unassigned) that contains everything else that could have extended the assembly but has a bunch of differences itself. You could try increasing the trimming coverage from the default of 2 (trimReadCoverage=3 or 5). You could also get rid of some of the longest reads if they're more erroneous (like the one above) and see if that improves the assembly too.

**Comment by iek** [comment]
Thank you so much! This was incredibly helpful.
