### ISSUE TITLE
Canu gives too much sequences back

### ISSUE THREAD

**Issue by RacheliHadjez** [marbl/canu#2237]
Hi,
I have PacBio reads of an organism called Henneguya salminicola. I am using Canu to assemble its genome which is ~70 m.
This is my command:

module load canu/canu-2.2

canu \
 -p HSA_DNA_1 -d /dorotheeh/hadjez/Canu_HSA_DNA \
 genomeSize=80m \ 
 gridOptions="-q huchond" \ 
 merylThreads=1 \
 useGrid=false \ 
 -pacbio-hifi /dorotheeh/hadjez/FilteredResults_Q20.fastq \

After it finished the assembly, I looked at the contigs and I am getting 1500 sequences which is strange since in other programs I tried to assemble with I get about ~150 sequences.  
I'm using Linux. 
I'm attaching the error file:
[Canu_error.txt](https://github.com/marbl/canu/files/11934036/Canu_error.txt)

Do you have any idea what could be the problem? 
I tried to run it also with genomeSize=70m and it also gave about 1400 sequences.

Thank you in advance!

**Comment by skoren** [comment]
I don't see anything off in the canu logs, though the coverage is higher than we typically use for HiFi. We recommend about 50x which you can specify with maxInputCoverage=50 (the default, I am not sure why it didn't use this automatically). I doubt that would make much difference here though.

There are about 500 contigs that add up to 280mb and about 220mb in bubbles which is typically the second haplotype. The largest 100 contigs (over 100mb) add up to almost 200mb alone. This would imply the genome is somewhere around 250 mbp in size not 80. Have you tried running genomescope of the read histogram to confirm the genome size is accurate? You could also try running purge_dupes to remove the secondary haplotype and retain just a primary assembly and see if that is consistent with the genome size estimate.

**Comment by RacheliHadjez** [comment]
Hi!
Thank you for replying.
We did check the genome size and we are sure the size is supposed to be around 70 mbp (also this genome was assembled before with Illumina and it was about 60-70 mbp).
We did see that the coverage is 200, so I tried to run canu again with maxInputCoverage=200, it gave me even more sequences back (~1500). 
If my coverage is 200, maybe maxInputCoverage=200 is not the correct parameter that I should have used? Do you have maybe another idea of what could be the problem?

This is my command:
module load canu/canu-2.2

canu \
 -p HSA_DNA_1 -d /dorotheeh/hadjez/Canu_HSA_DNA \
 genomeSize=70m \ 
 gridOptions="-q huchond" \ 
 merylThreads=50 \
 maxInputCoverage=200 \
 useGrid=false \
 -pacbio-hifi /dorotheeh/hadjez/FilteredResults_Q20.fastq \

I'm also attaching the error file.
[CANUerror.txt](https://github.com/marbl/canu/files/12092169/CANUerror.txt)

Thank you very much!!!

**Comment by skoren** [comment]
Idle
