### ISSUE TITLE
Overlap length in trimming

### ISSUE THREAD

**Issue by sarahchill91** [marbl/canu#2238]
Hi,

I'm trying to assemble of some nanopore data, which includes some short reads from virus that are about 500bp. At the moment, many of my reads are shorter than the default overlap length, and I appear to be losing a lot of reads at the trimming step that are relevant. I am therefore trying to reduce the overlap size parameter using minOverlapLength=400 to try and reduce the amount of trimming that occurs on reads from these short fragments. 

From my understanding, the minOverlapLength parameter should be inherited by all steps in the pipeline. When I change this parameter to minOverlapLength=400, the minOverlapLength value appears to be inherited by the trimming in the step trimming/1-overlapper (i.e., -ol parameter changes to the set value of 400 in the log as follows).

    cd trimming/1-overlapper
    /home/xxx/canu-2.2/build/bin/overlapInCorePartition \
     -S  ../../test.seqStore \
     -hl 80000000 \
     -rl 1000000000 \
     -ol 400 \
     -o  ./test.partition \
    > ./test.partition.err 2>&1

 However, it doesn't appear to be inherited in the step trimming/3-overlapbasedtrimming (i.e., -ol parameter remains at the default 500 in the log file, as below).

      cd trimming/3-overlapbasedtrimming
    /home/xxx/canu-2.2/build/bin/trimReads \
      -S  ../../test.seqStore \
      -O  ../test.ovlStore \
      -Co ./test.1.trimReads.clear \
      -e  0.12 \
      -minlength 500 \
      -ol 500 \
      -oc 0 \
      -o  ./test.1.trimReads \
    >     ./test.1.trimReads.err 2>&1

Do I need to change something additional here to force the overlap length to be reduced? I know it's a bit experimental to use canu on such short read data, but it's working well for me on longer viruses and I'd really like to give it a try. 

Thanks for your help,
Sarah

**Comment by skoren** [comment]
The parameters used here are different because it's not quite the same type of overlap. It is looking at the minimum overlap between adjacent reads to merge their regions and allow them to "support" the read being trimmed. Using `trimReadsOverlap` (the -ol) and the `trimReadsCoverage` (the -oc) should work.

**Comment by sarahchill91** [comment]
Great, thankyou for the explanation! It's now working for me with the addition of a trimReadsOverlap parameter.
