### ISSUE TITLE
 Read error detection jobs failed

### ISSUE THREAD

**Issue by cssanchez23** [marbl/canu#2244]
command used `canu -pacbio-corrected hifi_reads.fastq.gz genomeSize=3.5m -d canu_wrk -p project gnuplotTested=true maxMemory=32`

using version

linux `Canu 1.6`

The error message looks like the following 
"""`----------------------------------------
--
-- Read error detection jobs failed, tried 2 times, giving up.
--   job 00000.red FAILED.
--   job 00000.red FAILED.
--

ABORT:
ABORT: Canu 1.6
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
`
"""

**Comment by skoren** [comment]
Version 1.6 is over 6 years old and not supported nor does it support HiFi data. You can try installing v2.2 and re-start the assembly from scratch and see if you have an error with that version.
