### ISSUE TITLE
Error in cormhap stage

### ISSUE THREAD

**Issue by ld9866** [marbl/canu#2245]
Dear developer:
I am trying to assemble a genome of livestock and poultry using canu. Our operating memory is 500G with 64 cores. Errors occur at different stages in many attempts. The error in cormhap is something that we have tried many times but could not complete. I would like to ask you how to solve it.
shell: canu useGrid=false maxThreads=64 maxMemory=500g -p Canu.correct -d Canu genomeSize=2.5g \
-nanopore /storage/example.fq.gz
Thank you!

[log.txt](https://github.com/marbl/canu/files/12075203/log.txt)

**Comment by skoren** [comment]
Idle
