### ISSUE TITLE
Cannot run multiple Canu instances from the same .sh script!

### ISSUE THREAD

**Issue by Hollowed-Mind** [marbl/canu#2246]
When I try to run Canu from a .sh ran in a linux terminal, Canu claims to only be able to find the file listed in the last line. If you uncomment out a previous line and then comment out all lines below that one, that line will run fine. I've triple check the syntax of all my commands and my .sh code. I can't find any problem. No matter what I do, Canu will only run the last request in the .sh file.

I've attached screenshots of my file folder to prove the files are there, as well as my code (in a zip) to this issue. Anyone have any idea what is going on here?
![screenshot_of_Data_folder](https://github.com/marbl/canu/assets/137957162/13dc5d46-32b3-4a7f-9fd3-3ebbafbd9f1e)
[queue_code.zip](https://github.com/marbl/canu/files/12149568/queue_code.zip)
[Canu Run.txt](https://github.com/marbl/canu/files/12152271/Canu.Run.txt)

**Comment by skoren** [comment]
I don't follow what you mean or the error. Can you post the actual logs from launching the commands?

**Comment by Hollowed-Mind** [comment]
> I don't follow what you mean or the error since Canu doesn't maintain any state between different runs. Can you post the actual logs from launching the commands?

Sorry. Forgot to post that. I'll post it in just a second. Thanks.

**Comment by Hollowed-Mind** [comment]
> I don't follow what you mean or the error since Canu doesn't maintain any state between different runs. Can you post the actual logs from launching the commands?

I just posted a .txt file of the entire terminal output. Let me know if you need anything else!

**Comment by skoren** [comment]
As I suspected, this isn't related to Canu. Your scripts, at least the `first_queue_test.sh` is corrupted. If you printed the variable values it is using, they look like this:
```
'rec_set_0_seq_0_80x_corrected'
'rec_set_0_seq_0'
'Data/records_set_0_SeqID_0.fastq
'
```
which. matches what canu is complaining about:
```
' not found. read file 'Data/records_set_0_SeqID_0.fastq
'.  Did you forget quotes around options with spaces?_0_SeqID_0.fastq

```

If I run dos2unix on the scripts, then they report the correct files and everything runs as expected.
