### ISSUE TITLE
Trio binning - 1 mother 2 possible fathers 

### ISSUE THREAD

**Issue by carolhsb** [marbl/canu#2247]
Hi,

I´m using the Trio Binning strategy on a hybrid fish species. I know the ID of the mother, but I have two possible fathers.

I´m thinking of mixing the two fathers' DNA for short-reads extraction. Do you think this strategy can cause problems in separating the hybrid haplotypes?

Can you give me any tips or suggestions on how I should handle this problem?

Many thanks,

Carolina

**Comment by skoren** [comment]
Can you sequence both potential fathers separately? You can then try building the k-mer databases for the parents with Merqury (https://github.com/marbl/merqury) which should tell you which is the correct father based on the inherited hapmers. You can then use the correct father for the trio assembly.

**Comment by carolhsb** [comment]
Dear Koren,

Unfortunately, we are currently unable to sequence both fathers due to insufficient funds. As a result, I have randomly selected one father to sequence, and I will use Mercury to validate whether it is the correct one. If it is not, we will have to wait until we have enough funds to sequence the other father. Thank you for your suggestion.

Best,
Carolina
