### ISSUE TITLE
Can I remove asm.ovlStore in correction fold when asm.correctedReads.fasta.gz has been generate ?

### ISSUE THREAD

**Issue by kedduck** [marbl/canu#2248]
Thanks for your great software.

I am sorry to disturb you for a simple question.

I am using CANU to saaembly a plant genome which is ~3Gb. Now the progross is in trimming,  the correction may be finished (I see the asm.correctedReads.fasta.gz). Could I remove  'asm.ovlStore' in correction fold? It is ~45T. 

I read the tutorial  "if you have asm.trimmedReads.fasta.gz, you can remove trimming/asm.ovlStore". It not mention correction.

Thanks!

**Comment by brianwalenz** [comment]
Yes.

If needed, you can reuse these corrected reads in a later assembly (for example, with adjusted parameters) with `canu -[pacbio/nanopore] -corrected asm.correctedReads.fasta.gz`.  The same idea applies to trimmed reads.

**Comment by kedduck** [comment]
Thanks for your reply!
