### ISSUE TITLE
correction.html file does not show the plots

### ISSUE THREAD

**Issue by ugh-astya** [marbl/canu#2249]
Im trying to correct some short read nanopore data. As mentioned, the reports generated do not show the graphs. The correction folder contains the .svg files but when I open them, they just show the gnuplot code (i'm assuming).
One thing to note, I am accessing my data and running commands on a grid (SGE). I use jupyter noteboooks (in browser) to open .html files as my server does not have display forwarding enabled.
Attaching a photo for reference.
![Screenshot from 2023-08-04 18-13-14](https://github.com/marbl/canu/assets/122881171/4cde52d3-917d-48c1-8824-a968d992c011)

Command used: 
`canu -correct -p correct -d ../corrected/barcode01 genomeSize=8k useGrid=false -nanopore-raw *barcode01*.fastq.gz minReadLength=200 minOverlapLength=200`
Canu release v1.5
The server runs redhat OS

**Comment by skoren** [comment]
I suspect there was an issue with the gnuplot program canu found while running, can you post one of the SVG files here? 

That said, we've deprecated these plots in later releases so I wouldn't rely on them. I also would strongly discourage use of v1.5 for any assemblies since it's so old.

**Comment by ugh-astya** [comment]
I see. Here is one svg file:
![correct expectedLength-vs-correctedLength lg](https://github.com/marbl/canu/assets/122881171/3396a77d-4e3f-4b37-b3e2-6c70e12be0fb)

In the later releases, do you still have the plots using a different plotting software, or have you removed the plots altogether?

**Comment by skoren** [comment]
Idle, addressed, the HTML reports are deprecated by the same data is available in ASCII-form.
