### ISSUE TITLE
overlap store bucketizer jobs failed

### ISSUE THREAD

**Issue by ishengtsai** [marbl/canu#225]
Hi,

We've been running canu on a series of small genomes (10-120Mb) on LSF environment with no problem at all. But recently canu failed at 'overlap store bucketizer job' stage on a 740Mb with approximately 30X coverage. Could anyone suggest what we can do to solve the problem?

# Command used (bsubbed) :
/home/r07ijt00/bin/canu/Linux-amd64/bin/canu java=/pkg/java/jdk1.8.0_77/bin/java -p Bspecies -d Bspec-31X corMinCoverage=0 errorRate=0.035  genomeSize=740m -pacbio-raw data.fasta

Error log:

![image](https://cloud.githubusercontent.com/assets/5182142/17580122/88f1ce78-5fce-11e6-9de5-bae62b0f4242.png)

**Comment by brianwalenz** [comment]
In Bspecies.ovlStore.BUILDING/logs there should be many logs for these commands.  What error is reported?  I suspect they will all have the same error, but it would be good to check a several files.

Were any directories/files created in Bspecies.ovlStore.BUILDING (other than scripts/ and logs/)?

**Comment by ishengtsai** [comment]
Ah , it's the typical TERM_MEMLIMIT (please see below). Is it possible to specify which queue to submit in lsf?

Best,
Jason



------------------------------------------------------------
# LSBATCH: User input
/work/r07ijt00/Pacbio/canu/Bspecies31cells/Bspec-31X/correction/Bspecies.ovlStore.BUILDING/scripts/1-bucketize.sh 0
------------------------------------------------------------

TERM_MEMLIMIT: job killed after reaching LSF memory usage limit.
Exited with exit code 130.

Resource usage summary:

    CPU time :                                   28.09 sec.
    Max Memory :                                 6 GB
    Average Memory :                             6.00 GB
    Total Requested Memory :                     8.00 GB
    Delta Memory :                               2.00 GB

**Comment by ishengtsai** [comment]
Hi Brian,

Thanks for pointing out. It's the TERM_MEMLIMIT as well as not correctly assign to different queues (with different cpu allowed). 

For those who's interested, tweak the buildThreadOption in $canu_directory/bin/lib/canu/Execution.pm

![image](https://cloud.githubusercontent.com/assets/5182142/17616490/a128032a-60a7-11e6-9172-2537089c0cc1.png)




Best,
Jason

**Comment by brianwalenz** [comment]
What was the change needed to resolve the memory limit?

I can't see how to support the queue change you need generally, so I'm afraid you'll have to patch this whenever you reinstall.

**Comment by kevlim83** [comment]
Hi Jason,

I have a similar problem. Please share how you handled the memory limit.

Thanks!

Regards,
K
