### ISSUE TITLE
Genome fraction (%) after purge dups

### ISSUE THREAD

**Issue by dtusso2020** [marbl/canu#2250]
Hello

I would like you to help me to know how I can fix an assembly that I made by Canu, it gave me twice the expected size, I used purge_dups but when doing the QUAST analysis, the genome fraction percentage gave me 57%, before it gave me 98%.  BUSCO analysis it gives me 95% unique copy after using purge_dups and the genome size is as expected. If someone could help me I would appreciate it.

Thank you so much.

**Comment by skoren** [comment]
How closely related is the reference you're using for QUAST? Is it the same size genome as your new assembly after purge_dups? BUSCO is more reference-independent so it may be accurate here that the genome is complete.

**Comment by dtusso2020** [comment]
Hello Sergey

I am working with a yeast Candida tropicalis, and the reference is a genome from C. tropicalis MYA-3404 and its genome is in Refseq database. 

This is BUSCO analysis before purge_dups

`BUSCO version is: 4.1.4 
# The lineage dataset is: saccharomycetes_odb10  (number of species: 76, number of BUSCOs: 2137)
# Summarized benchmarking in BUSCO notation for file /home/jforero/mis_datos/tutoriales/racon/canufiltradosinpurgar.fasta
# BUSCO was run in mode: genome

	***** Results: *****

	C:98.6%[S:27.8%,D:70.8%],F:0.6%,M:0.8%,n:2137	   
	2106	Complete BUSCOs (C)			   
	594	Complete and single-copy BUSCOs (S)	   
	1512	Complete and duplicated BUSCOs (D)	   
	13	Fragmented BUSCOs (F)			   
	18	Missing BUSCOs (M)			   
	2137	Total BUSCO groups searched		   
`
This is after purge_dups
`# BUSCO version is: 4.1.4 
# The lineage dataset is: saccharomycetes_odb10 (number of species: 76, number of BUSCOs: 2137)
# Summarized benchmarking in BUSCO notation for file /home/jforero/mis_datos/tutoriales/anaconda3/canufiltradoshaplotigsfinal/curated.fasta
# BUSCO was run in mode: genome

	***** Results: *****

	C:95.6%[S:94.9%,D:0.7%],F:2.2%,M:2.2%,n:2137	   
	2042	Complete BUSCOs (C)			   
	2027	Complete and single-copy BUSCOs (S)	   
	15	Complete and duplicated BUSCOs (D)	   
	47	Fragmented BUSCOs (F)			   
	48	Missing BUSCOs (M)			   
	2137	Total BUSCO groups searched		   
`
This quast analysis before

![QUAST antes](https://github.com/marbl/canu/assets/67991820/879a8596-1d3f-44bb-8f13-8adf640825e1)

And after 
![Captura de pantalla 2023-08-07 131935](https://github.com/marbl/canu/assets/67991820/a5a3c75b-cc9e-40e1-ab06-7cc1f80dd7c4)
Finally, I did the alignment by D-genies,  only with 1.20 % that doesn't have a match
![Captura de pantalla 2023-08-07 134728](https://github.com/marbl/canu/assets/67991820/3d532feb-ecd8-499c-bd46-c4b5cdf180c5)
![Captura de pantalla 2023-08-07 134836](https://github.com/marbl/canu/assets/67991820/18f4385e-264f-4cbe-8a75-b28527696b9c)

**Comment by skoren** [comment]
It sounds like the purged assembly is OK but has enough divergence that QUAST can't align it properly. I think it uses the -asm20 option to minimap2, with some custom chaining params. I'm not sure why it can align the full assembly though, I wouldn't expect the alts to be closer to the reference than the retained nodes in a regular diploid. You could try running QUAST on the purged nodes to see if those align better which would explain it. Otherwise, it's likely a question for the QUAST developers but the assembly is likely OK.
