### ISSUE TITLE
error in "correct" link

### ISSUE THREAD

**Issue by Xinxin0314** [marbl/canu#2256]
Hello,

I met some problems when I assembled the genome. 

command, version and error information as follow:

command:
```canu -correct  -p ath -d pb_ath minThreads=10 useGrid=true genomeSize=1000m -pacbio-raw /md/cc/S_raw/01.S/subreads_L500.fa.gz```

version:
```Canu v0.0 (+0 commits) r0 unknown-hash-tag-no-repository-available.```

error:
```Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'can't open correction output '/md/cc/zz/02.g/01.canu/02.s/canu_correct/pb_ath/correction/2-correction/correction_outputs/0062.fasta' for reading: No such file or directory
```

I've assembled two genomes from the same species at the same time, which in theory should be of the same magnitude. But because of the error in “correct” link, I get corrective ath. correctedReads. fasta. gz is only 625018317, but not the data size gained by the genome data of error correction for 9824670725.

Looking forward to your reply.

Best wishes,
Xin

**Comment by skoren** [comment]
The error implies there were some files that are missing/removed during the run. However, your version and this error message implies your canu installation is very old, likely v1.6 or similar as that message no longer exists in later versions. I would suggest downloading the latest release from the releases page and re-running your assembly from scratch it instead to see if it still has an error. Make sure you use unique -d and -p values for each of your runs as well.

**Comment by Xinxin0314** [comment]
Ok, thanks for your response. I will try it by canu V2.2.

**Comment by skoren** [comment]
If you encounter errors with 2.2, please open a new issue, thanks.
