### ISSUE TITLE
Binary for new Apple M1/M2 processors? 

### ISSUE THREAD

**Issue by AlWa1** [marbl/canu#2261]
I've recently acquired a new-generation MacBook equipped with an M2 processor and was wondering if you provide binaries optimised for these new processors. It appears that the current system is utilising the integrated emulator software Rosetta to run the Intel-based code. 

Thank you in advance!

**Comment by skoren** [comment]
Duplicate with #2260. Right now canu does not build on ARM but we may add support for this in the near future. It requires updating some library dependencies built into canu.

**Comment by YoshitakaMo** [comment]
Hi, I've updated brewsci/bio/canu to ver. 2.2 (`brew install brewsci/bio/canu`). It works on Apple silicon and Linux OS. `canu` on Apple M2 processor could complete the tutorial case in 15 minutes:

```bash
curl -L -o pacbio.fastq http://gembox.cbcb.umd.edu/mhap/raw/ecoli_p6_25x.filtered.fastq
canu -p ecoli -d ecoli-pacbio \
 genomeSize=4.8m \
 -pacbio pacbio.fastq
```
