### ISSUE TITLE
Kmer counting (meryl-count) jobs failed

### ISSUE THREAD

**Issue by Bioinformatics-rookie** [marbl/canu#2266]
When I use the canu 2.2 version, I get an error like the following
```
 I appear to be task  in a job array, unsetting LSB_JOBINDEX.
--
-- Generating assembly '31-1' in '/ds3200_1/users_root/zhoushizhao/Q31-1rawData/00.rawData/canu/350':
--   genomeSize:
--     350000000
--
--   Overlap Generation Limits:
--     corOvlErrorRate 0.0000 (  0.00%)
--     obtOvlErrorRate 0.0250 (  2.50%)
--     utgOvlErrorRate 0.0100 (  1.00%)
--
--   Overlap Processing Limits:
--     corErrorRate    0.0000 (  0.00%)
--     obtErrorRate    0.0250 (  2.50%)
--     utgErrorRate    0.0003 (  0.03%)
--     cnsErrorRate    0.0500 (  5.00%)
--
--   Stages to run:
--     assemble HiFi reads.
--
--
-- Correction skipped; not enabled.
--
-- Trimming skipped; not enabled.
--
-- BEGIN ASSEMBLY
--
-- Kmer counting (meryl-count) jobs failed, tried 2 times, giving up.
--   job 31-1.01.meryl FAILED.
--   job 31-1.02.meryl FAILED.
--   job 31-1.03.meryl FAILED.
--   job 31-1.04.meryl FAILED.
--

ABORT:
ABORT: canu 2.2
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```

commands ： canu -p 31-1 -d 350 maxThreads=24 genomeSize=350000000 -pacbio-hifi ../CCS/ccs.fastq.gz

**Comment by skoren** [comment]
I'd guess this is an issue with PBS not liking the resource commands. PBS is very unstable in this regard between versions/clusters. What's the error in `unitigging/0-mercounts/meryl-count*out` files?

**Comment by SaelinB** [comment]
Hello, I'm having this same issue but with Slurm and my meryl-count files say they were cancelled due to time limit. 
My original script requested 4 days and I think it ran for under an hour. I'm skipping the correction step so it went straight to trimming, which is where it failed. I guess because the default sbatch default time limit is 30 minutes and the sbatch command ran by canu doesn't specify time? In canu-scripts, it failed on canu.04.sh

**Comment by skoren** [comment]
@SaelinB canu submits subsequent jobs to the grid which is why the initial job ran for a short time. You can specify arbitrary time limits to using the `gridOptions` command: https://canu.readthedocs.io/en/latest/faq.html#how-do-i-run-canu-on-my-slurm-sge-pbs-lsf-torque-system.

**Comment by SaelinB** [comment]
Ah sorry I should've seen that myself, thanks!

**Comment by skoren** [comment]
Idle, error due to not setting timeout on grid.
