### ISSUE TITLE
filterCorrectionLayouts : Failed with exit code 1.  (rc=256)

### ISSUE THREAD

**Issue by lgbTime** [marbl/canu#2273]
**canu to correct ONT rnseq **
 I am using the canu2.2(linux)  to correc the ONT rnaseq data,
my command is : 
```
canu useGrid=false -correct gnuplotImageFormat=png corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0 correctedErrorRate=0.16 overlapper=minimap genomesize=2.5G minReadLength=200 minOverlapLength=100 -p canu_out_RLL7AA -nanopore-raw pass.fq.gz -d RLL7AA minInputCoverage=0  stopOnLowCoverage=0 
```
I do have suceessfully correct on one samples, but when I use the same command to correct another samples, it generate the error below. Do anyone has experienced these, or are there any other method to correct the ont rna seq data?

```
 Starting command on Fri Oct 20 22:10:47 2023 with 27277.558 GB free disk space

    cd correction/2-correction
    canu-2.2/bin/filterCorrectionLayouts \
      -S  ../../canu_out_RLL7AA.seqStore \
      -C     ../canu_out_RLL7AA.corStore \
      -R      ./canu_out_RLL7AA.readsToCorrect.WORKING \
      -cc 1 \
      -cl 200 \
      -g  2500000000 \
      -c  10000 \
    > ./canu_out_RLL7AA.readsToCorrect.err 2>&1

-- Finished on Fri Oct 20 22:46:02 2023 (2115 seconds) with 27274.954 GB free disk space
----------------------------------------

ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:

ABORT:
ABORT: canu 2.2
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to generate list of reads to correct.
ABORT:
ABORT: Disk space available:  27274.954 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (correction/2-correction/canu_out_RLL7AA.readsToCorrect.err):
ABORT:
ABORT:   tgTig::loadFromStream()-- not at a tigRecord, got bytes '' (0x00000000).
ABORT:   Failed to load tig 10547465.
ABORT:
```

**Comment by skoren** [comment]
This can happen when there is an I/O failure that isn't caught by the file system. Canu wrote data but the file ends up with a 0 block on disk, I don't think we ever figured out why this happens (see also #936). Fixing it would require backing up to an earlier step and re-running all the overlaps but, if the filesystem is still having some kind of issue, it may happen again.

I suggest you can skip the bad read ID (10547465) by removing it from the readsToCorrect file and re-running. You may have to do this more than once depending on how many sequences are affected. As long as it's a small number you should be OK continuing
