### ISSUE TITLE
bubble contigs

### ISSUE THREAD

**Issue by wez078** [marbl/canu#2278]
**
![Genome_Survey](https://github.com/marbl/canu/assets/85767193/e9ac5a49-768c-4f8e-835b-1da1ef242e78)
![busco_figure](https://github.com/marbl/canu/assets/85767193/8e0b5263-e386-44d9-aefa-26b059280422)
![busco_figure](https://github.com/marbl/canu/assets/85767193/367bd1fd-7f17-41ef-821c-0616e5ead462)
[report_Cabu.pdf](https://github.com/marbl/canu/files/13417532/report_Cabu.pdf)
Dears, 
I survey the genome, and hetero is close to zero, and after I assembled with hiCanu, I still get some bubble contigs, wonder they are alternative or sequencing error,  I used Pcabio hifi reads . Canu report as below

Thanks
wentao

```
UNITIGGING/CONSENSUS]
-- Found, in version 2, after consensus generation:
--   contigs:      188 sequences, total length 68332715 bp (including 120 repeats of total length 2348159 bp).
--   bubbles:      145 sequences, total length 2808364 bp.
--   unassembled:  37102 sequences, total length 227250770 bp.
--
-- Contig sizes based on genome size 80mbp:
--
--            NG (bp)  LG (contigs)    sum (bp)
--         ----------  ------------  ----------
--     10     3472630             3    10534786
--     20     2182914             6    17418427
--     30     1881149            10    25335064
--     40     1361830            15    32768007
--     50     1107699            22    41002401
--     60      885302            30    48606077
--     70      487575            42    56319638
--     80      166589            66    64127837
--
```

**Comment by skoren** [comment]
The threshold in HiFi is very high so single-base differences would disallow reads to overlap. Thus, the bubbles likely contain both alternate haplotypes and noise/systematic errors in the reads. I would suggest setting some filters based on length (50kb or so) and number of reads (reported in the fasta header line, 5-10 would make sense I think) to see how many bubbles remain.

**Comment by wez078** [comment]
Dear Skoren, 
Thanks for your comments, I will give it a try to see 
Cheers'wentao
