### ISSUE TITLE
obtovl doesn't finish

### ISSUE THREAD

**Issue by bioprojects** [marbl/canu#228]
Dear Developers, 

Thank you very much for answering my question previously.
I'm trying to assemble a benchmark data of Nanopore R9 
rapid run (http://lab.loman.net/2016/07/30/nanopore-r9-data-release/),
direct link of which is http://s3.climb.ac.uk/nanopore/E_coli_K12_1D_R9.2_SpotON_2.pass.fasta 

However, obtovl doesn't finish.  It has been running over 60 hours...

I'm using UGE, and the jobs are executed in parallel, 
and two of which are still running now.

I uploaded canu-logs and canu-scripts to 
http://yahara.hustle.ne.jp/projects/canu-logs.tgz
http://yahara.hustle.ne.jp/projects/canu-scripts.tgz

Could you give me an advice about how to fix this problem?

Thanks a lot in advance.

Best wishes,

Koji

---
Koji Yahara
Senior Research Fellow
Department of Bacteriology II
National Institute of Infectious Diseases
4-7-1 Gakuen, Musashimurayama, Tokyo
2080011 Japan
Tel: +81-42-561-0771 (Ex. 3539)

**Comment by skoren** [comment]
I didn't see any issues in your logs (other than initial errors in the correction overlapping which were resolved). The longest reads in this run are quite long and so are making the overlapping run slower than average. However, the 1D data is higher quality than the default Canu parameters which were designed to handle down to MAP005 data so you can decrease the error rate from the default to 0.025 ```errorRate=0.025``` for 1D data and probably ```errorRate=0.013``` for the 2D data. 

I'd also suggest only using the 2D reads which are both directions (not template or complement so your input should be 244Mb or 50X, your current input looks like it's all 1D and 2D data.

**Comment by bioprojects** [comment]
I have confirmed that the "errorRate=0.025" option enabled the computation to finish within 2 days.  Thank you very much!
