### ISSUE TITLE
No contigs.fasta file

### ISSUE THREAD

**Issue by Ladybug1030** [marbl/canu#2283]
Canu version: canu 2.2
System: Virtual Cluster
```Initial Input: 
         -p Myprefix -d MyDirectory genomeSize=86M minReadLength=1000
         -gridOptions="--partition=general --qos=general" canuIteration=1 \
          -rawErrorRate=.18 \
          -nanopore My.fastq.gz\
```
After running the script, I received an error message of failure due to low memory. I have increased the memory several times for the different jobs that Canu runs and I still have a couple of jobs that won't complete.  The new input is below.
```
-p Myprefix -d MyDirectory genomeSize=86M minReadLength=1000
         -gridOptions="--partition=general --qos=general" canuIteration=1 \
          -rawErrorRate=.18 \
          -ovbMemory=50 \
          -ovsMemory=50 \
          -corovlMemory=50 \
          -obtovlMemory=50 \
          -utgovlMemory=50 \
          -nanopore My.fastq.gz\
```
After running this command, I am now receiving the error below. 

```

--   Overlap Generation Limits:
--     corOvlErrorRate 0.1800 ( 18.00%)
--     obtOvlErrorRate 0.1200 ( 12.00%)
--     utgOvlErrorRate 0.1200 ( 12.00%)
--
--   Overlap Processing Limits:
--     corErrorRate    0.1800 ( 18.00%)
--     obtErrorRate    0.1200 ( 12.00%)
--     utgErrorRate    0.1200 ( 12.00%)
--     cnsErrorRate    0.2000 ( 20.00%)
--
--   Stages to run:
--     assemble corrected and trimmed reads.
--
--
-- Correction skipped; not enabled.
--
-- Trimming skipped; not enabled.
--
-- ERROR:  Read coverage (8.69) lower than allowed.
-- ERROR:    stopOnLowCoverage = 10
-- ERROR:
-- ERROR:  This could be caused by an incorrect genomeSize or poor
-- ERROR:  quality reads that cound not be sufficiently corrected.
-- ERROR:
-- ERROR:  You can force Canu to continue by decreasing parameter
-- ERROR:  stopOnLowCoverage (and possibly minInputCoverage too).
-- ERROR:  Be warned that the quality of corrected reads and/or
-- ERROR:  contiguity of contigs will be poor.
--

ABORT:
ABORT: canu 2.2
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```

Please assist as soon as possible. I am not sure what needs to be done next to complete my assembly.

Thanks,

Laura H.

**Comment by skoren** [comment]
Like the message says, the default is to require at least 10x coverage for assembly and you ended up with about 9 after correction. You can force the assembly to run by specifying `stopOnLowCoverage=0 minInputCoverage=0`. However, if you started with much higher coverage this may indicate an issue with your input data/correction. How much coverage did you start with, the report file in the assembly folder should have more details on what the distribution of read lengths looked like and what happened during correction.

**Comment by Ladybug1030** [comment]
Yes. Thank you for your speedy response. What you've written above will be helpful and is aligned with what someone in my lab suggested as well. I appreciate your help with this. Thank you again.
