### ISSUE TITLE
pre-correction read filtering

### ISSUE THREAD

**Issue by igordot** [marbl/canu#229]
I am working with Nanopore data. I am trying to understand the correction summary (`correction.html`). For example, using R9 2D reads (from [Nick Loman E coli run](http://lab.loman.net/2016/07/30/nanopore-r9-data-release/)) and default parameters, I see that ~30,000 reads enter (Final Store readsLoaded), but only ~10,000 remain for read correction (Read Correction input reads). Having a very large fraction of reads drop out seems to be fairly normal based on my experience with a few other runs. Why are so many reads thrown out? There are "Overlaps" and "Overlap Filtering" tables that presumably explain everything, but neither of them specify which categories are kept or removed. Do they? Is there an explanation available for those tables?

**Comment by skoren** [comment]
As you mention in issue #230, corOutCoverage determines which reads are kept and which are thrown out. The R9 1D from that run (I haven't looked at the 2D) has over 300X so when it gets corrected, the longest 40X is only reads over 30 Kbp.

**Comment by igordot** [comment]
Thanks for clarifying! So are the numbers in "Overlap Filtering" table related to that?

**Comment by skoren** [comment]
I think the table you're referring to is for the global filtering Canu does. There are a couple of filters after all overlaps are computed. The first, a global one, only keeps at most C (where C = corOutCoverage) overlaps per read to avoid over-correcting repeats. Each read is only allowed to correct its best C reads (based on length and identity).
