### ISSUE TITLE
some canu contigs are in reverse

### ISSUE THREAD

**Issue by majogalarion** [marbl/canu#2290]
Some contigs (usually included in the unassembled file) are in the reverse direction. Is this even possible? Or is this affected by the quality of the reads?

**Comment by skoren** [comment]
What do you mean reverse direction, with respect to what? As in reverse-complement or something else?

**Comment by skoren** [comment]
The orientation of a contig in any assembly is arbitrary, it will be random chance based on which read got selected to start the contig from. I'd expect identical read inputs would lead to identical outputs but even the same reads re-ordered could change orientation. I wouldn't expect 100% identical sequences though to be duplicated in the assembly, usually unassembled are low-support and/or short sequences that were not included in the primary paths. What is the identical sequence you're aligning to?

**Comment by majogalarion** [comment]
I was trying to align it to a viral RefSeq from GenBank. But thanks for your reply, it makes more sense now. Thanks!
