### ISSUE TITLE
Runing canu in conda environment in HPC, which one is the assembly contig file I that I should get? 

### ISSUE THREAD

**Issue by JWang52md** [marbl/canu#2291]
I runing canu in conda environment in HPC (version 2.2), after running, it give me the output files seeing attached files, I just cannot find where are my assemblied contigs. This is my script:
conda activate canu
canu -d 2A  -p 2A genomeSize=2.5m -nanopore cat_barcode12.fastq

![image](https://github.com/marbl/canu/assets/153654375/502beee5-e2d3-4712-8464-50dd68693a50)

**Comment by skoren** [comment]
I suspect it's running on the grid (https://canu.readthedocs.io/en/latest/faq.html#how-do-i-run-canu-on-my-slurm-sge-pbs-lsf-torque-system), what was the output of the command you ran? If it says submitted that is the case, you can turn off grid use with `useGrid=false`.

**Comment by alpapan** [comment]
@JWang52md when you run canu on a grid, without the use grid set to false, canu's command submits the scripts to the grid and then exits.

Assuming you submitted them correctly, you should check the job queue and wait for your jobs to finish.

**Comment by dittoph** [comment]
Hi! I submitted in the hpc as : qsub -I -A hpc_xxx -q single -l walltime=48:00:00,nodes=1:ppn=4
and the command was : ./canu -d run1 -p TN96 genomeSize=40m mhapPipe=false purgeOverlaps=false saveOverlaps=true corMinCoverage=0 -nanopore 'Cercospora996.fastq'
-- canu 2.2
--
-- CITATIONS
--
-- For 'standard' assemblies of PacBio or Nanopore reads:
--   Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
--   Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
--   Genome Res. 2017 May;27(5):722-736.
--   http://doi.org/10.1101/gr.215087.116
-- 
-- Read and contig alignments during correction and consensus use:
-- Detected Java(TM) Runtime Environment '1.8.0_262' (from 'java') with -d64 support.
--
-- WARNING:
-- WARNING:  Failed to run gnuplot using command 'gnuplot'.
-- WARNING:  Plots will be disabled.
-- WARNING:
--
--
-- Detected 4 CPUs and 63 gigabytes of memory on the local machine.
--
-- Detected  '' with 'pbsnodes' binary in /usr/local/bin/pbsnodes.
-- Detecting PBS/Torque resources.
-- 
-- PBS/Torque support detected.  Resources available:
--    378 hosts with  20 cores and   62 GB memory.
--      1 host  with  20 cores and   54 GB memory.
--      3 hosts with  28 cores and  251 GB memory.
--      1 host  with  20 cores and   58 GB memory.
--     79 hosts with  16 cores and   31 GB memory.
--     32 hosts with  16 cores and   62 GB memory.
--      4 hosts with  36 cores and  376 GB memory.
--      1 host  with  40 cores and 1007 GB memory.
--      8 hosts with  16 cores and  251 GB memory.
--
--                         (tag)Threads
--                (tag)Memory         |
--        (tag)             |         |  algorithm
--        -------  ----------  --------  -----------------------------
-- Grid:  meryl      7.000 GB    4 CPUs  (k-mer counting)
-- Grid:  hap        7.000 GB    4 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   10.000 GB    5 CPUs  (overlap detection with mhap)
-- Grid:  obtovl     8.000 GB    5 CPUs  (overlap detection)
-- Grid:  utgovl     8.000 GB    5 CPUs  (overlap detection)
-- Grid:  cor        -.--- GB    4 CPUs  (read correction)
-- Grid:  ovb        4.000 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs        8.000 GB    1 CPU   (overlap store sorting)
-- Grid:  red       10.000 GB    5 CPUs  (read error detection)
-- Grid:  oea        8.000 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat       64.000 GB    8 CPUs  (contig construction with bogart)
-- Grid:  cns        -.--- GB    8 CPUs  (consensus)
--
-- Found untrimmed raw Nanopore reads in the input files.
--
-- Generating assembly 'TN81' in '/ddnA/work/alevarg/thesis/canu-2.2/bin/run1':
--   genomeSize:
--     40000000
--
--   Overlap Generation Limits:
--     corOvlErrorRate 0.3200 ( 32.00%)
--     obtOvlErrorRate 0.1200 ( 12.00%)
--     utgOvlErrorRate 0.1200 ( 12.00%)
--
--   Overlap Processing Limits:
--     corErrorRate    0.3000 ( 30.00%)
--     obtErrorRate    0.1200 ( 12.00%)
--     utgErrorRate    0.1200 ( 12.00%)
--     cnsErrorRate    0.2000 ( 20.00%)
--
--   Stages to run:
--     correct raw reads.
--     trim corrected reads.
--     assemble corrected and trimmed reads.
--
--
-- BEGIN CORRECTION
----------------------------------------
-- Starting command on Thu Mar 21 15:27:09 2024 with 841207.267 GB free disk space

    cd .
    ./TN96.seqStore.sh \
    > ./TN96.seqStore.err 2>&1

-- Finished on Thu Mar 21 15:27:59 2024 (50 seconds) with 841189.105 GB free disk space
----------------------------------------
--
-- In sequence store './TN81.seqStore':
--   Found 520700 reads.
--   Found 2766943001 bases (69.17 times coverage).
--    Histogram of raw reads:
--    
--    G=2766943001                       sum of  ||               length     num
--    NG         length     index       lengths  ||                range    seqs
--    ----- ------------ --------- ------------  ||  ------------------- -------
--    00010        20946     10102    276710051  ||       1000-2406       112002|------------------------------------------------
--    00020        14682     26069    553395328  ||       2407-3813       148016|---------------------------------------------------------------
--    00030        11004     47984    830085087  ||       3814-5220        92592|----------------------------------------
--    00040         8535     76652   1106778166  ||       5221-6627        51639|----------------------
--    00050         6744    113248   1383477328  ||       6628-8034        31408|--------------
--    00060         5412    159192   1660167216  ||       8035-9441        20895|---------
--    00070         4380    216135   1936864352  ||       9442-10848       14772|-------
--    00080         3539    286468   2213556541  ||      10849-12255       10684|-----
--    00090         2726    375047   2490250478  ||      12256-13662        8069|----
--    00100         1000    520699   2766943001  ||      13663-15069        6065|---
--    001.000x              520700   2766943001  ||      15070-16476        4644|--
--                                               ||      16477-17883        3840|--
--                                               ||      17884-19290        3049|--
--                                               ||      19291-20697        2505|--
--                                               ||      20698-22104        2037|-
--                                               ||      22105-23511        1634|-
--                                               ||      23512-24918        1303|-
--                                               ||      24919-26325        1059|-
--                                               ||      26326-27732         899|-
--                                               ||      27733-29139         684|-
--                                               ||      29140-30546         535|-
--                                               ||      30547-31953         477|-
--                                               ||      31954-33360         397|-
--                                               ||      33361-34767         319|-
--                                               ||      34768-36174         249|-
--                                               ||      36175-37581         187|-
--                                               ||      37582-38988         149|-
--                                               ||      38989-40395         138|-
--                                               ||      40396-41802         113|-
--                                               ||      41803-43209          85|-
--                                               ||      43210-44616          47|-
--                                               ||      44617-46023          44|-
--                                               ||      46024-47430          25|-
--                                               ||      47431-48837          36|-
--                                               ||      48838-50244          27|-
--                                               ||      50245-51651          17|-
--                                               ||      51652-53058          12|-
--                                               ||      53059-54465          10|-
--                                               ||      54466-55872          12|-
--                                               ||      55873-57279           7|-
--                                               ||      57280-58686           6|-
--                                               ||      58687-60093           3|-
--                                               ||      60094-61500           1|-
--                                               ||      61501-62907           1|-
--                                               ||      62908-64314           0|
--                                               ||      64315-65721           3|-
--                                               ||      65722-67128           1|-
----------------------------------------
--                                               ||      67129-68535           1|-
--                                               ||      68536-69942           1|-
--                                               ||      69943-71349           1|-
--    
----------------------------------------
-- Starting command on Thu Mar 21 15:28:00 2024 with 841189.105 GB free disk space
    cd correction/0-mercounts
    ./meryl-configure.sh \
    > ./meryl-configure.err 2>&1
-- Finished on Thu Mar 21 15:28:00 2024 (fast as lightning) with 841189.105 GB free disk space
----------------------------------------
--  segments   memory batches
--  -------- -------- -------
--        01  5.61 GB       2
--        02  2.99 GB       2
--        04  1.56 GB       2
--        06  1.19 GB       2
--        08  0.89 GB       2
--        12  0.60 GB       2
--        16  0.45 GB       2
--        20  0.36 GB       2
--        24  0.30 GB       2
--
--  For 520700 reads with 2766943001 bases, limit to 27 batches.
--  Will count kmers using 01 jobs, each using 7 GB and 4 threads.
--
-- Finished stage 'merylConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
--
-- Failed to submit compute jobs.  Delay 10 seconds and try again.
CRASH:
CRASH: canu 2.2
CRASH: Please panic, this is abnormal.
CRASH:
CRASH:   Failed to submit compute jobs.
CRASH:
CRASH: Failed at /ddnA/work/alevag/thesis/canu-2.2/bin/../lib/site_perl/canu/Execution.pm line 1259.
CRASH:  canu::Execution::submitOrRunParallelJob('TN81', 'meryl', 'correction/0-mercounts', 'meryl-count', 1) called at /ddnA/work/alevarg/thesis/canu-2.2/bin/../lib/site_perl/canu/Meryl.pm line 847
CRASH:  canu::Meryl::merylCountCheck('TN81', 'cor') called at ./canu line 1076
CRASH: 
CRASH: Last 50 lines of the relevant log file (correction/0-mercounts/meryl-count.jobSubmit-01.out):
CRASH:
CRASH: qsub: Bad UID for job execution MSG=ruserok failed validating alevarg/alevarg from mikeb53
CRASH:
