### ISSUE TITLE
Relax constraint for thread environment on SGE

### ISSUE THREAD

**Issue by skoren** [marbl/canu#23]
Currently, Canu looks for a parallel environment which has

```
allocation_rule    $pe_slots
control_slaves     FALSE
```

However, I think it will work with just $pe_slots and control_slaves set to TRUE. I suggest using the current requirements as a first pass then relaxing to ignore control_slaves if none are found.

**Comment by brianwalenz** [comment]
Commit 201fa6fdde41d1635d467e90fe416a4e11d565b5 removes the control_slaves constraint and picks a PE.  The PE selected is the one that has the most slots allowed.
