### ISSUE TITLE
Question: parameters for better quality data

### ISSUE THREAD

**Issue by marija-kra** [marbl/canu#2300]
Hi,
I recently rebasecalled some old R9.4.1 ONT data (using dorado sup) and I'm hoping to assemble it using canu. What parameters would you suggest tweaking for this? 

I was thinking of reducing the rawErrorRate, as the read quality is 10.9 (mean) & 13.1 (median). Keeping rawErrorRate at 0.50 feels wrong, but I'm wondering if I'm mistunderstanding something about this parameter. Thanks!

**Comment by skoren** [comment]
I would suggest the uncorrected parameters from the FAQ here: https://canu.readthedocs.io/en/latest/quick-start.html#assembling-with-multiple-technologies-and-multiple-files.
