### ISSUE TITLE
How much storage space is required for the assembly of a large genome species?

### ISSUE THREAD

**Issue by Jung19911124** [marbl/canu#2302]
My group is planning the WGS of a wild animal with a large genome size (approximately 6.5 Gb). 
After the HiFi assembly, we plan to gap-close using Tell-seq reads and CLRs. 
Due to budgetary constraints, the number of HiFi reads will be x20 of the genome size. 

Under these conditions, how much storage space should be reserved on the server when haplotype-aware assembly is performed using HiCanu?

Best,
Jung

**Comment by skoren** [comment]
There's some information on the resources required here: https://canu.readthedocs.io/en/latest/faq.html#what-resources-does-canu-require-for-a-bacterial-genome-assembly-a-mammalian-assembly. Usually a human genome requires approximately 200 Gb w/HiFi data so, given your genome is about 2x larger, I'd estimate 500 Gb - 1 Tb
