### ISSUE TITLE
Default parameters gave unsatisfied unitigging numbers, any suggestions to improve the parameters?

### ISSUE THREAD

**Issue by wsuplantpathology** [marbl/canu#231]
Hi canu team:

Thanks for such a nice tool. My first try is to use default parameters to correct, and assembly my PacBio reads. However, it seems these default parameters did not give me satisfied unitigging numbers, shown as following: 
```
--
--   category            reads     %          read length        feature size or coverage  analysis
--   ----------------  -------  -------  ----------------------  ------------------------  --------------------
--   middle-missing      27924    3.74     7251.08 +- 6145.65       1602.15 +- 2146.24    (bad trimming)
--   middle-hump             0    0.00        0.00 +- 0.00             0.00 +- 0.00       (bad trimming)
--   no-5-prime              0    0.00        0.00 +- 0.00             0.00 +- 0.00       (bad trimming)
--   no-3-prime              0    0.00        0.00 +- 0.00             0.00 +- 0.00       (bad trimming)
--   
--   low-coverage       103543   13.89     6932.34 +- 4680.17          3.00 +- 1.90       (easy to assemble, potential for lower quality consensus)
--   unique               4324    0.58     7751.81 +- 4287.26         28.41 +- 8.21       (easy to assemble, perfect, yay)
--   repeat-cont             0    0.00        0.00 +- 0.00             0.00 +- 0.00       (potential for consensus errors, no impact on assembly)
--   repeat-dove        183313   24.58     6772.24 +- 4717.46      10505.93 +- 9908.00    (hard to assemble, likely won't assemble correctly or even at all)
--   
--   span-repeat        234702   31.47     8900.86 +- 4972.07       7026.14 +- 4843.86    (read spans a large repeat, usually easy to assemble)
--   uniq-repeat-cont        0    0.00        0.00 +- 0.00                                (should be uniquely placed, low potential for consensus errors, no impact on assembly)
--   uniq-repeat-dove   151720   20.35     7697.52 +- 4899.48                             (will end contigs, potential to misassemble)
--   uniq-anchor            82    0.01    11410.68 +- 8569.05       2984.84 +- 2887.57    (repeat read, with unique section, probable bad read)
----------------------------------------
```
It seems there are too few reads in "unique" category, and too many reads in "repeat-dove" and "uniq-repeat-dove" categories, compared with the results shown in #162 . So I wonder do you have any suggestions or how to set the parameters to reduce the "repeat-dove" and "uniq-repeat-dove" reads, and to increase the "unique" reads? Thanks so much in advance.

ps: my fungus has a ~120Mb genome, probably is high heterozygous. The code is here: 
/home/plant_pathology/cho.xia/software/canu-1.3/Linux-amd64/bin/canu -p PST93210_default -d default genomeSize=120m -pacbio-raw /home/plant_pathology/cho.xia/PacBio/PST93210/data/filtered_subreads.fastq -useGrid=0

Thanks.

**Comment by skoren** [comment]
The stats above are not unitig stats but just overlap information on the reads. Is this output from the correction step, if so I wouldn't worry about the high number of unique or repeat-dove reads. That isn't indicative of final assembly quality.

**Comment by wsuplantpathology** [comment]
Thanks for your response. Yes, it's overlap information from correction step. Currently, the program is still running, I'm waiting for the final assembly. 

One more silly question: it seems canu cannot use GNUPLOT. I have gnuplot 4.0 in our HPC cluster, 
>[cho.xia@login1 ~]$ gnuplot --version
>gnuplot 4.0 patchlevel 0
but I have warning: 
>WARNING: gnuplot failed; no plots will appear in HTML output.

So is there a way to fix this? Thanks so much for this nice assembler.

**Comment by brianwalenz** [comment]
The gnuplot 'scripts' are left in the assembly tree, look for files ending in *.gp.  Canu is running gnuplot as: `gnuplot <file>.gp`.  Can you run some of those by hand and see what it reports?  Others have had problems generating png images.

From a relatively recent test assembly, I have files:
```
> find . -type f -name \*gp
./unitigging/0-mercounts/test.ms22.histogram.sm.gp
./unitigging/0-mercounts/test.ms22.histogram.lg.gp
./unitigging/test.gkpStore/readlengths.gp
./trimming/0-mercounts/test.ms22.histogram.sm.gp
./trimming/0-mercounts/test.ms22.histogram.lg.gp
./trimming/test.gkpStore/readlengths.gp
./trimming/3-overlapbasedtrimming/test.1.trimReads.outputNoOvlReads.gp
./trimming/3-overlapbasedtrimming/test.1.trimReads.trim5.gp
./trimming/3-overlapbasedtrimming/test.1.trimReads.outputUnchangedReads.gp
./trimming/3-overlapbasedtrimming/test.1.trimReads.outputTrimmedReads.gp
./trimming/3-overlapbasedtrimming/test.1.trimReads.trim3.gp
./trimming/3-overlapbasedtrimming/test.1.trimReads.inputDeletedReads.gp
./trimming/3-overlapbasedtrimming/test.1.trimReads.inputReads.gp
./trimming/3-overlapbasedtrimming/test.1.trimReads.inputNoTrimReads.gp
./trimming/3-overlapbasedtrimming/test.1.trimReads.outputDeletedReads.gp
./correction/test.gkpStore/readlengths.gp
./correction/2-correction/test.originalLength-vs-correctedLength.gp
./correction/2-correction/test.estimate.original-x-correctedLength.gp
./correction/2-correction/test.length-histograms.gp
./correction/0-mercounts/test.ms16.histogram.lg.gp
./correction/0-mercounts/test.ms16.histogram.sm.gp
```
just replace 'test' with the name of your assembly.

**Comment by wsuplantpathology** [comment]
Thanks @brianwalenz !
I can run `nuplot <file>.gp` correctly for each individual .gp file. In fact, during I ran Canu, the program already generated png images for each .gp files. I guess my original problem was, no plots in HTML output. 
Now I think it's not a big issue for me, since I can check the images individually in my output directories. Just report this.

Thanks so much anyway.

**Comment by brianwalenz** [comment]
If the files exist -- with the proper names -- they should be automatically included in the HTML.  What image files do you have in, for example, 0-mercounts and *.gkpStore?

**Comment by wsuplantpathology** [comment]
Hello @brianwalenz 
Thanks again for your response. Let's see what have:

> $ find . -type f -name \*gp
./default/correction/0-mercounts/PST93210_default.ms16.histogram.lg.gp
./default/correction/0-mercounts/PST93210_default.ms16.histogram.sm.gp
./default/correction/PST93210_default.gkpStore/readlengths.gp
./default/correction/2-correction/PST93210_default.estimate.original-x-correctedLength.gp
./default/correction/2-correction/PST93210_default.originalLength-vs-correctedLength.gp
./default/correction/2-correction/PST93210_default.length-histograms.gp
./default/trimming/0-mercounts/PST93210_default.ms22.histogram.lg.gp
./default/trimming/0-mercounts/PST93210_default.ms22.histogram.sm.gp
./default/trimming/PST93210_default.gkpStore/readlengths.gp
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.inputReads.gp
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.inputDeletedReads.gp
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.inputNoTrimReads.gp
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.outputTrimmedReads.gp
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.outputNoOvlReads.gp
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.outputDeletedReads.gp
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.outputUnchangedReads.gp
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.trim5.gp
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.trim3.gp
./default/unitigging/0-mercounts/PST93210_default.ms22.histogram.lg.gp
./default/unitigging/0-mercounts/PST93210_default.ms22.histogram.sm.gp
./default/unitigging/PST93210_default.gkpStore/readlengths.gp

When I click `unitigging.html` file I can see tables in my Chrome web page, but no images. For example, no images under Read Length Histogram and k-mer Counts. But I can find these images under my directory 
`./default/unitigging.html.files`

I assume this is not a big deal. Thanks anyway. Please let me if you need more information.

**Comment by brianwalenz** [comment]
Nope, search for 'png' files (the outputs), not the 'gp' files (the inputs).

**Comment by wsuplantpathology** [comment]
Thanks @brianwalenz 

Here it is:

> $ find . -type f -name \*png
./default/correction/0-mercounts/PST93210_default.ms16.histogram.lg.png
./default/correction/0-mercounts/PST93210_default.ms16.histogram.sm.png
./default/correction/PST93210_default.gkpStore/readlengths.lg.png
./default/correction/PST93210_default.gkpStore/readlengths.sm.png
./default/correction/2-correction/PST93210_default.estimate.original-x-corrected.lg.png
./default/correction/2-correction/PST93210_default.estimate.original-x-corrected.sm.png
./default/correction/2-correction/PST93210_default.originalLength-vs-expectedLength.lg.png
./default/correction/2-correction/PST93210_default.originalLength-vs-expectedLength.sm.png
./default/correction/2-correction/PST93210_default.originalLength-vs-correctedLength.lg.png
./default/correction/2-correction/PST93210_default.originalLength-vs-correctedLength.sm.png
./default/correction/2-correction/PST93210_default.expectedLength-vs-correctedLength.lg.png
./default/correction/2-correction/PST93210_default.expectedLength-vs-correctedLength.sm.png
./default/correction/2-correction/PST93210_default.length-histograms.lg.png
./default/correction/2-correction/PST93210_default.length-histograms.sm.png
./default/correction/2-correction/PST93210_default.length-difference-histograms.lg.png
./default/correction/2-correction/PST93210_default.length-difference-histograms.sm.png
./default/correction.html.files/readlengths.lg.png
./default/correction.html.files/readlengths.sm.png
./default/correction.html.files/PST93210_default.ms16.histogram.lg.png
./default/correction.html.files/PST93210_default.ms16.histogram.sm.png
./default/trimming/0-mercounts/PST93210_default.ms22.histogram.lg.png
./default/trimming/0-mercounts/PST93210_default.ms22.histogram.sm.png
./default/trimming/PST93210_default.gkpStore/readlengths.lg.png
./default/trimming/PST93210_default.gkpStore/readlengths.sm.png
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.inputReads.lg.png
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.inputReads.sm.png
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.inputDeletedReads.lg.png
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.inputNoTrimReads.lg.png
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.outputTrimmedReads.lg.png
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.outputTrimmedReads.sm.png
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.outputNoOvlReads.lg.png
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.outputNoOvlReads.sm.png
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.outputDeletedReads.lg.png
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.outputDeletedReads.sm.png
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.outputUnchangedReads.lg.png
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.outputUnchangedReads.sm.png
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.trim5.lg.png
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.trim5.sm.png
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.trim3.lg.png
./default/trimming/3-overlapbasedtrimming/PST93210_default.1.trimReads.trim3.sm.png
./default/trimming.html.files/readlengths.lg.png
./default/trimming.html.files/readlengths.sm.png
./default/trimming.html.files/PST93210_default.ms22.histogram.lg.png
./default/trimming.html.files/PST93210_default.ms22.histogram.sm.png
./default/unitigging/0-mercounts/PST93210_default.ms22.histogram.lg.png
./default/unitigging/0-mercounts/PST93210_default.ms22.histogram.sm.png
./default/unitigging/PST93210_default.gkpStore/readlengths.lg.png
./default/unitigging/PST93210_default.gkpStore/readlengths.sm.png
./default/unitigging.html.files/readlengths.lg.png
./default/unitigging.html.files/readlengths.sm.png
./default/unitigging.html.files/PST93210_default.ms22.histogram.lg.png
./default/unitigging.html.files/PST93210_default.ms22.histogram.sm.png

**Comment by brianwalenz** [comment]
They're being detected - they show up in the *.html.files directories - and I'll assume they are linked in the unitigging.html file too.  Try a different browser?

Anyway, they're being generated and detected and you're happy, so I'm happy.  Good luck with the assembly.

**Comment by wsuplantpathology** [comment]
OK. Thanks for your kind help.
