### ISSUE TITLE
200x coverage job stuck at 1-overlapper with "Pathname of a file,  directory or other parameter too long"

### ISSUE THREAD

**Issue by brunocontrerasmoreira** [marbl/canu#2310]
Hi, I am using canu 2.2 with 2.5TB compressed reads, you can see more details of my job at https://github.com/marbl/canu/issues/2309 .
  
My problem now is at script `unitigging/1-overlapper/overlap.jobSubmit-01.sh`: 

    sbatch \
      --cpus-per-task=16 --mem-per-cpu=1536m --mem-per-cpu=32G -o overlap.%A_%a.out \
      -D `pwd` -J "utgovl_Apin" \
      -a 1-4095 \
      `pwd`/overlap.sh 0 \
    > ./overlap.jobSubmit-01.out 2>&1

This fails with:

    sbatch.orig: error: Batch job submission failed: Pathname of a file,  directory or other parameter too long
  
This error was already discussed at https://github.com/marbl/canu/issues/2149 but in my case, an estimated 17g genome, I have a lot more coverage (200x), so I am asking for your recommendation. The `overlap.sh` script contains 857k lines! How should I proceed?

Thanks for your help, 
Bruno

**Comment by skoren** [comment]
You can follow the same suggestion as in #2149 and split the shells script into multiple files and submit them yourself and resume canu after they complete. I'd also remove the explicit mem-per-cpu option you have in your canu command since that will over-subscribe the memory on the nodes, meaning fewer jobs will run in parallel (for example the above job will use 24gb and 16 cores while reserving 512g). You can also adjust parameters to decrease the number of overlap jobs by increasing memory/partition sizes. There's some info here: https://canu.readthedocs.io/en/latest/parameter-reference.html#overlapper-configuration. You can increase the memory (currently 24g)/threads(currently 16)/ovlHashBlockLen (default 640000000) and ovlRefBlockLen (default 30000000000). To adjust the memory, you have to use the `utgOvl*` parameters not gridOptions. Generally, doubling the Len params will halve the number of jobs. There will likely be other parts you'll need to adjust the parameters to decrease the number of parallel jobs, probably `ovsMemory=64` and `redMemory=64` or maybe even 128.

That said, 200x is quite a lot of coverage. You can probably downsample that quite a bit and get the same or better assembly. What does the histogram from the first step look like? Is this a very homozygous or heterozygous genome? I'd suggest something like 30-50x per haplotype so if it's very homozygous 50x total or 60-100x if it's not.

**Comment by brunocontrerasmoreira** [comment]
Thanks @skoren , k-mer the histogram in the `.report` file looks like this:

````
[UNITIGGING/MERS]
--
--  22-mers                                                                                           Fraction
--    Occurrences   NumMers                                                                         Unique Total
--       1-     1         0                                                                        0.0000 0.0000
--       2-     2 271543286 *********                                                              0.0131 0.0002
--       3-     4 857430526 ****************************                                           0.0317 0.0007
--       5-     7 1629053870 ******************************************************                 0.0797 0.0027
--       8-    11 2074387778 *********************************************************************  0.1594 0.0077
--      12-    16 2077730021 ********************************************************************** 0.2554 0.0167
--      17-    22 1860855574 **************************************************************         0.3503 0.0294
--      23-    29 1598317004 *****************************************************                  0.4356 0.0450
--      30-    37 1356805080 *********************************************                          0.5095 0.0629
--      38-    46 1153836993 **************************************                                 0.5726 0.0824
--      47-    56 987585662 *********************************                                      0.6267 0.1031
--      57-    67 848670347 ****************************                                           0.6731 0.1250
--      68-    79 729611907 ************************                                               0.7132 0.1476
--      80-    92 627634652 *********************                                                  0.7477 0.1707
--      93-   106 540836253 ******************                                                     0.7774 0.1939
--     107-   121 467416038 ***************                                                        0.8031 0.2170
--     122-   137 405349063 *************                                                          0.8254 0.2400
--     138-   154 352830412 ***********                                                            0.8447 0.2626
--     155-   172 308220427 **********                                                             0.8615 0.2848
--     173-   191 270224294 *********                                                              0.8762 0.3065
--     192-   211 237573519 ********                                                               0.8891 0.3277
--     212-   232 209518692 *******                                                                0.9005 0.3484
--     233-   254 185327348 ******                                                                 0.9105 0.3685
--     255-   277 164310882 *****                                                                  0.9194 0.3880
--     278-   301 145894010 ****                                                                   0.9272 0.4068
--     302-   326 129770920 ****                                                                   0.9342 0.4251
--     327-   352 115567624 ***                                                                    0.9405 0.4427
--     353-   379 103142324 ***                                                                    0.9460 0.4596
--     380-   407  92198033 ***                                                                    0.9510 0.4759
--     408-   436  82539076 **                                                                     0.9554 0.4916
--     437-   466  74022051 **                                                                     0.9593 0.5067
--     467-   497  66457895 **                                                                     0.9629 0.5211
--     498-   529  59747225 **                                                                     0.9661 0.5350
--     530-   562  53802739 *                                                                      0.9690 0.5483
--     563-   596  48512381 *                                                                      0.9715 0.5610
--     597-   631  43788301 *                                                                      0.9739 0.5731
--     632-   667  39602333 *                                                                      0.9760 0.5848
--     668-   704  35843987 *                                                                      0.9779 0.5959
--     705-   742  32482626 *                                                                      0.9796 0.6065
--     743-   781  29483744                                                                        0.9812 0.6167
--     782-   821  26789631                                                                        0.9826 0.6264
--
--           0 (max occurrences)
-- 2305121852937 (total mers, non-unique)
-- 20729763390 (distinct mers, non-unique)
--           0 (unique mers)
```

**Comment by skoren** [comment]
The peak here is around 12-16x which is way lower than the 200x estimate based on genome size. What's the input data type and what was sequencing (individual, pool, amplified, etc)? If it's HiFi it seems much higher error than expected or at least not consistent with the genome size estimate. I'll be curious what jellyfish/genomescope give you. 

Given that info, I'm not sure you want to subset the reads. I'm not sure what you mean by refine but the assembler would not be able to use the reads it was not provided in any way. You could use them for polishing or validation after assembly.

**Comment by brunocontrerasmoreira** [comment]
It was a single individual, I will come back once jellyfish completes

**Comment by eead-csic-compbio** [comment]
Using only a quarter of the reads I got a coverage of 33x, please see http://genomescope.org/genomescope2.0/analysis.php?code=VqzczOczSTg55wiOzlTR

**Comment by skoren** [comment]
That doesn't look a reasonable estimate, there is no peak for non-noise k-mers, genomescope's fit is very poor. I wouldn't trust any of those estimates. Based on #2309 this is supposed to be HiFi data but it does not seem like it is. Are you using the subreads instead of the CCS-processed reads? The genomescope histogram for HiFi data should have a clear noise peak, a dip, and then a peak for the true genome coverage, like the examples provided on genome scope's page.

**Comment by eead-csic-compbio** [comment]
> That doesn't look a reasonable estimate, there is no peak for non-noise k-mers, genomescope's fit is very poor. I wouldn't trust any of those estimates. Based on #2309 this is supposed to be HiFi data but it does not seem like it is. Are you using the subreads instead of the CCS-processed reads? The genomescope histogram for HiFi data should have a clear noise peak, a dip, and then a peak for the true genome coverage, like the examples provided on genome scope's page.

Indeed I am using subreads extracted from BAM files
