### ISSUE TITLE
Something goes wrong when I use canu. Help me plz

### ISSUE THREAD

**Issue by helloworldABCD1234** [marbl/canu#2315]
Something goes wrong when I use canu. Help me plz

```
-- Detected Java(TM) Runtime Environment '18.0.2.1' (from '/APP/apps/jdk/18.0.2.1/bin/java') without -d64 support.
-- WARNING:  Failed to run gnuplot using command 'gnuplot'.
-- WARNING:  Plots will be disabled.

-- Stages to run:
-- assemble HiFi reads.
-- Correction skipped; not enabled.
-- Trimming skipped; not enabled.

3.
sbatch: error: Batch job submission failed: Invalid account or account/partition combination specified
----------------------------------------
ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:
-- Failed to submit Canu executive.  Delay 10 seconds and try again.
----------------------------------------
```
What should I do.

![1](https://github.com/marbl/canu/assets/63828474/574a079f-6ceb-4334-b8e4-efb8e45fecdf)
![2](https://github.com/marbl/canu/assets/63828474/367bda7d-b8be-404b-8f2e-1a7a49289237)
![3](https://github.com/marbl/canu/assets/63828474/71e6a94f-1dd0-4185-aee7-bfba8a0e0b53)

**Comment by skoren** [comment]
It's a good idea to check other issues and the documentation for similar cases (e.g. #1810, #1330). As listed on the FAQ: https://canu.readthedocs.io/en/latest/faq.html#how-do-i-run-canu-on-my-slurm-sge-pbs-lsf-torque-system, Canu will not request specific partitions/queues and will try to submit to the default partition. It looks like your  cluster requires something else, you have whatever account/partition you want Canu to use yourself using gridOptions (e.g. `gridOptions="<however your grid requires you to specify account/partition>".

**Comment by skoren** [comment]
Idle
