### ISSUE TITLE
 Read coverage (0) lower than allowed.  minInputCoverage  = 10. Help me boss

### ISSUE THREAD

**Issue by helloworldABCD1234** [marbl/canu#2316]
```
-- BEGIN CORRECTION
----------------------------------------
-- Starting command on Mon May 13 16:59:54 2024 with 761.581 GB free disk space

    cd .
    ./correct.seqStore.sh \
    > ./correct.seqStore.err 2>&1

-- Finished on Mon May 13 17:01:10 2024 (76 seconds) with 758.199 GB free disk space
----------------------------------------
--
-- ERROR:  Read coverage (0) lower than allowed.
-- ERROR:    minInputCoverage  = 10
-- ERROR:
-- ERROR:  This could be caused by an incorrect genomeSize.
-- ERROR:
-- ERROR:  You can force Canu to continue by decreasing parameter
-- ERROR:  minInputCoverage.  Be warned that the quality of corrected
-- ERROR:  reads and/or contiguity of contigs will be poor.
--

ABORT:
ABORT: canu 2.2
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```
![canu-problem](https://github.com/marbl/canu/assets/63828474/1b063fc6-4c2f-429b-89f3-694c8b1342c1)
![canu-problem2](https://github.com/marbl/canu/assets/63828474/9778397b-7173-4cd5-a64c-a484beedf87c)

**Comment by skoren** [comment]
I guess you were able to resolve the previous issue (#2315)? The error message means you have insufficient coverage for your genome. How big is your genome and how much coverage do you expect to have? Post the full log of the run and the report file in the folder.

**Comment by helloworldABCD1234** [comment]
my genome are 220M, I set genomeSize=5.4m
nohup canu -p test1 -d test1 genomeSize=5.4m -pacbio pacbio.fastq

**Comment by skoren** [comment]
If the genome is 220mb, is there a reason you're setting genome size to 5.4m instead? What sequencing coverage do you expect to have in your input? Can you post the full report and output of the canu run I mentioned last time?

**Comment by skoren** [comment]
Idle, no reply
