### ISSUE TITLE
ovStoreDump command

### ISSUE THREAD

**Issue by tianjio** [marbl/canu#2317]
I use the command `ovStoreDump -raw -S *seqStore -O *. ovlStore-paf > out_filter.paf` to output the overlap of uncorrected reads. However, the final out_filter.paf generated only the overlap between the first six reads and the others.

**Comment by skoren** [comment]
What there any error from the ovStoreDump command? The overlaps are sorted so the first reads will come first, that's normal. Without more info on how exactly you built the store though I can't say why more overlaps were not output.

**Comment by skoren** [comment]
Idle, no response
