### ISSUE TITLE
canu issue

### ISSUE THREAD

**Issue by NINI-recherche** [marbl/canu#2319]
canu -d '/home/ubintu/sars-cov-2_test/4_canu' -p prefix genomeSize=30K -nanopore-raw '/home/ubintu/sars-cov-2_test/3_NanoFilt/Filtered.fastq' -stopOnReadQuality=false
Don't panic, but a mostly harmless error occurred and canu failed.

Disk space available:  107.412 GB

Last 50 lines of the relevant log file (/home/ubintu/sars-cov-2_test/4_canu/unitigging/prefix.ctgStore/partitionedReads.err):

gkStore::gkStore_clone()- failed to find path of '/home/ubintu/sars-cov-2_test/4_canu/unitigging/prefix.gkpStore': Invalid argument

canu failed with 'failed to partition the reads'.

**Comment by brianwalenz** [comment]
Which version is this?  It looks like an exceptionally old version, so my first recommendation would be to update to the latest.

**Comment by skoren** [comment]
Idle, outdated version of canu
