### ISSUE TITLE
Java error in mhap stage of overlapper

### ISSUE THREAD

**Issue by ishengtsai** [marbl/canu#232]
Hi,

We have been running canu under LSF environment with great success in various genomes until this particular plant species (~35X ; 740Mb). Looking at the logs there are always 2-3 out of 47 jobs that failed. 

Looking at the log, it seems a memory issue even though I have now specified corMemory=60 and cormhapMemory=60 , with the parameters passed correctly (see below). Anyone can suggest what settings shall I try instead to hopefully have these jobs executed successfully? Thanks in advance. 

Best,
Jason

![image](https://cloud.githubusercontent.com/assets/5182142/17649567/2f046872-626b-11e6-91d8-c63e422697b6.png)

![image](https://cloud.githubusercontent.com/assets/5182142/17649573/94e163fc-626b-11e6-849e-10b875ead5d8.png)

**Comment by brianwalenz** [comment]
I'm thinking LSF isn't respecting the memory requested by each job.  What's the detected hardware (at the start of the canu output)?  How many jobs are being scheduled on a single node at the same time?

You can use number of threads as a surrogate for memory.  For example, if your hosts are 32 cores and 64gb, request mhapThreads=8 mhapMemory=15.  This will run at most four jobs per node (4*8 = 32) with each using at most 15gb.

**Comment by ishengtsai** [comment]
The detected hardware is as follows:
![image](https://cloud.githubusercontent.com/assets/5182142/17656447/c5087530-62ec-11e6-9c89-5c546ad6d29d.png)


I have set ovbMemory=10 mhapThreads=8 cormhapMemory=120 mhapMemory=15 and succeeded in mhap stage, but not the subsequent precompute stage (still reserve memory error). 

![image](https://cloud.githubusercontent.com/assets/5182142/17656508/597b9b48-62ed-11e6-9583-7c5cae2b05dc.png)

Any suggestions?

**Comment by ishengtsai** [comment]
I have removed cormhapMemory=120 , and only kept mhapThreads=8 mhapMemory=15 and succeeded. Thanks Brian for the advice.

**Comment by brianwalenz** [comment]
When it originally failed, do you remember the order of the parameters given to canu?

a) "cormhapMemory=120 mhapMemory=15"
b) "mhapMemory=15 cormhapMemory=120"

Case (a) should have worked as mhapMemory should also be setting cormhapMemory.

**Comment by ishengtsai** [comment]
Ah sorry I removed the command and replaced with the new one. I can rerun again when I have time.
