### ISSUE TITLE
How to install canu

### ISSUE THREAD

**Issue by Narmatha99** [marbl/canu#2324]
I am new to this method of genome assembly, so I am struggling a little with installing Canu. 
I think I should use the following command (but I am not sure):

`curl -L https://github.com/marbl/canu/releases/download/v2.2/canu-2.2.<OX>-amd64.tar.xz --output canu-2.2.<OS>.tar.xz`

If this is correct, what should I define `<OX>` and `<OS>` as? 

Thank you.

**Comment by skoren** [comment]
It looks like markdown hid the \<OS\> text in your issue and the documents. The `<OS>` is either Darwin or Linux, depending on what machine you're running on, both are x86. So if you have linux you'd want:
```
curl -L https://github.com/marbl/canu/releases/download/v2.2/canu-2.2.Linux-amd64.tar.xz --output canu-2.2.Linux.tar.xz 
tar -xJf canu-2.2.*.tar.xz
```

**Comment by Narmatha99** [comment]
Thank you for the explanation. I am however working on a Mac Pro, does that mean that Canu is not compatible with MacOS?

**Comment by skoren** [comment]
OSX is Darwin so you should download the Darwin tarball. Since it's compiled for x86 architectures if you have apple silicon you'll need to have rosetta (https://support.apple.com/en-us/102527) which it should automatically install when you run canu. You'll also need the other requirements for running canu listed on the release notes page:
```
Perl 5.12.0, or File::Path 2.08
Java SE 8
```

**Comment by Narmatha99** [comment]
I was able to download Canu, thank you very much! But I have come to the next problem (which is my estimation mistake I think). 

`(base) dagobert@Mac-Pro-van-Dagobert ~ % ~/Downloads/canu-2.2/bin/canu -d barcode1_canu -p pseaer genomeSize=6.3m -nanopore ~/Downloads/QIA_test_fastq/Long_read_barcode_1.fastq.gz
-- canu 2.2
--
-- CITATIONS
--
-- For 'standard' assemblies of PacBio or Nanopore reads:
--   Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
--   Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
--   Genome Res. 2017 May;27(5):722-736.
--   http://doi.org/10.1101/gr.215087.116
-- 
-- Read and contig alignments during correction and consensus use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '22.0.1' (from 'java') without -d64 support.
--
-- WARNING:
-- WARNING:  Failed to run gnuplot using command 'gnuplot'.
-- WARNING:  Plots will be disabled.
-- WARNING:
--
--
-- Detected 24 CPUs and 192 gigabytes of memory on the local machine.
--
-- Local machine mode enabled; grid support not detected or not allowed.
--
--                                (tag)Concurrency
--                         (tag)Threads          |
--                (tag)Memory         |          |
--        (tag)             |         |          |       total usage      algorithm
--        -------  ----------  --------   --------  --------------------  -----------------------------
-- Local: meryl     12.000 GB    4 CPUs x   6 jobs    72.000 GB  24 CPUs  (k-mer counting)
-- Local: hap        8.000 GB    4 CPUs x   6 jobs    48.000 GB  24 CPUs  (read-to-haplotype assignment)
-- Local: cormhap    6.000 GB   12 CPUs x   2 jobs    12.000 GB  24 CPUs  (overlap detection with mhap)
-- Local: obtovl     4.000 GB    8 CPUs x   3 jobs    12.000 GB  24 CPUs  (overlap detection)
-- Local: utgovl     4.000 GB    8 CPUs x   3 jobs    12.000 GB  24 CPUs  (overlap detection)
-- Local: cor        -.--- GB    4 CPUs x   - jobs     -.--- GB   - CPUs  (read correction)
-- Local: ovb        4.000 GB    1 CPU  x  24 jobs    96.000 GB  24 CPUs  (overlap store bucketizer)
-- Local: ovs        8.000 GB    1 CPU  x  24 jobs   192.000 GB  24 CPUs  (overlap store sorting)
-- Local: red       16.000 GB    4 CPUs x   6 jobs    96.000 GB  24 CPUs  (read error detection)
-- Local: oea        8.000 GB    1 CPU  x  24 jobs   192.000 GB  24 CPUs  (overlap error adjustment)
-- Local: bat       16.000 GB    4 CPUs x   1 job     16.000 GB   4 CPUs  (contig construction with bogart)
-- Local: cns        -.--- GB    4 CPUs x   - jobs     -.--- GB   - CPUs  (consensus)
--
-- Found untrimmed raw Nanopore reads in the input files.
--
-- Generating assembly 'pseaer' in '/Users/dagobert/barcode1_canu':
--   genomeSize:
--     6300000
--
--   Overlap Generation Limits:
--     corOvlErrorRate 0.3200 ( 32.00%)
--     obtOvlErrorRate 0.1200 ( 12.00%)
--     utgOvlErrorRate 0.1200 ( 12.00%)
--
--   Overlap Processing Limits:
--     corErrorRate    0.3000 ( 30.00%)
--     obtErrorRate    0.1200 ( 12.00%)
--     utgErrorRate    0.1200 ( 12.00%)
--     cnsErrorRate    0.2000 ( 20.00%)
--
--   Stages to run:
--     correct raw reads.
--     trim corrected reads.
--     assemble corrected and trimmed reads.
--
--
-- BEGIN CORRECTION
----------------------------------------
-- Starting command on Wed Jun 26 09:42:24 2024 with 7397.341 GB free disk space

    cd .
    ./pseaer.seqStore.sh \
    > ./pseaer.seqStore.err 2>&1

-- Finished on Wed Jun 26 09:42:25 2024 (one second) with 7397.341 GB free disk space
----------------------------------------
--
-- ERROR:  Read coverage (0) lower than allowed.
-- ERROR:    minInputCoverage  = 10
-- ERROR:
-- ERROR:  This could be caused by an incorrect genomeSize.
-- ERROR:
-- ERROR:  You can force Canu to continue by decreasing parameter
-- ERROR:  minInputCoverage.  Be warned that the quality of corrected
-- ERROR:  reads and/or contiguity of contigs will be poor.
--

ABORT:
ABORT: canu 2.2
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:`

So if I understand correctly the problem is my genome size in this? How should I estimate the genome size? I know already what bacteria it is (pseudomonas aeruginosa) and I googled the haploid genome size of what I (probably) assembled (5.5 - 7 Mbp). I also tried it with 5.5 Mbp but I got the same error about incorrect genomeSize.

**Comment by Narmatha99** [comment]
I was able to download Canu, thank you very much! But I have come to the next problem (which is my estimation mistake I think). 
I used the following command: ~/Downloads/canu-2.2/bin/canu -d barcode1 -p pseaer genomeSize=5.5m -nanopore ~/Downloads/QIA_test_fastq/Long_read_barcode_1.fastq.gz

And got this error:
![Scherm­afbeelding 2024-06-26 om 09 58 29](https://github.com/marbl/canu/assets/96242285/00033969-e728-432e-8256-cbd4a6377ae1)

So if I understand correctly the problem is my genome size in this? How should I estimate the genome size? I know already what bacteria it is (pseudomonas aeruginosa) and I googled the haploid genome size of what I (probably) assembled (5.5 - 7 Mbp). I also tried it with 5.5 Mbp but I got the same error about incorrect genomeSize.

**Comment by skoren** [comment]
The issue is you don't have enough input to assemble the genome. The genome size should be approximately what you expect the assembly to be. What is the input set you're using, how many reads/bases?

**Comment by Narmatha99** [comment]
Ah okay, so my input is a library of 8 samples pooled together but each one with a barcode (ONT + rapid barcoding kit). I did basecalling through the terminal with Dorado so now I have bam and fastq files. I am not sure how I would check the number of reads/bases because I did basecalling outside the usual nanopore software.

**Comment by skoren** [comment]
canu would put that info in the report file, you can also check the info in the pseaer.seqStore/info.txt. Post that file here.

**Comment by Narmatha99** [comment]
![Scherm­afbeelding 2024-07-08 om 14 55 42](https://github.com/marbl/canu/assets/96242285/6e97b13e-03bf-4ea9-8273-ab91253317d1)
So I tried it again with a Citrobacter Freundii but again I get the error message. I have added the info.txt underneath. 

     Reads        Bases Read Type
---------- ------------ ----------------------------------------
         0            - total-reads
         0            0 raw
         0            0 raw-trimmed
         0            0 raw-compressed
         0            0 raw-compressed-trimmed
         0            0 corrected
         0            0 corrected-trimmed
         0            0 corrected-compressed
         0            0 corrected-compressed-trimmed

**Comment by Narmatha99** [comment]
And the canu_asm.seqStore.sh:

#!/bin/sh


#  Path to Canu.

bin="/Users/dagobert/Downloads/canu-2.2/bin"

#  Report paths.

echo ""
echo "Found perl:"
echo "  " `which perl`
echo "  " `perl --version | grep version`
echo ""
echo "Found java:"
echo "  " `which java`
echo "  " `java -showversion 2>&1 | head -n 1`
echo ""
echo "Found canu:"
echo "  " $bin/canu
echo "  " `$bin/canu -version`
echo ""


#  Environment for any object storage.

export CANU_OBJECT_STORE_CLIENT=
export CANU_OBJECT_STORE_CLIENT_UA=
export CANU_OBJECT_STORE_CLIENT_DA=
export CANU_OBJECT_STORE_NAMESPACE=
export CANU_OBJECT_STORE_PROJECT=





/Users/dagobert/Downloads/canu-2.2/bin/sqStoreCreate \
  -o ./canu_asm.seqStore.BUILDING \
  -minlength 1000 \
  -genomesize 4300000 \
  -coverage   200 \
  -bias       0 \
  -raw -nanopore Long_reads_barcode_17 /Users/dagobert/Downloads/QIA_test_030724/QIA_fastq/Long_reads_barcode_17.fastq.gz \
&& \
mv ./canu_asm.seqStore.BUILDING ./canu_asm.seqStore \
&& \
exit 0

exit 1

**Comment by skoren** [comment]
According to the log there are no reads in the input files, are all the reads shorter than 1kb? Can you post the `canu_asm.seqStore.err` file as well as one of the fastq.gz sets (see https://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you if it's too big for GitHub).

**Comment by Narmatha99** [comment]
I send them through FTP. Can you let me know if you are able to download both files?

**Comment by skoren** [comment]
Unfortunately I don't see the files on the FTP site, are you able to send them another way?

**Comment by skoren** [comment]
Idle, no input reads, likely due to minimum length thresholds.
