### ISSUE TITLE
Failed to submit compute jobs

### ISSUE THREAD

**Issue by car0053** [marbl/canu#2329]
I am trying to assemble a chloroplast genome and I am unsure how to work around my Slurm system to get this to work. I have tried running this as a script and on it's own and each time I get this error and I am unsure how to resolve the issue. No matter what I try, it ends with an sbatch error whether I am running canu as a script or directly. 

canu -assemble -p Dig_isch_chl genomeSize=0.14m -maxMemory=768 -trimmed -pacbio-hifi *.fa

```
-- BEGIN ASSEMBLY
--
-- No change in report.
-- No change in report.
--
-- Running jobs.  First attempt out of 2.
--
-- Failed to submit compute jobs.  Delay 10 seconds and try again.

CRASH:
CRASH: Canu 2.0
CRASH: Please panic, this is abnormal.
CRASH:
CRASH:   Failed to submit compute jobs.
CRASH:
CRASH: Failed at /mmfs1/tools/canu-2.0/bin/../lib/site_perl/canu/Execution.pm line 1275.
CRASH:  canu::Execution::submitOrRunParallelJob("Dig_isch_chl", "meryl", "unitigging/0-mercounts", "meryl-count", 1) called at /mmfs1/tools/canu-2.0/bin/../lib/site_perl/canu/Meryl.pm line 834
CRASH:  canu::Meryl::merylCountCheck("Dig_isch_chl", "utg") called at /tools/canu-2.0/bin/canu line 1053
CRASH: 
CRASH: Last 50 lines of the relevant log file (unitigging/0-mercounts/meryl-count.jobSubmit-01.out):
CRASH:
CRASH: sbatch: error: Batch job submission failed: Access/permission denied
CRASH:
(END)
```

**Comment by skoren** [comment]
Sounds like your cluster isn't set up to allow submission from compute hosts. As explained here: https://canu.readthedocs.io/en/latest/faq.html#my-run-stopped-with-the-error-failed-to-submit-batch-jobs in this case you can run with useGrid=false.

**Comment by brianwalenz** [comment]
To expand, since I had it written already....

Since your genome size is small, you can run without grid support with `useGrid=false`, so something like:
```
#!/bin/sh
canu -assemble -p Dig_isch_chl useGrid=false genomeSize=0.14m -maxMemory=768 -trimmed -pacbio-hifi *.fa
```
then, from the head node, `sbatch the-above-script.sh`.

**Comment by car0053** [comment]
Thank you so much! It is working now.

Claudia Ann Rutland Landrum
***@***.***
Graduate Research Assistant
Crop, Soil, and Environmental Sciences
Auburn University


From: Brian Walenz ***@***.***>
Date: Wednesday, July 17, 2024 at 12:31 PM
To: marbl/canu ***@***.***>
Cc: Claudia Ann Rutland ***@***.***>, Author ***@***.***>
Subject: [EXT] Re: [marbl/canu] Failed to submit compute jobs (Issue #2329)
CAUTION: Email Originated Outside of Auburn.

To expand, since I had it written already....

Since your genome size is small, you can run without grid support with useGrid=false, so something like:

#!/bin/sh

canu -assemble -p Dig_isch_chl useGrid=false genomeSize=0.14m -maxMemory=768 -trimmed -pacbio-hifi *.fa

then, from the head node, sbatch the-above-script.sh.
