### ISSUE TITLE
correction empty

### ISSUE THREAD

**Issue by ishengtsai** [marbl/canu#233]
Hi,

Under LSF environment canu runs successfully at 1-overlapper stage but stopped at 2-correction without submitting more jobs. The files:

Bspecies.ovlStore.summary.err
Bspecies.ovlStore.per-read.log
2-correction/Bspecies.globalScores.err
2-correction/Bspecies.globalScores.log
2-correction/Bspecies.globalScores

all came empty.

Looking at correction/Bspecies.ovlStore/ everything seems to execute successfully:

correction/Bspecies.ovlStore/2-sorter.success
tail correction/Bspecies.ovlStore/logs/3-index.err

![image](https://cloud.githubusercontent.com/assets/5182142/17664602/deeb50a4-6327-11e6-9a69-50296b801ae8.png)

I can't seem to find the reasons behind it. Shall I just restart canu without deleting files? Any suggestions would be appreciated.

**Comment by skoren** [comment]
LSF has had limited testing as we don't have access to a system. Can you post the last two canu.\*.out files (the ones with the greatest numbers). 

If you want to restart Canu, erase the 2-correction folder before you do so it is forced to recreate the globalScores files.

**Comment by ishengtsai** [comment]
Sorry which folder do I find the canu.*.out files?

I restarted Canu without deleting the 2-correction folder. It seems to continue with correctReads.*.out files being executed. But I will restart everything again as some files come out empty:

![image](https://cloud.githubusercontent.com/assets/5182142/17685180/3b9dcbd0-6394-11e6-98ac-ef60eef05036.png)

**Comment by skoren** [comment]
The log files will be under your -d directory canu-scripts/canu.\*.out.

The run with an empty estimate.log will complete and should have corrected reads. You are just essentially skipping the global filtering which is meant to separate repeat copies better during correction so your corrected reads will likely be lower quality but it may or may not affect your assembly.

**Comment by ishengtsai** [comment]
Thanks. Turned out it's a memory issue of running canu.*.sh . Will adjust accordingly.
