### ISSUE TITLE
Undefined subroutine &canu::Report::caExit called" during CANU Assembly

### ISSUE THREAD

**Issue by Pvaskez** [marbl/canu#2334]
Hello! 

I am encountering an issue while running CANU for genome assembly. The process fails with the following error message:
Undefined subroutine &canu::Report::caExit called at /data/canu 2.2/bin/../lib/site_perl/canu/Report.pm line 116.

These are the details of my setup: 
CANU version: 2.2
I am on operating system linux, Ubuntu 20.4
my data type is: pacbio

this is the command I used: 
/data/canu-2.2/bin/canu -p XM_CANU24_045 -d XM_CANU24_045_Folder genomeSize=600m correctedErrorRate=0.045 -pacbio-raw /data/Prickleback_Genomes/R251-A01.1-Reads.fastq useGrid=false -corMinCoverage=4 &

The assembly process begins but fails shortly afterward with the error mentioned above. I’m not sure if this is related to the data type I'm using or if I am doing something incorrect.  I am new to using CANU and bioinformatic tools. 

I've checked my installation, and everything seems correct. If you have any suggestions for resolving this I would greatly appreciate it.

Thank you for your assistance!

**Comment by skoren** [comment]
What do you mean your input is illumina reads? Canu is only designed to handle pacbio or ONT data not short reads. The error line indicates it can't create a file/folder on your system. Are your running it in a location you have write access and space to write to?

**Comment by Pvaskez** [comment]
Hello, I am sorry I meant to write pacbio not illumina reads. I believe I have access to the location but I will make sure to confirm with my professor. This may be the issue that I may have not gotten granted access to this specific location though. Thank you so much for your help I really appreciate it!

**Comment by skoren** [comment]
Idle, seems like an issue with IO permissions and reporting error should also be fixed by commit.
