### ISSUE TITLE
Canu command to only generate corrected reads

### ISSUE THREAD

**Issue by Artifice120** [marbl/canu#2335]
Afternoon,

I would like to use the corrected reads generated by Canu in fasta format so I can then generate a fancy k-mer histogram in genomescope to justify the genome length I used in my canu assembly.

I have a complete canu run already but did not see and human readable read files in the .seqstore or any .bam files.

I remember it was mentioned in the docs that this could be done but was not explained.

**Comment by skoren** [comment]
If you ran the full pipeline, you should have `*correctedReads.fasta.gz` and `*trimmedReads.fasta.gz` in your folder already. The histograms are also in the `*.report` file as well to give you an idea of genome size/k-mer frequencies.

**Comment by Artifice120** [comment]
Thanks, they were in the main folder the whole time.

GenomeScope just has a nicer figure and it does its own genome length prediction as well.
