### ISSUE TITLE
DoesTrobining  work for Pacbio data from other offspring?

### ISSUE THREAD

**Issue by heziqing** [marbl/canu#2336]
Hello everyone,
I have Illumina short reads of parents (F0) and offspring (F1), but no Pacbio long read data of F1. but there is existing long-read data from other offspring, could I also use TroCanu to assemble the haplotype genome?

**Comment by skoren** [comment]
So you have parents (F0) and two siblings (F1_1 and F1_2)? F1_1 has Illumina and no long reads and F1_2 has no illumina and long reads. Is that correct? If so, it should be fine to run the F1_2 long read data with its parents (F0). Canu only takes the mat/pat data to bin the reads, it doesn't require the F1 to have illumina data as well.

**Comment by heziqing** [comment]
Thanks for your reply. I'm sorry I confused you. Let me say it again. I want to perform genotyping on an existing genome for which PacBio data is available. Now I have Illumina short reads of parents (F0) and offspring (F1).  The samples of the PacBio data are not siblings of my current F1 sample. I would like to know if I can use the existing PacBio data, then use the F1 Illumina short reads data to call SNPs on the existing contigs, and then use the parents' short reads data to perform genotype phasing.
