### ISSUE TITLE
[lsf] different files produced at 1-overlapper stage

### ISSUE THREAD

**Issue by ishengtsai** [marbl/canu#234]
Hi,

Under lsf environment the running the exact command :

/home/r07ijt00/bin/canu/Linux-amd64/bin/canu java=/pkg/java/jdk1.8.0_77/bin/java  ovbMemory=10 mhapThreads=8 mhapMemory=15 -p Bspecies -d Bspec-31X corMinCoverage=0 errorRate=0.035  genomeSize=740m -pacbio-raw data.fasta

has returned two sets of files, both stopped for some reason:

run-2 
![image](https://cloud.githubusercontent.com/assets/5182142/17701232/9e31a7f0-63fb-11e6-9a23-47b88972a5b6.png)

![image](https://cloud.githubusercontent.com/assets/5182142/17701268/d3da3e94-63fb-11e6-835b-226c033791ff.png)

run-1 (and much more files present at correction/Bspecies.ovlStore/)
![image](https://cloud.githubusercontent.com/assets/5182142/17701242/aa67d2ce-63fb-11e6-9bb1-0abbb38ea3ab.png)

![image](https://cloud.githubusercontent.com/assets/5182142/17701285/e07983d0-63fb-11e6-9df0-78de67cb7a15.png)

Which directory / log files shall I look for potential reasons for them to stop? By the way canu seems perfectly fine in genomes under <200Mb in our commands.

**Comment by skoren** [comment]
It doesn't look like they stopped for the same reason. One has completed the overlap store building (Bspec-31X) while the other run (Bspec-31X-run2) did not.

You ran the same command twice with a different folder specified for -d or continued a stopped run? The logs in Bspec\*/canu-scripts/canu.\*.out and Bspec\*/correction\*ovlStore/logs/\*.out

**Comment by ishengtsai** [comment]
Yes with -d Bspec-31X and -d Bspec-31X-run2 .

Ah yes I found it.. turned out it's a memory issue, which was not a problem in smaller assemblies. I take 
![image](https://cloud.githubusercontent.com/assets/5182142/17701803/d5bd2cd8-63fd-11e6-967e-3c9389a0165e.png)


I will adjust it accordingly.

**Comment by skoren** [comment]
This seems similar to issue #225 you had earlier. I'm not clear how LSF Is handing memory requests. Is there another flag that needs to be passed that Canu isn't using? From the log above, the job used a max of 7GB and requested 8 so why did it exceed the usage limit?

**Comment by ishengtsai** [comment]
Hi Sergey,

If I remember correctly,  the LSF log will only record Max memory used just when it's about to exceed the requested memory.

LSF has various variations depending on the setup. In our case, the queues that the job goes in is determined to how much threads was requested. In the case of canu.*.sh I believe so far it's always 1. So I am modifying the buildThreadOption in Execution.pm to force everything to request at least 2 threads, and hopefully all the jobs will be submitted to queues with larger available memory settings. 

Let's see how it goes..

Best,
Jason
