### ISSUE TITLE
Make not run make: *** No targets specified and no makefile found.  Stop.

### ISSUE THREAD

**Issue by huybo02** [marbl/canu#2347]
Hello team,
I tried to download and install canu2.2 on colad and Ubuntu
I tried this one: https://canu.readthedocs.io/en/latest/

<code>
git clone https://github.com/marbl/canu.git
cd canu/src
make -j 2
</code>

but it stop with error: 
make: *** No targets specified and no makefile found.  Stop.

Could you please help me resolve this error?
Thanks and Regards!

**Comment by skoren** [comment]
Idle
