### ISSUE TITLE
Canu for shotgun metagenomic assembly of complex environments

### ISSUE THREAD

**Issue by Hedi65** [marbl/canu#2348]
Dear developer,

I found there are inconsistent opinions across experts. Are you suggesting Canu for assembling metagenomic data from complex environments such as wastewater? If so, what settings should I pay attention to while running Canu?

Thanks

**Comment by skoren** [comment]
Yes, canu can work for metagenomic datasets as long as you aren't expecting it to maintain phase/reconstruct complete genomes. For high-accuracy data like HiFi you probably want to look at MetaFlye or Metahifiasm instead. The FAQ lists the settings for metagenomics, which essentially tell canu to correct all the input PacBio CLR or ONT data:https://canu.readthedocs.io/en/latest/faq.html#what-parameters-can-i-tweak
