### ISSUE TITLE
how to allocate number of threats

### ISSUE THREAD

**Issue by yaradua** [marbl/canu#2352]
Hi,

thank you for developing this program. I am trying to use canu2.2 to assemble genome of a plant species using the following command: `./canu -p myassembly -d canu_assembly genomeSize=1.5g -pacbio-hifi /nfs_fs/nfs4/Samaila/project/GingerGenome/SH/HiFi_Hic/HIFI_DATA/ShHIFI.fastq.gz`

I am running the analysis on our HPC and the program has taken over the HPC. 

How can I set the number of threats so that it will not consume the memory of our HPC?

Thank you.
Samaila

**Comment by skoren** [comment]
In general, canu submits array jobs to the grid with appropriate time and memory/CPU requirements, it should be up to the grid scheduler to manage resources and limit concurrent jobs if needed. 

However, depending on which cluster you're on, you can also limit array job concurrency manually: https://canu.readthedocs.io/en/latest/faq.html#how-do-i-run-canu-on-my-slurm-sge-pbs-lsf-torque-system. For example, on SLURM you can use: `gridEngineArrayOption="-a ARRAY_JOBS%4"` which will prevent more than 4 canu processes from running simultaneously.

**Comment by yaradua** [comment]
Dear skoren,

thank you very much, I run it using maximumthreat=32
