### ISSUE TITLE
Advise on the muticontig output

### ISSUE THREAD

**Issue by MonicaSteffi** [marbl/canu#2353]
Dear sir,

I have executed canu for one of my e.faecalis isoltaes.  The genome size is 3.026 Mb. For five of my isolates, I got nice one big contigs. For two of my isolates, I got multiple contigs. I blasted all these contigs against NCBI nucleotide database, couple of them were matched against plasmids, But couple of them matched against different e.faecalis chromosome. 

```
Size (bp) | suggestBubble | suggestrepeat | suggestCircular | class | reads | trim
-- | -- | -- | -- | -- | -- | --
2969815 | no | no | yes | contig | 3860 | 12668-2966609
70485 | no | no | yes | contig | 55 | 8775-54024
62756 | no | no | yes | contig | 64 | 11235-51520
27050 | no | yes | no | contig | 2 | 0-27050
```
I am not sure whether the the contigs 70485, 62756 and 27050 are part of the genome, if so, how to do I merge those genomes together?

**Comment by skoren** [comment]
Contigs 70485 and 62756 both have a good number of reads and are both marked as circular so I suspect these are plasmids. The last contigs, 27050, has only two reads and isn't circular. It's also marked as a bubble so I suspect this is a low-frequency variation in the sample you sequenced, it likely should map somewhere in the middle of the larger chromosome sequence but, unless you're trying to track down all variation in your sample, you can probably ignore it.

**Comment by MonicaSteffi** [comment]
Thank you so much for the quick reply. That makes sense. Als,o 27050 is marked as suggestrepeat not bubble (sorry for the poor formatting). In that case, I can ignore it too right

**Comment by skoren** [comment]
Ah yeah you're right, I didn't notice that. Are these all the contigs you have in the assembly? I think it would be safe to ignore, yes, as the largest chromosome contig is also circular. I still suspect it's a low-frequency variant.

**Comment by MonicaSteffi** [comment]
```
Size (bp) | suggestBubble | suggestrepeat | suggestCircular | class    | reads | trim
2969815 | no                     | no                     | yes                   | contig | 3860   | 12668-2966609
78009     | no                     | no                     | yes                   | contig | 68       | 9102-65684
70485     | no                     | no                     | yes                   | contig | 55       | 8775-54024
67048     | no                     | no                     | yes                   | contig | 18       | 0-67048
62756     | no                     | no                     | yes                   | contig | 64       | 11235-51520
27050    | no                      | yes                    | no                    | contig | 2         | 0-27050
```

I got 6 contigs in total. Among them 78009 and 67048 got 100% match with plasmid sequences when I performed Blast. Since we are also interested in detecting variants, Ill include for further analysis.
