### ISSUE TITLE
gzip: stdout: Disk quota exceeded   \   slurmstepd:  Exceeded job memory limit at some point.

### ISSUE THREAD

**Issue by hermeseduardo** [marbl/canu#237]
Hi there, I ran into some issues while running mhap, the precompute looks OK, any suggestion? bellow the mhap*.out

HE

mhap.229165_10.out:
Running block 000003 in query 000006
Picked up _JAVA_OPTIONS: -XX:+UseSerialGC
Running with these settings:
--filter-threshold = 5.0E-6
--help = false
--max-shift = 0.2
--min-olap-length = 116
--min-store-length = 0
--no-self = false
--no-tf = false
--num-hashes = 768
--num-min-matches = 2
--num-threads = 10
--ordered-kmer-size = 12
--ordered-sketch-size = 1536
--repeat-weight = 0.9
--settings = 0
--store-full-id = false
--supress-noise = 0
--threshold = 0.73
--version = false
-f = /flush1/esc003/Cynegetis_genome_transcriptome/Cynegetis_impunctata_WORKING_FOLDER/canu_assembly/Cynegetis-complete/correction/0-mercounts/Cynegetis_complete.ms16.frequentMers.ignore.gz
-h = false
-k = 16
-p = 
-q = /flush1/esc003/Cynegetis_genome_transcriptome/Cynegetis_impunctata_WORKING_FOLDER/canu_assembly/Cynegetis-complete/correction/1-overlapper/queries/000006
-s = /flush1/esc003/Cynegetis_genome_transcriptome/Cynegetis_impunctata_WORKING_FOLDER/canu_assembly/Cynegetis-complete/correction/1-overlapper/blocks/000003.dat

Reading in filter file /flush1/esc003/Cynegetis_genome_transcriptome/Cynegetis_impunctata_WORKING_FOLDER/canu_assembly/Cynegetis-complete/correction/0-mercounts/Cynegetis_complete.ms16.frequentMers.ignore.gz.
Time (s) to read filter file: 0.13107088
Read in k-mer filter for sizes: [16]
Processing files for storage in reverse index...
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
Current # sequences loaded and processed from file: 40000...
Current # sequences loaded and processed from file: 45000...
Current # sequences loaded and processed from file: 50000...
Current # sequences loaded and processed from file: 55000...
Current # sequences loaded and processed from file: 60000...
Current # sequences loaded and processed from file: 65000...
Current # sequences loaded and processed from file: 70000...
Current # sequences loaded and processed from file: 75000...
Current # sequences loaded and processed from file: 80000...
Current # sequences loaded and processed from file: 85000...
Current # sequences loaded and processed from file: 90000...
Current # sequences loaded and processed from file: 95000...
Current # sequences loaded and processed from file: 100000...
Current # sequences loaded and processed from file: 105000...
Current # sequences loaded and processed from file: 110000...
Current # sequences loaded and processed from file: 115000...
Current # sequences loaded and processed from file: 120000...
Current # sequences loaded and processed from file: 125000...
Current # sequences loaded and processed from file: 130000...
Current # sequences loaded and processed from file: 135000...
Current # sequences loaded and processed from file: 140000...
Current # sequences loaded and processed from file: 145000...
Current # sequences loaded and processed from file: 150000...
Current # sequences loaded and processed from file: 155000...
Current # sequences loaded and processed from file: 160000...
Current # sequences loaded and processed from file: 165000...
Current # sequences stored: 5000...
Current # sequences stored: 10000...
Current # sequences stored: 15000...
Current # sequences stored: 20000...
Current # sequences stored: 25000...
Current # sequences stored: 30000...
Current # sequences stored: 35000...
Current # sequences stored: 40000...
Current # sequences stored: 45000...
Current # sequences stored: 50000...
Current # sequences stored: 55000...
Current # sequences stored: 60000...
Current # sequences stored: 65000...
Current # sequences stored: 70000...
Current # sequences stored: 75000...
Current # sequences stored: 80000...
Current # sequences stored: 85000...
Current # sequences stored: 90000...
Current # sequences stored: 95000...
Current # sequences stored: 100000...
Current # sequences stored: 105000...
Current # sequences stored: 110000...
Current # sequences stored: 115000...
Current # sequences stored: 120000...
Current # sequences stored: 125000...
Current # sequences stored: 130000...
Current # sequences stored: 135000...
Current # sequences stored: 140000...
Current # sequences stored: 145000...
Current # sequences stored: 150000...
Current # sequences stored: 155000...
Current # sequences stored: 160000...
Current # sequences stored: 165000...
Stored 165000 sequences in the index.
Processed 165000 unique sequences (fwd and rev).
Time (s) to read and hash from file: 88.458012194
Time (s) to score and output to self: 4752.058701049
Opened fasta file /flush1/esc003/Cynegetis_genome_transcriptome/Cynegetis_impunctata_WORKING_FOLDER/canu_assembly/Cynegetis-complete/correction/1-overlapper/blocks/000004.dat.
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
Current # sequences loaded and processed from file: 40000...
Current # sequences loaded and processed from file: 45000...
Current # sequences loaded and processed from file: 50000...
Current # sequences loaded and processed from file: 55000...
Current # sequences loaded and processed from file: 60000...
Current # sequences loaded and processed from file: 65000...
Current # sequences loaded and processed from file: 70000...
Current # sequences loaded and processed from file: 75000...
Current # sequences loaded and processed from file: 80000...
Processed 82500 to sequences.
Time (s) to score, hash to-file, and output: 9006.381839581001
Opened fasta file /flush1/esc003/Cynegetis_genome_transcriptome/Cynegetis_impunctata_WORKING_FOLDER/canu_assembly/Cynegetis-complete/correction/1-overlapper/blocks/000005.dat.
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
Current # sequences loaded and processed from file: 40000...
Current # sequences loaded and processed from file: 45000...
Current # sequences loaded and processed from file: 50000...
Current # sequences loaded and processed from file: 55000...
Current # sequences loaded and processed from file: 60000...
Current # sequences loaded and processed from file: 65000...
Current # sequences loaded and processed from file: 70000...
Current # sequences loaded and processed from file: 75000...
Current # sequences loaded and processed from file: 80000...
Processed 82500 to sequences.
Time (s) to score, hash to-file, and output: 9487.53588757
Total scoring time (s): 23246.012313047002
Total time (s): 23334.470375489
MinHash search time (s): 6488.403775832
Total matches found: 1491753232
Average number of matches per lookup: 6027.285785858586
Average number of table elements processed per lookup: 59279.971438383836
Average number of table elements processed per match: 9.835268069994033
Average % of hashed sequences hit per lookup: 21.894370385062746
Average % of hashed sequences hit that are matches: 16.68419969167093
Average % of hashed sequences fully compared that are matches: 50.45109665988456

gzip: stdout: Disk quota exceeded
slurmstepd: Exceeded step memory limit at some point.
slurmstepd: Exceeded job memory limit at some point.

**Comment by brianwalenz** [comment]
Find more disk space?

If you have a LOT of input coverage, you can filter out the very short reads with option minReadLength.  These won't add anything to the assembly and will eat up disk space.  Check the histograms in correction.html.  Gains in assembly are minimal after about 50x of input coverage.

**Comment by hermeseduardo** [comment]
Hey Brian, in my case the coverage is low, about 10X.

**Comment by brianwalenz** [comment]
Are you out of disk, or is the output of this enormous?  If it is enormous, I'd check for a contaminant.

**Comment by hermeseduardo** [comment]
Hi, the disk does not seems to be a problem anymore after deleting some old files, but some Segmentation fault shoed up and this: canu failed with 'failed to compute mhap overlaps.  Made 2 attempts, jobs still failed'. I got this same message in previous runs, Any suggestions?

my script: canu -correct -gridOptions="--time=20:00:00" saveOverlaps=true corMinCoverage=0 -p Cynegetis_complete -d Cynegetis genomeSize=1g -pacbio-raw /flush1/esc003/Cynegetis_genome_transcriptome/Cynegetis_impunctata_WORKING_FOLDER/PacBio_fastq/*.fastq

the output indicating the segmentation fault:

Running block 000010 in query 000027
/cm/local/apps/slurm/var/spool/job350710/slurm_script: line 305: 12913 Segmentation fault      $bin/mhapConvert $cvt -o /flush1/esc003/Cynegetis_genome_transcriptome/Cynegetis_impunctata_WORKING_FOLDER/canu_assembly/Cynegetis/correction/1-overlapper/results/$qry.mhap.ovb.WORKING.gz /flush1/esc003/Cynegetis_genome_transcriptome/Cynegetis_impunctata_WORKING_FOLDER/canu_assembly/Cynegetis/correction/1-overlapper/results/$qry.mhap

**Comment by hermeseduardo** [comment]
looks like this line (305) in mhap.sh  is generating the segmentation fault:

fi
if [ -e "/flush1/esc003/Cynegetis_genome_transcriptome/Cynegetis_impunctata_WORKING_FOLDER/canu_assembly/Cynegetis/correction/1-overlapper/results/$qry.mhap.ovb.gz" ] ; then
  mv -f "/flush1/esc003/Cynegetis_genome_transcriptome/Cynegetis_impunctata_WORKING_FOLDER/canu_assembly/Cynegetis/correction/1-overlapper/results/$qry.mhap.ovb.gz" "/flush1/esc003/Cynegetis_genome_transcriptome/Cynegetis_impunctata_WORKING_FOLDER/canu_assembly/Cynegetis/correction/1-overlapper/results/$qry.ovb.gz"
fi

here the ouput from mhap:

Running block 000003 in query 000011
/flush1/esc003/Cynegetis_genome_transcriptome/Cynegetis_impunctata_WORKING_FOLDER/canu_assembly/Cynegetis/correction/1-overlapper/mhap.sh: line 305: 134487 Segmentation fault      $bin/mhapConvert $cvt -o /flush1/esc003/Cynegetis_genome_transcriptome/Cynegetis_impunctata_WORKING_FOLDER/canu_assembly/Cynegetis/correction/1-overlapper/results/$qry.mhap.ovb.WORKING.gz /flush1/esc003/Cynegetis_genome_transcriptome/Cynegetis_impunctata_WORKING_FOLDER/canu_assembly/Cynegetis/correction/1-overlapper/results/$qry.mhap

**Comment by brianwalenz** [comment]
I'm going to guess that the mhap output (in the *mhap files) is truncated.  You can check this by just looking at the last handful of lines of those files: `tail -n 5 *mhap`.  They should all be about the same length with the same number of columns.

The safest fix is to delete everything in the results/ folder and restart.  I've had terrible luck resuming assemblies after running out of disk.

**Comment by hermeseduardo** [comment]
I'm going to guess that the mhap output (in the *mhap files) is truncated
**YES IT WAS!!**

I made it run to the end disabling the grid.
