### ISSUE TITLE
unitigger ; bogart Segmentation fault 

### ISSUE THREAD

**Issue by ishengtsai** [marbl/canu#238]
Hi,

The assembly runs everything smoothly until the unitigging stage and failed when bogart gave a segmentation fault:

bsub -M 41 -n 16 -q 48cpu    \
        -J "bat_Bspecies[1-1]" \
        -o Bspec-31X/unitigging/4-unitigger/unitigger.%I.out \
        Bspec-31X/unitigging/4-unitigger/unitigger.sh 0

![image](https://cloud.githubusercontent.com/assets/5182142/17811926/7cc0926c-6657-11e6-8b72-d7cafac7e684.png)

Maybe this issue can be solved if I increase the memory, but which parameter controls this particular stage? utgmhap, utgovl or utgmmap? (Of course I can bsub with different -M, but would like to understand the pipeline in more details). 

I think I am very close... any suggestion is very appreciated.

J

**Comment by ishengtsai** [comment]
An update. Bogart sill fails after setting -M 100. Here's the unitigger.err.txt attached. 


[unitigger.err.txt](https://github.com/marbl/canu/files/428080/unitigger.err.txt)

**Comment by brianwalenz** [comment]
Can you give the just updated code a try?

It's not a lack of memory problem, but you're looking for batMemory.  Generally speaking, bogart isn't a huge process.  Yours should run in 16gb even though it was originally requesting 41g.

**Comment by ishengtsai** [comment]
Updated the code and worked like a charm. Everything else worked smoothly and I got my first assembly of this plant species! Many thanks.
