### ISSUE TITLE
/correction/genome.ovlStore/info file missing

### ISSUE THREAD

**Issue by dcopetti** [marbl/canu#239]
Hello,
A Canu assembler stopped at this point:

```
-- WARNING: failed to generate statistics for the overlap store; no summary will appear in HTML output.
-- Overlap store '/rsgrps/rwing/canu_assemblies/cucumber/11kb/correction/cuc11.ovlStore' statistics not available.
```

but that folder exists

```
-rw-r--r--  1 dcopetti oge 252 Aug 17 18:17 cuc11.gkpStore.gkp
-rw-r--r--  1 dcopetti oge 642 Aug 17 18:24 cuc11.gkpStore.err
drwxr-sr-x  2 dcopetti oge 32K Aug 17 18:24 cuc11.gkpStore
drwxr-sr-x  2 dcopetti oge 32K Aug 17 18:54 0-mercounts
drwxr-sr-x 95 dcopetti oge 32K Aug 19 01:40 cuc11.ovlStore
drwxr-sr-x  2 dcopetti oge 32K Aug 19 01:40 1-overlapper
-rw-r--r--  1 dcopetti oge 242 Aug 19 01:40 cuc11.ovlStore.summary.err
drwxr-sr-x  2 dcopetti oge 32K Aug 19 01:40 2-correction
```

and contains .ovs files, .index, .info, config, config.err, 1-bucketize.success, bucket1234 folders. Then I see:

```
-- Starting command on Fri Aug 19 03:40:44 2016 with 12506.894 GB free disk space

    /gsfs1/rsgrps/rwing/src/canu/Linux-amd64/bin/filterCorrectionOverlaps \
      -G /rsgrps/rwing/canu_assemblies/cucumber/11kb/correction/cuc11.gkpStore \
      -O /rsgrps/rwing/canu_assemblies/cucumber/11kb/correction/cuc11.ovlStore \
      -S /rsgrps/rwing/canu_assemblies/cucumber/11kb/correction/2-correction/cuc11.globalScores \
      -c 40 \
      -l 0 \
    > /rsgrps/rwing/canu_assemblies/cucumber/11kb/correction/2-correction/cuc11.globalScores.err 2>&1

-- Finished on Fri Aug 19 03:40:45 2016 (1 second) with 12506.894 GB free disk space
ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.
Last 50 lines of the relevant log file (/rsgrps/rwing/canu_assemblies/cucumber/11kb/correction/2-correction/cuc11.globalScores.err):

ERROR: directory '/rsgrps/rwing/canu_assemblies/cucumber/11kb/correction/cuc11.ovlStore' is not an overlapStore; failed to open info file '/rsgrps/rwing/canu_assemblies/cucumber/11kb/correction/cuc11.ovlStore/info': No such file or directory

canu failed with 'failed to globally filter overlaps for correction'.
```

and the /.../2-correction/cuc11.globalScores.err says:
`ERROR: directory '/rsgrps/rwing/canu_assemblies/cucumber/11kb/correction/cuc11.ovlStore' is not an overlapStore; failed to open info file '/rsgrps/rwing/canu_assemblies/cucumber/11kb/correction/cuc11.ovlStore/info': No such file or directory`
and in fact there is no info file in there. Any reason why this did not appear?

I am running Canu v1.3 (+60 commits) r7676 2c2bb9a1295b2cd2dcd0e45baf9dd7824037dc32
the command was `/rsgrps/rwing/bin/canu -d /rsgrps/rwing/canu_assemblies/cucumber/11kb -p cuc11 genomeSize=400m minOverlapLength=300 corMinCoverage=4 gridOptions="-M dcopetti@email.arizona.edu -m bea -W group_list=oge -q standard -l jobtype=large_mpi -l select=12:ncpus=12:mem=23GB -l walltime=240:00:00" -pacbio-raw /rsgrps/rwing/canu_assemblies/cucumber/cucumber_all_subreads_input.fa`
Thanks

**Comment by brianwalenz** [comment]
Sounds like the overlap store creating failed, and wasn't detected.

What's the `ls -lR` of the ovlStore?  This will be big, so please attach as a file.

Are there errors in the ovlStore/logs/ directory?

**Comment by dcopetti** [comment]
Here attached are the two files, the .err file in the /logs/ dir says
```
ERROR: Segment 1 data not present  (/rsgrps/rwing/canu_assemblies/cucumber/11kb/correction/cuc11.ovlStore.BUILDING/0001)
ERROR: Segment 1 info not present (/rsgrps/rwing/canu_assemblies/cucumber/11kb/correction/cuc11.ovlStore.BUILDING/0001.info)
ERROR: Segment 1 index not present (/rsgrps/rwing/canu_assemblies/cucumber/11kb/correction/cuc11.ovlStore.BUILDING/0001.index)
ERROR: Segment 2 data not present  (/rsgrps/rwing/canu_assemblies/cucumber/11kb/correction/cuc11.ovlStore.BUILDING/0002)

[3-index.err.tar.gz](https://github.com/marbl/canu/files/429134/3-index.err.tar.gz)
[ovlStore_ls.tar.gz](https://github.com/marbl/canu/files/429135/ovlStore_ls.tar.gz)

```
thanks

**Comment by brianwalenz** [comment]
Weird.  And bad.

The bad is that canu thinks it created the overlap store, and so deleted the 'raw' inputs and outputs of overlapper (in 1-overlapper/blocks and 1-overlapper/results).  However, it didn't create the store.  Which means you'll need to recompute overlaps.

Before we cleanup and restart:

Please send the 11kb/canu-scripts directory and the cuc11.ovlStore/logs directory.  I'm most interested in what canu reported (in canu-scripts/*out) and what errors are reported by the sort phase of overlap store creation (in cuc11.ovlStore/logs/2-*out).

Are there files in correction/1-overlapper/results/?  I suspect there are none.

I'd suggest deleting 1-overlapper -- even if you have results in it -- and cuc11.ovlStore before restarting.  This means you'll have to recompute overlaps (both the 'precompute' and the actual 'mhap' steps).  But something weird happened, and it's usually safer, easier and quicker to just erase and start over, instead of trying to figure out which files are good and which are bad.

Set option saveOverlaps=true before restarting.  This will save all the 1-overlapper files even after the store is built.  If it breaks again, you won't need to recompute overlaps again.  If it works, it is easy to manually clean up to reclaim disk space.

**Comment by dcopetti** [comment]
Here are the two scripts and the /logs dir. 
One of the correction/cuc11.ovlStore/logs/2-sortNNN.out files says:
```
Overlaps need 3.65 GB memory, allowed to use up to (via -M) 4 GB.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Failed with 'Aborted'
```
and the last line:
`/rsgrps/rwing/canu_assemblies/cucumber/11kb/correction/cuc11.ovlStore.BUILDING/scripts/2-sort.sh: line 78: 19322 Aborted                 $bin/ovStoreSorter -deletelate -M 4 -O /rsgrps/rwing/canu_assemblies/cucumber/11kb/correction/cuc11.ovlStore.BUILDING -G /rsgrps/rwing/canu_assemblies/cucumber/11kb/correction/cuc11.gkpStore -F 138 -job $jobid 91`

There is no correction/1-overlapper/results/ folder, in 1-overlapper there are mhap.sh, partitioning.log, partitioning.log, mhap.NNN.out and precompute.NNN.out files.

I can wait restarting after I hear from you based on these files,
thanks

[canu.01.sh.txt](https://github.com/marbl/canu/files/430911/canu.01.sh.txt)

[canu.01.out.txt](https://github.com/marbl/canu/files/430912/canu.01.out.txt)
[logs.tar.gz](https://github.com/marbl/canu/files/430913/logs.tar.gz)

**Comment by brianwalenz** [comment]
Sorry for the delay.

We made a bunch of changes to the overlap output file and the store building process.  So, go ahead and update to the latest code and restart.  You can either restart entirely from scratch, or just cleanup the 1-overlapper and *ovlStore directories/files.

**Comment by brianwalenz** [comment]
Idle.
