### ISSUE TITLE
"failed to generate mer counts"

### ISSUE THREAD

**Issue by RyanHMiller** [marbl/canu#24]
Hi,

Thank you for your great work on canu. I am trying to assemble PacBio reads but am running into some trouble and was wondering if you could give any insight as to what could be going wrong. Thanks in advance!

This is the command I used:

    export PATH="/path/to/jre1.8.0_66/bin/:$PATH"
    export JAVA_HOME="//path/to/jre1.8.0_66"

    #correct, trim, assemble with one command
    ~/path/to/canu/Linux-amd64/bin/canu \
        gridOptions='--time=72:00:00 --mail-user=@gmail.com --mail-type=BEGIN --mail-type=END --mail-type=FAIL' \
        -p human_assembled_pacbio -d human_assembled_pacbio \
        genomeSize=3.3g \
        -pacbio-raw ~/path/to/reads.fastq

In the "canu-scripts" directory that is created, there is "canu.01.out",  "canu.02.out", and " "canu.03.out".

canu.01.out shows: 

    131 -- MERYL (correction)
    132 -- Meryl attempt 1 begins.
    133 --
    134 -- Starting command on Wed Jan  6 18:45:30 2016 with 583697.3 GB free disk space
    135 --
    136   sbatch \
    137     --time=72:00:00 --mail-user=myemail --mail-type=BEGIN --mail-type=END --mail-type=FAIL  --mem=64g --cpus-per-task=24 \
    138     -D `pwd` -J "meryl_human_assembled_pacbio" \
    139     -a 1-1 \
    140     -o /path/to/human_assembled_pacbio/correction/0-mercounts/meryl.%A_%a.out \
    141     path/to/human_assembled_pacbio/correction/0-mercounts/meryl.sh
    142
    143 Submitted batch job 9234744
    144 --
    145 -- Finished on Wed Jan  6 18:45:30 2016 (0 seconds) with 583697.3 GB free disk space
    146 --
    147 -- Starting command on Wed Jan  6 18:45:31 2016 with 583697.3 GB free disk space
    148 --
    149 sbatch \
    150   --mem=12g \
    151   --cpus-per-task=1 \
    152   --time=72:00:00 \
    153   --mail-user=myemail \
    154   --mail-type=BEGIN \
    155   --mail-type=END \
    156   --mail-type=FAIL  \
    157   --depend=afterany:9234744 \
    158   -D `pwd` \
    159   -J "canu_human_assembled_pacbio" \
    160   -o /path/to/human_assembled_pacbio/canu-scripts/canu.02.out 
    161 Submitted batch job 9234745
    162 --
    163 -- Finished on Wed Jan  6 18:45:31 2016 (0 seconds) with 583697.3 GB free disk space
    164 slurmstepd: Exceeded step memory limit at some point.
    165 slurmstepd: Exceeded job memory limit at some point.

canu.02.out shows:

```
118 -- MERYL (correction)
119 --
120 -- meryl failed.
121 --
122 -- Meryl attempt 2 begins.
123 --
124 -- Starting command on Wed Jan  6 20:50:31 2016 with 583655.8 GB free disk space
125 --
126   sbatch \
127     --time=72:00:00 --mail-user=myemail --mail-type=BEGIN --mail-type=END --mail-type=FAIL  --mem=64g --cpus-per-task=24 \
128     -D `pwd` -J "meryl_human_assembled_pacbio" \
129     -a 1-1 \
130     -o /path/to/correction/0-mercounts/meryl.%A_%a.out \
131     /path/to/correction/0-mercounts/meryl.sh
132
133 Submitted batch job 9235177
134 --
135 -- Finished on Wed Jan  6 20:50:31 2016 (0 seconds) with 583655.8 GB free disk space
136 --
137 -- Starting command on Wed Jan  6 20:50:32 2016 with 583655.8 GB free disk space
138 --
139 sbatch \
140   --mem=12g \
141   --cpus-per-task=1 \
142   --time=72:00:00 \
143   --mail-user=myemail \
144   --mail-type=BEGIN \
145   --mail-type=END \
146   --mail-type=FAIL  \
147   --depend=afterany:9235177 \
148   -D `pwd` \
149   -J "canu_human_assembled_pacbio" \
150   -o /path/to/canu-scripts/canu.03.out /path/to
151 Submitted batch job 9235178
152 --
153 -- Finished on Wed Jan  6 20:50:32 2016 (0 seconds) with 583655.8 GB free disk space118 -- 
```

and canu.03.out shows:

```
118 -- MERYL (correction)
119 --
120 -- meryl failed.
121 --
122 ================================================================================
123 Don't panic, but a mostly harmless error occurred and canu failed.
124
125 canu failed with 'failed to generate mer counts.  Made 2 attempts, jobs still failed'.
```

Thanks so much!

**Comment by JohnUrban** [comment]
While waiting for the authors to respond maybe I can help because I have encountered this. It looks like you have Slurm and that Canu is not asking for enough memory for the first meryl job.

Look in the file meryl.jobSubmit.sh: 
$ less assembly-dir/correction/0-mercounts/meryl.jobSubmit.sh

See how much memory it is asking for - then ask for more when you re-submit the Canu job (edit your command by adding merylMemory=X at the end):
~/fsl_groups/fslg_RidgeLabRes/compute/tools/canu/Linux-amd64/bin/canu \
    gridOptions='--time=72:00:00 --mail-user=@gmail.com --mail-type=BEGIN --mail-type=END --mail-type=FAIL' \
    -p human_assembled_pacbio -d human_assembled_pacbio \
    genomeSize=3.3g \
    -pacbio-raw ~/fsl_groups/fslg_RidgeLabRes/compute/references/PacBio_human_54x/CHM1htert_all_reads.fastq \
 merylMemory=X

…where X is in Gb.

**Comment by RyanHMiller** [comment]
@JohnUrban Thanks so much for the insight. I tried that and we'll see how it goes. Thanks!

**Comment by brianwalenz** [comment]
Meryl memory sizing should be fixed now.  I wasn't accounting for extra overhead allocated per thread, and jobs with many threads (you had 24) would blow the memory limit.

Commit 7133228564d8113d08508a30367c0e0c9b6ebb15.
