### ISSUE TITLE
setting ovsMemory leads to error on PBS/Torque 

### ISSUE THREAD

**Issue by roberthaney** [marbl/canu#242]
-I am trying to set the ovsMemory for a PacBio self-correction and assembly run that is dying during overlapStoreBuilding in the correction phase. This is a set of older PacBio RNA-Seq data, with about half the raw reads < 1kb, and I am trying to see what contigs we can get out of it. I have completed a run of a subset of this data with enhanced memory for oea and red. However, increasing ovsMemory from its default as follows-

```
echo canu -d /bigdata/hayashilab/shared/garblab/jgarb/rob/Cdar_silk_gland_assembly/canu/Cd13_02Oct14_03Oct14_Aug2013_all_subreads_canu_mrl300 -p Cd13_02Oct14_03Oct14_Aug2013_all_subreads_canu_mrl300 genomeSize=30.0m minReadLength=300 minOverlapLength=150 ovsMemory=16 oeaMemory=16 oeaThreads=2 redMemory=16 redThreads=2 -pacbio-raw /bigdata/hayashilab/shared/garblab/jgarb/rob/Cdar_silk_gland_assembly/Cd13_pacbio_silk_02Oct14_03Oct14_Aug2013_all_subreads.fastq | qsub -l mem=8gb
```

-produces the following shell script command and error:

```
    qsub \
      -l mem=16-16g \
      -l nodes=1:ppn=1   \
      -W depend=afteranyarray:4120030[].torque.int.bioinfo.ucr.edu \
      -d `pwd` \
      -N "canu_Cd13_02Oct14_03Oct14_Aug2013_all_subreads_canu_mrl300" \
      -j oe \
      -o /bigdata/hayashilab/shared/garblab/jgarb/rob/Cdar_silk_gland_assembly/canu/Cd13_02Oct14_03Oct14_Aug2013_all_subreads_canu_mrl300/canu-scripts/canu.01.out /bigdata/hayashilab/shared/garblab/jgarb/rob/Cdar_silk_gland_assembly/canu/Cd13_02Oct14_03Oct14_Aug2013_all_subreads_canu_mrl300/canu-scripts/canu.01.sh
qsub: submit error (Illegal attribute or resource value for  Resource_List.mem)

-- Finished on Mon Aug 22 07:42:06 2016 (3 seconds) with 3970.2 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 168.  (rc=43008)
ERROR:
================================================================================
Please panic.  canu failed, and it shouldn't have.
```

-So PBS-Torque is not able to interpret the memory request syntax. For kicks, I resubmitted canu.01.sh with a corrected memory request (mem=16g). It runs and produces canu.01.out and canu.02.sh, whose submission then fails due to the same problem. I could continue, but this seems rather an inefficient way to proceed (and I don't know if it would work all the way to a completed run), so I am wondering if there is some other way to get around this?

Thanks!

**Comment by brianwalenz** [comment]
Canu will submit itself to the grid, so there is no need for you to submit it.  It was designed to be run on the head node directly.  All it will do here is query the grid environment to find what resources are available, set memory and thread parameters, and submit itself to the grid.

What are the defaults it is finding?  The defaults are set based on genomeSize, and are tuned for current reads from a genome.  It's entirely possible older RNA-Seq reads will need parameters tweaked.  That said, the first thing I'd try is running with default values.

You can also try setting ovsMemory=16-20, which is similar to what it is using internally.  I haven't been able to reproduce your flaw, so can't really make better suggestions.

Finally, which version of canu?

**Comment by roberthaney** [comment]
Hi Brian,

-In terms of running on the head node, can do, I was just following the protocol for our shared environment. That part of the process is not the issue though, I have run subsets of the data this way with no problem. Smaller subsets of this data with defaults do work. But as I increased the size of the data set runs were dying in the read error detection phase and overlap error adjustment phases, so I increased memory for those, and they completed successfully. 
-This was as yet  the largest set I tried to run, and the first run of it died while building the overlap store with the default setting for all parameters except oeaThreads, oeaMemory, redMemory, redThreads, minOverlapLength and minReadLength. Hence the increase in ovsMemory as a first attempt to get through this phase of analysis.

But the problem is that when I try to change the ovsMemory, the run dies as soon as it tries to submit canu.01.sh with the qsub submit error:

qsub: submit error (Illegal attribute or resource value for  Resource_List.mem)

-This has not happened in any run until I tried to change ovsMemory. If I submit the shell script manually but change the memory request from -l mem=16-16g to -1 mem=16g, it gets submitted OK and runs, producing the canu.01.out file and canu.02.sh. When I looked through all the shell scripts from my smaller successful runs, none had this error, but no memory request had a range, just a single value of format [int]g. This is why I assumed it might be related to the syntax of the memory request not being understood by qsub. 
 
I am using canu 1.3 and the resources the failed run found were as follows:

- Detected Java(TM) Runtime Environment '1.8.0_25' (from 'java').
- Detected 64 CPUs and 504 gigabytes of memory.
- Detected PBS/Torque with 'pbsnodes' binary in /opt/linux/centos/7.x/x86_64/pkgs/torque/5.1.0/bin/pbsnodes.
- 
- Found   2 hosts with  64 cores and  125 GB memory under PBS/Torque control.
- Found   2 hosts with  64 cores and 1007 GB memory under PBS/Torque control.
- Found   4 hosts with  32 cores and 1007 GB memory under PBS/Torque control.
- Found   1 host  with  64 cores and  487 GB memory under PBS/Torque control.
- Found   2 hosts with  32 cores and  125 GB memory under PBS/Torque control.
- Found  47 hosts with  64 cores and  503 GB memory under PBS/Torque control.
-
- Allowed to run under grid control, and use up to   4 compute threads and    7 GB memory for stage 'bogart (unitigger)'.
- Allowed to run under grid control, and use up to  16 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
- Allowed to run under grid control, and use up to  16 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
- Allowed to run under grid control, and use up to  16 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
- Allowed to run under grid control, and use up to   2 compute threads and   16 GB memory for stage 'read error detection (overlap error adjustment
)'.
- Allowed to run under grid control, and use up to   2 compute threads and   16 GB memory for stage 'overlap error adjustment'.
- Allowed to run under grid control, and use up to   4 compute threads and    8 GB memory for stage 'utgcns (consensus'.
- Allowed to run under grid control, and use up to   1 compute thread  and    2 GB memory for stage 'overlap store parallel bucketizer'.
- Allowed to run under grid control, and use up to   1 compute thread  and   16 GB memory for stage 'overlap store parallel sorting'.
- Allowed to run under grid control, and use up to   1 compute thread  and    2 GB memory for stage 'overlapper'.
- Allowed to run under grid control, and use up to   8 compute threads and    8 GB memory for stage 'overlapper'.
- Allowed to run under grid control, and use up to   8 compute threads and    8 GB memory for stage 'overlapper'.
- Allowed to run under grid control, and use up to   4 compute threads and    7 GB memory for stage 'meryl (k-mer counting)'.
- Allowed to run under grid control, and use up to   2 compute threads and    6 GB memory for stage 'falcon_sense (read correction)'.
- Allowed to run under grid control, and use up to  16 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
- Allowed to run under grid control, and use up to  16 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
- Allowed to run under grid control, and use up to  16 compute threads and    6 GB memory for stage 'minimap (overlapper)'.


Thanks for your help!

Rob

**Comment by roberthaney** [comment]
I also tried ovsMemory=16-20 as suggested, running directly from the head node and the run failed with the same error:

-- Detected Java(TM) Runtime Environment '1.8.0_25' (from 'java').
-- Detected 16 CPUs and 126 gigabytes of memory.
-- Detected PBS/Torque with 'pbsnodes' binary in /opt/linux/centos/7.x/x86_64/pkgs/torque/5.1.0/bin/pbsnodes.
-- 
-- Found   4 hosts with  32 cores and 1007 GB memory under PBS/Torque control.
-- Found   2 hosts with  32 cores and  125 GB memory under PBS/Torque control.
-- Found   2 hosts with  64 cores and 1007 GB memory under PBS/Torque control.
-- Found   1 host  with  64 cores and  487 GB memory under PBS/Torque control.
-- Found   2 hosts with  64 cores and  125 GB memory under PBS/Torque control.
-- Found  47 hosts with  64 cores and  503 GB memory under PBS/Torque control.
--
-- Allowed to run under grid control, and use up to   4 compute threads and    7 GB memory for stage 'bogart (unitigger)'.
-- Allowed to run under grid control, and use up to  16 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run under grid control, and use up to  16 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run under grid control, and use up to  16 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run under grid control, and use up to   2 compute threads and   16 GB memory for stage 'read error detection (overlap error adjustment)'.
-- Allowed to run under grid control, and use up to   2 compute threads and   16 GB memory for stage 'overlap error adjustment'.
-- Allowed to run under grid control, and use up to   4 compute threads and    8 GB memory for stage 'utgcns (consensus'.
-- Allowed to run under grid control, and use up to   1 compute thread  and    2 GB memory for stage 'overlap store parallel bucketizer'.
-- Allowed to run under grid control, and use up to   1 compute thread  and   20 GB memory for stage 'overlap store parallel sorting'.
-- Allowed to run under grid control, and use up to   1 compute thread  and    2 GB memory for stage 'overlapper'.
-- Allowed to run under grid control, and use up to   8 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run under grid control, and use up to   8 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run under grid control, and use up to   4 compute threads and    7 GB memory for stage 'meryl (k-mer counting)'.
-- Allowed to run under grid control, and use up to   2 compute threads and    6 GB memory for stage 'falcon_sense (read correction)'.
-- Allowed to run under grid control, and use up to  16 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run under grid control, and use up to  16 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run under grid control, and use up to  16 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
----------------------------------------
-- Starting command on Fri Aug 26 09:48:12 2016 with 3958 GB free disk space

    qsub \
      -l mem=16-20g \
      -l nodes=1:ppn=1   \
      -d `pwd` \
      -N "canu_Cd13_02Oct14_03Oct14_Aug2013_all_subreads_canu_mrl300" \
      -j oe \
      -o /bigdata/hayashilab/shared/garblab/jgarb/rob/Cdar_silk_gland_assembly/canu/Cd13_02Oct14_03Oct14_Aug2013_all_subreads_canu_mrl300/canu-scripts/canu.01.out /bigdata/hayashilab/shared/garblab/jgarb/rob/Cdar_silk_gland_assembly/canu/Cd13_02Oct14_03Oct14_Aug2013_all_subreads_canu_mrl300/canu-scripts/canu.01.sh
qsub: submit error (Illegal attribute or resource value for  Resource_List.mem)

-- Finished on Fri Aug 26 09:48:15 2016 (3 seconds) with 3958 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 168.  (rc=43008)
ERROR:
================================================================================
Please panic.  canu failed, and it shouldn't have.

Stack trace:

 at /bigdata/bioinfo/pkgadmin/opt/linux/centos/7.x/x86_64/pkgs/canu/1.3/bin/lib/canu/Defaults.pm line 234.
	canu::Defaults::caFailure("Failed to submit script", undef) called at /bigdata/bioinfo/pkgadmin/opt/linux/centos/7.x/x86_64/pkgs/canu/1.3/bin/lib/canu/Execution.pm line 860
	canu::Execution::submitScript("/bigdata/hayashilab/shared/garblab/jgarb/rob/Cdar_silk_gland_"..., "Cd13_02Oct14_03Oct14_Aug2013_all_subreads_canu_mrl300", undef) called at /opt/linux/centos/7.x/x86_64/pkgs/canu/1.3/bin/canu line 356


canu failed with 'Failed to submit script'.

**Comment by brianwalenz** [comment]
The easiest fix will be to update to the latest non-release version.

If you don't want to do that, src/pipelines/canu/Execution.pm to change the block at line 799 from
```
    if (getGlobal("ovsMethod") eq "sequential") {
        $mem = max($mem, getGlobal("ovsMemory"));
    }
```
to
```
    if (getGlobal("ovsMethod") eq "sequential") {
        $mem = getGlobal("ovsMemory");
        $mem = $2  if ($mem =~ m/^(\d+)-(\d+)$/);
    }
```
(if you only have the binary install, Execution.pm is in the same place as Defaults.pm mentioned in the error at the end of your last message.  you can edit it there too)

**Comment by roberthaney** [comment]
Thanks for digging into this. Seems like a simple fix, but I will have to run this by sysadmin.
