### ISSUE TITLE
Only a few reads left after correction

### ISSUE THREAD

**Issue by lamz138138** [marbl/canu#244]
Hi!

I had used pbsim to produce 100X random pacbio reads (median is 14K) of one chormosome (about 48m), then assemble them using canu with default parameters. However, only 14 reads left after correction. Considering canu was used to assemble pacbio data, 1) do you think the problem was caused by the simulate reads, or should I change the overlap parameters? 2) If I had to change the default parameter, which parameter should I change except the error rate mentioned in the tutorial. Besides, 3) what each category mean like "middle-missing" and how did they influence the correction process? In fact, I didn't know how reads were filtered from 141,440 to 14, 4) only 40X data were used, so 141,440 out of 336,993 reads were corrected, am I right? Following is some information, please let me know if you need more?

Any suggestion would be grateful.

Best wishes!

```
readsLoaded             336933 reads (4723834699 bp)                          
readsSkipped            62 reads (53801 bp) (read was too short)              
warnings                0 warnings (invalid base or quality value)

```

```
category            reads     %          read length        feature size or coverage  analysis
----------------  -------  -------  ----------------------  ------------------------  --------------------
middle-missing      57757   17.14    14900.70 +- 9080.69       4695.35 +- 4306.81    (bad trimming)
middle-hump             0    0.00        0.00 +- 0.00             0.00 +- 0.00       (bad trimming)
no-5-prime              0    0.00        0.00 +- 0.00             0.00 +- 0.00       (bad trimming)
no-3-prime              0    0.00        0.00 +- 0.00             0.00 +- 0.00       (bad trimming)

low-coverage        68257   20.26    14627.00 +- 9309.98          1.58 +- 1.13       (easy to assemble, potential for lower quality consensus)
unique                175    0.05    14563.00 +- 7179.97         16.50 +- 7.19       (easy to assemble, perfect, yay)
repeat-cont             0    0.00        0.00 +- 0.00             0.00 +- 0.00       (potential for consensus errors, no impact on assembly)
repeat-dove             3    0.00     4673.67 +- 1318.82         68.91 +- 9.37       (hard to assemble, likely won't assemble correctly or even at all)

span-repeat         14542    4.32    14068.56 +- 8647.89       1919.30 +- 2886.68    (read spans a large repeat, usually easy to assemble)
uniq-repeat-cont        0    0.00        0.00 +- 0.00                                (should be uniquely placed, low potential for consensus errors, no impact on assembly)
uniq-repeat-dove      706    0.21    11697.25 +- 6873.03                             (will end contigs, potential to misassemble)
uniq-anchor             0    0.00        0.00 +- 0.00             0.00 +- 0.00       (repeat read, with unique section, probable bad read)
```

```
Overlap Filtering

   PARAMETERS
            40      expected coverage                              
            0       don't use overlaps shorter than this           
            0.000   don't use overlaps with erate less than this   
            1.000   don't use overlaps with erate more than this   
   OVERLAPS 
            0       < 0.0000 fraction error                        
   Ignored  0       > 0.4095 fraction error                        
            0       < 0 bases long                                 
            0       > 2097151 bases long                           
   Filtered 1479144 too many overlaps, discard these shortest ones 
   Evidence 1529932 longest overlaps                               
   Total    3009076 all overlaps                                   
   READS    
            195493  no overlaps                                    
            126087  no overlaps filtered                           
            8006    < 50% overlaps filtered                        
            12712   < 80% overlaps filtered                        
            15186   < 95% overlaps filtered                        
            15353   < 100% overlaps filtered
```

```
Read Correction

   Filter method: corFilter=expensive. Expect to correct 141440 reads with bp
   to bp.

   INPUTS     
   141440     input reads                                       
   2074420921 input bases                                       
   OUTPUTS    
   141427     reads that failed to generate any corrected bases 
   14         corrected read pieces                             
   34295      corrected bases                                   
   PIECES PER READ
   0          141427                                            
   1          12                                                
   2          1
```

**Comment by skoren** [comment]
That definitely sounds like pbsim is producing reads with a higher average error rate than real data. There are overlaps being found by MHAP that the dynamic programming algorithm used to align and call consensus isn't finding. You can drop its identity with the ```corErrorRate=0.50``` parameter. You can also adjust PBSIM, I've found that setting ```--accuracy-min 0.8``` does a better job simulating data like current PacBio runs.

**Comment by lamz138138** [comment]
Hi, thanks for your reply very much!

I would try with corErrorRate=0.50, but how do you know that there are some overlap being found by MHAP, and what is the dynamic programming algorithm? After going through the tutorial several times, I still feel confused in some parameters, and the output log above. Anything more detail tutorial or should I review "Assembling large genomes with single-molecule sequencing and locality-sensitive hashing"?

Best wishes!

**Comment by skoren** [comment]
The way Canu generates corrected reads is by first running MHAP which does approximate alignments and estimates their identity without any dynamic programming. This is extremely fast but the boundaries of the overlaps aren't exact. Next it does some filtering of the overlaps to decide which will be used for generating the corrected reads. It uses this filtered set of overlaps to estimate the length of the corrected reads (the logs you're looking at). Then it calls falcon_sense which uses an ND algorithm to align each of the selected overlapping reads to the read being corrected and calls consensus from a DAG. The fact that you have reads that should be corrected in your logs but no bases are output means the DAG couldn't call a consensus, most likely because it couldn't find the alignments with ND at its default error rate. There's more details on the methods in the preprint.

**Comment by lamz138138** [comment]
I got it, thanks very much!
