### ISSUE TITLE
CANU release

### ISSUE THREAD

**Issue by bostanict** [marbl/canu#245]
Hi,

I saw that the citation is updated to 

> Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM. Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation. bioRxiv 071282; doi: http://dx.doi.org/10.1101/071282

The source was also updated. I just want to make sure that the version is now corresponding to the updated source code since in the website the latest release is June 8th. Another question I have is that is the problem of CANU is separating the baubles from primary contigs resolved in this version?

Thanks alor~

**Comment by skoren** [comment]
Hi,

All results in the paper are based on the 1.3 release (https://github.com/marbl/canu/releases/tag/v1.3) so it does not have the bubble fixes. That is under active development and should hopefully be part of a release soon.

**Comment by bostanict** [comment]
Thanks A lot~
