### ISSUE TITLE
correction stage: ovlStore error

### ISSUE THREAD

**Issue by mahulchak** [marbl/canu#250]
Hello,
I am running the lastest version of canu on a single node (64 cores, 512GB RAM). However, my jobs are failing at the correction stage with the error message:

Found 459082804 (459.08 million) overlaps.
Configuring for 32.00 GB to 32.00 GB memory and 0 open files.
At memory 32.000GB, 852282572 olaps per bucket, 1 buckets (pass 1).
ERROR:  Cannot sort 459.08 million overlaps using 32.00 GB memory; too few file handles available.
ERROR:    olapsPerBucket 852282572
ERROR:    buckets        1
ERROR:    SC_CHILD_MAX   18446744073709551615
ERROR:    SC_OPEN_MAX    262144
ERROR:  Increase memory size (in canu, ovsMemory; in ovStoreBuild, -M)

I tried to set ovsMemory=256 and it still does not work. Same thing happens when I switch to the grid mode on our SGE cluster.
Any idea what is causing this or how to fix this error?
Thanks.
Mahul

**Comment by mahulchak** [comment]
Update: canu 1.2 does not show this error.

**Comment by brianwalenz** [comment]
Interesting.  Any idea how SC_CHILD_MAX (the number of processes allowed per used) got so big?  What OS?  Do you know how to reduce it to sane values - say, something less than a few thousand?

Is 'latest version' the 1.3 release, or the latest code from the github repo?  What does 'canu --version' report?

I see the problem and have a fix, but applying the fix depends on what version you're using.  The simplest fix will be to change src/ovStoreBuild.C at around line 73 to set maxFiles to be, say, 10000.

**Comment by mahulchak** [comment]
Hi Brain,
Thanks for replying.

wow! Did not notice the SC_CHILD_MAX value. I am not sure how it got so
big. Could playing with ovsMemory values cause it? Our hpc runs on CentOS.

I am using the latest code from  the github repo.
 $ canu --version
Canu v1.3 (+152 commits) r7768 71dcf22e1e315f6f7f1cde22d165fed20c464465.

Do you want me to change src/ovStoreBuild.C and retry ?

**Comment by mahulchak** [comment]
But if this is the source of the problem, then why does canu1.2 work? It
seems to have the same code in ovStoreBuild.C

**Comment by brianwalenz** [comment]
Yes, make the change.

The SC_CHILD_MAX comes from the OS, nothing in canu will set it.  It's _supposed_ to be the maximum number of processes you can run at one time.  No idea how it is being interpreted by CentOS.

Due to other changes I need to redo this part in ovStoreBuild, but forcing it to 10000 for now will work.

**Comment by mahulchak** [comment]
Hi Brian,
It is working now after setting maxFiles to 10000.
Thanks.
Mahul

**Comment by brianwalenz** [comment]
I was just finishing up the 'real' patch.  Thanks for testing.
