### ISSUE TITLE
SGE option overwriting

### ISSUE THREAD

**Issue by chklopp** [marbl/canu#251]
Hi,

I'm running CANU on our SGE cluster. The build-in memory allocation parameters are too low for our configuration, therefore I've used gridOptionscormhap, gridOptionsred and gridOptionsoea options : 

canu -p TEST -d TEST=250m -pacbio-raw All.fastq java=/tools/java/jre1.8.0_45/bin/java gridEngineMemoryOption="-l mem=MEMORY,h_vmem=MEMORY" gridEngineThreadsOption="-pe parallel_smp THREADS" gridOptions="-V" gridOptionscormhap="-l mem=4G,h_vmem=4G -pe parallel_smp 8" gridOptionsred="-l mem=16G,h_vmem=16G -pe parallel_smp 4" gridOptionsoea="-l mem=16G,h_vmem=16G -pe parallel_smp 4"

Unfortunately it does not work because de parameters are added to the qsub command before the calculated options 

mhap.jobSubmit.sh
  qsub \
    -V -l mem=4G,h_vmem=4G -pe parallel_smp 8  -l mem=1.444G,h_vmem=1.444G -pe parallel_smp 8  \
    -cwd -N "cormhap_TEST" \
    -t 5-5 \
    -j y -o /xxxx/TEST/correction/1-overlapper/mhap.\$TASK_ID.out \
    /xxxx/TEST/correction/1-overlapper/mhap.sh

Is it possible to replace the build-in SGE parameters with the one given in the command line?

**Comment by skoren** [comment]
When you say the memory parameters are too low what do you mean? Generally, you shouldn't specify h_vmem to be the same as memory because Canu uses memory-mapped files which take up virtual memory but not resident memory (unless there is no memory pressure on the system), see issue #202 for details). You can specify a large h_vmem to gridOptions and don't specify it to gridEngineMemoryOption.

**Comment by chklopp** [comment]
Thanks for you quick reply.

On our cluster to run java 8 we have to provide at least 64G of memory in the qsub command line, and usually  we do it by -l mem=64G,h_vmem=64G. And then it works.
If I've understood the your suggestion, I could set gridOptions to '-l h_vmem=64G'  and leave the rest to CANU.

**Comment by chklopp** [comment]
The solution works.
Thank you.
