### ISSUE TITLE
quiver polishing Canu assemblies -- contigs missing in output

### ISSUE THREAD

**Issue by JohnUrban** [marbl/canu#253]
I know this is not exactly the right place for this, but I have a question regarding Quiver and I have had no luck getting responses on Quiver's github. If someone could offer insight here, that would be above and beyond -- and very much appreciated.

For aligning pacbio reads for quiver, I essentially follow these instructions:
https://github.com/PacificBiosciences/pbalign/wiki/Tutorial:-How-to-divide-and-conquer-large-datasets-using-pbalign

The command I use for quiver thereafter is:

```
quiver -j${THREADS} ${INPUT} -r ${REF} -o $OUTGFF -o $OUTFASTQ -o $OUTFASTA
```

I have been seeing that the number of output sequences is less than the number of input sequences. In other words, if the contig is not represented in the alignments file, Quiver does not report it in the polished assembly -- even when you use the option to report sequences that do not have enough coverage for polishing as lower-case. There seem to be several Canu contigs that have 0 alignments and are therefore affected. The ones I checked seem to be short contigs.

I am left wondering whether or not I should just add the missing sequences back to the Quiver-polished assemblies before moving on to Pilon --- or should I just let those sequences be removed at this step…?

Thanks for your time and possibly your thoughts on this.

best,

John Urban

**Comment by skoren** [comment]
First, I'd suggest looking at the Quiver pipeline here:https://github.com/skoren/QuiverGrid. It doesn't depend on one giant file being merged/sorted which is a killer on vertebrate genomes. Hopefully PacBio will release arrow soon which will fix some of these issues.

As for removing contigs, generally yes, I've removed those that have no alignments. They're often short and may be redundant with other contigs (so Quiver doesn't assign reads to them) or be due to unsplit chimeric reads that have a better alignment elsewhere.

**Comment by JohnUrban** [comment]
Hi Sergey,

Thank you for your feedback and explanation.

It sounds like you are manually removing contigs that have no alignments, but do you recall from your experience with Quiver that it automatically removes contigs that have no alignments? 

I will need to check more examples on my end to make sure it is only removing relatively short contigs with 0 coverage -- and not spuriously dropping out good contigs.

best,

 John

p.s. It may be of interest to you guys (or it might be a spurious observation) that I saw this issue of contigs being dropped out for Canu, DBG2OLC, Falcon, and Miniasm assemblies -- but did not see this with ABruijn and SMARTdenovo assemblies.

**Comment by JohnUrban** [comment]
For those following along, I received a response back from a PacBio representative:
"I apologize for your confusion. Allow me to clear up the functionality of the –NoEvidenceBaseCall. While we do take a reference sequence to align our raw reads to and pass that alignment to prior to entering Quiver, this flag is ONLY applied for bases that still have some level of coverage in another area of the contig. If a contig has 0 coverage without the entire contig, it will not be reported back as Quiver does not actually use the reference to call consensus at all, it simply looks at the alignment blocks. So if there is no alignment block, it does not report back the 0 coverage contig. I hope that clarifies things for you."

Short answer: 0 coverage contigs are not reported in the Quiver-polished output.

**Comment by skoren** [comment]
To clarify I also meant that I accept Quiver's throwing out contigs with no support (those that get erased due to no coverage).

**Comment by JohnUrban** [comment]
Thanks for the clarification, Sergey. 

I will close this for now. Your comments have been very illuminating for me. Thanks for taking the time to respond.

**Comment by JohnUrban** [comment]
Hi Sergey,

Do you also throw out the usually-short contigs that are not dropped by Quiver, but do not have enough reads for Quiver to compute a consensus for (so are reported as lower-case)?

i.e. these are usually-short low-coverage (lowercase) contigs as compared to the usually-short no-coverage contigs that Quiver drops.

Thanks for any input -- I know it is not necessarily the right place for this question.

best,

 John

**Comment by skoren** [comment]
I generally don't throw them out but we've previously flagged contigs with a few reads as not primary contigs so downstream tools now they're low-coverage/lower quality. The Quiver fastq should also capture their lower quality in the score.

**Comment by JohnUrban** [comment]
Thanks for the quick reply.
