### ISSUE TITLE
Wrong bin in LSF

### ISSUE THREAD

**Issue by sunnvor** [marbl/canu#256]
Hi,

I am using LSF as my grib engine and when I try to run the canu on the test data I get the error below. 

/../Canu/ecoli-oxford/canu-scripts/canu.06.sh: line 8: uname: command not found
/../Canu/ecoli-oxford/canu-scripts/canu.06.sh: line 9: uname: command not found
/../Canu/ecoli-oxford/canu-scripts/canu.06.sh: line 10: uname: command not found
Can't open perl script "/../software/canu/canu": No such file or directory

As far as I can tell the bin directory is not correct because of the uname command not working once the job has been submitted. Is there a way to manually set the bin directory?

Cheers,
Sunnvor

**Comment by brianwalenz** [comment]
Look for an option to the LSF submit command to export your current environment to the grid job, then set that canu option gridOptions to that, e.g., gridOptions="-V".  Failing that, check with a local admin.  This sounds like you're not getting _any_ kind of setup done for grid jobs.
