### ISSUE TITLE
Which reads are used for final assembly?

### ISSUE THREAD

**Issue by woodoo46** [marbl/canu#258]
Hi Sergey,

I assume that the program uses the reads in ecoli.trimmedReads.fasta.gz to generate the final contigs, is it reasonable?

Thanks.

**Comment by brianwalenz** [comment]
Yes.  Described in the preprint (http://biorxiv.org/content/early/2016/08/24/071282) and, as of a few moments ago, the pipeline documentation (http://canu.readthedocs.io/en/latest/pipeline.html).
