### ISSUE TITLE
Canu failed after trimming

### ISSUE THREAD

**Issue by garethli** [marbl/canu#264]
Hi

I am trying to assemble a 527Mb genome from 29X of raw PacBio data.

The assembly fails with the error: canu failed with 'failed to adjust overlap error rates.  Made 2 attempts, jobs still failed'.

I am running the three separate canu commands, correct, trim, assemble

canu -correct -p canu1 -d canu_out genomeSize=527m corMinCoverage=0 errorRate=0.035 -pacbio-raw all_filtered_subreads_15cells.fastq -maxMemory=240 -maxThreads=30 -useGrid=false

canu -trim -p canu1 -d canu_out genomeSize=527m corMinCoverage=0 errorRate=0.035 -pacbio-raw all_filtered_subreads_15cells.fastq -maxMemory=240 -maxThreads=30 -useGrid=false

canu -assemble -p canu1 -d canu_out genomeSize=527m corMinCoverage=0 errorRate=0.035 -pacbio-raw all_filtered_subreads_15cells.fastq -maxMemory=240 -maxThreads=30 -useGrid=false 

The corMinCoverage and errorRate params have been set as indicated in the canu manual for low coverage data sets.

Assembly is on a SLURM cluster but I am not using the grid. I am allocating 30 cores, each with 8Gb of RAM and treating it as a single large machine with 30 cores and 240Gb of RAM (perhaps this is the problem). I am doing it this way because I don't believe our cluster will allow job submission from compute nodes and I have seen on previous threads that this is a problem for canu.

The correction stage completes fine and I end up with 4.5Gb of gzipped fasta in corrected reads (960612 reads).
Although the trimming stage completes and the assembler begins to execute the unitigging stage, it seems likely to me that the problem was actually at the trimming stage since the the summary in my trimming.html looks like this..

INPUT READS

reads		bases	
1995189		14983942091	reads processed
0		0		reads not processed, previously deleted
0		0		reads not processed, in a library where trimming isn't allowed

OUTPUT READS

reads		bases	
2316		3316313		trimmed reads output
0		0		reads with no change, kept as is
1960932		14641130028	reads with no overlaps, deleted
31941		317210515	reads with short trimmed length, deleted

TRIMMING DETAILS
reads		bases	
2299		11430127	bases trimmed from the 5' end of a read
2264		10855108	bases trimmed from the 3' end of a read

So it seems most of my reads are being deleted at the trimming stage. So is it likely that the failure at the overlap error correction stage is actually caused by not enough data left over from the trimming stage?

Or even insufficient data left over from the correction stage? There are only 960612 reads in the correctedReads.fasta wheras there are 2144927 in the input fastq.

**Comment by brianwalenz** [comment]
The -trim and -assemble switches are expecting corrected or trimmed reads (respectively) on the command line.  You're giving the original raw reads for each step, and canu is using those reads instead of the previously computed result.  To run each step manually, you'll need to pass in the result of the previous step, something like:
`canu ... -assemble -pacbio-corrected canu_out/canu.trimmedReads.fasta.gz`

(aside: all -pacbio-corrected does is disable the correction step, e.g., it's equivalent to -trim-assemble)

These switches were added for cases where reads were corrected/trimmed by something other than canu.  I don't encourage running canu this way.
