### ISSUE TITLE
gatekeeperPartition failed

### ISSUE THREAD

**Issue by Katanagatari** [marbl/canu#265]
Hi,
I am runing canu to assemble lambda genome that I have got from MinIOn. In the gatekeeperPartion step, I got following error:

> Finished on Sun Oct  9 19:09:15 2016 (lickety-split) with 417.045 GB free disk space
> ###### 
> 
> ERROR:
> ERROR:  Failed with exit code 1.  (rc=256)
> ERROR:
> ###### 
> 
> Don't panic, but a mostly harmless error occurred and canu failed.
> Disk space available:  417.045 GB
> Last 50 lines of the relevant log file (/media/nanopore/corrected/lambda/5/unitigging/lambda5.utgStore/partitionedReads.err):
> tgStore::tgStore()-- ERROR, didn't find any tigs in the store.
> tgStore::tgStore()--        asked for store '/media/nanopore/corrected/lambda/5/unitigging/lambda5.utgStore', correct?
> tgStore::tgStore()--        asked for version '1', correct?
> canu failed with 'failed to partition the reads'.

Any ideas help me fix it?
Thanks too much.

**Comment by skoren** [comment]
It looks like you're running the latest code from the repo. I'd suggest trying with the 1.3 release to see if that fixes your problem. The latest has some large changes to unitigging which could be causing your error.

**Comment by brianwalenz** [comment]
Since it's my code that is breaking, I'd like to figure out what is broken.  I suspect that the assembly is triggering our false-assembly filter, which is looking for 'contigs' that are spanned by a single read.  Try setting canu output filtering options as described at http://canu.readthedocs.io/en/latest/parameter-reference.html#output-filtering

Is this data available for download?

**Comment by brianwalenz** [comment]
No response.

**Comment by miles-gene** [comment]
@brianwalenz
Hi, I got a very similar error with some very poor quality MinION R7 reads. They were supposed to be 2D but metrichor only basecalled a proportion of them and as template only. Deepnano processed them all and generated template, some complement and some 2D reads. The changes you suggested to the OP enabled canu to complete assembly in my case (reads=contigs basically but it ran) which I thought you might be interested to know.

**Comment by hwalinga** [comment]
@brianwalenz 

I got the exact same problem. But how exactly should I change the output filtering option to solve this issue?

**Comment by skoren** [comment]
The FAQ has more relaxed filtering parameters listed: https://canu.readthedocs.io/en/latest/faq.html#my-asm-contigs-fasta-is-empty-why that you could try.
