### ISSUE TITLE
Cannot compile canu

### ISSUE THREAD

**Issue by geneticsguy** [marbl/canu#270]
Hello,

I have been unable to successfully compile canu. I am running Mac OS 10.12 (Sierra) with 32 GB of RAM and more than 2 TB of free hard disk space. I have GCC v6.2.0 installed using homebrew, Java SE 8 update 101, and Perl v5.16.0. These installs look to be good. For example, gcc --version in any directory returns 'gcc (Homebrew gcc 6.2.0) 6.2.0'.

I get the following specific errors when compiling canu v1.3:

Makefile:537: /Users/me/Documents/pacbio: No such file or directory
Makefile:537: /Users/me/Documents/pacbio: No such file or directory
Makefile:537: reads/canu/src/reads/canu/src/stores/gatekeeperCreate.mk: No such file or directory
.
.
.
Makefile:537: /Users/me/Documents/pacbio: No such file or directory
Makefile:537: reads/canu/src/reads/canu/src/stores/tgStoreLoad.mk: No such file or directory
Segmentation fault: 11

I was wondering if you have any suggestions.

Thank you!

Ian Ehrenreich

**Comment by brianwalenz** [comment]
Wild guess: is the directory "pacbio reads", with a space?  Try renaming that to something without spaces.

I haven't tried either Sierra or gcc6, so most interested in hearing your results in compiling and running.

**Comment by geneticsguy** [comment]
That did the trick in terms of getting the compiler to run. However, clang is being used to compile instead of gcc, resulting in many warnings that certain arguments are unused or unsupported. Do you know how to make 'make' happen through gcc instead of clang? It appears installing the current gcc was insufficient.

Thanks again,

Ian

**Comment by geneticsguy** [comment]
Got things working. Two issues I noticed:

1. GCC updated via homebrew failed to correctly compile, while GCC updated through macports succeeded.
2. GCC v6.2  compiled, but produced many warnings. When I downgraded to GCC v4.7, everything worked fine with no warnings.

Have things compiled now!

Best,

Ian

**Comment by brianwalenz** [comment]
Don't know what to say about homebrew gcc.  I've not used it.

I fixed the gcc6 warnings, thanks for reporting.
