### ISSUE TITLE
BAC de novo assembly with CANU

### ISSUE THREAD

**Issue by sjin09** [marbl/canu#273]
To whom it may concern,

I have been quite successful with BAC de novo assembly using CANU. We pooled 48 BAC clones and sequenced the BAC clones with P6C4 chemistry on the SMRT platform. With CANU, we were consistently able to achieve average read length of ~90kb without any parameter adjustments.

I wanted to ask whether there could be additional parameter adjustments to further improve the BAC clone assembly with CANU. The BAC clones were on average sequenced to ~50X to 70X. In addition, the sequences originating from the E.coli has been removed and the vector sequences were masked from the subreads prior to the assembly. In particular, I am interested in retaining the ends of the BAC contigs as much as possible for identification of the BAC clones through the alignment of BAC end sequences to the contigs. The ends of the BAC contigs would most likely have lower coverage than the middle portion of the BAC inserts. 

I have tried the de novo assembly with HGAP And FALCON, but the results from these two assemblers were not as satisfactory as CANU. 

Any advice would be much appreciated. 

Best,
Sangjin Lee

**Comment by brianwalenz** [comment]
Yes, check out the recently updated FAQ: http://canu.readthedocs.io/en/latest/faq.html

1. Set `corOutCoverage=1000` to correct all input reads
2. Set `corMinCoverage=0` to retain even the uncorrected bases (and let our trimming clean things up).
3. Set `contigFilter="2 1000 1.0 1.0 2"` to not filter any contigs as unassembled.  Though this is probably not an issue.

The first two are essentially the 'low coverage' recipe, trying to keep the BAC ends.

Of the parameters to tweak, try increasing the minimum read and overlap lengths, and changing the two deviations.  This might get more assembly.
