### ISSUE TITLE
Canu ovlStore : Failed with signal SEGV (11) 

### ISSUE THREAD

**Issue by shameem356** [marbl/canu#274]
Hello ,
We are trying to do data 'correction'  and it failed at '**ovlStore**'  steps.We have tried two times and both attempt failed with same reason.Below is the error log.

ERROR: Failed with signal SEGV (11)
Failed with 'Segmentation fault'
Backtrace (mangled):
/data/labs/genomics_lab/shared/shameem/apps/canu-1.0/Linux-amd64/bin/ovStoreStats(_Z17AS_UTL_catchCrashiP7siginfoPv+0x27)[0x41d617]
/lib64/libpthread.so.0[0x36c460f790]
/data/labs/genomics_lab/shared/shameem/apps/canu-1.0/Linux-amd64/bin/ovStoreStats[0x40540a]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x36c421ed5d]
/data/labs/genomics_lab/shared/shameem/apps/canu-1.0/Linux-amd64/bin/ovStoreStats[0x401a29]
Backtrace (demangled):
[0] /data/labs/genomics_lab/shared/shameem/apps/canu-1.0/Linux-amd64/bin/ovStoreStats::AS_UTL_catchCrash(int, siginfo*, void*) + 0x27  [0x41d617]
[1] /lib64/libpthread.so.0() [0x36c460f790]
[2] /data/labs/genomics_lab/shared/shameem/apps/canu-1.0/Linux-amd64/bin/ovStoreStats() [0x40540a]
[3] /lib64/libc.so.6::(null) + 0xfd  [0x36c421ed5d]
[4] /data/labs/genomics_lab/shared/shameem/apps/canu-1.0/Linux-amd64/bin/ovStoreStats() [0x401a29]

Here is the parameter used for canu correction.

useGrid=0
maxThreads=60
maxMemory=300
corConcurrency=10
utgovlConcurrency=10
utgovlConcurrency=10
oeaConcurrency=10
ovbConcurrency=10
ovsConcurrency=10
redConcurrency=10
cormhapMemory=25
corovlMemory=25
obtmhapMemory=25
obtovlMemory=25
utgmhapMemory=25
utgovlMemory=25
oeaMemory=25
ovbMemory=25
ovsMemory=25
redMemory=25

Please let us know how to solve this issue.

**Comment by brianwalenz** [comment]
Is this really v1.0?  What does 'canu -version' report?  If so, you first need to update.  But be warned that you'll need to start a completely new assembly.  You can try resuming the current assembly with the new code, but I don't think it'll work.

This is generating a diagnostic output, and isn't critical to the run.  Does restarting canu with the same command, and without removing the old output, work?

I'd also advise against setting the memory and concurrency options, unless necessary.  Canu will figure out settings based on the genome size and the resources available on the machine.

**Comment by shameem356** [comment]
Hello,

Yes, I used canu-1.0 version.I have restarted canu with same command and removed old out put.Still got the same error.

Now I have downloaded new canu and running without memory and concurrency options.I will update the status of new run once it finished.

**Comment by shameem356** [comment]
In new version it worked fine and got the out put.

Thank you so much your help.

**Comment by shameem356** [comment]
Hello ,

Canu finished successfully and got the out put.But I am confused with canu out put file name.Last time I ran canu 1.0 version and assembly out put name was 'assemble.**consensus.fasta**'.But this time as per your suggestion we have updated the canu and got the out put as assembly.**contigs.fasta** .So I want to confirm that assembly.contigs.fasta is the final assembly file or not ?

**Comment by skoren** [comment]
Yes, outputs have been renamed. See the documentation page on outputs:http://canu.readthedocs.io/en/latest/quick-start.html#find-the-output
