### ISSUE TITLE
cannot find the assembly - canu

### ISSUE THREAD

**Issue by JahnDavik** [marbl/canu#275]
I am running the CANU and I cannot find the assembly. 
I am currently only doing the ecoli-data demo data set. However, no asm.contigs.fasta are made. Neither any other file that intuitively indicates that it is an assembly file.

**Comment by skoren** [comment]
What is the output from the Canu command? Are you running on the grid or a single system?

**Comment by JahnDavik** [comment]
Dear Sergey Koren,

Thanks for getting back to me promptly. For now I am running on a single system. It is a 256GB linux machine.



The output list is as follows:



drwxr-xr-x 8 kvijed users      4096 Oct 19 09:36 ecoli-auto
-rw-r--r-- 1 kvijed users 233631098 Sep 12 13:40 ecoli_p6_25x.filtered.fastq
kvijed@bioseq01:~/canuTest$ cd ecoli-auto
kvijed@bioseq01:~/canuTest/ecoli-auto$ ls -l
total 64
drwxr-xr-x 2 kvijed users 4096 Sep 13 10:19 canu-logs
drwxr-xr-x 2 kvijed users 4096 Sep 13 10:17 canu-scripts
drwxr-xr-x 7 kvijed users 4096 Sep 13 10:18 correction
-rw-r--r-- 1 kvijed users 8701 Sep 13 10:18 correction.html
drwxr-xr-x 2 kvijed users 4096 Sep 13 10:17 correction.html.files
-rw-r--r-- 1 kvijed users 9193 Oct 19 09:36 ecoli.correctedReads.fasta
-rw-r--r-- 1 kvijed users 3209 Sep 13 10:18 ecoli.correctedReads.fasta.gz
-rw-r--r-- 1 kvijed users   12 Sep 13 10:18 ecoli.correctedReads.length
drwxr-xr-x 5 kvijed users 4096 Sep 13 10:19 trimming
-rw-r--r-- 1 kvijed users 4148 Sep 13 10:19 trimming.html
drwxr-xr-x 2 kvijed users 4096 Sep 13 10:18 trimming.html.files
kvijed@bioseq01:~/canuTest/ecoli-auto$



I took the script from the canu Documentation Release 1.3, i.e.,

canu - p ecoli -d ecoli-auto genomeSize=4.8m -packbio-raw p6.25x.fastq











________________________________
Fra: Sergey Koren <notifications@github.com>
Sendt: 19. oktober 2016 21:23
Til: marbl/canu
Kopi: Jahn Davik; Author
Emne: Re: [marbl/canu] cannot find the assembly - canu (#275)


What is the output from the Canu command? Are you running on the grid or a single system?

-

**Comment by JahnDavik** [comment]
Incidently, I've tried to get canu running on a grid as well. That doesn't seem to succeed either.

After running:

"

./canu/Linux-amd64/bin/canu -gridOptions="--account=nn9457k --time=72:00:00 --nodes=1" -p ecoli -d ecoli_auto3 genomeSize=4.8m -pacbio-raw p6.25x.fastq

"


I get is the following list:


-bash-4.1$ cd ecoli_auto3
-bash-4.1$ ls -l
total 12
drwxr-xr-x 2 jahndavik users   14 Oct 20 09:22 canu-logs
drwxr-xr-x 2 jahndavik users    9 Oct 20 09:22 canu-scripts
drwxr-xr-x 7 jahndavik users   10 Oct 20 09:22 correction
-rw-r--r-- 1 jahndavik users 9130 Oct 20 09:22 correction.html
drwxr-xr-x 2 jahndavik users    6 Oct 20 09:22 correction.html.files





________________________________
Fra: Sergey Koren <notifications@github.com>
Sendt: 19. oktober 2016 21:23
Til: marbl/canu
Kopi: Jahn Davik; Author
Emne: Re: [marbl/canu] cannot find the assembly - canu (#275)


What is the output from the Canu command? Are you running on the grid or a single system?

-

**Comment by brianwalenz** [comment]
We're after the diagnostic output of the canu command.  If you rerun the first command (the one not using the grid) it'll try to resume the assembly.  Assuming it fails again, paste in what it prints to the screen.

**Comment by JahnDavik** [comment]
Hi,

Thanks for getting back to me.

I enclose the code I use and what comes out of the screen.


j


________________________________
Fra: Brian Walenz <notifications@github.com>
Sendt: 20. oktober 2016 13:28
Til: marbl/canu
Kopi: Jahn Davik; Author
Emne: Re: [marbl/canu] cannot find the assembly - canu (#275)


We're after the diagnostic output of the canu command. If you rerun the first command (the one not using the grid) it'll try to resume the assembly. Assuming it fails again, paste in what it prints to the screen.

-

**Comment by JahnDavik** [comment]
/usr/local/bin/canu-1.3/Linux-amd64/bin/canu \
-p ecoli -d ecoli-auto2 \
genomeSize=4.8 \
-pacbio-raw ecoli_p6_25x.filtered.fastq


drwxr-xr-x  2 kvijed users     0 Sep 13 10:49 zyxel03
kvijed@bioseq01:~$ cd canuTest/
kvijed@bioseq01:~/canuTest$ ls -l
total 228164
drwxr-xr-x 8 kvijed users      4096 Oct 19 09:36 ecoli-auto
-rw-r--r-- 1 kvijed users 233631098 Sep 12 13:40 ecoli_p6_25x.filtered.fastq
kvijed@bioseq01:~/canuTest$ cd ecoli-auto
kvijed@bioseq01:~/canuTest/ecoli-auto$ ls -l
total 64
drwxr-xr-x 2 kvijed users 4096 Sep 13 10:19 canu-logs
drwxr-xr-x 2 kvijed users 4096 Sep 13 10:17 canu-scripts
drwxr-xr-x 7 kvijed users 4096 Sep 13 10:18 correction
-rw-r--r-- 1 kvijed users 8701 Sep 13 10:18 correction.html
drwxr-xr-x 2 kvijed users 4096 Sep 13 10:17 correction.html.files
-rw-r--r-- 1 kvijed users 9193 Oct 19 09:36 ecoli.correctedReads.fasta
-rw-r--r-- 1 kvijed users 3209 Sep 13 10:18 ecoli.correctedReads.fasta.gz
-rw-r--r-- 1 kvijed users   12 Sep 13 10:18 ecoli.correctedReads.length
drwxr-xr-x 5 kvijed users 4096 Sep 13 10:19 trimming
-rw-r--r-- 1 kvijed users 4148 Sep 13 10:19 trimming.html
drwxr-xr-x 2 kvijed users 4096 Sep 13 10:18 trimming.html.files
kvijed@bioseq01:~/canuTest/ecoli-auto$ cd ..
kvijed@bioseq01:~/canuTest$ ls -l
total 228164
drwxr-xr-x 8 kvijed users      4096 Oct 19 09:36 ecoli-auto
-rw-r--r-- 1 kvijed users 233631098 Sep 12 13:40 ecoli_p6_25x.filtered.fastq
kvijed@bioseq01:~/canuTest$ usr/local/bin/canu-1.3/Linux-amd64/bin/canu \
> -p ecoli -d ecoli-auto2 \
> genomeSize=4.8 \
> -pacbio-raw ecoli_p6_25x.filtered.fastq
bash: usr/local/bin/canu-1.3/Linux-amd64/bin/canu: No such file or directory
kvijed@bioseq01:~/canuTest$ /usr/local/bin/canu-1.3/Linux-amd64/bin/canu -p ecoli -d ecoli-auto2 genomeSize=4.8 -pacbio-raw ecoli_p6_25x.filtered.fastq
-- Detected Java(TM) Runtime Environment '1.8.0_101' (from 'java').
-- Detected 32 CPUs and 252 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
-- Allowed to run   8 jobs concurrently, and use up to   4 compute threads and   16 GB memory for stage 'bogart (unitigger)'.
-- Allowed to run   2 jobs concurrently, and use up to  16 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   2 jobs concurrently, and use up to  16 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   2 jobs concurrently, and use up to  16 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   8 jobs concurrently, and use up to   4 compute threads and    2 GB memory for stage 'read error detection (overlap error adjustment)'.
-- Allowed to run  32 jobs concurrently, and use up to   1 compute thread  and    1 GB memory for stage 'overlap error adjustment'.
-- Allowed to run   8 jobs concurrently, and use up to   4 compute threads and   31 GB memory for stage 'utgcns (consensus'.
-- Allowed to run  32 jobs concurrently, and use up to   1 compute thread  and    4 GB memory for stage 'overlap store parallel bucketizer'.
-- Allowed to run  32 jobs concurrently, and use up to   1 compute thread  and    8 GB memory for stage 'overlap store parallel sorting'.
-- Allowed to run  32 jobs concurrently, and use up to   1 compute thread  and    6 GB memory for stage 'overlapper'.
-- Allowed to run   4 jobs concurrently, and use up to   8 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run   4 jobs concurrently, and use up to   8 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run   8 jobs concurrently, and use up to   4 compute threads and    8 GB memory for stage 'meryl (k-mer counting)'.
-- Allowed to run  16 jobs concurrently, and use up to   2 compute threads and   15 GB memory for stage 'falcon_sense (read correction)'.
-- Allowed to run   2 jobs concurrently, and use up to  16 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   2 jobs concurrently, and use up to  16 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   2 jobs concurrently, and use up to  16 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
--
-- This is canu parallel iteration #1, out of a maximum of 2 attempts.
--
-- Final error rates before starting pipeline:
--   
--   genomeSize          -- 4.8
--   errorRate           -- 0.025
--   
--   corOvlErrorRate     -- 0.075
--   obtOvlErrorRate     -- 0.075
--   utgOvlErrorRate     -- 0.075
--   
--   obtErrorRate        -- 0.075
--   
--   cnsErrorRate        -- 0.075
--
--
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Thu Oct 20 13:40:37 2016 with 6204.3 GB free disk space

    /usr/local/bin/canu-1.3/Linux-amd64/bin/gatekeeperCreate \
      -minlength 1000 \
      -o /data/kvijed/canuTest/ecoli-auto2/correction/ecoli.gkpStore.BUILDING \
      /data/kvijed/canuTest/ecoli-auto2/correction/ecoli.gkpStore.gkp \
    > /data/kvijed/canuTest/ecoli-auto2/correction/ecoli.gkpStore.BUILDING.err 2>&1

-- Finished on Thu Oct 20 13:40:38 2016 (1 second) with 6204.3 GB free disk space
----------------------------------------
--
-- WARNING: gnuplot failed; no plots will appear in HTML output.
--
----------------------------------------
--
-- In gatekeeper store '/data/kvijed/canuTest/ecoli-auto2/correction/ecoli.gkpStore':
--   Found 12528 reads.
--   Found 115899341 bases (24145696.04 times coverage).
--
--   Read length histogram (one '*' equals 20.62 reads):
--        0    999      0 
--     1000   1999   1444 **********************************************************************
--     2000   2999   1328 ****************************************************************
--     3000   3999   1065 ***************************************************
--     4000   4999    774 *************************************
--     5000   5999    668 ********************************
--     6000   6999    619 ******************************
--     7000   7999    618 *****************************
--     8000   8999    607 *****************************
--     9000   9999    560 ***************************
--    10000  10999    523 *************************
--    11000  11999    478 ***********************
--    12000  12999    429 ********************
--    13000  13999    379 ******************
--    14000  14999    366 *****************
--    15000  15999    353 *****************
--    16000  16999    329 ***************
--    17000  17999    297 **************
--    18000  18999    294 **************
--    19000  19999    283 *************
--    20000  20999    251 ************
--    21000  21999    195 *********
--    22000  22999    152 *******
--    23000  23999    132 ******
--    24000  24999     75 ***
--    25000  25999     66 ***
--    26000  26999     56 **
--    27000  27999     44 **
--    28000  28999     35 *
--    29000  29999     16 
--    30000  30999     21 *
--    31000  31999     18 
--    32000  32999     11 
--    33000  33999      8 
--    34000  34999      6 
--    35000  35999      6 
--    36000  36999     10 
--    37000  37999      2 
--    38000  38999      3 
--    39000  39999      2 
--    40000  40999      2 
--    41000  41999      2 
--    42000  42999      1 
-- Meryl attempt 1 begins.
----------------------------------------
-- Starting concurrent execution on Thu Oct 20 13:40:38 2016 with 6204.3 GB free disk space (1 processes; 8 concurrently)

    /data/kvijed/canuTest/ecoli-auto2/correction/0-mercounts/meryl.sh 1 > /data/kvijed/canuTest/ecoli-auto2/correction/0-mercounts/meryl.000001.out 2>&1

-- Finished on Thu Oct 20 13:40:59 2016 (21 seconds) with 6204 GB free disk space
----------------------------------------
-- Meryl finished successfully.
----------------------------------------
-- Starting command on Thu Oct 20 13:40:59 2016 with 6204 GB free disk space

    /usr/local/bin/canu-1.3/Linux-amd64/bin/meryl \
      -Dh \
      -s /data/kvijed/canuTest/ecoli-auto2/correction/0-mercounts/ecoli.ms16 \
    > /data/kvijed/canuTest/ecoli-auto2/correction/0-mercounts/ecoli.ms16.histogram \
    2> /data/kvijed/canuTest/ecoli-auto2/correction/0-mercounts/ecoli.ms16.histogram.info

-- Finished on Thu Oct 20 13:40:59 2016 (lickety-split) with 6204 GB free disk space
----------------------------------------
--
-- WARNING: gnuplot failed; no plots will appear in HTML output.
--
----------------------------------------
--
-- WARNING: gnuplot failed; no plots will appear in HTML output.
--
----------------------------------------
-- For mhap overlapping, set repeat k-mer threshold to 1157.
--
-- Found 115711421 16-mers; 89186744 distinct and 77230204 unique.  Largest count 37954.
--
-- OVERLAPPER (mhap) (correction)
--
-- Set corMhapSensitivity=low based on read coverage of 24145696.
--
-- PARAMETERS: hashes=256, minMatches=3, threshold=0.8
--
-- Given 6 GB, can fit 18000 reads per block.
-- For 2 blocks, set stride to 2 blocks.
-- Logging partitioning to '/data/kvijed/canuTest/ecoli-auto2/correction/1-overlapper/partitioning.log'.
-- Configured 1 mhap precompute jobs.
-- Configured 1 mhap overlap jobs.
-- mhap precompute attempt 0 begins with 0 finished, and 1 to compute.
----------------------------------------
-- Starting concurrent execution on Thu Oct 20 13:41:01 2016 with 6204.3 GB free disk space (1 processes; 2 concurrently)

    /data/kvijed/canuTest/ecoli-auto2/correction/1-overlapper/precompute.sh 1 > /data/kvijed/canuTest/ecoli-auto2/correction/1-overlapper/precompute.000001.out 2>&1

-- Finished on Thu Oct 20 13:42:14 2016 (73 seconds) with 6204.1 GB free disk space
----------------------------------------
-- All 1 mhap precompute jobs finished successfully.
-- mhap attempt 0 begins with 0 finished, and 1 to compute.
----------------------------------------
-- Starting concurrent execution on Thu Oct 20 13:42:14 2016 with 6204.1 GB free disk space (1 processes; 2 concurrently)

    /data/kvijed/canuTest/ecoli-auto2/correction/1-overlapper/mhap.sh 1 > /data/kvijed/canuTest/ecoli-auto2/correction/1-overlapper/mhap.000001.out 2>&1

-- Finished on Thu Oct 20 13:42:27 2016 (13 seconds) with 6204.1 GB free disk space
----------------------------------------
-- Found 1 mhap overlap output files.
----------------------------------------
-- Starting command on Thu Oct 20 13:42:27 2016 with 6204.1 GB free disk space

    /usr/local/bin/canu-1.3/Linux-amd64/bin/ovStoreBuild \
     -O /data/kvijed/canuTest/ecoli-auto2/correction/ecoli.ovlStore.BUILDING \
     -G /data/kvijed/canuTest/ecoli-auto2/correction/ecoli.gkpStore \
     -M 2-8 \
     -L /data/kvijed/canuTest/ecoli-auto2/correction/1-overlapper/ovljob.files \
     > /data/kvijed/canuTest/ecoli-auto2/correction/ecoli.ovlStore.err 2>&1

-- Finished on Thu Oct 20 13:42:27 2016 (lickety-split) with 6204.1 GB free disk space
----------------------------------------
--
-- Overlap store '/data/kvijed/canuTest/ecoli-auto2/correction/ecoli.ovlStore' successfully constructed.
--
-- Purged 0.212 GB in 3 overlap output files and 4 directories.
----------------------------------------
-- Starting command on Thu Oct 20 13:42:27 2016 with 6204.3 GB free disk space

    /usr/local/bin/canu-1.3/Linux-amd64/bin/ovStoreStats \
     -G /data/kvijed/canuTest/ecoli-auto2/correction/ecoli.gkpStore \
     -O /data/kvijed/canuTest/ecoli-auto2/correction/ecoli.ovlStore \
     -o /data/kvijed/canuTest/ecoli-auto2/correction/ecoli.ovlStore \
     > /data/kvijed/canuTest/ecoli-auto2/correction/ecoli.ovlStore.summary.err 2>&1

-- Finished on Thu Oct 20 13:42:27 2016 (lickety-split) with 6204.3 GB free disk space
----------------------------------------
--
-- Overlap store '/data/kvijed/canuTest/ecoli-auto2/correction/ecoli.ovlStore' contains:
--
--   category            reads     %          read length        feature size or coverage  analysis
--   ----------------  -------  -------  ----------------------  ------------------------  --------------------
--   middle-missing        164    1.31    12873.57 +- 8557.67       2044.83 +- 2835.39    (bad trimming)
--   middle-hump             0    0.00        0.00 +- 0.00             0.00 +- 0.00       (bad trimming)
--   no-5-prime              0    0.00        0.00 +- 0.00             0.00 +- 0.00       (bad trimming)
--   no-3-prime              0    0.00        0.00 +- 0.00             0.00 +- 0.00       (bad trimming)
--   
--   low-coverage         3921   31.30     6415.65 +- 5821.42          3.55 +- 2.05       (easy to assemble, potential for lower quality consensus)
--   unique                 19    0.15    11442.47 +- 5346.49         17.84 +- 4.27       (easy to assemble, perfect, yay)
--   repeat-cont             0    0.00        0.00 +- 0.00             0.00 +- 0.00       (potential for consensus errors, no impact on assembly)
--   repeat-dove             0    0.00        0.00 +- 0.00             0.00 +- 0.00       (hard to assemble, likely won't assemble correctly or even at all)
--   
--   span-repeat          6423   51.27    11681.77 +- 6822.49       8766.40 +- 5922.38    (read spans a large repeat, usually easy to assemble)
--   uniq-repeat-cont        0    0.00        0.00 +- 0.00                                (should be uniquely placed, low potential for consensus errors, no impact on assembly)
--   uniq-repeat-dove      372    2.97     9641.18 +- 5538.71                             (will end contigs, potential to misassemble)
--   uniq-anchor             0    0.00        0.00 +- 0.00             0.00 +- 0.00       (repeat read, with unique section, probable bad read)
----------------------------------------
-- Starting command on Thu Oct 20 13:42:27 2016 with 6204.3 GB free disk space

    /usr/local/bin/canu-1.3/Linux-amd64/bin/filterCorrectionOverlaps \
      -G /data/kvijed/canuTest/ecoli-auto2/correction/ecoli.gkpStore \
      -O /data/kvijed/canuTest/ecoli-auto2/correction/ecoli.ovlStore \
      -S /data/kvijed/canuTest/ecoli-auto2/correction/2-correction/ecoli.globalScores \
      -c 40 \
      -l 0 \
    > /data/kvijed/canuTest/ecoli-auto2/correction/2-correction/ecoli.globalScores.err 2>&1

-- Finished on Thu Oct 20 13:42:27 2016 (lickety-split) with 6204.3 GB free disk space
----------------------------------------
----------------------------------------
-- Starting command on Thu Oct 20 13:42:27 2016 with 6204.3 GB free disk space

    /usr/local/bin/canu-1.3/Linux-amd64/bin/generateCorrectionLayouts \
      -G /data/kvijed/canuTest/ecoli-auto2/correction/ecoli.gkpStore \
      -O /data/kvijed/canuTest/ecoli-auto2/correction/ecoli.ovlStore \
      -S /data/kvijed/canuTest/ecoli-auto2/correction/2-correction/ecoli.globalScores \
      -C 80 \
      -p /data/kvijed/canuTest/ecoli-auto2/correction/2-correction/ecoli.estimate

-- Finished on Thu Oct 20 13:42:28 2016 (1 second) with 6204.3 GB free disk space
----------------------------------------
--
-- WARNING: gnuplot failed; no plots will appear in HTML output.
--
----------------------------------------
-- Set corMinCoverage=4 based on read coverage of 24145696.
-- Using overlaps no worse than 0.30 fraction error for correcting reads (from corErrorRate parameter).
-- generate corrected reads attempt 0 begins with 0 finished, and 3 to compute.
----------------------------------------
-- Starting concurrent execution on Thu Oct 20 13:42:28 2016 with 6204.3 GB free disk space (3 processes; 16 concurrently)

    /data/kvijed/canuTest/ecoli-auto2/correction/2-correction/correctReads.sh 1 > /data/kvijed/canuTest/ecoli-auto2/correction/2-correction/correctReads.000001.out 2>&1
    /data/kvijed/canuTest/ecoli-auto2/correction/2-correction/correctReads.sh 2 > /data/kvijed/canuTest/ecoli-auto2/correction/2-correction/correctReads.000002.out 2>&1
    /data/kvijed/canuTest/ecoli-auto2/correction/2-correction/correctReads.sh 3 > /data/kvijed/canuTest/ecoli-auto2/correction/2-correction/correctReads.000003.out 2>&1

-- Finished on Thu Oct 20 13:42:29 2016 (1 second) with 6204.3 GB free disk space
----------------------------------------
-- Found 3 read correction output files.
-- Found 3 read correction output files.
-- Concatenating correctReads output.
-- Analyzing correctReads output.
--
-- WARNING: gnuplot failed; no plots will appear in HTML output.
--
----------------------------------------
--
-- WARNING: gnuplot failed; no plots will appear in HTML output.
--
----------------------------------------
--
-- Purging correctReads output after merging to final output file.
-- Purged 3 .dump.success sentinels.
-- Purged 3 .fasta outputs.
-- Purged 3 .err outputs.
-- Purged 3 .out job log outputs.
--
-- Corrected reads saved in '/data/kvijed/canuTest/ecoli-auto2/ecoli.correctedReads.fasta.gz'.
--
--
-- BEGIN TRIMMING
--
----------------------------------------
-- Starting command on Thu Oct 20 13:42:29 2016 with 6204.3 GB free disk space

    /usr/local/bin/canu-1.3/Linux-amd64/bin/gatekeeperCreate \
      -minlength 1000 \
      -o /data/kvijed/canuTest/ecoli-auto2/trimming/ecoli.gkpStore.BUILDING \
      /data/kvijed/canuTest/ecoli-auto2/trimming/ecoli.gkpStore.gkp \
    > /data/kvijed/canuTest/ecoli-auto2/trimming/ecoli.gkpStore.BUILDING.err 2>&1

-- Finished on Thu Oct 20 13:42:29 2016 (lickety-split) with 6204.3 GB free disk space
----------------------------------------
--
-- WARNING: gnuplot failed; no plots will appear in HTML output.
--
----------------------------------------
--
-- In gatekeeper store '/data/kvijed/canuTest/ecoli-auto2/trimming/ecoli.gkpStore':
--   Found 1 reads.
--   Found 9103 bases (1896.45 times coverage).
--
--   Read length histogram (one '*' equals 0.01 reads):
--        0    999      0 
--     1000   1999      0 
--     2000   2999      0 
--     3000   3999      0 
--     4000   4999      0 
--     5000   5999      0 
--     6000   6999      0 
--     7000   7999      0 
--     8000   8999      0 
--     9000   9999      1 **********************************************************************
-- Meryl attempt 0 begins.
----------------------------------------
-- Starting concurrent execution on Thu Oct 20 13:42:29 2016 with 6204.3 GB free disk space (1 processes; 8 concurrently)

    /data/kvijed/canuTest/ecoli-auto2/trimming/0-mercounts/meryl.sh 1 > /data/kvijed/canuTest/ecoli-auto2/trimming/0-mercounts/meryl.000001.out 2>&1

-- Finished on Thu Oct 20 13:42:30 2016 (1 second) with 6204.3 GB free disk space
----------------------------------------
-- Meryl finished successfully.
----------------------------------------
-- Starting command on Thu Oct 20 13:42:30 2016 with 6204.3 GB free disk space

    /usr/local/bin/canu-1.3/Linux-amd64/bin/meryl \
      -Dh \
      -s /data/kvijed/canuTest/ecoli-auto2/trimming/0-mercounts/ecoli.ms22 \
    > /data/kvijed/canuTest/ecoli-auto2/trimming/0-mercounts/ecoli.ms22.histogram \
    2> /data/kvijed/canuTest/ecoli-auto2/trimming/0-mercounts/ecoli.ms22.histogram.info

-- Finished on Thu Oct 20 13:42:30 2016 (lickety-split) with 6204.3 GB free disk space
----------------------------------------
----------------------------------------
-- Starting command on Thu Oct 20 13:42:30 2016 with 6204.3 GB free disk space

    /usr/local/bin/canu-1.3/Linux-amd64/bin/estimate-mer-threshold  \
      -m /data/kvijed/canuTest/ecoli-auto2/trimming/0-mercounts/ecoli.ms22  \
    > /data/kvijed/canuTest/ecoli-auto2/trimming/0-mercounts/ecoli.ms22.estMerThresh.out \
    2> /data/kvijed/canuTest/ecoli-auto2/trimming/0-mercounts/ecoli.ms22.estMerThresh.err

-- Finished on Thu Oct 20 13:42:30 2016 (lickety-split) with 6204.3 GB free disk space
----------------------------------------
--
-- WARNING: gnuplot failed; no plots will appear in HTML output.
--
----------------------------------------
--
-- WARNING: gnuplot failed; no plots will appear in HTML output.
--
----------------------------------------
----------------------------------------
-- Starting command on Thu Oct 20 13:42:30 2016 with 6204.3 GB free disk space

    /usr/local/bin/canu-1.3/Linux-amd64/bin/meryl \
      -Dt \
      -n 2 \
      -s /data/kvijed/canuTest/ecoli-auto2/trimming/0-mercounts/ecoli.ms22 \
    > /data/kvijed/canuTest/ecoli-auto2/trimming/0-mercounts/ecoli.ms22.frequentMers.fasta \
    2> /data/kvijed/canuTest/ecoli-auto2/trimming/0-mercounts/ecoli.ms22.frequentMers.fasta.err

-- Finished on Thu Oct 20 13:42:30 2016 (lickety-split) with 6204.3 GB free disk space
----------------------------------------
-- Reset obtOvlMerThreshold from auto to 2.
--
-- Found 9082 22-mers; 9082 distinct and 9082 unique.  Largest count 1.
--
-- OVERLAPPER (normal) (trimming) erate=0.075
--
----------------------------------------
-- Starting command on Thu Oct 20 13:42:30 2016 with 6204.3 GB free disk space

    /usr/local/bin/canu-1.3/Linux-amd64/bin/overlapInCorePartition \
     -g  /data/kvijed/canuTest/ecoli-auto2/trimming/ecoli.gkpStore \
     -bl 100000000 \
     -bs 0 \
     -rs 2000000 \
     -rl 0 \
     -ol 500 \
     -o  /data/kvijed/canuTest/ecoli-auto2/trimming/1-overlapper/ecoli.partition \
    > /data/kvijed/canuTest/ecoli-auto2/trimming/1-overlapper/ecoli.partition.err 2>&1

-- Finished on Thu Oct 20 13:42:30 2016 (lickety-split) with 6204.3 GB free disk space
----------------------------------------
--
-- Configured 0 overlapInCore jobs.
-- Found 0 overlapInCore output files.
--
-- overlapInCore compute '/data/kvijed/canuTest/ecoli-auto2/trimming/1-overlapper':
--   kmer hits
Illegal division by zero at /usr/local/bin/canu-1.3/Linux-amd64/bin/lib/canu/OverlapInCore.pm line 239.
kvijed@bioseq01:~/canuTest$

**Comment by skoren** [comment]
Ah the issue is your command is setting ```genomeSize=4.8``` which means 5bp. It should be 4.8m. In your first comment, it was correctly set as 4.8m so I'm not sure if it was always set incorrectly or only in your latest example but that is definitely the cause of the crash (there is only one corrected reads so nothing to assemble). The latest Canu has been fixed to provide a warning for this.

**Comment by JahnDavik** [comment]
Thank you.
That seem to do it.
Provided the assembly file is supposed to be 'ecoli.contigs.fasta' containing one fasta sequence, canu appear to run properly on my computer.
