### ISSUE TITLE
"canu -assemble" failed and no fasta file was created

### ISSUE THREAD

**Issue by CeciliaDeng** [marbl/canu#276]
Hi 

I ran canu assemly using the cleaned/trimmed reads as:

`canu -assemble useGrid=0 maxMemory=800 maxThreads=40 -p $prefix -d $outDir genomeSize=670m errorRate=0.013 -pacbio-corrected RG-auto_Trim/RG.trimmedReads.fasta.gz > 04_Assemble.log 04_Assemble.err`

After running for a day, the process exit without any fasta files created. The unitigging.html has empty "Overlap Error Adjustment", "Consensus", and "Final Outputs" sections.

`grep failed 04_Assemble.err` reported:

> -- 3 read error detection jobs failed:
> -- 131 overlap error adjustment jobs failed:
> Don't panic, but a mostly harmless error occurred and canu failed.
> canu failed with 'failed to adjust overlap error rates.  Made 2 attempts, jobs still failed'.

What caused the above failed attempts? How to fix the problem and let canu continue to do the assembly?

The raw PacBio datasets were cleaned and trimmed using commands:

`canu -correct useGrid=0 maxMemory=800 maxThreads=40 -p RG -d RG-auto genomeSize=670m -pacbio-raw 01_data/*.fastq` 

and

`canu -trim useGrid=0 maxMemory=800 maxThreads=40 -p RG -d RG-auto_Trim genomeSize=670m -pacbio-corrected RG-auto/RG.correctedReads.fasta.gz`

Thank you for your help.

**Comment by brianwalenz** [comment]
You're showing two sets if errors.

The first set, in 'read error detection' was resolved by canu automagically rerunning the jobs.  There might be useful messages in unitigging/3-overlapErrorAdjustment/red.*.out, but I suspect these were overwritten on the rerun.

The second set, in 'overlap error adjustment' failed on apparently every job.  Look for errors in the oea.*.out files.  I'm going to guess memory is being exhausted.

What `canu -version` are you using?  Does the machine have > 800gb memory?

For debugging, you can run the jobs by hand as `oea.sh 1`, `oea.sh 2`, etc.  If it is indeed memory, running each job individually should work.  You can set oeaConcurrency to limit the number of jobs that are run at the same time.  Right now, it should be trying to run 40 at the same time.

As for continuing, just restart Canu without removing any files.  It'll figure out where it needs to start up again.

**Comment by brianwalenz** [comment]
No response.
