### ISSUE TITLE
How to configure slurm to make use of grid?

### ISSUE THREAD

**Issue by gwaldbieser** [marbl/canu#278]
I'm trying to figure out parameters via slurm to use multiple nodes for a canu assembly. I have invoked canu with or without slurm I get the same message regarding available threads. The grid has 57 nodes available with 40 cores each. No matter how many nodes (N) or cores (n) I ask for, I get the same output in the log file.

$cat slurm.batch
#!/bin/bash
#SBATCH --job-name=bluecanu1
#SBATCH -p short
#SBATCH -N 32
#SBATCH -n 40
#SBATCH -t 48:00:00
date
module load canu/gcc/64/1.2
canu -p BPB1 -d BPB1 genomeSize=1.1g -pacbio-raw /project/blue_catfish_genome/*.gz 1>run1.log 2>&1
date
#End of file

#cmdline for submitting grid job
$sbatch slurm.batch

**beginning of the log file:**
```
$cat run1.log
-- Detected Java(TM) Runtime Environment '1.8.0_60' (from 'java').
-- Detected 40 CPUs and 126 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /usr/bin/sinfo.

-- Found  57 hosts with  40 cores and  125 GB memory under Slurm control.
-- Found   2 hosts with 120 cores and 1513 GB memory under Slurm control.
-- Found   3 hosts with 120 cores and 1513 GB memory under Slurm control.

-- Allowed to run under grid control, and use up to  13 compute threads and   41 GB memory for stage 'bogart (unitigger)'.
-- Allowed to run under grid control, and use up to  10 compute threads and   31 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run under grid control, and use up to  10 compute threads and   31 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run under grid control, and use up to  10 compute threads and   31 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run under grid control, and use up to   8 compute threads and   16 GB memory for stage 'read error detection (overlap error adjustment)'.
-- Allowed to run under grid control, and use up to   1 compute thread  and    2 GB memory for stage 'overlap error adjustment'.
-- Allowed to run under grid control, and use up to   8 compute threads and   25 GB memory for stage 'utgcns (consensus'.
-- Allowed to run under grid control, and use up to   1 compute thread  and    3 GB memory for stage 'overlap store parallel bucketizer'.
-- Allowed to run under grid control, and use up to   1 compute thread  and    3 GB memory for stage 'overlapper'.
-- Allowed to run under grid control, and use up to   8 compute threads and   12 GB memory for stage 'overlapper'.
-- Allowed to run under grid control, and use up to   8 compute threads and   12 GB memory for stage 'overlapper'.
-- Allowed to run under grid control, and use up to  30 compute threads and  125 GB memory for stage 'meryl (k-mer counting)'.
-- Allowed to run under grid control, and use up to   4 compute threads and   12 GB memory for stage 'falcon_sense (read correction)'.
-- Allowed to run under grid control, and use up to  10 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run under grid control, and use up to  10 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run under grid control, and use up to  10 compute threads and    6 GB memory for stage 'minimap (overlapper)'.

-- This is canu parallel iteration #1, out of a maximum of 2 attempts.
................................................................................................
```

#Alternatively, this cmdline does not invoke slurm:
```
$ canu -p BPB1 -d BPB1 genomeSize=1.1g -pacbio-raw /project/blue_catfish_genome/*.gz 1>run1.log 2>&1 &
```

It returns the same log information as above. 
I was thinking canu identified the available architecture and adjusted accordingly. How can I make use of the large number of available cores? Thanks for any suggestions. 
Geoff

**Comment by skoren** [comment]
Are you submitting the script you posted to the grid? Canu will take care of the submission for you, something like:
```
-- Starting command on Thu Oct 20 19:06:20 2016 with 575610.282 GB free disk space

    sbatch \
      --mem-per-cpu=8g \
      --cpus-per-task=1 \
      --time=24:00:00 \
      --partition norm,b1  \
      -D `pwd` \
      -J "canu_asm" \
      -o asm/canu-scripts/canu.14.out asm/canu-scripts/canu.01.sh
25184677

```
If you launch the command on a head node, it will detect resources and submit itself automatically. The resources won't change (because they're based on maximizing how many processes will run) but the parallel steps will submit large array jobs to use the cores.

You can add arbitrary restrictions to pass to the scheduler (like time or partition) using gridOptions: ```gridOptions="--time=24:00:00 --partition norm,b1" ```, however you should not request memory or CPU, Canu will handle that.

**Comment by gwaldbieser** [comment]
Yes, the script I posted was submitted to the grid. When I run on a different machine (single node with 64 cpus and 504GB available memory) the concurrent jobs are able to utilize more threads per concurrent job (see below), so I'm thinking I'm not setting up slurm appropriately.  Is the information at the beginning of the log file regarding compute threads the actual resources that canu will use on this run? If so, the grid is providing fewer resources than the single node machine.

-- Detected Java(TM) Runtime Environment '1.8.0_71' (from 'java').
-- Detected 64 CPUs and 504 gigabytes of memory.
-- No grid engine detected, grid disabled.

-- Allowed to run   4 jobs concurrently, and use up to  16 compute threads and  126 GB memory for stage 'bogart (unitigger)'.
-- Allowed to run   4 jobs concurrently, and use up to  16 compute threads and   32 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   4 jobs concurrently, and use up to  16 compute threads and   32 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   4 jobs concurrently, and use up to  16 compute threads and   32 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   8 jobs concurrently, and use up to   8 compute threads and    8 GB memory for stage 'read error detection (overlap er
ror adjustment)'.
-- Allowed to run  64 jobs concurrently, and use up to   1 compute thread  and    2 GB memory for stage 'overlap error adjustment'.
-- Allowed to run   8 jobs concurrently, and use up to   8 compute threads and   72 GB memory for stage 'utgcns (consensus'.
-- Allowed to run  64 jobs concurrently, and use up to   1 compute thread  and    4 GB memory for stage 'overlap store parallel bucketize
r'.
-- Allowed to run  64 jobs concurrently, and use up to   1 compute thread  and   32 GB memory for stage 'overlap store parallel sorting'.
-- Allowed to run  64 jobs concurrently, and use up to   1 compute thread  and    7 GB memory for stage 'overlapper'.
-- Allowed to run   8 jobs concurrently, and use up to   8 compute threads and   12 GB memory for stage 'overlapper'.
-- Allowed to run   8 jobs concurrently, and use up to   8 compute threads and   12 GB memory for stage 'overlapper'.
-- Allowed to run   2 jobs concurrently, and use up to  32 compute threads and  252 GB memory for stage 'meryl (k-mer counting)'.
-- Allowed to run  16 jobs concurrently, and use up to   4 compute threads and   31 GB memory for stage 'falcon_sense (read correction)'.
-- Allowed to run   4 jobs concurrently, and use up to  16 compute threads and   32 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   4 jobs concurrently, and use up to  16 compute threads and   32 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   4 jobs concurrently, and use up to  16 compute threads and   32 GB memory for stage 'minimap (overlapper)'.

**Comment by skoren** [comment]
No both runs are correct. Your slurm is properly set up.

The report is listing per-job thread/memory usage. For example the second line in the second report will use 16 threads/32gb of memory for MHAP and run 4 jobs at a time (so it will be using all 64 threads on the machine). On the grid, you have majority of hosts (57) with 40 cores and 125GB of memory. Here the same MHAP job will use 10 cores and 31gb of memory. That means each of the 57 machines can support 4 jobs so you can run 4*57 = 228 jobs using 2,280 cores total, much more than you would on a single machine. If on the grid Canu had tried to use 16 threads/32gb of memory per job (as on the single node), it would only be able to fit 2 jobs per host or 2*57 = 114 jobs using 1,824 cores. So the parameters it picked on Slurm let is use 400 cores more for the overlapping step which is why each job is using less memory/threads but more of them will run.
