### ISSUE TITLE
canu keeps running forever

### ISSUE THREAD

**Issue by JahnDavik** [marbl/canu#280]
Hi,
I am running a pacbio data set on my 256GB linux server. It has been running for a month or so and I start wondering whether this is to be expected. I've submitted the following code:
/usr/local/bin/canu-1.3/Linux-amd64/bin/canu \
-p Rida_02 -d Rida-auto_02 \
genomeSize=275m \
errorRate=0.2 \
corMaxEvidenceErate=0.15 \
-pacbio-raw pb14.fastq

The pb14.fastq is supposed to cover 70X of the 275Mbp genome.
There are 54 overlapInCore jobs and canu is currently chewing its way through the twenty-second (22th).

Does this sound normal? Should I kill the job? Use other parameters? Go for a larger computer?

Feedback is greatly appreciated.
Thank you.
Jahn

**Comment by skoren** [comment]
The problem is setting error rate to 0.2. This is the corrected error rate and defaults to 0.025 for PacBio (or 10x less than your setting). You can even set it to 0.015 for P6 PacBio data. Setting it to 0.2 will significantly slow down the assembly and will probably cause errors later.

I also wouldn't set the corMaxEvidenceErate parameter unless you have a high or low GC genome (e.g. <30 or >70).

**Comment by JahnDavik** [comment]
OK. I interpret you as just kill the job and rerun.
Thank you.
Jahn

**Comment by skoren** [comment]
You can start after correction by using -pacbio-corrected and the Rida_02.correctedReads.fasta.gz file in Rida-auto_02.

**Comment by JahnDavik** [comment]
OK.
But not setting the error rate? Let canu handle that by itself?
g

**Comment by skoren** [comment]
Yes, that's right. Worth checking how much corrected read coverage you have which could have been affected by corMaxEvidenceErate. If you have at least 25+X it should be fine.

**Comment by JahnDavik** [comment]
I did a rough calculation and ended somewhere around 30X. It is a de novo organism so it is not totally settled.

j

**Comment by JahnDavik** [comment]
So, you would kill the job I assume?

Thank you for getting back to me.


best

jahn



________________________________
Fra: Sergey Koren <notifications@github.com>
Sendt: 24. oktober 2016 16:19
Til: marbl/canu
Kopi: Jahn Davik; Author
Emne: Re: [marbl/canu] canu keeps running forever (#280)


The problem is setting error rate to 0.2. This is the corrected error rate and defaults to 0.025 for PacBio (or 10x less than your setting). You can even set it to 0.015 for P6 PacBio data. Setting it to 0.2 will significantly slow down the assembly and will probably cause errors later.

I also wouldn't set the corMaxEvidenceErate parameter unless you have a high or low GC genome (e.g. <30 or >70).

-

**Comment by skoren** [comment]
Yes
