### ISSUE TITLE
Need your attention for canu gridOptions error

### ISSUE THREAD

**Issue by shameem356** [marbl/canu#282]
I have used '**gridOptions** (gridOptions=gnx)' and started the assembly. gkpStore building part finished successfully and meryl.sh returned with an error '**sbatch: error: Unable to open file gnx**'.Below was is the meryl.jobSubmit.sh and there I noticed that error is due to missing -p option  for grid partition name.I have added **-p** before grid partition (gnx) and restarted meryl.jobSubmit.sh and it worked fine.

sbatch gnx  --mem-per-cpu=2560m --cpus-per-task=8 -D `pwd` -J "meryl_assembly_DNBC5" -a 1-1 -o /assembly-DNBC5/unitigging/0-mercounts/meryl.%A_%a.out /assembly-DNBC5/unitigging/0-mercounts/meryl.sh 0

Here I need your attention to solve this issue by adding **-p** in canu source code if gridOptions is mentioned.

**Comment by skoren** [comment]
The gridOptions are passed directly to the scheduler, you need to add the -p to your command: ```gridOptions="-p gnx". Canu is generic among many grids and you can request more than just a partition (like time limits) so we won't add implicit flags to this option.

**Comment by skoren** [comment]
The gridOptions is generic, it is passed as is to the scheduler so you need to add the -p option yourself: ```gridOptions="-p gnx". Canu is generic for multiple grids/schedulers and you can request more that just a partition (like time limits) with this option so we won't add implicit flags to it.
