### ISSUE TITLE
Canu Grid (lsf) Error : It does work without grid though!

### ISSUE THREAD

**Issue by MehmetGoktay** [marbl/canu#284]
Hi Everyone,

I have been struggling with lsf system for 1 week to make it run Canu successfully but unfortunately I have not got any progress yet. 

Please have a look at output below I will paste my script and program output below.

```
canu -p ecoli -d ecoli-auto java=/usr/lib/jvm/java-8-oracle/bin/java genomeSize=4.8m -pacbio-raw EcoliSmallExmp.fastq useGrid=true gridOptions='-q multicore20 -e err.out -o std.out'

-- Detected 48 CPUs and 252 gigabytes of memory.
-- Detected Java(TM) Runtime Environment '1.8.0_72' (from '/usr/lib/jvm/java-8-oracle/bin/java').
-- Detected LSF with 'bsub' binary in /opt/lsf/8.3/linux2.6-glibc2.3-x86_64/bin/bsub.
-- 
-- Found   1 host  with  16 cores and   16 GB memory under LSF control.
-- Found   5 hosts with  48 cores and  252 GB memory under LSF control.
-- Found   1 host  with  64 cores and  252 GB memory under LSF control.
-- Found   1 host  with  16 cores and  126 GB memory under LSF control.
-- Found   2 hosts with  64 cores and  505 GB memory under LSF control.
-- Found   1 host  with  48 cores and  505 GB memory under LSF control.
-- 
-- On LSF detected memory is requested in MB
-- 
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
--
-- Allowed to run under grid control, and use up to   4 compute threads and    4 GB memory for stage 'bogart (unitigger)'.
-- Allowed to run under grid control, and use up to  16 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run under grid control, and use up to  16 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run under grid control, and use up to  16 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run under grid control, and use up to   4 compute threads and    4 GB memory for stage 'read error detection (overlap error adjustment)'.
-- Allowed to run under grid control, and use up to   1 compute thread  and    2 GB memory for stage 'overlap error adjustment'.
-- Allowed to run under grid control, and use up to   4 compute threads and    8 GB memory for stage 'utgcns (consensus'.
-- Allowed to run under grid control, and use up to   1 compute thread  and    4 GB memory for stage 'overlap store sequential building'.
-- Allowed to run under grid control, and use up to   1 compute thread  and    2 GB memory for stage 'overlap store parallel bucketizer'.
-- Allowed to run under grid control, and use up to   1 compute thread  and    4 GB memory for stage 'overlap store parallel sorting'.
-- Allowed to run under grid control, and use up to   1 compute thread  and    2 GB memory for stage 'overlapper'.
-- Allowed to run under grid control, and use up to   8 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run under grid control, and use up to   8 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run under grid control, and use up to   4 compute threads and    4 GB memory for stage 'meryl (k-mer counting)'.
-- Allowed to run under grid control, and use up to   4 compute threads and    8 GB memory for stage 'falcon_sense (read correction)'.
--
-- This is canu parallel iteration #1, out of a maximum of 2 attempts.
--
-- Final error rates before starting pipeline:
--   
--   genomeSize          -- 4800000
--   errorRate           -- 0.025
--   
--   corOvlErrorRate     -- 0.075
--   obtOvlErrorRate     -- 0.075
--   utgOvlErrorRate     -- 0.075
--   
--   obtErrorRate        -- 0.075
--   
--   utgGraphErrorRate   -- 0.05
--   utgBubbleErrorRate  -- 0.0625
--   utgMergeErrorRate   -- 0.0375
--   utgRepeatErrorRate  -- 0.05
--   
--   corErrorRate        -- 0.30
--   cnsErrorRate        -- 0.0625
--
--
-- BEGIN CORRECTION
--
--
-- GATEKEEPER (correction)
--
--
-- Starting command on Tue Oct 25 17:00:04 2016 with 76478.3 GB free disk space
--
/opt/share/software/packages/canu-1.0/Linux-amd64/bin/gatekeeperCreate \
  -minlength 1000 \
  -o /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/correction/ecoli.gkpStore.BUILDING \
  /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/correction/ecoli.gkpStore.gkp \
> /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/correction/ecoli.gkpStore.err 2>&1
--
-- Finished on Tue Oct 25 17:00:07 2016 (3 seconds) with 76477.9 GB free disk space
--
-- In gatekeeper store '/netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/correction/ecoli.gkpStore':
--   Found 12528 reads.
--   Found 115899341 bases (24.14 times coverage).
--
--   Read length histogram (one '*' equals 20.62 reads):
--        0    999      0 
--     1000   1999   1444 **********************************************************************
--     2000   2999   1328 ****************************************************************
--     3000   3999   1065 ***************************************************
--     4000   4999    774 *************************************
--     5000   5999    668 ********************************
--     6000   6999    619 ******************************
--     7000   7999    618 *****************************
--     8000   8999    607 *****************************
--     9000   9999    560 ***************************
--    10000  10999    523 *************************
--    11000  11999    478 ***********************
--    12000  12999    429 ********************
--    13000  13999    379 ******************
--    14000  14999    366 *****************
--    15000  15999    353 *****************
--    16000  16999    329 ***************
--    17000  17999    297 **************
--    18000  18999    294 **************
--    19000  19999    283 *************
--    20000  20999    251 ************
--    21000  21999    195 *********
--    22000  22999    152 *******
--    23000  23999    132 ******
--    24000  24999     75 ***
--    25000  25999     66 ***
--    26000  26999     56 **
--    27000  27999     44 **
--    28000  28999     35 *
--    29000  29999     16 
--    30000  30999     21 *
--    31000  31999     18 
--    32000  32999     11 
--    33000  33999      8 
--    34000  34999      6 
--    35000  35999      6 
--    36000  36999     10 
--    37000  37999      2 
--    38000  38999      3 
--    39000  39999      2 
--    40000  40999      2 
--    41000  41999      2 
--    42000  42999      1 
-- MERYL (correction)
-- Meryl attempt 1 begins.
--
-- Starting command on Tue Oct 25 17:00:09 2016 with 76477.9 GB free disk space
--
  bsub \
    -q multicore20 -e err.out -o std.out  -M 4096 -n 4 \
    -J "meryl_ecoli[1-1]" \
     \
    -o /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/correction/0-mercounts/meryl.%I.out \
    /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/correction/0-mercounts/meryl.sh

--
-- Finished on Tue Oct 25 17:00:09 2016 (0 seconds) with 76477.9 GB free disk space
--
-- Starting command on Tue Oct 25 17:00:09 2016 with 76477.9 GB free disk space
--
bsub \
  -M 6144 \
  -n 1 \
  -q multicore20 \
  -e err.out \
  -o std.out  \
  -w "numended("meryl_ecoli[1-1]", *)" \
  -J "canu_ecoli" \
  -o /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/canu-scripts/canu.01.out /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/canu-scripts/canu.01.sh
meryl_ecoli[1-1]: Job array does not exist. Job not submitted.
--
-- Finished on Tue Oct 25 17:00:09 2016 (0 seconds) with 76477.9 GB free disk space

ERROR: Failed with 

================================================================================
Please panic.  canu failed, and it shouldn't have.

Stack trace:

 at /opt/share/software/packages/canu-1.0/Linux-amd64/bin/lib/canu/Defaults.pm line 220
    canu::Defaults::caFailure('Failed to submit script', undef) called at /opt/share/software/packages/canu-1.0/Linux-amd64/bin/lib/canu/Execution.pm line 842
    canu::Execution::submitScript('/netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/e...', 'ecoli', 'meryl_ecoli[1-1]') called at /opt/share/software/packages/canu-1.0/Linux-amd64/bin/lib/canu/Execution.pm line 1128
    canu::Execution::submitOrRunParallelJob('/netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/e...', 'ecoli', 'meryl', '/netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/e...', 'meryl', 1) called at /opt/share/software/packages/canu-1.0/Linux-amd64/bin/lib/canu/Meryl.pm line 333
    canu::Meryl::merylCheck('/netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/e...', 'ecoli', 'cor') called at /opt/share/software/packages/canu-1.0/Linux-amd64/bin/canu line 402


canu failed with 'Failed to submit script'.
/netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/canu-scripts/canu.01.sh: 24: /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/canu-scripts/canu.01.sh: Syntax error: Unterminated quoted string
```

**Comment by skoren** [comment]
LSF has the least testing so it is possible there is some variation between versions which is causing an issue. Does the meryl job get submitted:

```
  bsub \
    -q multicore20 -e err.out -o std.out  -M 4096 -n 4 \
    -J "meryl_ecoli[1-1]" \
     \
    -o /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/correction/0-mercounts/meryl.%I.out \
    /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/correction/0-mercounts/meryl.sh
```
If you run that command by hand does it run OK and submit a job or not? That would help diagnose if the error is the hold request in the next job or the original job itself.

**Comment by MehmetGoktay** [comment]
Hi skoren,

I have run this script by hand as you told me and apparently it submitted and worked.

I will paste below mery1.out file.

Sender: LSF System <hpcadmin@dell-node-3.mpipz.mpg.de>
Subject: Job 4364179[1]: <meryl_ecoli[1-1]> Done

Job <meryl_ecoli[1-1]> was submitted from host <dell-node-3.mpipz.mpg.de> by user <goktay> in cluster <biocluster>.
Job was executed on host(s) <1*dell-node-3.mpipz.mpg.de>, in queue <multicore20>, as user <goktay> in cluster <biocluster>.
                            <3*dell-node-4.mpipz.mpg.de>
</home/goktay> was used as the home directory.
</netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/correction/0-mercounts> was used as the working directory.
Started at Tue Oct 25 17:04:39 2016
Results reported at Tue Oct 25 17:19:08 2016

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
/netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/correction/0-mercounts/meryl.sh
------------------------------------------------------------

Successfully completed.

Resource usage summary:

    CPU time   :     78.05 sec.
    Max Memory :       221 MB
    Max Swap   :       294 MB

    Max Processes  :         4
    Max Threads    :         9

The output (if any) follows:

Can fit 4655677440 mers into table with prefix of 28 bits, using 3276.000MB (0.000MB for positions)


PS:

Read file <err.out> for stderr output of this job.

Sender: LSF System <hpcadmin@dell-node-7.mpipz.mpg.de>
Subject: Job 4366754[1]: <meryl_ecoli[1-1]> Done

Job <meryl_ecoli[1-1]> was submitted from host <dell-node-2.mpipz.mpg.de> by user <goktay> in cluster <biocluster>.
Job was executed on host(s) <4*dell-node-7.mpipz.mpg.de>, in queue <multicore20>, as user <goktay> in cluster <biocluster>.
</home/goktay> was used as the home directory.
</netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto> was used as the working directory.
Started at Wed Oct 26 10:17:32 2016
Results reported at Wed Oct 26 10:18:22 2016

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
/netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/correction/0-mercounts/meryl.sh
------------------------------------------------------------

Successfully completed.

Resource usage summary:

    CPU time   :     84.76 sec.
    Max Memory :        52 MB
    Max Swap   :       166 MB

    Max Processes  :         4
    Max Threads    :         5

The output (if any) follows:

Can fit 4655677440 mers into table with prefix of 28 bits, using 3276.000MB (0.000MB for positions)


PS:

Read file <err.out> for stderr output of this job.

**Comment by MehmetGoktay** [comment]
Additionally I also tried to run second script by hand but it did not work. It gave me same error (meryl_ecoli[1-1]: Job array does not exist. Job not submitted.)

Script was : bsub -M 6144 -n 1 -q multicore20 -e err.out -o std.out -w "numended("meryl_ecoli[1-1]", *)" -J "canu_ecoli" -o /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/canu-scripts/canu.01.out /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/canu-scripts/canu.01.sh

**Comment by MehmetGoktay** [comment]
Hi Skoren,

Is it possible to give me a suggestion to solve this problem? (The guys who work in the IT does not like me when I send a job without lsf system) :D

**Comment by skoren** [comment]
So then the question is if your LSF doesn't support holding for jobs by name. Remove all the ecoli.\* files in the 0-mercounts folder. Then try to run the first command:
```
  bsub \
    -q multicore20 -e err.out -o std.out  -M 4096 -n 4 \
    -J "meryl_ecoli[1-1]" \
     \
    -o /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/correction/0-mercounts/meryl.%I.out \
    /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/correction/0-mercounts/meryl.sh
```

Then, while it is running (this won't work if it already finished), try submitting either the second command:
```
bsub \
  -M 6144 \
  -n 1 \
  -q multicore20 \
  -e err.out \
  -o std.out  \
  -w "numended("meryl_ecoli[1-1]", *)" \
  -J "canu_ecoli" \
  -o /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/canu-scripts/canu.01.out /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/canu-scripts/canu.01.sh
```
or
```
bsub \
  -M 6144 \
  -n 1 \
  -q multicore20 \
  -e err.out \
  -o std.out  \
  -w "numended("<job number>[1-1]", *)" \
  -J "canu_ecoli" \
  -o /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/canu-scripts/canu.01.out /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/canu-scripts/canu.01.sh
```
replacing <job number> with whatever ID the first job is assigned (it was 4366754 in your previous comment so you would have used ```-w "numended("4366754[1-1]", *)"```. See if either of those work.

**Comment by MehmetGoktay** [comment]
No, I doesnt work. 

first I did run this script: 
bsub -q multicore20 -e err.out -o std.out  -M 4096 -n 4  -J "meryl_ecoli[1-1]" -o /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/correction/0-mercounts/meryl.%I.out /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/correction/0-mercounts/meryl.sh

When I run this script (while first one was running)
bsub -M 6144 -n 1 -q multicore20 -e err.out -o std.out -w "numended("4373104[1-1]", *)" -J "canu_ecoli" -o /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/canu-scripts/canu.01.out /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/canu-scripts/canu.01.sh

(I changed the previos job id as you told me but still it didnt work) I got this error: 4373104[1-1]: Job array does not exist. Job not submitted

This funny thing when I run just this script as I m supposed to run in normal cases : canu -p ecoli -d ecoli-auto java=/usr/lib/jvm/java-8-oracle/bin/java genomeSize=4.8m -pacbio-raw EcoliSmallExmp.fastq useGrid=true gridOptions='-q multicore20 -e err.out -o std.out'

Let's say this script submitted with 4373134 to the lsf system and it fails. It made some other submissions and 4373137 returns successful. When I have checked which script worked properly I saw this one.

Job <4373137[1]>, Job Name <meryl_ecoli[1]>, User <goktay>, Project <default>, 
                     Status <DONE>, Queue <multicore20>, Command </netscratch/d
                     ep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/
                     correction/0-mercounts/meryl.sh>, Share group charged </go
                     ktay>
Thu Oct 27 17:41:00: Submitted from host <dell-node-11.mpipz.mpg.de>, CWD </net
                     scratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ec
                     oli-auto/correction/0-mercounts>, Output File </netscratch
                     /dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-aut
                     o/correction/0-mercounts/meryl.%I.out>, Error File <err.ou
                     t>, 4 Processors Requested;
I think I will not be able to use grid system anyway. It is too complicated for me. May be I should just use one computer rather than grid system.

**Comment by skoren** [comment]
What about just
```
bsub -M 6144 -n 1 -q multicore20 -e err.out -o std.out -w "numended(<jobid>, *)" -J "canu_ecoli" -o /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/canu-scripts/canu.01.out /netscratch/dep_coupland/grp_hancock/MehmetRuns/EcoliPacBio/ecoli-auto/canu-scripts/canu.01.sh
```
that is removing the [1-1] and the quotes?

If you want to run on a single machine you can add the option useGrid=false to the canu command line and submit the canu command (e.g. canu -p ecoli -d ecoli-auto java=/usr/lib/jvm/java-8-oracle/bin/java genomeSize=4.8m -pacbio-raw EcoliSmallExmp.fastq useGrid=false) to the grid. It will then run Canu on one machine in the grid.

**Comment by brianwalenz** [comment]
No response.  Update and reopen if needed.
