### ISSUE TITLE
canu on human P5-C3 dataset

### ISSUE THREAD

**Issue by mke135** [marbl/canu#287]
Dear,

I want to ask few questions about canu on PacBio P5-C3 human (CHM1) assembly.
1.	How much hard disk space did canu require
2.	As mentioned in the paper of canu, canu+quiver will take 22749 cpu hour on this dataset. And I want to ask the running time for canu.

Thanks,
mke

**Comment by skoren** [comment]
1. Canu typically requires 1-2TB for a human assembly. To be safe I'd recommend having 5tb free

2. It requires about 17k cpu hours, Quiver requires about =5000 cpu hours on a human-sized genome.

**Comment by mke135** [comment]
Noted, thanks!
