### ISSUE TITLE
bogart repeat annotation

### ISSUE THREAD

**Issue by brianwalenz** [marbl/canu#29]
Bogart computes repeat boundaries and possibly splits repeats on those boundaries.  If a split occurs, the reads/unitigs that result are not marked as being from a repeat region, nor are the unsplit regions marked as possibly containing a repeat.  Both markings should be captured.

**Comment by aphillippy** [comment]
repeat boundary annotation would be fantastic, and could form basis of a future string graph output -- for those that prefer that model over unitig graph

**Comment by brianwalenz** [comment]
reads split out are marked as repeat, but the unsplit regions are not marked.  tracked elsewhere.
