### ISSUE TITLE
Code to view overlap graph

### ISSUE THREAD

**Issue by mchaisso** [marbl/canu#291]
Hi,
  I'm debugging (again) some assembly issues with low-coverage very small assemblies.   One thing that would help is the ability to view the overlap graph.  What file contains the overlap information and is there an easy way to transform into a gml/dot file?

Thanks!
-mark

**Comment by skoren** [comment]
There are several gfa outputs in the 4-unitigger folder which has various states of the assembly (all overlaps, best overlaps, final overlaps). If you re-run bogart with the -D most flag, it will generate intermediate GFAs showing how overlaps change through all its filtering steps.

If there are specific reads you are interested in, the ovStoreDump command can print a picture of all overlaps for a given read or can be queried to see if a specific overlap exists.
