### ISSUE TITLE
stopbefore parameter error

### ISSUE THREAD

**Issue by ruiguo-bio** [marbl/canu#294]
I use stopBefore=correction, but canu says
ERROR:  Invalid stopBefore specified (correction); must be one of:
ERROR:      'gatekeeper'
ERROR:      'meryl'
ERROR:      'trimReads'
ERROR:      'splitReads'
ERROR:      'red'
ERROR:      'oea'
ERROR:      'unitig'
ERROR:      'consensusConfigure'
ERROR:      'cns'

**Comment by brianwalenz** [comment]
Those are mostly for debugging, and are hit-or-miss as to what is implemented.  What are you trying to do?

**Comment by ruiguo-bio** [comment]
I want to just generate read overlap using mhap or ovl, so the correction read is not important.

**Comment by brianwalenz** [comment]
Try stopAfter=overlapStore.  This will generate overlaps and load them into the store.  Also use saveOverlaps=true to save the raw output of the overlapper if you want it.

There is currently no way to stop after overlaps are computed but before they're loaded into the store - you can just kill canu when it starts building the store if you don't want it.

**Comment by ruiguo-bio** [comment]
That works, thank you!
