### ISSUE TITLE
canu failed with 'didn't find '.../unitigging/3-overlapErrorAdjustment/oea.files'

### ISSUE THREAD

**Issue by KamilSJaron** [marbl/canu#30]
Hi,
a harmless error occured:

canu failed with 'didn't find '.../unitigging/3-overlapErrorAdjustment/oea.files' to add to store, yet overlapper finished'. Full log was pasted to http://jpst.it/ESKP

I believe, that the problem was in this subroutine overlapErrorAdjustmentCheck, because, there are not "FAILED" jobs or failed attempts to open "oea.files" for writing in the log file. It seems, that @success job was just empty and therefore no file was created.

**Comment by brianwalenz** [comment]
I think this is obtusely saying that at least one of the oea jobs failed.  If you rerun canu with the same command line, it'll try running the failed jobs again.  It seems canu is correctly trying to run the jobs twice, but then failing to check the outputs after the last try - instead, it blindly goes to the next step, which is (rightly) complaining the output from the last step doesn't exist.

**Comment by brianwalenz** [comment]
The pipeline is fixed (in e9175d86c82e122539853d093ca1cec0fef9e5db), but the problem with the actual compute is still unknown.

**Comment by KamilSJaron** [comment]
Great, I will try to run it again.

**Comment by KamilSJaron** [comment]
Now, it worked. Awesome, thank you. 

However... The html report was not filled (in fact it looked exactly same as in the last run - just summary of trimmed reads). So I checked the err log and I found:

  -- Summary saved in '/scratch/local/kjaron/amphio/CanuAssembly/amphio-assembly_er025/amphio.html'.

So it seems, that Canu is trying to save the report to wrong file (I believe, that the report should have name "unitigging.html"). This is not a problem for me, I can compute statistics by my own, I just wanted to report suspicious behaviour.

**Comment by brianwalenz** [comment]
Thanks.  It was reporting the wrong file name.  The unitigging.html report, and a few other output related tasks, are being worked on right now.

Open a new issue if 3-overlapErrorAdjustment fails again.

**Comment by shimiao12345** [comment]
Hi,
a harmless error occured:
canu failed with 'didn't find '.../unitigging/3-overlapErrorAdjustment/oea.files' to add to store, yet overlapper finished'
     The same problem  was occured when I run the canu,and the log file is same as you. I want to know how to solve this problem.
     Waiting for your reply,thank you!

**Comment by KamilSJaron** [comment]
I have run Canu again, and it worked. It seems like paralelization problem, if your dataset is not big, you might consider to run it only one thread (it will be probably safer). However, I do not see too deep into it, developers of pipeline will know better.

**Comment by vatese** [comment]
Getting a similar issue:

Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'can't find '/tmp/canutest/ecoli-auto/unitigging/5-consensus/cnsjob.files' for loading tigs into store: No such file or directory'.

Can't seem to correct it in any way after running several tests. Will check the rest of the output. Many thanks and cheers
