### ISSUE TITLE
Is it normal to get zero-sized corrected reads file?

### ISSUE THREAD

**Issue by mapleforest** [marbl/canu#301]
Dear authors,

I run Canu on all the reads I have (first with corMinCoverage=4 corOutCoverage=100 and then with corMinCoverage=0 corOutCoverage=100).
In the stage of correctReads.sh, I got the first three corrected fasta file with zero size (see the pic).
And I delete the 2-correction directory and rerun the program for several times.
I still get this result. It appeared that the program touch the "dump.success" file anyway.

Is this normal?
I have successfully run Canu on a subset of my reads for multiple times.

![correctionreads](https://cloud.githubusercontent.com/assets/15427328/20462892/c04c55a8-af62-11e6-9173-cb62cc7b81e2.PNG)

best regards,
Shengfeng

**Comment by brianwalenz** [comment]
This could happen if there are many short reads supplied in the first files given to canu.  For example: `canu ... -pacbio-raw short-reads.fasta long-reads.fasta`.

**Comment by skoren** [comment]
Closing, I assume this is resolved due to inactivity? If you ended up with sufficient coverage in corrected reads for assembly, it could be due to what @brianwalenz said regarding short reads being supplied first.

Please open a new issue if you encounter other errors with this assembly.
