### ISSUE TITLE
Installing Canu_Windows 

### ISSUE THREAD

**Issue by rnguyen2018** [marbl/canu#305]
Hi there, 
I'm new to this, and I am trying to install canu on my computer. I'm getting an error at the "make" step stating the following:
Makefile:581: *** mixed implicit and normal rules.  Stop.
Anyone know what this means or how this can be fixed? 
Thanks for your time!

**Comment by skoren** [comment]
Sorry, we have never test Canu on Windows. I know it can be compiled on Cygwin. This might be due to the version of make installed, we've tested 3.81 if you have a version newer than this but older than 4.1 that could be an issue. If possible, try version 4.1+ or 3.81.
