### ISSUE TITLE
canu failed after error correction is done

### ISSUE THREAD

**Issue by xxzhou1** [marbl/canu#306]
```
-- Meryl attempt 1 begins.
----------------------------------------
-- Starting concurrent execution on Tue Nov 22 09:01:08 2016 with 14778.088 GB free disk space (1 processes; 2 concurrently)

    /import/analysis/assembly/tech_request/canola_pb_assem/65037_2/canola-auto/trimming/0-mercounts/meryl.sh 1 > /import/analysis/assembly/tech_request/canola_pb_assem/65037_2
/canola-auto/trimming/0-mercounts/meryl.000001.out 2>&1

-- Finished on Tue Nov 22 09:01:24 2016 (16 seconds) with 14778.099 GB free disk space
----------------------------------------
--
-- meryl failed.
--
-- Meryl attempt 2 begins.
----------------------------------------
-- Starting concurrent execution on Tue Nov 22 09:01:25 2016 with 14778.096 GB free disk space (1 processes; 2 concurrently)

    /import/analysis/assembly/tech_request/canola_pb_assem/65037_2/canola-auto/trimming/0-mercounts/meryl.sh 1 > /import/analysis/assembly/tech_request/canola_pb_assem/65037_2
/canola-auto/trimming/0-mercounts/meryl.000001.out 2>&1

-- Finished on Tue Nov 22 09:01:41 2016 (16 seconds) with 14778.098 GB free disk space
----------------------------------------
--
-- meryl failed.
--
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'failed to generate mer counts.  Made 2 attempts, jobs still failed'.
```

**Comment by brianwalenz** [comment]
What is in `canola-auto/trimming/0-mercounts/meryl.000001.out`?  What version of canu?

**Comment by xxzhou1** [comment]
Hi

Below is what I can see with more or cat command.
The file is 3.Gb.

Thanks a lot for your help.

Joe


Computing 20 segments using 20 threads and 184640MB memory (27389MB if in one batch).
  numMersActual      = 14100688386
  mersPerBatch       = 4294967296
  basesPerBatch      = 707192917
  numBuckets         = 33554432 (25 bits)
  bucketPointerWidth = 30
  merDataWidth       = 19
Computing segment 1 of 20.
Allocating 120MB for bucket pointer table (30 bits wide).
Computing segment 13 of 20.
Allocating 128MB for counting the size of each bucket.
Allocating 120MB for bucket pointer table (30 bits wide).
Computing segment 9 of 20.
Allocating 120MB for bucket pointer table (30 bits wide).
Computing segment 17 of 20.
Computing segment 5 of 20.
Computing segment 3 of 20.
Allocating 120MB for bucket pointer table (30 bits wide).
Computing segment 12 of 20.
Allocating 120MB for bucket pointer table (30 bits wide).
Computing segment 14 of 20.
Allocating 120MB for bucket pointer table (30 bits wide).
Computing segment 11 of 20.
Allocating 120MB for bucket pointer table (30 bits wide).
Computing segment 10 of 20.
Computing segment 7 of 20.
Computing segment 19 of 20.
Allocating 120MB for bucket pointer table (30 bits wide).
Computing segment 15 of 20.
Allocating 120MB for bucket pointer table (30 bits wide).
Computing segment 20 of 20.
Allocating 120MB for bucket pointer table (30 bits wide).
Computing segment 4 of 20.
Allocating 120MB for bucket pointer table (30 bits wide).
Computing segment 8 of 20.
Allocating 120MB for bucket pointer table (30 bits wide).
Allocating 120MB for bucket pointer table (30 bits wide).
Computing segment 6 of 20.
Allocating 120MB for bucket pointer table (30 bits wide).
Computing segment 2 of 20.
Allocating 120MB for bucket pointer table (30 bits wide).
Computing segment 18 of 20.
Allocating 120MB for bucket pointer table (30 bits wide).
Allocating 120MB for bucket pointer table (30 bits wide).
Allocating 120MB for bucket pointer table (30 bits wide).
Allocating 120MB for bucket pointer table (30 bits wide).
Computing segment 16 of 20.
Allocating 120MB for bucket pointer table (30 bits wide).
Allocating 128MB for counting the size of each bucket.
Allocating 128MB for counting the size of each bucket.
Allocating 128MB for counting the size of each bucket.
Allocating 128MB for counting the size of each bucket.
Allocating 128MB for counting the size of each bucket.
Allocating 128MB for counting the size of each bucket.
Allocating 128MB for counting the size of each bucket.
Allocating 128MB for counting the size of each bucket.
Allocating 128MB for counting the size of each bucket.
Allocating 128MB for counting the size of each bucket.
Allocating 128MB for counting the size of each bucket.
Allocating 128MB for counting the size of each bucket.
Allocating 128MB for counting the size of each bucket.
Allocating 128MB for counting the size of each bucket.
Allocating 128MB for counting the size of each bucket.
Allocating 128MB for counting the size of each bucket.
Allocating 128MB for counting the size of each bucket.
Allocating 128MB for counting the size of each bucket.
Allocating 128MB for counting the size of each bucket.

**Comment by brianwalenz** [comment]
The error will be at the tail end of the file.  I'm going to guess out of memory, as it's estimating it will use 185gb.

How are you launching canu?  Any special options?

What did it report for its memory and thread configuration?

Try limiting the memory to meryl with option merylMemory, eg, merylMemory=20g.

**Comment by brianwalenz** [comment]
Idle.
