### ISSUE TITLE
canu failed with 'can't configure for SGE'

### ISSUE THREAD

**Issue by Mr-Inamn** [marbl/canu#310]
Hi,
I tried running canu on my server today. Based on the documentation, at first, I tried running with the following code:
```
date
canu  \
    -p ecoli -d ecoli-auto \
    genomeSize=4.8m \
    -pacbio-raw ecoli_p6_25x.filtered.fastq
```
But wrong message appeared that:
```
> Mon Dec 12 11:01:00 CST 2016
> -- Detected Java(TM) Runtime Environment '1.8.0_91' (from 'java').
> -- Detected 48 CPUs and 2272 gigabytes of memory.
> -- Detected Sun Grid Engine in '/opt/gridengine/default'.
> --
> -- WARNING:  Couldn't determine the SGE parallel environment to run multi-threaded codes.
> -- WARNING:  No valid choices found!  Find an appropriate Parallel Environment name (qconf -spl) and set:
> -- WARNING:    gridEngineThreadsOption="-pe <name> THREADS"
> --
> --
> -- WARNING:  Couldn't determine the SGE resource to request memory.
> -- WARNING:  No valid choices found!  Find an appropriate complex name (qconf -sc) and set:
> -- WARNING:    gridEngineMemoryOption="-l <name>=MEMORY"
> --
> ================================================================================
> Don't panic, but a mostly harmless error occurred and canu failed.
> 
> canu failed with 'can't configure for SGE'.
```
Then based on some comment on previous Issues, I tried running canu with the following code:
```
date
canu \
-p ecoli -d ecoli_test \
genomeSize=4.8m \
gridEngineMemoryOption="-l h_vmem=MEMORY" \
gridEngineThreadsOption="-pe make THREADS" \
-pacbio-raw ./ecoli_p6_25x.filtered.fastq
date
```
It appeared:
```
> Mon Dec 12 11:16:56 CST 2016
> -- Detected Java(TM) Runtime Environment '1.8.0_91' (from 'java').
> -- Detected 48 CPUs and 2272 gigabytes of memory.
> -- Detected Sun Grid Engine in '/opt/gridengine/default'.
> -- User supplied Grid Engine environment '-pe make THREADS'.
> -- User supplied Grid Engine consumable '-l h_vmem=MEMORY'.
> --
> -- Found   1 host  with  23 cores and 2272 GB memory under Sun Grid Engine control.
> --
> -- Allowed to run under grid control, and use up to   1 compute thread  and   16 GB memory for stage 'bogart (unitigger)'.
> -- Allowed to run under grid control, and use up to   1 compute thread  and    6 GB memory for stage 'mhap (overlapper)'.
> -- Allowed to run under grid control, and use up to   1 compute thread  and    6 GB memory for stage 'mhap (overlapper)'.
> -- Allowed to run under grid control, and use up to   1 compute thread  and    6 GB memory for stage 'mhap (overlapper)'.
> -- Allowed to run under grid control, and use up to   1 compute thread  and    2 GB memory for stage 'read error detection (overlap error adjustment)'.
> -- Allowed to run under grid control, and use up to   1 compute thread  and    1 GB memory for stage 'overlap error adjustment'.
> -- Allowed to run under grid control, and use up to   1 compute thread  and   32 GB memory for stage 'utgcns (consensus'.
> -- Allowed to run under grid control, and use up to   1 compute thread  and    4 GB memory for stage 'overlap store parallel bucketizer'.
> -- Allowed to run under grid control, and use up to   1 compute thread  and    8 GB memory for stage 'overlap store parallel sorting'.
> -- Allowed to run under grid control, and use up to   1 compute thread  and    6 GB memory for stage 'overlapper'.
> -- Allowed to run under grid control, and use up to   1 compute thread  and    8 GB memory for stage 'overlapper'.
> -- Allowed to run under grid control, and use up to   1 compute thread  and    8 GB memory for stage 'overlapper'.
> -- Allowed to run under grid control, and use up to   1 compute thread  and    8 GB memory for stage 'meryl (k-mer counting)'.
> -- Allowed to run under grid control, and use up to   1 compute thread  and   16 GB memory for stage 'falcon_sense (read correction)'.
> -- Allowed to run under grid control, and use up to   1 compute thread  and    6 GB memory for stage 'minimap (overlapper)'.
> -- Allowed to run under grid control, and use up to   1 compute thread  and    6 GB memory for stage 'minimap (overlapper)'.
> -- Allowed to run under grid control, and use up to   1 compute thread  and    6 GB memory for stage 'minimap (overlapper)'.
> ----------------------------------------
> -- Starting command on Mon Dec 12 11:16:57 2016 with 6500.2 GB free disk space
> 
>     qsub \
>       -l h_vmem=8g \
>       -pe make 1   \
>       -cwd \
>       -N "canu_ecoli" \
>       -j y \
>       -o /public/home/lijing/canu_test/ecoli_test/canu-scripts/canu.01.out /public/home/lijing/canu_test/ecoli_test/canu-scripts/canu.01.sh
> Your job 2596 ("canu_ecoli") has been submitted
> 
> -- Finished on Mon Dec 12 11:16:57 2016 (lickety-split) with 6500.2 GB free disk space
```
It seemed that I have successfully run the canu with the test ecoli reads. But when I check the results, there is no results at all, the files are as follows:
```
> L canu_test ll
> total 223M
> -rwxr-xr-x 1 lijing users  191 Nov 18 14:23 canu.test.sh
> -rwxr-xr-x 1 lijing users 223M Nov 11 14:48 ecoli_p6_25x.filtered.fastq
> drwxr-xr-x 4 lijing users 4.0K Nov 18 14:23 ecoli_test
> L canu_test ll ecoli_test/*
> ecoli_test/canu-logs:
> total 8.0K
> -rw-r--r-- 1 lijing users 318 Nov 18 14:23 1479450224_node1_35809_canu
> -rw-r--r-- 1 lijing users 318 Dec 12 11:16 1481512617_node1_19739_canu
> 
> ecoli_test/canu-scripts:
> total 4.0K
> -rwxr-xr-x 1 lijing users 1.1K Dec 12 11:16 canu.01.sh
```
Anyone could give me some help? many thanks.

**Comment by skoren** [comment]
You correctly fixed the first message by specifying the options on your system to request cores and memory. I will note that h_vmem is usually not appropriate because it is consumable, if it is set as consumable (reserves the memory when a job is scheduled) on your system then it is OK to use. 

Canu runs on the grid by submitting itself and exiting on the submission host. It will keep running on your grid if you check jobs with qsub. Unless there are errors in the last canu.\*.out file or you see no jobs running with qstat then it is still running without issue.

**Comment by Mr-Inamn** [comment]
Thank you@skoren
I checked the qstat today. The information is as follows:

> job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID
> -----------------------------------------------------------------------------------------------------------------
>    1719 0.55500 canu_ecoli lijing       qw    11/14/2016 17:36:27                                    1
>    1720 0.55500 canu_ecoli lijing       qw    11/14/2016 18:42:14                                    1
>    1856 0.55500 canu_ecoli lijing       qw    11/18/2016 10:29:23                                    1
>    1857 0.55500 canu_ecoli lijing       qw    11/18/2016 14:23:44                                    1
>    2596 0.55500 canu_ecoli lijing       qw    12/12/2016 11:16:57                                    1

It seems that all the job did not work at all. Do you know how to fix it?

**Comment by Mr-Inamn** [comment]
I tried using useGrid=false. Then everything is ok. But if anyone could give me some advice about SGE, it also helps a lot.

**Comment by skoren** [comment]
There should only be one canu_ecoli job at a time. Did you run the canu command multiple times when you thought it was not running? That would definitely cause issues as the jobs would collide with each other and corrupt the run. 

The qw state is not an error, it just means the jobs are waiting to get scheduled. It looks like the jobs have been sitting waiting to get scheduled for weeks so I would check with your grid admin if there are other flags that must be specified (like queue or other resources) to make the jobs run. The submit command Canu is using should only ask for 8gb of ram and 1 CPU, not a lot of resources so that should not be waiting to get scheduled for days or weeks. I'd also suggest checking that ``-pe make``` will request processors on the same machine not across machines, Canu requires all CPUs it requests to be on a single machine with shared memory. Finally, unless you're running large genomes (vertebrate or plants) you can run on a single machine.

**Comment by skoren** [comment]
Closing, inactivity, please open a new issue if you encounter errors.
