### ISSUE TITLE
Canu takes over a week for one assembly

### ISSUE THREAD

**Issue by Mirazoqui** [marbl/canu#311]
Hi, I tried running Canu on a set of Nanopore R9 D1 reads, but it's been over a week since it started and it's still running. It seems it got stuck in the trimming process. I used the following commands:

canu -correct -p ONT_021216_Cov500 -d ONT_021216_Cov500 corOutCoverage=500 corMinCoverage=0 corMhapSensitivity=high genomeSize=3m -nanopore-raw  24hs_ONT.fastq

canu -trim -p ONT_021216_Cov500 -d ONT_021216_Cov500 genomeSize=3m -nanopore-corrected ONT_021216_Cov500/ONT_021216_Cov500.correctedReads.fasta.gz

I was wondering if it's a normal thing to happen or it has something to do with the parameters I chose. I'm using a server with 16 cores and 128 Gb RAM, so it shouldn't be a problem of computational resources. 
Thanks!

**Comment by brianwalenz** [comment]
What task is currently running?

**Comment by Mirazoqui** [comment]
The trimming part, since last sunday

**Comment by brianwalenz** [comment]
I'll assume the overlapInCore process is running.

What is the size of 0-mercounts/*.frequentMers.fasta?  These are the kmers to ignore when finding overlaps - all the non-informative high copy repetitive stuff.  I've seen a few assemblies where this file is empty.  I don't have an automatic fix worked out yet, but it is relatively easy to manually fix.

**Comment by Mirazoqui** [comment]
Yes, sorry, the process is the overlapInCore. The frequentMers.fasta file is 327Kb, with 11468 sequences in it.

**Comment by skoren** [comment]
Do you have many very long (>100kb) sequences in your dataset? If you do and didn't set the error rate (```errorRate=0.025```) as listed on the FAQ: http://canu.readthedocs.io/en/latest/faq.html#what-parameters-should-i-use-for-my-genome-sequencing-type this could cause the overlapping to slow down. I'd suggest trying with the error rate set (you don't have to run correction again, just give the asm.correctedReads.fasta.gz with the nanopore-corrected option).

If you are running latest from the repository (not 1.3) then you can also try the experimental overlapped which is much faster on long and higher error rate, to do so run with the options ```obtOverlapper=mhap obtReAlign=raw utgOverlapper=mhap utgReAlign=raw```.

**Comment by brianwalenz** [comment]
Idle.
