### ISSUE TITLE
job failed at overlap step

### ISSUE THREAD

**Issue by igsbma** [marbl/canu#313]
Hi there, I have run it without any problem for a long while, but got this error repeatedly. Please advice, thank you!

PS: previous steps finished without problems.

-- 1 overlap error adjustment jobs failed:
--   job path/unitigging/3-overlapErrorAdjustment/0001.oea FAILED.
--
-- overlap error adjustment attempt 2 begins with 0 finished, and 1 to compute.
----------------------------------------

**Comment by skoren** [comment]
What version of Canu? What is the output in 3-overlapErrorAdjustment/oea.\*.out?

**Comment by igsbma** [comment]
Thanks!
version:
Canu v0.0 (+0 commits) r0 unknown-hash-tag-no-repository-available.

I just looked for the oea.*.out, there is one file oea.000001.out

Recomputing overlaps.
--Allocate 8 MB for fseq and rseq.
--Allocate 32 MB for fadj and radj.
--Allocate 16 MB for pedWorkArea_t.
-- Allocate 0 MB for Edit_Array pointers.
--Allocate 16 MB for edit array work space 0 (positions 0-4092)
Recomputing overlaps -         1 -     11265 -     11855
Failed with 'Segmentation fault'

The input fastq file is only 185M, and I already used a large memory machine. I launched a few jobs at the same time, all others finished but this one. Is it anything to do with the input file quality? 

Thanks again!
Bing

**Comment by skoren** [comment]
How did you download Canu? If you're not using the 1.4 release I would recommend downloading those binaries/source and running again (you would have to restart from scratch).

The error is likely a bug and so more memory wouldn't help. If you can share your unitigging folder (the gkpStore and ovlStore folders or the raw inputs if not too big) we can try to reproduce locally. You can upload them to our ftp here ftp://ftp.cbcb.umd.edu/incoming/sergek/

**Comment by igsbma** [comment]
Thanks! the failed was run by version 1.3. I upgraded to 1.4 and it run through!
