### ISSUE TITLE
High IO wait at generateCorrectionLayouts when jobs started all at once

### ISSUE THREAD

**Issue by HenrivdGeest** [marbl/canu#314]
First of all, without an article acknowledgement, I would like to thank you all for this wonderful piece of software, it has produced a couple great assemblies.

I am running Canu 1.4 on a slurm schedular cluster with hundreds of nodes. (Cartsius, The Netherlands)
When the subtasks  of generateCorrectionLayouts is submitted (in my case an array job of 525 tasks) they experience a huge IO wait. They jobs are all (at least almost all) really at 0% cpu usage, and 99% iowait and in 'D' state. It seems that actually none of them is doing anything. This problem seems solved when the submitted jobs do not all start at the same moment. I made a for loop for submitting my jobs every 5 seconds, and that seems to help:
`for NR in {1..525}; do sleep 5; sbatch     -t 1-00:00:00  --mem-per-cpu=426m --cpus-per-task=24     -D `pwd` -J "cor_test"     -a $NR     -o /home/user/storage/test/correction/2-correction/correctReads.%A_%a.out     /home/user/storage/test/correction/2-correction/correctReads.sh 0;done`

With that sleep delay I can run hundreds of these jobs at the  same time, while each node still is doing some computation. ( at least I see falcon_sense running on a few CPU's, so I assume it received data from 'generateCorrectionLayouts ') 
The file system is a Lustre with 48 storage nodes with Infiniband, so that should not be a bottleneck. 

My "/home/user/storage/test/correction/test.gkpStore" directory has a 15GB blob file, which I assume is the source file for reading:
```
drwxr-sr-x 2 user qt14793 4.0K Dec 19 10:31 .
drwxr-sr-x 7 user qt14793 4.0K Dec 19 13:45 ..
-rw-r--r-- 1 user qt14793  15G Dec 19 10:31 blobs
-rw-r--r-- 1 user qt14793  43M Dec 19 10:31 errorLog
-rw-r--r-- 1 user qt14793   56 Dec 19 10:31 info
-rw-r--r-- 1 user qt14793  279 Dec 19 10:31 info.txt
-rw-r--r-- 1 user qt14793  336 Dec 19 10:31 libraries
-rw-r--r-- 1 user qt14793  173 Dec 19 10:31 libraries.txt
-rw-r--r-- 1 user qt14793  297 Dec 19 10:31 load.dat
-rw-r--r-- 1 user qt14793 475M Dec 19 10:31 readNames.txt
-rw-r--r-- 1 user qt14793 1.5K Dec 19 10:31 readlengthhistogram.txt
-rw-r--r-- 1 user qt14793  700 Dec 19 10:31 readlengths.gp
-rw-r--r-- 1 user qt14793 6.5K Dec 19 10:31 readlengths.lg.png
-rw-r--r-- 1 user qt14793 1.9K Dec 19 10:31 readlengths.sm.png
-rw-r--r-- 1 user qt14793  28M Dec 19 10:31 readlengths.txt
-rw-r--r-- 1 user qt14793  80M Dec 19 10:31 reads
-rw-r--r-- 1 user qt14793 143M Dec 19 10:31 reads.txt
```

Does this all ring a bell or not at all? For this stage I figured out manually, but for any new assembly I have to submit this step by hand as well.

**Comment by skoren** [comment]
The first step loads most of the blobs into memory (it used to use a memory mapped file which caused issues on Slurm due to vm usage) so that is likely the source of your IO bottleneck. It does seem to have a higher IO load on our GPFS file system than NFS (though the GPFS has a slower interconnect). In the future Canu will probably stage the gkpStore to a local drive, if available, for this step. You could try the same strategy to see if it alleviates the IO. If it does, I can help you modify the code to always stage the store to local disk for this step.

**Comment by HenrivdGeest** [comment]
Probably it will, because running less concurrent jobs improves this a lot.  I don't know how to test that copy-to-local-disk first.
I also found a SLURM  parameter to limit the maximum of concurrent running jobs. (however this means that they still start exactly at the same time)
When submitting an array job, with "-a 1-467"  we can limit this to max 50 concurrent jobs with "-a 1-467%50"

I have no idea where to put that parameter. And, for the mhap jobs this is not required, since they are cpu limited.

**Comment by skoren** [comment]
You can specify flags to pass for the correction step using ```gridOptionscor```. For example, on our SLURM system you have to reserve scratch space so you would pass:
``"`gridOptionscor=--gres=lscratch:50```
which reserves 50G of space in /lscratch/$SLURM_JOB_ID. Adjust this to whatever your system uses.

Then, you would have to edit /src/pipelines/canu/CorrectReads.pm:
```
 363     my $erate    = getCorErrorRate($wrk, $asm);
 364     my $minidt   = 1 - $erate;
 365 
 366     print F "\n";
```

to be:
```
my $erate    = getCorErrorRate($wrk, $asm);
my $minidt   = 1 - $erate;

print F "\n";
print F "gkpStore=\"$wrk/$asm.gkpStore\"\n";
print F "\n";
print F "ls -l /lscratch\n";
print F "df -h /lscratch\n";
print F "df -h /lscratch/\$SLURM_JOBID\n";
print F "\n";
print F "if [ -d /lscratch/\$SLURM_JOBID ] ; then\n";
print F "    mkdir /lscratch/\$SLURM_JOBID/$asm.gkpStore\n";
print F "    cp -p $wrk/$asm.gkpStore/info      /lscratch/\$SLURM_JOBID/$asm.gkpStore/info\n";
print F "    cp -p $wrk/$asm.gkpStore/libraries /lscratch/\$SLURM_JOBID/$asm.gkpStore/libraries\n";
print F "    cp -p $wrk/$asm.gkpStore/reads     /lscratch/\$SLURM_JOBID/$asm.gkpStore/reads\n";
print F "    cp -p $wrk/$asm.gkpStore/blobs     /lscratch/\$SLURM_JOBID/$asm.gkpStore/blobs\n";
print F "    gkpStore=\"/lscratch/\$SLURM_JOBID/$asm.gkpStore\"\n";
print F "fi\n";
print F "\n";
```

You'd need to adjust SLURM_JOBID and lscratch to whatever is appropriate on your system.

**Comment by brianwalenz** [comment]
I properly implemented file staging for generating corrected reads.  There's a bit of documentation at http://canu.readthedocs.io/en/latest/parameter-reference.html#file-staging.

Staging is enabled if stageDirectory is set.  It is assumed this is a directory local to the node, and unique to the task.

It has only been lightly tested, on SGE, and my configuration doesn't need to use gridEngineStageOption, so that hasn't been tested much at all.
