### ISSUE TITLE
Segmentation fault in consensus building

### ISSUE THREAD

**Issue by dominik-handler** [marbl/canu#318]
Hi,

I am running Canu on mixed Nanopore and PacBio reads. It fails for me in the consensus building in the unitigging stage. Interestingly only 4/27 grid-jobs fail. 
In all of these 4 I get the following error:

`Failed with 'Segmentation fault'

Backtrace (demangled):

[0] /${PATH}/canu/Linux-amd64/bin/utgcns::AS_UTL_catchCrash(int, siginfo*, void*) + 0x26  [0x430326]
[1] /lib/x86_64-linux-gnu/libpthread.so.0::(null) + 0xf0a0  [0x2b5f7c7230a0]
[2] /${PATH}/canu/Linux-amd64/bin/utgcns() [0x46885d]
[3] /${PATH}/canu/Linux-amd64/bin/utgcns() [0x440f5b]
[4] /${PATH}/canu/Linux-amd64/bin/utgcns() [0x4447dc]
[5] /${PATH}/canu/Linux-amd64/bin/utgcns() [0x404e97]
[6] /lib/x86_64-linux-gnu/libc.so.6::(null) + 0xfd  [0x2b5f7c94eead]
[7] /${PATH}/canu/Linux-amd64/bin/utgcns() [0x405a19]

GDB:

/gridengine/ge2011.11/bioinfo/spool/compute-6-27/job_scripts/3973658: line 77: 16836 Segmentation fault      (core dumped) $bin/utgcns -G /${PATH}/canu-assembly/unitigging/combinedR9.4.${tag}Store/partitionedReads.gkpStore -T /${PATH}/canu-assembly/unitigging/combinedR9.4.${tag}Store 1 $jobid -O /${PATH}/canu-assembly/unitigging/5-consensus/${tag}cns/$jobid.cns.WORKING -maxcoverage 40 -e 0.15 -pbdagcon -threads 8
`

Is this a known problem? As far as I can tell it is different to the so far reported segmentation fault issues.
I am using V1.4 @ commit d7bfb42

Thank you,
Dominik

**Comment by skoren** [comment]
Recently known and we are testing a fix but it is a large change so it's not yet committed. If you can wait for a few days, you can test it once it is committed.

In the meantime, you can try editing consensus.sh to change ```-pbdagcon``` to ```-quick``` and re-run Canu, it should only recompute the failed subset of jobs.

**Comment by dominik-handler** [comment]
Thank you for the quick response.
I am currently testing the quick fix you mentioned. If this fails it is no problem for me to wait some days.

**Comment by dominik-handler** [comment]
Hi,

do you already have a fix for this issue? I also tried your suggested workaround but that also fails.

Dominik

**Comment by skoren** [comment]
I committed a fix, give it a try, it should switch to a different aligner in consensus on a second retry if the first attempt fails.
