### ISSUE TITLE
plasmids and other very small chromosomes aren't output

### ISSUE THREAD

**Issue by brianwalenz** [marbl/canu#326]
Small sequences (e.g., plasmids) are flagged as unassembled crud and not output, and in some cases, the reads are excluded from forming contigs.

Two issues here:

1)  As in issue #312, mutually contained reads are excluded from seeding a unitig.  In that issue, reads were selected from a much larger set, which resulted in tiny, non-ciruclar, 'chromosomes' spanned by multiple reads.

2)  Plasmids are usually spanned by a single read, and are therefore caught by the unassembled crud filter.

**Comment by brianwalenz** [comment]
Moving from active issue to feature request. https://github.com/marbl/canu/projects/1

**Comment by aphillippy** [comment]
3. small plasmids will also be lost if only some fraction of the longest reads are corrected and assembled. can be solved either by correcting all reads or implementing our k-mer coverage check idea
