### ISSUE TITLE
ERROR:  mhap overlapper requires java version at least 1.8.0; you have unknown (from 'java').

### ISSUE THREAD

**Issue by mictadlo** [marbl/canu#329]
Hi
I am getting the following errors while running canu:

```
ERROR:  mhap overlapper requires java version at least 1.8.0; you have unknown (from 'java').
ERROR:  'java -showversion' reports:
ERROR:  Failed to run gnuplot from 'gnuplot'.ERROR:  Set option gnuplot=<path-to-gnuplot> or gnuplotTested=true to skip this test and not generate plots.
```
```
java -showversion
openjdk version "1.8.0_92"
OpenJDK Runtime Environment (Zulu 8.15.0.1-linux64) (build 1.8.0_92-b15)
OpenJDK 64-Bit Server VM (Zulu 8.15.0.1-linux64) (build 25.92-b15, mixed mode)
```

```
> gnuplot

	G N U P L O T
	Version 5.0 patchlevel 4    last modified 2016-07-21 
```
What did I miss?

Thank you in advance.

Mic

**Comment by brianwalenz** [comment]
Canu can't find either java or gnuplot in the PATH it was supplied with.  You can set java=<path-to-java> and gnuplot=<path-to-gnuplot> on the canu command line.

Once you get it working, put those two options, one per line, in ~/.canu to have them used automagically.

**Comment by mictadlo** [comment]
Thank you. Would you like to manage Canu on BioConda?

**Comment by brianwalenz** [comment]
Nope, I've got enough stuff to keep me confused, and the issues I've seen there are outside my expertise.
