### ISSUE TITLE
job killed at 4-unitigger

### ISSUE THREAD

**Issue by geycu** [marbl/canu#330]
Hello,

My job was killed at Canu -assemble step bogart (unitigger.8298_1.out):

/var/spool/slurmd/job08298/slurm_script: line 45: 16229 Killed                  $bin/bogart -G /mnt/lustre/data/Canu_runs/Wheat/20million/asm_output1/unitigging/asm_wheat_20m.gkpStore -O /mnt/lustre/data/Canu_runs/Wheat/20million/asm_output1/unitigging/asm_wheat_20m.ovlStore -o /mnt/lustre/data/Canu_runs/Wheat/20million/asm_output1/unitigging/4-unitigger/asm_wheat_20m -gs 15000000000 -eg 0.075 -eM 0.075 -el 500 -dg 6 -db 6 -dr 3 -ca 2100 -cp 200 -threads 64 -M 957 -unassembled 2 1000 0.75 0.75 2 > /mnt/lustre/data/Canu_runs/Wheat/20million/asm_output1/unitigging/4-unitigger/unitigger.err 2>&1

Does it mean still not enough memory?

Thanks,
Xi

**Comment by skoren** [comment]
It looks like it is trying to use 1tb of ram, how much was requested when it submitted. You can adjust the script to use less memory (-M 500 would use 500g) and re-submit the 4-unitigger command.

**Comment by brianwalenz** [comment]
Idle.
