### ISSUE TITLE
perl modules (File::Path and Df)

### ISSUE THREAD

**Issue by dsommer** [marbl/canu#333]
File::Path & Filesys::Df perl modules were removed in canu-1.4.
https://github.com/marbl/canu/commit/129a859462b637f206492075489d0eb9f1fb7284

Release notes still says all perl modules needed are included.
Maybe add a note that you need to have File::Path version 2.08 or above otherwise canu-1.4 will not run on older versions of perl.

Thanks

**Comment by brianwalenz** [comment]
I updated the release notes and made version 2.08 the minimum.  It should now report:
```
File::Path version 2.08 required--this is only version 2.03 at /software/canu/FreeBSD-amd64/bin/canu line 48.
BEGIN failed--compilation aborted at /software/canu/FreeBSD-amd64/bin/canu line 48.
```
