### ISSUE TITLE
error to generate the .ovs file

### ISSUE THREAD

**Issue by yanz711** [marbl/canu#338]
I meet the problem with:

1 -bash: fork: retry: Resource temporarily unavailable

2 then i run canu again, but some file is zero:
-rw-r--r-- 1 zyan unildee 44573471152 Jan 20 05:02 0069
-rw-r--r-- 1 zyan unildee      292656 Jan 20 05:02 0069.index
-rw-r--r-- 1 zyan unildee          64 Jan 20 05:02 0069.info
-rw-r--r-- 1 zyan unildee           0 Jan 20 10:27 0070.ovs
-rw-r--r-- 1 zyan unildee           0 Jan 20 10:27 0071.ovs
-rw-r--r-- 1 zyan unildee           0 Jan 20 10:27 0072.ovs

3 then canu stop at:
Last 50 lines of the relevant log file (/scratch/beegfs/monthly/zyan/annotation/Pacbio/bigB/sinB/correction/2-correction/sinB.globalScores.err):

ERROR: directory '/scratch/beegfs/monthly/zyan/annotation/Pacbio/bigB/sinB/correction/sinB.ovlStore' is not an ovelrapStore; failed to open info file '/scratch/beegfs/monthly/zyan/annotation/Pacbio/bigB/sinB/correction/sinB.ovlStore/info': No such file or directory

**Comment by yanz711** [comment]
If you can tell me where to delete and restart, it will be great.

**Comment by brianwalenz** [comment]
You can try just restarting canu and seeing if it will pick up.

You seem to have an old version of canu - version 1.4 has been out for about six weeks.  This particular problem has been fixed, but you can't upgrade canu in the middle of an assembly, it's messy and error prone.  As painful as it sounds, the easiest and safest (and probably quickest) way to fix this is to upgrade to the github latest and restart from scratch.

This looks to be a gigantic assembly.  Can you share details?
