### ISSUE TITLE
Restart crashed job

### ISSUE THREAD

**Issue by hodgett** [marbl/canu#339]
Is it possible to restart a crashed job?
Canu has 'stopped', the job is no longer in the PBS queue. When I have a look in banaf-auto/correction/1-overlapper I see 000400.mhap.WORKING. There were 506 jobs from 202 blocks. All jobs appear to have completed except this one. Can I force this job to finish and the canu pipleline to continue from where it left off?

**Comment by brianwalenz** [comment]
You can just restart the same canu command and it will pick up where it left off.  But I suspect it will just fail again.

Any error will be in the `correction/1-overlapper/mhap.*400.out` error log.  Please post that.

**Comment by hodgett** [comment]
I suspect there is another bug? The .out files are named after the variable name, not the attribute;

-rw-rw----   1 hodgett default           179 Jan 20 11:26 mhap.$PBS_ARRAY_INDEX.out
-rw-rw----   1 hodgett default          3077 Jan 17 05:40 precompute.$PBS_ARRAY_INDEX.out

And I can't restart the job after applying the new code, it is stuck in the loop I have previously reported when detecting resources. I will have to wait for another process to complete so I can regress the code base

**Comment by brianwalenz** [comment]
I changed how PBS Pro array jobs are named.  They'll now use the default name, of something like <script-name>.o<jobid>.<taskid>, and should appear in the same directory as the script.

Close once you get a chance to test, and if it works.

**Comment by brianwalenz** [comment]
Fixed?  Fixed!
