### ISSUE TITLE
Recommended approach to extracting PacBio reads rom bas.h5 files?

### ISSUE THREAD

**Issue by JohnUrban** [marbl/canu#34]
Hi,

I was wondering if you have a recommended way to extract fastq/fasta information from PacBio's bas/bax files, and if you recommend filtering of any sort (e.g. based on quality) or just using all subreads. 

The way I have extracted fastq files is using bash5tools from pbh5tools (to get all subreads, no length or quality cutoffs):
$ bash5tools.py –readtype subread file.bas.h5

When I originally obtained the PacBio bas/bax dataset, they also provided "Filtered subreads" already extracted. These were filtered to be >= 500 bp and by some quality threshold. I unfortunately do not know exactly what was done to filter. Nonetheless, it is a subset of all reads.

I have tried Canu with both sets of reads described above (all and filtered) with various Canu parameters and with Canu specifying minReadLength = 500 or 1000. I get mixed results with a trend where using all reads gives higher max contig lengths and where using the filtered set gives slightly higher N50 values (using expected genome size to compare all). Ultimately though, they do not drastically differ. So, I am inclined to go with "all subreads" just because I know how that set of reads was obtained.

All in all, I am interested in what your standard practice is for extracting reads from the bas/bax files? -- i.e. what is your standard set of input reads to Canu? all? filtered? how?

Many many thanks,

John

**Comment by skoren** [comment]
We usually either take all the data in the fastq/fasta file in the Analysis_Results folder or run a filtering with a quality cutoff of 0.75. Both should work for Canu. The short reads don't need to be pre-filtered, they will be discarded on load by Canu.

**Comment by JohnUrban** [comment]
Unfortunately, I did not get an Analysis_Results folder with my data -- just the bas/bax files. Does the fastq/fasta in that folder have all the fastq/fasta data from all the bas/bax files from a run?

Based on your second suggestion, maybe the following can work:
bash5tools.py --readType subreads --outType fastq --minReadScore 0.75 --outFilePrefix $prefix file.bax.h5

I am slightly naive with PacBio data, much more familiar with nanopore data (.fast5).

**Comment by skoren** [comment]
Yes, your bash5tools.py command should work.

The fasta/fastq file has all the subread data from the bax.h5 files. The bas.h5 is just an index of the three bax.h5 files (at least in recent runs, old runs only had a bas.h5 output) and there are three fastq files corresponding to each of the bax.h5 files.

**Comment by JohnUrban** [comment]
Thanks. 
Do you have any data/insight on which of your two options performs better? 
(Feel free to close this issue.)

**Comment by skoren** [comment]
I think they should be comparable but I haven't done very extensive testing. I'll say most of our recent large assemblies are done just grabbing all the fastq files because I don't want to run filtering.

**Comment by claczny** [comment]
Hi,

@JohnUrban I found `dextractor` from https://dazzlerblog.wordpress.com/2014/03/22/the-dextractor-module-save-disk-space-for-your-pacbio-projects/ to be quite a bit faster. You provide it with all three *.bax.h5 files at once and it directly creates a merged FASTA file without intermediate FASTA files.

**Comment by JohnUrban** [comment]
@claczny -- Thanks for letting me know. I have read a lot into dextractor recently when trying to get Falcon working, and wondered if/assumed it would be faster than bash5tools. I will have to switch over to using it. Thank again.

**Comment by claczny** [comment]
@JohnUrban Should you mileage vary, kindly let us know :)

**Comment by dbrowneup** [comment]
I have some legacy bax and bas files that I am trying to work with. Seems like the best thing to do is use bax2bam (https://github.com/PacificBiosciences/blasr/tree/master/utils/bax2bam). Have you guys used this tool? If so, any thoughts on how it compares to the methods discussed in this thread?
