### ISSUE TITLE
Overall progress.

### ISSUE THREAD

**Issue by migrau** [marbl/canu#342]
I was wondering how can I know the overall progress on a CANU run. I am using the grid with many nodes and inside the work_folder/canu-logs there are > 1000 files. According to the run-times on your paper, it should take ~ 1.5-2 months to finish for our pacbio reads but I would like to know more info in each step.

Thank you!

Miquel

**Comment by brianwalenz** [comment]
canu-logs and canu-scripts aren't appropriately named.  canu-logs contains a report of every program run, while canu-scripts (the *.out files) contains what you're looking for.

There isn't any kind of 'progress bar' output, but I like the idea.

**Comment by migrau** [comment]
Thanks, Brian. I was looking for that.

**Comment by brianwalenz** [comment]
Moving from active issue to feature request. https://github.com/marbl/canu/projects/1
