### ISSUE TITLE
errorRate defaults clarification (1.4)

### ISSUE THREAD

**Issue by kfriesen2** [marbl/canu#347]
I didn't  specify errorRate in my canu 1.4 command. I noticed in the initial stream that it set errorRate to 0.015 for pacbio-raw:

> -- Final error rates before starting pipeline:
> . . .
> --   errorRate           -- 0.015

I thought it used to be 0.025 (https://github.com/marbl/canu/issues/183). I also saw this injunction in the documentation:

> The errorRate is not used correctly (we're working on it).  Don't set it

Please advise as to current recommended value, and if it should be set in the command or not. Thanks.

**Comment by skoren** [comment]
The default was lowered from 2.5% to 1.5% because we say it provided no benefit to compute overlaps to a higher error rate with recent pacbio datasets. Even for heterozygous genome assemblies we've done, the lower error rate was sufficient. So you should be fine leaving it at the default of 0.015.

**Comment by brianwalenz** [comment]
Worth adding to this:  the errorRate parameter was recently deprecated in favor of rawErrorRate and correctedErrorRate.  See:

http://canu.readthedocs.io/en/latest/tutorial.html#error-rates
http://canu.readthedocs.io/en/latest/parameter-reference.html#global-options

**Comment by kfriesen2** [comment]
Follow-up questions. Are the "new" error rates applicable to all post 1.4 versions? Do 1.4 and later versions provide default error values if none are specified in the command? If so, is there adjustment for high or low coverage?
