### ISSUE TITLE
Canu hangs at ovStoreStats?

### ISSUE THREAD

**Issue by cypridina** [marbl/canu#352]
Hi there,

What exactly is happening during `ovStoreStats`? I am running canu and it appears that there are no processes being run during this stage as there are no processes running.

*view from* `htop`
![screen shot 2017-01-26 at 10 20 10 am](https://cloud.githubusercontent.com/assets/3123273/22345120/b3592f94-e3b3-11e6-9f0b-4c430dbad65b.jpg)

This command started last night around 7:00PM, Wed Jan 25th. File paths redacted for brevity:

> -- Starting command on Wed Jan 25 18:46:55 2017 with 6211.548 GB free disk space
> 
>    /usr/local/bin/canu/Linux-amd64/bin/ovStoreStats \
>     -G DSMN06/unitigging/DSMN06.gkpStore \
>     -O DSMN06/unitigging/DSMN06.ovlStore \
>     -o DSMN06/unitigging/DSMN06.ovlStore \
>     > DSMN06/unitigging/DSMN06.ovlStore.summary.err 2>&1

This process ended today at 10:30AM, Thu Jan 26th -- 15 hours after this command was executed. However, the output to `$STDOUT` only lists that this command took 54 seconds, and that the command actually finished last night!

> -- Finished on Wed Jan 25 18:47:49 2017 (54 seconds) with 6211.541 GB free disk space

The next lines of output are the contents of the `.ovlStore.summary` file, listing the number of reads with their feature size, analysis, et cetera.

Even more bizarre, the next command that executed today (Thu Jan 26th around 10:30AM) is listed started running also lists last night (Wed Jan 25th). This is not correct though, as I was monitoring processes and core usage in the 15 hour period between last night and this morning and nothing was running, like the screenshot above.

> -- Starting concurrent execution on Wed Jan 25 18:47:51 2017 with 6211.541 GB free disk space (64 processes; 16 concurrently)
>     DSMN06/unitigging/3-overlapErrorAdjustment/red.sh 1 > DSMN06/unitigging/3-overlapErrorAdjustment/red.000001.out 2>&1

...et cetera, all the way up to `red.sh 43`.

To make this even more strange, I just checked the processes and `red.sh 59` through `red.sh 44` are running, even though they have not yet been printed to `$STDOUT`.

![screen shot 2017-01-26 at 11 00 01 am copy](https://cloud.githubusercontent.com/assets/3123273/22345921/ef8c417e-e3b6-11e6-8b2a-162752ee1fa2.jpg)

Any idea of what is going on here? I have never seen anything like this. Thanks for all your work on the assembler!

**Comment by brianwalenz** [comment]
ovStoreStats is reading all files in the ovStore directory to generate that summary file.  How do you know this finished at 10:30 today?  Do time stamps on the files make sense?

It's worth asking: are there two copies of canu running?  I.e., are you sure you're looking at what you think you're looking at?

Are jobs getting suspended?  That could explain no load, lack of things running, and abnormally large run times.

**Comment by cypridina** [comment]
> How do you know this finished at 10:30 today? 

I was actually monitoring `htop` from 10AM-11AM after noticing that no processes were being run for ~15 hours. In the middle of writing the above post, the `red.sh` processes started.

> It's worth asking: are there two copies of canu running? I.e., are you sure you're looking at what you think you're looking at?

Nope, I'm the only `canu` user on this machine, and no one else was running any jobs between last night and this morning.

I don't know how they could have been suspended, as no one else is using the machine currently. It's a mystery!

I'm a bit suspicious that maybe `htop` wasn't correctly displaying resources or something. When I noticed that the `red.sh` processes finally started running around 10:30AM, it was concurrently running processes `red.sh 44` through `red.sh 64`. This makes me think that somehow the first 44 jobs just didn't show up for the first 15 hours, then 44-64 finished  more quickly? Not sure but that's my hypothesis.

All the `red.sh` jobs stopped running at 11:17AM, so `canu` seems to be progressing normally now and I can see the processes in `htop`.

> -- Finished on Thu Jan 26 11:17:58 2017 (59407 seconds) with 6211.492 GB free disk space
> ----------------------------------------
> -- Found 64 read error detection output files.
> 
> Configure OEA for 2gb memory with batches of at most 25000 reads and (unlimited) bases.
> Configured 13 jobs.

Cheers-

**Comment by brianwalenz** [comment]
Did this run finish?  Canu has a lot of built in checks and generally fails when Bad Things happen (like missing jobs).
