### ISSUE TITLE
stopAfter=overlapStoreConfigure will not stop at that stage

### ISSUE THREAD

**Issue by ruiguo-bio** [marbl/canu#354]
I try that parameter, but it will continue to build overlapStore and then correct the reads, even continue after the overlapStore stage.

**Comment by brianwalenz** [comment]
Thanks for reporting.  There was a bunch of broken in there.  It should all be fixed.  Check the new documentation for the points it will stop at.

http://canu.readthedocs.io/en/latest/parameter-reference.html#process-control
