### ISSUE TITLE
Question: Is Canu capable of reading in multiple input files of the same sequencing type

### ISSUE THREAD

**Issue by mjjlou** [marbl/canu#356]
Dear Brian and Sergey,

I'm preparing to run the new version (1.4) of Canu and have more data to play with. However is the input restricted to one PacBio input FASTA/FASTQ file (i.e., I should merge all available input FASTA files)?

Best,
Melanie

**Comment by brianwalenz** [comment]
It will read all files on the command line, e.g., `-pacbio-raw *fastq`
