### ISSUE TITLE
ERROR:  Paramter 'masterThreads' is not known.

### ISSUE THREAD

**Issue by brkldj** [marbl/canu#357]
Hi,

I'd like to run canu on a single machine, and limit it to run on less than the total number of CPUs. If I try to limit it with the parameter masterThreads (which is specified in the documentation; I assume it will limit the number of threads for all steps), I get the following error message:

`ERROR:  Paramter 'masterThreads' is not known.`

I downloaded the latest version from github an hour ago. Is there a solution except specifying ****Threads for every single step?

**Comment by brianwalenz** [comment]
`maxThreads` and `maxMemory` will apply to every step.

Can you provide a link to the docs that mention this?  I can't find it in the latest version.

**Comment by brkldj** [comment]
Thank you!
I found it [here](https://media.readthedocs.org/pdf/canu/latest/canu.pdf), page 28.
