### ISSUE TITLE
Recommendation: AWS instance with and without starcluster

### ISSUE THREAD

**Issue by mjjlou** [marbl/canu#359]
Dear Brian and Sergey,

What is your recommendation for an appropriately sized amazon EC instance to run Canu to build a human de novo assembly at least 30x coverage (currently generating data to increase coverage)? I would assume one could select multiple smaller sized instances if starcluster were used to run canu in a distributed/batch-cluster set-up.

Thanks,
Melanie

**Comment by brianwalenz** [comment]
I have no experience with Amazon EC and/or starcluster, so can't really help there.

Most of canu will be happy with compute nodes with tens of CPUs and ~32gb ram.  Contig construction with bogart will benefit from larger memory, 128gb should be plenty.
