### ISSUE TITLE
CorrectReads.pm error

### ISSUE THREAD

**Issue by suryasaha** [marbl/canu#36]
Hi!

I am getting an error from CANU for a 1.9gb fastq pacbio bacterial dataset. It is running on a Ubuntu system
`Linux thompson.sgn.cornell.edu 3.19.0-43-generic #49~14.04.1-Ubuntu SMP Thu Dec 31 15:44:49 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

CANU command:
`~/tools/canu/Linux-amd64/bin/canu -p PS_14 -d PS_14-def genomeSize=6.5m -useGrid=0 -maxThreads=30 -maxMemory=500  -pacbio-raw Pseudomonas_14_BP_P6_010516_MB_170pM/all.fastq`

Error:
`Modification of non-creatable array value attempted, subscript -453 at /data/home/surya/tools/canu/Linux-amd64/bin/lib/canu/CorrectReads.pm line 980, <L> line 4.`

I have attached the log files to help track it down. Please let me know if you need anything else from me. Thanks much!

-Surya

[canu-logs.zip](https://github.com/marbl/canu/files/109953/canu-logs.zip)

**Comment by brianwalenz** [comment]
A 'feature' of perl must have been masking that particular error in our tests.

Commenting out the three @*DiffLengthHist arrays (one block of three at line 903, another block at line 979) will resolve the issue.  These must have been left over from development; they're never used.

In commit 6df89c83b8024b7a26879d882f51676b3fe5ff65.
