### ISSUE TITLE
Overlap store from correction step not working

### ISSUE THREAD

**Issue by EGroWi** [marbl/canu#360]
Hello,

we are currently testing running the current version of canu on our local cluster. Now, the run stopped at the end of the correction step. This is the relevant end of the canu.out:

```
-- BEGIN CORRECTION
--
-- Found 113 mhap overlap output files.
--
-- Overlap store '/home/ICE/grosse-wilde/Norb/correction/CanuTest.ovlStore' successfully constructed.
--
-- Purged 885.487 GB in 1354 overlap output files and 117 directories.
-- Overlap store '/home/ICE/grosse-wilde/Norb/correction/CanuTest.ovlStore' statistics not available (skipped in correction and trimming stages).
----------------------------------------
-- Starting command on Fri Feb  3 08:56:39 2017 with 11234.097 GB free disk space

    /opt/software/canu/bin/filterCorrectionOverlaps \
      -G /home/ICE/grosse-wilde/Norb/correction/CanuTest.gkpStore \
      -O /home/ICE/grosse-wilde/Norb/correction/CanuTest.ovlStore \
      -S /home/ICE/grosse-wilde/Norb/correction/2-correction/CanuTest.globalScores.WORKING \
      -c 40 \
      -l 0 \
    > /home/ICE/grosse-wilde/Norb/correction/2-correction/CanuTest.globalScores.err 2>&1

-- Finished on Fri Feb  3 08:56:39 2017 (lickety-split) with 11234.097 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

Disk space available:  11234.097 GB

Last 50 lines of the relevant log file (/home/ICE/grosse-wilde/Norb/correction/2-correction/CanuTest.globalScores.err):

ERROR: directory '/home/ICE/grosse-wilde/Norb/correction/CanuTest.ovlStore' is not an overlapStore; didn't find file '/home/ICE/grosse-wilde/Norb/correction/CanuTest.ovlStore/info': No such file or directory
ERROR:  failed to intiialize ovStore '/home/ICE/grosse-wilde/Norb/correction/CanuTest.ovlStore'.

canu failed with 'failed to globally filter overlaps for correction'.
```

I am not sure what exactly caused the problem, can you help us?

**Comment by brianwalenz** [comment]
I'm not sure either.  :-(

What is in the CanuTest.ovlStore directory?  If there is a `scripts/` or `logs/` directory, look in there for any errors in `out` or `err` files.

Also look in earlier canu.*.out files for errors (in canu-scripts/).

Unfortunately, the log file I think will have the error (CanuTest.ovlStore.err) was removed because the command claimed to complete successfully.  Worse, the input needed to recreate the overlap store was also removed.

To rerun set 'saveOverlaps=true' to save these inputs, remove (or just rename) the CanuTest.ovlStore and correction/1-overlapper directories.

**Comment by EGroWi** [comment]
Hello Brian,

first of all thanks for the reply!

> What is in the CanuTest.ovlStore directory? If there is a scripts/ or logs/ directory, look in there for any errors in out or err files.

The directory "CanuTest.ovlStore" doesn't exist, in "correction" or elsewhere. Weirdly enough. Hunting/grepping for "err" or "exit" in any out files I found nothing; looking at several out files all tasks look to have finished normally. This includes the ten out-files with the most recent time stamp, five each from precompute and mhap tasks. I haven't looked at all such files, there are simply too many. There are no *.err files beyond the CanuTest.globalScores.err listed above.

> Also look in earlier canu.*.out files for errors (in canu-scripts/).


Earlier canu.*.out didn't reach this stage - our SLURM pipeline needed updating, and those tasks crashed a lot earlier since it wasn't done yet.

I will re-run the analysis as soon as possible, then post results. In any case thanks for the explanations and suggestions!

**Comment by EGroWi** [comment]
Just a quick update - monitoring the progress, it looks like canu for some reason does not generate the overlap store; this is also true when called with the 'saveOverlaps=true' option. We are still trying to find out more - our HPC admin has some ideas he wants to test. I'll post more if we figure anything out.

**Comment by brianwalenz** [comment]
If you restart the same canu command, but add useGrid=remote, canu will try to resume the assembly, but not submit jobs to the grid (it will prompt you to do this).  This might give some hints why/where it is failing.  You can run this on the head node (it should be reasonably light weight) or from an interactive login (I don't suggest running it as a batch job).

Before starting, remove the 2-correction directory, which should be mostly empty.  With saveOverlaps=true, canu will either try to create the overlap store again -- I find it hard to believe there isn't any trace of the ovlStore directory -- or it will move on to 'filterCorrectionOverlaps' from your first log.

What files do exist in the correction/ directory (the directory where the gkpStore and ovlStore are)?

**Comment by EGroWi** [comment]
Found it! We - well, I- caused the problem by having quotation marks around the "parallel" setting for "ovsMethod=". Now everything runs smoothly. Sorry for the bother!

**Comment by brianwalenz** [comment]
Was this in a spec file or on the command line?  That's certainly something we should be allowing.

**Comment by EGroWi** [comment]
That was in the specs-file.

**Comment by brianwalenz** [comment]
Apologies for the frustration, I'll try to get it fixed.

**Comment by brianwalenz** [comment]
Fixed.  I'm sure someone will figure out the problem it still has -- a file name of `"reads.fasta"` _with_ the quotes will break it -- but if they do that, I have no sympathy.  (Although, supplying `""reads.fasta""` should work...)

**Comment by HenrivdGeest** [comment]
Thanks topic starter for pointing me in the right direction... I encountered the same sort of behaviour, but my error "no ovlStore found" was caused because the ovl store is not created at all due to miss spelling of the word paralell (instead of parallel).
Strage thing is that the CANU log just says:
```
-- BEGIN CORRECTION
--
-- Found 621 mhap overlap output files.
-- Finished stage 'cor-mhapCheck', reset canuIteration.
--
-- Overlap store 'correction/ac761.ovlStore' successfully constructed.
-- Overlap store 'correction/ac761.ovlStore' statistics not available (skipped in correction and trimming stages).
-- Finished stage 'cor-createOverlapStore', reset canuIteration.
-- Computing global filter scores 'correction/2-correction/ac761.globalScores'.
----------------------------------------
-- Starting command on Tue Jun 27 17:21:29 2017 with 52515.987 GB free disk space

    cd correction/2-correction
    /cm/shared/apps/canu/gcc/64/1.5/bin/filterCorrectionOverlaps \
      -G ../ac761.gkpStore \
      -O ../ac761.ovlStore \
      -S ./ac761.globalScores.WORKING \
      -c 200 \
      -l 0 \
    > ./ac761.globalScores.err 2>&1

-- Finished on Tue Jun 27 17:21:29 2017 (lickety-split) with 52515.987 GB free disk space
```
I am happy that I put in there saveOverlaps, since without this string,  the 1-overlapper results are purged, and one could start over. That happended to me the last few days....
Anyway, maybe CANU sould check a bit better if the ovl store is created succesfully before the mhap results are purged?

**Comment by brianwalenz** [comment]
Thanks.  We usually check the parameters, but ovsMethod slipped by.

I added a mostly useless report of the number of overlaps found, which serves to make sure the overlap store is working, before purging outputs.
```
-- Starting command on Thu Jun 29 05:05:59 2017 with 2478.339 GB free disk space

    cd unitigging
    /work/canu/FreeBSD-amd64/bin/ovStoreBuild \
     -O ./test.ovlStore.BUILDING \
     -G ./test.gkpStore \
     -M 2-8 \
     -L ./1-overlapper/ovljob.files \
     > ./test.ovlStore.err 2>&1

-- Finished on Thu Jun 29 05:06:00 2017 (1 second) with 2478.339 GB free disk space
----------------------------------------
-- Checking store.
----------------------------------------
-- Starting command on Thu Jun 29 05:06:00 2017 with 2478.339 GB free disk space

    cd unitigging
    /work/canu/FreeBSD-amd64/bin/ovStoreDump \
     -G ./test.gkpStore \
     -O ./test.ovlStore \
     -d -counts \
     > ./test.ovlStore/counts.dat 2> ./test.ovlStore/counts.err

-- Finished on Thu Jun 29 05:06:00 2017 (lickety-split) with 2478.339 GB free disk space
----------------------------------------
--
-- Overlap store 'unitigging/test.ovlStore' successfully constructed.
-- Found 1559332 overlaps for 21413 reads; 0 reads have no overlaps.
--
--
-- Purged 0.015 GB in 54 overlap output files and 1 directories.
----------------------------------------
```
