### ISSUE TITLE
latest update - something broken? Not going past step1

### ISSUE THREAD

**Issue by hodgett** [marbl/canu#362]
When running the latest canu (built 20170206) it will not progress past canu1. I get canu.01.out claiming that it finished but there are no other .sh scripts, not outputs, not files created, no 'correction' folder. Previous builds do still work.
(from canu.01.out)
```
-- Parameters:
--
--  genomeSize        1800000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.0450 (  4.50%)
--    obtOvlErrorRate 0.0390 (  3.90%)
--    utgOvlErrorRate 0.0390 (  3.90%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0390 (  3.90%)
--    utgErrorRate    0.0390 (  3.90%)
--    cnsErrorRate    0.0390 (  3.90%)
--
-- This is canu parallel iteration #1, out of a maximum of 2 attempts.
--
--
-- BEGIN CORRECTION
--
-- Meryl attempt 1 begins.
--
-- 'meryl.jobSubmit.sh' -> job 1636328.pbs tasks 1.
--
----------------------------------------
-- Starting command on Tue Feb  7 13:52:33 2017 with 1432901.814 GB free disk space

    cd /lustre/home-lustre/hodgett
    qsub \
      -W depend=afterany:1636328.pbs \
      -l mem=4g \
      -l nodes=1:ppn=1 \
      -V \
      -l nodes=1:ppn=8,walltime=196:00:00,mem=32gb \
      -W umask=0007  \
      -N 'canu_banaf_MH_banaf' \
      -j oe \
      -o canu-scripts/canu.05.out canu-scripts/canu.05.sh
1636329.pbs

-- Finished on Tue Feb  7 13:52:34 2017 (1 second) with 1432901.814 GB free disk space
----------------------------------------

-----
PBS Job 1636326.pbs
CPU time  : 00:00:00
Wall time : 00:00:06
Mem usage : 3492kb
```

**Comment by brianwalenz** [comment]
We changed from using absolute paths to relative paths.  Before, it didn't matter where the binaries or scripts ran from, they'd find the assembly directory.  But this also meant the assembly had to run on a shared filesystem.  Now, the binaries and scripts don't care where the assembly directory is, but it is critical they be run from within that directory.

What I see immediately is the lack of any kind of option to tell qsub to run canu05.sh in a specific directory.  Because of this, it probably ran in your home directory, leaving a bit of crud there.

The qsub command is being run from where the script should start.  Try using gridOptions=-d `pwd` (put in ~/.canu, so the back ticks don't get expanded early) .  If that works, I can implement a proper solution.  I'm finding a bunch of conflicting docs about PBS and PBSpro's qsub command, so I don't really know the correct switches to use.

**Comment by hodgett** [comment]
When determining a relative path, how are you determining that? I do see canu cd to the correct location for the first job. Are you sure you have your code right for figuring out where to run from? Are the subsequent jobs also cd to the right location when submitting a job?

Snipped from canu output;
```
    cd /lustre/work-lustre/bob/CANU_MH_Test_20170207/banaf-auto
    qsub \
      -l mem=4g \
      -l nodes=1:ppn=1 \
      -V \
      -l nodes=1:ppn=8,walltime=196:00:00,mem=32gb \
      -W umask=0007 \
      -v PBS_O_WORKDIR=/work/bob/CANU_MH_Test_20170207  \
      -N 'canu_banaf_MH_banaf' \
      -j oe \
      -o canu-scripts/canu.01.out canu-scripts/canu.01.sh
1638591.pbs
```
I have tried a number of options PBS, nothing is working yet which is why I'm still questioning your code. For PBSpro there are environment variables that are set when a job runs and should be able to be set using the -v options;
```
$PBS_HOME          The home directory Where you ran qsub command
$PBS_O_WORKDIR     The working directory from where you ran qsub
```
Setting these in gridOptions does not seem to be working. Your suggestion of -d won't work, there is no such option in PBSpro qsub.

**Comment by hodgett** [comment]
I tried running again, this time from the root of my home folder. It failed. Some files went in to the sub-folder -d banaf-auto and some went in to the home root.

**Comment by brianwalenz** [comment]
Thanks.  That is the expected (and wrong) behavior.

Canu is expecting the qsub command to have an option to tell it to run the script in a specific directory.  For reasons I can't imagine, PBSPro doesn't have such an option, and instead makes the script do this via those environment variables.

I'll add support for this probably next week.

**Comment by brianwalenz** [comment]
Hopefully fixed.

**Comment by hodgett** [comment]
I have been trying to test this using a small dataset. We have had a small hiccup on our system that has slowed me down but that has been sorted out.
 I am not yet sure this has been completely fixed but it is a lot closer than it was. The process is at the cormhap step and has submitted an array job, begun running a job (1661262[12]), and then seems to have completely stalled. The process on the node has 0% utilisation. I'm going to kill all and try again. I can't make heads or tails from the logs. Is there a single log file like the one from the output of a local running job? 
```
    1661262[1] cormhap_buildtest_MH_canu_bldtst  X   1     2 ---     33.6 -----    196 -----  
    1661262[2] cormhap_buildtest_MH_canu_bldtst  X   1     2 ---     33.6 -----    196 -----  
    1661262[3] cormhap_buildtest_MH_canu_bldtst  X   1     2 ---     33.6 -----    196 -----  
    1661262[4] cormhap_buildtest_MH_canu_bldtst  X   1     2 ---     33.6 -----    196 -----  
    1661262[5] cormhap_buildtest_MH_canu_bldtst  X   1     2 ---     33.6 -----    196 -----  
    1661262[6] cormhap_buildtest_MH_canu_bldtst  X   1     2 ---     33.6 -----    196 -----  
    1661262[7] cormhap_buildtest_MH_canu_bldtst  X   1     2 ---     33.6 -----    196 -----  
    1661262[8] cormhap_buildtest_MH_canu_bldtst  X   1     2 ---     33.6 -----    196 -----  
    1661262[9] cormhap_buildtest_MH_canu_bldtst  X   1     2 ---     33.6 -----    196 -----  
   1661262[10] cormhap_buildtest_MH_canu_bldtst  X   1     2 ---     33.6 -----    196 -----  
   1661262[11] cormhap_buildtest_MH_canu_bldtst  X   1     2 ---     33.6 -----    196 -----  
   1661262[12] cormhap_buildtest_MH_canu_bldtst  R   1     2   5     33.6   0.0    196    01  cl2n126/1*2 
   1661262[13] cormhap_buildtest_MH_canu_bldtst  X   1     2 ---     33.6 -----    196 -----  
   1661262[14] cormhap_buildtest_MH_canu_bldtst  X   1     2 ---     33.6 -----    196 -----  
   1661262[15] cormhap_buildtest_MH_canu_bldtst  X   1     2 ---     33.6 -----    196 -----  
   1661262[16] cormhap_buildtest_MH_canu_bldtst  X   1     2 ---     33.6 -----    196 -----  
   1661262[17] cormhap_buildtest_MH_canu_bldtst  X   1     2 ---     33.6 -----    196 -----  
   1661262[18] cormhap_buildtest_MH_canu_bldtst  X   1     2 ---     33.6 -----    196 -----  
       1661263 canu_buildtest_MH_canu_bldtst  H   1     1 ---     33.6 -----    196 -----  
```

**Comment by hodgett** [comment]
Failed.
```
canu \
  -p buildtest -d /work/_team/CANU_builttest \
  genomeSize=4.8m \
  -pacbio-raw /work/_team/CANU_builttest/ecoli_p6_25x.filtered.fastq \
  correctedErrorRate=0.039 \
  useGrid=true \
  gridOptionsJobName=MH_canu_bldtst \
  "gridOptions=-V -l walltime=196:00:00 -W umask=0007" 
```
Results in canu.0{1,2,3}.{out|sh}.
canu.02.out;
```
...
-- Running jobs.  Second attempt out of 2.
--
-- 'mhap.jobSubmit.sh' -> job 1662050[].pbs tasks 1-3.
--
----------------------------------------
-- Starting command on Thu Feb 16 14:25:59 2017 with 1436859.072 GB free disk space

    cd /lustre/work-lustre/_team/CANU_builttest
    qsub \
      -W depend=afterany:1662050[].pbs \
      -l mem=8g \
      -l nodes=1:ppn=1 \
      -V \
      -l walltime=196:00:00 \
      -W umask=0007  \
      -N 'canu_buildtest_MH_canu_bldtst' \
      -j oe \
      -o canu-scripts/canu.03.out canu-scripts/canu.03.sh
1662051.pbs

-- Finished on Thu Feb 16 14:25:59 2017 (lickety-split) with 1436859.072 GB free disk space
----------------------------------------

-----
PBS Job 1662043.pbs
CPU time  : 00:00:00
Wall time : 00:00:06
```
canu.03.out
```
...
-- Generating assembly 'buildtest' in '/lustre/work-lustre/_team/CANU_builttest'
--
-- Parameters:
--
--  genomeSize        4800000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.0450 (  4.50%)
--    obtOvlErrorRate 0.0390 (  3.90%)
--    utgOvlErrorRate 0.0390 (  3.90%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0390 (  3.90%)
--    utgErrorRate    0.0390 (  3.90%)
--    cnsErrorRate    0.0390 (  3.90%)
--
--
-- BEGIN CORRECTION
--
--
-- 3 mhap jobs failed:
--   job 1-overlapper/results/000001.ovb FAILED.
--   job 1-overlapper/results/000002.ovb FAILED.
--   job 1-overlapper/results/000003.ovb FAILED.
--
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'canu iteration count too high, stopping pipeline (most likely a problem in the grid-based computes)'.

-----
PBS Job 1662051.pbs
CPU time  : 00:00:00
Wall time : 00:00:02
Mem usage : 2088kb
```

**Comment by hodgett** [comment]
I have noticed the following error in mhap.\$PBS_ARRAY_INDEX.out that could be the reason why - is this a new bug? 

`/pkg/suse12/software2/ctcb/canu/1.4.20170216/Linux-amd64/bin/mhapConvert: /pkg/suse12/software/gcccore/4.9.3/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /pkg/suse12/software2/ctcb/canu/1.4.20170216/Linux-amd64/bin/mhapConvert)`

**Comment by hodgett** [comment]
Hold off, I'm doing a test. It may have been that one of our head nodes was at an updated patch version when compiling. Don't panic yet!

**Comment by hodgett** [comment]
Ok, I'm happy to report that we have succeeded in assembling the ecoli and an 8cell sample of our own data using PBSpro on our cluster. 

@brianwalenz Thanks for sorting this out, along with several of the other issues that were preventing us trying to assemble our main sequence. We will submit that job now and if there are any new issues I'll post as a new issue.

**Comment by brianwalenz** [comment]
Awesome!  Glad to hear.  The other issue you have open (with the unexpanded variable in output names) is mostly cosmetic.  I have a potential fix being tested - well, what little testing I can do without access to PBS Pro.
