### ISSUE TITLE
Input files

### ISSUE THREAD

**Issue by mictadlo** [marbl/canu#364]
Hi,
One RSII SMRT cell contains one h5 file, but when we converted it to Fasta file we get 3 Fasta files.

Furthermore, we have Sequel SMRT cells. Each of them contains one Fasta file.

Can we merge all Fasta files from RSII and Sequal into one big Fasta file?

Thank you in advance

Michal

**Comment by mjpdejong** [comment]
No need to merge, you can feed multiple fasta files separated by a space to Canu

`canu \
-p ecoli -d ecoli \
genomeSize=4.8m \
-pacbio-raw  1.fasta 2.fasta 3.fasta 4.fasta etc...`

**Comment by skoren** [comment]
You can also use wildcards ```-pacbio-raw *.fasta```
