### ISSUE TITLE
ctgStore.coverageStat. Coverage statistics.

### ISSUE THREAD

**Issue by migrau** [marbl/canu#365]
What is the content of x.ctgStore.coverageStat.log? There are not coverage statistics (coverage per contig) after unitigging step? Before unitigging, log contents `Found X bases (X times coverage)`. Is it for the final assembly?
Thanks!

Miquel

**Comment by brianwalenz** [comment]
There is supposed to be a header.  I don't know why it isn't being reported.  The columns are:
```
tigID rho coverage-stat arrival-distance
```

The log you quote is just global coverage in input reads.  Some of these reads might not be assembled.

There isn't a report of read coverage per contig/unitig in the default output.  Looking though the utility programs, I don't see any that will generate a coverage-per-contig report.  However,
```
tgStoreDump -G asm.gkpStore -T asm.ctgStore 2 -o OUT -coverage -tig 1-10
```
will generate a plot of coverage across the first ten contigs, one plot per contig.

**Comment by migrau** [comment]
Thanks a lot, brianwalenz. The tgStoreDump solution is what I was looking for. 
In my case, using "Canu v1.4 (+78 commits) r8073 8dde4fdb781d5fb4bc53c444c31ecdc25063ce1f.", I don't have the headers in x.ctgStore.coverageStat.log.

Miquel

**Comment by brianwalenz** [comment]
The header has returned!
