### ISSUE TITLE
errorRate being used by canu is default and not what i set

### ISSUE THREAD

**Issue by amit4mchiba** [marbl/canu#366]
Hi,

I am very new to canu, and was trying to perform de novo genome assembly using PacBio reads. 
My running scripts were-
```
#!/bin/sh
#$ -S /bin/sh
#$ -l month -l medium
#$ -N canu5-med
#$ -pe def_slot 5-100
#$ -cwd

/home/amit-rai8chiba/canu-1.4/Linux-amd64/bin/canu -p G_glabra_med -d ./G_glabra-assembly_med \
genomeSize=400m \
-pacbio-raw /home/amit-rai8chiba/G_glabra_pcdata/data/G_glabra_all_cat.fastq.gz \
useGrid=0 \
maxMemory=100 \
maxThreads=$NSLOTS \
minThreads=22 \
corMhapSensitivity=high \
errorRate=0.05 \
corMinCoverage=0 \
corOutCoverage=100 \
corErrorRate=0.105 \
minReadLength=200 \
minOverlapLength=100 \
utgGraphDeviation=50 \
corMaxEvidenceErate=0.15 \
```

I wanted to use error rate as 0.05 (and want to test different values of it, such as 0.075, 0.105). While running canu, this is the parameter being used-
```
-- Detected Java(TM) Runtime Environment '1.8.0_45' (from 'java').
-- Detected gnuplot version '4.4 patchlevel 4' (from 'gnuplot') and image format 'png'.
-- Detected 80 CPUs and 2020 gigabytes of memory.
-- Detected Sun Grid Engine in '/home/geadmin2/UGER/uger'.
-- Grid engine disabled per useGrid=false option.
--
-- Allowed to run   6 jobs concurrently, and use up to   8 compute threads and   16 GB memory for stage 'bogart (unitigger)'.
-- Allowed to run   5 jobs concurrently, and use up to  10 compute threads and   13 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   5 jobs concurrently, and use up to  10 compute threads and   13 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   5 jobs concurrently, and use up to  10 compute threads and   13 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run  17 jobs concurrently, and use up to   3 compute threads and    5 GB memory for stage 'read error detection (overlap error adjustment)'.
-- Allowed to run  51 jobs concurrently, and use up to   1 compute thread  and    2 GB memory for stage 'overlap error adjustment'.
-- Allowed to run   6 jobs concurrently, and use up to   8 compute threads and   16 GB memory for stage 'utgcns (consensus)'.
-- Allowed to run  51 jobs concurrently, and use up to   1 compute thread  and    2 GB memory for stage 'overlap store parallel bucketizer'.
-- Allowed to run  51 jobs concurrently, and use up to   1 compute thread  and   16 GB memory for stage 'overlap store parallel sorting'.
-- Allowed to run  51 jobs concurrently, and use up to   1 compute thread  and    2 GB memory for stage 'overlapper'.
-- Allowed to run  17 jobs concurrently, and use up to   3 compute threads and    5 GB memory for stage 'overlapper'.
-- Allowed to run  17 jobs concurrently, and use up to   3 compute threads and    5 GB memory for stage 'overlapper'.
-- Allowed to run   5 jobs concurrently, and use up to  10 compute threads and   20 GB memory for stage 'meryl (k-mer counting)'.
-- Allowed to run  12 jobs concurrently, and use up to   4 compute threads and    8 GB memory for stage 'falcon_sense (read correction)'.
-- Allowed to run   5 jobs concurrently, and use up to  10 compute threads and   13 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   5 jobs concurrently, and use up to  10 compute threads and   13 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   5 jobs concurrently, and use up to  10 compute threads and   13 GB memory for stage 'minimap (overlapper)'.
--
-- This is canu parallel iteration #1, out of a maximum of 2 attempts.
--
-- Final error rates before starting pipeline:
--   
--   genomeSize          -- 400000000
--   errorRate           -- 0.015
--   
--   corOvlErrorRate     -- 0.045
--   obtOvlErrorRate     -- 0.045
--   utgOvlErrorRate     -- 0.045
--   
--   obtErrorRate        -- 0.045
--   
--   cnsErrorRate        -- 0.045
--
--
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Thu Feb  9 15:17:15 2017 with 928268.62 GB free disk space
```
So, is it not possible to over write default errorRate parameter?

Please advice if i need to modify my command

**Comment by brianwalenz** [comment]
Hi-

Before you get too far into canu, I'd encourage you to upgrade the to latest unreleased version by using the green 'clone or download' button on the github page.  The errorRate parameters have changed since the 1.4 release.  Canu 1.5 will probably be out in around three weeks.

In 1.4 'errorRate' was interpreted as 'expected error rate in a single corrected read'.  Canu then multiplied this by 3 to get the other error rates which are interpreted as 'error rate in an alignment between two reads'.

In the latest version, all error rates are for alignments between two reads.

http://canu.readthedocs.io/en/latest/tutorial.html#error-rates
http://canu.readthedocs.io/en/latest/parameter-reference.html#global-options

Other comments:

Depending on the actual data, a minimum of 200bp not recommended.  The short reads won't contribute anything to the assembly structure and will just add computational expense and noise.

The corErrorRate is way too low - I suspect all overlaps will be filtered, and none will be left to generate corrected reads.  The default is 0.30 for PacBio.

corMaxEvidenceErate was a parameter very very early in canu development.  We stopped using this as a filter - it's still allowed, but by default, no filtering is done.  Use at your own risk!

**Comment by amit4mchiba** [comment]
Thank you so much. Indeed all my reads got filtered left nothing to generate corrected read. I will restart canu and make these changes. May i ask what parameteres i shall use to ensure a that most of my reads have got assembled. Reason for minLength as 200 and lower overlap length was to achieve or include all reads (although it does not matter since all reads were over 1000 which is default). About corErrorRate, it was a mistake. Going through Canu manual, i found comment on assembling low coverage datasets, where it was recommended to use correctedErrorRate=0.105 for a coverage around 20x. I thought that since there is no parameter called correctedErroRate, so, it must be corErrorRate. I will like to request you to please advice me what will be the most suitable parameter that i should change to achieve a better assembly using canu. My genome size is 400, and coverage is 25x. Based on my reading, i think that i must choose cormhapSensitivity as high, corOutCoverage as 50, corMinCoverage as 0, What else will be helpful to me. Increasing error rate? Thank you

**Comment by brianwalenz** [comment]
The parameters you've listed at the end are correct for low coverage data.  Other than using the latest code, and following the [low coverage recipe](http://canu.readthedocs.io/en/latest/quick-start.html#assembling-low-coverage-datasets) in the [quick start guide](http://canu.readthedocs.io/en/latest/quick-start.html) I don't have much else to advise.
