### ISSUE TITLE
Is it possible to add new data during the assembly?

### ISSUE THREAD

**Issue by lamz138138** [marbl/canu#368]
Hi!

I had checked docs and issues, but without finding this question. If I had finished assembly with 30X data, then I got another 30X data, whether I have to re-run the pipeline completely? Is it possible to used the data produce previously?

By the way, I had found I mistake fasta as fastq, that is I had give the parameter "-pacbio-raw data/CLR.fq", but CLR.fq is a fasta file, did I have to restart the pipeline, or it would take it as fasta automatic?

**Comment by brianwalenz** [comment]
Nope, nothing can be reused.  The additional data can be used to correct the original reads, which should result in better corrections.  You'll probably get about the same amount of data in corrected reads, but the reads should be longer.

It doesn't use the file extension for anything.  You can freely mix fasta and fastq, I think even in the same file (but don't do that).  You can also give any mix of compressed and uncompressed files.

**Comment by lamz138138** [comment]
OK, thanks for your reply!
