### ISSUE TITLE
canu-1.4.Linux-amd64.tar.xz install error

### ISSUE THREAD

**Issue by wsuplantpathology** [marbl/canu#372]
Hello:

I was trying to install canu-1.4 binary distribution. After I downloaded canu-1.4.Linux-amd64.tar.xz, I try this:
tar xvf canu-1.4.Linux-amd64.tar.xz

and got this error:

tar: This does not look like a tar archive
tar: Skipping to next header
tar: Archive contains obsolescent base-64 headers
tar: Read 3728 bytes from canu-1.4.Linux-amd64.tar.xz
tar: Error exit delayed from previous errors

I wonder should the tar ball be .tar.gz ?

Thanks.

**Comment by skoren** [comment]
I checked, the archive works. The xz extension is correct, the archive is compressed with XZ (https://en.wikipedia.org/wiki/XZ_Utils) and you need to provide the correct unzip option to tar (J in this case). You can either use ```tar xvJf ``` or ```xz -dc canu-1.4.Linux-amd64.tar.xz |tar -xf -```. I updated the release notes to clarify this.
