### ISSUE TITLE
failed to generate unitigs

### ISSUE THREAD

**Issue by fyymxb** [marbl/canu#377]
Hello,
  In the assemble step, I got an error that claimed "failed to generate unitigs".
  In the direcroty /unitigging/4-unitigger, the file 'unitigger.err' give the error information: bogart: bogart/AS_BAT_OverlapCache.C:468: uint32 OverlapCache::filterDuplicates(uint32&): Assertion `_ovs[jj].a_iid != 0' failed.
  I have carefully refered to the issues 139 (https://github.com/marbl/canu/issues/139) and 154 (https://github.com/marbl/canu/issues/154), I found that both of the error information from those two issues are different from mine.
  Could you give some help?

**Comment by brianwalenz** [comment]
This might be #328.  What version are you using?

**Comment by fyymxb** [comment]
The version that issued errors was downloaded from canu github web site in January 13, 2017. 
And another version that I downloaded in February 20, 2017 didn't issued any errors.
In addition, the overlapper of the correction, trim and assemble steps was all set as MHAP.
