### ISSUE TITLE
corrected error rate option rename?

### ISSUE THREAD

**Issue by calkan** [marbl/canu#378]
canu -version
Canu v1.4 (+21 commits) r8016 37b9b8074a5741fed7e7a6839b862d1eb11daa56.

Documentation mentions the option "correctedErrorRate", however when I use it:

ERROR:  Paramter 'correctedErrorRate' is not known. 
 (plus the typo Paramter)

however:

canu -options | grep -i error
cnsErrorRate                            Consensus expects alignments at about this error rate
corErrorRate                            Only use raw alignments below this error rate to construct corrected reads

I guess corErrorRate = correctedErrorRate ?

**Comment by brianwalenz** [comment]
The docs are referring to the latest version; the one you have is from December 22nd.  The error rate options changed on Jan 27th in eff57049b07837d3ee3a35807ba636c215163d8f.

corErrorRate controls which overlaps are used for correcting reads.  It is completely different from correctedErrorRate.  I'll try to make this more clear in the docs (and add some e's into the various paramters, thanks).

**Comment by calkan** [comment]
thanks. I pulled the latest version, and it is doing -something- now. Will continue to do so for a while :)
