### ISSUE TITLE
trimming.html and unitigging.html

### ISSUE THREAD

**Issue by kk86bioinfo** [marbl/canu#38]
It seems the html is not completely generated, for instance:

```
<h2>Trimming</h2>

<h2>Trimmed Reads</h2>
```

are remains empty even the trimming process is completed.

**Comment by brianwalenz** [comment]
These are definitely 'works in progress', aren't critical to the pipeline, and have a pretty low priority.

That said, the trimming file should be populated.  The last big change was on the 19th.  The unitigging file is still pretty empty.

**Comment by kk86bioinfo** [comment]
I see, sorry, thought that my run has issue that render it not properly generated. Should this be mentioned in documentation that HTML output is not ready?

**Comment by brianwalenz** [comment]
They've got enough information to be useful now.  There's more on the wish list, but nothing there is currently a priority.

Suggestions welcome, as are patches to make the pages less ugly.
