### ISSUE TITLE
using stageDirectory with pbspro

### ISSUE THREAD

**Issue by hodgett** [marbl/canu#384]
I was trying to use stageDirectory with pbspro (stageDirectory=$TMPDIR) but find it doesn't appear to get used. I notice in the documentation that "If gridEngineStageOption is left undefined, no resources will be requested for staging the data." I am assuming this means that if gridEngineStageOption is blank then stageDirectory is not used at all, however I see no option with pbspro that could be used in gridEngineStageOption. Have I missed something?

**Comment by brianwalenz** [comment]
Is TMPDIR known at submit time, or is this set only in the PBS job?  You might need to escape the $; stageDirectory=\$TMPDIR.

This is used only for read correction, and will appear in 2-correction/correctReads.sh.  Look for 'Start copy' in that file; if it's there, staging is enabled.  There will be four 'cp' commands around there, copying parts of the gkpStore to the specified directory.

The docs are noting that, like with memory and CPUs, the job can use the resources, but unless it requests them from the grid, the use might be 'illegal'.  If your directory is a free-for-all local scratch space, you don't need gridEngineStageOption.

**Comment by hodgett** [comment]
Ok, I'll try that. BTW, your example of escaping I don't think showed properly.

**Comment by brianwalenz** [comment]
Yup, didn't show correctly.  Fixed, thanks.

**Comment by skoren** [comment]
Closing, inactivity, open a new issue if you encounter errors.
