### ISSUE TITLE
urgent: gkStore()--  failed to open './cor.gkpStore' for read-only access: store doesn't exist.

### ISSUE THREAD

**Issue by hodgett** [marbl/canu#385]
We are still having trouble with getting canu (sourced Feb 16) to work with our 1.8g data and I have almost run out of time. As of Tues next week I will not be able to work on this for another month. Smaller datasets that we have tested with on our PBSpro cluster work fine. Now it is crashing out with error; 
"gkStore()--  failed to open './cor.gkpStore' for read-only access: store doesn't exist.
canu failed with 'failed to generate configuration for building overlap store'."

This is the command line;
```
#!/bin/bash
module unload ctcb/canu
module load ctcb/canu/1.4.20170216
canu \
  -p 110celltst -d $PWD \
  genomeSize=1.8g \
  -pacbio-raw /work/All_RawData/RSnSeQ_110.fastq \
  correctedErrorRate=0.039 \
  stageDirectory=$TMPDIR \
  gridEngineStageOption="-m a" \
  maxMemory=125 \
  minMemory=4 \
  useGrid=true \
  gridOptionsJobName=MH_canu_110ctst \
  "gridOptions=-V -l walltime=196:00:00 -W umask=0007" \
  corMaxEvidenceErate=0.15 \
  minReadLength=3000 \
  minOverlapLength=2000 
```

and this is the output of canu.02.out;
```
...
-- BEGIN CORRECTION
--
-- Found 421 mhap overlap output files.
-- Finished stage 'cor-mhapCheck', reset canuIteration.
----------------------------------------
-- Starting command on Thu Feb 23 16:09:03 2017 with 1383898.476 GB free disk space
    cd correction
    ./cor.ovlStore.BUILDING/scripts/0-config.sh \
    > ./cor.ovlStore.BUILDING/config.err 2>&1

-- Finished on Thu Feb 23 16:09:03 2017 (lickety-split) with 1383898.476 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.
Disk space available:  1383898.476 GB
Last 50 lines of the relevant log file (correction/cor.ovlStore.BUILDING/config.err):
Max processes per user limited to 2064739, no increase possible.
Max open files limited to 16384, no increase possible.
gkStore()--  failed to open './cor.gkpStore' for read-only access: store doesn't exist.
canu failed with 'failed to generate configuration for building overlap store'.
```

I can see in 0-config.sh that it is trying to use ./cor.ovlStore.BUILDING/config but it doesn't exist. Does this matter? Could this be what is stopping it from working?;
```
correction/cor.ovlStore.BUILDING/config.err contains;
`gkStore()--  failed to open './cor.gkpStore' for read-only access: store doesn't exist.`

$bin/ovStoreBuild \
 -G ./cor.gkpStore \
 -O ./cor.ovlStore \
 -M 4-32 \
 -config ./cor.ovlStore.BUILDING/config \
 -L ./1-overlapper/ovljob.files \
```

**Comment by brianwalenz** [comment]
That is a rather embarrassing mistake that somehow didn't get caught in testing (we're adding support for cloud-based engines, and that's resulted in quite a large amount of change recently).

It's fixed in the latest code.  Before restarting, remove the 110celltst.ovlStore.BUILDING directory so scripts get rewritten.

**Comment by hodgett** [comment]
Thanks for getting on to that so quickly. We have the code and am now running with that.
Using the code the day from the day before I did try removing 110celltst.ovlStore.BUILDING and re-running but it bombed out. I am re-running from the start.

**Comment by hodgett** [comment]
The errors I'm getting when deleting110celltst.ovlStore.BUILDING and re-running with the new code include;
```
-- 421 overlap store bucketizer jobs failed:
...

job correction/110celltst.ovlStore.BUILDING/bucket0421 FAILED.
```

**Comment by brianwalenz** [comment]
This might be PBS failing to create output files - are there any `2-sort*err` or similar files around?  I think they'll end up in either `110celltst.ovlStore.BUILDING` or `110celltst.ovlStore.BUILDING/scripts`.

Are there `create*` directories in `110celltst.ovlStore.BUILDING`?  If not, the jobs are probably failing to start at all.

Can you run `scripts/2-bucketize.sh 1` by hand, while in the `110celltst.ovlStore.BUILDING` directory?  This will run the first job.

Add `useGrid=remote` to your canu command.  This will tell canu to set up jobs for PBS, but to not actually run them.  It will instead print a `qsub` command for you to run the jobs with.  This might make it easier to figure out what is failing.

**Comment by brianwalenz** [comment]
Send me an email, too.

**Comment by hodgett** [comment]
No, something is wrong. 2-bucketize.sh is actually 1-bucketize.sh. I can call `scripts/2-bucketize.sh 1` and it works. I can call  `scripts/2-sort.sh 1` and it works. What calls these scripts?

**Comment by hodgett** [comment]
I also couldn't figure out what `useGrid=remote` is supposed to do - it did nothing. I don't see where the scripts are created for me to figure out whats happening.

**Comment by hodgett** [comment]
Ok, I have tried running1-bucketize.jobSubmit.sh from within 110celltst2.ovlStore.BUILDING and still get the error in files like ovB_110celltst2_MH_canu_110ctst.o1692789.99;
`gkStore()--  failed to open '../110celltst2.gkpStore' for read-only access: store doesn't exist.
`
and yet the folder does exist. Running 1-bucketize.sh from 110celltst2.ovlStore.BUILDING does work. It is something to do with the way jobs are being submitted, possibly not changing to the 110celltst2.ovlStore.BUILDING for the submitted job?

**Comment by skoren** [comment]
The jobs should be submitted from within 110celltst2.ovlStore.BUILDING and request to keep the same working directory. This option might not be working on PBS Pro. The script ```110celltst2.ovlStore.BUILDING/scripts/1-bucketize.jobSubmit.sh``` should have the PBS command being used to submit the job. 

Does the script work if you submit them from within 110celltst2.ovlStore.BUILDING.  You could try adding ```-V``` to it and submitting the jobs to see if they run correctly then.

**Comment by hodgett** [comment]
Jobs submitted via pbspro are still defaulting to the home folder!

**Comment by hodgett** [comment]
@skoren No, it doesn't work using the cluster even when submitting from within `110celltst2.ovlStore.BUILDING` (running the individual scripts directly does work). And yes, -V is already in the job.

**Comment by brianwalenz** [comment]
Can you paste in the header from those scripts, the part where it's using the PBS variables?

At this point, rather than trying to figure out what's wrong with canu, just edit those three scripts to hardcode a 'cd' to '/full/path/to/110celltst2.ovlStore.BUILDING', then submit by hand (you should be able to use the same jobSubmit scripts that are already there.

The 3-index.sh doesn't have a jobSubmit script.  This script needs to be run only once (i.e., not a job array).

When all done - when the store has a bunch of 4-digit files and an 'info' file - rename it to 110celltst2.ovlStore and then restart canu.  I think it's just this stage that isn't playing nicely with PBS Pro.

ALTERNATIVELY, you can switch back to the non-parallel version for this (use ovsMethod=sequential).  I wouldn't recommend this if the 1-overlapper directory is big.  If you do switch, remove 110celltst2.ovlStore.BUILDING before starting.

**Comment by brianwalenz** [comment]
Hopefully it'll behave better when you get back to this.  :-(
