### ISSUE TITLE
can we delete files after correction completes and trimming process continues

### ISSUE THREAD

**Issue by amit4mchiba** [marbl/canu#391]
Hi,

Sorry for asking this stupid question, but i was curious if we can delete huge files that is being created as part of read correction once the correction of PacBio step is over but trimming process is still on going. As these files require a lot of disk space, and i am working on different canu parameters, i am always getting over my allowed quota of disk space, and hence was curious to do this without affecting on-going assembly process.

thank you so much,
Amit

**Comment by skoren** [comment]
Yes, you can erase most of the files. The largest uses of space are probably the stores (\*.ovlStore and \*.gkpStore). You can remove them but to make sure Canu knows the correction step is complete, create empty placeholders once they are deleted (using ```mkdir -p```).

**Comment by amit4mchiba** [comment]
Thank you so  much. I have deleted all files within *.ovlStore but kept the folder...and it seems working fine.
