### ISSUE TITLE
canu failed with 'can't run 'qconf' to get SGE config'.

### ISSUE THREAD

**Issue by mw55309** [marbl/canu#392]
Hi

Problems running on our SGE cluster.

Why does Canu need qconf?  How do I get round this?

Cheers
Mick

**Comment by skoren** [comment]
Canu uses qconf to find flags for requesting memory and threads on the grid. It is also used to find the maximum array tasks allowed and the default shell behavior. 

Working around it is more complicated. You can bypass most calls by defining ```gridEngineThreadsOption=-pe thread THREADS```, ```gridEngineMemoryOption=-l mem_free=MEMORY```, ```gridOptions=/bin/sh``` which will skip some checks. Replace thread and mem_free with the appropriate flags on your system. However, you'd still need to comment out the code checking for array limits in src/pipelines/canu/Grid_SGE.pm:
```
 59     open(F, "qconf -sconf |") or caExit("can't run 'qconf' to get SGE config", undef);
 60     while (<F>) {
 61         if (m/max_aj_tasks\s+(\d+)/) {
 62             $maxArraySize = $1;
 63         }
 64     }
 65     close(F);
```

Canu will still try to use qhost to get a list of available hosts to run on so if that isn't available it will also cause issues.

**Comment by brianwalenz** [comment]
Mostly what Sergey said, except/additionally:
- Both THREADS And MEMORY are replaced by canu with actual values.
- "gridOptions=-S /bin/sh" (or /bin/bash)
- A workaround for the qhost call would be easy to implement, but not terribly easy to use.

**Comment by mw55309** [comment]
OK, so it would be great to be able to set these as options rather than have the canu jobs query SGE which is generally locked down on our system

Also qhost - why does it need to know this?  Forgive my naivety, but we just submit jobs using qsub and the scheduler decided which host or node the job gets run on.  What is it that qhost does that you need to do?

**Comment by skoren** [comment]
@brianwalenz added those as an option so I think you don't need qconf. The qhost query is used to build a list of available resources for Canu to request. It adjusts job sizes/parameters to fit into the available compute cluster. Without that there is no way to request memory/threads, it could request some combination not available on your system.

**Comment by mw55309** [comment]
OK so how do I bypass it?  

Surely there could be a way of setting sensible defaults?  Or user setting limits?  I mean I know the configuration of my cluster.  

I can even run qhosts and stick it as a text file for Canu to read....

**Comment by skoren** [comment]
Sure, edit the code in Grid_SGE.pm. Look for:
```
278     open(F, "qhost |");
```
and change it to open your text file instead.

**Comment by brianwalenz** [comment]
A trick I've used to simulate grids we don't run (like PBS) is to make a ~/bin/qhost command that returns the expected output.

You'll need to set (replacing 'thread' and 'mem_free' as needed):

gridEngineThreadsOption=-pe thread THREADS
gridEngineMemoryOption=-l mem_free=MEMORY
gridOptions=-S /bin/bash
gridEngineArrayMaxJobs=75000

I think I can make it use options maxThreads and maxMemory if it can't get any output from the proper method.  Give me a couple of hours to try.

I'm catching loose ends for the next release, so now is a good time to get this worked out.

**Comment by brianwalenz** [comment]
Give the latest a try.  Set maxMemory and maxThreads to, say, 1/2 what your nodes have.   Each canu job will be no bigger than that, and the grid will take care of running multiple jobs per node.

Stick all these options into ~/.canu or canu.defaults in the canu bin directory and they'll get used every time.
