### ISSUE TITLE
canu failed with 'didn't find any mers?'

### ISSUE THREAD

**Issue by MLister1** [marbl/canu#393]
Hi

I have received the following error when trying to run my pacbio data.

**Please panic.  canu failed, and it shouldn't have.

Stack trace:

 at /home/james/Downloads/canu-1.4/Linux-amd64/bin/lib/canu/Execution.pm line 1305.
	canu::Execution::caFailure("didn't find any mers?", "/home/james/Downloads/canu-1.4/Linux-amd64/bin/Documents/shel"...) called at /home/james/Downloads/canu-1.4/Linux-amd64/bin/lib/canu/Meryl.pm line 522
	canu::Meryl::merylProcess("/home/james/Downloads/canu-1.4/Linux-amd64/bin/Documents/shel"..., "VPI10463", "cor") called at canu line 471

Last few lines of the relevant log file (/home/james/Downloads/canu-1.4/Linux-amd64/bin/Documents/shell/170306_vpi_2/correction/0-mercounts/VPI10463.ms16.histogram.info):

Found 0 mers.
Found 0 distinct mers.
Found 0 unique mers.
Largest mercount is 0.

canu failed with 'didn't find any mers?'**.

I have used the following command:

`perl canu -correct -p VPI10463 -d Documents/shell/170306_vpi_2 corErrorRate=0.045 -genomeSize=4.3m  stopOnReadQuality=false -pacbio-raw VPI_10463_A.ccs.fastq.zip VPI_10463_A.filtered_subreads.fastq.zip VPI_10463_A.filtered_subreads.longest.fastq.zip`

Please could I get some help on this issue? Also could I get some clarification on which pacbio reads to use for this step, as you can see I have used all three .fastq files that I received.  
Apologies if there is an obvious fix I am a bioinformatics novice.

Thanks
Michelle

**Comment by skoren** [comment]
You don't want to provide the CCS reads to correction since they are already corrected by the SMRTportal software. I presume the longest.fastq.zip is a subset of filtered_subreads.fastq.zip so I would use only the filtered_subreads file. You can add the CCS reads after correction for assembly using the -pacbio-corrected option if you want.

As for the error, I think zip files are not supported, Canu should have detected the bad input and failed earlier but it did not. Can you try unzipping the files and running again?

**Comment by MLister1** [comment]
Thanks for the reply.  I have used your suggestions and everything has worked, the assembly size is what I was expecting too.

Just another quick question if you don't mind.  Is it possible to create a sam/bam file as part of the output?  Or use the outputs to make such files?

**Comment by skoren** [comment]
Canu does output approximate positions of the corrected reads in the contigs in the asm.contigs.layout* files. However, I presume you'd want the raw read alignments in your sam/bam so you'd have to track the corrected read back to the original raw read and compute an alignment to those positions in the final assembly indicated by the layout file. A sam/bam output is on our future features list but for now it's probably simplest to re-map the raw reads to the assembly.

**Comment by MLister1** [comment]
Ok thanks.  I will try your suggestion.
