### ISSUE TITLE
Trimming explanation

### ISSUE THREAD

**Issue by ptranvan** [marbl/canu#397]
Hi,

I am familiar with Illumina reads trimming but not with Pacbio.

Can you explain how the trimming work ? Does it trim a reads if it's below a certain score ? If yes how can I control that score ?

**Comment by skoren** [comment]
The trimming is based on a fixed count of overlaps to the corrected reads. If there is a read with no overlap support over part of it's sequence it is trimmed to the longest covered region. There are defaults on overlap error rate accepted and minimum coverage (default >1). 

The details are in the Canu paper:
http://biorxiv.org/content/early/2017/01/04/071282 in the overlap based trimming section.
