### ISSUE TITLE
What is the other option for ovsMethod?

### ISSUE THREAD

**Issue by qslin** [marbl/canu#398]
In the manual, there is only one option for ovsMethod given ("sequential”). This option seems suitable to small assembly. But I wanna assemble a genome up to 420Mb. So I think it might be better if I use the other option. What is the other option for ovsMethods?

**Comment by skoren** [comment]
The two options are sequential and parallel (listed in another part of the docs: http://canu.readthedocs.io/en/latest/parameter-reference.html#process-control). In general, Canu with defaults does something reasonable so you don't need to specify options unless you're trying to tune a specific aspect of the assembly. In this case, any genomes >300mb will automatically switch to the parallel version.
