### ISSUE TITLE
Difference between obtOvlErrorRate and obtErrorRate?

### ISSUE THREAD

**Issue by qslin** [marbl/canu#399]
If I use default algorithm for trimming, is there any difference between obtOvlErrorRate and obtErrorRate?

**Comment by brianwalenz** [comment]
obtOvlErrorRate controls which overlaps are generated, while obtErrorRate controls which overlaps are used.  So, obtOvlErrorRate=0.08 would compute overlaps up to 8% difference, and obtErrorRate=0.04 would then use only those below 4% difference (I just made up the values, not suggesting them).  It is suggested to set obtOvlErrorRate slightly higher than you want, so borderline overlaps are found.
