### ISSUE TITLE
Failed submit jobs SLURM grid

### ISSUE THREAD

**Issue by jordur** [marbl/canu#400]
Dear all, 
I tried to submit a canu assembly on a SLURM grid enviroment. However, it was unsuccesful. In fact I got the following:
```
Please panic.  canu failed, and it shouldn't have.

Stack trace:

 at /home/ibv/jdurban/programas/canu/Linux-amd64/bin/lib/canu/Execution.pm line 1475.
        canu::Execution::caFailure('Failed to submit batch jobs', undef) called at /home/ibv/jdurban/programas/canu/Linux-amd64/bin/lib/canu/Execution.pm line 1094
        canu::Execution::submitOrRunParallelJob('Canu_assembly', 'meryl', 'correction/0-mercounts', 'meryl', 1) called at /home/ibv/jdurban/programas/canu/Linux-amd64/bin/lib/canu/Meryl.pm line 406
        canu::Meryl::merylCheck('Canu_assembly', 'cor') called at /home/ibv/jdurban/programas/canu/Linux-amd64/bin/canu line 513

canu failed with 'Failed to submit batch jobs'. 
```
Attached you will find a full logfile.
The command line was as follow:
```
canu -p Canu_assembly -d Canu_assembly maxMemory=64G maxThreads=12 gridOptionsJobName=Canu_assembly "gridOptions=--n 4 --time 72:00 --mem-per-cpu=16GB" errorRate=0.013 genomeSize=11k corMinCoverage=0 corOvlErrorRate=0.1 -nanopore-raw Sequences.fasta &> Canu_assembly/canu.log
```
Should I contact with my systems administrator? It could be a matter of cluster use?
Thank you in advance
[canu_log.txt](https://github.com/marbl/canu/files/828335/canu_log.txt)

**Comment by skoren** [comment]
It is most likely a matter of missing required cluster options. What is the log in correction/0-\*/meryl.jobSubmit.out. You don't need to specify threads/memory in the gridOptions, Canu will take care of that for you.

On another note, is your genome really only 11kb, you probably want to use the options for plasmids/viral genomes on the FAQ:
http://canu.readthedocs.io/en/latest/faq.html#my-asm-contigs-fasta-is-empty-why

**Comment by jordur** [comment]
Thank you @skoren . In fact it was just a try of using canu under a SLURM environment using an amplicon of 11Kb. The goal is to use canu to assembly a non-reference 1.8-2Gbp genome. 
By the way, what do you mean by "You don't need to specify threads/memory in the gridOptions, Canu will take care of that for you." ? I am not allowed to use the entire resources of the grid so I would like to set a proper memory to perform the task avoiding any annoying use of the computational resources to the rest of users.

**Comment by skoren** [comment]
Canu will request whatever memory/threads it needs for each task, it varies by task in the assembly process. Requesting 16gb/4 threads across the board will likely fail if it chooses to use more. The SLURM sheduler's job is to keep you from using the entire resources of the grid not yours. There are often limits on how many total CPUs you will get access to.

**Comment by jordur** [comment]
Hi @skoren . Thank you for your suggestions. However something is going wrong with SLURM grid engine. As you can see in the canu_desktop.txt logfile, an assembly from a 11Kb test sequence was just ~ 15 secs (from 13:43:17 to 13:43:30) on a 16gb/8 desktop computer. However, on the SLURM system, seemed to be stalled on the meryl algorithm since it so far it is > 25min (in fact it is still running). A 'scontrol' call to the SLURM grid retrieves the following information:
```
  NumNodes=1 NumCPUs=4 CPUs/Task=4 ReqB:S:C:T=0:0:*:*
   Socks/Node=* NtasksPerN:B:S:C=0:0:*:* CoreSpec=*
   MinCPUsNode=4 MinMemoryCPU=1280M MinTmpDiskNode=0
   Features=(null) Gres=(null) Reservation=(null)
   Shared=OK Contiguous=0 Licenses=(null) Network=(null)
   Command=./meryl.sh 0
   WorkDir=/scratch-local/jdurban/5710/Canu_assembly/correction/0-mercounts
   StdErr=/scratch-local/jdurban/5710/Canu_assembly/correction/0-mercounts/meryl.5711_1.out
   StdIn=/dev/null
   StdOut=/scratch-local/jdurban/5710/Canu_assembly/correction/0-mercounts/meryl.5711_1.out
```
Moreover, after being in touch with my system administrator I called the algortihm just with a --mem=64GB option that was algo used as a maxMemory=64G option on canu options.

Any advice will be really appreciated

[canu_desktop.txt](https://github.com/marbl/canu/files/830852/canu_desktop.txt)

**Comment by jordur** [comment]
More information using:
```
scontrol show jobid -dd 5735_1
```
[logfile.txt](https://github.com/marbl/canu/files/830921/logfile.txt)

Regards

**Comment by skoren** [comment]
There's no different in meryl running on a local node or on the grid node in the code, it's just using shared memory on a single machine. 

Are you sure it's getting CPU on the system. Are the CPUs on the local node and the SLURM system comparable? Are the disks/filesystems comparable? This issue is most likely related to your SLURM configuration not Canu itself.

**Comment by jordur** [comment]
Sure! I will look deeper into the SLURM configuration.
Thank you very much

**Comment by jordur** [comment]
Hi @skoren . Is it possible that same sample gives rise to different results if it is assembled on a local computer than on a cluster grid? I mean, finally I have been able to run canu on a grid environment (really grateful to my system administrator). However even the .html files are pretty similar between the local results and the results obtained from the cluster, I obtained a unitig.fasta sequence on the local machine that actually does not exist in the cluster results. How can I compare if the process was successful in both cases? That is: is there a kind of log file in order to compare both processes? 
Thank you.
PS In order to run the script in the SLURM environment I had to define a new variable on the scratch-global rather than $SLURMTMP

**Comment by skoren** [comment]
No the two runs should be the same. If a file is missing in one it probably means the run did not complete. All the logs from the SLURM run are in canu-scripts/canu.\*.out. The last one should have something like:
```
-- Read layouts saved:
--   Contigs       -> 'asm.contigs.layout'.
--   Unitigs       -> 'asm.unitigs.layout'.
--
-- Graphs saved:
--   Contigs       -> 'asm.contigs.gfa'.
--   Unitigs       -> 'asm.unitigs.gfa'.
--
-- Bye.
-- Finished stage 'outputSequence', reset canuIteration.
```

Indicating it is done, if you don't have that, check the last output file for an error.

What do you mean SLURMTMP? Canu doesn't use any temporary variable/space by default, it runs on a shared filesystem, is this something specific to your grid configuration?

**Comment by jordur** [comment]
Hi @skoren . 
SLURMTMP is a temporal variable of the SLURM configuration which content is deleted after job completion. Thus, I had to define a global variable in the canu script in order to use a scratch-global directory.
On the other hand, I finally ran the three stages (correct, trim and assemble) separately either, locally and on the grid environment.  In both cases I reached the "-- Bye." statement so I suspect that the process was successful either in a local desktop computer and in the grid environment. However, in a desktop computer I got an unitig sequence which was not found in the grid environment . According to correction.html and trimming.html files , those processes were preformed in a similar way in both cases. However it seemed that the assemble process was slightly different. 
Moreover, my system administrator suggested different results due to CPU accuracy.
Please, let me know if more information is needed.
Regards,
[canu_comparison.tar.gz](https://github.com/marbl/canu/files/838125/canu_comparison.tar.gz)

**Comment by skoren** [comment]
The logs you posted (in the HTML) look the same but the text outputs don't match the HTML reports.  Can you share either the reads or the full run directories (I'm assuming they're small given the number of reads) to see where the difference is introduced?

**Comment by jordur** [comment]
Sure! Here they are. I attached both reads and run directories.
Glad if this could be helpful.
[grid_data.tar.gz](https://github.com/marbl/canu/files/840770/grid_data.tar.gz)

Thank you very much!

**Comment by skoren** [comment]
Your grid and desktop runs were using a different version of Canu, the grid logs report:
```
-- Canu v1.4 (+126 commits) r8121 35a6573af22a9388f357fc392960fe92d95b1665.
-- Detected Java(TM) Runtime Environment '1.8.0_102' (from 'java').
-- Detected gnuplot version '4.6 patchlevel 2' (from 'gnuplot') and image format 'png'.
-- Detected 8 CPUs and 24 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /usr/bin/sinfo.
-- Detected Slurm with 'MaxArraySize' limited to 1000 jobs.
```
and the desktop log reports:
```
-- Canu v1.4 (+62 commits) r8057 fb27dc42fa749cc6c4245bc6ec7162f2c7760612.
-- Detected Java(TM) Runtime Environment '1.8.0_65' (from 'java').
-- Detected gnuplot version '5.0 patchlevel 3' (from 'gnuplot') and image format 'png'.
-- Detected 8 CPUs and 16 gigabytes of memory.
-- No grid engine detected, grid disabled.
```

The grid is the newer run so I think that one is correct. The reason you don't get contigs is because you have a single read spanning the majority of your genome (see FAQ: http://canu.readthedocs.io/en/latest/faq.html#my-asm-contigs-fasta-is-empty-why). Adding the option from there: ```contigFilter="2 1000 1.0 1.0 2"```, I get a single 9kb contig. I confirmed I got the same result on a single machine as the grid.

**Comment by jordur** [comment]
Oh! Sorry for the inconvenience. I thought that both were v1.4. I did not realize about the number of commits. 
Thank you so much for your help!
