### ISSUE TITLE
meryl failed: failed to generate mer counts

### ISSUE THREAD

**Issue by indapa** [marbl/canu#401]
Hi Canu Team,

I've seen this error in some of the previous closed issues. I'm wondering if need to limit merylMemory

I have very high coverage for a modest size genome (192kb). I am running canu v1.4:

`
/home/indapa/software/canu-1.4/Linux-amd64/bin/canu  useGrid=false -p result_auto -d cop-auto genomeSize=192000 -pacbio-raw /home/indapa/filtered_subreads.fastq.gz  corOutCoverage=1000
`

 The error I got is 

meryl failed

canu failed with failed to generate mer counts. Made 2 attempts, jobs still failed

When I look at the meryl.out file:

```
Merge results.

bitPackedFile::bitPackedFile()-- '/home/indapa/cop-auto/correction/0-mercounts/xxx_cop.ms16.WORKING.batch1.mcdat' failed to write the header: Bad file descriptor
Can fit 7774841512 mers into table with prefix of 26 bits, using 6553.000MB (0.000MB for positions)
```

I don't understand the error, it seems that the program failed to write a file properly. Has anyone seen this error before?

**Comment by skoren** [comment]
It seems meryl is running of of space to count your k-mers, how deep coverage do you have? You can try increasing the meryl memory explicitly (```merylMemory=64```)

**Comment by indapa** [comment]
My genome is small, so coverage is ~1000x. I will try the merylMemory option.
