### ISSUE TITLE
Environment forwarding on cluster.

### ISSUE THREAD

**Issue by yeban** [marbl/canu#402]
Is there a way to tell Canu to automatically use, for example, the Java version loaded on the node the job was queued from for the jobs it runs? The default Java on our cluster is 1.6. Java 1.8 required by Canu is loaded automatically when the module definition for Canu is loaded (`module load canu`). This loads the right Java on the node Canu queues its jobs from. However, the queued jobs fail because the same Java version was not loaded on the nodes on which jobs submitted by Canu were eventually run on by the grid system (SGE in our case).

We are resorting to editing the scripts generated by Canu to load the right Java before Canu's commands are run. Alternatively, for quick tests `useGrid=false` is a work around. Best would be if Canu could automatically use the path to Java from the node it was queued on. I checked the documentation but didn't find a way to do it, but maybe I just missed something?

**Comment by skoren** [comment]
You can set an explicit path for java using the ```java``` option to canu. You can also set ```-V``` in gridOptions to maintain environment from the submit node on the compute nodes which will keep the same modules loaded.

**Comment by yeban** [comment]
Sweet! It works. Thanks!
