### ISSUE TITLE
Failed to submit batch jobs at correction overlapper store building stage

### ISSUE THREAD

**Issue by aviantask** [marbl/canu#404]
Here is the command I'm using to run Canu on a PBS/Torque HPC --- 
`/software/canu/Linux-amd64/bin/canu -p asm -d s2drd_canu1.4 genomeSize=780m corMinCoverage=0 correctedErrorRate=0.105 -pacbio-raw PacBio_seqFiles/S2Drd_065.AllInOne.fastq.gz saveReadCorrections=true ovsMemory=16 gridOptions="-l walltime=300:00:00 -q cegs" >canu_s2drd.log 2>&1`

And here is the error log --

```-- BEGIN CORRECTION
--
--
-- Running jobs.  First attempt out of 2.
--
================================================================================
Please panic.  canu failed, and it shouldn't have.

Stack trace:

 at ~/software/canu/Linux-amd64/bin/lib/canu/Execution.pm line 1475.
	canu::Execution::caFailure("Failed to submit batch jobs", undef) called at ~/software/canu/Linux-amd64/bin/lib/canu/Execution.pm line 1094
	canu::Execution::submitOrRunParallelJob("asm", "ovS", "correction/asm.ovlStore.BUILDING", "scripts/2-sort", 1, 2, 3, 4, 5, ...) called at ~/software/canu/Linux-amd64/bin/lib/canu/OverlapStore.pm line 550
	canu::OverlapStore::overlapStoreSorterCheck("correction", "asm", "cor") called at ~/software/canu/Linux-amd64/bin/lib/canu/OverlapStore.pm line 576
	canu::OverlapStore::createOverlapStoreParallel("correction", "asm", "cor") called at ~/software/canu/Linux-amd64/bin/lib/canu/OverlapStore.pm line 630
	canu::OverlapStore::createOverlapStore("asm", "cor", "parallel") called at ~/software/canu/Linux-amd64/bin/canu line 490
	main::overlap("asm", "cor") called at ~/software/canu/Linux-amd64/bin/canu line 516


canu failed with 'Failed to submit batch jobs'.```

Kindly suggest how to get rid of this error. Many thanks!

**Comment by brianwalenz** [comment]
Darn, we're not logging the error.  Look in 'correction/asm.ovlStore.BUILDING' or in the 'scripts' directory in there for a *.jobSubmit.out file.  I think it'll be 2-sort.jobSubmit.out, but check all of them.

**Comment by aviantask** [comment]
Ahh ok, found it.. this is same error as posted by me before --  issue#73 
 ```Maximum number of jobs already in queue for user MSG=total number of current user's jobs exceeds the queue limit```

However the -t option to limit the number of jobs is not working now it seems

**Comment by brianwalenz** [comment]
This will be hard to fix.  It's not the number of running jobs (which I'm guessing -t limits) but the number of jobs queued.

A workaround is to manually submit the jobs in batches, then restart canu.  I _think_ this is the only spot that will suffer from this problem.

On your next assembly, you can try increasing ovsMemory, which will reduce the number of jobs here.  You can't do it now without recomputing the previous ("bucketizing") step.

Do you know how to query PBS for this limit?  I can possibly put in a check to halt the assembly before that bucketizing step.

**Comment by sstef1** [comment]
Hi everybody,

I've been trying to run Canu v.1.4 on a SGE cluster and we 'Failed to submit batch jobs'  (this using the E.coli nanopore dataset provided)

Here are the commands used: 
-bash-4.1$ canu -correct \
> -p ecoli -d canu_test_SGE \
> genomeSize=4.8m \
> java=/share/ClusterShare/software/contrib/gi/java/jdk1.8.0_25/bin/java \
> -nanopore-raw oxford.fasta \
> gridEngineMemoryOption="-l mem_free=MEMORY" \
> gridEngineThreadsOption="-pe smp THREADS" 

We have also tried using this other commands in combination with the ones above, but the error is the same regardless of the commands:
useGrid=true gridEngine=“SGE"
gridOptions="-l mem_requested=6G,h_vmem=6G -V -S /bin/bash" stageDirectory="/scratch_local/\$JOB_ID-\$SGE_TASK_ID" gridEngineStageOption="100G" batMemory=56G

Here is the out log: 

Canu.out
-- Canu v1.4 (+125 commits) r8120 79f3bbdabf3f668ffe902fa28c5a2dc6fa35e9bd.
-- Detected Java(TM) Runtime Environment '1.8.0_25' (from '/share/ClusterShare/software/contrib/gi/java/jdk1.8.0_25/bin/java').
-- Detected gnuplot version '4.2 patchlevel 6 ' (from 'gnuplot') and image format 'png'.
-- Detected 64 CPUs and 505 gigabytes of memory.
-- Detected Sun Grid Engine in '/opt/gridengine/default'.
-- User supplied Grid Engine environment '-pe smp THREADS'.
-- User supplied Grid Engine consumable '-l mem_free=MEMORY'.
--
-- WARNING:
-- WARNING:  Queue 'all.q' has start mode set to 'posix_behavior' and shell set to '/bin/csh'.
-- WARNING:  Queue 'short.q' has start mode set to 'posix_behavior' and shell set to '/bin/csh'.
-- WARNING:  Queue 'long.q' has start mode set to 'posix_behavior' and shell set to '/bin/csh'.
-- WARNING:
-- WARNING:  Some queues in your configuration will fail to start jobs correctly.
-- WARNING:  Jobs will be submitted with option:
-- WARNING:    gridOptions=-S /bin/sh
-- WARNING:
-- WARNING:  If jobs fail to start, modify the above option to use a valid shell
-- WARNING:  and supply it directly to canu.
-- WARNING:
-- 
-- Found   7 hosts with  28 cores and  504 GB memory under Sun Grid Engine control.
-- Found   5 hosts with  64 cores and  504 GB memory under Sun Grid Engine control.
--
-- Run under grid control using    8 GB and   4 CPUs for stage 'meryl'.
-- Run under grid control using    6 GB and   4 CPUs for stage 'mhap (cor)'.
-- Run under grid control using    8 GB and   4 CPUs for stage 'overlapper (obt)'.
-- Run under grid control using    8 GB and   4 CPUs for stage 'overlapper (utg)'.
-- Run under grid control using   15 GB and   2 CPUs for stage 'falcon_sense'.
-- Run under grid control using    4 GB and   1 CPU  for stage 'ovStore bucketizer'.
-- Run under grid control using    8 GB and   1 CPU  for stage 'ovStore sorting'.
-- Run under grid control using    2 GB and   4 CPUs for stage 'read error detection'.
-- Run under grid control using    1 GB and   1 CPU  for stage 'overlap error adjustment'.
-- Run under grid control using   16 GB and   4 CPUs for stage 'bogart'.
-- Run under grid control using   31 GB and   4 CPUs for stage 'consensus'.
--
-- Generating assembly 'ecoli' in '/share/ScratchGeneral/sanpin/canu_test_SGE'
--
-- Parameters:
--
--  genomeSize        4800000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.1440 ( 14.40%)
--    obtOvlErrorRate 0.1440 ( 14.40%)
--    utgOvlErrorRate 0.1440 ( 14.40%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1440 ( 14.40%)
--    utgErrorRate    0.1440 ( 14.40%)
--    cnsErrorRate    0.1440 ( 14.40%)
--
--
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Wed Mar 15 17:24:56 2017 with 16221.208 GB free disk space

    cd correction
    /share/ClusterShare/software/contrib/marsmi/nanopore/canu/Linux-amd64/bin/gatekeeperCreate \
      -minlength 1000 \
      -o ./ecoli.gkpStore.BUILDING \
      ./ecoli.gkpStore.gkp \
    > ./ecoli.gkpStore.BUILDING.err 2>&1

-- Finished on Wed Mar 15 17:25:00 2017 (4 seconds) with 16221.208 GB free disk space
----------------------------------------
--
-- In gatekeeper store 'correction/ecoli.gkpStore':
--   Found 20365 reads.
--   Found 140042151 bases (29.17 times coverage).
--
--   Read length histogram (one '*' equals 41.48 reads):
--        0    999      0 
--     1000   1999    706 *****************
--     2000   2999   1682 ****************************************
--     3000   3999   1624 ***************************************
--     4000   4999   1543 *************************************
--     5000   5999   1905 *********************************************
--     6000   6999   2691 ****************************************************************
--     7000   7999   2904 **********************************************************************
--     8000   8999   2609 **************************************************************
--     9000   9999   1946 **********************************************
--    10000  10999   1280 ******************************
--    11000  11999    733 *****************
--    12000  12999    397 *********
--    13000  13999    181 ****
--    14000  14999    109 **
--    15000  15999     38 
--    16000  16999      9 
--    17000  17999      4 
--    18000  18999      2 
--    19000  19999      0 
--    20000  20999      0 
--    21000  21999      0 
--    22000  22999      1 
--    23000  23999      0 
--    24000  24999      0 
--    25000  25999      1 
-- Finished stage 'cor-gatekeeper', reset canuIteration.
-- Finished stage 'merylConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
--
================================================================================
Please panic.  canu failed, and it shouldn't have.

Stack trace:

 at /share/ClusterShare/software/contrib/marsmi/nanopore/canu/Linux-amd64/bin/lib/canu/Execution.pm line 1475
canu::Execution::caFailure('Failed to submit batch jobs', undef) called at /share/ClusterShare/software/contrib/marsmi/nanopore/canu/Linux-amd64/bin/lib/canu/Execution.pm line 1094
canu::Execution::submitOrRunParallelJob('ecoli', 'meryl', 'correction/0-mercounts', 'meryl', 1) called at /share/ClusterShare/software/contrib/marsmi/nanopore/canu/Linux-amd64/bin/lib/canu/Meryl.pm line 405
canu::Meryl::merylCheck('ecoli', 'cor') called at /share/ClusterShare/software/contrib/marsmi/nanopore/canu/Linux-amd64/bin/canu line 513

**Comment by skoren** [comment]
You're actually running a post 1.4 unreleased version (+125 commits), the releases correspond to +0 commits.

What's the output in ``sanpin/canu_test_SGE/correction/0-mercounts/meryl.jobSubmit.out``` (or similar)?

**Comment by sstef1** [comment]
Hi Skoren,

Thanks for looking into this... It turns out that the meryl.jobSubmit.out shows the following:
Unable to run job: denied: host "omega-1-4.local" is no submit host.
Exiting.

Should we revert to which version instead? We tested at one point Canu v.1.3 and we had the same issue.

**Comment by skoren** [comment]
The issue is your compute nodes aren't allowed to submit jobs, this mean you won't be able to use your grid with Canu (see issue #137). Is it possible for your configuration to allow compute hosts to submit jobs as well? Alternatively, you could run on a single node or with ```useGrid=remote``` on your head node, which would output a command to submit which you'd submit manually, wait for completion, and re-run the canu command which would continue.

**Comment by sstef1** [comment]
Thanks Skoren... I managed to run in using the useGrid=remote mode followed by manual submission of each step for the correct sequences module.  I'll try to work out if we can fix the batch submission with the system administrator.  We'll let you know if we run into trouble again!
