### ISSUE TITLE
Falcon_sense hangs with N (non ACGT characters)

### ISSUE THREAD

**Issue by skoren** [marbl/canu#41]
Running a job where the input data has Ns in the sequence causes falcon_sense to hang on that input sequence. Canu needs to filter out non ACGT bases before passing to falcon_sense.

**Comment by brianwalenz** [comment]
That's a problem - canu replaces non-ACGT with N during loading.  Any chance falcon_sense can be fixed?

**Comment by mschatz** [comment]
Replace non-ACGT with 'A' :)

**Comment by skoren** [comment]
I'm not sure where the issue in falcon_sense is. I think it might only be an issue if the template read has the N not the mapping reads.

**Comment by pb-jchin** [comment]
FALCON-sense is not test with non-"A/C/G/T" characters. (Non lower cases either.) However, it use `char` to store the bases. I would have to check the code to see if N is just treated like 5th base.

**Comment by skoren** [comment]
Jason, if you want to see if it is a simple fix, I attached the example layout that is causing the issue. If you did a sed s/N//g it will fix the file and run without issue
[bug.lay.gz](https://github.com/marbl/canu/files/119741/bug.lay.gz)

**Comment by skoren** [comment]
I found this bug in the C code becomes a SEGFAULT so it's much easier to track down. Adding default to the case statements for handling bases in falcon.c and kmer_lookup.c fixed it, specifically:

```
@@ -166,6 +166,9 @@ void add_sequence ( seq_coor_t start,
                 break;
             case 'T':
                 sa[ start + i ] = 3;
+                break;
+            default:
+                sa[ start + i ] = 0;
         }
     }
     kmer_bv = get_kmer_bitvector( sa + start, K);
@@ -241,6 +244,9 @@ kmer_match * find_kmer_pos_for_seq( const char * seq, seq_coor_t seq_len, uint32
                 break;
             case 'T':
                 sa[ i ] = 3;
+                break;
+             default:
+                sa[ i ] = 0;
         }
     }
```

and 

```
@@ -392,6 +392,7 @@ consensus_data * get_cns_from_align_tags( align_tags_t ** tag_seqs,
                 case 'G': base = 2; break;
                 case 'T': base = 3; break;
                 case '-': base = 4; break;
+                default : base = 4; break;
             }
             // Note: On bad input, base may be -1.
             update_col( &(msa_array[t_pos]->delta[delta].base[base]), c_tag->p_t_pos, c_tag->p_delta, c_tag->p_q_base);
@@ -452,7 +453,7 @@ consensus_data * get_cns_from_align_tags( align_tags_t ** tag_seqs,
                                 case 'G': pkk = 2; break;
                                 case 'T': pkk = 3; break;
                                 case '-': pkk = 4; break;
-                                default: pkk = 4;
+                                default : pkk = 4; break;
                             }
```

While looking through the code I also found the following two things I had a question of:

```
437                     aln_col = msa_array[i]->delta[j].base + kk;
438                     if (aln_col->count >= 0) {
439                         best_score = -1;
440                         best_i = -1;
441                         best_j = -1;
442                         best_b = -1;
```
but aln_col->count is defined as a uint so it can't be < 0. Is this intended to check something else or just an extra if statement?

```
        if ( km_ptr -> query_pos[i] < q_min) {
            q_min =  km_ptr->query_pos[i];
        }
        if ( km_ptr -> query_pos[i] > q_max) {
            q_max =  km_ptr->query_pos[i];
        }
        if ( km_ptr -> target_pos[i] < t_min) {
            t_min =  km_ptr->target_pos[i];
        }
        if ( km_ptr -> query_pos[i] > t_max) {
            t_max =  km_ptr->target_pos[i];
        }
```
I think last if should be km_ptr -> target_pos[i] > t_max?
