### ISSUE TITLE
Parameter minOverlapLength and minReadLength

### ISSUE THREAD

**Issue by ptranvan** [marbl/canu#410]
Hi,

I am trying to play with parameters. 

1) In order to save time, I would like to know if the parameter minOverlapLength is only applied at the assembly step ? (not at the correction and the trimming steps)

2) same question with the minReadLength ?

**Comment by skoren** [comment]
Min overlap length will affect all stages (correction, trimming and assembly).

**Comment by brianwalenz** [comment]
Oddly, our docs had no mention of these parameters, except in the FAQ.
