### ISSUE TITLE
problems with "+" in assembly-prefix

### ISSUE THREAD

**Issue by dominik-handler** [marbl/canu#412]
Hi,

I named my recent run "ONT+PB" and got the following error in the trimming step in ONT+PB.gkpStore.err:
`Starting file './ONT+PB.gkpStore.gkp'.
ERROR:  option 'ONT+PB.correctedReads.fasta.gz' not recognized, and not a file of reads.`

The file ONT+PB.correctedReads.fasta.gz was generated by the correction-step and is present at the default location.

I now restarted the canu run named as ONT_PB and used the ONT+PB.correctedReads.fasta.gz as input corrected read file. This now works and the pipeline continues.

Does canu have a problem with the "+" in the assembly-prefix?

Dominik

**Comment by brianwalenz** [comment]
Nope, '+' is certainly allowed.  Which version of canu?  I think you hit an unstable version.  Can you run lambda, either with or without a '+' in the name?  I expect both will fail.

Lambda reads: http://www.cbcb.umd.edu/software/PBcR/data/sampleData.tar.gz

**Comment by dominik-handler** [comment]
Ok, I will test it.
Another point could be that I supplied raw-nanopore and raw-pacbio reads. With the change in the assembly-prefix I canged to nanopore-corrected and supplied the previously generated file. 
Potentially this transition from supplying 2 raw-input files to the corrected.fasta file has some problem.

I am using version:
Canu v1.4 (+141 commits) r8136 15318d8b9935f36a9cffa6026f1a6102535e0d01.

**Comment by dominik-handler** [comment]
hm, it seems the "+" causes problems. I ran the two following canu-runs on you test-data (still using Canu v1.4 (+141 commits) r8136 15318d8b9935f36a9cffa6026f1a6102535e0d01. )

`canu -p canu-test+PB -d ~/canu-test/ -pacbio-raw ~/sampleData/pacbio.filtered_subreads.fasta genomeSize=50000 gridEngineMemoryOption="-l mem_total=MEMORY" minReadLength=500 stopOnReadQuality=false

 canu -p canu-test_PB -d ~/canu-test2/ -pacbio-raw ~/sampleData/pacbio.filtered_subreads.fasta genomeSize=50000 gridEngineMemoryOption="-l mem_total=MEMORY" minReadLength=500 stopOnReadQuality=false
`
Both runs finished the correction step properly and the corrected.fasta files are identically. The run named "canu-test+PB" then runs again into the following error, whereas the other one progresses successfully into trimming.
`canu.out:
ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

canu-test+PB.gkpStore.err:
Starting file './canu-test+PB.gkpStore.gkp'.
ERROR:  option 'canu-test+PB.correctedReads.fasta.gz' not recognized, and not a file of reads.
`

**Comment by brianwalenz** [comment]
I think I found it, but I don't know why it's working for me and not you.

At line 184 in src/pipelines/canu/Gatekeeper.pm, change
```
        if (($iii =~ m/-pacbio-corrected\0($asm.correctedReads.*)/) ||
            ($iii =~ m/-pacbio-corrected\0($asm.trimmedReads.*)/)) {
```
to
```
        if (($iii =~ m/-pacbio-corrected\0(.*.correctedReads.*)/) ||
            ($iii =~ m/-pacbio-corrected\0(.*.trimmedReads.*)/)) {
```
(Replacing "$asm" by ".*")

**Comment by brianwalenz** [comment]
Thanks for finding this and the testing.  It should be fixed now.
