### ISSUE TITLE
suggestCircular flag is inconsistent

### ISSUE THREAD

**Issue by brianwalenz** [marbl/canu#415]
suggestCircular is set, supposedly correctly, in the GFA output, but not in FASTA output.

**Comment by brianwalenz** [comment]
Now that we have GFA alignments, we can further trim back the sequence to remove the redundant (overlapping) sequence.

**Comment by skoren** [comment]
We should also identify circularized things in the asm.unassembled.fasta and not demote them to avoid filtering short plasmids.
