### ISSUE TITLE
GFA output has incorrect contig ordering for links

### ISSUE THREAD

**Issue by gringer** [marbl/canu#416]
The [GFA1 specification](https://github.com/thegenemyers/GFA-spec/blob/master/GFA-spec.md) mentions the following:

> A link from A to B means that the end of A overlaps with the start of B. If either is marked with -, we replace the sequence of the segment with its reverse complement, whereas a + indicates the segment sequence is used as-is.

It is not absolutely specific whether A or B represents the first column of a link (L) line, but Bandage (at least) assumes that the first column represents sequence A, which is inconsistent with what Canu 1.4 produces. Here's an example:

```
S       tig00000041     *       LN:i:488590
S       tig00018515     *       LN:i:662821
L       tig00018515     +       tig00000041     +       10806M  cv:A:F

```

The GFA link line suggests that the end of tig00018515 should join to the start of tig00000041. Compare this to the LAST interpretation [`lastal -l 100 shouldBeJoined.fasta shouldBeJoined.fasta | last-dotplot - LAST_positive_join.png`], where it should actually be the end of tig00000041 joining to the start of tig00018515:

![last_positive_join](https://cloud.githubusercontent.com/assets/856314/24174010/60fc180e-0ef3-11e7-94c9-3211f6f5bf8f.png)

When the GFA information for these contigs is taken as gospel and used to merge contigs using Bandage, the result can be quite an odd construct:

![large_almost_circular](https://cloud.githubusercontent.com/assets/856314/24172652/d8539cc0-0eed-11e7-9a6d-a2f1de162472.png)

When the link columns for the GFA output are flipped, and these contigs then merged using Bandage, the result of the merge for this example was a single linear sequence with no self matching.

Another example is the contig pair that I reported in (another issue)[https://github.com/marbl/canu/issues/409]. For some reason I didn't include the GFA lines in that issue, but here they are:

```
S       tig00003015     *       LN:i:16586
S       tig00019494     *       LN:i:20821
L       tig00003015     +       tig00019494     -       5458M   cv:A:F
L       tig00019494     +       tig00003015     -       5434M   cv:A:F

```
According to the GFA, the end of tig00003015 should match the start of the reverse complement of tig00019494, whereas LAST suggests that it is actually the _start_ of tig00003015 that matches:

![last_shouldbejoined](https://cloud.githubusercontent.com/assets/856314/24173779/613d9208-0ef2-11e7-8b70-55de6e59dab7.png)

The code for outputting GFA information in Canu appears to be in `bogart/AS_BAT_TigGraph.C` (lines 298-329).

**Comment by aphillippy** [comment]
Hi @gringer,
Yup, it looks like we have the GFA1 columns swapped relative to what Bandage expects. For your last example, assuming the origin of your dotplot is the upper left corner, the link should be:

L       tig00019494     -       tig00003015     +

Indicating a relationship like so:
tig00019494 <----------|
tig00003015          |------------->

The easy fix for now is to swap all link columns. Canu v1.5 is imminent (next week?) and will include this fix. GFA2 support is planned for Canu v1.6, which doesn't suffer from the ambiguity of the GFA1 spec. In GFA2, each edge is explicitly defined via coordinates on the segments and so the ordering of the columns doesn't matter. This is more the notation we are accustomed to.

Thanks very much for catching this bug,
-Adam

**Comment by brianwalenz** [comment]
This has been fixed.  Based on issue #428, Canu v1.5 will probably be computing alignments for the links reported.
