### ISSUE TITLE
Building from .tar.gz release source gives NULL version

### ISSUE THREAD

**Issue by tseemann** [marbl/canu#419]
```
%  canu --version
Canu v0.0 (+0 commits) r0 unknown-hash-tag-no-repository-available
```

This affects Brew packages, where we use the release tarball. 

But the release tarball is not a git repo, so `canu_version_update.pl` won't work.

However, Brew auto-parses the VERSION from the download name, so `https://github.com/marbl/canu/archive/v1.4.tar.gz` will give me `version==1.4` in the Brew script which i can use at compile time.

I guess one possibility is to create a `canu_version.H` file within the package script, but I think it would be better if you were able to create it somehow in a VERSION file, and use that as a fallback when you can't find a `.git` folder.

We build it like this:
```
system "make", "-C", "src"
```
I guess we could override yours with `make -C src -DCANU_VERSION_MAJOR=XX` etc ?

**Comment by brianwalenz** [comment]
We've hit this recently too (in other bug reports).  I plan to fix it in the next version...somehow.  Thanks for the reminder.

**Comment by brianwalenz** [comment]
I just published v1.5.  Testing claimed you'll get a useful version number now.

**Comment by tseemann** [comment]
```
% canu --version
Canu release v1.5
```

Seems to work!   

Would prefer `canu 1.5` though, as that is a semi-standard for Unix tools.

**Comment by brianwalenz** [comment]
Oh well, win some, lose some.  :-/

**Comment by tseemann** [comment]
The battle continues! https://github.com/marbl/canu/issues/481
