### ISSUE TITLE
ERROR: Failed with signal 127

### ISSUE THREAD

**Issue by kkrizanovic** [marbl/canu#42]
I'm trying to run canu on my test dataset. On one server, it run without problem. However, on another one, I get an error (on the same dataset). Here is the last part of the output:

    -- BEGIN CORRECTION
    --
    --
    -- GATEKEEPER (correction)
    --
    ----------------------------------------
    -- Starting command on Mon Feb  8 15:25:26 2016 with 222.9 GB free disk space
    
        /home/kresimir/src/canu/Linux-amd64/bin/gatekeeperCreate \
          -minlength 1000 \
          -o /home/kresimir/benchmark/results/canu/dataset5/correction/d5.gkpStore.BUILDING \
          /home/kresimir/benchmark/results/canu/dataset5/correction/d5.gkpStore.gkp \
        > /home/kresimir/benchmark/results/canu/dataset5/correction/d5.gkpStore.err 2>&1
    
    -- Finished on Mon Feb  8 15:25:30 2016 (4 seconds) with 222.8 GB free disk space
    ----------------------------------------
    runCommandSilently()
    
        gnuplot < /home/kresimir/benchmark/results/canu/dataset5/correction/d5.gkpStore/readlengths.gp \
        > /dev/null 2>&1
    
    ERROR: Failed with signal 127

I'm guessing that I'm missing some required program, but I can't figure out what.

**Comment by skoren** [comment]
The error is coming from gnuplot. What happens on that machine if you run:

```
gnuplot < /home/kresimir/benchmark/results/canu/dataset5/correction/d5.gkpStore/readlengths.gp
```

There was a recent change to Canu (after release 1.0) that made all failed commands halt the pipeline. We plan to update it to allow some non-critical commands (like the above) to fail and continue. In the meantime, fixing gnuplot should fix your error.

**Comment by kkrizanovic** [comment]
Thanks. I could have probably figured that out myself if I paid more attention. I don't have gnuplot on the second server, gonna install it and try again.

**Comment by brianwalenz** [comment]
Always good to get the little things fixed.  4d48b8f6fb85b6022f27220118ce803a056c3a29 complains gnuplot isn't available and continues the assembly.
