### ISSUE TITLE
How about the Sequel system?

### ISSUE THREAD

**Issue by RobertoRun** [marbl/canu#420]
Is canu be used for the data produced by Sequel system?

**Comment by skoren** [comment]
Yes, it's essentially the same as RSII data. The early data had a slightly lower quality so it required one parameter change (see FAQ: http://canu.readthedocs.io/en/latest/faq.html#what-parameters-should-i-use-for-my-genome-sequencing-type) but that may no longer be needed.

**Comment by RobertoRun** [comment]
Thanks! Actually, i have run the following command successfully, but the assembly contigs is only few Mb. Most of the reads are filtered after correction step. My data is produced by Sequel! Do you have any suggestion? 

Thanks again!

canu -d canu -p Gl genomeSize=1300m maxMemory=512g maxThreads=24 errorRate=0.013 corMhapSensitivity=normal minReadLength=2000 minOverlapLength=800 corOutCoverage
=35 
merylMemory=512g merylThreads=24 ovsMemory=256g 
gridOptionsExecutive="--mem-per-cpu=10g --time=2:00:00"
gridOptionsCORMHAP="--mem-per-cpu=5g" 
gridOptionsCORMHAP="--time=1:00:00" 
gridOptionsOBTMHAP="--mem-per-cpu=5g --time=1:00:00" 
gridOptionsUTGMHAP="--mem-per-cpu=5g --time=1:00:00" 
gridOptionsCOROVL="--mem-per-cpu=5g --time=12:00:00" 
gridOptionsOBTOVL="--mem-per-cpu=5g --time=12:00:00" 
gridOptionsUTGOVL="--mem-per-cpu=5g --time=12:00:00" 
gridOptionsRED="--mem-per-cpu=4g --time=1:00:00" 
gridOptionsOEA="--mem-per-cpu=4g --time=12:00:00" 
-pacbio-raw ./Gl.subreads.fa.gz

**Comment by skoren** [comment]
Any reason you are specifying minReadLength/minOverlap/corOutCoverage explicitly? The default corOutCoverage is higher (40x) which would give more data for assembly. How much input coverage do you have (what do the histograms in the first step and post-correction look like)?

**Comment by RobertoRun** [comment]
I did not modified the parameters of minReadLength/minOverlap/corOutCoverage explicitly. The coverage is only 47X. So should i decrease the default coverage?

**Comment by RobertoRun** [comment]
minReadLength=2000 minOverlapLength=800 corOutCoverage=35

Actually, the coverage is about 47x!

**Comment by skoren** [comment]
Your command includes ```minReadLength=2000 minOverlapLength=800 corOutCoverage
=35``` which modifies these from the default. What is the histogram of lengths going into correction (in canu.01.out), or if you can just share all ```canu-scripts/canu.*.out``` I can check those myself.

**Comment by RobertoRun** [comment]
Thank you so much! So pity, i have deleted the old failure file! I running again now! After it's finished, i will share all the canu-scripts/canu.*.out to you and ask your help!

**Comment by RobertoRun** [comment]
All the canu-scripts/canu.*.out  are attached as a zip file. The following is the correction summary. There are so many reads were filtered!

=====================

CORRECTION INPUTS:
-----------------
4358333 (input reads)
46914012376 (input bases)

CORRECTION OUTPUTS:
-----------------
4285149 (reads that failed to generate any corrected bases)
77780 (corrected read pieces)
626758819 (corrected bases)

PIECES PER READ:
---------------
0 pieces: 4285149
1 pieces: 68767
2 pieces: 4243
3 pieces: 169
4 pieces: 5

============================
I converted bam file to fasta file with the following command! 

samtools view $bam | awk '{OFS="\t"; print ">"$1"\n"$10}' - >$newfile

===========================

[canu.scripts.log.tat.gz](https://github.com/marbl/canu/files/873023/canu.scripts.log.tat.gz)

**Comment by skoren** [comment]
Your logs are missing the initial input distribution but it does seem that the majority of your reads have no overlaps during correction. Have you done any validation on the raw data? I would suggest getting the latest Canu from the repository (rather than the 1.4 release) and trying ```corMinCoverage=0 corMhapSensitivity=high``` to see how your corrected and trimmed reads look then.

If you are able to share your reads with us, I can try running some tests locally.

**Comment by RobertoRun** [comment]
Thank you so much! I did not know why there is no overlap, the coverage is not very low. Yes, i did not assess or validate my raw data (I also doubt the quality of the raw reads), just because i don't find the perfect method or software to do it! I wish to share my reads with you, but it actually too huge! Thank you so kind help!

I will try the new version.

**Comment by RobertoRun** [comment]
Actually, the latest one do not support "covMinCoerage=0".

ERROR:  Invalid 'corOutCoverage' specified (0); must be at least 1.0

I have set to 5 to redo it!

**Comment by RobertoRun** [comment]
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0390 (  3.90%)
--    utgOvlErrorRate 0.0390 (  3.90%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0390 (  3.90%)
--    utgErrorRate    0.0390 (  3.90%)
--    cnsErrorRate    0.0390 (  3.90%)
--
-- WARNING: Obsolete 'errorRate' used, replace with 'correctedErrorRate', set to three times the value.
-- WARNING: errorRate was the expected error rate in a single corrected read; correctedErrorRate is the
-- WARNING: allowed difference in an alignment of two corrected reads.

============================================

I have set "errorRate=0.013". Do you think i should change it? What't the best arguments of errorRate for Sequel machine in the different step?

**Comment by skoren** [comment]
Setting error rate to 0.013 is fine, the default is 0.015, not much difference. 

The options ```corMinCoverage``` and ```corOutCoverage``` are not the same thing. The latest code does support ```corMinCoverage=0```. You cannot set ```corOutCoverage=0``` and setting it to 5 is way too low. So your re-run will not work. You should restart it with ```corMinCoverage=0 corMhapSensitivity=high``` which I said yesterday.

Can you also share the hist file in correction/0-mercounts? The logs you had indicate it picked an extremely high threshold for repeat supression so I'd like to see what the histogram distribution of the k-mers looks like.

**Comment by RobertoRun** [comment]
Thanks! I have rerun with latest canu of "corMinCoverage=2 corMhapSensitivity=high corOutCoverage=30".

The attached is the text file and histogram distribution!
[Gl.ms16.histogram.txt](https://github.com/marbl/canu/files/876172/Gl.ms16.histogram.txt)

![gl ms16 histogram lg](https://cloud.githubusercontent.com/assets/286410/24413319/52fadc00-1398-11e7-9b0e-876e44a6ae95.png)

================

Another help, the latest goat genome is very very perfect work! It's so amazing assemble, especially the first step (PacBio assemble). I know you are co-first author. I think this awesome work should be carried out by you! Would you like to share your canu config file for this assemble? Actually, i have begin to learn how to assemble plant genome with third generation data. It's still a freshman in this field!

**Comment by skoren** [comment]
Can you run with the parameters I've listed, you are changing corOutCoverage from the default (lowering it) which isn't going to help the assembly and not setting corMinCoverage=0. I can't help diagnose the issue if you aren't following my instructions.

You don't need to share the raw data, only the fasta of the sequences is sufficient, given 35X coverage of a 1G genome, it should be small using gzip. You can upload it to our incoming ftp here:
ftp://ftp.cbcb.umd.edu/incoming/sergek
where only I can see it.

**Comment by RobertoRun** [comment]
So sorry for changing some parameters. Now, i rerun it with "corMinCoverage=0 corMhapSensitivity=high".

I uploading raw reads to your ftp now! The zip file is about 17Gb. It will spend about 1 hours to upload all the data. The genome size is about 1.35Gb. Thanks for you help!

**Comment by RobertoRun** [comment]
The file (Gl.subreads.fa.gz) was uploaded successfully.

**Comment by skoren** [comment]
After a first pass looking at the data with alternate parameters and an alternate assembler (miniasm which assembled only 11mb), I'm pretty sure there is something seriously amiss with this data. 

![screen shot 2017-03-30 at 4 13 59 pm](https://cloud.githubusercontent.com/assets/923478/24524265/e7383058-1563-11e7-8096-deb7d43901be.png)

This is a histogram of # of overlaps per read comparing a human run with about 65X coverage and your dataset. The human dataset shows a clear peak at around 60, the expected coverage. Using the same parameters, on your dataset the peak is much lower (<10x) implying either that the data is much higher error or that there is a contaminant in the sequencing (chloroplast?) which is stealing coverage from the primary genome.

I would bet that whatever you had assembled is coming from a chloroplast (this is a plant you said right?). It is possible that if the data is very noisy one of my runs will produce a larger assembly but in the meantime if you can I'd try to classify fraction of reads from organelles vs primary.

**Comment by RobertoRun** [comment]
Thank you so kind help, Skoren!

Yes, this is plant! We also doubt that most of sequence are for chloroplast or mitochondrion genome. If most of reads are from plastid genome, so it should be very very high coverage for these, and also there are many overlap for the correction, and so should be many reads will be kept after the correction step. But, little read were kept through correction step because of less overlap.

**Comment by RobertoRun** [comment]
Yes, Please help me to  classify fraction of reads from organelles vs primary.

Thanks again!

**Comment by skoren** [comment]
Is the mitochondria or chloroplast from this genome sequenced, even if not complete? You can try mapping reads to them and estimating identity and fraction of reads mapping. If it's low-identity data, you could try multiple rounds of correction (say 5) as suggested on the FAQ:
http://canu.readthedocs.io/en/latest/faq.html#what-parameters-should-i-use-for-my-reads

**Comment by RobertoRun** [comment]
1. Out of the 5,939,060 reads in Gl.fasta, 5,664,497 did not have any hits to the database and the reminder, a tiny percent, 274,563 had hits to chloroplast genomes. The fact that only a small percent is hitting the organelles is good but  it is a little bit puzzling that the rest of the reads did not have any hits.

2.Took 2,901,615 reads from preads4falcon.fasta and did similar BLAST analysis and most of the hits were to the chloroplast genomes.

3. Also took 16,296 contigs from p_ctg.fa and did the same BLAST analysis and we see similar results as in 2.

**Comment by brianwalenz** [comment]
Closing.  I don't see anything for us to do here.

**Comment by skoren** [comment]
It sounds from your comments like you also tried Falcon and also got primarily mitochondrial assembly (and I presume a much smaller than expected assembly) (based on the p_ctg.fa and preads4falcon.fasta). So that would make three assemblers (Canu, Miniasm, Falcon) which all fail to assembly much beyond the mitochondria on this dataset, I think that confirms there is something wrong with the data.

I ran an assembly following my last comment with multiple rounds of correction. I ran 4 rounds of correction with the parameters ```canu -assemble corMhapSensitivity=high corMinCoverage=0 corOutCoverage=100```, inputting the results of the previous round into the next one and assembled the final corrected reads with ```canu -pacbio-corrected asmRound4/asm.correctedReads.fasta.gz``` This gave an assembly of 1Gbp and about a 100kbp n50 so not very large but at least representing more of the genome. I think the issue here was that the reads were much higher error than is common for Sequel datasets and the only part of the data which had enough normal-quality reads was the mitochondria (due to its high coverage). It's possible more rounds of correction would further improve the asm or increasing ```obtOvlErrorrate/utgOvlErrorRate```. I'd suggesting going back and checking the median read identity against the mitochondria as I suggested if you wanted to confirm. I can also share this assembly fasta.

**Comment by fbemm** [comment]
A bit unrelated but we are having very similar troubles with other plant genomes that were sequenced on the Sequel. Overlap detection basically fails. Falcon works to some extend with greedy parameters but with sub optimal performance.

**Comment by skoren** [comment]
It sounds like the early Sequel runs have low identity reads compared to the released A. thaliana dataset. The defaults are tuned for 82+% identity. I'd suggest the multiple rounds approach which works down to 70% identity listed on the FAQ for your data as well.

**Comment by fbemm** [comment]
I wish we would be talking about early Sequel runs. It's happening also with latest chemistry (v2.0). A. thaliana works fine since v1.2. Other species don't. Effect looks Sequel-specific for us since RSII data for same species looks fine. Not sure what's going on there. Maybe nucleotide distribution skims coupled with base modification. Going to try iterative correction!

**Comment by kuinochi** [comment]
Hi, I have a naive question. We have some Sequel data now. And I found that the reads in the FASTQ generated by Sequel system has all its quality equal to "!", i.e. phred score 0. Is it normal? If it is, would this affect the assembly by canu?

**Comment by brianwalenz** [comment]
Can't comment if that's normal or not, but canu doesn't use the QV's at all.

**Comment by kuinochi** [comment]
Thanks for your reply!
I just wondering if the QV might affect the canu.
