### ISSUE TITLE
compute nodes with lsf

### ISSUE THREAD

**Issue by kevfengler227** [marbl/canu#421]
Hello,
I am trying to submit jobs to lsf cluster, but I getting the following error.

ERROR - Compute Nodes cannot be used as submission host

This behavior is not allowed on our system. Is there any way around this?

Thanks,
KF

**Comment by skoren** [comment]
You would have to either run on a single compute node or use useGrid=remote and manually submit jobs and wait for their completion (see issue #404 and #137)
