### ISSUE TITLE
what does corMaxEvidenceErate mean?

### ISSUE THREAD

**Issue by qslin** [marbl/canu#422]
In the canu manual, the explanation of corMaxEvidenceErate is the maximum error rate of overlap for correction. But I wonder how does it calculate the error rate between more than one read. Could you explain it using a case? What is the rationale that setting it as 0.15 will help the assembling of a plant genome with many repeats? Thank you!

**Comment by skoren** [comment]
The error rate is computed on a pairwise basis, using a conversion from the jaccard estimate to identity described in the Canu paper. Any overlap over this error rate will not be used for correction. The error here is approximately double the error in a single sequence (assuming random error, the overlap between two reads is approximately additive). Thus, 0.15 would be pretty low (it assumes reads are >93% identity). We've not found benefit in adjusting it except in the cases of high-AT/GC genomes. Typically the default is 0.20, unless you're running in low-coverage mode when is it 27%. Canu has downstream filtering steps which eliminate repeat overlaps from being used for correction/analysis.
