### ISSUE TITLE
What does trimReadsOverlap mean?

### ISSUE THREAD

**Issue by qslin** [marbl/canu#423]
In manual, it said: trimReadsOverlap <integer=1> Minimum overlap between evidence to make contiguous trim. 
But it confuses me that whether it means "once two overlapping reads have both of their un-overlapped region trimmed, this overlap will also be trimmed" or not? Thank you!

**Comment by skoren** [comment]
The value is the minimum support from alternate reads for a position. The default means at least one other sequence must support a read for it to remain untrimmed. Increasing it will trim more sequences but may also over-trim the reads.

The trimming step produces new sequences. Once a read is trimmed, it will be treated as a new read with a new name. The overlaps are recomputed from scratch so the old overlaps on the untrimmed data are no longer used. So if two overlapping reads are trimmed and no longer overlap, then there is no overlap to be used in the assembly step. If they still do after the trimming, the overlap is used.
