### ISSUE TITLE
GFA output has incorrect overlap CIGAR strings

### ISSUE THREAD

**Issue by gringer** [marbl/canu#428]
It seems that Canu has done the minimum necessary to stop Bandage from complaining about its overlap graphs. Unfortunately, this has resulted in GFA link lines that are not correct. Consider the example of two linked contigs that don't have a perfect overlap (and include INDELs in either or both contigs in the overlap region):

S	tig00003015	*	LN:i:16586
S	tig00019494	*	LN:i:20821
L	tig00019494	-	tig00003015	+	5458M	cv:A:F
L	tig00003015	-	tig00019494	+	5434M	cv:A:F

Because these CIGAR match strings (5448M/5434M) are different but relate to an identical link structure, it's not possible for them to both be correct, and very likely that they're both incorrect. The GFA specification states that "The length of the overlap is determined by the CIGAR string of the link. When the overlap is 0M the B segment follows directly after A. When the CIGAR string is *, the nature of the overlap is not specified."

In this case, I believe that '*' is more appropriate for these links if the correct CIGAR string cannot be determined or used (which is also supported as a valid CIGAR replacement in GFA2):

S	tig00003015	*	LN:i:16586
S	tig00019494	*	LN:i:20821
L	tig00019494	-	tig00003015	+	*	cv:A:F
L	tig00003015	-	tig00019494	+	*	cv:A:F

This has the unfortunate side effect of making Bandage complain about the GFA structure, but it's much better for that to happen than for people like me to assume that everything's peachy and we can Bandage-merge contigs without care:

![gfa_complex_links](https://cloud.githubusercontent.com/assets/856314/24425481/e2def798-1460-11e7-8176-54fea9fd0e0d.png)

**Comment by brianwalenz** [comment]
Thanks for pushing the GFA support a bit.  I'm not so happy you're finding major problems, but you seem to be just a little bit ahead of us in using it.

The challenge Canu has with GFA is that when the edges are generated we don't know consensus sequences.  The bogus CIGAR was mostly just a placeholder with the best guess at the size of the overlap.

I added a new program to Canu, `alignGFA`, that will compute an alignment for each link and emit a correct CIGAR.  It has not been integrated into the pipeline, but is simple to run.  Usage is:
```
alignGFA \
   -G unitigging/asm.gkpStore \
   -T unitigging/asm.ctgStore 2 \
   -i asm.contigs.gfa \
   -o asm.contigs.new.gfa
```
It will load all sequences into memory, and is using only one CPU.  On drosophila contigs, it runs in less than a minute.

Also on drosophila, it drops about 25% of the edges.  These appear to be mostly rDNA.  From nucmer alignments, they are mostly (a) things that really don't align or (b) things that probably do align but are a bit messy.  Here's a few examples of the horror show these are:

![plot-tig00000929 -tig00014077-](https://cloud.githubusercontent.com/assets/8249720/24444648/23cc21a8-1435-11e7-91f6-60a787684e56.png)

![plot-tig00000966--tig00001034-](https://cloud.githubusercontent.com/assets/8249720/24444725/667255c2-1435-11e7-9c77-1c313fb0bd96.png)

![plot-tig00002543--tig00002341](https://cloud.githubusercontent.com/assets/8249720/24444807/bd3a20f6-1435-11e7-9366-1a2da7324f5b.png)

**Comment by gringer** [comment]
I've encountered a lot of those crazy repetitive sequences in my Canu travels with parasite DNA.

In any case, if the overlap size is not known, it would be better to put "*' as the overlap CIGAR string, rather than an incorrect CIGAR. I'm not convinced that an approximate value is a good idea.

**Comment by brianwalenz** [comment]
Links where no alignment is found are discarded from the alignGFA output.  All the rest have actual valid (and loooong) cigar strings.

I can add the non-aligning links back, with *'s, but I suspect these are cases where canu is finding false edges based on overly permissive overlaps.

**Comment by gringer** [comment]
If you've got the actual cigar strings for the alignment, that would be much better. It'd mean I don't have to go through an intermediate LAST alignment to be able to join contigs for subsequent experimental validation of merged sequences.

**Comment by gringer** [comment]
Here's one of my horror-show links, which was identified as a unique match (i.e. these were the only two contigs that linked together) by Canu in the GFA output. The assembled contig is on the X axis, components on the Y axis. This is output from LAST, converted into a dot plot. It looks like I've managed to iron out most of the kinks in the merge code:

![out](https://cloud.githubusercontent.com/assets/856314/24632898/09783f1e-191a-11e7-97cb-e03b48997c4a.png)

Contig merge code (still a work in progress) is here:

https://github.com/gringer/bioinfscripts/blob/master/connected_components.r

I'm not quite sure why I'm doing this, but feel like putting in a summary of my merge approach:

1. Load the GFA into a graph structure
1. Identify connected clusters with >1Mb total length
1. Extract sequences for connected clusters
1. Carry out an all-vs-all mapping on cluster sequences, retain only the valid overlap matches:
  - no self matches
  - link region identity > 90%
  - matched region begins or ends at the start or end of both contigs
  - convert to direction-relative notation (as in GFA)
  - remove links that don't make sense (e.g. start of contig A linked to start of contig B, end of contig A linked to end of contig B)
1. Connect mapping results to GFA links
1. Identify GFA paths (and sub-paths) that are supported by mapping results
1. Retrieve component FASTA sequences and assemble into a larger contig (if possible)

**Comment by brianwalenz** [comment]
Thanks for complaining about the missing alignments, cheers!
