### ISSUE TITLE
error while running trimming step

### ISSUE THREAD

**Issue by ShuChen1986** [marbl/canu#429]
Dear Sir/Madam,

While runnning Canu, following error information was given and the program was paused. I followed the instruction and ovStoreBuild, -M to 100Gb, but it did not work and fed back with the same error message. 
Could you help with this issue, please? Thank you so much!

```
> -- Finished on Tue Mar 28 16:07:11 2017 (4 seconds) with 7138 GB free disk space
> ----------------------------------------
> ERROR:
> ERROR:  Failed with exit code 1.  (rc=256)
> ERROR:
> ================================================================================
> Don't panic, but a mostly harmless error occurred and canu failed.
> 
> Disk space available:  7138 GB
> 
> Last 50 lines of the relevant log file (/home/user/Documents/Result/0result_canu/trimming/stylosanthes.ovlStore.BUILDING/config.err):
> 
> Found 6648942758 (6648.94 million) overlaps.
> Configuring for 5.00 GB to 5.00 GB memory.
> ERROR:  Cannot sort 6648.94 million overlaps using 5.00 GB memory; too few file handles available.
> ERROR:    olapsPerBucket 127506841
> ERROR:    buckets        53
> ERROR:  Increase memory size (in canu, ovsMemory; in ovStoreBuild, -M)
> 
> canu failed with 'failed to generate configuration for building overlap store'.
```

**Comment by brianwalenz** [comment]
Try `canu .... ovsMemory=30g ...`.

Where did you set -M?  I'll admit the error message isn't terribly clear.

**Comment by ShuChen1986** [comment]
After the error, I tried to use ovStoreBuild to specify the ovsMemory.
```
ovStoreBuild \
> -G /home/user/Documents/Result/0result_canu/trimming/stylosanthes.gkpStore \
> -O /home/user/Documents/Result/0result_canu/trimming/stylosanthes.ovlStore \
> -M 100 \
> -config /home/user/Documents/Result/0result_canu/trimming/stylosanthes.ovlStore.BUILDING/config \
> -L /home/user/Documents/Result/0result_canu/trimming/1-overlapper/ovljob.files
```

**Comment by brianwalenz** [comment]
I have no good suggestions.  One of my data sets generated 15.5 billion overlaps, and resulted in a store of size 330gb.  Your data has less than half the number of overlaps, so the store should be about half the size, yet it is still failing even with 100gb memory allowed (meaning, it can almost process the data in one pass).

What OS is this?  What do `ulimit -Hu`,`ulimit -Su`, `ulimit -Hn` and `ulimit -Sn` report (being, the maximum number of processes and files you can run/have open)?

You're code is somewhat old.  Try updating to the latest unreleased code.  Remove the ovlStore.BUILDING directory before restarting.  Depending on just how old your canu is, it might not restart, in which case, you'll need to restart from the output of the correction step.

You can also try ovsMethod=sequential, which will use a non-parallel version of this algorithm.
