### ISSUE TITLE
Failed mhap precompute not detected

### ISSUE THREAD

**Issue by kehey** [marbl/canu#43]
Hi,

I'm having a curious and annoying problem where the .dat files all stay empty while my fasta files are around 700mb in size. Despite the fact that this is the case, the pipeline continues as it checks for the existence of the dat files, rather than the size.

I do however for the moment have no idea why they do not end up having the suffic FAILED, but the out log file of the precompute.sh is not telling me anything. It just ends with the phrase

```
Time (s) to read filter file: 0.06630411900000001
Processing FASTA files for binary compression...
```

There is nothing after that, and also nothing of the rest of the shell script is executed. So it means the job as a whole fails instantaneously when the mhap preconfigure is started (since no reads are read, and the dat files are size 0). I've tried running the exact commands just for a single file by copying them, and they work perfectly, so I'll have to look why the job fails. I hardly think it's a memory issue, since than I would expect them to die after loading in at least some data.

But in any case, the check for failure should ideally be extended to the size of the dat files.

**Comment by skoren** [comment]
That sounds like the jobs are being terminated by the grid engine though it is strange no message is being recorded. Have you tried manually submitting one of the commands to see if it runs successfully or checking the job history for your failed jobs in the grid engine's log?

The JVM pre-allocates the memory at startup so it should be reserving the full VM space it needs immediately but given that the run begins, it should not be a memory issue since the JVM initialization completed.

**Comment by kehey** [comment]
Yes, the single command works perfectly, that I tested yesterday. I'm going to go check the grid engine's log, but I needed by sys admin for this so that had to wait until today.

**Comment by kehey** [comment]
Okay, I think I identified the problem. It has to do with Java memory. Submitting a single job to the cluster indeed failed:

```
qsub -pe make 16 -l vf=3.125g,h_vmem=3.125g -> requested 50g, FAILED
```

But when I boosted the memory requested, it ran fine:

```
qsub -pe make 16 -l vf=6.125g,h_vmem=6.125g -> requested 98g, SUCCESS
```

However, lowering the memory requested by java (-Xmx) inside the precompute.sh script and leaving the memory at 30g (where it failed in the pipeline), also worked fine:

```
qsub -pe make 16 -l vf=3.125g,h_vmem=3.125g -> requested 50g, SUCCESS when lowering java -Xmx to 40g
```

**Conclusion**: the java command adds 5g requested memory on top of the -Xmx40g command, as the virtual memory was nicely 45g. The tool itself only required 18.9g (see screenshot of htop of this run), but since the virtual memory reserved immediately violated the -l h_vmem=40g, it crashed instanteanously when -Xmx was 50g and h_vmem was 50g.

**Solution**: make the memory in the -Xmx flag lower than the memory requested on the grid

![canumemory](https://cloud.githubusercontent.com/assets/13170085/12912685/71b3c9d6-cf1a-11e5-8154-0b5d64dccd88.png)

**Comment by kehey** [comment]
FYI: this is how I fixed the issue itself in a quick manner: https://github.com/kehey/canu/commit/ef27e53af379aab889f3e4f4cdcd5ac3569be218

I can understand you don't necessarily want this as default in your code, but an option in the trend of

```
adjustForJavaOverhead=20
```

Could be a nice thing to add to the pipeline. My problem is fixed but I'm going to leave this ticket open, just for the aspect of the fact that the check of the dat files could be done by checking file size. You can close if you want. :-)

**Comment by skoren** [comment]
I didn't realize you were requesting h_vmem to be equal to memory. I don't think it makes sense to request equal virtual and real memory limits. Canu requests the memory based on what will be resident not virtual. You will hit several places where the virtual memory usage will be higher than real memory. There are also places where files are memory mapped so the virtual usage would show much higher than real memory. Generally, we don't use h_vmem when running Canu but if you want to, you need to request the memory limits by manually setting the appropriate gridOptions parameter.

**Comment by kehey** [comment]
Okay, I get that, but from a cluster perspective, the reason the use of h_vmem is that if you don't specify h_vmem and multiple people are running the pipeline (or other tools), there is no way to protect the server from overloading on memory because nothing will get killed. Because vf will limit your job to start, but once it has started, there is nothing holding it back. This is exemplified by the fact that the actual virtual memory is already 5g higher for the java programs different than what was requested, which on a busy cluster gives trouble.

Setting h_vmem using the gridOptions parameter would set that limit the same for all jobs, regardless of their actual need. So that's why I set it as the memory parameter of canu and didn't think about it since it is the obliged way to set memory on our system.

So yes, I have to admit that I did indeed cause the crashing myself (oops :-) ), but I would say that taking into account the use of h_vmem is good protocol on a cluster system.

**Comment by skoren** [comment]
Right, I understand but the issue you're describing isn't high virtual memory usage it's swapping. Generally as long as you're not paging the virtual memory can be very large. Memory mapped can't ever be paged in/out (they're already on disk) but they can take up gigabytes of virtual space. While SGE doesn't kill jobs for memory usage other cluster systems (like Slurm) do so Canu does try hard to match its request to memory it will actually need to use while not paging so it shouldn't be the cause of a system being overloaded. Even with this there are sometimes issues where OS overhead causes Canu to use slightly more memory than expected (see issue #5) and it would be very difficult to accurately account for virtual memory usage, especially in the case of memory mapped files. 

You can specify gridOptions on a per-task level:

```
% canu  -options |grep gridOptions
gridOptions                             Grid engine options applied to all jobs
gridOptionsExecutive                    Grid engine options applied to the canu executive script
gridOptionsJobName                      Grid jobs job-name suffix
gridOptionsbat                          Grid engine options applied to unitig construction jobs
gridOptionscns                          Grid engine options applied to unitig consensus jobs
gridOptionscor                          Grid engine options applied to read correction jobs
gridOptionscormhap                      Grid engine options applied to mhap overlaps for correction jobs
gridOptionscorovl                       Grid engine options applied to overlaps for correction jobs
gridOptionsmeryl                        Grid engine options applied to mer counting jobs
gridOptionsobtmhap                      Grid engine options applied to mhap overlaps for trimming jobs
gridOptionsobtovl                       Grid engine options applied to overlaps for trimming jobs
gridOptionsoea                          Grid engine options applied to overlap error adjustment jobs
gridOptionsovb                          Grid engine options applied to overlap store bucketizing jobs
gridOptionsovs                          Grid engine options applied to overlap store sorting jobs
gridOptionsred                          Grid engine options applied to read error detection jobs
gridOptionsutgmhap                      Grid engine options applied to mhap overlaps for unitig construction jobs
gridOptionsutgovl                       Grid engine options applied to overlaps for unitig construction jobs
```

**Comment by kehey** [comment]
Okay, I see the point. Thanks for the elaborate answer!!

**Comment by brianwalenz** [comment]
I'll add and/or stress that we know (from Slurm, and by analysis of the algorithms) that canu is correctly estimating memory usage, and requesting however much memory each component actually uses.  The memory mapped file that Sergey is talking about contains the read data -- on a moderately large assembly, it can easily be 20gb; on a deep human, it's 50gb.  This counts against your VM size (and almost every component maps this file) but not your resident size.  As soon as there is memory pressure on the node, the pages from the memory mapped file are discarded.

It should be easy to set h_vmem to requested + mapped size + constant.  Dig through Execution.pm, looking for how the memory is currently set (buildMemoryOption()), and mirror that for h_vmem.  You can use the same gridEngineMemoryOption, expanded to something like "-l mem=MEMORY -l h_vmem=VMEM".  This is set in Grid_SGE.pm.  The mapped size will be the size of the gkpStore directory.

If patches ever show up, I'll merge in, but I won't set the default to use h_vmem.  You'll have to either modify your install of canu to st the default gridEngineMemoryOption, or supply it on the command line (or use the .canu defaults file that will appear any day now).  We had enough trouble with Slurm and memory and don't want to go through it again with SGE for something we're not convinced is an issue.
