### ISSUE TITLE
errorRate in documentation/source/faq.rst  need some update.

### ISSUE THREAD

**Issue by wangyugui** [marbl/canu#430]
We need to update errorRate in "What parameters should I use for my genome Sequencing type"  part of documentation/source/faq.rst.

1)  the errorRate parameter was recently deprecated in favor of rawErrorRate and correctedErrorRate.
   so we need to update this part.
  (canu 1.4 or earlier) xxxx
  (canu 1.4 and later) xxxx

2) There are advices for PacBio P6, but nothing for P5.

**Comment by wangyugui** [comment]
rawErrorRate  is so import param. and it is not fixed because of diff of operator, machine status.

Is there a tool to eval rawErrorRate  based on mapping to reference genome?
Can we add some Lambdato sample dna, and then eval rawErrorRate  based on Lambda mapping?

**Comment by wangyugui** [comment]
When errorRate=0.013, the corOvlErrorRate is set to 0.2400 ( 24.00%). 
the default is errorRate=0.015, corOvlErrorRate = 0.0450 (  4.50%).
so much changed. is it right?

# canu --version
Canu v1.4 (+141 commits) r8136 15318d8b9935f36a9cffa6026f1a6102535e0d01.

**Comment by brianwalenz** [comment]
The intent of the 'errorRate' parameter was that it would be the expected error in a single corrected read.  From this, we (tried to) pick appropriate values for the error in an uncorrected read, and the difference in an alignment between reads.  This was complicated and had a bunch of hardcoded constants.  One of those constants was to set corOvlErrorRate (the error rate allowed an finding overlaps between uncorrected reads) to 3 times the error rate (1.5 * 3 = 4.5).

We dropped errorRate in favor of setting the 'difference in an alignment of two reads' directly.  So, now, corOvlErrorRate is 24% - we'll accept an alignment of two uncorrected reads of up to 24% difference.

As the docs say, rawErrorRate isn't a very critical parameter.  It can help for _very_ early reads.

The change mentioned in the FAQ for P6 reads is essentially a time optimization.  Canu will run slightly faster with lower error tolerances.

The confusion you're seeing between errorRate=0.013 and the default should have been fixed.  We were incorrectly setting the default value of corOvlErrorRate.  However, in normal usage of canu, this parameter has no effect.

**Comment by wangyugui** [comment]
Thanks for your answer.

**Comment by wangyugui** [comment]
Thanks for the update of faq.rst.

If the eval error rate in unitigging/4-unitigger log is over correctedErrorRate param, should we change correctedErrorRate param and re-run it?

```
drosophila
unitigging/4-unitigger/drosophila.001.filterOverlaps.thr000.num000.log:mean   0.00615636 stddev 0.00697936 -> 0.04803254 fraction error =   4.803254% error
unitigging/4-unitigger/drosophila.001.filterOverlaps.thr000.num000.log:median 0.00380000 mad    0.00160000 -> 0.01803296 fraction error =   1.803296% error

tair
unitigging/4-unitigger/tair.001.filterOverlaps.thr000.num000.log:mean   0.01236207 stddev 0.00758564 -> 0.05787593 fraction error =   5.787593% error
unitigging/4-unitigger/tair.001.filterOverlaps.thr000.num000.log:median 0.01030000 mad    0.00400000 -> 0.04588240 fraction error =   4.588240% error
```
