### ISSUE TITLE
unitigger failed with 'Segmentation fault'

### ISSUE THREAD

**Issue by feixue1039** [marbl/canu#434]
Hello,

I have run canu 1.4 successfully with 50X corrected and trimmed reads, the result is acceptable but not as good as I expected. Then I selected the longest 23X reads and re-run canu. This time I encountered 'segmentation fault' at the bogart stage.

I know that there are many issue pages related to my problem. But I'm not sure which one I should follow. I have attached my log file below.

[unitigger.err.txt](https://github.com/marbl/canu/files/882018/unitigger.err.txt)

**Comment by brianwalenz** [comment]
We're pretty close to the 1.5 release, so upgrading to the latest code is advised.  I can't point to a specific issue for this crash; it does seem familiar.

**Comment by feixue1039** [comment]
I have downloaded the latest version from here: https://github.com/marbl/canu/releases/tag/v1.4
Still encounter the same error.
In issue #267, It was solved by go back to canu-1.3. I will give it a shot.

**Comment by skoren** [comment]
You should try the latest unreleased tip (https://github.com/marbl/canu/archive/master.zip) not a release version.

**Comment by feixue1039** [comment]
Thanks for the help.

I downloaded the master.zip file, installed it and have another try.

Still not work but the reported error seems changed:

Graph  error threshold  = 0.039 (3.900%)
Max    error threshold  = 0.039 (3.900%)

Minimum overlap length = 500 bases

number of threads     = 14 (command line)


==> LOADING AND FILTERING OVERLAPS.

ReadInfo()-- Using 2255009 reads, no minimum read length used.

OverlapCache()-- limited to 65536MB memory (user supplied).
OverlapCache()--       8MB for read data.
OverlapCache()--      34MB for best edges.
OverlapCache()--      60MB for unitig layouts.
OverlapCache()--       0MB for tigs.
OverlapCache()--      17MB for id maps.
OverlapCache()--     137MB for error profiles.
OverlapCache()--      25MB for overlap cache pointers.
OverlapCache()--      48MB for overlap cache initial bucket.
OverlapCache()--     224MB for overlap cache thread data.
OverlapCache()--       8MB for number of overlaps per read.
OverlapCache()--       0MB for other processes.
OverlapCache()-- ---------
OverlapCache()--     427MB for data structures (sum of above).
OverlapCache()--   65108MB available for overlaps.

OverlapCache()-- Loading number of overlaps per read.
OverlapCache()--  Retain at least 136 overlaps/read, based on 22.78x coverage.
OverlapCache()--  Initial guess at 1892 overlaps/read (maximum 2975 overlaps/read).

....
mergeOrphans()-- tig    18662 BUBBLE -> tig    17852
mergeOrphans()-- tig    18665 BUBBLE -> tig    12891
mergeOrphans()-- tig    18692 BUBBLE -> tig    11630
mergeOrphans()-- tig    18726 ORPHAN -> tig    15678
mergeOrphans()-- tig    19088 ORPHAN -> tig    17852
mergeOrphans()-- tig    19121 ORPHAN -> tig    11397
mergeOrphans()-- tig    19122 BUBBLE -> tig    13212
mergeOrphans()-- tig    19214 ORPHAN -> tig     1025
mergeOrphans()-- tig    19268 BUBBLE -> tig    11605
mergeOrphans()-- tig    19309 ORPHAN -> tig      531
mergeOrphans()-- tig    19381 ORPHAN -> tig     3536
mergeOrphans()-- tig    19464 BUBBLE -> tig     7680
mergeOrphans()-- tig    19574 BUBBLE -> tig    17064
mergeOrphans()-- tig    19662 BUBBLE -> tig    14425
mergeOrphans()-- tig    19956 ORPHAN -> tig    19078
mergeOrphans()-- tig    20027 ORPHAN -> tig    12354
mergeOrphans()-- tig    20039 ORPHAN -> tig     3704
mergeOrphans()-- tig    20086 BUBBLE -> tig    19456

Failed with 'Segmentation fault'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::102 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
bogart/AS_BAT_MergeOrphans.C::632 in _Z12mergeOrphansR9TigVectord()
bogart/bogart.C::423 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()

**Comment by skoren** [comment]
The latest is not backwards compatible, you would have to run the assembly from scratch.

**Comment by feixue1039** [comment]
OK. I will re-run the assemble stage in a new folder.
I should have the result tomorrow.
Thank you for the prompt reply. Really appreciate it.

**Comment by brianwalenz** [comment]
Hopefully I'm not too late - save the crashing run, please.  I don't think this is a compatibility problem.

**Comment by feixue1039** [comment]
I have not deleted the old folder yet.

In the meantime, I fail to get the latest version to run. I don't know what goes wrong, but it seems always  fail to find my FASTA file. Even though I feed the -pacbio-corrected option with absolute file path: /home/XX/YY/01.assembly/canu/Mar31th2017/W.trimmedReads.fa

Here is the error message:

Canu release v1.4 (r0 unknown-hash-tag-no-repository-available) failed with:
  reads '..//home/XX/YY/01.assembly/canu/Mar31th2017/W.trimmedReads.fa' not found.

Best wishes,
Min

**Comment by brianwalenz** [comment]
Argh.  A workaround is to remove 'trimmedReads' from the name.

**Comment by feixue1039** [comment]
Get it to work. I will check if it run smoothly to the end when I wake up tomorrow.

**Comment by feixue1039** [comment]
Changed file name and start to run the latest version of canu with the same data set. I will check the result when I wake up tomorrow.

**Comment by feixue1039** [comment]
Checked the progress, still at OverlapInCore stage.

I found that the latest version run much slower that release 1.4 at the OverlapInCore step due to a much higher $utgOvlMerThreshold cutoff (latest version: 5170; release 1.4: 339) was chosen. 

OverlapInCore should be finished by tomorrow.

**Comment by feixue1039** [comment]
Still encountered "segmantation fault" at the bogart stage.

This time I run with the latest version of canu.

-- Canu release v1.4 (r0 unknown-hash-tag-no-repository-available)
-- Detected Java(TM) Runtime Environment '1.8.0_73' (from '/home/xiemin/software/jdk1.8.0_73/bin/java').
-- Detected gnuplot version '4.6 patchlevel 2' (from 'gnuplot') and image format 'png'.
-- Detected 56 CPUs and 252 gigabytes of memory.
-- Limited to 256 gigabytes from maxMemory option.
-- Limited to 56 CPUs from maxThreads option.
-- No grid engine detected, grid disabled.

-- Run   4 jobs concurrently using   64 GB and  14 CPUs for stage 'bogart'.
 
Log file is attached below.
[unitigger.err.txt](https://github.com/marbl/canu/files/888393/unitigger.err.txt)

**Comment by feixue1039** [comment]
I increased input trimmed corrected reads to 30X, still encountered segmentation fault. Is there any way to work around this? 
I only run canu successfully with 54X trimmed corrected reads. However, the assembly result was not as good as I expected.

**Comment by brianwalenz** [comment]
Looking at the code I don't see anything obvious.  Can you share the data (gkpStore and ovlStore) for this?  Could you share it if the sequence data were stripped out?

**Comment by feixue1039** [comment]
What do you mean by "stripped out sequence data"?

Here is how I extracted 25X trimmed reads from all the output of OBT stage:
I calculate sequence length of each read and filtered those that are shorter than like 8000bp. I keep the description line unchanged like this:
>m151019_170443_42199_c100879752550000001823194304021611_s1_p0/19/13865_27965 id=3_0 id=2 clr=0,10641
GGAGTCATAATCTGATACAACATTGTGATGGCATTTAAGACTTCATATTATACCATGTGCTTGAGATTTTTCTTTGTAGAAATATTCTTCTAAGATCTAC
TGAATCCTATGAAGATTAAATGAAATTAACATATGAAATTCCTCAATCAGCATCAAAAGAAAAGCTCTACTACGCAGGACCTGCTCTAATACAAAGAAGT
CACTACCTGCTACAATTCTTTAACACACAAGGGTTGAAGATAGGACTATCTACATTTGGAATAAATGTGCATTCAATGCTAGATTTAAATGCTCCCAACA
ACCATTTTCATCAGACGAAGATCAATTGAAGATATATACCCGCTGTGAATAACAGATACTTGAAGATAAGACCTATATAAACTAGAAGCTTTGAAGATTG
AAGATATAATCTTGCACGAAAAACATTCATCATTTTTTCAACAAAAGCTTTATGTATATATTGTAAAGTTAGAAAAAGCTCTCAAAATACCTTGAACACA
TTGAGAGAAAAAGACTAAGGACTAATTTGTATATTTATCTGTAAGACGATTCTAGCTTTAGTCTCTCAGCAATCTTCAACCACAAATCTATTCTGATTTG
TTTATGGCCAGTAGTGGCTTGTTAGGACAAAGATCACTGGGTGTTAATCAAGCTTAGGGTAGAGCTAGAAGTGGTTGTAACACAATAATTGTAACTTGTG
AGAAGTCAATTCAACTTGGTGGTTTGCCAAGAACTAGACGTAATCTCAATGGTAGAGATGAATTAGTATAACTCCCTGTGTCCGATATTTTCTTGTTCTC
TCTTTGTTTTTAACTAACCCAGGGTCTGAATTGGTTTTTAGGTTTTTGAAAACTTATTGTGCTTTACAAACCTGTCTTTTTCATCATTTGAGTGTGTTTC
:
For the gkpStore and ovlStore data, it is a huge amount of data:
8.6G	MY.gkpStore
5.4G	MY.ovlStore
How to share?

**Comment by brianwalenz** [comment]
By 'stripped out', I could remove the sequence data before you transfer.  This would essentially anonymize you data and reduce the size of the gkpStore.  But it would take me time to write the code to do this.

Tar and gzip those two directories (`tar -cf - MY.gkpStore MY.ovlStore | gzip -1c > data.tar.gz`) then upload to ftp://ftp.cbcb.umd.edu/incoming/sergek.  This is an upload-only location that is only readable by us.

Canu option minReadLength=8000 would do this filtering for you.

**Comment by brianwalenz** [comment]
Possibly fixed, but with no test case, nothing more I can do here.
