### ISSUE TITLE
$bucketSize division by zero

### ISSUE THREAD

**Issue by rxetxe** [marbl/canu#436]
When running reads that are >1Mbp, errors out as “Illegal division by zero at /home/ubuntu/canu/Linux-amd64/bin/lib/canu/Gatekeeper.pm line 365.”

```
my $bucketSize = 0;

if      ($maxLen - $minLen < 10000) {
    $bucketSize = 100;
} elsif ($maxLen - $minLen < 100000) {
    $bucketSize = 1000;
} elsif ($maxLen - $minLen < 1000000) {
    $bucketSize = 5000;
}
```

This appears to solve it:
```
my $bucketSize = 0;

if      ($maxLen - $minLen < 10000) {
    $bucketSize = 100;
} elsif ($maxLen - $minLen < 100000) {
    $bucketSize = 1000;
} elsif ($maxLen - $minLen < 1000000) {
    $bucketSize = 5000;
} else {
    $bucketSize = 10000;
}
```
patch h/t: @koadman

**Comment by brianwalenz** [comment]
Awesome, thanks!

Do you know if the read survived correction and trimming?  Those histograms should help tell this.

**Comment by rxetxe** [comment]
Unfortunately I don't have the logs. I can try reproduce the error later on though.

**Comment by brianwalenz** [comment]
No worries.  That's a mighty long read, and I was curious what kind of quality others are getting from (I assume) Nanopore.
