### ISSUE TITLE
failed to generate estimated lengths of corrected reads

### ISSUE THREAD

**Issue by JohnUrban** [marbl/canu#44]
Hi,

I haven't seen this error before. Any thoughts?

This error was in canu.03.out in a run that otherwise went smooth up until that point.

-- Starting command on Fri Feb 12 02:34:01 2016 with 134537 GB free disk space

    /gpfs_home/jurban/software/canu/canu/Linux-amd64/bin/generateCorrectionLayouts \
      -G /users/jurban/scratch/canu/g250-default/correction/g250-default.gkpStore \
      -O /users/jurban/scratch/canu/g250-default/correction/g250-default.ovlStore \
      -S /users/jurban/scratch/canu/g250-default/correction/2-correction/g250-default.globalScores \
      -C 80 \
      -p /users/jurban/scratch/canu/g250-default/correction/2-correction/g250-default.estimate
ERROR: bogus overlap '   1986708    2010308  N       0       0 121096       0 4294805431  0.185900'
generateCorrectionLayouts: correction/generateCorrectionLayouts.C:92: tgTig* generateLayout(gkStore*, uint32*, uint32, double, double, ovOverlap*, uint32, FILE*): Assertion `ovlLength < (((uint32)1 << 21) - 1)' failed.

Failed with 'Aborted'

Backtrace (mangled):

/gpfs_home/jurban/software/canu/canu/Linux-amd64/bin/generateCorrectionLayouts(_Z17AS_UTL_catchCrashiP7siginfoPv+0x27)[0x42c3f7]
/lib64/libpthread.so.0(+0xf710)[0x7f9490818710]
/lib64/libc.so.6(gsignal+0x35)[0x7f94904a7925]
/lib64/libc.so.6(abort+0x175)[0x7f94904a9105]
/lib64/libc.so.6(+0x2ba4e)[0x7f94904a0a4e]
/lib64/libc.so.6(__assert_perror_fail+0x0)[0x7f94904a0b10]
/gpfs_home/jurban/software/canu/canu/Linux-amd64/bin/generateCorrectionLayouts[0x40272f]
/gpfs_home/jurban/software/canu/canu/Linux-amd64/bin/generateCorrectionLayouts[0x403c08]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x7f9490493d1d]
/gpfs_home/jurban/software/canu/canu/Linux-amd64/bin/generateCorrectionLayouts[0x402299]

Backtrace (demangled):

[0] /gpfs_home/jurban/software/canu/canu/Linux-amd64/bin/generateCorrectionLayouts::AS_UTL_catchCrash(int, siginfo*, void*) + 0x27  [0x42c3f7]
[1] /lib64/libpthread.so.0::(null) + 0xf710  [0x7f9490818710]
[2] /lib64/libc.so.6::(null) + 0x35  [0x7f94904a7925]
[3] /lib64/libc.so.6::(null) + 0x175  [0x7f94904a9105]
[4] /lib64/libc.so.6::(null) + 0x2ba4e  [0x7f94904a0a4e]
[5] /lib64/libc.so.6::(null) + 0  [0x7f94904a0b10]
[6] /gpfs_home/jurban/software/canu/canu/Linux-amd64/bin/generateCorrectionLayouts() [0x40272f]
[7] /gpfs_home/jurban/software/canu/canu/Linux-amd64/bin/generateCorrectionLayouts() [0x403c08]
[8] /lib64/libc.so.6::(null) + 0xfd  [0x7f9490493d1d]
[9] /gpfs_home/jurban/software/canu/canu/Linux-amd64/bin/generateCorrectionLayouts() [0x402299]

GDB:

sh: line 5: 31461 Aborted                 /gpfs_home/jurban/software/canu/canu/Linux-amd64/bin/generateCorrectionLayouts -G /users/jurban/scratch/canu/g250-default/correction/g250-default.gkpStore -O /users/jurban/scratch/canu/g250-default/correction/g250-default.ovlStore -S /users/jurban/scratch/canu/g250-default/correction/2-correction/g250-default.globalScores -C 80 -p /users/jurban/scratch/canu/g250-default/correction/2-correction/g250-default.estimate

-- Finished on Fri Feb 12 02:37:06 2016 (185 seconds) with 134529.7 GB free disk space
----------------------------------------

ERROR: Failed with signal ABRT (6)

================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

Disk space available:  134529.7 GB

canu failed with 'failed to generate estimated lengths of corrected reads'.

**Comment by skoren** [comment]
The error means you have a corrupt overlap store. I'm going to guess you increased the read length from 17 to 21 bits recently? If you had an assembly which had been running and computed some overlaps before the change but the store was built after the change, it would end up with corrupt overlaps. I haven't seen this error in other context than switching the bits mid-run.

**Comment by JohnUrban** [comment]
Yes, yesterday I downloaded the latest code, changed max read length bits from 17 to 21, and installed. However, this assembly started fresh. And it has now happened 4 independent times in a row.

**Comment by skoren** [comment]
That is strange, are you able to share a small dataset to demonstrate the issue?

**Comment by JohnUrban** [comment]
Using MHAP 2.0 packaged with no need for external libraries fixed this problem.

**Comment by jiaocathy** [comment]
Hi! Could you also point me where to find MHAP 2.0 - I can only find Mhap 1.6
I got the same error message on data.
Thanks!

**Comment by skoren** [comment]
It is the default in the head repository
