### ISSUE TITLE
AS_UTL_symlink() operation not supported

### ISSUE THREAD

**Issue by andreyurch** [marbl/canu#440]
```
-- BEGIN CORRECTION
--
--
-- Corrected reads saved in '/xxxxxx/CANU/test/test.correctedReads.fasta.gz'.
--
--
-- BEGIN TRIMMING
--
--
-- Trimmed reads saved in '/xxxxxx/CANU/test/test.trimmedReads.fasta.gz'
--
--
-- BEGIN ASSEMBLY
--
----------------------------------------
-- Starting command on Thu Apr  6 14:53:21 2017 with 8559.644 GB free disk space

    /export/home/aay2c/app2/canu-1.4/Linux-amd64/bin/gatekeeperPartition \
      -G /xxxxxxxx/CANU/test/unitigging/test.gkpStore \
      -T /xxxxxxxx/CANU/test/unitigging/test.ctgStore 1 \
      -b 25000 \
      -p 256 \
    > /xxxxxxxxx/CANU/test/unitigging/test.ctgStore/partitionedReads.err 2>&1

-- Finished on Thu Apr  6 14:53:22 2017 (1 second) with 8559.644 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

Disk space available:  8559.644 GB

Last 50 lines of the relevant log file (/xxxxxxxxx/CANU/test/unitigging/test.ctgStore/partitionedReads.err):


canu failed with 'failed to partition the reads'.
```

**Comment by brianwalenz** [comment]
Not much to go on here.  Is the partitionedReads.err file really empty?  What happens if you cut-n-paste that command (without the output redirection) into a shell?

**Comment by andreyurch** [comment]
This is a symbolic link problem.  
AS_UTL_symlink()-- Failed to make link '/xxxxx/CANU/test/unitigging/test.ctgStore/partitionedReads.gkpStore/info' pointing to file '/xxxxx/CANU/test/unitigging/test.gkpStore/info': Operation not supported
(END) 

I work on the university server.  I tried to execute this command myself:
ln -s /xxxxxx/test/unitigging/test.ctgStore/partitionedReads.gkpStore/info /xxxxx/CANU/test/unitigging/test.gkpStore/info
ln: creating symbolic link `/xxxxxx/CANU/test/unitigging/test.gkpStore/info': File exists

**Comment by skoren** [comment]
This looks like a system error due to ln being unsupported. This often happens on VMs (see issue #387). Are you running in a VM?

**Comment by andreyurch** [comment]
No, mainly work on the physical machine...

**Comment by skoren** [comment]
Try re-running the Canu command to see if it will resume the run since based on your manual command run the link has been created. If it keeps having the error, try moving the run folder to another volume or a local machine scratch disk to see if the symlink error goes away.
