### ISSUE TITLE
50% Reads deleted at trimming stage

### ISSUE THREAD

**Issue by dibyendukumar** [marbl/canu#441]
Hi,

I am trying to assemble a plant genome with high repeat content. Genome should be a homozygous inbred line. Almost half of the reads were discarded at trimming stage. Any suggestions/idea what to do?

I have 22x raw data from Sequel. Assembled contigs (~50k) covers only half of the genome. Please advice!

run command:
`canu -p 'seq14' 'genomeSize=2.5g' 'errorRate=0.013' 'corMhapSensitivity=high' 'corMinCoverage=0' -pacbio-raw`
Also tried `minReadLength=3000 minOverlapLength=400 corMhapSensitivity=normal corMaxEvidenceErate=0.15 corMinCoverage=0` with similar output.

*trimReads.stats output:
```
PARAMETERS:
----------
   1000    (reads trimmed below this many bases are deleted)
 0.0390    (use overlaps at or below this fraction error)
      1    (break region if overlap is less than this long, for 'largest covered' algorithm)
      1    (break region if overlap coverage is less than this many read, for 'largest covered' algorithm)

INPUT READS:
-----------
6171336 reads  52605828041 bases (reads processed)
     0 reads            0 bases (reads not processed, previously deleted)
     0 reads            0 bases (reads not processed, in a library where trimming isn't allowed)

OUTPUT READS:
------------
2987195 reads  22252076759 bases (trimmed reads output)
 48227 reads    240049021 bases (reads with no change, kept as is)
2852754 reads  15996568601 bases (reads with no overlaps, deleted)
283160 reads   2306251295 bases (reads with short trimmed length, deleted)

TRIMMING DETAILS:
----------------
2775030 reads   6645533689 bases (bases trimmed from the 5' end of a read)
2908826 reads   5165348676 bases (bases trimmed from the 3' end of a read)
```
Thanks,
Dibyendu

**Comment by skoren** [comment]
Since you're at the minimum coverage and using the low coverage parameters, the majority of trimming will happen during the trim step, so this is expected. You can try using your original command and increasing the error rate from 0.013 to 0.035. However, plants typically have lots of repeat sequence and some fraction of it is likely being collapsed and not output as contigs (because your coverage is low, read length too short to resolve them). You can check the asm.unassembled.fasta file, look for entries with reads=>1 (it's in the defline).

**Comment by dibyendukumar** [comment]
Thanks Sergey, good to know it is not unusual. We are trying to add more data to reach at least 30x. I am not sure how much we can improve on read-length.
Is covStat of Canu is same as A-stat of Celera? Can we move contings with > 5 covStat from unassembled.fasta to assembled contigs. unassembled.fasta file has plenty of reads with >5 covStat and suggestRepeat=no. Since, contigs.fasta has is only half of the genome size, we need more :)
dibyendu

**Comment by skoren** [comment]
Yes, covStat and A-stat are the same so you can move those contigs. The suggest repeat flag is measuring if that contig was split out during repeat detection/breaking so it should be possible to have A-stat <0 and suggestRepeat=no if that repeat was never in the assembly, just an orphaned collapsed contig.

**Comment by dibyendukumar** [comment]
Great, Thanks again!
dibyendu
