### ISSUE TITLE
optimal parameters for high coverage allotetraploid

### ISSUE THREAD

**Issue by dcopetti** [marbl/canu#442]
Hi,
I am assembling an allotetraploid (selfed) plant, with genome size of about 780 Mb. I have Sequel data, about 123x, subread N50 19 kb. I am making a subset of 100x by selecting only reads longer then 10 kb. Unless the overage is overkill, I would like to use this set for assembling. Our goal is to be able to recover both subgenomes separately - similar to having a heterozygous plant.

Looking at the documentaiton, the tentative command I wrote is this:
```
canu -d /path/ -p cr10k corOutCoverage=200 correctedErrorRate=0.040 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" corMinCoverage=4 genomeSize=771m minOverlapLength=2000 corMinCoverage=2 gridOptions="-W group_list=oge -q standard -l select=4:ncpus=28:mem=168GB -l walltime=240:00:00" -pacbio-raw /path/subreads_10k.fa
```
I wonder if there is something else I should edit before starting the assembly.
Thanks!

**Comment by skoren** [comment]
I would suggest using all 123x, you have essentially a 1.4g genome so having more coverage is better. For the command, you don't need to increase correctedErrorRate and you want to set corMinCoverage only once.
```
canu -d /path/ -p cr10k corMhapSensitivity=normal corOutCoverage=200 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50"  genomeSize=771m minOverlapLength=2000 gridOptions="-W group_list=oge -q standard -l select=4:ncpus=28:mem=168GB -l walltime=240:00:00" -pacbio-raw /path/subreads_10k.fa
```

**Comment by dcopetti** [comment]
Thanks. The 780 Mb is the size of the whole genome (4n). I will still use all the reads then.

**Comment by skoren** [comment]
Ah then you might not need ```corMhapSensitivity=normal``` but it probably won't hurt to run with it on.

**Comment by dcopetti** [comment]
I didn't have a duplicated corMinCoverage, the first was corOutCverage=200. Is actually 200 OK?

**Comment by skoren** [comment]
Your original command was:
```
corMinCoverage=4 genomeSize=771m minOverlapLength=2000 corMinCoverage=2
```
```corMinCoverage=4``` is the default so I left it out, you don't need 2. ```corOutCoverage=200``` is OK.

**Comment by dcopetti** [comment]
sorry about that, thanks!
