### ISSUE TITLE
Correction job failed after two attempts

### ISSUE THREAD

**Issue by mw55309** [marbl/canu#443]
Hi Guys

One of my 31 correction jobs failed after two attempts.  I have restarted and it failed twice again.

All four times resulted in core dumps :-(

The first job had 256Gb of RAM, the second 512Gb RAM.  I can keep increasing this if you think it might help?

More importantly, how do I figure out what's going wrong?

I am trying to assembly some ~500,000 nanopore reads, a metagenome

Cheers
Mick

```
 BEGIN CORRECTION

 generate corrected reads attempt 1 begins with 34 finished, and 1 to compute.

 Starting concurrent execution on Sat Apr  8 07:56:39 2017 with 2574.648 GB free disk space (1 processes; 4 concurrently)

    /exports/cmvm/eddie/eb/groups/watson_grp/rumen_nanopore_temp/rumen_nanopore2/correction/2-correction/correctReads.sh 15 > /exports/cmvm/eddie/eb/groups/watson_gr
p/rumen_nanopore_temp/rumen_nanopore2/correction/2-correction/correctReads.000015.out 2>&1

 Finished on Sat Apr  8 08:25:23 2017 (1724 seconds) with 2544.511 GB free disk space

 1 read correction jobs failed:
   job /exports/cmvm/eddie/eb/groups/watson_grp/rumen_nanopore_temp/rumen_nanopore2/correction/2-correction/correction_outputs/0015.fasta FAILED.
 generate corrected reads attempt 2 begins with 34 finished, and 1 to compute.

 Starting concurrent execution on Sat Apr  8 08:25:23 2017 with 2544.511 GB free disk space (1 processes; 4 concurrently)

    /exports/cmvm/eddie/eb/groups/watson_grp/rumen_nanopore_temp/rumen_nanopore2/correction/2-correction/correctReads.sh 15 > /exports/cmvm/eddie/eb/groups/watson_gr
p/rumen_nanopore_temp/rumen_nanopore2/correction/2-correction/correctReads.000015.out 2>&1

 Finished on Sat Apr  8 08:53:32 2017 (1689 seconds) with 2514.39 GB free disk space


 1 read correction jobs failed:
   job /exports/cmvm/eddie/eb/groups/watson_grp/rumen_nanopore_temp/rumen_nanopore2/correction/2-correction/correction_outputs/0015.fasta FAILED.
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'failed to generate corrected reads.  Made 2 attempts, jobs still failed'.
```

**Comment by mw55309** [comment]
Actually just found this in the .err

Failed with 'Segmentation fault'

Backtrace (mangled):

/exports/cmvm/eddie/eb/groups/watson_grp/software/canu-1.4/Linux-amd64/bin/falcon_sense[0x4074bd]
/lib64/libpthread.so.0(+0xf370)[0x2adecafe8370]
/exports/cmvm/eddie/eb/groups/watson_grp/software/canu-1.4/Linux-amd64/bin/falcon_sense[0x40a7bf]
/exports/cmvm/eddie/eb/groups/watson_grp/software/canu-1.4/Linux-amd64/bin/falcon_sense[0x407b60]
/exports/cmvm/eddie/eb/groups/watson_grp/software/canu-1.4/Linux-amd64/bin/falcon_sense[0x409557]
/exports/cmvm/eddie/eb/groups/watson_grp/software/canu-1.4/Linux-amd64/bin/falcon_sense[0x40271c]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x2adecb216b35]
/exports/cmvm/eddie/eb/groups/watson_grp/software/canu-1.4/Linux-amd64/bin/falcon_sense[0x4034b9]

Backtrace (demangled):

[0] /exports/cmvm/eddie/eb/groups/watson_grp/software/canu-1.4/Linux-amd64/bin/falcon_sense() [0x4074bd]
[1] /lib64/libpthread.so.0::(null) + 0xf370  [0x2adecafe8370]
[2] /exports/cmvm/eddie/eb/groups/watson_grp/software/canu-1.4/Linux-amd64/bin/falcon_sense() [0x40a7bf]
[3] /exports/cmvm/eddie/eb/groups/watson_grp/software/canu-1.4/Linux-amd64/bin/falcon_sense() [0x407b60]
[4] /exports/cmvm/eddie/eb/groups/watson_grp/software/canu-1.4/Linux-amd64/bin/falcon_sense() [0x409557]
[5] /exports/cmvm/eddie/eb/groups/watson_grp/software/canu-1.4/Linux-amd64/bin/falcon_sense() [0x40271c]
[6] /lib64/libc.so.6::(null) + 0xf5  [0x2adecb216b35]
[7] /exports/cmvm/eddie/eb/groups/watson_grp/software/canu-1.4/Linux-amd64/bin/falcon_sense() [0x4034b9]

GDB:

**Comment by skoren** [comment]
Are you using the latest code or Canu 1.4 release? This could be related to issue #318 so if you're not on the latest, you could update to master and retry.

Otherwise, can you generate the inputs for falcon sense and share them? That should be enough to reproduce the crash locally. In the correctReads.sh scripts there is a command like ```generateCorrectionLayouts``` which is piped into ```falcon_sense```. Edit it to  redirect to a file instead of pipe, run the failing partition by hand (```sh correctReads.sh 15```), zip the output, and upload to our incoming ftp: ftp://ftp.cbcb.umd.edu/incoming/sergek/

**Comment by mw55309** [comment]
Hey, I'm on Canu 1.4 so I'll upgrade to the most recent branch and re-try

Thanks
Mick

**Comment by mw55309** [comment]
Hey, just an update, I cloned the current repo and Canu has been running for days with no problems (yet) so mark this as solved

Cheers
Mick
