### ISSUE TITLE
qsub: command not found

### ISSUE THREAD

**Issue by mw55309** [marbl/canu#445]
Hey

I suspect I already know the answer to this.  Our SGE grid has submission nodes and worker nodes.  The worker nodes are disabled from submitting jobs.  All submissions *have* to happen on a submission node.

Is there any way to get round this using canu?

Other than "useGrid=false" which means the job takes ~5 days

Cheers
Mick

**Comment by skoren** [comment]
Can you get access to the submit nodes through qsub? If so you can add ```gridOptionsExecutive=<whatever options are required to get access to a submit node>```. The executive itself doesn't use many resources or threads so it can run on the submit nodes and will submit compute-intensive jobs to the grid.

Otherwise, your other option is to use ```useGrid=remote``` which should stop every time it gets to a submit command, tell you to submit, you manually submit the jobs, wait for the to finish, and re-run the canu command to restart computation. This requires lots of manual intervention.

Lastly, if you update to the latest code you can set ```overlapper=mhap utgReAlign=true```. This will use the mhap overlapper for all overlap stages. In limited testing, it seems to work reasonably well. We're planning on making this the default for the 1.6 release - but that's a few months away.

**Comment by brianwalenz** [comment]
Or you could be slightly sneaky and make a qsub wrapper command that uses ssh to run a command on the submit node.  The tricky part is to make sure that the qsub is run from the correct directory on the submit node.  Pseudocode:
```
#!/bin/sh
ssh submitnode cd `pwd` \&\& qsub "$@"
```
It might also be possible to change the submit command in Canu:
```
gridEngineSubmitCommand="ssh submitnode cd `pwd` \&\& qsub \"$@\""
```
but there is probably some crazy escaping needed to keep the shell from expanding variables too soon.

Note that Canu needs to have the job id of the new job on stdout of this command.

Not sure what else we can do for you here, so I'm closing the issue.  If you get something like this working, I'd appreciate seeing the solution.

**Comment by mw55309** [comment]
OK just an update and a question

We are close to having a work around for this, just need to double check the passing of environmental variables properly to the qsub node.

I will post if it works.

Question - we use "module" to load packages on job submission.  One of these is Java.  So in theory I need to run "module load java" on every job that uses java.

How should / could I do this in Canu?

**Comment by skoren** [comment]
You could just pass `java=<path to java binary>` to canu which should be sufficient. You could also add ```-V``` to gridOptions to pass through the current user's environment.

**Comment by mw55309** [comment]
Hi Sergey

So first question: I think module might do more than set the java path, it also sets environmental variables.  Is there any way to get these kind of module commands in the sell scripts?

Second question: I'm confused about canu.defaults and how it works.  This is my file:

gridEngineThreadsOption=-pe sharedmem THREADS
gridEngineMemoryOption=-l h_vmem=MEMORY
gridOptions=-V
gridOptions=-S /bin/bash
gridEngineArrayMaxJobs=5000
gridOptions=-P roslin_faang
gridOptions=-l h_rt=72:00:00
maxThreads=16
maxMemory=512G

When and where should these get picked up?

For example, here is my  precompute.jobSubmit.sh:

#!/bin/sh

/exports/cmvm/eddie/eb/groups/watson_grp/rumen_nanopore_temp/canu_test/qsub \
  -l h_vmem=4g -pe sharedmem 16 -l h_rt=72:00:00 -j y -o precompute.\$TASK_ID.out \
  -cwd -N "cormhap_canutest2" \
  -t 1-1 \
  ./precompute.sh 0 \
> ./precompute.jobSubmit.out 2>&1

I don't see "-V" in there, even though it's in my canu.defaults.  Nor "-P roslin_faang", but "-l h_rt=72:00:00" is... so I am confused.

Sorry if I missed this in the docs

Cheers
Mick
