### ISSUE TITLE
Duration of Canu assemblies

### ISSUE THREAD

**Issue by dcopetti** [marbl/canu#45]
Hello,
I am running Canu on a 16 processor server (181 Gb RAM) with a 10 Mb yeast genome (one SMRT cell of data, 420 Mb). Since more than 2 days it is stuck at the overlapInCore step. A file (trimming/1-overlapper/overlap.000001.out) was written a couple of hours ago, and below there is the STDOUT. I am wondering if this duration is normal for this software with this amount of data and on this machine. If so, even assembling a couple of good SMRT cells will be a very long process. With bacterial data I was able to complete assemblies in a few hours.
Thanks,

Dario

```
-- Meryl attempt 0 begins.
----------------------------------------
-- Starting concurrent execution on Wed Feb 10 10:57:40 2016 with 655.6 GB free disk space (1 processes; 4 concurrently)
    /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/0-mercounts/meryl.sh 1 > /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/0-mercounts/meryl.000001.out 2>&1
-- Finished on Wed Feb 10 10:58:14 2016 (34 seconds) with 655.5 GB free disk space
----------------------------------------
-- Meryl finished successfully.
----------------------------------------
-- Starting command on Wed Feb 10 10:58:14 2016 with 655.5 GB free disk space
    /opt/canu/Linux-amd64/bin/meryl \
      -Dh \
      -s /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/0-mercounts/Y11946_1.ms22 \
    > /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/0-mercounts/Y11946_1.ms22.histogram \
    2> /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/0-mercounts/Y11946_1.ms22.histogram.info
-- Finished on Wed Feb 10 10:58:14 2016 (lickety-split) with 655.5 GB free disk space
----------------------------------------
----------------------------------------
-- Starting command on Wed Feb 10 10:58:14 2016 with 655.5 GB free disk space
    /opt/canu/Linux-amd64/bin/estimate-mer-threshold  \
      -m /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/0-mercounts/Y11946_1.ms22  \
    > /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/0-mercounts/Y11946_1.ms22.estMerThresh.out \
    2> /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/0-mercounts/Y11946_1.ms22.estMerThresh.err
-- Finished on Wed Feb 10 10:58:14 2016 (lickety-split) with 655.5 GB free disk space
----------------------------------------
----------------------------------------
-- Starting command on Wed Feb 10 10:58:14 2016 with 655.5 GB free disk space
    /opt/canu/Linux-amd64/bin/meryl \
      -Dt \
      -n 1774 \
      -s /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/0-mercounts/Y11946_1.ms22 \
    > /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/0-mercounts/Y11946_1.ms22.frequentMers.fasta \
    2> /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/0-mercounts/Y11946_1.ms22.frequentMers.fasta.err
-- Finished on Wed Feb 10 10:58:15 2016 (1 second) with 655.5 GB free disk space
----------------------------------------
-- Reset obtOvlMerThreshold from auto to 1774.
--
-- Found 246325943 22-mers; 29779099 distinct and 14354894 unique.  Largest count 16314.
--
-- OVERLAPPER (normal) (trimming) erate=0.54
--
----------------------------------------
-- Starting command on Wed Feb 10 10:58:15 2016 with 655.6 GB free disk space
    /opt/canu/Linux-amd64/bin/overlapInCorePartition \
     -g  /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/Y11946_1.gkpStore \
     -bl 100000000 \
     -bs 0 \
     -rs 2000000 \
     -rl 0 \
     -ol 500 \
     -o  /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/1-overlapper/Y11946_1.partition \
    > /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/1-overlapper/Y11946_1.partition.err 2>&1
-- Finished on Wed Feb 10 10:58:15 2016 (lickety-split) with 655.6 GB free disk space
----------------------------------------
--
-- Configured 3 overlapInCore jobs.
-- overlapInCore attempt 0 begins with 0 finished, and 3 to compute.
----------------------------------------
-- Starting concurrent execution on Wed Feb 10 10:58:15 2016 with 655.6 GB free disk space (3 processes; 2 concurrently)
    /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/1-overlapper/overlap.sh 1 > /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/1-overlapper/overlap.000001.out 2>&1
    /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/1-overlapper/overlap.sh 2 > /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/1-overlapper/overlap.000002.out 2>&1
--
----------------------------------------
-- Starting command on Wed Feb 10 10:58:15 2016 with 655.6 GB free disk space
    /opt/canu/Linux-amd64/bin/overlapInCorePartition \
     -g  /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/Y11946_1.gkpStore \
     -bl 100000000 \
     -bs 0 \
     -rs 2000000 \
     -rl 0 \
     -ol 500 \
     -o  /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/1-overlapper/Y11946_1.partition \
    > /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/1-overlapper/Y11946_1.partition.err 2>&1
-- Finished on Wed Feb 10 10:58:15 2016 (lickety-split) with 655.6 GB free disk space
----------------------------------------
--
-- Configured 3 overlapInCore jobs.
-- overlapInCore attempt 0 begins with 0 finished, and 3 to compute.
----------------------------------------
-- Starting concurrent execution on Wed Feb 10 10:58:15 2016 with 655.6 GB free disk space (3 processes; 2 concurrently)
    /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/1-overlapper/overlap.sh 1 > /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/1-overlapper/overlap.000001.out 2>&1
    /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/1-overlapper/overlap.sh 2 > /opt/Sma_Processing/Dario_Analysis/yeast_canu/test1/trimming/1-overlapper/overlap.000002.out 2>&1
```

**Comment by skoren** [comment]
Over a day is definitely too long, normally we assemble yeast (12mb) in a couple of hours or less. However, it looks like the error rate is set very high (50%) which is most likely the issue. Are you starting with raw or corrected reads? How are you running Canu?

**Comment by dcopetti** [comment]
the command is this, with just errorRate modified:
canu -d /../test1 -p Y11946_1 genomeSize=16m corMinCoverage=2 errorRate=0.18 -pacbio-raw input.fa
and the first part of the STDOUT had the error values below. Which ones shall I touch first? To me the differences among them are not so clear, and I thought that the default would be fine.
Thanks

-- Detected Java(TM) Runtime Environment '1.8.0_66' (from 'java').
-- Detected 16 CPUs and 173 gigabytes of memory.
-- No grid engine detected, grid disabled.
[...]
-- This is canu parallel iteration #1, out of a maximum of 2 attempts.
-- Final error rates before starting pipeline:
--   genomeSize          -- 16000000
--   errorRate           -- 0.18
--   corOvlErrorRate     -- 0.54
--   obtOvlErrorRate     -- 0.54
--   utgOvlErrorRate     -- 0.54
--   obtErrorRate        -- 0.54
--   utgGraphErrorRate   -- 0.36
--   utgBubbleErrorRate  -- 0.45
--   utgMergeErrorRate   -- 0.27
--   utgRepeatErrorRate  -- 0.36
--   corErrorRate        -- 1.8
--   cnsErrorRate        -- 0.45

**Comment by skoren** [comment]
So the documentation might not be clear but the error rate is set automatically and is supposed to be the corrected read error rate. It is set to 0.025 by default for pacbio data. There are multipliers which adjust it for raw reads which is why you're ending up with huge error rates for everything downstream. I'd suggest re-running without manually setting the error rate.

**Comment by dcopetti** [comment]
Removing the error rate parameter the job finishes in about 24 h, with significant differences from the HGAP (SMRT portal, 10 kb read length threshold) assemblies.
Here are some basic metrics, I would appreciate your comment about them. These are two yeast strains of 10 Mb and 12 Mb, with 4 and 16 chromosomes, resp. The sequencing data had 420 and 1031 Mb, mean ROI length of 10 and 13 kb.
Canu assembly metrics:
- Strain1: # of ctg: 37 (with HGAP: 433); total size: 12.14 Mb (10.81); longest contig: 2422 kb (260 kb); N50: 1284 kb (60 kb); L50: 3 (53)
- Strain2: # of ctg: 63 (with HGAP: 107); total size: 12.85 Mb (13.01); longest contig: 907 kb (823 kb); N50: 613 kb (456 kb); L50: 9 (10)
I am surprised by the big differences in contig number and N50: do you think that the low coverage had Canu working better than HGAP?
Thanks

**Comment by skoren** [comment]
I assume you're using HGAP3? It's hard to say what exact reason caused the differences in assemblies. HGAP3 relies on BLASR which can have some issues on genomes with lots of repeat elements (like a chloroplast genome) which I don't know if either of your genomes have. Canu also auto-computes the read threshold to get a desired coverage for assembly and selects the best reads to correct rather than a fixed length threshold which could also have made a difference if the 10Kbp threshold was too stringent in HGAP. 

As a post-processing step you should run Quiver on the Canu assemblies, this is built into SMRTportal but not in Canu. You can run Quiverm manually or import the Canu assembly as a reference in SMRTportal and follow the RS-Resequencing protocol:
http://files.pacb.com/software/smrtanalysis/2.3.0/doc/smrtportal/help/Webhelp/SMRT_Portal.htm

There is documentation on how to run Quiver manually on the Canu docs here:
http://canu.readthedocs.org/en/latest/quick-start.html#consensus-accuracy
