### ISSUE TITLE
where is tigStore?

### ISSUE THREAD

**Issue by metacrobe** [marbl/canu#450]
Hi, 

I ran the standard canu pipeline for nanopore data described in the Quick start guide (http://canu.readthedocs.io/en/stable/quick-start.html#assembling-oxford-nanopore-data) and I am not seeing a  `tigStore ` directory in the `unitigging` directory. 

Canu is installed on a server and I am trying to determine if this has something to do with it or if there is another issue. The pipeline appeared to finish successfully with no errors.

Thanks!
Jarrod

**Comment by skoren** [comment]
The tigStore has been split into two stores, the ctgStore and the utgStore. You probably want the ctgStore to see the contigs. I've updated the docs:
http://canu.readthedocs.io/en/latest/quick-start.html#assembling-oxford-nanopore-data

Unitigs are meant to be maximal single haplotype (no switching) units while a contig is comprised of multiple unitigs.

**Comment by metacrobe** [comment]
perfect. thanks for the answer. I thought (was hoping) it was something like that. I have all the files I should have...
