### ISSUE TITLE
difference in final unitig size vs. genomeSize parameter

### ISSUE THREAD

**Issue by indapa** [marbl/canu#458]
Dear Canu team,

I'm still learning about de-novo assembly and I'm hoping you can provide some intuition. I was performing a PacBio canu assembly with my viral species of interest and provided a genomeSize value of 192000. However, the final unitig size 203kb. I'm wondering why there is a 10kb difference between the final unitig size and the genomeSize parameter?

**Comment by skoren** [comment]
The genome size parameter is only an estimate and used to select the longest reads of sufficient coverage for assembly and to compute the NG stats reported during the run. It doesn't actually affect or control what size the final assembly will be and it can be quite different (in the case of a heterozygous genome, for example). So it's normal for the two to be different.

If your genome is circular, Canu will break the circle in an arbitrary place and have an overlap between the two circular ends (you can also see if the contig is circular in the gfa output). In this case the contig size is an over-estimate of the genome size, you'd have to trim back the overlapping sequence to get the true genome without the redundancy. You can use the gfa/self alignments or [Circlator](https://sanger-pathogens.github.io/circlator/) can do this as well.

**Comment by indapa** [comment]
Thanks for the reply, @skoren. My viral species forms hairpin loops at the 5' and 3' end.  However, the fasta header in the unitig file says 'suggestCircular=no'  I'll  take a look at the gfa/self alignments or use Circlator like you said.

**Comment by skoren** [comment]
The suggestCircular flag isn't currently used and it sounds like your genome isn't circular in the standard sense. I would expect your self alignment to look like this:
![image002](https://cloud.githubusercontent.com/assets/923478/25185423/4d71b178-24eb-11e7-9905-353b66654e08.png)
where the sequencing goes through the hairpin and shows up as an X on the plot. The true end of the sequence would be where the arrows point to the middle of the X.

**Comment by indapa** [comment]
![out](https://cloud.githubusercontent.com/assets/456750/25193626/96040606-24ec-11e7-9995-e289386520b3.png)

Thanks @skoren. I did nucmer self-alignment and the hairpin(s) show up as an X, like you said. I'll take a look at the *.coords file to get the approximate end(s) of the sequence. I really appreciate your help!

**Comment by skoren** [comment]
No problem, happy to help.
