### ISSUE TITLE
canu failed with 'meryl histogram failed'.

### ISSUE THREAD

**Issue by rotheconrad** [marbl/canu#459]
Execute command: ```canu -p StPcB2a2b -d Canu_Assembly genomeSize=38.5m -pacbio-raw StPacBio2a2b.fastq -maxMemory=30 -maxThreads=8```

```
-- Detected 16 CPUs and 63 gigabytes of memory.
-- Detected Java(TM) Runtime Environment '1.8.0_121' (from 'java').
-- No grid engine detected, grid disabled.
maxMemory 30 maxThreads 8
maxMemory 30 maxThreads 8
maxMemory 30 maxThreads 8
maxMemory 30 maxThreads 8
maxMemory 30 maxThreads 8
maxMemory 30 maxThreads 8
maxMemory 30 maxThreads 8
maxMemory 30 maxThreads 8
maxMemory 30 maxThreads 8
maxMemory 30 maxThreads 8
maxMemory 30 maxThreads 8
maxMemory 30 maxThreads 8
maxMemory 30 maxThreads 8
maxMemory 30 maxThreads 8
maxMemory 30 maxThreads 8
--
-- Allowed to run   2 jobs concurrently, and use up to   4 compute threads and   15 GB memory for stage 'bogart (unitigger)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   2 jobs concurrently, and use up to   4 compute threads and    8 GB memory for stage 'read error detection (overlap error adjustment)'.
-- Allowed to run   8 jobs concurrently, and use up to   1 compute thread  and    2 GB memory for stage 'overlap error adjustment'.
-- Allowed to run   2 jobs concurrently, and use up to   4 compute threads and   15 GB memory for stage 'utgcns (consensus'.
-- Allowed to run   8 jobs concurrently, and use up to   1 compute thread  and    4 GB memory for stage 'overlap store sequential building'.
-- Allowed to run   8 jobs concurrently, and use up to   1 compute thread  and    3 GB memory for stage 'overlap store parallel bucketizer'.
-- Allowed to run   8 jobs concurrently, and use up to   1 compute thread  and    4 GB memory for stage 'overlap store parallel sorting'.
-- Allowed to run   8 jobs concurrently, and use up to   1 compute thread  and    3 GB memory for stage 'overlapper'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run   2 jobs concurrently, and use up to   4 compute threads and    8 GB memory for stage 'meryl (k-mer counting)'.
-- Allowed to run   2 jobs concurrently, and use up to   4 compute threads and   15 GB memory for stage 'falcon_sense (read correction)'.
--
-- This is canu parallel iteration #1, out of a maximum of 2 attempts.
--
-- Final error rates before starting pipeline:
--   
--   genomeSize          -- 38500000
--   errorRate           -- 0.025
--   
--   corOvlErrorRate     -- 0.075
--   obtOvlErrorRate     -- 0.075
--   utgOvlErrorRate     -- 0.075
--   
--   obtErrorRate        -- 0.075
--   
--   utgGraphErrorRate   -- 0.05
--   utgBubbleErrorRate  -- 0.0625
--   utgMergeErrorRate   -- 0.0375
--   utgRepeatErrorRate  -- 0.05
--   
--   corErrorRate        -- 0.30
--   cnsErrorRate        -- 0.0625
--
--
-- BEGIN CORRECTION
--
--
-- GATEKEEPER (correction)
--
--
-- Starting command on Tue Apr 18 14:17:38 2017 with 2573.3 GB free disk space
--
/home/boss/Documents/canu-1.0/Linux-amd64/bin/gatekeeperCreate \
  -minlength 1000 \
  -o /media/boss/Rollins_Lab/PacBio/Canu_Assembly/correction/StPcB2a2b.gkpStore.BUILDING \
  /media/boss/Rollins_Lab/PacBio/Canu_Assembly/correction/StPcB2a2b.gkpStore.gkp \
> /media/boss/Rollins_Lab/PacBio/Canu_Assembly/correction/StPcB2a2b.gkpStore.err 2>&1
--
-- Finished on Tue Apr 18 14:17:44 2017 (6 seconds) with 2573.2 GB free disk space
--
-- In gatekeeper store '/media/boss/Rollins_Lab/PacBio/Canu_Assembly/correction/StPcB2a2b.gkpStore':
--   Found 112265 reads.
--   Found 252581481 bases (6.56 times coverage).
--
--   Read length histogram (one '*' equals 837.65 reads):
--        0    999      0 
--     1000   1999  58636 **********************************************************************
--     2000   2999  35664 ******************************************
--     3000   3999  10793 ************
--     4000   4999   3672 ****
--     5000   5999   1644 *
--     6000   6999    895 *
--     7000   7999    461 
--     8000   8999    212 
--     9000   9999    142 
--    10000  10999     64 
--    11000  11999     37 
--    12000  12999     16 
--    13000  13999     14 
--    14000  14999      2 
--    15000  15999      6 
--    16000  16999      5 
--    17000  17999      2 
-- MERYL (correction)
-- Meryl attempt 1 begins.
--
-- Starting concurrent execution on Tue Apr 18 14:17:45 2017 with 2573.2 GB free disk space (1 processes; 2 concurrently)
/media/boss/Rollins_Lab/PacBio/Canu_Assembly/correction/0-mercounts/meryl.sh 1 > /media/boss/Rollins_Lab/PacBio/Canu_Assembly/correction/0-mercounts/meryl.000001.out 2>&1
--
-- Finished on Tue Apr 18 14:17:45 2017 (0 seconds) with 2573.2 GB free disk space
--
-- meryl failed.
--
-- Meryl attempt 2 begins.
--
-- Starting concurrent execution on Tue Apr 18 14:17:45 2017 with 2573.2 GB free disk space (1 processes; 2 concurrently)
/media/boss/Rollins_Lab/PacBio/Canu_Assembly/correction/0-mercounts/meryl.sh 1 > /media/boss/Rollins_Lab/PacBio/Canu_Assembly/correction/0-mercounts/meryl.000001.out 2>&1
--
-- Finished on Tue Apr 18 14:17:45 2017 (0 seconds) with 2573.2 GB free disk space
--
-- Starting command on Tue Apr 18 14:17:45 2017 with 2573.2 GB free disk space
--
/home/boss/Documents/canu-1.0/Linux-amd64/bin/meryl \
  -Dh \
  -s /media/boss/Rollins_Lab/PacBio/Canu_Assembly/correction/0-mercounts/StPcB2a2b.ms16 \
> /media/boss/Rollins_Lab/PacBio/Canu_Assembly/correction/0-mercounts/StPcB2a2b.ms16.histogram \
2> /media/boss/Rollins_Lab/PacBio/Canu_Assembly/correction/0-mercounts/StPcB2a2b.ms16.histogram.info
--
-- Finished on Tue Apr 18 14:17:45 2017 (0 seconds) with 2573.2 GB free disk space

ERROR: Failed with signal HUP (1)

================================================================================
Please panic.  canu failed, and it shouldn't have.

Stack trace:

 at /home/boss/Documents/canu-1.0/Linux-amd64/bin/lib/canu/Defaults.pm line 220.
	canu::Defaults::caFailure('meryl histogram failed', '/media/boss/Rollins_Lab/PacBio/Canu_Assembly/correction/0-mer...') called at /home/boss/Documents/canu-1.0/Linux-amd64/bin/lib/canu/Meryl.pm line 379
	canu::Meryl::merylProcess('/media/boss/Rollins_Lab/PacBio/Canu_Assembly', 'StPcB2a2b', 'cor') called at /home/boss/Documents/canu-1.0/Linux-amd64/bin/canu line 403

Last few lines of the relevant log file (/media/boss/Rollins_Lab/PacBio/Canu_Assembly/correction/0-mercounts/StPcB2a2b.ms16.histogram.info):

merylStreamReader()-- ERROR: /media/boss/Rollins_Lab/PacBio/Canu_Assembly/correction/0-mercounts/StPcB2a2b.ms16.mcidx is not a merylStream index file!
merylStreamReader()-- ERROR: /media/boss/Rollins_Lab/PacBio/Canu_Assembly/correction/0-mercounts/StPcB2a2b.ms16.mcdat is not a merylStream data file!

canu failed with 'meryl histogram failed'.
```

**Comment by brianwalenz** [comment]
If this really is v1.0, update to v1.5 and try again.

With only 6.5x coverage, and short reads, you won't get much - if any at all - assembly.

**Comment by rotheconrad** [comment]
Hello Thank you! I thought I had v1.4 working but my system was still accessing v1.0. I've updated it now and still get the following error very quickly. I have more and better reads on the way. I was just using these reads to get a head start on using the software.  Thank you again!

canu -p StPcB2a2b -d Canu_Assembly genomeSize=38.5m -pacbio-raw StPacBio2a2b.fastq -maxMemory=30 -maxThreads=8
-- Canu v1.4 (+0 commits) r7995 7b04cd09002d6b865ca05f4a3f53edb936b5c925.
-- Detected Java(TM) Runtime Environment '1.8.0_121' (from 'java').
-- Detected gnuplot version '4.6 patchlevel 4' (from 'gnuplot') and image format 'png'.
-- Detected 16 CPUs and 63 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
-- Allowed to run   2 jobs concurrently, and use up to   4 compute threads and   15 GB memory for stage 'bogart (unitigger)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run   2 jobs concurrently, and use up to   4 compute threads and    2 GB memory for stage 'read error detection (overlap error adjustment)'.
-- Allowed to run   8 jobs concurrently, and use up to   1 compute thread  and    1 GB memory for stage 'overlap error adjustment'.
-- Allowed to run   2 jobs concurrently, and use up to   4 compute threads and   15 GB memory for stage 'utgcns (consensus)'.
-- Allowed to run   8 jobs concurrently, and use up to   1 compute thread  and    3 GB memory for stage 'overlap store parallel bucketizer'.
-- Allowed to run   8 jobs concurrently, and use up to   1 compute thread  and    8 GB memory for stage 'overlap store parallel sorting'.
-- Allowed to run   8 jobs concurrently, and use up to   1 compute thread  and    3 GB memory for stage 'overlapper'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run   2 jobs concurrently, and use up to   4 compute threads and    8 GB memory for stage 'meryl (k-mer counting)'.
-- Allowed to run   4 jobs concurrently, and use up to   2 compute threads and    7 GB memory for stage 'falcon_sense (read correction)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run   1 job  concurrently, and use up to   8 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
--
-- This is canu parallel iteration #1, out of a maximum of 2 attempts.
--
-- Final error rates before starting pipeline:
--   
--   genomeSize          -- 38500000
--   errorRate           -- 0.015
--   
--   corOvlErrorRate     -- 0.045
--   obtOvlErrorRate     -- 0.045
--   utgOvlErrorRate     -- 0.045
--   
--   obtErrorRate        -- 0.045
--   
--   cnsErrorRate        -- 0.045
--
--
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Tue Apr 18 14:50:49 2017 with 2573.362 GB free disk space

    /home/boss/Documents/canu-1.4/Linux-amd64/bin/gatekeeperCreate \
      -minlength 1000 \
      -o /media/boss/Rollins_Lab/PacBio/Canu_Assembly/correction/StPcB2a2b.gkpStore.BUILDING \
      /media/boss/Rollins_Lab/PacBio/Canu_Assembly/correction/StPcB2a2b.gkpStore.gkp \
    > /media/boss/Rollins_Lab/PacBio/Canu_Assembly/correction/StPcB2a2b.gkpStore.BUILDING.err 2>&1

-- Finished on Tue Apr 18 14:50:54 2017 (5 seconds) with 2573.273 GB free disk space
----------------------------------------
--
-- In gatekeeper store '/media/boss/Rollins_Lab/PacBio/Canu_Assembly/correction/StPcB2a2b.gkpStore':
--   Found 112265 reads.
--   Found 252581481 bases (6.56 times coverage).
--
--   Read length histogram (one '*' equals 837.65 reads):
--        0    999      0 
--     1000   1999  58636 **********************************************************************
--     2000   2999  35664 ******************************************
--     3000   3999  10793 ************
--     4000   4999   3672 ****
--     5000   5999   1644 *
--     6000   6999    895 *
--     7000   7999    461 
--     8000   8999    212 
--     9000   9999    142 
--    10000  10999     64 
--    11000  11999     37 
--    12000  12999     16 
--    13000  13999     14 
--    14000  14999      2 
--    15000  15999      6 
--    16000  16999      5 
--    17000  17999      2 
-- Meryl attempt 1 begins.
----------------------------------------
-- Starting concurrent execution on Tue Apr 18 14:50:55 2017 with 2573.27 GB free disk space (1 processes; 2 concurrently)

    /media/boss/Rollins_Lab/PacBio/Canu_Assembly/correction/0-mercounts/meryl.sh 1 > /media/boss/Rollins_Lab/PacBio/Canu_Assembly/correction/0-mercounts/meryl.000001.out 2>&1

-- Finished on Tue Apr 18 14:50:55 2017 (lickety-split) with 2573.27 GB free disk space
----------------------------------------
--
-- meryl failed.
--
-- Meryl attempt 2 begins.
----------------------------------------
-- Starting concurrent execution on Tue Apr 18 14:50:55 2017 with 2573.27 GB free disk space (1 processes; 2 concurrently)

    /media/boss/Rollins_Lab/PacBio/Canu_Assembly/correction/0-mercounts/meryl.sh 1 > /media/boss/Rollins_Lab/PacBio/Canu_Assembly/correction/0-mercounts/meryl.000001.out 2>&1

-- Finished on Tue Apr 18 14:50:55 2017 (lickety-split) with 2573.27 GB free disk space
----------------------------------------
--
-- meryl failed.
--
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'failed to generate mer counts.  Made 2 attempts, jobs still failed'.

**Comment by brianwalenz** [comment]
What is in meryl.000001.out?  What happens if you run "meryl.sh 1" by hand?  Remove all the files in 0-mercounts (except the shell script, obviously) first.  It is failing almost immediately, which is somewhat good.

If possible, update canu again - v1.5 was released yesterday.

**Comment by rotheconrad** [comment]
Ok. Thank you again for your help. I updated to v1.5 and still get a similar error. I guess I need to change some permissions somewhere?

$:>cat trimming/0-mercounts/meryl.000001.out
sh: 1: ./meryl.sh: Permission denied

$:> canu -p StPcB2a2b -d Canu_Assembly genomeSize=38.5m -pacbio-corrected StPacBio2a2b.fastq   [ 2:34PM]
-- Canu release v1.5
-- Detected Java(TM) Runtime Environment '1.8.0_121' (from 'java').
-- Detected gnuplot version '4.6 patchlevel 4' (from 'gnuplot') and image format 'png'.
-- Detected 16 CPUs and 63 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
-- Run   4 jobs concurrently using    8 GB and   4 CPUs for stage 'meryl'.
-- Run   1 job  concurrently using    6 GB and  16 CPUs for stage 'mhap (cor)'.
-- Run   2 jobs concurrently using    8 GB and   8 CPUs for stage 'overlapper (obt)'.
-- Run   2 jobs concurrently using    8 GB and   8 CPUs for stage 'overlapper (utg)'.
-- Run   8 jobs concurrently using    7 GB and   2 CPUs for stage 'falcon_sense'.
-- Run  16 jobs concurrently using    3 GB and   1 CPU  for stage 'ovStore bucketizer'.
-- Run  16 jobs concurrently using    8 GB and   1 CPU  for stage 'ovStore sorting'.
-- Run   4 jobs concurrently using    2 GB and   4 CPUs for stage 'read error detection'.
-- Run  16 jobs concurrently using    1 GB and   1 CPU  for stage 'overlap error adjustment'.
-- Run   4 jobs concurrently using   15 GB and   4 CPUs for stage 'bogart'.
-- Run  16 jobs concurrently using    3 GB and   1 CPU  for stage 'GFA alignment and processing'.
-- Run   4 jobs concurrently using   15 GB and   4 CPUs for stage 'consensus'.
--
-- Generating assembly 'StPcB2a2b' in '/media/boss/Rollins_Lab/PacBio/Canu_Assembly'
--
-- Parameters:
--
--  genomeSize        38500000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0450 (  4.50%)
--
--
-- BEGIN TRIMMING
--
----------------------------------------
-- Starting command on Mon Apr 24 14:34:57 2017 with 2570.458 GB free disk space

    cd trimming
    /home/boss/Documents/canu-1.5/Linux-amd64/bin/gatekeeperCreate \
      -minlength 1000 \
      -o ./StPcB2a2b.gkpStore.BUILDING \
      ./StPcB2a2b.gkpStore.gkp \
    > ./StPcB2a2b.gkpStore.BUILDING.err 2>&1

-- Finished on Mon Apr 24 14:35:13 2017 (16 seconds) with 2570.369 GB free disk space
----------------------------------------
--
-- In gatekeeper store 'trimming/StPcB2a2b.gkpStore':
--   Found 112265 reads.
--   Found 252581481 bases (6.56 times coverage).
--
--   Read length histogram (one '*' equals 837.65 reads):
--        0    999      0 
--     1000   1999  58636 **********************************************************************
--     2000   2999  35664 ******************************************
--     3000   3999  10793 ************
--     4000   4999   3672 ****
--     5000   5999   1644 *
--     6000   6999    895 *
--     7000   7999    461 
--     8000   8999    212 
--     9000   9999    142 
--    10000  10999     64 
--    11000  11999     37 
--    12000  12999     16 
--    13000  13999     14 
--    14000  14999      2 
--    15000  15999      6 
--    16000  16999      5 
--    17000  17999      2 
-- Finished stage 'obt-gatekeeper', reset canuIteration.
-- Finished stage 'merylConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting concurrent execution on Mon Apr 24 14:35:14 2017 with 2570.366 GB free disk space (1 processes; 4 concurrently)

    cd trimming/0-mercounts
    ./meryl.sh 1 > ./meryl.000001.out 2>&1

-- Finished on Mon Apr 24 14:35:14 2017 (lickety-split) with 2570.366 GB free disk space
----------------------------------------
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting concurrent execution on Mon Apr 24 14:35:14 2017 with 2570.366 GB free disk space (1 processes; 4 concurrently)

    cd trimming/0-mercounts
    ./meryl.sh 1 > ./meryl.000001.out 2>&1

-- Finished on Mon Apr 24 14:35:14 2017 (lickety-split) with 2570.366 GB free disk space
----------------------------------------
--
-- meryl failed.
--
================================================================================
Don't panic, but a mostly harmless error occurred and Canu stopped.

Canu release v1.5 failed with:
  canu iteration count too high, stopping pipeline (most likely a problem in the grid-based computes)

**Comment by brianwalenz** [comment]
What are the permissions on meryl.sh?  Can you set them manually?  See what 'chmod 000 meryl.sh' and 'chmod 777 meryl.sh' do.

**Comment by brianwalenz** [comment]
The above referenced commit might help, but I suspect there is something else weird on your system (like maybe a VM).
