### ISSUE TITLE
Please provide a `make install` target

### ISSUE THREAD

**Issue by sjackman** [marbl/canu#46]
Please provide a `make install` target to ease installation and separate the compiled binaries from the source code. It would be helpful to install the executables to the directory specified by the environment variables `$(DESTDIR)$(PREFIX)/bin` and documents to `$(DESTDIR)$(PREFIX)/share/doc/canu` to agree with the Linux file hierarchy standard and autotools conventions.

**Comment by sjackman** [comment]
Although a `make install` target could potentially still be useful, I see that all the executables are installed in `Darwin-amd64/bin`. Feel free to close this issue.

**Comment by brianwalenz** [comment]
I'll note that 'Darwin-amd64/bin' path is necessary.  Canu determines, at run time, which architecture it is running on and uses those binaries.

**Comment by sjackman** [comment]
I've created a Homebrew formula for Canu:
Homebrew/homebrew-science#3318

**Comment by brianwalenz** [comment]
You won't get an install target, but you will get a nice message on successful builds with a pointer to the binaries (dc10eff17ad04eae56f4f05032263695aa6bda85) and DESTDIR/PREFIX support (853c5c700971ee7d03a753baf6170148f45e9fae).  If DESTDIR is set, it is installed into DESTDIR/canu/Darwin-amd64/bin.  I'll see if I can work around the runtime binary selection 'quirk'.

**Comment by sjackman** [comment]
Thanks, Brian!

**Comment by scarf** [comment]
so how can i install canu into /opt/bin for example, so i don't have to modify everyone's $PATH to include /opt/src/canu-1.3/Linux-amd64/bin? thx

**Comment by brianwalenz** [comment]
symlink /opt/src/canu-1.3/Linux-amd64/bin/canu into /opt/bin/canu

**Comment by sjackman** [comment]
Install http://linuxbrew.sh
`brew install canu`
