### ISSUE TITLE
Number of corrections for Nanopore R9

### ISSUE THREAD

**Issue by gwaldbieser** [marbl/canu#460]
You suggest multiple rounds of correction for R7 data. Is there any value in multiple rounds of correction for 1D R9 data in the 85% identity range?

**Comment by skoren** [comment]
Nope, recent R9 and R9.4 1D data is high enough quality that one round is sufficient. If you have very low coverage (<20x) it may help rescue some lower quality reads but we've been assembling our R9.4 datasets with just one round.
