### ISSUE TITLE
canu  failed with  unitigging/5-consensus

### ISSUE THREAD

**Issue by chenshixuan** [marbl/canu#462]
canu  failed with  unitigging/5-consensus  ,in this step,   the job is running ,but the output stoped. the 
consensus.$jobid.out like this :    
generatePBDAG()-- align read 190497 (51322/55975) at 12874025-12888527
generatePBDAG()-- aligned             distance=  170 size=14572, 0.011666 < 0.039000

generatePBDAG()-- align read 162083 (51323/55975) at 12874064-12878246
generatePBDAG()-- aligned             distance=   67 size= 4200, 0.015952 < 0.039000

generatePBDAG()-- align read 510894 (51324/55975) at 12874280-12881252
generatePBDAG()-- aligned             distance=  102 size= 7014, 0.014542 < 0.039000

generatePBDAG()-- align read 280776 (51325/55975) at 12874332-12892224
generatePBDAG()-- aligned             distance=  181 size=17977, 0.010068 < 0.039000

generatePBDAG()-- align read 162222 (51326/55975) at 12874350-12878219
generatePBDAG()-- aligned             distance=   68 size= 3881, 0.017521 < 0.039000

generatePBDAG()-- align read 419989 (51327/55975) at 12874549-12887418
generatePBDAG()-- aligned             distance=  130 size=12933, 0.010052 < 0.039000

generatePBDAG()-- align read 225556 (51328/55975) at 12874955-12882724
generatePBDAG()-- aligned             distance=  138 size= 7823, 0.017640 < 0.039000

**Comment by brianwalenz** [comment]
If it's still running, it's not failed.  If it's actually failed and reported an error, feel free to reopen (and report the error).

**Comment by chenshixuan** [comment]
no   the job will remainig running for several months, but the output have no changed .so how to solve it , thank you very much!

**Comment by brianwalenz** [comment]
First, verify that it actually is still running.  Months is exceptionally long for this program, and it's more likely that the machine crashed.

Second, what canu --version are you running?

**Comment by skoren** [comment]
What @bri said, I'll note there here have been significant changes to this code, especially since 1.4. You can try a workaround by editing the ```consensus.sh``` script and adding ```-quick ``` to the command. 

If you can package the failing dataset for us to reproduce the issue locally. Look for the last line like:
```
Working on unitig 2 of length 44268 (64 children)
```
Then run (assuming 2 is the last unitig before the job hangs)
```
utgcns -P tosend.dat -u 2 -G ../*.gkpStore -T ../*.ctgStore 1 -maxcoverage 40 -pbdagcon 
```
and then upload the tosend.dat file using the instruction on the FAQ.

**Comment by brianwalenz** [comment]
Reopen if needed.
