### ISSUE TITLE
negative value of covStat

### ISSUE THREAD

**Issue by bioprojects** [marbl/canu#464]
Dear developers, 

Thank you for developing this great software.
According to a previous advice, I've been using the latest code and the option (overlapper=mhap utgReAlign=true) which is much faster than the default.

But in a dataset, it yielded a complete genome (.contigs.fasta) file which indicates "covStat=-224.05".  What does it mean?  Canu1.4 with the default option yielded a complete genome (.contigs.fasta) file which indicates "covStat=1071.31".

Thanks a lot in advance.

Best wishes,

Koji

Koji Yahara
Senior Research Fellow
Antimicrobial Resistance Research Center
National Institute of Infectious Diseases
Aoba-cho 4-2-1, Higashimurayama-shi, Tokyo 
189-0002 Japan
Tel: +81-42-561-0771 (Ex. 3539)
Fax: +81-42-561-7173

**Comment by skoren** [comment]
Typically, a negative covStat implies the sequence is repetitive (higher than expected coverage). Is this the same dataset and same contig from both assemblies, the only difference being the overlapping parameters? That would be surprising, we'd have to check how the two are placing the reads in the assembly to see why the stat is being affected.

If it is different datasets, it is possible for your genome to have a negative coverage stat if there is some lower coverage genome/plasmid/etc present in the sequencing dataset.

**Comment by bioprojects** [comment]
Thank you very much for your reply. Yes, that's the same dataset.  The only difference is the overlapping parameters (overlapper=mhap utgReAlign=true) and canu binary (1.4 or compiled from the latest source code).  The genome size is about 1M, and it is known to have lots of repetitive sequences.

I uploaded results of the two conditions to https://1drv.ms/u/s!AgviESvFRNpSgyB9ITpdsCdvZCkY 
Could you have a look at it?  Thanks a lot in advance.

Best wishes,

Koji

**Comment by skoren** [comment]
It looks like for the non-mhap you specify ```genomeSize=1.0m``` and for the mhap run you specify ```genomeSize=4.0m```. You can see this from the outputs in ```4-unitigger```:
defaults:
```
CONTIGS (1 tigs) (1347685 length) (1347685 average) (1.35x coverage)
```
mhap:
```
CONTIGS (1 tigs) (1446837 length) (1446837 average) (0.36x coverage)
```

As a result the denominator for the astat is very different and the contig looks repetitive in one case but not the other. Otherwise, the two assemblies look the same.

**Comment by bioprojects** [comment]
Thank you so much!! Sorry I did not notice the change of the genomeSize parameter.  I've confirmed that specifying "genomeSize=1.0m" and "overlapper=mhap utgReAlign=true" for the canu binary compiled from the latest source code yielded a complete assembly with covStat=1446.60.  

Thanks a lot again!!!

Best wishes,

Koji
