### ISSUE TITLE
some questions about canu

### ISSUE THREAD

**Issue by chenshixuan** [marbl/canu#465]
hi ,
I'm not too far into the assembly process,so  I have a question need your help .
Sometimes, however, it makes sense to do the three top-level tasks by hand. This would allow trying multiple unitig construction parameters on the same set of corrected and trimmed reads.
And finally, assemble the output of trimming, twice. why need twice? IN these two step ,how to set the errorate? and what the relationship about the two errorate? the fist one is the half of the second one ?
thank you very much!

**Comment by skoren** [comment]
I'm not sure what you asking regarding the top-level tasks by hand, yes you can do that, the quick start tutorial gives examples on how to do it: http://canu.readthedocs.io/en/latest/quick-start.html#correct-trim-and-assemble-manually

There is only one assembly step (unitigging), before that the corrected reads are trimmed. There are details on the methods in the Canu manuscript. You can also see the explanation of the error rates in the documentation: http://canu.readthedocs.io/en/latest/tutorial.html#error-rates
