### ISSUE TITLE
How to limit the number of nodes that canu can  apply for?

### ISSUE THREAD

**Issue by nottwy** [marbl/canu#469]
Canu will explore the resource of our computing cluster before starting calculate and apply for as much resources as canu can.

But I want to limit the number of nodes that canu can apply for in one time. For example, now canu will apply for any number of nodes in one time that's less than the total number of nodes in our computing cluster. If we have 3500 nodes then canu will apply for i.e. 120, 230, 500 or any other number of nodes that's less than 3500 in one time.

How can I solve this problem?

**Comment by brianwalenz** [comment]
In SGE, you can use qsub's `-tc` option to limit the number of tasks running at one time.  In canu, `gridOptions="-tc 100"` will pass this through to qsub.  Other grids might have a similar option that can be used the same way.

**Comment by nottwy** [comment]
How about slurm?

**Comment by brianwalenz** [comment]
I didn't see anything on a quick scan of the `sbatch` man page.  Post a solution if you find one.

**Comment by nottwy** [comment]
What would happen if I set: `gridEngineArrayOption="-a 1-200"` ?
Would this set the total nodes that canu can apply for to 200?

**Comment by brianwalenz** [comment]
Nope, the -a option tells what tasks in the job to run.  Here, you're telling the grid to run job.sh (whatever it is) on tasks 1 through 200.  This is something Canu needs to have control of.

It's up to the grid scheduler to decide how to run those jobs.  Slurm can limit the number of jobs running at the same time (per user), but this is something the admin would set up.  If it's the admin complaining, tell 'em to set it up properly!  If you're just trying to be nice, don't.  That's the job of the scheduler.  None of the canu jobs are very big; they won't run for days on end for example.

If you _really_ want to take control, you can run with useGrid=remote, which will set up the jobs but not submit them.  You can then run at your leisure.
