### ISSUE TITLE
alignGFA with more cpus ?

### ISSUE THREAD

**Issue by ptranvan** [marbl/canu#470]
Hi,

I am at the final step where alignGFA is running. 

I used the default command to run the whole canu pipeline but by default alignGFA is running with 2 threads. How can I speed up this process ?

**Comment by skoren** [comment]
You can set ```gfaThreads``` to increase the threads. How long is your process running that you consider it a bottleneck? Typically even on a human genome it would finish in a couple of hours on 2 cores.

**Comment by ptranvan** [comment]
I have a 300M specie and it's running since 10 hours. 
Can I restart from the trimmed reads the step `canu -assemble` with adding the option `gfaThreads` ?

**Comment by brianwalenz** [comment]
Remove unitigging/4-unitigger/alignGFA.sh, add the gfaThreads option to the canu command, and restart.  It'll pick up with alignGFA.  Adding -assemble would be safe, but not needed (unless you deleted intermediate files already).

Is it working on unitigs or contigs?  Is there a unitigs.aligned.gfa output?

What do the stats in the *.report, umm, report?

**Comment by ptranvan** [comment]
it works thanks.
