### ISSUE TITLE
Canu crashes at error correction stage

### ISSUE THREAD

**Issue by PedroBarbosa** [marbl/canu#472]
Hello,

I'm trying to run canu on a local machine with 4 cpus (16cores each) with 1Tb of RAM.  For now, I'm just concerned to see how error correction step goes on my dataset:
`canu -correct -p ec_outCov90_minCov4 -d first_ec genomeSize=0.9g -s specs_file.txt -pacbio-raw $(cat allSMRT.txt) &> canu.stdout`

It fails to finish the job, as falcon_sense and generateCorrectionLayouts complained about some some missing libs.

Canu tail stdout:

`job correction/2-correction/correction_outputs/0510.fasta FAILED.
job correction/2-correction/correction_outputs/0511.fasta FAILED.
 job correction/2-correction/correction_outputs/0512.fasta FAILED.

Don't panic, but a mostly harmless error occurred and Canu stopped.

Canu release v1.5 failed with:
  canu iteration count too high, stopping pipeline (most likely a problem in the grid-based computes)`

On the 2-correction directory, last file being written:

`cat correctReads.000512.out
Running job 443 based on command line options.
/opt/tools/pacbioTools/canu-1.5/Linux-amd64/bin/generateCorrectionLayouts: /opt/tools/anaconda3/lib/libgomp.so.1: version `GOMP_4.0' not found (required by /opt/tools/pacbioTools/canu-1.5/Linux-amd64/bin/generateCorrectionLayouts)
/opt/tools/pacbioTools/canu-1.5/Linux-amd64/bin/generateCorrectionLayouts: /opt/tools/anaconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /opt/tools/pacbioTools/canu-1.5/Linux-amd64/bin/generateCorrectionLayouts)
Read layout generation failed.
mv: cannot stat './correction_outputs/0443.fasta': No such file or directory
`

On the correction_outputs:

`cat 0512.err
/opt/tools/pacbioTools/canu-1.5/Linux-amd64/bin/falcon_sense: /opt/tools/anaconda3/lib/libgomp.so.1: version `GOMP_4.0' not found (required by /opt/tools/pacbioTools/canu-1.5/Linux-amd64/bin/falcon_sense)
/opt/tools/pacbioTools/canu-1.5/Linux-amd64/bin/falcon_sense: /opt/tools/anaconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /opt/tools/pacbioTools/canu-1.5/Linux-amd64/bin/falcon_sense)
`

I believe it may be easy to install both, but I would like to know which commands I should follow to restart from where I left and avoid running mhap again.
Thanks in advance,
Pedro Barbosa

**Comment by brianwalenz** [comment]
Easy!  Just restart with the same canu command.  It'll detect the previously computed results and not redo them.

You can test if you have the libraries installed by running 'correctReads.sh 1', 'correctReads.sh 2', etc.  Also check that the 'utgcns' program runs - this is the program that usually fails to find libraries.

Did you compile on the same machine?  Which compiler?

**Comment by PedroBarbosa** [comment]
I think I compiled canu with the default gcc version on the server: 
gcc version 5.4.0

Now, I just updated conda libs with "conda install libgcc" to the latest:  
libgcc                    5.2.0 

I run the same canu command as you suggested, and It appears to be running smoothly :)
Last 15 modified files in correction_outputs:

> 2017-04-2716:24:42.945789591` +0100 ./0279.fasta.WORKING
2017-04-27 16:24:42.653771596 +0100 ./0280.fasta.WORKING
2017-04-27 16:24:41.425695916 +0100 ./0278.fasta.WORKING
2017-04-27 16:17:45.340220459 +0100 ./0280.err
2017-04-27 16:17:45.144208559 +0100 ./0277.fasta
2017-04-27 16:17:45.132207830 +0100 ./0277.dump.success
2017-04-27 16:11:59.991498808 +0100 ./0279.err
2017-04-27 16:11:59.603475869 +0100 ./0276.dump.success
2017-04-27 16:11:59.563473504 +0100 ./0276.fasta
2017-04-27 16:07:06.546482914 +0100 ./0278.err
2017-04-27 16:07:06.314469778 +0100 ./0275.fasta
2017-04-27 16:07:06.130459360 +0100 ./0275.dump.success
2017-04-27 15:52:12.983741714 +0100 ./0277.err
2017-04-27 15:52:12.575714828 +0100 ./0273.fasta
2017-04-27 15:52:12.531711929 +0100 ./0273.dump.success
