### ISSUE TITLE
Can canu be used to assemble pacbio targeted sequencing reads?

### ISSUE THREAD

**Issue by joyceil** [marbl/canu#476]
Hi,

We have some PacBio RSII targeted sequencing reads that target certain regions of an animal genome including the MHC region.  Can canu be used to assemble these reads into long contigs with reasonable accuracy?  If so, should some of the parameters be modified?  

Thank you!

**Comment by brianwalenz** [comment]
I can't think of anything special I'd set for a first assembly.

Set genomeSize to your best guess of the combined size of the regions.  You can probably be too high by an order of magnitude with no real problem; but too low would be somewhat bad.  This impacts how corrected reads are computed, and how many corrected reads are computed.  

Once you get a feel for how they assemble, correctedErrorRate can be varied to refine how much assembly is done.

Check the GFA outputs.  If they're showing a big tangle, try dropping correctedErrorRate a bit.  If unitigs look a lot like contigs, you've got a clean trusted assembly (and if they're big too, well, excellent).

**Comment by fbemm** [comment]
If it Pb CCS data tune error rates towards the mean error of the reads. We normally select only Q20 CCS reads and than set the error rate to 1%.

**Comment by joyceil** [comment]
Hi Brian,

Thank you very much for your help.  I did some initial trials and found the
final assembly size much smaller than the input.  I plan to tweak the
parameters but have not done much about it due to travels. I will update
the forum if I found something interesting.

Thanks again,
Joyce

Joyce

**Comment by ViriatoII** [comment]
Hi Joyceil,
3 years later I ask: did you find anything interesting?

Cheers,
