### ISSUE TITLE
Very long nanopore "reads" causing falconsense correction failures

### ISSUE THREAD

**Issue by eernst** [marbl/canu#478]
There are a number of such nanopore reads > 1 Mpb in my dataset causing multiple correction partitions to fail with the following errors:

```
falcon_sense: falcon_sense/libfalcon/falcon.C:391: FConsensus::consensus_data* FConsensus::get_cns_from_align_tags(FConsensus::align_tags_t**, uint32, uint32, uint32, uint32): Assertion 't_len < max_len' failed.

Failed with 'Aborted'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::102 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
falcon_sense/libfalcon/falcon.C::391 in _ZN10FConsensus23get_cns_from_align_tagsEPPNS_12align_tags_tEjjjj()
falcon_sense/libfalcon/falcon.C::699 in _ZN10FConsensus18generate_consensusESt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS6_EEjjdjj()
falcon_sense/falcon_sense.C::113 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
```

```
Aborted                 (core dumped) cat 0050.debug.correctionlayout.read490347.txt | /usr/local/src/canu-dev/Linux-amd64/bin/falcon_sense --min_idt 0.5 --min_len 1000 --max_read_len 4194302 --min_ovl_len 500 --min_cov 0 --n_core 64 > 0050.debug.falconsense.read490347.out 2> 0050.debug.falconsense.read490347.err
```
I've isolated an example of a correction read bundle (read# and data#s) with a 2 Mbp read that causes the error. If you'd like to take a look, the read bundle is here:
https://drive.google.com/file/d/0B81ZEZ28zd85SEFVZXVUbFVCS00/view?usp=sharing

It seems likely that the read is a chimera, possibly of several molecules passing through the pore in succession, but haven't confirmed this.

**Comment by skoren** [comment]
I think this is a bug with a read exactly the maximum read length (I presume it was longer and was trimmed by Canu). By default, we allocate more space than the read to correct because nanopore reads typically get longer during correction but the maximum is still set to be the maximum read length. Thus if this read increases in size during correction, the assert will fail. I'm testing the fix now.

**Comment by eernst** [comment]
The longest read in that bundle is only 2097162, which is much shorter than the maximum of 4194302. If the read to be corrected is a chimera, is it possible that the alignment is forcing the consensus to be much larger as a result?

Something like:

```
Alignment:
     <-----|------->
<------>   <------------>
  <--->        <--------------->

Consensus:
<----------|------------------>
```

If this is the case the chimera will hopefully be picked up in the subsequent trimming stage, but could cause significant corrected read size inflation with increasing real and artifactual read lengths.

**Comment by skoren** [comment]
No, the max read length defined in the assembler is 2097162. When the call to falcon_sense is made it allocates extra space by asking for 2*longest read (4194302). However, in this case it sees 4194302 > 2097162 and resets back to 2097162 causing the crash. It shouldn't reset to 2097162 is the fix.

**Comment by conchoecia** [comment]
I don't mean to hijack this thread, but I think @eernst's comment about the chimeric reads highlights a problem with building unitigs using nanopore data. For example, I have over one thousands reads in my dataset that are 100kb+, but when I get to the assemble stage (`BEGIN ASSEMBLY cd unitigging... In gatekeeper store... found x reads...`) the longest corrected reads fall into a much shorter length bracket:

```
--    44000  44999      0
--    45000  45999      3
--    46000  46999      0
--    47000  47999      3
--    48000  48999      2
--    49000  49999      1
--    50000  50999      2
```

Maybe I don't understand how the corrected reads are constructed up to this point, but if these are the reads that feed into the next stages of ovlStore then it seems like a lot of data in the longest reads is lost? I'm happy to take this discussion offline or elsewhere if you'd like.

**Comment by skoren** [comment]
@conchoecia reads are trimmed by coverage and support from other data (see Canu paper for details) and then trimmed post-correction to identify likely chimera/etc so there isn't an issue building unitigs from nanopore data. There is a lot of upstream checking of the data to make sure it is trustable to build a unitig.

As for why your 100kb reads get trimmed, have you tried mapping any of them to confirm they are real. If they have noise/erroneous sequence they would get trimmed.

**Comment by conchoecia** [comment]
@skoren thanks for your input. I just noticed the bit about internal trimming around adapters, et cetera. There is no reference to map to so I'm waiting for this assembly to finish to start checking for chimeric reads. I'll take my comments offline now-

Congrats on the publication in BMC genomics by the way!

**Comment by skoren** [comment]
I confirmed that correctly allowing extra space for the long reads does not crash. You can either update to get my bug fix or you can edit the code in 
```
src/stores/gkStore.H:
 61 #define AS_MAX_READLEN_BITS        21
```
to
```
 61 #define AS_MAX_READLEN_BITS        25
```
That should make the maximum read length >30mb and none of your long reads would be truncated on input. They may still not get corrected if they are not actual reads but are noise/chimera.

**Comment by eernst** [comment]
Thanks Sergey!

Setting AS_MAX_READLEN_BITS to anything > 22 is causing a compilation error:
```
g++ -o /mnt/grid/martienssen/hpc/home/data/eernst/src/canu-dev/Linux-amd64/obj/libcanu.a/overlapInCore/liboverlap/Binomial_Bound.o -c -MD -I/sonas-hs/martienssen/hpc/home/eernst/include -L/sonas-hs/martienssen/hpc/home/eernst/lib -Wl,-rpath=/sonas-hs/martienssen/hpc/home/eernst/lib -D_GLIBCXX_PARALLEL -pthread -fopenmp -fPIC -Wall -Wextra -Wno-write-strings -Wno-unused -Wno-char-subscripts -Wno-sign-compare -Wformat -g3 -O4 -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer -DLIBBACKTRACE -I/mnt/grid/martienssen/hpc/home/data/eernst/src/canu-dev/src -IAS_UTL -Istores -Istores/libsnappy -Ialignment -Iutgcns/libNDalign -Iutgcns/libcns -Iutgcns/libpbutgcns -Iutgcns/libNDFalcon -Iutgcns/libboost -Imeryl/libleaff -IoverlapInCore -IoverlapInCore/libedlib -IoverlapInCore/liboverlap -Ifalcon_sense/libfalcon overlapInCore/liboverlap/Binomial_Bound.C
overlapInCore/liboverlap/Binomial_Bound.C: In function 'void Initialize_Match_Limit(int32*, double, int32)':
overlapInCore/liboverlap/Binomial_Bound.C:180:26: error: 'sl' was not declared in this scope
   double  vl = ml[e-1] + sl;
                          ^
make: *** [/mnt/grid/martienssen/hpc/home/data/eernst/src/canu-dev/Linux-amd64/obj/libcanu.a/overlapInCore/liboverlap/Binomial_Bound.o] Error 1
make: *** Waiting for unfinished jobs....
```

I continued the assembly with your fix and no change to AS_MAX_READLEN_BITS, and cleared the correction stage without further issues.

**Comment by brianwalenz** [comment]
AS_MAX_READLEN_BITS 23 and 24 now work.  Larger values will work soon-ish.
