### ISSUE TITLE
Canu release v1.5 failed with: failed to generate configuration for building overlap store: Can't open './1-overlapper/ovljob.files': No such file or directory

### ISSUE THREAD

**Issue by ArizonaGenomicsInstitute** [marbl/canu#479]
I'm having a problem running canu release 1.5. The command used is `canu -d /rsgrps/rwing/canu_assemblies/coarctata -p coarall corMhapSensitivity=normal corOutCoverage=200 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" genomeSize=771m minReadLength=1000 minOverlapLength=1000 gridEngineThreadsOption="-l select=1:ncpus=THREADS:mem=100gb" gridEngineMemoryOption="-l walltime=24:00:00" gridOptions="-W group_list=oge -q standard" -pacbio-raw /rsgrps/rwing/canu_assemblies/coarctata/input/Ocoar_subreads_all.fa`

It looks like the first step completed, canu.01.out doesn't show any errors.

Here are the latest log files:

**1493756607_i0n18_14804_canu:** 
```
corMhapSensitivity=normal
corOutCoverage=200
batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50
genomeSize=771m
minReadLength=1000
minOverlapLength=1000
gridEngineThreadsOption=-l select=1:ncpus=THREADS:mem=100gb
gridEngineMemoryOption=-l walltime=24:00:00
gridOptions=-W group_list=oge -q standard
canuIteration=1
```

**1493756623_i0n18_14996_ovStoreBuild:** 
```
Canu v1.5 (+0 commits) r0 .

Current Working Directory:
/rsgrps/rwing/canu_assemblies/coarctata

Command:
/rsgrps/rwing/opt/canu-1.5/Linux-amd64/bin/ovStoreBuild \
  -G ./coarall.gkpStore \
  -O ./coarall.ovlStore \
  -M 4-16 \
  -config ./coarall.ovlStore.BUILDING/config \
  -L ./1-overlapper/ovljob.files
```

**canu.out -> canu-scripts/canu.02.out:**
```
-- Canu release v1.5
-- Detected Java(TM) Runtime Environment '1.8.0_131' (from 'java').
-- Detected gnuplot version '4.2 patchlevel 6 ' (from 'gnuplot') and image format 'png'.
-- Detected 28 CPUs and 189 gigabytes of memory.
-- Detected PBSPro 'PBSPro_13.0.2.153173' with 'pbsnodes' binary in /cm/shared/apps/pbspro/13.0.2.153173/bin/pbsnodes.
-- Detecting PBSPro resources.
-- 
-- Found 313 hosts with  28 cores and  188 GB memory under PBSPro control.
-- Found   1 host  with  48 cores and 2019 GB memory under PBSPro control.
-- Found   1 host  with  28 cores and  252 GB memory under PBSPro control.
-- Found  14 hosts with  28 cores and  251 GB memory under PBSPro control.
-- Found   2 hosts with 336 cores and 2105 GB memory under PBSPro control.
--
-- Run under grid control using   25 GB and   4 CPUs for stage 'meryl'.
-- Run under grid control using   25 GB and   4 CPUs for stage 'mhap (cor)'.
-- Run under grid control using   12 GB and   4 CPUs for stage 'overlapper (obt)'.
-- Run under grid control using   12 GB and   4 CPUs for stage 'overlapper (utg)'.
-- Run under grid control using   20 GB and   4 CPUs for stage 'falcon_sense'.
-- Run under grid control using    4 GB and   1 CPU  for stage 'ovStore bucketizer'.
-- Run under grid control using   16 GB and   1 CPU  for stage 'ovStore sorting'.
-- Run under grid control using    8 GB and   4 CPUs for stage 'read error detection'.
-- Run under grid control using    2 GB and   1 CPU  for stage 'overlap error adjustment'.
-- Run under grid control using   87 GB and  14 CPUs for stage 'bogart'.
-- Run under grid control using    8 GB and   4 CPUs for stage 'GFA alignment and processing'.
-- Run under grid control using   25 GB and   4 CPUs for stage 'consensus'.
--
-- Generating assembly 'coarall' in '/rsgrps/rwing/canu_assemblies/coarctata'
--
-- Parameters:
--
--  genomeSize        771000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0450 (  4.50%)
--
--
-- BEGIN CORRECTION
--
-- Found 251 mhap overlap output files.
-- Finished stage 'cor-mhapCheck', reset canuIteration.
----------------------------------------
-- Starting command on Tue May  2 13:23:43 2017 with 6205.708 GB free disk space

    cd correction
    ./coarall.ovlStore.BUILDING/scripts/0-config.sh \
    > ./coarall.ovlStore.BUILDING/config.err 2>&1
    

-- Finished on Tue May  2 13:23:43 2017 (lickety-split) with 6205.708 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:
================================================================================
Don't panic, but a mostly harmless error occurred and Canu stopped.

Disk space available:  6205.708 GB

Last 50 lines of the relevant log file (correction/coarall.ovlStore.BUILDING/config.err):

Max processes per user limited to 772481, no increase possible.

Max open files limited to 65536, no increase possible.

Can't open './1-overlapper/ovljob.files': No such file or directory

Canu release v1.5 failed with:
  failed to generate configuration for building overlap store


You may want to consider changing your batch submission script as follows to speed up your job run next time:

#PBS -l select=1:ncpus=16:mem=1gb
#PBS -l place=free:shared
#PBS -l walltime=00:05:00

Your group oge has been charged 00:00:19 for 16 cpus.
You previously had 115086:05:52.  You now have 115086:00:48 remaining for the queue oc_standard
```

**Comment by brianwalenz** [comment]
This looks like a transient failure.  It's failing to find file '1-overlapper/ovljob.files'.  This is supposed to be created after all the overlap jobs have been verified to have completed.  In fact, the canu.02.out log line 'Found 251 mhap overlap output files' is printed just before this file is created.

ovljob.files is just a list of the ovb files here: `ls 1-overlapper/results/*.ovb* > 1-overlapper/ovljob.files` should recreate it.  Or, remove 1-overlapper/mhap.files and restart canu - it should verify the outputs again, and (re)create these files.  If you run with 'useGrid=remote' you can run this on the head node; it'll prompt you to submit the next step to the grid, at which time just restart canu without the 'remote' option.

You can stick those big grid options into ~/.canu or $bin/canu.defaults.

**Comment by dcopetti** [comment]
Hi,
I am having the same issue as AGI (we are colleagues trying to have Canu running) and, after adding remote to the command I got:
```
[...]
-- BEGIN CORRECTION
--
-- Found 367 mhap overlap output files.
-- Finished stage 'cor-mhapCheck', reset canuIteration.
----------------------------------------
-- Starting command on Wed May  3 06:35:32 2017 with 6205.709 GB free disk space

    cd correction
    ./coarDC.ovlStore.BUILDING/scripts/0-config.sh \
    > ./coarDC.ovlStore.BUILDING/config.err 2>&1
-- Finished on Wed May  3 06:36:42 2017 (70 seconds) with 6205.708 GB free disk space
----------------------------------------
-- Finished stage 'cor-overlapStoreConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
Please run the following commands to submit jobs to the grid for execution using 4 gigabytes memory and 1 threads:
  /rsgrps/rwing/canu_assemblies/coarctata/dariostest/correction/coarDC.ovlStore.BUILDING/scripts/1-bucketize.jobSubmit.sh
When all jobs complete, restart canu as before.
```
So I run the shell as
`sh /rsgrps/rwing/canu_assemblies/coarctata/dariostest/correction/coarDC.ovlStore.BUILDING/scripts/1-bucketize.jobSubmit.sh`
but got the error:
`/rsgrps/rwing/canu_assemblies/coarctata/dariostest/correction/coarDC.ovlStore.BUILDING/scripts/1-bucketize.jobSubmit.sh: line 3: ./scripts/1-bucketize.jobSubmit.out: No such file or directory`

I still re-run the whole command (no=remote) as you suggested, it is queued now.

**Comment by dcopetti** [comment]
It eventually run, and I get this in the canu.out:
```
ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:
================================================================================
Don't panic, but a mostly harmless error occurred and Canu stopped.
Disk space available:  5772.103 GB
Last 50 lines of the relevant log file (correction/coarDC.ovlStore.BUILDING/logs/3-index.err):
ERROR: Segment 170 data  not present (./0170)
ERROR: Segment 170 info  not present (./0170.info)
ERROR: Segment 170 index not present (./0170.index)
[...]
ERROR: Segment 185 data  not present (./0185)
ERROR: Segment 185 info  not present (./0185.info)
ERROR: Segment 185 index not present (./0185.index)
ERROR: 185 segments, out of 185, failed.
Failure.
Canu release v1.5 failed with:
  failed to build index for overlap store
```
nothing was written in the /correction folder, the rest of the logs seem fine.

**Comment by skoren** [comment]
This again seems like an FS error. It is indicating the previous steps (```2-sort.sh```) failed to generate data but Canu should check for this output before running ```3-index.sh``` (your log higher than this should have something like:
```
-- BEGIN CORRECTION
--
-- Overlap store sorter finished.
-- Finished stage 'cor-overlapStoreSorterCheck', reset canuIteration.
----------------------------------------
```

What is the contents of your ```coarDC.ovlStore.BUILDING``` folder and the output of one of the ```coarDC.ovlStore.BUILDING/logs/2-sort.*.out``` files?

**Comment by dcopetti** [comment]
Correct, the part just above in the log file says:
```
-- BEGIN CORRECTION
--
-- Overlap store sorter finished.
-- Finished stage 'cor-overlapStoreSorterCheck', reset canuIteration.
----------------------------------------
-- Starting command on Wed May  3 07:32:19 2017 with 5772.103 GB free disk space
    cd correction/coarDC.ovlStore.BUILDING
    ./scripts/3-index.sh \
    > ./logs/3-index.err 2>&1
-- Finished on Wed May  3 07:32:20 2017 (1 second) with 5772.103 GB free disk space
```
The coarDC.ovlStore.BUILDING folder has plenty of NNNN, NNNN.info, NNNN.index, NNNN.evalueLen, ovB_coarDC.o681503.NNN files, /bucketNNNN fodlers, a 2-sorter.success file (empty). That should be all I think. There is no 2-sort file instead:
```
[dcopetti@login2 coarDC.ovlStore.BUILDING]$ cd logs/
[dcopetti@login2 logs]$ ls -lrth
total 32K
-rw-rw-r-- 1 dcopetti oge 27K May  3 07:32 3-index.err
```

**Comment by skoren** [comment]
Are the 2-sort.out files present in scripts (rather than logs) folder? Do you see the files that the 3-index.sh script was complaining about (```0170.*``` and ```0185.*```)?

**Comment by dcopetti** [comment]
yes, they are in /scripts.
the .sh says:
```
#!/bin/sh
qsub -j oe \
  -l walltime=24:00:00 -l select=1:ncpus=1:mem=100gb -W group_list=oge -q standard \
  -N "ovS_coarDC" \
  -J 1-185 \
  ./scripts/2-sort.sh  \
> ./scripts/2-sort.jobSubmit.out 2>&1
```

the .out says:
`681506[].head1.cm.cluster`

Yes, the 0170.* files are all binaries and all in /correction/coarDC.ovlStore.BUILDING

**Comment by arizonagenomicsinstitute** [comment]
Where are we at in trouble-shooting this?
Thanks

**Comment by skoren** [comment]
I'm not sure there is anything to change within Canu here. It seems like files which are present are not being loaded intermittently on the system, causing errors. To get past the error you can try running the 3-index.sh script manually in the ```correction/coarDC.ovlStore.BUILDING``` folder on a head node to see if it completes. Then, re-run the canu command to let it resume but you'll likely encounter other errors due to these FS issues later in the run. For that, you could try switching to the serial overlap store ```ovsMethod=sequential``` which is slower but less I/O intensive. I'd also suggest checking if there were networking/FS issues at the time of the error on the system.

**Comment by dcopetti** [comment]
I don't have the shell script in that folder, nor anywhere else:
```
[dcopetti@login2 coarDC.ovlStore.BUILDING]$ ls -lrth *sh
ls: cannot access *sh: No such file or directory
[dcopetti@login2 coarDC.ovlStore.BUILDING]$ locate 3-index.sh
[dcopetti@login2 coarDC.ovlStore.BUILDING]$
```
I will notify our sys admin people to inspect the FS and network, thanks!

**Comment by brianwalenz** [comment]
3-index.sh will be in the same directory as 2-sort.sh -- coarDC.ovlStore.BUILDING/scripts/.  If it doesn't exist, something very odd is going on; those scripts are all created at the same time.

Is this in 'scratch' space that purges unused files?  (If so, my sympathy.)  I can't think of any other explanation for this number of missing files.

Some random hints:

Possibly, renaming 'scripts' to, say, 'scripts-old' will allow canu to recreate the scripts.  It'll then try to resume where it left off.

If you want to try the SGE cluster, rsync the whole thing over.  Nothing in there should be path dependent.

Removing the whole coarDC.ovlStore.BUILDING directory will let canu restart the whole store building process again.  Overlaps don't need to be recomputed.  This should be a last resort, since you're one command away from finishing!

**Comment by dcopetti** [comment]
The sys admin says:

> We are not aware of any filesystem or network issues and we have not received complaints from other users. Do you know if there is some sort of requirement in canu for a local file system (ie ext4)?

Chandler and I are working on running manually the scripts, more updates soon.

**Comment by skoren** [comment]
We run Canu on an Isilon system over NFS as well as a GPFS without issue. The parallel overlap store building is I/O intensive so if it is overloading your network bandwidth perhaps files are being reported missing due to timeout or a subset of your nodes have network connectivity issues. The error seems to be outside of Canu's control as running the same script by hand completes but failed with missing file errors before. Since you didn't create those missing files, the system calls to open files were failing, implying a system issue.

I expect you might encounter the same error in the trimming/unitigging steps when building the overlap store. If that is the case, you can try to switch to the sequential store build to reduce I/O load.

**Comment by brianwalenz** [comment]
Fantastic!  I'm going to close this so we can forget the suffering.  Open new issues as needed.

I didn't really see any fixes other than restarting over and over.  Write back if you did something other than that.

**Comment by dcopetti** [comment]
OK.
I tried Brian's option of renaming the scripts folder and re-starting the whole command, I still get to "failed to build index for overlap store" with the 3 .sh files in the scripts folder.

**Comment by skoren** [comment]
Brian's option was listed as last resort if you couldn't find the 3-index.sh script. Once you've built a store you won't be able to build it again (intermediate files are removed). Use the store you already finished building (where you ran 3-index.sh to the end), leaving it named coarDC.ovlStore.BUILDING, and restart Canu.

**Comment by cement-head** [comment]
You have to run the script in a directory ONE level UP, then it will work.  There is no error.
