### ISSUE TITLE
Could not reserve enough space for 67108864KB object heap

### ISSUE THREAD

**Issue by mw55309** [marbl/canu#480]
Hi

So my mhap overlapper jobs are failing with:

Starting mhap precompute.

Error occurred during initialization of VM
Could not reserve enough space for 67108864KB object heap
Mhap failed.

The submit job has the correct resources:

-l h_vmem=4g -pe sharedmem 16 

(this asks for 16 * 4Gb cores which is 64Gb)

The Java command is then:

/exports/applications/apps/SL7/java/jdk1.8.0_74/bin/java -d64 -server -Xmx65536m \
  -jar  $bin/mhap-2.1.2.jar  \
  --repeat-weight 0.9 --repeat-idf-scale 10 -k 16 \
  --num-hashes 768 \
  --num-min-matches 2 \
  --ordered-sketch-size 1536 \
  --ordered-kmer-size 12 \
  --threshold 0.78 \
  --filter-threshold 0.000005 \
  --num-threads 16 \
  -f  ../../0-mercounts/canutest3.ms16.frequentMers.ignore.gz  \
  -p  ./$job.input.fasta  \
  -q  .  \
&& \
mv -f ./$job.input.dat ./$job.dat

So asking for 65536m and 16 threads - kind of OK so far.

But it looks to me like "67108864KB object heap" is bigger than the 64Gb requested?

Maybe there is some maths here I'm getting wrong?

Cheers
Mick

**Comment by brianwalenz** [comment]
The numbers are using K=1024.

Will it run if you either increase the grid memory request (4.1g?  5g?) or decrease the java size (64000m?  60000m?)?

Are these 64gb machines?  I'm not a java person, so turn to google for this stuff.  I find a lot of reports that this is indicating not enough physical RAM.  Restricting mhap to 48gb would work in that case.

**Comment by skoren** [comment]
Essentially, what @brianwalenz said. The JVM reserves all the Xmx memory at the start of the process and the error means the machine has insufficient memory to reserve it. The other thing to check is that the number jobs actually scheduled on the machine matches what you expect based on the resources. On our cluster h_vmem is not consumable so could lead to over-scheduling the jobs (if you have >16 cores but 64gb).

**Comment by mw55309** [comment]
Great, so let's see what the IT guys say.

So how do I limit mhap?

Something to do with 

gridOptionsCORMHAP <string=unset>

??

**Comment by brianwalenz** [comment]
Nope, mhapMemory=48 would limit it to exactly 48.  mhapMemory=32-48 (what I use) would let canu pick a size between 32 and 48 based on the machines in the grid.  mhapThreads works the same way, but for CPUs.

The various gridOptions settings are to pass in extra qsub options specific to that module.  An example would be needing to request a high-memory queue for these jobs, e.g., "gridOptions=-q highmemory.q".

**Comment by brianwalenz** [comment]
Sergey reminded me that you'll probably need to override the resources canu is requesting, too.

mhapMemory=48
gridOptionsCorMhap="-l h_vmem=4g -pe sharedmem 16"

Will tell canu to configure mhap to use 48gb memory, but then force the qsub to request 64gb memory.  The qsub command should have the '-l h_vmem' options listed twice.  The first one will be from canu (requesting 3*16 = 48g) and the second one from the gridOptionsCorMhap.
