### ISSUE TITLE
Short Read Issue

### ISSUE THREAD

**Issue by LianaKafetzopoulou** [marbl/canu#482]
I am aware that Canu is designed for reads >1000 but thought to ask just in case. The method I use to prep my samples generally produces reads with shorted length than that unfortunately so they fall in the <1000bp and are considered too short and get ignored. Is there any way to overcome this and get a de novo assembly with Canu even though reads are short?

**Comment by skoren** [comment]
There is on option to reduce the overlap and read length:
http://canu.readthedocs.io/en/latest/parameter-reference.html#global-options

You could try ```minOverlapLength=200 minReadLength=500``` or similar.

**Comment by LianaKafetzopoulou** [comment]
Awesome thanks very much for the quick responce! Will try right away!

**Comment by LianaKafetzopoulou** [comment]
Solved, thanks!
