### ISSUE TITLE
hang at cd trimming/1-overlapper     ./overlap.sh 1 > ./overlap.000001.out 2>&1

### ISSUE THREAD

**Issue by bluessherpa** [marbl/canu#484]
Hi,

I've been trying to run on my Mac (64 GB RAM 1.4 TB free on drive) Quad core Xeon) 10.12.4.  I first tried to run with a small data set (200MB total) and it did ok. Then tried to run over the weekend with nano corrected seq and it hung up on the above command.  So I retried with a smaller data set and it hung up on the same spot.  

Any ideas?
Thanks

**Comment by skoren** [comment]
As long as the job is getting CPU (e.g. in top) then it is OK. This would be the slowest part of the assembly, especially with nanopore data, so you can let it keep running. You can also try the experimental ```overlapper=mhap utgReAlign=true``` option if you are using Canu 1.5 (see https://github.com/marbl/canu/releases/tag/v1.5 for details)
