### ISSUE TITLE
Extract a single mhap output from all the [0-9].mhap files

### ISSUE THREAD

**Issue by PedroBarbosa** [marbl/canu#487]
Hello,

Is it possible to get a single mhap output file from the overlapping stage with original read names ? I'd like to input those to miniasm.

Best,
Pedro Barbosa

**Comment by skoren** [comment]
You should use the overlap store which will convert back to appropriate read IDs and give you all overlaps joined together. Take a look at the ovStoreDump command's paf output format. Something like:
```
gatekeeperDumpFASTQ -fasta -nolibname -G *.gkpStore -o reads
ovStoreDump -unique -d -paf -G *.gkpStore -O *.ovlStore |gzip -c > reads.paf.gz
```
should give you inputs for miniasm (reads.fasta and reads.paf.gz).

**Comment by PedroBarbosa** [comment]
Thank you @skoren , pretty useful tool. However, I'm still unable to recover the original read id.

`ovStoreDump -unique -d -paf -G ec_outCov90_minCov4.gkpStore -O ec_outCov90_minCov4.ovlStore/ | head `

> 1         9473    1915    9192  -       2         7516     285    7503  4294966285        7277     255
1         9473     137    1608  +       106914    4602    2862    4280  4294967098        1471     255
1         9473    6407    6469  +       603386    3919    2075    3157  4294967290          62     255
1         9473    2437    6293  +       968119    3849     128    3836  4294966626        3856     255
1         9473       0    8901  +       1084988  11309    2700   11296  4294966112        8901     255
1         9473      12    8606  -       1084989  11201     275    8664  4294966130        8594     255
1         9473     339    8713  +       1084990  10999    2919   10986  4294966213        8374     255
1         9473    5450    6141  -       1318683   5442     141     813  4294967203         691     255
1         9473      60    1772  +       1647386   8047    6306    7965  4294967061        1712     255
1         9473      12    1758  -       1647389   6763      94    1813  4294967052        1746     255

**Comment by brianwalenz** [comment]
There's a map from ID to name in *gkpStore/readNames.txt.

**Comment by skoren** [comment]
I'll add that using my commands above you don't need the original id. The fasta file is generated with internal ids consistent with thouse output by the overlap store. Pass both the fasta and paf files to run miniasm. We have done this on several occasions without issues.
