### ISSUE TITLE
Quiver

### ISSUE THREAD

**Issue by Subhi** [marbl/canu#488]
I ran canu assembly. 
I want to run assembly polishing step using Quiver, which output file should I use as a reference for can, the correctedReads.fasta file or asm.contigs.fasta or the .trimmedReads.fasta

Please help me with this.

**Comment by skoren** [comment]
You should use asm.contigs.fasta, this is the primary output of the assembler. The other files are corrected reads not the assembly. You could also include entires from the asm.unassembled.fasta file with > 1 read but that is optional.
