### ISSUE TITLE
Figuring what went wrong when there is no error message

### ISSUE THREAD

**Issue by mw55309** [marbl/canu#489]
Hello (again)

Sorry....

So I have no error messages but canu is not running and it should be.

The latest canu.out (which points to canu-scripts/canu.03.out) simply contains:

 -- Canu snapshot v1.4 +192 changes (r8187 ae428fcf280f61984f21abc32dfe16030cb56ea5)

The last bit of "work" done was in:

correction/0-mercounts/

In canutest5.ms16.estMerThresh.err I have

RAW MER COUNTS:
  distinct:   1119455306 (different kmer sequences)
  unique:      524761591 (single-copy kmers)
  total:      2977367443 (kmers in sequences)

Guessed X coverage is 96
Set maxCount to 38 (105812 kmers), which will cover 99.76% of distinct mers and 95.75% of all mers.
Average number of kmers between count 13 and 64 is 8169073
Found break in kmer coverage at 3390
Set maxCount to 3389 (1 kmers), which will cover 100.02% of distinct mers and 99.94% of all mers.

I also have canutest5.ms16.estMerThresh.out:
3389

(I also have a meryl.1.out which looks fine).

So.... any ideas?  That's the last thing I can see

Cheers
Mick

**Comment by mw55309** [comment]
On restarting, file "meryl.success" was created, which wasn't there previously.

**Comment by brianwalenz** [comment]
No ideas why canu.out is (apparently) truncated.

The flow here is:

1. 'canu' sets up and submits a meryl.sh job to the grid
2. meryl.sh computes kmers and thresholds
3. 'canu' resumes, checks the output, and creates meryl.success if all is well

So, the mystery is why was the original attempt at running step 3 aborted or killed.  Possibly there are grid logs telling what happened.

**Comment by mw55309** [comment]
Yeah so given all the hacks I have had to make (;-)) perhaps the problem is with point (3)?

What is the trigger for canu to resume?  What might make it not?

**Comment by brianwalenz** [comment]
It seems to have resumed, but stopped just after reporting the version number.  Right after that it tries to detect and run java (function checkJava() in Defaults.pm) and this always prints something.  My only guess is that running java caused the whole grid job to get killed with no warning or logging.

Canu uses SGE's hold_jid option to run jobs only after other jobs finish.  The first canu (flow step 1) will submit meryl.sh (flow step 2) to the grid, then submit another canu job (flow step 3) that will run only after the meryl job finishes.  The first canu then exits.
