### ISSUE TITLE
canu failed with 'can't open' corjob.files

### ISSUE THREAD

**Issue by laurencowley** [marbl/canu#49]
Hi,
I installed canu with brew but am getting this error:
```-- Starting command on Thu Feb 18 12:07:23 2016 with 220.2 GB free disk space
--
/usr/local/Cellar/canu/1.0/Darwin-amd64/bin/generateCorrectionLayouts \
  -G /Users/laurencowley/Ecoli_644/Ecoli644_canu_correct//correction/Ecoli_644_canu.gkpStore \
  -O /Users/laurencowley/Ecoli_644/Ecoli644_canu_correct//correction/Ecoli_644_canu.ovlStore \
  -S /Users/laurencowley/Ecoli_644/Ecoli644_canu_correct//correction/2-correction/Ecoli_644_canu.globalScores \
  -C 80 \
  -p /Users/laurencowley/Ecoli_644/Ecoli644_canu_correct//correction/2-correction/Ecoli_644_canu.estimate
--
-- Finished on Thu Feb 18 12:07:23 2016 (0 seconds) with 220.2 GB free disk space
gnuplot < /Users/laurencowley/Ecoli_644/Ecoli644_canu_correct//correction/2-correction/Ecoli_644_canu.estimate.original-x-correctedLength.gp \
> /dev/null 2>&1

ERROR: Failed with signal 127

-- generate corrected reads attempt 0 begins with 0 finished, and 4 to compute.
--
-- Starting concurrent execution on Thu Feb 18 12:07:24 2016 with 220.2 GB free disk space (4 processes; 2 concurrently)
/Users/laurencowley/Ecoli_644/Ecoli644_canu_correct//correction/2-correction/correctReads.sh 1 > /Users/laurencowley/Ecoli_644/Ecoli644_canu_correct//correction/2-correction/correctReads.000001.out 2>&1
/Users/laurencowley/Ecoli_644/Ecoli644_canu_correct//correction/2-correction/correctReads.sh 2 > /Users/laurencowley/Ecoli_644/Ecoli644_canu_correct//correction/2-correction/correctReads.000002.out 2>&1
/Users/laurencowley/Ecoli_644/Ecoli644_canu_correct//correction/2-correction/correctReads.sh 3 > /Users/laurencowley/Ecoli_644/Ecoli644_canu_correct//correction/2-correction/correctReads.000003.out 2>&1
/Users/laurencowley/Ecoli_644/Ecoli644_canu_correct//correction/2-correction/correctReads.sh 4 > /Users/laurencowley/Ecoli_644/Ecoli644_canu_correct//correction/2-correction/correctReads.000004.out 2>&1
--
-- Finished on Thu Feb 18 12:07:24 2016 (0 seconds) with 220.2 GB free disk space
-- generate corrected reads attempt 1 begins with 0 finished, and 4 to compute.
--
-- Starting concurrent execution on Thu Feb 18 12:07:24 2016 with 220.2 GB free disk space (4 processes; 2 concurrently)
/Users/laurencowley/Ecoli_644/Ecoli644_canu_correct//correction/2-correction/correctReads.sh 1 > /Users/laurencowley/Ecoli_644/Ecoli644_canu_correct//correction/2-correction/correctReads.000001.out 2>&1
/Users/laurencowley/Ecoli_644/Ecoli644_canu_correct//correction/2-correction/correctReads.sh 2 > /Users/laurencowley/Ecoli_644/Ecoli644_canu_correct//correction/2-correction/correctReads.000002.out 2>&1
/Users/laurencowley/Ecoli_644/Ecoli644_canu_correct//correction/2-correction/correctReads.sh 3 > /Users/laurencowley/Ecoli_644/Ecoli644_canu_correct//correction/2-correction/correctReads.000003.out 2>&1
/Users/laurencowley/Ecoli_644/Ecoli644_canu_correct//correction/2-correction/correctReads.sh 4 > /Users/laurencowley/Ecoli_644/Ecoli644_canu_correct//correction/2-correction/correctReads.000004.out 2>&1
--
-- Finished on Thu Feb 18 12:07:25 2016 (1 seconds) with 220.2 GB free disk space
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'can't open '/Users/laurencowley/Ecoli_644/Ecoli644_canu_correct//correction/2-correction/corjob.files' for reading: No such file or directory'.```
 Do you know what could be causing this?
Thanks,
Lauren

**Comment by brianwalenz** [comment]
Possibly two problems.  The first is the same as issue #30 and #32.  It's fixed, but we're behind on making releases.  We hope to get a release out in about a week.

It could also be that the correctReads component really is failing.  Are there errors reported in any of the correctReads.*.out files.

If you can't wait for the next release, install from the source.

**Comment by laurencowley** [comment]
Yeah i think the correction has failed all 4 of the correctReads.*.out files say:
Read layout generation failed.
mv: rename /Users/laurencowley/Ecoli_644/Ecoli644_canu_2//correction/2-correction/correction_outputs/0004.fasta to /Users/laurencowley/Ecoli_644/Ecoli644_canu_2//correction/2-correction/correction_outputs/0004.fasta.INCOMPLETE: No such file or directory
Is this something that can be fixed from installing from the source

**Comment by laurencowley** [comment]
Is there a reason why the read layout generation could have failed that you know of?

**Comment by laurencowley** [comment]
I have now installed from source and still getting the same error

**Comment by laurencowley** [comment]
ok so when I looked in the correction_outputs, I found that the error message for the reads are:
File "<string>", line 9, in <module>
 File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
 File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 551, in get_distribution
 File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 431, in get_provider
 File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 952, in require
 File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
pkg_resources.DistributionNotFound: The 'falcon-kit==0.4.0' distribution was not found and is required by the application
fc_consensus returned -1
So it looks like we are lacking the falcon-kit.... is this not included somewhere? its not on the list of requirements for the install

**Comment by skoren** [comment]
What is the version of OS X you're using. The binary is a self-contained python distribution build on OS X 10.10 so it works on 10.10 or newer. Older versions have an incompatibility with the encode.ascii library. As a workaround, you can install the FALCON assembler and point Canu to fc_consensus.py using the
falconSense=/full/path/to/fc_consensus.py option.

**Comment by laurencowley** [comment]
Excellent! thanks so much have updated to El Capitan and now Canu has completed, thanks for your help with using this ace program!
