### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by peterthorpe5** [marbl/canu#490]
Dear Canu,

firstly love the tool and I have replicated the canu versus spades assembly quality which you presented in your paper, with my own data.

**Request**: Could you please have a field in the contigs description for Average_read_coverage=40 (for example), so the user can easily pull out the reads that map to, or went into making that contig?

Regards,

Pete

**Comment by brianwalenz** [comment]
Would the layout files work?  See #324.

**Comment by peterthorpe5** [comment]
Yes I can see the coverage in the .contigs.layout.tigInfo file. This is what I am after. Thankyou!
