### ISSUE TITLE
Incompatibility with PBSpro: qsub: Nodes statement is not supported, use select statement.

### ISSUE THREAD

**Issue by mmokrejs** [marbl/canu#492]
Hi,
  I cannot get submitted jobs because canu tries to use `-l nodes=1:ppn=1` instead of `-l select=1:ncpus=24`.

```
Canu snapshot v1.5 +27 changes (r8227 43dc29f8aa8cdd8f31c61482711839e75d4d0be3) failed with:
  Failed to submit script
```

  I can append to the the qsub commandline using `gridOptions="-A blah"` but I cannot get replaced the `-l select` argument. Likewise, can I get the jobs in larger chunks utilizing our 128GB RAM nodes with 24 cores each?

Thank you

**Comment by skoren** [comment]
There is no incompatibility, Canu supports arbitrary requests for cores which can vary between grid configurations. See the documentation: http://canu.readthedocs.io/en/latest/parameter-reference.html#grid-engine-configuration

You would need to set ```gridEngineThreadsOption="-l select=1:ncpus=THREADS"``` and Canu will replace THREADS with the appropriate number of cores when submitting jobs. As for using 128GB ram nodes, Canu will already detect available resources and optimize to maximize cpu usage. Depending on genome size, it may not create a single job to fill 128gb of ram and that might not be the most efficient use of resources anyway. You can overwrite the config and force a step to use more memory with the memory options:
```canu -options |grep mem```
for a full list

**Comment by mmokrejs** [comment]
But still, I should not need to prevent canu using old syntax `-l nodes=1:ppn=THREADS` and telling it to use new syntax `-l select=1:ncpus=THREADS`. I forgot to mention we have `PBSPro_13.1.1.162303`.

**Comment by skoren** [comment]
This is a relatively recent change in PBSPro 13+. There's lots of users who still have older PBSPro and PBS (non-pro and torque) still use the node syntax. According to the documentation the nodes syntax is supposed to be converted to the new syntax by the system, not sure why it is not on your system:
```
In early versions of PBS, job submitters used “-l nodes=...” in what was called a “node specification” to specify where the job should run. The syntax for a “node specification” is deprecated.
For backward compatibility, a legal node specification or resource specification is converted into select and place directives; we show how in following sections.
```

We're not going to chase every version/configuration change in a grid, it would make the code far too cumbersome to not only switch grid engines but delineate PBS vs PBSpro by version. The defaults are meant to work on a majority of systems (which is true until everyone upgrades to PBSPro 13+) but it is easy enough for users to specify this for their system and documented. These defaults can be specified system-wide using a ```canu.defaults``` file placed in the bin directory of the Canu installation or a ```.canu``` file in your home folder.

**Comment by mmokrejs** [comment]
There is yet another problem. The commandline cannot proibably contain twice '-l` switch.

```
$ canu -correct -p myproj -d myproj__canu -nanopore-raw file.fastq gridOptions="-A myproj -q qlong" gridEngineThreadsOption="-l select=1:ncpus=THREADS,walltime=144:00:00"

...

Please panic.  Canu failed, and it shouldn't have.

Stack trace:

 at /scratch/work/project/bio/canu/Linux-amd64/bin/lib/canu/Execution.pm line 1105
        canu::Execution::submitOrRunParallelJob('tt_16D1C3L12', 'meryl', 'correction/0-mercounts', 'meryl', 1) called at /scratch/work/project/bio/canu/Linux-amd64/bin/lib/canu/Meryl.pm line 537
        canu::Meryl::merylCheck('tt_16D1C3L12', 'cor') called at /scratch/work/project/bio/canu/Linux-amd64/bin/canu line 535


Last few lines of the relevant log file (correction/0-mercounts/meryl.jobSubmit.out):


Canu snapshot v1.5 +27 changes (r8227 43dc29f8aa8cdd8f31c61482711839e75d4d0be3) failed with:
  Failed to submit batch jobs

$ cat myproj__canu/correction/0-mercounts/meryl.jobSubmit.out
qsub: "-lresource=" cannot be used with "select" or "place", resource is: mem
$

$ cat myproj/correction/0-mercounts/meryl.jobSubmit.sh 
#!/bin/sh

qsub -j oe \
  -l mem=125g -l select=1:ncpus=24,walltime=48:00:00 -A myproj -q qlong \
  -N "meryl_myproj" \
   \
  ./meryl.sh  \
> ./meryl.jobSubmit.out 2>&1
```

In the new syntax the following two commands work for me

```
-l select=1:ncpus=THREADS,walltime=144:00:00
-l select=1:mem=125GB,walltime=144:00:00
```

but their combination is forbidden:

> -l select=1:ncpus=THREADS,mem=125GB,walltime=144:00:00

with same error message.

**Comment by skoren** [comment]
So how do you request memory and cores for one job on your grid? You can overwrite the memory option as well to use select instead of mem with gridEngineMemoryOption. If you need only one -l option then that's issue #466 which is a feature request to combine thread and memory options. It also has a workaround.

**Comment by skoren** [comment]
Closing inactivity, see issue #466 for tracking this request.

**Comment by mmokrejs** [comment]
Sorry for the delay, I somewhat forgot about this ticket.

There is no way to specify both `ncpus=` and `mem=` inside a single `-l $blah` argument.

But these are allowed:

```
qsub -A OPEN-0-0 -q qfat -l select=1:mem=3099GB,walltime=48:00:00 ./myjob
qsub -A OPEN-0-0 -q qprod -l select=9:ncpus=24,walltime=48:00:00 -l place=group=switch ./myjob
```

I will check if I really need to set the `mem=` value myself for the normal computational nodes with `ncpus=24`.

**Comment by brianwalenz** [comment]
I'm waiting for access to a PBSpro installation.  Once that is approved, I'll get started fixing these issues.

Any help appreciated!

**Comment by brianwalenz** [comment]
There have been a few PBS improvements lately (e13467a0ada171b9f70dd9ea615452cd707ea0ac and df2dbf1df0fa8fd0a98a6f281dafcb131f57dc64).  Memory and CPU selection is also now controlled by a single parameter, `gridEngineResourceOption`, which should allow flexibility to have one or multiple `-l` options.
