### ISSUE TITLE
Have to run the assembly step twice

### ISSUE THREAD

**Issue by tbawin** [marbl/canu#499]
Hi  !

I tried to assemble a small genome with Canu on my computer and it worked fine.

Then I tried the same job on a grid environment where I plan to run bigger ones in the future.

Unfortunately it failed in the assembly step. I went through the forum and found that I had to run the job again - and that is what I did.

Now I wonder what is going on. I did not find how I can fix the issue and avoid to run such job twice every time I want an assembly.

Also, the output assembly on the grid environment is slightly different from that I obtained on my computer (about 10 bases shorter) though this is the same version of Canu (1.5). 

Do you have any suggestion?

Here are my commands:

canu useGrid=false -correct -pacbio-raw ../../cassava/Mes-B-60444-17M18_filteredSubreads.fastq genomeSize=142836 gnuplotTested=true -p Mes-B-60444-17M18 -d ./Mes-B-60444-17M18

canu useGrid=false -trim -pacbio-corrected Mes-B-60444-17M18/Mes-B-60444-17M18.correctedReads.fasta.gz genomeSize=142836 gnuplotTested=true -p Mes-B-60444-17M18 -d ./Mes-B-60444-17M18

canu useGrid=false -assemble -pacbio-corrected Mes-B-60444-17M18/Mes-B-60444-17M18.trimmedReads.fasta.gz genomeSize=142836 gnuplotTested=true -p Mes-B-60444-17M18 -d ./Mes-B-60444-17M18-erate-045 correctedErrorRate=0.045

**Comment by skoren** [comment]
The 10base difference is OK, there is some randomness in consensus due to the order the reads are aligned so small changes can happen between systems.

You shouldn't have to run any step twice, presumably the second run resume the assembly which had failed on your grid. The logs in the canu-scripts folder should have more information (```canu-scripts/canu.*.out```) if you can attach them to this issue we can see why the run stopped.

**Comment by tbawin** [comment]
Thanks for your response!

There is unfortunately no file in the canu-scripts folder. I tried `find -L . -name '*.out'` in the Mes-B-60444-17M18-erate-045 folder and did not found any `canu.*.out` file.

Is there something else I can provide to help you to solve the problem?

**Comment by skoren** [comment]
Ah I didn't notice that you had ```useGrid=false``` in your command. So when you say running Canu on the grid, you ran on a single node that you submitted the job to? Do you have the stdout/stderr of the original job as well as the second run and can you check why the job terminated on your grid? The likeliest is not requesting sufficient time so the job got killed for exceeding the default. You could try running the job from scratch again and requesting double the time.

Canu can also submit jobs by itself to the grid as well if you want to get more CPU utilization than a single machine for large genomes.

**Comment by tbawin** [comment]
Yes, I ran on a single node because I had problems instead that I was not able to solve. Maybe I will have to fix it in the future for larger genomes. But I guess I have to discuss it in a new issue.  

I attached the stdout/stderr files of the original job (689070) and the second run (689073).

The only error message I found is 'Failed with exit code 1.  (rc=256)'.

Which option can I use for requesting sufficient time?






[stdout_stderr.zip](https://github.com/marbl/canu/files/1010494/stdout_stderr.zip)

**Comment by skoren** [comment]
This looks like the same error as #501:
```
-- Starting command on Thu May 18 11:54:53 2017 with 9142.603 GB free disk space

    cd unitigging/4-unitigger
    ./alignGFA.sh
./alignGFA.sh: line 66:  8667 Aborted                 (core dumped) $bin/alignGFA -bed -T ../Mes-B-60444-17M18.utgStore 2 -C ../Mes-B-60444-17M18.ctgStore 2 -i ./Mes-B-60444-17M18.unitigs.bed -o ./Mes-B-60444-17M18.unitigs.aligned.bed -t 4 > ./Mes-B-60444-17M18.unitigs.aligned.bed.err 2>&1

-- Finished on Thu May 18 11:54:54 2017 (1 second) with 9142.599 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:
================================================================================
Don't panic, but a mostly harmless error occurred and Canu stopped.

Disk space available:  9142.599 GB

Canu snapshot v1.5 +36 changes (r8236 32c8fc85c45dc9a3c7e5b613b9bc782145b8e41e) failed with:
  failed to align contigs
```
Are you able to share you read fastq file, you can upload it to our FTP using the instructions here:
http://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you

**Comment by tbawin** [comment]
I am sorry but I am not sure how it works.
I just have to drag and drop the fastq file at ftp://ftp.cbcb.umd.edu/incoming/sergek?
There are few explanations on the page.

**Comment by skoren** [comment]
Depending on your OS/browser, drag-drop may work. I typically use a command line interface, you can use any ftp client (OS X or Linux should have one installed). Run:
```
ftp ftp.cbcb.umd.edu
```
specify anonymous and just hit return for password (blank). Then
```
cd incoming/sergek
put ../../cassava/Mes-B-60444-17M18_filteredSubreads.fastq
quit
```
assuming you're in the same directory as you launched canu from.

**Comment by brianwalenz** [comment]
I think I got it fixed.  Your assemblies look pretty small, so just redo the -assembly portion.

Close the issue if it works for you.

**Comment by tbawin** [comment]
Yes it works, that is what I explained at the beginning. What I'd like to know is why I have to redo this step.

I typed in your command lines to log into the FTP server. I think the dataset is available, if you wish.

**Comment by skoren** [comment]
You needed to run it twice because there was a bug which caused the run to crash. With the bug fix you can rerun the assembly step from scratch and it should run in one go.

**Comment by tbawin** [comment]
We updated the software (from version 1.5 + 36 changes to 46 changes) on the grid and it works fine.
Thanks!

**Comment by skoren** [comment]
Ok. Leaving open because Canu should not have completed if this step failed so we need to test if failure in this step is properly detected.

**Comment by brianwalenz** [comment]
Closing again.  ;-)
