### ISSUE TITLE
Is there a cap on read size used in trimming/unitigging stages?

### ISSUE THREAD

**Issue by JohnUrban** [marbl/canu#50]
I ran an assembly with some long reads in excess of 65,535 bp. What was interesting is that after correction, the read lengths in the trimming and unitigging stages (i.e. in asm.gkpStore/readlengths.txt) reached up to exactly 65535, which was repeated 11 times. What makes this more curious is that the read length histogram shows that the >10 bins before "65000 - 65999" all have <= 5 counts, then it shoots up to 11 (all of which are the same exact length of 65535):
33000   33999   50
34000   34999   78
35000   35999   41
36000   36999   37
37000   37999   40
38000   38999   39
39000   39999   23
40000   40999   23
41000   41999   35
42000   42999   20
43000   43999   18
44000   44999   11
45000   45999   11
46000   46999   10
47000   47999   10
48000   48999   4
49000   49999   3
50000   50999   7
51000   51999   9
52000   52999   6
53000   53999   6
54000   54999   3
55000   55999   2
56000   56999   2
57000   57999   1
58000   58999   4
59000   59999   3
60000   60999   5
61000   61999   1
62000   62999   1
63000   63999   3
64000   64999   1
65000   65999   11

All in all, I am just wondering if there is a cap on read size (even if unintended) imposed during/after correction .. perhaps in the beginning of the trimming stages…

**Comment by skoren** [comment]
Have you checked the lengths of the corrected reads output (in asm.correctedReads.*). Do those stop at 65K?

**Comment by JohnUrban** [comment]
Both the following files show the same thing (last 11 longest reads are 65535):
asm/asm.correctedReads.lengths
asm/asm.correctedReads.fasta

Interestingly, 65535 = 2^16 - 1.
That is even more curious and is similar to how the max read length cut off for input reads we discussed in issue#33 (https://github.com/marbl/canu/issues/33) was set to 131071 = 2^17 - 1.

So my guess was that there might be lines of code somewhere similar to the lines in gkStore.H (where I needed to change 17 to 21 to allow longer input reads):
#define AS_MAX_READLEN_BITS        21
#define AS_MAX_READLEN             (((uint32)1 << AS_MAX_READLEN_BITS) - 1)

But I didnt find much, except maybe these lines in ovStore.H:
ovOverlapWORD  ahg5           : AS_MAX_READLEN_BITS;   //  16
ovOverlapWORD  ahg3           : AS_MAX_READLEN_BITS;   //  16
ovOverlapWORD  bhg5           : AS_MAX_READLEN_BITS;   //  16
ovOverlapWORD  bhg3           : AS_MAX_READLEN_BITS;   //  16
ovOverlapWORD  span           : AS_MAX_READLEN_BITS;   //  16

I'm guessing these are irrelevant, but figured I'd share just in case.

**Comment by skoren** [comment]
I think this might be falcon_sense related, quickly looking through the code I saw at least one place where 100Kp is a maximum limit. Can you run the assembly with corConsensus=falcon and saveReadCorrections=true

That should leave outputs in 2-correction/correction_inputs and 2-correction/correction_outputs. If you can share the files in correction_inputs (or the one you know has a long read in it) we can try to test fixes locally.

**Comment by JohnUrban** [comment]
When specifying corConsensus=falcon, it now failed on this command:
...canu/Linux-amd64/bin/createFalconSenseInputs \
      -G asm/correction/asm.gkpStore \
      -T asm/correction/asm.corStore 1 \
      -o asm/correction/2-correction/correction_inputs/ \
      -p 256 \
    > asm/correction/2-correction/correction_inputs.err 2>&1

sh: line 5: 31946 Segmentation fault     

.
.
.
ERROR: Failed with signal SEGV (11)

================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

Disk space available:  121967.4 GB

Last 50 lines of the relevant log file (/users/jurban/scratch/canu/hybrid/troubleshooting/g350-lowcov/correction/2-correction/correction_inputs.err):

Will partition 160899645 total child reads into 256 partitions.

Failed with 'Segmentation fault'

**Comment by skoren** [comment]
That flow of the pipeline is primarily for debugging so it got broken in some of the commits. I had it crash on a small bacteria and committed a fix. Give it a try with the update and see if it works. 

I also committed an update to falcon_sense which should hopefully remove the 100Kb limit so you can try your normal pipeline (with just saveReadCorrections=true) and see if your corrected reads are longer than before.

**Comment by skoren** [comment]
I've confirmed (using simulated data) that the previous version of falcon_sense in Canu would never output reads longest than 65kbp:

```
read3_0	65535
read3_1	34404
read4_0	65535
read4_1	34452
read5_0	65535
read5_1	34452
​``

The updated version successfully handles 100kb+ sequences:

```
read3_0	126211
read4_0	147183
read5_0	113911
```
