### ISSUE TITLE
CANU is too polite on the grid

### ISSUE THREAD

**Issue by Kirk3gaard** [marbl/canu#502]
Hi 

I am a very happy user of CANU. However I have realised that when I have moved to a system with a grid and slurm queue (for larger datasets) I end up waiting in the queue for ever. 

The process seems to run just fine but since CANU breaks the entire process up into smaller pieces e.g. correction, trimming and assembly (it seems as if each of these include smaller sub-jobs). 

So I wait in the queue until I am first in line and the first process starts, but when it finishes after a few minutes CANU submits the next job for the queue and I have to wait until whatever people put in the queue after my first submission before the second sub- job starts. This makes it less feasible to run CANU on a cluster shared among many researchers as my <24 hour total job will end up waiting in line for a long time.

I have little experience with HPCs but I hope there is a workaround to make CANU less polite when it comes to resources.

I run canu using the command:
"canu -p metagenome1D -d metagenome1D-auto-HPC genomeSize=500.0m gridOptionsJobName=RHKgenomeassemblyCANU gridOptions="--account aauhpc_fat --nodes 30 --time=24:00:00 --mail-user rhk@bio.aau.dk --mail-type all" -nanopore-raw /gpfs/gss1/work/aauhpc/rkirke08/above4kcombined.fa"

Thanks in advance.

Best regards
Rasmus Kirkegaard

**Comment by skoren** [comment]
That is the appropriate behavior for Canu but I think the issue with the long wait time is your gridOptions. These get passed to all jobs and you are specifying ```--nodes 30``` which I would guess would try to reserve 30 nodes to run on? In that case your jobs will always sit in the queue waiting.

You don't need to request resources, Canu will put in requests as it needs them, it will also never submit a job that runs on more than a single machine (it will just submit several jobs that each run on a single machine). Try removing that option and see if it runs faster.

**Comment by Kirk3gaard** [comment]
Thanks for the fast reply. Yes you are absolutely right it tries to reserve 30 nodes.

Great. I will try to remove that and resubmit the job. Thanks a lot!

**Comment by Kirk3gaard** [comment]
Seems to fix everything. Thanks a lot!
