### ISSUE TITLE
How to detect best correctedErrorRate based on canu feedback?

### ISSUE THREAD

**Issue by wangyugui** [marbl/canu#503]
We can use the suggested correctedErrorRate  based the sequence type such as P6C4 as document. but the correctedErrorRate  is not fixed for diff operators?

Can we detect best correctedErrorRate based on canu feedback?  such as unitigging/4-unitigger/ecoli.001.filterOverlaps.thr000.num000.log:mean   0.00244207 stddev 0.00262130 -> 0.01816984 fraction error =   1.816984% error

I have two can result for ecoli dataset.
1)correctedErrorRate  =0.045
' fraction error =   1.816984% error ' is reported in unitigging/4-unitigger/ecoli.001.filterOverlaps.thr000.num000.log

2)correctedErrorRate  =0.075
'0.02382512 fraction error =   2.382512% error' is reported in unitigging/4-unitigger/ecoli.001.filterOverlaps.thr000.num000.log

Is the result of correctedErrorRate  =0.075 better than correctedErrorRate  =0.045?
although the results of  fasta files have only little diff.

```
# ls -l */*.fasta
-rw-r--r-- 1 root root 4716930 May 20 08:27 canu-0.045/ecoli.contigs.fasta
-rw-r--r-- 1 root root 4711925 May 20 09:24 canu-0.075/ecoli.contigs.fasta
```

**Comment by brianwalenz** [comment]
Short answer: no.

Bogart uses correctedErrorRate to decide what overlaps to use for computing these statistics, then (mostly) ignores overlaps above that threshold.  There are other algorithms that use correctedErrorRate (e.g., trimming) that do need the higher error rate overlaps.

The mean/stddev values are highly influenced by outliers.  The median/mad numbers (which are the ones used internally) shouldn't show much difference.

**Comment by wangyugui** [comment]
so the best correctedErrorRate should be decided as the guide(faq.rst):
1) the sequencing type such as P6C4 or P5C3.
2)coverage
3)heterozygosity in DNA samples.
