### ISSUE TITLE
settings.sh not found 

### ISSUE THREAD

**Issue by mw55309** [marbl/canu#505]
Hi

Using canu 1.5, the guess to my settings.sh is wrong, and I get

```
/var/spool/gridscheduler/execd/node2i22/job_scripts/2635995: line 9: /exports/applications//gridengine/2011.11p1_155/etc/common/settings.sh: No such file or directory
```

The offending code from canu-01.sh is

```
#  Attempt to (re)configure SGE.  For unknown reasons, jobs submitted
#  to SGE, and running under SGE, fail to read the shell init scripts,
#  and so they don't set up SGE (or ANY other paths, etc) properly.
#  For the record, interactive logins (qlogin) DO set the environment.

if [ "x$SGE_ROOT" != "x" ]; then
  . $SGE_ROOT/$SGE_CELL/common/settings.sh
fi
```

In fact there is no file called settings.sh anywhere under my $SGE_ROOT.

What is this code trying to do?  Can I turn it off?  (other than by hacking the code)

For some reason this was not present in my previous runs using canu 1.4, and subsequent github code updates

Cheers
Mick

**Comment by brianwalenz** [comment]
That's the stuff to set up SGE - all the environment variables and the path.  It's not new by any stretch.  It's been in there almost literally forever.  How do you set up SGE in an interactive login?  

You can turn it off by using a grid other than SGE....so not terribly helpful.  I can change the if test to make it source settings.sh only if the file actually exists (add `-a -e "$SGE_ROOT/$SGE_CELL/common/settings.sh"`).  Arguably the correct thing to do, except that file should (IIRC) always exist.

If SGE isn't set up -- if qhost and/or qconf and/or qsub aren't in the path -- then canu should fail when it tries to do its automagic configuration based on hosts in the grid.  Or, if not there, then definitely when it tries to submit jobs to the grid.

**Comment by mw55309** [comment]
Sorry for opening this, I think I must have commented out the code in 1.4 etc

Clearly whatever problem this fixes, the IT team have fixed it here in SGE anyway, as the problems we have with Canu are not SGE related (AFAIK).  I'm not sure what that fix is, but fixed it is.

It would just be good to turn this off to prevent me having to change the Canu code every time a new release comes out

Cheers
Mick

**Comment by mw55309** [comment]
Hey

Just upgrading to Canu 1.6 and experienced this error again.  

I have the binary/compiled version, so I guess the quick fix is to take the source and recompile (#shudder) but really I guess it would be great to have a check in the code to check the file exists before opening it

Cheers
Mick

**Comment by skoren** [comment]
Should be fixed in the code now.
