### ISSUE TITLE
Problem using Canu on SLURM-based grid for the first time

### ISSUE THREAD

**Issue by nataliering** [marbl/canu#506]
Fantastic assembly tool, thank you! I've used Canu in the past to assemble data sequenced by Nanopore R7, which ran fine on my MRC CLIMB account. Now we've generated a set of data many orders of magnitude larger using R9, so I'm attempting to process it using Canu on the University of Bath's High Performance Computing cluster, Balena, which allows me up to 16 nodes, each with 16 available CPUs (jobs are only allowed to run for 6 hours or less). 

I have submitted an assembly job to the cluster's queue a few times now, and am having the same issue each time. Canu seems to start running well, without any error messages, but finishes very quickly (after less than a minute usually), without actually doing any assembly - I think it is exiting for some reason during the correction stage. 

Here's a link to the SLURM job-script I have been submitting, which includes the Canu command, and also to the SLURM "err" file which shows the output from Canu, and where the process is ending: 
[https://drive.google.com/open?id=0B7A9vAPzC1yCdTFpOU5pVy1BdFk](https://drive.google.com/open?id=0B7A9vAPzC1yCdTFpOU5pVy1BdFk)

Why is this not running to completion, please? Am I not submitting it to the grid in a Canu-friendly way?

Thanks for your help,
Natalie Ring
(PhD student, University of Bath)

p.s. I can also add the fastq file I'm trying to assemble to the Google Drive folder if that would help, but the file is very, very large.

**Comment by skoren** [comment]
Canu knows slurm and submits the jobs to the grid itself. What is happening with your job is that Canu runs and submits the next job. That is the correct behavior. You can the tail end of the err log

--
-- Running jobs.  First attempt out of 2.
--
-- 'meryl.jobSubmit.sh' -> job 781383 task 1.
--
----------------------------------------
-- Starting command on Fri May 19 19:10:07 2017 with 59755.298 GB free disk space

    cd /beegfs/scratch/user/f/nar27/BP_UK76_0317/Running_files/BP_UK76_0317_auto
    sbatch \
      --depend=afterany:781383 \
      --mem-per-cpu=8g \
      --cpus-per-task=1   \
      -D `pwd` \
      -J 'canu_BP_UK76_0317_canu' \
      -o canu-scripts/canu.01.out canu-scripts/canu.01.sh

-- Finished on Fri May 19 19:10:07 2017 (1 second) with 59755.298 GB free disk space
----------------------------------------

You can see your running jobs with squeue. If you've run this command multiple times you likely have lots of jobs trying to run in the same folder, which is not good. I would kill all jobs you have, remove the folder, and run from scratch. You can let Canu submit itself and run on the grid. If you specify useGrid=false it will stay on a single node. 

The other thing from the logs seems to indicate you have 10000 fold coverage. Is that accurate? If so, subset the data to a random 100 fold coverage datase, running this much coverage is overkill and will just slow down the correction.

**Comment by nataliering** [comment]
Hi Sergey

Thanks for your reply - I can see the meryl job using squeue for a while but then it disappears and nothing more happens. I think the problem is that when Canu is submitting itself for the next stage, it automatically sets a time-limit of 10 minutes, which is timing out due to the absurdly large number of reads I have. 

I'm now trying to take a random 100x coverage sample of my reads using fastqSample, but I can't seem to get the usage right. I have all my reads in a single fastq file, called "BP_UK76_0317.fastq", and am submitting the following fastqSample command:

`fastqSample -I BP_UK76_0317 -A -m 4000 -g 4m -c 100`

This fails with the message 

> Counting the number of reads in the input.
> Failed to open 'BP_UK76_0317.fastq.1.fastq': No such file or directory

I feel like I'm being really stupid here, but what am I doing wrong please?

Thanks again,
Nat

**Comment by skoren** [comment]
fastqSample was originally designed for illumina reads so it expects .1.fastq and .2.fastq by default. You can get the usage information by running fastqSample without options. If you specify -U it will look for a BP_UK76_0317.u.fastq file. You also need to specify the genome size as 4000000 not 4m.

Is 10 minutes your default runtime if not specified? Canu won't add any time/partition request by itself but you can pass by setting the gridOptions flag like:
```
gridOptions=" --account=free --partition=batch-all --time=06:00:00"
```
Then all those options would be passed through to subsequent jobs.

**Comment by nataliering** [comment]
You're right - 10 minutes is our in-house default, I had forgotten I could set my own time limit using gridOptions! I've got that running now so hopefully it will progress past the meryl stage this time.

Back to fastqSample, it's finding the file now I'm using -U (and have changed the file name to match), but am getting a new error message:

> Counting the number of reads in the input.
> ERROR:  Not FastQ.  Read lines:
> 
>   @11a52085-a6f6-4583-acf3-e30f0df12796 runid=a155cc3c826a8b7da1bef513b309584cad3c1582 read=3260 ch=329 start_time=2017-03-20T03:45:09Z
>   TGCAAGCGGCGCGGCGATCGCCGCTTCTCGGCATCACGAGTGCTGCTGATCCGCCACATCCGTTCGCTGCTGTACGAACAGGGCTTCACCATCAGCAGCGCGCAACCGCCTGGGCGACGCGCGCGACGCCGCCTGTCACAAACGCGGTGCGGCTGAGCGCCAGACGAGCTGCAGGCCCTGCGCAACCGAGCTGGGCGACTATCGATGCTGGAACGCTTTGAGGCGCTGGGCAGCCAGTCCGGGGAACGGTAACGCCTGAGAACACAGCCCGGCCAACTCCAGGTGCAGTGAGCCGCGACGCCGCTGGTTCTTCGCGAACCGGCGGCGTTTTCACTGGTACTCACCAAACGCGGCCGTCCAGGCACGGCGATGCCGGAAATTGCGATGCAGTGCGTGCGCATTTTTTCAGTTCCTGATATGCTTTCGTTCTTTCGGGGCGTAGCGCGGCCTGGTAGCGCACTTGCATGGGGTGCAGGGTCGCGAGTTCGAATCCGCCGTCCGACCAGTGGTTCCAAGGCCGTCGGTGATCCCTCACTGGCAGCCTTAATCTTCGTCAGGGACTTGCTCCGCTTGGCTCCACCGCCGCTTGCGCATCGTCAAACGTCGGACTGGCGTGCTGGCTGCAGGCACTCCCGAACGCCCAAGACGCTGCGAGCGGTCATTAATTAGGCTGGGTCACCGGTTCGATCGACGCAGCGGGCGCGAATCTCAGGCCGTACTGGCATTGCAGGAATCAACGCCGGCGGAACTATAGATGTACGTCGCGTAGGCGGATTATCTTAGTACTGCTGATATCCAGGCTGGCAGCCAGCATCGGCCTGGGTGAATGAGGTCAGGCGGAGATTTGAGATCGTATCACCTTTTCAAATCTGCCCGTGTTCGTCGACGTAGACACAGGAATCGACTTCCATGACTGGGACAATGAAAGCTGATCGGCATATGCGTTGACATCTCACATTGGCATGACAGGATGCCGTCGCGTTCTACACGAAGATGCTGTTCCATGGGTCAAAAAAGTACCCATTTATTTGGCTGTAAGCCCA
>   +

I'm assuming this is a problem with my fastq file, but I'm not sure what. To make it, I concatenated all the fastq files produced by my Albacore basecalling using this:
`cat *.fastq > BP_UK76_0317.fastq`

Any ideas? 

Thanks again!

**Comment by brianwalenz** [comment]
There's a stray blank line in the file just before this read.

A few alternatives:

1)  Instead of `cat *fastq` then sampling out a handful of reads, give only a handful of these files to canu.

2)  Use `minReadLength=15000 stopOnReadQuality=false` to assemble only the longest of the reads.

**Comment by brianwalenz** [comment]
Reopen if needed.
