### ISSUE TITLE
Can't run canu in a grid environment

### ISSUE THREAD

**Issue by tbawin** [marbl/canu#507]
Hi,

Thanks to your support (#499) I am able to run Canu on a single grid node.

Now I would like to be able to run Canu using the whole grid because I will have to assemble large genomes.

I submitted the following job to the queue :

`canu -correct -pacbio-raw ../../cassava/bac_assemblies/Mes-B-60444-17M18_filteredSubreads.fastq genomeSize=150000 correctedErrorRate=0.045 gnuplotTested=true -p Mes-B-60444-17M18 -d Mes-B-60444-17M18-2`

It is the same than previously, without the `useGrid=false` option, but it failed. Canu asked for thread and memory options (error file 695020). I thus added `gridEngineThreadsOption="-pe snode THREADS"` and `gridEngineMemoryOption="-l h_vmem=MEMORY"` to my command, and submitted it again. 

This time, Canu run on the grid without any error message (error file 695027) and submitted jobs itself. But there was no output file with corrected sequences.

The meryl job 695028 mentioned in the error file stays pending in the queue system and never gets executed.

Do you know what is wrong with my command?

[17M18.zip](https://github.com/marbl/canu/files/1021432/17M18.zip)

**Comment by brianwalenz** [comment]
Is the SGE queue full?  `qstat -u \*` will show all jobs, not just yours.

Does SGE tell why the job isn't running?  `qstat -j 695028` (the 'scheduling info' might not be enabled on your grid).

Are there other options you need to use when submitting a job to SGE?  Add those to 'gridOptions'.

**Comment by tbawin** [comment]
Thanks for your answer!

Indeed the SGE queue is almost saturated by other jobs and it is not easy to work in there...

I run the analysis again from scratch and the meryl job got executed this time. However there still was no output file with corrected sequences. 

I added `maxMemory=16` and `maxThreads=4` to my command as suggested by the error file. These values are not limiting the process when running with the option `useGrid=false` (I just checked right now).

I rerun the analysis from scratch but it failed again. When looking at the `canu-scripts/canu.01.out`, I found the following error message: `error: denied: host "node07" is neither submit nor admin host`.

I submitted the analyses to the node01, which I think is the head node. But Canu sent its jobs to node07 where most of the free CPUs can be found. 

Thus I guess this is the same problem than issue #156 ?

[canu.01.out.zip](https://github.com/marbl/canu/files/1024947/canu.01.out.zip)

**Comment by brianwalenz** [comment]
Yup, same problem.  Canu needs to be able to submit jobs to the grid.  If you can run jobs on node01, setting `gridOptionsExecutive="-l hostname=node01"` will force the non-compute portions of canu to run only on that node.  These will do some small computes, but they can do significant I/O; for large assembles they could run for hours.

Can you elaborate on how maxMemory and maxThreads aren't working?

**Comment by tbawin** [comment]
I added the `gridOptionsExecutive="-l hostname=node01"` but it did not work either.

I had the following message: 

ABORT: Canu snapshot v1.5 +46 changes (r8246 42419ba90bee1a5d93ee50a442bc15d18778a96f)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.

What I did, without any success.
 
How can you see that maxMemory and maxThreads are not working ? Both seem to be detected in the 'Configure Canu' section of the report.

**Comment by skoren** [comment]
The change seems to have fixed the submission issues. Your errors indicate a failure in the precompute step, most likely it is due to an incorrect java version or other java error but not a grid error. Upload the ```correction/1-overlapper/precompute.*.out``` files for an exact cause.

As for maxMemory/maxThreads, you said it was not limiting the job when running with useGrid=false, which is by @brianwalenz asked about it. How did you detect that it was not limiting usage?

**Comment by tbawin** [comment]
I misspoke in referring to the maxMemory and maxThreads options. What I meant is that the values I fixed were high enough to run the jobs properly under useGrid=false (and did not limit/crash them). I apologize!

Here are the precompute.*.out files you asked for.

[precompute.out.zip](https://github.com/marbl/canu/files/1033465/precompute.out.zip)

**Comment by skoren** [comment]
The error indicates the JVM cannot start up:
```
Starting mhap precompute.

Error occurred during initialization of VM
Could not reserve enough space for 6291456KB object heap
```

It's possible h_vmem isn't the right memory option, if your grid has it available, I'd try mem_free or mem_total instead. It could also have something to do with how java is configured on your cluster by default, you could try increasing the memory it should use ```mhapMemory=16``` and see if that works (see issue #298).

**Comment by tbawin** [comment]
Sorry to have been long to answer. There was many jobs in the submission queue and it took a long time for mine to be processed.

I tried several combinations and some worked! Here is a summary:
- h_vmem => ko
- mem_free => ok
- mem_total => ok
- mhapMemory=16 => ko
- h_vmem + mem_free => ko
- h_vmem + mem_total => ko
- mem_free + mem_total => ok

So it seems that I have to request either mem_free or mem_total (or both). You were right!

Now I am wondering: why the options `gridEngineMemoryOption="-l h_vmem=MEMORY -l mem_free=MEMORY"` and `gridEngineMemoryOption="-l h_vmem=MEMORY -l mem_total=MEMORY"` are not working if mem_free and mem_total are available, respectively?

**Comment by skoren** [comment]
So first off, h_vmem is an enforced limit so if a job goes over this limit it is killed. Using mem_free the memory is reserved but a job is not killed for exceeding it. On SGE, usually a non-consumable resource like h_vmem is reserved per job but consumable resources are reserved per thread on SGE. Canu expects the memory to be specified per thread so it is specifying h_vmem to be too low, leading to the job to be killed. Canu tries to keep within the memory specified but due to system configuration and system overhead, the virtual memory may be slightly higher than the actual physical memory being used by the job. So you should be OK just running without h_vmem.
