### ISSUE TITLE
Canu stops before aligning contigs

### ISSUE THREAD

**Issue by annaallueg** [marbl/canu#508]
Hi,

I used Canu in the past and worked great! We recently did a migration to a new server (SGE) and I have been trying to run a job there, but it keeps stopping before the last step, failing to align the contigs. The log file says that it is mostly a harmless error, but I cannot find out what is wrong.
Here is the command I used:
```
canu gridEngineThreadsOption="-pe orte THREADS" gridEngineMemoryOption="-l mem_free=MEMORY" useGrid=false -d A1552WT_shamu -p A1552WT genomeSize=4m -nanopore-raw /home-new/ltj621/cbi-data/Minion_VC_A1552_051817/poretools_WT/poretools_fastq_A1552_WT-21291.fastq 
```
I am attaching the log file, where you can see the the error at the end ('failed with signal .').
Any help would be really appreciated.
Thanks a lot!

Anna Allue (University of Texas at San Antonio)

[canu_WT-21342.txt](https://github.com/marbl/canu/files/1027790/canu_WT-21342.txt)

**Comment by brianwalenz** [comment]
That's a very new feature, and was recently fixed.  Update to the latest code - you're about a month and a half out of date.

The 'orte' environment might not be the correct one for Canu.  Are there others available (`qconf -spl`)?  See if any of those have allocation_rule = $pe_slots (use `qconf -sp <pe_name>`).

**Comment by annaallueg** [comment]
Thanks a lot for the rapid response! I'll update the code and see if I can change the orte environment.
Much appreciated!

**Comment by brianwalenz** [comment]
Reopen if needed.
