### ISSUE TITLE
ovStoreSorter needs too much memory

### ISSUE THREAD

**Issue by tangerzhang** [marbl/canu#510]
I am using canu-1.3 on a SGE grid to assembly a very large genome (8G genome size and 60X sequencing coverage).  Command line and spec file are below:
1. command line:
canu -s spec.txt -p Mol -d asm80X genomeSize=8g -pacbio-raw Mol.raw.subreads.fasta
2. spec.txt 
```
corOutCoverage=120
ovbMemory=24g
ovbThreads=12
maxMemory=500g
maxThreads=48
ovsMemory=300-800
ovsThreads=20
oeaMemory=32g
corMhapSensitivity=low
```
However, the ovStoreSorter crashed in the trimming step as it needs 299G memory for each job. I have 20 nodes with 128G memory and 5 nodes with 256G memory. I can not provide any computer nodes to meed its requirement. Is it possible to solve this problem through tuning any parameter? Thanks.

**Comment by skoren** [comment]
Your spec file is setting:
```
ovsMemory=300-800
```
This means use between 300 and 800gb so it is trying to use 300G as you requested. I would suggest setting it to something like ```ovsMemory=32-128``` so it would fit on all your machines at the largest size.

**Comment by tangerzhang** [comment]
Ah, I did a stupid thing!
Thanks
