### ISSUE TITLE
another pbspro workdir issue?

### ISSUE THREAD

**Issue by hodgett** [marbl/canu#511]
We have encountered another place where the $PBS_O_WORKDIR is not being properly expanded. This is towards the end of the correction phase when it is building the .gkpStore. The referencing to the ovljob.files is not being referenced correctly causing it to crash out with the error from canu.out;

```
...
Can't open './1-overlapper/ovljob.files': No such file or directory

Canu snapshot v1.5 +22 changes (r8222 700032eff25266fbd0757b006376d5635d12fa34) failed with:
  failed to generate configuration for building overlap store
...
```

From the end of correction/banaMH17.ovlStore.BUILDING/scripts/0-config.sh ;
```
$bin/ovStoreBuild \
 -G ./banaMH17.gkpStore \
 -O ./banaMH17.ovlStore \
 -M 4-32 \
 -config ./banaMH17.ovlStore.BUILDING/config \
 -L ./1-overlapper/ovljob.files \
```
Where is correction/banaMH17.ovlStore.BUILDING/scripts/0-config.sh being called from?

**Comment by brianwalenz** [comment]
Argh, sorry.  The same problem as in #485.  The 3-index step (which runs at the end of this phase)  also had the same problem.  Fixed.

These scripts run from within the *.ovlStore.BUILDING directory.  You could clean up the scripts by hand, but there's no real work done yet so just remove the whole *.ovlStore.BUILDING directory.
