### ISSUE TITLE
Canu stopped during assembly

### ISSUE THREAD

**Issue by satomimitsuhashi** [marbl/canu#512]
Hi 

We are running Linux on a grid. 
Canu stopped during assembly and showed this message.
```
"Unitigger failed. 
Don't panic, but a mostly harmless error occurred and Canu stopped.
Canu snapshot v1.5 +36 changes (r8236 32c8fc85c45dc9a3c7e5b613b9bc782145b8e41e) failed with:
can iteration count too high, stopping pipeline (most likely a problem in the grid-based
computers)"
```
 
It seems to have failed with core dump with this in the unitigging/4-untigging.
```
bogart -G ../name.gkpStore -O ../name.ovlStore -o ./name \
  -gs 50000  -eM 0.144 -el 500 \
  -dg 6 -db 6 -dr 3 -ca 2100 -cp 200 \
  -threads 4 -M 7 -unassembled "2 1000 1.0 2" > ./unitigger.err 2>&1
```
We run this command again and it immediately showed the message "segmentation fault". 
But with this command, it was OK.
```
bogart -G ../name.gkpStore -O ../name.ovlStore -o ./name \
  -gs 50000  -eM 0.144 -el 500 \
  -threads 4 -M 7  > ./unitigger.err 2>&1
```
Does bogart actually have these options, -dg, -db, -dr -ca and -cp ?
If you could let me know how I re-run the program without these options, that would be very helpful.

Thank you very much.
Satomi

**Comment by brianwalenz** [comment]
Are those the _exact_ commands used?  In the first bogart command, the values after -unassembled should not be in quotes.

What is the error reported in unitigger.err for the original command?

**Comment by satomimitsuhashi** [comment]
Sorry, originally, it was not quoted. I just tried it with quote and copied that by mistake. 
Here is the original one. 

bin/bogart -G ../name.gkpStore -O ../name.ovlStore -o ./name \
  -gs 50000  -eg 0.144 -eM 0.144 -el 500 \
  -dg 6 -db 6 -dr 3 -ca 2100 -cp 200 \
  -threads 4 -M 16 -unassembled 2 1000 1.0 2 > ./unitigger.err 2>&1

Nothing was reported in unitigger.err.

**Comment by brianwalenz** [comment]
There needs to be an error reported somewhere!

In a new empty directory (created in the same directory that has 4-unitigger), run the same command but without the redirection to unitigger.err, just
```
bogart -G ../name.gkpStore -O ../name.ovlStore -o ./name
-gs 50000 -eg 0.144 -eM 0.144 -el 500
-dg 6 -db 6 -dr 3 -ca 2100 -cp 200
-threads 4 -M 16 -unassembled 2 1000 1.0 2
```
Report back with whatever is printed to the screen (I don't need all of it, just the last ~50 lines or so) and a list of the files created.

**Comment by satomimitsuhashi** [comment]
It only says "Segmentation fault" and did not create any files.

**Comment by brianwalenz** [comment]
I didn't see this before; you're missing one value in the -unassembled option.  Is this being set somewhere?

http://canu.readthedocs.io/en/latest/parameter-reference.html#output-filtering

**Comment by satomimitsuhashi** [comment]
Yes. One parameter was missing. I thought it was four values in total.
I ran with - unassembled 2 1000 1.0 1.0 2 and it worked.
Thank you very much for your help.

**Comment by brianwalenz** [comment]
You got a bug fix out of it anyway; you'll be the last one to get tripped up by this.
