### ISSUE TITLE
alternative paths in contigs.fasta

### ISSUE THREAD

**Issue by akautt** [marbl/canu#514]
I recently ran Canu v.1.5 on a high-coverage PacBio Sequel data set of a mildly heterozygous fish specimen with the default settings and everything worked like a charm. Thanks for developing such an intuitive and readily usable tool! 

However, during a subsequent scaffolding step (done externally) we obtained rather poor results, which might be due to the fact that alternative paths are still included in the contigs file. 

I noticed that according to the manual (at least in the latest version of Canu) the *.contigs.fasta currently includes alternate paths by default and the *.bubbles.fasta is currently always empty (does not even get generated). 

Is there any way to figure out which contigs might represent alternative paths so that they be be removed? Or is there a command in Canu (in the consensus step, I presume) that I missed and that makes it avoid incorporating alternative paths into the final contigs file? My apologies if I'm missing something obvious here.

**Comment by skoren** [comment]
Yes, we've heard that having alternates can cause issues for some scaffolders. There isn't an easy way to remove the alternate paths within Canu. There are a couple of options on the FAQ page:
http://canu.readthedocs.io/en/latest/faq.html#what-parameters-can-i-tweak

You can try the "smash haplotypes together" options on your data which may collapse your haplotypes together depending on how diverged they are and how much structural variation exists between them. You would only need to redo the assembly part of the run (```canu -assemble -p asm -d asm -pacbio-corrected <old run>/asm.trimmedReads.fasta.gz corOutCoverage=200 ovlErrorRate=0.15 obtErrorRate=0.15``` )

Alternatively, working with your current assembly, we've used a couple of approaches with some success, the first is using BUSCO genes and removing the "secondary" hits for unique genes using something like this:
https://github.com/skingan/HomolContigsByAnnotation

Another option is to compute self-alignments of the contigs and filter out contigs which are largely contained within larger contigs. Something as simple as counting number of hits between pairs of contigs and filtering the shorter contig in the pair can work as well. However, this can be difficult depending on how heterozygous your haplotypes are and how repetitive the genome is.

**Comment by akautt** [comment]
Thanks a lot for the fast reply and pointing me in the right direction. The assembly is of a wild-caught individual, but nucleotide diversity is really, really low in our fish, so I didn't expect it to be a big problem.

Anyway, I am currently trying the assembly with the "smash haplotypes" settings as suggested and might try some of the other options to improve/validate the new assembly. 

Thanks again. That was very helpful.
