### ISSUE TITLE
Enquiry for canu-1.5 installation

### ISSUE THREAD

**Issue by zx0223winner** [marbl/canu#516]
**Remove this text before submitting your issue!**
Hi I got an error when I install the canu-1.5 on the linux cloud server.
I typed the command: **make -j 8**, it showed me below:

"
Building for 'Linux' '2.6.32-642.6.2.el6.x86_64' as 'amd64' into '/home/****/canu-1.5/Linux-amd64/{bin,obj}'
CC icc CXX icpc
...
....
compilation aborted for utgcns/libcns/unitigConsensus.C (code 4)
make: *** [/home/****/canu-1.5/Linux-amd64/obj/libcanu.a/utgcns/libcns/unitigConsensus.o] Error 4
"

I guess I need to install some other modules. But I am not sure, so I hope you could hep me fix it. Thanks.

**Comment by skoren** [comment]
Is that the full output for the compilation, that error message looks truncated. It looks like you're using intel's compiler rather than gcc, Canu has not been tested with Intel's compiler. However, I've confirmed it can be built with a recent version as long as you have the Boost library installed on your system, remove the ```src/utgcns/libbost``` folder, and run ```make BUILDSTACKTRACE=0```. You might encounter other errors though even if the build finishes.

I'd recommend instead using the pre-compiled binaries rather than building it yourself or installing GCC and using that to build instead.

**Comment by zx0223winner** [comment]
Thanks for your reply, I just tried to download the the pre-compiled binaries file ("canu-1.5.Linux-amd64.tar.xz")  and run with the command "xz -dc canu-1.5.*.tar.xz |tar -xf -". It still did not work. 

Should I install the Java SE 8 first? Cause I am using the could service with Linux system, I don't know how to install the java on it. 

Will thanks for helping fix the bugs!

**Comment by skoren** [comment]
No if the first didn't work you probably don't have XZ Utils installed on the system. What did the command report? You would need to install that and you would need the JVM to run Canu. Neither one should require administrator rights to install.

**Comment by zx0223winner** [comment]
After running it with the intel.hpp. It showed me like this.
"
[zx.txt](https://github.com/marbl/canu/files/1056186/zx.txt)

"

**Comment by skoren** [comment]
I'm confused, you said you were downloading the pre-compiled binaries but your text file is build output. Are you using a pre-compiled binary or trying to build again? There should be nothing to build for the precompiled binaries, they have no src.

As for building you have to use the command I posted (make BUILDSTACKTRACE=0) make sure to run make clean as well (make clean && make BUILDSTACKTRACE=0).

**Comment by zx0223winner** [comment]
ok gotcha, I will try as you said. Thanks

**Comment by zx0223winner** [comment]
You are right, the XZ Utils and JVM are all needed for me. It works when I type in canu. 
[zx.txt](https://github.com/marbl/canu/files/1056288/zx.txt)

But, I have trouble with install the JVM, the report error is seen as followed:
"
[xzha25@orc-login2 ~]$ java -version
Error occurred during initialization of VM
Could not reserve enough space for object heap
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
"
I installed the java with "jdk-8u131-linux-x64.tar" and set the PATH, but still didn't work?

**Comment by skoren** [comment]
Try explicitly setting the max memory for java (```java -Xmx1g -version```). Canu will set the memory when running java.
