### ISSUE TITLE
Enquiry for canu Quick Start 

### ISSUE THREAD

**Issue by zx0223winner** [marbl/canu#517]
Hi canu supporting team,

It is good news that I made canu-1.5.0 running on the cloud(Linux),  but I got stuck when I do the Quick Start step given by your web: http://canu.readthedocs.io/en/latest/quick-start.html

After I running with the command **canu -p ecoli -d ecoli-auto genomeSize=4.8m -pacbio-raw ~/p6.25x.fastq** , the result only give information as followed without any assembly information.

I want to figure out why? Will appreciate for your help!

The source code has been attached.
[zx.txt](https://github.com/marbl/canu/files/1059235/zx.txt)

**Comment by skoren** [comment]
That is the correct behavior, see http://canu.readthedocs.io/en/latest/tutorial.html#execution-configuration. The job is running on the grid, you can monitor it using qstat. When no jobs are running you can check the canu.out file in the ecoli-auto folder for the last output. It should report that it was done unless an error is encountered.
