### ISSUE TITLE
'$' at the end of correctedReads fasta reads

### ISSUE THREAD

**Issue by StefanoLonardi** [marbl/canu#519]
I am a long time user of CANU - thanks for your wonderful assembler. I am using the latest version of CANU
```
[stelo@head ~]$ ./canu/Linux-amd64/bin/canu -version
Canu snapshot v1.5 +54 changes (r8254 f356c2c3f2eb37b53c4e7bf11e927e3fdff4d747)
```
I have noticed that the file XYZ.correctedReads.fasta.gz is improperly formatted. I found a few of the corrected reads that end with "$" (which is not allowed DNA symbol). I had to remove the "$" in order to use the FASTA file in other tools.

Stefano

**Comment by brianwalenz** [comment]
Awesome!  I can confirm this occurs, once, in our drosophila test.  It'll get fixed, but not immediately.

**Comment by StefanoLonardi** [comment]
Hi Brian, I just wanted to let you. I will close this.

**Comment by brianwalenz** [comment]
In that case, I'll move it to one of the bug lists.
