### ISSUE TITLE
Enquiry for Canu results

### ISSUE THREAD

**Issue by zx0223winner** [marbl/canu#520]
Hi canu supporting team,

After running the command: _canu -p uwo -d uwo-auto genomeSize=250m -pacbio-raw Run323_669.B02_1.filtered_subreads.fastq_

I didn't get any assembled reads or contigs in the output file . The report looks like this:

[report.txt](https://github.com/marbl/canu/files/1062304/report.txt)

Another question: if I have more than one raw reads file and I am willing to assemble them with canu at once, how do I type the command of input file, like this? _-pacbio-raw 1.fastq, 2.fastq, 3.fastq_

Will thank for debugging!

**Comment by skoren** [comment]
There is no error in the log you posted. This is the same as issue #517. Canu runs by submitting array jobs to the grid then submitting itself to wait for them. Once they compete, Canu will resume and submit the next set of jobs. This happens multiple times during a run, as long as you have jobs submitted by Canu in the grid scheduler it is running. You can check the canu.out file in the assembly directory which has the latest assembly outputs, it will report an error if a run fails.
