### ISSUE TITLE
Jobs freezing during trimming?

### ISSUE THREAD

**Issue by mw55309** [marbl/canu#521]
Hi 

Have you ever experienced jobs freezing during trimming?

I'm at the trimming/overlapper stage.  Most jobs (20-odd) have finished.  Now my qstat looks like this:

```sh
2754477 0.00411 obtovl_can mwatson9     r     06/01/2017 09:56:29 eddie@node2i16.ecdf.ed.ac.uk       8 10
2754478 0.00411 obtovl_can mwatson9     r     06/01/2017 09:56:29 eddie@node2i16.ecdf.ed.ac.uk       8 23
2754480 0.00411 obtovl_can mwatson9     r     06/01/2017 09:58:42 eddie@node2i26.ecdf.ed.ac.uk       8 27
```

So three jobs still going

But if I look at those jobs, there have been few updates:

```sh
ls -lrt trimming/1-overlapper/
total 4104
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3047 May 24 09:09 canutest9.partition.err
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp   116 May 24 09:09 canutest9.partition.ovlbat
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp   203 May 24 09:09 canutest9.partition.ovljob
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  2089 May 24 09:09 canutest9.partition.ovlopt
-rwx--x--x 1 mwatson9 datastore_eb_groups_watson_grp  5818 May 24 09:09 overlap.sh
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3660 May 24 09:29 overlap.1.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3700 May 24 10:08 overlap.2.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3745 May 24 10:54 overlap.29.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3762 May 24 11:44 overlap.5.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3665 May 24 11:58 overlap.3.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3700 May 24 12:08 overlap.4.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3766 May 24 12:18 overlap.6.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3769 May 24 12:39 overlap.7.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3723 May 24 13:15 overlap.8.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3729 May 24 14:35 overlap.9.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3736 May 24 14:55 overlap.11.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3743 May 24 16:07 overlap.12.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3756 May 24 16:26 overlap.14.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3762 May 24 17:03 overlap.15.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3763 May 24 17:53 overlap.16.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3765 May 24 18:44 overlap.17.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3765 May 24 19:37 overlap.19.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3775 May 25 01:12 overlap.28.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3767 May 25 05:39 overlap.20.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3771 May 25 06:40 overlap.24.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3775 May 25 08:00 overlap.26.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3747 May 25 09:14 overlap.13.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  3763 May 25 12:04 overlap.22.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp 11534 May 28 20:59 overlap.18.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  6951 May 29 16:17 overlap.21.out
-rwxr-xr-x 1 mwatson9 datastore_eb_groups_watson_grp   288 Jun  1 08:56 overlap.jobSubmit.sh
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp    71 Jun  1 08:56 overlap.jobSubmit.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp 11134 Jun  1 17:37 overlap.27.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp 14620 Jun  6 21:56 overlap.25.out
drwx--S--- 2 mwatson9 datastore_eb_groups_watson_grp  4096 Jun  6 21:56 001
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp 11268 Jun  8 03:32 overlap.10.out
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp 13203 Jun  9 12:43 overlap.23.out
```

And in 001

```
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  1006840 May 28 20:59 000018.counts
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp      248 May 28 20:59 000018.stats
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp 23204884 May 29 16:17 000021.ovb
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  1169800 May 29 16:17 000021.counts
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp      250 May 29 16:17 000021.stats
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  8388608 Jun  2 00:10 000027.ovb.WORKING
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  8388608 Jun  2 08:04 000010.ovb.WORKING
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp 29417903 Jun  6 21:56 000025.ovb
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp  1391476 Jun  6 21:56 000025.counts
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp      251 Jun  6 21:56 000025.stats
-rw------- 1 mwatson9 datastore_eb_groups_watson_grp 20971520 Jun  7 01:44 000023.ovb.WORKING
```

So whilst job 23 seems still to be active, jobs 10 and 27 seem stale with no updates to files for quite a few days.

They have been running for over a week.  They will die after 10 days due to my settings.

Have you seen this before?

Cheers
Mick

**Comment by mw55309** [comment]
BTW this was a restart, because the same three jobs failed last time

**Comment by skoren** [comment]
Sadly this is probably the overlapper going crazy on a small subset of reads, we've seen some extreme straggler jobs. Try increasing the number of threads in overlap.sh and re-running those jobs to see if they will complete faster.

**Comment by mw55309** [comment]
Thanks, that's kind of what I thought.  I gave it more RAM last time, you think threads are more important here?

Is there any way to identify which reads are the problem?

**Comment by mw55309** [comment]
On the issue of threads, I have noticed that my trimming overlapper jobs all have:
```
Num_PThreads          2
```
They are submitted with:
```
-l h_vmem=4g -pe sharedmem 16
```
i.e. 16 possible threads and 64Gb RAM

FYI my canu.defaults is

```
# Add site specific options (for setting up Grid or limiting memory/threads) here.
gridEngineSubmitCommand=/exports/cmvm/eddie/eb/groups/watson_grp/rumen_nanopore_temp/canu_test/qsub
gridEngineThreadsOption=-pe sharedmem THREADS
gridEngineMemoryOption=-l h_vmem=MEMORY
gridEngineArrayMaxJobs=5000
gridOptions= -l h_rt=240:00:00 -P roslin_faang -V -R y
mhapMemory=32-64
gridOptionsCORMHAP= -l h_vmem=4g -pe sharedmem 16
gridOptionsOBTMHAP= -l h_vmem=4g -pe sharedmem 16
gridOptionsUTGMHAP= -l h_vmem=4g -pe sharedmem 16
corMemory=64G
corThreads=8
obtovlMemory=64G
obtovlThreads=16
obtmhapMemory=64G
obtmhapThreads=16
obtmmapMemory=64G
obtmmapThreads=16
```

How do I increase the Num_PThreads option?

**Comment by brianwalenz** [comment]
If you changed this setting in the middle of an assembly, canu won't use it until the script that runs the job is removed (1-overlapper/overlap.sh).  Canu does not recreate these scripts on every run.  In this case, it's probably just as easy (and safer) to edit overlap.sh by hand.

Is the canu configuration report (at the start of the canu logging) showing 2 or 16 threads?  If 2, there's another problem somewhere.

**Comment by mw55309** [comment]
Hi Guys

I doubled the number of threads from 8 to 16 - one of the jobs finished, two haven't and are still running.

What I really need to do is ID the reads that are causing this and remove them.

Is there any way I can get a dump out of the reads causing the problem?

Cheers
Mick

**Comment by skoren** [comment]
I don't think there is an easy way, maybe @brianwalenz can comment.

You could just decrease the identity slightly (from the 14% or 0.144 to 0.12 or 0.10) for the problem partitions. It will run significantly faster in my experience in this case.

**Comment by mw55309** [comment]
OK thanks @skoren 

FYI with 16 threads and after over a week of running, one of the 3 problem jobs core dumped with:

```sh
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Failed with 'Aborted'; backtrace (libbacktrace):

Failed with 'Segmentation fault'; backtrace (libbacktrace):
```

**Comment by supanthee** [comment]
A similar question

How do we know if the job is ongoing or freezing? My macbook pro is not that high spec so I expect the analysis will be slow but I am afraid if the analysis has stopped working. I do check the disk space to make sure that analysis is going and there are ups and down in the free space available.

This is the display I have been looking at my terminal for past 10 hours. Any thoughts, please

Finished on Tue Jun 27 05:53:36 2017 (lickety-split) with 14.912 GB free disk space
----------------------------------------
--
-- Configured 2 overlapInCore jobs.
-- Finished stage 'obt-overlapConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting concurrent execution on Tue Jun 27 05:53:36 2017 with 14.912 GB free disk space (2 processes; 1 concurrently)

    cd trimming/1-overlapper
    ./overlap.sh 1 > ./overlap.000001.out 2>&1

**Comment by mw55309** [comment]
Just to note, increased threads (double!) allowed two jobs to finish, but one is still stubbornly carrying on :/

**Comment by danrdanny** [comment]
I am having a similar problem with a few trimming/overlapper jobs running for a week or longer. In my case it's job 23.

```
~/canu/trimming/1-overlapper/001]$ ls -lrth
...only showing end of the list...
-rwxrwxr-- 1 dem dem 524K Jul 10 06:10 000022.counts
-rwxrwxr-- 1 dem dem  251 Jul 10 06:10 000022.stats
-rwxrwxr-- 1 dem dem  49M Jul 10 14:21 000023.ovb.WORKING
-rwxrwxr-- 1 dem dem  47M Jul 10 14:53 000024.ovb
-rwxrwxr-- 1 dem dem 571K Jul 10 14:53 000024.counts
-rwxrwxr-- 1 dem dem  251 Jul 10 14:53 000024.stats
```

For others having this problem, and to make sure I did this correctly, I just wanted to be explicit as to how I fixed it.

1. Killed the canu process
2. Edit `trimming/1-overlapper/overlap.sh` and change the line `-t <threads>` to whatever the new number of threads is. For example, I started canu with 32, but it was set to 8 in overlap.sh.
3. Also edit `--maxerate 0.144` to `--maxerate 0.10`
4. Restart canu

It looks like this worked, as overlapInCore is now using 32 threads. It's just always mildly terrifying to kill a program that's been running for weeks.

**Comment by johnomics** [comment]
+1 for this. obtovl job 172 of 174 ran for five days with no progress, although it was still active. Cancelled, then followed @danrdanny's advice (thanks!), upping from 4 threads to 64. Job finished in 35 minutes.

I also added `gridOptionsobtovl="-l h_vmem=5g -pe smp 64"` to the canu command to run this on our cluster.

**Comment by dkainer** [comment]
related question - is it normal behaviour during Trimming that the overlapper (ovl) jobs take longer and longer as they increase in job index? The size of the .WORKING files, and hence the output .ovb files, appears to generally increase from job 000001 through to the later jobs. This is accompanied by longer and longer run time per job.

file sizes of output .ovb files:
000001.ovb     651,958
000002.ovb  1,879,904
000003.ovb  3,195,960
000004.ovb  3,812,839
...
000025.ovb  31,574,835
....
000095.ovb  89,651,900
000096.ovb  85,057,348

The early trimming jobs execute and complete in a matter of minutes while the latter ones take many many hours, if not days. Is this expected?

**Comment by megancamilla** [comment]
Hi @danrdanny @johnomics  many thanks for your comments on this issue.

I've tried editing overlapper.sh as well as overlap.jobSubmit-01.sh in my 1-overlapper directory.

However when I re-start canu (I'm restarting from scratch, running in grid mode, command below) my overlap.jobSubmit-01.sh gets re-written and -t gets set back to the lower number of threads, where my job is frozen. Trying to figure out why this file is getting re-made and how to "re-start" without this getting overwritten.

Thanks,

Megan


```
1) Kill canu process
2) edit overlapper.sh
3) edit  overlap.jobSubmit-01.sh
4) restart canu with below command
canu -p WAI1664_canu -d WAI1664_nano_canu genomeSize=40m \
-nanopore-raw /home/smrtanalysis/smrtanalysis/WAI1664_canu1.6/WAI1664_all.fastq stopOnReadQuality=false minReadLength=2000 gnuplotTested=true \
useGrid=true gridEngine=SGE gridEngineMemoryOption="-l mem_free=MEMORY" gridOptions="-q hugemem.q -l h_vmem=30G
5) overalpper.sh remains the same as my edits (with higher number of threads) BUT overlap.jobSubmit-01.sh is re-made and set back to lower number of threads...
```

**Comment by skoren** [comment]
Canu will always overwrite the submit script when it runs. You need to manually run the edited overlap.jobSubmit-01.sh file and when those jobs complete, resume Canu.

**Comment by OnlyHigh** [comment]
Based in a recent experience, Canu sometimes also get stuck in "./overlap.sh 1 > ./overlap.000001.out 2>&1" with contaminated samples or from different organisms.

**Comment by MRuinels** [comment]
Hi!
I am having the same issue but with canu1.8 :  trimming is stopping for days at the same point. I could find the overlap.sh file and changed the threads but whre do I find the overlap.jobSubmit-01.sh? 
thanks M

**Comment by skoren** [comment]
1.8 addresses most of the issues from before (too high a kmer threshold, too high error rate for nanopore data by default).

The overlap.jobSubmit-01.sh only exists if you're running on the grid. Days is not necessarily unexpected depending on genome size and compute resources available and 
There are a few options on the FAQ for speeding up further for this step (restricting kmers with ovlMerDistinct=0.975 or using -fast) but both would require you to kill the current job, remove the trimming folder completely, and restart the assembly.
