### ISSUE TITLE
PBSpro minimum memory setting

### ISSUE THREAD

**Issue by hodgett** [marbl/canu#522]
I have ovB  and oea jobs failing due to not enough memory;
```
maxError fraction: 1.000 percent: 100.000 encoded: 4095
Bucketizing ../1-overlapper/results/000317.ovb
=>> PBS: job killed: mem 3324036kb exceeded limit 3145728kb
```
I have set minMemory to 4 but this does not seem to take. Below you can see in the CONFIGURE CANU stage that the memory being set is 3g for ovb and 2g for oea.

What is the setting for the minimum memory for all jobs in a queuing system like PBSpro? Have I used the wrong setting, or is this a bug?

```
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_112' (from '/pkg/suse12/software/java/1.8.0_112/bin/java').
-- Detected gnuplot version '5.0 patchlevel 3' (from 'gnuplot') and image format 'png'.
-- Detected 32 CPUs and 126 gigabytes of memory.
-- Limited to 125 gigabytes from maxMemory option.
-- Detected PBSPro 'PBSPro_13.1.1.162303' with 'pbsnodes' binary in /opt/pbs/default/bin/pbsnodes.
-- Detecting PBSPro resources.
-- 
-- Found   2 hosts with  12 cores and   62 GB memory under PBSPro control.
-- Found  16 hosts with  14 cores and   62 GB memory under PBSPro control.
-- Found  32 hosts with   8 cores and  126 GB memory under PBSPro control.
-- Found 120 hosts with   8 cores and   62 GB memory under PBSPro control.
-- Found   4 hosts with   8 cores and  252 GB memory under PBSPro control.
-- Found  32 hosts with  10 cores and  126 GB memory under PBSPro control.
-- Found  58 hosts with  10 cores and   62 GB memory under PBSPro control.
-- Found   2 hosts with  14 cores and  126 GB memory under PBSPro control.
-- Found 160 hosts with  12 cores and  126 GB memory under PBSPro control.
-- Found  32 hosts with   8 cores and   31 GB memory under PBSPro control.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl    125 GB   12 CPUs  (k-mer counting)
-- Grid:  cormhap   20 GB    4 CPUs  (overlap detection with mhap)
-- Grid:  obtovl     7 GB    2 CPUs  (overlap detection)
-- Grid:  utgovl     7 GB    2 CPUs  (overlap detection)
-- Grid:  cor       10 GB    2 CPUs  (read correction)
-- Grid:  ovb        3 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       32 GB    1 CPU   (overlap store sorting)
-- Grid:  red        7 GB    2 CPUs  (read error detection)
-- Grid:  oea        2 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat       62 GB    6 CPUs  (contig construction)
-- Grid:  cns      125 GB    8 CPUs  (consensus)
-- Grid:  gfa       15 GB    4 CPUs  (GFA alignment and processing)
```

Even more interesting is when I use the setting gridOptionsOVB="-l mem=4g" I get both memory settings in scripts/1-bucketize.jobSubmit.sh and it still bombs out;

```
#!/bin/sh

qsub -j oe \
  -l mem=3g -l nodes=1:ppn=1 -M m.hodgett@qut.edu.au -m abe -V -l walltime=196:00:00 -W umask=0007 -l mem=8g \
  -N "ovB_banaMH15_MH_canu_1.5b" \
   \
  ./scripts/1-bucketize.sh  \
> ./scripts/1-bucketize.jobSubmit.out 2>&1
```

Using   ovbMemory=4g and  oeaMemory=4g  does seem to work. But why then does minMemory have no effect on setting a minumum size?

**Comment by skoren** [comment]
MinMemory isn't used on the grid, only on a local machine so I think this is why it is not setting a limit. We should probably change that.

Your command above doesn't have mem=4g anywhere, i only see mem=8g, was that run with "-l mem=8g". I see nothing wrong with that command, does it get submitted and get killed or does it fail to submit? It is possible PBSPro doesn't let you specify memory more than once (wouldn't surprise me given how inflexible PBSPro is in general). When you specify ovbMemory Canu will only put the -l mem=4g once.

**Comment by hodgett** [comment]
Yes, it would be useful if minMemory was implemented for grid jobs too. 
I have also just has another assembly fail. The issue was weird because the log indicated it was failing doing oea, but it turned out that there memory allocation for ovs was the issue. It would appear that the algorithm for calculating how much memory to assign is too conservative for grid work, especially since we don't have much in the way of swap on the grid nodes.

**Comment by hodgett** [comment]
Ok, the answer to minMemory has been answered, I'll open a separate issue for the other xxxMemory issues as I think that is a different issue. I'll leave it up to you to close this issue, you may need it open until you decide how this setting should work for grid jobs.

**Comment by skoren** [comment]
Closing and moving to feature request, make min memory the minimum used to submit jobs to grid on grid runs and used memory for steps
