### ISSUE TITLE
canu output ecoli circular genome with some diff at the begin and end

### ISSUE THREAD

**Issue by wangyugui** [marbl/canu#524]
Hi.

canu output ecoli circular genome with some diff at the begin and end.

ecoli dataset:https://github.com/PacificBiosciences/DevNet/wiki/Datasets

```
# canu --version
Canu snapshot v1.5 +63 changes (r8263 2710d31104bfc381be7b0df5eda46849f5bd7d22)
# it is same on old version too.


# blastn -task megablast -db /biowrk/ecoli/canu/ecoli.contigs.fasta -num_threads 44 -evalue 1.0e-30 -perc_identity 98.0 -min_raw_gapped_score 1000 -parse_deflines -outfmt '6 qaccver saccver pident length mismatch gapopen qstart qend sstart send evalue bitscore qlen slen' -query /biowrk/ecoli/canu/ecoli.contigs.fasta
tig00000880     tig00000880     99.985  19912   0       3       1       19911   4642438 4662347 0.0     36751   4669666 4669666
tig00000880     tig00000880     99.982  5536    0       1       21709   27243   4664131 4669666 0.0     10216   4669666 4669666
```

because of circular genome, the 1-21,709   should be same as (over 98%) 4,642,438-4,669,666 ?
but we can see there are some diff (below 98%) in 19,911-21,709   and 4,662,347 -4,664,131 .

**Comment by wangyugui** [comment]
circlator will remove one side , but kept worse one. 
the removed side is more close to GCF_000005845.2

**Comment by skoren** [comment]
This is the P6-C4 dataset? We've seen a similar result in our benchmarks. It seems in this case the "clonal" genome is not really clonal. The canu contigs ends have an inversion with respect to each other (and with respect to the reference on one end):
```
1	3478	4642557	4646033	3478	3477	99.97	4663489	4663489	0.07	0.07	tig00000053	tig00000053
1502	1667	16716	16881	166	166	92.77	4663489	4663489	0.00	0.00	tig00000053	tig00000053
1502	1667	4659265	4659430	166	166	92.77	4663489	4663489	0.00	0.00	tig00000053	tig00000053
3458	5303	4647852	4646013	1846	1840	99.14	4663489	4663489	0.04	0.04	tig00000053	tig00000053
4120	4486	3383667	3384033	367	367	92.64	4663489	4663489	0.01	0.01	tig00000053	tig00000053
5283	20932	4647832	4663489	15650	15658	99.87	4663489	4663489	0.34	0.34	tig00000053	tig00000053
```

In my case the start of the assembly has an inversion with respect to the reference while the end of the assembly agrees with it:
```
1       1097583 1213289 115691  1097583 1097599 99.99   4641652 4663489 23.65   23.54   gi|556503834|ref|NC_000913.3|   tig00000053
1096961 1207805 116132  5283    110845  110850  99.99   4641652 4663489 2.39    2.38    gi|556503834|ref|NC_000913.3|   tig00000053
1207785 1209623 3458    5303    1839    1846    99.19   4641652 4663489 0.04    0.04    gi|556503834|ref|NC_000913.3|   tig00000053
1209603 1213079 3478    1       3477    3478    99.97   4641652 4663489 0.07    0.07    gi|556503834|ref|NC_000913.3|   tig00000053
1192158 1873039 4663489 3982588 680882  680902  99.99   4641652 4663489 14.67   14.60   gi|556503834|ref|NC_000913.3|   tig00000053
```

So the positions 1192158-1213079 are covered twice by the assembly, once with an inversion from 1207785-1209623 and once without.

Looking at IGV at both ends of the assembly, there are reads across both forms of the contig so there is some population variation in this sample. Here are some reads aligning full length to the canonical form
```
m140930_121059_sherri_c100688052550000001823139503241542_s1_p0/133880/0_24636	tig00000053	86.3163	4627256	4649208	175	24636	24636
m140930_121059_sherri_c100688052550000001823139503241542_s1_p0/140788/1482_19916	tig00000053	87.0714	4634728	4650963	870	18434	18434
m140930_121059_sherri_c100688052550000001823139503241542_s1_p0/143563/0_21343	tig00000053	89.5333	4635542	4655459	32	21339	21343
```
and the alternate:
```
m140930_121059_sherri_c100688052550000001823139503241542_s1_p0/138647/7022_30221	tig00000053	88.8519	2175	13838	0	12374	23199
m140930_121059_sherri_c100688052550000001823139503241542_s1_p0/138977/7568_23649	tig00000053	87.8027	1475	11802	0	11210	16081
m140930_121059_sherri_c100688052550000001823139503241542_s1_p0/152734/0_6433	tig00000053	86.9593	1791	7419	293	6429	6433
m140930_121059_sherri_c100688052550000001823139503241542_s1_p0/135528/0_7198	tig00000053	87.7417	622	6827	379	7182	7198
```

Circlator probably kept one arbitrarily and one would agree with the reference and one wouldn't but both are supported by the data.

**Comment by wangyugui** [comment]
1)Yes. This is the P6-C4 dataset.
2) It is confirmed by skoren that There is some population variation in this sample. so let's close it.

Thanks a lot.

**Comment by wangyugui** [comment]
What will is the output when one human(diploid) have two diff MHC region?
The two MHCs have enough diff ,such as one have HLA-B, and anther does not have it.

**Comment by wangyugui** [comment]
Should we add a process to detect this primary/alternate  such as diploid that have big diff region(>1Kbp), and that have big same region too(> 2* minOverlapLength) ?

for this ecoli circular genome, the output problem can be fixed by downstream circlator.
but we need this for diploid such as human MHC region?

**Comment by wangyugui** [comment]
test result with pbsim data.

case 1:
data: 60x pbsim data(ref: heading 1M of the ecoloi reference sequence,no circular data)
result: 1contig with the size of near 1M => pbsim data is good

case2:
data: mix of  60x pbsim data(ref: heading 1M of the ecoloi reference sequence,no circular data)  + 60x pbsim data (ref: heading 1M of the ecoloi reference sequence wit 2k bp insert(from ebv,no circular data)
result: 
```
# cat pbsim.contigs.gfa
H       VN:Z:bogart/edges
S       tig00000001     *       LN:i:1000749
S       tig00000181     *       LN:i:22960
```
so there is already some basic support.

**Comment by skoren** [comment]
If you have enough structural variation between haplotypes, you will get both haplotypes represented as separate contigs. Canu does not filter them currently, if you want to run some post-processing to filter the primary/alternate contigs for your assembly you can do that.
