### ISSUE TITLE
failing to build ovlStore on re-run

### ISSUE THREAD

**Issue by hodgett** [marbl/canu#526]
We have been trying to trouble shoot and optimise Canu on our highly utilised PBSpro cluster for some time so that we can gave a stable platform for various assemblies. I feel we are getting close, we are gaining more knowledge as we go. Our challenge at the moment is restarting failed runs due to any variety of conditions that can cause an individual job to fail. To date we have had only little success correcting issues and restarting Canu.

Currently I have problems at the ovlStore building step. There were originally some jobs that failed as a result of low memory settings (see issue #522). After manually correctly and running these jobs I found canu wasn't able to get past the ovlStore building step, it continued claiming those same jobs were failed. I then tried to delete the whole .BUILDING folder, but it still fails to complete building. The err in canu.out is ```-- 1053 overlap store sorter jobs failed:``` i.e. all of them.

I have noticed that after deleting the ovlStore.BUILDING folder and re-running canu.sh that there were were some repeated tasks. Below you can see two jobs with similar conditions; 2120678 and 2120679. 

 ```
=========================================================================================
>              Job                   NDS    CPUs       Mem  (Gb)    Walltime   Host/Array/
>           ID     Name         State     Req Util%  Req'd  Used  Req'd  Used   GPU/mics
> =========================================================================================
>      2120678[] ovS_MH15_MH_canu_1.5b  Q   1     1 ---      5.2 -----    196 -----  1-1000 
>      2120679[] ovS_MH15_MH_canu_1.5b  Q   1     1 ---      5.2 -----    196 -----  1-1000 
>      2120680[] ovS_MH15_MH_canu_1.5b  Q   1     1 ---      5.2 -----    196 -----  1-53 
>        2120681 canu_MH15_MH_canu_1.5b  H   1     1 ---      4.2 -----    196 -----  
> =========================================================================================
```
I looked at the details for each and they were indeed exactly the same;
```
    Submit_arguments = -j oe -l mem=5g -l nodes=1:ppn=1 -V -l walltime=196:00:0
	0 -W umask=0007 -N ovS_MH15_MH_canu_1.5b -J 1-1000 ./scripts/2-sort
	.sh
```

In the ovlStore.BUILDING folder I see very very small XXXX XXXX.evalueLen XXXX.index XXXX.info files, I also see the bucketXXXX folders with slices in them.

Is there a problem restarting canu this way? Have I missed something? What is the proper process for restarting canu after failed store building?

**Comment by skoren** [comment]
It is fine to restart Canu in the middle of store building, it will resume and try to run the next step or re-run any failed jobs. I'm going to guess if some set of jobs were reported as failing then there was missing output.

As for the extra jobs now, were all previous Canu jobs on the grid killed before you restarted? One of those jobs could be left over from a previous execution which would cause issues. The ```canu.out``` log file should have information on how many sort jobs need to be run and how they were submitted, along with the ```scripts/2-sort.jobSubmit.sh``` in the BUILDING folder. It looks like your grid is limiting array jobs to 1000 so Canu is splitting the job into multiple pieces, it should be passing an offset to the job to let  it know it should not start at 0 but I don't see that in the submit arguments.

**Comment by hodgett** [comment]
All jobs for this were already terminated.
The limit to jobs that can be submitted is very high, much higher than 1000 so I don't see why there should be any limit applied now. I have seen canu submit more jobs than that in the past. How can I increase that for canu?
I included the line from canu.out that claims ```1053 overlap store sorter jobs failed```. That's all of them! The two scripts submitted to the job queue for the 1-1000 range are identical in every way, there is nothing different so they are repeated for some reason. I think the second iteration of the same job is what is causing the problem.

**Comment by skoren** [comment]
It looks like Canu always assumes a 1000 limit on array jobs on PBSPro, is there a way to check maximum array job size on PBSPro, can you run ```qmgr -c 'p s'``` on your system and post output if it works?

Also can you post the full canu.out file along with the ```scripts/2-sort.jobSubmit.sh``` file not just one line from it, that will give exact submit commands used to submit and confirm how many jobs Canu is submitting.

You can overwrite the default by setting gridEngineArrayMaxJobs, try ```gridEngineArrayMaxJobs=5000```. I don't see anywhere in the code where the same jobs would be submitted twice, I would guess one of those arrays of 1000 jobs is left over from an earlier run. I would erase all your jobs and re-run the Canu command with the gridEngineArrayMaxJobs set to see how it submits the jobs.

**Comment by hodgett** [comment]
```qmgr -c 'p s'``` gives ```set server max_array_size = 10000```
I'll have to see if I have a copy of the original canu.out and associated jobSubmit.sh, I have done a lot since.
I have another assembly already in process, I will need to wait a few days before i can try ```gridEngineArrayMaxJobs```, I have now incorporated that in to canu.sh

**Comment by hodgett** [comment]
Ok, after restarting the process I have gone past this stage and have interesting results. Setting ```gridEngineArrayMaxJobs=5000``` worked, and can now see that there are 2053 jobs in the array! So if the original limit to arraymaxjobs was setting at 1000 then there would have been two arrays of 1000 and one of 53, which is what we were seeing. The fact that this wasn't working means that there are probably two issues here;
1. the gridEngineArrayMaxJobs option is being detected and set wrong, and
2. the parameters for the arrays (-J 1-1000) must be getting set wrong if it can complete one set of 1000, but then fail on the next 1000 and 53. 

For me the workaround is setting gridEngineArrayMaxJobs, but these issues may need to be looked at for a future release.

**Comment by skoren** [comment]
Yes, the array size was definitely not being detected but always defaulting to 1000. Given that qmgr works on your system, we can add support for detecting an actual array limit. When Canu runs multiple array jobs for a task, it supplies a command-line offset for the jobs which I'm guessing is not being passed through or recognized on your system so all jobs ran with offset 0 (only computing jobs 0-1000 not 1000-2000 or 2000-2053). I know on PBS (non-Pro) you need to pass options using -F instead of on the command line like on other grids. Could you run a simple test using the following script:
```
#!/bin/sh

perl='/usr/bin/env perl'

baseid=0
offset=$1

if [ x$offset = x ]; then
  offset=0
fi
jobid=`expr $baseid + $offset`

echo "The offset=($offset) and jobid=($jobid)"
```

Submit it to the grid as ```script.sh 1000``` or ```-F 1000 script.sh 1000``` and see what it outputs in both cases.

**Comment by hodgett** [comment]
I have submitted using `qsub -- $PWD/array_jobs_tst.sh -F 1000` and got back in the error file;
```
expr: non-integer argument
The offset=(-F) and jobid=()
```
and `qsub -- $PWD/array_jobs_tst.sh 1000` returned, 
`The offset=(1000) and jobid=(1000)`

Also, the man page does not reference `-F` but does have `-J` job range;

> 
>        -J range
>                Declares  that  this  job is an array job.  Sets job's array attribute to TRUE.  The argument range identifies
>                the integers greater than or equal to zero that are associated with the subjobs of the array.  range is speci-
>                fied  in  the form X-Y[:Z]  where X is the first index, Y is the upper bound on the indices and Z is the step-
>                ping factor.  For example,  2-7:2 will produce indices of 2, 4, and 6.  If Z is not specified, it is taken  to
>                be 1.

**Comment by brianwalenz** [comment]
I fixed the gridEngineArrayMaxJobs problem.

With the latest code, and running ecoli or something similar, you can test the multiple-job problem by decreasing the mhap batch size:
```
gridEngineArrayMaxJobs=2
mhapBlockSize=100
stopAfter=overlap
useGrid=remote
```
should give about 25 mhap jobs with two tasks in each job.  The stopAfter will prevent it from running past 1-overlapper - so you can easily retry by removing correction/1-overlapper.  useGrid=remote will set everything up but not submit jobs - this will let you examine the jobSubmit scripts before submitting.  Running only the second jobSubmit script should run jobs 3 and 4.

The mechanism used here is a bit complicated.  The second jobSubmit script will submit tasks 1 and 2 to run command (`precompute.sh 2`).  precompute.sh will add the two to run jobs 3 and 4.  Similar for the third jobSubmit script, using offset 4 to get jobs 5 and 6.

If you do find a problem, open a new issue, include the second jobSubmit script and mhap outputs.
