### ISSUE TITLE
alignGFA Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by nottwy** [marbl/canu#527]
Problem:
I try to re-run totally several times. But they all failed at alignGFA step.
I'm sure I have enough memory space.
So is there any reasonable guess of cause?
The information you want is listed below. 
Thanks!

Have fun!
---------------------------Information you want, my friends.---------------------------
version:
Canu snapshot v1.5 +41 changes (r8241 90e69a6353c7a7fe7e9d710d9bd6447fc32bf7d9)

command:
```
data="subreads.fasta"
size="400m"
cer="0.091"
directory="20170613_cer_${cer}"
prefix="xxc"

srun -c 16 -p hpxg canu \
 -p ${prefix} -d ${directory} genomeSize=${size} \
 -pacbio-raw ${data} \
 correctedErrorRate=${cer} \
 gnuplotTested=true \
 > std_${flag}.log 2> err_${flag}.log
```

system: 
Linux

canu-scripts/canu.20.out:
```
-- BEGIN ASSEMBLY
--
--
-- GFA alignment failed.
--

ABORT:
ABORT: Canu snapshot v1.5 +41 changes (r8241 90e69a6353c7a7fe7e9d710d9bd6447fc32bf7d9)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   canu iteration count too high, stopping pipeline (most likely a problem in the grid-based computes).
ABORT:

```

**Comment by skoren** [comment]
This feature was recently added since the 1.5 release and has had lots of code changes recently. Try updating to the latest and see if that fixes the crash. You might also have to re-run consensus and unitigging (by removing 4-unitigger, 5-consensus, asm.utgStore, asm.ctgStore) in the unitigging folder.
