### ISSUE TITLE
canu container broken due to missing gnuplot shared library

### ISSUE THREAD

**Issue by ruyjau** [marbl/canu#529]
Hello! Did you make the canu container present in https://biocontainers.pro ?
Please excuse me and ignore this if you didn't. The container is missing a gnuplot shared library.

groot$ rkt-run -i quay.io/biocontainers/canu:1.5--pl5.22.0_0
/ $ gnuplot
gnuplot: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
/ $ type gnuplot
gnuplot is a tracked alias for /usr/local/bin/gnuplot
/ $ ldd /usr/local/bin/gnuplot
/lib64/ld-linux-x86-64.so.2 (0x5644fdbab000)
Error loading shared library libz.so.1: No such file or directory (needed by /usr/local/bin/gnuplot)
libstdc++.so.6 => /usr/local/bin/../lib/libstdc++.so.6 (0x7fbbf5b7c000)
libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x5644fdbab000)
libgcc_s.so.1 => /usr/local/bin/../lib/libgcc_s.so.1 (0x7fbbf5965000)
libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x5644fdbab000)
ld-linux-x86-64.so.2 => /lib/ld-linux-x86-64.so.2 (0x7fbbf5743000)
Error relocating /usr/local/bin/gnuplot: __rawmemchr: symbol not found
Error relocating /usr/local/bin/gnuplot: __isnan: symbol not found
Error relocating /usr/local/bin/gnuplot: __strtod_internal: symbol not found

**Comment by brianwalenz** [comment]
Nope, not us.  Canu should run without gnuplot, you might need to give it gnuplotTested=true.
