### ISSUE TITLE
xxxMemory set too low on some grid jobs

### ISSUE THREAD

**Issue by hodgett** [marbl/canu#530]
This issue was derived from issue #522. 
We have an ongoing issue where the process fails at various points due to PBS killing jobs for mem exceeded issues.
We have had this appear for ovs, ovb, oea, bat so far. It looks like the estimates being made for how much memory to allocate for a grid job are too low, in some cases possibly only calculating the requirements for the job only and not taking in to account system overheads? Or is there something not right in how the data is being examined to determine how much memory to allocate?
An example comes from ./unitigging/4-unitigger/bat_MH15_MH_canu_1.5c.o2130285
```
Running job 1 based on PBS_ARRAY_INDEX=1 and offset=0.
=>> PBS: job killed: mem 38427376kb exceeded limit 33554432kb

-----
PBS Job 2130285.pbs
CPU time  : 00:16:12
Wall time : 00:13:10
Mem usage : 38427376kb
```

**Comment by skoren** [comment]
This could also be an issue in how pbspro tracks memory usage vs other grids or a higher overheard on your systems, we commonly run on slurm and other grids which kill jobs for exceeding memory without issue. The bat is most surprising, I have never seen it exceed requested memory before. A workaround would be to use the gridOptions to set a higher memory limit for each step as long as your grid allows jobs to be submitted with multiple memory requests (-l mem=3 -l mem=8) taking the latest as the job request. 

What is the canu preamble report for the memory it is trying to request for the failing jobs? It seems bat requested 33.5 go but it should always request whole numbers. What is top reporting in terms of the virtual and physical memory usage for the jobs before it is killed?

**Comment by brianwalenz** [comment]
Any update?  Better?  Worse?  Managing with a workaround?

**Comment by skoren** [comment]
Closing, inactive. Please open a new issue if you have other questions or followup.
