### ISSUE TITLE
calling canu for testing without an input file

### ISSUE THREAD

**Issue by ruyjau** [marbl/canu#531]
Hello!
I'm talking with the bioconda developers who made the canu docker container.

(https://github.com/bioconda/bioconda-recipes/issues/4963)

I have this question: Is it possible to call canu, to test it, without giving an input file?
Beyond --help, -version and -options, is there a way to let canu run without other arguments?

**Comment by brianwalenz** [comment]
Giving it an empty file will get it to configure itself, failing after the first 'real' command is run.  It'll complain that 'gatekeeper store exists, but contains no reads'.

The lambda reads (http://www.cbcb.umd.edu/software/PBcR/data/sampleData.tar.gz) are super quick to assemble.
