### ISSUE TITLE
ovlStore hung?

### ISSUE THREAD

**Issue by mschatz** [marbl/canu#532]
Im attempting an assembly of corn using the latest precompiled release (1.5) from about 56x PacBio coverage of the genome using the grid at CSHL. It successfully computed all the overlaps for error correction (about 3.9TB in correction/1-overlapper/results), but now has been hung building the ovlStore for more than 1 week. 

The specific command that is hung is this:
```
mschatz  22212  0.0  0.1 326540 245288 ?       S    Jun12   0:00 /isilon/seq/schatz/bluearc_backup/schatz/software/packages/canu-1.5/Linux-amd64/bin/ovStoreSorter -deletelate -M 4 -O . -G ../first_att_05_22.gkpStore -F 3025 -job 149 273
```

The last update in the log directory was from several days ago:
```
$ ls -tlrs | tail
50 -rw-r--r-- 1 mschatz 10083 11625 Jun 13 05:55 2-sort.2706.out
50 -rw-r--r-- 1 mschatz 10083 11847 Jun 13 05:55 2-sort.2761.out
50 -rw-r--r-- 1 mschatz 10083 11847 Jun 13 05:55 2-sort.2755.out
50 -rw-r--r-- 1 mschatz 10083 11845 Jun 13 05:55 2-sort.2779.out
50 -rw-r--r-- 1 mschatz 10083 11845 Jun 13 05:55 2-sort.2789.out
```

And the last file seems to be okay:
```
$ tail 2-sort.2789.out
Loading 1178803 overlaps from './bucket0262/slice2789'.
Loading 1156943 overlaps from './bucket0263/slice2789'.
Loading 1250159 overlaps from './bucket0264/slice2789'.
Loading 1400771 overlaps from './bucket0265/slice2789'.
Loading 11903966 overlaps from './bucket0266/slice2789'.
Sorting.
Writing output.
Writing 126094303 overlaps.
Created ovStore segment './2789' with 0 overlaps for reads from 4294967295 to 0.
Success.
```

But Im seeing a bunch of out of memory errors:
```
$ grep bad_alloc *
2-sort.149.out:terminate called after throwing an instance of 'std::bad_alloc'
2-sort.149.out:  what():  std::bad_alloc
2-sort.1732.out:terminate called after throwing an instance of 'std::bad_alloc'
2-sort.1732.out:  what():  std::bad_alloc
2-sort.1735.out:terminate called after throwing an instance of 'std::bad_alloc'
2-sort.1735.out:  what():  std::bad_alloc
2-sort.1739.out:terminate called after throwing an instance of 'std::bad_alloc'
2-sort.1739.out:  what():  std::bad_alloc
2-sort.1740.out:terminate called after throwing an instance of 'std::bad_alloc'
2-sort.1740.out:  what():  std::bad_alloc
2-sort.1824.out:terminate called after throwing an instance of 'std::bad_alloc'
2-sort.1824.out:  what():  std::bad_alloc
2-sort.1830.out:terminate called after throwing an instance of 'std::bad_alloc'
2-sort.1830.out:  what():  std::bad_alloc
2-sort.1950.out:terminate called after throwing an instance of 'std::bad_alloc'
2-sort.1950.out:  what():  std::bad_alloc
<snip>
```

Here is the full log for one of them:
```
$ cat 2-sort.149.out
Running job 149 based on SGE_TASK_ID=149 and offset=0.
Max processes per user limited to 65536, no increase possible.

Changed max open files from 65535 to 262144 (max 262144).

Found 820731 overlaps from './bucket0001/sliceSizes'.
Found 924781 overlaps from './bucket0005/sliceSizes'.
Found 937581 overlaps from './bucket0009/sliceSizes'.
Found 1066790 overlaps from './bucket0013/sliceSizes'.
Found 1025033 overlaps from './bucket0017/sliceSizes'.
Found 981368 overlaps from './bucket0021/sliceSizes'.
Found 969732 overlaps from './bucket0025/sliceSizes'.
Found 26640178 overlaps from './bucket0029/sliceSizes'.
Found 36118337 overlaps from './bucket0030/sliceSizes'.
Found 32946933 overlaps from './bucket0031/sliceSizes'.
Found 23563534 overlaps from './bucket0032/sliceSizes'.
Overlaps need 3.75 GB memory, allowed to use up to (via -M) 4 GB.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Failed with 'Aborted'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::102 in _Z17AS_UTL_catchCrashiP7siginfoPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
../../gcc-4.8.2/libstdc++-v3/libsupc++/vterminate.cc::95 in _ZN9__gnu_cxx27__verbose_terminate_handlerEv()
../../gcc-4.8.2/libstdc++-v3/libsupc++/eh_terminate.cc::38 in _ZN10__cxxabiv111__terminateEPFvvE()
../../gcc-4.8.2/libstdc++-v3/libsupc++/eh_terminate.cc::48 in _ZSt9terminatev()
../../gcc-4.8.2/libstdc++-v3/libsupc++/eh_throw.cc::84 in __cxa_throw()
../../gcc-4.8.2/libstdc++-v3/libsupc++/new_op.cc::56 in _Znwm()
../../gcc-4.8.2/libstdc++-v3/libsupc++/new_opv.cc::32 in _Znam()
stores/ovOverlap.H::192 in _ZN9ovOverlap16allocateOverlapsEP7gkStorem()
stores/ovStoreSorter.C::213 in main()
(null)::0 in (null)()
(null)::0 in (null)()
```

Should I just kill the hung task now? Im guessing I'll need to restart rebuilding the ovlStore. Is there a way to do this gracefully or should I just delete the entire ovlStore and resubmit canu? Also, how do I increase the memory request for these jobs since apparently it needs more than requested.

Let me know if you need any other details.

Thanks so much!

Mike

**Comment by brianwalenz** [comment]
Hi Mike-

Graceful is possible.  Delete everything from the grid: the 2-sort array and the single canu job (delete the canu job first, so it doesn't respawn).  Then, edit the *BUILDING/scripts/2-sort.jobSubmit.sh script to increase the memory request and run that script to restart sorting.  Jobs that have completed will detect their output and do nothing.  When the sort jobs have completed, restart canu as before.

That all assumes that SGE is actually listening to the memory request, and that some other user isn't starving you of requested memory.

If you increase memory through canu, the sort jobs will also increase in size, and then you'd need to delete the incomplete store and start over.

**Comment by mschatz** [comment]
Thanks Brian, you are a life saver. I did as you suggested and boosted the RAM request to 10G instead of 5G. It looks like it is running on the previously failed tasks, but those tasks are finishing suspiciously quickly. For example, here is the new log file for task 149 that previously failed:

```
$ cat 2-sort.149.out
Running job 149 based on SGE_TASK_ID=149 and offset=0.
Max processes per user limited to 65536, no increase possible.

Changed max open files from 65535 to 262144 (max 262144).

Found 820731 overlaps from './bucket0001/sliceSizes'.
Found 924781 overlaps from './bucket0005/sliceSizes'.
Found 937581 overlaps from './bucket0009/sliceSizes'.
Found 1066790 overlaps from './bucket0013/sliceSizes'.
Found 1025033 overlaps from './bucket0017/sliceSizes'.
Found 981368 overlaps from './bucket0021/sliceSizes'.
Found 969732 overlaps from './bucket0025/sliceSizes'.
Found 26640178 overlaps from './bucket0029/sliceSizes'.
Found 36118337 overlaps from './bucket0030/sliceSizes'.
Found 32946933 overlaps from './bucket0031/sliceSizes'.
Found 23563534 overlaps from './bucket0032/sliceSizes'.
Overlaps need 3.75 GB memory, allowed to use up to (via -M) 4 GB.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Failed with 'Aborted'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::102 in _Z17AS_UTL_catchCrashiP7siginfoPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
../../gcc-4.8.2/libstdc++-v3/libsupc++/vterminate.cc::95 in _ZN9__gnu_cxx27__verbose_terminate_handlerEv()
../../gcc-4.8.2/libstdc++-v3/libsupc++/eh_terminate.cc::38 in _ZN10__cxxabiv111__terminateEPFvvE()
../../gcc-4.8.2/libstdc++-v3/libsupc++/eh_terminate.cc::48 in _ZSt9terminatev()
../../gcc-4.8.2/libstdc++-v3/libsupc++/eh_throw.cc::84 in __cxa_throw()
../../gcc-4.8.2/libstdc++-v3/libsupc++/new_op.cc::56 in _Znwm()
../../gcc-4.8.2/libstdc++-v3/libsupc++/new_opv.cc::32 in _Znam()
stores/ovOverlap.H::192 in _ZN9ovOverlap16allocateOverlapsEP7gkStorem()
stores/ovStoreSorter.C::213 in main()
(null)::0 in (null)()
(null)::0 in (null)()
Running job 149 based on SGE_TASK_ID=149 and offset=0.
Max processes per user limited to 65536, no increase possible.

Changed max open files from 65535 to 262144 (max 262144).

Job 149 is running or finished (remove './0149.ovs' or -force to try again).
Success.
```

Not just the last couple lines are added from the error log above. Should I delete the ./0149.ovs file or use the -force option? I assume I would need to apply this change to all the ones that previously ran out of memory.

Thanks a million!
Mike

**Comment by mschatz** [comment]
My restart of BUILDING/scripts/2-sort.jobSubmit.sh finished, but all of the new tasks finished suspiciously quickly. Any suggestions?

Mike

**Comment by brianwalenz** [comment]
Argh, I forgot about that, sorry.  All the bogus ovs files should be size zero, so just delete them.  The -force option will force every job to recompute.  Also get rid of the log files; SGE just tacks on new outputs.

**Comment by mschatz** [comment]
That seems to have done the trick! Here is the new log for that one that previously crashed:

```
$ cat 2-sort.149.out
Running job 149 based on SGE_TASK_ID=149 and offset=0.
Max processes per user limited to 65536, no increase possible.

Changed max open files from 65535 to 262144 (max 262144).

Found 820731 overlaps from './bucket0001/sliceSizes'.
Found 924781 overlaps from './bucket0005/sliceSizes'.
Found 937581 overlaps from './bucket0009/sliceSizes'.
Found 1066790 overlaps from './bucket0013/sliceSizes'.
Found 1025033 overlaps from './bucket0017/sliceSizes'.
Found 981368 overlaps from './bucket0021/sliceSizes'.
Found 969732 overlaps from './bucket0025/sliceSizes'.
Found 26640178 overlaps from './bucket0029/sliceSizes'.
Found 36118337 overlaps from './bucket0030/sliceSizes'.
Found 32946933 overlaps from './bucket0031/sliceSizes'.
Found 23563534 overlaps from './bucket0032/sliceSizes'.
Overlaps need 3.75 GB memory, allowed to use up to (via -M) 4 GB.
Loading 820731 overlaps from './bucket0001/slice0149'.
Loading 924781 overlaps from './bucket0005/slice0149'.
Loading 937581 overlaps from './bucket0009/slice0149'.
Loading 1066790 overlaps from './bucket0013/slice0149'.
Loading 1025033 overlaps from './bucket0017/slice0149'.
Loading 981368 overlaps from './bucket0021/slice0149'.
Loading 969732 overlaps from './bucket0025/slice0149'.
Loading 26640178 overlaps from './bucket0029/slice0149'.
Loading 36118337 overlaps from './bucket0030/slice0149'.
Loading 32946933 overlaps from './bucket0031/slice0149'.
Loading 23563534 overlaps from './bucket0032/slice0149'.
Sorting.
Writing output.
Writing 125994998 overlaps.
Created ovStore segment './0149' with 0 overlaps for reads from 4294967295 to 0.
Success.
```

The other failed tasks are knock-on-wood resolving themselves as well. Thank you!

Mike

**Comment by brianwalenz** [comment]
Yay!  Are these jobs using more than 3.75gb, or is this a quirk of your grid and/or current load?  These haven't been failing on the one grid that pays careful attention to memory usage.

**Comment by mschatz** [comment]
It doesnt seem to be using more than 3.75GB now. Our cluster doesnt enforce
the reservations, so it was probably just another user using more than
requested that crashed my jobs

Thanks again for your help

Mike

**Comment by mschatz** [comment]
Something really crazy happened. I launched the 2-sort.jobSubmit.sh twice times to get the last few jobs through. This seemed to work fine and all of the log files showed the tasks completed successfully. After that I restarted canu which began with the ovStoreIndexer as expected via 3-index.sh script. 

But then the crazy part happened and all of the bucket files are empty except for 2505 and 2512, which were the last two I needed to restart. To make matters worse, canu deleted the mhap output files, so I guess I need to go back to square one and restart overlapping everything. Ugh. Any ideas what happened here, and how to prevent it?

Mike

**Comment by brianwalenz** [comment]
Never seen that before, nope.  This step is supposed to be extremely paranoid, and is usually bullet proof.

I'm guessing the usual #### files don't exist then, and the 'index' file doesn't exist?  Any errors in the 3-index logs?

**Comment by mschatz** [comment]
The other #### bucket files are there, just zero bytes in size. The
3-index.err file is really weird:

```
$ head 3-index.err
Processing './index'
  No overlaps found.
Processing './index'
  No overlaps found.
Processing './index'
  No overlaps found.
Processing './index'
  No overlaps found.
Processing './index'
  No overlaps found.

$ tail 3-index.err
  No overlaps found.
Processing './2512.index'
  No overlaps found.
Processing './2512.index'
  No overlaps found.
Created ovStore '.' with 0 overlaps for reads from 4294967295 to 0.

Removing intermediate files.
Finished.
Success.
```

Here is the log files for one of the two batches that still has overlaps
(one of the two that needed to be restarted last)

```
$ tail 2-sort.2512.out
Loading 1233474 overlaps from './bucket0254/slice2512'.
Loading 1325593 overlaps from './bucket0255/slice2512'.
Loading 1158250 overlaps from './bucket0256/slice2512'.
Loading 1307597 overlaps from './bucket0257/slice2512'.
Loading 21943090 overlaps from './bucket0258/slice2512'.
Sorting.
Writing output.
Writing 126016682 overlaps.
Created ovStore segment './2512' with 0 overlaps for reads from 4294967295
to 0.
Success.
```

And here is the another one with zero bytes:

```
$ tail 2-sort.2513.out
Max processes per user limited to 65536, no increase possible.

Changed max open files from 65535 to 262144 (max 262144).

Overlaps need 0.00 GB memory, allowed to use up to (via -M) 4 GB.
Sorting.
Writing output.
Writing 0 overlaps.
Created ovStore segment './2513' with 0 overlaps for reads from 4294967295
to 0.
Success.
```

I dont understand why these say the segments have 0 overlaps in them.  Any
ideas?

Ive restarted overlapping-- last time that took a few days to complete

Thanks again,

Mike

**Comment by brianwalenz** [comment]
:-(

Add in saveOverlaps=true at your convenience.  This will save the overlapper/mhap outputs.

No ideas.  The read range of MAXINT to 0 is quite odd, implying bucketizing might have failed.  Any change you might have hit out of disk or a quota limit?  That hasn't been tested much, and canu hasn't handled it well in other places.  IIRC Linux only reports the error on fclose().

**Comment by skoren** [comment]
I've seen empty sort files before, I believe the 2-sort.sh script is not safe, that is, it won't detect completed jobs. This step just scans the bucket folders for any files from that partition but if a previous step already ran and cleaned up, there are no bucket files and thus no overlaps. I think it was probably your re-start of the 2-sort.sh that caused a bunch of the overlaps to get dumped and corrupted the store. We should fix that, @brianwalenz

**Comment by mschatz** [comment]
Yeah, the volume has ~100TB free, so shouldnt have been a space issue. Please take a look at the 2-sort.sh script. Thank you,

Mike

**Comment by brianwalenz** [comment]
Yes, it was broken.  The ovStoreSorter command was using one of the output files as a sentinel to say it had started processing.  I suspect a name change didn't propagate to this command, as a result, the command was failing to notice that the result existed.

Canu was masking this problem, by only rerunning jobs that needed to be rerun.  When I had you resubmit all jobs manually, they happily sorted zero overlaps and overwrote your correct outputs.

It will now report `Job 1 is running (remove './0001.ovs' or -force to try again).` for a crashed/running job, and `Job 1 is finished (remove './0001' or -force to try again).` for a completed job.

A hint on restarting: When the canu pipeline manages these jobs, it will remove the sentinel 0001.ovs file before (re)starting jobs.  If the job is started outside of the pipeline, by resubmitting jobs to the grid, the 0001.ovs sentinels will still exist, and all the jobs will fail as above.  If you're sure no jobs are running, just delete all *.ovs files in the *.ovlStore.BUILDING directory before restarting.

A second bug was resulting in the "Created ovStore segment ... with 0 overlaps" message regardless of how many overlaps were present.

**Comment by mschatz** [comment]
Hi Brian,

All of the MHAP tasks have completed, although the ovlStore building failed
again (somewhat as expected). What do you recommend to restart this? Im
inclined to play it super safe and just write a for loop over all the tasks
that have ovs sentinel files and call 2-sort.sh directly. What would you
recommend?

Thank you,

Mike

**Comment by brianwalenz** [comment]
That would work - when things go bad I generally do the same, but I know what needs to be run.

Some tips for maximum paranoia:

- Remove write permission on 1-overlapper: `chmod -R ugo-w 1-overlapper`, or make a 'results-backup' directory and hard link to the results files (`mkdir results-backup ; cd results-backup ; ls ../results/* .`) - won't protect against overwriting, but will protect against accidental deletion.
- Remove the -deletelate flag in 2-sort.sh to preserve the bucket inputs.
- Remvoe write permission on the existing 4-digit files and the etc files with extensions.  This might cause problems in 3-index when it tries to remove the files with extensions.
- Test what happens when an ovs file exists, and when an output file exists - take one of the jobs to rerun, run it with the ovs file in place, then rename that ovs to just four digits and rerun.  Both should stop immediately.  If not, ctrl-c to kill the job before it does anything.

When the 2-sort jobs are all done, you can then run 3-index by hand to finish building the store.  This step merges the various ####.* index files into one, finishing the store build.  Maximum paranoia would say to tar up or hardlink those files before running.

You should then have a complete store (ovStoreDump should be able to dump overlaps).  Renaming the store from *.ovlStore.BUILDING to *.ovlStore will then prevent canu from even entering the store building steps - notably skipping any cleanup of intermediate files.

**Comment by mschatz** [comment]
Thanks Brian! Will try this and let you know how it goes. Fingers crossed

Mike

**Comment by mschatz** [comment]
Success! I manually ran the last few dozen 2-sort jobs that failed, and
then manually ran the 3-index by hand to finish the store. Everything seems
to check out and it is evaluating the overlaps now for the 2-correction
phase.

The only slightly weird thing was there were a few jobs that had failed but
didnt leave an ovs file behind (but clearly crashed in the logs directory).
Restarting those by hand recovered the missing overlaps. Looking over the
logs, it looks like canu tried to restart things a couple times
automatically so the ovs files must have been clobbered at some point.

Thanks again -- now fingers crossed that these 10TB of overlaps lead to a
good assembly

Mike
