### ISSUE TITLE
Canu filling up disk/taking too long when assembling 'short' reads

### ISSUE THREAD

**Issue by BertVanm** [marbl/canu#535]
*This may be more of a question than a real issue*

I've been trying to assemble a metagenomic nanopore-dataset, containing a number of RNA viruses. Because these viruses probably only represent a small fraction of my reads, I've been trying to correct as many of the reads as possible before assembling them.

My dataset consists of ~4 million reads, average length between 300-400, totalling ~1.5 Gb.

The command I've been using is: 
```
Canu -p Test -d Test -nanopore-raw My/Path/reads.fasta -genomeSize=999m -corMinCoverage=0 -corOutCoverage=999 -MhapSensitivity=high minReadLength=200 minOverlapLength=100 stopOnReadQuality=false
```
I'm running this on a Linux server with 16 cores.

The command runs fine until it gets to the overlapping stage (cormhap). Canu splits the overlapping into 206 jobs, running one at a time, but after 48 hours, he's still on the first job, while already having generated >500 Gb of data. I had to kill this command due to a lack of available disk space.

Removing all reads >2 kb (which are mostly low quality artifacts) somewhat improves things (only 163 jobs) but again Canu is generating hundreds of Gb of data all while being on job 1/163.

My issue is that I do not have the disk space available for all this data (only 2.5 Tb free disk space) and that it seems to take an enormous amount of time (still stuck on job 1 after 48 hrs).

Is this what I should expect when trying to assemble millions of 'short' reads? Do you have any suggestions for what might speed up this assembly/reduce the amount of disk space I need?

I have tried assembling only the reads >1 kb (~5000 reads) and this worked without problem, so I'm guessing my issues are purely related to the amount of input data I use.

**Comment by skoren** [comment]
The number of reads isn't so much an issue as the length. Canu isn't really optimized for very short reads, at 200bp you lose the advantages of minhashing because you end up indexing the entire read anyway so this will significantly slow down computation. With 4m reads, you are on the scale of a 1gb genome (a human run has 15m reads) which would probably take >5k cpu hours on a normal length read set or a couple of weeks on your system and your dataset would likely be slower than this.

You can try switching the sensitivity to be lower ```MhapSensitivity=low``` which should speed up the computation and reduce space usage but I think fundamentally running through 4m short reads is going to be slow on 16-cores.

**Comment by BertVanm** [comment]
That's what I feared.
Do you think it's a good idea to split up my dataset into blocks of ~200k reads and try to assemble those separately?

**Comment by BertVanm** [comment]
Ok, I guess I'll have to look for another solution.

Something I tried yesterday was to only assemble the reads between 501-1000 nucleotides in length. However, I get this error during trimming: (*My apologies, I can't get it to format properly*)

-- BEGIN TRIMMING
--
----------------------------------------
-- Starting command on Tue Jun 27 09:51:37 2017 with 126.997 GB free disk space

    cd trimming/3-overlapbasedtrimming
    /home/bvmech0/canutest/splitReads \
      -G  ../phred10_501_1000.gkpStore \
      -O  ../phred10_501_1000.ovlStore \
      -Ci ./phred10_501_1000.1.trimReads.clear \
      -Co ./phred10_501_1000.2.splitReads.clear \
      -e  0.144 \
      -minlength 200 \
      -o  ./phred10_501_1000.2.splitReads \
    >     ./phred10_501_1000.2.splitReads.err 2>&1

-- Finished on Tue Jun 27 09:51:56 2017 (19 seconds) with 126.997 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 134.  (rc=34304)
ERROR:

CRASH:
CRASH: Canu snapshot v1.5 +47 changes (r8247 418b90656dd14f7c622f704634618031d4a39909)
CRASH: Please panic, this is abnormal.
ABORT:
CRASH:   splitReads failed.
CRASH:
CRASH: Failed at /home/bvmech0/canutest/lib/canu/OverlapBasedTrimming.pm line 157.
CRASH:  canu::OverlapBasedTrimming::splitReads('phred10_501_1000') called at /home/bvmech0/canutest/canu line 583
CRASH:
CRASH: Last 50 lines of the relevant log file (trimming/3-overlapbasedtrimming/phred10_501_1000.2.splitReads.err):
CRASH:
CRASH:


I'm running the following command on a 32-core linux device:
`canu -p phred10_501_1000 -d phred10_501_1000 -nanopore-raw input.fasta -corMinCoverage=0 -genomeSize=999m gnuplotTested=true -corOutCoverage=999 -MhapSensitivity=high -useGrid=false -stopOnReadQuality=false -minReadLength=200 -minOverlapLength=100
`

**Comment by brianwalenz** [comment]
This was possible fixed on June 13th in 542445b8162beeb24b4ee39eefd86caccab6f48f, so try updating.

There should have also been a crash report generated.  Did you disable it when compiling?  Old versions of gcc will do this automatically.  The build should also report this at the start, e.g., `make | less`

**Comment by BertVanm** [comment]
Ok, so I'm getting closer.
I updated canu and it finished trimming successfully but now it gives an error at the unitigging stage:

```
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'bat' concurrent execution on Tue Jun 27 18:19:14 2017 with 123.311 GB free disk space (1 processes; 2 concurrently)

    cd unitigging/4-unitigger
    ./unitigger.sh 1 > ./unitigger.000001.out 2>&1

-- Finished on Tue Jun 27 18:19:41 2017 (27 seconds) with 123.311 GB free disk space
----------------------------------------
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'bat' concurrent execution on Tue Jun 27 18:19:41 2017 with 123.311 GB free disk space (1 processes; 2 concurrently)

    cd unitigging/4-unitigger
    ./unitigger.sh 1 > ./unitigger.000001.out 2>&1

-- Finished on Tue Jun 27 18:20:09 2017 (28 seconds) with 123.282 GB free disk space
----------------------------------------
--
-- Unitigger failed.
--

ABORT:
ABORT: Canu snapshot v1.5 +98 changes (r8298 ffb36aae9419bd600247237e8cfdb378b8fbedf2)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   canu iteration count too high, stopping pipeline (most likely a problem in the grid-based computes).
ABORT:
```

When I check the contents of unitigger.000001.out, it says:

```
Running job 1 based on command line options.
./unitigger.sh: 86: ./unitigger.sh: cannot create ../phred10_501_1000.ctgStore/seqDB.v001.sizes.txt: Directory nonexistent
```

Any idea what goes wrong here?

**Comment by skoren** [comment]
There have been a lot of changes in bogart since the release and your commit, try updating and seeing if it runs with the latest code.

**Comment by BertVanm** [comment]
Works like a charm.

Thanks!
