### ISSUE TITLE
canu: command not found

### ISSUE THREAD

**Issue by supanthee** [marbl/canu#536]
I am new to canu or similar genome assembly tools. So far I have used only CLC Genomics. To start the first analysis using canu, I installed canu 1.5 and downloaded the fastq file from curl -L -o p6.25x.fastq http://gembox.cbcb.umd.edu/mhap/raw/ecoli_p6_25x.filtered.fastq
and utilized following command
canu \
 -p ecoli -d ecoli-auto \
 genomeSize=4.8m \
 -pacbio-raw p6.25x.fastq

Then the result I get is canu: command not found. Could anyone suggest me possible issues that I can overcome with. I am using  MacOS Sierra, 2.7 GHz Intel Core i5 processor, 8GB memory

Thanks

Suresh

**Comment by brianwalenz** [comment]
You need to tell the shell where to find the canu command.  You can do this either by running canu with the path to where you installed it (e.g., "/Users/suresh/canu/Darwin-amd64/bin/canu") or by setting the PATH environment variable to include that directory.

https://coolestguidesontheplanet.com/add-shell-path-osx/ has a decent explanation.

**Comment by supanthee** [comment]
Thanks
I have installed canu in the desktop/canu-1.5/Darwin-amd64/bin/canu. Now I run it using command

desktop Suresh$ canu-1.5/Darwin-amd64/bin/canu \
> -p ecoli -d ecoli-auto \
> genomeSize=4.8m \
> -pacbio-raw p6.25x.fastq

The output shows some error
-- Canu release v1.5
-- Detected Java(TM) Runtime Environment '1.8.0_131' (from 'java').

usage: canu [-version] \
            [-correct | -trim | -assemble | -trim-assemble] \
            [-s <assembly-specifications-file>] \
             -p <assembly-prefix> \
             -d <assembly-directory> \
             genomeSize=<number>[g|m|k] \
            [other-options] \
            [-pacbio-raw | -pacbio-corrected | -nanopore-raw | -nanopore-corrected] *fastq

  By default, all three stages (correct, trim, assemble) are computed.
  To compute only a single stage, use:
    -correct       - generate corrected reads
    -trim          - generate trimmed reads
    -assemble      - generate an assembly
    -trim-assemble - generate trimmed reads and then assemble them

  The assembly is computed in the (created) -d <assembly-directory>, with most
  files named using the -p <assembly-prefix>.

  The genome size is your best guess of the genome size of what is being assembled.
  It is used mostly to compute coverage in reads.  Fractional values are allowed: '4.7m'
  is the same as '4700k' and '4700000'

  A full list of options can be printed with '-options'.  All options
  can be supplied in an optional sepc file.

  Reads can be either FASTA or FASTQ format, uncompressed, or compressed
  with gz, bz2 or xz.  Reads are specified by the technology they were
  generated with:
    -pacbio-raw         <files>
    -pacbio-corrected   <files>
    -nanopore-raw       <files>
    -nanopore-corrected <files>

Complete documentation at http://canu.readthedocs.org/en/latest/

ERROR:  Failed to run gnuplot from 'gnuplot'.ERROR:  Set option gnuplot=<path-to-gnuplot> or gnuplotTested=true to skip this test and not generate plots.

How do I overcome this gunplot issue?

**Comment by brianwalenz** [comment]
I'm guessing you don't have gnuplot installed, and our error message is a little messed up.

1. if gnuplot isn't installed, install it.
2. if it is installed, set canu option gnuplot to the path to it, eg, `canu gnuplot=/opt/local/bin/gnuplot ...`
3. disable plots by setting canu option gnuplotTested=true

**Comment by supanthee** [comment]
Thanks, it appears that the command below will work
canu-1.5/Darwin-amd64/bin/canu \
-p ecoli -d ecoli-auto \
genomeSize=4.8m \
gnuplotTested=true \
-pacbio-raw p6.25x.fastq

The output now shows


-- Canu release v1.5
-- Detected Java(TM) Runtime Environment '1.8.0_131' (from 'java').
-- Detected 4 CPUs and 8 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
-- Run   1 job  concurrently using    8 GB and   4 CPUs for stage 'meryl'.
-- Run   1 job  concurrently using    6 GB and   4 CPUs for stage 'mhap (cor)'.
-- Run   1 job  concurrently using    8 GB and   4 CPUs for stage 'overlapper (obt)'.
-- Run   1 job  concurrently using    8 GB and   4 CPUs for stage 'overlapper (utg)'.
-- Run   2 jobs concurrently using    8 GB and   2 CPUs for stage 'falcon_sense'.
-- Run   4 jobs concurrently using    2 GB and   1 CPU  for stage 'ovStore bucketizer'.
-- Run   4 jobs concurrently using    8 GB and   1 CPU  for stage 'ovStore sorting'.
-- Run   1 job  concurrently using    2 GB and   4 CPUs for stage 'read error detection'.
-- Run   4 jobs concurrently using    1 GB and   1 CPU  for stage 'overlap error adjustment'.
-- Run   1 job  concurrently using    8 GB and   4 CPUs for stage 'bogart'.
-- Run   4 jobs concurrently using    2 GB and   1 CPU  for stage 'GFA alignment and processing'.
-- Run   1 job  concurrently using    8 GB and   4 CPUs for stage 'consensus'.
--
-- Generating assembly 'ecoli' in '/Users/Suresh/Desktop/ecoli-auto'
--
-- Parameters:
--
--  genomeSize        4800000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0450 (  4.50%)
--
--
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Mon Jun 26 14:10:30 2017 with 11.641 GB free disk space

    cd correction
    /Users/Suresh/Desktop/canu-1.5/Darwin-amd64/bin/gatekeeperCreate \
      -minlength 1000 \
      -o ./ecoli.gkpStore.BUILDING \
      ./ecoli.gkpStore.gkp \
    > ./ecoli.gkpStore.BUILDING.err 2>&1

-- Finished on Mon Jun 26 14:10:30 2017 (lickety-split) with 11.611 GB free disk space
----------------------------------------
--
-- WARNING: gnuplot failed; no plots will appear in HTML output.
--
----------------------------------------
--
-- In gatekeeper store 'correction/ecoli.gkpStore':
--   Found 12528 reads.
--   Found 115899341 bases (24.14 times coverage).
--
--   Read length histogram (one '*' equals 20.62 reads):
--        0    999      0 
--     1000   1999   1444 **********************************************************************
--     2000   2999   1328 ****************************************************************
--     3000   3999   1065 ***************************************************
--     4000   4999    774 *************************************
--     5000   5999    668 ********************************
--     6000   6999    619 ******************************
--     7000   7999    618 *****************************
--     8000   8999    607 *****************************
--     9000   9999    560 ***************************
--    10000  10999    523 *************************
--    11000  11999    478 ***********************
--    12000  12999    429 ********************
--    13000  13999    379 ******************
--    14000  14999    366 *****************
--    15000  15999    353 *****************
--    16000  16999    329 ***************
--    17000  17999    297 **************
--    18000  18999    294 **************
--    19000  19999    283 *************
--    20000  20999    251 ************
--    21000  21999    195 *********
--    22000  22999    152 *******
--    23000  23999    132 ******
--    24000  24999     75 ***
--    25000  25999     66 ***
--    26000  26999     56 **
--    27000  27999     44 **
--    28000  28999     35 *
--    29000  29999     16 
--    30000  30999     21 *
--    31000  31999     18 
--    32000  32999     11 
--    33000  33999      8 
--    34000  34999      6 
--    35000  35999      6 
--    36000  36999     10 
--    37000  37999      2 
--    38000  38999      3 
--    39000  39999      2 
--    40000  40999      2 
--    41000  41999      2 
--    42000  42999      1 
-- Finished stage 'cor-gatekeeper', reset canuIteration.
-- Finished stage 'merylConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting concurrent execution on Mon Jun 26 14:10:31 2017 with 11.61 GB free disk space (1 processes; 1 concurrently)

    cd correction/0-mercounts
    ./meryl.sh 1 > ./meryl.000001.out 2>&1

-- Finished on Mon Jun 26 14:11:09 2017 (38 seconds) with 11.262 GB free disk space
----------------------------------------
-- Meryl finished successfully.
-- Finished stage 'merylCheck', reset canuIteration.
--
-- WARNING: gnuplot failed; no plots will appear in HTML output.
--
----------------------------------------
--
-- WARNING: gnuplot failed; no plots will appear in HTML output.

Next step is the assembly of my bacterial genome.

Thanks

**Comment by agampodi** [comment]
Thanks..!supanthee. You saved my day..!
