### ISSUE TITLE
index error in the trimming step

### ISSUE THREAD

**Issue by tangerzhang** [marbl/canu#542]
Hi, I am using canu v1.5 in CentOS 6.2 to assemble 10 gb plant genome and the option details are below:
#### Command line:    
canu -trim -s spec.txt -p Mol -d asm80X genomeSize=8g -pacbio-corrected asm.correctedReads.fasta.gz
#### Spec file:  
useGrid=1
gridOptions=-S /bin/bash -q all.q -l mem_free=32g
gridEngineThreadsOption=-pe mpi THREADS
gridEngineMemoryOption=-l mem_total=MEMORY
corOutCoverage=120
ovbMemory=24g
ovbThreads=12
maxMemory=800g
maxThreads=48
ovsMemory=32-128
ovsThreads=12
oeaMemory=32g
corMhapSensitivity=low  

However, I got errors in trimming/Mol.ovlStore.BUILDING/logs/3-index.err below:
Processing './0020.index'
  Now finished with fragments 1 to 550823 -- 22376910881 overlaps.
Processing './0021.index'
  Now finished with fragments 1 to 578506 -- 23442403860 overlaps.
Processing './0022.index'
  Now finished with fragments 1 to 605004 -- 24507883820 overlaps.
Processing './0023.index'
ovStoreIndexer: stores/ovStoreWriter.C:537: void ovStoreWriter::mergeInfoFiles(): Assertion `recs[rr]._overlapID == tot

Failed with 'Aborted'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::102 in _Z17AS_UTL_catchCrashiP7siginfoPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
stores/ovStoreWriter.C::537 in _ZN13ovStoreWriter14mergeInfoFilesEv()
stores/ovStoreIndexer.C::137 in main()
(null)::0 in (null)()
(null)::0 in (null)()
./scripts/3-index.sh: line 24:  3568 Aborted                 (core dumped) $bin/ovStoreIndexer -O . -F 1213
Failure.

Any suggestions to solve this problem?
Thanks

**Comment by skoren** [comment]
Were there any errors while running the 2-sort step, specifically partition 23? What are the file sizes of the index files in your ovlStore.BUILDING folder?

**Comment by brianwalenz** [comment]
No response.
