### ISSUE TITLE
task meryl failed to find a configuration to run on

### ISSUE THREAD

**Issue by Jorpaes** [marbl/canu#547]
Hello canu team,
I just start using canu, but when I tried to launch it a error occur, 
these is my comand
```
canu -p OE_assembly -d OE_assembly genomeSize=1.5g gnuplotTested=true corMinCoverage=0 corOvlErrorRate=0.1 -nanopore-raw Echis_good.fastq &> OE_assembly/canu.log

``` 
and these is the error code:
```
-- Canu release v1.5
-- Detected Java(TM) Runtime Environment '1.8.0_131' (from '/usr/lib/jvm/java-8-oracle/bin/java').
-- Detected 8 CPUs and 63 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
-- DEBUG
-- DEBUG
-- DEBUG Have 1 configurations; largest memory size 63 GB; most cores 8:
-- DEBUG   class0 - 1 machines with 8 cores with 63GB memory each.
-- DEBUG
--
-- Task meryl can't run on any available machines.
-- It is requesting 64-256 GB memory and 1-32 threads.
-- See above for hardware limits.
--
================================================================================
Don't panic, but a mostly harmless error occurred and Canu stopped.

Canu release v1.5 failed with:
task meryl failed to find a configuration to run on
```
Thank you in advance

**Comment by brianwalenz** [comment]
Canu has a set of hardcoded memory/thread requirements for each component.  These are set based on the genome size supplied.  Here, for a 1.5Gbp genome, it wants to use beterrn 64 and 256GB memory with 1 to 32 threads for the 'meryl' (counting kmers) phase.

You can change the requirements with 'merylMemory=60' (GB).  You'll probably also need to set 'batThreads=8 batMemory=60'.

**Comment by Jorpaes** [comment]
Thank you for your respond,

I have tried changing the 1.5g to 800m, and right now the program is running, once we obtain the results I will change the parameters as you have recommend.

Thank you for your swift respond!

**Comment by skoren** [comment]
You changed the genome size? That won't work because that is used to compute corrected outputs so you'll end up with <20x coverage of your genome rather than the targeted 40x. You should change the memory parameter @brianwalenz suggested not the genome size.

**Comment by Jorpaes** [comment]
Hello canu team,
Thank you for the respond, i have stopped the processes and changed the parameters, i needed to change the cns memory to 60 too and now the process is running.
Thanks for your support!
