### ISSUE TITLE
unitigger "stuck"?

### ISSUE THREAD

**Issue by StefanoLonardi** [marbl/canu#549]
I have been running CANU on a 210Gb genome and it has been taking a really long time. This genome is probably quite repetitive, but my previous runs of CANU on a 620Gb genome never took more than two week total. I started CANU on the 210Gb genome at the end of May, and the error correction and trimming took one week each.

The unitigger started June 15, and it has been working on `4-unitigger` since July 2nd (single thread). The only file I see changing is `unitigger.err` which is reported below.

```
==> PARAMETERS.
Resources:
  Memory                18 GB
  Compute Threads       8 (command line)
Lengths:
  Minimum read          0 bases
  Minimum overlap       500 bases
Overlap Error Rates:
  Graph                 0.045 (4.500%)
  Max                   0.045 (4.500%)
Deviations:
  Graph                 6.000
  Bubble                6.000
  Repeat                3.000
Edge Confusion:
  Absolute              2100
  Percent               200.0000
Unitig Construction:
  Minimum intersection  500 bases
  Maxiumum placements   2 positions
Debugging Enabled:
  (none)

==> LOADING AND FILTERING OVERLAPS.
ReadInfo()-- Using 1902058 reads, no minimum read length used.
OverlapCache()-- limited to 18432MB memory (user supplied).
OverlapCache()--      14MB for read data.
OverlapCache()--      29MB for best edges.
OverlapCache()--      50MB for unitig layouts.
OverlapCache()--       0MB for tigs.
OverlapCache()--      14MB for id maps.
OverlapCache()--     116MB for error profiles.
OverlapCache()--      21MB for overlap cache pointers.
OverlapCache()--      48MB for overlap cache initial bucket.
OverlapCache()--     128MB for overlap cache thread data.
OverlapCache()--       7MB for number of overlaps per read.
OverlapCache()--       0MB for other processes.
OverlapCache()-- ---------
OverlapCache()--     314MB for data structures (sum of above).
OverlapCache()--   18117MB available for overlaps.
OverlapCache()-- Loading number of overlaps per read.
OverlapCache()--  Retain at least 462 overlaps/read, based on 77.10x coverage.
OverlapCache()--  Initial guess at 624 overlaps/read (maximum 260832 overlaps/read).
OverlapCache()--     624 overlaps/read - load all for  963287 reads, some for  938771 reads -    775194071 overlaps to load - 11828MB
OverlapCache()--    1063 overlaps/read - load all for 1044544 reads, some for  857514 reads -   1167360155 overlaps to load - 17812MB
OverlapCache()--    1086 overlaps/read - load all for 1047581 reads, some for  854477 reads -   1187049479 overlaps to load - 18112MB
OverlapCache()-- minPer           = 462 overlaps/reads
OverlapCache()-- maxPer           = 1086 overlaps/reads
OverlapCache()-- numBelow         = 1047446 reads (all overlaps loaded)
OverlapCache()-- numEqual         = 135 reads (all overlaps loaded)
OverlapCache()-- numAbove         = 854477 reads (some overlaps loaded)
OverlapCache()-- totalLoad        = 1187049479 overlaps (  5.69%)
OverlapCache()-- availForOverlaps = 18117MB
OverlapCache()-- totalMemory      = 0MB for organization
OverlapCache()-- totalMemory      = 18112MB for overlaps
OverlapCache()-- totalMemory      = 18112MB used
OverlapCache()-- Loading: overlaps processed          140 (000.00%) loaded          140 (000.00%) droppeddupe            0 (000.00%)
OverlapCache()-- Loading: overlaps processed    385703737 (001.85%) loaded     53210956 (000.25%) droppeddupe      4162427 (000.02%)
OverlapCache()-- Loading: overlaps processed    769368307 (003.69%) loaded    105563750 (000.51%) droppeddupe      7904970 (000.04%)
OverlapCache()-- Loading: overlaps processed   1161921095 (005.57%) loaded    158419417 (000.76%) droppeddupe     12172577 (000.06%)
OverlapCache()-- Loading: overlaps processed   1589406901 (007.62%) loaded    213075060 (001.02%) droppeddupe     17178481 (000.08%)
```
The last time `unitigger.err` was updated was four days ago. 
I have updated CANU a couple of days ago to the HEAD so giving the version would be not informative. I guess the version of the unitigger currently running might be a 2-3 weeks older.

Any advice? Should I kill the process and try to restart?

**Comment by brianwalenz** [comment]
I can confirm: your genome is VERY repetitive.  Just above the "Loading" lines, the log shows how many overlaps per read bogart will use.  There are 850,000 reads with more than 1086 overlaps per read.  At this cutoff, ~94% of the overlaps (the totalLoad line) are excessively repetitive.

How big is the ovlStore directory?  Regardless, it is reading at a glacial pace.  At 10MB/sec, bogart could load 6.5TB of overlaps in 8 days, and logs say it only read 7.62% of them so far.  There could be disk/network problems.  At an 18gb memory limit, I doubt you're out of memory.

So, my guess here is that either the minimum overlap length is too low, or the kmer seed threshold was too high.  I'm betting the threshold is too high.  It is computed using 0-mercounts/*histogram as input and logs to 0-mercounts/*estMerThresh.err.  Can you post those for both the trimming/ and unitigging/ stages?  (I'm curious why trimming was so fast and unitigging is stuck; the threshold picked is in the corresponding *.out file.)

For the length, `ovStoreDump -G *gkpStore -O *ovlStore -d -eratelen` will dump the number of overlaps (third column) at various lengths (first column) and error rate (second column).  A heat map of this can show short repeats (small overlaps at high error) which could inform a more reasonable minimum overlap length.

The last option is to decrease the maximum error, currently at 4.5%.  This has great risk of shattering your assembly.

The bad news is that, unless it is a disk performance issue, you're back to recomputing overlaps.  Filtering out the repeat overlaps from the current store will have the same problem bogart has: something has to read all those overlaps.

**Comment by StefanoLonardi** [comment]
Brian,
thanks for your quick answer. The unitigging ovlStore is 428GB.

`phyto.ms22.estMerThresh.out`  in `trimming/0-mercounts/` says 38795
`phyto.ms22.estMerThresh.out` in `unitigging/0-mercounts/` says 37884

I have stored the output of ovStoreDump and the two histogram files (trimming and unitigging) in
https://www.dropbox.com/sh/6r2oxay87ovr8m6/AADeCSppheezqFOqETiOYm1ua?dl=0

It is definitely a nasty genome (i.e., repetitive)

**Comment by StefanoLonardi** [comment]
A few more items of info. The initial coverage was about 110x. I wanted CANU to correct all the reads (I used `corOutCoverage=110`, maybe it was a bad idea). The output of error correction was about 75x worth of data, and the output of trimming was about 73x. Would it help to re-run CANU without changing `corOutCoverage`?

**Comment by brianwalenz** [comment]
Nope.  corOutCoverage just changes which reads are corrected; a higher value will correct more shorter reads.  You can get the same effect on your current corrected reads by just ignoring the shorter reads when assembling: `canu -assemble minReadLength=X ... trimmedReads.fasta`.

But that could explain why there are so many overlaps: a transposon that all those short reads are hitting.  Filtering reads shorter than that would be safer than increasing the minimum overlap length.  This conflicts with trimming being fast - If anything, trimming should have been much much slower, since it uses any local alignment instead of a proper overlap.

What's in the ovlStore.summary, specifically, the 'repeat-cont' category?  These are (short) reads contained in some other read.  For comparison, here's drosophila:
```
category            reads     %          read length        feature size or coverage  analysis
----------------  -------  -------  ----------------------  ------------------------  --------------------
middle-missing        695    0.20     9265.98 +- 6659.51       1986.41 +- 2253.10    (bad trimming)
middle-hump            10    0.00     4939.90 +- 4273.77       2185.60 +- 4015.06    (bad trimming)
no-5-prime            384    0.11     5031.21 +- 4915.00       1842.62 +- 2231.72    (bad trimming)
no-3-prime            428    0.12     4937.32 +- 4560.02       1533.01 +- 1526.73    (bad trimming)

low-coverage         1427    0.41     3971.29 +- 3280.24          3.48 +- 2.05       (easy to assemble, potential for lower quality consensus)
unique             158772   45.90    16592.60 +- 4126.91         34.99 +- 8.78       (easy to assemble, perfect, yay)
repeat-cont         19731    5.70    13782.48 +- 5310.70        412.29 +- 568.91     (potential for consensus errors, no impact on assembly)
repeat-dove          1107    0.32    23848.43 +- 2883.06        272.28 +- 382.66     (hard to assemble, likely won't assemble correctly or even at all)

span-repeat         62840   18.17    17855.09 +- 4183.40       6039.64 +- 5346.54    (read spans a large repeat, usually easy to assemble)
uniq-repeat-cont    68170   19.71    15811.36 +- 3743.38                             (should be uniquely placed, low potential for consensus errors, no impact on assembly)
uniq-repeat-dove    14557    4.21    22037.47 +- 3968.35                             (will end contigs, potential to misassemble)
uniq-anchor         17390    5.03    17356.68 +- 4322.80       7168.35 +- 5522.18    (repeat read, with unique section, probable bad read)
```

A good next step would be to assemble the longest 40x of corrected reads.

**Comment by StefanoLonardi** [comment]
Here is  `phyto.ovlStore.summary` in the unitigging directory, I see that `repeat-cont` is very high.

```
category            reads     %          read length        feature size or coverage  analysis
----------------  -------  -------  ----------------------  ------------------------  --------------------
middle-missing       1153    0.06    13721.94 +- 7619.78        786.55 +- 975.08     (bad trimming)
middle-hump            26    0.00     1595.15 +- 883.07         187.65 +- 498.09     (bad trimming)
no-5-prime            764    0.04     1785.51 +- 2481.78        361.84 +- 462.36     (bad trimming)
no-3-prime            575    0.03     2537.23 +- 4080.63        458.26 +- 577.34     (bad trimming)

low-coverage         2864    0.15     1561.61 +- 1256.69          3.88 +- 2.10       (easy to assemble, potential for lower quality consensus)
unique              41392    2.18     5839.04 +- 4407.88         35.71 +- 8.01       (easy to assemble, perfect, yay)
repeat-cont       1401272   73.67     7020.51 +- 5876.35       3534.01 +- 10512.27   (potential for consensus errors, no impact on assembly)
repeat-dove         27734    1.46    23300.07 +- 4298.63       1090.53 +- 3522.47    (hard to assemble, likely won't assemble correctly or even at all)

span-repeat         33210    1.75    11271.09 +- 5977.91       5211.89 +- 5022.76    (read spans a large repeat, usually easy to assemble)
uniq-repeat-cont   194606   10.23    10596.63 +- 5090.13                             (should be uniquely placed, low potential for consensus errors, no impact on assembly)
uniq-repeat-dove    21183    1.11    20928.46 +- 4971.75                             (will end contigs, potential to misassemble)
uniq-anchor        175931    9.25    14555.00 +- 5605.44       4285.82 +- 4080.47    (repeat read, with unique section, probable bad read)
```

Are you suggesting to start from the longest 40x of corrected reads, or the longest 40x of trimmed reads?

**Comment by brianwalenz** [comment]
Trimmed.

Yeah, wow, 74% of the reads.  Looking at that, I can't make a convincing argument for any particular minimum read length.  Mean size of those reads is 3.5k, but the stdddev is massive, so hard to say what 'the repeat' size is.  On the other side, span-repeat says the repeat is 5.2k +- 5k.  Hopefully, 40x of reads will have a minimum larger than 5k.

**Comment by brianwalenz** [comment]
Cleaning up issues for the next release.  Any update?

**Comment by StefanoLonardi** [comment]
Brian, thanks for checking with me. I followed your advice: grabbed 44x worth of trimmed reads 12Kbp or longer and restarted the CANU. It took about 20 day, and at the end the results were quite disappointing. CANU's N50 is 135Kb compared to 558kb of FALCON and 430Kb of ABRUIJN. I am not sure why. 

Find below `phyto.ovlStore.summary`

```
category            reads     %          read length        feature size or coverage  analysis
----------------  -------  -------  ----------------------  ------------------------  --------------------
middle-missing        936    0.16    18545.35 +- 4254.55       1690.11 +- 2233.99    (bad trimming)
middle-hump             0    0.00        0.00 +- 0.00             0.00 +- 0.00       (bad trimming)
no-5-prime             25    0.00    18428.92 +- 4611.83        445.80 +- 972.59     (bad trimming)
no-3-prime             49    0.01    18419.88 +- 4541.49        518.84 +- 1048.24    (bad trimming)

low-coverage           17    0.00    14547.06 +- 2277.27          3.97 +- 1.81       (easy to assemble, potential for lower quality consensus)
unique             104972   18.37    16626.67 +- 3604.01         30.67 +- 8.20       (easy to assemble, perfect, yay)
repeat-cont        113161   19.80    16016.42 +- 3144.91       1935.28 +- 3392.58    (potential for consensus errors, no impacton assembly)
repeat-dove          4147    0.73    23850.87 +- 4184.18        962.09 +- 2359.05    (hard to assemble, likely won't assemble correctly or even at all)

span-repeat         29893    5.23    17602.83 +- 4174.52       6888.17 +- 6066.15    (read spans a large repeat, usually easy to assemble)
uniq-repeat-cont   176298   30.85    16076.84 +- 2816.91                             (should be uniquely placed, low potential for consensus errors, no impact on assembly)
uniq-repeat-dove    33234    5.81    22330.96 +- 4232.55                             (will end contigs, potential to misassemble)
uniq-anchor        108815   19.04    17444.51 +- 3961.41       6829.41 +- 5087.26    (repeat read, with unique section, probable bad read)
```

**Comment by brianwalenz** [comment]
Bummer.  Not sure what else to suggest.
