### ISSUE TITLE
CIGAR string in contig.gfa

### ISSUE THREAD

**Issue by taoistly** [marbl/canu#550]
According to gfa-spec, L-line in GFA format looks like:
`L <From> <FromOrient> <To> <ToOrient> <CIGAR>`

In CANU(v1.5), the CIGAR string takes `<From>` as query, and `<To>` as reference.
Would you mind considering swaping them as https://github.com/GFA-spec/GFA-spec/issues/53
I guess this may be a little bit straightforward.

Thank you in advance.

**Comment by skoren** [comment]
The GFA spec is ambiguous about the To and From sequences, we had issues before with the orientations. I see in the referenced issue the CIGAR is defined as using the <From> as the reference but as far as I see the spec isn't updated yet? 

I think it makes sense to leave this as is and just wait for Canu's update to GFA2 which explicitly lists fragment A's position and B's positions so the alignment would then use A as the reference and B as the query. I'll close this issue and move it to the future release list as part of GFA2 support.
