### ISSUE TITLE
assemble large genome

### ISSUE THREAD

**Issue by jordur** [marbl/canu#553]
Hi all!
I was trying to assembly a large genome (genome size = 1.5g) on a Linux SLURM grid engine 
(attached you will find the canu.07.out file) with Canu v1.4 (+126 commits) r8121 35a6573af22a9388f357fc392960fe92d95b1665
According to the out files on correction/2-correction directory I am suffering a problem of mem-per-cpu resources as I read on #515.

```
Running job 15 based on SLURM_ARRAY_TASK_ID=15 and offset=0.
slurmstepd: error: Job 193341 exceeded memory limit (17614484 > 5242880), being killed
slurmstepd: error: *** JOB 193341 CANCELLED 

```
I tried to fix it using corMemory=10 option on the command line. However it does not seem to work. 
I have been looking at canu -options, but I am not sure which parameter should I tweak in order to fix the problem. thus, the command line I used was:

```
canu -p Canu_assembly_${sample}_${uniqueBC} -d Canu_assembly_${sample}_${uniqueBC} corMinCoverage=0 correctedErrorRate=0.105 corMemory=10 genomeSize=$genome -nanopore-raw $tmpcanu/${uniqueBC}.fastq.gz

```
[canu.out.txt](https://github.com/marbl/canu/files/1152204/canu.out.txt)

Could you help me with that issue?
Thank you in advance

**Comment by brianwalenz** [comment]
That's the correct parameter.  The error message is indicating the job tried to allocate 16.79 gb (17614484 kb) memory.  Memory usage is (mostly) determined by the maximum read length in the inpuot - issue 515 is saying corMemory=35 will suffice for 2mbp reads; half that will work for 1mbp reads, etc.  Try corMemory=20.

**Comment by jordur** [comment]
It works! Thank you very much for your help!
