### ISSUE TITLE
Really long run time (180 hr)

### ISSUE THREAD

**Issue by bruce-boles** [marbl/canu#555]
Hello, 

I've been trying to run the assembly of some lambda DNA that I sequenced on the oxford nanopore.  I believe I started the canu program on the 12th of July and it is still going today the 19th of July. I would not be concerned about this, but I ran your E.coli sequence on my laptop (MacOS) with no problems. The E.coli genome is significantly longer then the lambda genome, so I would assume my lambda genome would take a much shorter time to run.

The run seems to be stuck on a step that looks like this, it has been here for approximately 47 hours:

```Starting 'bat' concurrent execution on Wed Jul 12 11:22:08 2017 with 654.511 GB free disk space (1 processes; 2 concurrently)```

    cd unitigging/4-unitigger
    ./unitigger.sh 1 > ./unitigger.000001.out 2>&1

I'm running this program on Window, but in a Linux terminal. I'm also pretty sure the computer I running it on has 16 GB of RAM.

Sorry if I did not provide any information or called something the wrong name. Just let me know what you need and I'll try to get it to you. I'm pretty new to the field of bioinformatics.

Sincerely,

Bruce Boles

**Comment by brianwalenz** [comment]
Interesting.  Yup, it's stuck.  You might as well kill it.

Grab the latest unreleased code from github (see http://canu.readthedocs.io/en/latest/#install), rename 4-unitigger to 4-unitigger-bad, and rerun the same canu command to retry this step.  If it doesn't complete in a few moments post `unitigger.err` from that directory.  The list of files in the same directory might be helpful too.

**Comment by colindaven** [comment]
Try cutting the amount of input reads way down. Our ONT data for lambda was stupidly high coverage (>2000x or more). Try just using a small percentage (10%?) of the FASTQ you get out of albacore, since more isn't really going to help.

**Comment by brianwalenz** [comment]
Hi, Bruce-  I'm cleaning out issues for the next release.  Any update?

**Comment by bruce-boles** [comment]
We quit the run and updated the software. Worked like a charm. Thank you for the help.
