### ISSUE TITLE
corrected reads excellent for remapping and snp calling

### ISSUE THREAD

**Issue by colindaven** [marbl/canu#556]
Hi,

I just wanted to provide some positive feedback.

Recently have been asked to call SNPs on PacBio data. This is feasible with bbmap callvariants.sh but  results are inherently noisy as would be expected.

Canu comes to the rescue by generating a correctedReads.fastq. This can be remapped to a known genome and used to call high quality SNPs. 

cheers,
Colin

**Comment by skoren** [comment]
Thanks for the positive feedback. We did originally envision the corrected reads as a usable intermediate product so glad they were useful for you.

One caveat to note with corrected reads, they may not preserve haplotypes so you won't know if your SNPs co-occur in a molecule while you do know this from the raw reads. We've seen that the corrected reads do preserve phase to some extent but they are not perfect.
