### ISSUE TITLE
correctedReads.fasta.gz empty

### ISSUE THREAD

**Issue by janvanoeveren** [marbl/canu#557]
Hi,
I'm running canu-1.5 on a grid:
./canu-1.5/Linux-amd64/bin/canu -correct genomeSize=>10g corErrorRate=0.02 batThreads=64 batMemory=250 maxThreads=128 maxMemory=1024 gridEngineThreadsOption="-pe smp THREADS"
gridOptions="-r y -V -p -500" gridEngineMemoryOption="-l mem_free=MEMORY" -pacbio-raw

and finally got a correctedReads.fast.gz after some hick-ups, but it's completely empty - without any clear errors

There were some difficulties in the bucketize step - reporting a.o. (ovlStore/logs/1-bucketize.*.out):

> "Bucketizing ../1-overlapper/results/000975.ovb
> ERROR:  Failed to open ./create0975/sliceSizes: Input/output error
> Failure.
> Running job 975 based on SGE_TASK_ID=975 and offset=0.
> Removing incomplete bucket create0975
> Max processes per user limited to 1548965, no increase possible.
> 
> Max open files limited to 4096, no increase possible.
> 
> maxError fraction: 1.000 percent: 100.000 encoded: 4095
> Bucketizing ../1-overlapper/results/000975.ovb
> Success."

The 2-sorting step showed output like this (ovlStore/logs/2-sort.*.out):

> "Found 1014571 overlaps from './bucket0002/sliceSizes'.
> Overlaps need 0.03 GB memory, allowed to use up to (via -M) 19 GB.
> Loading 1014571 overlaps from './bucket0002/slice1255'.
> Sorting.
> Writing output.
> Writing 1014571 overlaps.
> Created ovStore segment './1255' with 0 overlaps for reads from 4294967295 to 0.
> Success."

and the 3-index.err also seemed OK (ovlStore/logs/3-index.err):

> "  Now finished with fragments 1 to 38035021 -- 837981564471 overlaps.
> Processing './4063.index'
>   Now finished with fragments 1 to 38046588 -- 837984439455 overlaps.
> Processing './4064.index'
>   Now finished with fragments 1 to 38047697 -- 837984678496 overlaps.
> Created ovStore '.' with 0 overlaps for reads from 4294967295 to 0.
> 
> Removing intermediate files.
> Finished.
> Success."

Could you tell me what could be wrong or where to look for? How to solve it?

many thanks,
Jan

**Comment by skoren** [comment]
Your corErrorRate is set way too low at 2%. This is the alignment error when generating corrected reads and defaults to 30% for pacbio data. I suggest not setting it to use defaults. I think you should be able to reuse the overlaps you already have so try removing the 2-\* folder and asm.correctedReads.fasta.gz and re-running. Also genome size should be a number so 10g not >10g.

**Comment by janvanoeveren** [comment]
thanks Sergey,

but are you sure?
corErrorRate is the corrected error rate right? This is in the tutorial:

> The four algoriothm error rates are used to select which overlaps can be used for correcting reads (corErrorRate); which overlaps can be used for trimming reads (obtErrorRate); which overlaps can be used for assembling reads (utgErrorRate). The last error rate, cnsErrorRate, tells the consensus algorithm to not trust read alignments above that value.
> 
> For convenience, two meta options set the error rates used with uncorrected reads (rawErrorRate) or used with corrected reads. (correctedErrorRate). The default depends on the type or read being assembled.

> Parameter | PacBio | Nanopore
> -- | -- | --
> rawErrorRate | 0.300 | 0.500
> correctedErrorRate | 0.045 | 0.144

> In practice, only the correctedErrorRate is usually changed.
> 
>         For low coverage datasets (less than 30X), we recommend increasing correctedErrorRate slightly, by 1% or so.
>         For high-coverage datasets (more than 60X), we recommend decreasing correctedErrorRate slightly, by 1% or so.

**Comment by janvanoeveren** [comment]
Oh I think I get it: corErrorRate is actually the rawErrorRate when using correctedReads as input - which I obviously don't have ...

**Comment by brianwalenz** [comment]
Most of the error rates directly control specific algorithms, and their meaning isn't always related to a physical quantity.  The two rates quoted in the table above are easier to interpret; `rawErrorRate` is related to the error rate in raw reads, and 'correctedErrorRate' is related to the expected error rate in corrected reads.  Changing these two values sets all the other error rates (usually) appropriately.

`corErrorRate` tells the read correction algorithm which overlaps to use for correcting reads.  It's a crude filter to get rid of false overlaps that could lead to incorrectly corrected reads.

**Comment by nottwy** [comment]
I also have a problem about this.

In the past, I used correctedErrorRate. But some days ago, I noticed there wasn't a parameter called correctedErrorRate when I invoked: canu -options.

So why is there no explaination about correctedErrorRate in the output of canu -options?

**Comment by skoren** [comment]
correctedErrorRate was added in 1.5 so if you run an older Canu version it will not be there. It is missing in the options description and we should add it. I'll close the issue to make it a request to fix the output of -options.

**Comment by brianwalenz** [comment]
I'm interested how you're using -options and what you expect from it.  It's now listing 288 things (including 43 I just added) which doesn't seem terribly user friendly.
