### ISSUE TITLE
Installation file structure

### ISSUE THREAD

**Issue by outpaddling** [marbl/canu#563]
Hey guys,

Wondering if you would consider changing the installation structure to conform to the filesystem hierarchy standard:

[https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard)

This will make it easier to create packages for systems like Debian packages, FreeBSD ports, Gentoo Portage, etc.

Currently, there are static libraries installed in ${PREFIX}/bin, and the lib directory is also under bin, which many package managers simply don't allow.

I would suggest the following structure:

1. Install programs and scripts in ${PREFIX}/bin
2. Install *.a (and *.so if they ever exist) in ${PREFIX}/lib
3. Install *.pm in ${PREFIX}/lib/site_perl/canu
4. Install *.jar in ${PREFIX}/share/java/classes

Cheers,

     Jason

**Comment by brianwalenz** [comment]
I like the suggestion, I just don't know how easy it will be to do.  I'll try it after the next release comes out.

**Comment by outpaddling** [comment]
I don't think it will be hard, but it will require thorough testing.   We're testing a patched installation here now, and so far no problems.  I only had to patch two files to get our test case working wit the new directory structure,  Here they are with the sed commands I used:

pipelines/canu/OverlapMhap.pm ('s|\\$$bin/mhap-|${JAVAJARDIR}/mhap-|g')
pipelines/canu.pl ('s|RealBin/lib|RealBin/../${SITE_PERL_REL}/canu|g'

SITE_PER_REL = lib/perl5/site_perl
JAVAJARDIR = ${PREFIX}/share/java/classes

I then moved things around in DESTDIR after the build as a quick and dirty test:

bin/lib/canu -> ${SITE_PERL_REL}
bin/*.a -> lib
bin/*.jar -> ${JAVAJARDIR:S,^${PREFIX}/,,}

Of course we'll want to change the target directories in the Makefile rather than move things after the fact.

**Comment by brianwalenz** [comment]
I changed the Makefile to install into the proper hierarchy, but didn't the sed replacements.  Everything is based relative to where the canu binary is located.  There's enough stuff in the bin directory that this probably shouldn't be installed in a common location.

I'm not planning on doing anything else here, so I'm closing the issue.

**Comment by outpaddling** [comment]
This looks good, thanks.

**Comment by outpaddling** [comment]
BTW, this is peanuts compared to a lot of other packages that install in a standard location.  Many of them install hundreds of files into $PREFIX/bin.  Resolving collisions between packages is trivial compared to the cumulative effort saved by potentially thousands of people using a package manager.
Also, I meant to suggest lib/perl5/site_perl, not lib/site_perl, in my original request.  This is better organization for systems with multiple perl versions installed.  Not a big deal, though.
