### ISSUE TITLE
canu failed with 'Failed to submit batch jobs' in SGE

### ISSUE THREAD

**Issue by liuqianhn** [marbl/canu#564]
Hi, I am new to use canu on SGE. When I used canu to run a test, I obtained the following error. May I know more details what is wrong here or how to fix it? Thanks.

-- Finished stage 'cor-gatekeeper', reset canuIteration.
-- Finished stage 'merylConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
--
================================================================================
Please panic.  canu failed, and it shouldn't have.

Stack trace:

 at ~/canu/canu/Linux-amd64/bin/lib/canu/Execution.pm line 1475.
        canu::Execution::caFailure("Failed to submit batch jobs", undef) called at ~/canu/canu/Linux-amd64/bin/lib/canu/Execution.pm line 1094
        canu::Execution::submitOrRunParallelJob("lambda", "meryl", "correction/0-mercounts", "meryl", 1) called at ~/canu/canu/Linux-amd64/bin/lib/canu/Meryl.pm line 405
        canu::Meryl::merylCheck("lambda", "cor") called at ~/canu/canu/Linux-amd64/bin/canu line 513

I also had some warnings at the beginning:
-- WARNING:
-- WARNING:  Queue 'gpu' has start mode set to 'posix_behavior' and shell set to '/bin/csh'.
-- WARNING:  Queue 'all.q' has start mode set to 'posix_behavior' and shell set to '/bin/csh'.
-- WARNING:  Queue 'bigmem' has start mode set to 'posix_behavior' and shell set to '/bin/csh'.
-- WARNING:
-- WARNING:  Some queues in your configuration will fail to start jobs correctly.
-- WARNING:  Jobs will be submitted with option:
-- WARNING:    gridOptions=-S /bin/sh
-- WARNING:
-- WARNING:  If jobs fail to start, modify the above option to use a valid shell
-- WARNING:  and supply it directly to canu.
-- WARNING:

The version of canu is Canu v1.4 (+112 commits) r8107 d43006830429f16fcb194885140f894b5ad43520 on centos 6. By the way, in my SGE, one cannot submit a job from a computing node but only from the head node. Thank you very much for your help or clarification.

**Comment by skoren** [comment]
Canu requires submitting from compute nodes to be enabled so you won't be able to use the default grid run in your environment. You can either request a large node and run Canu locally on it with useGrid=false or run with useGrid=remote which will stop at any submission step.  You'll have to then manually submit the job, wait for completion, and rerun the original Canu command.

**Comment by liuqianhn** [comment]
Hi skoren, Thank you very much for your suggestions.

**Comment by skoren** [comment]
Closing, since this is an issue with grid environment not matching Canu requirements. I'd also suggest updating to the latest Canu release, yours is relatively out of date.

**Comment by liuqianhn** [comment]
Hi skoren, thanks for your suggestion. My canu was downloaded five months agao. I am glad to install the new version of canu.

**Comment by skoren** [comment]
Closing since this is an issue with the grid environment which isn't supported by Canu. I've updated the docs to clarify this requirement. If you have errors with your run, open a new issue.
