### ISSUE TITLE
canu iteration count too high, stopping pipeline

### ISSUE THREAD

**Issue by ljcohen** [marbl/canu#566]
I have been trying to run `Canu release v1.5` to assemble my data on 2 different systems: first, an hpc grid with Torque resource management and then, on an Ubuntu 16.04 VM instance with 44 CPU and 120 GB mem. This is the command:

```
canu -p F_olivaceus -d F_olivaceus_onp_porecamp_2 \
genomeSize=1.1g \
minReadLength=100 minOverlapLength=50 \
-nanopore-raw porecamp_killifish2.fastq
```
I get the same error message on both systems, although at different points in the pipeline. This is the hpc grid:

```
-- BEGIN CORRECTION
--
--
-- meryl failed.
--
================================================================================
Don't panic, but a mostly harmless error occurred and Canu stopped.

Canu release v1.5 failed with:
  canu iteration count too high, stopping pipeline (most likely a problem in the grid-based computes)
```
This is the VM:
```
--   job 1-overlapper/results/000022.ovb FAILED.
--   job 1-overlapper/results/000023.ovb FAILED.
--   job 1-overlapper/results/000024.ovb FAILED.
--   job 1-overlapper/results/000025.ovb FAILED.
--   job 1-overlapper/results/000026.ovb FAILED.
--   job 1-overlapper/results/000027.ovb FAILED.
--   job 1-overlapper/results/000028.ovb FAILED.
--   job 1-overlapper/results/000029.ovb FAILED.
--   job 1-overlapper/results/000030.ovb FAILED.
--   job 1-overlapper/results/000031.ovb FAILED.
--   job 1-overlapper/results/000032.ovb FAILED.
--   job 1-overlapper/results/000033.ovb FAILED.
--   job 1-overlapper/results/000034.ovb FAILED.
--   job 1-overlapper/results/000035.ovb FAILED.
--   job 1-overlapper/results/000036.ovb FAILED.
--   job 1-overlapper/results/000037.ovb FAILED.
--   job 1-overlapper/results/000038.ovb FAILED.
--   job 1-overlapper/results/000039.ovb FAILED.
--   job 1-overlapper/results/000040.ovb FAILED.
--
================================================================================
Don't panic, but a mostly harmless error occurred and Canu stopped.

Canu release v1.5 failed with:
  canu iteration count too high, stopping pipeline (most likely a problem in the grid-based computes)
```
When I got this error message the first time, I thought perhaps that I would try a VM. But then I got it again. So, it does not seem like a grid-based problem. 

The data are relatively low coverage, ~5x for the 1.1Gb genome. Perhaps it is because of the data, or another issue?

Can you please tell me if there is anything I can do to fix this problem?

Thank you.

**Comment by brianwalenz** [comment]
It's probably not the data.  Can you grab one of the test data sets from http://canu.readthedocs.io/en/latest/quick-start.html#quickstart and try running on both systems?

The hpc could be missing (system/compiler) libraries.  Look in */0-mercounts for 'err' or 'out' files with a more specific error.

The VM is probably failing to run java.  Look in correction/1-overlapper/ for similar.

Your 5x data, however, is too low to do any useful assembly with.  You'll just assemble repeats.  The minimum for assembly is around 20x.

**Comment by ljcohen** [comment]
ah, on hpc it looks like the job timed out...

```
Segment 20 finished.
 Writing output:            176.93 Mmers -- 10.23 Mmers/second
Segment 25 finished.
 Writing output:            176.69 Mmers -- 10.32 Mmers/second
Segment 8 finished.
Merge results.
=>> PBS: job killed: walltime 61 exceeded limit 60
Unknown option: 1
Unknown option: 1
Usage: /var/spool/torque/mom_priv/epilogue [-hkbv]
```

How does one adjust the time settings for the jobs submitted? I'm having a hard time deciphering the 'Grid Engine Configuration' and 'Grid Options' sections of the Parameter Reference.

Thank you.

**Comment by skoren** [comment]
The time depends on your grid engine, on PBS it's probably something like ```-l walltime=96:00:00``` but you should check your grid configuration. 

For passing it through Canu you want the first option in the Grid Options documentation: http://canu.readthedocs.io/en/latest/parameter-reference.html?highlight=gridOptions#grid-options, namely ```gridOptions="-l walltime=96:00:00"``` which will make all Canu jobs submit commands adding the wall clock options.

**Comment by skoren** [comment]
Closing, inactivity. Hopefully the wall time option got you past the error on the HPC. If you encounter other errors with you run, please open a new issue.
