### ISSUE TITLE
Possible new issue with not asking for enough memory...

### ISSUE THREAD

**Issue by JohnUrban** [marbl/canu#57]
Hi,

I was not sure if it made more sense to add this to issue #5 (https://github.com/marbl/canu/issues/5) or give it its own, but since its a new issue I gave it its own. I have been running assemblies after corrections were made for issue #50 (https://github.com/marbl/canu/issues/50). During the correction phase, it seems Canu is making multiple iterations and failing due to exceeding memory (error messages below). For now, what variable should I use to ask for more memory than the default?

-- In Canu.out:
3 read correction jobs failed:
  job ./asm/correction/2-correction/correction_outputs/0128.fasta FAILED.
  job ./asm/correction/2-correction/correction_outputs/0134.fasta FAILED.
  job ./asm/correction/2-correction/correction_outputs/0135.fasta FAILED.

Don't panic, but a mostly harmless error occurred and canu failed.
canu failed with 'failed to generate corrected reads.  Made 2 attempts, jobs still failed'.

-- In ./asm/correction/2-correction/correctReads.12107224_134.out (as example):

/var/spool/slurmd/job12107226/slurm_script: line 671: 25929 Done(141)               ( $bin/generateCorrectionLayouts -b $bgn -e $end -rl ./asm/correction/2-correction/asm.readsToCorrect -G ./asm/correction/asm.gkpStore -O ./asm/correction/asm.ovlStore -S ./asm/correction/2-correction/asm.globalScores -C 80 -legacy -F && touch ./asm/correction/2-correction/correction_outputs/$jobid.dump.success )
     25930 Killed                  | $bin/falcon_sense --min_idt 0.7 --min_len 500 --min_ovl_len 500 --min_cov 2 --n_core 4 > ./asm/correction/2-correction/correction_outputs/$jobid.fasta.WORKING 2> ./asm/correction/2-correction/correction_outputs/$jobid.err
Read layout generation failed.
mv: cannot stat `./asm/correction/2-correction/correction_outputs/0134.fasta': No such file or directory
slurmstepd: Exceeded step memory limit at some point.

**Comment by rafalwoycicki** [comment]
Hi John,
"For now, what variable should I use to ask for more memory than the default?"
Quick answer = corMemory.
[cor]Memory/Threads/Concurrency is for Falcon - If I am right.
Hope it will help - I had also an issue (different with not utilizing all threads - solved I hope (as it is still running) with Sergey's help) with Falcon_sense last weekend.

Hope it will help.
Rafal

**Comment by JohnUrban** [comment]
Thanks Rafal - I will give it a try.

**Comment by rafalwoycicki** [comment]
Your welcome John, let me know how it worked out.

**Comment by skoren** [comment]
Hi John,

It should be using the same memory the previous version was so I'm not sure why it's suddenly overflowing. Can you check how much memory it requested/used before being terminated with sachet:

```
sacct -o JobID,UserCPU,SystemCPU,TotalCPU,MaxRSS,CPUTimeRAW,Elapsed -j <jobid>
```

**Comment by JohnUrban** [comment]
Hi Sergey,

It was asking for:
       JobID    UserCPU  SystemCPU   TotalCPU     MaxRSS CPUTimeRAW    Elapsed 
------------ ---------- ---------- ---------- ---------- ---------- ---------- 
12105208_135  11:10.734  04:36.831  15:47.565        16?       2796   00:11:39 
12105208_13+  11:10.734  04:36.831  15:47.565  10420164K 18446744073709550917   00:11:39 

I then set corMemory=15:
It is now asking for:
       JobID    UserCPU  SystemCPU   TotalCPU     MaxRSS CPUTimeRAW    Elapsed 
------------ ---------- ---------- ---------- ---------- ---------- ---------- 
12107326_128  22:08.372  07:00.936  29:09.308        16?       6336   00:26:24 
12107326_12+  22:08.372  07:00.936  29:09.308  14499580K 18446744073709550032   00:26:24 

The jobs with 15g are also failing (just 2 or 3 of 135 or so).
I just looked, and it seems like I should be asking for >=17g.

**Comment by JohnUrban** [comment]
Asking for 18g gave same result (corMemory=18).
Will try asking for a lot more this time. . .

**Comment by skoren** [comment]
I've verified with valgrind the new version doesn't have a memory leak. Can you share one of your layout files so I can see where the memory is being used and if we can reduce it. For one of your failed partitions you can run just the part up to the pipe (e.g.:) 

```
$bin/generateCorrectionLayouts -b $bgn -e $end \
  -rl /data/korens/test/lambda/correction/2-correction/asm.readsToCorrect \
  -G /data/korens/test/lambda/correction/asm.gkpStore \
  -O /data/korens/test/lambda/correction/asm.ovlStore \
  -S /data/korens/test/lambda/correction/2-correction/asm.globalScores \
  -C 80 \
  -legacy \
  -F  > correction_inputs/$jobid.lay \
&& \
  touch /data/korens/test/lambda/correction/2-correction/correction_outputs/$jobid.dump.success
```

**Comment by JohnUrban** [comment]
Ok thanks - I will do that.

For now an update - 30g was also not enough… 

I also keep seeing this type of message in the canu.outs:
Warning: multiple IDs for job cor_g310-default_g310m-default got 2 and should have been 1.

**Comment by skoren** [comment]
The messages are fine it is holding for multiple jobs when the failed ones are re-submitted.

**Comment by JohnUrban** [comment]
Alright - I have now tried even corMemory=60 and it failed with a similar error.

/var/spool/slurmd/job12114523/slurm_script: line 671: 17557 Done(141)               ( $bin/generateCorrectionLayouts -b $bgn -e $end -rl /asm/correction/2-correction/asm.readsToCorrect -G /asm/correction/asm.gkpStore -O /asm/correction/asm.ovlStore -S /asm/correction/2-correction/asm.globalScores -C 80 -legacy -F && touch /asm/correction/2-correction/correction_outputs/$jobid.dump.success )
     17558 Segmentation fault      | $bin/falcon_sense --min_idt 0.7 --min_len 500 --min_ovl_len 500 --min_cov 4 --n_core 4 > /asm/correction/2-correction/correction_outputs/$jobid.fasta.WORKING 2> /asm/correction/2-correction/correction_outputs/$jobid.err
Read layout generation failed.
mv: cannot stat `/asm/correction/2-correction/correction_outputs/0134.fasta': No such file or directory

**Comment by skoren** [comment]
This isn't really a memory issue, I'm pretty sure there is an infinite loop being triggered by some of the longest repetitive reads leading to the crash. No matter how much memory you'd request I think it would crash. There is a 900kb read with several very long reads contained within it (700kb, 500kb) that appears very repetitive at first glance. You could remove these reads (I'm assuming they're 1D reads?) as a workaround until we find the bug in falcon_sense.

**Comment by skoren** [comment]
I committed a test patch. In my testing the job which was going over 30GB before stayed below 8GB. Can you test and see if it fixes all your bad jobs?

**Comment by JohnUrban** [comment]
Downloading and will begin running ASAP. Will be able to let you know what happens tomorrow.

**Comment by JohnUrban** [comment]
Last time, there were 3 correctReads jobs that failed: 128, 134, and 135.

This time 1 failed: 134.

Error message in correctReads.jobid_134.out:
slurmstepd: Job 12121220 exceeded memory limit (11723748 > 11534336), being killed
slurmstepd: *** JOB 12121220 CANCELLED AT 2016-03-02T08:51:33 *** on node115
slurmstepd: Exceeded step memory limit at some point.
slurmstepd: Exceeded job memory limit

I've shared the layout file with you, if you want to look at it.

**Comment by JohnUrban** [comment]
Ok I ran it with asking for more memory (corMemory=30) and it finished… so no need to adjust MAX_KMER_REPEAT.

It originally asked for 11-12g -- that failed.
I gave it 30g -- that worked.
sacct is throwing an error right now though and I cannot tell you how much was actually needed.

**Comment by skoren** [comment]
In my tests it needed 19Gb so that makes sense. Adjusting the repeat might be worth it to bring that down to 10-12G instead.

**Comment by JohnUrban** [comment]
Do you mean make MAX_KMER_REPEAT < 1000?

Either way - bringing down the memory requirement for this single job does make more sense than asking for more memory for the other 148 jobs or so that did fine with 10-12G. So yeah - I could try making MAX_KMER_REPEAT less before compiling... or are you pushing a new commit with it adjusted?

**Comment by skoren** [comment]
I don't have a commit yet, you can try setting it to 500 instead and seeing if that brings the memory down enough.

**Comment by JohnUrban** [comment]
Result: it crashed for this one case even at 500.

**Comment by JohnUrban** [comment]
I ran it with corMemory=30 and it finished.

Some info on thejob:

       JobID    JobName   NTasks        NodeList 
------------ ---------- -------- --------------- 
12124407_134 cor_g310-+                  node242 
12124407_13+      batch        1         node242 


 MaxVMSize  AveVMSize     MaxRSS 
---------- ---------- ---------- 
       16?                   16? 
 25708956K   6304724K  19682596K 


              Start                 End    CPUTime    Elapsed 
------------------- ------------------- ---------- ---------- 
2016-03-03T07:37:58 2016-03-03T08:55:08   05:08:40   01:17:10 
2016-03-03T07:37:58 2016-03-03T08:55:08    INVALID   01:17:10 


   UserCPU  SystemCPU   TotalCPU CPUTimeRAW 
---------- ---------- ---------- ---------- 
  01:33:19  20:27.321   01:53:47      18520 
  01:33:19  20:27.321   01:53:47 18446744073709546986

**Comment by skoren** [comment]
Yes, dropping to 100 also used more than 10-12 GB. For now I think I will leave the code as is (at 1000) and you can request higher memory for the consensus jobs since these reads are relatively uncommon for now. We can fold this issue into #5 and improve the memory usage for these very long reads.

**Comment by JohnUrban** [comment]
Agreed - this discussion can move to #5
