### ISSUE TITLE
run crash due to outage

### ISSUE THREAD

**Issue by pwkooij** [marbl/canu#570]
Due to a power outage, my run crash deep in my analysis during the trimming (10 days into the run). I know I can restart using the correction results, skipping that part. But is there a way to continue the run from where it crashed? (just being hopeful here...)

Command used:
`canu -p mydata -d canu-assembly maxThreads 8 genomeSize=40m corOutCoverage=200 ovlErrorRate=0.15 obtErrorRate=0.15 -nanopore-raw *.fastq
`
Canu version:
`Canu snapshot v1.5 +41 changes (r8241 90e69a6353c7a7fe7e9d710d9bd6447fc32bf7d9)`

System:
Ubuntu 16.04, locally

**Comment by skoren** [comment]
Canu will automatically resume where it left off so re-running the same command should automatically start after the last good output.

**Comment by pwkooij** [comment]
That sounds like a lifesaver, will try it right away!

Thanks

**Comment by pwkooij** [comment]
Looks like that's working, fantastic! Thanks!

**Comment by pwkooij** [comment]
@skoren is it possible to restart an analysis on a different computer? I'm trying to put it on a faster/better one, but it doesn't seem to be able to load the files. Also I noticed that the log files contain the directories of the first computer + have the computer name in the file name

**Comment by brianwalenz** [comment]
Possible, but you might end up losing the last step worked on.  Can you post an example?  Which canu version?  Recent (most of this year) versions don't retain the full path.

**Comment by pwkooij** [comment]
when I try to run it on the new pc I get the following output

```-- BEGIN TRIMMING
--
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'obtovl' concurrent execution on Mon Aug 14 14:22:52 2017 with 893.543 GB free disk space (7 processes; 3 concurrently)

    cd trimming/1-overlapper
    ./overlap.sh 33 > ./overlap.000033.out 2>&1
    ./overlap.sh 34 > ./overlap.000034.out 2>&1
    ./overlap.sh 35 > ./overlap.000035.out 2>&1
    ./overlap.sh 36 > ./overlap.000036.out 2>&1
    ./overlap.sh 37 > ./overlap.000037.out 2>&1
    ./overlap.sh 38 > ./overlap.000038.out 2>&1
    ./overlap.sh 39 > ./overlap.000039.out 2>&1

-- Finished on Mon Aug 14 14:22:52 2017 (lickety-split) with 893.543 GB free disk space
----------------------------------------
--
-- Overlap jobs failed, retry.
--   job trimming/1-overlapper/001/000033.ovb FAILED.
--   job trimming/1-overlapper/001/000034.ovb FAILED.
--   job trimming/1-overlapper/001/000035.ovb FAILED.
--   job trimming/1-overlapper/001/000036.ovb FAILED.
--   job trimming/1-overlapper/001/000037.ovb FAILED.
--   job trimming/1-overlapper/001/000038.ovb FAILED.
--   job trimming/1-overlapper/001/000039.ovb FAILED.
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'obtovl' concurrent execution on Mon Aug 14 14:22:52 2017 with 893.543 GB free disk space (7 processes; 3 concurrently)

    cd trimming/1-overlapper
    ./overlap.sh 33 > ./overlap.000033.out 2>&1
    ./overlap.sh 34 > ./overlap.000034.out 2>&1
    ./overlap.sh 35 > ./overlap.000035.out 2>&1
    ./overlap.sh 36 > ./overlap.000036.out 2>&1
    ./overlap.sh 37 > ./overlap.000037.out 2>&1
    ./overlap.sh 38 > ./overlap.000038.out 2>&1
    ./overlap.sh 39 > ./overlap.000039.out 2>&1

-- Finished on Mon Aug 14 14:22:52 2017 (lickety-split) with 893.543 GB free disk space
----------------------------------------
--
-- Overlap jobs failed, tried 2 times, giving up.
--   job trimming/1-overlapper/001/000033.ovb FAILED.
--   job trimming/1-overlapper/001/000034.ovb FAILED.
--   job trimming/1-overlapper/001/000035.ovb FAILED.
--   job trimming/1-overlapper/001/000036.ovb FAILED.
--   job trimming/1-overlapper/001/000037.ovb FAILED.
--   job trimming/1-overlapper/001/000038.ovb FAILED.
--   job trimming/1-overlapper/001/000039.ovb FAILED.
--

ABORT:
ABORT: Canu snapshot v1.5 +203 changes (r8403 8f83b2f397156eecc66658123257c636042c72d2)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```

One of the top log-files in the canu-logs folder (gatekeeperCreate) shows this at the top of the file:

```Canu v1.5 (+41 commits) r8241 90e69a6353c7a7fe7e9d710d9bd6447fc32bf7d9.```

**Comment by brianwalenz** [comment]
The easiest and safest solution is to remove (or just rename) the trimming/1-overlapper directory and restart.

It looks like the change in machine size also changed the layout of these jobs.  One wanted to run 32 jobs, the other wanted 39 jobs.  I'm concerned that half the jobs were run one way and the other half the other way.  This would result in either duplicate overlaps (bad) or missing overlaps (very bad).

**Comment by pwkooij** [comment]
renamed is as 1-overlapper-backup and ran the command again. Looks like it is working now, thanks!
