### ISSUE TITLE
Use previously correct sequences for new trimming and assembly processes

### ISSUE THREAD

**Issue by uceleste** [marbl/canu#573]
Dear All,

I did a first assembly test with Canu doing all of the three steps and using a command line like this:

```
$ canu -p Name -d Name genomeSize=Size corOutCoverage=200 -pacbio-raw Dataset.fa
```

Now I would like to make a further test by entering the specific parameters for heterozygosity and using the same corrected dataset obtained from the first assembly. Can I only perform the trimming and assembly processes using the corrected dataset with a command like this?

```
$ canu -trim-assembly -p Name -d Name genomeSize=Size corOutCoverage=200 ovlErrorRate=0.15 obtErrorRate=0.15 -pacbio-corrected Name.correctedReads.fasta.gz
```

Is the corOutCoverage=200 parameter specific to the correction phase only? Can it be deleted from this command line?

Thank you ever so much!

**Comment by skoren** [comment]
Yes, ```corOutCoverage``` is specific to assembly and can be deleted. You also don't need to specify the ```-trim-assembly``` option, providing pacbio-corrected reads automatically selects that option.

The error rate you are using is relatively high (15%) so this will likely be much slower than the default assembly which uses 5% (or 1/3) the error rate.
