### ISSUE TITLE
The disk resource when using Canu

### ISSUE THREAD

**Issue by RyanBio** [marbl/canu#575]
Hi, developers:
I want to estimate how much the disk resource needed for assembling a nearly 6Gb genome with 60X sequencing data. As lack of experience for such huge genome, could you like to provide some infos about of peak disk and details of the processes when assembling such large genome. 
BTW, the Canu version is release v1.5.

Thanks,
Ryan

**Comment by brianwalenz** [comment]
Disk usage is heavily dependent on repeat content of the genome.  An assembly of human with 60x of PacBio reads uses about 1 TB disk.  Human is quite well behaved; other smaller genomes have used 30 TB.

Peak disk usage will be when correcting the reads.  Nearly all this space is used for read-to-read overlaps.

There are definitely ways to reduce disk usage, but they all depend on the quality of reads (length) and genome, so not a whole lot I can suggest right now.

**Comment by RyanBio** [comment]
Yes, repeat content is the key. A 2Gb repetitive genome i assembled used more than 20 TB disk.
I will monitor the free disk.

Thanks,
Ryan
