### ISSUE TITLE
 a mostly harmless error occurred and Canu stopped

### ISSUE THREAD

**Issue by Chenghong412** [marbl/canu#576]
Hi, developers:
      Error (as follows) occurs during the assembly process.
###
ABORT:
ABORT: Canu 1.5
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
###
    I have tried restarting twice, but the same error occurs. The code is 
###
canu -assemble -p xx -d xx_assemble1 genomeSize=1g correctedErrorRate=0.039 -pacbio-corrected /xx/duck.trimmedReads.fasta.gz
###
     Thanks.

**Comment by skoren** [comment]
There should be more output than this before the error. Do you have the full output of the command when you run it not just the end? That will give more information on the error.

**Comment by Chenghong412** [comment]
I re-checked the log file and found that "FAILED" indeed appear earlier than the before-mentioned. The detailed describe is:
###
Configure OEA for 2gb memory with batches of at most 25000 reads and (unlimited) bases.
  FAILED - configured 3471805 jobs, but 3471805 jobs process 1024 reads or less each.Increasing    memory from 2 GB to 2.5 GB.
Configure OEA for 2.5gb memory with batches of at most 25000 reads and (unlimited) bases.
Configured 535 jobs.
###

**Comment by brianwalenz** [comment]
We're looking for the lines just before the ABORT lines.  There might not be any error message shown, just a command being run.  It is this command that is failing.  If you have the canu screen output, paste in the last 100 lines or so.

**Comment by Chenghong412** [comment]
-- Using slow alignment for consensus (iteration '1').
-- Configured 153 contig and 113 unitig consensus jobs.
--
-- Consensus jobs failed, retry.
--   job ctgcns/0001.cns FAILED.
--   job ctgcns/0002.cns FAILED.
--   job ctgcns/0003.cns FAILED.
……
--   job utgcns/0111.cns FAILED.
--   job utgcns/0112.cns FAILED.
--   job utgcns/0113.cns FAILED.
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'cns' concurrent execution on Tue Aug  1 18:53:24 2017 with 564001.391 GB free disk space (266 proc
esses; 18 concurrently)

    cd unitigging/5-consensus
    ./consensus.sh 1 > ./consensus.000001.out 2>&1
    ./consensus.sh 2 > ./consensus.000002.out 2>&1
    ./consensus.sh 3 > ./consensus.000003.out 2>&1
    ./consensus.sh 4 > ./consensus.000004.out 2>&1
     ……
    ./consensus.sh 264 > ./consensus.000264.out 2>&1
    ./consensus.sh 265 > ./consensus.000265.out 2>&1
    ./consensus.sh 266 > ./consensus.000266.out 2>&1

-- Finished on Tue Aug  1 18:53:45 2017 (21 seconds) with 563960.34 GB free disk space
----------------------------------------
-- Using slow alignment for consensus (iteration '2').
-- Configured 153 contig and 113 unitig consensus jobs.
--
-- Consensus jobs failed, tried 2 times, giving up.
--   job ctgcns/0001.cns FAILED.
--   job ctgcns/0002.cns FAILED.
--   job ctgcns/0003.cns FAILED.
……
--   job utgcns/0111.cns FAILED.
--   job utgcns/0112.cns FAILED.
--   job utgcns/0113.cns FAILED.
--

ABORT:
ABORT: Canu 1.5
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:

**Comment by brianwalenz** [comment]
Perfect!  In unitigging/5-consensus, look in the various *.out and *.err files for errors like
```
/usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by .../Linux-amd64/bin/utgcns)
```
If so, you're missing the required runtime libraries from the GCC compiler suite.  Issues #95 and #467 have some more details.  Depending on how you installed v1.5 initially, you can try compiling it yourself or installing the binary release.

**Comment by Chenghong412** [comment]
I have looked the various *.out and *err files. As you said, the error  is " /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found". Thanks a lot !
