### ISSUE TITLE
Canu cannot detect grid for me but can for others

### ISSUE THREAD

**Issue by jwasmuth** [marbl/canu#577]
Dear developers,

I searched the closed issues but didn't find anything that helped. I am running canu-1.5 and am trying out the quick start command for the E. coli PacBio data. When I run the command the stdout incudes:

```-- Detected PBS/Torque '5.1.2' with 'pbsnodes' binary in /usr/local/bin/pbsnodes.
-- Detecting PBS/Torque resources.
-- 
-- Found   1 host  with  48 cores and 1259 GB memory under PBS/Torque control.
```

However, when I look at 
```ecoli-auto/canu-scripts/canu.01.out```
I'm told that
```-- No grid engine detected, grid disabled.```

The job then runs without scheduling the process as neatly as it could. What is bizarre is that for two other users on the same system, using the same installation of canu-1.5 the scheduling works fine.

We've looked at my path and other environmental factors but cannot work out what is going on. I am grateful for any suggestions.

Thanks
James

**Comment by skoren** [comment]
This would imply that the job doesn't have access to qsub/etc commands when running within the grid environment vs your local environment. You could test this by writing a script like:
```
which qsub
which pbsnodes
pbsnodes
```

and running it locally vs submitted to grid. You could also try adding the -V to your grid options (```gridOptions="-V"```) when running Canu. I am less familiar with PBS/Torque but I believe that will force the running job to inherit the environment. It is possible other users have the -V passed through by default while you don't/

**Comment by jwasmuth** [comment]
Further snooping has shown that `/usr/local/bin` wasn't in my $PATH when I submitted. It does seem to be in that of other users. Odd! Perhaps, I did something to it.
I have a temporary fix `ln -s /usr/local/bin/pbsnodes ~/bin/; ln -s /usr/local/bin/qsub ~/bin/` until the sysadmin fixes it properly. Currently, canu is working as expected. 
Thanks for your suggestions.

**Comment by jwasmuth** [comment]
Just to add before closing it again, in case anyone else has a similar problem, the `gridOptions="-V"` suggested by @skoren worked too. It's cleaner than my original solution.
