### ISSUE TITLE
Specify wall-time via CANU?

### ISSUE THREAD

**Issue by cement-head** [marbl/canu#579]
Hi,

  Trying to get CANU to do a big job and it's getting stuck submitting sub jobs through the GRID engine.  The problem that when CANU submits these sub-jobs, the default of ONE hour is given to each subjob which is the default on the GRID.  

Question:  Is there a way to specific the wall time with one of the GRID options commands?

Thanks.

**Comment by skoren** [comment]
See the documentation here: http://canu.readthedocs.io/en/latest/tutorial.html#execution

You can specify parameters to pass through to every job using ```gridOptions```.
