### ISSUE TITLE
Bucketizer failure

### ISSUE THREAD

**Issue by gwaldbieser** [marbl/canu#580]
I am running a vertebrate assembly for a 900Mb genome from an interspecific hybrid individual. The parental species are about 5% divergent at the DNA sequence level. The input reads are PacBio – total 5.4M reads >= 1000bp, total bases = 55 Gb, thus ~ 60X genome coverage. This is run on a Linux workstation (CentOS 7.3.1611) with 512 GB RAM and 64 cpu, using canu_1.5_r8269.

I began the run using suggested settings for a hybrid assembly. 
```
$/home/software/canu_1.5_r8269/Linux-amd64/bin/canu \
 -correct -p Hyb -d Hyb \
 corOutCoverage=200 corMinCoverage=0 corMhapSensitivity=high \
 correctedErrorRate=0.040 \
 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" \
 obtOverlapper=mhap obtReAlign=raw \
 utgOverlapper=mhap utgReAlign=raw  \
 genomeSize=900m \
 -pacbio-raw /mnt/qnap/HybridPacBio/PBraw.fasta 1>run1.log 2>&1
```

It crashed a few times due to space limitations (filling up a 4 TB HDD). After I realized it would require much more space then I moved most of the correction folder to a NAS (24 GB available). I moved all the files in 1-overlapper/, 1-overlapper/results/*.ovb and *.counts files and all the 1-overlapper/blocks/*.dat files. I was not able to move the symbolic links to the .dat files within the 1-overlapper/queries directory. In fact it won’t let me make the symbolic links manually – does this have to do with NTFS formatting of the NAS?  I tried running from that point without the symbolic links but the ovlStore build failed.

```
-- Starting 'ovB' concurrent execution on Fri Jul 28 23:18:59 2017 with 25502.724 GB free disk space (377 processes; 64 concurrently)

    cd correction/Hyb.ovlStore.BUILDING
    ./scripts/1-bucketize.sh 1 > ./logs/1-bucketize.000001.out 2>&1
    ./scripts/1-bucketize.sh 2 > ./logs/1-bucketize.000002.out 2>&1
    ./scripts/1-bucketize.sh 3 > ./logs/1-bucketize.000003.out 2>&1
(snip)
    ./scripts/1-bucketize.sh 375 > ./logs/1-bucketize.000375.out 2>&1
    ./scripts/1-bucketize.sh 376 > ./logs/1-bucketize.000376.out 2>&1
    ./scripts/1-bucketize.sh 377 > ./logs/1-bucketize.000377.out 2>&1

-- Finished on Sat Jul 29 08:06:47 2017 (31668 seconds) with 23096.21 GB free disk space
----------------------------------------
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'ovB' concurrent execution on Sat Jul 29 08:07:07 2017 with 23096.213 GB free disk space (261 processes; 64 concurrently)

    cd correction/Hyb.ovlStore.BUILDING
    ./scripts/1-bucketize.sh 1 > ./logs/1-bucketize.000001.out 2>&1
    ./scripts/1-bucketize.sh 2 > ./logs/1-bucketize.000002.out 2>&1
    ./scripts/1-bucketize.sh 3 > ./logs/1-bucketize.000003.out 2>&1
(snip)
    ./scripts/1-bucketize.sh 360 > ./logs/1-bucketize.000360.out 2>&1
    ./scripts/1-bucketize.sh 361 > ./logs/1-bucketize.000361.out 2>&1
    ./scripts/1-bucketize.sh 362 > ./logs/1-bucketize.000362.out 2>&1

-- Finished on Sat Jul 29 15:40:51 2017 (27224 seconds) with 23074.277 GB free disk space
----------------------------------------
--
-- 258 overlap store bucketizer jobs failed:
--   job correction/Hyb.ovlStore.BUILDING/bucket0001 FAILED.
--   job correction/Hyb.ovlStore.BUILDING/bucket0002 FAILED.
--   job correction/Hyb.ovlStore.BUILDING/bucket0003 FAILED.
(snip)
--   job correction/Hyb.ovlStore.BUILDING/bucket0359 FAILED.
--   job correction/Hyb.ovlStore.BUILDING/bucket0360 FAILED.
--   job correction/Hyb.ovlStore.BUILDING/bucket0361 FAILED.
--

ABORT:
ABORT: Canu snapshot v1.5 +69 changes (r8269 542445b8162beeb24b4ee39eefd86caccab6f48f)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   canu iteration count too high, stopping pipeline (most likely a problem in the grid-based computes).
ABORT: 
```

Are the symbolic links in the /queries directory that point to the .dat files still required at this stage? I’d rather not have to make hard links to the .dat files if that’s not necessary. BTW, I cannot form the links even as root, with root ownership of the targets.

**Comment by brianwalenz** [comment]
Nope, the symlinks aren't needed.  The blocks/ and queries/ aren't used any more, only results/ are needed.

Since you're not using a grid, there won't be any advantage to using the 'parallel' overlap store build method.  Use ovsMethod=sequential to use the older single-process method used in Celera Assembler.

Before you remove the *.ovlStore.BUILDING directory, poke around in the out/err files in there (probably in logs/, but don't quote me).  I'm curious why every job failed.

**Comment by gwaldbieser** [comment]
#############
**/correction/Hyb.ovlStore.BUILDING/logs $ cat 1-bucketize.000001.out**
Running job 1 based on command line options.
Removing incomplete bucket create0001
Max processes per user limited to 2062871, no increase possible.

Changed max open files from 1024 to 4096 (max 4096).

maxError fraction: 1.000 percent: 100.000 encoded: 4095
Bucketizing ../1-overlapper/results/000001.ovb
ERROR:  Failed to open output file './create0001/slice0198': Too many open files
Failure.

**/correction/Hyb.ovlStore.BUILDING/logs $ cat 1-bucketize.000359.out**
Running job 359 based on command line options.
Removing incomplete bucket create0359
Max processes per user limited to 2062871, no increase possible.

Changed max open files from 1024 to 4096 (max 4096).

maxError fraction: 1.000 percent: 100.000 encoded: 4095
Bucketizing ../1-overlapper/results/000359.ovb
ERROR:  Failed to open output file './create0359/slice1950': Too many open files
Failure.

**/correction/Hyb.ovlStore.BUILDING/logs $ cat 1-bucketize.000360.out**
Running job 360 based on command line options.
Removing incomplete bucket create0360
Max processes per user limited to 2062871, no increase possible.

Changed max open files from 1024 to 4096 (max 4096).

maxError fraction: 1.000 percent: 100.000 encoded: 4095
Bucketizing ../1-overlapper/results/000360.ovb
Success.
#############

Overall, the 1-bucketize.*.out files show 120 of 377 were successful. 
Is this the parallel problem?

**Comment by brianwalenz** [comment]
Thanks.

Yup, too many jobs trying to open too many files at the same time.  Though it reported a limit of 4096 jobs, I suspect it hit a global system limit on the number of open files.

The parallel method really isn't appropriate for a single machine (my early tests on this showed it was slower than the sequential method).  I should disable it for non-grid runs.  It also needs a big fast disk behind it.  Early tests with a 5 disk ZFS raid 5 showed the sequential method was still faster.  The sequential version is a bit nicer to disks, just because there is only one thing reading or writing at a time.

Options:

1. You can cut down the 'concurrency' of this stage (ovbConcurrency=8 and ovsConcurrency=8 seem reasonable) and keep plugging away.
2. Start overlap store building from scratch with the sequential method.  I suspect this will be the faster option, but probably not by that much.

**Comment by gwaldbieser** [comment]
I took option 2 and restarted from scratch with "ovsMethod=sequential". It required almost 5 days but it did complete the ovlStore build. I especially like the logging info that provides timing of each step and also shows that 2.5TB of overlap output files and 3 directories were purged. Thanks!

**Comment by brianwalenz** [comment]
Congratulations!  The longest store build I can remember was 3 days, and that was the one (more or less) that prompted development of the parallel method.

Two tricks I've used in the past:

1) leave the assembly in place, but make symlinks to stores on other disks.  This does require some manual effort - the store must be built by hand outside of canu.
2) make symlinks for the 001, 002, etc directories and store the overlapper outputs on a different disk.  This can be done before starting canu, something like `mkdir -p asmdir/trimming/1-overlapper/` then `ln -s /scratch/001 asmdir/trimming/1-overlapper/001`.  Same idea would work for mhap, just a different directory structure that I don't remember off the top of my head.
