### ISSUE TITLE
Overlap jobs failed

### ISSUE THREAD

**Issue by newlbs** [marbl/canu#581]
Hi, I attempted to use canu but have not yet to get the test data working so far.

I used the following command 
```~/package/canu/Linux-amd64/bin/canu -p ecoli -d ecoli-oxford genomeSize=4.8m -nanopore-raw oxford.fasta useGrid=false```

It seems the overlap jobs failed per the error message showing below:
```
......
-- Overlap jobs failed, tried 2 times, giving up.
--   job unitigging/1-overlapper/001/000001.ovb FAILED.
--   job unitigging/1-overlapper/001/000002.ovb FAILED.
--

ABORT:
ABORT: Canu snapshot v1.5 +177 changes (r8377 192c6c3dfee3d17433b3cf7f80598143c52060a6)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
```
I restarted the jobs multiple times but received the same errors.

The canu version I used is 
Canu snapshot v1.5 +177 changes (r8377 192c6c3dfee3d17433b3cf7f80598143c52060a6)

I was using it on a slurm grid but I encountered other problems for using the grid so I am testing without those functions for now.

Please let me know if there is any other information would be helpful to identify the problem. Thank you.

**Comment by skoren** [comment]
There should be more information in the unitigging/1-overlapper/00000[12].out files. Can you either run tail on them and post there results or upload them to the issue?

**Comment by newlbs** [comment]
Hi @skoren Thanks for your prompt reply! I ran tail on both of files and the they showed the same following info:

/gpfs/fs1/home/bli16/package/canu/Linux-amd64/bin/overlapInCore: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /gpfs/fs1/home/bli16/package/canu/Linux-amd64/bin/overlapInCore)

Then I loaded the gcc module on our cluster and it seemed to be working now. I will come back and close this issue if it successfully finishes the assembly. Thank you.

**Comment by newlbs** [comment]
Hi @skoren, the run halted again.
The error showed:

```
....
-- Bogart failed, retry
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'bat' concurrent execution on Wed Aug  2 14:40:51 2017 with 165760.359 GB free disk space (1 processes; 6 concurrently)

    cd unitigging/4-unitigger
    ./unitigger.sh 1 > ./unitigger.000001.out 2>&1

-- Finished on Wed Aug  2 14:40:52 2017 (1 second) with 165760.335 GB free disk space
----------------------------------------
--
-- Bogart failed, tried 2 times, giving up.
--
......
```

I checked in the unitigging/4-unitigger directory. 
The unitigger.000001.out showed:
```
./unitigger.sh: line 75: 26064 Aborted                 $bin/bogart -G ../ecoli.gkpStore -O ../ecoli.ovlStore -o ./ecoli -gs 4800000 -eg 0.144 -eM 0.144 -mo 500 -dg 6 -db 6 -dr 3 -
ca 2100 -cp 200 -threads 4 -M 10 -unassembled 2 0 1.0 0.5 5 > ./unitigger.err 2>&1
./unitigger.sh: line 87: ../ecoli.ctgStore/seqDB.v001.sizes.txt: No such file or directory
```
and the last line of unitigger.err showed:
```
bogart: bogart/AS_BAT_OverlapCache.H:217: BAToverlap* OverlapStorage::get(uint32): Assertion `_osLen < _osMax' failed.
```

I am no sure how to fix this one. If you need more info please let me know. Thanks.

**Comment by skoren** [comment]
There's been a lot of flux in that code recently, try updating to latest commit and seeing if that fixes it.

**Comment by newlbs** [comment]
I updated it and it did finish the assembly successfully! Thank you!
