### ISSUE TITLE
How to apply canu to multiple amplicons

### ISSUE THREAD

**Issue by liaoyunshi** [marbl/canu#583]
Given that canu commonly only deal with longest reads up to 40x coverage, I wonder how canu can be used in long amplicon assembly.

For example, I would like to amplify and sequence (use nanopore) a 16kb genome by 3 overlapping amplicons, which are 5, 6, 7 kb in length, respectively. When I use the default setting of canu to assemble the whole genome, only the 7 kb amplicon can be recovered and assembled, I think this is because the canu would only keep those "longest" reads (i.e. 7 kb reads). I do know I should increase the `corOutCoverage` to greater than the total input coverage, but this would be a huge number and would cost me lots of time to finish the job.

Thus I want to know if you have any other ways to deal with this situation. Thanks.

**Comment by skoren** [comment]
The best option is increasing the corOutCoverage. You could run just the correction which is fasta and then randomly subsample the corrected reads yourself to keep not just the longest but a random subset. Then, run an assembly of only the subset reads (using -nanopore-corrected). Alternatively you could run the full dataset and use the faster assembly option (```overlapper=mhap utgReAlign=true```) which would speed up the run.

**Comment by liaoyunshi** [comment]
Thanks for your prompt reply. Your suggestion is really helpful for me!

**Comment by brianwalenz** [comment]
Good question.  I added random sampling to the FAQ.

**Comment by wangyugui** [comment]
@brianwalenz 

Can we add a random corOut option to canu?

**Comment by wangyugui** [comment]
It seems that 'seqtk sample'  can be used to random sampling.

**Comment by brianwalenz** [comment]
I can do it, but not for a while.  We're planning changes to generating overlaps, then changes to corrected reads, then changes to consensus sequences.  It'll fit naturally into the last (for a technical reason).

The Canu roadmap is at https://github.com/marbl/canu/projects/2, but it's not written in any great detail and changes frequently.

**Comment by wangyugui** [comment]
The roadmap  info is very good. Thanks
