### ISSUE TITLE
Lots of contigs

### ISSUE THREAD

**Issue by bruce-boles** [marbl/canu#585]
Hello,

I recently ran a sequence on my nanopore. Then I ran the data through the latest version of the canu program. I received about 40 contigs. Obviously, I would like to decrease this number. Do you have any suggestions?

Sincerely,

Bruce

**Comment by skoren** [comment]
The continuity of the assembly is dependent on coverage, read length, and genome repeat content. Without more information, it isn't possible to say how to reduce the number of contigs nor if they should be reduced. You can look at the FAQ:
http://canu.readthedocs.io/en/latest/faq.html#my-assembly-continuity-is-not-good-how-can-i-improve-it

to see if any of that helps. If you have more questions, open a new issue with more details on your run (e.g input coverage, canu output, etc).
