### ISSUE TITLE
MhapRuntimeException: Next sequence does not start with >. Invalid format.

### ISSUE THREAD

**Issue by chenyufanxin** [marbl/canu#586]
Hi,
I just run the canu v1.5 to assemble the human genome on a slurm grid , here is my command:

`canu -p ren -d ~/storage/assemble_canu genomeSize=2.93g correctedErrorRate=0.040 corMhapSensitivity="low" gnuplotTested=true merylMemory=60  batMemory=60 cnsMemory=60 -pacbio-raw ~/storage/ren.fastq.gz`

But it failed in 1-overlapper,  and the output of canu.out is like this:

`--  job 1-overlapper/blocks/000210.dat FAILED.
--   job 1-overlapper/blocks/000211.dat FAILED.
--   job 1-overlapper/blocks/000213.dat FAILED.
--   job 1-overlapper/blocks/000215.dat FAILED.
--   job 1-overlapper/blocks/000216.dat FAILED.
--   job 1-overlapper/blocks/000217.dat FAILED.
--   job 1-overlapper/blocks/000218.dat FAILED.
--   job 1-overlapper/blocks/000219.dat FAILED.
--   job 1-overlapper/blocks/000222.dat FAILED.
--   job 1-overlapper/blocks/000226.dat FAILED.
--   job 1-overlapper/blocks/000231.dat FAILED.
--   job 1-overlapper/blocks/000238.dat FAILED.`
 `Don't panic, but a mostly harmless error occurred and Canu stopped.
Canu release v1.5 failed with:
  canu iteration count too high, stopping pipeline (most likely a problem in the grid-based computes)
`

And I also check the output in correctin/1-overlapper/precompute.*.out , here is  some of it :

`edu.umd.marbl.mhap.impl.MhapRuntimeException: Next sequence does not start with >. Invalid format.
        at edu.umd.marbl.mhap.impl.FastaData.enqueueNextSequenceInFile(FastaData.java:152)
        at edu.umd.marbl.mhap.impl.FastaData.dequeue(FastaData.java:108)
        at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.enqueue(SequenceSketchStreamer.java:131)
        at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.enqueueUntilFound(SequenceSketchStreamer.java:232)
        at edu.umd.marbl.mhap.impl.SequenceSketchStreamer.dequeue(SequenceSketchStreamer.java:118)
        at edu.umd.marbl.mhap.impl.SequenceSketchStreamer$2.run(SequenceSketchStreamer.java:362)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)`

`edu.umd.marbl.mhap.impl.MhapRuntimeException:java.io.IOException: Bad file descriptor
        at edu.umd.marbl.mhap.impl.SequenceSketchStreamer$2.run(SequenceSketchStreamer.java:367)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by skoren** [comment]
The fasta sequences being read are written right before mhap is run in the same job. Are there any errors from the gkpStore command in the output file? Given that most of your jobs ran without errors and the failed ones are complaining about I/O and truncated files, I would guess you are out of space. Is there any quota on your storage you are hitting?

**Comment by chenyufanxin** [comment]
Thanks for your reply, skoren. The storage I am hitting has 5TB space, I think it is enough for canu work.And I found that one of the precompute.*.out file reported  errors about gkpStore command:


Running job 210 based on SLURM_ARRAY_TASK_ID=210 and offset=0.
Dumping reads from 19437001 to 19530000 (inclusive).
safeRead()-- Read failure on gkStore::gkStore_loadDataFromFile::blob: Bad file descriptor.
safeRead()-- Wanted to read 3172 objects (size=1), read 832.
gatekeeperDumpFASTQ: AS_UTL/AS_UTL_fileIO.C:152: size_t AS_UTL_safeRead(FILE*, void*, const char*, size_t, size_t): Assertion (*__errno_location ()) == 0' failed.
Failed with 'Aborted'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::102 in _Z17AS_UTL_catchCrashiP7siginfoPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
AS_UTL/AS_UTL_fileIO.C::152 in _Z15AS_UTL_safeReadP8_IO_FILEPvPKcmm()
stores/gkStore.C::176 in _ZN6gkRead25gkRead_loadDataFromStreamEP10gkReadDataP8_IO_FILE()
stores/gkStore.C::197 in _ZN6gkRead23gkRead_loadDataFromFileEP10gkReadDataP8_IO_FILE()
stores/gkStore.H::543 in _ZN7gkStore20gkStore_loadReadDataEP6gkReadP10gkReadData()
stores/gatekeeperDumpFASTQ.C::368 in main()
(null)::0 in (null)()
(null)::0 in (null)()
/tmp/slurmd/job00328/slurm_script: line 1278: 22997 Aborted                 $bin/gatekeeperDumpFASTQ -G ../ren.gkpStore $rge -nolibname -fasta -o ./blocks/$job.input
Failed to extract fasta.

**Comment by chenyufanxin** [comment]
In addition, the 5 TB storage I mentioned above is on the master node in slurm grid , and it is  mounted to all slave nodes through samba. Does something go wrong when master node share data with slave nodes?

**Comment by brianwalenz** [comment]
Is this the last of the precompute jobs?

Is this reproducible?  Try running by hand - `precompute.sh 210` from within the 1-overlapper directory.

How many reads are in the store?  This is reported in the canu screen output, and saved in the *.report file in the assembly directory.

Can you run `gatekeeperDumpFASTQ -G ren.gkpStore -fasta -r 19437001-19530000 -o reads.fasta`?  How about for the last ten reads (change the -r numbers based on the number of reads in the store)?

How big is the `ren.gkpStore/blobs` file?

**Comment by chenyufanxin** [comment]
I just run `./precompute.sh 210 ` and found that it run well. Does it mean that the problem is not due to reads in gkpStore? 
There are  22324993 reads in the gkpStore, here is the output of my ren.report:
`[CORRECTION/READS]
-- In gatekeeper store 'correction/ren.gkpStore':
--   Found 22324993 reads.
--   Found 210633018409 bases (71.88 times coverage).
--   Read length histogram (one '*' equals 94021 reads):
--        0   4999 6144214 *****************************************************************
--     5000   9999 6109219 ****************************************************************
--    10000  14999 6581470 **********************************************************************
--    15000  19999 2498792 **************************
--    20000  24999 707319 *******
--    25000  29999 202815 **
--    30000  34999  57485
--    35000  39999  16818
--    40000  44999   4782
--    45000  49999   1352
--    50000  54999    464
--    55000  59999    158
--    60000  64999     55
--    65000  69999     16
--    70000  74999      9
--    75000  79999      8
--    80000  84999      6
--    85000  89999      6
--    90000  94999      4
--    95000  99999      0
--   100000 104999     1`

And I can run `gatekeeperDumpFASTQ -G ren.gkpStore -fasta -r 19437001-19530000 -o reads.fasta`  with no error. The command run well too with the last ten reads.
 The size of ren.gkpStore/blobs file is 52G

**Comment by skoren** [comment]
We should catch and abort the job when gatekeeper fails rather than running MHAP since this leaves a bad fasta file behind.

Yes, the fact that it runs implies it was probably an intermittent error with the FS. You could try limiting the number of concurrent jobs by increasing the threads or memory used for MHAP to create less jobs on your cluster. You can also run the failed jobs by hand and re-run Canu to have it continue. However, it is possible subsequent I/O-heavy jobs will encounter errors on your system.

**Comment by brianwalenz** [comment]
We **are** catching the gatekeeperDumpFASTQ errors.

Thanks for the gatekeeper logs and what not.  I was worried the data file in gkpStore was truncated, but it isn't.  I'm going to chalk this up to filesystem quirkiness, especially since it runs by hand, and the failing jobs are seemingly random.  I can't think of anything better than limiting the number of jobs that run at once.

**Comment by chenyufanxin** [comment]
Thanks. I will try that!
