### ISSUE TITLE
CANU using tons of diskspace in 1-correction step

### ISSUE THREAD

**Issue by sebastiangornik** [marbl/canu#587]
Hi,

I used CANU on a 2.4 Gb genome with approx >25X coverage reads on a slurm grid. In the 1-correction it used up >200TB of disk space and literally broke the cluster as it filled up the free disk to the rim. I had to stop the run and erase all the data to allow other users to use scratch space.

I do not know what I set wrong for this to happen. I invoke canu like so:
```
canu -p FI_1 -d FI_1 genomeSize=2.4g -pacbio-raw /data/snapdragon/x_gorniks/Fenneropenaeus/CANU/PacBio_rawdata_links/*subreads.fastq gridEngine=slurm maxThreads=128 correctedErrorRate=0.075 gridOptions="--time=96:00:00"
```
Any idea! How can I limit disk space usage and still get an assembly? I previously used CANU off the grid for much smaller genomes and got away with 64 cores :-)

Sorry for being so ignorant!

Thx!

Here the canu.out output after I start the run:
```
-- Canu v1.4 (+72 commits) r8067 feb313be9d64ae69cb623aca7a029ef72712d47b.
-- Detected Java(TM) Runtime Environment '1.8.0_131' (from 'java').
-- Detected gnuplot version '4.6 patchlevel 6' (from 'gnuplot') and image format 'svg'.
-- Detected 64 CPUs and 126 gigabytes of memory.
-- Limited to 64 CPUs from maxThreads option.
-- Detected Slurm with 'MaxArraySize' limited to 1048575 jobs.
-- 
-- Found   4 hosts with  64 cores and 1728 GB memory under Slurm control.
-- Found 232 hosts with  64 cores and  144 GB memory under Slurm control.
-- Found  40 hosts with  28 cores and  144 GB memory under Slurm control.
-- Found  93 hosts with  16 cores and   64 GB memory under Slurm control.
-- Found   1 host  with  40 cores and  128 GB memory under Slurm control.
-- Found 243 hosts with  64 cores and  288 GB memory under Slurm control.
-- Found   1 host  with  32 cores and  262 GB memory under Slurm control.
-- Found   4 hosts with  20 cores and   64 GB memory under Slurm control.
-- Found   2 hosts with  56 cores and  576 GB memory under Slurm control.
-- Found   3 hosts with  20 cores and  145 GB memory under Slurm control.
-- Found   3 hosts with  64 cores and 1952 GB memory under Slurm control.
-- Found   7 hosts with  32 cores and   64 GB memory under Slurm control.
-- Found  31 hosts with  20 cores and   96 GB memory under Slurm control.
-- Found   1 host  with  32 cores and  257 GB memory under Slurm control.
-- Found  16 hosts with  72 cores and  251 GB memory under Slurm control.
-- Found   9 hosts with  64 cores and 1152 GB memory under Slurm control.
-- Found   3 hosts with  64 cores and  864 GB memory under Slurm control.
-- Found   1 host  with  80 cores and 1728 GB memory under Slurm control.
-- Found   2 hosts with  20 cores and  512 GB memory under Slurm control.
-- Found 137 hosts with  20 cores and  128 GB memory under Slurm control.
-- Found   2 hosts with  20 cores and  256 GB memory under Slurm control.
-- Found  10 hosts with  56 cores and   70 GB memory under Slurm control.
-- Found  12 hosts with  16 cores and  251 GB memory under Slurm control.
-- Found   1 host  with  32 cores and  144 GB memory under Slurm control.
-- Found   1 host  with  40 cores and   96 GB memory under Slurm control.
-- Found   6 hosts with  56 cores and  144 GB memory under Slurm control.
--
-- Run under grid control using   64 GB and  32 CPUs for stage 'meryl'.
-- Run under grid control using   16 GB and   8 CPUs for stage 'mhap (cor)'.
-- Run under grid control using    5 GB and   4 CPUs for stage 'overlapper (obt)'.
-- Run under grid control using    5 GB and   4 CPUs for stage 'overlapper (utg)'.
-- Run under grid control using   10 GB and   4 CPUs for stage 'falcon_sense'.
-- Run under grid control using    2 GB and   1 CPU  for stage 'ovStore bucketizer'.
-- Run under grid control using   32 GB and   1 CPU  for stage 'ovStore sorting'.
-- Run under grid control using    5 GB and   4 CPUs for stage 'read error detection'.
-- Run under grid control using    4 GB and   1 CPU  for stage 'overlap error adjustment'.
-- Run under grid control using  128 GB and  32 CPUs for stage 'bogart'.
-- Run under grid control using   64 GB and   8 CPUs for stage 'consensus'.
--
-- Parameters:
--
--  genomeSize        2400000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.0450 (  4.50%)
--    obtOvlErrorRate 0.0750 (  7.50%)
--    utgOvlErrorRate 0.0750 (  7.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0750 (  7.50%)
--    utgErrorRate    0.0750 (  7.50%)
--    cnsErrorRate    0.0750 (  7.50%)
--
-- This is canu parallel iteration #2, out of a maximum of 2 attempts.
--
--
-- BEGIN CORRECTION
--
-- All 253 mhap precompute jobs finished successfully.
-- mhap attempt 1 begins with 0 finished, and 631 to compute.
--
-- '/scratch/dragon/amd/x_gorniks/FI_1/correction/1-overlapper/mhap.jobSubmit.sh' -> job 1267037 tasks 1-631.
--
```

**Comment by skoren** [comment]
This would seem to indicate the genome has some very prolific repeat sequences which is blowing up the space usage. There isn't a simple fix, just some parameter tweaks that should suppress repeats more and increase the minimum overlap size:

```corMhapFilterThreshold=0.0000000002 corMhapOptions="--threshold 0.78 --num-hashes 768 --num-min-matches 2 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50"

You'll need to restart from scratch. The downside with this is the precompute step will likely require more memory than the mhap.sh step and that Canu accounts for. The easiest fix for that would be to edit the precompute.sh and precompute.jobSubmit.sh scripts to request/allocate 4x more than the defaults and see if the jobs complete if you submit them manually.

I'd also suggest updating to the latest Canu from tip since your version is a bit old.

**Comment by skoren** [comment]
Update the code as well, there's been significant improvements in the corrected reads since your version.

**Comment by sebastiangornik** [comment]
i did that also. cloned the latest from github. Thx

**Comment by brianwalenz** [comment]
Add in useGrid=remote too.  This will set up for slurm, but prompt you to submit jobs.  That way, you can edit the two scripts before they run.

**Comment by sebastiangornik** [comment]
Does remote not mean I will have to submit all jobs manually after the scripts have been generated?

**Comment by skoren** [comment]
Yes you'd run the submit script, wait for the job to complete, and re-run Canu again. You only need to do that up until the precompute.sh step, once that one is done you can return to automated grid control by running Canu without the useGrid=remote option.

**Comment by sebastiangornik** [comment]
makes sense. I will try that!

**Comment by sebastiangornik** [comment]
The precompute jobs seem to start and then just idle, no data is being generated? Any idea why that is?

**Comment by skoren** [comment]
Are they still exhibiting this behavior or did they run? If you're still having trouble, try the attached mhap version. Just place the tar in the canu/src/mhap and re-build and the jar file used will get updated.

**Comment by sebastiangornik** [comment]
Sadly I still can not get canu to resolve my data! It seems to be a highly repetitive genome and that seems to break any attempts to correct reads as intended. Any idea how to proceed? Much appreciated! Thx!

**Comment by skoren** [comment]
What do you mean "break any attempts to correct reads as intended". Repetitiveness isn't going to change how reads are corrected, it may just take more disk space. The assembly is certainly going to be less contiguous but that's a function of read length and repeat length.

**Comment by sebastiangornik** [comment]
I mean I have a maximum of 200TB scratch and this is not enough to run my data as mhap creates intermediate files much larger than this totaling across all mhap jobs :-(. So thsi genome is currently (for me) physically impossible to correct reads for.

**Comment by skoren** [comment]
Have you tried the increased repeat filter as suggested above with the updated jar? You can also decrease the sensitivity: ```corMhapFilterThreshold=0.0000000002 corMhapOptions="--threshold 0.80 --num-hashes 256 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50"```. If you are able to share the fastq, we could try running it locally to see how much space it is using.

**Comment by sebastiangornik** [comment]
Trying now! Will report back! Thx!

**Comment by skoren** [comment]
Inactive
