### ISSUE TITLE
Correction inquiry

### ISSUE THREAD

**Issue by abayega** [marbl/canu#589]
Hi,

for read correction, can I tell canu to use X coverage for correcting the reminder of the reads, or maybe use tell canu to use reads below a certain length to correct reads above a certain length? I wasn't sure if that's the 'corOutCoverage' parameter.

Thanks

**Comment by skoren** [comment]
Yes, the corOutCoverage will control which reads have a corrected consensus called. All reads are allowed to correct them, they don't have to be shorter than the read being corrected since you can find partial overlaps.
