### ISSUE TITLE
How to understand trimmedReads header

### ISSUE THREAD

**Issue by nottwy** [marbl/canu#590]
I find there are duplicate records in trimmedReads.

For example:

these two
**m54045_170413_080630/7144014/3441_13579** id=22042_1 id=13042 clr=76,1556        **m54045_170413_080630/7144014/3441_13579** id=22042_0 id=13041 clr=30,7422

and these two

**m54045_170413_080630/7144065/9637_19993** id=22078_1 id=13060 clr=31,7034        **m54045_170413_080630/7144065/9637_19993** id=22078_0 id=13059 clr=0,1505

please tell me what does the header mean and why the bold words are the same.

thank you.

**Comment by brianwalenz** [comment]
The bold letters are the name of the raw read.  The raw read had a region of low quality or garbage sequence in the middle that was trimmed out, resulting in two corrected reads.  The specific location of the two corrected reads in the raw read is not (currently) tracked.

**Comment by nottwy** [comment]
3ku, you are quick as a flash of lightning.  ; )

**Comment by brianwalenz** [comment]
On the easy questions, yes.  Cheers!
