### ISSUE TITLE
Chimeric contigs

### ISSUE THREAD

**Issue by steinjosh** [marbl/canu#591]
Hi,
I used Canu v1.5 on a 400 Mb genome with 70X coverage PacBio reads.  The resulting 208 contigs have an N50 of nearly 13 Mb.  The problem is that a handful of contigs are mis-assembled as evidenced by joining regions of different chromosomes.  Are there parameter settings that could reduce the formation of chimeric contigs?

Thanks,
Josh

**Comment by skoren** [comment]
Typically, you end up with a dozen or two errors on a mammalian assembly which we've split using other information (like HiC or optical maps) in the past. You can adjust at least one parameter which controls how tolerant Canu is of near-best overlaps for splitting contigs (```batOptions="-ca 5000 -cp 500"```). The default is 2000/200. 

If you update to the latest code from tip, the unitig graph will also capture these regions and split. You'd have to re-run the unitigging part of the assembly (```canu -assemble -pacbio-corrected asm.trimmedReads.fasta.gz```). The unitigs also split at heterozygous sites so, if your genome is very heterozygous, the unitigs will be much smaller than the contigs. You can use the information from the unitig tiling of the contigs to see if your suspect regions correspond to unitig breaks (they should) and use those locations to inform splitting.

**Comment by skoren** [comment]
Any updates on this? Especially if you ran tip or Canu 1.6 and it didn't capture these errors in unitig breaks as the unitigs should be correct.
