### ISSUE TITLE
Is there a tool you developed as a statistic of time that canu used?

### ISSUE THREAD

**Issue by nottwy** [marbl/canu#592]
Now I want to evaluate the CPU time that canu used but I haven't found a good way to do this.

Have you ever developed a tool to count the total CPU time that canu used?

The CPU time I said means: 
If I have a task which need 24 threads and it runs for 2 hours. The CPU time it costed is 48 hours.

**Comment by skoren** [comment]
No we have not developed any tools. Typically we use GNU time (often in /usr/bin/time) which reports both wall clock and cpu time on a single machine and cluster-specific tools on grid jobs (qacct on SGE, sacct on SLURM, etc).
