### ISSUE TITLE
Cluster filesystem choice for canu

### ISSUE THREAD

**Issue by chenyufanxin** [marbl/canu#593]
Hello, I'm running canu v1.5 on a slurm grid. And the cluster filesystem I'm using is samba. But I found that samba performs not very well because canu often reports errors about I/O. So can you recommend a  cluster filesystem for me? I'll appreciate it.

**Comment by brianwalenz** [comment]
NFS.

I do development and lots of testing using SSD's in a ZFS filesystem served via NFS over gigabit ethernet.  It easily supports 100 cores on six hosts.

Our production machines use Isilon storage served via NFS over 10 gigabit ethernet.  Supports around 2000 cores on around 60 hosts.

**Comment by chenyufanxin** [comment]
Thank you very much! I will try that!
