### ISSUE TITLE
momory limits exceeded

### ISSUE THREAD

**Issue by dominik-handler** [marbl/canu#594]
Hi,

I was running Canu snapshot v1.5 +197 changes (r83975560ddc4b8be68fe2905c651625141276de2ebff). I have problems with the memory requests for at least the red & oea steps. For both steps I had to manually increase memory settings after Canu crashed  because it consumed too much memory.
My dataset is all >20kb reads so I could imagine that this could cause the problem.

This is the Canu output after I increased the memory for red already.

```
Detected Java(TM) Runtime Environment '1.8.0_121' (from '/software/21062017/software/Java/1.8.0_121-foss-2017a/bin/java').
-- Detected 56 CPUs and 189 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /cm/shared/apps/slurm/17.02.2/bin/sinfo.
-- Detected Slurm with 'MaxArraySize' limited to 1000 jobs.
-- 
-- Found  13 hosts with  28 cores and  188 GB memory under Slurm control.
-- Found   2 hosts with  28 cores and  755 GB memory under Slurm control.
-- Found   1 host  with  28 cores and  125 GB memory under Slurm control.
-- Found   3 hosts with   1 core  and    3 GB memory under Slurm control.
-- Found   5 hosts with  28 cores and  125 GB memory under Slurm control.
-- Found   2 hosts with  28 cores and    0 GB memory under Slurm control.
-- Found   1 host  with  28 cores and  125 GB memory under Slurm control.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl     62 GB   14 CPUs  (k-mer counting)
-- Grid:  cormhap   13 GB   14 CPUs  (overlap detection with mhap)
-- Grid:  obtmhap   13 GB   14 CPUs  (overlap detection with mhap)
-- Grid:  utgmhap   13 GB   14 CPUs  (overlap detection with mhap)
-- Grid:  cor       17 GB    4 CPUs  (read correction)
-- Grid:  ovb        3 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs        8 GB    1 CPU   (overlap store sorting)
-- Grid:  red        6 GB    4 CPUs  (read error detection)
-- Grid:  oea        2 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat       31 GB    7 CPUs  (contig construction)
-- Grid:  cns       31 GB    7 CPUs  (consensus)
-- Grid:  gfa        8 GB    7 CPUs  (GFA alignment and processing)

-- Found Nanopore corrected reads in 'unitigging/canu_new_onSLURM.gkpStore'.
--
-- Generating assembly 'canu_new_onSLURM' in '~/canu'
--
-- Parameters:
--
--  genomeSize        150000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1440 ( 14.40%)
--    utgOvlErrorRate 0.1440 ( 14.40%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1440 ( 14.40%)
--    utgErrorRate    0.1440 ( 14.40%)
--    cnsErrorRate    0.1920 ( 19.20%)
--
--
-- BEGIN ASSEMBLY
--
--
-- Overlap error adjustment jobs failed, tried 2 times, giving up.
--   job 00001.oea FAILED.
--   job 00002.oea FAILED.
--   job 00003.oea FAILED.
--   job 00004.oea FAILED.
--   job 00005.oea FAILED.
--   job 00006.oea FAILED.
--

ABORT:
ABORT: Canu snapshot v1.5 +197 changes (r8397 5560ddc4b8be68fe2905c651625141276de2ebff)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:


```

Thank you,
Dominik

**Comment by ashis20kumar** [comment]
Hi Team,
I am facing some memory issues, can somebody help us.
Canu release v1.5
-- Detected Java(TM) Runtime Environment '1.8.0_121' (from 'java').
-- Detected gnuplot version '4.6 patchlevel 0' (from 'gnuplot') and image format 'svg'.
-- Detected 24 CPUs and 126 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
-- DEBUG
-- DEBUG
-- DEBUG Have 1 configurations; largest memory size 126 GB; most cores 24:
-- DEBUG   class0 - 1 machines with 24 cores with 126GB memory each.
-- DEBUG
--
-- Task bat can't run on any available machines.
-- It is requesting 128-512 GB memory and 8-32 threads.
-- See above for hardware limits.
--
================================================================================
Don't panic, but a mostly harmless error occurred and Canu stopped.

Canu release v1.5 failed with:
  task bat failed to find a configuration to run on

**Comment by brianwalenz** [comment]
@dominik-handler if you're stuck, set useGrid=remote.  This will print the sbatch command used to submit jobs.  You can then change the memory request manually.  Both of these (red and oea) are scheduled for fixing in the 1.7 release (https://github.com/marbl/canu/projects/2).

@ashis20kumar Set batMemory=120g (or lower).

**Comment by skoren** [comment]
Closing since this seems resolved by @brianwalenz comments. OEA and RED are not requesting memory properly (see Known Issues in the release notes: https://github.com/marbl/canu/releases/tag/v1.6). This will be fixed in the next release.
