### ISSUE TITLE
contigs from different corOutCoverage values

### ISSUE THREAD

**Issue by joyceil** [marbl/canu#599]
I am using canu 1.5 for a set of PacBio targeted sequencing data.  The targeted region is about 0.6 MB.  I tried different corOutCoverage values (default, 100, 500, and 1000) and got different sets of contigs.  I have the following questions:
1. Would the set from the largest corOutCoverage value be the most trustworthy because it incorporates all the reads? 
2. If a contig obtained with a lower corOutCoverage value lies in one of the gaps of another set of contigs obtained with a higher corOutCoverage value, should it be completely disregarded or can it be used to provide some information about the gap in question?

**Comment by skoren** [comment]
Generally the lower corOutCoverage values should be subsets of the largest value. However, some contigs could end up split with higher coverage or demoted to unassembled so I'd also set the parameters listed here: http://canu.readthedocs.io/en/latest/faq.html#my-asm-contigs-fasta-is-empty-why (this is changed in 1.6). To answer your specific questions.

1. Yes, I'd use the largest value
2. It can be used, in particular I'd check if it is in the unassembled.fasta in the largest value and use the asm.contigs.layout.readToTig file to see where the raw reads in those contigs ended up in the largest value assembly which looks like this:
```
#readID	tigID	coordType	bgn	end
1473246	3	ungapped	0	10176
952537	3	ungapped	8688	273
```
The tig ids just strip off the leading tig and 0s (so 3 is tig00000003 and the read IDs are based on the file in unitigging/asm.gkpStore/readNames.txt so you'd grep it for 1473246:
```
1473246	m54033_170802_072645/49873633/0_13789 id=4633190_0 id=3927370 clr=3159,13308
```

**Comment by skoren** [comment]
For the 1.5 release you are fine. If you switch your analysis to 1.6, this parameter is changed (see release notes: https://github.com/marbl/canu/releases/tag/v1.6). It should just keep all the contigs you're finding with the adjusted contigFilter in 1.6 rather than having to adjust the parameter in 1.5

**Comment by joyceil** [comment]
Thank you very much for the clarification.

Joyce

**Comment by skoren** [comment]
Closing since this seems to be resolved. Please open a new issue if you encounter other errors or have followup questions on these assemblies.
