### ISSUE TITLE
Assembly results - cannot find <prefix>.consensus.fasta

### ISSUE THREAD

**Issue by isovic** [marbl/canu#60]
Hi,
the example in the Quick Start section of the docs (http://canu.readthedocs.org/en/latest/quick-start.html) mentions that the final assembly results can be found in:
```
ecoli*/ecoli.layout
ecoli*/ecoli.consensus.fasta
```
After running the process, I can't seem to find any *.consensus.fasta file in my output folder.
However, there is a file called <prefix>.contigs.fasta in my output folder.
Looking into the stdout/stderr I don't see any failure reports.
Perhaps just the naming of the output file changed in the latest version?
Is the <prefix>.contigs.fasta file obtained prior to or after the consensus phase? 
I'm running commit 3151c35322ecab826e5ba897bdbc4e82c27b752a.

Thanks,
Best regards,
Ivan.

**Comment by skoren** [comment]
Yes, the latest version breaks out the single consensus.fasta result into asm.contigs.fasta, asm.bubbles.fasta, and asm.unassembled.fasta.

**Comment by isovic** [comment]
Ok, thank you!

Ivan
