### ISSUE TITLE
faster gzip

### ISSUE THREAD

**Issue by AGI-admin** [marbl/canu#600]
Is it possible to make the gzip step(s) faster?  It only uses one core.  There is a program called "pigz" which is a multi-threaded gzip which can use multiple cores.  Perhaps you can replace gzip with pigz.
Thanks

**Comment by brianwalenz** [comment]
The only gzip I see is for creating correctedReads.fasta, and that's not much of a bottleneck.  I'd rather not add a dependence on a non-standard utility.  Which gzip steps are you seeing?

**Comment by AGI-admin** [comment]
Yes that's was what I was seeing... we are testing with the new AMD Epyc processors.  was just a little frustrating to see only 1 core being used for ~20 mins while the rest of the machine is idle.

**Comment by skoren** [comment]
I'm going to close this and move to a feature request. I would consider this relatively low priority as there are other (single core as well) bottlenecks in the assembler we want to work on first (for example issue #602).
