### ISSUE TITLE
Missing asm.unitigs.bed file from output

### ISSUE THREAD

**Issue by mvollger** [marbl/canu#603]
Issue:
I cannot find the asm.unitigs.bed output after my assembly successfully completes. 
I am sure this is something silly on my part, but any help would be appreciated. 

Canu Version:
```
Canu snapshot v1.5 +27 changes (r8227 cb9abbde2549ed3a8cb2149136d8e045471ca96f)
```
Assembly Command:
```
 module load java/8u25 && {CANU_DIR}/canu -pacbio-raw {input.readsq} \
                genomeSize=200000 -d assembly -p asm useGrid=false \
                gnuplotTested=true  corMhapSensitivity=high corMinCoverage=1 corOutCoverage=300 \
                minOverlapLength=750 minReadLength=2000 \
                maxThreads={threads} cnsThreads={threads} ovlThreads={threads} mhapThreads={threads} \
                contigFilter="50 2000 0.75 0.75 50" \
                || ( >&2 echo " no real assembly" && \
                mkdir -p assembly && \
                > {output.asm} )
```
Final assembly directory:
```
asm.contigs.fasta             asm.trimmedReads.fasta.gz     asm.unitigs.layout.tigInfo  trimming.html
asm.contigs.gfa               asm.unassembled.fasta         asm.unitigs.masked.fasta    trimming.html.files
asm.contigs.layout            asm.unitigs.fasta             canu-logs                   unitigging
asm.contigs.layout.readToTig  asm.unitigs.gfa               canu-scripts                unitigging.html
asm.contigs.layout.tigInfo    asm.unitigs.gfa.gml           correction                  unitigging.html.files
asm.correctedReads.fasta.gz   asm.unitigs.gfa.png           correction.html
asm.correctedReads.length     asm.unitigs.layout            correction.html.files
asm.report                    asm.unitigs.layout.readToTig  trimming
```

**Comment by brianwalenz** [comment]
I think your copy of Canu is just slightly too old.  I can't find that specific version in the repo, but if "+27 changes" is accurate, you're about 5 changes too early.

The safest solution would be to upgrade to the 1.6 release and rerun just the 'unitigging' part:
```
canu .... -assembly -pacbio-corrected assembly/asm.trimmedReads.fasta.gz
```
Those contigFilter parameters are a bit aggressive.  The implementation of this changed in 1.6, but I think you'll still be OK -- high coverage BACs, right?

**Comment by mvollger** [comment]
Thanks, I have started a run with 1.6

Yes, they are very high coverage BACs, ~1000. Would you recommend changing anything? I am still playing with parameters.

If you have time I have some additional questions about asm.unitigs.bed and what it represents in the GFA graph. If you don't feel free to close and I'll try and figure it out. 
Does asm.unitigs.bed have the locations of the unitigs within asm.unitigs.fasta without the overlaps, or does it contain the locations of asm.unitigs.fasta in asm.contigs.fasta?
Also I am looking for a sequence that represents a collapsed duplication, and if my understanding of GFA graphs is correct there should be one and only one representation of this repeat in a GFA graph, but I have found that asm.unitgis.fasta contains sequences that appears multiple times across each contig. 

Thanks for your time!

**Comment by skoren** [comment]
The asm.unitigs.bed has the locations of the asm.unitigs.fasta in the asm.contigs.fasta. The unitigs can and do overlap each other within a contig.

The canu GFA output is not string graphs and the unitigs have overlaps at the read ends. That means if multiple unitigs end in the same repeat, they will have some similarity. This is indicated by the cigar string in the GFA. It is also possible that the repeat itself is split into multiple unitigs because differences within the repeat can end up separating parts of the repeat while leaving other parts unseparated.
