### ISSUE TITLE
 Failed to partition the reads

### ISSUE THREAD

**Issue by chenyufanxin** [marbl/canu#605]
Hello, I'm running canu on PBS HPC with the following command:
```
canu \
-p ecoli -d /home/xiatian/storage/test/ecoli-pacbio \
genomeSize=4.8m gnuplotTested=true \
gridOptions="-l nodes=node71+node72+node73+node74+node75" \
-pacbio-raw /home/xiatian/storage/test/pacbio.fastq
```
However canu failed at gatekeeperPartition step. Here is part of canu.out:
```
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0750 (  7.50%)
--
--
-- BEGIN ASSEMBLY
--
-- Unitigger finished successfully.
-- Found, in version 1, after unitig construction:
--   contigs:      0 sequences, total length 0 bp (including 0 repeats of total length 0 bp).
--   bubbles:      0 sequences, total length 0 bp.
--   unassembled:  0 sequences, total length 0 bp.
--
-- Contig sizes based on genome size --
--            NG (bp)  LG (contigs)    sum (bp)
--         ----------  ------------  ----------
--
-- Finished stage 'unitigCheck', reset canuIteration.
----------------------------------------
-- Starting command on Mon Aug 28 23:41:27 2017 with 124447.616 GB free disk space

    cd unitigging
    /home/xiatian/storage/canu-1.6/Linux-amd64/bin/gatekeeperPartition \
      -G ./ecoli.gkpStore \
      -T ./ecoli.ctgStore 1 \
      -b 15000 \
      -p 8 \
    > ./ecoli.ctgStore/partitionedReads.log 2>&1

-- Finished on Mon Aug 28 23:41:27 2017 (lickety-split) with 124447.616 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:

ABORT:
ABORT: Canu 1.6
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to partition the reads.
ABORT:
ABORT: Disk space available:  124447.616 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (unitigging/ecoli.ctgStore/partitionedReads.log):
ABORT:
```
And I also check the unitigging/ecoli.ctgStore/partitionedReads.log file:
```
For 11162 reads, will make 1 partition with up to 11163 reads.
tgTig::loadFromStream()-- failed to read four byte code: Success
Failed to load tig 45.
```
Do you have any idea to fix it?

**Comment by chenyufanxin** [comment]
Full output logs from the canu-scripts folder：
[canu-scripts.zip](https://github.com/marbl/canu/files/1259009/canu-scripts.zip)
The 4-unitigger folder:
[4-unitigger.zip](https://github.com/marbl/canu/files/1259010/4-unitigger.zip)

**Comment by skoren** [comment]
Looks like unitigger ran OK but there was another disk issue at the end when dumping the report:
```
$ cat ecoli.009.generateOutputs.sizes 
UNASSEMBLED (1086 tigs) (5575625 length) (5134 average) (1.16x coverage)
ng010     17381   lg010       24   sum      494199  (UNASSEMBLED)
ng020     14872   lg020       54   sum      974425  (UNASSEMBLED)
ng030     12946   lg030       88   sum     1440716  (UNASSEMBLED)
ng040     11330   lg040      128   sum     1925723  (UNASSEMBLED)
ng050      9869   lg050      174   sum     2407437  (UNASSEMBLED)
ng060      8165   lg060      227   sum     2887378  (UNASSEMBLED)
ng070      6574   lg070      291   sum     3360255  (UNASSEMBLED)
ng080      5113   lg080      373   sum     3842358  (UNASSEMBLED)
ng090      3817   lg090      483   sum     4321108  (UNASSEMBLED)
ng100      2649   lg100      635   sum     4800872  (UNASSEMBLED)
ng110      1633   lg110      861   sum     5280303  (UNASSEMBLED)
CONTIGS (1 tigs) (4647762 length) (4647762 average) (0.97x coverage)
ng010   4647762   lg010        1   sum     4647762  (CONTIGS)
ng020   4647762   lg020        1   sum     4647762  (CONTIGS)
ng030   4647762   lg030        1   sum     4647762  (CONTIGS)
ng040   4647762   lg040        1   sum     4647762  (CONTIGS)
ng050   4647762   lg050        1   sum     4647762  (CONTIGS)
ng060   4647762   lg060        1   sum     4647762  (CONTIGS)
ng070   4647762   lg070        1   sum     4647762  (CONTIGS)
ng080   4647762   lg080        1   sum     4647762  (CONTIGS)
ng090   4647762   lg090        1   sum     4647762  (CONTIGS)
```

```
$ cat unitigger.1.out-1 
Running job 1 based on PBS_ARRAYID=1 and offset=0.
tgTig::loadFromStream()-- failed to read four byte code: Success
Failed to load tig 45.
```
This explains the 0 contigs assembled since the error is coming from the dump of the store. I would guess the ctg and utgStores are corrupt. The logs in ``` unitigging/ecoli.ctgStore/partitionedReads.log``` should confirm that. You can also try:
```
tgStoreDump \
  -G ../ecoli.gkpStore \
  -T ../ecoli.ctgStore 1 \
  -sizes -s 4800000 \
> ../ecoli.ctgStore/seqDB.v001.sizes.txt
```
from within the unitigging/4-unitigger directory.

One place where Canu is not currently checking for I/O errors is on file close so I'm guessing what is happening on your system is the final flush is being lost somehow leading to the truncated fasta files as well as this error. We'll add a check there as well to make it fail in these instances.

**Comment by brianwalenz** [comment]
Not sure what else to do here.  These errors seem like files aren't being flushed to the file server correctly.  About all I can do is check for errors when we close files in the code, which I just added.

**Comment by Billymyh** [comment]
I got the same problem, have you solved it? @chenyufanxin

**Comment by hd4git** [comment]
Hi skoren,

I also ran into the same problem. I have 3 separate samples with pacbio reads and get expected assemblies for 2 of them but for 1 no contigs are being made and I get:
"contigs:      0 sequences, total length 0 bp (including 0 repeats of total length 0 bp)."
[ccs.report.zip](https://github.com/marbl/canu/files/2014490/ccs.report.zip)

As mentioned in FAQs, I tried reducing stringency with contigFilter and also tried mentioning smaller genomeSize just in case smaller contigs can be made. But nothing helps.
While the problematic set has ~11.5k ccs reads, the other 2 that work fine have ~ 31.7k and 46.2k CCS reads ranging in size from ~70 to ~11000 nts.

I am expecting contigs of 10kb, 7kb, 4kb and 2kb lengths. 
Can you please let me know what could be the problem and  suggest what settings should be used? 

Thanks!!

**Comment by brianwalenz** [comment]
Try downsampling your trimmed reads to around 40x.  If that fails, downsample the uncorrected reads to around the same (you've got almost 4000x coverage in raw reads, which is waaaay too much).  Assuming the reads around 5kbp are the 'real' stuff, discarding reads below 4kbp might help too.  If it still fails, open a new issue.

**Comment by hd4git** [comment]
Makes sense. Thanks for your quick response.
Can you also let me know how should I get a random downsample.
