### ISSUE TITLE
fail to assemble from MinION data

### ISSUE THREAD

**Issue by splaisan** [marbl/canu#607]
`canu -d canu_albacore-pass 	-p ont_albacore_pass 	genomeSize=25M 	maxThreads=84 	maxMemory=500 	-nanopore-raw albacore_out/albacore_reads.fq.gz`

I get the error: `Illegal division by zero at /opt/biotools/canu_git/Linux-amd64/bin/lib/canu/CorrectReads.pm line 196.`

I have large resources (88threads and 500GB ram). I tried several times with and without thread and ram limits and it keeps crashing. 

== attached the log file for the run
`Canu snapshot v1.6 +12 changes (r8424 b2e67e16462ab63ce3c23786bb64a35cc241891b)`

Thanks for your help.

[canu-run_log_1504180594.txt](https://github.com/marbl/canu/files/1267317/canu-run_log_1504180594.txt)

**Comment by skoren** [comment]
You're running the tip which had a change in this code and introduced the bug which was fixed in the subsequent commit (e234bb3253e280837d2d62bbdb5c1212168bcda8) so if you update the code or use the 1.6 release, it should run.

**Comment by splaisan** [comment]
cool I do that right now, thanks!!!

**Comment by skoren** [comment]
Yes, that should have the bug fix.

**Comment by splaisan** [comment]
Hi Sergey,
I ran the assembly yesterday with the corrected version and it hanged since 8PM until now on teh same stage (see screen-shot); Is it normal that the process takes so long at that stage?
Thanks
[Imgur](http://i.imgur.com/D5JUGje.png)

**Comment by skoren** [comment]
Those steps are the slowest part of the assembly (especially given very long reads or very high coverage, see issues #609 or #521). If you have more than 100x coverage, you can randomly downsample. You can also run the fast version (```overlapper=mhap utgReAlign=true```) which you can run on the corrected reads in parallel to this assembly (```canu -nanopore-corrected asm/correctedReads.fasta.gz```).

**Comment by splaisan** [comment]
Thanks a lot for your kind feedback. 
I am also considering correcting multiple times as said in your faq since this is 1D quick-library data and the full auto run seems to do only one round of correction (right?).
I will let this go its way in teh week-end to see what comes out.
Best and thanks again

**Comment by skoren** [comment]
You probably don't need multiple rounds of correction if this is recent albacore R9.4 or 9.5 data, even though it is 1D it is high identity enough to be assembled with one pass. The multiple rounds are required only for data less than about 80% identity.

**Comment by splaisan** [comment]
Nice, this is good news!
I read the other two threads you pointed to and have a new question.
Should I add your 2 suggested options to a '-s default-config' file to link to my run call?
I am running on a single host and noticed I am using only few threads now and very limited RAM while I have 88 thr and 500GB RAM available.
What kind of extra options can I add to such conf file to force using more of the resources and speed up this long step (and others)? 
I found the full option list command but do not quite understand what they individually do (any doc about that?)
Thanks again

**Comment by skoren** [comment]
Your settings look ok and the preamble for Canu should tell you how many threads/resources it is going to use. The reason you are using only one thread now is because there is a handful of reads responsible for the slowness and so all other threads have finished and are waiting on the stragglers.

Then main way to speed it up would be to reduce the correctedErrorRate or use the fast option I suggested. I would try to run at least once with both options because we've seen on some genomes the fast option is not as contiguous as the default which is why it is not yet the default. If the fast option is comparable to the default and you're working with similar genomes (e.g. similar size, complexity) you're probably OK defaulting to the fast option. You can make a .canu file in your home directory which will always get used to add default options.

**Comment by splaisan** [comment]
Nice, will do as soon as this ends or if I loose patience.

The albacore I used on my fast5 data was a fresh ubuntu install . Does this match what you call R9.4 or recent above?

Cheers

```
read_fast5_basecaller.py --version
ONT Albacore Sequencing Pipeline Software (version 1.2.6)
```

**Comment by skoren** [comment]
Yes, I don't think albacore supports the old R7 flowcells. Albacore is the base caller, R9.4 is the physical flowcell (FLO-MIN106 is R9.4 and FLO-MIN107 is R9.5 I believe). But if you're using albacore, yes you should be fine.

**Comment by splaisan** [comment]
Thanks Sergey, it was a MIN106 if i remember well.
I see that I have quite some ONT vocabulary to learn still ;-)
Looking for the results of the asm.
Have a great WE
