### ISSUE TITLE
Canu got confused with Histone cluster in 1 out of 3 assemblies

### ISSUE THREAD

**Issue by dominik-handler** [marbl/canu#608]
Hi,

I performed 3 assemblies with Canu. The only difference was the amount of input reads I supplied. In one of the assemblies Canu got confused and placed a large block of sequence completely wrong. Looking into the issue it seems that the Histone cluster is somehow involved in this issue. this here are the synteny plots comparing the assembly to the reference for this chromosome:
<img width="114" alt="correct" src="https://user-images.githubusercontent.com/12491961/29947035-0863c2b6-8ea8-11e7-9f37-d798550685d3.png">
<img width="284" alt="wrong" src="https://user-images.githubusercontent.com/12491961/29947036-0864aa1e-8ea8-11e7-8988-9ea5957500f5.png">

Are you interested in some background logs/data to have a look into the issue? I am fine at the moment as my last assembly fixed the issue anyways. 

Dominik

**Comment by skoren** [comment]
Were these random downsampling runs of the largest dataset? Was the full dataset one of the correct assemblies?

Sure if you can share the full Canu output as it ran from the three assemblies and the log files in the 4-unitigger directories we can take a look to see if anything jumps out.

**Comment by dominik-handler** [comment]
Downsampling was not random. The runs looked like this:
1: ~15.8 Gb of input data (>1kb no quality filter)
2: ~9.6 Gb of input data (same as above + one additional run filtered for >20kb and avg Phred >13) ~60x raw coverage
3: ~10.6 Gb of input data (same as 2 with filtering to Phred>10 and >11kb

I can give you remote access to my full outputs if I can send you the links in private.

**Comment by skoren** [comment]
Sorry for not replying earlier, you can upload them to our incoming ftp, it is write-only so no one except me can read it. The instructions are here:
http://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you

**Comment by brianwalenz** [comment]
Idle.
