### ISSUE TITLE
hang at `./overlap.sh 1 > ./overlap.000001.out 2>&1`

### ISSUE THREAD

**Issue by shpotes** [marbl/canu#609]
Hi,

I've been trying to run canu on my Dell Precision 3510 with a 161,5 MB nanopore fastq and ... still have 888h running, then i run the same data in my hpz240 with 8 cores, have 413h. It's normal?

**Comment by skoren** [comment]
This is a known issue with very long nanopore reads, especially if you have a short genome and very high coverage (see issues #521 and release notes). You can try the fast option (```overlapper=mhap utgReAlign=true```) as well.
