### ISSUE TITLE
canu crash on grid: submitOrRunParallelJob failed

### ISSUE THREAD

**Issue by newlbs** [marbl/canu#611]
Hi, I used the following comman to do a denovo assembly on a slurm cluster.
canu -p aphid -d aphid_pb_grid_bh25 genomeSize=500m -pacbio-raw french_pacbio.fastq gridOptions="--partition=standard --time=5-00:00:00 --mem-per-cpu=12G"

And the canu version is:
Canu snapshot v1.6 +14 changes (r8426 14520f819a1e5dd221cc16553cf5b5269227b0a3)

It reported some errors as follows:
```
-- Finished stage 'cor-gatekeeper', reset canuIteration.
-- Finished stage 'merylConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
--

CRASH:
CRASH: Canu snapshot v1.6 +14 changes (r8426 14520f819a1e5dd221cc16553cf5b5269227b0a3)
CRASH: Please panic, this is abnormal.
ABORT:
CRASH:   Failed to submit batch jobs.
CRASH:
CRASH: Failed at /gpfs/fs1/sfw2/canu/b1/Linux-amd64/bin/lib/canu/Execution.pm line 1119.
CRASH: 	canu::Execution::submitOrRunParallelJob('aphid', 'meryl', 'correction/0-mercounts', 'meryl', 1) called at /gpfs/fs1/sf
w2/canu/b1/Linux-amd64/bin/lib/canu/Meryl.pm line 538
CRASH: 	canu::Meryl::merylCheck('aphid', 'cor') called at /software/canu/b1/bin/canu line 663
CRASH: 
CRASH: Last 50 lines of the relevant log file (correction/0-mercounts/meryl.jobSubmit-01.out):
CRASH:
CRASH:
```
Looks like it's somthing wrong with the sbumition? It used to work fine on our cluster, but we did have an system upgrade recently. I also updated the canu to the latest version. I am not sure where is the potential problem.

**Comment by skoren** [comment]
First, don't specify the memory on the gridOptions since Canu will request it for each job as needed.

Most likely the submit command is missing some option required on your system. What is the full output in correction/0-mercounts/meryl.jobSubmit-01.out? What happens if you try to run correction/0-mercounts/meryl.jobSubmit-01.sh manually?

**Comment by newlbs** [comment]
Hi @skoren Thanks for your reply. correction/0-mercounts/meryl.jobSubmit-01.out showed
sbatch: error: Batch job submission failed: Requested node configuration is not available
You are right that the memory request probably caused the problem. I removed it and started running it again now. Mannually running correction/0-mercounts/meryl.jobSubmit-01.sh did not start any jobs.

**Comment by skoren** [comment]
I would guess due to the threads requested by meryl there was no machine left to satisfy your memory request.
