### ISSUE TITLE
didn't find any mers? error

### ISSUE THREAD

**Issue by newlbs** [marbl/canu#615]
Hi, I have encountered the following errors when running canu on a grid:
```
-- Found PacBio uncorrected reads in 'correction/aphid.gkpStore'.
--
-- Generating assembly 'aphid' in '/gpfs/fs2/scratch/bli16/French_pb/aphid_pb_grid_bh25'
--
-- Parameters:
--
--  genomeSize        500000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0750 (  7.50%)
--
--
-- BEGIN CORRECTION
--

CRASH:
CRASH: Canu snapshot v1.6 +14 changes (r8426 14520f819a1e5dd221cc16553cf5b5269227b0a3)
CRASH: Please panic, this is abnormal.
ABORT:
CRASH:   didn't find any mers?.
CRASH:
CRASH: Failed at /gpfs/fs1/sfw2/canu/b1/Linux-amd64/bin/lib/canu/Meryl.pm line 670.
CRASH: 	canu::Meryl::merylProcess('aphid', 'cor') called at /software/canu/b1/bin/canu line 664
CRASH: 
CRASH: Last 50 lines of the relevant log file (correction/0-mercounts/aphid.ms16.histogram.info):
CRASH:
CRASH:
```

The command I used is
canu -p aphid -d aphid_pb_grid_bh25 genomeSize=500m -pacbio-raw french_pacbio.fastq gridOptions="--partition=standard --time=1-00:00:00"

The version is 
Canu snapshot v1.6 +14 changes (r8426 14520f819a1e5dd221cc16553cf5b5269227b0a3)

**Comment by brianwalenz** [comment]
From within the correction/0-mercounts/ directory, what is the result of running:
```
meryl -Dh -s aphid.ms16 > aphid.ms16.histogram
```
(meryl might not be in your path, it's in the same directory the canu command is)

**Comment by newlbs** [comment]
Hi Brian, the result is as follows:

```
bitPackedFile::bitPackedFile()-- 'aphid.ms16.mcdat' doesn't appear to be a bitPackedFile, not opened.
bitPackedFile::bitPackedFile()-- found  at position 0000000000000000
```

**Comment by skoren** [comment]
Can you do an ```ls -la``` on the correction/0-mercounts folder and post the output of the previous canu output (probably ```canu-scripts/canu.01.out```). It seems meryl didn't run at all or couldn't write its output.

**Comment by newlbs** [comment]
Hi skoren, I have restarted the run. I will let you know if this problem occurs again. Thank you.
