### ISSUE TITLE
Polish with corrected-only sequences or corrected-trimmed sequences?

### ISSUE THREAD

**Issue by uceleste** [marbl/canu#620]
Dear All

I did some assembly testing with Canu v1.5 using a dataset of the newest PacBio Sequel technology, and I'm really happy of the results!

Now I would try to use the corrected sequences produced by Canu to polish the assembly and to check its completeness with Quiver/Arrow. My question is simple: 

Is it better to use the corrected-only sequences or the corrected-trimmed sequences?

Thanks!

**Comment by brianwalenz** [comment]
Neither.  You want to use the raw data for these.

Canu 1.6 is out, too.

**Comment by uceleste** [comment]
Okay, understood! Thank you very much for the quick response. And yes, I am about to upgrade Canu to version 1.6.
