### ISSUE TITLE
How to run in a grid mode on some nodes only?

### ISSUE THREAD

**Issue by tbawin** [marbl/canu#623]
Hi,

Thanks to your support (#507) I am able to run Canu in a grid mode.

Up to now, all is running smoothly! My concern here is about convenience.

Indeed when I am trying to assemble large genomes, the grid is flooded by numerous small jobs that Canu submits by itself from the front node.

This is what is expected of course, but other users are no longer able to submit their own jobs to the grid and become crazy.

So I am wondering: is there a way to force Canu to submit its jobs to a specific group of nodes?

I am pretty sure it will be appreciated if I can leave some free space on the grid.

Here is a typical command that I use: 

`canu -correct -pacbio-raw ../../cassava/genome_assemblies/raw_60444/subreads_47smrt_raw.fq genomeSize=527m \
gnuplotTested=true gridOptionsExecutive="-l hostname=node01" gridEngineThreadsOption="-pe snode THREADS" gridEngineMemoryOption="-l mem_free=MEMORY -l mem_total=MEMORY" \
maxMemory=256 maxThreads=16 -p 60444_genome -d 60444_genome`

The current version is Canu snapshot v1.5 +46 changes.

Thanks!

**Comment by brianwalenz** [comment]
Definitely update to the 1.6 release.

This looks like SGE.

As far as I know, it isn't possible to limit to a set of nodes.  You can specify a single node (as you've done for the master) but can't specify more than one.  You'll have to make a new queue with a subset of the nodes to do this.

See if gridOptions="-tc N" will work for you.  This will limit the number of tasks running to N.  It doesn't know about threads, just number of jobs - meaning that the jobs that use 16 threads will submit N jobs (using N*16 CPUs) and the jobs that use one thread will use only N CPUs.  You can get finer control with, e.g., gridOptionsCNS, gridOptionsOVL, gridOptionsMHAP, etc.  All the choices are listed in the '-defaults' output.

Second option is to use the SGE priority mechanism, also through gridOptions.  "-p -999" will give your jobs almost the lowest priority, so, in theory, any other job will run first.  In practice, SGE seems to favor multithreaded jobs over single-thread jobs, regardless of priority.

But, I'd suggest arguing that it isn't your job to police what the grid schedules to run.  That's what the scheduler is for.

**Comment by skoren** [comment]
I'll also add that, at least on our version of SGE, you can use wildcards in the hostname requesting so you could also do ```gridOptions="-l hostname compute5*" would run on any nodes named compute5 like 51, 52, etc but ideally this would be handled through the grid engine itself (using priority/queues)

**Comment by tbawin** [comment]
Thanks for your suggestions!

Just to say that `gridOptions="-tc N"` doesn't work for me, but `gridEngineArrayOption="-t ARRAY_JOBS -tc N"` like issue #418 does.
