### ISSUE TITLE
Viewing HTML/PNG Summary Files

### ISSUE THREAD

**Issue by cement-head** [marbl/canu#626]
Apologies if this has already been answered, but viewing of the HTML output summary files (and the associated PNGs) is complete distorted (fonts are too large).  Is there a better viewer than FF and/or Chrome?  Thanks

**Comment by brianwalenz** [comment]
Those were an experiment that never really took off.  They're not maintained anymore.  I've been putting most of the same (excluding the png images) into the *.report file in the assembly directory.  Always happy to get suggestions for what could go in here.

**Comment by brianwalenz** [comment]
I'm probably going to get rid of the HTML reports in the future.  Comments accepted on issue #637.
