### ISSUE TITLE
Divide by zero error in CorrectReads.pm line 196

### ISSUE THREAD

**Issue by d-yarmosh** [marbl/canu#627]
Forgive me if I have misread other issues about this. I tried https://github.com/marbl/canu/issues/607, but I'm not sure it was exactly addressed.

The error looks like:
-- Filtered list of reads found in 'correction/2-correction/ONT_canu_test.readsToCorrect'.
Illegal division by zero at /home/src/canu/Linux-amd64/bin/lib/canu/CorrectReads.pm line 196.

Command is so:
canu -useGrid=false -d canu_results/ -p ONT_canu_test genomeSize=4.4m -nanopore-raw minIon.fastq maxThreads=4

-- Canu snapshot v1.6 +40 changes (r8452 1b39d4a00d42b376ec690f3129552e2f38b7ee65)

This is on a CentOS machine.

Clearly, the $numOlaps variable isn't changing from 0, hence the error. The issue I linked to above suggested a newer version with a commit that addressed this. I looked at the commit and it is correctly present in my file.

Thoughts? Am I missing something obvious?

**Comment by brianwalenz** [comment]
Thanks for reporting.  This is a known flaw, but I didn't know it was crashing.  It's trying to estimate memory requirements for read correction, but (incorrectly) picks a read with no overlaps.

For now, set this manually with corMemory=12g - that's probably more than it needs, but should be safe for longer nanopore reads.

I'll update when it gets fixed properly.

**Comment by d-yarmosh** [comment]
Hi Brian,

I didn't realize this was a memory issue or I'd have given that a shot.

Thanks for the quick response! I'm trying this now.

**Comment by skoren** [comment]
We're making some rather large changes in the correction step for the next release so there's been a lot of changes in the code that may have not all been tested yet. I'd suggest backing up to the 1.6 release to be safest. I'll close this and track on the projects page which has a list of features and issues for the next release.

**Comment by brianwalenz** [comment]
Hi David-

I've committed the 'large changes' to correction.  If you have time to test the github tip, I'd appreciate hearing about it.  Just rerunning whatever you were assembling above would be useful feedback.
