### ISSUE TITLE
Parallel ovsMethod without grid

### ISSUE THREAD

**Issue by Tierhon** [marbl/canu#630]
Hi Brian,
while we have a grid (SLURM) I don't know how to set it up so that canu can submit jobs to it. I don't think I'm allowed to do it. I rather get one big ass node and run most of the steps there, while sometimes running stuff such as overlaps and consensus in parallel by my own job submitting scripts. With some of the latest changes it seems that I can't run overlap store sorting etc., without setting up submissions to the grid. I would like to run this in parallel on one node. Is this possible anymore? Which options should I use then? I suspect this is possible, I just haven't found the right combination of options. useGrid=true or useGrid=remote don't work, and useGrid=false requires ovsMethod=sequential.

Thank you.

Ole

**Comment by brianwalenz** [comment]
I disabled this (issue #580) for sequential for three reasons:
1) early testing (back when this was in CA) indicated the parallel method was slower with only one network connection.
2) if you're running on one machine, there is a good chance that there isn't a high performance file system in use, and the massive amount of parallel I/O done by the parallel method just thrashes smaller disk systems.
3) it's easy to run out of open files - an OS limit

You can disable this check with a trivial code change.  The change is listed near the bottom of #580.

For Slurm, the only thing I can think of that would prevent it from working is if jobs can not be submitted from compute nodes.

**Comment by Tierhon** [comment]
Great, thank you Brian. 

I'll see if I can run it parallel. Sequential had used 3 days and I got a bit inpatient. 

Ole

**Comment by brianwalenz** [comment]
I added ovsMethod=forceparallel to force the parallel algorithm when Canu doesn't want to use it.
