### ISSUE TITLE
Retry ovlStore steps after failure

### ISSUE THREAD

**Issue by bredeson** [marbl/canu#633]
Hey Canu devs,

Thank you for the powerfully- and flexibly-written software! Canu is a big improvement over CA in terms of ease of running on a grid, I very much appreciate this.

I'm using Canu 1.6 to assemble three large genomes of roughly 30X PacBio depth, and I'm running into issues with restarting Canu after various stages fail; two of my ~3Gb genomes time out (12hrs) in `correction/2-correction` while generating correction layouts; Another (smaller, 750Mb) genome core dumps (logs report canu is requesting 2.5G of mem, 1 core) at ovlStore in `unitigging/3-overlapErrorAdjustment` while trying to apply the overlap error adjustements to the overlap store. When I try re-submitting Canu to the grid, Canu skips the failed step and attempts to proceed to the next step, leading to another failure. 

What is the best approach to re-running the failed commands and getting to the next Canu checkpoint (where Canu will recognize the stage as successful)? Overlaps (and their error adjustments) are computationally expensive for these large genomes and I'd like to avoid having to re-run the stage from the very beginning if possible (I'd like to not have to delete the `2-correction` dir and restart, for example). Is there a way to run just these long-running, single-process stages locally?

Thank you so much for your help.

My commands:
```
canu gridEngine=sge \
  gridEngineThreadsOption="-pe pe_slots THREADS" \
  gridEngineMemoryOption="-l h_vmem=MEMORY" \
  -p Mes -d Mes-pacbio genomeSize=750m \
  java=/full/path/to/java \
  -pacbio-raw  subreads.3kb.fasta

canu gridEngine=sge \
  gridEngineThreadsOption="-pe pe_slots THREADS" \
  gridEngineMemoryOption="-l h_vmem=MEMORY" \
  -p Xla -d Xla-pacbio genomeSize=3.1g \
  java=/full/path/to/java \
  -pacbio-raw ./subreads.3kb.fasta.gz

canu gridEngine=sge \
  gridEngineThreadsOption="-pe pe_slots THREADS" \
  gridEngineMemoryOption="-l h_vmem=MEMORY" \
  -p Xbo -d Xbo-pacbio genomeSize=2.9g \
  java=/full/path/to/java \
  -pacbio-raw ./subreads.3kb.fasta.gz
```

**Comment by brianwalenz** [comment]
That's the correct way to start a bug report / help request!

All of the steps that run on the grid can be run 'manually' by giving them their job number on the command line:  ./oea.sh 43 will run the 43 job of overlap error adjustment.  The scripts are save to run if the output exists; they will check for the output and report 'job completed successfully' and exiting if it is found.

If it did skip to the next stage, you might need to clean up stray files.  I can be more specific if logs on the restart failures are posted.

Do both of these - correction and overlap error adjustment - skip to the next stage?  It shouldn't be doing that, but I'll admit it's not well tested.

**Comment by bredeson** [comment]
Hey @brianwalenz,

I read through the source and saw that there should have been a `prefix.ovlStore.WORKING` directory if the pipeline did error, but there was none (suggesting that the stage in fact finished). I was eventually able to successfully restart from that stage. Hm, I think this issue stemmed partly from my lack of understanding on how Canu is tracking its progress at certain stages. Thanks for your help and sorry for the noise!
