### ISSUE TITLE
Illegal division by zero/CorrectReads.pm: [..] of length 141093 with 0 overlaps covering 0 bases

### ISSUE THREAD

**Issue by sklages** [marbl/canu#636]
Hi,

just a tiny thing.

I am currently playing around with 25x bird genome data. I used default error values.

Canu: `1.6.r8452`.

Assembly crashed due to:
```
Based on read 3291687 of length 141093 with 0 overlaps covering 0 bases, expecting to use 1790738768 bytes, 1.668 GB memory usage
```
with
```
Illegal division by zero at /package/sequencer/path/to/1.6.r8452/lib/canu/CorrectReads.pm line 196.
```
because `lib/canu/CorrectReads.pm` doesn't catch a by-zero division on line ~196.

I increased `correctedErrorRate` to 9%, hoping to circumvent the above error.

But nevertheless, `$numOlaps` should be verified :-)

best,
Sven

**Comment by brianwalenz** [comment]
Hi, Sven.

Thanks.  A better work around is to set corMemory=12g (or so).  It's failing to estimate the size of each of the correctReads jobs, so setting it explicitly avoids the problem.

This section is in the middle of a big rewrite.  With a bit of luck, I should be able to get something out for testing today.

**Comment by sklages** [comment]
Thanks for the hint, Brian :-)
I have re-started my assembly with both parameters changed ..

**Comment by brianwalenz** [comment]
And it's out for testing.  25x of bird is a bit large, but if you have some smaller data sets, I'd appreciate hearing how they work with the tip.

Closing the issue, because the offending code doesn't exist anymore.  Bug eradication!

**Comment by mastermindchr** [comment]
> Thanks for the hint, Brian :-)
> I have re-started my assembly with both parameters changed ..

could you please show how you changed the parameters and it worked for you?
Thanks!
