### ISSUE TITLE
Remove HTML reports in favor of asm.report

### ISSUE THREAD

**Issue by brianwalenz** [marbl/canu#637]
Submitted for user feedback.

I'd like to remove the html reports.  They're ugly, out of date, and painful to maintain.  The asm.report in the assembly directory includes all the info (and more) already.  The only significant loss would be an easy way to view the handful of png plots, but, those plots aren't terribly informative; **I** don't even look at them.

So, what brilliant ideas do **you** have for reporting "stuff" about the assembly process?

**Comment by gringer** [comment]
I also don't find the html reports useful. I'm much more comfortable with text.

Estimated time at completion would be great (the current step, as well as the entire assembly process). I've had to guess at that quite a few times when talking to others and when planning my work; an official Canu value would help in this regard.

**Comment by skoren** [comment]
No one objected so the html reports were removed. Closing.
