### ISSUE TITLE
Illegal division by zero at /Linux-amd64/bin/lib/canu/CorrectReads.pm line 196

### ISSUE THREAD

**Issue by agroppi** [marbl/canu#638]
Hi,

With Canu 1.6 : 

`Canu snapshot v1.6 +44 changes (r8456 28ecea57ccd60ad551fb807e7983c32fb02807df`

I'm facing this error : 

`Illegal division by zero at /Linux-amd64/bin/lib/canu/CorrectReads.pm line 196`

I'm working on a cluster node (20 CPUs and 252 gigabytes of memory) with CentOS 7.2)

My commande (in a bash script) :

`canu useGrid=false -p Sibirica_3kb -d $SLURM_SUBMIT_DIR/Sibirica_Canu_1.6_fasta_3kb corMhapSensitivity=normal corOutCoverage=54 genomeSize=270m -pacbio-raw $SLURM_SUBMIT_DIR/Sibirica_fasta_3kb/*.fasta`

Here attached the ouput/error log

[Canu_1.6_out.zip](https://github.com/marbl/canu/files/1313480/Canu_1.6_out.zip)

Thanks for your help

**Comment by brianwalenz** [comment]
A workaround is to set corMemory=12g (or so).  See issues #627 and #636 for more.

Leaving open since lots of people are hitting this.
