### ISSUE TITLE
Abort trimming process

### ISSUE THREAD

**Issue by SashaMeow** [marbl/canu#640]
Hello,

I am running latest version of canu on MacOS 
I try to start trim the reads.
Here is the command that I put in:
```
sudo  /var/log/MinKNOW/canu/Darwin-amd64/bin/canu -trim \
-p DB146_6_diploid \
-d /DB146_6_diploid/trim \
genomeSize=24.2m \
-nanopore-corrected /var/log/MinKNOW/canu/src/src/correction/DB146_6_diploid/DB146_6_diploid.correctedReads.fasta.gz \
gnuplotTested=true
```
and the program aborted the process with this:
```ABORT:
ABORT: Canu snapshot v1.6 +44 changes (r8456 28ecea57ccd60ad551fb807e7983c32fb02807df)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   gatekeeper store exists, but contains no reads.
```
I tried to restart the process, but it didn't help. 

What to do, and how to start the trimming process? 

Thank you,
Aleksandra

**Comment by skoren** [comment]
What is the output from Canu up to that point? Did it run through correction and end up with no corrected reads or is this the first thing it outputs? There have been lots of code changes in the tip which isn't always stable so I would suggest using the release code instead of tip (download the 1.6 release) and trying that instead.

**Comment by SashaMeow** [comment]
Yes, I ran these reads through the correction, and I got corrected reads, so they definitely exist.
I'll try the released version of canu, and follow up with the feedback. 


Here is full output

```
-- Canu snapshot v1.6 +44 changes (r8456 28ecea57ccd60ad551fb807e7983c32fb02807df)
--
-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
-- 
-- Read and contig alignments during correction, consensus and GFA building use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
--   Li H.
--   Minimap and miniasm: fast mapping and de novo assembly for noisy long sequences.
--   Bioinformatics. 2016 Jul 15;32(14):2103-10.
--   http://doi.org/10.1093/bioinformatics/btw152
-- 
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_51' (from 'java').
-- Detected 24 CPUs and 64 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |  algorithm
--        -------  ------  --------   --------  -----------------------------
-- Local: meryl      8 GB    4 CPUs x   6 jobs  (k-mer counting)
-- Local: cormhap    6 GB   12 CPUs x   2 jobs  (overlap detection with mhap)
-- Local: obtovl     8 GB    8 CPUs x   3 jobs  (overlap detection)
-- Local: utgovl     8 GB    8 CPUs x   3 jobs  (overlap detection)
-- Local: ovb        2 GB    1 CPU  x  24 jobs  (overlap store bucketizer)
-- Local: ovs        8 GB    1 CPU  x  24 jobs  (overlap store sorting)
-- Local: red        2 GB    4 CPUs x   6 jobs  (read error detection)
-- Local: oea        1 GB    1 CPU  x  24 jobs  (overlap error adjustment)
-- Local: bat       10 GB    4 CPUs x   6 jobs  (contig construction)
-- Local: cns       10 GB    4 CPUs x   6 jobs  (consensus)
-- Local: gfa        8 GB    4 CPUs x   6 jobs  (GFA alignment and processing)
--
-- Found Nanopore corrected reads in the input files.
--
-- Generating assembly 'DB146_6_diploid' in '/DB146_6_diploid/trim'
--
-- Parameters:
--
--  genomeSize        24200000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1440 ( 14.40%)
--    utgOvlErrorRate 0.1440 ( 14.40%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1440 ( 14.40%)
--    utgErrorRate    0.1440 ( 14.40%)
--    cnsErrorRate    0.1920 ( 19.20%)
--
--
-- BEGIN TRIMMING
--

ABORT:
ABORT: Canu snapshot v1.6 +44 changes (r8456 28ecea57ccd60ad551fb807e7983c32fb02807df)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   gatekeeper store exists, but contains no reads.
ABORT:
```

**Comment by skoren** [comment]
That output doesn't show the correction. Did you run them as separate steps? Do you have the output from the correction run?

**Comment by SashaMeow** [comment]
I was running correction separately from trim process. So I have just the .report file that generated during the correction process. 
[DB146_6_diploid.txt](https://github.com/marbl/canu/files/1322233/DB146_6_diploid.txt)

**Comment by brianwalenz** [comment]
Remove the trim/ directory and restart canu again, saving the log output to a file `canu ..... > canu.log 2>&1`.  Corrected reads could all be very small and discarded, or there could have been a crash.  Either way, it should be reported in canu.log.

When it finishes, check the trim/trimming/ directory for error files, there should only be a few files in there, so just see what's in all of them.

**Comment by SashaMeow** [comment]
I installed canu 1.6 (released) and I ran the trim process through it. 
Trim process still didn't go through; however, the error is different now -- it says "-- Meryl failed, tried 2 times, giving up.. 
Here is the .log file 
[canu.log.txt](https://github.com/marbl/canu/files/1322307/canu.log.txt)

**Comment by brianwalenz** [comment]
I wanted to see the gatekeeper report, and histogram of read lengths, but it seems to have passed that stage fine now.

What's the error in trimming/0-mercounts/meryl.*.out?

What happens if you run `meryl.sh 1` from that directory?  Remove any files with mcidx or mcdat in the name first.

**Comment by SashaMeow** [comment]
So canu 1.6 is running trimming with other set of data that I have, and it seems to run just fine. 
So I suspect that there is something wrong with this particular data. I removed all of the old files, and  I am rerunning correction process for it [failing data] now.

**Comment by brianwalenz** [comment]
The only known cause of 'gatekeeper store exists, but contains no reads' is when all reads are removed during correction or trimming.  By default, if they're shorter than 1000 bp, they're discarded.  Both the gatekeeper logging from canu and the various gkpStore output/log files would show this.

**Comment by SashaMeow** [comment]
Make sense..
Okay maybe something happened to those reads. I hope that regenerating would resolve the issue. 

Thank you for your help!

**Comment by skoren** [comment]
I assume this was resolved since the issue has been inactive for a couple of weeks. Open a new issue if the regenerated reads cause an issue.
