### ISSUE TITLE
canu trimming aborted with no specific error.

### ISSUE THREAD

**Issue by mortunco** [marbl/canu#642]
Hi,

Before I introduce my problems I have seen #640  which is very similar to my problem but we have different operating system and I did not want to post this huge thread on that post.

My canu run got aborted in the trimming section without specifying any problems and neither of my restarts solved the problem. Simply we would like to use canu to generate an assembly for a mammalian sample. Samples were sequenced with pacbio as you can see from the command line options.

I would be more than happy if you could help me out with this problem.

```
tmorova@lisa:~$ canu-1.6/Linux-amd64/bin/canu --version
Canu 1.6
```

```
tmorova@lisa:~$ canu-1.6/Linux-amd64/bin/canu 
-p kefal 
-d kefal_genome/ 
genomeSize=555g 
-pacbio-raw kefal_pacbio/pacbio/*/*/*.fastq 
```

and process gets aborted like this

```
--   job trimming/1-overlapper/001/000380.ovb FAILED.
--   job trimming/1-overlapper/001/000381.ovb FAILED.
--   job trimming/1-overlapper/001/000382.ovb FAILED.
--   job trimming/1-overlapper/001/000383.ovb FAILED.
--   job trimming/1-overlapper/001/000384.ovb FAILED.
--   job trimming/1-overlapper/001/000385.ovb FAILED.
--   job trimming/1-overlapper/001/000386.ovb FAILED.
--   job trimming/1-overlapper/001/000387.ovb FAILED.
--   job trimming/1-overlapper/001/000388.ovb FAILED.
--   job trimming/1-overlapper/001/000389.ovb FAILED.
--   job trimming/1-overlapper/001/000390.ovb FAILED.
--   job trimming/1-overlapper/001/000391.ovb FAILED.
--   job trimming/1-overlapper/001/000392.ovb FAILED.
--

ABORT:
ABORT: Canu 1.6
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```

Also I am not sure if this helps but when I check one of the 1-overlapper outputs i have seen this.

```
tmorova@lisa:~/kefal_genome/trimming/1-overlapper$ cat overlap.000001.out
Running job 1 based on command line options.
./overlap.sh: 2413: ./overlap.sh: /mnt/compgen/inhouse/src/canu/canu-1.6/Linux-amd64/bin/overlapInCore: Input/output error

```

Thank you very much,

Tunc.

**Comment by skoren** [comment]
Input/output error would seem to indicate I/O or disk issue (the job tried to write but couldn't) so I don't think this is Canu specific but a system issue. It could also be an out of space/quota issue as well. 

Is that one of the failed jobs, do the ones which are reported failed report any other errors. Canu should retry the jobs at least once before giving up but if it did not you could re-run the same command you ran before and it will try to re-run only the failed jobs again.

**Comment by mortunco** [comment]
Thank you for your fast response. If running the same command couple times can be counted as re-running. I have run like ~ 10 before. All the previous steps seems ok and it was marked checked in stdout and my run only failed at trimming step.

Let me check the quota and free space in our disc.

Best,

Tunc.

**Comment by brianwalenz** [comment]
It seems to be failing to read/load the overlapInCore binary, hinting some transient file system issue.  Can you run that by hand (no options needed, it'll just print out usage)?  If not rebuilding/reinstalling should fix it.  But you should monitor your disks for problems.

**Comment by mortunco** [comment]
I deleted everything and started a fresh run. It went smoothly. Our servers crushed couple ours before I got that error. I think this is the cause.
