### ISSUE TITLE
Contig sequence in contigs.gfa

### ISSUE THREAD

**Issue by Stan-Derksen** [marbl/canu#643]
Hi,

Would it be possible to write the actual contig sequence to the GFA files instead of *?
example line:
S	tig00000004	*	LN:i:33993 
I'm trying to analyze an assembly with Bandage and having the sequences in there would be very useful.

Regards,
Stan

**Comment by skoren** [comment]
We could probably do that relatively easily. We already need the sequences to compute the cigar string and this could make the GFA more self-contained. I believe Bandage does support loading sequences for a Canu assembly if the asm.contigs.fasta file is in the same folder (I know it was in a pre-release build so I'm not sure if it has been incorporated).

I'm going to close this and track along with other GFA issues for the a future release.
