### ISSUE TITLE
Recommended bam -> fastq conversion for Sequel data

### ISSUE THREAD

**Issue by jgarbe256** [marbl/canu#644]
To use Canu on Sequel data the raw BAM formatted data must first be converted to fastq format, however there are several different ways to do the conversion. It would be helpful to clarify in the Canu documentation which conversion method is recommended.
For example, the raw subreads.bam file generated by a Sequel run can be converted directly to a fastq file with no processing, resulting in a fastq file where each read contains one or more subreads  along with adapter sequences. Alternatively, a fastq file can be generated using the Circular Consensus Sequence (CCS) tool from the SMRT Portal software. The default CCS parameters generate a fastq file containing only high-quality sequences generated from at least 3 subreads, which effectively filters out the longest reads. The parameters can be modified to include longer sequences with the downside of including low-quality sequences. 
Any tips you could share on this topic?

**Comment by skoren** [comment]
We typically use the bam2fastq dump to get all the reads. The CCS tool will only work if you are sequencing relatively short molecules with long reads (that is your subreads are 2k but your read length is 10k). Typically, for assembly you want read length over quality so you should try to get 10k molecules which won't have enough data for CCS to do anything with.

**Comment by bmlett** [comment]
Hi, 

I am trying to figure out the best way to convert the subreads.bam files from pacbio into the fastq format for canu. In a previous post you mentioned using `bam2fastq -c 9`. I've tried finding this command and in the documentation I am not finding -c option and that bam2fastq itself is no longer supported by GSL. I've found a pacbio I was wondering if you knew of a different way to changes from bam to fastq/fasta. 

Any recommendations would be greatly appreciated. Thanks.

**Comment by skoren** [comment]
The bam2fastq tool is part of smrtanalysis (at least as of v6.0), it still supports -c:
```
% which bam2fastq
smrtanalysis/6.0.0.47841/current/bundles/smrttools/current/smrtcmds/bin/bam2fastq
% bam2fastq -h
Usage: bam2fastq [options] INPUT
Converts multiple BAM and/or DataSet files into into gzipped FASTQ file(s).

Options:
  -h,--help          Output this help.
  --version          Output version info.
  -o,--output        Prefix of output filenames
  -c                 Gzip compression level [1-9] [1]
  -u                 Do not compress. In this case, we will not add .gz, and we ignore any -c setting.
  --split-barcodes   Split output into multiple FASTQ files, by barcode pairs.
  -p,--seqid-prefix  Prefix for sequence IDs in headers

Arguments:
  input              Input file.
```

There's also the standalone version of the tool you can use: https://github.com/PacificBiosciences/bam2fastx

**Comment by bmlett** [comment]
Thank you for the quick reply. I'd originally found a stand alone bam2fastq tool, which does not have the -c command. I will look further in to the bam2fastx. 
Thank you!
