### ISSUE TITLE
canu 1.6 is much slower than canu 1.4

### ISSUE THREAD

**Issue by frankmyou** [marbl/canu#646]
I am using canu to do flax genome assembly (~370 Mb of the genome). Initially I used canu 1.4. and then I tried the latest version of canu 1.8. I noticed canu1.6 need double even triple time to finish the assembly for the same data set. I was wondering if the new version has more accurate algorithm but needs more time to finish it.

Here is the most time consuming step:
canu1.4
```
 -- Canu v1.4 (+0 commits) r7995 7b04cd09002d6b865ca05f4a3f53edb936b5c925.
Final error rates before starting pipeline:
--
--   genomeSize          -- 370000000
--   errorRate           -- 0.015
--
--   corOvlErrorRate     -- 0.045
--   obtOvlErrorRate     -- 0.045
--   utgOvlErrorRate     -- 0.045
--
--   obtErrorRate        -- 0.045
--
--   cnsErrorRate        -- 0.045

-- Starting concurrent execution on Fri Sep  1 16:16:41 2017 with 916.85 GB free disk space (114 processes; 10 concurrently)

 ..../unitigging/1-overlapper/overlap.sh 1 > ..../unitigging/1-overlapper/overlap.000001.out 2>&1

-- Finished on Fri Sep  1 18:37:52 2017 (8471 seconds) with 914.848 GB free disk space
```
 
only ~2 hrs were used. 
```
canu1.6
-- Canu snapshot v1.6 +44 changes (r8456 28ecea57ccd60ad551fb807e7983c32fb02807df)
Parameters:
--
--  genomeSize        370000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0450 (  4.50%)

-- Starting 'utgovl' concurrent execution on Fri Sep 22 11:37:22 2017 with 10543.862 GB free disk space (114 processes; 10 concurrently)

    cd unitigging/1-overlapper
    ./overlap.sh 1 > ./overlap.000001.out 2>&1
   ./overlap.sh 87 > ./overlap.000087.out 2>&1
```
Currently Sun Sep 24 11:32:44 EDT 2017, but only start running /overlap.sh 87. 
Already 47 hrs were used for  this step.

Similar with the assembly for another two  different genomes which took ~6 days in total.

Thanks for your help.

**Comment by skoren** [comment]
First, I'll caution that your second run is using the tip not the 1.6 release which has had major changes recently and may not be stable. I would recommend using the 1.6 release instead of tip.

As for the speed, I'd start by comparing the number of corrected reads generated by both 1.4 and 1.6. If 1.6 is generating significantly more corrected reads it may be slower but would probably give a better assembly. You can also check the repeat threshold used in 1.4 and 1.6 in the ```unitigging/0-mercounts/asm.ms22.estMerThresh.err```. If the threshold in 1.4 is much lower than 1.6 that could explain the speed difference (see issue #537). You can manually set the threshold in 1.6 to match 1.4 using the ```utgOvlMerThreshold``` parameter.

**Comment by frankmyou** [comment]
Thanks for the reply. I will try stable 1.6 release and let you know the results. 

Frank M. You Ph.D

Bioinformatics, Research Scientist
Agriculture and Agri-Food Canada 
101 Route 100, Morden, Manitoba R6M 1Y5 
Frank.you@agr.gc.ca 
Tel:  204-822-7525/Cel: 204-384-0704/TTY: 613-759-7470

Bioinformatique, Chercheur Scientifique
Agriculture et Agroalimentaire Canada
101 CH 100, Morden, Manitoba R6M 1Y5 
Frank.you@agr.gc.ca 
Tél: 204-822-7525/Tél Cell: 204-384-0704/ATS: 613-759-7470




-----Original Message-----

**Comment by kevfengler227** [comment]
Hi Sergey,
I tried setting the utgOvlMerThreshold as you describe above for v1.6 using the value determined using v1.4, but the estMerThresh.err was still being computed?

KF

canu-1.6/Linux-amd64/bin/canu -assemble -p CANU -d CANU-out genomeSize=2.3g utgOvlMerThreshold=453 -pacbio-corrected preads4falcon_12k.fasta useGrid=true minReadLength=5000 minOverlapLength=5000 

RAW MER COUNTS:
  distinct:   1138330449 (different kmer sequences)
  unique:      384260863 (single-copy kmers)
  total:     46539145246 (kmers in sequences)

Set maxCount to 2460 (740 kmers), which will cover 99.75% of distinct mers and 56.77% of all mers.
Average number of kmers between count 2435 and 2486 is 1851440
Found break in kmer coverage at 132348
Set maxCount to 59429 (1 kmers), which will cover 100.00% of distinct mers and 90.00% of all mers.

**Comment by skoren** [comment]
That's correct, it will still run it but when it runs the next command to generate the list of frequent mers it will use your value. Here is an example from my recent run:
```
Set maxCount to 105 (165 kmers), which will cover 99.75% of distinct mers and 98.01% of all mers.
Average number of kmers between count 80 and 131 is 20314
Found break in kmer coverage at 744
Set maxCount to 743 (1 kmers), which will cover 100.00% of distinct mers and 99.96% of all mers.
```

but the logs also indicate
```
    cd trimming/0-mercounts
    canu-1.6/Linux-amd64/bin/meryl \
      -Dt \
      -n 200 \
      -s ./asm.ms22 \
    > ./asm.ms22.frequentMers.fasta \
    2> ./asm.ms22.frequentMers.fasta.err

```

**Comment by skoren** [comment]
Idle, and next release will have some speed improvements.
