### ISSUE TITLE
Do we need canu assembled genome to get polished using Quiver or Arrow?

### ISSUE THREAD

**Issue by amit4mchiba** [marbl/canu#647]
Hi Guys,

First of all, Thank you so much for wonderful Canu, and for helping at each step. I just got my final assembly using 75x coverage for my plant genome (genome size-380MB) my mixing RS11 and sequel datasets. I got my genome in 893 scaffolds using Canu with N50 value is 1.69MB. This is really exciting for me. The next stage is to combine BioNano data to further improve this assembly. I have now started preparing for BioNano experiment and need to decide the nickase for this. Do i need to first polish the assembly before analyzing my genome to identify correct nickase or I can just use Canu assembled genome for this purpose. 

Please advise me.

**Comment by skoren** [comment]
You can probably identify the nickase without polishing but I would would recommend polishing with Arrow and even Pilon (if you have illumina data) before running the optical map scaffolding. The assembly will likely still have indel errors which would knock out restriction sites, making the optical map mapping harder. Depending on the coverage you could use just the Sequel data for arrow or combine Sequel + RS (as long as it is P6-C4 chem).

**Comment by chenyufanxin** [comment]
Hello, I want to polish canu assembly with arrow. I install SmrtAnalysis v2.3 in my computer but can't find arrow in GenomicConsensus. What should I do to get arrow? I am an undergraduate now and I'll appreciate your help.

**Comment by skoren** [comment]
Take a look at: https://github.com/PacificBiosciences/GenomicConsensus/blob/master/doc/FAQ.rst and https://github.com/PacificBiosciences/GenomicConsensus/blob/master/doc/HowTo.rst. Arrow is newer than quiver and was added to the 3+ version of SMRT analysis software. You can download the latest versions from PacBio: http://www.pacb.com/support/software-downloads/.

You can follow the FAQ and the documentation to run Arrow or contact PacBio. We have also been using slurm/sge wrapper than runs Arrow assuming you have SMRT software properly installed and in your path that is available on github here: https://github.com/skoren/ArrowGrid

**Comment by chenyufanxin** [comment]
Thanks for your reply. But I did't find 3+version of SMRT analysis software on the Pacbio website. What I can find is SMRT Link v5.0.1, is SMRT analysis bundled with SMRT Link now?

**Comment by skoren** [comment]
Yes, that is what you want.
