### ISSUE TITLE
canu, bogart failed (new to git hub too!)

### ISSUE THREAD

**Issue by TonyMane** [marbl/canu#648]
Greetings, here is the command I am trying:

```
./canu/Linux-amd64/bin/canu -assemble -d ./OUT_3/ -p OUT_3 genomeSize=2.5m -pacbio-corrected OUT.trimmedReads.fasta.gz gnuplotTested=true
```

> this starts running, but consistently leaves an error message:

```-- Finished on Tue Sep 26 12:48:45 2017 (lickety-split) with 785.954 GB free disk space
----------------------------------------
--
-- Bogart failed, tried 2 times, giving up.
--

ABORT:
ABORT: Canu snapshot v1.6 +61 changes (r8473 86f53cff1401ce4229d2a579ed093afe68751e0a)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```

> I moved into the canu directory directory and did 'git pull' as suggested by a user with a similar problem.

**Comment by skoren** [comment]
Were the trimmed reads generated by the same version of Canu or a previous release? I recommend using the release (code or binary) rather than doing a git pull because the tip may not be stable (and hasn't had any bogart fixes recently).

```What is the output in unitigging/4-unitigger/unitigger.err```

**Comment by TonyMane** [comment]
Yes, the trimmed reads were generated using 
`./Linux-amd64/bin/canu -d OUT_2/ -p OUT_2 genomeSize=2m -pacbio-corrected /home/anthony/Downloads/canu/OUT/OUT.trimmedReads.fasta.gz gnuplotTested=true`

`
==> PARAMETERS.

Resources:
  Memory                7 GB
  Compute Threads       4 (command line)

Lengths:
  Minimum read          0 bases
  Minimum overlap       500 bases

Overlap Error Rates:
  Graph                 0.045 (4.500%)
  Max                   0.045 (4.500%)

Deviations:
  Graph                 6.000
  Bubble                6.000
  Repeat                3.000

Edge Confusion:
  Absolute              2100
  Percent               200.0000

Unitig Construction:
  Minimum intersection  500 bases
  Maxiumum placements   2 positions

Debugging Enabled:
  (none)

==> LOADING AND FILTERING OVERLAPS.

ReadInfo()-- Using 1416315 reads, no minimum read length used.

OverlapCache()-- limited to 7168MB memory (user supplied).

OverlapCache()--      10MB for read data.
OverlapCache()--      54MB for best edges.
OverlapCache()--     140MB for tigs.
OverlapCache()--      37MB for tigs - read layouts.
OverlapCache()--      54MB for tigs - error profiles.
OverlapCache()--    1792MB for tigs - error profile overlaps.
OverlapCache()--       0MB for other processes.
OverlapCache()-- ---------
OverlapCache()--    2116MB for data structures (sum of above).
OverlapCache()-- ---------
OverlapCache()--      27MB for overlap store structure.
OverlapCache()--    5024MB for overlap data.
OverlapCache()-- ---------
OverlapCache()--    7168MB allowed.
OverlapCache()--
OverlapCache()-- Retain at least 3136 overlaps/read, based on 1568.27x coverage.
OverlapCache()-- Initial guess at 232 overlaps/read.
OverlapCache()--
OverlapCache()-- Not enough memory to load the minimum number of overlaps; increase -M.`

I suppose this is a memory issue. I'll retry by modifying -M.

**Comment by skoren** [comment]
Is that coverage accurate (1500x)? That is why it is having a memory issues, are you assembling a metagenome or amplicons? You can probably downsample the reads to 40x unless it's a metagenome.

**Comment by TonyMane** [comment]
This is a metagenome. Yes, this was my mistake. But initially we used the raw pacbio data, with the default 'canu' command. Everything works up until the assembly.

**Comment by skoren** [comment]
Take a look at issue #634 for parameters I suggested to another user.

**Comment by TonyMane** [comment]
Greetings, we have been trying to run canu on a using PBS server. I tried running through the tutorial with ecoli, but am getting an error saying "qsub: submit error (No default queue specified MSG=requested queue not found)". I have attached the pbs script used, the pbs output log file, and the output of meryl.jobSubmit-01.out. Any help is useful.
