### ISSUE TITLE
Clarification of adjuments of correctedErrorRate

### ISSUE THREAD

**Issue by cement-head** [marbl/canu#649]
Hello,

  Had a question regarding adjustment of the **correctedErrorRate** parameter.  For lower coverage datasets, the recommendation is to adjust the **correctedErrorRate** from 0.144 for Nanopore by 10%.  

Yet in the quick start example for low coverage (20x), the low coverage assembly is set at 0.075 from default of 0.045 (PacBio Reads).

I'm confused.  Wouldn't increasing the **correctedErrorRate** by 10% make the rate go from 0.045 to 0.0495?

More specifically, if one wished to increase the **correctedErrorRate** for Nanopore reads by 10% from the default of 0.144, what would that number be?

Thanks,
Andor

**Comment by skoren** [comment]
Does the documentation say by 10%? It should be 1% absolute not a percentage of the value, like it says here:
http://canu.readthedocs.io/en/latest/parameter-reference.html#correctederrorrate

The quick-start example is increasing it by 3% which is probably excessive and could be decreased to 0.055. For nanopore 0.15 or 0.16 should be enough.

**Comment by cement-head** [comment]
Whoops!,  Yep, sorry 1%.

I don't understand what you mean by "1% absolute not a percentage of the value"?  Also, what is "a fraction error" and how is that calculated?

**Comment by cement-head** [comment]
Are you saying 0.144 is actually 14.4%?

**Comment by skoren** [comment]
Yes, 0.144 is 14.4% and 0.045 = 4.5%. So increasing it by 1% means adding 0.01 to the value.

**Comment by cement-head** [comment]
Okay, got it - thanks!
