### ISSUE TITLE
falcon_sense taking too long time

### ISSUE THREAD

**Issue by kk86bioinfo** [marbl/canu#65]
Hi, would like to ask is falcon_sense (2-correction step) load time directly proportional with input reads amount? We have noticed that when we increase our input reads to canu, the time taken by falcon_sense seems taking much longer time (far more time needed compare to lesser input reads). In SGE, all process are still in 'r' stage but the file modified timestamp is no longer updated. Is there any way to check if there is any error occur? or it is just need longer time? Please advise.

**Comment by kk86bioinfo** [comment]
![screen shot 2016-03-05 at 4 36 49 am](https://cloud.githubusercontent.com/assets/2483401/13539525/eabfaae6-e28b-11e5-9b68-87e1ae8a43e5.png)

![screen shot 2016-03-05 at 4 36 31 am](https://cloud.githubusercontent.com/assets/2483401/13539531/f2461c6e-e28b-11e5-89c5-635d1816d135.png)

**Comment by kk86bioinfo** [comment]
`cat 0001.err`

![screen shot 2016-03-05 at 4 38 28 am](https://cloud.githubusercontent.com/assets/2483401/13539568/2cf525bc-e28c-11e5-81f4-fd49548a44a5.png)

**Comment by pb-jchin** [comment]
In FACLON, the initial overlap module can generate too many false overlaps (caused by repeats) which make the falcon_sense slow.  We add some logic to limit the overlap output. I am not sure how MHAP/Canu handle the repeat cases. Just some thing that might be worth to check.

**Comment by skoren** [comment]
There's up-front filters before reads are sent to falcon_sense in Canu to at most 2*coverage along with a global filter. Falcon_sense in the version you're running is also limited to using at most 200 reads for a correction. So as you add data, it is possible you would slow down falcon_sense if you start lower than 2*coverage initially so no filtering is done.

One other note is that this version of falcon_sense is threaded per-read so if the piped input can't output fast enough, even though you have 8 cores dedicated, most of them will site idle waiting for a read to call consensus. You can log into one of your machines and see what the % cpu is being utilized. I've seen on slower NFS filesystems the pipe input can become the bottleneck.

Lastly, check your input for non-ACGT characters. There was a bug (issue #41) where falcon_sense would hang while showing CPU usage with Ns in the reads. If you really have no output being written for a while this could be the cause and you'd have to pre-process your data to remove any invalid characters.

**Comment by kk86bioinfo** [comment]
@skoren  great advice, I think the newly added reads may have N in it (we actually just having some experimental run on canu trying to improve our assembly). I will try the pre-processing way to see if it is improving the run time (at least can monitor file modified timestamp get updated to relief my worry on the hang)

**Comment by rafalwoycicki** [comment]
Hi, I am not sure if it will help, but I also had issues with falcon_sense running very slow and not using all threads when using defaults. For example in 6 jobs/4 threads setting each job was using just 1.5 thread. In 3/6 setting it was 2 threads per job (I have 24 thread single machine). The most optimal setting for me is with having 24 jobs each with 1 thread, then it uses 1 thread per job.

**Comment by kk86bioinfo** [comment]
@skoren 's suggestion is working. Now I proceed toward bogart (unitigger) step. But I now another issue with bogart that used 64 threads but all nodes in my SGE has only 48 CPU. Is it means that I cannot finish canu assembly with my computing setup?

**Comment by kk86bioinfo** [comment]
![screen shot 2016-03-09 at 5 09 13 am](https://cloud.githubusercontent.com/assets/2483401/13616529/360a0f42-e5b5-11e5-8031-7cd536d03866.png)


![screen shot 2016-03-09 at 5 09 38 am](https://cloud.githubusercontent.com/assets/2483401/13616546/4198849c-e5b5-11e5-92f2-cece06f2dfef.png)

**Comment by brianwalenz** [comment]
Do you have the configuration output that canu reports at the start of its execution?

You can limit bogart to 48 cores with batThreads=1-48, but if the 'mpi' parallel environment is really for mpi, this is wrong.  What does 'qconf -sp mpi' report?

**Comment by kk86bioinfo** [comment]
![screen shot 2016-03-09 at 5 20 10 am](https://cloud.githubusercontent.com/assets/2483401/13616842/9feed9b4-e5b6-11e5-9eb8-7fb0241baf0d.png)


Ya, I just found batThreads option in documentation, now it resume with 48 cores!

**Comment by brianwalenz** [comment]
Great!

That config is proper for a multithreaded job, so canu is OK.  Running actual MPI jobs on it might not work so great.

I'm still curious why canu picked 64 cores.  Do you have a 64+ core host that is disabled?

**Comment by kk86bioinfo** [comment]
No, maximum cpu is only 48 cores, memory 125GB. I also feel like weird with it initially, but after check a few in the source code it seems Canu determine the setting based on several cutoff of run parameters, maybe because my genome size is large, that it assigned more cores.

**Comment by kk86bioinfo** [comment]
I will close this issue for now. The run is completed with consensus.fasta. Now is another nightmare time to analyze the assembly. To be clear for future reference, I solve the slow of canu by replacing all 'N' in my input reads to 'A'. The hanging issue of falcon_sense need to be investigated with.

**Comment by brianwalenz** [comment]
They should all be limited by whatever is in your grid.  Can you supply the output of 'qhost'?  I'll try (sometime) to debug it.

**Comment by kk86bioinfo** [comment]
```
HOSTNAME                ARCH         NCPU  LOAD  MEMTOT  MEMUSE  SWAPTO  SWAPUS
-------------------------------------------------------------------------------
global                  -               -     -       -       -       -       -
uc-sge10-1              lx26-amd64     48  1.23  125.7G    1.5G     0.0     0.0
uc-sge10-2              lx26-amd64     48  1.18  125.7G    1.6G     0.0     0.0
uc-sge10-3              lx26-amd64     48  1.10  125.7G    1.5G     0.0     0.0
uc-sge10-4              lx26-amd64     48  1.12  125.7G    1.6G     0.0     0.0
uc-sge9-2               lx26-amd64     48  1.22  125.7G    1.6G     0.0     0.0
uc-sge9-3               lx26-amd64     48  1.11  125.7G    1.5G     0.0     0.0
uc-sge9-4               lx26-amd64     48  1.09  125.7G    1.5G     0.0     0.0
uc-sge9-5               lx26-amd64     48  1.18  125.7G    1.6G     0.0     0.0
```

**Comment by kk86bioinfo** [comment]
```
-- Detected 48 CPUs and 126 gigabytes of memory.
-- Detected Java(TM) Runtime Environment '1.8.0_74' (from 'java').
-- Detected Sun Grid Engine in '/var/lib/gridengine/default'.
-- User supplied Grid Engine environment 'mpi THREADS'.
-- User supplied Grid Engine consumable 'mem_free'.
--
-- Found   8 hosts with  48 cores and  125 GB memory under Sun Grid Engine control.
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
maxMemory 1048576 maxThreads 1024
--
-- Allowed to run under grid control, and use up to  48 compute threads and 1024 GB memory for stage 'bogart (unitigger)'.
-- Allowed to run under grid control, and use up to  16 compute threads and   41 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run under grid control, and use up to  16 compute threads and   41 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run under grid control, and use up to  16 compute threads and   41 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run under grid control, and use up to   8 compute threads and   20 GB memory for stage 'read error detection (overlap error adjustment)'.
-- Allowed to run under grid control, and use up to   1 compute thread  and    2 GB memory for stage 'overlap error adjustment'.
-- Allowed to run under grid control, and use up to   8 compute threads and   20 GB memory for stage 'utgcns (consensus'.
-- Allowed to run under grid control, and use up to   1 compute thread  and    8 GB memory for stage 'overlap store sequential building'.
-- Allowed to run under grid control, and use up to   1 compute thread  and    2 GB memory for stage 'overlap store parallel bucketizer'.
-- Allowed to run under grid control, and use up to   1 compute thread  and    8 GB memory for stage 'overlap store parallel sorting'.
-- Allowed to run under grid control, and use up to   1 compute thread  and    2 GB memory for stage 'overlapper'.
-- Allowed to run under grid control, and use up to   8 compute threads and   16 GB memory for stage 'overlapper'.
-- Allowed to run under grid control, and use up to   8 compute threads and   16 GB memory for stage 'overlapper'.
-- Allowed to run under grid control, and use up to  32 compute threads and  125 GB memory for stage 'meryl (k-mer counting)'.

```

**Comment by kk86bioinfo** [comment]
I think `gridEngineThreadsOption="-pe mpi THREADS"` maybe the problem, I never set any environment value with THREADS.

**Comment by brianwalenz** [comment]
That's not an environment variable.  It's just a token for canu to replace with the number of threads it is requesting.

Those logs were a big hint - bogart should not be using 64 cores.  Hopefully easy to fix!
