### ISSUE TITLE
Canu fails to read grid memory

### ISSUE THREAD

**Issue by ANekhai** [marbl/canu#651]
Hey, I'm running Canu on a Slurm grid and it fails to do anything because it says there's not enough memory. Here are the commands I'm running:
```
canu -assemble \
-p D4Z4 -d 40k \
genomeSize=40k \
useGrid=remote \
-nanopore-raw D4Z4/?.fastq \
-nanopore-raw D4Z4/1?.fastq \
-nanopore-raw D4Z4/2?.fastq
```
Here is my output:
```
-- Canu 1.6

-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_20' (from 'java').
-- Detected gnuplot version '4.2 patchlevel 6 ' (from 'gnuplot') and image format 'png'.
-- Detected 16 CPUs and 126 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /c1/apps/slurm/15.08.3/bin/sinfo.
-- Detected Slurm with 'MaxArraySize' limited to 1000 jobs.
--
-- Found 160 hosts with  16 cores and    0 GB memory under Slurm control.
-- Found   1 host  with  48 cores and    0 GB memory under Slurm control.
-- Found  54 hosts with  12 cores and    0 GB memory under Slurm control.
--
-- ERROR
-- ERROR
-- ERROR  Found 3 machine configurations:
-- ERROR    class0 - 160 machines with 16 cores with 0.0009765625 GB memory each.
-- ERROR    class1 - 1 machines with 48 cores with 0.0009765625 GB memory each.
-- ERROR    class2 - 54 machines with 12 cores with 0.0009765625 GB memory each.
-- ERROR
-- ERROR  Task meryl can't run on any available machines.
-- ERROR  It is requesting:
-- ERROR    merylMemory=4-8 memory (gigabytes)
-- ERROR    merylThreads=1-4 threads
-- ERROR
-- ERROR  No available machine configuration can run this task.
-- ERROR
-- ERROR  Possible solutions:
-- ERROR    Change merylMemory and/or merylThreads
-- ERROR

ABORT:
ABORT: Canu 1.6
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   task meryl failed to find a configuration to run on.
ABORT:
```
I have the same issue even without the useGrid=remote, no matter what I do Canu says that there is no memory under Slurm control. I have no idea what is causing this...

Thanks for the help.

**Comment by skoren** [comment]
Canu is parsing the sinfo output which is not matching what it expects. What does:
```
sinfo --exact -o '%N %D %c %m'
```
report? it should show CPUs and memory for each set of machines on your grid.

Given how small your genome is you can also run it off grid by specifying useGrid=false.

**Comment by ANekhai** [comment]
The command reports:
```
sinfo --exact -o '%N %D %c %m'
NODELIST NODES CPUS MEMORY
node[033-191,992] 160 16 1
node901 1 48 1
node[001-032,333-353,991] 54 12 1
```

I will also try to run it off grid.

**Comment by skoren** [comment]
The man page for sinfo reports:
```
              %m    Size of memory per node in megabytes
```
So your nodes are reporting 1mb of ram (which is 0gb) as Canu is reporting. Perhaps you have an older version of slurm (sinfo --version) or your cluster is not configured to properly report available memory.

**Comment by ANekhai** [comment]
We're running an older version I guess (15.08) and perhaps there's something wonky with memory reporting. I'll ask around. Thanks for the help!

**Comment by skoren** [comment]
As a workaround you can alias the sinfo command to cat a file with the output above and the corrected email. Say you made a file named hostinfo.txt which had:
```
NODELIST NODES CPUS MEMORY
node[033-191,992] 160 16 100
node901 1 48 100
node[001-032,333-353,991] 54 12 100
```
or whatever memory was appropriate and then ran ```alias sinfo=cat /full/path/to/hostinfo.txt #``` then you'll get the expected output for Canu. You'd have to make sure the alias is in your profile so it is present on all the nodes where Canu would run.

**Comment by skoren** [comment]
Closing, Canu is correctly reading the config from the cluster but the config indicates no memory on the nodes.

**Comment by conchoecia** [comment]
I encountered this same error, but our grid is using a more recent version of `slurm`, 17.02.7.

**Comment by skoren** [comment]
I don't think it's a version issue but a config issue. The grid isn't accurately reporting the resources. There isn't anything we can do in the code to fix it. You can try the workarounds I suggested or ask your admins why nodes report no memory.

**Comment by zyndagj** [comment]
Besides overloading sinfo, is there a way to manually pass known system information to Canu?

**Comment by skoren** [comment]
Overloading or editing the code is the only way to pass machine info to Canu. You can also explicitly specify all resources to use for each step which will override Canu's auto-configuration.

**Comment by zyndagj** [comment]
Just tried overloading, and that didn't work because Can explicitly calls `/bin/sinfo`. I'll try editing the code and report back.

**Comment by skoren** [comment]
Canu doesn't have a fixed path, it uses which to find the sinfo binary (see findExecutable in Execution.pm). So it must be finding the ```/bin/sinfo``` before your overloaded one.

**Comment by zyndagj** [comment]
You're right - I was confused by the

```
Detected Slurm with 'sinfo' binary in /bin/sinfo
```

message, but came to the same conclusion as you after looking at

https://github.com/marbl/canu/blob/v1.7/src/pipelines/canu/Grid_Slurm.pm#L103

**Comment by zyndagj** [comment]
Got it working with

```
function sinfo {
   /bin/sinfo -p skx-normal --exact -o "%N %D %c %m" | awk '{if ($4 == 1) print $1" "$2" "$3" 192000"; else print $0;}';
}
export -f sinfo
```

Thanks for the help.

**Comment by brianwalenz** [comment]
Added to feature request list for v1.9.  https://github.com/marbl/canu/projects/2#card-17551316
