### ISSUE TITLE
AS_UTL_symlink()-- Failed to make link 'info' pointing to file '../../BC01.gkpStore/info': Function not implemented

### ISSUE THREAD

**Issue by timacwalker** [marbl/canu#657]
Hello, 

My assembly has crashed at the read partition stage. Below is the error message.

```
ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:

ABORT:
ABORT: Canu 1.6
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to partition the reads.
ABORT:
ABORT: Disk space available:  32.989 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (unitigging/BC01.ctgStore/partitionedReads.log):
ABORT:
ABORT:

```
The log file only has the sentence: AS_UTL_symlink()-- Failed to make link 'info' pointing to file '../../BC01.gkpStore/info': Function not implemented

I've noted that issues with AS_UTL_symlink() has happened to others but I think my issues is slightly different. I'm working on a physical machine and have tried reinstalling canu and restarting but the same error occurs. 

Any help will be really appreciated.

Thanks,

Tim.

**Comment by skoren** [comment]
Fundamentally, the error is the same as previous users, your filesystem does not implement ln functionality so the link command fails. I would suggest checking if there is any way to enable symlinks on the FS, otherwise you would have to edit the code to replace the symlink with a copy instead. Take a look at line 307 in src/AS_UTL/AS_UTL_fileIO.C:
```
304   //  Nope?  Make the link.
305 
306   errno = 0;
307   symlink(pathToFile, pathToLink);
308   if (errno)
309     fprintf(stderr, "AS_UTL_symlink()-- Failed to make link '%s' pointing to file '%s': %s\n",
310             pathToLink, pathToFile, strerror(errno)), exit(1);
311 }
```

 you'd need to replace the symlink function with a copy.

**Comment by skoren** [comment]
We should also check for this error within Canu and switch to copy if symlinks don't exist.

**Comment by timacwalker** [comment]
Hi, thanks for your advice.

I had been running the assembly on an external SSD with a exFAT system, I moved the run folder to the main SSD with ext3 system and restarted the run pointing to that new location and it appears to have continued with assembling the corrected/trimmed reads to completion.

**Comment by brianwalenz** [comment]
Not high on my priority list, but tracked with the future release wish list.  Just avoid FAT file systems.  ;-)
