### ISSUE TITLE
Does canu recognize lowercase in input fastq files?

### ISSUE THREAD

**Issue by ShuChen1986** [marbl/canu#658]
Hi,
I used lordec to correct and trim the PacBio reads with the illumina reads. The output fastq file contains lowercases representing the sequences uncorrected. 
My question is: Will canu process the lowercases the same as the uppercases? 
Is it necessary to convert the lowercases to uppercases before canu correction?
Thank you so much! Your reply is high appreciated.

**Comment by brianwalenz** [comment]
Lower case should work just fine, but I don't think it's ever been explicitly tested.  Check the asm.report file in the assembly directory for a report on how many reads and bases were loaded into the read database - also check the various `gkpStore` log files in the correction/ or trimming/ directories.

Since you've already corrected the reads, you can use -pacbio-corrected to skip the correction phase in canu.

**Comment by ShuChen1986** [comment]
Thank you very much! I will check the log files. 
Actually, I have tried to assemble the lordec corrected reads, but the results are very bad, so now I am trying to use canu to correct and trim the lordec corrected reads again. 
I am assembling a genome of ~1.2 Gb. I have 30 Gb PacBio reads and 70 Gb Illumina reads (no mate-pair). I have tried to assemble only PacBio reads with canu, yielding an assembly of ~400Mb, N50 of 35000. Do you have any suggestion to improve the assembly? Thank you so much!

**Comment by skoren** [comment]
The assembly quality is a function of read length, coverage, and repeat content. You are on the low end of coverage (<30x) and I would guess your genome is repetitive. The asm.report file will have more information on the assembly as it proceeded, if you post that it is possible we could suggest improving parameters. The generic advice on the FAQ of using the sensitive parameters (```corMhapSensitivity=high corMinCoverage=0``` would also help if you're not already using them).

**Comment by ShuChen1986** [comment]
I could not find asm.report file among the output files. Is it the log info output to the screen?

**Comment by brianwalenz** [comment]
The report will be $prefix.report, named with canu's -p option.  It is mostly just a cleaned up version of the screen output (the command logging is removed).

**Comment by dibyendukumar** [comment]
Maybe, I am in the wrong place to post a comment, still can't resist. 
I don't understand, why Mhap sensitivity high goes with zero coverage ( "corMhapSensitivity=high corMinCoverage=0"). I feel that setting 'corMinCoverage' to 'zero' leads to data loss at trimming stage. Is it possible to set 'corMhapSensitivity'to high and still use corMinCoverage to 3 or more?

**Comment by skoren** [comment]
You can combine them arbitrarily but I think you are misunderstanding the effects of ```corMinCoverage=0```. It leads to more data being generated from correction, some of which is lost in trimming. This loss in trimming is typically less than the loss in coverage from setting corMinCoverage higher, which leads to a data loss in correction. So the coverages you'd want to compare are the inputs to the unitigging step with corMinCoverage=0 and higher values to see if it is ending up with more to assemble.

**Comment by ShuChen1986** [comment]
I can not find any file named preflex.report. Below are all the files and folders that I got from the assembly step:
Folders:
0sh_assembly.sh
canu-logs
canu-scripts
unitigging
unitigging.html.files
Files
stylosanthes.bubbles.fasta
stylosanthes.contigs.fasta
stylosanthes.gfa
stylosanthes.layout
stylosanthes.layout.readToTig
stylosanthes.layout.tigInfo
stylosanthes.unassembled.fasta
unitigging.html
Will it be useful if I send you the correction.html, trimming.html and unitigging.html?

**Comment by brianwalenz** [comment]
It'd be useful if you'd update to the 1.6 release!  There have been incremental but significant improvements made since 1.4 (the last release to generate bubbles.fasta).

**Comment by ShuChen1986** [comment]
Ok, I will update to canu 1.6 and feed back, but it will probably takes a couple of weeks to finish correction and trimming.

**Comment by ShuChen1986** [comment]
Another question: does canu use sequencing quality in fastq files during correction?
I am asking because I am using lordec corrected reads for canu correction, and the lordec corrected reads do not include sequencing quality. Will it significantly affect the canu correction?

**Comment by brianwalenz** [comment]
Nope, canu doesn't use QVs.  They're actually just discarded if fastq is used.

**Comment by ShuChen1986** [comment]
Thanks a lot.
