### ISSUE TITLE
Small plasmid lost during read correction

### ISSUE THREAD

**Issue by martinghunt** [marbl/canu#66]
Here's some example PacBio data, from the NCTC sample NCTC13626...

Reference accession: GCA_000027045.1.

Fasta of reference: https://github.com/martinghunt/pacbio-14-nctc-assemblies/blob/master/NCTC13626/ref.fa

Filtered subreads: ftp://ngs.sanger.ac.uk/production/pathogens/mh12/pacbio-14-nctc-assemblies/NCTC13626.filtered_subreads.fq.gz

Reads corrected by Canu: ftp://ngs.sanger.ac.uk/production/pathogens/mh12/pacbio-14-nctc-assemblies/NCTC13626.corrected_reads_canu_1.0.fq.gz

Canu assembly: https://github.com/martinghunt/pacbio-14-nctc-assemblies/blob/master/NCTC13626/canu.1.0.fa

The plasmid that gets lost is gi|269942329|emb|FN433598.1|, which is 3kb long. I mapped the filtered subreads and the reads corrected by Canu to the whole reference with bwa mem (v0.7.12) with the option -x pacbio. It maps 259 filtered subreads to the plasmid, but no corrected reads get mapped to the plasmid (counted by running `samtools view foo.bam 'gi|269942329|emb|FN433598.1|' | wc -l`).

I ran Canu version 1.0 with:

    canu -p out -d canu maxThreads=8 maxMemory=16 genomeSize=3075806 -pacbio-raw filtered_subreads.fq -useGrid=0

I've still got all the files and stdout/err from the run if you need anything else.

Martin

**Comment by skoren** [comment]
Canu will correct the longest 40X of data by default so I'm guessing the 3Kb plasmid reads were too short to make it into this set. Try setting corOutCoverage=<whatever your input coverage is> and see if that recovers it.

**Comment by martinghunt** [comment]
Thanks for the fast reply!

So do I understand this correctly - it takes the reads sorted from longest to shortest, keeps adding in reads until it reaches 40X, then uses the remaining shorter reads to correct those longest reads? So I need to increase corOutCoverage to make it correct more reads? Presumably there is a trade-off here, where going too high with corOutCoverage will reduce the accuracy of the corrected reads. Makes sense, as HGAP also loses the plasmid.

Will give it a go and see what happens...

**Comment by skoren** [comment]
Yes, though it doesn't directly sort the reads by length, but by estimating how long they would be after correction. The main trade-off is time, it shouldn't affect your read quality and the longest reads should still be preferentially used for assembly of the chromosome.

**Comment by martinghunt** [comment]
OK, got it, thanks for the explanation. I'll let you know what happens.

**Comment by martinghunt** [comment]
I tried corOutCoverage with values 5 10 15 20 25 30 40 50 60 70 80 90 100. I get no corrected reads mapped to the reference 3k plasmid for any of the runs.

There's also a 30k plasmid in this genome. The number of corrected reads mapped to it depending on corOutCoverage is:
corOutCoverage numer_of_reads
5 0
10 1
15 3
20 3
25 3
30 3
40 4
50 10
60 13
70 19
80 18
90 26
100 30

corOutCoverage=60 was the sweet spot, where the 30k plasmid got assembled, and also the chromosome was still assembled in one piece. Over 60 and the chromosome was in 2 or more pieces. Less than 60 and the plasmid was lost.

But, the two plasmids share a 1kb repeat at 99% identity. Maybe that's not helping matters and might explain why the shorter plasmid is getting lost?

**Comment by skoren** [comment]
How much raw coverage do you have? My recollection from briefly looking at your data is that it was over 300X so you're not going to be correcting 3k reads even at 100. You'd need to set corOutCoverage to be >= your total input coverage to correct the shortest reads you have. 

The reason this isn't the default is because having so much coverage slows down the assembly and can make a worse assembly of the chromosome, which you saw. You probably need to set corOutCoverage very high to correct everything, then do an assembly of the longest 60X plus the shortest 20X to get both plasmids. Generally, PacBio reads aren't very good for assembling <10Kb plasmids because they can also be lost in the sequencing preps and the loading is meant to bias away from short fragments.

**Comment by martinghunt** [comment]
OK, so probably easiest to use Canu to get a good assembly of the chromosome. Then a reassembly of the unmapped reads or use miniasm to mop up the plasmids. Canu is doing a great job of the chromosomes!
