### ISSUE TITLE
chrM is assembled asa duplicated-overlapping contig

### ISSUE THREAD

**Issue by splaisan** [marbl/canu#663]
I assembled a yeast genome with canu and the Mt chromosome seems duplicated and nucmer aligns it as two overlapping segments to the reference Mt. I read that this is due to the fact that the Mt is circular, leading to artefacts during long read assembly. How can resolve this issue and correct the -novo contig to become a true 1 copy Mt? (which tool(s) should I apply?)

Thanks in advance

**Comment by skoren** [comment]
Yes, this is expected for any circular elements. In Canu 1.6 it should give you an alignment string in the GFA file which would tell you where to trim the contig back. Alternatively, you can try Circlator (http://www.sanger.ac.uk/science/tools/circlator)

**Comment by splaisan** [comment]
Thanks Sergey for this info. Could you maybe be a bit more verbose on what to do with the cigar like content in the contigs.gfa. I have never looked as this before and have no clue on what to do next.
I installed circlator but they do not provide a protocol to correct one chromosome so I am not very helped there either.
sorry about that

[tig00000099_rows.gfa.txt](https://github.com/marbl/canu/files/1362789/tig00000099_rows.gfa.txt)

**Comment by skoren** [comment]
The cigar string tells you how the ends of the sequences align so you can convert it to get an exact end point to trim. So you'd walk along the cigar and contig matching the bases up and adding gaps/etc.

This would require custom code or perhaps using something from BioPerl/Python so it may be easier to just run nucmer to get self-alignments on the contig and use those trim points. Run ``nucmer -maxmatch -nosimplify tig00000099.fa tig00000099.fa``` and ```show-coords -lrcTH out.delta``` to find the end overlaps in the tig. Something like this:
```
1	1895	48502	50400	1895	1899	99.37	50400	50400	3.76	3.77	tig00000001	tig00000001
48502	50400	1	1895	1899	1895	99.37	50400	50400	3.77	3.76	tig00000001	tig00000001
```
means trim to 1 to 48502.

Or just align the tig to the reference and trim the assembly to the region covering the reference without the redundancy removed, given something like this:
```
1	39797	10601	50400	39797	39800	99.99	48502	50400	82.05	78.97	ref000001|lambda_NEB3011	tig00000001
37902	48502	1	10600	10601	10600	99.92	48502	50400	21.86	21.03	ref000001|lambda_NEB3011	tig00000001
```
trim to 1895 off the start (or end) based on 39797-37902 (the redundant part in the ref).

PacBIo also has an alternate method written up: https://github.com/PacificBiosciences/Bioinformatics-Training/wiki/Circularizing-and-trimming

**Comment by skoren** [comment]
I've added some info to the FAQ and I presume this is resolved so closing the issue.

**Comment by splaisan** [comment]
thanks a lot @skoren, I still need to do this but am frustrated by the fact I need to clip away one of the overlaps which may be different (SNPs) from the other and be a better sequence. I could not get third party tools to work yet (TBD). I would prefer deriving the consensus of both but need to look for this (https://www.biostars.org/p/675/ ??), you can meanwhile close this track.

Best

**Comment by skoren** [comment]
I wouldn't worry about one or two snps. You should polish the assembly with signal level information like arrow if pacbio or nanopolish if Nanopore and the snps will be corrected.

**Comment by splaisan** [comment]
makes perfect sense, I will do this
Thanks you so much for your time and advice

**Comment by jordur** [comment]
Hi! Same here. We are trying to assembly a BAC (circular)  with a contig length of ~ 196Kb. 
However, Canu seems not to be able to resolve the ends of the unique contig that produces since it is a highly identical region (>99%) but not exactely the same. Attached you will find a self-blast dotplot picture self-explanatory. 
On the other hand the .gfa file from the assembly resulted:

H       VN:Z:bogart/edges
S       tig00000001     *       LN:i:191724
L       tig00000001     +       tig00000001     +       29012M  cv:A:F

Which as far as I know displays a perfect 29012nt region match, isnt' it?
Do you know if there is a way to resolve the ends of the aseembly?
Any advice will be appreciated.
Regards, 
![duplication](https://user-images.githubusercontent.com/3415289/32668433-d1f9f010-c63d-11e7-805c-248797c0ac4f.png)

**Comment by skoren** [comment]
As I said previously, this is expected and documented on the FAQ:http://canu.readthedocs.io/en/latest/faq.html#my-circular-element-is-duplicated-has-overlap

You have an old version of Canu which did not report the full alignment cigar string in the GFA. The current release would report the cigar string which gives the match and mismatch positions.
