### ISSUE TITLE
can't find trimmed reads 

### ISSUE THREAD

**Issue by sarah872** [marbl/canu#665]
I am running canu v1.5 +0 changes (r8200 69b5f328f8cdd16fc93d3768c09768a985b4be91) on a low coverage nanopore-sequenced genome with the following commands:
`canu -p genome -d genome genomeSize=4.5m -nanopore-raw nanopore_extracted_reads.fastq`

The correction step is successful, but when it comes to the trimming, no fastq output is written:

`can't find trimmed reads 'genome.trimmedReads*' in directory 'genome'`

Canu is run on a grid.

**Comment by brianwalenz** [comment]
How low coverage?  I'd guess that all the reads corrected poorly and were trimmed out.

You can try running v1.6 which, if it doesn't do better at correction, at least has better logging (the asm.report output).  Use the 'low coverage' options; see http://canu.readthedocs.io/en/latest/faq.html.

**Comment by sarah872** [comment]
Thank you very much for the support. Did you mean the `correctedErrorRate=0.075` option`? My coverage is only 5X.

**Comment by skoren** [comment]
Yes, though I just updated that documentation for Nanopore data. However, you have no corrected reads so this won't help you and Canu should already be auto-setting the low coverage settings for correction (```corMhapSensitivity=high corMinCoverage=0```). You can confirm this from the logs like this:
```
-- OVERLAPPER (mhap) (correction)
--
-- Set corMhapSensitivity=high based on read coverage of 16.
--
-- PARAMETERS: hashes=768, minMatches=2, threshold=0.78
--
```
5x really isn't enough to do much, you'd be best using the data for scaffolding or another hybrid assembler.
