### ISSUE TITLE
Failed to submit batch jobs.

### ISSUE THREAD

**Issue by yanboANU** [marbl/canu#669]
command:  
```
/canu-1.6/Linux-amd64/bin/canu -p 1 -d sd_0001 genomeSize=230k -pacbio-raw sd_0001.fastq
```

Error:
```
CRASH:
CRASH: Canu 1.6
CRASH: Please panic, this is abnormal.
ABORT:
CRASH:   Failed to submit batch jobs.
CRASH:
CRASH: Failed at /short/dl7/yli659/liyanbo/Tools/canu-1.6/Linux-amd64/bin/lib/canu/Execution.pm line 1119
CRASH: 	canu::Execution::submitOrRunParallelJob(1, 'meryl', 'correction/0-mercounts', 'meryl', 1) called at /short/dl7/yli659/liyanbo/Tools/canu-1.6/Linux-amd64/bin/lib/canu/Meryl.pm line 538
CRASH: 	canu::Meryl::merylCheck(1, 'cor') called at /short/dl7/yli659/liyanbo/Tools/canu-1.6/Linux-amd64/bin/canu line 663
CRASH: 
CRASH: Last 50 lines of the relevant log file (correction/0-mercounts/meryl.jobSubmit-01.out):
CRASH:
CRASH:
```

And I checked correction/0-mercounts/meryl.jobSubmit-01.out:
```
qsub: Error: The system doesn't support the use of "-l nodes". Please use "-l ncpus" instead.
```

I also checked the correction/0-mercounts/meryl.jobSubmit-01.sh
```
#!/bin/sh
qsub -j oe \
  -l mem=8g -l nodes=1:ppn=4 \
  -N "meryl_1" \
   \
  ./meryl.sh  \
> ./meryl.jobSubmit-01.out 2>&1
 ```
I think maybe I should change  -l nodes in correction/0-mercounts/meryl.jobSubmit-01.sh to -l ncpus?
But I use the binary code of canu. And source code on my server cannot be compiled successfully.

**Comment by skoren** [comment]
You don't need to change the code to change how cpu is requested, just set     ```gridEngineThreadsOption="-l npcus=THREADS"``` or whatever syntax is appropriate for your cluster.

**Comment by yanboANU** [comment]
Thanks, it works.

**Comment by yanboANU** [comment]
I am sorry bother you again.  

canu command:
#!/bin/bash
#PBS -q normal
#PBS -l walltime=0:05:00
#PBS -l mem=128GB
#PBS -l ncpus=16
#PBS -l wd
module load java/jdk1.8.0_60
module load gnuplot

/Tools/canu-1.6/Linux-amd64/bin/canu -p 1 -d sd_0001 genomeSize=230k gridEngineThreadsOption"=-l ncpus=16" -pacbio-raw /Project/yeastPacBioSim50x/sd_0001.fastq


canu-scripts/canu.01.out:
ERROR:  mhap overlapper requires java version at least 1.8.0; you have unknown (from 'java').
ERROR:  'java -showversion' reports:

**Comment by skoren** [comment]
You're loading a module in a script but the next time Canu launches itself on the grid it won't know to load that module unless you pass through a parameter to maintain environment, I believe adding -V to gridOptions should do it (```gridOptions="-V"```). You can also set the java executable for Canu using the java variable (see issue #671).
