### ISSUE TITLE
qsub error

### ISSUE THREAD

**Issue by TonyMane** [marbl/canu#671]
Greetings, we were able to run canu and the tutorial on a small linux machine, but I am now trying to run the ecoli tutorial using PBS grid, as we are farily confident we'll need to use this for assembling metagenomic data. I am using version 1.6 of canu. The command I am issuing is below (also included in the canu.pbs.txt):
```
#CANU
#PBS -N canu
#PBS -l nodes=1:ppn=20
#PBS -l mem=20gb
#PBS -l walltime=90:00:00
#PBS -q microbio-1
#PBS -j oe
#PBS -o /nv/hp10/abertagnolli3/scratch/data/canu.log
#PBS -m abe
#PBS -M abertagnolli3@biology.gatech.edu

module load java/1.8.0_25

/nv/hp10/abertagnolli3/scratch/data/canu/Linux-amd64/bin/canu -p ecoli -d /nv/hp10/abertagnolli3/scratch/data/ecoli-pacbio-2 genomeSize=4.8m -pacbio-raw /nv/hp10/abertagnolli3/scratch/data/pacbio.fastq gnuplotTested=true useGrid=1 gridEngineMemoryOption="-l h_vmem=MEMORY" gridEngineThreadsOption="-pe make THREADS" '
```

This appears to run, but crashes (see attached canu.log, and meryl.jobSubmit-01.out.txt).

the specific error message is "No default queue specified MSG=requested queue not found". 

I queue i would typically use is called 'microbio-1'... does canu need to be told this?

Any help is useful.  

[canu.log](https://github.com/marbl/canu/files/1381251/canu.log)

[canu.pbs.txt](https://github.com/marbl/canu/files/1381252/canu.pbs.txt)
[meryl.jobSubmit-01.out.txt](https://github.com/marbl/canu/files/1381253/meryl.jobSubmit-01.out.txt)

**Comment by skoren** [comment]
Canu won't request time or specific queues by default. You can make it request parameters for all steps using the gridOptions parameter (```gridOptions="--time=72:00:00"``` for example).

**Comment by TonyMane** [comment]
Thankyou- the above was fixed by adding gridOptions='-q microbio-1'. 
However, i am now getting a new error regarding java:
'ERROR:  mhap overlapper requires java version at least 1.8.0; you have 1.7.0_111 (from 'java').'
This is in the output directory 'canu.out'

In the pbs script i, the first line indicates:
'module load java/1.8.0_25'
This seems to work, in that the "correction" directory is created, and the correction program requires this, i think (java 1.8). 
I then saw in the documenation you can modify java with java<string="java">. So, i added the below to end of the previously attached pbs script:

 java='/etc/modulefiles/java/1.8.0_25' 

however, i still get the a similar out:

ERROR:  mhap overlapper requires java version at least 1.8.0; you have unknown (from '/etc/modulefiles/java/1.8.0_25').
ERROR:  '/etc/modulefiles/java/1.8.0_25 -showversion' reports:

again, any suggestions are welcome, thanks again!

**Comment by skoren** [comment]
You need to make java point to the binary, not the folder so it would be ```java=/etc/modulefiles/java/1.8.0_25/bin/java```

**Comment by TonyMane** [comment]
i think this is the binary based on the below:
'[abertagnolli3@microbio-1 java]$ ls -l
total 8
-rw-r--r--. 1 root root 539 May 11  2015 1.7.0
-rw-r--r--. 1 root root 542 May 11  2015 1.8.0_25'

**Comment by skoren** [comment]
I don't think it's the binary it's too small. It's probably just the module file. You could try loading the module and seeing what ```which java``` reports.

**Comment by TonyMane** [comment]
thank you! this provided the right path, looks like its running now...
