### ISSUE TITLE
Canu parameter for speeding up process

### ISSUE THREAD

**Issue by fetyj** [marbl/canu#674]
How can I speed up the assembly for a bacterial genome of 3Mb (which parameters could be modified). I tried with default parameters but it took more than 48h to finish (on Linux computer with 16CPU and 63Gb of memory), is this normal? here is my command and the log:

`./canu -p Lb6870_mixnano_sample -d /oradisk/nanoporemix_subsamp genomeSize=3.5m -nanopore-raw /home/fiestaj/nano_downsamplemix.fastq.gz`
``` 
CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_131' (from 'java').
-- Detected gnuplot version '5.0 patchlevel 3' (from 'gnuplot') and image format 'png'.
-- Detected 16 CPUs and 63 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |  algorithm
--        -------  ------  --------   --------  -----------------------------
-- Local: meryl      8 GB    4 CPUs x   4 jobs  (k-mer counting)
-- Local: cormhap    6 GB   16 CPUs x   1 job   (overlap detection with mhap)
-- Local: obtovl     8 GB    8 CPUs x   2 jobs  (overlap detection)
-- Local: utgovl     8 GB    8 CPUs x   2 jobs  (overlap detection)
-- Local: ovb        3 GB    1 CPU  x  16 jobs  (overlap store bucketizer)
-- Local: ovs        8 GB    1 CPU  x  16 jobs  (overlap store sorting)
-- Local: red        2 GB    4 CPUs x   4 jobs  (read error detection)
-- Local: oea        1 GB    1 CPU  x  16 jobs  (overlap error adjustment)
-- Local: bat       15 GB    4 CPUs x   4 jobs  (contig construction)
-- Local: cns       15 GB    4 CPUs x   4 jobs  (consensus)
-- Local: gfa        8 GB    4 CPUs x   4 jobs  (GFA alignment and processing)
```
Thanks for your help

**Comment by skoren** [comment]
If you have very long reads (>100kb) yes it can slow down the assembly portion (the correction should still be fast). See the release notes for details: https://github.com/marbl/canu/releases/tag/v1.6 and FAQ here:
http://canu.readthedocs.io/en/latest/faq.html#what-parameters-should-i-use-for-my-reads. You can use the parameters suggested there (```overlapper=mhap utgReAlign=true```) or just ```-fast``` if you are on the tip version of Canu.

**Comment by fetyj** [comment]
Thanks for the tip, my reads are not that long (~20kb) but changing those parameters you mentioned increase drastically the process (assembly finished in 3h-4h). 

Thanks,
Fety
