### ISSUE TITLE
slurm, sbatch error

### ISSUE THREAD

**Issue by nailooj** [marbl/canu#677]
Hi,
I'm having difficulties running canu (for the first time) on our cluster (slurm). The initial canu job to build gkpStore completes successfully but fails to submit canu.01.sh. Canu doesn't seem to find the redirected output from the meryl job and fails the slurm dependency check - maybe?

Any suggestions would be gratefully received.

Thanks 

Canu 1.6

```canu -p plg gridOptions="-V" -d /fast/users/ooj11/plg_canu/run1 genomeSize=620m -pacbio-raw /fast/users/nailooj/plantago_canu/all_WT_cells.fasta```

```-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Fri Oct 20 15:35:19 2017 with 175080.225 GB free disk space

    cd correction
    /fast/users/ooj11/local/canu-1.6/Linux-amd64/bin/gatekeeperCreate \
      -minlength 1000 \
      -o ./plg.gkpStore.BUILDING \
      ./plg.gkpStore.gkp \
    > ./plg.gkpStore.BUILDING.err 2>&1

-- Finished on Fri Oct 20 15:47:45 2017 (746 seconds) with 175044.478 GB free disk space
----------------------------------------
--
-- In gatekeeper store 'correction/plg.gkpStore':
--   Found 5218673 reads.
--   Found 39838269478 bases (64.25 times coverage).
--
--   Read length histogram (one '*' equals 27968.57 reads):
--        0   4999 1957800 ********************************************************************
**
--     5000   9999 1672859 ***********************************************************
--    10000  14999 1190331 ******************************************
--    15000  19999 289805 **********
--    20000  24999  73420 **
--    25000  29999  22752 
--    30000  34999   7602 
--    35000  39999   2602 
--    40000  44999    960 
--    45000  49999    349 
--    50000  54999    121 
--    55000  59999     33 
--    60000  64999     11 
--    65000  69999     13 
--    70000  74999      5 
--    75000  79999      4 
--    80000  84999      3 
--    85000  89999      0 
--    90000  94999      2 
--    95000  99999      0 
--   100000 104999      0 
--   105000 109999      0 
--   110000 114999      0 
--   115000 119999      0 
--   120000 124999      1

-- Finished stage 'cor-gatekeeper', reset canuIteration.
-- Finished stage 'merylConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
--
-- 'meryl.jobSubmit-01.sh' -> job slurm 17.02.6 task 1.
--
----------------------------------------
-- Starting command on Fri Oct 20 15:48:41 2017 with 175041.353 GB free disk space

    cd /fast/users/ooj11/plg_canu/run1
    sbatch \
      --depend=afterany:slurm 17.02.6 \
      --mem-per-cpu=4g \
      --cpus-per-task=1 \
      -V  \
      -D `pwd` \
      -J 'canu_plg' \
      -o canu-scripts/canu.01.out canu-scripts/canu.01.sh
sbatch: error: Unable to open file 17.02.6

-- Finished on Fri Oct 20 15:48:41 2017 (lickety-split) with 175041.353 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:

CRASH:
CRASH: Canu 1.6
CRASH: Please panic, this is abnormal.
ABORT:
CRASH:   Failed to submit script.

 ```

**Comment by skoren** [comment]
It looks like Canu couldn't parse the jobbed of the job it needs to wait for (meryl.sh). Whats the contents of meryl.jobSubmit-01.sh and meryl.jobSubmit-01.out?

**Comment by nailooj** [comment]
Thanks for the prompt response, my weekend got in the way.. 

Contents of meryl.jobSubmit-01.sh:
```#!/bin/sh

sbatch \
  --mem-per-cpu=3968m --cpus-per-task=8 -V -o meryl.%A_%a.out \
  -D `pwd` -J "meryl_plg" \
  -a 1-1 \
  ./meryl.sh 0 \
> ./meryl.jobSubmit-01.out 2>&1
```

Contents of meryl.jobSubmit-01.out:
```slurm 17.02.6 ```

Cheers!

**Comment by skoren** [comment]
Interesting, it seems slurm isn't returning the job id of the submitted job. Canu depends on the grid to return a job id for the submitted job to track dependencies. As far as we've seen, every grid returns a job id, yours is the first that did not. Is the meryl job actually submitted and running in your queue? Does sbatch normally print job ids when you submit jobs yourself?

**Comment by nailooj** [comment]
Hmm, after watching the queue, no I don't think the meryl job is submitted at all. You can submit jobs from compute nodes so I don't _think_ that's the issue. Will check with the sysadmins.

The stdout after sbatch is just: 
```Submitted batch job 4110756```

Thanks for your help.

**Comment by skoren** [comment]
Your output above is what Canu expects but I'm not sure why that isn't output from the meryl command. What happens if you run the submit command manually from inside the ```/fast/users/ooj11/plg_canu/run1/0-mercounts``` folder:
```sbatch \
  --mem-per-cpu=3968m --cpus-per-task=8 -V -o meryl.%A_%a.out \
  -D `pwd` -J "meryl_plg" \
  -a 1-1 \
  ./meryl.sh 0
```

**Comment by nailooj** [comment]
Oh! I thought -V was forwarding the environment, which I need to load modules on the compute node. I'll give it a try, thanks.

**Comment by skoren** [comment]
It does on PBS/Torque and SGE but not Slurm

**Comment by nailooj** [comment]
Ah, right. Thank you!

**Comment by nailooj** [comment]
Ok, Canu seems to be working with ```gridOptions="--export=ALL"```.

Many thanks skoren.
