### ISSUE TITLE
Canu can't find gkpStore

### ISSUE THREAD

**Issue by eyesmo** [marbl/canu#678]
Hi all! I'm using MinION to teach myself bioinformatics for the first time so this issue is probably my ignorance rather than a bug.

I'm running canu v 1.6 on MacOS (laptop), trying to de-novo assemble some PCRed amplicons. I'm following the data analysis pipeline outlined in the last two pages of this paper (https://www.biorxiv.org/content/biorxiv/early/2017/09/15/189159.full.pdf), and have gotten everything working up to the canu assembly step. 

However, when I try to run the canu assembly, I get this output: 

>ls: */*gkpStore: No such file or directory

The full command I'm using to try to run the assembly is 
```
canu –p 20171017_Filt13_NPextract_1658_14148_CRISPRrun_canu 
     –d alignment/canuAssembly genomeSize=6000 minReadLength=100 
     minOverlapLength=50 -nanopore-raw 20171017_Filt13_NPextract_1658_14148_CRISPRrun.fastq 
     tgStoreDump -T unitigging/20171017_Filt13_NPextract_1658_14148_CRISPRrun_canu.ctgStore 2 
     -G unitigging/ 20171017_Filt13_NPextract_1658_14148_CRISPRrun_canu.gkpStore - consensus 
     -fasta  -tig 1 > 20171017_Filt13_NPextract_1658_14148_CRISPRrun_canu.bestcontig.fasta
```

And the command from the paper that I'm trying to emulate is 

```
canu –p barcode01_eyelash_palm-pitviper_16S_canu 
     –d barcode01_eyelash_palm-pitviper_16S_canu genomeSize=1000
     minReadLength=100 minOverlapLength=50 -nanopore-raw
     barcode01_eyelash_palm-pitviper_16S.fastq
     tgStoreDump -T unitigging/barcode01_eyelash_palm-pitviper_16S_canu.ctgStore
     2 -G unitigging/ barcode01_eyelash_palm-pitviper_16S_canu.gkpStore -
     consensus -fasta -tig 1 > barcode01_eyelash_palm pitviper_16S_canu.bestcontig.fasta
```

Am I missing something? Do I need to run a command to create gkpStore or something before I can run canu?

Screenshots of the code I ran and the command from the paper attached. Thanks for reading!
<img width="1094" alt="screen shot 2017-10-20 at 9 19 08 pm" src="https://user-images.githubusercontent.com/2289040/31847274-b0f7adae-b5de-11e7-8d5a-fdff55e81b79.png">
<img width="692" alt="screen shot 2017-10-20 at 9 36 55 pm" src="https://user-images.githubusercontent.com/2289040/31847283-e17215fa-b5de-11e7-82b0-8f37d248d3fd.png">

**Comment by skoren** [comment]
Those are multiple commands so you want to run:
```
canu –p barcode01_eyelash_palm-pitviper_16S_canu 
     –d barcode01_eyelash_palm-pitviper_16S_canu genomeSize=1000
     minReadLength=100 minOverlapLength=50 -nanopore-raw
     barcode01_eyelash_palm-pitviper_16S.fastq
```
then wait for that to finish. Next enter the assembly directory (```barcode01_eyelash_palm```) and run:
```
     tgStoreDump -T unitigging/barcode01_eyelash_palm-pitviper_16S_canu.ctgStore
     2 -G unitigging/ barcode01_eyelash_palm-pitviper_16S_canu.gkpStore -
     consensus -fasta -tig 1 > barcode01_eyelash_palm pitviper_16S_canu.bestcontig.fasta
```

**Comment by eyesmo** [comment]
Thanks skoren! I got the first canu command to run properly, I think (see attached screenshot of created folder).

However, when I enter the canu assembly folder and try the second command 
```
tgStoreDump -T unitigging/20171017_Filt13_NPextract_1658_14148_CRISPRrun_canu.ctgStore 2 -G unitigging/20171017_Filt13_NPextract_1658_14148_CRISPRrun_canu.gkpStore - consensus -fasta -tig 1 > 20171017_Filt13_NPextract_1658_14148_CRISPRrun_canu.bestcontig.fasta
```
I get 
```
/bin/sh: tgStoreDump: command not found
```
I also tried 
```
canu tgStoreDump -T unitigging/20171017_Filt13_NPextract_1658_14148_CRISPRrun_canu.ctgStore 2 -G unitigging/20171017_Filt13_NPextract_1658_14148_CRISPRrun_canu.gkpStore - consensus -fasta -tig 1 > 20171017_Filt13_NPextract_1658_14148_CRISPRrun_canu.bestcontig.fasta
```
Which doesn't give an explicit error message. However, the contents of the generated 20171017_Filt13_NPextract_1658_14148_CRISPRrun_canu.bestcontig.fasta are not an assembly but a series of error messages:
```
ERROR:  Invalid command line option 'tgStoreDump'.  Did you forget quotes around options with spaces?
ERROR:  Invalid command line option '-T'.  Did you forget quotes around options with spaces?
ERROR:  File supplied on command line; use -s, -pacbio-raw, -pacbio-corrected, -nanopore-raw, or -nanopore-corrected.
ERROR:  Invalid command line option '2'.  Did you forget quotes around options with spaces?
ERROR:  Invalid command line option '-G'.  Did you forget quotes around options with spaces?
ERROR:  File supplied on command line; use -s, -pacbio-raw, -pacbio-corrected, -nanopore-raw, or -nanopore-corrected.
ERROR:  Invalid command line option '-'.  Did you forget quotes around options with spaces?
ERROR:  Invalid command line option 'consensus'.  Did you forget quotes around options with spaces?
ERROR:  Invalid command line option '-fasta'.  Did you forget quotes around options with spaces?
ERROR:  Invalid command line option '-tig'.  Did you forget quotes around options with spaces?
ERROR:  Invalid command line option '1'.  Did you forget quotes around options with spaces?

```
Is there something obvious that I'm missing to get tgStoreDump to run properly?
<img width="952" alt="screen shot 2017-10-22 at 12 43 27 am" src="https://user-images.githubusercontent.com/2289040/31858639-3ec5ff94-b6c2-11e7-94cb-8ab1cd36f3a6.png">

**Comment by skoren** [comment]
You don't seem to have the full canu binary directory in your path. What does ```which canu``` report? You can use that path to specify the path to tgStoreDump. Your second command (```canu tgStoreDump```) is wrong and won't work.

**Comment by eyesmo** [comment]
```
which canu
```
reports
```
usr/local/bin/canu
```
and I can find a 27 kb Alias labeled canu in that directory. What exactly should I do to specify the path to tgStoreDump from here?

**Comment by skoren** [comment]
The installation seems to have just symlinked to the canu script rather than copying all the binaries to your bin directory. Was this a package installer? tgStoreDump should be in the same directory as wherever the alias points.

**Comment by eyesmo** [comment]
Yes, I installed canu v1.6 with Hombrew. Should I try installing a different way?

**Comment by skoren** [comment]
It will work, you just may want to add the original Canu path that ```canu``` is symlinked from to your path as well or you'll always have to specify the full path to any program other than canu (like tgStoreDump).

**Comment by eyesmo** [comment]
I'm still something of a novice at navigating Bash. What command would I run to add the original canu path to my current path?

**Comment by skoren** [comment]
To do it permanently, you'd need to edit the login script, like .bash_profile to add the line
```export PATH=$PATH:/path/to/canu/binaries/```
replacing /path/to/canu/binaries with the actual path which is probably something like /usr/local/canu-1.6/Darwin-amd64/bin. See https://unix.stackexchange.com/questions/129143/what-is-the-purpose-of-bashrc-and-how-does-it-work for some info on bash startup scripts.

**Comment by eyesmo** [comment]
Making progress! I edited the .bash_profile script as you recommended and now bash recognizes tgStoreDump as a command. I re-ran the canu assembly, and then tried 
```
tgStoreDump -T unitigging/20171017_Filt13_NPextract_1658_14148_CRISPRrun_canu.ctgStore 2 -G unitigging/20171017_Filt13_NPextract_1658_14148_CRISPRrun_canu.gkpStore -consensus -fasta -tig 1 > 20171017_Filt13_NPextract_1658_14148_CRISPRrun_canu.bestcontig.fasta
```

and now it's giving me the error message
```
gkStore()--  failed to open 'unitigging/20171017_Filt13_NPextract_1658_14148_CRISPRrun_canu.gkpStore' for read-only access: store doesn't exist.
```
20171017_Filt13_NPextract_1658_14148_CRISPRrun_canu.gkpStore does exist, though I'm not sure if this is what the error message is referring to. Thanks again for your help!
<img width="1284" alt="screen shot 2017-10-23 at 2 27 21 pm" src="https://user-images.githubusercontent.com/2289040/31908993-51963a3e-b7fe-11e7-9e06-2e12b40900d3.png">

**Comment by skoren** [comment]
The error means the OS says a folder named ```unitigging/20171017_Filt13_NPextract_1658_14148_CRISPRrun_canu.gkpStore``` doesn't exist. What folder are you in when you run it? What does ls for the folder return? Can you send a link to your reads as well or upload them here?

**Comment by eyesmo** [comment]
Now it's working! Thanks, I was working one folder too far up and hadn't specified the full path to the gkpStore. That seems to have solved my problem for now. Thanks so much for your help!
