### ISSUE TITLE
no error but no .gz file

### ISSUE THREAD

**Issue by cpaight** [marbl/canu#679]
canu version 1.6
on a linux server
command
module load canu/1.6
module load java/8u66 

canu \
-p xfilter -d xfilterpb \
genomeSize=50g \
-pacbio-raw XRICL_20171011_RS42150_PL100093051-1_A01-1.fastq

canu runs with no errors, but does not output an assembly or a reads.gz file
there are fasta files in /correction/1-overlapper/blocks/ but I don't think that is what I want is it?

**Comment by skoren** [comment]
I would guess it is still running on your grid. What is the full output from the canu command? Is your genome size accurate (50G)?

**Comment by cpaight** [comment]
there is nothing in queue I have run 50g and 250g it is a metagenome 250g
is around total of what I expect

**Comment by skoren** [comment]
Typically we don't increase the genome size but set other parameters for a metagenome, see the FAQ:
http://canu.readthedocs.io/en/latest/faq.html#what-parameters-can-i-tweak

What is the output of the canu command you ran? What is in the output files in the ```xfilterpb/canu-scripts/canu.*.out``` files?

**Comment by cpaight** [comment]
Ahh I see
the 50g run made 3 out files the third failed with

Mhap precompute jobs failed, tried 2 times, giving up.

the 250g failed after 7 out files with

canu failed with 'canu iteration count too high, stopping pipeline (most
likely a problem in the grid-based computes)'

sorry now that I see where the errors are I can trouble shoot myself. Thank
you

**Comment by skoren** [comment]
Closing, original issue is resolved, open a new issue if you need help tracking down why it stopped.
