### ISSUE TITLE
Error: Could not create the Java Virtual Machine.

### ISSUE THREAD

**Issue by miguelpmachado** [marbl/canu#68]
Hi,
I've just installed CANU and I'm trying to assembly one MiniON run with the command:
<code>
canu -p uncorrected_reads -d ./uncorrected_reads genomeSize=2.1m maxMemory=10 maxThreads=2 -nanopore-raw /scratch/mpmachado/minion/GBS313V.200_2d.fasta
</code>
However it stops with the following error:
> canu failed with 'failed to precompute mhap indices.  Made 2 attempts, jobs still failed'.

(you can find more details [here](https://github.com/marbl/canu/files/179606/canu.uncorrected_reads.stderr.txt))

I looked into precompute.000001.out file and I found it was a problem with Java Virtual Machine:
```
 Dumping reads from 1 to 18000 (inclusive).
 Starting mhap precompute.
 Invalid maximum heap size: -Xmx6g
 The specified size exceeds the maximum representable size.
 Error: Could not create the Java Virtual Machine.
 Error: A fatal exception has occurred. Program will exit.
 mv: cannot stat `/scratch/mpmachado/minion/canu/./uncorrected_reads/correction/1-overlapper/blocks/000001.dat': No such file or directory
 Mhap failed.
```
(same for precompute.000002.out)

Does any one knows how can I fixed this?
Thank you in advance.
Best regards,
Miguel Machado

**Comment by skoren** [comment]
You have a 32-bit or mixed JVM that cannot allocate more than 4GB of ram. When running java try:

```
java -version
java -d64 version
```

It should report something like:
```
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
```

If it is reporting mixed or 32-bit you would need to install a 64-bit VM. If java -d64 doesn't give an error, you could also modify lines 365,441 of canu-1.1/Linux-amd64/bin/lib/canu/OverlapMhap.pm to be
```
 print F "$javaPath -d64 -server -Xmx", getGlobal("${tag}mhapMemory"), "g \\\n";
```
instead of
```
print F "$javaPath -server -Xmx", getGlobal("${tag}mhapMemory"), "g \\\n";
```

**Comment by miguelpmachado** [comment]
Thank you Sergey, changing to a 64x JRE worked fine.
Best regards,
Miguel

**Comment by Yunxia-li** [comment]
Hello:
     I had run the command:  `canu -correct -p yyl-cor -d yyl-bl67@mini-mapped Threads=32 corOutCoverage=500 corMinCoverage=2 genomeSize=1m minReadLength=1000 minOverlapLength=1000 -nanopore-raw  `


 I got the error in /pwd/correction/1-overlapper/precompute.000002.out
````
Running` job 2 based on command line options.
Dumping reads from 18001 to 29104 (inclusive).

Starting mhap precompute.

Unrecognized option: -d64
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Mhap failed.

```
It looks same with the previous problem.
Should I install a new JDE?

- When I run:   java -version 

there is : 
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

- When I run:   java -d64 -version 

there is : 
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

It seems that java (jde) is fine for me.
So, can you tell me why ?

Hope for your reply.

**Comment by skoren** [comment]
You've got a different java in your environment than the default that gets loaded when Canu's job runs. I would guess the one Canu sees is newer, as -d64 was removed in recent JVMs. Specify the full java path to can ```java="/path/to/what/java/you're/running"```

You've got an old canu install, newer versions report the software version within each job. Download the 1.8 release (or wait a week for the 1.9 release).
