### ISSUE TITLE
No errors, however cannot generate *correctedReads.fasta.gz.

### ISSUE THREAD

**Issue by EugeneKim76** [marbl/canu#680]
Hi all,
I'm trying to generate corrected reads by using canu 6.1.
I used commands as shown below.

nohup canu -correct \
        -p 35 -d 35 \
        genomeSize=5m \
        useGrid=false  -pacbio-raw reads.34_34.fasta &

canu running finished with no errors with the message below.

Purging correctReads output after loading into stores.
Purging overlaps used for correction.
Finished stage 'cor-loadCorrectedReads', reset canuIteration.
Bye.

However, there was no output file of corrected reads( *correctedReads.fasta.gz.)

Using canu 1.3, we could generate corrected reads from reads.34_34.fasta.
Am I missing something?

Best.

**Comment by skoren** [comment]
What does canu -version report? I would guess you're running the latest tip not 1.6 which doesn't output the fasta file by default. You can enable it using ```saveReads=true```.

**Comment by EugeneKim76** [comment]
Sorry for the typo.
I used canu ver. 1.6.
By using 'saveReads=true' , I could obtain *correctedReads.fasta.gz.
Thanks a lot.

**Comment by EugeneKim76** [comment]
Sorry for the typo.
I used canu ver. 1.6.
By using 'saveReads=true' , I could obtain *correctedReads.fasta.gz.
Thanks a lot.

**Comment by skoren** [comment]
Canu 1.6 does not support saveReads=true and outputs them by default so I don't think you are using 1.6 but the unreleased tip. The version would output something like:
```
Canu snapshot v1.6 +112 changes (r8524 2d3f55ab06f728c63cba306bab425cbd8368ae20)
```
