### ISSUE TITLE
SplitReads in Trimming seems to stall

### ISSUE THREAD

**Issue by dkainer** [marbl/canu#682]
Hi,

I am at the Trimming stage of assembling a 500 Mb genome using very high coverage nanopore data. I am using a PBSpro HPC. 

Canu-1.6 has reached 3-overlapbasedtrimming but the following command has been running on the Executive job for many hours without really producing anything :

```
-- Found 268 hosts with  28 cores and  256 GB memory under PBSPro control.
-- Found 1125 hosts with  16 cores and   64 GB memory under PBSPro control.
-- Found   3 hosts with  32 cores and 3072 GB memory under PBSPro control.
-- Found  72 hosts with  16 cores and  128 GB memory under PBSPro control.
-- Found  13 hosts with  24 cores and  256 GB memory under PBSPro control.
-- Found 2364 hosts with  16 cores and   32 GB memory under PBSPro control.
-- Found  30 hosts with  64 cores and  192 GB memory under PBSPro control.
-- Found  20 hosts with  32 cores and  128 GB memory under PBSPro control.
-- Found  10 hosts with  28 cores and 1024 GB memory under PBSPro control.
-- Found  19 hosts with  24 cores and  128 GB memory under PBSPro control.
-- Found 533 hosts with  28 cores and  128 GB memory under PBSPro control.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl     32 GB   16 CPUs  (k-mer counting)
-- Grid:  cormhap   32 GB   16 CPUs  (overlap detection with mhap)
-- Grid:  obtmhap   32 GB   16 CPUs  (overlap detection with mhap)
-- Grid:  utgmhap   32 GB   16 CPUs  (overlap detection with mhap)
-- Grid:  cor       16 GB    4 CPUs  (read correction)
-- Grid:  ovb        2 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       30 GB    1 CPU   (overlap store sorting)
-- Grid:  red       16 GB    4 CPUs  (read error detection)
-- Grid:  oea       32 GB   16 CPUs  (overlap error adjustment)
-- Grid:  bat       32 GB   16 CPUs  (contig construction)
-- Grid:  cns       32 GB   16 CPUs  (consensus)
-- Grid:  gfa       32 GB   16 CPUs  (GFA alignment and processing)
--
-- Found Nanopore corrected reads in 'trimming/150x.gkpStore'.
--
-- Generating assembly '150x' in '/short/xf1/nanopore/Epauc/assembly/canu_150x'
--
-- Parameters:
--
--  genomeSize        500000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1200 ( 12.00%)
--    utgOvlErrorRate 0.1200 ( 12.00%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1200 ( 12.00%)
--    utgErrorRate    0.1200 ( 12.00%)
--    cnsErrorRate    0.1200 ( 12.00%)
--
--
-- BEGIN TRIMMING
--
----------------------------------------
-- Starting command on Wed Oct 25 09:31:17 2017 with 2924452.85 GB free disk space

    cd trimming/3-overlapbasedtrimming
    /short/xf1/src_big/canu-1.6/Linux-amd64/bin/splitReads \
      -G  ../150x.gkpStore \
      -O  ../150x.ovlStore \
      -Ci ./150x.1.trimReads.clear \
      -Co ./150x.2.splitReads.clear \
      -e  0.12 \
      -minlength 1000 \
      -o  ./150x.2.splitReads \
    >     ./150x.2.splitReads.err 2>&1

```

There is a **splitReads.err** file which says only:
``` Processing from ID 1 to 5972710 out of 5972710 reads, using errorRate = 0.12 ```

but there does not seem to be any other output being generated. I have tried restarting the job but it is doing the same thing. From what i understand, the splitReads process should be quite quick?

This is the list of files in the 3-overlapbasedtrimming directory:

```
-rw-r----- 1 dxk800 xf1  46M Oct 24 21:40 150x.1.trimReads.clear
-rw-r----- 1 dxk800 xf1    0 Oct 24 21:40 150x.1.trimReads.inputDeletedReads.dat
-rw-r----- 1 dxk800 xf1  478 Oct 24 21:40 150x.1.trimReads.inputDeletedReads.gp
-rw-r----- 1 dxk800 xf1    0 Oct 24 21:40 150x.1.trimReads.inputDeletedReads.lg.png
-rw-r----- 1 dxk800 xf1    0 Oct 24 21:40 150x.1.trimReads.inputNoTrimReads.dat
-rw-r----- 1 dxk800 xf1  474 Oct 24 21:40 150x.1.trimReads.inputNoTrimReads.gp
-rw-r----- 1 dxk800 xf1    0 Oct 24 21:40 150x.1.trimReads.inputNoTrimReads.lg.png
-rw-r----- 1 dxk800 xf1  31M Oct 24 21:40 150x.1.trimReads.inputReads.dat
-rw-r----- 1 dxk800 xf1  450 Oct 24 21:40 150x.1.trimReads.inputReads.gp
-rw-r----- 1 dxk800 xf1 5.0K Oct 24 21:40 150x.1.trimReads.inputReads.lg.png
-rw-r----- 1 dxk800 xf1 1.7K Oct 24 21:40 150x.1.trimReads.inputReads.sm.png
-rw-r----- 1 dxk800 xf1 371M Oct 24 21:40 150x.1.trimReads.log
-rw-r----- 1 dxk800 xf1  16K Oct 24 21:41 150x.1.trimReads.outputDeletedReads.dat
-rw-r----- 1 dxk800 xf1  482 Oct 24 21:41 150x.1.trimReads.outputDeletedReads.gp
-rw-r----- 1 dxk800 xf1 4.8K Oct 24 21:41 150x.1.trimReads.outputDeletedReads.lg.png
-rw-r----- 1 dxk800 xf1 1.8K Oct 24 21:41 150x.1.trimReads.outputDeletedReads.sm.png
-rw-r----- 1 dxk800 xf1  280 Oct 24 21:41 150x.1.trimReads.outputNoOvlReads.dat
-rw-r----- 1 dxk800 xf1  474 Oct 24 21:41 150x.1.trimReads.outputNoOvlReads.gp
-rw-r----- 1 dxk800 xf1 5.7K Oct 24 21:41 150x.1.trimReads.outputNoOvlReads.lg.png
-rw-r----- 1 dxk800 xf1 1.8K Oct 24 21:41 150x.1.trimReads.outputNoOvlReads.sm.png
-rw-r----- 1 dxk800 xf1  31M Oct 24 21:40 150x.1.trimReads.outputTrimmedReads.dat
-rw-r----- 1 dxk800 xf1  482 Oct 24 21:40 150x.1.trimReads.outputTrimmedReads.gp
-rw-r----- 1 dxk800 xf1 5.1K Oct 24 21:41 150x.1.trimReads.outputTrimmedReads.lg.png
-rw-r----- 1 dxk800 xf1 1.7K Oct 24 21:41 150x.1.trimReads.outputTrimmedReads.sm.png
-rw-r----- 1 dxk800 xf1    0 Oct 24 21:41 150x.1.trimReads.outputUnchangedReads.dat
-rw-r----- 1 dxk800 xf1  490 Oct 24 21:41 150x.1.trimReads.outputUnchangedReads.gp
-rw-r----- 1 dxk800 xf1    0 Oct 24 21:41 150x.1.trimReads.outputUnchangedReads.lg.png
-rw-r----- 1 dxk800 xf1 1.1K Oct 24 21:41 150x.1.trimReads.stats
-rw-r----- 1 dxk800 xf1  12M Oct 24 21:41 150x.1.trimReads.trim3.dat
-rw-r----- 1 dxk800 xf1  428 Oct 24 21:41 150x.1.trimReads.trim3.gp
-rw-r----- 1 dxk800 xf1 4.6K Oct 24 21:41 150x.1.trimReads.trim3.lg.png
-rw-r----- 1 dxk800 xf1 1.6K Oct 24 21:41 150x.1.trimReads.trim3.sm.png
-rw-r----- 1 dxk800 xf1 788K Oct 24 21:41 150x.1.trimReads.trim5.dat
-rw-r----- 1 dxk800 xf1  428 Oct 24 21:41 150x.1.trimReads.trim5.gp
-rw-r----- 1 dxk800 xf1 4.6K Oct 24 21:41 150x.1.trimReads.trim5.lg.png
-rw-r----- 1 dxk800 xf1 1.6K Oct 24 21:41 150x.1.trimReads.trim5.sm.png
-rw-r----- 1 dxk800 xf1   77 Oct 25 09:31 150x.2.splitReads.err
-rw-r----- 1 dxk800 xf1    0 Oct 25 09:31 150x.2.splitReads.log
```

Hope you can help me as this assembly was going well until this point!

cheers
David

**Comment by skoren** [comment]
The trimming step is single core so it can take some time with a lot of reads or high coverage. It doesn't output detailed logging. Longest runtime on this step I've ever seen is a day. So I would let it run and it should complete.

**Comment by dkainer** [comment]
I see. Thanks for the response! 
Does increased memory make a difference at this step?

**Comment by skoren** [comment]
Memory increase wouldn't help because it's mostly streaming from disk. Any updates on this, I assume this has completed?

**Comment by JifengTang** [comment]
I have a similar problem
SplitReads is running over 8 days and still running for a genome size of 700m and about 100x raw input.
The process is using 100% cpu and 500m memory. 
I have never seem the problem before even for a larger genome. 
Is the process still ok? How to check that?

Thank you very much.

**Comment by dkainer** [comment]
my SplitReads did complete after about 2 days but I had no way of estimating the progress

**Comment by JifengTang** [comment]
Then it looks like my SplitReads is stuck. Hope the developers can help on this.

**Comment by skoren** [comment]
I've never seen this step get stuck, it's not multi-threaded so it's not clear why it would have an issue unless you are out of disk but I've also not seen it take over a couple of days. If it's getting CPU it is likely still making progress. The log is only written to when a read is split which is why it can run a long time before logging when the majority of reads reads are not chimeric.

Is your genome very repetitive? How much coverage did you end up with after correction? How big is the asm.ovlStore folder in the trimming directory? That is the primary determinant of the runtime.

**Comment by JifengTang** [comment]
I have more than 50T free disk.  It is not out of disk. 
It is a diploid genome possibly highly repetitive with a high degree of heterozygosity. The raw read coverage is about 94x on a haploid genome size of 700M
After correction is about 74x for haploid genome size of 700M.
The asm.ovlStore folder is 15T 
That was generated using canu source code from 29th sep 2017.

The settings I used " genomeSize=700m rawErrorRate=0.3 correctedErrorRate=0.04
corMhapSensitivity=normal corMinCoverage=0 corOutCoverage=200 batThreads=48
batMemory=200 maxThreads=128 maxMemory=240 ovsMemory=100g useGrid=1
gridOptions="-r y -V -p 0 " gridEngineMemoryOption="-l mem_free=MEMORY"
gridEngineThreadsOption="-pe smp THREADS" -pacbio-raw

I am thinking to restart the assembly with corrected reads using canu1.6 official release and appropriate settings.
 -trim-assemble -pacbio-corrected ams.correctedReads.fasta.gz
Can you recommend some settings?

Because I got 74x corrected reads, it may be too much, I can start with raw reads using more strict setting. Can you recommend some settings?
Thank you very much.

**Comment by skoren** [comment]
The issue is probably your ``corMinCoverage=0``` setting. We typically only use this for <30x of coverage. This puts the main burden of trimming data onto the trim step rather than the correction step and with 74x of data it's a lot of trimming. I'd run without that setting and see what you get.

**Comment by skoren** [comment]
Inactive, added a future feature to make this code multi-threaded.

**Comment by lamz138138** [comment]
Hi, @skoren 

The splitReads of mine is running over four days (you can image the genome is human, and raw coverage is 60X), is it any other methods could be used to check whether it is right, and when it would be finished?

I had traced the program with "strace -p PID", it seemed OK, but I don't think it wouldn't take four days, what's your experience in running human data?

Best regards!

**Comment by skoren** [comment]
SplitReads can take a few days, it depends on the number of overlaps (size of the asm.ovlStore in trimming), see the discussion on this issue above. I would guess your genome is more repetitive than human or you have more corrected output coverage than the default (e.g. with corMinCoverage=0)

**Comment by lamz138138** [comment]
Hi，thanks for your reply! @skoren 

I run with default parameter, and I didn't find the value of corMinCoverage from log. Anyway, I confirm it is running with "strace -p PID -o output.log". I can find following information in log, so it is in processing files, 

Hope this would helpful to others!

Best regards!

```
 47514 read(6, "\305\1\240\355\237\4\263\0\7\340\305\0\365$@\315\1\270\20\0\0171\340q\270\4\263\0\6<\202\0"..., 1048576) = 1048576
47514 read(6, "\3\3302\0\n\0\300\214A\234\316\0\10@\205\0\226 `\223\4p\t\0rF\300\257r\234\316\0"..., 1048576) = 1048576
47514 read(6, "\2614\0\22\3<\t\0z\1\200\34`\322\351\0\10\f\204\0\221 \300t\4T\r\0\t\21\340Q"..., 1048576) = 849072
47514 read(6, "", 1048576)              = 0
47514 read(6, "", 1048576)              = 0
47514 close(6)                          = 0
47514 munmap(0x2b7cff300000, 1048576)   = 0
47514 stat("../canu.ovlStore/0341", {st_mode=S_IFREG|0644, st_size=17691983520, ...}) = 0
47514 open("../canu.ovlStore/0341", O_RDONLY) = 6
47514 stat("../canu.ovlStore/0341", {st_mode=S_IFREG|0644, st_size=17691983520, ...}) = 0
47514 fstat(6, {st_mode=S_IFREG|0644, st_size=17691983520, ...}) = 0
```
