### ISSUE TITLE
error running Canu (Failed with exit code 134)

### ISSUE THREAD

**Issue by LianaKafetzopoulou** [marbl/canu#683]
Ran the command and had the below issue but not really sure where to look and what to solve as I am not sure what the problem is. Canu is newly installed on this machine and I have never managed to get it to work on this computer before. Any help is much appreciated

EDV-ID318-Virologie:Documents virologie$ canu-1.6/*/bin/canu -d barcode02 -p barcode02 genomeSize=15000 minReadLength=200 minOverlapLength=50 gnuplotTested=true -nanopore-raw ./Final_FASTQ_pass_ebov/barcode02.fastq
--   Reason: image not found
--
-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
-- 
-- Read and contig alignments during correction, consensus and GFA building use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
--   Li H.
--   Minimap and miniasm: fast mapping and de novo assembly for noisy long sequences.
--   Bioinformatics. 2016 Jul 15;32(14):2103-10.
--   http://doi.org/10.1093/bioinformatics/btw152
-- 
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_151' (from 'java').
-- Detected 4 CPUs and 16 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |  algorithm
--        -------  ------  --------   --------  -----------------------------
-- Local: meryl      8 GB    4 CPUs x   1 job   (k-mer counting)
-- Local: cormhap    6 GB    4 CPUs x   1 job   (overlap detection with mhap)
-- Local: obtovl     8 GB    4 CPUs x   1 job   (overlap detection)
-- Local: utgovl     8 GB    4 CPUs x   1 job   (overlap detection)
-- Local: cor        8 GB    2 CPUs x   2 jobs  (read correction)
-- Local: ovb        4 GB    1 CPU  x   4 jobs  (overlap store bucketizer)
-- Local: ovs        8 GB    1 CPU  x   4 jobs  (overlap store sorting)
-- Local: red        2 GB    4 CPUs x   1 job   (read error detection)
-- Local: oea        1 GB    1 CPU  x   4 jobs  (overlap error adjustment)
-- Local: bat       16 GB    4 CPUs x   1 job   (contig construction)
-- Local: cns       16 GB    4 CPUs x   1 job   (consensus)
-- Local: gfa        8 GB    4 CPUs x   1 job   (GFA alignment and processing)
--
-- Found Nanopore uncorrected reads in the input files.
--
-- Generating assembly 'barcode02' in '/Users/virologie/Documents/barcode02'
--
-- Parameters:
--
--  genomeSize        15000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1440 ( 14.40%)
--    utgOvlErrorRate 0.1440 ( 14.40%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1440 ( 14.40%)
--    utgErrorRate    0.1440 ( 14.40%)
--    cnsErrorRate    0.1920 ( 19.20%)
--
--
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Wed Oct 25 14:29:48 2017 with 720.467 GB free disk space

    cd correction
    /Users/virologie/Documents/canu-1.6/Darwin-amd64/bin/gatekeeperCreate \
      -minlength 200 \
      -o ./barcode02.gkpStore.BUILDING \
      ./barcode02.gkpStore.gkp \
    > ./barcode02.gkpStore.BUILDING.err 2>&1
sh: line 4: 20145 Abort trap: 6           /Users/virologie/Documents/canu-1.6/Darwin-amd64/bin/gatekeeperCreate -minlength 200 -o ./barcode02.gkpStore.BUILDING ./barcode02.gkpStore.gkp > ./barcode02.gkpStore.BUILDING.err 2>&1

-- Finished on Wed Oct 25 14:29:48 2017 (lickety-split) with 720.467 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 134.  (rc=34304)
ERROR:

ABORT:
ABORT:   Reason: image not found
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   gatekeeper store exists, but contains no reads.
ABORT:

**Comment by skoren** [comment]
Image not found means your system is missing a library Canu was compiled with. Download the release source and build it locally rather than using the binary distribution.

**Comment by LianaKafetzopoulou** [comment]
I was afraid that would be the answer! I will try and see if I manage to build it locally, Thanks

**Comment by LianaKafetzopoulou** [comment]
Easier than I thought! Build it locally and is currently running, will monitor it but seems to be ok now. Problem resolved. Thanks for your quick responce
