### ISSUE TITLE
retrieve trimmedReads.fasta and correctedReads.fasta

### ISSUE THREAD

**Issue by jacqueslagnel** [marbl/canu#686]
Hello,
I ran canu 1.6 and I didn't get the 2 output files *.trimmedReads.fasta.gz and *.correctedReads.fasta.gz
How can I retrieve these files from my run:

canu -d outs \
-p HarR \
minReadLength=1000 \
genomeSize=350m \
-nanopore-raw ont.fasta

thank you in advance
Jacques

**Comment by skoren** [comment]
Are you sure you are running 1.6 release and the assembly completed? What does ```canu -version``` report? What was the full output of the Canu command (stdout/stderr)?

**Comment by brianwalenz** [comment]
At present, the only way to get both of these is to use 'saveReads=true'.  This must be supplied from the start of the assembly though.

To get the trimmed reads, you can use `gatekeeperDumpFASTQ -G *gkpStore -o - > reads.fastq` (see command line usage for other options).  The untrimmed reads (aka correctedReads.fasta) are stored and it will eventually be possible to retrieve them, just not yet.

**Comment by skoren** [comment]
I've made the default to dump the reads. If you update, re-run you'd get the reads (assuming you were running tip). You can also dump the trimmed reads @brianwalenz suggested above.

**Comment by fishercera** [comment]
While this issue is closed, I want to leave an update for anyone else who is looking for this info: 
it seems that as of v.2.1 at least, the `gatekeeperDumpFASTQ` has been replaced with `sqStoreDumpFASTQ`

Usage:
```
usage: sqStoreDumpFASTQ [...] -o out-prefix -g seqStore
  -S seqStore
  -o out-prefix       write files out-prefix.(libname).fastq, ...
                      if out-prefix is '-', all sequences output to stdout
                      if out-prefix ends in .gz, .bz2 or .xz, output is compressed

  -fastq              output is FASTQ format (with extension .fastq, default)
                      (note that QVs are not stored, and are invalid)

  -fasta              output is FASTA format (with extension .fasta)

  -nolibname          don't include the library name in the output file name

  -noreadname         don't include the read name in the sequence header.  header will be:
                        '>original-name id=<seqID> clr=<bgn>,<end>   with names
                        '>read<seqID> clr=<bgn>,<end>                without names

 -reverse             Dump the reverse-complement of the read.

  -l id               output only read in library number 'id'
  -r id[-id]          output only the single read 'id', or the specified range of ids

 The default is to dump the latest version of each read.  You can force it to dump:
  -raw                Dump raw reads.
  -corrected          Dump corrected reads.

  -trimmed            Dump the trimmed version of the raw/corrected read.
  -compressed         Dump the compressed version of the raw/corrected read.
  -normal             Dump the uncompressed version of the raw/corrected read.
                        (for stores that are by default compressing homopolymers)
```

* a small error: usage should actually be 
` sqStoreDumpFASTQ [...] -o out-prefix -S seqStore ` --  as noted in the option definitions, it is -S and not -g.

**Comment by brianwalenz** [comment]
Thanks for the proof-reading!  I fixed the usage.

The rename happened in version 1.8, October 2018.
