### ISSUE TITLE
Setting walltime and queue options for Canu (PBS/Torque scheduler)

### ISSUE THREAD

**Issue by aviantask** [marbl/canu#69]
Hi,

I'm running Canu on our cluster using the following script. Kindly note that my research group has limitations to run our jobs on the queue named 'cegs'. Here is the script I'm using

```
#!/bin/bash

#PBS -l nodes=4:ppn=6
#PBS -l walltime=300:00:00
#PBS -l mem=512000mb,pmem=128000mb,vmem=512000mb
#PBS -q cegs

~/software/canu-1.1/Linux-amd64/bin/canu -p asm -d CDCFrontier_canu1.1 genomeSize=738m corMhapSensitivity=high corMinCoverage=2 errorRate=0.035 minOverlapLength=499 corMaxEvidenceErate=0.3 -pacbio-raw reads_CDC.fq  maxMemory=512000m maxThreads=24
```

Once I submit the job, Canu submits the jobs like 'meryl' etc. to 'main' or other queues, like following --

```
                                                                                                                  Req'd    Req'd                Elap
Job ID               Username    Queue    Jobname  SessID  NDS   TSK   Memory   Time     S          Time
-------------------- -----------       --------    --------------  -----        ------ ------     --------- - --------
14420[].hpc-pb  aviantask    quick    meryl_asm   --              1     12       23gb     00:30:00  R      00:30:0
14421.hpc-pbs  aviantask    main     canu_asm    --              1      1        4gb       00:30:00  Q           --
```

This eventually leads to my jobs being aboorted due to insufficient walltime , email from the cluster below --
```
PBS Job Id: 14420792[1].hpc-pbs...edu
Job Name:   meryl_asm-1
Exec host:  hpc1118/0+hpc1118/1+hpc1118/2+hpc1118/3+hpc1118/4+hpc1118/5+hpc1118/6+hpc1118/7+hpc1118/8+hpc1118/9+hpc1118/10+hpc1118/11
Aborted by PBS Server 
Job exceeded its walltime limit. Job was aborted
See Administrator for help
Exit_status=-11
resources_used.cput=03:08:25
resources_used.mem=23554512kb
resources_used.vmem=27651996kb
resources_used.walltime=00:30:25
```

I was looking into GridEngine settings to put in defaults, but I could not find any for queue or walltime. What can I do to fix this?

Thanks!

**Comment by skoren** [comment]
There are grid options for each step that will be passed as well as global grid options which will apply to all jobs. If you run
```
canu -options |grep gridOptions
gridOptions                             Grid engine options applied to all jobs
gridOptionsExecutive                    Grid engine options applied to the canu executive script
gridOptionsJobName                      Grid jobs job-name suffix
gridOptionsbat                          Grid engine options applied to unitig construction jobs
gridOptionscns                          Grid engine options applied to unitig consensus jobs
gridOptionscor                          Grid engine options applied to read correction jobs
gridOptionscormhap                      Grid engine options applied to mhap overlaps for correction jobs
gridOptionscormmap                      Grid engine options applied to mmap overlaps for correction jobs
gridOptionscorovl                       Grid engine options applied to overlaps for correction jobs
gridOptionsmeryl                        Grid engine options applied to mer counting jobs
gridOptionsobtmhap                      Grid engine options applied to mhap overlaps for trimming jobs
gridOptionsobtmmap                      Grid engine options applied to mmap overlaps for trimming jobs
gridOptionsobtovl                       Grid engine options applied to overlaps for trimming jobs
gridOptionsoea                          Grid engine options applied to overlap error adjustment jobs
gridOptionsovb                          Grid engine options applied to overlap store bucketizing jobs
gridOptionsovs                          Grid engine options applied to overlap store sorting jobs
gridOptionsred                          Grid engine options applied to read error detection jobs
gridOptionsutgmhap                      Grid engine options applied to mhap overlaps for unitig construction jobs
gridOptionsutgmmap                      Grid engine options applied to mmap overlaps for unitig construction jobs
gridOptionsutgovl                       Grid engine options applied to overlaps for unitig construction jobs
```

So if you want all canu steps to run in your queue, set gridOptions="-l walltime=300:00:00 -q cegs" and they will be appended to all submit commands.

**Comment by aviantask** [comment]
I appended the gridOptions="-l walltime=300:00:00 -q cegs" to my command line , but I am getting the very same error/problem as before. Jobs are getting submitted to the main/quick queue instead of the 'cegs' queue and with 30 min walltime.

**Comment by jmartinsjrbr** [comment]
#PBS -S/bin/bash                                                                                                                 
#PBS -N CANU-PACBIO                                                                                                            
#PBS -l nodes=1:ppn=20,walltime=360:00:00,vmem=250gb                                                                             
#PBS -M martins.jr.bio@gmail.com                                                                                               
#PBS -mbea                                                                                                                      
 #PBS -o /work/xylella/jocksmartinsjr/montagens/FB7v2_PacBio-JM/canu/canu-run.out                                                 
 #PBS -e /work/xylella/jocksmartinsjr/montagens/FB7v2_PacBio-JM/canu/canu-run.err                                                 
 #PBS  -V                                                                                                                        
 #PBS -W group_list=xylella


Is it possible to pass all pbs options above to gridOptions flag?

Best regards,
Joaquim

**Comment by skoren** [comment]
You can pass any number of options to the gridOptions flag, in quotes and they will be passed through to the scheduler:

```
gridOptions="-V -W group_list=xylella -M email -mbea"
```
However, I wouldn't specify cores (nodes,ppn) since Canu doesn't run as a monolithic process but instead submits different stages to the grid. Different stages will vary in their CPU usage and it will automatically request the appropriate cores and memory. You can leave wall clock and vmdm if you want. It also isn't necessary to specify the output and err files. Canu again will specify those for each stage it submits to the grid.

In future, please avoid commenting on closed issues and open a new one instead. It is harder for us to notice the comments on issue which are not open.
