### ISSUE TITLE
Where is final file go? 

### ISSUE THREAD

**Issue by SashaMeow** [marbl/canu#690]
I run canu v1.6 +115 changes.
I'm trying to run a correction on nanopore reads. However correction starts and finishes, but I don't see final file that contains all corrected reads. 
released version of canu 1.6 just shuts off the computer in the mid way. 
Last time the correction was completed correctly when I used canu 1.6 +93 changes (if I remeber correctly)

**Comment by skoren** [comment]
See issue #686, you need to specify saveReads=true. I switched the default to true since several people have asked about this.
