### ISSUE TITLE
canu1.6 from master branch on 26th oct 2017 did not produce correct reads fasta file and directly went to trimming step

### ISSUE THREAD

**Issue by JifengTang** [marbl/canu#692]
I used canu1.6 from master branch on 26th oct 2017 did not produce correct reads fasta file and directly went to trimming step
I followed https://github.com/marbl/canu/issues/680 and tried "saveReads=true". It did not produce fasta file and still went to trimming.
It may be due to I did not start the pipeline from beginning.
I just deleted trimming folder and restarted canu.

I searched the source code and found "CorrectReads.pm" contains some codes related to that (see the below code).

Does someone have a script to fetch fasta reads from cns files?

    my $Ncns     = 0;
    my $Nerr     = 0;
    my $Nlog     = 0;

    if (getGlobal("saveReadCorrections") != 1) {
        print STDERR "--\n";
        print STDERR "-- Purging correctReads output after loading into stores.\n";

        open(F, "< $path/corjob.files") or caExit("can't open '$path/corjob.files' for reading: $!", undef);
        while (<F>) {
            chomp;

            if (m/^(.*)\/results\/0*(\d+).cns$/) {
                my $ID6 = substr("00000" . $2, -6);
                my $ID4 = substr("000"   . $2, -4);
                my $ID0 = $2;

                if (-e "$1/results/$ID4.cns") {
                    $Ncns++;
                    unlink "$1/results/$ID4.cns";
                }
                if (-e "$1/results/$ID4.err") {
                    $Nlog++;
                    unlink "$1/results/$ID4.err";
                }

                if (-e "$1/correctReads.$ID6.out") {
                    $Nlog++;
                    unlink "$1/correctReads.$ID6.out";
                }
                if (-e "$1/correctReads.$ID0.out") {
                    $Nlog++;
                    unlink "$1/correctReads.$ID0.out";
                }

            } else {
                caExit("unknown correctReads job name '$_'\n", undef);
            }
        }
        close(F);

        print STDERR "-- Purged $Ncns .cns outputs.\n"                  if ($Ncns > 0);
        print STDERR "-- Purged $Nerr .err outputs.\n"                  if ($Nerr > 0);
        print STDERR "-- Purged $Nlog .out job log outputs.\n"          if ($Nlog > 0);
    } else {
        print STDERR "--\n";
        print STDERR "-- Purging correctReads output disabled by saveReadCorrections=true.\n"  if (getGlobal("saveReadCorrections") == 1);
    }

**Comment by skoren** [comment]
See issues #690 and #686. This is the expected behavior. Currently, saveReads must be specified from the start, if you erase the trimming folder, there are still corrected reads in the gatekeeper store Canu can resume from. You can dump the trimmed reads with the gatekeeperDumpFASTQ command. Without trimmed data (if you never completed trimming), it will dump the corrected reads. The default in the latest tip is to dump the reads by default. 

In general, I wouldn't recommend running on the latest tip unless you have a specific issue/error with the release as it has not undergone testing as much as a release.
