### ISSUE TITLE
I cannot find the corrected file

### ISSUE THREAD

**Issue by Fyphia** [marbl/canu#694]
Hello,

I've just tried to learn how to use canu.
As told in the "Quick Start", I got the two files by follow two commands:
```
curl -L -o pacbio.fastq http://gembox.cbcb.umd.edu/mhap/raw/ecoli_p6_25x.filtered.fastq
```
and
```
curl -L -o oxford.fasta http://nanopore.s3.climb.ac.uk/MAP006-PCR-1_2D_pass.fasta
```
And then I tried the command:
```
./canu -p ecoli -d ecoli genomeSize=4.8m -pacbio-raw pacbio.fastq
```

As a result, I could find these folders and files in the floder named "ecoli":

folders:
ecoli.gkpStore
correction.html.files
correction
canu-scripts
canu-logs

files:
ecoli.report
ecoli.gkpStore.err
correction.html
ecoli.gkpStore.gkp

Those were all in the "ecoli" folder. I count not find any thing like "*.correctedReads.fasta.gz" or  "*..trimmedReads.fasta.gz" as I expected.

Is there any solution that help me with this issue?

Thanks a lot!

Fyphia

**Comment by brianwalenz** [comment]
Assuming you're running a late version of Canu, those files were (inadvertently?) disabled.  You can enable them with saveReads=true.

If not, and that's _all_ Canu generated, it failed somewhere.  Was this a grid-enabled run?  Check for errors in canu-scripts; otherwise check for errors from the canu command itself.

**Comment by Fyphia** [comment]
Thanks for your comment.

My canu version report is:
```
Canu snapshot v1.6 +118 changes (r8530 87eeba06b16aefcaca80b6d4514bcdc831d795ab )
```
I tried to use "saveReads=true" like:
```
./canu -p ecoli -d ecoli saveReads=true genomeSize=4.8m -pacbio-raw pacbio.fastq
```
Is that right?
However the output was still as same as previous.

I also tried another version of canu: 
```
Canu 1.6
```
In this version , 
```
 ERROR:  Parameter 'saveReads' is not known.
```
What should I do to solve these issues?

Thanks!

**Comment by Fyphia** [comment]
And there is also a canu 1.4 version in my server . How can I get the corrected reads and trimmed reads by the 1.4 version ? I can only find an option "saveReadCorrections" which is discribed as "Save intermediate read correction files, almost never a good idea" and I don't know how to make it helpful.

**Comment by skoren** [comment]
saveReads is only in the tip, older versions do not require any parameter to save the reads. Generally, you should use a release version not a tip as the tip has not been tested as much as a release.

What is the full output of your canu run command? Most likely the job isn't finished yet.

**Comment by skoren** [comment]
Inactive, the tip now keeps the corrected reads by default and re-running with saveReads=true on an existing folder will create the fasta outputs. All release versions output the fasta always.

**Comment by lucky295** [comment]
Hello,

I would like to know on the above canu execution with a customized way. So, Is it possible to execute the above canu command with s3 data paths. Like something bellow like this..

canu -p ecoli -d s3://canu-job/data genomeSize=4.8m -pacbio-raw s3://canu-job/pacbio.fastq. 

Thanks in advance,
Lucky.

**Comment by skoren** [comment]
Please don't comment on old unrelated issues. 

No, there is no built-in support for s3/remote fetching in Canu. It uses standard file system libraries which won't understand those paths. It is possible to run Canu on AWS using StarCluster with a "shared" filesystem. For native distributed runs (see #1099) you'd have to add code to fetch/store the files as Canu runs.
