### ISSUE TITLE
Running Canu Separately (-correct, -trim and -assembly) and correctedErrorRate

### ISSUE THREAD

**Issue by CelinePB** [marbl/canu#695]
Hello, 

I am trying different parameters of canu on my datasets, and I wanted to test different correctedErrorRate. 
But I don't understand if this parameter is use during each of the three steps (correct, trim and assemble) or only in trim and assemble, or only in assemble?

the thing is that the correct step is by far the longest and the one requiring the most storage space, and if I can skip this step to test different ErrorRates it would be much more efficient for me.

To be clear, I want to obtain the best results, so if it change something to correct the reads with this parameter I would like to be aware of it!
Thank you in advance!
All the best, 
Celine

**Comment by skoren** [comment]
correctedErrorRate only affects the trimming and assembly stage not the correction stage so you can test it without re-running correction.

**Comment by CelinePB** [comment]
Amazing!
Thank you very much for your quick (and efficient) answer! :)

All the best, 
Celine
