### ISSUE TITLE
Reads are not corrected

### ISSUE THREAD

**Issue by kanute** [marbl/canu#698]
Hello,

I am running Canu to assemble a 95 MB eukaryotic genome from PacBio reads (10-15 kb reads, almost 80x coverage). The sequence data is very polymorphic (DNA from >300 pooled individuals, with roughly 1 SNP in 80 bp).

I run Canu 1.6 on a grid (slurm) using the following command:

```
canu \
-p J_12th \
-d J_12th \
corOutCoverage=100 \
MhapSensitivity=normal \
gridOptions='--time=240:00:00' \
genomeSize=95m \
-pacbio-raw Reads.fq
```

The assembly finishes, but along the way seems to fail to produce any corrected reads, claiming that there are 0 input bases:

```
CORRECTION INPUTS:
-----------------
696492 (input reads)
0 (input bases)

CORRECTION OUTPUTS:
-----------------
696492 (reads that failed to generate any corrected bases)
0 (corrected read pieces)
0 (corrected bases)

PIECES PER READ:
---------------
0 pieces: 696492


```

The correction layout seems normal:

 ```
                                     --------corrected---------  ----------rescued----------
                          evidence                     expected                     expected
category                     reads            raw     corrected            raw     corrected
-------------------- -------------  ------------- -------------  ------------- -------------
Number of Reads             891381         696492        696492              0             0
Number of Bases         6901894138     5901518831    5115645814              0             0
Coverage                    72.652         62.121        53.849          0.000         0.000
Median                        6867           8059          6869              0             0
Mean                          7742           8473          7344              0             0
N50                          10863          11155         10756              0             0
Minimum                       1000           1000             1              0             0
Maximum                     115357         115357         71330              0             0

                     --------uncorrected--------
                                        expected
category                       raw     corrected
-------------------- ------------- -------------
Number of Reads             276357        276357
Number of Bases         1061927567             0
Coverage                    11.178         0.000
Median                        2408             0
Mean                          3842             0
N50                           7674             0
Minimum                          0             0
Maximum                      51772             0

Maximum Memory          1589734814
```
What can I do about that?

And as a side note: When corMhapSensitivity is NOT set (and probably auto-determined as "low" given the 80x coverage in my data), the corOutCoverage parameter does not seem to have any effect on the fraction of reads chosen for correction (I tried 80, 100 and 999). Only after changing corMhapSensitivity to “normal” or “high” more reads are chosen for correction (but still not corrected).

Thanks for any help!

**Comment by skoren** [comment]
Based on the output you're running the tip, what's the canu version? There were times during some large changes when Canu wasn't producing corrected reads due to bugs a few months back. I'd suggesting running with Canu 1.6 release instead to be safe. Also, what is the full output from the Canu run, it should give some information on the overlaps found.

**Comment by kanute** [comment]
The version is Canu snapshot v1.6 +61 changes (r847386f53cff1401ce4229d2a579ed093afe68751e0a).
Would you recommend a different version?

Meanwhile I have re-run the assembly with saveReads=true. I get a file with corrected reads, but their IDs are all "_". I also get a file with trimmed reads, which have correct IDs. For a test I blasted raw, corrected and trimmed reads against my existing Illumina assembly, and they indeed are raw, corrected and trimmed reads. So it seems like only the report file was wrong in reporting 0 bases in the corrected reads.

**Comment by skoren** [comment]
That's definitely in the middle of some large changes so I'd recommend using the release 1.6 version. You can let the asm finish if you actually do have reads as a comparison point.
