### ISSUE TITLE
Canu 1.6 from bioconda

### ISSUE THREAD

**Issue by apredeus** [marbl/canu#699]
Hello all, 

I've ran into compatibility issues when using canu installed from bioconda. Most of the job completed successfully, but the consensus generation failed with the following message: 

>~/miniconda2/libexec/utgcns: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ~/miniconda2/libexec/utgcns

Seems like bioconda release was not build consistently? I know, I should have just used the binaries.

**Comment by skoren** [comment]
Yeah, it seems bioconda build part of the package with a newer gcc than you have. Not sure why that only happened in consensus though. We don't control the bioconda install so I would submit an issue there or just use the binary we have posted which are compiled using an old libc.

**Comment by skoren** [comment]
Looking at the bioconda recipe (https://github.com/bioconda/bioconda-recipes/blob/master/recipes/canu/build.sh) it seems like it is built locally so perhaps the machine it was installed on doesn't match the machine it is running on? Either way the distributed binaries should work on a reasonable linux system.
