### ISSUE TITLE
java can't allocate metaspace

### ISSUE THREAD

**Issue by GeoMicroSoares** [marbl/canu#701]
Hello there,

(following up on this <https://github.com/marbl/canu/issues/390#issuecomment-343670596>)

Using canu 1.6 in an SGE environment:
```
canu -p algae_pass -d algae_pass genomeSize=1g -nanopore-raw algae_pass.fastq corMinCoverage=0 corOutCoverage=all corMhapSensitivity=high correctedErrorRate=0.105 corMaxEvidenceCoverageLocal=10 corMaxEvidenceCoverageGlobal=10 gridEngineMemoryOption="-l mem_free=MEMORY" gridEngineThreadsOption="-pe multithread THREADS" gnuplotTested=true java='/cm/shared/apps/java/jdk1.8.0_40/bin/java -XX:CompressedClassSpaceSize=300m' stopOnReadQuality=false merylMemory=10 merylThreads=1 cormhapMemory=10 minReadLength=500
```
i.e. removing the h_vmem parameter from my command, it now seems that canu can't run like it was before due to a java issue.

From canu.out:
```
ERROR:  mhap overlapper requires java version at least 1.8.0; you have unknown (from '/cm/shared/apps/java/jdk1.8.0_40/bin/java -XX:CompressedClassSpaceSize=300m').
ERROR:  '/cm/shared/apps/java/jdk1.8.0_40/bin/java -XX:CompressedClassSpaceSize=300m -showversion' reports:
ERROR:    'Error occurred during initialization of VM'
ERROR:    'Could not allocate metaspace: 314572800 bytes'
```

Wasn't doing this before, as it appeared to be a memory issue.

Any help?

Thanks!

**Comment by skoren** [comment]
I think it is a memory issue with your JVM not being configured properly. All the options being passed (```-XX:CompressedClassSpaceSize=300m```) aren't from Canu but your environment. Canu is actually requesting 1gb of memory (```-Xmx1g -showversion ``` from line 983 in Defaults.pm) but those options are not being used. Either way, it's a JVM/environment issue not Canu. 

Make sure you can run the JVM on SGE on a submitted job with 1gb of memory or see how much memory it is using on your config and change gridOptionsExecutive to request more memory to match your JVM config.

**Comment by GeoMicroSoares** [comment]
Thanks @skoren! How can I check how much memory the JVM is using on my head node and my config?

**Comment by skoren** [comment]
Run java and watch top or run it with /usr/bin/time which reports max vm. You could also just try increasing memory for the program (```gridOptionsExecutive="-l mem_free=4g"```) and unsetting any JAVA environment variables (I'd guess you have ```_JAVA_OPTIONS``` set which overrides any other settings).

**Comment by GeoMicroSoares** [comment]
Still unsure to what this might be...
Ran gridOptionsExecutive="-l mem_free=4g" up until 100g and still got the same output from precompute.*.out (last few lines):
```
Reading in filter file ../../0-mercounts/algae_pass.ms16.frequentMers.ignore.gz.
Read in values for repeat 12768 and 0
Warning, k-mer filter file has zero elements.
Initializing
Trying size 12768 and it was successfull
Initialized
Time (s) to read filter file: 0.32485719900000004
Read in k-mer filter for sizes: [16]
Processing FASTA files for binary compression...
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 32744 bytes for ChunkPool::allocate
[thread 140732861048576 also had an error]
# An error report file with more information is saved as:
# /ibers/ernie/home/ans74/algae/algae_pass/correction/1-overlapper/blocks/hs_err_pid7267.log
#
# Can't open file to dump replay data. Error: Cannot allocate memory
Mhap failed.
```
Any other tweaks you think might work?

Thanks!

**Comment by skoren** [comment]
You shouldn't be tweaking Xmx yourself, Canu auto-sets it to what is needed at runtime. Are there still JAVA config variables in your environment? 

What are the resources/memory Canu auto-configures for the java steps? Try decreasing the threads from that (using ```cormhapThreads=`XX``) setting XX to half your current value and increasing the memory reserved (using ```gridOptionscormhap="-l mem_free=XX```) setting it to be 2-5G more than the default chosen and make sure if Xmx is specified in an environment variable it is at least what Canu auto-configures for. Also, confirm mem_free is reserving memory on your system (```qconf -sc|grep mem_free```) it should have  YES in the 6th column.
