### ISSUE TITLE
canu GFA possible incorrect header format 

### ISSUE THREAD

**Issue by cokelaer** [marbl/canu#706]
FYI

With canu version 1.6, I created an assembly and everything worked fine. One output is a contigs.gfa file but I noticed  that the header is not correct. This is not a big deal, but the GFA specs for version 1 (https://github.com/GFA-spec/GFA-spec/blob/master/GFA1.md ) or 2 indicates that the version should be a number. In the contigs.gfa created by Canu, :

```
H	VN:Z:bogart/edges
S	tig00000001	*	LN:i:4126934
L	tig00000001	+	tig00000001	+	55M1I32M1D10M
...
```

we can see that the VN:Z: field is followed by some text. It should be 1.0 or 2.0 I may be wrong but I believe this is not correct. This prevent this GFA from being parsed by validator.

**Comment by brianwalenz** [comment]
Hmmm, thanks!  I must have mixed up my file formats, thinking VN was the name of the program that created the file.  I'll get a patch for this in the near future.

**Comment by brianwalenz** [comment]
Fixed!
