### ISSUE TITLE
About utgRepeatConfusedBP

### ISSUE THREAD

**Issue by jhtrujillo** [marbl/canu#708]
Hi. 
Could you explain in more detail the function of the parameter utgRepeatConfusedBP?
Thank you very much

**Comment by skoren** [comment]
This is how much shorter (in terms of bases) a second overlap has to be in a potentially repeat region before a contig is split. See figure 2 in the Canu paper, essentially this is how much longer the blue overlap is vs the overlap to the red read. Bigger = more conservative, shorter contigs, more splitting. Shorter = more aggressive, bigger contigs, potential for mis-assembles.
