### ISSUE TITLE
GFA alignments failed.

### ISSUE THREAD

**Issue by charafore** [marbl/canu#711]
Hi, I have operated canu, yesterday. 

I am operating canu for metagenome Pacbio reads de novo assembly.
Operating command line is below.
```
canu -assemble -p cell01_2 -d /home/data02/assem_cell01_2 corMinCoverage=0 corOutCoverage=10000 corMhapSensitivity=high correctedErrorRate=0.105 genomeSize=5m corMaxEvidenceCoverageGlobal=10 oeaMemory=32 redMemory=32 batMemory=126 maxthreads=50 -pacbio-corrected /home/cell1.fasta
```
However, I mat a problem in process.

```
 -- Starting command on Sat Nov 25 05:01:06 2017 with 3468.36 GB free disk space

    cd unitigging
    /home/khkim/biotools/canu-1.6/Linux-amd64/bin/tgStoreCoverageStat \
      -G ./cell01_2.gkpStore \
      -T ./cell01_2.ctgStore 2 \
      -s 5000000 \
      -o ./cell01_2.ctgStore.coverageStat \
    > ./cell01_2.ctgStore.coverageStat.err 2>&1

-- Finished on Sat Nov 25 05:01:12 2017 (6 seconds) with 3468.336 GB free disk space
----------------------------------------
-- Finished stage 'consensusAnalyze', reset canuIteration.
----------------------------------------
-- Starting command on Sat Nov 25 05:01:12 2017 with 3468.336 GB free disk space

    cd unitigging/4-unitigger
    ./alignGFA.sh
GFA alignments failed.

-- Finished on Sat Nov 25 05:01:38 2017 (26 seconds) with 3468.336 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:

ABORT:
ABORT: Canu 1.6
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to align contigs.
ABORT:
```
I searched some information, but I cannot understand (GFA alignment failed. #606)

I want to operate this excellent software for my work. How can I do?

**Comment by skoren** [comment]
Are you running on a grid or a single machine? It may be running of of memory and getting killed on the grid. If that's the case, run the alignGFA.sh script by hand on a machine with at least 30gb of memory available. If you're not on the grid, then can you post the output of ```alignGFA*.out``` from the ```unitigging/4-unitigger``` folder

**Comment by charafore** [comment]
Thank you for your kindness reply.

First, I did not use a grid, just workstation in our lab.
Second, I try to find alignGFA*.out file in unitigging/4-unitigger folder,
but I cannot find the file.


After search a more information from internet, I will try to operating canu
again.

Sincerely, Kyung Hyun Kim


2017-11-25 23:46 GMT+09:00 Sergey Koren <notifications@github.com>:

**Comment by skoren** [comment]
Try running the alignGFA.sh script by hand from within the unitigging/4-unitigger by hand on a machine with at least 30gb and post any output. Also, post the contents of the file itself as well.

**Comment by charafore** [comment]
Thank you.
I try operate Canu again and GFA alignment step failed also.

Below list are files in 4-unitigger folder
alignGFA.sh*                                  
cell01.001.filterOverlaps.thr000.num000.log   
cell01.003.buildGreedy.sizes 
cell01.004.placeContains.sizes
cell01.005.mergeOrphans.sizes
cell01.005.mergeOrphans.thr000.num000.log 
cell01.005.mergeOrphans.unassembled
cell01.007.breakRepeats.sizes
cell01.007.breakRepeats.thr000.num000.log
cell01.009.generateOutputs.overlaps    
cell01.009.generateOutputs.sizes        
cell01.009.generateOutputs.thr000.num000.log  
cell01.011.generateUnitigs.thr000.num000.log  
cell01.best.contains.histogram
cell01.best.edges                             
cell01.best.edges.gfa                         
cell01.best.edges.histogram
cell01.best.edges.suspicious   
cell01.best.singletons
cell01.best.spurs
cell01.contigs.aligned.gfa
cell01.contigs.aligned.gfa.err
cell01.contigs.gfa
cell01.final.assembly.gfa
cell01.initial.assembly.gfa
cell01.unitigs.aligned.gfa
cell01.unitigs.aligned.gfa.err
cell01.unitigs.aligned.bed.err
cell01.unitigs.gfa
unitigger.000001.out              
unitigger.err
unitigger.sh*
unitigger.success

---------------------------------------cell01.contigs.gfa
H	VN:Z:bogart/edges

---------------------------------------cell01.contigs.aligned.gfa.err
-- Reading GFA './cell01.contigs.gfa'.
gfa:  Loaded 0 sequences and 0 links.
-- Loading sequences from tigStore '../cell01.ctgStore' version 2.
-- Resetting sequence lengths.
-- Aligning 0 links using 4 threads.
-- Writing GFA './cell01.contigs.aligned.gfa'.
-- Cleaning up.
-- Aligned      0 ciruclar tigs, failed      0
-- Aligned      0   linear tigs, failed      0
Bye.

---------------------------------------cell01.unitigs.aligned.bed.err
-- Reading BED './cell01.unitigs.bed'.
Failed to open './cell01.unitigs.bed' for reading: No such file or directory

---------------------------------------cell01.unitigs.aligned.gfa.err
-- Reading GFA './cell01.unitigs.gfa'.
gfa:  Loaded 0 sequences and 0 links.
-- Loading sequences from tigStore '../cell01.utgStore' version 2.
tgStore::tgStore()-- WARNING:  no tigs in store '../cell01.utgStore' version '2'.
-- Resetting sequence lengths.
-- Aligning 0 links using 4 threads.
-- Writing GFA './cell01.unitigs.aligned.gfa'.
-- Cleaning up.
-- Aligned      0 ciruclar tigs, failed      0
-- Aligned      0   linear tigs, failed      0
Bye.

---------------------------------------unitigger.err
==> PARAMETERS.

Resources:
  Memory                126 GB
  Compute Threads       4 (command line)

Lengths:
  Minimum read          0 bases
  Minimum overlap       500 bases

Overlap Error Rates:
  Graph                 0.105 (10.500%)
  Max                   0.105 (10.500%)

Deviations:
  Graph                 6.000
  Bubble                6.000
  Repeat                3.000

Edge Confusion:
  Absolute              2100
  Percent               200.0000

Unitig Construction:
  Minimum intersection  500 bases
  Maxiumum placements   2 positions

Debugging Enabled:
  (none)

==> LOADING AND FILTERING OVERLAPS.

ReadInfo()-- Using 581904 reads, no minimum read length used.

OverlapCache()-- limited to 129024MB memory (user supplied).

OverlapCache()--       4MB for read data.
OverlapCache()--      22MB for best edges.
OverlapCache()--      57MB for tigs.
OverlapCache()--      15MB for tigs - read layouts.
OverlapCache()--      22MB for tigs - error profiles.
OverlapCache()--   32256MB for tigs - error profile overlaps.
OverlapCache()--   12881MB for other processes.
OverlapCache()-- ---------
OverlapCache()--   45270MB for data structures (sum of above).
OverlapCache()-- ---------
OverlapCache()--      11MB for overlap store structure.
OverlapCache()--   83742MB for overlap data.
OverlapCache()-- ---------
OverlapCache()--  129024MB allowed.
OverlapCache()--
OverlapCache()-- Retain at least 2361 overlaps/read, based on 1180.62x coverage.
OverlapCache()-- Initial guess at 9431 overlaps/read.
OverlapCache()--
OverlapCache()-- Adjusting for sparse overlaps.
OverlapCache()--
OverlapCache()--               reads loading olaps          olaps               memory
OverlapCache()--   olaps/read       all      some          loaded                 free
OverlapCache()--   ----------   -------   -------     ----------- -------     --------
OverlapCache()--         9431    517500         0              62 100.00%      83742 MB
OverlapCache()--
OverlapCache()-- Loading overlaps.
OverlapCache()--
OverlapCache()--          read from store           saved in cache
OverlapCache()--   ------------ ---------   ------------ ---------
OverlapCache()--   ------------ ---------   ------------ ---------
OverlapCache()--             62 (100.00%)             52 (083.87%)
OverlapCache()--
OverlapCache()-- Ignored 0 duplicate overlaps.
OverlapCache()--
OverlapCache()-- Symmetrizing overlaps.
OverlapCache()--   Finding missing twins.
OverlapCache()--   Found 0 missing twins in 52 overlaps, 0 are strong.
OverlapCache()--   Dropping weak non-twin overlaps; allocated 0 MB scratch space.
OverlapCache()--   Dropped 0 overlaps; scratch space released.
OverlapCache()--   Adding 0 missing twin overlaps.
OverlapCache()--   Finished.

BestOverlapGraph()-- allocating best edges (17MB)

BestOverlapGraph()-- finding initial best edges.

BestOverlapGraph()-- filtering suspicious reads.
BestOverlapGraph()-- marked 581877 reads as suspicious.

BestOverlapGraph()-- filtering high error edges.

BestOverlapGraph()-- filtering reads with lopsided best edges.

BestOverlapGraph()-- filtering spur reads.
BestOverlapGraph()-- detected 27 spur reads and 581877 singleton reads.

BestOverlapGraph()-- removing best edges for contained reads.

==> BUILDING GREEDY TIGS.

breakSingletonTigs()-- Removed 27 singleton tigs; reads are now unplaced.
optimizePositions()-- Optimizing read positions for 28 reads in 581905 tigs, with 4 threads.
optimizePositions()--   Allocating scratch space for 581905 reads (0 KB).
optimizePositions()--   Initializing positions with 4 threads.
optimizePositions()--   Recomputing positions, iteration 1, with 4 threads.
optimizePositions()--     Reset zero.
optimizePositions()--     Checking convergence.
optimizePositions()--     converged: 581904 reads
optimizePositions()--     changed:        1 reads
optimizePositions()--   Recomputing positions, iteration 2, with 4 threads.
optimizePositions()--     Reset zero.
optimizePositions()--     Checking convergence.
optimizePositions()--     converged: 581904 reads
optimizePositions()--     changed:        1 reads
optimizePositions()--   Recomputing positions, iteration 3, with 4 threads.
optimizePositions()--     Reset zero.
optimizePositions()--     Checking convergence.
optimizePositions()--     converged: 581904 reads
optimizePositions()--     changed:        1 reads
optimizePositions()--   Recomputing positions, iteration 4, with 4 threads.
optimizePositions()--     Reset zero.
optimizePositions()--     Checking convergence.
optimizePositions()--     converged: 581904 reads
optimizePositions()--     changed:        1 reads
optimizePositions()--   Recomputing positions, iteration 5, with 4 threads.
optimizePositions()--     Reset zero.
optimizePositions()--     Checking convergence.
optimizePositions()--     converged: 581904 reads
optimizePositions()--     changed:        1 reads
optimizePositions()--   Expanding short reads with 4 threads.
optimizePositions()--   Updating positions.
optimizePositions()--   Finished.

==> PLACE CONTAINED READS.

computeErrorProfiles()-- Computing error profiles for 28 tigs, with 4 threads.
computeErrorProfiles()-- Finished.

placeContains()-- placing 0 contained and 581904 unplaced reads, with 4 threads.
placeContains()-- Placed 0 contained reads and 0 unplaced reads.
placeContains()-- Failed to place 0 contained reads (too high error suspected) and 581904 unplaced reads (lack of overlaps suspected).
optimizePositions()-- Optimizing read positions for 28 reads in 581905 tigs, with 4 threads.
optimizePositions()--   Allocating scratch space for 581905 reads (0 KB).
optimizePositions()--   Initializing positions with 4 threads.
optimizePositions()--   Recomputing positions, iteration 1, with 4 threads.
optimizePositions()--     Reset zero.
optimizePositions()--     Checking convergence.
optimizePositions()--     converged: 581904 reads
optimizePositions()--     changed:        1 reads
optimizePositions()--   Recomputing positions, iteration 2, with 4 threads.
optimizePositions()--     Reset zero.
optimizePositions()--     Checking convergence.
optimizePositions()--     converged: 581904 reads
optimizePositions()--     changed:        1 reads
optimizePositions()--   Recomputing positions, iteration 3, with 4 threads.
optimizePositions()--     Reset zero.
optimizePositions()--     Checking convergence.
optimizePositions()--     converged: 581904 reads
optimizePositions()--     changed:        1 reads
optimizePositions()--   Recomputing positions, iteration 4, with 4 threads.
optimizePositions()--     Reset zero.
optimizePositions()--     Checking convergence.
optimizePositions()--     converged: 581904 reads
optimizePositions()--     changed:        1 reads
optimizePositions()--   Recomputing positions, iteration 5, with 4 threads.
optimizePositions()--     Reset zero.
optimizePositions()--     Checking convergence.
optimizePositions()--     converged: 581904 reads
optimizePositions()--     changed:        1 reads
optimizePositions()--   Expanding short reads with 4 threads.
optimizePositions()--   Updating positions.
optimizePositions()--   Finished.

==> MERGE ORPHANS.

computeErrorProfiles()-- Computing error profiles for 28 tigs, with 4 threads.
computeErrorProfiles()-- Finished.

findPotentialOrphans()-- working on 28 tigs.
mergeOrphans()-- Found 0 potential orphans.
mergeOrphans()-- placed        0 unique orphan tigs
mergeOrphans()-- shattered     0 repeat orphan tigs
mergeOrphans()--
classifyAsUnassembled()--      0 tigs           0 bases -- singleton
classifyAsUnassembled()--      0 tigs           0 bases -- too few reads        (< 2 reads)
classifyAsUnassembled()--      0 tigs           0 bases -- too short            (< 0 bp)
classifyAsUnassembled()--      0 tigs           0 bases -- single spanning read (> 1.000000 tig length)
classifyAsUnassembled()--      0 tigs           0 bases -- low coverage         (> 0.500000 tig length at < 5 coverage)
classifyAsUnassembled()--      0 tigs           0 bases -- acceptable contigs


==> GENERATING ASSEMBLY GRAPH.

computeErrorProfiles()-- Computing error profiles for 28 tigs, with 4 threads.
computeErrorProfiles()-- Finished.

AssemblyGraph()-- allocating vectors for placements, 26.637MB
AssemblyGraph()-- finding edges for 0 reads (0 contained), ignoring 581904 unplaced reads, with 4 threads.
AssemblyGraph()-- building reverse edges.
AssemblyGraph()-- build complete.
AssemblyGraph()-- generating './cell01.initial.assembly.gfa'.
AssemblyGraph()-- Found 0 edges to unassembled contigs.
AssemblyGraph()--        0 bubble placements
AssemblyGraph()--        0 repeat placements

AssemblyGraph()-- Intratig edges:            0 contained         0 5'         0 3' (in both contig and unitig)
AssemblyGraph()-- Contig only edges:         0 contained         0 5'         0 3'
AssemblyGraph()-- Unitig only edges:         0 contained         0 5'         0 3'
AssemblyGraph()-- Intercontig edges:         0 contained         0 5'         0 3' (in neither contig nor unitig)

==> BREAK REPEATS.

computeErrorProfiles()-- Computing error profiles for 28 tigs, with 4 threads.
computeErrorProfiles()-- Finished.
markRepeatReads()-- Found 0 confused edges.

==> CLEANUP MISTAKES.

splitDiscontinuous()-- Tested 0 tigs, split none.
promoteToSingleton()-- Moved 581904 unplaced reads to singleton tigs.
dropDeadEnds()-- Modified 0 tigs.  Dropped 0 first and 0 last reads, 0 tigs had both reads dropped.
splitDiscontinuous()-- Tested 0 tigs, split none.
promoteToSingleton()-- Moved 0 unplaced reads to singleton tigs.

==> CLEANUP GRAPH.

AssemblyGraph()-- rebuilding
AssemblyGraph()-- building reverse edges.
AssemblyGraph()-- rebuild complete.
AssemblyGraph()-- filtering edges
AssemblyGraph()-- 0 contig edges and 0 unitig edges.
AssemblyGraph()-- 0 bubble edges and 0 repeat edges.
AssemblyGraph()-- 0 middle contig edges filtered from 0 reads.
AssemblyGraph()-- 0 repeat end edges filtered from 0 reads.
AssemblyGraph()-- 0 repeat edges (not output).
AssemblyGraph()-- 0 bubble edges.
AssemblyGraph()-- 0 intersecting edges (from the end of a tig to somewhere else).

==> GENERATE OUTPUTS.

AssemblyGraph()-- generating './cell01.final.assembly.gfa'.
AssemblyGraph()-- Found 0 edges to unassembled contigs.
AssemblyGraph()--        0 bubble placements
AssemblyGraph()--        0 repeat placements

AssemblyGraph()-- Intratig edges:            0 contained         0 5'         0 3' (in both contig and unitig)
AssemblyGraph()-- Contig only edges:         0 contained         0 5'         0 3'
AssemblyGraph()-- Unitig only edges:         0 contained         0 5'         0 3'
AssemblyGraph()-- Intercontig edges:         0 contained         0 5'         0 3' (in neither contig nor unitig)
AssemblyGraph()-- generating './cell01.contigs.gfa'.

==> GENERATE UNITIGS.

computeErrorProfiles()-- Computing error profiles for 581932 tigs, with 4 threads.
computeErrorProfiles()-- Finished.
splitDiscontinuous()-- Tested 0 tigs, split none.
AssemblyGraph()-- generating './cell01.unitigs.gfa'.

Bye.

I wrote contents of '.err' files. In my opinion, making contigs.gfa file maybe failed, so next step mat a filed continuously. 

I am looking forward to your comments. Thank you.

**Comment by skoren** [comment]
It appears you have no unitigs and no assembly which is causing the error. What's the output in ```cell01.001.filterOverlaps.thr000.num000.log``` and ```cell01.009.generateOutputs.sizes``` as well as the full output of the Canu run?

**Comment by brianwalenz** [comment]
Are these raw reads straight off the sequencer?  There are almost 600,000 reads, but only 62 overlaps were found.

**Comment by charafore** [comment]
Thank you for your comments.

First, I upload a contents of  cell01.001.filterOverlaps.thr000.num000.log and cell01.009.generateOutputs.sizes files. 

---------------------------------------------cell01.001.filterOverlaps.thr000.num000.log file

INITIAL EDGES
-------- ----------------------------------------
       0 reads are contained
  581877 reads have no best edges (singleton)
      27 reads have only one best edge (spur) 
               20 are mutual best
       0 reads have two best edges 
                0 have one mutual best edge
                0 have two mutual best edges


ERROR RATES (27 samples)
-----------
mean   0.09208148 stddev 0.01588718 -> 0.18740453 fraction error =  18.740453% error
median 0.10080000 mad    0.00340000 -> 0.13104504 fraction error =  13.104504% error


EDGE FILTERING
-------- ------------------------------------------
       0 reads have a suspicious overlap pattern
       0 reads had edges filtered
                0 had one
                0 had two
       0 reads have length incompatible edges
                0 have one
                0 have two

FINAL EDGES
-------- ----------------------------------------
       0 reads are contained
  581904 reads have no best edges (singleton)
       0 reads have only one best edge (spur) 
                0 are mutual best
       0 reads have two best edges 
                0 have one mutual best edge
                0 have two mutual best edges


--------------------------------------------------------cell01.009.generateOutputs.sizes file
UNASSEMBLED (581904 tigs) (5903082533 length) (10144 average) (1180.62x coverage)

when I am looking the output files, the data have a little amount of reads that overlaped and assembled
I heard that the PacBio data had just corrected, not assembled. 

How can I get a more longer and complete genome sequences using this raw data?

**Comment by skoren** [comment]
I noticed in your original command you are running with ```-pacbio-corrected cell1.fasta```. How were these data corrected? They don't seem to be corrected very well based on the fact that no overlaps are found. 

If these are raw data as @brianwalenz was asking, you should use ```-pacbio-raw cell1.fasta```. If they were corrected outside Canu, I'd suggest still using ```-pacbio-raw``` with the pre-correction raw data.

**Comment by skoren** [comment]
Closing inactive, appears to be raw data passed as corrected data causing no assembly to be generated.
