### ISSUE TITLE
canu1.6 stopped because too much bucket and overlapper files were generated

### ISSUE THREAD

**Issue by ShuChen1986** [marbl/canu#712]
Hi, I ran canu correction on our data with following command:
perl /home/user/Music/canu1.6/Linux-amd64/bin/canu \
-correct \
-p stylo-lordec \
-d /home/user/Documents/Result/0result_canu/canu_2017-10-05/correction \
genomeSize=1.5G \
maxThreads=11 \
maxMemory=100000000000 \
-pacbio-raw \
/home/user/Documents/Stylosanthes/lordec/stylo_pacbio_combined.trimmed.fq

The job was terminated at building bucket. it produced 2.9TB data under the folder 'stylo-lordec.ovlStore.BUILDING' and 2.4TB data under the folder '1-overlapper'. I suspect that the program stopped because there is just simply not enough room for more new files.
Our data processed this time was corrected and trimmed by lordec. The input fastq files contains upper case and low case letters.
I ran canu1.3 on our original data (fastq files did not get processed with lordec) before an all correction, trimming and assembling worked out fine. 
Does canu1.6 normally generate bucket and overlapper files as much 5TB?

**Comment by skoren** [comment]
Canu reports free space during the run so it should tell you if you're low on space. 

You're running correction on already corrected reads which is likely why you're getting so many overlaps. I don't think that's what you want. The correction step is tuned to find overlaps down to 30% error which is probably finding lots of repeat overlaps in the corrected reads you don't actually need. You should specify the lordec input as pacbio-corrected not pacbio-raw and don't specify correct.

**Comment by skoren** [comment]
Presuming not correcting the reads addressed the space issue, open a new issue if you encounter errors assembling lordec reads as already corrected data.
