### ISSUE TITLE
how to increase the required coverage for the trimming and assembly?

### ISSUE THREAD

**Issue by CelinePB** [marbl/canu#714]
Hello, 

I am using Canu 1.4 on a unix machine.
I am trying to assemble a eukaryote genome with a lot of repeats. We have PacBio datas, and a coverage ~35x. 
We are obtaining quite good results, but it seems that we have problems of misjuction among out final contigs.
I wanted to know if there is a possibility to require a higher coverage during the trimming and assembly phases.

thank you in advance.
Celine

**Comment by skoren** [comment]
Canu 1.4 is quite old, there have been significant changes when compared to the 1.6 release so if possible, I'd suggest re-assembling with the latest release. You should expect on the order of 10s of misjoined contigs in a large genome assembly. We typically rely on complimentary data such as HiC or optical maps to identify and break those. The latest version (1.6) also outputs a conservative set of unitigs which break at any suspect joins, you could then see if regions of mis-assembly correspond to breaks in the unitigs as confirmation that the assembly had poor support there.

**Comment by skoren** [comment]
I'm not aware of any recurrent issues in Canu 1.6 among users? Can you be more explicit.

There isn't a threshold on join coverage, just maximum error and length. You can either decrease the error rate or increase the minimum overlap length. You can also control how much better the used join has to be than an alternate with batOptions (```batOptions="-ca 2000 -cp 200```) which specify bases and percent better the best join has to be. Increasing the values would make the assembly more conservative.

**Comment by skoren** [comment]
Inactive.
