### ISSUE TITLE
Canu: cant' open 'unitigging/...'

### ISSUE THREAD

**Issue by Oxalis** [marbl/canu#716]
Hi,

I am trying to run Canu-1.6 using SLURM. Here is my command:

`sbatch -p tsl-short --mem 80000 --wrap "source perl-5.16.3 && source canu-1.6 && source java-8u102 && canu -assemble useGrid=false -p pacbio_assembly/rice_pacbio_ccs_sample_1_trimmed/rice_pacbio_ccs_sample_1_trimmed -d pacbio_assembly/rice_pacbio_ccs_sample_1_trimmed genomeSize=1.6m correctedErrorRate=0.01 trimReadsCoverage=2 minReadLength=500 minOverlapLength=250 gnuplotTested=true -pacbio-corrected pacbio_reads/trimmed_reads/rice_pacbio_ccs_sample_1_trimmed.fq.gz"`

And below is the log file I get:

`-- CONFIGURE CANU`
`--`
`-- Detected Java(TM) Runtime Environment '1.8.0_102' (from 'java').`
`-- Detected 32 CPUs and 126 gigabytes of memory.`
`-- Detected Slurm with 'sinfo' binary in /usr/bin/sinfo.`
`-- Grid engine disabled per useGrid=false option.`
`--`
`--                            (tag)Concurrency`
`--                     (tag)Threads          |`
`--            (tag)Memory         |          |`
`--        (tag)         |         |          |  algorithm`
`--        -------  ------  --------   --------  -----------------------------`
`-- Local: meryl      8 GB    4 CPUs x   8 jobs  (k-mer counting)`
`-- Local: cormhap    6 GB   16 CPUs x   2 jobs  (overlap detection with mhap)`
`-- Local: obtovl     8 GB    8 CPUs x   4 jobs  (overlap detection)`
`-- Local: utgovl     8 GB    8 CPUs x   4 jobs  (overlap detection)`
`-- Local: cor        7 GB    2 CPUs x  16 jobs  (read correction)`
`-- Local: ovb        3 GB    1 CPU  x  32 jobs  (overlap store bucketizer)`
`-- Local: ovs        8 GB    1 CPU  x  32 jobs  (overlap store sorting)`
`-- Local: red        2 GB    4 CPUs x   8 jobs  (read error detection)`
`-- Local: oea        1 GB    1 CPU  x  32 jobs  (overlap error adjustment)`
`-- Local: bat       15 GB    4 CPUs x   8 jobs  (contig construction)`
`-- Local: cns       15 GB    4 CPUs x   8 jobs  (consensus)`
`-- Local: gfa        8 GB    4 CPUs x   8 jobs  (GFA alignment and processing)`
`--`
`-- Found PacBio corrected reads in the input files.`
`--`
`-- Generating assembly` `'pacbio_assembly/rice_pacbio_ccs_sample_1_trimmed/rice_pacbio_ccs_sample_1_trimmed' in '/usr/users/sl/joueta/rice_full/pacbio_assembly/rice_pacbio_ccs_sample_1_trimmed'`
`--`
`-- Parameters:`
`--`
`--  genomeSize        1600000`
`--`
`--  Overlap Generation Limits:`
`--    corOvlErrorRate 0.2400 ( 24.00%)`
`--    obtOvlErrorRate 0.0100 (  1.00%)`
`--    utgOvlErrorRate 0.0100 (  1.00%)`
`--`
`--  Overlap Processing Limits:`
`--    corErrorRate    0.3000 ( 30.00%)`
`--    obtErrorRate    0.0100 (  1.00%)`
`--    utgErrorRate    0.0100 (  1.00%)`
`--    cnsErrorRate    0.0100 (  1.00%)`
`--`
`--`
`-- BEGIN ASSEMBLY`
`--`
`ABORT:`
`ABORT: Canu 1.6`
`ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.`
`ABORT: Try restarting.  If that doesn't work, ask for help.`
`ABORT:`
`ABORT:   cant' open 'unitigging/pacbio_assembly/rice_pacbio_ccs_sample_1_trimmed/rice_pacbio_ccs_sample_1_trimmed.gkpStore.gkp' for writing: /tsl/software/testing/bin/core/../..//canu/1.6/x86_64/bin/canu.`
`ABORT:`

I tried to add the Canu libraries to my path as seen in the issue #678 [https://github.com/marbl/canu/issues/678](url) but it does not change a thing:
`export PATH=$PATH:/tsl/software/testing/canu/1.6/x86_64/Linux-amd64/bin/lib/canu/`

Also wondering why it is trying to open `unitigging/pacbio_assembly/rice_pacbio_ccs_sample_1_trimmed/rice_pacbio_ccs_sample_1_trimmed.gkpStore.gkp` when my unitigging folder is at `pacbio_assembly/rice_pacbio_ccs_sample_1_trimmed/unitigging`

Could someone help me with this?

Many thanks,

Agathe

**Comment by skoren** [comment]
I think the issue is the / in the -d/-p options, we've not tested that. The -p is supposed to be a prefix within the folder not a full path. Try running without that (just ```-p rice_pacbio_ccs_sample_1_trimmed -d pacbio_assembly```).

**Comment by skoren** [comment]
Inactive, should be fixed by not including / in -p or -d options.
