### ISSUE TITLE
Input file for Bandage

### ISSUE THREAD

**Issue by suryasaha** [marbl/canu#72]
Do CANU generate a file for the final assembly that can be used as input for Bandage?
https://rrwick.github.io/Bandage/

**Comment by brianwalenz** [comment]
The output GFA will load, but isn't fully supported in Bandage.  Overlaps between contigs aren't displayed as overlaps, but rather as end-to-end abutments.  This is particularly frustrating for bubbles, which should be displayed as being in the middle of a contig, but are instead shown as hanging off one end.

**Comment by suryasaha** [comment]
That defeats the whole purpose of visualization. Is this something that can be fixed easily in the output .GFA using a script? Thanks

**Comment by aphillippy** [comment]
For the type of bubble Brian is describing, this would require breaking a contig into three pieces so that the alternate path could be displayed by bandage. Not ideal. As Brian says, this is an issue with Bandage and I may file a issue on that project requesting support for this type of bubble.

Currently, I see most users using Bandage to visualize alternate paths off the end of a contig. In this first version, Canu is only outputting the "best overlap graph" which will not contain all possible paths from the end of a contig. A future version will include this additional information in the GFA.

**Comment by suryasaha** [comment]
+1 for filing an issue with Bandage. They themselves say that GFA support is minimal at the moment.

It will be good to have all alternate paths in the GFA as an option in the future.

**Comment by tseemann** [comment]
+1 @rrwick : Ryan - any progress on this?

**Comment by rrwick** [comment]
Could any of the people on this thread upload or email me (rrwick@gmail.com) a Canu graph? I'd like to take a look in Bandage and see if there's a way to make it work better than it does.

However, Bandage isn't really suited to displaying a graph which contains complex overlaps. For example, if the sequences just overlap by their ends, then as Brian said, Bandage just shows them as abutments. If, however, there are complex overlaps including sequences contained within other sequences, then I'm not even sure how Bandage would best display that.

Here's my attempt to illustrate the issue (conceptual graph on the left, Bandage-style visualisation on the right):
![bandage_overlaps](https://cloud.githubusercontent.com/assets/7053555/14627734/77277e06-063a-11e6-94e8-62936bb21860.png)
A tool which displayed graphs as portrayed on the left would be cool, but Bandage couldn't do it without a serious overhaul.

Regarding Adam's comment about a bubble, yes - Bandage would currently have to display it in pieces like this:
![screen shot 2016-04-19 at 2 33 20 pm](https://cloud.githubusercontent.com/assets/7053555/14627854/b2ad7b46-063b-11e6-9f17-fc8a48aebcec.png)
A possible solution would be for Bandage to break such a contig into the necessary three pieces when it loaded the graph. That way Canu could save GFA files as it currently does but they could be viewed in Bandage with explicit bubbles. Happy to hear other's opinions on this.

**Comment by aphillippy** [comment]
Thanks for weighing in, Ryan. I would be happy if Bandage could auto-break a contig to display an internal bubble. Even better if the edges between pieces of the same contig were marked in some way to indicate they are connecting pieces of a single contig ... or if the pieces of the contig could all be colored the same.

Canu graph output is a bit half-baked at the moment. The next release should include more adjacency information off the ends of contigs, which is what Bandage is best at viewing.

Thanks!

**Comment by brianwalenz** [comment]
Graph output fully cooked now.  We're splitting contigs at intersections now, resulting in a set of unitigs with simple overlaps.

I'll note that GFA's containment edge is ignored.  It's not an issue for Canu's final graph output.
