### ISSUE TITLE
canu on sequel data, need for arrow correction?

### ISSUE THREAD

**Issue by splaisan** [marbl/canu#721]
Hi there,

Is there any reason to apply arrow correction (using sequel reads) on sequel assembled data or does canu do already the job well enough during the full pipeline execution?

I do not yet have Illumina reads to further correct my assembly.

Thanks for advice
Stephane

**Comment by skoren** [comment]
Yes, Sequel data is not appreciably different in quality from the RSII data and Arrow uses signal-data which Canu does not have access to from the fasta/fastq.
