### ISSUE TITLE
required coverage for correction?

### ISSUE THREAD

**Issue by mht85** [marbl/canu#722]
I tried using canu v1.6 to test the correction pipeline for nanopore raw reads at low coverage (3.6x).
It encounters errors in the middle of the pipeline, but I'm not sure what is causing the errors.

I've attached the log, anyone knows if this is a bug or if this is because the read coverage is too low?
[canu.out.txt](https://github.com/marbl/canu/files/1534727/canu.out.txt)

**Comment by skoren** [comment]
The FAQ suggest at least 20x coverage for correction/assembly. Your error isn't related to that but most likely due to a java version (the ```precompute.*.out``` files in ```correction/1-overlapper```) would have more details but 3x is not enough.

**Comment by mht85** [comment]
From the precompute.1.out file:

Running job 1 based on SGE_TASK_ID=1 and offset=0.
Dumping reads from 1 to 93000 (inclusive).

Starting mhap precompute.

Error occurred during initialization of VM
Could not reserve enough space for 65011712KB object heap
Mhap failed.
Running job 1 based on SGE_TASK_ID=1 and offset=0.
Dumping reads from 1 to 93000 (inclusive).

Starting mhap precompute.

Error occurred during initialization of VM
Could not reserve enough space for 65011712KB object heap
Mhap failed.

---
I ran it on a cluster, I'm guessing it ran out of memory at some point?
We are still in the process of generating more long read data - for now I'm just using 3x for testing to make sure the pipeline works.

Thanks.

**Comment by skoren** [comment]
This usually is an issue with the grid/JVM config, canu is requesting 62GB from your scheduler but then the VM can't actually reserve that space when running . I see you're using h_vmem which is typically not consumable and not requested per-core (see #538) which would mean Canu would end up under-requesting memory. There should be a consumable memory resource which you can check with ```qconf -sc```. You can see an example:
```
h_vmem              h_vmem     MEMORY      <=    YES         NO         0        0
mem_free            mf         MEMORY      <=    YES         YES        0        0
```

**Comment by skoren** [comment]
Inactive.
