### ISSUE TITLE
Assembly with multiple technologies

### ISSUE THREAD

**Issue by ml3958** [marbl/canu#725]
Dear Developers,

I have a general question about the strategy that Canu uses in the case where both Nanopore and Pacbio data are available and at good quality(>50 coverage).

1. If I use both datasets at the same time, does Canu perform separate processing since the parameter are different for Pacbio data and Nanopore, such as correctedErrorRate? If yes, at which steps?

2. As I mentioned, the two datasets are at good quality seperately. Do you recommend hybrid assembly, or only use one dataset of higher quality(usually Pacbio)?

Thanks!!

**Comment by skoren** [comment]
Mixing the datasets should be fine, for the settings the higher error dataset wins so it will be assembled with nanopore params. The best reads for assembly are the longest ones so if it can keep some longer lower-quality reads by correcting them with the higher quality dataset, that could help. So I'd suggest combining the data and letting it be assembled (there is an example of this on the quick start page), you could compare to a PacBio-only assembly if you wanted.

**Comment by skoren** [comment]
Idle, question answered, closing.

**Comment by ml3958** [comment]
Hi @skoren, as you suggested I ran hybrid assembly (mixing Pacbio + Nanopore) and PacBio-only assembly, and compared. I want to share my results here to the other users in case it is helpful to anyone by chance.  

In my case, PacBio-only assembly greatly out performed PacBio-Nanopore assembly. I think the reason is the PacBio data has significant higher coverage (1800X) than Nanopore(50X). Adding the Nanopore reads in did not make a huge difference in sequencing coverage but causes Canu to use Nanopore-specific paras, which eventually lead to low assembly and lots of missing contigs. Specifically, This organism we study contains 2.6 mb DNA. Using Pacbio-Only, we got 24 contigs for 2.58mb -- not as continuos enough, but reasonable coverage; In contrast, using Pacbio+ Nanopore, we got only 6 contigs for 6 sequences, total length 0.27mb. 

But I think in a case that two dataset has both relatively low coverage, it might worth mixing them together.

**Comment by apredeus** [comment]
Are there any updates on what would work best? We have a 600 Mb genome with 70x PacBio and 20x Nanopore (ultra-long reads + some nice long 1D). Nanopore-only assembly with Canu was very impressive, gave over 1.3 Mb N50 and outperformed most other things we have tried. Now I intend to simply run a Pacbio-only assembly and then PacBio + Nanopore, but not sure if there would be any tricks to it that can improve the assembly? 

Thanks you!

**Comment by skoren** [comment]
I'm not sure what happened with @ml3958's assembly, but losing most of the genome from adding nanopore data doesn't make sense. What I would guess happened is that something else changed due to the added coverage (sensitivity of overlapping) leading to worse corrected reads. We've done lots of combinations of higher PacBio and lower Nanopore without seeing this issue.

I would run with defaults, though you can probably drop the corrected error rate down from nanopore defaults since most of your data is PacBio. Try ``correctedErrorRate=0.105``` and provide both PacBio and Nanopore together. For the PacBio-only, defaults are fine. If it's sequel see the FAQ for adjusted parameters.

**Comment by apredeus** [comment]
Brilliant, thank you! I totally missed the sequel part. Maybe it's worth adding as a separate key (-nanopore-raw, -pacbio-raw, -sequel-raw)? 

Thanks again.

**Comment by alimayy** [comment]
Hi @skoren and others, thanks for your insights on this topic.

@skoren I have a related question: when there is both PB and ONT data for a given sample, does it make sense (might it be better) to error-correct (and maybe also trim?) these datasets separately, and then later combine the two error-corrected (and trimmed?) read sets to feed them into Canu's assembly module? Do you think this would give similar/better/worse results?

Thanks again,
Ali

**Comment by skoren** [comment]
@alimayy I usually mix the two together for correction/trimming/assembly. The data can help correct each mayy other so you end up with better consensus for the nanopore data than you would from nanopore alone. I'd use the same parameters I suggested earlier in this comment, probably ```corMhapSensitivity=normal correctedErrorRate=0.105```. You could try both (independent and combined) and see what happens.

@apredeus I am hoping this difference in quality is not permanent and sequel will improve with time. We'd rather not fragment our sequencing types for every instrument or chemistry iteration (e.g. nanopore r7 data is very different from r9 data).

**Comment by alimayy** [comment]
Thanks a lot for your input @skoren!

**Comment by hrpelg** [comment]
Hi, I would liek to ocmbine ONt data and hifi Pacbio reads, is that supported by Canu? Got a piece of teh genoem ignored in the Pacbio that I would like to assemble by providing teh ONT data simultaneusly.

Cheers

**Comment by skoren** [comment]
Nope, combining HiFi with other data types isn't supported by Canu. What you want is verkko: https://github.com/marbl/verkko which builds the initial assembly with HiFi and then fills gaps/resolves repeats with ONT. If there is a very large completely missed region in HiFi it won't assemble it but we don't see that very often.
