### ISSUE TITLE
canu 1.6 Bogart failed

### ISSUE THREAD

**Issue by JifengTang** [marbl/canu#726]
My assembly on about 1G failed at Bogart.
 I used "batThreads=40 batMemory=200 maxThreads=128 maxMemory=240".
Bogart was running a node with 40 cores and 252G memory. I saw it used 98% memory. 
From "unitigger.err", it seems failed at "GENERATING ASSEMBLY GRAPH".
Currently, the second trial is running. I am afraid it will crash as well.

Can someone have a solution about this issue?
I appreciate.

The last part of "unitigger.err"
```
==> MERGE ORPHANS.

computeErrorProfiles()-- Computing error profiles for 152805 tigs, with 48 threads.
computeErrorProfiles()-- Finished.

findPotentialOrphans()-- working on 152805 tigs.
mergeOrphans()-- Found 10005 potential orphans.
mergeOrphans()-- placed       18 unique orphan tigs
mergeOrphans()-- shattered     1 repeat orphan tigs
mergeOrphans()--
classifyAsUnassembled()--      0 tigs           0 bases -- singleton
classifyAsUnassembled()--      0 tigs           0 bases -- too few reads        (< 2 reads)
classifyAsUnassembled()--      0 tigs           0 bases -- too short            (< 0 bp)
classifyAsUnassembled()--      0 tigs           0 bases -- single spanning read (> 1.000000 tig length)
classifyAsUnassembled()--   1324 tigs    15581520 bases -- low coverage         (> 0.500000 tig length at < 5 coverage)
classifyAsUnassembled()--  17220 tigs  1014349538 bases -- acceptable contigs

==> GENERATING ASSEMBLY GRAPH.

computeErrorProfiles()-- Computing error profiles for 152805 tigs, with 48 threads.
computeErrorProfiles()-- Finished.

AssemblyGraph()-- allocating vectors for placements, 258.597MB
AssemblyGraph()-- finding edges for 4780895 reads (4487174 contained), ignoring 868252 unplaced reads, with 48 threads.
AssemblyGraph()-- building reverse edges.
```

**Comment by skoren** [comment]
Sorry, didn't see this issue earlier, did your re-run finish? What is the output from the first part of unitigger, it will report stats about how many overlaps it can fit into memory. You can potentially decrease the error rate or increase the minimum overlap length to reduce the memory usage as well. What version of Canu is this?

**Comment by JifengTang** [comment]
Thank you for your reply. 
Merry Christmas and Happy new year!

I used a little track to solved the problem already.
I just modified the script in the folder and let it run locally on a computer with large memory (2T)
when that was completed, I restarted the pipeline. It completed.
I used Canu1.6 official version.
