### ISSUE TITLE
canu 1.6 alignGFA failed Aborted (core dumped)

### ISSUE THREAD

**Issue by JifengTang** [marbl/canu#728]
I am doing canu 1.6 for a pathogen about 700M with 100x PacBio data. 
I had one assembly, but N50 size is jut 48kbp and the assembled base is about 1.2G.

I am changing the assembly setting in 4-unitiger/unitigger.sh
from 
```
-gs 700000000 \
 -eg 0.04 \
 -eM 0.04 \
 -mo 500 \
 -dg 6 \
 -db 6 \
 -dr 3 \
 -ca 2100 \
 -cp 200 \
```
to
```
 -gs 700000000 \
 -eg 0.02 \
 -eM 0.04 \
 -mo 500 \
 -dg 3 \
 -db 3 \
 -dr 1 \
 -ca 500 \
 -cp 50 \
```
The pipeline completed unitigger.sh, but crashed at alignGFA.sh
The errors are below:
```
### more xxx.unitigs.aligned.gfa.err
-- Reading GFA './xxx.unitigs.gfa'.
gfa:  Loaded 70809 sequences and 6630993 links.
-- Loading sequences from tigStore '../xxx.utgStore' version 2.
-- Resetting sequence lengths.
-- Aligning 6630993 links using 58 threads.
alignGFA: overlapInCore/libedlib/edlib.C:163: EdlibAlignResult edlibAlign(const char*, int, const char*, int, EdlibAlignConfig): Assertion `queryLength > 0' failed.
Aborted (core dumped)
### more xxx.aligned.gfa.err
-- Reading GFA './xxx.contigs.gfa'.
gfa:  Loaded 34242 sequences and 2170283 links.
-- Loading sequences from tigStore '../xxxi.ctgStore' version 2.
-- Resetting sequence lengths.
ERROR: sequence id 1514512 out of range b=0 e=1041862
alignGFA: gfa/alignGFA.C:105: sequence& sequences::operator[](uint32): Assertion `xx < e' failed.
Aborted (core dumped)
```
Can someone help on this?
I appreciate.

**Comment by skoren** [comment]
This seems like the unitigs in the store and the GFA are not in sync. How did you edit the ```4-unitigger/unitigger.sh``` file and did you remove all the previous results? In particular, you need to remove the ```xxx.*``` files in 4-unitigger as well as the ```xxx.utgStore```, ```xxx.ctgStore```, and ```5-consensus``` in the unitigging directory.

**Comment by JifengTang** [comment]
I remove xxx.* in 4-unitigger and also 5-consensus, I did not remove xxx.utgStrore and xxx.ctgStore.
Instead I edited unitigger.sh
#if [ -e ../Pachyrhizi.ctgStore/seqDB.v001.tig -a -e ../Pachyrhizi.utgStore/seqDB.v001.tig ] ; then
#  exit 0
#fi
unitigger.sh was successful, but  alignGFA.sh failed.
I will remove the folders of xxx.utgStore and  xxx.ctgStore. 
restart with unitigger.sh 
Do you think my settings would result bigger N50 size and less assembled bases?
I appreciate your suggestions.

 -gs 700000000 \
 -eg 0.02 \
 -eM 0.04 \
 -mo 500 \
 -dg 3 \
 -db 3 \
 -dr 1 \
 -ca 500 \
 -cp 50 \

**Comment by skoren** [comment]
Not removing the stores will cause errors so you'll need to remove those as well and re-run.

Your parameters will probably increase N50 but won't decrease assembled bases. You don't need to adjust eg, it will get adjusted by the dg/db parameters. You're using the haplotype splitting parameters which will separate haplotypes so it is likely your assembled bases will increase and your assembly will better represent multiple haplotypes. You could try the haplotype smashing parameters on the FAQ which would require running from corrected reads.

**Comment by JifengTang** [comment]
Thank you for quick reply.
do you mean that I should remove xxx.utgStrore and xxx.ctgStore, but not remove xxx.gkpStore and xxx.ovlStore?
I see the parameters for smashing haplotypes "corOutCoverage=200 ovlErrorRate=0.15 obtErrorRate=0.15".
does it mean that I have to start the pipeline from beginning? The previous assembly took about a month. It was too slow.
My project has a tight deadline. I afraid that I  only can try different parameters for unitiging.
Can you give some suggestions about unitigger parameters?
Thanks a lot.
By the way,  I have used "corOutCoverage=200" in my previous assembly.
My previous parameters:
"canu -p xxx -d CanuAss1.6
genomeSize=700m rawErrorRate=0.3 correctedErrorRate=0.04
corMhapSensitivity=normal corMinCoverage=0 corOutCoverage=200 batThreads=40
batMemory=200 maxThreads=128 maxMemory=240 ovsMemory=100g useGrid=1
gridOptions="-r y -V -p 0 -q all.q@@6gmempercore " gridEngineMemoryOption="-l
mem_free=MEMORY" gridEngineThreadsOption="-pe smp THREADS " -pacbio-raw
/data/sag2/2017/JTA_17060131_PhakopsoraPachyrhizi/fastqfile/*fastq

**Comment by skoren** [comment]
Yes, you need to remove the xxx.utgStore and xxx.ctgStore but not the others. The smashing parameters cannot be done with just unitigging changes because they require a higher error rate and you don't have overlaps computed to that error rate so what you can do with unitigging is limited. You would need to restart from the corrected reads, not from scratch.

You can run a sweep of unitigging parameters, you can vary ```-db/db``` between 1-6, ```-cp``` from 10-200, and ```-ca``` from 100-2000. You could also try changing the minimum overlap size (```-mo```) or turning off some of the filters ``` -nofilter suspicious-lopsided```. The ```xxx.009*sizes`` file will tell you the assembly continuity and you can keep the one with the best stats. You don't need to run the rest of the pipeline, just make sure to remove the xxx.utgStore and xxx.ctgStore between runs. Alternatively, you can try smartdenovo on the Canu corrected reads, it may collapse haplotypes as well.
