### ISSUE TITLE
Consensus jobs failed/

### ISSUE THREAD

**Issue by gfill628** [marbl/canu#729]
Hello, 

I am running Canu1.6 on a remote cluster to assemble a 27 Mbp protist genome with about 100x coverage.

**My script is below:**
```
#!/bin/bash
#$ -S /bin/bash
. /etc/profile
#$ -cwd
#$ -pe threaded 20

export PATH=/opt/perun/jre1.8.0_121/bin:$PATH

/scratch2/software/canu/canu-1.6/Linux-amd64/bin/canu \
-p Phaeo_100x_20kb_CANU -d Phaeo_100x_20kb_CANU_asm \
genomeSize=27m \
maxMemory=200g \
maxThreads=20 \
correctedErrorRate=0.13 \
-nanopore-raw /scratch2/ginaf/Phaeo_minion/assemblies/Phaeo_ALL_chop_100x_20kb_QandL.fastq \
useGrid=false
```
Both the correction and trimming modules seem to have run without any issues; however, the assembly failed during unitigging with the error: 
```
Consensus jobs failed, tried 2 times, giving up.
--   job ctgcns/0001.cns FAILED.
--   job utgcns/0001.cns FAILED.
--

ABORT:
ABORT: Canu 1.6
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```
I tried restarting canu; however, I received the same error message.

I have attached both the error file and the output file from ```/unitigging/5-consensus/consensus.000001.out. ```

Any insight would be great.  

Thank you!

[canu_phaeo.sh.e3626511.txt](https://github.com/marbl/canu/files/1549473/canu_phaeo.sh.e3626511.txt)
[consensus.000001.out.txt](https://github.com/marbl/canu/files/1549474/consensus.000001.out.txt)

**Comment by skoren** [comment]
It looks like one of your contigs is shrinking during consensus, causing an assert. First option would be to increase the error rate (with ```cnsErrorRate=0.25```) and see if it completes then.

**Comment by gfill628** [comment]
Hi Sergey, 

I increased the error rate as you recommended and the unitigging module completed. 

Thanks again!

**Comment by Tdanis** [comment]
Hi everyone, I ' ve got this problem with correction module with canu. My script is :
canu -correct -p canu_correction -d /mnt/scratch/to-my-folder 
gridOptions="--partition batch" gridEngineArrayOption="-a ARRAY_JOBS%12" corMinCoverage=0
 corMhapSensitivity=high genomeSize=0.5g
-nanopore-raw *.fastq

AND #####################




-- Parameters:
--
--  genomeSize        500000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1200 ( 12.00%)
--    utgOvlErrorRate 0.1200 ( 12.00%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1200 ( 12.00%)
--    utgErrorRate    0.1200 ( 12.00%)
--    cnsErrorRate    0.2000 ( 20.00%)
--
--
-- BEGIN CORRECTION
--
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  cor       11 GB    4 CPUs  (read correction)
--
--
-- Read correction jobs failed, tried 2 times, giving up.
--   job 2-correction/results/0021.cns FAILED.
--   job 2-correction/results/0022.cns FAILED.
--   job 2-correction/results/0023.cns FAILED.
--   job 2-correction/results/0024.cns FAILED.
--   job 2-correction/results/0025.cns FAILED.
--   job 2-correction/results/0026.cns FAILED.
--   job 2-correction/results/0027.cns FAILED.
--   job 2-correction/results/0028.cns FAILED.
--   job 2-correction/results/0029.cns FAILED.
--   job 2-correction/results/0030.cns FAILED.
--   job 2-correction/results/0031.cns FAILED.
--   job 2-correction/results/0032.cns FAILED.
--   job 2-correction/results/0033.cns FAILED.
--   job 2-correction/results/0034.cns FAILED.
--   job 2-correction/results/0035.cns FAILED.
--   job 2-correction/results/0036.cns FAILED.
--   job 2-correction/results/0037.cns FAILED.
--   job 2-correction/results/0038.cns FAILED.
--   job 2-correction/results/0039.cns FAILED.
--   job 2-correction/results/0040.cns FAILED.
--   job 2-correction/results/0041.cns FAILED.
--   job 2-correction/results/0042.cns FAILED.
--   job 2-correction/results/0043.cns FAILED.
--   job 2-correction/results/0044.cns FAILED.
--   job 2-correction/results/0045.cns FAILED.
--   job 2-correction/results/0046.cns FAILED.
--

ABORT:
ABORT: Canu 1.8
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:



Thank you for your help

**Comment by brianwalenz** [comment]
Make a new issue, please, and paste in some of the failing jobs logs that are in 2-correction/results/*.err.
