### ISSUE TITLE
job submit options

### ISSUE THREAD

**Issue by aviantask** [marbl/canu#73]
Hi, 

Canu is failing at overlap sorter stage with failure to submit batch jobs, here is the error reported

```
Overlap store bucketizer finished.
-- overlap store sorter attempt 0 begins with 0 finished, and 1098 to compute.
----------------------------------------
-- Starting command on Sun Mar 20 11:05:06 2016 with 80680 GB free disk space

      qsub \
        -l walltime=300:00:00 -q cegs  -l mem=5g -l nodes=1:ppn=1 \
        -d `pwd` -N "ovS_asm" \
        -t 1-1098 \
        -j oe -o /staging/Canu_assemblyTrial/CDCFrontier_canu1.1/correction/asm.ovlStore.BUILDING/logs/2-sort.\$PBS_ARRAYID.out \
        /staging/Canu_assemblyTrial/CDCFrontier_canu1.1/correction/asm.ovlStore.BUILDING/scripts/2-sort.sh
    
qsub: submit error (Maximum number of jobs already in queue for user MSG=total number of current user's jobs exceeds the queue limit: user aviantask@hpc2187, queue cegs)

-- Finished on Sun Mar 20 11:05:06 2016 (1 second) with 80680 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 228.
ERROR:
================================================================================
```

I tried limiting concurrency of jobs being submitted by adding the option of `corConcurrency=10` ,`ovsConcurrency=10` etc. but it didn't work. Here is the full command line I used --

`~/software/canu-1.1/Linux-amd64/bin/canu -p asm -d CDCFrontier_canu1.1 genomeSize=738m corMhapSensitivity=high corMinCoverage=2 errorRate=0.035 minOverlapLength=499 corMaxEvidenceErate=0.3 -pacbio-raw reads_CDC.fq  maxMemory=512000m maxThreads=24 gridOptions="-l walltime=300:00:00 -q cegs" ovsConcurrency=10`

How and where can I set the number of jobs being submitted in concurrency?

**Comment by brianwalenz** [comment]
As you've discovered, the concurrency options don't impact grid jobs.

The simplest solution might be to run the qsub command in batches, first with "-t 1-200" (or whatever the limit is), then "-t 201-400", etc.  Once all those complete, you can restart canu and it will resume.

Increasing ovsMemory will decrease the job count, but to do so you'll need to remove asm.ovlStore.BUILDING, and need to redo the first half of the store building process.  Doubling memory will halve the job count.

(FYI, it's three bacticks to get a block of text formatted, a single backtick just highlights the text inline, I edited to correct.)

**Comment by aviantask** [comment]
Thanks for the answer and also the text formatting tip!
