### ISSUE TITLE
-dg and -db parameter

### ISSUE THREAD

**Issue by jhtrujillo** [marbl/canu#732]
Hello, Could you tell me what is the difference between -dg and -db parameters in bogart?

Thank you very much!

**Comment by skoren** [comment]
The various ```-d*``` parameters control the deviation used for different parts of unitigging. You can see the median and MAD values computed in the ```*.001.filterOverlaps.thr000.num000.log```:
```
ERROR RATES (1307453 samples)
-----------
mean   0.02149000 stddev 0.00545580 -> 0.05422479 fraction error =   5.422479% error
median 0.02160000 mad    0.00370000 -> 0.05451372 fraction error =   5.451372% error
```

The ```-dg``` is the number of deviations allowed for building the assembly graph. The ```-dr``` is the number of deviations to use when classifying whether an overlap could be an alternate repeat path. The ```-db``` parameters controls the deviation for incorporating bubbles into the assembly.
