### ISSUE TITLE
Assertion `_listLen > 0' failed while tgStoreDump

### ISSUE THREAD

**Issue by pharthiphan** [marbl/canu#733]
Important Note:- Issue while running on linux fuse mount point and doesn't occur while running on gpfs or lustre filesystem

/home/foo/canu/Linux-amd64/bin/canu -p ecoli -d /tmp/foo_fuse/canu_fuse_output genomeSize=4.8m -pacbio-raw /tmp/foo_fuse/canu_fuse_input/p6.25x.fastq useGrid=false

----------------------------------------
-- Purging consensus output after loading to ctgStore and/or utgStore.
-- Purged 2 .cns outputs.
----------------------------------------
-- Starting command on Fri Dec 15 04:26:52 2017 with 41860.583 GB free disk space

    cd unitigging
    /home/foo/canu/Linux-amd64/bin/tgStoreDump \
      -G ./ecoli.gkpStore \
      -T ./ecoli.ctgStore 2 \
      -sizes -s 4800000 \
    > ./ecoli.ctgStore/seqDB.v002.sizes.txt
tgStoreDump: AS_UTL/intervalList.H:731: void intervalList<iNum, iVal>::computeDepth(intervalDepthRegions<iNum, iVal>*, uint32) [with iNum = int; iVal = int; uint32 = unsigned int]: Assertion `_listLen > 0' failed.

Failed with 'Aborted'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::101 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
AS_UTL/intervalList.H::731 in _ZN12intervalListIiiE12computeDepthEP20intervalDepthRegionsIiiEj()
AS_UTL/intervalList.H::626 in _ZN12intervalListIiiE5depthERS0_()
AS_UTL/intervalList.H::114 in intervalList()
stores/tgStoreDump.C::191 in _ZN8tgFilter14ignoreCoverageEP5tgTigb()
stores/tgStoreDump.C::140 in _ZN8tgFilter6ignoreEP5tgTigb()
stores/tgStoreDump.C::456 in _Z9dumpSizesP7gkStoreP7tgStoreR8tgFilterbm()
stores/tgStoreDump.C::1299 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
sh: line 4: 27229 Aborted                 /home/foo/canu/Linux-amd64/bin/tgStoreDump -G ./ecoli.gkpStore -T ./ecoli.ctgStore 2 -sizes -s 4800000 > ./ecoli.ctgStore/seqDB.v002.sizes.txt

-- Finished on Fri Dec 15 04:26:52 2017 (lickety-split) with 41860.583 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 134.  (rc=34304)
ERROR:

Also I tried with a different input "pacbio.fastq" and end up with the following error. at the same time it ran successfully with gpfs and lustre filesystem.

cat /tmp/foo_fuse/fuse_output/correction/2-correction/ecoli.readsToCorrect.err
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Failed with 'Aborted'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::101 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
AS_UTL/AS_UTL_alloc.H::105 in resizeArray<tgPosition, unsigned int>()
stores/tgTig.C::456 in _ZN5tgTig14loadFromStreamEP8_IO_FILE()
stores/tgStore.C::450 in _ZN7tgStore7loadTigEj()
correction/filterCorrectionLayouts.C::508 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()

**Comment by skoren** [comment]
Those both look like disk read errors. In both cases, the code reads a bit-packed structure and it appears some values are improperly initialized. The read within Canu checks for a complete read of the expected length and that there is no error on the read so I'm not sure what else we can do in the code. You could try editing the code to report the values read before they're used but I'm not sure how informative that would be. This seems like a filesystem bug.

**Comment by skoren** [comment]
Inactive, looks like a disk I/O errors so nothing to fix.
