### ISSUE TITLE
Canu 1.6 at correction step used 13T and more disk space

### ISSUE THREAD

**Issue by JifengTang** [marbl/canu#735]
I am assembling a 2.2G (haploid genome size) and heterozygous genome using Canu 1.6 (offical  release) on amazon. The input data is about 100x  of 2.2G genome size.
Currently it is running at building ovlStore (ovB_* jobs), it has been used 13.5T  disk space.
On amazon, the max size of EBS disk is 16T.  I am afraid that the first step of correction will not be completed.
Under the correction folder, the below folders are generated
19M     0-mercounts
9.4T    1-overlapper
49G     *.gkpStore
16K     *.gkpStore.err
12K     *.gkpStore.gkp
3.1T    *.ovlStore.BUILDING

Can someone knows which files can be deleted already at this stage?
If 16T is not enough to complete the first step and get corrected reads, 

I am afraid that I have to try another settings.

I used the settings : genomeSize=2200m  rawErrorRate=0.3 correctedErrorRate=0.04 corMhapSensitivity=normal corMinCoverage=2 corOutCoverage=200 batThreads=32 batMemory=200 maxThreads=128 maxMemory=240

Can anyone give  suggestions on the settings to reduce the disk space usage?

I appreciate any suggestions.

**Comment by skoren** [comment]
In general, the disk usage is dependent on genome size and repeat content. Increasing the sensitivity from the default for the high input data is likely contributing to the space usage. 

You are at the peak of disk usage, the store is sorting the output in 1-overlapper so it needs approximately double the space. That would be about 20TB. Once the store is constructed the 1-overlapper data is removed. There are some files that are safe to remove now. The 1-overlapper/blocks folder can safely be erased. If that drops the 1-overlapper down to < 7TB you can probably fit into 16TB.

You can also remove an input file in ```1-overlapper/results``` once the corresponding ```bucket``` folder exists in the ```*.ovlStore.BUILDING``` folder. For example, if you have
```bucket0001``` you can remove ```1-overlapper/results/000001.*```. Make sure you only remove the file once you have a ```bucket0001``` not just a ```create0001``` folder. However, this could cause an issue if the disk I/O fails and the bucket is corrupt, you would not be able to back up and re-try if you erase the inputs. We commonly do this to save space but I know from running on our systems, the I/O is reliable. This is why Canu maintains the inputs until the very end of store construction but if you're trying to save space this may be your only option.

**Comment by JifengTang** [comment]
Thank you very much.
The blocks only takes about 600G.
I see about 114 bucket* folders created in *.ovlStore.BUILDING
It will save about 2.6T space. Then 1-overlapper size can be reduced 6.2T. 

Maybe the best is that I will start a new assembly, what settings would you recommend to use?
Thanks a lot.

**Comment by skoren** [comment]
Not setting ```corMhapSensitivity=normal``` would probably save space. 

Since you already have the overlaps computed you might as well try to build the store. Just remove the files from 1-overlapper as the bucket files are created. It may be sufficient to remove the 1-overlapper/results files corresponding to the already created buckets and let Canu clean up the rest.

**Comment by JifengTang** [comment]
I tried as you suggested
/mnt/process/Canu/CanuAss16/correction$ ls -ltr imp.ovlStore.BUILDING/bucket0100/
......
-rw-r--r-- 1 ubuntu ubuntu  88076553 Dec 19 03:54 slice2032
-rw-r--r-- 1 ubuntu ubuntu  87813577 Dec 19 03:54 slice2033
-rw-r--r-- 1 ubuntu ubuntu  25122740 Dec 19 03:55 slice2034
-rw-r--r-- 1 ubuntu ubuntu     32648 Dec 19 03:55 sliceSizes
so bucket0100 is completed then I removed 1-overlapper/results/000100.*

When I restarted the pipeline, I got errrors:
ABORT:
ABORT: Canu 1.6
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   overlapper output '1-overlapper/results/000100.ovb' not found.
ABORT:

I do not know why that tool still check the completed jobs.
How can I continue my work?
I appreciate.

**Comment by skoren** [comment]
Sorry, forgot about that check, it is making sure that each input ovb file has a corresponding bucket. If you have all the buckets already, you can run ```touch imp.ovlStore.BUILDING/1-bucketize.success``` and re-launch canu and it will move onto the next step.

**Comment by JifengTang** [comment]
Thank you very much.
However, not all buckets are completed. 114 bucket* folders were generated.
According to  files in 1-overlapper/results/ and create* folder in imp.ovlStore.BUILDING, I should see 401 buckets folders. I am afraid that your suggestion is not suitable.
How do you think I should complete other bucket* folders?
Thank you.

**Comment by skoren** [comment]
You should not be restarting Canu until all the bucket folders are complete. What happened to all the bucket jobs which were running previously submitted by Canu? 

If any are not complete and you have the input files in ```1-overlapper/results/``` then you can run the bucket manually (using ``` imp.ovlStore.BUILDING/scripts/1-bucketize.sh <bucket number>```) for all the missing buckets or submit the jobs for the missing buckets (using ``` imp.ovlStore.BUILDING/scripts/1-bucketize-jobSubmit.01.sh```).

**Comment by JifengTang** [comment]
I appreciate.
I think imp.ovlStore.BUILDING/scripts/1-bucketize-jobSubmit.01.sh is easier.

But i looked at the scripts roughly yesterday and it seems the scripts also check whether *ovb exist. 
Does the script first check bucket* folders and If they exist then skip them?

**Comment by skoren** [comment]
The ```imp.ovlStore.BUILDING/scripts/1-bucketize-jobSubmit.01.sh``` doesn't run any of the bucketizing, just submits to the grid. The ```imp.ovlStore.BUILDING/scripts/1-bucketize.sh``` is safe, it will check for existence and skip any completed jobs, it will also remove any intermediate unfinished outputs before re-running.

**Comment by JifengTang** [comment]
My 1-bucketize.jobSubmit-01.sh is empty somehow.  It may be overwritten.
In the folder imp.ovlStore.BUILDING 
I run scripts/1-bucketize.sh 381
but It complains about  Error: I need SGE_TASK_ID set, or a job index on the command line.
Can you show an example of "1-bucketize-jobSubmit.01.sh"?
Then I will create mine.
Thank you very much.

**Comment by skoren** [comment]
The command you posted ```sh scripts/1-bucketize.sh 381``` should work, it can run on the command-line without the SGE_TASK_ID. Can you post the contents of that file?

The ```1-bucketize-jobSubmit.01.sh``` varies from grid to grid, here is an example but you will likely need to edit it to match the resource parameters on your grid:
```
#!/bin/sh

qsub \
  -l mem_free=5g -pe thread 1 -S /bin/sh -j y -o logs/1-bucketize.\$TASK_ID.out \
  -cwd -N "ovB_asm" \
  -t 1-401 \
  ./scripts/1-bucketize.sh 0 \
> ./scripts/1-bucketize.jobSubmit-01.out 2>&1
```

**Comment by JifengTang** [comment]
I modified your command. It seems working.

I retried "sh scripts/1-bucketize.sh 381". It worked as well.
I looked my history. The error possibly is due to I used 0381.
See the information below.

ubuntu@16090118canu-master:/mnt/process/Canu/CanuAss16/correction/imp.ovlStore.BUILDING$ sh scripts/1-bucketize.sh 0381>0381.out &
[1] 3564
ubuntu@16090118canu-master:/mnt/process/Canu/CanuAss16/correction/imp.ovlStore.BUILDING$ Error: I need SGE_TASK_ID set, or a job index on the command line.

**Comment by JifengTang** [comment]
Thanks a lot. Your help is great useful for us.

**Comment by JifengTang** [comment]
I know job 100 was completed previous time. 
I see it is still submited to SGE
    1 0.55500 ovB_imp    ubuntu       r     12/21/2017 14:54:06 all.q@16090118canu-node004         1 100
From the log file. It indicates that job is successful.

Why the job is not released the core for the remaining jobs?
what is the job doing?
Thank you very much.

ubuntu@16090118canu-master:/mnt/process/Canu/CanuAss16/correction/imp.ovlStore.BUILDING/logs$ more 1-bucketize.100.out
Running job 100 based on SGE_TASK_ID=100 and offset=0.

Attempting to increase maximum allowed processes and open files.
  Max processes per user limited to 1967909, no increase possible.
  Changed max open files from 1024 to 4096 (max 4096).

maxError fraction: 1.000 percent: 100.000 encoded: 4095
Bucketizing ../1-overlapper/results/000100.ovb
Success!
Running job 100 based on SGE_TASK_ID=100 and offset=0.
Bucket bucket0100 finished successfully.

**Comment by skoren** [comment]
The array job specification (```-t 1-401```) will launch all jobs, regardless of if they have finished. SGE has no way to know if a specific job is successful. The Canu script will recognize there is nothing to do and exit, that is what I mentioned in an earlier comment. You can see in the output, rather than running again, it just said "finished successfully".

**Comment by JifengTang** [comment]
It is so pity. The disk is still not enough.
2.0T    1-overlapper
14T     imp.ovlStore.BUILDING

320 out of 401 jobs have been done.
give up. I am leaving "corMhapSensitivity=normal" out.
