### ISSUE TITLE
canu read correction stage - confused about memory

### ISSUE THREAD

**Issue by mw55309** [marbl/canu#736]
So I am using Canu 1.6 on some nanopore data.

We're at the correction stage, and all my jobs are failing at the 1-overlapper stage.

My precompute.jobSubmit-01.sh script contains the following:

```sh
#!/bin/sh

qsub \
  -l h_vmem=3456m -pe sharedmem 16 -l h_rt=240:00:00 -P roslin_faang -V -R y -j y -o precompute.\$TASK_ID.out \
  -cwd -N "cormhap_tworuns.hic" \
  -t 1-16 \
  ./precompute.sh 0 \
> ./precompute.jobSubmit-01.out 2>&1
```

Doing the maths, this is asking for 16 * 3456m of RAM = 39296m.  Great

But then if I look in precompute.sh or mhap.sh I have the same java command:

```sh
java -d64 -server -Xmx55296m \
    -jar  $bin/mhap-2.1.2.jar  \
    --repeat-weight 0.9 --repeat-idf-scale 10 -k 16 \
    --num-hashes 768 \
# etc
```

It doesn't take long to figure out the 55296m request to jave is bigger than the 39296m to qsub, and lo-and-behold that's what all the errors are about:

```sh
Running job 6 based on SGE_TASK_ID=6 and offset=0.
Dumping reads from 405001 to 486000 (inclusive).

Starting mhap precompute.

Error occurred during initialization of VM
Could not reserve enough space for 56623104KB object heap
Mhap failed.
```

So I guess my question is why is the job submission script requesting less memory than the java script ends up requesting?  

Am I doing something wrong here?

Cheers
Mick

**Comment by skoren** [comment]
It should just be dividing total memory by number of cores so not sure how the numbers for the SGE request and the script would be different. What's the preamble for the resources it detects and what's the exact Canu command you are using?

**Comment by skoren** [comment]
The host lists come from qhost so it is whatever is being reported from there. However, it looks like it picked 54GB and the JVM is requesting 54GB so I'm not sure how the submit command is ending up with a different memory amount. Without some other parameter to change it, it should just take 54/16 per core.

**Comment by brianwalenz** [comment]
Everything looks fine to me.  Canu asked for 16 * 3456 = 55296 MB memory, java tried to allocate 55296 MB memory.

The odd value of 54 GB comes from Canu wanting to use those 2 hosts with 16 CPUs and 54GB RAM.  It was happy dropping both the memory request and JVM size to get them.

The failure seems to be from either your grid allowing a 54GB job on a machine that can't actually support a job requesting that much, or from Canu making a job of maximum size.

A simple fix is to use mhapMemory=60 (in your .canu or canu.defaults) to exclude those pesky nodes, and give the other nodes a small bit of breathing room.  Or =66 to exclude the 64GB nodes too.  I might drop the JVM request size by 1GB anyway.
