### ISSUE TITLE
Can I modify the weight in MHAP

### ISSUE THREAD

**Issue by bzvew** [marbl/canu#737]
Hi, I'm testing some idea using Canu, and I wonder if I can modify the _tf-idf_ weight in MHAP from source code or using some parameter of Canu? Thank you!

**Comment by skoren** [comment]
There is a pass-through parameter ```corMhapOptions``` which will be passed through directly to MHAP so you can modify the scaling of the tf-idf weight or specify any arbitrary MHAP parameters. Whatever you specify will overwrite the defaults. There are options within MHAP to control how strong the repeat suppression is, to completely discard repeat k-mers, or to do only idf not tf-idf weighting. You can get a full list of MHAP parameters by running the jar file without any options ```java -jar canu/*/bin/mhap*.jar```
