### ISSUE TITLE
About corMhapSensitivity

### ISSUE THREAD

**Issue by jhtrujillo** [marbl/canu#739]
Hello again, 

I was wondering what is the difference between corMhapSensitivity = normal and corMhapSensitivity = high. I also wondered what is the realation of this parameter (corMhapSensitivity) with correctedErrorRate.

Thank you very much.

**Comment by skoren** [comment]
You can see the difference in the logs for mhap parameters. The high sensitivity increases the number of hash tables and decreases the threshold for a hit to be evaluated. For sensitive:
```
-- PARAMETERS: hashes=768, minMatches=2, threshold=0.73
```
and normal:
```
-- PARAMETERS: hashes=512, minMatches=3, threshold=0.78
```

If you want more details on those values, you can read the original MHAP paper which has some parameter sweeps of these parameters in the supplementary data. In practice, these were what we found to work well in many cases. ```correctedErrorRate``` is not used by MHAP directly. MHAP will find all the alignments given its settings and estimate an identity. That identity will be filtered based on the ```correctedErrorRate``` setting.
