### ISSUE TITLE
alignGFA: Assertion failed

### ISSUE THREAD

**Issue by nottwy** [marbl/canu#743]
Dear developers,

Now I meet this problem. Do you have any suggestion?

alignGFA: overlapInCore/libedlib/edlib.C:1151: int obtainAlignment(const unsigned char*, const unsigned char*, int, const unsigned char*, const unsigned char*, int, int, int, unsigned char**, int*): Assertion `score_ == bestScore' failed.

version: canu 1.5

thanks a lot.

**Comment by skoren** [comment]
First option would be to try assembling the trimmed reads with the latest release instead of 1.5 to see if it works.

**Comment by nottwy** [comment]
That's a good choice.
And I choose to skip it as you suggested in other issue.
3ku~
