### ISSUE TITLE
Will canu run with Pacbio sequel data?

### ISSUE THREAD

**Issue by lakhujanivijay** [marbl/canu#745]
I have PacBio sequel data in which all quality symbols for all reads are "!" (technically that's a phred score of zero). However it seems like this is expected.

When I am trying to run the assembly with the PacBioi fastq file, it fails but when I try with fastq converted fasta file, it finished without any error.

Has Canu been tested on sequel data (fastq format)?

**Comment by brianwalenz** [comment]
How did it fail?  Canu will check - and complain - if too many bases are low quality.  The error message includes directions on how to ignore these checks.

Canu doesn't use the QV's at all.  We probably need to rethink how picky we need to be on the input data.  It would indeed appear that Sequel data has no valid QV score.

https://bioinformatics.stackexchange.com/questions/885/which-quality-score-encoding-does-pacbio-use

**Comment by skoren** [comment]
The QV check is currently disabled in the code (e.g. https://github.com/marbl/canu/blob/master/src/stores/gatekeeperCreate.C line 300) and I've definitely run PacBio fastq files with all `!` QV values with the 1.6 release so I don't think QVs are the issue. There might be another problem with the fastq file that is causing the error. What's the error output.

**Comment by brianwalenz** [comment]
Idle.
