### ISSUE TITLE
correct step Failed determine the sequencing technology of the reads.

### ISSUE THREAD

**Issue by U201412486** [marbl/canu#749]
Hi,
I use canu 1.6 (Linux) to assemble a insect genome.

This is the command in my first step:
canu -correct -p canu -d workdir genomeSize=700m -pacbio-raw  pacbio-raw.fasta

And,this is the log of correcting step above.

ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   ERROR: Failed to determine the sequencing technology of the reads.
ABORT:
I do not understand why it did not work with the command even though I try restarting again.
Do you have any idea? :)

**Comment by brianwalenz** [comment]
Nope, no ideas.

Did it do any processing, or immediately fail?

What's in 'workdir/correction/*gkpStore/libraries.txt'?

I don't think it'll help, but try renaming the reads so that 'pacbio-raw' isn't present in the name.

What's the full canu output from a fresh run (e.g, using '-d workdir2')?

**Comment by skoren** [comment]
Closing, inactive and most of this logic has changed since the 1.6 release.
