### ISSUE TITLE
Corrected reads take more time to run than raw reads

### ISSUE THREAD

**Issue by miguelpmachado** [marbl/canu#75]
Hi
In our lab we have some MiniOn runs, and before I know about CANU I corrected those reads with Nanocorrect and it took around 2 months to correct reads from one run.
And now, since I have both corrected and raw reads, I thought of running CANU with both data.
I was expecting that corrected reads take less time to run than raw reads, but it was the other way around:
<code>time canu -p corrected_reads_2 -d ./corrected_reads_2 genomeSize=2.1m maxMemory=10 maxThreads=4 -nanopore-corrected /home/mpmachado/BS313V.200_2d.corrected.fasta)</code>
>real    976m54.460s
>user    3789m23.241s
>sys     1m9.312s

<code>time canu -p uncorrected_reads_2 -d ./uncorrected_reads_2 genomeSize=2.1m maxMemory=10 maxThreads=4 -nanopore-raw /scratch/mpmachado/minion/GBS313V.200_2d.fasta</code>
>real    463m3.804s
>user    1553m3.544s
>sys     99m10.648s

`canu --version`
>Canu v1.1 (+18 commits) r7396 91906b6ce56217d765cf1938696ced0e738ca8a3.

Is this normal? Do you know why is it happens?
Thank you in advance.
Best regards,
Miguel

**Comment by brianwalenz** [comment]
Nice sanity test.

I'll guess coverage differences.  Canu only corrects the longest 40x (or so) of reads.  Compare the unitigging.html for both.  It doesn't report coverage, but does report number of reads and bases (and not much else at the moment).

**Comment by miguelpmachado** [comment]
Dear Brian,
Thanks for your reply.
In fact, for corrected reads it used all the 26847 reads, while without the correction step it used 8369 reads.
By the way, do you know which one would be more reliable?
Thank you once more.
Best regards,
Miguel

**Comment by skoren** [comment]
We generally use the longest set of reads for assembly because the longest reads are most informative and higher coverage doesn't always lead to better assembly so I think relying on the subset is fine.
