### ISSUE TITLE
Correcting with 1.6, trimming and assembling with tips

### ISSUE THREAD

**Issue by MattStata** [marbl/canu#750]
Hi, I have a quick question.  I put my genome assemblies on the back-burner for a little while and am going to give it another shot now... As you probably recall from my previous posts here, I have one species that keeps encountering problems during trimming with the 1.6 release, and cannot get past this step no matter what I do for some reason.  In a previous thread Sergey suggested correcting with 1.6 and assembling with the tip.  I am wondering, is it okay to also do the trimming with the tip, i.e. is the bug in the tips confined to the correction stage?  The 1.6 release cannot get past generating the XXX.ovlStore.BUILDING folder - in particular it freezes up when generating three specific folders, create0444, create0446, and create0454, and generates core dumps, even if I delete the entire folder and start it over, and no matter how much I increase the available memory.  If the bug is definitely confined to correction then I imagine it should be okay to trim and assembly with the tip, but I figured I'd ask before I use all those server resources.

**Comment by skoren** [comment]
Yes, only correction matters so you can do trimming and assembly with tip.

**Comment by MattStata** [comment]
Hi Sergey,

Thanks for your assistance through all of this.  I tried proceeding this way, calling a newly-compiled tip version of the program as follows:

canu -trim -p AROS -d trim_with_tip gridOptions='-A def-rsage --time=1400 --nodes=1 --mem=128000M' genomesize=1g minMemory=100000M maxMemory=100000M minThreads=32 maxThreads=32 merylMemory=100000M merylThreads=32 ovsMemory=100000M ovbMemory=100000M -pacbio-corrected AROS.correctedReads.fasta.gz

With the AROS.correctedReads.fasta.gz being generated with the 1.6 version.

Unfortunately, it seems whatever is causing Canu 1.6 to irreparably stall while generating the ovlStore.BUILDING folder is the result of something that v1.6 is doing during correction, because the tip version stalls *exactly* the same, down to the three folders, create0444, create0446, and create0454 (however, the tip version made it through trimming just fine if correction was also done with the tip.  So, the tip gets through correction and trimming without causing this problem but results in poor assembly, while 1.6 seems to hiccup somewhere during correction in a way that prevents either version of the software from getting through the trimming.  AND this problem did not occur with my other, related species, which was sequenced in the same way -- v1.6 managed to complete for this species.

Do you have any idea what might be causing this and how I might proceed?

**Comment by skoren** [comment]
There isn't really a way to stall at that step, unless you are running out of space. It's just binning existing data. 

Your command does not look correct. Canu isn't going to interpret the M argument for the memory (like merylMemory/ovsMemory/etc). I'm guessing that may be causing an issue and you got lucky running the tip. Asking for 100gb is also quite large for this step, the defaults are less than 10gb and I've personally never used more than 32. I would remove the full ovlStore.BUILDING folder and change the command to:
```
canu -trim -p AROS -d trim_with_tip gridOptions='-A def-rsage --time=1400 --nodes=1' GridEngineMemoryOption="--mem=MEMORY" genomesize=1g minMemory=100 maxMemory=100 minThreads=32 maxThreads=32 merylMemory=100 merylThreads=32 ovsMemory=20 ovbMemory=20 -pacbio-corrected AROS.correctedReads.fasta.gz
```
and see what happens then. If you can, monitor your I/O performance too because this step generates a lot of writes. If any buckets failed they will have more information in the ```ovlStore.BUILDING/logs/1-bucketize.*.out``` files

**Comment by MattStata** [comment]
Hi Sergey,

Thanks, I will try this.  The reason for requesting so much memory is because the folks at the server suggested that if I requested whole nodes it would actually run faster because of the way the nodes are allocated to the scheduler, and that is the memory size available.

Regarding why it was stalling here, it definitely was not running out of space.  The logs didn't really provide any insight, just saying 'Aborted' and 'core dumped.'

Hopefully your corrected command works.  Thanks!

**Comment by skoren** [comment]
Aborted or core dumped should give more information leading up to the error on where/what caused it to abort. It is possible system errors caused the job to abort or fail (if a node lost network connectivity). 

You also don't have to require whole nodes for the jobs either.

**Comment by MattStata** [comment]
Attached is the entire text of one of the .out files for the createxxxx folders that result in core dumps.  The reason they suggested whole nodes is due to how the server is set up, apparently only something like 20% of the server is available for partial-node jobs while the rest must be scheduled as whole nodes.
[1-bucketize.3256377_454.out.txt](https://github.com/marbl/canu/files/1615969/1-bucketize.3256377_454.out.txt)

**Comment by skoren** [comment]
Bad alloc is suspicious, seems like it could be a corrupt file. Try following my suggestion above to remove the offending ovb and counts files, re-run the overlap.sh command manually and then re-start canu with my command (after removing ovlStore.BUILDING)

**Comment by MattStata** [comment]
Hi again.  I have tried numerous times to get past this issue along the lines you've suggested.  I've modified the command as you said, I've tried resuming as suggested and also just deleting the entire ovlStore folder and starting over, and even starting straight from the original trim command with everything deleted.  I've tried with a few different memory arguments for ovsMemory and ovbMemory, and it always fails the same way, although now it is failing on a different set of bucket folders -- now the failure seems to be consistently on 418, 420, 424, 426, 428, 430, 448, and 452.  I don't know if it means anything but it seems a little odd that these are all evenly numbered?  Maybe I need to start over again right from the beginning with the correctly written memory arguments?  Any thoughts or suggestions would be greatly appreciated.

**Comment by skoren** [comment]
Your filesystem probably can't support the concurrency of I/O.  It's not clear from your last comment if you tried re-running the overlap.sh script for just the failed buckets and re-running those buckets manually as well before resuming? If that didn't work, your best option would be to re-run the trimming step but limit the concurrency of the jobs, either by requesting a limited set of nodes with ```gridOptions``` or specifying array job size limits (see issue #756).

**Comment by MattStata** [comment]
Sorry, yes I did try re-running overlap.sh as suggested, and when that didn't work I deleted the entire trimming output folder and started over with the memory specified correctly.  I'll read the issue you linked to and see if anything there helps, thanks.
