### ISSUE TITLE
seg fault during read correction

### ISSUE THREAD

**Issue by fochtmanb** [marbl/canu#751]
Hello,
   I am trying to assemble the ecoli_p6_25x.filtered.fastq reads from the quickstart guide and am failing during the correction step of the process.
   Using the following params for correction:  -correct -p output gnuplotTested=true genomeSize=5m -pacbio-raw reads.fastq
    In the error file correction/2-correction/correction_outputs/0001.err I get the following message 
Failed with 'Segmentation fault'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::102 in _Z17AS_UTL_catchCrashiP7siginfoPv()
(null)::0 in (null)()
(null)::0 in (null)()
falcon_sense/falcon_sense.C::149 in main()
(null)::0 in (null)()
(null)::0 in (null)()
Thank you for any insight or comments.

**Comment by skoren** [comment]
What is the version of Canu you are running? What is your system type (linux/max/etc)? Did you compile from source or use the binaries?

**Comment by fochtmanb** [comment]
version 1.6 on a Linux x86_64 system run from the binaries

**Comment by skoren** [comment]
First suggestion would be to try building the release from source instead.

**Comment by fochtmanb** [comment]
Thank you. I will try it but I should add that this same binary has worked
fine for other samples.

**Comment by brianwalenz** [comment]
I'm finishing up a large rewrite of this area - in particular, the part that claimed to fail no longer exists - so don't expect a fix until the next release.  The release should be out in a few weeks.

**Comment by fochtmanb** [comment]
Hi,
   Do you have an expected release date? I have several samples which fail at this area in the code.
