### ISSUE TITLE
Failed with exit code 134.  (rc=34304)

### ISSUE THREAD

**Issue by LarsenLa** [marbl/canu#753]
Hi there,

I would like to ask you for help since Canu has been crashing in this assembly every time and since I am a beginner I cannot figure out why.

I did use default settings running the assembly and ran it on Linux.

This is the log file of the error.

generateCorrectionLayouts: stores/ovStoreHistogram.C:706: uint16 ovStoreHistogram::overlapScoreEstimate(uint32, uint32): Assertion `_scores[id].points[cp-1] < coverage' failed.

Failed with 'Aborted'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::102 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
stores/ovStoreHistogram.C::706 in _ZN16ovStoreHistogram20overlapScoreEstimateEjj()
correction/generateCorrectionLayouts.C::79 in _Z14loadThresholdsP7gkStoreP7ovStorePcj()
correction/generateCorrectionLayouts.C::335 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
Aborted (core dumped)

Thank you for every advice!

Adam

**Comment by brianwalenz** [comment]
No solution, just a bunch of questions.

Can you share the data?
Which version is this (it's not the 1.6 release, and it's not the latest)?
Did you update Canu in the middle of an assembly?
Is it small enough to restart from the start with the latest code, or with the 1.6 release?

**Comment by brianwalenz** [comment]
Idle.
