### ISSUE TITLE
How are gfa files generated

### ISSUE THREAD

**Issue by chklopp** [marbl/canu#754]
Hi,

I see differences (different structural patterns in the components) in the graphs produced from the contigs.gfa files for different assemblies, with Bandage.
Understanding how the gfa files are generated (links between elements,...) would help me further in this analysis.
Is this documented?

**Comment by brianwalenz** [comment]
It's not documented, but it relatively simple in principle.  Overlaps are used to 'place' each terminal contig read (the read(s) that touch the end coordinate of the contig) in other contigs.  This overlap is used to 'align' the two contigs.  If all reads that should have an overlap as computed by the 'alignment' do indeed have an overlap, then an edge is formed in the output GFA.

For example, if the first read in contigA aligns to the middle of contigB
```
                -----------contigA-------->
                ----->
                    -------
                         ----------
<-----------contigB--------------
                    -------
                    ----------
                       ----------
```
and the three reads shown in contigB have overlaps to the reads in contig A, then we can confidently predict that contigA and contigB overlap.  If any of these reads fails to overlap, then the two contigs do not overlap and no GFA edge  is created - this would happen if contigA starts with a repeat that aligns to the middle of contigB.

There isn't any filtering for repeats or size of overlap, but there might be filtering for quality of overlap.  If so, it'd the be same filtering used for when assembling reads into contigs.

**Comment by chklopp** [comment]
Thank you,

Would this mean that in an very heterozygote species (in the case where alleles are often not merged) we would see more branching in the graphs because two possible paths exist a many locations in the genome? Could the graph give a hint or even a measure of this type of heterozygocity?

**Comment by gringer** [comment]
Yes, this happens. [Our paper](http://dx.doi.org/10.1186/s12915-017-0473-4) on the genome assembly of Nippostrongylus brasiliensis goes into a bit more detail what different match structures can be formed from 3-way splits in the assembly graph. [Figure 7](https://bmcbiol.biomedcentral.com/articles/10.1186/s12915-017-0473-4#Fig7) may be of particular interest to you.
