### ISSUE TITLE
Error in mix assembly (Pacbio and nanopore)

### ISSUE THREAD

**Issue by tangerzhang** [marbl/canu#757]
I am assembling a 1.7 Gb genome with 80 X pacbio reads and 10 X nanopore reads. The detailed error information are listed below. 
### Command line
canu -s spec.txt -p fish -d mix genomeSize=1.7g -pacbio-raw subreads/m161*.fastq -nanopore-raw nanopore/all.nanopore.raw.fastq
### Spec file:
useGrid=1
gridOptions=-S /bin/bash -q all.q -l mem_free=60g
gridEngineThreadsOption=-pe mpi THREADS
gridEngineMemoryOption=-l mem_total=MEMORY
corOutCoverage=100
ovbMemory=8g
maxMemory=500g
maxThreads=48
ovsMemory=8-500g
ovsThreads=4
oeaMemory=32g
Canu version: 1.6
### Running system:  
SGE grid

### Error information
-- Starting command on Wed Jan 17 12:40:31 2018 with 11894.338 GB free disk space

    cd correction/2-correction
    /public1/home/zhaoq/software/canu-1.6/Linux-amd64/bin/generateCorrectionLayouts \
      -G ../fish.gkpStore \
      -O ../fish.ovlStore \
      -S ./fish.globalScores \
      -c 4 \
      -C 200 \
      -p ./fish.estimate.WORKING

--Finished on Wed Jan 17 14:35:15 2018 (6884 seconds) with 11893.848 GB free disk space
-- Sorting reads by expected corrected length.
-- Sorting reads by uncorrected length.
-- Loading expected corrected read lengths.
Modification of non-creatable array value attempted, subscript -537503629 at /public1/home/zhaoq/software/canu-1.6/Linux-amd64/bin/lib/canu/CorrectReads.pm line 653, <F> line 1797211.

**Comment by brianwalenz** [comment]
That's attempting to load read lengths from file 2-correction/fish.estimate.originalLength.log, and finding what appears to be junk at line 1797211.  This file is generated by sorting fish.estimate.log, which is generated by the generateCorrectionLayouts command you show.

I've never seen something like this before, and would guess that one of the *.log files is getting corrupted somehow.  Grep for 537503629 in the *.log files, and remove (or just rename) the ones it appears in, then restart canu.  If you rename the files, you can compare old vs new.

Rerunning generateCorrectionLayouts will take about 2 hours, but the sorts should be relatively quick.

**Comment by tangerzhang** [comment]
Problem solved! It is very likely data corruption.
