### ISSUE TITLE
Version of the GFA format

### ISSUE THREAD

**Issue by isovic** [marbl/canu#759]
Hi,

The Canu-generated GFA files contain header lines which do not follow the standard for GFA versioning, i.e. the following line:
```
H   VN:Z:bogart/edges
```
should contain the version of the GFA file format in the `VN` tag, instead of the name of an internal tool which generated the GFA (for which a custom tag could be used).
Marking the version of the GFA would be a great feature, because it would allow downstream applications to automatically identify in which format the data is.

Thanks!

P.S. Not really required for this issue, but since it was asked for in the issue disclaimer... :-)
```
$ ./canu --version
Canu 1.6
```

Best regards,
Ivan.

**Comment by brianwalenz** [comment]
Thanks for reporting, it's already been fixed (issue #706).  The next version should be out in three to four weeks.

**Comment by isovic** [comment]
Great, thanks!

Ivan
