### ISSUE TITLE
Some stranger things in contigs.layout.readToTig

### ISSUE THREAD

**Issue by natir** [marbl/canu#760]
Hi,

I want identify read at extremity of my contig, the position of reads in contig are store in contigs.layout.readToTig, maybe some know a better solution to find the read at end of 
contig ?
For the contig 316 I have many read are at end and I see this:
```
17968   316     ungapped        2159589 2159589
22173   316     ungapped        2159589 2159589
12701   316     ungapped        2159589 2159589
```

Read 17968, 22173, 12701 contribute for one base at the end of contig 316 ? or it's bug ?

Dataset used [ERS685290](https://www.ebi.ac.uk/ena/data/view/ERS685290) 

Canu  command line : 
```
canu -p canu -d canu -pacbio-raw data/NCTC/ERR910536.fastq genomeSize=5094834.45437536 correctedErrorRate=0.105 corOutCoverage=40 corMinCoverage=4 maxThreads=10
```

Canu version : 
```
Canu 1.6 (installed by conda)
```

OS information : 
```
Debian 9.3
Not virtual machine
No grid
```

Thanks for your time and work

**Comment by skoren** [comment]
The positions are approximate and are before calling consensus on the contig. They don't get updated after that. I'd guess in this case the contig got longer during consensus and those reads extended past the end but that isn't represented in the layout file.

**Comment by skoren** [comment]
Closing, future releases of Canu will output a bam file of raw read positions so will track this as a feature.
