### ISSUE TITLE
ploidy setting for assembly of nanopore reads

### ISSUE THREAD

**Issue by ishengtsai** [marbl/canu#761]
Hi,

We have been having quite good successes in using canu default + haplomerger2 in assembly of very heterozygous fungal genomes. When revisiting the pipeline to see if there's any improvements, we were wondering if there's a setting in **avoiding collapsing the genome** for Nanopore data please? This should improve the post processing steps, too.

Best,
Jason

**Comment by skoren** [comment]
You can use the same parameters from the FAQ: http://canu.readthedocs.io/en/latest/faq.html#what-parameters-can-i-tweak. Just leave off the ```correctedErrorRate=0.004``` setting.
