### ISSUE TITLE
Combining PacBio and 10X data.

### ISSUE THREAD

**Issue by stueber** [marbl/canu#762]
Dear all 

I am trying to combine PacBio reads with an assembly produced by Illumina-10X technology.
The 10X assembly looks fine and shows good homologies to the PacBio assembly with a lot of
useful (dovetail) overlaps so that a combination looks promising.

The 10X assembly contains occasional gaps, filled with Ns. The number of Ns is the nearest
guess the 10X supernova assembler could find, so it is not always in exact correspondance to
the real number of bases in this gap(s).

Splitting the PacBio assembly and the 10X assembly in overlapping pseudoreads of length 30000
bases  and letting these be assembled again did not work, but produced a segmentation fault in the consensus step.

Here the Unittigging messages:
```
UNITIGGING/OVERLAPS
--   category            reads     %          read length        feature size or coverage  analysis
--   middle-missing          0    0.00        0.00 +- 0.00             0.00 +- 0.00       (bad trimming)
--   middle-hump             0    0.00        0.00 +- 0.00             0.00 +- 0.00       (bad trimming)
--   no-5-prime              0    0.00        0.00 +- 0.00             0.00 +- 0.00       (bad trimming)
--   no-3-prime              3    0.06    30000.00 +- 0.00             0.00 +- 0.00       (bad trimming)
--   low-coverage            0    0.00        0.00 +- 0.00             0.00 +- 0.00       (easy to assemble, potential for lower quality consensus)
--   unique               1910   39.71    30000.00 +- 0.00            30.99 +- 4.50       (easy to assemble, perfect, yay)
--   repeat-cont           126    2.62    30000.00 +- 0.00            58.03 +- 1.26       (potential for consensus errors, no impact on assembly)
--   repeat-dove          1770   36.80    30000.00 +- 0.00            58.66 +- 1.11       (hard to assemble, likely won't assemble correctly or even at all)
--   span-repeat            36    0.75    30000.00 +- 0.00         13756.42 +- 8487.37    (read spans a large repeat, usually easy to assemble)
--   uniq-repeat-cont       48    1.00    29922.65 +- 261.79                              (should be uniquely placed, low potential for consensus errors, no impact on assembly)
--   uniq-repeat-dove      899   18.69    30000.00 +- 0.03                                (will end contigs, potential to misassemble)
--   uniq-anchor            18    0.37    30000.00 +- 0.00          7483.06 +- 8040.76    (repeat read, with unique section, probable bad read)

-- Finished on Mon Jan 22 15:55:39 2018 (72 seconds) with 99545.101 GB free disk space
-- Using slow alignment for consensus (iteration '2').
-- Configured 1 contig and 1 unitig consensus jobs.
-- Consensus jobs failed, tried 2 times, giving up.
--   job ctgcns/0001.cns FAILED.
--   job utgcns/0001.cns FAILED.

ABORT:
ABORT: Canu 1.6
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
Mon Jan 22 15:55:39 CET 2018
```
So i am asking for help :-)

greetings

Kurt

**Comment by skoren** [comment]
There is no official 10x support and I'm not sure what happens when you end up with pseudo reads composed primarily of large gaps in the consensus. You could perhaps increase the consensus error rate (see issue #729) but no guarantees the assembly will make any sense.

I'd recommend using a 10x scaffolder on the pacbio assembly instead.

**Comment by dibyendukumar** [comment]
Just curious, can you use PBjelly on 10x assembly?

**Comment by skoren** [comment]
Yes, you can use PBJelly to fill gaps with PacBio data in a 10x assembly but the gap fill sequence will be lower quality so you'll want to either polish with pilon or arrow or both afterwards.

**Comment by anoronh4** [comment]
do you have any recommendation for a 10X scaffolder? sorry, just that "10X scaffolder" is super confusing to google.
