### ISSUE TITLE
About utgRepeatDeviation

### ISSUE THREAD

**Issue by jhtrujillo** [marbl/canu#764]
Hi, When you said in your paper the following:

"A maximum overlap error rate cutoff is automatically computed from this distribution as **six
MAD**s away from the median, and overlaps with an error greater than this cutoff are not used during graph construction..." in the Graph construction section. Is the value that you define as "six in MADS defined by the utgRepeatDeviation parameter?

Thanks!

**Comment by skoren** [comment]
Yes, that is mostly correct. There are two parameters, utgGraphDeviation and utgRepeatDeviation. You can use different MAD thresholds for both. The default is 6 and 3 (and 3 and 1 for heterzygous genomes when you're trying to split alleles) so you can adjust both if you'd like. Either way the unitigging output ```*.001.filterOverlaps.thr000.num000.log`` gives a report on what the error rate limit ended up being:
```

INITIAL EDGES
-------- ----------------------------------------
12229794 reads are contained
    5612 reads have no best edges (singleton)
   16164 reads have only one best edge (spur) 
            11702 are mutual best
  898728 reads have two best edges 
            41960 have one mutual best edge
           848249 have two mutual best edges


ERROR RATES (22151497 samples)
-----------
mean   0.01194431 stddev 0.00951854 -> 0.03098139 fraction error =   3.098139% error
median 0.00880000 mad    0.00440000 -> 0.02184688 fraction error =   2.184688% error
```
