### ISSUE TITLE
the output of Canu

### ISSUE THREAD

**Issue by wc529** [marbl/canu#765]
Dear All,

Canu output three fasta files "contigs.fasta, unitigs.fasta and unassembled.fasta". while contigs.fasta is "part of the primary assembly". So what is the primary assembly. which one is the final genome assembly? I am confused. Thank you for your help!

Best,

**Comment by skoren** [comment]
The asm.contigs.fasta is the final output of the assembly.  I removed "part" from the documentation to clarify that asm.contigs.fasta is the primary assembly.
