### ISSUE TITLE
canu for large plant genome assembly 

### ISSUE THREAD

**Issue by nanman1** [marbl/canu#767]
I am working on a 2.2 Gb plant genome assembly project. The genome is about 80% repetitive. I am very much interested in using Canu for the genome assembly. I have installed Canu 1.6 on my university cluster which has SLURM grid engine. I am now working on getting the appropriate computational resources. I was therefore wondering if you could provide me following information and the best parameters I can use for the genome assembly:
1) RAM requirement for each Canu stage 
2) Total disk space requirement
3) number of CPUs for each Canu stage

**Any other tips** regarding the assembly process will be highly appreciated.

Thank you

**Comment by dibyendukumar** [comment]
coverage and N50 read-length?
~40Tb space, ~300 gb RAM and >100-200 dedicated CPUs for 2-3 months might be a good start under default parameters.

**Comment by nanman1** [comment]
15X coverage (currently but we are expecting more so the final coverage should be around 50X) and N50 read length is 10kb

**Comment by mjpdejong** [comment]
Data usage of a repetitive 2.8 Gb genome I assembled last summer..

161,335 items, totalling 35.6 TB

So keep track of your data usage ;)

**Comment by gringer** [comment]
If error correction is taking too long, try minimap2 as the mapper for Canu:

    canu overlapper=minimap genomeSize=2.2G ...

**Comment by skoren** [comment]
Are you using PacBio or Nanopore data for the plant? That will affect runtime. For PacBio I'd expect 30-50k cpu hours and maybe 15-30tb. If you are using nanopore, consider using the fast option ```overlapper=mhap utgReAlign=true``` which will be ten times faster than the default.

The above should be ```corOverlapper=minimap```, you definitely don't want it to be used for all overlapping, the assembly will be worse. In my experience minimap is too aggressive at filtering repeats and ends up with a worse assembly. An alternate is to weight down repeats more with mhap:
```corMhapFilterThreshold=0.0000000002 corMhapOptions="--threshold 0.80 --num-hashes 256 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50"``` You only need to worry about it if the initial overlapping is very slow or if you are running out of space.

**Comment by nanman1** [comment]
It's PacBio data.  Thank you!

**Comment by skoren** [comment]
Closing, inactive.
