### ISSUE TITLE
Mhap overlap jobs failed*YIKES*

### ISSUE THREAD

**Issue by elipowel** [marbl/canu#771]
Hi folks,
I keep getting an "Mhap overlap jobs failed" error during an assembly of a bacterial genome.
This is with Canu 1.6, I am running it in via a SLURM submission on a TACC cluster queue.
The SLURM script is:

'''#!/bin/bash
#SBATCH -J n10_YESWECANU           # job name
#SBATCH -o n10_YESWECANU.o%j	   # output and error file name (%j expands to jobID)
#SBATCH -N 8             # total number of nodes requested
#SBATCH -n 32            # total number of mpi tasks requested
#SBATCH -p normal     # queue (partition) -- normal, development, etc.
#SBATCH -t 24:45:00        # run time (hh:mm:ss)

canu  -p N10A28 -d N10A28-pacbio  genomeSize=5m useGrid=false -pacbio-raw m54193_171202_081837.subreads.fastq'''

the genome size is an estimate based on closely related taxa, the useGrid was turned off after some early failures and the fastq was generated though SAMtools from a BAM file of subreads provided by a sequencing core. Each node in this queue has 68 cores and I have to balane nodes and mpi's to keep under my hard limit of 778 SU's.

The job goes merrily through the mhap precompute stage and then starts failing at the 'cormhap' concurrent execution stage.

slurm log file is included

[n10_YESWECANU_o700302.TXT](https://github.com/marbl/canu/files/1683316/n10_YESWECANU_o700302.TXT)

**Comment by skoren** [comment]
First, 1400x coverage, is that accurate? I'd suggest downsampling it to a random 200x.

Your sbatch parameters are spread across nodes, which doesn't make sense if you're running on a single node. You want all your CPUs on a single node. There is also no explicit memory limit requested either, what's the default? You also said these machines have 68 cores but the one Canu is scheduled on is actually 272 cores.

```
-- Detected 272 CPUs and 94 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /bin/sinfo.
-- Grid engine disabled per useGrid=false option.
``` 

I'd guess your grid is killing jobs for exceeding the default memory. One of the output files from the failed jobs in ```correction/1-overlapper/mhap*.out``` would have more information. Limit Canu to whatever memory/threads you request (```maxMemory=32 maxThreads=32```) and change your request to include memory and request 1 node.

**Comment by elipowel** [comment]
Thanks for the input. I was able to reconfigure my memory requirements and get Canu to work. As you noted, the coverage is super high and I would like to run with lower x to see if I can get a better looking assembly. What tool do you recommend for downsampling to a specific coverage? Should I prefilter what goes in there (eg. reads over a certain length etc.)? Cheers.

**Comment by skoren** [comment]
Canu has a built-in one called ```fastqSample```, your read input has to be named something like ```reads.u.fastq``` and it supports filters like length, coverage, etc. For a bacteria, I think a random 200x would be fine, something like:
```fastqSample -I reads -U -O reads200 -g 5000000 -c 200```

**Comment by elipowel** [comment]
Thank you for the help!
