### ISSUE TITLE
Treatment of chimeric reads?

### ISSUE THREAD

**Issue by philippbayer** [marbl/canu#772]
I'm not 100% sure that I understand Canu's treatment of chimeric reads correctly, from the FAQ:

https://github.com/marbl/canu/blob/master/documentation/source/faq.rst#why-do-i-get-less-corrected-read-data-than-i-asked-for
>Some reads are trimmed during correction due to being chimeric or because there wasn't enough evidence to generate a quality corrected sequence. 

Let's assume I got PacBio reads from 3 different regions, one of these reads is chimeric and has one piece from 2 regions each.

During the assembly, will Canu be smart enough to 'split' the read during trimming enough that the read is split into the two pieces from the two regions, which will then be joined into the two sets of contigs? Or will Canu place the read into the region with the longest alignment and then trim the chimeric rest away? The FAQ isn't clear on that

**Comment by brianwalenz** [comment]
The longest is used.

In the cases where the chimer is from multiple passes through the template, forming subreads, the other reads are redundant and won't add anything to the assembly.  For true chimers, any second read will be generally be shorter than average (so not useful to assembly), and usually lower quality (so just 'hard' to assemble anyway - the longest read too - the chimers I've seen in pacbio have all had a large stretch of bases 'mixed' from both regions.)

The 1.6 release and earlier (but not the current git tip code, and not the upcoming 1.7 release) would allow a single raw read to generate multiple corrected reads.  Some chimers were detected here, but nothing was explicitly detected.  Basically, if the chimeric region had little to no coverage, it wouldn't be corrected, resulting in two corrected reads per raw read.

**Comment by philippbayer** [comment]
I see, thank you very much for your detailed answer, I understand what's happening!
