### ISSUE TITLE
Canu exit code 134.  (rc=34304)

### ISSUE THREAD

**Issue by Gon1976** [marbl/canu#773]
Hi Canu!
I am trying to run canu v1.6 compiled in linux.

The command line used: ./canu -correct -d ../../../canuAssembly/ -p Gnome genomeSize=40m  -gnuplotTested=true -nanopore-raw ../../../MinionPass.fasta

It's run until this error:
```
-- Finished on Fri Feb  2 08:30:01 2018 (27 seconds) with 176.1 GB free disk space
----------------------------------------

ERROR:
ERROR:  Failed with exit code 134.  (rc=34304)
ERROR:
ABORT:
ABORT: Canu snapshot v1.6 +230 changes (r8642 96203a3780170cb32ff3c98c3173fb148d1452a5)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to generate correction layouts.
ABORT:
ABORT: Disk space available:  176.1 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (correction/Bere.corStore.err):
ABORT:

and the last 50 lines of Bere.corStore.err is:
ERROR: bogus overlap '     19102      11587  N       0      19     76      26 4294967288  0.068200'
generateCorrectionLayouts: correction/generateCorrectionLayouts.C:189: tgTig* generateLayout(tgTig*, uint16*, uint32, double, double, ovOverlap*, uint32): Assertion `ovlLength < (((uint32)1 << 21) - 1)' failed.

Failed with 'Aborted'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::101 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
correction/generateCorrectionLayouts.C::189 in _Z14generateLayoutP5tgTigPtjddP9ovOverlapj()
correction/generateCorrectionLayouts.C::484 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
Aborted (core dumped)
```
could you help me?

**Comment by brianwalenz** [comment]
Those have generally been caused by incomplete overlap outputs.

I'd just start over -- it's a difficult to track down which job failed, and a little difficult to rerun just that job.

When rerunning, add option 'saveOverlaps=true' to save the intermediate outputs.  If it happens again, these will be very useful to tracking down and fixing the problem.

You can save a little bit of time by removing just the 1-overlapper, 2-correction and *corStore directories from your current assembly and restarting.  This will reuse the 'gatekeeper' read database and mercounts.

**Comment by KFeye** [comment]
Hello!  So, how would one track down and fix the issue?  I'm having the same problem repeatedly from my phage sequencing (first one from Nanopore, want to play with the pipeline before sequencing my library of probiotics).  If it is function of low complexity from a short genome, is it worth fixing or should I move to a more complete sequencing run/genome

**Comment by skoren** [comment]
Are you sure you have the exact same error, that's from a pretty old version of Canu. What is the tail of the canu log report.
