### ISSUE TITLE
corMapSensitivity

### ISSUE THREAD

**Issue by pjm43** [marbl/canu#774]
Just a quick question regarding corMhapSensitivity.  I was having issues with disk space and I read in one of the threads that removing the corMhapSensitivity argument would reduce the disk space requirement (which it did).  I had originally had the corMapSensitivity=normal.  My assembly finished, but is less contiguous that I had hoped.  I have approximately 60X coverage of a 4Gb genome (1/2 RSII, 1/2 sequel).  The read lengths were not as good as I have had on other assemblies (asm.report):

```
[CORRECTION/CORRECTIONS]
--
-- Reads to be corrected:
--   28820130 reads longer than 10897 bp
--   248635716250 bp
-- Expected corrected reads:
--   28820130 reads
--   144840444344 bp
--   0 bp minimum length
--   5026 bp mean length
--   30747 bp n50 length

The assembly statistics:

[UNITIGGING/CONSENSUS]
-- Found, in version 2, after consensus generation:
--   contigs:      26574 sequences, total length 4159065453 bp (including 3723 repeats of total length 76539088 bp).
--   bubbles:      0 sequences, total length 0 bp.
--   unassembled:  1557597 sequences, total length 7353361044 bp.
--
-- Contig sizes based on genome size --
--            NG (bp)  LG (contigs)    sum (bp)
--         ----------  ------------  ----------
--     10     1119112           275   392279181
--     20      831314           685   782612019
--     30      657620          1218  1173772408
--     40      535815          1880  1565109000
--     50      435135          2693  1956198594
--     60      346944          3698  2347305749
--     70      266674          4978  2738420754
--     80      190317          6714  3129655645
--     90      118449          9287  3520816485
--    100       46287         14379  3912031216
```
My question is whether rerunning it with corMapSensitivity=normal would improve the assembly?  That would mean I would need to find additional disk space, but if it would improve the assembly I would attempt to identify the space.  Is there anything else you would suggest?

Thanks,

Jeff

**Comment by skoren** [comment]
What's the full ```asm.report```? Primarily, how long are the reads going into and coming out of correction and what do the k-mer distributions look like? That will give some indication of whether the sensitivity will help or if other settings will. It's also possible if this is a plant genome it is repetitive and won't improve in assembly.

**Comment by pjm43** [comment]
I'm attaching the asm.report here:
[eriantha_all2.report.txt](https://github.com/marbl/canu/files/1690308/eriantha_all2.report.txt)

I would appreciate you looking it quickly to give me your opinion.

Canu was run with the following command:
/zhome/pjm43/bin/canu_v16/canu/Linux-amd64/bin/canu -d eriantha_all2 -p eriantha_all2 genomeSize=3912m maxMemory=500g maxThreads=24 corOutCoverage=40 \
merylMemory=500g merylThreads=24 ovsMethod=parallel \
gridOptions="--qos=pws --time=72:00:00" \
gridOptionsOVS="--mem-per-cpu=10g --time=72:00:00" \
gridOptionsExecutive="--mem-per-cpu=256g --time=71:00:00" \
gridOptionsCORMHAP="--mem-per-cpu=10g --time=47:00:00" \
gridOptionsOBTMHAP="--mem-per-cpu=10g --time=46:00:00" \
gridOptionsCOROVL="--mem-per-cpu=10g --time=69:00:00" \
gridOptionsRED="--mem-per-cpu=12g --time=32:00:00" \
gridOptionsOEA="--mem-per-cpu=12g --time=40:00:00" \
gridOptionsOVB="--mem-per-cpu=12g --time=72:00:00" \
-pacbio-raw `less ./list2.txt`

**Comment by skoren** [comment]
It looks like the correction worked reasonably well. There are some large repeats in this genome which may be limiting your assembly contiguity (looks like 20kb from the overlap report). Do you have an idea of heterozygosity of this genome? You could get an estimate from genome scope (http://qb.cshl.edu/genomescope/) by giving it the histogram of corrected read k-mers (from ```trimming/0-mercounts``` or ```unitigging/0-mercounts```).

You could try to increase sensitivity and specificity by using the  parameters:
```MhapMerSize=17 corMhapOptions=--threshold 0.8 --num-hashes 512 --ordered-sketch-size 1000 --ordered-kmer-size 14 --num-min-matches 3```
which will increase the size of the raw read k-mer (16 looks low for your genome size) and mimics the normal parameters but only keeps the highest scoring overlaps rather than the default.

If your genome is heterozygous, try also adding the parameters from the FAQ too:
```corOutCoverage=200 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50"```

**Comment by pjm43** [comment]
Thanks for the quick response and the insight into the overlap report viz a viz the large repeats - I hadn't noticed that.

The genome should not be heterozygous (selfing species) - but I will give genomescope a try just to verify.

Thanks again for the help!
