### ISSUE TITLE
Error in the 3-overlapbased trimming step

### ISSUE THREAD

**Issue by npbhavya** [marbl/canu#775]
Hi, 

I am running canu1.6 release version on a  cluster with PBS/Torque job handler using the following command 
```
canu -p test-relase-2 -d test-release-2  gridOptions="-l vmem=400gb,walltime=30:00:00" useGrid=true genomeSize=5.8m minReadLength=300 minOverlapLength=150 -nanopore-raw INPUT.fa
```
The job runs the correction step successfully but fails at the trimming step. Here is the error message from canu.out 
```
ERROR:
ERROR:  Failed with exit code 134.  (rc=34304)
ERROR:

CRASH:
CRASH: Canu 1.6
CRASH: Please panic, this is abnormal.
ABORT:
CRASH:   splitReads failed.
CRASH:
CRASH: Failed at /gpfs/hps/soft/rhel7/canu/1.6/Linux-amd64/bin/lib/canu/OverlapBasedTrimming.pm line 157.
CRASH:  canu::OverlapBasedTrimming::splitReads("test-relase-2") called at /gpfs/hps/soft/rhel7/canu/1.6/Linux-amd64/bin/canu line 700
CRASH:
CRASH: Last 50 lines of the relevant log file (trimming/3-overlapbasedtrimming/test-relase-2.2.splitReads.err):
CRASH:
CRASH:
```
The error message in the trimming/3-overlapbasedtrimming/test-relase-2.2.splitReads.err file is 
```
### Processing from ID 1 to 216287 out of 216287 reads, using errorRate = 0.14
splitReads: overlapBasedTrimming/splitReads.C:365: int main(int, char**): Assertion `w->clrBgn >= w->iniBgn' failed.

Failed with 'Aborted'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::102 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
overlapBasedTrimming/splitReads.C::365 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
```
Any idea how I can fix this error

**Comment by brianwalenz** [comment]
No ideas.  That's generally been pretty stable code.

Can you share the reads and/or the assembly directory?

Omitting the read and overlap length limits might get around whatever problem it is having.  The defaults are 1000bp reads and 500bp overlaps.

What does the read length histogram look like in canu's *.report file?

**Comment by RajneeshSrivastava** [comment]
Hi Brian,
Thanks for the reply to the issue raised by my colleague. Here is the distribution that I have 
for the dataset. 
[read_distribution.pdf](https://github.com/marbl/canu/files/1712352/read_distribution.pdf)
Please note, this is cDNA data (not the direct DNA sequence dataset), thats why the reads are peaking up at ~500 bp. Increasing the min overlap to 500 might cause huge data loss.
We want to customize Canu parameters for this dataset to assemble denovo transcripts. I understand, Canu is originally developed for denovo DNA assembly. Any suggestions to follow up the main problem and any solution to the issue mentioned above ?

Thanks in advance,
Rajneesh

**Comment by skoren** [comment]
Assembling the transcripts hasn't been tested at all and isn't going to work. Assembly should also not be necessary because pacbio/nanopore is typically long enough to sequence a full length transcript. You'd want to do clustering/isoform identification not assembly at that point. The corrected reads can be used as input into a transcript assembler but they will still be higher error than short read data so I'm not sure that would work either.

**Comment by skoren** [comment]
Closing, inactive.
