### ISSUE TITLE
gatekeeper store exists, but contains no reads

### ISSUE THREAD

**Issue by wispingwillow** [marbl/canu#778]
Hi,
I am having trouble using the canu command and it keeps giving me the same message no matter what parameters I set. My command is:
```
$ canu-1.6/Darwin-amd64/bin/canu -p canu -d canu_outdir genomeSize=2.7m gnuplotTested=true -pacbio-raw allreads.fastq.gz
```
And I've also used more parameters:
```
$  canu-1.5/Darwin-amd64/bin/canu -p canu -d canu_outdir genomeSize=2.7m gnuplotTested=true corMhapMerSize=12 corMhapSensitivity=high corMinCoverage=2 minReadLength=100 minOverlapLength=50 corMaxEvidenceErate=0.3 corOutCoverage=100 contigFilter="2 1000 0.2 0.2 2" -pacbio-raw allreads.fastq.gz
```
Both give me the same result:
 ```
                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |  algorithm
--        -------  ------  --------   --------  -----------------------------
-- Local: meryl      8 GB    4 CPUs x   8 jobs  (k-mer counting)
-- Local: cormhap    6 GB   16 CPUs x   2 jobs  (overlap detection with mhap)
-- Local: obtovl     8 GB    8 CPUs x   4 jobs  (overlap detection)
-- Local: utgovl     8 GB    8 CPUs x   4 jobs  (overlap detection)
-- Local: cor        6 GB    2 CPUs x  16 jobs  (read correction)
-- Local: ovb        3 GB    1 CPU  x  32 jobs  (overlap store bucketizer)
-- Local: ovs        8 GB    1 CPU  x  32 jobs  (overlap store sorting)
-- Local: red        2 GB    4 CPUs x   8 jobs  (read error detection)
-- Local: oea        1 GB    1 CPU  x  32 jobs  (overlap error adjustment)
-- Local: bat       13 GB    4 CPUs x   8 jobs  (contig construction)
-- Local: cns       13 GB    4 CPUs x   8 jobs  (consensus)
-- Local: gfa        8 GB    4 CPUs x   8 jobs  (GFA alignment and processing)
--
-- Found PacBio uncorrected reads in the input files.
--
-- Generating assembly 'canu' in '/home/bi410/student20/s441/canu_outdir'
--
-- Parameters:
--
--  genomeSize        2700000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0750 (  7.50%)
--
--
-- BEGIN CORRECTION
--
-- WARNING:
-- WARNING:  Existing sequence inputs used.
-- WARNING:
----------------------------------------
-- Starting command on Fri Feb  9 19:40:58 2018 with 312.741 GB free disk space

    cd correction
    /home/bi410/student20/s441/canu-1.6/gatekeeperCreate \
      -minlength 1000 \
      -o ./canu.gkpStore.BUILDING \
      ./canu.gkpStore.gkp \
    > ./canu.gkpStore.BUILDING.err 2>&1

-- Finished on Fri Feb  9 19:40:58 2018 (lickety-split) with 312.741 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 127.  (rc=32512)
ERROR:

ABORT:
ABORT:
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   gatekeeper store exists, but contains no reads.
ABORT:
```
I am working on a 64-bit operating system with  a x64-based processor. I've read the other issues that include this same problem, but their solutions did not work for me. Could it be issues with the raw reads I am working with?

Thank you.

**Comment by skoren** [comment]
First, the warning indicates you are running in a directory that already exists and had output from a previous run. Make sure you completely remove ```canu_outdir```

Second, the ```canu.gkpStore.BUILDING.err``` will have more information on any errors loading the sequences.

**Comment by wispingwillow** [comment]
I removed the file completely and used the same command: 
```
 canu-1.6/Darwin-amd64/bin/canu -p canu -d canu_outdir genomeSize=2.7m gnuplotTested=true -pacbio-raw allreads.fastq.gz
```
Canu still won't run the reads through and 'failed with exit cod 127' : 
```
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |  algorithm
--        -------  ------  --------   --------  -----------------------------
-- Local: meryl      8 GB    4 CPUs x   8 jobs  (k-mer counting)
-- Local: cormhap    6 GB   16 CPUs x   2 jobs  (overlap detection with mhap)
-- Local: obtovl     8 GB    8 CPUs x   4 jobs  (overlap detection)
-- Local: utgovl     8 GB    8 CPUs x   4 jobs  (overlap detection)
-- Local: cor        6 GB    2 CPUs x  16 jobs  (read correction)
-- Local: ovb        3 GB    1 CPU  x  32 jobs  (overlap store bucketizer)
-- Local: ovs        8 GB    1 CPU  x  32 jobs  (overlap store sorting)
-- Local: red        2 GB    4 CPUs x   8 jobs  (read error detection)
-- Local: oea        1 GB    1 CPU  x  32 jobs  (overlap error adjustment)
-- Local: bat       13 GB    4 CPUs x   8 jobs  (contig construction)
-- Local: cns       13 GB    4 CPUs x   8 jobs  (consensus)
-- Local: gfa        8 GB    4 CPUs x   8 jobs  (GFA alignment and processing)
--
-- Found PacBio uncorrected reads in the input files.
--
-- Generating assembly 'canu' in '/home/bi410/student20/s441/canu_outdir'
--
-- Parameters:
--
--  genomeSize        2700000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0750 (  7.50%)
--
--
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Sat Feb 10 14:25:56 2018 with 312.741 GB free disk space

    cd correction
    /home/bi410/student20/s441/canu-1.6/gatekeeperCreate \
      -minlength 1000 \
      -o ./canu.gkpStore.BUILDING \
      ./canu.gkpStore.gkp \
    > ./canu.gkpStore.BUILDING.err 2>&1

-- Finished on Sat Feb 10 14:25:56 2018 (lickety-split) with 312.741 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 127.  (rc=32512)
ERROR:

ABORT:
ABORT:
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   gatekeeper store exists, but contains no reads.
```
Could there be a problem with memory space?

**Comment by brianwalenz** [comment]
That looks like it can't find, or maybe can't run, the 'gatekeeperCreate' command.  Is there any error in the canu.gkpStore.BUILDING.err file?

The path looks suspicious, too.  Is should be something like `..../canu-1.6/Linux-am64/bin/gatekeeperCreate`.

From within in the correction directory - the same place where that .err file is - can you run the same gatekeeperCreate command as shown (but without the redirect):
```
/home/bi410/student20/s441/canu-1.6/gatekeeperCreate \
      -minlength 1000 \
      -o ./canu.gkpStore.BUILDING \
      ./canu.gkpStore.gkp
```
or with adding `Linux-amd64/bin/`?

**Comment by wispingwillow** [comment]
Hi,
It has finally worked. For some reason it wouldn't work with canu-1.6.Darwin_amd64.tar.xz asset and once I downloaded and launched canu-1.6.Linux_amd64.tar.xz, it has started processing the reads. I used the command:
```
canu-1.6/Linux-amd64/bin/canu -p canu -d canu_outdir genomeSize=2.7m gnuplotTested=true -pacbio-raw allreads.fastq.gz
```
Thank you so much for your help!

**Comment by raw937** [comment]
I have a similar error. 
-- BEGIN CORRECTION
--
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `df -P -k /data/friesen/UAri/ftp.genome.arizona.edu/Trifolium-2_(bifidum)_40pM/bifidum/correction'
----------------------------------------
-- Starting command on Thu Mar  5 11:30:05 2020 with 0 GB free disk space

    /opt/apps/canu/1.3/bin/gatekeeperCreate \
      -minlength 1000 \
      -o /data/friesen/UAri/ftp.genome.arizona.edu/Trifolium-2_(bifidum)_40pM/bifidum/correction/bifidum.gkpStore.BUILDING \
      /data/friesen/UAri/ftp.genome.arizona.edu/Trifolium-2_(bifidum)_40pM/bifidum/correction/bifidum.gkpStore.gkp \
    > /data/friesen/UAri/ftp.genome.arizona.edu/Trifolium-2_(bifidum)_40pM/bifidum/correction/bifidum.gkpStore.BUILDING.err 2>&1
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `cd /data/friesen/UAri/ftp.genome.arizona.edu/Trifolium-2_(bifidum)_40pM/bifidum/correction && /opt/apps/canu/1.3/bin/gatekeeperCreate \'
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `df -P -k /data/friesen/UAri/ftp.genome.arizona.edu/Trifolium-2_(bifidum)_40pM/bifidum/correction'

-- Finished on Thu Mar  5 11:30:05 2020 (lickety-split) with 0 GB free disk space  !!! WARNING !!!
----------------------------------------
ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'gatekeeper store exists, but contains no reads'.

#assemble
canu -p bifidum -d bifidum genomeSize=500m -pacbio-raw m64041_191111_190658.subreads.fastq.gz

HELP?

**Comment by skoren** [comment]
Are you really using Canu 1.3? That is extremely old and not supported. I suggest updating to the latest release and trying again and opening a new issue if it fails (with the full output of the canu run).

**Comment by raw937** [comment]
ah okay. I will give the new one a go.
