### ISSUE TITLE
trimming reads prior to running canu

### ISSUE THREAD

**Issue by TinaH10** [marbl/canu#779]
Hello! 
I am on my second canu run, trying to adjust some of the parameters for low coverage (~20X) data and I am wondering if it would make any sense to filter and trim reads PRIOR to running canu, for example by running them through Nanofilt

https://github.com/wdecoster/nanofilt

Which allows to trim the ends and by size. Would this be helpful or rather hinder the assembly using canu? 

Thank you!

**Comment by brianwalenz** [comment]
I feel it will be unlikely to hurt, but also unlikely to help.  Both read correction and Canu's trimming use local alignments, so shouldn't be affected by crud on the end of the read.  However, with low coverage, there might not be enough evidence to handle the crud correctly, and so trimming could be beneficial.

A worthy experiment, but to be useful (for learning about parameters) remember to adjust only one parameter at a time.

I'm not a fan of trimming based on QV's, so avoid that.

**Comment by TinaH10** [comment]
Thank you very much for your response. Maybe I can add these related question for low coverage data:

For low coverage data you recommend 5 iterations of read corrections using these parameters:

corOutCoverage=500 corMinCoverage=0 corMhapSensitivity=high

In a different place in the manual you write:
For less than 30X coverage, increase the allowed difference in overlaps by a few percent 
correctedErrorRate=0.16

Question 1) shall I apply that different correctedErrorRate also to the 5 iterations of read correction?
Question 2) would you mind explaining exactly what these 3 parameters (corOutCoverage=500 corMinCoverage=0 corMhapSensitivity=high) mean? Would it make sense to vary those too? I understand, I should only vary one at a time.

Thank you!

**Comment by skoren** [comment]
Nope, 5 rounds are only recommended for low quality not low coverage data. That shouldn't be necessary for recent nanopore data. So the only thing you need is to increase the error rate. You can also try the faster overlapping option (```overlapper=mhap utgReAlign=true```) to make the assembly run faster.

**Comment by TinaH10** [comment]
Ah, ok! I misread that! Thank you. I will do that!
