### ISSUE TITLE
Problems using Canu assembly with Arrow

### ISSUE THREAD

**Issue by elipowel** [marbl/canu#780]
I have a Canu assembly, have aligned my initial subreads.bam file to it and when i attempt to run Arrow with these I get a  "Companion FASTA index (.fai) file not found or malformatted! Use 'samtools faidx' to generate FASTA index". Is the Canu FASTA different than what Arrow is expecting?

**Comment by skoren** [comment]
Canu fasta is compatible with arrow, you need to run ```samtools faidx``` on the assembly before running arrow. See https://github.com/skoren/ArrowGrid, specifically splitByContig.sh
