### ISSUE TITLE
Read correction jobs failed, tried 2 times, giving up.

### ISSUE THREAD

**Issue by r-renberg** [marbl/canu#782]
Computer: Ubuntu 16.04 - 32 GB memory, 24 CPUs
Canu version 1.6

I am trying to assemble some bacterial genomes. I ran the same command on a subset of my files and it ran to completion, so I started it running with my full dataset and it has failed multiple times. First attempt, it failed, the attached error. I restarted the command and it failed again, same error. I deleted all the files generated from the first attempt. Restarted my computer. Ran the command again and it failed with the same error. HELP!

Please see attached file for command and outputs.

[canu_assembly_abort_readout.txt](https://github.com/marbl/canu/files/1724162/canu_assembly_abort_readout.txt)

**Comment by skoren** [comment]
It looks like some jobs are finishing but most are not, the concurrency may be too high for your system.  Try adding ```corConcurrency=4``` to your command. If it keeps failing, also post one of the failing output files (```correction/2-*/correctReads.*.out```).

**Comment by brianwalenz** [comment]
Fixed.  Note that you cannot upgrade from 1.6 to the latest without starting the assembly over.
