### ISSUE TITLE
The final file ".contigs.fasta" is empty

### ISSUE THREAD

**Issue by thalissonns** [marbl/canu#786]
Dears,

I have been used the Canu 1.5 (build from the source code) for assemble a genome got from PacBio. The file is in FASTA format and it has 23.3 MB.

I'm using the Linux Mint 18.2 (Sonya) on a machine with a I5 (Quad-core) processor with 8 GB RAM.

I'm considering the genome size equal 6.9 M.

The file is a library of single-read contigs (unpears) and has at all 885 contigs.

I executed the follow commands:

```
perl canu \
-p genome_name -d genome_name-pacbio \
genomeSize=6.9m \
-corMemory=8 \
-pacbio-raw  genome_name/pacbio.fasta

```
```
perl canu \
-p genome_name -d genome_name-pacbio \
genomeSize=6.9 m \
-pacbio-raw  genome_name/pacbio.fasta

```
The Canu executed fine to the end, but the final file generated ("genome_name.contigs.fasta") has no data, is empty (0 bytes)

Could someone give me a explain about this ?

I used the Canu in others ocassion and the final file generate was a size very reduced in comparing with the original file. Like original file has a 11.5 Mb for example and the final file was 800 kb... why Canu threw away a lot of information ?

I would like some help please.

**Comment by skoren** [comment]
Can you clarify what your input is? What is a "single-read contig" library? The input for Canu should be the raw data directly from the sequencing run. 855 reads or 23mb is not enough coverage to assemble a 7mb genome, that's about 3x and you need at least 20x input for Canu. In general, assembly will always reduce your input since you have 20x+ redundancy and the assembled genome is just 1x representation of the genome.

**Comment by thalissonns** [comment]
Thanks for the answer.

The input file used for Canu comes directly from PacBio.

Such that:
```
1.
A header: "name_bacteria_and_some_thing_else_Contigs001:
Base pairs: TGACTGACTGAC ....

2.
A header: "name_bacteria_and_some_thing_else_Contigs002:
Base pairs: TGACTGACTGAC ....

...

855.
A header: "name_bacteria_and_some_thing_else_Contigs855:
Base pairs: TGACTGACTGAC ....
```
and so on ...

I've said a library of single read contigs because I judge this as a library of contigs (a set of contigs). I used other scripts to try to do the assembly, so I used that nameclature of them ("library"...)

I understood what you said .. 23 mb is too small to generate a 7 mb genome. I'll review this information.. There is a way to reduce the loss of information into final file?

I got two PacBio files: one Fasta (11.8mb) and other Fastq (23.3mb). The Fasta format is not the error correction stage.

I think both files were polished in Quiver (it is at header of all contigs in file - "|quiver")... maybe an automatic post-stage after PacBio process (I do not know ... I'm fledgling in bioinformatics).

**Comment by skoren** [comment]
I don't think either of those files are raw sequencing data. It sounds like you're running them through HGAP or similar which is already assembling the data. That is not appropriate input for Canu. 

You want to find the analysis results folder from the run which should have either a bam or h5 files and corresponding fastq files (named something like ```*.subreads.fasta```) and use that instead. It would be the input to the HGAP or similar pipeline you're running.

**Comment by thalissonns** [comment]
Okay, I'll try to get the raw file to run on Canu.
If I had 900 contigs in a file, Canu would reduce the number of contigs to less than 10 or 20 contigs?

**Comment by skoren** [comment]
Canu isn't designed to assemble contigs so I'm not sure what it would do. The total contigs for your genome would depend on genome repeats, heterozygosity, coverage, and read lengths.

**Comment by thalissonns** [comment]
Ok, I'll try!
Thank you.

**Comment by skoren** [comment]
Invalid input, assembly not sequences. Open a new issue if you have errors running the assembly on the raw data.
