### ISSUE TITLE
maxThreads not followed in submission scripts to cluster.

### ISSUE THREAD

**Issue by ralowe** [marbl/canu#789]
Submitting job as below with maxThreads set to 2

`canu-1.6/Linux-amd64/bin/canu -p canu -d canu_outdir genomeSize=100m --useGrid=true  gridEngineMemoryOption="-l h_vmem=MEMORY" gridOptions="-l h_rt=6:0:0" maxThreads=2  gnuplotTested=true -pacbio-raw *.fastq.gz`

This sets the appropriate qsub parameter "-pe smp 2" in the jobsubmit script but fails to adjust the used threads in actual script. e.g.

```
$bin/overlapInCore \
  -G \
  -t 4 \
```

This seems to effect the majority of programs e.g seen in meryl as well.

**Comment by brianwalenz** [comment]
Sorry, I started looking at this a while ago, didn't see anything going wrong with the latest version, then got sidetracked.  Is it reproducible with the v1.7 release?

**Comment by ralowe** [comment]
Yes fixed in 1.7
