### ISSUE TITLE
evaluate corrected sequence

### ISSUE THREAD

**Issue by zhuzhuo** [marbl/canu#791]
I'm new to canu and this question might be naive. Since there is no quality score for the consensus sequence after canu correction, how do I evaluate the quality of the consensus sequence for de novo sequencing?

Thanks for your time.

**Comment by skoren** [comment]
See issue #744 if you want to evaluate assembly quality for some suggestions. You can generate QVs by polishing with Arrow for the final assembly consensus. You can also see per-base coverage using the ```tgStoreDump``` command, run it without arguments to see options.

If you are trying to evaluate the quality of a corrected read, the latest tip also tracks sequence from raw to corrected and will give you a layout and per-base coverage that was used to make the corrected read. Again, see ```tgStoreDump``` and the corStore in the correction folder.

**Comment by zhuzhuo** [comment]
Thank you for the reply Sergey. I only did the correction step and yes I am trying to evaluate the quality of a corrected read. I'm not sure if I could run tgStoreDump, because I don't have tigStore.

**Comment by skoren** [comment]
The tigStore is a generic name, as I said above, it is called corStore in the correction step but this only exists in 1.7 not in 1.6.
