### ISSUE TITLE
Canu via command line on a Windows 10 machine?

### ISSUE THREAD

**Issue by ranitori** [marbl/canu#792]
HI, I'm a newbie, but managed to get a complete genome assembly using v1.6 on a Macbook laptop. I have a more powerful machine, which will probably complete assemblies faster than my Mac did (about 3 days), but it's a Windows 10 PC. I tried installing canu on it, but haven't gotten it to work. Will it run on a PC via the command line?
Thanks

**Comment by skoren** [comment]
No explicit support for windows natively and I wouldn't expect it to work. I know it can run under Cygwin and I think some users have gotten it to run under bash in windows 10. The easier option is to stick with the mac and use the fast overlapping option (```-fast```) if you're on the latest tip.

**Comment by ranitori** [comment]
Thanks. Would I expect a lower quality assembly using -fast?

**Comment by skoren** [comment]
Probably not, it is slightly less contiguous on large genomes (human) which is why it's not the default but the smaller stuff we've tried like drosophila or yeast or similar are comparable or often better. In terms of consensus it should be comparable.
