### ISSUE TITLE
how to restart correction step after subjobs reached scheduler run-time limit 

### ISSUE THREAD

**Issue by gdczoller** [marbl/canu#794]
Hi canu team

We are trying to assemble a large genome on the cluster and the correction step runs into a problem. It seems that quite a few of the "mhap" jobs in correction/1-overlapper got killed by the cluster scheduler because they reach the run-time limit. Can we now simply change the settings in the submit script (e.g. set: `gridOptions="-W 48:00"`) and restart the run? Or do we have to remove some files and results before restarting? If so, which files do we need to delete? 
Thanks for your help!
We are using Canu 1.6 on a Linux/Centos cluster with LSF scheduling system.

**Comment by brianwalenz** [comment]
You should be able to simply change the option given to Canu and restart (for the gridOption options only).

Check the \*jobSubmit*sh files in correction/1-overlapper/ to make sure the correct parameters are sent to the scheduler.  Canu will only rerun the missing jobs, so don't freak out if there are 'missing' jobs.

I'm quite interested in hearing how Canu works on LSF.  It's not used that much.  A note back with any complaints or successes would be appreciated!

**Comment by gdczoller** [comment]
Thanks for the quick reply! The *jobSubmit*sh files look good and Canu is running fine as far as I can tell. 
So far Canu runs fine on this LSF cluster. We have been using it for two small assemblies (40Mbases), one medium sized (500Mbases). And now we have started this 3Gbases genome. For the smaller genomes we didn't have to tweak the LSF parameters much, just add a bit more memory and run-time. But for this large genome it seems a bit more tricky.

**Comment by gdczoller** [comment]
We have now run Canu for several days with longer run-time limits, but still see failed subjob every now and then (reaching the LSF time limit of 48h). I wonder what approach would be best to fix this. I could further increase the time limit, but that would make it slower, as the priority of such jobs on the cluster is much lower. Or I could give each subjob more CPUs, but I am not sure how well the subjobs scale at the error correction step. Or maybe I could force Canu to create smaller correction batches by setting "corPartitions" to a high number. But that might be inefficient. Do you have any experience which approach would work best? Personally, I would rather have it run a bit inefficient instead of having subjobs running out of time thereby wasting a lot of CPU time.  
Thanks for your insight into this!

**Comment by skoren** [comment]
If most of your jobs are finished it makes more sense to just up the wall time for the remaining jobs and let them finish, Canu won't rerun any jobs which finished automatically. You can just modify the *jobSubmit*.sh files manually and run them or re-run Canu with the update walltime and it will submit the failed jobs.

If a large fraction of your jobs are not finishing within the time limit, yes you can increase the number of threads used with cormhapThreads. You could also decrease the cormhapMemory which will decrease the job sizes and create more jobs but that would require you to remove the 1-overlapper folder completely and re-run it so the data gets re-partitioned.

**Comment by gdczoller** [comment]
We have now tried with more threads but it seems it does not scale well (15% CPU usage). Therefore, we have stopped the run and would like to try with smaller data packages that could run in 24h on 4 CPUs (which would fit the small but fast nodes on the cluster). Do you have any idea/experience how small the cormhapMemory (or other memory setting) should be for this? In case it is needed: the genome is about 3.5-4 Gb and there is roughly 55x raw coverage.

**Comment by skoren** [comment]
Typically this step is completely CPU-bound so the fact that it isn't getting close to max CPU is likely I/O issues on your cluster. In that case having more small jobs would make it worse. You could modify the mhap.sh script to write to scratch disk and only move the final ovb/counts files to shared storage to decrease contention. You could also limit the number of jobs running concurrently. 

Finally, the default k=16 might be a bit small for a 4gb genome, you could increase it to 17 or 18 which would also decrease the number of spurious overlaps found. That would require a restart from scratch though.

**Comment by gdczoller** [comment]
Strange, we hardly ever see a problem with I/O. We are told it is a rather fast file system (panasas). But well, it seems indeed I/O is a problem. I am not sure I can properly modify the mhap.sh script. Do you have an example for LSF? And we will try the increased kmer.

**Comment by skoren** [comment]
We don't have access to LSF but I can give an example from Slurm. You will need to replace ```/lscratch/$SLURM_JOBID``` with a path specific to your system, it should be unique to each element in a job array so jobs don't collide. 

First add a copy of the gkpStore to the local disk:
```
gkpStore="../asm.gkpStore"

if [ ! -d /lscratch/$SLURM_JOBID ] ; then
  mkdir -p /lscratch/$SLURM_JOBID
fi

mkdir -p /lscratch/$SLURM_JOBID/asm.gkpStore

echo Start copy at `date`
cp -p $gkpStore/info      /lscratch/$SLURM_JOBID/asm.gkpStore/info
cp -p $gkpStore/libraries /lscratch/$SLURM_JOBID/asm.gkpStore/libraries
cp -p $gkpStore/reads     /lscratch/$SLURM_JOBID/asm.gkpStore/reads
cp -p $gkpStore/blobs     /lscratch/$SLURM_JOBID/asm.gkpStore/blobs
echo Finished   at `date`

gkpStore="/lscratch/$SLURM_JOBID/asm.gkpStore"
```

also update mhap to write to scratch space:
```
  > /lscratch/$SLURM_JOBID/$qry.mhap.WORKING \
  && \
  mv -f /lscratch/$SLURM_JOBID/$qry.mhap.WORKING /lscratch/$SLURM_JOBID/results/$qry.mhap
fi

if [   -e /lscratch/$SLURM_JOBID/$qry.mhap -a \
     ! -e ./results/$qry.ovb ] ; then
  $bin/mhapConvert \
    -G $asm.gkpStore \
    -o ./results/$qry.mhap.ovb.WORKING \
    /lscratch/$SLURM_JOBID/$qry.mhap \
  && \
  mv ./results/$qry.mhap.ovb.WORKING ./results/$qry.mhap.ovb
fi

if [   -e /lscratch/$SLURM_JOBID/$qry.mhap -a \
       -e ./results/$qry.mhap.ovb ] ; then
  rm -f /lscratch/$SLURM_JOBID/$qry.mhap
fi

if [ -e ./results/$qry.mhap.ovb ] ; then
  mv -f ./results/$qry.mhap.ovb ./results/$qry.ovb
fi
```

and finally clean up at the end
```
rm -rf /lscratch/$SLURM_JOBID/asm.gkpStore
rmdir  /lscratch/$SLURM_JOBID
```
at the end.

**Comment by gdczoller** [comment]
Many thanks, this helped a lot and the correction/1-overlapper stage is done. Unfortunately, we are now facing another problem. I will open another issue for this.
