### ISSUE TITLE
v1.7 still has much higher maxCount compared to v1.4

### ISSUE THREAD

**Issue by kevfengler227** [marbl/canu#796]
Were any changes made to the method for computing maxCount in the new version? I am still seeing similarly high counts as in v1.5 and v1.6 which results in very long run times for unitigging/1-overlapper jobs.

Thanks,
KF

v1.4
Set maxCount to 578, which will cover 99.00% of distinct mers and 45.21% of all mers.

v1.7 
Set maxCount to 2800 (680 kmers), which will cover 99.75% of distinct mers and 56.99% of all mers.

**Comment by brianwalenz** [comment]
No changes made.  I completely forgot about it.

Can you upload some of the 0-mercounts/*histogram files for me?  That'll give me enough to fiddle around with the algorithm (again) or suggest better parameters.  I suspect that ovlMerDistinct=0.99 will get back to (nearly) the v1.4 behavior.

You can also try the '-fast' option.  This switches the overlap algorithm from the default 'overlapInCore' to 'mhap'.  The downside is that we haven't done any tuning on it when it's used on corrected reads.

**Comment by kevfengler227** [comment]
Thanks Brian. I uploaded “CANU.ms22.histogram” from running v1.4. Is this what you need?

KF

**Comment by kevfengler227** [comment]
So it appears that setting ovlMerDistinct=0.99 may have a negative impact when starting with raw reads. The jobs in correction/2-correction are taking much longer than expected (over two days a piece). Should I be setting all the *MerDistinct options separately?

**Comment by skoren** [comment]
The mer setting cannot affect the 2-correction step, it doesn't use k-mers. I expect this is a file system I/O issue because we no longer use memory mapped files because they were not compatible with all filesystems and caused performance issues. I think 1.4 might have still used them.

Try using the staging options if you have scratch space on your nodes (```stageDirectory=/lscratch/$SLURM_JOBID  gridEngineStageOption=--gres=lscratch:100```) where the directory is the path to your temp space and the grid option is if you have some way to reserve the scratch space from the scheduler.

**Comment by kevfengler227** [comment]
Thanks Sergey. I will give that a try. I am also wondering if I have too many correction jobs running at once?
I have 250 jobs (out of 692) running concurrently. Perhaps this should be throttled back? what is the best way to do that, if needed (or least for testing)?

**Comment by kevfengler227** [comment]
to run on lsf cluster I added the following two options
stageDirectory=/scr/$LSB_JOBID  gridEngineStageOption=”-R rusage[scr=10000]”

now for example, on one of the compute nodes there is a dir called file.gkpStore. However, there are two jobs running on this node, should there be two gkpStore directories, one for each jobid?

**Comment by skoren** [comment]
Yes, the directory name ($LSB_JOBID in your case) has to be unique across all running jobs. I'm guessing it's not on LSF for array jobs? The slurm example I posted is, perhaps you need to combine LSB_JOBID and LSB_JOBINDEX in the name.

**Comment by brianwalenz** [comment]
This should be (finally) resolved.  And if not, we're planning on removing the need for these pesky kmers in the next release.
