### ISSUE TITLE
read correction indeed much improved

### ISSUE THREAD

**Issue by kevfengler227** [marbl/canu#797]
not an issue, but positive feedback. read correction appears to be dramatically better than v1.4 and falcon v1.8.8. I have suspected that lulls in corrected read coverage (above a size cut-off) were more important for determining overall contiguity than read length, but have been unable to do anything about it. This is very exciting. Are you still using falcon_sense?

Thanks,
KF
[ReadCorrection_Improvement.pptx](https://github.com/marbl/canu/files/1769257/ReadCorrection_Improvement.pptx)

**Comment by brianwalenz** [comment]
That's pretty awesome to hear!  It's still essentially falcon_sense, but it was rewritten in the fall.  I'm pretty sure I fixed a few seemingly minor bugs, but nothing I'd expect to make this much of a difference  We've noticed a slight increase in consensus accuracy (compared to reference) but nothing worth mentioning.

What you're possibly seeing is the 'read rescue' that is new in v1.7.  This adds any read not already selected for correction or used as evidence for correcting some read to the list of reads to correct.  It was developed to 'rescue' short reads from plasmids that are typically excluded when reads are long.  There's no option to turn it off, and I doubt the logging records which reads are rescued -- though it does at least say how many reads were rescued.

The powerpoint shows this image:

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/8249720/36820563-778e7b16-1cbc-11e8-8364-306a928229d4.png">

Thanks for sharing.  I added a new label for these 'bug reports'.

**Comment by kevfengler227** [comment]
Yes, I think that is it. The corrected read coverage lulls I have observed do have long reads, but perhaps a bit less than surrounding areas and are dropping out of the longest subset.

KF

[cid:image001.png@01D3B0C7.62BF48C0]

**Comment by kevfengler227** [comment]
On second thought, the read rescue may not be the only factor underlying the improvement. With falcon v1.8.8. and canu v1.4 I do get corrected reads in the problematic regions but observe a lull in coverage after filtering at certain size cut-off. So somehow those 20 kb raw reads which were previously being split into a 12kb and 8 kb read and lost with filtering are now surviving as a corrected 20 kb read.  However, I still think this has something to do with a lack of "longest" reads in these regions. Is there another way read rescue is improving read correction?

Also, with falcon I am not using the longest "40x" per se for correction, but everything above 15 kb. So most of the reads should be targeted for correction, but somehow they are being truncated during correction and filtered out compared to canu v1.7.

**Comment by skoren** [comment]
There's been a lot of changes since 1.4 in read correction so while it's still the core falcon_sense algorithm for generating the consensus sequence, it really isn't similar in everything else. The main changes would be:
   - Alignment with edlib rather than custom ND implementation which was giving more accurate alignments (this was changed in 1.5)
   - Alignment bounded by initial overlap rather than attempting to pick a position from scratch by k-mers (I think this is probably what's helping your read). This should help in repetitive regions where another part of the read could inadvertently attract all the overlaps without being bounded to the right copy (this was 1.7)

So you could try generating the same corrected reads with 1.4, 1.5, 1.6, and 1.7 to see which of the changes is contributing.

**Comment by kevfengler227** [comment]
Thanks for the great insights Sergey. You are right, the dramatic improvement in read correction came with v1.5. In my test, the output of corrected trimmed reads >15kb increased from 19x to 34x compared to v1.4 with better coverage in "lulls".  

Unfortunately, I have been sticking with v1.4 because of the maxCount issue. This version has given me the best assemblies with FALCON corrected reads. But now I see the better read correction I have been missing!

KF

**Comment by skoren** [comment]
Closing, since we have info on where the improvement in corrected reads came from. You should be able to work around the maxCount issue using @brianwalenz suggestion in ticket #796
