### ISSUE TITLE
Meryl error during trimming in canu-1.7

### ISSUE THREAD

**Issue by dikkeaap** [marbl/canu#798]
Hi, I'm running canu-1.7 with the -fast option on a dataset that I have succesfully assembled with canu-1.6 before. The full command line I used for canu-1.7 is

`~/tools/canu-1.7/Linux-amd64/bin/canu -p ORGANISM -d canu-1.7 genomeSize=750M -nanopore-raw pass.fastq -fast -useGrid=true -gridEngineThreadsOption="-pe smp THREADS" -gridEngineMemoryOption="-l mem_total=MEMORY"`

During the trimming stage meryl crashes with the following message found at the end of trimming/0-mercounts/meryl.1.out :
 
```
Index error in read 12 mPtr 16612038828 pID 0 expected BLOB, got 00 00 00 00 '^@^@^@^@'
meryl: stores/gkStore.C:422: void gkReadData::gkReadData_loadFromBlob(uint8*): Assertion `blob[0] == 'B'' failed.
Can fit 74516004864 mers into table with prefix of 28 bits, using 52428.000MB (0.000MB for positions)
/opt/sge/default/spool/execd/cl3node018/job_scripts/1216070: line 29: 18015 Aborted                 (core dumped) $bin/meryl -B -C -L 2 -v -m 16 -threads 16 -memory 52428 -s ../ORGANISM.gkpStore -o ./ORGANISM.ms16.WORKING
/opt/sge/default/spool/execd/cl3node018/job_scripts/1216070: line 58: 18038 Segmentation fault      (core dumped) $bin/estimate-mer-threshold -h ./ORGANISM.ms16.histogram -c 39 > ./ORGANISM.ms16.estMerThresh.out.WORKING 2> ./ORGANISM.ms16.estMerThresh.err
```

Any idea what's going on here?

Best,
Erwin Datema

**Comment by brianwalenz** [comment]
Can you give the e.coli in the quick start (http://canu.readthedocs.io/en/latest/quick-start.html) a try?  What OS and what filesystem are you using?  I want to write some code to verify the gkpStore before we do much more - the error is complaining that 'read 12' (possibly the first corrected read) has no data, just NULL bytes.

**Comment by skoren** [comment]
Have you tried re-running the failing genome from scratch in a new folder? Don't erase your existing run (for troubleshooting) but run with a new -d folder. Does it still fail or does it get past this error. I'm curious if it is reproducible or could be caused by an intermittent FS issue.

**Comment by dikkeaap** [comment]
I restarted the assembly with a new output directory and it is currently in the unitigging stage, so I cannot reproduce the error. I guess it was a "random" error that caused the read store to be corrupted. I closed the issue since this was apparently entirely on my end :)
