### ISSUE TITLE
Genome size estimation

### ISSUE THREAD

**Issue by kushalsuryamohan** [marbl/canu#799]
Hi @skoren, I am new to genome assembly and am trying Canu for de novo assembly of a snake (no reference genome). Based on my literature survey, I would guesstimate the size to be under 2 Gbp but don't have a more accurate estimate (I plan to do some FACS analysis to get a better estimate).
I specified genomeSize as 1.5g in my first iteration of Canu and got an assembly of ~1.6 Gbp (see report below). 
I then took the 0-mers.histogram from /unitigging/0-mercounts and fed it into Genomescope and got a genome size of ~1.1 Gbp.
In your opinion is this the more closer estimate of genome size than what Canu reports?
I am currently trying genome sizes of 1.2, 1.3 and 2 Gbp (as an overestimate to see how Canu behaves). In other words, my question is does it force the assembly to the specified genome sizes?
If so, does it make sense to go off of Genomescope's estimate?

Many thanks for your patience in answering my questions!
Attachments: histogram of 0-mer counts and final report.
[Archive.zip](https://github.com/marbl/canu/files/1775899/Archive.zip)

**Comment by skoren** [comment]
In my experience genomescope tends to underestimate the genome size a bit (for human it estimates 2.2-2.5 Gbp) so if it estimates 1.1 the real genome may be closer to 1.4-1.5. The genome size doesn't affect very much in Canu (overlap sensitivity for very high or very low coverage, how many reads get selected for correction),so it's better to over estimate than under estimate. It's not worth running 1.2,1.3,1.4, etc in addition to 1.5. Since you're borderline on coverage so running with 2.0 will increase sensitivity and might get a more contiguous assembly (equivalently you can run with ```corMinCoverage=0 corMhapSensitivity=high``` and 1.5g genome size).

Looking at genomescope, there is a good bit of diversity in this genome (1.1%) so I'd expect a bunch of separate alleles in your assembly which will inflate the assembly size. You can try the heterozygous parameters on the FAQ to either separate more haplotypes or collapse them (your choice). Even better, if you can get Illumina data for parents of the snake you can use trio canu to assemble the parental haplotypes separately.

**Comment by kushalsuryamohan** [comment]
@skoren Thanks for the quick response!
That makes sense - learning something new everyday on genome assembly! I'll re-run with genomeSize=2g as well as another one with the higher mhap sensitivity and genomeSize=1.5g.

In terms of borderline coverage after correction, I have gotten ~30 Gbp of Pacbio data since I ran that first assembly. However, when I used ~15 Gbp of this pacbio data in combination with the Oxford data from the first assembly, my NG50 (70 kb vs the first NG50 of 267 kb) and # of contigs (15000 to 41000!) changed drastically (see second report pacbio_ont_canu_assembly.report). Initially I thought this was because I changed the genomeSize to 1.3g. But is this more due to the different error rates of the two technologies? Is there some middle path to error correcting both data sets? I could try correctedErrorRate=0.1?

In terms of the heterozygosity, unfortunately, this species of snake is particularly endangered so I don't think we could get more specimens :(
I looked up the FAQs on tweaking parameters to compensate for heterozygosity but don't see anything. There's a "stay tuned for more" placeholder and that's it. I'd appreciate more input here as well.

Also, related to inflated genome sizes, I was worried that I was seeing an inflation in genome size due to potential microbial contaminants and ran mash screen on my genome assembly (see attached screen report). Initially I was worried that this could be the potential reason but after digging through a couple of other posted final assembly reports and reading a blog from the Phillippy lab (https://genomeinformatics.github.io/mash-screen/), I think this is not something I should be overly concerned about. Please correct me if I am wrong in my conclusion that the #of shared hashes for the top hits and the median multiplicity is not high and also not a true indicator of containment of these bacterial/viral genomes in my assembly. 


Again, thanks a ton for your help!

[Archive.zip](https://github.com/marbl/canu/files/1777738/Archive.zip)

**Comment by skoren** [comment]
The polyploid genomes section is under http://canu.readthedocs.io/en/latest/faq.html#what-parameters-can-i-tweak. As for nanopore, the default correctedErrorRate is 0.14 and this asm ran with 0.105. Did you set an explicit correctedErorrRate? I would set it to at least 0.15 or higher perhaps. Setting it high does slow down the assembly so you could also try the -fast option available with 1.7. That would likely explain the lower contiguity. 

Most of the mash screen hits are below 95% identity and I presume there are no good snake genomes so they may be false hits to small genomes which share k-mer similarity with the snake.

**Comment by kushalsuryamohan** [comment]
Thanks! I missed that section. I set the error correction rate manually. 
Will repeat the run with 0.15 as you suggested and increase mhap sensitivity as well. I have more pacbio data now as well so hopefully after correction, I'll have > 30X data (I have ~90 Gbp of data = ~60X raw read coverage).

Thanks for the clarification on the mash report.

I will keep you posted on the new Canu run with the increased sensitivity parameters over the next couple of days.

Many thanks @skoren!

**Comment by kushalsuryamohan** [comment]
Hi @skoren, just wanted to update you - Canu, as you said has been taking quite a while to get past even the correction stage with the new parameters (corErrorRate=0.15,corMinCoverage=0 corMhapSensitivity=high and 1.5g genome size)

It's currently building corStore for the last day and a half on an LSF grid. Is this is something I should be concerned or just let it do its job? :)

Thanks!

**Comment by brianwalenz** [comment]
Nothing too much to worry about.  This step has to read the whole ovlStore, and that can be quite large.  The files in the corStore should be slowly increasing in size.  Unfortunately, there's no status report (which, Serge asked me yesterday, again, to implement) and all you can really do is wait it out.

**Comment by kushalsuryamohan** [comment]
Thanks @brianwalenz for the quick response! I shall wait it out while the suspense kills me! :)
Will keep you guys updated on the new v1.7 performance on reptilian genomes.

**Comment by kushalsuryamohan** [comment]
Also, the more I am getting familiar with the vast universe of genome assembly, I have another perhaps trivial question - since I got better assembly contiguity (don't know how complete it is though, yet) with Oxford Nanopore data alone vs combining additional Pacbio data with ONT data, would you recommend a tiered approach to assembly? 
i.e., correct Pacbio and ONT data separately using specific error correction rates and then use the corrected reads together to assemble? 
As you can see from my communication above with Sergey, I'm currently using a number that's perhaps too high to correct sequencing reads (0.15) for Pacbio and therefore lose a lot of reads but may be optimal for ONT data.

**Comment by brianwalenz** [comment]
I suspect that correcting individually will be worse, only because coverage won't be enough.  It'll take more than 50x (of each) to be worth it.

The error rate are more about rejecting bad alignments than working harder to find good alignments.  Lower rates help computationally in that the aligners can reject higher error alignments earlier (and so are faster).

How big is the ovlStore?  Human is around 1.5 TB, I've seen 10 TB before.  You might have a long repeat that generates tons of overlaps.  The only solution I know of for that is to increase the minimum overlap length, but that risks losing short real overlaps.

**Comment by kushalsuryamohan** [comment]
The ovlStore is a whopping ~32 TB! (Mild panic attack!)
Right now the corStore is only at 15 Gb! This could just take forever then :(

**Comment by kushalsuryamohan** [comment]
I've left the minimum read lengths and min overlap sizes to default.

**Comment by skoren** [comment]
The corStore will be much smaller than the ovlStore, I'd expect yours to end up <100gb in size and will probably take 4-5 days to build.
