### ISSUE TITLE
Recover contigs

### ISSUE THREAD

**Issue by ranitori** [marbl/canu#805]
Hi,
In a fit of stupidity I used to Text Edit on a Mac to remove some of my contigs from a canu 1.7 run contigs.fasta file, and of course it saved the modified file without asking me. So:
(i) is there a way to get the contig sequences back by running a part of canu, rather than having to redo the entire run from the beginning?
(ii) Is there somewhere I can recover the fasta contig headers? For example, the .contigs.layout.tigInfo file?
Thanks

**Comment by skoren** [comment]
i) You can recover contigs from the ctgStore in the unitigging folder. Something like: ```tgStoreDump -contigs -consensus -fasta -T unitigging/*.ctgStore 2 -G unitigging/*.gkpStore``` should do it.

ii) what do you mean the fasta header? The tig ID in contigs.layout.tigInfo corresponds to the tig name with a prefix of 0s. So for example tig 4 in contigs.layout.tigInfo is tig00000004 in the fasta. The dump above will put the default information into the header.

**Comment by brianwalenz** [comment]
A less hacky way is to move all the outputs from the assembly directory `rm *contigs* *unitigs* *unassembled*` (into a new directory) then rerun Canu with the same command line.  It'll notice the outputs don't exist and regenerate them.  This assumes that all the intermediate results still exist in correction/, trimming/, and unitigging/.

**Comment by ranitori** [comment]
I got the less hacky way to work! Thanks.
