### ISSUE TITLE
Can canu assemble a genome about 30 Gb with 100x ONT data ？

### ISSUE THREAD

**Issue by lijingjing1** [marbl/canu#809]
Hi i have a genome about 30 Gb to sequence 100x ONT data, can canu fit so big genome with 100x ONT data in theory.

**Comment by gringer** [comment]
I expect your biggest limitation will be the amount of memory required by the computer, and second biggest will be runtime. If possible, I'd recommend breaking it down into chromosomes (e.g. using Hi-C or linkage maps to identify adjacent sequences), then assembling each chromosome separately.

My experience is that Canu can *almost* manage with memory spilling over into a really fast solid state drive, so getting a 2TB PCIe SSD, and using it as a swap drive, might give you a chance of assembling the data.

**Comment by skoren** [comment]
A 30gb genome, cool. Would be the largest genome Canu is used for so you're in unexplored territory. I hope you have a cluster available, running on a single machine is likely to take a while. We'd be interested in testing Canu scaling to these genomes so keep in touch if you get the data.

I don't think memory will be that big of a concern, disk space is more likely to be an issue. I suggest having 50tb available. I think using a large machine (1-2tb) and adjusting maxMemory to be limited to whatever your largest available is will work better than depending on swap space on SSD. Most of the steps are tolerant of memory limits and will scale to fit into what you have.

As for parameters, some suggestions: increase the default k-mer size from 16 to 17 or 18, definitely use -fast, and suppress repeats more than defaults (see issue #587). There will probably be more parameters (like memory/cpu/etc) that will need some adjustments too from the defaults to avoid creating too many jobs on the cluster.

**Comment by gringer** [comment]
Yes, that sounds better. I didn't realise (or forgot) that Canu had a maxMemory setting. I notice that the default help displayed by Canu states the following:

>     gridOptions=string
>      - Pass string to the command used to submit jobs to the grid.  Can be used to set
>        maximum run time limits.  Should NOT be used to set memory limits; Canu will do
>        that for you.

But that probably doesn't apply to large genomes like this one.

**Comment by lijingjing1** [comment]
Yes,the disk space is more likely to be an issue.Because I have another genome size 6.3 Gb and sequencing 100x ,when running trim step it take about 33 T disk space and the disk run out of storage.

I have to copy the ccorrectedReads.fasta.gz to another clusters and disk to rerun trim-assembly step.But it give a error, can you have any suggestions?

canu -trim-assemble -nanopore-corrected Sample.correctedReads.fasta.gz -fast -p Sample -d Sample-canu genomeSize=6300m gridEngineMemoryOption="-l vf=MEMORY" gnuplotTested=true

-- ERROR  Found 3 machine configurations:
-- ERROR    class0 - 2 machines with 20 cores with 188 GB memory each.
-- ERROR    class1 - 99 machines with 20 cores with 62 GB memory each.
-- ERROR    class2 - 2 machines with 40 cores with 62 GB memory each.
-- ERROR
-- ERROR  Task bat can't run on any available machines.
-- ERROR  It is requesting:
-- ERROR    batMemory=256-1024 memory (gigabytes)
-- ERROR    batThreads=16-64 threads
-- ERROR
-- ERROR  No available machine configuration can run this task.

**Comment by lijingjing1** [comment]
I use the version 1.6 and 1.7 in the correction it cleaned up but only in trim directory it take 33T disk storage and only finished half of the jobs.So I have to copy the corrected data to another clusters to continue.

Thanks for you suggestion.i will look at the options setting about the large repeat genome later.

**Comment by skoren** [comment]
Interesting, haven't seen trimming take so much space. How much corrected data do you have? I guess if you have space by copying it you can let it run.

**Comment by skoren** [comment]
Idle, nothing to fix.
