### ISSUE TITLE
gkpStore being created in wrong folder

### ISSUE THREAD

**Issue by AShaw1802** [marbl/canu#811]
Hi, 

I've been trying to run canu v1.7 on the oxford.fasta test dataset in a Linux virtual box using the command
```
qiime@qiime-190-virtual-box:~/Desktop/Shared_Folder/CanuTest$ /home/qiime/Desktop/Shared_Folder/canu-1.7/Linux-amd64/bin/canu -correct  -p ecoli -d ecoli-dir  genomeSize=4.8m  -nanopore-raw /home/qiime/Desktop/Shared_Folder/CanuTest/oxford.fasta maxThreads=4
```
(full addresses added just to check)
The program runs until it reaches the meryl.sh step, where it can't find the gkpStore in the correction folder:
```
qiime@qiime-190-virtual-box:~/Desktop/Shared_Folder/CanuTest/ecoli-dir/correction/0-mercounts$ more meryl.000001.out 
seqFactory::openFile()--  Cannot determine type of file '../ecoli.gkpStore'.  Tried:
seqFactory::openFile()--         'FastA'
seqFactory::openFile()--         'FastAstream'
seqFactory::openFile()--         'Fastq'
seqFactory::openFile()--         'FastQstream'
seqFactory::openFile()--         'seqStore'
seqFactory::openFile()--         'GKSTORE'
```
The gkpStore is instead created in my base folder (in this case ecoli-dir). The key output line appears to be in the correction step where I have:
```
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Fri Mar  9 07:49:02 2018 with 71.095 GB free disk space

    cd .
    /home/qiime/Desktop/Shared_Folder/canu-1.7/Linux-amd64/bin/gatekeeperCreate \
      -minlength 1000 \
      -o ./ecoli.gkpStore.BUILDING \
      ./ecoli.gkpStore.gkp \
    > ./ecoli.gkpStore.BUILDING.err 2>&1
```
In other people's output examples I noted that their change directory command enters the "correction" folder rather than just having the period. I currently end up with a ecoli-dir folder containing:
```
qiime@qiime-190-virtual-box:~/Desktop/Shared_Folder/CanuTest/ecoli-dir$ ls
canu-logs     correction      ecoli.gkpStore.err  ecoli.report
canu-scripts  ecoli.gkpStore  ecoli.gkpStore.gkp
```
and a correction folder with only:
```
qiime@qiime-190-virtual-box:~/Desktop/Shared_Folder/CanuTest/ecoli-dir/correction$ ls
0-mercounts
```
I can run the meryl.sh script successfully if I manually move all the gkpStore files into the correction folder, but canu crashes again later (I assume it's working on the wrong gkpStore again). Any feedback to help redirect the gkpStore creation would be much appreciated! Please let me know if any further information would be useful.

Cheers,

Alex

**Comment by brianwalenz** [comment]
One gkpStore is expected, and it should be in the root directory instead of the correction/ directory.  In v1.7, only the one gkpStore is created, with symlinks from correction/ back to the one gkpStore.  Are you able to make symbolic links - `cd correction ; ln -s ../*gkpStore .`?

I vaguely remember this occurring in VMs on Windows hosts, but don't remember if it is an inherent problem in that configuration, or if there is a way to configure the host OS, the VM, or the guest OS to resolve.

**Comment by AShaw1802** [comment]
That's got it- thanks Brian, I hadn't realised that v1.7 only had one gkpStore with a symlink, and symlinks don't work in virtualbox's shared folder. I just solved it by setting up a folder outside the virtualbox's shared folder where the symlink can be made. Everything looks to be running fine now.
Cheers,
Alex

**Comment by nkuyfq** [comment]
> 
> 
> That's got it- thanks Brian, I hadn't realised that v1.7 only had one gkpStore with a symlink, and symlinks don't work in virtualbox's shared folder. I just solved it by setting up a folder outside the virtualbox's shared folder where the symlink can be made. Everything looks to be running fine now.
> Cheers,
> Alex

I also underwent a similar situation like you: I installed Canu 1.7 in Ubuntu installed in Virtualbox. Would you please tell me how you set up a folder outside the virtualbox's shared folder? Thank you so much!

**Comment by AShaw1802** [comment]
I just created a folder for Canu to work within on the VirtualBox Desktop instead of the shared_folder- once I was outside the constraints of the shared_folder it worked fine.

**Comment by nkuyfq** [comment]
It worked! Thanks a lot!
