### ISSUE TITLE
wrong memory resource of Meryl in canu-1.7?

### ISSUE THREAD

**Issue by wangyugui** [marbl/canu#813]
wrong memory resource of Meryl in canu-1.7?

command usage:
```
--  genomeSize        3200000000
...
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl    660 GB   44 CPUs  (k-mer counting)
-- Grid:  cormhap  220 GB   40 CPUs  (overlap detection with mhap)
-- Grid:  obtovl   220 GB   40 CPUs  (overlap detection)
-- Grid:  utgovl   220 GB   40 CPUs  (overlap detection)
-- Grid:  ovb        8 GB    5 CPUs  (overlap store bucketizer)
-- Grid:  ovs       32 GB    7 CPUs  (overlap store sorting)
-- Grid:  red      220 GB   40 CPUs  (read error detection)
-- Grid:  oea       16 GB    4 CPUs  (overlap error adjustment)
-- Grid:  bat      220 GB   40 CPUs  (contig construction)
-- Grid:  cns      220 GB   40 CPUs  (consensus)
-- Grid:  gfa      220 GB   40 CPUs  (GFA alignment and processing)
```

memory required by meryl in correction
```
 cat correction/0-mercounts/meryl.jobSubmit-01.sh
#!/bin/sh

qsub \
  -l mem_free=5585m -pe smp 44 -j y -o meryl.\$TASK_ID.out \
  -cwd -N "meryl_human" \
  -t 1-1 \
  ./meryl.sh 0 \
> ./meryl.jobSubmit-01.out 2>&1
```

memory required by meryl in trimming
```
# cat trimming/0-mercounts/meryl.jobSubmit-01.sh
#!/bin/sh

qsub \
  -l mem_free=15g -pe smp 44 -j y -o meryl.\$TASK_ID.out \
  -cwd -N "meryl_human" \
  -t 1-1 \
  ./meryl.sh 0 \
> ./meryl.jobSubmit-01.out 2>&1
```

The memory for meryl should be 660 G, not 5585m / 15g ?

**Comment by skoren** [comment]
The memory is per core so the trimming request is correct (15*44 = 660). The correction request is lower but it ran so probably used less memory than 660g. 

Did the configuration change between correction/trimming that could have changed the memory request? What memory is meryl actually set to use in meryl.sh?

**Comment by wangyugui** [comment]
yes. mem_free is the resource limit for per slot, NOT for whole sge job.
so 15g*44 = 660 is right.

I configure the meryl step to run on the big node with the max cpu solt(-pe smp 44) and max memory.
In fact,  It run with memory less than 660G.

```
./correction/0-mercounts/meryl.sh
  -B -C -L 2 -v -m 16 -threads 44 -memory 196608

./trimming/0-mercounts/meryl.sh
  -B -C -L 2 -v -m 22 -threads 44 -memory 540672
```

**Comment by skoren** [comment]
It looks like the correction wasn't set to use the large memory machine but used the default of about 200gb which matches what it requested. It seems like in both cases the request matched what it used.

**Comment by wangyugui** [comment]
so we should fix the memory resource of meryl in correction step?

**Comment by skoren** [comment]
I don't see anything wrong with it, it doesn't really need 600gb so it ran fine. How/when did you specify the memory usage for meryl to be 600g?

**Comment by wangyugui** [comment]
How:
```
canu command param
                merylMemory=660 merylThreads=44 \
```

**Comment by wangyugui** [comment]
If we can make sure meryl to run on the SGE node with the max memory, it will be more safe.

**Comment by skoren** [comment]
I don't see a difference running on the largest node or not, the memory is reserved and meryl won't use more than it requested. We almost never run it on a machine larger than 240gb.

Did you specify merylMemory from the very start of the run, before correction or did you re-launch Canu and modify the parameters. The output from the canu run in ```canu-scripts/canu.*.out``` will summarize whatever memory it was configured to use at each step. My guess is the merylMemory only got added on a re-start which is why correction didn't use it. I don't see how it would use it in trimming but not correction otherwise from the code.

**Comment by wangyugui** [comment]
I checked canu-scripts/canu.01.out again.

The first time I run canu with 'meryl    240 GB', so there is no problem in canu.

This is just my miss.
