### ISSUE TITLE
error in unitigging/3-overlapErrorAdjustment

### ISSUE THREAD

**Issue by kevfengler227** [marbl/canu#815]
Still to make it all the way through with v1.7. Almost there. Encountering an error in unitigging/3-overlapErrorAdjustment. The job array index is too large for the job to be submitted. Any suggestions?

Thanks,
KF

cat red.jobSubmit-01.out
Job array index too large. Job not submitted.

#!/bin/sh

bsub \
  -M 5120 -R span[hosts=1] -n 4 -u pbadmin -q prod -P ga-assembly-bigspades -R rusage[mem=8000,scr=10000] -o red.%I.out \
  -J "red_EDE4N[1-65535]" \
   \
  ./red.sh 0 \
> ./red.jobSubmit-01.out 2>&1

**Comment by skoren** [comment]
You can increase the memory used for RED/OEA, try ```oeaMemory=64 redMemory=64``` (assuming you have 64-bg machines). You'll have to remove the ```3-*``` folder in unitigging.
