### ISSUE TITLE
Read correction jobs failed. job 2-correction/results/####.cns FAILED.

### ISSUE THREAD

**Issue by psur9757** [marbl/canu#819]
Hi I get the following error

```
 -- Read correction jobs failed, tried 2 times, giving up.
--   job 2-correction/results/0010.cns FAILED.
--   job 2-correction/results/0018.cns FAILED.
--   job 2-correction/results/0020.cns FAILED.
--   job 2-correction/results/0025.cns FAILED.
--   job 2-correction/results/0028.cns FAILED.
--   job 2-correction/results/0036.cns FAILED.
--   job 2-correction/results/0050.cns FAILED.
--   job 2-correction/results/0052.cns FAILED.
--   job 2-correction/results/0068.cns FAILED.
--   job 2-correction/results/0086.cns FAILED.
--   job 2-correction/results/0096.cns FAILED.
--   job 2-correction/results/0101.cns FAILED.
--   job 2-correction/results/0103.cns FAILED.
--   job 2-correction/results/0106.cns FAILED.
--
ABORT:
ABORT: Canu 1.7
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```

I am working on a grid with Canu version 1.7. See canu output and my pbs script attached. 

Thank you.

Priyanka

[canu_output.txt](https://github.com/marbl/canu/files/1813636/canu_output.txt)
[canu_pbs_script.txt](https://github.com/marbl/canu/files/1813637/canu_pbs_script.txt)

**Comment by skoren** [comment]
Since not all jobs failed, first guess would be they were killed by the scheduler. What's the output of one of the failed jobs (like ```2-correction/*106.out```). The limit specified for them in your script is 3 hrs so it's possible some of them tried to run longer than this and got killed.

**Comment by psur9757** [comment]
No in my initial run, the limit specified was 16 hrs but it still failed.


Priyanka Surana | Postdoctoral Research Associate
Plant Breeding Institute | The University of Sydney
Room A2-4, 107 Cobbitty Rd, Cobbitty, NSW 2570
+61 2 9351 8825 (o) | +61 481 785 312 (m)



On Fri, Mar 16, 2018 at 12:58 AM +1100, "Sergey Koren" <notifications@github.com<mailto:notifications@github.com>> wrote:


Since not all jobs failed, first guess would be they were killed by the scheduler. What's the output of one of the failed jobs (like 2-correction/*106.out). The limit specified for them in your script is 3 hrs so it's possible some of them tried to run longer than this and got killed.

**Comment by psur9757** [comment]
The error file is too large to be added here. The last few lines for 0106.err 

> mapped 779036     0- 8569 to template  10229- 18676 trimmed by      0-    23 TTCGTTTTCA T--GTT---A
read244226 #83 location 0 to template 782-8462 length 7680 diff 0.208073
read244226 #83 location 1 to template 782-8463 length 7681 diff 0.208046
read244226 #83 location 2 to template 782-8464 length 7682 diff 0.208019
read244226 #83 location 3 to template 782-8465 length 7683 diff 0.207992
read244226 #83 location 4 to template 782-8466 length 7684 diff 0.207965
read244226 #83 location 5 to template 782-8467 length 7685 diff 0.207938
read244226 #83 location 6 to template 782-8468 length 7686 diff 0.207910
mapped 244226     0- 7864 to template  10862- 18543 trimmed by      0-     2 TGCCATCCTC TGC-ATCC-C

**Comment by skoren** [comment]
There's no error reported there, so I'm back to suspecting it is being killed by the scheduler due to time. What does the cluster job history report for either this run or your previous run for the failed jobs.

**Comment by psur9757** [comment]
I will restart with a longer wall time. Attached is the report from the cluster.
[OSR_512_canu_error.txt](https://github.com/marbl/canu/files/1816941/OSR_512_canu_error.txt)

**Comment by psur9757** [comment]
I restarted the job and it has already failed.

**Comment by skoren** [comment]
You've asked Canu to correct every read with the corOutCoverage parameter so it may take a while, depending on coverage, the initial 16 hrs might not have been enough either and if it failed with 16 why drop it to 3 rather than increase it? 

The attached above is only canu's output, I mean the output of the scheduler, there should be a way to get accounting information for how much time a job used, how much memory, and what its exit status was. Something like this, but for your cluster system:
```
63698617_104      norm   COMPLETED      1    56   10-00:00:00    1-13:34:42      4.1GB/cpu   26.4GB  cn2148
63698617_105      norm   COMPLETED      1    56   10-00:00:00    1-15:46:31      4.1GB/cpu   46.5GB  cn2149
63698617_106      norm   COMPLETED      1    56   10-00:00:00      03:54:07      4.1GB/cpu   25.5GB  cn3386
63698617_107      norm   COMPLETED      1    56   10-00:00:00      15:58:01      4.1GB/cpu   42.3GB  cn2158
63698617_108      norm   COMPLETED      1    56   10-00:00:00      18:36:33      4.1GB/cpu   51.2GB  cn2164
63698617_109      norm   COMPLETED      1    56   10-00:00:00      16:17:08      4.1GB/cpu   47.1GB  cn2184
```

Also, if it failed again, post the error output of canu as well as the job logs, not just that it failed.

**Comment by psur9757** [comment]
Here are the files I get from the canu.pbs main script itself. The remaining are all outputs from Canu itself.
Usage Statistics [OSR_512_canu_output.usage.txt](https://github.com/marbl/canu/files/1816962/OSR_512_canu_output.usage.txt)
Standard Out [OSR_512_canu_output.txt](https://github.com/marbl/canu/files/1816963/OSR_512_canu_output.txt)
Standard Error [OSR_512_canu_error.txt](https://github.com/marbl/canu/files/1816964/OSR_512_canu_error.txt)

The error details from 0106.err haven't changed in the last few tries. 
> read779036 #81 location 0 to template 886-9332 length 8446 diff 0.231589
mapped 779036     0- 8569 to template  10229- 18676 trimmed by      0-    23 TTCGTTTTCA T--GTT---A
read244226 #83 location 0 to template 782-8462 length 7680 diff 0.208073
read244226 #83 location 1 to template 782-8463 length 7681 diff 0.208046
read244226 #83 location 2 to template 782-8464 length 7682 diff 0.208019
read244226 #83 location 3 to template 782-8465 length 7683 diff 0.207992
read244226 #83 location 4 to template 782-8466 length 7684 diff 0.207965
read244226 #83 location 5 to template 782-8467 length 7685 diff 0.207938
read244226 #83 location 6 to template 782-8468 length 7686 diff 0.207910
mapped 244226     0- 7864 to template  10862- 18543 trimmed by      0-     2 TGCCATCCTC TGC-ATCC-C

In 2-correction, Canu gives me a bunch of usage files but none in the results folder. For example, [cor_OSR_512_canu_OSR512.o2132855_usage.txt](https://github.com/marbl/canu/files/1816981/cor_OSR_512_canu_OSR512.o2132855_usage.txt)

Please let me know which other files from Canu would you like me to post?

**Comment by skoren** [comment]
Can you upload all the usage and the err files from the 2-correction folder, they should not be too large if you tar.gz them, alternatively you can put them on our FTP site (see FAQ). 

Can you also try running the failing job by hand on an interactive session, from within 2-correction folder run ```sh correctRead.sh 106``` and report its output.

**Comment by psur9757** [comment]
I have uploaded the entire 2-correction folder (except the results subfolder) to your FTP site so you can access them all. 

I ran the code, `sh correctReads.sh 106` and the output was
> Running job 107 based on PBS_ARRAY_INDEX=1 and offset=106.
Job finished successfully.

**Comment by skoren** [comment]
Ah OK I see the issue. The initial jobs did get killed due to time limit, which seems like it was set to 1 hr:
```
2-correction/cor_OSR_512_canu_OSR512.o2129901.106:=>> PBS: job killed: walltime 3635 exceeded limit 3600
```

However, there seems to be a bug in the Canu resume of jobs on PBSPro where it's not passing the right job ID so the restarted jobs keep running job 1 which is already done. From within 2-correction/correctReads-01.jobSubmit.sh to be:
```
#!/bin/sh

qsub -j oe \
  -l mem=6g -l nodes=1:ppn=4 -P RDS-FAE-OSR-RW -l walltime=16:00:00 \
  -N "cor_OSR_512_canu_OSR512" \
   -J 1-107 \
  ./correctReads.sh  0 \
> ./correctReads.jobSubmit-01.out 2>&1
```
and run that, it should submit an array of jobs which will properly compute the offsets.

**Comment by psur9757** [comment]
After modifying the `correctReads.jobSubmit-01.sh` script in 2-correction, I resubmit the `canu.pbs` script but it ends again. I noticed when I do this, the `correctReads.jobSubmit-01.sh` script reverts back. 

When I try running the modified `correctReads.jobSubmit-01.sh` script from within 2-correction. It again fails but without even an error message. The pbs script I used to run `correctReads.jobSubmit-01.sh` script 
[runcorrectReads.pbs.txt](https://github.com/marbl/canu/files/1823163/runcorrectReads.pbs.txt)
 


Would you like me resend the 2-correction folder?

**Comment by skoren** [comment]
The modified ```correctReads.jobSubmit-01.sh``` script just submits other jobs and exits, it's not supposed to do anything more so would run very quickly. You don't actually need to submit it, just run it on the head node. So if you're saying it "failed" because it exited quickly, that's fine and expected. The ```correctReads.jobSubmit-01.out`` file will have the job id of the array submitted to run the actual correction jobs. Sure, resend the 2-correction folder.

**Comment by psur9757** [comment]
I ran the modified `correctReads.jobSubmit-01.sh` script, followed by the canu main script to move the program onto the next step. At this point, I am not sure how to proceed to get the output files. I have sent you the 2-correction folder. Thank you.

**Comment by skoren** [comment]
I checked the correcteReads.jobSubmit-01.sh you had in the uploaded files, it didn't have the added array job index (```-J 1-107```) so the job didn't run anything. I am guessing you tried to run it after it was overwritten by Canu so it lost your modifications. 

The only output files I see which had the -J option added are from March 14, the original run. Modify the correctReads.jobSubmit-01.sh to add the -J option (see my comment above) and run it directly on the head node, don't re-launch Canu or submit the job and then check your grid to see if it submitted an array job to the scheduler.

**Comment by psur9757** [comment]
I changed the `Execution.pm` file, deleted all `*.out` files in the 2-correction folder and resubmitted the `canu.pbs` script but it failed. 

The new `correctReads.jobSubmit-01.sh` still is missing the `-J 1-107` bit. Should I change this separately?

I am attaching the error file from the main script as well the new files from the 2-correction folder.

[correctReads.jobSubmit-01.sh.txt](https://github.com/marbl/canu/files/1839766/correctReads.jobSubmit-01.sh.txt)
[correctReads.jobSubmit-01.out.txt](https://github.com/marbl/canu/files/1839767/correctReads.jobSubmit-01.out.txt)
[OSR_512_canu_error.txt](https://github.com/marbl/canu/files/1839768/OSR_512_canu_error.txt)

**Comment by skoren** [comment]
The code patch worked correctly and added the job info as an argument to the script. However, it seems PBSPro can't maintain consistent syntax between versions. The documentation for older versions states it should allow you to pass parameters to the script (and users have done so) but I don't see a way to do this in version 13. If you know of a way to pass parameters to a script (so they'll be interpreted as $1, $2, etc), I can patch the code. Without access to a PBSPro grid we have no way to test especially if they keep changing the syntax.

So you should go back to the script I suggested with the -J a few comments ago and we'll consider leave PBSPro support limited to versions before 13.

**Comment by psur9757** [comment]
I added the `-J 1-107` bit to the `correctReads.jobSubmit-01.sh` and submitted it directly on the node using the command `./correctReads.jobSubmit-01.sh`.

Below is the text of the output file.

>usage: qsub [-a date_time] [-A account_string] [-c interval]
	[-C directive_prefix] [-e path] [-f ] [-h ] [-I [-X]] [-j oe|eo] [-J X-Y[:Z]]
	[-k o|e|oe] [-l resource_list] [-m mail_options] [-M user_list]
	[-N jobname] [-o path] [-p priority] [-P project] [-q queue] [-r y|n]
	[-S path] [-u user_list] [-W otherattributes=value...]
	[-v variable_list] [-V ] [-z] [script | -- command [arg1 ...]]
       qsub --version

I have also contacted our HPC facility to see if we can patch the code directly. 

Will I encounter these same problems with Canu v1.6? If not, I could run my assembly on that version.

**Comment by psur9757** [comment]
To run a script with args, it appears that you use:

qsub -P -o outout.txt -e error.txt -- script.sh
The -P is required here.
Would probably need to add "-l select=1:ncpus=X" to select X cpus
ie: qsub -P -o outout.txt -e error.txt -l select=1:ncpus=6 -- script.sh myarg1 myarg2 etc
 
script.sh needs to be executable as well.
 
Alternatively, args can kind of be passed as environment variables using the -v options.

**Comment by psur9757** [comment]
Your script would probably look like this:

 
>qsub -j oe \
-l mem=6g -l nodes=1:ppn=4 -P RDS-FAE-OSR-RW -l walltime=16:00:00 \
-N "cor_OSR_512_canu_OSR512" \
-J 1-107 \
-- ./correctReads.sh 10 > ./correctReads.jobSubmit-01.out 2>&1
 
Note the extra -- characters.

**Comment by skoren** [comment]
You would encounter the same error with all versions of Canu. The problem is the resume function depends on passing arguments to the script and that is not supported on your version of PBSPro using the syntax that worked on previous versions. The issue stems from the restart and initial fail so you could also just remove the 2-correction folder and re-run Canu with a high wall clock limit, as long as all the jobs complete in the allocated time, you won't have to restart and won't have the error.

Does that above script work? The correctReads.sh should already be executable. If it does, we can support that syntax for PBSPro. You should also modify the 10 to be 0 in this case (you either way to specify the -J or the 10 after the sh but not both).

**Comment by psur9757** [comment]
I think the script above worked. I have sent over the 2-correction folder via FTP. Look for the March 28th files. However, when I resubmit the `canu.pbs` script to move it to the next stage after 2-correction, it gives me an error. [OSR_512_canu_error.txt](https://github.com/marbl/canu/files/1853961/OSR_512_canu_error.txt)

I will delete 2-correction folder next and restart with 36 hours as wall time. Hopefully that should do.

**Comment by skoren** [comment]
Yep, you're right you need to undo the change to the Execution.pm script.
