### ISSUE TITLE
generateTemplateStitch()-- significant size difference, stopping

### ISSUE THREAD

**Issue by mjpdejong** [marbl/canu#823]
I am running into an error, and am not exactly sure how to proceed..

Canu version canu/1.6.8642

```/usr/bin/env perl \
$bin/canu -trim-assemble -p 'NGS0028_#38VJ0' 'genomeSize=200M' 'obtOverlapper=mhap' 'utgOverlapper=mhap' 'obtReAlign=true' 'utgReAlign=true' 'minOverlapLength=1000' 'corMhapSensitivity=high' 'redMemory=16G' 'batMemory=128G' 'corMinCoverage=0' 'corMaxEvidenceErate=0.15' 'gnuplotTested=true' 'useGrid=true' 'java=/cm/shared/apps/Java/1.8.0_121/bin/java' -nanopore-corrected '*PATH*/NGS0028_#Q12OT.correctedReads.fasta.gz' canuIteration=2
```

```generateTemplateStitch()-- generated template of length 184684, expected length 102816, 56.9517% difference.
generateTemplateStitch()-- significant size difference, stopping.
utgcns: utgcns/libcns/unitigConsensus.C:529: char* generateTemplateStitch(abAbacus*, tgPosition*, uint32, double, bool): Assertion `(tiglen < 100000) || ((-50.0 <= pd) && (pd <= 50.0))' failed.

Failed with 'Aborted'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::101 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
utgcns/libcns/unitigConsensus.C::529 in _Z22generateTemplateStitchP8abAbacusP10tgPositionjdb()
utgcns/libcns/unitigConsensus.C::754 in _ZN15unitigConsensus13generatePBDAGEcbP5tgTigPSt3mapIjP6gkReadSt4lessIjESaISt4pairIKjS4_EEEPS2_IjP10gkReadDataS6_SaIS7_IS8_SE_EEE()
utgcns/utgcns.C::581 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
/cm/local/apps/slurm/var/spool/job4216592/slurm_script: line 79: 82144 Aborted                 $bin/utgcns -G ../NGS0028_#38VJ0.${tag}Store/partitionedReads.gkpStore -T ../NGS0028_#38VJ0.${tag}Store 1 $jobid -O ./${tag}cns/$jobid.cns.WORKING -maxcoverage 40 -e 0.192 -pbdagcon -edlib -threads 8
```

**Comment by skoren** [comment]
What's version 8642? Is that a checkout between the 1.6 and 1.7 release? There was some large changes between those versions and so your assembly may not be optimal. I'd suggest running using either 1.6 or 1.7 and see if it fixes the error. If you want to keep this run, you can probably increase the consensus error rate, change ```consensus.sh``` to have ```-e 0.4``` and see if it completes OK.

**Comment by mjpdejong** [comment]
Thank you for the reply. I have been quite pleased with the results of some of the bleeding edge versions of your assembler. Anyway, your suggestion fixed the issue in this case, so I have at least retrieved the results I was looking for. I have updated the Canu module to 1.7 the day it was released. Thank you for the support! Are you interested in a re-run with the exact same settings with version 1.7?

Greets,

**Comment by skoren** [comment]
Yes, it would be good to know if the 1.7 changes fix this or not.

**Comment by mjpdejong** [comment]
I will let you know when the results are in.. This particular genome is taking a lot of assembly time unfortunately.. I have not yet figured out what is causing this.

Greets,

**Comment by skoren** [comment]
It's probably relatively repetitive, you can save time by getting rid of the obtReAlign=true option, that doesn't seem to make much difference in assembly quality and will save time.

**Comment by mjpdejong** [comment]
Both obtMhap and utgMhap took significantly longer than usual.. Most of the genomes I assemble are plant genomes and have significant repeats, I have not yet figured out what is so "special" about this one.

Do I understand correctly that losing the obtReAlgin=true results in the same setting as the -fast trigger from Canu 1.7 considering the other adjustments I included? I'll give that I try for the sake of trying :)

**Comment by skoren** [comment]
Yep, dropping that option is equivalent to fast in 1.7

**Comment by skoren** [comment]
Closing, initial issue fixed by increasing error rate for consensus.

**Comment by mjpdejong** [comment]
The re-run with Canu 1.7 gave the same error..

The contig that is causing the problem has few percent ( < 10%, ~85% accuracy ) BLAST hit with mitochondrial genomes from various plant species. I find multiple other contigs that have comparable characteristics. If you are interested in this error I can supply more information in private.. For us, raising the error rate indeed solved the problem.

Greets,

```
Working on tig 57 of length 102986 (1400 children)
  unitig 57 detected 1398 contains (435.47x, 99.55%) 2 dovetail (1.99x, 0.45%)
    unitig 57 removing 1343 (396.98x) contained reads; processing only 55 contained (38.49x) and 2 dovetail (1.99x) reads

generateTemplateStitch()-- generated template of length 184577, expected length 102986, 56.7465% difference.
generateTemplateStitch()-- significant size difference, stopping.
utgcns: utgcns/libcns/unitigConsensus.C:529: char* generateTemplateStitch(abAbacus*, tgPosition*, uint32, double, bool): Assertion `(tiglen < 100000) || ((-50.0 <= pd) && (pd <= 50.0))' failed.

Failed with 'Aborted'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::97 in _Z17AS_UTL_catchCrashiP7siginfoPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
utgcns/libcns/unitigConsensus.C::529 in _Z22generateTemplateStitchP8abAbacusP10tgPositionjdb()
utgcns/libcns/unitigConsensus.C::754 in _ZN15unitigConsensus13generatePBDAGEcbP5tgTigPSt3mapIjP6gkReadSt4lessIjESaISt4pairIKjS4_EEEPS2_IjP10gkReadDataS6_SaIS7_IS8_SE_EEE()
utgcns/utgcns.C::581 in main()
(null)::0 in (null)()
(null)::0 in (null)()
/cm/local/apps/slurm/var/spool/job4320826/slurm_script: line 79: 312249 Aborted                 $bin/utgcns -G ../NGS0028_#B2V2R.${tag}Store/partitionedReads.gkpStore -T ../NGS0028_#B2V2R.${tag}Store 1 $jobid -O ./${tag}cns/$jobid.cns.WORKING -maxcoverage 40 -e 0.192 -pbdagcon -edlib -threads 2-8
```
