### ISSUE TITLE
Times reported during Canu run.

### ISSUE THREAD

**Issue by daewoooo** [marbl/canu#825]
EXAMPLE:
-- Starting command on Mon Mar 12 05:58:39 2018 with 13598.834 GB free disk space

    cd unitigging
      -minlength 1000 \
      -o ./WholeGenome_errorRate0.045_overlapLen500.gkpStore.BUILDING \
      ./WholeGenome_errorRate0.045_overlapLen500.gkpStore.gkp \
    > ./WholeGenome_errorRate0.045_overlapLen500.gkpStore.BUILDING.err 2>&1

-- Finished on Mon Mar 12 06:21:42 2018 (1383 seconds) with 13577.54 GB free disk space

Are the times reported over the course of CANU run real clock times or CPU times?

Thank you in advance answering this question.

David

**Comment by skoren** [comment]
It's using time() so wall clock not CPU.

**Comment by tobiasmarschall** [comment]
Good to know. In case that's easy to do, additionally reporting CPU times might be helpful to Canu users (including me ;)

**Comment by skoren** [comment]
It's a bit difficult to report CPU times since Canu runs multiple processes in parallel and uses the grid when it's available so we'd need code that is smart enough to query both the grid and the local processes. I'll close and move to a feature request because we've talked about adding this info.

**Comment by skoren** [comment]
This exists in Canu now under canu-time for SGE/Slurm, run as ```canu-time <asm folder>```
