### ISSUE TITLE
how much data to expect in the bucketizing/sorting/indexing steps in the correction stage?

### ISSUE THREAD

**Issue by gdczoller** [marbl/canu#828]
We are trying to assemble a big genome (3.5-4Gb) and are now at the  bucketizing step after the correction/1-overlapper stage. This already produced 14TB of bucket data and is not done. If it continues like that I expect about 18TB of bucket data. When I look at the scripts in the ovlStore.BUILDING directory I see also 2-sort.sh and 3-index.sh. Now I wonder how much data, also short lived temporary data, will be produced by these two steps? Will it be another 20TB? And what happens at the end of these steps? Will some big chunk of the data in ovlStore.BUILDING be copied somewhere else and then the ovlStore.BUILDING be deleted in one go? This is important because we are reaching the limits of the file system. Actually, we have already started with linking in directories on other file systems in order to be able to hold all the data.

**Comment by skoren** [comment]
The 2-sort and 3-index scripts will not generate more data, they erase as they go along. The 1-bucketize step duplicates the data in ````1-overlapper/results``` so it will be about equal to that. 

You can erase some intermediate files early if you want to save space. You can erase ```1-overlapper/blocks```. You can also erase``` 1-overlapper/results/XXXX.ovb``` though this is not as safe in case there is any error building the bucket file you would need to re-create the overlaps again so if you can avoid erasing these, they will get cleaned up by Canu after the store is done.

The full store will be erased once corrected reads are generated though in 1.7 it is possible to erase it even earlier if needed (as soon as the ```asm.corStore``` is created).

**Comment by gdczoller** [comment]
It seems the 2-sort produces temporarily quite a bit of data. For example I get these files from one job (out of 2000): 
9.6G 0001
8.2M  0001.evalueLen
114K  0001.index
64  0001.info
I guess, as you say, it will delete as it goes along, but in the meantime it seems it needs quite a bit of disk space. 
Anyway, I realize now that many of the sort jobs failed due to reaching the LSF memory limit. Can I just increase the memory in the 2-sort.jobSubmit  scripts and restart Canu run? Or do I need to clean up some things first?

**Comment by skoren** [comment]
Yes, you can restart Canu, it will find what didn't run, no need to clean up first.
