### ISSUE TITLE
correction coverage ??

### ISSUE THREAD

**Issue by davidvilanova** [marbl/canu#829]
Hi,
I´m using canu1.7 and trying to correct nanopore reads.

`canu -correct -d canu/canu_correct_small -p canuAssembly gridOptions="--export=ALL"  genomeSize=2.6m useGrid=true -nanopore-raw demultiplex/BC01.fastq.gz
`
When i check the file 'canuAssembly.gkpStore i´m confused about the coverage.

Coverage for raw reads goes from 122.259  to 8.075 for corrected.
Then below again, for evidence reads it goes for 123.827 to 41.217.

Is the real coverage after correction and overlap 41,217 ?? 

Just need to understand all the output. 

[CORRECTION/LAYOUT]
```
--                             original      original
--                            raw reads     raw reads
--   category                w/overlaps  w/o/overlaps
--   -------------------- ------------- -------------
--   Number of Reads              42099          6387
--   Number of Bases          366775524      24225362
--   Coverage                   122.259         8.075
--   Median                        7407          2601
--   Mean                          8712          3792
--   N50                          11631          6758
--   Minimum                       1000             0
--   Maximum                      58800         28903
--   
--                                        --------corrected---------  ----------rescued----------
--                             evidence                     expected                     expected
--   category                     reads            raw     corrected            raw     corrected
--   -------------------- -------------  ------------- -------------  ------------- -------------
--   Number of Reads              43987           6556          6556            674           674
--   Number of Bases          371481462      123651705     120005611        5041515       2707187
--   Coverage                   123.827         41.217       40.002          1.681         0.902
--   Median                        7071          17441         17111           6753          3369
--   Mean                          8445          18860         18304           7479          4016
--   N50                          11433          18483         17997           9310          5282
--   Minimum                       1001          13736         13735           1189          1030
--   Maximum                      58800          58800         49621          30428         13460
--   
--                        --------uncorrected--------
--                                           expected
--   category                       raw     corrected
--   -------------------- ------------- -------------
--   Number of Reads              41256         41256
--   Number of Bases          262307666     171087955
--   Coverage                    87.436        57.029
--   Median                        5790          2834
--   Mean                          6358          4146
--   N50                           8687          9083
--   Minimum                          0             0
--   Maximum                      46930         13734



```

**Comment by skoren** [comment]
Canu only targets the longest 40x of reads for correction. Your report is saying 8x coverage (raw reads w/o overlaps) of your reads have no overlaps so won't be corrected. Canu expects to have 40.002X coverage in corrected reads (expected corrected) plus another 0.9x in rescued reads (these are reads which were not represented by the longest 40x and could be short plasmids). The report will output a histogram of the raw input data and the actual corrected data (the above is just an estimate not actual corrected data). Something like this:
```

[TRIMMING/READS]
--
-- In gatekeeper store 'trimming/asm.gkpStore':
--   Found 8890188 reads.
--   Found 68182296697 bases (21.99 times coverage).
--
--   Read length histogram (one '*' equals 97985.3 reads):
--        0   9999 6858971 **********************************************************************
--    10000  19999 1587954 ****************
--    20000  29999 276013 **
--    30000  39999  68540 
--    40000  49999  27519 
--    50000  59999  15982 
--    60000  69999  10916 
--    70000  79999   7640 
--    80000  89999   6007 
--    90000  99999   4579 
--   100000 109999   3576 
--   110000 119999   2952 
--   120000 129999   2425 
--   130000 139999   2037 
--   140000 149999   1706 
--   150000 159999   1494 
--   160000 169999   1246 
--   170000 179999   1161 
--   180000 189999    992 
--   190000 199999    864 
--   200000 209999    841 
--   210000 219999    698 
--   220000 229999    602 
--   230000 239999    528 
--   240000 249999    500 
--   250000 259999    471 
--   260000 269999    434 
--   270000 279999    361 
--   280000 289999    321 
--   290000 299999    267 
--   300000 309999    259 
--   310000 319999    223 
--   320000 329999    221 
--   330000 339999    180 
--   340000 349999    174 
--   350000 359999    155 
--   360000 369999    130 
--   370000 379999    146 
--   380000 389999    121 
--   390000 399999    128 
--   400000 409999     81 
--   410000 419999     78 
--   420000 429999     69 
--   430000 439999     78 
--   440000 449999     47 
--   450000 459999     52 
--   460000 469999     44 
--   470000 479999     41 
--   480000 489999     42 
--   490000 499999     35 
--   500000 509999     28 
--   510000 519999     31 
--   520000 529999     24 
--   530000 539999     23 
--   540000 549999     16 
--   550000 559999     17 
--   560000 569999     20 
--   570000 579999     13 
--   580000 589999     18 
--   590000 599999     13 
--   600000 609999      9 
--   610000 619999      6 
--   620000 629999      7 
--   630000 639999      8 
--   640000 649999      8 
--   650000 659999      3 
--   660000 669999      6 
--   670000 679999      2 
--   680000 689999      2 
--   690000 699999      4 
--   700000 709999      2 
--   710000 719999      2 
--   720000 729999      5 
--   730000 739999      3 
--   740000 749999      2 
--   750000 759999      2 
--   760000 769999      1 
--   770000 779999      2 
--   780000 789999      1 
--   790000 799999      1 
--   800000 809999      2 
--   810000 819999      0 
--   820000 829999      1 
--   830000 839999      0 
--   840000 849999      1 
--   850000 859999      0 
--   860000 869999      2 
--   870000 879999      0 
--   880000 889999      0 
--   890000 899999      1 
--   900000 909999      0 
--   910000 919999      0 
--   920000 929999      0 
--   930000 939999      0 
--   940000 949999      0 
--   950000 959999      0 
--   960000 969999      0 
--   970000 979999      0 
--   980000 989999      0 
--   990000 999999      0 
--   1000000 1009999      0 
--   1010000 1019999      1
```

**Comment by davidvilanova** [comment]
Thanks so much for the clarification !!!!
Might be out of scope here but when i use quast to evaluate assembly towards the reference i only get 42% of my reference covered. I´m surprised since i see assemblies up to 92% similarity to their reference. Any hint ?

**Comment by skoren** [comment]
Is the assembly the expected size? I am not sure what the default QUAST alignment options are, the nanopore assemblies may only be 95% identity (depending on the base caller) plus whatever difference these is between your sample and the reference. You can run nano polish to get a better consensus sequence.

**Comment by davidvilanova** [comment]
The assembly has 18 contigs. First contig is 2401703 while the reference bacteria is 2601426 so i was expecting to catch at least 92% of the reference. 
I´m using latest quast dev that uses minimap2 as follows

```
minimap2 -c -x \
     asm5 -B5 -O4,16 --no-long-join -r 50 -N 50 -s 65 -z 200 --mask-level 0.9 -f 200 \
     --cs -t 4 SAMPLE1/quast_corrected_input/ref_genome.fa \
     SAMPLE1/quast_corrected_input/CANU.fasta > SAMPLE1/contigs_reports/minimap_output/CANU.coords_tmp \
     2>> SAMPLE1/contigs_reports/contigs_report_CANU.stderr

```

Coverage of the reference scaffolds using the canu assembly seems to be good enough for the largest scaffold but poor for the others. But still the largest contig should align to the assembly much higher than 42% (current genome fraction returned by quast). 

```
Contig | Coverage | Size of contig
tig00000001 | 153,243514 | 2401703
tig00000002 | 6,964671 | 23550
tig00000004 | 6,58085 | 5671
tig00000005 | 7,075151 | 15369
tig00000006 | 7,796166 | 14762
tig00000008 | 6,378989 | 12784
tig00000012 | 6,197856 | 12873
tig00000016 | 6,696972 | 12814
tig00000017 | 7,198031 | 8837
tig00000018 | 8,03012 | 14442
tig00000019 | 8,628038 | 12469
tig00000025 | 6,019222 | 6867
tig00000027 | 7,888349 | 11724
tig00000028 | 8,843412 | 10071
tig00000029 | 14,954398 | 4013
tig00000033 | 6,372372 | 8991
tig00000718 | 4,778756 | 7268
tig00000719 | 4,798407 | 14812


```

**Comment by skoren** [comment]
The 42% isn't the amount of the genome captured but the part that could be aligned. The ```-asm 5``` parameter is tuned to align at up to 95% identity. So, if your assembly is 95% identity to the truth and the truth is 2% diverged from the reference (I am guessing the numbers as an example) then then expected identity between the assembly and reference is 93%. The accuracy and divergence aren't constant across the genome so parts will be >=95% and parts will be <95%. The alignment and stats will only capture those >=95% which will gives your 42%. 

You can either modify the minimap2 call in quast to run at a higher error rate (```-asm10``` for example) or run nanopolish which will improve the accuracy to 98-99% so then the identity of most of the genome will be >=95% and will be aligned.

**Comment by davidvilanova** [comment]
Sounds good to me. So far i have run racon on top of the canu assembly, i will add the nanopolish step. On the other hand i will try minimap2 with `-asm10`.
Do you think racon is still needed on top of racon ? I have seen an improved assembly less than 1%.

**Comment by skoren** [comment]
Racon isn't worth running on top of Canu, it improves it in some cases and makes it worse in some others in our experience but all are relatively minor changes. Either way, it's relying on the fasta sequences to call a consensus and Canu has its own consensus module already so the next boost in quality will come from either another technology (e.g. Illumina + Pilon) or signal-level information in the data (e.g. Nanopolish).

**Comment by davidvilanova** [comment]
Thanks so much for the comments. I will definitely try nanopolish while the illumina data for the same species is coming alone so i guess it will improve the assembly.

**Comment by skoren** [comment]
Closing, resolved.
