### ISSUE TITLE
Canu Correction failed

### ISSUE THREAD

**Issue by samuelbloomfield** [marbl/canu#830]
Hello, I am trying to run Canu 1.7 on some PacBio reads. However, I keep getting problems at the correction step and I could not find a way to correct the problem online. 

I have attached the section of the canu.01.out file which describes when the problem occured:

```
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Wed Mar 21 08:30:58 2018 with 695.727 GB free disk space

    cd .
    /home/ubuntu/canu-1.7/Linux-amd64/bin/gatekeeperCreate \
      -minlength 1000 \
      -o ./temp_subreads.gkpStore.BUILDING \
      ./temp_subreads.gkpStore.gkp \
    > ./temp_subreads.gkpStore.BUILDING.err 2>&1
-- WARNING:
-- WARNING:  Previously failed gkpStore detected.
-- WARNING:

-- Finished on Wed Mar 21 08:30:58 2018 (lickety-split) with 695.727 GB free disk space
----------------------------------------
    /home/ubuntu/canu-1.7/Linux-amd64/bin/gatekeeperDumpMetaData \
      -G ./temp_subreads.gkpStore \
      -libs \
    > ./temp_subreads.gkpStore/libraries.txt \
    2> /dev/null

ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:

ABORT:
ABORT: Canu 1.7
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   gatekeeper failed.
ABORT:

ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:

ABORT:
ABORT: Canu 1.7
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to generate list of libraries in store.
ABORT:

```

**Comment by samuelbloomfield** [comment]
I deleted the entire output directory and re-ran canu with a differently named output directory, and received the same error. However, the rest of the script seemed to have worked, so I am less worried now.

**Comment by skoren** [comment]
The same error and Canu stopping or a different error? So is the issue resolved and you are able to run an assembly?

**Comment by samuelbloomfield** [comment]
I got the same error. To tell the truth when I first got the error I stopped the assembly. Therefore, I don't know if it would have assembled correctly. Regardless, the assemblies seemed to have worked so I am not too worried about it now, even though I continue to get the same error.

**Comment by skoren** [comment]
Are you able to share the input data so we could try to reproduce it locally? Would be good to fix even if it still assembles.

**Comment by skoren** [comment]
Closing inactive, assembly completed.
