### ISSUE TITLE
Canu 1.7 Crashed

### ISSUE THREAD

**Issue by romeA4** [marbl/canu#831]
My high coverage, about 500x, crashes when running on the grid.
Seems that batch job submission failed due to some parameter being too long.
Restarting or manually trying to run batch script does not seem to work.
Please advice.

**Runing the following on the grid:**
```
#!/bin/bash
#SBATCH --job-name=strain4-canu-maxcov  		
#SBATCH --partition=hugemem				
#SBATCH -o output_%j.txt				
#SBATCH -e errors_%j.txt				


cp Strain04-from1804.fastq.gz $SCRATCH

## Move to work directory
cd $SCRATCH

## Loading and running canu module
module load canu
canu -p strain4-canu-maxcov -d strain4-canu-maxcov genomeSize=4.8m corOutCoverage=999 -nanopore-raw Strain04-from1804.fastq.gz

**Error output**

-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_65' (from '/local/genome/packages/java/jdk1.8.0_65/bin/java').
-- Detected gnuplot version '5.0 patchlevel 6' (from 'gnuplot') and image format 'svg'.
-- Detected 80 CPUs and 1010 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /local/genome/packages/slurm/15.08.5/bin/sinfo.
-- Detected Slurm with 'MaxArraySize' limited to 99999 jobs.
-- 
-- Found   1 host  with  12 cores and   31 GB memory under Slurm control.
-- Found   2 hosts with  80 cores and 1009 GB memory under Slurm control.
-- Found  18 hosts with   8 cores and   15 GB memory under Slurm control.
-- Found   7 hosts with  32 cores and  189 GB memory under Slurm control.
-- Found   3 hosts with   4 cores and    3 GB memory under Slurm control.
-- Found   1 host  with   6 cores and   14 GB memory under Slurm control.
-- Found   1 host  with  48 cores and  189 GB memory under Slurm control.
-- Found   2 hosts with  12 cores and   62 GB memory under Slurm control.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl      8 GB    4 CPUs  (k-mer counting)
-- Grid:  cormhap    6 GB    4 CPUs  (overlap detection with mhap)
-- Grid:  obtovl     4 GB    4 CPUs  (overlap detection)
-- Grid:  utgovl     4 GB    4 CPUs  (overlap detection)
-- Grid:  ovb        2 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs        8 GB    1 CPU   (overlap store sorting)
-- Grid:  red        3 GB    4 CPUs  (read error detection)
-- Grid:  oea        4 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat       16 GB    4 CPUs  (contig construction)
-- Grid:  gfa        8 GB    4 CPUs  (GFA alignment and processing)
--
-- In 'strain4-canu-maxcov.gkpStore', found Nanopore reads:
--   Raw:        332249
--   Corrected:  216721
--   Trimmed:    196452
--
-- Generating assembly 'strain4-canu-maxcov' in '/mnt/SCRATCH/rmeisal/strain4-canu-maxcov'
--
-- Parameters:
--
--  genomeSize        4800000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1440 ( 14.40%)
--    utgOvlErrorRate 0.1440 ( 14.40%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1440 ( 14.40%)
--    utgErrorRate    0.1440 ( 14.40%)
--    cnsErrorRate    0.1920 ( 19.20%)
--
--
-- BEGIN ASSEMBLY
--
--
-- Running jobs.  First attempt out of 2.
--

CRASH:
CRASH: Canu 1.7
CRASH: Please panic, this is abnormal.
ABORT:
CRASH:   Failed to submit batch jobs.
CRASH:
CRASH: Failed at /mnt/various/local/genome/packages/canu/1.7/Linux-amd64/bin/../lib/site_perl/canu/Execution.pm line 1101.
CRASH: 	canu::Execution::submitOrRunParallelJob("strain4-canu-maxcov", "red", "unitigging/3-overlapErrorAdjustment", "red", 1, 2, 3, 4, ...) called at /mnt/various/local/genome/packages/canu/1.7/Linux-amd64/bin/../lib/site_perl/canu/OverlapErrorAdjustment.pm line 351
CRASH: 	canu::OverlapErrorAdjustment::readErrorDetectionCheck("strain4-canu-maxcov") called at /local/genome/packages/canu/1.7/bin/canu line 685
CRASH: 
CRASH: Last 50 lines of the relevant log file (unitigging/3-overlapErrorAdjustment/red.jobSubmit-01.out):
CRASH:
CRASH:
```

**Output from red.jobsubmit-01.out**
```
sbatch: error: Batch job submission failed: Pathname of a file, directory or other parameter too long
```

**Comment by skoren** [comment]
The paths should all be relative to the working directory so I expect there is something else your slurm doesn't like about the submit command. Can you post the contents of ```unitigging/3-overlapErrorAdjustment/red.jobSubmit-01.sh```?

**Comment by romeA4** [comment]
Hi Skoren, thanks, here you have the content of asked file:

#!/bin/sh

sbatch \
  --mem-per-cpu=768m --cpus-per-task=4 -o red.%A_%a.out \
  -D `pwd` -J "red_strain4-canu-maxcov" \
  -a 1-99999 \
  ./red.sh 0 \
> ./red.jobSubmit-01.out 2>&1

**Comment by skoren** [comment]
OK I suspect the issue here is too many RED jobs. Remove the ```unitigging/3-overlapErrorAdjustment``` folder and re-launch Canu with the options ```redMemory=60 oeaMemory=60```. 

This happened because you have more corrected coverage than typical due to the corOutCoverage being set to 999. Generally you don't need more than about 40x (the default) to get a good assembly unless you have a meta genome.

**Comment by romeA4** [comment]
Solved.
using the redMemory=60 and oeaMemory=60 solved the problem.
Thanks!!

**Comment by briangsaint** [comment]
Hello, 

I am having a similar issue. 
I have high coverage as well.
Tried to follow this comment thread to fix but couldn't solve my problem.

Here is the out file from SLURM...


***********************
-- Canu snapshot v1.8 +65 changes (r9275 4b1747852a4831c877bb907fe6cd08dcc48b27f6)
--
-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
-- 
-- Koren S, Rhie A, Walenz BP, Dilthey AT, Bickhart DM, Kingan SB, Hiendleder S, Williams JL, Smith TPL, Phillippy AM.
-- De novo assembly of haplotype-resolved genomes with trio binning.
-- Nat Biotechnol. 2018
-- https//doi.org/10.1038/nbt.4277
-- 
-- Read and contig alignments during correction, consensus and GFA building use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_65' (from 'java') with -d64 support.
-- Detected gnuplot version '5.0 patchlevel 5   ' (from 'gnuplot') and image format 'png'.
-- Detected 160 CPUs and 251 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /usr/bin/sinfo.
-- Detected Slurm with 'MaxArraySize' limited to 1000 jobs.
-- 
-- Found   3 hosts with  24 cores and   83 GB memory under Slurm control.
-- Found   3 hosts with 160 cores and  165 GB memory under Slurm control.
-- Found   1 host  with  80 cores and  165 GB memory under Slurm control.
-- Found   1 host  with  80 cores and   71 GB memory under Slurm control.
-- Found   1 host  with 160 cores and  812 GB memory under Slurm control.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl     12 GB    8 CPUs  (k-mer counting)
-- Grid:  hap        7 GB    8 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap    8 GB   10 CPUs  (overlap detection with mhap)
-- Grid:  obtovl     8 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl     8 GB    8 CPUs  (overlap detection)
-- Grid:  cor      --- GB    4 CPUs  (read correction)
-- Grid:  ovb        4 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs        8 GB    1 CPU   (overlap store sorting)
-- Grid:  red        6 GB    6 CPUs  (read error detection)
-- Grid:  oea        4 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat       64 GB    8 CPUs  (contig construction with bogart)
-- Grid:  cns      --- GB    8 CPUs  (consensus)
-- Grid:  gfa        8 GB    8 CPUs  (GFA alignment and processing)
--
-- Found PacBio uncorrected reads in the input files.
--
-- Generating assembly 'pbachei' in '/gpfs0/work/brian/canu_bachei/pbachei-pacbio'
--
-- Parameters:
--
--  genomeSize        150000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0750 (  7.50%)
--
--
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Wed Dec 12 21:11:02 2018 with 5658.656 GB free disk space

    cd .
    /gpfs0/work/brian/scripts/canu/Linux-ppc64le/bin/sqStoreCreate \
      -o ./pbachei.seqStore.BUILDING \
      -minlength 1000 \
      ./pbachei.seqStore.ssi \
    > ./pbachei.seqStore.BUILDING.err 2>&1

-- Finished on Wed Dec 12 21:20:34 2018 (572 seconds) with 5650.359 GB free disk space
----------------------------------------
--
-- In sequence store './pbachei.seqStore':
--   Found 4336850 reads.
--   Found 24348934185 bases (162.32 times coverage).
--
--   Read length histogram (one '*' equals 31398.91 reads):
--        0   4999 2197924 **********************************************************************
--     5000   9999 1673807 *****************************************************
--    10000  14999 349400 ***********
--    15000  19999  79691 **
--    20000  24999  21106 
--    25000  29999   7030 
--    30000  34999   3150 
--    35000  39999   1590 
--    40000  44999   1019 
--    45000  49999    672 
--    50000  54999    407 
--    55000  59999    335 
--    60000  64999    231 
--    65000  69999    137 
--    70000  74999     94 
--    75000  79999     77 
--    80000  84999     54 
--    85000  89999     36 
--    90000  94999     30 
--    95000  99999     22 
--   100000 104999     10 
--   105000 109999      3 
--   110000 114999      5 
--   115000 119999      3 
--   120000 124999      4 
--   125000 129999      3 
--   130000 134999      1 
--   135000 139999      0 
--   140000 144999      1 
--   145000 149999      2 
--   150000 154999      1 
--   155000 159999      2 
--   160000 164999      0 
--   165000 169999      1 
--   170000 174999      0 
--   175000 179999      0 
--   180000 184999      1 
--   185000 189999      1 
----------------------------------------
-- Starting command on Wed Dec 12 21:21:40 2018 with 5650.218 GB free disk space

    cd correction/0-mercounts
    ./meryl-configure.sh \
    > ./meryl-configure.err 2>&1

-- Finished on Wed Dec 12 21:21:43 2018 (3 seconds) with 5650.218 GB free disk space
----------------------------------------
--  segments   memory batches
--  -------- -------- -------
--        01 12.00 GB       5
--        02 12.00 GB       3
--        04 12.00 GB       2
--        06  8.01 GB       1
--        08  7.00 GB       1
--        12  4.01 GB       1
--        16  3.50 GB       1
--        20  3.12 GB       1
--        24  2.62 GB       1
--        32  2.00 GB       1
--        40  1.56 GB       1
--        48  1.31 GB       1
--        56  1.12 GB       1
--        64  1.00 GB       1
--        96  0.69 GB       1
--
--  For 4336850 reads with 24348934185 bases, limit to 243 batches.
--  Will count kmers using 06 jobs, each using 10 GB and 8 threads.
--
-- Finished stage 'merylConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
--

CRASH:
CRASH: Canu snapshot v1.8 +65 changes (r9275 4b1747852a4831c877bb907fe6cd08dcc48b27f6)
CRASH: Please panic, this is abnormal.
ABORT:
CRASH:   Failed to submit batch jobs.
CRASH:
CRASH: Failed at /gpfs0/work/brian/scripts/canu/Linux-ppc64le/bin/../lib/site_perl/canu/Execution.pm line 1235.
CRASH: 	canu::Execution::submitOrRunParallelJob("pbachei", "meryl", "correction/0-mercounts", "meryl-count", 1, 2, 3, 4, 5, ...) called at /gpfs0/work/brian/scripts/canu/Linux-ppc64le/bin/../lib/site_perl/canu/Meryl.pm line 818
CRASH: 	canu::Meryl::merylCountCheck("pbachei", "cor") called at /gpfs0/work/brian/scripts/canu/Linux-ppc64le/bin/canu line 807
CRASH: 
CRASH: Last 50 lines of the relevant log file (correction/0-mercounts/meryl-count.jobSubmit-01.out):
CRASH:
CRASH: sbatch: error: Batch job submission failed: Requested time limit is invalid (missing or exceeds some limit)
CRASH:
***********************

**Comment by skoren** [comment]
Nope, not similar, the error message is due to your slurm cluster rejecting the canu job. Looks like your cluster wants you to include a time request. You didn't give your canu command but I assume you didn't set gridOptions? You'll need to set it and specify a wall clock time. See the FAQ: https://canu.readthedocs.io/en/latest/faq.html#my-run-stopped-with-the-error-failed-to-submit-batch-jobs for details.

**Comment by briangsaint** [comment]
Hey Skoren,
Thanks for the rapid reply. You're absolutely right, I didn't set a wall time. 
So from googling around and the FAQ a fix would be to submit a command such as /gpfs0/work/brian/scripts/canu/Linux-ppc64le/bin/canu -p pbachei -d pbachei-pacbio genomeSize=150m -pacbio-raw pacbio_pbachei_all.fasta.gz gridOptions="--time=1440" ?
