### ISSUE TITLE
Problem with Assembly stage

### ISSUE THREAD

**Issue by jhtrujillo** [marbl/canu#832]
I itraying to run the assembly stage, but I got the following error:

Processing './index'
  Now finished with fragments 1 to 4743 -- 119309431 overlaps.
Processing './0001.index'
  No overlaps found.
Processing './0001.index'
  Adding empty records for fragments 4744 to 8534
  Now finished with fragments 1 to 14018 -- 238279332 overlaps.
Processing './0003.index'
ERROR: './0004.index' starts with iid 13003, but store only up to 14018

```
-- BEGIN ASSEMBLY
--
----------------------------------------
-- Starting command on Wed Mar 21 11:10:38 2018 with 3181.115 GB free disk space

    cd unitigging/pacBioall.ovlStore.BUILDING
    ./scripts/3-index.sh \
    > ./logs/3-index.err 2>&1

-- Finished on Wed Mar 21 11:10:39 2018 (1 second) with 3181.115 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:
================================================================================
Don't panic, but a mostly harmless error occurred and Canu stopped.

Disk space available:  3181.115 GB

Last 50 lines of the relevant log file (unitigging/pacBioall.ovlStore.BUILDING/logs/3-index.err):
```

**Comment by skoren** [comment]
That error seems strange, especially since the failing ID is smaller than the max. What does canu -version report?

**Comment by jhtrujillo** [comment]
I solved the problem by restarting the last stage. 

However, I have another problem. I finished my assembly using 50 Gbps of PacBio, delivering good results. This assembly was repeated using 100 Gbps of PacBio but the results were bad compared to the first assembly. What could be happening?

**Comment by skoren** [comment]
Can't say without more information, at least the parameters between versions and the reports output by Canu.
