### ISSUE TITLE
falconsense: inefficient I/O on filesystem with large block size

### ISSUE THREAD

**Issue by wookietreiber** [marbl/canu#834]
## analysis

We realized that the **falconsense** step on our HPC cluster runs with an inefficient I/O performance.

Our filesystem is a IBM GPFS / Spectrum Scale, i.e. it is networked, not local. It has a 2 MB filesystem block size. This results in the following read behavior (captured with `strace -p $(pidof falconsens)`):

```console
$ head strace-falconsense.log.19323
1521030436.617850 lseek(3, 7837057024, SEEK_SET) = 7837057024 <0.000009>
1521030436.617933 read(3, "..."..., 2097152) = 2097152 <0.017566>
1521030436.635592 lseek(3, 13040091136, SEEK_SET) = 13040091136 <0.000008>
1521030436.635615 read(3, "..."..., 2097152) = 2097152 <0.022290>
1521030436.657967 lseek(3, 4722786304, SEEK_SET) = 4722786304 <0.000008>
1521030436.657988 read(3, "..."..., 2097152) = 2097152 <0.655112>
1521030437.313192 lseek(3, 12769558528, SEEK_SET) = 12769558528 <0.000007>
1521030437.313215 read(3, "..."..., 2097152) = 2097152 <0.037452>
1521030437.350754 lseek(3, 3107979264, SEEK_SET) = 3107979264 <0.000007>
1521030437.350786 read(3, "..."..., 2097152) = 2097152 <0.243697>

$ lsof -p $(pidof falconsense)
falconsen 19323 user  txt    REG   0,21     3406056 673872987 /path/to/bin/falconsense
falconsen 19323 user  cwd    DIR   0,21        4096 471306209 /work/user/PacBio_assemblies/20180313_canu/correction/2-correction
falconsen 19323 user    1w   REG   0,21    18174578 701143852 /work/user/PacBio_assemblies/20180313_canu/correction/2-correction/results/0051.err
falconsen 19323 user    2w   REG   0,21    18174578 701143852 /work/user/PacBio_assemblies/20180313_canu/correction/2-correction/results/0051.err
falconsen 19323 user    7w   REG   0,21    94371840 722116328 /work/user/PacBio_assemblies/20180313_canu/correction/2-correction/results/0051.WORKING.cns
falconsen 19323 user    8r   REG   0,21  4263206312 471306707 /work/user/PacBio_assemblies/20180313_canu/correction/delia_radicum.corStore/seqDB.v001.dat
falconsen 19323 user    3r   REG   0,21 15577652764  20406425 /work/user/PacBio_assemblies/20180313_canu/delia_radicum.gkpStore/blobs
falconsen 19323 user    4r   REG   0,21 15577652764  20406425 /work/user/PacBio_assemblies/20180313_canu/delia_radicum.gkpStore/blobs
falconsen 19323 user    5r   REG   0,21 15577652764  20406425 /work/user/PacBio_assemblies/20180313_canu/delia_radicum.gkpStore/blobs
falconsen 19323 user    6r   REG   0,21 15577652764  20406425 /work/user/PacBio_assemblies/20180313_canu/delia_radicum.gkpStore/blobs
```

The `blobs` file is opened four times because of parallelism, i.e. I guess each worker thread jumping to its assigned indices of the file.

As you can see, the falconsense tool is jumping to a point in the file and reads a 2 MB chunk. Then, I suppose, it only needs a few bytes / kilobytes of that 2 MB chunk, processes it, and then continues to the next chunk. Here is a visualization of this process:

![canu_0](https://user-images.githubusercontent.com/827088/37765979-f4ab319c-2dc5-11e8-9a94-64fd6c6802bb.jpg)

The vertical bars represent the entire 2 MB chunk that is read, while only the small, highlighted black portion in the top represents the data that is actually needed for that read. The rest (unhighlighted portion of the chunk), is essentially read multiple times and thrown away. If you would **strace** the entire falconsense run, not just the sample as we did above, and sum up all the bytes read, it would be larger than the **blobs** file size. This problem gets exceedingly important with increasing file system block sizes. 

## possible solutions

I suppose, our large block size combined with the read behavior of falconsense is causing the inefficient I/O performance. I figure, there are two possible solutions to this issue:

1.  do not read the entire chunk of 2 MB, but just the part you're interested in, i.e. not `read(fd, buf, FS_BLOCK_SIZE)` but `read(fd, buf, next_index - cur_index + 1)`
1.  Just read the file as a whole without indexing, though I suppose this is not what you want to do because its a requirement for your parallelism.

## system information

```console
$ cat /etc/centos-release
CentOS release 6.9 (Final)

$ uname -a
Linux idiv1 2.6.32-696.13.2.el6.x86_64 #1 SMP Thu Oct 5 21:22:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ qconf -help | head -1
UGE 8.4.4

$ canu -version
Canu snapshot v1.6 +275 changes (r8687 9addfb95f2b79b61f35b2aae12bab7343491bcd0)
```

```
canu \
  -p my_prefix \
  -d /path/to/results \
  genomeSize=800m \
  minReadLength=10000 \
  stopOnReadQuality=false \
  maxMemory=.. \
  maxThreads=.. \
  gridEngineMemoryOption="..." \
  gridEngineThreadsOption="..." \
  -pacbio-raw \
  /path/to/raw/*.fa
```

**Comment by skoren** [comment]
Kudos for the detailed analysis, yes we've seen this performance issue on our GPFS as well. The 2MB read isn't coming from the code but GPFS because the code is only asking for a reads worth of information at a time (which is 2-bit encoded). The GPFS seems unwilling or unable to retrieve less than this so the code gets 2mb and dumps everything but a few bytes. The reads aren't 2mb on other filesystems. We had previously tried memory mapped files (similar to your option 2) but GPFS doesn't work any better with those either for similar reasons.

Our solution has been to enable staging for this step in the pipeline which copies the gkpStore folder to local scratch space on each compute node and avoids I/O. On our GPFS system this drops the wall time of a falcon sense job from 24 to <2 hrs on a large genome. As long as you have local scratch on your systems, you can enable the staging with two options
```stageDirectory=/lscratch/$SLURM_JOBID gridEngineStageOption="--gres=lscratch:100"```
The first tells Canu where to copy the gkpStore, it has to be unique to each job within the array and the grid options is needed if there is a way to reserve scratch space on your grid.

**Comment by skoren** [comment]
The issue with GPFS is known and addressed by staging to scratch.
