### ISSUE TITLE
Question: subsampling datasets using the longest reads

### ISSUE THREAD

**Issue by alimayy** [marbl/canu#841]
Hi, thanks a lot for developing Canu. Unfortunately I didn't have the chance to investigate in detail so apologies if this question was asked before: I was wondering whether subsampling very large datasets using the longest reads possible (e.g. to 100-200X for a bacterial genome) could possibly have any undesired effect for Canu, for instance for the error correction module?

Thanks in advance
Ali

**Comment by skoren** [comment]
The main negative effect is likely to be loss of short sequence (e.g. plasmids). The longest may also not be the best quality so a read you think is 100kbp is really only 20kb and you end up with less coverage than you expected. 

For these reason, we usually take a random sampling to reduce coverage. Canu will automatically select the "best" subset of those keeping the longest based on quality and keeping any short sequences which represent unique sequence.

**Comment by alimayy** [comment]
Thanks a lot for your answer, it makes perfect sense. I'll adjust our sampling procedure accordingly. Please consider this ticket closed.
