### ISSUE TITLE
Default memory usage twice the available memory on the machine in version 1.1

### ISSUE THREAD

**Issue by schmeing** [marbl/canu#85]
I reran the newest version of canu (1.1) on some data I previously ran version 1.0 on and did not specify any memory:
nice -19 canu -p asm -d 00-assembly genomeSize=0.7g corMhapSensitivity=high corMinCoverage=2 errorRate=0.035 -pacbio-raw ../../../data/pacBio/01_original/*.fastq.gz | tee canu.log

In the second step of asm.ovlStore.BUILDING "2-sort" it used all 64 cores with 16GB of memory each, blocking itself from memory so the threads crashed because they couldn't allocate memory, restarted blocked the rest and finally crashed again, ending up in a loop.

In version 1.0 it ran through just fine.
The server has 512GB of swap. Did canu add the swap to the physical memory for determining the maximum usable memory?

P.S.: Is it normal that the "correction/1-overlapper/results/" folder has a size of 7.4T for a 0.7gb genome with 30x coverage?

Is there a way to continue the correction process or do I have to restart it from scratch?

**Comment by skoren** [comment]
I think the large size of the store is due to the bug in 1.1 (issue #80) so the next release would decrease its size.

The memory usage is a bug in the local scheduling of jobs, it is running the maximum number of parallel threads you machine can fit but not checking the memory. You can limit the number of jobs with 
```
ovsConcurrency=32
```
to limit it to using 16 * 32 or 512 GB of ram. You should be able to resume by re-running your original command.

**Comment by woodoo46** [comment]
So we can safely remove the data in that directory: correction/1-overlapper/results/?

**Comment by skoren** [comment]
No, not until the store is built then it is automatically removed.

**Comment by woodoo46** [comment]
If the canu pipeline finishes, we can remove the directory?

**Comment by skoren** [comment]
Yes, but the output files in that directory should already be removed. Do you have large files remaining in that directory after a run?

**Comment by woodoo46** [comment]
Yes. I had data is there. Does it suggest our run did not finish correctly?

**Comment by skoren** [comment]
No, if you have an assembly the run finished correctly, the cleanup may be missing some files though that it should have removed.
