### ISSUE TITLE
Can I remove directory of  ovlStore in trimming?

### ISSUE THREAD

**Issue by lamz138138** [marbl/canu#851]
Hi, dear canu team,

My programme is in the step of unitigging, and the directory of 0-mercounts was created. I had thought the directory of trimming/.*ovlStore would be deleted to release disk, but now I found only a few of disk is left.  Thus, I review my demos, I found there are different files in trimming: one demo remove .*ovlStore, the others keep the directory, but one have "0001  evalueLen  index  info  overlapScores", while another only have "0001  index  info". Maybe these were caused by different canu versions.
 
Considering the version at the moment is (Canu snapshot v1.6 +133 changes (r8545 f960f2ebf249ff07b991407e2b81981c46443315)), can I delete the directory of trimming/.*ovlStore to release disk?

Any suggestion would be grateful!

Best wishes!

**Comment by skoren** [comment]
As long as you have the trimmed reads and have moved onto unitigging, you can remove the files from inside the ovlStore folder in trimming.

**Comment by lamz138138** [comment]
OK, thanks very much!
