### ISSUE TITLE
Adding Pacbio data worsens genome assembly

### ISSUE THREAD

**Issue by kushalsuryamohan** [marbl/canu#852]
Hello again @skoren,
If you recall from earlier messages, I used ~30X (52.6 Gbp, assuming genome size= 1.5-2 Gb) of ONT data to assemble de novo a snake genome and after a few iterations, got a decent assembly with an NG50 of 267 Kb. I polished the assembly using Pilon with Illumina data and then tested assembly completeness using BUSCO.
Here are the parameters I specified for the assembly using Canu v1.6 - 

`'corMemory=20' 'stopOnReadQuality=0' 'genomeSize=1.5g' 'correctedErrorRate=0.105' 'mhapMemory=20g'`

By comparison to the best snake assembly (another species) currently available, the BUSCO scores for this assembly are far better (For Eukaryota, my assembly has 82% complete BUSCOs compared to 64% for the other species' assembly).

Since then, I have acquired about 40 Gbp of Pacbio RSII data and I've tried combining the two technologies' data to assemble the snake genome on an LSF grid (canu version 1.7).

Running on default parameters gave a worse assembly in terms of contiguity (NG50 = 76 Kbp) and so I re-ran the pipeline with the following parameters -
`'corMaxEvidenceErate=0.12' 'corOutCoverage=40' 'cormhapSensitivity=normal' 'mhapThreads=8' 'mhapMemory=15' 'corminCoverage=0' 'genomeSize=1.5g'`

This improved the assembly NG50 to 214 Kbp but I would have hoped naively that adding more data would improve the assembly. 

I actually just got another 20 Gbp of Pacbio Sequel data and I'm hoping to improve the assembly with this additional data - It would be a real shame if the best assembly is achieved using only the Oxford data. Being new to the field of genome assembly, I would really appreciate your help in figuring out the issue here.

Attached are reports from the two assemblies.

Thanks!

[Archive.zip](https://github.com/marbl/canu/files/1868824/Archive.zip)

**Comment by skoren** [comment]
From the second run, it looks like the reads didn't get corrected as well.

I would suggest sticking to the same Canu version, either 1.7 or 1.6 for comparisons, just in case something changed between versions. Have you tried assembling just the PacBio data alone with defaults? For the combination, I'd remove corMaxEvidenceErate and corminCoverage and increase corOutCoverage to 100 and keep your correctedErrorRate=0.105 parameter as well.

**Comment by skoren** [comment]
Is this an early Sequel chemistry? What I'd suggest is correcting the data separately and mixing after. You could even run correction multiple times on the PacBio data, try it with ```corMhapSensitivity=high corMaxEvidenceErate=0.12 corOutCoverage=100 corMinCoverage=0```, just run the PacBio through and then run the same parameters again giving the corrected data as raw. That should improve the accuracy. Then combine this data with the nanopore corrected reads you have from your nanopore-only run.

**Comment by kushalsuryamohan** [comment]
Yes, it is an early Pacbio chemistry (run on the RSII and not the Sequel).
I'll give your suggestions a try and see how it works.
Many thanks!

**Comment by brianwalenz** [comment]
Don't forget to let us know how it works.  ;-)
