### ISSUE TITLE
Meryl memory problem

### ISSUE THREAD

**Issue by dikkeaap** [marbl/canu#853]
Hi, I'm running canu-1.7 with the -fast option on a large (~15 Gb) plant genome that we have assembled before on a low coverage (~25x) dataset. We have now generated additional data up to ~50x coverage but are running into some memory issues during the initial meryl stage. The full command line I used for canu-1.7 is

`~/tools/canu-1.7/Linux-amd64/bin/canu -p ORGANISM -d canu-1.7 genomeSize=15G -pacbio-raw filtered.fasta/* -fast -useGrid=true -gridEngineThreadsOption="-pe smp THREADS" -gridEngineMemoryOption="-l mem_total=MEMORY" -batThreads=40 -batMemory=250G`

During the correction stage, meryl crashes with the following error message found at the end of correction/0-mercounts/meryl.1.out 

```
what():  std::bad_alloc
Can fit 382537302016 mers into table with prefix of 29 bits, using 206438.000MB (0.000MB for positions)
```

The machine with the largest memory on our cluster has 256 Gb RAM; meryl was running on this machine, and was the only (relevant) process on that machine. It seems this is insufficient for this dataset, but was sufficient for the ~25x coverage. Are there any parameters I can adjust to lessen the memory requirement; or, alternatively, is there any way to estimate a realistic upper limit on the required memory so we can upgrade machines if needed?

Best,
Erwin Datema

**Comment by skoren** [comment]
Meryl can run in essentially any memory available so 256g is more than enough. I suspect the machine doesn't actually have as much free memory as it claims or the memory isn't properly reserved by the scheduler. Try setting merylMemory=100 to constrain it explicitly.

**Comment by dikkeaap** [comment]
I keep getting the same error, I can see meryl running on an otherwise unoccupied node in the cluster (with 256 Gb RAM) and it honrestly does run out of memory. The output in meryl.1.out I showed above indicates to me it's using more than 200 Gb RAM. Any suggestions how I can debug this?

Thanks for the pointer on the fast option. I haven't found it explained in detail anywhere; what does it do exactly?

**Comment by brianwalenz** [comment]
What's in meryl.sh?  My only guess, and I'm not sure I agree with it, is that excessive threads are eating up memory.

What's the first line in meryl.out?  Something like "Computing N segments using T threads and NNNMB memory ....".

-fast switches from an alignment-based overlap method to an alignment-free overlap method (the same one used during correction).  It seems to work, but we haven't really validated it yet.

**Comment by dikkeaap** [comment]
The top of meryl.1.out contains

```
Computing 64 segments using 32 threads and 206432MB memory (227607MB if in one batch).
  numMersActual      = 629279007072
  mersPerBatch       = 11954290688
  basesPerBatch      = 9842614142
  numBuckets         = 33554432 (25 bits)
  bucketPointerWidth = 34
  merDataWidth       = 7
'''

**Comment by dikkeaap** [comment]
meryl.sh contains:

```
syst=`uname -s`
arch=`uname -m | sed s/x86_64/amd64/`

bin="/data/interos/eda/tools/canu-1.7/$syst-$arch/bin"

if [ ! -d "$bin" ] ; then
  bin="/data/interos/eda/tools/canu-1.7"
fi


#  Store must exist: correction/allium_cepa.gkpStore

#  Purge any previous intermediate result.  Possibly not needed, but safer.

rm -f ./allium_cepa.ms16.WORKING*

$bin/meryl \
  -B -C -L 2 -v -m 16 -threads 32 -memory 206438 \
  -s ../allium_cepa.gkpStore \
  -o ./allium_cepa.ms16.WORKING \
&& \
mv ./allium_cepa.ms16.WORKING.mcdat ./allium_cepa.ms16.mcdat \
&& \
mv ./allium_cepa.ms16.WORKING.mcidx ./allium_cepa.ms16.mcidx

#  File is important: allium_cepa.ms16.mcdat

#  File is important: allium_cepa.ms16.mcidx


#  Dump a histogram

$bin/meryl \
  -Dh -s ./allium_cepa.ms16 \
>  ./allium_cepa.ms16.histogram.WORKING \
2> ./allium_cepa.ms16.histogram.info \
&& \
mv -f ./allium_cepa.ms16.histogram.WORKING ./allium_cepa.ms16.histogram

#  File is important: allium_cepa.ms16.histogram

#  File is important: allium_cepa.ms16.histogram.info


#  Compute a nice kmer threshold.

$bin/estimate-mer-threshold \
  -h ./allium_cepa.ms16.histogram \
  -c 39 \
>  ./allium_cepa.ms16.estMerThresh.out.WORKING \
2> ./allium_cepa.ms16.estMerThresh.err \
&& \
mv ./allium_cepa.ms16.estMerThresh.out.WORKING ./allium_cepa.ms16.estMerThresh.out

#  File is important: allium_cepa.ms16.estMerThresh.out

#  File is important: allium_cepa.ms16.estMerThresh.err


exit 0
```

**Comment by skoren** [comment]
That looks like it didn't get re-run with my suggested lowered merylMemory. You can manually edit the meryl.sh script to change the memory from 206438 to 106438 and then run meryl.jobSubmit-01.sh  from within the 0-mercounts folder. That should run to completion and you could then resume Canu.

**Comment by dikkeaap** [comment]
Editing meryl.jobSubmit-01.sh as suggested solved the issue, thanks!
