### ISSUE TITLE
mhap correction taking very long

### ISSUE THREAD

**Issue by MarkChristianHarrison** [marbl/canu#855]
Hi,

I'm running Canu under default settings, except for preventing grid usage:
/Canu/canu-1.7/Linux-amd64/bin/canu useGrid=false -p Dpun -d Dpun_Canu genomeSize=3.0g -pacbio-raw *fastq

It's quite a large genome at an estimated 3.0 Gb and it is also rather repetitive at approx. 51%. The pacbio reads are uncorrected and I have roughly 60x coverage.

The assembly is running on a virtual machine with a Ubunutu OS (cloud image v18), with 2Tb RAM, 90 CPUs and 15Tb storage (connected via NFS). The assembly has become very slow at the 'cormhap' stage. 6 jobs are running in parallel on 15 CPUs each, and these are taking about a day to complete. There are 1600 processes to be completed in this stage so if each batch of 6 takes a day this will take almost a year to complete.

Do you have any tips on how to speed things up or some reassurances that it may get quicker as it proceeds?

Thanks,
Mark

**Comment by skoren** [comment]
Fundamentally, your genome is too big to run on a single node. A human genome would take 2-4 weeks on a single machine and I'm not sure what overhead the VM adds. You said it is more repetitive so will likely take longer. You can take a look at some suggestions in issue #587 to dowweight repeats more which should also decrease runtime. Ideally, though if a grid is available I'd suggest using that instead.

**Comment by MarkChristianHarrison** [comment]
Thanks for the info. At the moment the using a grid is not really an option but I'll try the parameters you suggest for highly repetitive genomes.

**Comment by skoren** [comment]
You'll have to restart from scratch if you do change those parameters unfortunately. As a first cut, you can try: ```corMhapFilterThreshold=0.0000000002 corMhapOptions="--threshold 0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50" mhapMemory=60g mhapBlockSize=500```
