### ISSUE TITLE
Too many small indels (<5bp) in final assembly 

### ISSUE THREAD

**Issue by davidvilanova** [marbl/canu#860]
Hi,
I´m using latest Canu to assemble a single bacterial genome (long reads were produced with nanopore). I end up recovering the chromosome with a 94% identity to the reference genome. Also i recover 6 plasmids.

It looks pretty good but have noticed i still get too many indels (<5bp). I was wondering if i can tune canu to be more sensitive and remove small indels ? larger indels >5bp are pretty good so it really concerns small indels. 

My Canu assembly is 2.4Mb long and contains 11862 short indels (<5bp). My reference genome is ~2.4Mb. GC content is 32.2%.

Thanks for advice,

**Comment by davidvilanova** [comment]
Thanks for the update!!! 
I have run an hybrid assembly using miseq data and indels(<5bp) went down to 469 which is a nice reduction !!!!

Just to let you know that i have also tested racon twice on the CANU assembly and reads went down to 6400 so half of initial indels (<5bp) so i guess there is still space to improve canu in this area.

Definitely the hybrid assembly is much better !!!!
Thanks,

**Comment by skoren** [comment]
Right, the downside of the illumina-polishing or hybrid assembly is that repeats will still be incorrect. You still want to run long-read polishing with nanopolish to get the best possible assembly (you probably want to run nanopolish then illumina polishing). Hopefully, nanopore can improve their data quality further so the short-read data isn't needed.
