### ISSUE TITLE
Correction step description

### ISSUE THREAD

**Issue by migrau** [marbl/canu#863]
I would like to know how the correction is done. It uses consensus, overlaps? There is a fastq file available for the corrected reads?
Thanks!

**Comment by skoren** [comment]
The correction step is described in the Canu manuscript in detail but, essentially, yes the raw reads get a new consensus sequence and are trimmed to well-supported regions. There is a fasta file output for the corrected reads.

**Comment by migrau** [comment]
Thanks, skoren. In case we have a mixed sample containing two potential individuals (from the same organism, so they could be very similar), can the correction itself be detrimental? The diversity between the individuals can disappear. Any canu parameter to deal with?
