### ISSUE TITLE
bogart options recommended in FAQ

### ISSUE THREAD

**Issue by peritob** [marbl/canu#864]
Hello and thanks in advance for your help,

I have looked for bogart options here: 
http://canu.readthedocs.io/en/latest/commands/bogart.html

but don't see the flags in the suggested FAQ for diploid assembly.

```corOutCoverage=200 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50"```

Can you please point me to these or advise me on what they refer to?

**Comment by skoren** [comment]
The command line help doesn't list these options, it should be updated. The dg/db are standard deviations to build the best overlap graph and dr is used for repeat breaking. The defaults are 6/6/3 so reducing the standard deviations means use a lower error rate to separate haplotypes more. The breaking options ca/cp state how different the alternate path has to be to be split. The 500/50 means if the alternate overlap to one used in the assembly is 500bp shorter or at least 50% shorter then the unitig won't be split. These are heuristic based on our experience with some genome assemblies.

**Comment by peritob** [comment]
Thanks for your very prompt and helpful response.

**Comment by skoren** [comment]
The defaults for ca/cp 2100/200. We will add the info to the binary output.
