### ISSUE TITLE
ovStoreSorter Error: Write failure on ovFile::writeBuffer: Cannot allocate memory

### ISSUE THREAD

**Issue by santiagosnchez** [marbl/canu#866]
Hi Brian,

This is the error I'm getting with `ovStoreSorter`. As I said, it seems memory-related.

Thanks.

```
  loading    5816057 overlaps from './Mag.ovlStore.BUILDING/bucket0033/slice0010'.

Sorting.

Writing sorted overlaps.
safeWrite()-- Write failure on ovFile::writeBuffer: Cannot allocate memory
safeWrite()-- Wanted to write 262080 objects (size=4), wrote 15360.
ovStoreSorter: AS_UTL/AS_UTL_fileIO.C:107: void AS_UTL_safeWrite(FILE*, const void*, const char*, size_t, size_t): Assertion `errno == 0' failed.
/var/spool/slurmd/job6889966/slurm_script: line 76: 147933 Killed                  $bin/ovStoreSorter -O ./Mag.ovlStore.BUILDING -G ./Mag.gkpStore -C ./Mag.ovlStore.config -s $jobid -M 7
slurmstepd: error: Detected 1 oom-kill event(s) in step 6889966.batch cgroup.
```

**Comment by santiagosnchez** [comment]
It seems to be related to #125 
I'm trying with:

    ovsMemory=6

Given that the original script is going for 7g.

**Comment by skoren** [comment]
Setting ovsMemory won't change the request from the grid, I think there is more overhead than expected so it overflows  the request and is killed by the scheduler. Setting```gridOptionsovs="--mem=10g``` should fix it. Canu will re-lauch only the failed jobs and should complete. If you change ovsMemory=6 you'd need to remove the ovlStore.BUILDING folder.

We test that Canu uses the memory it's supposed to but we recently found our slurm cluster implicitly doubles allocation for these single-threaded jobs so it's possible we didn't account for overhead correctly in these cases.

**Comment by brianwalenz** [comment]
Do you have a `*.ovlStore.config.txt` file?  It's not terribly exciting, but does report the requested and actual sizes:
```
Configured for:
  numBuckets        3
  numSlices         3
  sortMemory        7 GB (6.189 GB)
```
If not, no worries.  This file only appears in most recent versions.

**Comment by santiagosnchez** [comment]
Sorry it should have been version:
`Canu snapshot v1.7 +104 changes (r8796 65abccb7bdb5604ccdb1815d1e6e8ebc0d386ebd)`
