### ISSUE TITLE
Read trimming during correction step

### ISSUE THREAD

**Issue by abayega** [marbl/canu#867]
Hi, I was so excited to use Canu to correct ONT cDNA reads. However, it seems Canu also trims the corrected reads. Is this true? If true is it possible to turn off this behaviour and how to? 

Basically the trimmed part includes my adapters which enable poly(A) site identification and strand orientation. 

It would be best to leave uncorrected part of the read intact.

Thanks you,

**Comment by abayega** [comment]
Hi Brian, thank you so much. I really should have read that part, it's going to cost me 2 weeks of re-correcting these reads... And since these reads have uneven coverage (RNA-Seq reads) I guess setting corOutCoverage=10000 is wise.

**Comment by brianwalenz** [comment]
If you've still got the overlap data (in `correction/*ovlStore`) you can restart without recomputing overlaps.  Unfortunately, this is deleted by default once corrections are done.

Add options 'saveReadCorrections=true' and 'saveOverlaps=true' to save most/all of the intermediate data.  (TIP: If your assembly is computing overlaps right now, you can add these options to `~/.canu` (one per line) and canu will pick them up the next time it restarts, when overlaps are computed.)

There is logic in Canu that will ensure that every read is either corrected, or used as evidence for correcting some other read.  In most cases, this is enough to prevent loss of 'real' data.  Setting corOutCoverage to MAX will, of course, correct every single read, but that's also pretty time consuming.

In the `*.report`, look for the 'rescued' reads (this is from drosophila):
```
[CORRECTION/LAYOUT]
--                             original      original
--                            raw reads     raw reads
--   category                w/overlaps  w/o/overlaps
--   -------------------- ------------- -------------
--   Number of Reads            1302897        129986
--   Number of Bases        13218563480     148781881
--   Coverage                    82.616         0.930
--   Median                        8903             0
--   Mean                         10145          1144
--   N50                          14272          8291
--   Minimum                       1000             0
--   Maximum                      44766         32545
--   
--                                        --------corrected---------  ----------rescued----------
--                             evidence                     expected                     expected
--   category                     reads            raw     corrected            raw     corrected
--   -------------------- -------------  ------------- -------------  ------------- -------------
--   Number of Reads            1055784         347815        347815         116387        116387
--   Number of Bases        11445143376     6507444183    6400005073      726361296     580893493
--   Coverage                    71.532         40.672        40.000          4.540         3.631
--   Median                        9725          18085         17711           5184          4039
--   Mean                         10840          18709         18400           6240          4991
--   N50                          14530          19148         18769           8856          7366
--   Minimum                       1000          13034         13033           1002          1001
--   Maximum                      44766          41579         41566          36586         13033
--   
--                        --------uncorrected--------
--                                           expected
--   category                       raw     corrected
--   -------------------- ------------- -------------
--   Number of Reads             968681        968681
--   Number of Bases         6133539882    4569475390
--   Coverage                    38.335        28.559
--   Median                        5854          4293
--   Mean                          6331          4717
--   N50                           9380          8770
--   Minimum                          0             0
--   Maximum                      44766         43749
```

**Comment by skoren** [comment]
Idle, answered.
