### ISSUE TITLE
Trying to assemble using grid with SLURM

### ISSUE THREAD

**Issue by AsclepiusDoc** [marbl/canu#869]
Hello,

I am trying to start a canu run on a HPC grid that runs SLURM and I can't seem to get it to work. I was hoping to get some advice. 

canu command: `./canu -p duster_lib_y0 -d $DUSTER_LIB_Y0_ANALYSIS/canu_assembly useGrid=true gridOptions="--mem-per-cpu=4g" correctedErrorRate=0.16 genomeSize=17g  -nanopore-raw $DUSTER_LIB_Y0_ANALYSIS/fastq_porechop/porechop_trimmed_output.fastq
`

canu version: Canu snapshot v1.7 +9 changes (r8701 7717c7f1e9db22baecac95a7a769b4ceead9c2ab)

Also, I am submitting the command in a batch script below are the options I set.

```
#!/bin/bash
#SBATCH --job-name=duster_canu
#SBATCH -p RM
#SBATCH -N 4
#SBATCH -n 28
#SBATCH -t 48:00:00
```
I have also attached the .log file and error output that was generated.

Thank you for your time.

Kind Regards,
Alex

[meryl.jobSubmit-01.txt](https://github.com/marbl/canu/files/1908174/meryl.jobSubmit-01.txt)
[slurm-2788211.txt](https://github.com/marbl/canu/files/1908175/slurm-2788211.txt)

**Comment by skoren** [comment]
First, based on the number of reads you have and genome size you specified, you likely have <1x coverage so it's not going to assemble.

As for the grid, you shouldn't submit the canu script to the grid, it will submit itself. Just launch on the head node. Also, don't specify the memory in gridOptions, that will be taken care of by Canu for you. These should instead be general options you want to always set, based on your submit script something like ```gridOptions="--time=96:00:00 --partition=RM"```.

Now for the error, your scheduler claims you can never request more than 4.4G/core but there are much larger nodes in the cluster:
```
-- Found   2 hosts with 288 cores and 1209 GB memory under Slurm control.
-- Found 768 hosts with  28 cores and  125 GB memory under Slurm control.
-- Found  42 hosts with  32 cores and  125 GB memory under Slurm control.
-- Found   8 hosts with  64 cores and 3023 GB memory under Slurm control.
-- Found  34 hosts with  80 cores and 3023 GB memory under Slurm control.
-- Found   2 hosts with 352 cores and 1209 GB memory under Slurm control.
```

This requirement isn't a standard slurm config but specific to your site and I must say doesn't make much sense. What if a process requires 10gb of ram but 1 core, would you have to pretend it needs 3 cores instead? Is there a partition on your grid that does not have this limitation? 

Canu requests memory and cores independently so if not you're going to have to set your limits explicitly to satisfy these requirements. Looking at the config, most jobs are OK. Look at this preamble for any jobs requesting more than 4gb and modify them:
```
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl    256 GB   32 CPUs  (k-mer counting)
-- Grid:  cormhap   48 GB   14 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    24 GB    7 CPUs  (overlap detection)
-- Grid:  utgovl    24 GB    7 CPUs  (overlap detection)
-- Grid:  ovb        3 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       32 GB    1 CPU   (overlap store sorting)
-- Grid:  red       13 GB    4 CPUs  (read error detection)
-- Grid:  oea        8 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat     1024 GB   64 CPUs  (contig construction)
-- Grid:  gfa       64 GB   64 CPUs  (GFA alignment and processing)
```
These might be enough: ```merylMemory=100 merylThreads=28 batMemory=100 batThreads=28 oeaMemory=64 redMemory=64 redThreads=16 gridOptionsoea="--mem-per-core=4g --cpus-per-task=16" gridOptionsovs="--mem-per-core=4g --cpus-per-task=8"```.  The last two are single-core jobs that use 32-64gb. Hopefully your grid will be ok with a request like ```--mem-per-core=32g --mem-per-core=4g```.

**Comment by AsclepiusDoc** [comment]
Hello Sergey,

Thank you for your advice. I have made the modifications and it seems that I still run into errors. Also, I would like to ask an additional question what would be the best way to approach running canu when the computing system I work with doesn't allow array jobs?

Kind Regards,

Alex Lim

**Comment by skoren** [comment]
Can you be more specific about the error?

Running without array jobs would be difficult, you could run with useGrid=remote and whenever it gives you a grid command submit each job in that array by hand and when all of them finish, resume Canu. You could also modify the code to do that but I'm not sure your grid would support holding on several hundred jobs at once.

**Comment by skoren** [comment]
I've fixed support for 1-job arrays so that might work in your case, though it depends on how the admins turned off job arrays in your case. Don't update in the middle of an assembly though.

Try setting ```gridEngineArrayMaxJobs``` to 1 and see if it runs. There may be issues with shell command limits if you end up with >1000 jobs to hold on. Open a new issue if you hit an error with that option and the latest code.
