### ISSUE TITLE
Can Canu assemble circular genomes?

### ISSUE THREAD

**Issue by BertVanm** [marbl/canu#87]
I can't seem to find this anywhere in the documentation but is Canu capable of assembling (short) circular genomes? If so what parameters can I use to specify this?

**Comment by skoren** [comment]
There are no special parameters for circular genomes, Canu doesn't do anything different for them. It will output a linear contig which will be arbitrarily broken somewhere along the circle. If it is a very short genome (e.g. lambda or a phage) it will help to randomly downsample your coverage to no more than 200X before assembly.

**Comment by aphillippy** [comment]
For circular genomes, the resulting Canu contig will usually go around the circle slight more than once, and the ends will need to be trimmed back using a tool like Circulator https://github.com/sanger-pathogens/circlator

**Comment by BertVanm** [comment]
Thank you for your answers!
