### ISSUE TITLE
SGE grid submission stuck in "queued"

### ISSUE THREAD

**Issue by mtgassr** [marbl/canu#871]
I'm running canu v1.7 remotely and letting it submit to our SGE grid:
```
canu -assemble -p bm -d bm-errate-0.16 \
  genomeSize=95m correctedErrorRate=0.16 \
  gridEngineThreadsOption="-pe thread THREADS" \
  gridEngineMemoryOption="-l mem_free=MEMORY" \
  gridOptions="-r y -V -P lab" -nanopore-corrected bm.trimmedReads.fasta.gz
```
```
-- CONFIGURE CANU

-- Detected Java(TM) Runtime Environment '1.8.0_144' (from 'java').
-- Detected gnuplot version '5.0 patchlevel 6' (from 'gnuplot') and image format 'png'.
-- Detected 4 CPUs and 16 gigabytes of memory.
-- Detected Sun Grid Engine in '/usr/local/packages/sge-root/igs'.
-- User supplied Grid Engine environment '-pe thread THREADS'.
-- User supplied Grid Engine consumable '-l mem_free=MEMORY'.

-- Found   1 host  with 128 cores and  503 GB memory under Sun Grid Engine control.
-- Found   1 host  with  56 cores and  220 GB memory under Sun Grid Engine control.
-- Found   1 host  with 120 cores and  503 GB memory under Sun Grid Engine control.
-- Found  15 hosts with  56 cores and  251 GB memory under Sun Grid Engine control.
-- Found   1 host  with  64 cores and 1007 GB memory under Sun Grid Engine control.
-- Found  11 hosts with  48 cores and  251 GB memory under Sun Grid Engine control.
-- Found   1 host  with  64 cores and  503 GB memory under Sun Grid Engine control.
-- Found   1 host  with  32 cores and  125 GB memory under Sun Grid Engine control.
-- Found   1 host  with  16 cores and   62 GB memory under Sun Grid Engine control.
-- Found  48 hosts with  48 cores and  125 GB memory under Sun Grid Engine control.
-- Found   1 host  with  16 cores and  252 GB memory under Sun Grid Engine control.

--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm

-- Grid:  meryl      8 GB    4 CPUs  (k-mer counting)
-- Grid:  cormhap   13 GB    8 CPUs  (overlap detection with mhap)
-- Grid:  obtovl     8 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl     8 GB    8 CPUs  (overlap detection)
-- Grid:  ovb        2 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs        8 GB    1 CPU   (overlap store sorting)
-- Grid:  red        8 GB    4 CPUs  (read error detection)
-- Grid:  oea        4 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat       64 GB    8 CPUs  (contig construction)
-- Grid:  gfa        8 GB    8 CPUs  (GFA alignment and processing)

-- Found Nanopore corrected reads in the input files.

-- Generating assembly 'bm' in '$workingdirectory/bm-errate-0.16'

-- Parameters:

--  genomeSize        95000000

--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1600 ( 16.00%)
--    utgOvlErrorRate 0.1600 ( 16.00%)

--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1600 ( 16.00%)
--    utgErrorRate    0.1600 ( 16.00%)
--    cnsErrorRate    0.1600 ( 16.00%)

-- Starting command on Mon Apr 16 16:29:02 2018 with 1661.688 GB free disk space

    cd $workingdirectory/bm-errate-0.16
    qsub \
      -l mem_free=8g \
      -pe thread 1 \
      -r y \
      -V \
      -P lab  \
      -cwd \
      -N 'canu_bm' \
      -j y \
      -o canu-scripts/canu.01.out canu-scripts/canu.01.sh
Your job 5591098 ("canu_bm") has been submitted
```
I confirm its submission with
```
$ qstat
job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID 
5591098 0.47966 canu_bm    mtgassr      qw    04/16/2018 16:29:02                                    1 
```
**## ISSUE: canu job will now stay in "queued" status indefinitely.** It is not from lack of resources or open resources. While queued, I can sub other programs that request more threads and memory, and they'll jump right into "running." So I believe it may be an issue with how canu is communicating with the grid.

There is no canu-scripts/canu.01.out
Here is canu-scripts/canu.01.sh:
<img width="724" alt="canu 01 sh" src="https://user-images.githubusercontent.com/38252752/38835790-205832f8-419a-11e8-8333-2fcb675da9ad.png">

I appreciate any suggestions-if there are any-before I begin to tackle this issue from the grid side. 

Thank you for your time and help.

Cheers,
Mark

**Comment by mtgassr** [comment]
Thanks for , Brian.

Here's output of qstat -j

'''
job_number:                 5591098
exec_file:                  job_scripts/5591098
submission_time:            Fri Apr 13 18:03:18 2018
owner:                      mtgassr
group:                      lab
gid:                        1000
sge_o_home:                 /home/mtgassr
sge_o_log_name:             mtgassr
sge_o_path:                 /usr/local/packages/emacs-23.4/bin:/home/ksieber/perl5/lib/perl5/:/local/projects/ergatis/package-driley/lib/perl5/x86_64-linux-thread-multi/:/usr/local/packages/sge-root/bin/lx24-amd64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/jmattick/edirect:/home/jmattick/bin:/home/jmattick/mirdeep2_0_0_7:/home/jmattick/mirdeep2_0_0_7/essentials/ViennaRNA-1.8.4/install_dir/bin
sge_o_shell:                /bin/bash
sge_o_workdir:              $workingdirectory/bm-oxford
sge_o_host:                 thanos
account:                    sge
cwd:                        $workingdirectory/bm-oxford
merge:                      y
hard resource_list:         mem_free=8g
mail_list:                 mtgassr
notify:                     FALSE
job_name:                   canu_bm
stdout_path_list:           NONE:NONE:canu-scripts/canu.01.out
jobshare:                   0
hard_queue_list:            all.q
env_list:                   
script_file:                canu-scripts/canu.01.sh
parallel environment:  thread range: 1
project:                    lab
scheduling info:            queue instance "sequencing.q@grid-1-5-7" dropped because it is disabled
                            queue instance "threaded.q@grid-1-5-7" dropped because it is disabled
                            queue instance "test.q@grid-1-5-7" dropped because it is disabled
                            queue instance "all.q@grid-1-5-7" dropped because it is disabled
                            queue instance "workflow.q@grid-1-5-7" dropped because it is disabled
                            cannot run in queue "sequencing.q" because it is not contained in its hard queue list (-q)
                            cannot run in queue "interactive.q" because it is not contained in its hard queue list (-q)
                            cannot run in queue "threaded.q" because it is not contained in its hard queue list (-q)
                            cannot run in queue "test.q" because it is not contained in its hard queue list (-q)
                            cannot run in queue "submit.q" because it is not contained in its hard queue list (-q)
                            cannot run in queue "all.q" because PE "thread" is not in pe list
                            cannot run in queue "workflow.q" because it is not contained in its hard queue list (-q)
                            does not request 'forced' resource "rhel5" of host magneto
                            does not request 'forced' resource "rhel5" of host juggernaut
                            cannot run in PE "thread" because it only offers 0 slots

'''





If I run the qsub manually from the directory 
'''
cd $workingdirectory/bm-errate-0.16
    qsub \
      -l mem_free=8g \
      -pe thread 1 \
      -r y \
      -V \
      -P lab  \
      -cwd \
      -N 'canu_bm' \
      -j y \
      -o canu-scripts/canu.01.out canu-scripts/canu.01.sh
'''

It also remains in queued indefinitely and same scheduling info returns from qstat -j above. I do not receive that information from other submitted jobs.

Mark

**Comment by brianwalenz** [comment]
How do you run other threaded jobs?  I suspect you need to add '-q threaded.q' based on this error:
```
cannot run in queue "threaded.q" because it is not contained in its hard queue list (-q)
```

**Comment by mtgassr** [comment]
Adding "-q threaded.q" to gridOptions worked! I've never needed any hard queue (-q) options for threaded jobs before so will investigate its requirement here, but thank you for your time and help.

Cheers.
