### ISSUE TITLE
Parameters recommendation for haploid > 100X ?

### ISSUE THREAD

**Issue by ptranvan** [marbl/canu#878]
Dear Canu developers, 

My question is on the title: I have 120X of PacBio Sequel data for a haploid specie (pool of differents individual).

Do you have any parameters to recommend for the assembly ? 

Thanks for your support

**Comment by skoren** [comment]
Do you expect the whole species is clonal or are there re-arrangements between the individuals? 

If the former, default parameters should work well. If the latter (variation between individuals) you probably want to use the heterozygous parameters from the FAQ. Something like ```corMhapSensitivity=normal corOutCoverage=100 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50"```. You essentially then have multiple haplotypes corresponding to the different individuals and so, depending on frequency of variants in the population and variant type, you may end up with a larger than expected assembly where the haplotypes are separated out.

**Comment by ptranvan** [comment]
I expect it to be clonal (or very few SNPs among individuals).

Thanks for the recommendation. For some reasons, I have to run separately the correction, trimming and assemby steps.

Do I need to set those parameters for all steps ?

**Comment by skoren** [comment]
You shouldn't have to run the steps separately but if you do, make sure you're using Canu 1.7 not 1.6. 1.6 had a bug when run as individual steps. Not all the parameters are used by all steps but all steps will accept them so you can just run all steps with the same command for consistency. However, if the genomes are as homozygous as you say, the defaults would work so you don't need to set any additional parameters.
