### ISSUE TITLE
Corrected reads as fastq

### ISSUE THREAD

**Issue by treitlis** [marbl/canu#879]
Hello,

I would like to ask if there would be any possibility to get the corrected reads in fastq format. I have a single cell genome, and I have a lot of Illumina data for it but just very little nanopore data for it (assembly size of the single cell metagenome is around 240 Mbp and I have around 2.8 Gbp of nanopore data) . And I would like to try to use the corrected reads as input in SPAdes assembler to see if it would improve the assembly. I know spades can take the raw nanopore data, but from my experience it maps very low amount of it to the assembly and thus I am thinking that feeding in the corrected reads would increase the ability to map even more reads, and scaffold better the data.

Also SPAdes can take as input fasta file for nanopore, but... I would like to see if there will be any difference if I provide him with a fastq file which has some quality scores.

Thank you in advance,
Best regards,
Sebastian

**Comment by skoren** [comment]
The latest release (canu 1.7) does compute QVs based on corrected read coverage. You can use the ```gatekeeperDumpFASTQ``` command to dump the reads. Something like:

```gatekeeperDumpFASTQ -nolibname -G <your asm folder>/*.gkpStore -fastq -o asm.correctedReads.gz``` will make a ```asm.correctedReads.fastq.gz``` file.

However, we've never checked how well these QV match the true probability of an error so I'm not sure how useful they'll be to SPAdes.
