### ISSUE TITLE
Read correction in Canu 1.7 release: falconsense crashes

### ISSUE THREAD

**Issue by manclu** [marbl/canu#881]
Hello,

I'm trying to correct some PacBio reads in Canu release v1.7 (+0 commits) r0 , but falconsense appears to be choking on some reads:

```
[...]
ALIGN to 0-18455 length 18455
read1356274 #29 location 0 to template 825-15828 length 15003 diff 0.313071
read1356274 #29 location 1 to template 825-15844 length 15019 diff 0.312737
read      29 failed to map - different
ALIGN to 0-13067 length 18455
read1128757 #30 location 0 to template 659-11927 length 11268 diff 0.250532
mapped 1128757     0-11048 to template    659- 11928 trimmed by      0-     0 TTCCAAACAA TTCCGAATAA
ALIGN to 0-15968 length 18455
read1471948 #31 location 0 to template 834-14632 length 13798 diff 0.254675
read1471948 #31 location 1 to template 834-14634 length 13800 diff 0.254638
read1471948 #31 location 2 to template 834-14635 length 13801 diff 0.254619
read1471948 #31 location 3 to template 834-14636 length 13802 diff 0.254601
mapped 1471948     0-13001 to template    834- 14633 trimmed by      0-     0 TCAACACTTA TTGA-A-T-A
ALIGN to 0-14253 length 18455
read2656254 #32 location 0 to template 862-13009 length 12147 diff 0.160698
read2656254 #32 location 1 to template 862-13010 length 12148 diff 0.160685
falconsense: overlapInCore/libedlib/edlib.C:347: void edlibAlignmentToStrings(const unsigned char*, int, int, int, int, int, const char*, const char*, char*, char*): Assertion `strlen(qry_aln_str) == alignmentLength && strlen(tgt_aln_str) == alignmentLength' failed.

Failed with 'Aborted'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::97 in _Z17AS_UTL_catchCrashiP7siginfoPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
overlapInCore/libedlib/edlib.C::347 in _Z23edlibAlignmentToStringsPKhiiiiiPKcS2_PcS3_()
correction/falconConsensus-alignTag.C::252 in (null)()
correction/falconConsensus-alignTag.C::152 in _Z20alignReadsToTemplateP11falconInputjdjb()
correction/falconConsensus.C::321 in _ZN15falconConsensus17generateConsensusEP11falconInputj()
correction/falconsense.C::160 in generateFalconConsensus()
correction/falconsense.C::377 in main()
(null)::0 in (null)()
(null)::0 in (null)()
```

example falconsense command from correctReads.sh:

```
falconsense \
  -G ../pac_M.gkpStore \
  -C ../pac_M.corStore \
  -b 255001 \
  -e 270000 \
  -r ./pac_M.readsToCorrect \
  -t 4 \
  -cc 0 \
  -cl 500 \
  -oi 0.7 \
  -ol 500 \
  -p ./results/0018.WORKING
```

Content of readsToCorrect.stats:

```
                          original      original
                         raw reads     raw reads
category                w/overlaps  w/o/overlaps
-------------------- ------------- -------------
Number of Reads            3040122         39509
Number of Bases        18434396592     112102035
Coverage                    18.434         0.112
Median                        4989          1164
Mean                          6063          2837
N50                           8939          6513
Minimum                        500             0
Maximum                      86238         57326

                                     --------corrected---------  ----------rescued----------
                          evidence                     expected                     expected
category                     reads            raw     corrected            raw     corrected
-------------------- -------------  ------------- -------------  ------------- -------------
Number of Reads            3053574        3040122       3040122              0             0
Number of Bases        18372483530    18434396592   17904258095              0             0
Coverage                    18.372         18.434        17.904          0.000         0.000
Median                        4934           4989          4821              0             0
Mean                          6016           6063          5889              0             0
N50                           8924           8939          8990              0             0
Minimum                        500            500             1              0             0
Maximum                      86238          86238         80168              0             0

                     --------uncorrected--------
                                        expected
category                       raw     corrected
-------------------- ------------- -------------
Number of Reads              39509         39509
Number of Bases          112102035             0
Coverage                     0.112         0.000
Median                        1164             0
Mean                          2837             0
N50                           6513             0
Minimum                          0             0
Maximum                      57326             0

Maximum Memory          1359640496
```

I tried using the latest falconsense version from source, but that one is not compatible with my read stores. Is there any way to complete correction without starting from scratch with the latest source version of canu?

Many thanks for your time.

**Comment by brianwalenz** [comment]
It's possible to update the data to the latest format, but it's involved and painful, and I don't see any recent changes that obviously apply to this failure.  So let's not do that.

Instead, let's just not correct this read.  It's somewhat long (18.5k) which is sad.  In the same log file with the crash (thanks for tracking that down) look for the last line saying "Processing read ... of length ..." (grep for '^Processing').  Then in file 'pac_M.readsToCorrect' remove the line with that number.  Restart and hope this isn't systematic.

I'd love to get a copy of the data causing this crash -- this read and most of the reads that overlap it.  I need to do some coding first, then move the changes back to the 1.7 code.  I should have this done in the next day or so.  Before you resume your assembly, make a copy of the current data in the gkpStore:
```
mkdir save.gkpStore
cd save.gkpStore
cp -p ../pac_M.gkpStore/[e-r]*
ln -s ../pac_M.gkpStore/blobs .
```
(that is, copy all files but the gigantic blobs file to a new directory).  If you're unable to share the data, no worries, just let me know so I don't waste time moving the changes back to 1.7.

**Comment by manclu** [comment]
Thank you for your advice. I will have a look at the offending reads tomorrow (it's 7pm where I am, and I can't access my work just now). I'm sure I can share some data (i.e. the reads in question), but I'd rather not upload entire read stores. I'll update you tomorrow. Many thanks!

**Comment by manclu** [comment]
OK, it looks like this same error happens multiple times in my dataset. Virtually all of my 206 correction jobs are crashing at some point (some sooner, some later). 

I've extracted three offending reads and all the evidence reads that I could get from the .err file. I don't know how to dump all overlapping reads at once - please let me know if you need more input.

For now, I will remove offending reads from the file as you suggest and see how far I get. Thank you for looking into this.
[falconsense_crash.tar.gz](https://github.com/marbl/canu/files/1950728/falconsense_crash.tar.gz)

**Comment by skoren** [comment]
Thanks for sending the data. I see from the read names these are CCS data. Were they already run through PacBio's circular consensus? In that case you probably want to treat them as corrected reads not raw data (```-pacbio-corrected```). That might help you work around the issue as well.

**Comment by manclu** [comment]
Yes, these are CCS reads. The reason why I'm running them through the correction module is that I'm having trouble with heterozygosity (pooled DNA samples) when doing trimming+assembly only, and I wanted to see whether correction with `correctedErrorRate=0.15` will smash haplotypes together and make a difference to the assembly.

**Comment by skoren** [comment]
Correction tries to avoid smashing data by selecting only the best subset of reads for consensus so it's unlikely to help. You could try the FAQ parameters for heterozygous genomes (either separating or smashing, your choice) for the trimming+assembly step instead.

**Comment by skoren** [comment]
It looks from your reads that you also have Ns in the sequences. I guess CCS reads can have Ns in them while the raw reads do not? I expect you would be able to work around by either replacing Ns with another character or excluding reads with Ns in them from your assembly.

**Comment by skoren** [comment]
Fixed, you can try the latest from GitHub if you want to keep the reads with N bases.
