### ISSUE TITLE
Resource allocation for large genome

### ISSUE THREAD

**Issue by zrlewis** [marbl/canu#886]
Hello,

I am working on assembling a 3.3 Gb invertebrate genome using about 50X PacBio coverage (160 Gb reads). First, I wanted to say that I really appreciate how well-documented `Canu` is. It has been extremely helpful for working on this relatively large assembly.

I am looking for advice on allocating resources. I am working in a SLURM cluster and using `Canu 1.7`. There are several partitions available to me, including these:

```
sinfo -p bigmem --format="%c %F %b %l %m" | column -t

CPUS  NODES(A/I/O/T)  ACTIVE_FEATURES                        TIMELIMIT   MEMORY
32    2/0/0/2         haswell,v3,sse4_2,avx,avx2,E7-4809_v3  7-00:00:00  1543168
32    7/0/0/7         bulldozer,sse4_2,avx,opteron-6276      7-00:00:00  510976

sinfo -p general --format="%c %F %b %l %m" | column -t

CPUS  NODES(A/I/O/T)  ACTIVE_FEATURES                        TIMELIMIT    MEMORY
16    32/0/0/32       sandybridge,sse4_2,avx,E5-2670         30-00:00:00  123904
20    98/0/1/99       haswell,v3,sse4_2,avx,avx2,E5-2660_v3  30-00:00:00  123904
8     1/35/0/36       westmere,sse4_2,E5-620                 30-00:00:00  44032
```

When I try to run `Canu` it seems to recognize/attempt to utilize resources across the entire cluster, not just the partition that I specify in `gridOptions`. 

```
canu \
    -p physalia -d physalia_assembly_2 \
    genomeSize=3.3g \
    -pacbio-raw $READS/Physalia_concatenated_reads.fasta \
    correctedErrorRate=0.065 corMhapSensitivity=normal \
    gridOptions="--partition general --cpus-per-task=20"

```
```
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_121' (from '/ysm-gpfs/apps/software/Java/1.8.0_121/bin/java').
-- Detected gnuplot version '4.6 patchlevel 2' (from 'gnuplot') and image format 'png'.
-- Detected 32 CPUs and 1512 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /usr/bin/sinfo.
-- Detected Slurm with 'MaxArraySize' limited to 10000 jobs.
--
-- Found 120 hosts with  20 cores and  121 GB memory under Slurm control.
-- Found  21 hosts with   8 cores and  121 GB memory under Slurm control.
-- Found  59 hosts with  16 cores and  121 GB memory under Slurm control.
-- Found   2 hosts with  32 cores and 1507 GB memory under Slurm control.
-- Found   1 host  with   8 cores and   58 GB memory under Slurm control.
-- Found  15 hosts with  32 cores and  499 GB memory under Slurm control.
-- Found  34 hosts with  28 cores and  246 GB memory under Slurm control.
-- Found 124 hosts with   8 cores and   43 GB memory under Slurm control.


```

The problem seems to be that `Canu` detects 32 available cpus-per-task and request it even though I specified 20 and only 20 CPUs/node are available on the `general` partition. Both values get passed to the scheduler, resulting in an error.

Meryl job submission output:
```
#!/bin/sh

sbatch \
  --mem-per-cpu=8g --cpus-per-task=32 --partition general --cpus-per-task=20 -o meryl.%A_%a.out \
  -D `pwd` -J "meryl_physalia" \
  -a 1-1 \
  ./meryl.sh 0 \
> ./meryl.jobSubmit-01.out 2>&1
```

I didn't try to troubleshoot this too much and instead decided to use the `bigmem` partition, that has 32 available CPUs/node. 

```
canu \
    -p physalia -d physalia_assembly_4 \
    genomeSize=3.3g \
    -pacbio-raw $READS/Physalia_concatenated_reads.fasta \
    correctedErrorRate=0.065 corMhapSensitivity=normal \
    gridOptions="--partition bigmem"
```
```

--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl    256 GB   32 CPUs  (k-mer counting)
-- Grid:  cormhap   21 GB    4 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    24 GB    4 CPUs  (overlap detection)
-- Grid:  utgovl    24 GB    4 CPUs  (overlap detection)
-- Grid:  ovb        4 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       32 GB    1 CPU   (overlap store sorting)
-- Grid:  red       16 GB    4 CPUs  (read error detection)
-- Grid:  oea        8 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      512 GB   32 CPUs  (contig construction)
-- Grid:  gfa       32 GB   32 CPUs  (GFA alignment and processing)
```

Everything seems to run fine, with the exception of one memory-limit failure during the beginning of correction. I restarted `canu` and it has moved on to `cormhap`. Overlapping has been running for several days now. I'm starting to get concerned that overlapping will take too long on this partition, given the small number of nodes available on the partition. Overlapping can be distributed across nodes, correct? 

I am wondering if it makes more sense to run `meryl` and `bat` on the large memory/low node partition, while moving intervening steps to the partition with more available nodes. Would I see any improvement in using this approach? What would be the best way of doing this? 

Should I also consider adjusting `corMhapSensitivity` so that I can make it through overlapping in a reasonable amount of time? I don't have any sense of repeat structure of this genome, or heterozygosity, though both could potentially be high.

Thank you in advance for any suggestions! Zack

**Comment by skoren** [comment]
Yes, Canu queries the full grid not a specific partition. It's not really necessary to use more than 200gb for bat/meryl so I'd just limit their memory so they fit on the general partition rather than using bigmem. Just add ```batMemory=100 batThreads=20 merylMemory=100 merylThreads=20```. Don't specify the ```--cpus-per-task=20``` request in gridOptions, those will be auto-set for each job, for example the mhap jobs will only use 4 cores and if you leave in the 20 core request, you're under-utilizing your system.

As for mhap sensitivity/options, it will auto set the parameter if you don't provide it depending on your coverage. Typically, >60x is ok to run with sensitivity low so if you have more than that, you can remove your corMhapSensitivity parameter and let it auto-set to low.

**Comment by zrlewis** [comment]
@skoren Thank you for your prompt response and clarifications! I will try restarting my assembly using those options and let you know if I run into any issues.

**Comment by skoren** [comment]
Idle and resolved, open a new issue if you have other parameter questions.
