### ISSUE TITLE
Canu manually

### ISSUE THREAD

**Issue by mictadlo** [marbl/canu#887]
Hi, 
Did anyone successfully run all Canu steps manually parallel? I did it with [Falcon](https://github.com/mictadlo/FALCON-manually) and now I am looking for any advice how to do it with Canu because we have problems with our HPC environment?

Thank you in advance,

Michal

**Comment by skoren** [comment]
Running with useGrid=remote is probably what you want. It will print the command to submit to the grid and you can edit it as necessary for your HPC environment and then run it, followed by the original Canu command when it completes.
