### ISSUE TITLE
Overlap jobs failed, job trimming/1-overlapper/001/000057.ovb FAILED

### ISSUE THREAD

**Issue by psur9757** [marbl/canu#888]
Error when running overlap jobs. 

> BEGIN TRIMMING
> 
> Overlap jobs failed, tried 2 times, giving up.
> job trimming/1-overlapper/001/000057.ovb FAILED.
> 
> ABORT:
> ABORT: Canu 1.7
> ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
> ABORT: Try restarting. If that doesn't work, ask for help.
> ABORT:

I tried `sh overlap.sh 000057` but it was aborted with the following error.

> Running job 57 based on command line options.
> 
> STRING_NUM_BITS 31
> OFFSET_BITS 31
> STRING_NUM_MASK 2147483647
> OFFSET_MASK 2147483647
> MAX_STRING_NUM 2147483647
> 
> Hash_Mask_Bits 23
> Max_Hash_Strings 12180
> Max_Hash_Data_Len 170639703
> Max_Hash_Load 0.750000
> Kmer Length 22
> Min Overlap Length 500
> Max Error Rate 0.150000
> Min Kmer Matches 0
> 
> Num_PThreads 4
> 
> HASH_TABLE_SIZE 8388608
> sizeof(Hash_Bucket_t) 216
> hash table size: 1728 MB
> 
> terminate called after throwing an instance of 'std::bad_alloc'
> what(): std::bad_alloc
> 
> Failed with 'Aborted'; backtrace (libbacktrace):
> AS_UTL/AS_UTL_stackTrace.C::97 in _Z17AS_UTL_catchCrashiP7siginfoPv()
> (null)::0 in (null)()
> (null)::0 in (null)()
> (null)::0 in (null)()
> ../../gcc-4.8.2/libstdc++-v3/libsupc++/vterminate.cc::95 in _ZN9__gnu_cxx27__verbose_terminate_handlerEv()
> ../../gcc-4.8.2/libstdc++-v3/libsupc++/eh_terminate.cc::38 in _ZN10__cxxabiv111__terminateEPFvvE()
> ../../gcc-4.8.2/libstdc++-v3/libsupc++/eh_terminate.cc::48 in _ZSt9terminatev()
> ../../gcc-4.8.2/libstdc++-v3/libsupc++/eh_throw.cc::84 in __cxa_throw()
> ../../gcc-4.8.2/libstdc++-v3/libsupc++/new_op.cc::56 in _Znwm()
> ../../gcc-4.8.2/libstdc++-v3/libsupc++/new_opv.cc::32 in _Znam()
> overlapInCore/overlapInCore.C::527 in main()
> (null)::0 in (null)()
> (null)::0 in (null)()
> overlap.sh: line 794: 44317 Aborted (core dumped) $bin/overlapInCore -G -t 4 -k 22 -k ../0-mercounts/OSR_512_canu2.ms22.frequentMers.fasta --hashbits 23 --hashload 0.75 --maxerate 0.15 --minlength 500 $opt -o ./$job.ovb.WORKING -s ./$job.stats ../OSR_512_canu2.gkpStore

@brianwalenz suggested 
> It looks like you need to request more memory, or increase your memory limit. The job seems to be failing to allocate a relatively small (1.7GB) array.

Can I get further details? Thanks!

**Comment by brianwalenz** [comment]
The std::bad_alloc error is usually saying it can't allocate memory.  The last logging hints that it's trying to allocate 1.7 GB of memory and failing.

First thing to check is the bash process limits.  Check the output of `ulimit -a` for limits on 'data seg size' or 'max memory size' (google for more info, like how to relax the limits).

Next, I'd ask people locally if they've seen this before and what's going on.  Something is preventing the job from running.  I'm assuming you've got more than 2GB RAM on your machine.

**Comment by skoren** [comment]
Some more information would be helpful as well, what version of Canu? Is this running locally or on a grid, what is the Canu preamble (the resources it plans to use)?

**Comment by psur9757** [comment]
I am using Canu 1.7. and here is the script I give for it.

```
#!/bin/bash
#PBS -P RDS-FAE-OSR-RW
#PBS -N canu2
#PBS -l select=1:ncpus=8:mem=64GB
#PBS -l walltime=36:00:00
#PBS -e ./OSR_512_canu2_error.txt
#PBS -o ./OSR_512_canu2_output.txt
#PBS -M priyanka.surana@sydney.edu.au
#PBS -m abe

module load canu/1.7

canu -p OSR_512_canu2 -d /scratch/RDS-FAE-OSR-RW/OSR_512_canu2 gnuplot="/usr/local/gnuplot/5.0.0/bin/gnuplot" genomeSize=86m corOutCoverage=200 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" correctedErrorRate=0.15 gridOptions="-P RDS-FAE-OSR-RW" gridOptionsJobName=OSR512 corConcur
rency=4 gridOptionsCOR="-l walltime=36:00:00" gridOptionsCORMHAP="-l walltime=36:00:00" gridOptionsCOROVL="-l walltime=36:00:00" gridOptionsOBTOVL="-l walltime=106:00:00 -l mem=16g -l nodes=1:ppn=8" gridOptionsUTGOVL="-l walltime=106:00:00 -l mem=16g -l nodes=1:ppn=8" -pacbio-raw 
/home/psur9757/osr/raw_data/m54078_170626_*.subreads.fasta

module unload canu/1.7
```

**Comment by psur9757** [comment]
The output of `ulimit -a` is below

> core file size          (blocks, -c) 0
> data seg size           (kbytes, -d) unlimited
> scheduling priority             (-e) 0
> file size               (blocks, -f) unlimited
> pending signals                 (-i) 128256
> max locked memory       (kbytes, -l) unlimited
> max memory size         (kbytes, -m) unlimited
> open files                      (-n) 1024
> pipe size            (512 bytes, -p) 8
> POSIX message queues     (bytes, -q) 819200
> real-time priority              (-r) 0
> stack size              (kbytes, -s) unlimited
> cpu time               (seconds, -t) unlimited
> max user processes              (-u) 512
> virtual memory          (kbytes, -v) 1048576
> file locks                      (-x) unlimited

**Comment by psur9757** [comment]
I spoke to the university HPC help desk. Here are their comments.

> It's their compiled code, I can't really do anything. (Ie we don't have source code, we just install their supplied binaries. We don't have gcc-4.8.2)
> 
> You clearly are asking for enough memory (64Gb)
>  
> Of course, the input might be what's causing it.

**Comment by skoren** [comment]
Thanks for the additional info, it looks like you're explicitly requesting memory for both the ovl and utg stages (```gridOptionsOBTOVL="-l walltime=106:00:00 -l mem=16g -l nodes=1:ppn=8" gridOptionsUTGOVL="-l walltime=106:00:00 -l mem=16g -l nodes=1:ppn=8"```). However, Canu will automatically request the threads and memory itself based on your resources/genome size so it is possible your request is in conflict with what Canu is trying to use, causing the out of memory issue. You don't need to request the ovl memory from the grid explicitly, or if you do, also set ```ovlMemory=15``` in future runs.

I assume when you ran ```sh overlap.sh 000057``` you did it on a head node or without an explicit memory request? Adding memory should fix it. Run an interactive job requesting 64gb or submit a script request for 64gb just to run ```sh overlap.sh 000057``` and see if that completes.

**Comment by skoren** [comment]
Original issue appears fixed, if there are other errors in this run open a new issue.
