### ISSUE TITLE
qsub: submit error

### ISSUE THREAD

**Issue by nasreenbano** [marbl/canu#891]
i am trying to run quality filter PBS but its not working. its giving the error i.e. 
qsub: submit error (Unknown queue MSG=requested queue not found)

Its my PBS -

```
#!/bin/bash
#PBS -l walltime=48:00:00
#PBS -N fastx_trimmer
#PBS -q workq
#PBS -l select=1:ncpus=1:mpiprocs=1
#PBS -l place=scatter:excl
#PBS -V

# Go to the directory from which u have submitted the job
cd $PBS_O_WORKDIR

cd /home/nbri/Desktop/nasreen

fastq_quality_filter -Q 33 -q 30 -p 80 -i /home/nbri/Desktop/nasreen/L.fq -o /home/nbri/Desktop/nasreen/qf_L.fq
```
can any one help me please?

**Comment by skoren** [comment]
fastq_quality_filter isn't part of Canu so I'm not sure what program you're running. Either way your queue (workq) is invalid according to PBS.
