### ISSUE TITLE
Why my assembly is so fragment with awful N50

### ISSUE THREAD

**Issue by lamz138138** [marbl/canu#892]
Hi @skoren 

Thanks for all your previously help. I start a new issue since I think it don't related with previous issue.

The organism is primate (can be taken as human), and I had ~60X pacbio data (34X RSII data and 25X Sequel data), and assembled using CANU with default parameters. In the end, I got 18,360 contigs (total bases is 2,862,489,775), and N50 is 672,836.

One reason of the bad result is the genome is highly repeated. Indeed, the unitigging/*.ovlStore is 5.4T that much bigger than others, so I had follow your suggestion, running GenomeScope with k-mer of trimmed reads. Since reads length is variable, I using N50 length, that is 8000, and max_k_mer as 38000000 (the Largest mercount). I had tried read length as 12000, and max_k_mer as 1000, 3000 or 8000, it didn't changed a lot expect the total base. **In all, it seemed the genome is not too repeated.**

```
cat output/summary.txt
GenomeScope version 1.0
k = 22

property                      min               max
Heterozygosity                0.921255%         0.92303%
Genome Haploid Length         2,583,758,177 bp  2,584,264,362 bp
Genome Repeat Length          725,511,108 bp    725,653,243 bp
Genome Unique Length          1,858,247,069 bp  1,858,611,119 bp
Model Fit                     97.4355%          98.9025%
Read Error Rate               0.640239%         0.640239%

Percent Kmers Modeled (All Kmers) = 97.4355% [13, 25249527]
Percent Kmers Modeled (Full Model) = 98.9025% [13, 65]
Percent Kmers Modeled (Unique Kmers) = 99.3048% [13, 39]

Model RSSE (All Kmers) = 15544433307330.8 [13, 25249527]
Model RSSE (Full Model) = 10641772583239.3 [13, 65]
Model RSSE (Unique Model) = 6963101012904.12 [13, 39]
```

Another reason is that I get too few trimmed reads. As illustrated below, most read is longer than 8Kb, and the coverage of >8Kb reads is 21X . Also,  I didn't find any problem of the read length distribution of trimmed reads (I don't know how to import image here).

```
tail -n 20 canu.trimmedReads.stats 
Total length of sequence:	83375929344 bp
Total number of sequences:	9307119
N25 stats:			25% of total sequence length is contained in the 895835 sequences >= 17861 
bp
N50 stats:			50% of total sequence length is contained in the 2319406 sequences >= 12246 
bp
N75 stats:			75% of total sequence length is contained in the 4401104 sequences >= 8029 
bp
Total GC count:			33450006344 bp
GC %:				40.12 %
```

In all, it seemed all statistics is right, but I got a worse assembly. **What should I do to improve the genome?** 

In addition, other related information were list:
```
canu -version
Canu snapshot v1.6 +133 changes (r8545 f960f2ebf249ff07b991407e2b81981c46443315)

tail unitigging/0-mercounts/canu.ms22.histogram.info 
Found 83180479845 mers.
Found 10201085944 distinct mers.
Found 6435795131 unique mers.
Largest mercount is 37375124.

[UNITIGGING/MERS]
--
--  22-mers                                                                                           Fraction
--    Occurrences   NumMers                                                                         Unique Total
--       1-     1 6435795131 *******************************************************************--> 0.6309 0.0774
--       2-     2 851102075 ********************************************************************** 0.7143 0.0978
--       3-     4 461727022 *************************************                                  0.7442 0.1088
--       5-     7 242680752 *******************                                                    0.7695 0.1225
--       8-    11 228386219 ******************                                                     0.7892 0.1391
--      12-    16 314671972 *************************                                              0.8115 0.1679
--      17-    22 458132946 *************************************                                  0.8435 0.2272
--      23-    29 548282844 *********************************************                          0.8895 0.3431
--      30-    37 416921478 **********************************                                     0.9419 0.5159
--      38-    46 164618975 *************                                                          0.9792 0.6713
--      47-    56  36391901 **                                                                     0.9930 0.7420
--      57-    67  11869065                                                                        0.9960 0.7610
--      68-    79   6713512                                                                        0.9971 0.7693
--      80-    92   4365779                                                                        0.9977 0.7750
--      93-   106   3151008                                                                        0.9981 0.7794
--     107-   121   2396792                                                                        0.9984 0.7831
--     122-   137   1889243                                                                        0.9987 0.7863
--     138-   154   1549121                                                                        0.9988 0.7892
--     155-   172   1287889                                                                        0.9990 0.7919
--     173-   191   1053132                                                                        0.9991 0.7944
--     192-   211    864541                                                                        0.9992 0.7967
--     212-   232    727730                                                                        0.9993 0.7988
--     233-   254    616407                                                                        0.9994 0.8007
--     255-   277    527718                                                                        0.9994 0.8025
--     278-   301    458421                                                                        0.9995 0.8042
--     302-   326    398838                                                                        0.9995 0.8058
--     327-   352    351851                                                                        0.9996 0.8073
--     353-   379    315013                                                                        0.9996 0.8087
--     380-   407    280990                                                                        0.9996 0.8101
--     408-   436    250918                                                                        0.9997 0.8114
--     437-   466    225409                                                                        0.9997 0.8127
--     467-   497    200834                                                                        0.9997 0.8139
--     498-   529    180214                                                                        0.9997 0.8151
--     530-   562    162944                                                                        0.9997 0.8162
--     563-   596    146091                                                                        0.9998 0.8172
--     597-   631    133133                                                                        0.9998 0.8183
--     632-   667    121730                                                                        0.9998 0.8192
--     668-   704    111650                                                                        0.9998 0.8202
--     705-   742    102914                                                                        0.9998 0.8211
--     743-   781     95203                                                                        0.9998 0.8220
--     782-   821     88910                                                                        0.9998 0.8229
--
--    37375124 (max occurrences)
-- 76744684714 (total mers, non-unique)
--  3765290813 (distinct mers, non-unique)
--  6435795131 (unique mers)


[UNITIGGING/READS]
--
-- In gatekeeper store './canu.gkpStore':
--   Found 9307119 reads.
--   Found 83375929344 bases (27.79 times coverage).
--
--   Read length histogram (one '*' equals 13207.74 reads):
--        0    999      0 
--     1000   1999 924542 **********************************************************************
--     2000   2999 729924 *******************************************************
--     3000   3999 706642 *****************************************************
--     4000   4999 682401 ***************************************************
--     5000   5999 654350 *************************************************
--     6000   6999 620775 ***********************************************
--     7000   7999 570997 *******************************************
--     8000   8999 545394 *****************************************
--     9000   9999 532816 ****************************************
--    10000  10999 495422 *************************************
--    11000  11999 429030 ********************************
--    12000  12999 365601 ***************************
--    13000  13999 315215 ***********************
--    14000  14999 269047 ********************
--    15000  15999 230225 *****************
--    16000  16999 195031 **************
--    17000  17999 165087 ************
--    18000  18999 140345 **********
--    19000  19999 119197 *********
--    20000  20999 100792 *******
--    21000  21999  85077 ******
--    22000  22999  71435 *****
--    23000  23999  60492 ****
--    24000  24999  51193 ***
--    25000  25999  42698 ***
--    26000  26999  35314 **
--    27000  27999  29633 **
--    28000  28999  24789 *
--    29000  29999  20577 *
--    30000  30999  17317 *
--    31000  31999  14395 *
--    32000  32999  11567 
--    33000  33999   9509 
--    34000  34999   7872 
--    35000  35999   6242 
--    36000  36999   5270 
--    37000  37999   4258 
--    38000  38999   3391 
--    39000  39999   2670 
--    40000  40999   2191 
--    41000  41999   1770 
--    42000  42999   1448 
--    43000  43999   1128 
--    44000  44999    830 
--    45000  45999    728 
--    46000  46999    545 
--    47000  47999    426 
--    48000  48999    334 
--    49000  49999    262 
--    50000  50999    212 
--    51000  51999    137 
--    52000  52999    144 
--    53000  53999    103 
--    54000  54999     75 
--    55000  55999     60 
--    56000  56999     40 
--    57000  57999     34 
--    58000  58999     25 
--    59000  59999     31 
--    60000  60999     22 
--    61000  61999     10 
--    62000  62999     10 
--    63000  63999     10 
--    64000  64999      7 
--    65000  65999      1 
--    66000  66999      1 
--    67000  67999      2 
--    68000  68999      0 
--    69000  69999      0 
--    70000  70999      0 
--    71000  71999      0 
--    72000  72999      1

```

**Comment by skoren** [comment]
I see several issues:
1. Your canu version is between releases and in the midst of some large-scale changes. In particular, the corrected reads are lower quality than either 1.6 or 1.7 releases. In general, it's best to use one of the released versions for a production assembly.

2. Your genome has a relatively high heterozygosity at 1%. That's an issue because it's high enough to break the assembly but low enough that most of the genome won't get separated in Canu.

3. Your read length is OK but not that great (8k average, 12k n50). For comparison, a recent human genome where the assembly NG10 is about 10mb has an average read length >12kb and N50 >17kb.

Given that you have another assembly where the NG50 is similar (1.2 mb vs 700kbp), this may be indicating that the genome has some large repeats that are not being resolved. 

There are a couple of things you can try:
1. Try assembling the corrected reads with another assembler (like wtdbg) which is more willing to collapse variation together than Canu and see what assembly you get. Specify the corrected reads as "error-free" reads. If you get a more contiguous assembly, your lower NG50 is probably caused by worse corrected reads and/or heterozygosity.

2. Start a new assembly with adjusted parameters using Canu 1.7. Given the heterozygosity you want to keep more of your corrected reads so I'd try something like:
```corMhapSensitivity=normal corOutCoverage=100 correctedErrorRate=0.105 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" OvlMerThreshold=500```

These are basically the parameters for heterozygous genomes but with an increased error rate (can you post your ```unitigging/4-unitigger/*filterOverlaps.thr000.num000.log``` file, that will confirm if this is needed or not to compensate for the Sequel data).

**Comment by lamz138138** [comment]
Hi, thanks for the reply

1. The information of unitigging/4-unitigger/\*.001.filterOverlaps.thr0*.log is list below. So I think correctedErrorRate should be changed to 0.08. Considering this would be changed when correcting with new canu version and parameters, change it to 0.105 would be better.
 
```
ERROR RATES (12524941 samples)
-----------
mean   0.02113984 stddev 0.01027649 -> 0.08279879 fraction error =   8.279879% error
median 0.01910000 mad    0.00660000 -> 0.07781096 fraction error =   7.781096% error
```

2.  I had spend two months to finish the assembly, with canu-1.7, would it be more faster?

3. The heterozygosity of 1% is high, what level could be deemed as not high and how about the heterozygosity in human?

4. I couldn't understand "_Your genome has a relatively high heterozygosity at 1%. That's an issue because it's high enough to break the assembly but low enough that most of the genome won't get separated in Canu_",  **could you give me more detail**. My understanding is that other than repeat, the bad assembly is result from diploidy.  That is, reads from two haplotype were mis-merged, but **how this lead to discontinuity**?

**Comment by skoren** [comment]
1. Yes, 0.105 would be good, not sure the best bogart options (batOptions) but those are quick to vary once you have an assembly.

2. Probably a bit faster but the higher error rate will add runtime. So figure same time to be safe, that's why I mentioned it's good to use the tagged releases for a production asm. That was also why I suggested another option to see how much improvement you could expected from a re-run which wouldn't require you to generate a new assembly.

3. Human is on the order of 0.1-0.3%. High heterozygosity can be OK as well because you'll end up separating the genome into the haplotypes, you'll just have to de-duplicate it afterwards.

3. You can think of homozygous regions as large repeats. Canu can separate unspanned repeats in the 1.5-2% range. Below that, the correction and the unitigging will likely mix include reads from both haplotypes. So you'll have higher heterozygosity regions assembled as two contigs and lower heterozygosity regions assembled as a mixture. Then, haplotype differences look like repeat branches (where the homozygous and heterozygous regions meet) and often lead to false splitting (e.g. the assembly would be structurally correct but not in phase and canu breaks it to be conservative). So if you have human-level diversity, most of your genome is a mix and there aren't many branches (though there are still some in highly heterozygous that get split). If you have higher diversity, like 2+%, most of your genome is separated, though at half coverage, but again you don't have many of the branches.

**Comment by skoren** [comment]
1. No, I meant WTDBG: https://github.com/ruanjue/wtdbg-1.2.8

2. No you don't need to multiply. 0.1% is about 1 in 1000 bases difference. 1% would be 1 in 100 bp. Your example is far higher, that would definitely end up being split apart and I'm not sure any genomes actually have such a high divergence rate. I expect 20% would cause issues for recombination.

**Comment by lamz138138** [comment]
Thanks for the reply.

1. Can I understand high heterozygosity and repeat as follow: First, when we failed to distinguish reads came from different repeat or different haplotype (means their diversity is 1.5%-2%), we would get a corrected reads with alleles from different regions. Then, when get contain by connecting these corrected reads, there are two possibility: 1) The mix alleles in them would lead to lost of finding overlap which result in discontinuity; 2) The mix alleles link to different reads (branches) , so we had to split it which lead to discontinuity.

2. Does batoptions affect correct reads? If the answer is NO, I guess it only find high identity overlap between corrected reads, so several true overlap also missed that lead to discontinuity. For me, since the corrected reads were mixed, without re-corrected, it don't suitable to use new batoptions only.

Am I right for above point? Thanks and go to sleep at first.

**Comment by lamz138138** [comment]
Hi, thanks for your reply. I had rethought about above discussions:

1. **I don't think high heterozygosity would lead to discontinuity at the moment.** If the genome is high heterozygosity, the correct reads would contain the highest frequency alleles from different haplotype. Suppose reads_A from one haplotype, and reads_B from another haplotype, then the corrected reads (corrected_A and corrected_B) maybe have same sequence (corrected_AB) which taking the highest alleles. In this way, we would get corrected_CD (reads in this region is C, D) that link to corrected_AB. So, considering corrected_AB and corrected_CD would contain same alleles, I think we would't lost the connection. In addition, only when C and D is different (structure variation in homologous region), there would be branches for corrected_AB, and I guess there maybe a few of such different homologous region.

2. According to unitigging/4-unitigger/\*.001.filterOverlaps.thr0*.log, the error rate of my data is 8%, so several true overlap were missed as correctedErrorRate is 0.045. I should restart from unitigging/1-overlapper by change "--maxerate  0.045" in unitigging/1-overlapper/overlap.sh to 0.105. Then change bat options too. 

3. **But it still failed to figure out why my unitigging/*.ovlStore is so big.** Change 0.045 to 0.105, there would be a bigger *ovlStore. According to GenomeScope, the uniq rate is 71.9%, so I think repeat is not high. And if my above point 1 is right, the high heterozygostiy wouldn't lead to a lot of overlap.  


What's your opinion?

**Comment by skoren** [comment]
1. At 1% there will be enough branches to affect contiguity, I've seen this with other genomes in the same range.

2. You could restart with just unitigging to save time but I think you could get better read correction because you were using a checkout with a known bug in read correction which dropped contiguity on large genomes.

3. Genomescope cuts off the kmer distribution at 1000 and I bet you have some repeats it's not including above that. That's why I included ```OvlMerThreshold=500``` to hopefully prune some of those repeat sequences more.

**Comment by lamz138138** [comment]
Thanks for reply. 

1. I could accept the opinion, and it would be better if it is convenient for you to explain more. Could you take the correct_AB and correct_CD in above 1 as example to tell me how it lead to branches.

2. I had set kmer_max to 38000000 in Genomescope, is it too high and would be changed to 1000 by default? 

3. What is the default value of ovlMerThreshold (I found it was unset in document)?
