### ISSUE TITLE
Apparent bug in array job setting within trimming

### ISSUE THREAD

**Issue by peritob** [marbl/canu#893]
This is a query and perhaps a bug.

We are running canu v1.6 with 1g genome and around 60X coverage within a PBS PRO grid environment.

We have 917 buckets within trimming/genome.ovlStore.BUILDING/
The overlapping sorting stage initiates 3587 jobs. It would seem that these are meant to be split into four PBS PRO array jobs with array ids as follows: 1-1000, 1001-2000, 2001-3000, 3001-3587. There seems to be a bug where the four array jobs are created but the array ids are: 1-1000, 1-1000, 1-1000, 1-587.

**Comment by brianwalenz** [comment]
That's normal, but possibly not working with PBS.

The intent was to submit array jobs with no more than 1000 tasks.  When the job is submitted, on the command line, an offset is given so restore the original range.  So the first job should have an offset of 0, the second an offset of 1000, etc.  But, we've had no end of trouble with PBS/PBSpro, so it might not be working properly.

If there are outputs for the higher index jobs, then it's working.  The job err/out logging should also indicate what task number it is working on; if it just says 'job previously completed' or something like that, it's probably not working.

Setting gridEngineArrayMaxJobs to something mighty large will disable this 'feature'.

**Comment by peritob** [comment]
The array jobs were beginning again and redoing 1-1000 x 3. I am manually submitting to get correct jobs in the array but just thought you might like to know. 

Thanks for the advice on the setting gridEngineArrayMaxJobs to a big number to override this 'feature'.

**Comment by skoren** [comment]
I've tested this behavior works correctly in the latest code on PBS 6.1.2 so this should be fixed, at least for that PBS version.
