### ISSUE TITLE
Canu , metagenome assembly

### ISSUE THREAD

**Issue by jaube** [marbl/canu#894]
Hi,

I tried to assemble a metagenome from simplified microbial community with canu v1.7 on a slurm cluster :

`canu -p canu-contig2 -d canu-metagenome2 genomeSize=0.4m corOutCoverage=all corMhapSensitivity=high corMinCoverage=0 correctedErrorRate=0.105 redMemory=32 oeaMemory=32 batMemory=200 gridEngineThreadsOption='--cpus-per-task THREADS' maxMemory=230G maxThreads=8 -pacbio-raw 041118ERmetagenome_reads.fastq`

I followed the parameters suggested in #672 except for genome size because we are targeting a dominant archaea of interest which should be arround 0.4M.

The assembly failed at this step:

> ==> LOADING AND FILTERING OVERLAPS.
> 
> ReadInfo()-- Using 1569226 reads, no minimum read length used.
> 
> OverlapCache()-- limited to 204800MB memory (user supplied).
> 
> OverlapCache()--      11MB for read data.
> OverlapCache()--      59MB for best edges.
> OverlapCache()--     155MB for tigs.
> OverlapCache()--      41MB for tigs - read layouts.
> OverlapCache()--      59MB for tigs - error profiles.
> OverlapCache()--   51200MB for tigs - error profile overlaps.
> OverlapCache()--       0MB for other processes.
> OverlapCache()-- ---------
> OverlapCache()--   51559MB for data structures (sum of above).
> OverlapCache()-- ---------
> OverlapCache()--      29MB for overlap store structure.
> OverlapCache()--  153210MB for overlap data.
> OverlapCache()-- ---------
> OverlapCache()--  204800MB allowed.
> OverlapCache()--
> OverlapCache()-- Retain at least 14880 overlaps/read, based on 7440.22x coverage.
> OverlapCache()-- Initial guess at 6398 overlaps/read.
> OverlapCache()--
> OverlapCache()-- Not enough memory to load the minimum number of overlaps; increase -M.

Do you think that the genome size could be the reason of the memory issue ? Must I set it at 5M? Otherwise what can I modify to do my assembly ?

Thank you for any advice about this issue.

**Comment by skoren** [comment]
The genome size setting is somewhat an issue since it tells Canu how many overlaps it should expect to load and triggers the message.

If you have a larger memory machine, you could just increase batMemory and re-launch. If not, you could increase the minimum overlap length to prune some overlaps out and fit into the current memory. If you just want to get around the message and keep everything the same, increase the genome size to 5mb, that should tell Canu it only needs to retain <1000 overlaps/read and it will run.

**Comment by jaube** [comment]
Hi Sergey,
Thanks a lot for your prompt response.
I increased the genome size to 5mb and the unitigger step was completed but the job failed at the next step:

> > 
> -- BEGIN ASSEMBLY
> --
> -- Using slow alignment for consensus (iteration '2').
> -- Configured 8 contig and 6 unitig consensus jobs.
> --
> --                     (tag)Threads
> --            (tag)Memory         |
> --        (tag)         |         |  algorithm
> --        -------  ------  --------  -----------------------------
> -- Grid:  cns        2 GB    4 CPUs  (consensus)
> --
> --
> -- Consensus jobs failed, tried 2 times, giving up.
> --   job ctgcns/0004.cns FAILED.
> --
> 
> ABORT:
> ABORT: Canu 1.7
> ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
> ABORT: Try restarting.  If that doesn't work, ask for help.

I saw in the issue #729 that you advise to increase the error rate (with `cnsErrorRate=0.25`), I will try it.

**Comment by jaube** [comment]
Hi Sergey,
I modified the error rate to 0.25 because of my last error on the consensus step and I have a new issue on the trimming step:

> > -- BEGIN TRIMMING
> --
> --
> -- Overlap jobs failed, tried 2 times, giving up.
> --   job trimming/1-overlapper/001/000045.ovb FAILED.
> --
> 
> ABORT:
> ABORT: Canu 1.7
> ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
> ABORT: Try restarting.  If that doesn't work, ask for help.

Here my last command:
```
canu -p canu-contig4 -d canu-metagenome4 genomeSize=5m corOutCoverage=all corMhapSensitivity=high corMinCoverage=0 correctedErrorRate=0.25 corMaxEvidenceCoverageLocal=10 corMaxEvidenceCoverageGlobal=10 red
Memory=32 oeaMemory=32 batMemory=250 gridEngineThreadsOption='--cpus-per-task THREADS' maxMemory=250G maxThreads=8 -pacbio-raw 041118ERmetagenome_reads.fastq
```
What can I do to fix it? Thanks!

**Comment by skoren** [comment]
That's not the error rate you want to modify. The simplest would be to just edit the consensus.sh shell script to increase the value to 0.25 and run it by hand. 

If you don't have the old assembly then what you want to set is cnsErrorRate, so ```cnsErrorRate=0.25```. You don't need to restart from the raw reads either, you can just run something like ```canu -assemble -p canu-contig4 -d canu-metagenome5 -pacbio-corrected canu-metagenome4/canu-contig4.trimmedReads.fasta.gz```.

**Comment by jaube** [comment]
I succeeded to assemble my metagenome. Thanks a lot for your help.
