### ISSUE TITLE
ovlStore.BUILDING' is a valid ovStore; cannot create a new one and strandedness of cDNA reads

### ISSUE THREAD

**Issue by abayega** [marbl/canu#896]
Hi,

2 questions:

1. is it possible to get Canu to continue from where it finished previously in building the ovStore? 
2. during correction, does orientation (strandedness) of the reads affect correction? I am trying to use Canu to error correct ONT cDNA reads and our library is stranded.

Thank you,

**Comment by abayega** [comment]
Hi, 

thank you very much for the advice, since the job I was re-running was to test whether providing stranded reads improves correction (which you say shouldn't change much) I will just cancel this job. For ovStore Building I will leave that for now. You can mark this as closed, thank you soo much for your quick replies, always.

**Comment by Qiuhaiji** [comment]
Hi;
   specialist, good evening, i come across a question when i used canu1.7.1, thank you for your answer
.I want to know why the code as follow can not work when restart, and how can i do ?/
##the code are as follow
cd /home01/haiji/caculation/genomic/
/home01/haiji/software/canu-1.7.1/Linux-amd64/bin/canu -correct \
        -p camellia -d camellia_fasta \
        genomeSize=3500000000 \
        useGrid=0\
        -pacbio-raw /home01/haiji/rna-data/tea_genome/subreads/tmp/tea_subreads.fasta
##the details of the report errors
#1/-- Starting command on Sun Aug 19 21:34:21 2018 with 7980.745 GB free disk space

    cd correction
    /home01/haiji/software/canu-1.7.1/Linux-amd64/bin/ovStoreBuild \
     -O ./camellia.ovlStore.BUILDING \
     -G ./camellia.gkpStore \
     -M 4-32 \
     -L ./1-overlapper/ovljob.files \
     > ./camellia.ovlStore.err 2>&1

-- Finished on Sun Aug 19 21:42:54 2018 (513 seconds) with 7980.745 GB free disk space
----------------------------------------

ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:

ABORT:
ABORT: Canu 1.7.1
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to create the overlap store.
ABORT:
ABORT: Disk space available:  7980.745 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (correction/camellia.ovlStore.err):
ABORT:

#2/ tail camellia.ovlStore.err 
  bucket 3432 has 126074196 olaps.
  bucket 3433 has 126031795 olaps.
  bucket 3434 has 126077111 olaps.
  bucket 3435 has 45334457 olaps.
Will sort 125.930 million overlaps per bucket, using 3435 buckets 4.00 GB per bucket.
-- BUCKETIZING --

ERROR:  './camellia.ovlStore.BUILDING' is a valid ovStore; cannot create a new one.
