### ISSUE TITLE
split reads step within /trimming/3-overlapbasedtrimming

### ISSUE THREAD

**Issue by peritob** [marbl/canu#903]
Hi again, hoping for some advice please.

I am using canu v1.6 and assembling a 1G diploid genome (using FAQ suggested polyploid assembly parameters and correctedErrorRate=0.040) with 60X coverage within PBS-pro grid environment.

I am at the trimming split read step within /trimming/3-overlapbasedtrimming directory. This is what is currently in the directory but the step timed out so I had to restart canu and give more walltime. 

It has been running for over 8 hours with no change to the split reads files. Is this normal? I have given it 60 hours of walltime after timing out at 48 hours.

```total 390M
288M May  7 21:41 MR_1802b.1.trimReads.log
 35M May  7 21:41 MR_1802b.1.trimReads.clear
 462 May  7 21:41 MR_1802b.1.trimReads.inputReads.gp
 24M May  7 21:41 MR_1802b.1.trimReads.inputReads.dat
 486 May  7 21:41 MR_1802b.1.trimReads.inputNoTrimReads.gp
   0 May  7 21:41 MR_1802b.1.trimReads.inputNoTrimReads.dat
 490 May  7 21:41 MR_1802b.1.trimReads.inputDeletedReads.gp
   0 May  7 21:41 MR_1802b.1.trimReads.inputDeletedReads.dat
 440 May  7 21:41 MR_1802b.1.trimReads.trim5.gp
 11M May  7 21:41 MR_1802b.1.trimReads.trim5.dat
 502 May  7 21:41 MR_1802b.1.trimReads.outputUnchangedReads.gp
1.9M May  7 21:41 MR_1802b.1.trimReads.outputUnchangedReads.dat
 494 May  7 21:41 MR_1802b.1.trimReads.outputTrimmedReads.gp
 22M May  7 21:41 MR_1802b.1.trimReads.outputTrimmedReads.dat
 486 May  7 21:41 MR_1802b.1.trimReads.outputNoOvlReads.gp
250K May  7 21:41 MR_1802b.1.trimReads.outputNoOvlReads.dat
 494 May  7 21:41 MR_1802b.1.trimReads.outputDeletedReads.gp
443K May  7 21:41 MR_1802b.1.trimReads.outputDeletedReads.dat
 440 May  7 21:41 MR_1802b.1.trimReads.trim3.gp
 10M May  7 21:41 MR_1802b.1.trimReads.trim3.dat
1.1K May  7 21:41 MR_1802b.1.trimReads.stats
   0 May  9 12:00 MR_1802b.2.splitReads.log
  77 May  9 12:00 MR_1802b.2.splitReads.err```

Also this is in canu-logs.

Command:
/usr/local/canu/1.6/bin/splitReads \
  -G ../MR_1802b.gkpStore \
  -O ../MR_1802b.ovlStore \
  -Ci ./MR_1802b.1.trimReads.clear \
  -Co ./MR_1802b.2.splitReads.clear \
  -e 0.040 \
  -minlength 1000 \
  -o ./MR_1802b.2.splitReads

**Comment by skoren** [comment]
Yes, this step can take some time given a large genome and especially if you have a large ovlStore, see #682.

**Comment by peritob** [comment]
Thanks, and apologies for not seeing the previous responses. Still running.

**Comment by peritob** [comment]
Just a quick note to say that the job was killed at 60 hours with no change to the splitReads files. I have restarted with 124 hours.

**Comment by peritob** [comment]
Just reposting this as I am still stuck at the splitReads step after running for 95 hours so far...
There is now enough disk space I think (44T). I notice that there are two empty files within the MR_1802b.ovlStore. All other files (3587 in total) appear to be present and around 2.5G. Is this likely to cause problems?

```
2523035480 May  4 12:40 2943
2526813060 May  4 12:36 2944
         0 May  4 15:56 2945
2520668260 May  4 15:58 2946
2521861040 May  4 12:36 2947
2521703440 May  4 15:58 2948
         0 May  4 15:56 2949
2524969520 May  4 12:36 2950
2520610580 May  4 12:35 2951
```

**Comment by skoren** [comment]
That would imply your FS had some issues writing files and lost part of the overlap data. This should be fixed in the latest release but you can't easily switch versions and you'd have to go back to overlapping to recover the lost data. It probably won't make too much difference on trimming but will on assembly. Next time you restart, I'd suggest adding ```saveOverlaps=true```, that way if it happens again during the unitigging step, you can restore the lost data.

**Comment by peritob** [comment]
Thanks for the advice. I think there were problems writing to disk at one stage. Anyway the trimmedReads.fasta was output after 119 hours. I have been using polyploid parameters from FAQ and realize that the resources relate to setting corOutCoverage to 200. This worked well for a previous assembly at lower coverage but adds a very heavy load to compute resources with higher coverage.

**Comment by chopra29** [comment]
split reads step within /trimming/3-overlapbasedtrimming was killed due to expiry of walltime on the node I was using. As the job was killed will those intermediate steps be saved or restart the split read command.

I have about 6TB ovl.store file and can we estimate the time for this step.

**Comment by skoren** [comment]
The time for the step is dependent on your filesystem efficiency, it is dominated by the time  to stream through the store. If you resume canu, it will start the trimming step that did not complete again (split read). The previous trimming step will not re-run since it completed. Request as much time as you can on your cluster, this step does not require a lot of memory (10gb should be plenty) and only one core.

**Comment by chopra29** [comment]
Thank you for the quick response. But when I restart will the split read step resume from were it quit or restart the split read process.

**Comment by skoren** [comment]
Each step in Canu is atomic so they don't resume in the middle. The split read step will resume from scratch. However, your last job which got killed for wall time limits was running more than just split reads, it ran a previous trimming step which counted towards its wall time as well.

**Comment by chopra29** [comment]
Thanks again for the quick response. I notice that split read step takes almost twice as long as it does for the trim reads. This has been consistent at least with 6 of my runs.
