### ISSUE TITLE
comhap error: Job index out of range.

### ISSUE THREAD

**Issue by MarkChristianHarrison** [marbl/canu#904]
Hi,

I'm attempting to assemble a 3Gb genome (~50% repetitive) with Canu 1.7. As it was taking too long on one machine (VM connected to NFE server, grid-engine disabled), I interrupted the analysis in the cormhap stage. We are now trying to run it on further servers besides the VM using an SGE grid-engine.
With the following command (most of these parameters were previously suggested by Sergey to speed up the correction phase by down-weighting repeat content):

~/Canu/canu-1.7/Linux-amd64/bin/canu gridEngine=sge gridEngineThreadsOption="-pe smp THREADS"  corMhapFilterThreshold=0.0000000002 corMhapOptions="--threshold 0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50" mhapMemory=60g mhapBlockSize=500  -p Dpun -d Dpun_Canu genomeSize=3.0g -pacbio-raw *fastq

We have altered the following line in Grid_SGE.pm to limit the servers to be used:
    setGlobalIfUndef("gridEngineNameOption",                 "-cwd -l 'hostname=srvXY|VM' -N ");

The jobs are being submitted but finishing with the following message within the mhap files:

Running job 0 based on command line options.
Error: Job index out of range.

```
Here's the standard-out:
-- BEGIN CORRECTION
--
--
-- Running jobs.  First attempt out of 2.
--
-- 'mhap.jobSubmit-01.sh' -> job 2390377 tasks 15-7671.
--
----------------------------------------
-- Starting command on Wed May  9 14:07:54 2018 with 8534.204 GB free disk space

    cd ~/Dpun_PacBio/Dpun_Canu
    qsub \
      -hold_jid 2390377 \
      -l book_ram=4g \
      -pe smp 1 \
      -S /bin/sh  \
      -cwd \
      -l 'hostname=srvXY|VM' \
      -N  'canu_Dpun' \
      -j y \
      -o canu-scripts/canu.03.out canu-scripts/canu.03.sh
Your job 2390378 ("canu_Dpun") has been submitted

-- Finished on Wed May  9 14:07:54 2018 (lickety-split) with 8534.204 GB free disk space
----------------------------------------
```

Thanks for any help,
Mark

**Comment by MarkChristianHarrison** [comment]
Thank you for the quick response! Your solution sounds very reasonable.
First I reversed the change I had made in Grid_SGE.pm, removed mhap.sh and then submitted the following command:

/global/group/home/harrisom/Canu/canu-1.7/Linux-amd64/bin/canu gridEngine=sge gridEngineThreadsOption="-pe smp THREADS" gridOptions=" -l 'hostname=ebbsrv04|ebb-assembly' -o  '/global/group/home/harrisom/canu.out' -e '/global/group/home/harrisom/canu.err' " corMhapFilterThreshold=0.0000000002 corMhapOptions="--threshold 0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50" mhapMemory=60g mhapBlockSize=500 -p Dpun -d Dpun_Canu genomeSize=3.0g -pacbio-raw *fastq


However, the code doesn't seem to be running at all now. The initial job gets submitted but then does not continue.

Here's the output:

-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_131' (from '/usr/lib/jvm/java-8-oracle/bin/java').
-- Detected gnuplot version '4.6 patchlevel 4' (from 'gnuplot') and image format 'png'.
-- Detected 64 CPUs and 756 gigabytes of memory.
-- User supplied Grid Engine environment '-pe smp THREADS'.
-- Detected Grid Engine consumable 'book_ram'.
--
-- WARNING:
-- WARNING:  Queue 'all.q' has start mode set to 'posix_behavior' and shell set to '/bin/tcsh'.
-- WARNING:
-- WARNING:  Some queues in your configuration will fail to start jobs correctly.
-- WARNING:  Jobs will be submitted with option:
-- WARNING:    gridOptions=-S /bin/sh
-- WARNING:
-- WARNING:  If jobs fail to start, modify the above option to use a valid shell
-- WARNING:  and supply it directly to canu.
-- WARNING:
-- 
-- Found   1 host  with  12 cores and   15 GB memory under Sun Grid Engine control.
-- Found   9 hosts with  24 cores and   31 GB memory under Sun Grid Engine control.
-- Found   1 host  with   4 cores and    3 GB memory under Sun Grid Engine control.
-- Found   1 host  with  12 cores and   62 GB memory under Sun Grid Engine control.
-- Found   1 host  with  24 cores and   23 GB memory under Sun Grid Engine control.
-- Found   1 host  with  64 cores and  755 GB memory under Sun Grid Engine control.
-- Found   1 host  with  80 cores and 1007 GB memory under Sun Grid Engine control.
-- Found   1 host  with  64 cores and  125 GB memory under Sun Grid Engine control.
-- Found   4 hosts with  32 cores and   31 GB memory under Sun Grid Engine control.
-- Found   1 host  with   4 cores and   10 GB memory under Sun Grid Engine control.
-- Found   1 host  with  90 cores and 1874 GB memory under Sun Grid Engine control.
-- Found   1 host  with   8 cores and   15 GB memory under Sun Grid Engine control.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl      8 GB    4 CPUs  (k-mer counting)
-- Grid:  cormhap    6 GB    8 CPUs  (overlap detection with mhap)
-- Grid:  obtovl     4 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl     4 GB    8 CPUs  (overlap detection)
-- Grid:  ovb        2 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs        8 GB    1 CPU   (overlap store sorting)
-- Grid:  red        3 GB    4 CPUs  (read error detection)
-- Grid:  oea        4 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat       16 GB    4 CPUs  (contig construction)
-- Grid:  gfa        8 GB    4 CPUs  (GFA alignment and processing)
--
-- In 'Dpun.gkpStore', found PacBio reads:
--   Raw:        92061600
--   Corrected:  0
--   Trimmed:    0

######################

the log:
###
###  Reading options from '/global/group/home/harrisom/Canu/canu-1.7/Linux-amd64/bin/canu.defaults'
###

# Add site specific options (for setting up Grid or limiting memory/threads) here.

###
###  Reading options from the command line.
###

gridEngine=sge
gridEngineThreadsOption=-pe smp THREADS
gridOptions= -l 'hostname=ebbsrv04.nwz.wwu.de|ebb-assembly.nwz.wwu.de' -o  '/global/group/home/harrisom/canu.out' -e '/global/group/home/harrisom/canu.err' 
corMhapFilterThreshold=0.0000000002
corMhapOptions=--threshold 0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50
mhapMemory=60g
mhapBlockSize=500
genomeSize=3.0g

#####################
canu.sh:
#!/bin/sh

#  Attempt to (re)configure SGE.  For unknown reasons, jobs submitted
#  to SGE, and running under SGE, fail to read the shell init scripts,
#  and so they don't set up SGE (or ANY other paths, etc) properly.
#  For the record, interactive logins (qlogin) DO set the environment.

if [ "x$SGE_ROOT" != "x" -a \
     -e  $SGE_ROOT/$SGE_CELL/common/settings.sh ]; then
  . $SGE_ROOT/$SGE_CELL/common/settings.sh
fi


#  Path to Canu.

syst=`uname -s`
arch=`uname -m | sed s/x86_64/amd64/`

bin="/global/group/home/harrisom/Canu/canu-1.7/$syst-$arch/bin"

if [ ! -d "$bin" ] ; then
  bin="/global/group/home/harrisom/Canu/canu-1.7"
fi



rm -f canu.out
ln -s canu-scripts/canu.04.out canu.out

/usr/bin/env perl \
$bin/canu 'gridEngine=sge' 'gridEngineThreadsOption=-pe smp THREADS' 'gridOptions= -l 'hostname=ebbsrv04.nwz.wwu.de|ebb-assembly.nwz.wwu.de' -o  '/global/group/home/harrisom/canu.out' -e '/global/group/home/harrisom/canu.err' ' 'corMhapFilterThreshold=0.0000000002' 'corMhapOptions=--threshold 0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50' 'mhapMemory=60g' 'mhapBlockSize=500' -p 'Dpun' 'genomeSize=3.0g' -pacbio-raw '/EBB-ZIVNFS/harrisom/Dpun_PacBio/Sequel.RunS029.005.COQ1-3-4.ccs.bam.fastq' -pacbio-raw '/EBB-ZIVNFS/harrisom/Dpun_PacBio/Sequel.RunS029.005.COQ1-3-4.longest.bam.fastq' -pacbio-raw '/EBB-ZIVNFS/harrisom/Dpun_PacBio/Sequel.RunS029.005.COQ1-3-4.scraps.bam.fastq' -pacbio-raw '/EBB-ZIVNFS/harrisom/Dpun_PacBio/Sequel.RunS029.005.COQ1-3-4.subreads.bam.fastq' -pacbio-raw ' <all the file names> canuIteration=0

**Comment by skoren** [comment]
You don't need to specify the canu.out/canu.err outputs, that will get always passed through to every command which is not what you want. Canu will handle that appropriately.

There is no error in your log, I'd imagine the command is still running (e.g. is it in your queue).

**Comment by MarkChristianHarrison** [comment]
I posted that above under "output".

The log just ends with:
-- In 'Dpun.gkpStore', found PacBio reads:
--   Raw:        92061600
--   Corrected:  0
--   Trimmed:    0
(END)

**Comment by skoren** [comment]
No I mean, run Canu without overwriting the input/outputs and look in your asm ```folder/canu-scripts/canu.*.out``` That log you posted is truncated so I want to see the full version logged by Canu is. Do you have any jobs in the queue submitted by Canu still or are they all gone?

**Comment by MarkChristianHarrison** [comment]
I've just had another look. The first line of the log, which I missed before, seems to point towards a problem with our grid:
/var/spool/gridengine/execd/ebbsrv04/job_scripts/2390400: 31: /var/spool/gridengine/execd/ebbsrv04/job_scripts/2390400: ebb-assembly.nwz.wwu.de : not found

Do you agree?
Thank you for your time, Sergey!

**Comment by skoren** [comment]
i have not seen that before so I'm not sure what it is caused by. Were any jobs submitted by Canu (like mhap.sh) or just the initial one?

**Comment by MarkChristianHarrison** [comment]
No, just the initial one was submitted. Strangely, I didn't get this error before I deleted the mhap.sh file.

By the way, I ran the code again without the -o -e options and still received the truncated output I presented above.

In any case I assume there has been a problem hooking up the VM to our grid.
I will keep trying. Thanks again for your help

**Comment by skoren** [comment]
Try with a new run or remove 1-overlapper folder, it's possible Canu isn't re-generating the mhap.sh file.

**Comment by MarkChristianHarrison** [comment]
I was hoping I wouldn't need to remove the 1-overlapper folder, since the precompute phase took about 3 weeks to complete. I've tried a new run with grid disabled and mhap.sh has been regenerated and everything is running fine. 
So maybe our grid is causing the problems?

**Comment by skoren** [comment]
Yes, that does sound like it but it would still be better to try on a clean folder to confirm. It shouldn't take as long on the grid with more cores available.
