### ISSUE TITLE
Massive drop in coverage (55x to 1.96x) in PacBio Sequel data

### ISSUE THREAD

**Issue by kautto** [marbl/canu#905]
Dear devs,

I'm having issues with an unexpectedly high loss of coverage (55x down to 1.96x) on some PacBio Sequel data. The data is from a cancer cell line so we're assuming ~3gb genome size. The correction step appears to kill the coverage, for whatever reason. 

Command (for correction):
```
/igm/projects/KAUTTO_Esko/software/canu-1.7/Linux-amd64/bin/canu -correct \
-p A673 \
-d /igm/projects/KAUTTO_Esko/A673/PacBio/Canu.20180504 \
genomeSize=3.0g \
-maxMemory=480G \
-maxThreads=64 \
cormhapMemory=48G \
cormhapThreads=8 \
gridEngineThreadsOption="-pe smp THREADS" \
gridEngineMemoryOption="-l h_vmem=MEMORY -l mem_free=MEMORY" \
gridOptionsCORMHAP="-l h_vmem=7g -l mem_free=56g -pe sharedmem 8 -pe smp 8" \
gnuplot=/igm/projects/KAUTTO_Esko/software/gnuplot/gnuplot \
-pacbio-raw /igm/projects/KAUTTO_Esko/A673/PacBio/FASTQ/1SQ_reads.tar.gz /igm/projects/KAUTTO_Esko/A673/PacBio/FASTQ/2SQ1-4_reads.tar.gz /igm/projects/KAUTTO_Esko/A673/PacBio/FASTQ/2SQ5-8_reads.tar.gz /igm/projects/KAUTTO_Esko/A673/PacBio/FASTQ/3SQ1-4_reads.tar.gz /igm/projects/KAUTTO_Esko/A673/PacBio/FASTQ/3SQ5-8_reads.tar.gz /igm/projects/KAUTTO_Esko/A673/PacBio/FASTQ/4SQ1235_reads.tar.gz
```

I had to manually set the memory etc. limits above, since otherwise Java over-allocates itself memory and crashes everything. But I don't think that should be the culprit here. 

[canu.zip](https://github.com/marbl/canu/files/1992073/canu.zip) has the canu.out and .report files.

Any ideas would be much appreciated!

**Comment by skoren** [comment]
Sequel data is lower quality than RS data, especially the earlier chemistries. The FAQ has some suggested alternate parameters. I'd start with at least ```correctedErrorRate=0.105 corMhapSensitivity=normal```. If you still don't get over 35x coverage of corrected reads, also add ```corMinCoverage=0```.

**Comment by kautto** [comment]
@skoren I'll give that a try and see if it works, thanks!

**Comment by skoren** [comment]
Added info on sequel data to FAQ, inactive closing.
