### ISSUE TITLE
Assembly failed for plasmid DNA

### ISSUE THREAD

**Issue by yi-syong** [marbl/canu#906]
Hello everyone.
I use Canu 1.7 to assembly plasmid DNA.
It has been running for 3 weeks and has no result.

The longest length of plasmid DNA is about 125k.
79% of plasmid DNA length is between 1000 and 16,000.

The system is Ubuntu 16.04. The parameter is set maxmemory=10, maxthread=8.

Does anyone have solutions?

Please advise.
Thanks for reply.

**Comment by skoren** [comment]
There isn't enough information here to help much. You said it's still running, does that mean it didn't actually fail but is just slow? What is your canu command? What is the report file say (in the assembly folder)? What is the full output of the canu command?

**Comment by yi-syong** [comment]
Thanks for your reply.
I used another dataset (203k reads) to assemble with the same system settings before.
It took only 5 hours to complete.

This dataset is only 24k reads. 
I think that running over 3 weeks is too long.
Maybe too less reads or bad quality of the dataset ?

command : 
canu -p R16-0676 -d output_folder genomeSize=125k maxMemory=10 maxThreads=8 -nanopore-raw raw_reads.fastq

report:
(I have manually interrupted)

[CORRECTION/READS]
--
-- In gatekeeper store './R16-0676.gkpStore':
--   Found 42079 reads.
--   Found 539350360 bases (4314.8 times coverage).
--
--   Read length histogram (one '*' equals 261.72 reads):
--        0   4999  18321 *********************************************************************
--     5000   9999   7175 ***************************
--    10000  14999   4063 ***************
--    15000  19999   2992 ***********
--    20000  24999   2271 ********
--    25000  29999   1834 *******
--    30000  34999   1410 *****
--    35000  39999   1145 ****
--    40000  44999    860 ***
--    45000  49999    635 **
--    50000  54999    457 *
--    55000  59999    335 *
--    60000  64999    259 
--    65000  69999    138 
--    70000  74999     74 
--    75000  79999     42 
--    80000  84999     18 
--    85000  89999     11 
--    90000  94999      4 
--    95000  99999      2 
--   100000 104999      5 
--   105000 109999      3 
--   110000 114999      4 
--   115000 119999      6 
--   120000 124999     15

[CORRECTION/MERS]
--
--  16-mers                                                                                           Fraction
--    Occurrences   NumMers                                                                         Unique Total
--       1-     1 136225304 *******************************************************************--> 0.7509 0.2529
--       2-     2  21767732 ********************************************************************** 0.8709 0.3337
--       3-     4  11156375 ***********************************                                    0.9114 0.3746
--       5-     7   5533207 *****************                                                      0.9459 0.4257
--       8-    11   2854052 *********                                                              0.9684 0.4773
--      12-    16   1332513 ****                                                                   0.9807 0.5195
--      17-    22    719194 **                                                                     0.9868 0.5498
--      23-    29    453677 *                                                                      0.9904 0.5739
--      30-    37    310351                                                                        0.9927 0.5947
--      38-    46    221173                                                                        0.9943 0.6133
--      47-    56    163136                                                                        0.9955 0.6299
--      57-    67    122962                                                                        0.9963 0.6451
--      68-    79     93510                                                                        0.9970 0.6590
--      80-    92     71904                                                                        0.9975 0.6715
--      93-   106     55918                                                                        0.9979 0.6827
--     107-   121     44250                                                                        0.9982 0.6929
--     122-   137     34849                                                                        0.9984 0.7022
--     138-   154     27370                                                                        0.9986 0.7104
--     155-   172     21571                                                                        0.9987 0.7177
--     173-   191     17235                                                                        0.9989 0.7242
--     192-   211     14047                                                                        0.9989 0.7299
--     212-   232     11512                                                                        0.9990 0.7351
--     233-   254      9425                                                                        0.9991 0.7398
--     255-   277      7908                                                                        0.9991 0.7441
--     278-   301      6596                                                                        0.9992 0.7480
--     302-   326      5485                                                                        0.9992 0.7515
--     327-   352      4595                                                                        0.9992 0.7546
--     353-   379      3976                                                                        0.9993 0.7575
--     380-   407      3522                                                                        0.9993 0.7602
--     408-   436      3304                                                                        0.9993 0.7628
--     437-   466      3047                                                                        0.9993 0.7653
--     467-   497      2799                                                                        0.9993 0.7679
--     498-   529      2726                                                                        0.9994 0.7704
--     530-   562      2783                                                                        0.9994 0.7730
--     563-   596      2977                                                                        0.9994 0.7758
--     597-   631      3017                                                                        0.9994 0.7790
--     632-   667      3324                                                                        0.9994 0.7825
--     668-   704      3719                                                                        0.9994 0.7865
--     705-   742      4028                                                                        0.9995 0.7913
--     743-   781      4300                                                                        0.9995 0.7967
--     782-   821      4788                                                                        0.9995 0.8028
--
--       15903 (max occurrences)
--   402493871 (total mers, non-unique)
--    45192983 (distinct mers, non-unique)
--   136225304 (unique mers)

[CORRECTION/LAYOUT]
--                             original      original
--                            raw reads     raw reads
--   category                w/overlaps  w/o/overlaps
--   -------------------- ------------- -------------
--   Number of Reads              38186          3893
--   Number of Bases          491384336      45727559
--   Coverage                  3931.075       365.820
--   Median                        6346          7078
--   Mean                         12868         11746
--   N50                          27498         23021
--   Minimum                       1000             0
--   Maximum                     124973        119577
--   
--                                        --------corrected---------  ----------rescued----------
--                             evidence                     expected                     expected
--   category                     reads            raw     corrected            raw     corrected
--   -------------------- -------------  ------------- -------------  ------------- -------------
--   Number of Reads                728             48            48          23918         23918
--   Number of Bases           44137204        5090789       5072279      323788921     243398345
--   Coverage                   353.098         40.726        40.578       2590.311      1947.187
--   Median                       63122         108134        108121           7570          4634
--   Mean                         60628         106058        105672          13537         10176
--   N50                          65472         112341        111938          26997         23490
--   Minimum                       2198          84662         84649           1004          1001
--   Maximum                     124973         124973        124960          89584         70437
--   
--                        --------uncorrected--------
--                                           expected
--   category                       raw     corrected
--   -------------------- ------------- -------------
--   Number of Reads              18113         18113
--   Number of Bases          208232185      36660152
--   Coverage                  1665.857       293.281
--   Median                        5034             0
--   Mean                         11496          2023
--   N50                          26289         63967
--   Minimum                          0             0
--   Maximum                     119577         84275
--   
--   Maximum Memory          1826730872

[TRIMMING/READS]
--
-- In gatekeeper store './R16-0676.gkpStore':
--   Found 23963 reads.
--   Found 244651074 bases (1957.2 times coverage).
--
--   Read length histogram (one '*' equals 179.98 reads):
--        0   4999  12599 **********************************************************************
--     5000   9999   4121 **********************
--    10000  14999   1997 ***********
--    15000  19999   1283 *******
--    20000  24999    946 *****
--    25000  29999    751 ****
--    30000  34999    600 ***
--    35000  39999    519 **
--    40000  44999    418 **
--    45000  49999    320 *
--    50000  54999    229 *
--    55000  59999    120 
--    60000  64999     11 
--    65000  69999      0 
--    70000  74999      1 
--    75000  79999      0 
--    80000  84999      4 
--    85000  89999      8 
--    90000  94999      5 
--    95000  99999      1 
--   100000 104999      4 
--   105000 109999      5 
--   110000 114999      3 
--   115000 119999      4 
--   120000 124999     14

[TRIMMING/MERS]
--
--  22-mers                                                                                           Fraction
--    Occurrences   NumMers                                                                         Unique Total
--       1-     1  20383109 *******************************************************************--> 0.6559 0.0835
--       2-     2   2897904 ********************************************************************** 0.7491 0.1072
--       3-     4   2096017 **************************************************                     0.7907 0.1231
--       5-     7   1516390 ************************************                                   0.8357 0.1485
--       8-    11   1433507 **********************************                                     0.8780 0.1857
--      12-    16   1279690 ******************************                                         0.9213 0.2432
--      17-    22    727816 *****************                                                      0.9584 0.3128
--      23-    29    269591 ******                                                                 0.9781 0.3629
--      30-    37    104890 **                                                                     0.9854 0.3874
--      38-    46     53011 *                                                                      0.9884 0.4006
--      47-    56     35053                                                                        0.9900 0.4091
--      57-    67     26410                                                                        0.9911 0.4163
--      68-    79     20687                                                                        0.9919 0.4229
--      80-    92     16663                                                                        0.9926 0.4290
--      93-   106     14238                                                                        0.9931 0.4348
--     107-   121     11858                                                                        0.9935 0.4405
--     122-   137     10972                                                                        0.9939 0.4460
--     138-   154      9627                                                                        0.9943 0.4518
--     155-   172      7683                                                                        0.9946 0.4575
--     173-   191      6543                                                                        0.9948 0.4626
--     192-   211      5580                                                                        0.9950 0.4675
--     212-   232      4983                                                                        0.9952 0.4720
--     233-   254      4675                                                                        0.9954 0.4765
--     255-   277      3998                                                                        0.9955 0.4812
--     278-   301      3722                                                                        0.9956 0.4855
--     302-   326      3487                                                                        0.9957 0.4899
--     327-   352      3492                                                                        0.9959 0.4944
--     353-   379      3123                                                                        0.9960 0.4993
--     380-   407      2789                                                                        0.9961 0.5039
--     408-   436      2856                                                                        0.9962 0.5084
--     437-   466      2687                                                                        0.9963 0.5134
--     467-   497      2690                                                                        0.9963 0.5183
--     498-   529      2601                                                                        0.9964 0.5236
--     530-   562      2585                                                                        0.9965 0.5291
--     563-   596      2718                                                                        0.9966 0.5349
--     597-   631      2642                                                                        0.9967 0.5413
--     632-   667      2922                                                                        0.9968 0.5480
--     668-   704      2973                                                                        0.9969 0.5558
--     705-   742      3085                                                                        0.9970 0.5642
--     743-   781      3523                                                                        0.9971 0.5734
--     782-   821      3791                                                                        0.9972 0.5844
--
--        7975 (max occurrences)
--   223764742 (total mers, non-unique)
--    10693772 (distinct mers, non-unique)
--    20383109 (unique mers)

[TRIMMING/TRIMMING]
--  PARAMETERS:
--  ----------
--     1000    (reads trimmed below this many bases are deleted)
--   0.1440    (use overlaps at or below this fraction error)
--        1    (break region if overlap is less than this long, for 'largest covered' algorithm)
--        1    (break region if overlap coverage is less than this many read, for 'largest covered' algorithm)
--  
--  INPUT READS:
--  -----------
--   42079 reads    244651074 bases (reads processed)
--       0 reads            0 bases (reads not processed, previously deleted)
--       0 reads            0 bases (reads not processed, in a library where trimming isn't allowed)
--  
--  OUTPUT READS:
--  ------------
--   14754 reads    146159546 bases (trimmed reads output)
--    8801 reads     96870036 bases (reads with no change, kept as is)
--   18121 reads         5635 bases (reads with no overlaps, deleted)
--     403 reads       399807 bases (reads with short trimmed length, deleted)
--  
--  TRIMMING DETAILS:
--  ----------------
--   10856 reads       649451 bases (bases trimmed from the 5' end of a read)
--    7995 reads       566599 bases (bases trimmed from the 3' end of a read)

[TRIMMING/SPLITTING]
--  PARAMETERS:
--  ----------
--     1000    (reads trimmed below this many bases are deleted)
--   0.1440    (use overlaps at or below this fraction error)
--  INPUT READS:
--  -----------
--   23555 reads    244245632 bases (reads processed)
--   18524 reads       405442 bases (reads not processed, previously deleted)
--       0 reads            0 bases (reads not processed, in a library where trimming isn't allowed)
--  
--  PROCESSED:
--  --------
--       0 reads            0 bases (no overlaps)
--       0 reads            0 bases (no coverage after adjusting for trimming done already)
--       0 reads            0 bases (processed for chimera)
--       0 reads            0 bases (processed for spur)
--   23555 reads    244245632 bases (processed for subreads)
--  
--  READS WITH SIGNALS:
--  ------------------
--       0 reads            0 signals (number of 5' spur signal)
--       0 reads            0 signals (number of 3' spur signal)
--       0 reads            0 signals (number of chimera signal)
--       9 reads            9 signals (number of subread signal)
--  
--  SIGNALS:
--  -------
--       0 reads            0 bases (size of 5' spur signal)
--       0 reads            0 bases (size of 3' spur signal)
--       0 reads            0 bases (size of chimera signal)
--       9 reads         4242 bases (size of subread signal)
--  
--  TRIMMING:
--  --------
--       2 reads         3332 bases (trimmed from the 5' end of the read)
--       7 reads         8130 bases (trimmed from the 3' end of the read)

[UNITIGGING/READS]
--
-- In gatekeeper store './R16-0676.gkpStore':
--   Found 23555 reads.
--   Found 243018120 bases (1944.14 times coverage).
--
--   Read length histogram (one '*' equals 175.38 reads):
--        0   4999  12277 **********************************************************************
--     5000   9999   4077 ***********************
--    10000  14999   1977 ***********
--    15000  19999   1274 *******
--    20000  24999    948 *****
--    25000  29999    750 ****
--    30000  34999    595 ***
--    35000  39999    517 **
--    40000  44999    416 **
--    45000  49999    319 *
--    50000  54999    228 *
--    55000  59999    117 
--    60000  64999     11 
--    65000  69999      0 
--    70000  74999      1 
--    75000  79999      0 
--    80000  84999      4 
--    85000  89999      8 
--    90000  94999      5 
--    95000  99999      1 
--   100000 104999      4 
--   105000 109999      5 
--   110000 114999      3 
--   115000 119999      4 
--   120000 124999     14

[UNITIGGING/MERS]
--
--  22-mers                                                                                           Fraction
--    Occurrences   NumMers                                                                         Unique Total
--       1-     1  19704347 *******************************************************************--> 0.6495 0.0812
--       2-     2   2871683 ********************************************************************** 0.7442 0.1049
--       3-     4   2086748 **************************************************                     0.7865 0.1208
--       5-     7   1515900 ************************************                                   0.8326 0.1463
--       8-    11   1437283 ***********************************                                    0.8759 0.1838
--      12-    16   1273976 *******************************                                        0.9204 0.2419
--      17-    22    714517 *****************                                                      0.9580 0.3113
--      23-    29    263259 ******                                                                 0.9779 0.3609
--      30-    37    103359 **                                                                     0.9851 0.3848
--      38-    46     52003 *                                                                      0.9882 0.3979
--      47-    56     34783                                                                        0.9898 0.4064
--      57-    67     26318                                                                        0.9909 0.4135
--      68-    79     20419                                                                        0.9917 0.4202
--      80-    92     16631                                                                        0.9924 0.4262
--      93-   106     14230                                                                        0.9929 0.4321
--     107-   121     11855                                                                        0.9934 0.4378
--     122-   137     10934                                                                        0.9938 0.4434
--     138-   154      9617                                                                        0.9941 0.4492
--     155-   172      7663                                                                        0.9944 0.4549
--     173-   191      6538                                                                        0.9947 0.4601
--     192-   211      5483                                                                        0.9949 0.4649
--     212-   232      5027                                                                        0.9951 0.4694
--     233-   254      4630                                                                        0.9952 0.4740
--     255-   277      3991                                                                        0.9954 0.4787
--     278-   301      3717                                                                        0.9955 0.4830
--     302-   326      3474                                                                        0.9956 0.4874
--     327-   352      3490                                                                        0.9958 0.4919
--     353-   379      3117                                                                        0.9959 0.4968
--     380-   407      2792                                                                        0.9960 0.5015
--     408-   436      2850                                                                        0.9961 0.5061
--     437-   466      2697                                                                        0.9962 0.5110
--     467-   497      2674                                                                        0.9963 0.5160
--     498-   529      2598                                                                        0.9963 0.5213
--     530-   562      2580                                                                        0.9964 0.5268
--     563-   596      2714                                                                        0.9965 0.5326
--     597-   631      2661                                                                        0.9966 0.5391
--     632-   667      2928                                                                        0.9967 0.5459
--     668-   704      2962                                                                        0.9968 0.5538
--     705-   742      3100                                                                        0.9969 0.5621
--     743-   781      3549                                                                        0.9970 0.5715
--     782-   821      3759                                                                        0.9971 0.5826
--
--        7951 (max occurrences)
--   222819118 (total mers, non-unique)
--    10632715 (distinct mers, non-unique)
--    19704347 (unique mers)

**Comment by brianwalenz** [comment]
We're not handling very deep coverage well - and you've got 4300x coverage in the input.

Lots of options to try, but nothing I have much experience actually using.

1) There are 14 trimmed reads that are 120kbp to 125kbp long.  These seem like they should be the full plasmid, but consensus quality might be lower than if contigs were generated.

2) The slowdown is caused by an explicit alignment of reads-to-reads.  The -fast option uses a different algorithm that seems to work better with long nanopore reads.  Remove the scripts and partial results from the old algorithm (in unitigging/1-overlapper) before restarting with this option.

3) The latest non-released Canu has support for sampling reads (http://canu.readthedocs.io/en/latest/parameter-reference.html#readsamplingcoverage).  However, I don't have much experience actually using these options.

The problem is that the long reads are what you want to keep for assembly, but the short reads are typically more true.  There aren't many long reads, so a random sampling tends to lose them.  Thus the Canu sampling options allow a biasing towards long reads, and it is this I don't know how to set.  Sampling down to 200x for uncorrected reads seems reasonable.

An alternate strategy is to sample the corrected and trimmed reads you already have.  In this case, sampling down to 50x and biasing to the longer reads seems reasonable.

**Comment by yi-syong** [comment]
Thank you !
