### ISSUE TITLE
Consensus jobs failed error

### ISSUE THREAD

**Issue by WallyL** [marbl/canu#907]
Hi,
I'm running canu ver. 1.6 within a Singularity container.  The job is running on a cluster and I'm using a single high mem (512G) 24 core node.  I am fairly new to this, but I have recently used the same configuration to assemble a 5 Mb bacterial genome w/o any issues.  This data is an algal isolate of unknown complexity and genome size, but estimated to be < 20 Mb.  For this first attempt, I was running the job with default settings.  The dataset is from a single Sequel SMRT cell, ca. 7GB data, so likely > 300X coverage.

Here is my submission code:
singularity exec /home/software/Singularity_Containers/canu-1.6--pl5.22.0_1.simg canu -p psal1 -d Psal_assy1 genomeSize=20m -pacbio-raw Psal_subreads.fasta gnuplotTested=true useGrid=false maxMemory=400 maxThreads=20

Here is the error (I restarted the job as suggested and got the same error again) 

```-- Using slow alignment for consensus (iteration '1').
-- Configured 3 contig and 2 unitig consensus jobs.
--
-- Consensus jobs failed, retry.
--   job utgcns/0002.cns FAILED.
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'cns' concurrent execution on Fri May 11 07:34:50 2018 with 62790.622 GB free disk space (1 processes; 5 concurrently)

    cd unitigging/5-consensus
    ./consensus.sh 5 > ./consensus.000005.out 2>&1

-- Finished on Fri May 11 07:37:35 2018 (165 seconds) with 62772.819 GB free disk space
----------------------------------------
-- Using slow alignment for consensus (iteration '2').
-- Configured 3 contig and 2 unitig consensus jobs.
--
-- Consensus jobs failed, tried 2 times, giving up.
--   job utgcns/0002.cns FAILED.
--

ABORT:
ABORT: Canu 1.6
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```
Any suggestions as to what I should to try next would be greatly appreciated.

**Comment by skoren** [comment]
Increasing the error rate for consensus should fix this, see issue #894 and #729. This may also be fixed in Canu 1.7 but you can't just run it on your current data, you'd have to re-start the unitigging step.

**Comment by WallyL** [comment]
Thank you, Sergey.  Adding the cnsErrorRate=0.25 flag got me through it.  Now if I can just get some contiguity in the assembly...

**Comment by skoren** [comment]
Sequel data != RS data, see issue #905 for some suggested parameters that would probably help you as well. Without the report file and maybe the unitigging logs can't say it would help for sure. If you want to post those and open a new issue go ahead.
