### ISSUE TITLE
Mhap precompute jobs failed

### ISSUE THREAD

**Issue by llalcll** [marbl/canu#909]
I am very new with canu and command in line. I am assembling a genome around 2.8 mil with canu 1.6.
my command: canu -p canu -d canu_outdir genomeSize=2.8m gnuplotTested=true -pacbio-raw S194_allreads.tar.gz.  And, the command was aborted at mhap precompute jobs failed. 

```
 CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '10.0.1' (from 'java').
-- Detected 4 CPUs and 8 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |  algorithm
--        -------  ------  --------   --------  -----------------------------
-- Local: meryl      8 GB    4 CPUs x   1 job   (k-mer counting)
-- Local: cormhap    6 GB    4 CPUs x   1 job   (overlap detection with mhap)
-- Local: obtovl     8 GB    4 CPUs x   1 job   (overlap detection)
-- Local: utgovl     8 GB    4 CPUs x   1 job   (overlap detection)
-- Local: cor        8 GB    2 CPUs x   2 jobs  (read correction)
-- Local: ovb        2 GB    1 CPU  x   4 jobs  (overlap store bucketizer)
-- Local: ovs        8 GB    1 CPU  x   4 jobs  (overlap store sorting)
-- Local: red        2 GB    4 CPUs x   1 job   (read error detection)
-- Local: oea        1 GB    1 CPU  x   4 jobs  (overlap error adjustment)
-- Local: bat        8 GB    4 CPUs x   1 job   (contig construction)
-- Local: cns        8 GB    4 CPUs x   1 job   (consensus)
-- Local: gfa        8 GB    4 CPUs x   1 job   (GFA alignment and processing)
--
-- Found PacBio uncorrected reads in 'correction/canu.gkpStore'.
--
-- Generating assembly 'canu' in '/home/lxadmin/S194/H01_1/Analysis_Results/canu_outdir'
--
-- Parameters:
--
--  genomeSize        2800000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0450 (  4.50%)
--    utgOvlErrorRate 0.0450 (  4.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0450 (  4.50%)
--    utgErrorRate    0.0450 (  4.50%)
--    cnsErrorRate    0.0750 (  7.50%)
--
--
-- BEGIN CORRECTION
--
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'cormhap' concurrent execution on Fri May 11 18:38:00 2018 with 61.687 GB free disk space (5 processes; 1 concurrently)

    cd correction/1-overlapper
    ./precompute.sh 1 > ./precompute.000001.out 2>&1
    ./precompute.sh 2 > ./precompute.000002.out 2>&1
    ./precompute.sh 3 > ./precompute.000003.out 2>&1
    ./precompute.sh 4 > ./precompute.000004.out 2>&1
    ./precompute.sh 5 > ./precompute.000005.out 2>&1

-- Finished on Fri May 11 18:38:08 2018 (8 seconds) with 61.687 GB free disk space
----------------------------------------
--
-- Mhap precompute jobs failed, retry.
--   job correction/1-overlapper/blocks/000001.dat FAILED.
--   job correction/1-overlapper/blocks/000002.dat FAILED.
--   job correction/1-overlapper/blocks/000003.dat FAILED.
--   job correction/1-overlapper/blocks/000004.dat FAILED.
--   job correction/1-overlapper/blocks/000005.dat FAILED.
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'cormhap' concurrent execution on Fri May 11 18:38:08 2018 with 61.687 GB free disk space (5 processes; 1 concurrently)

    cd correction/1-overlapper
    ./precompute.sh 1 > ./precompute.000001.out 2>&1
    ./precompute.sh 2 > ./precompute.000002.out 2>&1
    ./precompute.sh 3 > ./precompute.000003.out 2>&1
    ./precompute.sh 4 > ./precompute.000004.out 2>&1
    ./precompute.sh 5 > ./precompute.000005.out 2>&1

-- Finished on Fri May 11 18:38:16 2018 (8 seconds) with 61.687 GB free disk space
----------------------------------------
--
-- Mhap precompute jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/blocks/000001.dat FAILED.
--   job correction/1-overlapper/blocks/000002.dat FAILED.
--   job correction/1-overlapper/blocks/000003.dat FAILED.
--   job correction/1-overlapper/blocks/000004.dat FAILED.
--   job correction/1-overlapper/blocks/000005.dat FAILED.
--

ABORT:
ABORT: Canu 1.6
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:


Precompute.000001.out file 

Running job 1 based on command line options.
Dumping reads from 1 to 18000 (inclusive).

Starting mhap precompute.

Error: Unable to access jarfile /usr/lib/canu/mhap.jar
Mhap failed.
```

**Comment by llalcll** [comment]
I downloaded canu 1.7 from the release page, and installed by command
apt install canu 1.7 (the file name for linux).
But when it showed me canu 1.6 instead of 1.7. And, I still have the same
issue as my previous post.

**Comment by skoren** [comment]
You shouldn't need to use apt to install the downloaded file, that is a package manager and has nothing to do with Canu. Follow the instructions on the release page to extract the file. For example say you are in your home folder, run this:
```
curl -L https://github.com/marbl/canu/releases/download/v1.7/canu-1.7.Linux-amd64.tar.xz -o canu-1.7.Linux-amd64.tar.xz
tar -xf canu-1.7.Linux-amd64.tar.xz 
./canu-1.7/*/bin/canu -help
./canu-1.7/*/bin/canu <your command>
```
You'll have to either add that folder to your path or remove your other installation, otherwise whenever you run "canu" it will run the one in /usr/bin/.

**Comment by robvdl** [comment]
I notice in your logs your JRE version is 10, I don't know if this is related to your issue but I have been unable to use Java 10 unless I manually remove the -d64 option which seems to have been removed in Java 10.

I have filed this under issue #901

**Comment by llalcll** [comment]
Thank you for your help. My issue is solved. I reinstalled java se 8
instead of 10, and it works.

**Comment by llalcll** [comment]
Thank you very much. I reinstall java as you suggested and it worked.
And, I have a question, I am very new with all of the command. You
mentioned that you removed the -d64. What does it mean may I ask?


On Sun, May 13, 2018 at 4:44 PM, Rob van der Linde <notifications@github.com

**Comment by robvdl** [comment]
Sure, when we ran canu last week on a fresh Ubuntu 18.04 VM we noticed that it failed to run the java mhap step.

We noticed that canu creates some shell scripts then executes them, in one of those shell scripts it was invoking java with -d64 and that is failing on Java 10 because Java 10 doesn't have such a command line argument anymore.

One thing that can be done is the shell script could be patched to not use -d64 argument as I don't think it is necessary anymore, because it was already a 64 bit OS and 64 bit Java JRE, I don't think it is needed it anymore and that is possibly why it was removed from Java 10.

In the mean time we downgraded to Java 8 and all was good, but my suggestion to the canu authors is looking into removing -d64, even if the Java version has to be detected and only do it if Java version is >= 10

**Comment by skoren** [comment]
It looks like only a 64-bit VM is available starting with 10. Previously, we had issues with users running a 32-bit VM so we wanted to explicitly request 64bit so it would crash if only a 32-bit VM was available. I've added a check for this option so it only gets used when available.
