### ISSUE TITLE
Use relative URLs in the .html reports

### ISSUE THREAD

**Issue by tseemann** [marbl/canu#91]
The HTML reports are awesome, but I can't relocate them to my webserver, because all the `HREF` are absolute file URLs to where I ran CANU from.

Can you make them relative to the `-d folder` I ran canu into so I can relocate the reports?

**Comment by brianwalenz** [comment]
I didn't exactly make them relative, but I did copy the images to a single directory (one directory for each of the three html outputs).

Yes, I know, I still need to finish unitigging.html.  ;-)
