### ISSUE TITLE
My assembly is too short 

### ISSUE THREAD

**Issue by ssilva1** [marbl/canu#911]
I am running Canu 1.7 on a linux machine.
My genome of interest is about 40Mb (size from both illumina and pacbio assemblies of related strains). However, I am getting an assembly file of 3.5Mb. 

I have tried these three commands: 

canu -p Example -d Example.canu genomeSize=40m -pacbio-raw filtered.subreads.fastq

canu -p Example -d Example.canu genomeSize=40m corOutCoverage=1000 -pacbio-raw filtered.subreads.fastq

canu -p canu-lins -d Example.canu genomeSize=41m corOutCoverage=all corMhapSensitivity=high corMinCoverage=0 correctedErrorRate=0.25 redMemory=32 oeaMemory=32 batMemory=200 gridEngineThreadsOption='--cpus-per-task THREADS' maxMemory=230G maxThreads=32 -pacbio-raw filtered.subreads.fastq

All give me a final assembly file of 3 to 3.5Mb. The correctedReads.fasta.gz is 80Mb and the trimmedReads.fasta.gz is 52Mb. 

I have tried running the assembly separately and still get a contigs file of the same size. 

The histogram of the reads shows the following:

![screen shot 2018-05-13 at 12 14 02](https://user-images.githubusercontent.com/33957452/39966641-2c82b068-56a7-11e8-9724-0ce8cf7d8c36.png)

Any ideas on how to fix this? 

Thanks very much!

**Comment by skoren** [comment]
Given the variations of commands you've tried, I would suspect something with the sequencing not the assembly. Do you have the full Canu report file, that will have more information on the corrected reads. You could also try running GenomeScope on the ```trimmed/0-mercounts/*.histogram``` file to get an estimate of the genome size/etc.

**Comment by ssilva1** [comment]
Thanks for the reply. I have attached  the report file.
Do you see anything out of the ordinary?



On 13 May 2018, at 19:52, Sergey Koren <notifications@github.com<mailto:notifications@github.com>> wrote:


Given the variations of commands you've tried, I would suspect something with the sequencing not the assembly. Do you have the full Canu report file, that will have more information on the corrected reads. You could also try running GenomeScope on the trimmed/0-mercounts/*.histogram file to get an estimate of the genome size/etc.

**Comment by skoren** [comment]
Github doesn't process email attachments, you have to either upload it on the GitHub page or put it in the body (escaped by three `).

**Comment by ssilva1** [comment]
[TvLinsPB.report.txt](https://github.com/marbl/canu/files/1998806/TvLinsPB.report.txt)

**Comment by skoren** [comment]
That reports shows you end up with no corrected coverage, indicating the data is low quality. Is this RSII or Sequel data? 

I noticed in your commands you have the same folder being passed to -d, did you remove this folder before running each command or not? If not, then none of your commands except the first one generated an assembly. The other runs would notice you already have a completed assembly and do nothing. If not do you have the report from the latest run.

**Comment by ssilva1** [comment]
This is Sequel data. And I changed the directories every time. The first file was the report from the first command and the one I attach now is from the second (after adding corOutCoverage=1000 change) . I don't have from the third one. 

If the data remains low quality, would the use of another PacBio assembly as reference help the process? Can this be done?

Thanks!



[TvLins-trial.report.txt](https://github.com/marbl/canu/files/1998833/TvLins-trial.report.txt)

**Comment by skoren** [comment]
The two reports you posted look pretty much identical, it looks like insufficient overlaps to get corrected reads to get an assembly. Sequel data is lower quality than RSII which is why we recommend adjusting the parameters for in on the FAQ. That's why I wanted to see the third report to see why even when you increase the error rate there was no assembly. 

It is also possible there is contamination from a larger genome in the dataset or the genome you sequenced is much larger than you expect. In that case you'd end up with low coverage and no assembly as well. You could evaluate that by mapping to similar strains to see how many reads are mapped/unmapped. You could try running multiple rounds of correction (see FAQ for nanopore 1d data). If you're able to share the reads (see FAQ again for sending us data), then we could try some experiments locally as well.

**Comment by ssilva1** [comment]
I will start by evaluating contamination from a larger genome as that seems plausible for our sample. If that doesn't work, then I will proceed with the other suggestions. 
Can you suggest a specific mapping software? 
Thanks very much.

**Comment by skoren** [comment]
I'd first tryminimap2 for mapping.

**Comment by skoren** [comment]
Any updates on this?

**Comment by ssilva1** [comment]
Yes. I depleted the host genome by mapping and then increased  the error rate to 0.25. It wasn’t perfect, but I got a very low coverage (4X) due to host contamination.

Thanks.

On 4 Jun 2018, at 17:06, Sergey Koren <notifications@github.com<mailto:notifications@github.com>> wrote:


Any updates on this?
