### ISSUE TITLE
corMinCoverage's role in the correction step

### ISSUE THREAD

**Issue by yeban** [marbl/canu#913]
I am confused about `corMinCoverage`'s role in the correction step. If `corMinCoverage=0` retains all input bases but also corrects what it can, then isn't 'what can be corrected' automatically determined and should be the same for any value of `corMinCoverage`? And if so, then is `corMinCoverage` simply a way to _additionally report uncorrected bases_ depending on the number of reads supporting a base? As an example, `corMinCoverage=2` will report 'what could be corrected' and any uncorrected bases supported by at least 2 reads.

(related #696)

**Comment by yeban** [comment]
> corMinCoverage is a lower threshold on what is considered to be corrected. ...

All this is after applying falcon-sense or pbdagcon on raw reads?

**Comment by skoren** [comment]
There is no pbdagcon support in Canu. The corrected consensus is called using a modified version of the falcon-sense algorithm but whether the bases meet corMinCoverage is computed from the alignments themselves, you don't need a consensus to count pileups.
