### ISSUE TITLE
TrioCanu read classification

### ISSUE THREAD

**Issue by gwaldbieser** [marbl/canu#919]
I am assembling a hybrid individual. I modified the E coli example scripts to produce unique kmer files from Illumina data of multiple individuals of each parental species ('blue' and 'chan') using meryl from canu-1.7. (The trio binning scripts were moved to within the existing canu-1.7 install). 

##This is an example classification run for PacBio output using BioPython version 1.59.
```
$python /home/software/canu-1.7/trioBinningScripts/classify.py blue.counts chan.counts PacBioFasta/016697_subreads.fasta > 016697.out  &
Recorded 9762864 haplpotype 0 specfic 16-mers
Recorded 20584064 haplpotype 1 specfic 16-mers
/usr/lib64/python2.7/site-packages/Bio/Seq.py:155: BiopythonWarning: Biopython Seq objects now use string comparison. Older versions of Biopython used object comparison. During this transition, please use hash(id(my_seq)) or my_dict[id(my_seq)] if you want the old behaviour, or use hash(str(my_seq)) or my_dict[str(my_seq)] for the new string hashing behaviour.
  "the new string hashing behaviour.", BiopythonWarning)

$ head -5 016697.out
Read m170406_131557_42282_c101209722550000001823275308211712_s1_p0/65/18489_31586 classified as haplotype1 due to 0.000004 but second best existed with 0.000001 all counts {0: 7.170027155965709e-07, 1: 4.420895698730824e-06}
Read m170406_131557_42282_c101209722550000001823275308211712_s1_p0/70/0_12979 classified as haplotype0 due to 0.000006 but second best existed with 0.000004 all counts {0: 6.1457375622563215e-06, 1: 4.032245527413829e-06}
Read m170406_131557_42282_c101209722550000001823275308211712_s1_p0/89/0_22704 classified as haplotype1 due to 0.000009 but second best existed with 0.000002 all counts {0: 2.4582950249025284e-06, 1: 8.550303768973901e-06}
Read m170406_131557_42282_c101209722550000001823275308211712_s1_p0/90/0_20457 classified as haplotype1 due to 0.000012 but second best existed with 0.000003 all counts {0: 3.2777266998700383e-06, 1: 1.1562342596680617e-05}
Read m170406_131557_42282_c101209722550000001823275308211712_s1_p0/94/0_10845 classified as haplotype0 due to 0.000003 but second best existed with 0.000002 all counts {0: 2.663152943644406e-06, 1: 2.1861572136580997e-06}
```

The Read Stats script asks to grep for 'chan' or 'blue' in the output but they're not in the output. The subsequent Read Extraction script doesn't require 'chan' or 'blue' so should I not worry about it?

**Comment by skoren** [comment]
I'm not sure which read stats script you mean, you should be able to take all reads assigned to haplotype0 as the first (which should be blue) and haplotype1 as chan. 

These scripts are somewhat clunky and you can just provide Canu 1.7 with the data for the haplotype individuals and it will bin the data and run the assemblies for you but since you've already classified the data you might as well finish binning it this way.

**Comment by gwaldbieser** [comment]
I was referring to these commands in the E coli example script:

# get read stats
echo "For K12 classify stats:"
cat pacbio.out |grep Read |grep K12 |awk '{if ($5 == "haplotype0") { print "CORRECT"; } else { print "WRONG"}}'|sort |uniq -c

echo ""
echo "For O157 classify stats:"
cat pacbio.out |grep Read |grep O157 |awk '{if ($5 == "haplotype0") { print "WRONG"; } else { print "CORRECT"}}'|sort |uniq -c

In my case, the second grep of ‘blue’ or ‘chan’ instead of ‘K12’ or ‘O157’ would return an empty set.
But in the subsequent extraction commands it wouldn’t make a difference.

# extract reads matching each haplotype and assemble
cat pacbio.out |grep Read |grep haplotype0 |awk '{print $2" 1 200000"}' > k12.cut
cat pacbio.out |grep Read |grep haplotype1 |awk '{print $2" 1 200000"}' > o157.cut
java -cp ../ SubFasta k12.cut pacbio.fasta > k12.fasta
java -cp ../ SubFasta o157.cut pacbio.fasta > o157.fasta
../canu/*/bin/canu -p asm -d k12 useGrid=false genomeSize=5m -pacbio-raw k12.fasta

**Comment by skoren** [comment]
Ah yes, those are optional. They're just part of the example to show approximate false positive classification rates.

**Comment by gwaldbieser** [comment]
OK, thanks. I had wondered if it was important to have the kmer index name in the header line for each read.
