### ISSUE TITLE
The difference between tgStoreDump size stats and asm size stats from contig sequences

### ISSUE THREAD

**Issue by JohnUrban** [marbl/canu#92]
I find if I do this:
$bin/tgStoreDump -contigs -bubbles -sizes -s $G -G $GKP -T $TGS 1

It gives larger size stats (i.e. NG50) than what I get size stats from the lengths of sequences in contigs.fasta

e.g. 
tgStoreDump lenContig ng50  --> 3.7 Mb 
contigs.fasta ng50    --> 3.3 Mb

Does a step after 4-unitigger (e.g. consensus) result in smaller contigs?
Any insight into this would be welcomed.

I was trying to use tgStoreDump in a loop (like Sergey suggeste din #88 ) to see how different combinations affect the results. But the results differ at this step from the final results. I suppose if the smaller trend in the final results is consistent I can still use these as a proxy…

Side note:
I was also curious about setting the repeatdetect parameter SPURIOUS_COVERAGE_THRESHOLD lower (it is at 6 now). How would that affect results? Moreover, how is REGION_END_WEIGHT selected (3rd parameter in repeatdetect) and how does that affect results?

**Comment by brianwalenz** [comment]
First, bogart is in the middle of a rather major overhaul, so everything here will be obsolete soon ("the schedule" says by this Friday, but this isn't the first time "the schedule" was totally wrong).

We suspect that a step just before output is removing some reads from the unitigs, leaving a hole with no read coverage.  Consensus (annoyingly) generates no error or warning, and generates a sequence with N's in the middle.   The N's are stripped when the sequence is output, which is rather a big Bad Thing.  I'll commit a patch to disable this filtering.

Repeat detection (currently) works by using overlap to place reads (not in the same unitig) on unitigs.  Any unitig region with reads placed in it is a candidate repeat.  SPURIOUS_COVERAGE_THRESHOLD attempted to remove the noise, discarding any region with less than some coverage reads aligning to it.  With default value of 6, it'd take 7 reads before the region is considered a repeat.  (aside: any region spanned by a read in the unitig is dropped; it's correctly assembled).

The edges of the repeat -- where to split the unitig -- are detected by looking for reads that partially align.  A pile up of more than ISECT_NEEDED_TO_BREAK will cause a unitig to be split.  REGION_END_WEIGHT artificially adds this weight to the end of the region detected above.  The result is that a region with lots of reads aligning to it (S_C_T) is split at the boundary of the region (R_E_W), and maybe internally (I_N_T_B).

This style of splitting is getting scrapped in the near future.  There were too many magic thresholds (tuning was impossible) and no filtering of diverged repeats (it was easy to oversplit).

**Comment by JohnUrban** [comment]
Thanks for the quick response, the patch, and the explanations of repeatdetect parameters. I look forward to the major overhaul.

**Comment by brianwalenz** [comment]
Me too.  :-)
