### ISSUE TITLE
Canu assembly too large, duplicated, and fragmented

### ISSUE THREAD

**Issue by hlicht** [marbl/canu#925]
Hi,

We have some issues assembling a 40 Mbp haploid fungal genome. A previous assembly of another isolate of this species assembled with Illumina reads suggests that the genome size is 40 Mbp, and running GenomeScope on the trimming/0-mercounts histogram provided the following output also suggesting a 40 Mbp genome:

```GenomeScope version 1.0
k = 21

property                      min               max               
Heterozygosity                0.391802%         0.404415%         
Genome Haploid Length         40,215,081 bp     40,258,105 bp     
Genome Repeat Length          3,894,310 bp      3,898,477 bp      
Genome Unique Length          36,320,770 bp     36,359,628 bp     
Model Fit                     96.4192%          97.5191%          
Read Error Rate               0.406735%         0.406735%         
```

We have ca. 150x Pacbio data coverage and running canu with default coverage parameters and errorrate=0.045 we get an assembly size of 74,767,702 bp (including 28 repeats of total length 1,568,312 bp) with 397 contigs.

BUSCO analysis for completenes of this assembly indicates that we have captured most of the genome, but with some repetition as nearly 40% of the single copy genes are duplicated (BUSCO output given below):

```Summarized benchmarks in BUSCO notation:
        C:97%[D:38%],F:2.0%,M:0.5%,n:1438

Representing:
        1401    Complete Single-Copy BUSCOs
        557     Complete Duplicated BUSCOs
        29      Fragmented BUSCOs
        8       Missing BUSCOs
        1438    Total BUSCO groups searched
```

We were hoping to get a reference-level assembly with this assembly and was wondering why we get such a large assembly and what we can do to improve the continouty?

Many thanks in advance for any help or pointers you can provide with.
best,
Henrik

We are using canu v. 1.7 running on a PBS grid computer cluster system with the following commands:
canu -correct -p macr -d /home/projects/cu_10081/generateddata/canu_results/macr3 genomeSize=40m -pacbio-raw /home/projects/cu_10081/data/m54071_180310_105846.fasta gnuplotTested=true gridOptions="-l walltime=10:00:00"
 
canu -trim -p macr -d /home/projects/cu_10081/generateddata/canu_results/macr3  genomeSize=40m -pacbio-corrected /home/projects/cu_10081/generateddata/canu_results/macr3/macr.correctedReads.fasta.gz gnuplotTested=true gridOptions="-l walltime=10:00:00"
 
canu -assemble -p macr -d /home/projects/cu_10081/generateddata/canu_results/macr3_erate_0.045 genomeSize=40m correctedErrorRate=0.045 -pacbio-corrected /home/projects/cu_10081/generateddata/canu_results/macr3/macr.trimmedReads.fasta.gz gnuplotTested=true gridOptions="-l walltime=10:00:00"  

I attach the report file from the final assemble command.
[macr.report.txt](https://github.com/marbl/canu/files/2031078/macr.report.txt)

**Comment by skoren** [comment]
I'm not convinced from your results this genome is haploid. The genome scope report indicates almost 0.5% heterozygosity. For comparison, a human would be 0.1%. This is just SNP-level diversity so any structural differences would contribute more. So either this genome is not haploid or you've got more than one strain in the sample. You can look at the FAQ for heterozygous genomes and try to either smash the differences away or separate even more of the genome. You'd want to then de-duplicate the assembly. There are several tools to do this, we've used https://bitbucket.org/mroachawri/purge_haplotigs with some luck.

As for contiguity, the assembly seems reasonable with an NG50 of 1.5 Mbp. Typically the fungal genome assemblies are limited by their chromosome sizes, not sure if you know the karyotype here.

**Comment by hlicht** [comment]
Thanks for your reply. You make a good point, we'll see if we can resolve this further. Many thanks again for your quick response.
Best Henrik

**Comment by peterthorpe5** [comment]
@skoren  this is really useful, from above  " ...I personally don't like the smashing approach since in most cases you'll end up with a consensus that doesn't really represent either haplotype/strain well. If you don't smash, you'd want to de-duplicate the assembly. There are several tools to do this, we've used https://bitbucket.org/mroachawri/purge_haplotigs with some luck ..." -  Would you consider adding this to your FAQ or manual, as this (currently in testing) could really help me and therefore others. Cheers Pete

**Comment by skoren** [comment]
I added a link to purge_haplotigs to the FAQ

**Comment by peterthorpe5** [comment]
Thank you  ☺
