### ISSUE TITLE
deduplicating canu assembly

### ISSUE THREAD

**Issue by ersgupta** [marbl/canu#926]
I want to deduplicate contigs in my assembly (#848). Can I simply use cdhit with 0.9 cutoff for this? or do you suggest anything else?

**Comment by ersgupta** [comment]
Just read #925 , is purge_haplotigs the answer I am looking for?

**Comment by skoren** [comment]
It's definitely not the only tool that tries to do this but it's the only one I've run and it worked reasonably well on an arabidopsis genome so I can't comment on others.

**Comment by ersgupta** [comment]
Thanks. Indeed, I will try this and few more to compare.
