### ISSUE TITLE
Canu is at the ovS step for two weeks

### ISSUE THREAD

**Issue by ksenia-krasheninnikova** [marbl/canu#929]
Hello,

I'm running Canu (Canu snapshot v1.7 +184 changes (r8876 098679d3a315131e04658b0351f9031b52a85d7d)) on a Linux server trying to assemble 4.9 Gb of pacbio reads (*.fasta.gz files) for a plant genome. The command line is

```
canu -d Vav_assembly -p Vav genomeSize=2g -maxMemory=200 -maxThreads=30 -useGrid=false -ovsMemory=128 -pacbio-raw ./*.fasta.gz
```

Looks like it's performing sorting but without producing any output for 14 days (the output files haven't been updated since May, 12), while the process in top is marked as runnable. Take last produced console output is
```
----------------------------------------
-- Overlap store bucketizer finished.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'ovS' concurrent execution on Sat May 12 11:52:37 2018 with 2223.637 GB free disk space (18 processes; 1 concurrently)

    cd correction/Vav.ovlStore.BUILDING
    ./scripts/2-sort.sh 1 > ./logs/2-sort.000001.out 2>&1
```
My question is if it's an expected behavior, or if perhaps it's the result the memory limit for ovS step?

Thank you!

**Comment by skoren** [comment]
There should be output in the log file it is pointing to, can you post that? It should load output from a bunch of bucket files, sort them in memory, and write it out. You've set a very large ovsMemory which essentially eliminated all parallelism in this step. Unless you have a good reason for the change, defaults would work better. Unfortunately, that also means you'd need to re-start the build from scratch by removing the ovlStore.BUILDING folder and re-running Canu.

**Comment by ksenia-krasheninnikova** [comment]
The contents of 2-sort.000001.out:
```
Running job 1 based on command line options.

Attempting to increase maximum allowed processes and open files.
  Changed max processes per user from 1024 to 4135043 (max 4135043).
  Max open files limited to 65536, no increase possible.


Finding overlaps.
  found  820566993 overlaps in './Vav.ovlStore.BUILDING/bucket0001/sliceSizes'.
  found  650167212 overlaps in './Vav.ovlStore.BUILDING/bucket0002/sliceSizes'.
  found  672102191 overlaps in './Vav.ovlStore.BUILDING/bucket0003/sliceSizes'.
  found  692740142 overlaps in './Vav.ovlStore.BUILDING/bucket0004/sliceSizes'.
  found   46689673 overlaps in './Vav.ovlStore.BUILDING/bucket0005/sliceSizes'.
  found  726059709 overlaps in './Vav.ovlStore.BUILDING/bucket0006/sliceSizes'.
  found  621677179 overlaps in './Vav.ovlStore.BUILDING/bucket0007/sliceSizes'.
  found  650380898 overlaps in './Vav.ovlStore.BUILDING/bucket0008/sliceSizes'.
  found  624630413 overlaps in './Vav.ovlStore.BUILDING/bucket0009/sliceSizes'.

Loading 5505014410 overlaps using 123.05 GB of allowed (-M) 124 GB memory.
```
Previously, I had canu failed at the 1-correction step with message "Can't fork: Resource temporarily unavailable". So I meant to limit the number of the forked processes by increasing the ovsMemory.

**Comment by brianwalenz** [comment]
Is the process getting CPU time?
How much swap space is available and used?
How big is the process?

The logging should have lines like the 'found' lines, but reporting that it is now 'loading' the overlaps.  That there are none is a little troubling.

You're essentially up-to-date with the latest code as far as this step goes.

**Comment by ksenia-krasheninnikova** [comment]
The process has consumed 26095:59 of CPU time by know, which keeps increasing. There is no swap space available. The process is consuming 123g memory.

Do you think it makes sense to restart with the overlaps memory parameter something in the middle, say -ovsMemory=64 or what value would you recommend?

**Comment by ksenia-krasheninnikova** [comment]
OK Thank you for help!
