### ISSUE TITLE
Canu fail in the consensus step

### ISSUE THREAD

**Issue by araceli-fernandez** [marbl/canu#932]
Hi,
I had this error in the final step, I hope you can help me to how to finish it ok

```
-- Finished on Fri May 25 20:10:33 2018 (9009 seconds) with 3233.609 GB free dis
k space
----------------------------------------
-- Using slow alignment for consensus (iteration '1').
-- Configured 69 contig and 70 unitig consensus jobs.
--
-- Consensus jobs failed, retry.
--   job utgcns/0046.cns FAILED.
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'cns' concurrent execution on Fri May 25 20:10:33 2018 with 3233.609 GB free disk space (1 processes; 5 concurrently)

    cd unitigging/5-consensus
    ./consensus.sh 115 > ./consensus.000115.out 2>&1
-- Finished on Fri May 25 20:14:59 2018 (266 seconds) with 3233.61 GB free disk space
----------------------------------------
-- Using slow alignment for consensus (iteration '2').
-- Configured 69 contig and 70 unitig consensus jobs.
--
-- Consensus jobs failed, tried 2 times, giving up.
--   job utgcns/0046.cns FAILED.
--

ABORT:
ABORT: Canu 1.6
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```
the tail of  file utgcns/0046.cns is:

```
Generated template of length 176697
Aligning reads.
Finished aligning reads.  21 failed, 433 passed.
Constructing graph
Merging graph
Calling consensus
Consensus finished successfully.  Bye.
```
I how you can help me.
Thank you in advance.

**Comment by skoren** [comment]
The job thats failing is number 115 not 46, can you post that error log? 

You can probably fix it by increasing the consensus error (see issue #729 or #907). You can either remove the consensus.sh script and re-launch canu adding ```cnsErrorRate=0.25``` or edit the consensus.sh file to replace the current error rate (the ```-e``` flag) to be 0.25 and then run ```consensus.sh 115``` from the 5-consensus folder.

**Comment by araceli-fernandez** [comment]
Hi Sergey,

Thank you so much for your help, I edited the consensus file and then run

./consensus.sh 115


generateTemplateStitch()-- generated template of length 31035, expected length 31046, -0.0354% difference.
Generated template of length 31035
Aligning reads.
Finished aligning reads.  0 failed, 18 passed.
Constructing graph
Merging graph
Calling consensus
Consensus finished successfully.  Bye.


now what I have to do?


Best regards.


________________________________
De: Sergey Koren <notifications@github.com>
Enviado: lunes, 28 de mayo de 2018 14:40:17
Para: marbl/canu
Cc: Araceli Fernández Cortés; Author
Asunto: Re: [marbl/canu] Canu fail in the consensus step (#932)


The job thats failing is number 115 not 46, can you post that error log?

You can probably fix it by increasing the consensus error (see issue #729<https://github.com/marbl/canu/issues/729> or #907<https://github.com/marbl/canu/issues/907>). You can either remove the consensus.sh script and re-launch canu adding cnsErrorRate=0.25 or edit the consensus.sh file to replace the current error rate (the -e flag) to be 0.25 and then run consensus.sh 115 from the 5-consensus folder.

**Comment by skoren** [comment]
Re-run the original Canu command and it will pickup where it left off, recognizing that all consensus jobs are complete.
