### ISSUE TITLE
Error while restarting canu after removing ovb files

### ISSUE THREAD

**Issue by ersgupta** [marbl/canu#933]
I was reading #828 where you mention we can delete ovb files ```1-overlapper/results/XXXX.ovb``` once the buckets are created. All buckets are created successfully, confirmed by the number of folders and number of sliceSizes files.

When I restart canu (```useGrid=remote```), it is still looking for the ovb files and giving error.
```
-- BEGIN CORRECTION
--
ABORT: 
ABORT: Canu 1.7
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.  
ABORT: Try restarting.  If that doesn't work, ask for help.    
ABORT: 
ABORT:   overlapper output '1-overlapper/results/000001.ovb' not found. 
ABORT:  
```

**Comment by brianwalenz** [comment]
This looks like a flaw in our state detection.  What *.sh files exist in the ovlStore scripts/ directory?  If you don't have four, make empty files so you have: 0-config.sh, 1-bucketize.sh, 2-sort.sh and 3-index.sh.  When those four are not present, canu thinks it needs to set up the overlap store building process, which looks for the ovb files.

**Comment by ersgupta** [comment]
I have all the 4 shell scripts in the folder ovlStore.BUILDING/scripts/. I am looking at what else could cause this.

**Comment by brianwalenz** [comment]
Looks like a missing ovlStore.BUILDING/1-bucketize.success file could result in this too.  This file should have been created when canu checks that all bucketizing jobs are finished.

**Comment by ersgupta** [comment]
Yes that was the case. Now I am looking why 1-bucketize.success was not created at first place. I see in subroutine overlapStoreBucketizerCheck it basically checks for bucketXXXX folder to exist or not. I have total 573 files in ovljob.files and same number of bucket folders and sliceSizes.

**Comment by ersgupta** [comment]
I think I have figured it out, please correct me if I am wrong here.

Once the buckets were created for say 1-200 ovb files, I deleted the ovb files after ensuring that the bucketXXXX folders are created and have sliceSizes file in it. Now to create 1-bucketize.success file, the subroutine overlapStoreBucketizerCheck needs to make a call to countOverlapStoreInputs which counts the number of files but also checks if ovb files exist. So, until 1-bucketize.success file is created ovb files have to be present.

**Comment by brianwalenz** [comment]
All correct.  1-bucketize.success is just an empty file to indicate that step is done.  The step is done when there is one bucket (and sliceSizes) per input file, which you've already checked.  Just create the success file (`touch 1-bucketize.success`) and continue.

I'll leave this open until I verify or fix the latest code.

**Comment by ersgupta** [comment]
Yes I figured that.

Actually sliceSizes is being checked inside 1-bucketize.sh and not in overlapStoreBucketizerCheck (which creates 1-bucketize.success) which only checks for bucketXXXX folder.

**Comment by brianwalenz** [comment]
Confirmed to not be an issue in tip.
