### ISSUE TITLE
filterCorrectionLayouts error

### ISSUE THREAD

**Issue by ersgupta** [marbl/canu#936]
I have the following error at filterCorrectionLayout step. It is something to do with some IO related issue? Any solutions?

```
-- BEGIN CORRECTION
--
-- Set corMinCoverage=4 based on read coverage of 88.
-- Computing correction layouts.
----------------------------------------
-- Starting command on Fri Jun  1 09:49:48 2018 with 272.534 GB free disk space

    cd correction/2-correction
   apps/canu-1.7/Linux-amd64/bin/filterCorrectionLayouts \
      -G  ../canu.het.gkpStore \
      -C  ../canu.het.corStore \
      -R  ./canu.het.readsToCorrect.WORKING \
      -cc 4 \
      -cl 1000 \
      -g  1400000000 \
      -c  200 \
    > ./canu.het.readsToCorrect.err 2>&1
...
$ cat canu.het.readsToCorrect.err 
tgTig::loadFromStream()-- not at a tigRecord, got bytes '' (0x00000000).
Failed to load tig 555088.    
```

**Comment by skoren** [comment]
Definitely looks like an I/O error, the question is if the data is corrupt on disk or if it was a bad read. 

You can try getting information for the same tigs using the ```tgStoreDump``` utility. Try running:
```tgStoreDump -G ../canu.het.gkpStore -T ../canu.het.corStore 1 -status``` and ```tgStoreDump -G ../canu.het.gkpStore -T ../canu.het.corStore 1 -tig 555085-555090 -layout``` from inside the 2-correction folder and see those fail as well. If it fails, you probably have to remove the 2-correction folder and the canu.het.corStore folder and re-launch Canu which will force it to re-generate the canu.het.corStore from scratch. If it doesn't fail, you can try running the above command again and see if it completes.

**Comment by ersgupta** [comment]
Thanks.

```-status``` gives ```13803985``` which I assume are the number of reads. I have ```Raw:        13803984```. ```-layout``` gives the same error as above for tig 555088.

Is it possible that ```canu.het.ovlStore``` has some issue? As I had to delete some files (#933 ) during the run. Is there a way to verify ovlStore?

**Comment by skoren** [comment]
A bad ovlStore should have been caught by Canu in the previous step but worth confirming. There is an equivalent ```ovStoreDump``` command, though its output is likely to be rather large if you dump all the reads. You could try random subsets ```ovStoreDump -G ../canu.het.gkpStore -O ../canu.het.ovlStore -d 1-1000 -coords``` varying the 1-1000 and see if you get any read errors or values that look obviously wrong (e.g. coordinates longer than your read lengths).

**Comment by ersgupta** [comment]
Cool, I will check this out and get back.

**Comment by ersgupta** [comment]
Could you help me with the column headers please?

```
         1        233  N       0     472   2608    8262  10432  0.216800
         1        406  N       0   10618  11166   11060  11612  0.123000
         1       1167  N       0    1150   2042      98   1039  0.156300
         1       1665  I       0    2157   3380   21786  20578  0.188900
         1       2268  N       0     519   3381    2998   6007  0.208300
         1       3384  I       0    3561   6180    2316    420  0.196400
         1       5776  N       0     539   2076   13907  15424  0.158700
         1       6011  I       0     649   3298    5615   2154  0.199000
         1       6258  N       0     468   2417    5369   7418  0.193600
         1       6370  N       0     497   2346    1768   3938  0.206600
```

**Comment by brianwalenz** [comment]
You got it!  Corruption usually shows as enormous values (as in billions) in the coordinates.

I'm going to guess the corStore lost a block of data somewhere.  I've seen (more and more often) corruption that is just a big block of zero-byte data.  No idea what causes this; it's spanning writes from Canu, and occurs in the middle of writes, so it's not us dropping data.

Instead of rebuilding the corStore, you can edit the 'readsToCorrect' file and remove the bad ID - do also check that you can dump the next one in the list.  You'll lose one corrected read, but save a bunch of time.

**Comment by ersgupta** [comment]
Thanks Brian. I had that in mind for a bit but did not go through with that. Unfortunately I already deleted the corStore folder and restarted canu, so one day (it took to build that) is lost but that is ok. :)

**Comment by ersgupta** [comment]
It again gave same error for a different tig though:
```
tgTig::loadFromStream()-- not at a tigRecord, got bytes 'h/' (0x682f0000).
Failed to load tig 7361716.
```
I tried ```tgStoreDump -G ../canu.het.gkpStore -T ../canu.het.corStore 1 -tig 7361717-7361718 -layout``` but it gave the same error, which probably means some random memory dump issue which causes the subsequent memory blocks to malform. Random because previously it was a different tig.

I have restarted corStore build again, hope it works now.

Have there been any changes to this code since 1.7 release? is it worth trying that out?

**Comment by ersgupta** [comment]
After 3 attempts, it works. Any idea about the source of this?

```
-- Finished on Mon Jun  4 05:00:13 2018 (630 seconds) with 162.813 GB free disk space
----------------------------------------
--                             original      original
--                            raw reads     raw reads
--   category                w/overlaps  w/o/overlaps
--   -------------------- ------------- -------------
--   Number of Reads           13424101        379883
--   Number of Bases       119974812413    3119524848
--   Coverage                    85.696         2.228
--   Median                        7159          7243
--   Mean                          8937          8211
--   N50                          13373         10788
--   Minimum                       1000             0
--   Maximum                     137402        114321
--   
--                                        --------corrected---------  ----------rescued----------
--                             evidence                     expected                     expected
--   category                     reads            raw     corrected            raw     corrected
--   -------------------- -------------  ------------- -------------  ------------- -------------
--   Number of Reads           13778464       11066325      11066325              0             0
--   Number of Bases       123058994890   109252469619   96975523221              0             0
--   Coverage                    87.899         78.037        69.268          0.000         0.000
--   Median                        7177           8492          7433              0             0
--   Mean                          8931           9872          8763              0             0
--   N50                          13301          13980         14176              0             0
--   Minimum                       1000           1000             1              0             0
--   Maximum                     137402         137402        132487              0             0
--   
--                        --------uncorrected--------
--                                           expected
--   category                       raw     corrected
--   -------------------- ------------- -------------
--   Number of Reads            2737659       2737659
--   Number of Bases        13841867642             0
--   Coverage                     9.887         0.000
--   Median                        3594             0
--   Mean                          5056             0
--   N50                           7367             0
--   Minimum                          0             0
--   Maximum                     114321             0
--   
--   Maximum Memory          2241111734
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  cor        8 GB    4 CPUs  (read correction)
--
-- Using overlaps no worse than 0.3 fraction error for correcting reads (from corErrorRate parameter).
```

**Comment by brianwalenz** [comment]
That's definitely puzzling.  Has Canu been stable on other assemblies?  What filesystem is this?

There have been massive engineering changes since 1.7, but I can't think of anything that would affect this behavior.  And to use those changes, you'd need to start the assembly over.  One benefit is that it is much easier to debug and fix problems in the latest code.

**Comment by ersgupta** [comment]
Well, before this I was able to complete only one assembly in which I did not encounter this error. Filesystem is "nfs".

**Comment by ersgupta** [comment]
Closing, as the error is resolved.
