### ISSUE TITLE
alignGFA faild with core dump

### ISSUE THREAD

**Issue by hdzierz** [marbl/canu#938]
Hi There,

I am using canu 1.7 on a 100x pacbio assembly project. Canu ran through just fine incl. the unitigging consensus step. Canu ten starts an alignment process for the final assembly using alignGFA. That process immediatelt stops with a core dump.

Any ideas?

Helge

```
------------------------------------------------------------
# LSBATCH: User input
./alignGFA.sh 0
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time   :      6.04 sec.
    Max Memory :       317 MB
    Max Swap   :       616 MB

    Max Processes  :         4

The output (if any) is above this job summary.

./alignGFA.sh: line 38: 61778 Segmentation fault      (core dumped) $bin/alignGFA -T ../species.utgStore 2 -i ./species.unitigs.gfa -o ./species.unitigs.aligned.gfa -t 16 > ./species.unitigs.aligned.gfa.err 2>&1
./alignGFA.sh: line 38: 61974 Segmentation fault      (core dumped) $bin/alignGFA -T ../species.utgStore 2 -i ./species.unitigs.gfa -o ./species.unitigs.aligned.gfa -t 16 > ./species.unitigs.aligned.gfa.err 2>&1
./alignGFA.sh: line 61: 61979 Segmentation fault      (core dumped) $bin/alignGFA -bed -T ../species.utgStore 2 -C ../species.ctgStore 2 -i ./species.unitigs.bed -o ./species.unitigs.aligned.bed -t 16 > ./species.unitigs.aligned.bed.err 2>&1
GFA alignments failed.
```

**Comment by hdzierz** [comment]
Forgot to mention the actual error message:
```
-- Reading GFA './petunia_hybrida.unitigs.gfa'.
gfa:  Loaded 1792 sequences and 12097 links.
-- Loading sequences from tigStore '../petunia_hybrida.utgStore' version 2.
tgTig::buildUngapped()--  WARNING: tried to build ungapped sequence for tigID 169 before consensus exists.

Failed with 'Segmentation fault'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::97 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
(null)::0 in (null)()
gfa/alignGFA.C::57 in _ZN8sequence3setEP5tgTig()
gfa/alignGFA.C::86 in sequences()
gfa/alignGFA.C::560 in _Z10processGFAPcjS_S_j()
gfa/alignGFA.C::929 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
```

**Comment by brianwalenz** [comment]
Are there any errors in 5-consensus *.out and/or *.err files?  This is saying that unitig 169 doesn't have a consensus sequence.  There are two steps, actually computing the consensus sequence, and then loading those results into the appropriate store.  Either could have failed, but canu should have detected it.

What files exist in *.utgStore/?  There should be two sets of two files.  Are there unitigs and contigs generated?  `tgStoreDump -G *gkpStore -T *ctgStore 1 -sizes -g <your-genome-size>` will report the size of contigs before consensus is generated.  Replace `1` with `2` for sizes after consensus; and, of course, `ctgStore` for `utgStore` to see unitigs.

If you don't care about GFA outputs, look at the end of alignGFA.sh, and make empty files for what it's looking for.
