### ISSUE TITLE
Advice for assembly- initial assembly failed

### ISSUE THREAD

**Issue by CraigMichell** [marbl/canu#941]
Hi,

I tried my first assembly yesterday with some raw oxford nanopore reads.

My initial code for the assembly is.
canu -p cephalcia -d cephalcia genomeSize=300m -nanopore-raw ./cephalcia.fastq.gz "gridOptions=-t 72:00:00" maxMemory=48 maxThreads=8
I am only using about 12X coverage, I thought that I would try the assembly out first. We will have higher coverage in my next attempts. The sequencing is average, as it is a 10 year old preserved sample. The genome size should be able 300Mbp, and the heterozygosity should be very low as it is a haploid male.

```
The assembly failed here:
 1-bucketize.22479425_190.out
Running job 190 based on SLURM_ARRAY_TASK_ID=190 and offset=0.
Removing incomplete bucket create0190
Attempting to increase maximum allowed processes and open files.
  Changed max processes per user from 4096 to 515660 (max 515660).
  Changed max open files from 2048 to 65536 (max 65536).
maxError fraction: 1.000 percent: 100.000 encoded: 4095
Bucketizing ../1-overlapper/results/000190.ovb
slurmstepd: error: Job 22479425 exceeded memory limit (3199904 > 3145728), being killed
slurmstepd: error: Exceeded job memory limit
slurmstepd: error: *** JOB 22479425 ON c902 CANCELLED AT 2018-06-05T02:50:58 ***
 ```

The other thing that i noticed when running this assembly was that the peak memory usage was about 23TB, which is huge. I have the feeling that this is most likely due to the large number of small reads in the sequencing and the error rate with the low coverage. But i am not familiar at all with assembling data from this technology.

Any advice would be welcome.
Thanks in advance.
Craig

**Comment by skoren** [comment]
The step failed due to memory so you can increase the request by adding ```gridOptionsovb="--mem=8g```. 

As for disk space, with very low coverage you get the highest sensitivity settings which will also generate more false overlaps too. I expect when you have higher coverage and don't have to use those settings, you'll end up using less space.

**Comment by CraigMichell** [comment]
Thanks for the reply, is it possible to just restart with that option?

Cheers,
Craig


Sent from my iPhone

On Jun 5, 2018, at 8:47 PM, Sergey Koren <notifications@github.com<mailto:notifications@github.com>> wrote:


The step failed due to memory so you can increase the request by adding gridOptionsovb="--mem=8g.

As for disk space, with very low coverage you get the highest sensitivity settings which will also generate more false overlaps too. I expect when you have higher coverage and don't have to use those settings, you'll end up using less space.

**Comment by skoren** [comment]
Yes, just re-run the Canu command you used before with that option added.
