### ISSUE TITLE
unitigger.jobSubmit error

### ISSUE THREAD

**Issue by a-89** [marbl/canu#943]
Hi all,

I am using canu for the first time with the objective to assemble genomes from a metagenomic sample using Nanopore data. I have searched which parameters can be modified to achieve metagenomics assembly. However, I am not able to get the contigs and unitigs files. The process gets always stuck at the same point: unitigging/4-unitigger

This is the command I have run:

canu minReadLength=1000 corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0 redMemory=60 oeaMemory=60 batMemory=200 -p BC07 -d BC07_canu genomeSize=2m -nanopore-raw BC07_filt.fastq &

And this is the error:
```
-- BEGIN ASSEMBLY
--
-- Found 1 overlap error adjustment output files.
----------------------------------------
-- Starting command on Wed Jun  6 15:18:56 2018 with 101127.517 GB free disk space

    cd unitigging/3-overlapErrorAdjustment
    /opt/rh7/canu/canu-1.7.b/bin/ovStoreBuild \
      -G ../BC07.gkpStore \
      -O ../BC07.ovlStore \
      -evalues \
      -L ./oea.files \
    > ./oea.apply.err 2>&1

-- Finished on Wed Jun  6 15:18:56 2018 (lickety-split) with 101127.517 GB free disk space
----------------------------------------
-- No report available.
--
-- Running jobs.  First attempt out of 2.
--

CRASH:
CRASH: Canu snapshot v1.7 +8 changes (r8700 9976b149f12a594b3cffc811ef4b849505608aa6)
CRASH: Please panic, this is abnormal.
ABORT:
CRASH:   Failed to submit batch jobs.
CRASH:
CRASH: Failed at /opt/rh7/canu/canu-1.7.b/bin/../lib/site_perl/canu/Execution.pm line 1101.
CRASH: 	canu::Execution::submitOrRunParallelJob('BC07', 'bat', 'unitigging/4-unitigger', 'unitigger', 1) called at /opt/rh7/canu/canu-1.7.b/bin/../lib/site_perl/canu/Unitig.pm line 294
CRASH: 	canu::Unitig::unitigCheck('BC07') called at /opt/rh7/canu/canu-1.7.b/bin/canu line 693
CRASH: 
CRASH: Last 50 lines of the relevant log file (unitigging/4-unitigger/unitigger.jobSubmit-01.out):
CRASH:
CRASH:

```
This is the information of the log file unitigger.jobSubmit-01.out:
sbatch: error: Batch job submission failed: Requested node configuration is not available

Many thanks!

Anna

**Comment by skoren** [comment]
That should be easy to fix. You specified 200g for memory for bogart but the grid scheduler is saying no node can be found to match this request. I assume you have 200gb memory nodes in the cluster but probably not in the default partition? The Canu preamble describing resources it found should list all your available compute. 

Assuming there are 200gb nodes, the question is what flags do you need to specify on your cluster to use them? Adding the option ```gridOptionsbat="<whatever flags you need to access 200gb nodes>"``` (it's probably something like ```--partition=largemem```) should let it run.

**Comment by a-89** [comment]
Many thanks for the fast answer! 

Yes, we have 200gb memory nodes in the cluster. I have just tried to add the information, but it still gives me the same error. Any other suggestions? 

Thanks again!!!

The new command:
````
canu minReadLength=1000 corOutCoverage=10000 corMhapSensitivity=high corMinCoverage=0 redMemory=60 oeaMemory=60 batMemory=200 gridOptionsBAT="-p fatnodes -m 200g" -p BC07 -d BC07_canu_2 genomeSize=2m -nanopore-raw BC07_filt.fastq &

**Comment by skoren** [comment]
Remove the 4-unitigger folder before re-running and then post the ```unitigger.jobSubmit-01.sh``` and ```unitigger.jobSubmit-01.out``` files if it happens again.

**Comment by a-89** [comment]
It worked! Many thanks for the recommendations :)
