### ISSUE TITLE
What does covStat mean?(A-stat)

### ISSUE THREAD

**Issue by Geunil** [marbl/canu#946]
Hello, Canu developers.

I appreciate your effort for this assembler.

Can you explain more about covStat in *.report file comparing with A-stat?
I read the site about A-stat you linked in previous issues.
[http://wgs-assembler.sourceforge.net/wiki/index.php/Celera_Assembler_Theory#Coverage-based_repeat_discrimination](url)
I know that covStat is the ratio of the contig being unique versus being two-copy.
How do you calculate or derive the values with the read arrival rate?

Sincerely,
Geunil

P.S. Apologize me if there's any awkward expression because I'm an undergraduate student and not native-speaker.

**Comment by skoren** [comment]
The a-stat and covStat are the same (see documentation at: http://canu.readthedocs.io/en/latest/tutorial.html#outputs). This metric comes from the original celera assembler paper: http://science.sciencemag.org/content/287/5461/2196.full#ref-24.
