### ISSUE TITLE
canu consensus error not fixed by adjusting error rate

### ISSUE THREAD

**Issue by schumerm** [marbl/canu#948]
Hello, I'm running canu on a slurm system and have run into an issue with the consensus step. I have ~70X pacbio data and have attached the slurm scripts I was submitting. I saw that the error I received is similar to others posted so tried changing to cnsErrorRate=0.25 and re-running (I confirmed that this has been updated in the consensus.sh script), but am getting the same error. I've pasted the relevant piece below and attached the full log:
```
-- BEGIN ASSEMBLY
--
-- Using slow alignment for consensus (iteration '2').
-- Configured 24 contig and 21 unitig consensus jobs.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  cns        4 GB    4 CPUs  (consensus)
--
--
-- Consensus jobs failed, tried 2 times, giving up.
--   job ctgcns/0001.cns FAILED.
--

ABORT:
ABORT: Canu 1.7
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
```
[canu.zip](https://github.com/marbl/canu/files/2088201/canu.zip)

**Comment by brianwalenz** [comment]
What's at the end of 5-consensus/*.out?  The first file is likely the failure.  The second is probably a successful result.

**Comment by schumerm** [comment]
thanks. turns out that in the subsequent runs with higher cnsErrorRate the job was getting killed for exceeding the slurm memory limit. I haven't figured out why the requested resources weren't enough but was able to run the consensus.sh script on a high memory interactive node and then the subsequent steps finished.

**Comment by brianwalenz** [comment]
The memory sizes here are complete guesses, and the algorithm doesn't know about the limit, and can't use that information even if it knew - it'll use what it needs.

I'd guess with a higher allowed error limit, it's seeing more reads aligning, and those alignments are noisier, both resulting in more memory needed.  Thanks for reporting that.
