### ISSUE TITLE
utgcns requires gcc 4.5+

### ISSUE THREAD

**Issue by igordot** [marbl/canu#95]
In the installation requirements, it says GCC 4.5+ is required for compilation only. However, `utgcns` needs GCC 4.5+ to run. I compiled with 4.7, but when I ran with 4.4, I got an error because `unitigging/5-consensus/cnsjob.files` could not be generated. Running it `utgcns` directly gives an error `/usr/lib64/libstdc++.so.6: version 'GLIBCXX_3.4.15' not found`. Switching to GCC 4.7 fixed the problem.

This isn't a major issue, but since the instructions explicitly specify "for compilation only", it seems worth pointing out.

**Comment by skoren** [comment]
The documentation means that GCC is only required if you're compiling from source, not if you use the pre-compiled binary. If you compile yourself, you need to either have the same GCC version available where you run or compile with static linking of libcxx. If you compile Canu with gcc 4.4 you would be able o run with 4.4
