### ISSUE TITLE
Update to 1.7 - no html report?

### ISSUE THREAD

**Issue by Omer-K** [marbl/canu#951]
I've update from 1.6 to 1.7.
Running something as simple as 
`canu -p Gene-canu-1.7 -d ./OutputFolder/ genomeSize=10000 -nanopore-raw ./Input.fastq`

It does not produce a final report in html as 1.6 used to. Can such report still be produced with a ceratin command?

Note sure if it's related but I should note that I get this message which I haven't seen before with 1.6:
`Use of implicit split to @_ is deprecated at /usr/local/canu-1.7/Linux-amd64/bin/../lib/site_perl/canu/Grid_Cloud.pm line 65.`

**Comment by Omer-K** [comment]
Thanks @brianwalenz.
Should I be worried regarding this notice? Honestly I'm not sure what it means.

**Comment by brianwalenz** [comment]
Nope.  It just means we (might) be using a feature in perl that won't be supported in future versions of perl.  I couldn't see anything amiss there though.
