### ISSUE TITLE
Meryl failed while correct the reads

### ISSUE THREAD

**Issue by SYSU-SinLee** [marbl/canu#955]
Hi,

Error (as follows) occurs during the assembly process.
```
-- Meryl failed, tried 2 times, giving up.
--

ABORT:
ABORT: Canu snapshot v1.7 +251 changes (r8943 be1d566a783eb4a04dda3fb4993f508b49109aef)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:

-- Finished on Fri Jun 15 09:55:33 2018 (683 seconds) with 9027.192 GB free disk space
```
The code is:
```
nohup ~/software/canu/Linux-amd64/bin/canu -correct -p bg1 -d bg genomeSize=330m -pacbio-raw m54059_170618_075501.subreads.fastq maxMemory=16 maxThreads=4 useGrid=false
```
Thanks.

**Comment by brianwalenz** [comment]
What's in `correction/0-mercounts/meryl.1.out`, or any of the other files in there?

**Comment by SYSU-SinLee** [comment]
Thanks for your reply, and the two attached files are the information in the 
correction/0-mercounts/meryl.0000001.out
 and correction/0-mercounts/bg1.ms16.estMerThresh.err. 
[bg1.ms16.estMerThresh.err.txt](https://github.com/marbl/canu/files/2105398/bg1.ms16.estMerThresh.err.txt)
[meryl.0000001.out.txt](https://github.com/marbl/canu/files/2105399/meryl.0000001.out.txt)

**Comment by brianwalenz** [comment]
Weird.  It looks like it finished successfully.  What files exit in correction/0-mercounts (e.g., `ls -l correction/0-mercounts`)?

Why the maxMemory and maxThreads?

You seem to have around 4.7 Gbp of sequence data.  That's only 13x coverage for a 330 Mbp genome.  There won't be much correction, and what it does correct will still be pretty noisy.

I can't think of anything else to try, so might as well just try running it again.  Rename 0-mercounts to 0-mercounts-old, and restart canu, adding option saveMerCounts=true.

**Comment by skoren** [comment]
Any updates?
