### ISSUE TITLE
TrioCanu meryl haplotype: Segmentation fault/ core dumped

### ISSUE THREAD

**Issue by bfr42** [marbl/canu#960]
Hello,

I am receiving an error during meryl at 0-mercounts-haplotype. This is my command:

` trioCanu -p ${Btrio1} -d ${dir} genomeSize=500m merylMemory=16g -haplotypeP1 ${P1} -haplotypeP2 ${P2} -pacbio-raw ${reads} 'useGrid=1' 'gridOptionsJobName=BTrio1' 'gridOptionsExecutive=-M 17000' 'gridEngineThreadsOption=-pe multislot THREADS' 'gridEngineMemoryOption=-l m_mem_total=MEMORY' 'gridEngineSubmitCommand=qsub -P den -l idle=1' `

Version: Canu 1.7

From meryl.1.out:
 ```
Allocating 128MB for counting the size of each bucket.
 Allocating 128MB for counting the size of each bucket.
/var/spool/codine/suc01008/job_scripts/2924064: line 29: 54502 Killed                  $bin/meryl -B -C -L 2 -v -m 20 -threads 16 -memory 13107 -s ../haplotypeP2.gkpStore -o ./haplotypeP2.ms20.WORKING
/var/spool/codine/suc01008/job_scripts/2924064: line 58: 55511 Segmentation fault      (core dumped) $bin/estimate-mer-threshold -h ./haplotypeP2.ms20.histogram -c 142 > ./haplotypeP2.ms20.estMerThresh.out.WORKING 2> ./haplotypeP2.ms20.estMerThresh.err
```

From haplotypeP2.ms20.estMerThresh.err:

```
Failed with 'Segmentation fault'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::97 in _Z17AS_UTL_catchCrashiP7siginfoPv()
(null)::0 in (null)()
(null)::0 in (null)()
meryl/estimate-mer-threshold.C::115 in _Z13loadHistogramP8_IO_FILERmS1_S1_RjRPj()
meryl/estimate-mer-threshold.C::201 in main()
(null)::0 in (null)()
(null)::0 in (null)()
```

In most runs parent1 fails also with the same error, but after several restarts meryl finally finished the first parent. However, meryl comes not very far for parent2 and fails every time. I tried out several Memory options:

`merylMemory=16g & 'gridOptionsExecutive=-M 17000' `
`merylMemory=250g & 'gridOptionsExecutive=-M 25100'`'
`merylMemory=500g & 'gridOptionsExecutive=-M 500000'`'
`merylMemory=1000g & 'gridOptionsExecutive=-M 250000' `

Only `merylMemory=16g & 'gridOptionsExecutive=-M 17000'` was able to let meryl  finish for parent1.
I also tried the recommended parameters (without using merylMemory=X & 'gridOptionsExecutive=-M X' ): 

`gridOptionsExecutive="--mem=250g" gridOptionsMeryl='--partition=largemem --mem=1000g'`

But I get the following error:
```qsub: ERROR! invalid option argument "--partition=largemem" ```
And when only using 'gridOptionsExecutive="--mem=250g"' it also complains:
```qsub: ERROR! invalid option argument "--mem=250g"```

I also thought of using the Canu Version from the Master-branch (16.06.2018). I am only able to compile Canu with changing `cp -pf` in the Makefile to `install -c` (our support told me to do so). Canu itself runs fine, yet trioCanu fails immediately:
```
-- BEGIN HAPLOTYPING
--
Undefined subroutine &main::createSequenceStore called at /prj/programs/canu-1.7-master/Linux-amd64/bin/trioCanu line 407.
statler:/vol/Assembly/canu> Undefined subroutine &main::createSequenceStore called at /prj/programs/canu-1.7-master/Linux-amd64/bin/trioCanu line 407.
```

**Comment by skoren** [comment]
The recommended parameters need to be updated for your grid. Something like ```'gridOptionsExecutive=-M 250000' 'gridOptionsMeryl=-M 250000'```, assuming you don't need any other flags to use more than 250g on a node on your cluster. Changing merylMemory won't matter because it doesn't affect the request to the grid and the grid manager is what is killing your jobs.
