### ISSUE TITLE
more information about the corMhapSens parameter.

### ISSUE THREAD

**Issue by cokelaer** [marbl/canu#965]
I would like to get additional information concerning the MhapSensitivity parameter. I could find documentation on the RTD page here:

https://canu.readthedocs.io/en/latest/parameter-reference.html?highlight=corMhap#overlapper-configuration-mhap-algorithm

I would like to know more precisely what is happening when we use the low/normal/high option ? 
thanks in advance

**Comment by skoren** [comment]
It adjusts the number of hashes used as well as the minimum identity and number of k-mer matches. You can see the exact MHAP parameters used for each setting in https://github.com/marbl/canu/blob/master/src/pipelines/canu/OverlapMhap.pm lines 113-130.

**Comment by cokelaer** [comment]
thanks that will do it :+1:
