### ISSUE TITLE
Canu failed during trimming

### ISSUE THREAD

**Issue by ggargAUS** [marbl/canu#966]
I am trying to run Canu for a large genome assembly (genome size ~600 Mb) using Pac bio reads on a slurm based HPC system. It's aborting at trimming step.

 Overlap store bucketizer jobs failed.

Command used:
canu -p BGA \
        -d BGA_2 \
        genomeSize=603m \
        useGrid=true gridEngine=slurm \
        gridOptions="--time=160:00:00" \
        -pacbio-raw BGA_pacbio_raw.fastq

Check the report and log from Canu attached
[BGA.report.txt](https://github.com/marbl/canu/files/2130300/BGA.report.txt)
[canu.out.txt](https://github.com/marbl/canu/files/2130301/canu.out.txt)

Please help. Thanks in advance for help

**Comment by skoren** [comment]
The logs in ```trimming/BGA.ovlStore.BUILDING/logs/*_41.out``` or similar should have more information on why the jobs are failing.

**Comment by ggargAUS** [comment]
It's showing following error :

Running job 41 based on SLURM_ARRAY_TASK_ID=41 and offset=0.
Removing incomplete bucket create0041

Attempting to increase maximum allowed processes and open files.
  Changed max processes per user from 514751 to 514763 (max 514763).
  Max open files limited to 51200, no increase possible.

maxError fraction: 1.000 percent: 100.000 encoded: 4095
Bucketizing ../1-overlapper/001/000041.ovb
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Failed with 'Aborted'; backtrace (libbacktrace):
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
../../../../libstdc++-v3/libsupc++/vterminate.cc::95 in _ZN9__gnu_cxx27__verbose_terminate_handlerEv()
../../../../libstdc++-v3/libsupc++/eh_terminate.cc::47 in _ZN10__cxxabiv111__terminateEPFvvE()
../../../../libstdc++-v3/libsupc++/eh_terminate.cc::57 in _ZSt9terminatev()
../../../../libstdc++-v3/libsupc++/eh_throw.cc::93 in __cxa_throw()
../../../../../libstdc++-v3/src/c++11/functexcept.cc::54 in _ZSt17__throw_bad_allocv()
src/jemalloc_cpp.cpp::72 in _Z7newImplILb0EEPvm()
(null)::0 in (null)()
(null)::0 in (null)()
../sysdeps/x86_64/start.S::118 in (null)()
(null)::0 in (null)()
/cm/local/apps/slurm/var/spool/job16453656/slurm_script: line 174:  4574 Aborted                 (core dumped) $bin/ovStoreBucketizer -O . -G ../BGA.gkpStore -C ./config -job $jobid -i $jn

**Comment by brianwalenz** [comment]
This has almost always been caused by a corrupt overlapper output 'ovb' file.

Remove `trimming/1-overlapper/001/000041.*` (two files) then run `overlap.sh 41` from in the trimming/1-overlapper directory.  See *jobSubmit*sh for a template to submit the jobs to slurm (change the -a parameter to be just '41').

When that finishes, restart canu.

**Comment by ggargAUS** [comment]
Thanks for your help. Canu moved to next step on restarting after overlap.sh runs.
