### ISSUE TITLE
CANU failing due to not finding File::Path 2.08 (using perl 5.22)

### ISSUE THREAD

**Issue by jmartin77777** [marbl/canu#967]
I'm having trouble getting CANU to run.  I'm working under Linux using 
CANU v1.7 (binary distribution):

```
canu --version
Canu 1.7
```

The command I'm running is this:

```
<local_path>/canu-1.7/Linux-amd64/bin/canu -p 
Trichostrongylus_colubriformis_CANU_default -d 
/gscmnt/gc2732/mitrevalab/USDA_Zarlenga/t_colubriformis/180530_assembly_and_annotation_PacBio_sequel_data/CANU_ASSEMBLY/default_CANU 
genomeSize=400m correctedErrorRate=0.065 corMhapSensitivity=normal 
-pacbio-raw 
/gscmnt/gc2732/mitrevalab/USDA_Zarlenga/t_colubriformis/180530_assembly_and_annotation_PacBio_sequel_data/FASTQ_from_smrt_link/reads.fastq 
gnuplotTested=true
```

I am running it with the pre-requisites provided by a docker container 
(although I have also run it in a docker container that includes CANU 
itself + the pre-requisites and get the same error). The container is 
running Ubuntu linux 16.04, and has all the listed pre-reqs including 
perl 5.22.  When I interactively log into the container I am able to run 
perl and invoke the same File::Path statement from the CANU executable:

```
perl
use File::Path 2.08 qw(make_path remove_tree);
```

and it doesn't complain.  So I'm not sure why it says it can't find that 
library when I run the full command.   I am using bsub (LSF) with a 
240Gb memory allocation to launch the command in a docker instance.   I 
am pretty sure the perl compiler in your CANU executable should be 
seeing the correct perl from inside the container ( /usr/bin/env perl).  
The error message I'm seeing that points the finger at File::Path is 
from the file:

canu-scripts/canu.01.out

and the exact error message is:

```
File::Path version 2.08 required--this is only version 2.07_03 at 
/gscmnt/gc2732/mitrevalab/TOOLS_Mitreva/SOFTWARE/CANU/canu-1.7/Linux-amd64/bin/canu 
line 48.
BEGIN failed--compilation aborted at 
/gscmnt/gc2732/mitrevalab/TOOLS_Mitreva/SOFTWARE/CANU/canu-1.7/Linux-amd64/bin/canu 
line 48.
```

Any help or advice would be appreciated.

Thanks,
John Martin

**Comment by brianwalenz** [comment]
I will guess the qsub isn't doing the same initialization you get when you login interactively.  An easy way to test this is to modify canu.01.sh to include:
```
echo $PATH
/usr/bin/env perl --version
```
and submit that as a normal job.

You can force Canu to use a specific perl with option `perl=/some/path/to/the/correct/perl`.

You _might_ be able to use 2.07_03 instead of 2.08.  You'd need to modify all the perl files to remove the version requirement, then reinstall canu.  I'm not sure exactly what https://perldoc.perl.org/File/Path.html#NOTES is warning about in 'API changes'.  We're not using the buggy mkpath/rmtree interface, so the only issue would be if make_path/remove_tree are not available in 2.07.

**Comment by jmartin77777** [comment]
The perl version reported when I ran canu.01.sh with the diagnostic lines  is:

```
This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi
(with 58 registered patches, see perl -V for more detail)
```

Even if it was a problem with the ENV of the docker container, our workstation ENV uses  perl 5.8.7 which seems to be able to find File::Path 2.08.   I will go ahead and try repeating my command with an explicit path to perl in case it is an ENV issue that we just haven't thought of yet.  If you have any other suggestions I could try please let me know.


Thanks,
John

**Comment by jmartin77777** [comment]
Canu didn't understand the argument I added to force it to use the expected perl (5.22.1):

```
ARGUMENT ADDED: perl=/usr/bin/perl

canu -p Trichostrongylus_colubriformis_CANU_default -d /gscmnt/gc2732/mitrevalab/USDA_Zarlenga/t_colubriformis/180530_assembly_and_annotation_PacBio_sequel_data/CANU_ASSEMBLY/default_CANU perl=/usr/bin/perl genomeSize=400m correctedErrorRate=0.065 corMhapSensitivity=normal -pacbio-raw /gscmnt/gc2732/mitrevalab/USDA_Zarlenga/t_colubriformis/180530_assembly_and_annotation_PacBio_sequel_data/FASTQ_from_smrt_link/reads.fastq gnuplotTested=true
```
And when I look through the documentation I don't see 'perl' as a listed argument.  Can you tell me if I'm using it incorrectly?

Thanks,
John

**Comment by jmartin77777** [comment]
I was eventually able to get the script to use the correct version of perl but its still failing during the correction overlap step.  Now it keeps dying and giving me the message:

ABORT:
ABORT: Canu 1.7
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:

I've tried restarting and it continues to fail with this  message.  I could use some advice on how to troubleshoot this.

Thanks,
John

p.s. I wasn't sure if I should continue in this same thread or start a new one, since this isn't really the original problem anymore...

**Comment by skoren** [comment]
There should be more details in the log that specify exactly which command failed, could you post that or the full output of the run?

**Comment by jmartin77777** [comment]
I'm not sure I know which logfile you mean, but here is the contents of canu.03.out:

...
-- Canu 1.7
--
-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
-- 
-- Read and contig alignments during correction, consensus and GFA building use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
--   Li H.
--   Minimap and miniasm: fast mapping and de novo assembly for noisy long sequences.
--   Bioinformatics. 2016 Jul 15;32(14):2103-10.
--   http://doi.org/10.1093/bioinformatics/btw152
-- 
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_45' (from 'java').
-- Detected 24 CPUs and 95 gigabytes of memory.
-- Detected LSF with 'bsub' binary in /opt/lsf9/9.1/linux2.6-glibc2.3-x86_64/bin/bsub.
-- Warning: unknown memory units for grid engine LSF assuming KB
-- 
-- Found   1 host  with  32 cores and 1023 GB memory under LSF control.
-- Found   1 host  with  16 cores and  255 GB memory under LSF control.
-- Found   1 host  with  12 cores and  383 GB memory under LSF control.
-- Found 108 hosts with   8 cores and   31 GB memory under LSF control.
-- Found   8 hosts with  12 cores and   94 GB memory under LSF control.
-- Found   1 host  with  12 cores and   79 GB memory under LSF control.
-- Found   1 host  with   2 cores and    3 GB memory under LSF control.
-- Found   3 hosts with  12 cores and   87 GB memory under LSF control.
-- Found  32 hosts with  28 cores and  503 GB memory under LSF control.
-- Found  57 hosts with   8 cores and   47 GB memory under LSF control.
-- Found  32 hosts with  24 cores and  377 GB memory under LSF control.
-- Found   1 host  with   4 cores and    3 GB memory under LSF control.
-- Found   2 hosts with   8 cores and    7 GB memory under LSF control.
-- Found   2 hosts with   4 cores and    7 GB memory under LSF control.
-- Found  53 hosts with  12 cores and   95 GB memory under LSF control.
-- Found  31 hosts with  20 cores and  377 GB memory under LSF control.
-- Found   2 hosts with   1 core  and    1 GB memory under LSF control.
-- Found   1 host  with  32 cores and  511 GB memory under LSF control.
-- Found   8 hosts with  32 cores and  251 GB memory under LSF control.
-- Found   1 host  with  20 cores and  283 GB memory under LSF control.
-- Found   1 host  with   8 cores and  125 GB memory under LSF control.
-- 
-- On LSF detected memory is requested in KB
-- 
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl     64 GB   16 CPUs  (k-mer counting)
-- Grid:  cormhap   13 GB    4 CPUs  (overlap detection with mhap)
-- Grid:  obtovl     8 GB    4 CPUs  (overlap detection)
-- Grid:  utgovl     8 GB    4 CPUs  (overlap detection)
-- Grid:  ovb        2 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       16 GB    1 CPU   (overlap store sorting)
-- Grid:  red        7 GB    4 CPUs  (read error detection)
-- Grid:  oea        4 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat       64 GB    8 CPUs  (contig construction)
-- Grid:  gfa        8 GB    8 CPUs  (GFA alignment and processing)
--
-- In 'Trichostrongylus_colubriformis_CANU_default.gkpStore', found PacBio reads:
--   Raw:        2976983
--   Corrected:  0
--   Trimmed:    0
--
-- Generating assembly 'Trichostrongylus_colubriformis_CANU_default' in '/gscmnt/gc2732/mitrevalab/USDA_Zarlenga/t_colubriformis/180530_assembly_and_annotation_PacBio_sequel_data/CANU_ASSEMBLY/default_CANU'
--
-- Parameters:
--
--  genomeSize        400000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.0650 (  6.50%)
--    utgOvlErrorRate 0.0650 (  6.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.0650 (  6.50%)
--    utgErrorRate    0.0650 (  6.50%)
--    cnsErrorRate    0.0650 (  6.50%)
--
--
-- BEGIN CORRECTION
--
--
-- Mhap precompute jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/blocks/000056.dat FAILED.
--

ABORT:
ABORT: Canu 1.7
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:

------------------------------------------------------------
Sender: LSF System <lsf9@blade13-1-9.gsc.wustl.edu>
Subject: Job 5710047: <canu_Trichostrongylus_colubriformis_CANU_default> in cluster <lsfcluster9> Exited

Job <canu_Trichostrongylus_colubriformis_CANU_default> was submitted from host <blade13-2-3.gsc.wustl.edu> by user <jmartin> in cluster <lsfcluster9>.
Job was executed on host(s) <blade13-1-9.gsc.wustl.edu>, in queue <long>, as user <jmartin> in cluster <lsfcluster9>.
</gscuser/jmartin> was used as the home directory.
</gscmnt/gc2732/mitrevalab/USDA_Zarlenga/t_colubriformis/180530_assembly_and_annotation_PacBio_sequel_data/CANU_ASSEMBLY/default_CANU> was used as the working directory.
Started at Tue Jul 10 01:17:09 2018
Results reported on Tue Jul 10 01:17:11 2018

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
canu-scripts/canu.03.sh
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :               0.47 sec.
    Total Requested Memory : 4000.00 MB
    Delta Memory :           -
    (Delta: the difference between Total Requested Memory and Max Memory.)

The output (if any) is above this job summary.
...

Let me know if you meant a different log file

**Comment by skoren** [comment]
Yep, that's the one. Looks like one of the overlapping jobs failed, what's the output in ```correction/1-overlapper/*56.out```?

**Comment by jmartin77777** [comment]
It does show a problem (precompute.56.out):

```
Running job 56 based on LSB_JOBINDEX=56 and offset=0.
Dumping reads from 2145001 to 2184000 (inclusive).

Starting mhap precompute.

Exception in thread "main" java.lang.UnsupportedClassVersionError: edu/umd/marbl/mhap/main/MhapMain : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
Could not find the main class: edu.umd.marbl.mhap.main.MhapMain. Program will exit.
Mhap failed.

------------------------------------------------------------
Sender: LSF System <lsf9@blade13-3-16.gsc.wustl.edu>
Subject: Job 5707834[56]: <cormhap_Trichostrongylus_colubriformis_CANU_default[1-77]> in cluster <lsfcluster9> Exited

Job <cormhap_Trichostrongylus_colubriformis_CANU_default[1-77]> was submitted from host <blade13-3-1.gsc.wustl.edu> by user <jmartin> in cluster <lsfcl
uster9>.
Job was executed on host(s) <4*blade13-3-16.gsc.wustl.edu>, in queue <long>, as user <jmartin> in cluster <lsfcluster9>.
</gscuser/jmartin> was used as the home directory.
</gscmnt/gc2732/mitrevalab/USDA_Zarlenga/t_colubriformis/180530_assembly_and_annotation_PacBio_sequel_data/CANU_ASSEMBLY/default_CANU/correction/1-over
lapper> was used as the working directory.
Started at Mon Jul  9 22:40:38 2018
Results reported on Mon Jul  9 22:40:45 2018

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
./precompute.sh 0
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :               2.50 sec.
    Total Requested Memory : 4000.00 MB
    Delta Memory :           -
    (Delta: the difference between Total Requested Memory and Max Memory.)

The output (if any) is above this job summary.

Running job 56 based on LSB_JOBINDEX=56 and offset=0.
Dumping reads from 2145001 to 2184000 (inclusive).

Starting mhap precompute.

Exception in thread "main" java.lang.UnsupportedClassVersionError: edu/umd/marbl/mhap/main/MhapMain : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
Could not find the main class: edu.umd.marbl.mhap.main.MhapMain. Program will exit.
Mhap failed.

------------------------------------------------------------
Sender: LSF System <lsf9@blade13-1-9.gsc.wustl.edu>
Subject: Job 5710045[56]: <cormhap_Trichostrongylus_colubriformis_CANU_default[55-56]> in cluster <lsfcluster9> Exited

Job <cormhap_Trichostrongylus_colubriformis_CANU_default[55-56]> was submitted from host <blade13-2-3.gsc.wustl.edu> by user <jmartin> in cluster <lsfc
luster9>.
Job was executed on host(s) <4*blade13-1-9.gsc.wustl.edu>, in queue <long>, as user <jmartin> in cluster <lsfcluster9>.
</gscuser/jmartin> was used as the home directory.
</gscmnt/gc2732/mitrevalab/USDA_Zarlenga/t_colubriformis/180530_assembly_and_annotation_PacBio_sequel_data/CANU_ASSEMBLY/default_CANU/correction/1-over
lapper> was used as the working directory.
Started at Tue Jul 10 00:20:32 2018
Results reported on Tue Jul 10 00:20:55 2018

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
./precompute.sh 0
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :               2.50 sec.
    Max Memory :             38.92 MB
    Average Memory :         38.92 MB
    Total Requested Memory : 4000.00 MB
    Delta Memory :           3961.08 MB
    (Delta: the difference between Total Requested Memory and Max Memory.)
    Max Swap :               156 MB
    Max Processes :          4
    Max Threads :            5

The output (if any) is above this job summary.
```

I did restart this CANU after the first try and it failed with the same msg both times.  Sometimes I wonder if maybe some of our compute nodes are bad, but this same batch hit 2 different blades and failed both times so I wonder if its something with the contents of the batch itself

**Comment by skoren** [comment]
It's definitely a compute node issue, it seems some have an old JVM so you're getting different versions of java on different nodes. The majority are OK since most of your jobs finished but some aren't. You could probably make it run by specifying a full path to java with ```java=/path/to/java/bin``` as an option to Canu. You can manually edit the precompute.sh file to have the full java path and re-run Canu and it should finish that job.

**Comment by brianwalenz** [comment]
I added some logging to the output of each job to report the perl, java and canu in use for that job.  Not much else I can do.
