### ISSUE TITLE
TrioBinning - Thresholding

### ISSUE THREAD

**Issue by fbemm** [marbl/canu#969]
I successfully ran TrioCanu on two F1's. For both sets one of the haplotypes look pretty god. The second one is always a bit worse (in terms of N50 and total length). Reads are unequally distributed between the two haplotypes to some extent. Also the thresholding looks different. Could you guys share how the thresholding should look like? I added two examples below.

Haplotype 1

```
RAW MER COUNTS:
  distinct:   2918112078 (different kmer sequences)
  unique:     2257385245 (single-copy kmers)
  total:     34532885589 (kmers in sequences)

Set maxCount to 1094 (4274 kmers), which will cover 99.75% of distinct mers and 75.70% of all mers.
Average number of kmers between count 1069 and 1120 is 4609469
Found break in kmer coverage at 64450
Set maxCount to 16307 (38 kmers), which will cover 99.99% of distinct mers and 90.00% of all mers.
```

Haplotype 2

```
RAW MER COUNTS:
  distinct:   3680674341 (different kmer sequences)
  unique:     2929870021 (single-copy kmers)
  total:     52281482642 (kmers in sequences)

Set maxCount to 1797 (890 kmers), which will cover 99.75% of distinct mers and 72.87% of all mers.
Average number of kmers between count 1772 and 1823 is 1625881
Found break in kmer coverage at 81540
Set maxCount to 32614 (15 kmers), which will cover 99.99% of distinct mers and 90.00% of all mers.
```

**Comment by skoren** [comment]
It's normal for the two haplotypes to have slightly different assemblies because they are independent assemblies. As long as the NG50s are in the same range (e.g. within 10-15% of each other). The size can also vary especially if you have the heterogametic sex since one sex chromosome is often shorter than the other, the haplotype with it will have a shorter assembly. For example, the cattle F1 sire haplotype was 100mb shorter because it has only the Y chromosome while the dam had the X and mitochondria. The sex chromosomes also differ in repeat content which again affects the assembly stats.

Nothing in the above thresholding seems off, here is the example from the cattle:
HAP1:
```
RAW MER COUNTS:
  distinct:   3916926862 (different kmer sequences)
  unique:      915467555 (single-copy kmers)
  total:    106210684142 (kmers in sequences)

Set maxCount to 330 (25000 kmers), which will cover 99.75% of distinct mers and 79.65% of all mers.
Average number of kmers between count 305 and 356 is 8284529
Found break in kmer coverage at 113046
Set maxCount to 32401 (2 kmers), which will cover 100.00% of distinct mers and 90.00% of all mers.
```

HAP2:
```
RAW MER COUNTS:
  distinct:   3723140516 (different kmer sequences)
  unique:      790888805 (single-copy kmers)
  total:    102873630908 (kmers in sequences)

Set maxCount to 340 (21015 kmers), which will cover 99.75% of distinct mers and 75.87% of all mers.
Average number of kmers between count 315 and 366 is 7240686
Found break in kmer coverage at 151331
Set maxCount to 137602 (1 kmers), which will cover 100.00% of distinct mers and 90.00% of all mers.
```

**Comment by fbemm** [comment]
Both F1 are plants with a target genome size of 500Mb. One F1 assembles into 460 and into 510Mb. So the 10-15% would match. N50s 1Mb and 2Mb, also that is not dramatic I guess. Numbers are similar for the second F1. Only dramatic difference is that the read set is 25% smaller. Also there is always one haplotype that has a 5-10% lower completeness. The "better" one shows higher duplication rates. Thanks for sharing the thresholding results. Guess thresholding is not the "problem" here.

**Comment by skoren** [comment]
There is some thresholding to choose the k-mers to use for classification. It's likely the thresholds are slightly different between the haplotypes which explains difference in the size of the read sets. 

There should be a ```*.threshold``` file in each of the haplotype mercount folders that tells you what was used. You should be able to edit it manually if you wanted to (set the first value to the minimum count that isn't noise and max can be quite high like 1000) and remove the classified reads and have it re-generate the read sets with your custom thresholds.

**Comment by fbemm** [comment]
Looking at the thresholds I can imaging the difference between the assembly. H1 is 13/83 and H2 is 7/46. The high cutoff from the latter is still within the haploid peak of the k-Mer distribution. Going to report back on the assemblies with the adjusted thresholds.
