### ISSUE TITLE
SGE modules

### ISSUE THREAD

**Issue by igordot** [marbl/canu#97]
Canu is designed to run on grid environments and will submit itself to the default queue with default time options. You can specify parameters for how you launch jobs, but there does not seem to be a way to control modules (environment modules, not Canu modules) that are loaded within jobs (or modify the environment in general). Is that correct?

**Comment by skoren** [comment]
The only interaction Canu has with the system is through qsub. You can pass arbitrary parameters to qsub using gridOptions including -V which should preserve your current environment variables through to the job or -v which can define a specific variable. You cannot have Canu run some arbitrary commands before running its job.

**Comment by igordot** [comment]
Thanks for clarifying! That worked.

On a related note, do you know why the maxThreads parameter is not being recognized? I specified `maxThreads=64`, but it says my jobs will get a max of 16 threads despite detecting more resources being available:
```
[]$ ~/software/canu-1.2/Linux-amd64/bin/canu \
> maxMemory=32 \
> maxThreads=64 \
> useGrid=1 "gridOptions=-V" gridEngineMemoryOption="-l mem_free=MEMORY -l mem_token=MEMORY" \
> -p ecoli -d ecoli-oxford-q-64 \
> genomeSize=4.8m \
> -nanopore-raw oxford.fasta
-- Detected Java(TM) Runtime Environment '1.8.0_05' (from 'java').
-- Detected 32 CPUs and 126 gigabytes of memory.
-- Detected Sun Grid Engine in '/cm/shared/apps/sge/2011.11p1/default'.
-- Detected Grid Engine environment 'threaded'.
-- User supplied Grid Engine consumable '-l mem_free=MEMORY -l mem_token=MEMORY'.
-- 
-- Found   1 host  with  64 cores and 1009 GB memory under Sun Grid Engine control.
-- Found  69 hosts with  32 cores and  126 GB memory under Sun Grid Engine control.
--
-- Allowed to run under grid control, and use up to   4 compute threads and   15 GB memory for stage 'bogart (unitigger)'.
-- Allowed to run under grid control, and use up to  16 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run under grid control, and use up to  16 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run under grid control, and use up to  16 compute threads and    6 GB memory for stage 'mhap (overlapper)'.
-- Allowed to run under grid control, and use up to   4 compute threads and    8 GB memory for stage 'read error detection (overlap error adjustment)'.
-- Allowed to run under grid control, and use up to   1 compute thread  and    2 GB memory for stage 'overlap error adjustment'.
-- Allowed to run under grid control, and use up to   4 compute threads and   15 GB memory for stage 'utgcns (consensus'.
-- Allowed to run under grid control, and use up to   1 compute thread  and    3 GB memory for stage 'overlap store parallel bucketizer'.
-- Allowed to run under grid control, and use up to   1 compute thread  and    3 GB memory for stage 'overlapper'.
-- Allowed to run under grid control, and use up to   8 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run under grid control, and use up to   8 compute threads and    8 GB memory for stage 'overlapper'.
-- Allowed to run under grid control, and use up to   4 compute threads and    8 GB memory for stage 'meryl (k-mer counting)'.
-- Allowed to run under grid control, and use up to   4 compute threads and   15 GB memory for stage 'falcon_sense (read correction)'.
-- Allowed to run under grid control, and use up to  16 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run under grid control, and use up to  16 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
-- Allowed to run under grid control, and use up to  16 compute threads and    6 GB memory for stage 'minimap (overlapper)'.
```

**Comment by skoren** [comment]
The maxThreads is just that, a maximum limit. It can still use less threads per job. Some parts submit large array jobs while others run on a single node, either multi-or single threaded. Canu will auto-configure to maximize the number of parallel jobs it can run within some size limits which are based on genome size. In your case, if you ran with 64 threads it could only run on one machine whereas with the settings it is using, it can run on any of the 70 hosts. You can overwrite the auto-configure if you really want to use more threads by setting the individual thread parameters:
```
canu -options |grep -i thread
```

**Comment by igordot** [comment]
I understand it wouldn't get all 64, but there are a bunch of nodes with 32 cores and yet the maximum it's using is 16.

**Comment by brianwalenz** [comment]
These limits are hard coded based on our experience with assemblies of various sizes.  Only a few algorithms can make effective use of lots of cores, and on smaller data sets, the additional cores aren't terribly useful.  Worse, on loaded grids, asking for more resources usually means your job is stuck in queue instead of computing.

All the options for tuning are exposed (memory, threads and various batch sizes), have fun!
