### ISSUE TITLE
Canu Error 'failed to create the overlap store'

### ISSUE THREAD

**Issue by AsclepiusDoc** [marbl/canu#971]
**Remove this text before submitting your issue!**
Hello Canu,

I'm currently running the command:

`canu -p duster_lib_x0_y7_ESM -d $DUSTER_LIB_X0_Y7_ANALYSIS/duster_x0_y7_ESM/canu_assembly useGrid=false correctedErrorRate=0.16 genomeSize=17g -nanopore-raw $DUSTER_LIB_X0_Y7_ANALYSIS/duster_x0_y7_ESM/porechop_fastq/porechop_trimmed_output.fastq`

I have ran this command twice to see if the error will go away but, I keep getting 'failed to create the overlap store'.

Here are the output files that were generated.
[slurm-3146888.out.txt](https://github.com/marbl/canu/files/2134138/slurm-3146888.out.txt)
[duster_lib_x0_y7_ESM.ovlStore.err.txt](https://github.com/marbl/canu/files/2134139/duster_lib_x0_y7_ESM.ovlStore.err.txt)

The canu  version that I'm using currently is Canu snapshot v1.7.

Currently, I am running Canu on a Linux system using SLURM on the Pittsburgh Supercomputer BRIDGES.

Kind Regards,

Alex Lim

**Comment by skoren** [comment]
Before you spend too much time debugging this, based on your genome size and number of reads, I presume you have less than 5-fold coverage here? That isn't going to assemble and most likely won't generate much in terms of corrected reads.

The error is indicating a write failure:
```
safeWrite()-- Write failure on ovFile::writeBuffer: Input/output error
```
So this is likely an issue with your cluster FS.

This is a rather large genome to run on a single node like you're doing. Typically, the store is built in parallel instead. You could either let it run on the grid (remove ```useGrid=false```) or force it to use the parallel build on a single node (```ovsMethod=forceparallel```). In either case, you can increase the sort memory with ```ovsMemory=32``` which will increase the number of sort jobs and hopefully the number of simultaneous open files. 

You could also update to the latest code in the repo which has a different store construction algorithm but you'll have to re-launch the assembly from scratch.

**Comment by AsclepiusDoc** [comment]
Hello Sergey,

You mentioned that we won't generate any type of assembly. At what coverage
can we expect to generate some type of assembly in terms of many contigs?

Also, thank you for your help I will update Canu and see if that works.

Kind Regards,

Alex Lim

**Comment by brianwalenz** [comment]
Lots of advice at http://canu.readthedocs.io/en/latest/faq.html.
