### ISSUE TITLE
Problems with non-terminal repeats

### ISSUE THREAD

**Issue by nevergerome** [marbl/canu#972]
I've been doing plasmid-enriched MinION read assemblies and I understand that Canu causes a terminal repeat, which I can easily cut out.

However, I've been having problems with non-terminal direct repeats in large plasmids. One is ~20kb long and starts immediately after the last. Through comparison to a reference, I can tell that this is a false repeats. In this case, annotation has shown me that it is an entire transposon, directly and falsely repeated (see below):

![screenshot6560728967717146161](https://user-images.githubusercontent.com/37619941/41915432-9ba58556-794d-11e8-8d94-6445fd69fd01.png)

Which parameters could I alter to prevent these non-terminal direct repeats from happening? I've tried increasing the minimum overlap length parameter and min read length. Or do I simply need longer reads?

**Comment by skoren** [comment]
I assume by terminal repeats you mean the circular overlap in the contig?

I am not aware of a mechanism which would create a false duplication, a collapse is more likely in assembly. The only thing I can think of would be an undetected 1d^2 read but that should make the repeat inverted. Have you checked the read mappings across the region to see if any reads have a duplication in them?

**Comment by nevergerome** [comment]
Thanks for your reply! I suppose my reference sequence must be wrong. I have a 90kb read spanning the repeat, so this must be a true repeat. 

Just as a final question, if I am running an assembly with many plasmids, which have identical segments of DNA, are there parameters I can change to prevent two different plasmids being merged into a single contig?

**Comment by skoren** [comment]
Depends on how similar the segments are. If they really are 100% identity they won't get resolved unless you get a spanning read and the common region will get collapsed. You can use the heterozygous parameters from the FAQ to try to separate close regions but it likely won't work if the divergence is less than about 1.5-2%.
