### ISSUE TITLE
trioCanu on test data

### ISSUE THREAD

**Issue by chengroup** [marbl/canu#976]
Hi,

When I run trioCanu module on the official test data and found the error occurred in the correlation process. The truncated copy of error log is:

```
- ./correctReads.sh 58 > ./correctReads.000058.out 2>&1
- ./correctReads.sh 59 > ./correctReads.000059.out 2>&1
- ./correctReads.sh 60 > ./correctReads.000060.out 2>&1
- ./correctReads.sh 61 > ./correctReads.000061.out 2>&1
- ./correctReads.sh 62 > ./correctReads.000062.out 2>&1
- 
- -- Finished on Wed Jun 27 18:39:33 2018 (1554 seconds) with 1161.514 GB free disk space
- ----------------------------------------
- --
- -- Read correction jobs failed, retry.
- --   **job 2-correction/results/0043.cns FAILED.**
- --   **job 2-correction/results/0056.cns FAILED.**
- --
- --
- -- Running jobs.  Second attempt out of 2.
-
- -- Starting 'cor' concurrent execution on Wed Jun 27 18:39:33 2018 with 1161.514 GB free disk space (2 processes; 3 concurrently)
- 
- cd correction/2-correction
- ./correctReads.sh 43 > ./correctReads.000043.out 2>&1
- ./correctReads.sh 56 > ./correctReads.000056.out 2>&1
- 
- -- Finished on Wed Jun 27 18:40:43 2018 (70 seconds) with 1161.514 GB free disk space
- ----------------------------------------
- --
- -- Read correction jobs failed, tried 2 times, giving up.
- --   job 2-correction/results/0043.cns FAILED.
- --   job 2-correction/results/0056.cns FAILED.
- --
- 
- ABORT:
- ABORT: Canu 1.7.1
- ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
- ABORT: Try restarting.  If that doesn't work, ask for help.
- ABORT:
- 
- -- Finished on Wed Jun 27 18:40:43 2018 (4487 seconds) with 1161.514 GB free disk space
- ----------------------------------------
- 
- ERROR:
- ERROR:  Failed with exit code 1.  (rc=256)
- ERROR:
- 
- CRASH:
- CRASH: Canu 1.7.1
- CRASH: Please panic, this is abnormal.
- ABORT:
- CRASH:   Failed to run canu  on haplotype O157.
- CRASH:
- CRASH: Failed at /home/csy/Downloads/canu-1.7.1/Linux-amd64/bin/trioCanu line 508.
- CRASH: 
- CRASH: No log file supplied.
- CRASH:
- 
```
Because both reads of 0043 and 0056 were reported to be error, I checked the Result folder in '2-correction' and found that "0043.WORKING.cns" and "0056.WORKING.cns" files were present instead of the expected "0043.cns" and "0056.cns" .  

Thanks

**Comment by skoren** [comment]
What is in the failed job logs (e.g. ```haplotypeO157/2-correction/*43.out```).

**Comment by chengroup** [comment]
Hi Skoren,

I checked the two .out files and found the information:

`Running job 43 based on command line options.
./correctReads.sh: line 331: 14087 Aborted                 (core dumped) $bin/falconsense -G $gkpStore -C ../asm.corStore -b $bgn -e $end -r ./asm.readsToCorrect -t 4 -cc 4 -cl 1000 -oi 0.7 -ol 500 -p ./results/$jobid.WORKING > ./results/$jobid.err 2>&1

Running job 56 based on command line options.
./correctReads.sh: line 331: 14088 Aborted                 (core dumped) $bin/falconsense -G $gkpStore -C ../asm.corStore -b $bgn -e $end -r ./asm.readsToCorrect -t 4 -cc 4 -cl 1000 -oi 0.7 -ol 500 -p ./results/$jobid.WORKING > ./results/$jobid.err 2>&1`

I also tried to filter out the short reads < 500 bp and run again, the failed reports were both 43 job and 56 job. Why just the two jobs failed whiled others not.

Additionally, I tested your Prototype code on example data (https://github.com/skoren/triobinningScripts) and found that the ambiguous reads were not fed to the following Canu assemblies. Why not? Could I simultaneously put these ambiguous reads into the two haplotype sets for assembly?

Thanks,
Shiyi

**Comment by skoren** [comment]
You could include the ambiguous reads into both sets which the automated pipeline will do if they make up a sufficient fraction of the data (5% by default). In this test case, you can see from the output the unclassified reads are all short and represent a very small fraction of the input.

As for the crash, there should be more logging before the part you posted indicating where in the code the error was. Once thing to confirm is that your input data downloaded OK, the MD5s for the input files should be:
```
64c8befea83d043344bdff7c43b04a71  F1.fasta
69920456a2ef25fc3e89cdcb604861ed  K12.parental.fasta
792d0af43740b3534516e8f73ead8a35  O157.parental.fasta
```

**Comment by chengroup** [comment]
Yes, I just checked the MD5 values and found there are inconsistent. I will try again. Thank Skoren for your help.
