### ISSUE TITLE
Canu failing at correction step

### ISSUE THREAD

**Issue by ggargAUS** [marbl/canu#977]
Hi,

Canu is failing at correction step with following errors :

BEGIN CORRECTION
--
--
-- Overlap store sorting jobs failed, tried 2 times, giving up.
--   job correction/BGA_4.ovlStore.BUILDING/0032 FAILED.
--   job correction/BGA_4.ovlStore.BUILDING/0033 FAILED.
--   job correction/BGA_4.ovlStore.BUILDING/0050 FAILED.
--   job correction/BGA_4.ovlStore.BUILDING/0051 FAILED.
--   job correction/BGA_4.ovlStore.BUILDING/0053 FAILED.
--   job correction/BGA_4.ovlStore.BUILDING/0078 FAILED.
--   job correction/BGA_4.ovlStore.BUILDING/0079 FAILED.
--   job correction/BGA_4.ovlStore.BUILDING/0080 FAILED.
--   job correction/BGA_4.ovlStore.BUILDING/0081 FAILED.
[BGA_4.report.txt](https://github.com/marbl/canu/files/2145243/BGA_4.report.txt)
[canu.out.txt](https://github.com/marbl/canu/files/2145244/canu.out.txt)

Can't understand which log files to check.

Please help. Thanks

**Comment by skoren** [comment]
There should be more information in the ```correction/BGA_4.ovlStore.BUILDING/logs/2-sort.*.out``` files, in particular 32 or 33. If you can post one of those it should have more details of what happened.

**Comment by ggargAUS** [comment]
32 log file : 

Finding overlaps.
  found    1002184 overlaps in './bucket0003/sliceSizes'.
  found    1475531 overlaps in './bucket0007/sliceSizes'.
  found    1720515 overlaps in './bucket0011/sliceSizes'.
  found    1772680 overlaps in './bucket0015/sliceSizes'.
  found    1984745 overlaps in './bucket0019/sliceSizes'.
  found    1390421 overlaps in './bucket0022/sliceSizes'.
  found     793984 overlaps in './bucket0023/sliceSizes'.
  found    2444111 overlaps in './bucket0026/sliceSizes'.
  found    2586055 overlaps in './bucket0030/sliceSizes'.
  found    2672995 overlaps in './bucket0034/sliceSizes'.
  found    2778684 overlaps in './bucket0038/sliceSizes'.
  found    2162015 overlaps in './bucket0042/sliceSizes'.
  found     578712 overlaps in './bucket0046/sliceSizes'.
  found     392170 overlaps in './bucket0050/sliceSizes'.
  found     527520 overlaps in './bucket0058/sliceSizes'.
  found     483488 overlaps in './bucket0062/sliceSizes'.
  found     549698 overlaps in './bucket0070/sliceSizes'.
  found     532075 overlaps in './bucket0073/sliceSizes'.
  found     573470 overlaps in './bucket0076/sliceSizes'.
  found     365127 overlaps in './bucket0079/sliceSizes'.
  found     389073 overlaps in './bucket0082/sliceSizes'.
  found     527036 overlaps in './bucket0085/sliceSizes'.
  found     591433 overlaps in './bucket0088/sliceSizes'.
  found     411695 overlaps in './bucket0090/sliceSizes'.
  found     219644 overlaps in './bucket0091/sliceSizes'.
  found     713073 overlaps in './bucket0093/sliceSizes'.
  found     727142 overlaps in './bucket0096/sliceSizes'.
  found     832676 overlaps in './bucket0099/sliceSizes'.
  found     691084 overlaps in './bucket0102/sliceSizes'.
  found     455943 overlaps in './bucket0105/sliceSizes'.
  found     486563 overlaps in './bucket0108/sliceSizes'.
  found     564935 overlaps in './bucket0111/sliceSizes'.
  found     639136 overlaps in './bucket0114/sliceSizes'.
  found     714461 overlaps in './bucket0117/sliceSizes'.
  found     837194 overlaps in './bucket0120/sliceSizes'.
  found     720729 overlaps in './bucket0123/sliceSizes'.
  found     603725 overlaps in './bucket0126/sliceSizes'.
  found     624923 overlaps in './bucket0128/sliceSizes'.
  found    1258147 overlaps in './bucket0130/sliceSizes'.
  found    1451996 overlaps in './bucket0132/sliceSizes'.
  found    1408052 overlaps in './bucket0134/sliceSizes'.
  found    2008851 overlaps in './bucket0136/sliceSizes'.
  found    2474393 overlaps in './bucket0138/sliceSizes'.
  found   40914838 overlaps in './bucket0140/sliceSizes'.
  found   22530119 overlaps in './bucket0141/sliceSizes'.
  found   18743395 overlaps in './bucket0142/sliceSizes'.
  found    9979187 overlaps in './bucket0143/sliceSizes'.
ERROR:  Overlaps need 4.12 GB memory, but process limited (via -M) to 4 GB.

**Comment by skoren** [comment]
Interesting, looks like it is mis-calculating how much memory it will use. 

Change the ```correction/BGA_4.ovlStore.BUILDING/scripts/2-sort.sh``` to have ```-M 6``` instead of ```-M 4``` and then either run the failed jobs manually on a node with at least 6gb of ram or edit the ```correction/BGA_4.ovlStore.BUILDING/scripts/2-sort.jobSubmit-01.sh``` to only submit the failing jobs (```-a 32,33,50,51,53,78,79,80,81```). Make sure to remove any ```*.ovs``` files in the store first.

**Comment by ggargAUS** [comment]
Sorry I can't see any *.ovs files in the store.

**Comment by ggargAUS** [comment]
when I am trying to run failing jobs manually, the job is not running at all

**Comment by skoren** [comment]
How are you running the jobs manually? The have to be run within the ovlStore.BUILDING folder and either way should output something.

**Comment by ggargAUS** [comment]
It worked. Thanks for your help
