### ISSUE TITLE
Assembly Pacbio reads from certain region of BAM

### ISSUE THREAD

**Issue by jiadong324** [marbl/canu#978]
Dear all,

I want to assembly a certain region of reads from blasr aligned BAM file. And the assembled reads will be used to draw dotplot towards the sequence from this region. I am wondering if CANU is able to complete this task.

Thanks and looking forward to any suggestions!

**Comment by skoren** [comment]
I'm not sure what you're intending to use Canu for? Assembly of a targeted region you select by mapping? Then yes, it can do that as long as you provide the subset reads in fastq/fasta formats.
