### ISSUE TITLE
Trouble Generating Small Genome Assembly

### ISSUE THREAD

**Issue by snunzi** [marbl/canu#979]
I am having issues generating an assembly after trying many different parameter combinations. I am trying to assemble a very small virus genome (~9795bp), and should have plenty of coverage to do this with ~25,000 reads. My read lengths are pretty short with average length of 1,000bp, and when canu is run with default parameters only ~50 reads get past the correction stage, and no contigs are assembled. I set the correction very lenient so that most reads would pass for contig assembly, but still got nothing assembling.  I have included the commands used below and the log file generated. I see almost all reads are classified "repeat-cont"...but I'm not sure what this means in terms of genome assembly? Any tips of tweaking parameters so that reads assemble would be greatly appreciated, or any insight into why things are not assembling with my current data and run parameters.

canu version and os: Canu release v1.5 run on  linux (centos 7)

COMMANDS:

canu -correct -p test genomeSize=9795 -nanopore-raw test_mapped.fastq gnuplotTested=true -minReadLength=500 -minOverlapLength=100 corOutCoverage=5000 corMinCoverage=0 corMhapSensitivity=high

canu -trim -p test genomeSize=9795 -nanopore-corrected test.correctedReads.fasta.gz gnuplotTested=true

canu -assemble -p test -d canu_default genomeSize=9795 -nanopore-corrected test.trimmedReads.fasta.gz gnuplotTested=true

[PPV.report.txt](https://github.com/marbl/canu/files/2150511/PPV.report.txt)

**Comment by skoren** [comment]
Version 1.5 is over a year old and would commonly filter short sequences like this out of the main assembly. Your genome is likely in the unassembled.fasta file (see issue #523 for one example). You could try the parameter changes suggested there or, better yet, upgrade to 1.7.1 instead.

I don't think you need all the extra correction parameters, I'd expect ```minReadLength=500 minOverlapLength=100``` would be sufficient.
