### ISSUE TITLE
Are QVs in fastq files actually of any use to Canu?

### ISSUE THREAD

**Issue by e-sevin** [marbl/canu#98]
Hi,

I'm pretty sure this topic doesn't deserve a dedicated issue, but I can't seem to find the info and do not know where else to ask the question. Which is, by the way:
Does Canu actually make any use of the QVs in fastq-formated files? Or is it just an OK format to use, but basically, you're as good using (lighter) fasta files?
It seemed to me in CA they were, but maybe I got the whole thing confused with another assembler...
Thanks, hope this question doesn't take too much of your time!

**Comment by brianwalenz** [comment]
Not a bad question, and we should probably document it.  They're not used, and we don't really have plans to support them.
