### ISSUE TITLE
Hi-C scaffolding with canu assembly

### ISSUE THREAD

**Issue by ersgupta** [marbl/canu#982]
Hi, do you have any recommendations for the best Hi-C scaffolder for canu assemblies?

I have 2 assemblies one with falcon and one with canu (Similar assembly size after deduplicating canu assembly).

I used SALSA for Hi-C scaffolding, which worked for falcon but did not join any scaffolds for canu.

**Comment by skoren** [comment]
We typically use either 3D-DNA or Salsa2. If you haven't already, you need to run Arrow to polish the assemblies (depending on how you ran falcon it may already be done) because not running it will affect the mappability of HiC data.

**Comment by ersgupta** [comment]
You mean run Arrow with canu assembly (de-duplicated)? or with falcon? Falcon assembly worked well with Hi-C data.

**Comment by skoren** [comment]
You would run arrow on the full assembly, not the deduplicated one. You can also provide the canu gfa file to SALSA to improve Hi-C scaffolding.

**Comment by ersgupta** [comment]
Ok.
For SALSA though, I use the deduplicated assembly, so can I use the gfa file of complete assembly with SALSA when I use de-duplicated assembly?

**Comment by skoren** [comment]
Yes, you can

**Comment by ptranvan** [comment]
Hi, regarding this question:

1) After polishing with Arrow, the header name is changed. example:

After canu, the contig file:

`>tig00000004 len=44211 reads=77 covStat=119.33 gappedBases=no class=contig suggestRepeat=no suggestCircular=no`

and after arrow:

`>tig00000004|arrow`

If I provide the initial GFA with this Arrow contigs to SALSA, will it be recognized ?
