### ISSUE TITLE
Canu output assembly greater than estimated genome size

### ISSUE THREAD

**Issue by ggargAUS** [marbl/canu#983]
Estimated size of my genome is around 600 Mb but Canu assembly is greater then 700Mb. 

Any explanation ?

I used the following command to run Canu on slurm system : 

canu -p test \
        -d genome \
        genomeSize=600m \
        useGrid=true gridEngine=slurm \
        gridOptions="--time=160:00:00" \
        -pacbio-raw pacbio_raw.fastq

Assembly finished with some overlap jobs needs to be run manually as discussed in my other raised issues.

Thanks for the help.

**Comment by skoren** [comment]
Multiple reasons, your estimate could be incorrect or there are highly heterozygous regions which are split out into both haplotypes in the assembly (see the FAQ: https://github.com/marbl/canu/blob/master/documentation/source/faq.rst#what-parameters-can-i-tweak).  You can look at gene content (duplicated genes) or coverage to see which it is. The FAQ has suggestions on how to remove the duplication in the assembly as well.
