### ISSUE TITLE
Canu unitigging/overlaps step failed due to time limit

### ISSUE THREAD

**Issue by icruz1989** [marbl/canu#986]
Hello, I was running Canu, and all was good until unitigging step. I got this message from the program about the time limit. Should I have to re-run Canu? Canu was running over one week to complete the assembly
 
slurmstepd: error: *** JOB 4465 ON compute-0-6 CANCELLED AT 2018-07-03T00:23:44 DUE TO TIME LIMIT
Output
[canu_out_13.txt](https://github.com/marbl/canu/files/2159003/canu_out_13.txt)

In this step Canu failed:

[unitigging:overlaps.txt](https://github.com/marbl/canu/files/2159004/unitigging.overlaps.txt)

This is the command that I used to run Canu, and I do not if it is because I set 80:00:00 in the grid options and this was not enough

canu -d ensamble_tic23_pacbio -p datura_tic23 genomeSize=1.5g gridOptionscormhap="--mem=40g" merylMemory=62 batMemory=62 gridOptions="--time=80:00:00 --partition=FAST" gnuplotTested=true -pacbio-raw /home/icruz/data/secuencias_pacbio/bamfiles_tic_g/tic23.subreads.fastq 1>run2.log &

Thank you

**Comment by skoren** [comment]
Based on the output you posted, I don't think Canu was actually submitting jobs to the grid but just running on the single node you submitted it to. Over a week for a 1.5gb genome on a single machine is expected. If you re-run the same command, it will resume where it left off.

If you want it to use the cluster, post the full canu output log, it should have more information on the detected resources and why jobs weren't submitted to the cluster. Your overlap report also doesn't look very promising, lots of reads with no overlaps on the ends, low fraction of unique overlaps, and coverage below 10x. I don't expect a very good assembly.

**Comment by icruz1989** [comment]
I rerun Canu and, I set in gridoptions more time, and Canu finally has finished. I had a considerable number of reads without being part of the first assembly. I ran Quast for assembly evaluation, and this was de output. I am rerunning Canu for another individual genome. 

I am using Canu as part of a Pipeline where I will use Illumina reads to improve the Canu assembly. I used Soapdenovo to assembly Illumina reads and the Canu output was much better than Soap even though we do not have enough coverage for PacBio reads.

Quast output (canu asssembly)
All statistics are based on contigs of size >= 500 bp, unless otherwise noted (e.g., "# contigs (>= 0 bp)" and "Total length (>= 0 bp)" include all contigs).

Assembly                    datura_tic23.contigs
# contigs (>= 0 bp)         47338               
# contigs (>= 1000 bp)      47338               
# contigs (>= 5000 bp)      41591               
# contigs (>= 10000 bp)     33270               
# contigs (>= 25000 bp)     15532               
# contigs (>= 50000 bp)     4692                
Total length (>= 0 bp)      1111011294          
Total length (>= 1000 bp)   1111011294          
Total length (>= 5000 bp)   1093107853          
Total length (>= 10000 bp)  1030302617          
Total length (>= 25000 bp)  736054033           
Total length (>= 50000 bp)  358179681           
# contigs                   47338               
Largest contig              329416              
Total length                1111011294          
GC (%)                      37.94               
N50                         35071               
N75                         20140               
L50                         9443                
L75                         19860               
# N's per 100 kbp           0.00

**Comment by brianwalenz** [comment]
Oooh!  Poisonous flowers!  Do try to get more PacBio reads!
