### ISSUE TITLE
TrioCanu & Polishing

### ISSUE THREAD

**Issue by bfr42** [marbl/canu#987]
Hello,

I used TrioCanu to compute some nice assemblies. However, now I want to polish them. How do you recommend to do this? I thought of using blasr, arrow and the binned reads plus the unassigned ones. But the binned reads are only present in fasta format. Do you convert the binned reads somehow to bam format because blasr/arrow needs raw reads in bam format? Or can I use something like minimap2 and then arrow? Also, is running two times the polishing step better and recommended for a Canu assembly?

Thank you!

**Comment by skoren** [comment]
Generally, you want to subset the bam files using the names in the fasta files. There is a dataset command within SMRTportal which lets you do this. We typically do run two rounds of arrow on the assembly.

The arrow wrapper I have here: https://github.com/skoren/ArrowGrid can take the readNames.txt input from the gatekeeper store. So, say you have an assembly named haplotypeA, you can pass haplotypeA/asm.gkpStore/readNames.txt to arrow.sh along with the other parameters (something like ```sh arrow.sh input.fofn arrow asm.contigs.fasta readNames.txt```). It will handle subsetting the original bams by the read names for you.
