### ISSUE TITLE
Assembling only a few reads. 

### ISSUE THREAD

**Issue by conchoecia** [marbl/canu#989]
Hi All,

I'm using 1.7 - not sure which exact release.

I have a unique problem: I want to use canu to assemble only small regions for which I will have as few as two reads. In these cases I sometimes just end up with a single corrected read, and other times end up with several corrected reads.

When there are very few corrected reads I get `ERROR: Failed with exit code 136.` at the overlapper step. Do you know what would cause this? In this specific case there were only 4 reads after correction.

Any advice that you might have for how to use `canu` to only assemble a few reads from a single locus would be much appreciated.

Thank you,
Darrin

[most_of_log.txt](https://github.com/marbl/canu/files/2160746/most_of_log.txt)

```
-- Starting command on Tue Jul  3 12:15:31 2018 with 9452.651 GB free disk space

    cd trimming/1-overlapper
    /usr/local/bin/canu-1.7.1/Linux-amd64/bin/overlapInCorePartition \
     -G  ../Haplotig6763.gkpStore \
     -hl 85312000 \
     -rl 1000000000 \
     -ol 500 \
     -o  ./Haplotig6763.partition \
    > ./Haplotig6763.partition.err 2>&1

-- Finished on Tue Jul  3 12:15:31 2018 (lickety-split) with 9452.651 GB free disk space
----------------------------------------

ERROR:
ERROR:  Failed with exit code 136.  (rc=34816)
ERROR:
```

**Comment by conchoecia** [comment]
Hi Brian,

The file `trimming/1-overlapper/Haplotig6763.partition.err` was not present, so I ran the `overlapInCorePartition` command I found in the logs.

```
/usr/local/bin/canu-1.7.1/Linux-amd64/bin/overlapInCorePartition \
  -G ../Haplotig6763.gkpStore \
  -hl 85312000 \
  -rl 1000000000 \
  -ol 500 \
  -o ./Haplotig6763.partition
```

I received this error:

```
Configuring for:
  hash table:       85312000 bases.
  read stream:    1000000000 bases.


       Raw          Raw  Corrected    Corrected    Trimmed      Trimmed
     Reads        Bases      Reads        Bases      Reads        Bases
---------- ------------ ---------- ------------ ---------- ------------

Failed with 'Floating point exception'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::97 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
overlapInCore/overlapInCorePartition.C::171 in _Z15loadReadLengthsP7gkStoreRSt3setIjSt4lessIjESaIjEERjS7_S6_S7_S7_()
overlapInCore/overlapInCorePartition.C::447 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
./manual_cmd.sh: line 6: 90063 Floating point exception(core dumped) /usr/local/bin/canu-1.7.1/Linux-amd64/bin/overlapInCorePartition -G ../Haplotig6763.gkpStore -hl 85312000 -rl 1000000000 -ol 500 -o ./Haplotig6763.partition
```

I'm wondering if the floating point exception is coming from some array not being occupied or something? 

Thanks,
Darrin

**Comment by brianwalenz** [comment]
It's fixed in the unreleased tip version.  That seems to be stable, but it isn't possible to upgrade and continue your assemblies.  You'd need to start over.

If you want to fix your version, change file `src/overlapInCore/overlapInCorePartition.C` at line 134 from
```
  uint32  reportInterval = numReads / 40;
```
to
```
  uint32  reportInterval = numReads / 39 + 1;
```
then, in `src/`, `make` to rebuild the binaries.
