### ISSUE TITLE
unitigging.html

### ISSUE THREAD

**Issue by woodoo46** [marbl/canu#99]
First of all, thanks for helping to choose the parameters. We finished 2nd run on 27X coverage 3G genome. We had

lenContig ng50      393884 bp   lg50    1780   sum 1500229865 bp

So it reached 400kb compared with around 70kb. I then examined the output file, I found that in unitigging.html. The following sections are empty:

Overlap Error Adjustment
Unitigs
Consensus
Final Outputs

Did I miss any parameters turning one?

Thanks.

**Comment by brianwalenz** [comment]
You didn't miss anything.  That report is incomplete, and seems to be perpetually at the bottom of the to do list.
