### ISSUE TITLE
If the machine out of memory, do I need to rerun the existing command?

### ISSUE THREAD

**Issue by huangziyan11111** [marbl/canu#991]
I am running the overlap step of assemble, while cause the other command cost too much memory, so the machine is out of memory once. So I want to know do I need to rerun the command?
the command is like:
```
/psd/biosoft/canu-1.7/Linux-amd64/bin/overlapInCore -t 12 -k 22 -k ../0-mercounts/CC.ms22.frequentMers.fasta --hashbits 23 --hashload 0.75 --maxerate 0.050 --minlength 500 -h 937855-956380 -r 1-789833 --hashstrings 18526 --hashdatalen 341259773 -o ./001/000062.ovb.WORKING -s ./001/000062.stats ../CC.gkpStore
```

**Comment by brianwalenz** [comment]
Rerunning Canu with the same options as before will detect any incomplete results are rerun commands as needed.
