### ISSUE TITLE
cormhap uses more cpus than requested and gets killed by grid

### ISSUE THREAD

**Issue by BurlEarl** [marbl/canu#993]
To get around the PBSpro/select statement problem I tried specifying resources for each step using values from canu.out. 

Command used (Canu version 1.7.1):
```
canu -p $SAMPLE\_new5 -d ~/WorkingDir/assemblies/$SAMPLE\_canu_new5 \
genomeSize=500m -pacbio-raw /home/u14/earlm1/WorkingDir/data/PacBio/$SAMPLE/reads/$SAMPLE\_PacBio_new?.fastq \
gridEngineMemoryOption="-l walltime=30:00:00" \
gridEngineThreadsOption="-q windfall -W group_list=earlm" \
stageDirectory=/tmp/\$USER\_\$PBS_JOBID \
gridOptionsExecutive="-l select=1:mem=12gb:ncpus=2" \
gridOptionsMERYL="-l select=1:mem=64gb:ncpus=16" \
gridOptionsCORMHAP="-l select=1:mem=26gb:ncpus=4" \
gridOptionsOBTOVL="-l select=1:mem=16gb:ncpus=4" \
gridOptionsUTGOVL="-l select=1:mem=16gb:ncpus=4" \
gridOptionsOVB="-l select=1:mem=4gb:ncpus=1" \
gridOptionsOVS="-l select=1:mem=16gb:ncpus=1" \
gridOptionsRED="-l select=1:mem=8gb:ncpus=4" \
gridOptionsOEA="-l select=1:mem=4gb:ncpus=1" \
gridOptionsBAT="-l select=1:mem=168gb:ncpus=28" \
gridOptionsGFA="-l select=1:mem=16gb:ncpus=16"
```
Many cormhap jobs get killed because they use too many cpus even though mhap has the "--num-threads =4" argument:
```
Running job 92 based on PBS_ARRAY_INDEX=92 and offset=0.
Fetch blocks/000039.dat

Running block 000038 in query 000092

Running with these settings:
--filter-threshold = 5.0E-6
--help = false
--max-shift = 0.2
--min-olap-length = 500
--min-store-length = 0
--no-rc = false
--no-self = false
--no-tf = false
--num-hashes = 256
--num-min-matches = 3
--num-threads = 4
--ordered-kmer-size = 14
--ordered-sketch-size = 1000
--repeat-idf-scale = 10.0
--repeat-weight = 0.9
--settings = 0
--store-full-id = true
--supress-noise = 0
--threshold = 0.8
--version = false
-f = 
-h = false
-k = 16
-p = 
-q = queries/000092
-s = ./blocks/000038.dat

Processing files for storage in reverse index...
Current # sequences loaded and processed from file: 5000...
...
Current # sequences loaded and processed from file: 125000...
Current # sequences loaded and processed from file: 130000...
Current # sequences loaded and processed from file: 135000...
Current # sequences loaded and processed from file: 140000...
=>> PBS: job killed: ncpus 6.03 exceeded limit 5 (sum)
```

Even increasing the requested cores via ```gridOptionsCORMHAP="-l select=1:mem=60gb:ncpus=10"```, the jobs still fail.
```
Current # sequences loaded and processed from file: 120000...
Current # sequences loaded and processed from file: 125000...
Current # sequences loaded and processed from file: 130000...
Current # sequences loaded and processed from file: 135000...
Current # sequences loaded and processed from file: 140000...
=>> PBS: job killed: ncpus 10.80 exceeded limit 10 (sum)
```

Unfortunately, something about when the jobs are killed, canu thinks they are completed, skips them, then says they failed to complete.

I think there is something fundamental I do not understand.  I thought maybe PBS was only allowing me to use a total of 4 cpus for all the array jobs or something (which our admin assured me is not happening), but I already tried limiting the number of concurrent array jobs(mentioned in #912).  Unsurprisingly, that doesn't seem to help.

Has any one seen this kind of behavior out of mhap before?  Is the num-threads argument ignored? I think the problem is intrinsic to the job because it seems to be the same mhap queries which keep being a problem.  

Any help would be greatly appreciated. 

Thanks,
Earl

**Comment by skoren** [comment]
It's your JVM config not mhap. It's likely launching extra threads to run garbage collection. I'd guess the default is the throughput parallel collector which defaults to the # of cores on the machine. Try explicitly setting ```-XX:+UseParallelGC -XX:ParallelGCThreads=4```.  If you set the environment variable JAVA_TOOL_OPTIONS to those values it should get picked up by the JVM (as long as PBS passes through your environment to the running job).

**Comment by BurlEarl** [comment]
Wow, thanks for the blazing fast response!

Alright, I just put ```export JAVA_TOOL_OPTIONS='-XX:+UseParallelGC -XX:ParallelGCThreads=4'``` in a script that will get sourced for each job.  It needs to get through the precompute step before I know if it works.  

Do you think this might be a problem with the blocks being too big for the amount of mem that java is given?  I had a problem with garbage collection when pollishing using Pilon and getting close to -Xmx.  It basically spent ~100% of the cpus time on GC.  I guess in that case it didnt crash because I was asking for a whole node.  

Will update when precompute finishes.

**Comment by BurlEarl** [comment]
It got through cormhap without issue.  Thanks a bunch.  

In then end I just put ```export JAVA_TOOL_OPTIONS='-XX:+UseParallelGC -XX:ParallelGCThreads=4'``` in my bashrc file.  I'm guessing it could slow down some other Java script which needs to do a bunch of garbage collecting.  Is there another way to pass environmental variables through canu to PBS?

Thanks!
Earl

**Comment by brianwalenz** [comment]
You can try setting `java=java -XX:+UseParallelGC -XX:ParallelGCThreads=4` in ~/.canu or in canu.defaults in the same directory as the canu executable.

**Comment by BurlEarl** [comment]
Awesome.  Brian, I'll try your suggestion when I start another assembly in a couple days and post the results for future viewing but I think this issue is pretty much solved for me.

Thanks to both of you.
Earl
