### ISSUE TITLE
long running time on unitig/1-overlap

### ISSUE THREAD

**Issue by imneuro** [marbl/canu#994]
Hi, 

The general question is unitig/1-overlap runs for a week. It is unexpected.

The command I used is 
$ /opt/canu/bin/canu -p CC -d CC genomeSize=650m -pacbio-raw /shared/qi65037/fasta/CC.fasta gridOptionsJobName=CC -s test_spec

$more test_spec
useGrid=1

version: Canu-1.6 
system: Linux ip-10-30-3-9 3.13.0-116-generic #163-Ubuntu SMP Fri Mar 31 14:13:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

This input fastq file is 59GB.  I assembled another genome with input file size 39GB and genomeSize=550m, same pacbio data, the whole assembly finished in one day on the same machine with same amount of computational resource required.  This assembly so far has been running for more than 4 weeks. I wonder if this is normal or is there anything I can do to speed it up.

Thanks,
Xin

**Comment by skoren** [comment]
The runtime depends on the repetitiveness of your genome. You can manually lower the threshold for repetitive k-mers to speed up the run (see issue #947, #646 addressing the same question). You'd have to restart the unitigging step (```canu -assemble -p CC -d CC2 genomeSize=650m -pacbio-corrected CC/asm.trimmedReads.fasta.gz gridOptionsJobName=CC2 -s test_spec ovlMerThreshold=500```) to try this.

**Comment by skoren** [comment]
That command won't change, the size of the ```../0-mercounts/CC.ms22.frequentMers.fasta```  file will.

**Comment by imneuro** [comment]
Indeed, the file size increased from 1.1M to 71M after add the option. Is this what you expected?
-rw-rw-r-- 1 ubuntu ubuntu  71M Jul 16 16:42 CC2/unitigging/0-mercounts/CC.ms22.frequentMers.fasta
-rw-rw-r-- 1 ubuntu ubuntu 1.1M Jul  5 18:42 CC/unitigging/0-mercounts/CC.ms22.frequentMers.fasta

**Comment by skoren** [comment]
Yes, the header will have the count of the k-mers in the file. As long as you see lines like
```
>501
```
it worked correctly.

**Comment by imneuro** [comment]
It really speeds up! A side question but important one as following:

How this "ovlMerThreshold=500" will affect the assemble result on these repeated region?  Any principle I can follow to adjust the parameter? This CC plant genome has 40-50% of repeated region estimated by known information.  I have another plant genome that has 70% repeated region, shall I make the same adjustment in the finally unitig stage or do something earlier in the correction stage? Such as in https://github.com/marbl/canu/issues/855

**Comment by skoren** [comment]
It will still resolve repeats as long as they have some unique anchoring k-mer. We plan to make the threshold lower in a future release so I think your assembly should be OK. Your main issue if you don't make the adjustment in correction will be disk usage so if you are running low on space you can make the adjustment in correction too.
