### ISSUE TITLE
Can I find which reads canu used for each assembly?

### ISSUE THREAD

**Issue by Omer-K** [marbl/canu#996]
I've run canu over several cell lines to come up with assemblies of a gene.
In one cell line it outputted only "truncated" contigs. Namely, these contigs aligned to the gene with a missing piece of ~1kb, which possibly indicate this cell line as having a structural variant.

Can I Isolate the reads which canu used for a specific assembly?
For purposes of aligning these against the reference.

**Comment by skoren** [comment]
The layout files will tell you where each read went. You want the readToTig file:
```
#readID	tigID	coordType	bgn	end
677083	4	ungapped	0	23436
2343812	4	ungapped	12469	1223
```
In this case read ids 677083 and 2343812 ended up in tig00000004 and the coordinates are listed at the end (read 2343812 is reverse-complemented). You need to do a bit of work to get the original id of 2343812, look in the gkpStore/readNames.txt file, there you should find:
```
2343812	m54033_180126_223601/39780749/39781_51526 id=4778961_0 id=2354708 clr=181,11399
```
which gives you the original read (PacBio in this case) id.
