### ISSUE TITLE
3 peaks in per base coverage plot

### ISSUE THREAD

**Issue by michieitel** [marbl/canu#997]
Hi!

Not sure this is the right spot to discuss my issue. If this is the wrong place I'd appreciate a link to the correct one.

I have problems interpreting the results from our assemblies. We have sequenced an animal with nanopore and Illumina reads. I first performed Canu v1.7.1 assemblies of subsets of the nanopore reads to see effects on the outcome. Here I generated individual assemblies with all reads >1kb, >2kb, etc. up to 20kb (with a jump from 15kb to 20kb straight). Afterwards, I corrected each Canu assembly with the Illumina reads each with 10 iterations of Pilon error correction (using Bowtie2 mapping). Then I used Bedtools to get histograms for each mapping from the bam files. The results of the per-base coverage plot can be seen on the attached graph (cov on the x- and millions of bases on the y-axis; the number in brackets behind the sets is the rough nanopore coverage based on the 1kb assembly length).

As you can see we have three peaks at coverage ratios of 0.25, 0.5 and 1. First I was interpreting the graph as a triploid organism, but this does not fit to the ratio. One would expect 0.33-0.66-1 for a triploid.

I also performed a mapping of the corrected & trimmed >1kb nanopore reads (generated by Canu) to the raw >1kb read assembly with bwa and also plotted a per base coverage (2nd file).

Any Idea what we see here? Any help in interpreting the results would be highly appreciated. This drives me nuts already...

Thanks for your help.

Michael

[per_base_genome_coverage_canu_err12_pilon10_histo200.pdf](https://github.com/marbl/canu/files/2188450/Avas_per_base_genome_coverage_canu_err12_pilon10_histo200.pdf)

[canu_assembly-1kb_pilon10_bwa_ont2d_trimmed_reads_mapped_bedtool_genomecov_.pdf](https://github.com/marbl/canu/files/2188485/Avastus_canu_assembly-1kb_pilon10_bwa_ont2d_trimmed_reads_mapped_bedtool_genomecov_.pdf)

**Comment by michieitel** [comment]
just realized lines for 1kb and 2kb are missing, but I think the trend is quite obvious ...

Michael

**Comment by skoren** [comment]
Your nanopore mapped reads show only two peaks at 1x and 0.3x which is also a bit strange, you'd expect a peak at 1 and 0.5x if there are heterozygous regions. Are the raw nanopore reads consistent with that? To make sure it's not a mapping artifact, I'd suggest keeping only reads mapping full length and only allow a read to go to its best single location.

Have you looked at the k-mer distributions from either the corrected reads or the illumina reads in something like genome scope to get an idea of heterozygosity/genome size.  Have you checked for contamination in your sample?

**Comment by michieitel** [comment]
Hi Sergey,

thanks for your comments.

> Your nanopore mapped reads show only two peaks at 1x and 0.3x which is also a bit strange, you'd expect a peak at 1 and 0.5x if there are heterozygous regions. 
I agree. That is weird.

> Are the raw nanopore reads consistent with that? 
Good idea. I will also map the raw read.

> To make sure it's not a mapping artifact, I'd suggest keeping only reads mapping full length and only allow a read to go to its best single location.
Also great idea. I will this as well. 

> Have you looked at the k-mer distributions 
No not yet. Will try

> Have you checked for contamination in your sample?
You mean physical (material) contaminations? No was not possible since we got the sample frozen and pulverized it with liquid N2. You think it could be a different organism in here and we have overlaping homo/hetero peaks in the middle peak, and we should in fact see 4?

**Comment by skoren** [comment]
I mean any off-target sequences, could be from whatever the animal ate (depending on if you're using whole animal or not) or handling etc. You can run Mash screen against the DB to look for contamination in the Illumina or Nanopore data.

**Comment by michieitel** [comment]
We're talking of a filter feeder that (most likely) filters bacteria. I do not expect to have other eukaryote material in there in this high amount

**Comment by michieitel** [comment]
can you tell me how to filter the bam file to get only full-length matches? should be some samtools option that I cant find right now

**Comment by brianwalenz** [comment]
Looks like we got sidetracked enjoying our summer (when it's not raining).  I don't know of a method to get full-length matches from bam - it probably involves parsing the CIGAR string, which sounds rather ugly.

Reopen if you've got an update.
