### ISSUE TITLE
max mem-per-cpu for cormhap?

### ISSUE THREAD

**Issue by Phylloxera** [marbl/canu#998]
Here is my command:
~/canu-1.7/Linux-amd64/bin/canu -correct -p gaur_mhap -d /shared/gaur -gnuplotTested=true useGrid=true -batMemory=120 corMhapSensitivity=normal corOutCoverage=100 gridOptionsCORMHAP="--mem-per-cpu=7g" stageDirectory=/scratch/$SLURM_JOBID gridEngineStageOption="--gres=lscratch:250" java=/usr/bin/java8 genomesize=2.8g -pacbio-raw /shared/gaur/gaur.fasta.gz stopAfter=overlap

canu-1.7

amazon AWS grid with SLURM, will introduce autoscaling to the grid later which will likely cause canu to about (future issue :) )

Even though, I submitted as "--mem-per-cpu=7g", the console printed out
...
-- Grid:  cormhap   48 GB   16 CPUs  (overlap detection with mhap)
...
sbatch \
  --mem-per-cpu=4g
...

I'm guessing from this that cormhap won't use more mem-per-cpu even if asked, is that right?

**Comment by skoren** [comment]
No it can use whatever memory you want. The gridOptions parameters control the resource request not the actual usage of the program (http://canu.readthedocs.io/en/latest/tutorial.html#module-tags). In your case it will keep using the same memory for mhap but request 7gb per core. You should see that option in the ```correction/1-overlapper/mhap.jobSubmit-01.sh`` or similar. I think the request you've pasted above is just the executive script. You can specify corMhapMemory=48 or whatever you want to actually increase memory used but if you request more than available on any of your nodes at launch Canu will likely complain that there is nowhere to run the job.
