### ISSUE TITLE
How much mem cormhap uses... follow-up to #998

### ISSUE THREAD

**Issue by Phylloxera** [marbl/canu#999]
canu-1.7; amazon AWS grid with SLURM

my new command:
~/canu-1.7/Linux-amd64/bin/canu -correct -p gaur_mhap -d /shared/gaur -gnuplotTested=true useGrid=true -batMemory=120 corMhapSensitivity=normal corOutCoverage=100 corMhapMemory=120 stageDirectory=/scratch/$SLURM_JOBID gridEngineStageOption="--gres=lscratch:250" java=/usr/bin/java8 genomesize=2.8g -pacbio-raw /shared/gaur/gaur.fasta.gz stopAfter=overlap

so, I replaced gridOptionsCORMHAP="--mem-per-cpu=7g" with corMhapMemory=120
The console output changed to 
-- Grid: cormhap 120 GB 16 CPUs (overlap detection with mhap)

but when I ssh'ed into the compute node, individual cormhap jobs are using no more than 21% of the available memory. Is there some other parameter that needs to be set so that cormhap will utilize more of the available memory?

**Comment by skoren** [comment]
Presumably you have way fewer jobs submitted as a result of the change. The memory will fluctuate and the VM performs best when there is space to grow (so it doesn't spend all the time on GC) so it will adjust to be using more memory like you asked just not 100%.

**Comment by Phylloxera** [comment]
That sounds good. It may take me working on a different cluster with a fixed number of higher memory nodes to see what changes took place as a result... On a local cluster with 64 GB RAM-per-node, stopAfter=overlap subdivided this workload into 108 precompute array jobs and 267 mhap overlap array jobs, and I could see this by typing squeue:

 9172_[169-267]      defq cormhap_ aaron.di PD       0:00      1 (Resources)
              9187      defq canu_gau aaron.di PD       0:00      1 (Dependency)

But on AWS with autoscaling (issues for another day), the overlap array jobs have been allocated (by canu/SLURM?) to multiple jobIDs so when I type squeue, I get:

 192_[27-29]   compute cormhap_ ec2-user PD       0:00      1 (Resources)
          193_[38]   compute cormhap_ ec2-user PD       0:00      1 (Priority)
          194_[40]   compute cormhap_ ec2-user PD       0:00      1 (Priority)
          195_[47]   compute cormhap_ ec2-user PD       0:00      1 (Priority)
          196_[49]   compute cormhap_ ec2-user PD       0:00      1 (Priority)
          197_[55]   compute cormhap_ ec2-user PD       0:00      1 (Priority)
          198_[57]   compute cormhap_ ec2-user PD       0:00      1 (Priority)
          199_[82]   compute cormhap_ ec2-user PD       0:00      1 (Priority)
          200_[92]   compute cormhap_ ec2-user PD       0:00      1 (Priority)
          201_[99]   compute cormhap_ ec2-user PD       0:00      1 (Priority)
         202_[104]   compute cormhap_ ec2-user PD       0:00      1 (Priority)
               203   compute canu_gau ec2-user PD       0:00      1 (Dependency)
            191_25   compute cormhap_ ec2-user  R      26:40      1 ip-172-31-12-18

104 is less than 267... Not sure if 104 represents the total number of mhap overlap array jobs remaining after cormhap ran for a few days and then aborted, or if this is all due to the corMhapMemory increase.
Sorry for the ramble.

**Comment by skoren** [comment]
The only reason you'd end up with multiple IDs is because some jobs finished and so it's only running the failed partitions. The 104 is just the max failed job, doesn't say anything about the max job ID, that should be in one of the the ```canu-scripts/canu.*.out``` files (probably one less than the last one you have there). 

You didn't say you're resuming a run here, you can't change memory in the middle. You'd have to completely remove the 1-overlapper folder since the precompute already subdivided the data into fixed-size chunks.

**Comment by Phylloxera** [comment]
Trying to figure out if this is even worth testing... i.e. even if  there are fewer cormhap jobs, won't those jobs just take longer and overall run time remain similar? Or should overall run time be reduced with higher corMhapMemory?

**Comment by skoren** [comment]
I'd expect it to be similar overall cpu time. It may be faster in wall clock time if your grid takes a while to schedule jobs so fewer large jobs will sit in the queue less than a lot of small jobs.

**Comment by Phylloxera** [comment]
OK, I've got a little comparison running slurm's sacct on a canu run with the default settings (167 precompute jobs, sum of 'Elapsed' = 124H 30M 4S) vs corMhapMemory=490 (11 precompute jobs, sum of 'Elapsed' = 102H 14M 0S). I don't know... is 'Elapsed' wall clock time? Seems like somewhat of a time savings, maybe >15%. I don't yet have any comparisons for 31 vs 413 overlap jobs due to some bad luck (server room power failures and 'harmless' canu ABORT errors after multiple days of running). If I get some comparisons for overlap at some point, I'll come back to this issue and post them.

**Comment by brianwalenz** [comment]
Fewer jobs could also reduce filesystem contention, but finding the balance with the increase in job size is tricky.

What were the 'harmless' abort problems?

If you've moved on, please close the issue.
